### PR TITLE
Keep a copy of anchor ref to preserve highlighted text selection

### LINKED ISSUE #36254: RichText: Unable to add a custom highlight color
### Description

When trying to highlight text with a custom color, the input doesn't accept any new characters, and when trying to delete any character the popup menu closes. It seems to have been introduced with v11.8.0 as in my testing v11.7.1 works correctly (see demo videos).

### Step-by-step reproduction instructions

1. Write some text into a paragraph block
2. Select a part of this text
3. Open the `Highlight` menu from the rich text toolbar
4. Try to apply custom color via the text input (see demo)
5. See how the current value cannot be changed

### Screenshots, screen recording, code snippet

**Current Gutenberg version v11.8.0 (broken):**

https://user-images.githubusercontent.com/1451471/140508249-256d68db-b754-4c47-ae7e-25e735e99903.mov

**Previous Gutenberg version v11.7.1 (working):**

https://user-images.githubusercontent.com/1451471/140508431-830f6fde-bc06-442c-9c29-fd206aa5a631.mov

### Environment info

- WP 5.8.1
- Gutenberg v11.8.0
- Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by alshakero**
## Description
When highlighting a text to change its color, we use `document.currentView.getSelection` to determine what's selected on the screen. But when you try to type in the color you want using the custom color input, you're also discarding the selection you'd made of the text you want to colorize. 

So when `useAnchorRef` goes to look for the `<mark>` element within the selected text, it won't find it, since it's actually looking inside the [input field](https://user-images.githubusercontent.com/17054134/140542315-b79d552b-5003-497b-9286-6a9c569e25c1.png).

This PR proposes caching the truthy value of the selection anchor, so user can select other text (like the color string inside the input) without losing track of the text they want to format.

## How has this been tested?
Luckily, the issue is reproducible on trunk here. This change demonstrably fixes it.

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 

Fixes https://github.com/WordPress/gutenberg/issues/36254 and https://github.com/Automattic/wp-calypso/issues/57687

### CODE REVIEW

**Review by fullofcaffeine — APPROVED** [review]
This tests well!

**Comment by fullofcaffeine** [comment]
@jorgefilipecosta  @ellatrix I’ve tested that this fixes issue https://github.com/WordPress/gutenberg/issues/36254 in `v11.8.0` and from this branch (closer to `trunk` / `11.9.0 RC1`), but I’m not sure if this is how you’d prefer to handle this kind of focus/selection related issue long-term. We can follow up with another iteration afterward, if needed.

**Comment by fullofcaffeine** [comment]
This has been cherry-picked into https://github.com/WordPress/gutenberg/tree/release/11.8.

File: packages/block-editor/src/hooks/use-cached-truthy.js [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+ */
+import { useState, useEffect } from '@wordpress/element';
+
+/**
+ * Keeps an up-to-date copy of the passed value and returns it. If value becomes falsy, it will return the last truthy copy.
+ *
+ * @param {any} value
+ * @return {any} value
+ */
+export function useCachedTruthy( value ) {
```
Comment (youknowriad) [inline packages/block-editor/src/hooks/use-cached-truthy.js:12]: This hook seem a bit misplaced. If we need to be a public API, it should be on the "compose" package (more generic as it has nothing to do with block-editor). But personally, I see it only used once and I'm not sure this hook is very valuable outside that use-case so why not just move it close to its current usage?

**Comment by youknowriad** [comment]
Also was this cherry-picked to 10.9 as well, since 10.9 is now branched, any cherry-pick made to 10.8 should also be made to 10.9 or the commit won't be on the next major release.

**Comment by fullofcaffeine** [comment]
@youknowriad jinx! I just did that, and also released RC2 with it https://github.com/WordPress/gutenberg/releases/tag/v11.9.0-rc.2. Thanks for the reminder, anyway! 🙇🏻
