### PR TITLE
RTC: Fix core/table cell merging

### LINKED ISSUE #76908: RTC: Typing in the same table replaces content
Two users can't simultaneously add content to a table:

https://github.com/user-attachments/assets/8a15fe7b-6b38-4eb9-a4a6-adb1f2a09666

---

The root cause is [`updateYBlockAttribute()`](https://github.com/WordPress/gutenberg/blob/54cc471a56ed022c5fb29bd6a7a7207f9c217382/packages/core-data/src/utils/crdt-blocks.ts#L534-L537) detects `Y.Text` for smart merging of rich text, but calls `createNewYAttributeValue()` with table data types (`array`).

This replaces all data in the table at the same time. This means any user editing a table force-replaces all cells in that table with each update. This leads to the results above, where simultaneous edits result in one user (the one with the lower clientID) to win.

### PR DESCRIPTION
**Pull request by alecgeatches**
## What?

This is a bit risky of a change for late-stage 7.0, so it's intended for post-7.0 merging into Gutenberg. Part of the overall work in https://github.com/WordPress/gutenberg/issues/76915.

Closes https://github.com/WordPress/gutenberg/issues/76908:

https://github.com/user-attachments/assets/ac876d51-5b0d-444d-9b50-e7fa688ef1bd

*Users can not add simultaneous updates to separate cells of the same table*

---

This PR changes how query block attributes like a table `body` are stored in the CRDT document. This gives each table cell its own independent `Y.Text`, so two users editing different cells no longer overwrite each other:

https://github.com/user-attachments/assets/0b338846-3704-4904-b1f7-280b3cab26ff

*Demonstration of correct cell data merging in `core/table`*

## Why?

Previously, the entire table `body` was stored as a single opaque value in the block's `Y.Map`:

```
Y.Map (block attributes)
  └─ "body" → plain JS array   ← entire value replaced on any cell edit
       [
         { cells: [{ content: "A1", tag: "td" }, { content: "B1", tag: "td" }] },
         { cells: [{ content: "A2", tag: "td" }, { content: "B2", tag: "td" }] }
       ]
```

Any cell edit (e.g. modifying "A1") replaced the whole `body` array. With slower HTTP polling, two users typing in different cells of the same table can easily overlap on updates, and Yjs would silently discard one user's edit as `body` is a big non-Y-type blob.

Note that this is related but different from #76597. That PR fixed nested `RichTextData` instances inside table cells that were accidentally being serialized to empty data. This PR improves in a different direction by restructuring the whole table layout in the CRDT to nested Yjs types.

## How?

Previously, we only cared about top-level block `RichText` attributes into `Y.Text`, but other attribute types would get serialized into the CRDT as-is. The change uses the existing `query` property in block attribute schemas to recursively create nested Yjs types. For a table `body` attribute, the new structure looks like this:

**After (deep Yjs types):**
```
Y.Map (block attributes)
  └─ "body" → Y.Array
       ├─ [0] Y.Map (row)
       │    └─ "cells" → Y.Array
       │         ├─ [0] Y.Map (cell)
       │         │    ├─ "content" → Y.Text("A1")   ← independent Y.Text entry
       │         │    └─ "tag" → "td"
       │         └─ [1] Y.Map (cell)
       │              ├─ "content" → Y.Text("B1")   ← independent Y.Text entry
       │              └─ "tag" → "td"
       └─ [1] Y.Map (row)
            └─ "cells" → Y.Array
                 ├─ [0] Y.Map (cell)
                 │    ├─ "content" → Y.Text("A2")
                 │    └─ "tag" → "td"
                 └─ [1] Y.Map (cell)
                      ├─ "content" → Y.Text("B2")
                      └─ "tag" → "td"
```

With this structure, User A editing cell A1 and User B editing cell B2 write to different Y.Text instances, and Yjs can merge them correctly.

To get started reading the code, the best entry point is `updateYBlockAttribute()`, which calls into `mergeYValue()`. This function handles merging or creating new Y values. Previously `updateYBlockAttribute()` only reacted to top-level `Y.Text` values, but now `mergeYValue()` recurses into schema definitions to create the right Y types for internal arrays and objects.

Any block attribute with `type: 'array'` or `type: 'object'` and a `query` schema definition gets nested Y types automatically. This change also affects [`core/gallery` images](https://github.com/WordPress/gutenberg/blob/802e9e0f9343f1a44b5198df61d57e44d9ff6037/packages/block-library/src/gallery/block.json#L13-L56), though table is the much more important case.

For structural changes (adding/removing rows), the Y.Array is rebuilt from scratch as a fallback. This means a concurrent cell edit during a structural change could still conflict, but these are infrequent and should be a reasonable fallback.

This is also related to https://github.com/WordPress/gutenberg/issues/76812, because we can't render cursors without `Y.Text` instances for table cells. The changes in here should allow for fixing #76812.

## Testing Instructions

1. Enable RTC via Settings -> Writing -> "Enable real-time collaboration" checkbox.
2. Create a post with a table block (e.g. 2 columns, 2 rows). Add some text to each cell.
3. Open the same post in a second browser tab.
4. In tab 1, edit a cell in row 1. In window 2, edit a different cell in row 2.
5. Verify both edits appear in both windows within a few seconds without overwriting each other.

## Use of AI Tools

AI assistance: Yes
Tool(s): Claude Code
Used for: Implementation of nested Y.js types for array/object block attributes

### CODE REVIEW

File: packages/core-data/src/utils/crdt-blocks.ts [hunk 1]
```diff
@@ -499,11 +582,151 @@ export function mergeCrdtBlocks(
...
+	newObj: Record< string, unknown >,
+	query: Record< string, BlockAttributeSchema >,
+	cursorPosition: number | null
+): void {
+	for ( const [ key, newVal ] of Object.entries( newObj ) ) {
+		mergeYValue( query[ key ], newVal, yMap, key, cursorPosition );
+	}
+
+	// Delete properties absent from the incoming object.
+	for ( const key of yMap.keys() ) {
```
Comment (ingeniumed) [inline packages/core-data/src/utils/crdt-blocks.ts:721]: Tests: Don't think this is covered atm.

File: packages/core-data/src/utils/crdt-blocks.ts [hunk 2]
```diff
@@ -499,11 +582,151 @@ export function mergeCrdtBlocks(
...
+			const newElement = newValue[ i ];
+
+			if ( currentElement instanceof Y.Map && isRecord( newElement ) ) {
+				mergeYMapValues(
+					currentElement,
+					newElement,
+					query,
+					cursorPosition
+				);
+			} else {
```
Comment (ingeniumed) [inline packages/core-data/src/utils/crdt-blocks.ts:622]: Tests: Don't believe this is covered rn

File: packages/core-data/src/utils/crdt-blocks.ts [hunk 3]
```diff
@@ -255,14 +255,89 @@ function createNewYAttributeValue(
...
+ *
+ * @param query The query schema defining the properties.
+ * @param obj   The plain object to convert.
+ * @return A Y.Map with typed values.
+ */
+function createYMapFromQuery(
+	query: Record< string, BlockAttributeSchema >,
+	obj: unknown
+): Y.Map< unknown > {
+	if ( ! isRecord( obj ) ) {
```
Comment (ingeniumed) [inline packages/core-data/src/utils/crdt-blocks.ts:329]: Minor: Is it valuable to cover this path in the tests?

File: packages/core-data/src/utils/crdt-blocks.ts [hunk 4]
```diff
@@ -499,11 +582,151 @@ export function mergeCrdtBlocks(
...
+	) {
+		mergeRichTextUpdate( currentVal, newVal, cursorPosition );
+	} else if (
+		schema?.type === 'array' &&
+		schema.query &&
+		Array.isArray( newVal ) &&
+		currentVal instanceof Y.Array
+	) {
+		mergeYArray( currentVal, newVal, schema, cursorPosition );
+	} else if (
```
Comment (ingeniumed) [inline packages/core-data/src/utils/crdt-blocks.ts:680]: Tests: Would cover this path, as I don't think its covered rn

**Review by ingeniumed — COMMENTED** [review]
It worked well in my testing. Considering how targeted each PR is getting, I noted down gaps in the tests that'd be useful to cover. That way the unit tests cover any changes that are accidentally made. Don't mind whether the coverage happens via unit or e2e tests - whatever's easier

**Comment by alecgeatches** [comment]
@ingeniumed Added a few more test cases in https://github.com/WordPress/gutenberg/pull/76913/commits/cf895afcc4cd8253726999e20adfcf1cd61f98f9 for deleted properties, type differences/migration, and cases when a top-level query represents an object.

**Review by ingeniumed — APPROVED** [review]

**Comment by alecgeatches** [comment]
I'm merging this now. As mentioned above, this is not intended for 7.0 backport at this time.
