### PR TITLE
Do not output navigation links with empty labels

### LINKED ISSUE #19603: Navigation Block: Detect links with no text and avoid rendering them
**Describe the bug**
Using the navigation block, if I add a link with no text, it will still render on the front end. For example as a sub menu item:

In the editor:

Screen Shot 2020-01-13 at 12 26 36 PM

Means the sub menu hover will render and be empty:

Screen Shot 2020-01-13 at 12 26 43 PM

I think the ideal is that the block can detect when a link item has no text and avoids rendering it.

**To reproduce**
1. Add the navigation block
2. Add a top level link item with URL and text
3. Add a submenu link item and leave the text part blank
4. Check the front end

**Expected behavior**
I should not see a space or empty rendering of a link causing the above visual.

### PR DESCRIPTION
**Pull request by jeryj**
Closes https://github.com/WordPress/gutenberg/issues/19603

Previously all links from the navigation blocks were output on the frontend, even if they had no label content. This PR removes links with empty labels so they are not output.

## How has this been tested?
Manually, with empty labels in both the top level and submenu.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: packages/block-library/src/navigation/index.php [hunk 1]
```diff
@@ -67,6 +67,17 @@ function build_css_font_sizes( $attributes ) {
 	return $font_sizes;
 }
 
+/**
+ * Filters out links with no labels
```
Comment (obenland) [inline packages/block-library/src/navigation/index.php]: Let's add a trailing period here.
https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#1-functions-class-methods

File: packages/block-library/src/navigation/index.php [hunk 2]
```diff
@@ -67,6 +67,17 @@ function build_css_font_sizes( $attributes ) {
...
+ *
+ * @param array $block Block to check label attribute on.
+ *
+ * @return boolean
+ */
+function has_navigation_label( $block ) {
```
Comment (obenland) [inline packages/block-library/src/navigation/index.php]: I realize the other functions in this file are not namespaced either, but let's lead by good example until #18589 is in.
Maybe add a leading `gutenberg_`?

File: packages/block-library/src/navigation/index.php [hunk 3]
```diff
@@ -121,7 +132,8 @@ function build_navigation_html( $block, $colors, $font_sizes ) {
 		? sprintf( ' style="%s"', esc_attr( $colors['inline_styles'] ) . esc_attr( $font_sizes['inline_styles'] ) )
 		: '';
 
-	foreach ( (array) $block['innerBlocks'] as $key => $block ) {
+	// Only include link blocks that have a label set.
+	foreach ( (array) array_filter( $block['innerBlocks'], 'has_navigation_label' ) as $key => $block ) {
```
Comment (retrofox) [inline packages/block-library/src/navigation/index.php]: A suggestion in order to run this write this call once:

```php
function render_block_navigation( $attributes, $content, $block ) {
  $inner_blocks = (array) array_filter( $block['innerBlocks'], 'has_navigation_label' );
  if ( empty( $inner_blocks ) ) {
    return ;
  }

  // ...
}
```

In this way, we are avoiding run unnecessary code such as defining vars, etc. And also we won't need to care for checking the sub-menus items (L181)

File: packages/block-library/src/navigation/index.php [hunk 4]
```diff
@@ -165,7 +177,8 @@ function build_navigation_html( $block, $colors, $font_sizes ) {
 		$html .= '</a>';
 		// End anchor tag content.
 
-		if ( count( (array) $block['innerBlocks'] ) > 0 ) {
+		// Only include innerBlocks that have a label set in the count. Otherwise a submenu with no links will be rendered.
+		if ( count( (array) array_filter( $block['innerBlocks'], 'has_navigation_label' ) ) > 0 ) {
```
Comment (retrofox) [inline packages/block-library/src/navigation/index.php]: `empty()` > `count() > 0` :-D

File: packages/block-library/src/navigation/index.php (hunk 3 above)
Comment (obenland) [inline packages/block-library/src/navigation/index.php]: The `(array)` casting should probably be kept in place for `$block['innerBlocks']`. `array_filter()` will always return an array. Same below

File: packages/block-library/src/navigation/index.php (hunk 4 above)
Comment (obenland) [inline packages/block-library/src/navigation/index.php]: This is getting pretty involved. Maybe we could save that in a variable to make that conditional easier to grok?

**Review by obenland — CHANGES_REQUESTED** [review]

File: packages/block-library/src/navigation/index.php (hunk 3 above)
Comment (obenland) [reply packages/block-library/src/navigation/index.php]: If we're only using the callback once, it's fine to keep it inline, too.

Comment (retrofox) [reply packages/block-library/src/navigation/index.php]: Do you mean that the `return;` will break the loop?

**Comment by jeryj** [comment]
Thanks for your feedback @obenland and @retrofox! I’m combining a bit of all of it and redoing it as a recursive function in the `render_block_navigation()` to remove all empty labels. Then the `build_navigation_htm()` knows it has valid data to work with.

This also prevents a nav block with no content from being rendered at all (ie no empty `<nav>` in the HTML).

File: packages/block-library/src/navigation/index.php [hunk 5]
```diff
@@ -67,6 +67,41 @@ function build_css_font_sizes( $attributes ) {
...
+/**
+ * Recursively filters out links with no labels to build a clean navigation block structure.
+ *
+ * @param array $blocks Navigation link inner blocks from the Navigation block.
+ *
+ * @return boolean
+ */
+function gutenberg_remove_empty_navigation_links_recursive( $blocks ) {
+
+	$blocks = array_filter( $blocks, 'gutenberg_has_navigation_label' );
```
Comment (obenland) [inline packages/block-library/src/navigation/index.php]: Since it's only being used once, let's move that callback inline

File: packages/block-library/src/navigation/index.php [hunk 6]
```diff
@@ -67,6 +67,41 @@ function build_css_font_sizes( $attributes ) {
...
+
+	if ( empty( $blocks ) ) {
```
Comment (obenland) [inline packages/block-library/src/navigation/index.php]: Personal preference: If the conditional was reversed the foreach loop could be moved in its body and the function would have only one return statement.

File: packages/block-library/src/navigation/index.php [hunk 7]
```diff
@@ -67,6 +67,41 @@ function build_css_font_sizes( $attributes ) {
...
+function gutenberg_has_navigation_label( $block ) {
+	return ! empty( $block['attrs']['label'] );
+}
+
+/**
+ * Recursively filters out links with no labels to build a clean navigation block structure.
+ *
+ * @param array $blocks Navigation link inner blocks from the Navigation block.
+ *
+ * @return boolean
```
Comment (obenland) [inline packages/block-library/src/navigation/index.php]: This should be `array` now

File: packages/block-library/src/navigation/index.php [hunk 8]
```diff
@@ -67,6 +67,41 @@ function build_css_font_sizes( $attributes ) {
...
+ */
+function gutenberg_remove_empty_navigation_links_recursive( $blocks ) {
+
+	$blocks = array_filter( $blocks, 'gutenberg_has_navigation_label' );
+
+	if ( empty( $blocks ) ) {
+		return $blocks;
+	}
+
+	foreach ( $blocks as $key => $val ) {
```
Comment (obenland) [inline packages/block-library/src/navigation/index.php]: Personal preference: `$block` would be more descriptive than `$val` and it could be used in the following `empty()` check and passed to the function call instead of `$blocks[ $key ]` to make it a bit easier to read.

File: packages/block-library/src/navigation/index.php [hunk 9]
```diff
@@ -77,6 +112,13 @@ function build_css_font_sizes( $attributes ) {
  * @return string Returns the post content with the legacy widget added.
  */
 function render_block_navigation( $attributes, $content, $block ) {
+
+	$block['innerBlocks'] = gutenberg_remove_empty_navigation_links_recursive( $block['innerBlocks'] );
+
+	if ( empty( $block['innerBlocks'] ) ) {
+		return;
```
Comment (obenland) [inline packages/block-library/src/navigation/index.php]: Function docs say it returns a string.

**Review by obenland — CHANGES_REQUESTED** [review]
Nice iteration! Feel free to remove the leading empty line in function bodies, I don't think WP coding standards are calling for that.

File: packages/block-library/src/navigation/index.php (hunk 6 above)
Comment (jeryj) [reply packages/block-library/src/navigation/index.php]: I like early returns in general, but I can go with it :)

**Comment by jeryj** [comment]
Ready for another review 👍

**Review by obenland — APPROVED** [review]
Looking good! I still think the empty lines at the beginning of function bodies could/should be removed, but it doesn't need to stand in the way of getting this in.

**Comment by jeryj** [comment]
>  Feel free to remove the leading empty line in function bodies

Ah! Sorry - I missed that one. Thanks for merging!

**Comment by obenland** [comment]
I didn't merge, it looks like it needs a rebase before it can go in.

**Comment by jeryj** [comment]
Missed that then too... I'll get the leading lines removed and rebase 👍
