### PR TITLE
Bug: PHP notice when an image with lightbox is deleted

### LINKED ISSUE #55347: Image block lightbox: PHP notices when an image with lightbox is deleted
### Description

Discovered because of an edge case scenario but can be reproduced with a normal flow users can take in the WP admin.

Here:

https://github.com/WordPress/gutenberg/blob/e21581b38aaaf2f22f44f41a598929a9e5b82ac6/packages/block-library/src/image/index.php#L170-L175

we are trying to access the width and height array offsets that may not exist. In fact, `wp_get_attachment_metadata` can return `false` instead of an array.

On my local development environment, I had to re-import all my attachments via the WordPress importer and the theme unit test data becasue attachments got deleted while running PHP unit tests. By reimporting them, the post attachments got a new ID. Their path in the upload directory was unchanged, because I previously uploaded them in this same month:
`/wp-content/uploads/2023/10/`

Testing a post with an image block that opens in the lightbox:
- The image was still visible, both in the Editor and on the front end, because the image path was unchanged.
- The image actual id was new, although it stayed unchanged in the block markuo.
- As such, `wp_get_attachment_metadata` returned false, triggering the PHP notices.

A more common scenario that users can potentially trigger by just using the WP admin is when deelting an image from the Media Library. See testing instructione below.

Seems to me that as a good practice, we should always check if an array item is set before trying to access it. Even though it's only a PHP notice that would probably be not visible on production, the code should be more safeguarder.

### Step-by-step reproduction instructions

- Create a post.
- Add an image from the Media Library and set it to open in the lightbox.
- Publish and view the front end.
- Observe everything works as expected.
- Go to the Media Library.
- Delete the image that you previously added in the post.
- View the previous post in the front end, refresh the page if necessary.
- The image will be 'broken', and that is expected.
- However these PHP notices are not expected:

```
PHP Notice:  Trying to access array offset on value of type bool in /var/www/src/wp-content/plugins/gutenberg/build/block-library/blocks/image.php on line 174

PHP Notice:  Trying to access array offset on value of type bool in /var/www/src/wp-content/plugins/gutenberg/build/block-library/blocks/image.php on line 175
```

Aside:
when refreshing the post in the Editor, you will get the additional, usual, PHP warning `Cannot modify header information - headers already sent`

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by kishanjasani**
`wp_get_attachment_metadata` return false if it has no metadata related to attachment, So, I added a condition to check before extrtacting the value from array. it help fixes: #55347 

## Testing Instructions
- Create a post or page.
- Add an image from the Media Library and set it to `Expand on Click`: `true`. 
- Publish and view the front end.
- Observe everything works as expected.
- Go to the Media Library.
- Delete the image that you previously added in the post.
- View the previous post in the front end, refresh the page if necessary.
- The image will be 'broken', and that is expected and PHP notice should not show.

### CODE REVIEW

File: packages/block-library/src/image/index.php [hunk 1]
```diff
@@ -167,15 +167,17 @@ function block_core_image_render_lightbox( $block_content, $block ) {
...
+	$img_height = 'none';
 	if ( isset( $block['attrs']['id'] ) ) {
 		$img_uploaded_src = wp_get_attachment_url( $block['attrs']['id'] );
 		$img_metadata     = wp_get_attachment_metadata( $block['attrs']['id'] );
-		$img_width        = $img_metadata['width'];
-		$img_height       = $img_metadata['height'];
+		if ( ! empty( $img_metadata ) && is_array( $img_metadata ) ) {
+			$img_width  = $img_metadata['width'];
+			$img_height = $img_metadata['height'];
+		}
```
Comment (ramonjd) [inline packages/block-library/src/image/index.php]: This could cause an error. Since `img_width` and `img_height` won't be set, `$img_metadata` won't pass the conditions.

`Undefined variable $img_width in /var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/image.php on line 216 Warning: Undefined variable $img_height in /var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/image.php on line 217`

Maybe we could provide a default value like the below else statement.

```suggestion
		$img_width        = $img_metadata['width'] ?? 'none';
		$img_height       = $img_metadata['height'] ?? 'none';
```

Comment (kishanjasani) [reply packages/block-library/src/image/index.php]: Hey @ramonjd, Thanks for the feedback. I already moved `$img_width  = 'none';` and `$img_height = 'none';` out side of `if` statement. So, It won't throw error. I already checked the condition you mentioned with updated code.

Let me know, If I still need to make changes.

Comment (kishanjasani) [reply packages/block-library/src/image/index.php]: By the way, Liked your short and optimal solution. I have updated the PR.

Thanks @ramonjd

Comment (ramonjd) [reply packages/block-library/src/image/index.php]: Thank you for working on this!

Looks good to me,  but maybe @artemiomorales should run an eye past it just to be sure.

**Review by michalczaplinski — APPROVED** [review]
LGTM! 👍 

Thank you @kishanjasani

**Comment by afercia** [comment]
@mikachan I think the same change should be done for the `lib/block-supports/behaviors.php` file, just in case. Quick PR incoming.

**Comment by SiobhyB** [comment]
I just cherry-picked this PR to the 6.4-rc1-2 branch to get it included in the next release: https://github.com/WordPress/gutenberg/pull/55348/commits/ab7369e4cedc5f6b4bf44e4a3f1bc3e303ae87d3
