### PR TITLE
Site editor: Shorter screen reader announcement after changing pages

### LINKED ISSUE #55776: Tracking: Style Revision UX Improvements
I'm documenting some discussion around improvements to style revisions in the block editor. Specifically refinements to improve the UX and discoverability of the feature. These will be broken out as separate issues over time, but this can act as a tracking issue.

- [x] https://github.com/WordPress/gutenberg/issues/53621
    - https://github.com/WordPress/gutenberg/pull/56799 
    - Use load more for pagination instead of number pagination??
- [x] https://github.com/WordPress/gutenberg/issues/55577
    - https://github.com/WordPress/gutenberg/pull/56800
- [x] Update the saving flow for style revisions to provide detail instead of just a "custom styles" checkbox. 
    - https://github.com/WordPress/gutenberg/pull/57411
    - https://github.com/WordPress/gutenberg/pull/57470
- [ ] https://github.com/WordPress/wordpress-develop/pull/5699
- [x] https://github.com/WordPress/gutenberg/pull/54046
- [x] https://github.com/WordPress/gutenberg/pull/55827
- [x] #55779
- [x] #55647
    - https://github.com/WordPress/gutenberg/pull/56577
- [x] https://github.com/WordPress/gutenberg/issues/55648
- [x] https://github.com/WordPress/gutenberg/pull/55881
- [x] https://github.com/WordPress/gutenberg/pull/56491
- [x] Explore a link to the code revisions view https://github.com/WordPress/gutenberg/pull/56577#issuecomment-1846305014

Future once these are done: https://github.com/WordPress/gutenberg/issues/53484

### Related

- https://github.com/WordPress/gutenberg/issues/56413

### LINKED ISSUE #56188: Site editor: Fix the document title announcement for screen readers
### Description

Alternative to https://github.com/WordPress/gutenberg/pull/56167

The Site Editor uses a 'single page app' navigation type, where navigating through the different views of the editor updates the content of the page but the HTML document is always the same. 
As such, like in all single page apps, the navigation needs to be announced bt screen readers to emulate the native beheavir of a traditional navigation across different pages, where the document title is announced as first thing.

The current implementation in the Site editor uses a `speak()` to announce the updated document title and the site title, also appending the string `WordPress`:

https://github.com/WordPress/gutenberg/blob/dc7e1aa202ee2605f0423ac0f48fa590b3027f60/packages/edit-site/src/components/routes/use-title.js#L38-L58

There's a few problems though:
- Sometimes, the document title doesn't actually reflect the displayed view. For example, the initial view is called 'Design' but the current state of the editor is displaying the Home bloc template. The document title is `<title>Blog Home ‹ Template ‹ Editor ‹ WordPress Develop — WordPress</title>` and that gets announced, which is misleading and doesn't reflect what is shown visually.
- When navigating to some page, the document title doesn't change. For example clicking on 'Templates', I would expect the document title to tell me I'm in the Templages page. Intead, it is still `<title>Blog Home ‹ Template ‹ Editor ‹ WordPress Develop — WordPress</title>`. This gets announced by screen readers and it's just wrong.
- The same thing happens when clicking on Navigation, Styles, Pages, or Patterns: the document title is not announced so the audible feedback is just wrong. It appears all 'first level' pages in the routing mechanism don't update the document title correctly.
- The announcement is too verbose anyways. For example, when navigating to the 'Single posts' template page, as a screen reader user I just need to know that the navigation completed succesfully and I'm now in the Single Posts view. Insteead, the announcement is really too long and annoying:
`Now displaying: Single Posts ‹ Template ‹ Editor ‹ WordPress Develop — WordPress`

## Suggested remediation:
- Make sure the document title is always updated.
- Make sure the document title always accurately reflects what the current view is.
- Shorten the audibel message and strip out the part ` ‹ Editor ‹ WordPress Develop — WordPress`.

### Step-by-step reproduction instructions

- Test with a screen reader. For this issue, using Safari and VoiceOver is sufficient. On Windows, you can try Firefox and NVDA.
- Go to the Site editor and navigate through the site editor views.
- Observe the navigation announcement is incorrect for the first level views.
- Observe the announcement is too verbose and annoying.

### Screenshots, screen recording, code snippet

Wrong document title announced on the Templates view:

wrong document title

Wrong document title announced on the Navigation view:

Screenshot 2023-11-16 at 09 14 59

Example of too verbose announcement:

too verbose

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by alexstine**
## What?

Partially fixes #56188

## Why?

The current title message is very verbose, this PR shortens it.

## How?

Adds a dedicated prop for accessibility announcements.

## Testing Instructions

1. Enable a screen reader.
2. Open the Appearance > Editor.
3. Notice the message spoken is shorter.
> Now displaying: template_name template_type

### CODE REVIEW

File: packages/edit-site/src/components/routes/use-title.js [hunk 1]
```diff
@@ -47,14 +47,17 @@ export default function useTitle( title ) {
 			document.title = formattedTitle;
 
 			// Announce title on route change for screen readers.
+			if ( ! accessibleTitle ) {
+				return;
+			}
 			speak(
 				sprintf(
 					/* translators: The page title that is currently displaying. */
 					__( 'Now displaying: %s' ),
```
Comment (joedolson) [inline packages/edit-site/src/components/routes/use-title.js]: Is the prefix "Now displaying" necessary? Could that be shortened? E.g., "Showing: %s". I feel like we don't need to indicate that it's happening now; that should be obvious from context, so dropping this from four syllables to two would be helpful. I'm not even 100% convinced the prefix is required at all; page navigation in a standard context doesn't prefix the `title` element.

File: packages/edit-site/src/components/routes/use-title.js [hunk 2]
```diff
@@ -47,14 +47,17 @@ export default function useTitle( title ) {
 			document.title = formattedTitle;
 
 			// Announce title on route change for screen readers.
+			if ( ! accessibleTitle ) {
```
Comment (joedolson) [inline packages/edit-site/src/components/routes/use-title.js]: What's the case where accessibleTitle would be absent? Is it a better option for no announcement if that version of the title isn't made, or fto keep the more verbose announcement?

**Review by joedolson — COMMENTED** [review]
Just some points of discussion added.

File: packages/edit-site/src/components/routes/use-title.js (hunk 2 above)
Comment (alexstine) [reply packages/edit-site/src/components/routes/use-title.js]: @joedolson It should always be available but I guess I could add a fallback here. The verbose title is so annoying I opted to not use it but easy enough to adjust the conditional.

File: packages/edit-site/src/components/routes/use-title.js (hunk 1 above)
Comment (alexstine) [reply packages/edit-site/src/components/routes/use-title.js]: @joedolson Agreed. Making this change.

File: packages/edit-site/src/components/routes/use-title.js (hunk 2 above)
Comment (alexstine) [reply packages/edit-site/src/components/routes/use-title.js]: Done.

File: packages/edit-site/src/components/routes/use-title.js (hunk 1 above)
Comment (alexstine) [reply packages/edit-site/src/components/routes/use-title.js]: Done.

File: packages/edit-site/src/components/list/index.js [hunk 3]
```diff
@@ -51,7 +51,7 @@ export default function List() {
 		[ templateType ]
 	);
 
-	useTitle( postType?.labels?.name );
+	useTitle( postType, postType );
```
Comment (afercia) [inline packages/edit-site/src/components/list/index.js]: Not sure why the first parameter has been changed?
I'm not even sure this `List` component is actually used anywhere though.

File: packages/edit-site/src/components/editor/index.js [hunk 4]
```diff
@@ -176,11 +177,18 @@ export default function Editor( { listViewToggleElement, isLoading } ) {
 			POST_TYPE_LABELS[ editedPostType ] ??
 				POST_TYPE_LABELS[ TEMPLATE_POST_TYPE ]
 		);
+		accessibleTitle = sprintf(
```
Comment (afercia) [inline packages/edit-site/src/components/editor/index.js]: Instead of using this new `accessibleTitle` string, which is the same as `title` with the ` ‹ Editor` part stripped out, I'd strip out ` ‹ Editor` from the existing title and add it later in `useTitle`. I think we could entirely avoid to use `accessibleTitle`?

File: packages/edit-site/src/components/routes/use-title.js [hunk 5]
```diff
@@ -16,7 +16,7 @@ import { unlock } from '../../lock-unlock';
 
 const { useLocation } = unlock( routerPrivateApis );
 
-export default function useTitle( title ) {
+export default function useTitle( title, accessibleTitle ) {
```
Comment (afercia) [inline packages/edit-site/src/components/routes/use-title.js]: We could avoid to pass a second parameter.
We could simply add the ` ‹ Editor` part later in the `formattedTitle` string.

File: packages/edit-site/src/components/routes/use-title.js [hunk 6]
```diff
@@ -47,14 +47,7 @@ export default function useTitle( title ) {
...
 			// Announce title on route change for screen readers.
-			speak(
-				sprintf(
-					/* translators: The page title that is currently displaying. */
-					__( 'Now displaying: %s' ),
-					document.title
-				),
-				'assertive'
-			);
+			speak( accessibleTitle || formattedTitle, 'assertive' );
```
Comment (afercia) [inline packages/edit-site/src/components/routes/use-title.js]: Instead of `accessibleTitle` we could use `title` if we remove the ` ‹ Editor` part and add it later only for the formattedTitle.

File: packages/edit-site/src/components/routes/use-title.js [hunk 7]
```diff
@@ -47,14 +47,7 @@ export default function useTitle( title ) {
...
 		}
-	}, [ title, siteTitle, location ] );
+	}, [ title, accessibleTitle, siteTitle, location ] );
```
Comment (afercia) [inline packages/edit-site/src/components/routes/use-title.js]: I think we could remove `accessibleTitle` from everywhere?

File: packages/edit-site/src/components/list/index.js (hunk 3 above)
Comment (alexstine) [reply packages/edit-site/src/components/list/index.js]: Oversight, reverted.

File: packages/edit-site/src/components/editor/index.js (hunk 4 above)
Comment (alexstine) [reply packages/edit-site/src/components/editor/index.js]: Correct, done.

File: packages/edit-site/src/components/routes/use-title.js (hunk 5 above)
Comment (alexstine) [reply packages/edit-site/src/components/routes/use-title.js]: Done.

File: packages/edit-site/src/components/routes/use-title.js (hunk 6 above)
Comment (alexstine) [reply packages/edit-site/src/components/routes/use-title.js]: Done.

File: packages/edit-site/src/components/routes/use-title.js (hunk 7 above)
Comment (alexstine) [reply packages/edit-site/src/components/routes/use-title.js]: Yes, done.

**Review by afercia — APPROVED** [review]
LGTM to me!

I rebased on top of latest trunk and pushed a commit to clarify a couple translators comments.

**Comment by afercia** [comment]
Some unrelated End-to-End Tests (Puppeteer ) are continuously failing even after restarting the failing job several times. I've seen these tests failing on other pull requests as well. That's a little annoying :) Does anyone know why these tests fail and if it's a known issue? @youknowriad 🙏 

Example: https://github.com/WordPress/gutenberg/actions/runs/7002611856/job/19050455970?pr=56339
- `TimeoutError: waiting for selector `tr[data-slug="gutenberg-test-allowed-patterns"] .deactivate a` failed: timeout 30000ms exceeded`
- `TimeoutError: waiting for selector `div[data-slug="emptytheme"].active` failed: timeout 30000ms exceeded`
