### PR TITLE
Don't persist mobile and publish sidebars

### LINKED ISSUE #4248: Chrome: Publish sidebar toggle state persists between page loads
## Issue Overview

If the Publish menu is opened, it will remain open in subsequent editor sessions.

## Steps to Reproduce

1. Navigate to Posts > Add New
2. Enter a title
3. Press Publish in the editor header
4. Navigate to Posts > Add New
   - Ignore the prompt about unsaved changes and continue navigation

## Expected Behavior

In the new editor session, the Publish sidebar is not visible.

## Current Behavior

The Publish sidebar is visible, including after subsequent refreshes.

## Possible Solution

Sidebar toggle state is [managed in preferences state](https://github.com/WordPress/gutenberg/blob/38b60d6ec3c902bd552592d0b61cee0179bd92c2/editor/store/reducer.js#L495-L570) which is persisted between editor loads. Is this meant to be a preference? And if so, do we need to implement some behavior for the preferences reducer to allow specific values to be persisted vs. others? Maybe [as with the `REDUX_REHYDRATE` action](https://github.com/WordPress/gutenberg/blob/38b60d6ec3c902bd552592d0b61cee0179bd92c2/editor/store/persist.js#L32-L66), we need a complementing persist action which allows the reducer to define which values should be included in that state?

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/4248

This PR creates a mechanism that allows reducers to customize what gets saved to localStorage. They can do that customization by changing the state returned for the action type 'REDUX_SERIALIZE'.
To do that, in this approach I had to pass the reducer function to loadAndPersist, I wanted to avoid that but I'm not certain how. An advantage we got with that is that now we don't need to pass defaults to loadAndPersist they are retrieved from the reducers defaults.
In the end, the new custom serialization mechanism was used to avoid persisting mobile and publish sidebars.

## How Has This Been Tested?
Resize Gutenberg to mobile resolution, open the sidebar, refresh the page, verify the sidebar is closed on refresh.
Open the publish sidebar refresh the page, verify publish is also closed on refresh.

### CODE REVIEW

**Comment by youknowriad** [comment]
Not sure what's happening to Travis, but I like this change.

**Comment by jorgefilipecosta** [comment]
Hi, @youknowriad I missed some test case changes, but they were updated now.

**Review by youknowriad — APPROVED** [review]
LGTM 👍  

We'll have to document the persisting behavior at some point.

File: editor/store/persist.js [hunk 1]
```diff
@@ -34,17 +34,17 @@ export function withRehydratation( reducer, reducerKey ) {
...
+ * @param {string}   storageKey The storage key to use.
  */
-export function loadAndPersist( store, reducerKey, storageKey, defaults = {} ) {
+export function loadAndPersist( store, reducer, reducerKey, storageKey ) {
 	// Load initially persisted value
 	const persistedString = window.localStorage.getItem( storageKey );
 	if ( persistedString ) {
 		const persistedState = {
-			...defaults,
+			...get( reducer( undefined, { type: 'DEFAULTS' } ), reducerKey ),
```
Comment (aduth) [inline editor/store/persist.js]: Not sure it's a convention we care to adopt, but Redux goes out of its way to try to make the `type` distinct so as not to conflict with what could exist as an application-handled "DEFAULTS" type here. The Redux initialization type is `@@INIT`.

File: editor/store/persist.js [hunk 2]
```diff
@@ -60,7 +60,8 @@ export function loadAndPersist( store, reducerKey, storageKey, defaults = {} ) {
 		const newStateValue = get( store.getState(), reducerKey );
 		if ( newStateValue !== currentStateValue ) {
 			currentStateValue = newStateValue;
-			window.localStorage.setItem( storageKey, JSON.stringify( currentStateValue ) );
+			const stateToSave = get( reducer( store.getState(), { type: 'REDUX_SERIALIZE' } ), reducerKey );
```
Comment (aduth) [inline editor/store/persist.js]: Do you think the `REDUX_` prefix adds much value here? It's not as though it's a feature native to Redux, or that we _need_ it to be specific to Redux. I think we could either remove the prefix altogether, or otherwise make it specific to the feature itself (persistence).

File: editor/store/persist.js [hunk 3]
```diff
@@ -34,17 +34,17 @@ export function withRehydratation( reducer, reducerKey ) {
...
- * @param {string} reducerKey The reducer key to persist (example: reducerKey.subReducerKey).
- * @param {string} storageKey The storage key to use.
- * @param {Object} defaults   Default values of the reducer key.
+ * @param {Object}   store      Store to enhance.
+ * @param {Function} reducer    The reducer function. Used to get default values and to allow custom serialization by the reducers.
+ * @param {string}   reducerKey The reducer key to persist (example: reducerKey.subReducerKey).
+ * @param {string}   storageKey The storage key to use.
  */
-export function loadAndPersist( store, reducerKey, storageKey, defaults = {} ) {
+export function loadAndPersist( store, reducer, reducerKey, storageKey ) {
```
Comment (aduth) [inline editor/store/persist.js]: This feels very much like it would fit the signature of a [store enhancer](https://redux.js.org/docs/Glossary.html#store-enhancer):

```js
export function loadAndPersist( reducerKey, storageKey ) {
	return ( createStore ) => ( reducer, ...args ) => {
		const store = createStore( reducer, ...args );

		// ...

		return store;
	};
}
```

_(Reference: [`applyMiddleware`](https://github.com/reactjs/redux/blob/master/src/applyMiddleware.js))_

But I'd guess this isn't well-supportable by our data module?

Comment (jorgefilipecosta) [reply editor/store/persist.js]: Yes, I remember that some enhancers had to be removed because of not being well-supported.
@youknowriad, are you aware if the situation changed and now we can safely use a store enhancer?
