### PR TITLE
Cover block: Only use white text when the background of the cover block is dark.

### LINKED ISSUE #3483: Multiple Themes: Cover Block with White Background defaults to White Font, text goes "missing"
### Steps to reproduce the behavior

1. Go to Site - Pages and create a page.
2. Add a Cover Block to it, and make the Cover Block have a white background.
3. Add some text on top of that Cover Block.

#### What I expected to happen
The font color to be black, or some other contrasting color that would be visible on the Cover Block.

#### What actually happened
The font color automatically defaults to white, and hidden/lost on the Cover Block, since it blends into the background. 

### Context
#user-report

#### Browser / OS version
All

#### Is this specific to the applied theme? Which one?
Multiple themes. Tested on Hever and Coutoire. 

Could not replicate on Spearhead

#### Does this happen on simple or atomic sites or both?
Both

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
Affects all Cover Blocks on multiple themes. 

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

image

image

### PR DESCRIPTION
**Pull request by scruffian**
## Description
Presently the text of the Cover block is always white unless the user customizes it. This causes a problem when the background of the block is light.

This PR updates the conditions on which we make the text white - it is now only white when then block has an "is-dark-theme" class, which gets applied when the block has a dark background color or image.

Fixes https://github.com/Automattic/themes/issues/3483 and https://github.com/WordPress/gutenberg/issues/17953

One issue to be aware of is that in a dark theme (for example Quadrat), when the cover block is set to a light background, the default text color for the theme will still be used. Perhaps in a dark theme we should default the block to have a white background and dark text, but that is a much larger change, and this PR doesn't make that problem worse so we can dealt with it in the future.

## How has this been tested?
In empty theme, add a cover block. Set the background to a light color and confirm you can still see the text.

## Screenshots
Screenshot 2021-07-19 at 12 01 17

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-library/src/cover/edit.js [hunk 1]
```diff
@@ -214,7 +214,12 @@ function ResizableCover( {
  *
  * @return {boolean} True if the cover background is considered "dark" and false otherwise.
  */
-function useCoverIsDark( url, dimRatio = 50, overlayColor, elementRef ) {
+function useCoverIsDark(
+	url,
+	dimRatio = 50,
+	overlayColor = '#000000',
```
Comment (jorgefilipecosta) [inline packages/block-library/src/cover/edit.js]: What makes us need to set a default overlay color?


In case we set a default overlay color some code on the hook needs to be updated. For example, the code inside conditions "if ( ! overlayColor ) {" and "if ( ! url && ! overlayColor ) {" is never going to be executed (as we will always have an overlayColor).

File: packages/block-library/src/cover/style.scss [hunk 2]
```diff
@@ -104,7 +104,13 @@
 	.wp-block-cover__inner-container {
 		width: 100%;
 		z-index: z-index(".wp-block-cover__inner-container");
-		color: $white;
+
+	}
+
+	&.is-dark-theme {
```
Comment (jorgefilipecosta) [inline packages/block-library/src/cover/style.scss]: The class is-dark-theme is only applied on the editor side, not on the frontend (not found by searching in packages/block-library/src/cover/save.js). Styles that apply only on the editor side should be on "packages/block-library/src/cover/editor.scss", to avoid loading styles on the frontend that are not used.

File: packages/block-library/src/cover/edit.js (hunk 1 above)
Comment (scruffian) [reply packages/block-library/src/cover/edit.js]: The reason we need it is because by default the block background is set to black by CSS.

File: packages/block-library/src/cover/edit.js [hunk 3]
```diff
@@ -604,7 +618,7 @@ function CoverEdit( {
 	const classes = classnames(
 		dimRatioToClass( dimRatio ),
 		{
-			'is-dark-theme': isDark,
```
Comment (scruffian) [inline packages/block-library/src/cover/edit.js:649]: I couldn't find any evidence that this was used so I figured it was ok to change the name.

File: packages/block-library/src/cover/edit.js [hunk 4]
```diff
@@ -604,7 +618,7 @@ function CoverEdit( {
...
+			'is-light': ! isDark,
```
Comment (scruffian) [inline packages/block-library/src/cover/edit.js:655]: `is-light` is preferable, since the current default for the block is dark. We can't update all the blocks that already exist in post content, so the class works better as a modification to a new style rather than a change to the existing rules.

File: packages/block-library/src/cover/edit.js [hunk 5]
```diff
@@ -209,44 +209,56 @@ function ResizableCover( {
...
+ * @param {?Function} setAttributes Function to set attributes on the block.
  */
-function useCoverIsDark( url, dimRatio = 50, overlayColor, elementRef ) {
-	const [ isDark, setIsDark ] = useState( false );
+function useCoverIsDark(
+	url,
+	dimRatio = 50,
+	overlayColor = '#000000',
+	elementRef,
+	setAttributes
```
Comment (scruffian) [inline packages/block-library/src/cover/edit.js]: I'm not sure if passing in `setAttributes` is the best approach here, but it works :)

File: packages/block-library/src/cover/block.json [hunk 6]
```diff
@@ -51,6 +51,10 @@
 		},
 		"contentPosition": {
 			"type": "string"
+		},
+		"isDark": {
```
Comment (scruffian) [inline packages/block-library/src/cover/block.json:62]: Do we need to updates the deprecations when adding an attribute?

Comment (scruffian) [reply packages/block-library/src/cover/block.json:62]: From my tests, we don't...

**Comment by scruffian** [comment]
One issue I see with this, which I am not sure how serious it is:

When I open a page with a cover block in which has a light background, the 'is-light' class is applied and therefore the text changes from white to black. This will alter some users sites in an unexpected way. They can still set the color of the text back to white if they want to, but it might be a problem. What do you think?

File: packages/block-library/src/cover/edit.js (hunk 3 above)
Comment (jasmussen) [reply packages/block-library/src/cover/edit.js:649]: It used to be applied when a theme opted into "dark editor styles", which would apply that CSS class to the body element. 

It's used in a bunch of blocks to invert the block editor UI to be visible, such as changing the spacer block background gray to white:

Screenshot 2021-08-02 at 11 07 09

I think there's probably a better way to do this, it's a bit hacky for this block to apply the class so that nested blocks inside show inverted block UI. But I can't think of an easy solution to doing so.

File: packages/block-library/src/cover/style.scss (hunk 2 above)
Comment (jasmussen) [reply packages/block-library/src/cover/style.scss]: This has been problematic in the past. It's easy to confuse the class, discovered via inspecting in the editor, and assume it's also on the frontend, when as you suggest it's only about the block UI being contrasty (such as a white focus style for blocks when the theme is dark, vs. a blue focus style). The class has also been confused with being related to operating system dark modes, whether for the theme or for the editor. 

We might need to reconsider that UI inversion feature entirely, either automate it so it works without a CSS class, or find some other way to explore contrast in such cases.

**Comment by glendaviesnz** [comment]
@scruffian, I rebased and put the is-dark-theme selector back as discussed - it all seems to be working as expected on TT1-blocks, seedlet, twentytwenty and twenty-nineteen, but not on TT1 - on that theme the text doesn't change to white when the  background is dark, haven't managed to work out why yet, but will have a bit more of a look on Monday.

**Comment by glendaviesnz** [comment]
@scruffian I had to add some [more specificity to the text colour selectors](https://github.com/WordPress/gutenberg/pull/33541/commits/2552a495c99d6d8833ca422fb2b54ae98c83c897) to get this fix to work on TwentyTwentyOne as it has a `currentColor` var that was overriding these new styles due to a higher specificity selector. 

With this in place it seems to work as expected with dark and light images and background colours, and the text colours can still be overridden at the innerBlock level:

Screen Shot 2021-09-20 at 12 43 52 PM

**Comment by jasmussen** [comment]
> I had to add some more specificity to the text colour selectors to get this fix to work on TwentyTwentyOne as it has a currentColor var that was overriding these new styles due to a higher specificity selector.

Does the default style work well in other themes? The reason it's best to keep specificity as low as possible, even if will require theme changes, is that as global styles eventually expands to enable styling more things, it will only work if blocks and themes use low specificity in the place where it connects.

**Comment by glendaviesnz** [comment]
> Does the default style work well in other themes?

It worked as expected in all the other themes I tested on, but another option would be to update TT1 - @scruffian, do you have any thoughts on this as a theme team member?

**Comment by scruffian** [comment]
My preference would be to update TT1 as @jasmussen suggests.

**Comment by glendaviesnz** [comment]
@jasmussen, @scruffian I have reverted the additional selectors that were added for TT1, and this is now working as expected on TT1-blocks, seedlet, twentytwenty and twenty-nineteen, but not on TT1 if you want to give it another test.

Should we finalise and merge this and [then open a core ticket for tt1 theme](https://core.trac.wordpress.org/newticket?component=Bundled+Theme&summary=Twenty+Twenty-One)? It might be be easier for people to replicate the issue once this fix is in a gutenberg plugin release, and I don't think this change makes it any more broken in TT1.

**Comment by scruffian** [comment]
> Should we finalise and merge this and then open a core ticket for tt1 theme? It might be be easier for people to replicate the issue once this fix is in a gutenberg plugin release, and I don't think this change makes it any more broken in TT1.

Yeah sounds like a good plan :+1:

**Review by apeatling — COMMENTED** [review]
I've tested this and it works as expected when choosing any shade of background color from the placeholder:

Screen Shot 2021-09-21 at 4 11 34 PM

I wonder if we can avoid the default attribute though?

**Comment by glendaviesnz** [comment]
> I wonder if we can avoid the default attribute though?

I have removed the default and it still seems to work as expected - it still ends up with the attribute set every time as there is always a background that is compares against and the theme default of black is picked up even if a background colour or image hasn't been selected.

**Comment by glendaviesnz** [comment]
> I have removed the default and it still seems to work as expected

Actually, if we don't set a default it causes validation issues with older blocks, if the default is set it looks like we don't need a deprecation, but without a default we do, so have put the default back.

**Review by apeatling — APPROVED** [review]
This works well for me as per above. I think we should get another approval before merging.

**Comment by jasmussen** [comment]
Seems to work:
Screenshot 2021-10-08 at 10 28 39
Screenshot 2021-10-08 at 10 29 07

It seems good that there isn't any added specificity, which lets us avoid future problems with the low default specificity that global styles outputs, and similarly the `is-light` class is preferrable to avoid any user interface class confusion. In that vein, this seems to work as intended. 

Edit: I also tested the frontend working correctly in the above.

**Review by aristath — APPROVED** [review]
