### PR TITLE
Prevent the image from being resized larger than its container

### LINKED ISSUE #26715: Image block can be resized to be larger than viewport
From https://core.trac.wordpress.org/ticket/48418.

---

On drag to increase the size of the image. it going out of the viewport. 
Please check the attached screenshot. 

steps to reproduce.

- Create a post
- Add image block
- drag the image block from side and bottom.
- notice the issue

Thanks

### PR DESCRIPTION
**Pull request by d-alleyne**
## What?

On drag to increase the size of the image, it goes outside of the viewport. This PR fixes the issue by preventing the image from being larger than its container.
## Why?

It resolves https://github.com/WordPress/gutenberg/issues/26715 . Prevent dragged images from being larger than their container.
## How?

The `clientWidth` variable contains the width of the container, and it is used as the `max-width` for the image.

## Testing Instructions

1. Create a post
2. Add image block
3. drag the image block from side and bottom.
4. notice that the image never grows wider than the container

### CODE REVIEW

File: packages/block-library/src/image/image.js [hunk 1]
```diff
@@ -125,33 +125,29 @@ export default function Image( {
...
-			},
-			[ clientId ]
-		);
+	const { canInsertCover, imageEditing, imageSizes, mediaUpload } = useSelect(
+		( select ) => {
+			const { getBlockRootClientId, getSettings, canInsertBlockType } =
+				select( blockEditorStore );
+
+			const rootClientId = getBlockRootClientId( clientId );
+			const settings = pick( getSettings(), [
```
Comment (kevin940726) [inline packages/block-library/src/image/image.js]: If we don't need `maxWidth`, I think we should also remove it from the array below.

File: packages/block-library/src/image/image.js [hunk 2]
```diff
@@ -544,13 +540,9 @@ export default function Image( {
...
-		// vanilla editor style. The following variable adds a buffer to this
-		// vanilla style, so 3rd party themes have some wiggleroom. This does,
-		// in most cases, allow you to scale the image beyond the width of the
-		// main column, though not infinitely.
-		// @todo It would be good to revisit this once a content-width variable
-		// becomes available.
-		const maxWidthBuffer = maxWidth * 2.5;
+		// vanilla editor style. We'll use the clientWidth here, to prevent the width
+		// of the image growing larger than the width of the block column.
+		const maxWidthBuffer = clientWidth;
```
Comment (kevin940726) [inline packages/block-library/src/image/image.js:547]: Should we compare with `maxWidth` here and choose the minimum?

```suggestion
		const maxWidthBuffer = Math.min( clientWidth, maxWidth * 2.5 );
```

**Review by kevin940726 — COMMENTED** [review]
Thanks for the PR! I haven't tested the branch yet but left some initial recommendations and questions.

File: packages/block-library/src/image/image.js (hunk 1 above)
Comment (d-alleyne) [reply packages/block-library/src/image/image.js]: Good idea.

File: packages/block-library/src/image/image.js (hunk 2 above)
Comment (d-alleyne) [reply packages/block-library/src/image/image.js:547]: @kevin940726 I believe the goal of this commit is to prevent the image from being larger than its container (`clientWidth`). Is there an instance where `maxWidth * 2.5` is smaller than the container?

Comment (kevin940726) [reply packages/block-library/src/image/image.js:547]: I'm not sure! It's a question and I'm not very familiar with the `maxWidth` settings. I think it's fine to keep just the `clientWidth` though.

**Review by kevin940726 — APPROVED** [review]
LGTM 👍 

I'm not familiar with the constraints of the image block but this tests good to me. Unless there are objections, I'd say let's merge this. We can always revert if we're missing something 🙂 .

**Comment by kevin940726** [comment]
I'd be nice if we could add some e2e tests for this, but it might be too complicated 🤔 .

**Comment by kevin940726** [comment]
Oh, we might want to also add a changelog entry for this?

**Comment by d-alleyne** [comment]
@kevin940726 Is anything else required of this?

**Comment by kevin940726** [comment]
Thanks for your patience! Due to a recent CI change, could you help rebase it again to get them green again? I'm not sure a changelog entry is required here, maybe not! I think once the CI is green we can merge this 👍
