### PR TITLE
Fix grid resizer drag over embed

### LINKED ISSUE #63279: Grid resizers not working well when resizing an embed block down
### Description

When a block containing an iframe, such as a YouTube embed, is placed within a Grid block and set to span multiple columns, trying to resize it down to a smaller size with the handles doesn't always work as expected, especially when resizing over the iframe area itself (dragging the handles over the caption space below works fine).

This is likely because the event listeners responsible for the resizing can't follow events inside the area of the iframe.

### Step-by-step reproduction instructions

1. Add a Grid block to a post or template;
2. Add a YouTube block inside it, and resize it to take up two columns;
3. Try to resize the block back down to one column with the resize handles and observe the flaky behaviour.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/8096000/278a6b52-fb91-4408-8acc-205591a68375

### Environment info

Latest Gutenberg and also WP 6.6.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by stokesman**
## What?
A bug fix for grid resizing.

## Why?
To fix #63279 where dragging to resize grid items is impeded if the grid item is an object/embed/iframe.

## How?
Uses [`setPointerCapture`](https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture)

### No flaky drag over embed with iframe
1. Add a Grid block to a post or template;
2. Add a YouTube block inside it, and resize it to take up two columns;
3. Try to resize the block back down to one column and note the dragging responds as expected.

### No regression of stuck dragging when releasing the drag with the pointer off of the drag handle
4. Resize the block and be sure to release the drag somewhere that the drag handle is not under the pointer

## Screenshots or screencast 

https://github.com/user-attachments/assets/9cdf84cc-6866-40bc-9c66-2914048592d5

### CODE REVIEW

File: packages/block-editor/src/components/grid/grid-item-resizer.js [hunk 1]
```diff
@@ -119,28 +119,22 @@ function GridItemResizerInner( {
...
 				boundsByDirection
+				onPointerDown={ ( { target, pointerId } ) => {
+					/*
+					 * Captures the pointer to avoid hiccups while dragging over objects
+					 * like iframes and ensures that the event to end the drag is
+					 * captured by the target (resize handle) whether or not it’s under
+					 * the pointer.
+					 */
+					target.setPointerCapture( pointerId );
+				} }
```
Comment (stokesman) [inline packages/block-editor/src/components/grid/grid-item-resizer.js:130]: I think it’d nice to put this in `ResizableBox` as it should be okay for any use case.
<details><summary>I gave it a quick try but typing it perfectly is an exercise I didn’t complete (had to use `@ts-ignore`).</summary>

```diff
diff --git a/packages/components/src/resizable-box/index.tsx b/packages/components/src/resizable-box/index.tsx
index 1b05270ea0..96c3044b7b 100644
--- a/packages/components/src/resizable-box/index.tsx
+++ b/packages/components/src/resizable-box/index.tsx
@@ -9,7 +9,7 @@ import { forwardRef } from '@wordpress/element';
 import clsx from 'clsx';
 import { Resizable } from 're-resizable';
 import type { ResizableProps } from 're-resizable';
-import type { ReactNode, ForwardedRef } from 'react';
+import type { ReactNode, ForwardedRef, PointerEventHandler } from 'react';
 
 /**
  * Internal dependencies
@@ -92,6 +92,7 @@ type ResizableBoxProps = ResizableProps & {
 	showHandle?: boolean;
 	__experimentalShowTooltip?: boolean;
 	__experimentalTooltipProps?: Parameters< typeof ResizeTooltip >[ 0 ];
+	onPointerDown: PointerEventHandler;
 };
 
 function UnforwardedResizableBox(
@@ -116,6 +117,17 @@ function UnforwardedResizableBox(
 			handleStyles={ HANDLE_STYLES }
 			ref={ ref }
 			{ ...props }
+			// @ts-ignore -- Ignore that ResizableProps does not include `onPointerDown`
+			onPointerDown={ ( event ) => {
+				/*
+				 * Captures the pointer to avoid hiccups while dragging over objects
+				 * like iframes and ensures that the event to end the drag is
+				 * captured by the target (resize handle) whether or not it’s under
+				 * the pointer.
+				 */
+				event.target.setPointerCapture( event.pointerId );
+				props.onPointerDown( event );
+			} }
 		>
 			{ children }
 			{ showTooltip && <ResizeTooltip { ...tooltipProps } /> }

```
</details>

Comment (noisysocks) [reply packages/block-editor/src/components/grid/grid-item-resizer.js:130]: Ideally this would be fixed in `re-resizable` but you could do something like this as a workaround:

```diff
diff --git a/packages/components/src/resizable-box/index.tsx b/packages/components/src/resizable-box/index.tsx
index 1b05270ea0b..28d3a7cea74 100644
--- a/packages/components/src/resizable-box/index.tsx
+++ b/packages/components/src/resizable-box/index.tsx
@@ -9,7 +9,7 @@ import { forwardRef } from '@wordpress/element';
 import clsx from 'clsx';
 import { Resizable } from 're-resizable';
 import type { ResizableProps } from 're-resizable';
-import type { ReactNode, ForwardedRef } from 'react';
+import type { ReactNode, ForwardedRef, PointerEventHandler } from 'react';
 
 /**
  * Internal dependencies
@@ -87,11 +87,19 @@ const HANDLE_STYLES = {
 	bottomLeft: HANDLE_STYLES_OVERRIDES,
 };
 
+declare module 're-resizable' {
+	// eslint-disable-next-line @typescript-eslint/no-shadow
+	interface ResizableProps {
+		onPointerDown: PointerEventHandler;
+	}
+}
+
 type ResizableBoxProps = ResizableProps & {
 	children: ReactNode;
 	showHandle?: boolean;
 	__experimentalShowTooltip?: boolean;
 	__experimentalTooltipProps?: Parameters< typeof ResizeTooltip >[ 0 ];
+	onPointerDown: PointerEventHandler;
 };
 
 function UnforwardedResizableBox(
@@ -116,6 +124,11 @@ function UnforwardedResizableBox(
 			handleStyles={ HANDLE_STYLES }
 			ref={ ref }
 			{ ...props }
+			onPointerDown={ ( event ) => {
+				const target = event.target as Element;
+				target.setPointerCapture( event.pointerId );
+				props.onPointerDown( event );
+			} }
 		>
 			{ children }
 			{ showTooltip && <ResizeTooltip { ...tooltipProps } /> }
```

**Review by noisysocks — APPROVED** [review]
This is great! TIL about `setPointerCapture`. Love that you've gotten rid of the `once` hack, too. 

Tested that this fixes the bug and there's no regression of https://github.com/WordPress/gutenberg/pull/61668.

File: packages/block-editor/src/components/grid/grid-item-resizer.js (hunk 1 above)
Comment (stokesman) [reply packages/block-editor/src/components/grid/grid-item-resizer.js:130]: Thanks for the tip!
