### PR TITLE
Show PostFeaturedImage in editor

### LINKED ISSUE #25410: Display the Post Featured Image on the editor and not a placeholder.
**Describe the bug**
Currently when you insert a `PostFeaturedImage` block is displayed only a placeholder.

This block works with FSE enabled only.

**Expected behavior**
The featured image should be shown if available.

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/25410

Currently when you insert a PostFeaturedImage block is displayed only a placeholder.
This PR displays the image properly.

There are going to be follow up PRs to enhance this block's functionality, like the selecting size, add link etc..

## How has this been tested?
Locally.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-library/src/post-featured-image/edit.js [hunk 1]
```diff
@@ -1,35 +1,40 @@
...
+		'featured_media',
+		postId
 	);
 	const media = useSelect(
 		( select ) =>
 			featuredImage && select( 'core' ).getMedia( featuredImage ),
 		[ featuredImage ]
 	);
-	return media ? (
+	if ( ! media ) {
```
Comment (ntsekouras) [inline packages/block-library/src/post-featured-image/edit.js:21]: We need to show something to not confuse the users with no content at all. This is not displayed in front-end though. Maybe handle with a different message to let them know??

Any thoughts?

File: packages/block-library/src/post-featured-image/edit.js [hunk 2]
```diff
@@ -1,35 +1,40 @@
...
+		return __( 'Featured Image is not set' );
+	}
+	const alt = media.alt_text || `{postType} Featured Media`;
```
Comment (ntsekouras) [inline packages/block-library/src/post-featured-image/edit.js:24]: Not 100% sure about this fallback `alt`. It's definitely not applicable to `posts` though, so it should change somehow..

Comment (draganescu) [reply packages/block-library/src/post-featured-image/edit.js:24]: I believe we use a message like "No alternative text set" ...

Comment (ntsekouras) [reply packages/block-library/src/post-featured-image/edit.js]: I changed it :)

File: packages/block-library/src/post-featured-image/edit.js (hunk 1 above)
Comment (mcsf) [reply packages/block-library/src/post-featured-image/edit.js:21]: We could probably draw inspiration from how we handle empty states elsewhere in Gutenberg by inviting the user to edit:

Captura de ecrã 2020-09-25, às 17 46 13

But this is a general design problem, so /cc @mapk @jasmussen

Comment (jasmussen) [reply packages/block-library/src/post-featured-image/edit.js:21]: Thanks for the ping. This is what I see in this branch:

Screenshot 2020-09-28 at 08 26 41

My instinct, when reading the context alone, was to suggest that we shouldn't show anything. Because just like an empty social links placeholder, if it's empty, there's nothing to show. 

However seeing it only in the site editor context and when editing templates, it definitely feels like a different heuristic is needed, one which does indeed show an empty state even if on some pages you won't add a featured image.

I would like us to eventually find a better design for the placeholders, one which better scales to small contexts, and also possibly looks a little bit like the block itself when finalized — right now it's just a sequence of white sheets with dark borders. And once we have that pattern it should be used for dropzones and placeholders alike. Here's a work in progress mockup for a dropzone in the Cover sidebar that I've abandoned because it's not very good:

Screenshot 2020-09-28 at 08 29 40

Screenshot 2020-09-28 at 08 28 34

However the point is the same — the placeholder should indicate the block that will land there, and can sometimes work as a dropzone. 

---

In the mean time, we should do what Miguel suggests, and just reuse the current placeholder material. But I'm not sure it's helpful to show that giant 200px tall sheet — because after all, there are posts where you won't add a featured image. So maybe go with a small chip for now:

Screenshot 2020-09-28 at 08 34 07

Also, the text should be rephrased because in the site editor context, you _can't_ set a featured image, so suggesting you could is going to confuse. 

Also I wonder, is there a better name than "Post Featured Image"? Could it just be "Featured Image"?

Comment (ntsekouras) [reply packages/block-library/src/post-featured-image/edit.js:21]: Thanks for reviewing @mcsf and @jasmussen!

>Also, the text should be rephrased because in the site editor context, you can't set a featured image, so suggesting you could is going to confuse.

Actually I think the first step forward is to show the previews at least and then give the ability to users to edit things here. This applies to content as well based on this comment here: https://github.com/WordPress/gutenberg/issues/25394#issuecomment-699083858.

The actual issue that this PR solves is that now on master the `featured image` when exist is not shown at all. I don't believe design and the `not set` placeholder should be a blocker for this PR and we can revisit with a follow up PR to handle the case of not having set a featured image. 

We can even show nothing for not having a featured image for now, as this is the current behavior. What do you think?

Comment (jasmussen) [reply packages/block-library/src/post-featured-image/edit.js:21]: Oh of course — that's valuable context — when the featured image is inside a query block, it will actually show the featured image of the _post queried_ 🤦  — yes absolutely agree, that needs to show the image directly, if set, and perhaps the chip above if not. 

> We can even show nothing for not having a featured image for now, as this is the current behavior. What do you think?

I would agree with your assessment that it's important to move forward with the baseline feature to get it working. But it highlights a really interesting template building question that's good to think about for future iteration, because even though showing nothing would seem correct in this case, the featured image "spot" seems like a unique situation. CC: @MichaelArestad @jameskoster @shaunandrews

**Review by mcsf — APPROVED** [review]
I'll leave it up to you to manage how much of the design improvements you want to get in this PR vs. subsequent PRs. I hereby unblock you. :D

**Comment by ntsekouras** [comment]
Thanks @mcsf 👍 ! I'll wait for some feedback from @jasmussen 's ping here: https://github.com/WordPress/gutenberg/pull/25412#discussion_r495807817 and we'll see how it goes from there.

File: packages/block-library/src/post-featured-image/edit.js (hunk 1 above)
Comment (jameskoster) [reply packages/block-library/src/post-featured-image/edit.js:21]: Hoo boy, this is a fun one. My current thoughts, fwiw:

If the template includes the featured image block then it should be visible in the site editor (in one form or another) _regardless_. 

When context is provided (e.g. I'm editing my singular template with the "Hello world" post loaded in to it) we should load the actual image if one is provided. This aligns with how other "token" blocks like the post title behave. Whether it should be possible to _edit_ the image in this scenario is less clear to me. It doesn't help that it is currently possible to edit the post _content_, but not other details like the _date_ or the _title_. It's a question of how much we want to blur the lines between template editing and content editing, and I feel we should be consistent in that behaviour. 

If I'm editing the same "Single" template with no context, the placeholder should be noninteractive and serve purely as a visual indication of where the block appears in the associated template.

Comment (jasmussen) [reply packages/block-library/src/post-featured-image/edit.js:21]: > When context is provided (e.g. I'm editing my singular template with the "Hello world" post loaded in to it) we should load the actual image if one is provided. This aligns with how other "token" blocks like the post title behave. Whether it should be possible to edit the image in this scenario is less clear to me. It doesn't help that it is currently possible to edit the post content, but not other details like the date or the title. It's a question of how much we want to blur the lines between template editing and content editing, and I feel we should be consistent in that behaviour.

Yeah that sums up the challenge. 

It looks like an image, but it isn't an image. However as soon as you select it, it should be clear that it's a featured image block. At least that feels sufficient to move forward to me.

What still feels vague to me is the no-content situation where you don't have any posts that add featured images, and you're only really building out the template. What shows up there? Given the insights from this discussion, perhaps it shouldn't be a dropzone. 

In that vein, will there ever be a situation where you are editing just a template, but with no content filled in? Seems like this would only ever happen on a brand new blog where actively delete pages and posts, no?

Comment (ntsekouras) [reply packages/block-library/src/post-featured-image/edit.js:21]: >In that vein, will there ever be a situation where you are editing just a template, but with no content filled in?

I'm not sure for the current behavior, but that's something we'll need to be able to support and have a good design. 

>What still feels vague to me is the no-content situation where you don't have any posts that add featured images, and you're only really building out the template. What shows up there? Given the insights from this discussion, perhaps it shouldn't be a dropzone.

Based on the whole discussion I feel that the best choice for now is to have a simple non-editable placeholder like @jasmussen's screenshot above. The editable/non-editable `PostBlocks` is a different matter, that will handled in another issue and should definitely be consistent as @jameskoster has mentioned. For start I think the goal is to be non-editable, but we'll revisit again.

@jasmussen do you have a similar styled `chip` in mind I can see the styles, so as to be consistent?

Comment (jasmussen) [reply packages/block-library/src/post-featured-image/edit.js:21]: Yep seems good to move forward in a light weight way because we can always improve later.

The basic chip would be good to get.

https://github.com/WordPress/gutenberg/blob/e259fd03b7ba4852ef6b01be06ad4f5c4a100eec/packages/block-library/src/embed/editor.scss#L19

Lines 19-21 contain the css to make it work. I'd add some padding as well.

Comment (ntsekouras) [reply packages/block-library/src/post-featured-image/edit.js:22]: Thanks! I added the chip.
