### PR TITLE
Fix browser history when synchronising state with urls

### LINKED ISSUE #48726: [Site Editor] White screen when using browser back button.
### Description

A white screen appears when using the browser's back button after navigating to the Editor, clicking in the navigation sidebar, then clicking the browser's back button once/twice.

### Step-by-step reproduction instructions

1. Navigate to the Site Editor.
2. Click on the navigation sidebar.
3. Click the browser's back button 🐞  Nothing happens
4. Click the browser's back button again 🐞  Get a white screen with `/site-editor.php?canvas=init&path=%2F` (or similar).

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/79332690/222730102-a4ec0e72-6a8c-4c87-ba71-b334cb37ec65.mp4

### Environment info

- WordPress: `trunk` going as far back as 6.2 Beta 1
- Gutenberg: With/without Gutenberg `trunk` active.
- Theme: Twenty-Twenty Three
- Browser: Chrome
- Plugins: No other plugins activated.
- OS: Ubuntu (WSL2 - Windows 10)
- PHP: 7.4
- @mukeshpanchal27 and @ndiego have confirmed it reproduced on their ends.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by youknowriad**
closes #48726

## What?

This PRs fixes the browser history when navigating the site editor.

## How?

- It avoids persisting default values in urls (path=/ and canvas=view)
- Prevents unnecessary history changes.

## Testing Instructions

1- Open the site editor
2- Click browser "back" button
3- you should be back in the dashboard properly
4- Testing using Chrome, Firefox or Edge (in trunk it's broken with these)

### CODE REVIEW

**Comment by costdev** [comment]
Seems to fix the issue on my end! Nice one @youknowriad!

Out of curiosity, on a separate note (not caused by this PR), when I click "Template Parts" and click "Footer", for example, I need to click the browser's back button twice to actually go back. Is this related or a separate issue?

**Review by Mamaduka — COMMENTED** [review]
This partially fixes the reported issue, but when I navigate around in Site Editor and then use the Back button, I end up with `wp-admin/site-editor.php?canvas=init&path=%2Fwp_template%2Ftwentytwentythree%252F%252Fhome` URL, which produces white screen.

**Comment by costdev** [comment]
@Mamaduka I can't reproduce this myself. Do you have some steps I could follow to see if I can reproduce?

**Comment by youknowriad** [comment]
@Mamaduka which browser are you using?

**Comment by youknowriad** [comment]
> Out of curiosity, on a separate note (not caused by this PR), when I click "Template Parts" and click "Footer", for example, I need to click the browser's back button twice to actually go back. Is this related or a separate issue?

I can reproduce this issue, it seems there's still an extra history.push. Let's see if I can find it.

**Comment by Mamaduka** [comment]
My bad! It looks like this was a browser cache issue. Sorry for the confusion.

P.S. I'm testing with Chrome.

**Comment by youknowriad** [comment]
It turns out that when you do `history.push` you override query arguments but if you omit one argument from the call, it is kept in the URL. This is what was causing the double back button issue. I think it should be fixed now.

**Comment by youknowriad** [comment]
While the previous fix works, I'm also exploring if I can change how "push" works instead.

**Comment by costdev** [comment]
[85f2370](https://github.com/WordPress/gutenberg/pull/48731/commits/85f23706b94b2c7c3c4f6d9ce185904e72916018) fixes the double back button issue but also appears to flash the "Home" submenu briefly.

See:
https://user-images.githubusercontent.com/79332690/222753579-b5542f35-6da9-426e-9400-00669611831f.mp4

File: packages/edit-site/src/components/template-details/index.js [hunk 1]
```diff
@@ -32,7 +32,6 @@ export default function TemplateDetails( { template, onClose } ) {
 
 	// TODO: We should update this to filter by template part's areas as well.
 	const browseAllLinkProps = useLink( {
-		canvas: 'view',
```
Comment (Mamaduka) [inline packages/edit-site/src/components/template-details/index.js:35]: I think this causes regression of #48301.

**Comment by Mamaduka** [comment]
@youknowriad, I also noticed that if I refresh `canvas` in "edit" mode, I end up in the "view" mode. I believe you fixed this issue a few weeks ago.

File: packages/edit-site/src/components/template-details/index.js (hunk 1 above)
Comment (youknowriad) [reply packages/edit-site/src/components/template-details/index.js:35]: it should be "undefined" now because "view" is the default value. But I guess it suffers from the issue I talk about here https://github.com/WordPress/gutenberg/pull/48731#issuecomment-1453654827

**Comment by youknowriad** [comment]
Ok, I think I've fixed all the issues. I'm not entirely satisfied with these syncing hooks and I believe we need e2e tests for all these flows but this should be good maybe for now?

**Comment by apeatling** [comment]
This is working perfectly when going straight from the dashboard to the site editor then hitting the back button.

One thing I noticed is when you go dashboard > site editor > [back to templates sidebar view] then try the browser back button, there's a couple of extra dead back button clicks in there between the site editor and the dashboard. I tried to capture it in this gif:

**Comment by costdev** [comment]
@apeatling Noticing that too when I do the following:

1. Navigate to the "Home" template.
2. Refresh - This is the bit that's different for me.
3. Click the arrow to go back to the templates sidebar view.
4. Click the browser back button a few times.

I'm also still noticing the flash of the "Home" sidebar view when I do the following:
1. Navigate to the "Footer" template part.
2. Click the arrow to go back to the "Template Parts" sidebar view.
3. Navigate to the "Header" template part.
4. Click back in the browser. Each time you click, look for the flash of the "Home" sidebar view.

**Comment by youknowriad** [comment]
I think I fixed both of these issues. I'd appreciate some checks.

@apeatling I also noticed that on your video you land directly on a sub menu when opening the site editor. I'm aware of this issue but it's specific to old WP versions (there's a redirect that we can't override in Gutenberg). If you test with WP trunk, you'll notice that you land on the "root" of the site editor.

File: packages/edit-site/src/components/sync-state-with-url/use-sync-canvas-mode-with-url.js [hunk 2]
```diff
@@ -20,22 +20,47 @@ export default function useSyncCanvasModeWithURL() {
...
+		) {
+			setCanvasMode( 'view' );
+		} else if (
+			canvasInUrl === 'edit' &&
+			currentCanvasMode.current !== 'edit'
+		) {
+			setCanvasMode( 'edit' );
 		}
-	}, [ canvasInUrl ] );
+	}, [ canvasInUrl, params ] );
```
Comment (ntsekouras) [inline packages/edit-site/src/components/sync-state-with-url/use-sync-canvas-mode-with-url.js]: I guess you wanted to add `params` to the above hook.

**Comment by youknowriad** [comment]
I added some e2e tests to cover these flows.

File: packages/edit-site/src/components/sync-state-with-url/use-sync-canvas-mode-with-url.js (hunk 2 above)
Comment (youknowriad) [reply packages/edit-site/src/components/sync-state-with-url/use-sync-canvas-mode-with-url.js]: yeah something like that, it should be fixed now.

File: packages/edit-site/src/components/template-details/index.js [hunk 3]
```diff
@@ -32,10 +32,8 @@ export default function TemplateDetails( { template, onClose } ) {
...
-		postType: template.type,
-		postId: undefined,
 		path: '/' + template.type + '/all',
+		canvas: undefined,
```
Comment (ntsekouras) [inline packages/edit-site/src/components/template-details/index.js]: Do we still need this, since you changed the `history.push`?

Comment (youknowriad) [reply packages/edit-site/src/components/template-details/index.js]: probably not.

File: test/e2e/specs/site-editor/browser-history.spec.js [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+	test.afterAll( async ( { requestUtils } ) => {
+		await requestUtils.activateTheme( 'twentytwentyone' );
+	} );
+
+	test( 'Back button works properly', async ( { admin, page } ) => {
+		// Navigate to a template.
+		await admin.visitAdminPage( 'index.php' );
+		await admin.visitSiteEditor();
+
+		expect( page.url() ).toEqual( baseUrl + '/wp-admin/site-editor.php' );
```
Comment (kevin940726) [inline test/e2e/specs/site-editor/browser-history.spec.js]: You can use `toHaveURL` and omit `baseUrl`:

```suggestion
		await expect( page ).toHaveURL( '/wp-admin/site-editor.php' );
```

File: test/e2e/specs/site-editor/browser-history.spec.js [hunk 5]
```diff
@@ -0,0 +1,65 @@
...
+
+		// Navigate to the template list
+		await page.click( 'role=button[name="Show template details"]' );
+		await page.click( 'role=link[name="Manage all templates"]' );
+
+		expect( page.url() ).toEqual(
+			baseUrl + '/wp-admin/site-editor.php?path=%2Fwp_template%2Fall'
+		);
+
+		const title = page.locator( '.edit-site-list-header__title' );
```
Comment (kevin940726) [inline test/e2e/specs/site-editor/browser-history.spec.js]: Using class name selectors is generally not recommended. Try role selectors instead:

```suggestion
		const title = page.getByRole( 'heading', { level: 1 } );
```

Or if you don't need the level 1 heading but want the tab's title:

```js
await expect( page ).toHaveTitle( /^Templates/ );
```

File: packages/edit-site/src/components/sidebar-navigation-screen-templates/index.js [hunk 6]
```diff
@@ -72,6 +72,7 @@ export default function SidebarNavigationScreenTemplates() {
 
 	const browseAllLink = useLink( {
 		path: '/' + postType + '/all',
+		canvas: undefined,
```
Comment (ntsekouras) [inline packages/edit-site/src/components/sidebar-navigation-screen-templates/index.js]: Same here, it doesn't seem to be needed.

**Review by ntsekouras — APPROVED** [review]
I've tested this PR quite a lot and everything seems to work well. Thanks Riad!

File: test/e2e/specs/site-editor/browser-history.spec.js (hunk 5 above)
Comment (youknowriad) [reply test/e2e/specs/site-editor/browser-history.spec.js]: Personally, I think that just a random guideline, heading levels or classnames are subject to change similarly. But it's fine, I can change the selector.

Comment (kevin940726) [reply test/e2e/specs/site-editor/browser-history.spec.js]: I would argue that accessibility-wise, heading levels should rarely change (and if it does change, it often represents a change to the user flow too), while class names are implementation details and not exposed to the end users. Let's follow the established [best practices](https://github.com/WordPress/gutenberg/tree/trunk/docs/contributors/code/e2e#use-accessible-selectors) until we change them ❤️ . (Feel free to open an issue/PR to discuss about this!)

Comment (youknowriad) [reply test/e2e/specs/site-editor/browser-history.spec.js]: If that's what you all think we should do, it's fine, it's not important enough for me to lose time on it.

**Comment by ntsekouras** [comment]
I just cherry-picked this PR to the wp/6.2 branch to get it included in the next release: e0648136a0

File: packages/edit-site/src/components/sync-state-with-url/use-sync-canvas-mode-with-url.js [hunk 7]
```diff
@@ -20,22 +20,52 @@ export default function useSyncCanvasModeWithURL() {
...
+
+		if (
+			canvasMode === 'view' &&
+			currentCanvasInUrl.current !== undefined
+		) {
 			history.push( {
-				...params,
-				canvas: canvasMode,
+				...currentUrlParams.current,
+				canvas: undefined,
```
Comment (ntsekouras) [inline packages/edit-site/src/components/sync-state-with-url/use-sync-canvas-mode-with-url.js:52]: I'm still debugging but do you remember why we needed to set `undefined` here? There is a problem when we want to push to history something like:
```
history.push( {
	postId: post.id,
	postType: post.type,
	canvas: 'edit',
} );
```
The above example is used in pages list(click the title or `edit` in actions) and creates unexpected results, since at first the canvas mode is `view` in the state and we update it here. So an example like the above doesn't seem to have a good way of being achieved. and adds one more entry to history too. 

I mean, if we want to push to history `edit` canvas, should we just use `setCanvasMode( 'edit' )` and leave the `canvas` param get handled by this hook? 🤔

Comment (youknowriad) [reply packages/edit-site/src/components/sync-state-with-url/use-sync-canvas-mode-with-url.js:52]: When I first wrote this PR, unsetting the canvas from the url meant you're going to "view" mode. I think that's good because on `site-editor.php` you don't specify anything and it loads and there's no rewriting of the url.  IMO, `view` should never be present in the URL, it's either not set (undefined) or "edit".

Comment (youknowriad) [reply packages/edit-site/src/components/sync-state-with-url/use-sync-canvas-mode-with-url.js:52]: In other words `undefined` in the url, should map strictly to `view` in state.

Comment (ntsekouras) [reply packages/edit-site/src/components/sync-state-with-url/use-sync-canvas-mode-with-url.js:52]: I don't disagree with the `view` being absent from url. The issue still exists though when we want to go directly to `edit` from `view` and it seems we probably can't avoid using `setCanvasMode` in such cases. I'll explore more and open a PR.

Comment (youknowriad) [reply packages/edit-site/src/components/sync-state-with-url/use-sync-canvas-mode-with-url.js:52]: What I found is that we shouldn't be using both `setCanvasMode` and `history.push` together. It's one or the other because of the "sync process" as otherwise it creates a race condition. Not sure that helps.

Comment (ntsekouras) [reply packages/edit-site/src/components/sync-state-with-url/use-sync-canvas-mode-with-url.js:52]: I got that, that's what I'm trying to figure out how to solve in the best possible way. Thanks!
