### PR TITLE
Layout child fixed size should not be fixed by default and should always have a value set

### LINKED ISSUE #46116: It's possible to set a block layout to have a fixed width, but not include a value
When you switch to 'Fixed' from the other options the text input is empty, and no fixed value seems to be set on the frontend. 

Screenshot 2022-11-28 at 12 20 27

This makes the fixed width option feel a bit buggy.

One solution might be to treat the inherent width (IE the width if set to 'Fit') as a fallback, which the input will be populated with even if left empty.

### PR DESCRIPTION
**Pull request by tellthemachines**
## Why?

Fixes #46116 and addresses [this discussion](https://github.com/WordPress/gutenberg/pull/45364#issuecomment-1327736069)

Makes fixed flex child size shrinkable by default, with optional toggle to un-shrink it. Also makes sure that a value for 'fixed' setting exists.

## How?

`flex-shrink` should only be `0` if the block is explicitly set to unshrinkable.

## Testing Instructions

1. Add a Row block to a post and add a couple of child blocks in it;
2. Select a child block and under "Dimensions" in the sidebar select "Width";
3. Set width to "fixed", add a fixed size e.g. `500px` in the input, save;
4. Verify that on a small viewport the fixed width block shrinks and doesn't overflow it.
5. Check the "Allow block to break out of layout" toggle, save;
6. Verify that now the fixed width block is always the same width independently of viewport size.
7. Remove fixed width completely from block;
8. Deselect then reselect the block;
9. Verify that width toggle has been set back to 'fit'.

## Screenshots or screencast 
Screenshot 2022-11-29 at 3 13 48 pm

### CODE REVIEW

File: packages/block-editor/src/hooks/child-layout.js [hunk 1]
```diff
@@ -41,7 +43,21 @@ export function ChildLayoutEdit( {
 } ) {
 	const { style = {} } = attributes;
 	const { layout: childLayout = {} } = style;
-	const { selfStretch, flexSize } = childLayout;
+	const { selfStretch, flexSize, breakOutOfLayout = false } = childLayout;
+
+	useEffect( () => {
```
Comment (andrewserong) [inline packages/block-editor/src/hooks/child-layout.js:47]: I remember we needed to remove the useEffect in the Group block back in https://github.com/WordPress/gutenberg/pull/44176. Will adding a `useEffect` here have similar performance concerns as the earlier Group block useEffect?

I'm wondering if we need to change the attribute via `setAttribute` or if it'd be possible to use a different temporary variable for determining which control to display, if it's more about which tab is shown when the block is initially selected, rather than changing the attributes for the block 🤔

File: lib/block-supports/layout.php [hunk 2]
```diff
@@ -334,10 +334,11 @@ function gutenberg_render_layout_support_flag( $block_content, $block ) {
 		$child_layout_styles = array();
 
 		if ( 'fixed' === $block['attrs']['style']['layout']['selfStretch'] && isset( $block['attrs']['style']['layout']['flexSize'] ) ) {
+			$has_shrink            = isset( $block['attrs']['style']['layout']['breakOutOfLayout'] ) && $block['attrs']['style']['layout']['breakOutOfLayout'];
```
Comment (andrewserong) [inline lib/block-supports/layout.php]: Tiny style nit (don't worry about updating this if you prefer the explicit approach):

Would it be worth using `_wp_array_get` here with a default value of `false`?

E.g. something like `_wp_array_get( $block, array( 'attrs', 'style', 'layout', 'breakOutOfLayout' ), false )`

**Review by andrewserong — COMMENTED** [review]
This is testing nicely for me, and I like the idea of adding the toggle control 👍

Just left a comment about the `setAttributes` call within `useEffect`, since I think I remember a similar thing causing performance issues with the Group block in the past, but I can't quite remember why it did, I'm sorry! 😅

File: packages/block-editor/src/hooks/child-layout.js (hunk 1 above)
Comment (tellthemachines) [reply packages/block-editor/src/hooks/child-layout.js:47]: Offhand I'd think not because this control only loads once the block is selected. I think the perf issues we were seeing with using an effect in the Group edit function were related to the editor content taking longer to load. 

In any case, I'm happy to change if there's a better approach! I played around with it a bit but couldn't find another way to tell if the component is rendering for the first time, or just updating as a result of a change of value.

Comment (andrewserong) [reply packages/block-editor/src/hooks/child-layout.js:47]: > Offhand I'd think not because this control only loads once the block is selected.

Ah, good point, yes, the rendering is neatly tucked away inside the `DimensionsPanel` isn't it — sounds like we can go with this approach for now and revisit if need be 👍

**Comment by jasmussen** [comment]
Thank you for this! It's nice to see this being mainly a "flex-shrink" toggle! 

I'd love for us to start with flex-shrink enabled by default, and add the toggle separately. I can sense you're concerned that we won't add such a toggle — I think we should, but I also think it needs the right prominence and placement, and a separate control like this probably isn't the right one.

The thing is, we have this same challenge for fluid typography, this one:

Screenshot 2022-11-29 at 10 35 48

Those 2.25rem in the screenshot are clamp-based fluid, despite being custom and explicit. It would be good for design to think of a universal interface for making these values non-fluid or non-responsive. One basic idea is to have this option live in the unit selector:
Screenshot 2022-11-29 at 10 35 53

Another is an explicit toggle that's integrated into the component-row itself, like "link/unlink". But it needs a little more design work, and it would be good to not hold up the flex-shrink change based on the toggle design. What do you think?

**Comment by jameskoster** [comment]
Thanks for working on this, I agree with everything Joen said re the toggle.

As for the original issue, it still feels a bit buggy that you can select a fixed width and save with the empty input. Could we auto-populate the input with the inherent value instead?

For example here:

Screenshot 2022-11-29 at 11 28 49

The calculated with is 135px, so when I click 'Fixed' in the width control, the input would automatically be populated with 135px. This would also help folks understand exactly what the 'Fixed' option means.

**Comment by jasmussen** [comment]
I took a stab at where a toggle might live in https://github.com/WordPress/gutenberg/issues/46128#issuecomment-1330539055

**Review by andrewserong — APPROVED** [review]
This is still working well for me after the removal of the toggle, and defaults to no shrink value being applied 👍

> The calculated with is 135px, so when I click 'Fixed' in the width control, the input would automatically be populated with 135px. This would also help folks understand exactly what the 'Fixed' option means.

That's a cool idea seeing if we can grab the inherent width and pre-populate it here. It can be challenging to introspect the width of elements reliably from within block controls, though, so I think that sounds like a good thing to look at in a follow-up after this PR lands.

**Comment by tellthemachines** [comment]
> Could we auto-populate the input with the inherent value instead?

I've tried doing this in the latest commit. How well it works depends on how many child blocks there are as well as their intrinsic sizes: how the flex container distributes values changes depending on whether the element has an explicit size or not. Weirdly enough, if the block's siblings are able to grow further, setting an explicit value equal to the block's current size can actually cause it to shrink:

smolfix

**Comment by tellthemachines** [comment]
> that sounds like a good thing to look at in a follow-up after this PR lands.

Oh whoops, just saw this now. That might have been best, but I just went and did it 😂

File: packages/block-editor/src/hooks/child-layout.js [hunk 3]
```diff
@@ -96,7 +108,7 @@ export function ChildLayoutEdit( {
 							},
 						} );
 					} }
-					value={ flexSize }
+					value={ flexSize || blockSize }
```
Comment (andrewserong) [inline packages/block-editor/src/hooks/child-layout.js]: Using the value as a fallback in all cases appears to cause an odd behaviour when editing / removing the fixed value altogether, because it winds up getting a closer to fresh value for the width. Here's a screengrab (initially set to `200px`, then after deleting the value and clicking out of the field, it sets it to `95px`:



Would it work to use `blockSize` within the `onChange` handler when switching between `fit` and `fixed` instead? Edit: ah wait, I see you're already doing that. I guess the question is then, do we need to include the fallback on `value`?

**Comment by andrewserong** [comment]
> Oh whoops, just saw this now. That might have been best, but I just went and did it 😂

No worries! I wasn't sure how hard it'd be to retrieve the value. Good work digging in so quickly!

File: packages/block-editor/src/hooks/child-layout.js (hunk 3 above)
Comment (tellthemachines) [reply packages/block-editor/src/hooks/child-layout.js]: I'm not sure I understand the question. If we remove the fallback from `value` the field won't be pre-populated, which I think is a requirement?

Comment (andrewserong) [reply packages/block-editor/src/hooks/child-layout.js]: >  If we remove the fallback from value the field won't be pre-populated, which I think is a requirement?

Ah, good point, my apologies, I missed that detail of the requirement that James mentioned. I'd been thinking of the Fit -> Fixed selection and not the saved empty Fixed state problem 🤔

Comment (tellthemachines) [reply packages/block-editor/src/hooks/child-layout.js]: No worries, always worth asking!

Comment (andrewserong) [reply packages/block-editor/src/hooks/child-layout.js]: Just thought I'd hack around a little bit. The only other way I could come up with addressing that requirement while preventing the `95px` issue from showing up, would be to add a bit of logic so that when the block is initially selected, it displays as if `fit` were selected if `fixed` is selected but `flexSize` is empty:

```js
	const [ showFit, setShowFit ] = useState();

	useEffect( () => {
		if ( selfStretch === 'fixed' && ! flexSize ) {
			setShowFit( true );
		}
	}, [] );
```

Then, in the `ToggleGroupControl` change handler we'd call `setShowFit( false )` whenever the value changes. And the bits where we're referring to `selfStretch` would become the slightly awkward:

```
				value={ showFit ? 'fit' : selfStretch || 'fit' }
				help={ helpText( showFit ? 'fit' : selfStretch ) }
```

With that in place, I think we could then remove the `blockSize` fallback in `value={ flexSize || blockSize }`, but overall it would be slightly different behaviour than what was asked for.

Feel free to ignore all that, though, I was mostly curious to better understand how it's working! 🙂

Comment (tellthemachines) [reply packages/block-editor/src/hooks/child-layout.js]: Wouldn't that hide the input altogether when it has no value? I'm not sure we want that; the idea is that if 'fixed' is selected the input should be pre-populated with the current width/height of the block, so we have to pass `blockSize` as the value unless there's an existing `flexSize`.

Comment (andrewserong) [reply packages/block-editor/src/hooks/child-layout.js]: > Wouldn't that hide the input altogether when it has no value?

Yes, it would hide it when initially selected if it doesn't have a `flexSize` value, and would default to display 'fit' instead. I'm not really advocating for that, but it was the only behaviour I could figure out that avoided accidentally displaying the wrong width value when a user clears out the Fixed input field and then tabs away.

Comment (andrewserong) [reply packages/block-editor/src/hooks/child-layout.js]: Another thought: the issue of the wrong width value only appears when you tab away from the cleared input field, and is correct again if you select another block and then click to re-select the block you were initially working on. Personally, I'd be fine with the idea of merging this PR as-is, and us continue to fix/tweak in follow-ups if need be.

**Comment by jameskoster** [comment]
> setting an explicit value equal to the block's current size can actually cause it to shrink

Could this be a rounding issue?

Going back to my screenshot in https://github.com/WordPress/gutenberg/pull/46139#issuecomment-1330486135, notice that the paragraph is actually `138.08px` wide. In the latest version of this PR I see the shrinking you mentioned, but it seems to be due to the width being set to `138px`. Apparently that .08 of a pixel makes a big difference because If I override it manually in the Inspector then there's no shrink.

Could we force values like this to round up to the next pixel? IE 138.00001 becomes 139. That might solve the shrinking problem?

**Comment by andrewserong** [comment]
Thanks for re-testing @jameskoster!

> Could this be a rounding issue? ... Could we force values like this to round up to the next pixel? That might solve the shrinking problem?

It doesn't seem to be a result of rounding, from hacking around locally to get it to round up. It looks like it's to do with what happens when we set an explicit `flex-basis` value without disabling `flex-shrink`. Here's a screengrab (in this one, the width is `129.23`, and I've hacked it to round up to the nearest pixel value, so the input says `130`, but the element still gets shrunk by the flex logic):
 


So, I think displaying a value unfortunately highlights the gap between the user entered value and the fuzziness of how `flex-basis` deals with that value. If we stick we pre-populating the value, I think we'll need to live with there being some kind of jumpiness.

As a workaround, one way to potentially deal with the jumpiness when toggling between Fit and Fixed would be to display the pixel value in the input field, but not actually set it on the block until a user changes the value. However, as soon as they go to change the value, they'd still see the jumpiness.

What do you think?

**Comment by jasmussen** [comment]
It seems okay that there's a little shift, even if it's curious. Can it be related to the box model? I.e. is it accurate if there's no padding?

**Comment by jameskoster** [comment]
I agree a little shift is ok, but perhaps its best to force an _upwards_ shift so that we eliminate the extreme text reflow we see in https://github.com/WordPress/gutenberg/pull/46139#issuecomment-1333100511? I guess adding a couple of pixels to the calculated value would solve it?

**Comment by andrewserong** [comment]
Thanks again for taking a look.

> Can it be related to the box model? I.e. is it accurate if there's no padding?

It doesn't appear to be, because we're applying `box-sizing: border-box` to the element in the editor UI when `flex-basis` is used, and the `offsetWidth` measurement gets that same measurement.

> I guess adding a couple of pixels to the calculated value would solve it?

I did a bit more digging, and the short answer appears to be that no, a couple of pixels won't solve it. I was curious to learn more about why that's the case, so there's a longer explanation below, hope y'all don't mind me sharing the longer version! 🙂

---

It's a really interesting one, but the issue appears to be with how browsers deal with `flex-basis` values, and I don't think we can reliably predict or calculate what the browser is going to do with the `flex-basis` value once it updates the block. In short, whichever calculation we go with will be wrong, because of the fuzzy nature of `flex-basis` when a flex item is allowed to shrink. Hopefully the following screenshot will help explain the problem a bit better.

In the below screenshot we have a Row block where the left two items are set to "Fit". In this case, we will set the left most block to "Fixed" and use its default value based on the calculation in this PR. Note the reflow, with the value being set to `157px`, which we retrieve by getting the `offsetWidth` from the block prior to setting `flex-basis`.

In order to get the width of the block to line up to roughly the same width of the original row, we need to set an explicit `flex-basis` value of around `200px`, which is significantly more than tweaking the values a little bit:

image

The reason for this seems to be touched on in the [MDN entry](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis) for flex-basis:

> The demo then changes the flex-basis on the first item. It will then grow and shrink from that flex-basis. This means that, for example, when the flex-basis of the first item is 200px, it will start out at 200px but then shrink to fit the space available with the other items being at least min-content sized.

Examining the block after applying the `200px` flex-basis in the above screenshot shows that the width that the browser winds up calculating for that element is `157px`, consistent with the shrink behaviour described:

image

So, where does this leave us? I think it means that if we remove `flex-shrink` (which I agree with), then we also need to accept that the value entered for `flex-basis` is different to what the browser outputs. This means that examining an existing element within the DOM, and retrieving its final width, is not a reliable indicator of a value to be used in `flex-basis`.

Based on this, in my view, I think I would probably lean toward abandoning attempting to pre-fill the `flex-basis` field at all, since the value is not going to be accurate. Alternately, accept that in situations where there is enough room, it'll be pretty close to correct, but as soon as the row is filled with other content, we will see a jump in the UI.

**Comment by andrewserong** [comment]
Since @tellthemachines isn't around today, and just in case it's desirable to get the `flex-shrink` removal landed prior to figuring out the desired behaviour for pre-populating the `Fixed` field, I've copied the `flex-shrink` removal over to a separate PR over in: https://github.com/WordPress/gutenberg/pull/46261 (I'm very happy to close that one out if everyone would prefer to wait until this one can land, of course).

**Comment by jameskoster** [comment]
Thanks for the digging! Perhaps I am misinterpreting, but it seems like a pretty big problem that setting a width of 200px in the settings doesn't actually result in a block that is 200px wide?

**Comment by tellthemachines** [comment]
Thanks for the detailed description of the problem @andrewserong ! The short of it is that, due to the way `flex` is implemented in browsers, it's not possible to pre-populate the size input in a reliable manner _unless_ we use `flex-shrink`. I'll revert the latest commit to this branch, which will leave us with the toggle being reset to `fit` if the user clicks away from the block without adding and explicit `fixed` value. This is the same as what happens in other parts of the UI, e.g.: when toggling the font size field to set a custom font size, that input is also not pre-populated.

**Comment by tellthemachines** [comment]
> Perhaps I am misinterpreting, but it seems like a pretty big problem that setting a width of 200px in the settings doesn't actually result in a block that is 200px wide?

This is always going to happen if we don't set `flex-shrink` to `0`. No matter what the width of the viewport, there's no guarantee that the item's actual width will be equal to its `flex-basis` (it would be the same if we set `width` instead of `flex-basis`). This is why I thought it important to be able to switch off the "smart" behaviour.
