### PR TITLE
Inserting a tag with Apostrophe throws an error

### LINKED ISSUE #17291: Tags: Single Apostrophe turns into &#039 in editor
**Describe the bug**
When adding a tag with an apostrophe,`'`, via Gutenberg -- the tag briefly disappears and the apostrophe appears as the HTML `&#039`.

It appears this is the only special character/symbol with this behavior.

The tag appears properly via the tag manager in WP-Admin but not in the editor.

If added via the tag manager (WP-Admin > Posts > Tags), the tag will appear properly on both the tag manager and the editor. 

**To reproduce**
1. Go to a post
2. Add a tag with an apostrophe
3. Tag may disappear but will be available via tag search.  The tag will show the apostrophe as `&#039`

**Expected behavior**
For the tag to properly display the apostrophe and not the HTML symbol code.

**Screenshots**

Video of adding a tag with an apostrophe via the editor: https://cld.wthms.co/qHOsTq

Example of what it looks like in the editor:
Screen Shot on 2019-08-24 at 12-29-01

Example of what things look like on the tags management page:
Screen Shot 2019-08-24 at 12 28 41

**Desktop (please complete the following information):**
 - OS: Latest MacOS
 - Browser: Tested in latest versions of Chrome, Safari, and Firefox
- Standard US English Keyboard

**Additional context**
- 6.4.0 / WP Core 5.2.2

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/17291

When inserting a tag with "'" as part of the tag I got error in the browser console. This PR fixes the issue and adds a test case to make sure tags with "'" work as expected.

## How has this been tested?
I verified I could add a tag with an Apostrophe in the name.

### CODE REVIEW

File: packages/editor/src/components/post-taxonomies/flat-term-selector.js [hunk 1]
```diff
@@ -34,8 +34,15 @@ const DEFAULT_QUERY = {
 	_fields: 'id,name',
 };
 const MAX_TERMS_SUGGESTIONS = 20;
+
+// Lodash unescape function handles &#39; but not &#039; which may be return in some API requests.
```
Comment (aduth) [inline packages/editor/src/components/post-taxonomies/flat-term-selector.js:38]: Which API requests? What other strings are those endpoints returning that we should be aware of?

Comment (jorgefilipecosta) [reply packages/editor/src/components/post-taxonomies/flat-term-selector.js:38]: Hi @aduth,
If one issues the following request:
```
wp.apiFetch( {
    path: 'wp/v2/tags?_locale=user',
    method: 'POST',
    data: { name: 'tag2321&#39;aa' },
} ).then( res => {
    console.log( res );
} );
```

The server returns "tag2321&#039;aa" instead of "tag2321&#39;aa" this caused a bug because we did not recognize the strings as equivalent. I'm not sure if there are additional cases it seems like a safer bet would be to use a regex replace to remove zeros at the left from encoding character codes? What do you think?
