### PR TITLE
Fix autocompletion in IE11

### LINKED ISSUE #3409: IE 11: typing / doesn't make the block autocomplete suggestions appear
In IE 11, typing `/` to make the blocks autocomplete suggestions appear, doesn't do anything. In the screenshot below: IE 11 and Chrome on Windows:

screenshot 108

### PR DESCRIPTION
**Pull request by brandonpayton**
## Description
This is a PR to fix autocompletion in IE11.

Fixes #3409.

## Details

The cause for this breakage is that IE11 doesn't dispatch `input` events for contenteditable, only for `<input>` and `<textarea>` elements.

The proposed fix is to update our TinyMCE component to listen for IE11's comparable `textinput` event and manually creating and dispatching an `input` on the same target. In addition, because `textinput` isn't dispatched for deletions, we also dispatch `input` for Delete and Backspace `keyup` events.

## How has this been tested?
Loaded Gutenberg in IE11, Chrome, Firefox, and Safari and exercised the block and user completers.

I also used the IE11 and Chrome debuggers to verify the fix is applied for just IE and that its event listeners are removed when unmounted.

## Screenshots 

screen shot 2018-05-09 at 1 18 09 pm

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by brandonpayton** [comment]
I'm finding that `compareDocumentPosition` only appears to work for testing direct containment. It's breaking when selection enters a grandchild of the container.

We can still use it if we want, but we'd need to loop and check if parent nodes are contained until we reach the document root or find containment.

**Comment by jorgefilipecosta** [comment]
Hi @brandonpayton thank you for creating this PR. I like this version and I think it is better when compared to what was proposed in https://github.com/WordPress/gutenberg/pull/5914 as it avoids the need for a new component.

> I'm finding that compareDocumentPosition only appears to work for testing direct containment. It's breaking when selection enters a grandchild of the container.
Would using the check used in https://github.com/WordPress/gutenberg/pull/5914 solve the problem:
```
				if ( ! container.contains( selection.anchorNode ) &&
					selection.anchorNode &&
					! container.textContent.includes( selection.anchorNode.textContent.trim() )
				) {
					throw new Error( 'Invalid assumption: expected selection to be within the autocomplete container' );
				}
```

**Comment by brandonpayton** [comment]
Hi @jorgefilipecosta, thanks for commenting on this. I'll work to clean this up for merge.

I haven't found a good feature test, so for now, I plan to conditionally add the `textinput` mapping to `input` when `/Trident/.test( navigator.userAgent )` is true. I don't like it, but it's better than nothing IMO.

> Would using the check used in https://github.com/WordPress/gutenberg/pull/5914 solve the problem:

I was uncomfortable with the string-based containment check because we could have false positives. It's not really that important because this is just for a development warning, but since we may want to use `Node#contains` elsewhere, I went ahead an added a `containsNode` function to `@wordpress/dom` that should should work cross-browser. It may deserve its own PR, but I'll see if we can just discuss it here.

**Comment by brandonpayton** [comment]
I played around with this a bit more and found a couple of things that could be used for a feature test:
1. Adding an empty text node to contenteditable in IE11 causes a `textinput` event to be dispatched.
2. Deleting a zero-width space using `document.execCommand( 'delete', false )` causes an `input` event to be dispatched in IE11 for `<input>` and `<textarea>` elements.

☝️ I'm posting this in case this is interesting to someone, but I don't want to use such complicated testing per TinyMCE instance, which is what we'd need to do since IE11 contenteditable input behavior depends on the element. Something like this is simpler and at least limited to IE11:
```javascript
const listenForTextInput =
  /Trident/.test( navigator.userAgent ) &&
  ! /input/i.test( tagName ) &&
  ! /textarea/i.test( tagName );
```

**Comment by noisysocks** [comment]
Is this still WIP?

**Comment by brandonpayton** [comment]
@noisysocks Yeah, I need to make the fix conditional and probably split out the change to `@wordpress/dom` to its own PR.

**Comment by brandonpayton** [comment]
It turns out that IE11's `textinput` isn't dispatched for deletions. We can probably use `keydown` or `keyup` to listen for backspaces and deletes, but we should be careful to preserve typical event ordering (keydown before input, input before keyup) since we're actually dispatching an `input` (or input-like) event in response.

I like that this fix produces a real `input` event, but on the other hand, I like how #5914 simply called the component's `onInput` method which skips the ordering concern.

I plan to look at this more tomorrow.

**Comment by brandonpayton** [comment]
This is ready for review.

File: editor/components/rich-text/tinymce.js [hunk 1]
```diff
@@ -96,6 +182,23 @@ export default class TinyMCE extends Component {
...
+		 * `null` when unmounting.
+		 */
+		if ( this.removeInternetExplorerInputFix ) {
+			this.removeInternetExplorerInputFix();
+		}
+
+		this.removeInternetExplorerInputFix =
+			editorNode && needsInternetExplorerInputFix( editorNode ) ?
+				applyInternetExplorerInputFix( editorNode ) :
+				null;
```
Comment (noisysocks) [inline editor/components/rich-text/tinymce.js]: Minor: I think this would read better as an `if`, e.g.

```js
if ( editorNode && needsInternetExplorerInputFix( editorNode ) ) {
	this.removeInternetExplorerInputFix = applyInternetExplorerInputfix( editorNode );
}
```

File: editor/components/rich-text/tinymce.js [hunk 2]
```diff
@@ -96,6 +182,23 @@ export default class TinyMCE extends Component {
 		} );
 	}
 
+	saveEditorNode( editorNode ) {
```
Comment (noisysocks) [inline editor/components/rich-text/tinymce.js]: Minor: `bindEditorNode` is more consistent with how we name these sorts of functions elsewhere in the codebase.

File: editor/components/rich-text/tinymce.js [hunk 3]
```diff
@@ -9,15 +9,101 @@ import classnames from 'classnames';
...
+ * Determines whether we need a fix to provide `input` events for contenteditable.
+ *
+ * @param {Element} editorNode The root editor node.
+ *
+ * @return {boolean} A boolean indicating whether the fix is needed.
+ */
+function needsInternetExplorerInputFix( editorNode ) {
+	return (
+		// Rely on userAgent in the absence of a reasonable feature test for contenteditable `input` events.
+		/Trident/.test( window.navigator.userAgent ) &&
```
Comment (noisysocks) [inline editor/components/rich-text/tinymce.js]: Could we borrow what Modernizr does here? Or is that for a different `input` event?

https://github.com/Modernizr/Modernizr/blob/master/feature-detects/event/oninput.js

File: editor/components/rich-text/tinymce.js [hunk 4]
```diff
@@ -96,6 +182,23 @@ export default class TinyMCE extends Component {
 		} );
 	}
 
+	saveEditorNode( editorNode ) {
+		this.editorNode = editorNode;
+
+		/**
+		 * A ref function can be used for cleanup because React calls it with
+		 * `null` when unmounting.
+		 */
```
Comment (noisysocks) [inline editor/components/rich-text/tinymce.js]: Oh, that's cool!

**Review by noisysocks — APPROVED** [review]
Tested in IE11, Edge and Chrome. It fixes the bug!

I left some minor comments but nothing blocking.

File: editor/components/rich-text/tinymce.js (hunk 3 above)
Comment (brandonpayton) [reply editor/components/rich-text/tinymce.js]: I thought about that too. The test returns true for even a non-contenteditable `<div>` in IE11 because of the first part that sets an `oninput` attribute and checks the type of the element's `oninput` property. The browser _does_ support the `input` event but doesn't dispatch it for `contenteditable` text input.

I tried to adapt the latter half of the test that dispatches a KeyboardEvent and listens for `input` but didn't have any luck getting it to work in IE11. It's possible I missed something but didn't think I should spend more time on it.

File: editor/components/rich-text/tinymce.js (hunk 4 above)
Comment (brandonpayton) [reply editor/components/rich-text/tinymce.js]: Yeah, I love being able to keep allocation and cleanup in one place while also handling real situations where a ref is removed and re-added during the life of a component.

File: editor/components/rich-text/tinymce.js (hunk 3 above)
Comment (brandonpayton) [reply editor/components/rich-text/tinymce.js]: Also, thank you for taking the time to look and make this suggestion, @noisysocks . I actually forgot that I'd looked at this until I worked through it again. :)

File: editor/components/rich-text/tinymce.js (hunk 4 above)
Comment (aduth) [reply editor/components/rich-text/tinymce.js]: Shouldn't we just use `componentDidMount` and `componentWillUnmount` ?

Related: The latest version of React includes a new `React.createRef` function which may become the recommended standard in place of the `ref` callback:

https://reactjs.org/docs/refs-and-the-dom.html#creating-refs

File: editor/components/rich-text/tinymce.js [hunk 5]
```diff
@@ -9,15 +9,101 @@ import classnames from 'classnames';
...
+ * @param {Element} editorNode The root editor node.
+ *
+ * @return {boolean} A boolean indicating whether the fix is needed.
+ */
+function needsInternetExplorerInputFix( editorNode ) {
+	return (
+		// Rely on userAgent in the absence of a reasonable feature test for contenteditable `input` events.
+		/Trident/.test( window.navigator.userAgent ) &&
+		// IE11 dispatches input events for `<input>` and `<textarea>`.
+		! /input/i.test( editorNode.tagName ) &&
```
Comment (iseulde) [inline editor/components/rich-text/tinymce.js]: Why do we check this? A rich text field can never be an input or textarea.
