### PR TITLE
NumberControl: Fix invalid HTML attributes for infinite bounds

### LINKED ISSUE #69022: NumberControl: Infinity isn't a valid value for min and max
### Description

Discovered while investigating https://github.com/WordPress/gutenberg/issues/68599 and similar issues.

By default, the `NumberControl` component and other components that extend it e.g. UnitControl > ValueInpu > NumberControl use `Infinity` and `-Infinity` for the min and max HTMl attributes values.

That is: the rendered HTML attribute values is:
`max="Infinity"`
`min="-Infinity"`

Those aren't valid values, it's invalid HTML.

I'm not sure what was the reasoning about using `Infinity` as default value. Shouldn't the `max` and `min` attributes be simply omitted to allow infinite values?

Reference:

https://html.spec.whatwg.org/multipage/input.html#the-min-and-max-attributes
https://html.spec.whatwg.org/multipage/input.html#number-state-(type=number)

> The min attribute, if specified, must have a value that is a valid floating-point number. The max attribute, if specified, must have a value that is a valid floating-point number.

Cc @WordPress/gutenberg-components 

### Step-by-step reproduction instructions

- Go to the Storybook at https://wordpress.github.io/gutenberg/?path=/story/components-experimental-numbercontrol--default
- Inspect the source and observe the values are `max="Infinity"` and `min="-Infinity"`.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by Infinite-Null**
Closes: #69022

## What?
Fixes invalid HTML attributes in the NumberControl component where `min="-Infinity"` and `max="Infinity"` are being rendered.

## Why?
The NumberControl component currently uses JavaScript's Infinity and -Infinity values as HTML attributes for min and max, which is invalid according to the HTML. It requires min and max attributes to have valid floating-point numbers as values.

## How?
Modified the NumberControl component to omit the min/max attributes entirely when their values are infinite by using undefined:

## Testing Instructions
1. Run storybook by following command:

```bash
npm run storybook:dev
```

2. Go to `Number Control` component
3. Inspect the source and observe the  max and min attribute of input field.

## Screencast:

https://github.com/user-attachments/assets/eaf1306b-b031-41d1-8a81-68fd0b154655

### CODE REVIEW

File: packages/components/src/number-control/index.tsx [hunk 1]
```diff
@@ -229,8 +229,8 @@ function UnforwardedNumberControl(
 			hideHTMLArrows={ spinControls !== 'native' }
 			isDragEnabled={ isDragEnabled }
 			label={ label }
-			max={ max }
-			min={ min }
+			min={ min === -Infinity ? undefined : min }
+			max={ max === Infinity ? undefined : max }
```
Comment (hbhalodia) [inline packages/components/src/number-control/index.tsx]: Why prop position changed? Can you please update to use max first and min later?

**Review by hbhalodia — CHANGES_REQUESTED** [review]
Left some suggestion.

File: packages/components/src/number-control/index.tsx (hunk 1 above)
Comment (Infinite-Null) [reply packages/components/src/number-control/index.tsx]: Thank you for the feedback, I've updated the PR to maintain consistent prop ordering.

**Comment by Infinite-Null** [comment]
Hi @hbhalodia,

I have implemented the changes and requested for review. Please review it at your convince.
Thank You!

**Review by hbhalodia — APPROVED** [review]
LGTM! as per the screencast attached.

**Comment by Mamaduka** [comment]
cc @WordPress/gutenberg-components

**Comment by mirka** [comment]
Thanks! Looks good to merge with a changelog entry 👍

**Comment by Infinite-Null** [comment]
Hi @Mamaduka and @mirka,
I have added the changelog entry please have a look at it at your convicence.
Thank You!

**Comment by Mamaduka** [comment]
Sorry for the late reply, @Infinite-Null!

It looks like there's a merge conflict with CHANGELOG.md. Do you mind resolving it?  Then we can merge the PR.

**Comment by Infinite-Null** [comment]
No worries, @Mamaduka! 
I’ve resolved the merge conflict, we can proceed with merging this PR 😊.
