### PR TITLE
Components: Fix the timepicker, only update the values on blur

### LINKED ISSUE #3661: Entering a time in the post publish settings is not working
## Issue Overview

Currently it is impossible to:
- clear the field
- enter a time that starts with 00
- easily change a time to anything other than: 01, 10, 11 or 12

And it is very hard to change the time, as by default a `1` is entered, but the only accepted characters after that are `0`, `1` and `2` to create 10-12.

## Steps to Reproduce (for bugs)
For the hours:
1. Enter '1' as the hour to publish a post
2. Try to change it to '8'

For the minutes:
1. Enter `21` as the minutes
1. Try to change it to `31` by just changing the 2 to a 3

Try to use the `backspace` to change the numbers or clear them.

Sometimes even changing the hours to anything other than a `7` does not work at all.

[ Browser: Chrome, Firefox ]

## Possible Solution
Fix it.

## Screenshots / Video

I tried to make a recording, but the keypresses are not shown, so backspaces are not pointed out.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #3661

This PR changes the behavior of the TimPicker to be able to edit it freely and do the validation and updates on blur only.

This also makes the Component API more consistent, the format of the input and output value is made consistent. (Moment is only internal while the API expects timezone-less dates)

**Testing instructions**

 - Check that you can type anything in the time field and it resets on blur
 - Check that you can clear the input and type an hour

### CODE REVIEW

File: components/date-time/time.js [hunk 1]
```diff
@@ -8,87 +8,158 @@ import moment from 'moment';
...
-		}
-		const newDate = selected.clone().hours( parseInt( hours, 10 ) % 12 );
-		onChange( newDate );
-	};
+	updateAmPm( value ) {
+		return () => {
+			const { onChange } = this.props;
+			const { am, date, hours } = this.state;
+			if ( am === value ) {
+				return;
```
Comment (chriskmnds) [inline components/date-time/time.js]: Does this ever fire, or is it just for sanity here?

Comment (youknowriad) [reply components/date-time/time.js]: It does fire when you hit the "toggled" button

Comment (chriskmnds) [reply components/date-time/time.js]: Ah cool, thanks for clarifying. It wasn't clear to me and it's not covered by the tests either, so I thought to ask :-)

File: components/date-time/date.js [hunk 2]
```diff
@@ -4,13 +4,21 @@
 import ReactDatePicker from 'react-datepicker';
 import moment from 'moment';
 
-export function DatePicker( { currentDate, onChange, ...args } ) {
+/**
+ * Module Constants
+ */
+const TIMEZONELESS_FORMAT = 'YYYY-MM-DDTHH:mm:ss';
```
Comment (mtias) [inline components/date-time/date.js]: Why not just `TIME_FORMAT`?

File: components/date-time/time.js [hunk 3]
```diff
@@ -8,87 +8,158 @@ import moment from 'moment';
...
+					onChange={ this.onChangeMinutes }
+					onBlur={ this.updateMinutes }
+				/>
+				{ is12Hour && <div>
+					<Button
+						className="button components-time-picker__am-button"
+						isToggled={ am === 'AM' }
+						onClick={ this.updateAmPm( 'AM' ) }
+					>
+						{ __( 'AM' ) }
```
Comment (mtias) [inline components/date-time/time.js]: Not sure if these need some translation context in general. cc @yoavf

File: components/date-time/date.js (hunk 2 above)
Comment (youknowriad) [reply components/date-time/date.js]: The input and the output format should be the same, that's the format we have in the post object. We could use only a time format  for time and date format for date but this means adding some "unnecessary" date manipulations in the parent component `date-time` (extract time and date on input, and recompute the whole date on change). I think it's just for convenience.

File: components/date-time/time.js (hunk 3 above)
Comment (aduth) [reply components/date-time/time.js]: >Not sure if these need some translation context in general.

I would have possibly expected context to be good here, but noting elsewhere in core it is not provided:

https://github.com/WordPress/wordpress-develop/blob/f3d3254/src/wp-includes/class-wp-locale.php#L197-L201

**Comment by youknowriad** [comment]
Going to merge this if no more concerns?
