### PR TITLE
Fixed that the block is selected instead of the title when using the select all shortcut.

### LINKED ISSUE #33589: When Control + A is pressed on the title, if there are two or more blocks, the block will be selected instead of the title.
## Description
When select all ( ctrl + A or cmd + A) on the title, if there are two or more blocks, the block will be selected instead of the title.

This problem occurs in WordPress 5.8 or Gutenberg 11.

I think it is related to the pull request at https://github.com/WordPress/gutenberg/pull/33167, but I don't know.

## Step-by-step reproduction instructions

1. Go to edit post.
2. Add title text.
3. Added some blocks.
4. Press Control + A on title.

## Expected behaviour
The block will not be selected, and all the characters of the title will be selected.

## Actual behaviour
The title will not be selected, the block will be selected.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/1908815/126456534-4b68b03d-a08e-46ff-9127-f25354329426.mov

## WordPress information
- WordPress version: 5.8
- Gutenberg version: 11.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop 
- Operating system: macOS 11.4 / Windows 10
- Browser: Chrome 91.0 / Edge 91 / firefox 89

### PR DESCRIPTION
**Pull request by torounit**
## Description
close https://github.com/WordPress/gutenberg/issues/33589

Fixed a problem where pressing ctrl+A when the cursor is in the title field would select the block instead of the title string.

## How has this been tested?
see: https://github.com/WordPress/gutenberg/issues/33589

1. Go to edit post.
2. Add title text.
3. Added some blocks.
4. Press Control + A on title.

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by ntsekouras — APPROVED** [review]
LGTM - thanks! 👍

**Comment by torounit** [comment]
@ntsekouras Thank you for reviewing!

File: packages/block-editor/src/components/writing-flow/use-select-all.js [hunk 1]
```diff
@@ -31,6 +31,12 @@ export default function useSelectAll() {
 				return;
 			}
 
+			if (
+				event.target.classList.contains( 'editor-post-title__input' )
```
Comment (talldan) [inline packages/block-editor/src/components/writing-flow/use-select-all.js:35]: I don't think code in the block editor package should use a classname from the editor package. The dependency is the other way, that editor package depends on block editor. 

But it also doesn't cause any issues, this will just be ignored in other editors.

It could be good to see if there are other options for solving this that don't rely on an editor class name, though.

Comment (torounit) [reply packages/block-editor/src/components/writing-flow/use-select-all.js:35]: Thank you @talldan 
I think that point is well taken.

Conditions such as `isEmpty( getSelectionStart() ) && isEmpty( getSelectionEnd() ) ` will cause this test to fail.
https://github.com/WordPress/gutenberg/blob/v11.1.0/packages/e2e-tests/specs/editor/various/multi-block-selection.test.js#L656

Any good ideas to get the state that the cursor is on the title?

Comment (talldan) [reply packages/block-editor/src/components/writing-flow/use-select-all.js:35]: It looks like @ellatrix iterated on this in #33699, sorry I couldn't provide any better suggestions.
