### PR TITLE
Template Part: Prevent infinite recursion

### LINKED ISSUE #27612: Template part block fails attempting to preview recursive template parts
**Describe the bug**
For issue #26923 I created a couple of template parts which would cause an infinitely recursive loop.
In Gutenberg 9.5.1 these cause the Template part block to fail with `This block has encountered an error and cannot be previewed`. 

**To reproduce**
1. Using a Full Site Editing theme such as Twenty Twenty-One blocks create recursive template parts as below.
2. Add a new post.
3. Add a Template part block.
4. Click on Choose existing.
5. Wait for a while.
6. The block will fail.

issue-27.html
```
<ul>
    <li>Issue-27 test case.
    <!-- wp:template-part { "slug": "issue-30", "theme": "fizzie" } /-->
    </li>
</ul>
```

issue-30.html
```
<ul>
    <li>Issue-30 test case.
    <!-- wp:template-part { "slug": "issue-27", "theme": "fizzie" } /-->
    </li>
</ul>
```

**Expected behavior**
- The fixes developed to prevent recursion in the server need equivalent logic in the block editor.
- The preview should indicate that recursion has occurred, indicating where it was detected.
- It could suggest a method for fixing the problem.

**Screenshots**
recursive-template-part-block

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] 9.5.1
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 87.0.4280.88 (Official Build) (64-bit)

**Additional context**
See also 
- #26923 
- https://github.com/bobbingwide/fizzie/issues/49

### PR DESCRIPTION
**Pull request by gziolo**
## Description

Fixes #27612.

Based on #28405 from @mcsf.

Tries to apply the same technique used for Reusable block to prevent infinite recursion when the same block is inserted into itself at any level of nesting.

## Technical details

`useNoRecursiveRenders` required some improvements as there was the probability that the same unique id would be used for different block types. In theory, we could mitigate that by using the block name in the id but it would be up to the block author to ensure it. Instead, it uses the solution proposed by @mcsf to use the block edit context inside `useNoRecursiveRenders` to resolve ambiguity on the framework level.

## How has this been tested?

1. Activate the FSE theme.
2. Open the Site Editor.
3. Insert the same Template Part block twice next to each other and ensure they render correctly.
4. Insert the same Template Part inside itself and observe it prevents infinite recursion.
5. Save the post and open the page that uses the modified template. Ensure the infinite recursion is prevented on the front-end and a warning is printed when `WP_DEBUG` and `WP_DEBUG_DISPLAY` config flags are enabled.
6. There are different combinations that might need to be tested like:
  a. Template Part A inside Template Part B that contains Template Part A.
  b. Template Part A inside Template Part B  that contains Template Part B. 

## Screenshots 

Screen Shot 2021-03-03 at 11 54 22
Screen Shot 2021-03-03 at 11 54 09

Screen Shot 2021-03-03 at 14 06 50

Screen Shot 2021-03-03 at 14 09 04

## Types of changes
Bug fix (non-breaking change which fixes an issue).

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by bobbingwide** [comment]
See #27012 where, for the server side rendering I implemented logic to detect recursion in nested blocks by adding and removing the block to a stack.

- Check if the block that's about to be rendered is already being rendered.
- If it isn't already being rendered. ie It's safe to render 
  - add it to the stack of blocks being rendered.
  - render the block
  - pop it from the stack
- else don't render it

See #27612 for my original issue and test case data

**Comment by mcsf** [comment]
> The template part has a `slug`, which is unique

See reference below. Template parts are also a function of the theme, so that needs to be part of the identifier.

https://github.com/WordPress/gutenberg/blob/437a546a427ef39b9a3af61b33576bba84160940/packages/block-library/src/template-part/edit/index.js#L34

**Comment by mcsf** [comment]
Thanks for getting this PR started. It would be good to solve https://github.com/WordPress/gutenberg/pull/28405#issuecomment-766687251, as you've pointed out, before generalising this server-side solution.

**Comment by gziolo** [comment]
@bobbingwide, thank you for the helpful comment. It aligns with what @carlomanf commented in https://github.com/WordPress/gutenberg/pull/28405#issuecomment-766741751 in relation to Reusable block:

> #26951 solved this by [unsetting the block from the static variable after the end of the render.](https://github.com/WordPress/gutenberg/pull/26951/files#diff-8372ba798df02239c3dd7da6a3d082bd1b57bebd7f6daf746412b00c709922cfR256) It should be an easy fix I think.

We might as well merge the editor part for now and tackle the server-side separately based on the implementation you shared.

File: packages/block-library/src/template-part/edit/index.js [hunk 1]
```diff
@@ -63,9 +68,18 @@ export default function TemplatePartEdit( {
 	);
 
 	const blockProps = useBlockProps();
-	const isPlaceholder = ! slug;
-	const isEntityAvailable = ! isPlaceholder && ! isMissing;
 
+	if ( hasAlreadyRendered ) {
```
Comment (gziolo) [inline packages/block-library/src/template-part/edit/index.js:72]: Since `templatePartId` might be `null`. In theory, we should move this check after `isMissing` verification. Although in practice it should never be an issue because it bails out early. Anyway, for the sake of correctness, I will update the flow.

File: packages/block-library/src/template-part/edit/index.js [hunk 2]
```diff
@@ -78,6 +82,17 @@ export default function TemplatePartEdit( {
 		);
 	}
 
+	if ( hasAlreadyRendered ) {
```
Comment (mcsf) [inline packages/block-library/src/template-part/edit/index.js:85]: What happens when `! theme || ! slug`?

File: packages/block-library/src/template-part/index.php [hunk 3]
```diff
@@ -55,6 +57,31 @@ function render_block_core_template_part( $attributes ) {
...
+			defined( 'WP_DEBUG_DISPLAY' ) && WP_DEBUG_DISPLAY;
+
+		return $is_debug ?
+			// translators: Visible only in the front end, this warning takes the place of a faulty block.
+			__( '[block rendering halted]' ) :
+			'';
+	}
+
+	$seen_content[] = $content;
+
```
Comment (mcsf) [inline packages/block-library/src/template-part/index.php:84]: Feel free to mirror `master`'s 86aa2f53361d8c13e95a195d702d25b89d1b8a6e.

File: packages/block-library/src/template-part/edit/index.js (hunk 2 above)
Comment (mcsf) [reply packages/block-library/src/template-part/edit/index.js:85]: I haven't tested this, but my concern is that `templatePartId` depends on those two variables, and passing a null value to `useNoRecursiveRenders` is something to approach with care, because `hasAlreadyRendered` might come out true even though that template part is not recursive.

**Review by mcsf — CHANGES_REQUESTED** [review]

File: packages/block-library/src/template-part/edit/index.js (hunk 2 above)
Comment (gziolo) [reply packages/block-library/src/template-part/edit/index.js:85]: Yes, it's on my mind. See https://github.com/WordPress/gutenberg/pull/28456#discussion_r563731762 that is collapsed now. It's not clear to me why one of them would be `null` which makes it difficult to process in the first place.

**Comment by mcsf** [comment]
@gziolo, can I help with this PR in any way?

**Comment by gziolo** [comment]
Feel free to take it over. I won't have time to work on it this week.

**Comment by mcsf** [comment]
> Feel free to take it over. I won't have time to work on it this week.

Will do!

File: packages/block-library/src/template-part/edit/index.js (hunk 2 above)
Comment (gziolo) [reply packages/block-library/src/template-part/edit/index.js]: I opted for:
```
if ( isEntityAvailable && hasAlreadyRendered ) {
```

`isEntityAvailable` is true only when inner blocks are ready to render. It covers also the case when `templatePartId` is `null`  which means there is no way to find an entity.

File: packages/block-library/src/template-part/index.php [hunk 4]
```diff
@@ -56,12 +65,36 @@ function render_block_core_template_part( $attributes ) {
...
+		return __( 'Template Part not found.' );
+	}
+
+	if ( isset( $seen_ids[ $template_part_id ] ) ) {
+		if ( ! is_admin() ) {
+			trigger_error(
+				sprintf(
+					// translators: %s are the block attributes.
+					__( 'Could not render Template Part block with the attributes <code>%s</code>: blocks cannot be rendered inside themselves.' ),
+					wp_json_encode( $attributes )
```
Comment (gziolo) [inline packages/block-library/src/template-part/index.php:78]: It's hard to tell how what to show here. `$template_part_id` might be better but it can be different things.

Comment (mcsf) [reply packages/block-library/src/template-part/index.php:78]: I'm not super worried about this. Whether we show attributes or an ID, the most important part of the UX will be for users to visually see which template part failed from the context, and when they go into the editor they will see the error state in the `Edit` element. I think either datum is fine.

**Review by mcsf — COMMENTED** [review]
Looking good! Let me know when you want a final review.

File: packages/block-library/src/template-part/index.php (hunk 4 above)
Comment (gziolo) [reply packages/block-library/src/template-part/index.php:78]: I think it reads good:
Screen Shot 2021-03-03 at 11 54 09

**Comment by gziolo** [comment]
This is how it looks with template parts nested in themselves when browsing in the template parts view on the Edit Site page:

https://user-images.githubusercontent.com/699132/109811007-97ab7900-7c2a-11eb-9a12-a4f006057fe5.mov

It behaves a bit strange for the template part that is nested inside another template part, but it all makes sense. I would say it's an anti-pattern in the first place to nest the same template part inside itself so it doesn't explode but the result is random that should raise the flag for the theme author 😄

**Comment by gziolo** [comment]
@aristath and  @ntsekouras – this PR is ready for review and testing. It means we have Reusable Block and Template Parts covered. What else is missing?

**Comment by ntsekouras** [comment]
> It means we have Reusable Block and Template Parts covered. What else is missing?

Post Content is missing.

File: packages/block-library/src/template-part/index.php [hunk 5]
```diff
@@ -56,12 +65,36 @@ function render_block_core_template_part( $attributes ) {
...
+			// translators: Visible only in the front end, this warning takes the place of a faulty block.
+			__( '[block rendering halted]' ) :
+			'';
 	}
 
 	// Run through the actions that are typically taken on the_content.
-	$content = do_blocks( $content );
+	$seen_ids[ $template_part_id ] = true;
+	$content                       = do_blocks( $content );
+	unset( $seen_ids[ $template_part_id ] );
```
Comment (ntsekouras) [inline packages/block-library/src/template-part/index.php:97]: I'm a bit confused with this. Why do you unset after setting?

File: packages/block-editor/src/components/use-no-recursive-renders/test/use-no-recursive-renders.js [hunk 6]
```diff
@@ -4,29 +4,40 @@
...
+import useNoRecursiveRenders from '../';
+import {
+	BlockEditContextProvider,
+	useBlockEditContext,
+} from '../../block-edit/context';
 
 // Mimics a block's Edit component, such as ReusableBlockEdit, which is capable
 // of calling itself depending on its `ref` attribute.
 function Edit( { attributes: { ref } } ) {
+	const { name } = useBlockEditContext();
```
Comment (ntsekouras) [inline packages/block-editor/src/components/use-no-recursive-renders/test/use-no-recursive-renders.js:18]: I understand the enhancement you made for taking into account block name and id, but these tests now are a bit confusing with the `ref` usage IMO. First thing I thought when seeing `ref` was React's ref, when the case is that we care about a unique id. A bit of renaming here might help probably, but I don't see this as blocking.

**Review by ntsekouras — COMMENTED** [review]
Thanks for working on this @gziolo! I left a couple of comments but in my testing everything works as expected.

Great work on the addition to check ids with block 💯

File: packages/block-editor/src/components/use-no-recursive-renders/test/use-no-recursive-renders.js (hunk 6 above)
Comment (gziolo) [reply packages/block-editor/src/components/use-no-recursive-renders/test/use-no-recursive-renders.js:18]: Sure, we can use `uniqueId` to make it easier to follow. I think `ref` is coming from the Reusable blocks 😄

File: packages/block-library/src/template-part/index.php [hunk 7]
```diff
@@ -56,12 +65,36 @@ function render_block_core_template_part( $attributes ) {
 		}
 	}
 
-	if ( is_null( $content ) ) {
-		return 'Template Part Not Found';
+	if ( ! $template_part_id || is_null( $content ) ) {
+		return __( 'Template Part not found.' );
```
[the remark this answers is not in the document]
Comment (gziolo) [reply packages/block-library/src/template-part/index.php:69]: A separate PR is better. Good catch, but it isn't related to this code 😄

File: packages/block-library/src/template-part/index.php (hunk 5 above)
Comment (gziolo) [reply packages/block-library/src/template-part/index.php:97]: You need to unset template part ids once the child blocks were processed, so other blocks in the same level (siblings) would render. It's the case like this pseudocode:

```jsx
<>
    <TemplatePart id="A" />
    <TemplatePart id="A" />
</>
```

If you wouldn't unset, then it would consider the second occurrence as already seen and it would prevent its rendering.

Comment (mcsf) [reply packages/block-library/src/template-part/index.php:97]: We unset after calling `do_blocks`. :) So the flow becomes:

1. Set _seen_ to prevent future loops
2. "Do" the content, i.e. traverse and render any inner blocks
3. Unset _seen_, so that we don't prevent legitimate use cases, like the same block being rendered in distinct stacks. Imagine the following:

* Document
  * Header
    * **Site Title + Logo** template part
  * Main
    * Post content
  * Footer
    * **Site Title + Logo** template part

Comment (ntsekouras) [reply packages/block-library/src/template-part/index.php:97]: Thanks both!

Comment (mcsf) [reply packages/block-library/src/template-part/index.php:97]: (GitHub didn't properly reload, so I didn't realise Grzegorz had already replied 🤦)

File: packages/block-editor/src/components/use-no-recursive-renders/test/use-no-recursive-renders.js (hunk 6 above)
Comment (gziolo) [reply packages/block-editor/src/components/use-no-recursive-renders/test/use-no-recursive-renders.js:18]: Done it https://github.com/WordPress/gutenberg/pull/28456/commits/c0d579652e07395075328381269498001e031341.

**Comment by gziolo** [comment]
@mcsf and @ntsekouras - anything left to rework here?

**Review by mcsf — APPROVED** [review]
Looks great. Thanks for circling back to this, and also for catching little things along the way.

**Comment by gziolo** [comment]
Interesting, 5 unit tests fail on CI. I will investigate that and fix it before merging this PR..

**Comment by gziolo** [comment]
> Interesting, 5 unit tests fail on CI. I will investigate that and fix it before merging this PR.

It looks like there were some changes introduced in https://github.com/WordPress/gutenberg/pull/29333. The hook uses now `useSelect` call to retrieve the name of the block from the `clientId`. I need to understand better why this change was introduced.

File: packages/block-library/src/template-part/index.php (hunk 7 above)
[the remark this answers is not in the document]
Comment (ntsekouras) [reply packages/block-library/src/template-part/index.php:69]: i18n fix for the above: https://github.com/WordPress/gutenberg/pull/29612
