### PR TITLE
Dataviews: Fix sticky table headers

### LINKED ISSUE #58977: Data views: Table headers are no longer sticky
Most likely due to the addition of wrappers like `.dataviews-wrapper` and `.dataviews-view-table-wrapper`, table column headers are no longer sticking to the top of the container as you scroll. 

Given the additional nesting we may need to use javascript to handle this.

### PR DESCRIPTION
**Pull request by jameskoster**
Fixes https://github.com/WordPress/gutenberg/issues/58977.

https://github.com/WordPress/gutenberg/assets/846565/a5e266f0-a5b4-432a-ba55-e2b0efbee51a

## Testing Instructions
1. Open a data view like 'Manage all pages'
2. As you scroll notice the ~filter bar~, table headers, and pagination stick
3. Check other layouts (Grid / List) work as before 

~With this approach the filter controls are also sticky where previously it was only the table headers. I haven't found an approach that avoids this yet, but perhaps it's useful? We can discuss that and investigate alternative approaches in this PR.~

### CODE REVIEW

File: packages/dataviews/src/dataviews.js [hunk 1]
```diff
@@ -92,7 +92,7 @@ export default function DataViews( {
 	);
 	return (
 		<div className="dataviews-wrapper">
-			<VStack spacing={ 3 } justify="flex-start">
+			<VStack spacing={ 0 } justify="flex-start">
```
Comment (t-hamano) [inline packages/dataviews/src/dataviews.js]: I'm thinking maybe we can remove this nested div. That is, it would look like this:

```javascript
return (
	<VStack
		className="dataviews-wrapper"
		spacing={ 0 }
		justify="flex-start"
	>
		<HStack />
		<ViewComponent />
		<Pagination />
	</VStack>
);
```

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

The following is how it looks on Windows OS / Chrome, and it appears to be working as expected.

https://github.com/WordPress/gutenberg/assets/54422211/1b9be54a-ee4d-458b-bff0-8685a4cba45e

However, we may need to increase the z-index of the table header so that the checkbox is not in front:

image

> With this approach the filter controls are also sticky where previously it was only the table headers. I haven't found an approach that avoids this yet, but perhaps it's useful?

Personally, I would expect the filter control to be fixed, but I think it might be a good idea to make the filter control fixed on all layouts.

**Comment by ntsekouras** [comment]
>With this approach the filter controls are also sticky where previously it was only the table headers.

Personally I think that we might want to explore this more before merging, because right now the filters are few, but could be lots of them in the future. I know it's not quite easy though, from all the things I tried and searched..

**Comment by jameskoster** [comment]
I agree with you both, fixing the filter controls can be useful, but in cases where there are many active filters there's potential for clunkiness. As an extreme (but realistic) example, here are the filters a user might enact on orders in WooCommerce, on an iPad mini viewport size:

Screenshot 2024-03-01 at 17 01 52

You could argue this is an edge case not worth optimising for. And that some dimensions could be massaged at this breakpoint (the sidebar takes over a third of the horizontal space 😱). A couple of tweaks can go a long way:

Screenshot 2024-03-01 at 17 09 14

But clearly the filters are still accounting for a lot of space. Let's see what other designers have to say.

**Comment by jameskoster** [comment]
@ntsekouras Seems unlikely we can merge this with 100% confidence for 6.5, and it may be too late now. Do you think we should spin up a separate PR to remove the 'broken' sticky styles for 6.5?

**Comment by ntsekouras** [comment]
>@ntsekouras Seems unlikely we can merge this with 100% confidence for 6.5, and it may be too late now. Do you think we should spin up a separate PR to remove the 'broken' sticky styles for 6.5?

We could yes, but this would mean reverting [this PR](https://github.com/WordPress/gutenberg/pull/57930) and bring back the issue it solved. If that's okay with you, let's do it.

**Comment by jameskoster** [comment]
I think I've cracked it. @t-hamano was on the right path, consolidating some of the wrappers seems to be the key.

* Filters do not stick when scrolling vertically
* Column headers and pagination stick to top / bottom when scrolling vertically
* Filters and Pagination stick to left when scrolling horizontally

https://github.com/WordPress/gutenberg/assets/846565/49a86d9a-7f04-4604-b98f-5cc5b874a462

**Review by ntsekouras — APPROVED** [review]
This looks great now, thanks!

**Comment by getdave** [comment]
I just cherry-picked this PR to the pick/wp-65-rc-2 branch to get it included in the next release https://github.com/WordPress/gutenberg/pull/59756
