### PR TITLE
Fix invalid Spacer markup when set to fill

### LINKED ISSUE #51235: Spacer block breaks when height is set to "fill"
### Description

See title.
Interestingly, it also seems to impact  the image block, that looks stretched in the editor. The front-end is fine.

Console log
```
JQMIGRATE: Migrate is installed, version 3.4.0
logger.js:17 Block validation: Expected attributes Array(3), instead saw Array(2).
(anonymous) @ logger.js:17
logger.js:17 Block validation: Block validation failed for `core/spacer` (Object).

Content generated by `save` function:

<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>

Content retrieved from post body:

<div aria-hidden="true" class="wp-block-spacer"></div>
(anonymous) @ logger.js:17
logger.js:17 Block validation: Expected attributes Array(3), instead saw Array(2).
(anonymous) @ logger.js:17
logger.js:17 Block validation: Block validation failed for `core/spacer` (Object).

Content generated by `save` function:

<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>

Content retrieved from post body:

<div aria-hidden="true" class="wp-block-spacer"></div>
(anonymous) @ logger.js:17
logger.js:17 Block validation: Expected attributes Array(3), instead saw Array(2).
(anonymous) @ logger.js:17
logger.js:17 Block validation: Block validation failed for `core/spacer` (Object).

Content generated by `save` function:

<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>

Content retrieved from post body:

<div aria-hidden="true" class="wp-block-spacer"></div>
(anonymous) @ logger.js:17
logger.js:17 Block validation: Expected attributes Array(3), instead saw Array(2).
(anonymous) @ logger.js:17
logger.js:17 Block validation: Block validation failed for `core/spacer` (Object).

Content generated by `save` function:

<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>

Content retrieved from post body:

<div aria-hidden="true" class="wp-block-spacer"></div>
(anonymous) @ logger.js:17
logger.js:17 Block validation: Expected attributes Array(3), instead saw Array(2).
(anonymous) @ logger.js:17
logger.js:17 Block validation: Block validation failed for `core/spacer` (Object).

Content generated by `save` function:

<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>

Content retrieved from post body:

<div aria-hidden="true" class="wp-block-spacer"></div>
(anonymous) @ logger.js:17
```

### Step-by-step reproduction instructions

1. Set spacer height to "fill"

### Screenshots, screen recording, code snippet

image

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

Fixes #51235.

When spacer block is in vertical mode, inside a flex container (e.g a Stack block) and set to "fill" or "fit", the block markup is flagged as invalid due to a missing height attribute. This fixes the issue by making sure the default height value doesn't automatically get added in the save function if the block is in a flex container and set to "fit" or "fill".

## Testing Instructions

1. Paste the markup from [this comment](https://github.com/WordPress/gutenberg/issues/51235#issuecomment-1579284684) in the block editor;
2. There should be no invalid block warnings.
3. Try adding a Spacer to the page outside of any flex block: it should still get the default 100px height.

### CODE REVIEW

File: packages/block-library/src/spacer/save.js [hunk 1]
```diff
@@ -3,12 +3,17 @@
  */
 import { useBlockProps, getSpacingPresetCssVar } from '@wordpress/block-editor';
 
-export default function save( { attributes: { height, width } } ) {
+export default function save( { attributes } ) {
+	const { height, width, style } = attributes;
+	const { layout: { selfStretch } = {} } = style || {};
+	// If self-stretch is set to fill, avoid setting default height.
```
Comment (ramonjd) [inline packages/block-library/src/spacer/save.js]:
```suggestion
	// If selfStretch is set to 'fill' or 'fit', don't set default height.
```

**Review by ramonjd — APPROVED** [review]
On trunk I'm seeing the validation errors:

Screenshot 2023-06-13 at 11 01 07 am

With this PR, those validations are gone! Editor changes look good on the frontend as well. 

Thank you!

**Comment by tellthemachines** [comment]
Thanks for reviewing @ramonjd !

**Comment by t-hamano** [comment]
I arrived at this PR from #51453. I think to solve the problem reported in #51453, the height needs to be undefined even for Fixed width. Also, since this PR is updating save.js, we may need to add a deprecation as well.
