### PR TITLE
Copy All Content button: Hide if is no content

### LINKED ISSUE #15500: Don't display "Copy All Content" in new, empty, posts
When creating a new post and the post doesn't have a title or some content yet, the "Copy All Content" button doesn't do anything:

copy all content new empty post

To reproduce:
- create a new post
- make sure to not enter any title or content
- open the toolbar "More" menu
- click on "Copy All Content"
- nothing happens

Instead, when there's some content, clicking the "Copy All Content" ... copies the content, and the button text changes to "Copied!".

Note: filling in only the title post doesn't seem to enable the copy functionality.

As this button doesn't do anything without content, it shouldn't be displayed until there's actually something to copy.

Accessibility notes:
- the button text shouldn't change dynamically: button text gives the button its accessible name which should inform users about _what_ the button does. It shouldn't be used for feedback or to indicate the _state_ of an action/setting. The "Copied!" text should appear separately.
- to evaluate: use an audible `speak()` message to confirm the copy operation result

### PR DESCRIPTION
**Pull request by Soean**
## Description
The "Copy All Content" button should not be visible if there is no content.

Fixes #15500

hide-copy-button

### CODE REVIEW

File: packages/edit-post/src/plugins/copy-content-menu-item/index.js [hunk 1]
```diff
@@ -8,27 +8,29 @@ import { withState, compose } from '@wordpress/compose';
...
-					}
-				);
-			} }
-			onFinishCopy={ () => setState( { hasCopied: false } ) }
-		>
-			{ hasCopied ?
-				__( 'Copied!' ) :
-				__( 'Copy All Content' ) }
-		</ClipboardButton>
+		editedPostContent.length > 0 && (
```
Comment (jorgefilipecosta) [inline packages/edit-post/src/plugins/copy-content-menu-item/index.js]: I had some worries that editedPostContent may be null or undefined, but I checked the docs of the selector that ultimately is used, and it refers a string is always returned  `* @return {string} Post content.`

**Review by jorgefilipecosta — APPROVED** [review]
Works well on my tests 👍

**Comment by aduth** [comment]
While it's arguably not useful if the post has no content, to avoid introducing inconsistency to the set of menu items available, I wonder if we would just leave it as it was, set the behavior to copy an empty string, and still show notices as if it were successful. Would that not still satisfy #15500, where the concern this change addresses is that there is no response to the button click?

File: packages/edit-post/src/plugins/copy-content-menu-item/index.js (hunk 1 above)
Comment (aduth) [inline packages/edit-post/src/plugins/copy-content-menu-item/index.js]: `getEditedPostAttribute` is a non-trivial selector, but it was previously more necessary because we did not conditionally render the element based on whether there is content or not.

With the addition of this condition, I wonder if we might consider to optimize the rendering to check whether there is content using the more-optimized [`isEditedPostEmpty`](https://github.com/WordPress/gutenberg/blob/b95e865de32ee62d722be3e3e71b334a4b639032/packages/editor/src/store/selectors.js#L474-L512) (see inline comments for optimization specifics).

It could be applied using a series of higher-order components:

```js
export default compose(
	withSelect( ( select ) => ( {
		hasEditedPostContent: ! select( 'core/editor' ).isEditedPostEmpty(),
	} ) ),
	ifCondition( ( { hasEditedPostContent } ) => hasEditedPostContent ),
	withSelect( ( select ) => ( {
		editedPostContent: select( 'core/editor' ).getEditedPostAttribute( 'content' ),
	} ) ),
	withDispatch( ( dispatch ) => {
		const {
			createNotice,
		} = dispatch( 'core/notices' );

		return {
			createNotice,
		};
	} ),
	withState( { hasCopied: false } )
)( CopyContentMenuItem );
```
