### PR TITLE
iAPI: Fix and refactor runtime initialization logic

### LINKED ISSUE #70870: iAPI: Review the initialization logic
## What problem does this address?

Currently, the Interactivity API initialization relies on the correct order of modules to function as intended. All modules that register a store should be evaluated before the hydration process begins. Similarly, the Interactivity API Router depends on the initial page to be hydrated beforehand; it fails if the module is enqueued directly.

## What is your proposed solution?

We need to ensure everything works okay without having to rely on the order or the order these modules are enqueued or imported.

### LINKED ISSUE #74184: Image block “Enlarge on click” throws JS error and locks page scrolling on first load
When using the Image block with “Enlarge on click” enabled, the page becomes unscrollable after closing the lightbox, but only on the first page load. After a browser reload, the issue no longer occurs.

I investigated this myself and found a JavaScript console error coming from WordPress core, which prevents the scroll-unlock logic from running.

**Steps to Reproduce**

1. Open a page with large images using the Image block
2. Ensure “Enlarge on click” is enabled
3. Scroll down the page
4. Click an image to open it in the lightbox
5. Close the image
6. Try to scroll the page

**Issue Source:** https://wordpress.org/support/topic/enlarge-on-click-page-scroll-issue/

**Screenshot:**
Image

### LINKED ISSUE #74685: Image block: The page is prevented from scrolling after the lightbox is closed if the image wasn't ready before the lightbox was clicked open
### Description

After opening and closing the Lightbox of the Image block, the page is stuck when the image for the Lightbox is not loaded in time. If the image is already loaded and opens immediately, this is not happening.

### Step-by-step reproduction instructions

0. Open Developer Tools in a browser
1. Go to: https://asia.wordcamp.org/2026/contributor-day/
2. Click on an image in the post.
3. Nothing is happening for a long time - image is loading.
4. The image is opened.
5. Click to close the image.
6. Try to scroll the page—it resists and returns to the place when the lightbox was.
8. Try to open and close the lightbox several times.
7. Go to the Network tab and notice that the image was requested multiple times.

### Screenshots, screen recording, code snippet

Image
Image

### Environment info

WordPress 6.9.1-alpha-61393
Gutenberg 22.3.0
Twenty Twenty-Four 1.3 theme

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by DAreRodz**
## What?

Closes #70870 and #74184.

Revisits the initialization logic to clarify all steps and when they run. Also, fixes a race condition during the iAPI initialization, causing a bug in the Image block.

For now, this PR serves more as an exploration to discuss possible implementations.

## Why?

See #70870 for the initial motivation.
See #74184 for the Image block bug.

## How?

Basically, the code changes are as follows:
1. All initialization has been moved to `index.ts`. There is no longer any initialization of isolated parts in internal modules, as was the case with the initial state and config.
2. The `init.ts` file has been renamed `hydration.ts`, as it only involves the hydration part. The `init()` function is now called `hydrateRegions()`.
3. To delay hydration right after all sync modules have been executed, a util named `isDOMReady` has been implemented. This function relies on [domContentLoadedEventStart](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming/domContentLoadedEventStart) to detect whether the `DOMContentLoaded` event has been dispatched. If not, it registers an event listener for that event, ensuring that all sync modules statically importing `@wordpress/interactivity` have been evaluated before hydration, preventing errors from missing state, actions, or callbacks. If dispatched, hydration is guaranteed; however, missing properties at hydration time may cause directives such as `data-wp-init` to fail.

## Testing Instructions

1. Follow the steps described in #74184, with network throttling enabled (3G should work).
2. Ensure no error appears now in the console after closing the image lightbox.
3. Ensure scrolling works after closing the image lightbox.

### CODE REVIEW

File: packages/interactivity/src/index.ts [hunk 1]
```diff
@@ -63,5 +68,10 @@ export const privateApis = ( lock ): any => {
...
 };
 
+// Parse and populate the initial state and config.
+// All the core directives are registered at this point as well.
+populateServerData( parseServerData() );
 registerDirectives();
-init();
+
+// Defer hydration to the end of the task queue.
+postTask( hydrateRegions );
```
Comment (DAreRodz) [inline packages/interactivity/src/index.ts]: This is mostly the same as before, with the `setTimeout` function replaced by a new `postTask` function, which adds the `hydrateRegions` function to the end of the event loop.

Effectively, the result would be the same, as `setTimeout` wouldn't be affected by any of the [limitations](https://developer.mozilla.org/en-US/docs/Web/API/Window/setTimeout#reasons_for_delays_longer_than_specified) that could potentially delay the callback execution.

File: packages/interactivity/src/utils.ts [hunk 2]
```diff
@@ -55,6 +69,14 @@ const afterNextFrame = ( callback: () => void ) => {
 	} );
 };
 
+// TODO: consider initializing this only if required.
+const taskQueue: ( () => any )[] = [];
+const taskChannel = new MessageChannel();
+// Drain one task per message
+taskChannel.port1.onmessage = () => {
+	taskQueue.shift()?.();
+};
```
Comment (DAreRodz) [inline packages/interactivity/src/utils.ts]: I'm reusing these for a `scheduler` fallback. Not entirely confident this is the most suitable approach, though. 🤔

Using `MessageChannel` could be considered more reliable than `setTimeout()` to schedule tasks (the [`scheduler` polyfill](https://github.com/GoogleChromeLabs/scheduler-polyfill) from GoogleChromeLabs uses it when available), I feel that none of the [delay issues](https://developer.mozilla.org/en-US/docs/Web/API/Window/setTimeout#reasons_for_delays_longer_than_specified) `setTimeout()` has would apply here, at least for the initialization case.

**Comment by DAreRodz** [comment]
I've been testing different implementations [here](https://stackblitz.com/edit/iapi-rfmckrcw) for `postTask`. They all do the job, although the results are inconsistent between browsers.

As an example, these are the logs obtained for the `MessageChannel` implementation in Chrome, Firefox, and Safari.

```
| Chrome                     | Firefox                    | Safari                     |
| -------------------------- | -------------------------- | -------------------------- |
| scheduler                  | scheduler                  | scheduler                  |
| test1                      | test1                      | DOMContentLoaded scheduler |
| test2                      | test2                      | test1                      |
| test3                      | test3                      | test2                      |
| DOMContentLoaded scheduler | postTask scheduler         | test3                      |
| postTask scheduler         | DOMContentLoaded scheduler | postTask scheduler         |
| postTask test1             | postTask test1             | postTask test1             |
| postTask test2             | postTask test2             | postTask test2             |
| postTask test3             | postTask test3             | postTask test3             |
| after await test1          | after await test1          | after await test1          |
| after await test2          | after await test2          | after await test2          |
| after await test3          | after await test3          | after await test3          |
```

And these are for the implementation using `setTimeout`:

```
| Chrome                     | Firefox                    | Safari                     |
| -------------------------- | -------------------------- | -------------------------- |
| scheduler                  | scheduler                  | scheduler                  |
| test1                      | test1                      | test1                      |
| test2                      | test2                      | DOMContentLoaded scheduler |
| test3                      | test3                      | test2                      |
| DOMContentLoaded scheduler | DOMContentLoaded scheduler | test3                      |
| postTask scheduler         | postTask scheduler         | postTask scheduler         |
| postTask test1             | postTask test1             | postTask test1             |
| postTask test2             | postTask test2             | postTask test2             |
| postTask test3             | postTask test3             | postTask test3             |
| after await test1          | after await test1          | after await test1          |
| after await test2          | after await test2          | after await test2          |
| after await test3          | after await test3          | after await test3          |
```

One interesting conclusion from these results is that, in Safari, the `DOMContentLoaded` event seems to be dispatched even before all the modules have been executed, so it is, in fact, not reliable to initialize the interactivity API.

**Comment by DAreRodz** [comment]
Another interesting finding is that we should avoid using top-level awaits in our code.

When a module statically imports another module using a top-level `await`, the module is effectively awaited as if it were imported dynamically, delaying the module execution. This is how modules work natively.

Let's consider the init code that delays the hydration. Imagine we await `postTask`:

```js
// Defer hydration to the end of the task queue.
await postTask( hydrateRegions );
```

All `view.js` files **statically importing** `@wordpress/interactivity` would stop until the hydration is complete, and all `store()` calls would run after hydration.

**Comment by luisherranz** [comment]
After further investigation, we have concluded that the only method to ensure that all script modules included in the HTML have been executed is to use `DOMContentLoaded`, and the only reliable way to know if it has already been executed is to use `domContentLoadedEventStart`. So, the implementation proposal is:

```js
const [navigation] = performance.getEntriesByType('navigation');

if (navigation.domContentLoadedEventStart > 0) {
  // DOMContentLoaded has started or already completed
  init();
} else {
  document.addEventListener('DOMContentLoaded', init);
}
```

[Browser support](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming/domContentLoadedEventStart) aligns with import maps, so we're good there.

Regarding top-level await: Our testing showed that Safari < 26 treats modules with top-level await as async. They can complete after DOMContentLoaded, breaking this guarantee. Since there is no known pattern using top-level await right now, we can document this as a known limitation for now.

Anyway, we should also work on initializing `data-wp-init`, `data-wp-watch`, and `data-wp-run` callbacks if they are dynamically populated in the stores.

File: packages/interactivity/src/index.ts (hunk 1 above)
Comment (DAreRodz) [reply packages/interactivity/src/index.ts]: I replaced this with a function named `onDOMReady` that relies on [`domContentLoadedEventStart`](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming/domContentLoadedEventStart) to know whether the event was dispatched. See https://github.com/WordPress/gutenberg/pull/71123/commits/b83dc4e852e0845bfb8b5c4da8bda675adf416c4.

File: packages/interactivity/src/utils.ts (hunk 2 above)
Comment (DAreRodz) [reply packages/interactivity/src/utils.ts]: I discarded this as I removed the `postTask` util in https://github.com/WordPress/gutenberg/pull/71123/commits/b83dc4e852e0845bfb8b5c4da8bda675adf416c4.

**Comment by DAreRodz** [comment]
@luisherranz, I've updated this PR to use the approach you mentioned in https://github.com/WordPress/gutenberg/pull/71123#issuecomment-3738592059. I've added some e2e tests as well to ensure the race condition mentioned in https://github.com/WordPress/gutenberg/issues/74184#issuecomment-3728586560 is solved.

> Anyway, we should also work on initializing `data-wp-init`, `data-wp-watch`, and `data-wp-run` callbacks if they are dynamically populated in the stores.

Should we address that in a new PR? I can open an issue to keep track of this.

File: packages/interactivity/src/index.ts [hunk 3]
```diff
@@ -12,13 +12,17 @@ import { batch } from '@preact/signals';
  * Internal dependencies
  */
 import registerDirectives, { routerRegions } from './directives';
-import { init, getRegionRootFragment, initialVdom } from './init';
+import {
+	initialVdom,
+	hydrateRegions,
+	getRegionRootFragment,
+} from './hydration';
```
Comment (DAreRodz) [inline packages/interactivity/src/index.ts:19]: I renamed `init.js` to `hydration.js` to further clarify this file's purpose. The same goes for the `init` function, now renamed to `hydrateRegions`. Let me know what you think about these changes.

File: packages/interactivity/src/index.ts [hunk 4]
```diff
@@ -71,5 +75,15 @@ export const privateApis = (
 	throw new Error( 'Forbidden access.' );
 };
 
+// Parses and populates the initial state and config. All the core directives
+// are registered at this point as well.
+populateServerData( parseServerData() );
```
Comment (DAreRodz) [inline packages/interactivity/src/index.ts:80]: I moved the state and config initialization here so that `index.js` is the only file that calls functions.

**Comment by DAreRodz** [comment]
> Since there is no known pattern using top-level await right now, we can document this as a known limitation for now.

I wanted to mention this somewhere in the documentation, although I'm unsure where to do so. 🤔

File: packages/e2e-tests/plugins/interactive-blocks/hydration-timing-async/view.js [hunk 5]
```diff
@@ -0,0 +1,29 @@
+/**
+ * This module dynamically imports @wordpress/interactivity on DOMContentLoaded.
+ *
+ * This simulates a lazy-loading scenario where the Interactivity API is not
+ * statically imported. The test verifies that hydration still occurs even
+ * when the library is loaded after DOMContentLoaded has already fired.
+ */
+
+const initStore = async () => {
+	const { store, getContext } = await import( '@wordpress/interactivity' );
```
Comment (luisherranz) [inline packages/e2e-tests/plugins/interactive-blocks/hydration-timing-async/view.js:10]: These tests are not bundled with webpack, right? The files are served as they are.

File: test/e2e/specs/interactivity/hydration-timing.spec.ts [hunk 6]
```diff
@@ -0,0 +1,100 @@
...
+		page,
+	} ) => {
+		// Delay only the "slow" module to simulate slow network conditions.
+		// The "fast" module loads immediately and imports @wordpress/interactivity,
+		// which could trigger hydration before the slow module finishes loading.
+		await page.route(
+			/hydration-timing-slow\/view\.js/,
+			async ( route ) => {
+				// Add a 500ms delay to simulate slow module loading.
+				await new Promise( ( resolve ) => setTimeout( resolve, 500 ) );
```
Comment (luisherranz) [inline test/e2e/specs/interactivity/hydration-timing.spec.ts]: Maybe we could use more than 500ms here? Something more obvious, like for example 3 seconds?

**Review by luisherranz — APPROVED** [review]
Just a couple of questions, but LGTM! Thanks David 🙂

File: packages/e2e-tests/plugins/interactive-blocks/hydration-timing-async/view.js (hunk 5 above)
Comment (DAreRodz) [reply packages/e2e-tests/plugins/interactive-blocks/hydration-timing-async/view.js:10]: Exactly, the modules in the e2e tests are not being bundled.

File: test/e2e/specs/interactivity/hydration-timing.spec.ts (hunk 6 above)
Comment (DAreRodz) [reply test/e2e/specs/interactivity/hydration-timing.spec.ts]: Done in https://github.com/WordPress/gutenberg/pull/71123/commits/412972d9ef7109d338de39914d04b449b03896f9.

File: packages/e2e-tests/plugins/interactive-blocks/hydration-timing-async/view.js (hunk 5 above)
Comment (luisherranz) [reply packages/e2e-tests/plugins/interactive-blocks/hydration-timing-async/view.js:10]: Perfect, thanks.

**Comment by t-hamano** [comment]
This PR has been backported to the `wp/6.9` branch. #74806
