### PR TITLE
Docgen/stop crashing on missing return types

### LINKED ISSUE #37766: Docgen: Crash for untyped @param descriptions on default re-export
### Description

In context-provider modules we typically re-export the `Provider` as the default export, wrapping a custom context.

```js
export const Context = createContext( false );

const { Consumer, Provider } = Context;

/**
 * @param {boolean} props.value Whether to turn the thing on.
 * @returns {WPComponent} Provider component
 */
export default Provider;
```

For TypeScript modules we don't need or want the type annotations as those are enforced and maintained by the compiler.

```ts
/**
 * @param props.value Whether to turn the thing on.
 * @returns Provider component
 */
export default Provider;
```

When generating the docs though it fails with a couple of different types of errors.

```
TypeError: Cannot read properties of undefined (reading 'name')
```

```
TypeError: Cannot read properties of undefined (reading '0')
```

These come from trying to [get the first parameter](https://github.com/WordPress/gutenberg/blob/trunk/packages/docgen/lib/get-type-annotation.js#L460) and [printing the name of the function in the error log](https://github.com/WordPress/gutenberg/blob/trunk/packages/docgen/lib/get-type-annotation.js#L467).

### Step-by-step reproduction instructions

See Description

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by dmsnell**
Resolves #37766 

## Description

The `docgen` process currently fails in a number of circumstances where it's trying to find type information, specifically return-type information, and can't find it. As highlighted in PRs converting modules to TypeScript, this introduces a mismatch in how some idiomatic code will be written and in the case where we can't find type information we should quietly accept that and remove the type information from the generated docs.

Eventually it would be nice to get better inference from TypeScript on the types it knows, but some issues around type usefulness remain. For now, this patch makes the process more lenient so that it doesn't hold up other changes and so
that we avoid pushing developers from writing value-lacking types such as `{Object}` or `{Function}` for the sake of getting past the linter.

For example, by removing the JSDoc type annotations in #37239 we find the corresponding changes to the `data` package's `README`. The JSDoc description still provides the helpful part of documenting the types and has a lower risk chance of getting out of sync with the code than it would be to annotate `Function` or `<InnerProps extends HOCProps>(Inner: ComponentType<InnerProps>) => {} extends HOCProps ? ComponentType<...> : ComponentType<...>`

```
Δ packages/data/README.md
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

──────────────────────────────────────────────────────┐
• 761: const ParentProvidingRegistry = ( props ) => { │
──────────────────────────────────────────────────────┘
761 ⋮761 │
762 ⋮762 │_Returns_
763 ⋮763 │
764 ⋮    │-   `Function`: A custom react hook exposing the registry context value.
    ⋮764 │-   A custom react hook exposing the registry context value.
765 ⋮765 │
766 ⋮766 │### useSelect
767 ⋮767 │

Δ packages/data/src/components/registry-provider/use-registry.js
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

───────────────────────────────────────────┐
• 45: import { Context } from './context'; │
───────────────────────────────────────────┘
 45 ⋮ 45 │ * };
 46 ⋮ 46 │ * ```
 47 ⋮ 47 │ *
 48 ⋮    │ * @return {Function}  A custom react hook exposing the registry context value.
    ⋮ 48 │ * @return A custom react hook exposing the registry context value.
 49 ⋮ 49 │ */
 50 ⋮ 50 │export default function useRegistry() {
 51 ⋮ 51 │    return useContext( Context );
```

## How has this been tested?

After re-building the package the reference docs were re-generated and no differences in output were found against `trunk` (given that we don't introduce any of the cases that would have broken the `docgen` in this PR we expect no changes).

## Types of changes
This changes the build pipeline, namely it relaxes the requirement that a JSDoc entry for a value that has a description also has an explicit type listed.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by gziolo** [comment]
One of the unit tests related to Docgen fails on CI:

https://github.com/WordPress/gutenberg/runs/4796282998?check_suite_focus=true

I’m personally fine with the changes proposed, but I don’t know the tool that wel.

**Comment by dmsnell** [comment]
Thanks @gziolo - one of the tests seemed to be a spurious issue with a mobile dependency; the other was a good catch. I've updated and hopefully everything will pass now.

File: packages/docgen/lib/get-type-annotation.js [hunk 1]
```diff
@@ -397,7 +397,10 @@ function getFunctionToken( token ) {
 
 function getFunctionNameForError( declarationToken ) {
```
Comment (sarayourfriend) [inline packages/docgen/lib/get-type-annotation.js:398]: This particular function has been such a headache to maintain with its many edge cases. Thanks for taking the time to improve it!

File: packages/docgen/lib/markdown/formatter.js [hunk 2]
```diff
@@ -103,54 +103,88 @@ module.exports = (
 			formatTag(
 				'Related',
 				getSymbolTagsByName( symbol, 'see', 'link' ),
-				( tag ) =>
-					`\n- ${ tag.name.trim() }${
-						tag.description ? ' ' : ''
-					}${ tag.description.trim() }`,
+				( tag ) => {
```
Comment (sarayourfriend) [inline packages/docgen/lib/markdown/formatter.js:106]: Thanks for breaking out the conditional logic in the functions in this file. It improves the readability a lot.

File: packages/docgen/test/get-type-annotation.js [hunk 3]
```diff
@@ -196,16 +196,12 @@ describe( 'Type annotations', () => {
...
+			expect( getTypeAnnotation( returnTag, node, 0 ) ).toBeNull();
 		} );
 
-		it( 'should throw an error if there is no param type', () => {
-			expect( () => getTypeAnnotation( paramTag, node, 0 ) ).toThrow(
-				"Could not find type for parameter 'foo' in function 'fn'."
-			);
+		it( 'should return null if there is no param type', () => {
+			expect( getTypeAnnotation( paramTag, node, 0 ) ).toBeNull();
 		} );
```
Comment (sarayourfriend) [inline packages/docgen/test/get-type-annotation.js]: Can we add some tests for the case where it will throw? That's still a branch in the code.

**Review by sarayourfriend — CHANGES_REQUESTED** [review]
Requesting that we add tests to cover the case where the code will throw. Otherwise this looks good to me. Thanks for digging into this and finding a solution.

File: packages/docgen/test/get-type-annotation.js (hunk 3 above)
Comment (dmsnell) [reply packages/docgen/test/get-type-annotation.js]: it seems like it might be worth removing the `try/catch` entirely because it shouldn't crash after fixing the null-dereference bug. in fact I'm not sure how to trigger a crash because I'm having to dive deep into the other `getType` family functions to try and find an exploit in the code that I could trigger…

Comment (sarayourfriend) [reply packages/docgen/test/get-type-annotation.js]: Okay, in that case let's just remove that try/catch altogether as you suggested. If the code fails there then we'll hopefully get a nice bug report with a more descriptive error than the one we're currently spitting out anyway 🙂

Comment (dmsnell) [reply packages/docgen/test/get-type-annotation.js]: removed the try/catch and had to update other code. I did try a few types that I think should be totally invalid and they don't throw. I think the only thing that did throw was attempting to access the `typeAnnotation` assuming it was there, then trying to grab the name identifier on a function that doesn't exist _for the sake of error reporting_. without these I think we're safe apart from unlikely bugs that could always creep up

**Comment by sarayourfriend** [comment]
Looks like with the most recent change the doc generation is printing empty type and return value descriptions for functions that don't have any type or return annotations.

For example:

```js
/**
 * Initializes WordPress `postboxes` script and the logic for saving meta boxes.
 */
export function* initializeMetaBoxes() {
  // ...
}
```

Results in:

```md
### initializeMetaBoxes

Initializes WordPress `postboxes` script and the logic for saving meta boxes.

_Type_

-

```

I'm curious why the unit tests didn't fail in this case. It'd be good to add a unit test to cover this case based on [the already existing fixture example](https://github.com/WordPress/gutenberg/blob/6999bf8a778034caf0d506bef373cbde698d90b8/packages/docgen/test/fixtures/default-function-named/code.js#L0-L1)

**Comment by dmsnell** [comment]
Thanks for that catch @sarayourfriend. I tried adding a test case for this and it was pretty hard - I couldn't figure out the right way to do it. I also got lost in the test code.

The reason for the extra blank `Type` lines turned out to be a missing type error, ironically, where we were expecting an empty string specifically for the case of no found types vs. having a falsey value, which we are now returning as `undefined`. By relaxing the test, `if ( potentialTypeAnnotation )`, we capture if there's an actual match because if there is it will be a non-empty string, but `undefined` otherwise, potentially an empty string if we mess up elsewhere.

I'm tempted to not add a new test case because in this case it seems like code review was effective at catching this. I'm anxious about spending time working in the test code especially if, as you mentioned, we want to rip out most of this code anyway for a more robust and type-aware version.

**Comment by dmsnell** [comment]
> I'm curious why the unit tests didn't fail in this case

The tests failed because they were verifying that there wasn't any type information `type: undefined` but not that the output didn't have the `_Type_` section.

**Comment by sarayourfriend** [comment]
Nice. At least our CI actually verifies when there is a documentation change and luckily changes to `docgen` that we don't catch as causing documentation changes will cause the CI to fail anyway. In a sense there are still tests guarding us from breaking docgen 🙂

**Comment by dmsnell** [comment]
I'm a bit disturbed that editor tests failed on this unrelated PR.

**Comment by dmsnell** [comment]
@sarayourfriend the tests are all passing and I think the docs are unchanged. is there anything else you would want from this PR?

@jorgefilipecosta added you here for extra eyes, but feel free to ignore if you're busy

**Review by sarayourfriend — APPROVED** [review]
LGTM!
