### PR TITLE
Fix Meta boxes saving when they’re not present

### LINKED ISSUE #67207: Hiding all metaboxes prevents `POST` request to `post.php` to save meta fields
### Description

Since WordPress 6.7, when all the metaboxes are hidden in the preferences, the  `POST` request to `post.php` to save meta fields is not fired anymore as it used to (e.g. in 6.6.2).
This creates problems with plugins, e.g. Yoast SEO, that use a sidebar to allow users to change some post metadata.
In general, this is a different behaviour from what used to happen so any mechanism relying on that request being fired could be affected.

### Step-by-step reproduction instructions

1. Have WordPress 6.7.* on your site
2. Install and activate only one plugin adding metaboxes, e.g. Yoast SEO
3. In the block editor, _Preferences_ > _General_ > _Advanced_, disable "Yoast SEO" and close
4. important: reload the page or edit another post - the metabox needs to be hidden from the beginning
5. open the Yoast SEO sidebar and change a setting, e.g. the focus keyphrase
6. save the post
7. no `POST` request is fired to `post.php`, so the changed value is not saved

Up until  6.6.2, a `POST` request was fired to `post.php` even with hidden metaboxes, so the new value was saved.

Important to notice: the value change in the hidden field works as expected, only the `POST` request is not fired anymore.

Notable finding:
if the user visits _Preferences_ > _General_ > _Advanced_, enables the metabox and then disables it again, then **doesn't reload the page**, the changed value will be saved instead. The problem happens only if all metaboxes are hidden since the editor page has been loaded and the relevant settings have not been touched.

### Screenshots, screen recording, code snippet

https://www.loom.com/share/bdf879f26d67454caca89aa7b6c3de0b (created by a Yoast support engineer for [this issue](https://github.com/Yoast/wordpress-seo/issues/21851))

### Environment info

- WordPress 6.7, 6.7.1
- Firefox 132 on Devuan Linux "Daedalus"
- Local by Flywheel instance with PHP 8.2.10

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by stokesman**
## What?
Ensures meta boxes are saved even if none of their areas are present in the Post editor’s UI.

Fixes #67207. Alternative to #67228 (or possibly a follow up to it).

## Why?
Besides fixing a bug, this makes the meta box initialization more explicit/visible. It’s also a small optimization by invoking an effect in fewer places and executing less code when meta boxes aren’t present.

It seems more sensible this way because the initialization of all meta boxes is not really a responsibility of a component that represents only a single area of meta boxes.

## How?
1. Removes the effect to initialize meta boxes from the `MetaBoxes` component
2. Encapsulates the effect and its dependencies in a custom hook
3. Uses the hook in the `Layout` component

## Testing Instructions
1. Install and activate only one plugin adding metaboxes, e.g. Yoast SEO
2. In the block editor, Preferences > General > Advanced, disable "Yoast SEO" and close
3. Important: reload the page or edit another post - the metabox needs to be hidden from the beginning
open the Yoast SEO sidebar and change a setting, e.g. the focus keyphrase
4. Save the post
5. Observe a request is fired to post.php
6. Reload the page and verify the changed value was persisted

### CODE REVIEW

**Comment by t-hamano** [comment]
Thanks for the PR!

I can't review this PR now because [I haven't yet been able to reproduce the issue](https://github.com/WordPress/gutenberg/issues/67207#issuecomment-2495504579), but the approach looks reasonable.

This PR ensures that `initializeMetaBoxes()` will run if there are meta boxes available, even if there are no visible meta box locations. It will not render empty meta boxes (`.edit-post-layout__metaboxes`) though. Is my understanding correct?

File: packages/edit-post/src/components/meta-boxes/use-meta-box-initialization.js [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+			const { __unstableIsEditorReady } = select( editorStore );
+			const { areMetaBoxesInitialized, getMetaBoxesPerLocation } =
+				select( editPostStore );
+			return {
+				areInitialized: areMetaBoxesInitialized(),
+				isEditorReady: __unstableIsEditorReady(),
+				hasAny:
+					getMetaBoxesPerLocation( 'normal' ).length > 0 ||
+					getMetaBoxesPerLocation( 'advanced' ).length > 0 ||
+					getMetaBoxesPerLocation( 'side' ).length > 0,
```
Comment (afercia) [inline packages/edit-post/src/components/meta-boxes/use-meta-box-initialization.js]: Could this length checks be avoided by using `isMetaBoxLocationActive` directly?

**Comment by afercia** [comment]
@stokesman thanks for looking into this. I quickly tested it and it does fix https://github.com/WordPress/gutenberg/issues/67207

Seems a better approach than https://github.com/WordPress/gutenberg/pull/67228

To my understanding:

While the presentation in the UI of the meta boxes will be still controlled by [hasAnyVisible](https://github.com/WordPress/gutenberg/blob/0b4af6ff15256b04f9fb450239a61dbbf6167ac1/packages/edit-post/src/components/layout/index.js#L230) > `isMetaBoxLocationVisible`, which checks:
- whether there is a metabox in a location
- _and_ the panel is active in the preferences

instead, the functionality and thus the POST request will be controlled by [this new check](https://github.com/WordPress/gutenberg/pull/67254/files#diff-723b03f7a89cd1cbade6044233b630208857021979d8dc4423e23ef3a3f73cd6R30-R33), which only checks whether there is a metabox in a location, regardless of whether it's active in the preferences.

Is that correct?

File: packages/edit-post/src/components/meta-boxes/use-meta-box-initialization.js (hunk 1 above)
Comment (stokesman) [reply packages/edit-post/src/components/meta-boxes/use-meta-box-initialization.js]: Yes! Thanks for the suggestion. It spurred me to reexamine this and find that it can be simplified further. Since all locations are tested then calling the `hasMetaBoxes` selector would be most succinct. Yet, the `Layout` is already using that selector for a couple conditions and so can just pass it in to this hook.

Furthermore, it seems testing `areMetaBoxesInitialized` is extraneous, the `initializeMetaBoxes` action already returns early if initialized so it doesn’t help to test it twice.

Thus I’ve pushed db46c07d5e0f4a87db9784fb7143b6b976e0947e with those changes.

**Comment by stokesman** [comment]
> It will not render empty meta boxes (`.edit-post-layout__metaboxes`) though. Is my understanding correct?

It will not only when none of the locations have any meta boxes. If the "side" location has a meta box and the "normal" or "advanced" do not then `.edit-post-layout__metaboxes` will still render (empty).

--- 

> While the presentation in the UI of the meta boxes will be still controlled by [hasAnyVisible](https://github.com/WordPress/gutenberg/blob/0b4af6ff15256b04f9fb450239a61dbbf6167ac1/packages/edit-post/src/components/layout/index.js#L230) > `isMetaBoxLocationVisible`, which checks:
> 
> * whether there is a metabox in a location
> * _and_ the panel is active in the preferences
> 
> instead, the functionality and thus the POST request will be controlled by [this new check](https://github.com/WordPress/gutenberg/pull/67254/files#diff-723b03f7a89cd1cbade6044233b630208857021979d8dc4423e23ef3a3f73cd6R30-R33), which only checks whether there is a metabox in a location, regardless of whether it's active in the preferences.
> 
> Is that correct?

Correct 🎯

File: packages/edit-post/src/components/layout/index.js [hunk 2]
```diff
@@ -414,6 +415,8 @@ function Layout( {
 			const { isZoomOut } = unlock( select( blockEditorStore ) );
 			const { getEditorMode, getRenderingMode } = select( editorStore );
 			const isRenderingPostOnly = getRenderingMode() === 'post-only';
+			const isNotDesignPostType =
+				! DESIGN_POST_TYPES.includes( currentPostType );
```
Comment (stokesman) [inline packages/edit-post/src/components/layout/index.js:419]: Unrelated micro optimization here so that the couple of places this was evaluated can share the result (and read a little better I think).

**Review by t-hamano — APPROVED** [review]
I've tested this PR again and everything works as expected, so I think it can be backported to WP 6.7.2.

cc @cbravobernal

File: packages/edit-post/src/components/meta-boxes/use-meta-box-initialization.js [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+ * Internal dependencies
+ */
+import { store as editPostStore } from '../../store';
+
+/**
+ * Initializes WordPress `postboxes` script and the logic for saving meta boxes.
+ *
+ * @param { boolean } enabled
+ */
+export default ( enabled ) => {
```
Comment (Mamaduka) [inline packages/edit-post/src/components/meta-boxes/use-meta-box-initialization.js]: Can we do a named export here, `export default function useMetaBoxInitialization( enabled )`? This would make it easier to search for hooks/components in the codebase.

Comment (stokesman) [reply packages/edit-post/src/components/meta-boxes/use-meta-box-initialization.js]: Sure, done in 030c6a5b25ca1b6b1f0e054a48f8258199495a53.

**Comment by cbravobernal** [comment]
@t-hamano, @stokesman  I tried to do a cherry-pick to the `6.7` branch. But it is conflicting:

```
<<<<<<< HEAD

			const isZoomOut = __unstableGetEditorMode() === 'zoom-out';
=======
			const { isZoomOut } = unlock( select( blockEditorStore ) );
			const { getEditorMode, getRenderingMode } = select( editorStore );
			const isRenderingPostOnly = getRenderingMode() === 'post-only';
			const isNotDesignPostType =
				! DESIGN_POST_TYPES.includes( currentPostType );
>>>>>>> cd26001761 (Fix Meta boxes saving when they’re not present (#67254))

			return {
				mode: select( editorStore ).getEditorMode(),
				isFullscreenActive:
					select( editPostStore ).isFeatureActive( 'fullscreenMode' ),
				hasActiveMetaboxes: select( editPostStore ).hasMetaBoxes(),
				hasBlockSelected:
					!! select( blockEditorStore ).getBlockSelectionStart(),
				showIconLabels: get( 'core', 'showIconLabels' ),
				isDistractionFree: get( 'core', 'distractionFree' ),
<<<<<<< HEAD
				showMetaBoxes:
					! DESIGN_POST_TYPES.includes( currentPostType ) &&
					! isZoomOut,
=======
				showMetaBoxes: isNotDesignPostType && ! isZoomOut(),
>>>>>>> cd26001761 (Fix Meta boxes saving when they’re not present (#67254))
				isWelcomeGuideVisible: isFeatureActive( 'welcomeGuide' ),
				templateId:
					supportsTemplateMode &&
					isViewable &&
					canViewTemplate &&
					! isEditingTemplate
						? getEditedPostTemplateId()
						: null,
<<<<<<< HEAD
			};
		},
		[ currentPostType, isEditingTemplate, settings.supportsTemplateMode ]
=======
				enablePaddingAppender:
					! isZoomOut() && isRenderingPostOnly && isNotDesignPostType,
			};
		},
		[
			currentPostType,
			currentPostId,
			isEditingTemplate,
			settings.supportsTemplateMode,
		]
	);
	useMetaBoxInitialization( hasActiveMetaboxes );

	const [ paddingAppenderRef, paddingStyle ] = usePaddingAppender(
		enablePaddingAppender
>>>>>>> cd26001761 (Fix Meta boxes saving when they’re not present (#67254))
	);
```

I don't have the context to decide what should be in 6.7 branch vs trunk right now. Can you please take a look? Otherwise it will take some time to understand everything 😅

**Comment by stokesman** [comment]
It looks like the only thing that needs kept from this branch in those conflicted sections is:
```js
useMetaBoxInitialization( hasActiveMetaboxes );
```
I’ve made #67503 as such. I’ve yet to manually test it but I’ll do so now.

UPDATE: That PR works well but while testing I realized this PR had introduced a separate regression. Now meta boxes don’t hide/show as intended. I have #67504 open to fix trunk.

File: packages/edit-post/src/components/meta-boxes/index.js [hunk 4]
```diff
@@ -13,38 +11,11 @@ import MetaBoxVisibility from './meta-box-visibility';
...
-				getMetaBoxesPerLocation,
-				areMetaBoxesInitialized: _areMetaBoxesInitialized,
-			} = select( editPostStore );
-			return {
-				metaBoxes: getMetaBoxesPerLocation( location ),
-				areMetaBoxesInitialized: _areMetaBoxesInitialized(),
-				isEditorReady: __unstableIsEditorReady(),
-			};
-		},
-		[ location ]
```
Comment (stokesman) [inline packages/edit-post/src/components/meta-boxes/index.js:30]: This dependency should not have been removed 🤦‍♂️.

File: packages/edit-post/src/components/meta-boxes/index.js [hunk 5]
```diff
@@ -13,38 +11,11 @@ import MetaBoxVisibility from './meta-box-visibility';
...
+	const metaBoxes = useSelect(
+		( select ) =>
+			select( editPostStore ).getMetaBoxesPerLocation[ location ]
```
Comment (stokesman) [inline packages/edit-post/src/components/meta-boxes/index.js:16]: Should be a function call `getMetaBoxesPerLocation( location )`. Bummer this was missed as it seems to break hiding/showing of the meta boxes.

**Comment by cbravobernal** [comment]
I compared the code with the ´wp/6.7´ and both are the same except from ´enablePaddingAppender´. Which doesn't exist on that branch. I can consider this PR backported, but please @stokesman confirm if we need anything else.

**Comment by stokesman** [comment]
> I can consider this PR backported, but please @stokesman confirm if we need anything else.

Yes, nothing else should be needed.
