### PR TITLE
[Automated Testing]: Fix preview e2e tests

### LINKED ISSUE #35387: [Flaky Test] should open a preview window for a new post
<!-- __META_DATA__:{"failedTimes":11,"totalCommits":1} -->
**Flaky test detected. This is an auto-generated issue by GitHub Actions. Please do NOT edit this manually.**

## Test title
should open a preview window for a new post

## Test path
`/test/e2e/specs/editor/various/preview.spec.js`

## Errors
<!-- __TEST_RESULTS_LIST__ -->
<!-- __TEST_RESULT__ --><time datetime="2021-10-06T06:54:30.977Z"><code>[2021-10-06T06:54:30.977Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1310705294"><code>fix/save-focus-loss</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-12T06:56:23.500Z"><code>[2021-10-12T06:56:23.500Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/1331905678"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-12T08:49:31.391Z"><code>[2021-10-12T08:49:31.391Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1332239849"><code>mobile/issue/3055-show-disabled-block-reason</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-12T09:13:57.185Z"><code>[2021-10-12T09:13:57.185Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1332328778"><code>try/link-control-split-url-text</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-12T10:13:22.880Z"><code>[2021-10-12T10:13:22.880Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/1332556871"><code>add/detailed-loading-performance-times</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-12T11:58:21.239Z"><code>[2021-10-12T11:58:21.239Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/1332884264"><code>fix/inlined-relative-urls</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-12T12:00:14.460Z"><code>[2021-10-12T12:00:14.460Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/1332671867"><code>update/theme-block-placeholder-content</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-12T12:02:59.462Z"><code>[2021-10-12T12:02:59.462Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/1332079987"><code>add/template-details-for-template-part</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-12T12:56:41.399Z"><code>[2021-10-12T12:56:41.399Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/1333089409"><code>update/card-global-styles-root</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-12T13:12:45.865Z"><code>[2021-10-12T13:12:45.865Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/1333138917"><code>fix-helphub-link-i18n</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-12T13:18:27.166Z"><code>[2021-10-12T13:18:27.166Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/1332766422"><code>fix/block-inserter-gap</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-12T15:01:55.126Z"><code>[2021-10-12T15:01:55.126Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1333476713"><code>bug/help-section-overflow</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-12T15:16:58.896Z"><code>[2021-10-12T15:16:58.896Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/1333627397"><code>update/components-navigator-sticky</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-12T16:20:02.317Z"><code>[2021-10-12T16:20:02.317Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1333870048"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-12T17:01:40.720Z"><code>[2021-10-12T17:01:40.720Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1334003817"><code>remove/use-jump-step</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-12T21:41:24.123Z"><code>[2021-10-12T21:41:24.123Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/1334899740"><code>bug/android-bottom-sheet-overlay</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-12T22:21:14.916Z"><code>[2021-10-12T22:21:14.916Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/1335017065"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-13T01:02:42.042Z"><code>[2021-10-13T01:02:42.042Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/1335433660"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-13T04:36:14.580Z"><code>[2021-10-13T04:36:14.580Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/1335945912"><code>update/inspector-controls-design-tools-order</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-13T05:10:11.531Z"><code>[2021-10-13T05:10:11.531Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1336009518"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-13T06:13:58.480Z"><code>[2021-10-13T06:13:58.480Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1336156144"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-13T07:32:41.656Z"><code>[2021-10-13T07:32:41.656Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1336360353"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-10-13T08:23:29.085Z"><code>[2021-10-13T08:23:29.085Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1336517296"><code>fix/toggle-group-control-visual-state-when-value-not-exists-in-options</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-11-11T13:08:55.585Z"><code>[2021-11-11T13:08:55.585Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1448787299"><code>add/edit-site-list</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2021-11-18T11:07:03.265Z"><code>[2021-11-18T11:07:03.265Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1476003644"><code>try/alternate-fixed-appender</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-18T02:56:40.834Z"><code>[2022-03-18T02:56:40.834Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2001941799"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-27T22:26:40.443Z"><code>[2022-03-27T22:26:40.443Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2049097811"><code>try/partial-multi-selection</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-24T22:48:00.395Z"><code>[2022-06-24T22:48:00.395Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2558503156"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-07-19T10:06:22.806Z"><code>[2022-07-19T10:06:22.806Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2696670910"><code>update/re-architect-templates-addition</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-07-21T06:48:21.494Z"><code>[2022-07-21T06:48:21.494Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2709783778"><code>add/slider-component</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-07-27T14:44:27.005Z"><code>[2022-07-27T14:44:27.005Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2747331055"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-08-23T15:57:02.638Z"><code>[2022-08-23T15:57:02.638Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2912737004"><code>update/add-canRead-to-use-resource-permissions</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-09-28T05:50:55.509Z"><code>[2022-09-28T05:50:55.509Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3141006322"><code>try/tools-panel-in-global-styles</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-09-29T07:16:43.000Z"><code>[2022-09-29T07:16:43.000Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3149196796"><code>form-fields</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-10-21T12:54:47.816Z"><code>[2022-10-21T12:54:47.816Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3297415141"><code>migrate/gallery-caption-tests-playwright</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-10-21T18:42:45.973Z"><code>[2022-10-21T18:42:45.973Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3299514477"><code>tests/record-cpus-data</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-10-26T02:21:11.934Z"><code>[2022-10-26T02:21:11.934Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3325593424"><code>fix/color-palette-pattern</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-10-30T19:08:21.370Z"><code>[2022-10-30T19:08:21.370Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3356599168"><code>fix/text-control-storybook-help-label-type</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-11-01T19:08:23.158Z"><code>[2022-11-01T19:08:23.158Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3371915277"><code>refactor/url-popover-placement-position</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-11-17T05:35:31.240Z"><code>[2022-11-17T05:35:31.240Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3485510930"><code>add-test-for-post-title-block-render</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-11-18T15:48:58.832Z"><code>[2022-11-18T15:48:58.832Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3498053599"><code>upgrade/react-18-pure-with-react-native-upgrade</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-11-23T17:25:11.033Z"><code>[2022-11-23T17:25:11.033Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3534047154"><code>fix/undo-after-autocorrect</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-11-29T10:23:51.920Z"><code>[2022-11-29T10:23:51.920Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3572920640"><code>refactor/lodash-filter</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-12-01T12:12:51.714Z"><code>[2022-12-01T12:12:51.714Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3592220926"><code>perf/refactor-tree</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-12-05T02:52:27.787Z"><code>[2022-12-05T02:52:27.787Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3616319927"><code>update/hide-context-block-toolbar</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-12-09T05:54:08.011Z"><code>[2022-12-09T05:54:08.011Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3654726294"><code>add/block-style-editing</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-12-09T17:54:36.860Z"><code>[2022-12-09T17:54:36.860Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3659385108"><code>use/offsite-menu-component-on-the-navigation-inspector</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-12-12T15:10:17.387Z"><code>[2022-12-12T15:10:17.387Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3676809759"><code>refactor/lodash-find-core-data</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-12-12T20:47:37.611Z"><code>[2022-12-12T20:47:37.611Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3679439183"><code>ts-responsive-wrapper</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-12-13T15:31:44.230Z"><code>[2022-12-13T15:31:44.230Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3686555729"><code>fix/42689</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-12-14T08:37:41.895Z"><code>[2022-12-14T08:37:41.895Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3692884947"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-12-15T06:00:36.316Z"><code>[2022-12-15T06:00:36.316Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/3701362805"><code>add/typography-columns-support</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-12-15T10:12:07.797Z"><code>[2022-12-15T10:12:07.797Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3702860357"><code>try/page-list-submenu</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-12-19T12:38:57.264Z"><code>[2022-12-19T12:38:57.264Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3731218714"><code>add/query-loop-terms-dynamic-suggestions-fetching</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-12-19T12:59:18.534Z"><code>[2022-12-19T12:59:18.534Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3731218714"><code>add/query-loop-terms-dynamic-suggestions-fetching</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-12-20T04:44:42.379Z"><code>[2022-12-20T04:44:42.379Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3737400839"><code>fix/performance-tests</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-12-20T11:20:38.837Z"><code>[2022-12-20T11:20:38.837Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3739773626"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-12-27T12:35:54.512Z"><code>[2022-12-27T12:35:54.512Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3787257744"><code>try/improve-block-context-cache</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-01-02T11:13:38.023Z"><code>[2023-01-02T11:13:38.023Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3821946485"><code>update/post-featured-image-wrapper-height</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-01-06T12:29:27.195Z"><code>[2023-01-06T12:29:27.195Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3854988095"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-01-09T15:40:12.666Z"><code>[2023-01-09T15:40:12.666Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3875038862"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-01-10T14:51:03.440Z"><code>[2023-01-10T14:51:03.440Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3884176918"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-01-11T18:43:08.707Z"><code>[2023-01-11T18:43:08.707Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3895437506"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-01-16T10:05:49.566Z"><code>[2023-01-16T10:05:49.566Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3929007399"><code>fix/arrow-key-resizing</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-01-16T10:34:22.730Z"><code>[2023-01-16T10:34:22.730Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/3929218974"><code>add/get-set-content-inside-balanced-tags</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-01-25T00:55:11.857Z"><code>[2023-01-25T00:55:11.857Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4001635966"><code>update/custom-css-move-to-menu</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-01-26T22:24:03.745Z"><code>[2023-01-26T22:24:03.745Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4019386924"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-01-30T10:01:15.551Z"><code>[2023-01-30T10:01:15.551Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4042373891"><code>add/tag-selection-dropdown</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-01-30T12:37:20.444Z"><code>[2023-01-30T12:37:20.444Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4032516688"><code>refactor/Notice-typescript</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-02T10:32:04.545Z"><code>[2023-02-02T10:32:04.545Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/4073301940"><code>optimize/downloadable-blocks-panel</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-04T14:19:13.585Z"><code>[2023-02-04T14:19:13.585Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/4091899111"><code>fix/colorpalette-contrast-check</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-05T23:06:49.194Z"><code>[2023-02-05T23:06:49.194Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4098804295"><code>refactor/tools-panel-ts</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-06T23:41:28.383Z"><code>[2023-02-06T23:41:28.383Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4108819969"><code>tests/store-perf-test-results</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-07T06:42:47.285Z"><code>[2023-02-07T06:42:47.285Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4111109144"><code>fix/core-data-hooks-eslint</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-07T17:12:02.031Z"><code>[2023-02-07T17:12:02.031Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4116215595"><code>add/template-modal</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-07T17:30:43.149Z"><code>[2023-02-07T17:30:43.149Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4116378747"><code>rename-experiments-to-private-apis</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-07T21:12:20.730Z"><code>[2023-02-07T21:12:20.730Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4118075198"><code>remove/lodash-wordpress-data</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-08T10:42:45.050Z"><code>[2023-02-08T10:42:45.050Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4123071877"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-08T15:11:19.085Z"><code>[2023-02-08T15:11:19.085Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4125273394"><code>tests/store-perf-test-results</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-08T15:22:51.643Z"><code>[2023-02-08T15:22:51.643Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4125273394"><code>tests/store-perf-test-results</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-09T07:01:12.820Z"><code>[2023-02-09T07:01:12.820Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4131612162"><code>try/link-preview</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-09T09:26:05.335Z"><code>[2023-02-09T09:26:05.335Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4132521756"><code>refactor/remove-name-element-props-from-typography-panel</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-13T01:57:25.945Z"><code>[2023-02-13T01:57:25.945Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4159231011"><code>try/list-view-scroll-off-screen-selected-blocks-into-view</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-13T02:27:08.413Z"><code>[2023-02-13T02:27:08.413Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4159393038"><code>fix/render_block_core_page_list</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-13T12:11:17.341Z"><code>[2023-02-13T12:11:17.341Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4163020860"><code>wp/6.2</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-17T09:13:34.480Z"><code>[2023-02-17T09:13:34.480Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4202056067"><code>fix/customized-template-info-accessibility</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-17T11:12:50.766Z"><code>[2023-02-17T11:12:50.766Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4202965119"><code>fix-i18n/date-format-picker</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-17T12:36:06.926Z"><code>[2023-02-17T12:36:06.926Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4203595698"><code>fix-i18n/block-parent-selector</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-19T07:08:38.791Z"><code>[2023-02-19T07:08:38.791Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4214778301"><code>migrate/playwright-multi-block-selection</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-19T07:52:05.246Z"><code>[2023-02-19T07:52:05.246Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4214778301"><code>migrate/playwright-multi-block-selection</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-20T05:54:45.842Z"><code>[2023-02-20T05:54:45.842Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4220376392"><code>rnmobile/add-reassure</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-21T11:30:54.546Z"><code>[2023-02-21T11:30:54.546Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4231953931"><code>try/test-pr-46983</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-23T09:53:37.017Z"><code>[2023-02-23T09:53:37.017Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4251069132"><code>feat/storybook-e2e-tests-custom-controls</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-23T12:36:43.500Z"><code>[2023-02-23T12:36:43.500Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4252374388"><code>revert/link-control-changes</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-23T16:39:12.870Z"><code>[2023-02-23T16:39:12.870Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4254543048"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-24T06:19:44.277Z"><code>[2023-02-24T06:19:44.277Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4259719245"><code>add/site-logo-border</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-28T06:59:00.106Z"><code>[2023-02-28T06:59:00.106Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4290181161"><code>add/details-summary-block</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-02-28T09:12:38.103Z"><code>[2023-02-28T09:12:38.103Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4291038401"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-01T04:47:36.967Z"><code>[2023-03-01T04:47:36.967Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4300006453"><code>fix/layout-class-attribution</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-01T17:16:35.225Z"><code>[2023-03-01T17:16:35.225Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4305834634"><code>wp/6.2</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-01T17:31:31.122Z"><code>[2023-03-01T17:31:31.122Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4306104603"><code>refactor/Autocomplete-typescript</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-02T13:53:24.538Z"><code>[2023-03-02T13:53:24.538Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4314356626"><code>refactor/guide-typescript</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-02T15:23:24.285Z"><code>[2023-03-02T15:23:24.285Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4315229137"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-03T12:33:51.162Z"><code>[2023-03-03T12:33:51.162Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4323319616"><code>remove/use-anchor-value-dependency</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-06T09:59:24.968Z"><code>[2023-03-06T09:59:24.968Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4341828852"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-06T12:46:55.294Z"><code>[2023-03-06T12:46:55.294Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4343264727"><code>fix/browse-mode-desc-margings</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-09T06:46:17.822Z"><code>[2023-03-09T06:46:17.822Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4371645442"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-09T12:51:48.266Z"><code>[2023-03-09T12:51:48.266Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4374327338"><code>try/global-styles-style-engine</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-12T12:27:06.618Z"><code>[2023-03-12T12:27:06.618Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4397365374"><code>add/styles-section-to-the-browse-mode-sidebar</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-13T13:18:25.354Z"><code>[2023-03-13T13:18:25.354Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4405048464"><code>fix/global-styles-getPresetsClasses-crashes-if-there-is-no-selector-passed</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-14T03:25:42.193Z"><code>[2023-03-14T03:25:42.193Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4411721342"><code>try/grid-layout</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-15T06:24:54.975Z"><code>[2023-03-15T06:24:54.975Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4423248120"><code>update/default-media-text-align-to-none</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-15T07:02:28.371Z"><code>[2023-03-15T07:02:28.371Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4423248120"><code>update/default-media-text-align-to-none</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-16T08:20:54.884Z"><code>[2023-03-16T08:20:54.884Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4434707546"><code>try/block-tools-marry-document-tools</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-17T08:07:50.326Z"><code>[2023-03-17T08:07:50.326Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4445269444"><code>try/global-styles-style-engine</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-17T17:01:01.992Z"><code>[2023-03-17T17:01:01.992Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4449587331"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-21T08:01:57.641Z"><code>[2023-03-21T08:01:57.641Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4476519200"><code>rnmobile/add-reassure-pt-2</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-21T15:08:58.613Z"><code>[2023-03-21T15:08:58.613Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4480338060"><code>refactor/GradientPicker-typescript</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-22T14:01:21.798Z"><code>[2023-03-22T14:01:21.798Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4490429220"><code>update/wp-prettier-2.8.5</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-03-31T05:24:40.971Z"><code>[2023-03-31T05:24:40.971Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4571678342"><code>fix/cover-block-tests</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-04-12T23:01:25.581Z"><code>[2023-04-12T23:01:25.581Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4683294126"><code>add-published-types-checker</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-04-17T07:49:32.435Z"><code>[2023-04-17T07:49:32.435Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4718544193"><code>add/elements-variations-custom-css</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-04-18T22:24:54.895Z"><code>[2023-04-18T22:24:54.895Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4737254870"><code>add/gutenberg_register_fonts_from_theme_json-tests</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-04-20T01:44:28.616Z"><code>[2023-04-20T01:44:28.616Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4749225974"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-04-22T01:41:06.642Z"><code>[2023-04-22T01:41:06.642Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4770095402"><code>update-port-parsing</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-04-25T17:45:12.540Z"><code>[2023-04-25T17:45:12.540Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4800287624"><code>fix/iframe-enqueuing</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-04-27T04:23:23.179Z"><code>[2023-04-27T04:23:23.179Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4815775926"><code>try/wrapping-patterns-in-pattern-block</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-04-27T20:56:15.072Z"><code>[2023-04-27T20:56:15.072Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4824052490"><code>update/tree-grid-readme-a11y</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-05-03T17:13:35.175Z"><code>[2023-05-03T17:13:35.175Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/4874192340"><code>try/pass-rich-text-value-to-store</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-05-11T13:21:17.374Z"><code>[2023-05-11T13:21:17.374Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/4948088044"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-05-30T11:59:11.787Z"><code>[2023-05-30T11:59:11.787Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5120886073"><code>fix/navigation-block-aria-expanded-on-hover</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-06-02T11:25:20.522Z"><code>[2023-06-02T11:25:20.522Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5154637047"><code>browse-mode-navigation-options</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-06-07T05:14:00.259Z"><code>[2023-06-07T05:14:00.259Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5196008480"><code>try/site-editor-library</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-06-07T13:39:57.788Z"><code>[2023-06-07T13:39:57.788Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5200288551"><code>try/auto-inserting-block-patterns</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-06-08T20:40:50.360Z"><code>[2023-06-08T20:40:50.360Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5215215915"><code>refactor/remove-unnecesary-select-all</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-06-09T20:22:13.157Z"><code>[2023-06-09T20:22:13.157Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5225495570"><code>release/16.0</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-06-10T09:06:43.618Z"><code>[2023-06-10T09:06:43.618Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5229008186"><code>add/list-experimental-api-matches</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-06-10T12:16:31.395Z"><code>[2023-06-10T12:16:31.395Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5229008186"><code>add/list-experimental-api-matches</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-06-13T15:45:36.878Z"><code>[2023-06-13T15:45:36.878Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5257153122"><code>update/move-reset-button-to-default-option</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-06-15T16:12:52.508Z"><code>[2023-06-15T16:12:52.508Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5280757961"><code>add/distraction-free-to-site-editor</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-06-19T13:45:09.371Z"><code>[2023-06-19T13:45:09.371Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5312095960"><code>refactor/playwright-performance-tests</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-06-28T08:28:01.655Z"><code>[2023-06-28T08:28:01.655Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5398646517"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-06T03:49:26.174Z"><code>[2023-07-06T03:49:26.174Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5471188003"><code>update/patterns-to-list-all-template-part-areas</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-10T18:55:23.034Z"><code>[2023-07-10T18:55:23.034Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5511579157"><code>fix/unique-global-font-sizes</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-10T20:22:11.798Z"><code>[2023-07-10T20:22:11.798Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5511579157"><code>fix/unique-global-font-sizes</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-10T20:33:32.749Z"><code>[2023-07-10T20:33:32.749Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5512483214"><code>revert-52227</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-11T06:28:08.547Z"><code>[2023-07-11T06:28:08.547Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5516327506"><code>item/fix-focus-state-as-a</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-11T09:16:32.509Z"><code>[2023-07-11T09:16:32.509Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5517806837"><code>try/display-archive-title</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-11T09:29:42.642Z"><code>[2023-07-11T09:29:42.642Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5517930788"><code>update/loginout-spacing</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-11T10:10:28.604Z"><code>[2023-07-11T10:10:28.604Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5518338882"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-13T06:53:59.742Z"><code>[2023-07-13T06:53:59.742Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5539786100"><code>fix/dimensions-visualizers-avoid-errors</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-13T18:42:45.125Z"><code>[2023-07-13T18:42:45.125Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5546419834"><code>create-block-interactive-template-v2</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-13T19:05:38.583Z"><code>[2023-07-13T19:05:38.583Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5546419834"><code>create-block-interactive-template-v2</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-17T12:10:11.560Z"><code>[2023-07-17T12:10:11.560Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5575194831"><code>fix/dimensions-panel-decode</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-18T12:33:39.250Z"><code>[2023-07-18T12:33:39.250Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5587133915"><code>enhancement/patterns-sticky-header</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-18T14:30:23.923Z"><code>[2023-07-18T14:30:23.923Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5588400246"><code>try/fn-revision</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-18T16:40:15.979Z"><code>[2023-07-18T16:40:15.979Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5589773093"><code>rnmobile/add/e2e-util-addBlockUsingAppender</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-18T17:06:32.182Z"><code>[2023-07-18T17:06:32.182Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5590039154"><code>improve/visual-editor-disabled-message</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-19T03:45:26.649Z"><code>[2023-07-19T03:45:26.649Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5594537941"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-19T10:14:49.886Z"><code>[2023-07-19T10:14:49.886Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5597559323"><code>rnmobile/update-media-placeholders-and-block-outline</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-20T06:17:24.252Z"><code>[2023-07-20T06:17:24.252Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5607349796"><code>wp/latest</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-20T10:36:53.299Z"><code>[2023-07-20T10:36:53.299Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5609636722"><code>form-fields</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-21T01:14:24.590Z"><code>[2023-07-21T01:14:24.590Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5617365791"><code>update/patterns-command</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-21T07:02:28.797Z"><code>[2023-07-21T07:02:28.797Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5619336429"><code>fix/image-block-deprecation</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-21T07:45:33.733Z"><code>[2023-07-21T07:45:33.733Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5619689602"><code>try/move-padding-background</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-21T19:34:20.393Z"><code>[2023-07-21T19:34:20.393Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5625683399"><code>interactivity-store-json-encode-inside-render</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-25T04:50:10.876Z"><code>[2023-07-25T04:50:10.876Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5652576541"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-25T11:00:39.984Z"><code>[2023-07-25T11:00:39.984Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5655618770"><code>revert/verse-disable-line-breaks</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-25T12:38:49.439Z"><code>[2023-07-25T12:38:49.439Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5656492114"><code>i11y/remove-hyphen-from-hex-value</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-25T14:04:36.037Z"><code>[2023-07-25T14:04:36.037Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5657490726"><code>rnmobile/0.69.4-upgrade-gradle-to-8.2.1-and-agp-to-8.0.2</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-25T15:07:22.897Z"><code>[2023-07-25T15:07:22.897Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5657490726"><code>rnmobile/0.69.4-upgrade-gradle-to-8.2.1-and-agp-to-8.0.2</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-25T22:31:23.370Z"><code>[2023-07-25T22:31:23.370Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5662179505"><code>components-ui-cleanup</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-26T14:19:52.795Z"><code>[2023-07-26T14:19:52.795Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5669653992"><code>try/enfoce-prs-make-readonly</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-26T17:45:07.167Z"><code>[2023-07-26T17:45:07.167Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5671790605"><code>fix/52216</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-27T07:58:36.251Z"><code>[2023-07-27T07:58:36.251Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5677744257"><code>rnmobile/non-functioning-gallery-caption-button</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-27T08:37:46.346Z"><code>[2023-07-27T08:37:46.346Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5677744257"><code>rnmobile/non-functioning-gallery-caption-button</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-27T14:47:25.213Z"><code>[2023-07-27T14:47:25.213Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5681748086"><code>fix/dfm-sidebar</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-27T20:10:42.612Z"><code>[2023-07-27T20:10:42.612Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5684758088"><code>try/fonts-library-backend</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-28T10:42:41.372Z"><code>[2023-07-28T10:42:41.372Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5690799497"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-07-31T21:01:33.184Z"><code>[2023-07-31T21:01:33.184Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5662179505"><code>components-ui-cleanup</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-08-01T02:23:20.728Z"><code>[2023-08-01T02:23:20.728Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5721605092"><code>try/footnotes-disallow-in-patterns-prevent-duplication</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-08-01T05:57:10.245Z"><code>[2023-08-01T05:57:10.245Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5722990149"><code>update/second-round-6-3-rc3</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-08-07T11:33:23.123Z"><code>[2023-08-07T11:33:23.123Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5784303633"><code>docs/interactivity-api-package-README</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-08-15T08:59:08.693Z"><code>[2023-08-15T08:59:08.693Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/5865159888"><code>try/adding-more-block-instance-elements-support</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-08-29T17:02:26.657Z"><code>[2023-08-29T17:02:26.657Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/6014995047"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-08-29T23:37:51.007Z"><code>[2023-08-29T23:37:51.007Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/6018333059"><code>update/block-editor-inserter-merge-patterns</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-09-04T09:23:02.911Z"><code>[2023-09-04T09:23:02.911Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/6071225341"><code>update/make-shortcuts-provider-optional-2</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-09-21T13:18:34.044Z"><code>[2023-09-21T13:18:34.044Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/6261868047"><code>try/perf-log-out-everything</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-09-27T09:54:23.639Z"><code>[2023-09-27T09:54:23.639Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/6323998899"><code>rnmobile/try/optional-chaining-reusableblock-call</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-09-28T17:13:50.387Z"><code>[2023-09-28T17:13:50.387Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/6341792087"><code>try/fixed-fonts</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-10-04T02:50:53.861Z"><code>[2023-10-04T02:50:53.861Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/6400795176"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-10-09T05:35:06.905Z"><code>[2023-10-09T05:35:06.905Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/6452542166"><code>fix/drag-over-iframe-positioning</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-10-11T21:39:34.533Z"><code>[2023-10-11T21:39:34.533Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/6487955751"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-10-16T15:30:03.731Z"><code>[2023-10-16T15:30:03.731Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/6535444485"><code>6.4-rc1-2</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-10-18T11:04:12.274Z"><code>[2023-10-18T11:04:12.274Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/6559591806"><code>add/e2e-utils-editor-preferences</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2023-10-24T14:10:36.269Z"><code>[2023-10-24T14:10:36.269Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/6627491178"><code>test/ignore-android-build-files</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><details>
<summary>
	<time datetime="2024-04-24T07:31:27.496Z"><code>[2024-04-24T07:31:27.496Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/8812471906"><code>update/selector-scoping-utils</code></a>.
</summary>

```
Test timeout of 100000ms exceeded.
```
</details><!-- /__TEST_RESULT__ -->
<!-- /__TEST_RESULTS_LIST__ -->

### PR DESCRIPTION
**Pull request by ntsekouras**
Fixes: https://github.com/WordPress/gutenberg/issues/35387

Previously `publishPost` util relied on waiting for the snackbar to exist, but after https://github.com/WordPress/gutenberg/pull/34731 a snackbar is shown in other cases as well - like saving a draft. This can create unexpected results with race conditions. An example would be the [preview test here](https://github.com/WordPress/gutenberg/blob/17bdf97b7ecfe579dfac10b415b84cf959865fdf/packages/e2e-tests/specs/editor/various/preview.test.js#L155-L161) where:
1. we initiated the save/publish
2. snackbar was there so the promise of `publishPost` resolved sooner than what we wanted
3. started typing in an input
4. the actual save/publish kicks in and `getEditedEntityRecord` gets these edits.

I think I got it right here with the flow.. --cc  @youknowriad ?

This PR changes the util to wait for `PostPublishPanelPostpublish`.

--edit seems PostPublishPanelPostpublish is not doing the trick and should find a better way to reliably know when a post is published..

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]
Good catch, Nik.

I ran tests locally using the following snippet ten times, and all of them were green 👍 

```
for i in {1..10}; do npm run test-e2e -- packages/e2e-tests/specs/editor/various/preview.test.js; done
```

**Comment by ntsekouras** [comment]
>I ran tests locally using the following snippet ten times, and all of them were green 👍

Locally tests were passing for me as well 😄

File: packages/e2e-test-utils/src/publish-post.js [hunk 1]
```diff
@@ -16,5 +16,7 @@ export async function publishPost() {
 	await page.click( '.editor-post-publish-button' );
 
 	// A success notice should show up
-	return page.waitForSelector( '.components-snackbar' );
+	return page.waitForXPath(
+		'//div[contains(@class, "components-snackbar__content") and contains(text(),"Post published.")]'
```
Comment (Mamaduka) [inline packages/e2e-test-utils/src/publish-post.js]: The message can be different based on CPT, and since this is a public util method, it might break things.

**Comment by Mamaduka** [comment]
> Locally tests were passing for me as well 😄

At this point, it's expected from e2e tests 😄

File: packages/e2e-test-utils/src/publish-post.js (hunk 1 above)
Comment (ntsekouras) [reply packages/e2e-test-utils/src/publish-post.js]: You're right! I'll check it better first thing tomorrow that I'll have more time, as I'm leaving now..

File: packages/e2e-test-utils/src/publish-post.js [hunk 2]
```diff
@@ -15,6 +15,6 @@ export async function publishPost() {
 	// Publish the post
 	await page.click( '.editor-post-publish-button' );
 
-	// A success notice should show up
-	return page.waitForSelector( '.components-snackbar' );
+	// `PostPublishPanelPostpublish` will be visible after the post is published.
+	return page.waitForSelector( '.post-publish-panel__postpublish' );
```
Comment (ellatrix) [inline packages/e2e-test-utils/src/publish-post.js]: Looks like this is not there in some cases. What if we dismiss the previous snackbar before checking again?

Comment (ntsekouras) [reply packages/e2e-test-utils/src/publish-post.js]: Seems the alternative PR didn't seem to do the trick either.. How do you feel about adding a temp fix for this test for now to make CI green and handle the main problem separately?

Comment (ellatrix) [reply packages/e2e-test-utils/src/publish-post.js]: Sure, sounds good

**Review by ellatrix — APPROVED** [review]
