### PR TITLE
Block Directory: Return inactive plugins in search results

### LINKED ISSUE #23570: Block Directory: Return deactivated plugins in search results.
**Describe the bug**
Inactive block directory blocks should return as installable in the search results. The block should be activated if the user decides to click `Add Block` again.

This functionality was removed in the transition to using the `WP_REST_Plugins_Controller` in https://github.com/WordPress/gutenberg/pull/22454.

This feature was initially introduce in https://github.com/WordPress/gutenberg/pull/22286.

**To reproduce**
1. Install a block from the directory (Boxer)
2. Disable plugin via `wp-admin/plugins.php`
3. Reload page
4. Search for the same block
5. Notice the result is not returned.

**Expected behavior**
See description.

**Editor version (please complete the following information):**
- WordPress version: current master

### PR DESCRIPTION
**Pull request by ryelle**
## Description
Fixes #23570 — This skips the check in the search results endpoint that filters out installed blocks, so that installed-but-deactivated blocks are returned. Blocks that are installed will contain an extra link property in the result, which we can use in the install flow to just activate the plugin.

This also changes the uninstallation flow to use the same link property, instead of a custom endpoint property.

## How has this been tested?
I updated the unit tests, and manually tested with a combination of locally installed block plugins.

From the original issue:

1. Install a block from the directory (Boxer)
2. Disable plugin via wp-admin/plugins.php
3. Reload page
4. Search for the same block
5. The result is should now be returned

## Types of changes
Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/block-directory/src/store/actions.js [hunk 1]
```diff
@@ -54,16 +55,35 @@ export function* installBlockType( block ) {
...
+		if ( url ) {
+			yield apiFetch( {
+				url,
+				data: {
+					status: 'active',
+				},
+				method: 'PUT',
+			} );
+		} else {
+			const response = yield apiFetch( {
```
Comment (TimothyBJacobs) [inline packages/block-directory/src/store/actions.js:71]: Not necessary, but we could also use the `wp:install-plugin` link as a base, and just add the `status: active` data.

File: packages/block-directory/src/store/utils/get-plugin-url.js [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+ */
+export default function getPluginUrl( block ) {
+	if ( ! block ) {
+		return false;
+	}
+	const link = block.links[ 'wp:plugin' ] || block.links.self;
+	if ( link && link.length ) {
+		return link[ 0 ].href;
+	}
+	return false;
```
Comment (StevenDufresne) [inline packages/block-directory/src/store/utils/get-plugin-url.js:16]: Not incredibly important but `@wordpress/url`'s `getPath` returns `undefined` (which we use in `controls.js`). 

I wonder if it makes sense to follow that convention.

**Review by StevenDufresne — APPROVED** [review]
Tested it locally. Works are expected. Good job!
