### PR TITLE
Writing flow: preserve block when merging into empty paragraph

### LINKED ISSUE #16436: Writing flow: hitting backspace causes block to lose heading when prior block is empty
**Describe the bug**

This is a small writing flow issue.

**To reproduce**

1. Create an empty paragraph
2. Press `Enter`
3. Create a heading with some text
4. Put the caret at the start of the heading
5. Press `Backspace`

**Expected behavior**

The block should be preserved if the previous block is empty.

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Fixes #16436.

## Why?

When merging a heading into an empty paragraph, the heading should be preserved and the paragraph removed.

### CODE REVIEW

File: packages/block-editor/src/components/rich-text/use-delete.js [hunk 1]
```diff
@@ -43,7 +43,7 @@ export function useDelete( props ) {
 				// an intentional user interaction distinguishing between Backspace and
 				// Delete to remove the empty field, but also to avoid merge & remove
 				// causing destruction of two fields (merge, then removed merged).
-				if ( onRemove && isEmpty( value ) && isReverse ) {
+				else if ( onRemove && isEmpty( value ) && isReverse ) {
```
Comment (jorgefilipecosta) [inline packages/block-editor/src/components/rich-text/use-delete.js:46]: With this change in practice, this condition `else if ( onRemove && isEmpty( value ) && isReverse ) {`is never executed right ? We pass an onMerge on the block list so `if ( onMerge ) {` will always be truth, if that's the case would it make sense to remove the condition?

**Review by jorgefilipecosta — APPROVED** [review]
The changes works well on the tests I did and the code looks good 👍

File: packages/block-editor/src/components/rich-text/use-delete.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-editor/src/components/rich-text/use-delete.js:46]: Not all blocks may pass an onMerge function to RichText, they may only pass onRemove.
