### PR TITLE
Core Data: Test entity undo reducer.

### LINKED ISSUE #17434: Increase Coverage of Undo/History E2E Tests
To catch regressions like the ones fixed in #17420 and #17259.

### PR DESCRIPTION
**Pull request by epiqueras**
Closes #17434

## Description

This PR adds unit tests for `core-data`'s new undo reducer.

It also fixes a minor edge case where we were updating a reference to the last edit action even if the new action only contained transient edits. This was causing us to skip/delete an undo level when explicitly marking the last changes as persistent.

## How has this been tested?

They are tests :smile:

## Checklist:

- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

File: packages/core-data/src/test/reducer.js [hunk 1]
```diff
@@ -99,6 +107,206 @@ describe( 'entities', () => {
...
+		} else if ( args.length ) {
+			action = createNextEditAction( ...args );
+		}
+		return deepFreeze( undo( undoState, action ) );
+	};
+	beforeEach( () => {
+		lastEdits = {};
+		undoState = undefined;
+		expectedUndoState = [];
+		expectedUndoState.offset = 0;
```
Comment (ellatrix) [inline packages/core-data/src/test/reducer.js]: This is interesting to see in a state, as normally the state should be serialisable. Could you comment on this in the reducer? Why can't it be nested?

File: packages/core-data/src/test/reducer.js [hunk 2]
```diff
@@ -99,6 +107,206 @@ describe( 'entities', () => {
...
+			},
+		};
+		lastEdits = { ...lastEdits, ...edits };
+		return action;
+	};
+	const createNextUndoState = ( ...args ) => {
+		let action = {};
+		if ( args[ 0 ] === 'isUndo' || args[ 0 ] === 'isRedo' ) {
+			// We need to "apply" the undo level here and build
+			// the action to move the offset.
```
Comment (ellatrix) [inline packages/core-data/src/test/reducer.js]: Why does the action need to be build based on the state? Isn't that something that can be done in the reducer?

File: packages/core-data/src/reducer.js [hunk 3]
```diff
@@ -314,7 +314,13 @@ export function undo( state = UNDO_INITIAL_STATE, action ) {
 				! isCreateUndoLevel && ( action.meta.isUndo || action.meta.isRedo );
 			if ( isCreateUndoLevel ) {
 				action = lastEditAction;
-			} else if ( ! isUndoOrRedo ) {
+			} else if (
+				! isUndoOrRedo &&
+				// Don't update the last edit cache if the new one only has transient edits.
+				// Transient edits don't create new levels so updating the cache would make
+				// us skip an edit later when creating levels explicitly.
+				Object.keys( action.edits ).some( ( key ) => ! action.transientEdits[ key ] )
```
Comment (ellatrix) [inline packages/core-data/src/reducer.js]: Is there an e2e test case that could fail without this change?

File: packages/core-data/src/test/reducer.js [hunk 4]
```diff
@@ -99,6 +107,206 @@ describe( 'entities', () => {
...
+		recordId: 'someRecordId',
+		edits,
+	} );
+	const createNextEditAction = ( edits, transientEdits = {} ) => {
+		let action = {
+			...createEditActionPart( edits ),
+			transientEdits,
+		};
+		action = {
+			type: 'EDIT_ENTITY_RECORD',
```
Comment (ellatrix) [inline packages/core-data/src/test/reducer.js]: I really liked how the previous history reduces could work with any state and actions. This one seems to handle `EDIT_ENTITY_RECORD`. Is there any way it could be more abstracted? Cc @aduth.

File: packages/core-data/src/test/reducer.js (hunk 2 above)
Comment (ellatrix) [reply packages/core-data/src/test/reducer.js]: Previously we had `UNDO` and `REDO` actions.

File: packages/core-data/src/test/reducer.js (hunk 1 above)
Comment (epiqueras) [reply packages/core-data/src/test/reducer.js]: It could be nested. I just followed from the previous iteration and I think I've seen other places where this is done.

I guess we should change it in another PR if we need to serialize it.

File: packages/core-data/src/test/reducer.js (hunk 2 above)
Comment (epiqueras) [reply packages/core-data/src/test/reducer.js]: Because the editor grabs the undo edit and applies it, the undo reducer just keeps track of the offset.

File: packages/core-data/src/reducer.js (hunk 3 above)
Comment (epiqueras) [reply packages/core-data/src/reducer.js]: No, it's not a flow that happens in the editor, but it could happen with other third party usage.

File: packages/core-data/src/test/reducer.js (hunk 4 above)
Comment (epiqueras) [reply packages/core-data/src/test/reducer.js]: What other actions does it need to handle for entities?

I don't think this is how this reducer will look like in the long term, specially after adding support for collaborative editing.

But, for now it gives us a lot of control over details that allow us to meet requirements for things like explicit levels and other nuances that the editor and block editor need. A more generalized abstraction could make that harder.

**Review by ellatrix — APPROVED** [review]
Thanks! It's great to have some tests :)

**Comment by epiqueras** [comment]
@ellatrix My change to the reducer needed a tweak. I would appreciate another look :smile:

**Comment by ellatrix** [comment]
In 3bcddbed4b4a4f4826e9c91eb58f7fcd7945ccc5, I see changed and added code, but no extra tests. Would it make sense to have tests for this part?

**Comment by epiqueras** [comment]
@ellatrix Yeah, but it fixed an e2e test that was failing, so it's already covered.

**Review by ellatrix — APPROVED** [review]

File: packages/core-data/src/test/reducer.js [hunk 5]
```diff
@@ -99,6 +107,206 @@ describe( 'entities', () => {
...
+		// even if undone.
+		undoState = createNextUndoState( { value: 3 } );
+		undoState = createNextUndoState( 'isUndo' );
+		undoState = createNextUndoState( 'isCreate' );
+		expectedUndoState.pop();
+		expectedUndoState.push( createEditActionPart( { value: 3 } ) );
+		expect( undoState ).toEqual( expectedUndoState );
+	} );
+
+	it( 'explicitly creates an undo level when undoing with pending transient edits', () => {
```
Comment (epiqueras) [inline packages/core-data/src/test/reducer.js]:
```suggestion
	it( 'explicitly creates an undo level when undoing while there are pending transient edits', () => {
```
