### PR TITLE
Chrome: Avoid creating empty terms

### LINKED ISSUE #2581: Add empty or existing category: error 500
To reproduce:
- open the "Add New Category" form in the sidebar
- submit testing all these 3 cases:
  - leave the new category field empty
  - enter only spaces
  - enter an already existing category
- observe your browser console
- POST ... `500 (Internal Server Error)`

As far as I zee, there is a response, for example:
`{"code":"empty_term_name","message":"A name is required for this term.","data":null}`
but maybe it's not handled correctly

Also, the UI doesn't give any feedback in both cases. At the very least, I'd consider to:
- don't allow user to submit an empty term name or made of only spaces
- handle the already existing term correctly: the UI should display a proper message and also send an audible message to the ARIA live region
-

### PR DESCRIPTION
**Pull request by youknowriad**
fixes #2581

This avoids triggering a network request to create an empty term.
I don't know if it's necessary but I also added a "required" attribute to the input field.

**Testing instructions**
 - Trying creating an empty category
 - No request should be triggered when submitting.

### CODE REVIEW

File: editor/sidebar/post-taxonomies/hierarchical-term-selector.js [hunk 1]
```diff
@@ -85,6 +85,9 @@ class HierarchicalTermSelector extends Component {
 	onAddTerm( event ) {
 		event.preventDefault();
 		const { formName, formParent } = this.state;
+		if ( formName === '' ) {
```
Comment (aduth) [inline editor/sidebar/post-taxonomies/hierarchical-term-selector.js]: I note similar errors of #2581 when term is nothing but whitespace. We should probably trim here before testing as empty.

File: editor/sidebar/post-taxonomies/hierarchical-term-selector.js [hunk 2]
```diff
@@ -221,6 +224,7 @@ class HierarchicalTermSelector extends Component {
 							placeholder={ newTermLabel }
 							value={ formName }
 							onChange={ this.onChangeFormName }
+							required
```
Comment (aduth) [inline editor/sidebar/post-taxonomies/hierarchical-term-selector.js]: On principle I'd be fine with the browser default behavior, but if we do decide to trim the input, we might want to consider how to convey this to the user, since the `required` browser default won't appear. Alternatively, we could prevent whitespace from being added to the `value` if no other non-whitespace characters in value.

**Review by aduth — DISMISSED** [review]

**Comment by afercia** [comment]
About the required attribute, no objections. Just noting there's an ongoing discussion in core about the best way to markup required fields. It's more for historical reasons since old browsers don't have built-in validation or support is inconsistent. In core, there's no standard pattern yet. See https://core.trac.wordpress.org/query?status=!closed&keywords=~required-fields

A different issue is some kind of visual indication that a field is required. There should be some indication. No consistency in core (or no indication at all) also in this case.

**Review by afercia — COMMENTED** [review]
see comment

**Comment by youknowriad** [comment]
As noted in the dev chat, it's ok to use `required` attribute for this. We should move forward here.

**Review by aduth — APPROVED** [review]
