### PR TITLE
Meta Boxes: Fix Dirty Detection in Safari

### LINKED ISSUE #3929: The editor has encountered an unexpected error
## Issue Overview

Gutenberg 1.9 is displaying a box with this error and 3 buttons when other plugins adding metaboxes to the edit screen are activated at the same time.

Disabling the other plugins resolve the issue and Gutenberg displays correctly.

## Steps to Reproduce (for bugs)

1. Activate Gutenberg
2. Activate another plugin that adds metaboxes to the edit screen (personal example: SEOPress)
3. Try to add a new post/page or edit an existing one
4. Error in console is `TypeError: e.entries is not a function. (In 'e.entries()', 'e.entries' is undefined)` for `/plugins/gutenberg/vendor/react-dom.min.cc6ec027.js` line 436

This was tested on Safari 11.0.2

## Expected Behavior
Gutenberg displaying and the metaboxes from the other plugins also.

## Current Behavior
Error visible in the screenshot below

## Screenshots / Video
https://imgur.com/Isr1iQi

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by youknowriad**
closes #3929

Dirty Detection of Meta Boxes forms was broken in Safari because it was relying on FormData `entries`API which is not available in all browsers yet. This PR uses `jQuery.serialize` as a cross-browser alternative.

**Testing instructions**

 - Install Gutenberg and Seo Press
 - Open Gutenberg
 - It should not break

### CODE REVIEW

File: editor/components/meta-boxes/meta-boxes-area/index.js [hunk 1]
```diff
@@ -89,9 +90,7 @@ class MetaBoxesArea extends Component {
 	}
 
 	getFormData() {
-		const data = new window.FormData( this.form );
-		const entries = Array.from( data.entries() );
-		return entries;
+		return jQuery( this.form ).serialize();
```
Comment (gziolo) [inline editor/components/meta-boxes/meta-boxes-area/index.js]: It returns a string in here after changes got applied.

`getFormData` is compared against `this.originalFormData` which is initialized as an empty array.
```
this.originalFormData = [];
```

Comment (youknowriad) [reply editor/components/meta-boxes/meta-boxes-area/index.js]: Good catch, changing the initial value :)

**Comment by gziolo** [comment]
We are polyfilling `fetch`, but apparently we don't do it for `FormData`. We use `FormData` also for media upload: https://github.com/WordPress/gutenberg/blob/9f05eef4ac31e1a35089ad090047bce99895528a/utils/mediaupload.js#L71. We should test if it works in Safari, too.

Is it possible to polyfil `FormData` instead?

**Comment by gziolo** [comment]
It looks like this polyfill would work: https://github.com/jimmywarting/FormData/blob/master/FormData.js.

**Comment by gziolo** [comment]
It looks like jQuery is loaded anyways in Gutenberg. It uses a different version than the one specified in `package.json`: `v1.12.4`. Should we use the same version?

**Comment by youknowriad** [comment]
> It looks like jQuery is loaded anyways in Gutenberg. It uses a different version than the one specified in package.json: v1.12.4. Should we use the same version?

This one is only for testing purpose, it's not even run :)

**Comment by youknowriad** [comment]
> Do we need to load all the code for meta boxes every time Gutenberg loads or is there case where we could skip it? 

It small enough IMO. I don't it's worth a separate script.

**Comment by gziolo** [comment]
Feel free to merge if you find someone to test it before I get to it 👍

**Review by gziolo — APPROVED** [review]
I can confirm it works in Safari with SEOPress plugin.
