### PR TITLE
Classic block: save content bug fix

### LINKED ISSUE #15577: Update button doesn't work reliably
**Describe the bug**
The update button doesn't reliably become enabled after making edits.

After making some edits to a Classic Block, the Update button is still disabled and I'm not able to save, and clicking on the button does nothing. I then make a few more edits and the Update button still remains disabled, but I'm able to click on it and save my changes.

It's not reliably detecting block changes, and also not changing state even after detecting changes.

Video: https://cl.ly/fcfbd14e2196

**To reproduce**
1. Add Classic Block
2. Save & Publish page
3. Edit Classic Block and see if Update button becomes available.

**Expected behavior**
As soon as I make a change to a block, no matter how small, the update button should become enabled and I should be able to click it to save my changes.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Browser: Firefox Quantum 66.0.5
 - Version: WP 5.2

### LINKED ISSUE #22935: Classic block content not saved until block is blurred
Content in a classic block is not saved until the block is blurred. This is different behaviour to other blocks, where content is saved immediately (and by 'saved' I mean the block content is saved outside of the block).

This could lead to a loss of content if a classic block is used and something happens where the window is closed before a blur event happens (i.e. the user closes the window, or Gutenberg crashes).

This also affects the `beforeunload` protection, which is not enabled until the blur occurs.

This was tested in Gutenberg 8.2.1 using MacOS Chrome.

## Steps to reproduce

- Create a new post
- Add a classic block
- Enter some content into the block, but don't click outside of it
image
- Check the ‘application’ tab in the developer console and note that the Session Storage autosave does not contain content from the block
image
- When the post is autosaved, note that the database contains a draft post with no content
image

- Click out of the block and note that the session storage now contains the content of the classic block, and this is eventually saved to the database.
- Click the 'save draft' to save the post
- Re-edit the classic block and make some changes. Note how the save status still shows 'saved', and doesn't change to 'save draft'
- Click out of the block and note how the save status now changes to 'save draft'.
- Re-edit the classic block, make some changes, and then close the window - no browser `beforeunload` warning is shown

Contrast this to a paragraph block:
- Create new post
- Type into paragraph block and don't click out of the block
- Note the session storage contains the block content
- Note the database contains the content
- Save as draft
- Reedit the paragraph and don't click out of the block
- Note the save status is showing 'save draft'

### PR DESCRIPTION
**Pull request by glendaviesnz**
## Description
Fixes: #22935 
Fixes: #15577

Uses the TinyMCE change events to push changed content back out to gutenberg instead of just relying on the onblur event

## How has this been tested?
Manually

## Screenshots 
Before:

onchange-before

After:

onchange-after

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by scruffian** [comment]
Looks good to me

File: packages/block-library/src/classic/edit.js [hunk 1]
```diff
@@ -112,6 +121,20 @@ export default class ClassicEdit extends Component {
 			bookmark = null;
 		} );
 
+		editor.on(
+			'Paste Change input Undo Redo',
+			debounce( () => {
```
Comment (ntsekouras) [inline packages/block-library/src/classic/edit.js:126]: Why are you using `debounce` here?

Comment (glendaviesnz) [reply packages/block-library/src/classic/edit.js:126]: We figured that this could be a busy call as someone is typing, making lots of changes, etc., and we don't need ervy minute change to go through this cycle. We didn't actually start to see any visible performance degradation until you got upwards of 50,000 words in a post, but didn't think it would hurt to add this in anyway.

Comment (ntsekouras) [reply packages/block-library/src/classic/edit.js:126]: > we didn't think it would hurt to add this in anyway

I believe that too and I also think that `250` is a fair debounce time.

It's great that you have made some tests checking performance! :+1:

**Review by ntsekouras — APPROVED** [review]
Good fix @glendaviesnz ! Thank you!

**Comment by glendaviesnz** [comment]
Thanks @ntsekouras, did you have any thoughts on this one https://github.com/WordPress/gutenberg/pull/23376?
