### PR TITLE
Fix class serialization of font-size and colors in dynamic blocks that use block supports

### LINKED ISSUE #35708: theme.json and Global Styles: Bug in generating the CSS custom properties (variables) if the slug contains numbers and letters (e.g.: h1 - h2 - h3 etc)
### Description

The generation of CSS custom properties (variables) if the slug contains numbers and letters (e.g.: h1 - h2 - h3 etc)) does not work properly for `core/site-title` and `core/post-title` (I do not tested all the blocks but for now I can see the issue in theese 2). The CSS variables generated in the `body` selector are ok but those variables or css class names applyed to post title and site title are not generated correctly.

### Step-by-step reproduction instructions

Let's take an example of theme.json:
```json
{
    "settings": {
        "typography": {
            "fontSizes": [
                {
                    "slug": "h1",
                    "size": "32px",
                    "name": "Used in H1 titles"
                }
            ]
        }
    }
}
```

We have `h1` as slug and the CSS variables generated inside the `body` selector we have the variable `--wp--preset--font-size--h-1` where the `h` and the `1` are separated by a dash, so this is the expected behavior because the regex works in this way.

Let say we also have h2 h3 h4 h5 h6 registered in theme.json preset now in the editor if you apply one of those styles (e.g. `h3`) from the drop down menu in the select box for font sizes to a block `[site|post]-title` you can see in the front-end of the page that instead of applying the correct class name `has-h-3-font-size` it has applyed instead the one without the dash separator: `has-h3-font-size`, in the editor it works as expected, the correct class name with the dash separator is applyed correctly but not in front-end

Further I also noticed that if I add a style in the theme.json under `styles` section and I change the style inside the Global Styles Editor for example to add an h2 font size to the `[site|post]-title` block the css generated is not what we can expect:

```css
// CSS generated by GS
.wp-block-post-title {
	color: var(--wp--preset--color--body-color);
	font-size: var(--wp--preset--font-size--h2); // without the dash separator
}
```

```css
// CSS from the theme.json
.wp-block-post-title {
	color: var(--wp--preset--color--body-color);
	font-size: var(--wp--preset--font-size--h-1); // with the dash separator
}
```

This is the snippet under the styles sections in the theme.json
```json
{
    "styles": {
        "blocks": {
            "core/post-title": {
                "typography": {
                    "fontSize": "var(--wp--preset--font-size--h-1)"
                }
            }
        }
    }
}
```

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WP 5.8.1, Gutenberg 11.7, Custom child theme and also TT1, PHP 7.4
Firefox
Win 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by oandregal**
Fixes https://github.com/WordPress/gutenberg/issues/35708

Converting the slug to a kebab-case format has been problematic in the past. In the client, we use lodash's `kebabCase`, which has some peculiarities. In the server, we don't have that, so we created `gutenberg_experimental_to_kebab_case` function to replicate the most common use cases. See https://github.com/WordPress/gutenberg/issues/32347 for details.

Apparently, when that was implemented the block supports didn't get updated. Hence, blocks that are rendered in the server may still generate an incorrect class. This PR fixes the font size class generation.

## How to test

- Use the empty theme and register this font size:
```json
{
    "settings": {
        "typography": {
            "fontSizes": [
                {
                    "slug": "h1",
                    "size": "32px",
                    "name": "Used in H1 titles"
                }
            ]
        }
    }
}
```
- Add a paragraph, a post title, and a site title in the block editor.
- Attach the font size to those blocks.

The expected result at this point is that, in the editor, they have a new class called `.has-h-1-font-size`.

- Publish the post and verify that, in the front end, they still have that class (previous to this PR it'd be rewritten to `.has-h1-font-size`, which is incorrect as per lodash's kebabCase function).

## Related

Font family preset is being fixed at https://github.com/WordPress/gutenberg/pull/31910

### CODE REVIEW

**Comment by oandregal** [comment]
Pushed a fix for font family at https://github.com/WordPress/gutenberg/commit/21e6ab1847aebe4265ab4e7a2b987feda2a94dc3

**Comment by oandregal** [comment]
Pushed a fix for colors as well. Also pushed tests for both typography and colors.

**Comment by ockham** [comment]
PHP Unit tests are failing 😕 

```
There was 1 failure:

1) WP_Block_Supports_Spacing_Test::test_spacing_gap_block_support_renders_block_inline_style
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'<div style="--wp--style--block-gap: 3em" class="wp-block-test-block">Test</div>'
+'<div class="wp-block-test-block">Test</div>'

/var/www/html/wp-content/plugins/gutenberg/phpunit/block-supports/spacing-test.php:52
```

**Comment by ockham** [comment]
Sorry for the naive question, but how do I register a font size? Copy-paste the snippet to the theme's `theme.json`? 😅

**Comment by ockham** [comment]
> Sorry for the naive question, but how do I register a font size? Copy-paste the snippet to the theme's `theme.json`? 😅

It's `experimental-theme.json` for Emptytheme, but regardless, that didn't work. (Is that expected to work?)

Adding to Gutenberg's own `lib/theme.json` also didn't work 😕  (I rebuilt and re-started wp-env.)

```diff
diff --git a/lib/theme.json b/lib/theme.json
index f32734b6ef..0dd7f4a0e5 100644
--- a/lib/theme.json
+++ b/lib/theme.json
@@ -185,6 +185,11 @@
                        "customTextDecorations": true,
                        "customLetterSpacing": true,
                        "fontSizes": [
+                               {
+                                       "slug": "h1",
+                                       "size": "32px",
+                                       "name": "Used in H1 titles"
+                               },
                                {
                                        "name": "Small",
                                        "slug": "small",
```

image

**Comment by ockham** [comment]
Ah-ha, it seems like this is only available in the Site Editor!

image

That doesn't seem to apply at block level though 🤔  Changing it doesn't seem to do much at all, actually.

Oh well 😅  Sorry I cannot be of more help for now, but I guess I need further instructions 😅

**Comment by oandregal** [comment]
> It's experimental-theme.json for Emptytheme, but regardless, that didn't work. (Is that expected to work?)

Do you perhaps need to update the theme-experiments repo to the latest? We no longer support `experimental-theme.json`, only `theme.json`. The empty theme has been updated a few moons ago. What is probably happening in your setup is that, because the theme has the wrong file, the theme settings are ignored and, instead, the core defaults for font size are shown.

I'm looking now at the failing test.

**Comment by oandregal** [comment]
Pushed a change to fix the test.

**Comment by ockham** [comment]
> > It's experimental-theme.json for Emptytheme, but regardless, that didn't work. (Is that expected to work?)
> 
> Do you perhaps need to update the theme-experiments repo to the latest? We no longer support `experimental-theme.json`, only `theme.json`. The empty theme has been updated a few moons ago. What is probably happening in your setup is that, because the theme has the wrong file, the theme settings are ignored and, instead, the core defaults for font size are shown.

Ah, that seems to have done the trick 🤦‍♂️  I thought wp-env would take care of that for me, but turns out I had to manually `git checkout trunk && git pull` in `~/.wp-env/[sha]/theme-experiments`. Thanks André!

image

File: phpunit/block-supports/colors-test.php [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+/**
+ * Test the typography block supports.
+ *
+ * @package Gutenberg
+ */
+
+class WP_Block_Supports_Colors_Test extends WP_UnitTestCase {
+
+	function test_color_slugs_with_numbers_are_kebab_cased_properly() {
+		register_block_type(
```
Comment (ockham) [inline phpunit/block-supports/colors-test.php:12]: How about we [`unregister_block_type()`](https://developer.wordpress.org/reference/functions/unregister_block_type/) after we're done? That might help avoid future test block name clashes like the one that caused the PHP unit test error (IIUC)

File: phpunit/block-supports/typography-test.php [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+/**
+ * Test the typography block supports.
+ *
+ * @package Gutenberg
+ */
+
+class WP_Block_Supports_Typography_Test extends WP_UnitTestCase {
+
+	function test_font_size_slug_with_numbers_is_kebab_cased_properly() {
+		register_block_type(
```
Comment (ockham) [inline phpunit/block-supports/typography-test.php:12]: Same as https://github.com/WordPress/gutenberg/pull/35751/files#r732731893 😄

**Review by ockham — APPROVED** [review]
Thanks André, this is working great now 👍

Love the unit test coverage. I only had two minor notes -- feel free to address or ignore 😄

File: phpunit/block-supports/colors-test.php (hunk 1 above)
Comment (oandregal) [reply phpunit/block-supports/colors-test.php:12]: That's a good call https://github.com/WordPress/gutenberg/pull/35751/commits/922882a87ef537e62231333e97f940804a9bde00

**Comment by oandregal** [comment]
I see there's the React Native e2e test failure. I've seen this one in another of my PRs and the recommendation was to re-run the test until it passed. I want to use parts of this PR (test) on https://github.com/WordPress/gutenberg/pull/31910 so I'm going to go ahead and merge this.
