### PR TITLE
[Site Editor]: Register block editor shortcuts

### LINKED ISSUE #33948: Some writing flow / keyboard shortcuts doesn't work in the site editor
In the site editor, I'm not able to use several writing flow interactions from the post editor.

 - The first one is "select all" shortcut, hitting "ctrl + a" twice doesn't select all the blocks
 - The other one I noticed is the "delete" or "backspace" to remove selected blocks.

### PR DESCRIPTION
**Pull request by ntsekouras**
Fixes: https://github.com/WordPress/gutenberg/issues/33948

It seems we never registered the block editor shortcuts in site editor and this PR does just that.

## Testing instructions
1. In site editor try the writing flow shortcuts and make sure they work as expected

## Notes
Examples can be found in block settings in a block's toolbar:

Screenshot 2021-12-22 at 10 10 00 AM

The full list of the block editor shortcuts[ is here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/keyboard-shortcuts/index.js) in code.

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]
Thanks, Nik! The fix works as expected.

File: packages/edit-site/src/components/block-editor/index.js [hunk 1]
```diff
@@ -108,8 +109,8 @@ export default function BlockEditor( { setIsInserterOpen } ) {
 					}
 				} }
 			>
+				<BlockEditorKeyboardShortcuts.Register />
```
Comment (Mamaduka) [inline packages/edit-site/src/components/block-editor/index.js:112]: Should we register this alongside other shortcuts, to match other editors? https://github.com/WordPress/gutenberg/blob/b6400f7d3ed330976ee074b252554c2ae7cea738/packages/edit-site/src/components/editor/index.js#L185

Comment (ntsekouras) [reply packages/edit-site/src/components/block-editor/index.js:112]: IMO is better to have them here, in the same place where we add the `block-editor` in site editor, but in general 🤷 😄

Comment (Mamaduka) [reply packages/edit-site/src/components/block-editor/index.js:112]: No strong opinion on this 😄  Feel free to merge.

**Review by ellatrix — APPROVED** [review]
Seems fine to me.
