### PR TITLE
Storybook: Components: Apply style changes

### LINKED ISSUE #18675: Storybook: Component style changes don't apply
**Describe the bug**
Hi there!

This isn't a bug... more like a very nice to have enhancement :).

At the moment, any `.scss` changes that happen for `@wordpress/components` don't reflect in Storybook. The `import` of the style files reference `.css`, which are built before Storybook launches.

To resolve this, we can `import` the `.scss` files instead. Storybook's Webpack has already been set up with `.scss` support, which is how we got the Playground working 🙌 

**To reproduce**
1. Run `npm run storybook:dev`
2. Make an update to a `.scss` file in `packages/components`
3. No changes

**Expected behavior**
For style changes to update

### PR DESCRIPTION
**Pull request by ItsJonQ**
## Description
This update fixes the Storybook x WP/Components workflow to enable for style changes made in `.scss` files to be reflected within Storybook. Previously, this was not supported due to the importing of the pre-build `.css`.

Storybook's webpack config was also enhanced with `postcss-loader`, allowing for PostCSS functions to execute on run time. This is necessary for functions like `color()` to work correctly.

## How has this been tested?
Storybook

## Screenshots

Screen Capture on 2019-11-21 at 14-32-55

## Types of changes

Some things to consider would be how this may impact the build Storybook to be uploaded and served to Github pages. I don't think it would have too much of a negative impact.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

Resolves: https://github.com/WordPress/gutenberg/issues/18675

### CODE REVIEW

File: storybook/stories/playground/index.js [hunk 1]
```diff
@@ -21,8 +21,6 @@ import { registerCoreBlocks } from '@wordpress/block-library';
 import '@wordpress/format-library';
 
 /* eslint-disable no-restricted-syntax */
-import '@wordpress/components/build-style/style.css';
-import '@wordpress/block-editor/build-style/style.css';
 import '@wordpress/block-library/build-style/style.css';
```
Comment (ItsJonQ) [inline storybook/stories/playground/index.js]: If this workflow is desired, we could apply the same technique to the editor/library styles as well.

Comment (gziolo) [reply storybook/stories/playground/index.js]: I think it's perfectly fine to use sources everywhere. We do it for stories where we import JS source files directly, so we can follow the same approach for styles.

**Comment by ItsJonQ** [comment]
Screen Shot 2019-12-02 at 10 33 23 AM

@gziolo All of the styles in the Playground should be `.scss` now!

cc'ing @epiqueras 😊

File: storybook/style.scss [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+// used within @wordpress/*/src/*.scss
+@import "~@wordpress/base-styles/animations";
+@import "~@wordpress/base-styles/breakpoints";
+@import "~@wordpress/base-styles/colors";
+@import "~@wordpress/base-styles/mixins";
+@import "~@wordpress/base-styles/variables";
+@import "~@wordpress/base-styles/z-index";
+
+// @wordpress package styles
+@import "../packages/components/src/style.scss";
```
Comment (gziolo) [inline storybook/style.scss]: I'm wondering if you could reference them the same way like base styles, but it doesn't matter after all.

**Review by gziolo — APPROVED** [review]
Nice one. Thank you for bringing this in.
