### PR TITLE
Compose: Implement useCopyToClipboard and useCopyOnClick with native clipboard API

### LINKED ISSUE #37700: Use native clipboard API instead of a 3rd party dependency
## What problem does this address?
The hook `useCopyToClipboard` uses a 3rd party dependency `clipboard`. We could improve bundle size by using the native clipboard API.

I wrote this PR in an external repo which similarly replaces `clipboard` with the native clipboard API: https://github.com/Automattic/wp-calypso/pull/59266

## What is your proposed solution?

Here's the current code:
https://github.com/WordPress/gutenberg/blob/d754759c45a4f882b01a78e1a2064b77e9d87370/packages/compose/src/hooks/use-copy-to-clipboard/index.js#L44-L68

One could simply use `window.navigator.clipboard.writeText( copyText ).then( ... )` instead of `new Clipboard( ... )`. The only thing I'm unsure about is how to handle the selection clearing and focusing that the existing component uses.

### LINKED ISSUE #65874: LinkControl crashing block in Pattern Editor
### Description

The `LinkControl` component from the `@wordpress/block-editor` package does not work as expected when used inside the Pattern Editor. The block crashes with some JS errors in the console:
Image

Here's the error with `SCRIPT_DEBUG` set to `true`
Image
 

### Step-by-step reproduction instructions

Steps to Reproduce
1. Create a Pattern with a block that contains a `LinkControl` Image

2. Open Pattern Editor
3. Open the Pattern with the LinkControlImage

All I know is that the error is caused by the `useCopyToClipboard` hook inside used by `LinkPreview` component internally in `LinkControl`. 
I tried installing the [Gutenberg Plugin](https://wordpress.org/plugins/gutenberg/) 19.3 but it still crashes. 

### Screenshots, screen recording, code snippet

I created a simple test repo with WP and a theme with block that contains a LinkControl to reproduce the issue: [repo](https://github.com/StYankov/gutenberg-linkcontrol/tree/master) [block edit.js](https://github.com/StYankov/gutenberg-linkcontrol/blob/master/wp-content/themes/block-theme/src/blocks/hello-world/edit.js)

### Environment info

WordPress Version: 6.6.2
Browser: Chrome 127

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

UPDATE:
The issue appears after WP 6.5. Before that the example block doesn't crash in the Pattern Editor.
Update:
Added a comment describing the problem and a possible solution

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #65874
Closes #37700

## What? Why? 

The `useCopyToClipboard` hook uses `clipboard.js` internally, but that library doesn't support iframe documents and hasn't been maintained for years. It should be possible to implement the same thing with native browser APIs by now.

## Testing Instructions

I've created two blocks that implement the `useCopyToClipboard` or `useCopyOnClick` hooks. Insert them into the editor and verify that they work correctly.

```javascript
// useCopyToClipboard( recommended );

wp.blocks.registerBlockType( 'test/use-copy-to-clipboard', {
	apiVersion: 3,
	title: 'Test Block (useCopyToClipboard version)',
	edit: function Edit() {
		const state = wp.element.useState( false );
		const hasCopied = state[ 0 ];
		const setHasCopied = state[ 1 ];
		const ref = wp.compose.useCopyToClipboard(
			'Text to be copied via useCopyToClipboard.',
			function onSuccess() {
				setHasCopied( true );
			}
		);
		return wp.element.createElement(
			'div',
			wp.blockEditor.useBlockProps(),
			wp.element.createElement(
				wp.components.Button,
				{
					ref,
					variant: 'primary',
				},
				hasCopied ? 'Copied!' : 'Copy via useCopyToClipboard'
			)
		);
	},
} );

// useCopyOnClick( Deprecated );

wp.blocks.registerBlockType( 'my-plugin/test-block', {
	apiVersion: 3,
	title: 'Test Block (useCopyOnClick version)',
	edit: function Edit() {
		const buttonRef = wp.element.useRef( null );
		const hasCopied = wp.compose.useCopyOnClick(
			buttonRef,
			'Text to be copied via useCopyOnClick.'
		);
		return wp.element.createElement(
			'div',
			wp.blockEditor.useBlockProps(),
			wp.element.createElement(
				wp.components.Button,
				{
					ref: buttonRef,
					variant: 'primary',
				},
				hasCopied ? 'Copied!' : 'Copy Text via useCopyOnClick'
			)
		);
	},
} );

```

Verify that the various copy buttons in the editor continue to work as before. For example:

- Permalink copy button
- Color value copy button in a color picker

### Testing on non-secure site

Similar efforts have been abandoned in the past because the copy didn't work on non-secure sites, i.e. sites running over HTTP. https://github.com/WordPress/gutenberg/pull/37810

This PR includes a fallback for HTTP sites, so be sure to check it out to see if it works.

Perhaps the easiest way to build an HTTP site is with [Studio](https://developer.wordpress.com/studio/). Launch your site with the "Enable HTTPS" check disabled:

image

Open your browser console and run the following code. It should return `false` and `undefined`.

```
window.isSecureContext
window.navigator.clipboard
```

image

We'll verify that the copy works correctly even in this environment.

### CODE REVIEW

**Comment by Mamaduka** [comment]
I think this was tried and abandoned a couple of times. Here's the latest attempt I could find - #37810.

**Comment by t-hamano** [comment]
> I think this was tried and abandoned a couple of times. Here's the latest attempt I could find - https://github.com/WordPress/gutenberg/pull/37810.

I didn't know that 😅 This PR has [a fallback code for HTTP](https://github.com/WordPress/gutenberg/pull/75723/changes#diff-330100d0f5237d7839ac7b1e9b8d1e4ea0c9ac1d051b969acca35f4bc7ec5d23R33-R43), but I would like to test this PR to see if it actually works in various environments.

**Comment by t-hamano** [comment]
This PR should technically work in an HTTP environment, but to verify this, I'll try to set up an HTTP environment somehow. [This temporary log](https://github.com/WordPress/gutenberg/pull/75723/changes#diff-330100d0f5237d7839ac7b1e9b8d1e4ea0c9ac1d051b969acca35f4bc7ec5d23R29-R38) should be logged, and it should work correctly.

**Comment by t-hamano** [comment]
Ok, so this PR seems to work on non-secure sites too. See the [Testing on non-secure site](https://github.com/WordPress/gutenberg/pull/75723#:~:text=Testing%20on%20non%2Dsecure%20site) section.

cc @ciampo

File: packages/compose/src/hooks/use-copy-to-clipboard/index.js [hunk 1]
```diff
@@ -13,6 +8,56 @@ import { useRef, useLayoutEffect } from '@wordpress/element';
  */
 import useRefEffect from '../use-ref-effect';
 
+/**
+ * Copies text to the clipboard using the Clipboard API when available,
+ * with a fallback for non-secure contexts (e.g. HTTP) and older browsers.
+ *
+ * @param {string}       text    The text to copy.
+ * @param {Element|null} trigger The element that triggered the copy. Required for
```
Comment (ciampo) [inline packages/compose/src/hooks/use-copy-to-clipboard/index.js]: Looks like the description for `trigger` was truncated

File: packages/compose/src/hooks/use-copy-to-clipboard/index.js [hunk 2]
```diff
@@ -13,6 +8,56 @@ import { useRef, useLayoutEffect } from '@wordpress/element';
...
+ * @return {Promise<boolean>} Resolves to true if successful, false otherwise.
+ */
+export async function copyToClipboard( text, trigger ) {
+	if ( ! text || ! trigger ) {
+		return false;
+	}
```
Comment (ciampo) [inline packages/compose/src/hooks/use-copy-to-clipboard/index.js]: This is potentially a small behavioural change compared to the previous code: if the text is an empty string the new code returns `false` immediately, which means that the `onSuccess` callback is not called.

Previously, it looks like `onSuccess` would be called with an empty string.

We should either document this intentional behaviour, or change the code to allow `text` to be `null` and/or `undefined`, and update the check to allow for empty strings.

File: packages/compose/src/hooks/use-copy-on-click/index.ts [hunk 3]
```diff
@@ -28,48 +28,67 @@ export default function useCopyOnClick( ref, text, timeout = 4000 ) {
...
-				setHasCopied( true );
-				clearTimeout( timeoutId );
-				timeoutId = setTimeout( () => setHasCopied( false ), timeout );
+		const handleClick = ( /** @type {Event} */ event ) => {
+			const trigger = /** @type {Element} */ ( event.currentTarget );
+			if ( ! trigger ) {
+				return;
 			}
-		} );
+			copyToClipboard(
```
Comment (ciampo) [inline packages/compose/src/hooks/use-copy-on-click/index.ts]: Non -blocking.

Since `copyToClipboard` returns a `Promise`, if the component unmounts between the function call and the promise resolving (which is _highly unlikely_, but possible), the success callback will fire and the `setHasCopied(true)` statement will be called on an unmounted component, and the `setTimeout` will also fire. React probably won't complain, but it's still something that we could avoid.
The cleanup function only clears `timeoutId`, but only the value from the last render. It won't clear a `timeoutId` set from a promised that resolved late after unmounting.


One potential way to fix this would be to introduce an `isActive`  flag that is `true` at the top of the `useEffect`, set it to `false` in the effect cleanup function, and add an early return in the promise `.then()` callback if `isActive` is `false`.

File: packages/compose/src/hooks/use-copy-to-clipboard/index.ts [hunk 4]
```diff
@@ -37,33 +82,25 @@ function useUpdatedRef( value ) {
...
 			}
-		} );
-
+		};
+		node.addEventListener( 'click', handleClick );
 		return () => {
-			clipboard.destroy();
+			node.removeEventListener( 'click', handleClick );
 		};
 	}, [] );
```
Comment (ciampo) [inline packages/compose/src/hooks/use-copy-to-clipboard/index.ts:119]: The same `isActive` pattern can be also applied to the `useRefEffect` hook here, although the risk of out-of-sync promise updates is even lower, since the callbacks are refs (and not state setters)

File: packages/compose/src/hooks/use-copy-on-click/index.ts [hunk 5]
```diff
@@ -28,48 +28,67 @@ export default function useCopyOnClick( ref, text, timeout = 4000 ) {
...
-		clipboardRef.current.on( 'success', ( { clearSelection, trigger } ) => {
-			// Clearing selection will move focus back to the triggering button,
-			// ensuring that it is not reset to the body, and further that it is
-			// kept within the rendered node.
-			clearSelection();
+		let targets;
+		if ( typeof ref.current === 'string' ) {
+			targets =
+				typeof document !== 'undefined'
+					? Array.from( document.querySelectorAll( ref.current ) )
```
Comment (ciampo) [inline packages/compose/src/hooks/use-copy-on-click/index.ts:48]: It looks like using `document` matches previous behaviour, although I wonder if we should consider switching to `ownerDocument` ?

Probably not super important since the hook is deprecated.

**Review by ciampo — COMMENTED** [review]
Thank you for the ping!

Apart from the comments that I left, I have two additional suggestions:

- I still it would be valuable to add unit tests to test the branching logic (secure vs. fallback, guard clauses, error handling) and the hook integration (click listeners, state management, timeouts, cleanup). Some aspects will still require e2e tests (actual clipboard behaviour, HTTP vs HTTPS, real iframe scenarios, cross-browser quirks re. `execCommand`), but unit tests IMO will still bring value.
- should we write the new version in TypeScript?

**Comment by t-hamano** [comment]
@ciampo Thanks for the feedback! I'll try to convert it to Typescript, add tests, and address your feedback.

File: packages/compose/src/hooks/use-copy-to-clipboard/index.js (hunk 1 above)
Comment (t-hamano) [reply packages/compose/src/hooks/use-copy-to-clipboard/index.js]: Removed orphaned text.

File: packages/compose/src/hooks/use-copy-to-clipboard/index.js (hunk 2 above)
Comment (t-hamano) [reply packages/compose/src/hooks/use-copy-to-clipboard/index.js]: I think copying empty text should be just as successful as before. Addressed in 5bc2c900590a54df695034e14353a6474277558b

File: packages/compose/src/hooks/use-copy-on-click/index.ts (hunk 3 above)
Comment (t-hamano) [reply packages/compose/src/hooks/use-copy-on-click/index.ts]: Addressed in 582bc5f89418474798a7a7e307f46f07f09c71f0

File: packages/compose/src/hooks/use-copy-on-click/index.ts (hunk 5 above)
Comment (t-hamano) [reply packages/compose/src/hooks/use-copy-on-click/index.ts:48]: This was a bit of a struggle, but I'm leaning towards keeping the previous behavior, as deriving the ownerDocument is a bit tricky and could change behavior.

Comment (t-hamano) [reply packages/compose/src/hooks/use-copy-on-click/index.ts:48]: Addressed in 39fc7a482ad95ad22eed27f5dc1dd0b24bee78b7

**Comment by t-hamano** [comment]
I think I've addressed all the feedback.

- Add unit tests for `useCopyToClipboard` and `useCopyOnClick`
- add e2e test to make sure `useCopyToClipboard` works in the iframe editor

File: packages/compose/src/hooks/use-copy-to-clipboard/index.ts [hunk 6]
```diff
@@ -0,0 +1,119 @@
...
+
+/**
+ * Copies text to the clipboard using the Clipboard API when available,
+ * with a fallback for non-secure contexts (e.g. HTTP) and older browsers.
+ *
+ * @param text    The text to copy.
+ * @param trigger The element that triggered the copy.
+ * @return Resolves to true if successful, false otherwise.
+ */
+export async function copyToClipboard(
```
Comment (ciampo) [inline packages/compose/src/hooks/use-copy-to-clipboard/index.ts:20]: Non blocking nit: there aren't currently any tests for `copyToClipboard`, `clearSelection` and in general the fallback path for when the clipboard API is not available. Adding those tests should be possible by deleting `navigator.clipboard` (or mocking it to `undefined`).

Can be done in a follow-up PR

File: test/e2e/specs/editor/various/clipboard.spec.js [hunk 7]
```diff
@@ -0,0 +1,69 @@
...
+			'clipboard-read',
+			'clipboard-write',
+		] );
+
+		await editor.insertBlock( { name: 'test/copy-button-block' } );
+
+		const copyButtonBlock = editor.canvas.getByRole( 'document', {
+			name: 'Block: Copy Button Block',
+		} );
+		await copyButtonBlock.click();
```
Comment (ciampo) [inline test/e2e/specs/editor/various/clipboard.spec.js]: Nit: This click works correctly because the button is 100% of the width, but ideally we should query for the button itself — maybe something like

```js
const copyButton = editor.canvas.getByRole( 'button', { name: 'Copy' } );
await copyButton.click();
```

?

File: test/e2e/specs/editor/various/clipboard.spec.js [hunk 8]
```diff
@@ -0,0 +1,69 @@
+/**
+ * WordPress dependencies
+ */
+const { test, expect } = require( '@wordpress/e2e-test-utils-playwright' );
+
+test.describe( 'Clipboard (useCopyToClipboard)', () => {
+	test.beforeEach( async ( { admin, page } ) => {
+		await admin.createNewPost();
```
Comment (ciampo) [inline test/e2e/specs/editor/various/clipboard.spec.js:8]: This should validate `iframe` usage too, right? 🎉

File: packages/compose/src/hooks/use-copy-on-click/test/index.tsx [hunk 9]
```diff
@@ -0,0 +1,132 @@
...
+		await user.click( screen.getByRole( 'button' ) );
+
+		await act( async () => {
+			await new Promise( ( resolve ) => setTimeout( resolve, 0 ) );
+		} );
+
+		expect( screen.getByRole( 'button' ) ).toHaveTextContent( 'Copy' );
+	} );
+
+	it( 'should not update hasCopied after unmount', async () => {
```
Comment (ciampo) [inline packages/compose/src/hooks/use-copy-on-click/test/index.tsx:123]: Non-blocking nit:

The current test asserts that `navigator.clipboard.writeText` was called, but doesn't directly verify that internally `setHasCopied(true)` was *not* triggered after unmount — which is what the `isActive` guard is protecting against.

Since `useCopyOnClick` doesn't expose an `onSuccess` callback (unlike `useCopyToClipboard`), we can instead track component renders via a spy. If the `isActive` guard works, the promise resolving after unmount will not call `setHasCopied(true)`, so no re-render will occur.

<details>
<summary>Suggested diff</summary>

```diff
 	it( 'should not update hasCopied after unmount', async () => {
+		const renderSpy = jest.fn();
+
+		const SpyComponent = ( { text }: { text: string } ) => {
+			const ref = useRef< HTMLButtonElement >( null );
+			const hasCopied = useCopyOnClick( ref, text );
+			renderSpy( hasCopied );
+			return (
+				<button ref={ ref } type="button">
+					{ hasCopied ? 'Copied!' : 'Copy' }
+				</button>
+			);
+		};
+
 		let resolvePromise: () => void;
 		const delayedPromise = new Promise< void >( ( resolve ) => {
 			resolvePromise = resolve;
 		} );
 		jest.spyOn( navigator.clipboard, 'writeText' ).mockReturnValue(
 			delayedPromise as Promise< void >
 		);
 
 		const user = userEvent.setup();
-		const { unmount } = render( <TestComponent text="test" /> );
+		const { unmount } = render( <SpyComponent text="test" /> );
+
+		expect( renderSpy ).toHaveBeenLastCalledWith( false );
+		const renderCountBeforeUnmount = renderSpy.mock.calls.length;
 
 		await user.click( screen.getByRole( 'button' ) );
 		unmount();
 
 		await act( async () => {
 			resolvePromise();
 			await new Promise( ( resolve ) => setTimeout( resolve, 0 ) );
 		} );
 
-		// No state update after unmount — no throw, and we've resolved after unmount
-		expect( navigator.clipboard.writeText ).toHaveBeenCalled();
+		// No additional renders after unmount — setHasCopied(true) was not called.
+		expect( renderSpy ).toHaveBeenCalledTimes( renderCountBeforeUnmount );
 	} );
```

</details>

This way, the test directly verifies the behavior the `isActive` flag is protecting against: no state update (and therefore no re-render) after unmount.

**Review by ciampo — APPROVED** [review]
LGTM, testing well as per instructions 🚀 

Left some more comments, but none are blocking. Feel free to address them in this PR, or in a follow-up.

Thank you for working on this 🙏

File: packages/compose/src/hooks/use-copy-on-click/test/index.tsx [hunk 10]
```diff
@@ -0,0 +1,132 @@
...
+ * WordPress dependencies
+ */
+import { useRef } from '@wordpress/element';
+
+/**
+ * Internal dependencies
+ */
+import useCopyOnClick from '../';
+
+jest.mock( '@wordpress/deprecated', () => () => {} );
```
Comment (ciampo) [inline packages/compose/src/hooks/use-copy-on-click/test/index.tsx]: Should we actually check that the hook is marked as deprecated in the tests?

Comment (t-hamano) [reply packages/compose/src/hooks/use-copy-on-click/test/index.tsx]: Addressed in 46fcf3dcc9ec27e887eebff43ec341c07f407626

File: packages/compose/src/hooks/use-copy-on-click/test/index.tsx (hunk 9 above)
Comment (t-hamano) [reply packages/compose/src/hooks/use-copy-on-click/test/index.tsx:123]: Addressed in 92f6684348979fea1250c5fee3ea399667bdd4f4

File: test/e2e/specs/editor/various/clipboard.spec.js (hunk 8 above)
Comment (t-hamano) [reply test/e2e/specs/editor/various/clipboard.spec.js:8]: Yes 👍

File: test/e2e/specs/editor/various/clipboard.spec.js (hunk 7 above)
Comment (t-hamano) [reply test/e2e/specs/editor/various/clipboard.spec.js]: Addressed in 64dc678448e957e2a246acb2add232c891a35422

File: packages/compose/src/hooks/use-copy-to-clipboard/index.ts (hunk 6 above)
Comment (t-hamano) [reply packages/compose/src/hooks/use-copy-to-clipboard/index.ts:20]: Addressed in a7159b768086fdf62eec2528b7594d3983365dee

I've added the following two tests, but is there anything else we should test?

- `copyToClipboard > should use execCommand fallback when clipboard API is not available`
- `clearSelection > should focus the trigger element`

Comment (ciampo) [reply packages/compose/src/hooks/use-copy-to-clipboard/index.ts:20]: Very small nit, but maybe we could also check that `getSelection()?.removeAllRanges()` is invoked in the `clearSelection` tests?

```tsx
it( 'should clear the selection', () => {
    const trigger = document.createElement( 'button' );
    document.body.appendChild( trigger );
    const removeAllRangesMock = jest.fn();
    jest.spyOn( window, 'getSelection' ).mockReturnValue( {
        removeAllRanges: removeAllRangesMock,
    } as unknown as Selection );

    clearSelection( trigger );

    expect( removeAllRangesMock ).toHaveBeenCalledTimes( 1 );

    document.body.removeChild( trigger );
});
```

File: packages/compose/src/hooks/use-copy-on-click/index.ts [hunk 11]
```diff
@@ -0,0 +1,102 @@
...
+
+		const handleClick = ( event: Event ) => {
+			const trigger = event.currentTarget as Element;
+			if ( ! trigger ) {
+				return;
+			}
+			copyToClipboard(
+				typeof text === 'function' ? text() : text || '',
+				trigger
+			).then( ( success ) => {
```
Comment (ciampo) [inline packages/compose/src/hooks/use-copy-on-click/index.ts]: Also super nitty, but, for consistency, we could use `async`/`await` instad of `.then()`, as we already do in  `useCopyToClipboard`

File: packages/compose/src/hooks/use-copy-to-clipboard/index.ts [hunk 12]
```diff
@@ -0,0 +1,119 @@
...
+		if ( defaultView?.navigator?.clipboard?.writeText ) {
+			await defaultView.navigator.clipboard.writeText( text );
+			return true;
+		}
+		// Fallback for non-secure contexts (HTTP) and older browsers.
+		const textarea = ownerDocument.createElement( 'textarea' );
+		textarea.value = text;
+		textarea.setAttribute( 'readonly', '' );
+		textarea.style.position = 'absolute';
+		textarea.style.left = '-9999px';
```
Comment (ciampo) [inline packages/compose/src/hooks/use-copy-to-clipboard/index.ts]: If the document has horizontal scrolling behaviour, `textarea.select()` _could_ cause a scroll jump in some browsers. A more robust approach could be to


```suggestion
		textarea.style.position = 'fixed';
		textarea.style.left = '-9999px';
		textarea.style.top = '-9999px';
```

File: packages/compose/src/hooks/use-copy-on-click/index.ts (hunk 11 above)
Comment (t-hamano) [reply packages/compose/src/hooks/use-copy-on-click/index.ts]: Addressed in 5bdf1083eb54167626e5695827fb24c86a46ac43

**Comment by TobiasBg** [comment]
Hi @t-hamano,

Somehow this broke the success callback for `useCopyToClipboard` for me:

I have
```js
const copyButtonRef = useCopyToClipboard( 'my text', () => {
	console.log( 'Text copied to clipboard.' );
} );
```
and use that in a DropdownMenu button
```jsx
<MenuItem
	ref={ copyButtonRef }
	icon={ copy }
	onClick={ () => closeMenu() }
>
	{ __( 'Copy' ) }
</MenuItem>
```
Before this merged PR, the `console.log` was printed (I'm actually showing a success notice in a Snackbar), but with this merged PR, this is no longer called.

Any pointers on what I might need to adjust? Thanks!

**Comment by t-hamano** [comment]
@TobiasBg Thanks for the report. I've identified the root cause, and PR #78387 should resolve the issue.

**Comment by TobiasBg** [comment]
Just saw that, @t-hamano! Looks good, thanks for your quick reaction here :-)
