### PR TITLE
Fix unit control not escaping units

### LINKED ISSUE #52210: Unit Control crashes with certain units
### Description

The `<UnitControl>` component does not escape the units used to build the `firstCharacters` regular expression, see https://github.com/WordPress/gutenberg/blob/9a6958e6a3e69ecda18b8deb4e1b3cec352e30a0/packages/components/src/unit-control/index.tsx#L82

This causes the component to crash with RegExp syntax errors like `Nothing to repeat` when units are used that contain regex control characters.

There is a [`escapeRegExp`](https://github.com/WordPress/gutenberg/blob/9a6958e6a3e69ecda18b8deb4e1b3cec352e30a0/packages/components/src/utils/strings.ts#L81) helper that I think could be applied to the `first` character value.

This looks to be a bug introduced in #39303.

### Step-by-step reproduction instructions

1. Use the `UnitControl` in a block or any React environment with the following code.

```js
<UnitControl
	value={value}
	onChange={onChange}
	units={[
		{
			label: '+',
			value: '+',
		},
		{
			label: '-',
			value: '-',
		},
	]}
/>
```

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- Gutenberg 16.1
- Firefox

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by TimothyBJacobs**
## What?
Applies `escapeRegExp` to unit values when building the regular expression.

## Why?
This escapes any units that happen to be regex control characters which prevents the component from crashing due to an invalid regular expression.

Fixes #52210.

### CODE REVIEW

File: packages/components/src/unit-control/test/index.tsx [hunk 1]
```diff
@@ -373,18 +373,20 @@ describe( 'UnitControl', () => {
 			const units = [
 				{ value: 'pt', label: 'pt', default: 0 },
 				{ value: 'vmax', label: 'vmax', default: 10 },
+				{ value: '+', label: '+', default: 10 },
```
Comment (stokesman) [inline packages/components/src/unit-control/test/index.tsx:377]:
```suggestion
				// Proves that units with regex control characters don't error.
				{ value: '+', label: '+', default: 10 },
```
I like the idea of noting the significance of this but I don't think anyone’s going to haphazardly change the test on us 🤷.

**Review by stokesman — APPROVED** [review]
This makes sense and works. Thanks for the fix! For my personal itch to get hands-on I tested this in the block editor.

<details><summary>Console paste-able snippet for testing in block settings of a Paragraph block</summary>

```javascript
( ( {
	blockEditor: { InspectorControls },
	components: { PanelBody, __experimentalUnitControl: UnitControl },
	compose: { createHigherOrderComponent },
	element: { createElement: el, Fragment },
	hooks: { addFilter },
} ) => {
	addFilter(
		'editor.BlockEdit',
		'test/unit-control-regexp',
		createHigherOrderComponent( CoreEdit => props => {
			if ( props.name !== 'core/paragraph' ) return el( CoreEdit, props );

			return el( Fragment, null,
				el( InspectorControls, null,
					el( PanelBody, {title: 'Loggy UnitControl'},
						el( UnitControl, {
							onChange: v => console.log( '¡', v, '!' ),
							units: [
								{ value: 'pt', label: 'pt', default: 0 },
								{ value: 'vmax', label: 'vmax', default: 10 },
								{ value: '+', label: '+', default: 10 }
							]
						}),
					)
				),
				el( CoreEdit, props )
			);
		} )
	)
} )( wp );
```

</details>

**Comment by TimothyBJacobs** [comment]
Thanks for the review @stokesman!
