### PR TITLE
Fix: JavaScript error when pattern category is unregistered

### LINKED ISSUE #67060: Edge case: The editors break if the pattern category taxonomy is unregistered
### Description

The `wp_pattern_category` is [a taxonomy registered on the `wp_block` post type](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/taxonomy.php#L226).

It can be unregistered using [unregister_taxonomy_for_object_type](https://developer.wordpress.org/reference/functions/unregister_taxonomy_for_object_type/)

If the taxonomy is unregistered, the editors break with the following JavaScript error:

```
react-dom.min.js?ver=18:1 TypeError: Cannot read properties of undefined (reading 'map')
    at Pe (private-selectors.js:333:47)
    at private-selectors.js:394:6
    at Array.map (<anonymous>)
    at private-selectors.js:393:6
    at s (rememo.js:270:18)
    at r (factory.js:56:10)
    at r (index.js:249:13)
    at selectors.js:2482:22
    at s (rememo.js:270:18)
    at r (factory.js:56:10)

```

Image

I am not sure what the use case would be: But since unregistering is supported by WordPress, the editors should not break if it happens.

### Step-by-step reproduction instructions

Unregister the taxonomy. For example, copy the following to functions.php in your active theme:

```
add_action( 'init', 'unregister' );
function unregister() {
	unregister_taxonomy_for_object_type( 'wp_pattern_category', 'wp_block' );
}
```

Create a new post. Confirm if there is a JavaScript error.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

I am using WordPress 6.7 with Gutenberg trunk and:

```
define( 'WP_DEBUG', true );
define( 'WP_DEVELOPMENT_MODE', 'theme' );
define( 'WP_ENVIRONMENT_TYPE', 'local' );
```

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by carolinan**
## What?

Because the wp_pattern_category taxonomy can be unregistered, it needs to be used conditionally in the JavaScript code, or there may be JavaScript errors.

Closes https://github.com/WordPress/gutenberg/issues/67060

## Testing Instructions
Unregister the wp_pattern_category taxonomy.
For example, copy the following to functions.php in your active theme:

```
add_action( 'init', 'unregister' );
function unregister() {
	unregister_taxonomy_for_object_type( 'wp_pattern_category', 'wp_block' );
}
```

Please test the following and watch for any regressions or JavaScript errors:

1. Create a new post
2. Insert a paragraph block and open the Options menu in the block toolbar. 
3. In the options menu dropdown, select "Create pattern". Select synced. Do not add a category. Create the pattern.
4. Click on "Edit original" in the block toolbar.
5. Confirm that there is no category setting.

Repeat and create 3 more patterns:
Synced with custom category
Unsynced without category
Unsycned with custom category

Go to the pattern dataviews page (Appearance > Editor > Patterns or Appearance > Patterns depending on your theme)
Create the different patterns using the "Add New Pattern" button.

Confirm that the custom category you created when creating patterns is not listed in the sidebar with the other pattern categories.

### CODE REVIEW

**Comment by carolinan** [comment]
This is a follow up to https://github.com/WordPress/gutenberg/pull/66945 https://github.com/WordPress/gutenberg/pull/66889
@matiasbenedetto @mcsf I need help with finding out if there are any other scenarios to test for / any other parts of the code that needs updating.

Also, while it does not break the editors in a way that make them unusable, it is not correct  and a strange user experience that it is still possible to enter a custom category name during pattern creation, even if the taxonomy is unregistered.

File: packages/edit-site/src/components/page-patterns/use-patterns.js [hunk 1]
```diff
@@ -156,7 +156,7 @@ const selectPatterns = createSelector(
 				categoryId,
 				hasCategory: ( item, currentCategory ) => {
 					if ( item.type === PATTERN_TYPES.user ) {
-						return item.wp_pattern_category.some(
+						return item.wp_pattern_category?.some(
```
Comment (mcsf) [inline packages/edit-site/src/components/page-patterns/use-patterns.js:159]: There's another `item.wp_pattern_category.some( ... )` call 16 lines below. I assume you intentionally left it untouched because it's guarded with `! item.wp_pattern_category?.length ||`, but I would feel safer if we added the `?` there too — just in case someone in the future refactors that code and in the process forgets to guard it.

**Review by mcsf — APPROVED** [review]
From my own search through the code, I think you've found all the occurrences. LGTM, but please see my inline comment about adding an extra guard.

File: packages/edit-site/src/components/page-patterns/use-patterns.js (hunk 1 above)
Comment (carolinan) [reply packages/edit-site/src/components/page-patterns/use-patterns.js:159]: Yes, that was why.
I updated this location and found one more that I skipped earlier.

**Review by mcsf — APPROVED** [review]

**Review by juanfra — APPROVED** [review]
LGTM, thanks!
