### PR TITLE
Fix: Disable block commenting when postId is not number

### LINKED ISSUE #71642: Block Comenting: Add `block-comment` as a new post type support
## What problem does this address?

In #71643, we disabled the block commenting when postId is not a number, because the block commenting functionality doesn't work in the template or template part, which has a string value post id, such as `'twentytwentyfive//home'`.

That said, ideally, enabling block commenting should depend on whether the post type supports it, rather than on whether the post ID is an integer.

## What is your proposed solution?

Add `block-comment` as a new post type support. The block commenting should be enabled by default for built-in post types Post and Page.

### PR DESCRIPTION
**Pull request by R1shabh-Gupta**
## What?
Closes #71642 

This PR fixes block commenting functionality to prevent crashes and disable comments when editing templates or other contexts without valid integer post ID.

## Why?
Comments were allowed in template editing (where post ID is a string like `'twentytwentyfive//home'`), but the WordPress REST API requires post IDs to be integers, causing requests to fail

## How?
 Added a check to only show comment functionality when `postId` is a valid number (integer), completely hiding comment UI for templates and other invalid contexts

## Testing Instructions
1. **Test normal post commenting** (should still work):
   - Open any existing post or page for editing
   - Select any block 
   - Verify the comment button appears and works normally

2. **Test template editing** (comments should be disabled):
   - Go to Appearance > Theme Editor > Templates
   - Edit any template (like "Home" or "Single Post")
   - Select any block within the template
   - Verify that NO comment button or comment functionality appears

## Screenshots or screencast 

|Before|After|
|-|-|
| Screenshot 2025-09-14 at 6 21 59 PM | Screenshot 2025-09-14 at 6 21 29 PM |

### CODE REVIEW

File: packages/editor/src/components/collab-sidebar/index.js [hunk 1]
```diff
@@ -336,6 +338,10 @@ export default function CollabSidebar() {
 		? AddCommentToolbarButton
 		: AddCommentButton;
 
+	if ( ! hasValidPostId ) {
+		return null;
+	}
```
Comment (Mamaduka) [inline packages/editor/src/components/collab-sidebar/index.js]: Nit: We could just inline the check here. I usually avoid creating the variables if they're only used once.

**Comment by Mamaduka** [comment]
@R1shabh-Gupta, is this ready for the review?

**Comment by t-hamano** [comment]
@Mamaduka, do we ship this PR first and then add a block comment post type support? https://github.com/WordPress/gutenberg/issues/71642#issuecomment-3291140001

File: packages/editor/src/components/collab-sidebar/index.js (hunk 1 above)
Comment (R1shabh-Gupta) [reply packages/editor/src/components/collab-sidebar/index.js]: Should I update it like this, @Mamaduka? And would it be fine to add a comment?
```JavaScript
// If postId is not a valid number, do not render the comment sidebar.
if ( ! ( !! postId && typeof postId === 'number' ) ) {
	return null;
}
```

Comment (Mamaduka) [reply packages/editor/src/components/collab-sidebar/index.js]: Yes, that looks about right.

**Comment by Mamaduka** [comment]
@t-hamano, yes. We should resolve current errors and since post type supports is still in discussion, this seems like a fastest way.

**Review by t-hamano — APPROVED** [review]
Looks good to me 👍
