### PR TITLE
Font Library: fixes installed font families not rendering in the editor or frontend.

### LINKED ISSUE #58765: Uploaded Fonts Are Not Reflected in Editor Canvas Immediately
### Description

After uploading and activating new fonts through the Font Library modal in Gutenberg, changes are not immediately reflected in the editor's canvas. Specifically, when a new font is applied to a block, the canvas continues to display the default font until the browser tab is refreshed. It might be related to https://github.com/WordPress/gutenberg/issues/58764.

**Expected Behavior**:
After a font is uploaded, activated, and applied to an element in Gutenberg, the canvas should immediately reflect this change without requiring a page refresh.

**Actual Behavior**:
The canvas does not update to show the newly applied font until after the browser tab where Gutenberg is open is refreshed.

### Step-by-step reproduction instructions

1. Download the "Super Enjoy" font from https://www.dafont.com/super-enjoy.font.
2. Upload and activate the font in the Font Library modal.
3. Apply the newly activated font to a heading block in the Gutenberg editor.
4. Observe that the canvas does not update to show the new font; it continues to display the text in the default font. 
5. Refresh the browser tab. 
6. After refreshing, observe that the canvas now correctly displays the heading in the "Super Enjoy" font.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/5287479/4b86e014-c019-479b-9988-8fb19449e6dc

### Environment info

Gutenberg > 17.6

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

### LINKED ISSUE #59010: Font Library in Beta 1 doesn't reflect all applied fonts in the editor side.
### Description

While testing WordPress 6.5 Beta 1, I found that a few fonts if applied won't be reflected in the editor side. However, the applied font is clearly visible on the front end. The next time we open the editor we are able to see this applied font properly with in the editor, but not during the first application.

### Step-by-step reproduction instructions

1. Install WordPress 6.5 Beta 1
2. Go to font library 
3. These are the two fonts I tested with, [Font 1](https://fonts.google.com/specimen/Are+You+Serious?sort=alpha) and [Font 2](https://fonts.google.com/specimen/Black+And+White+Picture?sort=alpha).
4. Apply the font and check whether it can be viewed in the editor side during the first attempt.

### Screenshots, screen recording, code snippet

The editor side:

The front end:

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
Fixes installed font families not rendering in the editor or frontend.

This is an alternative fix https://github.com/WordPress/gutenberg/pull/58853

## Why?
Fixes: https://github.com/WordPress/gutenberg/issues/58765
Fixes: https://github.com/WordPress/gutenberg/issues/59010

## How?
- Improving the format/sanitization functions to output valid CSS properties. Uses the quotes in all the cases needed.
It follows the recommendations from the CSS spec: https://www.w3.org/TR/css-fonts-4/#font-family-prop
- Using the kebab case function formatter to sanitize or create the font family slugs in the frontend and backend to avoid edge cases around slugs. (example: 'dotgothic16' is converted to 'dotgothic-16' because the `theme.json` presets renderer uses that format)
- Firefox-specific fix for loading font faces using JS for 'live' preview. (because Firefox needs quotes in the font faces loaded by JS when the other browsers need to avoid quotes on font faces loaded by JS).

## Testing Instructions
**Test with Firefox, Chrome and Safari** 
- Use WordPress 6.4.3
- Use Gutenberg in this branch.
- Install several font families and check that they load correctly in the editor; as a guide, you can see the screencast below.
Use font faces that demonstrated to produce errors i.e.:  Abril Fatface, Rock 3D, DotGothic16, Slabo 27px, Baloo 2, etc.

## Screenshots or screencast 
Screencast of the fix working:

https://github.com/WordPress/gutenberg/assets/1310626/392df090-fd53-464e-a80d-d99fafae8bf2

### CODE REVIEW

**Comment by matiasbenedetto** [comment]
It seems to be a difference on the quotes needed in Chrome vs Firefox, I'll add a fix for that.

**Comment by matiasbenedetto** [comment]
> It seems to be a difference on the quotes needed in Chrome vs Firefox, I'll add a fix for that.



Chromium-based browsers (Chrome, Edge, Brave, etc) and WebKit browsers (Epiphany, Safari, etc) seem to be working in the same way: Font faces loaded by JS should not have quotes in their names. Gecko browsers (Firefox) are the exception to this. they need quotes on the font face names loaded by JS. I added a conditional to cover both cases and a test assertion based on the user agent here: https://github.com/WordPress/gutenberg/pull/59019/commits/975838582e8bea3669121b965ae3e7ecfc88884b

File: packages/edit-site/src/components/global-styles/font-library-modal/utils/preview-styles.js [hunk 1]
```diff
@@ -30,22 +30,81 @@ function extractFontWeights( fontFaces ) {
...
+			.find( ( item ) => item.trim() !== '' )
+			.trim()
+			// removes leading and trailing quotes.
+			.replace( /^["']|["']$/g, '' );
+	}
+	// removes leading and trailing quotes.
+	output = output.replace( /^["']|["']$/g, '' );
+
+	// Firefox needs the font name to be wrapped in double quotes meanwhile other browsers don't.
+	if ( window.navigator.userAgent.toLowerCase().includes( 'firefox' ) ) {
```
Comment (juanfra) [inline packages/edit-site/src/components/global-styles/font-library-modal/utils/preview-styles.js]: Nit: Should we check for `gecko` to make it more broad and cover not only Firefox but all gecko browsers?

File: packages/edit-site/src/components/global-styles/font-library-modal/utils/preview-styles.js [hunk 2]
```diff
@@ -30,22 +30,81 @@ function extractFontWeights( fontFaces ) {
...
+		output = output
+			.split( ',' )
+			// finds the first item that is not an empty string.
+			.find( ( item ) => item.trim() !== '' )
+			.trim()
+			// removes leading and trailing quotes.
+			.replace( /^["']|["']$/g, '' );
+	}
+	// removes leading and trailing quotes.
+	output = output.replace( /^["']|["']$/g, '' );
```
Comment (juanfra) [inline packages/edit-site/src/components/global-styles/font-library-modal/utils/preview-styles.js:99]: Nit: We could think of abstracting this replacement in a function as we use it in different places.

**Review by juanfra — APPROVED** [review]
Thank you, @matiasbenedetto! The fix works as expected. Tested in Chrome and Firefox. Code looks good to me, left a couple nits.

https://github.com/WordPress/gutenberg/assets/252415/8b2bb03c-f39c-4f8d-ba01-e94d0f5423bf

File: packages/edit-site/src/components/global-styles/font-library-modal/utils/preview-styles.js (hunk 2 above)
Comment (matiasbenedetto) [reply packages/edit-site/src/components/global-styles/font-library-modal/utils/preview-styles.js:99]: Good catch, I removed one of the calls that was redundant: https://github.com/WordPress/gutenberg/pull/59019/commits/8abd359c1b163f6569d4b48805694246a8a8324d

File: packages/edit-site/src/components/global-styles/font-library-modal/utils/preview-styles.js (hunk 1 above)
Comment (matiasbenedetto) [reply packages/edit-site/src/components/global-styles/font-library-modal/utils/preview-styles.js]: I tried with 'gecko' https://github.com/WordPress/gutenberg/pull/59019/commits/2f3a0dfabcaae6e3a8b33a4d119f2aff33b23f30, but after that, I noticed that "Gecko" string is in a wide range of user-agents, so I think we should use "firefox" and "fxios"(firefox for ios). Added that here: https://github.com/WordPress/gutenberg/pull/59019/commits/f85650a927669ebb4da74b2e43680b08064f623a

Reference:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent
- https://deviceatlas.com/blog/list-of-user-agent-strings

Comment (creativecoder) [reply packages/edit-site/src/components/global-styles/font-library-modal/utils/preview-styles.js]: Note that Firefox on iOS uses the Safari/Webkit engine (as do all iOS browsers, as currently required by Apple), so I'm guessing it will need the same treatment as Safari (no quotes), I'll see if I can test it.

Comment (matiasbenedetto) [reply packages/edit-site/src/components/global-styles/font-library-modal/utils/preview-styles.js]: Good call; I didn't know that. I'm unable to test on iOS, but if it's not Gecko engine, we should not include it among the exceptions. I removed that from the conditional in this PR: https://github.com/WordPress/gutenberg/pull/59037

Reference: https://firefox-source-docs.mozilla.org/overview/ios.html

File: lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php [hunk 3]
```diff
@@ -20,11 +20,41 @@
...
+		/**
+		 * Adds surrounding quotes to font family names that contain special characters.
+		 *
+		 * It follows the recommendations from the CSS Fonts Module Level 4.
+		 * @link https://www.w3.org/TR/css-fonts-4/#font-family-prop
+		 *
+		 * @since 6.5.0
+		 * @access private
+		 *
+		 * @see sanitize_font_family()
```
Comment (creativecoder) [inline lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php:33]: `@see` is for referencing other things that this method relies on, so doesn't seem needed here (https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#1-functions-class-methods)

File: lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php [hunk 4]
```diff
@@ -20,11 +20,41 @@
...
 	class WP_Font_Utils {
+
+		/**
+		 * Adds surrounding quotes to font family names that contain special characters.
+		 *
+		 * It follows the recommendations from the CSS Fonts Module Level 4.
+		 * @link https://www.w3.org/TR/css-fonts-4/#font-family-prop
+		 *
+		 * @since 6.5.0
+		 * @access private
```
Comment (creativecoder) [inline lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php:31]: `@access private` probably isn't needed, since this is already a private method.

File: lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php [hunk 5]
```diff
@@ -20,11 +20,41 @@
...
+		 *
+		 * @see sanitize_font_family()
+		 *
+		 * @param string $item A font family name.
+		 * @return string The font family name with surrounding quotes if necessary.
```
Comment (creativecoder) [inline lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php:36]: Add comma: `The font family name with surrounding quotes, if necessary.`

File: lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php [hunk 6]
```diff
@@ -20,11 +20,41 @@
...
+		 */
+		private static function maybe_add_quotes( $item ) {
+			// Match any non alphabetic characters (a-zA-Z), dashes -, or parenthesis ().
+			$regex = '/[^a-zA-Z\-()]+/';
+			$item  = trim( $item );
+			if ( preg_match( $regex, $item ) ) {
+				// Removes leading and trailing quotes.
+				$item = preg_replace( '/^["\']|["\']$/', '', $item );
+				return "\"$item\"";
```
Comment (creativecoder) [inline lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php:45]: Perhaps a little easier to read: `return '"' . $item . '"';`

File: lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php [hunk 7]
```diff
@@ -20,11 +20,41 @@
...
+			}
+			return $item;
+		}
+
 		/**
 		 * Sanitizes and formats font family names.
 		 *
 		 * - Applies `sanitize_text_field`
-		 * - Adds surrounding quotes to names that contain spaces and are not already quoted
+		 * - Adds surrounding quotes to names that special
```
Comment (creativecoder) [inline lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php:54]: I think this was meant to be something like: "Adds surrounding quotes to names that contain spaces or special characters"

File: lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php [hunk 8]
```diff
@@ -39,26 +69,19 @@ public static function sanitize_font_family( $font_family ) {
...
 			}
 
-			$font_family           = sanitize_text_field( $font_family );
-			$font_families         = explode( ',', $font_family );
-			$wrapped_font_families = array_map(
-				function ( $family ) {
-					$trimmed = trim( $family );
-					if ( ! empty( $trimmed ) && str_contains( $trimmed, ' ' ) && ! str_contains( $trimmed, "'" ) && ! str_contains( $trimmed, '"' ) ) {
-							return '"' . $trimmed . '"';
+			$output          = trim( sanitize_text_field( $font_family ) );
```
Comment (creativecoder) [inline lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php:72]: `sanitize_text_field` already applies `trim`, so adding `trim` here is redundant.

File: lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php [hunk 9]
```diff
@@ -20,11 +20,41 @@
...
+		 * @param string $item A font family name.
+		 * @return string The font family name with surrounding quotes if necessary.
+		 */
+		private static function maybe_add_quotes( $item ) {
+			// Match any non alphabetic characters (a-zA-Z), dashes -, or parenthesis ().
+			$regex = '/[^a-zA-Z\-()]+/';
+			$item  = trim( $item );
+			if ( preg_match( $regex, $item ) ) {
+				// Removes leading and trailing quotes.
+				$item = preg_replace( '/^["\']|["\']$/', '', $item );
```
Comment (creativecoder) [inline lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php:44]: Using `trim` and specifying quotes to strip here is probably slightly more performant than using a regex.

**Review by creativecoder — COMMENTED** [review]
@matiasbenedetto I left several code comments for things that may come up in Core review, in case you want to address them now.

File: lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php [hunk 10]
```diff
@@ -20,11 +20,41 @@
...
+		 * @access private
+		 *
+		 * @see sanitize_font_family()
+		 *
+		 * @param string $item A font family name.
+		 * @return string The font family name with surrounding quotes if necessary.
+		 */
+		private static function maybe_add_quotes( $item ) {
+			// Match any non alphabetic characters (a-zA-Z), dashes -, or parenthesis ().
+			$regex = '/[^a-zA-Z\-()]+/';
```
Comment (creativecoder) [inline lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php:40]: I see [in the spec](https://www.w3.org/TR/css-fonts-4/#family-name-syntax), it says

> To avoid mistakes in escaping, it is recommended to quote font family names that contain white space, digits, or punctuation characters other than hyphens

I'm curious, why allow unquoted names with parentheses here, as well?

Comment (matiasbenedetto) [reply lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php:40]: I'm 100% not sure about the '()' characters because the spec has examples like this, but I have never saw outside of those examples.
```
body { font-family: "Adobe Fangsong Std R", generic(fangsong), serif}
```

>The first choice in this example is a specific, named font, in Fang Song (仿宋) style. The family name is enclosed in quotes as it contains space characters. **The second is a recently added script-specific generic font; it is unicode-range specific and so may not match to an actual installed font on some systems; but if it exists it will be an example of the requested style.** The third is a universal generic font, which is guaranteed to match on all systems.

I think we should allow the parenthesis but not anywhere, the regex should only allow them used with the `generic` keyword like this: `generic(<generic-name>)`.

Comment (creativecoder) [reply lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php:40]: I see, it looks like `generic()` is used for specifying system fonts for some scripts: `generic(fangsong)` for the Fang Song Chinese typeface, `generic(kai)` for Simplified and Traditional Chinese, and `generic(nastaliq)` for Urdu and Kashmiri are [listed in the spec](https://drafts.csswg.org/css-fonts/#generic-font-families). Though I imagine others could be added.

> I think we should allow the parenthesis but not anywhere, the regex should only allow them used with the `generic` keyword like this: `generic(<generic-name>)`.

That makes sense to me, with generic-name having the same restriction to contain only alphabetic characters and dashes.

Comment (creativecoder) [reply lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php:40]: Note that [according to this W3C notice](https://www.w3.org/TR/clreq-gap/#issue587_fonts), no major browsers support font family names like `generic(fangsong)`, yet, (at least for Chinese fonts).

Though I think it would be best for us to anticipate this will be supported sometime in the future.

Comment (matiasbenedetto) [reply lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php:40]: Adding generic support here: https://github.com/WordPress/gutenberg/pull/59103

**Comment by matiasbenedetto** [comment]
@creativecoder I added all the nits you pointer in this PR: https://github.com/WordPress/gutenberg/pull/59103

**Comment by swissspidy** [comment]
> This pull request has changed or added PHP files. Please confirm whether these changes need to be synced to WordPress Core, and therefore featured in the next release of WordPress.
> 
> If so, it is recommended to create a [new Trac ticket](https://core.trac.wordpress.org/newticket) and submit a pull request to the [WordPress Core Github repository](https://github.com/WordPress/wordpress-develop) soon after this pull request is merged.
> 
> If you're unsure, you can always ask for help in the #core-editor channel in [WordPress Slack](https://make.wordpress.org/chat/).
> 
> Thank you! ❤️
> 
> View changed files

There is already a ticket, see https://core.trac.wordpress.org/ticket/60537

File: lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php (hunk 4 above)
Comment (swissspidy) [reply lib/compat/wordpress-6.5/fonts/class-wp-font-utils.php:31]: Indeed!

Adding `@access private` is incorrect as per the coding standards.

**Comment by nith53** [comment]
> > This pull request has changed or added PHP files. Please confirm whether these changes need to be synced to WordPress Core, and therefore featured in the next release of WordPress.
> > If so, it is recommended to create a [new Trac ticket](https://core.trac.wordpress.org/newticket) and submit a pull request to the [WordPress Core Github repository](https://github.com/WordPress/wordpress-develop) soon after this pull request is merged.
> > If you're unsure, you can always ask for help in the #core-editor channel in [WordPress Slack](https://make.wordpress.org/chat/).
> > Thank you! ❤️
> > View changed files
> 
> There is already a ticket, see https://core.trac.wordpress.org/ticket/60537

The ticket was recently closed stating it was reported upstream.

**Comment by swissspidy** [comment]
@nith53 Well, yes, but a ticket is still required for adding this PR here into core :)

**Comment by nith53** [comment]
> @nith53 Well, yes, but a ticket is still required for adding this PR here into core :)

Reopened for now. Thank you for the clarification.

**Comment by getdave** [comment]
I just cherry-picked this PR to the cherry-pick-beta-2 branch to get it included in the next release: de9eb98014
