### PR TITLE
Fix and refine core function escaping in block output

### LINKED ISSUE #38568: Audit block escaping issues
The following PRs introduces regressions in output of markup on the front of the site. This was due to overzealous escaping of Core functions which in hindsight was not a good idea. I apologise for this.

This Issue tracks an audit of each PR. Any escaping of core functions will be revert in [#38569](https://github.com/WordPress/gutenberg/pull/38569) unless otherwise noted:

- [x]  https://github.com/WordPress/gutenberg/pull/37834 - no Core functions escaped. 
- [x]  https://github.com/WordPress/gutenberg/pull/37835 -  no Core functions escaped. 
- [x]  https://github.com/WordPress/gutenberg/pull/37860 - reverting in [#38569](https://github.com/WordPress/gutenberg/pull/38569)
- [x]  https://github.com/WordPress/gutenberg/pull/37865 - reverting in [#38569](https://github.com/WordPress/gutenberg/pull/38569)
- [x]  https://github.com/WordPress/gutenberg/pull/37866 - fixed in [#38145](https://github.com/WordPress/gutenberg/pull/38145) + additional fixes in `#38568`
- [x]  https://github.com/WordPress/gutenberg/pull/37870 - no Issues identified.
- [x]  https://github.com/WordPress/gutenberg/pull/37873 - reverting in [#38569](https://github.com/WordPress/gutenberg/pull/38569)
- [x]  https://github.com/WordPress/gutenberg/pull/37874 - no Issues identified.
- [x]  https://github.com/WordPress/gutenberg/pull/37875 - reverting in [#38569](https://github.com/WordPress/gutenberg/pull/38569)
- [x]  https://github.com/WordPress/gutenberg/pull/37876 - reverting in `#38567` and also in [#38569](https://github.com/WordPress/gutenberg/pull/38569)
- [x]  https://github.com/WordPress/gutenberg/pull/37877 - fixed in `#38519`.
- [x]  https://github.com/WordPress/gutenberg/pull/37878 - fixed in `#38117`
- [x]  https://github.com/WordPress/gutenberg/pull/37879 - no Issues identified.
- [x]  https://github.com/WordPress/gutenberg/pull/37880 - reverting in [#38569](https://github.com/WordPress/gutenberg/pull/38569)
- [x]  https://github.com/WordPress/gutenberg/pull/37881 - no Issues identified.
- [x]  https://github.com/WordPress/gutenberg/pull/37882 - no Issues identified.
- [x] Post Pagination - fixed in [`#38519`](https://github.com/WordPress/gutenberg/pull/38519)

### PR DESCRIPTION
**Pull request by getdave**
## Description
Reverts various blocks as per audit in https://github.com/WordPress/gutenberg/issues/38568

Closes https://github.com/WordPress/gutenberg/issues/38568

## Testing Instructions

Test each block's output on the front of the site. No raw HTML should be output.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

File: packages/block-library/src/comment-date/index.php [hunk 1]
```diff
@@ -31,13 +31,13 @@ function render_block_core_comment_date( $attributes, $content, $block ) {
 	$link               = get_comment_link( $comment );
 
 	if ( ! empty( $attributes['isLink'] ) ) {
-		$formatted_date = sprintf( '<a href="%1s">%2s</a>', esc_url( $link ), esc_html( $formatted_date ) );
```
Comment (getdave) [inline packages/block-library/src/comment-date/index.php:34]: Core function - can be trusted, maybe filtered.

File: packages/block-library/src/comment-date/index.php [hunk 2]
```diff
@@ -31,13 +31,13 @@ function render_block_core_comment_date( $attributes, $content, $block ) {
...
+		$formatted_date = sprintf( '<a href="%1s">%2s</a>', esc_url( $link ), $formatted_date );
 	}
 
 	return sprintf(
 		'<div %1$s><time datetime="%2$s">%3$s</time></div>',
 		$wrapper_attributes,
-		esc_attr( get_comment_date( 'c', $comment ) ),
+		get_comment_date( 'c', $comment ),
```
Comment (getdave) [inline packages/block-library/src/comment-date/index.php]: Core function - can be trusted, maybe filtered.

File: packages/block-library/src/latest-comments/index.php [hunk 3]
```diff
@@ -86,14 +86,14 @@ function render_block_core_latest_comments( $attributes = array() ) {
 
 			$author_markup = '';
 			if ( $author_url ) {
-				$author_markup .= '<a class="wp-block-latest-comments__comment-author" href="' . esc_url( $author_url ) . '">' . esc_html( get_comment_author( $comment ) ) . '</a>';
+				$author_markup .= '<a class="wp-block-latest-comments__comment-author" href="' . esc_url( $author_url ) . '">' . get_comment_author( $comment ) . '</a>';
```
Comment (getdave) [inline packages/block-library/src/latest-comments/index.php:89]: Core function - can be trusted, maybe filtered.

File: packages/block-library/src/latest-comments/index.php [hunk 4]
```diff
@@ -86,14 +86,14 @@ function render_block_core_latest_comments( $attributes = array() ) {
...
 			} else {
-				$author_markup .= '<span class="wp-block-latest-comments__comment-author">' . esc_html( get_comment_author( $comment ) ) . '</span>';
+				$author_markup .= '<span class="wp-block-latest-comments__comment-author">' . get_comment_author( $comment ) . '</span>';
```
Comment (getdave) [inline packages/block-library/src/latest-comments/index.php:91]: Core function - can be trusted, maybe filtered.

File: packages/block-library/src/latest-comments/index.php [hunk 5]
```diff
@@ -86,14 +86,14 @@ function render_block_core_latest_comments( $attributes = array() ) {
...
 			}
 
 			// `_draft_or_post_title` calls `esc_html()` so we don't need to wrap that call in
 			// `esc_html`.
-			$post_title = '<a class="wp-block-latest-comments__comment-link" href="' . esc_url( get_comment_link( $comment ) ) . '">' . esc_html( wp_latest_comments_draft_or_post_title( $comment->comment_post_ID ) ) . '</a>';
+			$post_title = '<a class="wp-block-latest-comments__comment-link" href="' . get_comment_link( $comment ) . '">' . wp_latest_comments_draft_or_post_title( $comment->comment_post_ID ) . '</a>';
```
Comment (getdave) [inline packages/block-library/src/latest-comments/index.php]: Core function - can be trusted, maybe filtered.

File: packages/block-library/src/latest-comments/index.php [hunk 6]
```diff
@@ -106,7 +106,7 @@ function render_block_core_latest_comments( $attributes = array() ) {
 				$list_items_markup .= sprintf(
 					'<time datetime="%1$s" class="wp-block-latest-comments__comment-date">%2$s</time>',
 					esc_attr( get_comment_date( 'c', $comment ) ),
-					esc_html( date_i18n( get_option( 'date_format' ), get_comment_date( 'U', $comment ) ) )
+					date_i18n( get_option( 'date_format' ), get_comment_date( 'U', $comment ) )
```
Comment (getdave) [inline packages/block-library/src/latest-comments/index.php:109]: Core function - can be trusted, maybe filtered.

File: packages/block-library/src/latest-posts/index.php [hunk 7]
```diff
@@ -119,7 +119,7 @@ function render_block_core_latest_posts( $attributes ) {
 			if ( ! empty( $author_display_name ) ) {
 				$list_items_markup .= sprintf(
 					'<div class="wp-block-latest-posts__post-author">%1$s</div>',
-					esc_html( $byline )
+					$byline
```
Comment (getdave) [inline packages/block-library/src/latest-posts/index.php:122]: Generated by Core function - can be trusted, maybe filtered.

File: packages/block-library/src/latest-posts/index.php [hunk 8]
```diff
@@ -128,7 +128,7 @@ function render_block_core_latest_posts( $attributes ) {
 			$list_items_markup .= sprintf(
 				'<time datetime="%1$s" class="wp-block-latest-posts__post-date">%2$s</time>',
 				esc_attr( get_the_date( 'c', $post ) ),
-				esc_html( get_the_date( '', $post ) )
+				get_the_date( '', $post )
```
Comment (getdave) [inline packages/block-library/src/latest-posts/index.php:131]: Core function - can be trusted, maybe filtered.

File: packages/block-library/src/page-list/index.php [hunk 9]
```diff
@@ -188,10 +188,10 @@ function block_core_page_list_render_nested_page_list( $open_submenus_on_click,
...
 
 		if ( isset( $page['children'] ) && $is_navigation_child && $open_submenus_on_click ) {
-			$markup .= '<button aria-label="' . esc_attr( $aria_label ) . '" class="' . esc_attr( $navigation_child_content_class ) . ' wp-block-navigation-submenu__toggle" aria-expanded="false">' . esc_html( $title ) . '<span class="wp-block-page-list__submenu-icon wp-block-navigation__submenu-icon"><svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 12 12" fill="none" aria-hidden="true" focusable="false"><path d="M1.50002 4L6.00002 8L10.5 4" stroke-width="1.5"></path></svg></span>' .
+			$markup .= '<button aria-label="' . esc_attr( $aria_label ) . '" class="' . esc_attr( $navigation_child_content_class ) . ' wp-block-navigation-submenu__toggle" aria-expanded="false">' . $title . '<span class="wp-block-page-list__submenu-icon wp-block-navigation__submenu-icon"><svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 12 12" fill="none" aria-hidden="true" focusable="false"><path d="M1.50002 4L6.00002 8L10.5 4" stroke-width="1.5"></path></svg></span>' .
```
Comment (getdave) [inline packages/block-library/src/page-list/index.php:191]: Generated by Core function - can be trusted, maybe filtered.

File: packages/block-library/src/page-list/index.php [hunk 10]
```diff
@@ -188,10 +188,10 @@ function block_core_page_list_render_nested_page_list( $open_submenus_on_click,
...
 			'</button>';
 		} else {
-			$markup .= '<a class="wp-block-pages-list__item__link' . esc_attr( $navigation_child_content_class ) . '" href="' . esc_url( $page['link'] ) . '"' . $aria_current . '>' . esc_html( $title ) . '</a>';
+			$markup .= '<a class="wp-block-pages-list__item__link' . esc_attr( $navigation_child_content_class ) . '" href="' . esc_url( $page['link'] ) . '"' . $aria_current . '>' . $title . '</a>';
```
Comment (getdave) [inline packages/block-library/src/page-list/index.php:194]: Generated by Core function - can be trusted, maybe filtered.

File: packages/block-library/src/page-list/index.php [hunk 11]
```diff
@@ -316,8 +316,8 @@ function render_block_core_page_list( $attributes, $content, $block ) {
 
 	$wrapper_attributes = get_block_wrapper_attributes(
 		array(
-			'class' => esc_attr( $css_classes ),
-			'style' => esc_attr( $style_attribute ),
+			'class' => $css_classes,
+			'style' => $style_attribute,
```
Comment (getdave) [inline packages/block-library/src/page-list/index.php:320]: Not required. Handled by function.

File: packages/block-library/src/post-comments-link/index.php [hunk 12]
```diff
@@ -33,7 +33,7 @@ function render_block_core_post_comments_link( $attributes, $content, $block ) {
 		$comment_html = sprintf(
 			/* translators: %s post title */
 			__( 'No comments<span class="screen-reader-text"> on %s</span>' ),
-			esc_html( $post_title )
+			$post_title
```
Comment (getdave) [inline packages/block-library/src/post-comments-link/index.php:36]: Generated by Core function - can be trusted, maybe filtered.

File: packages/block-library/src/post-comments-link/index.php [hunk 13]
```diff
@@ -44,7 +44,7 @@ function render_block_core_post_comments_link( $attributes, $content, $block ) {
 				$comments_number
 			),
 			esc_html( number_format_i18n( $comments_number ) ),
-			esc_html( $post_title )
+			$post_title
```
Comment (getdave) [inline packages/block-library/src/post-comments-link/index.php:47]: Generated by Core function - can be trusted, maybe filtered.

File: packages/block-library/src/post-date/index.php [hunk 14]
```diff
@@ -23,7 +23,7 @@ function render_block_core_post_date( $attributes, $content, $block ) {
 	$wrapper_attributes = get_block_wrapper_attributes( array( 'class' => $align_class_name ) );
 	$formatted_date     = get_the_date( isset( $attributes['format'] ) ? $attributes['format'] : '', $post_ID );
 	if ( isset( $attributes['isLink'] ) && $attributes['isLink'] ) {
-		$formatted_date = sprintf( '<a href="%1s">%2s</a>', get_the_permalink( $post_ID ), esc_html( $formatted_date ) );
+		$formatted_date = sprintf( '<a href="%1s">%2s</a>', get_the_permalink( $post_ID ), $formatted_date );
```
Comment (getdave) [inline packages/block-library/src/post-date/index.php:26]: Generated by Core function - can be trusted, maybe filtered.

File: packages/block-library/src/site-tagline/index.php [hunk 15]
```diff
@@ -23,7 +23,7 @@ function render_block_core_site_tagline( $attributes ) {
 	return sprintf(
 		'<p %1$s>%2$s</p>',
 		$wrapper_attributes,
-		esc_html( $site_tagline )
+		$site_tagline
```
Comment (getdave) [inline packages/block-library/src/site-tagline/index.php:26]: Generated by Core function - can be trusted, maybe filtered.

File: packages/block-library/src/site-title/index.php [hunk 16]
```diff
@@ -36,7 +36,7 @@ function render_block_core_site_title( $attributes ) {
 		if ( '_blank' === $attributes['linkTarget'] ) {
 			$link_attrs[] = 'target="_blank"';
 		}
-		$site_title = sprintf( '<a %1$s>%2$s</a>', implode( ' ', $link_attrs ), esc_html( $site_title ) );
+		$site_title = sprintf( '<a %1$s>%2$s</a>', implode( ' ', $link_attrs ), $site_title );
```
Comment (getdave) [inline packages/block-library/src/site-title/index.php]: Generated by Core function - can be trusted, maybe filtered.

File: packages/block-library/src/post-excerpt/index.php [hunk 17]
```diff
@@ -24,7 +24,7 @@ function render_block_core_post_excerpt( $attributes, $content, $block ) {
 		return '';
 	}
 
-	$more_text           = ! empty( $attributes['moreText'] ) ? '<a class="wp-block-post-excerpt__more-link" href="' . esc_url( get_the_permalink( $block->context['postId'] ) ) . '">' . esc_html( $attributes['moreText'] ) . '</a>' : '';
+	$more_text           = ! empty( $attributes['moreText'] ) ? '<a class="wp-block-post-excerpt__more-link" href="' . esc_url( get_the_permalink( $block->context['postId'] ) ) . '">' . wp_kses_post( $attributes['moreText'] ) . '</a>' : '';
```
Comment (getdave) [inline packages/block-library/src/post-excerpt/index.php:27]: More text may be rich text and contain some HTML. See https://github.com/WordPress/gutenberg/issues/38560

File: packages/block-library/src/comment-date/index.php (hunk 2 above)
Comment (Mamaduka) [reply packages/block-library/src/comment-date/index.php]: I think it's okay to escape this value - https://github.com/Automattic/_s/blob/master/inc/template-tags.php#L23

File: packages/block-library/src/latest-comments/index.php (hunk 5 above)
Comment (Mamaduka) [reply packages/block-library/src/latest-comments/index.php]: Core escapes `get_comment_link` - https://github.com/WordPress/wordpress-develop/blob/f0180f59ea00683647c602941c1f2b422192df46/src/wp-includes/comment.php#L3675

File: packages/block-library/src/latest-comments/index.php (hunk 4 above)
Comment (Mamaduka) [reply packages/block-library/src/latest-comments/index.php:91]: LGTM 👍

File: packages/block-library/src/comment-date/index.php (hunk 2 above)
Comment (getdave) [reply packages/block-library/src/comment-date/index.php]: Unfortunately as I'm learning, anything that can be filtered can contain HTML. 

https://github.com/WordPress/wordpress-develop/blob/f0180f59ea00683647c602941c1f2b422192df46/src/wp-includes/comment-template.php#L568

So I'm not sure. Most of these "reverts" are on core functions because of this fact.

File: packages/block-library/src/latest-comments/index.php (hunk 6 above)
Comment (getdave) [reply packages/block-library/src/latest-comments/index.php:109]: ✅

File: packages/block-library/src/latest-comments/index.php (hunk 5 above)
Comment (getdave) [reply packages/block-library/src/latest-comments/index.php]: ✅

File: packages/block-library/src/comment-date/index.php (hunk 2 above)
Comment (Mamaduka) [reply packages/block-library/src/comment-date/index.php]: In this case, it should never contain HTML since the value is for the `datetime` attribute.

P.S. There's similar escape login in the latest-comments block.

Comment (getdave) [reply packages/block-library/src/comment-date/index.php]: > it should never contain HTML since the value is for the datetime attribute.

That's the key point. Thanks 👍

File: packages/block-library/src/page-list/index.php (hunk 9 above)
Comment (Mamaduka) [reply packages/block-library/src/page-list/index.php:191]: The value is sanitized above using `wp_kses` 👍

File: packages/block-library/src/comment-date/index.php (hunk 2 above)
Comment (getdave) [reply packages/block-library/src/comment-date/index.php]: ✅

File: packages/block-library/src/page-list/index.php (hunk 11 above)
Comment (Mamaduka) [reply packages/block-library/src/page-list/index.php:320]: Nice catch.

File: packages/block-library/src/site-title/index.php (hunk 16 above)
Comment (Mamaduka) [reply packages/block-library/src/site-title/index.php]: Do you remember if the site title can contain HTML?

I think we should escape here. The `get_bloginfo` calls the `get_option` directly and doesn't do anything else.

Comment (getdave) [reply packages/block-library/src/site-title/index.php]: These scenarios are confusing. If the user has chosen to use HTML in their site title should we allow it to be output to the frontend?

File: packages/block-library/src/page-list/index.php (hunk 9 above)
Comment (getdave) [reply packages/block-library/src/page-list/index.php:191]: If anything we should be the `wp_kses` inline.

Comment (Mamaduka) [reply packages/block-library/src/page-list/index.php:191]: The `$title` is used by aria-label, making sense to "escape" once and re-use.

File: packages/block-library/src/site-title/index.php (hunk 16 above)
Comment (Mamaduka) [reply packages/block-library/src/site-title/index.php]: I can see that the "adminbar" escapes the site title.

CleanShot 2022-02-07 at 16 25 36

Comment (getdave) [reply packages/block-library/src/site-title/index.php]: I've restored the $site_title escaping. 

See https://github.com/WordPress/gutenberg/pull/38569/commits/7456e9dce1ac148f1d0e24bcb8694d3ef1fc212f

File: packages/block-library/src/page-list/index.php (hunk 9 above)
Comment (getdave) [reply packages/block-library/src/page-list/index.php:191]: Agreed.

**Review by kevin940726 — APPROVED** [review]
Code looks good, let's just merge it 👍 .

**Review by Mamaduka — APPROVED** [review]
