### PR TITLE
Add fix to make inputs of type email return true from isTextField

### LINKED ISSUE #12780: Copy Paste Handler Issue
**Describe the bug**
Copying & pasting from a `<input type="text" />` element produces different results to a `<input type="email" />` element.

The value copied from an email input (and also a number input) contains the full block HTML, not the input's value. Issue is demonstrated in the following screen recording.

wbjglpucyf

**To Reproduce**
1. Add the following JS to register the block
2. Enter values into both the text and email inputs
3. Copy and paste the values into the provided textarea

```js
	var el = wp.element.createElement,
    	registerBlockType = wp.blocks.registerBlockType;
	
	registerBlockType( 'test/test-copy-paste', {
	    title: 'Test Copy & Paste',
	    icon: 'universal-access-alt',
	    category: 'layout',
	    edit: function( props ) {
	        return el(
	            'div',
	            {
	                className: 'test',
	            },
	            el(
		            'input',
		            {
		               	type: 'text',
		                placeholder: 'text',
		                style: { width: '45%' }
		            }
		        ),
	            el(
		            'input',
		            {
		                type: 'email',
		                placeholder: 'email',
		                style: { width: '45%' }
		            }
		        ),
		        el(
		            'textarea',
		            {
		                placeholder: 'textarea',
		                style: { width: '100%' }
		            }
		        ),
	        );
	    },
	    save: function( props ) {
	        return el(
	            'p',
	            {},
	            'This is a test.'
	        );
	    }
	});
```

**Expected behavior**
The value copied from any input/textarea should match the behavior of the "text" input.

**Additional context**
- WordPress 5.0

### LINKED ISSUE #15121: Gutenberg 7.7.1/7.8: Simple Payments Block is removed if pasting into the email field
**Describe the bug**

**To reproduce**
1. Edit a page
2. Add a Simple Payments Block
3. Paste any text into the **Email** field
4. See that the field is removed

**Expected behavior**
The text should be pasted into the field

**Screenshots**
Screen Capture on 2020-03-25 at 16-45-37

**Desktop (please complete the following information):**
 - OS: MacOS V10.15.4 (19E266)
 - Browser Firefox
 - Version 74.0 (64-bit)

**Additional context**
- Started with Gutenberg 7.7.1. Also tested on the 7.8 edge version.
- This issue does not happen on previous versions
- Discovered in WPCOM Calypso, also tested on JN with 7.7.1 and 7.8 Gutenberg versions

### PR DESCRIPTION
**Pull request by glendaviesnz**
## Description
Currently `input` fields of type `email` return false from `isTextField` which causes the Gutenberg past handler to take over when pasting into an email input. 

Fixes https://github.com/Automattic/jetpack/issues/15121
Fixes https://github.com/WordPress/gutenberg/issues/12780

## How has this been tested?
Only tested manually at this staging using the email field in the Jetpack Simple Payments block.

## Screenshots 
**before:**

before

after:

after

## Types of changes
Adds an additional check in order flag an input of type email as a text input to prevent Gutenberg's paste handler from hijacking the native input field copy/cut/paste events.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.

### CODE REVIEW

**Comment by glendaviesnz** [comment]
What are people's thoughts on this as at least a temporary fix for the likes of https://github.com/Automattic/jetpack/issues/15121? 

It is not particularly nice approach having to list alternative ways to identify `inputs` that should be classed as `text` but that return `selectStart` as null, but can't think of a simple alternative at the moment that wouldn't still involve listing other input types that should be classed as text for the sake of the pasteHandler bypassing.

File: packages/dom/src/dom.js [hunk 1]
```diff
@@ -453,6 +453,7 @@ export function isTextField( element ) {
 
 		return (
 			( nodeName === 'INPUT' && selectionStart !== null ) ||
+			element.getAttribute( 'type' ) === 'email' ||
```
Comment (glendaviesnz) [inline packages/dom/src/dom.js]: Probably should make this  `( nodeName === 'INPUT' && element.getAttribute( 'type' ) === 'email' )`  will update it if there is some agreement to go with this approach.

Comment (ellatrix) [reply packages/dom/src/dom.js]: I don't get it... is this input type not an input element?

Comment (glendaviesnz) [reply packages/dom/src/dom.js]: The problem is that Chrome at least does not set `selectStart` for anything other than `<input  type="text">`. For  `<input  type="email">`  `selectStart` is `null`, so this method returns false, but in all instances as far as I can tell we are going to want the block editor to treat an input of type email as a text input - sorry, I outlined this in the original ticket, but should have copied it over to this PR.

Comment (ocean90) [reply packages/dom/src/dom.js]: https://stackoverflow.com/a/21959157 seems to be related and links to this [overview](https://html.spec.whatwg.org/multipage/input.html#do-not-apply). `type=number` should be affected as well.

Comment (ocean90) [reply packages/dom/src/dom.js]: @ellatrix How would you like to see this fixed?

Comment (ellatrix) [reply packages/dom/src/dom.js]: Can we remove the `selectionStart` check? I don't know why it's there. There's no comment about it. In which commit was this added?

Comment (ocean90) [reply packages/dom/src/dom.js]: This was added in https://github.com/WordPress/gutenberg/pull/5513/commits/31e70d58a519d9bfb21da5a9d29fb2fb29fa8cc1 by @aduth. Also changed in https://github.com/WordPress/gutenberg/commit/c05ede75a490b5c8b911ad43c6d882a5e61f0a22 to catch an exception in Safari related to `selectionStart`.

Comment (ellatrix) [reply packages/dom/src/dom.js]: Hm, I can't find the relevant PR for 31e70d5. Based on the comment in the other commit, it sounds like we should remove this check as it's terribly inconsistent.

Comment (ocean90) [reply packages/dom/src/dom.js]: Sorry, the commit was part of #5513.

Comment (ocean90) [reply packages/dom/src/dom.js]: Another idea might be restore the previous `isInputField()` and change `isTextField()` to use `isInputField()` + `selectionStart`. Then use `isInputField()` in `documentHasSelection()` which is the [method to check for the native copy handler](https://github.com/WordPress/gutenberg/blob/6b6af357f8addeb5754b620eb5d5e19f2775cf37/packages/block-editor/src/components/copy-handler/index.js#L39).

Comment (ocean90) [reply packages/dom/src/dom.js]: @aduth Do have any thoughts on removing `selectionStart` from `isTextField()`?

Comment (aduth) [reply packages/dom/src/dom.js]: I could have been clearer with code comments. If I recall correctly, I think the main idea was to exclude certain `<input>` elements like "checkbox" and "button". If `selectionStart` is a problem for indicating the positive case of "is a text input", then maybe the logic can be inverted to the negative case of "is not an excluded input". The existing unit tests should give some coverage here.

Comment (glendaviesnz) [reply packages/dom/src/dom.js]: At a quick glance it seems that of the possible 17 `input` `types` 7 could be classed as `text` in terms of user using standard keyboard/paste for text input, so if we want to remove `selectionStart` it probably makes more sense to identify the positive cases explicitly, so have updated the PR to take this approach - if there is some agreement on this will also take a look at tests to check we have this covered effectively.

File: packages/dom/src/dom.js [hunk 2]
```diff
@@ -448,25 +448,22 @@ export function placeCaretAtVerticalEdge(
...
-	}
+	const { nodeName, contentEditable } = element;
+	const textInputs = [
+		'text',
+		'email',
+		'number',
+		'password',
+		'search',
+		'url',
+		'tel',
```
Comment (ocean90) [inline packages/dom/src/dom.js:459]: We probably have to add the date types as well since not all browsers (e.g. Safari) support them and fall back to a text field. Since that's actually the default fall back vor any unknown type we should probably go with a list which are definitely no text inputs. `button`, `checkbox`, `hidden`, `upload`, …

Comment (glendaviesnz) [reply packages/dom/src/dom.js]: ah, good point, have switched to the checking for non text inputs - I think the list is correct, let me know if I have missed anything.

File: packages/dom/src/dom.js [hunk 3]
```diff
@@ -448,25 +448,24 @@ export function placeCaretAtVerticalEdge(
...
+		'file',
+		'radio',
+		'image',
+		'range',
+		'reset',
+		'submit',
+	];
+	return (
+		( nodeName === 'INPUT' &&
+			! nonTextInputs.includes( element.getAttribute( 'type' ) ) ) ||
```
Comment (ellatrix) [inline packages/dom/src/dom.js:465]:
```suggestion
			! nonTextInputs.includes( element.type ) ) ||
```

**Review by ellatrix — APPROVED** [review]
Makes more sense now. :)

**Comment by glendaviesnz** [comment]
Looks like the e2e tests may have picked up some issues with this change, will try and take a look at that in next day or so.
