### PR TITLE
Editor: Fix block highlight rendering after block is moved

### LINKED ISSUE #23413: Highlight remains after selecting other block
**Describe the bug**

Probably caused by #20938. When you move a block and then select another, the highlight remains visible on the first block.

highlight-bug

### PR DESCRIPTION
**Pull request by ItsJonQ**
Screen Capture on 2020-06-24 at 11-04-51

This update resolves the highlight rendering for blocks **after** they've been dragged and moved. The GIF demo above shows the highlight correctly disappearing after a block is moved, and another block is selected.

The solution involved removing the `requestAnimationFrame` wrapper that controlled the highlight state. It seemed like this was previously added to help with Toolbar rendering. I've done a bunch on my end. There does not appear to be any behavioural issues (or console errors) from removing this `rAF` wrapper.

## How has this been tested?

* Run `npm run dev`
* Add a block
* Add another block
* Drag the first block to re-order it. Highlight should appear.
* Drop the block
* Click on another block
* The highlight should disappear.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. 

Resolves: https://github.com/WordPress/gutenberg/issues/23413

### CODE REVIEW

**Comment by youknowriad** [comment]
Is it intended that the block stays highlighted after I drop it?

**Review by youknowriad — APPROVED** [review]
this is better than master, but the fadeout animation when I select another block after move feels a bit long. I'd personally prefer to not highlight the block entirely after drag and drop but maybe that's intended.

**Comment by ItsJonQ** [comment]
> Is it intended that the block stays highlighted after I drop it

@youknowriad It's highlight as long as the BlockSwitcher / Move arrows are hovered or focused. At least, that's how the logic works right now :)

**Comment by youknowriad** [comment]
>  It's highlight as long as the BlockSwitcher / Move arrows are hovered or focused

Makes sense I guess after drag and drop the switcher/movers are focused. maybe there are better heuristics but definitely not the PR for it.

**Comment by ItsJonQ** [comment]
Travis was complaining about snapshots 🤔 . I'm not sure what command I need to run to regenerate these (correctly).

I tried `npm run fixtures:regenerate`. It didn't seem to do anything

**Comment by ItsJonQ** [comment]
Hmm! Not sure how to fix these E2E snapshot test failures 🤔

**Comment by ItsJonQ** [comment]
👋 I think I need some help with these E2E tests.

For example, the Admin 1 test:

GH actions is saying:

```
FAIL packages/e2e-tests/specs/editor/various/block-hierarchy-navigation.test.js (19.371s)
  ● Navigating the block hierarchy › should navigate using the block hierarchy dropdown menu

    expect(received).toMatchSnapshot()

    Snapshot name: `Navigating the block hierarchy should navigate using the block hierarchy dropdown menu 1`

    - Snapshot  - 3
    + Received  + 1

    @@ -8,10 +8,8 @@
      <!-- wp:column -->
      <div class="wp-block-column"></div>
      <!-- /wp:column -->

      <!-- wp:column -->
    - <div class="wp-block-column"><!-- wp:paragraph -->
    - <p>Third column</p>
    - <!-- /wp:paragraph --></div>
    + <div class="wp-block-column"></div>
      <!-- /wp:column --></div>
      <!-- /wp:columns -->


      71 | 		await page.keyboard.type( 'Third column' );
      72 | 
    > 73 | 		expect( await getEditedPostContent() ).toMatchSnapshot();
         | 		                                       ^
      74 | 	} );
      75 | 
      76 | 	it( 'should navigate block hierarchy using only the keyboard', async () => {

      at Object.<anonymous> (specs/editor/various/block-hierarchy-navigation.test.js:73:42)
          at runMicrotasks (<anonymous>)

 › 1 snapshot failed.
```

However, then I run it locally:

```
npm run test-e2e -- packages/e2e-tests/specs/editor/various/block-hierarchy-navigation.test.js
```

It seems okay:

```
 PASS  packages/e2e-tests/specs/editor/various/block-hierarchy-navigation.test.js (44.841s)
  Navigating the block hierarchy
    ✓ should navigate using the block hierarchy dropdown menu (11585ms)
    ✓ should navigate block hierarchy using only the keyboard (9260ms)
    ✓ should appear and function even without nested blocks (8007ms)
    ✓ should select the wrapper div for a group  (8129ms)

Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   4 passed, 4 total
Time:        44.969s
```

**Comment by ItsJonQ** [comment]
Hmm. I'm a bit stuck on this E2E test.

```
	it( 'should undo asterisk transform with backspace after mouse move', async () => {
		await clickBlockAppender();
		await page.keyboard.type( '* ' );
		await page.mouse.move( 0, 0, { steps: 10 } );
		await page.keyboard.press( 'Backspace' );

		expect( await getEditedPostContent() ).toMatchSnapshot();
	} );
```

It says that the snapshot doesn't match.

In doing the interaction in real life (and also observing Chromium), it seems to work okay.
The test seems to not like this part, specifically, the `return` of the `useEffect` hook:

```js
	useEffect( () => {
		// On mount, we make sure to cancel any pending animation frame request
		// that hasn't been completed yet. Components like NavigableToolbar may
		// mount and unmount quickly.
		if ( requestAnimationFrameId ) {
			cancelAnimationFrame( requestAnimationFrameId );
		}

		return () => {
			// Sequences state change to enable editor updates (e.g. cursor
			// position) to render correctly.
			requestAnimationFrameId = requestAnimationFrame( () => {
				updateBlockHighlight( false );
			} );
		};
	}, [ updateBlockHighlight ] );
```

I've tried a bunch of things, including moving the functionality to the `useShowMoversGestures` instead. Doing various this with the `requestAnimationFrameId`. No luck so far.

**Comment by youknowriad** [comment]
I tried playing with the tests, added some timeouts... but unfortunately, I didn't learn a lot. 
Since the snapshot suggests that there's no content, I think maybe the issue is that the "backspace" remove the block entirely.

I think it's a race condition between the "backspace to remove empty lists" and "backspace to work as undo after a transform". cc @ellatrix 

I noticed other bugs (on master too) that could be related: If you have "two empty lists" and click backspace when the last one is focused, both are removed.

**Comment by ellatrix** [comment]
@ItsJonQ This doesn't fix the issue for me. If I select a block, press up/down, then select another block, and you'll see that the highlight is still on the previous block.

**Comment by ItsJonQ** [comment]
@youknowriad Thank you so much for looking into the E2E for me 🙏 

@ellatrix Thank you for extra context. Lemme see what I can do. Maybe it'll fix the E2E complaints 🤷‍♀️

**Comment by ItsJonQ** [comment]
@ellatrix Hmm! I'm not noticing the bug on my end - I'd love to reproduce it though!

I recorded a screencast of me walking through the steps:
https://d.pr/v/xzLOgx

* Click up
* Click Down
* Click another block
* (Highlight disappears)

Let me know if I'm missing something! 🙏

**Comment by ItsJonQ** [comment]
Still figuring out what's happening with this test. I tried something that **may** point to regarding the delete action - something that @youknowriad touched upon.

If I remove my custom `toggleBlockHighlight` hook and add a basic `useEffect` to the `BlockToolbar`, it still breaks in E2E:

```jsx
// packages/block-editor/src/components/block-toolbar/index.js

const { toggleBlockHighlight } = useDispatch( 'core/block-editor' );
useEffect( () => {
    return () => {
        toggleBlockHighlight( blockClientId, false );
    };
}, [ blockClientId ] );

// const toggleBlockHighlight = useToggleBlockHighlight( blockClientId );
```

Test Failure:
```
  ● List › should undo asterisk transform with backspace after mouse move

    expect(received).toMatchSnapshot()

    Snapshot name: `List should undo asterisk transform with backspace after mouse move 1`

    - Snapshot  - 3
    + Received  + 0

    - <!-- wp:paragraph -->
    - <p>* </p>
    - <!-- /wp:paragraph -->
```

**Comment by ItsJonQ** [comment]
Still figuring out what's happening with this test. I tried something that **may** point to regarding the delete action - something that @youknowriad touched upon.

If I remove my custom `toggleBlockHighlight` hook and add a basic `useEffect` to the `BlockToolbar`, it still breaks in E2E:

```jsx
// packages/block-editor/src/components/block-toolbar/index.js

const { toggleBlockHighlight } = useDispatch( 'core/block-editor' );
useEffect( () => {
    return () => {
        toggleBlockHighlight( blockClientId, false );
    };
}, [ blockClientId ] );

// const toggleBlockHighlight = useToggleBlockHighlight( blockClientId );
```

Test Failure:
```
  ● List › should undo asterisk transform with backspace after mouse move

    expect(received).toMatchSnapshot()

    Snapshot name: `List should undo asterisk transform with backspace after mouse move 1`

    - Snapshot  - 3
    + Received  + 0

    - <!-- wp:paragraph -->
    - <p>* </p>
    - <!-- /wp:paragraph -->
```

**Comment by ItsJonQ** [comment]
Revisited this one. Still unsure what's up 🤔

**Comment by ellatrix** [comment]
@ItsJonQ You're right it does fix the issue.

File: packages/block-editor/src/components/block-toolbar/utils.js [hunk 1]
```diff
@@ -195,14 +195,15 @@ export function useToggleBlockHighlight( clientId ) {
 		if ( requestAnimationFrameId ) {
 			cancelAnimationFrame( requestAnimationFrameId );
 		}
+
 		return () => {
 			// Sequences state change to enable editor updates (e.g. cursor
 			// position) to render correctly.
 			requestAnimationFrameId = requestAnimationFrame( () => {
```
Comment (ellatrix) [inline packages/block-editor/src/components/block-toolbar/utils.js:202]: Where is this cancelled?

Comment (ItsJonQ) [reply packages/block-editor/src/components/block-toolbar/utils.js:202]: @ellatrix I don't think we need the RAF. I paused on this for now, as regardless of whether I use RAF or not, a couple of particular E2E tests keep failing. They fail when they attempt to use the `toggleBlockHighlight` action in a `useCallback` return.

**Comment by ItsJonQ** [comment]
@ellatrix Haii! @youknowriad and I hopped on a call to debug this. I think we discovered the issue.

The `useIsAccessibleToolbar` hook within `packages/block-editor/src/components/navigable-toolbar/index.js` appears to be causing the inner `<Toolbar />` to be mounting twice on render. The side-effect of this is that it causes the highlight `useEffect` to be unreliable.

The reason why it's double mounting is because it starts with an accessibility state of `false`, which is flipped to `true` after a `useLayoutEffect` check.

To make the tests happy, we opted to use a default accessibility state of `true`, to avoid to double render. This appears to make the (previously failing) E2E test happy. There is no different we can see or feel when using the editor in real life.

cc'ing @diegohaz . Haii! It would be great to get your quick thoughts on the solution we went with. I know you've done extensive and wonderful work on the Toolbar 🙏 

Thank you all ❤️

**Comment by diegohaz** [comment]
@ItsJonQ I agree with defaulting the accessible state of the navigable toolbar to `true`. It was set to `false` just because, when it was implemented, most of the toolbars were using the old behavior. 👍

File: packages/block-editor/src/components/navigable-toolbar/index.js [hunk 2]
```diff
@@ -35,11 +35,27 @@ function focusFirstTabbableIn( container ) {
 }
 
 function useIsAccessibleToolbar( ref ) {
+	/*
+	 * By default, we'll assume the starting accessible state of the Toolbar
+	 * is true, as it seems to be the most common case.
+	 *
+	 * Transitioning from an (initial) false to true state causes the
+	 * <Toolbar /> component to mount twice, which is causing undesired
```
Comment (ellatrix) [inline packages/block-editor/src/components/navigable-toolbar/index.js:43]: Mount or render?

File: packages/block-editor/src/components/block-toolbar/utils.js [hunk 3]
```diff
@@ -181,28 +175,13 @@ let requestAnimationFrameId;
...
-		}
-		return () => {
-			// Sequences state change to enable editor updates (e.g. cursor
-			// position) to render correctly.
-			requestAnimationFrameId = requestAnimationFrame( () => {
-				updateBlockHighlight( false );
-			} );
-		};
-	}, [] );
+		return () => toggleBlockHighlight( clientId, false );
```
Comment (ellatrix) [inline packages/block-editor/src/components/block-toolbar/utils.js:183]: Why are we toggling block highlight in an effect rather than at the reducer level? For a SELECT_BLOCK action etc., the highlight state should change immediately. Cc @youknowriad.

Comment (youknowriad) [reply packages/block-editor/src/components/block-toolbar/utils.js:183]: I agree that if we can do it automatically on the reducer, it's better and avoid an extra rerenders for all components.

File: packages/block-editor/src/components/navigable-toolbar/index.js (hunk 2 above)
Comment (youknowriad) [reply packages/block-editor/src/components/navigable-toolbar/index.js:43]: mount :)

Comment (ellatrix) [reply packages/block-editor/src/components/navigable-toolbar/index.js:43]: I wonder if this is still needed after the adjustments I made?

**Comment by ItsJonQ** [comment]
OMG @ellatrix ! That did it! You are amazing 🙏 . Thank you so much!!!

**Comment by ItsJonQ** [comment]
I retested it locally, and it looks like it's working for me! 

With things working and E2E happy, I'll merge this up!

Thank you @ellatrix , @youknowriad , and @diegohaz for all of your help!!!! <3
