### PR TITLE
Update fixed block toolbar

### LINKED ISSUE #51711: Top Toolbar: Refine icons and handle document title
When the top toolbar option is selected and you select a block, the document title in the site editor awkwardly overlaid. It should be hidden when a block is selected:

Responsive scheme

Note also that in this mode to enable the extra space necessary, the mockups here hide the Tools selector. 

Additionally, the expand/collapse icons have been updated to double-chevrons, where we can use these:

Screenshot 2023-06-23 at 12 45 48

---

<details><summary>Initial issue</summary>

## What problem does this address?
With the changes in https://github.com/WordPress/gutenberg/issues/40450, the top toolbar can now become very large, to the point where it overlaps the command center:

Screenshot 2023-06-20 at 16 55 30

## What is your proposed solution?
One option worth exploring is having items moving into/out of the ellipsis menu in the toolbar, as more/less space is available. This would require nested toolbars:

Screenshot 2023-06-20 at 17 00 08

</details>

### PR DESCRIPTION
**Pull request by draganescu**
## What?

Closes #51711

## Why?

To improve the UX of using fixed block toolbar by:

- making the icons more clearly convey the result of collapse and expand action on the fixed toolbar
- allowing undo and redo to always be available
- saving some space

## How?

- [x] Update the icons for the expand and collapse buttons
- [x] Hide the Tools item in document tools when top toolbar preference is on
- [x] Move the position of the top toolbar to uncover undo and redo

## Testing Instructions

- In the site editor
- Toggle the top toolbar preference to on from the dot menu in the top right corner
- Select a block
- The block toolbar should have the new double horizontal chevron collapse and expand icons
- The block toolbar should not cover the undo and redo items in the document tools
- The Tools item in the document tools should be hidden

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/107534/e2ec1e7f-045a-47ac-bfe6-e3dd85338aec

### CODE REVIEW

**Comment by jasmussen** [comment]
Great first step, thanks for working on this:

top toolbar

The double chevrons work well here. I'd love to animate them in the future.

I think the important next piece is uncovering undo/redo! Thanks Andrei.

**Comment by draganescu** [comment]
@jasmussen it's kinda complete. The show button labels preference really needs some love. I think you did a great job polishing this interaction, it makes a lot more sense now! 👏🏻 Let me know how it tests for you.

Edit: The collapsing in the post editor is a bit useless as things stand now ...

**Comment by jasmussen** [comment]
Awesome work, this is feeling very good to me, I think this fixes the pressing issues while keeping the core of it.

A few small things; this vertical separator:

Screenshot 2023-06-29 at 19 27 16

It's both a little tall, and hanging a bit low. Essentially it should be identical in placement and height as the separator that sits between toolbar groups:

Screenshot 2023-06-29 at 19 27 32

Secondly, I agree we can do better with the tooltips. Here's "Show block tools":
Screenshot 2023-06-29 at 19 27 21

Here's "Show document tools".

Since the top toolbar is always going to be about document tools, and since we are leaning into the expand/collapse pattern of the chevrons, how about we just go with:

* Show block tools
* Hide block tools

Then it's essentially _one button_ with tooltips describing its state. Since that is already how focus is handled (it stays on the same button), it would seem a better switchup of the tooltips, keeping the topic the same.

**Comment by scruffian** [comment]
We have an option in the editor called `Show button text labels`. With that enabled the chevron should have text:

Screenshot 2023-06-30 at 11 42 34

I also see some weird overlapping stuff:

Screenshot 2023-06-30 at 11 42 50

File: packages/edit-site/src/components/header-edit-mode/index.js [hunk 1]
```diff
@@ -108,6 +108,9 @@ export default function HeaderEditMode() {
 		};
 	}, [] );
 
+	const { get: getPreference } = useSelect( preferencesStore );
+	const hasFixedToolbar = getPreference( editSiteStore.name, 'fixedToolbar' );
```
Comment (scruffian) [inline packages/edit-site/src/components/header-edit-mode/index.js:112]: Should we make this a hook so we can share the code?

File: packages/block-editor/src/components/block-tools/style.scss [hunk 2]
```diff
@@ -186,8 +206,8 @@
 					margin-bottom: $grid-unit + $grid-unit-05;
 					background-color: $gray-300;
 					position: relative;
-					left: -12px; //the padding of buttons
-					height: 24px;
+					left: -10px; //the padding of buttons
```
Comment (scruffian) [inline packages/block-editor/src/components/block-tools/style.scss]: Is this still the padding of buttons?

File: packages/block-editor/src/components/block-tools/style.scss [hunk 3]
```diff
@@ -186,8 +206,8 @@
...
+					height: 26px;
```
Comment (scruffian) [inline packages/block-editor/src/components/block-tools/style.scss]: Should we make 26px a variable?

**Comment by jasmussen** [comment]
I think we should probably hide the zoom out mode buttons in this context. I don't actually expect the environment to graduate as is, and most likely it won't have a button in the toolbar if it does.

File: packages/edit-site/src/components/header-edit-mode/index.js (hunk 1 above)
Comment (draganescu) [reply packages/edit-site/src/components/header-edit-mode/index.js:112]: To me a two liner is not worth a hok. I would be if the two liner would be some arcane expression or something but this is really basic.

**Comment by jasmussen** [comment]
> We have an option in the editor called Show button text labels. With that enabled the chevron should have text:

I would not let this block this PR. The text labels mode is lacking in other contexts too, such as the inspector.

File: packages/block-editor/src/components/block-tools/style.scss (hunk 2 above)
Comment (draganescu) [reply packages/block-editor/src/components/block-tools/style.scss]: It's not, its pure CSS whack'a'mole, removing the comment.

File: packages/block-editor/src/components/block-tools/style.scss (hunk 3 above)
Comment (draganescu) [reply packages/block-editor/src/components/block-tools/style.scss]: I can make it in grid units

**Comment by draganescu** [comment]
@scruffian ready for a new review :)

**Comment by scruffian** [comment]
This is almost there, the only thing I noticed is that when you have text labels and you hide the block tools, you see this:

Screenshot 2023-06-30 at 14 51 57

**Comment by scruffian** [comment]
Actually sorry I found another few things on smaller screens:

Screenshot 2023-06-30 at 14 54 37

Screenshot 2023-06-30 at 14 54 50

Screenshot 2023-06-30 at 14 54 55

This is in Firefox (Chrome looks ok).

**Comment by draganescu** [comment]
@scruffian @jasmussen I've updated the command center button to be smalller on small viewports. I've also made the toolbar scrollable so we avoind as much as possible visible overlapped elements. I've hidden all document tools when show butotn labels is toggled on in the site editor (they're also hidden in the post editor).

The option to show button labels really needs its own PR. There's multiple ways to make it look borked.


https://github.com/WordPress/gutenberg/assets/107534/d273c83a-c4a6-49b1-b2d2-1cef2dedec8f

**Comment by scruffian** [comment]
I can still see some strange overlapping behaviour at some breakpoints:

Screenshot 2023-07-04 at 13 24 47
Screenshot 2023-07-04 at 13 24 31

I'm happy to go ahead and merge this if you want to deal with them in a followup?

**Comment by draganescu** [comment]
There is no immediate solution, the way we manage the UX is with fixed breakpoints for mobile, tablet, desktop and large desktop. It's likely inbetween there will be overlapping. The only way to fix this is to have a flex container and a way for the scrollbar to overflow nicely. We don't - at least yet.

**Review by scruffian — APPROVED** [review]
Let's bring this in and then iterate on it with bug fixes.

File: packages/edit-post/src/components/header/header-toolbar/index.js [hunk 4]
```diff
@@ -36,6 +37,8 @@ function HeaderToolbar() {
 	const inserterButton = useRef();
 	const { setIsInserterOpened, setIsListViewOpened } =
 		useDispatch( editPostStore );
+	const { get: getPreference } = useSelect( preferencesStore );
+	const hasFixedToolbar = getPreference( 'core/edit-post', 'fixedToolbar' );
```
Comment (Mamaduka) [inline packages/edit-post/src/components/header/header-toolbar/index.js:41]: This isn't a good way to use selectors when value is used during the render. When the `fixedToolbar` preference value changes, this won't rerender the component.

Let's make it part of the `useSelect` below.

File: packages/edit-site/src/components/header-edit-mode/index.js (hunk 1 above)
Comment (Mamaduka) [reply packages/edit-site/src/components/header-edit-mode/index.js:112]: The same comment as above - https://github.com/WordPress/gutenberg/pull/52123/files#r1252980401.

**Comment by Mamaduka** [comment]
I found one minor design issue. The toolbar overlaps the "Saved" status button in the post editor.

## Screenshot

CleanShot 2023-07-05 at 15 49 19

File: packages/edit-post/src/components/header/header-toolbar/index.js (hunk 4 above)
Comment (scruffian) [reply packages/edit-post/src/components/header/header-toolbar/index.js:41]: I made a PR for this: https://github.com/WordPress/gutenberg/pull/52332

Comment (Mamaduka) [reply packages/edit-post/src/components/header/header-toolbar/index.js:41]: There's another one in `packages/edit-site/src/components/header-edit-mode/index.js`, let fix both in one go :)

Comment (scruffian) [reply packages/edit-post/src/components/header/header-toolbar/index.js:41]: done

**Comment by draganescu** [comment]
oh @Mamaduka the joy of this implementation 👯

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the update/first-pre-beta-4 branch to get it included in the next release: 73987713f4

**Comment by ktmn** [comment]
Post editor - overlaps Update button when plenty of space is available:
image

**Comment by draganescu** [comment]
@ktmn there is an incoming fix for the post editor. Thanks for the testing! 👏🏻
