### PR TITLE
Fixture Tests: Correctly generate fixture files for form-related blocks

### LINKED ISSUE #56590: Form Blocks: Ensure fixtures are generated correctly
### Description

_Note: This issue was discovered in #56507 when trying to add deprecation to the Input Field block._

There are four blocks related to the form:

- Form (`core/form`)
- Input Field (`core/form-input`)
- Form Submission Notification (`core/form-submission-notification`)
- Form Submit Button (`core/form-submit-button`)

There are two fixture files for these blocks:

- [core__form](https://github.com/WordPress/gutenberg/blob/e7ebdcf9fb61a729a20c83bbf1baf7a511850268/test/integration/fixtures/blocks/core__form.html)
- [core__form-input](https://github.com/WordPress/gutenberg/blob/e7ebdcf9fb61a729a20c83bbf1baf7a511850268/test/integration/fixtures/blocks/core__form-input.html)

However, in the json file that represents the expected representation, it is recognized as a `core/missing` block.

https://github.com/WordPress/gutenberg/blob/e7ebdcf9fb61a729a20c83bbf1baf7a511850268/test/integration/fixtures/blocks/core__form.json#L3
https://github.com/WordPress/gutenberg/blob/e7ebdcf9fb61a729a20c83bbf1baf7a511850268/test/integration/fixtures/blocks/core__form-input.json#L3

As a result, deprecation will not work and serialized markup will not be generated correctly.

The cause of this is due to various factors, and I believe that the following two issues need to be resolved in order to generate the fixture file correctly.

## Full post content test does not register experimental blocks

In the `full-content.test.js` file, all core blocks are registered via [registerCoreBlocks()](https://github.com/WordPress/gutenberg/blob/e7ebdcf9fb61a729a20c83bbf1baf7a511850268/test/integration/full-content/full-content.test.js#L66). However, the blocks related to the form are experimental and [will not be registered](https://github.com/WordPress/gutenberg/blob/e7ebdcf9fb61a729a20c83bbf1baf7a511850268/packages/block-library/src/index.js#L235-L240) unless you explicitly opt-in in the Experimental settings.

As a result, the fixture test treats it as a non-existent block, which is the first cause.

We need to somehow register blocks related to the form that are not registered via `registerCoreBlocks()` in our fixture tests.

## The behavior of the save function of the Input Field block is different in the fixture test

The Input Field block attempts to generate a `name` attribute from its `label` in the `save()` function when the `name` attribute does not exist. This is handled via the [getNameFromLabel()](https://github.com/WordPress/gutenberg/blob/e7ebdcf9fb61a729a20c83bbf1baf7a511850268/packages/block-library/src/form-input/save.js#L23-L36) function. Inside this function, we create a dummy element that contains the label string, and generate an appropriate `name` attribute from its `innerText`.

However, if we assume that the Input Field block is registered in the fixture test, this process will result in an error.

```
TypeError: Cannot read properties of undefined (reading 'replace')

  26 |      // Get the slug.
  27 |      return (
> 28 |              removeAccents( dummyElement.innerText )
     |                           ^
  29 |                      // Convert anything that's not a letter or number to a hyphen.
  30 |                      .replace( /[^\p{L}\p{N}]+/gu, '-' )
  31 |                      // Convert to lowercase
```

If we don't generate a dummy element and replace it with logic that removes the HTML tag, the fixture test should pass.

### Step-by-step reproduction instructions

N/A

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #56590
This issue was discovered in this comment: https://github.com/WordPress/gutenberg/pull/56507#issuecomment-1827856129

## What?
This PR will ensure that the fixture files for the following two blocks are generated correctly.

- `test/integration/fixtures/blocks/core__form-input.html`
- `test/integration/fixtures/blocks/core__form.html`

Additionally, this PR creates fixture files for form-related blocks that do not yet exist.

- `test/integration/fixtures/blocks/core__form-submission-notification.html`
- `test/integration/fixtures/blocks/core__form-submit-button.html`

## Why?

These blocks are not available unless you explicitly opt-in on the Experimental Settings page. In other words, in fixture tests, it is excluded from the blocks registered with the `registerBlocks()` function.

As a result, even if you create a fixture file, that block will be considered a `core/missing` block and will not generate a correct serialized file that has passed deprecation.

## How?

- Explicitly registered these blocks in fixture tests.
- In the form-input block, the `getNameFromLabel()` function no longer depends on the `document` object to avoid fixture test failures. (See the "The behavior of the save function of the Input Field block is different in the fixture test" section in [#56590](https://github.com/WordPress/gutenberg/issues/56590) for details.)
- Regarding the two existing fixture files, the original HTML markup was invalid, so I fixed it.

## Testing Instructions

Confirm that the form-input block's save function outputs exactly the same markup as before.

- Switch to trunk branch.
- Insert a form-input block.
- Decorate the label with bold text, links, etc., and save the post.
- Switch to this PR and reload the post.
- The block should not break.

### CODE REVIEW

File: phpunit/class-block-fixture-test.php [hunk 1]
```diff
@@ -7,6 +7,12 @@
 
 class Block_Fixture_Test extends WP_UnitTestCase {
 
+	public function filter_allowed_html( $tags ) {
+		$tags['form']['class']   = true;
+		$tags['form']['enctype'] = true;
+		return $tags;
+	}
```
Comment (t-hamano) [inline phpunit/class-block-fixture-test.php:14]: The `wp_kses_post()` function does not allow `form` tag [by default](https://github.com/WordPress/wordpress-develop/blob/0ce733c78f86c4ea06dd0dde329fcca571179f50/src/wp-includes/kses.php#L153-L167). So we need to allow attributes to be included in the serialized form block.

File: test/integration/full-content/full-content.test.js [hunk 2]
```diff
@@ -35,6 +35,13 @@ import {
 	writeBlockFixtureSerializedHTML,
 } from '../fixtures';
 
+/* eslint-disable no-restricted-syntax */
+import * as form from '@wordpress/block-library/build-module/form';
+import * as formInput from '@wordpress/block-library/build-module/form-input';
+import * as formSubmitButton from '@wordpress/block-library/build-module/form-submit-button';
+import * as formSubmissionNotification from '@wordpress/block-library/build-module/form-submission-notification';
+/* eslint-enable no-restricted-syntax */
```
Comment (t-hamano) [inline test/integration/full-content/full-content.test.js]: If you have a better approach than this, please let me know.

**Review by aristath — APPROVED** [review]
Thank you @t-hamano!
LGTM 👍
