### PR TITLE
Theme: Fix design-tokens.js entrypoint to specify types and CJS variants

### LINKED ISSUE #73096: Theme: Add full typings for all entrypoints
## What problem does this address?

Currently, if an external project that uses TypeScript tries to import some of `@wordpress/theme`'s entrypoints, they will emit an error because there are no types associated with those files.

```ts
import tokenList from '@wordpress/theme/design-tokens.js';
// error TS7016: Could not find a declaration file for module '@wordpress/theme/design-tokens.js'
```

## What is your proposed solution?

All of the `@wordpress/theme` entrypoints should be fully-typed.

In practice, this means that the `design-tokens.js` should define an object of exports including `types`, similar to what's done with the primary entrypoint.

https://github.com/WordPress/gutenberg/blob/154a95a1e0a14ed1e5976d7c3279926007fc8f84/packages/theme/package.json#L28-L34

### PR DESCRIPTION
**Pull request by aduth**
## What?

Closes #73096

Updates `@wordpress/theme` package exports to correctly specify variants for the `/design-tokens.js` entrypoint.

## Why?

So that TypeScript can resolve the types, and presumably so this can be used in a CommonJS project environment which isn't compatible with loading the ESM variant of the package.

## How?

The `.d.ts` and `.cjs` files were already being built, we just needed to update the `package.json` to point to them, consistent with the `"."` main entrypoint.

Also includes a few semi-related housekeeping tasks:

- Avoids using DocBlock syntax for prebuilt file headers, since otherwise these will be picked up by TypeScript and used incorrectly to describe the return value of the default export.
- Updates the name of the Terrazzo plugin that generates this file to use `@wordpress/` as its scope, for consistency with other custom plugins, and because it's within the WordPress scope (not Terrazzo). These plugins aren't actually published anywhere, but if they were, we'd use the WordPress organization. We're not affiliated with Terrazzo.

## Testing Instructions

Verify improvement using [the "Are the types wrong?" site](https://arethetypeswrong.github.io/):

1. Build packages: `npm run build`
2. Change into the theme directory: `cd packages/theme`
3. Pack the package: `npm pack`
4. Upload the generated zip file to [the "Are the types wrong?" site](https://arethetypeswrong.github.io/)
5. Observe that the `/design-tokens.js` files are resolved in Node.js 16+
6. On the site, enter `@wordpress/theme` as the package name and click "Check"
7. Observe that the result for the published package is much worse, and `/design-tokens.js` doesn't resolve at all

## Screenshots or screencast 

Before|After
---|---
Screenshot 2025-12-19 at 2 04 30 PM|Screenshot 2025-12-19 at 2 04 21 PM

### CODE REVIEW

File: packages/theme/src/prebuilt/ts/token-types.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
-/**
+/*
```
Comment (SirLouen) [inline packages/theme/src/prebuilt/ts/token-types.ts:1]: This

File: packages/theme/src/prebuilt/ts/color-tokens.ts [hunk 2]
```diff
@@ -1,4 +1,4 @@
-/**
+/*
```
Comment (SirLouen) [inline packages/theme/src/prebuilt/ts/color-tokens.ts:1]: This

File: packages/theme/bin/terrazzo-plugin-typescript-types/index.ts [hunk 3]
```diff
@@ -102,7 +102,7 @@ export default function typescriptTypes( {
 		},
 		async build( { outputFile } ) {
 			const outputLines = [
-				'/**',
+				'/*',
```
Comment (SirLouen) [inline packages/theme/bin/terrazzo-plugin-typescript-types/index.ts:105]: This

File: packages/theme/bin/terrazzo-plugin-inline-alias-values/index.ts [hunk 4]
```diff
@@ -99,7 +99,7 @@ export default function inlineAliasValues( {
 			outputFile(
 				filename,
 				[
-					'/**',
+					'/*',
```
Comment (SirLouen) [inline packages/theme/bin/terrazzo-plugin-inline-alias-values/index.ts:102]: This

**Review by SirLouen — CHANGES_REQUESTED** [review]
I think all these changes have been added erroneously, as this must be autogen?

**Comment by aduth** [comment]
@SirLouen Those changes were intentional. I included a note in the original pull request message about them:

>Avoids using DocBlock syntax for prebuilt file headers, since otherwise these will be picked up by TypeScript and used incorrectly to describe the return value of the default export.

I could have been more clear that the difference of the extra `*` is enough to change its meaning from "this is just a simple multi-line comment" (`/*`) to "this is a DocBlock that describes the thing that follows it" (`/**`).

**Comment by SirLouen** [comment]
> > Avoids using DocBlock syntax for prebuilt file headers, since otherwise these will be picked up by TypeScript and used incorrectly to describe the return value of the default export.

Ok, I thought this files were autogen, so basically they could be rewritten at any point with the original  `/**` 

PS: My bad, they are actually the generator.

**Review by SirLouen — APPROVED** [review]

**Review by mirka — APPROVED** [review]
Looks good 👍

**Comment by aduth** [comment]
I had to rebase to account for the new exports in #74226, though based on the build failures it may end up being more involved. Originally we pointed to the `/src` files, but I don't think that'll necessarily work if we're not providing a fallback for CommonJS projects. Using `build` artifacts is typically what we'd want to do, but many of the CI tasks don't seem set up to pre-build packages to make those artifacts available.

**Comment by aduth** [comment]
c99b7cbd5b066d95da3b62d3ce80d04e60af932e switches the `import` source back to what it was previously, effectively matching the prior behavior (since `import` is what matches in this project). This should be fine since the source content is valid ESM JavaScript, but as mentioned in https://github.com/WordPress/gutenberg/pull/74226#discussion_r2653035390 we might want to eventually port this to TypeScript, so we'll need to figure out the build prerequisite at that point.
