### PR TITLE
Custom Fields option: Add confirmation step

### LINKED ISSUE #15320: Custom field check box automatically changes the context on user focus
Custom field check box automatically changes the context on user focus 

-   **Severity:** High
-   **Affected Populations:**
    -   Blind
    -   Low-Vision
    -   Motor Impaired
    -   Cognitively Impaired
-   **Platform(s):**
    -   All / Universal
-   **Components affected:**
    -   Tools and Options

#### Issue description

The "Custom Fields" checkbox within the "Options" dialog causes an
unexpected page refresh when the user selects it, and consequently
resets the focus position to the top of the page.

This is not expected behaviour for checkboxes, and the sudden change of
context may be confusing for assistive technology users, while the loss
of focus position will force keyboard users to manually navigate back to
where they were before.

#### Remediation Guidance

If it's not possible to update the page in the background, as happens
with other checkboxes in the "Options" dialog, then the user should be
warned (with visible text, not visually-hidden) that selecting this
option will close the options dialog and reload the page.

Alternatively, an "Apply Changes" button could be added to the dialog,
which confirms the user's changes for all checkboxes (i.e. none of the
checkboxes cause background updates or page reloads until the user
explicitly presses the Apply button).

#### Relevant standards

-   [3.2.5 Change on Request (Level
    AAA)](https://www.w3.org/TR/WCAG20/#consistent-behavior-no-extreme-changes-context)

**Note:** This issue may be a duplicate with other existing accessibility-related bugs in this project. This issue comes from the Gutenberg accessibility audit, performed by [Tenon](https://www.tenon.io) and funded by [WP Campus](https://wpcampus.org/). This issue is GUT-65 in Tenon's report

### PR DESCRIPTION
**Pull request by marekhrabe**
Fixes #15320.

"Custom Fields" in Options modal requires a full page reload in order to toggle the option. Currently, this happens instantly after clicking the checkbox. 

This PR changes the flow to add an inline confirmation step:

see the latest version https://github.com/WordPress/gutenberg/pull/15688#issuecomment-515697517

### CODE REVIEW

**Comment by marekhrabe** [comment]
Update:

This PR shows additional message about a reload and a confirmation button to proceed. This additional UI only shows when a reload action is required and disappears when you change your mind and toggle the option back without a confirmation. It is additionally announced with spoken messages to differentiate the tickbox from all others which save options instantly.

It's not well styled and polished at this point. Let's figure out a proper interaction first.

Question: Do spoken messages make sense here? If so, what would their formulations be? I'm sure I haven't came up with the most ideal copy.

If we confirm this approach is a way forward, I can take a look at styling, making string translatable etc…

**Comment by noisysocks** [comment]
I can't answer the question about using `speak()`, but functionally I think this is the right approach!

I added the `Needs Design` label so that the design team can offer some suggestions. Personally I'd advocate for something relatively inline and unobtrusive.

Screen Shot 2019-05-27 at 11 22 06

(The link would be a `<Button>` with `isLink`.)

**Comment by mapk** [comment]
Oh dang, turns out I added a redesign to the issue and not the PR. In case people don't want to click around, here's the proposed redesign.

Screen Shot 2019-05-28 at 6 58 44 PM

I'm not entirely sure if the notification should be `blue` or `yellow`. Any thoughts on that?

**Comment by mapk** [comment]
Okay, because this is more of a warning notification, let's go with a yellow version.

Screen Shot 2019-05-29 at 10 07 20 AM

**Comment by afercia** [comment]
Discussed during today's accessibility bug scrub. Quick feedback: if there’s text with relevant information and if the button says “Save and Reload” there’s no need for a spoken message.

**Comment by noisysocks** [comment]
confirmation

I've rebased this, removed the `speak()` commands, and changed the UI to look like the mockup posted above.

It was a little tricky getting everything to line up nicely. I ended up using CSS grid for this. @mapk, let me know what you think and feel free to make any adjustments to the styling.

File: packages/components/src/checkbox-control/index.js [hunk 1]
```diff
@@ -27,6 +37,7 @@ function CheckboxControl( { label, className, heading, checked, help, instanceId
 			<label className="components-checkbox-control__label" htmlFor={ id }>
 				{ label }
 			</label>
+			{ children }
```
Comment (noisysocks) [inline packages/components/src/checkbox-control/index.js]: Not sure about this change. None of the other control components have `children` as a prop.

**Comment by noisysocks** [comment]
confirmation

I've rebased this, removed the `speak()` commands, and changed the UI to look like the mockup posted above. It should be ready for a review from both a designer and developer 🙂

**Comment by karmatosed** [comment]
Can I ask why we're using an information message there and not just having as a simple extra text section? It feels a lot having even the yellow notice on that settings page. 

For example, in accessibility options this is being considered, to me, this could fit better.

**Comment by afercia** [comment]
Removed the notice style in favor of plain text. Adjusted margins. Screenshot:

Screenshot 2019-07-08 at 14 30 23

Note: when pressed, the button gets disabled with a HTML `disabled` attribute. This an exception to the pattern used in Gutenberg to avoid focus losses, as in this case there's a page reload anyways.

**Comment by mapk** [comment]
Just to jump back into this and provide devs with a more high fidelity mockup, I put one together based on both @karmatosed's and @afercia's comments. Thanks for the feedback!

I think it's still important to keep the margin for readability, but dropping the notification style makes a lot of sense here.

Screen Shot 2019-07-10 at 9 50 05 AM

**Comment by noisysocks** [comment]
Done and done!

custom-fields

This should be ready for a final code review now.

File: packages/edit-post/src/components/options-modal/options/enable-custom-fields.js [hunk 2]
```diff
@@ -1,47 +1,54 @@
...
-		);
-	}
+export function EnableCustomFieldsOption( { label, areCustomFieldsEnabled } ) {
+	const [ isChecked, setIsChecked ] = useState( areCustomFieldsEnabled );
+
+	return (
+		<BaseOption
+			label={ label }
+			isChecked={ isChecked }
+			onChange={ ( nextIsChecked ) => setIsChecked( nextIsChecked ) }
```
Comment (talldan) [inline packages/edit-post/src/components/options-modal/options/enable-custom-fields.js]: could this be simplified to `onChange={ setIsChecked }`?

File: packages/edit-post/src/components/options-modal/options/enable-custom-fields.js [hunk 3]
```diff
@@ -1,47 +1,54 @@
...
+				className="edit-post-options-modal__custom-fields-confirmation-button"
+				isDefault
+				isBusy={ isReloading }
+				disabled={ isReloading }
+				onClick={ () => {
+					setIsReloading( true );
+					document.getElementById( 'toggle-custom-fields-form' ).submit();
+				} }
+			>
+				{ __( 'Save & Reload' ) }
```
Comment (talldan) [inline packages/edit-post/src/components/options-modal/options/enable-custom-fields.js]: 'Save & Reload' - clicking the button does save the change to the custom fields option, but doesn't save any other edits to the post, which may be misleading to the user and lead to lost data. I'm thinking that perhaps the post should be saved when this is clicked?

File: packages/edit-post/src/components/options-modal/options/enable-custom-fields.js [hunk 4]
```diff
@@ -1,47 +1,54 @@
...
-	render() {
-		const { label } = this.props;
-		const { isChecked } = this.state;
+export function CustomFieldsConfirmation() {
+	const [ isReloading, setIsReloading ] = useState( false );
+
+	return (
+		<>
+			<p className="edit-post-options-modal__custom-fields-confirmation-message">
+				{ __( 'Page reload is required for this change.' ) }
```
Comment (talldan) [inline packages/edit-post/src/components/options-modal/options/enable-custom-fields.js]: Very very minor, but I think this minor change makes the sentence sound a lot less terse.
```suggestion
				{ __( 'A page reload is required for this change.' ) }
```

**Review by talldan — COMMENTED** [review]
I had one big question about 'Save & Reload', so haven't approved this, but generally the code looks good. 

I know that previously clicking the custom fields option didn't save the post, but I think the messaging now will lead to some expecting that to happen.

File: packages/edit-post/src/components/options-modal/options/enable-custom-fields.js (hunk 3 above)
Comment (marekhrabe) [reply packages/edit-post/src/components/options-modal/options/enable-custom-fields.js]: In case there is unsaved content, the page won't reload automatically and will still show the "Are you sure" dialog of the browser. While this is not ideal, I think that merging this will still improve the totally unclear and inaccessible way that is shipped now. I think that mixing together post saving could become very complex (you need to wait for the request to succeed etc) and we would need to handle possible edge cases. 

Do you think that updating the label to remove the word "Save" would solve the problem in a way we can get this merged and fix the root accessibility problem? I'm thinking of making the label dynamic based on the checkbox status to reflect the exact action that will be taken — either "Enable & Reload" or "Disable & Reload".

Comment (marekhrabe) [reply packages/edit-post/src/components/options-modal/options/enable-custom-fields.js]: And/or add something in lines of "Make sure your editor content is saved before proceeding"

**Comment by karmatosed** [comment]
Can I get confirmation that this does 'save and reload'? I am reading comments and wondering if that is the case @noisysocks and @talldan. If it doesn't actually do that saying so is a little unexpected.

**Comment by mapk** [comment]
> I know that previously clicking the custom fields option didn't save the post, but I think the messaging now will lead to some expecting that to happen.

I believe the "save" refers to the setting. It's saving the setting and reloading the page. But it does cause confusion when the help text says that "A *page* reload is required" and then the button implies a "Save and load" as if referring to the _page_.

Maybe we can adjust the language of the button? Here are some ideas:

`Submit`
`Agree`
`Acknowledge`
`Reload`
`Do it`

Any other thoughts?

**Comment by talldan** [comment]
Agree that adjusting the wording would be a good compromise to get this merged. I like @marekhrabe's suggestions in the comment above, or just shortening it to 'Reload' / 'Reload now'. 

Could it also be worth adding something to the main part of the message? e.g. 'A page reload is required for this change, please save any changes to your content before reloading.'

**Comment by mapk** [comment]
> "Enable & Reload" or "Disable & Reload"

Oh, I missed these. I prefer them over my suggestions. Thanks!

> Could it also be worth adding something to the main part of the message? e.g. 'A page reload is required for this change, please save any changes to your content before reloading.'

If handling the save of the document automatically before reloading gets tricky, this seems like the right solution. And if they miss that text and trigger the reload anyways, alerting them with an "Are you sure" message as @marekhrabe suggested works too.

**Comment by marekhrabe** [comment]
> "Enable & Reload" or "Disable & Reload"

I have implemented these in 8320d22c83a3d51ae5d14500a002698173e84aaf

> And if they miss that text and trigger the reload anyways, alerting them with an "Are you sure" message as @marekhrabe suggested works too.

"Are you sure" functionality is done on a global level and it is already triggering for this option. 

I have added an extra sentence to the info message about saved content.

# Current State

Screenshot 2019-07-27 at 09 37 12

Screenshot 2019-07-27 at 09 37 01

With unsaved content:

Screenshot 2019-07-27 at 09 37 31

**Comment by marekhrabe** [comment]
All tests now account for new labels. Are we good to go with this state https://github.com/WordPress/gutenberg/pull/15688#issuecomment-515697517?

File: packages/edit-post/src/components/options-modal/options/enable-custom-fields.js [hunk 5]
```diff
@@ -1,47 +1,54 @@
...
+				className="edit-post-options-modal__custom-fields-confirmation-button"
+				isDefault
+				isBusy={ isReloading }
+				disabled={ isReloading }
+				onClick={ () => {
+					setIsReloading( true );
+					document.getElementById( 'toggle-custom-fields-form' ).submit();
+				} }
+			>
+				{ nextState === true ? __( 'Enable & Reload' ) : __( 'Disable & Reload' ) }
```
Comment (noisysocks) [inline packages/edit-post/src/components/options-modal/options/enable-custom-fields.js]: This could be simplified.

```suggestion
				{ nextState ? __( 'Enable & Reload' ) : __( 'Disable & Reload' ) }
```

File: packages/edit-post/src/components/options-modal/options/enable-custom-fields.js [hunk 6]
```diff
@@ -1,47 +1,54 @@
...
-		document.getElementById( 'toggle-custom-fields-form' ).submit();
-
-		// Make it look like something happened while the page reloads.
-		this.setState( { isChecked: ! this.props.isChecked } );
-	}
-
-	render() {
-		const { label } = this.props;
-		const { isChecked } = this.state;
+export function CustomFieldsConfirmation( { nextState } ) {
```
Comment (noisysocks) [inline packages/edit-post/src/components/options-modal/options/enable-custom-fields.js]: Am thinking something like `willEnable` is a more descriptive name for this prop, but it's not a big deal since this component is only used in this file.

**Review by noisysocks — APPROVED** [review]
The code changes look good, and this tests well. Thanks for the assist @marekhrabe!

I'll leave it for @mapk to give the final say on whether the design and copy are ready to be merged.

File: packages/edit-post/src/components/options-modal/options/enable-custom-fields.js (hunk 6 above)
Comment (marekhrabe) [reply packages/edit-post/src/components/options-modal/options/enable-custom-fields.js]: It took me the longest time to come up with the bad name. `willEnable` is 💯

**Comment by mapk** [comment]
I gave it another go. The added sentence looks great! Thanks everyone for helping out with this one. :shipit:

**Review by mapk — APPROVED** [review]
:shipit: Looks good!

**Comment by marekhrabe** [comment]
This PR has truly been a journey 😀Thanks everybody!

**Comment by marekhrabe** [comment]
I just saw this featured as one of the tips about Gutenberg on Twitter 😀 

https://twitter.com/editorskit/status/1178693225923497984
