### PR TITLE
Embed: Fix Flickr double-padding with responsive wrapper

### LINKED ISSUE #49320: Flickr Embed: White space above video with 'Resize for smaller devices' on
### Description

With 'Resize for smaller devices' on, Flickr Embed Block creates an extra white space above the video.

(Turning off 'Resize for smaller devices' fixes the issue. Also, even with this option off, the aspect of videos is kept properly on smaller devices.)

### Step-by-step reproduction instructions

1. Create a new page.
2. Add a Flickr Block and link a video.
3. Make sure 'Resize for smaller devices' is turned ON in the Media settings on the block. (It is on by default)
4. Publish the page.

### Screenshots, screen recording, code snippet

Markup on 2023-03-23 at 16:38:07

### Environment info

- WordPress 6.1.1
- Gutenberg 15.4
- FireFox 111.0.1
- Zoologist theme

Originally reported here: https://github.com/Automattic/wp-calypso/issues/74083

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by annezazu**
Fixes #49320

## Summary

Flickr video embeds displayed unwanted white space above the video when "Resize for smaller devices" was enabled (default setting). This was caused by Flickr's oEmbed response including its own responsive wrapper with `padding-bottom: 56.25%`, while Gutenberg was also adding its own responsive aspect ratio styling via CSS pseudo-element `padding-top: 56.25%`, resulting in double padding.

### Modified Files:
- `packages/block-library/src/embed/util.js`
- `packages/block-library/src/embed/test/index.js`

### Implementation:

1. **Added `hasResponsiveWrapper()` function** to detect when embed HTML already contains responsive aspect ratio styling (padding-top/padding-bottom percentages)

2. **Modified `getClassNames()` function** to skip adding Gutenberg's aspect ratio classes when the embed provider has already included responsive wrapper styling

3. **Added comprehensive test coverage** for the new functionality

## How to Test

1. Create a new post/page
2. Add a Flickr embed block with URL: `https://flic.kr/p/2gthFp5`
3. Ensure "Resize for smaller devices" is ON (default)
4. **Expected:** Video displays with no white space above it
5. **Verify:** Toggle "Resize for smaller devices" OFF - video should still display correctly
6. **Regression test:** Add YouTube/Vimeo embeds to ensure they still work correctly

### Root Cause:
Flickr's oEmbed HTML structure:
```html
<div style="padding-bottom: 56.25%;">
    <iframe style="position: absolute;" width="1024" height="576" ...></iframe>
</div>
```

Gutenberg was detecting the iframe dimensions and adding `wp-embed-aspect-16-9` and `wp-has-aspect-ratio` classes, which triggered additional `padding-top: 56.25%` via CSS, creating ~112.5% total vertical padding.

### Solution:
Detect existing responsive wrapper styling using regex pattern `/padding-(top|bottom)\s*:\s*[\d.]+%/i` and skip adding duplicate aspect ratio classes.

### ✅ No Breaking Changes
- **New Flickr embeds:** Fixed - no white space
- **New other embeds (YouTube, Vimeo, etc.):** Unchanged - continue to work correctly
- **Existing Flickr embeds:** No regression - still have the issue until manually updated
- **Generic solution:** Prevents double-padding for any embed provider that includes responsive wrapper styling

### ⚠️ Known Limitations

**Existing Flickr embeds created before this fix will not be automatically corrected.**

This is due to an optimization in `getAttributesFromPreview()` (lines 329-331 in util.js) that skips className regeneration when:
1. The block already has aspect ratio classes, AND
2. The embed URL hasn't changed

**Workarounds for existing embeds:**
- Change the Flickr URL (even slightly) to trigger regeneration
- Remove and re-add the embed block
- Toggle "Resize for smaller devices" off (if acceptable)

**Future Enhancement:**
A separate PR could add automatic migration logic to fix existing Flickr embeds by forcing className regeneration for the Flickr provider. This was intentionally kept separate to:
1. Keep this fix focused and minimal
2. Allow for proper testing of the migration logic
3. Avoid potential performance implications of broader className regeneration

## Testing Performed

- ✅ Manual testing in local wp-env environment
- ✅ Unit tests added for `hasResponsiveWrapper()` function
- ✅ Unit tests added for Flickr double-padding scenario
- ✅ Verified YouTube and Vimeo embeds still work correctly
- ✅ Build successful

### Before Fix:
White space above Flickr video
_(Screenshot from original issue)_

### After Fix:

https://github.com/user-attachments/assets/9340c38c-9cfd-437d-afdd-cb8cf12c10cc

## Related Issues

- Closes #49320

---

**Note for reviewers:** This fix uses a generic pattern-matching approach rather than Flickr-specific logic, so it will also prevent similar double-padding issues with any other embed provider that includes responsive wrapper styling in their oEmbed HTML.

### CODE REVIEW

File: packages/block-library/src/embed/util.js [hunk 1]
```diff
@@ -195,6 +195,21 @@ export const removeAspectRatioClasses = ( existingClassNames ) => {
...
 
+/**
+ * Checks if HTML already contains responsive aspect ratio styling.
+ * Some embed providers (like Flickr) include their own responsive wrapper
+ * with padding-bottom or padding-top percentages for aspect ratio.
+ *
+ * @param {string} html The embed HTML to check.
+ * @return {boolean} True if the HTML already has responsive styling.
+ */
+export function hasResponsiveWrapper( html ) {
```
Comment (scruffian) [inline packages/block-library/src/embed/util.js]: I think this name could be more descriptive - maybe hasInlineResponsivePadding

**Review by scruffian — APPROVED** [review]
This is looking good. Just one minor comment about the name.

File: packages/block-library/src/embed/util.js (hunk 1 above)
Comment (annezazu) [reply packages/block-library/src/embed/util.js]: Thanks for reviewing! Updated this. Good call.
