### PR TITLE
Edit Site: New template creation flow.

### LINKED ISSUE #22638: Removing a Template Part dirties the entity state with inner content removed.
**Describe the bug**
Removing a Template Part from a page results in the Template Part edited to clear all inner content.  This is a 'recent' regression in behavior.  @noahtallen mentioned this is likely related to a recent PR of his (#21368 ).

**To reproduce**
1. Go to an Edtior (shown below is page editor) with full site editing experiment enabled.
2.  insert a Template Part.
3. remove the template part.
4. notice the template part is 'dirty' in the save panel, and re-inserting will result in an empty template part.

**Expected behavior**
Expect the template part to not be dirtied on removal.

**Screenshots**

deleting-template-part-bug

### PR DESCRIPTION
**Pull request by epiqueras**
## Description

This PR continues the work to make page template navigation in the editor page-centric.

#22368, #22449, and #22543 implemented functionality for navigating between pages while resolving and loading their templates. The current template switcher that lets you select from any of your templates doesn't make a lot of sense anymore.

This PR modifies the template switcher to better align with the new page-centric navigation. Now it will only show the currently resolved template and the option to overwrite it for the current page or to revert overwrites.

This means that you can have a category template for all your categories, a page template for all your pages, a post template for all your posts, and then spin up variations for specific categories, pages, or posts, with the click of a button. Then, you can revert just as easily. The GIF below demonstrates the process for a category.

Testing this PR required changing between lots of templates, and this helped catch some related bugs that were solved with a bit of hardening:

- The `lib/compat.php` hook that checks for category queries now works for both category slugs and IDs.
- The site editor now sets an empty query context when there isn't any so that stale rerenders with query blocks don't throw errors by trying to access an undefined object.
- The `useBlockSync` hook now guards against potential race conditions:

```js
// Sometimes, when changing block lists, lingering subscriptions
// might trigger before they are cleaned up. If the block for which
// the subscription runs is no longer in the store, this would clear
// its parent entity's block list. To avoid this, we bail out if
// the subscription is triggering for a block (`clientId !== null`)
// and its block name can't be found because it's not on the list.
// (`getBlockName( clientId ) === null`).
if ( clientId !== null && getBlockName( clientId ) === null )
    return;
```

## How has this been tested?

It was verified that the flow shown in the GIF works as expected and that nothing breaks or is cleared when switching between templates.

## Screenshots

gif

## Types of Changes

*New Feature:* The site editor's navigation continues to improve, and now supports spinning up variations of the current template for the current page.

## Checklist:

- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-editor/src/components/provider/use-block-sync.js [hunk 1]
```diff
@@ -119,6 +119,16 @@ export default function useBlockSync( {
...
 
 		const unsubscribe = registry.subscribe( () => {
+			// Sometimes, when changing block lists, lingering subscriptions
+			// might trigger before they are cleaned up. If the block for which
+			// the subscription runs is no longer in the store, this would clear
+			// its parent entity's block list. To avoid this, we bail out if
+			// the subscription is triggering for a block (`clientId !== null`)
+			// and its block name can't be found because it's not on the list.
+			// (`getBlockName( clientId ) === null`).
+			if ( clientId !== null && getBlockName( clientId ) === null )
```
Comment (noahtallen) [inline packages/block-editor/src/components/provider/use-block-sync.js:129]: thanks for this!

File: packages/edit-site/src/components/add-template/index.js [hunk 2]
```diff
@@ -1,91 +0,0 @@
-/**
- * WordPress dependencies
- */
-import { useSelect, useDispatch } from '@wordpress/data';
```
Comment (noahtallen) [inline packages/edit-site/src/components/add-template/index.js:4]: Interesting, so instead of creating an arbitrary template, we would now have to override the base template level-by-level on a certain page type until we get to the desired specificity? I imagine we'll want to make it easier to "zoom in really far" in one go in the future

File: packages/edit-site/src/components/editor/index.js [hunk 3]
```diff
@@ -94,14 +94,15 @@ function Editor( { settings: _settings } ) {
 		[]
 	);
 
-	const blockContext = useMemo( () => {
-		if ( ! settings.page.context.queryContext )
-			return settings.page.context;
-
-		return {
+	// Set default query for misplaced Query Loop blocks, and
```
Comment (noahtallen) [inline packages/edit-site/src/components/editor/index.js:97]: What is a "misplaced" query loop block?

File: packages/edit-site/src/components/page-switcher/index.js [hunk 4]
```diff
@@ -33,8 +33,13 @@ export default function PageSwitcher( {
 						const path = getPathFromLink( _page.link );
 						return {
 							label: _page.title.rendered,
+							type: 'page',
+							slug: _page.slug,
```
Comment (noahtallen) [inline packages/edit-site/src/components/page-switcher/index.js:37]: Is this the template slug?

File: packages/edit-site/src/components/template-switcher/index.js [hunk 5]
```diff
@@ -2,24 +2,30 @@
...
+import { Icon, home, plus, undo } from '@wordpress/icons';
 
 /**
  * Internal dependencies
  */
-import AddTemplate from '../add-template';
 import TemplatePreview from './template-preview';
 import ThemePreview from './theme-preview';
 
+const TEMPLATE_OVERRIDES = {
```
Comment (noahtallen) [inline packages/edit-site/src/components/template-switcher/index.js:23]: What's the path forward for supporting more of the possible overrides in the template hierarchy? Will we just add more keys here, or make it more dynamic?

File: packages/edit-site/src/components/template-switcher/index.js [hunk 6]
```diff
@@ -41,77 +47,97 @@ function TemplateLabel( { template, homeId } ) {
...
+	const overwriteTemplate = async () => {
+		const newTemplate = await saveEntityRecord( 'postType', 'wp_template', {
+			slug: overwriteSlug,
+			title: overwriteSlug,
+			status: 'publish',
+			content: template.content.raw,
+		} );
+		onAddTemplateId( newTemplate.id );
+	};
+	const unoverwriteTemplate = async () => {
```
Comment (noahtallen) [inline packages/edit-site/src/components/template-switcher/index.js:133]: We should probably prompt the user for confirmation before deleting a template

File: packages/edit-site/src/components/template-switcher/index.js [hunk 7]
```diff
@@ -175,15 +202,6 @@ export default function TemplateSwitcher( {
 					</>
 				) }
 			</DropdownMenu>
-			<AddTemplate
```
Comment (noahtallen) [inline packages/edit-site/src/components/template-switcher/index.js:178]: removing this will definitely break the dirty state entity e2e tests. Not sure what the best path forward is for those e2e tests considering that the UI is likely to continue changing a lot.

File: packages/edit-site/src/components/template-switcher/index.js [hunk 8]
```diff
@@ -41,77 +47,97 @@ function TemplateLabel( { template, homeId } ) {
...
+			slug: overwriteSlug,
+			title: overwriteSlug,
+			status: 'publish',
+			content: template.content.raw,
+		} );
+		onAddTemplateId( newTemplate.id );
+	};
+	const unoverwriteTemplate = async () => {
+		await apiFetch( {
+			path: `/wp/v2/templates/${ template.value }`,
```
Comment (noahtallen) [inline packages/edit-site/src/components/template-switcher/index.js:135]: Should the core/data controls handle this?

**Review by noahtallen — COMMENTED** [review]
Really cool stuff here! Not really any major concerns from me. As we've been mentioning, moving a lot of this logic into a store would make the code cleaner and separate "business logic" from the UI components a bit better. But that's a separate task. I also imagine the UI for this will eventually change, so I'm not all that concerned about how it looks or its UX. I think the main thing is adding a way to override a template in the first place

File: packages/edit-site/src/components/add-template/index.js (hunk 2 above)
Comment (epiqueras) [reply packages/edit-site/src/components/add-template/index.js:4]: There are only two levels of specificity:

- Page type, e.g., category, page, post.
- Page-specific, e.g., a specific category, specific page, specific post.

File: packages/edit-site/src/components/editor/index.js (hunk 3 above)
Comment (epiqueras) [reply packages/edit-site/src/components/editor/index.js:97]: Placed in a document without a query context.

This can also sometimes happen when switching between templates very quickly, and the rerender lags behind the context switch for some reason.

File: packages/edit-site/src/components/page-switcher/index.js (hunk 4 above)
Comment (epiqueras) [reply packages/edit-site/src/components/page-switcher/index.js:37]: The page slug.

File: packages/edit-site/src/components/template-switcher/index.js (hunk 5 above)
Comment (epiqueras) [reply packages/edit-site/src/components/template-switcher/index.js:23]: Both are viable. It depends on what templates we need to support.

File: packages/edit-site/src/components/template-switcher/index.js (hunk 6 above)
Comment (epiqueras) [reply packages/edit-site/src/components/template-switcher/index.js:133]: Yeah, I think we need to work it into the "Review Changes" sidebar somehow.

File: packages/edit-site/src/components/template-switcher/index.js (hunk 7 above)
Comment (epiqueras) [reply packages/edit-site/src/components/template-switcher/index.js:178]: Can we update them to use the API directly?

File: packages/edit-site/src/components/template-switcher/index.js (hunk 8 above)
Comment (epiqueras) [reply packages/edit-site/src/components/template-switcher/index.js:135]: Yeah

File: packages/edit-site/src/components/page-switcher/index.js (hunk 4 above)
Comment (noahtallen) [reply packages/edit-site/src/components/page-switcher/index.js:37]: 🙃 I realized that's what the variable is called, but was originally wondering if it had to do with the page page instead of the page cpt

File: packages/edit-site/src/components/template-switcher/index.js (hunk 7 above)
Comment (noahtallen) [reply packages/edit-site/src/components/template-switcher/index.js:178]: 🤔 Maybe? Like the WP API or the block-editor API? I feel like the e2e test ought to be going through real user actions at the end of the day. Otherwise, the unit tests on `useBlockSync` would be good enough, right?

File: packages/edit-site/src/components/page-switcher/index.js (hunk 4 above)
Comment (epiqueras) [reply packages/edit-site/src/components/page-switcher/index.js:37]: Well, the page page's slug is the same as the page CPT slug in this case. It's what we need to generate its specific template slug.

File: packages/edit-site/src/components/template-switcher/index.js (hunk 7 above)
Comment (epiqueras) [reply packages/edit-site/src/components/template-switcher/index.js:178]: Yeah, I agree. It's just that the UI will probably change a lot with the new designs coming up. Using the WP API, for now, would let us have some sort of safety net, without having to have significant test rewrites as we iterate.

That said, we don't have that many tests right now, I think it makes sense to update them in this PR.

File: packages/edit-site/src/components/page-switcher/index.js (hunk 4 above)
Comment (noahtallen) [reply packages/edit-site/src/components/page-switcher/index.js:37]: Ah, that makes sense

**Comment by epiqueras** [comment]
@noahtallen Can you take a look at why the tests are failing, please?

It's not even opening the inserter.

**Comment by epiqueras** [comment]
@noahtallen Fixed them! This is ready for review 🚀 🚀 🚀

**Review by noahtallen — CHANGES_REQUESTED** [review]
It's pretty incredible how flexible the entity system is. In the site editor I can open a category page showing a list of posts and update the post content of a post right from there. I can even update reusable blocks inside of post content. It's pretty cool that it works!

Overall, I think this is an improvement in that it forces you to only create templates that will actually work with your site's pages. (So you can't create dangling templates that you won't see any more.)

On the other hand, I found it difficult to navigate back to the "home page" or index template, because at first I didn't know which entity to select to see it. how easy would it be to add a "home" icon to the current homepage?

One final thing I noticed is this bug, where you can't select "All posts" after selecting "sample page":

Screen Shot 2020-05-27 at 3 11 13 PM

That console error logs every time I click "all posts".

Additionally, I noticed the whole editor screen flashes white when you navigate to "sample page" at first. Is something causing the editor component to remount?

**Comment by epiqueras** [comment]
>On the other hand, I found it difficult to navigate back to the "home page" or index template, because at first I didn't know which entity to select to see it. how easy would it be to add a "home" icon to the current homepage?

https://github.com/WordPress/gutenberg/pull/22586/commits/9ffec578930c097300475e40d6843ab2ff4863ff

>One final thing I noticed is this bug, where you can't select "All posts" after selecting "sample page":

https://github.com/WordPress/gutenberg/pull/22586/commits/864000289c94fe9a49b442d50c8aa9e22f7369eb

>Additionally, I noticed the whole editor screen flashes white when you navigate to "sample page" at first. Is something causing the editor component to remount?

Yes, the entire block list is changing. I don't see white, though; I see the editor's background color.

**Comment by noahtallen** [comment]
> Yes, the entire block list is changing

Interesting. I wasn't really expecting the toolbar and stuff to disappear when that happened.

Nice home icon. Gets the job done for now!

**Review by noahtallen — APPROVED** [review]
Approving with the expectation that designs will improve in the future and that we'll be able to clean up the code a bit more by integrating it to the edit-site store

**Comment by epiqueras** [comment]
The failed tests are unrelated. I think they are caused by an `axe` update.
