### PR TITLE
Fix Off Canvas Editor add submenu item option

### LINKED ISSUE #46553: Navigation List View: Add submenu is broken
## What problem does this address?
Since merging https://github.com/WordPress/gutenberg/pull/46541, when you try to add a submenu item using the List View, it throws an error on the second attempt:

https://user-images.githubusercontent.com/275961/207663712-a256b547-b7e1-4b23-bdac-4afafe88b1c2.mov

We should make it possible to add as many submenu items as you like.

### PR DESCRIPTION
**Pull request by talldan**
## What?
Fixes #46553

## Why?
This feature stopped working as a side effect of not passing the entire block data through the off canvas list view.

## How?
Use a selector to get the block information from the block editor store.

I've also changed a minor aspect of how this feature works. It was originally creating a new submenu block every time, even when the block was already a submenu block. That's a little inefficient, as it'll result in the block getting a new client id.

If the block is already a submenu, it now only inserts a new navigation link.

## Testing Instructions
1. Add a navigation block to a post
2. Open the block inspector
3. Use the + button to add a link to the navigation block
4. Open the settings menu for the link (the stacked three dots icon)
5. Choose 'Add submenu item'
6. Observe that a new submenu is created with one item.
7. Repeat steps 4-5 a few times, more submenu items should be added.

### Testing Instructions for Keyboard
1. Tab to the post content and type '/navigation' followed by enter to create a navigation block
2. Shift tab to the block toolbar and activate the 'Settings' button
3. Tab (or navigate regions) to the block inspector until you reach the 'Block navigation structure' application
4. Press the down arrow until you get to the 'Add block' button, then hit enter to add a block
5. In the resulting popover, type in a URL or page name (or use arrow keys to navigate through options) and press enter
6. Press the up arrow once to focus the block just added
7. Press right arrow once to get to the block settings dropdown and use enter to open it
8. Arrow down to the 'Add submenu item' option and press enter to use it
9. At this point there is a focus loss bug (the block is selected in the canvas). Tab back to the block inspector block navigation structure and repeat steps 4-8 a few times. The focus loss will only happen the first time through.
10. Use up and down arrows to check the blocks in list view, you should have one Navigation Submenu with multiple Navigation Links

## Screenshots or screencast 

https://user-images.githubusercontent.com/677833/207767355-39d59949-c7eb-40cb-bdd1-cf635e23cde7.mp4

### CODE REVIEW

File: packages/block-editor/src/components/off-canvas-editor/block.js [hunk 1]
```diff
@@ -145,7 +144,7 @@ function ListViewBlock( {
 
 	const { isTreeGridMounted, expand, collapse } = useListViewContext();
 
-	const isEditable = blockName !== 'core/page-list-item';
+	const isEditable = block.name !== 'core/page-list-item';
```
Comment (getdave) [inline packages/block-editor/src/components/off-canvas-editor/block.js:147]: Aside: I added this line to https://github.com/WordPress/gutenberg/issues/46166

File: packages/block-editor/src/components/off-canvas-editor/block.js [hunk 2]
```diff
@@ -369,20 +368,34 @@ function ListViewBlock( {
...
-											);
-											replaceBlock(
-												clientId,
-												newSubmenu
-											);
+											if (
+												block.name ===
+												'core/navigation-submenu'
+											) {
+												const updateSelectionOnInsert = false;
```
Comment (getdave) [inline packages/block-editor/src/components/off-canvas-editor/block.js:375]: Given the API this is very helpful 🙇

File: packages/block-editor/src/components/off-canvas-editor/block.js [hunk 3]
```diff
@@ -369,20 +368,34 @@ function ListViewBlock( {
...
-													  ]
-													: [ newLink ]
-											);
-											replaceBlock(
-												clientId,
-												newSubmenu
-											);
+											if (
+												block.name ===
+												'core/navigation-submenu'
```
Comment (getdave) [inline packages/block-editor/src/components/off-canvas-editor/block.js:373]: I added this to https://github.com/WordPress/gutenberg/issues/46166

**Review by getdave — APPROVED** [review]
I tested this and it worked as described.

Thank you for fixing ❤️

**Comment by scruffian** [comment]
Thanks for fixing this. I had a hunch that the problem was that the block wasn't defined but I wasn't sure exactly what line was relying on that. Are you able to explain it?

**Comment by talldan** [comment]
@scruffian The change in https://github.com/WordPress/gutenberg/pull/46541 results in the off canvas editor using a slimmed down version of the block hierarchy that only has `clientId` and `innerBlocks` properties, so it seemed to be tripping up on accessing the missing `name` and `attributes` of the block.
