### PR TITLE
Rich Text: Apply attributes properly

### LINKED ISSUE #14858: Rich Text: Unrelated attributes are applied to Rich Text FormatType
**Describe the bug**
There is an error in the program, which causes strange behavior as described in the title.

**To reproduce**
1. Register format type which has no attributes
  ```tagName: span, className: my-span``` (hereinafter referred to format type A)
2. Register format type which has style attribute
  e.g. install and activate `Advanced Rich Text Tools for Gutenberg` plugin
  https://wordpress.org/plugins/advanced-rich-text-tools/
  (e.g. background color)
  (hereinafter referred to format type B)
3. Input text and apply format type A to Rich Text on block editor
4. Apply format type B to Rich Text, which is
 * same node as format type A
 * prior to format type A
 * not the beginning of the node
5. Clear format type B
⇒ the attributes that format type B had is applied to format type A
(the attributes are not applied on the front end or after reloading editor)

**Expected behavior**
Unrelated attributes should not be applied.

**Screenshots**
screenshot

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: 
   - :x:: Chrome (72.0.3626.121)
   - :x:: FireFox (65.0.2)
   - :white_check_mark:: Edge (42.17134.1.0)
 - Gutenberg plugin v5.1.0 ～ v5.4.0, WP5.2 beta1

**Additional context**
https://github.com/WordPress/gutenberg/blob/release/5.4/packages/rich-text/src/to-dom.js#L212
```
for ( let ii = 0; ii < currentAttributes.length; ii++ ) {
	const { name } = currentAttributes[ ii ];

	if ( ! futureChild.getAttribute( name ) ) {
		currentChild.removeAttribute( name );
	}
}
```
I think that it should be changed as shown below.
```
for ( let ii = currentAttributes.length; --ii >= 0; ) {
	const { name } = currentAttributes[ ii ];

	if ( ! futureChild.getAttribute( name ) ) {
		currentChild.removeAttribute( name );
	}
}
```
I tried the above changes locally and confirmed that they worked correctly.
 - OS: Windows10
 - Browser: 
   - :white_check_mark:: Chrome (72.0.3626.121)
   - :white_check_mark:: FireFox (65.0.2)
   - :white_check_mark:: Edge (42.17134.1.0)
- Gutenberg plugin v5.4.0

### PR DESCRIPTION
**Pull request by technote-space**
## Description

This PR fixes #14858 

## How has this been tested?

- I added a test case
  - Both current and future include node which
    - is same node name 
    - is not text node 
    - has multiple attributes 

```
const cases = [

...

	{
		current: 'test1 <span data-current-attribute1="current1" data-current-attribute2="current2">test2</span> <span>test3</span>',
		future: 'test1 test2 <span data-future-attribute1="future1" data-future-attribute2="future2">test3</span>',
		movedCount: 1,
		description: 'should apply attributes',
	},
];
```
This test will cover this section
https://github.com/WordPress/gutenberg/blob/release/5.5/packages/rich-text/src/to-dom.js#L206-L230

before fix:
```
    Difference:

    - Expected
    + Received

    - test1 test2 <span data-future-attribute1="future1" data-future-attribute2="future2">test3</span>
    + test1 test2 <span data-current-attribute2="current2" data-future-attribute1="future1" data-future-attribute2="future2">test3</span>
```
after fix:
```
  applyValue
    ✓ should remove nodes (1ms)
    ✓ should add nodes (1ms)
    ✓ should not modify (1ms)
    ✓ should apply attributes (4ms)
```

## Screenshots 
before
before

after
after

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/rich-text/src/to-dom.js [hunk 1]
```diff
@@ -207,7 +207,7 @@ export function applyValue( future, current ) {
 				const futureAttributes = futureChild.attributes;
 
 				if ( currentAttributes ) {
-					for ( let ii = 0; ii < currentAttributes.length; ii++ ) {
+					for ( let ii = currentAttributes.length; --ii >= 0; ) {
```
Comment (ellatrix) [inline packages/rich-text/src/to-dom.js]: Could you explain a bit how the fix works? It looks like you're reversing the loop. Could you add a test case with the same content, but the elements reversed? Wouldn't that fail? Thanks for the PR!

File: packages/rich-text/src/test/to-dom.js [hunk 2]
```diff
@@ -59,6 +59,42 @@ describe( 'applyValue', () => {
...
 		},
+		{
+			current: '<span data-1="">b</span>',
+			future: '<span>b</span>',
+			movedCount: 0,
+			description: 'should remove attribute',
+		},
+		{
+			current: '<span data-1="" data-2="">b</span>',
+			future: '<span>b</span>',
```
Comment (ellatrix) [inline packages/rich-text/src/test/to-dom.js]: In case anyone was wondering, this test case would fail in `master`. Added a comment: https://github.com/WordPress/gutenberg/pull/15070/files#diff-829f9f4e942450ee8c33f082c016b173R212.

**Review by ellatrix — APPROVED** [review]
Thanks @technote-space! I cleaned up the tests a bit so it's easier to see what is happening. I also swapped out the reverse `for` loop for a simpler `while` loop.

**Comment by ellatrix** [comment]
Alternatively we could have copied the attributes to an array, but the reverse loop is faster. :)
