### PR TITLE
Unify how editor alignments are applied across blocks

### LINKED ISSUE #21685: Button Block: Backwards compatibility floating doesn’t work properly
The recent changes to Button Block markup in 7.9.1 has caused a backward compatibility issue for buttons created well before 7.9. I have a testing post that lists the Button Block with _all_ of its possible options. I created this post many months ago and I’m not sure which version of Gutenberg I had at the time. 

After updating to 7.9.1 the `.wp-block-button` wrapper gets removed on those older buttons leaving the alignment class a direct child of the content wrapper in the markup like this: 

`.entry-content > wp-block-button.alignleft.wp-block-button__link`. 

I expected to get something like this which is what new buttons created after 7.9.1 give you:

 `.entry-content > .wp-block-buttons.alignleft > .wp-block-button__link`.

**Steps to reproduce the behavior:**
1. Update to Gutenberg version 7.9.1
2. Start a new post. Using the code view, copy the sample content at the bottom of this issue and paste it into your new post.
3. Switch back to the visual view and you should see something similar to this:

image

**Expected behavior**
Before 7.9.1, Button blocks came with a `.wp-block-button` wrapper in the markup. After 7.9.1, newly created buttons get a `.wp-block-buttons` (with an “s”) wrapper but both of them are missing from these “legacy” button blocks I created a while ago. 

I can fix this with some very specific CSS but ideally, “legacy“ Buttons should also get wrapped in `.wp-block-button` or `.wp-block-buttons` markup to prevent disruption on sites that have older Gutenberg content. 

Lastly, this issue effects both the frontend and in the editor backend the same way. I’m wondering if its possible to have Gutenberg re-render those “legacy” buttons to include the wrappers like it did before. 

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Gutenberg plugin
- Gutenberg 7.9.1

**Desktop (please complete the following information):**
 - Mac OS
 - Chrome
 - Version 80.0.3987.163

**Sample content**
```
<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<a class="wp-block-button wp-block-button__link">Singular</a>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:heading {"level":3} -->
<h3>After 7.9.1 👆 — Before 7.9.1 👇</h3>
<!-- /wp:heading -->

<!-- wp:button -->
<a class="wp-block-button wp-block-button__link" href="#">Default</a>
<!-- /wp:button -->

<!-- wp:button {"align":"left"} -->
<a class="wp-block-button alignleft wp-block-button__link" href="#">Left</a>
<!-- /wp:button -->

<!-- wp:button {"align":"center"} -->
<a class="wp-block-button aligncenter wp-block-button__link" href="#">Center</a>
<!-- /wp:button -->

<!-- wp:button {"align":"right"} -->
<a class="wp-block-button alignright wp-block-button__link" href="#">Right</a>
<!-- /wp:button -->

```

### PR DESCRIPTION
**Pull request by youknowriad**
While working on the `lightBlockWrapper` API, we experimented on the Image block about how we can keep the frontend similar to the backend for alignments. It worked for this particular block but it's not something we can generalize yet to all blocks (especially the ones relying on the align hook).

This PR partially reverts the image block alignments change and at the same time updates the "align" hook to support the new "lightBlockWrapper" behavior. This means lightBlockWrapper doesn't mean we're consistent with frontend for aligned blocks but it also means that all blocks in the editor behaves consistently when it comes to alignment (fixes #21685) 

So this is an intermediate step before the bigger alignments rethinking that is happening separately.

### CODE REVIEW

File: packages/block-editor/src/components/block-list/block-wrapper.js [hunk 1]
```diff
@@ -30,7 +30,16 @@ import { BlockContext } from './block';
 import ELEMENTS from './block-elements';
 
 const BlockComponent = forwardRef(
-	( { children, tagName = 'div', __unstableIsHtml, ...props }, wrapper ) => {
+	(
+		{
+			children,
+			tagName = 'div',
+			__unstableIsHtml,
+			wrapperProps: parentWrapperProps,
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-list/block-wrapper.js:38]: Adding this prop is the most controversial change of this PR but the fact is that we need to separate the props applied to the block wrapper (wrapperProps) and the ones applied to the last element rendered by the wrapper (`props` useful to add contentEditable and related props by RichText)

File: packages/block-editor/src/components/block-list/block-wrapper.js [hunk 2]
```diff
@@ -196,13 +209,24 @@ const BlockComponent = forwardRef(
 		const blockElementId = `block-${ clientId }${ htmlSuffix }`;
 		const Animated = animated[ tagName ];
 
+		// For aligned blocks, provide a wrapper element so the block can be
+		// positioned relative to the block column. This is enabled with the
+		// .is-block-content className.
+		const blockEdit = isAligned ? (
+			<div { ...props } className="is-block-content">
```
Comment (ellatrix) [inline packages/block-editor/src/components/block-list/block-wrapper.js:216]: Why does this wrapper need to be added within the block?

File: packages/block-editor/src/components/block-list/block.js [hunk 3]
```diff
@@ -144,13 +144,6 @@ function BlockListBlock( {
 		/>
 	);
 
-	// For aligned blocks, provide a wrapper element so the block can be
-	// positioned relative to the block column. This is enabled with the
-	// .is-block-content className.
-	if ( ! lightBlockWrapper && isAligned ) {
```
Comment (ellatrix) [inline packages/block-editor/src/components/block-list/block.js:150]: https://github.com/WordPress/gutenberg/pull/21822/files#r413741147
In other words, would removing the check here not be enough?

File: packages/block-editor/src/components/block-list/block-wrapper.js (hunk 1 above)
Comment (youknowriad) [reply packages/block-editor/src/components/block-list/block-wrapper.js:38]: Seems like this doesn't work as expected though :(

File: packages/block-library/src/buttons/editor.scss [hunk 4]
```diff
@@ -4,19 +4,19 @@
 }
 
 .wp-block-buttons {
-	&[data-align="center"] .block-editor-block-list__layout {
+	&[data-align="center"] > .is-block-content {
```
Comment (ellatrix) [inline packages/block-library/src/buttons/editor.scss:7]: Blocks starting to use this class is what scares me most, because we're unlikely to keep this helper class.

File: packages/block-library/src/image/edit.js [hunk 5]
```diff
@@ -352,6 +352,9 @@ export class ImageEdit extends Component {
 			sizeSlug,
 		} = attributes;
 
+		const wrapperProps = {
+			'data-align': align,
```
Comment (ellatrix) [inline packages/block-library/src/image/edit.js:356]: Can this not be built in?

File: packages/block-library/src/cover/editor.scss [hunk 6]
```diff
@@ -23,13 +22,14 @@
...
-	[data-align="left"] &,
-	[data-align="right"] & {
-		max-width: $content-width / 2;
-		width: 100%;
-	}
+[data-align="left"] > .wp-block-cover,
+[data-align="right"] > .wp-block-cover,
+[data-align="left"] > .wp-block-cover-image,
+[data-align="right"] > .wp-block-cover-image {
+	max-width: $content-width / 2;
```
Comment (ellatrix) [inline packages/block-library/src/cover/editor.scss:31]: Why is with being defined here?

Comment (ellatrix) [reply packages/block-library/src/cover/editor.scss:31]: I'm just curious, it's not a comment to this PR.

File: packages/block-editor/src/components/block-list/block.js (hunk 3 above)
Comment (youknowriad) [reply packages/block-editor/src/components/block-list/block.js:150]: Discussed this in DM and not, this doesn't work

File: packages/block-library/src/cover/editor.scss (hunk 6 above)
Comment (youknowriad) [reply packages/block-library/src/cover/editor.scss:31]: Just guessing

I believe if we don't do it and align a block (left or right) we won't notice any change as otherwise it will stay with a 100% width

File: packages/block-library/src/image/style.scss [hunk 7]
```diff
@@ -16,24 +16,6 @@
 		width: 100%;
 	}
 
-	// Floats get an extra wrapping <div> element, so the <figure> becomes a child.
-	.alignleft,
-	.alignright,
-	.aligncenter,
-	&.is-resized {
```
Comment (ellatrix) [inline packages/block-library/src/image/style.scss:23]: Could the removal of this have something to do with resizing being broken?

Comment (youknowriad) [reply packages/block-library/src/image/style.scss:23]: Mmm seems related yes

Comment (youknowriad) [reply packages/block-library/src/image/style.scss:23]: I did test before removing this but probably missed the "large caption" use-case.

Comment (ellatrix) [reply packages/block-library/src/image/style.scss:23]: Fixed it in the last commit

Comment (ellatrix) [reply packages/block-library/src/image/style.scss:23]: I wonder if it would be better to generally add to the image styles, but we can explore that separately.

Comment (youknowriad) [reply packages/block-library/src/image/style.scss:23]: Now that I think about it, I wonder if we should also restore the other selectors, since this applies also in the frontend and they could be needed there for large captions.

**Review by ellatrix — APPROVED** [review]
I think this is a good step in the right direction. From here we can better look at having the same structure as the front-end.

File: packages/block-library/src/image/style.scss (hunk 7 above)
Comment (ellatrix) [reply packages/block-library/src/image/style.scss:23]: Yeah, I agree we should restore

File: packages/block-editor/src/components/block-list/block-wrapper.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-editor/src/components/block-list/block-wrapper.js:38]: Can we not use the context for this?

Comment (youknowriad) [reply packages/block-editor/src/components/block-list/block-wrapper.js:38]: I'm not sure how you'd do so, retrieve the context value, alter it and add a new provider? It would work but it's also not great code either, I'd rather remove this at some point (after the image refactor).

Comment (youknowriad) [reply packages/block-editor/src/components/block-list/block-wrapper.js:38]: Actually, we can probably use getEditPropsWrapper

File: packages/block-library/src/image/style.scss (hunk 7 above)
Comment (ellatrix) [reply packages/block-library/src/image/style.scss]: I restored them. Do you thing there might be other front-end classes that are accidentally removed?

Comment (youknowriad) [reply packages/block-library/src/image/style.scss]: I'll check but I don't expect it, I was aware of these, just missed the image ones for some reason.

File: packages/block-editor/src/components/block-list/block-wrapper.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-editor/src/components/block-list/block-wrapper.js:38]: I meant adding it to `useContext( BlockContext )` below

**Comment by jasmussen** [comment]
Sorry for being so late to this review. 

This feels like an excellent first step onto bigger things, and the reduced and simplified markup is so lovely. Also bonus points for including the float margin. Great work all around.

There's one thing I noticed, technically it's not a regression from master — master is actually broken here 😱  — but worth noting so as to not grow worse. I notice because I recently merged  https://github.com/WordPress/gutenberg/pull/21608 and wanted to be sure things didn't regress.

It looks as though a centered image isn't centered in either master or this branch, **in the editor only**. But in master, at least the `aligncenter` class exists. Whereas in this branch, it appears is if nothing is output at all for a centered block.

Master:

Screenshot 2020-04-24 at 11 18 51

You can see there's a text-align: center there which doesn't work (that's the bug), but at least it's there. 

This branch:

Screenshot 2020-04-24 at 11 19 23

It seems the quick fix would be to just remember to include some centering stuff? As mentioned, it works on the frontend, so what we could output in the editor could be something like:

```
.wp-block[data-align="center"] figure {
    margin-left: auto;
    margin-right: auto;
}
```
This appears to work for me in the editor, and should not be needed on the frontend, but I can't think of how it might cause issues.

**Comment by youknowriad** [comment]
> This appears to work for me in the editor, and should not be needed on the frontend, but I can't think of how it might cause issues.

I think that's a good fix, I noticed this too but left it separate but I'm ok including it here. The reason there's no classnames here is to stay consistent, we don't use these classnames in the editor in general (not just within this PR), we tried using some of them on the image block recently but the inconsistency it created with other blocks that rely on data-align was not great. 

Ideally, we'd remove data-align and only use the classnames to match frontend but since this would require updates and changes to frontend markup for the float alignments essentially, it's left separate.

**Comment by jasmussen** [comment]
Ship it then! It seems like a good path forward.

**Comment by ellatrix** [comment]
Yes, in one of the next iteration we'll try out the classnames again, but for all blocks to use it consistently rather than just the image block. This PR is a key step towards that.

**Comment by jasmussen** [comment]
All good, go forth and conquer!

**Comment by nfmohit-wpmudev** [comment]
Guys, I might be absolutely wrong but I think I've found some sort of a regression here. I noticed #21885 reporting that a centre-aligned image wasn't appearing as centre-aligned when they were using the Gutenberg plugin.

I started testing it out and eventually landed on this commit and PR.

> It seems the quick fix would be to just remember to include some centering stuff? As mentioned, it works on the frontend, so what we could output in the editor could be something like:
> 
> .wp-block[data-align="center"] figure {
>     margin-left: auto;
>     margin-right: auto;
> }

@jasmussen I'm not sure if this issue is specific to the theme, but this workaround only seems to work when the `is-resized` class is available on the `figure` element because that adds the `display: table` property to the element. Otherwise, it stays aligned to the left.

Also, after you add an image, it stays aligned to the very left. I'm not sure if this is related to this PR too though.

Let me share a screencast: https://take.ms/S54Si which may help understand the issue better.

Do you think the changes in this PR might've introduced these problems? If that is the case, could you point me towards a potential fix and I can quickly work on a PR?

If that is not the case, please excuse my concern, I might've just not done the investigation well. I can create a new issue in that case.

Thanks! ❤️

**Comment by nfmohit-wpmudev** [comment]
I’d like to add, adding `text-align: center` on the `figure` element under `data-align: center` does resolve the issue with the center alignment. I can write a PR with that upon getting your green light. Thanks!

**Comment by jasmussen** [comment]
Excellent catch, @nfmohit-wpmudev. I can confirm that:

- A small image that is **not resized**, when centered, does not show up as centered in the editor.
- As soon as it is resized even a little bit, it does center itse.f
- That this is an editor-only issue, on the frontend, the image is centered when aligned thusly, regardless of whether it's resized.

Centered but not resized:

Screenshot 2020-04-27 at 09 55 36

Centered and resized:

Screenshot 2020-04-27 at 09 55 40

At a glance, this change fixes it. Instead of:

```
.wp-block[data-align="center"] > .wp-block-image {
    margin-left: auto;
    margin-right: auto;
}
```

if we do this:

```
.wp-block[data-align="center"] > .wp-block-image {
    margin-left: auto;
    margin-right: auto;
    text-align: center;
}
```

it appears to work for both resized and unresized images.

@youknowriad any concerns with that one? Let me know if you'd like me to make a PR.

**Comment by nfmohit-wpmudev** [comment]
Hey @jasmussen !

Thank you very much for the confirmation. I'm very sorry, I didn't notice this response and submitted #21911, is that okay?

Thanks!

**Comment by jasmussen** [comment]
Of course that's okay, it's incredibly helpful. Thank you!

**Comment by nfmohit-wpmudev** [comment]
Thank you very much!

Also, do you possibly have any idea why the image block gets added originally to the very left (like, left-aligned)? [Here's a screencast](https://take.ms/n2YZI). I can confirm that this doesn't happen on the core without the plugin. It aligned with the content when first added. Thank you!

**Comment by jasmussen** [comment]
Yep, I believe that's an issue with the TwentyTwenty theme happening after some of these alignment refactors. It's unfortunate, but I believe, necessary, so as to improve the editor styles overall.

**Comment by nfmohit-wpmudev** [comment]
Thank you for the confirmation.

That's completely understandable. Just wanted to confirm that it is something that needs to be updated on the theme's end.
