### PR TITLE
Fix comment counts with filter

### LINKED ISSUE #71621: Inline comments display oddly on All post screen
### Description

Originally reported in https://github.com/WordPress/gutenberg/issues/66377#issuecomment-2485607973

-  The comment count bubble on the All Posts screen is behaving oddly. The numbers of inline comments and on post comments are mixed and not accurate.

### Step-by-step reproduction instructions

1. Add some inline comments to a post
2. Add some (front end) comments to the same post
3. Check the All Posts page

### Screenshots, screen recording, code snippet

Image

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by adamsilverstein**
## What?
Fix an issue with comment counts showing block_comments as part of the counted comments (specifically the pending comments in the red dots).

Closes https://github.com/WordPress/gutenberg/issues/71621

## Screenshots or screencast 

Note in the before image the counts in the red dot are actually Editorial (Inline block) comments, not front end comments. These are inaccurately shown.

|Before|After|
|-|-|
|before|after|

### CODE REVIEW

File: lib/experimental/block-comments.php [hunk 1]
```diff
@@ -93,3 +93,26 @@ function exclude_block_comments_from_admin( $clauses, $query ) {
...
+ * Filter the comment count query to exclude block_comment type comments.
+ *
+ * Note: we need to make sure this doesn't interfere with the "Editorial Comments" view
+ * once https://github.com/WordPress/gutenberg/issues/71621 is implemented.
+ *
+ * @param string $query The SQL query string.
+ * @return string The modified SQL query string.
+ */
+if ( ! function_exists( 'filter_comment_count_query_exclude_block_comments' ) ) {
+	function filter_comment_count_query_exclude_block_comments( $query ) {
```
Comment (Mamaduka) [inline lib/experimental/block-comments.php]: Out of curiosity, why do we use this pattern for block comment filters instead of using the `gutenberg_` prefix?

Comment (adamsilverstein) [reply lib/experimental/block-comments.php]: I think I saw the pattern in an existing file and followed it. I will fix by adding a gutenberg_ prefix.

Comment (Mamaduka) [reply lib/experimental/block-comments.php]: No worries, saw your comment in other PRs. Sorry for repeating the same 😄

Comment (adamsilverstein) [reply lib/experimental/block-comments.php]: Updated in c6adcb176aa7ad1156f1a0b9e1d1f84e8e7e8bf6

File: lib/experimental/block-comments.php [hunk 2]
```diff
@@ -93,3 +93,24 @@ function exclude_block_comments_from_admin( $clauses, $query ) {
...
+ * @param string $query The SQL query string.
+ * @return string The modified SQL query string.
+ */
+function gutenberg_filter_comment_count_query_exclude_block_comments( $query ) {
+	// Look for a query that is counting comments like "SELECT comment_post_ID, COUNT(comment_ID) as num_comments FROM ...
+	// AND comment_approved = '0' GROUP BY comment_post_ID". Then add the conditional "AND comment_type != 'block_comment'".
+	if ( 0 === strpos( $query, 'SELECT comment_post_ID, COUNT(comment_ID) as num_comments FROM' ) && false !== strpos( $query, 'comment_approved' ) ) {
+		if ( false === strpos( $query, "comment_type != 'block_comment'" ) ) {
+			$query = str_replace( 'comment_approved', "comment_type != 'block_comment' AND comment_approved", $query );
+		}
```
Comment (Mamaduka) [inline lib/experimental/block-comments.php]: We could use modern string methods - `str_starts_with` and `str_contains`, which are polyfilled by WP.

**Review by Mamaduka — APPROVED** [review]
A bit tricky filter, but I don't see any other way to override core behavior in the plugin unless we ignore it.

This works well in my tests.

File: lib/experimental/block-comments.php (hunk 2 above)
Comment (adamsilverstein) [reply lib/experimental/block-comments.php]: updated in 675d63dfde1af9bfad5ac76e27f32d56f55245c3
