### PR TITLE
TinyMCE: fix IE11 lost focus after init

### LINKED ISSUE #12113: IE11: Enter in a paragraph loses focus.
Steps to reproduce:

- Use IE11
- Set focus in a Paragraph
- Type some text and press Enter
- Note that focus is lost and you have to click the new paragraph to set focus there again

Expected result: you should just be able to keep typing.

When focus is lost, it's actually set on the body element. An additional side effect is that _clicking_ a paragraph to type requires _two_ clicks. The first click sets focus on the block itself (`.editor-block-list__block`), and the 2nd click finally sets focus where it needs to be.

This appears to have been a regression that happened between Gutenberg 3.8.1 and 3.9.1. 

3.8.1 GIF of the expected behavior:

3.9.1 GIF of the bug:

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #12113.

I'm not sure what is causing the focus loss. An easy fix is to just set it back if focus is gone.

## How has this been tested?
See #12113.

## Types of changes
Bug fix.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Review by jasmussen — COMMENTED** [review]
Hoooray! I can confirm this PR fixes #12113 and fixes #12181.

ie11

I would approve, but I would appreciate a sanity check by a better JS developer than myself. 

AMAZING WORK. Thank you.

**Comment by iseulde** [comment]
Unfortunately we now have failing e2e test, which is was expecting a bit. The reason for this is that the user might already have move the focus in the meantime, and we'd still be setting back focus.

Thinking... 

I'm slightly tempted to just not initialise TinyMCE in IE11.

**Comment by iseulde** [comment]
For some reason focus moves to:

```html
<div tabindex="0" class="wp-block editor-block-list__block is-typing" id="block-d7cdbeb7-cdab-4e94-8539-1fa71d1463f1" aria-label="Block: Paragraph" data-type="core/paragraph">...</div>
```

So the tab-able element seems to capture focus?

**Comment by iseulde** [comment]
To reproduce the bug this PR would be causing: hold enter to create a lot of paragraphs (in any browser). You'll see that focus unexpectedly moves to an earlier created paragraph.

**Comment by youknowriad** [comment]
@iseulde The issue might be that the paragraph RichText never gets focused? It could be something in `focusTabbable` in `block.js`

**Comment by youknowriad** [comment]
otherwise I'd be fine with this fix but only in IE11 as the issue it creates is less critical than the one it solves for IE

**Comment by iseulde** [comment]
> The issue might be that the paragraph RichText never gets focused? It could be something in focusTabbable in block.js

No, it does receive focus. This PR checks for it, to then set it back. If you don't init TinyMCE at all, everything works. Something happens during TinyMCE init that moves away the focus to the block.

**Comment by iseulde** [comment]
@joen Does the latest commit work for you?

**Comment by jasmussen** [comment]
Testing now.

**Comment by jasmussen** [comment]
This works well when pressing Enter. But sadly tabbing took a downturn. It doesn't work as it should:

ie11

**Comment by iseulde** [comment]
😭

**Comment by iseulde** [comment]
@jasmussen How about now (force pushed)?

**Comment by jasmussen** [comment]
I'm happy to report this seems to work exactly as it should to me! Very nice work. 

ie11

File: packages/editor/src/components/rich-text/tinymce.js [hunk 1]
```diff
@@ -243,6 +243,15 @@ export default class TinyMCE extends Component {
 
 					// Restore the original `setHTML` once initialized.
 					editor.dom.setHTML = setHTML;
+
+					// In IE11, focus is lost to parent after initialising
+					// TinyMCE, so we have to set it back.
+					if (
+						document.activeElement !== this.editorNode &&
+						document.activeElement.contains( this.editorNode )
```
Comment (youknowriad) [inline packages/editor/src/components/rich-text/tinymce.js]: This is a bit concerning. I wonder for example how this works for quotes where we have two RichTexts that might be inside the selection. Can't we check the isFocused element before the `init` call and only focus if it's the current one?

Comment (iseulde) [reply packages/editor/src/components/rich-text/tinymce.js]: I'm not sure what you mean. Could you elaborate?

Comment (iseulde) [reply packages/editor/src/components/rich-text/tinymce.js]: This commit is more restrictive than the last.

Comment (youknowriad) [reply packages/editor/src/components/rich-text/tinymce.js]: I'm suggesting doing this before the init call.

```
const wasFocused = document.activeElement === this.editorNode
```

And changing this condition to

```
wasFocused &&
document.activeElement !== this.editorNode &&
document.activeElement.contains( this.editorNode )
```

Comment (youknowriad) [reply packages/editor/src/components/rich-text/tinymce.js]: Basically making it a little bit more strict

Comment (iseulde) [reply packages/editor/src/components/rich-text/tinymce.js]: There's no point in checking that. The initialisation is only done on focus, so `document.activeElement === this.editorNode` will always be true.

Comment (youknowriad) [reply packages/editor/src/components/rich-text/tinymce.js]: You're totally right :) I forgot that part.

It's still a bit concerning that if we move the focus quickly between two RichTexts in the same block (quote block for instance) while the initialization is in progress, we'll revert the focus. But I guess it's very rare.

**Review by youknowriad — APPROVED** [review]

File: packages/editor/src/components/rich-text/tinymce.js (hunk 1 above)
Comment (iseulde) [reply packages/editor/src/components/rich-text/tinymce.js]: Yes, that's concerning to me too, which is why I tried some other things to fix it. Don't know what would work though. The best thing would be to figure out why focus is lost and prevent that. Another thing we can do is just not initialise TinyMCE in IE11, but perhaps it's better to wait a bit with that.

Comment (youknowriad) [reply packages/editor/src/components/rich-text/tinymce.js]: CAn we test that we're just in IE11 to do that?

Comment (iseulde) [reply packages/editor/src/components/rich-text/tinymce.js]: Yeah, we can detect IE and not initialise. But maybe it's better to wait for the list commands (indent and change type) to work with the rich text value, otherwise they won't work.

Comment (youknowriad) [reply packages/editor/src/components/rich-text/tinymce.js]: I was thinking detect if IE and apply the current patch only in IE. (still initialize the editor) just to make sure we avoid side effects in other browsers.
