### PR TITLE
Editor: Fix autosaves for draft and auto-draft posts

### LINKED ISSUE #76143: AutosaveMonitor: New post becomes dirty right after auto-save
I noticed that when we create a post and add some content and wait for the `auto-save` to kick in, the post becomes dirty without any user interaction.

Initially I though it was related to RTC, but it seems the issue is present both in 6.9 and 7.0 that I tested, with and without the GB enabled. 

### Testing instructions
1. Create a new post and add a word or two in the content
2. Wait for the `auto-save` to kick in
3. Observe that after the `auto-save` the post becomes 'dirty' again.

I'd expect the post to **not** be dirty after the auto-save and without any user interaction.

Below I'm sharing a video that demonstrates the above, but I've change the time that triggers the auto-save to be create a smaller video. Following the above testing instructions though are enough to reproduce what I'm showing in the video.

https://github.com/user-attachments/assets/f0bd9801-8aed-4026-99a8-68714210b9c0

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes #76143.

PR fixes a bug when post content remained "dirty" (`content: fn()`) after autosaving a draft or auto-draft post, which is usually processed as a normal save.

## Why?
During autosave, `content` was replaced with the evaluated value, which later prevented cleanup in `RECEIVE_ITEMS` because `fastDeepEqual(fn, string)` was always false.

## How?
Remove `! options.isAutosave` guard, which was introduced in #17420, but was no longer needed after #17452.

Ideally, we could remove content evaluation from `savePost` and let [the `saveEntityRecord` handle it](https://github.com/WordPress/gutenberg/blob/cd4bc05b9ee385408d7610ebb2dcc890be79b88c/packages/core-data/src/actions.js#L630-L636), but this would be a breaking change since filters expect `edits.content` to be a string.

## Testing Instructions
1. Create a post or page.
2. Add title and content.
3. Trigger an autosave - `window.wp.data.dispatch( 'core/editor' ).autosave()`.
4. Confirm that the "Save Draft" button remains disabled.

I've added an e2e test that fails on trunk when RTC is disabled.

### Testing Instructions for Keyboard
Same.

## Use of AI Tools

Used Cluade to run simulations for a couple of fix options I had in mind.

### CODE REVIEW

File: packages/editor/src/store/actions.js [hunk 1]
```diff
@@ -189,10 +189,7 @@ export const savePost =
 		}
 
 		const content = select.getEditedPostContent();
-
-		if ( ! options.isAutosave ) {
```
Comment (youknowriad) [inline packages/editor/src/store/actions.js:193]: Has this changed recently, is this a recent regression?

Comment (youknowriad) [reply packages/editor/src/store/actions.js:193]: Also what about the case of non draft posts, it seems in this case the should keep this condition no?

Comment (Mamaduka) [reply packages/editor/src/store/actions.js:193]: I think it's a very old regression. I included details in the PR description. The guard was introduced before there was an `undoIgnore` flag, but we forgot to remove it after.

This has no visible effect on non-draft posts; the only change is that `content` is replaced with the evaluated string, but it still remains dirty.

**Review by youknowriad — APPROVED** [review]

**Review by ntsekouras — APPROVED** [review]
LGTM, thanks!
