### PR TITLE
Patterns: fix bug with pattern categories not saving sometimes

### LINKED ISSUE #54617: Patterns: category doesn't appear for synced patterns
While testing the pattern categories, I noticed that the categories only appear if I create an unsynced pattern. To replicate, create a synced pattern with a brand new category and notice it doesn't appear. I am using WP 6.3.1 and GB nightly: https://github.com/bph/gutenberg/releases/tag/16.8.-nightly

https://github.com/WordPress/gutenberg/assets/26996883/67d47ffa-7c72-48d8-a6b5-5ed0e3fd975d

cc @glendaviesnz

### PR DESCRIPTION
**Pull request by glendaviesnz**
## What?
Ensures that the pattern categories that are entered in the pattern creation modal are always saved before the new pattern is saved.

## Why?
Currently if the modal save button is clicked directly after entering a category the pattern is saved before the onBlur add category event has completed, so the pattern ends up as `uncategorised`
Fixes: #54617

## How?
Only create the pattern categories on submit to also prevent intermediate categories from being created.

## Testing Instructions

- In the site editor Patterns library use the + option at top left menu to add a new pattern
- Add a name and enter a new category, and then directly click on the `Create` button
- Check that the category was correctly added to the pattern
- Create another pattern and this time toggle to `unsynced` after entering category and then click `Create`
- Add a number of patterns with different sync statuses and vary adding new and existing categories, single and multiple categories and check that they all save as expected
- When clicking the Create button double check that it turns to a disabled/busy state and that multiple clicks on it do not affect the save process

## Screenshots or screencast 
Before:

https://github.com/WordPress/gutenberg/assets/26996883/32a95e1a-b6a2-4b48-8c69-b08c78934aa8

After:

https://github.com/WordPress/gutenberg/assets/3629020/03c4c338-8f23-498e-a315-a38b60dd45e9

### CODE REVIEW

**Comment by glendaviesnz** [comment]
@aaronrobertshaw, @kevin940726  this seems to be a reasonably robust fix for this issue, but open to suggestions if you can see a better way.

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for fixing this @glendaviesnz 👍 

It appears to be robust for me in my testing. I couldn't trigger the pattern save prior to the terms updating, as I can on trunk.

As for the approach, no alternatives I could think of were any better, so I don't have any objections to it. Especially, if it allows this fix to be backported in time for the GB 16.7 and WP 6.4 releases.

Also, special thanks for the nice before and after videos, they definitely make the original issue clear.

**Comment by glendaviesnz** [comment]
> Also, special thanks for the nice before and after videos, they definitely make the original issue clear.

I can't take credit for the before video - @annezazu did [such a good job of capturing the problem](https://github.com/WordPress/gutenberg/issues/54617#issuecomment-1728366309) I thought I might as well just borrow that one 😄

File: packages/patterns/src/components/category-selector.js [hunk 1]
```diff
@@ -92,13 +95,21 @@ export default function CategorySelector( { onCategorySelection } ) {
...
+		const categorySaving = new Promise( function ( resolve ) {
+			Promise.all(
+				uniqueTerms.map( ( termName ) =>
+					findOrCreateTerm( { name: termName } )
+				)
+			).then( ( newTerms ) => {
+				setCategorySaving();
+				onCategorySelection( newTerms );
+				resolve( newTerms );
+			} );
```
Comment (kevin940726) [inline packages/patterns/src/components/category-selector.js]: I think we can just chain the promise, making it a bit easier to read.

```suggestion
		const categorySaving = Promise.all(
			uniqueTerms.map( ( termName ) =>
				findOrCreateTerm( { name: termName } )
			)
		).then( ( newTerms ) => {
			setCategorySaving();
			onCategorySelection( newTerms );
			return newTerms ;
		} );
```

File: packages/patterns/src/components/create-pattern-modal.js [hunk 2]
```diff
@@ -36,16 +36,18 @@ export default function CreatePatternModal( {
 	const [ syncType, setSyncType ] = useState( PATTERN_SYNC_TYPES.full );
 	const [ categories, setCategories ] = useState( [] );
 	const [ title, setTitle ] = useState( '' );
+	const [ categorySaving, setCategorySaving ] = useState();
```
Comment (kevin940726) [inline packages/patterns/src/components/create-pattern-modal.js]: Nit: I would probably name it `saveCategoryPromise` to make it clear that the value is a promise instance.

**Review by kevin940726 — APPROVED** [review]
I can't think of a better way off the top of my head. Let's do this unless someone else has a better idea 👍!

File: packages/patterns/src/components/create-pattern-modal.js (hunk 2 above)
Comment (glendaviesnz) [reply packages/patterns/src/components/create-pattern-modal.js]: Yeh, that is clearer, thanks, have done.

File: packages/patterns/src/components/category-selector.js (hunk 1 above)
Comment (glendaviesnz) [reply packages/patterns/src/components/category-selector.js]: hmm, yeh, that extra promise wrapper was a bit redundant, thanks - have removed.

File: packages/patterns/src/components/create-pattern-modal.js [hunk 3]
```diff
@@ -117,7 +139,12 @@ export default function CreatePatternModal( {
 							{ __( 'Cancel' ) }
 						</Button>
 
-						<Button variant="primary" type="submit">
+						<Button
+							variant="primary"
+							type="submit"
+							disabled={ isSaving }
+							aria-disabled={ isSaving }
+						>
```
Comment (aaronrobertshaw) [inline packages/patterns/src/components/create-pattern-modal.js]: Should we be using the `isBusy` prop here as well?

Comment (glendaviesnz) [reply packages/patterns/src/components/create-pattern-modal.js]: for sure, thanks, done.

**Comment by glendaviesnz** [comment]
@aaronrobertshaw, @kevin940726 I noticed a bug with this when testing the changes that you suggested Kai, which is the save button could be clicked multiple times while the category promise was resolving, which causes the pattern to save incorrectly. 

Have updated to disable button and show busy, and have added a note to PR test instructions about this. If one of you has time to give it another quick test to check these changes that would be great thanks.

**Review by kevin940726 — COMMENTED** [review]
After playing and thinking about it for a little bit more, I feel like we shouldn't create categories on blur, but only on save. If the user keeps blurring the input then it will accidentally create a lot of spammy categories, which may be unexpected to the user. If we only create the categories on save then maybe we can also make this flow easier. 🤔 

I'll see what I can do!

File: packages/patterns/src/components/create-pattern-modal.js [hunk 4]
```diff
@@ -117,7 +139,13 @@ export default function CreatePatternModal( {
 							{ __( 'Cancel' ) }
 						</Button>
 
-						<Button variant="primary" type="submit">
+						<Button
+							variant="primary"
+							type="submit"
+							disabled={ isSaving }
+							aria-disabled={ isSaving }
```
Comment (Mamaduka) [inline packages/patterns/src/components/create-pattern-modal.js]: a11y suggestion: we should only use `aria-disabled` here to allow focus on disabled elements. This means that we have to return early in `onCreate` when `isSaving` is true since `aria-disabled` doesn't prevent click actions.

You can see a similar pattern in action here: https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-post/src/components/sidebar/post-template/create-modal.js

Comment (kevin940726) [reply packages/patterns/src/components/create-pattern-modal.js]: I also noticed this and fixed it in [f0ee899](https://github.com/WordPress/gutenberg/pull/54676/commits/f0ee8990cb6843ad91042c6d4824496e7539c27c) 👍

**Comment by kevin940726** [comment]
I refactored the code to move the creation logic to the parent component and make `CategorySelector` fully controlled in [f0ee899](https://github.com/WordPress/gutenberg/pull/54676/commits/f0ee8990cb6843ad91042c6d4824496e7539c27c). Let's see if the CI god is happy with it 😆.

**Review by glendaviesnz — COMMENTED** [review]
The refactor of the week 🏆 goes to @kevin940726  - this is a much better approach, thanks for doing this. This tests well for me in site and post editors:

✅ Category added on synced pattern saved if Create clicked directly after entering category
✅ Can add multiple categories for synced and unsynced patterns and all save as expected
✅ Multiple clicks on the `Create` button while saving in progress do not have any adverse effect

**Review by aaronrobertshaw — APPROVED** [review]
The switch to making `CategorySelector` fully controlled is much better. Thank you @kevin940726 🙇 

I've retested as per the updated test instructions. LGTM!

**Comment by mikachan** [comment]
I just cherry-picked this PR to the release/16.7 branch to get it included in the next release: 40c12b4421
