### PR TITLE
Fix Word paste

### LINKED ISSUE #4854: Pasting Microsoft Word content on Google Chrome for macOS creates an image block rather than text.
## Issue Overview
Gutenberg now supports pasting pre-formatted content from Microsoft Word in most web browsers. 

However, when I use Google Chrome on MacOS, pasting pre-formatted text from Microsoft Word creates an image block of text rather than the expected, editable text. All of my Google Chrome extensions are disabled.

## Steps to Reproduce (for bugs)
1. Open a document in the latest version of Microsoft Word for MacOS.
2. Copy contents of document.
3. Paste into Gutenberg editor, using Google Chrome for MacOS.
4. The text gets pasted as a block image. Te text cannot be edited in anyway, the content is unusable as a block image rather than workable text.

## Expected Behavior
Content pasted from Microsoft Word should show up as formatted text, it should behave in a similar manor as it did in the classic editor. Images, text, and other elements copied from Microsoft Word should be handled properly rather than just turning the entire copied document into a giant image.

## Current Behavior
Copied text gets pasted as a block image. Te text cannot be edited in any way, the text content is converted to an image rather than pasted as workable text.

## Screenshots / Video
Result of pasting a sample document into gutenberg (It is pasted as an image block rather than useable text):
Paste
Paste issue
I have this problem regardless of the amount of text I copy. Even just copying one letter from word gets pasted as a letter in WordPress.

Here is a GIF that demonstrates my problem: https://i.imgur.com/VqNtz6o.gif

## More info
Using MacOS High Sierra, with latest version of Microsoft Office 2016 for Mac. Copied into Google Chrome. Site I run: http://www.mdinvasives.org

Edit:
I discovered that "Paste and Match Style" does not have this issue.

All of these browsers are experiencing this issue on MacOS High Sierra for me:
- Google Chrome v64
- Google Chrome Canary v66
- Opera v50

This issue does NOT affect:

- Google Chrome for Windows 10
- Firefox for Windows 10
- Firefox for MacOS
- Safari for MacOs

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #4854.

## How Has This Been Tested?
On Mac, copy text from Word into Chrome. Text should be pasted instead of an image with the text.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code has proper inline documentation.

### CODE REVIEW

File: blocks/rich-text/index.js [hunk 1]
```diff
@@ -283,11 +283,19 @@ export default class RichText extends Component {
 	 * @param {PasteEvent} event The paste event as triggered by tinyMCE.
 	 */
 	onPaste( event ) {
-		const dataTransfer = event.clipboardData || event.dataTransfer || this.editor.getDoc().dataTransfer;
-		const { items = [], files = [] } = dataTransfer;
+		const dataTransfer =
+			event.clipboardData ||
+			event.dataTransfer ||
+			this.editor.getDoc().dataTransfer ||
+			{ getData: () => '' };
```
Comment (gziolo) [inline blocks/rich-text/index.js]: Interesting :)

Comment (iseulde) [reply blocks/rich-text/index.js]: I noticed the code previously did not fall back to an object, so if this ends up `undefined` the following line would error. Also no need for further `dataTransfer` checks then. I don't even know if this is a real scenario, but better safe than sorry.

Comment (aduth) [reply blocks/rich-text/index.js]: Sounds like a good inline comment.

File: blocks/rich-text/index.js [hunk 2]
```diff
@@ -283,11 +283,19 @@ export default class RichText extends Component {
...
+
+		const { items = [], files = [], types = [] } = dataTransfer;
 		const item = find( [ ...items, ...files ], ( { type } ) => /^image\/(?:jpe?g|png|gif)$/.test( type ) );
+		const plainText = dataTransfer.getData( 'text/plain' );
+		const HTML = dataTransfer.getData( 'text/html' );
 
-		if ( item ) {
+		// Only process file if no HTML is present.
```
Comment (aduth) [inline blocks/rich-text/index.js]: What about plain text? It's not clear why we'd target HTML specifically, except if we're intending to address Word's behavior alone (in which case, maybe we should comment as such). Otherwise should we be verifying that there are _no other types_ here?

Comment (iseulde) [reply blocks/rich-text/index.js]: This is not necessarily Word specific. Other sources might also add files, in which case we should make sure it's a file without any HTML. Pasted image data might have a URL in the plain text data, so we shouldn't check for it here. I added a comment.

File: blocks/rich-text/index.js (hunk 1 above)
Comment (iseulde) [reply blocks/rich-text/index.js]: Done.

**Comment by iseulde** [comment]
Fairly straightforward fix, added comments to unclear bits, 2 reviews, and steeped for a bit, so I think this is ready for merge.

File: blocks/rich-text/index.js (hunk 2 above)
Comment (WraithKenny) [reply blocks/rich-text/index.js]: Related: #11683
