### PR TITLE
Fix zoom animation scrollbar

### LINKED ISSUE #67360: Block editor: unwanted scroll bar while loading.
### Description

On load time the block editor displays an unwanted scroll bar. Please take a look at the screenshot below.

I'm tagging this issue with zoom-out tag because this seems to be the result of the changes introduced in https://github.com/WordPress/gutenberg/pull/67126

Specifically this line:
https://github.com/WordPress/gutenberg/blob/857ca64ae813ae75e5f3a3c5a7d4f930d7bd47d9/packages/block-editor/src/components/iframe/content.scss#L22-L24

### Step-by-step reproduction instructions

1. Use Gutenberg trunk and TT5 theme.
2. Browse theme style variations in the sidebar.
3. Observe the unwanted scroll bars while the block editors are loading

### Screenshots, screen recording, code snippet

Image

### Environment info

- WordPress 6.7.1
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by jeryj**
Fixes https://github.com/WordPress/gutenberg/issues/67360

## What?

When animating between zoom levels, we were forcing a scrollbar during the `positioned: fixed` part of the animation to prevent a width snap. However, this assumes the container always has a scrollbar, which isn't true. To fix it, we only add the scrollbar into the frame if necessary.

## Why?

Improve layout animation when the editor canvas does not have a scrollbar.

## How?

- Check to see if the container has a scrollbar or not by seeing if the `scrollHeight` is greater than the container (if it is, we force a scrollbar)
- Keeps it in line with the correct `TransitionState` type (previously, `transitionTo` did not have a `scrollHeight` but `transitionFrom` did.
- Separates out `computeScrollHeightNext` from `computeScrollTopNext`
- Extra: Refactors `computeScrollTopNext` to use `prev` prefixed constants for all `transitionFrom` values to normalize the naming

### With scrollbar
- Have an editor canvas with a scrollbar (add content)
- Toggle zoom in/out
- Scrollbar should be present during the animation

### With scrollbar
- Have an editor canvas without a scrollbar (remove content)
- Toggle zoom in/out
- Scrollbar should NOT be present during the animation

## Screenshots or screencast 

|Before|After|
|-|-|
|||

### CODE REVIEW

File: packages/block-editor/src/components/iframe/use-scale-canvas.js [hunk 1]
```diff
@@ -409,20 +433,24 @@ export function useScaleCanvas( {
...
 					frameSize,
 					containerHeight:
-						iframeDocument.documentElement.clientHeight, // use clientHeight to get the actual height of the new container, as it will be the most up-to-date.
+						iframeDocument.documentElement.clientHeight, // use clientHeight to get the actual height of the new container after zoom state changes have rendered, as it will be the most up-to-date.
 				};
+
+				transitionToRef.current.scrollHeight = computeScrollHeightNext(
+					transitionFromRef.current,
+					transitionToRef.current
+				);
```
Comment (jeryj) [inline packages/block-editor/src/components/iframe/use-scale-canvas.js:453]: On first render (previously), `transitionToRef` did not have a `scrollHeight` value.

File: packages/block-editor/src/components/iframe/use-scale-canvas.js [hunk 2]
```diff
@@ -47,12 +62,12 @@ function computeScrollTopNext( transitionFrom, transitionTo ) {
 		containerHeight: prevContainerHeight,
 		frameSize: prevFrameSize,
 		scaleValue: prevScale,
-		scrollTop,
-		scrollHeight,
+		scrollTop: prevScrollTop,
```
Comment (jeryj) [inline packages/block-editor/src/components/iframe/use-scale-canvas.js:65]: Renamed to keep naming consistent with all `transitionFrom` values having a `prev` prefix for clarity.

File: packages/block-editor/src/components/iframe/use-scale-canvas.js [hunk 3]
```diff
@@ -409,20 +433,24 @@ export function useScaleCanvas( {
 				// the iframe at this point when we're about to animate the zoom out.
 				// The iframe scrollTop, scrollHeight, and clientHeight will all be
 				// the most accurate.
-				transitionFromRef.current.containerHeight =
-					transitionFromRef.current.containerHeight ??
-					containerHeight; // Use containerHeight, as it's the previous container height value if none was set.
```
Comment (jeryj) [inline packages/block-editor/src/components/iframe/use-scale-canvas.js:414]: Using the `transitionFromRef.current.containerHeight` won't be as accurate, as it could have changed from a manual resize between animations. Relying on `containerHeight` will be more accurate.

File: packages/block-editor/src/components/iframe/use-scale-canvas.js [hunk 4]
```diff
@@ -71,15 +86,12 @@ function computeScrollTopNext( transitionFrom, transitionTo ) {
...
+	scrollTopNext = prevScrollTop <= prevFrameSize ? 0 : scrollTopNext;
 
 	// This is the scrollTop value if you are scrolled to the bottom of the
 	// iframe. We can't just let the browser handle it because we need to
 	// animate the scaling.
-	const maxScrollTop =
-		scrollHeight * ( scaleValue / prevScale ) +
-		frameSize * 2 -
-		containerHeight;
+	const maxScrollTop = scrollHeight - containerHeight;
```
Comment (ajlende) [inline packages/block-editor/src/components/iframe/use-scale-canvas.js:94]: Nice! This is a lot more understandable after the refactoring!

**Review by ajlende — APPROVED** [review]
Looks good to me 👍 

|Before|After|
|-|-|
|zoom-sidebar-before|zoom-sidebar-after|

**Comment by t-hamano** [comment]
Thanks for the fix! I have confirmed that the issue has been resolved on Windows OS.
