### PR TITLE
Fix race condition in block moving animation.

### LINKED ISSUE #16540: Isuue with editor.BlockListBlock filter after v6.1
The issue is present when the `style` prop is modified using the `editor.BlockListBlock` filter.

Let's suppose I need to add some custom styles to a block's wrapper element (only `core/image` for the example). Currently I'm using something similar to that:

```javascript
const { createHigherOrderComponent } = wp.compose;

const withStyles = createHigherOrderComponent( ( BlockListBlock ) => {
	return ( props ) => {
		if ( props.block.name !== 'core/image' ) {
			return <BlockListBlock { ...props } />;
		}

		let wrapperProps = props.wrapperProps;
		wrapperProps = {
			...wrapperProps,
			style: {
				...( wrapperProps && { ...wrapperProps.style } ),
				marginBottom: '30px',
			},
		};
		return <BlockListBlock { ...props } wrapperProps={ wrapperProps } />;
	};
}, 'withStyles' );

wp.hooks.addFilter( 'editor.BlockListBlock', `my-plugin/core-image-blb-with-styles`, withStyles );
```
This approach seems to collide with the changes introduced in #16065.

**To reproduce**
1. Use the snippet above. 
2. Add two image blocks and a heading.
3. Remove the first image block.

You should get something like this:
Screen record from 2019-07-11 17 39 19

### PR DESCRIPTION
**Pull request by youknowriad**
The block animations introduced in the previous release can suffer from some issues:

 - Sometimes on very quick rerenders, the animation stops in the middle causing the blocks to overflow each other.
 - The `style` prop that can be provided by third-party plugins is not rendered anymore.

closes #16540

### CODE REVIEW

File: packages/block-editor/src/components/block-list/moving-animation.js [hunk 1]
```diff
@@ -29,10 +29,17 @@ import { useReducedMotion } from '@wordpress/compose';
  */
 function useMovingAnimation( ref, isSelected, enableAnimation, triggerAnimationOnChange ) {
 	const prefersReducedMotion = useReducedMotion() || ! enableAnimation;
-	const [ resetAnimation, setResetAnimation ] = useState( false );
+	const [ triggeredAnimation, triggerAnimation ] = useReducer( ( state = 0 ) => state + 1 );
```
Comment (jorgefilipecosta) [inline packages/block-editor/src/components/block-list/moving-animation.js]: Is useReducer needed here? The logic using a reducer to do a sum is complex to follow, can we use two-state flags (triggeredAnimation, finishedAnimation) and change the flags accordingly?
If using useReducer can we use a single reducer with multiple actions if that makes things more simple?

**Review by jorgefilipecosta — COMMENTED** [review]
I used the code sample provided in the issue with JSX removed:
```
const { createHigherOrderComponent } = wp.compose;
const el = wp.element.createElement;

const withStyles = createHigherOrderComponent( ( BlockListBlock ) => {
	return ( props ) => {
		if ( props.block.name !== 'core/image' ) {
			return el( BlockListBlock, props );
		}

		let wrapperProps = props.wrapperProps;
		wrapperProps = {
			...wrapperProps,
			style: {
				...( wrapperProps && { ...wrapperProps.style } ),
				marginBottom: '30px',
			},
		};
		return el( BlockListBlock, { ...props, wrapperProps } );
	};
}, 'withStyles' );

wp.hooks.addFilter( 'editor.BlockListBlock', `my-plugin/core-image-blb-with-styles`, withStyles );
```
This PR fixed the problem, but I feel the reducers logic is complex to follow. Can it be coded in a way that is easy to understand for people seeing it for the first time? If not, I guess we should add a small comment explaining how the reducers work.

File: packages/block-editor/src/components/block-list/moving-animation.js (hunk 1 above)
Comment (youknowriad) [reply packages/block-editor/src/components/block-list/moving-animation.js]: I find it simpler this way personally. Each hook keeps track of the "id" of the animation. Basically, it's just a counter that increments each time you call the dispatch function.

Comment (youknowriad) [reply packages/block-editor/src/components/block-list/moving-animation.js]: Could this be a personal preference. Or maybe it's just because we're not used to using `useReducer` that much?

**Review by jorgefilipecosta — APPROVED** [review]
Approving this PR as the reason the code was not easy to understand is probably related to the fact that useReducer is still not common in the codebase.

File: packages/block-editor/src/components/block-list/moving-animation.js (hunk 1 above)
Comment (youknowriad) [reply packages/block-editor/src/components/block-list/moving-animation.js]: I don't want to discard that feedback thought, what do you think? maybe others could share opinions here. @aduth @epiqueras

Comment (epiqueras) [reply packages/block-editor/src/components/block-list/moving-animation.js]: `useReducer` is useful when you need handlers to read props and current state, but don't want to create a new function on every render or whenever they change if you are memoizing. In this case you could just use `setState`:

```js
const [ state, setState ] = useState( 0 );
setState( ( state ) => ++state );
```

I don't think that makes a big difference though. I do agree with @jorgefilipecosta that it would be nicer if we could just use 2 booleans instead of ever increasing numbers. Something like:

```js
const [ { started, finished }, setAnimationState ] = useState( {
	started: false,
	finished: false,
} );
```

Also note that you should pass `initialState` as the second parameter to `useReducer` instead of using a default parameter in the reducer function, so that it is defined before the first update.

https://github.com/facebook/react/blob/42b75ab007a5e7c159933cfdbf2b6845d89fc7f2/packages/react-reconciler/src/ReactFiberHooks.js#L635

Comment (youknowriad) [reply packages/block-editor/src/components/block-list/moving-animation.js]: Ohhh, I wasn't clear enough. We can't use booleans (it was the previous approach) to fix the race conditions completely. We need to be sure all the animations (multiple rerenders can trigger two in a row) have been triggered before resetting.

> const [ state, setState ] = useState( 0 );
> setState( ( state ) => ++state );

This is actually a bad pattern, it creates unexpected bugs especially if you trigger setState from effects because `state` can be outdated at that point. React team talked about that a little bit. The idea is that each time the updated state value depends on the previous state value, it's better to use `useReducer`.

Comment (youknowriad) [reply packages/block-editor/src/components/block-list/moving-animation.js]: I extracted the reducer to avoid recreating a function on each render, I also used the default value argument.

Comment (epiqueras) [reply packages/block-editor/src/components/block-list/moving-animation.js]: >Ohhh, I wasn't clear enough. We can't use booleans (it was the previous approach) to fix the race conditions completely. We need to be sure all the animations (multiple rerenders can trigger two in a row) have been triggered before resetting.

You could achieve that with 2 booleans instead of 1 like the previous approach. But, I can see why numbers make this easier.

>This is actually a bad pattern, it creates unexpected bugs especially if you trigger setState from effects because state can be outdated at that point. React team talked about that a little bit. The idea is that each time the updated state value depends on the previous state value, it's better to use useReducer.

That's why my example uses the functional variant of `setState`. I am not closing over the state, React passes the latest value as a param and I operate on that.

>I extracted the reducer to avoid recreating a function on each render, I also used the default value argument.

:rocket:

File: packages/block-editor/src/components/block-list/block.js [hunk 2]
```diff
@@ -466,8 +466,15 @@ function BlockListBlock( {
 			aria-label={ blockLabel }
 			childHandledEvents={ [ 'onDragStart', 'onMouseDown' ] }
 			tagName={ animated.div }
-			style={ style }
 			{ ...blockWrapperProps }
+			style={
```
Comment (aduth) [inline packages/block-editor/src/components/block-list/block.js]: This reordering clobbers any styles assigned by `blockWrapperProps`.

Notably: Column widths.

https://github.com/WordPress/gutenberg/blob/6f56a7a704114980902485879a151bb46d7ba3cb/packages/block-library/src/column/index.js#L28-L37

Comment (aduth) [reply packages/block-editor/src/components/block-list/block.js]: What's the difference between `wrapperProps` and `blockWrapperProps` anyways? It's not very clear.

Comment (youknowriad) [reply packages/block-editor/src/components/block-list/block.js]: I don't understand. I'm merging the styles here 

```
{
						...wrapperProps.style,
						...animationStyle,
					}
```

so it should continue to work?

Comment (aduth) [reply packages/block-editor/src/components/block-list/block.js]: Oh, I guess `blockWrapperProps` just merges into `wrapperProps` anyways:

https://github.com/WordPress/gutenberg/blob/6f56a7a704114980902485879a151bb46d7ba3cb/packages/block-editor/src/components/block-list/block.js#L414-L421

So the solution should probably be that we don't ever reference `wrapperProps` directly after this merge, and instead always use `blockWrapperProps` (either that or we just remove the separate variable and merge into itself).

Comment (youknowriad) [reply packages/block-editor/src/components/block-list/block.js]: Oh I missed that. yeah, that should work.

Comment (aduth) [reply packages/block-editor/src/components/block-list/block.js]: See #16819

File: packages/block-editor/src/components/block-list/block.js [hunk 3]
```diff
@@ -466,8 +466,15 @@ function BlockListBlock( {
...
+				wrapperProps && wrapperProps.style ?
```
Comment (miina) [inline packages/block-editor/src/components/block-list/block.js]: @youknowriad Question: Is it necessary to add `animationStyle` even if `enableAnimation` is set to `false`? This way it's overriding the potential `transform` style added by `wrapperProps.style`.

Comment (youknowriad) [reply packages/block-editor/src/components/block-list/block.js]: Probably not necessary in that case.

Comment (miina) [reply packages/block-editor/src/components/block-list/block.js]: OK, thanks, will create a PR.
