### PR TITLE
fix: Don't focus link in new NUX tooltip

### LINKED ISSUE #7452: Tips text link border remains on next tip
If you click a tip the next one gets the text border around it. Ideally this should reset over having it on all Tips after the one you click.

2018-06-21 at 21 42

### PR DESCRIPTION
**Pull request by tofumatt**
## Description
Changed the focus from the first element in the popover to the container. This is a good compromise between accessibility and style, plus I think it's a bit more intuitive.

Fix #7452.

## How has this been tested?
Tabbed and clicked through elements and container was always focused after creation.

## Types of changes
Bug fix I suppose; @karmatosed considered this undesired behaviour 😄

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by tofumatt** [comment]
I've no idea why this (seemingly) unrelated snapshot test is failing: https://travis-ci.org/WordPress/gutenberg/jobs/395629001#L967

Not failing for me locally either 🤷‍♂️

File: components/popover/index.js [hunk 1]
```diff
@@ -109,10 +108,9 @@ class Popover extends Component {
 		// Related https://stackoverflow.com/questions/35522220/react-ref-with-focus-doesnt-work-without-settimeout-my-example
 		const focusNode = ( domNode ) => setTimeout( () => domNode.focus() );
 
-		// Find first tabbable node within content and shift focus, falling
-		// back to the popover panel itself.
-		const firstTabbable = focus.tabbable.find( this.contentNode.current )[ 0 ];
-		focusNode( firstTabbable ? firstTabbable : this.contentNode.current );
+		// Focus the popover panel so further tips are easily navigated to via the
+		// keyboard.
+		focusNode( this.contentNode.current );
```
Comment (youknowriad) [inline components/popover/index.js]: I also think it's a good compromise between A11y and UX. These buttons focused on popover open are so ugly and confusing (can't distinguish between what's selected and what's focused sometimes). 

But this is a very impactful change, because we use Popover a lot. I think we need to test all the other usage carefully.

Ellipsis menu, Block Settings Menu, Block Switcher, Table Block's toolbar, inserter (also mobile). I just wanted to mention it and I'll try to test it later.

File: components/popover/index.js [hunk 2]
```diff
@@ -109,10 +108,9 @@ class Popover extends Component {
 		// Related https://stackoverflow.com/questions/35522220/react-ref-with-focus-doesnt-work-without-settimeout-my-example
 		const focusNode = ( domNode ) => setTimeout( () => domNode.focus() );
 
-		// Find first tabbable node within content and shift focus, falling
-		// back to the popover panel itself.
-		const firstTabbable = focus.tabbable.find( this.contentNode.current )[ 0 ];
-		focusNode( firstTabbable ? firstTabbable : this.contentNode.current );
+		// Focus the popover panel so further tips are easily navigated to via the
```
Comment (youknowriad) [inline components/popover/index.js]: We should probably avoid mentioning tips because it's not specific to tips.

Comment (tofumatt) [reply components/popover/index.js]: Oh, yes, good call. I was too narrow in my documentation because it's where I tested it.

File: components/popover/index.js (hunk 1 above)
Comment (tofumatt) [reply components/popover/index.js]: After testing this, it might actually be better to add a prop that disables focus and applies it to the tooltip only. In a lot of other places (especially Block Switcher) you click on a button and you really want focus in the new popover. In the block selector, for instance, it seems silly to have to type tab first to start searching.

Now I think it's better we focus by default (existing behaviour, largely seems to work) with an option to disable. I'll add that, should be easy (but I'll do it tomorrow, I'ma go read a book or something now 😆)

**Comment by afercia** [comment]
OK from an a11y perspective 👍 When the dialog's content is made of text, it's OK to set focus on the first text element, whether it's a heading or paragraph. For reference, see the ARIA Authoring Practices example: https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html open the first modal, then click on "Verify address" to open the second modal.

**Comment by tofumatt** [comment]
So it looks like the `Popover` already has a `focusOnMount` prop, which is in use. I think it's confusing to have both a `focusOnMount` and `focusFirstElement` prop, but given `focusOnMount` is already in use and its behaviour is different/required by some things, that's what I have now. 😞

There's a new prop `focusFirstElement` that only `Tooltip` disables.

File: components/popover/README.md [hunk 3]
```diff
@@ -51,6 +51,16 @@ render(
 
 The component accepts the following props. Props not included in this set will be applied to the element wrapping Popover content.
 
+### focusFirstElement
+
+Focus the *first tabblable element* inside the `Popover` if `focusOnMount` is enabled. This is the default behaviour; set this flag to `false` to focus the container, requiring the user to manually tab to the first element inside the `Popover`.
+
+Has no effect if `focusOnMount` is set to `false`.
```
Comment (noisysocks) [inline components/popover/README.md]: Just an idea: maybe we could deprecate `focusOnMount` and use an enum-like property with three states instead?

```jsx
<Popover autofocus="firstElement" /> // focuses the first tabbable element on mount
<Popover autofocus="container" /> // focuses the container on mount
<Popover autofocus="none" /> // disables focusing on mount
```

Comment (tofumatt) [reply components/popover/README.md]: I’m cool with that actually. What’s our way to throw errors or warn developers when they invariably type something not in the enum list? Mind if I just throw an error?

Comment (tofumatt) [reply components/popover/README.md]: Actually, I wonder about using `autofocus` because there's already an `<input>` prop `autofocus` in HTML.

🚲🏠!

**Comment by tofumatt** [comment]
@noisysocks Do you care enough about the prop name to wanna change it? If yes I'll do it, otherwise I'm basically of the opinion either of these are "meh, but rarely used" APIs and I'd rather do the one with less overlap with an existing prop and less admin work (deprecating stuff).

But if you feel yours is better, I'll do it. I'm not trying to be lazy, I just don't care so I'm not good to ask about it 😆

File: components/popover/README.md (hunk 3 above)
Comment (noisysocks) [reply components/popover/README.md]: Maybe leave the name as is then, i.e. `focusOnMount="firstElement"`.

**Review by noisysocks — APPROVED** [review]
Tested locally and it works 👍

Up to you if you want to try and simplify the `Popover` API 🙂

**Comment by tofumatt** [comment]
Awesome, I went with the simplification; it's enough of a change that another review would be good, sorry! 😄

File: components/popover/index.js [hunk 4]
```diff
@@ -96,23 +96,39 @@ class Popover extends Component {
...
 
 	focus() {
-		const { focusOnMount = true } = this.props;
-		if ( ! focusOnMount ) {
-			return;
+		const { focusOnMount } = this.props;
+
+		// Boolean values for focusOnMount deprecated in 3.2.
+		if ( focusOnMount === true ) {
+			window.console.warn( '<Popover> component: focusOnMount should be false or a string as of Gutenberg 3.2. See: https://github.com/WordPress/gutenberg/tree/master/components/popover/README.md' );
```
Comment (noisysocks) [inline components/popover/index.js]: I think it's worth using `deprecated()` here and adding a note to `docs/deprecated.md`. Then, in 3.4, we can remove the check entirely.

```js
deprecated( 'focusOnMount={ true }', {
	version: '3.4',
	alternative: 'focusOnMount="firstElement"',
	plugin: 'Gutenberg',
} );
```

File: components/popover/index.js [hunk 5]
```diff
@@ -96,23 +96,39 @@ class Popover extends Component {
...
 
 		// Without the setTimeout, the dom node is not being focused
 		// Related https://stackoverflow.com/questions/35522220/react-ref-with-focus-doesnt-work-without-settimeout-my-example
 		const focusNode = ( domNode ) => setTimeout( () => domNode.focus() );
 
-		// Find first tabbable node within content and shift focus, falling
-		// back to the popover panel itself.
-		const firstTabbable = focus.tabbable.find( this.contentNode.current )[ 0 ];
-		focusNode( firstTabbable ? firstTabbable : this.contentNode.current );
+		if ( focusOnMount === 'firstElement' || focusOnMount === true ) {
```
Comment (noisysocks) [inline components/popover/index.js]: If we do the above then let's make a note here that this `focusOnMount === true` check can be removed in 3.4.

File: editor/components/rich-text/format-toolbar/index.js [hunk 6]
```diff
@@ -221,7 +221,7 @@ class FormatToolbar extends Component {
 						<div className="editor-format-toolbar__link-container" style={ { ...focusPosition } }>
 							<Popover
 								position="bottom center"
-								focusOnMount={ !! isAddingLink }
+								focusOnMount={ !! isAddingLink ? 'firstElement' : false }
```
Comment (noisysocks) [inline editor/components/rich-text/format-toolbar/index.js]: The `!!` isn't necessary here since we're just using the result in a conditional.

**Review by noisysocks — APPROVED** [review]
I (still) like this. Left some minor comments.

File: components/popover/index.js (hunk 4 above)
Comment (tofumatt) [reply components/popover/index.js]: Oh, nice! I am total noob so I didn't know how to deprecate stuff. That's totally slick.

File: editor/components/rich-text/format-toolbar/index.js (hunk 6 above)
Comment (tofumatt) [reply editor/components/rich-text/format-toolbar/index.js]: iu

But yeah fair enough.

File: components/popover/index.js [hunk 7]
```diff
@@ -271,7 +293,7 @@ class Popover extends Component {
 
 		// Apply focus return behavior except when default focus on open
 		// behavior is disabled.
-		if ( false !== focusOnMount ) {
+		if ( ! focusOnMount ) {
 			content = <FocusManaged>{ content }</FocusManaged>;
 		}
```
Comment (afercia) [inline components/popover/index.js]: I'm not sure I understand this change. Unless I'm missing something, the "focus return" behavior should be managed if `focusOnMount` is truthy. /Cc @tofumatt @noisysocks

Comment (tofumatt) [reply components/popover/index.js]: Oh shoot, I think I had a brain fail. It sucks that tests didn't catch this but I read this as `false === focusOnMount` not `false !== focusOnMount`… because the latter seems a weird way to write it.

Follow-up/fix PR incoming, my bad.

Comment (afercia) [reply components/popover/index.js]: I think the previous syntax allowed teh prop to be omitted (`null`) and still have focus managed by default?

Comment (tofumatt) [reply components/popover/index.js]: It has a default prop now; omitting it doesn't set it to `null`, it sets it to `"firstElement"`:

https://github.com/WordPress/gutenberg/blob/master/components/popover/index.js#L315

Comment (afercia) [reply components/popover/index.js]: Yeah, sorry for cross-commenting on the new PR 😉
