### PR TITLE
Fix overflow of Highlighted white-space in Code Block

### LINKED ISSUE #69668: Code Block: Highlighted white space overflows
### Description

Currently, if text within a code block is highlighted and contains extra white spaces, it may overflow outside the code box, which is undesirable. Although this scenario is rare, but it impacts the overall UI experience when it occurs.

### Step-by-step reproduction instructions

1. Create a new post 
2. Add a `Code Block` to it 
3. Add some code to the code block 
4. Add some extra whitespace after the end of a line 
5. Highlight the whole code snippet with a distinguishing colour
6. Notice the highlighted whitespace overflows the code box

### Screenshots, screen recording, code snippet

Image

### Environment info

- WordPress 6.7.2 
- Gutenberg Version 20.5.0
- MacOS Sequoia 
- Google Chrome

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by coderGtm**
## What?
Closes #69668 

Fixes the highlight issue for the frontend but does not seem to be working for editor.

## Why?

Currently, when text within a code block is highlighted and includes extra white space, it can overflow beyond the code box, which is not ideal. While this issue is uncommon, it negatively affects the overall UI experience when it does happen.

## How?

The PR introduces a variable called `whiteSpaceStyle` that determined the value of the `white-space` property of the component style. It uses the modern `break-spaces` value to fix the issue on browsers that support this value and uses the older `pre-wrap` on incompatible browsers.

## Testing Instructions

1. Create a new Post
2. Insert a code block with extra white-spaces at the end of 1 line.
3. Highlight the code's background from the Block Controls Toolbar.
4. Verify that the highlight does not overflow the code block in the frontend.

## Screenshots

|Before|After|
|-|-|
|Screenshot 2025-06-03 at 5 46 06 PM|Screenshot 2025-06-03 at 5 46 16 PM|

## Note

This PR is the same as #70301 but since it was based from trunk, there were many issues. Hence this new PR is created for a cleaner workflow.

Thanks

### CODE REVIEW

**Comment by Mamaduka** [comment]
@coderGtm, it looks like prettier is triggering some errors for changes. See - https://github.com/WordPress/gutenberg/pull/77085/changes.

**Comment by Mamaduka** [comment]
Thanks for creating a new PR, @coderGtm!

I just retested, and this doesn't seem to fix the problem. The support is correctly detected, but RichText ignores styles override and still applies `pre-wrap`.

The `pre-wrap` styling is coming from the `useDefaultStyle` hook, which is triggered later and overrides the custom `whiteSpace`.

Does this fix work in your testing?

## Screenshot
CleanShot 2026-04-07 at 11 45 32

File: packages/block-library/src/code/edit.js [hunk 1]
```diff
@@ -5,6 +5,13 @@ import { __ } from '@wordpress/i18n';
 import { RichText, useBlockProps } from '@wordpress/block-editor';
 import { createBlock, getDefaultBlockName } from '@wordpress/blocks';
 
+const SUPPORTS_BREAK_SPACES =
+	typeof CSS !== 'undefined' &&
+	// eslint-disable-next-line no-undef
+	CSS.supports &&
+	// eslint-disable-next-line no-undef
+	CSS.supports( 'white-space', 'break-spaces' );
```
Comment (t-hamano) [inline packages/block-library/src/code/edit.js]: I understand this check is based on https://github.com/WordPress/gutenberg/pull/70301#discussion_r2128246890, but since `break-sopaces` has been supported across all browsers for several years, I believe this check can be removed. What do you think?

https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/white-space#browser_compatibility

File: packages/block-library/src/code/style.scss [hunk 2]
```diff
@@ -14,5 +14,9 @@
 		direction: ltr;
 		text-align: initial;
 		/*!rtl:end:ignore*/
+
+		@supports (white-space: break-spaces) {
+			white-space: break-spaces;
+		}
```
Comment (t-hamano) [inline packages/block-library/src/code/style.scss]:
```suggestion
		white-space: break-spaces;
```

This can also be simplified

**Review by t-hamano — COMMENTED** [review]
The `pre-wrap` styling is coming from the `useDefaultStyle` hook, which is triggered later and overrides the custom `whiteSpace`.

I have confirmed the same behavior. Should we prioritize the `style` prop?

```diff
diff --git a/packages/rich-text/src/hook/use-default-style.js b/packages/rich-text/src/hook/use-default-style.js
index 5d45d027034..f09bd42b783 100644
--- a/packages/rich-text/src/hook/use-default-style.js
+++ b/packages/rich-text/src/hook/use-default-style.js
@@ -30,6 +30,6 @@ export function useDefaultStyle() {
                if ( ! element ) {
                        return;
                }
-               element.style.whiteSpace = whiteSpace;
+               element.style.whiteSpace = element.style.whiteSpace || whiteSpace;
        }, [] );
 }
```

File: packages/block-library/src/code/edit.js (hunk 1 above)
Comment (Mamaduka) [reply packages/block-library/src/code/edit.js]: Good point. The 97% support should be good - https://caniuse.com/?search=white-space.

Comment (coderGtm) [reply packages/block-library/src/code/edit.js]: Okay so should I remove it then to keep only `break-spaces`?

**Comment by coderGtm** [comment]
Hello @Mamaduka and @t-hamano 

Firstly, thanks for testing it @Mamaduka, and yes, the initial commit did not solve the editor side problem as it was an inline styling and I was not sure how to override it without using `!important`.

Secondly, thanks to @t-hamano. Your suggested fix for overriding the default inline styling is superb and it completes the patch for the editor side also.

So now this PR makes the code block behaviour as expected for both frontend and the editor.

One thing I am concerned of is will the changes made to the `useDefaultStyle()` function negatively affect any other component. I am 99% sure it won't since the `element.style.whiteSpace = element.style.whiteSpace || whiteSpace;` will only take the element's white-space style if it is defined but still wanted to know your opinion.

**Comment by Mamaduka** [comment]
> element.style.whiteSpace = element.style.whiteSpace || whiteSpace;

This should be okay. If the consumer wants to override, then we should allow it, IMO. @ellatrix, what do you think?

**Review by Mamaduka — APPROVED** [review]
Works as expected; the new white-space behavior was also approved in the old https://github.com/WordPress/gutenberg/pull/70301#issuecomment-3306943658.

I'm going to merge this.
