### PR TITLE
E2E Tests: Add CPU/Network slowdown configuration options

### LINKED ISSUE #15677: Testing: Add a way to simulate slow network or CPU in e2e tests
Related #15538, #14986.

We constantly encounter issues with tests which fail randomly. It's more noticeable on Travis. It's usually difficult to reproduce those failures locally but it turns out that we can simulate slow network or CPU with Puppeteer API. I opened an issue https://github.com/smooth-code/jest-puppeteer/issues/241 to see whether it'd be a good idea to include such debugging tools into `jest-puppeteer`. If it gets rejected we should integrate it into our e2e test setup ourselves.

Full proposal:
https://github.com/smooth-code/jest-puppeteer/issues/241.

Example of debugging code used with other PRs in the past:

```js
	const client = await page.target().createCDPSession();
	await client.send( 'Network.emulateNetworkConditions', {
		// Whether chrome should simulate
		// the absence of connectivity
		offline: false,
		// Simulated download speed (bytes/s)
		downloadThroughput: 1.5 * 1024 * 1024 / 8,
		// Simulated upload speed (bytes/s)
		uploadThroughput: 750 * 1024 / 8,
		// Simulated latency (ms)
		latency: 40,
	} );
	await client.send( 'Emulation.setCPUThrottlingRate', { rate: 4 } );
```

### PR DESCRIPTION
**Pull request by aduth**
Closes #15677

This pull request seeks to add additional environment variable configuration options to the E2E test runner which can be used to simulate slow network or CPU conditions.

For more information, see included Testing Overview document description:

>If you find that end-to-end tests pass when run locally, but fail in Travis, you may be able to isolate a CPU- or netowrk-bound race condition by simulating a slow CPU or network:
>
>```
>THROTTLE_CPU=4 npm run test-e2e
>```
>
>`THROTTLE_CPU` is a slowdown factor (in this example, a 4x slowdown multiplier)
>
>Related: https://chromedevtools.github.io/devtools-protocol/tot/Emulation#method-setCPUThrottlingRate
>
>```
>DOWNLOAD_THROUGHPUT=125000 npm run test-e2e
>```
>
>`DOWNLOAD_THROUGHPUT` is a numeric value representing bytes-per-second network download (in this example, a 1Mbps download speed).
>
>Related: https://chromedevtools.github.io/devtools-protocol/tot/Network#method-emulateNetworkConditions

**Testing Instructions:**

You can observe that by providing a `THROTTLE_CPU` value when running `npm run test-e2e` for a test suite, it will likely take longer to complete than if the value is not provided.

### CODE REVIEW

File: packages/e2e-tests/config/setup-test-framework.js [hunk 1]
```diff
@@ -190,13 +206,40 @@ async function runAxeTestsForBlockEditor() {
...
+}
+
 // Before every test suite run, delete all content created by the test. This ensures
 // other posts/comments/etc. aren't dirtying tests and tests don't depend on
 // each other's side-effects.
 beforeAll( async () => {
 	capturePageEventsForTearDown();
 	enablePageDialogAccept();
 	observeConsoleLogging();
+	simulateAdverseConditions();
```
Comment (gziolo) [inline packages/e2e-tests/config/setup-test-framework.js]: It's async so it probably should look as follows:

```suggestion
	await simulateAdverseConditions();
```

**Review by gziolo — APPROVED** [review]
Thank you for working on it.

It's a bit simplified implementation in comparison to what I proposed in the original issue but it should be enough for us to simulate those specific configurations. One day, I will implement it as advertised in https://github.com/smooth-code/jest-puppeteer/issues/241 directly in the `jest-puppeteer` unless someone else does it earlier :)

Based on the code from the issue and this implementation. I'm confident it's good to go. I can give it a spin once it's merged into `master` 💯

File: packages/e2e-tests/config/setup-test-framework.js (hunk 1 above)
Comment (aduth) [reply packages/e2e-tests/config/setup-test-framework.js]: > It's async so it probably should look as follows:

Good catch! Updated.

**Comment by aduth** [comment]
> It's a bit simplified implementation in comparison to what I proposed in the original issue but it should be enough for us to simulate those specific configurations.

Yeah, at least for how I expected it to work, this would be sufficient for one-off debugging. I see it as similar to running "headless" or "slowmo" in that way, so modeled it after those options.
