### PR TITLE
Hide the Classic block in the Site Editor

### LINKED ISSUE #23086: The classic block doesn't work on the Site Editor Page
Capture d’écran 2020-06-11 à 11 15 30 AM

TinyMCE might not be loaded properly.

### PR DESCRIPTION
**Pull request by michalczaplinski**
## What?
An attempt to fix #23086.

## Why?
As described in the issue, the Classic block (`core/freeform`) fails to load in the site editor.

## How?
Disabling the block in the Site Editor by using a filter first introduced in https://github.com/WordPress/gutenberg/pull/37157

## Testing instructions
1. Open the site editor. Try to insert the Classic block. Verify that the block does not show up in the inserter.
2. Open the post editor. Make sure that the Classic block is available.

### CODE REVIEW

**Comment by michalczaplinski** [comment]
I ran out of time to fix it completely. Currently, it hides the Classic block completely - I need to add the logic to only hide it in the Site Editor.

It looks to me that there is no flag in the `core/block-editor` redux store that can tell us if the site editor or the post editor is currently open. This is problematic because we need to know if we're in the site editor to hide the block in the inserter.

This could be easily fixed by importing the `core/editor` store from `@wordpres/editor` and doing something like:

```js
import { store as editorStore } from '@wordpress/editor';

// inside of the `useSelect()`
const isSiteEditor = !! select( editorStore ).postId;
```

However the `@wordpress/editor` is currently **not** a dependency of the `block-editor` which I assume is for a reason. Presumably the reason is that the `block-editor` should be agnostic of the particular editor it's in. So, I'm hesitant to add it as a dependency just to solve this issue.

**Comment by ockham** [comment]
> However the `@wordpress/editor` is currently **not** a dependency of the `block-editor` which I assume is for a reason. Presumably the reason is that the `block-editor` should be agnostic of the particular editor it's in. So, I'm hesitant to add it as a dependency just to solve this issue.

Yeah, that's spot-on -- we shouldn't do that 😬 

I'm not entirely sure what's the best way to tackle this, but I came across https://github.com/WordPress/gutenberg/pull/44480, which solves the "inverse" problem -- hiding a block from the _post_ editor. I think the principle might be applicable here, though 🙂 

Maybe the folks that were working on that PR can advise/review 😊

**Comment by adamziel** [comment]
Just leaving a link to the filter @michalczaplinski ended up using: https://github.com/WordPress/gutenberg/pull/37157

**Comment by michalczaplinski** [comment]
Following @ockham's advice, I've followed the approach in https://github.com/WordPress/gutenberg/pull/44480 which was originally introduced in https://github.com/WordPress/gutenberg/pull/37157

We can re-use `blockEditor.__unstableCanInsertBlockType` filter created originally in https://github.com/WordPress/gutenberg/pull/37157

If this gets merged, let's leave a note in both of the PRs since this API might be changed in the future according to: 

https://github.com/WordPress/gutenberg/blob/0ab1a64d2dadd663099cf659342580fe14bc0c71/packages/block-editor/src/store/selectors.js#L1553-L1564

**Review by cbravobernal — APPROVED** [review]
Work as expected. LGTM!

**Comment by michalczaplinski** [comment]
Cherry-picked for the 6.1 release in https://github.com/WordPress/gutenberg/pull/44656

File: packages/edit-site/src/index.js [hunk 1]
```diff
@@ -51,6 +52,26 @@ export function reinitializeEditor( target, settings ) {
...
+	/*
+	 * Prevent adding the Clasic block in the site editor.
+	 * Only add the filter when the site editor is initialized, not imported.
+	 * Also only add the filter(s) after registerCoreBlocks()
+	 * so that common filters in the block library are not overwritten.
+	 *
+	 * This usage here is inspired by previous usage of the filter in the post editor:
+	 * https://github.com/WordPress/gutenberg/pull/37157
+	 */
+	addFilter(
```
Comment (youknowriad) [inline packages/edit-site/src/index.js:64]: Did we try just unregistering (or not registering) the block instead of using a filter?

Comment (michalczaplinski) [reply packages/edit-site/src/index.js:64]: I didn't! 

Let me try it out quickly.

Comment (michalczaplinski) [reply packages/edit-site/src/index.js:64]: I see something quite strange: when **not** registering the block, three `core/freeform` blocks get inserted into the site editor: 

https://user-images.githubusercontent.com/5417266/198698173-fe786c34-61e0-4ef3-ad5a-853c4497cc0c.mp4

https://user-images.githubusercontent.com/5417266/198698183-f8225373-16ac-4ab7-9ef8-5120de6f9459.mp4

Any idea why that might be? I now remember that I've seen this behaviour before when working on this PR which is why I've opted for the fix by using a filter but I didn't investigate the root cause.

Comment (youknowriad) [reply packages/edit-site/src/index.js:64]: I guess, it's something in the parser (probably related about the fallback block being used). Also makes me wonder what happens now in trunk when you edit the HTML of templates manually and add random stuff. Do we have a block that handles random HTML.

Comment (talldan) [reply packages/edit-site/src/index.js:64]: In the widget editor there was also a situation where freeform blocks were inserted, but I think that only happened when pasting blocks. I guess it wasn't happening when loading content because the widget editor doesn't store blocks as html, while the site editor does.

The fix that was used in the widget editor was to use the html block as the freeform block (instead of the classic block). But that caused some other issues - [no block delimiter for the html block](https://github.com/WordPress/gutenberg/issues/35266) and [autop running on freeform content](https://github.com/WordPress/gutenberg/pull/42623).

My suggestion for a longer term fix would be a [new (non-classic) freeform block](https://github.com/WordPress/gutenberg/issues/23086#issuecomment-1250722344) for the site and widget editors. It probably wouldn't be too difficult to implement, borrowing parts from the html and classic block.
