### PR TITLE
Cover: Fix placeholder color options keyboard accessibility

### LINKED ISSUE #68639: Cover placeholder: color palette not fully operable with keyboard
### Description

Discovered while working on https://github.com/WordPress/gutenberg/pull/68602 

The Cover block placeholder now shows a color palette users can use to set a background color:

Image

Navigating the color options with the keyboard isn't fully functional and at some point users may end up in a state where it is impossible to change the selected color option with the keyboard.

It appears this UI change hasn't been tested at all with keyboard, as the non-functional keyboard navigation is very clear and apparent. I would like to remind that any new UI should be tested for at least _basic_ keyboard interaction before being merged and released.

### Step-by-step reproduction instructions

- Add a Cover block.
- Navigate the block placeholder with the keyboard: Press the Tab key three times to move focus to the first color option.
- At this point:
  - Tab: focus moves to the block settings panel 
  - Right arrow: doesn't do anything 
  - Left arrow: moves focus to the previous buttons in the placeholder 
  - Down arrow: moves focus to the following color options, so this is the only keyboard navigation that works
  - Up arrow: moves focus to the wrapper block, so this doesn't work, although I guess it's the expected behavior for nested blocks

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by afercia**
Fixes https://github.com/WordPress/gutenberg/issues/68639

## What?

- The color options in the Cover block placeholder can't be fully operated with the keyboard.
- When the circular options picker is rendered with `asButtons` set to true, it would be best for it to have a `role=group` and appropriate labeling.

## Why?

- Any UI must fully work with the keyboard.
- Labeling is essential to communicate assistive technology users what an UI is about.

## In the fist commit
Setting `asButtons` to true makes the circular options picker render the buttons as a a list of buttons that are all focusable and tabbables. This basically removes the arrow keys navigation that is in use when the options are rendered as a listbox, which conflicts with WritingFlow.

## In the second commit.
I just wanted to set a `role="group"` and a meaningful `aria-label` when `asButtons` is true. This is important because otherwise the options are just a series of buttons. Adding a `role="group"` to the wrapper makes them logically grouped and the `aria-label` communicates users what this group of buttons is about.

However, I discovered that adding `aria-label` didn't render an aria-label attribute when `asButtons` is true. Turned out the aria-label and aria-labelledby props were only allowed for the `ListboxCircularOptionPicker` and not for `ButtonsCircularOptionPicker`.

I'm not that familiar with TypeScript and I had to make a series of changes to make this work that honestly I don't fully understand. I would greatly appreciate some eyes from contributors more familiar than me with TypeScript.
Note that I had to make changes to the allowed types also for the components that consume `CircularOptionPicker` which are: `ColorPalette`, `DuotonePicker` and `GradientPicker`.

To recap;
on trunk, by default the circular option picker renders:
- a `role="listbox"`
- a default `aria-label="Custom color picker."` that cab be passed a custom aria-label 

Instead, when rendered as normal buttons via `asButton`, it renders:
- no role
- passing an `aria-label` doesn't work

I just want the `asButtons` version have a `role=group` and an `aria-label`.

Note: to my understanding, this old issue https://github.com/WordPress/gutenberg/issues/54055 was aiming to provide a better labeling mechanism for these components but it seems it still needs to be addressed. It would be nice to consider further improvements in the context of that issue.

## Testing Instructions

- Repeat the steps from the issue https://github.com/WordPress/gutenberg/issues/68639#issuecomment-2587258773
- Observe that all the color options in the Cover block placeholder can be navigated with Tab and Shit+Tab.
- Inspect the DOM.
- Observe the color options wrapper has a `role="group"` and an `aria-label="Background color"`.

## Screenshots or screencast 

|Before|After|
|-|-|
|||

### CODE REVIEW

**Comment by afercia** [comment]
Since any UI in the editor should be operable with the keyboard at least for a basic usage, and this UI isn't, I would appreciate this PR to be considered for the next WordPress release. Cc @WordPress/gutenberg-core 
Note: I'm not sure this change really needs a changelog entry for the components package.

**Comment by Mamaduka** [comment]
Pinging @WordPress/gutenberg-components as well for feedback.

File: packages/components/src/circular-option-picker/types.ts [hunk 1]
```diff
@@ -40,7 +40,16 @@ type CommonCircularOptionPickerProps = {
...
+} & (
+	| {
+			'aria-label': string;
+			'aria-labelledby'?: never;
+	  }
+	| {
+			'aria-label'?: never;
+			'aria-labelledby': string;
+	  }
+);
```
Comment (ciampo) [inline packages/components/src/circular-option-picker/types.ts]: This seems technically correct, but let's watch out for TS computed types since combining type "unions" can quickly result in a high number or resulting types

File: packages/components/src/duotone-picker/duotone-picker.tsx [hunk 2]
```diff
@@ -130,10 +130,27 @@ function DuotonePicker( {
...
+			metaProps = {
+				..._metaProps,
+				'aria-labelledby': ariaLabelledby,
+			};
+		} else {
+			metaProps = {
+				..._metaProps,
+				'aria-label': __( 'Custom color picker.' ),
+			};
+		}
```
Comment (ciampo) [inline packages/components/src/duotone-picker/duotone-picker.tsx]: The whole logic for building the `metaProps` object feels more complicated than it could be, potentially with less `if` statements and without using an intermediate `_metaProps` object.

I don't have much to take a look at it today, but if needed I can try to help in the next days.

File: packages/components/src/gradient-picker/index.tsx [hunk 3]
```diff
@@ -131,10 +131,27 @@ function Component( props: PickerProps< any > ) {
...
+			metaProps = {
+				..._metaProps,
+				'aria-labelledby': ariaLabelledby,
+			};
+		} else {
+			metaProps = {
+				..._metaProps,
+				'aria-label': __( 'Custom color picker.' ),
+			};
+		}
```
Comment (ciampo) [inline packages/components/src/gradient-picker/index.tsx]: I know that this was an existing issue before this PR, but it looks like we have the same exact logic of `DuotonePicker` repeated in `GradientPicker` — something to look into and understand if it's worth de-duping.

**Review by ciampo — COMMENTED** [review]
Thank you for working on this, @afercia .

I think it would be best to split the changes to a few separate PR:
- one improving the accessibility (grouping and labelling `CircularOptionPicker` options when `asButtons`)
- another one switching the Cover block placeholder to use the `asButtons` prop

It makes code changes easier to follow and test in isolation, especially when they happen across separate packages.

File: packages/components/src/circular-option-picker/types.ts (hunk 1 above)
Comment (afercia) [reply packages/components/src/circular-option-picker/types.ts]: First time for me familiarizing with 'unions' so any advice is more than welcome.
Also, there's a little bit of duplication in this PR, I'd appreciate any feedback about how to prevent it and abstract a bit.

File: packages/components/src/duotone-picker/duotone-picker.tsx (hunk 2 above)
Comment (afercia) [reply packages/components/src/duotone-picker/duotone-picker.tsx]: Yes totally agree, I know. I just followed the existing pattern but I did see there's room for improvements. Also, there's now some duplication. I'd be glad if you want to make improvements here and make this PR yours, when you have a chance.

File: packages/components/src/gradient-picker/index.tsx (hunk 3 above)
Comment (afercia) [reply packages/components/src/gradient-picker/index.tsx]: Yes totally agree, as mentioned above. I was just unsure abou tthe best way to abstract it and de-dupe.

Comment (ciampo) [reply packages/components/src/gradient-picker/index.tsx]: We could do something like the following:

- simplify the logic by splitting the accessible label computation from the `asButtons`+`loop`, which already enables a lot of de-duping
- move the logic to a shared place, eg a utils file in the `CircularOptionPicker` folder

<details>

<summary>Example code changes:</summary>

```diff
diff --git a/packages/components/src/color-palette/index.tsx b/packages/components/src/color-palette/index.tsx
index 68c4d339120..93f1dc6c576 100644
--- a/packages/components/src/color-palette/index.tsx
+++ b/packages/components/src/color-palette/index.tsx
@@ -39,6 +39,7 @@ import {
 	isMultiplePaletteArray,
 	normalizeColorValue,
 } from './utils';
+import { useComputeCircularOptionPickerCommonProps } from '../circular-option-picker/utils';
 
 extend( [ namesPlugin, a11yPlugin ] );
 
@@ -251,50 +252,15 @@ function UnforwardedColorPalette(
 		</CircularOptionPicker.ButtonAction>
 	);
 
-	let metaProps:
-		| { asButtons: false; loop?: boolean; 'aria-label': string }
-		| { asButtons: false; loop?: boolean; 'aria-labelledby': string }
-		| { asButtons: true; 'aria-label': string }
-		| { asButtons: true; 'aria-labelledby': string };
-
-	if ( asButtons ) {
-		const _metaProps: { asButtons: true } = {
-			asButtons: true,
-		};
-
-		if ( ariaLabel ) {
-			metaProps = { ..._metaProps, 'aria-label': ariaLabel };
-		} else if ( ariaLabelledby ) {
-			metaProps = {
-				..._metaProps,
-				'aria-labelledby': ariaLabelledby,
-			};
-		} else {
-			metaProps = {
-				..._metaProps,
-				'aria-label': __( 'Custom color picker.' ),
-			};
-		}
-	} else {
-		const _metaProps: { asButtons: false; loop?: boolean } = {
-			asButtons: false,
+	const { metaProps, labelProps } = useComputeCircularOptionPickerCommonProps(
+		{
+			asButtons,
 			loop,
-		};
-
-		if ( ariaLabel ) {
-			metaProps = { ..._metaProps, 'aria-label': ariaLabel };
-		} else if ( ariaLabelledby ) {
-			metaProps = {
-				..._metaProps,
-				'aria-labelledby': ariaLabelledby,
-			};
-		} else {
-			metaProps = {
-				..._metaProps,
-				'aria-label': __( 'Custom color picker.' ),
-			};
+			ariaLabel,
+			ariaLabelledby,
+			fallbackLabel: __( 'Custom color picker.' ),
 		}
-	}
+	);
 
 	return (
 		<VStack spacing={ 3 } ref={ forwardedRef } { ...additionalProps }>
@@ -352,6 +318,7 @@ function UnforwardedColorPalette(
 			{ ( colors.length > 0 || actions ) && (
 				<CircularOptionPicker
 					{ ...metaProps }
+					{ ...labelProps }
 					actions={ actions }
 					options={
 						hasMultipleColorOrigins ? (
diff --git a/packages/components/src/duotone-picker/duotone-picker.tsx b/packages/components/src/duotone-picker/duotone-picker.tsx
index ee8319b1618..f6348bf1129 100644
--- a/packages/components/src/duotone-picker/duotone-picker.tsx
+++ b/packages/components/src/duotone-picker/duotone-picker.tsx
@@ -20,6 +20,7 @@ import CustomDuotoneBar from './custom-duotone-bar';
 import { getDefaultColors, getGradientFromCSSColors } from './utils';
 import { Spacer } from '../spacer';
 import type { DuotonePickerProps } from './types';
+import { useComputeCircularOptionPickerCommonProps } from '../circular-option-picker/utils';
 
 /**
  * ```jsx
@@ -127,50 +128,15 @@ function DuotonePicker( {
 		);
 	} );
 
-	let metaProps:
-		| { asButtons: false; loop?: boolean; 'aria-label': string }
-		| { asButtons: false; loop?: boolean; 'aria-labelledby': string }
-		| { asButtons: true; 'aria-label': string }
-		| { asButtons: true; 'aria-labelledby': string };
-
-	if ( asButtons ) {
-		const _metaProps: { asButtons: true } = {
-			asButtons: true,
-		};
-
-		if ( ariaLabel ) {
-			metaProps = { ..._metaProps, 'aria-label': ariaLabel };
-		} else if ( ariaLabelledby ) {
-			metaProps = {
-				..._metaProps,
-				'aria-labelledby': ariaLabelledby,
-			};
-		} else {
-			metaProps = {
-				..._metaProps,
-				'aria-label': __( 'Custom color picker.' ),
-			};
-		}
-	} else {
-		const _metaProps: { asButtons: false; loop?: boolean } = {
-			asButtons: false,
+	const { metaProps, labelProps } = useComputeCircularOptionPickerCommonProps(
+		{
+			asButtons,
 			loop,
-		};
-
-		if ( ariaLabel ) {
-			metaProps = { ..._metaProps, 'aria-label': ariaLabel };
-		} else if ( ariaLabelledby ) {
-			metaProps = {
-				..._metaProps,
-				'aria-labelledby': ariaLabelledby,
-			};
-		} else {
-			metaProps = {
-				..._metaProps,
-				'aria-label': __( 'Custom color picker.' ),
-			};
+			ariaLabel,
+			ariaLabelledby,
+			fallbackLabel: __( 'Custom color picker.' ),
 		}
-	}
+	);
 
 	const options = unsetable
 		? [ unsetOption, ...duotoneOptions ]
@@ -180,6 +146,7 @@ function DuotonePicker( {
 		<CircularOptionPicker
 			{ ...otherProps }
 			{ ...metaProps }
+			{ ...labelProps }
 			options={ options }
 			actions={
 				!! clearable && (
diff --git a/packages/components/src/gradient-picker/index.tsx b/packages/components/src/gradient-picker/index.tsx
index 544faee8481..7d9ecdff8bd 100644
--- a/packages/components/src/gradient-picker/index.tsx
+++ b/packages/components/src/gradient-picker/index.tsx
@@ -18,6 +18,7 @@ import type {
 	OriginObject,
 	GradientObject,
 } from './types';
+import { useComputeCircularOptionPickerCommonProps } from '../circular-option-picker/utils';
 
 // The Multiple Origin Gradients have a `gradients` property (an array of
 // gradient objects), while Single Origin ones have a `gradient` property.
@@ -128,54 +129,20 @@ function Component( props: PickerProps< any > ) {
 		<SingleOrigin { ...additionalProps } />
 	);
 
-	let metaProps:
-		| { asButtons: false; loop?: boolean; 'aria-label': string }
-		| { asButtons: false; loop?: boolean; 'aria-labelledby': string }
-		| { asButtons: true; 'aria-label': string }
-		| { asButtons: true; 'aria-labelledby': string };
-
-	if ( asButtons ) {
-		const _metaProps: { asButtons: true } = {
-			asButtons: true,
-		};
-
-		if ( ariaLabel ) {
-			metaProps = { ..._metaProps, 'aria-label': ariaLabel };
-		} else if ( ariaLabelledby ) {
-			metaProps = {
-				..._metaProps,
-				'aria-labelledby': ariaLabelledby,
-			};
-		} else {
-			metaProps = {
-				..._metaProps,
-				'aria-label': __( 'Custom color picker.' ),
-			};
-		}
-	} else {
-		const _metaProps: { asButtons: false; loop?: boolean } = {
-			asButtons: false,
+	const { metaProps, labelProps } = useComputeCircularOptionPickerCommonProps(
+		{
+			asButtons,
 			loop,
-		};
-
-		if ( ariaLabel ) {
-			metaProps = { ..._metaProps, 'aria-label': ariaLabel };
-		} else if ( ariaLabelledby ) {
-			metaProps = {
-				..._metaProps,
-				'aria-labelledby': ariaLabelledby,
-			};
-		} else {
-			metaProps = {
-				..._metaProps,
-				'aria-label': __( 'Custom color picker.' ),
-			};
+			ariaLabel,
+			ariaLabelledby,
+			fallbackLabel: __( 'Custom color picker.' ),
 		}
-	}
+	);
 
 	return (
 		<CircularOptionPicker
 			{ ...metaProps }
+			{ ...labelProps }
 			actions={ actions }
 			options={ options }
 		/>


```

</details>

File: packages/components/src/circular-option-picker/utils.tsx [hunk 4]
```diff
@@ -0,0 +1,27 @@
+/**
+ * WordPress dependencies
+ */
+import { __ } from '@wordpress/i18n';
+
+/**
+ * Computes the common props for the CircularOptionPicker.
+ */
+export function useComputeCircularOptionPickerCommonProps(
```
Comment (Mamaduka) [inline packages/components/src/circular-option-picker/utils.tsx]:
```suggestion
export function getComputeCircularOptionPickerCommonProps(
```

Should we use the `get` prefix instead of `use`? The latter is a reserved prefix in React for hooks, but since this method isn't a hook, it does not need to adhere to the "Rules of Hook" enforced by ESLint/React.

**Comment by afercia** [comment]
~~I'm going to update this PR title because it's not specific to the Cover block, it's more generic to the `CircularOptionPicker` component and its usage in other components.~~ I changed my mind :D

File: packages/components/src/circular-option-picker/circular-option-picker-option-group.tsx [hunk 5]
```diff
@@ -15,7 +15,7 @@ export function OptionGroup( {
 }: OptionGroupProps ) {
 	const role =
 		'aria-label' in additionalProps || 'aria-labelledby' in additionalProps
-			? 'group'
+			? 'listbox'
```
Comment (afercia) [inline packages/components/src/circular-option-picker/circular-option-picker-option-group.tsx]: This aims to fix [an additional issue](https://github.com/WordPress/gutenberg/issues/68639#issuecomment-2642629369) with the `CircularOptionPicker.OptionGroup`. To my understanding, it always contains buttons with a `role="option"` so it should be a listbox.
This is different from the behavior of the parent component `CircularOptionPicker` that changes role depending on the `asButton` prop, which actually renders two alternative components: `ListboxCircularOptionPicker` or `ButtonsCircularOptionPicker`.

**Comment by afercia** [comment]
I tried to do my best to abstract the computation of the props. Please do let me know if this PR needs a changelog entry for the components package. Not sure because it started as a fix for the Cover block but then required changes to:
- CircularOptionPicker
- ColorPalette
- DuotonePicker
- GradientPicker

I'd appreciate some eyes on the Typescript changes, really not my area of expertise. I tried to simplify. To recap:
- `asButtons` and `loop` are now common props and they are optional
- The mutual exclusivity of `aria-labelledby` and `aria-label` (only one of them should be rendered) is now in the `getComputeCircularOptionPickerCommonProps` logic rather than in the Typescript part. Both are now optional props, with an `aria-label` fallback.

File: packages/components/src/circular-option-picker/circular-option-picker-option-group.tsx (hunk 5 above)
Comment (ciampo) [reply packages/components/src/circular-option-picker/circular-option-picker-option-group.tsx]: > it always contains buttons with a `role="option"` so it should be a listbox.

Not 100% about that, but for sure this component is already rendered inside an element with `role="listbox"`, see [this example](https://wordpress.github.io/gutenberg/?path=/story/components-colorpalette--multiple-origins):

Screenshot 2025-02-07 at 15 07 05

File: packages/components/src/circular-option-picker/circular-option-picker.tsx [hunk 6]
```diff
@@ -132,7 +132,7 @@ function ButtonsCircularOptionPicker(
 	);
 
 	return (
-		<div { ...additionalProps } id={ baseId }>
+		<div { ...additionalProps } role="group" id={ baseId }>
```
Comment (ciampo) [inline packages/components/src/circular-option-picker/circular-option-picker.tsx:135]: Is it ok to have a `role="group"` even when the element is not labelled? Should we add a check like in the `OptionGroup` component?

File: packages/components/src/circular-option-picker/circular-option-picker-option-group.tsx (hunk 5 above)
Comment (afercia) [reply packages/components/src/circular-option-picker/circular-option-picker-option-group.tsx]: Hm so this is intended to render one or more `group`s inside a listbox? Then I'm not understanding why the `CircularOptionPicker` in the `ColorPalette` is not renderinf the `role=listbox`.
To recapt:
1. role=listbox > role=group > series of role=option is a valid structure
2. role=group > series of role=option isn't.

I can revert this change but this should be investigated to understand how to fix the scenario 2).

File: packages/components/src/circular-option-picker/circular-option-picker.tsx (hunk 6 above)
Comment (afercia) [reply packages/components/src/circular-option-picker/circular-option-picker.tsx:135]: Yes it is OK. It should use the fallback label though, am I missing something?

File: packages/components/src/circular-option-picker/circular-option-picker-option-group.tsx (hunk 5 above)
Comment (ciampo) [reply packages/components/src/circular-option-picker/circular-option-picker-option-group.tsx]: The example above is from `ColorPalette`
Screenshot 2025-02-07 at 15 51 00


Did you come across an instance of `ColorPalette` without a `listbox` parent?

Comment (afercia) [reply packages/components/src/circular-option-picker/circular-option-picker-option-group.tsx]: I mentioned on the issue: Paragraph block > Color > Text.
Notice there's also a difference beween single palette and multiple palette.

File: packages/components/src/circular-option-picker/circular-option-picker.tsx (hunk 6 above)
Comment (ciampo) [reply packages/components/src/circular-option-picker/circular-option-picker.tsx:135]: It will when used in `ColorPalette` / `DuotonePicker` / `GradientPicker`, but when the `CircularOptionPicker` is used standalone, we're not guaranteed to have a fallback label, right?

> Yes it is OK.

If it is OK, should we remove the equivalent check in `OptionGroup` ?

File: packages/components/src/circular-option-picker/circular-option-picker-option-group.tsx (hunk 5 above)
Comment (ciampo) [reply packages/components/src/circular-option-picker/circular-option-picker-option-group.tsx]: Thank you for signaling — I think it deserves a separate investigation, and I would otherwise leave the `group` role for the time being.

Comment (afercia) [reply packages/components/src/circular-option-picker/circular-option-picker-option-group.tsx]: Agreed, will revert on Monday and create a separate issue. Thanks for the review.

File: packages/components/src/circular-option-picker/circular-option-picker.tsx (hunk 6 above)
Comment (afercia) [reply packages/components/src/circular-option-picker/circular-option-picker.tsx:135]: A `group` role is a very generic role for signaling logically grouped controls. In a way, it's similar to a `<fieldset>` element that, without a `<legend>` element would only signal the grouping without communicating the 'what' the group is about. It is acceptable but it would be good to label the group.
Rather, I think the `group` role should not depend on the presence of aria-label or ariar-labelledby. To me, a listbox that contains only one set of options should not have a group. Instead, when a listbox contains two or more set of options, they should be groups and be labeled.

**Comment by afercia** [comment]
I reverted the change to the `OptionGroup` ARIA role.
Apparently I was wrong. There is a `listbox` role. It's way up in the DOM hierarchy so that I couldn't see it.

File: packages/block-library/src/cover/edit/index.js [hunk 7]
```diff
@@ -514,6 +514,8 @@ function CoverEdit( {
 								value={ overlayColor.color }
 								onChange={ onSetOverlayColor }
 								clearable={ false }
+								asButtons
+								aria-label={ __( 'Background color' ) }
```
Comment (carolinan) [inline packages/block-library/src/cover/edit/index.js]: Nit: In the cover block, it is not called background color but overlay.
Even if there is no media selected.

File: test/e2e/specs/editor/various/list-view.spec.js [hunk 8]
```diff
@@ -162,10 +162,10 @@ test.describe( 'List View', () => {
 		// make the inner blocks appear.
 		await editor.canvas
 			.getByRole( 'document', { name: 'Block: Cover' } )
-			.getByRole( 'listbox', {
-				name: 'Custom color picker.',
+			.getByRole( 'group', {
+				name: 'Background color',
```
Comment (carolinan) [inline test/e2e/specs/editor/various/list-view.spec.js]: Same here, this background color should be overlay.

**Comment by carolinan** [comment]
I am not able to do the code review, but I have confirmed that I can use the tab key or the right and left arrow keys to navigate inside the cover block placeholder to select different colors or media options.

**Comment by afercia** [comment]
Thanks @carolinan I updated the label and selector in the test file.

File: packages/components/src/circular-option-picker/README.md [hunk 9]
```diff
@@ -93,6 +93,19 @@ Prevents keyboard interaction from wrapping around. Only used when `asButtons` i
...
 
+### `aria-labelledby`: `string`
+
+The ID reference list of one or more elements that label the wrapper element.
+
+- Required: No
+
+### `aria-label`: `string`
+
+The label for the wrapper element. Not used if an 'aria-labelledby' is provided.
```
Comment (ciampo) [inline packages/components/src/circular-option-picker/README.md:104]: Question — is it a good practice to add extra logic to labels priority?

What I mean is, should we remove the custom logic in `getComputeCircularOptionPickerCommonProps` that ignores `aria-label` if `aria-labelledby` is defined?  From what I understand, it's already the default behaviour applied by browsers, which means that `aria-label` would be automatically ignored if `aria-labelledby` is also defined.
In that sense, it wouldn't make sense to document the behaviour either, since it's standard DOM and not a particular behaviour of this component.

File: packages/components/src/circular-option-picker/circular-option-picker.tsx (hunk 6 above)
Comment (ciampo) [reply packages/components/src/circular-option-picker/circular-option-picker.tsx:135]: Got it — feel free to work on this improvement to `OptionGroup` in a follow-up PR and ping for reviews

**Review by ciampo — COMMENTED** [review]
Changes are testing good, overall. Left a couple of comments but I think once those are solved, we can do a final testing round and approve/merge

File: packages/components/src/circular-option-picker/README.md (hunk 9 above)
Comment (afercia) [reply packages/components/src/circular-option-picker/README.md:104]: Yes, aria-labelledby overrides aria-label so that's what browsers already do when exposing information in the accessibility tree. I think the logic and documentation do add value because developers need to be educated. They may set both props and think `aria-label` does something, while it wouldn't do anything,
Anyways, I would say it's unrelated to the scope of this PR and the previous implementation made sure only one of the two was in use anyways.

File: packages/components/src/circular-option-picker/circular-option-picker.tsx (hunk 6 above)
Comment (afercia) [reply packages/components/src/circular-option-picker/circular-option-picker.tsx:135]: It's very minor, not sure it is worth it.

File: packages/components/src/circular-option-picker/README.md (hunk 9 above)
Comment (ciampo) [reply packages/components/src/circular-option-picker/README.md:104]: I agree with the point that this behavior was already part of the component's logic.

In general, though, I'd prefer not to document standard DOM features. Given that these are web components, consumers should assume Web Standards and platform behavior as a pre-requisite unless specified otherwise. Otherwise, where do we draw the line between what need to be re-documented and what can be left implied?

**Review by ciampo — APPROVED** [review]
LGTM 🚀  Thank you all for working on this fix

**Comment by afercia** [comment]
Thanks for your review @ciampo

> In general, though, I'd prefer not to document standard DOM features. Given that these are web components, consumers should assume Web Standards and platform behavior as a pre-requisite unless specified otherwise. Otherwise, where do we draw the line between what need to be re-documented and what can be left implied?

I would love contributors and consumers of this project to be knowledgeable of Web Standards and basic specifications such as HTML, WCAG, and ARIA. Unfortunately, what I've been observing in eight years of contribution to this project is that some of them don't. As such, either we enforce via code standards and best practices in the base components (which is a topic we had the opportunity to discuss in person but there's no progress about that) or we document the usage best practices in the docs and comments.
