### PR TITLE
Spacing controls: using CustomSelectControlV2 for >= 8 spacing sizes

### LINKED ISSUE #64270: Sidebar styles tab crashes block when theme has >= 8 spacing values
### Description

Multiple blocks crash ("This block has encountered an error and cannot be previewed.") when clicking on the "styles" tab in the post editor, when the current theme has >= 8 spacing values.

The console is full of errors like:

```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `SpacingInputControl`.

Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `SpacingInputControl`.
```

### Step-by-step reproduction instructions

1. With a theme with 8+ values in `settings.spacing.spacingSizes` in theme.json
2. Create or edit a post
3. Add a group, or buttons, or anything with dimension controls
4. Click the "styles" tab in the sidebar
5. The block crashes

Blocks with the dimension control just in the sidebar (no tabs), like Quote, just crash immediately on adding.

### Screenshots, screen recording, code snippet

I tested this with the `emptytheme` theme in gutenberg, updating the theme.json to the following to give me 8 spacing values.

<details>
<summary>theme.json</summary>

```json
{
	"$schema": "../../schemas/json/theme.json",
	"version": 3,
	"settings": {
		"appearanceTools": true,
		"layout": {
			"contentSize": "840px",
			"wideSize": "1100px"
		},
		"spacing": {
			"spacingSizes": [
				{
					"name": "1",
					"size": "10px",
					"slug": "10"
				},
				{
					"name": "2",
					"size": "20px",
					"slug": "20"
				},
				{
					"name": "3",
					"size": "30px",
					"slug": "30"
				},
				{
					"name": "4",
					"size": "40px",
					"slug": "40"
				},
				{
					"name": "5",
					"size": "50px",
					"slug": "50"
				},
				{
					"name": "6",
					"size": "60px",
					"slug": "60"
				},
				{
					"name": "7",
					"size": "70px",
					"slug": "70"
				},
				{
					"name": "8",
					"size": "80px",
					"slug": "80"
				}
			]
		}
	},
	"customTemplates": [
		{
			"name": "custom-template",
			"title": "Custom",
			"postTypes": [ "post" ]
		}
	],
	"patterns": [ "short-text-surrounded-by-round-images", "partner-logos" ]
}
```

</details>

The issue seems to be when it tries to fall back to the select control, when there are too many values for the range slider.

### Environment info

- WP trunk
- Gutenberg 18.9 (works on 18.8 & below)
- I've reproduced on Firefox & Chrome on Mac.

Initially reported to me on wordpress.org here https://github.com/WordPress/wporg-main-2022/issues/433#issuecomment-2268936669, and https://core.trac.wordpress.org/ticket/61820

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by ramonjd**
## What?

Fixes: https://github.com/WordPress/gutenberg/issues/64270

Where there are more than a defined number of spacing sizes, the spacing input control component will render custom component, rather than the slider controls.

The current threshold for this behaviour is 8 spacing sizes:

https://github.com/WordPress/gutenberg/blob/75d0173916bee81173e99a9294f6d5bdc384f181/packages/block-editor/src/components/spacing-sizes-control/utils.js#L15

A theme.json that contains more than this number causes the browser to crash.

## Why?
CustomSelectControlV2Legacy was removed in favour of V2 but it appears the spacing input control component was not updated.

See: 

- https://github.com/WordPress/gutenberg/pull/63190 (uses legacy component)
- https://github.com/WordPress/gutenberg/pull/63258 (removed legacy component)

## How?

Exporting `CustomSelectControlV2` from components private APIs for use in spacing-input-control.js.

A slight refactor of the component's children was required.

## Testing Instructions

Things should work as they do before https://github.com/WordPress/gutenberg/pull/63258.

You can compare this PR and the previously working version by deactivating the Gutenberg plugin.

1. With a theme with 8+ values in settings.spacing.spacingSizes in theme.json
2. Create or edit a post
3. Add a group, or buttons, or anything with dimension controls
4. Click the "styles" tab in the sidebar
5. Check that you can add padding/margin/block gap sizes to the block and that they publish okay.
6. Also make sure you can toggle between custom/preset spacing sizes
7. Check in global styles and the site editor as well for good luck.

<details>
<summary>Example theme.json</summary>

```json
{
	"$schema": "../../schemas/json/theme.json",
	"version": 3,
	"settings": {
		"appearanceTools": true,
		"spacing": {
			"spacingSizes": [
				{
					"name": "1",
					"size": "1rem",
					"slug": "10"
				},
				{
					"name": "2",
					"size": "min(1.5rem, 2vw)",
					"slug": "20"
				},
				{
					"name": "3",
					"size": "min(2.5rem, 3vw)",
					"slug": "30"
				},
				{
					"name": "4",
					"size": "min(4rem, 5vw)",
					"slug": "40"
				},
				{
					"name": "5",
					"size": "min(6.5rem, 8vw)",
					"slug": "50"
				},
				{
					"name": "6",
					"size": "min(10.5rem, 13vw)",
					"slug": "60"
				},
				{
					"name": "7",
					"size": "min(10.5rem, 17vw)",
					"slug": "70"
				},
				{
					"name": "8",
					"size": "min(10.5rem, 21vw)",
					"slug": "80"
				}
			],
			"units": ["%", "px", "em", "rem", "vh", "vw"]
		}
	}
}

```
</details>

### With the plugin turned off

Screenshot 2024-08-06 at 11 00 18 AM

### With the plugin turned on (trunk)

Screenshot 2024-08-06 at 11 02 44 AM

### This PR with the plugin turned on

https://github.com/user-attachments/assets/4e94f584-9f58-46cd-8cb2-75c27987e18d

### CODE REVIEW

File: packages/block-editor/src/components/spacing-sizes-control/input-controls/spacing-input-control.js [hunk 1]
```diff
@@ -33,7 +33,7 @@ import {
 } from '../utils';
 import { unlock } from '../../../lock-unlock';
 
-const { CustomSelectControlV2Legacy: CustomSelectControl } = unlock(
+const { CustomSelectControlV2: CustomSelectControl } = unlock(
```
Comment (ramonjd) [inline packages/block-editor/src/components/spacing-sizes-control/input-controls/spacing-input-control.js]: @ciampo Looking at the description in https://github.com/WordPress/gutenberg/pull/63190, should this be using the V1 implementation?

Comment (andrewserong) [reply packages/block-editor/src/components/spacing-sizes-control/input-controls/spacing-input-control.js]: Thanks for looking into this @ramonjd! I was just wondering that from looking at this PR, whether we should be using `CustomSelectControl` as in https://github.com/WordPress/gutenberg/pull/63258 instead of adding `CustomSelectControlV2` to the private APIs at this stage?

I imagine @ciampo or @mirka will know which is preferred 🙂

Comment (t-hamano) [reply packages/block-editor/src/components/spacing-sizes-control/input-controls/spacing-input-control.js]: This problem appears to be solved if we import the `CustomSelectControl` component directly from the `@wordpress/components` package without using unlock. However, I'm not confident about it yet, so I'll wait for feedback from the component team 😅

Comment (ramonjd) [reply packages/block-editor/src/components/spacing-sizes-control/input-controls/spacing-input-control.js]: I think we're asking the same question 😄 

Using ~v1~ "whatever the other version is called these days" is even easier. 

I'll add a commit to save time later. We can swap out one for the other depending on what the components avengers say. 🦸🏻

Comment (ramonjd) [reply packages/block-editor/src/components/spacing-sizes-control/input-controls/spacing-input-control.js]: v1 in [629a94a](https://github.com/WordPress/gutenberg/pull/64284/commits/629a94a4b428d9d95bca7e9c1ca3aa45d932c111)

**Review by andrewserong — APPROVED** [review]
This is working nicely for me in testing, and sure beats an error! Thanks for digging in 👍 

| Before | After |
| --- | --- |
| image | image |

From my perspective I think this is good to land, and we can always follow up with further PRs if need be.

LGTM! 🚀

File: packages/block-editor/src/components/spacing-sizes-control/input-controls/spacing-input-control.js (hunk 1 above)
Comment (mirka) [reply packages/block-editor/src/components/spacing-sizes-control/input-controls/spacing-input-control.js]: Thank you for sorting this out 😱 What you did here is correct!

**Comment by ciampo** [comment]
Thank you for fixing this! It's worrying that this wasn't picked up by linting / testing / building the project 😨 

Definitely something to keep in mind as a potential improvement for `lock`/`unlock`
