### PR TITLE
Navigation: Improve UX on adding links

### LINKED ISSUE #19481: Link Editing Covers the + when Adding Submenu Items
**Describe the bug**
When adding new submenu items in succession, the link edit covers the + to add another submenu item. 

**To reproduce**
1. Add a submenu to a menu item
2. Add the link
3. The + to add another submenu item is covered by the link edit box

To add a new item, I had to click off the submenu, click the top level item to display the submenu, then click the + to add the submenu item.

**Expected behavior**
There should be an easy way to add multiple submenu items in succession. I don't know what the best UX solution would be here (moving the + down? adjusting the position of the edit link box? seems very context dependent).

**Screenshots**
image

**Desktop**
OS: MacOS Catalina - 10.15.2
Browser: Chrome
Version: Gutenberg 7.2.0-rc.1 & 7.1

**Additional context**
Tested locally with built version of master and WordPress Version 5.3.2 with Gutenberg as the only active plugin.

### PR DESCRIPTION
**Pull request by jeryj**
Closes https://github.com/WordPress/gutenberg/issues/19481

## Description
The link control covers up the submenu link + when adding submenu link items. It means that to access the + to add another submenu link, you have to:
- click off of the link to close the link control, 
- then reclick the top navigation item you were working with (because clicking off it closes the submenu list)
- click the +

This PR will be a WIP on testing out different methods. The first one is to move the focus back to wherever it came from after a link is selected on the link control. This means most of the time it ends up on the link text, but if you edit the link from the Link button in the toolbar, it will return there after you make a change.

This is very much a WIP. Currently a kind of playground and discussion for UX iterations on this.

## How has this been tested?
Manually

## Screenshots
return focus on link change

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by shaunandrews** [comment]
This feels nice and more natural. I wonder, could we try selecting the label text rather than just putting the cursor focus at the end? Especially for URLs, I can imagine wanting to completely replace the label by typing right away.

**Comment by jeryj** [comment]
@shaunandrews I like this interaction a lot more as well. I'll try the auto select of the label. I can see how it would be useful to have that, but I could also see how you may not realize it's selected, press a key, and be a bit annoyed it just deleted your label.

**Comment by jeryj** [comment]
@shaunandrews The latest is selecting the entire label text (with the cursor/caret at the end of the text). Selecting text hides the caret though, so it doesn't make it totally obvious what's going on. I personally prefer the caret just placed at the far end of the text so you can delete or add from there.

To quickly change between modes (selecting the label vs placing the caret at the end of the text) go to `packages/block-library/src/navigation-link/edit.js` and set line `71` to false:
```
const _experimentalSelectLabelContentOnChange = true; // true selects the text, false places the caret at the end
```

**Comment by shaunandrews** [comment]
Very cool. I like highlighting the text when adding a link, it feels really natural to me. However, it doesn't seem to work in Safari.

highlight in safari

Here's how it looks in Chrome:

highlight in chrome

**Comment by karmatosed** [comment]
I think this is a definite improvement. Let me remove the feedback label as we seem to have it for design - great iteration.

**Comment by jeryj** [comment]
I have this code in a much better spot. Works in Safari now as well. I've tested Firefox, Safari, and Chrome. Note that the + on adding submenu items is gone due to a new bug of some kind unrelated to this commit: https://github.com/WordPress/gutenberg/issues/19788

**Comment by obenland** [comment]
> I like highlighting the text when adding a link

Interesting, I feel the opposite way. To me it feels like I'm supposed to replace it with something (because why else would the text be highlighted?).

How about not setting the cursor at all and just having the navigation-item be focused?

**Comment by jeryj** [comment]
> To me it feels like I'm supposed to replace it with something (because why else would the text be highlighted?).
I agree with this take for when you select a page from the list. I like the highlighting when you type in a URL though.

I imagine I could add a check to see if it's a URL vs an item chosen from the suggestions.

**Comment by jeryj** [comment]
I've updated a few things:
1. When entering text/url from the add link popover (so, not choosing an option from the suggestions), it will automatically add whatever you entered in the field.
2. If this text looks url-like, the label text will be automatically selected
3. If this text does NOT look url-like, it will place the caret at the end of the text

focus vs select text

**Comment by obenland** [comment]
Nice job, those recent updates feel like they're going in the right direction. 

I can see that you'd want the entire text highlighted when inserting a URL to make it easer add a custom label. Focussing the navigation item as a whole still feels a bit more universally useful, though. I'd worry that folks accidentally delete their labels after inserting a URL

**Comment by jeryj** [comment]
>  I'd worry that folks accidentally delete their labels after inserting a URL

100% agree. I'd rather do the focus on suggestion click and select the text on url insertion. Accidentally deleting the label from a suggestion (which is likely the label you wanted) will be really common IMO if we always go with selecting all the text.

I'd like to move forward with the current implementation (focus on suggestion click, select text on manual url entry) if that's OK.

**Comment by obenland** [comment]
@apeatling Would you mind taking this for a spin? Inserting a URL and a suggested page and share your thoughts?

**Comment by apeatling** [comment]
Having tried this I think it's a big improvement, and we should move ahead with it. Highlighting the text feels natural to me, as I would expect folks would want to change the label. Having the URL you've typed rather than nothing is a smoother experience as a whole.

**Review by obenland — APPROVED** [review]

**Review by apeatling — APPROVED** [review]

**Comment by apeatling** [comment]
Not sure why the other reviewers were removed above, seems like a Github bug.

**Comment by jeryj** [comment]
I rebased and then it wouldn't let me push without a pull. That ended up bringing in _all_ the changes from others as new changes from the other files (111 of them 😳) That may have triggered an automatic review process. I then reverted and force pushed, since that stuff wasn't relevant here.

**Comment by jeryj** [comment]
@WordPress/gutenberg-core I believe this merge is ready to go, but I don't want to merge it via the command line unless I absolutely have to :) Do y'all have advice on the best way forwards here?

File: packages/block-library/src/navigation-link/edit.js [hunk 1]
```diff
@@ -78,6 +80,36 @@ function NavigationLinkEdit( {
...
+				// Focus it (but do not select).
+				placeCaretAtHorizontalEdge( ref.current, true );
+			}
+		}
+	}, [ url ] );
+
+	/**
+	 * Focus the navigation link label text and select it.
+	 */
+	function selectLabelText( ) {
```
Comment (youknowriad) [inline packages/block-library/src/navigation-link/edit.js]: I feel we already have a way to do this using selectors/actions without messing with refs, selection... right @ellatrix ?

File: packages/block-library/src/navigation-link/edit.js [hunk 2]
```diff
@@ -196,8 +229,11 @@ function NavigationLinkEdit( {
 											normalizedTitle !== normalizedURL &&
 											label !== newTitle ) {
 											return escape( newTitle );
+										} else if ( label ) {
+											return label;
 										}
-										return label;
+										// If there's no label, add the URL.
+										return escape( normalizedURL );
 									} )(),
```
Comment (youknowriad) [inline packages/block-library/src/navigation-link/edit.js]: Very weird code style, but this was here before anyway.

**Review by youknowriad — COMMENTED** [review]
Are we certain about this UX? It seems a bit weird to me to ignore the post-link insertion options (like openInNewTab)?

File: packages/block-library/src/navigation-link/edit.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-library/src/navigation-link/edit.js]: Yes, if you have access to the value (if HTML you need to convert to rich text value), the block client ID and attribute key.

Comment (ellatrix) [reply packages/block-library/src/navigation-link/edit.js]: Why does it need to be selected?

Comment (jeryj) [reply packages/block-library/src/navigation-link/edit.js]: It's not about getting the value, but to actually select/highlight the text so that someone can start typing delete the label value. This was discussed here: https://github.com/WordPress/gutenberg/pull/19686#issuecomment-575280635

Can I focus the input on the DOM and highlight/select it without using `ref`s? I'm very new to React and Gutenberg, so any direction is helpful and appreciated :)

File: packages/block-library/src/navigation-link/edit.js (hunk 2 above)
Comment (jeryj) [reply packages/block-library/src/navigation-link/edit.js]: Yeah, just trying to sneak in what I needed in the way that made the most sense :) I'm happy to redo it if you think it'd be cleaner a different way.

**Comment by jeryj** [comment]
@youknowriad It seemed to be the best of the current options, as there was no way to continue adding links due to the appenders being covered up by the popover. The only way to close the popover was to click to a top-level or sibling. 

It's definitely not 100% perfect, but we did appear to have some consensus that this UX flow was a significant improvement over the current one in regards to creating navigation items, and specifically submenu items.

**Comment by apeatling** [comment]
> Are we certain about this UX? It seems a bit weird to me to ignore the post-link insertion options (like openInNewTab)?

It's possible to get back to these via the sidebar, or hitting the link button in the block toolbar. I do think it makes these options less obvious, but the disruption to the flow of adding more links this popover causes is worse.

**Comment by aduth** [comment]
A bit of related commentary at: https://github.com/WordPress/gutenberg/pull/19885#issuecomment-578967785

As far as parallel improvements to the current (previous) implementation:

- I intuitively expect to be able to press <kbd>Escape</kbd> after selecting a link to be able to close the Popover. This currently doesn't work correctly. (See #19931)
- From that point, I might expect to be able to insert a new link simply by pressing <kbd>Enter</kbd>, rather than needing to explicitly click on the "+" button.

File: packages/e2e-tests/specs/editor/blocks/navigation.test.js [hunk 3]
```diff
@@ -65,23 +65,21 @@ async function updateActiveNavigationLink( { url, label } ) {
 		await page.keyboard.press( 'ArrowDown' );
 		// Select the suggestion.
 		await page.keyboard.press( 'Enter' );
-		// Make sure that the dialog is still opened, and that focus is retained
-		// within (focusing on the link preview).
-		await page.waitForSelector(
-			':focus.block-editor-link-control__search-item-title'
-		);
```
Comment (jeryj) [inline packages/e2e-tests/specs/editor/blocks/navigation.test.js]: @aduth I removed this test that was added in https://github.com/WordPress/gutenberg/pull/19931, as with this UX change the `LinkControl` will be automatically closed and the focus moved to the label text.

**Comment by aduth** [comment]
Noting that my comment at https://github.com/WordPress/gutenberg/pull/19462#discussion_r373694597 has quite a bit of overlap with the changes here. In that comment, I discuss the problems associated with a user flow where pressing <kbd>Enter</kbd> upon editing a link would move focus back to the block. In a paragraph block, that would have the result of making it impossible to toggle "Opens in New Tab" without using a cursor (i.e. by keyboard, assistive technologies). I worried that might have been introduced here, but it seems to be fine because the "Link" button in the Navigation Link block's toolbar will always open the link popup.

But, ideally these workflows are consistent for editing links either in a paragraph, or for the Navigation Link block. 

Currently, I foresee the following inconsistencies:

- My leaning for addressing this in the paragraph block is that <kbd>Enter</kbd> should keep the popover open and focused. This would basically be the complete opposite of the changes introduced in this pull request (i.e. it was the previous behavior, if I understand correctly).
- [Conventions in other applications](https://en.wikipedia.org/wiki/Control-K) might lead a user to think that <kbd>Cmd+K</kbd> in a Navigation Link block would put them immediately into the editing mode. Right now, <kbd>Cmd+K</kbd> will shift focus into the Popover, but in its "View" mode. While this can serve as a solution to allow "Open in New Tab" to be accessible by keyboard, it might be contrary to what a user's expectations are.
- A paragraph block's "Link" button will behave as removing the active link. The same button in the Navigation Link block will show the link popover instead. This could be okay, considering that it makes less sense to remove a link from a Navigation Link block than it does to remove a link from a selected text in a paragraph.
