### PR TITLE
Try: Make gallery randomization work when nested

### LINKED ISSUE #58404: Gallery randomization does not work when nested within another block
After testing https://github.com/WordPress/gutenberg/pull/57477, I realized that the gallery block's new randomization feature does not function when the gallery block is nested within another block. 

### Visuals

Here's a video I recorded with the gallery block within a group block (not randomizing):  

https://github.com/WordPress/gutenberg/assets/1813435/892bb3a6-4e8b-475d-bef1-4fd0c0e33b5a

Here's a video of the randomization working, when not nested: 

https://github.com/WordPress/gutenberg/assets/1813435/2b0fb42a-844e-42cf-bd74-a9bd2f57de1b

cc @t-hamano

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #58404

## What?

This PR resolves an issue where the randomization of the Gallery block added in #57477 does not work when nested.

## Why?

Randomization is achieved by shuffling the `$parsed_block['innerBlocks']` via the `render_block_data` hook. However, we found a problem with this hook: it cannot override `$parsed_block['innerBlocks']` when blocks are nested.

This issue is also reported in the core ticket: https://core.trac.wordpress.org/ticket/56417

Ideally, `render_block_data` should be improved, but the impact is probably large and there isn't much time left to fix it in WP6.5.

So in this PR, we will try similar randomization in the render callback function instead of `render_block_data`. If we can't find a good solution, we may need to consider reverting the randomization function.

## How?

Sort theIimage blocks within the content HTML based on the following logic:

- Use `WP_HTML_Tag_Processor` to add a sequential number (`data-image-index`) to elements with the `wp-block-image` class. This is to identify duplicate images when they are included in a gallery.
- Use the `preg_match_all()` function to extract elements with the `data-image-index` attribute, i.e. Image blocks.
- Randomize the extracted Image blocks.
- Use the `preg_replace_callback()` function to extract the Image blocks again and replace each Image block with the randomized Image in turn.
- Finally, use `WP_HTML_Tag_Processor` to remove unnecessary `data-image-index` attributes.

To be honest, this approach may not be perfect for the following reasons:

- What if the user has already given the data-image-index attribute?
- What if the user had rewritten the wp-block-image class?
- What if the user uses the new allowed_blocks to insert something other than an image block?

Let me discuss whether we should ship this approach or bring back the randomization feature. 🙇

## Testing Instructions

- Insert a Gallery block and add images.
- Enable "Randomize order".
- On the front end, check that the image order changes every time you reload the browser.

### CODE REVIEW

File: packages/block-library/src/gallery/index.php [hunk 1]
```diff
@@ -130,7 +116,58 @@ function block_core_gallery_render( $attributes, $content ) {
...
 	);
-	return (string) $processed_content;
+
+	// Randomize the order of image blocks. Ideally we should shuffle
+	// the `$parsed_block['innerBlocks']` via the `render_block_data` hook.
+	// However, this hook doesn't apply inner block updates when blocks are
+	// nested.
+	// TODO: In the future, if this hook supports updating innerBlocks in
+	// nested blocks, it should be refactored.
+	// See: https://github.com/WordPress/gutenberg/pull/58733
```
Comment (aaronrobertshaw) [inline packages/block-library/src/gallery/index.php]:
```suggestion
	// See: https://github.com/WordPress/gutenberg/pull/58733.
```

I get a linting error for the inline comment here not ending in a `.` Is there an official recommendation for adding these reference links. Does it hurt to add the period to the end of it to reduce noise from the linter?

File: packages/block-library/src/gallery/index.php [hunk 2]
```diff
@@ -130,7 +116,58 @@ function block_core_gallery_render( $attributes, $content ) {
...
+	}
+	$content = $processor->get_updated_html();
+
+	$pattern = '/<figure[^>]*\bdata-image-index\b[^>]*>.*?<\/figure>/';
+
+	// Find all Image blocks.
+	preg_match_all( $pattern, $content, $matches );
+	if ( ! $matches ) {
+		return $content;
+	}
```
Comment (aaronrobertshaw) [inline packages/block-library/src/gallery/index.php]:
```suggestion
	preg_match_all( $pattern, $procesed_content, $matches );
	if ( ! $matches ) {
		return $procesed_content;
	}
```

If we aren't parsing and manipulating the gallery content this can just reference the current markup in `$processed_content`.

File: packages/block-library/src/gallery/index.php [hunk 3]
```diff
@@ -130,7 +116,58 @@ function block_core_gallery_render( $attributes, $content ) {
...
+	shuffle( $image_blocks );
+	$i       = 0;
+	$content = preg_replace_callback(
+		$pattern,
+		static function () use ( $image_blocks, &$i ) {
+			$new_image_block = $image_blocks[ $i ];
+			++$i;
+			return $new_image_block;
+		},
+		$content
```
Comment (aaronrobertshaw) [inline packages/block-library/src/gallery/index.php]:
```suggestion
		$processed_content
```
Again, if not manipulating the gallery content before reordering images, this can be the current content.

File: packages/block-library/src/gallery/index.php [hunk 4]
```diff
@@ -130,7 +116,58 @@ function block_core_gallery_render( $attributes, $content ) {
...
+	);
+
+	// Remove the index from each Image block.
+	$processor = new WP_HTML_Tag_Processor( $content );
+	while ( $processor->next_tag( array( 'class_name' => 'wp-block-image' ) ) ) {
+		$processor->remove_attribute( 'data-image-index' );
+	}
+	$content = $processor->get_updated_html();
```
Comment (aaronrobertshaw) [inline packages/block-library/src/gallery/index.php]:
```suggestion
```

Not needed if we aren't manipulating the content unnecessarily.

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for the fix @t-hamano 👍 

✅ I could replicate the issue when a randomized gallery was nested
✅ This PR fixes the issue

I think there's some unnecessary manipulation of the gallery markup which we could avoid. I've left some suggested code tweaks inline but in case it's easier I'll include a diff in this review.

Apologies if I'm missing some logic as to why we need to add and then remove index attributes. 

<details>
<summary>Diff with suggestion changes</summary>

```diff
diff --git a/packages/block-library/src/gallery/index.php b/packages/block-library/src/gallery/index.php
index e3eeeef3f0..464449154a 100644
--- a/packages/block-library/src/gallery/index.php
+++ b/packages/block-library/src/gallery/index.php
@@ -123,27 +123,17 @@ function block_core_gallery_render( $attributes, $content ) {
 	// nested.
 	// TODO: In the future, if this hook supports updating innerBlocks in
 	// nested blocks, it should be refactored.
-	// See: https://github.com/WordPress/gutenberg/pull/58733
+	// See: https://github.com/WordPress/gutenberg/pull/58733.
 	if ( empty( $attributes['randomOrder'] ) ) {
 		return $processed_content;
 	}
 
-	$processor = new WP_HTML_Tag_Processor( (string) $processed_content );
-
-	// Add an index to each figure tag to uniquely identify each Image block.
-	$i = 0;
-	while ( $processor->next_tag( array( 'class_name' => 'wp-block-image' ) ) ) {
-		$processor->set_attribute( 'data-image-index', $i );
-		++$i;
-	}
-	$content = $processor->get_updated_html();
-
-	$pattern = '/<figure[^>]*\bdata-image-index\b[^>]*>.*?<\/figure>/';
+	$pattern = '/<figure[^>]*\bwp-block-image\b[^>]*>.*?<\/figure>/';
 
 	// Find all Image blocks.
-	preg_match_all( $pattern, $content, $matches );
+	preg_match_all( $pattern, $processed_content, $matches );
 	if ( ! $matches ) {
-		return $content;
+		return $processed_content;
 	}
 	$image_blocks = $matches[0];
 
@@ -157,16 +147,9 @@ function block_core_gallery_render( $attributes, $content ) {
 			++$i;
 			return $new_image_block;
 		},
-		$content
+		$processed_content
 	);
 
-	// Remove the index from each Image block.
-	$processor = new WP_HTML_Tag_Processor( $content );
-	while ( $processor->next_tag( array( 'class_name' => 'wp-block-image' ) ) ) {
-		$processor->remove_attribute( 'data-image-index' );
-	}
-	$content = $processor->get_updated_html();
-
 	return $content;
 }
 /**

```
</details>

Here's what I see with the suggested diff applied. The top gallery is nested while the second is a duplicate of the first gallery but as a top level block.

https://github.com/WordPress/gutenberg/assets/60436221/593d02f1-dea8-4df8-befc-7be424bdd4da

File: packages/block-library/src/gallery/index.php [hunk 5]
```diff
@@ -130,7 +116,58 @@ function block_core_gallery_render( $attributes, $content ) {
...
+
+	// Add an index to each figure tag to uniquely identify each Image block.
+	$i = 0;
+	while ( $processor->next_tag( array( 'class_name' => 'wp-block-image' ) ) ) {
+		$processor->set_attribute( 'data-image-index', $i );
+		++$i;
+	}
+	$content = $processor->get_updated_html();
+
+	$pattern = '/<figure[^>]*\bdata-image-index\b[^>]*>.*?<\/figure>/';
```
Comment (aaronrobertshaw) [inline packages/block-library/src/gallery/index.php]:
```suggestion
	$pattern = '/<figure[^>]*\bwp-block-image\b[^>]*>.*?<\/figure>/';
```

This can probably skip the manipulation of the existing markup.

It might also be good to add an inline comment explaining the regex. 

Edit: Missed hitting save when adding this to the original review, sorry.

File: packages/block-library/src/gallery/index.php (hunk 1 above)
Comment (t-hamano) [reply packages/block-library/src/gallery/index.php]: Looking at the entire core and Gutenberg code, it seems like using the `@see` annotation is a good idea. Updated with [5ce2ec0](https://github.com/WordPress/gutenberg/pull/58733/commits/5ce2ec01ef6a74ddaff12a781dd18c7f3e68ebdc).

**Comment by t-hamano** [comment]
Thanks for the review, @aaronrobertshaw!

I think the index-less approach you suggested makes sense and also made the code simpler. I think I've handled everything, but if I've missed anything please let me know.

File: packages/block-library/src/gallery/index.php [hunk 6]
```diff
@@ -130,7 +116,47 @@ function block_core_gallery_render( $attributes, $content ) {
 			'context' => 'block-supports',
 		)
 	);
-	return (string) $processed_content;
+
+	$updated_content = $processed_content->get_updated_html();
```
Comment (t-hamano) [inline packages/block-library/src/gallery/index.php:123]: `$processed_content` should be a `WP_HTML_Tag_Processor` object. However, even without converting to a string on this line, the rest of the processing seems to run correctly and the blocks also are rendered correctly 🤔

Comment (aaronrobertshaw) [reply packages/block-library/src/gallery/index.php:123]: Good catch. It's because the class [implements](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/html-api/class-wp-html-tag-processor.php#L3114) the [`__toString`](https://www.php.net/manual/en/language.oop5.magic.php#object.tostring) function which when the instance is treated as a string just returns the `get_updated_html()` value. 

I think it is better to be explicit here to reduce the potential for the confusion you just highlighted.

File: packages/block-library/src/gallery/index.php [hunk 7]
```diff
@@ -130,7 +116,47 @@ function block_core_gallery_render( $attributes, $content ) {
...
+	 * @todo: In the future, if this hook supports updating innerBlocks in
+	 * nested blocks, it should be refactored.
+	 *
+	 * @see: https://github.com/WordPress/gutenberg/pull/58733
+	 */
+	if ( empty( $attributes['randomOrder'] ) ) {
+		return $updated_content;
+	}
+
+	// Matches figure elements with class `wp-block-image`
```
Comment (aaronrobertshaw) [inline packages/block-library/src/gallery/index.php]:
```suggestion
	// This pattern matches figure elements with the `wp-block-image` class to
	// avoid the gallery's wrapping `figure` element and extract images only.
```

The current comment misses the trailing `.` again so triggers a linting error. I think we could also tweak the comment to reflect a little more of the intent of the regex. What do you think?

**Review by aaronrobertshaw — APPROVED** [review]
🚀 Thanks for the fast turnaround on these changes @t-hamano!

The code is looking good. I left one small comment regarding another new linting error but if that gets tweaked, I'm happy to give this an approval now.

This will also need to get backported in time for 6.5, correct?

One last thing, I think this is the sort of thing that would be good to have some test coverage for. As a follow-up, maybe a unit test could be added? The cover block might provide an example.

File: packages/block-library/src/gallery/index.php (hunk 6 above)
Comment (t-hamano) [reply packages/block-library/src/gallery/index.php:123]: I've updated it by 323cdec, but if I haven't explained it well, feel free to update it 🙇

File: packages/block-library/src/gallery/index.php (hunk 7 above)
Comment (t-hamano) [reply packages/block-library/src/gallery/index.php]: This is definitely easier to understand 👍

**Comment by t-hamano** [comment]
> This will also need to get backported in time for 6.5, correct?

Yes. My understanding is that if we merge this PR now, it will become part of Gutenberg 17.7, so I believe it will automatically reflect this PR as of WP6.5Beta1. Or do I need to backport it first?

> One last thing, I think this is the sort of thing that would be good to have some test coverage for. As a follow-up, maybe a unit test could be added? The cover block might provide an example.

I think unit tests make sense. However, even with randomization enabled, there is a small chance that it will return the markup in exactly the same order, which may make the test a bit unstable 😅

**Comment by aaronrobertshaw** [comment]
> so I believe it will automatically reflect this PR as of WP6.5Beta1

My mistake, I was forgetting this was part of the block library and should, I believe, be covered by the package updates if it makes this Gutenberg release.

Best to get this merged then! 🚢

**Comment by getdave** [comment]
Thanks for being diligent folks. I can confirm this will not require a manual backport because it has merged prior to the RC for Gutenberg 17.7.0.
