### PR TITLE
Commands: Restrict editor UI commands to entity-edit context

### LINKED ISSUE #73716: Command palette: show/hide (blocks) settings is available in wrong context
Somehow related: https://github.com/WordPress/gutenberg/issues/71925

### Description

Some commands are available in the wrong context.

### Step-by-step reproduction instructions

- Go to Site Editor > Templates.
- Engage the command palette.
- Search for show/hide, and you'll get two commands (show/hide the settings + show/hide the block settings). Those commands don't trigger any action in that context.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/36c7bfa0-5e1c-4911-ad9d-7caae9593219

### Environment info

WordPress 6.9. No plugins active other than WordPress Importer 0.9.5.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by oandregal**
Fixes https://github.com/WordPress/gutenberg/issues/73716

## What?

This PR makes sure that editor-related commands are only available in a `entity-edit` context.

## Why?

Otherwise, the commands are listed in places where they don't trigger any action.

## How?

Add `entity-edit` as context in the command registration.

## Testing Instructions

- Go to Site Editor > Templates.
- Engage the command palette.
- Search for show/hide.

In trunk, two commands will be listed (show/hide the settings + show/hide the block settings). The expected result is that they aren't in this branch.

### CODE REVIEW

**Review by senadir — APPROVED** [review]

**Review by t-hamano — APPROVED** [review]
LGTM! I'm curious why [this if statement](https://github.com/WordPress/gutenberg/blob/7f07bca4d64b88a6cb64568b59eb8fc2fba9666a/packages/editor/src/components/commands/index.js#L96-L98) that checks whether we're in preview mode didn't work, but I think this fix will work for now.

File: packages/editor/src/components/commands/index.js [hunk 1]
```diff
@@ -455,6 +455,7 @@ export default function useCommands() {
 	useCommandLoader( {
 		name: 'core/editor/edit-ui',
 		hook: getEditorCommandLoader(),
+		context: 'entity-edit',
```
Comment (youknowriad) [inline packages/editor/src/components/commands/index.js:458]: This actually doesn't restrict the commands, you can still search for them. What "context" does is that these commands are made "visible" by default when you open the command palette in that context.

Comment (oandregal) [reply packages/editor/src/components/commands/index.js:458]: Interesting. With this change, the commands aren't displayed for me even in search (before they did). What would that be?

Do you think we should revert this so the default list displayed in the editors is shorter?

Comment (t-hamano) [reply packages/editor/src/components/commands/index.js:458]: > Do you think we should revert this so the default list displayed in the editors is shorter?

Let's revert this PR if we can't find an ideal approach by next Wednesday, when GB 22.3 RC1 is released. I have a vague idea of ​​what's causing this: `isPreviewMode` isn't working as intended on certain screens.

Comment (youknowriad) [reply packages/editor/src/components/commands/index.js:458]: > Interesting. With this change, the commands aren't displayed for me even in search (before they did). What would that be?

So I didn't test, my comment was more "I made this API kind of thing" :P now, I didn't keep up with all the changes, so it's possible that it was updated afterwards or something but context was definitely not implemented to "restrict visibility"
