### PR TITLE
DataViews: Fix author sorting in templates and template parts

### LINKED ISSUE #57978: Templates data view: Switching author sort order doesn't always work
https://github.com/WordPress/gutenberg/assets/846565/a2af60ec-cfaa-4fdc-aba7-39d1ad323cfb

To reproduce:

1. Enable data views experiment
2. Navigate to Appearance > Templates 
3. In View Options (or table header as in the video above) attempt to sort by author
4. Notice sorting only works if the data was previously sorted by another field
5. Notice that switching from asc to desc (and vice versa) doesn't work

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/57978

## Testing Instructions
1. Navigate to Manage all templates
2. Test that sorting by author works properly.
3. Do the same for the template parts view

### CODE REVIEW

File: packages/edit-site/src/components/page-templates-template-parts/index.js [hunk 1]
```diff
@@ -374,7 +374,7 @@ export default function PageTemplatesTemplateParts( { postType } ) {
 				data: filteredData,
 				view,
 				fields,
-				textFields: [ 'title' ],
+				textFields: [ 'title', 'author' ],
```
Comment (oandregal) [inline packages/edit-site/src/components/page-templates-template-parts/index.js:377]: I think this can work for now, but we could follow-up to do the following:

- add `text` type to fields
- remove `textFields` from `sortByTextFields`

**Review by oandregal — APPROVED** [review]

File: packages/edit-site/src/components/page-templates-template-parts/index.js (hunk 1 above)
Comment (oandregal) [reply packages/edit-site/src/components/page-templates-template-parts/index.js:377]: Now that I look at this utility, `sortByTextFields` can probably become `sortByField` with more type field info.

Comment (ntsekouras) [reply packages/edit-site/src/components/page-templates-template-parts/index.js:377]: It's not that straightforward right now because `author` is an `type:enumeration`. Maybe we could explore if we could use `getValue` for those fields too, but we would need to think of what other use cases we could have..

Comment (mcsf) [reply packages/edit-site/src/components/page-templates-template-parts/index.js:377]: I agree with removing `textFields`. It's true that not all enums behave like regular text fields, but we can approach this more generally. Also, is sort-by-author currently sorting by the _username_? What about display name?

Comment (ntsekouras) [reply packages/edit-site/src/components/page-templates-template-parts/index.js:377]: For templates and template parts we use the [author_text](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.5/rest-api.php#L81), which is a custom implementation due to the different kind of authors. For example for theme items the actual persisted value in db is `author:0`, but we extract the theme name as author.
