### PR TITLE
Metaboxes: Hold jQuery ready only if there are metaboxes

### LINKED ISSUE #3465: Intermittent failure "Cannot read property hasClass of undefined"
## Issue Overview

Gutenberg is throwing an error intermittently if Chrome inspector tools are showing. The failure is probably relatively irrelevant to the rest of the Gutenberg page, so it isn't noticeable unless the inspector is open.

It seems to be related to heartbeat. Specifically, this code:

```
var e, f;
    a(document).on("heartbeat-tick.wp-auth-check", function(a, f) {
        "wp-auth-check"in f && (d(),
        !f["wp-auth-check"] && e.hasClass("hidden") ? b() : f["wp-auth-check"] && !e.hasClass("hidden") && c())
    }).on("heartbeat-send.wp-auth-check", function(a, b) {
        (new Date).getTime() > f && (b["wp-auth-check"] = !0)
    }).ready(function() {
        d(),
        e = a("#wp-auth-check-wrap"),
        e.find(".wp-auth-check-close").on("click", function() {
            c()
        })
```

## Steps to Reproduce (for bugs)

1. Create a new post
2. Open the Chrome inspector
3. Do things, move the mouse, open the block inserter .... talk to people 
4. Wait

Apologies for not giving a better replication case, but it really is intermittent!

### PR DESCRIPTION
**Pull request by youknowriad**
closes #3465

We hold jQuery ready event when we have metaboxes still being loaded but this breaks the heartbeat script since we never trigger the "ready" event if we do not have metaboxes.

This PR fixes the issue by holding the "ready" event only if we have metaboxes.

### CODE REVIEW

File: editor/effects.js [hunk 1]
```diff
@@ -280,6 +277,12 @@ export default {
 
 		return effects;
 	},
+	INITIALIZE_META_BOX_STATE( action ) {
+		// Hold jquery.ready until the metaboxes load
+		if ( action.metaBoxes.side || action.metaBoxes.normal ) {
```
Comment (aduth) [inline editor/effects.js]: Do we need to account for `action.metaBoxes.advanced` ? I guess we're not showing these?

Otherwise this could work well:

```js
if ( some( action.metaBoxes ) ) {
```

**Review by aduth — APPROVED** [review]
Finding this to be another case where refx would be better suited to fire effects _after_ the original action occurs. As implemented here, it means we could create a selector to reuse between `META_BOX_LOADED` and `INITIALIZE_META_BOX_STATE` to find `getUnloadedMetaBoxes` to determine if there is anything pending load.

I still don't really understand the purpose of `holdReady`, but if we're assuming it should be holding so long as there are unloaded meta boxes, then I agree with the change that it should only hold in the first place if there _are_ meta boxes.

File: editor/effects.js (hunk 1 above)
Comment (youknowriad) [reply editor/effects.js]: I found that "advanced" and "normal" are the showing the same metaboxes somehow. We're still not showing the metaboxes supposed to appear under the title but I'm not sure how these are registered.
