### PR TITLE
Fix memory leaks in `<Iframe>`

### LINKED ISSUE #53382: Memory leaks in `Iframe` and `BlockPreview`
### Description

While playing with ideas of potentially improving the performance of `<BlockPreview>`, I discovered that the `<Iframe>` component from the `block-editor` package is leaking memory.

This is especially noticeable when loading lots of patterns, which render `<BlockPreview>`s and `<Iframe>`s under the hood. Memory leaks can cause the page to feel heavy and unresponsive, then eventually stop working when it reaches the browser's limits. This is also worse in Site Editor where we rely on client side navigation and never give the browser chance to nuke everything.

I have some leads regarding identifying the code that causes the leaks, but none are proven yet. I can continue to find them if given more time, but decided to open an issue first for awareness.

### Step-by-step reproduction instructions

1. Open a block editor (post or site)
2. Open your desired memory leak detection tool. For chrome devtools it can be the "Performance Monitor" tab and observe the live document frames or JS heap size, or it can also be the "Memory" tab and take snapshots of the before and after then compare them.
3. Open the global inserter and load a set of block patterns (which renders `<BlockPreview>` -> `<Iframe>`).
4. Close the inserter to unmount the patterns (thus unmounting `<BlockPreview>` and `<Iframe>`)
5. Repeat the process of steps (2) ~ (3) for a few times
6. Notice that the memory keeps growing and never gets garbage collected. The number of document frames also keeps increasing and never gets freed.

### Screenshots, screen recording, code snippet

Using the "Performance Monitor" tab:

https://github.com/WordPress/gutenberg/assets/7753001/2e0e76b3-eda4-45d1-b5c0-560bc31a57fe

Using the "Memory" tab record the heap snapshots:

https://github.com/WordPress/gutenberg/assets/7753001/6844dcbd-2438-415f-82d4-467d3c4238cb

### Environment info

- WordPress trunk, gutenberg trunk (production build)
- macOS, Microsoft Edge, and Brave.
- Theme: twentytwentytwo

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by kevin940726**
## What?

Fix (some) memory leaks in the `<Iframe>` component. Though not completely fixed, I think we can still close https://github.com/WordPress/gutenberg/issues/53382 in this PR.

## Why?

Memory leaks crash users' browsers with lower-end devices or limited available resources. The memory leaks this PR fixed leak the iframe `document` for each `<BlockPreview>`, which means the whole DOM tree and the whole document frame cannot be freed even when it's navigated away or unmounted.

## How?

There are two separate fixes 1e4d8dc8aec1fc43cf301fefca62dd2ac50b37cf and e5e9e6fe7e32e337b12eed1a912f4c70a1d25c04. I'll share more details about them in the inline comments below.

## Testing Instructions

Follow the instructions in #53382.

Note that both commits need to be applied for the fix to work since they leak the same document. Try disabling any one of them and see that the document is still leaked.

### Testing Instructions for Keyboard

Same as above.

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/7753001/113ff258-82bd-42f6-b60c-911c6e1bb53c

You can see that there are still around 2KB of leaks, but the majority are fixed now.

### CODE REVIEW

File: packages/block-editor/src/components/iframe/index.js [hunk 1]
```diff
@@ -167,6 +167,7 @@ function Iframe( {
 		node.addEventListener( 'load', onLoad );
 
 		return () => {
+			delete node._load;
```
Comment (ellatrix) [inline packages/block-editor/src/components/iframe/index.js:170]: Why does not doing this prevent the node from being removed from memory? When React removes the iframe, this callback is removed as well?

This reminds me of https://github.com/WordPress/gutenberg/pull/27544#discussion_r537520633

That said, it doesn't hurt of course, I'd just like to understand why.

File: packages/components/src/style-provider/index.tsx [hunk 2]
```diff
@@ -12,19 +11,27 @@ import * as uuid from 'uuid';
...
+	let key = uuid.v4().replace( /[0-9]/g, '' );
+	while ( uuidCache.has( key ) ) {
+		key = uuid.v4().replace( /[0-9]/g, '' );
+	}
+	uuidCache.add( key );
+
+	const cache = createCache( { container, key } );
+	containerCacheMap.set( container, cache );
+	return cache;
+};
```
Comment (ellatrix) [inline packages/components/src/style-provider/index.tsx:34]: Cc @sarayourfriend 

@dmsnell Weren't you talking about emotion going crazy? Does this fix it?

Comment (ellatrix) [reply packages/components/src/style-provider/index.tsx:34]: @kevin940726 Is there any way we could tests this to prevent regressions? 🤔

File: packages/components/src/style-provider/index.tsx [hunk 3]
```diff
@@ -3,7 +3,6 @@
  */
 import { CacheProvider } from '@emotion/react';
 import createCache from '@emotion/cache';
-import memoize from 'memize';
```
Comment (ellatrix) [inline packages/components/src/style-provider/index.tsx:6]: Memoize should never be used for anything except if when defining a max size imo. Always creates memory problems. Maybe we should add a rule to at least always define the maxSize option.

**Review by ellatrix — APPROVED** [review]

File: packages/components/src/style-provider/index.tsx (hunk 2 above)
Comment (dmsnell) [reply packages/components/src/style-provider/index.tsx:34]: yeah I suppose this could be a source of the leak.

I never thought about `memize` being unbounded, though it looks like it does allow us to pass [a `maxSize` option as the second argument](https://github.com/aduth/memize/blob/master/index.js#L133) which will bound it such that it purges the least-recently-used entry when adding into the cache.

in other words, maybe it would be worth attempting this change first as this

```diff
 const memoizedCreatedCacheWithContainer = memoize(
 	( container: HTMLElement ) => { … },
+	{ maxSize: 1000 }
 }
```

seems like both approaches might resolve the memory leak, though this one is a smaller change.

using a `WeakMap` for the container cache does seem better though, since we could plausibly hold a number of references for nodes that are gone, and yeah, that could hold onto the entire iframe. yikes.

nevermind what I said. you found gold @kevin940726

Comment (ellatrix) [reply packages/components/src/style-provider/index.tsx:34]: Well, WeakMap is a superior solution if it can be used. But yes, maybe we should always require a maxSize option for memoize https://github.com/WordPress/gutenberg/pull/53406#discussion_r1286726012

Comment (dmsnell) [reply packages/components/src/style-provider/index.tsx:34]: are we defeating the purpose of the `WeakMap` by storing the container inside the cache?

`WeakMap` allows the release of the keys, but not the values. do we need to store a `WeakRef` to the container instead of the container itself?

does emotion allow this?

Comment (kevin940726) [reply packages/components/src/style-provider/index.tsx:34]: I don't think `maxSize` prevents the memory leak. It simply adds an upper bound of what this cache can hold until it starts trimming the old ones (or just stop caching?). A `maxSize` of `1000` will still unnecessarily leak at most 1000 detached documents, which is still a lot. Making the value of `maxSize` smaller doesn't help either as it will just defeat the purpose of such cache.

AFAIK, `WeakMap` does allow values to be garbage collected. See this section of the [MDN doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap#why_weakmap):

> By contrast, in a `WeakMap`, a key object refers strongly to its contents as long as the key is not garbage collected, but weakly from then on. As such, a `WeakMap`:
>
> - does not prevent garbage collection, which eventually removes references to the key object
> - allows garbage collection of any values if their key objects are not referenced from somewhere other than a `WeakMap`

Comment (kevin940726) [reply packages/components/src/style-provider/index.tsx:34]: > Is there any way we could tests this to prevent regressions? 

I believe we can test this some way or another in the performance test suite (c.c. @WunderBart). Though I would rather keep it in another PR since it's not trivial to do 😆.

**Comment by kevin940726** [comment]
Well, I intended to add inline comments but @ellatrix beat me to it 😆 . (Thx!)

File: packages/block-editor/src/components/iframe/index.js (hunk 1 above)
Comment (kevin940726) [reply packages/block-editor/src/components/iframe/index.js:170]: This is a tricky one that's several levels deep. I'm not entirely sure why this fix helps either! I'll try to post more details after I have a clearer vision.

File: packages/components/src/style-provider/index.tsx (hunk 2 above)
Comment (sarayourfriend) [reply packages/components/src/style-provider/index.tsx:34]: Excellent catch :+1: +100% to adding a rule to require max size on memoisation functions and/or to strongly suggest a fall back to a WeakMap. It is really a much better, harder to screw-up option for simple, single-argument cases like this.

File: packages/block-editor/src/components/iframe/index.js (hunk 1 above)
Comment (kevin940726) [reply packages/block-editor/src/components/iframe/index.js:170]: Okay, I still don't fully understand what happened. It seems to require a very specific setting to make it reproducible. For instance, there has to be a `.focus()` call on a `<input>` somewhere, the iframe has to be rendered under a condition and a wrapper, etc. This might also only be reproducible in a chromium-based browser.

However, we can still learn from this mistake and prevent it from happening again by following the general best practice: don't cross-reference between parent and child frames. In particular, the `window.frameElement` call is the code smell we want to avoid. Instead, use [`postMessage`](https://web.dev/detached-window-memory-leaks/#solution-postmessage) to communicate to the parent frame. In this case though, deleting `node._load` has the same effect, and it's easier than refactoring to `postMessage`.

File: packages/components/src/style-provider/index.tsx (hunk 2 above)
Comment (dmsnell) [reply packages/components/src/style-provider/index.tsx:34]: > WeakMap does allow values to be garbage collected

thanks for double-checking @kevin940726 - it was late when I was reading through the docs and I wasn't sure that holding the key as part of a value would remain weak.

so a fair amount of time has passed between when I wrote the previous sentence and now. I've done some testing in Safari and Chrome. testing was hard because at least in Chrome, the JavaScript engine seems to overlook small `WeakMap` instances, so I [took a suggestion](https://stackoverflow.com/a/72305723) and filled one up before manually triggering collection.

we have marginal insight here because the browser consoles show the contents of the `WeakMap`, which is something we can't do in code for obvious reasons. here's the summary of my testing:

 - yes they do let go of references to the objects if they are values of the `WeakMap`
 - but at least during some test runs it stubbornly held on to the references longer than I expected. this was worse when the values were `weakmap.set( o, { o, i } )` than when they were simpler as `weakmap.set( o, o )`
 - if the object is referenced in the value of some other key then it doesn't seem to let go. that is, `weakmap.set( b, [ a, b ] ); a = null;` leaves `a` allocated and it won't seem to free it until I also clear `b = null`
 - at times I would see this stubborn clinging lead to multiple copies of `c` in the `WeakMap` long after `a` and `b` were purged and long after each copy of `c` had been set as `c = null` and manual garbage collection was run. that is, the `WeakMap` can be leaky in this regard through multiple garbage collection cycles.

after a while of testing I found that things freed up more reliably when I tried. I'm guessing this could be related to the engine warming up.

in the process I found [`FinalizationRegistry()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) which is really neat and I didn't know it existed. All of the debugging tools around garbage-collection though are intentionally blurry and non-deterministic. for a while I saw no finalization events, then they started appearing after several trial runs. browsers stress out to ensure we don't count on this behavior.

so take this as validation that we should be good here, but we also in general probably want to make sure we don't store the same object in two `WeakMap` values or they won't get freed until both `WeakMap` keys have been released.

File: packages/components/src/style-provider/index.tsx (hunk 3 above)
Comment (dmsnell) [reply packages/components/src/style-provider/index.tsx:6]: > A maxSize of 1000 will still unnecessarily leak at most 1000 detached documents, which is still a lot.

as @kevin940726 noted, this still leaves ample room for memory bloat, but I think it's better than uncapped memoization. maybe we can look into places where we use it and analyze each situation to figure out a reasonable cap.

File: packages/components/src/style-provider/index.tsx (hunk 2 above)
Comment (kevin940726) [reply packages/components/src/style-provider/index.tsx:34]: @dmsnell Thanks for the validation!

If you're using chrome devtools, clicking on the bin icon shown in my video will force garbage collection, which is consistent and instant in my testing. Another thing is that some browsers (chromium-based for instance) only collect garbage every 20 seconds even when you use some advanced memory API. So that might be the reason why you're getting the results late.

> but we also in general probably want to make sure we don't store the same object in two `WeakMap` values or they won't get freed until both `WeakMap` keys have been released.

Yep! This is working as expected because the value is still reachable by the other key. `WeakMap` is probably a rare advanced API that we don't normally use, but it fits perfectly in this case IMO.

Comment (dmsnell) [reply packages/components/src/style-provider/index.tsx:34]: > clicking on the bin icon shown in my video will force garbage collection

right, but I saw plenty of cases where garbage collection didn't free the items in the `WeakMap`, which is something indicated in the docs too. they have their own heuristics for when to purge the entries and I was testing those out to see what it's like. so clicking on the button triggered garbage collection, but in many cases left the values in the `WeakMap` for some time - and for the most part, until the `WeakMap` was big enough that it was "heavy" and warranted purging.

maybe this appears in some of our measurements as retaining values too long, but those values aren't strong references so they could be purged at any time. the measurements might at times be misleading.
