### PR TITLE
Block Editor: Fix 'isBlockSubtreeDisabled' private selector

### LINKED ISSUE #54561: Any (synced) block patterns in a post stops blocks deeply nested in `templateLock: contentOnly` parents from being editable
### Description

If I have a structure like:

```html
<!-- wp:group {"templateLock":"contentOnly","layout":{"type":"default"}} -->
<div class="wp-block-group">
  <!-- wp:group {"layout":{"type":"constrained"}} -->
  <div class="wp-block-group">
    <!-- wp:paragraph -->
    <p>Some text</p>
    <!-- /wp:paragraph -->
  </div>
  <!-- /wp:group -->
</div>
<!-- /wp:group -->
```

The paragraph block's text is editable.

However, when adding a synced block pattern to the content, the paragraph block is no longer editable – the immediate parent `core/group` block has `inert="true"` and `is-editing-disabled` HTML class applied to it. I have only tested with synced block patterns. It could well be the same for unsynced.

### Step-by-step reproduction instructions

1. Create a synced block pattern in the site editor with any content.
2. Create a new page.
3. Switch to the code editor, paste in the code mentioned previously.
4. Switch back to visual editor and notice that the paragraph content can be edited.
5. Add the synced block pattern from step 1 into the page content.
6. Try to edit the paragraph content now and observe how it cannot be edited.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/11310624/1ad35a86-3ef4-4593-8bd5-6dc065111822

### Environment info

Replicated in:

- WordPress 6.3.1
- WordPress Playground 6.3
- Chrome Version 116.0.5845.188 (Official Build) (64-bit)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Fixes #54561.

PR fixes a bug with the `isBlockSubtreeDisabled` private selector incorrectly marking deeply nested blocks in the `contentOnly` template locked parent as non-editable.

## Why?
The selector had two issues:

1. It was returning a stale value because of missing dependencies. The first commit (4d5d02024e31f7601799608946faaf225e125257) confirms that the block isn't editable even when a synced pattern isn't present in the canvas.
2. The block editing mode condition for child blocks needed to be improved. The `getBlockEditingMode` checks blocks for attributes with content roles.

## How?
1. Update memoized selector dependencies.
3. Use `getBlockEditingMode` for the child block checks.

## Testing Instructions
1. Open a post or page.
4. Add example content.
5. Confirm that the nested Paragraph block is editable.
6. Add a synced pattern to the canvas.
7. Confirm that the paragraph is still editable.

### Example content

```html
<!-- wp:group {"templateLock":"contentOnly","layout":{"type":"default"}} -->
<div class="wp-block-group">
  <!-- wp:group {"layout":{"type":"constrained"}} -->
  <div class="wp-block-group">
    <!-- wp:paragraph -->
    <p>Some text</p>
    <!-- /wp:paragraph -->
  </div>
  <!-- /wp:group -->
</div>
<!-- /wp:group -->
```

### Testing Instructions for Keyboard
Same

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/240569/88f5bd4c-501c-4d9d-b130-11e44ab34e71

### CODE REVIEW

File: packages/block-editor/src/store/private-selectors.js [hunk 1]
```diff
@@ -45,9 +45,8 @@ export function getLastInsertedBlocksClientIds( state ) {
 export const isBlockSubtreeDisabled = createSelector(
 	( state, clientId ) => {
 		const isChildSubtreeDisabled = ( childClientId ) => {
-			const mode = state.blockEditingModes.get( childClientId );
 			return (
-				( mode === undefined || mode === 'disabled' ) &&
+				getBlockEditingMode( state, childClientId ) === 'disabled' &&
```
Comment (ramonjd) [inline packages/block-editor/src/store/private-selectors.js:49]: Just checking, is the `mode === undefined` check not required anymore? 

`getBlockEditingMode()` can still try to fetch from the `blockEditingModes` Map:  `state.blockEditingModes.get( childClientId )` which will return `undefined` if the key returns no value.

Just by reading the previous check, it seems to say, "if the parent's mode is not yet  known, or has never been set, flag the tree as disabled if all the children are disabled"

Then again, I went through the test description of the [PR that introduced the selector](https://github.com/WordPress/gutenberg/pull/51079), and things still work as expected.

What do you think?

**Review by ramonjd — APPROVED** [review]
Thanks for catching this @Mamaduka 

### Before

I can't edit the content inside a contentOnly locked template!

https://github.com/WordPress/gutenberg/assets/6458278/db128ae4-2ed3-4475-b390-4485a52bf3aa



### After

Now I can edit the content inside a contentOnly locked template!

https://github.com/WordPress/gutenberg/assets/6458278/f9551286-9a32-41a8-8d63-ddc2b647fb38

Just left a question about the changed condition inside the selector.

File: packages/block-editor/src/store/private-selectors.js (hunk 1 above)
Comment (Mamaduka) [reply packages/block-editor/src/store/private-selectors.js:49]: I read through all PRs that touched this code and couldn't find the exact reason why the first check used the `getBlockEditingMode` selector and the child subtree did not.

> Just by reading the previous check, it seems to say, "if the parent's mode is not yet known, or has never been set, flag the tree as disabled if all the children are disabled"

This was causing false positives in the case. The paragraph mode is `undefined`, but the check for its children will also resolve to `true` because `[].every( condition ) === true`.

Comment (ramonjd) [reply packages/block-editor/src/store/private-selectors.js:49]: > This was causing false positives in the case. The paragraph mode is undefined, but the check for its children will also resolve to true because [].every( condition ) === true.

Ah okay. I just wasn't sure whether a block tree whose children are disabled but whose parent isn't could be classed as "disabled". The function name implies it, but as you say there'd have to be further checks. If it's not being used this way, then it seems safe.

Thanks for confirming!

**Comment by mikachan** [comment]
I just cherry-picked this PR to the release/16.7 branch to get it included in the next release: 9b9931f643
