### PR TITLE
DOM: Limit single tabbable radio input by name

### LINKED ISSUE #6988: focus.tabbables fails when the tabbables collection is made of only radio buttons
Splitting this out from #6987 

There's a problem with the `focus.tabbables` implementation when the tabbables are exclusively radio buttons. This is clearly visible in the "Visibility setting" when switching to the #6987 branch (see also screenshot below).

Radio buttons are technically "tabbables" but in a set of grouped radio buttons it's actually possible to tab into just one of them. In this case, the current implementation fails as `focus.tabbables` returns a collection of 3 elements but only one of them can be "tabbed" into:

screen shot 2018-05-28 at 17 17 14

While technically all the radio buttons are tabbable, the current behavior doesn't help so much and in some cases it defeats the purpose of having such a tool. Gutenberg uses `focus.tabbables` mainly to get the next or previous tabbable elements and manage focus accordingly.

In the above scenario, the three radio buttons should be considered 1 tabbable element, to match the native browsers behavior.

### PR DESCRIPTION
**Pull request by aduth**
Closes #6988 

This pull request seeks to enhance the behavior of `tabbables.find` to include only a single radio input for a given name, preferring the checked input, falling back to the first in the tabindex-sorted set.

**Testing Instructions:**

Repeat both sets of Steps to Reproduce from https://github.com/WordPress/gutenberg/issues/6988#issuecomment-467521131 , verifying the expected behavior.

### CODE REVIEW

**Review by afercia — APPROVED** [review]
From an accessibility perspective, works nicely. Tested on the Visibility panel: tabbing is now constrained within the panel. Wish there was a simpler way to solve it 😬 It's self container. Has test. Brilliant, thanks.
(will leave code review to the author himself 😉)

File: packages/dom/src/tabbable.js [hunk 1]
```diff
@@ -30,6 +35,46 @@ function getTabIndex( element ) {
 export function isTabbableIndex( element ) {
 	return getTabIndex( element ) !== -1;
 }
+/**
```
Comment (youknowriad) [inline packages/dom/src/tabbable.js]: Nit: An empty line above maybe

**Review by youknowriad — APPROVED** [review]
