### PR TITLE
Block Editor: Fix block search for non-Latin characters

### LINKED ISSUE #44644: Searching for blocks stopped working for Cyrillic from 14 version
### Description

Version 13.9.0:
image

Version 14+:
image

There has been a similar problem for a long time: https://github.com/WordPress/gutenberg/issues/10775

### Step-by-step reproduction instructions

See above.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Fixes #44644.

I've restored the usage of `lodash.words` instead of `noCase`; the latter [only supports Latin characters](https://github.com/blakeembrey/change-case/issues/289).

We'll need to find a better alternative for `_.words`.

P.S. I've also added a test case for `getNormalizedSearchTerms` to avoid regressions.

## Testing Instructions
1. Switch the site language to one that uses non-Latin characters - Chinese, Cyrillic, Greek, Georgian, etc.
2. Open a Post or Page.
3. Open the block inserter.
4. Type the block name in that language.
5. Confirm that block search works.

_I tested with Georgian (`ქართული`). The testing terms were Media (`მედია`) and List (`სია`)._

## Screencast

https://user-images.githubusercontent.com/240569/193654453-b6a0e85b-a8e7-48ef-8bd7-2460a7704792.mp4

### CODE REVIEW

**Comment by sgomes** [comment]
Thank you, @Mamaduka! 👍 That is a pretty severe limitation in `change-case` that it really should point out.

It might be possible to keep using `change-case`, however, as long as we tweak it with the `options` optional parameter: https://github.com/blakeembrey/change-case#options

We'll need a better regexp for `splitRegexp` that takes into account non-latin characters. We could use unicode character properties like `\p{Uppercase Letter}`, but we should be mindful of bundle sizes; depending on the target browsers, this may cause some large polyfills to be added, which would negate the benefits of removing `lodash`.

**Comment by Mamaduka** [comment]
@sgomes, I'm sure we can find or come up with a good replacement for `_.words`, but for WP 6.1, I would recommend just reverting back to `lodash`.

**Comment by sgomes** [comment]
> @sgomes, I'm sure we can find or come up with a good replacement for `_.words`, but for WP 6.1, I would recommend just reverting back to `lodash`.

Right, no argument there from me 👍 Sorry I wasn't clear, just thinking ahead a bit 🙂

**Review by tyxla — APPROVED** [review]
Thanks for the fix, and for the test, @Mamaduka!

I agree that we should fix this for 6.1 and seek a better replacement of `_.words()` afterwards. I'm happy to work on one.

**Review by aristath — APPROVED** [review]

**Comment by Mamaduka** [comment]
Thanks for the reviews and feedback!

File: packages/block-editor/src/components/inserter/test/search-items.js [hunk 1]
```diff
@@ -42,6 +42,10 @@ describe( 'getNormalizedSearchTerms', () => {
 			getNormalizedSearchTerms( '  Média  &   Text Tag-Cloud > 123' )
 		).toEqual( [ 'media', 'text', 'tag', 'cloud', '123' ] );
 	} );
+
+	it( 'should support non-latin letters', () => {
+		expect( getNormalizedSearchTerms( 'მედია' ) ).toEqual( [ 'მედია' ] );
+	} );
```
Comment (ockham) [inline packages/block-editor/src/components/inserter/test/search-items.js:48]: ❤️

**Comment by ockham** [comment]
I just cherry-picked this PR to the wp/6.1 branch to get it included in the next release: db4455ad2d

**Comment by tyxla** [comment]
I've worked on a second take to remove `_.words()` - see #42467. Would love some testing in Georgian, if you get a chance, @Mamaduka 🙌
