### PR TITLE
Have `createNewPost` wait for editor canvas contents

### LINKED ISSUE #51933: Local e2e tests `createNewPost()` not waiting for the page to be fully loaded
### Description

When running the e2e tests locally, I often have to set a breakpoint or `await page.pause()` immediately after the `createNewPost()`. Otherwise, the test will fail since it's trying to do things to the page (typing, inserting blocks, etc) before the editor is ready for it to be doing those steps. I had thought it was only happening to me, but @scruffian and I paired and I can see the same issue happening on his setup.

So, I think we need to add some kind of "page ready" for `createNewPost`. A lot of the tests seem to start with the expectation that the title is focused, so one potential would be adding an await for the post title to be focused.

### Step-by-step reproduction instructions

1. Pick an e2e test that relies on `createNewPost()` and run it locally, such as `npm run test:e2e:playwright -- -g "can be created by selecting text and using keyboard shortcuts"`.
2. The test will fail at the first assertion or element being missing, as it will do all the things in the test like typing and inserting blocks until it has to do something it can't locate. For example, if you create a post and start typing, it'll allow typing, but what you're typing won't appear on the page. What you're typing will only appear on the page once the editor is fully loaded. We need to wait until the page is fully loaded and the editor is ready before continuing with the test.
3. Add `await page.pause()` after the `createNewPost()`. 
4. Run the same test again
5. When you see the debugger popover, press Play to continue the test past the breakpoint. 
6. The test will pass since you allowed time for the editor to be fully loaded.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by stokesman**
## What?
Improvements to e2e testing (Playwright utils) and some test/plugin updates.

Right now, this only updates `createNewPost` for Playwright and so I don't know if it completely resolves #51933, because I suppose the Puppeteer version may need the same sort of update.

## Why?
On my modest laptop, it’s almost the rule that tests using `createNewPost` get derailed by the late appearance of the editor canvas’s contents and waiting for them alleviates it. In CI, this doesn't seem to happen too often but better that it never does.

## How?
af06387 updates `createNewPost` to wait on an element that's inside the iframe instead of an element outside of it.
Doing so makes some other tests fail because they register blocks that trigger the non-iframed canvas.

bbe171a, d1f38a1, c9f7a12, 3e32458 update tests/plugins to register blocks with `apiVersion` `3` so they'll use the iframed editor canvas.

Then there was a final test failing that I couldn't find a way to have run with the iframed editor canvas. So I resorted to b937013 which allows a consumer to configure which canvas is awaited in `createNewPost` and 3fdf738 which uses that option in the test for meta box saving.

### Further details
b937013 means that the updates to blocks’ `apiVersion` aren’t necessary but the work was already done and it seems okay to run those with the iframed canvas. I'd be fine with reverting those if we'd rather reduce the changes.

## Testing Instructions
```shell
npm run test:e2e:playwright
```

### CODE REVIEW

**Comment by jeryj** [comment]
Haven't gone through the code, but I tested it quickly locally and it fixes https://github.com/WordPress/gutenberg/issues/51933 for me! Thanks for working on this!

File: packages/e2e-test-utils-playwright/src/admin/create-new-post.js [hunk 1]
```diff
@@ -29,7 +31,11 @@ export async function createNewPost( {
 	} ).slice( 1 );
 
 	await this.visitAdminPage( 'post-new.php', query );
-	await this.page.waitForSelector( '.edit-post-layout' );
+	const canvasRoot = legacyCanvas
+		? this.page
+		: this.page.frameLocator( '[name=editor-canvas]' );
+
+	await canvasRoot.locator( '.editor-styles-wrapper' ).waitFor();
```
Comment (kevin940726) [inline packages/e2e-test-utils-playwright/src/admin/create-new-post.js]: Could we wait for something more accessible than a style wrapper? I'm not sure what we should be looking for here though 🤔

File: test/e2e/specs/editor/various/inner-blocks-templates.spec.js [hunk 2]
```diff
@@ -28,9 +28,11 @@ test.describe( 'Inner blocks templates', () => {
 			name: 'test/test-inner-blocks-async-template',
 		} );
 
-		const blockWithTemplateContent = editor.canvas.locator(
-			'role=document[name="Block: Test Inner Blocks Async Template"i] >> text=OneTwo'
-		);
+		const blockWithTemplateContent = page
+			.frameLocator( '[name=editor-canvas]' )
```
Comment (kevin940726) [inline test/e2e/specs/editor/various/inner-blocks-templates.spec.js:32]: Could you explain why we need to use `frameLocator` here? Is it still needed if we wait for the page to load in `createNewPost`?

Comment (stokesman) [reply test/e2e/specs/editor/various/inner-blocks-templates.spec.js:32]: It's for reuse after the `page.reload()` that follows. Now that this test runs in the iframed editor `editor.canvas` returns a [`Frame`](https://playwright.dev/docs/api/class-frame) and the locator formed from that isn't reusable after a page reload.

So this can be done differently if there's a style that seems better to you or I can add a comment. I thought it might be ideal to consider doing a follow up to try having `editor.canvas` return a `FrameLocator` instead of a `Frame` and then this could revert back to using that.

File: packages/e2e-test-utils-playwright/src/admin/create-new-post.js (hunk 1 above)
Comment (stokesman) [reply packages/e2e-test-utils-playwright/src/admin/create-new-post.js]: Ideally we can. Though, this is on par with what it replaces `.edit-post-layout`. I'll take another look and see if I can find something.

Comment (jeryj) [reply packages/e2e-test-utils-playwright/src/admin/create-new-post.js]: Maybe [`.wp-embed-responsive`](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/iframe/index.js#L152)? It's added on load for the iframe, but not for the legacy editor though.

File: test/e2e/specs/editor/various/inner-blocks-templates.spec.js (hunk 2 above)
Comment (kevin940726) [reply test/e2e/specs/editor/various/inner-blocks-templates.spec.js:32]: > I thought it might be ideal to consider doing a follow up to try having editor.canvas return a FrameLocator instead of a Frame and then this could revert back to using that.

Yeah, I regret using `frame` in the first place 😅 . One thing to consider is that there are code that depend on some `frame`-specific API so it's not easy to switch to `frameLocator` now. I've been trying to find alternatives but haven't found any. Please share if you have an idea! 🙇

File: packages/e2e-test-utils-playwright/src/admin/create-new-post.js (hunk 1 above)
Comment (stokesman) [reply packages/e2e-test-utils-playwright/src/admin/create-new-post.js]: I've not been able to see anything that's clearly better. I'd started with the post title in my first experiments with this but had the thought that there could be a test for a custom post type that doesn't support a post title. I thought about the 'Add default block' button that's usually present but post types can have templates that won't include it. Maybe we don't and will never have tests for custom post types where this would be a problem.

Here's an idea. Add another option to `createNewPost` that's a string whose default is `'heading="Add title"'`. If we do have any tests that are for post types without titles they’ll have to be updated to pass in something else there. I'm happy to try that but wasn't sure it's any better. WDYT?

EDIT: I'd originally suggested the option could be used instead of the `legacyCanvas` option but I think it wouldn't work.

File: test/e2e/specs/editor/various/inner-blocks-templates.spec.js (hunk 2 above)
Comment (stokesman) [reply test/e2e/specs/editor/various/inner-blocks-templates.spec.js:32]: > One thing to consider is that there are code that depend on some frame-specific API so it's not easy to switch to frameLocator now

I'd noticed but I figured it should possible to refactor any dependent tests/code. It also looks like many of the `Frame` methods are deprecated so it might be good for scrubbing that in case we are using some.  I don't know Playwright well enough to have a clue if there's any easier alternative.

File: packages/e2e-test-utils-playwright/src/admin/create-new-post.js (hunk 1 above)
Comment (Mamaduka) [reply packages/e2e-test-utils-playwright/src/admin/create-new-post.js]: The post title field and default block appender depend too much on post type settings. The title can be disabled and post-type content locked.

What about using the method from `visitSiteEditor`?

```js
if ( legacyCanvas ) {
	await this.page.waitForSelector( '.edit-post-layout' );
} else {
	// Wait for the iframed canvas contents to be rendered.
	await this.page
		.frameLocator( 'iframe[title="Editor canvas"i]' )
		.locator( 'body > *' )
		.first()
		.waitFor();
}
```

**Comment by Mamaduka** [comment]
Note: Some tests force legacy canvas by registering v2 blocks at the run time. We should evaluate them after this fix is merged.

Repo search: https://github.com/search?q=repo%3AWordPress%2Fgutenberg%20window.wp.blocks.registerBlockType(%20%27test%2Fv2%27&type=code

File: packages/e2e-test-utils-playwright/src/admin/create-new-post.js (hunk 1 above)
Comment (stokesman) [reply packages/e2e-test-utils-playwright/src/admin/create-new-post.js]: I think that's better. Thanks George! See f585b1f. Style aside the main difference is avoiding `waitForSelector` because `ElementHandle` isn't encouraged in the docs.

**Comment by Mamaduka** [comment]
@stokesman, do you mind rebasing this branch on top of the `trunk`? If all tests run without a failure I think we can merge this.

File: test/e2e/specs/editor/various/inner-blocks-templates.spec.js (hunk 2 above)
Comment (kevin940726) [reply test/e2e/specs/editor/various/inner-blocks-templates.spec.js:32]: I couldn't find an alternative to `evaluate` or `waitForFunction` though, which I believe some existing code rely on?

**Review by Mamaduka — APPROVED** [review]

**Comment by Mamaduka** [comment]
The failing Playwright test should be resolved now - #52308, but will require another rebase.

**Comment by Mamaduka** [comment]
@stokesman, it looks like some unwanted commits show-up in PR after the last rebase.

**Comment by stokesman** [comment]
> looks like some unwanted commits show-up in PR after the last rebase.

Yes, that was strange. Those were only showing on this PR page while at the [branch](https://github.com/WordPress/gutenberg/tree/update/e2e-playwright-create-new-post) they weren't part of the commits ahead of trunk. I'd triple-checked the commands I ran and they were fine. Anyway, after another rebase it now looks right here too.

Before that happened, I’d meant to highlight the last two commits as they were added since approval.
- 3bb740f because I found the previous minimal update I had done in the 'inner-blocks-templates' plugin was causing an error in a few of the Puppeteer tests.
- c6925b2 One test needed an update to work with the iframed canvas.

File: test/e2e/specs/editor/various/inner-blocks-templates.spec.js (hunk 2 above)
Comment (stokesman) [reply test/e2e/specs/editor/various/inner-blocks-templates.spec.js:32]: Thanks for those specifics. It does look like that is a sticking point 🤔.

**Comment by Mamaduka** [comment]
Thank you, @stokesman. Let's merge this, and we can do follow-ups as needed.
