### PR TITLE
Simplify the RESET_BLOCK action to fix template part focus mode content loss

### LINKED ISSUE #36937: Site Editor: Template part is missing after exiting focus mode
When switching into focus mode to edit the template part, it's missing after going back to the template using the "Back" button.

## Step-by-step reproduction instructions
1. Go to Appearance > Editor
2. Open templates details dropdown in the header.
3. Click on "More Options" for the area and "Edit {templatePartName}
4. Without doing anything, click the "Back" button.
5. See that now the template part you were editing is missing from the page.

## Screenshot
https://user-images.githubusercontent.com/240569/143783792-861f6c55-ed5c-4e53-bf6f-3499bcd22d26.mp4

I tested with TT1 Blocks and TT2 themes.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #36937 

A long time ago, we used to keep the reusable blocks parsed content inside the "block-editor" store even if these were not rendered. To be able to do so, we needed to keep the blocks of these reusable blocks in state when `RESET_BLOCKS` action was called as it only concerns the "main" block list.

That behavior though is a bit problematic now when we switch to template part focus mode because when we do so, a block that was "controlled" become top-level in the store so "uncontrolled", and when we come back to the old state, the "controlled" block was kept in the state but not its children, so it seemed like the content disappeared because `getBlock( id )` of these child blocks was returning `null`.

This PR removes that old RESET_BLOCKS` behavior because I believe it's probably useless nowadays and potentially a source for memory leaks. I'm not certain yet that I didn't miss any hidden use case for that behavior but let's see what e2e tests say.

### CODE REVIEW

File: packages/block-editor/src/store/reducer.js [hunk 1]
```diff
@@ -637,70 +594,17 @@ const withInnerBlocksRemoveCascade = ( reducer ) => ( state, action ) => {
  */
 const withBlockReset = ( reducer ) => ( state, action ) => {
```
Comment (youknowriad) [inline packages/block-editor/src/store/reducer.js:595]: We can probably now remove these HoR and just move its logic to the sub reducers.

**Review by Mamaduka — APPROVED** [review]
Thanks again, Riad.

This fix works as expected.

File: packages/block-editor/src/store/reducer.js [hunk 2]
```diff
@@ -637,70 +594,17 @@ const withInnerBlocksRemoveCascade = ( reducer ) => ( state, action ) => {
...
-			},
-			attributes: {
-				...omit( state?.attributes, visibleClientIds ),
-				...getFlattenedBlockAttributes( action.blocks ),
-			},
-			order: {
-				...omit( state?.order, visibleClientIds ),
-				...omit(
-					mapBlockOrder( action.blocks ),
-					controlledInnerBlocks
```
Comment (ntsekouras) [inline packages/block-editor/src/store/reducer.js:691]: This is specific to `controlledInnerBlocks` and not `visibleClientIds`. Could this affect something else?

**Comment by ntsekouras** [comment]
>A long time ago, we used to keep the reusable blocks parsed content inside the "block-editor" store even if these were not rendered. 

Unrelated, but do you know why we did that?

File: packages/block-editor/src/store/reducer.js (hunk 2 above)
Comment (youknowriad) [reply packages/block-editor/src/store/reducer.js:691]: no I don't think so, we're basically resetting everything here so there's no leftovers

**Comment by youknowriad** [comment]
> Unrelated, but do you know why we did that?

yes, we didn't have any "core" store, and it was just the initial naive implementation of reusable blocks. It went through several iterations since.

**Comment by Mamaduka** [comment]
@youknowriad It looks like we have slight regression after this PR - #37361.
