### PR TITLE
Metaboxes: Prefetch Metaboxes and don't reload them on save

### LINKED ISSUE #3523: Version 1.7 metaboxes refresh and break functionality
## Issue Overview

My plugin adds a metabox to the Extended Settings side area. It contains a single input field and a get button, which triggers ajax actions to load information within (keyword information). However, the Extended Settings area refreshes even if there's a fetch going on, which basically aborts whatever was happening and reloads the metabox.

After spending 2 weeks getting my plugin to work with the iframes only to see them dropped (thankfully) in v1.7, I'm hesitant to do any work to accommodate for this quirk.

Also, I'm not sure what triggers the Extended Settings refresh, as it seems quite random. I've been editing the title and body of the test post in the hopes of getting the refresh to happen, but one thing I have *not* done is click publish or save draft..

## Steps to Reproduce (for bugs)

1. Add a simple side metabox with an input field (adding the code in functions.php is fine)
```
function gb_test_side_metabox_refresh(){
    add_meta_box( 'test-gutenberg-refresh', esc_html('test gutenberg refresh'), 'gb_test_render_metabox', 'post', $context = 'side', $priority = 'default', $callback_args = null );
}

function gb_test_render_metabox( $post ){ 
?>
    <input type="text">
<?php 
}

add_action( 'add_meta_boxes', 'gb_test_side_metabox_refresh' );
```

2. Load an existing post or create a new one;
3. Expand the side Extended Settings area
4. Type something into the newly-created metabox
5. Wait for the spinner to appear next to the top-most metabox in the Extended Settings area, indicating that the area will be refreshed;
6. See that the input field is now empty.

## Expected Behavior

The settings area should *not* be refreshed automatically, just like they're not in the classic builder.

## Current Behavior

The bug causes the input field to be emptied, effectively negating any work that the user has done before saving.

## Screenshots / Video

step1
step2
step3

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by youknowriad**
The idea is that the metaboxes needs to be loaded with Gutenberg on initial load to initialize properly and their HTML don't need to be updated on Save.

So this does:

 - Prefetch the metaboxes HTML when loading Gutenberg
 - When showing "the metabox area", the dom node are moved from the "prefetch" zone to the the "metabox area" and when the "metabox area" is unmounted (for example, closing the sidebar) the "prefetched metaboxes" are moved back to the "prefetch" zone.
 - When saving a post with metaboxes, an AJAX request is triggered to save the metaboxes but the returned HTML is ignored.

closes #3523 #3277

### CODE REVIEW

**Comment by youknowriad** [comment]
I like how this removes a lot of code :)

**Comment by BE-Webdesign** [comment]
Yeah, going to check this out more in depth, but now that we are on post.php this is more the approach we should head. We don't need to fake things anymore since we are just on post.php. Great stuff so far!

**Comment by youknowriad** [comment]
Do you all agree on moving forward with this direction?

File: lib/meta-box-partial-page.php [hunk 1]
```diff
@@ -550,3 +189,102 @@ function gutenberg_is_meta_box_empty( $meta_boxes, $context, $post_type ) {
...
+	 * This allows for the filtering of meta box data, that should already be
+	 * present by this point. Do not use as a means of adding meta box data.
+	 *
+	 * By default gutenberg_filter_meta_boxes() is hooked in and can be
+	 * unhooked to restore core meta boxes.
+	 *
+	 * @param array $wp_meta_boxes Global meta box state.
+	 */
+	$wp_meta_boxes = apply_filters( 'filter_gutenberg_meta_boxes', $wp_meta_boxes );
+
```
Comment (pento) [inline lib/meta-box-partial-page.php]: Now that we're loading it inline, we should call `gutenberg_intercept_meta_box_render()` here - it should be done immediately before the `do_meta_boxes()` calls.

I'm inclined to not attach it to `filter_gutenberg_meta_boxes`, to prevent anything from being added to `$wp_meta_boxes` after it runs.

Comment (youknowriad) [reply lib/meta-box-partial-page.php]: I thought the `gutenberg_intercept_meta_box_render` was meant to display a warning in the classic editor while `the_gutenberg_metaboxes` renders the metaboxes in Gutenberg.

Am I missing something?

Anyway, feel free to push any change to this branch

**Comment by pento** [comment]
Oh, wait. Yeah, I totally wasn't reading it right. 🙂

File: lib/meta-box-partial-page.php (hunk 1 above)
Comment (pento) [reply lib/meta-box-partial-page.php]: Oh, wait. Yeah, I totally wasn't reading it right. 🙂

File: lib/meta-box-partial-page.php [hunk 2]
```diff
@@ -666,3 +305,100 @@ function gutenberg_show_meta_box_warning( $callback ) {
...
+	<input type="hidden" id="user-id" name="user_ID" value="<?php echo (int) $user_id; ?>" />
+	<input type="hidden" id="hiddenaction" name="action" value="<?php echo esc_attr( $form_action ); ?>" />
+	<input type="hidden" id="originalaction" name="originalaction" value="<?php echo esc_attr( $form_action ); ?>" />
+	<input type="hidden" id="post_author" name="post_author" value="<?php echo esc_attr( $post->post_author ); ?>" />
+	<input type="hidden" id="post_type" name="post_type" value="<?php echo esc_attr( $post->post_type ); ?>" />
+	<input type="hidden" id="original_post_status" name="original_post_status" value="<?php echo esc_attr( $post->post_status ); ?>" />
+	<input type="hidden" id="referredby" name="referredby" value="<?php echo $referer ? esc_url( $referer ) : ''; ?>" />
+	<!-- These fields are not part of the standard post form. Used to redirect back to this page on save. -->
+	<input type="hidden" name="gutenberg_meta_boxes" value="gutenberg_meta_boxes" />
+	<input type="hidden" name="gutenberg_meta_box_location" value="<?php echo esc_attr( $location ); ?>" />
```
Comment (aduth) [inline lib/meta-box-partial-page.php]:
```
Notice: Undefined variable: location in /srv/www/editor/htdocs/wp-content/plugins/gutenberg/lib/meta-box-partial-page.php on line 390
```

**Review by aduth — COMMENTED** [review]
To be clear, is the idea that we're abandoning any attempt to keep the meta boxes up to date since they don't always work well with auto-save or otherwise long-lived page sessions?

**Comment by youknowriad** [comment]
> To be clear, is the idea that we're abandoning any attempt to keep the meta boxes up to date

I'd not phrase it like this, There are two things:

 - Prefetching metaboxes from the server when loading the gutenberg page. This makes sure all metaboxes initialization scripts run just like before
 
 - Do not refresh the HTML for the metaboxes on save. I personally haven't encoutered any metaboxes where this cause issues. Most metaboxes refresh with JavaScript or are forms that update with user input. And updating the HTML on save was broken anyway because there's no way to ensure the initialization scripts run again on success.

**Comment by aduth** [comment]
>And updating the HTML on save was broken anyway because there's no way to ensure the initialization scripts run again on success.

I guess this was easier with iframes, since they were standalone documents, but is there no way to mimic the document readying events for plugin metaboxes?

**Comment by youknowriad** [comment]
> but is there no way to mimic the document readying events for plugin metaboxes?

Nothing that I'm aware of. Even regular `onload` events were not being called on "initial rendering".

**Comment by youknowriad** [comment]
Merging. Most concerns addressed and the code is way cleaner with this
