### PR TITLE
Block Library: Fix Comments Pagination Number with no pagination settings

### LINKED ISSUE #39157: Discussion settings are not respected when using inherit option in Comments Query Loop block
### Description

Right now, when the “Inherit from Discussion Settings” option is enabled in the Comments Query loop, it doesn’t respect the setting “Break comments into pages with X top level comments per page and the last/first page displayed by default. Comments should be displayed with the older/newer comments at the top of each page.”

### Step-by-step reproduction instructions

1. Go to Discussion Settings and change the "Break comments into pages" to 1 top level comments. Keep it disabled.
2. Go to a post with more than 1 comment, using the Comments Query Loop block.
3. You can see that, even when the setting is disabled, it is still breaking the comments into pages with 1 comments. If it is disabled, it shouldn't create different pages.

### Screenshots

**_Discussion settings_**
Screenshot 2022-03-02 at 10 56 43

**_Comments Query Loop inherit option_**
Screenshot 2022-03-02 at 10 17 30

**_Current result_**
Screenshot 2022-03-02 at 10 50 44

**_Expected result_**
Screenshot 2022-03-02 at 10 57 44

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by cbravobernal**
## Description

Fixes partial #39157 (not fixing anything related with order)

Before the PR, if the `Inherit from Discussion Settings` option is enabled in the Comments Query loop, it did not respect the setting `Break comments into pages with X top level comments per page and the last/first page displayed by default`.

After the fix, the Comments Query Loop, on the frontend, if we have `Inherit from Discussion Settings` enabled, will apply the settings selected by the user on Discussion Settings.

## How to test

In trunk (before)
1. Go to Discussion Settings and disable the "Break comments into pages", set to a number of top level comments.
2. Go to a post with more than the number you put before comments, add the Comments Query Loop block.
3. You can see on the frontend that, even when the setting is disabled, it is still breaking the comments into pages with 1 comment.

On the PR branch
1. Go to Discussion Settings and disable the "Break comments into pages" to 1 top level comments.
2. Go to a post with more than 1 comment, add the Comments Query Loop block.
3. You can see on the frontend that, when the setting is disabled, now it will show all comments, respecting the setting.
4. You can also enable `break comments` settings and, in Comments Query Loop, having inherit setting enabled, it should paginate on frontend with the discussion settings selected.

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Review by SantosGuillamot — APPROVED** [review]

**Comment by gziolo** [comment]
There is one unit test that needs to be updated:

```
1) Block_Library_Comment_Template_Test::test_build_comment_query_vars_from_block_no_context
[48](https://github.com/WordPress/gutenberg/runs/5411667756?check_suite_focus=true#step:8:48)
Failed asserting that two arrays are equal.
[49](https://github.com/WordPress/gutenberg/runs/5411667756?check_suite_focus=true#step:8:49)
--- Expected
[50](https://github.com/WordPress/gutenberg/runs/5411667756?check_suite_focus=true#step:8:50)
+++ Actual
[51](https://github.com/WordPress/gutenberg/runs/5411667756?check_suite_focus=true#step:8:51)
@@ @@
[52](https://github.com/WordPress/gutenberg/runs/5411667756?check_suite_focus=true#step:8:52)
     'no_found_rows' => false
[53](https://github.com/WordPress/gutenberg/runs/5411667756?check_suite_focus=true#step:8:53)
     'update_comment_meta_cache' => false
[54](https://github.com/WordPress/gutenberg/runs/5411667756?check_suite_focus=true#step:8:54)
     'hierarchical' => 'threaded'
[55](https://github.com/WordPress/gutenberg/runs/5411667756?check_suite_focus=true#step:8:55)
+    'number' => 5
[56](https://github.com/WordPress/gutenberg/runs/5411667756?check_suite_focus=true#step:8:56)
+    'paged' => 1
[57](https://github.com/WordPress/gutenberg/runs/5411667756?check_suite_focus=true#step:8:57)
 )
[58](https://github.com/WordPress/gutenberg/runs/5411667756?check_suite_focus=true#step:8:58)

[59](https://github.com/WordPress/gutenberg/runs/5411667756?check_suite_focus=true#step:8:59)
/var/www/html/wp-content/plugins/gutenberg/phpunit/class-block-library-comment-template-test.php:124
```

File: phpunit/class-block-library-comment-template-test.php [hunk 1]
```diff
@@ -120,7 +120,32 @@ function test_build_comment_query_vars_from_block_no_context() {
 				'no_found_rows'             => false,
 				'update_comment_meta_cache' => false,
 				'hierarchical'              => 'threaded',
-				'number'                    => self::$per_page,
```
Comment (DAreRodz) [inline phpunit/class-block-library-comment-template-test.php:123]: Uhm, this change seems odd to me. As `comments/inherit` is `true` by default, and the `page_comments` option is also `true` (it's defined at the top of the tests), shouldn't this test have stayed the same, keeping the pagination query vars?  Why `number`and `paged` disappeared? 🤔

Comment (DAreRodz) [reply phpunit/class-block-library-comment-template-test.php:123]: Oh, I see. The block being parsed is Comment Template, and context is added by Comments Query Loop (the parent block), which is not being instantiated in the tests. Everything alright. 👍

**Comment by DAreRodz** [comment]
Thanks for these changes @c4rl0sbr4v0! Code is fine, tests were passing, and the PR was already approved, so I merged directly. 😄
