### PR TITLE
Permalink: Decode URLs 😄 

### LINKED ISSUE #5231: Permalink preview doesn't render emojis
## Issue Overview
Permalink preview input over the title block doesn't render emojis nicely.

## Steps to Reproduce (for bugs)
1. Create a new post
2. Insert emojis in the title
3. Save the post
4. Observe permalink preview show URL encoded codes `%...` instead of emojis:

image

For comparison, Chrome's URL bar shows them nicely: 

image

#### Setup:
- Gutenberg 2.2.0
- Chrome  64 / MacOS

## Expected Behavior
🌻🌻🐞✨

## Current Behavior
`%f0%9f%8c%bb%f0%9f%8c%bb%e2%9c%a8/`

## Ideas

If/when emojis render correctly, they could be shown grayscale with some CSS:
```css
filter: grayscale(100%);
```

### PR DESCRIPTION
**Pull request by youknowriad**
closes #5231  😄 

**Testing instructions**

 - Add emojis in the title (slug)
 - Verify that the permalink is showing the emoji and not the encoded value.

### CODE REVIEW

File: editor/components/post-permalink/index.js [hunk 1]
```diff
@@ -53,7 +53,7 @@ class PostPermalink extends Component {
 				<Dashicon icon="admin-links" />
 				<span className="editor-post-permalink__label">{ __( 'Permalink:' ) }</span>
 				<Button className="editor-post-permalink__link" href={ link } target="_blank">
-					{ link }
+					{ decodeURI( link ) }
```
Comment (aduth) [inline editor/components/post-permalink/index.js]: Can you explain the choice of `decodeURI` over `decodeURIComponent` ?

Comment (youknowriad) [reply editor/components/post-permalink/index.js]: I may be wrong but I use `decodeURI` when I have to decode the whole URL and `decodeURIComponent` when decoding a slice of the URL (just a value of a query string for instance)

**Review by aduth — APPROVED** [review]
