### PR TITLE
Real-time Collaboration: Fix revision restore bug

### LINKED ISSUE #75199: Real Time Colllaboration: Revision restore broken
### Description

Restoring a revision when the default real time collaboration provider is enabled, is broken at the moment. The collaborator that restores the revision correctly sees the restored content. But all other collaborators lose the content on their screen. If they exit out and reload the post, the content is doubled at times.

### Step-by-step reproduction instructions

1. Enable the default RTC provider
2. Open up two browser sessions
3. Make changes in each session
4. Restore a revision
5. The collaborator not doing the restore loses their content.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/95199b35-04ad-4419-92e1-6db463242403

### Environment info

- Latest trunk branch of Gutenberg
- Latest Vivaldi and Safari

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by ingeniumed**
## What?

Restoring a revision in an RTC session causes other collaborators to lose their blocks.

Closes #75199.

## Why?

The blocks are set to undefined, which causes the Yjs doc to transmit that and thereby update the UI to wipe the blocks for other collaborators. Future saves/edits start to create unpredictable situations as a result. 

## How?

When the revision is restored, parse out the blocks using the content to ensure the correct blocks are transmitted to all collaborators.

## Testing Instructions

1. Pull down this branch
2. Enable the default RTC provider
3. Open up two browser sessions
4. Make changes in either one
5. Restore a previous revision
6. Ensure that the content is correctly updated

### Testing Instructions for Keyboard

N/A

### Before

https://github.com/user-attachments/assets/32d7325f-0223-47be-969e-4c70252591d2

### After

https://github.com/user-attachments/assets/cdfb79b6-17ad-4a62-b766-e2ba7d8888fc

### CODE REVIEW

**Review by ellatrix — APPROVED** [review]

File: packages/editor/src/store/private-actions.js [hunk 1]
```diff
@@ -614,9 +614,8 @@ export const restoreRevision =
 		}
 
 		// Build the edits object with all restorable fields from the revision.
-		// Setting blocks to undefined clears edited blocks, forcing a re-parse of content.
 		const edits = {
-			blocks: undefined,
+			blocks: parse( revision.content.raw ),
```
Comment (youknowriad) [inline packages/editor/src/store/private-actions.js:618]: I think the real issue here is not here to be honest, setting blocks to undefined and content to a modified string is a valid "edit", it means the content has changed. Use the content, if you need blocks parse the content.
