### PR TITLE
Chrome: Show notices on post save, schedule, update

### LINKED ISSUE #967: UI: Add notices for published, updated, save failed
Splitting this out from #707. The flow for publishing and saving is soon in a good place. 

We have, however, a need for a few edgecase notices:

- Published successfully
- Updated successfully
- Scheduled successfully

... as well as failure states:

- Publishing failed
- Updating failed
- Scheduling failed

... and also for draft saving and auto saving:

- Save failed

## Save Failed

Let's make this part of the "Save" area on the left:

saving publishing

## Publish/Updating/Scheduling notices

We'll probably want notices after all (see also #486), because thankfully we were able to test for a while a design where the notice itself was integrated in the button. Not only did this feel ephemeral, but it made the button itself feel more complex. It also doesn't work that well if we ever get to exploring a dropdown button as suggested in #708.

So here's how notices could look:

notices

### PR DESCRIPTION
**Pull request by youknowriad**
closes #967 

 - Triggers Publish, Schedule and update notices on successful saves
 - Triggers Failed notices on failing requests.

### CODE REVIEW

File: editor/effects.js [hunk 1]
```diff
@@ -67,13 +68,36 @@ export default {
...
+		const { dispatch } = store;
+
+		const publishStatus = [ 'publish', 'private', 'future' ];
+		const isPublished = publishStatus.indexOf( previousPost.status ) !== -1;
+		const messages = {
+			publish: __( 'Post published!' ),
+			'private': __( 'Post published privately!' ),
+			future: __( 'Post schduled!' ),
+		};
+		if ( isPublished || publishStatus.indexOf( post.status ) !== -1 ) {
```
Comment (mtias) [inline editor/effects.js]: Can we add a few comments explaining how we are handling this?

**Comment by mtias** [comment]
Looking good to me.

**Review by mtias — APPROVED** [review]

**Comment by jasmussen** [comment]
Love it. Ship it.
