### PR TITLE
Fixed background grey of the Shortcode block placeholder screen

### LINKED ISSUE #14718: Grey placeholder color is inconsistent in the Shortcode block
The Shortcode block's background placeholder grey is lighter than the other greys used in the other block placeholders setup screens.

**To Reproduce**
1. Add an Image block and observe the grey background.
2. Add a Shortcode block and observe the grey background.
3. Add an RSS block and observe the grey background.

Screen Shot 2019-03-29 at 5 52 05 PM

**Expected behavior**
The grey background on the Shortcode block should match all the others.

All the others use the `.components-placeholder` style which uses the `background: rgba(139, 139, 150, 0.1)` but the Shortcode block doesn't use the `.components-placeholder` styles.

I'd like to see something like this instead, but maybe we can at least get a PR to fix the color.

Screen Shot 2019-03-29 at 6 06 53 PM

### PR DESCRIPTION
**Pull request by mapk**
## Description
Changed the background grey of the shortcode block to match all the other placeholder setup screens on other blocks. Fixes #14718

## How has this been tested?
Tested locally.

## Before

shortcode

## After

Screen Shot 2019-03-29 at 8 34 52 PM

## Types of changes
Changed the variable used for the background grey.

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by paulwilde** [comment]
It would also make sense to add support for dark themes to be even more consistent with the placeholder component:

```css
.is-dark-theme & {
    background: $light-opacity-light-200;
}
```

**Comment by mapk** [comment]
Here's how it looks now.

Screen Shot 2019-04-01 at 11 51 06 AM

**Comment by mapk** [comment]
Also, the dark mode work for the setup screen.

Screen Shot 2019-04-01 at 12 47 04 PM

There is a problem about the placeholder text being lost in the field, but this applies to multiple blocks which should be addressed in another PR.

**Comment by mapk** [comment]
@gziolo Can you review this for me? I had made some changes, then noticed some conflicts with changes you had made earlier. I rebased and force pushed this bad boy, and want to make sure I did it all right. If we're good, can I get your approval?

**Review by gziolo — COMMENTED** [review]
> Can you review this for me? I had made some changes, then noticed some conflicts with changes you had made earlier. I rebased and force pushed this bad boy, and want to make sure I did it all right. If we're good, can I get your approval?

All good 👍 There are more changes coming to all core blocks. We need those refactorings to validate all the assumptions made in RFC (#13693).

File: packages/block-library/src/shortcode/edit.js [hunk 1]
```diff
@@ -10,8 +10,8 @@ const ShortcodeEdit = ( { attributes, setAttributes, instanceId } ) => {
 	const inputId = `blocks-shortcode-input-${ instanceId }`;
 
 	return (
-		<div className="wp-block-shortcode">
-			<label htmlFor={ inputId }>
+		<div className="wp-block-shortcode  components-placeholder">
```
Comment (gziolo) [inline packages/block-library/src/shortcode/edit.js]: @jasmussen - can you advice how it could be coded differently? In general, we assume that class names are local to the component which define them. In this case, it's `wp.components.Placeholder` which uses `components-placeholder`. While it seems to be very convenient to use an existing class, it doesn't scale well as we learned down the road.

Comment (jasmussen) [reply packages/block-library/src/shortcode/edit.js]: Yeah this is an interesting question.

I would say there are two ways to go. 

1. Keep the shortcode block as its own thing. But then we remove the placeholder classes and _duplicate_ the CSS rules necessary for them to look the same.
2. Rewrite/potentially redesign the shortcode to actually _use_ the placeholder component. 

2 is a bigger task, and I have no strong opinions on which one is the right way to go. What do you think?

Comment (youknowriad) [reply packages/block-library/src/shortcode/edit.js]: What is a placeholder component? What does it mean? Does it make sense as a separate component?

Comment (talldan) [reply packages/block-library/src/shortcode/edit.js]: One of the main issues with duplicating the class like this is maintainability. If someone wants to refactor the placeholder styles, they'd generally expect only the `<Placeholder>` component to be affected, but in this case other components can be affected in an unexpected way.

> What is a placeholder component?

In the context of a block, it seems like it's the UI that's displayed when the proper wysiwyg part of a block can't be shown. Outside of the context of a block, I'm not really sure. The word 'placeholder' generally implies a stopgap that will eventually be replaced, but I'm not sure how that applies to other user interfaces that `@wordpress/components` might be used in.

A couple of other options might be:
1) Extend `Placeholder` to support other layouts, like the horizontal layout shown here
2) Extract the container of the placeholder into a separate component (`PlaceholderCard`?) and use that.

**Review by gziolo — APPROVED** [review]
Looks good.

We should open a follow-up issue where we cover the part about reusing class names from existing components.

**Comment by youknowriad** [comment]
I wonder if this is related to these changes here #15032

**Comment by aduth** [comment]
> We should open a follow-up issue where we cover the part about reusing class names from existing components.

>@youknowriad or @aduth - what would be the best way moving forward to tackle it? We definitely need to clean it up.

Sorry I missed this until now. I agree this shouldn't be done this way, and was part of the reason for #14556 in more strongly asserting that the class name should never be used outside its own component.

>A component's class name should **never** be used outside its own folder (with rare exceptions such as [`_z-index.scss`](https://github.com/WordPress/gutenberg/blob/master/assets/stylesheets/_z-index.scss)). If you need to inherit styles of another component in your own components, you should render an instance of that other component. At worst, you should duplicate the styles within your own component's stylesheet. This is intended to improve maintainability by treating individual components as the isolated abstract interface.

I would much rather have seen the styles duplicated, or to make some separate component which encompasses what it is we're trying to do with this padded gray container. But to me, the "padded gray container" is what the Placeholder component is trying to be. Whether it supports the desired use-case, it either (a) should be made to or (b) the desired use-case should be changed to align to what the Placeholder is meant to be used for.

Is it not enough to do something like:

```jsx
<Placeholder
	icon="shortcode"
	label={ __( 'Shortcode' ) }
>
	<PlainText /* ... */ />
</Placeholder>
```
