### PR TITLE
Theme.json: fix some outline properties doesn't work properly on the editor

### LINKED ISSUE #44502: theme.json: The `outline` property does not work properly on the editor
### Description

 The `outline` property does not work properly in the editor. The following are either not applied or incorrect values are applied on the editor:

### `styles.outline`

Not work on the **site** editor.

### `styles.blocks.{namespace/blockName}.outline`

Not work on the **post** / **site** editor..

### `styles.elements.button.outline`

The incorrect `outline-color` property is applied and the `outline-offset` property is not on the **site** editor.

button

### `styles.h{X}.outline`

The incorrect `outline-color` property is applied and the `outline-offset` property is not on the **site** editor.

h2

### Step-by-step reproduction instructions

In the active theme, define theme.json as follows:

<details>
<summary>theme.json</summary>

```json
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"settings": {
		"appearanceTools": true,
		"layout": {
			"contentSize": "840px"
		}
	},
	"styles": {
		"outline": {
			"offset": "2px",
			"width": "4px",
			"style": "dashed",
			"color": "red"
		},
		"blocks": {
			"core/paragraph": {
				"outline": {
					"offset": "2px",
					"width": "4px",
					"style": "dashed",
					"color": "red"
				}
			}
		},
		"elements": {
			"button": {
				"outline": {
					"offset": "2px",
					"width": "4px",
					"style": "dashed",
					"color": "red"
				},
				":active": {
					"outline": {
						"offset": "2px",
						"width": "4px",
						"style": "dashed",
						"color": "green"
					}
				},
				":focus": {
					"outline": {
						"offset": "2px",
						"width": "4px",
						"style": "dashed",
						"color": "yellow"
					}
				},
				":hover": {
					"outline": {
						"offset": "2px",
						"width": "4px",
						"style": "dashed",
						"color": "blue"
					}
				}
			},
			"h2": {
				"outline": {
					"offset": "2px",
					"width": "4px",
					"style": "dashed",
					"color": "red"
				}
			}
		}
	}
}
```

</details>

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress: 6.1-beta1-54304
- Gutenberg: 14.2.0-rc.1 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fix: #44502

## What?
This PR fixes some outline properties doesn't work properly on the editor.
See #44502 for more context on the issue and test step.

## Why? / How?

I suspect this is due to a typo in the `ruleKey` and the fact that the key to the global style has not been added.

### CODE REVIEW

File: packages/edit-site/src/components/global-styles/use-global-styles-output.js [hunk 1]
```diff
@@ -605,12 +610,12 @@ export const toStyles = (
...
-			.has-global-padding > .alignfull:where(:not(.has-global-padding)) > :where([class*="wp-block-"]:not(.alignfull):not([class*="__"]),p,h1,h2,h3,h4,h5,h6,ul,ol) { padding-right: var(--wp--style--root--padding-right); padding-left: var(--wp--style--root--padding-left); } 
+		ruleset += `padding-right: 0; padding-left: 0; padding-top: var(--wp--style--root--padding-top); padding-bottom: var(--wp--style--root--padding-bottom) }
+			.has-global-padding { padding-right: var(--wp--style--root--padding-right); padding-left: var(--wp--style--root--padding-left); }
+			.has-global-padding :where(.has-global-padding) { padding-right: 0; padding-left: 0; }
+			.has-global-padding > .alignfull { margin-right: calc(var(--wp--style--root--padding-right) * -1); margin-left: calc(var(--wp--style--root--padding-left) * -1); }
+			.has-global-padding :where(.has-global-padding) > .alignfull { margin-right: 0; margin-left: 0; }
+			.has-global-padding > .alignfull:where(:not(.has-global-padding)) > :where([class*="wp-block-"]:not(.alignfull):not([class*="__"]),p,h1,h2,h3,h4,h5,h6,ul,ol) { padding-right: var(--wp--style--root--padding-right); padding-left: var(--wp--style--root--padding-left); }
```
Comment (t-hamano) [inline packages/edit-site/src/components/global-styles/use-global-styles-output.js:618]: This change is due to the code editor's trailing space removal feature.

**Review by ramonjd — APPROVED** [review]
Thanks for the fix @t-hamano 💟 

I can confirm that has the outline offset property working in the site editor for all elements (root-level in theme.json, blocks and elements)

Screen Shot 2022-09-28 at 10 15 41 am

File: packages/style-engine/src/styles/outline/index.ts [hunk 2]
```diff
@@ -22,7 +22,7 @@ const offset = {
 		style: Style,
 		options: StyleOptions,
 		path: string[] = [ 'outline', 'offset' ],
-		ruleKey: string = 'outlineColor'
+		ruleKey: string = 'outlineOffset'
```
Comment (ramonjd) [inline packages/style-engine/src/styles/outline/index.ts:25]: Yeah looks like a copy / paste job.

Unit tests might have caught it.

Comment (ramonjd) [reply packages/style-engine/src/styles/outline/index.ts:25]: Added some here https://github.com/WordPress/gutenberg/pull/44518

**Comment by michalczaplinski** [comment]
Cherry-picked for inclusion in Gutenberg 14.2 in 6ec5a2999d208

**Comment by michalczaplinski** [comment]
Cherry-picked for the 6.1 release in https://github.com/WordPress/gutenberg/pull/44656
