### PR TITLE
Limit the npm version to be 6

### LINKED ISSUE #2610: [BUG] NPM v7 uses SSH instead of an explicit HTTPS for GitHub repos
### Current Behavior:

When I use a git repository via an HTTP link NPM "takes liberties" with it, which breaks my build:

```txt
$ npm init -y
Wrote to /Users/eugene.lazutkin/Work/temp/package.json:

{
  "name": "temp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


$ npm i --save https://github.com/uhop/stream-chain.git

added 1 package, and audited 2 packages in 3s

found 0 vulnerabilities
```

It produces `package-lock.json`:

```json
{
  "name": "temp",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "version": "1.0.0",
      "license": "ISC",
      "dependencies": {
        "stream-chain": "github:uhop/stream-chain"
      }
    },
    "node_modules/stream-chain": {
      "version": "2.2.4",
      "resolved": "git+ssh://git@github.com/uhop/stream-chain.git#459f5a1708c138b6e0abaae4cf103c3488e1e78e",
      "license": "BSD-3-Clause"
    }
  },
  "dependencies": {
    "stream-chain": {
      "version": "git+ssh://git@github.com/uhop/stream-chain.git#459f5a1708c138b6e0abaae4cf103c3488e1e78e",
      "from": "stream-chain@github:uhop/stream-chain"
    }
  }
}
```

Note that `https://github.com/uhop/stream-chain.git` was replaced with `github:uhop/stream-chain`, which is probably OK in this case. But other two links (?) are rewritten from `https://github.com/uhop/stream-chain.git` to `git+ssh://git@github.com/uhop/stream-chain.git`, which is clearly bad.

The problem is that a build bot we use in similar situations can access private git repositories using HTTP, but not SSH for security reasons. It fails on an authentication. Rewriting `https://github.com/uhop/stream-chain.git` to `git+ssh://git@github.com/uhop/stream-chain.git` is not acceptable for that reasons.

The fix is relatively minor yet unpleasant: we have to replace `npm ci` with `npm i`, which takes more time and introduced instabilities with other dependencies.

### Expected Behavior:

When running `npm ci` it should use the original URL with the HTTP authentication instead of SSH.

### Steps To Reproduce:

See the description and do the same steps using git repositories (github only?) as dependencies.

### Environment:

OS: Mac
Node: 15.7.0
NPM: 7.4.3

### PR DESCRIPTION
**Pull request by kevin940726**
## Description

An alternative to #29000.

As pointed out in #28824, we don't currently support npm 7 until they fix https://github.com/npm/cli/issues/2610. As a temporary fix, we should limit the npm version to 6 for now.

## How has this been tested?

```sh
npm i -g npm@7
# Expect to see the error
node ./bin/check-latest-npm.js

npm i -g npm@6
# Expect to pass
node ./bin/check-latest-npm.js
```

## Screenshots 
image

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: bin/check-latest-npm.js [hunk 1]
```diff
@@ -6,12 +6,20 @@
...
+ * Internal dependencies
+ */
+const {
+	engines: { npm: npmSemver },
+} = require( '../package.json' );
 
 /**
  * Returns a promise resolving with the version number of the latest available
- * version of NPM.
+ * version of npm.
```
Comment (kevin940726) [inline bin/check-latest-npm.js:20]: Changed from `NPM` to `npm` since it's actually supposed to be [all-lowercase](https://www.npmjs.com/about) 😅 .

**Review by ockham — APPROVED** [review]
Thanks @kevin940726! This should allow us to sidestep the npm 7 conundrum.

The `check-latest-npm` fix is great and aligns with what we seem to have reached agreement for on #29097 :+1:
