### PR TITLE
fix: Use aria-disabled instead of disabled for undo/redo

### LINKED ISSUE #3486: Keyboard activation of undo buttons in toolbar creates inconsistent focus behaviour
## Issue Overview

So Gutenberg's history is managed by changing redux state. This works really well if the `undo` and `redo` buttons are fired by the keyboard shortcuts (e.g. Ctrl + Z), where moving through the page history can shift the focus to the corresponding block correctly.

However, if the user has navigated to the toolbar, and pressed Space / Enter to active the undo and redo buttons, the focus becomes very inconsistent

1. It can stay on the button itself. This happens if the undo puts you in the `PostTitle`. This is likely because the `PostTitle` focus state is not encapsulated in the redux state.
2. It can jump to the block where the last history change was saved. This is likely because the block focus is often encapsulated in the redux state.

Note, with (1), if the undo button becomes disabled because you get back to the start of the undo history, the focus is lost, and the focus returns to the body, breaking keyboard navigation.

With (2), this prevents a user from making multiple `undo` operations in a row. You could rather easily argue that most people would be using the Ctrl + Z shortcut, though (note, however, that this is a different operation from clicking / keyboard activating that button though ... as it goes through TinyMCE). The behaviour just seems to be inconsistent. We need to decide what should happen.

a) Should keyboard activating the undo / redo buttons always transfer focus back to whatever block previously had focus? What if something else had focus in the block?
b) Should keyboard activating the undo / redo buttons always keep focus on the button. Would it work differently then if you clicked on it with the mouse?

### Situation 1

1. Create a new post
2. Focus the post title
3. Type "One word"
4. Press Alt + F10 (or equivalent)
5. Navigate with the arrow keys to undo
6. Press Space to trigger Undo repeatedly until the button gets disabled

### Expected Behavior

The focus stays somewhere in the toolbar, or it jumps straight to the PostTitle immediately.

### Current Behavior

The focus stays in the toolbar until the last undo, and then focus is just lost.

### Situation 2

1. Create a new post
2. Focus the "Write Your Story" block
3. Type "One two three four five"
4. Press Alt + F10 (or equivalent)
5. Navigate with the arrow keys to undo
6. Press Space to trigger Undo

### Expected Behavior

The focus stays somewhere in the toolbar, or it jumps to the last editable focused in the history.

Note: I also thought that pressing that button would trigger an `undo` in TinyMCE instead, but it doesn't. This means that Ctrl + Z and activating that button have completely different meanings. Is there a better way we can handle that?

### Current Behavior

The focus jumps to the last editable focused in the history, so this can be fine as long as it is consistent.

### PR DESCRIPTION
**Pull request by tofumatt**
Fixes #3486

## Description
Change the undo/redo buttons from using the `disabled` attribute and instead use the `aria-disabled` attribute; this prevents focus loss when the undo/redo actions are unavailable.

Note that there are no visual/functional differences here aside from screenreaders now announcing that the button becomes unavailable once disabled and focus is not lost as before.

### CODE REVIEW

**Review by noisysocks — APPROVED** [review]
It works! 👍 

I'm wondering, should this logic exist in `Button` and/or `IconButton`? Does this bug also exist in other places where we're using buttons with the `disabled` prop? It would be nice if developers could set the `disabled` prop on our `Button` component and rely on it doing the Right Thing™.

**Comment by tofumatt** [comment]
It probably should, but I tried that in the past with some other buttons (in the Datepicker's `ToggleButton`) and it was enough of a refactor as to not be entirely trivial. I think it's just an easy place to hit up regressions, so I'd rather do it when we have more time to test things as there are a lot of buttons lacking in E2E tests and I don't want any Beta 3/4 regressions 😉

File: packages/editor/src/components/editor-history/redo.js [hunk 1]
```diff
@@ -24,7 +24,14 @@ export default compose( [
 	withSelect( ( select ) => ( {
 		hasRedo: select( 'core/editor' ).hasEditorRedo(),
 	} ) ),
-	withDispatch( ( dispatch ) => ( {
-		redo: () => dispatch( 'core/editor' ).redo(),
+	withDispatch( ( dispatch, ownProps ) => ( {
+		redo: () => {
+			// If there are no redo levels this is a no-op, because we don't actually
```
Comment (aduth) [inline packages/editor/src/components/editor-history/redo.js]: In treating `EditorHistoryRedo` as the presentational component of the [Presentational / Container pair](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0), it seems like if it's meant to be a disabled behavior, it should be considered by the component in deciding to invoke the `onClick` callback.

Even something like:

```jsx
onClick={ hasRedo ? redo : undefined }
```

It's not so much a concern here in that the components are so tied to the specific editor use case of Undo/Redo, but is a good rule of thumb in delegating where logic should occur between the underlying component and its enhancer(s).

Comment (tofumatt) [reply packages/editor/src/components/editor-history/redo.js]: Oh, good point. Follow-up PR with a fix is here: #11428.
