### PR TITLE
Fix Block Editor Iframe component to render in standards mode

### LINKED ISSUE #38854: Gutenberg Block Editor renders in quirks mode causing visual/css errors.
### Description

Block Editor renders its contents into `<Iframe />` component dynamically via `React.createPortal` and by default empty document created for an <iframe /> without a src/srcDoc that would provide it doesn't have any doctype defined. This causes the iframe to render in quirks mode which in absence of css reset controlling rendering baseline causes some potential rendering differences between front-end which has `<!doctype html>` provided and renders in standards mode.

This can cause editor and front-end to render differently and, among [all](https://quirks.spec.whatwg.org/) [the](https://www.quirksmode.org/css/quirksmode.html) [little](https://html.spec.whatwg.org/multipage/rendering.html) nuances, can cause tables (typography, spacing) issues, images to position differently (inline on baseline vs block), margins to calculate differently sometimes and have different defaults (ie. form).

This affects Site Template and Template Part editors. Post/Page editor is not affected (doesn't render in an iframe)

We've noticed this at Automattic when working on Full Site Editing for WooCommerce.

Also was fun to visit PPK's [quriksmode](https://www.quirksmode.org/) after so many years :) 

### Step-by-step reproduction instructions

1. Go to Template or Template Part editor.
2. Add block or edit template part containing quirks mode affected CSS/HTML. (Ie. [Mini Cart](https://github.com/woocommerce/woocommerce-gutenberg-products-block))
3. See contents render differently than in the front-end

#### 🛑   Example error:
| css | preview |
| - | - |
| table-quirks-mode | quirks-mode |

#### ✅  Example valid after applying fix:
| css | preview |
| - | - |
| table-standards-mode | standard-mode |

### Environment info

- Chrome (97, Mac)
- WordPress 5.9
- Gutenberg 12.6

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by tomasztunik**
## Description

This fixes an issue where iframe component used by Block Editor would 
render its contents differently to how they were rendered on the front-end.

Iframe document doctype is not set by default if it is not provided via iframe 
`src` or `srcDoc` and not having doctype will cause browser to render iframe 
contents in quirks mode. Appending doctype to existing document won't change 
iframe's rendering mode. `Document.write` will overwrite the document with 
a new one containing a correct doctype and will correctly render in stadards mode.

I've reviewed other areas of Gutenberg and it seems this is the only place
affected. All other places are correctly setting `<!DOCTYPE html>`.

More details provided in the related issue.

Fixes #38854

## Testing Instructions

1. Go to Template or Template Part editor.
2. Add block or edit template part containing quirks mode affected CSS/HTML. (Ie. [Mini Cart](https://github.com/woocommerce/woocommerce-gutenberg-products-block))
3. Confirm that contents render the same in the editor and in the front-end

#### Example error:
|css|preview|
|-|-|
| table-quirks-mode | quirks-mode |

#### Example valid after applying fix:
|css|preview|
|-|-|
| table-standards-mode | standard-mode |

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by ellatrix** [comment]
@tomasztunik Did you find any resources about this issue? Is there no other way to achieve it? I tried to use `document.write` at some point and it caused the contents to load quite a bit slower, so that's worth comparing. Although if there's styling issue, we don't really have much choice. We also need to test in other browsers to confirm that the iframe works, we only have test coverage for Chrome.

**Comment by tomasztunik** [comment]
👋  @ellatrix - thanks for looking into this. 

As `document.write` happens only once on Iframe setup while the iframe document is still empty I did not notice any performance degradation on my end. Tried to run performance profiling on impact but couldn't really notice difference - might be dev machine is just too much for it to make it significant.

Were your findings around using document.write around iframe as well or were they part of DOM rendering as part of page loading flow?

Before I made it to this solution I've tried to populate the initial state using `srcDoc`, but this conflicted with different areas as it seemed to happen async with react ref setup hook. After that I've learned the hard way that appending doctype to already rendered document doesn't update the document's rendering mode if it was already rendered. So if I tried to use `document.implementation.createDocumentType('html', '', '')` and prepending it to the document even though you'd be able to see it in inspector it would still remain rendered in quirks mode.

Confirmed the bug to be present on latest Safari (16.1) and Firefox (97) and that the fix works there as well.

**Comment by tomasztunik** [comment]
PS. re links - I've shared some resources on quirks mode on the issue (but I guess they were bit hidden in the description!):
- https://quirks.spec.whatwg.org/
- https://html.spec.whatwg.org/multipage/rendering.html (page search "In quirks mode")
- https://www.quirksmode.org/css/quirksmode.html

and additionally:
- https://html.spec.whatwg.org/multipage/syntax.html#the-doctype

**Comment by ellatrix** [comment]
Would it be possible to add an e2e test with some example CSS, then check the result with `getComputedStyle`?

**Comment by tomasztunik** [comment]
I've added E2E tests that validate that site editor iframe is running in a correct `compatMode` ([ref](https://developer.mozilla.org/en-US/docs/Web/API/Document/compatMode)). I decided to go with this approach as I thought quirks mode can have different impact as mentioned in the docs linked earlier, and some of its side effects could be masked with css reset etc. This way we'll be sure even if all quirks were masked :) 

Tested to confirm that prior to code change it would fail the test with `BackCompat` value set.

Also tried to do it as unit tests with testing-libarary or enzyme rendering but it's super though to test iframes! 😵

(Noticed the tests have failed but it was some kind of timeout on one of the instances in unrelated area of the code)

**Comment by jsnajdr** [comment]
Which service generates the actual document inside the iframe? And can we fix that service to send a correct doctype in the first place?

If we replace the document with a new one (doctype + original) when `readyState` becomes `interactive` or `complete`, doesn't that mean we'll load the document twice? That includes running all the inline scripts again, loading all the resources etc.

**Comment by tomasztunik** [comment]
@jsnajdr by default empty iframe has no doctype (renders in quirks mode). And it's the responsibility of content provider to set it up. It can be done either via src (and it would come from remote content provider) or srcDoc if content provider is local. In theory it should be possible to setup initial document state - including doctype - via srcDoc as mentioned but this caused errors in unrelated areas because of how iframe control is handed over to react via React.Portal. Made some attempts toward that but the surface of the change started getting out of hand and would result in a much more complex code. 

And regarding your concerns, this wouldn't cause the contents to setup twice as this happens before control is given back to react and before anything is rendered into the iframe, including scripts and styles as the iframe document override is synchronous and happens before these are processed. 

Was trying to cpu profile that change prompted by @ellatrix but it wasn't even showing up in the logs and perceptive rendering speed doesn't seem to be affected.

**Comment by jsnajdr** [comment]
Looking at the `Iframe` component that's being modified, the content of the `iframe` is managed by React, which renders a React UI into it, using a portal. It doesn't really support a `src` attribute, because it would overwrite the iframe markup with its own React UI?

So the task to do is to setup the initial empty document with a correct `<!DOCTYPE html>` tag? Yeah, then it makes sense, although instead of `document.write` we could write just `document.innerHTML = '<!DOCTYPE html>'` or init the iframe from a data URL:
```
<iframe src="data:<!DOCTYPE html>"/>
```

> Appending doctype to existing document won't change iframe's rendering mode.

This sounds like the `document.innerHTML` solution won't work and we really need to `document.write`?

> I've tried to populate the initial state using srcDoc, but this conflicted with different areas as it seemed to happen async with react ref setup hook.

`srcDoc` would be preferrable to `document.write`, and seems very similar to `<iframe src="data:..."/>`. Yes, it's probably async because `document.srcDoc = '...'` doesn't load immediately, but behaves as if it was loaded from a "virtual URL". We'd need to wait for some load event before calling `setIframeDocument` and triggering React render into the portal. But we already do that, because the rendering happens inside `setDocumentIfReady`?

Where were you calling `document.srcDoc =` when testing? The `load` event is probably too late.

**Comment by tomasztunik** [comment]
Modifying existing document was my first instinct as well as mentioned [here](https://github.com/WordPress/gutenberg/pull/38855#issuecomment-1041577123) but unfortunately once document rendering mode is set appending doctype doesn't change it despite doctype being visible in DOM.

I was passing static `srcDoc` as prop to the `iframe` element with correct doctype included but as you mention - this caused initial empty document to load and then be asynchronously replaced with the one provided by srcDoc - you've described it better than I did before I think - so document replace happened regardless. This would force us to add complexity in waiting for iframe to be ready by having to skip first initialisation with wrong `compatMode` and wait for the correct one to be loaded. This replace was causing React which already took over content to act as if someone pulled carpet from under its legs.

The way proposed here seemed cleaner to me from code complexity as it was doing the same just made it synchronous within the iframe binding/setup method as we were already giving the control of the iframe to react and felt like this will keep the concern encapsulated in this method.

If you think this is not the case I could try to look again at the `srcDoc` approach. Now that we talk about that I'm thinking if waiting for right compatMode rather than interactive state wouldn't be enough... Let me think if we should give it a go :)

**Comment by jsnajdr** [comment]
If you initialize the iframe as `<iframe srcDoc="..."/>` or `<iframe src="data:...">` then it should load that document right away, without loading an empty (`about:blank`) document first. I think it's worth trying one more time, and if it doesn't work, trying to observe carefully what exactly does not work.

Using `document.write` is acceptable, I just would write it as:
```js
document.open();
document.write( '<!DOCTYPE html>' );
document.close();
```
I think this is going to be a little less efficient because the API is synchronous -- like other legacy things like synchronous XHR requests or `window.alert`. But other than that, it's fine.

The `Iframe` component should be also modified to not accept a `src` prop, because from what I see it won't work. The component creates its own document and manages it.

**Comment by tomasztunik** [comment]
I think it's worth a try. Will look into it bit later today - thanks for joining in @jsnajdr and giving a new perspective.

**Comment by tomasztunik** [comment]
I think this looks cleaner now 🧹 

Thanks for the review @ellatrix and @jsnajdr. Was quite a trip into the iframe land :)

File: packages/block-editor/src/components/iframe/index.js [hunk 1]
```diff
@@ -264,6 +271,8 @@ function Iframe(
 				{ ...props }
 				ref={ useMergeRefs( [ ref, setRef ] ) }
 				tabIndex={ tabIndex }
+				// Correct doctype is required to enable rendering in standards mode
+				srcDoc="<!doctype html><html><head>yyy</head><body>xxx</body></html>"
```
Comment (jsnajdr) [inline packages/block-editor/src/components/iframe/index.js]: Here you only need to create the `<html>` element, with no content. The `createPortal` call will populate the `.documentElement` (which points to the `html` element) with `head` and `body`. As is the custom, the root element where React UI is mounted should be empty.

File: packages/block-editor/src/components/iframe/index.js [hunk 2]
```diff
@@ -174,9 +174,16 @@ function Iframe(
 	const setRef = useRefEffect( ( node ) => {
 		function setDocumentIfReady() {
 			const { contentDocument, ownerDocument } = node;
-			const { readyState, documentElement } = contentDocument;
-
-			if ( readyState !== 'interactive' && readyState !== 'complete' ) {
+			const { readyState, documentElement, compatMode } = contentDocument;
+
+			// As srcDoc loads contents asynchronously this will cause the iframe to
+			// load documents twice. We need to hook react to the correct contentDocument
```
Comment (jsnajdr) [inline packages/block-editor/src/components/iframe/index.js]: When you're testing, does the document really load twice for you? With `srcDoc`, it should only load once.

When I run this little test app:
```js
function App() {
  const elRef = React.useRef();
  React.useEffect(() => {
    function onLoad() {
      const doc = elRef.current.contentDocument;
      console.log("load", doc.readyState, doc.compatMode);
    }
    elRef.current.addEventListener("load", onLoad);
    return () => elRef.current.removeEventListener("load", onLoad);
  }, []);

  return <iframe ref={elRef} srcDoc="<!doctype html>" />;
}
ReactDOM.render(<App />, document.getElementById("root"));
```
I get only one `load` event logged:
```
load complete CSS1Compat
```

Comment (tomasztunik) [reply packages/block-editor/src/components/iframe/index.js]: Double checked by logging and breaking to inspect the iframe node and this is what we get:
Screenshot 2022-03-08 at 10 51 42

File: packages/block-editor/src/components/iframe/index.js (hunk 1 above)
Comment (tomasztunik) [reply packages/block-editor/src/components/iframe/index.js]: Good catch - removing - and left some debug noise on top.

File: packages/block-editor/src/components/iframe/index.js (hunk 2 above)
Comment (tomasztunik) [reply packages/block-editor/src/components/iframe/index.js]: ~I'm thinking if it wasn't because first load fires before ref is set and useEffect executes?~

Comment (tomasztunik) [reply packages/block-editor/src/components/iframe/index.js]: ~Or more likely it's a browser difference - Found this exploration https://stackoverflow.com/questions/10781880/dynamically-created-iframe-triggers-onload-event-twice/38459639#38459639 it seems it might be Chrome/webkit only?~

Comment (tomasztunik) [reply packages/block-editor/src/components/iframe/index.js]: On Firefox I get:
Screenshot 2022-03-08 at 11 15 01

So a little bit different handling but still load fires twice

Comment (jsnajdr) [reply packages/block-editor/src/components/iframe/index.js]: On my minimal example, I get only one load event even for Firefox: `load complete CSS1Compat`. I'll try it with the full Gutenberg editor.

> I'm thinking if it wasn't because first load fires before ref is set and useEffect executes?

Yes, the load certainly fires right after the element is added to DOM, which is before refs are set and effects executed. But the `iframe` element has the `srcDoc` attribute from the very beginning, and therefore should load only once.

Comment (tomasztunik) [reply packages/block-editor/src/components/iframe/index.js]: Ok got it. First one is initial state not `onload` event. It is not triggered by the listener but by the manual call to the setDocumentIfReady handler. 

https://github.com/WordPress/gutenberg/blob/21e2d2249e8a478fd4c6b49e44c1c170e5c44b2d/packages/block-editor/src/components/iframe/index.js#L213-L220

We have the comment here that load happens only in `firefox` but now with srcDoc in place it will fire everywhere it seems.

Should we remove L213-215 and leave only the onload event? This way we could remove the comment here and remove or simplify the comment inside the `setDocumentIfReady` and maybe remove the ready check before we initialise the iframe content.

Comment (jsnajdr) [reply packages/block-editor/src/components/iframe/index.js]: > Should we remove L213-215 and leave only the onload event?

Yes, it's most likely guaranteed that the load is async, and the `useRefEffect` callback is always called before the load finishes. We can rely on the `load` event to fire and avoid checking synchronously.

Comment (ellatrix) [reply packages/block-editor/src/components/iframe/index.js]: Yes, probably good to only use the load event now. The reason we didn't use the load event for all browsers was because we could start loading the editor much quicker.

**Review by ellatrix — CHANGES_REQUESTED** [review]
Could you change it so we're just using the load event?

File: packages/block-editor/src/components/iframe/index.js (hunk 2 above)
Comment (tomasztunik) [reply packages/block-editor/src/components/iframe/index.js]: I've removed the comment and direct call and removed the `compatMode` check from ready check. I believe with how much we've simplified it the simple comment around iframe event binding and reason behind srcDoc with E2E tests explaining it a bit more and guarding for ensuring we have the right `compatMode` should be enough.

File: packages/block-editor/src/components/iframe/index.js [hunk 3]
```diff
@@ -176,7 +176,7 @@ function Iframe(
 			const { contentDocument, ownerDocument } = node;
 			const { readyState, documentElement } = contentDocument;
 
-			if ( readyState !== 'interactive' && readyState !== 'complete' ) {
+			if ( readyState !== 'complete' && readyState !== 'interactive' ) {
```
Comment (jsnajdr) [inline packages/block-editor/src/components/iframe/index.js]: In the end this part of the patch only swaps the order of the two `readyState` checks and is redundant.

File: packages/block-editor/src/components/iframe/index.js [hunk 4]
```diff
@@ -203,11 +203,7 @@ function Iframe(
...
 
-		if ( setDocumentIfReady() ) {
-			return;
-		}
-
-		// Document is not immediately loaded in Firefox.
+		// Document set with srcDoc is not immediately ready.
 		node.addEventListener( 'load', () => {
 			setDocumentIfReady();
 		} );
```
Comment (jsnajdr) [inline packages/block-editor/src/components/iframe/index.js]: This can be done without the arrow function:
```js
node.addEventListener( 'load', setDocumentIfReady );
```
`setDocumentIfReady` will receive an `event` parameter which it doesn't use anyway.

Also, to tidy things up, the effect callback should return a cleanup function:
```js
return () => node.removeEventListener( 'load', setDocumentIfReady );
```

**Review by jsnajdr — APPROVED** [review]
Looks good! I posted two comments that are more about code quality rather than functionality. 🚢

File: packages/block-editor/src/components/iframe/index.js (hunk 4 above)
Comment (tomasztunik) [reply packages/block-editor/src/components/iframe/index.js]: done and done :)

**Comment by jsnajdr** [comment]
@tomasztunik Can you rebase the PR branch onto the latest `trunk`? That could make the React Native e2e tests green again.

**Comment by tomasztunik** [comment]
@jsnajdr seems it worked 👍

**Comment by jsnajdr** [comment]
Nice! Now only @ellatrix's :-1: blocks the merge. There used to be a "dismiss merge" action (the requested changes have been done) in the GitHub UI, but I don't see it now.

**Comment by tomasztunik** [comment]
It is under the ellipsis next to reviewer name but if it's available depends on how the repository is setup.  

Thanks again for great review session on this to both of you! I feel like I've recapped most of my knowledge on iframes and learned some on top :)

**Comment by tomasztunik** [comment]
Hey @ellatrix, Could you please do the final check? Appreciated!

**Comment by gziolo** [comment]
Everything looks green on CI. I see that all feedback was addressed so let's get this one in.
