### PR TITLE
Dataviews: Fix dataview columns width

### LINKED ISSUE #72774: DataViews table layout regression
In 6.8 the Title column 'fills' the available space regardless of cell content length to create a more consistent layout across pages. Here's a comparison between 6.8 (left) and 6.9 (right).

Image

On trunk the title column seems to 'hug' the content, so if you have (for example) pages with significantly different title lengths, that causes the layout to jump quite a bit as you paginate. Here are two pages from the same DataView:

Image
Image

### PR DESCRIPTION
**Pull request by rcrdortiz**
## What?

Closes https://github.com/WordPress/gutenberg/issues/72774

We've changed how the title column of dataview and other columns are rendered so that the title uses most of the available space. This way, pages with different title lengths will have a consistent layout.

## Why?

See the linked issue (the one we're solving) for more information.

## How?

Changed CSS classes to allow the title column to use as much available space as needed. The rest of the columns use the minimum space. Added a `colgroup` for better column intent declaration.

## Testing Instructions

1. Make sure you're on WordPress 6.9
2. Go to `http://localhost:8888/wp-admin/site-editor.php?p=%2Fpage`
3. You should see that the different columns of the dataview are arranged as in the screenshot.

## Screenshots or screencast 

|Before|After|
|---|---|
|Screenshot 2025-11-04 at 14 22 17|Screenshot 2025-11-06 at 17 07 51|
|||

### CODE REVIEW

**Comment by rcrdortiz** [comment]
I'm working on making the primary column have a max-width so that we don't get back to having the original issue.
See: https://github.com/WordPress/gutenberg/issues/72774#issuecomment-3486228796

File: packages/dataviews/src/dataviews-layouts/table/index.tsx [hunk 1]
```diff
@@ -374,6 +374,23 @@ function ViewTable< Item >( {
 				aria-describedby={ tableNoticeId }
 				role={ isInfiniteScroll ? 'feed' : undefined }
 			>
+				<colgroup>
```
Comment (ntsekouras) [inline packages/dataviews/src/dataviews-layouts/table/index.tsx:377]: I think this approach with `colgroup` is nice and we don't have to set styles for each row.

File: packages/dataviews/src/dataviews-layouts/table/style.scss [hunk 2]
```diff
@@ -298,18 +286,16 @@
...
 	.dataviews-view-table__group-header-cell {
 		font-weight: $font-weight-medium;
 		padding: $grid-unit-15 $grid-unit-60;
 		color: $gray-900;
 	}
 }
+
+
+/* Column width intents via colgroup: make non-primary columns shrink-to-fit */
+.dataviews-view-table col[class^="dataviews-view-table__col-"]:not(.dataviews-view-table__col-primary) {
```
Comment (ntsekouras) [inline packages/dataviews/src/dataviews-layouts/table/style.scss:318]: Besides this addition and the `colgroup` changes, why change anything else here?

I mean, you should also remove some `width:1%` above for checkbox td, but isn't that enough? Can you elaborate what use case is being discussed that is not handled by the above? 

I opened a [temp PR here](https://github.com/WordPress/gutenberg/pull/73016) (that I'll close after testing in order to land this one) for easier testing. --cc @jameskoster

Comment (rcrdortiz) [reply packages/dataviews/src/dataviews-layouts/table/style.scss:318]: We're still discussing some things [here](https://github.com/WordPress/gutenberg/issues/72774#issuecomment-3486228796), as mentioned in the description. This PR might not land, or might have many changes.

Comment (ntsekouras) [reply packages/dataviews/src/dataviews-layouts/table/style.scss:318]: Hm.. I still don't get the issue with just the changes I'm suggesting in my PR. Isn't the max-width already applied from [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/dataviews/src/dataviews-layouts/table/style.scss#L302)?

There is a chance I'm not getting what's more is needed by just applying a subset of changes from here, like my [temp PR](https://github.com/WordPress/gutenberg/pull/73016). Can you test and share a screenshot or something from what's more is needed?

Comment (rcrdortiz) [reply packages/dataviews/src/dataviews-layouts/table/style.scss:318]: The thing is that they explicitly made the columns look like that on purpose a few days ago in https://github.com/WordPress/gutenberg/pull/72417 

Screenshot 2025-11-06 at 09 15 44

@jameskoster was involved in that PR. And now we're asking for the opposite. I just want to make sure we don't get stuck in a loop where one day we apply one style and the next day we change it again. So it's not just a matter of fixing the issue, I would like to see a commitment to establish one way of having Dataviews present the columns before implementing a final fix. 

Most likely, we'll keep the colgroup and revert the changes from the PR  I shared above.

Comment (rcrdortiz) [reply packages/dataviews/src/dataviews-layouts/table/style.scss:318]: > Hm.. I still don't get the issue with just the changes I'm suggesting in my PR. Isn't the max-width already applied from [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/dataviews/src/dataviews-layouts/table/style.scss?rgh-link-date=2025-11-06T06%3A50%3A28Z#L302)?

@jameskoster mentioned
> Title col: no width ⇒ it absorbs remaining space.

This involves removing the max-width. This didn't work out very well (as was reported [here](https://github.com/WordPress/gutenberg/issues/72774#issuecomment-3486228796)) because, without a max-width, the title col overflows. That's why some of the code you're seeing in this PR is outdated or irrelevant, and why I suggested not reviewing these changes.

**Comment by ntsekouras** [comment]
@rcrdortiz can you add a changelog entry in dataviews package?

Also we should fix this [comment](https://github.com/WordPress/gutenberg/pull/73016#issuecomment-3497317735) from Jay (it was in my temp PR).

File: packages/dataviews/src/dataviews-layouts/table/style.scss [hunk 3]
```diff
@@ -313,3 +313,8 @@
 		color: $gray-900;
 	}
 }
+
+/* Column width intents via colgroup: make non-primary columns shrink-to-fit */
```
Comment (ntsekouras) [inline packages/dataviews/src/dataviews-layouts/table/style.scss:317]: I guess we can add this [change](https://github.com/WordPress/gutenberg/pull/73016/files#diff-90161488605f493d6d3373ccc278b42e484d27347f7e78794f182d181bf04050L50) too, right? I think `colgroup` handles that style for checkbox.

Comment (rcrdortiz) [reply packages/dataviews/src/dataviews-layouts/table/style.scss:317]: Yup, changed.

**Comment by rcrdortiz** [comment]
> @rcrdortiz can you add a changelog entry in dataviews package?
> 
> Also we should fix this [comment](https://github.com/WordPress/gutenberg/pull/73016#issuecomment-3497317735) from Jay (it was in my temp PR).

Addressed in the latest commit.

**Review by ntsekouras — APPROVED** [review]
Looks good, thanks!

Let's wait just a tiny bit for @jameskoster to verify the wrapping [white-space change](https://github.com/WordPress/gutenberg/pull/72969/files#diff-90161488605f493d6d3373ccc278b42e484d27347f7e78794f182d181bf04050R174) and let's land this.

**Comment by jameskoster** [comment]
Seems good now! :)

**Comment by ntsekouras** [comment]
@rcrdortiz please rebase for the changelog conflicts and let's land

**Comment by rcrdortiz** [comment]
> @rcrdortiz please rebase for the changelog conflicts and let's land

There ya go.

**Comment by ntsekouras** [comment]
Opened a PR for the manual [backport](https://github.com/WordPress/gutenberg/pull/73078).
