### PR TITLE
Post Title: Fix empty heading element when post_title is empty but get_the_title returns markup V2

### LINKED ISSUE #56465: Post Title: Empty heading element when `post_title` is empty but `get_the_title` returns markup
### Description

An empty heading element (or more specifically, a heading without text content) will be output from the Post Title block, if the post title returned from the loop has **markup but no text content**. The most likely case (only case?) is if a plugin/theme has filtered `the_title` and adds markup around an empty `post_title`.

The Post Title block currently does not output the heading if the post content is empty:
https://github.com/WordPress/gutenberg/blob/v17.1.0/packages/block-library/src/post-title/index.php#L30

But in a case where the title has markup without text content, it will **not** be an empty string and will result with in an empty heading element output.

In my specific case, this is triggered by the wp-uf2 (Microformats) plugin, which filters the title to add markup:
https://github.com/indieweb/wordpress-uf2/blob/master/includes/class-uf2-post.php#L65

Admitedly this could be handled by the plugin in some way, or by the theme. And in fact, in a classic theme this could/would have been handled there. However, I feel this case should be handled within the block, since it's generating the heading markup.

It was previously decided to not output the heading element if the title is empty. See:
https://github.com/WordPress/gutenberg/issues/29520

So an option would be to handle this simply with `strip_tags`: 
```php
if ( ! strip_tags( $title ) ) {
```

This way, the heading would only be output when there is content to go with it. That feels in line with the intention of the current code.

But I think a more appropriate option is to output a valid heading. The Post Title block is, presumably, used most often within a Query Loop block with other Post blocks (Post Excerpt, Date, etc.), so a heading should be output ahead of that content. If an `article` is wrapping the post, the heading is required. But that's a more involved change that could use discussion.

### Step-by-step reproduction instructions

1. Publish a new post without a title
2. On a page, add a Query Loop block with at least a Post Title
3. Install and activate the plugin 'wp-uf2' (or filter `the_title` to add markup wrapping the post title)
4. View the front end of the page created in step 2, locate the post with the empty title
5. View empty h2 in markup:
```html
<h2 class="wp-block-post-title"><a href="_permalink_" target="_self"><span class="p-name"></span></a></h2>
```

### Screenshots, screen recording, code snippet

_No response_

### Environment info

* WordPress 6.4.1
* Gutenberg plugin is not installed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by SirLouen**
Fixes #56465

This is a continuation of #70417, here you can find full context
Just for some context:

Fix empty heading element when `post_title` is empty but `get_the_title` returns markup by checking for text content after stripping HTML tags.

cc @ntsekouras

### CODE REVIEW

**Review by ntsekouras — APPROVED** [review]
Thank you!

File: packages/block-library/src/post-title/index.php [hunk 1]
```diff
@@ -27,7 +27,7 @@ function render_block_core_post_title( $attributes, $content, $block ) {
 	 */
 	$title = get_the_title();
 
-	if ( ! $title ) {
+	if ( ! strip_tags( $title ) ) {
```
Comment (Mamaduka) [inline packages/block-library/src/post-title/index.php]: Left a note regarding using both (`! title || ! strip_tags()`) checks in the original PR - https://github.com/WordPress/gutenberg/pull/70417#discussion_r2602521506.

Comment (SirLouen) [reply packages/block-library/src/post-title/index.php]: @Mamaduka technically that is correct. 

But this evaluation interruption is only useful when there is actually a complex task behind the second. 

Doing a `strip_tags` of an empty string is barely a function initialization, almost the same time complexity as the first comparison in terms of performance. 

So I feel it's unnecessarily redundant, but as you say, technically it's more efficient, so I would go with whatever you prefer.

Comment (Mamaduka) [reply packages/block-library/src/post-title/index.php]: Agree, it depends on the case. I don't have a strong opinion here; either option is fine with me.

Comment (SirLouen) [reply packages/block-library/src/post-title/index.php]: I've been profiling, and with a couple million iterations it scales faster without the first check.

Comment (SirLouen) [reply packages/block-library/src/post-title/index.php]: https://github.com/php/php-src/blob/c380f7e38298f479342397ac0bcfd0bf2bad2f86/ext/standard/string.c#L4820-L4861

The problem is that with an empty string, still gets to `php_strip_tags_ex` and allocates a buffer with the duplicated empty string. Over 10 million iterations, there is almost a 3x difference in total. It doesn't scale too crazily but is something to be considered.

I've reported this upstream, reporting a possible PR to improve this a little bit. 
https://github.com/php/php-src/pull/20675/

It's not going to come anytime early, but it could help us leave this simpler.

Comment (Mamaduka) [reply packages/block-library/src/post-title/index.php]: Thank you, @SirLouen!

**Review by Mamaduka — APPROVED** [review]
