### PR TITLE
Fix auto focus in accordion block

### LINKED ISSUE #71933: Accordion block requires manual click to start editing, unlike other blocks
### Description

Auto-focus feature is not working properly in the accordion block. I expect the cursor to immediately appear in the first editable field (summary/title) when the block is inserted, allowing me to start typing right away like other Gutenberg blocks, but nothing gets focused and I have to manually click on the summary field to start editing instead.
[this ](https://github.com/WordPress/gutenberg/issues/71777)might be related.

### Step-by-step reproduction instructions

1. Open WordPress block editor (Gutenberg)
2. Click the "+" button to add a new block
3. Search for and select "Accordion" block
4. Observe that the block is inserted but no cursor appears
5. Try typing immediately - nothing happens
6. Compare with other blocks:
  - Add a "Paragraph" block → cursor immediately appears, can type
  - Add a "Heading" block → cursor immediately appears, can type
  - Add "Accordion" block → no cursor, cannot type
 

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by byteninjaa0**
## What?

Closes #71933

Fix: Add auto-focus to accordion heading on block selection

## Why?

Automatically focus the accordion heading title field when the block
is selected, making it consistent with other Gutenberg blocks like
paragraphs and headings. This allows users to start typing immediately
after inserting an accordion block without requiring a manual click.

## How?

The implementation uses useRef to reference the RichText component and
useEffect to focus it when isSelected becomes true. A setTimeout with
cleanup ensures the DOM is ready before focusing and prevents memory
leaks.The implementation uses useRef to reference the RichText component and
useEffect to focus it when isSelected becomes true. A setTimeout with
cleanup ensures the DOM is ready before focusing and prevents memory
leaks.

### Testing Instructions for Keyboard

1. Open the WordPress block editor (create a new post or page)
2. Click the block inserter button (+) or press / to search for blocks
3. Search for "Accordion" and select it
4. The cursor should immediately appear in the accordion heading title field

## Screenshots or screencast 
before 

https://github.com/user-attachments/assets/7315632d-8051-4343-b401-8690e804d5e8

after 

https://github.com/user-attachments/assets/a4a8a1d1-a727-4fe3-bba2-8099b2d25ca4

|Before|After|
|-|-|
|||

### CODE REVIEW

File: packages/block-library/src/accordion-heading/edit.js [hunk 1]
```diff
@@ -18,7 +23,10 @@ export default function Edit( { attributes, setAttributes, context } ) {
 	} = context;
 	const TagName = 'h' + headingLevel;
 
+	const titleRef = useRef();
+
 	// Set icon attributes.
+
```
Comment (mikachan) [inline packages/block-library/src/accordion-heading/edit.js]: I don't think we need this extra line here.

```suggestion
```

File: packages/block-library/src/accordion-heading/edit.js [hunk 2]
```diff
@@ -28,6 +36,18 @@ export default function Edit( { attributes, setAttributes, context } ) {
 		}
 	}, [ iconPosition, showIcon, setAttributes ] );
 
+	useEffect( () => {
```
Comment (mikachan) [inline packages/block-library/src/accordion-heading/edit.js]: We also have `useRefEffect` in the `@wordpress/compose` package. Using this instead of `useEffect` would mean we wouldn't need the null check on `titleRef.current?.focus()`, but I don't think there's a major difference between the two.

File: packages/block-library/src/accordion-heading/edit.js [hunk 3]
```diff
@@ -28,6 +36,18 @@ export default function Edit( { attributes, setAttributes, context } ) {
...
+		if ( isSelected ) {
+			const timeoutId = setTimeout( () => {
```
Comment (mikachan) [inline packages/block-library/src/accordion-heading/edit.js]: Did you consider using `window.requestAnimationFrame` rather than a timeout here? This would be triggered after the browser's next repaint, which is more reliable than `setTimeout`.

**Review by mikachan — COMMENTED** [review]
Thanks for working on this! It's testing well for me 🙌 

I've left some inline comments with some possible improvements, let me know what you think.

**Comment by t-hamano** [comment]
Thanks for the PR! I understand the approach using the `isSelected` prop and effect, but I think that approach alone may not be sufficient.

After inserting the Accordion block, select it and press the "Add" button. The title field should no longer be focused:

https://github.com/user-attachments/assets/a1ea8ca5-df25-4d77-84e4-5384e8b56ec4

I haven't been able to look into it enough yet, but it might be worth looking a bit more into _why_ the problem occurs rather than simply fixing the symptoms.

**Comment by t-hamano** [comment]
@mikachan I was able to fix this problem by applying the following changes to trunk branch, but what do you think?

```diff
git diff
diff --git a/packages/block-library/src/accordion-heading/edit.js b/packages/block-library/src/accordion-heading/edit.js
index 8818e9cc4f..ceddfb4ae7 100644
--- a/packages/block-library/src/accordion-heading/edit.js
+++ b/packages/block-library/src/accordion-heading/edit.js
@@ -33,7 +33,7 @@ export default function Edit( { attributes, setAttributes, context } ) {
 
        return (
                <TagName { ...blockProps }>
-                       <button
+                       <div
                                className="wp-block-accordion-heading__toggle"
                                style={ spacingProps.style }
                        >
@@ -64,7 +64,7 @@ export default function Edit( { attributes, setAttributes, context } ) {
                                                +
                                        </span>
                                ) }
-                       </button>
+                       </div>
                </TagName>
        );
 }
diff --git a/packages/block-library/src/accordion/edit.js b/packages/block-library/src/accordion/edit.js
index f628c93e9b..43fdae369e 100644
--- a/packages/block-library/src/accordion/edit.js
+++ b/packages/block-library/src/accordion/edit.js
@@ -56,7 +56,7 @@ export default function Edit( {
        const isContentOnlyMode = blockEditingMode === 'contentOnly';
 
        const innerBlocksProps = useInnerBlocksProps( blockProps, {
-               template: [ [ ACCORDION_BLOCK_NAME ], [ ACCORDION_BLOCK_NAME ] ],
+               template: [ [ ACCORDION_BLOCK_NAME ] ],
                defaultBlock: ACCORDION_BLOCK,
                directInsert: true,
                templateInsertUpdatesSelection: true,
```

- Update the Accordion block template to have only one Accordion Item. Focus propagation may not be working properly due to multiple Accordion Items being inserted at the same time.
- Change the button element to a div element. This may be related to the fact that the button element is a focusable element.

In my tests, it works fine in most cases, except when I press the Add button, the RichText doesn't get focus.


https://github.com/user-attachments/assets/a428d51d-e83d-427b-8567-66d878d8311a

**Comment by byteninjaa0** [comment]
@t-hamano yes it works for me too but don't you think changing the button tag to div will cause regressions?

**Comment by mikachan** [comment]
> Change the button element to a div element. This may be related to the fact that the button element is a focusable element.

We used a button in the heading element so we could follow these examples as closely as possible: https://www.w3.org/WAI/ARIA/apg/patterns/accordion/examples/accordion/ and https://designsystem.digital.gov/components/accordion/. I believe the button helps describe the open/close action of the accordions. I'm not suggesting that we can't change the markup, but we should be careful not to reduce the accessibility.

**Comment by t-hamano** [comment]
How about adding `tabIndex="-1"` to the button element? I suspect the underlying issue is that the RichText component is wrapped in a focusable and tabbable button element.

**Comment by mikachan** [comment]
> How about adding tabIndex="-1" to the button element?

Good idea! I've just tried this out, and it works nicely when combined with reducing the number of accordions to one. I think this is a better solution as it's simpler and addresses the underlying issue.

```diff
diff --git a/packages/block-library/src/accordion-header/edit.js b/packages/block-library/src/accordion-header/edit.js
index fbd5a4e3005..682fb79c898 100644
--- a/packages/block-library/src/accordion-header/edit.js
+++ b/packages/block-library/src/accordion-header/edit.js
@@ -52,6 +52,7 @@ export default function Edit( { attributes, setAttributes, context } ) {
                                        style={ {
                                                ...spacingProps.style,
                                        } }
+                                       tabIndex="-1"
                                >
                                        { showIcon && iconPosition === 'left' && (
                                                <span
diff --git a/packages/block-library/src/accordion/edit.js b/packages/block-library/src/accordion/edit.js
index 7ed2693067f..52eced629b6 100644
--- a/packages/block-library/src/accordion/edit.js
+++ b/packages/block-library/src/accordion/edit.js
@@ -41,7 +41,7 @@ export default function Edit( {
        const { insertBlock } = useDispatch( blockEditorStore );

        const innerBlocksProps = useInnerBlocksProps( blockProps, {
-               template: [ [ ACCORDION_BLOCK_NAME ], [ ACCORDION_BLOCK_NAME ] ],
+               template: [ [ ACCORDION_BLOCK_NAME ] ],
                defaultBlock: ACCORDION_BLOCK,
:
```

**Comment by t-hamano** [comment]
@byteninjaa0, could you try this approach? https://github.com/WordPress/gutenberg/pull/72021#issuecomment-3365028665

**Comment by byteninjaa0** [comment]
Yes sure

**Comment by byteninjaa0** [comment]
it works for me too

https://github.com/user-attachments/assets/c7c5753a-e344-4296-9287-6a28ecd3b7da

**Comment by byteninjaa0** [comment]
@t-hamano should i send a commit with the changes?

**Comment by t-hamano** [comment]
@byteninjaa0 Yes 👍

File: packages/block-library/src/accordion-heading/edit.js [hunk 4]
```diff
@@ -28,14 +36,27 @@ export default function Edit( { attributes, setAttributes, context } ) {
...
+
 	const blockProps = useBlockProps();
 	const spacingProps = useSpacingProps( attributes );
 
 	return (
 		<TagName { ...blockProps }>
 			<button
 				className="wp-block-accordion-heading__toggle"
-				style={ spacingProps.style }
+				style={ { ...spacingProps.style } }
```
Comment (t-hamano) [inline packages/block-library/src/accordion-heading/edit.js]:
```suggestion
				style={ spacingProps.style }
```

Nit: No need to change this line

File: packages/block-library/src/accordion-heading/edit.js [hunk 5]
```diff
@@ -28,14 +36,27 @@ export default function Edit( { attributes, setAttributes, context } ) {
...
+		if ( isSelected ) {
+			const timeoutId = setTimeout( () => {
+				titleRef.current?.focus();
+			}, 0 );
+
+			return () => {
+				clearTimeout( timeoutId );
+			};
+		}
+	}, [ isSelected ] );
```
Comment (t-hamano) [inline packages/block-library/src/accordion-heading/edit.js]: This is no longer necessary, right?

**Review by t-hamano — APPROVED** [review]

**Review by t-hamano — APPROVED** [review]
LGTM 👍

**Comment by t-hamano** [comment]
I believe the failing E2e test is not related to this PR. See https://github.com/WordPress/gutenberg/pull/71630#issuecomment-3368296268
