### PR TITLE
Navigation block: Fix some off canvas appender accessibility issues

### LINKED ISSUE #47024: Nav offcanvas set the correct `aria-posinset` for the appender
As reported in https://github.com/WordPress/gutenberg/issues/46939#issuecomment-1376732975 by @talldan:

> the appender doesn't have the correct aria-posinset value (it's a minor thing as this isn't announced, but it'd be nice to fix it).

### PR DESCRIPTION
**Pull request by talldan**
## What?
Fixes #47024
See also #47011

Sets the correct `aria-posinset` and `aria-setsize` html attributes for the off-canvas editor's appender.

Also adds an aria description ('Append at position 3, Level 1') to give some context about where the block will be added.

## Why?
The `aria-posinset` and `aria-setsize` issue is very minor as screen readers don't announce them. But it's good to set it correctly just in case screenreaders do start announcing them after an update.

The aria description is used to replace the fact that screen readers don't announce that information These descriptions could be improved to mention the parent block name (especially in the case of the appender). The trouble is there's no safe way to access the `rootClientId` at the moment. For now this is roughly inline with the other aria descriptions in List View.

## How?
- Moves the `Appender` implementation to the `ListViewBranch` component (where it has access to the block count and nesting level).
- Passes in the correct values for `aria-posinset` and `aria-setsize`. The `aria-setsize` for blocks also needs to be incremented when there's an appender to account for the extra row.
- Adds an aria description to the appender.

### Testing Instructions for Keyboard
1. Create a new post
2. Tab to the 'Settings' button in the Editor top bar and ensure this is toggled on
3. Tab to the post content and insert a navigation block by typing '/navigation' and pressing enter
4. Tab to the block settings region (or navigate to the region) and tab until you reach the 'Block navigation structure'
5. If there are no blocks in the menu, you should land straight on the 'Add block' appender. If there are blocks, press the down arrow until you reach the 'Add block' button.
6. You should hear an additional description like 'Append at position 2, level 1'.

## Screenshots or screencast 
Screen Shot 2023-01-11 at 1 40 00 pm

### CODE REVIEW

File: packages/block-editor/src/components/off-canvas-editor/appender.js [hunk 1]
```diff
@@ -1,48 +1,69 @@
...
+					__experimentalIsQuick
+					{ ...props }
+					toggleProps={ { 'aria-describedby': descriptionId } }
+				/>
+				<div
+					className="offcanvas-editor-appender__description"
+					id={ descriptionId }
+				>
+					{ description }
+				</div>
```
Comment (getdave) [inline packages/block-editor/src/components/off-canvas-editor/appender.js:65]: This is a great idea ❤️

File: packages/block-editor/src/components/off-canvas-editor/style.scss [hunk 2]
```diff
@@ -14,6 +14,10 @@
 	}
 }
 
+.offcanvas-editor-appender__description {
+	display: none;
```
Comment (getdave) [inline packages/block-editor/src/components/off-canvas-editor/style.scss:18]: Question: does not `display: none` make the content in accessible to screen readers _entirely_? I guess the purpose here is that we don't want this text to be read out _except_ in the context of being the description of the inserter? Am I right?

**Review by getdave — APPROVED** [review]
I tested this with Voiceover and it behaved as expected. 

One small concern about the `display: none` but in my testing it did announce the description correctly so perhaps this isn't an Issue?

File: packages/block-editor/src/components/off-canvas-editor/style.scss (hunk 2 above)
Comment (talldan) [reply packages/block-editor/src/components/off-canvas-editor/style.scss:18]: I think `display: none` is fine for aria descriptions. For visually hidden text where a different approach needs to be taken.

Comment (getdave) [reply packages/block-editor/src/components/off-canvas-editor/style.scss:18]: Thanks for confirming.
