### PR TITLE
`Modal`: Fix loss of focus when clicking outside

### LINKED ISSUE #51722: Botch of focus return when dismissing `Modal` by clicking outside
### Description

When a modal is dismissed, focus is expected to return to the element that opened the modal. This fails when dismissing a modal by clicking outside it.

### Step-by-step reproduction instructions

1. Start in the Post Editor
2. Open the Options menu
3. Open the Preferences modal
4. Click outside the Preferences modal to dismiss it
5. Observe the Options menu is still open and clicking or focus other elements does not cause it to close.

### Screenshots, screen recording, code snippet

Here are a couple instances of the issue but there are more uses of `Modal` that are probably affected.

## Preferences modal
https://github.com/WordPress/gutenberg/assets/9000376/0115752a-8eb0-458a-a0ee-2906c3fc0430

## Post visibility confimation dialog
This is a `ConfirmDialog` which is built on top of `Modal`. I would expect the visibility dropdown menu would stay open and the focus return to the 'private' radio.

https://github.com/WordPress/gutenberg/assets/9000376/bb131537-e52b-40eb-a822-281c2af3bb4c

### Environment info

- Gutenberg trunk running on wp-now
- Chrome
- macOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by stokesman**
## What?
- Ensures that return of focus from the `Modal` component works when it’s dismissed by clicking outside.
- Adds a unit test to guard regressions.

## Why?
Focus loss is troublesome in various ways. This fixes #51722.

## How?
Uses a pointer event handler to preempt the `onFocusOutside` handling for dismissing the modal when clicking outside.

## Testing Instructions
1. Start in the Post Editor
2. Open the Options menu
3. Open the Preferences modal
4. Click outside the Preferences modal to dismiss it
5. Observe the Options menu is still open and focus returned to the “Preferences” button.

This can be generalized to any modal/confirmation dialog in any of the block editors.

### Testing Instructions for Keyboard
After step 4 of the above testing instructions you can try using editor keyboard shortcuts and observe they do work.

### Unit Test Testing Instructions
1. Check out the first commit on this branch `git checkout 1aaa194`
2. `npm run test:unit -- modal/test/index.tsx`
3. Observe the new test fails
4. `git switch -`
5. Repeat step 2.
6. Observe the new test passes

### CODE REVIEW

**Review by mirka — COMMENTED** [review]
This works as described, but it leaves me wondering why `useFocusOutside()` was necessary in the first place. Do you know? Since tabbing is constrained to the modal, wouldn't a click on the overlay be the only way that focus would move outside the modal?

I've even noticed that only relying on `useFocusOutside` to detect clicks on the overlay doesn't even work reliably when iframes are involved. For example in the Storybook in Canvas mode, if you open the modal, click outside the story iframe, then click on the overlay, it doesn't close.

It seems like a click handler on the overlay like in this PR is better _and_ sufficient.

**Comment by stokesman** [comment]
Thanks for having a look Lena 🙇 

> it leaves me wondering why `useFocusOutside()` was necessary in the first place. Do you know?

🤓 As best I can tell it never was technically necessary. The component had an overlay element and constrained tabbing from the start #6261 so you'd think it might have used a simple click handler on the overlay. Instead it used a more generalized approach provided by an HOC of an external library. Later that was replaced by the `withFocusOutside` HOC #16878 and of course later the hook equivalent. 

> Since tabbing is constrained to the modal, wouldn't a click on the overlay be the only way that focus would move outside the modal?

Practically speaking yes. Focus can be moved programmatically but I don't think that was intentionally supported or relied upon.

> It seems like a click handler on the overlay like in this PR is better _and_ sufficient.

Well, yeah that’s #51602 which removes the hook from the Modal. That stalled mostly because there’s one case of unintentional reliance on closing the modal when focus moves outside programmatically. Also, there is some desire to update `useFocusOutside` so it could support iframes so that `useDialog` and its consumers would not have the iframe issue.

File: packages/components/src/modal/index.tsx [hunk 1]
```diff
@@ -179,6 +188,9 @@ function UnforwardedModal(
 				overlayClassName
 			) }
 			onKeyDown={ handleEscapeKeyDown }
+			onPointerDown={
```
Comment (mirka) [inline packages/components/src/modal/index.tsx:195]: Can we add a TODO comment here? Something to the effect of "Reconcile with `useFocusOutside`" and "Ideally this should be an onClick".

**Review by mirka — APPROVED** [review]
Thanks for explaining how this relates to the other PRs 🙏 I think it makes sense to merge this to fix the immediate problem with the focus returning then!

File: packages/components/src/modal/index.tsx (hunk 1 above)
Comment (stokesman) [reply packages/components/src/modal/index.tsx:195]: I gave it my best and hopefully it captures what you had in mind. At least regarding the first part. I left out the bit about preferring `onClick`. That could provide some nuance to the interaction but I think handling `pointerdown` will still be necessary. That’s because if the default isn't prevented from `pointerdown` focus will move and be left unreturned by `useFocusReturn`.

Comment (mirka) [reply packages/components/src/modal/index.tsx:195]: It does 👍 I'm mostly concerned that we're treating a mere `pointerdown` as a `click` intent, which isn't technically true. For example I sometimes `mousedown` on a button but change my mind and drag away so it doesn't go through as a `click`.

But I guess we could even resolve that right now, if we just `event.preventDefault()` on the `pointerdown`, and wait until the `click` event to actually call `onRequestClose()`.

Comment (stokesman) [reply packages/components/src/modal/index.tsx:195]: Yep, that's just what I meant about nuance in the interaction. I do the same sometimes. To keep current behavior and this PR focused, I'd left it as is.

Since you agree it should be resolved I went ahead and tried it. It's not quite as simple as we likely both thought. It's also an opportunity to try a bit of further nuance as suggested by Aki https://github.com/WordPress/gutenberg/pull/51602#issuecomment-1600392962. So I've got a branch for it and will make it a separate PR.

Comment (stokesman) [reply packages/components/src/modal/index.tsx:195]: …and that PR #52994
