### PR TITLE
Paste: check plain text for Gutenberg content

### LINKED ISSUE #14534: Rich Text: Void blocks are considered plain-text, aren't converted
**Describe the bug**

A void block (a block with no content, self-closing), when pasted, is not converted to a block (at least in macOS Chrome). The root cause is that `ClipboardData#getData` considers the comment-only markup as plain-text, not HTML. This could be considered a browser bug, though it has the practical impact of preventing blocks from being converted correctly.

Example void block:

```html
<!-- wp:latest-posts /-->
```

**To Reproduce**

1. Copy the block markup above
2. Navigate to Posts > Add New
3. Click on the writing prompt
4. Paste the block markup

**Expected behavior**

The pasted text is converted into a Latest Posts block.

Alternatively, if it was interpreted as plain-text, the plain text of the markup should be inserted into the paragraph.

**Actual behavior**

Nothing happens.

**Desktop:**

 - OS: macOS Mojave Version 10.14.3 (18D109)
 - Browser: Chrome Version 73.0.3683.75 (Official Build) (64-bit)

**Additional context**

Both HTML and plain text data are retrieved from the clipboard and passed to `clipboardData`.

https://github.com/WordPress/gutenberg/blob/27c0d00102341615df838d1df2a40f1e33ff7973/packages/block-editor/src/components/rich-text/index.js#L236-L237

For this reason, if it's not possible to have the browser consider the comment markup as HTML, an alternative to consider may be to update the following condition to consider `plainText`, in addition to `HTML`:

https://github.com/WordPress/gutenberg/blob/27c0d00102341615df838d1df2a40f1e33ff7973/packages/blocks/src/api/raw-handling/paste-handler.js#L130-L133

cc @ellatrix

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #14534.

We should also check the plain text, if no HTML is present (pure plain text paste), for Gutenberg content.

## How has this been tested?

See #14534.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/blocks/src/api/raw-handling/paste-handler.js [hunk 1]
```diff
@@ -127,9 +127,14 @@ export function pasteHandler( { HTML = '', plainText = '', mode = 'AUTO', tagNam
 	// First of all, strip any meta tags.
 	HTML = HTML.replace( /<meta[^>]+>/, '' );
 
-	// If we detect block delimiters, parse entirely as blocks.
-	if ( mode !== 'INLINE' && HTML.indexOf( '<!-- wp:' ) !== -1 ) {
-		return parseWithGrammar( HTML );
+	// If we detect block delimiters in HTML, parse entirely as blocks.
+	if ( mode !== 'INLINE' ) {
+		// Check plain text if there is no HTML.
+		const content = HTML ? HTML : plainText;
```
Comment (aduth) [inline packages/blocks/src/api/raw-handling/paste-handler.js]: Should this apply for just the `parseWithGrammar` consideration, or also for the rest of `rawHandling`'s treatment of where it currently considers "HTML" ?

Comment (aduth) [inline packages/blocks/src/api/raw-handling/paste-handler.js]: I was hoping to find some information about when and why `clipboardData` would provide values for `text/plain` vs. `text/html`, and whether they're mutually exclusive, but the specification appears to be a bit ambiguous.

https://html.spec.whatwg.org/multipage/dnd.html#dom-datatransfer-getdata

I suppose if (a) the implementation favors HTML and (b) the non-existent form would be generated as an empty string (falsey), then this should be considered correct.

**Review by aduth — APPROVED** [review]

File: packages/blocks/src/api/raw-handling/paste-handler.js (hunk 1 above)
Comment (ellatrix) [reply packages/blocks/src/api/raw-handling/paste-handler.js]: We have separate logic for that: https://github.com/WordPress/gutenberg/pull/14536/files#diff-7703746fe73380c92b8bfe2370aab646R155

We also want to run it through the Markdown converter in other cases.

Comment (ellatrix) [reply packages/blocks/src/api/raw-handling/paste-handler.js]: I see it like this: there _should_ always be a plain text version of the pasted data, and if there's HTML, also an HTML version.

Because the browser might still provide an HTML version, even if there's no HTML, we check for it (as linked above): 
https://github.com/WordPress/gutenberg/pull/14536/files#diff-7703746fe73380c92b8bfe2370aab646R154

**Comment by ellatrix** [comment]
Thanks for the review!
