### PR TITLE
Fix: Button block text alignment.

### LINKED ISSUE #44614: Buttons Block: Add text align to block toolbar, and replace align
The Buttons block supports setting the width of buttons, but does not offer a way to change text alignment. In the following screenshots, the blocks have set their individual _alignments_ to center, left, and right:

Screenshot 2022-09-30 at 13 08 28
Screenshot 2022-09-30 at 13 08 43

However the "alignment" dropdown doesn't work in this case, because it simply applies `align[left|right|center]` classes. These are the legacy float based classes that were relevant when the Button block stood alone (see also #39937). Those classes need to still exist for legacy content that uses the Button in this way, but the controls are not useful anymore. In that light, we could replace those alignments with a text alignment dropdown, so we can do this:

Screenshot 2022-09-30 at 13 54 18

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Fixes: https://github.com/WordPress/gutenberg/issues/44614

The button block had a block alignment control for legacy reasons added before the buttons block existed. The block alignment control does not make sense anymore when the block is nested inside buttons and does not work as expected.

This PR removes the block alignment control, and adds a new text alignment control that allows results that were not previously possible.
cc: @jasmussen

## Testing

I pasted the following code on the block editor:
```
<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"textAlign":"center","width":25} -->
<div class="wp-block-button has-custom-width wp-block-button__width-25"><a class="wp-block-button__link has-text-align-center wp-element-button">center</a></div>
<!-- /wp:button -->

<!-- wp:button {"textAlign":"right","width":50} -->
<div class="wp-block-button has-custom-width wp-block-button__width-50"><a class="wp-block-button__link has-text-align-right wp-element-button">right</a></div>
<!-- /wp:button -->

<!-- wp:button {"textAlign":"left","width":25} -->
<div class="wp-block-button has-custom-width wp-block-button__width-25"><a class="wp-block-button__link has-text-align-left wp-element-button">left</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"textAlign":"center","width":100} -->
<div class="wp-block-button has-custom-width wp-block-button__width-100"><a class="wp-block-button__link has-text-align-center wp-element-button">default</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->
```

I verified the result in both editor and front-end of the site was this one:
image

I pasted the legacy button block markup on the editor:
```
<!-- wp:button {"align":"left"} -->
<div class="wp-block-button alignleft"><a class="wp-block-button__link wp-element-button">1</a></div>
<!-- /wp:button -->

<!-- wp:button {"align":"center"} -->
<div class="wp-block-button aligncenter"><a class="wp-block-button__link wp-element-button">2</a></div>
<!-- /wp:button -->

<!-- wp:button {"align":"right"} -->
<div class="wp-block-button alignright"><a class="wp-block-button__link wp-element-button">3</a></div>
<!-- /wp:button -->
```
I verified the result was this one, and there were no errors:

image

### CODE REVIEW

File: packages/block-library/src/button/deprecated.js [hunk 1]
```diff
@@ -51,6 +51,20 @@ const migrateBorderRadius = ( attributes ) => {
...
+function migrateAlign( attributes ) {
+	if ( ! attributes.align ) {
+		return attributes;
+	}
+	const { align, ...otherAttributes } = attributes;
+	return {
+		...otherAttributes,
+		className: classnames(
+			otherAttributes.className,
+			'align' + attributes.align
```
Comment (bangank36) [inline packages/block-library/src/button/deprecated.js]: I think we should use literal template for consistency, how do you think?

`` `align${ attributes.align }` ``

File: packages/block-library/src/button/deprecated.js [hunk 2]
```diff
@@ -780,10 +794,12 @@ const deprecated = [
...
 			!! attributes.customTextColor ||
 			!! attributes.customBackgroundColor ||
-			!! attributes.customGradient,
+			!! attributes.customGradient ||
+			!! attributes.align,
 		migrate: compose(
 			migrateBorderRadius,
-			migrateCustomColorsAndGradients
+			migrateCustomColorsAndGradients,
+			migrateAlign
```
Comment (bangank36) [inline packages/block-library/src/button/deprecated.js:802]: Is this for general alignment or `textAlignment` specifically?

Comment (jorgefilipecosta) [reply packages/block-library/src/button/deprecated.js:802]: This is for general align, in this PR, we remove general align and add textAlign. Here we are migrating the general alignment.

File: packages/block-library/src/button/deprecated.js (hunk 1 above)
Comment (jorgefilipecosta) [reply packages/block-library/src/button/deprecated.js]: Updated 👍

**Review by bangank36 — COMMENTED** [review]
LGTM

**Comment by jasmussen** [comment]
Nice, fast work, already merged. I can now do this:

Screenshot 2022-11-10 at 09 04 49

That is, Buttons justifies right, button is an explicit width, and text-left-aligned. Nice!
