### PR TITLE
[Commands]: Add group/ungroup commands only when eligible

### LINKED ISSUE #53921: Command Palette: Block commands that do not work on the selected block are displayed
### Description

Related to #52509

By #52509, commands related to blocks were added. However, you will see commands that are not expected to be used with the selected block.

### Step-by-step reproduction instructions

N/A

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/5fef782a-fb06-4229-bf8d-531df2faf404

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/53921
The `group/ungroup` commands are shown even if they conditions for grouping or ungrouping is met. This PR fixes that, by making the proper checks, for example if the selected blocks can be removed, etc..

## Testing Instructions
1. In the editor test both commands by selecting different blocks.

Some examples:
3. If a block is locked, it cannot be grouped or ungrouped
4. If we have not selected a single grouping block(ex a Paragraph block), the `ungroup` command shouldn't be available. Same goes if we have multiple selected blocks.

### Extra testing

Since I've changed `useConvertToGroupButtonProps` to use the new selectors, some test is needed to verify there is no regression in showing the `group/ungroup` buttons in block settings dropdown menu on different scenarios.

### CODE REVIEW

File: packages/block-editor/src/store/selectors.js [hunk 1]
```diff
@@ -2941,3 +2941,68 @@ export const getBlockEditingMode = createRegistrySelector(
...
+ * If a block has an `ungroup` transform, it is also ungroupable, without the
+ * requirement of being the default grouping block.
+ * Additionally a block can only be ungrouped if it has inner blocks and can
+ * be removed.
+ *
+ * @param {Object} state    Global application state.
+ * @param {string} clientId Client Id of the block. If not passed the selected block's client id will be used.
+ * @return {boolean} True if the block is ungroupable.
+ */
+export const isUngroupable = createRegistrySelector(
```
Comment (ntsekouras) [inline packages/block-editor/src/store/selectors.js:2957]: Personally I think it makes sense to have this logic in selectors. We could always make the private if it's not desired to expose them yet.

File: packages/block-editor/src/components/use-block-commands/index.js [hunk 2]
```diff
@@ -283,6 +277,22 @@ const useActionsCommands = () => {
 			},
 		};
 	} );
+	if ( isUngroupable ) {
+		commands.push( {
+			name: 'ungroup',
```
Comment (ntsekouras) [inline packages/block-editor/src/components/use-block-commands/index.js:260]: Note to me: add the prefix to the name.

File: packages/block-editor/src/components/convert-to-group-buttons/use-convert-to-group-button-props.js [hunk 3]
```diff
@@ -34,55 +34,27 @@ export default function useConvertToGroupButtonProps( selectedClientIds ) {
...
-						?.ungroup ) &&
-				!! firstSelectedBlock.innerBlocks.length;
-
-			// Do we have
-			// 1. Grouping block available to be inserted?
-			// 2. One or more blocks selected
-			const isGroupable =
-				groupingBlockAvailable && blocksSelection.length;
-
+			const _isUngroupable = isUngroupable();
```
Comment (ntsekouras) [inline packages/block-editor/src/components/convert-to-group-buttons/use-convert-to-group-button-props.js]: Note to me: check if we need to pass the selectedClientIds here..

**Comment by Mamaduka** [comment]
FYI #53974.

**Review by draganescu — APPROVED** [review]
Din't test but the code changes look good. 

The only problem I see is with making groupable / ungroupable selectors public. If people lean into them and we change the criteria of groupable and ungroupable we'll need to maintain back compat on this.

Groupable and ungroupable seems today as something internal to the block editor not something to depend on.

File: packages/block-editor/src/store/selectors.js [hunk 4]
```diff
@@ -2941,3 +2941,68 @@ export const getBlockEditingMode = createRegistrySelector(
...
+		}
+);
+
+/**
+ * Indicates if the provided blocks(by client ids) are groupable.
+ * We need to have at least one block, have a grouping block name set and
+ * be able to remove these blocks.
+ *
+ * @param {Object} state    Global application state.
+ * @param {string} clientId Client Id of the block. If not passed the selected blocks client ids will be used.
```
Comment (t-hamano) [inline packages/block-editor/src/store/selectors.js]: I think this parameter is `clientIds` (`string[]`).

File: packages/block-editor/src/store/selectors.js [hunk 5]
```diff
@@ -2941,3 +2941,68 @@ export const getBlockEditingMode = createRegistrySelector(
...
+			const { getGroupingBlockName } = select( blocksStore );
+			const block = getBlock( state, _clientId );
+			const groupingBlockName = getGroupingBlockName();
+			const _isUngroupable =
+				block &&
+				( block.name === groupingBlockName ||
+					getBlockType( block.name )?.transforms?.ungroup ) &&
+				!! block.innerBlocks.length;
+
+			return _isUngroupable && canRemoveBlock( state, _clientId );
```
Comment (t-hamano) [inline packages/block-editor/src/store/selectors.js:2973]: This selector additionally checks if the block can be deleted in order to determine if the block is ungroupable. Therefore, `canRemove` in the following sections may be removed?

https://github.com/WordPress/gutenberg/blob/3b114f7b736d322c837e84cb8483a04d3ed0f4d3/packages/block-editor/src/components/block-settings-menu-controls/index.js#L58-L59

Comment (ntsekouras) [reply packages/block-editor/src/store/selectors.js:2973]: Yes, good catch!
