### PR TITLE
Duotone: Backport from Core to fix filters in classic themes

### LINKED ISSUE #54099: Duotone filters are missing from live site when used in Classic Themes
### Description

On sites using a classic theme, Duotone filters apply in the post editor, but don't appear on the live site

### Step-by-step reproduction instructions

1. Activate a classic theme such as Twenty Twenty One
2. Open a new post and add an image block
3. Add a duotone filter to the image 
     - _(observe that this filter appears in the editor)_
4. Save and view the post
     - _(observe that the filter does not appear on the live site)_

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/27249804/ea71cf8c-e2ef-4647-a0fe-6d10f2744d9e

Inspecting the image block shows `wp-duotone-rgb10400-rgb255232232-1`, even though the filter is not applied.

Markup on 2023-08-31 at 15:16:20

### Environment info

- WP 6.3.1
- GB 16.5.1

Deactivating Gutenberg altogether allows the Duotone filter to appear on the live site.

Possibly related? https://github.com/WordPress/gutenberg/issues/49293 (I can't tell if this is the same issue - it appears to just be about the default colors available, and not the function of duotone on the live site).

Many WordPress.com customers have reported this issue; those reports are being tracked here: https://github.com/Automattic/wp-calypso/issues/78442

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #54099
Related Core PR: https://github.com/WordPress/wordpress-develop/pull/4839

## What?

This PR applies the Duotone filter fix in the Classic theme committed in Core to the Gutenberg plugin.

## Why?

Without this PR, the Dutone filter will not be applied to Classic themes when the Gutenberg plugin is activated, as reported in #54099.

## How?

I applied the changes made in the core as is.

## Testing Instructions

Verify that the image block duotone filter works in both block and classic themes.

### CODE REVIEW

File: lib/class-wp-duotone-gutenberg.php [hunk 1]
```diff
@@ -939,9 +939,17 @@ public static function output_footer_assets() {
...
-			wp_add_inline_style( 'core-block-supports', self::get_global_styles_presets( self::$used_global_styles_presets ) );
+		// In block themes, the CSS is added in the head via wp_add_inline_style in the wp_enqueue_scripts action.
+		if ( ! wp_is_block_theme() ) {
+			$style_tag_id = 'core-block-supports-duotone';
+			wp_register_style( $style_tag_id, false );
+			if ( ! empty( self::$used_global_styles_presets ) ) {
+				wp_add_inline_style( $style_tag_id, self::get_global_styles_presets( self::$used_global_styles_presets ) );
+			}
+			if ( ! empty( self::$block_css_declarations ) ) {
+				wp_add_inline_style( $style_tag_id, wp_style_engine_get_stylesheet_from_css_rules( self::$block_css_declarations ) );
```
Comment (t-hamano) [inline lib/class-wp-duotone-gutenberg.php]: Should the prefix of `wp_style_engine_get_stylesheet_from_css_rules()` function be changed to `gutenberg_`?

**Comment by nderambure** [comment]
Hello !
Any news about this ?

Side question : now that duotone is part of block rendering, and no more in global styles, how do we force the ouput of SVGs to user Duotone outside the content of a post. I was just applying `filter: url('#wp-duotone-accent3-to-accent4');` to some img tags, but it does not work anymore.

Thx !

File: lib/class-wp-duotone-gutenberg.php (hunk 1 above)
Comment (ajlende) [reply lib/class-wp-duotone-gutenberg.php]: > Should the prefix of `wp_style_engine_get_stylesheet_from_css_rules()` function be changed to `gutenberg_`?

Yeah, the `gutenberg_` prefixed functions should be preferred over the `wp_` ones if they exist in the plugin. This way we're testing the changes to those functions everywhere within the plugin. That way issues are much more likely to surface before porting things to core.

**Review by ajlende — APPROVED** [review]
Thanks @t-hamano! Sorry for the delay on the review—I got really busy for a while and forgot about this one.

I've rebased with trunk, made the `gutenberg_` prefix change, and tested the whole thing. It looks good to me. 👍
