### PR TITLE
Format Library: Improve inline image replacement workflow

### LINKED ISSUE #25909: Inline Images: Can't replace image
**Describe the bug**
When you add an inline image, there isn't a way to replace it with a new image.

**To reproduce**
1. Go to the editor and add some text.
2. Click on the dropdown arrow and click "Inline image"
3. Upload or select an image
4. Click on the image; you can change its size, but not replace the image.

**Expected behavior**
I expect inline images to have a similar block toolbar as images, or, image settings should be appended to the paragraph/heading toolbars.

**Screenshots**
image

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default?: Default

**Additional context**
This came up while trying to implement a pattern in Twenty Twenty-One: https://github.com/WordPress/twentytwentyone/pull/299

### PR DESCRIPTION
**Pull request by Sukhendu2002**
## What?

Closes: https://github.com/WordPress/gutenberg/issues/25909

This PR improves the user experience when working with inline images by addressing issue #25909, where users couldn't easily replace an existing inline image.

## Changes:
1. **Dynamic Button Label**: Changes the toolbar button title to "Replace image" when an inline image is selected.
2. **Image Preselection**: Preselects the current image in the media library when replacing an inline image, providing better context for users.

## Testing Instructions
1. Open the block editor and create a new post
2. Add a paragraph block and type some text
3. Place your cursor in the paragraph and open the format dropdown (+ icon)
4. Select "Inline image" from the dropdown menu
5. Upload or select an image from the media library
6. After the image is inserted, click on it to select it
7. Verify that the toolbar button now shows "Replace image" instead of "Inline image"
8. Click the "Replace image" button
9. Verify that the media library opens with the current image already selected/highlighted
10. Select a different image and confirm it replaces the existing inline image

## Screenshots or screencast 

https://github.com/user-attachments/assets/c211f3dc-af8e-4217-821a-809e0decd45f

### CODE REVIEW

File: packages/format-library/src/image/index.js [hunk 1]
```diff
@@ -145,10 +145,20 @@ function Edit( {
...
 	contentRef,
 } ) {
+	let currentImageId;
+	if ( isObjectActive && activeObjectAttributes.className ) {
+		const wpImageMatch =
+			activeObjectAttributes.className.match( /wp-image-(\d+)/ );
+		if ( wpImageMatch && wpImageMatch[ 1 ] ) {
+			currentImageId = parseInt( wpImageMatch[ 1 ], 10 );
+		}
+	}
```
Comment (Mamaduka) [inline packages/format-library/src/image/index.js]: Suggestion: We could extract this into a helper function near the top of the file.

```js
function getCurrentImageId( activeObjectAttributes ) {
    if ( ! activeObjectAttributes?.className ) {
        return undefined;
    }

    const [ , id ] = activeObjectAttributes.className.match( /wp-image-(\d+)/ ) ?? [];

    return id ? parseInt( id, 10 ) : undefined;
}
```

File: packages/format-library/src/image/index.js [hunk 2]
```diff
@@ -145,10 +145,20 @@ function Edit( {
...
+
 	return (
 		<MediaUploadCheck>
 			<MediaUpload
 				allowedTypes={ ALLOWED_MEDIA_TYPES }
+				value={ currentImageId }
```
Comment (Mamaduka) [inline packages/format-library/src/image/index.js]:
```suggestion
				value={ getCurrentImageId( activeObjectAttributes ) }
```

The `activeObjectAttributes` is an empty object, when `isObjectActive` is false, so the method will return `undefined` as expected.

**Review by Mamaduka — APPROVED** [review]
Thanks, @Sukhendu2002!
