### PR TITLE
List Block: Fix numbering style to be applied correctly

### LINKED ISSUE #52826: List block list-style-type issue
### Description

Hello Team,

I have worked on the Gutenberg **List block** and found that the list block **list-style-type** is not working as expected in different themes.

When we are trying to change its **NUMBERING STYLE**, it's not working as expected. Also, the selected **NUMBERING STYLE** is not selected when we refresh the page; it always displays the first option. So, I think that it should be fixed.

Here, I have provided its video:
**[Issue Video](https://share.cleanshot.com/lPwkNFyCWCB40N7Ck91z)**

Please review it and let me know your feedback for the same.

Thanks,

### Step-by-step reproduction instructions

- Type / to choose a List block
- Add list items
- Also, we can add sub-items for list items.
- Select **Ordered** from **components-toolbar-group** box
- Then change the **NUMBERING STYLE** dropdown option based on the requirement from the block setting right side.
- Save the changes and publish the page.
- Then open page **Preview in the new tab**
 

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress version: 6.2.2, Gutenberg 16.2.1, Theme active: Twenty Twenty, Twenty Twenty-Two, Twenty Twenty-Three,
- Browser: Google chrome, Version 114.0.5735.198 (Official Build) (arm64)
- Device: MacBook Air M1
- OS: macOS Ventura 13.4.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #54384: List Block: Numbering Style setting not working on Twenty Twenty-One theme.
### Description

I have tested the list block on twenty twenty-one theme and found the numbering style setting not working on it.

### Step-by-step reproduction instructions

1.  First, Active the Twenty Twenty-One theme.
2. Create a new page and take the list block.
3. Change the number list and check the numbering style setting.
4. Apply setting like "Uppercase letters", "Lowercase letters", "Uppercase Roman numerals", and "Lowercase Roman numerals" And check it not working.

### Screenshots, screen recording, code snippet

Please check the provided screen recording video below for a better understanding of the issue.

Video URL: https://share.cleanshot.com/jRFR0SjRNQF18R0k3Bp9

### Environment info

- WordPress 6.3.1 running
- Chrome
- macOS 13.2

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes: #52826
Fixes: #54384

**Update:** This PR has changed its approach based on the discussion. For the latest implementation details, please check the comments [here](https://github.com/WordPress/gutenberg/pull/53301#issuecomment-1666753766).

-------

## What?

This PR adds explicit selectors and styles to ensure that numbering styles are applied correctly under certain conditions.

## Why?

From what I have found in [this comment](https://github.com/WordPress/gutenberg/issues/52826#issuecomment-1645582401), this problem is because the WP-Admin `common.css` and `reset.css` applied to the editor are overriding the styles. I also found that these styles are also loaded into the iframe editor in the case of the classic theme.

However, if, for example, custom fields are enabled or a block with apiVersion 2 is present, the editor is not iframed.
As a result, the WP-Admin reset style is applied even in the case of a block theme, which causes problems.

## How?

This issue should be approached on the assumption that a WP-Admin reset style exists.

I first wrote the following selector:

```css
ol {
	&[type="A"] {
		list-style-type: upper-alpha;
	}
	&[type="a"] {
		list-style-type: lower-alpha;
	}
	&[type="I"] {
		list-style-type: upper-roman;
	}
	&[type="i"] {
		list-style-type: lower-roman;
	}
}
```

However, it did not take into account whether the value was uppercase or lowercase, as seen in the screenshot below (confirmed in Chrome and FireFox)

type

Therefore, I explicitly generated class names like `is-type-${type}` and applied styles to them.

## Testing Instructions

- Activate custom fields from the Preferences menu.
- Insert a List block and apply the Ordered style.
- Change the Numbering Style.
- (trunk): The numbering style should not change.
- (This PR): The numbering style should change correctly.

### CODE REVIEW

**Review by ramonjd — APPROVED** [review]
Nice find!

**Comment by glendaviesnz** [comment]
This tested well for me in the editor, but I noticed there is a similar issue in the front end with some non-block themes, eg. TT1. In this case the themes own style is overriding the user styles assigned in the editor:

Screenshot 2023-08-04 at 4 09 34 PM

I wonder if we should be doing something to try and give the styles for this a higher specificity in the frontend 🤔 This could be a follow up PR if we do.

**Comment by ramonjd** [comment]
> I wonder if we should be doing something to try and give the styles for this a higher specificity in the frontend 🤔 This could be a follow up PR if we do.

Would it hurt to use `.wp-block-list` 🤷🏻

**Comment by glendaviesnz** [comment]
> Would it hurt to use `.wp-block-list` 🤷🏻

I guess it depends on the selectors a theme might be using  - this is why the other user applied global styles use a `! important`, but we then hit the same potential issue that non-block theme authors may not be happy with their styles being hammered with that heavy-handed approach. But it seems to make sense that in this case, users should be able to expect their selection of numbering to override the theme one.

**Comment by t-hamano** [comment]
Thanks for the review, @ramonjd, @glendaviesnz.

I am a bit confused about applying this style to the front end as well. At the very least, this is because the markup must be updated for this attribute alone as follows:

Before

```html
<ul type="a">
  <li>List Item</li>
  <li>List Item</li>
</ul>
```

After

```html
<ul type="a" class="is-type-a">
  <li>List Item</li>
  <li>List Item</li>
</ul>
```

On the back end, `reset.css` and `common.css` are applied, so an approach is needed to override them. On the front end, however, style control is completely left to the theme side. 

However, the classic theme may need a good deal of updating to properly apply these styles on the front end. There may be some burden on the theme developer and the default theme regarding updates, but I personally think it is acceptable for now 🤔

What do you think?

File: packages/block-library/src/list/edit.js [hunk 1]
```diff
@@ -124,8 +129,12 @@ function IndentUI( { clientId } ) {
 }
 
 export default function Edit( { attributes, setAttributes, clientId, style } ) {
+	const { ordered, type, reversed, start } = attributes;
 	const blockProps = useBlockProps( {
 		...( Platform.isNative && { style } ),
+		className: classnames( {
+			[ `is-type-${ type }` ]: type && type !== '1',
```
Comment (ellatrix) [inline packages/block-library/src/list/edit.js]: Would love if we can find a solution without adding extra classes.

Comment (ellatrix) [reply packages/block-library/src/list/edit.js]: Is there no way we can tweak the reset styles that we have?

**Review by ellatrix — COMMENTED** [review]
I don't love the classes. Let's look into the root causes as well. `common.css` should never be added to the iframe, that's defeating the whole purpose, so something is going wrong there.

**Comment by ellatrix** [comment]
So it seems that `common` is added as a dependency, not because it's an actual dependency, but because the wish is to reset after that stylesheet. 

https://github.com/WordPress/gutenberg/blob/284455b1c4830c45ea0df749b801aab718c535dd/lib/client-assets.php#L348

**Comment by t-hamano** [comment]
Unintended CSS loading into the iframe should be fixed, but since the editor may not be an iframe (meta box is enabled, or v2 blocks are included, etc.), I think we need to address this issue, assuming that WP-Admin's `reset.css` and `common.css` exist.

**Comment by ellatrix** [comment]
And the funny thing is, we actually had to add the reset styles for lists because it was breaking list margins:

https://github.com/WordPress/gutenberg/pull/48286/files#diff-d66c57d67603bf45e2664289929b228b0eb69b037553b5c35a3497182a7e17d5R50

So the reset styles both fix and break list styles at the same time! Ideally we should just make it work without the reset styles.

**Comment by ellatrix** [comment]
And in addition, we should fix the reset styles so that they're not too aggressive. Looking into it.

**Comment by ellatrix** [comment]
> Unintended CSS loading into the iframe should be fixed, but since the editor may not be an iframe (meta box is enabled, or v2 blocks are included, etc.), I think we need to address this issue, assuming that WP-Admin's `reset.css` and `common.css` exist.

Yes, but is there no way to fix the reset styles?

**Comment by t-hamano** [comment]
> assuming that WP-Admin's reset.css and common.css exist.

Sorry, this was my mistake. I see that WP-Admin enqueues only `common.css`, and `reset.css` is enqueued from the block editor. 🙈 However, as long as the decimal style is defined in WP-Admin's `common.css`, adjusting `reset.css` may not solve the problem.

style

BTW, I have learned that [the `type` attribute is deprecated](url). Perhaps we could just replace `type` attribute with inline style...

**Comment by ellatrix** [comment]
I've added a commit that adds reset styles without the classes https://github.com/WordPress/gutenberg/pull/53301/commits/72512d7ca0068cadc0f4992db2bcb0f9778b14e2

**Comment by ellatrix** [comment]
> BTW, I have learned that [the `type` attribute is deprecated](url). Perhaps we could just replace `type` attribute with inline style...

Yes, that a good option

**Comment by ellatrix** [comment]
Also, this has been an issue pre 6.3

**Comment by ellatrix** [comment]
> However, it did not take into account whether the value was uppercase or lowercase, as seen in the screenshot below (confirmed in Chrome and FireFox)

Oh, I didn't see this comment! Removing my commit 😅

**Comment by t-hamano** [comment]
Yes, I do not understand this behavior 😅 I think I'll switch to an inline style implementation.

case

**Comment by ellatrix** [comment]
Since this is not a regression, maybe we should indeed rewrite the feature to use CSS styling.

**Comment by ellatrix** [comment]
Have you seen https://caniuse.com/css-case-insensitive? Apparently you create a case sensitive selector: `[type="I" i]`

**Comment by ellatrix** [comment]
What that makes attribute selectors case INsensitive, meaning they're normally case sensitive? 🤔 Don't understand this feature

**Comment by t-hamano** [comment]
The case-sensitive CSS selector seems to exist. However, only Firefox supports it, and indeed we have confirmed that the following CSS works only in Firefox.

https://caniuse.com/mdn-css_selectors_attribute_case_sensitive_modifier

It may still be better to use inline styles.

**Comment by ellatrix** [comment]
Yes, let's migrate this to CSS styles. Also, there seems to be a lot more options an flexibility with CSS styles, so that's exciting!

**Comment by t-hamano** [comment]
Based on our previous discussions, I have taken the following approach:

- Do not use the `type` attribute, but output `list-style-type` as the inline style
- Output the inline style only if the element is `ol` element and Numbering Style is not the default `Numbers` (`decimal`)
- The inline style is also output on the front end, so the problem reported in [this comment](https://github.com/WordPress/gutenberg/pull/53301#issuecomment-1664943833) should be resolved
- Updated raw-handler and paste-handler tests
- The fixture was added in #51186, but since we did not update `save.js` in #51186, I think this fixture was not needed. Therefore, this PR updated this fixture. In addition, the file name was changed from `core__list__ol-with-type` to `core__list__deprecated-v2` to [prevent unit test failure due to the console log output when deprecations are executed](https://github.com/WordPress/gutenberg/blob/25215a997e23b8b4b05b122ccb1c2778dcd4cfa7/test/integration/full-content/full-content.test.js#L130-L140).

**Comment by ellatrix** [comment]
@t-hamano This seems related too, when we use CSS? #45830 :)

**Comment by t-hamano** [comment]
I believe that even if we merged this PR first, we would still be able to accommodate the requests that would be added in #45830, but it might be better to first decide in #45830 which list types the core should implement.

**Comment by t-hamano** [comment]
@ellatrix What are your thoughts on whether this PR should ship to WP6.4? We may need to continue discussing what list types to support, but personally, I think it's okay to inherit the existing list types and merge this PR that fixes the bug.

**Comment by ellatrix** [comment]
I don't think it's a serious issue and we're introducing a block deprecation. Why not switch immediately to CSS styling?

**Comment by t-hamano** [comment]
Ok, now let's merge 👍

**Comment by ellatrix** [comment]
@t-hamano ? I think we shouldn't introduce a new deprecation if we're planning to change it immediately again? Why not switch immediately to CSS styling?

**Comment by t-hamano** [comment]
@ellatrix Sorry, I may have misunderstood something. However, as noted in [this comment](https://github.com/WordPress/gutenberg/pull/53301#issuecomment-1666753766), this PR has been updated to use inline CSS styles. am I missing something?

File: packages/block-library/src/list/save.js [hunk 2]
```diff
@@ -7,7 +7,16 @@ export default function save( { attributes } ) {
...
+		<TagName
+			{ ...useBlockProps.save( {
+				reversed,
+				start,
+				style: {
+					listStyleType:
+						ordered && type !== 'decimal' ? type : undefined,
+				},
+			} ) }
+		>
```
Comment (ellatrix) [inline packages/block-library/src/list/save.js:19]: Why are we changing the save function if we're only needing to fix something in the admin?

Comment (t-hamano) [reply packages/block-library/src/list/save.js:19]: I think this PR settled on the solution of using the inline style (`list-style-type`) because the `type` attribute of the list would be overridden on the editor side. Shouldn't the save function side also be updated to match the editor side?

**Comment by ellatrix** [comment]
Oh ok, I didn't realise it had been rewritten. I'll review

**Comment by ellatrix** [comment]
Sorry, in that case it seems fine!

**Comment by t-hamano** [comment]
Thanks! If you find any issues with this PR in the future, I will be happy to address them 👍

File: packages/block-library/src/list/edit.js [hunk 3]
```diff
@@ -124,9 +124,14 @@ function IndentUI( { clientId } ) {
 }
 
 export default function Edit( { attributes, setAttributes, clientId, style } ) {
+	const { ordered, type, reversed, start } = attributes;
 	const blockProps = useBlockProps( {
-		...( Platform.isNative && { style } ),
```
Comment (ellatrix) [inline packages/block-library/src/list/edit.js:128]: Not sure why this was ignored for native. Does that have any consequences for the new inline style?

File: packages/block-library/src/list/save.js (hunk 2 above)
Comment (ellatrix) [reply packages/block-library/src/list/save.js:19]: Yes, sorry, I misunderstood and thought this was the previous fix.

File: packages/block-library/src/list/edit.js (hunk 3 above)
Comment (t-hamano) [reply packages/block-library/src/list/edit.js:128]: Doesn't this line mean that the Edit component's `style` prop is used _only_ on native platforms? This line appears to have originally been changed in #42711, which changed the List block to use nested blocks.

https://github.com/WordPress/gutenberg/pull/42711/files#diff-99bb126c574fb4790a60e7b6cf372c8a8bce3114f8a9740d0f92e47e74238724R133

File: packages/block-library/src/list/save.js (hunk 2 above)
Comment (youknowriad) [reply packages/block-library/src/list/save.js:19]: How were these styles injected into the frontend before this? Why did we decide to use inline styles now?

Comment (ellatrix) [reply packages/block-library/src/list/save.js:19]: Because the type attribute is deprecated.

Comment (t-hamano) [reply packages/block-library/src/list/save.js:19]: Another reason is that the `type` attribute is overwritten by CSS styles ([see](https://github.com/WordPress/gutenberg/pull/53301#issuecomment-1664943833)). We also tried overriding it with a CSS style using the type attribute as a selector, but there was also the problem that uppercase and lowercase letters were not distinguished ([see](https://github.com/WordPress/gutenberg/pull/53301#issuecomment-1665772786)).

Comment (youknowriad) [reply packages/block-library/src/list/save.js:19]: Ok Thanks for the details. 👍
