### PR TITLE
Edit Post: Fix pattern modal reopening when making the title empty again

### LINKED ISSUE #55847: Page: Empty title reopens pattern selection modal
### Description

When creating a new page, if a starter pattern exists, a modal will be displayed to select a pattern. If you close the modal without selecting a pattern, enter characters in the title, and delete all the characters, the pattern selection modal will be displayed again.

This problem doesn't seem to occur if you've entered some content before entering the characters in the title.

WordPress Version: Latest (6.5-alpha-57054)
Gutenberg Plugin: Latest (reproduces even if disabled)

### Step-by-step reproduction instructions

- Enable TT4 theme.
- Add a new page.
- A pattern selection modal should appear.
- Close the modal window **without selecting a pattern**.
- Enter some text in the title area.
- Delete all that text.
- The pattern modal should now appear.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/647a16ee-d5a7-4e34-81fe-288842d98ff4

### Environment info

WordPress Version: Latest (6.5-alpha-57054)
Gutenberg Plugin: Latest (reproduces even if disabled)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #55847

## What?
This PR fixes an issue where after closing the pattern modal when opening a new page, if you make the post title empty again, the modal appears again.

https://github.com/WordPress/gutenberg/assets/54422211/647a16ee-d5a7-4e34-81fe-288842d98ff4

## Why?

This modal primarily consists of `StartPageOptions` and a child `StartPageOptionsModal` component. Whether this modal is opened is managed by the child `StartPageOptionsModal` component.

Whether or not child `StartPageOptionsModal` components are rendered is controlled by the `shouldOpenModal` variable. This variable contains the condition whether the post is empty or not (`isCleanNewPost`).

When you enter a post title and then empty the title, the `shouldOpenModal`  variable changes from `false` to `true`, causing the `StartPageOptionsModal` component to be rendered again.

As a result, the `StartPageOptionsModal` component's `modalState` is initialized and the modal is displayed again.

## How?
I decided to manage whether the modal is closed or not using a higher-level component, the `StartPageOptions` component. This PR is related to #53673 which improved performance, but should not impact performance.

## Testing Instructions

- Enable TT4 theme.
- Add a new page.
- A pattern selection modal should appear.
- Close the modal window without selecting a pattern.
- Enter some text in the post title area.
- Delete all that text.
  - This PR: The pattern modal should NOT appear.
  - trunk: The pattern modal should appear.

### CODE REVIEW

File: packages/edit-post/src/components/start-page-options/index.js [hunk 1]
```diff
@@ -83,19 +75,20 @@ function StartPageOptionsModal() {
...
-					onChoosePattern={ () => setModalState( 'closed' ) }
+					onChoosePattern={ onClose }
 				/>
 			</div>
 		</Modal>
 	);
 }
 
 export default function StartPageOptions() {
+	const [ modalState, setModalState ] = useState( 'initial' );
```
Comment (jsnajdr) [inline packages/edit-post/src/components/start-page-options/index.js]: It's nice that you've been able to reduce the three-state (`initial`, `open`, `closed`) logic into just two states, "open", "closed". The code could be further simplified to use a single boolean value:
```js
const [ isClosed, setClosed ] = useState( false );
```

**Review by jsnajdr — APPROVED** [review]
Thanks for a nice fix! I was able to reproduce the issue and to verify that the PR really fixes it. I also checked that there's no regression related to bugs fixed in #54245.

File: packages/edit-post/src/components/start-page-options/index.js (hunk 1 above)
Comment (t-hamano) [reply packages/edit-post/src/components/start-page-options/index.js]: Makes sense, updated with [8127399](https://github.com/WordPress/gutenberg/pull/55873/commits/8127399017676ff7ade6281b3e4446b20a4b4f9c) 👍

**Comment by talldan** [comment]
The code matches very closely what I also did in another PR, so that's very reassuring https://github.com/WordPress/gutenberg/pull/55117#discussion_r1351635347 😄 

Great to get this merged first, thanks! 👍

**Comment by jsnajdr** [comment]
Apologies @talldan for causing merge conflicts in your PR 🙂
