### PR TITLE
Fix converting a reusable block with nested blocks into a static block

### LINKED ISSUE #9278: Reusable Blocks: Convert to Regular Block does not preserve nested blocks
## The issue
If you save a block containing nested blocks as a Reusable Block, then it works just fine as a Reusable Block. But if you try to convert an instance of that Reusable Block to a regular block, then the resulting regular block will not contain any of the nested blocks that the Reusable Block had.

## Steps to reproduce
1. Insert a Columns block.
2. Insert some other block into the Columns block.
3. Open the ellipsis (<kbd><samp>More Options</samp></kbd>) menu and choose <kbd><samp>Add to Reusable Blocks</samp></kbd>.
4. Finish naming and saving the Reusable Block.
5. Notice that the nested blocks are saved in the Reusable Block as expected.
6. Open the ellipsis menu again and choose <kbd><samp>Convert to Regular Block</samp></kbd>.
7. Notice that the nested blocks are gone.

## Expected behavior
Reusable blocks should preserve nested blocks when an instance is converted to a regular block.

## Related issues and PRs
- #5754
- #7453
- #8375

### PR DESCRIPTION
**Pull request by noisysocks**
Fixes #9278.

The `CONVERT_BLOCK_TO_STATIC` effect needs to handle the case where the block being converted has inner blocks.

#### Testing

1. Insert a Columns block.
2. Insert some other block into the Columns block.
3. Open the ellipsis (<kbd><samp>More Options</samp></kbd>) menu and choose <kbd><samp>Add to Reusable Blocks</samp></kbd>.
4. Finish naming and saving the Reusable Block.
5. Notice that the nested blocks are saved in the Reusable Block as expected.
6. Open the ellipsis menu again and choose <kbd><samp>Convert to Regular Block</samp></kbd>.
7. The nested blocks should not have disappeared.

### CODE REVIEW

File: packages/editor/src/store/effects/reusable-blocks.js [hunk 1]
```diff
@@ -237,7 +237,11 @@ export const convertBlockToStatic = ( action, store ) => {
 	if ( referencedBlock.name === 'core/template' ) {
 		newBlocks = referencedBlock.innerBlocks.map( ( innerBlock ) => cloneBlock( innerBlock ) );
 	} else {
-		newBlocks = [ createBlock( referencedBlock.name, referencedBlock.attributes ) ];
+		newBlocks = [ createBlock(
+			referencedBlock.name,
+			referencedBlock.attributes,
+			referencedBlock.innerBlocks
```
Comment (youknowriad) [inline packages/editor/src/store/effects/reusable-blocks.js]: I think we should clone the blocks before calling this:

 - Insert the reusable block twice
 - Convert one of them to regular
 - Edit the regular blocks (notice they change in both blocks)

**Comment by slimmilkduds** [comment]
Can you please reconsider include this in 4.2? I know I’m been nagging about this issue and I promise this is the last time, whatever you decide 😁

**Review by youknowriad — APPROVED** [review]
LGTM 👍

**Comment by talldan** [comment]
@noisysocks - sorry - was a bit slow to review this. The only thing I spotted is that I can now nest a reusable block inside of itself, which causes an infinite recursion and my chrome tab ran out of memory! 

I know, I know, but I had to try it! 🤣 

Want me to create an issue about that?

**Comment by youknowriad** [comment]
@talldan I don't think it's related to this PR but I saw an issue about it (created yesterday I think)

**Comment by talldan** [comment]
Thanks, found it - https://github.com/WordPress/gutenberg/issues/11206
