### PR TITLE
Patterns: Fix pattern categories on import

### LINKED ISSUE #58901: Pattern: show "my patterns" after importing a pattern to show where it's been imported
Using GB nightly (Version 17.8.20240208), I noticed that after importing a pattern, it seems to refresh and dump me in the overall pattern view rather than showing me/placing me either in the original spot I was in or in "my patterns" so I can see where the pattern is:

https://github.com/WordPress/gutenberg/assets/26996883/1695e444-4413-4746-81b2-a3c5a65874e0

I'd expect to be shown "my patterns" or to see where it was uploaded. If we can't do that, I think we should show a "View pattern" in the snackbar notice similar to this https://github.com/WordPress/gutenberg/pull/52693 that takes you to "My patterns".

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/58901

Currently in patterns page when we import a pattern, there is an issue where we only add the pattern category if it's an already created user pattern category. This PR adds similar logic to the creation pattern flow, where we also check the core categories and create a user category with same name and slug.

This results in adding the current category in the imported pattern properly and remaining in the same view we were.

## How?
I created a private hook to get the same patterns category map with the creation flow.

## Testing Instructions
1. Importing a pattern will add the current pattern category we're viewing and create the respective user pattern category if not exists.
2. If we import a pattern while viewing `my patterns`, we stay at the same page
3. Ensure the creation of patterns flow with adding categories works as before

### CODE REVIEW

**Comment by bph** [comment]
I ran into an error message: 

Screenshot 2024-02-12 at 14 30 58
On Import on both screens, the old and the new admin list.  But the error message wasn't particularly helpful. 

Screenshot 2024-02-12 at 14 34 32

Was using 

- WordPress  6.5-alpha-57544 (via LocalWP)
- Build from the PR 
- Twenty-Twenty-Four

**Comment by ntsekouras** [comment]
>I ran into an error message:

Thanks for testing @bph! TBH I wasn't aware of the import button in the admin view, but on the other hand I made no changes there.

Regarding the error you saw in site editor, it seems weird at first sight and should't happen. It indicates the return value of `usePatternCategoriesMap` could be not set(or set properly), but it seems it's always initiated..

Can you share the pattern you're testing, because I cannot reproduce in my tests?

Additionally, can you test the same pattern in trunk and see if there are errors there too? Thanks!

**Comment by hanneslsm** [comment]
> But the error message wasn't particularly helpful.

There is a big room for UX improvement in general on error messages. Linking for visibility: https://github.com/WordPress/gutenberg/issues/53095

**Comment by bph** [comment]
>I wasn't aware of the import button in the admin view
@ntsekouras there two places to import patterns:
via Site Editor > Patterns patterns (wp-admin/site-editor.php?path=%2Fpatterns)
the 'old admin view' (wp-admin/edit.php?post_type=wp_block), and via experiment enable 

Both ran into the error message. The one from the admin view as a bit more helpful. 

The pattern 

```
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50","right":"var:preset|spacing|50"},"margin":{"top":"0","bottom":"0"}}},"backgroundColor":"accent","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-accent-background-color has-background" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--50)"><!-- wp:columns {"verticalAlignment":"center","align":"wide","style":{"spacing":{"blockGap":{"top":"var:preset|spacing|50","left":"var:preset|spacing|50"}}}} -->
<div class="wp-block-columns alignwide are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center","width":"50%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:50%"><!-- wp:heading {"metadata":{"id":"9NAGvU","bindings":{"content":{"source":"core/pattern-overrides"}}},"className":"is-style-default","fontSize":"x-large","fontFamily":"body"} -->
<h2 class="wp-block-heading is-style-default has-body-font-family has-x-large-font-size">Enhance your architectural journey with the Études Architect app.</h2>
<!-- /wp:heading -->

<!-- wp:list {"style":{"typography":{"lineHeight":"1.75"}},"className":"is-style-checkmark-list"} -->
<ul style="line-height:1.75" class="is-style-checkmark-list"><!-- wp:list-item -->
<li>Collaborate with fellow architects.</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Showcase your projects.</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Experience the world of architecture.</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"contrast","metadata":{"id":"eBKMUK","bindings":{"text":{"source":"core/pattern-overrides"},"url":{"source":"core/pattern-overrides"},"linkTarget":{"source":"core/pattern-overrides"},"rel":{"source":"cåore/pattern-overrides"}}},"style":{"border":{"radius":"25px"}},"fontSize":"medium"} -->
<div class="wp-block-button has-custom-font-size has-medium-font-size"><a class="wp-block-button__link has-contrast-background-color has-background wp-element-button" style="border-radius:25px">Download app</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","width":"50%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:50%"><!-- wp:image {"id":292,"aspectRatio":"4/3","scale":"cover","sizeSlug":"full","linkDestination":"none","metadata":{"id":"gDXyh2","bindings":{"url":{"source":"core/pattern-overrides"},"title":{"source":"core/pattern-overrides"},"alt":{"source":"core/pattern-overrides"}}},"style":{"border":{"radius":"10px"}},"className":"is-style-rounded"} -->
<figure class="wp-block-image size-full has-custom-border is-style-rounded"><img src="https://icodeforapurpose.com/wp-content/uploads/2024/02/abstract-geometric-art.webp" alt="" class="wp-image-292" style="border-radius:10px;aspect-ratio:4/3;object-fit:cover"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->
```
--- 
And importing it into trunk work as expected.

**Comment by ntsekouras** [comment]
@bph can you share the `json` file you're importing?

**Comment by bph** [comment]
[birgit-s-cta-one.json](https://github.com/WordPress/gutenberg/files/14247502/birgit-s-cta-one.json)
- Once it's imported you need to update the image in the pattern, as it points to some non-accessible location. 
Also imports without issue when using GB trunk

**Comment by ntsekouras** [comment]
@bph thank you for sharing. That's weird though.. I quickly tested the `json` file you shared and it's imported with no issues for me.. I'll take a second look tomorrow..

**Review by aaronrobertshaw — COMMENTED** [review]
It's been a while since I've been heavily involved with patterns but this is looking pretty good from what I can tell 👍 

✅ Importing a pattern adds it to the currently viewed category
✅ Stays on the `my patterns` category page when importing a pattern there
✅ Didn't spot any regressions around adding patterns and custom categories

FWIW I also tested with the pattern file @bph shared and it worked fine for me.

File: packages/edit-site/src/components/add-new-pattern/index.js [hunk 1]
```diff
@@ -97,6 +98,31 @@ export default function AddNewPattern() {
...
+			);
+			invalidateResolution( 'getUserPatternCategories' );
+			return newTerm.id;
+		} catch ( error ) {
+			if ( error.code !== 'term_exists' ) {
+				throw error;
+			}
+			return error.data.term_id;
+		}
+	}
```
Comment (glendaviesnz) [inline packages/edit-site/src/components/add-new-pattern/index.js]: Could we call the new hook `useAddPatternCategory` and have it return `createPatternCategory` and `categoryMap` so we don't have to replicate this method here and in the patterns package?

Comment (ntsekouras) [reply packages/edit-site/src/components/add-new-pattern/index.js]: Sounds good. I updated the code.

**Comment by bph** [comment]
I tested this PR again this morning, on a new installation, and it worked without fail or error messages.  

- ✅ Import pattern on clean install = first user pattern, it opened the My Pattern page. 
- ✅ Import from the Call to action category, adds the new patterns to the same category
- ✅ Import from My Pattern, stays on My Pattern after import. 

Great work! 

For now, I attribute yesterday's error messages to a corrupt local installation. It was time to retire the test site and start a new one. Or it was a corrupt download of the PR artifact. 🤷

**Review by glendaviesnz — APPROVED** [review]
Tested well for me. Thanks for sorting this @ntsekouras

**Comment by youknowriad** [comment]
Is this one meant to be backported to WP 6.5?
Also is it worth e2e testing this flow?

**Comment by ntsekouras** [comment]
>Is this one meant to be backported to WP 6.5?

Yes.  Also I'll add in my backlog to add some tests.

**Comment by youknowriad** [comment]
I just cherry-picked this PR to the more/backports-for-beta3 branch to get it included in the next release: 942cc3e2c2e
