### PR TITLE
Interactivity Router: fix back and forward navigation after refresh

### LINKED ISSUE #70500: Interactivity Router does not update content with back/forward after reload
### Description

The Interactivity client-side router does not update content when using the back/forward browser navigations after reloading a page that has been navigated to via client-side routing. The URL changes, the scroll position is restored, but the content remains the same. I'd expect either the client-side router to not activate or the content to be updated to show the correct content for the URL.

### Step-by-step reproduction instructions

Via WordPress Playground, using `core/query` enhanced pagination:

1. [Open this blueprint](https://playground.wordpress.net/?mode=seamless&blueprint-url=https%3A%2F%2Fgist.githubusercontent.com%2Fwongjn%2Fd9c3bbfdc2532d7f28eca1231b7dd3a2%2Fraw%2F6080cd65d46c32d90682f93caa796b8e1615f6f7%2Fblueprint.json)
2. On the homepage, click the next page pagination link a couple of times.
3. Right click → Reload frame (or equivalent).
4. Right click → Back (or equivalent).
5. Notice how the list of blog posts has not updated.

Via a normal installation:

1. Generate many posts, i.e. `wp post generate`.
2. Create/edit a template to display posts with pagination via the `core/query` block. Ensure *Full page reload* is **off**.
3. Go to the page that uses said template.
4. Click the next page pagination link a couple of times.
5. Reload the page.
6. Hit the back browser button.
5. Notice how the list of blog posts has not updated.

### Screenshots, screen recording, code snippet

<details>
<summary>Template code for TwentyTwenty-Five</summary>

```html
<!-- wp:template-part {"slug":"header","theme":"twentytwentyfive"} /-->

<!-- wp:group {"tagName":"main","style":{"spacing":{"margin":{"top":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} -->
<main class="wp-block-group" style="margin-top:var(--wp--preset--spacing--60)"><!-- wp:heading {"textAlign":"left","level":1} -->
<h1 class="wp-block-heading has-text-align-left">Blog</h1>
<!-- /wp:heading -->

<!-- wp:query {"queryId":0,"query":{"perPage":10,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false,"taxQuery":null,"parents":[]},"enhancedPagination":true,"align":"full","layout":{"type":"constrained","justifyContent":"center"}} -->
<div class="wp-block-query alignfull"><!-- wp:post-template {"align":"full","layout":{"type":"grid","columnCount":3}} -->
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:post-title {"isLink":true,"fontSize":"x-large"} /-->

<!-- wp:post-date {"isLink":true,"style":{"spacing":{"margin":{"top":"var:preset|spacing|40"}}},"fontSize":"small"} /--></div>
<!-- /wp:group -->
<!-- /wp:post-template -->

<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:query-no-results -->
<!-- wp:paragraph -->
<p>Sorry, but nothing was found. Please try a search with different keywords.</p>
<!-- /wp:paragraph -->
<!-- /wp:query-no-results --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"wide","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide"><!-- wp:query-pagination {"paginationArrow":"arrow","align":"wide","layout":{"type":"flex","justifyContent":"space-between"}} -->
<!-- wp:query-pagination-previous /-->

<!-- wp:query-pagination-numbers /-->

<!-- wp:query-pagination-next /-->
<!-- /wp:query-pagination --></div>
<!-- /wp:group --></div>
<!-- /wp:query --></main>
<!-- /wp:group -->

<!-- wp:template-part {"slug":"footer","theme":"twentytwentyfive"} /-->
```

</details>

### Environment info

- WordPress 6.8.1
- Chrome 137.0.7151.120, Firefox 139.0.4
- Windows 11

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by DAreRodz**
## What?

Closes https://github.com/WordPress/gutenberg/issues/70500
Supersedes https://github.com/WordPress/gutenberg/pull/75853

Fixes the Interactivity API client-side router so that browser back/forward navigation correctly updates page content after a full page reload.

## Why?

When a user navigates between pages using the client-side router (e.g., enhanced pagination in `core/query`) and then reloads the page, pressing the browser's back or forward buttons updates the URL but leaves the content stale. This happens because:

1. The router creates history entries via `history.pushState()`, which means the browser expects the app to handle `popstate` events for those entries.
2. After a full page reload, the `@wordpress/interactivity-router` module is not loaded yet (it is dynamically imported on user interaction), so nothing handles the `popstate` event and the content is never updated.

## How?

Introduces a **session ID** mechanism to detect stale history entries after a reload:

1. **`@wordpress/interactivity` runtime** (`packages/interactivity/src/utils.ts`): Generates a unique `sessionId` (`crypto.randomUUID()`) when the module is first evaluated.
2. **`@wordpress/interactivity` runtime** (`packages/interactivity/src/index.ts`):
   - Tags the current history entry with the `sessionId` via `history.replaceState()` so that all entries within the same session share the same ID.
   - Registers a `popstate` event listener that compares `window.history.state.wpInteractivityId` against the current `sessionId`. On a mismatch (i.e., the entry was created before a reload), it forces a full page reload via `window.location.reload()`.
3. **`@wordpress/interactivity-router`** (`packages/interactivity-router/src/index.ts`): Includes the `sessionId` in the state object passed to `history.pushState()` / `history.replaceState()` during client-side navigations.

This ensures:
- **Same session** (no reload in between): All history entries carry the same `sessionId`, the `popstate` handler is a no-op, and the router handles back/forward as before.
- **After a reload**: A new `sessionId` is generated. Old history entries still have the previous session's ID, so navigating to them triggers a full page reload, which lets the server render the correct content.

## Testing Instructions

1. Create several posts (e.g., `wp post generate --count=30`).
2. Add a Query Loop block with enhanced pagination enabled (ensure "Full page reload" is **off**).
3. Visit the page on the front end.
4. Click the next-page pagination link two or three times.
5. Reload the page.
6. Press the browser back button.
7. **Expected:** The page content updates to match the URL (shows the previous page of posts).
8. Press the browser forward button.
9. **Expected:** The page content updates again to match the URL.

### CODE REVIEW

File: packages/interactivity/src/index.ts [hunk 1]
```diff
@@ -105,3 +112,21 @@ registerDirectives();
 // asynchronous modules, or modules importing this module asynchronously, this
 // cannot be guaranteed.
 onDOMReady( hydrateRegions );
+
+// Tag the current history entry with the session ID so that, within the same
+// session, all entries share the same ID and back/forward works normally.
+window.history.replaceState(
+	{ ...window.history.state, wp_iapi_sessionId: sessionId },
```
Comment (luisherranz) [inline packages/interactivity/src/index.ts]: I know this is somewhat internal, but it's also exposed to the public and the term `iapi` to refer to the Interactivity API is not used anywhere else. We usually use `interactivity`. Also, the combination of camelCase and snake_case is also strange.

I'd use `wpInteractivityId` for example.

**Review by luisherranz — COMMENTED** [review]
I haven't tested it, but I've taken a first look at the code and, in principle, the approach seems good to me.

Let me know when it's ready for a full review 🙂

File: packages/interactivity/src/index.ts (hunk 1 above)
Comment (DAreRodz) [reply packages/interactivity/src/index.ts]: Yeah, I wasn't convinced of that name either. Changed in https://github.com/WordPress/gutenberg/pull/75927/commits/f20e6fa18c88e356412d1659232a71f019907a30.

File: packages/interactivity/src/index.ts [hunk 2]
```diff
@@ -105,3 +112,27 @@ registerDirectives();
...
+// When the browser fires `popstate` for a history entry that was created in a
+// different session (i.e., before a full page reload), force a reload so the
+// server can render the correct content. Without this, the URL would change but
+// the page content would remain stale because the interactivity router — which
+// handles client-side navigations — might not be loaded yet.
+//
+// The check runs inside `setTimeout` because `history.state` is not yet updated
+// when the `popstate` callback executes synchronously:
+// https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event#:~:text=Note%3A%20When,setTimeout(doSomeThing%2C%200)%3B
+window.addEventListener( 'popstate', () => {
```
Comment (DAreRodz) [inline packages/interactivity/src/index.ts]: I'm considering adding `once: true` to this event listener.

If the first `popstate` event contains the same ID, we could expect the `@wordpress/interactivity-router` module to have been loaded and to already handle the case where the page was not visited.

**Comment by DAreRodz** [comment]
@luisherranz, ready for a full review. 🙂

**Review by SantosGuillamot — APPROVED** [review]
We've reverted the `setTimeout` commit and fixed the e2e failing tests by adding a `preventDefault` to the back navigation button in the e2e tests, which was incorrect.

Approving because it looks good to me, and tests pass locally.

**Comment by scruffian** [comment]
This seems to be causing an error on my local environment:

`Uncaught TypeError: crypto.randomUUID is not a function`

I think that's because I don't run on https...

**Comment by scruffian** [comment]
Created a fix here: [Interactivity: Fix crypto.randomUUID crash in non-secure contexts](https://github.com/WordPress/gutenberg/pull/76151#top)

**Comment by luisherranz** [comment]
Good catch. Thanks for the PR, Ben!
