### PR TITLE
RichText: Avoid stale active formats when deleting the text

### LINKED ISSUE #16627: Impossible to remove link
**Describe the bug**

I tried to fully remove a link from a paragraph. I even removed a few more characters. But as soon as I started typing again, the letters are hyperlinked again.

**Expected behavior**

After fully removing the link it should not come back.

**Screenshots**

Here's a video

https://cloudup.com/cg8dDEl8VQc

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 75

**Smartphone (please complete the following information):**

**Additional context**
- WordPress 5.2.2, not Gutenberg plugin installed.

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes #16627.
Alternative to #70073. Uses `onInput` callback instead of delete event listener.

PR fixes an issue where RichText formats receive stale active formats, even when formatted text is no longer part of the value.

## Why?
See ##16627.

## Testing Instructions
1. Open a post or page.
2. Add a paragraph with text.
3. Select a section of the text and link it.
4. Fully select the linked text. Ensure that the preview popover is displayed.
5. Delete the text.
6. Confirm that the popover is no longer displayed.

### Testing Instructions for Keyboard
Same

## Screenshots or screencast 

**Before**

https://github.com/user-attachments/assets/50489abe-fa51-4a7e-960c-b66633334fb2

**After**

https://github.com/user-attachments/assets/eeb371f4-8b27-4030-8285-1a36459639eb

### CODE REVIEW

File: packages/rich-text/src/component/event-listeners/input-and-selection.js [hunk 1]
```diff
@@ -88,12 +89,18 @@ export default ( props ) => ( element ) => {
 		const currentValue = createRecord();
 		const { start, activeFormats: oldActiveFormats = [] } = record.current;
 
+		// When a non-collapsed selection is deleted (not replaced with new
+		// text), the old active formats refer to the deleted content and
+		// should not be carried forward.
+		const isDelete =
```
Comment (ntsekouras) [inline packages/rich-text/src/component/event-listeners/input-and-selection.js]: Nit: I'm wondering if we could find a better name for this, as it feels a bit ambiguous with the `delete` key. Your check handles content removal that could occur with `cut` etc, so maybe something like `shouldClearFormats` or `isContentRemoved`?

**Review by ntsekouras — APPROVED** [review]
I think that's a good fix, thanks George!

File: packages/rich-text/src/component/event-listeners/input-and-selection.js (hunk 1 above)
Comment (Mamaduka) [reply packages/rich-text/src/component/event-listeners/input-and-selection.js]: Good idea. I think `clearFormats` could be a good name.
