### PR TITLE
Block editor: async mode: enable only for blocks out of view

### LINKED ISSUE #30249: Re-render delays in Safari in nested InnerBlocks
## Description

I've encountered an issue in Safari when nested `InnerBlocks` are used.  When an inner block is selecting the currently selected block in the editor, it should re-render whenever a new block is selected. In Safari, there is a "lag" such that there is sometimes a second or two delay until one of the inner blocks receives the updated props and is forced to re-render. There is no lag in Chrome.

Hopefully this report makes sense. Please let me know if more info is needed.

## Step-by-step reproduction instructions

I've created a proof of concept block to reproduce the problem:

Code: https://gist.github.com/tlovett1/7a6ffcf994f85d41821e9469c35fdea4

## Screenshots or screen recording (optional)

Video showing the problem: https://user-images.githubusercontent.com/1844351/112491396-a6330f00-8d56-11eb-9cd5-517de03c71aa.mov

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.2.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Operating system: macOS 10.15.7

### LINKED ISSUE #30299: Parent block delayed re-render after inner block move in Safari
## Description

I've encountered an issue in Safari when inner blocks are moved.  Although the inner blocks move correctly, the parent block sometimes receives the updated inner blocks with their new ordering after a few second delay. This does not happen in Chrome.

This could be related to #30249

## Step-by-step reproduction instructions

I've created a proof of concept block to reproduce the problem:

Code: https://gist.github.com/tlovett1/2c49074bc4ed6931e914bb2bd1bf92d1

## Screenshots or screen recording (optional)

Video showing the problem: 

https://user-images.githubusercontent.com/1844351/112659737-0dba8e80-8e2b-11eb-933c-b3bb4057c0e2.mov

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.2.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Operating system: macOS 10.15.7

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #30249.
Fixes #30299.

Right now we prioritise select calls for selected blocks. This PR explores prioritising (disabling async mode) select calls for all blocks that are visible on the screen.

|Safari Before|Safari After|
|-|-|
|safari-async-before|safari-async-after|

I'd expect there to be a small performance hit for typing, but the absolute increase should be the same for both small and large posts.

I tested a large post and I didn't really notice a difference. Perhaps the first character typed felt a bit slower (when typing mode get enabled and toolbars disappear), but I'm not sure without more testing. There's a delay for the first character in `trunk` as well.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-editor/src/components/block-list/index.js [hunk 1]
```diff
@@ -86,52 +137,30 @@ function Items( {
...
-		};
-	}
-
-	const {
-		blockClientIds,
-		selectedBlockClientId,
-		multiSelectedBlockClientIds,
-		hasMultiSelection,
-	} = useSelect( selector, [ rootClientId ] );
+	const intersectingBlocks = useContext( IntersectingBlocks );
```
Comment (ellatrix) [inline packages/block-editor/src/components/block-list/index.js]: This will be a set of a small number of client IDs that are in view.

File: packages/block-editor/src/components/block-list/index.js [hunk 2]
```diff
@@ -86,52 +137,30 @@ function Items( {
...
+					key={ clientId }
+					value={ ! intersectingBlocks.has( clientId ) }
+				>
+					<BlockListBlock
+						rootClientId={ rootClientId }
+						clientId={ clientId }
+						// This prop is explicitely computed and passed down
+						// to avoid being impacted by the async mode
+						// otherwise there might be a small delay to trigger the animation.
+						index={ index }
```
Comment (ellatrix) [inline packages/block-editor/src/components/block-list/index.js]: I wonder if we still need this when all blocks in view are updated synchronously.

File: packages/block-editor/src/components/block-list/index.js [hunk 3]
```diff
@@ -52,12 +64,43 @@ export default function BlockList( { className, __experimentalLayout } ) {
...
+					const clientId = entry.target.getAttribute( 'data-block' );
+					const action = entry.isIntersecting ? 'add' : 'delete';
+					newIntersectingBlocks[ action ]( clientId );
+				}
+				return newIntersectingBlocks;
+			} );
+		}
+
+		const observer = new Observer( callback, {
+			threshold: 0.1,
```
Comment (ellatrix) [inline packages/block-editor/src/components/block-list/index.js]: We could change this to `0` as well.

File: packages/block-editor/src/components/block-list/index.js [hunk 4]
```diff
@@ -86,39 +87,60 @@ function Items( {
...
-				return (
-					<AsyncModeProvider
-						key={ clientId }
-						value={ ! isBlockInSelection }
+			{ order.map( ( clientId, index ) => (
+				<AsyncModeProvider
+					key={ clientId }
+					value={
+						! intersectingBlocks.has( clientId ) &&
+						! selectedBlocks.has( clientId )
```
Comment (ellatrix) [inline packages/block-editor/src/components/block-list/index.js]: Leaving a check for selected blocks because I see some e2e test failures that I think come from a selected block being edited that is out of view.

File: packages/block-editor/src/components/block-list/index.js [hunk 5]
```diff
@@ -86,39 +87,60 @@ function Items( {
...
+		( select ) => {
+			const {
+				getBlockOrder,
+				getSelectedBlockClientId,
+				getMultiSelectedBlockClientIds,
+				hasMultiSelection,
+			} = select( blockEditorStore );
+			return {
+				order: getBlockOrder( rootClientId ),
+				selectedBlocks: new Set(
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-list/index.js]: This is not great, it returns a new object on each subscribe, we should memoize it or avoid using a "set" and rely on existing selectors.

**Review by youknowriad — COMMENTED** [review]
this looks promising.

File: packages/block-editor/src/components/block-list/index.js (hunk 5 above)
Comment (ellatrix) [reply packages/block-editor/src/components/block-list/index.js]: Why is it a problem if a new object is returned? Are these values cached somewhere? Just trying to understand better for other places.

Comment (youknowriad) [reply packages/block-editor/src/components/block-list/index.js]: yes `useSelect` does shallow comparison of returned values and avoid rerendering the component if we get the same ones.

File: packages/block-editor/src/components/block-list/index.js [hunk 6]
```diff
@@ -105,25 +105,19 @@ function Items( {
...
 			} = select( blockEditorStore );
 			return {
 				order: getBlockOrder( rootClientId ),
-				selectedBlocks: new Set(
-					hasMultiSelection()
-						? getMultiSelectedBlockClientIds()
-						: [ getSelectedBlockClientId() ]
-				),
+				multiSelectedBlocks: getMultiSelectedBlockClientIds(),
+				selectedBlock: getSelectedBlockClientId(),
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-list/index.js]: I think you're looking for getSelectedBlockClientIds (works for both multi and simple selection)

Comment (ellatrix) [reply packages/block-editor/src/components/block-list/index.js]: Huh, I didn't know we had that. Strange that we weren't using it before here.

**Review by youknowriad — APPROVED** [review]
There are some failing tests that are worth checking. But this looks good to me.

**Comment by ellatrix** [comment]
Yeah there's a failing test that I can't figure out atm. I'll need to have a fresh look next week I think.

**Comment by ellatrix** [comment]
I think this is solid. Let's try it.
