### PR TITLE
Block editor: Self nesting and circular nesting block fix

### LINKED ISSUE #66090: Self-nested blocks causing infinite recursion and crashing the editor
### Description

With the changes in https://github.com/WordPress/gutenberg/pull/65700, self-nested or circular-nested blocks could [cause infinite recursion](https://github.com/WordPress/gutenberg/blob/27b86b2a447ebc9f1f3541c86cd2cce475744a2d/packages/block-editor/src/store/selectors.js#L1587) resulting in crashing the editor.

cc: @youknowriad 

### Step-by-step reproduction instructions

1. Register self-nested or circular-nested blocks. For example:

```js
// Self-nested block
window.wp.blocks.registerBlockType( 'test/self-nested-block', {
	title: 'Self-nested Block',
	parent: [ 'test/self-nested-block', 'core/group' ],
	save: () => {
		return '';
	}
} );

// Circular-nested blocks
window.wp.blocks.registerBlockType( 'test/self-nested-block-1', {
	title: 'Self-nested Block #1',
	parent: [ 'test/self-nested-block-2', 'core/group' ],
	save: () => {
		return '';
	}
} );

window.wp.blocks.registerBlockType( 'test/self-nested-block-2', {
	title: 'Self-nested Block #2',
	parent: [ 'test/self-nested-block-1' ],
	save: () => {
		return '';
	}
} );
```

2. Attempt to open the Inserter from the header toolbar. Note that if the problematic blocks already exist in the page content, the block editor will immediately crash after registering the blocks.

Note that if a visible parent block comes first, e.g. `[ 'core/group', 'test/self-nested-block-2' ]` instead of `[ 'test/self-nested-block-2', 'core/group' ]`, [the infinite recursion](https://github.com/WordPress/gutenberg/blob/27b86b2a447ebc9f1f3541c86cd2cce475744a2d/packages/block-editor/src/store/selectors.js#L1585-L1587) will not occur.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 6.6.2
- Gutenberg 19.4.0

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### PR DESCRIPTION
**Pull request by SH4LIN**
closes #66090

## What?

- This PR checks the current block name when determining if a block is allowed in the inserter. If the parent block name and the current block name are the same, we immediately return `false`.
- This PR also checks for circular nesting by maintaining a list of blocks that have already been checked. If circular nesting is detected, we return `false`.
- Additionally, this PR prevents the registration of a block if it is supposed to be added within itself.

## Why?

- Self nesting blocks and circular nesting block causes infinite loops.

## How?

- This PR checks the current block name when determining if a block is allowed in the inserter. If the parent block name and the current block name are the same, we immediately return `false`.
- This PR also checks for circular nesting by maintaining a list of blocks that have already been checked. If circular nesting is detected, we return `false`.
- Additionally, this PR prevents the registration of a block if it is supposed to be added within itself.

### Fixes/Covers
- https://github.com/WordPress/gutenberg/issues/66090

### CODE REVIEW

**Review by youknowriad — COMMENTED** [review]
Changes look good to me. Do you think we can add some unit tests?

File: packages/blocks/src/api/registration.js [hunk 1]
```diff
@@ -232,6 +232,20 @@ export function registerBlockType( blockNameOrMetadata, settings ) {
 		return;
 	}
 
+	if (
+		settings?.parent &&
+		Array.isArray( settings.parent ) &&
+		settings.parent.length === 1 &&
+		settings.parent[ 0 ] === name
+	) {
```
Comment (t-hamano) [inline packages/blocks/src/api/registration.js]:
```suggestion
	if ( settings?.parent?.[ 0 ] === name && settings.parent.length === 1 ) {
```

Nit: I don't have a strong opinion, but this might be simpler.

**Review by t-hamano — COMMENTED** [review]
I've confirmed that nested blocks cannot be inserted at the root level, and I've also confirmed the browser warning when registering a block that is itself a parent.

At the very least, we may need to add unit tests for registering blocks [here](https://github.com/WordPress/gutenberg/blob/0ee8ce4536a2fc57ddeef10b9ada4bf9ceb07cdd/packages/blocks/src/api/test/registration.js#L74).

File: packages/blocks/src/api/registration.js (hunk 1 above)
Comment (SH4LIN) [reply packages/blocks/src/api/registration.js]: Sure, I'll update the code and add test case

**Comment by SH4LIN** [comment]
@t-hamano @youknowriad I have updated the code LMK if any further changes are required

**Review by youknowriad — APPROVED** [review]

**Comment by youknowriad** [comment]
Thanks for your contribution :)
