### PR TITLE
Fix tiny editor preview when using Mobile or Tablet options with metaboxes enabled

### LINKED ISSUE #23404: Metaboxes shrink in-editor mobile preview pane height to un-viewable size
**Describe the bug**
When metaboxes are present, the in-editor mobile preview height shrinks down, often becoming unusable because it's so short.

**To reproduce**
1. Add some plugins that use metaboxes (e.g. CoAuthors Plus and Yoast SEO). This issue is most noticeable with Yoast SEO, as their metabox is so huge.
2. Click on Preview > Tablet or Preview > Mobile
3. Observe the preview pane is just a thin sliver.
4. Collapse the metaboxes using the little arrows. Observe the situation is better, but they are still squishing the pane somewhat.

**Expected behavior**
I think the mobile preview pane should be unnaffected by the presence of metaboxes, and should not get shorter by their presence.

**Screenshots**
Screen Shot 2020-06-23 at 1 33 06 PM
Screen Shot 2020-06-23 at 1 21 08 PM

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 8.3.0 (latest version at the time of this issue)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 83.0.4103.106

**Smartphone (please complete the following information):**
n/a

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #23404.

The issue was caused by `overflow-y: auto` being applied to the editor area, but no `min-height` being set which caused the area to collapse.

I've fixed this by making the preview area generally try to have the right dimensions for the desired devices (min-height of 768px for the mobile option, and 1024px for the Tablet option).

This does result in the metabox options being pushed down the page a bit, but I think this is ok, the user can still scroll down, and generally has to do that anyway outside of preview. When a user selects one of those preview options, they generally want to be able to see the content at the right size first and foremost.

## How has this been tested?
1. Install a plugin with lots of metaboxes (i.e. Yoast)
2. Start a new post.
3. Select the 'Mobile' preview option.
4. Observe the editor should be displayed at the correct size

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-editor/src/components/use-resize-canvas/index.js [hunk 1]
```diff
@@ -51,14 +51,17 @@ export default function useResizeCanvas( deviceType ) {
...
 			case 'Tablet':
 			case 'Mobile':
 				return {
 					width: getCanvasWidth( device ),
 					margin: marginValue() + 'px auto',
 					flexGrow: 0,
-					maxHeight: device === 'Mobile' ? '768px' : '1024px',
+					height,
+					minHeight: height,
+					maxHeight: height,
```
Comment (talldan) [inline packages/block-editor/src/components/use-resize-canvas/index.js:64]: Seems unusual that three height properties are needed, but I couldn't see another way.

Comment (talldan) [inline packages/block-editor/src/components/use-resize-canvas/index.js:64]: Seems unusual that three height properties are needed, but I couldn't see another way.

**Review by tellthemachines — APPROVED** [review]
Tested across browsers, with and without metaboxes, and LGTM.
