### PR TITLE
Site Editor: Fix navigation on mobile web

### LINKED ISSUE #58044: Regression regarding layout in the Site Editor
After #57938 was merged, there seem to be some layout breakdowns in the site editor. This issue summarizes the problems I discovered.

> [!NOTE]
> The following issue was discovered with the "New admin view" experimental flag **enabled**. There may be other issues if this experimental flag is turned off. One of them is attempted to be resolved in #58039.

### Templates are not displayed in the mobile layout

In fact, the expected screenshot itself doesn't seem right. I think the preview area itself needs to be hidden in the mobile layout.

| Expected | Actual (trunk) |
|--------|--------|
| image | image| 

### Canvas area and data view area overlap

You will see this issue when the viewport width is approximately between 800px and 1100px.

| Expected | Actual (trunk) |
|--------|--------|
| image | image |

<details><summary>Fixed</summary>

### The headers and the footer are not fixed on Templates, Template Parts, and Pattern pages

- #58077

| Expected | Actual (trunk) |
|--------|--------|
| image | image |
| image | image | 

### Top right and bottom right corners are not rounded

- #58077

Presumably, this can only be reproduced in the Chrome browser on Windows OS. It happens on All Templates, Template Parts, and Pattern pages.

| Expected | Actual (trunk) |
|--------|--------|
| expected | actual | 

### Extra space on top and right side

- #58077

| Expected | Actual (trunk) |
|--------|--------|
| image | image

### Pattern padding

https://github.com/WordPress/gutenberg/pull/58139 stabilizes the Patterns page with DataViews, so this issue effectively no longer needs to be fixed.

Disable the data views experiment to see this:

With the margin added to `.edit-site-layout__area` the vertical stroke on the left doesn't quite reach the top/bottom of the viewport, and the pattern thumbnails are prematurely clipped.

</details>

### PR DESCRIPTION
**Pull request by youknowriad**
closes #58044 

## What?

This address the biggest outstanding issues when it comes to mobile web in the site editor. While also keeping things simple by introducing a new "mobile" area in the router.

This PR makes the assumption that on mobile, there's not multiple areas to render pages like desktop (sidebar, preview, content), there's only a single area, so each URL should define what to render on the mobile area in the router.js.

I've made some decisions here:

 - I hid "manage all pages" like we do for templates and template parts
 - For patterns, I remove the sidebar filtering because I didn't want to introduce specific implementations in the layout for a given page.

## Testing Instructions

1- Open the site editor on mobile web (small viewport)
2- Navigate to all the pages and check that everything is correct.

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

> I hid "manage all pages" like we do for templates and template parts
> For patterns, I remove the sidebar filtering because I didn't want to introduce specific implementations in the layout for a given page.

At this point, I also agree with this decision. In the future, as reported in #49769, I would be happy if we could also publish the "Manage all XXX" menu in the mobile viewport.

I tested this PR, and when I click on the pattern menu, the pattern category appears only for a moment, and then the Dataview appears.

https://github.com/WordPress/gutenberg/assets/54422211/5a09bebf-2b97-4197-924c-f16bd01c8b1b

**Comment by youknowriad** [comment]
> At this point, I also agree with this decision. In the future, as reported in https://github.com/WordPress/gutenberg/issues/49769, I would be happy if we could also publish the "Manage all XXX" menu in the mobile viewport.

When that becomes default, we'll have to address it indeed. But I think the solution for it is probably to use the "canvas" in the URL for mobile.

**Comment by youknowriad** [comment]
> I tested this PR, and when I click on the pattern menu, the pattern category appears only for a moment, and then the Dataview appears.

I pushed a commit that make this less visible (basically shows nothing for a millisecond). This can't be solved entirely until we actually make the "sidebar" part of the routing (get rid of the Navigator component or make it controlled). It's the result of the synchronization between the internal path of the "navigator" and the url. so there's a small delay when the two are not synced which gives this result.

File: packages/edit-site/src/components/layout/index.js [hunk 1]
```diff
@@ -251,47 +251,64 @@ export default function Layout() {
...
-									} }
-									className="edit-site-layout__sidebar"
-								>
-									<Sidebar />
-								</motion.div>
-							) }
-						</AnimatePresence>
-					</NavigableRegion>
+					{ ( ! isMobileViewport ||
+						( isMobileViewport && ! areas.mobile ) ) && (
```
Comment (ntsekouras) [inline packages/edit-site/src/components/layout/index.js:255]: Based on the above comment, shouldn't we render `NavigableRegion`?

**Comment by t-hamano** [comment]
When I click the Edit button on the Styles page, the canvas view is not displayed. This problem does not occur with trunk. Maybe we need to adjust the conditional somewhere.


https://github.com/WordPress/gutenberg/assets/54422211/642cc6fd-a29e-4c61-bb44-bc4f01493366

**Review by ntsekouras — APPROVED** [review]
Thanks for the PR Riad! Besides my comment about `NavigableRegion`, this looks good. 

This is a tough one and while not perfect, I think it's pros outweight the cons. I had also explored this a bit by adding a `sidebar` area instead of your `mobile` area, but thought it added way more complexity than your suggestion.

I'd say this is an improvement right now for mobile and when we implement the sidebar as part of the routing, we'll have a much improved experience.

**Comment by youknowriad** [comment]
I don't think we need a region because the regions are defined by the `Page` component within these. I think this is probably not idea, for me I don't understand why the label of the region depend on the title of the page but that's for some other PR/refactoring. I think ideally the regions are defined top level (with each area) but right now, the ones for "content", "preview" and "mobile" are left to be rendered within the areas.

**Comment by t-hamano** [comment]
Thanks for the update! I confirmed that the canvas view is displayed when I click the Edit button on the Styles page.

This code is a bit complicated for me, but I agree that this PR is a solid improvement for the moment.
