### PR TITLE
DataViews: Fix pagination

### LINKED ISSUE #73129: DataViews: Regression in DataViews pagination, On next page it does not increment count, instead it's concatenation
### Description

- On DataViews, clicking next page after (page 2), it is working as concatenation instead of increment.
- Discovered while testing - https://github.com/WordPress/gutenberg/issues/73103
- Initially, the view.page in data-views pagination is number, but when on clicking next page, it changes the view.page type to string, which makes it to concatenate instead of addition.

### Step-by-step reproduction instructions

1. Create pages with more than 100.
2. Go to Editor -> Pages.
3. Click Next page, page 2 will be shown.
4. Click Next page again, instead of `3` it will take to `21` page.
5. Check network tab to confirm payload.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/c9bcc22b-efe6-4dc4-8f38-2b59b97c3226

view.page type as shown in below screencast.

https://github.com/user-attachments/assets/0daba5cb-a82e-413a-91e7-a81f97c0db45

### Environment info

- WP: 6.8.3
- GB: 22.0

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/73129

From the issue: 

> On DataViews, clicking next page after (page 2), it is working as concatenation instead of increment.

> Initially, the view.page in data-views pagination is number, but when on clicking next page, it changes the view.page type to string, which makes it to concatenate instead of addition.

## Testing Instructions
1. DataViews pagination in site editor (pages, templates, patterns) should work as expected by navigating to next and previous pages

### CODE REVIEW

File: packages/views/src/use-view.ts
Comment (hbhalodia) [inline packages/views/src/use-view.ts:87]: Hi @ntsekouras, Do we need to typecast this here as well? on updating the view.

Comment (ntsekouras) [reply packages/views/src/use-view.ts:87]: No, because it's converted to `string` for the URL.

Comment (hbhalodia) [reply packages/views/src/use-view.ts:87]: Ah got it, we are constructing URL param, we are not getting the value from param. 👍

File: packages/edit-site/src/components/page-patterns/index.js [hunk 1]
```diff
@@ -106,7 +106,7 @@ export default function DataviewsPatterns() {
 		slug: categoryId,
 		defaultView: DEFAULT_VIEW,
 		queryParams: {
-			page: Number( query.pageNumber ?? 1 ),
```
Comment (oandregal) [inline packages/edit-site/src/components/page-patterns/index.js:109]: So, the issue affected any page that used `useView` but didn't convert strings to numbers. It'd be pages, templates, and the post list experiment.

**Review by oandregal — APPROVED** [review]
Thanks @ntsekouras for preparing a fix so promptly and @hbhalodia for raising it (and also preparing a fix!).

**Comment by oandregal** [comment]
@ntsekouras it'd be good to follow-up with an e2e test to cover this. Actually, having more of the basic interactions covered.

**Review by hbhalodia — APPROVED** [review]

File: packages/views/src/use-view.ts [hunk 2]
```diff
@@ -66,7 +66,7 @@ export function useView( config: ViewConfig ): UseViewReturn {
 	const { set } = useDispatch( preferencesStore );
 
 	const baseView: View = persistedView ?? defaultView;
-	const page = queryParams?.page ?? baseView.page ?? 1;
+	const page = Number( queryParams?.page ?? baseView.page ?? 1 );
```
Comment (youknowriad) [inline packages/views/src/use-view.ts:69]: For me the issue should be fixed where we read the value from the url instead of here. But I guess this is defensive coding.
