### PR TITLE
Block Variation Picker: adds support to declarated icon with src

### LINKED ISSUE #46372: Block Variation Picker doesn't support icons registered with the src attribute.
### Description

The component [BlockVariationPicker](https://github.com/WordPress/gutenberg/blob/84386b262c6bd658fba3d6eb681a54ced0fd65da/packages/block-editor/src/components/block-variation-picker/index.js) doesn't support icons with the src attribute.

### Step-by-step reproduction instructions

1. Create a Query Loop variation that has a declared icon with src (you can use [this code](https://gist.github.com/gigitux/cf0014e4c144af2a2c0043b615f93435)).
2. Add the Query Loop block.
3. Click `Start Blank`.
5. The block crashes.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/4463174/206240656-ab8ba6a7-34b4-4f33-8b0b-b72686006413.mp4

### Environment info

- WordPress 6.1
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by gigitux**
## What?
This PR adds the support of a declared icon with src to the `Block Variation Picker`.
## Why?
This avoids the crash of the `Block Variation Picker` when a variation has a declared icon with src. Fixes #46372.

## Testing Instructions
1. Create a Query Loop variation that has a declared icon with src (you can use [this code](https://gist.github.com/gigitux/cf0014e4c144af2a2c0043b615f93435)).
2. Add the Query Loop block.
3. Click `Start Blank`.
4. Be sure the `Block Variation Picker` doesn't crash.

## Screenshots or screencast 
https://user-images.githubusercontent.com/4463174/206242543-2fd0acbe-fef7-43df-8b14-ade8a85433ca.mp4

### CODE REVIEW

File: packages/block-editor/src/components/block-variation-picker/index.js [hunk 1]
```diff
@@ -43,7 +43,7 @@ function BlockVariationPicker( {
 					<li key={ variation.name }>
 						<Button
 							variant="secondary"
-							icon={ variation.icon }
+							icon={ variation.icon.src || variation.icon }
```
Comment (jorgefilipecosta) [inline packages/block-editor/src/components/block-variation-picker/index.js]: Most code guards against icon being undefined using "variation.icon && variation.icon.src ? variation.icon.src : variation.icon". I guess we can follow a similar approach but other that the change looks good and can be merged after the update.

**Review by jorgefilipecosta — APPROVED** [review]

**Comment by gigitux** [comment]
@jorgefilipecosta Thanks for the review! I updated the check!

**Comment by Aljullu** [comment]
@gigitux given that this PR was approved and you did the change, should we go ahead and merge?

**Comment by gigitux** [comment]
> @gigitux given that this PR was approved and you did the change, should we go ahead and merge?

For me, it makes sense. Unfortunately, I don't have permission to merge the PR (I think that @ellatrix must approve the PR).  

cc @jorgefilipecosta
