### PR TITLE
Fix document title html entities

### LINKED ISSUE #28558: HTML entities in post_type labels get escaped in edit post plugin sidebar tab title
## Description
The Gutenberg editor does not properly display HTML entities (e.g. `&shy;`)  which are contained in a custom post_type's label.
In fact it escapes the HTML entities (_properly)_, causing the title to actually contain the string "`&shy;`" in some places.

This is actually the desired behavior. When rendering the label/title it should be treated as a string rather than HTML, to prevent XSS. Unfortunately this makes it also incompatible with HTML entities.

I'm not sure if it's a bad idea to include HTML entities in the post_type's label in the first place. Anyways, WordPress displays them properly.

I located the issue in the [`settings-header` component](https://github.com/WordPress/gutenberg/blob/master/packages/edit-post/src/components/sidebar/settings-header/index.js#L55) of the sidebar to be the root cause here. I also found a [possible workaround](https://github.com/mdavid626/react-html-entities-example) for React which would replace known HTML entities with Unicode characters like [`\u00AD` (Soft hyphen)](https://unicode-table.com/en/00AD/).

## Step-by-step reproduction instructions
1. Create a new theme or plugin
2. Add a custom post_type and assign it a label with manual hyphenation (see [code example](##code-snippet) below)
3. Navigate to the WordPress backend and verify that the label/title of your post type is *properly* displayed on the left side menu. 
image
4. Create or edit a post of that post_type with Gutenberg. If not already done, open the settings sidebar on the right and verify the post_type's label/title is not properly displayed in the tab.
image

## Expected behaviour
Gutenberg displays the label properly, making the "`&shy;`" invisible, because the whole label fits into the tab's title.

## Actual behaviour
See screenshot above.

## Code snippet
```PHP
// function.php (if it's a theme)
add_action( 'init', function() {
	register_post_type(
		'free_representatives',
		array(
			'label' => 'free represen&shy;tatives',
			'public' => true,
			'show_in_rest' => true,
		)
	);
});
```

## WordPress information
- WordPress version: 5.6
- Gutenberg version: Default shipped with WordPress version 5.6
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: any
- Browser: Firefox

### PR DESCRIPTION
**Pull request by talldan**
## What?
Fixes #28558

When registering a postType, devs might add html entities in the postType label. These were being rendered verbatim in two places in the UI - the document tab title and the block breadcrumbs. The 'Address Bar' area also shows the postType label, but already handles decoding the entities.

## How?
This PR uses decodeEntities to convert any entities.

## Testing Instructions
1. Add a small snippet of code to register a custom post type:
```php
add_action( 'init', function() {
	register_post_type(
		'shy_guy,
		array(
			'label' => '&shy; guy',
			'public' => true,
			'show_in_rest' => true,
		)
	);
});
```
2. Create a new post of the custom post type
3. Open the Inspector sidebar

Expected: The post title doesn't render HTML entities in the Block Breadcrumbs (in the editor footer) or the document tab title (in the inspector)
In trunk: `&shy;` is rendered in the text

4. Now change the `label` value for the post type to an empty string `''`.
5. Reload the editor.
6. Check that the fallback to the default value of 'Document' works in both places.

#### Before
Screenshot 2025-12-16 at 12 52 16 pm
<br>
Screenshot 2025-12-16 at 12 52 21 pm

#### After
Screenshot 2025-12-16 at 12 51 42 pm
<br>
Screenshot 2025-12-16 at 12 51 51 pm

### CODE REVIEW

File: packages/editor/src/components/editor-interface/index.js [hunk 1]
```diff
@@ -87,9 +87,7 @@ export default function EditorInterface( {
 			isDistractionFree: get( 'core', 'distractionFree' ),
 			isPreviewMode: editorSettings.isPreviewMode,
 			showBlockBreadcrumbs: get( 'core', 'showBlockBreadcrumbs' ),
-			documentLabel:
-				// translators: Default label for the Document in the Block Breadcrumb.
-				postTypeLabel || _x( 'Document', 'noun, breadcrumb' ),
```
Comment (talldan) [inline packages/editor/src/components/editor-interface/index.js:92]: This fallback to 'Document' was duplicating what the `BlockBreadcrumb` component already does, so I've removed it.

File: packages/block-editor/src/components/block-breadcrumb/index.js [hunk 2]
```diff
@@ -38,7 +38,9 @@ function BlockBreadcrumb( { rootLabelText } ) {
 			hasSelection: !! getSelectionStart().clientId,
 		};
 	}, [] );
-	const rootLabel = rootLabelText || __( 'Document' );
+
+	// translators: Default label for the Document in the Block Breadcrumb.
+	const rootLabel = rootLabelText || _x( 'Document', 'noun, breadcrumb' );
```
Comment (talldan) [inline packages/block-editor/src/components/block-breadcrumb/index.js:43]: Updated this to match the fallback translation used elsewhere.

File: packages/editor/src/components/editor-interface/index.js [hunk 3]
```diff
@@ -192,7 +190,9 @@ export default function EditorInterface( {
 				isLargeViewport &&
 				showBlockBreadcrumbs &&
 				mode === 'visual' && (
-					<BlockBreadcrumb rootLabelText={ documentLabel } />
+					<BlockBreadcrumb
+						rootLabelText={ decodeEntities( postTypeLabel ) }
+					/>
```
Comment (ramonjd) [inline packages/editor/src/components/editor-interface/index.js]: Should editor-interface/index.js explicitly check for postTypeLabel before calling decodeEntities to match sidebar/header.js?

**Review by ramonjd — APPROVED** [review]
Nice work, thanks for fixing this old bug!

LGTM in the sidebar and doc breadcrumb.

Here's the sidebar:

| Before  | After |
| ------------- | ------------- |
| Screenshot 2025-12-16 at 5 16 51 pm | Screenshot 2025-12-16 at 5 15 58 pm  |

Optional, I noticed that the sidebar title's button element has `white-space: nowrap;`, which keeps the title on one line despite the soft hyphen. The breadcrumb button (`.block-editor-block-breadcrumb__button`) doesn't have `white-space: nowrap;`:

Screenshot 2025-12-16 at 5 31 26 pm


I guess this can be seen in two ways:

- `white-space: nowrap;` prevents the soft hyphen from working, OR
- `white-space: nowrap;` enforces a one-line rule.

Not sure which is preferred, but since it's on trunk and an edge case, I don't think folks are going to lose any sleep over it.

File: packages/editor/src/components/editor-interface/index.js [hunk 4]
```diff
@@ -192,7 +190,9 @@ export default function EditorInterface( {
 				isLargeViewport &&
 				showBlockBreadcrumbs &&
 				mode === 'visual' && (
-					<BlockBreadcrumb rootLabelText={ documentLabel } />
+					<BlockBreadcrumb
+						rootLabelText={ decodeEntities( postTypeLabel ) }
```
Comment (Mamaduka) [inline packages/editor/src/components/editor-interface/index.js]: Wouldn't it make sense to decode this label in the `BlockBreadcrumb` component and before the actual value is rendered?

My thinking here is similar to escaping data: you want to escape when you echo, not before. Ref: https://developer.wordpress.org/apis/security/escaping/#escaping-functions

Comment (talldan) [reply packages/editor/src/components/editor-interface/index.js]: Because `BlockBreadcrumb` is a general purpose component that's exported, someone might be using it with a `rootLabelText` value that doesn't need to be decoded, so my thinking is that it's best not to always decode the value.

File: packages/editor/src/components/editor-interface/index.js (hunk 3 above)
Comment (talldan) [reply packages/editor/src/components/editor-interface/index.js]: 👍 I've pushed some code to do that.

`decodeEntities` does handle null or undefined values, but I guess it makes no sense to call it with nothing.

File: packages/editor/src/components/editor-interface/index.js (hunk 4 above)
Comment (Mamaduka) [reply packages/editor/src/components/editor-interface/index.js]: Good point!

**Comment by talldan** [comment]
> The breadcrumb button (.block-editor-block-breadcrumb__button) doesn't have white-space: nowrap;:

Might as well fix this too, pushed a `white-space: nowrap` fix.
