### PR TITLE
BorderControl: Fix focus styling

### LINKED ISSUE #40897: Border Tools: Inconsistent focus borders
The Border tool displays `:focus` in ways that don't match other controls in the Inspector sidebar:

image

I'd expect the Border tools to use a similar treatment to other inputs and controls — thicker borders, avoiding doubled borders, etc — something like this:

image

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Fixes: #40897

- https://github.com/WordPress/gutenberg/issues/40897

## What?

Makes the inner component focus styles and border radii consistent.

## Why?

The small details matter.

## How?

Updated focus styles and border radii including RTL styling.

###### UnitSelect
- Fixed RTL border radii
- Fixed inconsistent focus box-shadow and border

###### BorderControlDropdown
- Fixed z-index causing focus styles to be clipped

###### InputControl's BackdropUI
- Fixed RTL border radii
- Fixed focus box-shadow

## Testing Instructions

1. Start up Storybook & visit [BorderControl page](http://localhost:50240/?path=/story/components-experimental-bordercontrol--default)
    - `npm run storybook:dev`
2. Optional: Zoom the page in as far as possible to more clearly see styling changes.
3. Select the input within the control then tab/shift-tab through the parts of the control, ensuring correct border radii and that the outline looks correct
4. Switch to RTL mode and repeat the process paying close attention to the border radii

## Screenshots or screencast 

https://user-images.githubusercontent.com/60436221/167525428-6dff79c0-6895-4b17-875a-36e18fe803d2.mp4

### CODE REVIEW

File: packages/components/src/border-control/styles.ts [hunk 1]
```diff
@@ -154,12 +176,22 @@ export const borderWidthControl = () => css`
...
 	/* See packages/components/src/unit-control/styles/unit-control-styles.ts */
 	&&& input {
 		${ rtl( { paddingRight: 0 } )() }
+
+		/*
+		 * Allows the input control's backdrop to overlay its box shadow over
+		 * the BorderControl's wrapper border.
+		 */
+		&:focus ~ ${ BackdropUI } {
+			box-shadow: 0 0 0 ${ CONFIG.borderWidthFocus }
```
Comment (andrewserong) [inline packages/components/src/border-control/styles.ts]: Should these box-shadows be set to inset instead, for consistency with the color indicator?

image

From clicking around in the editor sidebar, it looks like most of the other input fields currently use inset for the focus styling.

**Review by andrewserong — COMMENTED** [review]
Nice work putting up these PRs to fine-tune the UI @aaronrobertshaw! The border radii are looking good to me, but the border width looks slightly inconsistent to me compared to similar components (e.g. `InputControl`) where the focus style doesn't change the overall size of the field — I was wondering if setting `inset` will fix it (and / or if the border-width needs to be slightly heavier?)

File: packages/components/src/border-control/styles.ts (hunk 1 above)
Comment (aaronrobertshaw) [reply packages/components/src/border-control/styles.ts]: > Should these box-shadows be set to inset instead 

They weren't inset so that the box-shadow overlayed the border from the overall `BorderControl`. That is, no "double border" as mentioned in the original issue. 

I chose that as opposed to removing borders from the wrapper and managing additional partial borders and edge cases for all the internal components.

> for consistency with the color indicator?

The color indicator's focus style should already be consistent i.e. it isn't `inset` either. It appears from that screenshot that you are highlighting the dropdown button's hover style?

Screen Shot 2022-05-10 at 1 06 30 pm

From the Storybook, here's how it looks to me when I toggle on focus for both the button and the input field.

Screen Shot 2022-05-10 at 1 04 02 pm

I did wonder about making the hover style match the focus but thought I'd see what came up there in review. So that is still something I could address in a follow-up.

> From clicking around in the editor sidebar, it looks like most of the other input fields currently use inset for the focus styling.

I might need to re-test via the block editor and see if any style conflicts are occurring there. Thanks!

Comment (andrewserong) [reply packages/components/src/border-control/styles.ts]: Thanks for the extra context!

> It appears from that screenshot that you are highlighting the dropdown button's hover style?

Ah, yes, I was, that's it. A better comparison might be `InputControl` / `UnitControl` in fields that we render near the Border controls, (e.g. Block Spacing or Border Radius):

| Border focused | Border Radius focused |
| --- | --- |
| image | image |

I _think_ the latter's style comes from the following line:
https://github.com/WordPress/gutenberg/blob/be92ce8d06f1e282e9cfb401e43790d60ef8f137/packages/components/src/input-control/styles/input-control-styles.tsx#L301

With the UnitControl in BorderRadius, it looks like that one currently has a thicker "looking" inset style that avoids the double-border and looks a bit closer to the design in #40897 to my eyes.

For InputControl, it appears it currently achieves a 2px effective border in [backdropFocusedStyles](https://github.com/WordPress/gutenberg/blob/be92ce8d06f1e282e9cfb401e43790d60ef8f137/packages/components/src/input-control/styles/input-control-styles.tsx#L292) by doing the following:

* Sets a `1px` border with the color set to the border focus color when the component is focused
* Sets a `1px` inset box shadow with the color set to the border focus color

That way it winds up looking effectively like a 2px border, without increasing the apparent size of the element. Not to say that we need to do that necessarily for this component, too, but just thought I'd add that in here in case it helps!

> I did wonder about making the hover style match the focus but thought I'd see what came up there in review. So that is still something I could address in a follow-up.

Tackling other inconsistencies in follow-ups sounds good to me! I'm sure @shaunandrews will have a better idea of some of the trade-offs of these fine-tuning decisions than me, also 😀

Happy to do more testing, too 🙂

Comment (aaronrobertshaw) [reply packages/components/src/border-control/styles.ts]: I've taken another look at the block editor and controls within the sidebar. I'm struggling to find any consistency as to whether the controls are concerned with focus styling not extending the bounds of the non-focused control dimensions.

#### Without inset box-shadow

- Toggle controls
- Buttons (General buttons, menu item checkboxes, tabs, dropdown buttons, panel headers)
- Font Size Picker (ToggleGroup view)
- CustomSelectControl
- TextControl (both input and textarea)
- Links
- CheckboxControl
- RangeControl drag handles

#### With inset box-shadow

- InputControl
- UnitControl
- SelectControl

Given the widespread use of UnitControl, that sort of makes the balance more even. 

As the current approach will address the "double borders" issue, I'm inclined to proceed with it, perhaps just with a tweak to make the border control dropdown button's hover style match its focus style.

What do you think @andrewserong?

Comment (aaronrobertshaw) [reply packages/components/src/border-control/styles.ts]: Thank you for the extra digging and testing.

> For InputControl, it appears it currently achieves a 2px effective border in [backdropFocusedStyles](https://github.com/WordPress/gutenberg/blob/be92ce8d06f1e282e9cfb401e43790d60ef8f137/packages/components/src/input-control/styles/input-control-styles.tsx#L292) by doing the following:

I will take another look at getting the resulting width consistent (i.e. `2px`). In my testing the box-shadow sets a width of `COLORS.ui.borderFocus` which shows as `1.5px` and renders as `2px`?

> Sets a 1px border with the color set to the border focus color when the component is focused

While making these changes this appeared to make the resulting border/outline/shadow "too" thick and from memory the button component didn't add the extra border. I'm not sure which is the "correct" or preferred option.

As for the `inset` suggestion, I still believe this will make any box shadow we add begin at the controls edge and go inwards thus leaving the border from the `BorderControl`'s wrapper around the dropdown and `UnitControl` outside the box shadow. Hence the "double border".

The only way around that I saw was reworking the styling for all the inner components to the `BorderControl`.

Comment (andrewserong) [reply packages/components/src/border-control/styles.ts]: Very interesting that there isn't much consistency across the components, there, thanks for reviewing all those.

> As the current approach will address the "double borders" issue, I'm inclined to proceed with it, perhaps just with a tweak to make the border control dropdown button's hover style match its focus style.

Yes, that sounds good to me, particularly with the matching hover + focus style tweak for the dropdown button. And with the shape of this PR, it looks like it should be pretty straightforward to adjust again in a follow-up if need be!

Comment (andrewserong) [reply packages/components/src/border-control/styles.ts]: Likewise, thanks for doing more digging!

> While making these changes this appeared to make the resulting border/outline/shadow "too" thick and from memory the button component didn't add the extra border. 

Sounds like it might be easier to go with your current approach then, particularly if it looks like it's going to be complex to get it working right with an `inset` approach.

Comment (aaronrobertshaw) [reply packages/components/src/border-control/styles.ts]: I took a run at refactoring the styles here to allow the `inset` focus box shadows and didn't hit as many edge cases as I thought. It did require a small negative margin hack to affect border collapsing but other than that came up well.

I'll resolve this conversation but wait for a final review.

**Comment by aaronrobertshaw** [comment]
This PR now reworks the application of borders to the `BorderControl`'s inner components. This allows for simpler focus styles and an `inset` box shadow for greater consistency with the common `UnitControl`.

https://user-images.githubusercontent.com/60436221/167591854-20675a91-6f6f-41ba-a3e2-7c2137d2690e.mp4

**Comment by shaunandrews** [comment]
This looks great! Thanks for tackling it. I did notice that the left border radii are different from the rest:

image

**Comment by aaronrobertshaw** [comment]
>  I did notice that the left border radii are different from the rest:

Nice catch. Thank you.

I missed tweaking the button's border radii after refactoring the styling in https://github.com/WordPress/gutenberg/pull/40951/commits/ec58f46a5f38c411d834a0b2900f3be21c821f2e. That's been fixed now.

**Review by andrewserong — APPROVED** [review]
Excellent, thanks for reworking this @aaronrobertshaw, that's looking really solid now! ✨

✅ Works nicely in the editor and the focus style is consistent with the nearby UnitControls
✅ Tested in Storybook that it looks good in RTL mode 



LGTM! 🚀
