### PR TITLE
Writing flow: fix paste for input fields

### LINKED ISSUE #61377: Block Editor: Unable to paste text into text field inside block
### Description

Some blocks have text fields. For example, Embed block, Shortcode block, etc. Pasting text into the text field of these blocks deletes the blocks and creates a Paragraph block in their place.

I think this can happen with any block that has a text field, not just the core block.

This problem does not seem to occur in WP6.5.

### Step-by-step reproduction instructions

- Insert Shortcode block, Embed block, etc.
- Copy text from elsewhere and paste it into the text field.
- It should be converted to a Paragraph block.

### Expected Behaviour (WP6.5)

https://github.com/WordPress/gutenberg/assets/54422211/dc5764ea-2626-4583-a7b4-e1dbdaa6eb29

### Actual Behaviour (Latest Gutenberg)

https://github.com/WordPress/gutenberg/assets/54422211/df22bb58-385f-49c1-bca4-1def4b569952

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Fixes #61377. I don't remember exactly why I removed this check for the paste event.

## How?

Turns out I shouldn't have removed this condition for the paste event. We still don't want to handle paste for input and textarea elements, but we do want to override it for `contenteditable`.

### CODE REVIEW

File: packages/block-editor/src/components/writing-flow/use-clipboard-handler.js [hunk 1]
```diff
@@ -72,22 +91,6 @@ export default function useClipboardHandler() {
...
 			if ( event.type === 'copy' || event.type === 'cut' ) {
-				if ( ! hasMultiSelection() ) {
-					const { target } = event;
-					const { ownerDocument } = target;
-					// If copying, only consider actual text selection as selection.
-					// Otherwise, any focus on an input field is considered.
-					const hasSelection =
-						event.type === 'copy' || event.type === 'cut'
-							? documentHasUncollapsedSelection( ownerDocument )
-							: documentHasSelection( ownerDocument );
```
Comment (ellatrix) [inline packages/block-editor/src/components/writing-flow/use-clipboard-handler.js:83]: I changed this line to `documentHasSelection( ownerDocument ) &&  ! ownerDocument.activeElement.isContentEditable` while also running it for the paste event as we did before #54543.

**Review by Mamaduka — COMMENTED** [review]
Thanks, @ellatrix!

The fix works when manually testing the changes. The e2e tests are failing due to pasting not working; nothing gets pasted into the input field.

The embed block e2e test isn't a great place to test this regression. Embeddable URLs in paragraphs are auto-embedded. Let's add a separate test in writing flow specs for the RSS block.

```js
// See: https://github.com/WordPress/gutenberg/pull/61389.
	test( 'should retain native copy/paste behavior for input fields', async ( {
		editor,
		pageUtils,
	} ) => {
		await editor.insertBlock( { name: 'core/rss' } );
		pageUtils.setClipboardData( {
			plainText: 'https://developer.wordpress.org/news/feed/',
		} );
		await pageUtils.pressKeys( 'primary+v' );

		await expect.poll( editor.getBlocks ).toMatchObject( [
			{
				name: 'core/rss',
				attributes: {
					feedURL: 'https://developer.wordpress.org/news/feed/',
				},
			},
		] );
	} );
```

P.S. It seems your local trunk is a little behind. I had to rebase so I could switch between branches.

File: test/e2e/specs/editor/various/embedding.spec.js [hunk 2]
```diff
@@ -301,10 +305,10 @@ class EmbedUtils {
...
 		await test.step( `Inserting embed ${ url }`, async () => {
 			await this.#editor.insertBlock( { name: 'core/embed' } );
-			await this.#editor.canvas
-				.getByRole( 'textbox', { name: 'Embed URL' } )
-				.last()
-				.fill( url );
+			// Do not use `fill` here, it's not how the user interacts with the
+			// block.
+			this.#pageUtils.setClipboardData( { plainText: url } );
+			await this.#pageUtils.pressKeys( 'primary+v' );
```
Comment (Mamaduka) [inline test/e2e/specs/editor/various/embedding.spec.js]: @kevin940726 reminded me that this currently doesn't work on regular elements. See https://github.com/WordPress/gutenberg/pull/55030.

Comment (ellatrix) [reply test/e2e/specs/editor/various/embedding.spec.js]: Hm, interesting. I fixed it a bit differently here: 3bed7b6ff4c57cb0032f9333fafa27533e790c29

Comment (Mamaduka) [reply test/e2e/specs/editor/various/embedding.spec.js]: @kevin940726, do you mind having a look?

Comment (kevin940726) [reply test/e2e/specs/editor/various/embedding.spec.js]: I'm afraid it's not that simple. It's a cross-browser and cross-os compatibility issue too. PR #55030 should work fine but it's too complicated to review. I haven't had the time to refactor it to a simpler form. I think it's okay to omit this change and just add the `test.skip` and a comment for now.

Comment (ellatrix) [reply test/e2e/specs/editor/various/embedding.spec.js]: Why skip? It actually tests a regression? Could you elaborate on why it's not that simple? Currently all our copy/paste tests are emulated and we manually fill in data, so how is this different?

This is a pretty bad regression, so we should get at least the fix in asap.

Comment (kevin940726) [reply test/e2e/specs/editor/various/embedding.spec.js]: Playwright doesn't handle native copy/paste events nicely at the moment. There are subtle differences between different browsers (chromium, firefox, webkit), and different OSes (linux, mac, windows). What makes this even more complicated is that sometimes we have to emulate it by manually dispatching events, but some other times we have to use the native events. A proper "fix" might be maintaining a table of these factors and keeping them updated as we update Playwright or our OSes.

I totally agree we should get the fix in. However, the changes in the e2e utils might not work perfectly in all cases. What I'm suggesting is omitting the changes in e2e utils and adding an e2e test marked as `test.skip` so that we can cover this case while refactoring #55030.

I'm not entirely opposed to merging the e2e utils changes either, just that we might have to refactor it again sometimes. And I personally prefer to do that at once to avoid unintentional breakage 😅.

Comment (ellatrix) [reply test/e2e/specs/editor/various/embedding.spec.js]: I think it's fine if we have to refactor it again. To me the most important thing is that we have good e2e test coverage.

Comment (kevin940726) [reply test/e2e/specs/editor/various/embedding.spec.js]: I don't mind merging this as is 👍. I just think that the test might not have good coverage after all if we're "designing" the test in a way that it should pass. I guess it's hard to argue against not having the test at all though 😆.

Comment (ellatrix) [reply test/e2e/specs/editor/various/embedding.spec.js]: Not sure I agree there. We're "designing" all copy/paste tests to pass then? We're actually manually emulating everything, this is no different? For example for copy/cut, we're manually setting a clipboard instead of the browser doing the default behaviour. The test assures that default behaviour is not prevented, and we emulate the default behaviour.

Comment (kevin940726) [reply test/e2e/specs/editor/various/embedding.spec.js]: Yeah, I think I chose the wrong words😅. I couldn't find a better word. What I mean is that for this particular use case, we might not want to intercept what Playwright already does. It's to prevent future breakage of our tests when the bundled browsers update. The more robust way might be to feature-detect it in our utils, but even that is hard to do right. I hope that this convo didn't sound discouraging or blaming! I'm just not sure what the best approach is at the time, but I'm positive that we can find one! ❤️

Comment (ellatrix) [reply test/e2e/specs/editor/various/embedding.spec.js]: Not at all! ❤️ Just saying I prefer to err on the side of adding a test, even if it's not perfect, but I'm open to your util changes as a follow-up

Comment (kevin940726) [reply test/e2e/specs/editor/various/embedding.spec.js]: Sounds good! I'll try to experiment with it some more another time 😅.

**Review by allilevine — APPROVED** [review]
[We've agreed that this fix should be merged ASAP](https://github.com/WordPress/gutenberg/pull/61389#discussion_r1609550421), and it fixes the issue for me when manually testing. ✅ 


https://github.com/WordPress/gutenberg/assets/1689238/06b9bfcd-16f7-48b3-b6c8-f63b1e5408a0
