### PR TITLE
Lightbox: Fix close button position.

### LINKED ISSUE #56052: Lightbox: The right position of the close button is incorrect on Windows OS
### Description

On Windows OS, when opening Lightbox with a document that has a scroll bar, the right position of the close button is incorrect.

close-button

The button position should be 16px from the right edge as defined by [this CSS](https://github.com/WordPress/gutenberg/blob/a1ccf422e1d54598d69d0fd02a6991a2f85366e3/packages/block-library/src/image/style.scss#L227).

However, the width of the overlay, which is the reference for the position of the close button, is `100vw`, so the width includes the scrollbar.

100vw

As a result, the close button's right position no longer takes into account the width of the scrollbar.

I tried CSS like below to solve this problem:

```diff
diff --git a/packages/block-library/src/image/style.scss b/packages/block-library/src/image/style.scss
index 2b8631fffe..9926cf0b4e 100644
--- a/packages/block-library/src/image/style.scss
+++ b/packages/block-library/src/image/style.scss
@@ -215,7 +215,7 @@
        left: 0;
        z-index: 100000;
        overflow: hidden;
-       width: 100vw;
+       right: 0;
        height: 100vh;
        box-sizing: border-box;
        visibility: hidden;
```

If you apply `right: 0`, the overlay width will fit _inside_ the scrollbar. However, when the lightbox is closed, there is a slight unnatural shift, so a different approach is needed.

https://github.com/WordPress/gutenberg/assets/54422211/4585923c-a058-46ca-8b83-f10ce761375f

### Step-by-step reproduction instructions

Note: This problem would only be reproducible on Windows OS where the browser scrollbars have a physical width.

- Insert a Image Block and add an image.
- Enable "Expand on click"
- Show the post.
- Click the image.
- Focus on the button.
- The focus outline should be almost adjacent to the browser scrollbar.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 6.4.1
- Gutenberg latest trunk (Can be reproduced even if disabled)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by torounit**
## What?

Changed the position of close button to be calculated from the inside of the scroll bar.

## Why?

Fix #56052.

This problem is more noticeable in Chrome on Windows because of the wider scrollbars, but the same problem occurs when the scrollbars are displayed on a Mac.

## How?

Change width of `.wp-lightbox-overlay` to `100%` . 
Because `.wp-lightbox-overlay` is a child element of `body`, 100% is the size of 100vw minus the width of the scrollbar.

> However, when the lightbox is closed, there is a slight unnatural shift, so a different approach is needed.

Within `keyframes` `100%` is not computed. Instead `100vw - $scrollbar-width` is used.

## Testing Instructions

1. Add Image block and activate lightbox.
2. Check lightbox view.

## Screenshots or screencast 

screenshot  chrome on windows

### CODE REVIEW

**Comment by torounit** [comment]
https://github.com/WordPress/gutenberg/blob/a1ccf422e1d54598d69d0fd02a6991a2f85366e3/packages/block-library/src/image/style.scss#L375-L392

The 50vw here should also be 50%.

File: packages/block-library/src/image/view.js [hunk 1]
```diff
@@ -568,6 +568,9 @@ function setStyles( context, ref ) {
 			--wp--lightbox-image-width: ${ lightboxImgWidth }px;
 			--wp--lightbox-image-height: ${ lightboxImgHeight }px;
 			--wp--lightbox-scale: ${ containerScale };
+			--wp--lightbox-scrollbar-width: ${
+				window.innerWidth - document.body.clientWidth
```
Comment (t-hamano) [inline packages/block-library/src/image/view.js]: This may be rare, but if the `body` tag itself has an explicit width, the animation seems to break. This is probably because the `document.body.clientWidth` value used to calculate the scrollbar width changes.

I think `window.innerWidth - document.documentElement.clientWidth` is better.

body

https://github.com/WordPress/gutenberg/assets/54422211/15d2a6d5-1a90-4466-b3b6-5dbbbbcd54fd

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR! The approach seems to make sense to me too, but I'll leave a comment regarding one edge case.

**Review by michalczaplinski — APPROVED** [review]
Thanks for the PR! This approach seems sound to me! 👍

File: packages/block-library/src/image/view.js (hunk 1 above)
Comment (torounit) [reply packages/block-library/src/image/view.js]: @t-hamano 
Replaced to documentElement. Thanks!!

**Review by t-hamano — APPROVED** [review]
LGTM!

- ✅ When the document has the scrollbar
- ✅ When the document has the scrollbar and the body element has a fixed width
- ✅ When the document has no scrollbar
- ✅ When the document has no scrollbar and the body element has a fixed width


https://github.com/WordPress/gutenberg/assets/54422211/f76318ed-be5a-43dc-8c16-81cdfcc00927
