### PR TITLE
Fix: Converting video shortcode results in empty block

### LINKED ISSUE #15869: Converting video shortcode results in empty block
**Describe the bug**

When the following `[video]` shortcode is converted to a block, the resulting block is empty.

[Originally reported on the forums](https://wordpress.org/support/topic/gutenberg-convert-to-blocks-videos-are-not-being-converted/).

**Expected behavior**

The resulting block should contain the contents of the original shortcode.

**To reproduce**

1. Create a Classic block
2. Switch to HTML mode and paste in the following

```html
<p>[video width="860" height="484" mp4="https://marc.tv/media/2019/01/shenmue-vergleich-gdemu.mp4" poster="https://marc.tv/media/2019/01/gdemu_shenmue_comp-1.jpg"][/video]</p>
```

3. Switch back to visual mode, then save
4. From the kebab menu, click `Convert to blocks`. 

This created block will just be an Embed placeholder. e.g.,

```html
<figure class="wp-block-video"></figure>
```

Additionally, if you highlight the content in HTML mode, you'll see this in the error console:

```
TypeError: "this.videoPlayer.current is null"
    value http://wp.test/content/plugins/gutenberg/build/block-library/index.js?ver=1559074859:14
    qi http://wp.test/content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:130
    ui http://wp.test/content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:133
    Vc http://wp.test/content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:158
    unstable_runWithPriority http://wp.test/content/plugins/gutenberg/vendor/react.min.f4c1469c.js:27
    Vc http://wp.test/content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:158
    Sc http://wp.test/content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:158
    Z http://wp.test/content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:156
    Kc http://wp.test/content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:155
    si http://wp.test/content/plugins/gutenberg/vendor/react-dom.min.fa9ca8c8.js:132
    Q http://wp.test/content/plugins/gutenberg/vendor/react.min.f4c1469c.js:11
    ta http://wp.test/content/plugins/gutenberg/vendor/react.min.f4c1469c.js:12
    onmessage http://wp.test/content/plugins/gutenberg/vendor/react.min.f4c1469c.js:24
react-dom.min.fa9ca8c8.js:117:150
```

**Desktop (please complete the following information):**
 - OS X 
 - Chrome 74
 - WP 5.2.1
 - Gutenberg `master` @ c0ac81a6465e15125f1b54ee2b1bf63076d21e62

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/15869

The shortcode to video transform was not handling the file type shortcode attributes as a possible source so the video shortcodes ended up being transformed into an empty video block.

This PR  makes the transform handle all file type attributes documented in https://wordpress.org/support/article/video-shortcode/.

## How has this been tested?
I added a class block.
I used the insert media button to insert an mp4 video.
I used the covert to blocks option.
I verified the video block works as expected (on master it is converted to an empty video block).

### CODE REVIEW

File: packages/block-library/src/video/tranforms.js [hunk 1]
```diff
@@ -28,8 +28,8 @@ const transforms = {
 			attributes: {
 				src: {
 					type: 'string',
-					shortcode: ( { named: { src } } ) => {
-						return src;
+					shortcode: ( { named: { src, mp4, m4v, webm, ogv, wmv, flv } } ) => {
+						return src || mp4 || m4v || webm || ogv || wmv || flv;
```
Comment (talldan) [inline packages/block-library/src/video/tranforms.js]: Hey @jorgefilipecosta 

Just looking at the code for the video shortcode, and I'm not sure wmv is supported:
https://github.com/WordPress/wordpress-develop/blob/d36eda33f72f7a4fd2cfb693a84c6c1fd985cb56/src/wp-includes/media.php#L2610

I wasn't able to find any uses of the filter in that function. Might be worth double checking that one.

Comment (jorgefilipecosta) [reply packages/block-library/src/video/tranforms.js]: Nice catch @talldan 👍 The code was updated.

**Review by talldan — APPROVED** [review]
Nice! Works well when I tested it.
