### PR TITLE
Use a modal for the reusable blocks creation flow

### LINKED ISSUE #12940: Can't cancel creation of Resuable Block
**Describe the bug**
If you accidentally click the _Add to Reusable Blocks_ menu option, there's no Cancel button to allow you to cancel the Creation of the Block.

**To Reproduce**
1. Select a block
2. Click the _Add to Reusable Blocks_ menu option and then try and cancel out of that action

**Expected behavior**
I should be able to cancel the creation of a Reusable Block if I accidentally click that menu option or decide that I no longer want to create a Reusable Block.

**Desktop (please complete the following information):**
- macOS Sierra
- Firefox Quantum 63.0.3
- WP 5.0.1

### PR DESCRIPTION
**Pull request by youknowriad**
closes #12940 

Implements the flow discussed in #12940 for reusable blocks.
This new reusable block creation flow has three advantages:

 - You can cancel the creation of the reusable block
 - The generated slug for the reusable block won't be the same `untitled-reusable-block-xxx`
 - It makes it easier to give a name for the reusable block since now the "title" is in the inspector controls.

This flow is likely to be applied to template parts as well.

### CODE REVIEW

**Comment by mtias** [comment]
One issue I'm seeing:

- Create a reusable block and name it.
- After it's created, detach it (convert to regular blocks).
- Open the ellipsis for the block: a modal opens immediately.

image

**Comment by youknowriad** [comment]
Good catch @mtias it should be fixed

File: packages/reusable-blocks/src/components/reusable-blocks-menu-items/reusable-block-convert-button.js [hunk 1]
```diff
@@ -98,15 +107,61 @@ export default function ReusableBlockConvertButton( {
...
+								onSubmit={ ( event ) => {
+									event.preventDefault();
+									onConvert( title );
+									setIsModalOpen( false );
+									setTitle( '' );
+									onClose();
+								} }
+							>
+								<TextControl
+									label={ __( 'Name your reusable block' ) }
```
Comment (mtias) [inline packages/reusable-blocks/src/components/reusable-blocks-menu-items/reusable-block-convert-button.js:139]: This could be just "Add name" or "Name"

**Comment by jameskoster** [comment]
> This flow is likely to be applied to template parts as well.

It is not as the PR currently stands:

https://user-images.githubusercontent.com/846565/108200892-fe9f3d00-7116-11eb-9492-8e703c56730b.mp4

But I think it would be good to keep these flows consistent.

**Comment by youknowriad** [comment]
> But I think it would be good to keep these flows consistent.

Agreed, the idea is that this PR is focused on the reusable block UI. Once it lands, the same flow will be applied to the template part as well. It's better to keep PRs small and focused to ease reviews...

File: packages/reusable-blocks/src/components/reusable-blocks-menu-items/reusable-block-convert-button.js (hunk 1 above)
Comment (youknowriad) [reply packages/reusable-blocks/src/components/reusable-blocks-menu-items/reusable-block-convert-button.js:139]: Sure, I just used what was shown on the issue's video :)

**Comment by simison** [comment]
Not directly related to this PR but noticed while looking at some string changes here.

Language for reusable blocks feels a bit inconsistent.

How about:

- Reusable Block → Reusable block
- Block created. → Reusable block created.
- Create reusable block → Create Reusable block
- Untitled Reusable Block → Untitled Reusable block
- Manage Reusable blocks
- Add to Reusable blocks

— or maybe better with lowerkey r, "reusable block"? As long as it's consistent.

File: packages/e2e-tests/specs/editor/various/reusable-blocks.test.js [hunk 2]
```diff
@@ -260,7 +235,7 @@ describe( 'Reusable blocks', () => {
 		// Save the reusable block
 		await page.click( publishButtonSelector );
 		await page.waitForXPath(
-			'//*[contains(@class, "components-snackbar")]/*[text()="Reusable Block updated."]'
+			'//*[contains(@class, "components-snackbar")]/*[text()="Reusable block updated."]'
```
Comment (ntsekouras) [inline packages/e2e-tests/specs/editor/various/reusable-blocks.test.js:238]: This breaks due to this: https://github.com/WordPress/gutenberg/blob/master/lib/compat.php#L266

Since we make `blocks` with a lower `b`, should we change the other Labels as well?

**Review by ntsekouras — APPROVED** [review]
Thanks for woking on this Riad!

I tested and code wise looks good. I left a note for the labels thing, but we could certainly handle this in a follow up, if this decision to change all labels feel like it needs to be discussed more 🤔 .

File: packages/e2e-tests/specs/editor/various/reusable-blocks.test.js (hunk 2 above)
Comment (youknowriad) [reply packages/e2e-tests/specs/editor/various/reusable-blocks.test.js:238]: It seems there's an inconsistency between Core and Gutenberg. Core menus favor capitalizing everything and Gutenberg the opposite. This is one area where the same string can be used in two different places. The issue is that at some point the guideline here should be consistent between Core and  Gutenberg but it's a broader issue.

**Comment by paaljoachim** [comment]
This is what I see:

https://user-images.githubusercontent.com/5323259/108352345-fe6e7280-71e6-11eb-9bb7-f3d99124a149.mp4

Should the drop down seen in the background close before the popup modal is seen?

**Comment by youknowriad** [comment]
Yes, the dropdown should stay open in case you cancel, the focus is moved back there.

**Comment by chrisvanpatten** [comment]
Late to the party but very happy to see this; thanks @youknowriad ❤️

**Comment by paaljoachim** [comment]
I just made an issue. 
If the reusable block is for instance named Heading it can cause confusion. 
Should there be a prefix added to all Reusable blocks?
https://github.com/WordPress/gutenberg/issues/29267
