### PR TITLE
Fix duotone on parallax/repeated featured image cover blocks

### LINKED ISSUE #50828: Duotone filter not showing on Covers inside Query Loops
### Description

As I am exploring different ways to use Cover blocks I may have found a possible bug. I am using Covers inside Query loops (`Query loops > Post template > Cover`) and duotone filters set to those covers do not show in Frontend site.
While previewing in the Editor they are there but once published the site they're gone.

The issue is repeated in two different sites, both [Jazzers](https://jazzers.mystagingwebsite.com/) and [Nested](https://nested.mystagingwebsite.com/).

We had a discussion about it on [this Slack thread](https://a8c.slack.com/archives/C029FM1EH/p1682679111379989) but we couldn't get to a solution.

### Step-by-step reproduction instructions

1. Create a group on the root and add a Query Loop to it;
2. Inside Post Template add a Cover and pull the post content into this cover;
3. Add a duotone filter to this Cover. Please test with duotones available on preset and custom colors;
4. Check the published site.

### Screenshots, screen recording, code snippet

May22_cover-duotone_fail

Check the site here: https://jazzers.mystagingwebsite.com/

### Environment info

- WordPress 6.2.2, Gutenberg 15.8.1
- Create Block Theme generated theme called **Jazzers**

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ajlende**
## What?

Updates the cover block to render a `<div>` background when using featured images.

The best way to review this is to compare with the [cover block's `save` function](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/cover/save.js#L127-L146) as the newly added code should mirror that when a featured image is used.

## Why?

Fixes #50828 

Cover blocks using featured images didn't pick up duotone because they weren't using an element for the featured image.

## How?

Generate a `<div>` instead of setting `background-image` for cover blocks using featured images.

## Testing Instructions

```html
<!-- wp:query {"queryId":9,"query":{"perPage":12,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false,"taxQuery":null,"parents":[],"format":[]}} -->
<div class="wp-block-query"><!-- wp:post-template -->
<!-- wp:cover {"useFeaturedImage":true,"hasParallax":true,"dimRatio":0,"isUserOverlayColor":true,"isDark":false,"style":{"color":{"duotone":"var:preset|duotone|grayscale"}}} -->
<div class="wp-block-cover is-light has-parallax"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","fontSize":"large"} -->
<p class="has-text-align-center has-large-font-size"></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->
<!-- /wp:post-template --></div>
<!-- /wp:query -->
```

1. Create some posts that have featured images.
2. Insert above content or add the following structure.
   - Query loop block
     - Cover block
       - Enable featured image
       - Enable parallax (also try repeat)
       - Enable duotone filter
4. Save and view the page to confirm that the featured images cover blocks show the duotone effect.

### Testing Instructions for Keyboard

N/A

### Before

Screen Shot 2024-10-07 at 16 09 32

### After

Screen Shot 2024-10-07 at 16 09 13

### CODE REVIEW

File: packages/block-library/src/cover/index.php [hunk 1]
```diff
@@ -52,15 +45,40 @@ function render_block_core_cover( $attributes, $content ) {
...
+
+		$processor->add_class( 'wp-block-cover__image-background' );
+		if ( $attributes['hasParallax'] ) {
+			$processor->add_class( 'has-parallax' );
+		}
+		if ( $attributes['isRepeated'] ) {
+			$processor->add_class( 'is-repeated' );
+		}
+
+		$styles = 'background-position:' . isset( $object_position ) ? $object_position : '50% 50%' . ';';
```
Comment (ajlende) [inline packages/block-library/src/cover/index.php]: The default `50% 50%` comes from the default value returned from [`mediaPosition`](https://github.com/WordPress/gutenberg/blob/502a2d5bd25cc06af4241ad872c3bcef0d56fed5/packages/block-library/src/cover/shared.js#L27) in [`save`](https://github.com/WordPress/gutenberg/blob/502a2d5bd25cc06af4241ad872c3bcef0d56fed5/packages/block-library/src/cover/save.js#L81).

This default value isn't used for `object-position` in the JS, but it probably should be. However, that can't be changed without adding a deprecation for the cover block which I don't want to do as part of this bug fix.

File: packages/block-library/src/cover/index.php [hunk 2]
```diff
@@ -52,15 +45,40 @@ function render_block_core_cover( $attributes, $content ) {
...
+		if ( $current_featured_image ) {
+			$styles .= 'background-image:url(' . esc_url( $current_featured_image ) . ');';
+		}
+		$processor->set_attribute( 'style', $styles );
```
Comment (ajlende) [inline packages/block-library/src/cover/index.php]: Oddly enough, the `background-position` is always added even if the `background-image` isn't in the JS. That can't be changed without adding a deprecation for the cover block which I don't want to do as part of this bug fix.

File: packages/block-library/src/cover/index.php [hunk 3]
```diff
@@ -52,15 +45,40 @@ function render_block_core_cover( $attributes, $content ) {
...
-		$processor->set_attribute( 'style', $merged_styles );
-		$content = $processor->get_updated_html();
+	/*
+	 * Inserts the featured image between the (1st) cover 'background' `span` and 'inner_container' `div`,
+	 * and removes eventual whitespace characters between the two (typically introduced at template level)
+	 */
+	$inner_container_start = '/<div\b[^>]+wp-block-cover__inner-container[\s|"][^>]*>/U';
+	if ( 1 === preg_match( $inner_container_start, $content, $matches, PREG_OFFSET_CAPTURE ) ) {
+		$offset  = $matches[0][1];
+		$content = substr( $content, 0, $offset ) . $image . substr( $content, $offset );
```
Comment (ajlende) [inline packages/block-library/src/cover/index.php:82]: Moved from [L37-L45 above](#diff-4518dd019994a649b1d4def5459d5a5899d93543145bff074d531327730fef92L37-L45) as both branches of the conditional need to insert content in the same place.

**Review by jeryj — APPROVED** [review]
Reviewed on a pairing call. Tested with various combinations of the cover block and confirmed this fixes the issue and aligns editor and frontend HTML output.
