### PR TITLE
Fix the lingering dropzone placeholder at the end of the editor

### LINKED ISSUE #4810: Lingering placeholder at the bottom of page when dragging a file over the blocks list
## Issue Overview

There appears to be a bug whereby a lingering placeholder appears at the bottom of the page when dragging a file to drop into the dropzones. On first glance this looks to be related to the changes made to the block sibling inserter - might be a good place to start.

Spotted by @youknowriad

p.s. Not sure if this is a bug or a feature.

## Steps to Reproduce (for bugs)

1. Create a post with several blocks.
2. Grab a file from desktop and drag over the page.

## Screenshots / Video

bottom-placeholder

### PR DESCRIPTION
**Pull request by youknowriad**
closes #4810 

Since the DragOver event handler is debounced, it's called even after the onDrop event handler happens which causes the placeholder to show up after the mouse has been released.
This PR fixes this behavior by canceling the debounced calls.
It also includes some small fixes to the dropzone size of the default block appender.

**Testing instructions**

 - Drag and drop files into the document
 - You should not see any lingering placeholder after releasing the mouse.

### CODE REVIEW

**Comment by chriskmnds** [comment]
Ah I thought the placeholder shouldn't show at all when dragging - but now I understand the problem is that it stays after dropping something. It still lingers though if you don't drop the image i.e. don't release the mouse on the page. Other than that, looks awesome on my end - tested in Chrome/Safari/FF. :-)

**Comment by jorgefilipecosta** [comment]
This seems to fix a bug where  placeholders continue to show after releasing the mouse in the document 👍 
But if the release happens outside of the window we can come back to the window scroll on it and the placeholders continue to show:
feb-05-2018 22-08-33

File: editor/components/block-list/index.js [hunk 1]
```diff
@@ -250,7 +249,6 @@ class BlockList extends Component {
 
 		return (
 			<BlockSelectionClearer>
-				{ !! blocks.length && <BlockInsertionPoint /> }
```
Comment (jorgefilipecosta) [inline editor/components/block-list/index.js]: I'm not seeing the relation of this change to the others.What's the reason for the removal of this line? (sorry, I'm probably missing something)

Comment (youknowriad) [reply editor/components/block-list/index.js]: No you're not, this was a left-over from another PR. It's useless because the insertion point should not be shown here (it's shown inside each block). I've lost the link to the comment suggesting removing this.

It's in this PR because I thought it was related at first but it was not but I just kept this removal since its useless.

**Comment by youknowriad** [comment]
@jorgefilipecosta @chriskmnds It's not easy to solve the dropping outside of the document issue but I believe this issue has always been there, it's not a recent regression. 

I'm thinking we should move forward with this patch as is and fix the remaining issue separately (try to find a way to fix without over-complexifying the code)

File: editor/components/block-list/index.js (hunk 1 above)
Comment (jorgefilipecosta) [reply editor/components/block-list/index.js]: Ok thank you for the clarification 👍

**Review by jorgefilipecosta — APPROVED** [review]
The changes look good to me, and they cause no regressions, so I think it is good to merge. Not certain why CI is failing but locally the tests passed.

**Comment by youknowriad** [comment]
@jorgefilipecosta Yes, CI is failing today (not specific to this branch) and I can't find the exact reason yet. I suspect some changes in a docker image we use.

**Comment by chriskmnds** [comment]
Well spotted Riad! :-)
