### PR TITLE
Image Block: Fix cover block exists check

### LINKED ISSUE #32094: Image block shows toolbar button to "Add text over image" even when `core/cover` block is nor registered
## Description

The Core Image Block recently added an option to "Add text over image" which under the hood transforms the Image block to a Cover Block. This button still gets rendered in the Blocks Toolbar in cases where the Cover Block is not registered. 

Instances where this can happen is when a site uses white / blacklisting.  

## Expected behaviour

When the Core Cover block is not registered the button should not show anymore.

## Actual behaviour

When the Core Cover block is not registered the button does snow but doesn't do anything.

## WordPress information
- WordPress version: "5.7.2"
- Gutenberg version: "Not installed"
- Are all plugins except Gutenberg deactivated? "Yes"
- Are you using a default theme (e.g. Twenty Twenty-One)? "Yes"

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
Updates `coverBlockExists` check to include checking against `allowedBlockTypes` list.

Fixes #32094.

## How has this been tested?
1. Filter allowed block types list to remove the cover block:
```php
add_filter( 'allowed_block_types', function() {
    return [
        'core/image',
        'core/paragraph',
        'core/heading',
        'core/list'
    ];
} );
```
2. Create a post.
3. Add image block.
4. Toolbar shouldn't render the "Add text over the image" button.

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ x My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by jorgefilipecosta — APPROVED** [review]
LGTM 👍

File: packages/block-library/src/image/image.js [hunk 1]
```diff
@@ -61,6 +61,27 @@ function getFilename( url ) {
...
 
+/**
+ * Checks if the given block is registered and is in the allowed blocks list.
+ *
+ * @param {string}        name Block name.
+ * @param {boolean|Array} list Allowed block types.
+ *
+ * @return {boolean}           Whether the block exists.
+ */
+function checkBlockExists( name, list ) {
```
Comment (mtias) [inline packages/block-library/src/image/image.js:72]: If this is formalized in a function, it seems like it belongs in the block/api/registration set and not on the block

Comment (Mamaduka) [reply packages/block-library/src/image/image.js:72]: Hi, @mtias

Do you want me to create a new issue for this function?

Comment (mtias) [reply packages/block-library/src/image/image.js:72]: I think it'd make sense in order to keep the image block file cleaner. Alternatively, we might want to approach this slightly different and look at `getPossibleBlockTransformations` instead and not to the block registry.

Comment (jorgefilipecosta) [reply packages/block-library/src/image/image.js:72]: Yes relying on the transforms seems to be a really good idea, it may cover other checks that we may be missing. I guess we can rely on the getBlockTransformItems selector.

Comment (mtias) [reply packages/block-library/src/image/image.js:72]: Just to be clear, the `getPossibleBlockTransformations` selector already exists :)

Comment (Mamaduka) [reply packages/block-library/src/image/image.js:72]: I agree. Using a transforms selector makes more sense here. Also, we don't have all cases covered yet - #32520.

I will create a new PR that uses `getPossibleBlockTransformations` if possible or similar logic.
