### PR TITLE
Site Editor: Add theme taxonomy to templates and template parts

### LINKED ISSUE #24377: FSE Post Meta Queries Performance
**Describe the bug**
Template part posts use a `theme` post meta key value. The problem is that FSE then searches for posts that have this value in the future, specifically on save.

While this happens in a lot of WP sites, the performance is poor, and it does not scale. Such a query will outright fail on a large site, and could bring down a database server on sites handling lots of concurrent visitors.

The posts meta table was never intended for those kind of queries, if it was then tags and categories would be stored in post meta. That table is designed for finding values when you know the post ID and key, not the other way around.

**The problem is trivial to sidestep though, and  even has precedent elsewhere in core, use a taxonomy.**

The performance of that query if a taxonomy were used would be orders of magnitude faster. Post meta queries do not scale as the site gets more content and traffic, taxonomies do. Take a look at Nav menus for an example of taxonomies in core. I wouldn't recommend copying it, but a simple `wp_theme` taxonomy for the template and template parts would give massive performance gains for minimal effort.

**To reproduce**
1. Try to save a template part on a site that has a lot of posts and posts meta
2. Observe degraded performance

### PR DESCRIPTION
**Pull request by david-szabo97**
## Description

Fixes #24377

Replace theme meta with theme taxonomy. Register a taxonomy called `wp_theme` and use it to store the theme of the template and template parts.

A special value is used to mark templates that were created from a theme template file. This value is: `_wp_file_based`.

## How has this been tested?
Everything should work the same way as before. You will need to start clean. (Delete all templates and template parts)

## Types of changes
Breaking change

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by carlomanf** [comment]
Thanks for this. I just have a few questions:

> A special values is used to to mark templates that were created from a theme template file. This value is: `wp_file_based`.

What's the purpose of this? Is it necessary? It would conflict if there happened to be a theme called `wp_file_based`.

> You will need to start clean. (Delete all templates and template parts)

I want to be able to keep the ones I already have and have them automatically update to the new system. Would it be a good idea to automatically associate templates and parts with the current theme by default, similar to how posts get automatically put in Uncategorized?

**Comment by david-szabo97** [comment]
> What's the purpose of this? Is it necessary? It would conflict if there happened to be a theme called wp_file_based.

It will used to differentiate between file-based theme templates and user-created templates. 

> I want to be able to keep the ones I already have and have them automatically update to the new system. Would it be a good idea to automatically associate templates and parts with the current theme by default, similar to how posts get automatically put in Uncategorized?

I've added a function that migrates from meta to taxonomy. Good point there, it would be difficult to ask everyone to start  clean 😄 Later on we can remove this function.

**Comment by carlomanf** [comment]
> > What's the purpose of this? Is it necessary? It would conflict if there happened to be a theme called wp_file_based.
> 
> It will used to differentiate between file-based theme templates and user-created templates.

I gathered that much, but I mean where will this differentiation be needed?

> > I want to be able to keep the ones I already have and have them automatically update to the new system. Would it be a good idea to automatically associate templates and parts with the current theme by default, similar to how posts get automatically put in Uncategorized?
> 
> I've added a function that migrates from meta to taxonomy. Good point there, it would be difficult to ask everyone to start clean 😄 Later on we can remove this function.

Thanks, but I think we could go a step further and implement something permanent. My understanding is theme-less templates and parts are not being supported for the time being, so wouldn't it make sense for there to be some kind of "sanitisation" on saving the post?

**Comment by aristath** [comment]
Is this a duplicate of https://github.com/WordPress/gutenberg/pull/24720 ? :thinking:

**Comment by gziolo** [comment]
@aristath, good catch. I was about to ask exactly the same question. As far as I can tell it look nearly identical.

**Comment by david-szabo97** [comment]
> Is this a duplicate of #24720 ? 🤔

@aristath Would you like to rebase your PR and finish it up? I'd be happy to close this PR as a duplicate and review yours.

**Comment by aristath** [comment]
No need... Yours is up to date and rebasing mine would be a waste of time since we already have this one.
I'll close mine as superseded by this one, review it and see if there's anything missing (though from a quick look it looks OK). As long as it gets done it doesn't matter who does it :+1:

File: lib/templates.php [hunk 1]
```diff
@@ -75,19 +75,94 @@ function gutenberg_register_template_post_type() {
...
+		wp_set_post_terms( $post->ID, $terms, 'wp_theme', true );
+	}
+	wp_reset_postdata();
+
+	global $wp;
+	wp_redirect( add_query_arg( $wp->query_vars, home_url( $wp->request ) ) );
+	exit;
 }
-add_action( 'init', 'gutenberg_register_template_post_type' );
+add_action( 'init', 'gutenberg_migrate_theme_meta_to_taxonomy' );
```
Comment (aristath) [inline lib/templates.php:165]: I don't think we really need a migration process here... 
FSE themes are extremely experimental and there's just 1 theme in the repo with very few installs - mostly by people working in Gutenberg.
If this migration function is removed, nothing breaks... worst case scenario there are a couple more entries in the db. Which is OK, and preferable to shipping code that will eventually have to be removed IMO

**Comment by david-szabo97** [comment]
> No need... Yours is up to date and rebasing mine would be a waste of time since we already have this one.
> I'll close mine as superseded by this one, review it and see if there's anything missing (though from a quick look it looks OK). As long as it gets done it doesn't matter who does it 👍

Thank you! Sorry for hijacking your PR 😅

File: lib/templates-sync.php [hunk 2]
```diff
@@ -42,6 +47,7 @@ function _gutenberg_create_auto_draft_for_template( $post_type, $slug, $theme, $
 				'post_status'  => 'auto-draft',
 				'post_type'    => $post_type,
 				'post_name'    => $slug,
+				'tax_input'    => array( 'wp_theme' => array( $theme, 'wp_file_based' ) ),
```
Comment (Copons) [inline lib/templates-sync.php:50]: How about `_wp_file_based` instead?
It should hopefully guard well enough against themes with the same name (and yes, the irony that Automattic has a theme that starts with an underscore is not lost on me 😄).

File: lib/templates.php (hunk 1 above)
Comment (Copons) [reply lib/templates.php:165]: Agree!
We are pushing so many breaking changes around Full Site Editing, that I don't really see the need of a migration for these meta.

File: lib/template-parts.php [hunk 3]
```diff
@@ -191,15 +182,52 @@ function filter_rest_wp_template_part_collection_params( $query_params ) {
...
+			);
+			if ( $theme_slug ) {
+				$response->data['wp_theme_slug'] = $theme_slug[0];
+			}
+		}
+	}
+
+	return $response;
+}
+add_filter( 'rest_prepare_wp_template_part', 'filter_rest_prepare_wp_template_part' );
```
Comment (Copons) [inline lib/template-parts.php:233]: Do we still need this?
The `wp_theme` taxonomy is set to `show_in_rest` so we should get it for free now.

File: lib/template-parts.php [hunk 4]
```diff
@@ -191,15 +182,52 @@ function filter_rest_wp_template_part_collection_params( $query_params ) {
...
-			'value' => $request['theme'],
+		$tax_query   = isset( $args['tax_query'] ) ? $args['tax_query'] : array();
+		$tax_query[] = array(
+			'taxonomy' => 'wp_theme',
+			'field'    => 'slug',
+			'terms'    => $request['theme'],
 		);
 
-		$args['meta_query'] = $meta_query;
+		$args['tax_query'] = $tax_query;
```
Comment (Copons) [inline lib/template-parts.php:192]: I don't think we need this filter anymore, since we can just use the built-in `wp_theme` param now.

I'm wondering about this.
Now we should be able to filter by taxonomy by simply providing `?wp_theme=[ termId ]`.
Of course we don't have the term ID, but its slug.
Maybe there's a hidden trick that lets us do this without having to filter the query? 🤔

**Review by aristath — CHANGES_REQUESTED** [review]
Overall this looks good!

I only found 1 part that was missed, but I didn't want to push directly to your branch so there's a small additional PR against this one here: https://github.com/WordPress/gutenberg/pull/27042

File: lib/template-parts.php (hunk 4 above)
Comment (aristath) [reply lib/template-parts.php:192]: :laughing: I ran into the same issue in my alternative PR a few months ago and after some research I couldn't find a better way to do it either... (https://github.com/WordPress/gutenberg/pull/24720#issuecomment-702675209)
We _could_ do it by adding an extra JS implementation to get the term ID from its slug, but that would be extremely wasteful as it would just result in an extra query to the server... The current implementation is not perfect, but I think it's the best we can do with the current state of the REST API without significant refactors :+1:

Comment (Copons) [reply lib/template-parts.php:192]: Ooh, I see, makes sense.

File: lib/template-parts.php (hunk 3 above)
Comment (david-szabo97) [reply lib/template-parts.php:233]: Easier to access this way. I'd like to avoid adding JS code to every part where we accessed the meta. We would need to `select` the taxonomy terms and do filtering and all kind of stuff.

File: lib/templates.php [hunk 5]
```diff
@@ -75,19 +75,37 @@ function gutenberg_register_template_post_type() {
...
+function gutenberg_register_wp_theme_taxonomy() {
+	if ( ! gutenberg_is_fse_theme() ) {
+		return;
+	}
 
-	register_post_type( 'wp_template', $args );
-	register_meta( 'post', 'theme', $meta_args );
+	register_taxonomy(
+		'wp_theme',
+		array( 'wp_template', 'wp_template_part' ),
```
Comment (Copons) [inline lib/templates.php:91]: I find the fact that we are registering in `wp_template` a taxonomy for both `wp_template` and `wp_template_part` slightly confusing.
I don't have a better solution though, unless we created a new file to contain FSE-related taxonomies, and load it after both templates and template parts have been registered.

I don't think it's a blocker either way, just something we might need to remember while working on this stuff. 🤔

File: lib/template-parts.php (hunk 3 above)
Comment (Copons) [reply lib/template-parts.php:233]: Ah right, the term ID fooled me twice. 😤

**Review by aristath — APPROVED** [review]

**Comment by david-szabo97** [comment]
All should be good, now let's wait for the tests 😬

File: lib/template-parts.php [hunk 6]
```diff
@@ -191,15 +182,55 @@ function filter_rest_wp_template_part_collection_params( $query_params ) {
...
+			);
+			if ( $theme_slug ) {
+				$response->data['wp_theme_slug'] = $theme_slug[0];
+			}
+		}
+	}
+
+	return $response;
+}
+add_filter( 'rest_prepare_wp_template', 'filter_rest_prepare_add_wp_theme_slug_and_file_based' );
```
Comment (david-szabo97) [inline lib/template-parts.php:235]: @Copons Same problem here. We are using the same function for both... Any idea where we should put this?

Comment (Copons) [reply lib/template-parts.php:235]: It's a tricky one.
How do you feel about moving these:

- Taxonomy registration.
- `filter_rest_prepare_add_wp_theme_slug_and_file_based`
- `gutenberg_set_template_post_theme` and `gutenberg_set_template_part_post_theme`
- Anything else related to the **management** (not usage) of the `wp_theme` term that I might have forgotten.

...into a `templates-terms.php` lib? 🤔

File: lib/templates.php [hunk 7]
```diff
@@ -114,24 +114,20 @@ function gutenberg_register_wp_theme_taxonomy() {
...
-		// Using a string instead of integer will create the term and assign it to the post.
-		wp_set_object_terms( $post_id, wp_get_theme()->get_stylesheet(), 'wp_theme' );
+	if ( ! $themes ) {
+		wp_set_post_terms( $post_id, array( wp_get_theme()->get_stylesheet() ), 'wp_theme', true );
 	}
 }
 
-add_action( 'save_post', 'gutenberg_set_template_post_theme', 10, 3 );
+add_action( 'save_post_wp_template', 'gutenberg_set_template_post_theme', 10, 3 );
+add_action( 'save_post_wp_template_part', 'gutenberg_set_template_post_theme', 10, 3 );
```
Comment (Copons) [inline lib/templates.php:130]: These two should have `gutenberg_set_template_and_template_part_post_theme` as callback.

Comment (david-szabo97) [reply lib/templates.php]: Gosh, was about to commit. You are fast :D

**Review by Copons — APPROVED** [review]
I'm not convinced that `templates.php` is the best place for the `wp_theme` term handling, but I don't have a better idea.
It might be worth it to move them into their own separate file, but it's something we can discuss and address separately.

Everything else seems to work fine to me! ✨ 
Thank @david-szabo97 for pushing this forward and @aristath for being so graceful about the old PR and for the excellent reviews!

File: lib/template-parts.php (hunk 6 above)
Comment (noahtallen) [reply lib/template-parts.php]: that makes sense to me. I'm not sure if any other util files exist that would make sense for it

**Review by noahtallen — CHANGES_REQUESTED** [review]
I found a bug:

(prereq: have 2021-blocks active)

1. From the template CPT page, create a new template.
2. Name it "front page".
3. Add some content and save it.
4. Load the site editor.

Expectation: my new front-page template is the front page of the site (custom templates should override theme templates)

Result: the theme-provided front-page template is used. My custom front-page is still seen in the nav sidebar. That's weird because you get two front-page templates there. But the one resolved for actual use is the theme-provided one, not your custom one.

This is why the e2e test is failing. I'm still trying to figure out exactly why this is happening

File: lib/templates.php [hunk 8]
```diff
@@ -96,19 +114,19 @@ function gutenberg_register_template_post_type() {
  * @param array $post    Template Post.
  * @param bool  $update  Is update.
  */
-function gutenberg_set_template_post_theme( $post_id, $post, $update ) {
-	if ( 'wp_template' !== $post->post_type || $update || 'trash' === $post->post_status ) {
+function gutenberg_set_template_and_template_part_post_theme( $post_id, $post, $update ) {
+	if ( $update || 'trash' === $post->post_status ) {
 		return;
 	}
```
Comment (carlomanf) [inline lib/templates.php:120]: Can we remove this early return? This is basically what I was asking for originally, not so much a migration. I don't believe there is any case in which a template should be without a theme, not with the current implementation anyway.

Comment (carlomanf) [reply lib/templates.php:120]: Plus, it would only ever happen through a corruption of the database, since the theme is automatically added upon the post first being created. Removing this early return would just protect against that.

File: lib/template-parts.php (hunk 6 above)
Comment (aristath) [reply lib/template-parts.php]: Makes sense I suppose... Though tbh I don't know if splitting to more files is better than merging multiple files in 1. 
One could argue that instead of adding yet another file, we should merge the `templates.php` and `template-parts.php` files. There's pros and cons to both approaches, and IMO it's a trivial decision that should not be a blocker :+1:

File: lib/templates.php (hunk 8 above)
Comment (david-szabo97) [reply lib/templates.php:120]: Sounds right to me! Committing

**Comment by david-szabo97** [comment]
Just to leave an update, the bug mentioned by Noah is fixed with the 7cfd2eb commit. (Big thanks to @noahtallen for debugging it out!)

The performance test is still failing. I'm rebasing in hopes of magically fixing it

**Comment by david-szabo97** [comment]
Hopefully, perf test is now going to pass. Perf test was failing because we use the same database for testing the `master` and this branch. Since `master` branch is ran first in the perf test, it creates all the templates (with meta) and this branch won't find any templates because the theme terms are missing. (Since `master` created the templates) To fix this, we also delete the `auto-draft` templates so we can regenerate the templates with terms instead of metas.

**Review by noahtallen — APPROVED** [review]
LGTM! That bug is fixed now. :shipit:

**Comment by youknowriad** [comment]
Hi there! Can we update the architecture docs to reflect these changes? Can we explain the purpose of each of these taxonomies?

Also what value the "_wp_file_based" provides? A user might edit the template entirely which might make this taxonomy meaningless.

**Comment by Copons** [comment]
> Also what value the "_wp_file_based" provides? A user might edit the template entirely which might make this taxonomy meaningless.

@youknowriad `_wp_file_based` indicates the "origin" of a template/part.
As long as it's `auto-draft`, we know that it hasn't been modified, and so it's exactly like its file counterpart.

Once it's modified, its status will change to anything else (`draft`, `publish`). Combined with `_wp_file_based` it means that:
- The template was originally converted from a file.
- It is now customized.
- We can "revert" it to be like the original file.

Without the `_wp_file_based` tag, we wouldn't have a good way to know if a template was automatically created from a file.
Initially we relied only on the `auto-draft` status, but that's not necessarily enough, as users can create auto-draft templates if they start editing a template with the normal post editor (e.g. from `/wp-admin/edit.php?post_type=wp_template`) and leave without saving.
