### PR TITLE
Fix visual indication of switch to default template in the post editor

### LINKED ISSUE #48577: No visual indication of switch to default template in the post editor
### Description

When using the template switcher in the post editor sidebar to switch from a custom template back to the default one, there is a brief flash of layout reflow but apart from that no visual indication that the change was successful. Neither the template name in the sidebar or the layout actually changes.

### Step-by-step reproduction instructions

1. In a block theme with more than one post (single) template, create a post and set it to use a non-default template.
2. Save and reload the page.
3. Try switching the template back to the default.

### Screenshots, screen recording, code snippet

template-switch-to-default

### Environment info

I noticed this happening on the latest Gutenberg trunk, but it's also reproducible on WP 6.1.1 with no plugins enabled so it's not a regression from the last release.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/48577

When using the template switcher in the post editor sidebar to switch from a custom template back to the default one, there is no visual indication that the change was successful. Neither the template name in the sidebar or the layout actually changes.

## Why?
As @talldan mentions [here](https://github.com/WordPress/gutenberg/issues/48577#issuecomment-1459817254), internally we were using `__experimentalGetTemplateForLink` which doesn't take into account unsaved changes(in our case the `template` prop) which results in the wrong template resolution. The same problem was encountered in switching templates in site editor and has been resolved with this [PR](https://github.com/WordPress/gutenberg/pull/55883), that introduced the `getDefaultTemplateId` selector I'm using here.

## Testing Instructions
1. In a block theme with more than one post (single) template, create a post and set it to use a non-default template.
2. Save and reload the page.
3. Try switching the template back to the default.

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/16275880/a929f645-6e35-4418-bc9c-4169789746bd

### CODE REVIEW

**Comment by ntsekouras** [comment]
The e2e failures are valid. I'll have to investigate..

File: packages/edit-post/src/store/selectors.js [hunk 1]
```diff
@@ -583,12 +583,27 @@ export const getEditedPostTemplate = createRegistrySelector(
 		}
 
 		const post = select( editorStore ).getCurrentPost();
-		if ( post.link ) {
-			return select( coreStore ).__experimentalGetTemplateForLink(
-				post.link
-			);
+		let slugToCheck;
```
Comment (youknowriad) [inline packages/edit-post/src/store/selectors.js:597]: I think this function is actually a duplicate of a similar behavior `useResolveEditedEntityAndContext` in the edit-site package. So I think we should probably apply the same fix here which might fix an issue @ellatrix experienced with the wrong template being loaded in the site editor for draft pages.

Comment (ntsekouras) [reply packages/edit-post/src/store/selectors.js:597]: >So I think we should probably apply the same fix here

You're talking about the slug to check logic and you  meant `there` instead of `here` I reckon, right?

Comment (youknowriad) [reply packages/edit-post/src/store/selectors.js:597]: yes, I mean there :)

Comment (ntsekouras) [reply packages/edit-post/src/store/selectors.js:597]: Done

File: packages/edit-post/src/store/selectors.js [hunk 2]
```diff
@@ -594,12 +594,27 @@ export const getEditedPostTemplate = createRegistrySelector(
...
-
-		return null;
+		const defaultTemplateId = select( coreStore ).getDefaultTemplateId( {
+			slug: slugToCheck,
+		} );
+		return select( coreStore ).getEditedEntityRecord(
+			'postType',
+			'wp_template',
+			defaultTemplateId
+		);
```
Comment (youknowriad) [inline packages/edit-post/src/store/selectors.js:618]: So one thing I noticed here is that this function is getting closer to use-init-edited-entity-from-url which is good.
The remaining difference is about the handling of the "posts page" and the "home page", both of these have special handling in the site editor that is not present here. I'm thinking that we might want to check these and unify these as well (probably a separate PR though)

**Review by youknowriad — APPROVED** [review]
I confirm that this fixes both issues I was seeing:

 - The draft pages not showing the right template in the site editor (theme 2024).
 - The right template selected in the sidebar of the post editor when swapping templates.

I'd love if we can test some of these.

**Comment by ntsekouras** [comment]
>I'd love if we can test some of these.

There is a test in post editor and a draft page already and I added one more for post editor.
