### PR TITLE
Popover, CustomGradientPicker, Dropdown: Fix positioning of popover when used in a dropdown

### LINKED ISSUE #41353: `CustomGradientPicker`: `ColorPicker` popover is glitchy (size and position)
The popover containing the `ColorPicker` opens in unexpected positions (and sometimes with a smaller size than expected) in the `CustomGradientPicker` component:

https://user-images.githubusercontent.com/1083581/170356848-6d62166e-0746-4868-9d9d-8303d4e917d3.mp4

This could be related to the recent refactor of the `Popover` component in #40740

### PR DESCRIPTION
**Pull request by andrewserong**
## What?

Fixes: https://github.com/WordPress/gutenberg/issues/41353

Fix positioning of the Popover when used in dropdowns and the custom gradient picker. Also, fix the issue where the width of the Popover was being reduced when it appears close to the edge of the viewport.

## Why?

As reported in #41353 there were a few issues with the Popover positions when used in the custom gradient bar. The issues appeared to be the following:

* The position of the Popover was incorrect due to the Dropdown component using the parent Dropdown node as the reference for where to position the popover, as opposed to the toggle button, which is where we'd expect it to be attached.
* The `size` [middleware in the Popover](https://floating-ui.com/docs/size) reduces the size of the popover by looking at the amount of space between the anchor and the edge of the viewport — this is likely not what we want for the horizontal axis, as it reduces the Popover when the Popover is right at the edge of the screen, and also appears to be the root cause of one of the issues in https://github.com/WordPress/gutenberg/pull/41268 (Tooltip issues).

## How?

* Remove the `maxWidth` setting from the `size` middleware used in the Popover
* Force the Dropdown to use the first child of the Dropdown (the rendered toggle) as the anchor point for the Popover when no anchor ref is provided

## Testing Instructions

1. In Storybook, follow the issue in #41353 and check that the popover displays correctly.
2. In the editor, add a custom gradient to a Group block and ensure the Popover is still positioned at the right of the area (and doesn't change position based on where you click on the gradient bar)
3. Hover over the Settings icon at the top right of the editor — you should see that the Tooltip no longer gets cut off

***Note***: clicking on the control points in the gradient bar is a little glitchy at the moment, too — I think some adjustments need to be made there, too, but that's outside the scope of this PR.

## Screenshots or screencast 

| Before | After |
| --- | --- |
|  |  |
|  | image |

### CODE REVIEW

File: packages/components/src/custom-gradient-picker/utils.js [hunk 1]
```diff
@@ -75,7 +75,7 @@ export function getGradientAstWithControlPoints(
 			return {
 				length: {
 					type: '%',
-					value: position.toString(),
+					value: position?.toString(),
```
Comment (andrewserong) [inline packages/components/src/custom-gradient-picker/utils.js:78]: This was throwing errors in Storybook due to `position` being undefined. To prevent those errors, I've added in optional chaining, which seemed to do the trick. It doesn't appear to change anything in real world usage in the editor, but made it easier to log out values while debugging in storybook.

File: packages/components/src/popover/index.js [hunk 2]
```diff
@@ -194,6 +194,7 @@ const Popover = (
 		shift( {
 			crossAxis: true,
 			limiter: limitShift(),
+			padding: 1, // Necessary to avoid flickering at the edge of the viewport.
```
Comment (andrewserong) [inline packages/components/src/popover/index.js:197]: I'm not sure what it is about the particular settings we're using, but I couldn't get everything to work correctly (removed maxWidth on the size middleware, and a popover at the edge of the screen) without adding at least `1px` of padding to the `shift` middleware. Otherwise We'd see jiggling like in this comment: https://github.com/WordPress/gutenberg/pull/41268#discussion_r881293934



I'm hoping that adding `1px` padding here (which only gets applied at the edge of the viewport) will be viable in the shorter-term. Though it'd be good to get to the bottom of why the issue occurs without the padding.

**Comment by andrewserong** [comment]
@kevin940726 I've added you as a reviewer, since I saw you ran into a similar issue with the Tooltip / maxWidth issue 🙂

**Review by youknowriad — APPROVED** [review]
All the changes here make sense to me. Thanks Andrew

Tested these:

 - Settings tooltips
 - Gradient picker

File: packages/components/src/custom-gradient-picker/utils.js (hunk 1 above)
Comment (kevin940726) [reply packages/components/src/custom-gradient-picker/utils.js:78]: When will it error in storybook? Are there reproduction steps?

File: packages/components/src/dropdown/index.js [hunk 3]
```diff
@@ -108,7 +108,11 @@ export default function Dropdown( props ) {
 					// This value is used to ensure that the dropdowns
 					// align with the editor header by default.
 					offset={ 13 }
-					anchorRef={ ! hasAnchorRef ? containerRef : undefined }
+					anchorRef={
+						! hasAnchorRef
+							? containerRef?.current?.firstChild // Anchor to the rendered toggle.
+							: undefined
+					}
```
Comment (kevin940726) [inline packages/components/src/dropdown/index.js:115]: This always feels weird to me that the prop is called `anchorRef` but it can also accept DOM elements 😆.

**Review by ciampo — APPROVED** [review]
Thank you @andrewserong , code changes LGTM (and the issues is fixed)

I wonder if we could add any unit tests that will help us to avoid this regression in the future? (although not a blocker for this PR if it becomes too complicated).

---

Also, while testing the fix to `CustomGradientPicker` in Storybook, I noticed a couple of other unrelated issues:

**Focus Management**

It looks like the "gradient bar" is blurred when the component is mounted. As a result, clicking on the gradient bar opens the `ColorPicker` in a `Popover` that is also blurred out.

https://user-images.githubusercontent.com/1083581/170501602-681b0247-ccc1-46ab-8f45-962f767694d2.mp4


**Position and "clickability" of color stops**

I also noticed that, when clicking on the gradient bar to add a color stop:

- it's impossible to add a color stop in proximity of the pre-existing start/end color stops — the "+" simply doesn't appear and clicking doesn't do anything (although I'm not sure if this is by design)
- when the "+" icon appears on hover the gradient bar, I noticed that the icon's position doesn't track perfectly the cursor. This behaviour is more visible as the cursor moves _away_ from the middle and towards the left or the right of the gradient bar. It gets to a point where the "+" icon appears, but clicking with the mouse doesn't fire on the icon (because of its offset)

https://user-images.githubusercontent.com/1083581/170501940-e5c840c6-ea26-49fb-9e42-a58b763cee8f.mp4

I'll wait for confirmation of other folks with regard to these potential bugs, and then I'll proceed to open any potential issues

File: packages/components/src/custom-gradient-picker/utils.js (hunk 1 above)
Comment (andrewserong) [reply packages/components/src/custom-gradient-picker/utils.js:78]: It was erroring when the component is first loaded if you navigate to `?path=/story/components-customgradientpicker--default` and open up the console. I think in the story for this component, when it's initially mounted it doesn't yet have any position settings which caused the issue. We should probably also update the story, but making this function a little more tolerant to empty values was a quick win 🙂

**Comment by andrewserong** [comment]
Thanks for the reviews, folks! I'll merge this in shortly.

> I wonder if we could add any unit tests that will help us to avoid this regression in the future?

That's a great idea — I couldn't quite think of how to neatly unit test this, though perhaps (particularly for the Tooltip) we could look at adding tests that open a Popover close to the edge of a viewport and check that the width setting is still correct. It'd be good for us to look into some of these things separately to see what's viable!

> I also noticed that, when clicking on the gradient bar to add a color stop:

I noticed these things too. If you wouldn't mind opening up issues for them, that'd be great!

I _think_ part of the issue is with the calculation of the position of the control points — the component that's used to measure the length of the bar has some right padding or right margin that means the calculation for the `left` CSS property is slightly off, which is much more noticeable in Storybook where the component stretches to the width of the viewport instead of a much smaller container. It'd probably also be good for us to tweak how the drag behaviour works, it seems a little glitchy when we click a control point as to whether it's handled as moving the control point, or opening the popover. I'm happy to have a go at some of these tweaks next week if no-one beats me to it 🙂

**Comment by ciampo** [comment]
> That's a great idea — I couldn't quite think of how to neatly unit test this, though perhaps (particularly for the Tooltip) we could look at adding tests that open a Popover close to the edge of a viewport and check that the width setting is still correct. It'd be good for us to look into some of these things separately to see what's viable!

Yeah, that's what I had in mind — triggering the opening of the popover next to the edges of the viewport. Although I'm not sure if that's possible in an environment like `jest-dom` 🤔 

> I noticed these things too. If you wouldn't mind opening up issues for them, that'd be great!

Opened #41388 and #41390.

> I _think_ part of the issue is with the calculation of the position of the control points — the component that's used to measure the length of the bar has some right padding or right margin that means the calculation for the `left` CSS property is slightly off, which is much more noticeable in Storybook where the component stretches to the width of the viewport instead of a much smaller container. It'd probably also be good for us to tweak how the drag behaviour works, it seems a little glitchy when we click a control point as to whether it's handled as moving the control point, or opening the popover. I'm happy to have a go at some of these tweaks next week if no-one beats me to it 🙂

I also got the same gut feeling (at least for #41390) — thank you!

**Comment by andrewserong** [comment]
I've opened a follow-up for the control and insertion point positioning in: https://github.com/WordPress/gutenberg/pull/41492
