### PR TITLE
Fix navigation editor undo button being active when editor loads

### LINKED ISSUE #34802: Bogus undo and unsaved changes state
## Problem
When you open the Navigation Editor or reload the page after saving (CMD + R), the page is displayed if you have unsaved changes. It also shows the active "Undo" button, which does nothing.

## Screencast

https://user-images.githubusercontent.com/240569/133230675-08fb9bfc-e3e4-4d79-b2c9-c7bccc54f243.mp4

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #34802

The navigation editor is an entity driven editor, like the post or widget editor. But the entity that drives it is never saved, it's only a convenient in-memory entity. It also didn't have any configuration (edit: it actually presently uses the `postTypes` entity, which is a bit of a hack), which caused the undo feature in the nav editor to work differently to other editors (more details in point 2 here - https://github.com/WordPress/gutenberg/issues/34802#issuecomment-919839931).

In this PR I've made it so that the entity config is created at initialisation of the editor. As it's only a convenience entity, I don't think it makes sense to add it to the `entities.js` file. This seems like a decent alternative.

It also changes the kind and type so that the navigation post is more like a `postType` entity.

To avoid this entity making REST API calls I've added an `__experimentalNoFetch` property to it.

## How has this been tested?
1. Create a menu with menu items and save it
2. Reload the editor

Expected: The `undo` button should be disabled.

## Types of changes

Bug fix (non-breaking change which fixes an issue) 

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by talldan** [comment]
This does fix the issue, but it looks like the entity config also causes a request to an `undefined` endpoint.

It might be time to formalise the idea of an in-memory entity. What do you think @adamziel?

**Comment by talldan** [comment]
So I think the alternative to this is that we replace `useEntityBlockEditor` in the navigation editor with a new hook called something like `useInMemoryBlockEditor`. That would avoid the need for this 'stub post'.

It might be nice, but it would be a lot of work and potentially a point where errors might be introduced.

I'm not sure if there's any prior art for this kind of thing.

**Comment by Mamaduka** [comment]
> It might be time to formalise the idea of an in-memory entity. What do you think @adamziel?

I agree. We already have two editors that use "in-memory" or stub entities.

I'm just getting more familiar with the `core/data` internals, so below are just my thoughts 😄 

Maybe we can have a more general "in-memory" entity?

```js
const entity = {
	label: __( 'In Memory' ),
	name: '__experimentalInMemory',
	kind: 'root',
	transientEdits: { blocks: true, selection: true },
}
```

Can we use `entity?.baseURL` for checks instead of using a custom property? I think entities without `baseURL` shouldn't request anything, and if an endpoint is incorrect, it will return 404.

Should we move the core data changes into separate PR and add some unit tests.

Thanks for working on this, @talldan, and sorry if my comment isn't very helpful.

**Comment by talldan** [comment]
> Can we use entity?.baseURL for checks instead of using a custom property? I think entities without baseURL shouldn't request anything, and if an endpoint is incorrect, it will return 404.

Yep, that is an option. I do prefer an explicit property, because it means we're not relying on an undocumented behavior. For example, the entity system seems like it could have a default `baseURL`. If that were ever introduced by another dev, this would stop working.

> Should we move the core data changes into separate PR and add some unit tests.

Yep, happy to do that. I think I'll gather a bit more feedback on this one first.

**Comment by Mamaduka** [comment]
> For example, the entity system seems like it could have a default baseURL. If that were ever introduced by another dev, this would stop working.

That's a good point, thanks for the clarification.

**Comment by talldan** [comment]
So there was a bug with this where making the entity have the `postType` kind broke fetching pages for the block placeholder. Thanks to the e2e tests for catching that. I've switched it to be a `root` entity.

File: packages/edit-navigation/src/index.js [hunk 1]
```diff
@@ -55,6 +60,17 @@ function setUpEditor( settings ) {
...
 	registerCoreBlocks();
 
+	// Set up the navigation post entity.
+	dispatch( coreStore ).addEntities( [
+		{
+			kind: NAVIGATION_POST_KIND,
+			name: NAVIGATION_POST_POST_TYPE,
+			transientEdits: { blocks: true, selection: true },
+			label: __( 'Navigation Post' ),
+			__experimentalNoFetch: true,
```
Comment (getdave) [inline packages/edit-navigation/src/index.js:70]: Let's add a comment here to explain (briefly) why we do this.

**Review by getdave — APPROVED** [review]
I tested this and 

✅ There are no `undo/redo` states on reload.
✅ There are no erroneous network requests.

It would seem reasonable to me to add this experimental entity prop. It is after all "experimental" and so if we decide to formalise the concept of an in-memory entity later, we can remove it.

**Comment by adamziel** [comment]
> It might be time to formalise the idea of an in-memory entity. What do you think @adamziel?

Short term as an experimental thing, for sure, let's go for it.

Longer-term, I'm leaning more towards removing in memory post entirely, and editing the menu and menu item entities directly. I had a chat with @noisysocks about that, and we're not sure how much effort would be involved. It would couple the block with the entities directly, which means we wouldn't have to do much transforming and diffing on save. I'm not sure if that's good or bad yet, but sounds like an attractive simplification.

Let's explore, document what we learn, and regroup then.

**Comment by talldan** [comment]
The tricky part is the top level `useEntityBlockEditor` which seems to expect a post style entity with a `content` property. The post editor has posts, the site editor has templates. Menus are stored as `terms` though, and don't really have content.

Definitely agree that it'd be good to explore `useEntityProp` for menu items, that seems like a great fit already and it would help with some of the diffing that currently happens on saving.

We should probably make an issue to discuss this in the context of both widgets and menus so that both editors don't end up with completely different implementations.
