### PR TITLE
Do not focus new navigation block menu until loading is finished

### LINKED ISSUE #59771: Fix focus loss regression in menu creation
### Description

https://github.com/WordPress/gutenberg/pull/59630 introduced a regression that is now in core for WP 6.5 so this would need to be addressed for the release.

Previously:
In a navigation block, when clicking the 'Create new menu' in the dropdown in the inspector:
- The menu immediately closed.
- Focus was moved back to the ellipsis toggle button.

Thie made sure there was no focus loss.

After https://github.com/WordPress/gutenberg/pull/59630
- The dropdown menu stays open.
- All the menu items in the dropdown get disabled, not sure why.
- When using a keyboard, the 'Create new menu' item has focus but it gets disabled so there is a focus loss.
- After the menu is created, the dropdown closes ad focus is lost.

I'm not sure wjy the menu stays open in the first place, this doesn't seem to be the best user scperience.
Anyways, keeping the menu open _and_ disabling all its menu items doesn't allow the menu built-in focus management to work properly.

See animated GIF below to better illustarate the focus loss.

### Step-by-step reproduction instructions

- Go to the Site editor and edit a Navigation block.
- In the settings panel (the inpector) use the keyboard to tab to the ellipsis button after the title 'Menu'.
- Press Enter to open the dropdown and use the arrow keys or Tab key to move focus to the 'Create new menu' button.
- Press Enter.
- Observe the menu stays open. Expected: the menu to close and focus to be moved back to the ellipsis button.
- Observe all items within the dropdown menu get disabled.
- Wait the new menu to be created and the dropdown to close.
- Press the Tab key.
- Observe focus is lost and, depending on the browser, th tab sequence either starts from the document root or from the top of the settings panel.

### Screenshots, screen recording, code snippet

focus loss

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by jeryj**
Fixes https://github.com/WordPress/gutenberg/issues/59771

When a new navigation is created, we place focus on the navigation block. If we place focus while loading is still happening, focus will be lost when focus the loading is finished and the block gets replaced with the new content.

Instead of replacing the entire nav HTML element, just replace the inner part of it so focus is not lost.

## Testing Instructions

- Go to the site editor
- Click a navigation block
- Open block settings
- Above the navigation tree click the dot menu in the top right
- Click "Create new menu"
- When loading is finished, press the down arrow key
- Focus should be on the navigation block appender

### CODE REVIEW

**Review by draganescu — APPROVED** [review]
This makes perfect sense to me and it also fixes the original issue.

**Review by draganescu — DISMISSED** [review]
There seems to be an issue with importing classic menus, looking into it.

**Comment by draganescu** [comment]
I pushed a commit fixing the focus for importing. But I also am able to break the block somehow by fiddling with import/delete and this only happens here not on trunk.

**Comment by draganescu** [comment]
Found this problem:


https://github.com/WordPress/gutenberg/assets/107534/5aa1729a-7bba-472a-a521-9f74d7a51faa

File: packages/block-library/src/navigation/edit/index.js [hunk 1]
```diff
@@ -342,16 +342,7 @@ function Navigation( {
...
-			classicMenu.id,
-			classicMenu.name,
-			'draft'
-		);
-		if ( navMenu ) {
-			handleUpdateMenu( navMenu.id, {
-				focusNavigationBlock: true,
-			} );
-		}
+		await convertClassicMenu( classicMenu.id, classicMenu.name, 'draft' );
```
Comment (getdave) [inline packages/block-library/src/navigation/edit/index.js]:
```suggestion
		return convertClassicMenu( classicMenu.id, classicMenu.name, 'draft' );
```

No need to return await inside an `async` function as it will _always_ return a `Promise`.

File: test/e2e/specs/editor/blocks/navigation-list-view.spec.js [hunk 2]
```diff
@@ -543,6 +543,50 @@ test.describe( 'Navigation block - List view editing', () => {
...
+		// Move focus to the appender
+		await page.keyboard.press( 'ArrowDown' );
+		await expect( editor.canvas.getByLabel( 'Add block' ) ).toBeFocused();
+
+		// Make sure it's a nav block appender. If it is, the linkControl search input will be opened on enter.
+		await page.keyboard.press( 'Enter' );
+
+		// Expect to see the Link creation UI be focused.
+		const linkUIInput = linkControl.getSearchInput();
+		await expect( linkUIInput ).toBeFocused();
```
Comment (getdave) [inline test/e2e/specs/editor/blocks/navigation-list-view.spec.js]: As this behaviour might change in future, would it be possible to scope the selector for the `Add block` to be relative to the Navigaiton block.

So in pseudo code

`editor.canvas.getNavBlock().getByLabel('Add block')`

**Review by getdave — COMMENTED** [review]
Quick code review

**Comment by jeryj** [comment]
Thanks for the reviews and fixes, @draganescu and @getdave! This is ready for another review.

**Comment by jeryj** [comment]
The failed e2e tests pass locally. Rerunning.

**Review by getdave — APPROVED** [review]
I tested and this and the behaviour was as described and expected.

In the longer term, I'm wondering whetehr it would probably be better to have focus remain in the sidebar where you invoked the "Create" action. But for now this manages focus in a much better way and resolves the bug.

Great work 👏

**Comment by getdave** [comment]
This PR should be included in the WordPress 6.5 release during the RC phase. The bug was identified during the RC cycle and represents a focus loss issue which could make navigating the editor very difficult for users of assistive tech.

**Comment by youknowriad** [comment]
I just cherry-picked this PR to the update/packages-rc2-6.5 branch to get it included in the next release: 1d93d989676
