### PR TITLE
Fix/media library collections #4612

### LINKED ISSUE #4612: Media Library doesn't update after dragging image onto Image block
## Issue Overview
After inserting an Image block, I then dragged 'n dropped an image directly onto the block. I then inserted another image block and after clicking the _Add from Media Library_ button, and displaying the Media popup window, the previous image that I added to the page isn't displaying in the Media Library.

New image that I dragged onto Image Block
gutenberg-imgblockdragdrop

Newly added image not appearing in Media LIbrary
gutenberg-imgnotinlibrary

## Steps to Reproduce (for bugs)
1. Insert Image block
2. Drag 'n drop image onto Image block
3. Insert new Image block
4. Click the _Add from Media Library_ button and try to add the same image. You can't, because it doesn't appear in the Media Library

## Expected Behavior
If I drag'n drop an image onto an Image BLock, this should get added to my Media LIbraray, and should be displayed when I try to add another image by viewing the Media Library popup

## Current Behavior
Images dragged onto Image Block aren't reflected in Media Library popup window

_Firefox Quantum 57.0.4 (64-bit)
Gutenberg 2.0.0
WordPress 4.9.2
No other plugins activated_

### PR DESCRIPTION
**Pull request by antpb**
## Description
Fixes #4612.

We need to refresh the collection when a user uploads media outside of the Media Library workflow (i.e. file drops, file uploads, others?) 

This adds a refresh of the collection after finishing uploading media via REST API fixing #4612

1. Insert 1st Image Block
2. Drag image to 1st block
3. Insert 2nd Image Block
4. Click Add from Media Library button on 2nd block (The first image you dragged will most likely show)
5. Close Popup window
6. Drag new image to 2nd block
7. Insert 3rd Image block
8. Click Add from Media Library button on new block (Image that was last dragged should now appear!)

based on @jorgefilipecosta 's closed PR : https://github.com/WordPress/gutenberg/pull/6390

### CODE REVIEW

File: packages/editor/src/utils/media-upload/media-upload.js [hunk 1]
```diff
@@ -31,7 +31,8 @@ import { __, sprintf } from '@wordpress/i18n';
  * https://bugs.chromium.org/p/chromium/issues/detail?id=227004
  *
  * @param {?Object} wpMimeTypesObject Mime type object received from the server.
- *                                    Extensions are keys separated by '|' and values are mime types associated with an extension.
+ *                         	// Create upload payload
```
Comment (jorgefilipecosta) [inline packages/editor/src/utils/media-upload/media-upload.js]: Hi @antpb, I'm not seeing the relation between this changes and the PR, were they intentional or I'm missing something?

File: packages/edit-post/src/hooks/components/media-upload/index.js [hunk 2]
```diff
@@ -199,7 +199,21 @@ class MediaUpload extends Component {
 		}
 	}
 
+	updateCollection() {
+		const frameContent = this.frame.content.get();
+		if ( frameContent ) {
+			const collection = frameContent.collection;
+			// clean all attachments we have in memory.
+			collection.toArray().forEach( ( model ) => model.trigger( 'destroy', model ) );
```
Comment (jorgefilipecosta) [inline packages/edit-post/src/hooks/components/media-upload/index.js]: Hi @antpb, If I'm not in error I think @aduth  suggested me during the tries of https://github.com/WordPress/gutenberg/pull/6390 that a possible improvement would be destroying the models when the modal Closes. This would have the advantage of only keeping models in memory when they are needed.

**Review by jorgefilipecosta — COMMENTED** [review]
Thank you @antpb for taking a look at this issue and reviving this fix. I left a comment with a possible improvement.

File: packages/edit-post/src/hooks/components/media-upload/index.js (hunk 2 above)
Comment (antpb) [reply packages/edit-post/src/hooks/components/media-upload/index.js]: @jorgefilipecosta thanks for that. Is the updated code more what you are saying here? I added a `destroyCollection` function to trigger in `onClose`. Doing the destroy on close and doing the `collection.more();` in updateCollection. 

In my local it seems to be working as intended. :)

Comment (antpb) [reply packages/edit-post/src/hooks/components/media-upload/index.js]: I was doing some testing of having the collection destroyed at `onClose` now when you select a media item using the Media Library button, it does not return back the data needed because onClose it is clearing the collection. I think we need to keep the process of destroying and requesting new items in `updateCollection`

**Review by jorgefilipecosta — COMMENTED** [review]
Hi @antpb the end 2 end tests in CI are failing, I think the failures are not related to this changes. Would it be possible to rebase this branch so we can check if the failure persists?

**Comment by jorgefilipecosta** [comment]
I think this PR will also close I think closing this issue will also close https://github.com/WordPress/gutenberg/issues/11567.

**Comment by gziolo** [comment]
@jorgefilipecosta, can you help to fix e2e test? It looks like this PR is based on your prior work.

**Comment by gziolo** [comment]
Well, I triggered another build for e2e tests, will double check them locally, too.

**Comment by gziolo** [comment]
It works as advertised. e2e tests are green. Let's get it in.

**Review by gziolo — APPROVED** [review]

**Comment by youknowriad** [comment]
This PR have been reverted in #12064 because the e2e tests were failing in master which was blocking the other PRs. I'm certain this the failure is minor but I wasn't able to reproduce locally to fix it. I also reopened the original issue. Let's make sure we recommit this PR back and see how to fix the tests. Thanks for your understanding.

**Comment by jorgefilipecosta** [comment]
I submitted a new version of this PR which should address the reason why the end 2 end tests failed https://github.com/WordPress/gutenberg/pull/12074.
