### PR TITLE
Fix alignment when viewing a DataView with table layout and non-default column alignment

### LINKED ISSUE #73397: Alignment issue when viewing a DataView with table layout and non-default column alignment
### Description

When applying a non-default alignment to a Dataview column in the table layout, the header element's spacing becomes misaligned with the rest of the data in that list. 

A similar misalignment exists for the `center` align value, but this is harder to notice due to its minimal impact, resulting in a few pixels off.

### Step-by-step reproduction instructions

1. Run `npm run storybook:dev`.
2. Navigate to DataViews examples.
3. Edit the default view and specify `layout.styles.[column].align = end` (and `center`). For example,  the screenshots below have the following view configured:

```js
const [ view, setView ] = useState< View >( {
		...DEFAULT_VIEW,
		fields: [ 'categories' ],
		titleField: 'title',
		descriptionField: 'description',
		mediaField: 'image',
		layout: {
			styles:
				{
					categories: {
						align: 'end', // 'center'
					},
				},
			},
		} );
```` 

### align: end

|||
|---|---|
|Image|Image|

### align: center

Image

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by xristos3490**
## What?

When applying a non-default alignment to a Dataview column in the table layout, the header element's spacing becomes misaligned with the rest of the data in that list.

Closes #73397

## Why?

Alignment needs to be on point.

## How?

This PR does the following:
- Adds two new class names to the header element: `dataviews-view-table__header-align-{end, center}`
- Removes the inline `textAlign` style.
- Introduces CSS to control the spacing and text alignment within the newly added class names.

### Testing Instructions for Keyboard

- Run `npm run storybook:dev`.
- Navigate to DataViews examples.
- Edit the default view and specify `layout.styles.[column].align = end` (and `center`). The screenshots below have the following view configured:
```js
const [ view, setView ] = useState< View >( {
		...DEFAULT_VIEW,
		fields: [ 'categories' ],
		titleField: 'title',
		descriptionField: 'description',
		mediaField: 'image',
		layout: {
			styles:
				{
					categories: {
						align: 'end', // 'center'
					},
				},
			},
		} );
```

### Align:end

|Before|Before(Hover)|
|-|-|
|Screenshot 2025-11-18 at 5 43 16 PM|Screenshot 2025-11-18 at 5 43 24 PM|

|After|After(hover)|
|-|-|
|Screenshot 2025-11-18 at 5 46 03 PM|Screenshot 2025-11-18 at 5 46 10 PM|

### Align:center

|Before|After|
|-|-|
|Screenshot 2025-11-18 at 5 45 17 PM|Screenshot 2025-11-18 at 5 45 38 PM|

### CODE REVIEW

**Comment by oandregal** [comment]
I tested this a bit and this is what I found:

- The `title` ("primary column") is unaffected by the alignment. This also happens in `trunk`. @xristos3490 is this something you could take a look at as a follow-up? I don't think that's intentional.
- Columns that render buttons (all but actions) are now properly aligned at the end.

| Before | After |
| --- | --- |
| Screenshot 2025-11-18 at 18 08 04 | Screenshot 2025-11-18 at 18 03 19 |

File: packages/dataviews/src/dataviews-layouts/table/index.tsx [hunk 1]
```diff
@@ -469,11 +469,16 @@ function ViewTable< Item >( {
 							return (
 								<th
 									key={ column }
+									className={ clsx( {
```
Comment (oandregal) [inline packages/dataviews/src/dataviews-layouts/table/index.tsx]: This works. It's so similar to https://github.com/WordPress/gutenberg/issues/73385 where @jameskoster suggested a different approach (introduce an unstyled button variant, so that the container would control the spacing of buttons), that I'd rather ask what your thoughts are on this, James.

Comment (jameskoster) [reply packages/dataviews/src/dataviews-layouts/table/index.tsx]: I don't think it would hurt to merge something like this in the short-term. But yes, this button is already applying custom styles which suggests an unstyled button variant would be useful.

File: packages/dataviews/src/dataviews-layouts/table/style.scss [hunk 2]
```diff
@@ -163,6 +163,18 @@
 			&:has(.dataviews-view-table-header-button):not(:first-child) {
 				padding-left: $grid-unit-05;
```
Comment (jameskoster) [inline packages/dataviews/src/dataviews-layouts/table/style.scss:155]: If we just added `padding-right: $grid-unit-05;` here would that solve the issue without all the extra logic and CSS?

**Comment by xristos3490** [comment]
Thank you, @oandregal and @jameskoster, for the swift reviews!

Following James's suggestion, I went with a more straightforward, CSS-based approach to fix this, which seems to cover all cases:

#### Case A: No primary columns
|First column end-aligned|First column start-aligned|
|-|-|
|Screenshot 2025-11-19 at 12 33 56 PM|Screenshot 2025-11-19 at 12 34 24 PM|
#### Case B: No actions column
Screenshot 2025-11-19 at 12 38 00 PM

- Classnames are removed at: https://github.com/WordPress/gutenberg/pull/73398/commits/5fe3e0b3c15bdd0053a5f2f45f583d7cd42fe8c7
- CSS fixes at: https://github.com/WordPress/gutenberg/pull/73398/commits/1b8c55334a69f4ac59f8ff86cf99c8dfe633ffdc

Can you please take another look? Thanks!

> The title ("primary column") is unaffected by the alignment. This also happens in trunk. @xristos3490 is this something you could take a look at as a follow-up? I don't think that's intentional.

Nice catch, André! Happy to follow up on this! 🙇

File: packages/dataviews/src/dataviews-layouts/table/style.scss (hunk 2 above)
Comment (xristos3490) [reply packages/dataviews/src/dataviews-layouts/table/style.scss:155]: Ah, I appreciate the clear thinking, @jameskoster! I tried this out, but it actually breaks the rules' specificity when handling the first and last child—such as when (a) the table has no primary column or checkboxes, and (b) there are no actions, causing a regular column to be placed to the last child.

This exploration also made me realize that the current approach won't work as expected in the aforementioned (b) case.

See:
b-case-miss

However, we could modify the header-specific rules to make this work without adding any extra classes. I took a stab at this [here](https://github.com/WordPress/gutenberg/pull/73398#issuecomment-3552075840).

File: packages/dataviews/src/dataviews-layouts/table/style.scss [hunk 3]
```diff
@@ -155,13 +147,33 @@
...
+				}
+			}
+
+			&:has(.dataviews-view-table-header-button):first-child {
+				padding-left: $grid-unit-60;
+
+				.dataviews-view-table-header-button {
+					margin-left: - #{$grid-unit-10};
+				}
+			}
```
Comment (jameskoster) [inline packages/dataviews/src/dataviews-layouts/table/style.scss:166]: Instead of a negative margin could it make sense to just set the left padding to `$grid-unit-50`? 🤔

Comment (xristos3490) [reply packages/dataviews/src/dataviews-layouts/table/style.scss:166]: This is a spot-on suggestion, @jameskoster! I believe I carried over the negative margin from before, where we were setting the padding for both table cells and headers. Simplified the rules, and it works as expected in my testing. Also added a few comments to clarify; not sure about the comments policy, happy to remove them to keep it clean. 

Done in https://github.com/WordPress/gutenberg/pull/73398/commits/eba86ee211bfa045cd63dffd8a8de010e2bcc980

While testing this, I realized the compact density needed a small fix too, which I added here: https://github.com/WordPress/gutenberg/pull/73398/commits/128db1293fb29e0ab8f591b37654f51db751e33b

See:

|Before|After|
|-|-|
|Screenshot 2025-11-19 at 3 48 56 PM|Screenshot 2025-11-19 at 3 49 10 PM|

Comment (jameskoster) [reply packages/dataviews/src/dataviews-layouts/table/style.scss:166]: It's pretty hard to keep track of what some of these styles are for, so I think the comments are a great idea.

**Review by oandregal — APPROVED** [review]

**Comment by oandregal** [comment]
Thanks for the changes here @xristos3490 There's some conflicts with the changelog, so you need to rebase this PR. I'll be happy to merge it afterwards!

**Comment by xristos3490** [comment]
Rebased in https://github.com/WordPress/gutenberg/pull/73398/commits/49e9b64363055cd6aa64ae71374c92f4a1ea4a8a, @oandregal! Thanks for the reviews, folks! 🙇

**Comment by oandregal** [comment]
Congrats on your 1st PR merged, @xristos3490 You're welcome to send many more :)

**Comment by PanosSynetos** [comment]
Congrats Chris - Onwards and upwards!
