### PR TITLE
Autocomplete: fix double popover

### LINKED ISSUE #32986: Sticky autocomplete
Using the Gutenberg 10.9.0 plugin and Twenty Nineteen I get a sticky autocompleter when editing a post consisting of a single `@`. Once the autocompleter has appeared it doesn't disappear until I press space.

screencast 2021-06-25 12-52-23

This is in contrast to earlier versions of Gutenberg (maybe <10.7.0) where the autocompleter disappeared.

WordPress 5.7.2 / Chrome 91.0.4472.106 / Gutenberg 10.9.0 plugin

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Introduced in #31718. Fixes https://github.com/WordPress/gutenberg/issues/32986.

The popover is rendered twice, once inside the rich text tag and once outside. One of the popovers is removed when rich text is deselected, but the other is not.

I removed the popover that is rendered outside the tag and added a condition (for selection) for the second popover that is rendered in the tag. In other words, previously there was an `isSelected` check, which is now missing.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by johngodley — APPROVED** [review]
This solves the problem described in #32986. A 👍  from me. Thanks for the quick fix!

**Review by fullofcaffeine — APPROVED** [review]
This tests well! Thanks!

File: packages/components/src/autocomplete/index.js [hunk 1]
```diff
@@ -377,12 +377,13 @@ function useAutocomplete( {
...
 		? `components-autocomplete-item-${ instanceId }-${ selectedKey }`
 		: null;
+	const hasSelection = record.start !== undefined;
 
 	return {
 		listBoxId,
 		activeId,
 		onKeyDown: handleKeyDown,
-		popover: AutocompleterUI && (
+		popover: hasSelection && AutocompleterUI && (
```
Comment (fullofcaffeine) [inline packages/components/src/autocomplete/index.js:386]: Could you elaborate a bit more (maybe in the PR description) on why adding this short-circuit here fixed the issue and/or what was in https://github.com/WordPress/gutenberg/pull/31718 that introduced it, specifically?

**Comment by ockham** [comment]
The failing e2e test is unrelated, is has been failing for a while on other PRs (and `trunk` merges), e.g. https://github.com/WordPress/gutenberg/runs/2915343279

File: packages/components/src/autocomplete/index.js (hunk 1 above)
Comment (ellatrix) [reply packages/components/src/autocomplete/index.js:386]: Sure. Added some more explanation.

**Comment by fullofcaffeine** [comment]
Cherry-picked to `release/10.9`.
