### PR TITLE
Data: Implement atomic stores

### LINKED ISSUE #26849: Replace hand-picked redux concepts with react hooks...?
**Could we do away with most redux concepts that we use today, and instead rely on React hooks?**

_This is an audacious proposal directly building up on findings from [26692](https://github.com/WordPress/gutenberg/pull/26692). Not much thought given to cost/benefit analysis yet but the amount of work involved is potentially huge. Even if this ends up not being pursued, having a discussion would be beneficial anyway. Let's talk!_

Our redux actions and selectors have complex needs such as invoking side-effects or actions and selectors from other stores. To enable these interactions, we have concepts like:

* Registry selectors
* yield anotherAction()
* Async actions, controls, thunk middleware

At the same time,  we do all this things in React components using:

* useSelect
* useDispatch
* useEffect and promises

I wonder - what are the advantages of using the former over the latter? These ideas seem to be interchangeable, only using both means more code paths to maintain plus twice the learning and a higher barrier of entry. Let’s see how React hooks could replace the existing concepts side by side:

### Actions with yield

These two seem to be equivalent and interchangeable:

```js
export function* undo() {
	const undoEdit = yield controls.select( 'core', 'getUndoEdit' );
	if ( ! undoEdit ) {
		return;
	}
	yield {
		type: 'EDIT_ENTITY_RECORD',
		...undoEdit,
		meta: {
			isUndo: true,
		},
	};
}
```

```js
export function useUndo() {
    const undoEdit = useSelect( select => select('core').getUndoEdit() );
    const { editEntityRecord } = useDispatch( 'core' );
    const undo = useCallback(() => {
        if( ! undoEdit ) {
            return;
        }
        editEntityRecord( {
            ...undoEdit,
            meta: {
                isUndo: true
            }
        } );
    }, [ undoEdit ]);
    return undo;
}
```

Only with the latter one doesn’t need to know about generators, controls, or dispatching actions inline.

### Controls

Similarly, controls seems to exist just to handle the async behavior and grant access to different stores. Consider the `yield controls.select( 'core', 'getUndoEdit' );` part of the undo action above. This is the underlying select control:

```js
// controls.js:
export const builtinControls = {
	[ SELECT ]: createRegistryControl(
		( registry ) => ( { storeKey, selectorName, args } ) =>
			registry.select( storeKey )[ selectorName ]( ...args )
	),
  // ...
}
```

With hooks, this control wouldn’t be required at all - its role would be fulfilled by `useSelect()`. The same goes for `controls.dispatch`.

### Async controls

How about async controls, for example `apiFetch`? I find this:
```js
export function* deleteEntityRecord( kind, name, recordId, query ) {
	/* ... */
	deletedRecord = yield apiFetch( {
		path,
		method: ‚DELETE’,
	} );
	/* ... */
```

To be the same as this:
```js
export function useDeleteEntityRecord() {
	/* ... */
	return useCallback(async ( kind, name, recordId, query ) => {
		/* ... */
		await apiFetch( {
			path,
			method: ‚DELETE’,
		} );
		/* ... */
	});
}
```

In this case `yield` turned out to really be just a reimplementation of  `await` - we „hack” generators to simulate async behavior. Actions invoke other actions that are really controls, a middleware (?) calls the control handler, and then the handler waits for the actual promise. Why not remove the indirection and `await` for the promise directly?

### Registry selectors

This registry control:

```js
// component.js:
const postContent = useSelect(
	( select ) => select( 'core/editor' ).getEditedPostContent(),
	[]
);

// selectors.js:
export const getEditedPostContent = createRegistrySelector(
	( select ) => ( state ) => {
		const postId = getCurrentPostId( state );
		const postType = getCurrentPostType( state );
		const record = select( 'core' ).getEditedEntityRecord(
			'postType',
			postType,
			postId
		);
		// ...
	}
);
```

Seems to be just this hook in disguise:

```js
// component.js:
const postContent = useEditedPostContent();

// hooks.js
export const useEditedPostContent = () => {
	const { postId, postType, record } = useSelect( select => {
		const postId = select('core/editor').getCurrentPostId();
		const postType = select('core/editor').getCurrentPostType();
		const record = select( 'core' ).getEditedEntityRecord(
			'postType',
			postType,
			postId
		);
		return { postId, postType, record };
	});
	// ...
} );
```

### Resolvers

Resolvers are particularly interesting. I didn’t quite figure out all the code paths that are running in order to make them work just yet, but it seems like this controls plays an important role:

```js
[ RESOLVE_SELECT ]: createRegistryControl(
	( registry ) => ( { storeKey, selectorName, args } ) => {
		const method = registry.select( storeKey )[ selectorName ]
			.hasResolver
			? '__experimentalResolveSelect'
			: 'select';
		return registry[ method ]( storeKey )[ selectorName ]( ...args );
	}
)
```

I imagine that without controls, a canonical `useSelect` hook could be used to explicitly trigger the resolution when needed.

### Public API

One downside of react hooks is that one could no longer call `wp.data.select( 'x' ).myFunc()` as easily. Or is it true? This isn't fully fleshed out yet, but I imagine exploring "bridge layer" could yield a solution:

```js
const PublicApiCompat = memo(() => {
    useSelect(select => window.wp.data.select = select);
})
```

### Other considerations

* `@wordpress/redux-routine` would go away entirely.
* At least some redux middlewares would go away.
* Concepts of async actions, controls, registry selectors would all go away.
* All that’s left would be pure reducers, pure selectors, and pure action creators. Other than that, the logic would live in hooks.
* The code would be more approachable by new contributors.
* Using hooks would improve debugging. Currently with async generators stack traces aren’t always informative plus stepping through the code is challenging.
* A nice side-effect of this would be that it would remove the concept of registry selectors and thus make store-specific selectors possible.
* *It would break BC big time*, unless of course we can build a „compatibility layer” to keep the existing API in place but really call the new one under the hood.

### Anything else?

Am I missing anything? Is there anything that makes this a blunder or a technical impossibility? Really curious to learn what does everyone think. cc @noisysocks @draganescu @youknowriad @mtias @talldan @tellthemachines @gziolo @nerrad @jorgefilipecosta @ellatrix @kevin940726 @azaozz @aduth @nosolosw

### PR DESCRIPTION
**Pull request by youknowriad**
This PR is an attempt to solve some of the current flaws of the data module:

- Creating async stores with resolvers + controls + actions + selectors + reducer is very hard. Luckily we don't have much stores like that (just one), but it's definitely something that I hope we can improve.
- Improve the performance at scale: Redux (whether you subscribe to just one store or multiple) doesn't scale very well. If you keep rendering a growing list of components on a page (say a block list), these components will add computation time regardless of whether they rerender or not. In a block list for instance, no matter if the components of that blocklist subscribe to just a single store say 'core/block-editor', for each change of any block, they'll still have to call the selectors that power these components and that's way too much. We did introduce the async mode which "solves" this issue or more exactly "hides" this issue but I believe we can do better there.

--- 

- the performance factor is an important one, I'd like for our applications to scale properly when we render more and more components. This can be solved by making sure components only "subscribe" to the data they're interested in. Tools like mobx, recoil and the like solve this by relying on observables basically (atoms are just hidden observables).

 - Recoil and [jotai](https://github.com/pmndrs/jotai) also have very interesting ways to define async behavior and data which can be used as a replacement for selectors + resolvers + controls + async actions. Reducing the number of concepts would make it easier to create these kinds of stores. It's a very different way of defining stores though and a mental model that requires some getting used to in the beginning but probably simpler than what we have anyway.

This is what this PR is about. It introduces a new `@wordpress/stan` package that serves as a low-level package to build atomic stores. To learn more,  read the README of the `@wordpress/stan` package in this PR.

I've refactored the keyboard-shortcuts package store as an example of how to leverage atomic stores with the data package.

Notice that this PR also makes useSelect only subscribes to the stores that are used in mapSelectToProps. This and other improvements related to atomic stores are showing a 10ms gain in terms of typing performance in this PR. This is equivalent to approximatively 25 to 30% of the time it takes to type a character in long posts.

**TODO**

 - [x] Make `@wordpress/stan` a bundled package like `icons` or `interface`

An alternative to: https://github.com/WordPress/gutenberg/pull/26724 and https://github.com/WordPress/gutenberg/pull/26692.
Related: https://github.com/WordPress/gutenberg/pull/26733
closes #26849

### CODE REVIEW

File: packages/data/src/atomic-store/index.js [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+ * External dependencies
+ */
+import { mapValues } from 'lodash';
+
+export function createAtomicStore( config, registry ) {
+	// I'm probably missing the atom resolver here
+	const selectors = mapValues( config.selectors, ( atomSelector ) => {
+		return ( ...args ) => {
+			return atomSelector(
+				registry.__unstableGetAtomResolver()
```
Comment (ntsekouras) [inline packages/data/src/atomic-store/index.js:11]: You probably meant to check its existence here and not call it, no?

Comment (youknowriad) [reply packages/data/src/atomic-store/index.js:11]: no, this is correct actually, it's a getter for the resolver but it doesn't call the resolver.

**Comment by jsnajdr** [comment]
> @gziolo requested your review on: #26866 Implement atomic stores.

Some description of what's going on would be helpful 🙂

File: packages/stan/README.md [hunk 2]
```diff
@@ -0,0 +1,208 @@
+# Stan
+
+"stan" stands for "state" in Polish 🇵🇱. It's a framework agnostic library to manage distributed state in JavaScript application. It is highly inspired by the equivalent [Recoil](https://recoiljs.org/) and [jotai](https://jotai.surge.sh)
```
Comment (adamziel) [inline packages/stan/README.md:3]: 🎉

Comment (gziolo) [reply packages/stan/README.md:3]: 🇵🇱

**Comment by gziolo** [comment]
> > @gziolo requested your review on: #26866 Implement atomic stores.
> 
> Some description of what's going on would be helpful 🙂

It's a work in progress, you can ignore my ping for now. Documentation for the new package can be found here: https://github.com/WordPress/gutenberg/blob/98f1ba60a36d666c9c16d4771c28ca3ea7247730/packages/stan/README.md

File: packages/stan/README.md [hunk 3]
```diff
@@ -0,0 +1,208 @@
...
+```js
+// Retrieve the sum instance and adds the counter1 and counter2 atoms to the registry as well
+const sumInstance = registry.getAtom( sum );
+```
+
+One important thing to note here as well is that atoms are "lazy", which means unless someone subscribes to their changes, they won't bother computing their state. This is an important property of atoms for performance reasons. 
+
+```js
+// No one has subscribed to the sum instance yet, its value is "null"
+console.log( sumInstance.get() ); // prints null.
```
Comment (jsnajdr) [inline packages/stan/README.md:105]: This looks wrong. If I have a React component that wants to render the `sumInstance.get()` value, then even the initial render should print `3`, not `null`.

The subscription will be created only after the initial render, in a `useEffect` or `componentDidMount` callback. It can't be created anywhere else, because it's a side effect.

This is true no matter how exactly the React bindings are implemented (`@wordpress/data` adapter or anything else).

Comment (youknowriad) [reply packages/stan/README.md:105]: > This looks wrong. If I have a React component that wants to render the sumInstance.get() value, then even the initial render should print 3, not null

This is already handled properly in useSelect, we can compute the initial value before the subscription if we want. I may add a more direct way to do that with atoms: make the "resolve" a public API of the atom instance but it's very important that the atoms stay lazy. If I don't use a selector (which becomes an atom), I don't want it to keep updating its value and consuming CPU.

Comment (youknowriad) [reply packages/stan/README.md:105]: This is a good remark though, and I need to think more about how to solve this in a better way: having the laziness while allowing sync resolution for react hooks.

Comment (jsnajdr) [reply packages/stan/README.md:105]: > This is already handled properly in useSelect, we can compute the initial value before the subscription if we want.

I tested this with the following example:
```js
const count = createAtom( 1 );
const double = createDerivedAtom( ( get ) => get( count ) * 2 );

const getDouble = ( get ) => () => get( double );

registerAtomicStore( 'standa', {
	atoms: { double },
	selectors: { getDouble },
} );

function UI() {
	const dbl = useSelect( ( select ) => select( 'standa' ).getDouble() );
	return React.createElement( 'div', null, dbl );
}

const rendered = ReactDOMServer.renderToString(
	React.createElement( UI, null )
);

console.log( rendered );
```
In the end, the `double` atom is really resolved even at the time of the initial render and the example correctly renders `<div>2</div>`.

But the reason _why_ it is resolved is not great: the atoms in the atomic store are instantiated in the `data` package's own atom registry, and that registry has an `onAdd` callback that immediately subscribes to the new atom's changes and relays them to the `globalListener`. I.e., every atom has at least one subscription during its entire lifetime. That ensures that the atom is resolved in the initial render, but at the same time completely defeats the lazy optimizations.

After removing the `onAdd` and `onDelete` callbacks from the `createAtomRegistry` call (with SSR, we don't need any subscriptions anyway), the resolution of `double` is not done. The selector returns `null` on initial render.

Comment (jsnajdr) [reply packages/stan/README.md:105]: > This is a good remark though, and I need to think more about how to solve this in a better way: having the laziness while allowing sync resolution for react hooks.

The selector value should be computed when calling `.get()`. Calling the getter is a strong-enough signal that someone is interested in the value and that it's worth computing.

Comment (youknowriad) [reply packages/stan/README.md:105]: @jsnajdr it's not that simple, resolving might trigger effects (async atoms) in which case, we shouldn't resolve in render phase, I think it's more subtle and we need to figure out a way to declaratively separate async atoms from sync ones.

Comment (youknowriad) [reply packages/stan/README.md:105]: and yes, I agree the global listener is not a great idea, it's a temporary measure that I put in place for backward compatibility reasons. I'll have to think more about that and probably only subscribe to the "root" atoms there.

Comment (youknowriad) [reply packages/stan/README.md:105]: Ok, I've tried the approach you're suggestion in 0c6cd78 
it seems to work well but there's something wrong with the e2e tests. It doesn't feel related to my commit but I don't know.

Comment (youknowriad) [reply packages/stan/README.md:105]: Tests aare back to normal and we're gaining 10ms when typing in this PR (this is huge)

**Comment by youknowriad** [comment]
The API right now is a bit inconsistent.

 - The registry has the following API: `registry.read( atom )` and `registry.write( atom, value )`
 - the derived atoms has the following one: `createDerivedAtom( ( { get } ) => get( atom ), { get, set } => set( get(atom), value ) )`

We need to consolidate on a single naming: "read/write" or "get/set". not sure what's better?

File: packages/stan/README.md (hunk 3 above)
Comment (jsnajdr) [reply packages/stan/README.md]: > resolving might trigger effects (async atoms) in which case, we shouldn't resolve in render phase

It's interesting that both Recoil and Jotai run the resolvers, both sync and async ones, during `get`. I.e., during the render phase, firing the side effects right away.

That suggests that running the resolver or any side effect during render is not bad per-se. We only need to avoid doing certain things that would make it bad:
- the resolver shouldn't do any sync state updates, like setting the `isResolving` flag and triggering a `setState` by that
- the resolver shouldn't allocate any resources (e.g., make subscriptions) because they won't be cleaned up in case of aborted render
- the resolver should be resilient against running twice

Looking at Apollo Client, I see they execute the query in two phases: `queryData.execute()` during render, and then `queryData.afterExecute()` in a `useEffect` hook. Only the latter can allocate something and be sure that it will be cleaned up.

To implement a good React binding, maybe exposing only the simple `get` primitive and nothing else is not enough? The current `get` does two tasks at once: "synchronously reading the value" and "triggering the resolution". There can easily be two lower-level primitives that do that separately.

**Comment by jsnajdr** [comment]
> The registry has the following API: `registry.read( atom )` and `registry.write( atom, value )`

Why did you choose to hide the atom instances completely, allowing access only through the registry as a proxy?

An alternative is splitting the registry interface into two:
```js
registry.get( atom ).read();
registry.get( atom ).write( value );
```

File: packages/data/src/atomic-store/index.js [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+				registry.getAtomRegistry()
+			)( ...args );
+		};
+	} );
+
+	return {
+		getSelectors: () => selectors,
+		getActions: () => actions,
+		// The registry subscribes to all atomRegistry by default.
+		subscribe: () => () => {},
```
[the remark this answers is not in the document]
Comment (youknowriad) [reply packages/data/src/atomic-store/index.js:35]: because that's the API for generic stores registries support.

**Comment by youknowriad** [comment]
> Why did you choose to hide the atom instances completely, allowing access only through the registry as a proxy?

Because the concept of atom instances is a bit confusing IMO and users shouldn't have access to it. (implementation detail). I actually already have the "get" function you propose but I'm marking it unstable. 

Also, now I'm considering renaming "registry" to just "store" because it's what holds the actual state. I think it's a bit better.

File: packages/stan/README.md (hunk 3 above)
Comment (youknowriad) [reply packages/stan/README.md]: > To implement a good React binding, maybe exposing only the simple get primitive and nothing else is not enough? The current get does two tasks at once: "synchronously reading the value" and "triggering the resolution". There can easily be two lower-level primitives that do that separately.

Yes, I agree, I think there's value in "execute" and "afterExecute" to handle things like resolution state... but I believe we can start with the current API and see later. The important thing is to ensure `@wordpress/stan` remains an internal package (like icons and interface) where we're able to make breaking changes. (I'll update the building to do that)

Comment (jsnajdr) [reply packages/stan/README.md]: > but I believe we can start with the current API and see later.

My perspective is that I'd like to implement something like React Query on top of the `stan` store. That means maintaining mainly collections rather than individual atomic values, performing CRUD operations on them, acknowledging that these operations can fail and having first-class support for error handling, having control over the cache ("invalidating resolution" in the language of `@wordpress/data`)...

Recoil or Jotai provide some basic support for that, but I feel I'd quickly hit a wall when trying to implement some of the more complex requirements.

**Comment by jsnajdr** [comment]
> Because the concept of atom instances is a bit confusing IMO and users shouldn't have access to it.

The concept still needs to be a part of the programmer's mental model, doesn't it? They need to know that `createAtom` only "declares" an atom, something like a `class`, and it's only really "created" in a store. If I don't have access to the concept of atom instance, I can't even describe in English what the library does. That suggests it's not an implementation detail, but a part of the public description.

File: packages/stan/README.md (hunk 3 above)
Comment (youknowriad) [reply packages/stan/README.md]: yes, that's definitely where we'll see the most complex use-cases :) (basically, how to write core-data with stan).
I believe as is right now, it will provide a lot of good for performance for things like block-editor store but handling the complexities of something like `core-data` is still something that need to be tested.

**Comment by youknowriad** [comment]
Here's how I see the mental model evolving.

 - The store holds the state of all atoms.
 - I want to retrieve the value of an atom, I call  `store.read( atom )`
 - I want to update the value of an atom, I call `store.write( atom, value )`
 - I want to be notified about the change of the value of an atom, I call `store.subscribe( atom, listener )`

Note that I didn't use "atom state" here at all, I just  used "value of an atom" or "state of an atom", I believe it's simpler to understand that way.

Basically, for someone familiar with redux stores, the difference would be that the store holds states per atoms and not just a global state. In this mental modal, the atom is an "identifier".

**Comment by youknowriad** [comment]
Regardless though, we still need to figure out if use read/write or get/set for the APIs :P

File: packages/data/src/components/use-select/index.js [hunk 5]
```diff
@@ -75,42 +57,50 @@ const renderQueue = createQueue();
...
-	const latestMapSelect = useRef();
-	const latestIsAsync = useRef( isAsync );
-	const latestMapOutput = useRef();
-	const latestMapOutputError = useRef();
-	const isMountedAndNotUnsubscribing = useRef();
-
-	let mapOutput;
+	const [ , dispatch ] = useState( {} );
+	const rerender = () => dispatch( {} );
+	const isMountedAndNotUnsubscribing = useRef( true );
```
Comment (jsnajdr) [inline packages/data/src/components/use-select/index.js:70]: There is a package called [use-subcription](https://www.npmjs.com/package/use-subscription), directly from the React team, that provides a `useSubscription` hook for subscribing to things from React components in async mode.

It solves all the gotchas and race conditions that need to be taken care of. Using it in `useSelect` (both in this new and the legacy version) would simplify the hook tremendously, outsourcing most of the complexity. All that remains is calling `mapSelect` and memoizing it properly, and handling the "async mode" where the state updates are fired through the priority queue rather than done directly.

Comment (youknowriad) [reply packages/data/src/components/use-select/index.js:70]: Oh good reminder, I actually did try that package once of useSelect but at that time, it was causing a big loss in performance, maybe with the atoms implementation, it will be better.

**Comment by youknowriad** [comment]
I'm going to use `get/set` everywhere because it's shorter, any objection :P ?

File: packages/editor/src/components/post-title/index.js [hunk 6]
```diff
@@ -42,26 +42,30 @@ export default function PostTitle() {
...
+			return {
+				isCleanNewPost: _isCleanNewPost(),
+				title: getEditedPostAttribute( 'title' ),
+				placeholder: titlePlaceholder,
+				isFocusMode: focusMode,
+				hasFixedToolbar: _hasFixedToolbar,
+			};
+		},
+		[],
+		'test-atom'
```
Comment (jsnajdr) [inline packages/editor/src/components/post-title/index.js:67]: This third `useSelect` arg is not used. Will it be at some point?

**Comment by jsnajdr** [comment]
> I'm going to use `get/set` everywhere because it's shorter, any objection

Just that you might regret that choice later when you decide to implement the atom-state-getter `store.get( atom )` 😜

File: packages/stan/src/derived.js [hunk 7]
```diff
@@ -0,0 +1,187 @@
...
+	};
+
+	/**
+	 * @param {import('./types').WPAtomState<any>} atomState
+	 */
+	const addDependency = ( atomState ) => {
+		if ( ! dependenciesUnsubscribeMap.has( atomState ) ) {
+			dependenciesUnsubscribeMap.set(
+				atomState,
+				atomState.subscribe( refresh )
```
Comment (jsnajdr) [inline packages/stan/src/derived.js:73]: One optimization idea, not sure how impactful: currently, all derived atoms maintain subscriptions to their dependencies, even if their own consumers unsubscribed and are not longer interested in the value.

The derived atom could unsubscribe from dependencies once its own subscriber count drops to zero. Two scenarios to watch for:
- when calling `.get()`, ensure we're not returning a stale value
- there is a "dependency changed while we were resolving so we need to rerun the resolver" case that might be affected

**Comment by jsnajdr** [comment]
> Tests are back to normal and we're gaining 10ms when typing in this PR (this is huge)

Where does this gain come from? The reimplementation of `useSelect` using a derived atom? Does that impl use more granular subscriptions, even if all the stores continue to be old-fashioned Redux ones?

Or did the `keyboard-shortcuts` store get so much faster?

File: packages/editor/src/components/post-title/index.js (hunk 6 above)
Comment (youknowriad) [reply packages/editor/src/components/post-title/index.js:67]: I added it for debug, even if I find it useful. Let's remove it and keep it for another time.

**Comment by youknowriad** [comment]
> Where does this gain come from? The reimplementation of useSelect using a derived atom? Does that impl use more granular subscriptions, even if all the stores continue to be old-fashioned Redux ones?

It's  50/50 between:

 - Stores based on atoms which mean granular subscriptions 
 - And running mapSelectToProps only  once when mounting (thanks to atom resolution, we don't need to run the function another time inside useEffect)

**Comment by adamziel** [comment]
I wonder if there are any gains in making the subscriptions even more granular. For example, atom per entity type. Or even atom per entity?

**Comment by youknowriad** [comment]
> I wonder if there are any potential gains in making the subscriptions even more granular. For example, atom per entity type. Or even atom per entity record?

That's the purpose of the atomic store yes. Each selector is basically a subscription. It's how the "keyboard-shortcuts" package in this PR works but once/if we land it, we should try to do it for all stores. (It's going to be a long refactor that requires involvement from a lot of folks :)  )

**Comment by diegohaz** [comment]
Might be helpful testing this approach using https://github.com/dai-shi/will-this-react-global-state-work-in-concurrent-mode to check how it works in concurrent mode.

I was working on a similar idea that passes all of those concurrent mode tests. Here's a very simple implementation (just for reference, probably doesn't cover all use cases here): https://codesandbox.io/s/react-pubsub-state-gpc1u

It uses React state underneath, so everything would be done in the React way (async stuff would useEffect etc.). No new thing to teach/learn. On the other hand, this is also a limitation as things would only work inside React.

File: packages/stan/src/atom.js [hunk 8]
```diff
@@ -0,0 +1,37 @@
...
+			return value;
+		},
+		async resolve() {
+			return value;
+		},
+		subscribe( listener ) {
+			listeners.push( listener );
+			return () =>
+				( listeners = listeners.filter( ( l ) => l !== listener ) );
+		},
```
Comment (diegohaz) [inline packages/stan/src/atom.js:34]: I would consider using `Set` instead of an array for listeners: https://www.measurethat.net/Benchmarks/Show/9862/0/array-filter-vs-set-delete

**Comment by adamziel** [comment]
I wonder about "debuggability" - Redux devtools are a nice benefit of using redux. There is a plugin called [Recoil devtools](https://github.com/ulises-jeremias/recoil-devtools) and it _seem_  approachable - maybe it wouldn't be too hard to for/build bindings for.

**Comment by youknowriad** [comment]
@adamziel yes, I took a look at the ReduxDevTools API already and it's going to be easyish to add the integration for @wordpress/stan

**Comment by adamziel** [comment]
Also, it seems like the logic behind invalidation (`getEntityRecords.shouldInvalidate`) could now be expressed in terms of derived atoms?

**Comment by youknowriad** [comment]
> Might be helpful testing this approach using https://github.com/dai-shi/will-this-react-global-state-work-in-concurrent-mode to check how it works in concurrent mode.

This is very cool. Thanks @diegohaz for sharing. If anyone has time to perform the test with @wordpress/stan that would be great. Otherwise, I'll do it later.

**Comment by youknowriad** [comment]
@ceyhun Do you know why this PR is breaking mobile?

**Comment by adamziel** [comment]
fyi I'm experimenting with removing effect.js middleware in https://github.com/WordPress/gutenberg/pull/27006

**Comment by ceyhun** [comment]
> @ceyhun Do you know why this PR is breaking mobile?

On the Android build there's an error during `npm ci` and I'm not sure why. It should be the same on iOS build because they execute the same steps up to that point. But it's successful on the `npm ci` step on iOS and failing with a crash during runtime instead. It should've recorded a video and saved it as an artifact where we could see the error but there wasn't any. Here's the screenshot I took of the crash running locally: 



Exporting `usePrevious` in this file fixed the issue for me: https://github.com/WordPress/gutenberg/blob/b5620dc6818a9519e2e6e146b7cfaffdafa3af7a/packages/compose/src/index.native.js

**Comment by youknowriad** [comment]
Thanks @ceyhun that's very helpful.

File: packages/data/tsconfig.json [hunk 9]
```diff
@@ -0,0 +1,16 @@
...
+	"extends": "../../tsconfig.base.json",
+	"compilerOptions": {
+		"rootDir": "src",
+		"declarationDir": "build-types"
+	},
+	"references": [
+		{ "path": "../stan" },
+	],
+	"include": [
+		"src/atomic-store/*",
```
Comment (youknowriad) [inline packages/data/tsconfig.json:11]: @sirreal I tried to type that file which seems very easy, but for some reason, it's not working as expected. I could use help 😬

**Comment by youknowriad** [comment]
So this PR is not a draft anymore, it's time to get more eyes here and consider merging a first experimental version.

**Comment by youknowriad** [comment]
> Off topic: very suspicious that @wordpress/interface is bundled, although it registers a core/interface data store. If multiple packages bundle interface, that will lead to multiple instances of that store and not one shared one. 

The packages that rely on interface are exclusive: top-level packages  (edit-post, edit-site), so this can't happen.

File: packages/stan/src/derived.js (hunk 7 above)
Comment (adamziel) [reply packages/stan/src/derived.js:68]: I talked to @grzim today and he noted how utilizing Rx.js could drastically reduce the amount of code here - I know he'll want to follow-up with more details but I wanted to add this idea to the discussion early.

Comment (youknowriad) [reply packages/stan/src/derived.js:68]: My first thought here is that stan is approximatively 1.5kb now and I don't want to add Rx.js just for that. Thought it's been a long time I didn't look at that, maybe we can reuse a very small part of it.

Comment (jsnajdr) [reply packages/stan/src/derived.js:68]: Besides RxJS, there's also a [proposal to add `Observable` directly to the language](https://github.com/tc39/proposal-observable). There's one implementation that's directly in `core-js` and multiple other ones with various levels of minimalism (or maximalism). Even RxJS should be compatible with it.

Comment (adamziel) [reply packages/stan/src/derived.js:68]: I'm playing with it right now just to assess the impact on bundle size, I'll update this thread soon.

File: packages/stan/src/test/atom.js [hunk 10]
```diff
@@ -0,0 +1,27 @@
...
+		const count = createAtom( 1 );
+		const registry = createAtomRegistry();
+		const listener = jest.fn();
+		registry.subscribe( count, listener );
+		expect( registry.get( count ) ).toEqual( 1 );
+		registry.set( count, 2 ); // listener called once
+		expect( registry.get( count ) ).toEqual( 2 );
+		registry.set( count, 3 ); // listener called once
+		expect( registry.get( count ) ).toEqual( 3 );
+		expect( listener ).toHaveBeenCalledTimes( 2 );
```
Comment (adamziel) [inline packages/stan/src/test/atom.js:25]: Shouldn't the listener be called once immediately on `registry.subscribe()` and once on each `registry.set()` adding up to 3 calls in total ?

Comment (adamziel) [reply packages/stan/src/test/atom.js:25]: Ah I see, this is a design choice to defer this responsibility to `useSelect`.

**Comment by youknowriad** [comment]
Created an issue to track follow-up tasks here https://github.com/WordPress/gutenberg/issues/27109
Feel free to comment and help there, I'll be working on some of them as well.

File: .gitignore [hunk 11]
```diff
@@ -18,8 +18,9 @@ playground/dist
 .cache
 *.tsbuildinfo
 
-# Report generated from jest-junit
+# Report generated from tests
 test/native/junit.xml
+artifacts
```
Comment (gziolo) [inline .gitignore:23]: `artifacts` was added to this file in the meantime, you can delete this line or the other one.

File: package-lock.json [hunk 12]
```diff
@@ -52102,9 +52112,9 @@
 					"dev": true
 				},
 				"debug": {
-					"version": "4.3.0",
-					"resolved": "https://registry.npmjs.org/debug/-/debug-4.3.0.tgz",
-					"integrity": "sha512-jjO6JD2rKfiZQnBoRzhRTbXjHLGLfH+UtGkWLc/UXAh/rzZMyjbgn0NcfFpqT8nd1kTtFnDiJcrIFkq4UKeJVg==",
+					"version": "4.3.1",
```
Comment (gziolo) [inline package-lock.json:52115]: It needs a rebase, I guess. A similar change landed in `master`.

File: packages/data/src/atomic-store/index.js [hunk 13]
```diff
@@ -0,0 +1,69 @@
...
+
+/**
+ * WordPress dependencies
+ */
+import { createDerivedAtom } from '@wordpress/stan';
+
+/**
+ *
+ * @param {string}                                     name   Store name.
+ * @param {import('../types').WPDataAtomicStoreConfig} config Atomic store config.
```
Comment (gziolo) [inline packages/data/src/atomic-store/index.js:14]: A similar issue I had in #27061. There needs to be a `typedef` to ensure that auto-generated documentation works correctly, otherwise we see `(unknown type)` instead of  `WPDataAtomicStoreConfig`.

File: packages/data/src/atomic-store/index.js [hunk 14]
```diff
@@ -0,0 +1,69 @@
...
+ * @return {import('../types').WPDataStore} Store.
+ */
+export default function createAtomicStore( name, config ) {
+	return {
+		name,
+		instantiate: ( registry ) => {
+			// I'm probably missing the atom resolver here
```
Comment (gziolo) [inline packages/data/src/atomic-store/index.js:21]: Is it still missing or we can remove this comment? 😄

File: packages/data/src/atomic-store/index.js [hunk 15]
```diff
@@ -0,0 +1,69 @@
...
+			const selectors = mapValues( config.selectors, ( atomSelector ) => {
+				return ( /** @type {any[]} **/ ...args ) => {
+					const get = registry.__internalGetAtomResolver()
+						? registry.__internalGetAtomResolver()
+						: (
+								/** @type {import('@wordpress/stan/src/types').WPAtom<any>|import('@wordpress/stan/src/types').WPAtomFamilyItem<any>} **/ atom
```
Comment (gziolo) [inline packages/data/src/atomic-store/index.js:27]: @sirreal, would know best, but I believe there is a way to avoid using `src/types` part.

File: packages/data/src/components/with-select/test/index.js [hunk 16]
```diff
@@ -734,12 +685,8 @@ describe( 'withSelect', () => {
...
 			);
 		} );
-		// 4 times:
-		// - 1 on initial render
-		// - 1 on effect before subscription set.
-		// - 1 on re-render
-		// - 1 on effect before new subscription set (because registry has changed)
-		expect( mapSelectToProps ).toHaveBeenCalledTimes( 4 );
+
+		expect( mapSelectToProps ).toHaveBeenCalledTimes( 2 );
```
Comment (gziolo) [inline packages/data/src/components/with-select/test/index.js:689]: So many re-renders prevented 😍

File: packages/stan/package.json [hunk 17]
```diff
@@ -0,0 +1,36 @@
+{
+	"name": "@wordpress/stan",
+	"version": "0.0.1",
+	"description": "WordPress state library.",
+	"author": "The WordPress Contributors",
+	"license": "GPL-2.0-or-later",
+	"keywords": [
+		"wordpress",
+		"gutenberg",
+        "state",
```
Comment (gziolo) [inline packages/stan/package.json:10]: Some formatting issue, we should enable Prettier for `json` and `md` and fix it later 😄

File: packages/stan/package.json [hunk 18]
```diff
@@ -0,0 +1,36 @@
+{
+	"name": "@wordpress/stan",
+	"version": "0.0.1",
+	"description": "WordPress state library.",
```
Comment (gziolo) [inline packages/stan/package.json:4]: It could use a better selling description one day 😄

**Review by gziolo — COMMENTED** [review]
I finished the first pass of review for all files in preparation for merging 😄

**Comment by adamziel** [comment]
Being able to just call `get( anotherAtom )` is sure a nice syntax sugar, but we're paying for that with `didThrow = true`. It crossed my mind to statically declare dependent atoms (or via babel plugin?), but given we need to support the current signature of `useSelect()` that comes without static dependencies it would just generate branches of code to support 🤔

File: packages/stan/README.md [hunk 19]
```diff
@@ -0,0 +1,203 @@
...
+<!-- START TOKEN(Autogenerated API docs) -->
+
+<a name="createAtom" href="#createAtom">#</a> **createAtom**
+
+Creates a basic atom.
+
+_Parameters_
+
+-   _initialValue_ `T`: Initial Value in the atom. \*
+-   _config_ (unknown type): Common Atom config.
```
Comment (gziolo) [inline packages/stan/README.md:140]: This bug with autogenerated API is really annoying, let's tackle it in a follow-up.

File: packages/stan/src/registry.js [hunk 20]
```diff
@@ -0,0 +1,134 @@
...
+ * @typedef {( atomState: import('./types').WPAtomState<any> ) => void} RegistryListener
+ */
+
+/**
+ * @template T
+ * @param {import('./types').WPAtom<any>|import('./types').WPAtomFamilyItem<T>} maybeAtomFamilyItem
+ * @return {boolean} maybeAtomFamilyItem is WPAtomFamilyItem<T>.
+ */
+export function isAtomFamilyItem( maybeAtomFamilyItem ) {
+	if (
```
Comment (gziolo) [inline packages/stan/src/registry.js:16]: Could it `return` immediately instead?
```suggestion
	return (
```

Not that important though.

File: packages/stan/src/test/atom.js (hunk 10 above)
Comment (gziolo) [reply packages/stan/src/test/atom.js:25]: It might be easier to follow if there was `expect( listener ).toHaveBeenCalledTimes( 1 );` instead of code comments.

File: packages/data/src/atomic-store/index.js (hunk 14 above)
Comment (youknowriad) [reply packages/data/src/atomic-store/index.js:21]: it's fine now  :)

File: packages/data/src/redux-store/test/index.js [hunk 21]
```diff
@@ -233,4 +244,163 @@ describe( 'controls', () => {
 			);
 		} );
 	} );
+
+	describe( 'atomSelectors', () => {
+		const createUseSelectAtom = ( mapSelectToProps ) => {
+			return createDerivedAtom( ( { get } ) => {
+				const current = registry.__internalGetAtomResolver();
```
Comment (gziolo) [inline packages/data/src/redux-store/test/index.js:251]: Can you explain what is it doing? It might be nice to add a code comment here.

**Comment by youknowriad** [comment]
>  How about declaring dependent atoms statically via another argument to createDerivedAtom? This could be made easier via an eslint rule or even automated via babel plugin.

The dependencies of an atom are not static, they can change depending on the value of another dependency for instance.

File: packages/data/src/registry.js [hunk 22]
```diff
@@ -221,6 +263,16 @@ export function createRegistry( storeConfigs = {}, parent = null ) {
 		dispatch,
 		use,
 		register,
+		getStoreAtom,
```
Comment (gziolo) [inline packages/data/src/registry.js:266]: Note to myself: check why `getStoreAtom` rather than `getAtomStore` and as a consequence `atomStores`.

**Comment by youknowriad** [comment]
> Being able to just call get( anotherAtom ) even before the resolution is sure a nice syntax sugar, but we're paying for that with didThrow = true. How about declaring dependent atoms statically via another argument to createDerivedAtom? This could be made easier via an eslint rule or even automated via babel plugin.

if you really need two parallel async resolutions, Promise.all should be sufficient.

File: packages/data/src/types.d.ts [hunk 23]
```diff
@@ -27,6 +30,34 @@ export interface WPDataReduxStoreConfig {
...
 export interface WPDataRegistry {
+    /**
+     * Registers a store.
+     */
     register: ( store: WPDataStore ) => void,
+
+    /**
+     * Creates an atom that can be used to subscribe to a selector.
+     */
+    __internalGetSelectorAtom: <T> ( selector: ( get: WPAtomResolver<any> ) => any ) => WPAtom<T>
```
Comment (gziolo) [inline packages/data/src/types.d.ts:51]: Not to myself, check why `__internalGetSelectorAtom` rather than `__internalGetAtomSelector` for consistency.

**Comment by adamziel** [comment]
> if you really need two parallel async resolutions, Promise.all should be sufficient.

How would I use `Promise.all` with two derived atoms?

File: packages/keyboard-shortcuts/src/store/actions.js [hunk 24]
```diff
@@ -24,37 +34,40 @@
...
-		type: 'REGISTER_SHORTCUT',
-		name,
-		category,
-		keyCombination,
-		aliases,
-		description,
-	};
-}
+export const registerShortcut = ( config ) => ( { get, set } ) => {
+	const shortcutNames = get( shortcutNamesAtom );
```
Comment (gziolo) [inline packages/keyboard-shortcuts/src/store/actions.js:42]: Interesting, it processes multiple atoms. I like this concpet 👍 I'm curious how it scales though.

File: packages/keyboard-shortcuts/src/store/selectors.js [hunk 25]
```diff
@@ -13,6 +12,11 @@ import {
 	rawShortcut,
 } from '@wordpress/keycodes';
 
+/**
```
Comment (gziolo) [inline packages/keyboard-shortcuts/src/store/selectors.js:15]: I would feel way more comfortable if there were unit tests for those selectors, but this refactor is very straightforward so let's hope that CI is correct.

**Comment by youknowriad** [comment]
> How would I use Promise.all with e.g. two derived atoms? Can I access their .resolve functions from another derived atom?

@adamziel something like:

```
const [result1, result2] =  await Promise.all( [  fetch1(), fetch2() ] )
```

File: packages/stan/src/derived.js (hunk 7 above)
Comment (adamziel) [reply packages/stan/src/derived.js:86]: With a few Rx.js operators imported AND webpack tree shaking enabled, the size of stan goes up to 20-25kb, or 6.4kb gzipped (vs 4.9K / 1.7K gzipped before). It's not terrible, but I stumbled upon a potential roadblock. `stan` is really simple and most of the code would be necessary even if we relied on Observables, e.g. I don't see how tracking dependencies in `derived.js` could be simplified. Perhaps this library is small enough that using functional programming while exposing an imperative API is counter-productive? I imagine it would make more sense if the public API exposed observables, but this increases the barrier of entry.

File: packages/data/src/redux-store/test/index.js (hunk 21 above)
Comment (youknowriad) [reply packages/data/src/redux-store/test/index.js:251]: This is basically for "registry selectors", basically I'm retrieving the `get` function passed to the parent atom.  I think I have a comment  somewhere in the registry about that.

File: packages/data/src/types.d.ts (hunk 23 above)
Comment (youknowriad) [reply packages/data/src/types.d.ts:51]: We're creating an "atom" for the "selector" :)  (so it's  not a selector of atoms)

File: packages/data/src/registry.js (hunk 22 above)
Comment (youknowriad) [reply packages/data/src/registry.js:266]: We're creating an "atom" for the "store" :) (so it's not a store of atoms)

File: packages/keyboard-shortcuts/src/store/actions.js (hunk 24 above)
Comment (youknowriad) [reply packages/keyboard-shortcuts/src/store/actions.js:42]: it can itself be an atom if we really want to push the optimization forward and the action becomes just the shortcut to the final atom.

**Comment by adamziel** [comment]
> @adamziel something like:
> const [result1, result2] =  await Promise.all( [  fetch1(), fetch2() ] )

Right, but this assumes I'm resolving something asynchronous in my derived atom. My concern is about two asynchronous resolutions in derived atoms my atom is using. For example, I don't think I can do this:

```js
	const posts = createDerivedAtom( async ( { get } ) => { /* ... */ } );
	const pages = createDerivedAtom( async ( { get } ) => { /* ... */ } );
	const sum = createDerivedAtom( async ( { get } ) => {
		const [_posts, _pages] = await Promise.all([ get( posts ), get( pages ) ]);
	} );
```

File: packages/stan/src/derived.js (hunk 7 above)
Comment (adamziel) [reply packages/stan/src/derived.js:86]: By returning observables from derived atoms, I mean something like:

```js
const count1 = createAtom( 1 );
const count2 = createAtom( 1 );
const count3 = createAtom( 1 );
const sum = createDerivedAtom( ( { get } ) =>
	combineLatest( get( count1 ), get( count2 ), get( count3 ) )
		.pipe( map( ( [ a, b, c ] ) => a + b + c ) )
);
```

In which case, `createDerivedAtom` could be as simple as:

```js
export const createDerivedAtom = ( resolver, updater = noop, id ) => (
	registry
) => {
	let lastValue = null;
	const get = ( atom ) => registry.__unstableGetAtomState( atom ).subject;
	const observable = resolver( { get } ).pipe(
		tap( ( value ) => ( lastValue = value ) )
	);
	return {
		id,
		type: 'derived',
		get: () => lastValue,
		subscribe: ( listener ) => observable.subscribe( listener ),
		async set( action ) {
			await updater(
				{
					get: ( atom ) => registry.get( atom ),
					set: ( atom, arg ) => registry.set( atom, arg ),
				},
				action
			);
		},
	}
```

**Comment by youknowriad** [comment]
I think you can do that. I don't see why you wouldn't be able to.

**Comment by youknowriad** [comment]
Oh, actually you're right, it's not possible because of the error we throw, I'll need to think about it more. But I definitely don't want to give up the dynamic dependencies. I feel we can just keep a map of unresolved dependencies instead of the  try/catch I'm doing.

**Comment by adamziel** [comment]
> Oh, actually you're right, it's not possible because of the error we throw, I'll need to think about it more. But I definitely don't want to give up the dynamic dependencies. I feel we can just keep a map of unresolved dependencies instead of the try/catch I'm doing.

Maybe `get` could return a promise instead of a value? That promise could be then resolved as soon as the atom is initially resolved (or immediately)? For example:

```js
	const sum = createDerivedAtom(
		async ( { get } ) => await get( count1 ) + await get( count2 ) + await get( count3 )
	);
```

**Comment by youknowriad** [comment]
@adamziel I fixed it in 6c719eae17 and added a unit test for it.

File: packages/stan/README.md [hunk 26]
```diff
@@ -0,0 +1,203 @@
...
+In the example above, we create two simple counter atoms and third derived "sum" atom which value is the sum of both counters.
+
+```js
+console.log( registry.get( sum ) ); // prints 3.
+
+// Adding a listener automatically triggers the refreshing of the value.
+// If the atom has no subscriber, it will only attempt a resolution when initially read. 
+// But it won't bother refreshing its value, if any of its dependencies change.
+// This property (laziness) is important for performance reasons.
+sumInstance.subscribe( () => {
```
Comment (noisysocks) [inline packages/stan/README.md:97]: What is `sumInstance` here?

File: packages/data/src/registry.js (hunk 22 above)
Comment (gziolo) [reply packages/data/src/registry.js:266]: `getAtomForStore` - would it work better or does it read the same?

The name `atomsForStores` doesn't sound better though 😅

File: packages/stan/README.md [hunk 27]
```diff
@@ -0,0 +1,203 @@
+# Stan
+
+"stan" stands for "state" in Polish 🇵🇱. It's a framework agnostic library to manage distributed state in JavaScript application. It is highly inspired by the equivalent [Recoil](https://recoiljs.org/) and [jotai](https://jotai.surge.sh)
+
+It share the same goals as Recoil and Jotai:
+
+-   Based on atoms (or observables) which means it's highly performant at scale: Only what needs to update get updated.
```
Comment (gziolo) [inline packages/stan/README.md:7]:
```suggestion
-   Based on atoms (or observables) which means it's highly performant at scale - only what needs to update gets updated.
```

File: packages/stan/README.md [hunk 28]
```diff
@@ -0,0 +1,203 @@
...
+-   Shares with Jotai the goal of maintaining a very light API surface.
+-   Supports async and sync state.
+
+Unlike these frameworks, it has the following goals too: (which justified the creation of a separate library)
```
Comment (gziolo) [inline packages/stan/README.md:11]:
```suggestion
Unlike these frameworks, it has the following goals that justified the creation of a separate library:
```

File: packages/stan/README.md [hunk 29]
```diff
@@ -0,0 +1,203 @@
...
+
+-   It is React independent. You can create binding for any of your desired framework.
```
Comment (gziolo) [inline packages/stan/README.md:13]:
```suggestion
-   It is independent from other libraries like React. You can create binding for any of your desired framework.
```

File: packages/stan/README.md [hunk 30]
```diff
@@ -0,0 +1,203 @@
...
+-   It needs to be flexible enough to offer bindings for `@wordpress/data` consumer API. (useSelect and useDispatch).
```
Comment (gziolo) [inline packages/stan/README.md:14]:
```suggestion
-   It needs to be flexible enough to offer bindings for `@wordpress/data` consumer API (`useSelect` and `useDispatch`).
```

File: packages/stan/README.md [hunk 31]
```diff
@@ -0,0 +1,203 @@
...
+```
+
+### Async derived atoms
+
+Derived atoms can use async functions to compute their values. They can for instance trigger some REST API call and returns a promise.
+
+```js
+const sum2 = createDerivedAtom(
+    async ( { get } ) => {
+        const val1 = await Promise.resolve(10);
```
Comment (gziolo) [inline packages/stan/README.md:113]:
```suggestion
        const val1 = await Promise.resolve( 10 );
```

File: packages/stan/README.md (hunk 29 above)
Comment (gziolo) [inline packages/stan/README.md:13]:
```suggestion
-   It is React independent. You can create bindings for any of your desired framework.
```

File: packages/stan/README.md [hunk 32]
```diff
@@ -0,0 +1,203 @@
...
+        return val1 * get( counter );
+    } 
+);
+```
+
+The value of async atoms will be equal to `null` until the resolution function finishes.
+
+### Bindings
+
+It is important to note that stan instance and registries API are low-level APIs meant to be used by developpers to build bindings for their preferred frameworks. By in general, a higher-level API is preferred.
```
Comment (gziolo) [inline packages/stan/README.md:123]:
```suggestion
It is important to note that stan instance and registries are low-level APIs meant to be used by developers to build bindings for frameworks of their choice. In general, a higher-level API is preferred.
```

File: packages/stan/README.md [hunk 33]
```diff
@@ -0,0 +1,203 @@
...
+
+Currently available bindings:
+
+-   `@wordpress/data`: WordPress data users can continue to use their existing high-level APIs useSelect/useDispatch (selectors and actions) to access the atoms. The selectors are just high-level atoms that can rely on lower-level ones and the actions are just functions that trigger atom setters. The API for `@wordpress/data` store authors to bridge the gap is still experimental.
```
Comment (gziolo) [inline packages/stan/README.md:127]:
```suggestion
-   `@wordpress/data`: WordPress data users can continue to use their existing high-level APIs `useSelect`/`useDispatch` (selectors and actions) to access the atoms. The selectors are just high-level atoms that can rely on lower-level ones and the actions are just functions that trigger atom setters. The API for `@wordpress/data` store authors to bridge the gap is still experimental.
```

File: packages/stan/README.md [hunk 34]
```diff
@@ -0,0 +1,203 @@
...
+
+_Parameters_
+
+-   _resolver_ `WPAtomFamilyResolver<T>`: Atom resolver.
+-   _updater_ `WPAtomFamilyUpdater<T>`: Atom updater.
+-   _atomConfig_ `[WPCommonAtomConfig]`: Common Atom config.
+
+_Returns_
+
+-   (unknown type): Atom Family Item creator.
```
Comment (gziolo) [inline packages/stan/README.md:156]: Type is missing.

File: packages/stan/README.md [hunk 35]
```diff
@@ -0,0 +1,203 @@
...
+
+-   `WPAtom<T>`: Createtd atom.
+
+<a name="createStoreAtom" href="#createStoreAtom">#</a> **createStoreAtom**
+
+Creates a store atom.
+
+_Parameters_
+
+-   _subscribe_ (unknown type): Subscribe to state changes.
```
Comment (gziolo) [inline packages/stan/README.md:191]: Types for params are missing.

File: packages/stan/src/atom.js [hunk 36]
```diff
@@ -0,0 +1,43 @@
...
+ * @typedef {import("./types").WPAtom<T>} WPAtom
+ */
+
+/**
+ * Creates a basic atom.
+ *
+ * @template T
+ * @param {T}                   initialValue Initial value in the atom. *
+ * @param {WPCommonAtomConfig=} config       Common Atom config.
+ * @return {WPAtom<T>} Createtd atom.
```
Comment (gziolo) [inline packages/stan/src/atom.js:13]:
```suggestion
 * @return {WPAtom<T>} Created atom.
```

File: packages/stan/src/atom.js [hunk 37]
```diff
@@ -0,0 +1,43 @@
...
+ * @template T
+ * @typedef {import("./types").WPAtom<T>} WPAtom
+ */
+
+/**
+ * Creates a basic atom.
+ *
+ * @template T
+ * @param {T}                   initialValue Initial value in the atom. *
+ * @param {WPCommonAtomConfig=} config       Common Atom config.
```
Comment (gziolo) [inline packages/stan/src/atom.js:12]:
```suggestion
 * @param {WPCommonAtomConfig=} config       Common atom's config.
```

File: packages/stan/src/derived.js [hunk 38]
```diff
@@ -0,0 +1,198 @@
...
+ */
+
+/**
+ * Creates a derived atom.
+ *
+ * @template T
+ * @param {WPDerivedAtomResolver<T>} resolver Atom Resolver.
+ * @param {WPDerivedAtomUpdater<T>}  updater  Atom updater.
+ * @param {WPCommonAtomConfig=}      config   Common Atom config.
+ * @return {WPAtom<T>} Createtd atom.
```
Comment (gziolo) [inline packages/stan/src/derived.js:38]:
```suggestion
 * @return {WPAtom<T>} Created atom.
```

File: packages/stan/src/derived.js [hunk 39]
```diff
@@ -0,0 +1,198 @@
...
+ * @typedef {import("./types").WPAtomState<T>} WPAtomState
+ */
+
+/**
+ * Creates a derived atom.
+ *
+ * @template T
+ * @param {WPDerivedAtomResolver<T>} resolver Atom Resolver.
+ * @param {WPDerivedAtomUpdater<T>}  updater  Atom updater.
+ * @param {WPCommonAtomConfig=}      config   Common Atom config.
```
Comment (gziolo) [inline packages/stan/src/derived.js:37]:
```suggestion
 * @param {WPCommonAtomConfig=}      config   Common atom's config.
```

File: packages/stan/src/derived.js [hunk 40]
```diff
@@ -0,0 +1,198 @@
...
+/**
+ * @template T
+ * @typedef {import("./types").WPAtomState<T>} WPAtomState
+ */
+
+/**
+ * Creates a derived atom.
+ *
+ * @template T
+ * @param {WPDerivedAtomResolver<T>} resolver Atom Resolver.
```
Comment (gziolo) [inline packages/stan/src/derived.js:35]:
```suggestion
 * @param {WPDerivedAtomResolver<T>} resolver Atom resolver.
```

File: packages/stan/README.md (hunk 26 above)
Comment (youknowriad) [reply packages/stan/README.md:97]: good catch, it's something I decided to hide inside the registry (atom state objects)

File: packages/stan/src/family.js [hunk 41]
```diff
@@ -0,0 +1,57 @@
...
+/**
+ * @template T
+ * @typedef {import("./types").WPAtomFamilyItem<T>} WPAtomFamilyItem
+ */
+
+/**
+ * @template T
+ * @param {WPAtomFamilyResolver<T>} resolver   Atom resolver.
+ * @param {WPAtomFamilyUpdater<T>}  updater    Atom updater.
+ * @param {WPCommonAtomConfig=}     atomConfig Common Atom config.
```
Comment (gziolo) [inline packages/stan/src/family.js:28]:
```suggestion
 * @param {WPCommonAtomConfig=}     atomConfig Common atom's config.
```

File: packages/stan/src/family.js [hunk 42]
```diff
@@ -0,0 +1,57 @@
...
+ * @return {(key:string) => WPAtomFamilyItem<T>} Atom Family Item creator.
```
Comment (gziolo) [inline packages/stan/src/family.js:29]:
```suggestion
 * @return {(key:string) => WPAtomFamilyItem<T>} Atom family item creator.
```

File: packages/stan/src/registry.js [hunk 43]
```diff
@@ -0,0 +1,150 @@
...
+ * @typedef {import("./types").WPAtomFamilyConfig<T>} WPAtomFamilyConfig
+ */
+/**
+ * @typedef {( atomState: import('./types').WPAtomState<any> ) => void} RegistryListener
+ */
+
+/**
+ * @template T
+ * @param {WPAtom<any>|WPAtomFamilyItem<T>} maybeAtomFamilyItem
+ * @return {boolean} maybeAtomFamilyItem is WPAtomFamilyItem<T>.
```
Comment (gziolo) [inline packages/stan/src/registry.js:34]:
```suggestion
 * @return {boolean} maybeAtomFamilyItem Returns `true` when atom family item detected.
```

File: packages/stan/src/store.js [hunk 44]
```diff
@@ -0,0 +1,39 @@
...
+ */
+
+/**
+ * Creates a store atom.
+ *
+ * @template T
+ * @param {(listener: () => void) => (() => void)} subscribe Subscribe to state changes.
+ * @param {() => T}                                get       Get the state value.
+ * @param {(action: any) => void}                  dispatch  Dispatch store changes,
+ * @param {WPCommonAtomConfig=}                    config    Common Atom config.
```
Comment (gziolo) [inline packages/stan/src/store.js:16]:
```suggestion
 * @param {WPCommonAtomConfig=}                    config    Common atom's config.
```

File: packages/stan/src/test/derived.js [hunk 45]
```diff
@@ -0,0 +1,169 @@
...
+			( { get } ) => get( count1 ) + get( count2 ) + get( count3 )
+		);
+		const registry = createAtomRegistry();
+
+		// Atoms don't compute any value unless there's a subscriber.
+		const unsubscribe = registry.subscribe( sum, () => {} );
+		expect( registry.get( sum ) ).toEqual( 3 );
+		registry.set( count1, 2 );
+		expect( registry.get( sum ) ).toEqual( 4 );
+		unsubscribe();
```
Comment (gziolo) [inline packages/stan/src/test/derived.js:30]: Ideally, `unsubscribe` would be called in `afterEach` section when set by the test to avoid issues when a test failure impacts other tests. 

Although, it might be non issue here as registries seem to be isolated.

File: packages/stan/src/test/derived.js [hunk 46]
```diff
@@ -0,0 +1,169 @@
...
+			( { set }, value ) => {
+				set( sum, value / 3 );
+			}
+		);
+		const registry = createAtomRegistry();
+		registry.set( multiply, 18 );
+		expect( registry.get( count1 ) ).toEqual( 3 );
+		expect( registry.get( count2 ) ).toEqual( 3 );
+	} );
+} );
```
Comment (gziolo) [inline packages/stan/src/test/derived.js:169]: Those tests are great for documentation purposes and help better undesirable how it all should work ❤️

**Review by gziolo — COMMENTED** [review]
More feedback, mostly improvements to code and docs to apply or reject at your will.

File: packages/stan/README.md (hunk 35 above)
Comment (youknowriad) [reply packages/stan/README.md:191]: These are inline typed which I think is better for these, I don't want to create dedicated types for these basic arguments. I feel it's more a tool issue.

File: packages/stan/README.md (hunk 34 above)
Comment (youknowriad) [reply packages/stan/README.md:156]: This one is typed properly, not sure why it's missing here.

File: packages/stan/src/atom.js (hunk 37 above)
Comment (youknowriad) [reply packages/stan/src/atom.js:12]: I think I'm going to skip this one as I believe the existing name is also good enough.

File: packages/keyboard-shortcuts/src/store/actions.js (hunk 24 above)
Comment (gziolo) [reply packages/keyboard-shortcuts/src/store/actions.js:42]: Still, there is this question of how many nested atoms it might absorb for the most popular actions. Think of it as a gigantic switch in the Redux reducer. I guess the fact that you import those atoms explicitly might only help to structure code better.

File: packages/stan/README.md (hunk 35 above)
Comment (gziolo) [reply packages/stan/README.md:191]: Huh, yes, let's leave it as is. We definitely need to improve how this tool works as it clearly works against us when using TypeScript syntax.

**Review by gziolo — APPROVED** [review]
In my opinion, this proposal is already in a mergeable state. @youknowriad, you did amazing job bringing the latest development in state management to WordPress. The performance implications are the best justification that new concepts introduced are worth exploring further:

capture_d___e__cran_2020-11-20_a___8 37 54_am

I hope to see more improvements as we try to apply the new type of store to the most popular stores.

As noted in my comments, it's a bit unfortunate that we don't have the store (keyboard shortcuts) covered with unit tests which would give 100% confidence that the transition from Redux to `@wordpress/stan` is bulletproof. At the same time, this code is well tested indirectly through a huge number of e2e tests so it makes me feel more comfortable.

I'd love to hear from @jsnajdr and @adamziel, how they feel about the internal implementation of `@wordpress/stan` (that part is more approachable to me) and in particular, about optimizations applied to `@wordpress/data`. I'm not as familiar with Redux, recoil, and others, but seeing the number of unit tests that existed before and were added makes me confident that is good enough to proceed.

File: packages/dependency-extraction-webpack-plugin/lib/util.js [hunk 47]
```diff
@@ -1,5 +1,9 @@
 const WORDPRESS_NAMESPACE = '@wordpress/';
-const BUNDLED_PACKAGES = [ '@wordpress/icons', '@wordpress/interface' ];
+const BUNDLED_PACKAGES = [
+	'@wordpress/icons',
+	'@wordpress/interface',
+	'@wordpress/stan',
```
[the remark this answers is not in the document]
Comment (youknowriad) [reply packages/dependency-extraction-webpack-plugin/lib/util.js:5]: It's still undecided whether we'd make stan a script on its own on Core or not.

**Comment by youknowriad** [comment]
@sirreal I actually already renamed the file and fixed the types.

**Comment by sirreal** [comment]
> @sirreal I actually already renamed the file and fixed the types.

`data` and `stan` should be added here in order to be compiled as part of the main typechecking/building flows:

https://github.com/WordPress/gutenberg/blob/8df048cddeb5d4be8adc19c52f5534a9539e6398/tsconfig.json#L2-L29

Otherwise it needs to be built on its own, i.e. `node_modules/.bin/tsc --build packages/data`. I see some errors when building the packages, would you like me to push fixes for them or provide suggestions?

**Comment by youknowriad** [comment]
@sirreal go push fixes :)

File: packages/stan/src/derived.js [hunk 48]
```diff
@@ -0,0 +1,199 @@
...
+					updatedDependencies.push( atomState );
+					if ( ! atomState.isResolved ) {
+						unresolved.push( atomState );
+					}
+					return atomState.get();
+				},
+			} );
+		} catch ( error ) {
+			if ( unresolved.length === 0 ) {
+				throw error;
```
Comment (adamziel) [inline packages/stan/src/derived.js:117]: If I read it correctly, it will silence any exceptions during the resolution.

Comment (adamziel) [reply packages/stan/src/derived.js:117]: I think the entire try/catch could be avoided if `get: ( atom ) => {` was async and defered the responsibility of waiting for dependencies to `resolver` function. I'll propose a change later today.

Comment (adamziel) [reply packages/stan/src/derived.js:117]: (or there's always [this functional API](https://github.com/WordPress/gutenberg/pull/26866/files#r527058918) idea where get: (atom) would return an observable and reduce this file to ~20 LOC)

**Comment by sirreal** [comment]
Noting that I'm finished with the types for now, they seem to be building correctly. I'll save any further changes for follow-up PRs.

File: packages/stan/src/derived.js (hunk 48 above)
Comment (youknowriad) [reply packages/stan/src/derived.js:117]: how so? It throws the error once again?

**Comment by youknowriad** [comment]
Let's try that 🎉

**Comment by gziolo** [comment]
Important note: `@wordpress/stan` won't be published to npm until WordPress 5.6 is released which is planned for December 8th (https://make.wordpress.org/core/2020/08/13/wordpress-5-6-release-planning/). It will most likely happen a few days later after that date when the forthcoming Gutenberg plugin is released.

File: packages/stan/src/derived.js (hunk 48 above)
Comment (adamziel) [reply packages/stan/src/derived.js:117]: Only if `unresolved.length === 0`, I imagine there could be a case where dependent atom's `resolve()` throws an error in this line: `return atomState.get();` and this error gets supressed since `unresolved.length` is no longer 0. Although the solution could be maybe as simple as moving `.get()` above push.

Comment (youknowriad) [reply packages/stan/src/derived.js:117]: Catching these is intended :). If we have an unresolved value, we might have unexpected exceptions because the  resolver might expect a number but since it's unresolved, it will have `null`, so maybe the atom author will use it in an addition and this will trigger an exception until the value is resolved. That's fine but if there's really an error in the logic, the error will be thrown once all the values are resolved.

Comment (adamziel) [reply packages/stan/src/derived.js:117]: @youknowriad alright, I was right after all - here's a test case where the error is not thrown:
```js
	it( 'should not suppress resolution errors', async () => {
		const count1 = createAtom( 1 );
		const asyncCount = createDerivedAtom( async ( { get } ) => {
			throw new Error();
		} );
		const sum = createDerivedAtom( async ( { get } ) => {
			return get( count1 ) + get( asyncCount );
		} );
		const registry = createAtomRegistry();
		expect( () => {
			registry.get( sum ); // or registry.subscribe( sum, () => {} );
		} ).toThrow();
	} );
```

I played with adding `flushImmediatesAndTicks` but it doesn't help. Either way, node logs `(node:31681) UnhandledPromiseRejectionWarning: Error` as `resolve()` is not awaited for nor are its resolution errors caught. I'm playing with a small refactor to address that problem.

Comment (youknowriad) [reply packages/stan/src/derived.js:117]: This case is very weird :P While I agree we should have better error handling, I'm not sure we should be throwing errors because in the example above, you have a failing promise and not an exception that is thrown

Comment (jsnajdr) [reply packages/stan/src/derived.js:117]: The `sum` resolver with the `+` operation is special because `+` doesn't mind if one argument is `null`:
```js
42 + null === 42;
null + null === 0;
```
The `sum` resolver will never throw. It will return questionable sums instead 🙂 

It's better to test this with a resolver that doesn't tolerate `null` values. Like when the upstream values are arrays.

Comment (adamziel) [reply packages/stan/src/derived.js:117]: @jsnajdr IMHO that should be two separate tests - sum resolver is also a valid use case.

Comment (adamziel) [reply packages/stan/src/derived.js:117]: I couldn't come up with anything that wouldn't `async/await` all the things, here's my attempt: https://github.com/WordPress/gutenberg/pull/27155
