### PR TITLE
Blocks: Fix image block error with .tiff images, refactor using withAPIData

### LINKED ISSUE #2535: .tiff files cause error on refresh
To reproduce:

- Click image block
- Add a .tiff file
- Nothing shows
- Refresh
- This shows:

2017-08-25 at 12 29

### PR DESCRIPTION
**Pull request by aduth**
Fixes #2535 

This pull request seeks to refactor the image block to use the `withAPIData` higher-order component for image data request, and in doing so, resolve an error described at #2535 related to `.tiff` file uploads. Such files should no longer cause the block to error, but they do not preview well in all browsers. We may separately want to explore better previews for images which cannot be displayed in the current browser.

__Testing instructions:__

Repeat steps to reproduce from #2535, ensuring that no errors occur when assigning a `.tiff` image to an image block.

Example: https://cldup.com/h4c6dcv9pg.tiff

Verify that there are no regressions in existing image block behavior, particularly:

- Inserting a new image block and assigning an image
- Selecting a thumbnail size
- Dragging to resize an image

### CODE REVIEW

**Comment by youknowriad** [comment]
Which browser are you using for testing, it's now working on Chrome. I guess it's the preview issue?

File: blocks/library/image/block.js [hunk 1]
```diff
@@ -73,31 +70,20 @@ class ImageBlock extends Component {
 		this.props.setAttributes( { ...extraUpdatedAttributes, align: nextAlign } );
 	}
 
-	fetchMedia( id ) {
```
Comment (gziolo) [inline blocks/library/image/block.js]: HOCs remove so much code duplication 👍

File: blocks/library/image/block.js [hunk 2]
```diff
@@ -257,4 +243,16 @@ class ImageBlock extends Component {
...
+export default flowRight( [
+	withEditorSettings(),
+	withAPIData( ( props ) => {
+		const { id } = props.attributes;
+		if ( ! id ) {
+			return {};
+		}
+
+		return {
+			image: `/wp/v2/media/${ id }`,
```
Comment (gziolo) [inline blocks/library/image/block.js]: It's surprising that you need to combine the endpoint's url here, but otherwise it's very nice 👍

**Comment by gziolo** [comment]
Code changes look good, I haven't tested though.

File: blocks/library/image/block.js (hunk 2 above)
Comment (aduth) [reply blocks/library/image/block.js]: >It's surprising that you need to combine the endpoint's url here

Could you elaborate on what you mean by this? I'm not sure if the surprise is something I should be worried about 😄

**Comment by aduth** [comment]
>Which browser are you using for testing, it's not working on Chrome. I guess it's the preview issue?

What specifically is not working? On master it currently errors the whole block (captured by `componentDidCatch`). That is fixed here, but yes, it does not preview very well.

>Such files should no longer cause the block to error, but they do not preview well in all browsers. We may separately want to explore better previews for images which cannot be displayed in the current browser.

File: blocks/library/image/block.js (hunk 2 above)
Comment (gziolo) [reply blocks/library/image/block.js]: I would expect to see API url creation hidden in the HOC. So in this place we could have the following instead:
```js
return [
	id && { type: 'image', params: { id } }
];
```
`withAPIData` could filter out undefined elements to make this more conceise here.

At the moment we have the following code in a few places:
```js
const applyWithAPIData = withAPIData( () => {
	return {
		user: '/wp/v2/users/me?context=edit',
	};
} );```

which would simplify to:
```js
const applyWithAPIData = withAPIData( () => [ { type: 'user' } ] );
```

`withAPIData` would have all mappings stored internally:
`user` => `/wp/v2/users/me?context=edit`

I might be missing something obvious here, but I'm happy to discuss if you think it would be an improvement. It's good how it is because those urls won't rather change in the future :)

**Review by youknowriad — APPROVED** [review]
No block error anymore and still works great for the other formats

File: blocks/library/image/block.js (hunk 2 above)
Comment (aduth) [reply blocks/library/image/block.js]: The issue I'd see is `type` wouldn't always be so simple. This could potentially be used for custom endpoints, which can be defined as whichever route structure the developer chooses (even `/this/is/an/obnoxious/route/pattern`). I noted some downsides here in [the original text](https://gist.github.com/aduth/e5dd6327963475e9f580b8ece523ffa0) of #1974, including how this binds us to the REST API, but doing so in a way that is easy for developers to use (don't need to understand mappings if they already know the routes), isolated, generic.
