### PR TITLE
Site Editor: Fix template author avatar check

### LINKED ISSUE #37452: Can't see template list when avatars are disabled
### Description

When using the Site Editor and heading over to the templates list I encountered a white screen. I noticed an error in the console relating to avatars. It turns out I have them disabled. When enabling the avatars I can view the template list as expected.

### Step-by-step reproduction instructions

1. Disable avatars through Options > Discussion
2. Go to the Site Editor and head over to templates
3. Et voila, a white screen with the following error in the console: TypeError: n.avatar_urls is undefined

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress version 5.8.2
- Gutenberg plugin version 12.1.0
- Tove Theme version 0.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
Closes #37452

Fixes error on Template list screen when user avatars are disabled.

## How has this been tested?
1. Disable avatars through Options > Discussion
2. Go to Site Editor and then Templates.
3. Screens shouldn't crash and display a black circle instead of the user avatar.

## Screenshots 
CleanShot 2021-12-16 at 16 44 05

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by Mamaduka** [comment]
@jameskoster, do you think we should display a fallback icon in this case?

**Comment by jameskoster** [comment]
Comment Author Avatar seems like a good candidate.

**Comment by Mamaduka** [comment]
Looks much better 😄 

CleanShot 2021-12-16 at 17 12 20

File: packages/edit-site/src/components/list/added-by.js [hunk 1]
```diff
@@ -77,18 +81,26 @@ function AddedByAuthor( { id } ) {
 	] );
 	const [ isImageLoaded, setIsImageLoaded ] = useState( false );
 
+	const hasAvatar = !! user?.avatar_urls?.[ 48 ];
```
Comment (kevin940726) [inline packages/edit-site/src/components/list/added-by.js]: I think we could just create a variable here and reference that variable in JSX.

```suggestion
	const avatarURL = user?.avatar_urls?.[ 48 ];
	const hasAvatar = !! avatarURL;
```

So that we won't repeat ourselves :).

File: packages/edit-site/src/components/list/added-by.js [hunk 2]
```diff
@@ -77,18 +81,26 @@ function AddedByAuthor( { id } ) {
...
+
 	return (
 		<HStack alignment="left">
 			<div
-				className={ classnames( 'edit-site-list-added-by__avatar', {
+				className={ classnames( {
+					'edit-site-list-added-by__avatar': hasAvatar,
+					'edit-site-list-added-by__icon': ! hasAvatar,
```
Comment (kevin940726) [inline packages/edit-site/src/components/list/added-by.js]: Maybe it could just be:

```suggestion
				className={ classnames(
					hasAvatar 
						? 'edit-site-list-added-by__avatar'
						: 'edit-site-list-added-by__icon',
				{
```

**Review by kevin940726 — COMMENTED** [review]
Thank you! Code looks good, just a bit nitpicking below, totally optional.

**Comment by talldan** [comment]
Thanks for fixing this. I completely forgot about a similar fix I worked on. This PR reminded me so I've pushed the branch - https://github.com/WordPress/gutenberg/pull/37474.

The changes there should make this fix easier. I can't remember if I'd finished it though, so let me familarise myself again.

**Comment by Mamaduka** [comment]
PR is ready for final review and merging.

**Review by kevin940726 — APPROVED** [review]
LGTM 👍
