### PR TITLE
Format library: fix unsetting highlight color

### LINKED ISSUE #36532: [format/highlights] Block-level color specificity issues when a text block has a block-level color set
### Description

This issue is threefold:
1. Gutenberg had a bug ([issue](https://github.com/WordPress/gutenberg/pull/34680#issuecomment-934190177), [fix](https://github.com/WordPress/gutenberg/pull/35516)) in its recently-refactored `Highlight` tool that required a transparent background color to be applied to all `marks` by default if no background is set, to prevent the `mark`s default yellow background. This effectively means that - as far as the `Highilight` tool/format algorithm are concerned - that the `mark` always has a background color (even if transparent), which means that if you clear the color, the `mark` tag *is not removed* from the DOM, until you also remove the background color, that is (even if it wasn't explicitly set!);
2. The `mark` tag has a default `color` CSS rule that is more specific than the rules applied at its parent (in this case the `paragraph` and `heading` blocks). This means that this will apply until the `mark` is removed (which means clearing the color and background color). 
3. **This actually can cause another issue:** if the text has a block-level color set and you apply only a *background color* using the Highlight tool, the actual block-level text color is lost and you get the `mark`'s text color instead.

### Clearing the highlight text color is not enough to recover the block-level color:

1. Start a new post, write something in a paragraph or heading block.
2. Select this block, and in its settings, apply a color.
3. Now select the text, and using the `Highlight` tool apply a text color (not a background color).
4. Select the same text again and using the `Highlight` tool, clear the text color.
5. Observe how the text doesn't have the block-level color you set in step 1.
6. To recover the color, you need to clear the background color in the `Highlight` tool, too, even though you did not set any.

### Applying a background color using the `Highlight` tool overrides the block-level text color, too

1. Start a new post, write something in a paragraph or heading block.
2. Select this block, and in its settings, apply a color.
3. Now select the text, and using the `Highlight` tool apply a background color only.
4. Observe how the text doesn't have the block-level color you set in step 1, even though intuitively you'd think it would, as you did not set any color for this highlight selection.
5. To recover the color, you need to clear the background color in the `Highlight` tool.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/81248/142041463-aaed586b-7db7-4ceb-aacd-39915eabe951.mp4

https://user-images.githubusercontent.com/81248/142041449-63dd582e-7935-4aed-a737-681dacec044d.mp4

### Environment info

Wodpress 5.8.1, Gutenberg 11.9.0
Firefox 95.0b7 (64-bit)
Ubuntu Linux 18.04

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #36532. If a transparent background color is set, it should be considered as no background set so that the format is removed when neither color not background color is set.

Secondly, for named colors, we mistakenly don't take into account color slugs with dashes, so they never become active, and they cannot be unset. This PR also fixes that.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by youknowriad — COMMENTED** [review]
This fixes the issue 

but I don't really understand why this fix is that low level (in the CSS parsing) instead of when the color is cleared (remove the format)

**Review by youknowriad — APPROVED** [review]

File: packages/format-library/src/text-color/index.js [hunk 1]
```diff
@@ -17,6 +17,8 @@ import { removeFormat } from '@wordpress/rich-text';
  */
 import { default as InlineColorUI, getActiveColors } from './inline';
 
+export const transparentValue = 'rgba(0, 0, 0, 0)';
```
Comment (mcsf) [inline packages/format-library/src/text-color/index.js:20]: I pushed a commit replacing all remaining occurrences of this string in `format-library` with the new constant. This should decrease the chances of format mismatches creeping in — for example, if the setter uses a hardcoded string like `rgba(0,0,0,0)` (with no spaces), the logic breaks.

The module constant, coupled with the expanded test coverage, might be enough. Otherwise we could use a regular expression.

File: packages/format-library/src/text-color/inline.js [hunk 2]
```diff
@@ -44,9 +44,10 @@ function parseCSS( css = '' ) {
 
 function parseClassName( className = '', colorSettings ) {
 	return className.split( ' ' ).reduce( ( accumulator, name ) => {
-		const match = name.match( /^has-([^-]+)-color$/ );
-		if ( match ) {
-			const [ , colorSlug ] = name.match( /^has-([^-]+)-color$/ );
+		if ( name.startsWith( 'has-' ) && name.endsWith( '-color' ) ) {
```
Comment (mcsf) [inline packages/format-library/src/text-color/inline.js:48]: There should be a comment here explaining that `colorSlug` may be more than one word long, lest someone reintroduce a naive regular expression.

**Review by mcsf — APPROVED** [review]
> Secondly, for named colors, we mistakenly don't take into account color slugs with dashes, so they never become active, and they cannot be unset. This PR also fixes that.

Do we have such slugs in our E2E environment? Could we test the scenario?

Regardless, LGTM!

**Comment by ellatrix** [comment]
> but I don't really understand why this fix is that low level (in the CSS parsing) instead of when the color is cleared (remove the format)

It's not a general parsing CSS function, it's one specifically to parse the color from the style attribute. We have a similar function to parse the color from a class attribute.

> Do we have such slugs in our E2E environment? Could we test the scenario?

We did implicitly. I made that explicit now.
