### PR TITLE
Fix/column width units

### LINKED ISSUE #26096: Correct column widths
**Describe the bug**
After using `UnitControls` in `Columns introduced in the [PR](https://github.com/WordPress/gutenberg/pull/24711) there is a regression in distributing columns width.

Basically some functions such as [hasExplicitColumnWidths](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/columns/utils.js#L99) or [toWidthPrecision](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/columns/utils.js#L14) from `columns/utils.js` cannot work since there is a check `Number.isFinite(value)`. Value always comes with the unit, so the result is `false`. Unfortunately it has an effect on columns width distribution (_please notice that on presented gif, the third column width is different_)

before PR | after PR
--- | ---
before_pr | after_pr

Function called `getTotalColumnsWidth` used within `getRedistributedColumnWidths` sums the width attribute of the individual column defined in % (correct me if I'm wrong). With the approach where width can be defined in different units, function mentioned above should take into account somehow.

**To reproduce**
1. Open a post
2. Add columns block
3. Choose variation `30/70`
4. Add third column
5. Observe width is not distributed properly

**Expected behavior**

Width should be distributed properly as before introducing the `UnitControls`

**Screenshots**

Added above

**Editor version (please complete the following information):**
- Gutenberg 9.2

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 86.0.4240.75

### PR DESCRIPTION
**Pull request by tellthemachines**
## Description

Fixes #26096 and #26641

#24711 introduced two issues when column width attributes switched from being defined as numbers to strings:

* Some of the utility functions for calculating width when changing column number broke as they expected to always receive numbers;
* Templates defining widths as numbers broke as they expected a number to always be interpreted as a percent.

This PR:
* changes two of the utility functions to parse strings for numbers and use them as such; 
*  re-introduces the previous behaviour of  adding a `%` to the end of a column width when it is defined as a number. 

To avoid breaking columns already set with fixed widths, recalculation on adding/removing columns only takes into account the existing column widths if they are defined in percent, or if they are unitless (which should be interpreted as percent for back compat reasons).

## How has this been tested?

Tested in browser:
 * Add a 30/70 columns block, add a new column to it and verify new widths look as expected. 
* Add/remove columns to various blocks with explicit widths defined. Check that widths defined in `px` don't get changed when adding or removing columns.
* Check that unitless widths in a custom post type template are interpreted as `%`.

Also added a few unit tests for the changes in the utility functions.

## Types of changes

 Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-library/src/columns/utils.js [hunk 1]
```diff
@@ -96,10 +99,18 @@ export function getRedistributedColumnWidths(
  *
  * @return {boolean} Whether columns have explicit widths.
  */
-export function hasExplicitColumnWidths( blocks ) {
-	return blocks.every( ( block ) =>
-		Number.isFinite( block.attributes.width )
-	);
+export function hasExplicitPercentColumnWidths( blocks ) {
+	return blocks.every( ( block ) => {
```
Comment (ntsekouras) [inline packages/block-library/src/columns/utils.js:103]: I think you can simplify this a bit like:
```
const blockWidth = block.attributes.width;
return Number.isFinite(
	blockWidth.endsWith?.( '%' ) ? parseFloat( blockWidth ) : blockWidth
);
```

File: packages/block-library/src/column/deprecated.js [hunk 2]
```diff
@@ -6,9 +6,34 @@ import classnames from 'classnames';
 /**
  * WordPress dependencies
  */
-import { InnerBlocks } from '@wordpress/block-editor';
+import { InnerBlocks, useBlockProps } from '@wordpress/block-editor';
 
 const deprecated = [
+	{
```
Comment (ntsekouras) [inline packages/block-library/src/column/deprecated.js:12]: I'm not really sure about the deprecation here. For start it should have `attributes` or `isEligible` etc.. With just a `save` function, wouldn't it match if a Columns block was invalid for whatever reason? -cc @gziolo

**Review by ntsekouras — COMMENTED** [review]
Hey @tellthemachines - thanks for working on this. I tested it and seems fine! I'm not really sure about the deprecation though about what cases wants to handle..

File: packages/block-library/src/column/deprecated.js (hunk 2 above)
Comment (gziolo) [reply packages/block-library/src/column/deprecated.js:12]: It would work without `attributes`, but as soon as they change, it might stop working. So it's safer to set them. `isEligible` is optional.

File: packages/block-library/src/column/deprecated.js [hunk 3]
```diff
@@ -6,9 +6,34 @@ import classnames from 'classnames';
...
+		save( { attributes } ) {
+			const { verticalAlignment, width } = attributes;
+
+			const wrapperClasses = classnames( {
+				[ `is-vertically-aligned-${ verticalAlignment }` ]: verticalAlignment,
+			} );
+
+			let style;
+			if ( width ) {
```
Comment (gziolo) [inline packages/block-library/src/column/deprecated.js:21]: Is it possible to modify the previous deprecation instead? The one that created the issue in the first place?

**Comment by gziolo** [comment]
It would be great to add some tests that verify if the originally introduced deprecation work as expected in the first place. We should also add a block fixture that is buggy to ensure it's resolved.

**Comment by gziolo** [comment]
I opened #26774 that adds tests for the deprecation introduced in #24711. It also improves a bit the setup for the deprecation based on the suggestions from @ntsekouras. It would be nice to land first and rebase this PR to ensure this test still passes.

File: packages/block-library/src/column/save.js [hunk 4]
```diff
@@ -16,7 +16,10 @@ export default function save( { attributes } ) {
 	} );
 
 	let style;
-	if ( width ) {
+
+	if ( Number.isFinite( width ) ) {
```
Comment (gziolo) [inline packages/block-library/src/column/save.js:20]: `width` can be undefined, so we still should keep the check, how about (I included code comment to ensure it doesn't get removed:

```js
if ( width ) {
	// Numbers are handled for backward compatibility when provided with templates.
	style = { flexBasis: Number.isFinite( width ) ? width + '%' : width };
}
```

File: packages/block-library/src/column/deprecated.js (hunk 3 above)
Comment (gziolo) [reply packages/block-library/src/column/deprecated.js:21]: If we have https://github.com/WordPress/gutenberg/pull/26757/files#r518737391 + https://github.com/WordPress/gutenberg/pull/26774, then we might not need another deprecation.

File: packages/block-library/src/columns/utils.js (hunk 1 above)
Comment (tellthemachines) [reply packages/block-library/src/columns/utils.js:103]: Ooooh, much better, thanks!

**Comment by tellthemachines** [comment]
I addressed all the feedback, removed the deprecation and ran the integration tests locally; everything looks fine. Also tested with a few column blocks created on a previous branch and nothing breaks in the editor. 

E2e failures don't seem related to this work; they're failing on every PR now 😩 

Would be good to get this merged today though, so we can include it in Beta 4.

**Review by aristath — APPROVED** [review]
LGTM :+1:

File: packages/block-library/src/column/save.js [hunk 5]
```diff
@@ -16,8 +16,10 @@ export default function save( { attributes } ) {
 	} );
 
 	let style;
+
 	if ( width ) {
-		style = { flexBasis: width };
+		// Numbers are handled for backward compatibility as they can be still provided with templates.
+		style = { flexBasis: Number.isFinite( width ) ? width + '%' : width };
```
Comment (gziolo) [inline packages/block-library/src/column/save.js:22]: I will explore it further, but seeing this PR again, I started thinking about whether new changes applied to `edit` are enough. Anyway, I can send a follow-up PR when I confirm it isn't necessary anymore. For now, better safe than sorry 😄

**Review by gziolo — APPROVED** [review]
Looks good 🚢

**Review by lukewalczak — APPROVED** [review]
Tested changes on mobile and didn't spot any breakage 🎉

File: packages/block-library/src/column/save.js (hunk 5 above)
Comment (gziolo) [reply packages/block-library/src/column/save.js:22]: I tested it with the following diff:

```diff
diff --git a/packages/block-library/src/column/save.js b/packages/block-library/src/column/save.js
index c43edc8464..ccf1b64387 100644
--- a/packages/block-library/src/column/save.js
+++ b/packages/block-library/src/column/save.js
@@ -18,8 +18,7 @@ export default function save( { attributes } ) {
 	let style;
 
 	if ( width ) {
-		// Numbers are handled for backward compatibility as they can be still provided with templates.
-		style = { flexBasis: Number.isFinite( width ) ? width + '%' : width };
+		style = { flexBasis: width };
 	}
 
 	return (
diff --git a/packages/block-library/src/columns/variations.js b/packages/block-library/src/columns/variations.js
index 9f20699dee..6026a5f51e 100644
--- a/packages/block-library/src/columns/variations.js
+++ b/packages/block-library/src/columns/variations.js
@@ -74,8 +74,8 @@ const variations = [
 			</SVG>
 		),
 		innerBlocks: [
-			[ 'core/column', { width: '33.33%' } ],
-			[ 'core/column', { width: '66.66%' } ],
+			[ 'core/column', { width: 33.33 } ],
+			[ 'core/column', { width: 66.66 } ],
 		],
 		scope: [ 'block' ],
 	},
```

and it seems to work correctly. Do you think we should update codebase or do I miss some other case?

Comment (tellthemachines) [reply packages/block-library/src/column/save.js:22]: Tested this by adding a 30/70 columns block, and both columns are rendering with the same size. But that happens with or without your change to `save.js`, so looking for the issue now 🤔

Comment (tellthemachines) [reply packages/block-library/src/column/save.js:22]: Scratch that, I was passing the template widths in as unitless strings 😅 . That's not something we'd ever expect to happen, is it?

I think it's fine to make this change, anyway!

Comment (gziolo) [reply packages/block-library/src/column/save.js:22]: Yes, it works properly only with numbers. I had the same issue with strings. We can always check the issue filed and previous setup before it was converted to percentages. If it worked with strings in the past, we might need another fix 😃
