### PR TITLE
Restore Post Formats UI by fixing editorSettings variable reference

### LINKED ISSUE #6864: Post formats not selectable
**Describe the bug**
With the latest plugin update (2.9.1) and Wordpress update (4.9.6) when using the Gutenberg editor one can't select the format of the post.

**To Reproduce**
1. Go to 'All posts'
2. Click on 'Edit' on one of the posts
3. On the right sidebar there is no 'Formats' section

**Expected behavior**
A Formats section should be visible also in the Gutenberg editor, as is in the Classic editor

**Screenshots**
The Gutenberg editor without the Formats
The Classic editor with Formats

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Firefox
 - Version: 60.0 (64-bit)

### PR DESCRIPTION
**Pull request by danielbachhuber**
Adds e2e test to prevent future regression.

image

Fixes #6864

### CODE REVIEW

File: editor/components/post-format/check.js [hunk 1]
```diff
@@ -14,8 +14,11 @@ function PostFormatCheck( { disablePostFormats, ...props } ) {
 }
 
 export default withSelect(
-	( select ) => ( {
-		disablePostFormats: select( 'core/editor' ).getEditorSettings(),
```
Comment (youknowriad) [inline editor/components/post-format/check.js]: 😅

File: test/e2e/specs/hello.test.js [hunk 2]
```diff
@@ -12,10 +12,15 @@ describe( 'hello', () => {
...
 		expect( page.url() ).toEqual( expect.stringContaining( 'post-new.php' ) );
+		// Should display the title.
 		const title = await page.$( '[placeholder="Add title"]' );
 		expect( title ).not.toBeNull();
+		// Should display the Preview button.
 		const postPreviewButton = await page.$( '.editor-post-preview.components-button' );
 		expect( postPreviewButton ).not.toBeNull();
+		// Should display the Post Formats UI.
+		const postFormatsUi = await page.$( '.editor-post-format' );
+		expect( postFormatsUi ).not.toBeNull();
```
Comment (youknowriad) [inline test/e2e/specs/hello.test.js]: Thanks for the e2e test, I wonder if this test should be separate for clarity :) 

Actually, even testing the preview button seems odd in this "hello world" test but I guess it's fine for now.

**Review by youknowriad — APPROVED** [review]
LGTM 👍

File: test/e2e/specs/hello.test.js (hunk 2 above)
Comment (danielbachhuber) [reply test/e2e/specs/hello.test.js]: At some point I'd like to flesh out the e2e tests and make sure we have tests for every element.

Comment (youknowriad) [reply test/e2e/specs/hello.test.js]: I personally don't think we should have e2e tests for everything :). e2e have maintenability and debugging costs that sometimes I prefer more granular unit tests while keeping the e2e tests for the main regressions we want to prevent from.
