### PR TITLE
Respect Posts Page

### LINKED ISSUE #3659: Clicking edit blog page suggest to write story for it
## Issue Overview
Using twentyseventeen theme In static front page mode. Front page with panels: main page, page, one more page and blog page. Clicking edit link under blog page title allows to add story to it o_O  

## Steps to Reproduce (for bugs)
1. ensure you are using twentyseventeen theme
2. switch to static page mode for main page
3. add some pages to the panels
4. add blog page to one of the panels
5. hit home page 
6. scroll to panel with blog page
7. hit edit
8. add some story in blog page

Google Chromium 62.0.3202.94 (Official Build) Built on Ubuntu , running on LinuxMint 18.2 (64-bit)

## Expected Behavior
Expected editable title for blog page and editable permalink **only** like it done in core editor.

## Current Behavior
Currently I can add a story for the blog page which should not have any story itself.

## Possible Solution
Need handle for special pages like blog page or such.

### PR DESCRIPTION
**Pull request by wpscholar**
## Description
Ensure that Gutenberg is disabled when on the assigned blog page in WordPress. Provides feature parity as per functionality from https://github.com/WordPress/WordPress/blob/master/wp-admin/edit-form-advanced.php#L73).

Fixes https://github.com/WordPress/gutenberg/issues/3659

## How has this been tested?

Tested manually as follows:

1. From 'Settings' > 'Reading' in the admin, make sure you configure the 'Your homepage displays' section to have a 'Posts page' configured. (The posts page should have no content on it)
2. Visit the posts page edit screen in the WordPress admin.
3. The blog page should not utilize Gutenberg and should show a "You are currently editing the page that shows your latest posts." message.

Added unit tests to ensure the gutenberg_can_edit_post() function returns false when attempting to edit the posts page if it does not have content and returns true when it does have content.

## Screenshots
edit_page_ _gutenberg_ _wordpress

## Types of changes
Bug fix - adds a check to the `gutenberg_can_edit_post()` function and returns false if it is the posts page and has no content. 

## Checklist:
- [ ✓] My code is tested.
- [✓ ] My code follows the WordPress code style.
- [ ✓] My code follows the accessibility standards.
- [✓ ] My code has proper inline documentation.

### CODE REVIEW

**Review by aduth — CHANGES_REQUESTED** [review]
Pending approach feedback at https://github.com/WordPress/gutenberg/issues/3659#issuecomment-408921872

File: lib/register.php [hunk 1]
```diff
@@ -269,6 +269,10 @@ function gutenberg_can_edit_post( $post ) {
 		return false;
 	}
 
+	if ( $post->ID == get_option( 'page_for_posts' ) && empty( $post->post_content ) ) {
```
Comment (aduth) [inline lib/register.php]: - Needs [Yoda condition](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#yoda-conditions) (see failing build)
- Should ideally be using strict equality. This isn't codified in the standard, but if we expect it to take a particular value shape, we'd be better off than to allow leniency (prone to false positives)
- The condition is not self-explanatory, and could do for an inline code comment explaining why it exists.

**Review by aduth — CHANGES_REQUESTED** [review]

File: phpunit/class-admin-test.php [hunk 2]
```diff
@@ -75,6 +75,20 @@ function test_gutenberg_can_edit_post() {
 
 		wp_set_current_user( self::$editor_user_id );
 		$this->assertTrue( gutenberg_can_edit_post( $generic_post_id ) );
+
+		$blog_page_without_content = self::factory()->post->create( array(
+			'post_title'   => 'Blog',
+			'post_content' => '',
+		) );
+		update_option( 'page_for_posts', $blog_page_without_content );
```
Comment (aduth) [inline phpunit/class-admin-test.php]: Are these tests isolated from one another? Is this something which should be reverted in a `tearDown` ?

Comment (wpscholar) [reply phpunit/class-admin-test.php]: @aduth All MySQL queries in WordPress unit tests use the `COMMIT` and `ROLLBACK` approach to ensure that things like `update_option` are automatically rolled back. See https://github.com/WordPress/wordpress-develop/blob/master/tests/phpunit/includes/testcase.php#L155

**Review by aduth — APPROVED** [review]
Looks good. E2E failures are unrelated and are being investigated separately. Will try restarting Travis to get a passing build.
