### PR TITLE
Display server error message when one exists

### LINKED ISSUE #7137: Display error when image fails to upload and server returns error message
In the WordPress Media Library, a failed image upload will display the specific error returned by the server:

image

However, Gutenberg displays a generic "Error while uploading" message:

image

It would be better to display the specific error message.

This scenario can be reproduced with the following code snippet:

```
$force_upload_failure = function( $file ) {
	$file['error'] = 'This file upload has been forced to fail.';
	return $file;
};
add_filter( 'wp_handle_sideload_prefilter', $force_upload_failure );
add_filter( 'wp_handle_upload_prefilter', $force_upload_failure );
```

Tested with Gutenberg 3.0.

### PR DESCRIPTION
**Pull request by danielbachhuber**
## Description

If the server rejects a media upload and includes a message, display that message in the error UI.

Fixes #7137

## How has this been tested?

Add the following code snippet in `functions.php` or similar:

```
$force_upload_failure = function( $file ) {
	$file['error'] = 'This file upload has been forced to fail.';
	return $file;
};
add_filter( 'wp_handle_sideload_prefilter', $force_upload_failure );
add_filter( 'wp_handle_upload_prefilter', $force_upload_failure );
```

Attempt to upload an image into the image block. Observe `This file upload has been forced to fail.` as the error message.

## Screenshots

image

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: utils/mediaupload.js [hunk 1]
```diff
@@ -98,16 +98,22 @@ export function mediaUpload( {
...
 			},
-			() => {
+			( response ) => {
 				// Reset to empty on failure.
 				setAndUpdateFiles( idx, null );
-				onError( {
-					code: 'GENERAL',
-					message: sprintf(
+				let message;
+				if ( ! isEmpty( response.responseJSON.message ) ) {
```
Comment (gziolo) [inline utils/mediaupload.js]: It might be safer to use `has` or `get` from lodash in here in case `responseJSON` is not set:
```js
if ( has( response, [ 'responseJSON', 'message' ] ) {
```

Comment (danielbachhuber) [reply utils/mediaupload.js]: Good suggestion. Updated in 20d673af4

**Review by gziolo — APPROVED** [review]
Code-wise, it looks good. It has some merge conflicts to be resolved before merging.
