### PR TITLE
Avoid adding default block to empty widget areas in customizer

### LINKED ISSUE #32968: Widget Editor: Unable to empty widget areas in customizer
## Description

Widget areas can't be emptied in the customizer. 

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Go to the customizer.
2. Empty a widget area that already had widgets in it and click update.
3. View the front end.
4. Note the empty widget area.

## Expected behaviour

Widget areas can be emptied from the customizer as they can on the widgets screen.

## Actual behaviour

Widget areas can't be emptied in the customizer. The placeholder can't be removed.

## Screenshots or screen recording (optional)

In Customize, only the placeholder is visible after deleting widgets. Backspacing does not remove the placeholder:

Screen Shot 2021-06-24 at 2 56 18 PM

On the front end, the widget area is empty, but present in source code:
Screen Shot 2021-06-24 at 2 56 54 PM

## WordPress information
- WordPress version: 5.8-beta3-51224
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Mac
- Operating system: MacOS 10.15.x
- Browser: Chrome 91

### PR DESCRIPTION
**Pull request by kevin940726**
## Description

Fix #32968.

The block editor will inject a default block whenever the content is empty, preventing it from losing focus. This doesn't play nice in the Widgets Customizer though, as an empty block will still create a widget and thus pollute the sidebar. The standalone widgets screen doesn't suffer from this because it will never be emptied, there's always going to be Widget Area blocks.

The solution is to unregister the default block in the customizer, so that the editor won't try to insert a default block whenever the editor is empty. This has a side-effect though as now the focus will be lost after deleting the last block. A possible solution to that would be to manually move the focus to the button block appender whenever that happens.

Another solution to this problem would be to skip creating the empty widget when there's only one block and which is an empty default block. This is more semantically correct and we won't lose the focus. But it might be confusing to the users though 🤔. 

I'm open to any other suggestions.

## How has this been tested?

1. Go to Appearance -> Customize -> Widgets
2. Try to empty a widget area by deleting all blocks
3. Hit "Publish"
4. Confirm that all widgets are deleted in the frontend

## Screenshots 

https://user-images.githubusercontent.com/7753001/123385317-fb85f300-d5c7-11eb-92fa-f8c2161b880d.mp4

## Types of changes

Bug fix

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by talldan** [comment]
> The block editor will inject a default block whenever the content is empty, preventing it from losing focus. This doesn't play nice in the Widgets Customizer though, as an empty block will still create a widget and thus pollute the sidebar.

Hmm, seems like it shouldn't do this when `renderAppender` is defined. Not sure if the bit of code that handles the default block insertion has any awareness over `renderAppender`, where is that defined @kevin940726 ?

edit: ah, I think I see it, `ensureDefaultBlock`.

**Comment by talldan** [comment]
> This has a side-effect though as now the focus will be lost after deleting the last block.

There might be other things, like the Insert Before / After are no longer available since they insert the default block. Possibly other bits of functionality that's lost too. (edit: the slash inserter also doesn't work)

> Another solution to this problem would be to skip creating the empty widget when there's only one block and which is an empty default block. This is more semantically correct and we won't lose the focus. But it might be confusing to the users though 🤔.

I feel like this would be good, but we also need the block not to be there in the editor.

Maybe an option is an `__unstableHasCustomAppender` editor setting that bypasses `ensureDefaultBlock`. To be clear, this isn't a long term option, but it would hopefully fix for 5.8, and then we'd want to prioritise removing that for a better solution.

File: packages/customize-widgets/src/components/sidebar-block-editor/index.js [hunk 1]
```diff
@@ -118,7 +124,12 @@ export default function SidebarBlockEditor( {
 						<WritingFlow>
 							<ObserveTyping>
 								<BlockList
-									renderAppender={ ButtonBlockAppender }
+									renderAppender={ ( props ) => (
```
Comment (talldan) [inline packages/customize-widgets/src/components/sidebar-block-editor/index.js]: There's a flaw with `renderAppender` that it doesn't work too well as a function prop (essentially it's like giving React a new component on every render), so it'd be good to `useCallback` on the function to avoid that.

File: packages/block-editor/src/store/actions.js [hunk 2]
```diff
@@ -914,10 +914,26 @@ export function* removeBlocks( clientIds, selectPrevious = true ) {
...
+		blockEditorStoreName,
+		'getSettings'
+	);
+
+	// If there's an custom appender, don't insert default block.
+	// We have to remember to manually move the focus elsewhere to
+	// prevent if from being lost though.
+	if ( __unstableHasCustomAppender ) {
+		return;
+	}
```
Comment (talldan) [inline packages/block-editor/src/store/actions.js]: I think this bit of code could be moved to `ensureDefaultBlock`, as that would also cover `replaceBlocks` (which also calls `ensureDefaultBlock`).

File: packages/customize-widgets/src/components/sidebar-block-editor/index.js (hunk 1 above)
Comment (talldan) [reply packages/customize-widgets/src/components/sidebar-block-editor/index.js]: An alternative could be to move the effect to ButtonBlockAppender to avoid that.

File: packages/block-editor/src/store/actions.js (hunk 2 above)
Comment (kevin940726) [reply packages/block-editor/src/store/actions.js]: Oh right, I forgot about that.

File: packages/customize-widgets/src/components/block-appender/index.js [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+
+	// Move the focus to the block appender to prevent focus from
+	// being lost when emptying the widget area.
+	useEffect( () => {
+		if ( isBlocksListEmpty && ref.current ) {
+			const { ownerDocument } = ref.current;
+
+			if (
+				! ownerDocument.activeElement ||
+				ownerDocument.activeElement === ownerDocument.body
```
Comment (kevin940726) [inline packages/customize-widgets/src/components/block-appender/index.js:25]: I'm not sure we need this, but in case if the focus is intentionally moved to other element then we don't want to hijack it either.

**Review by talldan — APPROVED** [review]
This works well. 

We know it's not the ideal solution, but it's not too far away IMO, just need to find a way to detect the existence of a custom appender, rather than use a manual setting. And also think about other ways to handle moving the focus to the button appender.

**Comment by adamziel** [comment]
E2E failures seem unrelated, I restarted these tests.
