### PR TITLE
fix button link modal not closing

### LINKED ISSUE #3501: Button link modal doesn't close
## Issue Overview
In the button block, the link dropdown doesn't close when you are done using it, and blocks other areas of the screen.

## Steps to Reproduce (for bugs)
Gutenberg 1.7, WP 4.8.3, Windows, Firefox and Chrome
1. Create a button block
2. Start typing in the URL field, and the dropdown of suggested links appears
3. Select a link
4. Click anywhere else on the screen, and the dropdown stays there.  The dropdown covers the selection of common blocks underneath it.

## Expected Behavior
After you select a link, the dropdown should go away.  Or maybe it should go away after you click the "Apply" button.  Or maybe there should be an "X" so you can choose to close it, or it should close when you click outside it.  There needs to be some way to make that dropdown go away.

## Current Behavior
The dropdown stays there until you click in another block.  If the button is the only block you have, then it's hard to add a new one because the dropdown covers up the common block suggestions.

## Possible Solution
This should be consistent with the behavior of other pop-ups and modals.

## Screenshots / Video
button link modal

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by vladanost**
## Description

Fixes https://github.com/WordPress/gutenberg/issues/3501

Button link suggestion modal could only be closed buy first using arrow keys and pressing ENTER afterwards. When clicked, the link changed but the modal was stuck.

## How Has This Been Tested?

JS unit test passing

## Types of changes

I added a new method to handle this.

### CODE REVIEW

File: blocks/url-input/index.js [hunk 1]
```diff
@@ -147,6 +147,14 @@ class UrlInput extends Component {
 		}
 	}
 
+	onClickInputSuggestion( index, link ) {
+		this.props.onChange( link );
+		this.setState( {
+			selectedSuggestion: index,
```
Comment (aduth) [inline blocks/url-input/index.js]: Should we reset this back to `null` (the initial value) ?

**Comment by vladanost** [comment]
@aduth Thank you for catching that. I have refactored the code to do the same when pressing Enter key.

**Review by aduth — APPROVED** [review]
This looks to be a good intermediary fix, but I'm generally concerned about the behavior of the visible suggestions list being tied to a selection more than it is to input focus. There's also several places within `URLInput` we manage this: in input handlers, change handlers, selection handlers. Could do for some more refactoring I think, but fine for subsequent pull requests.
