### PR TITLE
[Components - ToggleGroupControl]: Fix extra update on incoming change

### LINKED ISSUE #37172: Editor History: Font size settings don't redo properly
### Description

If font-size is the first block typography setting I update, I can undo and redo sizing without issue. I'm, however, unable to redo font-size changes when they are made _**after**_ other typography updates (line spacing, line height, etc.).

Ex. I update line spacing _and then_ I update font-size. When I undo and redo, font-sizes won't redo properly.

### Step-by-step reproduction instructions

**Block Editor**

1. Navigate to the post editor
2. Add text to a paragraph block
3. In the paragraph block's block settings menu, update line height
4. Update font size
5. Undo until the text and typography updates are gone
6. Redo until you return to the current revision
7. Verify that font-size isn't restored

**Site Editor**

1. Enable full site editing by activating the Gutenberg plugin and an FSE enabled theme (Ex. Quadrat)
2. Navigate to the site editor
3. Add text to a paragraph block
4. In the paragraph block's block settings menu, update line height
5. Update font size
6. Undo until the text and typography updates are gone
7. Redo until you return to the current revision
8. Verify that font-size isn't restored

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ntsekouras**
Fixes: https://github.com/WordPress/gutenberg/issues/37172

There was a bug in `ToggleGroupControl` component where it would call the passed `onChange` function during rendering an extra time where the value was the result of an incoming change (redo/undo). That would cause an extra level in history which was the same with the previous one, due to internal logic of handling history steps.

## Testing instructions (from the issue 😄 )

1. Navigate to the post editor
2. Add text to a paragraph block
3. In the paragraph block's block settings menu, update line height
4. Update font size
5. Undo until the text and typography updates are gone
6. Redo until you return to the current revision
7. Verify that font-size isn't restored

** noting that to reproduce the bug we have to also have at least one more typography setting which is handled by `style` object property. This is needed because it has to do with internals detection of `marking` history steps.

### Before

https://user-images.githubusercontent.com/16275880/145225987-58eda2e7-5bed-4c1c-b872-75cf5373371d.mov

### After

https://user-images.githubusercontent.com/16275880/145225999-11fd44f7-1e22-4615-8481-79f9267d625e.mov

### CODE REVIEW

**Review by mcsf — COMMENTED** [review]
Looks good, although the manual two-way binding with the twin `useUpdateEffect` hooks is something I found surprising.

File: packages/components/src/toggle-group-control/toggle-group-control/component.tsx [hunk 1]
```diff
@@ -59,10 +59,15 @@ function ToggleGroupControl(
...
 		state: value,
 	} );
+	const previousValue = usePrevious( value );
 
 	// Propagate radio.state change
 	useUpdateEffect( () => {
-		onChange( radio.state );
+		// Avoid calling onChange if radio state changed
+		// from incoming value.
+		if ( previousValue !== radio.state ) {
```
Comment (youknowriad) [inline packages/components/src/toggle-group-control/toggle-group-control/component.tsx:68]: It feels like this should be part of useUpdateEffect instead?

Comment (ntsekouras) [reply packages/components/src/toggle-group-control/toggle-group-control/component.tsx:68]: Why? It seems that `useUpdateEffect` just skips first render, but here we can pass an incoming value later on..

Comment (youknowriad) [reply packages/components/src/toggle-group-control/toggle-group-control/component.tsx:68]: I guess I was confused by the "useUpdateEffect" name, for me it was about syncing and calling an onChange value from an internal state but I guess it's not :P

**Review by youknowriad — APPROVED** [review]

**Review by ciampo — COMMENTED** [review]
The changes test well as per instructions, and do fix the issue reported in #37172

I just wonder if this change in behavior could be unexpected for a consumer of this component, in case they expected the `onChange` callback to fire _every time_ there's a change in value, regardless of whether the change is "external" or "internal"

In any case, could we also add a couple of doc changes:
- potentially update the `onChange` prop docs in the [README](https://github.com/WordPress/gutenberg/blob/24d603e80f5d83e5536c6c3a08e66f97caf5a864/packages/components/src/toggle-group-control/toggle-group-control/README.md?plain=1#L64) and in [`types.ts`](https://github.com/WordPress/gutenberg/blob/9aeb7d779de39d4199c336f31fc29b28e1cec838/packages/components/src/toggle-group-control/types.ts#L76) specifying the new behaviour
- add a [CHANGELOG](https://github.com/WordPress/gutenberg/blob/cdedab28a09d3f2720dc7bd006be0ef173fd6705/packages/components/CHANGELOG.md) entry to the `@wordpress/components` package? It can go under the `Experimental` section, since the component is marked as such

**Comment by youknowriad** [comment]
> I just wonder if this change in behavior could be unexpected for a consumer of this component, in case they expected the onChange callback to fire every time there's a change in value, regardless of whether the change is "external" or "internal"

I think we should base the behavior of all the components on the behavior of the regular elements (input...) and onChange is not called there if it's an external change.

**Review by ciampo — APPROVED** [review]
> I think we should base the behavior of all the components on the behavior of the regular elements (input...) and onChange is not called there if it's an external change.

That sounds reasonable, let's go ahead and merge these changes once the CHANGELOG is updated

File: packages/components/src/toggle-group-control/toggle-group-control/component.tsx (hunk 1 above)
Comment (ntsekouras) [reply packages/components/src/toggle-group-control/toggle-group-control/component.tsx:68]: I was confused at first as well by the name 😄
