### PR TITLE
Swap Template: Show the right templates for the right post type

### LINKED ISSUE #57112: Post Template: The correct template list is not displayed and saving fails
### Description

My understanding is that if a custom template is defined in theme.json, you can switch to that template in the Post Editor. Additionally, if `postTypes` prop is defined, the post type should limit the available templates.

However, it seems that the post type is not taken into account and the post fails to save if I change the template.

### Step-by-step reproduction instructions

- Enable the Twenty Twenty-Four theme. This theme defines four custom templates:
  - Page No Title (page)
  - Page With Sidebar (page)
  - Page with wide Image (page)
  - Single with Sidebar (post)
- Open the **Post** Editor. 
- Click the "Single Posts" button in the sidebar.
- Click Swap template.
- A template selection modal will open, but you should see three templates whose `postTypes` are "page", even though the actual post type is `post`.
- Select one of the templates.
- The post should fail to save.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/8c5b3002-5c2f-4726-a766-665ec488afb0

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by youknowriad**
closes #57112 

## What?

We recently moved the template swapping modal to the post editor, this highlighted a small issue where the list of available templates was hardcoding the templates that are available for the page post type. This PR fixes that by using the right post type to fetch the available templates.

## Testing Instructions

1- Edit a post in 2024 theme, you should only see the "post" specific templates in the swap template modal.
2- For pages, you should only see "page" specific templates.

### CODE REVIEW

File: packages/editor/src/components/post-template/hooks.js [hunk 1]
```diff
@@ -41,21 +41,21 @@ export function useAllowSwitchingTemplates() {
...
-function useTemplates() {
+function useTemplates( postType ) {
 	return useSelect(
 		( select ) =>
 			select( coreStore ).getEntityRecords( 'postType', 'wp_template', {
 				per_page: -1,
-				post_type: 'page',
+				post_type: postType,
 			} ),
 		[]
```
Comment (t-hamano) [inline packages/editor/src/components/post-template/hooks.js]: Does it make sense to add `postType` to avoid an eslint warning error regarding a dependency?

**Review by t-hamano — COMMENTED** [review]
LGTM!

- In the editor where the post type is `post`, I only see the "post" specific templates in the swap template modal.
- In the editor where the post type is `page`, I only see the "page" specific templates in the swap template modal.
- It works the same way when I create a custom post type and define it in `customTemplates` in theme.json.
- If I select any page in the Site Editor, I only see the "page" specific templates in the swap template modal.

**Review by ntsekouras — APPROVED** [review]
LGTM, thanks! We should add the `postType` in deps though as @t-hamano suggests.
