### PR TITLE
Editable: Fix splitting inline Editables using shift+enter

### LINKED ISSUE #1243: Text block: Failures when using shift+enter for adding line breaks
TinyMCE in WordPress presently requires that you use shift+enter to add a single line as opposed to adding a paragraph. Having this engrained into my muscle memory (though I realize a simple `enter` creates a single line break now, I was trying the same in the Text block only to encounter a couple issues:

1) When typing `First<shift+enter>second<shift+enter>third` there are three lines appearing in the block as expected, but the up arrow only allows me to to go up to the second line; it does not allow be to go up to the first line.

2) When switching to the Text tab, every line other than the first is lost:

```html
<!-- wp:core/text -->
<p>First</p>
<!-- /wp:core/text -->
```

### PR DESCRIPTION
**Pull request by youknowriad**
closes #1243 #1254 

In this PR, I'm proposing to split a text block if we hit shift+enter.
The current `shift+enter` behaviour is broken (see #1243 and #1254)

### CODE REVIEW

**Comment by iseulde** [comment]
So, enter behaves as it does now, shift+enter splits is right away?

**Comment by jasmussen** [comment]
I think I like this! Nice 👍 👍

**Comment by youknowriad** [comment]
@iseulde yes, that's the idea.

**Comment by iseulde** [comment]
Testing

**Comment by iseulde** [comment]
@youknowriad I changed it slightly so `shift+enter` in other inline Editables doesn't do anything. Atm it's broken there as well.

**Comment by youknowriad** [comment]
@iseulde nice, thanks

File: blocks/editable/index.js [hunk 1]
```diff
@@ -206,6 +206,14 @@ export default class Editable extends wp.element.Component {
 			event.preventDefault();
 			event.stopImmediatePropagation();
 		}
+
+		if ( event.keyCode === ENTER && event.shiftKey && this.props.inline ) {
```
Comment (aduth) [inline blocks/editable/index.js]: Can we include some more inline documentation describing what these various inline conditions are achieving? Seems like they'll be difficult to revisit in the future otherwise.

**Comment by iseulde** [comment]
There's another change that this PR is introducing: when you split with just enter, and merge the blocks back, there's a line break left over, whereas before it would merge without any line breaks and the caret at the place they are merged.

File: blocks/editable/index.js (hunk 1 above)
Comment (iseulde) [inline blocks/editable/index.js]: Adding some.

**Comment by youknowriad** [comment]
@iseulde Merging back without empty lines should be fixed now.

File: blocks/editable/index.js [hunk 2]
```diff
@@ -207,6 +207,8 @@ export default class Editable extends wp.element.Component {
 			event.stopImmediatePropagation();
 		}
 
+		// If we click shift+Enter on inline Editables, we should avoid creating `p` tags
```
Comment (iseulde) [inline blocks/editable/index.js]: It would also split two contenteditables into two, e.g. a heading will suddenly become two headings.

**Comment by iseulde** [comment]
Works well in various browsers.
Seeing another small inconsistency: pressing enter with an uncollapsed selection will delete the selection, while pressing shift+enter will delete _and_ split it. Not sure what the right behaviour should be.

**Review by ellatrix — APPROVED** [review]
