### PR TITLE
MetaBoxes: Saving meta boxes don't reset the comment/ping status

### LINKED ISSUE #4663: Allow Comments and Allow Pingbacks & Trackbacks settings do not save
## Issue Overview
`Allow Comments` and `Allow Pingbacks & Trackbacks` settings do not save when we publish/update the post.

## Steps to Reproduce (for bugs)
1. Create a new post or edit existing post.
2. Toggle `Allow Comments` and `Allow Pingbacks & Trackbacks` settings. Enable these settings.
3. Publish or Update post.
4. Reload the page and you can see that `Allow Comments` and `Allow Pingbacks & Trackbacks` settings not enabled.

WordPress v4.9.2
Gutenberg v2.0.0

## Expected Behavior
When you enable `Allow Comments` and `Allow Pingbacks & Trackbacks` settings then it should save.

## Current Behavior
Currently, `Allow Comments` and `Allow Pingbacks & Trackbacks` settings not enabled.

## Possible Solution
I've tried to debug the issue. When we publish or update post, first REST API called to update a post. In this request, `Allow Comments` and `Allow Pingbacks & Trackbacks` will save properly.

After this, another `fetch` request called to URL `http://example.test/wp-admin/post.php?post=438&action=edit&classic-editor=1&meta_box=1` to save meta boxes values. See https://github.com/WordPress/gutenberg/blob/master/editor/store/effects.js#L154

So in this request, `Allow Comments` and `Allow Pingbacks & Trackbacks` settings will be disabled. Because these settings do not available in request data. In this request, `wp_insert_post()` called again and `comment_status` and `ping_status` set to `closed` because not found in post data. See line no `3399-3408` -- `https://core.trac.wordpress.org/browser/trunk/src/wp-includes/post.php#L3399`

So this issue happened when saving meta boxes.

### LINKED ISSUE #4843: Comments and pingbacks on new posts are set to off and cannot be turned on
## Issue Overview
New posts created in Gutenberg have comments and pingbacks off regardless of the global setting, and attempts to turn them on in Gutenberg do not work. As a workaround, they can be turned on using Quick Edit in the list table. I ran a `git bisect` and it points to https://github.com/WordPress/gutenberg/commit/6dd01de8675b88626748f1773371065b0ec26591.

## Steps to Reproduce (for bugs)

1. Publish a new post. Note that comments and pingbacks are off.
2. Turn them on in the Dicussion panel and update.
3. View the post and note that comments are off.
4. Refresh the editor and note that both settings are still off.

## Expected Behavior
I would expect the post-level discussion settings to respect the global discussion setting and actually save changes.

## Related Issues and/or PRs
* #4184

### PR DESCRIPTION
**Pull request by youknowriad**
closes #4843 and closes #4663 

This PR fixes two related issues:

 - The meta boxes save was being triggered even if we didn't have any meta box enabled
 - The meta boxes save was resetting the ping/comments status due to legacy code on the backend. I ensured the post status and ping status are passed to the meta box request to avoid this.

**Testing instructions**

 - Add some metaboxes
 - Save your post
 - Refresh the page
 - The ping and comment status should stay enabled unless you disable them explicitely.

### CODE REVIEW

**Comment by youknowriad** [comment]
⌛️  I don't blame you :) no one wants to review meta boxes.

File: editor/store/effects.js [hunk 1]
```diff
@@ -498,11 +501,18 @@ export default {
 		}, {} );
 		store.dispatch( setMetaBoxSavedData( dataPerLocation ) );
 
+		// Additional data needed for backwards compatibility.
+		// If we do not provide this data the post will be overriden with the default values.
+		const additionData = []
```
Comment (gziolo) [inline editor/store/effects.js]: You can express it also as:

```js
const additionalData = [
    post[ 'comment_status' ] && `comment_status=${ post[ 'comment_status' ] }`,
    post[ 'ping_status' ] && `ping_status=${ post[ 'ping_status' ] }`,
].filter( Boolean );
```
I learned this trick with filter recently :)

**Review by gziolo — COMMENTED** [review]
Code looks good. I haven't tested yet.

File: editor/store/effects.js [hunk 2]
```diff
@@ -489,7 +492,7 @@ export default {
 		}, {} );
 		store.dispatch( setMetaBoxSavedData( dataPerLocation ) );
 	},
-	REQUEST_META_BOX_UPDATES( action, store ) {
+	REQUEST_META_BOX_UPDATES( { post }, store ) {
```
Comment (aduth) [inline editor/store/effects.js]: Does `post` need to come through the action, or could we assume that the value in `store.getState()` would be up to date by now?

File: editor/store/effects.js (hunk 1 above)
Comment (aduth) [inline editor/store/effects.js]: Typo: "addition" -> "additional"

File: editor/store/effects.js [hunk 3]
```diff
@@ -498,11 +501,18 @@ export default {
...
+
 		// To save the metaboxes, we serialize each one of the location forms and combine them
 		// We also add the "common" hidden fields from the base .metabox-base-form
-		const formData = values( dataPerLocation ).concat(
-			jQuery( '.metabox-base-form' ).serialize()
-		).join( '&' );
+		const formData = values( dataPerLocation )
+			.concat( jQuery( '.metabox-base-form' ).serialize() )
+			.concat( additionData )
+			.join( '&' );
```
Comment (aduth) [inline editor/store/effects.js]: Aside: Would it be easier to construct this with [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData) instead?

Unfortunately not possible to pass an object to its constructor, needs to iterate with [`FormData#append`](https://developer.mozilla.org/en-US/docs/Web/API/FormData/append).†

But it can be passed directly into `fetch`'s `body` property.

Above `jQuery.serialize` would need to be revised to [`jQuery.serializeArray`](https://api.jquery.com/serializeArray/).

I think `FormData` manages encoding too, unlike the current code here where we concatenate `post[ 'comment_status' ]` into the form without first `encodeURIComponent` (not likely a real-world issue).

_† There are helpers like [`object-to-formdata`](https://www.npmjs.com/package/object-to-formdata)_

File: editor/store/effects.js [hunk 4]
```diff
@@ -498,11 +501,18 @@ export default {
 		}, {} );
 		store.dispatch( setMetaBoxSavedData( dataPerLocation ) );
 
+		// Additional data needed for backwards compatibility.
+		// If we do not provide this data the post will be overriden with the default values.
+		const additionData = []
+			.concat( post[ 'comment_status' ] ? [ `comment_status=${ post[ 'comment_status' ] }` ] : [] )
```
Comment (aduth) [inline editor/store/effects.js]: Unnecessary square brackets here. Surprised this isn't a lint error.

File: editor/store/effects.js (hunk 3 above)
Comment (gziolo) [reply editor/store/effects.js]: I’m afraid FormData doesn’t work properly with our codebase. We polyfill fetch with very limited support for FormData. At least I had a few issues with a few weeks back.

Comment (gziolo) [reply editor/store/effects.js]: Please note the gaps for Edge and Safari: https://developer.mozilla.org/en-US/docs/Web/API/FormData.

File: editor/store/effects.js (hunk 2 above)
Comment (youknowriad) [reply editor/store/effects.js]: Yes, it's probably the same, I'll remove the post from the action

File: editor/store/effects.js (hunk 3 above)
Comment (youknowriad) [reply editor/store/effects.js]: I tried something similar the problem is that `serializeArray` doesn't return a nested array when we have array parameters instead it returns something like `{ "fields[foo]": "bar" }` which is not the correct object we want.

File: editor/store/effects.js (hunk 2 above)
Comment (gziolo) [reply editor/store/effects.js]: Is it? I mean, it might be the same. It all depends how all those `dispatch` actions are processed. This is quite tricky because you dispatch action in the middle of another dispatch. In the moment when you trigger `requestMetaBoxUpdates` action, the payload of `requestPostUpdateSuccess` is still processed, so there might be a different value in the store at that time. I think actions are dispatched asynchronously which means it should all end up as expected.

**Comment by youknowriad** [comment]
I'm merging this one as it's a necessary fix for the release.
