### PR TITLE
Fixes the default fluid value on the UI based on the global typography fluid value.

### LINKED ISSUE #64765: Font size presets inconsistent with the global fluid typography setting.
### Description

The font size preset UI is inconsistent regarding the global fluid typography setting. If the setting is not enabled, the fluid typography UI is still available to users, but the saved settings have no impact on the frontend because the fluid settings make no impact when the `"fluid":true` isn't set in the `settings.typography` path of the `theme.json` file.

Fixing this issue is an alternative to another issue: make the 'local' fluid setting work despite the global one. Depending on the decision on [#64766 Should a particular 'fluid' setting of a font size preset work if the global typography.fluid setting is not set or is false?](https://github.com/WordPress/gutenberg/issues/64766) we can close this issue as not valid.

### Step-by-step reproduction instructions

1. Use or create a theme **without** the `"fluid":true` set in the `settings.typography` path of the `theme.json` file.
2. Navigate to the typography settings of the editor.
3. Enter the font size presets and edit a font size preset.
4. Check that you can mark the fluid option of the font size preset.

This isn't consistent because despite adding those settings, they won't impact the rendering of the font sizes because the global `fluid` is not set.

### Screenshots, screen recording, code snippet

image

### Environment info

- Gutenberg trunk
- WordPress 6.6.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
Fixes the default fluid value on the UI based on the global typography fluid value.

## Why?
This PR makes the UI consistent with the default behavior of the fluid typography settings. If the global fluid setting `settings.typography.fluid` is defined as `true,` all the font size presets are rendered as fluid despite not being set as `fluid` explicitly. This PR reflects that in the UI. 

Fixes: https://github.com/WordPress/gutenberg/issues/64765

## How?
Considers the global fluid typography option to render and display the control correctly.

## Testing Instructions
1. Use a theme.json like this:
```json
{
	"settings": {
		"typography": {
			"fluid": true,
			"fontSizes": [
				{
					"name": "Theme font size 1",
					"size": "30px",
					"slug": "theme-1"
				}
			]
		}
	},
	"version": 3,
	"$schema": "https://schemas.wp.org/trunk/theme.json"
}
```
2. With this PR enabled, the `fluid` control should be rendered as true, and without this PR, it should render (incorrectly) as false.

## Screenshots or screencast 
Despite the `fluid` option not being explicitly defined in the font size preset, the UI will be checked because the behavior will be true because the global option is enabled.
```json
{
	"settings": {
		"typography": {
			"fluid": true,
			"fontSizes": [
				{
					"name": "Theme font size 1",
					"size": "30px",
					"slug": "theme-1"
				}
			]
		}
	},
	"version": 3,
	"$schema": "https://schemas.wp.org/trunk/theme.json"
}
```
image

### CODE REVIEW

**Review by ramonjd — APPROVED** [review]
Good catch. LGTM


| Trunk | This PR |
|--------|--------|
| Screenshot 2024-08-27 at 11 45 23 AM | Screenshot 2024-08-27 at 12 03 19 PM |

File: packages/edit-site/src/components/global-styles/font-sizes/font-size.js [hunk 1]
```diff
@@ -44,14 +44,17 @@ function FontSize() {
...
 	// Get the font sizes from the origin, default to empty array.
 	const sizes = fontSizes[ origin ] ?? [];
 
 	// Get the font size by slug.
 	const fontSize = sizes.find( ( size ) => size.slug === slug );
 
-	// Whether fluid is true or an object, set it to true, otherwise false.
-	const isFluid = !! fontSize.fluid ?? false;
+	// Whether the font size is fluid. If not defined, use the global fluid value of the theme.
+	const isFluid =
```
Comment (t-hamano) [inline packages/edit-site/src/components/global-styles/font-sizes/font-size.js:56]: Sorry for the late review. I noticed that it was already merged, but I'll comment just in case.

`settings.typography.fluid` is not necessarily a boolean value, but can be an object. That is, if the following theme.json is defined, `isFluid` will be an object:

```json
{
	"settings": {
		"typography": {
			"fluid": {
				"minFontSize": "16px"
			},
			"fontSizes": [
				{
					"name": "Theme font size 1",
					"size": "30px",
					"slug": "theme-1"
				}
			]
		}
	},
	"version": 3
}
```


We might want to change it to the following to ensure that `isFluid` is always a boolean value:

```javascript
fontSize.fluid !== undefined ? !! fontSize.fluid : !! globalFluid;
```

However, the current implementation works fine for now.

Comment (ramonjd) [reply packages/edit-site/src/components/global-styles/font-sizes/font-size.js:56]: Good point, thanks for catching.

Comment (matiasbenedetto) [reply packages/edit-site/src/components/global-styles/font-sizes/font-size.js:56]: Thanks for noticing that @t-hamano.
I submitted the fix: https://github.com/WordPress/gutenberg/pull/64882
