### PR TITLE
Restore block prop for BlockListBlock filter

### LINKED ISSUE #12938: Removing getBlock from the BlockListBlock component breaks back compat
**Describe the bug**

#11899 broke back compat, which is manifesting as breaking any custom blocks registered through ACF.

**To Reproduce**
1. Install and activate ACF Pro 5.8 Beta 3
2. Register a custom block in a plugin:

```php
acf_register_block(array(
	'name'				=> 'testimonial',
	'title'				=> __('Testimonial'),
	'description'		=> __('A custom testimonial block.'),
	'render_callback'	=> 'my_acf_block_render_callback',
	'category'			=> 'formatting',
	'icon'				=> 'admin-comments',
	'keywords'			=> array( 'testimonial', 'quote' ),
));
function my_acf_block_render_callback() {
	echo 'foo';
}
```

3. Click on the "Start writing" block.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #12938

Plugins used to be able to access the `block` prop in the `BlockListBlock` filter which was inadvertently removed when we moved the filter. The intention for this filter was to only allow plugins to use `clientId` and with this, and using selectors they can retrieve any information about the blocks.

This PR restores the `block` props for backward compatibility purpose.

**Testing instructions**

 - Repeat instructions in #12938

### CODE REVIEW

File: packages/editor/src/components/block-list/block.js [hunk 1]
```diff
@@ -776,7 +774,25 @@ const applyWithDispatch = withDispatch( ( dispatch, ownProps, { select } ) => {
 	};
 } );
 
+const getBlock = memize( ( name, attributes ) => {
```
Comment (jorgefilipecosta) [inline packages/editor/src/components/block-list/block.js]: I may be missing something but aren't we creating a memory leak where name and attributes are never clean up and stay in memory forever?

Comment (jorgefilipecosta) [reply packages/editor/src/components/block-list/block.js]: If a memory leak exists I think one possible way to solve it would be something like:
```
	(() => {
	const getBlock = memize( ( name, attributes ) => {
	...
	}, { maxSize: 1 } );
	return withSelect( ( select, { clientId } ) => {
		const { getBlockName, getBlockAttributes } = select( 'core/editor' );
		const name = getBlockName( clientId );
		const attributes = getBlockAttributes( clientId );
		return {
			block: getBlock( name, attributes ),
		};
	} )
})(),
```

This way we would memoize only the last name attribute pair per BlockListBlock.

File: packages/editor/src/components/block-list/block.js [hunk 2]
```diff
@@ -776,7 +774,25 @@ const applyWithDispatch = withDispatch( ( dispatch, ownProps, { select } ) => {
...
 export default compose(
+	// This withSelect is only necessary for backward compatibility
+	// Users of the editor.BlockListBlock filter used to be able to access the block prop
+	// Ideally these blocks would rely on the clientId prop only.
+	withSelect( ( select, { clientId } ) => {
+		const { getBlockName, getBlockAttributes } = select( 'core/editor' );
+		const name = getBlockName( clientId );
+		const attributes = getBlockAttributes( clientId );
+		return {
+			block: getBlock( name, attributes ),
```
Comment (jorgefilipecosta) [inline packages/editor/src/components/block-list/block.js]: To note that there is still some risk because getBlock selector returned innerBlocks and now the block object does not contain innerBlocks. I'm not sure about what the best approach would be as calling getBlock selector would reduce the performance gain we had. But developers using the filter may find strange that this block object does not contain the innerBlocks property.

File: packages/editor/src/components/block-list/block.js (hunk 1 above)
Comment (youknowriad) [reply packages/editor/src/components/block-list/block.js]: The issue with this is if you have multiple blocks on the page, you'll keep invalidating them as you'll only keep one set of arguments. Unless I'm misunderstanding the `maxSize` property.

File: packages/editor/src/components/block-list/block.js (hunk 2 above)
Comment (youknowriad) [reply packages/editor/src/components/block-list/block.js]: Yes, the idea here should be to mark this prop as deprecated, I'm not sure how we can do that exactly. But if people want to full object or anything else, they should rely on `clientId` instead.

**Review by gziolo — DISMISSED** [review]
This fix looks legit, it would be nice to get confirmation from @aduth whether using `memize` doesn't introduce any issues. I sense that we should be using Weak Map instead but I'm also not quite sure how it would look implementation wise :)

File: packages/editor/src/components/block-list/block.js [hunk 3]
```diff
@@ -776,7 +774,25 @@ const applyWithDispatch = withDispatch( ( dispatch, ownProps, { select } ) => {
...
+		};
+	} ),
 	withFilters( 'editor.BlockListBlock' ),
```
Comment (gziolo) [inline packages/editor/src/components/block-list/block.js]: Do we really need to keep `withFilters( 'editor.__experimentalBlockListBlock' )`? It looks like it can be also re-created using the public filter. I might be missing something though.

File: packages/editor/src/components/block-list/block.js (hunk 1 above)
Comment (aduth) [reply packages/editor/src/components/block-list/block.js]: You're right, this is a memory leak. We'll create a new cache entry for every change to a block's attributes (every keypress) which will never be cleared.

File: packages/editor/src/components/block-list/block.js [hunk 4]
```diff
@@ -776,7 +774,25 @@ const applyWithDispatch = withDispatch( ( dispatch, ownProps, { select } ) => {
...
+		name,
+		attributes,
+	};
+} );
+
 export default compose(
+	// This withSelect is only necessary for backward compatibility
+	// Users of the editor.BlockListBlock filter used to be able to access the block prop
+	// Ideally these blocks would rely on the clientId prop only.
+	withSelect( ( select, { clientId } ) => {
```
Comment (aduth) [inline packages/editor/src/components/block-list/block.js]: Prior to #11899, `withFilters( 'editor.BlockListBlock' )` occurred after `applyWithSelect` . Could we / shouldn't we do the same here, rather than creating a separate `withSelect` (which will also incur another per-block store subscription)?

File: packages/editor/src/components/block-list/block.js (hunk 1 above)
Comment (youknowriad) [reply packages/editor/src/components/block-list/block.js]: It should be fixed now.

File: packages/editor/src/components/block-list/block.js (hunk 4 above)
Comment (youknowriad) [reply packages/editor/src/components/block-list/block.js]: Restored the order.

File: packages/editor/src/components/block-list/block.js (hunk 3 above)
Comment (youknowriad) [reply packages/editor/src/components/block-list/block.js]: Restored the order, this filter is useless now.

**Comment by gziolo** [comment]
Moving forward, we need to rethink how to take over control what can be passed to the filtered component. Ideally, we should seek a way to abstract away all usages of filters in Gutenberg. It never occurred to me before how bad it can become if the number of props passed to the filter introduced `withFilter` grow over time.

**Comment by youknowriad** [comment]
Also, we should explore separately how to catch errors in `withFilter` callbacks and ignore the filters entirely instead of breaking the whole editor.

**Review by aduth — APPROVED** [review]

**Review by aduth — APPROVED** [review]

**Comment by youknowriad** [comment]
Tests are funky at the moment. I'm going to merge while we figure out what's wrong with our test setup.
