### PR TITLE
Fix: DateTimePicker passes current seconds as the selected seconds value

### LINKED ISSUE #13898: Missing seconds when planning a post
**Describe the bug**
When scheduling a post, a random (actually current) seconds are saved in the database. When WP_CRON is disabled and the linux crontab runs every minute exact on 00 seconds, this causes some posts to be missed.

Can we add also seconds in the planning block?

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Closes: https://github.com/WordPress/gutenberg/issues/13898

DateTimePicker does not allow users to pick a value for seconds, so when the user changes a time/date, it should look like a value of 0 was selected as the seconds value. Currently, the seconds of the current date are passed as the selected seconds, which may make it look like a "random" value was selected as the seconds value.

This causes a regression where WP_CRON missed some scheduled posts.

## How has this been tested?
I created a new post.
I changed the date/time fields in the post scheduling dialog and I verified with redux dev tools that the editPost action contained a date whose seconds were equal to 0.

### CODE REVIEW

**Comment by gziolo** [comment]
This PR needs to be rebased with `master` to make Travis green again :)

**Comment by jorgefilipecosta** [comment]
Hi @gziolo this PR was rebased.

**Comment by mapk** [comment]
This is great! Thanks for fixing @jorgefilipecosta!

**Comment by katsar0v** [comment]
Any update on this?

**Comment by noisysocks** [comment]
> This causes a regression where WP_CRON missed some scheduled posts.

Could you elaborate on this? What causes cron to miss the posts?

**Comment by katsar0v** [comment]
> Could you elaborate on this? What causes cron to miss the posts?

I explained it here - https://github.com/WordPress/gutenberg/issues/13898#issuecomment-499254340
But will try again. There are missed schedules (e.g.: https://www.hostinger.com/tutorials/how-to-fix-wordpress-missed-schedule) and there is this famous plugin which fixes it all: https://github.com/sLaNGjI/wp-missed-schedule

Use case: I setup wordpress to use system cron (setup a cronjob calling the wp-cron every minute for example). After setting up the cronjob I plan a post for the next week on 20:00. The time in database stored is 20:00:43 (43 in this case is seconds, fully random, but in fact this are my browser seconds).
Now the cronjob runs every minute and starts on the 0th second. If the cronjob is calling the url via http it might take longer than calling the wp-cron.php via php process (but that's an edge case). When the cron job starts next week on 20:00 the post is *not being* published, because local time is 20:00:01 (time of cron job execution) but the post should be published on 20:00:43 (remember the 43 seconds?).
Now the next time the cron job runs (on 20:01) the post *does not* get published as well and wordpress says "missed schedule" which really annoys me and probably thousands of other WP users...

File: packages/components/src/date-time/time.js [hunk 1]
```diff
@@ -62,6 +63,12 @@ class TimePicker extends Component {
 		}
 	}
 
+	changeDate( newDate ) {
```
Comment (aduth) [inline packages/components/src/date-time/time.js]: Might be nice for some docs, even if there's plenty of prior art of no documentation in this component.

**Review by aduth — APPROVED** [review]
Looks good. A nice refactor of some duplicate logic too 👍
