### PR TITLE
List Block: Fix the top empty list item deletion

### LINKED ISSUE #56223: List Block: deleting an empty list block at the top of a list deletes all items within it
Using WP 6.4.1 with or without GB 17.0.2, when you delete an empty list block at the very top of a list with sub list items underneath, it deletes every single item in the list:

https://github.com/WordPress/gutenberg/assets/26996883/40eee630-fac8-492a-ab18-03a192484c73

My expectation would be that it would just delete the top level item and then move the sub items into their own top level list item status.

### PR DESCRIPTION
**Pull request by Mamaduka**
## What
Closes #56223.
Alternative to #71482.

PR fixes the content loss issue when a user tries to delete an empty list item that has a child list and items.

## Why?
The `useMerge` hook tried to handle this via `onMerge > moveFirstItemUp`, but it currently can't handle complex nested items.

## How?
I tried to re-use the `outdentListItem` method, which is the difference between this PR and #71482. The remaining changes are just conversions to early returns.

## Testing Instructions
1. Open a post or page.
2. Paste the test content.
3. Deleting an empty top-level list item should outdent its children.

<details><summary>Test Blocks</summary>
<p>

```html
<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li><!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>Item</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Item</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Item<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>Testing</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Testing</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Testing</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>List 2<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>Item</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Item</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Item</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->
``` 

</p>
</details> 

### Testing Instructions for Keyboard
Same.

## Screenshots or screencast 

**Before**

https://github.com/WordPress/gutenberg/assets/26996883/40eee630-fac8-492a-ab18-03a192484c73

**After**

https://github.com/user-attachments/assets/c82a6861-aed3-4509-aa41-a2e2a372bd43

### CODE REVIEW

File: packages/block-library/src/list-item/hooks/use-merge.js [hunk 1]
```diff
@@ -132,12 +134,26 @@ export default function useMerge( clientId, onMerge ) {
...
+
+			const blockOrder = getBlockOrder( clientId );
+			if (
+				isUnmodifiedBlock( getBlock( clientId ) ) &&
+				blockOrder.length > 0
+			) {
+				registry.batch( () => {
+					outdentListItem( getBlockOrder( blockOrder[ 0 ] ) );
+					removeBlock( clientId, true );
+				} );
```
Comment (Mamaduka) [inline packages/block-library/src/list-item/hooks/use-merge.js:156]: @ellatrix, what do you think about this solution?

Comment (ellatrix) [reply packages/block-library/src/list-item/hooks/use-merge.js:156]: Should we check for 'content' modification like your other PR?

But logically speaking, this seems fine

**Review by ellatrix — APPROVED** [review]
Haven't tested, but based on the code and e2e test, this looks good

File: packages/block-library/src/list-item/hooks/use-merge.js (hunk 1 above)
Comment (Mamaduka) [reply packages/block-library/src/list-item/hooks/use-merge.js:156]: Good point.

**Comment by Mamaduka** [comment]
Thanks for the review, Ella!
