### PR TITLE
Fix some JAWS bugs

### LINKED ISSUE #29526: Unable to edit blocks once they've been inserted into content while using a screen reader
Please fill out ALL required sections. Bug reports with missing information will
be closed.

Before submitting a bug report:

- Check if the bug has already been fixed by updating WordPress and/or Gutenberg.
- Check if the bug is caused by a plugin by deactivating all plugins except Gutenberg.
- Check if the bug is caused by a theme by activating a default theme e.g. Twenty Twenty.
- Check if the bug has already been reported by searching https://github.com/WordPress/gutenberg/issues.

If this is a security issue, please report it in HackerOne instead:
https://hackerone.com/wordpress
-->

## Description

As of WordPress V. 5.6 and including 5.6.1 and 5.6.2, screen reader users are unable to edit blocks after they have been inserted into a post or page. NVDA will allow some flaky editing of some of the less advanced blocks, but not things like the table block, Narrator allows editing of zero of the blocks, reporting "unable to take focus", and Jaws for Windows reads all text as blank whether you tab from the title field or down-arrow from it. The only thing that will read with Jaws is the blocktype: ("block heading group", "block paragraph group", ETC.).
## Step-by-step reproduction instructions

Open the "add new post" or "add new page" or "edit post" or "edit page" screen. Press "E" to navigate to the title field and then press enter on this to enter forms mode or your screen reader's equivalent. Tab or arrow to the content area where already-entered content is.

## Expected behaviour

Expectation is that I should be able to read the text within blocks, select, copy, cut, and paste as in either the Classic Editor or any other form field on the web.

## Actual behaviour

Screen reader speaks the word "blank" while navigating through what I know for a fact to be entered text. This can be determined by exiting forms mode and then arrowing through the page. Block types are the only things that read: "block heading group" "block paragraph group" ETC.).

## WordPress information
- WordPress version: 
- Gutenberg version: Version shipping with stable WordPress 
- Are all plugins except Gutenberg deactivated? Yes. 
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes. 

## Device information
- Device: 
- Operating system: 
- Browser: Firefox 86.0 and two versions back, Google Chrome 88 and two versions back, Microsoft Edge shipping with latest stable build of Windows 10, screen readers: Jaws 2021, Jaws 2020, Jaws 2019, NVDA 2020.4, NVDA 2020.3, Narrator shipping with latest stable build of Windows 10 

See issue #23892 https://github.com/WordPress/gutenberg/issues/23892 where multiple members of the WordPress Accessibility Team as well as outside accessibility experts and ordinary users of assistive technology and/or low-vision users warned that playing around with the focus outlines for blocks would produce results like this.

### PR DESCRIPTION
**Pull request by alexstine**
## Description

Fixes #29526

1. JAWS will now have the ability to use Gutenberg navigation mode and here the blocks announced via Tab.
2.Removed broken speak() function call that was only working part of the time.
3. Remove the wordpress/a11y package. No longer needed.
4.Replace `role="group"` with `role="document"` for better block editing experience in earlier versions of JAWS. 
 
## How has this been tested?

I have tested using NVDA and JAWS on Windows 10. I tested using Voiceover on Mac. All seems to be in working order.

## Types of changes

Hopefully some much needed Bug fixes.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by alexstine** [comment]
Anyone know why these last 2 e2e tests are failing? I thought I had fixed them all running the tests locally, but maybe I missed something?

File: packages/block-editor/src/components/block-list/use-block-props/index.js [hunk 1]
```diff
@@ -151,7 +151,7 @@ export function useBlockProps( props = {}, { __unstableIsHtml } = {} ) {
 		ref: mergedRefs,
 		id: `block-${ clientId }${ htmlSuffix }`,
 		tabIndex: 0,
-		role: 'group',
+		role: 'document',
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-list/use-block-props/index.js:154]: Was trying to read a bit about this change here https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Document_Role it does seem to be a bit impactful. The link seem to suggest that the role is more suited for elements that should be read and not interacted with and this is not the case for blocks as we should be able to navigate inside blocks and interact with them in different ways depending on the block.

Would you mind sharing more about this change, Is this just for the navigation mode? I wonder if it's something that could have a bad impact on edit mode.

File: packages/block-editor/src/components/block-tools/block-selection-button.js [hunk 2]
```diff
@@ -90,13 +80,6 @@ function BlockSelectionButton( { clientId, rootClientId, blockElement } ) {
 	// Focus the breadcrumb in navigation mode.
 	useEffect( () => {
 		ref.current.focus();
-
-		// NVDA on windows suffers from a bug where focus changes are not announced properly
-		// See WordPress/gutenberg#24121 and nvaccess/nvda#5825 for more details
-		// To solve it we announce the focus change manually.
-		if ( isWindows() ) {
-			speak( label );
-		}
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-tools/block-selection-button.js:99]: I'm really curious why this has been removed and replaced with the `aria-live` attribute, they are supposed to have the same result. I think you mentioned that `speak` was `undefined` for you, is that right? This would mean that there's probably an issue elsewhere that could have larger impacts.

File: packages/block-editor/src/components/block-list/use-block-props/index.js (hunk 1 above)
Comment (alexstine) [reply packages/block-editor/src/components/block-list/use-block-props/index.js:154]: @youknowriad No, this is to make older versions of JAWS work in edit mode. From my testing, I can't see that it has hurt in anyway how screen readers interact with the block. However, I flagged this for the Accessibility Team to test that way we can be confident that it has been tested on different systems.

File: packages/block-editor/src/components/block-tools/block-selection-button.js (hunk 2 above)
Comment (alexstine) [reply packages/block-editor/src/components/block-tools/block-selection-button.js:99]: @youknowriad Yes, whenever I did a

`console.log( speak( label ) );`

it came back undefined 90% of the time when it was supposed to be called. I have a feeling this is related to how the React hook is used in combination with useEffect(). If I understand it right, useEffect() will run directly after the component is rendered so if that's the case, speak() may not be callable at this point. Instead, I just added the attribute directly to the button because the dynamic change that occurs with Tab key triggers the aria-live region to announce to screen readers. This is an easy fix in comparison to all the debugging that may have to be done to figure out why wordpress/a11y.speak() is having trouble in this context. It's an easier solution so I think it's fine to go with it.


https://www.freecodecamp.org/news/beginners-guide-to-using-react-hooks/

Comment (alexstine) [reply packages/block-editor/src/components/block-tools/block-selection-button.js:99]: I also tried to create a timeout function there to see if waiting some time would allow me access to speak() more reliably, but no dice on that either.

Comment (youknowriad) [reply packages/block-editor/src/components/block-tools/block-selection-button.js:99]: `speak` function doesn't return anything meaning calling `console.log( speak( label ) );` will always print `undefined` in the console, but this doesn't mean the function didn't work. `speak` works by changing the content of a DOM element with the following class `a11y-speak-polite` at the end of the DOM

Comment (alexstine) [reply packages/block-editor/src/components/block-tools/block-selection-button.js:99]: @youknowriad No, I am certain it didn't work. The only time the speak() function seems to be fired is win tabbing from the title field to the first block or from the post options sidebar after the block list, Shift+Tab. Other than that, just tabbing through the list does not trigger the region. It does not announce or change, you can view this with the web inspector.

Also, I tried changing the 2nd arg to "assertive" and still no luck.

`speak( label, 'assertive' );`

I was just trying with console.log() to see if I could find the issue but it lead to nothing. I am still convinced it may have something to do with useEffect().

All I can say for certain is the speak() function only fires sometimes, it doesn't work all the time. E.g. if you have a list of 10 blocks, it will fire on block 1 and block 10 (Shift+Tab) but nowhere else during the list.

**Comment by joedolson** [comment]
Tested this with NVDA/Chrome and NVDA/Firefox, and it worked OK. On Chrome, it triple read every block. That's potentially annoying, but it's not a problem at the scale of what this patch fixes.

File: packages/block-editor/src/components/block-tools/block-selection-button.js (hunk 2 above)
Comment (tellthemachines) [reply packages/block-editor/src/components/block-tools/block-selection-button.js:99]: I played around with this a bit and you're right, @alexstine , the problem is with useEffect. It's only running once, when the component first renders, but it should run every time the label changes. We can fix this by adding the label variable inside the square brackets passed as the second parameter of useEffect. For this to work, we'll also have to move the declaration of the label variable to just before useEffect is called, and we should probably move the declaration of blockType too as that variable is only used in computing the value of label. 

We should still remove the `isWindows()` condition, as this issue is also reproducible on Mac with VoiceOver.

The default "polite" value for `speak()` worked well for me on VoiceOver after these changes.

**Review by tellthemachines — COMMENTED** [review]
Tested with NVDA on Windows 10 and VoiceOver on mac and this is working well!  I left a comment with suggested changes so we can continue using the `speak` function instead of using `aria-live` directly. 

The remaining e2e failures are in places where we're searching for elements by aria role and expecting a block to have a group role, so searching in the whole project for any remaining `role: 'group'` should give you all the instances that still need changing. If you'd like any help with this, let me know!

File: packages/block-editor/src/components/block-tools/block-selection-button.js (hunk 2 above)
Comment (alexstine) [reply packages/block-editor/src/components/block-tools/block-selection-button.js:99]: Fixed.

**Comment by alexstine** [comment]
Can I get a final review on this? I believe I've addressed all concerns and thank you to @tellthemachines for showing me the way with this weird useEffect() bug. Now that label is used as an arg, it only fires speak() when label changes.

Addressing @joedolson feedback:

The only other way to fix the repeating NVDA announcement is to completely restructure how Gutenberg does this. Instead of a dynamically updating button, it should be a list of regular buttons. Sadly, this was a bit of a poor implementation and maybe in the future it can be re-worked. That is a discussion for a bigger issue and different PR. Navigation mode should completely transform the screen and present a list of blocks similar to how the List View works.

Thanks all. 🥇

**Review by youknowriad — APPROVED** [review]
Assuming we're ok with the role change for a11y team. The changes here look good to me.

**Comment by alexstine** [comment]
I personally think it works fine with all screen readers I've tested with. It is certainly a big improvement from where it was. 👍

**Comment by joedolson** [comment]
Based on my testing, it at worst makes one AT combination a little more annoying, but it fixes an issue in another combination that made the feature unusable. So it's a win.
