### PR TITLE
Show the default style variation if none provided

### LINKED ISSUE #23822: Block Editor: Arrow up/down keys get intercepted by the block list when a block is selected
**Describe the bug**

This bug might be difficult to reproduce as presented in the screencasts recorded. It only happens when one fo the block is selected and in Edit mode.

**To reproduce**
The most possible steps to reproduce the behavior:
1. Open a post with multiple blocks.
2. Move focus to one of the blocks in the middle that is in Edit mode and move focus to the toolbar.
3. Use arrow keys to go to the toolbar item that has a dropdown menu, use arrows up/down and observe that the drodpown randomly closes and the focus moves to the block.

It might require several tries, but I'm able to reproduce it also in the header section with other dropdown menus.

**Expected behavior**
Arrow up/down never moves focus out of the toolbar when navigating in dropdown menu between items.

**Screenshots**

The issue exists for both the floating toolbar and when docked to the top.

toolbar-arrows-dropdowns

toolbar-arrows-dropdowns-floating

**Editor version (please complete the following information):**
- WordPress version: WordPress 5.5.0-beta.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes? Gutenberg plugin, the latest `master` branch

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
- Version: 13.1.1

### LINKED ISSUE #24147: The "Default" style is gone from WordPress 5.5.
Thank you for always improving Gutenberg.

The "Default" style is gone from WordPress 5.5.

If you added your own block style from the theme or plugin side, the "default" style was displayed automatically until now.

Since this is gone, the block style cannot be undone.

Is this a specification?

If you add the "default" style for 5.5 or later, you will see two "default" styles before 5.4, which is a little troublesome.

I want to know why it was changed like this.

**Screenshots**

WordPress 5.4
スクリーンショット 2020-07-23 13 03 47

WordPress 5.5
スクリーンショット 2020-07-23 13 05 23

### PR DESCRIPTION
**Pull request by youknowriad**
closes #24147 

The logic to add default style variations was only checking the "blockType.styles" property and not the registered styles.

**Testing instructions**

 - Add a style variations to the list block like so

```
wp.blocks.registerBlockStyle( 'core/list', {
	name: 'test',
	label: 'Test',
} );
```

 - The default style variation should be also  added to the block styles switcher.

### CODE REVIEW

**Comment by StefanXhunga** [comment]
I need to be those  requested changes

**Comment by youknowriad** [comment]
@StefanXhunga I'm not sure I understand your message?

File: packages/block-editor/src/components/block-styles/index.js [hunk 1]
```diff
@@ -110,18 +110,21 @@ function BlockStyles( {
 		return null;
 	}
 
-	if ( ! type.styles && ! find( styles, 'isDefault' ) ) {
```
Comment (ocean90) [inline packages/block-editor/src/components/block-styles/index.js:113]: Looks like you already knew it two years ago :) https://github.com/WordPress/gutenberg/pull/12519/files#r240045926

**Comment by ItsJonQ** [comment]
Screen Shot 2020-07-27 at 10 14 01 AM

Changes look good to me! Tested it locally, (using the supplied test code), and it looks like it worked as expected 👍

**Review by ItsJonQ — APPROVED** [review]
🚀 from me! Changes look good to me! Tested it locally, (using the supplied test code), and it looks like it worked as expected 👍

Screen Shot 2020-07-27 at 10 14 01 AM

File: packages/block-editor/src/components/block-styles/index.js (hunk 1 above)
Comment (nosolosw) [reply packages/block-editor/src/components/block-styles/index.js:113]: Ah, so what happened was that by [setting](https://github.com/WordPress/gutenberg/pull/22849/files#diff-33e0ac9c44b16a617039a563d4c065f3R170) `[]` as default for `styles`, the `!type.styles` was no longer true. :+1:
