### PR TITLE
Global Styles: Fix push-to-global-styles clearing of attributes, border fallbacks, link hover colors, and behaviors

### LINKED ISSUE #48048: Featured Image block: applying styles globally resets the border changes in the editor
### Description

When using the apply globally feature with the featured image block, some style options are reset and not properly pushed globally. In particular, it seems border isn't properly moved over but there could be others. This was initially found as part of the FSE Outreach Program's twentieth call for testing:

>When making changes to a block, e.g., Featured Image Block, and going to the block setting -> Advanced and choosing “Push changes to Global Styles,” the changes I applied (such as a border) are removed from the Site Editor, but it applied on the live Posts.

### Step-by-step reproduction instructions

1. Open Appearance > Editor.
2. Click "Edit" to edit the home template.
3. Edit a featured image block and add various styling options, including duotone and border changes.
4. Notice that the duotone options stick around but that the border option is reset both in the editor and on the front end, despite showing as having changes to border in the Styles interface. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/218580042-562085d4-932a-43ec-ae93-3946f089b999.mov

Meanwhile, in Styles, there are border changes listed for the post featured image that aren't appearing:

Screen Shot 2023-02-13 at 1 37 34 PM

### Environment info

- WP 6.2-beta1-55308
- Both with and without GB 15.1 installed
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Fixes: https://github.com/WordPress/gutenberg/issues/48048

## What?

- Adds fallback default border style when applying block styles globally so a visual border is maintained
- Fixes pushing of border styles to global styles
- Fixes resetting of block attributes for presets when applying globally
- Cleans updated block style attribute to remove empty objects that were left behind
- Fixes pushing link hover colors
- Fixes clearing of behavior attributes
- Updates hook dependencies to satisfy linter (needs extra testing to ensure no regressions)

## Why?

Currently, the pushing of block instance styles to global styles doesn't work for borders creating unexpected UX.

## How?

- When determining the changes that need to be pushed to the user's global styles, we apply the required global styles logic to border styles (e.g. global styles needs longhand config).
- Border style fallbacks are only added if the side doesn't already have one in global styles to maintain prior selections
- Updates the config arrays so that border color preset values are added to the changes correctly
- Clears preset block attribute values from the updated block attributes
- Handle case where single support key for `linkColor` needs to check two style properties for changes
- Fix snackbar undo actions to also undo clearing of attributes

## Testing Instructions

1. Replicate the original issue before checking out this PR. See https://github.com/WordPress/gutenberg/issues/48048 for further info.
2. In the site editor, select an individual block that has border support e.g. Featured Image or Group
3. Apply a border width or color only to that block, note that the editor shows a visual border
4. Switch to the settings tab and expand the Advanced panel revealing the `Apply globally` button
5. Click "Apply globally" and confirm that the border remains visible as before in the editor, including color application now being fixed
6. Switch back to the styles tab and ensure that the border controls there are now reset
7. Navigate to Global Styles > Blocks > and then to the block type you styled
8. Confirm that block type's border controls now show the color or width you selected, along with the default border style
9. Repeat the process however this time set a dashed or dotted border style and confirm that border style is retained throughout
10. Test the application of block styles global setting all available color and font preset values e.g. text, background, gradient, border color, font size, font family etc. Confirm that now when you apply those styles globally, the block's attribute has been reset.
11. Test setting global styles first, then updating a block instance style before applying the block styles globally e.g. https://github.com/WordPress/gutenberg/pull/51621#issuecomment-1596572371
12. Test with varied border configs per side ensuring they are applied as expected globally.
13. Make sure that block instance styles are correctly applied globally when the block has per-side config, the global styles are using shorthand, and vice versa.
14. Confirm that when configuring per-side borders on a block instance the border style attributes are properly cleaned from the block attributes.
15. Test that after applying block styles globally, the undo link in the snackbar notice works correctly. In particular, ensure that preset attribute values are reinstated.
16. Test that block gap styles trigger the activation of the "Apply Globally" button and that they are successfully pushed to global styles and cleared from the block instance when the button is clicked.
17. Confirm link hover color is successfully pushed and cleared from block instance
18. Confirm pushed behaviours are also cleared

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/60436221/999bae6a-3d50-4083-9e9c-790009086448

### CODE REVIEW

File: packages/edit-site/src/hooks/push-changes-to-global-styles/index.js [hunk 1]
```diff
@@ -96,27 +98,33 @@ const STYLE_PATH_TO_PRESET_BLOCK_ATTRIBUTE = {
...
+		// To ensure display of a visible border, global styles require a
+		// default border style if a border color or width is present.
+		const { color, style, width } = attributes.style?.border || {};
+
+		if ( ( color || width ) && ! style ) {
+			changes.push( { path: [ 'border', 'style' ], value: 'solid' } );
+		}
+
+		return changes;
+	}, [ supports, attributes ] );
```
Comment (aaronrobertshaw) [inline packages/edit-site/src/hooks/push-changes-to-global-styles/index.js]: Unused dependency removed to satisfy linter. I couldn't see any regressions but worth flagging in case I missed something.

File: packages/edit-site/src/hooks/push-changes-to-global-styles/index.js [hunk 2]
```diff
@@ -182,7 +200,16 @@ function PushChangesToGlobalStylesControl( {
...
+	}, [
+		changes,
+		attributes,
+		userConfig,
+		name,
+		createSuccessNotice,
+		setAttributes,
+		setUserConfig,
+		__unstableMarkNextChangeAsNotPersistent,
+	] );
```
Comment (aaronrobertshaw) [inline packages/edit-site/src/hooks/push-changes-to-global-styles/index.js]: Missing dependencies added to keep linter happy.

**Comment by t-hamano** [comment]
Thanks for the PR, @aaronrobertshaw!


I have tried applying various styles globally. Perhaps some of them are not included in the scope of this PR, but they are listed below.

---

The "Apply globally" button is not enabled when I change the Block Spacing of the block. If I change other styles, that button is enabled, but it is not reflected in the global style. This problem also occurs with trunk.

<details><summary>Recorded Video</summary>

https://github.com/WordPress/gutenberg/assets/54422211/1879108c-97a2-4996-b5d1-ccb35aa1c3f7

</details> 

If you apply only a border color to a block, its border will be rendered. However, if you push that style globally, the border will disappear. In trunk, if only the border color is changed, the "Apply globally" button cannot be pressed.

<details><summary>Recorded Video</summary>

https://github.com/WordPress/gutenberg/assets/54422211/49dbeeda-161f-49d0-877b-bf7232dca11f

</details> 

If you specify a custom value for the border color and push it globally, an error is logged in the browser console. In trunk, if you change only the border color, the "Apply globally" button cannot be pushed, but if you change other styles (such as margin) and push globally, the same error is logged.


<details><summary>Recorded Video</summary>

https://github.com/WordPress/gutenberg/assets/54422211/03383a23-6a20-4391-99a9-64ebfa3ead13

</details>

**Comment by ramonjd** [comment]
I was trying the reverse and think I found a bug: setting global border styles to a group block, then applying local block border changes globally doesn't work. The bug is also in trunk, so I'm not sure what the scope of this branch is. 

1. In the Site editor, edit a template with some group blocks
2. Apply group block border width and color in global styles
3. Save - The editor and frontend match 👍 
4. Now click on a single block and adjust its border width and color styles. Select a custom color.
5. Apply these globally
6. Styles are not applied, and when adding a custom color and width the Group block edit.js throws an error

> Removing a style property during rerender (borderColor) when a conflicting property is set (borderBottomColor) can lead to styling bugs. To avoid this, don't mix shorthand and non-shorthand properties for the same value; instead, replace the shorthand with separate values.


<details>

<summary>Screencast</summary>




</details>

**Comment by aaronrobertshaw** [comment]
Thanks for the testing and reviews. I've also just been working on a fix for pushing split borders i.e. borders with different configurations per side. 

Block gap isn't included in the `__EXPERIMENTAL_STYLE_PROPERTY` constant so doesn't get picked up in the changes as determined by `useChangesToPush`. Furthermore, there are a number of other supports and styles that aren't in that constant e.g. filter, shadow etc. I'm not clear on when that was added and if there are any reasons why some things were left out.

For this PR, I think it would be best to now limit the scope to just the border styles, and address each other style/support in a follow up.

**Comment by aaronrobertshaw** [comment]
> Styles are not applied, and when adding a custom color and width the Group block edit.js throws an error

I can replicate the application of a block instance's styles not overriding pre-existing global styles but I can't get the error at all. 

I'll keep digging but it might be a few days before I can devote too much time to this. Given this is bug related we should still be able to get it merged within the next GB beta period.

**Comment by aaronrobertshaw** [comment]
> I'll keep digging but it might be a few days before I can devote too much time to this. Given this is bug related we should still be able to get it merged within the next GB beta period.

There's a catch with global styles borders and theme.json set borders. If the theme json sets per side borders, the global styles also has to apply per side borders even if the user's border is "flat" and can be a simple shorthand `border: ...` rule.

Currently, if the border is a flat border on the instance it's still being pushed as that and so won't clear or override the per side config set by Global Styles. We could clear the Global Styles per side config but then might expose the issue if a theme.json sets per side borders. 

Long story, short, applying block styles globally will require `PushChangesToGlobalStylesControl` to convert a flat border to a split "per-side" border.

**Comment by aaronrobertshaw** [comment]
I've pushed some changes that I believe fix the issues reported on earlier reviews (although I still can't replicate the error).

Given there are so many different ways borders can be configured, I'd really appreciate some further thorough testing 🙏 


https://github.com/WordPress/gutenberg/assets/60436221/3cd04241-66a9-4073-95d7-1ae0e187c2b1

File: packages/edit-site/src/hooks/push-changes-to-global-styles/index.js [hunk 3]
```diff
@@ -152,12 +228,22 @@ function PushChangesToGlobalStylesControl( {
...
 		}
 
+		const newBlockAttributes = {
+			borderColor: undefined,
+			backgroundColor: undefined,
+			textColor: undefined,
+			gradient: undefined,
+			fontSize: undefined,
+			fontFamily: undefined,
+			style: cleanEmptyObject( newBlockStyles ),
```
Comment (aaronrobertshaw) [inline packages/edit-site/src/hooks/push-changes-to-global-styles/index.js]: Only clearing the individual border side properties would still leave empty objects in the block style attribute without this `cleanEmptyObject`.

File: packages/edit-site/src/hooks/push-changes-to-global-styles/index.js [hunk 4]
```diff
@@ -86,37 +88,111 @@ const STYLE_PATH_TO_CSS_VAR_INFIX = {
...
+			if ( flatBorderProperties.includes( key ) && value ) {
+				// The shorthand config path is included to clear the block attribute.
+				const borderChanges = [ { path, value } ];
+				sides.forEach( ( side ) => {
+					const currentPath = [ ...path ];
+					currentPath.splice( -1, 0, side );
+					borderChanges.push( { path: currentPath, value } );
+				} );
+				return borderChanges;
+			}
```
Comment (aaronrobertshaw) [inline packages/edit-site/src/hooks/push-changes-to-global-styles/index.js:223]: There's an issue where if a theme.json configures longhand border properties and the user's global styles only configured shorthand border styles, the theme.json styles would incorrectly take precedence. As a result, Global Styles applies even shorthand borders to the longhand border properties.

This block of code maps shorthand block instance border styles to the longhand paths required by global styles.

File: packages/edit-site/src/hooks/push-changes-to-global-styles/index.js [hunk 5]
```diff
@@ -128,11 +204,11 @@ function PushChangesToGlobalStylesControl( {
 	attributes,
 	setAttributes,
 } ) {
-	const changes = useChangesToPush( name, attributes );
-
 	const { user: userConfig, setUserConfig } =
 		useContext( GlobalStylesContext );
 
+	const changes = useChangesToPush( name, attributes, userConfig );
```
Comment (aaronrobertshaw) [inline packages/edit-site/src/hooks/push-changes-to-global-styles/index.js:296]: We now pass the current user global styles to assist with determining if we need to provide a fallback border style to maintain a visible border.

**Review by youknowriad — COMMENTED** [review]
If I'm not wrong, I think we've discussed a potential alternative to actually add the fallback when generating the styles (I don't remember entirely why we discarded this option). It feels to me, like this PR is kind of a hack because we're not applying the fallback properly. 

I know that there are some nuances there that might make the above not easy to achieve, so not entirely a blocker but if we want to remove these hacks, I think we should probably apply the conceptual fix at some point.

**Comment by aaronrobertshaw** [comment]
> If I'm not wrong, I think we've discussed a potential alternative to actually add the fallback when generating the styles (I don't remember entirely why we discarded this option).

I'm not sure of the alternative you are referring to. Was it setting defaults in controls from global styles? I think a blocker for that was flagged in this [comment](https://github.com/WordPress/gutenberg/pull/49738#issuecomment-1512610437).

For some history and context. The discussion began after the [extraction of the border panel](https://github.com/WordPress/gutenberg/pull/48636). Which required some follow-up fixes in https://github.com/WordPress/gutenberg/pull/49603. That lead to the proposal to [remove the "smart" border style behaviour](https://github.com/WordPress/gutenberg/pull/49714). That PR has more in the way of explanations.

Ultimately, from those discussions, we went with two fixes for the extracted panel that continued to handle the edge cases with borders:
- https://github.com/WordPress/gutenberg/pull/49738
- https://github.com/WordPress/gutenberg/pull/49603

> It feels to me, like this PR is kind of a hack because we're not applying the fallback properly.

I'd be 100% on board with a holistic fix to covering these edge cases. Unfortunately, I don't know what that fix is, whether it is getting global styles defaults in the block editor for all controls, updating the style engine or its use to cover these edge cases etc.

I'm happy to close this PR if you have better ideas. I created it to try and get this feature fixed as it has had bugs since it landed (not clearing preset attributes etc, missing some styles) and is accumulating more as additional styles have been added to the style config arrays in the block editor package and not here.

**Comment by ramonjd** [comment]
Thanks for updating the PR @aaronrobertshaw 

I've retested the changes using Featured Image and Group blocks in the site editor.

Applying a block's styles globally, I can:

- set border color, width and radius values for all blocks
- update border color, width and radius values set in block global styles
- set and update individual side border color, width and radius values. This includes updating any individual sides that have been previously set in global block styles. 
- overwrite any theme.json styles set in `styles.blocks['core/group']`^
- reset them via "reset to defaults"

It's working well for me. Haven't run into any issues so far. 


^
I still see the js console error (could be just me). Here's the theme.json styles I'm using
```json
	"styles": {
		"blocks": {
			"core/group": {
				"border": {
					"color": "#000000",
					"style": "solid",
					"width": "10px"
				}
			}
		}
	},
```

Screenshot 2023-06-20 at 2 22 31 pm

**Comment by youknowriad** [comment]
Just noting that I'm not suggesting that we change anything in this PR. I think if you're all satisfied with it please continue and merge. Mainly trying to understand the problem better to see why it's so complex.

---
Here's my mental model,, just sharing how I think about this problem and what might be an alternative solution.

We have two places where we generate styles based on "user input":

 1- Global Styles (theme.json) root level
 2- Global Styles (theme.json) block level
 3- Block Styles (block supports): individual block level

When do we need the fallback? (this is where I'm not sure about my answer, so correct me here because the logic depends on it)

 - We need to apply the fallback for 2 and 3 from the list above but not on 1 (is that right?)

Or maybe the correct fallback by taking into consideration the edge cases is:

 - Don't apply the fallback for 1.
 - Apply the fallback for 2.
 - Apply the fallback for 3 but only if 2 didn't define a border style?

So we could move the fallback logic to the style generation if we have access to global styles from the block supports it seems, right?

**Comment by aaronrobertshaw** [comment]
Thank you for expanding on things @youknowriad 👍 

> When do we need the fallback?

We need to potentially apply a fallback on all three places users can set styles.

> - Don't apply the fallback for 1.
> - Apply the fallback for 2.
> - Apply the fallback for 3 but only if 2 didn't define a border style?

#### Use Case 1 - Global Styles - root level - set by user

We still need a fallback here if nothing is set in the theme.json.

The UI control handles this as it should get the theme.json value as a default on the control.

#### Use Case 2 - Global Styles - block level - set by user

Almost the same as Use Case 1. We need a fallback if nothing has been set yet, either by theme.json or the user's global root styles

#### Use Case 3 - Block Styles (block supports): individual block level

We need a fallback only if theme.json or global styles haven't set a border style. This is currently handled via a `:where()` CSS rule given the block editor didn't have access to global styles data.

#### Use Case 4 - Pushing Block Styles To Global Styles

So for the use case in this PR, moving from block styles to global styles, the `:where()` CSS rule no longer works so hence the application of logic that we're trying to remove.


> So we could move the fallback logic to the style generation if we have access to global styles from the block supports it seems, right?

Yes, if the style engine could access the global styles data and apply some logic during style generation, the fallback could be applied there. 

The ability to add some logic to the style generation would also be useful to clean up the global styles for borders which currently has to be the longhand version. This is to overcome the scenario where a theme.json defines different borders per side (longhand). In this case, if a user sets a uniform flat border (shorthand), the theme.json's longhand styles take precedence overriding the user's choice.

Effectively, we need to conditionally generate styles via the style engine, or avoid merging longhand values when the user origin sets a shorthand definition. FWIW the current fallback approaches pre-date the style engine.

**Comment by tellthemachines** [comment]
Hey peeps, how likely is it that this can still be included in 6.3? It's a regression from 6.2 so could still be added during RC if we're confident it won't impact anything else.

**Comment by aaronrobertshaw** [comment]
> Hey peeps, how likely is it that this can still be included in 6.3? It's a regression from 6.2 so could still be added during RC if we're confident it won't impact anything else.

@tellthemachines I will take a look at reviving this tomorrow. 

It fixes bugs that have been present since the apply globally feature was introduced rather than a regression. Given it is still a bug fix, it would be good to include it if possible. 

Addressing the [concerns](https://github.com/WordPress/gutenberg/pull/51621#issuecomment-1598392459) around a better solution to the fallback logic can be worked on post-6.3.

**Comment by tellthemachines** [comment]
> It fixes bugs that have been present since the apply globally feature was introduced rather than a regression.

Oh, I mentioned this as a regression because I'm unable to reproduce https://github.com/WordPress/gutenberg/issues/48048 in WP 6.2.2. That's what this PR fixes, right? Or is its scope wider than that?

**Comment by aaronrobertshaw** [comment]
> That's what this PR fixes, right? Or is its scope wider than that?

The scope is wider as there were bugs in the `packages/edit-site/src/hooks/push-changes-to-global-styles/index.js` script since its inception. Those are detailed in the PR description but to summarise the "apply globally" issues:

- Didn't handle required border fallback logic to ensure visible borders
- Didn't clear preset block attributes
- Missed including block supports in the config arrays such as borders or block gap
- Leaves empty objects within the block's style attribute

The regression aspect might have been caused by https://github.com/WordPress/gutenberg/pull/47098 which duplicated config arrays from the block editor package and those were out of date or incomplete.

**Comment by tellthemachines** [comment]
I guess then the question is how confident are we that this is safe to go in during RC phase? 😄 In any case, it's a bug that only happens in very specific circumstances, so it's not the end of the world if it doesn't make it.

**Comment by aaronrobertshaw** [comment]
I've rebased this locally, resolving the current conflict. It is testing ok for me but I can replicate the console error @ramonjd reported. There's a chance that's an existing issue given how global styles has to convert flat borders to split ones to ensure split styles set by theme.json are overridden properly.

In terms of how confident I am, that this is safe for the RC, I'd say reasonably. 

- The changes are limited to the push to global styles control
- Fixes relatively straightforward bugs for block gap spacing, clearing preset block attributes etc.
- The border fallback logic adds additional changes to be pushed to global styles and reset in the block attributes. This is the bit that needs plenty of testing to raise confidence levels. That said, it's already broken.

With some further testing and reviews, we should be able to land this if desired. More so if I can work out how to avoid the reported console error as well.

**Comment by aaronrobertshaw** [comment]
After some further testing, the console error can be replicated in the post editor as well by:

1. setting a custom border color on a group block
2. choosing to reset the border via the panel's menu

I don't recall this being an issue before and am now wondering if it's a regression introduced with the extraction of the border panel and subsequent fixes made to that. I'll try and dig into that more tomorrow. 

In the meantime, I've pushed the latest for this PR in case we wish to proceed with it and address the console error as a separate issue.

**Comment by aaronrobertshaw** [comment]
Overnight a range of updates to the push-to-global-styles file were merged for pushing behaviours as well. These changes won't go into 6.3 and make landing this PR's fixes a bit messy. As a result, I'm less confident we should try to force this into 6.3.

The bugs addressed by this PR are fairly minor but the changeset is somewhat disproportionally large. Giving it some further time to cook would definitely limit the potential introduction of unintended side effects. It might be a better candidate for WP 6.3.1.

@annezazu, while it isn't ideal to not address https://github.com/WordPress/gutenberg/issues/48048 in time for 6.3, do you have any issues with the proposed plan to leave this PR out?

**Comment by annezazu** [comment]
I trust your read of it. Let's have it planned for 6.3.1 in that case.

**Comment by aaronrobertshaw** [comment]
A fix is up for the console error when clearing custom border colors: https://github.com/WordPress/gutenberg/pull/52963.

**Comment by aaronrobertshaw** [comment]
This PR should be ready for a final review now 🙏 

The console error for clearing custom border colors has been fixed and this PR now fixes the detection of block gap changes etc.

A more holistic approach to border-style fallbacks is outside the scope of this PR and will be considered a follow-up.

**Comment by t-hamano** [comment]
Thanks for your continuous work on this issue, @aaronrobertshaw!

The series of processes starting with `PushChanges()` is very complicated for me, but I tried various tests on global pushing of styles again. There are probably some things that this PR shouldn't cover, but I'll list all the things that caught my eye during testing.

--- 

In the global style, apply the border style in one direction only. Then apply the border style on the block other than that direction and push it globally. Then the border styles are _merged_. Is this the intended behavior? For padding, margin and border radius it seems to `overwrite` global styles when pushed globally. In this screencast, I'm applying the style for the top border in the global style, and then pushing the global from the block that applied the bottom border.

<details><summary>Screencast</summary>

https://github.com/WordPress/gutenberg/assets/54422211/d8ac6327-2342-4182-8beb-e37ca0a79a26

</details> 

---

Border control does not allow only border style to be applied in one direction when unlinked. To select a border style, you must set either border width or border color.

<details><summary>Screencast</summary>

https://github.com/WordPress/gutenberg/assets/54422211/108936a7-c54b-4075-9ac0-0758bc42598f

</details> 

---

Of the link colors, the default color is successfully pushed globally, but the hover state color is not.

<details><summary>Screencast</summary>

https://github.com/WordPress/gutenberg/assets/54422211/5ff969e1-3880-4aa8-a27e-811d98af5e6d

</details> 

---


#52370 adds Behaviors to the global styles and also updates the files this PR is changing. I noticed that when I push the behaviors setting globally, it doesn't clear the block level setting.

<details><summary>Screencast</summary>

https://github.com/WordPress/gutenberg/assets/54422211/faadedd3-a006-4498-b103-95dded4f915e

</details> 

---

The padding disappears when the background is pushed globally. This may be due to the has-background class disappearing at the block level.

<details><summary>Screencast</summary>

https://github.com/WordPress/gutenberg/assets/54422211/ede33a7d-8137-4261-b1f7-b5ab278ea9ab

</details>

**Comment by aaronrobertshaw** [comment]
Thank you @t-hamano for the thorough testing, great stuff! 🥇 

I'll work through making any required updates to this PR over the next few days.

> Then the border styles are merged. Is this the intended behavior?

I'm not certain on what the best approach here is. I'd probably lean towards the current behaviour as the user is seeing the combined results of theme.json, global styles, and individual block styles. The push-to-global-styles, is pushing the current appearance/styling for the block so it applies to all.

If the user wants to override the top border, as per your example, they'd only have to apply a `0` border width to the top border on the block instance, then push.

I'll investigate the spacing controls and border radius behaviour as I address the other issues raised in your review.

>  Border control does not allow only border style to be applied in one direction when unlinked.

This has been a behaviour on those controls since their inception and not really related to the pushing of global styles. So, I think that would be better suited to a follow-up where the history and context on those controls can be dug up,

> Of the link colors, the default color is successfully pushed globally, but the hover state color is not.

Good catch. This looks like another one that was missed with the duplicated config arrays not being kept in sync. A possible follow-up to this might be trying to consolidate those via our private APIs lock/unlock mechanism.

> I noticed that when I push the behaviors setting globally, it doesn't clear the block level setting.

Thanks. When I first created this PR the behaviors weren't merged as you noted. After rebasing this, I wasn't expecting to also have to fix any new additions, so missed that 🤦 

I'll update this PR accordingly. The sooner we can get this in the better I think so there is a complete example that can be followed for future additions so this doesn't keep reoccurring.

> The padding disappears when the background is pushed globally. This may be due to the has-background class disappearing at the block level.

I'm not sure there's an easy fix for this. That CSS class is added by the color block supports. We also don't currently have a way to conditionally generate global styles for some properties, or add extra CSS classes based on theme.json/global styles values.

It's part of the reason, global border styles have to include longhand definitions, even though a shorthand definition has been applied, to ensure they correctly override any longhand definition in theme.json.

For now, I'm inclined to say that is out of the scope for this PR. The user can add padding styles to what they are pushing to global styles to restore or maintain padding. If we left the color support values in place, that block would have padding but not the rest of that block type. Erring towards consistency seems like the best bet here to me.

I'll update again once I've addressed all the actionable items.

Thanks again for the great feedback and review 🙇

File: packages/edit-site/src/hooks/push-changes-to-global-styles/index.js [hunk 6]
```diff
@@ -243,8 +364,10 @@ function PushChangesToGlobalStylesControl( {
 				}
 			);
 		}
+
 		if ( userHasEditedBehaviors ) {
 			__unstableMarkNextChangeAsNotPersistent();
+			setAttributes( { behaviors: undefined } );
```
Comment (aaronrobertshaw) [inline packages/edit-site/src/hooks/push-changes-to-global-styles/index.js:370]: A good potential follow-up here might be to consolidate the updating of attributes and snackbar notices for both styles and behaviours. To keep the scope of this PR manageable for testing I've opted against this larger refactor.

**Review by aaronrobertshaw — COMMENTED** [review]
I've fixed the pushing of link hover colors and the clearing of their style attribute. This was a little clunky due to the single supports key covering two separate attributes.

The behaviors only needed to have the block attribute cleared but it highlights that the behaviours and styles should probably be being processed together in a single set of changes. If you set behaviors as well as styles, then push them all globally, you'll receive two snackbar notices each with a different "undo" action. 

This is better suited to a follow-up once we have this suite of fixes in place.

**Review by t-hamano — APPROVED** [review]
Just to be sure, I rebased this PR locally with the latest trunk and tested it. I believe everything is working as expected 🚀

https://github.com/WordPress/gutenberg/assets/54422211/d177e48f-9820-4c26-ba6c-c6701d487166

**Review by glendaviesnz — APPROVED** [review]
Tested well for me:

✅ All typograpy, padding, margin, block spacing, border settings were removed from block settings, but still applied in editor canvas when pushed to global
✅ The settings pushed to global were applied to new blocks
✅ With global settings set first, styles applied after at block level took priority
✅ A range of single border, custom per side settings, different styles, custom colors all pushed successfully to global

**Comment by aaronrobertshaw** [comment]
Thank you for the reviews and testing everyone, I appreciate this one got a bit gnarly 🙇 

I've updated the PR description and title to also cover the link hover color and behavior fixes.

**Comment by tellthemachines** [comment]
This PR can't be cherry-picked cleanly onto the wp/6.3 branch because the file on trunk has diverged too much from the version on that branch (mostly I think because 
the behaviours changes don't exist yet). If this fix is required for 6.3.x it's going to need a new PR done against that branch, taking into account that the code in this file is at a much earlier stage there 😅

**Comment by aaronrobertshaw** [comment]
The fixes for the behaviour changes in this PR are very minor. Hopefully, that will mean spinning up a new PR against wp/6.3 won't take too long. I can do that tomorrow morning.

**Comment by tellthemachines** [comment]
Thanks Aaron! The conflicts weren't straightforward to solve at all, but you have more context on the feature than I do 😄

**Comment by aaronrobertshaw** [comment]
> The conflicts weren't straightforward to solve at all, but you have more context on the feature than I do

Another source for the conflicts might be the removal of the lodash function use. 

I've knocked up a quick draft in https://github.com/WordPress/gutenberg/pull/53624 but am out of time, so I'll give it a proper test and once over tomorrow as promised.
