### PR TITLE
Navigation block: Only focus submenu trigger on escape key press

### LINKED ISSUE #41975: Navigation submenus: avoid to focus the submenu trigger button when submenu loses focus
### Description

https://github.com/WordPress/gutenberg/pull/41774 introduced a couple changes for the navigation submenu keyboard interaction. 

1 Close the submenu when pressing the Escape key: makes perfectly sense and works as expected.
2 Always move focus to the submanu trigger button when the submenu loses focus, such as tabbing out of it.

The second change triggers a few unexpected behaviors that are pretty confusing for both mouse and keyboard users.

### Step-by-step reproduction instructions

1
**Focus moves to the trigger when focusing any other interactive element on the page.**
- Test a page with other interactive elements, for example the Hello World post with comments enabled will show the comment form at the end of the page.
- Use the keyboard to move to the navigation menu and open a submenu.
- Leave the submenu open.
- Scroll the page and click within the comment textarea.
- This step can be performed also by screen reader users, directly jumping from the menu item to the comment textarea via dedicated keyboard shortcuts.
- Once the comment textarea receives focus, the new behavior will move focus back to the open submenu trigger:
   - Visually: the page will scroll up unexpectedly.
   - The comment textarea is not focused any longer.
   - Keyboard users and screen reader users will be catapulted back to the submenu, which is likely placed several tab stops before the comment textarea.

This "jumping back' may happen with any other focusable element on the page. The first animated GIF attached below tries to better illustrate the problem. Note: I used a red outline for the focus style, to make things clearer.

2
**Focus is moved to the next trigger when tabbing backwards to the previous menu item.**
The 'focus trigger' behavior is pretty confusing when tabbing backwards:
- Use the keyboard to move to the navigation menu and open a submenu.
- Press Tab to focus one of the the submenu items.
- Press Shift + Tab to move focus back to the submenu trigger.
- Press Shift + Tab again to move focus back to the menu item the trigger belongs to.
- Press Shift + Tab again.
- At this point, focus will jump forward to the next menu item trigger, which is  unexpected and pretty confusing for users.
- Note that this happens also with nested submenus.

Overall, I'm not sure there's a reliable way to move focus to the trigger when the submenu loses focus. I'd suggest to keep only the 'focus on Escape' behavior.

### Screenshots, screen recording, code snippet

Animated GIF to illustrate what happens when focusing any other interactive element on the page:

jump-to-form-

Animated GIF to illustrate what happens when tabbing backwards:

tab-backwards

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by alexstine**
## What?

Fixes #41975

## Why?

My last change introduced too much bad UX behavior.

## How?

Only target escape key press to place focus on the submenu trigger.

## Testing Instructions

1. Insert a navigation block and create a menu.
2. Create a submenu.
3. View the front-end.
4. Open the submenu.
5. Press escape key.
6. Notice how focus is placed on the submenu trigger.
7. Open the submenu again.
8. Use the tab key to tab out of the submenu.
9. Notice how the submenu closes but focus does not reset to the submenu trigger.

### CODE REVIEW

**Review by draganescu — COMMENTED** [review]
Code looks good 👏🏻  Let's have a second round of testing from @afercia 🙏🏻

**Comment by afercia** [comment]
@draganescu hello. Quick question, when you have a chance: is the submenu navigation `view.js` actually used anywhere or maybe it's. kept only for backwards compatibility?

**Comment by draganescu** [comment]
@afercia `view.js` is enqueued on the front end to provide fly out behavior to menus rendered by the navigation block.

File: packages/block-library/src/navigation/view.js [hunk 1]
```diff
@@ -63,11 +61,13 @@ window.addEventListener( 'load', () => {
 			'.wp-block-navigation-item.has-child'
 		);
```
Comment (afercia) [inline packages/block-library/src/navigation/view.js:62]: I see some room for performance improvements here, as this run for any keyup event on the page for example for any Tab key press or even when typing within an input field or textarea. It's part of the existing implementation though so I'll open a separate issue.

File: packages/block-library/src/navigation/view.js [hunk 2]
```diff
@@ -63,11 +61,13 @@ window.addEventListener( 'load', () => {
...
-				! block.contains( event.target ) ||
-				( block.contains( event.target ) && event.key === 'Escape' )
-			) {
+			if ( ! block.contains( event.target ) ) {
+				closeSubmenus( block );
+			} else if ( event.key === 'Escape' ) {
+				const toggle = block.querySelector( '[aria-expanded="true"]' );
 				closeSubmenus( block );
+				// Focus the submenu trigger so focus does not get trapped in the closed submenu.
+				toggle.focus();
```
Comment (afercia) [inline packages/block-library/src/navigation/view.js]: When testing with a menu with nested submenu, this triggers an error:

`Uncaught TypeError: Cannot read properties of null (reading 'focus')`

That's because:
- the script loops through all the submenu blocks
- for each submenu block, it gets the toggle with an aria-expanded="true" attribute
- then it closes all the submenu and switches aria-expanded to false
- at this point, it loops to the second submenu block, where the toggle has now an aria-expanded set to false
- querySelector returns null and `toggle` is null
- attempting to set focus on `null` triggers the error

I think it would be sufficient to check for the toggle existence before attempting to set focus on it or alternatively return it it's null before setting focus.

Of course, this should be fixed also in the other file for the submenu.

**Comment by afercia** [comment]
> @draganescu hello. Quick question, when you have a chance: is the submenu navigation `view.js` actually used anywhere or maybe it's. kept only for backwards compatibility?

@draganescu thanks. I do see `wp-block-navigation-view-js` enqueued on the page. I do see it's enqueued in `packages/block-library/src/navigation/index.php`. I meant the view.js of the submenu: `packages/block-library/src/navigation-submenu/view.js`. I don't see that file enqueued anywhere and it's not in the page.

File: packages/block-library/src/navigation/view.js (hunk 2 above)
Comment (alexstine) [reply packages/block-library/src/navigation/view.js]: @afercia Better now?

Comment (afercia) [reply packages/block-library/src/navigation/view.js]: Looks good to me!

**Comment by afercia** [comment]
LGTM 👍 Restarted one e2e job that faield, waiting to see if it passes.

**Review by afercia — APPROVED** [review]
