### PR TITLE
Fix self closing navigation overlay

### LINKED ISSUE #60048: Navigation Block: overlay menu closes automatically when hovering menu items linked to drafts that follow a submenu item
### Description

Edge case: When a site has a draft page linked to a menu item and that menu item is positioned after a submenu in a Navigation Block, the overlay will automatically close without user input.

### Step-by-step reproduction instructions

1. Add a Navigation Block with the following structure:

* Menu Item
* Menu Item
** Submenu item
** Submenu item
* Menu item with a post/page saved as a draft

2. Set the Navigation to display as an overlay
3. Check the frontend and over the menu item associated with the draft

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/14153300/77f3dd7f-3b5e-4b87-af5f-5bbe7bd1c8f8

Example menu structure:

CleanShot 2024-03-20 at 16 01 27@2x

### Environment info

- WordPress 6.5 RC3, GB 17.9
- Chrome 122, MacOS 14.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by draganescu**
## What?

Fixes #60048

## Why?

It's a bug

## How?

Copy the closing conditions from the opening conditions on the `closeMenuOnHover` action in navigation block's view script.

## Testing Instructions

1. Add a Navigation Block with the following structure:
Menu Item
SubMenu
** Submenu item
** Submenu item
Menu item with a post/page saved as a draft
2. Set the Navigation to display as an overlay
3. Check the frontend and hover over the submenu

### Testing Instructions for Keyboard

N/A

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/107534/a50b4dff-2db6-4a9a-889c-ed50ab4bd743

### CODE REVIEW

**Comment by annezazu** [comment]
Tested this using https://playground.wordpress.net/gutenberg.html and it works! I can no longer replicate the problem.

**Comment by fabiankaegy** [comment]
I can also no longer replicate the issue with this. Thank you for working on this

**Comment by huzaifaalmesbah** [comment]
Looks good for me. I can't replicate this issue with this PR.

**Comment by kjnanda** [comment]
I am unable to reproduce the issue after the fix is added. [Here](https://github.com/WordPress/gutenberg/issues/60048#issuecomment-2017455724) is link to check the complete report!

File: packages/block-library/src/navigation/view.js [hunk 1]
```diff
@@ -66,7 +66,14 @@ const { state, actions } = store(
 					actions.openMenu( 'hover' );
 			},
 			closeMenuOnHover() {
-				actions.closeMenu( 'hover' );
+				const { type, overlayOpenedBy } = getContext();
+				if (
+					type === 'submenu' &&
+					// Only open on hover if the overlay is closed.
```
Comment (scruffian) [inline packages/block-library/src/navigation/view.js:72]:
```suggestion
					// Only close on hover if the overlay is open.
```

Comment (scruffian) [inline packages/block-library/src/navigation/view.js:72]:
```suggestion
					// Only close on hover if the overlay is closed.
```

**Review by scruffian — APPROVED** [review]
LGTM. I think the logic to determine whether the overlay is open should actually live inside the `openMenuOnHover` and `closeMenuOnHover` functions, so that if they are called from other places we don't need to do the same checks, but this could be a different PR.

**Review by SantosGuillamot — APPROVED** [review]
It looks good to me as well. I believe the whole navigation block JS logic should probably be revisited at some point, but this seems to work fine for now.

**Comment by getdave** [comment]
Code quality follow up in https://github.com/WordPress/gutenberg/pull/60162

**Comment by getdave** [comment]
This PR was triaged by Editor release leads and contributors in WP Slack as part of the final WordPress 6.5 process.

See https://wordpress.slack.com/archives/C02QB2JS7/p1711368222436929?thread_ts=1711367867.806179&cid=C02QB2JS7 (requires registration).

The criteria used was:

- Was this bug identified during the RC cycle for WP 6.5?
- Is this bug directly related to one of the blessed features in this release?
- Would this bug cause existing website’s to break/fail upon upgrade to WP 6.5?
- What is the approximate scope of the impact? Scale: (Minimal) 1 - 5 (Severe).
- Is the fix introducing any new features or changes?

**Conclusion**: we propose that this fix _is_ included in WP 6.5 but would be flexible if it were to be bumped to 6.5.1.

**Reason**: It’s not directly affecting on the of the blessed features. It won’t really cause an existing website to break because it relies on unpublished Post/Pages to trigger the issue. Scope for me is 1-2. However, the scope of the change itself in the PR is relatively small and limited.

We now await a final decision from the full release team.

**Comment by bph** [comment]
I just cherry-picked this PR to the release/18.0 branch to get it included in the next release: 07871b8962

File: packages/block-library/src/navigation/view.js (hunk 1 above)
Comment (getdave) [reply packages/block-library/src/navigation/view.js:72]: Addressed in https://github.com/WordPress/gutenberg/pull/60162

**Comment by getdave** [comment]
I just cherry picked this into WP 6.5 RC 4 branch https://github.com/WordPress/gutenberg/pull/60241/commits/4306077940290d450af95fa03a7333258a22cab8
