### PR TITLE
Block Editor: Partition attributes updates to avoid conflating meta and blocks attributes

### LINKED ISSUE #15739: Cursor jumps to end in TextControl with attribute source 'meta' after each keystroke
**Describe the bug**
In WP 5.2, if a TextControl component is connected to an attribute with source 'meta', whenever I try to type something in the middle of the already typed text, the cursor jumps to the end after each keystroke. 
If I comment out the source and meta attributes (such that the data is stored in the html block comment), this behaviour changes: now typing in the middle of already present text works fine.
Storage of the metadata is working fine in both cases.

**To reproduce**
1. copy and paste the code from the WP example https://developer.wordpress.org/block-editor/tutorials/metabox/meta-block-1-intro/ into your themes code.
2. create one of these meta blocks (called "Meta Block") in the Gutenberg editor.
3. type something into the TextControl. 
4. Move your cursor somewhere in the middle and continue typing
observed behaviour: after the first keystroke the cursor jumps to the end of the content.

**Expected behavior**
the cursor stays behind the most recently typed character

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Firefox 
 - Version: 60.6.3esr (32-bit)

 - OS: OS X
 - Browser: Safari 
 - Version: 12.1.1

**Additional context**
I am using the built in latest version of Gutenberg as of the time of this post.
I have noticed that the edit() function of the block is called twice for each keystroke in the buggy case (source: 'meta'). If a different source is selected this does not seem to happen.

Thanks everybody in advance!

### PR DESCRIPTION
**Pull request by aduth**
Fixes #15739 

This pull request seeks to resolve an issue where setting a new meta attribute value in a block can wrongfully displace the text caret selection.

**Implementation Notes:**

I consider this to be an incomplete but likely sufficient resolution to #15739. The issue occurs because a render of the block's `edit` occurs synchronously as a result of `updateBlockAttributes`. At this point in time the meta attributes have not yet updated, so the old value is used (more at https://github.com/WordPress/gutenberg/issues/15739#issuecomment-494822233). Arguably, it is not correct (or at least ineffective) to be calling `updateBlockAttributes` with new meta values, since the selector to generate a block's attributes will always ignore these ([source](https://github.com/WordPress/gutenberg/blob/27a6ead99b6ec38106c2b8696c74fe2a6e3d24d2/packages/block-editor/src/store/selectors.js#L154)). To that point, the changes here will avoid calling `updateBlockAttributes` with meta value updates, and avoid calling it altogether if the only attributes updates are meta value updates. The solution works because `updateBlockAttributes` is avoided, and thus the problematic intermediate render does not occur.

It is technically incomplete in that if a block were to call `setAttributes` with a mix of block attributes and meta attributes, a similar issue may occur. It is quite unlikely that a block would be implemented this way.

In any case, I'd like to see some improvements to this sort of "external" sourcing, which would be a larger task than I propose to resolve here. I will aim to submit a formal proposal for how it might work, informed on #15739 and previous issues #4989 and #2759. An inline code comment has been added to reflect this future work.

**Testing Instructions:**

An existing end-to-end test case has been adapted to reveal the failure from `master` resolved here. Verify that it passes:

```
npm run test-e2e packages/e2e-tests/specs/plugins/meta-attribute-block.test.js
```

Repeat Steps to Reproduce from #15739

### CODE REVIEW

File: packages/block-editor/src/components/block-list/block.js [hunk 1]
```diff
@@ -644,18 +644,34 @@ const applyWithDispatch = withDispatch( ( dispatch, ownProps, { select } ) => {
...
-				( result, value, key ) => {
-					if ( get( type, [ 'attributes', key, 'source' ] ) === 'meta' ) {
-						result[ type.attributes[ key ].meta ] = value;
-					}
-
-					return result;
-				},
-				{}
-			);
+
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-list/block.js]: The behavior of all this setAttributes function seems like something that should be absorbed in the `updateBlockAttributes` action instead.

As you said, we should ship the bug fix and consider these consolidations separately.

**Review by youknowriad — APPROVED** [review]

File: packages/block-editor/src/components/block-list/block.js (hunk 1 above)
Comment (aduth) [reply packages/block-editor/src/components/block-list/block.js]: > The behavior of all this setAttributes function seems like something that should be absorbed in the `updateBlockAttributes` action instead.
> 
> As you said, we should ship the bug fix and consider these consolidations separately.

Yes, I think so too. One point of clarification / affirmation is that: I don't think the changes here dig us any further into a hole, and in-fact serve more as an implementation which ought to have existed in the first place.
