### PR TITLE
Alternative: Fix template part area listing when a template has no edits

### LINKED ISSUE #55061: Site Editor Template Details: Areas not available after saving
Areas are no longer captured in the template if the template has been edited. To replicate, install a block theme like TT3 or TT4, then view the Blog Home template, make a change to it, save and refresh. 

May be related to https://github.com/WordPress/gutenberg/pull/54861 (or the alternative https://github.com/WordPress/gutenberg/pull/54942). 

https://github.com/WordPress/gutenberg/assets/1813435/c809ea0d-afb9-46f5-89a9-7aee08ee4bd4

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Fixes #55061.
Alternative to #55085.

PR fixes the getCurrentTemplateTemplateParts selector returning an empty value when a template has no edits.

This is probably a side-effect of #52417.

Update: If anyone is wondering why areas are displayed when a template has no edits at all (loaded from the file). This is due to blocks like Query and core/pattern performing updates on the initial load. This loads blocks in the store.

## Why?
A record returned by `getEditedEntityRecord` will have an undefined `block` property when an entity has no edits. In the past, blocks were loaded into the store for a current recond via `useEntityBlockEditor`. This isn't the case anymore.

## How?
Use blocks from the block editor store. We can get all template part block `clientIds` with `__experimentalGetGlobalBlocksByName` and then grab block objects using `getBlocksByClientId`.

## Testing Instructions
1. Open a Site Editor.
2. Open the home template.
3. Make some edits, save and reload.
4. Confirm template areas are still listed in both template detail sidebars.
5. Confirm that clicking on the areas performs the intended action. Left sidebar - opens the template part. The right sidebar - selects the template part in the canvas.

## Screenshots or screencast 
CleanShot 2023-10-05 at 16 28 59

### CODE REVIEW

**Comment by Mamaduka** [comment]
One side-effect of this alternative fix is that now it correctly renders nested Template Parts.

## Screenshot
CleanShot 2023-10-06 at 10 16 09

File: packages/edit-site/src/store/selectors.js [hunk 1]
```diff
@@ -292,22 +292,21 @@ export function isSaveViewOpened( state ) {
...
-
+	( select ) => () => {
 		const templateParts = select( coreDataStore ).getEntityRecords(
 			'postType',
 			TEMPLATE_PART_POST_TYPE,
 			{ per_page: -1 }
 		);
 
-		return getFilteredTemplatePartBlocks( template.blocks, templateParts );
+		const clientIs =
```
Comment (andrewserong) [inline packages/edit-site/src/store/selectors.js]: Just a typo in this const 🙂

```suggestion
		const clientIds =
```

File: packages/edit-site/src/store/selectors.js [hunk 2]
```diff
@@ -292,22 +292,21 @@ export function isSaveViewOpened( state ) {
...
+			select( blockEditorStore ).__experimentalGetGlobalBlocksByName(
+				'core/template-part'
+			);
+		const blocks =
+			select( blockEditorStore ).getBlocksByClientId( clientIs );
```
Comment (andrewserong) [inline packages/edit-site/src/store/selectors.js]:
```suggestion
			select( blockEditorStore ).getBlocksByClientId( clientIds );
```

**Review by andrewserong — APPROVED** [review]
This is testing nicely for me, thanks for the follow-up @Mamaduka!

Are there any performance concerns with grabbing `blocks` fresh each time this selector is called via `getBlocksByClientId()`? I didn't notice any perceivable slowdown from this PR, but I did notice the selector is being called quite frequently (i.e. > 400 times in a fresh load of the site editor running TT3). Also, it seems that `getBlocksByClientId` is itself a memoized selector via `createSelector`, so hopefully that means there shouldn't be much a performance hit. If there is, I suppose one option could be to refactor this behaviour to a hook, instead of a selector, and then it could be clearer when to memoize?

On `trunk`, the memoized version of `getFilteredTemplatePartBlocks` gets called `4` times for me, and with this PR it gets called `10` times, so it seems that the memoization for that function is still providing some benefit at least 👍

Also, I have now written `memoize` too many times, so that word is starting to lose meaning for me 😄

In any case, this change looks like a good and simple way to resolve the underlying issue, and I didn't notice any performance issues in my testing of it. This looks good to try to me! ✨

**Comment by andrewserong** [comment]
I've just added the backport label since it sounds like this is needed for TT4 / WP 6.4 — feel free to remove the label if that's not the case!

**Comment by Mamaduka** [comment]
Thanks, @andrewserong!

Using the `parse` method would have been more expensive, depending on the side of the template.

It's hard to guess the performance implication for changes like this. We know where to start if we see a degraded performance, but I doubt this has any real impact.

**Comment by andrewserong** [comment]
> It's hard to guess the performance implication for changes like this. We know where to start if we see a degraded performance, but I doubt this has any real impact.

Same. Thanks for thinking this through! LGTM :shipit:

**Comment by Mamaduka** [comment]
I'm going to merge this. The Playwright failure isn't related and I'm tracking in separately.

**Comment by mikachan** [comment]
I just cherry-picked this PR to the 6.4-beta3 branch to get it included in the next release: https://github.com/WordPress/gutenberg/pull/55039/commits/95e1f627841f59117b8ef15496adbac1bc10b92b
