### PR TITLE
Fix: Hide resolved comments in unpinned mode

### LINKED ISSUE #71394: Only unresolved comments should be shown in unpinned mode
## What problem does this address?
When a comment is resolved, it should disappear from the default view to declutter the editor display.

## What is your proposed solution?

- Don't show resolved comments in the unpinned mode

### PR DESCRIPTION
**Pull request by R1shabh-Gupta**
## What?
Closes #71394 

This PR filters out resolved comments from the unpinned collaboration sidebar to declutter the editor display while keeping them visible in the pinned sidebar for complete comment history.

## Why?
When comments are resolved, they should disappear from the default unpinned view to reduce visual clutter and help editors focus on active, unresolved comments that need attention. Previously, both resolved and unresolved comments were shown in all sidebar modes.

## How?
- Added filtering logic to exclude comments with `status === 'approved'` from the unpinned sidebar
- Preserved all comments (resolved + unresolved) in the pinned sidebar for full history access
- Refactored variable names for clarity (`sortedThreads` → `unresolvedSortedThreads`)

## Testing Instructions
1. Open the Gutenberg editor with a post or page
2. Add some blocks and create comments on them
3. Resolve one or more comments by clicking the "Resolve" button (checkmark icon)
4. Open the unpinned collaboration sidebar
5. Verify that resolved comments do not appear in the unpinned sidebar
6. Open the pinned collaboration sidebar
7. Verify that all comments (resolved + unresolved) appear in the sidebar

### Before
https://github.com/user-attachments/assets/542560dd-850f-4447-8ac9-18490114ed25

### After
https://github.com/user-attachments/assets/2d1720db-6c35-45fc-8c14-4013929f8c6f

### CODE REVIEW

File: packages/editor/src/components/collab-sidebar/index.js [hunk 1]
```diff
@@ -305,11 +305,16 @@ export default function CollabSidebar() {
 			updatedResult.map( ( thread ) => [ thread.id, thread ] )
 		);
 
-		const sortedComments = blockCommentIds
+		// Get comments by block order, filter out undefined threads, and exclude resolved comments.
+		const unresolvedSortedComments = blockCommentIds
 			.map( ( id ) => threadIdMap.get( id ) )
-			.filter( ( thread ) => thread !== undefined );
+			.filter( ( thread ) => thread !== undefined )
+			.filter( ( thread ) => thread.status !== 'approved' );
```
Comment (adamsilverstein) [inline packages/editor/src/components/collab-sidebar/index.js]:
```suggestion
			.filter( ( thread ) => thread !== undefined && thread.status !== 'approved' );
```
combine the two related conditionals to avoid iterating over the comments twice.

**Comment by adamsilverstein** [comment]
@R1shabh-Gupta - this worked well in my testing, thanks for the PR!

I left some small feedback on the filter approach.

**Comment by R1shabh-Gupta** [comment]
Hey @adamsilverstein,
Thank you for the feedback! I’ve updated the code to address the issue.

**Review by adamsilverstein — APPROVED** [review]
Nice work.

**Comment by adamsilverstein** [comment]
@t-hamano does this one look ok to you?

**Review by Mamaduka — APPROVED** [review]
Let's give this a try.
