### PR TITLE
Convert the toolbar in Widgets screen to ARIA toolbar

### LINKED ISSUE #24938: Widgets page: the controls in the toolbar should be in an ARIA toolbar
**Describe the bug**

I'm not sure why the first UI controls in the Widgets page top toolbar are within a role=menu with orientation=vertical:

Screenshot 2020-08-31 at 16 08 09

The orientation isn't vertical but, more importantly, this is not a menu.

For semantics and consistency with the top toolbar in the block editor, these buttons should be in an ARIA toolbar. No more, no less than what is currently implemented in the block editor page.

### PR DESCRIPTION
**Pull request by kevin940726**
## Description

Fix #24938.

Convert the toolbar in Widgets screen from menu to toolbar, and make them accessible.

## How has this been tested?

1. Go to Widgets screen (Enable via experiments in Gutenberg)
2. Play with the toolbar on the top left corner
3. It should be accessible, and functionally the same as before.

## Screenshots 
image

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/edit-widgets/src/components/header/index.js [hunk 1]
```diff
@@ -33,17 +34,27 @@ function Header( { isCustomizer } ) {
...
+					aria-label={ __( 'Document tools' ) }
+				>
+					<ToolbarItem>
+						{ ( toolbarItemProps ) => (
+							<Inserter
+								position="bottom right"
+								showInserterHelpPanel
+								toggleProps={ {
+									...inserterToggleProps,
+									...toolbarItemProps,
```
Comment (kevin940726) [inline packages/edit-widgets/src/components/header/index.js:48]: This also includes `ref`, which will pass to the toggle button in `<Inserter>`

File: packages/edit-widgets/src/components/header/style.scss [hunk 2]
```diff
@@ -6,6 +6,36 @@
...
+				0 0 0 $border-width-focus var(--wp-admin-theme-color),
+				inset 0 0 0 $border-width $white;
+			outline: 1px solid transparent;
+		}
+
+		&::before {
+			display: none;
+		}
+	}
+}
```
Comment (kevin940726) [inline packages/edit-widgets/src/components/header/style.scss:37]: These are mostly copied from `edit-post/header-toolbar`

File: packages/edit-widgets/src/components/header/style.scss [hunk 3]
```diff
@@ -6,6 +6,36 @@
 	padding: 0 $grid-unit-20;
 }
 
+.edit-widgets-header-toolbar {
+	display: inline-flex;
+	align-items: center;
```
Comment (tellthemachines) [inline packages/edit-widgets/src/components/header/style.scss:11]: We don't need the `display: inline-flex` here because it's already set by the `components-accessible-toolbar` class. 

Any reason for adding `align-items: center`? We shouldn't need it either, because the buttons are all the same height so will align by default.

File: packages/edit-widgets/src/components/header/style.scss [hunk 4]
```diff
@@ -6,6 +6,36 @@
...
+
+	// The Toolbar component adds different styles to buttons, so we reset them
+	// here to the original button styles
+	> .components-button.has-icon,
+	> .components-dropdown > .components-button.has-icon {
+		height: $button-size;
+		min-width: $button-size;
+		padding: 6px;
+
+		&.is-pressed {
```
Comment (tellthemachines) [inline packages/edit-widgets/src/components/header/style.scss:22]: When would this state be applied? Not sure how to test it 😅

**Review by tellthemachines — COMMENTED** [review]
Mostly looks good, just a couple comments below!

I noticed while testing that the Undo/Redo buttons aren't working correctly, but it's not related to this changeset as they're broken on the main branch too 🤔

File: packages/edit-widgets/src/components/header/style.scss (hunk 3 above)
Comment (kevin940726) [reply packages/edit-widgets/src/components/header/style.scss:11]: Yeah I mainly just copied paste from the code in `edit-post` 😅 , I'll re-examinate them! Thx!

**Review by tellthemachines — APPROVED** [review]
Looks good!
