### PR TITLE
Details Block: Fix keyboard accessibility issues and allow list view selection to show up inner blocks

### LINKED ISSUE #70047: Details Block: Inner blocks cannot be focused using only the keyboard
### Description

Reported at https://github.com/WordPress/gutenberg/issues/65603#issuecomment-2844575410

Previously, the Details block automatically opened and closed the contents inside the block when the block was selected. However, this behavior was removed by #67766 after users reported issues with dragging and dropping blocks.

However, this introduced another accessibility issue. Keyboard users cannot access the inner blocks because the contents inside the block can only be opened and closed by clicking the summary element with the mouse pointer.

### Step-by-step reproduction instructions

1. Add a new post.
2. Insert details block.
3. Notice how focus should land in the summary title field.
4. Try to move to the hidden paragraph.
5. Impossible because the block is collapsed.
6. Try to expand the block with the keyboard.
7. Impossible because there is no exposed expander/trigger due to the overriding of semantics for screen readers.
8. Open the list view.
9. Expand the details block in the tree.
10. Try to select the paragraph block.
11. Block is announced as selected but focus doesn't move since it is not exposed in the canvas.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by yogeshbhutkar**
## What, Why, and How?
Closes #70047

This PR enhances keyboard interaction with the Details block, enabling users to expand inner blocks using the keyboard. It also fixes a bug that previously prevented selecting an inner block from the List View; clicking an inner block in the List View now correctly selects it in the editor canvas.

With this PR, pressing the down arrow key expands the inner blocks within the Details block, while pressing the up arrow key collapses them.

## Testing Instructions

1. Create a post and add the following block markup.

<details>

<summary>Code</summary>

```html
<!-- wp:paragraph -->
<p>First Paragraph Block</p>
<!-- /wp:paragraph -->

<!-- wp:details -->
<details class="wp-block-details">
<summary>Details Block Summary</summary>
<!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>Details Block Content</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Details Block Content</p>
<!-- /wp:paragraph -->
</details>
<!-- /wp:details -->

<!-- wp:paragraph -->
<p>Second Paragraph Block</p>
<!-- /wp:paragraph -->
```

</details>

2. Try moving through the blocks with the arrow keys.
3. Confirm, the inner blocks within details are accessible using the keyboard.
4. Open the list view and expand the details block.
5. Confirm that clicking on an inner block within the list view opens and selects the inner block properly.

## Screencast

pr-demo

### CODE REVIEW

File: packages/block-library/src/details/edit.js [hunk 1]
```diff
@@ -108,7 +128,7 @@ function DetailsEdit( { attributes, setAttributes } ) {
 						}
 					/>
 				</summary>
-				{ innerBlocksProps.children }
+				{ shouldRenderChildren && innerBlocksProps.children }
```
Comment (yogeshbhutkar) [inline packages/block-library/src/details/edit.js]: When the Details block always displays its children, pressing the up arrow from the block below it doesn't move the selection to the Details block. This approach addresses that issue, but I'm open to a better approach here.

Comment (Mamaduka) [reply packages/block-library/src/details/edit.js]: Depending on the block content, this can be an expensive operation, because it will mount/unmount children. Additionally, it might affect accessibility since the `details` contents are rendered on demand.

**Comment by Mamaduka** [comment]
Adding handlers for arrow keys introduces a new behavior for `details`, which is expanded using <kbd>Space</kbd> or  <kbd>Enter</kbd> keys. Are we okay with this? It would be good to get a11y feedback on this PR before it's merged. cc @joedolson

P.S. I think @t-hamano was also working on this issue.

File: packages/block-library/src/details/edit.js [hunk 2]
```diff
@@ -42,6 +44,15 @@ function DetailsEdit( { attributes, setAttributes } ) {
...
 	const dropdownMenuProps = useToolsPanelDropdownMenuProps();
 
+	// Check if the inner blocks are selected.
+	const hasSelectedInnerBlock = useSelect(
+		( select ) =>
+			select( blockEditorStore ).hasSelectedInnerBlock( clientId, true ),
+		[ clientId ]
+	);
+
+	const shouldRenderChildren = hasSelectedInnerBlock || isSelected || isOpen;
```
Comment (Mamaduka) [inline packages/block-library/src/details/edit.js]: This reintroduces a buggy behavior resolved via https://github.com/WordPress/gutenberg/pull/67766. We should avoid introducing regression while trying to solve other bugs.

File: packages/block-library/src/details/edit.js (hunk 1 above)
Comment (yogeshbhutkar) [reply packages/block-library/src/details/edit.js]: Yes, I had the same concern. I'll try looking at some alternative approaches. For now, I've reverted this.

**Comment by alexstine** [comment]
@yogeshbhutkar Thanks for working on this.

@Mamaduka We need a way to expand the details block because it isn't currently possible in the editor with the keyboard alone. Give it a test on current trunk, not sure how anyone allowed a regression like this to slip by without keyboard testing. Seems like only way is the mouse at this point.

**Comment by yogeshbhutkar** [comment]
On a separate note, while spacebar toggling makes sense on the front end, it disrupts the editing experience (I understand it's the default behavior). Disabling this behavior when typing in the summary's rich text would be better. I'd appreciate any accessibility feedback on this.

bug

Observe, pressing the spacebar while typing toggles the hidden content, which could be confusing for users in the editor.

**Comment by alexstine** [comment]
@yogeshbhutkar Yes, absolutely. If you can detect focus in the summary rich text, space keyboard event needs to be prevented for expand/collapse.

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR! The approach that uses keyboard events to collapse or expand the content is an interesting approach.

The only concern is that the summary text can span multiple lines. In this case, the content is toggled every time you move from one line to another can be annoying.

Another approach I can think of may be using the Enter key. Additionally, ~let screenreader users know the details block was toggled by the `speak()` method~. In other words, the code would be like this:

```javascript
<summary
	onKeyDown={ ( event ) => {
		if ( event.key === 'Enter' && ! event.shiftKey ) {
			setIsOpen( ! isOpen );
			event.preventDefault();
		}
	} }
>
```

Finally, I think we also need to add some e2e tests to avoid regressions.

**Comment by t-hamano** [comment]
Another thing to note is that in CJK languages, an IME (Input Method Editor) is used to input complex characters.

There is [a higher-order function](https://github.com/WordPress/gutenberg/blob/8b7b04ab0c95abd52fb0ef6c7cbb7ec6b440ea23/packages/components/src/utils/with-ignore-ime-events.ts) to ignore keyboard events during IME composition. We will probably need to wrap keydown events in this function in your Details block as well.

See the following PRs for more details:

- https://github.com/WordPress/gutenberg/pull/59081
- https://github.com/WordPress/gutenberg/pull/60090

**Comment by alexstine** [comment]
That looks good @t-hamano. Shift enter will insert new line while enter will expand/collapse. I'm not overly thrilled with the UX but it is 100% better than trunk today. Also, can we fix the list view here as well? Any time a hidden block is selected, auto-expand the summary?

Thanks.

**Comment by t-hamano** [comment]
@alexstine  

> Also, can we fix the list view here as well? Any time a hidden block is selected, auto-expand the summary?

I think you can confirm that this issue has already been fixed in this PR. This is because when an inner block is selected in the List View, `hasSelectedInnerBlock` is `true` and the `open` attribute of the `details` element is `true`:

https://github.com/WordPress/gutenberg/pull/70056/files#diff-20d83620db8197c679e5617a73e78de6306074dff49588bb00fd5ee35a17793bR105

**Comment by joedolson** [comment]
This looks like it's progressing well; thanks for getting on this! I think that you all have this well in hand, but if you need a 2nd review once everything is ready, let me know.

**Comment by alexstine** [comment]
This is working much better indeed. For sure need to do something about the expanding content though. If I insert a new line with enter and then down arrow to it, all I hear is expanded. So I do like the idea of shift+enter to insert a new line, enter will trigger expand/collapse, and arrows should navigate the content only.

File: packages/block-library/src/details/edit.js [hunk 3]
```diff
@@ -42,6 +48,27 @@ function DetailsEdit( { attributes, setAttributes } ) {
...
+			event.preventDefault();
+		}
+	};
+
+	// Prevent spacebar from toggling <details> while typing.
+	const handleSummaryKeyUp = ( event ) => {
+		if ( event.key === ' ' ) {
+			event.preventDefault();
+		}
+	};
```
Comment (t-hamano) [inline packages/block-library/src/details/edit.js:70]: Do we actually need this code? It seems to work as expected without this code.

File: packages/components/src/private-apis.ts [hunk 4]
```diff
@@ -18,5 +19,6 @@ lock( privateApis, {
 	Theme,
 	Menu,
 	kebabCase,
+	withIgnoreIMEEvents,
```
Comment (t-hamano) [inline packages/components/src/private-apis.ts:22]: @WordPress/gutenberg-components 

We export this HOF as a private API. We need this function in the block library to prevent the Details content from being toggled by the Enter key event fired by the IME event.

File: test/e2e/specs/editor/blocks/details.spec.js [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+		editor,
+		page,
+	} ) => {
+		// Insert a details block with empty inner blocks.
+		await editor.insertBlock( {
+			name: 'core/details',
+			attributes: {
+				summary: 'Details summary',
+			},
+		} );
```
Comment (t-hamano) [inline test/e2e/specs/editor/blocks/details.spec.js]:
```suggestion
		await editor.insertBlock( {
			name: 'core/details',
			attributes: {
				summary: 'Details summary',
			},
			innerBlocks: [
				{
					name: 'core/paragraph',
					attributes: { content: 'Details content' },
				},
			],
		} );
```

It might be better to use an inner block with explicit text.

File: test/e2e/specs/editor/blocks/details.spec.js [hunk 6]
```diff
@@ -0,0 +1,84 @@
...
+
+		// Verify the summary is multiline.
+		await expect( summary ).toHaveText( 'First line\nSecond line', {
+			useInnerText: true,
+		} );
+	} );
+
+	test( 'typing space in summary rich-text should not toggle details', async ( {
+		editor,
+	} ) => {
```
Comment (t-hamano) [inline test/e2e/specs/editor/blocks/details.spec.js:74]: I'm not sure if this test is necessary. See https://github.com/WordPress/gutenberg/pull/70056#discussion_r2078800049

**Review by t-hamano — COMMENTED** [review]
Thanks for the update, @yogeshbhutkar!

I think this PR is going pretty well.

> Any time a hidden block is selected, auto-expand the summary?

Can we add an e2e test for this? The steps should be like this:

- Insert a Details block
- Open the List view
- Press the right arrow key: The inner blocks of the Details block are displayed in the List View
- Press the down arrow key: The first inner block is focused in the List View
- Press the enter key: The first inner block should be focused in the editor canvas

File: packages/block-library/src/details/edit.js (hunk 3 above)
Comment (yogeshbhutkar) [reply packages/block-library/src/details/edit.js:70]: https://github.com/user-attachments/assets/a6dbebaf-faf5-4176-9af7-01787abcacb2

I tested this across different browsers and found that it works correctly only in Firefox. On both Safari and Chrome (macOS), pressing the spacebar while typing in the summary input unexpectedly toggles the hidden blocks. I tried several approaches, but this was the only one that reliably worked. Additionally, when I run the Playwright test for this case locally, it consistently fails if this code is removed.

Comment (t-hamano) [reply packages/block-library/src/details/edit.js:70]: Interesting. In my environment ( Chrome and Firefox on Windows 11), the space key doesn't toggle the hidden blocks in the editor. The behavior may vary depending on the OS.

We also need to wrap this function with the `withIgnoreIMEEvents`, as in an IME, we use the space key during an IME composition, not just `enter` and arrow keys:

https://github.com/user-attachments/assets/102a89b3-226a-4a84-ac10-564749e32260

File: test/e2e/specs/editor/blocks/details.spec.js (hunk 6 above)
Comment (yogeshbhutkar) [reply test/e2e/specs/editor/blocks/details.spec.js:74]: As it's established that this behavior can be [OS specific](https://github.com/WordPress/gutenberg/pull/70056#discussion_r2078852443), I believe it's fair to keep this e2e test.

**Comment by megane9988** [comment]
I tested it.

OS: macOS 15.4.1（24E263）
Browser: Chrome 135.0.7049.115
IME: Google 日本語入力 ( https://www.google.co.jp/ime/ )

# Test Steps
- Adding a Details Block
-  Pressing the Enter key on the Summary text should toggle the content open and closed.
-  Pressing Enter + Shift on the Summary text should insert a line break without toggling the content.
-  Key operations while inputting Japanese (such as the Enter key and Space key) should be ignored, and the content should not toggle.


https://github.com/user-attachments/assets/087c597e-7755-4e68-9ed5-61c7cb419ce4

It worked well.

**Comment by megane9988** [comment]
I tested it.

OS: macOS 15.4.1（24E263）
Browser: Safari 18.4 (20621.1.15.11.10)
IME: Google 日本語入力 ( https://www.google.co.jp/ime/ )

# Test Steps
- Adding a Details Block
-  Pressing the Enter key on the Summary text should toggle the content open and closed.
-  Pressing Enter + Shift on the Summary text should insert a line break without toggling the content.
-  Key operations while inputting Japanese (such as the Enter key and Space key) should be ignored, and the content should not toggle.


https://github.com/user-attachments/assets/5388c2d0-df73-4a87-9335-fb2c88c22995


It also worked well.

**Comment by megane9988** [comment]
I also tested using ことえり ( macOS default IME ) in both browsers (Chrome and Safari).
It also worked well.

https://github.com/user-attachments/assets/aa5d0822-f330-466e-9b58-1a333a4992ee

File: packages/block-library/src/details/edit.js (hunk 3 above)
Comment (yogeshbhutkar) [reply packages/block-library/src/details/edit.js:70]: I've wrapped the function with `withIgnoreIMEEvents` in the latest commit. The docs for `withIgnoreIMEEvents` only mention key down events and not up events. (It needs to be generalized.)

Ref.
https://github.com/WordPress/gutenberg/blob/8b7b04ab0c95abd52fb0ef6c7cbb7ec6b440ea23/packages/components/src/utils/with-ignore-ime-events.ts#L9

MDN Reference:
https://developer.mozilla.org/en-US/docs/Web/API/Element/keyup_event#keyup_events_with_ime

Should the docs be updated?

**Comment by yogeshbhutkar** [comment]
I've incorporated all the feedback. A few follow-ups for the details block (separate from this PR):

1. We should add e2e coverage for drag-and-drop, as it previously caused a [regression](https://github.com/WordPress/gutenberg/pull/67766) and remains a risk.

2. Keyboard navigation should also be possible when the block is collapsed. As of now, hidden blocks restrict the movement, and removing them might not be good for accessibility.

3. When inserting inner blocks, only the first shows the correct `/` placeholder (Type `/` to add a hidden block). Subsequent ones revert to the default. We should persist the template message while adding hidden blocks to avoid confusion. Coming out of details requires double enter, but the editor screen shows no feedback. Plus, if we are adding a hidden block, the message should always state so.

I'd like to know the opinion of others on this.

File: packages/block-library/src/details/edit.js (hunk 3 above)
Comment (t-hamano) [reply packages/block-library/src/details/edit.js:70]: According to the test results by @megane9988, it seems to work as expected without wrapping the function with `withIgnoreIMEEvents`. We can probably remove `withIgnoreIMEEvents` from the `onKeydown` event handler as well. Sorry for the confusion.

> The docs for `withIgnoreIMEEvents` only mention key down events and not up events. (It needs to be generalized.)

Good catch, we can address this issue as a separate PR.

File: packages/components/src/private-apis.ts (hunk 4 above)
Comment (t-hamano) [reply packages/components/src/private-apis.ts:22]: Update: Let's test whether it works without this HOF.

**Comment by t-hamano** [comment]
@yogeshbhutkar Thanks for the update! 

I think it's almost ready to ship. The only thing to check is whether it works properly with CJK languages ​​without using `withIgnoreIMEEvents`.

@megane9988 Could you please test this PR from the following link one more time to make sure it works properly? 🙏

https://playground.wordpress.net/?gutenberg-pr=70056

@joedolson @alexstine I think this PR is ready from a code perspective, let me know if there are any other accessibility issues that should be addressed.

**Comment by megane9988** [comment]
@t-hamano 
Unfortunately, it did not work well.

I tested it.
https://playground.wordpress.net/?gutenberg-pr=70056

OS: macOS 15.4.1（24E263）
Browser: Safari 18.4 (20621.1.15.11.10) and Chrome 135.0.7049.115
IME: ことえり ( macOS default IME ) and IME: Google 日本語入力 ( https://www.google.co.jp/ime/ )

# Test Steps

- Pressing the Enter key on the Summary text should toggle the content open and closed.
- Pressing Enter + Shift on the Summary text should insert a line break without toggling the content.
- Key operations while inputting Japanese (such as the Enter key and Space key) should be ignored, and the content should not toggle.

# Result
- ✅️ Pressing the Enter key on the Summary text should toggle the content open and closed.
- ✅️ Pressing Enter + Shift on the Summary text should insert a line break without toggling the content.
- ❌️ Key operations while inputting Japanese (such as the Enter key and Space key) should be ignored, and the content should not toggle.
    - A Space key worked well. But the Enter key did not work well. It also toggles open and close when I press the Enter key.

https://github.com/user-attachments/assets/1fc4f176-2f8b-4200-9194-2b0fc126ebf2

**Comment by yogeshbhutkar** [comment]
Based on the test results, I think it's best to at least wrap the keydown handler function. The space would always work because it technically just prevents the default behavior; therefore, no abnormalities can be seen in the editor.

What do you think, @t-hamano?

**Comment by t-hamano** [comment]
Thank you so much for testing, @megane9988!

> I think it's best to at least wrap the keydown handler function.

@yogeshbhutkar Yes, based on his tests, it would be enough to apply HOF only to the keydown handler. Sorry for the frequent suggestions for changes.

File: packages/components/src/private-apis.ts (hunk 4 above)
Comment (t-hamano) [reply packages/components/src/private-apis.ts:22]: Update: If the HOF is not used, unintended events occur in the IME and it does not work properly (See https://github.com/WordPress/gutenberg/pull/70056#issuecomment-2862592442). Therefore, it is necessary to use HOF as a private API.

**Review by t-hamano — APPROVED** [review]
LGTM! Before shipping this PR, let's get some accessibility feedback again.

**Comment by alexstine** [comment]
@yogeshbhutkar This is looking much better. One final thought. Since it isn't clear that the details can be expanded, maybe add `aria-describedby` with some basic instructions?

> Press Enter to toggle details child blocks.

The expanded/collapsed state does enough to notify users of the exposed content, nice job on that.

I also agree it would be nice to do something about the "hidden" in the new block placeholder phrasing. The block isn't technically hidden if the details element is expanded.

Thanks.

**Comment by yogeshbhutkar** [comment]
Thanks for the feedback, @alexstine.

I've implemented the suggested feedback. When you have a moment, could you please re-review the changes and approve them if everything looks good?

**Comment by alexstine** [comment]
@yogeshbhutkar Can you add the `aria-describedby` to the input rich text field, not the block wrapper? If you press Enter from the block wrapper, you will insert a new block, not expand the element.

It also seems like something has changed where the Up/Down arrow keys can now toggle the display and this can be rather disruptive as Up/Down arrow keys allow screen reader users to read by line.

Thanks.

File: packages/block-library/src/details/edit.js [hunk 7]
```diff
@@ -30,10 +38,13 @@ const TEMPLATE = [
...
 ];
 
-function DetailsEdit( { attributes, setAttributes } ) {
+function DetailsEdit( { attributes, setAttributes, clientId } ) {
 	const { name, showContent, summary, allowedBlocks, placeholder } =
 		attributes;
-	const blockProps = useBlockProps();
+	const instanceId = useInstanceId( DetailsEdit, 'details-edit-desc' );
+	const blockProps = useBlockProps( {
+		'aria-describedby': instanceId,
```
Comment (alexstine) [inline packages/block-library/src/details/edit.js]: This cannot be defined here as pressing Enter at block wrapper level will insert a new block, not expand/collapse the summary.

**Review by alexstine — COMMENTED** [review]
I'm not sure if `RichText` can take `aria-describedby` by default, hopefully so. I would also like to see if anyone else can reproduce the Up/Down arrow keys toggling the state of the hidden blocks while in the summary edit field.

**Comment by yogeshbhutkar** [comment]
> I would also like to see if anyone else can reproduce the Up/Down arrow keys toggling the state of the hidden blocks while in the summary edit field.

I tested this and wasn't able to toggle the hidden blocks using the arrow keys; only the `Enter` key worked, as expected. I've attached a screencast for reference.

cc: @alexstine

Edit: I tested this in Chrome, Firefox, and Safari, but wasn't able to replicate it in any of them. Can you provide a screencast, as it might help me investigate this further?

https://github.com/user-attachments/assets/a2b2eb41-c123-4b38-955f-18242ea3e2bd

File: packages/block-library/src/details/edit.js (hunk 7 above)
Comment (yogeshbhutkar) [reply packages/block-library/src/details/edit.js]: Thanks! I've moved this to `RichText` and verified that the message now triggers correctly when typing in the `RichText` field.

**Comment by t-hamano** [comment]
Adding the `VisuallyHidden` component inside the `summary` element seems to add unexpected focus.

For example, add a Details block to the top and focus on the post title. The screen reader will read it as follows:

1. Press the down key: `Block: Details  document  blank`
2. Press the down key: `Press Enter to expand or collapse the details. Summary Text  button  collapsed  1 of 1`
3. Press the down key: `Write summary  edit  multi line  Press Enter to expand or collapse the details.  Summary Text`

https://github.com/user-attachments/assets/36bc4758-16d2-455d-ab24-24cebfb3c794

A second focus should not be necessary.

I would suggest that since the `RichText` component already has an `aria-label`, we just add the text there.

```diff
diff --git a/packages/block-library/src/details/edit.js b/packages/block-library/src/details/edit.js
index a21a00bade..c2df5721e9 100644
--- a/packages/block-library/src/details/edit.js
+++ b/packages/block-library/src/details/edit.js
@@ -130,14 +130,11 @@ function DetailsEdit( { attributes, setAttributes, clientId } ) {
                                        onKeyDown={ withIgnoreIMEEvents( handleSummaryKeyDown ) }
                                        onKeyUp={ handleSummaryKeyUp }
                                >
-                                       <VisuallyHidden id={ instanceId }>
-                                               { __(
-                                                       'Press Enter to expand or collapse the details.'
-                                               ) }
-                                       </VisuallyHidden>
                                        <RichText
                                                identifier="summary"
-                                               aria-label={ __( 'Write summary' ) }
+                                               aria-label={ __(
+                                                       'Write summary. Press Enter to expand or collapse the details.'
+                                               ) }
                                                aria-describedby={ instanceId }
                                                placeholder={ placeholder || __( 'Write summary…' ) }
                                                withoutInteractiveFormatting
```

So the screen reader should read something like this:

1. Press the down key: `Block: Details  document  blank`
2. Press the down key: `Write summary. Press Enter to expand or collapse the details.  edit  multi line  Summary Text`

> I would also like to see if anyone else can reproduce the Up/Down arrow keys toggling the state of the hidden blocks while in the summary edit field.

In the first state of this PR, we were using the up and down arrow keys.
But now we're using the enter key to toggle the content, so I think this issue is no longer a problem.

**Comment by t-hamano** [comment]
I think this PR is ready to ship. @alexstine What do you think?

I believe the following requirements are met in this PR:

- When the `RichText` component gets focus, the screen reader reads out the appropriate description.
- Pressing the Enter key toggles content, but is ignored during IME composition.
- Pressing the Shift+Enter key creates a multiline.
- When a block inside a Details block is selected in the List View, the content expands and the block gets focused.

**Comment by yogeshbhutkar** [comment]
This PR appears to have gone stale. Given that we've already completed the initial round of accessibility feedback and considering that this PR clearly enhances accessibility overall, I'd suggest proceeding with this PR. Any remaining or future accessibility concerns can be addressed as a follow-up.

cc: @t-hamano

**Comment by t-hamano** [comment]
> This PR appears to have gone stale. Given that we've already completed the initial round of accessibility feedback and considering that this PR clearly enhances accessibility overall, I'd suggest proceeding with this PR. Any remaining or future accessibility concerns can be addressed as a follow-up.

I agree. This PR is much better than the trunk one, so if there are improvements to the label reading, let's address them in a follow-up.

**Comment by joedolson** [comment]
Thanks for moving forward with this! I definitely agree that this is much better than the trunk version, and it makes far more sense to ship the improvements and iterate, rather than continue to need to refactor the patch when it's gone out of date.

**Comment by t-hamano** [comment]
I am checking the PRs with the "Backport to WP Minor Release" label applied to clarify which PRs should be backported to [the WordPress 6.8.2 release](https://make.wordpress.org/core/2025/06/17/wordpress-6-8-2-release-schedule/).

I believe this PR should be backported to the 6.8.2 release since it is a regression that occurred in 6.8.

**Comment by joedolson** [comment]
Agreed!

**Comment by t-hamano** [comment]
This PR was cherry-picked into the `wp/6.8` branch for the WP 6.8.2 release: #70557
