### PR TITLE
Navigation Block: Add missing menu item attributes to core/navigation

### LINKED ISSUE #4813: Quadrat: open in a new tab not working for menu links
## Steps to replicate

- Checked “Link Target” in advanced menu properties in the Customizer: https://d.pr/i/tqgq4Z

image

- Checked “Open link in a new tab” in the menu element: https://d.pr/i/8qxhI5

image

## Result

- Clicking on the link, the linked page opens in the same tab
- With a different theme this does not happen

## Expected

Setting a menu item to open in a new tab should result in the linked page opening in a new tab

* User report: 4366104-zd-woothemes

### PR DESCRIPTION
**Pull request by mikachan**
## Description

The `navigation-link` block handles the following attributes if they are passed through to the block: `url`, `opensInNewTab`, `rel`, and `title`.

However, if the `navigation` block is used on its own for a menu, without any `navigation-link` block children (such as automatically populating a menu with an `__unstableLocation` set), the `opensInNewTab`, `rel` and `title` attributes are not passed through to the front end.

It looks like this is because these attributes are not handled in `gutenberg_parse_blocks_from_menu_items`, so this PR adds these 3 attributes to this function.

## How has this been tested?

Add a `navigation` block on its own with an `__unstableLocation`:

```
<!-- wp:navigation {"itemsJustification":"right","isResponsive":true,"__unstableLocation":"primary"} /-->
```

You'll also need a menu set to the primary location. Then set at least one link to open in a new tab, set a title and set a link relationship:

image

Before:
image

After:
image

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 

Fixes https://github.com/Automattic/themes/issues/4813

### CODE REVIEW

File: packages/block-library/src/navigation/index.php [hunk 1]
```diff
@@ -161,11 +161,17 @@ function gutenberg_parse_blocks_from_menu_items( $menu_items, $menu_items_by_par
...
+
 		$block = array(
 			'blockName' => 'core/navigation-link',
 			'attrs'     => array(
-				'label' => $menu_item->title,
-				'url'   => $menu_item->url,
+				'label'         => $menu_item->title,
+				'opensInNewTab' => $opens_in_new_tab,
+				'rel'           => $rel,
+				'title'         => $menu_item->title,
```
Comment (talldan) [inline packages/block-library/src/navigation/index.php]: Not 100% sure, but I think it should be `$menu_item->attr_title` for the block's title attribute. Otherwise it ends up the same as the label.

There's a JavaScript version of this function that I referenced, and it probably indicates some other things are missing too:
https://github.com/WordPress/gutenberg/blob/5185ffc964b4a8bf77ee72da146598205c41620b/packages/block-library/src/navigation/menu-items-to-blocks.js#L114-L166

Comment (mikachan) [reply packages/block-library/src/navigation/index.php]: > Not 100% sure, but I think it should be $menu_item->attr_title for the block's title attribute. Otherwise it ends up the same as the label.

Thanks, this makes sense! I've changed it and it looks like it works well.

Thanks also for pointing me in the direction of that JS function. I'll run through this and see if I can match up the other missing attributes.

File: packages/block-library/src/navigation/index.php [hunk 2]
```diff
@@ -161,11 +161,18 @@ function gutenberg_parse_blocks_from_menu_items( $menu_items, $menu_items_by_par
...
 	foreach ( $menu_items as $menu_item ) {
+		$opens_in_new_tab = null !== $menu_item->target && '_blank' === $menu_item->target;
+		$rel              = ( null !== $menu_item->xfn && '' !== $menu_item->xfn ) ? $menu_item->xfn : null;
+
 		$block = array(
 			'blockName' => 'core/navigation-link',
 			'attrs'     => array(
-				'label' => $menu_item->title,
-				'url'   => $menu_item->url,
+				'classes'       => $menu_item->classes,
```
Comment (talldan) [inline packages/block-library/src/navigation/index.php]: This stood out to me as the link block doesn't have a `classes` attribute.

I think it'd be good to try to stick to block attributes so that the render code in the block doesn't need changes.

It might be an option to use `className` instead here, which is added by the `customClassName` hook by default to all blocks that don't opt out:
https://github.com/WordPress/gutenberg/blob/39b4c968b2b4faa7c701faf388efac72e3ed1e66/packages/block-editor/src/hooks/custom-class-name.js#L33-L35

By doing that it should also be possible to avoid the changes to the navigation-link/index.php. The array to string conversion would have to be moved from there to here.

Comment (talldan) [reply packages/block-library/src/navigation/index.php]: When I check back on this PR I realised this comment above was still 'pending' (had probably been so for about three days). Better late than never!

Comment (mikachan) [reply packages/block-library/src/navigation/index.php]: > When I check back on this PR I realised this comment above was still 'pending' (had probably been so for about three days). Better late than never!

Haha no worries! Thanks for the pointer with `className`, I'll take a look at this next.

File: packages/block-library/src/navigation-link/index.php [hunk 3]
```diff
@@ -152,12 +152,6 @@ function render_block_core_navigation_link( $attributes, $content, $block ) {
 	$has_submenu = count( $block->inner_blocks ) > 0;
 	$is_active   = ! empty( $attributes['id'] ) && ( get_the_ID() === $attributes['id'] );
 
-	$class_name = ! empty( $attributes['className'] ) ? implode( ' ', (array) $attributes['className'] ) : false;
-
-	if ( false !== $class_name ) {
-		$css_classes .= ' ' . $class_name;
-	}
-
```
Comment (talldan) [inline packages/block-library/src/navigation-link/index.php:160]: @mikachan Just double-checking, should this have been removed?

I was thinking that the `navigation-link/index.php` would be able to remain unchanged from `trunk`.

Comment (mikachan) [reply packages/block-library/src/navigation-link/index.php:160]: I was seeing some of the class names being duplicated, which is why I removed this. I can't see where they're being added originally though.

With `$attributes['className']`:

image

Without `$attributes['className']`:

image

`faq-class` (a custom test class I've added from Appearance > Menus), `menu-item`, `menu-item-type-post_type`, and `menu-item-object-page` are all duplicated when `$attributes['className']` is used here. If I change the attribute name to something else (in both `navigation-link/index.php` and `navigation/index.php`), then the class names are only included once, so I'm assuming something else is picking up on `className` and adding them. If I var_dump `$attributes['className']`, it only includes unique classes, and I'm struggling to find where the others are added.

Ideally, I'd like to leave `navigation-link/index.php` unchanged and fix the duplication problem. If you have time, it would be great if you have any ideas around this!

Comment (talldan) [reply packages/block-library/src/navigation-link/index.php:160]: Ah, yep, you're right, good catch. It seems like a bug in trunk that a custom class name is applied twice (happens when using the navigation block normally in the block editor too), so this would be a fix.

> I can't see where they're being added originally though.

I think it must be via the `get_block_wrapper_attributes` function, which is defined in WordPress core:
https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/class-wp-block-supports.php#L179

Since the block supports both generated and custom class names, those values get merged in like this:
https://github.com/WordPress/wordpress-develop/blob/b45c85a405ab0b1968380a79f7a76dc9293adc0f/src/wp-includes/block-supports/custom-classname.php#L44-L56

In that case it looks good to me, will approve the PR

**Review by talldan — APPROVED** [review]
Thanks for improving this, and also fixing the bug with class names. 🎉

File: packages/block-library/src/navigation-link/index.php (hunk 3 above)
Comment (mikachan) [reply packages/block-library/src/navigation-link/index.php:160]: Ahh brilliant, I understand, thanks so much for explaining. Nice, unexpected bug fix!

Thanks for your help with this! 🎉
