### PR TITLE
Layout: fix flex direction column

### LINKED ISSUE #42938: Row element with stack orientation doesn't work
### Description

The row element with stack orientation doesn't work since https://github.com/WordPress/gutenberg/pull/42452 was merged.

### Step-by-step reproduction instructions

- Add a Row element
- Add two paragraphs inside the row element
- Select stack orientation in the row element
- Save the post and verify in the frontend that the elements are not vertically stacked.

### Screenshots, screen recording, code snippet

The editor

image

Frontend:
image

### Environment info

- WordPress 6.0.1
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by matiasbenedetto**
Fixes: https://github.com/WordPress/gutenberg/issues/42938

## What?
Fixing stacked (column/vertical) orientation of the row block.

## Why?
The row element with stack orientation doesn't work since https://github.com/WordPress/gutenberg/pull/42452 was merged.
Currently, the CSS related to the flex-direction is not rendered in the frontend.

## How?
This PR fixes the styles engine to render the CSS to the flex-direction in the frontend.

## Testing Instructions
- Add a Row element
- Add two paragraphs inside the row element
- Select stack orientation in the row element
- Save the post and verify in the frontend that the elements are not vertically stacked.

## Screenshots or screencast 
Before:
image

After:
image

Fixes: https://github.com/WordPress/gutenberg/issues/42938

### CODE REVIEW

**Review by ramonjd — APPROVED** [review]
Thanks for catching that one. Must have slipped past us 😄

File: lib/block-supports/layout.php [hunk 1]
```diff
@@ -184,9 +184,9 @@ function gutenberg_get_layout_style( $selector, $layout, $has_block_gap_support
 				);
 			}
 		} else {
-			$layout_styles[ $selector ] = array(
-				'flex-direction' => 'column',
-				'align-items'    => 'flex-start',
+			$layout_styles[] = array(
+				'selector'     => $selector,
+				'declarations' => array( 'flex-direction' => 'column' ),
```
Comment (ramonjd) [inline lib/block-supports/layout.php:189]: Not sure, but should the align-items prop also come across?

```suggestion
				'declarations' => array( 'flex-direction' => 'column', 'align-items' => 'flex-start' ),
```

Comment (andrewserong) [reply lib/block-supports/layout.php:189]: It looks like we already have a duplicate `'align-items' => 'flex-start'` in the else condition below, so I think we were duplicating that output previously?

**Review by andrewserong — APPROVED** [review]
Thanks so much for catching this one @matiasbenedetto! It turns out with #42452, I was testing the layout implementation using the Buttons block, which provides its own vertical orientation CSS, so it didn't catch this one in manual testing 🤦

We'll now know to properly test the Stack variation, too!

This LGTM, so I'll merge it in once the e2es pass. Thanks! 🙇

**Comment by andrewserong** [comment]
I've just given this a rebase to get the e2e tests passing now that https://github.com/WordPress/gutenberg/pull/42947 has been merged
