### PR TITLE
Try: Fix issue where block fails validation when a default attribute is deprecated

### LINKED ISSUE #11705: Error when deprecating the default value of a block attribute
**Describe the bug**
Changing a custom block's default attribute value results in the error: `This block contains unexpected or invalid content.`

**To Reproduce**
1. Register a custom block with an attribute that has a default value
2. Edit a post, then add the custom block, save the post
3. Edit the registered block and change the default value
4. Edit the previous post. The block will have an error

**Expected behavior**
The previously added block shouldn't have an error. Since the block with the error was old, I expect that it shouldn't be affected with a change in an attribute's default value.

Also, removing the default value doesn't result in an error, but changing it does.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
- OS: MacOS High Sierra 10.13.6
- Browser: Chrome
- Version: 69.0.3497.100

**Additional context**
- Gutenberg v4.2

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #11705

Block implementors are unable update their code to change the default value for an attribute, even when adding a deprecation. Block validation fails for posts that contain blocks still using an old default.

Note - this is only for attributes that aren't sourced

## How has this been tested?
1. Add a columns block to a new post (keeping the number of columns at the default of 2) and save the post
2. Modify the code of the columns block, changing the `columns` attribute default from 2 to 3. 
3. Load the post created in step 1 and observe that the columns block failed validation.
4. Add a deprecation for the columns block to try to solve the failed validation, ensure this new deprecation still has the old default value for the `columns` attribute of 2.
5. Load the post created in step 1.

**Expected Result**
The deprecation with the column count of 2 should be applied.

**Actual Result**
The block fails validation.

## Diagnosis

The bug occurs because the attempt to apply the deprecation fails validation here and so the deprecation is skipped (`isValid` is false):
https://github.com/WordPress/gutenberg/blob/40d1282a992702e1933118ef626f0666692baf2b/packages/blocks/src/api/parser.js#L338-L353

This is happening because the `attributes` variable in the above call to `getBlockAttributes` has the default value from the failed initial attempt to create the block (in case of the columns example above, that would be the new default of 3). Because of that the deprecation's default is not applied (as there's already an existing value).

## Fix
Instead of using the attributes from the failed first attempt to create the block when validating a deprecation, this fix instead uses the attributes as they were when the block markup was parsed (those initially passed into `createBlockWithFallback`):
https://github.com/WordPress/gutenberg/blob/40d1282a992702e1933118ef626f0666692baf2b/packages/blocks/src/api/parser.js#L386-L392

This means that a deprecation receives the same attributes that normal block creation would receive, which to me seems logical.

## Types of changes
Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by talldan** [comment]
Oh, sorry about that, updated tests and added a test case to cover this fix.

**Comment by talldan** [comment]
Would like some developer feedback on this. I realise this introduces the need to deprecate `getMigratedBlock` due to the extra param, which is less than ideal.

One way around that could be to store the original attributes on the block in the same way as `originalContent` is here before the call to `getMigratedBlock`:
https://github.com/WordPress/gutenberg/blob/6262b603bb5b8cb13ac7f118334bf71622a5b5f3/packages/blocks/src/api/parser.js#L469-L471

I wanted to avoid mutation and that data being kept around longer than necessary.

**Comment by aduth** [comment]
> I realise this introduces the need to deprecate `getMigratedBlock` due to the extra param, which is less than ideal.

Can you elaborate why a deprecation would occur, if `getMigratedBlock` is not part of any public interface?

File: packages/blocks/src/api/test/parser.js [hunk 1]
```diff
@@ -529,10 +532,53 @@ describe( 'block parser', () => {
 				],
 			} );
 
-			const migratedBlock = getMigratedBlock( block );
+			const migratedBlock = getMigratedBlock( block, parsedAttributes );
 
 			expect( migratedBlock.attributes ).toEqual( { fruit: 'Bananas!' } );
 		} );
+
+		it( 'allows a default attribute to be deprecated', () => {
```
Comment (aduth) [inline packages/blocks/src/api/test/parser.js]: Being a bit confused about what actually changed as part of the implementation aside from moving attributes into an argument rather than having it be destructured, I copied this test and this test only into master. It passed. I can't imagine that's expected? I'd expect the test case would be one which only passes in the branch, and fails on master.

**Comment by talldan** [comment]
> Can you elaborate why a deprecation would occur, if `getMigratedBlock` is not part of any public interface?

I think that's down to me misinterpreting what's public and what's internal. Thanks for the clarification.

File: packages/blocks/src/api/test/parser.js (hunk 1 above)
Comment (talldan) [reply packages/blocks/src/api/test/parser.js]: Thanks for the catch - looks like I made a mistake in the test with attribute type, which was causing a false positive (the types didn't match so that attribute was being reset). Fixed here:
https://github.com/WordPress/gutenberg/pull/12757/commits/ec0e490375ed3de842a05e28e421e37b5f6ff1f8

> Being a bit confused about what actually changed as part of the implementation aside from moving attributes into an argument rather than having it be destructured.

It's really hard to explain!

The difference is that before this change, the attributes may have had defaults applied from the main block type:
https://github.com/WordPress/gutenberg/blob/master/packages/blocks/src/api/parser.js#L455

If the main block type fails validation, the deprecations are attempted, but the default value from main block type is passed in when testing the deprecations, which doesn't give the deprecations a chance to apply their own defaults.

My change instead passes the original attributes from before those defaults from the main block type have been applied into `getMigratedBlock`, which gives the deprecations a chance to use their defaults.

**Review by mcsf — APPROVED** [review]
The change is well reasoned and tests well for me. Thanks for the fix, LGTM.

@aduth, did Dan clarify things for you?

**Review by aduth — APPROVED** [review]
Thanks for the explanation 👍
