### PR TITLE
Enable drag and drop in List View, fix performance issues

### LINKED ISSUE #25067: Improve performance of List View drag and drop
**Describe the bug**
The performance for drag and drop in List View (currently enabled on the experimental navigation page) deteriorates significantly in relation to the number of blocks present, in contrast to the general editor canvas.

I've noticed a few things that can be improved. A big on seems to be that `useDropZone` is continually 

**To reproduce**
1. Open the experimental navigation page
2. Add lots of blocks (duplicating is the easiest way to do this)
3. Try dragging and dropping in list view

**Expected behavior**
Observe the updates to the drop zones and draggable chip become very laggy.

### LINKED ISSUE #29727: List View: Allow drag and drop to reorder items
## What problem does this address?
We have numerous tools to reorder blocks. The List View provides a glancable tool of your site structure, and is used in a few places, it's in the post editor, it's in the post editor, it works as a persistent sidebar in the site editor, and it exists as a tool for the navigation block. 

We could offer an additional drag and drop affordance in this tool, which might be useful for very long posts, or for the navigation which might feature complex nesting in menus.

## What is your proposed solution?

**Note:** This change should apply to anywhere we use the List View component. Here shown for the Navigation block:

list view

Make the entire list view item draggable:

list view hover

You'd still be able to focus the item itself, or the ellipsis, individually:

focus

The ellipsis menu contains a "Move to..." item that duplicates the move action.

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #25067
Fixes #29727

Enables list view drag and drop and fixes the performance issues.

List view's drag and drop has been implemented for a while, but disabled due to some performance issues were solved. The main problem is that previously the drag and drop system in List View used borders on each individual block for displaying the drop indicator. This means that when dragging over a list of block, each individual block has to re-render.

This change makes the drop indicator a separate popover element, which mirrors how the InsertionPoint component in the normal block list works. Only this single component now has to re-render, which improves things significantly in my tests.

## How has this been tested?
Some things to try:
- Drag and drop blocks around reordering as siblings
- Drag blocks into groups/columns
- Test using a large number of blocks

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-editor/src/components/list-view/block-contents.js [hunk 1]
```diff
@@ -62,27 +55,8 @@ const ListViewBlockContents = forwardRef(
...
-			dropTargetClientId === clientId &&
-			dropPosition === 'bottom';
-		const isDroppingToInnerBlocks =
-			dropTargetRootClientId === clientId && dropPosition === 'inside';
-
 		const className = classnames( 'block-editor-list-view-block-contents', {
-			'is-dropping-before': isDroppingBefore || isBlockMoveTarget,
-			'is-dropping-after': isDroppingAfter,
-			'is-dropping-to-inner-blocks': isDroppingToInnerBlocks,
+			'is-dropping-before': isBlockMoveTarget,
```
Comment (talldan) [inline packages/block-editor/src/components/list-view/block-contents.js:59]: TODO - remove this and use the new drop indicator for the 'Move To' option.

File: packages/block-editor/src/components/list-view/index.js [hunk 2]
```diff
@@ -122,21 +120,25 @@ export default function ListView( {
...
-			aria-label={ __( 'Block navigation structure' ) }
-			ref={ treeGridRef }
-			onCollapseRow={ collapseRow }
-			onExpandRow={ expandRow }
-		>
-			<ListViewContext.Provider value={ contextValue }>
+		<ListViewContext.Provider value={ contextValue }>
+			<ListViewDropIndicator
+				listViewRef={ elementRef }
+				blockDropTarget={ blockDropTarget }
```
Comment (talldan) [inline packages/block-editor/src/components/list-view/index.js:126]: TODO - try making List View use the Insertion Point state so that the indicators appear in both the main and list view block lists.

File: packages/block-editor/src/components/list-view/index.js [hunk 3]
```diff
@@ -122,21 +120,25 @@ export default function ListView( {
...
 	return (
-		<TreeGrid
-			className="block-editor-list-view-tree"
-			aria-label={ __( 'Block navigation structure' ) }
-			ref={ treeGridRef }
-			onCollapseRow={ collapseRow }
-			onExpandRow={ expandRow }
-		>
-			<ListViewContext.Provider value={ contextValue }>
+		<ListViewContext.Provider value={ contextValue }>
```
Comment (talldan) [inline packages/block-editor/src/components/list-view/index.js]: TODO - move this back where it was.

File: packages/block-editor/src/components/list-view/index.js (hunk 2 above)
Comment (talldan) [reply packages/block-editor/src/components/list-view/index.js:126]: Tried this out, but it does slow things down a bit, will push my explorations to a separate PR.

File: packages/block-editor/src/components/list-view/block-contents.js (hunk 1 above)
Comment (talldan) [reply packages/block-editor/src/components/list-view/block-contents.js:59]: Hmm, I'm going to make this a follow up too. I think Move To needs some refactoring. It currently changes the selected block to determine where it should be inserted, but it should just use the `insertionPoint` too. It needs changing in both the main block editor and list view.

**Comment by talldan** [comment]
This is ready for review now.

https://github.com/WordPress/gutenberg/pull/33327 should be merged before this though, the tests I've added depend on that.

File: package-lock.json [hunk 4]
```diff
@@ -15704,7 +15704,7 @@
 				"postcss": "^8.2.15",
 				"postcss-loader": "^4.2.0",
 				"prettier": "npm:wp-prettier@2.2.1-beta-1",
-				"puppeteer-core": "^9.0.0",
+				"puppeteer-core": "^10.0.0",
```
Comment (gwwar) [inline package-lock.json]: Did we mean to include package-lock updates?

File: packages/scripts/package.json [hunk 5]
```diff
@@ -69,7 +69,7 @@
 		"postcss": "^8.2.15",
 		"postcss-loader": "^4.2.0",
 		"prettier": "npm:wp-prettier@2.2.1-beta-1",
-		"puppeteer-core": "^9.0.0",
+		"puppeteer-core": "^10.0.0",
```
Comment (gwwar) [inline packages/scripts/package.json]: Did we mean to bump puppeteer in this PR?

**Review by gwwar — COMMENTED** [review]
What sort of initial performance targets are we aiming for? I am seeing some dropped frames while dragging in list view with the natural resources pattern.

Screen Shot 2021-07-09 at 9 01 39 AM

I did a very quick check, but one hotspot is the dragover event:
Screen Shot 2021-07-09 at 8 59 50 AM

I'm guessing this is coming from a library ( I didn't dig too deep), but modifying `width`, `height`, `left`, `right`  props are one of the most expensive actions (basically anything that modifies getboundingclientrect) since we end up needing to go through layout > paint > and composite steps in the rendering process.

One thing we could try is seeing it's possible to use `transform` property for dragging which can potentially skip layout and paint steps.

See also: https://developers.google.com/web/fundamentals/performance/rendering

> This change makes the drop indicator a separate popover element, which mirrors how the InsertionPoint component in the normal block list works. Only this single component now has to re-render, which improves things significantly in my tests.

One other idea might be to render all droppable indicators _once_ while starting a drag, but toggle `opacity` of them as we enter over them. We'd of course need to profile to test if this helps or not.

I'll leave a some follow up comments for manual testing, as I did spot a few things.

**Comment by gwwar** [comment]
Overall this looks pretty close @talldan! I did spot a few things, so may want to disable dragging in some list view instances or try to polish the behavior.

❌ The navigation block also has a list view, trying to drag in this modal can abruptly close this, since I think we're fighting with the other draggables in the post editor:

https://user-images.githubusercontent.com/1270189/125108985-9d611180-e097-11eb-8296-aa2c04299b91.mp4

❌ When the persistent list view is open in the post editor, and we try dragging the modal, the wrong draggable indicators are updated:

https://user-images.githubusercontent.com/1270189/125109394-25471b80-e098-11eb-95a6-237b0edf670c.mp4

✅ Persistent List View Looks Good in Post Editor ✨ 

https://user-images.githubusercontent.com/1270189/125109554-617a7c00-e098-11eb-8914-fb6b203fd966.mp4

✅ Persistent List View Looks Good in Site Editor

https://user-images.githubusercontent.com/1270189/125109980-e4033b80-e098-11eb-9b77-a249c04c4691.mp4

❓ Navigation Editor

🤔 There's two ways of dragging in the Navigation Editor. One using the modal, and the other using an editor mode when we press <kbd>esc</kbd>
- The modal feels a bit funny when we have a whole editor dedicated to this. (It does behave well for dragging though!)
- When pressing <kbd>esc</kbd> the chip sits on top of the editor (which is maybe not intentional?) and we're able to do some funny things like drag the entire nav parent around.

We may want some UX feedback for this. What's our preferred way of dragging? cc @jasmussen @shaunandrews maybe?

https://user-images.githubusercontent.com/1270189/125110846-ff227b00-e099-11eb-9c9b-38381fe54a4e.mp4

https://user-images.githubusercontent.com/1270189/125110929-1c574980-e09a-11eb-8351-99137082a271.mp4

✅ Widget Editor looks good

I did notice two things: the list view isn't persistent (it's a dropdown vs sidebar), and we allow draggables from the list view to drop into the main editor (which looks like it works?)


https://user-images.githubusercontent.com/1270189/125112108-9805c600-e09b-11eb-8aca-74572fca9166.mp4


https://user-images.githubusercontent.com/1270189/125111808-334a6b80-e09b-11eb-9169-6606d97290fc.mp4


Things for potential follow ups:
💡 Nice to have: when List View items are collapsed, and we drag hover over it, let's toggle it open. 
💡 Nice to have: better hint that these items are draggable.

**Comment by gwwar** [comment]
Here's a video showing that the layout shifts are coming from the draggable chip:

https://user-images.githubusercontent.com/1270189/125113649-c71d3700-e09d-11eb-9faf-5ac415da06e0.mp4

Edit: https://web.dev/cls/#animations-and-transitions 
https://web.dev/debug-layout-shifts/

> To move elements around, avoid changing the top, right, bottom, or left properties and use transform: translate() instead.

Looks like this is recommended ✨

File: package-lock.json (hunk 4 above)
Comment (talldan) [reply package-lock.json]: 👍 I do have another PR which is handling a Puppeteer upgrade - #33327. I'll rebase this and drop the changes when that's merged.

**Comment by talldan** [comment]
Thanks for the amazing review @gwwar!

> What sort of initial performance targets are we aiming for?

It's mostly anecdotal, but with the previous implementation there were two main issues:
- scrolling was very juddery.
- the drop indicator was very laggy at updating it's position

So if that doesn't happen too much it's a good sign. I've been testing using the demo post, which has a decent number of blocks.

I think as long as it's working reasonably well, it'd be great for this feature to be released in the plugin for further testing and feedback, especially at this early stage where there's a fair amount of time until the next WordPress release.

> I'm guessing this is coming from a library ( I didn't dig too deep), but modifying width, height, left, right props are one of the most expensive actions (basically anything that modifies getboundingclientrect) since we end up needing to go through layout > paint > and composite steps in the rendering process.

This is a really good point. AFAIK, all popovers modify `top` and `left`, so I wonder if it's possible to try using `transform`. It may have been tried before, not sure. I don't think `BlockDraggableChip` uses popovers to this might be a good place to start using transform. I'll try that out in a separate PR.

> The navigation block also has a list view, trying to drag in this modal can abruptly close this, since I think we're fighting with the other draggables in the post editor:

Thanks, I'll take a look at this and see if I can fix it in this PR. 

> When the persistent list view is open in the post editor, and we try dragging the modal, the wrong draggable indicators are updated:

Oh wow, I think it's just using the first element it finds using `getElementById`, so this would mean there are also duplicate ids in the document when ListView is in two places. I think list view can probably avoid using those ids in favour of data-block attributes it already has. I'll take a look at that in this PR.

> I did notice two things: the list view isn't persistent (it's a dropdown vs sidebar), and we allow draggables from the list view to drop into the main editor (which looks like it works?)

I think the widget editor would definitely benefit from the persistent list view, given the widget areas automatically have nesting. Being from list view to the main block list is intentional 😄.

> Things for potential follow ups:
>💡 Nice to have: when List View items are collapsed, and we drag hover over it, let's toggle it open.
>💡 Nice to have: better hint that these items are draggable.

I'll make sure to capture these ideas. There are some ideas on https://github.com/WordPress/gutenberg/issues/29727 that should be followed-up on too. A lot of this came quite a long time after I'd already developed the drag and drop feature for the navigation screen (https://github.com/WordPress/gutenberg/pull/23952), but then List View was mostly removed from that screen so the feature has just lay dormant. With the persistent list view it's now very relevant again.

File: packages/block-editor/src/components/block-draggable/index.js [hunk 6]
```diff
@@ -75,7 +74,6 @@ const BlockDraggable = ( {
 	return (
 		<Draggable
 			cloneClassname={ cloneClassname }
-			elementId={ elementId }
```
Comment (talldan) [inline packages/block-editor/src/components/block-draggable/index.js:78]: The `elementId` prop seems to be dead code, `Draggable` ignores it when `__experimentalDragComponent` is defined, and `BlockDraggable` has that prop hard-coded just below this line.

**Comment by talldan** [comment]
> The navigation block also has a list view, trying to drag in this modal can abruptly close this, since I think we're fighting with the other draggables in the post editor

@gwwar I tried a few different things, but couldn't reproduce this. Let me know if you have any pointers for reproducing it.

> When the persistent list view is open in the post editor, and we try dragging the modal, the wrong draggable indicators are updated:

I've fixed this one.

**Comment by gwwar** [comment]
> The navigation block also has a list view, trying to drag in this modal can abruptly close this, since I think we're fighting with the other draggables in the post editor

> When the persistent list view is open in the post editor, and we try dragging the modal, the wrong draggable indicators are updated:

✅ I've verified that these two issues are now fixed. ✨

**Review by gwwar — APPROVED** [review]
> I think as long as it's working reasonably well, it'd be great for this feature to be released in the plugin for further testing and feedback, especially at this early stage where there's a fair amount of time until the next WordPress release.

That sounds reasonable to me! Dragging is currently usable but not smooth on my dev laptop. Ideally we'll want to do a few browser profiling passes at it so folks can use this without needing beefy hardware.

> This is a really good point. AFAIK, all popovers modify top and left, so I wonder if it's possible to try using transform. It may have been tried before, not sure. I don't think BlockDraggableChip uses popovers to this might be a good place to start using transform. I'll try that out in a separate PR.

Happy to help investigate that too. So this is coming from the [popovers component](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/popover)? Edit: ah I think it's from draggable https://github.com/WordPress/gutenberg/blob/dc1821fe6763ddd0b6f4ecc143a136aa13d25352/packages/components/src/draggable/index.js#L103-L113

**Comment by talldan** [comment]
> Happy to help investigate that too. So this is coming from the popovers component? Edit: ah I think it's from draggable

That's the one. 👍 

Hopefully shouldn't be too complicated to modify those styles.

**Comment by priethor** [comment]
Amazing review of an amazing PR! 👏 ❤️

**Comment by gwwar** [comment]
@talldan I started profiling drag performance in https://github.com/WordPress/gutenberg/pull/33395

Looks like there some nice potential gains if we can also tune dropzone handling to not fire until a user intends to drop an item (vs triggering it while we're dragging quickly).

**Comment by nixsee** [comment]
I apologize if this is not the right place to share this. You can move it if necessary (or tell me to).

This functionality is great, but it doesn't seem to allow you to drag a child-block to the bottom of the list at the top-level of the hierarchy unless you bring it to the very top of the list and then rearrange the top-level blocks using their Move Up/Down arrows. Here's a screen recording of what I mean.

Also, it would be nice to have a wider space to drag within - ideally anywhere above and below the top and bottom of the list would be treated as a draggable section, rather than just a small sliver. I submitted similar feedback about dragging blocks within the editor too here (https://github.com/WordPress/gutenberg/issues/32438)


https://user-images.githubusercontent.com/24255237/126843315-fb9f6726-7abe-4ed4-9c42-790784af21bb.mp4

**Comment by talldan** [comment]
Thanks for the feedback @nixsee.

Those were both known issues, but I don't think they're adequately tracked in github.

https://github.com/WordPress/gutenberg/issues/33678 now tracks the un-nesting issue.

I've also put together an overview issue for drag and drop (https://github.com/WordPress/gutenberg/issues/33683), which incorporates #32438.
