### PR TITLE
RichText: Format boundaries without DOM

### LINKED ISSUE #11091: Highlighted formatting in the toolbar doesn't match MCE inline boundaries
Duplicates: #11326, #13087.

**Describe the bug**
There's a minor inconsistency with the formatting toolbar and TinyMCE's inline boundaries (used to highlight formatted text).

When the caret is positioned on the left side of formatted text, within the inline boundary, the toolbar button for the active formatting is correctly shown toggled on:
screen shot 2018-10-26 at 4 05 40 pm

Pressing the left arrow key once to move the caret outside of the inline boundary, the format is incorrectly still shown toggled on:
screen shot 2018-10-26 at 3 57 50 pm

Positioning the caret on the right side of formatted text, back within the inline boundary, the toolbar button is incorrectly toggled off:
screen shot 2018-10-26 at 3 52 46 pm

**To Reproduce**
1. Add formatted text (bold/italic/strikethrough/link) to a paragraph block.
2. Position the caret on the left of the formatted text within the inline boundary.
3. Move the mouse to display the toolbar and observe that formatting is toggled on correctly.
4. Press the left arrow key once to move outside of the inline boundary.
5. Move the mouse to display the toolbar and observe that formatting is incorrectly toggled on.
6. Position the caret on the right of the formatted text within the inline boundary.
7. Move the mouse to display the toolbar and observe that formatting is incorrectly toggled off.

**Expected behavior**
The toggle state of toolbar formats should match the position of the caret.

**Additional context**
- 4.1
- Noticed while working on #10983

### LINKED ISSUE #11178: Cursor positioning lost after pasting a link onto text selection following CTRL + SHIFT selection
**Describe the bug**
When selecting text, I expect the right arrow key to take me to the end of the selection. After pasting a link on top of a text selection made with CTRL + SHIFT, the right arrow key deselects text and the text cursor is placed at the _start_ of the selection.

**To Reproduce**
1. Type out anchor text
2. Use CTRL + SHIFT to select the text (selecting text in either direction triggers the bug)
3. Paste a link onto the selection that is on the clipboard already
4. Hit right arrow key
5. Text is deselected and the cursor is positioned at the **beginning** of the selection

**Expected behavior**
Cursor goes to the end of the selection

**Screenshots**
link-selection-bug

**Desktop (please complete the following information):**
 - Win 10
 - Firefox 63
 - WP 5.0-beta1-43823, Twenty Nineteen, no plugins

### LINKED ISSUE #11276: Inline code with backticks stays within the code tag when closing
**Describe the bug**
Adding inline code tags using the backtick shortcuts keeps the cursor within the code formatting and forces you to navigate out of it to write normal text. 

**To Reproduce**
1. Type a backtick in a paragraph block (`)
2. Write some "code"
3. Add another backtick to close the inline code formatting
4. Continue typing. The cursor is still inside the code formatting and it shouldn't be

**Expected behavior**
After the backtick that closes the code tag is added, the cursor should automatically be outside the code tag as it is in the classic editor

**Screencast**
https://youtu.be/-pAGqeNckf8

**Additional context**
- Gutenberg 4.1.1

### LINKED ISSUE #11423: Part of the word in italic covers partly letter next to it when the caret is active inside the inline boundary
**Describe the bug**
Doing some of the word in italic covers over the letters beside it.

**To Reproduce**
1. Do part of the word italic and the letter beside it will perhaps also be partly covered.

**Expected behavior**
Not to cover the letter beside that is not italic

**Screenshots**
screen shot 2018-11-02 at 17 25 02

**Desktop (please complete the following information):**
 - OS: Mac os 10.13.6
 - Browser Chrome with Desktop Server
 - Gutenberg version 4.1.1

### LINKED ISSUE #11741: Can't Select Bold/Italic and Type with Format from Start of List Item
**Describe the bug**
It's current impossible to select an inline format (bold and italic tests) from the start of any list item (empty or not) except the first and then type with that format.

**To Reproduce**
1. Make a list block.
1. Type in the first item
1. Start a second list item
1. Click the "Bold" format or press `CTRL` + `B` (also works for Italic button / `CTRL` + `I`)
1. Type

**Result:** Text is unformatted (not bold in this example).

**Expected behavior**
I should be able to format the beginning of a list item. This is common especially for a pattern like this:

- **Topic 1:** This is the first topic.
- **Topic 2:** This is different from the first topic.

**Screenshots**
demonstrating the steps to reproduce above

**Desktop (please complete the following information):**
Win 10, Firefox 63 and Chrome 70, WP 5.0-beta3, no plugins, Twenty Nineteen

### LINKED ISSUE #11812: (Firefox) Misplaced caret when selecting a RichText element
## Describe the bug

Caret is erroneously positioned at the start of a RichText element when selecting a block in Firefox.

## To Reproduce

1. Start with a post (I'm using a [sizable post provided here](https://github.com/WordPress/gutenberg/issues/10418#issuecomment-436431030)).
2. Make sure no blocks are selected.
3. Click on the end of a textful RichText element, or click in the middle of the text.
4. **Observed:** Caret is positioned at the start of the element.

## Expected behavior

Caret should be placed where I clicked.

## Screenshots

richtext-caret-firefox

## Desktop (please complete the following information):

 - OS: macOS
 - Browser: Firefox Developer Edition

### LINKED ISSUE #12529: Space after italics gets deleted when using keyboard shortcut
**Describe the Bug**
When writing, if you use keyboard shortcut for italics (or bold), then hit space before un-italicizing, the space gets deleted when you un-italicize, and any further typing gets italicized and combined to the previous word.

**Steps to reproduce the behavior:**
1. Start typing in a text block
2. Use keyboard shortcut to switch to italics (cmd+i)
3. Type italicized word, then a space
4. Use keyboard shortcut to cancel italics (cmd+i)
5. Type the next word in sentence.

**Expected behavior**
Ideally, the editor would put a closing </em> tag on the last character before the space, and allow you to keep typing un-italicized (or un-bolded, etc.). 

At the very least, there should be a non-breaking space after the character, then the closing </em> tag.

In either case, you would be able to continue writing un-interrupted. Right now, it requires you to use the mouse to fix, or the right arrow key, which is disruptive to the user's writing flow.

**Screenshots**
Here's a gif of a short video of the behavior: https://imgur.com/iYvzfBG

I hope it helps, because this was a weird one to describe.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.1
 - Browser: Chrome
 - Version 70.0.3538.110

**Additional context**
- Gutenberg 4.6.1
- Replicated on latest WP, as well as latest 5.0RC

### LINKED ISSUE #12973: Inline boundaries don't work properly when using multiple inline formats
**Describe the bug**

I have the following content in my post

```
<!-- wp:paragraph -->
<p><em>italic <code>code</code></em></p>
<!-- /wp:paragraph -->
```

Notice that it's impossible to move the caret after the `code` element, but before still inside the `em` to continue typing italic text.

**Expected behavior**
I expected the first right arrow key presse to go out of the code element but stay inside the `em` and the second one to go out of the `em`

### LINKED ISSUE #12978: Flashing background when typing inside an inline text boundaries
**To Reproduce**
1. Create a post with the following content

```
<!-- wp:paragraph -->
<p>some <em>italic</em> text</p>
<!-- /wp:paragraph -->
```

2. Put the caret inside the "italic" text
3. Start typing
4. Notice that the background of the inline boundaries is flashing

flash

### LINKED ISSUE #13153: Cannot reach some text positions in nested formatting
**Describe the bug**
When nesting formatting, it can be difficult to select which text section we want to edit. In the following example I want to add a space on the italicized text rather than the `<em>`. I'm incapable of doing so, and would need to add a space after the `i` in `is` then delete text.

nested formatting

**To Reproduce**
1. Start a new post in the block editor.
2. Add text to a paragraph block containing "This is italicized" and add italicized formatting to the section
3. After the word "This", add more text "is a code block", then select that section and add backticks to trigger `<em>` formatting
4. Try to add a space to the start of "is" in the italicized section instead of the codeblock. 

**Expected behavior**
I can add a space before `is` that is italicized. Right now I can only do that in the code block, or one character after the italicized section begins.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 71.0.3578.98

**Additional context**
- WP 5.0.2

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

This PR adds boundary logic to the Rich Text package. Every format will now have boundaries, not just some registered element tags.

Fixes 10 known bugs: closes #13153, closes #12973, closes #12978, closes #11091, closes #11178, closes #11276, closes #12529, closes #11741, closes #11423, closes #11812.

## How has this been tested?

See e2e.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by iseulde** [comment]
At the moment there are only two e2e test suite failures: annotations and navigable toolbar. No idea yet what has changed that causes this.

File: packages/dom/src/dom.js [hunk 1]
```diff
@@ -130,14 +130,21 @@ export function isHorizontalEdge( container, isReverse ) {
 	// If confirmed to be at extent, traverse up through DOM, verifying that
 	// the node is at first or last child for reverse or forward respectively.
 	// Continue until container is reached.
-	const order = isReverse ? 'first' : 'last';
+	const order = isReverse ? 'previous' : 'next';
```
[the remark this answers is not in the document]
Comment (iseulde) [reply packages/dom/src/dom.js]: I'll have a look into them. Selection set by rich text is purely done with text nodes, so sometimes we need these trailing text nodes. I can see if we con do it without them.

File: packages/e2e-test-utils/src/get-edited-post-content.js [hunk 2]
```diff
@@ -1,25 +1,10 @@
...
-	const content = await page.evaluate( () => {
-		const { select } = window.wp.data;
-		return select( 'core/editor' ).getEditedPostContent();
+	return await page.evaluate( () => {
+		return window.wp.data.select( 'core/editor' ).getEditedPostContent();
 	} );
-
-	// Globally guard against zero-width characters.
-	if ( REGEXP_ZWSP.test( content ) ) {
-		throw new Error( 'Unexpected zero-width space character in editor content.' );
```
[the remark this answers is not in the document]
Comment (iseulde) [reply packages/e2e-test-utils/src/get-edited-post-content.js]: Because neither TinyMCE nor we ever insert them. What's the point in keeping it?

File: packages/e2e-tests/specs/__snapshots__/undo.test.js.snap [hunk 3]
```diff
@@ -28,7 +28,7 @@ exports[`undo should undo typing after a pause 2`] = `
 
 exports[`undo should undo typing after non input change 1`] = `
 "<!-- wp:paragraph -->
-<p>before keyboard <strong>after keyboard</strong></p>
+<p>before keyboard <strong>after keyboard</strong></p>
```
[the remark this answers is not in the document]
Comment (iseulde) [reply packages/e2e-tests/specs/__snapshots__/undo.test.js.snap]: Yes :) One that TinyMCE no longer inserts.

File: packages/dom/src/dom.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (iseulde) [reply packages/dom/src/dom.js]: Just noting, this is a workaround for a browser bug. Selection can never be set to the empty text node by arrow nav, so you can never reach the end.

File: packages/e2e-test-utils/src/get-edited-post-content.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (aduth) [reply packages/e2e-test-utils/src/get-edited-post-content.js]: Well, TinyMCE did. But you're right, there's nothing as of this pull request which could ever conceivably result in the ZWSP being inserted.

[the remark this answers is not in the document]
Comment (iseulde) [reply packages/e2e-test-utils/src/get-edited-post-content.js]: I've not ever seen a browser inserting them, so I think it's ok. I also removed all our use of the character.

**Comment by hypest** [comment]
cc @Tug in case this is in any way interesting for the gutenberg-mobile side of things.

**Comment by youknowriad** [comment]
@iseulde Nice to see the e2e tests passing and more red than green.

**Comment by youknowriad** [comment]
Small bug I noticed:

Hit Block (or any format in the toolbar). I expected the caret to stay in its position so I can continue to write, instead the focus was lost.

**Comment by youknowriad** [comment]
It's working fairly well in general. What should we do about the inline image resizing? Should we work on it separately, do you think it's ok to "lose" this for now?

Also, let's get this PR tested and reviewed properly, it's a huge improvement in terms of formats. cc @WordPress/gutenberg-core (See the list of bug fixes by this :) )

**Comment by iseulde** [comment]
> What should we do about the inline image resizing? Should we work on it separately, do you think it's ok to "lose" this for now?

@youknowriad I'm working on a PR right now for it.

**Comment by youknowriad** [comment]
I notice this changes the styles of the list block (the margin is not the same as master), I guess it was not intentional?

**Comment by jasmussen** [comment]
Any list item changes COULD be because the list block was changed recently in master: https://github.com/WordPress/gutenberg/pull/12941

**Comment by iseulde** [comment]
Thanks @youknowriad, I'll check the block styles for the changed class in this PR and try to reduce the use of it.

**Comment by iseulde** [comment]
The image stuff is a fairly simple and more hidden feature, so I think it's ok as long as we have it in before a release.

**Comment by iseulde** [comment]
> Hit Block (or any format in the toolbar). I expected the caret to stay in its position so I can continue to write, instead the focus was lost.

@youknowriad Ah I see what you mean. Did that work before? I've always tested that with the keyboard shortcuts. :) I'll see if I can add an e2e test.

File: packages/block-library/src/cover/editor.scss [hunk 4]
```diff
@@ -1,13 +1,6 @@
 .wp-block-cover-image,
 .wp-block-cover {
-	.editor-rich-text__tinymce[data-is-empty="true"]::before {
```
Comment (iseulde) [inline packages/block-library/src/cover/editor.scss]: `data-is-empty` was removed in #1485 (thanks @aduth), so I'm removing the styles as they're most likely very outdated and haven't worked in 1.5 years.

**Comment by iseulde** [comment]
@youknowriad I fixed the format button issue and the block CSS issues. Worth noting that with the latest default theme, the bullets _are_ designed to be out of the box though.

**Comment by youknowriad** [comment]
Nice :)

> Worth noting that with the latest default theme, the bullets _are_ designed to be out of the box though.

I guess the issue was in master then :) 

---
I'll give it a try in a few minutes.

**Comment by iseulde** [comment]
Found another issue this PR fixes: #12529.

**Comment by iseulde** [comment]
Another one: #11741. So we're at 8 issues.

**Comment by iseulde** [comment]
A smaller styling issue that I fixed while working on this: #11423.

**Comment by iseulde** [comment]
And, correct me if I'm wrong, but this also fixes #11812 for me. Perhaps TinyMCE interfering with something.

File: packages/block-library/src/heading/editor.scss [hunk 5]
```diff
@@ -35,13 +35,13 @@
 	}
 
 	// Adjust line spacing for larger headings.
-	h1.editor-rich-text__tinymce,
-	h2.editor-rich-text__tinymce,
-	h3.editor-rich-text__tinymce {
```
Comment (youknowriad) [inline packages/block-library/src/heading/editor.scss]: I love these removals but I think this is also something we should document in the release... as some themes might have relied on these tinymce classNames. Granted that the components classNames should not be considered public API.

Comment (youknowriad) [reply packages/block-library/src/heading/editor.scss]: We should also drop a note to the themes/design team once this lands to check the twenty* themes.

File: packages/editor/src/components/rich-text/editable.js [hunk 6]
```diff
@@ -0,0 +1,199 @@
...
+const { userAgent } = window.navigator;
+
+/**
+ * Applies a fix that provides `input` events for contenteditable in Internet Explorer.
+ *
+ * @param {Element} editorNode The root editor node.
+ *
+ * @return {Function} A function to remove the fix (for cleanup).
+ */
+function applyInternetExplorerInputFix( editorNode ) {
```
Comment (youknowriad) [inline packages/editor/src/components/rich-text/editable.js]: Is this something that was done by TinyMCE, is this the only browser quirk done by TinyMCE?

File: packages/editor/src/components/rich-text/editable.js [hunk 7]
```diff
@@ -0,0 +1,199 @@
...
+const CLASS_NAME = 'editor-rich-text__editable';
+
+/**
+ * Whether or not the user agent is Internet Explorer.
+ *
+ * @type {boolean}
+ */
+const IS_IE = userAgent.indexOf( 'Trident' ) >= 0;
+
+export default class Editable extends Component {
```
Comment (youknowriad) [inline packages/editor/src/components/rich-text/editable.js]: Having a hard time understanding how do we decide what belongs in this class which I believe is the replacement for the TinyMCE component and what belongs in RichText. The line is very blury right now. I do see a need for splitting to keep the code contained. 

It doesn't need an immediate resolution but maybe there are better ways to split the RichText component.

**Review by youknowriad — COMMENTED** [review]
This is looking very good. To steel from @jasmussen this deservers a 🏅 

I left some comments, mostly questions. I think it's very close. I'd appreciate some design checks for the different blocks.

File: packages/block-library/src/heading/editor.scss (hunk 5 above)
Comment (iseulde) [reply packages/block-library/src/heading/editor.scss]: Yes. We should really discourage the use of these classes. The only reasonable uses I've seen is to style the placeholder or boundaries differently. Ideally the default styles should work for anything though. Worth looking into at some point.

File: packages/editor/src/components/rich-text/editable.js (hunk 6 above)
Comment (iseulde) [reply packages/editor/src/components/rich-text/editable.js]: No this isn't something that was done by TinyMCE. This code is currently in master too. It's to fix the `input` event for IE11. Original code was added by @brandonpayton I believe.

File: packages/editor/src/components/rich-text/editable.js (hunk 7 above)
Comment (iseulde) [reply packages/editor/src/components/rich-text/editable.js]: I see this component as just an enhanced `contenteditable` element, that's why I called it editable. The main things it does is preventing React from rerendering it and applying some browser specific fixes.

Comment (iseulde) [reply packages/editor/src/components/rich-text/editable.js]: One of my next PRs will be to use React to render the children of this component. Then we can get rid of the custom attribute diffing and `shouldComponentUpdate`.

Comment (iseulde) [reply packages/editor/src/components/rich-text/editable.js]: So eventually I think this class will be reduced to nothing.

**Comment by youknowriad** [comment]
@kjellr @jasmussen anyone have some time to test the impact of this PR on the block styles in several themes?

**Comment by iseulde** [comment]
@youknowriad It looks like there's only one rule, which doesn't even work because `data-is-empty` has been gone for 1.5 years. 

https://github.com/WordPress/twentynineteen/blob/e74d348ab9cfc6ad46bdf33f691611930c39e944/style-editor.scss#L470

**Comment by youknowriad** [comment]
I'm more concerned about the `.editor-rich-text__tinymce` change.

**Comment by iseulde** [comment]
@youknowriad Yes, that is what I meant. There's only one use of `.editor-rich-text__tinymce`, which is in combination with `data-is-empty`, so the rule doesn't work.

**Comment by youknowriad** [comment]
Themes could have relied on `editor-rich-text__tinymce` to override the heading styles...

**Comment by iseulde** [comment]
I don't see a mention of `.editor-rich-text__tinymce` for headings. In fact, it's good to lower the specificity, so if any theme were to use the class (which is no more), the specificity would be the same again.

https://github.com/WordPress/twentynineteen/search?q=tinymce&unscoped_q=tinymce

**Comment by youknowriad** [comment]
@iseulde I agree lower specificity is better and I don't think we should change anything in this PR here. But if we look at this change for instance https://github.com/WordPress/gutenberg/pull/13697/files#diff-fa79e5f8e65d45695ed24f6c773a80cbL38

It means that previous to this PR, the themes should have used `.editor-rich-text__tinymce` to override the styles, otherwise the headings default styles were more specific. So I'm interested in testing this PR on these themes and see which ones needs to be updated.

**Review by youknowriad — COMMENTED** [review]
Should we add changelog entries?

**Comment by iseulde** [comment]
For the classes? Or what do you have in mind?

**Comment by youknowriad** [comment]
For the modified packages. In theory every PR should add something. Just some small items like:

"Refactor boundaries to fix multiple format issues, ..." 

whatever you think is best.

https://github.com/WordPress/gutenberg/blob/master/packages/README.md#maintaining-changelogs

**Comment by iseulde** [comment]
Something like this?

File: packages/dom/CHANGELOG.md [hunk 8]
```diff
@@ -1,3 +1,7 @@
+## 2.0.9 (Unreleased)
+
+- Update `isHorizontalEdge` to account for empty text nodes.
```
Comment (youknowriad) [inline packages/dom/CHANGELOG.md]: I think this is missing headings. `### Enhancement`...

Comment (iseulde) [reply packages/dom/CHANGELOG.md]: Sorry, I followed previous formatting. I'll adjust

**Review by youknowriad — APPROVED** [review]
Awesome work. This PR is big and may require a second review but I love it. So many bug fixes at once.

**Comment by iseulde** [comment]
Thanks @youknowriad! I'll wait a bit so there's time  if someone else wants to have a look.

File: packages/dom/src/dom.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (iseulde) [reply packages/dom/src/dom.js]: As this is technically a bug in master as well (the empty text nodes have been there for a while) and it would require changes to selection setting, I think it would be better to look into separately. I don't think adjusting selection setting will be trivial.

In any case, this seems like good behaviour to add to me. Visually the caret is at the end, so the it's at the horizontal edge.

File: docs/designers-developers/faq.md [hunk 9]
```diff
@@ -241,7 +241,7 @@ Here is a brief animation illustrating how to find and use the keyboard shortcut
 
 ## Is Gutenberg built on top of TinyMCE?
 
-No. [TinyMCE](https://www.tinymce.com/) is one of the best tools for enabling rich text on the web. In Gutenberg, TinyMCE does exactly that. Nearly every text field you'll find is augmented with TinyMCE for rich text. Whether it be text, lists, or even just a single caption, TinyMCE can be invoked on blocks for rich text enhancements.
```
Comment (aduth) [inline docs/designers-developers/faq.md]: Another reference worth updating:

https://github.com/WordPress/gutenberg/blob/b488d83b9f0863d01be4b6c558e23506a6f87a4d/docs/designers-developers/developers/tutorials/block-tutorial/introducing-attributes-and-editable-fields.md#L121

File: packages/e2e-tests/specs/writing-flow.test.js [hunk 10]
```diff
@@ -141,6 +142,42 @@ describe( 'adding blocks', () => {
...
+		await page.keyboard.type( 'h' );
+		await page.keyboard.press( 'ArrowRight' );
+		await page.keyboard.type( 'i' );
+		await page.keyboard.press( 'ArrowRight' );
+		await page.keyboard.type( 'j' );
+
+		expect( await getEditedPostContent() ).toMatchSnapshot();
+	} );
+
 	it( 'should clean TinyMCE content', async () => {
```
Comment (aduth) [inline packages/e2e-tests/specs/writing-flow.test.js]: This test case seems unnecessary now.

Also consider some comment updates to:

- https://github.com/WordPress/gutenberg/blob/b488d83b9f0863d01be4b6c558e23506a6f87a4d/packages/e2e-tests/specs/splitting-merging.test.js#L142
- https://github.com/WordPress/gutenberg/blob/b488d83b9f0863d01be4b6c558e23506a6f87a4d/packages/e2e-tests/specs/writing-flow.test.js#L94-L106

File: packages/editor/src/components/rich-text/index.js [hunk 11]
```diff
@@ -415,13 +449,14 @@ export class RichText extends Component {
...
+		this.formatPlaceholder = formatPlaceholder;
 		this.onChangeEditableValue( record );
 
 		this.savedContent = this.valueToFormat( record );
 		this.props.onChange( this.savedContent );
-		this.setState( { start, end } );
+		this.setState( { start, end, selectedFormat } );
 
 		if ( ! withoutHistory ) {
 			this.onCreateUndoLevel();
```
Comment (aduth) [inline packages/editor/src/components/rich-text/index.js]: Further down, a comment which could use updates:

https://github.com/WordPress/gutenberg/blob/b488d83b9f0863d01be4b6c558e23506a6f87a4d/packages/editor/src/components/rich-text/index.js#L501-L502

File: packages/e2e-tests/specs/writing-flow.test.js (hunk 10 above)
Comment (aduth) [reply packages/e2e-tests/specs/writing-flow.test.js]: In the WritingFlow component itself, I wonder about the relevance of these comments, and whether there's any need for implementation updates:

https://github.com/WordPress/gutenberg/blob/b488d83b9f0863d01be4b6c558e23506a6f87a4d/packages/editor/src/components/writing-flow/index.js#L240

https://github.com/WordPress/gutenberg/blob/b488d83b9f0863d01be4b6c558e23506a6f87a4d/packages/editor/src/components/writing-flow/index.js#L248-L255

https://github.com/WordPress/gutenberg/blob/b488d83b9f0863d01be4b6c558e23506a6f87a4d/packages/editor/src/components/writing-flow/index.js#L265-L269

**Comment by aduth** [comment]
One thing I notice is that when clicking into an inline boundary, and then into some other paragraph / field, the inline boundary from the first click lingers. This doesn't happen in the current plugin release.

File: packages/dom/src/dom.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (aduth) [reply packages/dom/src/dom.js]: We should still update the comment then, to explain the exceptions we're considering. Right now, the comment doesn't reflect reality.

>verifying that the node is at first or last child for reverse or forward respectively.

File: packages/e2e-tests/specs/rich-text.test.js [hunk 12]
```diff
@@ -57,6 +62,21 @@ describe( 'RichText', () => {
...
 	} );
 
+	it( 'should return focus when pressing formatting button', async () => {
+		await clickBlockAppender();
+		await page.keyboard.type( 'Some ' );
+		// Sets isTyping to false.
+		await moveMouse();
+		await page.click( '[aria-label="Bold"]' );
+		await page.keyboard.type( 'bold' );
+		// Sets isTyping to false.
```
Comment (aduth) [inline packages/e2e-tests/specs/rich-text.test.js]: We should do `page.keyboard.press( 'Escape' )` instead. It should work just as well, and is simpler than imitating some "shake the mouse" interaction.

File: packages/e2e-tests/specs/writing-flow.test.js [hunk 13]
```diff
@@ -141,6 +142,42 @@ describe( 'adding blocks', () => {
...
 	} );
 
+	it( 'should navigate around nested inline boundaries', async () => {
+		await setPostContent( `
+			<!-- wp:paragraph -->
+			<p><strong><em>1</em> <em>2</em></strong></p>
+			<!-- /wp:paragraph -->
+		` );
+
+		await page.click( '[data-type="core/paragraph"] [contenteditable]' );
```
Comment (aduth) [inline packages/e2e-tests/specs/writing-flow.test.js]: The way we enter this paragraph and assume some caret position seems fragile to me. What guarantee do we have that the click here occurs at some specific reliable point? 

I'd wonder if instead we could do one of:

- Craft the content manually before running your test interactions
- Otherwise ensure we're where we want to be in the text field (press "End" maybe if we're trying to go to the end of the field?)

File: packages/editor/src/components/rich-text/style.scss [hunk 14]
```diff
@@ -48,54 +48,29 @@
 		}
 	}
 
-	// Style TinyMCE inline boundaries on select inline text elements.
-	&:focus {
```
Comment (iseulde) [inline packages/editor/src/components/rich-text/style.scss]: @aduth That's true (re: boundaries don't disappear). This reason seems to be that I removed `:focus` here.

Comment (iseulde) [reply packages/editor/src/components/rich-text/style.scss]: Ideally we should remove the selection state, but maybe better to look at it separately.

Comment (iseulde) [reply packages/editor/src/components/rich-text/style.scss]: Restored.

File: packages/rich-text/src/to-tree.js [hunk 15]
```diff
@@ -2,24 +2,34 @@
...
+import { getActiveFormats } from './get-active-formats';
 import { getFormatType } from './get-format-type';
 import {
 	LINE_SEPARATOR,
 	OBJECT_REPLACEMENT_CHARACTER,
-	ZERO_WIDTH_NO_BREAK_SPACE,
 } from './special-characters';
 
-function fromFormat( { type, attributes, unregisteredAttributes, object } ) {
+function fromFormat( { type, attributes, unregisteredAttributes, object, boundaryClass } ) {
```
Comment (aduth) [inline packages/rich-text/src/to-tree.js]: Documenting even the internal functions can be helpful, as it wasn't obvious to me that `boundaryClass` is a boolean indicating that the specific `data-rich-text-format-boundary` class should be applied, rather than the classname itself (string) we want to apply.

**Review by aduth — COMMENTED** [review]
This feels pretty great. Awesome work 👍

File: docs/designers-developers/faq.md (hunk 9 above)
Comment (iseulde) [reply docs/designers-developers/faq.md]: Oh, not sure why searching for `TinyMCE` didn't catch this. Must have overlooked. :)

File: packages/e2e-tests/specs/writing-flow.test.js (hunk 10 above)
Comment (iseulde) [reply packages/e2e-tests/specs/writing-flow.test.js]: Yeah, I'll have a look through these.

File: packages/e2e-tests/specs/rich-text.test.js (hunk 12 above)
Comment (iseulde) [reply packages/e2e-tests/specs/rich-text.test.js]: Oh, thanks, didn't realise.

File: packages/e2e-tests/specs/writing-flow.test.js (hunk 13 above)
Comment (iseulde) [reply packages/e2e-tests/specs/writing-flow.test.js]: Done :)

**Comment by iseulde** [comment]
@aduth Thanks! I addressed all your feedback.

File: packages/editor/src/components/writing-flow/index.js [hunk 16]
```diff
@@ -262,7 +263,7 @@ class WritingFlow extends Component {
 			return;
 		}
 
-		// Abort if navigation has already been handled (e.g. TinyMCE inline
+		// Abort if navigation has already been handled (e.g. RichText inline
```
Comment (aduth) [inline packages/editor/src/components/writing-flow/index.js]: We changed the name, but... do the rich text boundaries even cause `preventDefault` to be called? This seems like it was oriented to very specifically handle a TinyMCE behavior which may not apply any longer.

The same applies for the previous changes around handling Cmd+A . This would have been handled internally by TinyMCE, which as best I can tell is what prompted the workaround to be implemented.

Could either or both of these be removed now?

Comment (iseulde) [reply packages/editor/src/components/writing-flow/index.js]: Yes, we're still prevent defaulting on left/right arrow keys. I quickly tested if it would work without the check, but it doesn't. With cmd+a it's actually not TinyMCE but the browser.

Comment (iseulde) [reply packages/editor/src/components/writing-flow/index.js]: https://github.com/WordPress/gutenberg/pull/13697/files#diff-e373e566d15f8f4196eb0b3998adbdd7R660

Comment (iseulde) [reply packages/editor/src/components/writing-flow/index.js]: This makes sense to me, because when you're at a horizontal edge of the DOM, it doesn't necessarily mean that you're at the edge of the boundary. E.g. `<p><strong>|text<strong><p>`: | is not at the edge, but it is at the edge of the DOM. That's why we have to look at `preventDefault`.

Comment (aduth) [reply packages/editor/src/components/writing-flow/index.js]: Okay, I'm convinced 😃

**Review by aduth — APPROVED** [review]

**Comment by iseulde** [comment]
🎉

**Comment by youknowriad** [comment]
🎉 Nice combo issue closing

**Comment by mcsf** [comment]
Awesome!
