### PR TITLE
Fix Nav Submenu block Link UI text control

### LINKED ISSUE #46206: Nav Submenu block Link UI text control
I noticed that Submenu block's dont' seem to activate the `Text` control portion of the Link UI. This should be achievable by passing in the `hasTextControl` prop to `<LinkControl>` and also ensuring the `label` prop is set on the the link `value` that is passed to `<LinkControl>`. 

The `core/navigation-link` block does this.

### PR DESCRIPTION
**Pull request by ajlende**
## What?

Adds the text control to the navigation submenu link ui to match the normal navigation link ui.

## Why?

Fixes #46206

## How?

Adds the `hasTextControl` prop to the `<LinkControl>` component.

## Testing Instructions

1. Add a _submenu_ to the navigation
2. Edit the link
3. See the Text control in the UI

### Before

before submenu link ui

### After

after submenu link ui

### CODE REVIEW

File: packages/block-library/src/navigation-submenu/edit.js [hunk 1]
```diff
@@ -284,6 +284,7 @@ export default function NavigationSubmenuEdit( {
 	const { label, type, opensInNewTab, url, description, rel, title, kind } =
 		attributes;
 	const link = {
+		title: label,
```
Comment (getdave) [inline packages/block-library/src/navigation-submenu/edit.js]: I think this will need to be stripped of HTML before it's provided. We have ~`escapeHTML`~ `stripHTML` from `@wordpresss/dom` for this.

In the longer run we can normalize all this code with the `LinkUI` component from `core/navigation-link`.

Comment (getdave) [reply packages/block-library/src/navigation-submenu/edit.js]:
```suggestion
		title: label && stripHTML( label ),
```

Sorry I meant `stripHTML`.

**Review by getdave — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/444434/205139070-7e11929a-e56b-43b5-bf35-647cf4705765.mov

Thanks for solving this one. We just need to strip the HTML as shown in this video.

That functionality isn't a default part of link control because not all values that are passed in are HTML but maybe it should be...?

**Comment by ajlende** [comment]
> That functionality isn't a default part of link control because not all values that are passed in are HTML but maybe it should be...?

I feel like it should be. I'll open up a follow-up to this PR to tackle that though. For now I've done the same thing as in `LinkUI` from from the regular nav link.

UPDATE: Added in https://github.com/WordPress/gutenberg/pull/46263

**Review by scruffian — APPROVED** [review]
LGTM

**Review by getdave — APPROVED** [review]
