### PR TITLE
ContrastChecker: Fix check for button block colors

### LINKED ISSUE #39226: Buttons: No color contrast warning, regardless of chosen colors
### Description

On the Button block, you can set a text & link color. Regardless of the colors chosen, then contrast warning does not appear. This seems to be because [the node used in `ColorPanel`](https://github.com/WordPress/gutenberg/blob/24ece160bb46453ea7e0d6a523d3c3052746a5c9/packages/block-editor/src/hooks/color-panel.js#L27) to get the color data is getting `.wp-block-button`, when the colors are actually applied to the child div `.wp-block-button__link`. So it's never getting the set colors, just whatever happens to be set on the container element.

### Step-by-step reproduction instructions

1. Add a Buttons block
2. Select the Button
3. In the sidebar, edit the text & background colors
4. No color combo, even using the same color for both, will show the contrast warning

Doing the same with a paragraph block shows the contrast warning.

### Screenshots, screen recording, code snippet

The contrast warning shows correctly on Paragraphs, but not on Buttons:

| Paragraph | Button |
| -----------|--------|
|  |  |

### Environment info

- WordPress 5.9.1
- Gutenberg 12.7.0 (also reproduced on GB trunk, core without Gutenberg, and in GB 11.9.0, trying to see when this was introduced)
- MacOS, Chrome & Firefox

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #68853: Add basic e2e test for the most `ContrastChecker` simple cases
### Description

After https://github.com/WordPress/gutenberg/pull/68799 it would be nice to add at least one e2e test to make sure the `ContrastChecker` detects and checks colors reliably for the most simple case:
- Add a paragraph with some content.
- Set both background and text colors to black.
- Test that the `ContrastChecker` notice appears in the block settings panel _immediately_ as soon as the low-contrast color pair is applied.

For the future, it would be nice to expand the `ContrastChecker` tests when other pending issues will ne solved, they are tracked at https://github.com/WordPress/gutenberg/issues/60824

### Step-by-step reproduction instructions

N/A

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by juanfra**
## What?

Closes: https://github.com/WordPress/gutenberg/issues/39226
Closes: #68856
Closes: https://github.com/WordPress/gutenberg/issues/68853
Closes: https://github.com/WordPress/gutenberg/pull/71272
Follow-up to https://github.com/WordPress/gutenberg/issues/67035

The contrast checker wasn’t working for buttons, since their colors are applied to a different DOM element.

## Why?

Without this fix, the contrast checker didn’t display warnings when button text and background colors had poor readability.

## How?

For blocks where the root element is defined, use that element to retrieve colors for the contrast check.

## Testing Instructions

1. Create a page.
2. Add a Button block.
3. Change the button’s text and background colors.
4. Confirm that a contrast notice appears when using low-contrast color combinations.
5. Test with other blocks (paragraph, columns, etc.) and confirm they still behave as expected.

## Screenshots or screencast 

https://github.com/user-attachments/assets/2afd6c54-6566-4cd5-b03c-af152fac1f46

### CODE REVIEW

**Comment by Mamaduka** [comment]
Thanks, @juanfra!

There's a WIP PR for the same problem - #71272. You can see the feedback there for some of the challenges for this fix.

**Comment by juanfra** [comment]
Thanks, @Mamaduka! 🙏 Sorry I missed the other PR and the related issue, my bad.

I’ve gone through the feedback there and just pushed some changes that (hopefully) address the concerns.

File: packages/block-editor/src/hooks/contrast-checker.js [hunk 1]
```diff
@@ -2,32 +2,52 @@
...
+import { useSelect } from '@wordpress/data';
 
 /**
  * Internal dependencies
  */
 import ContrastChecker from '../components/contrast-checker';
 import { useBlockElement } from '../components/block-list/use-block-props/use-block-refs';
+import { store as blockEditorStore } from '../store';
+import { store as blocksStore } from '@wordpress/blocks';
+import { getBlockCSSSelector } from '../components/global-styles/get-block-css-selector';
```
Comment (Mamaduka) [inline packages/block-editor/src/hooks/contrast-checker.js]: It looks like this method no longer exists, since - #72464. Haven't tested, but I think we can replace it withthe  following:

```js
import { getBlockSelector } from '@wordpress/global-styles-engine';
```

File: packages/block-editor/src/hooks/contrast-checker.js [hunk 2]
```diff
@@ -65,15 +85,25 @@ export default function BlockColorContrastChecker( { clientId } ) {
...
 
+	// Get the block type for selector resolution.
+	const blockType = useSelect(
+		( select ) => {
+			const blockName =
+				select( blockEditorStore ).getBlockName( clientId );
+			return select( blocksStore ).getBlockType( blockName );
+		},
+		[ clientId ]
+	);
```
Comment (Mamaduka) [inline packages/block-editor/src/hooks/contrast-checker.js]: We could pass the `name` block alongside the `clientId` as a prop to simplify the selector. One store subscription vs two very active ones.

File: packages/block-editor/src/hooks/contrast-checker.js [hunk 3]
```diff
@@ -2,32 +2,52 @@
...
 import { useLayoutEffect, useReducer } from '@wordpress/element';
+import { useSelect } from '@wordpress/data';
 
 /**
  * Internal dependencies
  */
 import ContrastChecker from '../components/contrast-checker';
 import { useBlockElement } from '../components/block-list/use-block-props/use-block-refs';
+import { store as blockEditorStore } from '../store';
+import { store as blocksStore } from '@wordpress/blocks';
```
Comment (Mamaduka) [inline packages/block-editor/src/hooks/contrast-checker.js]: Let's group this above with other WP dependencies.

**Review by Mamaduka — COMMENTED** [review]
Thanks for refreshing the branch, @juanfra!

It looks like it needs a bit more work after the recent refactoring.

File: packages/block-editor/src/hooks/contrast-checker.js (hunk 2 above)
Comment (juanfra) [reply packages/block-editor/src/hooks/contrast-checker.js]: Good catch, thanks 🫡

Comment (juanfra) [reply packages/block-editor/src/hooks/contrast-checker.js]: I relied on the `data-type` attribute as the name wasn't accessible at this point and I don't think it's worth passing it via props if we can do it this way.

**Comment by juanfra** [comment]
Thanks for taking another look, @Mamaduka! 

I've pushed updates addressing those fixes. The rebase was mostly a sanity check after the PR had been sitting for a few months 😄

File: packages/block-editor/src/hooks/contrast-checker.js (hunk 2 above)
Comment (Mamaduka) [reply packages/block-editor/src/hooks/contrast-checker.js]: Passing down yet another prop like `name` won't make any difference and should be the preferred method, IMO. The only reason we didn't do it before was that it wasn't needed.

This is an internal component, so we also don't change any requirements.

**Comment by juanfra** [comment]
Thanks for pushing that fix @Mamaduka! Somehow the linter didn't warn me about it. I believe this is ready for a new review.

**Comment by Mamaduka** [comment]
It seems (at least in my tests) that the minor bug described in https://github.com/WordPress/gutenberg/pull/68856#issuecomment-2626709107 became more apparent with these changes.

What's odd is that I can reproduce the same problem with the Buttons block. It's only affecting text blocks in my tests.

It would be great if we could run some basic tests and try fixing the remaining bugs before we move forward with this.

## Screencast

https://github.com/user-attachments/assets/36d8ac45-d1a8-4a6f-8a96-93f9acdd9c18

**Comment by juanfra** [comment]
Thank you @Mamaduka 

I've been digging into the issue Andrea described in that comment, and I believe they're not related to the changes introduced in this PR. What I see is that the reducer stores the stale default value on the first read, and there's no mechanism to re-check once the CSS actually applies.

For the first color selection the style engine takes a bit longer to inject the CSS and the double-rAF is not enough to catch the changes. By the time we read the computed styles, they're still showing the default/inherited values. Once that gets stored, we never retry.

From what I saw and tested we have a few ways to improve this:

- We can add a delayed retry with `setTimeout`. The double-rAF handles the fast path, while a `setTimeout` catches the slow path (first color pick). This keeps the same approach as the existing code, but we'll need to set an arbitrary number for the delay and maybe we may have the same issue on slow machines.
- Another option is to use a MutationObserver on the block element and watch for class or style attribute changes. This fires exactly when the color is applied. That way we don't have to rely on an arbitrary number.

I believe the second approach is more robust, I can give it a try here or on a new PR. I tested locally and it seems to be working fine in my tests. 

The fix is adding the following after the double-rAF:

```
const observer = new window.MutationObserver( () => {
	window.requestAnimationFrame( updateColors );
} );

observer.observe( blockEl, {
	attributes: true,
	attributeFilter: [ 'class', 'style' ],
} );

return () => {
	observer.disconnect();
};
```

**Comment by Mamaduka** [comment]
@juanfra, maybe we should bring in the tests from other PR, add case for buttons and then verify latest idea with it. WDT?

**Comment by juanfra** [comment]
@Mamaduka sounds good to me 🫡

I'll push the changes, and bring the tests here.

**Comment by juanfra** [comment]
Thanks again for the earlier reviews and suggestions @Mamaduka, really appreciated! 

I’ve updated the PR and added the tests we discussed. Whenever you have a chance, would love another pass. 

Thanks :)

**Comment by Mamaduka** [comment]
Thanks for the follow-ups, @juanfra!

Have you tried adding `blockEl` and `blockType` as dependencies to the `useLayoutEffect`, then running the e2e tests?

Now, cleanup runs very often, which might be wasteful.

P.S. I'll do better testing/review early next week.

**Comment by juanfra** [comment]
Thanks @Mamaduka!

Yes, I tried this time again and [we've tried in the past](https://github.com/WordPress/gutenberg/pull/68799/changes#r1923823376). The problem is that there are a bunch of different things that can change the block color, so restricting the check to just those dependencies won't cover all the cases.

File: packages/block-editor/src/hooks/contrast-checker.js [hunk 4]
```diff
@@ -15,19 +18,35 @@ function getComputedValue( node, property ) {
...
+	const textElement = blockEl.querySelector( textSelector ) || blockEl;
+	const backgroundElement =
+		blockEl.querySelector( backgroundSelector ) || blockEl;
+	const linkElement = blockEl.querySelector( 'a' );
 
-	let backgroundColorNode = blockEl;
+	// Get computed colors from the appropriate elements
+	const textColor = getComputedValue( textElement, 'color' );
+	const linkColor =
+		linkElement && linkElement.textContent
```
Comment (Mamaduka) [inline packages/block-editor/src/hooks/contrast-checker.js:45]: We just want to check if the link has contents, not a big perf improvement, but `textContent` does trigger reflow.

File: packages/block-editor/src/hooks/contrast-checker.js [hunk 5]
```diff
@@ -61,28 +80,56 @@ function reducer( prevColors, newColors ) {
...
+	// Runs in its own effect with dependencies so the observer is only
+	// recreated when the block element or block type changes.
+	useLayoutEffect( () => {
+		if ( ! blockEl || ! blockType ) {
+			return;
+		}
+
+		const observer = new window.MutationObserver( () => {
+			setColors( getBlockElementColors( blockEl, blockType ) );
+		} );
```
Comment (Mamaduka) [inline packages/block-editor/src/hooks/contrast-checker.js:121]: This shouldn't need a double rAF hack; the mutated attributes should already be in the DOM.

**Review by Mamaduka — APPROVED** [review]
Made some minor changes. I run tests locally frequently, and they pass consistently.

Let's ensure we include folks from PRs in the props list

```js
npm run test:e2e -- test/e2e/specs/editor/various/contrast-checker.spec.js --repeat-each 20
```
