### PR TITLE
Perform a complete draft save on preview

### LINKED ISSUE #9151: Setting a featured image and clicking Preview does not show the featured image
**Describe the bug**
After you set a feature image, clicking _Preview_ does not show the feature image on the frontend. This is a very confusing experience.

**To Reproduce**
1. Create a new post
2. Insert a title or add some text
3. Using the Document sidebar, set a _Featured Image_
4. Click _Preview_ in the top right

**Expected behavior**
The selected featured image should be visible at the top of the post, but it is not.

**Screenshots**
featured-image

**Additional context**
Encountered this during user testing. Clicking _Save Draft_ before _Preview_ works as expected.

### LINKED ISSUE #12047: Perform a full save when previewing drafts
**Describe the bug**
When clicking the preview button for draft posts, Gutenberg should save all post details, including meta fields and the featured image. Currently Gutenberg performs an autosave when previewing drafts, which includes title, content and excerpt and leaves out meta and featured image information.

**To Reproduce**
1. Start a new post, add a title and a featured image and click save draft
2. Change the featured image to a new image
3. Click the preview button
4. Reload the editor screen

**Expected behavior**
At step 3 we should see the newly selected featured image in the preview - instead we see the first/saved image.
At step 3 we should see the new featured image because it was saved when previewing; instead we see the original image.

Note: this behavior matches the long established current classic editor behavior.

**Additional context**
See https://github.com/WordPress/gutenberg/pull/12037#issuecomment-439753179 which solves featured image issue for _non draft posts_
Related: #11409 (which does not resolve this issue)
Related featured image issue: #9151

### PR DESCRIPTION
**Pull request by youknowriad**
closes #12047
fixes #9151

This is a follow-up to https://github.com/WordPress/gutenberg/pull/12037#issuecomment-439753179 and it builds on top of some changes in #11409 

This PR changes the behavior of the preview button. It now performs a full draft save (on non published posts) before previewing the post. This matches Core behavior. (classic editor)

**Testing instructions**

 - Create a post
 - Set a featured image
 - Click preview
 - You should see the post with the featured image

### CODE REVIEW

File: packages/editor/src/store/reducer.js [hunk 1]
```diff
@@ -1203,13 +1203,29 @@ export function autosave( state = null, action ) {
...
+
+/**
+ * Reducer returning the poost preview link
+ *
+ * @param  {string?} state  The preview link
+ * @param  {Object} action Dispatched action.
+ *
+ * @return {string?} Updated state.
+ */
+export function previewLink( state = null, action ) {
```
Comment (youknowriad) [inline packages/editor/src/store/reducer.js]: Preview link is tracked separately as it's not directly related to autodrafts anymore.

File: packages/editor/src/store/selectors.js [hunk 2]
```diff
@@ -1532,6 +1533,23 @@ export function isPreviewingPost( state ) {
...
+ * Returns the post preview link
+ *
+ * @param {Object} state Global application state.
+ *
+ * @return {string?} Preview Link.
+ */
+export function getEditedPostPreviewLink( state ) {
+	const featuredImageId = getEditedPostAttribute( state, 'featured_media' );
+	const previewLink = state.previewLink;
+	if ( previewLink && featuredImageId ) {
```
Comment (gziolo) [inline packages/editor/src/store/selectors.js]: we should add also a unit test, can be a follow-up PR

**Comment by gziolo** [comment]
> FAIL test/e2e/specs/preview.test.js
>   ● Preview › Should open a preview window for a new post
>     expect(received).toBe(expected) // Object.is equality
>     Expected: "http://localhost:8889/?p=144&preview=true"
>     Received: "http://localhost:8889/?p=144"
>       73 | 
>       74 | 		let expectedPreviewURL = getUrl( '', `?p=${ postId }&preview=true` );
>     > 75 | 		expect( previewPage.url() ).toBe( expectedPreviewURL );
>          | 		                            ^
>       76 | 
>       77 | 		// Title in preview should match input.
>       78 | 		let previewTitle = await previewPage.$

There is one e2e test to fix and we should be good to go. In my testing, everything works as expected.

File: packages/editor/src/components/post-preview-button/index.js [hunk 3]
```diff
@@ -192,33 +195,30 @@ export default compose( [
...
 			getPostType,
 		} = select( 'core' );
 
-		let previewLink = getAutosaveAttribute( 'preview_link' );
-		const featuredImageId = getEditedPostAttribute( 'featured_media' );
-		if ( previewLink && featuredImageId ) {
-			previewLink = addQueryArgs( previewLink, { _thumbnail_id: featuredImageId } );
-		}
-
+		const previewLink = getEditedPostPreviewLink();
```
Comment (gziolo) [inline packages/editor/src/components/post-preview-button/index.js]: `previewLink` can be inlined again.

File: packages/editor/src/store/test/reducer.js [hunk 4]
```diff
@@ -2422,15 +2422,13 @@ describe( 'state', () => {
 						raw: 'The Excerpt',
 					},
 					status: 'draft',
-					preview_link: 'https://wordpress.org/?p=1&preview=true',
```
Comment (gziolo) [inline packages/editor/src/store/test/reducer.js]: It looks like this missing `preview=true` part in the e2e is expected.

Comment (youknowriad) [reply packages/editor/src/store/test/reducer.js]: It should be fixed

File: test/e2e/specs/preview.test.js [hunk 5]
```diff
@@ -97,16 +97,6 @@ describe( 'Preview', () => {
...
-		// Wait until the publish panel is closed
-		await Promise.all( [
-			editorPage.waitForFunction( () => ! document.querySelector( '.editor-post-publish-panel' ) ),
-			editorPage.click( '.editor-post-publish-panel__header button' ),
-		] );
-		expectedPreviewURL = await editorPage.$eval( '.components-notice.is-success a', ( node ) => node.href );
-
-		await editorPage.bringToFront();
-		await waitForPreviewNavigation( previewPage );
-		expect( previewPage.url() ).toBe( expectedPreviewURL );
```
Comment (youknowriad) [inline test/e2e/specs/preview.test.js]: I removed this part because in my testing even if the url is a preview url and not the final url, it works as intended.

Comment (gziolo) [reply test/e2e/specs/preview.test.js]: It works this way in classic, so maybe we should keep it with this param.

Comment (gziolo) [reply test/e2e/specs/preview.test.js]: I don't remember why this part is here, @aduth should confirm whether we can remove it. I remember that this test was very fragile in the past.

**Review by gziolo — APPROVED** [review]
It works properly in my testing. I would appreciate someone else doing a sanity check as I'm not super familiar with the preview logic. I performed my tests comparing how it works in Classic editor with what this PR proposes.

File: packages/editor/src/components/post-preview-button/index.js [hunk 6]
```diff
@@ -192,33 +195,30 @@ export default compose( [
...
 		const postType = getPostType( getEditedPostAttribute( 'type' ) );
 		return {
 			postId: getCurrentPostId(),
 			currentPostLink: getCurrentPostAttribute( 'link' ),
-			previewLink: forcePreviewLink !== undefined ? forcePreviewLink : getAutosaveAttribute( 'preview_link' ),
+			previewLink: forcePreviewLink !== undefined ? forcePreviewLink : previewLink,
 			isSaveable: isEditedPostSaveable(),
 			isAutosaveable: forceIsAutosaveable || isEditedPostAutosaveable(),
 			isViewable: get( postType, [ 'viewable' ], false ),
+			isDraft: [ 'draft', 'auto-draft' ].indexOf( getEditedPostAttribute( 'status' ) ) !== -1,
```
Comment (aduth) [inline packages/editor/src/components/post-preview-button/index.js]: Seems like a possible candidate for a selector.

File: test/e2e/specs/preview.test.js (hunk 5 above)
Comment (aduth) [reply test/e2e/specs/preview.test.js]: I think the idea was that if there is nothing to save and we have a known preview URL, we don't save, we go straight to the preview URL.

I don't know that it's necessarily breaking to let the save go through, however.
