### PR TITLE
In-editor Revisions: Update success notice message

### LINKED ISSUE #19226: Restoring a revision doesn't display a success message
**Describe the bug**

The `Post restored to revision from...` message isn't shown when restoring an older revision of a post. The message correctly appears when using the classic editor.

**To reproduce**
1. Publish a post and then make a change to it and save it.
2. Click the Revisions item in the editor sidebar.
3. Navigate to the previous revision and click `Restore This Revision`.
4. Observe that the revision was restored but there was no success message.

**Expected behavior**

The `Post restored to revision from [date]` message should appear, as it does in the classic editor. This is element with index 5 in the `post_updated_messages` array.

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes #19226.
Closes #20349.
This is a follow-up to #74771.

PR updates the revision restoration success message to match the [text used in classic views](https://github.com/WordPress/wordpress-develop/blob/81885a9ff64f3902d4f3162c011745a35b46e6ba/src/wp-admin/edit-form-advanced.php#L180).

* I've omitted the post type prefix to keep the message more general.
* The date formatting matches one used in [slider tooltips](https://github.com/WordPress/gutenberg/blob/362af57e564e88499d2d50c40a492dce21bc168a/packages/editor/src/components/post-revisions-preview/revisions-slider.js#L82).

## Testing Instructions
1. Open a post or page with revisions.
2. Open the in-editor revisions view.
3. Restore to the previous revision.
4. Confirm the new success notice message.

### Testing Instructions for Keyboard

CleanShot 2026-02-11 at 14 56 42

### CODE REVIEW

**Comment by jasmussen** [comment]
Seems good to me 👍 👍—I'll defer to the other folks pinged!

File: packages/editor/src/store/private-actions.js [hunk 1]
```diff
@@ -638,12 +639,17 @@ export const restoreRevision =
 		await dispatch.savePost();
 
 		// Show success notice.
-		registry
-			.dispatch( noticesStore )
-			.createSuccessNotice( __( 'Revision restored.' ), {
+		registry.dispatch( noticesStore ).createSuccessNotice(
+			sprintf(
+				/* translators: %s: Date and time of the revision. */
+				__( 'Restored to revision from %s.' ),
```
Comment (mcsf) [inline packages/editor/src/store/private-actions.js:645]: - Would "dated" be better than "from"? I'm undecided.
- The main difficulty here is that the date format isn't known, so we can't let translators know what to expect, and that information could influence the choice of translation. But there's not much we can do.
- The string combined with the translators note don't give translators a lot of context: what is "restored"? It's a past participle and not a simple past form. It refers to a post/page. It is a success notice. All that could be useful to understand. So, e.g., `translators: Success notice after a user has restored a post/page to a specific revision. %s: date and time of the revision.`

**Review by mcsf — APPROVED** [review]
Left suggestions, but LGTM either way!

File: packages/editor/src/store/private-actions.js (hunk 1 above)
Comment (Mamaduka) [reply packages/editor/src/store/private-actions.js:645]: The string is taken from the core and has been there for years. See: https://github.com/WordPress/wordpress-develop/blob/81885a9ff64f3902d4f3162c011745a35b46e6ba/src/wp-admin/edit-form-advanced.php#L180.

When I tried to translate this in Georgian, it worked. But it might be a different story for other languages.

cc @ocean90

Comment (Mamaduka) [reply packages/editor/src/store/private-actions.js:645]: @mcsf, should I merge since the text isn't much different from what's already used in core?

Comment (mcsf) [reply packages/editor/src/store/private-actions.js:645]: @Mamaduka: go for it :)
