### PR TITLE
Font Library: Fix modal scrollbar

### LINKED ISSUE #54401: Font Library: show the scrollbar bottom edge
image

### PR DESCRIPTION
**Pull request by mikachan**
## What?

Improves the display of the Font Library modal's scrollbar to prevent it from disappearing behind the footer.

## Why?

Fixes https://github.com/WordPress/gutenberg/issues/54401.

## How?

This adjusts the CSS of the Font Library modal's content to add a bottom margin, which means it can take into account the height of the footer when displaying the scrollbar. I've also made the footer a fixed height so that these two measurements always match.

## Testing Instructions

1. Open the Font Libary modal
2. Ensure there are enough fonts installed to increase the height of the content to cause a vertical scrollbar (add more fonts via the Install Fonts tab if necessary)
3. Scroll to the bottom of the modal content
4. Ensure that you can still see the scroll bar and its position at the bottom of the modal

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/1645628/e86d37c7-061a-42a5-b641-da9f651e918c

### CODE REVIEW

File: packages/edit-site/src/components/global-styles/font-library-modal/installed-fonts.js [hunk 1]
```diff
@@ -181,7 +181,6 @@ function InstalledFonts() {
 							) ) }
 						</>
 					) }
-					<Spacer margin={ 16 } />
```
Comment (mikachan) [inline packages/edit-site/src/components/global-styles/font-library-modal/installed-fonts.js:184]: I think this was added to create some space between the content and the footer. I don't think this is needed now that it's possible to see the bottom of the content above the footer.

File: packages/edit-site/src/components/global-styles/font-library-modal/style.scss [hunk 2]
```diff
@@ -15,6 +15,7 @@
 
 	.components-modal__content {
 		padding-top: 0;
+		margin-bottom: 70px; // This should match the height of the footer
```
Comment (creativecoder) [inline packages/edit-site/src/components/global-styles/font-library-modal/style.scss]: How about using a variable here, defined at the top of the file, so it doesn't need to be manually kept in sync?

Comment (mikachan) [reply packages/edit-site/src/components/global-styles/font-library-modal/style.scss]: Yes, nice idea! I did think about this but doubted myself 😅 Done in https://github.com/WordPress/gutenberg/pull/60641/commits/e5a985f7d5ea6eaaff3a8c47a6edb91de4f35f70.

**Review by creativecoder — APPROVED** [review]
Looks good. I can see the bottom of the font library modal scrollbar now! Tested desktop and mobile screen sizes.

File: packages/edit-site/src/components/global-styles/font-library-modal/style.scss (hunk 2 above)
Comment (t-hamano) [reply packages/edit-site/src/components/global-styles/font-library-modal/style.scss]: It is not guaranteed that the footer height will be exactly 70px. This may be because the fonts differ slightly depending on the OS. In my environment (Windows11, Chrome), the height is 68.8px.

image

If we expect the footer to have a height of 70px, I think we need to give an explicit height to the footer itself.

My other idea is to apply `position:sticky`. This approach is also used in [the data view footer](https://github.com/WordPress/gutenberg/blob/e1842bb8dadd224ccf2e7499bcff781afb9ce499/packages/dataviews/src/style.scss#L43-L45). Styles will probably look like this:

```scss
.font-library-modal__tabpanel-layout__footer {
	margin: 0 #{$grid-unit-40 * -1} #{$grid-unit-40 * -1};
	position: sticky;
	bottom: #{$grid-unit-40 * -1};
	width: auto;
}
```

This will also fix the issue where the scrollbar is hidden behind the footer.

scrollbar-overflow

What do you think?

Comment (mikachan) [reply packages/edit-site/src/components/global-styles/font-library-modal/style.scss]: >If we expect the footer to have a height of 70px, I think we need to give an explicit height to the footer itself.

We're setting the height of the footer via the class `.font-library-modal__tabpanel-layout__footer` on line 48 of style.scss. In my testing, even when changing the font size, the height remains at 70px.

image

I'm not sure why you're seeing 68.8px there, although I know that's what the height was before I set it to 70px. Could this maybe be caused by a caching issue on the CSS?

**Review by t-hamano — APPROVED** [review]
> I'm not sure why you're seeing 68.8px there, although I know that's what the height was before I set it to 70px. Could this maybe be caused by a caching issue on the CSS?

Sorry, I was debugging with trunk 😅 This PR does indeed have a footer height of 70px and is working as expected.

**Comment by matiasbenedetto** [comment]
I added the "Backport to WP Minor Release" tag to include it in WordPress 6.5.3.

**Comment by creativecoder** [comment]
Thanks @matiasbenedetto! I've added this to the 6.5.x board for consideration in the 6.5.3 release.

**Comment by creativecoder** [comment]
Confirming that [this will be included](https://wordpress.slack.com/archives/C02RQBWTW/p1714081557416189) in the 6.5.3 release.

**Comment by creativecoder** [comment]
I just cherry-picked this PR to the update/fixes-for-wp-6-5-3 branch to get it included in the next release: 25c18ac266f
