### PR TITLE
Fix allow mouse users to edit link text when Link UI is active

### LINKED ISSUE #59525: Link Control: allow double clicking to edit text of link
### Description

When you have a link inside text (paragraph, list item, etc) placing the cursor inside the link shifts focus to the popup, so your cursor leaves the paragraph text. This is new behavior in version 17.8.0 

**Proposed behavior** : The way it has worked in the past: you click inside of a link and your cursor stays, allowing you to type inside the link without having to press `esc`

### Step-by-step reproduction instructions

1. Activate Gutenberg 17.8.0
2. Hyperlink some text inside of a paragraph block. 
3. Place your cursor somewhere else, then try to place it back inside the link.
4. Note that your cursor is gone and the link is focused

### Screenshots, screen recording, code snippet

_Ignore the weirdness of where the popovers sit on the screen, that's a separate Playground issue that's been reported_

https://github.com/WordPress/gutenberg/assets/6867360/bf5288d3-4be6-49a3-a66e-a5a6f021bc99

### Environment info

- Default theme,(tested in other themes as well)
- Only occurs when 17.8.0 is active

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by getdave**
## What?

Allows for editing a link underneath popover UI when clicking on it in Rich Text. Restores this portion of the original behaviour in WP 6.4 prior (see below) to updating the UX on the Link UI.

<details>
<summary> 📹 Screencast of behaviour in WP 6.4</summary>

https://github.com/WordPress/gutenberg/assets/444434/b4cf06ff-60de-4fbc-be0a-a14f7c732c00

</details>

Alternative to https://github.com/WordPress/gutenberg/pull/59599 and https://github.com/WordPress/gutenberg/pull/59626.

Fixes https://github.com/WordPress/gutenberg/issues/59525

## Why?

Currently on `trunk` if you click a link you cannot edit the text of the link except by:

- hitting escape
- using the `Text` input within the Link UI

This is a regression on WP 6.4 and so this PR tries to solve that.

This is an alternative approach to https://github.com/WordPress/gutenberg/pull/59599 and tries to better restore the previous functionality from WP 6.4 in terms of retaining the ability to edit the link text underneath the UI when it has been clicked.

## How?

In this PR I have disabled auto focus when a user _clicks_ on a link. This means the focus is not automatically transferred to the popover and remains on the rich text until the mouse user _chooses_ to select the Link UI.

This means mouse users can edit the text _underneath_ the link popover in the same way as keyboard users.

Note that users of mice should be able to perceive that a popover has appeared and thus can use the mouse pointer to choose to edit the link via the control in popover. 

The behaviour should remain the same for keyboard users. 

I also fixed a hidden bug with `useAnchor` whereby it cannot distinguish between multiple `core/link` formats within in a content editable.

### Accessibility Checks

Note that the a11y of this PR's approach was discussed during Accessibility team office hours on WP Slack. As part of this we received the [following guidance](https://wordpress.slack.com/archives/C02RP4X03/p1709741010966669):

> For now, I’d opt for:
> Not move focus into the link UI when it opens via a mouse click
> This would have to advantages:
> Mouse users can always click again inside the popover, if their intent is to edit
> or simply continue editing the text.

This suggests that this PR does meet a11y standards because the keyboard interactions are maintained as per `trunk` but mouse users get a more intuitive experience.

## Testing Instructions

For this PR please be sure to test against `trunk` (or WP 6.5 RC) to validate any "issue" isn't something already present as intended behaviour. Link UI UX has changed a lot in WP 6.5 so it's important to validate 🙏 

- New Post
- Add a paragraph block
- Add several links to the paragraph block
- Click on each link in turn and validate that the popover moves correctly between the links, shows the correct contents and anchors correctly.
- Check that when activating a link via mouse focus is _not_ transferred to the popover and remains on rich text. Check that you can make edits to the text underneath the popover (note this is as per WP 6.4).
- Check that using a keyboard to interact with links remains as per trunk.
- Check that adding other formats within a link (e.g. bold, italic .etc) does not prevent accessing the link popover by mouse or keyboard.

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/444434/914b6144-c3ce-4bab-844a-607defb207a8

Co-authored-by: getdave <get_dave@git.wordpress.org>
Co-authored-by: jeryj <jeryj@git.wordpress.org>
Co-authored-by: draganescu <andraganescu@git.wordpress.org>
Co-authored-by: scruffian <scruffian@git.wordpress.org>
Co-authored-by: bacoords <bacoords@git.wordpress.org>
Co-authored-by: annezazu <annezazu@git.wordpress.org>
Co-authored-by: youknowriad <youknowriad@git.wordpress.org>
Co-authored-by: richtabor <richtabor@git.wordpress.org>
Co-authored-by: fabiankaegy <fabiankaegy@git.wordpress.org>

### CODE REVIEW

File: packages/format-library/src/link/inline.js [hunk 1]
```diff
@@ -245,6 +247,10 @@ function InlineLinkUI( {
 		);
 	}
 
+	if ( ! hasLink ) {
+		return null;
+	}
```
Comment (getdave) [inline packages/format-library/src/link/inline.js]: Without this there will be a flash of "Empty link" because the UI can only be closed via a "click" event on the rich text. As this click event happens on `useLayoutEffect` it will always be slightly late to hide the UI.

Comment (draganescu) [reply packages/format-library/src/link/inline.js]: Since this is the `InlineLinkUI` component this makes sense to me.

**Comment by draganescu** [comment]
For some reason checking this branch produces this result for me:


https://github.com/WordPress/gutenberg/assets/107534/d36af941-a52a-4571-8fde-76d984c349bf

**Comment by scruffian** [comment]
This breaks the CMD + K shortcut to create links (for me at least).

**Comment by getdave** [comment]
> For some reason checking this branch produces this result for me:

@draganescu Thank you for testing. Much appreciated. Could you possibly share what specifically you encountered as the issue. I tried to grok from the video but it wasn't immediately apparent 🙏 

> This breaks the CMD + K shortcut to create links (for me at least).

I re-tested found I could create links using Cmd + K. If you could share specifically what is broken I'd appreciate it? 🙏 

Update: I was using the keyboard. Using a mouse to select text and then pressing CMD+K cuases the Link UI not to appear due to empty `activeAttributes`.

**Comment by jeryj** [comment]
There is danger in making assumptions about how a user wants to interact based on how they activate the link. If I click the link and it's visible on the page, is it possible for me to enter into the link ui via the keyboard?

**Comment by bacoords** [comment]
> For some reason checking this branch produces this result for me:

> @draganescu Thank you for testing. Much appreciated. Could you possibly share what specifically you encountered as the issue. I tried to grok from the video but it wasn't immediately apparent 🙏

I can replicate the issue in that video - when you have one link selected and then select a different link in the same block, it updates the content of the popover but not the position.

**Comment by draganescu** [comment]
@getdave in my video there are two issues (Safari):

1. On first click the focus is _not_ moved to the popover
2. On clicking on another link the popover is still anchored to the 1st link

**Comment by getdave** [comment]
> 1. On first click the focus is _not_ moved to the popover

That's intentional in order to solve the Issue. By not forcing focus we can manipulate the text underneath. However the auto focus is retained for keyboard users when they initiate opening the Link UI.

> On clicking on another link the popover is still anchored to the 1st link

That's a bug. I think because something changed and now the component doesn't unmount and so doesn't find it's new position.

**Comment by getdave** [comment]
Folks - alternatively I can update this PR to retain the current focus behaviour (in `trunk`) but use the "click to toggle" UX as per the previous PR.

What we need to decide is what is best:

- don't auto focus at all for clicks and allow sighted users to edit underneath the popover.
- make clicks _toggle_ the Link UI popover and allow sighted users to learn that clicking a link twice will close the popover and allow them to edit the text.

Here is an example of ["click to toggle"](https://github.com/WordPress/gutenberg/pull/59635#pullrequestreview-1920136642) (not in this PR yet just for example purposes) which you can compare against the screencapture in the description of this PR.

https://github.com/WordPress/gutenberg/assets/444434/3d824950-065f-483a-9699-4a1cdc7a7ce5

File: packages/format-library/src/link/index.js [hunk 2]
```diff
@@ -56,10 +74,11 @@ function Edit( {
 			// to be rendered in "creating" mode. We need to check isActive to see if
 			// we have an active link format.
 			if ( event.target.tagName !== 'A' || ! isActive ) {
+				setIsEditingExistingLink( false );
 				return;
 			}
 
-			setAddingLink( true );
+			setIsEditingExistingLink( true, { shouldAutoFocus: false } );
```
Comment (getdave) [inline packages/format-library/src/link/index.js]:
```suggestion
			setIsEditingExistingLink( ( curVal ) => ! curVal, {
				shouldAutoFocus: false,
			} );
```

If we want to make this PR do the "click to toggle" behaviour we can commit this change.

**Comment by jeryj** [comment]
Found some odd bugs:

1. If you click a link, then use the arrow keys to move the caret off the link and onto another link, the popover will open again

https://github.com/WordPress/gutenberg/assets/967608/c233ddca-022f-49a5-8aad-e6692fba7453

2. The Link UI position gets "stuck" on the second clicked link

https://github.com/WordPress/gutenberg/assets/967608/20348f52-67fc-4ba9-bfe9-518802bfb0ab

File: packages/format-library/src/link/index.js [hunk 3]
```diff
@@ -157,7 +184,7 @@ function Edit( {
 				aria-haspopup="true"
 				aria-expanded={ addingLink }
 			/>
-			{ addingLink && (
+			{ ( ( addingLink && isActive ) || addingNewLink ) && (
```
Comment (jeryj) [inline packages/format-library/src/link/index.js]: addingLink || addingNewLink reads oddly. It's not clear what the difference is.

**Comment by getdave** [comment]
> 1. If you click a link, then use the arrow keys to move the caret off the link and onto another link, the popover will open again

Fixed in https://github.com/WordPress/gutenberg/pull/59635/commits/d4e68613007b3f2c47f90505f4f85f622e7c1a2d. Generally i'd consider this an anti-pattern, but here I think it's valid because the incoming state cannot be synced in any other way and is triggered by changes outside the React tree (i.e. contenteditable). Open to being told I'm wrong though.


> 2. The Link UI position gets "stuck" on the second clicked link

I've fixed this in https://github.com/WordPress/gutenberg/pull/59635/commits/f1b33eea0c631fba9239dc43a72112942b0eb4ce. I believe the current code in `trunk` has been masking an underlying issue with `useAnchor` which I've been suspicious of for some time and have tried to narrow down before.

Essentially, if you have multiple anchors within the same content editable then useAnchor has no means to distinguish between them. This is because the args provided to the `useLayoutEffect` hook within `useAnchor` do not change when you move between the anchors which means the effect doesn't re-run which means the `getAnchor` call is never triggered and thus the anchor remains on the last link.

If you're wondering why it's inconsistent then that's because of the usage of `usePrevious` within the hook to track the last `isActive` state. This _will_ change between the first and second clicks and thus the effect _will_ run. However, on subsequent clicks the `usePrevious` will return `isActive` as `true` forever more and thus the _effect_ will stop re-running.

My solution is to provide more information to disambiguate the link. I've done this by passing `activeAttributes` as a dependency because that is used by _all_ format types and not just `core/link` which means we could pull this out into a standalone fix. Moreover, by defaulting it to a stable object, it guarantees that any consumer of `useAnchor` that doesn't pass `activeAttribute` in the settings will behave "as was".


<details>
<summary>Testing overview</summary>

https://github.com/WordPress/gutenberg/assets/444434/0a5d891b-1f39-494e-b364-4098e90b6330



</details>

File: packages/format-library/src/link/index.js (hunk 3 above)
Comment (getdave) [reply packages/format-library/src/link/index.js]: Not yet 😅

Comment (getdave) [reply packages/format-library/src/link/index.js]: Now fixed.

File: packages/rich-text/src/component/use-anchor.js [hunk 4]
```diff
@@ -162,7 +169,19 @@ export function useAnchor( { editableContentElement, settings = {} } ) {
...
-	}, [ editableContentElement, tagName, className, isActive, wasActive ] );
+	}, [
+		editableContentElement,
+		tagName,
+		className,
+		isActive,
+		wasActive,
+		// Active attributes is defaulted to a stable object to avoid re-rendering,
+		// but in specific circumstances it can be used to provide additional information
+		// about the currently active format to disambiguate the anchor from other anchors
```
Comment (getdave) [inline packages/rich-text/src/component/use-anchor.js]:
```suggestion
		// about the currently active format to disambiguate the format from other instances of the same format
```

File: packages/format-library/src/link/index.js [hunk 5]
```diff
@@ -38,10 +38,38 @@ function Edit( {
 	onFocus,
 	contentRef,
 } ) {
-	const [ addingLink, setAddingLink ] = useState( false );
+	const [ editingLink, setEditingLink ] = useState( false );
+	const [ creatingLink, setCreatingLink ] = useState( false );
```
Comment (getdave) [inline packages/format-library/src/link/index.js:42]: This is the concept we've been missing.

**Comment by draganescu** [comment]
I found an edge case: if there is a format in a link format the link ui won't show on click:


https://github.com/WordPress/gutenberg/assets/107534/fc9cd00f-98f6-420f-a16d-3c4cdb74d960

**Comment by getdave** [comment]
> I found an edge case: if there is a format in a link format the link ui won't show on click:
> 

Fixed in https://github.com/WordPress/gutenberg/pull/59635/commits/d0c5015540695d319d23ea0271f2b86df016c4f7

**Comment by scruffian** [comment]
Thanks for the fix Dave. Unfortunately it doesn't work if you have both bold and italics!
Screenshot 2024-03-07 at 17 36 47


Note; This is also an issue in trunk

**Comment by bacoords** [comment]
Just did some more testing as of 3f63012 and I'm not seeing any of the other issues. Looks really good!

The only inconsistent behavior I see is when moving the keyboard via cursor
- from link to link, the popover stays visible (but correctly moves to the new link)
- from link to text to link, the popover disappears 

I hesitate to even mention it, as I don't think it's really an issue stopping this. Working very well IMO.

**Comment by jeryj** [comment]
Thanks for testing it out @bacoords!

> from link to link, the popover stays visible (but correctly moves to the new link)
> from link to text to link, the popover disappears

Could you explain these a bit more or upload a video of the behavior you're seeing? I'm not sure I follow the situations and what the expected behavior is.

File: packages/format-library/src/link/inline.js [hunk 6]
```diff
@@ -88,6 +89,8 @@ function InlineLinkUI( {
 		]
 	);
 
+	const hasLink = linkValue?.url;
```
Comment (jeryj) [inline packages/format-library/src/link/inline.js]: Why was this moved outside of the `onChangeLink` function?

**Comment by bacoords** [comment]
> Could you explain these a bit more or upload a video of the behavior you're seeing? I'm not sure I follow the situations and what the expected behavior is.

Yep adding a video here. Basically when you move the cursor into a link with the keyboard, there's no popover. But if you move the cursor from one link (and the popover is showing) directly into another link, the popover is showing already. 

*I really don't think this is a big deal,* just noting that it occurs in case there's some specific issue (A11y, maybe) with the popover already showing when you keyboard nav into a link.

I can't find any other issues, though.

https://github.com/WordPress/gutenberg/assets/6867360/5af03564-c4b1-4360-a287-e5e60ed348d8

**Comment by getdave** [comment]
> Thanks for the fix Dave. Unfortunately it doesn't work if you have both bold and italics! > 
> Note; This is also an issue in trunk

I've believe I've fixed it with a more robust method using `.closest()`. Note I"m not intending to fix the issue on `trunk` but a consequence of fixing the click is that this is also fixed.


https://github.com/WordPress/gutenberg/assets/444434/ac5f117e-f9c6-4e0a-a50b-da0b35948a7f

**Comment by getdave** [comment]
@jeryj I noticed you forced constrained tabbing in https://github.com/WordPress/gutenberg/pull/59635/commits/3f63012880d4273075fcda7d1906f8e68cbcafa6. Can I confirm that's an a11y change to enforce some consistency in how the modal behaves once focus is transferred into it? It seems fine to me but I wanted to make sure.

File: packages/format-library/src/link/inline.js (hunk 6 above)
Comment (getdave) [reply packages/format-library/src/link/inline.js]: Ah that's a left over from a previous experiment. Let me revert that.

**Comment by scruffian** [comment]
> @jeryj I noticed you forced constrained tabbing in https://github.com/WordPress/gutenberg/commit/3f63012880d4273075fcda7d1906f8e68cbcafa6. Can I confirm that's an a11y change to enforce some consistency in how the modal behaves once focus is transferred into it? It seems fine to me but I wanted to make sure.

@jeryj and I worked on this yesterday and we felt that the focus trap was beneficial in this case. That's also how things work in trunk, because the popover grabs focus initially, so it's restoring that behaviour.

**Review by scruffian — APPROVED** [review]
This seems to solve a lot of bugs and is an ingenious solution. Well done!

File: packages/format-library/src/link/index.js [hunk 7]
```diff
@@ -38,10 +38,38 @@ function Edit( {
...
+
 	// We only need to store the button element that opened the popover. We can ignore the other states, as they will be handled by the onFocus prop to return to the rich text field.
 	const [ openedBy, setOpenedBy ] = useState( null );
 
+	const [ autoFocus, setAutoFocus ] = useState( true );
```
Comment (draganescu) [inline packages/format-library/src/link/index.js]: Is the state _actually_ `autoFocus`, or is it reall `shouldAutofocus`?

File: packages/format-library/src/link/index.js [hunk 8]
```diff
@@ -38,10 +38,38 @@ function Edit( {
...
+
+	function setIsEditingLink( _val, { shouldAutoFocus = true } = {} ) {
+		setEditingLink( _val );
+		setAutoFocus( shouldAutoFocus );
```
Comment (draganescu) [inline packages/format-library/src/link/index.js]: why not set the state right where we determine the value of `shouldAutoFocus`?

File: packages/format-library/src/link/index.js [hunk 9]
```diff
@@ -38,10 +38,38 @@ function Edit( {
...
+	}
+
+	function setIsCreatingLink( _val ) {
+		// Don't add a new link if there is already an active link.
```
Comment (draganescu) [inline packages/format-library/src/link/index.js:56]: what is `_val`?

File: packages/format-library/src/link/index.js [hunk 10]
```diff
@@ -38,10 +38,38 @@ function Edit( {
...
+		// The two states are mutually exclusive.
+		if ( _val === true && isActive ) {
+			return;
+		}
+		setCreatingLink( _val );
+	}
+
+	useEffect( () => {
+		// When the link becomes inactive (i.e. isActive is false), reset the editingLink state
+		// and the isAddingNewLink state. This means that if the Link UI is displayed and the link
```
Comment (draganescu) [inline packages/format-library/src/link/index.js]: is there a difference why isAddingNewLink but only editingLink (not isEditingLink)?

File: packages/rich-text/src/component/use-anchor.js [hunk 11]
```diff
@@ -7,6 +7,8 @@ import { useState, useLayoutEffect } from '@wordpress/element';
 /** @typedef {import('../register-format-type').WPFormat} WPFormat */
 /** @typedef {import('../types').RichTextValue} RichTextValue */
 
+const STABLE_OBJECT = {};
```
Comment (draganescu) [inline packages/rich-text/src/component/use-anchor.js]: what is this stable object?

File: packages/rich-text/src/component/use-anchor.js [hunk 12]
```diff
@@ -162,7 +169,19 @@ export function useAnchor( { editableContentElement, settings = {} } ) {
...
 			);
 		}
-	}, [ editableContentElement, tagName, className, isActive, wasActive ] );
+	}, [
+		editableContentElement,
+		tagName,
+		className,
+		isActive,
+		wasActive,
+		// Active attributes is defaulted to a stable object to avoid re-rendering,
```
Comment (draganescu) [inline packages/rich-text/src/component/use-anchor.js]: It's unclear what the "stable object" idea should offer.

File: packages/format-library/src/link/index.js (hunk 8 above)
Comment (getdave) [reply packages/format-library/src/link/index.js]: Given how critical autoFocus state is to the UX and a11y I wanted to make it as hard as possible for someone to accidentally call `setEditingLink` without managing the focus. 

So I made this wrapper "setter" function to default autoFocus to `true` meaning that someone has to really really want to disable autoFocus.

It's not perfect but...

File: packages/format-library/src/link/index.js (hunk 10 above)
Comment (getdave) [reply packages/format-library/src/link/index.js]: No - its a typo I will correct.

File: packages/format-library/src/link/index.js (hunk 9 above)
Comment (getdave) [reply packages/format-library/src/link/index.js:56]: I used a better name here in this place and in one other place where I used the same silly pattern. Thanks for calling it out 👍

File: packages/rich-text/src/component/use-anchor.js (hunk 12 above)
Comment (getdave) [reply packages/rich-text/src/component/use-anchor.js]: I agree. See

> The Link UI position gets "stuck" on the second clicked link

...from [this comment](https://github.com/WordPress/gutenberg/pull/59635#issuecomment-1983462373).

I am loath to modify the API of `useAnchor` (even if it's "safe") but without this "fix" this PR will not working because the anchor will not be recomputed.

We've run into this issue before but somehow our UI masked the error but it keeps surfacing.

Comment (getdave) [reply packages/rich-text/src/component/use-anchor.js]: ~I am actually wondering if I made the function signature use a object is that object "stable" (by which I mean, it is not a new _reference_ on each call of the hook).~

Update: I confidence checked myself and no this would be incorrect. We need to provide a stable object as the default and so what I have in the PR now is correct.


```js
// I'm now proposing we DON'T do this...
const {
	tagName,
	className,
	isActive,
	__unstableActiveAttributes: activeAttributes = {}, // new object reference each time :(
} = settings;
```

The reason why I want a stable object, is because it is one of the deps to the `useLayoutEffect` and thus if it changes on each render then the effect will run more often then is necessary. For the purposes of backwards compatibility I want to make sure there are no performance regressions introduced by providing this new setting option.

File: packages/rich-text/src/component/use-anchor.js (hunk 11 above)
Comment (getdave) [reply packages/rich-text/src/component/use-anchor.js]: https://github.com/WordPress/gutenberg/pull/59635#discussion_r1517628025

File: packages/rich-text/src/component/use-anchor.js [hunk 13]
```diff
@@ -138,7 +140,12 @@ function getAnchor( editableContentElement, tagName, className ) {
  * @return {Element|VirtualAnchorElement|undefined|null} The active element or selection range.
  */
 export function useAnchor( { editableContentElement, settings = {} } ) {
```
Comment (getdave) [inline packages/rich-text/src/component/use-anchor.js]: @ellatrix I would very much appreciate your opinion on this change.

The crux of this is that when clicking between multiple links in the same `contenteditable` (i.e. paragraph), the Link UI popover was being incorrectly anchored.

This was because the `useLayoutEffect` was not being re-run because all the props were the same between renders. This is because _all_ link formats have the same:

- `tagName` - this is _always_ `a` for `core/link`.
- `className` - this is an empty string by default.
- `isActive` status - this will vary based on state of link activation.

The last is is probably the one that will peek interest. Whilst it's obvious that the `tagName` and `className` will be stable, you'd think `isActive` would change when moving between links.

It does in fact do this, but when you click on a link the `isActive` status is set to `true`. If you then click _directly_ on _another_ link the `isActive` status remains as `true`. This state continues across all links so long as you don't click outside of a link format. As a result the `useLayoutEffect` deps don't change and thus the anchor is not recomputed.

Ultimately I decided what we needed is a way to distinguish between mutliple link formats in a single contenteditable. It is for this reason that I have introduced the `activeAttributes` as an optional setting prop because this will be unique to each individual format. This guarantees the `useLayoutEffect` will run and recompute the anchor position correctly.

As I'm not absolutely 100% confident in the API, I've elected to do two things

1. Default to a stable reference so that any consumer of `useAnchor` will not cause re-renders if it doesn't pass `activeAttributes` as one of the settings.
2. Mark as `__unstable`.

File: packages/rich-text/src/component/use-anchor.js [hunk 14]
```diff
@@ -162,7 +169,19 @@ export function useAnchor( { editableContentElement, settings = {} } ) {
...
+		editableContentElement,
+		tagName,
+		className,
+		isActive,
+		wasActive,
+		// Active attributes is defaulted to a stable object to avoid re-rendering,
+		// but in specific circumstances it can be used to provide additional information
+		// about the currently active format to disambiguate the format from other instances of the same format
+		// within the same editable content element. This is useful for `core/link` when you
+		// want to disambiguate between different links when clicking between them.
```
Comment (youknowriad) [inline packages/rich-text/src/component/use-anchor.js]: Reading this comment, and looking at the history of this file, I see that in 6.4 we had event listeners to listen to "selection changes". I'm almost certain that these event listeners were here to address this particular issue. (update the anchor when the selection changes).

Comment (youknowriad) [reply packages/rich-text/src/component/use-anchor.js]: So I guess we need to check why these event listeners were actually removed.

File: packages/rich-text/src/component/use-anchor.js (hunk 13 above)
Comment (getdave) [reply packages/rich-text/src/component/use-anchor.js]: @youknowriad also pointed out that https://github.com/WordPress/gutenberg/pull/58900/ seemed to make some large changes to the implementation of `useAnchor` which may be related to the incorrect anchor situation.



I'm going to continue to dive in here as in essence I would much prefer to avoid any change to `useAnchor` (excepting reverting to a previous code state) at this juncture.

File: packages/rich-text/src/component/use-anchor.js (hunk 14 above)
Comment (getdave) [reply packages/rich-text/src/component/use-anchor.js]: Discussion continues in [this comment](https://github.com/WordPress/gutenberg/pull/59635#discussion_r1517687396)

File: packages/rich-text/src/component/use-anchor.js (hunk 13 above)
Comment (getdave) [reply packages/rich-text/src/component/use-anchor.js]: I reverted (locally only at this stage) `useAnchor` to the [state of the code](https://github.com/WordPress/gutenberg/blob/7e51b4352cdb5ad22b874d969f8dbb972d233525/packages/rich-text/src/component/use-anchor.js#L139C1-L180C2) prior to https://github.com/WordPress/gutenberg/pull/58900.

```
git checkout 7e51b4352cdb5ad22b874d969f8dbb972d233525 packages/rich-text/src/component/use-anchor.js
```

<details>
<summary>Patch diff</summary>


```diff
diff --git a/packages/rich-text/src/component/use-anchor.js b/packages/rich-text/src/component/use-anchor.js
index 3e950d4d3c..5f99509c1f 100644
--- a/packages/rich-text/src/component/use-anchor.js
+++ b/packages/rich-text/src/component/use-anchor.js
@@ -140,48 +140,44 @@ function getAnchor( editableContentElement, tagName, className ) {
  * @return {Element|VirtualAnchorElement|undefined|null} The active element or selection range.
  */
 export function useAnchor( { editableContentElement, settings = {} } ) {
-	const {
-		tagName,
-		className,
-		isActive,
-		__unstableActiveAttributes: activeAttributes = STABLE_OBJECT,
-	} = settings;
+	const { tagName, className } = settings;
 	const [ anchor, setAnchor ] = useState( () =>
 		getAnchor( editableContentElement, tagName, className )
 	);
-	const wasActive = usePrevious( isActive );
 
 	useLayoutEffect( () => {
 		if ( ! editableContentElement ) return;
 
 		const { ownerDocument } = editableContentElement;
 
-		if (
-			editableContentElement === ownerDocument.activeElement ||
-			// When a link is created, we need to attach the popover to the newly created anchor.
-			( ! wasActive && isActive ) ||
-			// Sometimes we're _removing_ an active anchor, such as the inline color popover.
-			// When we add the color, it switches from a virtual anchor to a `<mark>` element.
-			// When we _remove_ the color, it switches from a `<mark>` element to a virtual anchor.
-			( wasActive && ! isActive )
-		) {
+		function callback() {
 			setAnchor(
 				getAnchor( editableContentElement, tagName, className )
 			);
 		}
-	}, [
-		editableContentElement,
-		tagName,
-		className,
-		isActive,
-		wasActive,
-		// Active attributes is defaulted to a stable object to avoid re-rendering,
-		// but in specific circumstances it can be used to provide additional information
-		// about the currently active format to disambiguate the format from other instances of the same format
-		// within the same editable content element. This is useful for `core/link` when you
-		// want to disambiguate between different links when clicking between them.
-		activeAttributes,
-	] );
+
+		function attach() {
+			ownerDocument.addEventListener( 'selectionchange', callback );
+		}
+
+		function detach() {
+			ownerDocument.removeEventListener( 'selectionchange', callback );
+		}
+
+		if ( editableContentElement === ownerDocument.activeElement ) {
+			attach();
+		}
+
+		editableContentElement.addEventListener( 'focusin', attach );
+		editableContentElement.addEventListener( 'focusout', detach );
+
+		return () => {
+			detach();
+
+			editableContentElement.removeEventListener( 'focusin', attach );
+			editableContentElement.removeEventListener( 'focusout', detach );
+		};
+	}, [ editableContentElement, tagName, className ] );
 
 	return anchor;
 }

```
</details>

This appears to fix the anchor positioning issue without requiring any further changes to `useAnchor`.



https://github.com/WordPress/gutenberg/assets/444434/5208f872-3c65-4592-8f31-c20db138d69c

Therefore I wonder if @jeryj could confirm whether he notices any other regressions as a result of reverting https://github.com/WordPress/gutenberg/pull/58900?

It not then I propose we revert the changes in https://github.com/WordPress/gutenberg/pull/58900.

File: packages/format-library/src/link/inline.js [hunk 15]
```diff
@@ -216,7 +217,11 @@ function InlineLinkUI( {
 
 	const popoverAnchor = useAnchor( {
 		editableContentElement: contentRef.current,
-		settings: { ...settings, isActive },
+		settings: {
+			...settings,
+			isActive,
+			__unstableActiveAttributes: activeAttributes,
```
Comment (youknowriad) [inline packages/format-library/src/link/inline.js:223]: This change is not needed anymore right.

File: packages/rich-text/src/component/use-anchor.js (hunk 14 above)
Comment (jeryj) [reply packages/rich-text/src/component/use-anchor.js]: This PR explains the rationale and bug fixes it addresses: https://github.com/WordPress/gutenberg/pull/58900

tl;dr: The selection listeners were necessary for the previous link popover behavior of using the arrows to move a caret into the text to show the link ui popover. This UX was changed based on design and a11y feedback, so they were no longer necessary. Also, the previous useAnchor implementation did not account for repositioning a popover when the selection changed elements underneath of it (for example, when creating a link, the selected text goes from no extra markup to having an <a> wrapped on it, which caused the popover to lose its anchoring).

File: packages/rich-text/src/component/use-anchor.js (hunk 13 above)
Comment (jeryj) [reply packages/rich-text/src/component/use-anchor.js]: Try creating a link :) The isActive / wasActive checks allow for the popover to reposition when the selection changes the element underneath of it. Ie, going from no markup to an <a>. This bug was attempted to be fixed by caching the position, but that just covered up the underlying issue and caused its own bug of being fixed position on the page when scrolling.

https://github.com/WordPress/gutenberg/assets/967608/2057a931-ca9f-49f2-8404-4f6b1027da9b

File: packages/rich-text/src/component/use-anchor.js (hunk 14 above)
Comment (getdave) [reply packages/rich-text/src/component/use-anchor.js]: > The selection listeners were necessary for the previous link popover behavior of using the arrows to move a caret into the text to show the link ui popover.

So I _think_ that may have been there also to account for clicking between links. So when you click from one link to the next the "selection" event fires and thus the anchor gets recompute.

File: packages/rich-text/src/component/use-anchor.js (hunk 13 above)
Comment (getdave) [reply packages/rich-text/src/component/use-anchor.js]: Ah yes it was about _creation_ of links. Right. Let's see if we can work this out then.

**Comment by jeryj** [comment]
> @jeryj I noticed you forced constrained tabbing in https://github.com/WordPress/gutenberg/commit/3f63012880d4273075fcda7d1906f8e68cbcafa6. Can I confirm that's an a11y change to enforce some consistency in how the modal behaves once focus is transferred into it? It seems fine to me but I wanted to make sure.

Yup. If you don't constrain tabbing, then it's very easy to accidentally tab outside of the popover, which closes it due to onFocusOutside on the popover closing itself. It _is_ technically a focus trap, but it doesn't _feel_ like one, as it's akin to focus being placed on the wrapper of the popover when clicking a link. Also, escape does work to move back to the caret selection. I think this is one of those murky areas where having a focus trap when you tab into it is actually a better experience for everyone.

**Comment by joedolson** [comment]
Noting that a 'focus trap' is actually a case where there is *no* way to get out of a context. This is not a focus trap, it's a focus constraint; which limits focus movement, but offers methods to end the constraint - and there are several ways to exit the popover.  It does seem like a close button would be beneficial, for clarity - it's a little confusing for a keyboard user to have to click 'edit' in order to cancel.

**Comment by getdave** [comment]
As a next step here I am going to explore reverting the changes to `useAnchor` and go back to having listeners

File: packages/rich-text/src/component/use-anchor.js (hunk 13 above)
Comment (getdave) [reply packages/rich-text/src/component/use-anchor.js]: Circling back, here's what I've done to resolve this:

- reverted (some of) the changes to the `useAnchor` API in https://github.com/WordPress/gutenberg/pull/58900 to restore the selection listeners present in WP 6.4.
- applied the internal changes around `isActive` from https://github.com/WordPress/gutenberg/pull/58900 which are a bug fix required to account for correct positioning when switching from "virtual" to Element anchors.
- reverted any changes to `useAnchor` API that I initially made when I introduced the `__unstableActiverAttributes` prop.

These changes were made in https://github.com/WordPress/gutenberg/pull/59635/commits/f92328689079442c7070d5e6b903d12ebf024d9e.

Rationale:

- changes to remove the listeners in https://github.com/WordPress/gutenberg/pull/58900 were made on the basis of them not being required for the Link UI implementation. However, as `useAnchor` is exported, we cannot know what use cases it is currently supporting and changing such a key implementation detail has the potential for backwards compatibility issues. Therefore reverting to the state of the code in WP 6.4 should not be considered a "change" for 6.5.
- changes to introduce the `isActive` prop were included in WP 6.5 prior to the Beta / RC period and thus are valid to be maintained. They are part of a legitimate bug fix.

From what I can see the functionality is now working as expected but I could do with careful checking.

Comment (youknowriad) [reply packages/rich-text/src/component/use-anchor.js]: > we cannot know what use cases it is currently supporting and changing such a key implementation detail has the potential for backwards compatibility issues

It's not just about backward compatibility, having the listeners is the right fix to position the anchor properly when you switch between links using the mouse.

**Comment by getdave** [comment]
I'm proposing this for inclusion in WordPress 6.5 during the RC period. Why? Because

- this PR fixes a bad bug with the Link UI where mouse users cannot edit the text of the link within the rich text when clicking on a link.
- this PR reverts the `useAnchor` implementation to restore code _already_ in use in WP 6.**4**

File: packages/rich-text/src/component/use-anchor.js (hunk 13 above)
Comment (jeryj) [reply packages/rich-text/src/component/use-anchor.js]: Sounds like a reasonable way forwards to me. Thanks @getdave!

**Comment by jeryj** [comment]
> I'm proposing this for inclusion in WordPress 6.5 during the RC period.

👍🏻

File: packages/format-library/src/link/index.js [hunk 16]
```diff
@@ -52,14 +81,18 @@ function Edit( {
 			// There is a situation whereby there is an existing link in the rich text
 			// and the user clicks on the leftmost edge of that link and fails to activate
 			// the link format, but the click event still fires on the `<a>` element.
-			// This causes the `addingLink` state to be set to `true` and the link UI
+			// This causes the `editingLink` state to be set to `true` and the link UI
 			// to be rendered in "creating" mode. We need to check isActive to see if
 			// we have an active link format.
-			if ( event.target.tagName !== 'A' || ! isActive ) {
+			if (
+				! event.target.closest( '[contenteditable] a' ) || // other formats (e.g. bold) may be nested within the link.
```
Comment (draganescu) [inline packages/format-library/src/link/index.js:88]: This is an enhancement compared to `trunk` 😄

**Review by draganescu — APPROVED** [review]
This PR seems to tick all the boxes:

- fixes the bug
- improves underlying issues
- enhances the experience where the bug exists

File: packages/format-library/src/link/index.js (hunk 16 above)
Comment (getdave) [reply packages/format-library/src/link/index.js:88]: ...yes in terms of it fixes a regression introduced during the 6.5 cycle whereby links that had other formats inside them would not activate on click 👍

**Comment by getdave** [comment]
I just manually cherry-picked this PR to the pick/wp-65-rc-2 branch to get it included in the next release

https://github.com/WordPress/gutenberg/pull/59756
