### PR TITLE
GMT Offset Issues in RSS Block According to Trac Report 62400

### LINKED ISSUE #66970: RSS Block displays date in UTC instead of site timezone
### Description

The RSS Block is displaying dates in UTC rather than using the timezone set in the WordPress site settings. This causes dates from feeds to appear incorrectly when the site’s timezone is not UTC. For instance, if a feed contains an item with <pubDate>Wed, 13 Nov 2024 04:52:00 +0900</pubDate> and the site timezone is set to UTC+9, the date is displayed as November 12, 2024, rather than the expected November 13, 2024.

Related Trac Ticket: [#62400](https://core.trac.wordpress.org/ticket/62400)

### Step-by-step reproduction instructions

1. Go to Settings > General in the WordPress dashboard and set the site timezone to something other than UTC, such as UTC+9.
2. Add an RSS Block to a post or page.
3. Link the RSS Block to an RSS feed where pubDate includes a timezone offset (e.g., [MixOnline](https://www.mixonline.jp/DesktopModules/MixOnline_Rss/MixOnlinerss.aspx?rssmode=3), which uses +0900).
4. Enable “Display date” in the RSS Block settings.
5. Preview or publish the post.

### Environment info

WordPress Version: 6.7
Browser: Chrome
Operating System: Mac OS

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by SirLouen**
## What?
Closes #66970.

There is a Wordpress issue 
https://core.trac.wordpress.org/ticket/62400
And a PR that was sorting this
https://github.com/WordPress/wordpress-develop/pull/8543

## Why?
The code was resolved in the wordpress core repo, but then @peterwilsoncc suggested me that blocks code is going now into the Gutenberg's repo. So this is just an extension of the OG code.

## Testing Instructions
I recommend checking my testing report
https://core.trac.wordpress.org/ticket/62400#comment:21
Which led me to create this patch

Both testing instructions, and a testing report + PHP Unit tests are included in both the track report and the `wordpress-develop` repo

### CODE REVIEW

**Comment by peterwilsoncc** [comment]
Looks like there are some network issues causing some of the tests to fail.

As noted in the WP-Dev repo, the tests can be brought across in to the https://github.com/WordPress/gutenberg/tree/trunk/phpunit/blocks folder, you'll need to add a new file for the RSS block.

(Cross post for others tracking this issue)

**Comment by SirLouen** [comment]
I have updated the file, so now I can pick the RSS mock data (although it's unclear where all the mock data is contained is this repo's file structure). I placed wherever I felt it seemed a good place for this.

Also, It's strange because the test is failing, when it was perfectly working in the WP repo.

From what I can read in the failed test, it seems like the `index.php` updated code is not being integrated into the final WP testing environment for the unit test, so it’s still taking for the test the old version. 

Am I missing some command to integrate this updated `index.php` into the final build or something?

**Comment by Mamaduka** [comment]
I think there's already PR to fix the same problem - https://github.com/WordPress/gutenberg/pull/66971.

**Comment by SirLouen** [comment]
@Mamaduka it's weird that such PR even exist, a little history to set you up:

If you can see the in WordPress trac report: https://core.trac.wordpress.org/ticket/62400
Another guy called narenin https://github.com/WordPress/wordpress-develop/pull/7798
Copy/pasted that wrong PR, as you can see in all the testing reports there like:
https://core.trac.wordpress.org/ticket/62400#comment:20
https://core.trac.wordpress.org/ticket/62400#comment:21

But in WP core, if you want to solve an "abandoned" PR (that the person did not take the intention to continue with it), you should recreate another PR. This is when I tooked it from scratch and sorted it here:
https://github.com/WordPress/wordpress-develop/pull/8543

I could have never imagined that that person "narenin" would have copy/pasted the #66971 here. 

So lets close that #8543 that is broken and lets try to continue from here to sort this issue that was planned to released in 6.8.

This said:
> Am I missing some command to integrate this updated index.php into the final build or something?

Any comments or ideas about this?

**Comment by Mamaduka** [comment]
@SirLouen, it's not a problem. Just wanted to mention existing PR for booking keeping and reference.

File: phpunit/blocks/render-block-rss-test.php [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+		$attributes = array(
+			'feedURL'        => 'https://example.com/testrss.xml',
+			'itemsToShow'    => 2,
+			'displayExcerpt' => false,
+			'displayAuthor'  => false,
+			'displayDate'    => true,
+			'blockLayout'    => 'list',
+		);
+
+		$rendered_html = render_block_core_rss( $attributes );
```
Comment (Mamaduka) [inline phpunit/blocks/render-block-rss-test.php]:
```suggestion
		$rendered_html = gutenberg_render_block_core_rss( $attributes );
```

I've not tested the suggested change, but IIRC, the plugin tests should prefix the render function with `gutenberg_`. This is how the plugin builds PHP files and avoids conflicts with the core.

You can check the `build/block-library/blocks` directory for confirmation.

**Comment by SirLouen** [comment]
Failing the [Verify Core Backport Changelog / Check for a Core backport changelog entry (pull_request)
Should I add something on my side? Or shall I assume that a core committer should add the respective entry in the changelog md?

**Comment by Mamaduka** [comment]
There's no need for a manual backport for this PR. Any changes in the `block-library` package are automatically synced with the core when packages are updated.

File: phpunit/blocks/render-block-rss-test.php [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+
+		add_filter( 'wp_feed_cache_transient_lifetime', '__return_zero' );
+		add_filter( 'pre_http_request', array( $this, 'mock_http_request' ), 10, 3 );
+	}
+
+	/**
+	 * Mock HTTP request to return test feed data.
+	 *
+	 * @ticket 62400
+	 *
```
Comment (peterwilsoncc) [inline phpunit/blocks/render-block-rss-test.php]:
```suggestion
```

File: phpunit/blocks/render-block-rss-test.php [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+			'cookies'  => array(),
+			'filename' => null,
+		);
+	}
+
+	/**
+	 * Sets up the "core/rss" block context for testing.
+	 * This is needed to avoid null access in WP_Block_Supports::apply_block_supports().
+	 *
+	 * @ticket 62400
```
Comment (peterwilsoncc) [inline phpunit/blocks/render-block-rss-test.php]:
```suggestion
```

File: phpunit/blocks/render-block-rss-test.php [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+		$reflection        = new ReflectionClass( $wp_block_supports );
+		$property          = $reflection->getProperty( 'block_to_render' );
+		$property->setAccessible( true );
+		$property->setValue( $wp_block_supports, $block );
+	}
+
+	/**
+	 * Test that the date in the RSS feed is correctly rendered in the HTML.
+	 *
+	 * @ticket 62400
```
Comment (peterwilsoncc) [inline phpunit/blocks/render-block-rss-test.php]: Reference to the Gutenberg ticket number rather than the core ticket.

```suggestion
	 * @ticket 66970
```

**Review by peterwilsoncc — APPROVED** [review]
This looks good and works well in manual testing.

Thanks for the assist with getting the tests running against the correct function, George. 

I've left a couple of minor notes but pre-approving pending those changes

File: phpunit/blocks/render-block-rss-test.php [hunk 5]
```diff
@@ -0,0 +1,108 @@
...
+
+		add_filter( 'wp_feed_cache_transient_lifetime', '__return_zero' );
+		add_filter( 'pre_http_request', array( $this, 'mock_http_request' ), 10, 3 );
+	}
+
+	/**
+	 * Mock HTTP request to return test feed data.
+	 *
+	 * @ticket 66970
+	 *
```
Comment (peterwilsoncc) [inline phpunit/blocks/render-block-rss-test.php]:
```suggestion
```

File: phpunit/blocks/render-block-rss-test.php [hunk 6]
```diff
@@ -0,0 +1,108 @@
...
+			'cookies'  => array(),
+			'filename' => null,
+		);
+	}
+
+	/**
+	 * Sets up the "core/rss" block context for testing.
+	 * This is needed to avoid null access in WP_Block_Supports::apply_block_supports().
+	 *
+	 * @ticket 66970
```
Comment (peterwilsoncc) [inline phpunit/blocks/render-block-rss-test.php]:
```suggestion
```

**Review by peterwilsoncc — COMMENTED** [review]
I'm going to self merge these so I can get the code committed. 

It's just a couple of changes to remove the ticket number from the non-test methods as they're not required.
