### PR TITLE
Fix: Show Meta Boxes at the bottom of the screen regardless of the current rendering mode

### LINKED ISSUE #66507: Metaboxes are not shown when editor rendering mode is set to `template-locked`
The editor usually shows the traditional metaboxes at the bottom of the screen. Big players such as Yoast or Multilingualpress are still using this metabox location so we even made the effort to now support having it visible when the post editor is rendered in an iframe. 

However in testing I just noticed that we are only showing the metaboxes when the rendering mode of the editor is set to `post-only`. To me this doesn't really make sense. The `template-locked` rendering mode to me also deserves to get the metabox area displayed. Because at that point in time you are still editing a post and therefore metadata of said post. 

Only when you get to the `template-only` mode does it make sense to hide that metabox area as we are no longer in the context of a single post.

https://github.com/WordPress/gutenberg/blob/bf84ac6cf918591c394d09dbb53caa7e16be34bb/packages/edit-post/src/components/layout/index.js#L427-L429

### PR DESCRIPTION
**Pull request by fabiankaegy**
## What?

allow metaboxes to remain visible in `template-locked` rendering mode (closing #66507)

## Why?

Because in the `template-locked` rendering mode you are actively still editing a post. So any metaboxes should still be available. They should only disappear in the `template-only` mode.

## How?

By adding an additional check if the mode is either `post-only` or `template-locked`

## Testing Instructions

1. Install a plugin such as Yoast which registers a Metabox
2. Activate that plugin
3. Open a post
4. Check the "Preview Template" option in the post sidebar under the template setting
5. Ensure the metabox is still visible in the `template-locked` mode

### CODE REVIEW

**Comment by Mamaduka** [comment]
This was introduced in #65885.

**Comment by fabiankaegy** [comment]
@Mamaduka I think the PR you share is unrelated. I'm not talking about the additional padding appender at the bottom but rather the metaboxes area which was refactored in the 6.7 cycle but already in 6.6 using the preview template hid the metaboxes. So this is not a new regression.

File: packages/edit-post/src/components/layout/index.js [hunk 1]
```diff
@@ -426,7 +428,7 @@ function Layout( {
 				isDistractionFree: get( 'core', 'distractionFree' ),
 				showMetaBoxes:
 					! DESIGN_POST_TYPES.includes( currentPostType ) &&
-					isRenderingPostOnly,
+					( isRenderingPostOnly || isRenderingTemplateLocked ),
```
Comment (Mamaduka) [inline packages/edit-post/src/components/layout/index.js]: Can you refresh my memory here? Do we have rendering modes besides `post-only` and `template-locked`?

If not, then I think we can remove rendering mode checks from this condition.

Comment (fabiankaegy) [reply packages/edit-post/src/components/layout/index.js]: I am not a 100% certain but I thought that the "edit template" portion in the post editor technically uses `template-only` as the rendering mode 🤔 

@youknowriad may be able to help clarify this though :)

Comment (t-hamano) [reply packages/edit-post/src/components/layout/index.js]: Judging from [the comment of the `setRenderingMode` action](https://github.com/WordPress/gutenberg/blob/7714bce8d9356707a020b5d7df84797832c423f8/packages/editor/src/store/actions.js#L651-L652), there should be no modes other than `post-only` and `template-locked`. The `template-only` mode has been removed in #57700. I've tried searching Gutenberg in general for `getRenderingMode()` or `setRenderingMode(`, but I can't find any other modes.

Therefore, I think this check should be removable, but I will ping @stokesman to double check.

Comment (stokesman) [reply packages/edit-post/src/components/layout/index.js]: Removing it looks safe to me. I quickly checked with "edit template" and its rendering mode is "post-only". The condition that matters in that case is the post type being "wp_template" so it will still not show the meta boxes.

Comment (fabiankaegy) [reply packages/edit-post/src/components/layout/index.js]: Thanks all! I just updated the code to remove the check entirely  👍 :)

**Review by stokesman — APPROVED** [review]
I tested and the meta boxes show with "show template" enabled. This makes sense to me. Maybe the title of this PR can be updated since the rendering mode is no longer factored in.

**Comment by fabiankaegy** [comment]
@youknowriad @ndiego @annezazu Wondering if we could consider this a fix we want to get into 6.7.1? With the new meta box styling here and more usage of the template preview this issue is much more prevalent in 6.7 than it was before 🤔

**Comment by youknowriad** [comment]
Let's give it a try. I added the flag. Not sure who's going to be leading that release though

**Comment by annezazu** [comment]
Agreed with Riad. Thanks for flagging this, Fabian!

**Comment by cbravobernal** [comment]
Backported to `wp/6.7` to include in 6.7.2

**Comment by fabiankaegy** [comment]
@aaronjorbin I am not seeing this change when running 6.7.2-RC1. Any idea what might be going on there or how to better debug this?  🤔

**Comment by stokesman** [comment]
From a quick look I think we [undid](https://github.com/WordPress/gutenberg/commit/2a8dc3794cf1a67a8e0ed04a6e7cfa89ae84e86b#diff-8933c0b377d83066f7dde9c8b573bab9a7bfe60f73919e4e5e80aff92a88800cR456) this unintentionally with #68902 😢.

**Comment by fabiankaegy** [comment]
@stokesman any reason we shouldn't remove that line you linked on the 6.7 branch to re fix the issue?

**Comment by stokesman** [comment]
> any reason we shouldn't remove that line you linked on the 6.7 branch to re fix the issue?

Not that I can see.

**Comment by t-hamano** [comment]
Removing `Backport to WP Minor Release` label because #67241, which is equal to this PR, has already been merged into `wp/6.7` branch.
