### PR TITLE
Only scroll page for multi-selections

### LINKED ISSUE #19682: Screen focus is lost when a user clicks on a list item in a lengthy list block
**Describe the bug**
When a user tries to edit an item near the end of a list block with lengthy content, is not alread in that block, and clicks on the list item, the user is brought to the center of the list block. For longer lists, this behavior (re-centering/focusing) is problematic for users who expect the screen to remain where they clicked. 

It is a bit difficult to exactly express this behavior, but this GIF captures it quite nicely. 
ezgif-6-6b059c98208b

**To reproduce**
1. Create a list with lengthy items that would extend beyond the current view of the desktop. 
2. scroll to a list item that is near the end of the list 
3. click on a list item 

**Expected behavior**
When a user clicks on a list item, the current view of the screen would remain where the user clicked; not towards the center of the block. 

**Desktop (please complete the following information):**
- Firefox (have not tested this on Chrome) on both linux and windows 
- Gutenberg v7.2.0; 
- replicated this on both TwentyTwenty theme and our internal custom theme. 

**Work around**
I've been able to workaround this with our content editors by instructing them to first click anywhere within the list block (which establishes initial focus), and then click the list item that they wish to edit.

### LINKED ISSUE #21432: After block removal, selecting a following block sometimes also scrolls the window to the top
**Describe the bug**
When editing a long page and using the shortcut ctrl + opt + z to remove a block at the end of the page with at least two more blocks below it and then clicking on a block lower than the one you removed you’ll get scrolled up to the top of the page. It only happens sometimes though. I’m not sure what the exact conditions are to trigger it but I’m able to get it to happen semi-consistently as you can see in the video.

**To reproduce**
1. Create a new page that is long enough to need you to scoll to edit the bottom of it.
2. Add some paragraph blocks with any text in them (“asdf” will do)
3. Use the keyboard shortcut to remove the second to last block
4. Click the last block on the page (or the “Start writing…” block)

You'll see that the block you clicked _is selected_ but sometimes you get scrolled to the top of the page.

**Expected behavior**
The block you clicked is now selected and in view

**Screenshots**
Video: https://d.pr/v/hw4ZPQ

**Desktop:**
 - OS: macOS
 - Browser: Firefox
 - Version: 75.0b12

**Additional context**
- Version: 7.8

### PR DESCRIPTION
**Pull request by youknowriad**
closes #19682
closes #21432 

It seems that this component "MultiSelectScrollIntoView" has been refactored during the WP 5.4 lifecycle and it was triggering for simple selections too.

I'm not 100% certain this is the right fix but right now it only triggers for multi selections fixing this important bug #19682

### CODE REVIEW

File: packages/block-editor/src/components/multi-select-scroll-into-view/index.js [hunk 1]
```diff
@@ -21,19 +21,29 @@ import { getBlockDOMNode } from '../../utils/dom';
...
+		selector,
+		[]
+	);
 
 	useEffect( () => {
-		if ( ! selectionEnd || isMultiSelecting ) {
+		if (
+			! selectionEnd ||
+			isMultiSelecting ||
+			selectionEnd === selectionStart
```
Comment (ellatrix) [inline packages/block-editor/src/components/multi-select-scroll-into-view/index.js:45]: How about using the `hasMultiSelection` selector?

Comment (youknowriad) [reply packages/block-editor/src/components/multi-select-scroll-into-view/index.js:45]: yes, this works too

Comment (youknowriad) [reply packages/block-editor/src/components/multi-select-scroll-into-view/index.js]: Updated

**Review by ellatrix — APPROVED** [review]
