### PR TITLE
iAPI: Fix `wp-each` item contexts for objects with same key

### LINKED ISSUE #70866: iAPI: Items from `data-wp-each` doesn't work when exposed from state getters
### Description

The `wp-each` directive exposes a property that is added to the iAPI context, representing each list item. By default, this property is named `item`. When the directives inside the template access that property using derived state, they don't react to item changes under certain circumstances, e.g., when the whole list is removed and replaced by new items, even when they have the same structure.

In the following example, note the `getCurrentItem()` getter and how it is used inside the template instead of `context.item.text`:

```html
<ul>
  <template data-wp-interactive="test" data-wp-each="state.someList">
    <li data-wp-text="state.currentItem.text"></li>
  </template>
</ul>
```

```js
import { store } from '@wordpress/interactivity';

store( 'example', {
    state: {
        someList: [{ text: 'hi' }, { text: 'hola' }, { text: 'olá' }]
        get currentItem() {
            return getContext().item;
        },
    },
} );
```

### Step-by-step reproduction instructions

1.  In a JS module, create a store similar to the one in the example above.
2. Add an action that replaces the content of `state.someList` with new objects.
3. Inject the HTML above in a page or template with interactive blocks.
4. Visit that page or template.
5. Execute the action that replaces `state.someList` content.
6. Check that the list doesn't update correctly.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by DAreRodz**
## What?

Fixes a bug in the `wp-each` directive related to item contexts that affects derived state props inside the template. The bug arises when these conditions are met:
-   List items are objects.
-   Directives inside the `wp-each` template access the current item through a getter.
-   The template element has a `wp-each-key` directive pointing to a specific item prop.
-   Items from the list are replaced with new objects with the same keys.

When the template element re-renders, the items' reactive contexts are instantiated again, while the internal signals associated with the getters continue to be subscribed to the old reactive contexts.

It can be tested with the following example in a Custom HTML block:

```html
<ul data-wp-interactive="example">
  <button data-wp-on--click="actions.replaceAll">Replace all</button>
  <template data-wp-each="state.someList" data-wp-each-key="state.currentItem.text">
    <li>
        <span data-wp-text="state.currentItem.text"></span>:
        <span data-wp-text="state.isItemInList"></span>
    </li>
  </template>
</ul>
<script type="module">
import { store, getContext } from '@wordpress/interactivity';

const { state } = store( 'example', {
    state: {
        someList: [{ text: 'hi' }, { text: 'hola' }],
        get currentItem() {
            return getContext().item;
        },
        get isItemInList() {
            return state.someList.includes( state.currentItem )
                ? 'included'
                : 'not included';
        }
    },
    actions: {
        replaceAll() {
            state.someList = [{ text: 'olá' }, { text: 'hola' }]
        },
    },
} );
</script>
```

When you click on the `Replace all` button, the `state.isItemInList` getter would return "not included" for the second item. If you click again, both items will show "not included".

## Why?

The bug appeared in WooCommerce while working on an iAPI-powered Minicart block.
Related issue: https://github.com/woocommerce/woocommerce/issues/58673.

This could affect other developers using the Interactivity API.

## How?

This bug fix maintains the same reactive contexts for items with the same key when the template element is re-rendered.

For that, it implements the hook `useItemContexts` and the function `evaluateItemKey`, used by the `wp-each` directive implementation.

## Testing Instructions

1. In a page, add a Custom HTML block component with the content above.
2. Visit that page.
3. Click on the button `Replace All`.
4. Ensure items with the same previous text show  "included" instead of "not included".

### CODE REVIEW

**Comment by DAreRodz** [comment]
I rebased and updated this branch. All the tests are passing. I'm setting this PR ready for review.

File: packages/interactivity/src/directives.tsx [hunk 1]
```diff
@@ -173,6 +173,98 @@ const getGlobalEventDirective = (
...
+	item: unknown,
+	itemProp: string,
+	eachKey?: DirectiveEntry
+) => {
+	// Construct a client context with the item. Note that accessing the item
+	// prop is not reactive, as this simulated context is not proxified.
+	const clientContextWithItem = {
+		...inheritedValue.client,
+		[ namespace ]: {
+			...inheritedValue.client[ namespace ],
```
Comment (samueljseay) [inline packages/interactivity/src/directives.tsx:250]: I still don't completely grok wp-each but, is there any case where this could result in undefined? I guess that would be a user error, but do we want to throw in that case, or would it be better to just spread an empty object? Sorry if this is off, I'm still not sure if that's possible here.

File: packages/interactivity/src/directives.tsx [hunk 2]
```diff
@@ -173,6 +173,98 @@ const getGlobalEventDirective = (
...
+ * @return Generator that yields items along with their context and key.
+ */
+const useItemContexts = function* (
+	inheritedValue: any,
+	namespace: string,
+	items: Iterable< unknown >,
+	itemProp: string,
+	eachKey?: DirectiveEntry
+): Generator< [ item: unknown, context: any, key: any ] > {
+	const { current: itemContexts } = useRef< Map< any, any > >( new Map() );
```
Comment (samueljseay) [inline packages/interactivity/src/directives.tsx:286]: This map stays around and is only added to, it seems like that'd be leaky. Is there a point where we can prune unused keys every render or something similar?

**Review by samueljseay — APPROVED** [review]
Overall looks good to me. I had a couple questions, but don't consider them blockers.

File: packages/interactivity/src/directives.tsx (hunk 1 above)
Comment (DAreRodz) [reply packages/interactivity/src/directives.tsx:250]: You mean `inheritedValue`? There shouldn't be any case. We have an initial value set here:

https://github.com/WordPress/gutenberg/blob/0cfb6f8a322268205aaf8fcc874960ba9225815e/packages/interactivity/src/hooks.tsx#L116

File: packages/interactivity/src/directives.tsx (hunk 2 above)
Comment (DAreRodz) [reply packages/interactivity/src/directives.tsx:286]: Yeah, good catch! I guess we can remove entries from the `Map` instance whenever an item is removed, although I'd leave that for another PR. 🤔

**Review by luisherranz — APPROVED** [review]
Approving on behalf of @samueljseay 🙂
