### PR TITLE
Fix font library modal dialog translatable strings

### LINKED ISSUE #58201: Fonts Library: Fix translatable strings and enforce l10n best practices
### Description

Splitting this out from https://github.com/WordPress/gutenberg/issues/58110 / https://github.com/WordPress/gutenberg/pull/58117

There's a couple places in the Fonts Library user interfaces where translatable strings are less than ideal and are hardly translatable:

https://github.com/WordPress/gutenberg/blob/50fa46b51f34e956851ed00413e41d263006e208/packages/edit-site/src/components/global-styles/font-library-modal/font-card.js#L59-L64

and 

https://github.com/WordPress/gutenberg/blob/50fa46b51f34e956851ed00413e41d263006e208/packages/edit-site/src/components/global-styles/font-library-modal/local-fonts.js#L34-L38

To recap some of the l10n best practices, which are better detailed in the WordPress handbook:

- Translatable strings must not use concatenation.
- Always provide a full translatable string, do not split it in separate parts when possible.
- Use `sprintf()` and placeholders when appropriate.
- Don't ever include variables that refers to terms with varying genre / number within a single `__()` function. These cases need to be handled either bu providing separate strings or by using the `_n()` function.

### Step-by-step reproduction instructions

N/A
See code snippets linked above.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by afercia**
Fixes https://github.com/WordPress/gutenberg/issues/58201

## What?

A couple translatable strings are not translatable as they don't follow the WordPress localization best practices and are unnecessarily comples.

## Why?

Following the WordPress localization best practices makes sure strings are translatable to all languages. For example:
- Always provide full sentences instead of split sentences.
- Avoid concatenation.
- Use `sprintg` and placeholder appropriately.
- The liste item separator `, ` must be translatable as well.

## How?

- Simplifies the strings and use `sprintf` where appropriate.
- Avodis concatenation.
- ~Removes a `__( 'and' )` translatable string anc concatenation.~
- ~Introduces a `l10n` object in the `editor/utils` package. For now, it only contains a `listItemSeparator` string. In the future this could be expanded with more strings, reshaped, or even moved to a separate package if desired. Pleaae let me know if the current approach is acceptable Cc @youknowriad @SergeyBiryukov~
- Update: simplifies the allowed font types string.

Note: in Core, the list item separator comes from  `WP_Locale->get_list_item_separator()`. It is in a centralized location and can be reused across the codebase. I'd think something similar is worth introducing also in Gutenberg.

## Testing Instructions

- Go to Site editor > Styles > Typography > Manage fonts.
- In the Fonts modal dialog, go to the Google fonts tab.
- Observe the indication of the font variants is correct e.g. '1 variant', '2 variants', etc.
- Go to the Upload tab.
- Observe the descriptive text of the allowed font types is unchanged.

### CODE REVIEW

File: packages/editor/src/utils/l10n.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+/**
+ * WordPress dependencies
+ */
+import { __ } from '@wordpress/i18n';
+
+export const l10n = {
```
Comment (youknowriad) [inline packages/editor/src/utils/l10n.js]: Can you share more about this? Why is this in the editor package? Can we instead just use the string where we need it?

Comment (youknowriad) [reply packages/editor/src/utils/l10n.js]: I'm guessing the goal is to have a central place for these localized things. 
I feel like "editor" is not the right package for that. Maybe a dedicated package like `@wordpress/locale` or something. 

Also, since it's only used in one place now, maybe it's fine to start adhoc.

Comment (t-hamano) [reply packages/editor/src/utils/l10n.js]: I think this is probably aiming to implement a function equivalent to WP Core's `wp_get_list_item_separator()` function, as mentioned in [this comment](https://github.com/WordPress/gutenberg/issues/58201#issuecomment-1908456742). Personally, I think adhoc is fine for now.

Comment (afercia) [reply packages/editor/src/utils/l10n.js]: > Can you share more about this? Why is this in the editor package? Can we instead just use the string where we need it?

@youknowriad I tried to explain that in the PR summary:

> Introduces a l10n object in the editor/utils package. For now, it only contains a listItemSeparator string. In the future this could be expanded with more strings, reshaped, or even moved to a separate package if desired. Pleaae let me know if the current approach is acceptable 

I don't think we should fix it on a 'per case' basis as there are other occurrences. I created https://github.com/WordPress/gutenberg/issues/58265

Glad to move to a new package if desired. I think in the future there would be the need for _more_ l10n things but for now it's just this tiny string...

File: packages/edit-site/src/components/global-styles/font-library-modal/font-card.js [hunk 2]
```diff
@@ -58,9 +58,15 @@ function FontCard( { font, onClick, variantsText } ) {
...
-									_n( 'variant', 'variants', variantsCount ) }
+								sprintf(
+									/* translators: %d: Number of font variants. */
+									_n(
+										'%d variant',
+										'%d variants',
+										variantsCount
+									),
+									variantsCount
+								) }
```
Comment (matiasbenedetto) [inline packages/edit-site/src/components/global-styles/font-library-modal/font-card.js:69]: Nice addition, thanks.

File: packages/editor/src/utils/l10n.js (hunk 1 above)
Comment (matiasbenedetto) [reply packages/editor/src/utils/l10n.js]: For this particular case,  I think it will make the code simpler if we use just the string `.tff, .otf, .woff, .woff2`. The loop to iterate over the file extensions is not necessary and it seems like an overkill because that info is unlikely to changes for a good amount of time.

File: packages/edit-site/src/components/global-styles/font-library-modal/local-fonts.js [hunk 3]
```diff
@@ -31,11 +32,11 @@ function LocalFonts() {
...
-	const supportedFormats =
-		ALLOWED_FILE_EXTENSIONS.slice( 0, -1 )
-			.map( ( extension ) => `.${ extension }` )
-			.join( ', ' ) +
-		` ${ __( 'and' ) } .${ ALLOWED_FILE_EXTENSIONS.slice( -1 ) }`;
+	const { listItemSeparator } = l10n;
+
+	const supportedFormats = ALLOWED_FILE_EXTENSIONS.map(
+		( extension ) => `.${ extension }`
+	).join( listItemSeparator );
```
Comment (matiasbenedetto) [inline packages/edit-site/src/components/global-styles/font-library-modal/local-fonts.js]: This seems like an overkill because this info is unlikely to change.

Comment (afercia) [reply packages/edit-site/src/components/global-styles/font-library-modal/local-fonts.js]: Glad to simplify all of that and just provide a string, agree it's a bit overkill.

**Review by matiasbenedetto — APPROVED** [review]
The translation strings are looking better. Thanks for this improvement. LGTM

**Comment by afercia** [comment]
Thanks for the review.

**Comment by afercia** [comment]
Rebased after changes from https://github.com/WordPress/gutenberg/pull/58180 
Waiting for the tests to pass.
