### PR TITLE
Block API: Replace JSON-escaped quotation mark with unicode escape sequence

### LINKED ISSUE #6181: PlainText block not properly escaping attributes object in db
## Issue Overview

* WordPress 4.9.5.
* Gutenberg 2.6.0.
* No other plugins, etc. running.

When registering a custom block type that uses the PlainText block, the object saved into the `post_content` database field is not a properly escaped JSON object.

## Steps to Reproduce (for bugs)

I created a very simple plugin to test the usability of a simple `textarea` block for entering just plain text. The relevant JavaScript is as follows:

```
        wp.blocks.registerBlockType( 'my-custom/gutenberg-plain', {

                title: 'Plain Textarea',

                icon: 'format-aside',

                category: 'common',

                attributes: {
                        content: {
                                type: 'string'
                        }
                },

                edit: function ( props ) {
                        return wp.element.createElement(
                                wp.blocks.PlainText, {
                                        className: props.ClassName,
                                        value: props.attributes.content,
                                        onChange: function ( content ) {
                                                props.setAttributes( { content: content } );
                                        }
                                }
                        );
                },

                save: function () {
                        return null;
                }

        } );
```

This works fine. I can create a text block, enter the text and it stores it. In my case I'm using a `render_callback` to take the `content` attribute and manipulate it before displaying it on the front end. So entering this text in the editor works:

```
This is a sample of some plain text entered into a custom block.
```

But entering this type of text breaks things when WordPress tries to load the attributes later:

```
This is a sample of some "plain text" entered into a "custom block".
```

The problem is if I include any character that has a special meaning in a JSON object: `"`~~, `'`, `[`, `]`, `{`, `}`~~

**Edit:** Looks like it's just the double-quotes that are the problem and it appears the breakdown is [here](https://github.com/WordPress/gutenberg/blob/727da2c415f1768f7aa681fff6f9accbd9177d00/blocks/api/serializer.js#L135).

These characters are **not** escaped in the object when it's saved to the database, so when the attributes are reloaded (either to edit the post or display on the frontend), reading the object fails and therefore no content is provided (either in the editor or in the frontend).

## Expected Behavior

Database `post_content` should look like this:

```
<!-- wp:my-custom/gutenberg-plain {"content":"This is a sample of some \u0022plain text\u0022 entered into a \u0022custom block\u0022."} -->
```
## Current Behavior

Instead database content looks like this:

```
<!-- wp:my-custom/gutenberg-plain {"content":"This is a sample of some "plain text" entered into a "custom block"."} -->
```

## Possible Solution

Properly escape the correct characters when building the object.

### PR DESCRIPTION
**Pull request by aduth**
Fixes #6181

This pull request seeks to resolve an issue where contributors who submit a block containing an (escaped) quotation mark in the serialized attributes would have the resulting post content become malformed. The specific behavior results during post sanitization, which for users without `unfiltered_html` capability includes a number more filters. In particular, the [`wp_kses_stripslashes` function](https://developer.wordpress.org/reference/functions/wp_kses_stripslashes/) causes escaped JSON quotes to become unescaped, thus resulting in an invalid parse in the next editor session.

__Implementation notes:__

It was proposed at https://github.com/WordPress/gutenberg/issues/6181#issuecomment-387062185 to use entity-encoding on the quotation mark. However, this can result in a jarring end-user experience, where the encoded version would be displayed on next load:

encoding

__Testing instructions:__

Repeat steps to reproduce from https://github.com/WordPress/gutenberg/issues/6181#issuecomment-387057513 , verifying that the unicode escape sequence is saved to post content and that the post restores itself correctly upon refresh.

### CODE REVIEW

File: blocks/api/serializer.js [hunk 1]
```diff
@@ -149,12 +149,29 @@ export function getCommentAttributes( allAttributes, blockType ) {
...
+		// Don't break non-standard-compliant tools.
+		.replace( /</g, '\\u003c' )
+		.replace( />/g, '\\u003e' )
+		.replace( /&/g, '\\u0026' )
+
+		// Bypass server stripslashes behavior which would unescape stringify's
+		// escaping of quotation mark.
+		//
+		// See: https://developer.wordpress.org/reference/functions/wp_kses_stripslashes/
+		.replace( /\\"/g, '\\u0022' );
```
Comment (dmsnell) [inline blocks/api/serializer.js]: Can we find a corresponding translation in the parser? I'm nervous about introducing asymmetries in the parser/printer system that could confuse people or introduce inconsistencies. For example, what happens if we want to write `\"` in a code block? Would it be preserved or transformed into `\u0022`?

Is there a way we can transform the quotation mark on save so that it never gets mangled by the WordPress backend?

Comment (aduth) [reply blocks/api/serializer.js]: >I'm nervous about introducing asymmetries in the parser/printer system that could confuse people or introduce inconsistencies.

To be fair, is it being introduced? What about the other replacements here? I ask partly because I was hoping to find precedent in the parser 😄 

>Is there a way we can transform the quotation mark on save so that it never gets mangled by the WordPress backend?

I don't have the knowledge to speak to whether it's viable, but the documentation of the [`wp_kses_stripslashes` function](https://developer.wordpress.org/reference/functions/wp_kses_stripslashes/) reads like a hacky fix ("It’s really weird, but the quoting from preg_replace(//e) seems to require this") that could potentially do for a better solution more accommodating of the slash'd quote.

Comment (dmsnell) [reply blocks/api/serializer.js]: > To be fair, is it being introduced? What about the other replacements here? I ask partly because I was hoping to find precedent in the parser 😄

Huh. Well in my head there was precedence. Maybe it was primarily the HTML itself which was the other half of the equation.

If we can store that value in a code block and have it remain the same through the whole cycle then I think we're fine.

_/me digs around to find those unserializers…_

Comment (aduth) [reply blocks/api/serializer.js]: By default this wouldn't impact a code block, since it's only relevant for the JSON-serialized attributes. The code block sources its content from the markup. Manually updating the block to use comment attributes, the escaped form becomes:

```html
<!-- wp:code {"content":"$foo = \u0022my \\\u0022escaped\\\u0022 string\u0022;"} -->
<pre class="wp-block-code"><code>$foo = "my \"escaped\" string";</code></pre>
<!-- /wp:code -->
```

Which apparently the parser converts back to its non-unicode form when restored:

```json
{
  "blockName": "core/code",
  "attrs": {
    "content": "$foo = \"my \\\"escaped\\\" string\";"
  },
  "innerBlocks": [],
  "innerHTML": "\n<pre class=\"wp-block-code\"><code>$foo = \"my \\\"escaped\\\" string\";</code></pre>\n"
}
```

Further interesting to note is that the original problem (slash stripping) doesn't exist with the code block as implemented currently. I think it has to do with the behavior of [`wp_kses_split`](https://developer.wordpress.org/reference/functions/wp_kses_split/) which only operates on text within HTML comments (i.e. serialized block attributes) or within the opening tags, not the content between the opening and closing tag.

Comment (aduth) [reply blocks/api/serializer.js]: Let me see if it'll be simple enough to write a unit test for this.

Comment (aduth) [reply blocks/api/serializer.js]: Added in cc34b0e.

**Review by noisysocks — APPROVED** [review]
Followed the testing steps locally—looks good! 👍

**Comment by aduth** [comment]
Thanks for reviewing @noisysocks ! As with #6620, I'll plan to land this shortly after the upcoming 3.0 release.

**Comment by gziolo** [comment]
> Thanks for reviewing @noisysocks ! As with #6620, I'll plan to land this shortly after the upcoming 3.0 release.

I think I saw that one in the past. Not much time left before 3.1. Let's give it a spin before we start looking for a regression introduced after 3.0 :D
