### PR TITLE
Fix dependency extraction webpack v5 deprecation

### LINKED ISSUE #27984: webpack dependency extraction: deprecation warnings on webpack 5
**Describe the bug**
When using the dependency extraction webpack plugin with webpack 5, I'm getting  the following warnings:

* `[DEP_WEBPACK_EXTERNALS_FUNCTION_PARAMETERS] DeprecationWarning: The externals-function should be defined like ({context, request}, cb) => { ... }`
* `[DEP_WEBPACK_CHUNK_MODULES_ITERABLE] DeprecationWarning: Chunk.modulesIterable: Use new ChunkGraph API`
* `[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.`
* `[DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET_PUSH] DeprecationWarning: chunk.files was changed from Array to Set (using Array method 'push' is deprecated)`

Code in question:

https://github.com/WordPress/gutenberg/blob/6dc0b14fe7f983318421dcf3c3f7a2cf02ed3965/packages/dependency-extraction-webpack-plugin/lib/index.js#L48-L49

https://github.com/WordPress/gutenberg/blob/6dc0b14fe7f983318421dcf3c3f7a2cf02ed3965/packages/dependency-extraction-webpack-plugin/lib/index.js#L138-L145

https://github.com/WordPress/gutenberg/blob/6dc0b14fe7f983318421dcf3c3f7a2cf02ed3965/packages/dependency-extraction-webpack-plugin/lib/index.js#L186-L190

**To reproduce**
1. Run `npx webpack ...` orr `node --trace-deprecation node_modules/webpack/bin/webpack.js`

**Expected behavior**

No deprecation warnings should be emitted.

**Screenshots**

**Editor version (please complete the following information):**
- `@wordpress/dependency-extraction-webpack-plugin` version: 2.9.0
- `webpack` version: 5.11.1

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

### PR DESCRIPTION
**Pull request by ismaeldcom**
## Description
Get rid of webpack v5 deprecation, supporting also v4. Using conditionals checks to implement solutions for both versions
This should fix #27984. And allow other projects using this package to update to v5 safely.
## How has this been tested?
Appreciate a hand here to properly test it. I checked the following cases:
- Tests runs without issues.
- Used it in WC Pay with both v4 and v5 without issues.

## Types of changes
**Bug fix** -  The support for webpack v5 is now completed, fixing all warnings about deprecation.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by gziolo** [comment]
@sirreal and @jsnajdr, what do you think about the proposed approach?

We could also take a different route and upgrade webpack to v5 in Gutenberg and WordPress core and stop supporting webpack v4 in this plugin.

**Comment by sirreal** [comment]
I'm not up to speed on webpack 5 or the changes that may be necessary. I'll defer to @jsnajdr.

File: packages/dependency-extraction-webpack-plugin/lib/index.js [hunk 1]
```diff
@@ -104,116 +111,139 @@ class DependencyExtractionWebpackPlugin {
...
-			] of compilation.entrypoints.entries() ) {
-				const entrypointExternalizedWpDeps = new Set();
-				if ( injectPolyfill ) {
-					entrypointExternalizedWpDeps.add( 'wp-polyfill' );
+		if ( isWebpack4 ) {
+			compiler.hooks.emit.tap( this.constructor.name, ( compilation ) =>
+				this.addAssets( compilation, compiler )
+			);
+		} else {
+			compiler.hooks.thisCompilation.tap(
```
Comment (jsnajdr) [inline packages/dependency-extraction-webpack-plugin/lib/index.js:119]: `compiler.hooks.compilation` should also be OK. The difference is that `thisCompilation` is not passed down to child compilations.

File: packages/dependency-extraction-webpack-plugin/lib/index.js [hunk 2]
```diff
@@ -104,116 +111,139 @@ class DependencyExtractionWebpackPlugin {
...
+				this.constructor.name,
+				( compilation ) => {
+					compilation.hooks.processAssets.tap(
+						{
+							name: this.constructor.name,
+							stage:
+								webpack.Compilation
```
Comment (jsnajdr) [inline packages/dependency-extraction-webpack-plugin/lib/index.js]: nit: you can use `compiler.webpack.Compilation` here to remove one dependency on the `webpack` import.

File: packages/dependency-extraction-webpack-plugin/lib/index.js [hunk 3]
```diff
@@ -104,116 +111,139 @@ class DependencyExtractionWebpackPlugin {
...
+					);
+					entrypointExternalizedWpDeps.add( scriptDependency );
+				}
+			};
+
+			// Search for externalized modules in all chunks.
+			for ( const chunk of entrypoint.chunks ) {
+				const modulesIterable = isWebpack4
+					? chunk.modulesIterable
+					: compilation.chunkGraph.getChunkModules( chunk );
```
Comment (jsnajdr) [inline packages/dependency-extraction-webpack-plugin/lib/index.js:169]: There is a difference between webpack 4 and webpack 5 behavior. `chunk.modulesIterable` is sorted by module ID, while `chunkGraph.getChunkModules` returns an unsorted set/array. But it shouldn't matter because `entrypointExternalizedWpDeps` is sorted at the end.

File: packages/dependency-extraction-webpack-plugin/lib/index.js [hunk 4]
```diff
@@ -104,116 +111,139 @@ class DependencyExtractionWebpackPlugin {
...
+			else runtimeChunk.files.add( assetFilename );
+		}
+
+		if ( combineAssets ) {
+			// Assert the `string` type for output path.
+			// The type indicates the option may be `undefined`.
+			// However, at this point in compilation, webpack has filled the options in if
+			// they were not provided.
 				const outputFolder = /** @type {{path:string}} */ ( compiler
 					.options.output ).path;
```
Comment (jsnajdr) [inline packages/dependency-extraction-webpack-plugin/lib/index.js]: This statement is incorrectly indented. Running Prettier on the file will solve it. The Static Analysis CI check is failing because of this.

File: packages/dependency-extraction-webpack-plugin/lib/index.js [hunk 5]
```diff
@@ -104,116 +111,139 @@ class DependencyExtractionWebpackPlugin {
...
-				// they were not provided.
+			const assetFilename = buildFilename.replace(
+				/\.js$/i,
+				'.asset.' + ( outputFormat === 'php' ? 'php' : 'json' )
+			);
+
+			// Add source and file into compilation for webpack to output.
+			compilation.assets[ assetFilename ] = new RawSource( assetString );
+			if ( isWebpack4 ) runtimeChunk.files.push( assetFilename );
+			else runtimeChunk.files.add( assetFilename );
```
Comment (jsnajdr) [inline packages/dependency-extraction-webpack-plugin/lib/index.js]: I would personally write this as:
```js
runtimeChunk.files[ isWebpack4 ? 'push' : 'add' ]( assetFilename );
```

**Review by jsnajdr — APPROVED** [review]
I like this. And learned a lot about webpack 5 and its Chunk Graph while reviewing. Left just a few minor comments.

**Comment by gziolo** [comment]
@ismaeldcom, do you plan to address feedback shared in the review? 

> The Static Analysis CI check is failing because of this.

This issue block merging this PR.

**Comment by ismaeldcom** [comment]
@gziolo Yes! I was AFK until today, just catching up with everything 🙂

File: packages/dependency-extraction-webpack-plugin/lib/index.js (hunk 2 above)
Comment (ismaeldcom) [reply packages/dependency-extraction-webpack-plugin/lib/index.js]: Addressed in 7ee8995

File: packages/dependency-extraction-webpack-plugin/lib/index.js (hunk 4 above)
Comment (ismaeldcom) [reply packages/dependency-extraction-webpack-plugin/lib/index.js]: 🤦 I had the formatter disabled in the editor. Addressed in d8e4832

File: packages/dependency-extraction-webpack-plugin/lib/index.js (hunk 5 above)
Comment (ismaeldcom) [reply packages/dependency-extraction-webpack-plugin/lib/index.js]: @jsnajdr Thanks for all your comments, appreciate your help!
Addressed in c97fc55

**Comment by gziolo** [comment]
Thank you for a quick response. CI is green so let's give it a try. I trust you both @jsnajdr and @ismaeldcom 😄
