### PR TITLE
Fix navigation editor missing appender not showing appender when no blocks selected

### LINKED ISSUE #31276: Navigation Screen: Always show appender
## What problem does this address?

The default menu on the navigation screen doesn't show the appender:

Screenshot 2021-04-28 at 12 28 05

Not until the menu is selected:

Screenshot 2021-04-28 at 12 28 35

This is the default behavior for inner-blocks, and the the navigation, even on this screen, is technically a block.

## What is your proposed solution?

Extracting from https://github.com/WordPress/gutenberg/pull/31228#issuecomment-827964020, maybe that plus should show up by default, even without the navigation block being selected first.

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #31276

This fix is frustratingly complex.

The main problem is that the navigation block has its own custom logic for appender visibility, which conflicts with the desired behavior for the navigation editor.

The secondary problem is that even without the navigation block's custom logic, the block editor's default appender wouldn't be displayed anyway. When all blocks are deselected the block editor would usually show an appender at the root level, but not if that root level is a locked template, which is the case in the navigation editor.

This PR fixes things by supplying a completely custom appender implementation to the Navigation Block—yet another place where the block is being extend by the editor.

But at least with this situation, the navigation editor is in complete control of when the appender is shown, and this logic can be changed to whatever is desired now, even the appearance of the appender could be changed.

## How has this been tested?
1. Create a menu and choose 'Start blank'
2. Deselect the nav block

Expected: the appender should still be visible

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-library/src/navigation/edit.js [hunk 1]
```diff
@@ -145,19 +148,24 @@ function Navigation( {
 
 	const placeholder = useMemo( () => <PlaceholderPreview />, [] );
 
+	// When the block is selected itself or has a top level item selected that
+	// doesn't itself have children, show the standard appender. Else show no
+	// appender.
+	const appender =
+		isSelected ||
+		( isImmediateParentOfSelectedBlock && ! selectedBlockHasDescendants )
+			? undefined
```
Comment (talldan) [inline packages/block-library/src/navigation/edit.js:157]: It turns out that `InnerBlock.DefaultAppender` isn't a thing, it resolves as `undefined`, so I've just put `undefined` here 😆

File: packages/block-editor/src/components/inner-blocks/button-block-appender.js [hunk 2]
```diff
@@ -9,9 +14,13 @@ export const ButtonBlockAppender = ( {
 	showSeparator,
 	isFloating,
 	onAddBlock,
+	isToggle,
 } ) => {
 	return (
 		<BaseButtonBlockAppender
+			className={ classnames( {
+				'block-list-appender__toggle': isToggle,
```
Comment (talldan) [inline packages/block-editor/src/components/inner-blocks/button-block-appender.js:22]: There's some code smell with this classname, it was added to `BlockListAppender` at some point in the past, but it should really be part of the `ButtonBlockAppender` component. It's also missing the `block-editor` prefix. I'll work on a separate PR to fix it.

File: packages/edit-navigation/src/components/editor/style.scss [hunk 3]
```diff
@@ -164,4 +164,12 @@
...
 		}
 	}
+
+	// Override behavior that hides the navigation block's appender when it's selected.
+	.block-editor-block-list__block:not(.is-selected):not(.has-child-selected):not(.block-editor-block-list__layout) {
+		.block-editor-block-list__layout > .block-list-appender .block-list-appender__toggle {
+			opacity: unset;
+			transform: unset;
+		}
+	}
```
Comment (talldan) [inline packages/edit-navigation/src/components/editor/style.scss:174]: The block editor also has CSS to hide the appender, so that needs to be unset.

**Review by getdave — APPROVED** [review]
Looks good and thanks for working on this. 

One thing I noticed is that the inserter seems to change position once you've inserted a block

#### Before

No whitespace either side and aligned left.
Screen Shot 2021-09-10 at 11 55 37

#### After 

Lots of whitespace either side here...

Screen Shot 2021-09-10 at 11 55 22

**Comment by talldan** [comment]
Thanks for the review! The styling improvements just merged in #34281 should fix the issue with the appender position.
