### PR TITLE
Fix inserter expecting experimental settings to exist in the context

### LINKED ISSUE #24051: Storybook playground is broken
**Describe the bug**
Storybook playground is broken. https://wordpress.github.io/gutenberg/?path=/story/docs-introduction--page I also tried building latest release (at this time https://github.com/WordPress/gutenberg/releases/tag/v8.5.1) locally and I encountered same error.

I am looking at integrating standalone version of gutenberg inside my react based application so I followed the setup from storybook when I encountered this error. I was able to setup this once before and everything worked. I have the [project and yarn.lock](https://github.com/capJavert/gutenberg-standalone) here if you want to checkout the last version that worked for me.

What can we do to fix this?

**To reproduce**
1. Go to https://wordpress.github.io/gutenberg/?path=/story/playground-block-editor--default
2. Click on "Add block" button.
3. See error `Cannot read property 'length' of undefined`

**Expected behavior**
A new block is added inside editor area.

**Screenshots**
image

**Editor version (please complete the following information):**
- This error is happening inside storybook playground released [here](https://wordpress.github.io/gutenberg/?path=/story/playground-block-editor--default).

**Desktop (please complete the following information):**
 - any OS or browser

### PR DESCRIPTION
**Pull request by diegohaz**
closes #24051  

While reviewing [this PR](https://github.com/Automattic/wp-calypso/pull/44801#discussion_r470064423) that's trying to integrate the block editor directly in WP Calypso, I noticed that the inserter is expecting these experimental settings to exist in the context: `__experimentalBlockPatterns` and `__experimentalBlockPatternCategories`. Which doesn't seem correct, especially since they're experimental.

This PR changes it so they use empty arrays by default. But please let me know if there's a better way to handle this. :)

### CODE REVIEW

File: packages/block-editor/src/components/inserter/hooks/use-patterns-state.js [hunk 1]
```diff
@@ -21,8 +21,8 @@ import { __, sprintf } from '@wordpress/i18n';
 const usePatternsState = ( onInsert ) => {
 	const { patternCategories, patterns } = useSelect( ( select ) => {
 		const {
-			__experimentalBlockPatterns,
-			__experimentalBlockPatternCategories,
+			__experimentalBlockPatterns = [],
+			__experimentalBlockPatternCategories = [],
```
Comment (youknowriad) [inline packages/block-editor/src/components/inserter/hooks/use-patterns-state.js:25]: There's a file called `defaults.js` in the "store" folder of block-editor that is meant to be used for these initializations. Maybe we should use it instead to avoid the need for default values in all places where we use these?

**Review by youknowriad — APPROVED** [review]
Thanks for the fix.
