### PR TITLE
Block Directory: Silently avoid re-installing local blocks

### LINKED ISSUE #24560: Block Directory: Installed blocks show up in the block directory results
**Describe the bug**
Blocks found in the block directory that are already installed are not treated differently than uninstalled blocks. If you search for a term that does not match the local block, but does match the criteria for the block directory, the installed block will appear as an option to install.

If the user clicks "Add Block", this technically works, but does show an error in console, trying to request a page that doesn't exist (ex: `http://trunk.wordpress.test/wp-admin/undefined`). I'm guessing that has to do with the [code to load new assets into the page.](https://github.com/WordPress/gutenberg/blob/e4931d8e536fb9ff69f0b9454e29139f9fe4ef5b/packages/block-directory/src/store/controls.js#L84-L89)

**To reproduce**
1. Install & activate [the "waves" block plugin](https://wordpress.org/plugins/waves/)
2. Edit a post, open the block inserter
3. Search for "gradients"
4. Waves and Starscape are both returned, but there's no indication that Waves is already installed

**Expected behavior**
Either the block in the regular block list should be shown, or the block directory entry should indicate that this is already installed. Or maybe nothing should change in the UI, and only the "add block" action should change?

Another approach could be finding out why "gradients" matches waves on wp.org, but not in the editor, and bringing that into line.

**Screenshots**
Waves is already installed, but it shows up to add here:

Screen Shot 2020-08-13 at 4 21 51 PM

### PR DESCRIPTION
**Pull request by ryelle**
See #24911, Fixes #24560 — it's possible to get block directory results for locally installed blocks if you use slightly different keywords (ex `maps` in place of `map`). If this happens, you can try to "Add Block", but the install process will trigger an error. Instead of trying to re-install an existing block, this PR silently switches to the regular insert block flow, so the block is added to the page.

In combination with #28301, this should fix the unreliability described in #24911.

**Testing**

1. Install the [Star Rating block](https://wordpress.org/plugins/star-rating-block/)
2. In the inserter, search for "rating"
3. Star Rating is found, and can be inserted as normal
4. In the inserter, search for "review"
5. The local block "Star Rating" is not found, but it is a result in the Block Directory- since review is in the description. See #28301 
6. Click "Add Block" next to Star Rating, it should bypass the install process and add the block to the page

## Screenshots

Screen Shot 2021-01-18 at 3 00 18 PM

### CODE REVIEW

File: packages/block-directory/src/components/downloadable-blocks-list/index.js [hunk 1]
```diff
@@ -35,12 +36,16 @@ function DownloadableBlocksList( { items, onHover = noop, onSelect } ) {
 					<DownloadableBlockListItem
 						key={ item.id }
 						onClick={ () => {
-							installBlockType( item ).then( ( success ) => {
-								if ( success ) {
-									onSelect( item );
-									setIsInserterOpened( false );
-								}
-							} );
+							if ( getBlockType( item.name ) ) {
```
Comment (StevenDufresne) [inline packages/block-directory/src/components/downloadable-blocks-list/index.js:39]: Maybe it's worth a comment here since the function relies on knowledge of the `getBlockType` functionality that lives outside of this package.

Comment (StevenDufresne) [reply packages/block-directory/src/components/downloadable-blocks-list/index.js:39]: Or set the response to a variable:

`let alreadyInstalled = getBlockType( item.name )`

**Review by StevenDufresne — APPROVED** [review]

File: packages/block-directory/src/components/downloadable-blocks-list/index.js [hunk 2]
```diff
@@ -35,12 +36,19 @@ function DownloadableBlocksList( { items, onHover = noop, onSelect } ) {
...
+							// Check if the block is registered (`getBlockType`
+							// will return an object). If so, insert the block.
+							// This prevents installing existing plugins.
+							if ( getBlockType( item.name ) ) {
+								onSelect( item );
+							} else {
+								installBlockType( item ).then( ( success ) => {
+									if ( success ) {
+										onSelect( item );
+										setIsInserterOpened( false );
```
Comment (gziolo) [inline packages/block-directory/src/components/downloadable-blocks-list/index.js:48]: Noting that it changes the state of the inserter here but not when it's already installed. Should it align?
