### PR TITLE
Fix template part focus mode resizable editor height

### LINKED ISSUE #42226: Canvas height in focus mode should wrap document contents
I'm sure we discussed this elsewhere but I am struggling to find the issue. Apologies in advance if this is a duplicate.

---

When you enter focus mode to edit something like a header, the canvas stretches to fill the viewport. This can make it difficult to understand the boundaries of the entity you're editing:

https://user-images.githubusercontent.com/846565/177759317-4c5f936a-2be3-48bc-83dc-c95af92d4930.mp4

Ideally the canvas should wrap its contents more precisely, something like:

Screenshot 2022-07-07 at 12 09 08

### PR DESCRIPTION
**Pull request by talldan**
## What?
Fixes #42226

It seems like #38855 switching the iframe to standards mode changed a few aspects of how the iframe behaves:
- The document isn't ready immediately, and I think this results in a strange issue where `requestAnimationFrame` doesn't work. I could see it would get triggered but the callback never called. Possibly it doesn't work until the document is ready. The code that sets the height was within a `requestAnimationFrame` for throttling, so that was the first issue. I've switched to `setTimeout`
- `iframe.contentDocument.documentElement.scrollHeight` always seems to be whatever the pixel value is for `100%` height in standards mode. I've switched to `iframe.contentDocument.body.scrollHeight`.
- The timeout needs to continue being deferred until the document is ready. Otherwise `iframe.contentDocument.body` isn't defined and an error is thrown.
- The iframe itself needs a height, otherwise it will have the wrong height when the resize handles are used.

## Testing Instructions
<strike>Adds an e2e test</strike> (I did write an e2e test for this, but it was too unstable, I couldn't find a way to wait for the focus mode to finish loading and resizing, it's now removed)

1. Open the site editor.
2. Select a template part and click the 'Edit' button on the toolbar

Expected: the editable area should be the height of the content
In trunk: the editable area is the height of the viewport

### Before

https://user-images.githubusercontent.com/677833/185577675-fe8897b3-a55e-4d90-a633-b51dc87e9618.mp4

### After

https://user-images.githubusercontent.com/677833/185577437-838d83bd-ee26-4a7c-929c-18fb127b66ca.mp4

### CODE REVIEW

File: packages/edit-site/src/components/block-editor/resizable-editor.js [hunk 1]
```diff
@@ -57,20 +57,27 @@ function ResizableEditor( { enableResizing, settings, children, ...props } ) {
...
+							readyState !== 'complete'
+						) {
+							resizeHeight();
+							return;
 						}
-					);
+
+						setHeight( iframe.contentDocument.body.scrollHeight );
+						timeoutId = null;
+					}, 40 );
```
Comment (Mamaduka) [inline packages/edit-site/src/components/block-editor/resizable-editor.js]: Is `40` just an arbitrary delay here?

File: packages/edit-site/src/components/block-editor/resizable-editor.js [hunk 2]
```diff
@@ -84,9 +91,7 @@ function ResizableEditor( { enableResizing, settings, children, ...props } ) {
 				);
 				// Observing the <html> rather than the <body> because the latter
 				// gets destroyed and remounted after initialization in <Iframe>.
-				resizeObserver.observe(
-					iframe.contentDocument.documentElement
-				);
+				resizeObserver.observe( iframe.contentDocument.body );
```
Comment (Mamaduka) [inline packages/edit-site/src/components/block-editor/resizable-editor.js:99]: Should we remove the above comment since we don't observe `html` anymore?

**Review by Mamaduka — APPROVED** [review]
Thanks for picking this up, @talldan 🙇

The fix works well in my tests ✅

I couldn't debug why RAF wasn't working, but switching to `setTimeout` to defer the action makes sense.

File: packages/edit-site/src/components/block-editor/resizable-editor.js (hunk 1 above)
Comment (talldan) [reply packages/edit-site/src/components/block-editor/resizable-editor.js]: It was 25 fps, but I've decided to change it to 30fps, which should be closer to `requestAnimationFrame`.

File: packages/edit-site/src/components/block-editor/resizable-editor.js (hunk 2 above)
Comment (talldan) [reply packages/edit-site/src/components/block-editor/resizable-editor.js:99]: Thanks for spotting that, I've pushed a commit that updates the comment.

Comment (Mamaduka) [reply packages/edit-site/src/components/block-editor/resizable-editor.js:99]: Thanks

**Comment by mtias** [comment]
Thanks for fixing this one, was really degrading the experience
