### PR TITLE
[Block Library - Query Pagination Numbers]: Fix first page's link

### LINKED ISSUE #32792: Pagination query block issue
The pagination query block previous pages work. But going back to the 1st page from any of the others fails. Instead, it reloads the current page.

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description

Fixes: https://github.com/WordPress/gutenberg/issues/32792

`paginate_links` doesn't use the provided `format` when the page is `1`. This is great for the main query as it removes the extra query params making the URL shorter, but in the case of multiple custom queries is problematic. It results in returning an empty link which ends up with a link to the current page.

A way to address this is to add a `fake` query arg with no value that is the same for all custom queries. This way the link is not empty and preserves all the other existent query args.

Reference: https://developer.wordpress.org/reference/functions/paginate_links/
`$link = str_replace( '%_%', 1 == $n ? '' : $args['format'], $args['base'] );
                $link = str_replace( '%#%', $n, $link );`

## How has this been tested?
1. In page with many `Query Loop` blocks with `QueryPaginationNumbers` blocks check that by clicking another page number first, the pagination link for the first page (`1`), works as expected.
2. This can be tested with a single custom `Query` in a page as well, but it's better to have multiple `Query Loop` blocks which can be both `custom` and ones that `inherit the global query`.

## Notes
1. The issue can be replicated only when we have no other query args, because in that case the `link` is not empty - thus the `hacky` approach here to add an empty `query arg`.

I couldn't find any better alternative so a more elegant solution would be more than welcomed. We could also look at making some changes in core `paginate_links` but needs more exploration there. For example we could extend the `paginate_links` filter by passing the current `page number ($n)` and use this filter in the block??(🤔 ).

### CODE REVIEW

File: packages/block-library/src/query-pagination-numbers/index.php [hunk 1]
```diff
@@ -45,6 +45,22 @@ function render_block_core_query_pagination_numbers( $attributes, $content, $blo
...
+			 * problematic. It results in returning an empty link which ends up with
+			 * a link to the current page.
+			 *
+			 * A way to address this is to add a `fake` query arg with no value that
+			 * is the same for all custom queries. This way the link is not empty and
+			 * preserves all the other existent query args.
+			 *
+			 * @see https://developer.wordpress.org/reference/functions/paginate_links/
+			 */
+			$paginate_args['add_args'] = array( 'cst' => '' );
```
Comment (youknowriad) [inline packages/block-library/src/query-pagination-numbers/index.php:68]: What does `cst` stand for here, is it just a random useless param?

Comment (youknowriad) [reply packages/block-library/src/query-pagination-numbers/index.php:68]: I feel ideally, we should add a dedicated argument/option in `paginate_links` to disable the default behavior of skipping `format`. That said, this is fine a stopgap solution.

Comment (swissspidy) [reply packages/block-library/src/query-pagination-numbers/index.php:68]: So this causes `?cst` to be added to every link? 🤔  Seems a bit unexpected/weird.

Why not just filter `paginate_links_output`?

Theoretically it could cause some confusion if someone's already using a query arg with this name and expects it to do something else.

Could you perhaps share what the expected output is with this change?

Agreed that this should be fixed with a patch in core.

Comment (ntsekouras) [reply packages/block-library/src/query-pagination-numbers/index.php:68]: >What does cst stand for here, is it just a random useless param?

Yes.

>Theoretically it could cause some confusion if someone's already using a query arg with this name 

We can change this to whatever. That's why I didn't used a single character, as it would increase those chances. I'm open to any suggestions.

>Why not just filter paginate_links_output?

This would require parsing the html string and I'm not sure it worths it and how complicated it can get with other filters having been applied before, to other parts of this html construction. An extra variable in core should be the best solution probably.

**Comment by ntsekouras** [comment]
Should we land this as a stopgap solution then? 🤔 I'll create a core patch as well.

**Comment by ntsekouras** [comment]
Created a core patch here: https://github.com/WordPress/wordpress-develop/pull/1540

**Review by youknowriad — APPROVED** [review]
I think we should land this since Gutenberg needs to support at least two WP versions but maybe we should clarify that we can remove it once the core patch lands in an inline comment.
