### PR TITLE
Reopen sidebar when going to viewport sizes larger than medium.

### LINKED ISSUE #5586: Restore sidebar state when resizing a window
This appears to be a regression per the merge of the in-progress sidebar API. 

If you have the sidebar toggled, then resize the window to be small, the sidebar is _untoggled_. This is in contrast to the previous behavior, where the sidebar _state_ was not untoggled, the editor just entred into a mobile state, where the sidebar is a modal. 

The problem is, that the sidebar should be enabled by default on a vanilla out-of-the-box WordPress install. This is key in order for users to learn that if you dismiss the sidebar by pressing the X in the top right corner of the sidebar, you can _see_ that the cog icon is untoggled in the editor bar. This teaches users how to get the sidebar back (and we can show a pointer as well). If a user simply resizes the viewport and it disappears, this connection is less likely to happen. 

restore sidebar state on resize

Ideally the sidebar would be restored when you return to the desktop breakpoint, unless you explicitly toggle it off.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
This PR adds logic to reopen sidebar when going to viewport sizes larger than medium if it was closed because of resizing to viewport sizes lower than medium.

Fixes: https://github.com/WordPress/gutenberg/issues/5586

## How Has This Been Tested?
Start with a big screen size and the sidebar closed, resize the window to a small size see the sidebar was closed. Resize again to a big size and see the sidebar reopens was it was before we did any of the resize operations.

### CODE REVIEW

File: edit-post/store/effects.js [hunk 1]
```diff
@@ -108,11 +108,21 @@ const effects = {
 		// Collapse sidebar when viewport shrinks.
 		subscribe( onChangeListener(
 			() => select( 'core/viewport' ).isViewportMatch( '< medium' ),
-			( isSmall ) => {
-				if ( isSmall ) {
-					store.dispatch( closeGeneralSidebar() );
-				}
-			}
+			( () => {
```
Comment (youknowriad) [inline edit-post/store/effects.js]: I feel this could be written more succinctly. Is the IIFE required?

Comment (jorgefilipecosta) [reply edit-post/store/effects.js]: The `if ( sidebarToReOpenOnExpand ) {` could be removed, as it was before, but it is useful as it avoids dispatching an action to close the sidebar if it is already closed. The other conditions look necessary, unfortunately, I don't think we can remove them.

**Comment by jasmussen** [comment]
Yep. Amazing. Works as it should for me. 👍 👍 for the experience and thank you.

File: edit-post/store/effects.js [hunk 2]
```diff
@@ -108,11 +108,21 @@ const effects = {
...
+				// contains the sidebar we close when going to viewport sizes lower than medium.
+				// This allows to reopen it when going again to viewport sizes greater than medium.
+				let sidebarToReOpenOnExpand = null;
+				return ( isSmall ) => {
+					if ( isSmall ) {
+						sidebarToReOpenOnExpand = getActiveGeneralSidebarName( store.getState() );
```
Comment (youknowriad) [inline edit-post/store/effects.js]: Actually, now I understand you need the IIFE to store the previous sidebar.

**Review by youknowriad — APPROVED** [review]
LGTM 👍

**Comment by jorgefilipecosta** [comment]
Thaank you for the reviews @jasmussen and @youknowriad.
