### PR TITLE
Fix unexpected dragging triggered on spinner buttons on hover in Safari.

### LINKED ISSUE #32497: RangeControl value changes in Safari with mouse over
## Description
When using Safari on a Mac, if the RangeControl input box has focus, you can change the value simply by mousing over the up or down arrow after you have used either arrow to change the value.

## Step-by-step reproduction instructions
1. Go to: https://wordpress.github.io/gutenberg/?path=/story/components-rangecontrol--with-help
2. Click on either the up or down arrow in the text input field
3. Hover over the other arrow (or move your cursor off the clicked arrow and back onto it)

## Expected behaviour
Value only increases or decrease when the arrow is clicked

## Actual behaviour
Value increases or decreases with only the cursor hovering over the arrow

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.7.4
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: MacOS 11.4
- Browser:Safari 14.1.1

### LINKED ISSUE #37127: NumberControl: Hovering over spin buttons in Safari can trigger drag
### Description

In Safari, you can get stuck in a drag-like motion when simply hovering over the spin buttons. This happens after you click a spin button once, or after you initiate an actual drag motion in the input field.

### Step-by-step reproduction instructions

1. Go to the [Storybook](https://wordpress.github.io/gutenberg/?path=/story/components-numbercontrol--default) for `NumberControl`.
2. Click on a spin button once and let go of the mouse button.
3. Hover over the spin buttons.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/555336/144716668-fe1324e3-84dd-4b20-ad11-88192c22312d.mp4

### Environment info

Safari 15.0 (Does not reproduce in Chrome or Firefox)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by stokesman**
Upgrades react-use-gesture to the latest version (now @use-gesture/react) and uses one of its new features to avoid a Safari bug with number inputs and pointer capture.

Fix #32497 fix #37127

## Testing Instructions
1. Load the Block Editor in Safari >= 13
2. Insert a Column, Cover, Gallery or other block that has a setting that employs a NumberControl or RangeControl
3. Find the input with the spinner arrows and press them to change the value
4. Verify that hovering over the spinner arrows does nothing

## Screenshots
fix-safari-spin-button

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

File: packages/components/src/input-control/input-field.tsx [hunk 1]
```diff
@@ -168,9 +168,6 @@ function InputField(
 	const dragGestureProps = useDrag< PointerEvent< HTMLInputElement > >(
 		( dragProps ) => {
 			const { distance, dragging, event } = dragProps;
-			// The event is persisted to prevent errors in components using this
-			// to check if a modifier key was held while dragging.
-			event.persist();
```
Comment (mirka) [inline packages/components/src/input-control/input-field.tsx:173]: Was this related to the fix?

Shift-dragging still works as expected, but not sure what the original problem was. (Checking with @aaronrobertshaw from the git blame.)

**Review by mirka — COMMENTED** [review]
Thanks for fixing this!

This fix is working well for me. The only regression I noticed is that we no longer get the `ns-resize` cursor in Safari when dragging. If there's an easy enough fix we can put in this PR, then great. If not, I'm fine with bumping it to a separate issue because the bug fix is more important.

If you could add a quick changelog entry that would be great 👍 

And for the `touch-action` problem that we're getting new console warnings for, I went ahead and made a new issue (#38865).

File: packages/components/src/input-control/input-field.tsx (hunk 1 above)
Comment (stokesman) [reply packages/components/src/input-control/input-field.tsx:173]: It's related in that I noticed console errors after the change to avoid pointer capture. The errors were about `persist` not existing on `event`. At first, I added optional-chaining 41f5161410afd290a1775fe0afe82aa3bb174754 to avoid those errors. Later, I remembered we're on React 17 [so using `persist` is outdated](https://reactjs.org/docs/legacy-event-pooling.html).

Comment (aaronrobertshaw) [reply packages/components/src/input-control/input-field.tsx:173]: From memory, this was the [original issue](https://github.com/WordPress/gutenberg/issues/30073) and was related to a need to check modifier keys being held when dragging on a UnitControl or BoxControl.

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for the updates @stokesman 👍 

This is working nicely for me. I also noticed the cursor and console warning issues @mirka raised. If those are being addressed separately I don't think they should block this fix.

I can also confirm there is no regression regarding the [issue with the `BoxControl` and holding `alt` ](https://github.com/WordPress/gutenberg/issues/30073)to adjust multiple inputs at once.

Nice work!

**Comment by stokesman** [comment]
Thanks for the testing and reviews @mirka and @aaronrobertshaw 🙇 .

I would like to address the cursor regression here but I'm finding that to be quite baffling. Both the inline style on the document element and the class on the input element change as expected during the drag gesture but somehow fail to affect the cursor.

File: packages/components/src/input-control/input-field.tsx (hunk 1 above)
Comment (mirka) [reply packages/components/src/input-control/input-field.tsx:173]: Ah I see, thanks!
