### PR TITLE
Fix broken multi-block selection after block movements

### LINKED ISSUE #3226: Multi-selection with the mouse breaks after blocks have been moved
## Issue Overview

There's an issue with multi selection after blocks have been rearranged.

## Steps to Reproduce (for bugs)

- Have a number of blocks, like paragraphs, verify that multi selection with the mouse works fine
- Move a block using the arrow mover on the side
- Try to multi select again

## Expected Behavior

Multi selection works as intended.

## Current Behavior

Multi select seems to assume blocks are still in their previous position, which causes some unpredictable selection behavior.

GIF:

multiselect

### PR DESCRIPTION
**Pull request by mcsf**
Fixes #3226

## Description

Pointer-based block selection hinges on finding blocks in the pointer's path by looking at a map of _y_ coordinates. The finding algorithm expects the _y_ coordinates to be sorted from least to greatest. Once a block is moved, the node map `this.nodes` in `VisualEditorBlockList` is updated, but its order isn't, thus breaking the ability to find the closest block under the pointer when performing multi-block selection.

JS objects' key order isn't reliable anyway, so this fix sorts `this.coordMapKeys` directly.

## How Has This Been Tested?

Try reproducing the parent issue.

### CODE REVIEW

**Comment by mcsf** [comment]
Wait, I jumped the gun. This was working and now it isn't. :/

File: editor/modes/visual-editor/block-list.js [hunk 1]
```diff
@@ -133,14 +133,15 @@ class VisualEditorBlockList extends Component {
...
+		const uidToCoordMap = mapValues( this.nodes, ( node ) =>
+			node.getBoundingClientRect().top - boundaries.top );
 
 		// Cache a Y coördinate to uid map for use in `onPointerMove`.
 		this.coordMap = invert( uidToCoordMap );
 		// Cache an array of the Y coördinates for use in `onPointerMove`.
-		this.coordMapKeys = Object.values( uidToCoordMap );
+		// Sort the coördinates, as `this.nodes` will not necessarily reflect
+		// the current block sequence.
+		this.coordMapKeys = sortBy( Object.values( uidToCoordMap ) );
```
Comment (iseulde) [inline editor/modes/visual-editor/block-list.js]: Hm, aren't they? This is recalculated every time at selection start, no?

Comment (mcsf) [reply editor/modes/visual-editor/block-list.js]: `coordMapKeys` and the other temporary variables in this method are recalculated, but they all derive from `this.nodes`, which is only changed in `setBlockRef`. If you inspect `setBlockRef` calls, you'll see it doesn't fire often (e.g. new block insertion). Namely, `this.nodes` stays the same when moving blocks. And that makes sense: as an [unordered] set of nodes, it still reflects the current post, we just can't expect the keys in the map to be in a particular order.

**Review by ellatrix — APPROVED** [review]
Awesome! I think I've noticed this bug a few times, but could never track down the issue.

**Comment by jasmussen** [comment]
💖💖

Didn't have a chance to test this but thanks for working on this.
