### PR TITLE
Fix: Adding buttons should respect the preferred style

### LINKED ISSUE #27217: Buttons block: 1st button doesn't inherit the preferred default style
Describe the bug
in Button Block the "Default Style" is set to "Outline" instead of "Not set"

Steps to reproduce the behaviour:
1. Go to 'Editor'
2. Add new page
3. Click on 'add block'
4. Select the block 'Button'
5. View the options of 'Default Style' drop down
6. See error

Expected behaviour
instead of showing "Outline" in drop down we have to show "Not set" as default in drop down

Screenshots
https://prnt.sc/vovex9

Video
for more detail please view the attached video
https://www.loom.com/share/93958a6d4c3b427bad3c16a33a6af450

Editor version:
WordPress version: 5.6-RC1

Desktop:
OS: Windows
Browser chrome
Version 86.0.4240.193 (Official Build) (64-bit)

### LINKED ISSUE #31084: Buttons block: 1st button doesn't inherit the preferred default style
## Description

Button blocks don't inherit the user-defined "Default Style".
It works for the 2nd, 3rd etc button in the buttons block, but not the 1st one.

## Step-by-step reproduction instructions
1. In the editor add a new block, set its style to "Outline", then in the "Default Style" dropdown below select "Outline"
2. Add a 2nd `buttons` block, and notice that the button is not an outline.
3. Add a 2nd button inside the same buttons block you just added and notice it's styled as an outline.

## Expected behaviour
The 1st button should also inherit the default style.

### PR DESCRIPTION
**Pull request by aristath**
## Description
Fixes https://github.com/WordPress/gutenberg/issues/27217

## How has this been tested?

Testing instructions from #31084:

1. In the editor add a new block, set its style to "Outline", then in the "Default Style" dropdown below select "Outline"
2. Add a 2nd `buttons` block, and notice that the button is not an outline.
3. Add a 2nd button inside the same buttons block you just added and notice it's styled as an outline.

This PR fixes the above issue, so the 1st button has the right style.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by aristath** [comment]
This PR is still missing a commit for `.native.js`, but I won't push it yet... I feel what I did here is the wrong solution to this issue, and chances are we'll need to do it a bit more abstractly, probably in the inner-blocks component.

--------------------
EDIT: Hiding comment as it's outdated and no longer applies.

**Comment by talldan** [comment]
There's another issue with the template described in https://github.com/WordPress/gutenberg/issues/28217, so I wonder if it might be good to remove the template and look for a different way of handling empty buttons blocks.

**Comment by aristath** [comment]
The only downside if we completely remove the template is that it requires an extra click

Peek 2021-04-23 09-28

Ideally though IMO we could have something like `template: [ createBlock( 'core/button' ) ]` which would dynamically create the blocks

--------------------
EDIT: Hiding comment as it's outdated and no longer applies.

File: packages/block-library/src/buttons/edit.js [hunk 1]
```diff
@@ -42,9 +43,23 @@ function ButtonsEdit( {
 			'is-vertical': orientation === 'vertical',
 		} ),
 	} );
+	const preferredStyle = useSelect( ( select ) => {
+		const preferredStyleVariations = select(
+			blockEditorStore
+		).getSettings().__experimentalPreferredStyleVariations;
+		return preferredStyleVariations?.value?.[ 'core/button' ];
```
Comment (ntsekouras) [inline packages/block-library/src/buttons/edit.js]:
```suggestion
		return preferredStyleVariations?.value?.[ buttonBlockName ];
```

File: packages/block-library/src/buttons/edit.js [hunk 2]
```diff
@@ -42,9 +43,23 @@ function ButtonsEdit( {
...
+	}, [] );
+
 	const innerBlocksProps = useInnerBlocksProps( blockProps, {
 		allowedBlocks: ALLOWED_BLOCKS,
-		template: BUTTONS_TEMPLATE,
+		template: preferredStyle
```
Comment (ntsekouras) [inline packages/block-library/src/buttons/edit.js]: We can simplify a bit with this:
```
template: [
	[
		buttonBlockName,
		{ className: preferredStyle && `is-style-${ preferredStyle }` },
	],
],

```

**Review by ntsekouras — COMMENTED** [review]
Thanks for working on this Ari!

I've left some small comments but this works as expected.

File: packages/block-library/src/buttons/edit.native.js [hunk 3]
```diff
@@ -133,7 +140,18 @@ export default function ButtonsEdit( {
 			{ resizeObserver }
 			<InnerBlocks
 				allowedBlocks={ ALLOWED_BLOCKS }
-				template={ BUTTONS_TEMPLATE }
+				template={
+					preferredStyle
```
Comment (ntsekouras) [inline packages/block-library/src/buttons/edit.native.js]: Just make the quick update to `native` file as well and it will be good to go.

Comment (aristath) [reply packages/block-library/src/buttons/edit.native.js]: Good catch, done :+1:

**Review by ntsekouras — APPROVED** [review]
Green CI and 🚢 ! Thanks!
