### PR TITLE
Comment Template: Improve UX of inner block selection

### LINKED ISSUE #37154: Comment Template: Improve selection for the inner blocks
### Description

Originally reported in https://github.com/WordPress/gutenberg/pull/36065#pullrequestreview-821372216:

> Selecting blocks for nested comments sometimes changes the position on the screen in an unexpected way, you can observe that in the video I included:
>
> https://user-images.githubusercontent.com/699132/144412452-0e71915c-eea4-4e67-b9e2-4e3ef4114c85.mov

Confirmed in https://github.com/WordPress/gutenberg/pull/36065#issuecomment-985146916 by @michalczaplinski:

> There is some issue with block focus/selection, related to what you mentioned in your last point. Sometimes, you have to click twice or three times in order to select the relevant block inside of the Template. And sometimes. even then, the an incorrect block gets selected initially.

It might be the same issue that @andrewserong is trying to resolve for Query Loop and Post Comment in https://github.com/WordPress/gutenberg/pull/36431.

### Step-by-step reproduction instructions

1. Insert the Comments Query Loop block in the site template and make sure that it contains comments with replies.
2. Try to select inner blocks in the Comment Template block for the nested (replies) comments.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/699132/144412452-0e71915c-eea4-4e67-b9e2-4e3ef4114c85.mov

### Environment info

- `trunk` in Gutenberg
- WordPress 5.9 beta 1
- Safari on macOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by michalczaplinski**
https://user-images.githubusercontent.com/5417266/151283278-6312a36a-3d84-4e8d-947d-a22ae643cb43.mov

Fixes https://github.com/WordPress/gutenberg/issues/37154 using the same technique as used in https://github.com/WordPress/gutenberg/pull/36431. 

Instead of using the `BlockPreview` component, the Comment Template block is now using the `useBlockPreview` hook. The part that seems to improve the UX is NOT rendering the inserters after each of the blocks inside of the Comment Template.

Also renamed `firstBlock` prop to `firstComment` for clarity.

The UX seems a lot better now. Two outstanding issues that I ll tackle in following PRs:
- There is still a small flicker when deselecting the Comments Query Loop when it switches from the editor view to preview.
- Sometimes the whole Comment Template is selected instead of the individual comment.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-library/src/comment-template/edit.js [hunk 1]
```diff
@@ -53,13 +53,13 @@ function CommentTemplateInnerBlocks( {
 	);
 	return (
 		<li { ...innerBlocksProps }>
-			{ comment === ( activeComment || firstBlock ) ? (
+			{ comment === ( activeComment || firstComment ) ? (
 				children
 			) : (
-				<BlockPreview
+				<MemoizedCommentTemplatePreview
```
Comment (andrewserong) [inline packages/block-library/src/comment-template/edit.js]: This is currently only rendering the preview if it isn't the selected instance (which makes semantic sense). However, over in #36431, to remove the flicker when clicking between instances, I also needed to render the currently selected instance, but then used styling to set it to `display: none`. While it does wind up with an extra preview in the DOM, using styling to switch the visibility of the preview means that it doesn't need to be mounted from scratch, which appeared to be the expensive operation that caused the flicker.

**Review by andrewserong — COMMENTED** [review]
Nice work @michalczaplinski! This is testing pretty well 👍. I've left a comment where it might be possible to address that remaining flicker, and how we got it working in #36431. It wasn't the neatest approach, but seemed to work, in case it helps here.

For the other issue, where clicking on a block within another instance selects the parent template block instead, I _think_ this is because we're not specifically clicking on a "real" block to select it. I made an attempt at trying to workaround that in #37519 by switching off `pointer-events: none` in the block preview, and then grabbing the `clientId` of the block from within the preview — however that wound up causing confusing issues with double-ups in the sidebar inspector controls. I'm not sure if that approach is really viable, but just thought I'd mention it in case it sparks any ideas! The [comment here](https://github.com/WordPress/gutenberg/pull/37519#issuecomment-1000013791) is where I got to late last year. I'm mostly focused on a couple of other tasks at the moment, but hope to eventually get back to trying to figure it out. Of course, if you beat me to it, I'm more than happy to review / test and then copy over to the Query Loop block, too 😀

**Comment by michalczaplinski** [comment]
Thanks so much for the comments @andrewserong ! 🙂 

The approach from the https://github.com/WordPress/gutenberg/pull/36431 solves the flicker issue just fine but I wonder if there is perhaps a better way to achieve this 🤔 I think that react shouldn't really be rendering anything in between rendering the inner blocks and the preview. Maybe this is an issue with `useInnerBlocksProps()`...? Have you investigated it or tried any other approach? Any hunch would be appreciated too - I don't really want to spend too much time looking into it if you have done it already!

About https://github.com/WordPress/gutenberg/pull/37519: lt looks like there are multiple ways to achieve the same bug because we suffer from the same issue in the Comment Template (it doesn't show up consistently though) and I haven't implemented your suggestion yet 😅 .

**Comment by michalczaplinski** [comment]
###  Status update

- I've now included the suggestions from Andrew which fixes the issues with flicker which appeared when switching between different inner blocks of the Comment Template.

- Selecting the Comment Template instead of the inner block is still an issue as already mentioned.

   I'll investigate based on https://github.com/WordPress/gutenberg/pull/37519 and will make a follow up PR. 
   
I think this should be good to merge now but I'd like more eyes on this still @gziolo @DAreRodz @c4rl0sbr4v0 🙏

**Comment by andrewserong** [comment]
> Maybe this is an issue with useInnerBlocksProps()...? Have you investigated it or tried any other approach?

No, I haven't had a chance yet to dig in further, since I've been focused on other areas recently. Glad that the short-term workaround works to remove the flicker, though! But yes, it would be good to clean this up further down the track if we can.

> lt looks like there are multiple ways to achieve the same bug because we suffer from the same issue in the Comment Template

It's a very strange bug that one. I didn't manage to reproduce it in production for the Query Loop block, but only in https://github.com/WordPress/gutenberg/pull/37519... I think it'll need a bit more digging, too. 🤔

**Review by cbravobernal — COMMENTED** [review]
Code looks good!

The only issue that I found is that when I click on the first element, the reply is getting selected.

https://user-images.githubusercontent.com/37012961/152968177-67e7d47e-2cdd-4239-ad1b-592481e4744f.mov

It is an improvement of we had before, so, if you prefer to land this PR and add an issue for that "weird" selection let me know and I will approve it asap!

**Comment by gziolo** [comment]
Nice work. I agree that those issues should be addressed in as many steps as necessary. Every improvement landed is a win for users.

**Comment by michalczaplinski** [comment]
Thanks for your comments guys!


https://user-images.githubusercontent.com/5417266/153096075-77df0981-aefd-4d86-ae51-01ebf1d40655.mp4



> It is an improvement of we had before, so, if you prefer to land this PR and add an issue for that "weird" selection let me know and I will approve it asap!

Indeed, I ll try to work out the remaining issues in the next PR! :) @c4rl0sbr4v0

**Review by gziolo — APPROVED** [review]

**Review by cbravobernal — APPROVED** [review]
