### PR TITLE
Borders: Fix border style on color/width clearing and global styles fallback logic

### LINKED ISSUE #49677: Border Panel: Empty value applies solid style
### Description

With a block that supports borders, entering a border-width will apply a solid style at the same time. However, if you delete the value, the solid style remains. This does not occur when changing values individually.

**This problem is not reproduced when the latest Gutenberg is disabled.**

### Step-by-step reproduction instructions

- Insert a group block or table block.
- In the Border panel, enter 1 for Width.
- 1px border would be applied to the block.
- Remove value.
- A border of about 3px wide is applied to the block.
- Open the border and style picker.
- You will see that a solid style is selected.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/54422211/230834566-eb22a57b-f5d6-4552-88a1-07e787bd16d8.mp4

### Environment info

- WordPress Version: 6.3-alpha-55641
- Gutenberg Version: 15.5 (latest trunk)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Fixes: https://github.com/WordPress/gutenberg/issues/49677

## What?

- Move the global styles specific application of a fallback border style to the global styles border panel
- When clearing an individual border color or border width control in Global Styles, also unset the border style.

## Why?

Without correcting the application of the fallback border style, moving it to the global styles panel, borders on the individual blocks accidentally override theme.json or global styles values.

Without the tweak to unset the border style when clearing a color or width individually, the user has to reset the control via the border panel's menu to get rid of the border style that was added as a fallback.

## How?

Updates the change handling to apply an undefined border style when the width and color haven't been set. This application of a fallback will now only happen in the global styles border panel.

## Testing Instructions

1. Navigate to Site Editor > Global Styles > Blocks > Group > Border
2. Enter a border width and confirm borders are immediately displayed in the preview
3. Clear the width input and confirm the borders are removed in the preview
4. Add a border color. The borders should be back and the correct color
5. Clear the color selection and the borders should disappear again
6. Now enter a width and select a color and the `dashed` border style
7. Save the global styles
8. Switch to the block editor, select an individual Group block, and navigate to the block's styles tab
9. Enter a new custom border width only. Confirm the border is updated appropriately and maintains the dashed style
10. Clear the width, and test that a color selection also maintains the dashed style
11. Switch back to the Site Editor and reset the global styles
12. Back in the Block Editor, select the Group block again, and navigate to the Styles tab
13. Enter a border width only and confirm a border is visible
14. Clear the border width and the border should disappear
15. Select a border color only (custom & preset) and confirm border is visible
16. Clear the color and the border should disappear again
17. Set a complete border and confirm border displays appropriately
18. Check it all on the frontend.

## Screenshots or screencast 

https://user-images.githubusercontent.com/60436221/231976160-aea124ac-e727-4927-a8bd-3efdc2dda613.mp4

### CODE REVIEW

File: packages/block-editor/src/components/global-styles/border-panel.js [hunk 1]
```diff
@@ -50,10 +50,16 @@ function applyFallbackStyle( border ) {
...
 	}
 
-	if ( ! border.style && ( border.color || border.width ) ) {
+	const hasColorOrWidth = border.color || border.width;
+
+	if ( ! border.style && hasColorOrWidth ) {
 		return { ...border, style: 'solid' };
 	}
 
+	if ( border.style && ! hasColorOrWidth ) {
```
Comment (ramonjd) [inline packages/block-editor/src/components/global-styles/border-panel.js]: Is it possible that a user would want to set a border style and nothing else? Perhaps the border width/color is coming from a theme CSS or other external source?

As it is, selecting only a border style for a block doesn't add that style to the attributes (so I can't save)

**Review by ramonjd — COMMENTED** [review]
Looks good to me. Thanks for the quick fix. 

It addresses the bug reported in https://github.com/WordPress/gutenberg/issues/49677 and preserves the original intention behind showing a default width and

|  This branch | Trunk  |
| ------------- | ------------- |
|  |   |

I just had one question in relation to allowing users to set a style (and nothing else). 

I wasn't sure whether it was covered by the comment under "Next Steps" in the PR description.

> Only apply the fallbacks for the Global Styles border panel as this prevents individual blocks from inheriting from a global border style

File: packages/block-editor/src/components/global-styles/border-panel.js (hunk 1 above)
Comment (aaronrobertshaw) [reply packages/block-editor/src/components/global-styles/border-panel.js]: Thanks for flagging this. Moving the application of the border style fallback to the global styles panel restores the ability to set a style only for the individual block where that makes sense.

**Comment by aaronrobertshaw** [comment]
Thanks for the review @ramonjd 👍 

> I just had one question in relation to allowing users to set a style (and nothing else).
>
> I wasn't sure whether it was covered by the comment under "Next Steps" in the PR description.

When we were first adding the border support to global styles, it was suggested it didn't make sense really to set a global style only. So with what was under "Next Steps", moving the application of the fallback to the Global Styles' border panel, you can set only a border style for an individual block. In Global Styles though it aligns with the earlier feedback that you need to configure an entire border starting with width or color before style.

**Comment by aaronrobertshaw** [comment]
I've rebased this onto the latest trunk to see if we can get the failing iOS e2e test to pass.

**Review by youknowriad — APPROVED** [review]
Just noting that this also suffers from the same issue that my PR had at the block level. In other words, if there's already a border style defined differently (using CSS for instance), it can be overridden. Granted that it's less impactful though.

Also, I think that we should always ask ourselves whether we're doing the right fix if the behavior between local (block inspector) and global (global styles) differ. In most cases it's not but I'm fine with this one for now. I just don't want it to create a precedent for us so we keep creating more of these edge cases.

**Comment by oandregal** [comment]
:wave: I tested this as per the instructions provided in the bug report this aims to fix https://github.com/WordPress/gutenberg/issues/49677 I cannot reproduce this fixing the issue, I still see it happening.

**Comment by aaronrobertshaw** [comment]
> I tested this as per the instructions provided in the bug report this aims to fix https://github.com/WordPress/gutenberg/issues/49677 I cannot reproduce this fixing the issue, I still see it happening.

Thanks for flagging that @oandregal, it's odd. I've rebuilt this PR branch locally and it still tests well in terms of fixing the original issue in https://github.com/WordPress/gutenberg/issues/49677. 

Here's what I see:

https://user-images.githubusercontent.com/60436221/232699992-a5e593b1-a5b3-4e34-8a35-63bd1a6dcbc0.mp4


For me:
- In the block editor: Adding only a width or color in the block editor displays a visible border, style isn't explicitly set so it inherits from global styles, clearing the width or color removes a visible border, there's no explicit style to unset either.
- In the site editor: The same behaviour is exhibited in the block editor there for individual blocks. 
- In the site editor: Selecting only a width or color in the global styles will also set an explicit border style if needed, clearing the width or color, also clears the explicit border style that was set.


Can you confirm you are still seeing the original issue and if so perhaps share some extra replication steps or a video?

**Comment by aaronrobertshaw** [comment]
Thanks for reviewing this PR @youknowriad 👍 

> Also, I think that we should always ask ourselves whether we're doing the right fix if the behavior between local (block inspector) and global (global styles) differ. In most cases it's not but I'm fine with this one for now. I just don't want it to create a precedent for us so we keep creating more of these edge cases.

I agree, that's a great question to ask and the guideline would work in most cases, just not this one until we update all the block inspector tools to use default values set from the merged global styles.

+1 for not creating more edge cases, the nuances here have already proven how confusing they can be.

> Just noting that this also suffers from the same issue that my PR had at the block level. In other words, if there's already a border style defined differently (using CSS for instance), it can be overridden. Granted that it's less impactful though.

I still think we are on different pages regarding some of the issues around borders. I've retested this PR against https://github.com/WordPress/gutenberg/pull/49714 and you can see the difference in the videos below. For testing purposes, I added the following theme.json snippet to the TwentyTwentyThree theme.

```json
	...
	"styles": {
		"blocks": {
			"core/group": {
				"border": {
					"style": "dashed",
					"color": "darkseagreen",
					"width": "5px"
				}
			},
			...
		}
	}
```

| This PR | https://github.com/WordPress/gutenberg/pull/49714 |
|---|---|
| <video src="https://user-images.githubusercontent.com/60436221/232707003-f0189047-e69a-47b6-9e90-1f422027b071.mp4" /> | <video src="https://user-images.githubusercontent.com/60436221/232706897-5ab19c39-0857-4e4e-8c9b-7d135d915456.mp4" /> |

In this PR branch, you'll note that when editing only a color or width in the block inspector for an individual block, it honours the global styles' `dashed` border style. 

In https://github.com/WordPress/gutenberg/pull/49714, you can see that setting a width or color only in the block inspector, will actually also set a `solid` style, incorrectly overriding the `dashed` style from theme.json/global styles.

When it comes to global styles, the value from theme.json is set as the default style for the border control. So in that instance, if there isn't a border style and we set a width or color, we do want a border style to be explicitly set.

Hopefully, that is clearer now.

**Comment by youknowriad** [comment]
> When it comes to global styles, the value from theme.json is set as the default style for the border control. So in that instance, if there isn't a border style and we set a width or color, we do want a border style to be explicitly set.

What I'm saying is that global styles might not be the only place where one could apply a border style, custom CSS is another one for instance and forcing a style ("solid") that a user didn't chose has the potential to override that fallback.

**Comment by aaronrobertshaw** [comment]
> What I'm saying is that global styles might not be the only place where one could apply a border style, custom CSS is another one for instance and forcing a style ("solid") that a user didn't chose has the potential to override that fallback.

That is true, the Custom CSS comes with strong recommendations that it is supposed to be a last resort for things that aren't configurable via Global Styles. Of course, no recommendations will prevent the scenario where it isn't used appropriately or the theme loads its own stylesheet.

Those scenarios would be much less common than a global style being set and someone tweaking an individual block's border. They were also deemed not worth catering for during initial feedback on the border block supports. 

So my comment about the desire for setting a border style when adjusting global styles was made from that perspective and to restore the border behaviour that existed prior to https://github.com/WordPress/gutenberg/pull/48636.

**Comment by oandregal** [comment]
> Can you confirm you are still seeing the original issue and if so perhaps share some extra replication steps or a video?

I must have done something wrong. I've tested again the block-level styles: it works beautifully now for me, and the width is no longer serialized to block. Global-level styles also works fine. :+1:

**Comment by aaronrobertshaw** [comment]
> I must have done something wrong. I've tested again the block-level styles: it works beautifully now for me, and the width is no longer serialized to block. Global-level styles also works fine. 

Thanks for taking the time to re-test this one. Appreciate it.

It's still working for me also so I'll get this merged.
