### PR TITLE
[Site Editor]: Set `html` block as freeform fallback block

### LINKED ISSUE #47212: Templates : HTML comments cause the Site Editor to crash.
## What problem does this address?
When testing https://github.com/WordPress/gutenberg/pull/38984, the modified template causes the Site Editor to crash.

To replicate:
1. Add an empty HTML comment to a template file in a block theme:
2. Open the template in the Site Editor
3. The Site Editor displays this error:

Screenshot 2023-01-17 at 16 39 29

## What is your proposed solution?
We should allow HTMLs comment in template files!

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Resolves: https://github.com/WordPress/gutenberg/issues/47212

This PR does two things:
1. Sets the `core/html` block as a fallback freeform fallback block in site editor(this is the resolution of the issue)
2. Removes the `__unstableCanInsertBlockType` for `classic` block and achieves the same behavior by not registering it.

## Testing Instructions for `html` block fallback
1. Add an HTML comment(empty or not) to a template file and/or plain html(ex `<p>Hello World</p>` in a block theme
3. Open the template in the Site Editor
4. Observe no errors are thrown and `html` blocks are used for the above.
5. Ensure no regression is introduced

## Testing Instructions for `classic` block not available in site editor
1. In site editor try to insert the `classic` block
2. Observe that is not available
3. In post editor everything should work as before

### CODE REVIEW

File: packages/edit-site/src/index.js [hunk 1]
```diff
@@ -41,32 +41,17 @@ export function initializeEditor( id, settings ) {
 	settings.__experimentalFetchRichUrlData = fetchUrlData;
 
 	dispatch( blocksStore ).__experimentalReapplyBlockTypeFilters();
-	registerCoreBlocks();
+	const coreBlocks = __experimentalGetCoreBlocks().filter(
+		( { name } ) => name !== 'core/freeform'
+	);
+	registerCoreBlocks( coreBlocks );
+	dispatch( blocksStore ).setFreeformFallbackBlockName( 'core/html' );
```
Comment (mcsf) [inline packages/edit-site/src/index.js:48]: What happens in the Widget editor and other spinoffs? 😉 

This feels hacky and exposes other underlying fragilities:

* `registerCoreBlocks` implicitly calls `setFreeformFallbackBlockName` and then we override that here by calling `setFreeformFallbackBlockName` again.
* `registerCoreBlocks` accepts an optional argument to override the default selection of block types to register. However, it doesn't take the (IMO necessary) precaution to check that `core/freeform` is actually on the list of registered blocks before setting it as the fallback.
* This solution, as I mentioned, requires all editors instances to do this kind of failure checking.
* Supposedly, `registerCoreBlocks` already does some checking (`if ( window.wp && window.wp.oldEditor ) {
`), but it is clearly insufficient.

So I would start from that condition:
* Ensure it's actually testing for the presence of TinyMCE
* Ensure that it doesn't set Freeform as the fallback if it's not included in the `blocks` array
* ... and then we'll see what is left to do :)

Comment (ntsekouras) [reply packages/edit-site/src/index.js:48]: Makes sense. I didn't think about this check  `window.wp?.oldEditor` too much and had the impression that it was not defined in site editor, but what we actually checked was only if it was a WP environment. 

In general, `registerCoreBlocks` probably does more than it should IMO and we should better handle this separately. At first I thought about adding an `option` object that the `grouping, default, etc..` blocks could be set. The problem is bigger though, as we should not only have guards here about these blocks, but also in other actions like `unregisterBlock`, etc.. because we rely in many places about these blocks to be set.

File: test/integration/fixtures/blocks/core__freeform.json [hunk 2]
```diff
@@ -1,9 +1,11 @@
 [
 	{
-		"name": "core/freeform",
+		"name": "core/missing",
```
Comment (ntsekouras) [inline test/integration/fixtures/blocks/core__freeform.json]: If we go this way, we should rethink how to adjust the tests. We could either mock `window.tinymce` or find a way to handle separately the testing for `core/freeform` fixtures by registering it.

File: packages/edit-site/src/index.js (hunk 1 above)
Comment (dmsnell) [reply packages/edit-site/src/index.js:48]: I'm probably more comfortable at the outset with calling `setFreeformFallbackBlockName`. @mcsf if not in a place like this, where would you expect people to call it?

it would make me just as happy to remove that entirely from state and instead have this statically set at editor boot.

Comment (mcsf) [reply packages/edit-site/src/index.js:48]: Yeah, I'm not really liking the tight coupling in `registerCoreBlocks`, despite what I said. It's also arguably too big a change for something implicit; that could break stuff in third-party editors, etc.

> if not in a place like this, where would you expect people to call it? it would make me just as happy to remove that entirely from state and instead have this statically set at editor boot.

Thinking aloud:

* The closest thing we have to a "standard init interface" is each editor's `initializeEditor` function. As was Nik's intuition, this is the most natural place to do this sort of imperative configuration.
* We also have editor `settings` (a two-part pipeline starting in the server as `$editor_settings` and ending in the client in `initializeEditor`). There's always the possibility of introducing optional settings for this kind of stuff instead. It's more declarative, but I'm also wary of introducing a setting when other APIs already exist (even if they are imperative).
* I think my initial reflex to fix this directly in `registerCoreBlocks` came because that function was already making implicit choices (and doing them poorly, since it wasn't properly checking for `window.tinymce`). Well, what if we separate these two problems. That is:
  - Don't try to be smart in `registerCoreBlocks`. Instead of automatically falling back to other block types, just throw a loggable error ("Cannot set xyz as fallback block type: block type not found.").
  - Thus, go back to Nik's original approach and update all of core's non-post editors so that they explicitly set their freeform handler to HTML in `initializeEditor`.
  - Fix the Classic block so that it checks for the presence of TinyMCE instead of just blindly failing.

Thoughts?

Comment (dmsnell) [reply packages/edit-site/src/index.js:48]: it all seems fine to me. `settings` seems like the same general idea I had concerning "statically set at editor boot."

> making implicit choices (and doing them poorly,

this is more or less why I'm fine with a raggy solution now, because I doubt it would very much change the existing situation or impede improvements.

if the site editor needs to replace the fallback block then it only needs to ensure that happens before a post is loaded.

getting this into a more declarative spot might take a little more thought, whereas the imperative approach already exists and announces itself basically as the way to do it right now.

---

hopefully it's clear I have almost no concern about how this change is implemented at this stage.

Comment (ntsekouras) [reply packages/edit-site/src/index.js:48]: I kept only my initial commit and it seems the other screens already did that([1](https://github.com/WordPress/gutenberg/blob/trunk/packages/customize-widgets/src/index.js#L76), [2](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-widgets/src/index.js#L92)).

Maybe we could fix this as is part of `6.2` and handle in a follow up the better handling in registerBlocks? What do you think @mcsf ?

**Review by mcsf — APPROVED** [review]
LGTM!

**Comment by mcsf** [comment]
An additional test scenario that I tried:

* In both the Post Editor and the Site Editor, paste this block into the code editor:

```
<!-- wp:freeform -->hi<!-- /wp:freeform -->
```

Expected:
* In the Post Editor, this gets automatically converted to `hi` (implicitly a freeform block)
* In the Site Editor, this is preserved as is. Then in the visual editor the missing block is properly handled and the user has the option to convert it.

**Comment by oandregal** [comment]
@ntsekouras @mcsf @dmsnell I just realized this PR existed and went to test the following use case: add an empty HTML comment (meaning no content as a child). My expectation was that the comment would be ignored. Instead, it was converted to a block.

Steps:

- Add the following to the `single.html` template of TwentyTwentyThree:

```html
<!--
        title: Title for the template or part
        area: related-area
-->
```

- Go to the site editor and navigate to the `single.html` template. This is what I see:

Captura de ecrã de 2023-02-23 17-39-18

- The front-end works as expected (doesn't render the HTML comment):

image

Would you think there's a way to follow up this PR and ignore HTML comments with no content? While the issue reported caused [a bug](https://github.com/WordPress/gutenberg/issues/47212), the original intent was that the comments would be ignored, so we can attach metadata to the template via HTML comments, as in https://github.com/WordPress/gutenberg/pull/38984

**Comment by mcsf** [comment]
@oandregal: yeah, we fixed the worst part, which was the crash, but the rendering of comments is still something to address. Could you turn your comment into an issue and link it to #47212? 🙏 

IMO, this part will be the hardest to fix if we want to fix it properly.

**Comment by oandregal** [comment]
Issue at https://github.com/WordPress/gutenberg/issues/48408

**Comment by ntsekouras** [comment]
I just cherry-picked this PR to the wp/6.2 branch to get it included in the next release: abf45f593c
