### PR TITLE
Avoid loading theme fonts twice and assume they were already resolved by the font face resolver.

### LINKED ISSUE #59352: Font Manager uses incorrect URLs on multisite
### Description

The font library manager attempts to load fonts using incorrect URLs in the font-manager when using Multisite in sub-directory mode. 

In the console when I open the font manager model the Caro and Inter fonts attempt to load from the following URLs which throw 404 errors:

* http://gb-dev.local/two/wp-admin/undefined/wp-content/themes/twentytwentyfour/assets/fonts/cardo/cardo_normal_400.woff2
* http://gb-dev.local/two/wp-admin/undefined/wp-content/themes/twentytwentyfour/assets/fonts/inter/Inter-VariableFont_slnt,wght.woff2

Elsewhere in the site editor they appear to load from the correct URLs

WordPress installed in a sub-directory will also need to be tested. 

### Step-by-step reproduction instructions

_Edit: Creating a sub-site in not necessary, the issue occurs on the main site too._

1. Configure Multisite in sub-directory mode
2. Create a sub-site `/two/`
3. Visit `host/two/wp-admin/site-editor.php?canvas=edit`
4. Open the browser's developer tools, clear the console.
5. Open Styles > Typography > Manage Fonts
6. Observe the 404 errors in your browsers console or network tab

### Screenshots, screen recording, code snippet

Screen Shot 2024-02-26 at 12 55 33 pm

### Environment info

- WordPress 6.4
- Gutenberg trunk @ 4d5fd5a01f758d19568c885fadbc9b57ba30fb2d

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
- Avoid loading theme font assets twice.
- Fix incorrect guessed URLs in some scenarios as multisite: https://github.com/WordPress/gutenberg/issues/59352
- Update tests.

## Why?
- We were loading theme font assets twice:
     1. With CSS by the backend font face resolver
     2. With Javascript  (removed in this PR for theme fonts).
- The theme fonts were already resolved by the font face resolver in the backend and printed to the page's HTML.
- Fix https://github.com/WordPress/gutenberg/issues/59352

## How?
If we deal with theme fonts:
- Don't try to load their assets to generate a demo/preview.
- Don't guess theme font face URLs.
- Assume the backed font face resolver already resolved the font face.

## Testing Instructions
- Run JS unit tests
- Use the font library with a theme that ships several font families. Check the demos of that fonts load as expected in the font library modal.

## Screenshots or screencast 
The theme fonts should render as expected here:
image

### CODE REVIEW

File: packages/edit-site/src/components/global-styles/font-library-modal/utils/index.js [hunk 1]
```diff
@@ -132,9 +138,9 @@ export function getDisplaySrcFromFontFace( input, urlPrefix ) {
 	} else {
 		src = input;
 	}
-	// If it is a theme font, we need to make the url absolute
-	if ( src.startsWith( 'file:.' ) && urlPrefix ) {
-		src = src.replace( 'file:.', urlPrefix );
+	// If it is a theme we expect the font face be already loaded in the browser.
```
Comment (peterwilsoncc) [inline packages/edit-site/src/components/global-styles/font-library-modal/utils/index.js]: WordPress tries to avoid self-referential "we" comments.

```suggestion
	// It's expected theme fonts will already be loaded in the browser.
```

**Review by peterwilsoncc — COMMENTED** [review]
This looks good to me and tests well.

Testing notes:

* Installed `adventurer` theme
* Uploaded Open Sans
* Replaced all the fonts faces to use open sans in headings, text, etc, etc
* Saved, reloaded site editor
* Confirmed that the theme font's `@font-face` definitions appeared in the site editor markup.
* Confirmed the fonts loaded once I opened the font library
* Reset to default styles
* Confirmed that open-sans loaded once I opened the font library.

**Comment by youknowriad** [comment]
This is working for me as well. I tested that installing fonts still work as expected without having to reload pages to get the styles or anything.

**Review by youknowriad — APPROVED** [review]

**Comment by youknowriad** [comment]
I just cherry-picked this PR to the update/packages-6.5-rc1 branch to get it included in the next release: 30c4f7d40d
