### PR TITLE
contentOnly patterns: Fix lock icon appearing on toolbar when editing a section

### LINKED ISSUE #72159: Block Locking: Incorrectly shows a block as locked when parent has `blockEditingMode: 'disabled'`
### Description

If a block's parent is set to a 'disabled' block editing mode, with the block itself set to a 'default' block editing mode, then the block incorrectly displays as 'locked' to the user, even allowing them to unlock the block (which does nothing as users cannot modify block editing modes).

The reason for this is that the lock feature (via the `useBlockLock` hook) checks for locking by looking at the `canMoveBlock` and `canRemoveBlock` selectors. These return `false` when the parent block is disabled.

The tricky part is that these selectors are correct, for example I'm sure `canRemoveBlock` is used in places to prevent inner blocks of `disabled` blocks being removed, and that's good. I think the lock feature is using them incorrectly, it should perhaps instead have separate selectors that reason about what the user is capable of.

### Step-by-step reproduction instructions

1. Create a post with a single paragraph that has some text in it.
2. Copy the client id of the paragraph (I usually 'Inspect element' and then grab the value of the `data-block` attribute. )
3.  In the console run the following snippet, on the second line use the client id you copied in place of 'paste-copied-client-id-here':
```js
wp.data.dispatch( 'core/block-editor' ).setBlockEditingMode( '', 'disabled' );
wp.data.dispatch( 'core/block-editor' ).setBlockEditingMode( 'paste-copied-client-id-here', 'default' );
```
4. Observe that the paragraph shows the lock icon in the toolbar, and even allows unlocking, but unlocking does nothing

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by talldan**
## What?
Fixes #72159 - the block locking UI being displayed in cases where it shouldn't.

## Why?
The bug happens because the block locking feature uses selectors like `canMoveBlock` and `canRemoveBlock`. These selectors are low level, and what the block editor uses as the source of truth for whether a block can be moved or removed. They reason about a wider range of systems that might prevent moving or removal, like block editing modes.

A user can't change block editing modes from the block locking UI, so this shouldn't be something the block locking features incorporates into its locking logic.

## How?
Introduces some new selectors that specifically reason about the types of locking the user can modify via the UI. Removes usage of selectors like `canMoveBlock`, `canRemoveBlock` and `canEditBlock` for the locking feature.

## Testing Instructions
Do a general smoke test of block locking. Some gotchas about how the feature works in trunk (and maintained in this PR):
- If you select 'Lock removal' and then 'Apply to all blocks inside', this adds `templateLock: 'insert'`. It will also prevent block insertion, though it's not clear from the UI.
- If you select any type of locking and then 'Apply to all blocks inside', you can select an inner block and remove the locking for just that one block. E.g. you can make that block movable again even when parent locks moving.

Also test that the bug is fixed:
1. Enable the 'contentOnly: Make patterns contentOnly by default upon insertion' gutenberg experiment
2. Open the post editor and insert a pattern
3. From the block inspector click 'Edit section'
4. Observe that a lock icon doesn't appear on the toolbar
5. Click 'Exit section', observe that an unlock icon doesn't appear on the toolbar.

## Screenshots or screencast 

https://github.com/user-attachments/assets/da454ea2-0e27-49b7-acaa-ee9795074846

### CODE REVIEW

File: packages/block-editor/src/components/block-lock/use-block-lock.js [hunk 1]
```diff
@@ -19,25 +20,20 @@ export default function useBlockLock( clientId ) {
...
 
 			return {
-				canEdit,
-				canMove,
-				canRemove,
+				isEditLocked: isEditLockedBlock( clientId ),
+				isMoveLocked: isMoveLockedBlock( clientId ),
+				isRemoveLocked: isRemoveLockedBlock( clientId ),
 				canLock: canLockBlockType( getBlockName( clientId ) ),
-				isContentLocked: getTemplateLock( clientId ) === 'contentOnly',
```
Comment (talldan) [inline packages/block-editor/src/components/block-lock/use-block-lock.js:39]: I couldn't see anywhere this is used, so it's deleted.

File: packages/block-editor/src/components/list-view/block.js [hunk 2]
```diff
@@ -553,7 +555,7 @@ function ListViewBlock( {
 		'is-dragging': isDragged,
 		'has-single-cell': ! showBlockActions,
 		'is-synced': blockInformation?.isSynced,
-		'is-draggable': canMove,
+		'is-draggable': canMoveBlock,
```
Comment (talldan) [inline packages/block-editor/src/components/list-view/block.js:558]: In some cases like this, it's correct to keep using the `canMoveBlock` selector. Now I use that selector directly instead of via the hook.

**Comment by ramonjd** [comment]
### Before

https://github.com/user-attachments/assets/90ddfefc-ce9a-41ac-90ce-c3f09e00ea0d



### After


https://github.com/user-attachments/assets/cb146297-f01a-4e38-ac32-7c4d1f6fc381

**Review by ramonjd — APPROVED** [review]
Bug is fixed. Smoke tested locking/unlocking on trunk and on this branch. 


I couldn't spot any regressions.

LGTM

**Review by andrewserong — APPROVED** [review]
Nicely done, this is testing great for me, too, and it makes a lot of sense having separate selectors for this 👍. The desired behaviour on trunk including locking all blocks inside, and unlocking some blocks within a parent locked block, is all still testing well for me, with the bug with spotlighted section blocks resolved.

One tiny question (not a blocker), in terms of naming, I was wondering if putting the word `block` earlier in the selector name would make it more consistent with some of the other `isBlock` selectors (like `isBlockSelected`)? So, `isBlockEditLocked`, rather than `isEditLockedBlock`. No strong opinions for me, so just a question 🙂

LGTM!
