### PR TITLE
Fix client-side media file naming

### LINKED ISSUE #75302: Ensure client side image file naming matches server
## Description

When the client-side media experiment is active, uploading or drag-and-dropping an image causes the original filename to be stripped and replaced with a generic `image` prefix. File names should ideally match what happens with the existing server side approach.

This was noted by @andrewserong during review of #74566 but is not caused by that PR — it occurs whenever the client-side media experiment is enabled.

## Steps to Reproduce

1. Enable the Client Side Media experiment (Gutenberg → Experiments → Enable Client Side Media)
2. Create or open a post in the block editor
3. Upload or drag and drop an image with a distinctive filename (e.g., `IMG_7977.jpg`)
4. Check the image details in the sidebar or Media Library

## Expected Behavior

The uploaded image and its sub-sizes should retain the original filename as a prefix (e.g., `IMG_7977-scaled.jpeg`, `IMG_7977-1024x768.jpeg`).

## Actual Behavior

The original filename is stripped and replaced with a generic `image` prefix (e.g., `image-scaled.jpeg`, `image-1024x768.jpeg`).

Screenshot from the sidebar showing the generic filename:

Image showing generic 'image' filename prefix in sidebar

Screenshot showing files created from client and server based processing of same image, note file names:

Image

## Context

Reported in: https://github.com/WordPress/gutenberg/pull/74566#pullrequestreview-3760653159

### PR DESCRIPTION
**Pull request by adamsilverstein**
## Summary

Fixes #75302

When the client-side media experiment is active, uploading or drag-and-dropping files causes the original filename to be stripped and replaced with a generic prefix (`image.jpeg`, `document.pdf`). This PR fixes two bugs:

- **Cross-realm `instanceof File` failure**: The block editor canvas renders inside an iframe. File objects from the iframe fail `instanceof File` in the parent window because each browsing context has its own `File` constructor. `convertBlobToFile()` now checks for a `name` property as a fallback, preserving the original filename for cross-realm File objects.
- **Wrong REST field name for thumbnails**: `generateThumbnails()` referenced `attachment.media_filename` which doesn't exist — the REST API field is `filename`. Thumbnails now correctly use the server-provided filename when renaming source files.

Also adds a `convert-blob-to-file.ts` unit test.

## Test plan

- [ ] Upload an image with a distinctive filename (e.g., `IMG_7977.jpg`)
- [ ] Verify the uploaded image retains the original filename prefix (e.g., `IMG_7977.jpeg`, `IMG_7977-1024x768.jpeg`)
- [ ] Upload a non-image file (e.g., `my-document.pdf`) and verify it retains its original name
- [ ] Test naming of scaled image on upload (over big image threshold size, verify matches server

### CODE REVIEW

**Comment by adamsilverstein** [comment]
@andrewserong - this PR fixed the naming bug we noticed. Currently working to address the `-scaled` suffix behavior as well which isn't quite right. I also re-enabled the feature since I think this was the main reason we disabled it. If you prefer, i can move those changes to a separate PR

**Comment by swissspidy** [comment]
> * **Wrong REST field name for thumbnails**: `generateThumbnails()` referenced `attachment.media_filename` which doesn't exist — the REST API field is `filename`. Thumbnails now correctly use the server-provided filename when renaming source files.

Looks like this originated from `mexp_filename` in media-experiments which aims to remove the suffixes. See:

https://github.com/swissspidy/media-experiments/blob/dc2267dde0984554e6de1e3ce4bf10310b8908a0/inc/functions.php#L727-L752

**Comment by adamsilverstein** [comment]
I have resolved the issue with the scaled image naming and creation; these changes will require an additional backport PR which I am working on now.

**Comment by adamsilverstein** [comment]
Core backport: https://github.com/WordPress/wordpress-develop/pull/11015

**Comment by swissspidy** [comment]
I implemented the naming in media-experiments the other way around.

Core: a large image is resized to fit threshold, the "large" version you can use gets a -scaled suffix. The unscaled original has no suffix.
Mexp: image is resized on the client, gets uploaded without any suffix. The unscaled original is uploaded with -original suffix.

This PR implies both -scaled and -original versions will be uploaded, which doesn't make sense under these circumstances.

**Comment by adamsilverstein** [comment]
> image is resized on the client, gets uploaded without any suffix. The unscaled original is uploaded with -original suffix.

I am trying to match the existing core behavior.  i'm trying to understand: why did you choose to do it this way? is there some advantage?

To match existing behavior:

I would expect the original image I uploaded to be exactly what i see when I look in `wp-content/uploads`. if i upload IMG_2300.jpg, i expect to see that same file on the server. we have always done that and shouldn't change that behavior.

the -scaled image gets _recorded in meta as the "original" (full size)_ so the very large original is never served on he front end. an additional `original_image` meta value points to the actual original image

This is what I see uploading an image with CSM disabled: (server processed)

scaled on server

I see my original file i uploaded, then all the sizes, plus the -scaled version. scaled is a new size matching the filtered setting. 

In this PR meta should be set correctly, after your feedback I will check manually and try to add a test.

> This PR implies both -scaled and -original versions will be uploaded, which doesn't make sense under these circumstances.

this PR should: upload the original, upload all the sizes and upload the -scaled version. why doesn't that make sense?

File: packages/upload-media/src/store/private-actions.ts [hunk 1]
```diff
@@ -1205,6 +1190,68 @@ export function generateThumbnails( id: QueueItemId ) {
...
+						sourceForScaled,
+						{
+							width: bigImageSizeThreshold,
+							height: bigImageSizeThreshold,
+						},
+						false, // smartCrop
+						false, // addSuffix
+						item.abortController?.signal,
+						true // scaledSuffix
+					);
```
Comment (swissspidy) [inline packages/upload-media/src/store/private-actions.ts]: Image operations like resizing should never happen "inline" like this. It should go through a proper upload queue step. That's what the `ResizeCrop` above was for.

**Comment by swissspidy** [comment]
A bit fuzzy on the details, but IIRC this was just much easier to implement. Scale down image, upload all thumbnails, and then upload the unmodified original with the prefix. No hassle with suffixes for thumbnails or anything.
(Edit: also, makes it easier to disable this logic, if you never want to upload the originals in the first place, see https://github.com/swissspidy/media-experiments/blob/dc2267dde0984554e6de1e3ce4bf10310b8908a0/packages/upload-media/src/store/private-actions.ts#L1250)

I don't mind parity with the server-side logic but then it needs some thorough e2e tests IMO.

File: packages/upload-media/src/store/private-actions.ts (hunk 1 above)
Comment (adamsilverstein) [reply packages/upload-media/src/store/private-actions.ts]: Ah, good point!

Comment (adamsilverstein) [reply packages/upload-media/src/store/private-actions.ts]: updated the approach

**Review by andrewserong — COMMENTED** [review]
This is testing nicely for me so far! Looking at the uploaded files on my file-system, they all preserve the prefix as expected with client side media activated _or_ deactivated:

Image

Other files (pdf, mp4, zip) continue to behave as expected when uploaded, too.

I can also safely disable client-side media processing via adding `add_filter( 'wp_client_side_media_processing_enabled', '__return_false' );` to a separate plugin, and that works as expected 👍 

Since this PR is proposing re-enabling client-side media process by default, should we also re-enable the cross-origin isolation e2e tests that I skipped in https://github.com/WordPress/gutenberg/pull/75764?

And did we want to add checks to skip if the user is on a low-powered or low-network device in this PR, or leave it for a follow-up?

**Comment by adamsilverstein** [comment]
> Since this PR is proposing re-enabling client-side media process by default, should we also re-enable the cross-origin isolation e2e tests that I skipped in #75764?

let me open a separate PR explicitly to re-enable client-side media process by default, and also re-enable the cross-origin isolation e2e tests. That will keep this PR a little smaller and we can try to add other fixes as well.

> 
> And did we want to add checks to skip if the user is on a low-powered or low-network device in this PR, or leave it for a follow-up?

Yes, good idea. I think we may also want to disable for Safari and Firefox initially until we can resolve any glaring compatibility issues (so fr: tinymce and maintenence mode are reported effected).

File: test/e2e/specs/editor/various/big-image-size-threshold.spec.js [hunk 2]
```diff
@@ -21,6 +21,38 @@ test.use( {
...
+	await page.waitForFunction(
+		() => {
+			const uploadStore = window.wp.data.select( 'core/upload-media' );
+			if ( ! uploadStore ) {
+				return true; // Store not available, upload happened server-side.
+			}
+			const items = uploadStore.getItems();
+			return items.length === 0;
+		},
+		{ timeout: 120000 }
```
Comment (andrewserong) [inline test/e2e/specs/editor/various/big-image-size-threshold.spec.js:42]: Tiniest of tiny nits, please feel free to ignore. Is 2 minutes a long time for this timeout?

**Review by andrewserong — APPROVED** [review]
Still testing great for me! Looks like the e2e test failures are unrelated 👍

This looks good to merge to me, nice work fixing this up! 🎉

**Comment by ockham** [comment]
I'm planning to publish another Gutenberg RC today, and I'd be happy to include this fix.

@adamsilverstein Would you mind rebasing? Ideally we can merge with CI all-green.

**Comment by ockham** [comment]
Nevermind, I'll do a quick rebase myself :)

**Comment by adamsilverstein** [comment]
Great thanks, was in my queue to work on that

**Comment by ockham** [comment]
I'll go ahead and land this so we can unblock https://github.com/WordPress/gutenberg/pull/75848 and get both into GB 22.6 RC3.

**Comment by ockham** [comment]
I just cherry-picked this PR to the release/22.6 branch to get it included in the next release: 89864fb8b66

**Comment by ockham** [comment]
@ellatrix This should probably be included in WP 7.0 as well, no?

**Comment by ellatrix** [comment]
Probably. @adamsilverstein could you apply the `Backport to WP 7.0 Beta/RC` label if it needs back porting to core? If it can't be automatically merged, it will leave instructions to manually cherry pick.
