### PR TITLE
Font Library: Refactors the upload handler in order to check if files being uploaded are valid font files.

### LINKED ISSUE #59578: Font Library uploader apparently crashes with broken font files
### Description

When a user attempts to upload a font file that is broken, the font library uploader tab apparently crashes.

Inspecting the console, an error is thrown but fails to be caught.

### Step-by-step reproduction instructions

MacOS instructions

1. Remove the first 100 bytes from a font file: `tail -c +100 OpenSans-Bold.ttf > _broken-font.ttf`
2. Open the Font Library uploader tab via the site editor
3. Attempt to upload the broken font file
4. The uploader will show the upload progress bar for the foreseeable future

### Screenshots, screen recording, code snippet

crash-uploader

### Environment info

- WordPress 6.4
- Gutenberg trunk @ 619f0a3ea612f5bc836eafb6d3cfd46175bf1d8c

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by vcanales**
## What?

Refactors the upload handler in order to check if files being uploaded are valid font files.

## Why?
Fixes: https://github.com/WordPress/gutenberg/issues/59578

Uploading invalid font files would cause the uploader to crash due to lack of error handling.

## Testing Instructions
1. Upload a broken font file.
2. The uploader should let you know that one or more of the files uploaded is not valid, and should allow you to try again immediately.

### CODE REVIEW

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js [hunk 1]
```diff
@@ -45,29 +45,50 @@ function UploadFonts() {
...
-	const handleFilesUpload = ( files ) => {
+	const handleFilesUpload = async ( files ) => {
 		setNotice( null );
 		setIsUploading( true );
 		const uniqueFilenames = new Set();
 		const selectedFiles = [ ...files ];
-		const allowedFiles = selectedFiles.filter( ( file ) => {
+		let hasInvalidFiles = false;
+
+		// Use map to create a promise for each file check, then filter with Promise.all
```
Comment (peterwilsoncc) [inline packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js]:
```suggestion
		// Use map to create a promise for each file check, then filter with Promise.all.
```

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js [hunk 2]
```diff
@@ -45,29 +45,50 @@ function UploadFonts() {
...
+		const checkFilesPromises = selectedFiles.map( async ( file ) => {
+			const isFont = await isFontFile( file );
+			if ( ! isFont ) {
+				hasInvalidFiles = true;
+				return null; // Return null for invalid files
```
Comment (peterwilsoncc) [inline packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js]:
```suggestion
				return null; // Return null for invalid files.
```

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js [hunk 3]
```diff
@@ -45,29 +45,50 @@ function UploadFonts() {
...
+			}
+			// Check for duplicates
 			if ( uniqueFilenames.has( file.name ) ) {
-				return false; // Discard duplicates
+				return null; // Return null for duplicates
```
Comment (peterwilsoncc) [inline packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js]:
```suggestion
				return null; // Return null for duplicates.
```

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js [hunk 4]
```diff
@@ -45,29 +45,50 @@ function UploadFonts() {
...
 			}
-			// Eliminates files that are not allowed
+			// Check if the file extension is allowed
```
Comment (peterwilsoncc) [inline packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js]:
```suggestion
			// Check if the file extension is allowed.
```

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js [hunk 5]
```diff
@@ -45,29 +45,50 @@ function UploadFonts() {
...
 			const fileExtension = file.name.split( '.' ).pop().toLowerCase();
 			if ( ALLOWED_FILE_EXTENSIONS.includes( fileExtension ) ) {
 				uniqueFilenames.add( file.name );
-				return true; // Keep file if the extension is allowed
+				return file; // Return the file if it passes all checks
```
Comment (peterwilsoncc) [inline packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js]:
```suggestion
				return file; // Return the file if it passes all checks.
```

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js [hunk 6]
```diff
@@ -45,29 +45,50 @@ function UploadFonts() {
...
 			}
-			return false; // Discard file extension not allowed
+			return null; // Return null for disallowed file extensions
```
Comment (peterwilsoncc) [inline packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js]:
```suggestion
			return null; // Return null for disallowed file extensions.
```

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js [hunk 7]
```diff
@@ -45,29 +45,50 @@ function UploadFonts() {
...
 		} );
+
+		// Filter out the nulls after all promises have resolved
```
Comment (peterwilsoncc) [inline packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js]:
```suggestion
		// Filter out the nulls after all promises have resolved.
```

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js [hunk 8]
```diff
@@ -94,6 +115,22 @@ function UploadFonts() {
 		handleInstall( fontFacesLoaded );
 	};
 
+	/**
+	 * Checks if a file is a valid Font file.
+	 *
+	 * @param {file} file The file to be checked
```
Comment (peterwilsoncc) [inline packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js]: My reading of the MDN docs is that it's a File not a file. 
```suggestion
	 * @param {File} file The file to be checked.
	 * @return {boolean} Whether the file is a valid font file.
```

**Review by peterwilsoncc — APPROVED** [review]
This looks good to me and test well.

I've got a few nitpicks in to match the [documentation standards](https://developer.wordpress.org/coding-standards/inline-documentation-standards/javascript/#inline-comments) and add a return type to the docblock.

Pre-approving as the code is LGTM.

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js [hunk 9]
```diff
@@ -45,29 +45,50 @@ function UploadFonts() {
...
+	const handleFilesUpload = async ( files ) => {
 		setNotice( null );
 		setIsUploading( true );
 		const uniqueFilenames = new Set();
 		const selectedFiles = [ ...files ];
-		const allowedFiles = selectedFiles.filter( ( file ) => {
+		let hasInvalidFiles = false;
+
+		// Use map to create a promise for each file check, then filter with Promise.all
+		const checkFilesPromises = selectedFiles.map( async ( file ) => {
```
Comment (t-hamano) [inline packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js:56]: I think it could probably be made a little simpler.

```javascript
const allowedFiles = (
	await Promise.all(
		selectedFiles.map( async ( file ) => {
			// ...
		} )
	)
).filter( Boolean );
```

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js [hunk 10]
```diff
@@ -45,29 +45,50 @@ function UploadFonts() {
...
+		const allowedFiles = ( await Promise.all( checkFilesPromises ) ).filter(
+			( file ) => file !== null
+		);
+
 		if ( allowedFiles.length > 0 ) {
 			loadFiles( allowedFiles );
 		} else {
+			const message = hasInvalidFiles
+				? __(
+						'One or more of the selected files are not valid fonts. Please, try again.'
```
Comment (carolinan) [inline packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js]: Nit :) All other occurrences of "Please try again" in the plugin and in core does not use a comma between please and try.

**Comment by carolinan** [comment]
_Not a code review._
I followed the test instructions and the error message displays correctly in the modal. And I do not see an error in the console anymore.

Error message displaying in the Font Library modal.

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js (hunk 9 above)
Comment (vcanales) [reply packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js:56]: I agree that it's an elegant way to use `.filter`, but I think that since we are explicitly trying to filter out `null` files, it's clearer for the reader to add the specific condition instead of a blanket `Boolean`.

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js [hunk 11]
```diff
@@ -45,29 +45,50 @@ function UploadFonts() {
...
+
 		if ( allowedFiles.length > 0 ) {
 			loadFiles( allowedFiles );
 		} else {
+			const message = hasInvalidFiles
+				? __(
+						'One or more of the selected files are not valid fonts. Please try again.'
+				  )
+				: __( 'No valid fonts found to install.' );
+
```
Comment (vcanales) [inline packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js]: @getdave I'm adding a separate error message to let the user know that they're trying to upload invalid files. Do you think this is reasonably justifiable if we were to include the bugfix in 6.5?

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js [hunk 12]
```diff
@@ -94,6 +115,23 @@ function UploadFonts() {
 		handleInstall( fontFacesLoaded );
 	};
 
+	/**
+	 * Checks if a file is a valid Font file.
+	 *
+	 * @param {File} file The file to be checked.
```
Comment (matiasbenedetto) [inline packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js:119]:
```suggestion
	 * @param {File} The file to be checked.
```

**Review by matiasbenedetto — APPROVED** [review]
This works as advertised: invalid font files raise an error notice, and valid font files continue to upload as expected.
Because of that, I approved the PR. Still, I think we could simplify the code a little by doing this: https://github.com/WordPress/gutenberg/pull/59648/files#r1516698107

LGTM

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js (hunk 11 above)
Comment (matiasbenedetto) [reply packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js]: I suspect that regarding the 6.5 string freeze, it's somewhat the same to include a new string rather than modify an existing one.

Given both messages say basically the same, I'd prefer to simplify the code by removing this ternary and keeping only one string. That would allow us to remove these lines, too:

https://github.com/WordPress/gutenberg/blob/39228ab9464be8b871dc7b0c3637bf05ffa5369b/packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js#L59

https://github.com/WordPress/gutenberg/blob/39228ab9464be8b871dc7b0c3637bf05ffa5369b/packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js#L53

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js (hunk 12 above)
Comment (peterwilsoncc) [reply packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js:119]: `file` is the parameter name and required. It's unclear in the diff but will be clearer in IDEs.

Screen Shot 2024-03-08 at 9 26 33 am

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js (hunk 11 above)
Comment (peterwilsoncc) [reply packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js]: It might be possible to ~adapt~ _use_ some existing strings in the WP 6.5 branch:

`__( 'There were some errors installing fonts. %s' )` 
`__( 'No fonts found to install.' )`
`__( 'Sorry, you are not allowed to upload this file type.' )`

Comment (getdave) [reply packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js]: For 6.5 let's try and reuse strings we already have. We can optimise to a better string later (perhaps create a followup Issue?).

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js [hunk 13]
```diff
@@ -45,29 +45,50 @@ function UploadFonts() {
...
+		const allowedFiles = ( await Promise.all( checkFilesPromises ) ).filter(
+			( file ) => null !== file
+		);
+
 		if ( allowedFiles.length > 0 ) {
 			loadFiles( allowedFiles );
 		} else {
+			const message = hasInvalidFiles
+				? __(
+						'One or more of the selected files are not valid fonts. Please try again.'
```
Comment (getdave) [inline packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js]:
```suggestion
						'Sorry, you are not allowed to upload this file type.'
```

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js [hunk 14]
```diff
@@ -45,29 +45,50 @@ function UploadFonts() {
...
+				  )
+				: __( 'No valid fonts found to install.' );
```
Comment (getdave) [inline packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js]:
```suggestion
				: __( 'No fonts found to install.' );
```

File: packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js (hunk 11 above)
Comment (getdave) [reply packages/edit-site/src/components/global-styles/font-library-modal/upload-fonts.js]: ✅ I reused the existing strings as best I could in https://github.com/WordPress/gutenberg/pull/59648/commits/6b97632d4e40c3d473fd4eac243f8a89cf9d0ade

**Comment by getdave** [comment]
I broken the linting. I'll fix that shortly.

**Comment by getdave** [comment]
Proposing for inclusion in WP 6.5 during RC period because this is a bug in the critical upload path for the Font Libray feature. It seems to have been [identified during the RC testing phase](https://github.com/WordPress/gutenberg/issues/59578).

**Comment by getdave** [comment]
I just manually cherry-picked this PR to the pick/wp-65-rc-2 branch to get it included in the next release

https://github.com/WordPress/gutenberg/pull/59756
