### PR TITLE
Fix applying bindings or pattern overrides to button blocks with empty text

### LINKED ISSUE #61303: Pattern Overrides: Button block left empty in original pattern and used as an override throws an error in pattern instances
### Description

If a user creates a pattern with an empty button block that has 'Allow Overrides' enabled, an error is thrown when that pattern is used and text is added to the button.

I believe this happens because the button block outputs nothing when the button block is empty:
https://github.com/WordPress/gutenberg/blob/edb7e4ea109d0155de9d6dce327b2ba72dead56b/packages/block-library/src/button/save.js#L34-L36

But block bindings still tries to update the HTML for the pattern overrides binding without checking that a button is present.

A basic fix might be to check for the presence of a button element, and do nothing if there isn't one, but this leads to a problem that no button block is output when the user specifies text in a pattern instance for an empty button. I'm not sure if we could move this check to a server side render callback to fix the problem?

The reverse is also a problem. If a button is specified in the original pattern with text, but the override removes text, an empty button is output, whereas the button block would usually output nothing.

I think the same could also happen for any other type of block binding, so this is probably not a pattern overrides specific issue.

### Step-by-step reproduction instructions

1. Create a synced pattern with an empty button block (no text defined)
2. Allow overrides for the button block
3. Save the pattern
4. Create a new post and insert the pattern you just created
5. Enter some text into the button
6. Preview the post

Expected: No error occurs, the button is shown
Actual: An error is thrown

### Screenshots, screen recording, code snippet

```
Warning: foreach() argument must be of type array|object, null given in /var/www/html/wp-content/plugins/gutenberg/lib/compat/wordpress-6.5/blocks.php on line 84 Deprecated: strcasecmp(): Passing null to parameter #1 ($string1) of type string is deprecated in /var/www/html/wp-content/plugins/gutenberg/lib/compat/wordpress-6.5/blocks.php on line 91 Notice: Function WP_HTML_Tag_Processor::seek was called incorrectly. Unknown bookmark name. Please see Debugging in WordPress for more information. (This message was added in version 6.2.0.) in /var/www/html/wp-includes/functions.php on line 6080 Deprecated: strcasecmp(): Passing null to parameter #1 ($string1) of type string is deprecated in /var/www/html/wp-content/plugins/gutenberg/lib/compat/wordpress-6.5/blocks.php on line 91 Notice: Function WP_HTML_Tag_Processor::seek was called incorrectly. Unknown bookmark name. Please see Debugging in WordPress for more information. (This message was added in version 6.2.0.) in /var/www/html/wp-includes/functions.php on line 6080
```

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by talldan**
## What?
Fixes #61303

An issue for block bindings and pattern overrides is when a button block's text is left empty, the editor saves no html due to a conditional return in the block's save function.

When a binding tries dynamically to update a button block in this state, it won't be able to due to the missing content.

This PR changes the button block so that the conditional rendering is implemented dynamically on the server. This allows block bindings to dynamically change the content of the block, even when there's empty text.

## How?
Uses the tag processor to check for inner content.

The `text` of a button block is a sourced attribute, so the sever is unable to parse the attribute value, so it needs to be read from the content.

## Testing Instructions
1. Create a synced pattern with an empty button block (no text defined)
2. Allow overrides for the button block
3. Save the pattern
4. Create a new post and insert the pattern you just created
5. Enter some text into the button
6. Preview the post

Expected: The button should appear with the override text.

As a general smoke test, it's also worth checking that buttons outside of patterns continue to work as expected when they have and do not have text.

You should also be able to add a button that has text to a pattern, and then override it with no text, and it won't render in the frontend

### Editor
Screenshot 2024-06-03 at 4 26 47 pm

### Frontend
Screenshot 2024-06-03 at 4 27 58 pm

### CODE REVIEW

File: packages/block-library/src/button/index.php [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+		switch ( $p->get_token_name() ) {
+			case '#text':
+				$text .= $p->get_modifiable_text();
+				break;
+
+			case 'BR':
+				$text .= '';
+				break;
+		}
+	}
```
Comment (talldan) [inline packages/block-library/src/button/index.php]: I haven't written a lot of tag processor code, so would be happy to receive feedback on this.

File: packages/block-library/src/button/index.php [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+	while ( $p->next_tag() ) {
+		$tag = $p->get_tag();
+		if ( 'A' === $tag || 'BUTTON' === $tag ) {
+			break;
+		}
+	}
+
+	// If this happens, the likelihood is there's no block content.
+	if ( null === $tag ) {
+		return '';
```
Comment (dmsnell) [inline packages/block-library/src/button/index.php]: why not render `$content` here? a viable alternative is that some other plugin already modified the button. do we want to wipe it out entirely just because there's no more `A` or `BUTTON`? e.g. maybe there's now a `<myplugin-button>` in there

File: packages/block-library/src/button/index.php [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+			case 'BR':
+				$text .= '';
+				break;
+		}
+	}
+
+	/*
+	 * When there's no text, render nothing for the block.
+	 * It's this way because an anchor or button element without text results
+	 * in poor accessibility.
```
Comment (dmsnell) [inline packages/block-library/src/button/index.php]: does this hold even when there is CSS with the `content` property set? maybe there is additional code involved somewhere else. is removing the content without any indicating the better accessible choice?

File: packages/block-library/src/button/index.php (hunk 1 above)
Comment (dmsnell) [reply packages/block-library/src/button/index.php]: this is great @talldan! here are some thoughts. it _looks_ like you're attempting to remove all content inside the button except for the plain text content. that is, no formatting, no spans, no inline images, etc… I don't speak to whether that's a great idea or not, but I can provide feedback for the HTML API use in doing so.

first of all, this is technically the domain of the HTML Processor, which knows HTML structure, but since that's not really ready yet this will suffice. you did the right thing using the Tag Processor.

this code, however, is going to grab only the first text nodeat the start of the `A` or `BUTTON`. Maybe we don't expect any other content, but if you want to (unreliably) limit it to the inner contents, then you can add one more step which would improve the reliability a little bit and capture more text.

```php
// Build a string of the inner text.
$text = '';
while ( $p->next_token() ) {
	switch ( $p->get_token_name() ) {
		/*
         * Neither `A` nor `BUTTON` can nest, so it doesn't matter
         * if these are opening or closing tags. Both will close
         * the open element.
         */
		case $tag:
			break;

		case '#text':
			$text .= $p->get_modifiable_text();
			continue;

		case 'BR':
			$text .= "\n";
			continue;
	}
}
```

**Review by dmsnell — COMMENTED** [review]
This is a change I don't fully understand, so I'm probably overlooking something, but it looks like it wipes out all buttons, which seems non-optimal. Should we be checking for some condition before trashing the HTML?

Also even when we choose to, it might help to provide more insightful checks than "we didn't find an `A` or a `BUTTON`" in case plugin code has modified the markup in a way we don't expect. Perhaps we assume that if the tags are missing then someone else modified the content intentionally and we should leave it alone.

If this is for the block bindings, would it help avoid unintentional corruption if we looked for some block attribute indicating that we intend to perform Block Binding on it?

I'm just a bit nervous from this that the effect is a broad stroke that introduces normal corruption for the sake of fixing one much-rarer edge case. But like I acknowledge, I'm probably missing something major.

**Comment by SantosGuillamot** [comment]
If I am not mistaken, we don't need to process the content and modify it. Right now, the modifications of the block attributes to apply the bindings are done during the rendering. This means that we can check if the text attribute exists (or if it is empty). In that case, we just return null. And if not, we just return the content. Something like this:

```php
if ( empty( $attributes["text"] ) ) {
    return null;
} else {
    return $content;
}
```

I quickly tested and it seems to work, but I didn't take a close look at the different scenarios. Do you think something like that could work?

**Comment by talldan** [comment]
> I quickly tested and it seems to work, but I didn't take a close look at the different scenarios. Do you think something like that could work?

@SantosGuillamot My first hope is that the solution would be as simple as that, but I don't think it is. My understanding is that what you propose will only work when bindings are applied (`$attributes[ 'text' ]` only has a value due to the block binding). When the button block is used normally without bindings it will still need the conditional rendering to work as expected.

**Comment by SantosGuillamot** [comment]
Oh, okay. I had assumed that `attributes[ "text "]` existed for normal buttons as well. Trying to understand better what we want, is this right?

* If attributes[ "text" ] exist: return content.
* If the BUTTON or A tag HAS inner text: return content.
* If the BUTTON or A tag HAS NOT inner text: return null.

If that's the case and I'm understanding it correctly, @dmsnell can help better identify the easiest way to do that check now. I can't say if the current approach is the right one or not.

If I am not mistaken, and according to [this comment](https://github.com/Wordpress/wordpress-develop/blob/trunk/src/wp-includes/html-api/class-wp-html-processor.php#L25-L30), in the future, we could potentially rely on the HTML processor to read the inner text (something like `$p->get_inner_text()`). Ideally, I imagine something like this:

```php
if ( ! empty( $attributes[ "text" ] ) ) {
    return $content;
}

while ( $p->next_tag() ) {
    $tag = $p->get_tag();
    if ( 'A' === $tag || 'BUTTON' === $tag ) {
        if ( $p->get_inner_text() ){
            return $content;
        } else {
            return null;
        }
    }
}
```

But again, I believe this is not possible right now and I am not that familiar with the HTML API, so it may be wrong.

File: packages/block-library/src/button/index.php (hunk 1 above)
Comment (talldan) [reply packages/block-library/src/button/index.php]: > case $tag:
>	break;

Thanks for the feedback! Should this also break out of the while loop in addition to the switch? I believe in PHP `break 2` can be used to break two levels, but I might change it from a `switch` to an `if` statement.

Comment (talldan) [reply packages/block-library/src/button/index.php]: > it looks like you're attempting to remove all content inside the button except for the plain text content. that is, no formatting, no spans, no inline images, etc… I don't speak to whether that's a great idea or not, but I can provide feedback for the HTML API use in doing so.

The goal in this PR is for the replace the old static implementation (removed in this PR):
https://github.com/WordPress/gutenberg/blob/dbf201449e9736f672b61e422787d47659db327a/packages/block-library/src/button/save.js#L34-L36

Retaining the HTML from the save function allows for bindings to work with empty buttons.

It looks like the conditional logic introduced as a result of this issue - https://github.com/WordPress/gutenberg/issues/17221. 

It's not an accessibility reason. How many years have I incorrectly believed that?!  I'll update the comment in the code.

File: packages/block-library/src/button/index.php (hunk 2 above)
Comment (talldan) [reply packages/block-library/src/button/index.php]: Agreed 👍 

I've made that change.

File: packages/block-library/src/button/index.php (hunk 3 above)
Comment (talldan) [reply packages/block-library/src/button/index.php]: As mentioned in another comment, it originates from https://github.com/WordPress/gutenberg/issues/17221.

I've updated this comment so that it doesn't mention accessibility, instead I link straight to that issue.

File: packages/block-library/src/button/index.php (hunk 1 above)
Comment (talldan) [reply packages/block-library/src/button/index.php]: I did some further testing and realized there's also the case of inline images. I've now simplified the code down to just this:
```php
// If the next token is the closing tag, the button is empty.
$p->next_token();
$is_empty = $p->get_token_name() === $tag;

if ( $is_empty ) {
	return '';
}
```

Which should better match how `RichText.isEmpty` works (even a space is considered content) - https://github.com/WordPress/gutenberg/blob/trunk/packages/rich-text/src/is-empty.js.

I should've endeavoured to match that implementation first.

Anything I might be overlooking here? I'll work on adding some tests for this.

**Comment by kevin940726** [comment]
From my testing in a pattern with the empty second button.

```html
<!-- wp:block {"ref":199,"content":{"2":{"text":"123"}}} /-->
```

In the editor it looks correctly:

image

However, on the frontend, the second button disappears and magically erases the first character.
image

Is there something I'm doing wrong?

**Comment by talldan** [comment]
> Is there something I'm doing wrong?

I couldn't reproduce it, and I'm not sure how that could happen.

I'll do some more testing. It has been pretty challenging working on this fix as my local xdebug isn't working for block PHP. Not sure what's causing that.

**Comment by talldan** [comment]
There's one caveat that I'll note for testing, this won't work for patterns already saved before you checked out this branch. Those patterns are already missing the button markup, so there's very little that can be done to fix them (beyond making the button block completely dynamic).

And as a side note, I managed to figure out what was happening with xdebug. A breakpoint needs to be set in the `build/block-library/blocks/button.php` file, it won't work in the source file. It's a bit of an inconvenience, not sure if there's a way to solve that.

File: packages/block-library/src/button/index.php (hunk 1 above)
Comment (dmsnell) [reply packages/block-library/src/button/index.php]: It's probably good enough, but keep in mind that there could be comments in there too.

```php
$is_empty = true;
while ( $p->next_token() && $tag !== $p->get_token_name() && $is_empty ) {
	if ( '#comment' !== $p->get_token_type() ) {
		// Anything else implies this is not empty.
		$is_empty = false;
	}
}
```

**Comment by kevin940726** [comment]
> I couldn't reproduce it, and I'm not sure how that could happen.

I can only reproduce it if the override for the empty button starts with a number. e.g. `Button 2` works correctly, but `2Button 2` doesn't work for some reason. Could anyone verify this?

**Comment by talldan** [comment]
> I can only reproduce it if the override for the empty button starts with a number. e.g. Button 2 works correctly, but 2Button 2 doesn't work for some reason. Could anyone verify this?

Yep, I can reproduce it now, thanks for the extra info!

**Comment by talldan** [comment]
I can reproduce that in `trunk` as well using a non-empty button, so it must be a problem with the bindings code.

**Comment by kevin940726** [comment]
> I can reproduce that in `trunk` as well using a non-empty button, so it must be a problem with the bindings code.

Yep. I think it's related to https://github.com/WordPress/gutenberg/issues/62347, thanks for @Mamaduka for the mention!

**Comment by SantosGuillamot** [comment]
I just answered in [the mentioned issue](https://github.com/WordPress/gutenberg/issues/62347#issuecomment-2151562376):

>I believe it is caused by this refactoring of the replacement logic: https://github.com/WordPress/gutenberg/pull/61236. My fault for using regex 🤦
>
>The idea behind that pull request was to simplify the logic to support more attributes, but that didn't make it to 6.6. We should probably go back to the previous implementation and refactor the logic once the HTML API adds new methods to help with that.

**Review by kevin940726 — APPROVED** [review]
Works for me! I'll leave the binding code for others with more knowledge to review though.

**Comment by SantosGuillamot** [comment]
I've tested it and it seems to work fine! Regarding bindings, I think it is ready. But I'll defer it to @dmsnell because most of the changes are related to how to use the HTML Tag Processor.

**Review by dmsnell — APPROVED** [review]
I could have added an approval before, but mainly I'm only examining the HTML API usage, and it seems fine what's happening here, so from that angle the patch is good.

**Comment by ellatrix** [comment]
This was cherry-picked to the wp/6.6 branch.
