### PR TITLE
Fix Synced Patterns' color in quick inserter

### LINKED ISSUE #53209: Patterns: make the synced patterns purple the quick inserter list
## What problem does this address?
Currently the synced patterns display a `--wp-block-synced-color` but in the quick inserter they just display as black, which makes it hard to separate synced from unsynced patterns at a glance.

## What is your proposed solution?
Update the autocompleter component to allow an item color to be passed in so that the synced patterns can be color coded.

### PR DESCRIPTION
**Pull request by kevin940726**
## What?

Fix https://github.com/WordPress/gutenberg/issues/53209. Fix the color for Synced Patterns in the quick inserter.

## Why?

Consistency and clear separation.

## How?

Use the `{ src, foreground }` syntax for icons.

## Testing Instructions

1. Create a synced pattern and an unsynced pattern and make their name include `pattern` and easy to distinguish between.
2. Open Post or Site editor.
3. Type `/pattern` and use the Arrow key to navigate through different patterns.
4. Expect the Synced one to have its icon filled with the purple color.

### Testing Instructions for Keyboard

Follow the same instructions above. Note that this fix changes the visual UI so it's not noticeable if you're only using screen readers.

## Screenshots or screencast 
image

### CODE REVIEW

File: packages/block-editor/src/store/selectors.js [hunk 1]
```diff
@@ -1963,7 +1963,14 @@ const buildBlockTypeItem =
 export const getInserterItems = createSelector(
 	( state, rootClientId = null ) => {
 		const buildReusableBlockInserterItem = ( reusableBlock ) => {
-			const icon = symbol;
+			const icon =
+				reusableBlock.wp_pattern_sync_status === 'synced' ||
```
Comment (glendaviesnz) [inline packages/block-editor/src/store/selectors.js]: I don't think we assign a sync status of `synced` anywhere currently, for fully synced blocks `wp_pattern_sync_status` is always `undefined`, so I wonder if we need this extra check?

Comment (kevin940726) [reply packages/block-editor/src/store/selectors.js]: Oh I was just following the logic in [line 1990](https://github.com/WordPress/gutenberg/pull/53327/files#diff-aa92c48095c35f17feb834dd919baf52274a73c7b1180ff5acce7b6087b126cfR1990). But yeah, we can simplify this.

Comment (glendaviesnz) [reply packages/block-editor/src/store/selectors.js:1967]: I don't see that logic, did you paste the correct link, it just circles back to this diff?

Comment (kevin940726) [reply packages/block-editor/src/store/selectors.js]: I simply mean that we define `syncStatus` by referencing `wp_pattern_sync_status` in `syncStatus: reusableBlock.wp_pattern_sync_status` rather than hardcoding it. (Which implicitly means that it depends on the `wp_pattern_sync_status` variable)

Comment (glendaviesnz) [reply packages/block-editor/src/store/selectors.js]: I don't see that logic on 1990?  but probably worth simplifying this to avoid any confusion.

Comment (aaronrobertshaw) [reply packages/block-editor/src/store/selectors.js]: At first glance, this looked like something left behind from when we were assigning a value for synced status on patterns. I agree, this check doesn't appear to be required anymore.

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for the fix @kevin940726 👍 

This tests well for me. Unsynced pattern icons are the normal color while synced pattern icons are purple. 

I also tested this after removing the additional sync status check and it continued to work as advertised.

Screenshot 2023-08-07 at 1 33 49 pm

File: packages/block-editor/src/store/selectors.js (hunk 1 above)
Comment (kevin940726) [reply packages/block-editor/src/store/selectors.js]: I just gave it a try in my environment but seems like unsynced patterns are also returned by the `getReusableBlocks` call, so the check is still needed. Is it because I'm on an older core? Can any of you reproduce this? 🙇‍♂️

Comment (aaronrobertshaw) [reply packages/block-editor/src/store/selectors.js]: Sorry for the confusion, I was meaning the first condition in the check, only the part highlighted by Glen's original comment. It works as expected for me removing just that conditional.

```diff
diff --git a/packages/block-editor/src/store/selectors.js b/packages/block-editor/src/store/selectors.js
index f5002f2b027..45955366f1b 100644
--- a/packages/block-editor/src/store/selectors.js
+++ b/packages/block-editor/src/store/selectors.js
@@ -1963,14 +1963,12 @@ const buildBlockTypeItem =
 export const getInserterItems = createSelector(
 	( state, rootClientId = null ) => {
 		const buildReusableBlockInserterItem = ( reusableBlock ) => {
-			const icon =
-				reusableBlock.wp_pattern_sync_status === 'synced' ||
-				! reusableBlock.wp_pattern_sync_status
-					? {
-							src: symbol,
-							foreground: 'var(--wp-block-synced-color)',
-					  }
-					: symbol;
+			const icon = ! reusableBlock.wp_pattern_sync_status
+				? {
+						src: symbol,
+						foreground: 'var(--wp-block-synced-color)',
+				  }
+				: symbol;
 			const id = `core/block/${ reusableBlock.id }`;
 			const { time, count = 0 } = getInsertUsage( state, id ) || {};
 			const frecency = calculateFrecency( time, count );

```

Comment (kevin940726) [reply packages/block-editor/src/store/selectors.js]: Oh oops! I completely missed that we don't use the `synced` enum anymore 🤦 .

Comment (aaronrobertshaw) [reply packages/block-editor/src/store/selectors.js]: All good. Small price to pay given all the chopping and changing throughout our pattern explorations 👍

**Review by aaronrobertshaw — APPROVED** [review]
After the latest tweak, this is looking good now. Still tests as advertised both manually and via unit tests.

Thanks @kevin940726 👍
