### PR TITLE
Media & Text: Hide the alt text option for featured images

### LINKED ISSUE #60023: Media & text block: The Alt text for the featured image is not working correctly
### Description

When the Media & text block uses a featured image, the alt text is:

1. Pre-populated with the alt text from the media library, and can not be deleted or replaced from the alt text input field in the editor.
2. Not present on the front.

### Step-by-step reproduction instructions

With Gutenberg active:
Create a new post and assign a featured image that has an alt text in the media library.
Add a Media & text block and select the option "Use Featured image".
Try to change the text in the block settings panel.
Save and reload the post.
Confirm that the alt text does not include the changes you made.

View the source of the block on the front of the site and confirm that there is no alt text output.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

Gutenberg current trunk.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by carolinan**
## What?

Hides the TextareaControl for the alternative text if the block uses a featured image.
Adds the alt attribute to the img tag on the front.

Closes https://github.com/WordPress/gutenberg/issues/60023

## Why?

The alt text option does not work correctly in the editor, it is problematic inside query loops, and the alt text is not output on the front. Please see the discussion in the linked issue.

## How?

The PR:
- Updates the condition that shows the option for editing the alternative text, so that it is hidden when a featured image is used.
- Adds the alt attribute to the img tag on the front, using the WP_HTML_Tag_Processor.

## Testing Instructions

With Gutenberg **trunk**:
Add three media & text blocks:
One with a video, one with a standard image, and one with a featured image. The featured image should not have an alt text in the media library.
Save.

Apply the PR.
Refresh the post and confirm that the PR does not cause any block validation errors with the existing blocks.
Select the media & text block that has the standard image. Confirm that the alternative text option shows in the block settings panel.
Select the media & text block that has the featured image. Confirm that the alternative text option does not show.

Confirm that the block with the featured image has an empty alt attribute in the editor and the front.
Return to the editor, open the media library and add an alt text to the featured image.
Confirm that the block with the featured image uses the correct text in the alt attribute in the editor and the front.

### CODE REVIEW

File: packages/block-library/src/media-text/edit.js [hunk 1]
```diff
@@ -318,11 +318,11 @@ function MediaTextEdit( {
 						onDrag={ imperativeFocalPointPreview }
 					/>
 				) }
-			{ mediaType === 'image' && ( mediaUrl || featuredImageURL ) && (
+			{ mediaType === 'image' && mediaUrl && ! featuredImageURL && (
```
Comment (t-hamano) [inline packages/block-library/src/media-text/edit.js]: Wouldn't it be more reliable to refer to `useFeaturedImage`, similar to [the Cover block](https://github.com/WordPress/gutenberg/blob/ee3fd1a6756b3cd2cd254092c2e879ceb2cc5ec9/packages/block-library/src/cover/edit/inspector-controls.js#L204)?

File: packages/block-library/src/media-text/index.php [hunk 2]
```diff
@@ -48,6 +48,7 @@ function render_block_core_media_text( $attributes, $content ) {
 	}
 	$processor->set_attribute( 'src', esc_url( $current_featured_image ) );
 	$processor->set_attribute( 'class', 'wp-image-' . get_post_thumbnail_id() . ' size-' . $media_size_slug );
+	$processor->set_attribute( 'alt', esc_attr( get_post_meta( get_post_thumbnail_id(), '_wp_attachment_image_alt', true ) ) );
```
Comment (t-hamano) [inline packages/block-library/src/media-text/index.php]:
```suggestion
	$processor->set_attribute( 'alt', trim( strip_tags( get_post_meta( get_post_thumbnail_id(), '_wp_attachment_image_alt', true ) ) ) );
```

This might be better. Because it matches [the internal implementation](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/media.php#L1076) of the `wp_get_attachment_image()` function for getting the HTML of the image element. Additionally, it is consistent with [the implementation of the Post Featured Image block](https://github.com/WordPress/gutenberg/blob/ee3fd1a6756b3cd2cd254092c2e879ceb2cc5ec9/packages/block-library/src/post-featured-image/index.php#L31).

File: packages/block-library/src/media-text/edit.js (hunk 1 above)
Comment (carolinan) [reply packages/block-library/src/media-text/edit.js]: I don't know if it is more reliable but sure lets make them more consistent.

**Review by t-hamano — APPROVED** [review]
LGTM 🚀
