### PR TITLE
Fix resolver resolution status key types mismatch causing unwanted resolver calls for identical state data

### LINKED ISSUE #52106: Generated state keys for selector resolution do not account for varying types of recordKey
Calling `getEntityRecord` on a populated Redux cache (can) result in unnecessary network requests.

This is dependent on whether a consumer passes the [3rd `recordKey` argument](https://github.com/WordPress/gutenberg/blob/3b7902e6885fd12c660e4cfd94f115ebfbe91434/packages/core-data/src/resolvers.js#L51) as a `String` or an `Integer`.

**Expected behaviour**: if a record _already_ exists in state, a call to select that record by ID should _not_ result in a network request to retrieve that record.

**Actual behaviour**: if a record already exists in state, a `getEntityRecord` call to select that record by ID using a _string-based_ ID results in an additional network request.

## Replication

You can replicate as follows:

- Create some Navigation Menus on your website using the Navigation block. Be sure to save/publish them.
- Create a new Post
- Open dev tools network tab and then hit `Esc` to _also_ open the `Console` tab below it.
- In console type `wp.data.select('core').getEntityRecords('postType', 'wp_navigation')`. You should see `null` and then running it _again_ you should see results. This has populated the `core/data` state with entities of that type.
- Note down the `id`s of those records.
- At this point those records are in state and thus any calls to select the individual records should _not_ result in a network request because they are already in state and `getEntityRecords` [resolves the `getEntityRecord` selectors](https://github.com/WordPress/gutenberg/blob/3b7902e6885fd12c660e4cfd94f115ebfbe91434/packages/core-data/src/resolvers.js#L199-L217). 
- Choose the ID of one of your records and enter the following into the console making sure that you pass the 3rd argument as a _string_ and _not_ a int value - `wp.data.select('core').getEntityRecord('postType', 'wp_navigation','{YOUR_RECORD_ID}')`
- See a network request triggered to fetch a record which is already in state!
- Now take a different ID and enter the following but this time pass the 3rd argument as an _integer_  - `wp.data.select('core').getEntityRecord('postType', 'wp_navigation',{YOUR_RECORD_ID})`
- See no network request is dispatched.
- Do the same query again but pass the same ID as a string and see a network request will be dispatched.

## Screencapture

https://github.com/WordPress/gutenberg/assets/444434/ce7b52ed-c0cb-47a7-9838-c867207f0ef6

## Explanation

@wordpress/data has a mechanism whereby [the next resolution state of a selector](https://github.com/WordPress/gutenberg/blob/3b7902e6885fd12c660e4cfd94f115ebfbe91434/packages/data/src/redux-store/metadata/reducer.ts#L123) is determined by setting a `status` prop on a `value` in a ([special kind of](https://www.npmjs.com/package/equivalent-key-map)) `Map` object.

This map is is "keyed" by the selector's args as an array ([remember `Map` ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)can have many different types of keys compared to plain objects).

For example a call to `getEntityRecords('postType', 'wp_navigation')` would result in a "key" array for a given record that might look like this - `['postType', 'wp_navigation', 379)]`.

When it comes time to determine whether a given resolver is "resolved", we check the same `Map` for a key which matches the given selector's args.

https://github.com/WordPress/gutenberg/blob/3b7902e6885fd12c660e4cfd94f115ebfbe91434/packages/data/src/redux-store/metadata/selectors.js#L22-L29

However the bug occurs when you pass different types as the _3rd_ argument to `getEntityRecord()`.

The reason this happens is that the `args` being set in the `EquivalentKeyMap` cache have different types for the 3rd (`recordKey`) argument. This is because consumers often call `getEntityRecords` interchangeably, passing the 3rd (`recordKey`) argument as either a number of a string (note it's _also_ due to the way `getEntityRecords` resolves the `getEntityRecord` selector - see below).

This means that the call to 

```
return map.get( selectorArgsToStateKey( args ) ); 
```

...tries to get a value using the key `['postType', 'wp_navigation', '379')]` but the key is actually using the integer form `['postType', 'wp_navigation', 379)]` so no match occurs.

This causes the selector to not be resolved and thus the network request is dispatched. This is wrong as the resolver should in fact be resolved.

It's worth noting that the reason a `integer` sends up in the state is due to how we resolve the `getEntityRecord` (singular) selector within the `getEntityRecords` (plural) resolver:

https://github.com/WordPress/gutenberg/blob/3b7902e6885fd12c660e4cfd94f115ebfbe91434/packages/core-data/src/resolvers.js#L203-L206

The `record[ key ]` part will always result in a integer because the value of the `id` property of the REST API response is always a int and not a string.

Screen Shot 2023-06-29 at 10 35 06

## Solution

I have a fix whereby I patched the `selectorArgsToStateKey` to convert any "numeric" strings in the `args` array into their integer equivalents.

This ensures that however `getEntityRecord` is called the cache always sets/gets using the same type.

However it might be a bit drastic and I'm not sure of any side effects.

### PR DESCRIPTION
**Pull request by getdave**
## What?

Stops unwanted resolver calls due to resolver cache misses. 

Specifically fixes `getEntityRecord` in `@wordpress/core-data` to avoid cache miss caused by type mismatch on the `recordKey` argument.

Closes https://github.com/WordPress/gutenberg/issues/52106

## Why?

The following selector calls are not considered equivalent by the caching mechanism in `@wordpress/data` (see https://github.com/WordPress/gutenberg/issues/52106 for detailed explanation):

```js
getEntityRecord( 'postType', 'post', 1 ); // number as recordKey
getEntityRecord( 'postType', 'post', '1' ); // string as recordKey
```

This means that even if the record exists in state, the relevant _resolver_ is not marked as resolved and thus the resolver runs again thereby triggering a network request.

This is very likely to occur because in Gutenberg `ID`s can be strings which means a lot of (potential) cache misses and unnecessary network calls and loading delays.

A specific example is the `useNavigator` hooks where the resulting `params` object will contain params as strings even if they are numeric. So if there's a param of `postId` then it will be a string. It's very easy to accidentally pass that to `getEntityRecord`.

## How?

Adds a new optional property to the ~resolver~ selector which allows the implementor to define a method which normalizes the ~resolver~ `args` passed to the selector into to a standard form. This standardised form is then used in cache set/get.

This PR implements such a method for the `getEntityRecord` ~resolver~ selector to stabize the type of the `recordKey` as a number rather than a string when the `recordKey` argument looks like a numberic ID (which is likely to be the ID of a Post record).

## Testing Instructions

- Create some Navigation Menus on your website using the Navigation block. Be sure to save/publish them.
- Create a new Post
- Open dev tools network tab and then hit `Esc` to _also_ open the `Console` tab below it.
- In console type `wp.data.select('core').getEntityRecords('postType', 'wp_navigation')`. You should see `null` and then running it _again_ you should see results. This has populated the `core/data` state with entities of that type.
- Note down the `id`s of those records.
- At this point those records are in state and thus any calls to select the individual records should _not_ result in a network request because they are already in state and `getEntityRecords` [resolves the `getEntityRecord` selectors](https://github.com/WordPress/gutenberg/blob/3b7902e6885fd12c660e4cfd94f115ebfbe91434/packages/core-data/src/resolvers.js#L199-L217). 
- Choose the ID of one of your records and enter the following into the console making sure that you pass the 3rd argument as a _string_ and _not_ a int value - `wp.data.select('core').getEntityRecord('postType', 'wp_navigation','{YOUR_RECORD_ID}')`
- You should _**not**_ see `GET` request (ignore `OPTIONS`) to `wp/v2/navigation/{RECORD_ID}`.
- Make the same request but this time make the `recordKey` argument a `Number`.
- See no network request is dispatched.

...you can also test this in the Site Editor by:

- Clicking `Navigation` in Browse Mode sidebar.
- Clicking on one of your Navigations.
- See that no `GET` network request was dispatched.

### CODE REVIEW

File: packages/core-data/src/resolvers.js [hunk 1]
```diff
@@ -121,6 +121,22 @@ export const getEntityRecord =
 		}
 	};
 
+function isNumeric( n ) {
+	return ! isNaN( parseFloat( n ) ) && isFinite( n );
+}
+
+getEntityRecord.normalizeArgs = ( args ) => {
```
Comment (getdave) [inline packages/core-data/src/resolvers.js]: Could just as easily be defined on the _selector_.

File: packages/data/src/redux-store/index.js [hunk 2]
```diff
@@ -598,6 +598,9 @@ function mapSelectorsWithResolvers(
 		}
 
 		const selectorResolver = ( ...args ) => {
+			if ( resolver.normalizeArgs ) {
```
Comment (getdave) [inline packages/data/src/redux-store/index.js]: We'd need to check if it's a callable function...

File: packages/core-data/src/resolvers.js [hunk 3]
```diff
@@ -121,6 +121,40 @@ export const getEntityRecord =
...
+		return false;
+	}
+
+	// Check if the string is a number
+	if ( ! isNaN( str ) ) {
+		return true;
+	}
+
+	// Check if the string contains only numeric characters
+	if ( /^\d+$/.test( str ) ) {
```
Comment (jsnajdr) [inline packages/core-data/src/resolvers.js]: This entire function could be just `return /^\s*\d+\s*$/.test( str )`. This regexp already contains all the preceding conditions: it matches only non-empty strings, if it matches, then the number can't be `NaN`, takes whitespace into account...

Also, returning `true` on `! isNan( str )` is a bug -- it will accept floating numbers like `"3.14"` as numeric IDs.

File: packages/data/src/redux-store/index.js (hunk 2 above)
Comment (jsnajdr) [reply packages/data/src/redux-store/index.js]: This code currently passes the normalized args also to the `selector` itself, but I think we want to pass them only to the `fulfillSelector` function.

@youknowriad what do you think about the new `normalizeArgs` optional resolver field? The problem being solved is that the following selector calls are equivalent:
```js
getEntityRecord( 'postType', 'post', 1 );
getEntityRecord( 'postType', 'post', '1' );
```
But the resolver machinery (`resolversCache`, metadata reducer) will treat these two `args` arrays as different, and will store two distinct records in the `EquivalentKeyMap`s that hold the resolution state.

At the same time we are reluctant to do the string->number conversion in the `selectorArgsToStateKey` function because this normalization is application-specific, other selectors might not want it.

File: packages/core-data/src/resolvers.js (hunk 3 above)
Comment (getdave) [reply packages/core-data/src/resolvers.js]: Yeh I have to admit I used Chat GPT to scaffold this out very quickly as a PoC.

It needs unit testing and your feedback is also good.

File: packages/data/src/redux-store/index.js (hunk 2 above)
Comment (getdave) [reply packages/data/src/redux-store/index.js]: ...and bear in mind that we cannot simply normalize the args in the selector or resolver function body itself because the `args` are used by the aforesaid "resolver machinery" prior to invocation of the functions themselves.

File: packages/core-data/src/resolvers.js (hunk 3 above)
Comment (jsnajdr) [reply packages/core-data/src/resolvers.js]: I used ChatGPT, too, to help me create the `\s`-using regexp 🙂

File: packages/data/src/redux-store/index.js (hunk 2 above)
Comment (getdave) [reply packages/data/src/redux-store/index.js]: > This code currently passes the normalized args also to the selector itself, but I think we want to pass them only to the fulfillSelector function.

I would think we'd like to normalize the arguments for _both_ selector and resolver? I would expect both to receive the same arguments.

------

Another option we could consider is having a property like `normalizeArgsToCacheKey` (again on the resolver) which we can use selectively _only_ at the points where we interact with the cache thereby leaving the `args` "intact" elsewhere.

File: packages/core-data/src/resolvers.js (hunk 3 above)
Comment (getdave) [reply packages/core-data/src/resolvers.js]: ✅

File: packages/data/src/redux-store/index.js (hunk 2 above)
Comment (jsnajdr) [reply packages/data/src/redux-store/index.js]: There are two ways how to work with the normalization:
1. limit it only to the places that interact with the internal resolvers cache and resolution metadata state. The resolver and the selector itself would get the raw args. It's user-space code, it's supposed to handle them on its own.
2. Always normalize them and pass the normalized version to the selector and the resolvers, too.

I think both ways are good, but you're right that 2) is probably better. The user-space selectors and resolvers likely want to do the same normalization anyway.

In addition to converting strings to numbers, another good use case for normalization is supplying default values. Currently, a selector like:
```js
function getBlocks( type, filter = 'all' ) {}
```
will store two non-equivalent args keys in the resolvers cache: `[ type, undefined ]` and `[ type, 'all' ]`. Normalization can merge them into one.

**Comment by getdave** [comment]
Ok so it's time for some tests here...

**Comment by youknowriad** [comment]
Can I ask why do we want to consider "1" and 1 as equivalent in the first place? Is it certain that we want to do this or is this a bug elsewhere (where we lose the actual type of the identifier)

**Comment by getdave** [comment]
> Can I ask why do we want to consider "1" and 1 as equivalent in the first place? 

We _only_ want to do this in the case where `recordKey` is clear a numeric Post ID. In this case we know that for the following post:

```js
{
title: "My Post",
id: 123,
type: 'some_post_type'
}
```

...these two calls are asking for the same data:

```js
// String as Post ID as record key
getEntityRecord('postType', 'some_post_type', '123');

// Number as Post ID as record key
getEntityRecord('postType', 'some_post_type', 123);
```

If we don't do this then the cache will think it's empty and the resolver will be triggered even though it's already been resolved for the given `recordKey`.


> Is it certain that we want to do this or is this a bug elsewhere (where we lose the actual type of the identifier)

No I don't believe it's a bug "with type "loss". The type is _passed_ to the selector/resolver when it is _called_ incorrectly with a `string` Post ID for the `recordKey`.

The caller is wrong and the resolver is just doing what it should do.

We can protect the caller from this bug. It is being "clever" so there's an argument to just leave it "as is", but that results in additional network requests as I hope I've explained in the Issue and this PR.

## Alternatives considered

One other option might be to introduce a new selector/resolver specifically for fetching records by Post ID. Something like `getEntityRecordById` where we could enforce the type coercion and then forward the call onto `getEntityRecord` under the hood.

Reasons I don't favour that:

- clunky
- another API to learn
- doesn't fix existing issues in the wild

## More Context

The issue that for `getEntityRecords()` the recordKey can be a int or a string. That means I can interchangeably call:

```js
// String as Post ID as record key
getEntityRecord('postType', 'some_post_type', '123');

// Number as Post ID as record key
getEntityRecord('postType', 'some_post_type', 123);
```

There are no guards in place and nor can we add any because there are cases when `recordKey` is a string such as:


```js
// Slug as recordKey
getEntityRecords('postType', 'wp_template_part', 'twentytwentythree//header');
```

This flexibility is great except that it allows those who are intending to pass a post _ID_ as `recordKey` open to cache misses when they accidentally pass a `string`.

Now we could say "everyone should know to pass `recordKey` as a number not a string when you pass a post ID" but it's very easy to get that wrong as there is no way to enforce it because the `recordKey` can be either type.

We could of course patch the individual instances within the Gutenberg repo where `recordKey` ends up as a string for Post IDs but that won't stop 3rd party consumers from "doing it wrong".

As far as I can see there isn't a cleaner solution to this problem but I'm open to discussion.

File: packages/core-data/src/utils/is-numeric-id.js [hunk 4]
```diff
@@ -0,0 +1,10 @@
+/**
+ * Checks a given string to determine if it's a numeric ID.
+ * For example, '123' is a numeric ID, but '123abc' is not.
+ *
+ * @param {string} str the string to determine if it's a numeric ID.
+ * @return {boolean} true if the string is a numeric ID, false otherwise.
+ */
+export default function isNumericID( str = '' ) {
```
Comment (youknowriad) [inline packages/core-data/src/utils/is-numeric-id.js]: Do we need this function? What about `! isNaN( str )`

File: packages/data/src/redux-store/index.js [hunk 5]
```diff
@@ -601,6 +601,9 @@ function mapSelectorWithResolver(
 	}
 
 	const selectorResolver = ( ...args ) => {
+		if ( resolver.normalizeArgs && args?.length ) {
+			args = resolver.normalizeArgs( args );
```
Comment (youknowriad) [inline packages/data/src/redux-store/index.js]: might be worth documenting this new API. Also should we also call normalize in the selector function?

File: packages/data/src/redux-store/index.js (hunk 2 above)
Comment (youknowriad) [reply packages/data/src/redux-store/index.js]: Agreed here, I think if we normalize, we should normalize for all places (for selectors that define the normalize function). Which makes me thing maybe the normalization is a property of a selector (and not the resolver) since not all selectors have resolvers.

**Comment by youknowriad** [comment]
> We could of course patch the individual instances within the Gutenberg repo where recordKey ends up as a string for Post IDs but that won't stop 3rd party consumers from "doing it wrong".

I mean if third parties are doing it wrong, it's also their problem. I'm "ok" with this normalization but can't stop but wonder whether it's really necessary. Is there a lot of places where we use "strings" instead of "numbers" in Gutenberg?

File: packages/data/src/redux-store/index.js (hunk 2 above)
Comment (getdave) [reply packages/data/src/redux-store/index.js]: OK I'll move this to the selector 👍

File: packages/data/src/redux-store/index.js (hunk 5 above)
Comment (getdave) [reply packages/data/src/redux-store/index.js]: Definitely needs documenting 👍

**Comment by getdave** [comment]
> I mean if third parties are doing it wrong, it's also their problem. 

Yes, but unlike with many other WP APIs we don't alert to the user that they are "doing it wrong" because strictly they aren't. It's just our cache (which is masked from the caller) is absolutely strict about types.

In this case we allow them to make this call and they are absolutely none-the-wiser to the performance impact unless they happen to be monitoring network calls. 

On a slower network having to retrieve a record from REST over the network instead of from state could be pretty impactful.

Personally I spotted this when going from Navigation listing -> Single Navigation view in the Site View. Having to wait for the record to resolve _again_ is a pretty poor experience and it's exacerbated by the fact that we've already preloaded the navigation menus query on the server.

> I'm "ok" with this normalization but can't stop but wonder whether it's really necessary. Is there a lot of places where we use "strings" instead of "numbers" in Gutenberg?

Understood and I agree It's not a clear cut problem -> solution.

I found a few instances in Core but admittedly it's not a lot, largely thanks to the fact that we tend to store block attributes with specific types.

One area where we are open to bugs however, is when retrieving params from the URL. If, for example, I get `postId` from the `params` of the `useNavigation()` hook then its type will be `string`. 

```
/wp-admin/site-editor.php?postId=435&postType=wp_navigation
```

Screen Shot 2023-07-04 at 13 25 40

All I need do is inadvertently pass that to `getEntityRecord` and I'll have a cache miss resulting in a network request for no reason (aside: we could guard against this by having to register URL params with specfic types before we can use them).

I definitely see the argument that this isn't 100% critical, but it's a nice quality of life improvement and also guards against performance issues which _definitely_ possible (and potentially even likely, depending on how we store data).

Another alternative is that we trigger a console warning if we suspect a caller is passing the wrong argument type?

Do we think it's worth me committing any more effort here or shall I focus elsewhere?

My opinion is that it _is_ worth it but I'm just one contributor 😄

**Comment by jsnajdr** [comment]
> Is there a lot of places where we use "strings" instead of "numbers" in Gutenberg?

It might be that calling selectors with "wrong" argument types is a very common mistake, it just goes undetected. Because the consequences are not that bad, it's just that the potential resolver is called twice. If your state is stored as an object, then `state[ 1 ]` and `state[ '1' ]` is exactly the same thing, as the numeric key is coerced to a string, so existing state is found and returned by the selector. But the resolution metadata state doesn't know that the selector has already been resolved and resolves it one more time.

It seems to me that mixing up `getEntityRecord( 'postType', 'post', 1 )` and `getEntityRecord( 'postType', 'post', '1' )` is a very easy mistake to make, it really suggests itself.

**Comment by getdave** [comment]
I'll proceed then 🙇‍♂️

**Comment by getdave** [comment]
I'm now stuck with TypeScript in allowing the `normalizeArgs` function to be a property of `GetEntityRecord` type.

File: packages/core-data/src/selectors.ts [hunk 6]
```diff
@@ -275,6 +276,7 @@ export function getEntityConfig(
  * See https://github.com/WordPress/gutenberg/pull/41578 for more details.
  */
 export interface GetEntityRecord {
+	normalizeArgs: ( args: any ) => any;
```
Comment (getdave) [inline packages/core-data/src/selectors.ts]: The `args` here are always an array of arguments passed to `getEntityRecord`. These are:

```
kind: string,
name: string,
key: EntityRecordKey,
query?: GetRecordsHttpQuery
```

...which are defined immediately below.

I guess there's a syntax where I can extract these args to a definition and reuse them?

File: packages/data/README.md [hunk 7]
```diff
@@ -1028,6 +1028,52 @@ function Component() {
 }
 ```
 
+### Normalizing Selector Arguments
```
Comment (getdave) [inline packages/data/README.md:1130]: I don't think I've done a great job here. I'm going to dive back into the code again and fully grok the rationale in order that I can explain it more succienctly. 

In the meantime if anyone feels like offering up corrections it would be greatly appreciated 😅

File: packages/data/README.md [hunk 8]
```diff
@@ -1028,6 +1028,52 @@ function Component() {
...
+	return state.items[name][type][id] || null;
+}
+
+const getItemsResolver = ( name, type, id ) => {
+	// 'id' is also guaranteed to be a number in the resolver.
+	return {};
+}
+
+// Define normalization function.
+getItemsSelector.normalizeArgs = ( args ) {
```
Comment (getdave) [inline packages/data/README.md:1052]: I'm not sure I enjoy the inconsistency here. Perhaps if we spread the `args` when `normalizeArgs` is invoked then we could destructure them which might make things clearer.

```js
getItemsSelector.normalizeArgs = ( { name, type, id } ) {
//
```

File: packages/core-data/src/utils/is-numeric-id.js (hunk 4 above)
Comment (getdave) [reply packages/core-data/src/utils/is-numeric-id.js]: That fails on the following test:

```
// should return false for input ""
expect( isNumericID( '' ) ).toBe( false );
// true
```

This can be tested in console:

```
! isNaN( '' )
// true
```

Comment (getdave) [reply packages/core-data/src/utils/is-numeric-id.js]: Adding a small check for length would solve that I guess.

File: packages/data/src/redux-store/index.js (hunk 5 above)
Comment (getdave) [reply packages/data/src/redux-store/index.js]: I've now "documented" this in this PR but I don't think I've done a great job thus far. Needs improving. Input welcomed.

File: packages/data/src/redux-store/index.js (hunk 2 above)
Comment (getdave) [reply packages/data/src/redux-store/index.js]: ✅

File: packages/data/README.md (hunk 7 above)
Comment (getdave) [reply packages/data/README.md:1130]: Maybe the best approach is to briefly explain that each resolver has its resolution status cached in an internal state where the key is the arguments supplied to the selector at _call time_.

For example for a selector with a single argument the related resolver would generated a cache key of: `[123]`

This cache is used to determine the resolution status of a given resolver which is used to avoid unwanted additional invocations of resolvers (which often undertake "expensive" operations such as network requests).

As a result it's important that arguments remain _consistent_ when _calling_ the selector. For example these two calls will not be cached using the same key, even though they are likely identical:

```js
// Arg as number
getSomeDataById( 123 );

// Arg as string
getSomeDataById( '123' );
```

To help with this selectors can optionally define a `normalizeArgs` property which should be a function which accepts the arguments passed to the selector and returns a normalized form of those same arguments.

...

File: packages/data/src/redux-store/index.js [hunk 9]
```diff
@@ -233,11 +233,24 @@ export default function createReduxStore( key, options ) {
...
+						args = selector.normalizeArgs( args );
+					}
 					const state = store.__unstableOriginalGetState();
 					return selector( state.root, ...args );
 				};
 
+				// Expose normalization method on the bound selector
+				// in order that it can be called when fullfilling
+				// the resolver.
+				boundSelector.normalizeArgs = selector.normalizeArgs;
```
Comment (getdave) [inline packages/data/src/redux-store/index.js]: I don't love this but I couldn't see another way to expose the normalization to the resolver.

File: packages/data/src/redux-store/test/index.js [hunk 10]
```diff
@@ -286,3 +286,75 @@ describe( 'resolveSelect', () => {
...
+			},
+			resolvers: {
+				getItems: () => 'items',
+			},
+		} );
+		registry.select( 'store' ).getItems( 'foo', 'bar' );
+
+		expect( normalizingFunction ).toHaveBeenCalledWith( [ 'foo', 'bar' ] );
+
+		// Needs to be call twice:
```
Comment (getdave) [inline packages/data/src/redux-store/test/index.js]:
```suggestion
		// Needs to be called twice:
```

File: packages/core-data/src/selectors.ts (hunk 6 above)
Comment (jsnajdr) [reply packages/core-data/src/selectors.ts]: I think you'll have to repeat the args, like:
```ts
normalizeArgs: ( kind: string, name: string, key: EntityRecordKey ) => [ string, string, EntityRecordKey ]
```
Also, the `normalizeArgs` field should be optional.

`EntityRecordKey` is `string | number`. To avoid further type complication, we can assume that `normalizeArgs` doesn't change types, i.e., it converts `EntityRecordKey` to the same `EntityRecordKey`. Not a strict `number`.

Comment (jsnajdr) [reply packages/core-data/src/selectors.ts]: Now I realized that `normalizeArgs` takes one argument, the array of `args`. Then you can define the args as tuple:
```ts
type EntityRecordArgs =
  | [ string, string, EntityRecordKey ]
  | [ string, string, EntityRecordKey, GetRecordsHttpQuery ];
```
and use it.

File: packages/data/src/redux-store/index.js (hunk 9 above)
Comment (jsnajdr) [reply packages/data/src/redux-store/index.js]: Don't worry about this for now, I have plans to merge all the binding code into one function. Then the `bindSelector` function would make sure that the `fullfillSelector` call is also there when appropriate. And then `normalizeArgs` will be available as local variable. The ugly code will disappear.

File: packages/data/src/redux-store/index.js [hunk 11]
```diff
@@ -601,6 +614,13 @@ function mapSelectorWithResolver(
 	}
 
 	const selectorResolver = ( ...args ) => {
+		if (
+			selector.normalizeArgs &&
+			typeof selector.normalizeArgs === 'function' &&
+			args?.length
+		) {
+			args = selector.normalizeArgs( args );
+		}
```
Comment (jsnajdr) [inline packages/data/src/redux-store/index.js]: This complex condition could be extracted into a helper, called like `args = normalize( selector, args )`.

Also, the `args?.length` check seems redundant to me. `args` is always a valid array, as it comes from the `...args` spread syntax. And the `normalizeArgs` function must be able to deal with missing parameters anyway.

File: packages/data/README.md (hunk 7 above)
Comment (getdave) [reply packages/data/README.md:1130]: Ok I updated things with:

- better description
- code references

File: packages/data/src/redux-store/index.js (hunk 9 above)
Comment (getdave) [reply packages/data/src/redux-store/index.js]: Thanks for the information 🙇

File: packages/core-data/src/selectors.ts (hunk 6 above)
Comment (getdave) [reply packages/core-data/src/selectors.ts]: OK we now have

```ts
/**
 * Arguments for EntityRecord selectors.
 */
type EntityRecordArgs =
	| [ string, string, EntityRecordKey ]
	| [ string, string, EntityRecordKey, GetRecordsHttpQuery ];
```

```ts
normalizeArgs?: ( args: EntityRecordArgs ) => EntityRecordArgs;
```

File: packages/data/src/redux-store/index.js (hunk 11 above)
Comment (getdave) [reply packages/data/src/redux-store/index.js]: That's a good idea. Now this is duplicated it makes sense to tidy up.

Good spot on the `args.length` 👍 

✅ Done

File: packages/core-data/src/selectors.ts [hunk 12]
```diff
@@ -281,22 +289,23 @@ export interface GetEntityRecord {
...
 	>(
 		state: State,
-		kind: string,
-		name: string,
-		key: EntityRecordKey,
-		query?: GetRecordsHttpQuery
+		kind: EntityRecordArgs[ 0 ],
+		name: EntityRecordArgs[ 1 ],
+		key: EntityRecordArgs[ 2 ],
+		query?: EntityRecordArgs[ 3 ]
```
Comment (getdave) [inline packages/core-data/src/selectors.ts]: @jsnajdr I'm not sure how "legit" this is but it seemed to make sense to reuse the `tuple` args.

File: packages/data/README.md [hunk 13]
```diff
@@ -1028,6 +1028,87 @@ function Component() {
 }
 ```
 
+### Normalizing Selector Arguments
+
+In specific circumstances it may be necessary to normalize the arguments passed to a given _call_ of a selector/resolver pairing.
```
Comment (scruffian) [inline packages/data/README.md:1132]: I'm not sure about the use of the underscores as emphasis. I worry that they might cause more confusion than clarity :)

File: packages/data/src/redux-store/test/index.js [hunk 14]
```diff
@@ -286,3 +286,75 @@ describe( 'resolveSelect', () => {
...
+
+		expect( normalizingFunction ).toHaveBeenCalledWith( [ 'foo', 'bar' ] );
+
+		// Needs to be called twice:
+		// 1. When the selector is called.
+		// 2. When the resolver is fullfilled.
+		expect( normalizingFunction ).toHaveBeenCalledTimes( 2 );
+	} );
+
+	it( 'should not call the normalizeArgs method if there are no arguments passed to the selector (and thus the resolver)', async () => {
```
Comment (getdave) [inline packages/data/src/redux-store/test/index.js]: @jsnajdr I reinstated the `arg?.length` check before calling the `normalizeArgs` method because if I didn't then this test will fail.

File: packages/data/README.md [hunk 15]
```diff
@@ -1028,6 +1028,87 @@ function Component() {
...
+// Call with correct number type.
+registry.select( 'store' ).getItems( 'foo', 'bar', 54 );
+
+// Call with the wrong string type, **but** here we have avoided an
+// wanted resolver call because '54' is guaranteed to have been
+// coerced to a number by the `normalizeArgs` method.
+registry.select( 'store' ).getItems( 'foo', 'bar', '54' );
+```
+
+Ensuring consistency of arguments for a given selector call is [an important optimization to help improve performance in the data layer](https://github.com/WordPress/gutenberg/pull/52120).
```
Comment (scruffian) [inline packages/data/README.md]: I wonder if its also worth adding a comment about why we can't just ensure that we always use an ID?

File: packages/data/README.md (hunk 13 above)
Comment (getdave) [reply packages/data/README.md:1132]: Yeh but that's markdown syntax? 🤷

Comment (getdave) [reply packages/data/README.md:1132]: See https://github.com/WordPress/gutenberg/blob/c6cd22a6bc68658b6597f74d6e52c90b17c961ca/packages/data/README.md#normalizing-selector-arguments

File: packages/data/README.md [hunk 16]
```diff
@@ -1028,6 +1028,87 @@ function Component() {
...
+
+This is an opportunity to utilize the `normalizeArgs` property to guarantee consistency by protecting callers from passing incorrect types.
+
+#### Example
+
+The _3rd_ argument of the following selector is intended to be a `Number`:
+
+```js
+const getItemsSelector = ( name, type, id ) => {
+	// here 'id' is now guaranteed to be a number.
```
Comment (getdave) [inline packages/data/README.md]:
```suggestion
```
We should remove this comment from the example as it's not yet the case!

File: packages/data/README.md (hunk 15 above)
Comment (getdave) [reply packages/data/README.md]: I don't think we can do that _here_ because that's specific to Core Data `getEntityRecord` no? 

How would you word the update you suggest?

**Comment by getdave** [comment]
@tellthemachines I think we should try to land this one for 6.3.

**Comment by getdave** [comment]
FYI I've now found _many_ instances in the Site View where the recordKey is assumed to be an ID when in fact it's being passed as a string. This is causing additional network requests.

I ~will raise~ [have raised a PR to patch these instances](https://github.com/WordPress/gutenberg/pull/52338), but we should look to land this PR as a low level guard against this problem being reintroduced in future.

File: packages/data/README.md (hunk 15 above)
Comment (scruffian) [reply packages/data/README.md]: This normalization is attempting to protect the caller when it is called incorrectly with a string instead of an integer, but ideally the selectors and resolvers should pass their arguments with the correct type.

Comment (getdave) [reply packages/data/README.md]: >  the selectors and resolvers should pass their arguments with the correct type.

I think we could say, many problems can be avoided by selectors avoiding variable types for their args. It's not that the `getEntityRecord` is "doing it wrong" it's just we allowed `recordKey` to be two types. 

In this case it's probably unavoidable but in general if selectors keep consistent type args `normalizeArgs` won't be necessary for those selectors.

Comment (getdave) [reply packages/data/README.md]: ✅

**Comment by getdave** [comment]
We appear to have a legit bug now with URL routing. Debugging now.

The issue is that the `args` are not normalized for the given selector's metadata selector at:

https://github.com/WordPress/gutenberg/blob/cea0afda8a086ba12eb634202ad2a6f771655756/packages/data/src/redux-store/index.js#L255

We won't be able to do that unless we can access the original selector here.

**Comment by getdave** [comment]
The PR checks are now all passing.

Final ✅ now required:

- test that this prevents the additional network requests for `getEntityRecord` (see Testing Instructions).
- test no regressions Navigating around different content types in Site Editor Site View sidebar.
- check the code to ensure that "normalization" is applied in the most efficient place. It seems to be in x3 locations now and I wonder if there's a simpler way?

File: packages/core-data/src/selectors.ts (hunk 12 above)
Comment (jsnajdr) [reply packages/core-data/src/selectors.ts]: I would personally keep the types written out explicitly. I think applying the DRY principle makes the code less readable.

File: packages/core-data/src/utils/is-numeric-id.js (hunk 4 above)
Comment (jsnajdr) [reply packages/core-data/src/utils/is-numeric-id.js]: Also, we want floats like `3.14` to fail the test, they are not numeric IDs.

BTW the `str` argument doesn't need the default `''` value.

File: packages/core-data/src/selectors.ts [hunk 17]
```diff
@@ -370,6 +379,30 @@ export const getEntityRecord = createSelector(
...
+	if (
+		recordKey &&
+		typeof recordKey === 'string' &&
+		isNumericID( recordKey )
+	) {
+		recordKey = Number( recordKey );
+	}
+
+	args[ 2 ] = recordKey;
+	return args;
```
Comment (jsnajdr) [inline packages/core-data/src/selectors.ts]: It's not very nice that the function mutates the `args`. With ES2023 we'll be [able to use](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/with) `return args.with( 2, recordKey )` 🙂

File: packages/core-data/src/selectors.ts [hunk 18]
```diff
@@ -370,6 +379,30 @@ export const getEntityRecord = createSelector(
...
+/**
+ * Normalizes `recordKey`s that look like numeric IDs to numbers.
+ *
+ * @param args EntityRecordArgs the selector arguments.
+ * @return EntityRecordArgs the normalized arguments.
+ */
+getEntityRecord.normalizeArgs = (
+	args: EntityRecordArgs
+): EntityRecordArgs => {
+	let recordKey = args && args[ 2 ];
```
Comment (jsnajdr) [inline packages/core-data/src/selectors.ts]: `args` is always a valid array, the `args &&` check is not needed.

File: packages/core-data/src/selectors.ts [hunk 19]
```diff
@@ -370,6 +379,30 @@ export const getEntityRecord = createSelector(
...
+
+	// If recordKey looks to be a numeric ID then coerce to number.
+	if (
+		recordKey &&
+		typeof recordKey === 'string' &&
+		isNumericID( recordKey )
```
Comment (jsnajdr) [inline packages/core-data/src/selectors.ts]: All three conditions could be encapsulated inside `isNumeridID`, if its body was `typeof id === 'string' && regex.test( id )`.

No need to check if `recordKey` is truthy, both `typeof` and `regex.test` can work with `undefined`.

File: packages/data/src/redux-store/index.js [hunk 20]
```diff
@@ -252,10 +259,24 @@ export default function createReduxStore( key, options ) {
...
-			function bindMetadataSelector( selector ) {
+			function bindMetadataSelector( metaDataSelector ) {
 				const boundSelector = ( ...args ) => {
 					const state = store.__unstableOriginalGetState();
-					return selector( state.metadata, ...args );
+
+					const originalSelectorName = args && args[ 0 ];
+					const originalSelectorArgs = args && args[ 1 ];
+					const targetSelector =
+						options?.selectors?.[ originalSelectorName ];
```
Comment (jsnajdr) [inline packages/data/src/redux-store/index.js:272]: This will not work with private selectors.

File: packages/data/src/redux-store/index.js [hunk 21]
```diff
@@ -252,10 +259,24 @@ export default function createReduxStore( key, options ) {
...
+
+					// Normalize the arguments passed to the target selector.
+					if ( originalSelectorName && targetSelector ) {
+						args[ 1 ] = normalize(
+							targetSelector,
+							originalSelectorArgs
+						);
+					}
+
+					return metaDataSelector( state.metadata, ...args );
```
Comment (jsnajdr) [inline packages/data/src/redux-store/index.js:282]: I wish this code could be moved into the affected metadata selectors themselves. Actually the only one that needs the normalization is `getResolutionState`.

**Comment by draganescu** [comment]
As a thought, it feels like we should have a universal cache key making function instead of relying on ever changing data. Whatever we pass to the function it converts into the same key and it's there where we make sure we work with the same data types.

I am also more with Riad on this, in the sense that the fact that I can pass two types to get same result is not a developer experience enhancement - it's a lie that we build into the framework. I mean whole languages - ahem PHP - had to be rediscovered for trying to be nice and helpful.

I think if you want to optimize your requests read the documentation on the types and how they're cached, if that one extra request is the issue.

File: packages/data/src/redux-store/index.js (hunk 21 above)
Comment (jsnajdr) [reply packages/data/src/redux-store/index.js:282]: One idea: the metadata selectors and the `metadata` state are private, not exposed in any public API, so we can change their parameters. As state, we could pass an object like:
```js
{
  metadata, // the actual state object
  normalizeArgs( selectorName, args ), // a new helper function
}
```
The `bindMetadataSelector` function has access to all registered selectors, their names and `normalizeArgs` functions. So, it can implement the `normalizeArgs` helper as:
```js
function normalizeArgs( selectorName, args ) {
  if ( allSelectors[ selectorName ]?.normalizeArgs ) {
    return allSelectors[ selectorName ].normalizeArgs( args );
  }
  return args;
}
```
and `getResolutionState` can be implemented as:
```js
function getResolutionState( state, selectorName, args ) {
  return state.metadata[ selectorName ].get( state.normalizeArgs( selectorName, args ) );
}
```

**Comment by getdave** [comment]
Thanks for your review @draganescu. Always useful to have more input.

> we should have a universal cache key making function

We _do_ already have this. However we cannot simply mutate the args for _all_ selector calls because in some cases the keys _should_ be strings.

That's why we decided to go with a very targeted approach which effectively allows the developer to create a normalized cache key for a specific scenario. 

It's likely to be something that's rarely used and indeed I'm recommending in the docs (see changeset) that we could avoid it by ensuring selectors have stable argument types. However, there _will_ be selectors that require it.

> I think if you want to optimize your requests read the documentation on the types and how they're cached...

With respect I think that's quite...optimistic. 

Most people (including members of the Core team) will commit code (and have done so) which passes the wrong type of argument to `getEntityRecord`. 

Humans are bad at this type of stuff - that's why we invented TypeScript 😅 . However we cannot use TypeScript here to enforce `number` because by design `recordKey` can be a string or a number.

> ...if that one extra request is the issue.

I believe it _is_ an issue. As you know, not everyone is on a fibre connection. There are _several_ cases in Site View already where we have data in state and we are re-requesting over the network and blocking the UI (i.e. showing a loading spinner) for no reason whatsoever. Imagine that on a slow mobile connection...terrible and _totally_ unnecessary.

It's relatively simple to fix those specific instances in Core (that won't save 3rd party devs though), but we're wide open to them being re-introduced because...not everyone will read the docs.

I've worked on this project for a few years now and I've never _needed_ to deeply understand the underlying resolver caching system in `@wordpress/data`. It's a low level implementation detail that should "just work". [As Jarda said](https://github.com/WordPress/gutenberg/pull/52120#issuecomment-1620180853), asking developers to be mindful of whether they pass `123` or `"123"` to `getEntityRecord` is asking a lot IMHO.

My takeaway is that you are recommending we:

- close this PR 
- fix the instances where we're passing a string as an ID in Core
- improve the docs 
- leave 3rd party developers to catch up

**Comment by draganescu** [comment]
I know not everybody is on a high speed connection but yes, fixing in core to pass the correct kind of argument and allowing people to optimise seems better in the long run than doing a behind the scenes trick. 

> However we cannot simply mutate the args for all selector calls because in some cases the keys should be strings.

I don't understand this. In a caching system the cache key should normally be a string or some int and all the details that make it unique can be mutated to fit inthe algo that build the cache key string or calculate the int. That does mean we can choose to make cacke key for `1` be the same as `'1'` or not. 

Also in terms of strictly posts and CPTs when do IDs have to be strings?

**Comment by jsnajdr** [comment]
> In a caching system the cache key should normally be a string or some int and all the details that make it unique can be mutated to fit inthe algo that build the cache key

In our case we're using [`equivalent-key-map`](https://github.com/aduth/equivalent-key-map) as the cache and this package doesn't serialize the keys into strings. Instead, it creates a tree of nested `Map` objects, and a lookup of a complex key like `[ 'x', { a: 'y' } ]` expands to a chain of primitive `get`s like:
```js
map
  .get( 0 )   // index
  .get( 'x' ) // value
  .get( 1 )   // index
  .get( 'a' ) // prop
  .get( 'y' ) // value
```
The real reason why `'1'` and `1` are considered distinct keys is because the native `Map` considers them distinct.

Could we serialize the key to a string instead? I'm not sure about that. The main questions is whether all possible `args` that selectors could use are serializable to a string. Are the sets of things that "can be a `Map` key" and that "can be serialized to a string" identical?

**Comment by draganescu** [comment]
> The real reason why '1' and 1 are considered distinct keys is because the native Map considers them distinct.

There, this is why manually reconciling this for better DX seems wrong to me.

**Comment by getdave** [comment]
> the native Map considers them distinct

Yes but that's why we're not applying a blanket conversion to the types of data in the key but rather offering an _optional_ escape hatch for very specific circumstances where we _know_ we can improve developer DX (and as a consequence UX) by normalizing the way data is cached.

**Question**: if we don't do this then what other solutions (other than documentation - which I don't see as solution) are available to mitigate these superfluous network requests?

**Comment by draganescu** [comment]
Here is another thing DEFAULT_ENTITY_KEY is `id`. Could assume this is always a number? Keys which are not numbers (strings) usually are not named id, they're `slug` or something else?

**Comment by jsnajdr** [comment]
Another possible solution is that the "normalization" would be named like `.getCacheKey`, and would return a string like `/posts/1`. And maybe we need it only on the resolver after all.

The rationale is that what `getEntityRecord( 'postType', 'post', '1' )` _really_ means is "give me the REST resource at `/wp/v2/posts/1`". It's only the resource URL that matters and nothing else. It doesn't matter how exactly the `1` suffix was produced. Many distincts JS objects generate this value when an expression like `'posts/' + val` or `` `posts/${ val }` `` converts them to a string. It can be `"1"` (string), `1` (number), `[ 1 ]` (array), or `{ toString: () => 1 }` (object).

Therefore, we shouldn't focus too much on the low-level details of what exactly does the `args` array contain. We should focus on what state/cache key is generated from the `args`. The selector will use some key to index the reducer state, and the resolver will use a similar key to track resolution state, and to issue REST requests.

**Comment by getdave** [comment]
> Keys which are not numbers (strings) usually are not named id, they're `slug` or something else?

I believe template parts still use `id` for the `recordKey` but the value is a `string`.

File: packages/core-data/src/utils/is-numeric-id.js (hunk 4 above)
Comment (getdave) [reply packages/core-data/src/utils/is-numeric-id.js]: I've updated to remove the default and added a test case for decimals.

Comment (getdave) [reply packages/core-data/src/utils/is-numeric-id.js]: Just to confirm

```
! isNaN( '3.12' )
// true
```

It should be `false` because we want to check for numeric **IDs** not strict numbers.

File: packages/core-data/src/selectors.ts (hunk 19 above)
Comment (getdave) [reply packages/core-data/src/selectors.ts]: Yes I agree. We should encapsulate that test.

File: packages/data/src/redux-store/index.js (hunk 20 above)
Comment (getdave) [reply packages/data/src/redux-store/index.js:272]: I knew it. The complexity of the code was a clue. Having to jump through so many hoops.

File: packages/data/src/redux-store/index.js (hunk 21 above)
Comment (getdave) [reply packages/data/src/redux-store/index.js:282]: This might be a "simpler" approach. I'll take a look.

**Comment by scruffian** [comment]
If we decide not to go down this route, could we add a warning if we suspect that someone is passing a string instead of an ID?

**Comment by draganescu** [comment]
> I believe template parts still use id for the recordKey but the value is a string.

@getdave that is definitely misleading if the id is actually a slug. If the id is just a number that is given as a string then it's fine to assume id is a number.

@jsnajdr I think that is the way to go:

> the "normalization" would be named like .getCacheKey, and would return a string like /posts/1. 

That is what it should be expected from a caching system, plus I also think your reasoning to cache by REST address is spot on.

**Comment by getdave** [comment]
> That is what it should be expected from a caching system, plus I also think your reasoning to cache by REST address is spot on.

Can I query what the expectation is here? My understanding is that @wordpress/data can have resolvers that can request data from any type of source. It could be GraphQL or anything really. `fetch` over network is just one way to get that data.

So when you said a key of `/posts/1` it made me think that perhaps this wasn't the way to go because that implies a REST endpoint. But actually I think you're saying that `getCacheKey` would allow you to _optionally_ define a custom cache key for a given selector/resolver? So if you're using GraphQL you can come up with whatever cache key works for you, but if - like Core - you are using REST you can use the `URL` as the cache key.

If that's the case then how would we handle `POST` / `PUT` requests where the "args" aren't part of the `url` itself but rather are sent as part of the body?

It would be good to try and reach a reasonable consensus of how the system would operate before committing additional code/work here 🙇

**Comment by jsnajdr** [comment]
> My understanding is that `@wordpress/data` can have resolvers that can request data from any type of source.

The cache key would be very similar, almost identical, to query keys in React Query. There, the query function is also free do anything it wants to get the queried data, and the data are then identified by the query key array.

> If that's the case then how would we handle POST / PUT requests where the "args" aren't part of the url itself but rather are sent as part of the body?

POST/PUT requests are "mutations" rather than "queries". In `@wordpress/data`, they will be triggered by action dispatches, not by selector resolvers. We can quite safely assume that selector resolution means a read-only idempotent GET request.

> It would be good to try and reach a reasonable consensus of how the system would operate before committing additional code/work here

I think it's OK to spend some time trying out several alternative implementations and discussing them in detail. The `.normalizeArgs` API is going to be a public WordPress API, and will be very hard to modify or replace once it is published.

**Comment by getdave** [comment]
> The cache key would be very similar, almost identical, to query keys in React Query.

I'll have to look that up as I've not worked with React Query (although I am _aware_ of it).

> POST/PUT requests are "mutations" rather than "queries". In `@wordpress/data`, they will be triggered by action dispatches, not by selector resolvers. We can quite safely assume that selector resolution means a read-only idempotent GET request.

Ah yes. Thanks for clarifying that one.

> I think it's OK to spend some time trying out several alternative implementations and discussing them in detail. The `.normalizeArgs` API is going to be a public WordPress API, and will be very hard to modify or replace once it is published.

I agree. I miscommunicated here. We should iterate on _other_ potential solutions rather than narrow down on only `normalizeArgs`.

**Comment by felixarntz** [comment]
Sharing my 2 cents, if the core/Gutenberg code does not trigger a warning or throw an exception or anything when you pass a string ID for what should be an integer, then core/Gutenberg should ensure it casts/treats the results accordingly.

In principle I agree that people should read the documentation, but we're working in an ecosystem with 10000s extensions, and it is unreasonable to expect that everyone does. While the purist in me doesn't like this change, I think it makes perfect sense in a WordPress core context.

Many places in older core code have the same problem, not being strict about parameter & return types, but core has historically handled that gracefully. We can always handle that differently in new code, but then we should truly enforce the correct type (e.g. with PHP/JS warnings of exceptions so that it becomes very obvious, not just "requires reading documentation"), which it looks like is not the case here either. So I think casting the ID to an integer is the right call here.

**Review by felixarntz — APPROVED** [review]

**Comment by draganescu** [comment]
I see my "read documentation" take is being repeated over and over and I want to clarify that my main point is that we should make a better keying system for the cache, not that we should hope for people to read the docs. I am no purist, I don't usually read docs, I wanted to make a point in that context 😆

**Comment by draganescu** [comment]
We also have #52338 approved which is solving this for core exclusively.

**Comment by jsnajdr** [comment]
I think that this core data solution is much better than the particular fix in #52338. The only change I'd recommend before merging is prefixing the `normalizeArgs` function name with `__unstable` or `__experimental`. We want to retain the freedom to evolve the API further, and to potentially remove it and replace with something like `resolver.getCacheKey`.

Philosophically, I think being tolerant about exact parameter types is a very good thing in this particular case. "Being strict about types", when forming a value judgment about it, is not always automatically good. The JS language itself is often very liberal about casting numbers to strings. For example, `Object.keys(['x'])` will return an array with a numeric _string_, `'0'`, although the array index should totally be a number. And I can also index arrays with strings, `['x']['0']` will return `'x'`. Therefore, I don't think it's a reasonable expectation from the API user that they will always pass values of exact types, when even the language itself is happy to throw a wrench into it.

**Review by jsnajdr — APPROVED** [review]

**Comment by getdave** [comment]
@jsnajdr Let me get the prefix added. Let's merge that way and then revisit @draganescu's (very valid) points.

File: packages/core-data/src/selectors.ts (hunk 18 above)
Comment (getdave) [reply packages/core-data/src/selectors.ts]: ✅

File: packages/core-data/src/selectors.ts (hunk 12 above)
Comment (getdave) [reply packages/core-data/src/selectors.ts]: ✅ Reverted to inlining

File: packages/core-data/src/selectors.ts (hunk 17 above)
Comment (getdave) [reply packages/core-data/src/selectors.ts]: Screen Shot 2023-07-12 at 09 25 48

TS complains at me if I try to do this...

Comment (jsnajdr) [reply packages/core-data/src/selectors.ts]: Oh yes, sorry for confusing you, the `.with` method is brand new in ES2023, Gutenberg doesn't support it yet. We'll need to upgrade TypeScript (and its type definitions), enable polyfills etc.

For now, you just need to use `args.slice()` or `[ ... args ]` to make a clone:
```js
const normalizedArgs = args.slice();
normalizedArgs[ 2 ] = ...;
return normalizedArgs;
```

Comment (getdave) [reply packages/core-data/src/selectors.ts]: ✅ Updated.

**Comment by getdave** [comment]
I realised this is approved but not merged. I will rebase and see if @jsnajdr is still happy for this to land.

**Comment by jsnajdr** [comment]
Yes, I still like this :+1:

File: packages/data/src/redux-store/index.js (hunk 20 above)
Comment (getdave) [reply packages/data/src/redux-store/index.js:272]: Looking at this again. I don't yet understand why it doesn't work for private selectors.

First step would be writing a test that fails based on what @jsnajdr said above.

With that in place we can fix for private selectors.

File: packages/data/src/redux-store/index.js (hunk 21 above)
Comment (getdave) [reply packages/data/src/redux-store/index.js:282]: Looking here against. The complexity still exists in the `bindMetadataSelector` but we're just making the `getResolutionState` aware of the complexity as well.

I'm probably missing something but I'd like to understand more before I proceed with further refactor.
