### PR TITLE
Components: Adds AccessibleSVG component and use consistently for block icons

### LINKED ISSUE #9372: Provide (and require) block icon component to ensure accessibility attributes are present
Related to #9269 and #9299, specifically: https://github.com/WordPress/gutenberg/issues/9269#issuecomment-415397686

We should create a component that allows developers to supply an SVG or acts like an SVG, but adds required accessibility attributes to it like in #9299. We should be using it (to set an example and avoid regressions like in #9269.

Ideally we could deprecate icon props that don't use our new `<BlockIcon>` component or whatever, so we can have more control over how they're rendered in the future.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #9372

- This PR adds an `AccessibleSVG` component
- Use this component in BlockIcon

Test that the svg icons contain the required A11y props.

### CODE REVIEW

**Comment by jasmussen** [comment]
This is impressive. From my quick testing, it seems like all the block icons had the proper attributes as they need. Fine work! I can't really speak too much for the code — it looks good to me. But from everything else, 👍 👍

Thanks for working on this.

File: packages/block-library/src/subhead/index.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ export const settings = {
 
 	description: __( 'This block is deprecated. Please use the Paragraph block instead.' ),
 
-	icon: <svg role="img" aria-hidden="true" focusable="false" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M7.1 6l-.5 3h4.5L9.4 19h3l1.8-10h4.5l.5-3H7.1z" /></svg>,
+	icon: <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M7.1 6l-.5 3h4.5L9.4 19h3l1.8-10h4.5l.5-3H7.1z" /></svg>,
```
Comment (tofumatt) [inline packages/block-library/src/subhead/index.js]: I get that we don't *have* to use our component directly, but I wonder why we wouldn't. This is less explicit and we're already changing all of the lines 🤷‍♂️

**Review by tofumatt — APPROVED** [review]
I think some documentation around what happens here would be useful as right now this is elegant, but a bit Magic™.

Overall a cool solution though, and definitely one that prevents third-party developers from making mistakes.

I trust you to add some kind of documentation or something, so 👍 with docs. Feel free to ping for further review if needed 😄

File: packages/block-library/src/subhead/index.js (hunk 1 above)
Comment (youknowriad) [reply packages/block-library/src/subhead/index.js]: I don't mind, I was hesitant as well.

File: packages/editor/src/components/block-icon/index.js [hunk 2]
```diff
@@ -18,6 +18,8 @@ function renderIcon( icon ) {
 		}
 
 		return icon();
+	} else if ( icon && icon.type === 'svg' ) {
```
[the remark this answers is not in the document]
Comment (youknowriad) [reply packages/editor/src/components/block-icon/index.js]: I personally don't think it's important enough for people to know precisely that we're adding some props to their SVGs to make them accessible. I guess it doesn't harm to add a mention in the documention but if we do so, we should avoid using `AccessibleSVG` directly in the components because the behavior is documented in that case.

[the remark this answers is not in the document]
Comment (tofumatt) [reply packages/editor/src/components/block-icon/index.js]: That's fair. I think I'd prefer the documentation because it teaches people about an accessibility issue and it means our code can be: 1. a bit leaner (no imports) 2. more idiomatic (regular SVGs)

So maybe just a note of "we add accessibility properties to SVGs" in the block property documentation with a link to the original issue for context or something.

File: packages/block-library/src/subhead/index.js (hunk 1 above)
Comment (tofumatt) [reply packages/block-library/src/subhead/index.js]: As mentioned though, feel free to leave them SVG if you add docs. I think that's probably the better approach, upon reflection.

**Review by tofumatt — APPROVED** [review]
Docs look good; I made a few tweaks (mainly changing a11y to accessibility).

:shipit:

**Comment by afercia** [comment]
> Test that the svg icons contain the required A11y props.

 ❤️

**Comment by caxco93** [comment]
I think we should extract the SVG icons to another package, maybe `@wordpress/icons`. This will increase their reusability and maintainability. Right now I was looking at #9642 and it would require to declare the same SVG again for the `MediaPlaceholder` icon.

Here's [the PR](https://github.com/WordPress/gutenberg/pull/9648) where I extract the SVG icons to a new package 

Then we could simply do it like this 
image

**Comment by jasmussen** [comment]
CC: @gziolo because you mentioned https://github.com/airbnb/babel-plugin-inline-react-svg/blob/master/README.md

**Comment by mtias** [comment]
@youknowriad coming a bit late to this, but I feel this should be just called `Svg` (with capital) as being accessible should be core to all the components we offer.

**Comment by tofumatt** [comment]
That's kinda confusing if you quickly scan it 🤷‍♂️ (`<Svg />` vs `<svg />`), but also the point is the stock SVGs aren't always accessible and the aim of the wrapper is to make them so.
