### PR TITLE
Select Mode: Hide tool selector in the post editor and force design mode

### LINKED ISSUE #66775: Only render the write/design mode control with a template preview
### Description

The “Write” and “Design” mode control appears even when a template is not rendered, though this distinction is less meaningful without a template preview. Showing these controls can be confusing when post content is abstracted from the template, as users expect unrestricted typing. The mode control should be hidden in the editor header whenever the template is not rendered. 

Additionally, “Design” mode should be the default whenever the template preview is off, ensuring a consistent experience.

Hiding the mode control without a rendered template and defaulting to “Design” mode with preview off will simplify the interface, reducing unnecessary options and improving clarity.

### Steps to reproduce

1. Open the site editor or post editor.
2. Switch to a view where no template is rendered.
3. Observe that the “Write” and “Design” mode control is still visible.
4. Turn off the template preview and check the active mode.

### Expected

- The “Write” and “Design” mode control should be removed when a template is not rendered, as the mode distinction is less meaningful.
- “Design” mode should be enabled automatically when turning off the template preview, maintaining consistency as the default mode.

### Visual

This is how to engage the template preview. Within the Site Editor template preview is enabled by default; in the post editor it is not. I'd expect when the template preview is off, the tool is not available and the mode is set to "Design". 

https://github.com/user-attachments/assets/efe01123-a8af-45d4-9e53-6bedfbea40eb

### PR DESCRIPTION
**Pull request by youknowriad**
closes #66775

## What?

The "write/design" mode selector doesn't make a lot of sense in the post editor when only seeing posts and pages... This PR hides the tool selector and forces full design mode in this case.

An exception exists for wp_template post type.

## Testing Instructions

1- Open the post editor
2- Notice there's no tool selector
3- Toggle the "show template" in the sidebar
4- The tool selector appears and you can switch to "write" mode
5- Toggle the template off, and notice that you're back in "design" mode with the tool selector hidden.

### CODE REVIEW

File: packages/block-editor/src/store/selectors.js [hunk 1]
```diff
@@ -2764,8 +2764,11 @@ export function isNavigationMode( state ) {
  * @return {string} the editor mode.
  */
 export const __unstableGetEditorMode = createRegistrySelector(
-	( select ) => () => {
-		return select( preferencesStore ).get( 'core', 'editorTool' );
+	( select ) => ( state ) => {
+		return (
+			state.settings.editorTool ??
```
Comment (ntsekouras) [inline packages/block-editor/src/store/selectors.js:2769]: I like that approach where we don't mess with the preference.

**Review by ntsekouras — APPROVED** [review]
LGTM, thanks!
