### PR TITLE
RangeControl: Fix number input change interaction

### LINKED ISSUE #21549: [ Latest Posts ] Max. number of words control doesn't react to keyboard input
**Describe the bug**
The default value for excerpt display is 55 words. There are three methods available, it seems, to modify that number in the sidebar
1) Slider
2) up/down 1
3) Type in a new value. 

The third method, typing in a new value, doesn't work. 

**To reproduce**
1. Insert Latest Posts block 
2. Open the Block settings sidebar
3. Enable Post Content
4. Check Excerpt 
5. Try modify the number of words displayed with the keyboard

**Expected behavior**
I would have expected that I would be able to modify the number by typing in the right value. 

**Screenshots**
Screen Shot 2020-04-11 at 5 03 43 PM

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 10.15.3
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 80.0.3987.163

**Additional context**
Gutenberg 7.8.1
WordPress 5.4

### PR DESCRIPTION
**Pull request by ItsJonQ**
Screen Capture on 2020-05-04 at 10-20-52

This update fixes the number input field that renders within RangeControl to allow for (keyboard) changes to happen before it gets applied (or submitted). This temporarily bypasses the validation step, which accommodates cases where the current value (e.g. 1) may be lower than the min value (e.g. 10) while typing.

The unit tests have RangeControl have been refactored to use @testing-library/react. This enables more accurate rendering as the (number) input value is applied only on blur or on <kbd>Enter</kbd> keypress.

These changes are important to fix certain RangeControl integrations like the one within the Latest Posts block. The GIF below demos the fix as the user can now type in values like `10`. Previously, this did not work - Each key stroke would have been invalidated (keydown `1`, keydown `0`) in the process of typing `10`.

Screen Capture on 2020-05-04 at 11-48-01

Blurring or pressing <kbd>Enter</kbd> (new) applies the typed change. If valid, the change will go through. If not, the value will reset.

## How has this been tested?

* Updated unit tests to use `@testing-library/react` for more accurate DOM testing
* Tested in Storybook
* Tested in local Gutenberg

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. 

Resolves: https://github.com/WordPress/gutenberg/issues/21549

### CODE REVIEW

File: packages/components/src/range-control/index.js [hunk 1]
```diff
@@ -61,6 +61,7 @@ const BaseRangeControl = forwardRef(
 			onFocus = noop,
 			onMouseMove = noop,
 			onMouseLeave = noop,
+			resetFallbackValue,
```
Comment (aduth) [inline packages/components/src/range-control/index.js:64]: What's the prop needed for? Could we include documentation?

File: packages/components/src/range-control/input-field.js [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+		 *
+		 * Pressing the up/down arrows of the HTML input also triggers a
+		 * change event. However, those values will be (pre)validated by the
+		 * HTML input.
+		 */
+		if ( event.target.checkValidity && ! event.target.checkValidity() ) {
+			return;
+		}
+
+		handleOnSubmit( event );
```
Comment (aduth) [inline packages/components/src/range-control/input-field.js:79]: If I understand "submit" in this context to mean "propagate a value which is valid", I'd worry about the specific word "submit", since it typically carries a very different meaning when considering an input of a form (i.e. the form submission). At least, that was my first impression seeing this.

A word like "commit" or "persist" might be less prone to confusion?

File: packages/components/src/range-control/utils.js [hunk 3]
```diff
@@ -7,6 +7,10 @@ import { clamp, noop } from 'lodash';
  * WordPress dependencies
  */
 import { useCallback, useRef, useEffect, useState } from '@wordpress/element';
+/**
```
Comment (aduth) [inline packages/components/src/range-control/utils.js:10]: Nit:

```suggestion

/**
```

File: packages/components/src/utils/hooks.js [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+ * @return {Array<any, Function>} The controlled value and the value setter.
+ */
+export function useControlledState( initialState ) {
+	const [ state, setState ] = useState( initialState );
+	const stateRef = useRef( initialState );
+
+	useEffect( () => {
+		/**
+		 * Update the internal state if the incoming value changes.
+		 */
```
Comment (aduth) [inline packages/components/src/utils/hooks.js:23]: At one point the JavaScript standards were updated to not be opinionated one way or the other of multi-line comments being formatted as `/*` vs. `//`, but the one which wouldn't be valid except in the case of documenting a function or variable would be the JSDoc `/**` syntax here.

```suggestion
		// Update the internal state if the incoming value changes.
```

```suggestion
		/*
		 * Update the internal state if the incoming value changes.
		 */
```

File: packages/components/src/utils/hooks.js [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+
+/**
+ * Custom hooks for "controlled" components to track and consolidate internal
+ * state and incoming values. This is useful for components that render
+ * `input`, `textarea`, or `select` HTML elements.
+ *
+ * https://reactjs.org/docs/forms.html#controlled-components
+ *
+ * @param {any} initialState The initial state value.
+ * @return {Array<any, Function>} The controlled value and the value setter.
```
Comment (aduth) [inline packages/components/src/utils/hooks.js:14]: I'm not entirely sure this would be the valid syntax for expressing a type of "array of two members, any and function". Typically I'd see this syntax being used more to say something like: An array of strings of any length (`Array<string>`).

I'd have to look closer at the TypeScript/JSDoc docs to confirm.

My instinct instead would be:

```suggestion
 * @return {[*, Function]} The controlled value and the value setter.
```

(`*` and `any` are interchangeable)

File: packages/components/src/utils/hooks.js [hunk 6]
```diff
@@ -0,0 +1,31 @@
+/**
```
Comment (aduth) [inline packages/components/src/utils/hooks.js:1]: Should there be tests and/or documentation for this? It took me some time to understand its purpose, even with the JSDoc for the component function.

File: packages/components/src/range-control/input-field.js [hunk 7]
```diff
@@ -0,0 +1,105 @@
+/**
+ * External dependencies
+ */
+
+import { noop } from 'lodash';
```
Comment (aduth) [inline packages/components/src/range-control/input-field.js:5]: Nit:

```suggestion
import { noop } from 'lodash';

```

**Review by aduth — COMMENTED** [review]
Thanks for jumping on the issue so quickly. I left a few comments, but I'll plan to take a closer look in my morning.

File: packages/components/src/range-control/input-field.js (hunk 2 above)
Comment (ItsJonQ) [reply packages/components/src/range-control/input-field.js:79]: Thank you @aduth ! That makes sense. I think `commit` works! I'll make the update here (as well as my other PR that uses a similar flow)

File: packages/components/src/utils/hooks.js (hunk 6 above)
Comment (ItsJonQ) [reply packages/components/src/utils/hooks.js:1]: Sure thing!! I'll add some tests 😊 
Really appreciate your impressions on this!

**Comment by ItsJonQ** [comment]
@aduth (As always) Thank you for your thorough review!! 

I made a minor update based on a suggestion by @mcsf from another one of my PRs

> Minor point, but this ref might be clearer if named lastInitialState or ``lastInitialStateRef`.

**Comment by ItsJonQ** [comment]
Hai! Following up on this one. Do you folks think this one is ready to land?

Thank you!

File: packages/components/src/range-control/index.js (hunk 1 above)
Comment (aduth) [reply packages/components/src/range-control/index.js:64]: > What's the prop needed for? Could we include documentation?

Still wondering about this one.

File: packages/components/src/utils/hooks.js (hunk 6 above)
Comment (aduth) [reply packages/components/src/utils/hooks.js:1]: Thanks! Tests are of course good to have in any case. In this instance, it was largely because I can sometimes rely on the test case descriptions to inform me of what's expected from the behavior of the utility. It's much clearer now.

File: packages/components/src/range-control/index.js (hunk 1 above)
Comment (ItsJonQ) [reply packages/components/src/range-control/index.js:64]: Ah! Thanks for following up. It's the value to be used if the "Reset" button is clicked.

This was a prop that existed previously, but I guess didn't have docs. I'll add some.

**Review by aduth — APPROVED** [review]
This is definitely an improvement, and appears to resolve #21549 in my testing.

One thing I can't recall is if we'd previously supported temporarily, invalid non-numeric input (i.e. typing letters within these number fields). This doesn't appear to work at all, though it may very well be expected since it's a number input (possibly the browser preventing it).

**Comment by ItsJonQ** [comment]
> One thing I can't recall is if we'd previously supported temporarily, invalid non-numeric input (i.e. typing letters within these number fields). This doesn't appear to work at all, though it may very well be expected since it's a number input (possibly the browser preventing it).

@aduth Thank you so much for reviewing! I just checked a branch with the older version. It appears the `input` was always `type="number"`, which means numbers only (handled by the browser) 😊

**Comment by ItsJonQ** [comment]
Yay! Looks like Travis started. Will merge once Travis is happy.

Thank you for the reviews!
