### PR TITLE
Insertion point bar: hide onBlur and onMouseLeave

### LINKED ISSUE #35536: Add a timeout for the in-between-inserter for cases where the onmouseout isn't invoked
The in-between inserter shows up when you hover between two blocks, and disappears when you move the cursor out from that area:

inserter

However a number of actions can cause this inserter to linger and stay, presumably because mouse action to fade the inserter out again isn't fired. One easy way to reproduce this is is to use the keyboard shortcut to open the list view, control alt O, while the inserter is present:

lingering quick inserter

Other ways to make the inserter linger is when keyboard shortcuts are used to resize the window, or to invoke the web inspector. It also happens if the viewport resizing gets invoked:

lingering

Quite simply, if you move the mouse out from canvas itself fast enough, it will stay around. Occasionally this can cause horizontal or even double scrollbars to appears, as the canvas size is reduced while a stray sibling inserter lingers in the canvas (#30055).

To address this and fade out the sibling inserter in these cases, can we add a timeout that checks if the mouse is over the sibling inserter, and fade it out if not? Are there other solutions?

### LINKED ISSUE #36882: Inserter stays fixed on the screen when scrolling
### Description

When scrolling on the page and I hover to reveal an inserter, the inserter becomes fixed while I would expect it to scroll with the rest of the content.

It just feels jumpy when it doesn't stick to the place:

https://user-images.githubusercontent.com/87168/143483357-02a092c8-b71d-41ab-b7c3-ce342eee47ef.mov

https://user-images.githubusercontent.com/87168/143483569-b1a1425b-3b0c-4f76-9cbf-3417f5ef7853.mov

FYI @jasmussen perhaps this started after making the appender fixed in https://github.com/WordPress/gutenberg/pull/36605 ?

### Step-by-step reproduction instructions

- Go to site editor
- Reveal inserter by mouse hover and scroll with mouse scroll wheel

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- Gutenberg v12.0.1
- Firefox 94 MacOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

### PR DESCRIPTION
**Pull request by ramonjd**
Possibly, in some way, resolves https://github.com/WordPress/gutenberg/issues/35536
Also resolves https://github.com/WordPress/gutenberg/issues/36882

## Description

This PR hides the inserter point via the `hideInsertionPoint` action when the horizontal inserter bar loses focus, or when the mouse leaves.

`hideInsertionPoint` will not fire when the block inserter panel is open.

Kapture 2021-11-25 at 11 49 00

We might not have covered all cases documented in https://github.com/WordPress/gutenberg/issues/35536, and there is no timeout, but it might help to avoid some of the concerns with the persistent inserter bar.

Try it out today!

## How has this been tested?

Take a look at the various scenarios over at https://github.com/WordPress/gutenberg/issues/35536

With the right mouse artistry you might find that the bar persists, but, at least in my testing, it doesn't persist as often with these changes.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by jasmussen** [comment]
My goodness, even as is, this feels like a VAST and profound improvement over what's in trunk. As a reminder, this is how easy it is to stick the sibling inserter in trunk at the moment:
trunk

Here's this branch:

this branch

This feels like a massive forward step. I'd love for this to land as soon as possible! Thank you!

**Review by jasmussen — APPROVED** [review]
Gave it another spin, and in all my testing I saw no downsides to this one. 

The code looks minimal and good. I'd encourage just a quick sanity check from another dev, but honestly this feels good enough to land.

File: packages/block-editor/src/components/block-tools/insertion-point.js [hunk 1]
```diff
@@ -294,6 +300,8 @@ function InsertionPointPopover( {
 			// Forces a remount of the popover when its position changes
 			// This makes sure the popover doesn't animate from its previous position.
 			key={ nextClientId + '--' + rootClientId }
+			onFocusOutside={ maybeHideInserterPoint }
+			onMouseLeave={ maybeHideInserterPoint }
 		>
 			<motion.div
```
Comment (ntsekouras) [inline packages/block-editor/src/components/block-tools/insertion-point.js]: I've started looking at this and I'm not familiar with this code, but I was wondering if you have search for a solution from [motion](https://www.framer.com/docs/gestures/###onhoverend) maybe something like `onHoverEnd={ maybeHideInserterPoint }` in this motion.div?

**Review by ntsekouras — COMMENTED** [review]
Thanks for working on this Ramon! It would be great if @ellatrix shared her thoughts here as she has worked a lot with these parts. Should this be better handled here: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-list/use-in-between-inserter.js#L15?

**Review by apeatling — COMMENTED** [review]
Tried this and I agree is a big improvement. I'm not familiar with the code, so good to get @ellatrix's input if it makes sense in a difference place. Either way this should land once that's done.

File: packages/block-editor/src/components/block-tools/insertion-point.js (hunk 1 above)
Comment (ramonjd) [reply packages/block-editor/src/components/block-tools/insertion-point.js]: > I was wondering if you have search for a solution from motion maybe something like onHoverEnd={ maybeHideInserterPoint } in this motion.div?

Thanks for looking!

I tried it out and I don't see any difference in behaviour, so I don't see any implementation issues with it.

Was there a specific reason why we should prefer motion's eventhandler?

**Comment by ramonjd** [comment]
Thanks for testing, everyone!

>  It would be great if @ellatrix shared her thoughts here as she has worked a lot with these parts. Should this be better handled here: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-list/use-in-between-inserter.js#L15?

Yes, I'm also a newbie in this area of the code so would be interested to hear if there's a better way. I couldn't see how we could attach event to the inserter in that hook.

File: packages/block-editor/src/components/block-tools/insertion-point.js (hunk 1 above)
Comment (ramonjd) [reply packages/block-editor/src/components/block-tools/insertion-point.js]: > Was there a specific reason why we should prefer motion's eventhandler?

Oh, I did find one advantage, aside from the fact that `Popover` doesn't specifically define an `onMouseLeave` event: we can perform an equality check on the even target and the current ref to make sure the event is occurring on the motion div. 

I've pushed that change since I couldn't detect any noticeable divergence in behaviour.

**Comment by ramonjd** [comment]
I removed the `onFocusOutside` for now, mainly because in testing I couldn't detect any noticeable difference without it. 

There is an edge case that this PR does not address: the inserter persists when you click the plus icon and drag your mouse away from it. 

This is because there's an exisiting [onFocus callback](https://github.com/WordPress/gutenberg/blob/9ebdd3719248ae7fc03ad723fa6bee805017545b/packages/block-editor/src/components/block-tools/insertion-point.js#L190) on the motion div that sets `openRef.current = true;`, which is supposed to indicate that the block inserter panel is open.

**Review by ntsekouras — APPROVED** [review]
LGTM, thanks Ramon! Changes are minimal and make for a way better experience.

>There is an edge case that this PR does not address: the inserter persists when you click the plus icon and drag your mouse away from it.

I think we can address this in a follow up, as it's already in trunk. Maybe this should be handled in `useInBetweenInserter` as we are only listening to `mousemove` event and we could add logic for detecting the dragging.
