### PR TITLE
Fix popover not calling onClose on unmount

### LINKED ISSUE #71281: `useFocusOutside` doesn't run callback when unmounted
### Description

When a popover is closed, the `useFocusOutside` hook should call the passed callback, as the popover has been closed.

### Step-by-step reproduction instructions

This manifests in a specific scenario where the popover's base component is unmounted. I have pushed a branch to demonstrate it.

- `git checkout base/popover-test-case`
- Click a navigation block in the site editor to show the appender
- Open the sidebar
- Click the appender for the navigation block within the sidebar
- The popover should open and there should be a "Select Page" placeholder in the canvas for where the new link will go
- Click into the canvas
- The popover should be removed
- Bug: Select Page will still be visible, but it should have been removed. 

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/44f1933f-d568-4689-8c2f-721c7cea9407

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by jeryj**
## What?

Closes  https://github.com/WordPress/gutenberg/issues/71281, which is a blocking issue in https://github.com/WordPress/gutenberg/pull/71163#issuecomment-3191252617

When a popover unmounts, it should call its related onClose, if provided.

## Why?

It makes sense - the popover is closing, so the onClose should be called.

## How?

Remove cancelling the onBlur check when unmounting the popover.

### Testing Instructions for Keyboard

- All popovers should retain the same behavior as they currently do
- To test what this fixes, checkout this branch: `git checkout test/onclose-popover-unmount`. This is a combination of https://github.com/WordPress/gutenberg/pull/71163/ but with [this commit removed that tried to fix this issue with a prop](https://github.com/WordPress/gutenberg/pull/71163/commits/dbeb8b8156153dd010b842959d10c30d6b1d1071).
- Click a navigation block in the site editor to show the appender
- Open the sidebar 
- Click the appender for the navigation block within the sidebar
- The popover should open and there should be a "Select Page" placeholder in the canvas for where the new link will go
- Click into the canvas
- The popover should be removed and the Select Page should be removed (through the onClose that is called when the popover unmounts).

## Screenshots or screencast 

**Before**

https://github.com/user-attachments/assets/44f1933f-d568-4689-8c2f-721c7cea9407

**After**

https://github.com/user-attachments/assets/8d1c62ea-22ae-4c23-bc06-5d64e1c033a9

### CODE REVIEW

**Review by aduth — COMMENTED** [review]
Based on the discussion in #71163, my hope is we could get rid of the timeout altogether, and instead check `event.relatedTarget` synchronously as part of the `onBlur` handler.

Roughly something like:

```tsx
const onBlur = useCallback( ( event ) => {
  if ( ! event.target.contains( event.relatedTarget ) ) {
    onFocusOutside();
  }
} );

return { onBlur };
```

How feasible would that be?

**Comment by ciampo** [comment]
What were the original reasons for the lines of code being deleted?

We need to make sure that this change, which targets a specific use case of the `Popover` component, won't cause regressions in other use cases (since the `useFocusOutside` is a much more general hook)

**Comment by jeryj** [comment]
@ciampo - It fixes the bug we're experiencing in https://github.com/WordPress/gutenberg/pull/71163#discussion_r2278741629 where the popover onClose isn't being called, even though the popover is being closed.

@aduth - I'm looking at the implmentation using just the `onBlur`: `! event.target.contains( event.relatedTarget )`. I think I'll have to pass a ref into it though. I'm seeing `event.target` being logged as the element that is losing focus, and `event.relatedTarget` as the element receiving focus. The container seems hard to parse out since it's all using portals to populate the popover. Is passing a ref from useDialog a viable option here, or would that create too many back compat issues?

**Comment by aduth** [comment]
> The container seems hard to parse out since it's all using portals to populate the popover. Is passing a ref from useDialog a viable option here, or would that create too many back compat issues?

Ah, right. Maybe we want `currentTarget` instead of `target` to make sure the element is the one to which the event is being assigned?

Passing a `ref` might be problematic if the component using the hook has its own ref that it expects to apply, so I'm not sure how far we'd be able to get with that.

**Comment by jeryj** [comment]
@aduth I created an alternative approach using just the onBlur and passing a ref in from the dialog. I'm not sure what all it will break :) https://github.com/WordPress/gutenberg/pull/71256

If the idea works, then maybe we can find an alternate reliable way to access the container.

**Comment by jeryj** [comment]
> @aduth I created an alternative approach using just the onBlur and passing a ref in from the dialog. I'm not sure what all it will break :) https://github.com/WordPress/gutenberg/pull/71256
> 
> If the idea works, then maybe we can find an alternate reliable way to access the container.

I commented this on #71256, but it's appropriate to share here too:

I think running the callback only onBlur is the wrong approach. It should run after focus  resolves (onFocus), because we'll get into weird states where the onClose callback sets states before the onMouseUp event finishes. This means you can't click a button to open the popover, then click the same button to close it (the popover will reopen). I think the trunk approach of queueing and canceling timeouts is a really clever and correct approach to this.

What do you think? Can we move forward with removing the unmount that cancels the blur check which prevents the focus outside onClose callback from running?

**Comment by aduth** [comment]
> What do you think? Can we move forward with removing the unmount that cancels the blur check which prevents the focus outside onClose callback from running?

I was hopeful we could get rid of the timeouts because asynchronous always adds a lot more complexity and room for edge cases (like the one we're dealing with), but realistically I didn't have high confidence we'd be able to do it.

Regardless, I think the change you're presenting is logical; if a component is mounted, it should call `onClose`.

To @ciampo's point, I think it'd help give us confidence if we knew why these were here in the first place, and the potential scope of what might be impacted by the change so we can at least do a spot check on those behaviors not regressing. It could also be helpful to have some sort of test coverage for the type of behavior we're expecting to see (i.e. calls `onClose` on unmount).

**Comment by jeryj** [comment]
@aduth Went digging. Here's what I found:

This concept was first added in 2017 in https://github.com/WordPress/gutenberg/pull/3235. There is no specific mention or explanation of [`componentWillUnmount` cancelling the blur check](https://github.com/WordPress/gutenberg/pull/3235/files#diff-abf08faa9d622650de4925d5d2664ecaa7626d9a9bc86aa65ae071f60c704c02R16-R18). It's mentioned that the HOC is [built upon this closed PR's concept for fixing a blur event bug ](https://github.com/WordPress/gutenberg/pull/2974/)within the Clipboard Button component. The clipboard component _does_ have an[ `componentWillUnmount` that destroys the clipboard contents](https://github.com/WordPress/gutenberg/pull/2974/files#diff-47d2ff2409d037d3d54056d9ba6c3945606af986fa6f7249f1d54cd120586feaL28-L31) (Note linked code is collapesed). It feels like a stretch, but maybe it was scaffolded off the clipboard component, and it didn't cause any obvious issue, so it was left in?

There is no mention of needing it to fix a specific bug. It has just been there since the beginning. Then, [when it was changed to a hook, it was added](https://github.com/WordPress/gutenberg/pull/27369/files#diff-9732f79a944181759774e91a627dc5657483415a8f7dd2a703f16900cec84348R107-R112) because they were rewriting the HOC. [The philosophy to not make changes unless necessary is clear ](https://github.com/WordPress/gutenberg/pull/27369#discussion_r537237292), so the basis for the unmount goes back to the original PR. There is [some related conversation about why the cancelling is happening](https://github.com/WordPress/gutenberg/pull/27369#discussion_r539054687), but it's more for when the callback becomes null rather than the unmounting.

So, I don't see any specific conversation around why specifically it was added or what it fixes. If I were arguing for its inclusion, I would say it's because we shouldn't leave a dangling timeout without being cleaned up. This seems potentially valid?

If so, then a possible fix here isn't to remove the unmount, but to cancel the timeout and then immediately execute the callback:

```
// Cancel blur checks on unmount.
useEffect( () => {
	return () => {
	    cancelBlurCheck();
	    currentOnFocusOutsideRef.current();
	 }   
}, [] );
```

The issues with doing that would be:
- What event do we return for `currentOnFocusOutsideRef.current( event );`?
- `currentOnFocusOutsideRef.current( event );` would run immediately instead of after the next tick. That [causes issues since onClose could run before focus has resolved](https://github.com/WordPress/gutenberg/pull/71256#discussion_r2291104628).

Long story short: Since the unmount cancelling the timeout is causing a bug for us, and I don't see a clear reason why it was added, I feel comfortable with removing the unmount hook if we don't see it causing any new problems.

**Comment by aduth** [comment]
@jeryj Thanks for digging into that, and apologies on behalf of my past self for not leaving more context on the blur cancellation behavior 😅 My sense was that it was a browser-specific quirk ("A blur event's relatedTarget is not reliable in IE11" in #3235), hence hammering so much on the potential removal now that we no longer support IE11.

>Long story short: Since the unmount cancelling the timeout is causing a bug for us, and I don't see a clear reason why it was added, I feel comfortable with removing the unmount hook if we don't see it causing any new problems.

Considering everything you mentioned, I agree that it's best to be consistent in how we're triggering this callback asynchronously, like you have in the proposed implementation.

Have you been able to do some testing on potential impact to other components using this? I see it's not too many, with most of its usage going through the higher-order component (`ComboBox` uses `withFocusOutside`) or higher-level abstractions (`useDialog`, in turn used primarily in `Popover`, but also in `EntitiesSavedStates`).

**Comment by jeryj** [comment]
> Have you been able to do some testing on potential impact to other components using this?

Nothing extensive beyond seeing that all playwright tests pass and clicking around to see if there's any surprising behaviors. I'm hoping our e2e test suite is diverse enough that it would catch if there was a regression somewhere on a flow.

**Comment by getdave** [comment]
I preferred the idea of clearing the timeouts but then immediately triggering the callback.

We could do this "safely" by:

- wrapping the execution of the callback in a `try/catch`
- using `queueMicrotask` to run the callback after the component has unmounted
- using a synthetic event as `event`

 What do you think? Is this taking things too far?

**Comment by jeryj** [comment]
> What do you think? Is this taking things too far?

I think it may be riskier, as the normal flow and unmount flow would be separate. For example:

- `queueMicrotask` might not run at the same time in the cycle as `setTimeout( () => {}, 0 );`
- The original event and synthetic event might not be identical

So, I think the risk of creating a new system to handle unmount that is separate from the default flow is greater than having a  potential uncleared timeout. That's my untested opinion. Very open to being wrong here :)

**Comment by stokesman** [comment]
> If I were arguing for its inclusion, I would say it's because we shouldn't leave a dangling timeout without being cleaned up. This seems potentially valid?

I doubt it's valid in this case. I don't see how this can be a dangling timeout because it's only ever queued if focus had been within the tree. Even when the component will unmount, the `blur` event happens and queues the timeout. The callback should be invoked.

It seems to me the only risk here is a breaking change. Perhaps if someone had created a workaround for this their callback would execute twice though of course that's not necessarily going to break anything.

I think this is a bug fix but I understand the need for caution.

**Review by aduth — COMMENTED** [review]
Personally, I'm generally in favor of this approach if it helps unblock #71163, even if there's additional opportunities to explore with synchronous callbacks, which could be done as iterative improvements. I also see some value in being consistent across the board in how the hook calls the callback (rather than a mix of some synchronous and some asynchronous callbacks).

While I think this looks good, a couple questions that come to mind in last-minute thoughts about the approach:

- Are there potential issues that could occur if the popover is unmounted because the parent component is also unmounted? I'm imagining `onClose` being called on some parent component that's been unmounted and that parent component callback taking some action like setting state, and causing warnings like "Can't perform a React state update on an unmounted component."
- If this is fixing something and we're relying on tests to give confidence in this not causing regressions, should there not also be some test code revisions here to validate the expected change in behavior?

**Comment by jeryj** [comment]
> Are there potential issues that could occur if the popover is unmounted because the parent component is also unmounted? I'm imagining onClose being called on some parent component that's been unmounted and that parent component callback taking some action like setting state, and causing warnings like "Can't perform a React state update on an unmounted component."

If the parent component using the useFocusCallback is unmounted, would [this effect that cancels the blur check](https://github.com/WordPress/gutenberg/pull/71252/files#diff-ff86e23e91ebf4904d9c61103345eb971caecf569334227d6943e359c67b16e2R90-R95) be triggered, which would cancel the callback? Something like:
- Parent is unmounted
- `onFocusOutside` (the callback) becomes null? (I'm not sure this is what happens)
- The `useEffect` with the `onFocusOutside` dependency changes, cancelling the blur check.
- `setTimeout` doesn't run. 

> If this is fixing something and we're relying on tests to give confidence in this not causing regressions, should there not also be some test code revisions here to validate the expected change in behavior?

Yup! That should be the case. I'll get a test that demonstrate the callback runs on unmount.

**Comment by aduth** [comment]
>onFocusOutside (the callback) becomes null? (I'm not sure this is what happens)

I'm not sure either 😄 which is the concern. My hunch is that the function still exists, and that this is the exact sort of scenario why the warning message exists in React in the first place.

**Review by getdave — APPROVED** [review]
I'm going to take a leap and approve this one. 

**Update**: I added some unit tests coverage, although I'd appreciate a confidence check that it's covering what I think it's covering 😅 

I have removed all custom implementation from https://github.com/WordPress/gutenberg/pull/71163. I then applied this PR to that one. I then added a temporary `setState` call to the `onClose` callback to see if the unmount of the parent would cause React to fire its warning:

```jsx
<LinkUI
			clientId={ insertedBlock?.clientId }
			link={ insertedBlock?.attributes }
			onBlockInsert={ handleSetInsertedBlock }
			onClose={ () => {
				// Use cleanup function
				cleanupInsertedBlock();
				setRandomState( 'crash all the things!' );
			} }
....
```

I did not see any warning. I don't think this is necessarily conclusive proof that we'll never encounter such a scenario but it's a good indicator.

There also seems to be a general consensus that the chances of bugs are relatively low and that we should ship and iterate on improve the approach if issues are uncovered.

If anyone disagrees please let us know, otherwise I'll let @jeryj press the merge button when he's online later today.

**Comment by Mamaduka** [comment]
> Can't perform a React state update on an unmounted component.

React no longer triggers `setState` warnings, since version 18.

File: packages/compose/src/hooks/use-focus-outside/test/index.js [hunk 1]
```diff
@@ -130,11 +130,19 @@ describe( 'useFocusOutside', () => {
...
+
+		// Immediately unmount the component while the blur event is queued
+		// The callback should still be called.
 		unmount();
 
-		expect( mockOnFocusOutside ).not.toHaveBeenCalled();
+		// Wait for the queued timeout to execute
+		await new Promise( ( resolve ) => setTimeout( resolve, 10 ) );
+
+		expect( mockOnFocusOutside ).toHaveBeenCalled();
```
Comment (aduth) [inline packages/compose/src/hooks/use-focus-outside/test/index.js]: I'd discourage a real-time sleep like this, both because it's pretty fragile, and because it artificially prolongs the test runtime (although not by much in this case).

Could we do something where we set up the mock implementation to finish the test? Either using [the `done` callback](https://jestjs.io/docs/asynchronous#callbacks), or maybe something with [`Promise.withResolvers`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers), e.g.

```ts
const { promise, resolve } = Promise.withResolvers();
mockOnFocusOutside.mockImplementation( resolve );
unmount();
await promise;
```

**Review by aduth — APPROVED** [review]
> > Can't perform a React state update on an unmounted component.
>
>React no longer triggers setState warnings, since version 18.

Thanks @Mamaduka , I overlooked that. Based on [the context of that change](https://github.com/reactwg/react-18/discussions/82) and some more thought about my previous concerns, the sense I have is that: If a component using `useFocusOutside` unmounts because its parent unmounts, any callbacks on that parent will still be called, even though its unmounted. That could cause some unintentional side-effects depending on what those callbacks are doing, but in the case of React-related effects like `setState`, they'll be effectively treated as a no-op (and no longer log as of v18). It feels like a pretty low risk overall.

**Comment by Mamaduka** [comment]
@aduth, yes, the local React shouldn't be a problem. I guess this would be a breaking change for users who have more complex `onClose` callbacks, though I hope that's rare.

P.S. I was debugging an odd inserter bug, which reminded me of this PR - https://github.com/WordPress/gutenberg/issues/65598#issuecomment-3249229264.

File: packages/compose/src/hooks/use-focus-outside/test/index.js (hunk 1 above)
Comment (Mamaduka) [reply packages/compose/src/hooks/use-focus-outside/test/index.js]: The `withResolvers` is such a nice addition to the promises ⭐

Comment (getdave) [reply packages/compose/src/hooks/use-focus-outside/test/index.js]: TIL about `withResolvers()`. Thanks!

Comment (getdave) [reply packages/compose/src/hooks/use-focus-outside/test/index.js]: Looks like `Promise.withResolvers()` is only available in Node.js 22+, but the project requires Node.js >=20.10.0. This was leading to unit test failures on CI.

I've reverted to using the traditional manual deferred promise pattern for better compatibility.
