### PR TITLE
Pattern Inserter: Fix pattern list overflow

### LINKED ISSUE #65189: Pattern Inserter: Pattern list is not scrollable
### Description

The pattern list is not scrollable. Instead, the scrollbar will appear on the editor canvas:

patterns_1

If you scroll down using this scroll bar, you will notice that the pattern list is overflowing:

pattern_2

### Step-by-step reproduction instructions

- Open the site editor or the post editor
- Main inserter > Patterns tab > Click on one of the pattern categories

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #65189
Follow-up #65115

## What?

This PR fixes an issue where the pattern list could not be scrolled correctly when opened from the pattern inserter.

## Why?

The following CSS is expected to make the `BlockPatternsList` scroll automatically if the content is long:

https://github.com/WordPress/gutenberg/blob/57e0b9cb658669e2bcc8d4cb2daa537e7d678d4b/packages/block-editor/src/components/inserter/style.scss#L340-L345

However, it appears that this component was wrapped by the `VStack` component, causing unintended behavior.

## How?

~~There are probably a few different approaches we could take, but adding `overflow:hidden` to a VStack component seems like the easiest approach.~~ Based on [this discussion](https://github.com/WordPress/gutenberg/pull/65192#discussion_r1751916904), I removed the `VStack` component and applied a bottom padding to the text instead.

## Testing Instructions

- Open the Site Editor or Post Editor
- Main Inserter > Patterns tab > click any pattern category
- Make sure the pattern category is scrollable
- Enable Zoom Out experiment
- Open the Site Editor
- Enable "Desktop (50%)" view
- Main Inserter > Patterns tab > click any pattern category
- Make sure the pattern category is scrollable

### Before

https://github.com/user-attachments/assets/f69da219-abc8-4c7a-97d1-2f52ddd32081

### After

https://github.com/user-attachments/assets/fce6c3cd-e080-4e04-bb1c-75e511279768

### CODE REVIEW

File: packages/block-editor/src/components/inserter/block-patterns-tab/pattern-category-previews.js [hunk 1]
```diff
@@ -170,7 +170,10 @@ export function PatternCategoryPreviews( {
 					</Text>
 				) }
 			</VStack>
-			<VStack spacing={ 4 }>
+			<VStack
+				spacing={ 4 }
+				className="block-editor-inserter__patterns-category-panel-body"
+			>
```
Comment (getdave) [inline packages/block-editor/src/components/inserter/block-patterns-tab/pattern-category-previews.js]: Oh wow. I didn't see that side effect. I'd be happy to remove the `VStack` and apply the spacing manually to the help text. Especially as that only appears in Zoom Out mode.

Comment (t-hamano) [reply packages/block-editor/src/components/inserter/block-patterns-tab/pattern-category-previews.js]: I removed the `VStack` component and applied a bottom padding to the text instead. What do you think?

image

**Review by getdave — APPROVED** [review]
Looks good. Thanks for the quick fix.
