### PR TITLE
`ColorPalette`: show `Clear` button even when `colors` array is empty

### LINKED ISSUE #45928: ColorPalette: Clear button doesn't show when default colors array is empty
### Description

I am developing a custom Gutenberg block, and using the [ColorPalette](https://developer.wordpress.org/block-editor/reference-guides/components/color-palette/) component for some color attributes. The ColorPallete doesn't show the clear button if the `colors` props is empty or not set. The `clearable` property is not honored in this case. Whereas if the `colors` is set to at least one default color object, the clearable also works as expected.

### Step-by-step reproduction instructions

In order to reproduce the issue, you need to add the following ColorPalette code in any test Gutenberg Block's edit.js file:

```jsx
<ColorPalette
    value={ color }
    onChange={ ( color ) => setColor( color ) }
    clearable = {true} // Regardless of true or false, this prop is not honored
/>
```

The following code will work when the colors prop is set to at least one default color object:

```jsx
<ColorPalette
    colors={ [
        { name: 'Red', color: '#f00' }
    ]}
    value={ color }
    onChange={ ( color ) => setColor( color ) }
/>
```

### Screenshots, screen recording, code snippet

colorpalette

### Environment info

- WordPress v6.1.1. Gutenberg as comes with this version of WordPress
- Chrome v 107.0.5304.107
- Desktop with Windows 10

Similar issue was addressed in #40960 but in this case the `clearable` props is not honored. So that one doesn't solve the issue.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ciampo**
## What?

Fixes #45928 by showing the `Clear` button in `ColorPalette` even when the array of `colors` is empty.

## Why?

Fixing a regression introduced in #44632 

## How?

- Removed the check that was forcing the component not to render `CircularOptionPicker`, which was effectively the source of the regression
- Fixed an issue in the Storybook example, which was causing the example to crash when `colors=[]`
- Added a unit test to prevent this regression from happening again
- In the process, tidied up a little the unit tests file (including changing example colors to be less US-centric)

## Testing Instructions

- Try to reproduce the bug flagged in #44632 — the bug should not be reproducible
- Make sure that new test makes sense

## Screenshots

| Before (trunk) | After (this PR) |
|---|---|
| Screenshot 2022-11-23 at 12 41 09 | Screenshot 2022-11-23 at 12 40 33 |

### CODE REVIEW

File: packages/components/src/color-palette/test/index.tsx [hunk 1]
```diff
@@ -153,12 +161,40 @@ describe( 'ColorPalette', () => {
...
+			<ColorPalette
+				colors={ EXAMPLE_COLORS }
+				value={ INITIAL_COLOR }
+				onChange={ onChange }
+			/>
+		);
+
+		expect(
+			screen.getByRole( 'button', { name: 'Clear' } )
+		).toBeInTheDocument();
```
Comment (tyxla) [inline packages/components/src/color-palette/test/index.tsx]: Is this part of the test relevant? Won't it be the same if we remove it and just render once with `colors: []`?

**Review by tyxla — APPROVED** [review]
Tests well and code looks good 🚀 Thanks for the fix!

**Comment by tyxla** [comment]
Note that the failing check is not related to this PR and I've filed a fix for it in #45999.

File: packages/components/src/color-palette/test/index.tsx (hunk 1 above)
Comment (ciampo) [reply packages/components/src/color-palette/test/index.tsx]: I thought it was relevant because we never check for the `Clear` button to be visible by default — do you think it would be better to split the check to a separate test?

Comment (tyxla) [reply packages/components/src/color-palette/test/index.tsx]: Okay, that makes sense. And I agree a separate test would be better - it would help express the intentions better. We don't seem to earn anything by re-rendering and staying in the same test.

Comment (ciampo) [reply packages/components/src/color-palette/test/index.tsx]: Done in https://github.com/WordPress/gutenberg/pull/46001/commits/b6bae63553b3dac60b4e6fcd32fd718cea158511

File: packages/components/src/color-palette/test/index.tsx [hunk 2]
```diff
@@ -153,12 +161,38 @@ describe( 'ColorPalette', () => {
...
+	} );
+
+	it( 'should show the clear button even when `colors` is an empty array', () => {
+		const onChange = jest.fn();
+
+		render( <ColorPalette colors={ [] } onChange={ onChange } /> );
```
Comment (tyxla) [inline packages/components/src/color-palette/test/index.tsx:192]: Do we even need the `onChange` if we render no color option pickers?

Comment (ciampo) [reply packages/components/src/color-palette/test/index.tsx:192]: It's a required prop, so I'm afraid we do 🤷

File: packages/components/src/color-palette/stories/index.tsx [hunk 3]
```diff
@@ -43,10 +43,20 @@ const Template: ComponentStory< typeof ColorPalette > = ( {
 	onChange,
 	...args
 } ) => {
-	const firstColor =
-		( args.colors as ColorObject[] )[ 0 ].color ||
-		( args.colors as PaletteObject[] )[ 0 ].colors[ 0 ].color;
-	const [ color, setColor ] = useState< string | undefined >( firstColor );
+	let initialColor;
+	if ( args.color?.length ) {
```
Comment (mirka) [inline packages/components/src/color-palette/stories/index.tsx]: I assume we mean this?

```suggestion
	if ( args.colors?.length ) {
```

File: packages/components/src/color-palette/stories/index.tsx [hunk 4]
```diff
@@ -43,10 +43,20 @@ const Template: ComponentStory< typeof ColorPalette > = ( {
...
+		const asColorObject = ( args.colors as ColorObject[] )?.[ 0 ].color;
+		let asPaletteObject;
+
+		if ( ( args.colors as PaletteObject[] )[ 0 ].colors?.length ) {
+			asPaletteObject = ( args.colors as PaletteObject[] )[ 0 ]
+				.colors[ 0 ].color;
+		}
+
+		initialColor = asColorObject || asPaletteObject;
```
Comment (mirka) [inline packages/components/src/color-palette/stories/index.tsx]: I personally find it more readable if we just added some question marks to the original code — what do you think?

```tsx
	const initialColor =
		( args.colors as ColorObject[] )?.[ 0 ]?.color ||
		( args.colors as PaletteObject[] )?.[ 0 ]?.colors[ 0 ].color;
```

FWIW I'm also fine with removing this "initial color" selection logic altogether. It's not part of the default component logic, and it's probably not a common use case either.

**Review by mirka — COMMENTED** [review]
Thanks for the quick fix!

File: packages/components/src/color-palette/stories/index.tsx (hunk 3 above)
Comment (ciampo) [reply packages/components/src/color-palette/stories/index.tsx]: Woops! Good spot

File: packages/components/src/color-palette/stories/index.tsx (hunk 4 above)
Comment (ciampo) [reply packages/components/src/color-palette/stories/index.tsx]: I'd rather remove it altogether, to be honest — done in https://github.com/WordPress/gutenberg/pull/46001/commits/5be28fbc2e2686c193e1511f5aac588aa0b29e7d
