### PR TITLE
Navigation: Fix issue creating front-end markup

### LINKED ISSUE #18604: Navigation: Markup is broken
Markup is broken since it doesn't escape the characters in the link title.

Screen Shot 2019-11-19 at 8 26 45 AM

### PR DESCRIPTION
**Pull request by retrofox**
## Description

It fixes a bug when the link has special chars escaping them applying the esc_attr() function.

Fixes https://github.com/WordPress/gutenberg/issues/18604

## How has this been tested?

Add a link from a post or page where its menu has a special char, for instance `<`, `>`, etc

**Before**
Confirm that it breaks the markup in the front-end:

Screen Shot 2019-11-19 at 9 33 04 AM

**After**
The markup should be ok.

Screen Shot 2019-11-19 at 9 34 35 AM

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.

### CODE REVIEW

**Review by getdave — APPROVED** [review]
Nice work @retrofox 👍

**Review by draganescu — APPROVED** [review]
All attributes should go through `esc_attr` indeed :)

File: packages/block-library/src/navigation/index.php [hunk 1]
```diff
@@ -89,10 +89,10 @@ function build_navigation_html( $block, $colors ) {
 
 		// Start appending HTML attributes to anchor tag.
 		if ( isset( $block['attrs']['url'] ) ) {
-			$html .= ' href="' . $block['attrs']['url'] . '"';
+			$html .= ' href="' . esc_attr( $block['attrs']['url'] ) . '"';
```
Comment (obenland) [inline packages/block-library/src/navigation/index.php]: This should be `esc_url()`

File: packages/block-library/src/navigation/index.php [hunk 2]
```diff
@@ -103,7 +103,7 @@ function build_navigation_html( $block, $colors ) {
 		// Start anchor tag content.
 		$html .= '>';
 		if ( isset( $block['attrs']['label'] ) ) {
-			$html .= $block['attrs']['label'];
+			$html .= esc_attr( $block['attrs']['label'] );
```
Comment (obenland) [inline packages/block-library/src/navigation/index.php]: Feel free to use `esc_html()` here, since we're not in an attribute

**Review by obenland — CHANGES_REQUESTED** [review]

**Review by obenland — APPROVED** [review]
