### PR TITLE
Fix CodeEditor not loading when WordPress is installed in a subfolder

### LINKED ISSUE #5374: Custom HTML blocks don't load when WordPress is served out of a subdirectory
## Issue Overview
With 2.3.0 the Custom HTML block is not working at all. 
Attempting to insert the block produces "This block has encountered an error and cannot be previewed."

## Steps to Reproduce (for bugs)

1. Install 2.3.0 in Windows server
2. Attempt to insert a Custom HTML block

## Expected Behavior
Custom HTML block appears

## Current Behavior
- Error dialog and messages in the Chrome console.
```
Uncaught TypeError: Cannot read property 'initialize' of undefined
The above error occurred in the <t> component:
Uncaught TypeError: Cannot read property 'on' of undefined
```
- Different messages in the Firefox console
```
TypeError: wp.codeEditor is undefined
The above error occurred in the <t> component:
TypeError: this.editor is undefined
```
- Fails with the built version of the plugin and latest git extracts and builds.
- Works fine on a hosted site - AIX server.

## Todos
- [ ] Tests
- [ ] Documentation

### LINKED ISSUE #6737: CodeEditor component warns on missing onChange
Coming from here https://wordpress.slack.com/archives/C02QB2JS7/p1526301453000491?thread_ts=1526050915.000297&cid=C02QB2JS7

When creating a post type with a template using the following code

```
function myplugin_register_lorem_post_type() {
    $args = array(
        'public' => true,
        'label'  => 'Lorems',
        'show_in_rest' => true,
        'template' => array(
            array( 'core/html', array(
                'content' => '<p>Hello</p>'
            ) ),
        ),
    );
    register_post_type( 'lorem', $args );
}
add_action( 'init', 'myplugin_register_lorem_post_type' );
```

I get the following console error

```
Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
    in textarea (created by CodeEditor)
    in CodeEditor (created by LazyCodeEditor)
    in LazyCodeEditor
    in div
    in Unknown (created by WithState(Component))
    in WithState(Component) (created by Edit)
    in Edit (created by WithToolbarControls(Edit))
    in WithToolbarControls(Edit) (created by WithInspectorControl(WithToolbarControls(Edit)))
    in WithInspectorControl(WithToolbarControls(Edit)) (created by WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit))))
    in WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit))) (created by modifyCustomHTMLBlock)
    in modifyCustomHTMLBlock
    in Unknown (created by WithDispatch(Component))
    in WithDispatch(Component) (created by WithUseOnceValidation(modifyCustomHTMLBlock))
    in WithUseOnceValidation(modifyCustomHTMLBlock) (created by WithFilters(Edit))
    in WithFilters(Edit) (created by BlockEdit)
    in BlockEdit (created by WrappedComponent)
    in WrappedComponent (created by WithApiData(WrappedComponent))
    in WithApiData(WrappedComponent) (created by WithSelect(WithApiData(WrappedComponent)))
    in WithSelect(WithApiData(WrappedComponent)) (created by BlockListBlock)
    in BlockCrashBoundary (created by BlockListBlock)
    in div (created by IgnoreNestedEvents)
    in IgnoreNestedEvents (created by BlockListBlock)
    in div (created by IgnoreNestedEvents)
    in IgnoreNestedEvents (created by BlockListBlock)
    in BlockListBlock (created by WithHoverAreasComponent)
    in WithHoverAreasComponent (created by (BlockListBlock))
    in (BlockListBlock) (created by WithAlign((BlockListBlock)))
    in WithAlign((BlockListBlock)) (created by WithFilters((BlockListBlock)))
    in WithFilters((BlockListBlock)) (created by WithViewportMatch(WithFilters((BlockListBlock))))
    in WithViewportMatch(WithFilters((BlockListBlock))) (created by WithDispatch(WithViewportMatch(WithFilters((BlockListBlock)))))
    in WithDispatch(WithViewportMatch(WithFilters((BlockListBlock)))) (created by WithSelect(WithDispatch(WithViewportMatch(WithFilters((BlockListBlock))))))
    in WithSelect(WithDispatch(WithViewportMatch(WithFilters((BlockListBlock))))) (created by BlockListLayout)
    in div (created by BlockListLayout)
    in BlockListLayout (created by WithDispatch(BlockListLayout))
    in WithDispatch(BlockListLayout) (created by WithSelect(WithDispatch(BlockListLayout)))
    in WithSelect(WithDispatch(BlockListLayout)) (created by WithSelect(WithSelect(WithDispatch(BlockListLayout))))
    in WithSelect(WithSelect(WithDispatch(BlockListLayout))) (created by BlockList)
    in BlockList (created by VisualEditor)
    in div (created by ObserveTyping)
    in ObserveTyping (created by WrappedComponent)
    in WrappedComponent (created by WithDispatch(WrappedComponent))
    in WithDispatch(WrappedComponent) (created by WithSelect(WithDispatch(WrappedComponent)))
    in WithSelect(WithDispatch(WrappedComponent)) (created by VisualEditor)
    in div (created by WritingFlow)
    in div (created by WritingFlow)
    in WritingFlow (created by WithDispatch(WritingFlow))
    in WithDispatch(WritingFlow) (created by WithSelect(WithDispatch(WritingFlow)))
    in WithSelect(WithDispatch(WritingFlow)) (created by VisualEditor)
    in div (created by BlockSelectionClearer)
    in BlockSelectionClearer (created by WithDispatch(BlockSelectionClearer))
    in WithDispatch(BlockSelectionClearer) (created by WithSelect(WithDispatch(BlockSelectionClearer)))
    in WithSelect(WithDispatch(BlockSelectionClearer)) (created by VisualEditor)
    in VisualEditor (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by WithViewportMatch(Layout))
    in WithViewportMatch(Layout) (created by _class)
    in div (created by _class)
    in _class (created by WithDispatch(_class))
    in WithDispatch(_class) (created by WithSelect(WithDispatch(_class)))
    in WithSelect(WithDispatch(_class)) (created by Editor)
    in ErrorBoundary (created by Editor)
    in RichTextProvider (created by EditorProvider)
    in SlotFillProvider (created by EditorProvider)
    in APIProvider (created by EditorProvider)
    in DropZoneProvider (created by EditorProvider)
    in EditorProvider (created by WithDispatch(EditorProvider))
    in WithDispatch(EditorProvider) (created by Editor)
    in Editor (created by WithSelect(Editor))
    in WithSelect(Editor)
printWarning @ react-dom.cca5b42c.js:526
warning @ react-dom.cca5b42c.js:550
checkPropTypes @ react-dom.cca5b42c.js:2980
ReactControlledValuePropTypes.checkPropTypes @ react-dom.cca5b42c.js:3024
initWrapperState$2 @ react-dom.cca5b42c.js:13765
setInitialProperties$1 @ react-dom.cca5b42c.js:15540
finalizeInitialChildren @ react-dom.cca5b42c.js:16817
completeWork @ react-dom.cca5b42c.js:9823
completeUnitOfWork @ react-dom.cca5b42c.js:12117
performUnitOfWork @ react-dom.cca5b42c.js:12277
workLoop @ react-dom.cca5b42c.js:12289
renderRoot @ react-dom.cca5b42c.js:12320
performWorkOnRoot @ react-dom.cca5b42c.js:12895
performWork @ react-dom.cca5b42c.js:12816
performSyncWork @ react-dom.cca5b42c.js:12793
requestWork @ react-dom.cca5b42c.js:12693
scheduleWorkImpl @ react-dom.cca5b42c.js:12568
scheduleWork @ react-dom.cca5b42c.js:12528
enqueueSetState @ react-dom.cca5b42c.js:7090
Component.setState @ react.57836462.js:492
(anonymous) @ index.js:70
Promise.then (async)
componentDidMount @ index.js:68
commitLifeCycles @ react-dom.cca5b42c.js:10230
commitAllLifeCycles @ react-dom.cca5b42c.js:11901
callCallback @ react-dom.cca5b42c.js:140
invokeGuardedCallbackDev @ react-dom.cca5b42c.js:178
invokeGuardedCallback @ react-dom.cca5b42c.js:227
commitRoot @ react-dom.cca5b42c.js:12040
completeRoot @ react-dom.cca5b42c.js:12948
performWorkOnRoot @ react-dom.cca5b42c.js:12898
performWork @ react-dom.cca5b42c.js:12816
performSyncWork @ react-dom.cca5b42c.js:12793
requestWork @ react-dom.cca5b42c.js:12693
scheduleWorkImpl @ react-dom.cca5b42c.js:12568
scheduleWork @ react-dom.cca5b42c.js:12528
scheduleRootUpdate @ react-dom.cca5b42c.js:13156
updateContainerAtExpirationTime @ react-dom.cca5b42c.js:13184
updateContainer @ react-dom.cca5b42c.js:13211
ReactRoot.render @ react-dom.cca5b42c.js:16647
(anonymous) @ react-dom.cca5b42c.js:17066
unbatchedUpdates @ react-dom.cca5b42c.js:13003
legacyRenderSubtreeIntoContainer @ react-dom.cca5b42c.js:17062
render @ react-dom.cca5b42c.js:17121
initializeEditor @ index.js:90
(anonymous) @ post-new.php?post_type=lorem:3738
```

### PR DESCRIPTION
**Pull request by ajitbohra**
## Description
- Fixes #6737 
- Fixes #5374 codemirror scripts not loading when WordPress is installed in a subfolder
## How has this been tested?
Manual

## Types of changes
Bug fixes

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

File: components/code-editor/editor.js [hunk 1]
```diff
@@ -99,12 +99,12 @@ class CodeEditor extends Component {
 		}
 
 		if ( ! this.props.focus && this.editor.hasFocus() ) {
-			document.activeElement.blur();
+			document.activeElement.change();
```
Comment (noisysocks) [inline components/code-editor/editor.js]: `HTMLElement` doesn't have a `change()` method, so this would always result in an `undefined is not a function` exception.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement

File: components/code-editor/editor.js [hunk 2]
```diff
@@ -99,12 +99,12 @@ class CodeEditor extends Component {
...
 		}
 	}
 
 	render() {
-		return <textarea ref={ ( ref ) => ( this.textarea = ref ) } value={ this.props.value } />;
+		return <textarea ref={ ( ref ) => ( this.textarea = ref ) } value={ this.props.value } onChange={ this.props.onChange } />;
```
Comment (noisysocks) [inline components/code-editor/editor.js]: We're calling `this.props.onChange()` both here in the text field's `onChange` handler and also in our `this.editor.on( 'change', ... )` handler. I fear that this means we're calling `this.props.onChange()` twice on every keystroke. 

I think that a better approach would be to make this text area an uncontrolled component and then let CodeMirror be solely responsible for handling user input and dispatching its `change` event.

```js
return <textarea ref={ ( ref ) => ( this.textarea = ref ) } defaultValue={ this.props.value } />;

```

https://reactjs.org/docs/uncontrolled-components.html

**Review by noisysocks — CHANGES_REQUESTED** [review]
Thanks so much for looking into this! ❤️ 

I think that a simpler way to fix https://github.com/WordPress/gutenberg/issues/6737 is to change `components/code-editor/editor.js:107` to use `defaultValue` instead of `value`. We then don't need to worry about changing `onBlur` to `onChange`.

**Comment by ajitbohra** [comment]
@noisysocks 

Thanks for the detailed review and info. Initial thought to use defaultValue but don't know why took that adventurest turn!

Have updated & tested the PR.

**Comment by noisysocks** [comment]
I tested this locally and it looks good to go 👍 

There's one failing snapshot test that we'll need to fix before merging. This should be just a matter of updating the snapshot tests using this command:

```bash
$(npm bin)/jest --config test/unit/jest.config.json --updateSnapshot
```

**Comment by ajitbohra** [comment]
@noisysocks snapshots updated

**Review by noisysocks — APPROVED** [review]

File: components/code-editor/index.js [hunk 3]
```diff
@@ -21,7 +21,7 @@ function loadScript() {
 		}
 
 		const script = document.createElement( 'script' );
-		script.src = `/wp-admin/load-scripts.php?load=${ handles.join( ',' ) }`;
+		script.src = `${ wpApiSettings.schema.url }/wp-admin/load-scripts.php?load=${ handles.join( ',' ) }`;
```
Comment (youknowriad) [inline components/code-editor/index.js]: It's probably not the only place where we use this, but we should move away from using globals. I'm also wondering if the `CodeEditor` belongs in the `components` module since the components module is supposed to be for generic components (without WP dependency?).

Anyway, this is not urgent and will have to be figured out when we move components to an npm dependency anyway. And this is not specific to this component.
