### PR TITLE
DataViews: Fix focus loss when removing all filters or resetting

### LINKED ISSUE #64697: DataViews: focus lost when removing the last filter
### Description

Using the keyboard, when the last filter of DataViews is removed, the focus is lost.

### Step-by-step reproduction instructions

A video with the steps:

https://github.com/user-attachments/assets/68731f14-07d1-493e-bb41-4c90c314dc93

### What I expected instead

That the Filter Toggle gained the focus back.

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/64697

In DataViews when we remove the last visible filter or resetting the filters the focus is lost.
This PR fixes that by focusing the `add filter` toggle when we do the above. I'm reusing the same Button for the filters toggle to have the same `ref`, because based on the visible filters we either render an `add filter` button or a toggle visibility of current filters one.

## Testing Instructions
1. In any list using DataViews add some filters and then:
   1. remove all of the visible filters
   2. reset filters
3. Observe that in both cases the focus is not lost and is added back to the `add filter` button
4. You can try the above with keyboard navigation too.

### CODE REVIEW

File: packages/dataviews/src/components/dataviews-filters/index.tsx [hunk 1]
```diff
@@ -98,47 +100,74 @@ export function FilterVisibilityToggle( {
...
+} ) {
+	// Focus the `add filter` button when unmounts.
+	useEffect(
+		() => () => {
+			buttonRef.current?.focus();
+		},
+		[ buttonRef ]
+	);
+	return (
+		<div className="dataviews-filters__container-visibility-toggle">
```
Comment (ellatrix) [inline packages/dataviews/src/components/dataviews-filters/index.tsx]: Why is this wrapper not always there? It will cause the button to unmount whenever `hasVisibilityFilters` changes. At worst, we could leave an empty div without the class?

Comment (ntsekouras) [reply packages/dataviews/src/components/dataviews-filters/index.tsx]: What do you mean always there? Can you elaborate a bit?

Comment (ellatrix) [reply packages/dataviews/src/components/dataviews-filters/index.tsx]: I mean in both scenarios I think this wrapper div should de present

Comment (ntsekouras) [reply packages/dataviews/src/components/dataviews-filters/index.tsx]: done

File: packages/dataviews/src/components/dataviews-filters/index.tsx [hunk 2]
```diff
@@ -98,51 +100,75 @@ export function FilterVisibilityToggle( {
...
+					filters={ filters }
+					view={ view }
+					onChangeView={ onChangeViewWithFilterVisibility }
+					setOpenedFilter={ setOpenedFilter }
+					trigger={ buttonComponent }
+				/>
+			) : (
+				<FilterVisibilityToggle buttonRef={ buttonRef }>
+					{ buttonComponent }
+					{ hasVisibleFilters && !! view.filters?.length && (
```
Comment (ellatrix) [inline packages/dataviews/src/components/dataviews-filters/index.tsx]: Can't we add this within `FilterVisibilityToggle`? 😃

**Review by ellatrix — APPROVED** [review]

**Comment by afercia** [comment]
I'm seeing that probably something has changed in the 'Patterns' list where, at least for me, the filters panel is initially open and thus focusing on `useEffect` sets initial focus on the `FilterVisibilityToggle` button. Will create a new issue.
