### PR TITLE
Fix lightbox UI disallow editing

### LINKED ISSUE #59797: Lightbox: allow deactivating from third-party plugins
## What problem does this address?

Image blocks offer an option to "expand on click", via the Lightbox feature developed here:
https://github.com/WordPress/gutenberg/issues/51132

Since many other plugins already offer lightbox functionality, it would be useful if those third-party plugins could:

- detect whether Core's Lightbox feature is available so they can deactivate their own implementation in favor of Core;
- deactivate the Lightbox feature and its UI when needed (e.g. when said plugin offers a different lightbox solution that may conflict with Core, yet offer more options).

## What is your proposed solution?

I do not have a solution today, unfortunately.

- It is possible to disable the option in the theme, via `theme.json`. That's not an option in plugins though.

```json
	"settings": {
		"blocks": {
			"core/image": {
				"lightbox": {
					"enabled": false,
					"allowEditing": false
				}
			}
		},
	}
```

- Hooking into `render_block_core/image` isn't enough because the UI remains in the block editor.

- Hooking into `blocks.registerBlockType` like so doesn't seem to work:

```js
/**
 * WordPress dependencies
 */
import { addFilter } from https://github.com/WordPress/gutenberg/tree/master/packages/hooks;

function removeLightbox( settings, name ) {
	if ( name !== 'core/image' ) {
		return settings;
	}

	return {
		...settings,
		lightbox: {
			allowEditing: false,
		},
	};
}

addFilter(
	'blocks.registerBlockType',
	'test/lightbox/remove',
	removeLightbox,
	50 // Adjust the priority to run after any other filters that might override this.
);
```

- Hooking into `block_type_metadata_settings` doesn't work either:

```php
function filter_metadata_registration( $settings, $metadata ) {
	if ($metadata['name'] === 'core/image') {
		 return array_merge($metadata, array(
        	"lightbox" => array(
            	"allowEditing" => false
        	)
    	));
	}
    return $metadata;
};

add_filter( 'block_type_metadata_settings', 'filter_metadata_registration', 5, 2 );
```

### LINKED ISSUE #59837: Lightbox filtering no longer working/isn't disallowing editing
[Pulling this out of a separate issue](https://github.com/WordPress/gutenberg/issues/59797#issuecomment-1994826807) and copying/pasting from @justintadlock  (let's make sure to create separate issues here for 6.5 problems). 

It looks like the filter itself works. However, the implementation in the editor might be broken. I'm testing against WP 6.5 RC2.

This combination isn't disallowing editing:

- `allowEditing`: `false`
- `enabled`: `true`

With those two settings, I'm still able to change the lightbox status of an existing Image block and a newly-added Image block in the editor.

Tested with filter:

```php
add_filter(
	'wp_theme_json_data_theme',
	fn($theme_json) => $theme_json->update_with([
		'version' => 2,
		'settings' => [
			'blocks' => [
				'core/image' => [
					'lightbox' => [
						'allowEditing' => false,
						'enabled'      => true
					]
				]
			]
		]
	])
);
```

I also tested this without the filter but setting it in `theme.json`:

```json
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"settings": {
		"blocks": {
			"core/image": {
				"lightbox": {
					"allowEditing": false,
					"enabled": true
				}
			}
		}
	}
}
```

CC: @artemiomorales 

This is a change in previous behavior from WordPress 6.4 and seems to be a regression and bug to me. I don't know if it's related to a change in the Lightbox toggle in the sidebar to the new location in the Link dropdown. https://github.com/WordPress/gutenberg/pull/57608 Or something else altogether.

### PR DESCRIPTION
**Pull request by artemiomorales**
## What?
This PR fixes an issue wherein the `allowEditing` value of the lightbox was not resulting in a consistent UX. It also addresses other related edge cases.

## Why?
Fixes https://github.com/WordPress/gutenberg/issues/59837
Fixes https://github.com/WordPress/gutenberg/issues/59797

When one disables editing of the lightbox, the expectation is that the UI related to the lightbox config should be seamlessly removed from the editor.

## How?
It adds logic to handle the case wherein the lightbox animation is enabled by default but editing of the lightbox is not.
It also covers various edge cases regarding how the block-level settings interact with the `theme.json` settings.

## Testing Instructions
To make sure this is working properly, We need to test various scenarios and edge cases.
In particular, we need to test the UI in the following scenarios:

1. Image block DOES NOT have a link configured, and...
- DOES NOT have a lightbox override
- DOES have a lightbox override of ENABLED set to TRUE
- DOES have a lightbox override of ENABLED set to FALSE
2. Image block DOES have a link configured, and...
- DOES NOT have a lightbox override
- DOES have a lightbox override of ENABLED set to TRUE
- DOES have a lightbox override of ENABLED set to FALSE

In addition, each one of the scenarios above needs to be tested with the following `theme.json` configurations:

**allowEditing _false_, enabled _false_**
```
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"settings": {
		"blocks": {
			"core/image": {
				"lightbox": {
					"allowEditing": false,
					"enabled": false
				}
			}
		}
	}
}
```

**allowEditing _true_, enabled _false_**
```
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"settings": {
		"blocks": {
			"core/image": {
				"lightbox": {
					"allowEditing": true,
					"enabled": false
				}
			}
		}
	}
}
```

**allowEditing _false_, enabled _true_**
```
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"settings": {
		"blocks": {
			"core/image": {
				"lightbox": {
					"allowEditing": false,
					"enabled": true
				}
			}
		}
	}
}
```

**allowEditing _true_, enabled _true_**
```
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"settings": {
		"blocks": {
			"core/image": {
				"lightbox": {
					"allowEditing": true,
					"enabled": true
				}
			}
		}
	}
}
```

To test:
1. Add the image blocks detailed above to a new post
2. Click on each image, and verify that the UI appears (or is hidden) as expected for each scenario
3. Do this with each specified variation of the `theme.json`

### Testing overview

https://github.com/WordPress/gutenberg/assets/5360536/2dbf9a42-86f4-42a0-9827-9cfa7db1df19

#### Part 1
*I mispeak early in this video — in the first scenario, the lightbox UI should be disabled.*

https://github.com/WordPress/gutenberg/assets/5360536/984d907f-7aff-4e20-8066-c2e2b1d4ced9

#### Part 2
https://github.com/WordPress/gutenberg/assets/5360536/09d70ca7-14b5-4237-9d29-a4cdbc4bb7bf

### CODE REVIEW

**Comment by artemiomorales** [comment]
What should the behavior be in the event that an image block has an override of `lightbox.enabled`, as in the following example?

```
<!-- wp:image {"lightbox":{"enabled":true|false},"id":30,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large"><img src="http://gutenberglocal.com/wp-content/uploads/2023/12/32259440831_a39a7fb46e_o-1024x768.jpg" alt="" class="wp-image-30"/></figure>
<!-- /wp:image -->
```

This can happen if a user sets a local override for the lightbox while using a `theme.json` that has `lightbox.allowEditing` set to `true`, then later changes to a `theme.json` wherein `lightbox.allowEditing` is `false`.

In this PR, the block's local lightbox config would supersede the theme.json's default config, but with the UI hidden, it would also be impossible to reset the local value without the opening the code editor or otherwise modifying the block attributes manually.

Is this the right approach?

**Comment by artemiomorales** [comment]
I *believe* this PR is working as intended in all cases, but will give another test with fresh eyes tomorrow. In any case, I think it's ready to help open up discussion on how to handle block-level overrides as mentioned above.

**Comment by artemiomorales** [comment]
Ok this doesn't work as expected yet and mistakenly shows a blank popover if a link is configured and the lightbox's `allowEditing` and `enabled` are both `true`. Am looking into this.

**Comment by michalczaplinski** [comment]
> What should the behavior be in the event that an image block has an override of lightbox.enabled

In the ideal world, we would have some kind of "log" and the latest setting would take priority (in your case, the value from the `theme.json`) but such a mechanism does not exist in Gutenberg. 😅 

IMO, the least suprising behavior is if the local setting always overrides the `theme.json` setting.

**Comment by justintadlock** [comment]
I'd argue that preexisting block settings should take precedence, regardless of what the active theme supports. This would be consistent with other attributes. For example, if I set a custom text color for a Paragraph block with a theme that has custom colors enabled, that same text color persists if I switch to a theme where custom colors are disabled.

I wouldn't break from the precedent set with other block settings, and I don't know of any other instances where this works differently.

But that's a larger problem that I wouldn't worry about specifically for this ticket (don't want to get too far into the weeds). The goal should be to display the control based on the same conditionals present in WP 6.4.

**Comment by artemiomorales** [comment]
> I'd argue that preexisting block settings should take precedence, regardless of what the active theme supports. This would be consistent with other attributes. For example, if I set a custom text color for a Paragraph block with a theme that has custom colors enabled, that same text color persists if I switch to a theme where custom colors are disabled.

Ok got it @justintadlock @michalczaplinski. I went ahead and redid the implementation to allow the preexisting block settings to take precedence while gracefully handling any changes.

There were various edge cases, and actually just decided to address all of them, updating the description with new testing instructions and a few walkthrough videos to go through the scenarios.

Let me know what you think, thanks!

**Comment by michalczaplinski** [comment]
Apologies, I didn't get to review it fully today. I ll finish up tomorrow.

File: packages/block-library/src/image/image.js [hunk 1]
```diff
@@ -274,6 +274,21 @@ export default function Image( {
 		}
 	}
 
+	function resetLightbox() {
+		// When deleting a link from an image while lightbox settings
+		// are enabled by default, we should disable the lightbox,
+		// otherwise the resulting UX looks like a mistake.
```
Comment (michalczaplinski) [inline packages/block-library/src/image/image.js:280]: I want to make sure that I understand correctly: 

The case of image block with BOTH a link and a lightbox enabled should technically never happen. Or, at least it's not possible to get into this state using the UI. It might still happen if someone e.g. edits the attributes manually. So we have to handle this edge case somehow. Is that right?

**Review by michalczaplinski — APPROVED** [review]
Awesome work, thank you for the exhaustive video explanation - it made reviewing much easier 🙂 

The changes seem good to me 👍 

If there is both a link and a lightbox `enabled: true` on the block we have to handle it in a slightly odd way (as I mention in [this comment](https://github.com/WordPress/gutenberg/pull/59890/files?diff=split&w=1#r1532286123)) but I think it's a very unlikely edge case and I can't think of a better way.

It would also be good to have some e2e test coverage for this logic but it's out of scope for this PR.

File: packages/block-library/src/image/image.js (hunk 1 above)
Comment (artemiomorales) [reply packages/block-library/src/image/image.js:280]: This one is actually a pretty common case! If at any time, a user has the following in their `theme.json`...
```
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"settings": {
		"blocks": {
			"core/image": {
				"lightbox": {
					"allowEditing": true,
					"enabled": true
				}
			}
		}
	}
}
```
...and also has a link configured for the image, then one potential way to handle that UX would be to show the popup for the link, and if that link is removed, then immediately show the popup for the lightbox. However, I found that UX to be confusing.

Here I go over more in depth what the issue is. Let me know what you think, and I'm also happy to discuss more or answer any questions 😄

https://github.com/WordPress/gutenberg/assets/5360536/32065bda-d229-43ed-8655-3af4c5efffb2

**Review by justintadlock — APPROVED** [review]
It took me a bit to work through some of the scenarios/combos, but this makes sense to me.

**Comment by artemiomorales** [comment]
> It would also be good to have some e2e test coverage for this logic but it's out of scope for this PR.

@michalczaplinski My plan is to start working on e2e tests this week to make sure all of these scenarios are covered 👍

File: packages/block-library/src/image/image.js (hunk 1 above)
Comment (michalczaplinski) [reply packages/block-library/src/image/image.js:280]: ok, I understand it now. Thank you for the explanation! 

I agree that this is a better UX than just "jumping" to the lightbox. 👍 

Could you add a link to this PR in this very comment in the code (line 280)? It might be helpful for someone in the future to refer to your video explanations.

Comment (artemiomorales) [reply packages/block-library/src/image/image.js:280]: Done 🙂

**Comment by getdave** [comment]
This PR was triaged by Editor release leads and contributors in WP Slack as part of the final WordPress 6.5 process. 

See https://wordpress.slack.com/archives/C02QB2JS7/p1711370484796489 (requires registration).

The criteria used was:

- Was this bug identified during the RC cycle for WP 6.5?
- Is this bug directly related to one of the blessed features in this release?
- Would this bug cause existing website’s to break/fail upon upgrade to WP 6.5?
- What is the approximate scope of the impact? Scale: (Minimal) 1 - 5 (Severe).
- Is the fix introducing any new features or changes?

Conclusion: this fix will be _not_ be included in WP 6.5 but will be punted to WP 6.5.1.

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the add/fixes-for-651 branch to get it included in the next release: b54a426676
