### PR TITLE
Fix: Prevent Errors in Header Processing and Encode URLs Properly

### LINKED ISSUE #67358: Error when editing custom post type with non-Latin slug in Gutenberg: "You attempted to edit an item that doesn't exist."
### Description

When attempting to edit a custom post type with a Persian slug in the Gutenberg editor, I encounter the error message:

"You attempted to edit an item that doesn't exist. Perhaps it was deleted?"

The post is still accessible via its URL, and no data appears to be lost. This issue seems to be related to the handling of slugs containing non-Latin characters in the Gutenberg editor.

### Step-by-step reproduction instructions

1. Create a custom post type (CPT) with a Persian slug.
2. Example: my_custom_post_type with a slug like ویدیو (or any Persian characters).
3. Permalink structure should be /%postname%/ .
4. Publish a post in that CPT.
5. Attempt to edit the post using the Gutenberg editor by navigating to the post editing screen.
6. The error message "You attempted to edit an item that doesn't exist" appears.
```php
$video_labels = array(
            'name'                => _x('Videos', 'Post Type General Name', 'test'),
            'singular_name'       => _x('Video', 'Post Type Singular Name', 'test'),
            'menu_name'           => __('Videos', 'test'),
            'parent_item_colon'   => __('Video :', 'test'),
            'all_items'           => __('All Videos', 'test'),
            'view_item'           => __('View Video', 'test'),
            'add_new_item'        => __('Add Video', 'test'),
            'add_new'             => __('Add Video', 'test'),
            'edit_item'           => __('Edit Video', 'test'),
            'update_item'         => __('Update Video', 'test'),
            'search_items'        => __('Search Video', 'test'),
            'not_found'           => __('Video Not Found', 'test'),
            'not_found_in_trash'  => __('No Video Found In Trash', 'test'),
        );

        // Register Video Post Type
        register_post_type(
            'video',
            array(
                'labels'        => $video_labels,
                'public'        => true,
                'supports'      => array ( 'comments', 'title', 'editor', 'thumbnail','revisions' ),
                'has_archive'   => true,
                'show_in_rest'  => true,
                'rewrite'       => array('slug' => 'ویدیو'),
                'taxonomies'    => array('category', 'post_tag', 'artist_cat'),
                'menu_icon'     => 'dashicons-video-alt3',
                'menu_position' => 5
            )
        );

```

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WP Version | 6.7.1
-- | --
Site Language | en_US
User Language | en_US
Timezone | +00:00
Home URL | http://localhost
Site URL | http://localhost
Permalink structure | /%postname%/
Is this site using HTTPS? | No
Is this a multisite? | No
Can anyone register on this site? | No
Is this site discouraging search engines? | No
Default comment status | Open
Environment type | production
User count | 1
Communication with WordPress.org | WordPress.org is reachab

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [x] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by Juzar10**
## What?
Closes: https://github.com/WordPress/gutenberg/issues/67358

This PR solves the issue with the non-ASCII characters in the slug of the CPT. when non-ASCII characters are present in the slug the Gutenberg editor displays error. 

## Why?
Attempting to edit the post of the CPT with the Persian characters results in a fatal error.

## How?
this PR properly encodes the header value before sending the custom response from the `api-fetch` module. It solves the issue regarding the Gutenberg editor not working properly.

## Testing Instructions
Steps

1. Add custom CPT with persian slug, can use the same as provided in the issue.
2. Create a new post of the CPT.
3. Attempt to edit the post of the CPT.

Before:

https://github.com/user-attachments/assets/57ac20d0-3437-482a-acb3-37da6812c22c

After:

https://github.com/user-attachments/assets/055b10bd-accd-4a77-b400-e50d4d8fe8be

### CODE REVIEW

File: packages/api-fetch/src/middlewares/preloading.js [hunk 1]
```diff
@@ -68,6 +68,21 @@ function createPreloadingMiddleware( preloadedData ) {
...
+		Object.entries( responseData.headers ).forEach( ( [ key, value ] ) => {
+			if ( key.toLowerCase() === 'link' ) {
+				responseData.headers[ key ] = value.replace(
+					/<([^>]+)>/,
+					( /** @type {any} */ _, /** @type {string} */ url ) =>
+						`<${ encodeURI( url ) }>`
+				);
+			}
+		} );
+	}
```
Comment (ellatrix) [inline packages/api-fetch/src/middlewares/preloading.js]: What does this have to do with preloading? Does it work when you disable preloading altogether?

Comment (Juzar10) [reply packages/api-fetch/src/middlewares/preloading.js]: @ellatrix 

Commenting out [this line](https://github.com/WordPress/gutenberg/blob/d9f18e5561b6233f69d82fff65c9cf8488227572/packages/api-fetch/src/index.js#L193) in apiFetch does seem to resolve the issue, though it results in the expected console error.

I suspect the issue might be related to incorrect encoding being sent in the headers. Please let me know if you'd like me to test anything further or if there are specific scenarios I should focus on.

Screenshot 2024-12-20 at 11 02 59 PM

Thanks!

Comment (ellatrix) [reply packages/api-fetch/src/middlewares/preloading.js]: Can you try making this empty instead? https://github.com/WordPress/gutenberg/blob/d9f18e5561b6233f69d82fff65c9cf8488227572/packages/api-fetch/src/middlewares/preloading.js#L11-L16

If that fixes it, then it's indeed related to preload I guess.

In that case, can you be a bit more descriptive on how the PR fixes the issue? What was the previous preloaded data and what is it after the fix? Are we adjusting the data at the right point? Why is the data fixed client side vs server side for example?

Comment (Juzar10) [reply packages/api-fetch/src/middlewares/preloading.js]: yes, putting the empty cache object does resolve the issue.

The issue stems from the inability to send non-ASCII characters in HTTP headers when using the Response constructor.

This PR addresses the problem by encoding non-ASCII characters in header links before sending them. Without this encoding, an error is thrown. ( you have to add catch block in`getEntityRecord` function to check it )

```
TypeError: Response constructor: Cannot convert value in record<ByteString, ByteString> branch of (sequence<sequence<ByteString>> or record<ByteString, ByteString>) to ByteString because the character at index 23 has value 1608 which is greater than 255.
    prepareResponse http://localhost:8888/wp-content/plugins/gutenberg/build/api-fetch/index.min.js?ver=267f89098b708f8d02b1:680
    createPreloadingMiddleware http://localhost:8888/wp-content/plugins/gutenberg/build/api-fetch/index.min.js?ver=267f89098b708f8d02b1:637
    enhancedHandler http://localhost:8888/wp-content/plugins/gutenberg/build/api-fetch/index.min.js?ver=267f89098b708f8d02b1:178
```

### Problematic Header Link:

Before encoding:

```
<http://localhost:8888/ویدیو/hello-video-world>; rel="alternate"; type=text/html
```

After encoding

```
<http://localhost:8888/%D9%88%DB%8C%D8%AF%DB%8C%D9%88/hello-video-world>; rel="alternate"; type=text/html
```

The fix involves encoding the header link just before it is sent, It won't affect other headers and ASCII characters.

Since the issue is from client side handling of the header link, particularly in the Gutenberg api-fetch module, it seems appropriate to address it here.

let me know if anything else needs to be tested regarding this or any other module I should look into.

Thanks.

**Comment by Mamaduka** [comment]
Thanks for contributing, @Juzar10!

I posted the latest update on the issue - https://github.com/WordPress/gutenberg/issues/67358#issuecomment-2621163926.

The current proposal always tries to encode Link headers, which is only needed when the middleware cannot wrap data in `Response`. Let's update the code and avoid unnecessary encoding. See the example patch below.

Can you also rebase your branch on top of the lastest trunk?

<details><summary>Patch</summary>
<p>

```diff
diff --git packages/api-fetch/src/middlewares/preloading.js packages/api-fetch/src/middlewares/preloading.js
index ac293738513..1401282d0e1 100644
--- packages/api-fetch/src/middlewares/preloading.js
+++ packages/api-fetch/src/middlewares/preloading.js
@@ -68,15 +68,37 @@ function createPreloadingMiddleware( preloadedData ) {
  * @return {Promise<any>} Promise with the response.
  */
 function prepareResponse( responseData, parse ) {
-	return Promise.resolve(
-		parse
-			? responseData.body
-			: new window.Response( JSON.stringify( responseData.body ), {
-					status: 200,
-					statusText: 'OK',
-					headers: responseData.headers,
-			  } )
-	);
+	if ( parse ) {
+		return Promise.resolve( responseData.body );
+	}
+
+	try {
+		return Promise.resolve(
+			new window.Response( JSON.stringify( responseData.body ), {
+				status: 200,
+				statusText: 'OK',
+				headers: responseData.headers,
+			} )
+		);
+	} catch {
+		Object.entries( responseData.headers ).forEach( ( [ key, value ] ) => {
+			if ( key.toLowerCase() === 'link' ) {
+				responseData.headers[ key ] = value.replace(
+					/<([^>]+)>/,
+					( /** @type {any} */ _, /** @type {string} */ url ) =>
+						`<${ encodeURI( url ) }>`
+				);
+			}
+		} );
+
+		return Promise.resolve(
+			new window.Response( JSON.stringify( responseData.body ), {
+				status: 200,
+				statusText: 'OK',
+				headers: responseData.headers,
+			} )
+		);
+	}
 }
 
 export default createPreloadingMiddleware;
``` 

</p>
</details>

**Comment by Juzar10** [comment]
@Mamaduka Thanks for the update regarding the issue.

I have applied the changes and the patch you suggested and have tested it. It is working.

Also updated the branch with latest trunk changes.

Thanks.

**Comment by Mamaduka** [comment]
Thank you, @Juzar10!

Do you mind adding a unit test for this scenario? Preloading middleware has good unit test coverage. We should also include this case.

**Comment by Juzar10** [comment]
@Mamaduka, Thanks.

I have updated the PR with the unit test regarding this scenario.

File: packages/api-fetch/src/middlewares/preloading.js [hunk 2]
```diff
@@ -68,15 +68,39 @@ function createPreloadingMiddleware( preloadedData ) {
...
+	try {
+		return Promise.resolve(
+			new window.Response( JSON.stringify( responseData.body ), {
+				status: 200,
+				statusText: 'OK',
+				headers: responseData.headers,
+			} )
+		);
+	} catch {
+		Object.entries( responseData.headers ).forEach( ( [ key, value ] ) => {
```
Comment (Mamaduka) [inline packages/api-fetch/src/middlewares/preloading.js:85]:
```suggestion
		// See: https://github.com/WordPress/gutenberg/issues/67358#issuecomment-2621163926.
		Object.entries( responseData.headers ).forEach( ( [ key, value ] ) => {
```

Let's add a note for future reference.

Comment (Juzar10) [reply packages/api-fetch/src/middlewares/preloading.js:85]: good idea, done @Mamaduka  ✅

**Review by Mamaduka — APPROVED** [review]
Thank you, @Juzar10!
