### PR TITLE
Site Editor: Fix Global Styles outdated output

### LINKED ISSUE #59593: Site Editor: Content-width and wide widths sometimes don't apply when browsing through Pages
This one is hard to describe, so it's best to describe steps to reproduce:

* Have some pages saved/published on your site. 
* Have a site design, ideally a Header template part, that leverages the _wide_ width for the main containing group. E.g. Twenty TwentyFour by default.
* Go to the site editor (/wp-admin/site-editor.php).
* Navigate to "Pages"
* Select a page, and observe how the wide content-width for the header template becomes full-wide (or just unbounded).
* Now reload the page and observe how upon reload, the same wide content-width for the header template is correct.

The above steps are shown in these two GIF files as well:

wide alignment in page editor
reloading to fix it

In other words, the wide width is not respected when browsing to a page, that incorrect width even persists inside the editor. Until you reload in either the site editor page detail page, or the fullscreen editor. So some width-related CSS is missing in one case, but not the other.

### PR DESCRIPTION
**Pull request by youknowriad**
Closes #59593 

## What?

When navigating in the site editor, in some conditions, the right global styles CSS is not output properly. This PR fixes that

## How?

The issue happens because there's a flag `isTemplate` used to compute the right global styles and when navigating in the site editor, sometimes the flag moves from "undefined" to an actual value set and when that happens, the right global styles were not being regenerated.

## Testing Instructions

1- Open the site editor with tt4
2- Notice the padding around the template header (in the actual canvas)
3- Navigate to Page 404 in the site editor
4- Go back to the home page
5- In trunk the padding disappears, in this PR the padding remains.

### CODE REVIEW

File: packages/block-editor/src/components/global-styles/use-global-styles-output.js [hunk 1]
```diff
@@ -1246,24 +1244,26 @@ export function useGlobalStylesOutputWithConfig( mergedConfig = {} ) {
...
 		} );
 
-		return [ styles, mergedConfig.settings ];
+		return [ styles, updatedConfig.settings ];
 	}, [
 		hasBlockGapSupport,
 		hasFallbackGapSupport,
 		mergedConfig,
 		disableLayoutStyles,
+		isTemplate,
```
Comment (youknowriad) [inline packages/block-editor/src/components/global-styles/use-global-styles-output.js:1265]: Adding this line is the fix here. I did some additional cleanup to the hook though.

**Review by jasmussen — APPROVED** [review]
Nice! This fixes what I obseved in the initial issue, styles persist:

after

**Comment by andrewserong** [comment]
Wonderful, thank you for fixing this up quickly! 🎉

**Comment by getdave** [comment]
This bug was identified as an Issue during the RC period and is a critical fix to ensure correct CSS output for WP 6.5.

**Comment by getdave** [comment]
I just cherry-picked this PR to the pick/wp-65-rc-2 branch to get it included in the next release: 984ede0313
