### PR TITLE
i18n: Fix incorrect '_n' usage

### LINKED ISSUE #37471: Wrong usage of `_n()` in WP 5.9 beta 3 translatable strings
### Description

_This issue is copy pasted from https://core.trac.wordpress.org/ticket/54638.
Thanks @tobifjellner for the report._

---

The new code for WordPress contains three instances where the "Template Part"/"Template Parts" string pair is used.
However, this is usage of _n() is incorrect.

If you want to handle just the singular and plural terms, then this should be handled in the code (if 1 == n then ...) and not by using _n()
Alternatively, if these strings are used together with the relevant number, then a placeholder for the count variable should be present in the string (i.e. printf)
Three references (to the current as-built package)
https://build.trac.wordpress.org/browser/trunk/wp-includes/js/dist/editor.js?marks=5220#L5220
const entityLabel = name === 'wp_template_part' ? Object(external_wp_i18n__n?)('Template Part', 'Template Parts', list.length) : entity.label; Set description based on type of entity.

https://build.trac.wordpress.org/browser/trunk/wp-includes/js/dist/block-library.js?marks=38830#L38830
https://build.trac.wordpress.org/browser/trunk/wp-includes/js/dist/editor.js?marks=5220#L5220

### Step-by-step reproduction instructions

https://github.com/WordPress/gutenberg/blob/5604b2323e57f0125ad8fb8dc5423c067978b128/packages/editor/src/components/entities-saved-states/entity-type-list.js#L52-L55

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 5.9 beta 3
- Gutenberg not installed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Resolves #37471.

PR fixes the incorrect `_n` translation method.

## Why?
The plugin shouldn't use this function for "one item" or "more than one items" cases. Details - https://developer.wordpress.org/reference/functions/_n/#comment-2397

## Testing Instructions
1. Open a "Site Editor"
2. Modify the header template part
3. Click Save, and confirm correct label is displayed
4. Mofidy the footer and repeat step 3
5. Confirm that now the plural label is displayed

### CODE REVIEW

File: packages/editor/src/components/entities-saved-states/entity-type-list.js [hunk 1]
```diff
@@ -16,20 +16,20 @@ import { store as coreStore } from '@wordpress/core-data';
...
-				'These changes will affect pages and posts that use these templates.',
-				length
-			);
+			return 1 === count
+				? __(
+						'This change will affect pages and posts that use this template.'
+				  )
+				: __(
+						'These changes will affect pages and posts that use these templates.'
+				  );
```
Comment (Mamaduka) [inline packages/editor/src/components/entities-saved-states/entity-type-list.js]: @ockham, considering that you can only modify one template at a time, I don't think we need this logic.

Comment (ockham) [reply packages/editor/src/components/entities-saved-states/entity-type-list.js]: Good point 👍

Comment (Mamaduka) [reply packages/editor/src/components/entities-saved-states/entity-type-list.js]: Done [5805a49](https://github.com/WordPress/gutenberg/pull/40292/commits/5805a495bdd9e472218d8268e6ab1c71c83f3ee1) ✅

**Comment by Mamaduka** [comment]
@ockham, should we merge this?

**Review by aristath — APPROVED** [review]
LGTM! 👍

**Comment by adamziel** [comment]
This was cherry-picked to `wp/6.0` branch
