### PR TITLE
Fixes the nested blocks contextual toolbar preference

### LINKED ISSUE #6047: Nested block toolbars do not work properly with "Fix Toolbar to Top" setting
## Issue Overview
When you enable the "Fix Toolbar to Top" setting, the toolbars of nested blocks do not display in the top bar properly, and are still shown at the blocks themselves rather than just in the top bar.

## Steps to Reproduce (for bugs)
1. Enable the "Fix Toolbar to Top" setting.
2. Insert a Columns block.
3. Insert an Image block and a Paragraph block into the Columns block.
4. Select the Paragraph block.
5. Notice that the toolbar appears both at the block and in the top bar.
6. Select the Image block.
7. Notice that the Paragraph block toolbar settings are shown in the top bar in place of the Image block toolbar settings, except for the transform button on the left.
8. Select the Paragraph block.
9. Notice that the Image block toolbar settings are shown in the top bar in place of the Paragraph block toolbar settings, except for the transform button on the left.

## Expected Behavior
Nested blocks should have their toolbars display only in the top bar when the "Fix Toolbar to Top" setting is enabled.

## Current Behavior
When you enable the "Fix Toolbar to Top" setting, the toolbars of nested blocks are shown in both the top bar and at the blocks themselves. Selecting a block and then selecting another block will show the toolbar settings of the previously-selected block in the top bar, except for the transform button on the left.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #6047

On nested blocks, when we switch the "Fixed toolbar" preference, the UI was not being updated because the `InnerBlocks` component is cached and doesn't change on prop change.

So solve this issue, this does two things:

 - Move the `hasFixedToolbar` preference to the editor settings object to avoid having to pass it down as a prop to all the needed components and rely on context instead.

 - Since this preference can change over time, the old implementation of React context is not possible, so I'm also updating the editorSettings to rely on the new React context API.

This PR surfaces several things:

1 - The `blocks` module needs to know about the `editorSettings` (`editor` module). Previously, it was implicit because we we're just grabbing a context value, with the next React API, it's explicit (better IMO) because we need to import the `Consumer` component. In this first implementation, I implemented the `EditorSettings` context in the `blocks` module to avoid circular dependencies. But This is just one other thing proving that the distinction we have right now between blocks and editor is not correct and should be rethought separately.

2 - The new Editor Settings Object can change over time (it used to be immutable). This is already handled properly everywhere using the Context API. Aside one place, the `setupEditor` action is being triggered using the settings object. I think this is used to check the post against its template (which is available in the settings). I think it's fine for now because the template config can't be changed yet, but we could imagine rechecking again if the settings change. (retrigger a `setupEditor` action).

3 - Also this raises the question on the difference between the `data` module and the new React context API. And the response is simple, there's no difference conceptually :). So why I didn't use the data module instead of the React context API here? Because I didn't want to introduce a `blocks` store yet while the distinction between `editor` and `blocks` is not clear yet (see point 1). We should probably be using the `editor` store to hold these settings instead of a newly created `blocks` store. Bur for this to happen we need to merge these two modules first. So the tradeoff here is to use the React API and we'd be able to replace it easily with the data module once the point 1 is fixed.

**Testing instructionos**

 - Add a columns block
 - Switch the "Fixed toolbar preference"
 - The toolbar should show up at the right place depending on the value of the preference.

### CODE REVIEW

File: edit-post/components/visual-editor/index.js [hunk 1]
```diff
@@ -39,19 +37,12 @@ function VisualEditor( { hasFixedToolbar, isLargeViewport } ) {
...
-						renderBlockMenu={ VisualEditorBlockMenu }
-					/>
+					<BlockList renderBlockMenu={ VisualEditorBlockMenu } />
 				</ObserveTyping>
 			</WritingFlow>
 		</BlockSelectionClearer>
 	);
 }
 
 export default compose( [
```
Comment (aduth) [inline edit-post/components/visual-editor/index.js]: We don't need `compose` anymore?

File: editor/components/block-preview/index.js [hunk 2]
```diff
@@ -30,7 +30,7 @@ class BlockPreview extends Component {
 		// we inject this function via context.
 		return {
 			createInnerBlockList: ( uid ) => {
-				return createInnerBlockList( uid, noop, noop );
+				return createInnerBlockList( uid, noop );
```
Comment (aduth) [inline editor/components/block-preview/index.js]: Aside: Maybe these ought to be default values assigned from `createInnerBlockList`.

File: editor/components/provider/index.js [hunk 3]
```diff
@@ -22,73 +22,37 @@ import {
...
-
-	componentWillReceiveProps( nextProps ) {
-		if (
-			nextProps.settings !== this.props.settings
-		) {
-			// eslint-disable-next-line no-console
-			console.error( 'The Editor Provider Props are immutable.' );
+			this.store.dispatch(
+				setupEditor( props.post, {
+					...EditorSettings.defaultSettings,
```
Comment (aduth) [inline editor/components/provider/index.js]: Something about this feels off to me. Partly because we're duplicating the initialization of these settings between here and below. I think also it's odd that we don't need to observe changes in settings here; why does this only need to occur at setup time, and never thereafter? Should this be a proper `EditorSettings.Consumer` so we can just leverage the value from `EditorSettings.Provider` directly?

File: blocks/editor-settings/index.js [hunk 4]
```diff
@@ -0,0 +1,56 @@
+/**
+ * WordPress dependencies
+ */
+import { createContext } from '@wordpress/element';
+
+/**
+ * The default editor settings
+ * You can override any default settings when calling initializeEditor
```
Comment (aduth) [inline blocks/editor-settings/index.js]: This DocBlock feels outdated, particularly in its reference to `initializeEditor` of another module, and that we document only one of the many settings available (`alignWide`).

File: blocks/editor-settings/index.js [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+ *
+ *  alignWide   boolean   Enable/Disable Wide/Full Alignments
+ *
+ * @var {Object} DEFAULT_SETTINGS
```
Comment (aduth) [inline blocks/editor-settings/index.js]: I don't know that `@var` is correct here, and I'm not sure why its value is repeated `DEFAULT_SETTINGS`.

**Review by aduth — COMMENTED** [review]
A casual observer will have a difficult time distinguishing between `EditorProvider` and `EditorSettings.Provider`.

Will we have similar issues with `renderBlockMenu` ?

File: editor/components/provider/index.js (hunk 3 above)
Comment (youknowriad) [reply editor/components/provider/index.js]: Noted in the description :) (Second point)

Comment (aduth) [reply editor/components/provider/index.js]: Ah, I did read it, apparently not closely enough.

**Comment by youknowriad** [comment]
Conceptually `renderBlockMenu` suffers from the same issues but since it's immutable we don't have any bug. I'm on the fence on whether to add it to the editorSettings specially since it's not scalar. What do you think?

**Comment by youknowriad** [comment]
Ok this should be ready, any concern?

**Comment by youknowriad** [comment]
Granted that it's not perfect. (The initialization and `renderBlockMenu`). I'm getting this in as it's an improvement, it fixes an issue. And once we revisit the `editor`/`blocks` separation I'll revisit it.

File: editor/components/block-list/insertion-point.js [hunk 6]
```diff
@@ -37,7 +37,7 @@ class BlockInsertionPoint extends Component {
 	}
 }
 export default compose(
-	withContext( 'editor' )( ( { templateLock } ) => ( { templateLock } ) ),
+	withEditorSettings( ( { templateLock } ) => ( { templateLock } ) ),
 	ifCondition( ( { templateLock } ) => ! templateLock ),
```
Comment (aduth) [inline editor/components/block-list/insertion-point.js]: Aside: Should we collapse these into a single higher-order component?

```
ifEditable = compose( withEditorSettings, ifCondition );
```
