### PR TITLE
RTL: Fix showing/hiding the right block side UI on RTL languages

### LINKED ISSUE #6366: On RTL languages buttons appear and disappear incorrectly on hover
## Issue Overview

In Hebrew (and i assume other RTL languages, when trying to move the cursor to a block action icon (such as the trash can or the arrows), the icon disappears as can be seen here:
https://www.screencast.com/t/x50am4cx0

## Steps to Reproduce (for bugs)

1. Change wordpress admin language to an RTL language such as hebrew
2. On new post, create a new block.
3. Try to delete the post by clicking on the trash can icon.
4. you'll notice the trash can disappear when the cursor is in the right place and reappear only when the cursor is on the other side of the block.

Browser: Firefox 59
System: Windows 10

## Expected Behavior

The action icons (trash can, arrows, etc.) should appear and reappear when the cursor is on the correct side of the block.

## Current Behavior

The action icons (trash can, arrows, etc.) appear and reappear when the cursor is on the other side of the block.

## Screenshots / Video

https://www.screencast.com/t/x50am4cx0

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by youknowriad**
closes #6366

In RTL languages, if we hover the right area, the left side UI was shown and vice verca. This PR fixes it.

**Testing instructions**

1. Change wordpress admin language to an RTL language such as arabic
2. On new post, create a new block.
3. Try to delete the post by clicking on the trash can icon.
4. you'll notice the trash can disappear when the cursor is in the right place and reappear only when the cursor is on the other side of the block.

(Do the same on LTR languages as well)

### CODE REVIEW

File: editor/components/block-list/with-hover-areas.js [hunk 1]
```diff
@@ -34,13 +35,14 @@ const withHoverAreas = createHigherOrderComponent( ( WrappedComponent ) => {
 		}
 
 		onMouseMove( event ) {
+			const { isRtl } = this.props;
 			const { width, left, right } = this.container.getBoundingClientRect();
 
 			let hoverArea = null;
 			if ( ( event.clientX - left ) < width / 3 ) {
-				hoverArea = 'left';
+				hoverArea = isRtl ? 'right' : 'left';
```
Comment (gziolo) [inline editor/components/block-list/with-hover-areas.js]: I think it should be called isRTL, similar to findDOMNode.

Would it make sense to introduce a helper like:
const direction = ( value) => {
    if ( ! isRTL) {
        return value;
    }
    return value === ‚right’ ? ‚left’ : ‚right’;
};

My mobile keyboard is a bit limited 😭

Comment (youknowriad) [reply editor/components/block-list/with-hover-areas.js]: I personally don't think adding this helper will help. I like dumb code :)

I'll update to `isRTL`

**Review by gziolo — APPROVED** [review]
LGTM 👍
