### PR TITLE
Inserter: fix loading indicator for reusable blocks

### LINKED ISSUE #64274: Patterns tab is empty until all the user created patterns (Reusable blocks) are fetched
### Description

When the remote patterns, core, and theme patterns are disabled, the patterns tab shows empty until all the user patterns have been fetched from the server.

This is not a problem for websites with fewer user patterns. However, it significantly increases the loading time for websites with more user patterns(reusable blocks). For instance, an application with ~4K user patterns must make 40 remote Rest API calls before displaying the categories in the patterns tab.

Disable non-user patterns with the below code.

```
/**
 * Restricts block editor patterns in the editor by removing support for all patterns from:
 *   - Dotcom and plugins like Jetpack
 *   - Dotorg pattern directory except for theme patterns
 */
function remove_non_user_created_patterns( $dispatch_result, $request, $route ) {
    if ( strpos( $route, '/wp/v2/block-patterns/patterns' ) === 0 ) {
        $patterns = WP_Block_Patterns_Registry::get_instance()->get_all_registered();


        if ( ! empty( $patterns ) ) {
            // Remove theme support for all patterns from Dotcom, and plugins. See https://developer.wordpress.org/themes/features/block-patterns/#unregistering-block-patterns
            foreach ( $patterns as $pattern ) {
                unregister_block_pattern( $pattern['name'] );
            }

            // Remove theme support for core patterns from the Dotorg pattern directory. See https://developer.wordpress.org/themes/features/block-patterns/#removing-core-patterns
            remove_theme_support( 'core-block-patterns' );
        }
    }


    return $dispatch_result;
}

 
 
// Remove and unregister patterns from core, Dotcom, and plugins. See https://github.com/Automattic/jetpack/blob/d032fbb807e9cd69891e4fcbc0904a05508a1c67/projects/packages/jetpack-mu-wpcom/src/features/block-patterns/block-patterns.php#L107
add_filter( 'rest_dispatch_request', 'remove_non_user_created_patterns', 12, 3 );
 
 
// Disable the remote patterns coming from the Dotorg pattern directory. See https://developer.wordpress.org/themes/features/block-patterns/#disabling-remote-patterns
add_filter( 'should_load_remote_block_patterns', '__return_false' );
```

I have tried some potential solutions locally, but I'm not sure that would be scalable for smaller and larger sites.

1. Currently, the user pattern categories are fetched through a separate API call. We could display the categories first and load the user patterns in the background.
2. The patterns and pattern categories are displayed after all the 4K patterns are loaded from the server. We could implement lazy loading to show the patterns immediately after each page is fetched.

### Step-by-step reproduction instructions

1. Create 4000+ reusable blocks with the CLI using 
```
wp eval 'for ($i = 1; $i <= 4000; $i++) { wp_insert_post(["post_title" => "Reusable Block " . $i, "post_content" => "<!-- wp:paragraph --><p>This is block " . $i . "</p><!-- /wp:paragraph -->", "post_status" => "publish", "post_type" => "wp_block"]); }'
```
2. Open the Browser developer tools => Network tab
3. Open the post Editor and open the Inserter.
4. The user pattern will start fetching from the server
5. The patterns tab will be empty until the patterns are loaded from the server

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/ec9f6374-2bd1-4b79-b647-20d6d6f7968a

### Environment info

- WordPress 6.6
- macOS Sonoma 14.6
- [wp-env](https://github.com/WordPress/gutenberg/blob/trunk/packages/env/README.md) and all other environments

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Fixes #64274.

Loading state was introduced in #61513, but was not properly added to the reusable blocks selector.

## Why?

If there's only reusable blocks to be fetched, it causes the loading indicator to not appear, instead it will show "no results".

## How?

Use the same technique as in #61513 for the reusable blocks selector.

## Testing Instructions

* Add some reusable blocks.
* Add the following code to disable the other patterns (from #64274)

```php
/**
 * Restricts block editor patterns in the editor by removing support for all patterns from:
 *   - Dotcom and plugins like Jetpack
 *   - Dotorg pattern directory except for theme patterns
 */
function remove_non_user_created_patterns( $dispatch_result, $request, $route ) {
    if ( strpos( $route, '/wp/v2/block-patterns/patterns' ) === 0 ) {
        $patterns = WP_Block_Patterns_Registry::get_instance()->get_all_registered();


        if ( ! empty( $patterns ) ) {
            // Remove theme support for all patterns from Dotcom, and plugins. See https://developer.wordpress.org/themes/features/block-patterns/#unregistering-block-patterns
            foreach ( $patterns as $pattern ) {
                unregister_block_pattern( $pattern['name'] );
            }

            // Remove theme support for core patterns from the Dotorg pattern directory. See https://developer.wordpress.org/themes/features/block-patterns/#removing-core-patterns
            remove_theme_support( 'core-block-patterns' );
        }
    }


    return $dispatch_result;
}

 
 
// Remove and unregister patterns from core, Dotcom, and plugins. See https://github.com/Automattic/jetpack/blob/d032fbb807e9cd69891e4fcbc0904a05508a1c67/projects/packages/jetpack-mu-wpcom/src/features/block-patterns/block-patterns.php#L107
add_filter( 'rest_dispatch_request', 'remove_non_user_created_patterns', 12, 3 );
 
 
// Disable the remote patterns coming from the Dotorg pattern directory. See https://developer.wordpress.org/themes/features/block-patterns/#disabling-remote-patterns
add_filter( 'should_load_remote_block_patterns', '__return_false' );
```

### CODE REVIEW

File: packages/editor/src/components/provider/use-block-editor-settings.js [hunk 1]
```diff
@@ -26,15 +26,20 @@ import { store as editorStore } from '../../store';
...
+	const reusableBlocks = getEntityRecords( 'postType', 'wp_block', {
+		per_page: -1,
+	} );
+	return hasFinishedResolution( 'getEntityRecords', [
+		'postType',
+		'wp_block',
+		{ per_page: -1 },
+	] )
+		? reusableBlocks
+		: undefined;
```
Comment (jsnajdr) [inline packages/editor/src/components/provider/use-block-editor-settings.js:42]: I don't understand this `hasFinishedResolution` technique. If there are valid `reusableBlocks` in state, but resolution hasn't finished, then the resolution must have been invalidated. And the state contains stale data that we don't want. So we add this condition to avoid getting the stale data. Is that right?

**Review by jsnajdr — APPROVED** [review]

File: packages/editor/src/components/provider/use-block-editor-settings.js (hunk 1 above)
Comment (ellatrix) [reply packages/editor/src/components/provider/use-block-editor-settings.js:42]: I'm not sure I'm following. Could you elaborate? Sorry

Comment (jsnajdr) [reply packages/editor/src/components/provider/use-block-editor-settings.js:42]: I'm more or less asking why we call `hasFinishedResolution` instead of just always returning `reusableBlocks` from the selector.
