### PR TITLE
Make zip-based URL parsing more general

### LINKED ISSUE #24291: In wp-env installing plugin via ZIP, not from wp.org, creates an invalid file path for plugin
I am a WordPress plugin developer who is developing an add-on for a plugin on WordPress.org. I imagine this is a fairly common behaviour.

I'm using wp-env for local development. When I add a plugin, using a download from wordpress.org, it works as expected. When I use a link from Github -- I need to test with a beta version of the plugin -- the download link URL includes the 

## How To Reproduce

I am sorry that the source repo for this is private. I hope this is enough to understand isssue, I can provide more info if needed.

###  .wp-env.json Without Bug

Using latest -- released version of Ninja Forms from WordPress.org:

```json
{
	"plugins": ["https://downloads.wordpress.org/plugin/ninja-forms.zip", "."],
	"config": {
		"WP_DEBUG": true,
		"WP_DEBUG_LOG": true,
		"WP_DEBUG_DISPLAY": false
	}
}

```

This installs the plugin at /wp-content/plugins/ninja-forms. This expected behaviour.

###  .wp-env.json With Bug

Download a beta version of Ninja Forms, using a public Github link (yes I know it's in Caldera Forms' repo, we're moving things around right now)

```json
{
	"plugins": [
		"https://github.com/CalderaWP/Caldera-Forms/files/5002105/ninja-forms.zip",
		"."
	],
}
```

This installs the plugin at `/wp-content/plugins/github.com%2FCalderaWP%2FCaldera-Forms%2Ffiles%2F5002105%2Fninja-forms/`. That is fine for php files, but it doesn't create valid URLs for JS/CSS/images 

Annotation 2020-07-30 113438

## Expected behavior

I would expect the plugin to be installed with out the ZIP download in the file path

## Versions
- @wordpress/env: "^1.3.0",
- @wordpress/scripts: "^7.1.2",
- WordPress version: Version 5.4.2
- Does the website has Gutenberg plugin installed: NO, it does not.
 - OS: Windows
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by noahtallen**
## Description
Zip URLs aren't parsed quite right in wp-env. For example, given a URL "https://github.com/CalderaWP/Caldera-Forms/files/5002105/ninja-forms.zip", the basename of the plugin will be "github.com%2FCalderaWP%2FCaldera-Forms%2Ffiles%2F5002105%2Fninja-forms". These characters are not supported as pathnames in JS and CSS, so the plugin would be broken.

The fix is to make our zip-parsing behavior more general. Now, given the same input, the zip result will be `ninja-forms`. This behavior was already used for sources from wordpress.org, but I'm just extending it to support other providers too.

While troubleshooting this issue, I also uncovered another where another type of zip wasn't supported. Basically, some zips will be created such that the zip _is_ the container of the plugin. Others, like wordpress.org, will create a zip such that the container of the plugin is a subdirectory of the zip. I added logic to make sure we handle both cases. Previously, we only handled the latter case.

cc @Shelob9 

Resolves #24291 

## How has this been tested?
1. Checkout this branch in gutenberg
2. In your gutenberg wp-env override, add a URL to a .zip plugin which is not on wordpress.org. I have uploaded this one you can use to test: `https://srv-store1.gofile.io/download/F1zUEb/editing-toolkit-build-archive.zip`
3. Run `npx wp-env start`. 
4. The plugin should be downloaded without the garbage characters in the path.

Additionally, unit tests have been created to verify the behavior.

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/env/lib/config/parse-config.js [hunk 1]
```diff
@@ -97,13 +97,11 @@ function parseSourceString( sourceString, { workDirectoryPath } ) {
...
-			/^https?:\/\/downloads\.wordpress\.org\/(?:plugin|theme)\/([^\s\.]*)([^\s]*)?\.zip$/
-		);
-		const basename = wpOrgFields
-			? encodeURIComponent( wpOrgFields[ 1 ] )
-			: encodeURIComponent( zipFields[ 1 ] );
+	if ( zipFields && zipFields[ 1 ] ) {
+		// URL: "https://www.example.com/path/to/example-plugin.1.0.2.zip"
+		// Match group: "www.example.com/path/to/example-plugin.1.0.2"
+		// Basename: "example-plugin"
+		const basename = path.basename( zipFields[ 1 ] ).split( '.' )[ 0 ];
```
Comment (noisysocks) [inline packages/env/lib/config/parse-config.js:104]: Not sure about removing everything after the first `.`. What if the source string is something like `http://my-server.com/my.cool.plugin.zip`?

Comment (noahtallen) [reply packages/env/lib/config/parse-config.js:104]: Fair.. In that case it would resolve to "my". What do you think we should do instead? We could leave periods in the filename (will this be supported everywhere?), or perhaps convert them to dashes?

Comment (noisysocks) [reply packages/env/lib/config/parse-config.js:104]: Periods are generally allowed, no?

Maybe remove the numbers from the end if it's a w.org URL and leave everything as is if not.

- `https://example.com/my.cool.plugin.4.6.0.zip` → `my.cool.plugin.4.6.0`
- `https://downloads.wordpress.org/plugin/my.cool.plugin.4.6.0.zip` → `my.cool.plugin`

**Review by glendaviesnz — APPROVED** [review]
This tested well for me with both a zip containing a subfolder with the plugin name, and a zip that just contained plugin files at top level - unit tests also ran successful and seem to cover off the main test cases.
