### PR TITLE
RichText: List: Sync DOM after editor command

### LINKED ISSUE #12027: List block doesn't save indentation
**Describe the bug**
When I update the content with list block, the block is saved fine and show up in the front end, but any indentation is ignored. When I refresh the editor, the indentation is gone!

**To Reproduce**
1. Add list bloc with some list items.
2. Indent some of the list items, they will indent fine.
3. Click "update" and go to the front end, the list block is there but with no indentation.
4. Go back to the editor and refresh the page, the list block is there but with no indentation.

**Expected behavior**
The list block should save indentation.

**Screenshots**
list-block-bug

**Desktop**
 - OS: macOS High Sierra 10.13.6
 - Browser: Chrome
 - Version: 70.0.3538.102

**Additional context**
- WordPress v4.9.8
- Gutenberg plugin v4.4.0

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #12027. Since we're using editor commands for lists that manipulate the DOM directly, the internal state is not update immediately. On input, the internal state _will_ sync, so this is only a problem when you indent/change list type, and don't make any further changes. The solution is to create a RichText value from DOM right after the command and update the state.

## How has this been tested?
See #12027.

## Types of changes
Bug fix.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

File: packages/editor/src/components/rich-text/list-edit.js [hunk 1]
```diff
@@ -35,27 +35,39 @@ function isActiveListType( editor, tagName, rootTagName ) {
...
 
-export const ListEdit = ( { editor, onTagNameChange, tagName } ) => (
+export const ListEdit = ( { editor, onTagNameChange, tagName, onSyncDOM } ) => (
 	<Fragment>
 		<RichTextShortcut
 			type="primary"
 			character="["
-			onUse={ () => editor.execCommand( 'Outdent' ) }
+			onUse={ () => {
+				editor.execCommand( 'Outdent' );
```
Comment (jorgefilipecosta) [inline packages/editor/src/components/rich-text/list-edit.js]: In all the calls to editor.execCommand we need to perform the onSyncDom right? Would it make sense to have a function in RichText called editorExecCommand that abstracts this?

**Review by jorgefilipecosta — APPROVED** [review]
It worked great in my tests 👍
I think we may benefit from and end 2 end test to this  behaviours that would catch this bug.

**Comment by iseulde** [comment]
Yes, this needs e2e tests.

File: packages/editor/src/components/rich-text/list-edit.js (hunk 1 above)
Comment (iseulde) [reply packages/editor/src/components/rich-text/list-edit.js]: The calls are and should be limited to this file, so I would prefer not to. Ideally we should remove these calls soon.
