### PR TITLE
Limit the max width of image to its container size

### LINKED ISSUE #63326: Image block can be resized beyond the bounds of the column that it's in
### Description

When you have an Image block within a Columns block, you can currently use the resize handles on the image to resize it beyond the bounds of the column, which results in a pretty broken looking layout. The resize bounds should be limited to the column.

### Step-by-step reproduction instructions

1. Insert a new post
2. Add a Columns block with two columns
3. Add an image to each column
4. Select one of the images and resize it vertically downwards
5. The image overflows the column, but shouldn't

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/612155/cc5e05dd-79b7-46aa-b2ae-37c77acc3ca3

### Environment info

Latest Gutenberg + Core trunk. Firefox. macOS.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by kevin940726**
## What?

Attempt to fix https://github.com/WordPress/gutenberg/issues/63326.

Limit the max width of image to its container size.

## Why?

See https://github.com/WordPress/gutenberg/issues/63326. Images in columns or other container can be resized to be bigger than its container, which is not expected.

## How?

Limit the `maxWidth` of the image to its container's size. Not sure about this approach and potential side effects though.

## Testing Instructions

1. Add a columns block.
2. Add an image to one of its column.
3. Try resizing the image to be bigger than the column.

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/7753001/61c803e0-ec9b-4387-af4d-4e2db77073b1

### CODE REVIEW

**Comment by talldan** [comment]
It seems close and I like the solution, but I think the main issue is that the image resized to the max bounds loses its responsive because it's set to an exact pixel value instead of 'auto'. I think it'd be better to set it back to 'auto' like an image is when first uploaded to an image block.

Some steps to highlight the issue:
1. Add a columns block with two columns
2. Add an image block to the first column and upload an image
3. Go back to the columns block and set the image to wide width, observe how it's width adjusts responsively because it's set to 'auto'.

Now compare that behavior to this:
1. Add a columns block with two columns
2. Add an image block to the first column and upload an image
3. Resize the image to a smaller and then back to the max width
4. Go back to the columns block and set the image to wide width, observe how it's now limited to the max width the column was previously.

**Comment by talldan** [comment]
Another observation is that left/right aligned images can no longer be resized to the same degree they were before (it seems to be limited to content width).

That's an interesting one, I'm not sure what the preferred behavior is.

This is also a little bit theme dependent, some themes like TT4 show aligned blocks offset from the content which would allow them to be resized further, while others don't. That makes it tricky to know dynamically what the right limit is.

**Comment by noisysocks** [comment]
Nice work. Just chiming in to say that I tested this and it fixes the issue 😀

**Comment by andrewserong** [comment]
> Nice work. Just chiming in to say that I tested this and it fixes the issue 😀

+1, nice progress here, it feels much better to use to me with the constrained maximum.

> I think it'd be better to set it back to 'auto' like an image is when first uploaded to an image block.

Great idea, that sounds like a decent way to handle it. Would that be a matter of setting to `auto` in `onResizeStop` if we're currently at the max size?

Also just pinging @Mamaduka for visibility on this one since he commented on the linked issue 🙂

**Comment by Mamaduka** [comment]
Nice. I've not thought of using `useResizeObserver` for this particular case.

**Comment by kevin940726** [comment]
> the main issue is that the image resized to the max bounds loses its responsive because it's set to an exact pixel value instead of 'auto'. I think it'd be better to set it back to 'auto' like an image is when first uploaded to an image block.

I've been thinking about this. I think it's hard to distinguish the user's intention just by observing resizing. Maybe the user wants it to be a certain exact pixel wide. I think in most cases the user wants it to fit the max width though 😅. I wonder if some kind of "snapping" makes it clearer. Perhaps @WordPress/gutenberg-design has some ideas? 🙇 

> Would that be a matter of setting to `auto` in `onResizeStop` if we're currently at the max size?

Another thing to note is that I think it also depends on the original image's size. If the image width is smaller than the max width, then resizing it to the max width (the user intention) should probably mean "width: 100%" rather than "width: auto"? 🤔

**Comment by andrewserong** [comment]
> Maybe the user wants it to be a certain exact pixel wide. I think in most cases the user wants it to fit the max width though 😅. I wonder if some kind of "snapping" makes it clearer.

Good point. In this case, if folks want to set an exact pixel size, they can still do that in the sidebar. I like the idea of some kind of snapping at the max width that sets it to `auto`, though. It reminds me a bit of the older issue to snap to wide / full widths (https://github.com/WordPress/gutenberg/issues/44357). Possibly a nice-to-have, rather than a must have?

>  If the image width is smaller than the max width, then resizing it to the max width (the user intention) should probably mean "width: 100%" rather than "width: auto"? 🤔

Also a good point! The idea of defaulting to `auto` if the container is smaller than the image, and `100%` if the container is larger than the image sounds worth exploring to me!

**Comment by talldan** [comment]
> Another thing to note is that I think it also depends on the original image's size. If the image width is smaller than the max width, then resizing it to the max width (the user intention) should probably mean "width: 100%" rather than "width: auto"?

Possibly, I haven't checked the CSS. When I say 'auto', it's what the UI shows in the width field. Sorry if that wasn't clear.

**Comment by jasmussen** [comment]
> I've been thinking about this. I think it's hard to distinguish the user's intention just by observing resizing. Maybe the user wants it to be a certain exact pixel wide. I think in most cases the user wants it to fit the max width though 😅. I wonder if some kind of "snapping" makes it clearer. 

I'd echo fixed width vs. "unbounded" is one of the primary headaches to solve as part of this. And if we can do snapping to unbounded ("Auto" as Dan refers to), that would be great. We've had separate explorations into snapping into wide and full-wide alignments too, it's very difficult to build. But it would definitely be valuable, and in this case would account for snapping to _content-width_.

**Comment by talldan** [comment]
I found this old issue that might be closed by this PR - https://github.com/WordPress/gutenberg/issues/12168.

**Comment by kevin940726** [comment]
Should we include the snapping feature in this PR, or could it be implemented separately? Is the implementation in this PR without snapping worth merging?

**Comment by talldan** [comment]
Is there a basic version that could be attempted? Something like this pseudocode
```js
onResizeStop( { actualWidth } ) {
  if ( Math.abs( containerWidth - actualWidth ) < 10 ) { 
    setWidth( '100%' );
  } else {
    setWidth( actualWidth )
  }
}
```

**Comment by kevin940726** [comment]
> Is there a basic version that could be attempted? Something like this pseudocode
> 
> ```js
> onResizeStop( { actualWidth } ) {
>   if ( Math.abs( containerWidth - actualWidth ) < 10 ) { 
>     setWidth( '100%' );
>   } else {
>     setWidth( actualWidth )
>   }
> }
> ```

Committed in [858d8a2](https://github.com/WordPress/gutenberg/pull/63341/commits/858d8a2d1c44a8b36744a6657586dc0d4e10fdf3)!

File: packages/block-library/src/image/image.js [hunk 1]
```diff
@@ -960,12 +962,20 @@ export default function Image( {
 				onResizeStart={ onResizeStart }
 				onResizeStop={ ( event, direction, elt ) => {
 					onResizeStop();
+
+					let resizedWidth = `${ elt.offsetWidth }px`;
+					// Set width to 'auto' if the resized width is close to the max-content width.
+					if ( Math.abs( elt.offsetWidth - maxContentWidth ) < 10 ) {
+						resizedWidth = 'auto';
+						elt.style.width = 'auto';
```
Comment (andrewserong) [inline packages/block-library/src/image/image.js]: The default state of an image when it's inserted is that the controls display `auto`, but there's no explicit style output. Instead of injecting `width: 'auto'` and `height: auto`, could we instead treat this as a kind of "reset" and an early return, with something like:

```js
setAttributes( {
  width: undefined,
  height: undefined,
  aspectRatio: undefined, // (OR possibly re-use the ratio === naturalRatio logic below)
} );
return;
```

If we go with what we currently have, I notice that the markup winds up including the `auto` rules:

```
<!-- wp:image {"id":4711,"width":"auto","height":"auto","sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="http://a-toule-site.local/wp-content/uploads/2024/01/IMG_3906-768x1024.jpg" alt="" class="wp-image-4711" style="width:auto;height:auto"/></figure>
```

Whereas an image that is freshly inserted doesn't have any of those rules applied:

```
<!-- wp:image {"id":4711,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large"><img src="http://a-toule-site.local/wp-content/uploads/2024/01/IMG_3906-768x1024.jpg" alt="" class="wp-image-4711"/></figure>
```

**Review by andrewserong — COMMENTED** [review]
Thanks for the update @kevin940726! In general this is testing pretty well for me, but I notice that explicitly setting to `auto` results in a bug that stretches images upon resizing the viewport. I've left a comment, but I'm wondering if instead of setting `auto` explicitly, we can treat drags within the `10px` threshold of the container as a reset instead. Would that work?

Here's a quick demo of what happens when both width and height are explicitly set to `auto`: (seems fine at first until we resize the viewport)

https://github.com/user-attachments/assets/8db05a61-af6f-4544-a4f0-3eef0dd1cb5e

File: packages/block-library/src/image/image.js (hunk 1 above)
Comment (kevin940726) [reply packages/block-library/src/image/image.js]: Good idea unsetting to `undefined`!

I don't know if it's possible to set an image to 100% of the container's width, so I added a check to fallback to explicit pixel values if the image is smaller than the container.

Comment (andrewserong) [reply packages/block-library/src/image/image.js]: Thanks Kai, this is feeling really close to me!

> I don't know if it's possible to set an image to 100% of the container's width, so I added a check to fallback to explicit pixel values if the image is smaller than the container.

That sounds good to me for now — we could always look at it in a follow-up, potentially alongside an explicit way of locking to `full width` alignment as I imagine the two concepts could be quite related. E.g. when would we want to lock to "auto" vs setting the alignment 🤔

For now, though, I think unsetting and only doing so if the image is smaller than the container is a good solution 👍

The one issue I ran into in retesting is that I think I was wrong about explicitly setting `aspectRatio` to `undefined`. It looks like we might need to either not update the `aspectRatio` property at all in this call, or reuse the logic from the `setAttributes` call below:

```
						aspectRatio:
							ratio === naturalRatio
								? undefined
								: String( ratio ),
```

Otherwise, when adjusting the size within the threshold of the container area, we lose an aspect ratio if one has been set:

https://github.com/user-attachments/assets/6574397e-c559-4bce-a5e6-373403eb89ef

What do you think? From my perspective, once that bug's resolved I think this PR will be in good shape to switch over to ready for review and get wider testing / feedback from designers, etc.

Comment (kevin940726) [reply packages/block-library/src/image/image.js]: I think that makes sense! Maybe we could just not override the `aspectRatio` in this case? I pushed an update in [c1635bd](https://github.com/WordPress/gutenberg/pull/63341/commits/c1635bd75a2821e339691f9470a3b407aa1f7039).

Comment (andrewserong) [reply packages/block-library/src/image/image.js]: Nice, that's testing well for me now! (Also while re-testing, I think avoiding explicitly setting `auto` for width and height helps avoid potential conflicts with aspect ratios, too). Let's see what some designers think 🙂

Before landing, we'll likely want to manually test the controls in a variety of browsers and themes (including Classic ones), but overall this is feeling pretty solid to me!

**Review by andrewserong — APPROVED** [review]
This is testing great for me across browsers (Chrome, Safari, FF, Edge) and in a variety of scenarios with various blocks. Overall I think this is a really big improvement. There are still some outstanding bugs or things that would be good to polish in separate PRs, but for now I think the overall improvement here makes it very worthwhile 👍

I ran into one tricky issue (not a blocker) with Classic themes, with image blocks that are added to the root of the document — I think I've identified the issue, but I'm not 100% sure what the right fix might be.

In block themes, the max width of blocks within the document is determined by layout rules that apply to any element injected in the document. So the `div` added via the `contentResizeListener` gets the correct width assigned to it:

image

In the above screenshot, the listener `div` correctly gets the `max-width` of `620px`, so when we go to drag the handle on the image block, it can't go past `620px`, which is what we expected.

However on Classic themes like Twenty Twenty One, blocks get a max width based on the classname of `wp-block`, and the `div` used by the resize listener doesn't have that classname. As a result, the max width of the listener is much larger than expected:

image

This means that in Classic themes when we go to drag beyond the container it still lets us do it:

https://github.com/user-attachments/assets/ffd0f894-4ca3-4668-a778-a77189e32ceb

Whereas in block themes, the listener is the correct size, so it works just as we'd expect:

https://github.com/user-attachments/assets/4f59d965-687c-42e6-9fd3-60d6e09d289c

I found that in Classic themes, I could hack a fix in Dev Tools by inserting a `wp-block` class name into the `div` output by the content resize listener, which appears to prove out the above (though I'm not sure if that would be the right fix 🤔):

image

Longer-term, I wonder if it would be worth exploring whether we can let the resize observer accept a custom classname to output to the resize listener? If it supported that, then we could (potentially) pass it `wp-block` in order to fix this particular case. We'd then output it somewhere around here:

https://github.com/WordPress/gutenberg/blob/ca2ee4d6fa8c7044cd1d3045c0985a77659f44fa/packages/compose/src/hooks/use-resize-observer/index.tsx#L345-L359

In any case, I think that too could be a separate PR to look into. What do you think?

For now this PR resolves the situation of resizing within a Column block as reported in #63326, and also resolves dragging within the editor canvas in block themes, so I reckon the above could be looked at separately.

Thanks for reading this longer-than-expected brain dump! 😄

LGTM! 🚀

**Comment by kevin940726** [comment]
> If it supported that, then we could (potentially) pass it wp-block in order to fix this particular case.

That's an interesting idea! I think we can do that today with `cloneBlock`, but I'm concerned about the side effects of adding the `wp-block` class name to an element that isn't a block 🤔. Either way, I think it's worth experimenting in another PR 👍.
