### PR TITLE
Word count: Adjust to count numbers as words

### LINKED ISSUE #26339: wordcount does not count numbers as a word
**Describe the bug**
As title, the wordcount function does not count plain numbers as a word.

**To reproduce**
Put something like "Should be 4 words"

**Expected behavior**
Total words (based on the example) should be 4 words (rather than 3)

**Screenshots**
no

**Editor version (please complete the following information):**
I use the npm package of @wordpress/wordcount

**Desktop (please complete the following information):**
 - OS: Ubuntu (via WSL)
 - Browser Firefox

**Additional context**
no

### PR DESCRIPTION
**Pull request by phena109**
## Description
Adjusted the character range to be removed so count logic can count numbers.
Fixes #26339

## How has this been tested?
Used the unit test suite come with the repo. I have adjusted 1 existing case and added a new one

## Types of changes
Adjusted the character range to be removed so count logic can count numbers. It doesn't break anything. All test related to the `wordcount` package passed

## Checklist:
- [x] My code is tested.

### CODE REVIEW

File: packages/wordcount/src/defaultSettings.js [hunk 1]
```diff
@@ -50,7 +50,7 @@ export const defaultSettings = {
 			'[',
 
 			// Basic Latin (extract)
-			'\u0021-\u0040\u005B-\u0060\u007B-\u007E',
+			'\u0021-\u002F\u005B-\u0060\u007B-\u007E',
```
Comment (ambienthack) [inline packages/wordcount/src/defaultSettings.js:53]: It looks like you removed extra range \u003A-\u0040 which are not numbers

Comment (ambienthack) [reply packages/wordcount/src/defaultSettings.js:53]: https://jrgraphix.net/r/Unicode/0020-007F

Comment (phena109) [reply packages/wordcount/src/defaultSettings.js:53]: Yes, this is the main reason why numbers are not count as words. Because they are removed before the real count logic get a hold of them.

The purpose of this PR is about changing the behaviour of the word count logic because it behaves differently from the most other word count functions in other software/lib etc. The ticket #26339 details it.

Comment (ambienthack) [reply packages/wordcount/src/defaultSettings.js:53]: I mean numbers are \u0030-\u0039, not \u0030-\u0040, right?

Comment (phena109) [reply packages/wordcount/src/defaultSettings.js:53]: Yes, you are right! I should update that.

**Review by ambienthack — APPROVED** [review]
Tested on texts from similar issue (#17988) and PR looks good to me. 
I don't think tests are failing because of your code. You can try to rebase to force tests to rerun.

**Comment by phena109** [comment]
> 
> 
> Tested on texts from similar issue (#17988) and PR looks good to me.
> I don't think tests are failing because of your code. You can try to rebase to force tests to rerun.

Thanks! But would you mind show me how to perform a rebase (or other ways to rerun the test)?

**Comment by ambienthack** [comment]
1. update you fork https://github.com/WordPress/gutenberg/blob/master/docs/contributors/git-workflow.md#keeping-your-fork-up-to-date
2. rebase https://github.com/WordPress/gutenberg/blob/master/docs/contributors/git-workflow.md#keeping-your-branch-up-to-date

You'll still need a review from someone with write permissions (which i don't have) for PR to get merged. Good luck!

File: packages/wordcount/src/test/index.test.js [hunk 2]
```diff
@@ -43,10 +43,17 @@ describe( 'WordCounter', () => {
...
 			message: 'Punctuation.',
 			string: 'It’s two three \u2026 4?',
-			words: 3,
+			words: 4,
 			characters_excluding_spaces: 15,
 			characters_including_spaces: 19,
 		},
+		{
+			message: 'Numbers as word',
+			string: 'Should be 4 words',
```
Comment (gziolo) [inline packages/wordcount/src/test/index.test.js:52]: I did a quick cross-check with Pages from Apple and it produces the same result:

Screen Shot 2021-05-14 at 09 29 45

File: packages/wordcount/src/test/index.test.js [hunk 3]
```diff
@@ -43,10 +43,17 @@ describe( 'WordCounter', () => {
 		{
 			message: 'Punctuation.',
 			string: 'It’s two three \u2026 4?',
-			words: 3,
+			words: 4,
```
Comment (gziolo) [inline packages/wordcount/src/test/index.test.js:46]: The same sentence in Pages:
Screen Shot 2021-05-14 at 09 31 16

File: packages/wordcount/src/defaultSettings.js [hunk 4]
```diff
@@ -50,7 +50,7 @@ export const defaultSettings = {
 			'[',
 
 			// Basic Latin (extract)
-			'\u0021-\u0040\u005B-\u0060\u007B-\u007E',
+			'\u0021-\u002F\u003A-\u0040\u005B-\u0060\u007B-\u007E',
```
Comment (gziolo) [inline packages/wordcount/src/defaultSettings.js:53]: I confirm that it allows now digits from 0 to 9 👍🏻

**Review by gziolo — APPROVED** [review]
This PR needs a rebase or, a commit with a note in the CHANGELOG about the change applied.

File: packages/wordcount/src/test/index.test.js (hunk 2 above)
Comment (gziolo) [reply packages/wordcount/src/test/index.test.js:52]: I see also a comment from @Soean in https://github.com/WordPress/gutenberg/issues/26339#issuecomment-717069789:

> Good point, I tested Microsoft Word, Google Docs and Libre office, all apps count numbers as a word. So I think we should change it in WordPress

**Comment by gziolo** [comment]
@phena109, thank you for working on this PR and your patience. It took a while to land it 😅 

I couldn't add changes to the branch so I will open a follow-up with a note about the changes applied to the `@wordpress/wordcount` package.
