### PR TITLE
Quote Block: Fix serializing the quote block

### LINKED ISSUE #564: Blockquote block empties after switching to text and back.
To reproduce, switch to text mode, **focus** the field, and switch back to visual mode. The blockquote is now empty.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #564 

Follow the steps in #564 and ensures that the block is not empty anymore.

### CODE REVIEW

**Comment by jasmussen** [comment]
Can confirm that it fixes the problem for me! 👍

**Review by jasmussen — APPROVED** [review]

File: blocks/library/quote/index.js [hunk 1]
```diff
@@ -74,12 +74,12 @@ registerBlock( 'core/quote', {
...
 	},
 
-	save( attributes ) {
+	save( { attributes } ) {
 		const { value, citation, style = 1 } = attributes;
 
 		return (
 			<blockquote className={ `blocks-quote-style-${ style }` }>
-				{ value && value.map( ( paragraph, i ) => (
+				{ value && wp.element.Children.map( value, ( paragraph, i ) => (
```
Comment (aduth) [inline blocks/library/quote/index.js]: Based on the `value` attributes definition, we should be certain that `value` is an array, not one of React's opaque children structure:

```js
query( 'blockquote > p', children() )
```

Comment (youknowriad) [inline blocks/library/quote/index.js]: It's not when we insert an empty quote block, if we type inside the editable it'll not produce an array if we have a single paragraph.

Comment (aduth) [inline blocks/library/quote/index.js]: >It's not when we insert an empty quote block, if we type inside the editable it'll not produce an array if we have a single paragraph.

That's true, but in that case we have a bit of a mismatch between the shape of state on parse, and the value that will be assigned from Editable as described in your example.

Specifically, parse will treat a single paragraph as `[ <p>foo</p> ]`, whereas in a new block, the same content would be assigned as just `<p>foo</p>`

Comment (youknowriad) [inline blocks/library/quote/index.js]: Is this really concerning? we could update the `onChange` callback to match this if you prefer.

Comment (aduth) [inline blocks/library/quote/index.js]: Maybe, maybe not. Definitely want to avoid a situation where a developer would need to account for varying shapes of the value, if it ever comes to that (`Array.isArray` checks, `React.Children.map` when we know it's just one element, etc).
