### PR TITLE
Fix escaping to consider addition of pagination arrow in Query Loop

### LINKED ISSUE #38489: Query pagination prev/next arrow/chevron span incorrectly escaped
### Description

When adding a Query Loop to a page/post and selecting the Arrow or Chevron style in the Pagination block, the inline span that is added to the Previous & Next links is being escaped incorrectly, resulting in incorrect markup.

This issue is only present when Gutenberg is active and only when added to a page/post, not when included in a template.

In 5.9 without Gutenberg active, the issue is not present and the arrow displays correctly.

### Step-by-step reproduction instructions

Add a Query Loop block to a post or page.
In the Pagination inner block, make sure to select Arrow or Chevron under Block > Settings > Arrow.
View post or page in frontend and notice the inline span in the previous and next links appear as `&lt;span class=&#039;wp-block-query-pagination-next-arrow is-arrow-arrow&#039;&gt;→&lt;/span&gt;`

### Screenshots, screen recording, code snippet

This is the resulting markup on the frontend with Gutenberg active

```
<a href="/test-page/?query-22-page=2" class="wp-block-query-pagination-next has-small-font-size">Next Page&lt;span class=&#039;wp-block-query-pagination-next-arrow is-arrow-arrow&#039;&gt;→&lt;/span&gt;</a>
```

### Environment info

WP 5.9
Gutenberg 12.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by getdave**
## Description
In https://github.com/WordPress/gutenberg/issues/38489 we learnt that late escaping the pagination label wasn't considering the addition of the pagination arrow setting which is itself HTML.

This PR fixes https://github.com/WordPress/gutenberg/issues/38489 for both prev and next blocks.

## Testing Instructions

1. Create Page.
2. Add Query Loop.
3. Choose a variation and insert the block.
4. Select Pagination block.
5. Set the "arrow" to be on.
6. Save
7. View Post on front of site.
8. Check prev/next arrows are BOTH rendered and are not output as HTML.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by getdave** [comment]
cc @Andrew-Starr does this fix the Issue you reported?

File: packages/block-library/src/query-pagination-next/index.php [hunk 1]
```diff
@@ -51,7 +51,7 @@ function render_block_core_query_pagination_next( $attributes, $content, $block
 				'<a href="%1$s" %2$s>%3$s</a>',
 				esc_url( add_query_arg( $page_key, $page + 1 ) ),
 				$wrapper_attributes,
-				esc_html( $label )
+				$label
```
Comment (getdave) [inline packages/block-library/src/query-pagination-next/index.php:54]: Ideally I'd prefer to escape at the point where we're building the markup. But because of the potential concat of the pagination arrow it's difficult. If anyone wants to refactor to still allow us to escape as close to the point of output as possible that would be preferable.

**Review by draganescu — APPROVED** [review]
LGTM! :shipit:

**Comment by Andrew-Starr** [comment]
> cc @Andrew-Starr does this fix the Issue you reported?

@getdave thanks yes it fixes the issue.

File: packages/block-library/src/query-pagination-next/index.php (hunk 1 above)
Comment (Andrew-Starr) [reply packages/block-library/src/query-pagination-next/index.php:54]: To escape as late as possible wouldn't it be preferable to use `wp_kses`?

```
wp_kses( $label,
	array(
		'span' => array(
			'class' => array(),
		),
	)
)
```
