### PR TITLE
Fix Page List to Navigation Link conversion with entity bindings

### LINKED ISSUE #72245: Conversion from Page List to Synced Menu in Nav block not creating bindings
By default a Nav block contains a `core/page-list` block. When you `Edit` that block (or just when you add another Nav Link item) the pages in the Page List are converted into Links. 

Unfortunately the conversion doesn't create the entity bindings required to enable dynamic URLs as per https://github.com/WordPress/gutenberg/pull/71630/.

Let's fix that.

### PR DESCRIPTION
**Pull request by getdave**
### What
Fixes the Page List to Navigation Link conversion to automatically create entity bindings for dynamic URLs, ensuring converted links maintain their connection to the underlying page entities. This addresses the issue where Page List blocks converted to Navigation Links were missing the required entity bindings for dynamic URL resolution.

### Why
When a Page List block is converted to Navigation Links (either by editing the Page List or adding another Nav Link item), the conversion creates Navigation Link blocks but doesn't add the required entity bindings. This means the links don't have dynamic URLs as per #71630, causing them to lose their connection to the underlying page entities.

### How
- **Extracted binding structure**: Created `buildNavigationLinkEntityBinding()` function from the existing `useEntityBinding` hook to provide a single source of truth for entity binding structure
- **Updated Page List conversion**: Modified `createNavigationLinks` function to include entity binding metadata when creating Navigation Link blocks
- **Preserved submenu bindings**: Ensured `transformSubmenus` function maintains metadata when converting links to submenus
- **Updated test coverage**: Added comprehensive tests to verify binding structure is included in all conversion scenarios
- **Maintained backward compatibility**: No breaking changes to existing functionality

### Testing Instructions
1. Remove all existing Navigation Menus
2. Add a new Navigation Menu (should use Page List block by default)
3. Click "Edit" on the Page List block to convert to Navigation Menu items
4. Verify that all converted items are entity links to the correct pages
5. Check that the links maintain dynamic URLs that update when page URLs change
6. Test with both flat and nested page structures

### Screenshots

https://github.com/user-attachments/assets/7e7ef477-a871-4465-9f8b-601f246e3cc8

Fixes #72245

### CODE REVIEW

File: packages/block-library/src/page-list/use-convert-to-navigation-links.js [hunk 1]
```diff
@@ -26,6 +31,9 @@ function createNavigationLinks( pages = [] ) {
 				url,
 				type,
 				kind: 'post-type',
+				metadata: {
+					bindings: buildNavigationLinkEntityBinding(),
+				},
```
Comment (getdave) [inline packages/block-library/src/page-list/use-convert-to-navigation-links.js:38]: This is where we create the binding for the conversion.

File: packages/block-library/src/navigation-link/shared/use-entity-binding.js [hunk 2]
```diff
@@ -4,6 +4,29 @@
...
+ * This function generates the structure used to bind navigation link URLs to their entity sources.
+ *
+ * Using a function instead of a constant allows for future enhancements where the binding
+ * might need dynamic data (e.g., entity ID, context-specific arguments).
+ *
+ * @param {string} kind - The kind of entity ('post-type' or 'taxonomy')
+ * @return {Object} Entity binding configuration object
+ */
+export function buildNavigationLinkEntityBinding( kind ) {
+	const source = kind === 'taxonomy' ? 'core/term-data' : 'core/post-data';
```
Comment (scruffian) [inline packages/block-library/src/navigation-link/shared/use-entity-binding.js:35]: Should we only support `post-type` or `taxonomy` here? Right now I could pass some CPT and instead of erroring it would just use the post data binding.

File: packages/block-library/src/page-list/test/convert-to-links-modal.js [hunk 3]
```diff
@@ -4,6 +4,16 @@
 
 import { convertToNavigationLinks } from '../use-convert-to-navigation-links';
 
+// Expected entity binding structure for navigation links
+const EXPECTED_ENTITY_BINDING = {
+	url: {
+		source: 'core/entity',
```
Comment (scruffian) [inline packages/block-library/src/page-list/test/convert-to-links-modal.js]: Shouldn't this be either `core/post-data` or `core/term-data`?

Comment (getdave) [reply packages/block-library/src/page-list/test/convert-to-links-modal.js]: Great spot. How...did that allow the tests to pass 🤔

File: packages/block-library/src/navigation-link/shared/use-entity-binding.js (hunk 2 above)
Comment (getdave) [reply packages/block-library/src/navigation-link/shared/use-entity-binding.js:35]: Shall we throw an error if the wrong type is used? I guess it's a severe problem. But we'd need to bail out of any entity creation as well.

Comment (scruffian) [reply packages/block-library/src/navigation-link/shared/use-entity-binding.js:35]: I think we should throw an error yeah. I'm not sure how gracefully we need to handle it, since it should never happen to a user - only a developer who is messing with things.

File: packages/block-library/src/page-list/test/convert-to-links-modal.js (hunk 3 above)
Comment (scruffian) [reply packages/block-library/src/page-list/test/convert-to-links-modal.js]: yeah we should investigate that - maybe the tests always pass!

Comment (getdave) [reply packages/block-library/src/page-list/test/convert-to-links-modal.js]: They don't! Excellent news. I have a fix which I will push up

**Comment by getdave** [comment]
@ockham Let's see what CI does here, but locally I was seeing the tests fail again when they attempt to validate that the URL is dynamically resolved when viewing the front of the site.

I also tried this out manually and I was seeing the same thing. Is this related to your [earlier PR](https://github.com/WordPress/gutenberg/pull/72418)?

File: packages/block-library/src/page-list/test/convert-to-links-modal.js (hunk 3 above)
Comment (getdave) [reply packages/block-library/src/page-list/test/convert-to-links-modal.js]: Fixed.

File: packages/block-library/src/navigation-link/shared/use-entity-binding.js (hunk 2 above)
Comment (getdave) [reply packages/block-library/src/navigation-link/shared/use-entity-binding.js:35]: Updated to throw error and NOT create the binding if error is encountered.

**Comment by ockham** [comment]
@getdave I'll take a look now!

**Comment by getdave** [comment]
> @getdave I'll take a look now!

CI has passed 😕

**Comment by ockham** [comment]
Yeah. Still looking locally; sry, this is taking me a bit to figure out.

**Comment by ockham** [comment]
Turns out I missed two lines when working on https://github.com/WordPress/gutenberg/pull/72418:

https://github.com/WordPress/gutenberg/blob/c03a38d3ea54d7d5d54337344b7c890f5cb8cb00/lib/compat/wordpress-6.9/block-bindings.php#L220-L221

AFAICS, if I remove those, the Nav Link destination is updated correctly on the frontend.

I'll file a quick PR for this.

**Comment by ockham** [comment]
> I'll file a quick PR for this.

https://github.com/WordPress/gutenberg/pull/72442

**Review by scruffian — APPROVED** [review]
Looking good now!

**Review by tyxla — COMMENTED** [review]
Say I misclicked "Edit" - is there a way to go back from the converted items to the original state of the menu?

**Comment by getdave** [comment]
I don't believe so but that's been a thing for a while. You'd have to re-add the Page List.

I'm curious, do you see this as a common workflow and something we need to optimise for? I'm conscious we have a large surface area of UX improvements potentially on the cards for future iterations.

**Comment by tyxla** [comment]
I think it might be someting folks are confused from, especially given there's no clear way back. If we agree on this, I'm fine to have it just documented as an issue and something we can improve later.
