### PR TITLE
Template Loader: Fix template part resolution for edited files.

### LINKED ISSUE #23106: Edit site: Changes to html files are not reflected in the site editor.
**Describe the bug**

If I make changes to a html file that is a template or template part,
those changes are shown correctly on the front, but the site editor still
shows the original unchanged content and markup.

-I made sure that no templates or template parts are saved.
-Clearing browser cache does not help.
-Testing a different browser did not help.
-It makes no different if I am viewing the entire page or select a single template part in the editor.

-Changing themes does not help:
Make a change to theme A, switch to theme B.
Make changes to theme theme B, and change back to theme A.
The site editor will show the old content and markup for theme A.

**To reproduce**
1. Install Gutenberg and enable full site editing
2. Install and activate a full site editing theme
3. Make sure there are no templates or template parts saved.
4. Open the site editor to check the original theme.
4. Open any theme html file and make any change. 
5. View the theme on the front to see that the change is applied.
6. Open the site editor and see that the change is not applied.

**Expected behavior**
I expect changes to html files to be applied in the site editor.

**Editor version (please complete the following information):**
- WordPress version: 5.4.2.
- Gutenberg Version 8.3.0

**Desktop (please complete the following information):**
 - OS: Win 10
 - Chrome Version 83.0.4103.97
 - Firefox 77.0.1

### PR DESCRIPTION
**Pull request by epiqueras**
Fixes #23106

### CODE REVIEW

File: lib/template-loader.php [hunk 1]
```diff
@@ -160,35 +160,44 @@ function create_auto_draft_for_template_part_block( $block ) {
...
+				}
+
+				if ( $template_part_file_path ) {
+					$file_contents = file_get_contents( $template_part_file_path );
+					if ( $template_part_post && $template_part_post->post_content === $file_contents ) {
+						$template_part_id = $template_part_post->ID;
+					} else {
+						$template_part_id = wp_insert_post(
+							array(
+								'post_content' => file_get_contents( $template_part_file_path ),
```
Comment (ockham) [inline lib/template-loader.php:189]:
```suggestion
								'post_content' => $file_contents,
```

**Review by ockham — APPROVED** [review]
One [small suggestion](https://github.com/WordPress/gutenberg/pull/23591/files#r447981622). Looking good otherwise! Tested to fix #23106 :heavy_check_mark:

**Comment by kjellr** [comment]
Thank you for the fix! 🙌
