### PR TITLE
Paste: Omit <style> tags

### LINKED ISSUE #9719: Paste from Word or LibreOffice produces block of CSS first
**Description**
When pasting some simple text (one heading, one paragraph) from Word or LibreOffice, Gutenberg first creates a paragraph block of some CSS text and then the content blocks. 

**To Reproduce**
1. Create a document in Word or LibreOffice, one heading and one paragraph (any text will do). Select all and copy.
2. Create a new Gutenberg post.
3. Paste content.

**Expected behavior**
One heading block and one paragraph block.

**Screenshots**
gutenberg-error

**Desktop (please complete the following information):**
- Windows 10 Pro
- Tested on Chrome 69 and FireFox Quantum 62 (64 bits)

**Additional context**
- Gutenberg 3.7.0
- Tested on local setup and also on testgutenberg.com.

### PR DESCRIPTION
**Pull request by mcsf**
## Description

Fixes #9719 

## How has this been tested?

- Verify all block-conversion integration tests pass, including newly added `ms-word-styled`.
- Try reproducing parent issue.
- Stress-test pasting or classic-to-blocks conversion with whatever input.

## Questions

- [ ] Properly investigate the regression (this was seemingly working in 2.0), rather than "just fix" as I did.
- [x] Figure out if it's worth keeping a dedicated `HTML.replace` call to strip `meta` tags instead of relying on proper node processing.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

File: packages/blocks/src/api/raw-handling/head-remover/index.js [hunk 1]
```diff
@@ -0,0 +1,10 @@
+export default function( node ) {
+	if (
+		node.nodeName !== 'META' &&
+		node.nodeName !== 'STYLE'
```
Comment (iseulde) [inline packages/blocks/src/api/raw-handling/head-remover/index.js]: Interesting that we stopped stripping these. Maybe this happened with the paste rewrite, but that was ages ago... If we want to continue with this fix, maybe it's not a bad idea to think about all HTML tags that should be stripped entirely (as opposed to unwrapped), like `script` etc.

Comment (mcsf) [reply packages/blocks/src/api/raw-handling/head-remover/index.js]: Yeah, `script` would be another one. I can’t see a use for just unwrapping them.

File: packages/blocks/src/api/raw-handling/index.js [hunk 2]
```diff
@@ -79,7 +80,7 @@ function getRawTransformations() {
  */
 export default function rawHandler( { HTML = '', plainText = '', mode = 'AUTO', tagName, canUserUseUnfilteredHTML = false } ) {
 	// First of all, strip any meta tags.
-	HTML = HTML.replace( /<meta[^>]+>/, '' );
+	// HTML = HTML.replace( /<meta[^>]+>/, '' );
```
[the remark this answers is not in the document]
Comment (mcsf) [reply packages/blocks/src/api/raw-handling/index.js]: I did imagine it would affect the following pieces, but wanted to try this anyway. The tests still pass, so I think we need both comments and also some new tests that fail if this line is commented. Would you have some?

File: packages/blocks/src/api/raw-handling/head-remover/index.js (hunk 1 above)
Comment (iseulde) [reply packages/blocks/src/api/raw-handling/head-remover/index.js]: I'd say `script`, `style`, `noscript` and `template`. `meta` is fine I think, it cannot have any child nodes. I wouldn't expect it in pasted HTML, but maybe it's prudent to strip `head` as well.

File: packages/blocks/src/api/raw-handling/index.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (iseulde) [reply packages/blocks/src/api/raw-handling/index.js]: Sure, I'll have a look.

[the remark this answers is not in the document]
Comment (iseulde) [reply packages/blocks/src/api/raw-handling/index.js]: Pushed.

File: packages/blocks/src/api/raw-handling/head-remover/index.js [hunk 3]
```diff
@@ -0,0 +1,12 @@
+export default function( node ) {
```
Comment (iseulde) [inline packages/blocks/src/api/raw-handling/head-remover/index.js]: Just noting that, unlike the other filters, this has its own folder. Any reason why?

**Review by ellatrix — APPROVED** [review]

**Comment by ellatrix** [comment]
@mcsf Looks like this wasn't added to the inline filter. #46402 fixes this.
