### PR TITLE
Disallow setting grid block rows/columns to zero

### LINKED ISSUE #65201: Grid block: Meaningless `0` is rendered on screen when columns is set to `0`
## Steps to reproduce

1. Insert a Grid block.
1. In the block inspector, set the Grid Item Position to "Manual" and set the "Columns" to "0".

## Video

https://github.com/user-attachments/assets/93513426-9a2a-4ee9-88fe-5ec6b710facf

### PR DESCRIPTION
**Pull request by talldan**
## What?
Fixes #65201, by ensuring `0` isn't incorrectly output and then further not allowing a zero value for grid or row counts.

## Why?
IMO, a value of zero doesn't really make sense for grid block columns or rows, I'm not sure what purpose it would have, so I've added some code to disallow it. This also ensures the UI doesn't surprisingly switch between Manual and Auto without the user explicitly setting it.

## How?
- Adds min values to the fields, as well as some additional logic in the `onChange` to prevent `0` from being typed in.
- Updates the boolean rendering logic to ensure it can't output zero

## Testing Instructions
1. Ensure the Grid Experiment is switched off
2. Add a grid block
3. Switch to Manual
4. Try setting the column count to zero

#### Before
Screenshot 2024-09-10 at 5 33 31 PM

#### After
Screenshot 2024-09-10 at 5 33 08 PM

### CODE REVIEW

File: packages/block-editor/src/layouts/grid.js [hunk 1]
```diff
@@ -74,7 +74,8 @@ export default {
 		// In the experiment we want to also show column control in Auto mode, and
 		// the minimum width control in Manual mode.
 		const showColumnsControl =
-			window.__experimentalEnableGridInteractivity || layout?.columnCount;
+			window.__experimentalEnableGridInteractivity ||
+			!! layout?.columnCount;
```
Comment (talldan) [inline packages/block-editor/src/layouts/grid.js:78]: This is what was incorrectly causing `0` to be rendered

**Review by andrewserong — APPROVED** [review]
Nice simple fix, this is testing well for me and makes sense that you can't set `0` columns in the UI. Folks can still switch back to Auto mode manually via the toggle, so it doesn't feel like an issue to me if people can no longer set `0` manually via the input field to toggle back to Auto — I doubt anyone would really reach to do that anyway.

LGTM! 🚀

**Comment by mirka** [comment]
Thanks for the quick fix!
