### PR TITLE
Notes: Disable or hide "Add note" button depending on block’s state

### LINKED ISSUE #72520: Note: Does not work in classic and missing.
### Description

There are cases where notes do not work in classic and missing.
Renaming, locking, blockVisibility, etc. are also not preserved.

Related:#72458

### Step-by-step reproduction instructions

1. Open a post or page. 
2. Insert a Classic block. 
3. If you add a note and reload the screen, the note will be deleted.
4. To try notes in a missing block,
Paste the following code into the block editor.
```HTML
<!-- wp:unregistered/example {"attr1":"One","attr2":"Two"} -->
<p>Testing missing block with some</p>
<div class="wp-some-class">
	HTML <span style="color: red;">content</span>
</div>
<!-- /wp:unregistered/example -->
```
5. Add a note to the missing block.
6. Reloading the screen will remove the added note.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/1bb6759b-023c-4103-a931-3f44403df854

### Environment info

- WordPress 6.8
- Gutenberg  21.9.0-rc.2

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by t-hamano**
Closes #72520

## What?

This pull request hides or disables the "Add note" button in blocks where the Note feature is not available:

- Unsuppored (Missing) Block: Don't show the button
- Broken Block: Don't show the button
- Classic Block: Disable the button and show an info text

## How?

- Move the logic that determines whether a note can be added into the BlockActions component.
- Add special handling for the Classic block.

## Testing Instructions

Use the following HTML to insert to test the Unsupported block, broken block, and Classic block:

```html
<!-- wp:heading -->
<h2 class="wp-block-heading">Classic Block</h2>
<!-- /wp:heading -->

<p>This is a classic block content.</p>

<!-- wp:heading -->
<h2 class="wp-block-heading">Unsupported (Missing) Block</h2>
<!-- /wp:heading -->

<!-- wp:test /-->

<!-- wp:heading -->
<h2 class="wp-block-heading">Broken Block</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<pThis is a broken paragraph block.</p>
<!-- /wp:paragraph -->
```

- Select one of the blocks and open the block settings dropdown.
  - Unsuppored (Missing) Block: The Add note button isn't displayed
  - Broken Block: The Add note button isn't displayed
  - Classic Block: The Add note button is displayed and as an info text

### Classic Block dropdown menu

image

### CODE REVIEW

File: packages/editor/src/components/collab-sidebar/comment-menu-item.js [hunk 1]
```diff
@@ -14,23 +17,48 @@ import { unlock } from '../../lock-unlock';
...
+
+	return (
+		<MenuItem
+			icon={ commentIcon }
+			onClick={ onClick }
+			aria-haspopup="dialog"
+			disabled={ isFreeformBlock }
+			info={
+				isFreeformBlock
+					? __( 'Not supported for this block.' )
```
Comment (t-hamano) [inline packages/editor/src/components/collab-sidebar/comment-menu-item.js]: I don't have strong opinions about this text. I simply chose the shortest text from this comment: https://github.com/WordPress/gutenberg/issues/72520#issuecomment-3471604195

Comment (jeffpaul) [reply packages/editor/src/components/collab-sidebar/comment-menu-item.js]: I definitely prefer the `Convert to blocks to add notes.` as it provides context for what someone can do to allow notes to work with this specific content.

Comment (t-hamano) [reply packages/editor/src/components/collab-sidebar/comment-menu-item.js]: Updated in e16842805234fe7a8318d48321d3303049320df9

File: packages/block-editor/src/components/block-actions/index.js [hunk 2]
```diff
@@ -63,13 +64,23 @@ export default function BlockActions( {
 						canInsertBlockType( block.name, rootClientId )
 					);
 				} ),
+				canAddNote:
+					blocks.length === 1 &&
+					blocks[ 0 ].isValid &&
+					blocks[ 0 ].name !== getUnregisteredTypeHandlerName(),
```
Comment (Mamaduka) [inline packages/block-editor/src/components/block-actions/index.js]: I don't think this should be a part of the `block-editor` package. Colocating this into `AddCommentMenuItem` makes more sense to me.

Why? The notes feature is currently WP-specific; this is one of the main reasons for having it in the `editor` package. The plan for packages like `block-editor` is to try to keep them platform-agnostic.

Comment (t-hamano) [reply packages/block-editor/src/components/block-actions/index.js]: You're right! Fixed in d00859de1f21aa6c457072e7ff8c77f7708ed802

**Review by jasmussen — APPROVED** [review]
Thank you for contributing.

**Review by Mamaduka — APPROVED** [review]
Thank you, @t-hamano! The code looks good to me.
