### PR TITLE
Fixed handling of html captions on gallery and image.

### LINKED ISSUE #5338: Image/Gallery blocks don't parse HTML in captions
## Issue Overview
If the caption of an image already contains HTML(say for photo credits like `Photo by <a href="https://example.com">Author</a>`), when that image is inserted in either a Gallery or an Image block, the caption is just shown as plain text. The current WordPress editor doesn't have that restriction and renders your caption correctly.

## Steps to Reproduce (for bugs)
This is on Gutenberg 2.2.0
You can see a video of me demonstrating that bug here: https://www.youtube.com/watch?v=3OpMmCN-lmU&t=6624 (jump to `1:50:24` in case link doesn't work properly). Section of me explaining the issue and solution is about 5 minutes long.
If you don't want to watch the video, then the steps are fairly simple:
1. Upload an image to your Media Library
2. In it's caption, enter `Hello <a href="https://example.com">World</a>!`
3. Insert image via either Image block or Gallery block.
4. See the caption as `Hello <a href="https://example.com">World</a>!` instead of "Hello [World](https://example.com)!"

## Expected Behavior
Be able to edit the rendered HTML of the caption inside of the `RichText` component

## Current Behavior
The caption is rendered as plain text with all HTML visible(eg `<a href="...">link</a>`)

## Possible Solution
This is also demonstrated in the video, but this is how I fixed the problem locally:

 In `/blocks/library/image/block.js`:

1. Add to the top:
```
import { parse as hpqParse } from 'hpq';
```
2. Change `onSelectImage` to:
```
onSelectImage( media ) {
	const attributes = { url: media.url, alt: media.alt, id: media.id };
	if ( media.caption ) {
		const matcher = children( 'div' );
		attributes.caption = hpqParse( '<div>' + media.caption + '</div>', matcher );
	}
	this.props.setAttributes( attributes );
}
```

Not sure if that is an optimal implementation, but this is based off of the way `children` attributes are parsed.

## Related Issues and/or PRs
I couldn't find any related issues. I did mention this on Slack about a week ago.

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
When adding an image with existing HTML captions they were not being parsed. Now we use the existing HTML parsing mechanisms (hpqParse plus children matcher) to correctly parse the captions.

Fixes: https://github.com/WordPress/gutenberg/issues/5338

## How Has This Been Tested?
Follow instructions provided in https://github.com/WordPress/gutenberg/issues/5338 and verify the problem is now fixed and we correctly use the HTML that was in the caption instead of showing the

### CODE REVIEW

File: blocks/library/gallery/block.js [hunk 1]
```diff
@@ -86,7 +88,7 @@ class GalleryBlock extends Component {
 		this.props.setAttributes( {
 			images: images.map( ( attributes ) => ( {
 				...attributes,
-				caption: attributes.caption ? [ attributes.caption ] : [],
+				caption: hpqParse( attributes.caption, children() ),
```
Comment (iseulde) [inline blocks/library/gallery/block.js]: I feel like this should be part of the attributes declaration, rather than something afterwards. Would love to have @aduth's opinion/suggestion.

Comment (iseulde) [reply blocks/library/gallery/block.js]: hm also how does this belong in `onSelectImages`? When is it not being parsed exactly?

Comment (iseulde) [reply blocks/library/gallery/block.js]: I think whatever calls `onSelectImages` on the image(s) should do the parsing?

Comment (jorgefilipecosta) [reply blocks/library/gallery/block.js]: Hi @iseulde when we select an image from the mediaLibrary the media library pass us a string with a caption. The mediaLibrary should not handle the creation of the react children as the user of the library may, in fact, want things in string format. In order for us to correctly pass that html and use it in our captions RichText fields we need to pass it to the "react children format". That's exactly what this line is doing.

Comment (gziolo) [reply blocks/library/gallery/block.js]: I think that you can do it inside the `MediaUpload` component as @iseulde suggested. You would have only one place where this transformation happens and all blocks would benefit from it.

https://github.com/WordPress/gutenberg/blob/a2f41b7206a87ce56995b2a869fa2701a095866c/blocks/media-upload/index.js#L113-L117

Comment (jorgefilipecosta) [reply blocks/library/gallery/block.js]: Yes @iseulde and @gziolo I think it may make sense to do it in MediaUpload because it is part of the blocks, I had the idea it was part of the components and so it would not be good to include things from the block parsing. I will update the code.

Comment (jorgefilipecosta) [reply blocks/library/gallery/block.js]: Code was updated.

**Review by gziolo — APPROVED** [review]
Great job, it works like a charm! 💯
