### PR TITLE
Data: Await resolver implementing isFulfilled

### LINKED ISSUE #70805: `@wordpress/data` `isFulfilled` Deadlock Issue
## Description

A critical deadlock occurs when resolvers implement the `isFulfilled` callback, causing promises returned by `mapResolveSelector` or thrown by `mapSuspendSelector` to hang indefinitely.

The root cause lies within `fulfillSelector`. When a resolver's `isFulfilled` method returns `true`, the function exits early without dispatching a `finishResolution` action to the metadata store. Despite this early exit, the `selectorResolver` retains its `hasResolver` property set to `true`.

This creates a fatal mismatch: both `mapResolveSelector` and `mapSuspendSelector` detect `selector.hasResolver` as `true` and attempt to check the metadata store for resolution status. However, since no metadata entry was created due to the early return, the promises enter an infinite wait state, never finding the resolution they expect.

## The Problem

When `resolver.isFulfilled` returns `true` in `fulfillSelector` [index.js:705-711](https://github.com/WordPress/gutenberg/blob/7d045178de5879471793a627efeadfc1225073cb/packages/data/src/redux-store/index.js#L705-L711):

```javascript
if (
    resolversCache.isRunning( selectorName, args ) ||
    ( typeof resolver.isFulfilled === 'function' &&
        resolver.isFulfilled( state, ...args ) )
) {
    return; // Early return - no metadata entry created!
}
```

But both `mapResolveSelector` [index.js:559-607](https://github.com/WordPress/gutenberg/blob/7d045178de5879471793a627efeadfc1225073cb/packages/data/src/redux-store/index.js#L559-L607) and `mapSuspendSelector` [index.js:617-663](https://github.com/WordPress/gutenberg/blob/7d045178de5879471793a627efeadfc1225073cb/packages/data/src/redux-store/index.js#L617-L663) expect a metadata entry to exist:

**In `mapResolveSelector`**:
```javascript
const hasFinished = () => {
    return boundMetadataSelectors.hasFinishedResolution(
        selectorName,
        args
    );
};
// This check will always fail - no metadata entry exists
if ( hasFinished() ) {
    return finalize( result );
}

// Creates a subscription that waits forever
const unsubscribe = subscribe( () => {
    if ( hasFinished() ) {
        finalize( getResult() );
        unsubscribe();
    }
});
```

**In `mapSuspendSelector`**:
```javascript
if ( isFinished ) {
    if ( hasResolutionFailed ) {
        throw metadata.error;
    }
	
    return result;
}
// Throws a promise that will never resolve
throw new Promise( ( resolve ) => {
    unsubscribe = subscribe( () => {
        if ( boundMetadataSelectors.hasFinishedResolution( selectorName, args ) ) {
            resolve();
            unsubscribe();
        }
    });
});
```

**Result**: The promise waits forever for a `finishResolution` action that will never come, because the resolver was never started due to the `isFulfilled` early return.

### Step-by-step reproduction instructions

1. Implement a selector/resolver pair, with the resolver implementing `isFulfilled`.
2. Attempt to await the value using `resolveSelect` .

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- `@wordpress/data` version `10.26.0`.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by johnhooks**
## What?

Add dispatch of `finishResolution` when a resolver's `isFulfilled` callback is true in the `@wordpress/data` package.

Fixes #70805.

## Why?

A deadlock issue was discovered in the `@wordpress/data` package when using `resolveSelect` on a selector/resolver pair implementing `isFulfilled`.

This [failed test run](https://github.com/WordPress/gutenberg/actions/runs/16402291352/job/46343436719?pr=70806#step:6:220) from before adding the fix demonstrates the issue.  

## How?

The concept is to dispatch `finishResolution` to the metadata store when `resolver.isFulfilled` is `true`. This adds the correct state to the store, allowing resolution of the promises in `mapResolveSelector` and `mapSuspendSelector`.

### CODE REVIEW

**Comment by Mamaduka** [comment]
@johnhooks, do you mind rebasing the branch on top of the latest trunk?

@jsnajdr, IIRC you worked recently on improving this area of the code.

Side note: `isFulfilled` already has a test at the registry level, maybe we should colocate the new test there:

https://github.com/WordPress/gutenberg/blob/e043709f730e4b81367d548f0f00eb4aa85a116c/packages/data/src/test/registry.js#L294

**Comment by johnhooks** [comment]
@Mamaduka I've updated the branch, colocated the tests, and added a few more after reviewing the other tests in `packages/data/src/test/registry.js`.

File: packages/data/src/redux-store/index.js [hunk 1]
```diff
@@ -700,19 +700,29 @@ function mapSelectorWithResolver(
...
-			boundMetadataSelectors.hasStartedResolution( selectorName, args )
+			typeof resolver.isFulfilled === 'function' &&
+			resolver.isFulfilled( state, ...args )
 		) {
+			setTimeout( async () => {
+				resolversCache.clear( selectorName, args );
+				store.dispatch(
+					metadataActions.finishResolution( selectorName, args )
+				);
+			}, 0 );
```
Comment (jsnajdr) [inline packages/data/src/redux-store/index.js]: This could be neatly integrated into the main `setTimeout` callback several lines below. Just don't run the `fulfill` function when `isFulfilled` returns `true`:
```js
const isFulfilled =
  typeof resolver.isFulfilled === 'function' &&
  resolver.isFulfilled( state, ...args );
if ( ! isFulfilled ) {
  const action = resolver.fulfill( ...args );
  if ( action ) {
    await store.dispatch( action );
  }
}
```

It's the same thing, without code duplication, with just one difference: both `startResolution` and `finishResolution` are called, right after each other without any waiting. But that's fine, it's even welcome, because outside observers will see the same sequence of updates, no matter how the selector/resolver is internally implemented.

Another way to fix this is in the `mapResolveSelector` and `mapSuspendSelector` functions. These functions could perform the `isFulfilled` check and return a result right away. In that case, the `startResolution`/`finishResolution` actions would never be called when `isFulfilled` is `true`. But it's probably a worse solution than the first one, again for consistency reasons: sometimes, for the same selector, `start`/`finishResolution` would be called, sometimes not.

Comment (johnhooks) [reply packages/data/src/redux-store/index.js]: I agree with calling `startResolution`/`finishResolution` and being consistent. I'll wrap the call to `isFulfilled` into the main `setTimeout`. Thank you for the review.

File: packages/data/src/test/registry.js [hunk 2]
```diff
@@ -358,6 +358,150 @@ describe( 'createRegistry', () => {
...
+					getData: ( state ) => state.data,
+				},
+				resolvers: {
+					getData: { fulfill, isFulfilled },
+				},
+			} );
+
+			const promise = registry.resolveSelect( 'demo' ).getData();
+			jest.runAllTimers();
+			await expect( promise ).rejects.toThrow( 'isFulfilled error' );
```
Comment (johnhooks) [inline packages/data/src/test/registry.js]: @jsnajdr this is odd. The error is caught and the state of the resolver transitions to failed, but Jest fails the test without this line. I'm still researching the issue.

Comment (johnhooks) [reply packages/data/src/test/registry.js]: I've walked through with the debugger, wow there is a lot going on for a single resolution. Though after running `jest.runAllTimers`, `promise` has a rejected status and `Error: isFulfilled error`, even though it was caught in the try/catch and included in the `FAIL_RESOLUTION` action.

Comment (johnhooks) [reply packages/data/src/test/registry.js]: OH I got it, [`mapResolveSelector`](https://github.com/WordPress/gutenberg/blob/d3734f5e4839d0cf5ada56fedb253fae26c55116/packages/data/src/redux-store/index.js#L586) rejects it. So the test is correct, if this is the desired behavior.

Should the resolver resolution fail if `isFulfilled` throws an error?

File: packages/data/src/redux-store/index.js [hunk 3]
```diff
@@ -700,22 +700,15 @@ function mapSelectorWithResolver(
...
-			return;
-		}
-
-		if (
 			boundMetadataSelectors.hasStartedResolution( selectorName, args )
 		) {
 			return;
 		}
 
+		const state = store.getState();
```
Comment (jsnajdr) [inline packages/data/src/redux-store/index.js]: This could be inlined into the `isFulfilled` call, we don't use the `state` anywhere else do we?
```js
resolver.isFulfilled( store.getState(), ...args )
```

File: packages/data/src/test/registry.js [hunk 4]
```diff
@@ -358,6 +358,150 @@ describe( 'createRegistry', () => {
...
+				selectors: {
+					getPage: ( state, id ) => state.pages?.[ id ],
+				},
+				resolvers: {
+					getPage: fulfilledResolver,
+				},
+			} );
+
+			const promise1 = registry.resolveSelect( 'demo' ).getPage( 1 );
+			jest.runAllTimers();
```
Comment (jsnajdr) [inline packages/data/src/test/registry.js]: For the `resolveSelect` tests, we would be better off if we used `jest.useRealTimers()`. Then you don't need to run timers manually.

It will happen automatically if you move these tests to `redux-store/test/index.js`, where all other `resolveSelect` tests are. This `registry.js` suite has `jest.useFakeTimers()` at the start.

File: packages/data/src/test/registry.js (hunk 2 above)
Comment (jsnajdr) [reply packages/data/src/test/registry.js]: Yes, `resolveSelect` detects the error and returns it.

If `isFulfilled` throws, that is certainly suprising and unexpected and the error should be surfaced. So yes, the resolution should fail.

**Review by jsnajdr — APPROVED** [review]
Very nice, thanks for working on this and addressing all feedback :+1:

**Comment by johnhooks** [comment]
@jsnajdr absolutely, I appreciate you taking the time to help me through it.

Also shout out to @TimothyBJacobs for suggesting I create the PR.
