### PR TITLE
Fix Audio block to respect all possible src attributes coming from a shortcode

### LINKED ISSUE #23664: Convert to blocks loses info about audio media
**Describe the bug**
Original page uses shortcode audio format:
`<p>[audio mp3="https://www.evaeaston.com/wp-content/uploads/th-vl-end-4-10.mp3"][/audio]</p>`

Convert to blocks produces an empty audio media block asking for information that was within the original code.

**Screenshots**
classic
html
block

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, Native block editor

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Browser: Brave
 - Version:Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by getdave**
Fixes https://github.com/WordPress/gutenberg/issues/23664.

Essentially the `[audio]` shortcode does not currently respect all possible file type options that can be specified as the `src` on the shortcode. These include ‘mp3’, ‘m4a’, ‘ogg’, ‘wav’, ‘wma’, but currently only the block transform for the shortcode only looks for the `src` attribute:

https://github.com/WordPress/gutenberg/blob/612acd3faffc455af2dca216b589f27ce68de695/packages/block-library/src/audio/transforms.js#L32-L37

## Description

This is fixed by amending the transform which builds the block's `src` attribute to look for any of the approved formats falling back to the original `src` as the default. 

I will add some unit and e2e tests to cover this.

#### On Master branch

* Add new Post.
* Insert Classic Block.
* Paste in shortcode [audio mp3="https://www.evaeaston.com/wp-content/uploads/th-vl-end-4-10.mp3"][/audio]
* Validate Media will play in Editor.
* Select Classic Block and click "Convert to Blocks" on block toolbar.
* Classic Block is converted into an Audio Block with none of the original information from the shortcode. It's a blank Audio block!

#### On this branch

You can try this out at http://e9tpphz9.gutenberg.run/wp-admin/post-new.php

* Checkout this PR.
* Add new Post.
* Insert Classic Block.
* Paste in shortcode [audio mp3="https://www.evaeaston.com/wp-content/uploads/th-vl-end-4-10.mp3"][/audio]
* Validate Media will play in Editor.
* Select Classic Block and click "Convert to Blocks" on block toolbar.
* Classic Block is converted into an Audio Block with the correct mp3 src prepopulated.

Also try this same process for audio shortcodes with all of the possible attributes:

* `src`
* `mp3`
* `m4a`.
* `ogg`
* `wav`
* `wma`

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by getdave** [comment]
cc @bobeaston as the original creator of the Issue.

File: packages/block-library/src/audio/transforms.js [hunk 1]
```diff
@@ -32,8 +32,10 @@ const transforms = {
 			attributes: {
 				src: {
 					type: 'string',
-					shortcode: ( { named: { src } } ) => {
-						return src;
+					shortcode: ( {
+						named: { mp3, m4a, ogg, wav, wma, src },
+					} ) => {
+						return mp3 || m4a || ogg || wav || wma || src;
```
Comment (marekhrabe) [inline packages/block-library/src/audio/transforms.js:38]: We should read attributes with the same preference as the shortcode itself:

https://github.com/WordPress/WordPress/blob/af523447f46c351cb27432813273049777fbb890/wp-includes/media.php#L2859-L2878

If `src` exists, it will get used, and only if not, individual extension attributes are checked. Let's move `src` to the begining of the `||` chain and we should match it.

Comment (getdave) [reply packages/block-library/src/audio/transforms.js:38]: Great spot!

Comment (getdave) [reply packages/block-library/src/audio/transforms.js]: Fixed.

**Comment by getdave** [comment]
This branch now available on Gutenberg Run live

http://e9tpphz9.gutenberg.run/wp-admin/post-new.php

File: packages/block-library/src/audio/transforms.js (hunk 1 above)
Comment (bobeaston) [reply packages/block-library/src/audio/transforms.js]: THANKS all!

**Review by marekhrabe — APPROVED** [review]

**Comment by bobeaston** [comment]
Thanks again Dave for keeping track of it and pushing it through the process.  Much appreciated!
