### PR TITLE
Query block: Fix dirtying post on load

### LINKED ISSUE #26838: Query block: Loading the block causes unsaved changes
### Problem
When opening an existing post/page that has a Query block seems to cause unsaved changes? After loading the content on the post/page, if I do nothing and just click to exit the page, I get an alert stating there are unsaved changes.

**Example of problem**

loading

### Solution
Don't show this alert if there are no changes.

cc @ntsekouras

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/26838

There was a bug that when loading a post with a `Query` block would trigger an initial update to its attributes without needing it. This PR fixes it.

### CODE REVIEW

File: packages/block-library/src/query/edit/query-inspector-controls.js [hunk 1]
```diff
@@ -129,8 +129,12 @@ export default function QueryInspectorControls( {
 
 	const [ querySearch, setQuerySearch ] = useState( query.search );
 	const onChangeDebounced = useCallback(
-		debounce( () => setQuery( { search: querySearch } ), 250 ),
-		[ querySearch ]
+		debounce( () => {
```
Comment (gziolo) [inline packages/block-library/src/query/edit/query-inspector-controls.js:132]: `debounce` makes me always think that there is an underlying problem that can't be easily solved and it makes the issue invisible. Do you know why is it called in `useEffect` in the first place?

Comment (gziolo) [reply packages/block-library/src/query/edit/query-inspector-controls.js:132]: Does it exist here to prevent too many requests to the server when typing?

Comment (ntsekouras) [reply packages/block-library/src/query/edit/query-inspector-controls.js:132]: >Does it exist here to prevent too many requests to the server when typing?

Yes.

**Review by gziolo — APPROVED** [review]
Let's get this in, it makes sense to include this check.

I'm wondering if in the future the local state could be removed completely in this component in favor of `setQuery` call. It would require updating the part that triggers network requests to use debouncing instead, but it would benefit the case when changing other properties quickly as well.
