### PR TITLE
Link format: add aria label, remove 'x' in IE

### LINKED ISSUE #2667: Improve accessibility of open in new window toggle
[Edited by @afercia to report the right issues, sorry for the confusion]

Splitting this out from #2204 see also #2628 

1
the "cog" button doesn't have any text or aria-label, it's completely empty so it will be reported by assistive technologies just as "button". Worth noting the other buttons that are very close in the code, they all have an aria-label...

Since it misses an aria-label, the button misses also a tooltip. I'd say it should have an aria-label with text "Link settings" or something along those lines.

screen shot 2017-09-05 at 16 06 11

2
z-index issue!
see screenshot above: when entering or pasting a link *and* there are also search results, when pressing the cog button the expanded panel stays below the search results.
To reproduce, insert a link to `https://wordpress.org` in a couple other posts. Then edit a third post and insert a link pasting in the field `https://wordpress.org`.
I'd say either increase the x-index or, maybe better, close the search suggestions when the setting panel is expanded, and display them again when the setting panel gets closed.

3
the input field misses a focus style.
This is because the input fields inherit the focus style from `forms.css` where input of `type="url"` aren't targeted. Two options here:
- set the input field to `type="text"` and miss minor advantages given by `type="url"`
- add proper selectors to the styles in core `forms.css`, targeting `type="url"`

4
IE 11 and Edge display a proprietary "X" control in the input fields of `type="url"`:

ie11

edge

This would be a minor issue, but unfortunately the spinner that appears when the search runs doesn't look so nice in combination with the "X":

screenshot 62

If I remember correctly, a similar issue happened in the Customizer for the menu/widget search field and we just switched back the input field type "search" to "text" (which would also solve the focus style issue).

### PR DESCRIPTION
**Pull request by notnownikki**
Fixes: #2667

## Description
Adds a label for the settings button, removes the 'x' on the input in IE with some CSS.

## How Has This Been Tested?

In browser, check the label pops up on the link settings button.

Needs some checking in IE. It's been confirmed that the CSS is correct, but I don't have access to IE to test myself.

## Types of changes
Bug fix

### CODE REVIEW

File: blocks/editable/format-toolbar/index.js [hunk 1]
```diff
@@ -179,7 +179,7 @@ class FormatToolbar extends Component {
 						<UrlInput value={ newLinkValue } onChange={ this.onChangeLinkValue } />
 						<IconButton icon="editor-break" label={ __( 'Apply' ) } type="submit" />
 						<IconButton icon="editor-unlink" label={ __( 'Remove link' ) } onClick={ this.dropLink } />
-						<IconButton icon="admin-generic" onClick={ this.toggleLinkSettingsVisibility } aria-expanded={ settingsVisible } />
+						<IconButton icon="admin-generic" label={ __( 'Link Settings' ) } onClick={ this.toggleLinkSettingsVisibility } aria-expanded={ settingsVisible } />
```
Comment (aduth) [inline blocks/editable/format-toolbar/index.js]: This is a long line, I'd suggest we split props onto multiple lines to improve readability.

File: blocks/editable/format-toolbar/style.scss [hunk 2]
```diff
@@ -41,3 +41,11 @@
 		margin: 0;
 	}
 }
+
+.blocks-url-input {
```
Comment (aduth) [inline blocks/editable/format-toolbar/style.scss]: If these styles are specific to the `BlocksURLInput` component, they should probably be defined in:

https://github.com/WordPress/gutenberg/blob/master/blocks/url-input/style.scss

File: blocks/editable/format-toolbar/style.scss [hunk 3]
```diff
@@ -41,3 +41,11 @@
...
+	input[type=url] {
+		&::-ms-clear {
```
Comment (aduth) [inline blocks/editable/format-toolbar/style.scss]: I don't think we need so much nesting here, particularly when using the `&` and there being no other style selectors. As written, this could be simply:

```css
.blocks-url-input input[type=url]::-ms-clear {
	display: none;
}
```

Or when moved to `blocks/url-input/style.scss`:

```scss
.blocks-url-input {
	// ...

	input[type=url]::-ms-clear {
		display: none;
	}

	// ...
}
```

**Review by aduth — CHANGES_REQUESTED** [review]

File: blocks/editable/format-toolbar/style.scss (hunk 2 above)
Comment (aduth) [reply blocks/editable/format-toolbar/style.scss]: >If these styles are generic to all `BlocksURLInput` components

Although it seems like we might not want this to be generic to all these components? If it should only be applied within the format toolbar, the styles must be defined to nest as such (since there is no implied scoping for styles defined in this file to make them specific to the format toolbar).

Comment (notnownikki) [reply blocks/editable/format-toolbar/style.scss]: I moved this into the toolbar block above.

File: blocks/editable/format-toolbar/index.js (hunk 1 above)
Comment (notnownikki) [reply blocks/editable/format-toolbar/index.js]: Done!

**Review by aduth — APPROVED** [review]
Still thinking the styling should probably be applied to URLInput, since the original issue described the overlap between the search spinner and the X, and the spinner is applied in URLInput.

Otherwise looks good 👍

**Comment by notnownikki** [comment]
Oh, I mistunderstood, yeah it would make more sense to have it there. WIll move!

**Review by aduth — APPROVED** [review]
