### PR TITLE
Query Loop: Add useBlockPreview, fix Query Loop wide alignment in the editor

### LINKED ISSUE #33248: Query loop block: Wide alignment not working correctly on the editor
## Description

While using wide alignment on a Query block the width is only applied to the currently selected post while in the editor. The frontend shows the correct alignment for all posts

## Step-by-step reproduction instructions

1. Activate emptytheme (you may need to set layout sizes on the theme.json, [here](https://gist.github.com/MaggieCabrera/624da1fdbfad3ae271c78a728f337868)'s the theme.json file I used)
2. Insert a query block inside a page and set it to show more than one post
3. Apply wide alignment to the query block

## Expected behaviour

I expected all posts inside the query block to show as wide aligned within the editor

## Actual behaviour

Only the first (selected) post shows as wide, the rest show no alignment. The frontend shows them all as wide.

## Screenshots or screen recording (optional)

Editor | Frontent
--- | ---
Screenshot 2021-07-07 at 10 00 58 | Screenshot 2021-07-07 at 10 03 26

### PR DESCRIPTION
**Pull request by andrewserong**
## Description

This is an alternative to #35932 and is intended to resolve #33248.

It pulls in the `useBlockPreview` and `useDisabled` hooks from #35863 and uses them to render a block preview for the Post Template block, for those instances within the query loop that are not currently selected (and are therefore not interactive). By using these hooks, we can avoid adding the DOM nesting involved in using the `BlockPreview` component directly.

The `useDisabled` hook is mostly comprised of logic borrowed from the [Disabled](https://github.com/wordpress/gutenberg/blob/a7e2895829c16ecd77a5ba22d84f1dee1cfb0977/packages/components/src/disabled/index.js#L1) component. The context behaviour has not been included in the hook version, because we don't (yet) have a need for it. In a future follow-up, we could refactor the `Disabled` component to use the `useDisabled` hook introduced here, internally.

## How has this been tested?

In a page, insert a Query Loop block and set the alignment to Wide and make sure that the number of items within the loop is at least 2-3. Within the query loop block, select between the instances within the loop. Unlike in the reported issue (#33248), selecting between blocks should preserve the Wide layout.

__Note: this is specifically about dealing with adding a Query Loop block to a page — behaviour in the site editor should be unaffected__

## Screenshots 

| Before | After |
| --- | --- |
| Kapture 2021-11-12 at 16 38 49 | Kapture 2021-11-12 at 16 34 40 |

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by andrewserong** [comment]
I think this is ready for review now, so I've switched it out of draft.

File: packages/block-editor/src/components/index.js [hunk 1]
```diff
@@ -104,7 +104,7 @@ export { default as BlockList } from './block-list';
 export { useBlockProps } from './block-list/use-block-props';
 export { LayoutStyle as __experimentalLayoutStyle } from './block-list/layout';
 export { default as BlockMover } from './block-mover';
-export { default as BlockPreview } from './block-preview';
+export { default as BlockPreview, useBlockPreview } from './block-preview';
```
Comment (Mamaduka) [inline packages/block-editor/src/components/index.js]: Hi, @andrewserong. Should we export this new hook as experimental for now? Similar to `useDisabled`?

Comment (andrewserong) [reply packages/block-editor/src/components/index.js]: Yes, of course, that's a good idea. Thanks George, I've updated it in https://github.com/WordPress/gutenberg/pull/36431/commits/7c8af494d3d0310b82a345be678645a2b5e1e3ff to export as `__experimentalUseBlockPreview` which also removes it from the readme, too.

Comment (Mamaduka) [reply packages/block-editor/src/components/index.js]: Thanks, @andrewserong. I will try to do more detailed testing later today.

**Comment by andrewserong** [comment]
I've just given this a rebase to fix conflicts.

**Comment by getsource** [comment]
Hi! Thanks so much for putting this together.

I did a bit of testing, and it does look to solve the issue!

I noticed a bit of changed behavior, though. Whether this is better or worse than the existing align jumping, I don't know -- but I figured it was worth documenting.

It's hard to describe, but there are a two things I noticed when selecting / unselecting different posts. I wasn't able to pinpoint the exact situations that cause it, but if I clicked in and out from them couple times, I could usually cause it to happen:
- There's bit of visual flicking / refreshing sometimes, where you can see the other items flash by (or load perhaps?). This comes with it feeling a little slower to respond
- Sometimes the view scrolls up to the top of the page or down, in situations where it would stay in the same place without the PR.

Before:

https://user-images.githubusercontent.com/1034160/143421685-c89816ea-aa87-40b9-b90b-ca7eaa792c43.mov

After:

https://user-images.githubusercontent.com/1034160/143421730-ff16edaf-aa90-4c83-872a-59eec66781a6.mov

Tested with Firefox 94.0.1 on OSX and Twenty-Twenty Two.

**Comment by andrewserong** [comment]
Thanks so much for giving this a test @getsource and including the demo videos, that's super helpful! I don't think I tested this while using a background colour, so didn't notice the flickering issue (nor the scroll issue either 🤔). I'll investigate further (if I don't get time today, I'll follow up next week). Cheers!

**Comment by andrewserong** [comment]
It took me a little longer than expected to fix up the flickering issue. In https://github.com/WordPress/gutenberg/pull/36431/commits/8a34723d6436770dc39ac061018893d1f92e6a9b I've optimised the `PostTemplateBlockPreview` component's rendering by doing the following:

* Memoize the component
* Pass consistent values and references to the component (e.g. no anonymous function for `onClick`) to ensure the component doesn't re-render too frequently
* Always render a block preview for each block context in the list — but use `display: none` to hide the active preview. This ensures that when switching between block contexts, we switch visibility via CSS rather than requiring the preview itself to be re-rendered from scratch, which appears to have been the main culprit in the flickering issue that was most visible in Firefox (I had a harder time reproducing it in Chrome).

I believe this is now working pretty well, but could do with some more testing, as I _just_ got this finished before wrapping up my week. CC: @getsource.

| Before | After |
| --- | --- |
| Kapture 2021-12-03 at 17 26 11 | Kapture 2021-12-03 at 17 24 39 |

**Comment by ramonjd** [comment]
This is working as described for me I cannot detect any layout change with selecting inner blocks within the Query Loop block in the post editor.

Kapture 2021-12-08 at 09 14 50

It's not within the purview of this PR, but I'm not entirely sure that it addresses the Comments Query Loop block issue in https://github.com/WordPress/gutenberg/issues/37154

Kapture 2021-12-08 at 09 34 36

File: packages/block-editor/src/components/block-preview/index.js [hunk 2]
```diff
@@ -63,3 +69,58 @@ export function BlockPreview( {
...
+	props = {},
+	__experimentalLayout,
+} ) {
+	const originalSettings = useSelect(
+		( select ) => select( blockEditorStore ).getSettings(),
+		[]
+	);
+	const disabledRef = useDisabled();
+	const ref = useMergeRefs( [ props.ref, disabledRef ] );
+	const settings = useMemo( () => {
```
Comment (ramonjd) [inline packages/block-editor/src/components/block-preview/index.js]: Feel free to ignore if you think it's more readable as is. 

```suggestion
	() => ( { ...originalSettings, __experimentalBlockPatterns: [] } ),
```

Comment (andrewserong) [reply packages/block-editor/src/components/block-preview/index.js]: That does look more readable to me — I think from memory I'd just copied this bit from the other BlockPreview component, so the shorter syntax looks nice. I'll follow up.

**Comment by ramonjd** [comment]
I can't comment on the implementation in great detail, but, having played with trunk, this is a clear improvement and I'm happy to approve once folks with more high-level context are happy with it.

**Comment by andrewserong** [comment]
Thanks for testing @ramonjd!

> It's not within the purview of this PR, but I'm not entirely sure that it addresses the Comments Query Loop block issue in #37154

Yes, the Comments Query Loop block is quite similar so if this PR ends up being accepted, I think we'd then look at a follow-up for that block to deal with that issue 🤞.

File: packages/block-editor/src/components/block-preview/index.js (hunk 2 above)
Comment (andrewserong) [reply packages/block-editor/src/components/block-preview/index.js]: Pushed in https://github.com/WordPress/gutenberg/pull/36431/commits/a00533ecad7f0721af1103d62a6deb48320d1e87 👍

**Comment by getsource** [comment]
Oh! I'm so sorry, I missed the mention for re-testing on this one. It looks like it's been tested now, but I'll take another look on Monday if it hasn't already been merged before then.

**Comment by andrewserong** [comment]
> Oh! I'm so sorry, I missed the mention for re-testing on this one.

Thanks @getsource! No worries, I've had plenty of other things to keep me busy 😄 It'd be great to get another review/test to confirm the approach as both block previews and the Query Loop block can have quite a few edge cases. Also, since this uses a new hook-based approach for rendering the preview and the disabled behaviour, it'd be good make sure I haven't missed anything from the existing component-based approach, that might be needed here.

**Review by getsource — COMMENTED** [review]
Okay! I went through and re-tested this, and the flickering seems to be resolved, along with the layout change being fixed.

This is great! In general, everything feels much smoother than pre-PR/trunk.

I don't think I'm the best person for a final code review, so submitting as Comment for that reason. Thanks so much!

**Review by gziolo — COMMENTED** [review]
I would be in favor of giving it a try based on the feedback shared during testing. That's the most important aspect of this enhancement. We are planning to recreate a similar set of changes for the Comments Query Loop block as documented in https://github.com/WordPress/gutenberg/issues/37154. That should be a good way to validate whether the approach takes scales well.

This PR introduced a new experimental API in `@wordpress/components` – `useDisabled` hook. Is that a necessary step at the start or can it be inlined in the `@wordpress/block-editor` package for now? Do we have more use cases where the same hook could be used? @youknowriad and @ellatrix what do you think about it? If you think it's going to be useful in other places, we should include the documentation so the community knows how to use it.

**Comment by andrewserong** [comment]
Thanks for testing, folks!

> This PR introduced a new experimental API in `@wordpress/components` – `useDisabled` hook. Is that a necessary step at the start or can it be inlined in the `@wordpress/block-editor` package for now? Do we have more use cases where the same hook could be used?

Good question @gziolo! I originally added this hook [in a previous PR](https://github.com/WordPress/gutenberg/pull/35863) that didn't land, and over there @youknowriad [had the suggestion](https://github.com/WordPress/gutenberg/pull/35863#discussion_r738995769) of placing it in `@wordpress/compose`, which I've done here. The longer-term goal is to refactor the `Disabled` component in `@wordpress/components` to use this hook internally so that there's less duplication of logic (this hook borrows its logic from that component). I think the hook is generic enough that it could potentially be used in other circumstances, too, where a component might need to be rendered in a disabled state (disarming a form, perhaps?), so 🤞 the hook will sit nicely there alongside hooks like `useConstrainedTabbing`. Happy to move it if folks feel strongly about where it should go, though!

I like the suggestion of adding documentation, ~so I've had a go at adding in an entry for it in the `compose/README.md` file in https://github.com/WordPress/gutenberg/pull/36431/commits/57461d448d61c62b7ba8697605774cdd0de9527f — I know we often avoid adding documentation for experimental features, but I also see that the components package sometimes includes experimental features with a notice that it's experimental, so I've used that pattern here as well.~ Update: I've moved the documentation to the hook in https://github.com/WordPress/gutenberg/pull/36431/commits/ee8881f029940d66ebdead8a0ded7ef57f12fcfb — I just noticed that in CI it complains if we add it manually to the readme, I think the git commit hook must have failed for me locally 😄

Let me know if you'd like further changes!

**Comment by gziolo** [comment]
> The longer-term goal is to refactor the Disabled component in @wordpress/components to use this hook internally so that there's less duplication of logic (this hook borrows its logic from that component).

That and the suggestion from @youknowriad was the missing bit of information. I think it's a solid plan and with the JSDoc comment included for the new hook, it should be enough to expose the documentation once the API is promoted to stable. I hope you can do it in a follow-up that refactors the `Disabled` component.

**Review by gziolo — APPROVED** [review]
Let's get this in. I'm not the best person to approve, but you only live once and I trust all other reviewers 😄 

Thank you everyone for an excellent team work to help @andrewserong to take it to the finish line 🎉

**Comment by andrewserong** [comment]
> I think it's a solid plan and with the JSDoc comment included for the new hook, it should be enough to expose the documentation once the API is promoted to stable. I hope you can do it in a follow-up that refactors the Disabled component.

Yes, of course! There's a few other tasks to wrap up first, but my goal is to follow-up with a refactor for the Disabled component in the new year. (In the shorter-term, I'd like to continue refining the click behaviour when switching between blocks and block previews in the instances of the loop). Thanks again for the review and merge!

**Comment by ellatrix** [comment]
@andrewserong I don't get at all why we must render all inner blocks twice to fix and alignment issue. Could you try to explain this to me? I don't know anything about this block.

**Comment by andrewserong** [comment]
> I don't get at all why we must render all inner blocks twice to fix and alignment issue.

Thanks for the ping @ellatrix! The only one that gets rendered twice is the current instance of the loop — the double rendering is to avoid flickering when switching between instances. Without it, when clicking between instances, there's a flash of white as the preview renders. If the current instance is rendered for "real" as well as there being a hidden preview version of it, then the preview can be shown / hidden instantaneously. Not the best approach, but resulted in a smoother UI. That could totally be revisited if there are better approaches now, though.

For a bit more content: and my memory is a little fuzzy on this particular PR since it's a couple of years old now, but my understanding is that the way that the block works is that it should only render the "real" inner blocks once, for the instance selected. And all other instances of the loop should render a preview instead. If we accidentally render each child as "real" inner blocks (as in #60535) then we wind up with a bunch of duplicate controls in the UI (in both the block toolbar and inspector controls):

image

I believe using previews for the non-selected instances of the loop was a workaround for that problem. The previews pre-date this particular PR — this one was an attempt to work around some of the downsides of the preview approach prior to this PR (alignment display, reduce flickering etc).
