### PR TITLE
fix: inline text-color regex in edge-case when color slug ends with '-color'

### LINKED ISSUE #24620: Inline text-color regex can be faulty for edge cases.
**Describe the bug**
If a theme defines custom colors that have a slug ending in `-color` for the color palette via the `editor-color-palette`, the inline text-color [regex matching](https://github.com/wordpress/gutenberg/blob/1347a8cd2392bf106307bb9bddef2dee5c842935/packages/format-library/src/text-color/inline.js#L37) fails. The color is not set to active.

**To reproduce**
1. Define a custom color inside a theme adding theme support for the editor-color-palette. The below code can be copied and pasted inside one to check this:
```
	add_theme_support( 'editor-color-palette',  [
				[
					'name'  => 'TEST COLOR',
					'slug'  => 'test-color',
					'color' => '#bada55',
				]
			]
		);
```
2. Go inside the editor (add a new post) 
3. Type a paragraph 
4. Select one word inside it
5. Click on the `More rich text controls` dropdown toggle inside the toolbar
6. Click on `Text Color`
7. The color should be there. If you click it, it does not activate inside the Popover.

**Expected behavior**
The color should activate properly.

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Gutenberg Plugin
- 8.7.1 - Latest from the master branch on this repository

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 84.0.4147.125

**Additional context**
I'm not sure if this would disrupt anything else than the inline color, but I've traced the issue down to this line: 
https://github.com/wordpress/gutenberg/blob/1347a8cd2392bf106307bb9bddef2dee5c842935/packages/format-library/src/text-color/inline.js#L37

If you have a color like the one in the example above, it will stop matching after the first `-color` and the returned slug for `text-color` will be `test`, instead of `test-color`.

A possible solution can be to make sure that the regex stops only at the end of the string:
`/.*has-(.*?)-color$/` instead of `/.*has-(.*?)-color.*/`

I am not sure if this would affect anything else. 

I will submit a pull request with this change in case this is a good solution.

Thank you!

### PR DESCRIPTION
**Pull request by abaicus**
## Description
Changes regex used to match active color slug in the inline text-color library. Attempts to fix #24620.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/format-library/src/text-color/inline.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ export function getActiveColor( formatName, formatValue, colors ) {
 	}
 	const currentClass = activeColorFormat.attributes.class;
 	if ( currentClass ) {
-		const colorSlug = currentClass.replace( /.*has-(.*?)-color.*/, '$1' );
+		const colorSlug = currentClass.replace( /.*has-(.*?)-color$/, '$1' );
```
Comment (jorgefilipecosta) [inline packages/format-library/src/text-color/inline.js:37]: Hi @abaicus, thank you for reporting and proposing a fix to this bug 👍
There are no guarantees that the class attribute will only contain the color class. It may contain another class after "has-test-color-color another-class". What if instead we use a greedy regex and exclude the spaces. I guess something like `/.*has-([^\s]*)-color.*/` would work very well for this case.

Comment (abaicus) [reply packages/format-library/src/text-color/inline.js:37]: Hi @jorgefilipecosta, thanks for taking the time to review this :+1: 

Yes, it seems that a greedy regex with excluded spaces would be the better way to go indeed. 

I will submit a commit to change it. :+1:

Thank you! :see_no_evil:

**Review by jorgefilipecosta — APPROVED** [review]
LGTM 👍  Thank you for iterating and fixing this issue!
