### PR TITLE
Fix: Featured image block contains invalid HTML

### LINKED ISSUE #17739: Featured image button contains a div which is invalid HTML
**Describe the bug**

When a featured image is set, the image is displayed within the button and it's wrapped within the "responsive wrapper". The rendered HTML is the following (simplified code):

```
<button type="button" class=" ... " aria-label="Edit or update the image">
	<div class="components-responsive-wrapper">
		<div style="padding-bottom: 100%;"></div>
		<img src=" ... " alt="" class=" ... " />
	</div>
</button>
```

Button elements can't contain div elements, that's invalid HTML.

Although this doesn't impact the functionality, WordPress aims to use valid HTML as stated in its [HTML coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/html/) and there are good reasons for that.

I'd tend to think components that can be reused anywhere like the "responsive wrapper" shouldn't be made of `<div>`s. In this cases, when a generic wrapper is necessary, a better option would be using `<span>` which can be used anywhere and styled as a block element if needed.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/17739

This PR changes the responsive wrapper component to use a span instead of a div. The reason is that the component is used inside a button and having a div inside a button is not valid HTML.

## How has this been tested?
I added a featured image and I checked it showed correctly on the panel.
I clecked the image and verified the media library opened.
I was able to select a new image with success.

### CODE REVIEW

File: packages/components/src/responsive-wrapper/index.js [hunk 1]
```diff
@@ -16,12 +16,12 @@ function ResponsiveWrapper( { naturalWidth, naturalHeight, children } ) {
 		paddingBottom: ( naturalHeight / naturalWidth * 100 ) + '%',
 	};
 	return (
-		<div className="components-responsive-wrapper">
-			<div style={ imageStyle } />
+		<span className="components-responsive-wrapper">
```
Comment (youknowriad) [inline packages/components/src/responsive-wrapper/index.js]: We're changing a generic component to address the needs of a specific one. Not suggesting it's a good approach but maybe we should first think if it does make sense for all usage?  Any thoughts on that?

Also, I think with React hooks, these generic behavior can be written in a different way, hooks taking refs as argument maybe. So I'm wondering if there's an alternative solution here that would make this even more generic.

Comment (jorgefilipecosta) [reply packages/components/src/responsive-wrapper/index.js]: From the design perspective, this component is not changing at all I guess the only practical change is that it can be used in more places while still producing valid HTML.

> maybe we should first think if it does make sense for all usage

We only have the featured image usage in core, so we can not easily judge other use cases. A span is something that we can use almost anywhere the restriction that what children we can nest inside when creating this PR I thought this was supposed to be used in images as even the code referred to imageStyles. But on a second thought I guess someone may pass a div or a paragraph as a child of this component and in that case, we would produce invalid HTML.

So the possibilities we have to make this more generic are a flag that allows choosing div or span or even a tagName that allows specifying the element.
Or something that looks into the children and if is something that can be nested in a span (e.g: image, another span or pure text) we use a span otherwise we use a div.

> Also, I think with React hooks, these generic behavior can be written in a different way, hooks taking refs as argument maybe.

I'm not understanding how hooks would help. The idea is this component also exposing a hook the parent uses?
Because the component itself can not use a hook with a reference because to have a reference it needs to render something to the dom and to render something it already needs to know if it should render a div or a span.

Comment (youknowriad) [reply packages/components/src/responsive-wrapper/index.js]: Right this is like a use-case where hooks might not make a lot of sense, thanks for explaining.

Can we maybe just add a boolean `isInline` prop to switch? Thoughts?

File: packages/components/src/responsive-wrapper/index.js [hunk 2]
```diff
@@ -8,19 +8,34 @@ import classnames from 'classnames';
...
 		return null;
 	}
 	const imageStyle = {
 		paddingBottom: ( naturalHeight / naturalWidth * 100 ) + '%',
 	};
+	const wrapperClass = 'components-responsive-wrapper';
+	const childrenProcessed = cloneElement( children, {
+		className: classnames( 'components-responsive-wrapper__content', children.props.className ),
+	} );
+	if ( isInline ) {
```
Comment (youknowriad) [inline packages/components/src/responsive-wrapper/index.js]: if it's the exact same code, can't we just use `const TagName = isInline ? "span" : "tag"` to avoid duplicating it?

**Review by youknowriad — APPROVED** [review]
Thanks

File: packages/components/src/responsive-wrapper/index.js (hunk 2 above)
Comment (jorgefilipecosta) [reply packages/components/src/responsive-wrapper/index.js]: Yes it seems to reduce duplicate code, I update following your suggestion 👍

**Comment by bobbingwide** [comment]
This has broken the display of the Featured Image. Issue being raised.
