### PR TITLE
Fix labeling of the navigation links in the list view.

### LINKED ISSUE #59369: Site editor: List view: incorrect labeling of navigation links
### Description

In the Site Editor > Design > Navigation > Any navigation menu, the navigation links visually show the link _label_, that is the textual label users enter when they create a linb.

However, the aria-lable of each link is actually the navigation link _type_, ie. 'Page Link', 'Custom Link', 'Submenu'.

As such:
- The visual labeling and the actual accessible name mismatch.
- Screen reader users don't have any clue _what_ the navigation link actually is. Only the link _type_ is announced.
- Speech recognition software users can't activate the links because of the label / name mismatch.

It is worth reminding that aria-label _overrides any textual content_. As such, these labels aren't really useful for users, for example:
- aria-label="Page Link"
- aria-label="Custom Link"
- aria-label="Submenu"

Screenshot:

Screenshot 2024-02-26 at 10 05 55

In this context, 'Page Link', 'Custom Link', 'Submenu' etc. aren't meaningful names for these items.

Instead, in the Post editor list view, the block _type_ makes more sense. However, the items in teh list view can be many things:
- blocks with default names
- blocks with custom names (renamed by users)
- synced patterns with user provided names
- navigation links with user provided labels (the link text)

All these cases need the item aria-label to match the text that is visually displayed as that is the text that gives users the correct information about _what_ they are going to edit.

It appears the List View items labeling mechanism hasn't been tested enough in the context of the Site editor navigation links, as the current labeling is clearly insufficient to provide any useful information to users.

Additionally:

Each item may provide additional information like the 'sticky' status or the 'locked' status. These need improvements as well and I will open a separate issue. For now, I'd like to address also the 'Options' ellipsis button. To me, these aren't 'Options'. The concept of options is about settings or preferences, while the dropdown menu provides _actions_. Also, in other context  this ellipsis button is labeled 'Actions', for example in the patterns cards. For a more meaningful naming and for consistency I'd like to rename this button to 'Actions' and simplify it by removing the part 'for %s'.

### Step-by-step reproduction instructions

- Use a screen reader, for example VoiceOver with Safari.
- Go to the Site Editor > Design > Navigation > Any navigation menu.
- Navigate through the list view items in the navigation panel.
- Observe the items are announced with their navigation link _type_ rather than their link text.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by afercia**
Fixes https://github.com/WordPress/gutenberg/issues/59369

## What?

In the Site Editor > Design > Navigation > Any navigation menu, the labeling of the list view doesn't provide any informatiom about _what_ the item is. The only information provided is the link _type_.

## Why?

To be able to understand what they are going to edit, users need to know what the link actually is, ie. the link text.

## How?

- Provides a more meaningful label for the navigation-link blocks in the list view.
- Also simplifies the 'Options for %s' label of the ellipsis button to 'Actions', for simplicity and consistency.

## Testing Instructions

- Use a screen reader, for example VoiceOver with Safari.
- Go to the Site Editor > Design > Navigation > Any navigation menu.
- Navigate through the list view items in the navigation panel.
- Observe the items are now announced with their visible text so users can understand what the link they are going to edit is.
- Observe the item position is correctly provided in the visually hidden description of each item e.g. `Block 3 of 5, Level 1. `.
- Once on a selected item, use the arrow keys to move focus to the ellipsis button or hover the button to reveal its tooltip.
- Observe the button is announced as 'Actions' (same for the tooltip).
- Edit a navigation link, empty its label and save.
- ~Observe in the editor navigation panel list view the empty link has now a label 'Untitled'.~
- Update: The empty link will be empty in the list view, this is unchanged and will need to be addressed separately.
- Go to the post editor.
- Add a variety of blocks, for example:
  - blocks with default names
  - blocks with custom names (renamed by users)
  - synced patterns with user provided names
- Navigate the list view items with a screen reader and observe they are announced in the most meaningful way for that specific kind of block e.g.: custom name for renamed blocks, user provided name for synced patterns, default block name for default blocks etc.
- Add a Group block with a paragraph and lock the Group.
- In the list view, inspect the Group item and observe the visually hidden description provides both the block position and the locked state e.g.: `Block 3 of 5, Level 1. This block is locked.`
- Add a Heading block that only contains spaces. Save.
- Observe the heading is named 'Heading' in the List View.
- Onserve the headint is reported as empty heading in the Document Outline, screenshot:

Screenshot 2024-03-19 at 09 00 11

### CODE REVIEW

**Review by alexstine — APPROVED** [review]
@afercia Accessibility seems sound.

@talldan FYI.

**Comment by alexstine** [comment]
Also, @andrewserong.

**Comment by afercia** [comment]
Thanks @alexstine for your review.

To recap the main change in this PR, the logic to determine the list view items accessible name changes from this:

`blockInformation?.name || blockInformation?.title || __( 'Untitled' );`

to this:

`block.attributes?.label || blockInformation?.name || blockInformation?.title || __( 'Untitled' );`

This is to take into account navigation links because the links text is stored in their `label` attribute. However, I'm not sure this series of OR is great, it seems a bit fragile to me. I think it would have been better to treat the navigation links text label as the block custom name in the first place.
Would apprecaite some thoughts from @talldan

**Comment by afercia** [comment]
Noting that the labeling will need further improvements for the 'locked' information, the 'sticky' information and 'anchor' information that are visually added to the items in the list view, see https://github.com/WordPress/gutenberg/issues/59409

**Comment by afercia** [comment]
I decided to change approach.
Basically, the aria-label is only usd to add the `(locked)` information text. However, that info should be moved away from the label to a description. Any info about the block 'properties' like locked, sticky, or the anchor should not contribute to compoute the accessible name of the list view item. A follow-up is tracked in https://github.com/WordPress/gutenberg/issues/59409

As such I decided to remove the aria-label. The accessible name will now be the visible text. This has a few advantages:
- Visible text and accessible name do match.
- There is no longer the need to duplicate logic to retrieve the item label or name or title. That's already handled by `useBlockDisplayTitle` in the [ListViewBlockSelectButton](https://github.com/WordPress/gutenberg/blob/371a3ec6d9fcb5eb2afa3f2732a77c3f9f59d18a/packages/block-editor/src/components/list-view/block-select-button.js#L63-L66).
- The 'locked' info is moved to the visually hidden description. This also paves the way for https://github.com/WordPress/gutenberg/issues/59409 as more information will be added to the description.

**Comment by alexstine** [comment]
@afercia Yeah, I've been wanting to do that for a while now but never got around to refactoring all of that out of the aria-label. Thanks, having another pass on this soon.

**Review by alexstine — APPROVED** [review]
This is testing well.

**Comment by afercia** [comment]
Latest commit improves things a bit by providing the 'Untitled' fallback only for block labels (e.g. navigation links with a link text made of only spaces) and by adding a test.

A separate issue is whether the editor should ever allow to render empty links on the front end, which is tracked in a separate issue at https://github.com/WordPress/gutenberg/issues/59560

**Comment by afercia** [comment]
It is also worth noting that right now on trunk it is possible to add a Heading block and leave it empty or with only spaces.
In this case, the List View will only show an icon and an empty list item, which is less than ideal. Screenshot:

Screenshot 2024-03-07 at 15 15 04

The current code on trunk prioritizes a block `label` but it doesn't check if the label is empty or made of only spaces. This PR does it and fallbacks to 'Untitled'.

**Comment by afercia** [comment]
I'm probably missing something, as the failing tests show. I'll go again through my changes to see what I'm doing wrong.

**Comment by afercia** [comment]
To clarify:
I opted to use `Untitled` as a fallback because the fallback should be consistent with what we want to show on the front end for empty links or empty headings etc. See https://github.com/WordPress/gutenberg/issues/59560. It is also worth reminding that Classic Themes render `Untitled` for empty navigation links.

I'd appreciate more thoughts on this though Cc @getdave Open to consideer a different fallback if that's more desirable.

**Comment by Mamaduka** [comment]
@afercia, the empty heading bug was resolved in #59827.

**Comment by afercia** [comment]
Thanks @Mamaduka I will rebase. It seems https://github.com/WordPress/gutenberg/pull/59827 doesn't take into account the case when a heading contains only spaces though so I hink a `trim()` is still necessary. Screenshot from latest trunk:

Screenshot 2024-03-18 at 08 49 39

In this case, also the `accessibility` label won't provide a meaningful information because spaces will be appended to the aria label e.g. `aria-label="Heading Block. Row 2. Level 2.   "` while it should say it is empty.

**Comment by Mamaduka** [comment]
Good point. I can follow up on that! 

**Update:** Though historically, the RichText only checked emptiness based on the string length. See: https://github.com/WordPress/gutenberg/blob/trunk/packages/rich-text/src/is-empty.js

Do we still want to account for spaces?

**Comment by getdave** [comment]
Ideally we'd wrap this bug up in a single PR @Mamaduka as it will be easier to manage from a release perspective. Is that possible?

**Comment by Mamaduka** [comment]
@getdave, do you mean to push fixes on this branch?

File: packages/block-editor/src/components/block-title/use-block-display-title.js [hunk 1]
```diff
@@ -54,7 +55,11 @@ export default function useBlockDisplayTitle( {
 			const label = getBlockLabel( blockType, attributes, context );
 			// If the label is defined we prioritize it over a possible block variation title match.
 			if ( label !== blockType.title ) {
-				return label;
+				// Users can enter and save a label made of only spaces e.g. for
+				// navigation links. In that case we provide a fallback label.
+				// We do want to trim leading and trailing spaces anyways.
+				const trimmedLabel = label.trim();
+				return trimmedLabel === '' ? __( 'Untitled' ) : trimmedLabel;
```
Comment (Mamaduka) [inline packages/block-editor/src/components/block-title/use-block-display-title.js]: I think this should be handled in `getBlockLabel`, which should return a fallback (block title) when only spaces are provided.

Then, we don't need to handle this case by case.

I just saw [this comment](https://github.com/WordPress/gutenberg/pull/59370#issuecomment-1985701404). Changes in this hook will affect every block in the editor. While the argument makes sense for Heading and Navigation links, it might not work for other blocks like Template Part.

**Comment by getdave** [comment]
> do you mean to push fixes on this branch?

Sorry for adding confusion. 

I'm not personally intending to be pushing fixes to this branch.

I meant, if this is targeting 6.5 it'd probably be easier for all fixes to be in a single PR. But if the followups are minor then maybe we should ship this one "as is" and then decide on whether it would be more appropriate to wait on the followups until a post-6.5 patch release?

**Comment by Mamaduka** [comment]
@getdave, unfortunately, I've not been following PR closely enough to propose the milestone. But I can see that PR introduces a new string that can't be merged after hard string free — RC1.

**Comment by afercia** [comment]
In the latest two commits:
- I reverted the changes to `useBlockDisplayTitle`. This leaves unsolved the problem when users add only empty spaces to a heading or to a navigation link. However, this seems a broader problem that needs to be addressed separately.
- For the heading block: made sure the label is trimmed before being checked.

Overall, I think a decision should be made first: whether to allow users to save empty headings or empty links. This should be evaluated for other blocks as well but it's very impportant for headings and links.

Update:
I forgot to mention this PR also introduces a chance in the document outline, by trimming a heading content so that a heading that only contains spaces is considered 'empty' and reported as such in the document outline. Will update the test instrtuctions, for posterity.

**Comment by afercia** [comment]
> Do we still want to account for spaces?

I think this will need a careful evaluation on what it's best for users. It really depends on the kind of content (the block type). It doesn't only impact the admin, it impacts also the front end. For example:
- Empty headings are far from ideal for SEO and accessibility. The editor should not allow to save empty headings. They shouldn't even be rendered on the front end.
- Empty links are far from ideal for SEO and accessibility.
- Other empty blocks may have a minor impact. However, I'm not sure why in the world we'd want to render useless markup on the front end when the block is completely empty. For example. add an empty Code block and save. Observe the following, totally useless, markup is rendered on the front end: `<pre class="wp-block-code"><code></code></pre>`

@getdave @Mamaduka thanks for your feednack, when you have a chance I'd appreciate a final review.

**Review by Mamaduka — APPROVED** [review]
Thank you, @afercia. The changes test well for me ✅

File: packages/block-editor/src/components/list-view/block.js [hunk 2]
```diff
@@ -405,7 +396,7 @@ function ListViewBlock( {
 							clientIds={ dropdownClientIds }
 							block={ block }
 							icon={ moreVertical }
-							label={ settingsAriaLabel }
```
Comment (richtabor) [inline packages/block-editor/src/components/list-view/block.js:408]: I had [previously inquired about simplifying the "Options for %s" label](https://github.com/WordPress/gutenberg/issues/57078), but was informed the block name was necessary by @alexstine. Is that no longer the case? 

Either way though, this should be renamed "Options", like it's called in the block toolbar (as they're the same). 

@afercia @Mamaduka Was there a reason to change "Options" to "Actions"?

Comment (alexstine) [reply packages/block-editor/src/components/list-view/block.js:408]: @richtabor I guess it was a battle I was going to lose eventually. It was really a stopgap to make NVDA behave as sometimes navigating the rows on the right side would not tell you which block you were opening an options menu for.
