### PR TITLE
RichText: allow emoji panel at list item start

### LINKED ISSUE #17538: List block: indentation keyboard shortcut prevents MacOS emoji panel from opening at start of list item
**Describe the bug**

In the list block, there is a keyboard shortcut to indent the list (Ctrl + Space).

On OS X, there is a system keyboard shortcut to open the emoji panel (Ctrl + Cmd + Space).

This conflict means that it is not possible to open the emoji panel at the start of a new list item.

**To reproduce**
1. Create a new list block
2. Create a list item without any text
3. Press Ctrl+Command+Space to bring up the emoji panel
4. Notice that the list item is indented instead

**Expected behavior**
When I press Ctrl+Command+Space, the emoji panel should always appear.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 76

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #17538.

Currently it is not possible to use `Space` together with any modifier keys at the start of a list item:

* The emoji pop up can't be opened on `MacOS` (`Ctrl+Cmd+Space`).
* You can't insert a non breaking space (`Alt+Space`).
* You can't insert a normal space character (`Shift+Space`).

This PR fixes the issues. I also added an e2e test.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/block-editor/src/components/rich-text/index.js [hunk 1]
```diff
@@ -260,7 +260,7 @@ class RichTextWrapper extends Component {
 		const { start, text } = value;
 		const characterBefore = text.slice( start - 1, start );
 
-		if ( ! /\s/.test( characterBefore ) ) {
```
Comment (epiqueras) [inline packages/block-editor/src/components/rich-text/index.js]: This warrants a comment.

File: packages/e2e-tests/specs/blocks/list.test.js [hunk 2]
```diff
@@ -427,4 +427,23 @@ describe( 'List', () => {
...
+		await clickBlockAppender();
+
+		await page.keyboard.type( '* 1' );
+		await page.keyboard.press( 'Enter' );
+		await pressKeyWithModifier( 'shift', 'Space' );
+
+		expect( await getEditedPostContent() ).toMatchSnapshot();
+	} );
+
+	it( 'should only convert to list when shortcut ends with space', async () => {
```
Comment (epiqueras) [inline packages/e2e-tests/specs/blocks/list.test.js]: Nice!

**Review by epiqueras — CHANGES_REQUESTED** [review]

**Review by epiqueras — APPROVED** [review]

File: packages/block-editor/src/components/rich-text/index.js (hunk 1 above)
Comment (epiqueras) [reply packages/block-editor/src/components/rich-text/index.js]: >The character right before the caret must be a plain space.

We should explain why.

**Review by epiqueras — DISMISSED** [review]
