### PR TITLE
REST API: Support search_columns argument in the user endpoint

### LINKED ISSUE #67331: Author selector becomes unusable on sites with many authors
### Description

The current author selector implementation has a few limitations that make it unusable on sites greatly exceeding 50 authors:

1. The dropdown is limited to showing only 50 authors
2. The search functionality is also limited to returning 50 results
3. Search criteria mismatch between frontend and backend:
   - Backend (REST API) searches `user_login`, `user_email`, and `user_nicename`
   - Frontend filters differently, leading to inconsistent results
   - This means sometimes the backend can return 50 results and none of them appear on the frontend
4. Including email in search can make results unusable if many authors share a common email domain and the search criteria matches the domain.
5. No pagination or "Load more" functionality exists

Image

Image

### Impact

Some authors are inaccessible.

If an author is not in the first 50 alphabetical entries, they can only be chosen if they are found by search. However, search limitations may make that impossible. Imagine the scenario of a company with 2000 authors with "@stevesburgers.com" email addresses. If you search "Steve", looking for "Steve Smith", it's quite likely that no results will be displayed. This is because the backend will return the first 50 users with "Steve" in their email - Likely employees with names beginning with A-C because they come first alphabetically - and the frontend will filter them all out, because the frontend is looking for the string "Steve" in the name fields, not the email. The actual "Steve Smith" user will not be returned by the backend since it's past the 50 user cutoff, and the frontend won't get a chance to render it.

### Expected Behavior
 
- All authors should be accessible

## Technical Details

Current REST API endpoint (`/wp/v2/sites/{site}/users`) uses these arguments:
```json
{
  "exclude": [],
  "include": [],
  "order": "asc",
  "number": 50,
  "search": "*search_term*",
  "offset": 0,
  "orderby": "display_name",
  "who": "authors"
}
```

The resulting SQL includes email in search:
```sql
WHERE (user_login LIKE '%term%' OR user_email LIKE '%term%' OR user_nicename LIKE '%term%')
```

## Possible Solutions
- Add pagination or "Load more"
- Use consistent criteria between frontend/backend
- Make the author limit configurable
- Make search fields configurable (for example, turn off email domain matching)

## Impact
This affects any WordPress site with more than 50 authors, but is particularly problematic for:
- Multi-author news sites
- Corporate blogs
- Educational institutions
- Any site where authors share an email domain

## See Also
Note that #15994 is related but it doesn't seem to cover the frontend/backend search mismatch.

## Steps to Reproduce
1. Create a blank WordPress site
2. Use the FakerPress plugin to add 500 users with Author role
3. Open the post editor
4. Try to assign an author who isn't in the first 50 alphabetically by scrolling down in the list.
5. Try searching for a common string that would match many authors ("example" here - FakerPress puts this in their email domain)
6. Notice:
* You can't scroll past 50 authors
* Search results are limited to 50
* If you search for something matching the email domain, you get back authors A-C but can't reach later alphabetical authors

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- Gutenberg: 19.6.4
- WordPress: 6.x+

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by youknowriad**
closes #67331

## What?

There's a weird bug in the "post author" selector in the editor. Say you have a site with thousands of users, and imagine these users all have emails that end with `@automattic.com` :).  This means that if you search for an author named "Matt" in the post author selector, you'll never be able to assign the post to that person. The reason is the following:

 - The REST API would return the 50 first results and the user endpoint by default search within emails, names slugs and usernames, all the users will be returned, so you'll be getting the first 50 users and none of them is actually named "Matt" :P 

What a funny 🐛 right :) 

This PR solves this by adding support for a `search_columns` argument to the user endpoint. A similar argument is already supported for the posts endpoints.

## Testing Instructions

Based on #38791, props to @claudiulodro!

1. Generate a couple of hundred users and give them all `example.com` email address.
2. Open Dashboard > Users page.
3. Navigate to the last page on the list table and edit the last user.
4. Change their display and nickname name to `User Example`.
5. Open a post or page and search for an `example` author.
6. Confirm that "User Example" shows up in the results. **This doesn't work on trunk**

A snippet for user generation via WP CLI

```bash
wp user generate --role=author --format=ids --count=300 | tr ' ' '\n' | xargs -I % wp user update % --user_email="blah-$(echo %)@example.com"
```

## Screenshot

153926147-1bda6114-1610-4dd0-9e74-4c6b14862a97

### CODE REVIEW

File: packages/editor/src/components/post-author/constants.js [hunk 1]
```diff
@@ -5,6 +5,6 @@ export const BASE_QUERY = {
 
 export const AUTHORS_QUERY = {
 	who: 'authors',
-	per_page: 50,
+	per_page: 100,
```
Comment (youknowriad) [inline packages/editor/src/components/post-author/constants.js:8]: I don't see any reason to limit this to 50, I just put 100 which I believe is the max.

**Comment by Mamaduka** [comment]
A couple of surface notes:

* We should dig for historical reasons why this hasn't been supported yet.
* Check how it affects performance on large installations with many users.

File: packages/editor/src/components/post-author/constants.js (hunk 1 above)
Comment (Mamaduka) [reply packages/editor/src/components/post-author/constants.js:8]: I don't remember the exact reason; it was probably just an arbitrary number we chose. I'll have a better look tomorrow.

**Comment by youknowriad** [comment]
> Check how it affects performance on large installations with many users.

I think this has no impact at all since it's the "search_columns" for WP_Query is already used in the search endpoint. It's just using the default value when the user has the "list_users" capability, otherwise it's using `array( 'ID', 'user_login', 'user_nicename', 'display_name' )` for the rest of the users which in all situations is worse for performance than using just one of these like done here.

> We should dig for historical reasons why this hasn't been supported yet.

My guess is that it was just not requested. Even the posts endpoint one is a recent addition https://core.trac.wordpress.org/ticket/43867

File: packages/editor/src/components/post-author/constants.js (hunk 1 above)
Comment (Mamaduka) [reply packages/editor/src/components/post-author/constants.js:8]: Confirmed. The `50` was just an arbitrary number. It might affect initial loading for the post editor on sites with a large user sets, but it's hard to measure locally.

File: lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php
Comment (Mamaduka) [inline lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php:1]: Should we also move this into the `6.8/rest-api.php` file as we did for the `rest_index` changes?

File: lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+		$valid_columns          = isset( $prepared_args['search_columns'] )
+			? $prepared_args['search_columns']
+			: array( 'ID', 'user_login', 'user_nicename', 'user_email', 'user_url', 'display_name' );
+		$search_columns_mapping = array(
+			'id'       => 'ID',
+			'username' => 'user_login',
+			'slug'     => 'user_nicename',
+			'email'    => 'user_email',
+			'name'     => 'display_name',
+		);
```
Comment (Mamaduka) [inline lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php:46]: Question (non-blocking): The post controllers don't map these values; should we follow the same example?

File: packages/editor/src/components/post-author/constants.js (hunk 1 above)
Comment (youknowriad) [reply packages/editor/src/components/post-author/constants.js:8]: Happy to revert that if you think it's better for now, it's kind of outside the scope of the current PR.

File: lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+		$search_columns         = array_map(
+			function ( $column ) use ( $search_columns_mapping ) {
```
Comment (Mamaduka) [inline lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php]:
```suggestion
			static function ( $column ) use ( $search_columns_mapping ) {
```

**Review by Mamaduka — COMMENTED** [review]
Left some initial notes. Currently, trying to come dummy data generation method to actually test the fix :)

File: packages/editor/src/components/post-author/constants.js (hunk 1 above)
Comment (Mamaduka) [reply packages/editor/src/components/post-author/constants.js:8]: We can keep it. The query only fetches the `id,name` fields; the response size difference between 50 and 100 should be minimal.

File: lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php
Comment (youknowriad) [reply lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php:1]: I think not, since these changes are actually going to be applied to that file in Core. I believe our approach is to try to map core files in these compat folders.

File: lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php (hunk 2 above)
Comment (youknowriad) [reply lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php:46]: Personally, I think it's a mistake that they're not mapped in the posts controller. I think the arguments should match the "fields" that are present in the schema and also the `_fields` argument.

Comment (Mamaduka) [reply lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php:46]: > I think the arguments should match the "fields" that are present in the schema and also the _fields argument.

Agreed. Just double checking for the record :)

**Comment by Mamaduka** [comment]
I've updated the testing instructions. Props again to @claudiulodro for originally reporting the bug.

**Comment by ntsekouras** [comment]
While I get the use case described in the PR, someone could also search by email. This is subjective, but to be honest personally I usually go by emails at similar cases, as they are unique. Having said that, I think the `search_columns` value might be better to be an adjustable option that users can change, because with this fix we will create a bug for not searching  in `emails`. 

By the way, you can test way easier by adjusting this value [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/post-author/index.js#L14). I just set it to 1 and had to create a single user.

**Comment by youknowriad** [comment]
> While I get the use case described in the PR, someone could also search by email. This is subjective, but to be honest personally I usually go by emails at similar cases, as they are unique. Having said that, I think the search_columns value might be better to be an adjustable option that users can change, because with this fix we will create a bug for not searching in emails.

For me it doesn't make sense to search by email unless you actually show the emails in the results which we don't.

File: lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php [hunk 4]
```diff
@@ -0,0 +1,64 @@
...
+		$search_columns_mapping = array(
+			'id'       => 'ID',
+			'username' => 'user_login',
+			'slug'     => 'user_nicename',
+			'email'    => 'user_email',
+			'name'     => 'display_name',
+		);
+		$search_columns         = array_map(
+			static function ( $column ) use ( $search_columns_mapping ) {
+				return isset( $search_columns_mapping[ $column ] )
```
Comment (ntsekouras) [inline lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php]: I think we'll always have the mapping value, because the request would bail earlier if not, by the collection params validation.

File: lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php [hunk 5]
```diff
@@ -0,0 +1,64 @@
...
+ * @param array $query_params JSON Schema-formatted collection parameters.
+ * @return array Updated collection parameters
+ */
+function gutenberg_add_search_columns_param( $query_params ) {
+	$query_params['search_columns'] = array(
+		'default'     => array(),
+		'description' => __( 'Array of column names to be searched.' ),
+		'type'        => 'array',
+		'items'       => array(
+			'enum' => array( 'email', 'name', 'id', 'username', 'slug' ),
```
Comment (ntsekouras) [inline lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php:15]: Was there a specific reason not to add `user_url` too?

**Review by ntsekouras — APPROVED** [review]
I left some small comments, but this looks good. Thank you!

**Comment by ntsekouras** [comment]
>For me it doesn't make sense to search by email unless you actually show the emails in the results which we don't.

Fair enough. Ok.

File: lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php (hunk 4 above)
Comment (youknowriad) [reply lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php]: Ah I didn't know we had automatic validation.

File: lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php (hunk 5 above)
Comment (youknowriad) [reply lib/compat/wordpress-6.8/class-gutenberg-rest-user-controller.php:15]: I think I based this choice on the default used by the search algorithm

**Comment by Mamaduka** [comment]
Re-updated search columns: The `Combobox` filters/searches by `name`, so it makes sense to do the same on the server.

**Review by Mamaduka — APPROVED** [review]
