### PR TITLE
Navigation: Don't save the level of the link in an attribute

### LINKED ISSUE #47829: Navigation Block: fix link UI popover only opens if there's one navigation block in the page
### Description

While fixing https://github.com/WordPress/gutenberg/pull/47828 we uncovered a new bug in the case where more than one navigation block is present on the page.

### Step-by-step reproduction instructions

Insert a navigation block with custom links. 
Click the inserter to add a new custom link, it should trigger the popover to edit the link.
Insert a new navigation block just below.
Insert a new custom link to it. The popover should open, but it doesn't.

### Screenshots, screen recording, code snippet

Screen Capture on 2023-02-07 at 12-21-54

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #48594: Site Editor: Crashes when loading navigation panel
## What problem does this address?
If you try to load the navigation panel in the site editor directly, it crashes when the navigation contains any custom links:

## Steps to reproduce
1. Create a navigation that contains a custom link
2. Visit wp-admin/site-editor.php?canvas=view&path=%2Fnavigation
3. Wait
4. Notice that the site editor crashes (it takes a few seconds)

## Screen recording

https://user-images.githubusercontent.com/275961/221882273-1dd67781-0b66-4c79-a5f0-357235ce5107.mov

### LINKED ISSUE #48668: Occur "Maximum update depth exceeded.” in Navigation Screen.
### Description

Adding a Custom Link block to the navigation causes "Maximum update depth exceeded.”

This problem does not occur in 15.2.4, it occurs with trunk ( 4945d3f42254e36a87a09aa4f99cfbdca916f962 ).

```
Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (react-dom.js?ver=18:27302:13)
    at scheduleUpdateOnFiber (react-dom.js?ver=18:25485:5)
    at dispatchSetState (react-dom.js?ver=18:17537:9)
    at assignRef (index.js:20:3)
    at index.js:128:4
    at safelyDetachRef (react-dom.js?ver=18:22918:24)
    at commitDeletionEffectsOnFiber (react-dom.js?ver=18:24013:13)
    at recursivelyTraverseDeletionEffects (react-dom.js?ver=18:23999:7)
    at commitDeletionEffectsOnFiber (react-dom.js?ver=18:24128:11)
    at recursivelyTraverseDeletionEffects (react-dom.js?ver=18:23999:7)
```

### Step-by-step reproduction instructions

1. Go to Site Editor.
2. Select Navigation Screen. ( http://localhost:8888/wp-admin/site-editor.php?canvas=view&path=%2Fnavigation )
3. Insert "Custom Link" Block to Navigation.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1908815/222364797-2cf131d4-c42e-459b-a05d-42c6965dc2c4.mov

### Environment info

- Gutenberg: trunk ( 4945d3f42254e36a87a09aa4f99cfbdca916f962 )

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by scruffian**
## What?
The useEffect that saves the `isTopLevelLink` and `isTopLevelItem` to an attribute causes ripples through the other useEffects in the navigation block, which means that we get unexpected bugs like those listed below.

I don't think we need this useEffect at all - we don't even need to know if this is a top level link. Instead we can output the colors on the navigation submenu wrapper element itself. 

Closes https://github.com/WordPress/gutenberg/issues/47829
Closes https://github.com/WordPress/gutenberg/issues/48594
Closes https://github.com/WordPress/gutenberg/issues/48668

## Why?
I think this is a simpler approach and avoids the needs for a useEffect and extra attributes. 

## Testing Instructions
- Set a submenu color on the navigation block
- Check that the color setting is applied only to the submenu, and not the top level links.
- Test this for both text color and background color
- Test setting custom colors and preset colors

### Testing Instructions for Keyboard
I suppose you'll have to inspect the code to ensure that the correct colors are applied.

## Screenshots or screencast 
Here are some disgusting colors:
Screenshot 2023-03-02 at 12 37 17

### CODE REVIEW

File: packages/block-library/src/navigation-link/index.php [hunk 1]
```diff
@@ -5,77 +5,6 @@
...
 
-/**
- * Build an array with CSS classes and inline styles defining the colors
- * which will be applied to the navigation markup in the front-end.
- *
- * @param  array $context    Navigation block context.
- * @param  array $attributes Block attributes.
- * @return array Colors CSS classes and inline styles.
- */
-function block_core_navigation_link_build_css_colors( $context, $attributes ) {
```
Comment (scruffian) [inline packages/block-library/src/navigation-link/index.php:16]: I'm not sure why this was duplicated. I'd rather use the same function in both places. If we need to keep two copies of it, I'm not sure what we should do with this one - it never uses the $is_sub_menu branch, so we could just remove all that, but then it diverges from `block_core_navigation_submenu_build_css_colors`.

File: packages/block-library/src/navigation-link/index.php [hunk 2]
```diff
@@ -174,7 +103,7 @@ function render_block_core_navigation_link( $attributes, $content, $block ) {
 		return '';
 	}
 
-	$colors          = block_core_navigation_link_build_css_colors( $block->context, $attributes );
+	$colors          = block_core_navigation_submenu_build_css_colors( $block->context, $attributes );
```
Comment (scruffian) [inline packages/block-library/src/navigation-link/index.php]: Is it possible that this function won't be defined? I suppose it is possible for someone to deregister the navigation submenu block, but not the navigation-link block, though I can't think why you would do that. We could move the function to the parent block...

File: packages/block-library/src/navigation-submenu/index.php [hunk 3]
```diff
@@ -263,8 +269,16 @@ function render_block_core_navigation_submenu( $attributes, $content, $block ) {
 			$html = $tag_processor->get_updated_html();
 		}
 
+		$wrapper_attributes = get_block_wrapper_attributes(
+			array(
+				'class' => $css_classes,
+				'style' => $style_attribute,
```
Comment (getdave) [inline packages/block-library/src/navigation-submenu/index.php:277]: Let's make sure we're escaping this output if it's coming direct from uses

Comment (scruffian) [reply packages/block-library/src/navigation-submenu/index.php:277]: It is escaped here: https://github.com/WordPress/wordpress-develop/blob/0cb8475c0d07d23893b1d73d755eda5f12024585/src/wp-includes/class-wp-block-supports.php#L216

Comment (scruffian) [reply packages/block-library/src/navigation-submenu/index.php:277]: I added an extra esc_attr just to be sure!

Comment (getdave) [reply packages/block-library/src/navigation-submenu/index.php:277]: Oh sorry. I missed `get_block_wrapper_attributes`. It doesn't need escaping again. My bad !

**Review by getdave — COMMENTED** [review]
I tested this and it worked in the editor but not on the front of the site. I was using TT3.

# Editor
Screen Shot 2023-03-03 at 09 28 27

# Front of Site
Screen Shot 2023-03-03 at 09 28 40

**Review by getdave — COMMENTED** [review]
I tested this and the colors were applied as expected.

#### Front of Site

Screenshot 2023-03-03 at 09 45 47


#### Editor
Screenshot 2023-03-03 at 09 46 10

File: packages/block-library/src/navigation-submenu/index.php [hunk 4]
```diff
@@ -249,12 +249,13 @@ function render_block_core_navigation_submenu( $attributes, $content, $block ) {
 	}
 
 	if ( $has_submenu ) {
-		$colors          = block_core_navigation_submenu_build_css_colors( $block->context, $attributes, true );
-		$classes         = array_merge(
+		$colors      = block_core_navigation_submenu_build_css_colors( $block->context, $attributes, $has_submenu );
```
Comment (scruffian) [inline packages/block-library/src/navigation-submenu/index.php:252]: 👍

**Review by getdave — APPROVED** [review]
I tested this and couldn't find any regressions. I would prefer if we had a few more manual tests confirming the same. 

I'm going to cautiously approve though as I think this fix is critical for fixing numerous bugs.

**Comment by getdave** [comment]
@ntsekouras @Mamaduka I've added the backport label to this PR as I believe we need it to fix several bugs. I would prefer if more people could test it before it gets merged.

**Review by MaggieCabrera — APPROVED** [review]
This is working as expected!

**Review by draganescu — CHANGES_REQUESTED** [review]
There is a bug when moving a submenu item to top level, it gets rendered with submenu item colors - not happening on `trunk` for me:


https://user-images.githubusercontent.com/107534/222701971-20375385-0ce9-4535-b1d9-2205af9b8291.mp4

**Comment by scruffian** [comment]
I have fixed that bug in [623d6f5](https://github.com/WordPress/gutenberg/pull/48219/commits/623d6f5cf61730ab043fc419bfe42b0d32347f4f)

**Review by draganescu — APPROVED** [review]
I think this is a good change and in my testing it works as described.

**Comment by getdave** [comment]
🍾 🍾 🍾 🍾 🍾 🍾

**Comment by ntsekouras** [comment]
I just cherry-picked this PR to the wp/6.2 branch to get it included in the next release: e749760c01
