### PR TITLE
RichText: fix isComposing for Safari

### LINKED ISSUE #19161: (Safari) Dead key accents break out of inline formatting
**Description**

In Safari, when typing in a RichText element within an inline format (e.g. bold, italic), attempting to compose an accented character (e.g. **à**, **é**) using dead keys (e.g. **`**, **´**) results in the next character (and subsequent text) to be rendered without any inline formatting applies.

**Note:** Looking closely, we can see that the formatting is dropped as soon as the dead key is entered. My hunch is that the something in that character, such as its special width, throws off the logic in RichText that determines the position of the inline formatting boundaries.

**To reproduce**

0. Switch to a keyboard layout with dead keys (e.g. `Portuguese (Portugal)` or `English (International)`.
1. Start writing in a Paragraph block.
2. Apply a formatting such as Bold and keep writing.
3. Attempt to input `é` by pressing <kbd>´</kbd> followed by <kbd>e</kbd>.
4. Notice how `é` appears with no formatting applies.

**Expected behavior**

Formatting shouldn't be affected by character input.

**Screenshots**

dead-keys

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Safari, latest stable

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #19161.

Apparently Safari doesn't support `isComposing` on an `input` event. See https://developer.mozilla.org/en-US/docs/Web/API/InputEvent/isComposing.
 The solution is to set a flag on `compositionstart` and remove and `compositionend`.

Unfortunately, we cannot add an e2e test right now. See https://github.com/puppeteer/puppeteer/issues/4981.

## How has this been tested?

For an American keyboard:

* Create a paragraph.
* Press `Cmd+B`, then ``Alt+` ``, then type "a". "à" should be bold.

## Types of changes

Bug fix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

File: packages/rich-text/src/component/index.js [hunk 1]
```diff
@@ -403,17 +404,10 @@ class RichText extends Component {
...
-		if (
-			event &&
-			event.nativeEvent &&
-			event.nativeEvent.isComposing
-		) {
-			// Also don't update any selection.
-			document.removeEventListener( 'selectionchange', this.onSelectionChange );
+		// Do not trigger a change if characters are being composed. Browsers
+		// will usually emit a final `input` event when the characters are
+		// composed.
```
Comment (mcsf) [inline packages/rich-text/src/component/index.js]: Thanks for all the comments. Maybe expand this one to reflect the current change, e.g.

> … As of December 2019, Safari doesn't honour `nativeEvent.isComposing`.

Incidentally, that could make it easier — later on, in a year or ten — to know what workarounds can be eliminated in our code base.

**Review by mcsf — APPROVED** [review]
This is great, thanks for the prompt fix!

File: packages/rich-text/src/component/index.js (hunk 1 above)
Comment (ellatrix) [reply packages/rich-text/src/component/index.js]: Yes, I should add something here. I'm also wondering if I should still use `nativeEvent.isComposing` and fall back to `this.isComposing`. Normally `compositionstop` _should_ fire, but who knows, if in some rare cases it doesn't, the value would be stuck at `true` until composing is started again. `nativeEvent.isComposing` is probably more reliable. On the other hand, always using `this.isComposing` will more quickly surface any bugs.

Comment (mcsf) [reply packages/rich-text/src/component/index.js]: I don't oppose to listening to those two sources, but is there anything making you doubt of `compositionstop`'s reliability? Since it's a proper `SyntheticEvent`, I would expect adequate browser support.

Comment (ellatrix) [reply packages/rich-text/src/component/index.js]: Yes, browser support is good, but I wouldn't be surprised if it's implemented slightly differently in browsers, just like the calling order of all these event handlers, or not called at all in some situations. Let's try this and keep an eye on reports.
