### PR TITLE
Cover: Enable support for adding posters over video

### LINKED ISSUE #18962: Cover block with video: no option to set a poster
**Describe the bug**
One can choose not just images but also videos from the media library to be shown in the cover block.

This is cool, however videos tend to be large and for some reason the cover block does not let us set a poster image like the video block does. All this leads to a black background to be shown until the video is loaded, but that can be a confusing user experience in case of larger videos. 

**Expected behavior**
Also the Cover block needs an option to set a poster image for video like the Video block has that feature.

### PR DESCRIPTION
**Pull request by yogeshbhutkar**
## What?
Closes #18962

This PR adds support for displaying posters over videos within the `Core/Cover` block.

## Why?

For larger videos and users on slower connections, the inability to set a poster image can result in blocks displaying a blank background, leading to a poor user experience.

## How?

The refactorings made in https://github.com/WordPress/gutenberg/pull/67044 extracted the `poster-image` component, which is reused in this PR to implement a similar functionality within the `core/cover` block.

## Testing Instructions

1. Create a new post and insert a cover block.
2. Attach a large video to it.
3. Also, attach a corresponding poster image to the video.
4. On the front-end, from the developer tools, enable network throttling and set the throttle to "fast 4G".
5. Confirm that the poster gets shown and acts as a placeholder until the video loads up.

### Testing Instructions for Keyboard
Same.

## Screencast

https://github.com/user-attachments/assets/177dc205-674b-4abf-b5e7-ccb1b439bdc5

### CODE REVIEW

File: packages/block-library/src/cover/edit/inspector-controls.js [hunk 1]
```diff
@@ -243,6 +247,13 @@ export default function CoverInspectorControls( {
 								</ToolsPanelItem>
 							</>
 						) }
+						{ isVideoBackground && (
+							<PosterImage
+								poster={ poster }
+								setAttributes={ setAttributes }
+								instanceId={ instanceId }
+							/>
+						) }
```
Comment (fabiankaegy) [inline packages/block-library/src/cover/edit/inspector-controls.js]: This should use the same design pattern as the other controls of the block and live inside a ToolsPanelItem

**Review by fabiankaegy — COMMENTED** [review]
Very cool! I left one comment that we need to address before we can merge this but other than that I think this works as intended and solves a very old issue :)

File: packages/block-library/src/cover/edit/inspector-controls.js (hunk 1 above)
Comment (yogeshbhutkar) [reply packages/block-library/src/cover/edit/inspector-controls.js]: Thanks for the review, @fabiankaegy.

The `PosterImage` component already uses `ToolsPanelItem` under the hood.

See: https://github.com/WordPress/gutenberg/blob/cb72f6d60308f331d1437da82c019a25d8cbca57/packages/block-library/src/video/poster-image.js#L31

Comment (fabiankaegy) [reply packages/block-library/src/cover/edit/inspector-controls.js]: 🤦 sorry my bad

**Comment by fabiankaegy** [comment]
CleanShot 2025-07-21 at 12 40 10@2x

Looking at this more I think we should improve the way the poster image is handled here. I'd love to display it similar to the posts featured image where you get a preview of the poster and can then replace / remove it. 


https://github.com/user-attachments/assets/fb6a140a-084b-4f46-8318-9b5d90915846

**Comment by yogeshbhutkar** [comment]
I agree with this, @fabiankaegy. The current UI for previewing poster images definitely needs some iteration. That said, this has also been the case for the Video Block, where poster image support has existed for some time now.

In my opinion, this PR is simply adding poster image support in line with what's already available in the Video Block. With that in mind, I think it would make sense to handle the design enhancements for both blocks as part of a follow-up issue. What do you think?

**Comment by fabiankaegy** [comment]
@yogeshbhutkar Very good point! :) 

I hadn't realized that the video block uses the exact same control. 

In that case I'm happy with this  👍 :)

**Comment by fabiankaegy** [comment]
I just requested an additional final review from @t-hamano or @Mamaduka but from my end this is good to go

File: packages/block-library/src/cover/edit/inspector-controls.js [hunk 2]
```diff
@@ -35,6 +35,7 @@ import { COVER_MIN_HEIGHT, mediaPosition } from '../shared';
 import { unlock } from '../../lock-unlock';
 import { useToolsPanelDropdownMenuProps } from '../../utils/hooks';
 import { DEFAULT_MEDIA_SIZE_SLUG } from '../constants';
+import PosterImage from '../../video/poster-image';
```
Comment (t-hamano) [inline packages/block-library/src/cover/edit/inspector-controls.js]: Let's avoid directly referencing components from other blocks. For example, if someone changes the code of the `PosterImage` component to improve the Video block, they won't know that the changes in this component will also affect the Cover block. If we want to share a component, we should extract it to the `block-library/src/utils` directory. Refer to [the `Caption` component](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/utils/caption.js).

Personally, since there isn't that much code, I prefer to copy the code into the Cover block rather than commonizing it.

File: packages/block-library/src/cover/edit/inspector-controls.js [hunk 3]
```diff
@@ -198,6 +201,7 @@ export default function CoverInspectorControls( {
 								focalPoint: undefined,
 								isRepeated: false,
 								alt: '',
+								poster: '',
```
Comment (t-hamano) [inline packages/block-library/src/cover/edit/inspector-controls.js]:
```suggestion
								poster: undefined,
```

I think this value should be `undefined`, otherwise the `poster` attribute with an empty value remains when resetting: 

image

File: packages/block-library/src/cover/edit/inspector-controls.js [hunk 4]
```diff
@@ -243,6 +247,13 @@ export default function CoverInspectorControls( {
 								</ToolsPanelItem>
 							</>
 						) }
+						{ isVideoBackground && (
+							<PosterImage
+								poster={ poster }
+								setAttributes={ setAttributes }
+								instanceId={ instanceId }
```
Comment (t-hamano) [inline packages/block-library/src/cover/edit/inspector-controls.js]: If we share a `PosterImage` component with multiple blocks, I think the `instanceId` should be generated within the `PosterImage`; otherwise, there is a risk of duplicate IDs.

File: packages/block-library/src/cover/save.js [hunk 5]
```diff
@@ -137,6 +138,7 @@ export default function save( { attributes } ) {
 					loop
 					playsInline
 					src={ url }
+					poster={ poster }
```
Comment (t-hamano) [inline packages/block-library/src/cover/save.js:141]: It's probably OK, but since we are updating the save feature, so follow these steps to confirm the Cover block does not break.

1. Check out the trunk branch
2. Create Cover blocks with various variations
3. Save the post.
4. Check out this branch
5. Reload your browser

**Comment by t-hamano** [comment]
> I think we should improve the way the poster image is handled here. I'd love to display it similar to the posts featured image where you get a preview of the poster and can then replace / remove it.

I agree. The current `PosterImage` UI makes it difficult to preview poster images. We may be able to try to improve it with a separate PR.

File: packages/block-library/src/cover/edit/inspector-controls.js (hunk 2 above)
Comment (Mamaduka) [reply packages/block-library/src/cover/edit/inspector-controls.js]: +1. Duplication over early abstraction.

**Comment by Mamaduka** [comment]
> I think we should improve the way the poster image is handled here. I'd love to display it similar to the posts featured image where you get a preview of the poster and can then replace / remove it.

+1. Makes sense as a follow-up.

File: packages/block-library/src/cover/edit/poster-image.js [hunk 6]
```diff
@@ -0,0 +1,89 @@
...
+import { __, sprintf } from '@wordpress/i18n';
+import { useRef } from '@wordpress/element';
+import { useInstanceId } from '@wordpress/compose';
+
+const COVER_POSTER_ALLOWED_MEDIA_TYPES = [ 'image' ];
+
+function PosterImage( { poster, setAttributes } ) {
+	const posterImageButton = useRef();
+	const instanceId = useInstanceId( PosterImage );
+	const videoPosterDescription = `cover-block__poster-image-description-${ instanceId }`;
```
Comment (Mamaduka) [inline packages/block-library/src/cover/edit/poster-image.js]:
```suggestion
	const descriptionId = useInstanceId( PosterImage, 'cover-block__poster-image-description' );
```

Suggestion: The `useInstanceId` hook accepts a second `prefix` parameter. Removes the need for manual string contact.

There's nothing wrong with the current versions, which is why we don't refactor similar instances. Just something to keep in mind for the new code.

File: packages/block-library/src/cover/edit/poster-image.js [hunk 7]
```diff
@@ -0,0 +1,89 @@
...
+	__experimentalToolsPanelItem as ToolsPanelItem,
+} from '@wordpress/components';
+import { __, sprintf } from '@wordpress/i18n';
+import { useRef } from '@wordpress/element';
+import { useInstanceId } from '@wordpress/compose';
+
+const COVER_POSTER_ALLOWED_MEDIA_TYPES = [ 'image' ];
+
+function PosterImage( { poster, setAttributes } ) {
+	const posterImageButton = useRef();
```
Comment (Mamaduka) [inline packages/block-library/src/cover/edit/poster-image.js]:
```suggestion
	const posterButtonRef = useRef();
```

Suggestion: The new standard is to use `Ref` suffix to avoid React Compiler errors in the future. See #64718.

File: packages/block-library/src/cover/save.js (hunk 5 above)
Comment (yogeshbhutkar) [reply packages/block-library/src/cover/save.js:141]: I've verified with multiple combinations that the steps above neither lead to a block validation error nor cause abnormal logging within the console.

Edit: I'd also encourage others to test this to be on the safe side, but I'd expect it to work just fine.

File: packages/block-library/src/cover/edit/poster-image.js (hunk 6 above)
Comment (yogeshbhutkar) [reply packages/block-library/src/cover/edit/poster-image.js]: Thanks for pointing this out. Looks like I missed this 🤦‍♂️

I'd still like to refactor as it looks much cleaner.

File: packages/block-library/src/cover/edit/poster-image.js [hunk 8]
```diff
@@ -0,0 +1,91 @@
...
+	return (
+		<ToolsPanelItem
+			label={ __( 'Poster image' ) }
+			isShownByDefault
+			hasValue={ () => !! poster }
+			onDeselect={ () => {
+				setAttributes( { poster: undefined } );
+			} }
+		>
+			<MediaUploadCheck>
```
Comment (Mamaduka) [inline packages/block-library/src/cover/edit/poster-image.js]: I was cross-checking the Video block and realized that `MediaUploadCheck` isn't placed correctly. It needs to wrap `ToolsPanelItem`.

Here's the fix for the video block - #70830.

Comment (yogeshbhutkar) [reply packages/block-library/src/cover/edit/poster-image.js]: Makes sense!

**Review by Mamaduka — APPROVED** [review]
Thanks for working on this, @yogeshbhutkar!

The new poster image control works as expected, and I couldn't identify any regressions when testing the previous block markup.

A small note: Maybe we should place a new control below the 'Focal point' picker. IMO, seems less distracting and secondary with this order. @fabiankaegy, @t-hamano, what do you think?

## Screenshot
CleanShot 2025-07-22 at 12 35 28

File: packages/block-library/src/cover/edit/poster-image.js [hunk 9]
```diff
@@ -0,0 +1,91 @@
...
+					<p id={ descriptionId } hidden>
+						{ poster
+							? sprintf(
+									/* translators: %s: poster image URL. */
+									__( 'The current poster image url is %s' ),
+									poster
+							  )
+							: __(
+									'There is no poster image currently selected'
+							  ) }
```
Comment (t-hamano) [inline packages/block-library/src/cover/edit/poster-image.js]:
```suggestion
							? sprintf(
									/* translators: %s: poster image URL. */
									__( 'The current poster image url is %s.' ),
									poster
							  )
							: __(
									'There is no poster image currently selected.'
							  ) }
```

**Review by t-hamano — APPROVED** [review]
> Maybe we should place a new control below the 'Focal point' picker. IMO, seems less distracting and secondary with this order.

+1 👍

As a follow-up, it would be great to improve the `PosterImage` component of the Video block based on this feedback as well (Correctly place the `MediaUploadCheck`, use `ref` suffix, etc.).

**Comment by Mamaduka** [comment]
> As a follow-up, it would be great to improve the PosterImage component of the Video block based on this feedback as well (Correctly place the MediaUploadCheck, use ref suffix, etc.).

We got that covered in https://github.com/WordPress/gutenberg/pull/70830.

**Review by Mamaduka — APPROVED** [review]

**Comment by yogeshbhutkar** [comment]
The `MediaUpload` component supports pre-selecting images via attachment IDs, but this isn’t currently implemented. To enable this, we may need to introduce a `posterId` attribute in the `block.json` for the Video and Cover blocks.

I would like to know your thoughts on whether this is a viable approach and if it requires a follow-up.

**Comment by Mamaduka** [comment]
>  The MediaUpload component supports pre-selecting images via attachment IDs, but this isn’t currently implemented. To enable this, we may need to introduce a posterId attribute in the block.json for the Video and Cover blocks.

I've not seen any reports requesting the fix for it. While a nice QoL improvement, it doesn't seem to be a significant issue for users. I would say it's a very low priority.
