### PR TITLE
Fixed meta box configuration persistence to be per postType as in the classic editor.

### LINKED ISSUE #5512: Reordering meta boxes for Custom Post Types does not persist correctly
## Issue Overview

When reordering meta boxes (with drag and drop) on the edit page for a Custom Post Type, the new order of the meta boxes does not persist properly. In fact, they are persisted in the user meta `meta-box-order_post` instead of `meta-box-order_{post-type}`.

## Steps to Reproduce (for bugs)

1. Create or edit a post of a Custom Post Type with metaboxes using Gutenberg.
2. Reorder the metaboxes by dragging and dropping.
3. Check the `meta-box-order_{post-type}` user meta. The reordering information is not there.
4. Check the `meta-box-order_{post-type}` user meta. The reordering information is there.
5. Edit the post in the classic editor. The metaboxes will not be ordered as desired.

## Expected Behavior

I expect Gutenberg and the Classic editor to use the same user meta for storing the metabox ordering.

## Current Behavior

Although it appears to work when using only Gutenberg, the ordering is stored in the incorrect user meta, and thus it doesn't work when switching to the classic editor, and vice versa.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Fixes: https://github.com/WordPress/gutenberg/issues/5512

We were calling window.postboxes.add_postbox_toggles with a fixed post type of 'post'. Now we call with the correct post type we are editing.
To do that, the post type was added to INITIALIZE_META_BOX_STATE action so our effects can correctly call add_postbox_toggles.

## How Has This Been Tested?
Have at least 2 meta boxes (I used "Open Graph Metabox" and "Yoast SEO" plugins in my tests).
Open a post and change the order/collapsed state of the meta boxes.
Open a different post type and verify the last changes to meta box state don't affect this post type. I
In the CPT change the meta box state and verify the changes are persisted.
Verify that the classic editor shows exactly the same meta box ordering and collapsing state as Gutenberg and changes in the classic editor for posts and CPT's are reflected in Gutenberg and changes in Gutenberg are reflected in the classic editor.

### CODE REVIEW

File: edit-post/store/effects.js [hunk 1]
```diff
@@ -27,7 +27,7 @@ const effects = {
 		}
 
 		// Allow toggling metaboxes panels
-		window.postboxes.add_postbox_toggles( 'post' );
+		window.postboxes.add_postbox_toggles( action.postType );
```
Comment (aduth) [inline edit-post/store/effects.js]: Is `getCurrentPostType( store.getState() )` not an option?

Comment (jorgefilipecosta) [reply edit-post/store/effects.js]: Unfortunately no, getCurrentPostType is a selector from the editor store, here we are in the edit-post store and there is no information in this store referring postType.

Comment (youknowriad) [reply edit-post/store/effects.js]: I guess we can use `wp.data.select( 'core/editor' ).getCurrentPostType()` :)

Comment (jorgefilipecosta) [reply edit-post/store/effects.js]: Yes, we can do that, the code was updated. I had some fears that the initialization of the postType core/editor was after edit/post but that was not the case.

**Review by youknowriad — APPROVED** [review]
LGTM 👍
