### PR TITLE
Remove words count in the multi-selection inspector

### LINKED ISSUE #67610: Words count in the multi-selection inspector doesn't work with bound content
### Description

When two or more blocks are selected, the block inspector shows the amount of selected blocks and the selected words count.

When one of more of the selected blocks content is bound to a source, the words count still counts the words in the original content (the block markup) while visually the rendered content comes from the bound source, which likely contains a different amount of words.

While i do understand why this occurs, from an user perspective this looks just broken and confusing. Here's a couple of example screenshots:

Image

I wonder whether the words count adds great value in the first place. To my understanding it is only used when there is a multi-block selection. Is this information actually useful for users?

If the prevalent opinion is to keep the word count, then I would say that it should either work correctly for bound content or it should be disabled when a block has bound content.

Cc @WordPress/gutenberg-design @artemiomorales 

### Step-by-step reproduction instructions

- Have a bound source that provides a text string to be used for connected content attribute of a paragraph block. You can qui8cly add this to your theme's functions.php

```
add_action( 'init', 'test_block_bindings' );

function test_block_bindings() {
	register_meta(
		'post',
		'text_short',
		array(
			'show_in_rest'      => true,
			'single'            => true,
			'type'              => 'string',
			'sanitize_callback' => 'wp_strip_all_tags',
			'default'           => 'Text from the bound source',
		)
	);
}
```

- Create a post with two paragraphs and add only one word to each paragraph.
- Select the first Paragraph, and bount its content to the registered source from the block settings panel > Attributes.
- Select both paragraphs.
- Observe the block inspector shows the word count.
- Observe the words count is `2 words`.
- Observe the visible selected words are more than two.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Resolves: https://github.com/WordPress/gutenberg/issues/67610

## Why?

When two or more blocks are selected, the block inspector shows the amount of selected blocks and the selected words count.

The specific words counts doesn't work properly right now and doesn't provide much value. Additionally given the alternative to properly check the cases with block bindings and controlled blocks is too much work with not much value, this PR removes that.

> When one of more of the selected blocks content is bound to a source, the words count still counts the words in the original content (the block markup) while visually the rendered content comes from the bound source, which likely contains a different amount of words.

## Testing Instructions
1. Select multiple blocks and observe that the words is not shown in the inspector controls card.

### CODE REVIEW

File: packages/block-editor/src/components/multi-selection-inspector/index.js [hunk 1]
```diff
@@ -20,27 +19,20 @@ export default function MultiSelectionInspector() {
 			blocks: getMultiSelectedBlocks(),
```
Comment (Mamaduka) [inline packages/block-editor/src/components/multi-selection-inspector/index.js]:
```suggestion
			count: getSelectedBlockCount(),
```

The component only needs a selected block count for rendering.

**Review by Mamaduka — APPROVED** [review]
Thanks, Nik!

Removal makes sense for me ✅

File: packages/block-editor/src/components/multi-selection-inspector/index.js (hunk 1 above)
Comment (ntsekouras) [reply packages/block-editor/src/components/multi-selection-inspector/index.js]: Yeah, it's better that way. Thanks!
