### PR TITLE
 Fix Gutenberg editor link 

### LINKED ISSUE #3666: Fix "Add New" link in Posts editor
Using the latest version of Gutenberg, when you're in Posts screen and there's a dropdown for Gutenberg/Classic Editor, which has a unnecessary question mark in the Gutenberg URL instead of /wp-admin/post-new.php, this /wp-admin/post-new.php?

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Remove the unnecessary question mark from the Gutenberg URL. Fixes #3666

### CODE REVIEW

File: gutenberg.php [hunk 1]
```diff
@@ -495,7 +495,7 @@ function gutenberg_replace_default_add_new_button() {
 			}
 
 			var url = button.href;
-			var newUrl = url.replace( /&?classic-editor/, '' );
+			var newUrl = url.replace( /&?\?classic-editor/, '' );
```
Comment (aduth) [inline gutenberg.php]: This regular expression assumes it must match a question mark. We should do one of two things:

- If it really must match question mark, remove `&` since we're not expecting a sequence of `&?`
- Make question mark optional

Maybe: `/[&\?]?classic-editor/`

https://regex101.com/r/SP3owo/1

**Review by aduth — CHANGES_REQUESTED** [review]

**Comment by HardeepAsrani** [comment]
@aduth Hope it's better now. Thank you for the review. It makes more sense to make it fool proof. :)

**Review by aduth — APPROVED** [review]
Looks good! 👍
