### PR TITLE
Run `wp.oldEditor.removep()` when transforming shortcodes

### LINKED ISSUE #3900: 1.8.1: Gutenberg breaks "classic" posts w/ shortcodes by carelessly wrapping shortcodes into <p> tags
## Issue Overview
It is not safe to open classic posts in Gutenberg, shortcodes get unexpectedly wrapped in `<p>` tags.

## Steps to Reproduce (for bugs)

1. Author a new post in classic editor w/ this example content

```
<h2>Shinier than yours, meatbag.</h2>

You can crush me but you can't crush my spirit! Is today's hectic lifestyle making you tense and impatient? It's a T. It goes "tuh". I'll tell them you went down prying the wedding ring off his cold, dead finger.

[column]

I daresay that Fry has discovered the smelliest object in the known universe! For the last time, I don't like lilacs! Your 'first' wife was the one who liked lilacs! No argument here. A true inspiration for the children.

[/column]

Hello world.
```

2. Open this post in Gutenberg
3. Switch to Code Editor mode to review transformed markup

## Expected Behavior

I'm not sure what the latest transformation goal for classic posts is. `<!-- wp:freeform -->` seems to be gone? Is #2454 relevant to the issue at hand?

## Current Behavior

I see the following transformation in Code Editor, which I consider broken for the shortcodes, since the result is broken rendering on the frontend:

```
<h2>Shinier than yours, meatbag.</h2>
<p>You can crush me but you can't crush my spirit! Is today's hectic lifestyle making you tense and impatient? It's a T. It goes "tuh". I'll tell them you went down prying the wedding ring off his cold, dead finger.</p>
<p>[column grid="2" span="1"]</p>
<p>I daresay that Fry has discovered the smelliest object in the known universe! For the last time, I don't like lilacs! Your 'first' wife was the one who liked lilacs! No argument here. A true inspiration for the children.</p>
<p>[/column]</p>
<p>[column grid="2" span="1"]</p>
<p>Hello world.</p>
<p>[/column]</p>
```

## Possible Solution

Not sure, could use pointers. What instructions should I provide users to avoid insta-breaking all classic content saved in Gutenberg?

## Screenshots / Video

N/A

## Related Issues and/or PRs

Not sure, could use pointers.

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by danielbachhuber**
## Description

Multi-line shortcodes transformed to Shortcode Blocks end up with `<p>`
in awkward places. Thanks to @pento's quick thinking, we can use some
existing WordPress magic to solve the immediate problem without falling
into the deeper rabbit hole.

Fixes #3900

## How has this been tested?

1. Create a post in the Classic Editor with the following text:

```
[column]

I daresay that Fry has discovered the smelliest object in the known universe! For the last time, I don't like lilacs! Your 'first' wife was the one who liked lilacs! No argument here. A true inspiration for the children.

[/column]
```

2. Open the post in Gutenberg and click "Convert to Blocks"

3. You should see the shortcode converted into a Shortcode Block without paragraph tags:

image

The prior behavior looked like this:

image

## Types of changes

Bug fix.

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Review by aduth — DISMISSED** [review]
Can we use `removep` and `autop` from the `@wordpress/autop` package instead of relying on the global? (Should also then add `wp-autop` as a script dependency of the `wp-core-blocks` handle)

**Comment by danielbachhuber** [comment]
> Can we use `removep` and `autop` from the `@wordpress/autop` package instead of relying on the global?

Yep e81c6ab11

**Comment by pento** [comment]
I've added an extra check `removep()` when saving a single freeform block.

When Gutenberg saves a freeform block, it doesn't wrap it in the comment delimiters. When there's a single freeform block in the post, there's no way to tell that the post has been touched by Gutenberg, so Gutenberg needs to clean up after itself.

This should possible be a seperate PR, but let's make this one the "fix the two issues reported #3900" PR.

**Comment by danielbachhuber** [comment]
> This should possible be a seperate PR, but let's make this one the "fix the two issues reported #3900" PR.

@pento Could you clarify what you mean by this? Are we going down the path of landing this and also recreating unbalanced / broken paragraph tags on the inner content prior to rendering the shortcode?

**Comment by danielbachhuber** [comment]
@gziolo I'm not sure what's remaining on this. Do you know?

**Comment by pento** [comment]
I've turned `core/shortcode` into a dynamic block, so we can make sure it's correctly autop-ed when it's rendered.

Includes unit tests and such.

**Comment by pento** [comment]
Also, I rebased/force pushed this branch, to get the latest version of the server fixtures. 🙂

**Comment by danielbachhuber** [comment]
💯 I tested this locally and it works exactly as expected.

**Comment by danielbachhuber** [comment]
@WordPress/gutenberg-core This is ready for a final review/merge per https://github.com/WordPress/gutenberg/issues/3900#issuecomment-408108235 All issues are addressed.

**Review by pento — APPROVED** [review]
🎉

File: core-blocks/shortcode/index.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 /**
  * WordPress dependencies
  */
+import { removep, autop } from '@wordpress/autop';
```
Comment (aduth) [inline core-blocks/shortcode/index.js]: `core-blocks` does not have a dependency defined for `wp-autop`, so its existence is purely incidental and this could be prone to future breakage.

File: core-blocks/shortcode/index.js [hunk 2]
```diff
@@ -46,7 +47,7 @@ export const settings = {
 					text: {
 						type: 'string',
 						shortcode: ( attrs, { content } ) => {
-							return content;
+							return removep( autop( content ) );
```
Comment (aduth) [inline core-blocks/shortcode/index.js]: It's not evident why we're doing this. An inline code comment would have been appropriate.

File: editor/store/selectors.js [hunk 3]
```diff
@@ -1352,7 +1353,13 @@ export const getEditedPostContent = createSelector(
 			return edits.content;
 		}
 
-		return serialize( getBlocks( state ) );
+		const blocks = getBlocks( state );
+
+		if ( blocks.length === 1 && blocks[ 0 ].name === getUnknownTypeHandlerName() ) {
```
Comment (aduth) [inline editor/store/selectors.js]: It's not evident why we're doing this. An inline code comment would have been appropriate.

File: editor/store/selectors.js [hunk 4]
```diff
@@ -22,10 +22,11 @@ import createSelector from 'rememo';
 /**
  * WordPress dependencies
  */
-import { serialize, getBlockType, getBlockTypes, hasBlockSupport, hasChildBlocks } from '@wordpress/blocks';
+import { serialize, getBlockType, getBlockTypes, hasBlockSupport, hasChildBlocks, getUnknownTypeHandlerName } from '@wordpress/blocks';
 import { __ } from '@wordpress/i18n';
 import { moment } from '@wordpress/date';
 import deprecated from '@wordpress/deprecated';
+import { removep } from '@wordpress/autop';
```
Comment (aduth) [inline editor/store/selectors.js]: `editor` does not have a dependency defined for `wp-autop`, so its existence is purely incidental and this could be prone to future breakage.

File: phpunit/class-do-blocks-test.php [hunk 5]
```diff
@@ -22,4 +22,26 @@ function test_do_blocks_removes_comments() {
 
 		$this->assertEquals( $expected_html, $actual_html );
 	}
+
+	/**
+	 * Test that shortcode blocks get the same HTML as shortcodes in Classic content.
+	 */
+	function test_the_content() {
+		add_shortcode( 'someshortcode', array( $this, 'handle_shortcode' ) );
```
Comment (aduth) [inline phpunit/class-do-blocks-test.php]: I'm not as familiar with PHP testing, but should we be tearing down anything we create, i.e. a complementing `remove_shortcode`?

File: core-blocks/shortcode/index.php [hunk 6]
```diff
@@ -0,0 +1,29 @@
+<?php
+/**
+ * Server-side rendering of the `core/shortcode` block.
+ *
+ * @package gutenberg
+ */
+
+/**
+ * Performs wpautop() on the shortcode block content.
```
Comment (aduth) [inline core-blocks/shortcode/index.php]: Could be improved to explain _why_ we're `autop`-ing, not simply expressing that we are, which is already evident in the code itself.

Alternatively, it could be considered an implementation detail that the block's render applies autop, not necessarily appropriate for the callback function. In other words, this function should be documented along lines of "Renders the shortcode", and the implementation detail explained by an inline code comment.

**Comment by aduth** [comment]
None of my comments are blocking for Try Callout, but could be considered for further improvement.

**Comment by aduth** [comment]
Also noting that the `getEditedPostContent` selector is not the only place we serialize blocks ([search](https://github.com/WordPress/gutenberg/search?l=JavaScript&q=serialize)), but as implemented here is the only place where we adopt this behavior of applying autop to the freeform-only content. It's not clear to me whether this is a "good thing", but the inconsistency seems prone to future unintended consequences.
