### PR TITLE
Components: Mimic URLInput request abort on fetch

### LINKED ISSUE #8034: Components: Error when URLInput updates its suggestions
Related: #7566, https://github.com/WordPress/gutenberg/pull/7979#issuecomment-406021006

**Describe the bug**

When changing the URL of a button block and unselected the block, the block throws an unhandled error.

**To Reproduce**

1. Navigate to Posts > Add New
2. Insert a Button block
3. Insert a URL
4. Unselect the block
5. Observe block throws into error state

**Expected behavior**

No error occurs.

**Screenshots**

button-error

**Additional context**

I have a feeling this is related to the recent `api-fetch` refactor (#7566), changing from a [`jqXHR` type](http://api.jquery.com/jQuery.ajax/#jqXHR) (with `abort` function) to a `Promise` (from `fetch`) which has no cancellation.

Further, I think it's an issue that we're not ever unsetting `this.suggestionsRequest` when a request completes. There's no need to abort the request except when currently in-progress.

### PR DESCRIPTION
**Pull request by aduth**
Fixes #8034 

This pull request seeks to resolve an error which occurs when assigning the URL of a Button block. Notably, it replaces `Promise#abort` (which does not exist) with an equivalent implementation checking for the request reference in an array which is reset both on subsequent requests and unmounting (when previously we were calling `abort`).

**Testing instructions:**

Repeat testing instructions from #8034, ensuring there are no errors.

### CODE REVIEW

File: editor/components/url-input/index.js [hunk 1]
```diff
@@ -25,18 +25,41 @@ const stopEventPropagation = ( event ) => event.stopPropagation();
...
+		const { showSuggestions, selectedSuggestion } = this.state;
+		// only have to worry about scrolling selected suggestion into view
+		// when already expanded
+		if ( showSuggestions && selectedSuggestion !== null && ! this.scrollingIntoView ) {
+			this.scrollingIntoView = true;
+			scrollIntoView( this.suggestionNodes[ selectedSuggestion ], this.listNode, {
+				onlyScrollIfNeeded: true,
+			} );
+
+			setTimeout( () => {
```
Comment (youknowriad) [inline editor/components/url-input/index.js]: Unrelated, we should probably replace this with `withSafeTimeout` :)

**Review by youknowriad — APPROVED** [review]
LGTM 👍

File: editor/components/url-input/index.js (hunk 1 above)
Comment (aduth) [reply editor/components/url-input/index.js]: We should probably not have `setTimeout` of any form 😉
