### PR TITLE
Prevent Pre-Publish Panel from Displaying Incorrect Information After Navigating away

### LINKED ISSUE #64913: Pre-publish checks showing template part details
This is a very obscure bug; if you open the pre-publish checks, then switch immediately to edit a template part, the pre-publish panel will show broken/incorrect information about the template part. Here's a video:

https://github.com/user-attachments/assets/7caeacf8-662f-4396-a381-82916995d518

### To re-produce

1. Edit a draft page
2. Ensure pre-publish checks are enabled in editor preferences
3. Ensure template preview is toggled on so you can select the header or footer
4. Select the header (or footer) then click 'Edit' in the block toolbar
5. Notice the pre-publish panel contents update to reflect the template part

### What I'd expect

By navigating away from editing the page I'd consider the publish flow interrupted. Consequently I'd expect the pre-publish panel to close.

### PR DESCRIPTION
**Pull request by sarthaknagoshe2002**
Fixes: #64913 

## What?
This PR addresses a bug highlighted in #64913 where the pre-publish panel displays incorrect or broken information when switching to edit a template part. Specifically, if you open the pre-publish checks and immediately switch to edit a template part, the panel continues to show details about the template part, instead of closing or updating appropriately.

## Why?
This fix improves the user experience by preventing confusion caused by incorrect information in the pre-publish panel. It ensures the behavior aligns with expectations, where the pre-publish is closed when navigating away.

## How?
The issue is resolved by ensuring that when the user navigates away from editing the page, the pre-publish panel is closed. This change ensures that the publish flow is not interrupted and the pre-publish checks are only shown for the current page or post, not the template part.

## Testing Instructions

1. Open a draft page in the editor
2. Ensure pre-publish checks are enabled
3. Click on `publish` to open the pre-publish panel
4. Select the header then click 'Edit' in the block toolbar
5. Now the pre-publish panel closes when navigating away

## Screenshots or screencast 

https://github.com/user-attachments/assets/f750d1c9-9138-474a-87f3-696e5d2801dd

### CODE REVIEW

File: packages/editor/src/components/post-publish-panel/index.js [hunk 1]
```diff
@@ -47,9 +47,10 @@ export class PostPublishPanel extends Component {
 		// Automatically collapse the publish sidebar when a post
 		// is published and the user makes an edit.
 		if (
-			prevProps.isPublished &&
-			! this.props.isSaving &&
-			this.props.isDirty
+			( prevProps.isPublished &&
+				! this.props.isSaving &&
+				this.props.isDirty ) ||
+			! this.props.postlink
```
Comment (ntsekouras) [inline packages/editor/src/components/post-publish-panel/index.js]: I think a better check would be to see if the currentPostId changed: `this.props.currentPostId !== prevProps.currentPostId`, where `currentPostId` is `select(editorStore).getCurrentPostId()`.

Comment (sarthaknagoshe2002) [reply packages/editor/src/components/post-publish-panel/index.js]: Hey @ntsekouras, thanks for suggesting a better approach!
I have implemented the suggested changes, please have a look.

Thanks 🙌🏻

Comment (ntsekouras) [reply packages/editor/src/components/post-publish-panel/index.js]: Thank you! Let's use `getCurrentPostId` selector though instead of `getEditedPostAttribute( 'id' )` and name the prop `currentPostId` for clarity.

Comment (sarthaknagoshe2002) [reply packages/editor/src/components/post-publish-panel/index.js]: @ntsekouras I have implemented the changes!
Also, can you highlight on why using `getCurrentPostId ` is a better approach?

Thanks 🙌🏻

Comment (ntsekouras) [reply packages/editor/src/components/post-publish-panel/index.js]: Sure. Since we only want the `id`, `getCurrentPostId` returns that directly from the state whereas `getEditedPostAttribute` is a doing more and we don't need to fetch all the edits etc..

**Review by ntsekouras — APPROVED** [review]
LGTM, thank you! Mobile tests have an issue in general now, so let's see if they are resolved soon and try to rebase and land.

File: packages/editor/src/components/post-publish-panel/index.js (hunk 1 above)
Comment (sarthaknagoshe2002) [reply packages/editor/src/components/post-publish-panel/index.js]: @ntsekouras okay understood!
Is this PR now ready to be approved or does this need anymore changes?
