### PR TITLE
Fix e2e tests related to template parts

### LINKED ISSUE #25919: Fix skipped template-part e2e test.
An test in the experimental section was skipped (#25918) after a component it relied upon was removed and the change was merged into the master branch.

Now lets fix the test and un-skip it 😁

### PR DESCRIPTION
**Pull request by noahtallen**
**Note: There are still other e2e tests failing. This just fixes the most immediate issues. I haven't been able to track down solid fixes for the others quite yet.**

## Description
A few e2e tests are failing in master. The issue (I think) is that the text of a button is "Template Part", but the test queries for an xpath with text "Template part".

Additionally, there was an issue where the new nav sidebar did not display demo template parts, because it was querying for template parts associated only with the current theme.

This also reverts the previous attempt to skip failing tests in #25918.

Closes #25919

## How has this been tested?
e2e tests should not report issues with template parts in this PR.

## Types of changes
Bug fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/edit-site/src/components/left-sidebar/navigation-panel/menus/template-parts.js [hunk 1]
```diff
@@ -15,13 +15,10 @@ import TemplateNavigationItems from '../template-navigation-items';
 
 export default function TemplatePartsMenu( { onActivateItem } ) {
 	const templateParts = useSelect( ( select ) => {
-		const currentTheme = select( 'core' ).getCurrentTheme()?.textdomain;
```
Comment (noahtallen) [inline packages/edit-site/src/components/left-sidebar/navigation-panel/menus/template-parts.js:18]: Note: this prevented demo template parts from showing up in the sidebar, so we'll need to find a better way to handle thhis.

**Review by Addison-Stavlo — APPROVED** [review]
This looks and works well for me regarding fixing the tests failing regarding the site editor.  The other failing tests are unrelated, but will also need to be addressed.

File: packages/edit-site/src/components/left-sidebar/navigation-panel/menus/template-parts.js (hunk 1 above)
Comment (mcsf) [reply packages/edit-site/src/components/left-sidebar/navigation-panel/menus/template-parts.js:18]: Why use the `textdomain` property of the theme? I was trying to find a semantic reason for preferring this property over `stylesheet`, but I don't see one. Looking at the use of `currentTheme` it seems to be used as the canonical theme identifier, which normally would be the theme's `stylesheet` property.

Practically speaking, `textdomain` isn't required to match `stylesheet` and — although the field is required by the Theme Repository — omitting it doesn't break the theme.

Also cc @Addison-Stavlo for the use of `textdomain` in #23254

Comment (Addison-Stavlo) [reply packages/edit-site/src/components/left-sidebar/navigation-panel/menus/template-parts.js:18]: @mcsf Interesting, thanks for letting us know!  I thought of it as the identifier but did not realize it could be omitted.  I'l update these to use stylesheet.  I also noticed that global styles is using the `textdomain` field as well, but it may be for a different reason? https://github.com/WordPress/gutenberg/blob/270975190b5e539dc291be73749af3fb7e557c42/lib/global-styles.php#L144

Comment (Addison-Stavlo) [reply packages/edit-site/src/components/left-sidebar/navigation-panel/menus/template-parts.js:18]: https://github.com/WordPress/gutenberg/pull/25995

Comment (nosolosw) [reply packages/edit-site/src/components/left-sidebar/navigation-panel/menus/template-parts.js:18]: For context: IIRC, global styles used text domain because that was what FSE was using at the time + the thought was that it was the canonical identifier of the theme. In looking at this, I learned that it's not and that the `stylesheet` field that Miguel recommends using is what WordPress core uses instead when it wants a unique identifier ([example](https://github.com/WordPress/gutenberg/pull/26061)).

It looks like there are use cases in which the text-domain is not necessary (child themes that don't add any new string, themes not distributed through the WP repository) so any code that uses it as theme identifier can potentially break. Created a PR to fix `lib/global-styles.php` at https://github.com/WordPress/gutenberg/pull/26061

Would you follow suit and migrate FSE to use `stylesheet` as the new affix for the identifier? Do we need an issue to track this? I'm happy to help, but also have no experience with FSE so can miss tons of contexts as to what things may break by changing the identifier.
