### PR TITLE
Env: Download WordPress PHPUnit Into Container

### LINKED ISSUE #23171: Env: wp-phpunit not in sync with mapped WordPress version
**Describe the bug**
A few days ago, we noticed phpunit failures in Travis. This was because a change was merged to wordpress core which was propagated to wp-env. Unfortunately, wp-phpunit (the dep we use to install wp phpunit test lib) is pinned at the test code in the last WP version, so the same changes did not propogate to it.

Essentially, the WordPress version running on the wp-env container is _not in sync_ with the version the wp-phpunit test lib expects. 

Link to discussion in make WordPress slack (requires signup): https://wordpress.slack.com/archives/C02QB2JS7/p1591979580086000

**Solution**

The solution we have discussed (cc @TimothyBJacobs, @joemcgill) is to do something like this:
1. Detect the current WordPress version. If wordpress-develop, bail since the test lib is already mapped.
2. Use that WordPress version to generate a ref to wordpress-develop `svn` which contains the test-lib in sync with the current WP source code. (We can use [wp-cli as a basis for this code](https://github.com/wp-cli/scaffold-command/blob/master/templates/install-wp-tests.sh).)
3. Download `tests/phpunit/includes` and `tests/phpunit/data` (either inside the docker image or in `~/.wp-env/$hash/`)
4. Map those to the correct location in the phpunit Docker service.
5. Make sure that the phpunit tests reference this code for the test lib.

One benefit of this approach is that no one will have to worry about installing a wp-phpunit dep, which makes phpunit much more accessable in wp-env.

### PR DESCRIPTION
**Pull request by ObliviousHarmony**
## What?

This pull request downloads the WordPress PHPUnit test files into the `wordpress` and `tests-wordpress` container. This closes #23171.

## Why?

Currently, the best option we have for installing the WordPress PHPUnit test library is using `wp-phpunit/wp-phpunit`. This is not a _bad_ solution, however, it comes with a few problems:

* If you select a version of WordPress that is incompatible with the installed version of `wp-phpunit/wp-phpunit` your tests will fail.
* There is no option to download the current _trunk_ test files. This can lead to problems when trying to test against the next version of WordPress.

Since we know what version of WordPress the environment contains, a better solution would be to just download it and mount it in the container.

## How?

This pull request works by scanning `~/.wp-env/{hash}/{coreSource}/wp-includes/version.php` for the current WordPress version. An alternative that was considered was using `wp core version`, but, I wanted to find a solution that could give us the version to include the library in the docker-compose file.

We can then use this information to figure out what version of the WordPress PHPUnit library to install. We store it in the `~/.wp-env/{hash}/` directory and mount it at `/phpunit` in the container. To get around the need for anything other than `git`, we download from [WordPress/wordpress-develop](https://github.com/WordPress/wordpress-develop). It mirrors from SVN so we can rely on `master` being the bleeding edge and the tags containing WordPress versions. We're also using a sparse checkout to prevent having the _entire_ `WordPress/wordpress-develop` repository checked out.

Lastly, in order to use it in unit tests, we copy the `wp-config.php` file and set the required constants. Once we create the containers with the `WP_PHPUNIT__DIR` we can now run unit tests without `wp-phpunit/wp-phpunit`

**Note: I looked at removing `wp-phpunit/wp-phpunit` but it felt out of scope for this PR. It requires changes to the test suite to properly use `Yoast/PHPUnit-Polyfills`.**

## Testing Instructions

This is tricky to test, unfortunately. We're going to have to remove `wp-phpunit/wp-phpunit`. The tests won't pass unless you do the legwork, but, just removing it can let you see that the test suite boots up. That is really all you need to know this in particular works.

1. Run `composer remove wp-phpunit/wp-phpunit --dev` to get rid of `wp-phpunit/wp-phpunit`. In theory, the PHPUnit tests should now not even be able to boot.
2. Run `npm run wp-env run tests-wordpress "/var/www/html/wp-content/plugins/gutenberg/vendor/bin/phpunit -c /var/www/html/wp-content/plugins/gutenberg/phpunit.xml.dist --verbose"`
3. Note that the PHPUnit suite boots up and loads WordPress but fails because of `wp-phpunit/wp-phpunit` failures.
4. Poke around `~/.wp-env/{hash}` and check out the `WordPress-PHPUnit` and `tests-WordPress-PHPUnit` directories. They should contain all of the test files with a sparse checkout.
5. Use the `WP_ENV_CORE` environment variable to try out a few different options for WordPress installs. A local one, a zip, a git repository, etc. Verify that the correct version of the PHPUnit library is installed in each case.

I have prepared https://github.com/WordPress/gutenberg/pull/41852 with all of the commits from this pull request. It makes the appropriate changes for the Gutenberg PHPUnit tests to be ran in `wp-env`. The PHPUnit test workflow in that pull request uses the provided test files. That pull request passing is a demonstration of this working in CI.

### CODE REVIEW

**Comment by ObliviousHarmony** [comment]
One potential optimization for the git checkout could be to add a remote to an empty repository instead of cloning. This would mean nothing is downloaded that we don't want. I think we could fetch the specific tag or branch and then do the sparse checkout. I'm actually not completely sure if the sparse checkout saves us anything as-is, but it felt nice to empty the directory haha.

With that said, as far as I can tell, performance isn't really an issue. It's just a thought though. I think the depth of 1 already aggressively optimizes what we're cloning in the first place, but, I can take another pass at the download next week if we want to try and bleed whatever performance out that we can.

**Comment by ObliviousHarmony** [comment]
I went ahead with the performance optimization anyway. It should now only be downloading the latest files for the test library. It's a bit faster and the fact that the tests and development files are downloaded in parallel helps too!

**Comment by ObliviousHarmony** [comment]
As I was working on this I noticed that the test config doesn't have a different table prefix. I wasn't sure if it mattered at the time, but now, it feels like it should. Is there a good reason we shouldn't change the prefix so that unit tests don't truncate all of the tables?

**Comment by ObliviousHarmony** [comment]
I've opened [a PR making the appropriate changes for this to be used in Gutenberg](https://github.com/WordPress/gutenberg/pull/41852). That pull request includes the commits from this one, so, it should also be a demonstration of the functionality here.

**Comment by ndiego** [comment]
@ObliviousHarmony and @noahtallen the linked issue and this PR came up in today's Editor Bug Scrub. Just checking in to see what the status of this PR is and what needs to be done to get it across the line.

File: packages/env/test/build-docker-compose-config.js [hunk 1]
```diff
@@ -62,13 +65,20 @@ describe( 'buildDockerComposeConfig', () => {
...
+		let localSources = [
 			'/path/to/wp-plugins:/var/www/html/wp-content/plugins',
+			'/path/WordPress-PHPUnit/tests/phpunit:/wordpress-phpunit',
 			'/path/to/local/plugin:/var/www/html/wp-content/plugins/test-name',
 			'/path/to/local/theme:/var/www/html/wp-content/themes/test-theme',
 		];
-
 		expect( devVolumes ).toEqual( expect.arrayContaining( localSources ) );
+
+		localSources = [
```
Comment (noahtallen) [inline packages/env/test/build-docker-compose-config.js:76]: Nit: I'd just define this as a separate variable.

File: packages/env/lib/commands/start.js [hunk 2]
```diff
@@ -127,7 +129,25 @@ module.exports = async function start( { spinner, debug, update, xdebug } ) {
...
+		// Use the WordPress versions to download the PHPUnit suite.
+		const wpVersions = await Promise.all( [
+			readWordPressVersion(
+				config.env.development.coreSource,
+				spinner,
+				debug
+			),
+			readWordPressVersion( config.env.tests.coreSource, spinner, debug ),
+		] );
+		await downloadWPPHPUnit(
```
Comment (noahtallen) [inline packages/env/lib/commands/start.js:145]: Do we need to run this for every `wp-env` install? I wonder if we should instead have a top-level config option for including phpunit. That said, if this isn't causing any meaningful performance impact, we can probably leave it as is.

**Review by noahtallen — APPROVED** [review]
Nice, overall I think this is good to go! I think we can also remove the line which creates the old wp-phpunit-config.php file, as the new file does the same thing.

On this branch, after removing wp-phpunit from composer, `npm run test-unit-php` passes. As a result, it's using these changes successfully. This also works after removing the file I mentioned above.

So this change should be backwards compatible, which is a nice benefit :)

File: packages/env/lib/commands/start.js (hunk 2 above)
Comment (ObliviousHarmony) [reply packages/env/lib/commands/start.js:145]: I considered this initially but instead decided to heavily optimize the `develop` checkout. It _only_ downloads the `phpunit` files. I've also taken care to parallelize the download, so as far as performance goes, I've found this to be incredibly fast. It only downloads something like 21MB. For what it's worth, I'm pretty sure this is lighter than the `phpunit` container we're currently spinning up.

For me, this was a tradeoff between standardization and performance. Everyone who is using `wp-env` _should_ be writing unit tests. All of these tests will likely require the PHPUnit files, so, I didn't see any good reasons not to include them by default.

Comment (noahtallen) [reply packages/env/lib/commands/start.js:145]: That's a good reason. The easier we can make unit tests to use, the better.

**Comment by Mamaduka** [comment]
@noahtallen, is this good to merge?

**Comment by ObliviousHarmony** [comment]
No @Mamaduka, sorry, I need to check on something first. The PHP unit tests in this PR have a different output than `trunk`. There are risky tests now where there weren't, so, I think something about the test suite has changed and needs debugged.

File: packages/env/CHANGELOG.md [hunk 3]
```diff
@@ -2,6 +2,14 @@
 
 ## Unreleased
 
+### Breaking Changes
+-   Removed the `WP_PHPUNIT__TESTS_CONFIG` environment variable from the `phpunit` container. **This removes automatic support for `wp-phpunit/wp-phpunit`**.
```
Comment (noahtallen) [inline packages/env/CHANGELOG.md]: Could you add a line saying this is the composer package? I get confused about that sometimes. It might also be worth explicitly saying that this is replaced by the enhancement below.

File: packages/env/CHANGELOG.md [hunk 4]
```diff
@@ -2,6 +2,14 @@
...
+-   Removed the generated `/var/www/html/phpunit-wp-config.php` file from the environment.
+
+### Enhancement
+-   Read WordPress' version and include the correspond PHPUnit test files in the environment.
```
Comment (noahtallen) [inline packages/env/CHANGELOG.md]:
```suggestion
-   Read WordPress' version and include the corresponding PHPUnit test files in the environment.
```

File: packages/env/README.md [hunk 5]
```diff
@@ -188,6 +188,20 @@ wp-env start --debug
 	...
 ```
 
+## Using included WordPress PHPUnit test files
+
+Out of the box `wp-env` includes the [WordPress' PHPUnit test files](https://develop.svn.wordpress.org/trunk/tests/phpunit/) corresponding to the version of WordPress installed. There is an environment variable, `WP_TESTS_DIR`, which points to the location of these files within each container. By including these files in the environment, we remove the need for you to use a package or install and mount them yourself.
+
+### Custom `wp-tests-config.php` file
+
+WordPress provides a `WP_TESTS_CONFIG_FILE_PATH` constant that you can use to change the `wp-config.php` file used for testing. Set this to a desired path in your `bootstrap.php` file and the file you've chosen will be used instead of the one included in the environment.
```
Comment (noahtallen) [inline packages/env/README.md]: I might explicitly add that this is optional. Otherwise, I worry people will think they need to use this :P

File: packages/env/README.md [hunk 6]
```diff
@@ -188,6 +188,20 @@ wp-env start --debug
...
+
+### Using `wp-phpunit/wp-phpunit`
```
Comment (noahtallen) [inline packages/env/README.md]: Honestly, I don't know if we need to document this explicitly. I see the value of mentioning `WP_TESTS_DIR` and the bootstrap.php file, but I wonder if we really need to mention that wp-phpunit can still be used if our main goal is to discourage it in favor of the built-in solution

**Review by noahtallen — COMMENTED** [review]
Left some notes about the changelog and readme. I also want to test the upgrade path for other plugins, so I'll run this branch on a different plugin locally now!

File: packages/env/README.md (hunk 6 above)
Comment (ObliviousHarmony) [reply packages/env/README.md]: I guess it depends on whether or not you feel like we've explicitly supported the `wp-phpunit/wp-phpunit` use case. I suppose it's good to remove it, there are likely two kinds of users of the `wp-phpunit/wp-phpunit` package for us:

* Those who include the package but rely 100% on `wp-env` to bootstrap and use it. These would be unaffected by the change and it would be a silent transition.
* Those who include the package and support custom environments. These would be unaffected by the change since they need to set some of these variables in the first place. The one thing worth mentioning is the `WP_TESTS_DIR` bit.

With that in mind, I've gone ahead and removed the section and extracted the only useful bits.

**Comment by ObliviousHarmony** [comment]
Thanks for the feedback @noahtallen, I've gone ahead and made some changes to the changelog and documentation as requested.

**Review by noahtallen — APPROVED** [review]
Alright, I think this is good to go!
