### PR TITLE
Ensure block toolbar doesn't overlap block by modifying forcePosition and shift popover props

### LINKED ISSUE #41575: Block Toolbar Regression - Toolbar obstructs selected blocks.
When a block is near the top of the canvas and selected, the block toolbar obstructs the block.

We previously resolved this in https://github.com/WordPress/gutenberg/issues/29464 by moving the toolbar beneath the selected block IF there is no room in the editor canvas to position it above the block without selected block obstruction.

Some recent change has caused a regression in this behavior, trying to place the toolbar above the block regardless of available space. This causes the toolbar to float over the selected block, obstructing the user from interacting with that block or its children.

BEFORE REGRESSION:
Screen Shot 2022-06-07 at 8 29 41 AM

AFTER REGRESSION (current trunk branch):
Screen Shot 2022-06-07 at 8 31 55 AM

Either we need to:
* A: Re-add this conditional bottom-positioning behavior AND follow up to resolve the 1 edge case related to calculating the position when popover children are involved (i.e. navigation block submenus as reported here - [40382](https://github.com/WordPress/gutenberg/issues/40382), [36335](https://github.com/WordPress/gutenberg/issues/36335), [36977](https://github.com/WordPress/gutenberg/issues/36977))
* B:  add a background buffer space at the top of the editor canvas / above the template equal to the height needed for the block toolbar. (or do this until we can resolve the edge cases around the solution A)
* C: conditionally enable the "top toolbar" setting when a block at this position is selected. (or do this until we can resolve edge cases around solution A)
* D: other ideas?

The current state is extremely limiting and will not be acceptable to be in place for any extended period of time. Users are reporting inability to edit certain blocks near the top of the canvas, such as the main navigation block in their header.

image

cc @talldan @jasmussen @youknowriad @getdave @mtias

### PR DESCRIPTION
**Pull request by talldan**
## What?
Fixes #41575

Restores the previous behavior where the block toolbar flips below the block when there's not enough space at the top of the canvas.

## How?
Modifies the popover props on the fly. When there's enough space at the top of the canvas, the props `{ __unstableForcePosition: true, __unstableShift: true }` are used, disabling the toolbar 'flip' behavior and enabling the 'shift' behavior.

When there's a restricted amount of space, the props `{ __unstableForcePosition: false, __unstableShift: false }` are used, which enable the 'flip' behavior and disable the 'shift' behavior.

## Testing Instructions
1. Open the site editor, go to 'Templates' and choose Blank (which appears in the Twenty Twenty Two theme)
2. Insert some blocks, ideally enough for the page to be scrollable.
3. Select the first block—if there isn't enough space above the block it should appear below.

## Video

https://user-images.githubusercontent.com/677833/182343939-4d9987ae-97af-433f-bf4a-e71f7b1d94ac.mp4

### CODE REVIEW

**Comment by ciampo** [comment]
I'm a bit behind with my review queue at the moment, but I'll try to take a look soon enough!

File: packages/block-editor/src/components/block-popover/index.js [hunk 1]
```diff
@@ -53,7 +53,7 @@ export default function BlockPopover( {
 		<Popover
 			ref={ popoverScrollRef }
 			animate={ false }
-			position="top right left"
```
Comment (ciampo) [inline packages/block-editor/src/components/block-popover/index.js:56]: Out of curiosity, could you find any documentation re. the spec for the legacy `position` prop? The old [README](https://github.com/WordPress/gutenberg/pull/40740/files#diff-7a2068536fb5880fe5d63a404a6b957876f2791be9a6c9b32e3fa3a9f6d791dfL64) only shows strings composed by two values (e.g. `top left`), but there's no mention of what the third value does

**Review by ciampo — COMMENTED** [review]
I know that this is still a rough implementation and it's far from final code, but I stil gave this PR a try. The behavior is quite inconsistent:

- the toolbar is flipped also for blocks that shouldn't be flipped
- the "flip" doesn't always revert to the normal position 

https://user-images.githubusercontent.com/1083581/183051654-447e5547-b031-4424-9f8b-e9ce0dcdc61b.mp4

The main thing to discuss is the idea behind the approach:

> Passes a different `placement` to the `Popover` component depending on the amount of space at the top of the canvas. It does this in the `SelectedBlockPopover` component, which seems to be the one responsible for the floating block toolbar.
> 
> The good thing is that this doesn't touch the popover component, it works consistently in the post and site editors, and it doesn't completely prevent the `shift` behavior of the toolbar for blocks lower down in the canvas.

Personally I'm not sure about this approach — it's still potentially quite a lot of code with non-trivial logic (one we polish it), which can be error prone (and therefore not too different from a custom middleware).

**I'd like to rely on `floating-ui` as much as possible**, so here's another idea that came to mind:
- when a block is selected (or shifted across the document), we could still read  (outside of the `Popover` component) the distance of the selected block from the start of the page (and not of the viewport)
- if the distance if less than a certain threshold (which can be the toolbar's height or any arbitrary number), we could simply set a prop on `Popover` to enable the `flip` behavior

This would keep the block editor-specific code separate from Popover, but would also avoid writing any popover-specific code outside of the `Popover`.

File: packages/block-editor/src/components/block-popover/index.js (hunk 1 above)
Comment (talldan) [reply packages/block-editor/src/components/block-popover/index.js:56]: I don't know  what the third value does either, I think @ellatrix would be the person that knows the API best.

File: packages/components/src/popover/index.js [hunk 2]
```diff
@@ -328,7 +329,7 @@ const Popover = (
 		}
 
 		return autoUpdate( usedRef, refs.floating.current, update );
-	}, [ anchorRef, anchorRect, getAnchorRect ] );
+	}, [ anchorRef, anchorRect, getAnchorRect, middlewares ] );
```
Comment (talldan) [inline packages/components/src/popover/index.js:332]: This isn't a good idea, because it'll force `autoUpdate` on every render, but it seems we need a way to force `autoUpdate` to run if there's a change in middleware. Without it, the old middleware remains active.

Perhaps the middleware array should be memoized anyway.

**Comment by talldan** [comment]
@ciampo Sorry for the delay in replying, have been working across a few areas lately.

> if the distance if less than a certain threshold (which can be the toolbar's height or any arbitrary number), we could simply set a prop on Popover to enable the flip behavior

I've updated the code to work like this. I agree that it is nicer 👍 

I think it probably has the same problems to solve, that we'd need to update on block movement or resizing to determine the new props. That's still not an insurmountable problem, but I haven't attempted to solve it yet, just aiming for a proof of concept.

> the toolbar is flipped also for blocks that shouldn't be flipped
> the "flip" doesn't always revert to the normal position

I noticed something like this. There's the same problem with the new approach too. I think floating-ui may not support modifying placement or middleware on the fly. I had little success in calling floating-ui's `update` function to get it to recalculate, but I think this would be the right way to solve the problem.

To solve it for now, I've forced the popover to remount when a different block is selected - see d06ade5. I don't think this is a long term fix, but I've pushed it so that the PR demonstrates the desired behavior.

**Comment by ciampo** [comment]
> I think it probably has the same problems to solve, that we'd need to update on block movement or resizing to determine the new props. That's still not an insurmountable problem, but I haven't attempted to solve it yet, just aiming for a proof of concept.

Yeah, we should calculate the distance of the currently selected block from the top of the page (not the viewport):

- when the block is selected
- when the block is resized
- when the block is moved across the page (i.e. changed order)

> I noticed something like this. There's the same problem with the new approach too. I think floating-ui may not support modifying placement or middleware on the fly. I had little success in calling floating-ui's update function to get it to recalculate, but I think this would be the right way to solve the problem.
> To solve it for now, I've forced the popover to remount when a different block is selected - see https://github.com/WordPress/gutenberg/commit/d06ade5d35a1a462d932c5d28fd01542b10f0a3e. I don't think this is a long term fix, but I've pushed it so that the PR demonstrates the desired behavior.

That's unfortunate — it was also my impression that at most we'd need to call `update`. To be investigated (we may even open an issue on `floating-ui`'s repo if we believe it's an actual bug)

File: packages/components/src/popover/index.js (hunk 2 above)
Comment (ciampo) [inline packages/components/src/popover/index.js]: Interesting that this is also not enough to trigger an update of the popover behavior when changing its behavior through enabling/disabling middlewares

**Comment by talldan** [comment]
With the other popover fixes, this is working much better now. I've removed any hacks and tidied up the code.

Open to more feedback, testing and reviews now.

I haven't fixed the issue where the toolbar doesn't shift fully below the block in the site editor, but there are other PRs looking at that problem.

**Comment by ciampo** [comment]
Thanks Dan! I'll try to have a look soon at this

File: packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js [hunk 3]
```diff
@@ -0,0 +1,69 @@
+/**
+ * WordPress dependencies
+ */
+import { useEffect, useState } from '@wordpress/element';
+
+const TOOLBAR_HEIGHT = 72;
```
Comment (ciampo) [inline packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js]: We should try not to store hardcoded values like this one:

- we could either read it from the toolbar (probably the easiest alternative)
- or we could make it so that the value is originally stored in JS, and they applied to the toolbar (maybe via custom props)?

File: packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+const DEFAULT_PROPS = { __unstableForcePosition: true, __unstableShift: true };
+const RESTRICTED_HEIGHT_PROPS = {
+	__unstableForcePosition: false,
+	__unstableShift: false,
+};
```
Comment (ciampo) [inline packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js]: Let's add some comments here explaining the expected behaviour when setting these options (e.g with "restricted" mode, the toolbar won't shift when there's no space, but it will flip instead)

File: packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+ */
+export default function useBlockToolbarPopoverProps( {
+	contentElement,
+	selectedBlockElement,
+} ) {
+	const [ props, setProps ] = useState(
+		getProps( contentElement, selectedBlockElement )
+	);
+
+	useEffect( () => {
```
Comment (ciampo) [inline packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js]: Would using `useLayoutEffect` make any difference here?

**Review by ciampo — COMMENTED** [review]
Code looks much cleaner!

I think we will still need to listen to more events that can change the distance of the selected block from the toolbar.

For example, if a block is re-ordered, the toolbar currently doesn't adjust its position:

https://user-images.githubusercontent.com/1083581/185470898-ac822228-831f-4cdb-a6f5-46e66f5a0914.mp4

What if we undo an action that causes the block to change its distance from the top of the page (eg adding a block on top, and then cmd+z, which would remove it)?

I also checked multi-block selection and it seems to work

**Comment by talldan** [comment]
> For example, if a block is re-ordered, the toolbar currently doesn't adjust its position

I thought I'd solved that, but yes I see that issue. It seems to work ok when a block is moved down, but that's because `flip` remains active. It seems like there's still an issue switching from one set of middleware to another.

I'll look into it.

File: packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js (hunk 3 above)
Comment (talldan) [reply packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js]: Definitely. I've added some code that uses the popover's `offsetHeight`. 👍

File: packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js (hunk 4 above)
Comment (talldan) [reply packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js]: Agreed - I've improve the comments. 👍

File: packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js (hunk 5 above)
Comment (talldan) [reply packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js]: I don't seem to notice any difference. My take on it is that because the hook triggers a re-render, `useLayoutEffect` isn't needed, but I may be wrong.

**Comment by talldan** [comment]
I think I've covered most of the edge cases now, but more testing is welcome.

File: packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js (hunk 5 above)
Comment (ciampo) [reply packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js]: I believe it could be useful to `useLayoutEffect` because, compared to `useEffect`, it's guaranteed to run after React has performed DOM mutations.

Since we're performing measurements (`updateProps` causes some calls to `getBoundingClientRect`), that's why I thought it would be beneficial to use `useLayoutEffect` compared to `useEffect` in this hook.

What do you think?

File: packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js [hunk 6]
```diff
@@ -0,0 +1,122 @@
...
+const RESTRICTED_HEIGHT_PROPS = {
+	__unstableForcePosition: false,
+	__unstableShift: false,
+};
+
+/**
+ * Get the popover props for the block toolbar, determined by the space at the top of the canvas and the toolbar height.
+ *
+ * @param {Element} contentElement       The DOM element that represents the editor content or canvas.
+ * @param {Element} selectedBlockElement The clientId of the first selected block.
```
Comment (ciampo) [inline packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js]: The description of `selectedBlockElement` here probably needs to be updated

File: packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js [hunk 7]
```diff
@@ -0,0 +1,122 @@
...
+		() =>
+			setProps(
+				getProps( contentElement, selectedBlockElement, toolbarHeight )
+			),
+		[ contentElement, selectedBlockElement, toolbarHeight ]
+	);
+
+	// Update props when the block is moved. This also ensures the props are
+	// correct on initial mount.
+	useEffect( updateProps, [ blockIndex ] );
```
Comment (ciampo) [inline packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js]: Missing dependency:

```suggestion
	useEffect( updateProps, [ blockIndex, updateProps ] );
```

**Review by ciampo — COMMENTED** [review]
This PR is testing well for me! I couldn't find a way to "trip" the logic, which is great — and the code looks clean.


Apart from a few remaining comments, my only reservation left is about performance — measuring the `offsetHeight` and calling `getBoundingClientRect` are expensive functions to run, and so I wonder if we can find ways to call `getProps` as sparingly as possible (without introducing regressions, of course). For example, in my tests I could notice that function being called up to 4 times when clicking a single block

**Review by ntsekouras — COMMENTED** [review]
This PR is testing well for me too, thanks Dan!

File: packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js (hunk 5 above)
Comment (talldan) [reply packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js]: The part that I was unclear about is what happens if you update state from `useLayoutEffect` vs `useEffect`.

This blog post does seem to indicate that updating state will trigger a synchronous re-render:
https://kentcdodds.com/blog/useeffect-vs-uselayouteffect#uselayouteffect

> This can be useful if you need to make DOM measurements (like getting the scroll position or other styles for an element) and then make DOM mutations or trigger a synchronous re-render by updating state.

And I guess `useEffect` only triggers an asynchronous re-render.

So I think you're right that it would be beneficial. I've updated the code 👍

File: packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js (hunk 6 above)
Comment (talldan) [reply packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js]: Thanks! I've updated that.

File: packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js (hunk 7 above)
Comment (talldan) [reply packages/block-editor/src/components/block-tools/use-block-toolbar-popover-props.js]: Thanks, that's fixed too.

**Review by ciampo — APPROVED** [review]
Code changes LGTM 🚀 

My only doubt, as mentioned before, is regarding performance: the `getBoundingClientRect()` function are a relatively expensive call to make (as they cause layout reflow), and as of now they are executed 3 to 6 times (instead of only 1).

https://user-images.githubusercontent.com/1083581/186117011-5162ba2a-dac6-4bd4-96a3-cb4aad655b3a.mp4

I don't think it's a blocker for this PR, especially given how useful this fix is — but definitely something that I'd like to ideally follow-up on in order to keep the site editor as snappy as possible (for example, we could store the result of `getBoundingClientRect()` calls in a ref, and update it less frequently?)

**Comment by talldan** [comment]
@ciampo Thanks for helping this through!

Looks like an oversight in one of the places `getProps` is called. I've pushed a commit that fixes it. It should have been
```js
useState( () => getProps( contentElement, selectedBlockElement, toolbarHeight ) )
```

to set the initial state lazily instead of:
```js
useState( getProps( contentElement, selectedBlockElement, toolbarHeight ) )
```

(this only solves one of the calls. There are still two happening whenever switching blocks.)

**Comment by ciampo** [comment]
> Looks like an oversight in one of the places `getProps` is called. I've pushed a commit that fixes it. It should have been

That's definitely a step in the right direction!

I believe we can merge this PR and iterate in a lower-priority follow-up.

We could also now have a look at [reworking the props around the `flip`, `shift` and `resize` behaviors](https://github.com/WordPress/gutenberg/issues/43191)

**Comment by ciampo** [comment]
I realized that the props applied conditionally by the `useBlockToolbarPopoverProps` only make sense when the toolbar has a top or bottom placement — should we add `placement: 'top-start'` to the props returned by that hook?

**Comment by mtias** [comment]
Thanks for addressing this little obnoxious issue :)
