### PR TITLE
Fix multiselecting blocks using shift + arrow

### LINKED ISSUE #9848: Writing Flow: Repeated multi-selection in consecutive blocks of same type limited to two blocks
**Describe the bug**

When using Shift+ArrowDown to create a multi-selection, it is not possible to select more than two blocks of the same type†.

† "Of the same type" is important to note because the block transform toolbar option only appears when the multi-selection consists of blocks of the same type. I suppose it should also be noted that it might only be an issue for blocks of the same type which have transform options.

**To Reproduce**

1. Navigate to Posts > Add New
2. Add three paragraphs
3. Select the first paragraph block
4. Shift+ArrowDown to select all three blocks
5. Observe that after the second block becomes selected, the next Shift+ArrowDown causes focus to be moved into the transform modal, rather than continuing the multi-selection.

**Expected behavior**

I should be able to multi-select as many blocks as I continue to Shift+ArrowDown.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #9848

This PR fixes multiselection (of more than one block) using `shift + arrow` but it also keeps the focus ono the wrapper of the first multi-selected block which allows easy access to the toolbar using `Tab`  or `Alt+F10`

**Testing instructions**

 - Repeat testing instructions from #9848

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
YAAAAY THIS fixes it!

shift select

I also dig the amount of red. 

Code looks very healthy to me, but if you feel you need a sanity check might want to verify with some of the better coders out there. 

Thank you!

**Comment by youknowriad** [comment]
The failure is something in master and it was actually fixed already.

File: packages/editor/src/components/block-list/block.js [hunk 1]
```diff
@@ -93,6 +93,12 @@ export class BlockListBlock extends Component {
 		if ( this.props.isSelected && ! prevProps.isSelected ) {
 			this.focusTabbable( true );
 		}
+
+		// When triggering a multi-selection,
+		// move the focus to the wrapper of the first selected block.
+		if ( this.props.isFirstMultiSelected && ! prevProps.isFirstMultiSelected ) {
+			this.wrapperNode.focus();
```
[the remark this answers is not in the document]
Comment (youknowriad) [reply packages/editor/src/components/block-list/block.js]: Yes, it's meant to occur instead of `focusTabbable` and yes `focusTabbable` won't occur here because the `isSelected` is false when the block is multiselected.

I'm not sure about the assertive technologies though, it's very tied with multi-selection, not sure how multi-selection is announced.

File: test/e2e/specs/multi-block-selection.test.js [hunk 2]
```diff
@@ -77,4 +77,44 @@ describe( 'Multi-block selection', () => {
 		await pressWithModifier( META_KEY, 'a' );
 		await expectMultiSelected( blocks, true );
 	} );
+
+	it( 'Should select/unselect multiple blocks using Shift + Arrows', async () => {
+		const firstBlockSelector = '[data-type="core/paragraph"]';
```
Comment (gziolo) [inline test/e2e/specs/multi-block-selection.test.js]: The actual issue was for 3 blocks of the same type. We should another test :)

File: packages/editor/src/components/block-list/block.js [hunk 3]
```diff
@@ -314,7 +320,11 @@ export class BlockListBlock extends Component {
 	deleteOrInsertAfterWrapper( event ) {
 		const { keyCode, target } = event;
 
-		if ( target !== this.wrapperNode || this.props.isLocked ) {
+		if (
+			! this.props.isSelected ||
```
Comment (aduth) [inline packages/editor/src/components/block-list/block.js]: Why?

File: packages/editor/src/components/block-list/block.js [hunk 4]
```diff
@@ -93,6 +93,12 @@ export class BlockListBlock extends Component {
 		if ( this.props.isSelected && ! prevProps.isSelected ) {
 			this.focusTabbable( true );
 		}
+
+		// When triggering a multi-selection,
+		// move the focus to the wrapper of the first selected block.
```
Comment (aduth) [inline packages/editor/src/components/block-list/block.js]: These comments explain what we're doing (which is pretty plainly obvious in the implementation anyways) but not why. I don't know why we're doing this.

File: test/e2e/specs/multi-block-selection.test.js (hunk 2 above)
Comment (youknowriad) [reply test/e2e/specs/multi-block-selection.test.js]: The issue for me was happening no matter the type of the blocks.

File: packages/editor/src/components/block-list/block.js (hunk 4 above)
Comment (gziolo) [reply packages/editor/src/components/block-list/block.js]: We move the focus to ensure that it is not possible to continue editing the initially selected block. This happens for all active elements that allow editing like `RichText`, `PlainText` and all form fields. This behavior ensures that you no longer can modify the content of the selected blocks.
