### PR TITLE
Fix inbetween-inserter position in RTL languages

### LINKED ISSUE #30867: Incorrect position of "add new block/block list" in rtl mode
In rtl version of WordPress 57, there is a problem with **add new block/block list** position.
Please check the screenshot.

block-editor-block-list

- WordPress version: 5.7
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes
- Operating system: Windows 10
- Browser: Latest version of Firefox and Chrome

### PR DESCRIPTION
**Pull request by youknowriad**
closes #30867 

## What?

This PR fixes the position of the inbetween inserter in both vertical and horizontal position for RTL languages.

Screenshot 2023-04-10 at 11 34 37 AM

## Testing Instructions

1- Switch to an RTL language (like arabic)
2- Insert two paragraphs and verify that you can trigger the in-between inserter at the right position
3- Insert a social links block with at least two links and verify that you can trigger the in-between horizontal inserter between two buttons.

I also noticed that if you use the "slash" inserter, the initial position is correct but as soon as you start typing, the position is wrong. I think that's unrelated with the issue being fixed here though and might be some race condition within "Popover" component.

### CODE REVIEW

File: packages/block-editor/src/components/block-popover/inbetween.js [hunk 1]
```diff
@@ -106,16 +106,7 @@ function BlockPopoverInbetween( {
...
-					if ( isRTL() ) {
-						// vertical, rtl
-						left = previousRect
-							? previousRect.right
-							: nextRect.right;
-					} else {
-						// vertical, ltr
-						left = previousRect ? previousRect.left : nextRect.left;
-					}
+					left = previousRect ? previousRect.left : nextRect.left;
```
Comment (ciampo) [inline packages/block-editor/src/components/block-popover/inbetween.js:109]: Out of curiosity, why was the `isRTL()` check here unnecessary?

Comment (youknowriad) [reply packages/block-editor/src/components/block-popover/inbetween.js:109]: just imagine this visually. 

In LTR languages, the previous element is on the left of the next element but in RTL it's on the right. meaning that if we want to position a "div" between the two elements, its "left" coordinate should be the "right" coordinate of the "previous" element in LTR but it should be the "left" coordinate of the "next" element in RTL.

Comment (youknowriad) [reply packages/block-editor/src/components/block-popover/inbetween.js:109]: Oh I guess the question here is the "opposite". It's unnecessary here because in the case of the "vertical" in-between inserter, the "left" position is the same for both blocks anyway, so the left position of the empty space between them is also the same "left" position, so either prev.left or next.left. (and shouldn't be right in any case)

Comment (ciampo) [reply packages/block-editor/src/components/block-popover/inbetween.js:109]: Thank you for the explanation — it makes sense to remove the RTL check for the vertical inserter :)

**Review by ciampo — APPROVED** [review]
This is testing well for me
