### PR TITLE
Block supports: Restore root DOMDocument save

### LINKED ISSUE #25117: Query block in front end renders only the first element
**Describe the bug**
Something recently broke the rendering of `Query` block in front-end. While the query block works as expected in FSE, when trying to view the page in front-end, only the first element is displayed.

In some searching I've done, I noticed in `query-loop/edit.js`:
1. That `$posts = get_posts( $query )`  are correct
2. The `$content` is not because it's missing the `post-content`s but do have all `post-titile`s. It still renders only the first one though.

Also by changing the `query-loop/save.js` to return a `div` wrapper to apply the block's attributes ( which in this case is `class=wp-block-query-loop`), the rendered output in front-end is both `post-title` and `post-content` but only for the first item..

I have searched many recent PRs but I haven't found the cause of this and `WP_Block` class hasn't changed for a couple of months (https://github.com/WordPress/gutenberg/blob/master/lib/class-wp-block.php).

**To reproduce**
1. Enable FSE and add a `Query` block
2. Observe that in editor everything works as expected
3. View the page in front-end
4. Observe the missing rendered things/parts

**Expected behavior**
Rendered parts/posts should be the same as in the editor

### PR DESCRIPTION
**Pull request by sirreal**
Fix a regression from WordPress/gutenberg#25020 which was found to remove anything outside of the block root that may have been appended or prepended. This fix is achieved by concatenating all the childNodes in the DOMDocument body. See https://github.com/WordPress/gutenberg/pull/25026 for additional details on the regression.

Add a test to ensure that appended HTML is preserved.

The regression from #25020 exposes an issue I'll raise in another PR with some failing tests. HTML _appended_ to the block content works well. However, if additional output comes before the block content then then `gutenberg_apply_block_supports` will misbehave because it expects the block content to be the first element in the constructed DOM body:
https://github.com/WordPress/gutenberg/blob/7ee00ad4c5dc64a2b971cebe1d6ee4789eff7157/lib/block-supports/index.php#L75

See https://github.com/WordPress/gutenberg/pull/25053 for discussion around the expected behavior of `gutenberg_apply_block_supports`.

Fixes #25117

### CODE REVIEW

File: lib/block-supports/index.php [hunk 1]
```diff
@@ -96,7 +96,7 @@ function gutenberg_apply_block_supports( $block_content, $block ) {
 		$block_root->setAttribute( 'style', esc_attr( implode( '; ', $new_styles ) . ';' ) );
 	}
 
-	return $dom->saveHtml( $block_root );
+	return str_replace( array( $wrapper_left, $wrapper_right ), '', $dom->saveHtml() );
```
[the remark this answers is not in the document]
Comment (ockham) [reply lib/block-supports/index.php:99]: (That would allow us to retain the functionality we sought to add, and the unit test change.)

**Comment by sirreal** [comment]
This is no longer a simple revert. The regression should be addressed by this PR. The whitespace cleanup should be maintained here, and an additional test to cover the regression is introduced.

File: lib/block-supports/index.php [hunk 2]
```diff
@@ -96,7 +96,7 @@ function gutenberg_apply_block_supports( $block_content, $block ) {
 		$block_root->setAttribute( 'style', esc_attr( implode( '; ', $new_styles ) . ';' ) );
 	}
 
-	return $dom->saveHtml( $block_root );
+	return trim( str_replace( array( $wrapper_left, $wrapper_right ), '', $dom->saveHtml() ) );
```
Comment (westonruter) [inline lib/block-supports/index.php:99]: It seems somewhat unsafe to rely on the original HTML input to be identical after DOM serialization. I'd expect there to be some changes being made like addition of whitespace or changing attribute order or something at some point.

Comment (westonruter) [reply lib/block-supports/index.php:99]: You might want to consider what we are doing in the AMP plugin:

https://github.com/ampproject/amp-wp/blob/fc0373defb7cc8e5c4331d57d9140e8bd1454ac3/includes/utils/class-amp-dom-utils.php#L178-L193

Comment (sirreal) [reply lib/block-supports/index.php]: That's a good point, thanks for bringing it up. I've implemented an alternative that concatenates the child nodes of the body element that I believe improves on the original implementation from https://github.com/WordPress/gutenberg/pull/24645.

**Comment by sirreal** [comment]
Addressed comments and rebased to fix conflicts.

**Comment by sirreal** [comment]
I'll investigate the test failures…

File: lib/block-supports/index.php [hunk 3]
```diff
@@ -71,8 +77,8 @@ function gutenberg_apply_block_supports( $block_content, $block ) {
 		return $block_content;
 	}
 
-	$xpath      = new DOMXPath( $dom );
-	$block_root = $xpath->query( '/html/body/*' )[0];
+	$body_element = $dom->getElementByID( $body_id );
```
Comment (ockham) [inline lib/block-supports/index.php:80]: I think it'd be sufficient to 

```suggestion
	$body_element = $dom->getElementsByTagName( 'body' )[0];
```

(which means requiring that no other `<body />` be prepended, which I think is a fair assumption).

Also fine if you wanna play it even safer though :+1:

**Review by ockham — APPROVED** [review]
Looking good, thanks. One non-blocking note [here](https://github.com/WordPress/gutenberg/pull/25028#discussion_r484379944).

Feel free to merge once green!

File: lib/block-supports/index.php (hunk 3 above)
Comment (sirreal) [reply lib/block-supports/index.php]: I don't like going through the NodeList to get the first element, but I don't feel strongly.

I've implemented an alternative in b252259e2c52ecff711f812f48d026db700f85b0 that traverses simple, known path to the body.

**Comment by ntsekouras** [comment]
This will also fix https://github.com/WordPress/gutenberg/issues/25117

File: lib/block-supports/index.php [hunk 4]
```diff
@@ -71,9 +73,13 @@ function gutenberg_apply_block_supports( $block_content, $block ) {
 		return $block_content;
 	}
 
+	// Structure is like `<html><head/><body/></html>`, so body is the `lastChild` of our document.
+	$body_element = $dom->documentElement->lastChild; // phpcs:ignore WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase
+
 	$xpath      = new DOMXPath( $dom );
-	$block_root = $xpath->query( '/html/body/*' )[0];
+	$block_root = $xpath->query( './*', $body_element )[0];
```
Comment (sirreal) [inline lib/block-supports/index.php:80]: I had incorrectly assumed the xpath `*` query was synonymous to `DOMNode::childNodes`", but it isn't. That was causing the test failures.

The xpath `*` ["selects all element children of the context node"](https://www.w3.org/TR/1999/REC-xpath-19991116/#path-abbrev), whereas `childNodes` may be `DOMNodes` of any type, e.g. text nodes, which later error under some conditions.

I've restored the `DOMXpath` implementation to search for `*` (child elements) in the context of the `$body_element`.

An alternative I considered was to `array_search` with a function to match the `XML_ELEMENT_NODE` DOMNode::nodeType. However, I believe that would require introducing another named function which seems undesirable.

I've introduced a unit test for the text-only render output case.

File: lib/block-supports/index.php [hunk 5]
```diff
@@ -98,7 +104,12 @@ function gutenberg_apply_block_supports( $block_content, $block ) {
 		$block_root->setAttribute( 'style', implode( '; ', $new_styles ) . ';' );
 	}
 
-	return $dom->saveHtml( $block_root );
+	$result = '';
+	// phpcs:ignore WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase
+	foreach ( $body_element->childNodes as $child_node ) {
+		$result .= $dom->saveHtml( $child_node );
```
Comment (westonruter) [inline lib/block-supports/index.php:110]: The AMP plugin had difficulty using saveHTML in PHP versions prior to 7.3, so have an alternative for older versions:

https://github.com/ampproject/amp-wp/blob/f0b7ca9c9e2aa689be23ad6286cff5a98797f967/lib/common/src/Dom/Document.php#L509-L513

Comment (sirreal) [reply lib/block-supports/index.php:110]: I looked into the history around that change a little bit. It looks like it was related to some inconsistent whitespace formatting in the produced HTML. That doesn't seem problematic if its only formatting whitespace, is there anything in particular you think we should watch out for?

Comment (westonruter) [reply lib/block-supports/index.php:110]: Yes, it was inconsistent whitespace formatting. But it can indeed be problematic. For example, sometimes you may have markup like:

```html
<ul><li>left</li><li>right</li></ul>
```

If the list items here are displayed `inline`, then this will render differently than:

```html
<ul>
    <li>left</li>
    <li>right</li>
</ul>
```

Namely, there will be a space (" ") between the list items.

Comment (sirreal) [reply lib/block-supports/index.php:110]: That does sound like something that will need to be addressed especially as this block-supports work moves towards core. Thanks for flagging.

Comment (sirreal) [reply lib/block-supports/index.php:110]: @westonruter I've dug into this a little bit and have been unable to reproduce or to find bug reports. Do you have anything we can go on?

Here's an example:

```php
<?php
// save as test-dom-doc.php

$dom = new DOMDocument();

$html = '<html><head></head><body>
	a text node
<p>a paragraph</p>
<ul>
<li>a</li>
	<li>list</li>
		<li>is</li>
			<li>ordered
<em>emphasis</em></li>

</ul>
<pre>       obviously
 this     whitespace

is
    important</pre>
another     text    node with a bunch of wierd space
</body>
</html>';

$dom->loadHtml( $html );

$body = $dom->documentElement->lastChild;

$result = '';
foreach ( $body->childNodes as $c ) {
	$result .= $dom->saveHtml( $c );
}
echo $result;
```

```sh
docker run -it --rm --name check-domdoc-ws -v "$PWD":/usr/src/myapp -w /usr/src/myapp php:5-cli php test-dom-doc.php
docker run -it --rm --name check-domdoc-ws -v "$PWD":/usr/src/myapp -w /usr/src/myapp php:7.0-cli php test-dom-doc.php
docker run -it --rm --name check-domdoc-ws -v "$PWD":/usr/src/myapp -w /usr/src/myapp php:7.4-cli php test-dom-doc.php
docker run -it --rm --name check-domdoc-ws -v "$PWD":/usr/src/myapp -w /usr/src/myapp php:8.0.0beta3-cli php test-dom-doc.php
```

All of these seem to produce identical output with whitespace:

```html

	a text node
<p>a paragraph</p>
<ul><li>a</li>
	<li>list</li>
		<li>is</li>
			<li>ordered
<em>emphasis</em></li>

</ul><pre>       obviously
 this     whitespace

is
    important</pre>
another     text    node with a bunch of wierd space
```

[This bug report](https://bugs.php.net/bug.php?id=78129) looks similar, but has apparently stalled and [was suggested](https://bugs.php.net/bug.php?id=78129#1591607348) it was caused by an outdated libxml2.

Comment (westonruter) [reply lib/block-supports/index.php:110]: Here you go: https://3v4l.org/Adldb

Comment (sirreal) [reply lib/block-supports/index.php:110]: That's perfect, thank you.

Comment (sirreal) [reply lib/block-supports/index.php:110]: I created a PR to address this: https://github.com/WordPress/gutenberg/pull/25240
