### PR TITLE
Fix: InnerBlocks allowed blocks change with different sizes.

### LINKED ISSUE #14515: Not possible to change allowedBlocks dynamically
([Previous discussion on Slack](https://wordpress.slack.com/archives/C02QB2JS7/p1552991919570200))

**Describe the bug**

Background: I have a block type A that uses the `InnerBlocks` component with a limited list of `allowedBlocks`. I now want to limit the inner blocks in a way that I can insert block type B only once within `InnerBlocks`. Overall, in the whole post, it can occur multiple times though. 

One suggestion was to modify `allowedBlocks` dynamically. That's what I am now doing, but currently fail to do so.

I want to change `allowedBlocks` depending on some props, e.g. whether the block is the first one in the block order and whether it has already been added to the page.

Unfortunately this doesn't seem to be possible at the moment.

**To Reproduce**

Given a block type with code like this:

```js
export default withSelect( ( select, { clientId } ) => {
    const { getBlockOrder } = select( 'core/editor' );
    return {
        isFirstBlock: getBlockOrder().indexOf( clientId ) === 0,
    };
} )( MyBlockEdit );
// ...
// In MyBlockEdit's edit() function:

<InnerBlocks template={ myTemplate } allowedBlocks={ isFirstBlock ? [ 'my/block-a' ] : [ 'my/block-b' ] } />
```

Create 2 blocks of this type and notice that you're still able to insert both `my/block-a` and `my/block-b` in each.

You might even run into https://reactjs.org/docs/error-decoder.html/?invariant=185 at this point.

You can verify that `allowedBlocks` changes by using `wp.data.select( 'core/editor' ).getBlockListSettings()` in dev tools.

At the same time, the result of `wp.data.select( 'core/editor' ).canInsertBlockType()` does not seem to change.

That selector uses memoization, although it _should_ change when `allowedBlocks` changes. Apparently it doesn't.

**Expected behavior**

It should be possible to dynamically filter `allowedBlocks`.

It should be possible to limit a block to be only used once within a parent block.

**Additional context**
- Gutenberg version: 5.3 RC1

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Fixes: https://github.com/WordPress/gutenberg/issues/14515

The comparison we used for memorization did not take into account the arrays may change the size. This PR fixes the issue and updates the end-to-end test to include this case.

## Testing
Verify the end-to-end tests pass.

### CODE REVIEW

File: packages/block-editor/src/components/inner-blocks/use-nested-settings-update.js [hunk 1]
```diff
@@ -70,15 +70,15 @@ export default function useNestedSettingsUpdate(
...
-	// can be passed as dependencies.
-
+	// can be passed as dependencies but We need to include the length of the array,
+	// otherwise if the arrays change length but the first elements are equal the comparison,
+	// does not works as expected.
 	const _allowedBlocks = useMemo(
 		() => allowedBlocks,
 		// eslint-disable-next-line react-hooks/exhaustive-deps
-		allowedBlocks
+		[ allowedBlocks && allowedBlocks.length, ...allowedBlocks ]
```
Comment (youknowriad) [inline packages/block-editor/src/components/inner-blocks/use-nested-settings-update.js]: I guess there's an issue here if allowedBlocks is undefined, the spreading breaks.

**Comment by Mamaduka** [comment]
This will still generate a notice mentioned here https://github.com/WordPress/gutenberg/issues/14515#issuecomment-1116072777, no?

**Comment by youknowriad** [comment]
If we want to avoid that warning and still not force users to "memoize" the array themselves, we could write a `useShallowMemo` or something like that, that returns the previous version of a variable unless one of the array values change.

**Comment by Mamaduka** [comment]
Maybe we should leave memoization to blocks/consumers?

In most cases it’s easy as defining the value outside of the component and when blocks have reactive value they could handle this themselves.

We can also show best practices in docs.

**Comment by youknowriad** [comment]
> In most cases it’s easy as defining the value outside of the component and when blocks have reactive value they could handle this themselves.

I'd agree with that it was not a performance bottleneck in the editor. this particular memoization has potentially a bit impact on loading performance and would also impact typing a little bit.

**Comment by jorgefilipecosta** [comment]
> I'd agree with that it was not a performance bottleneck in the editor. this particular memoization has potentially a bit impact on loading performance and would also impact typing a little bit.


So we remove memoization? And we make sure none of our blocks creates a new reference every time?

**Comment by youknowriad** [comment]
> So we remove memoization? And we make sure none of our blocks creates a new reference every time?

I'm saying the opposite personally. Write something that uses the "previous" value of allowedBlocks unless the new value is different using shallow comparison.

File: packages/block-editor/src/components/inner-blocks/use-nested-settings-update.js [hunk 2]
```diff
@@ -15,6 +15,20 @@ import { getLayoutType } from '../../layouts';
 
 const pendingSettingsUpdates = new WeakMap();
 
+function useShallowMemo( value ) {
+	const ref = useRef();
+
+	// Store current value in ref if it is not shallow equal to the previous value.
+	useEffect( () => {
+		if( ! isShallowEqual( ref.current, value ) ) {
+			ref.current = value
```
Comment (youknowriad) [inline packages/block-editor/src/components/inner-blocks/use-nested-settings-update.js]: The problem is that, this won't "re-render" the component, so the component is going to use the old value unless there's something else in the component that causes a "re-render".

Now, we could replace this with a state value instead of a ref value but it also has a small downside: it will render the component twice: once with the old value and once with the new value. I wonder if there's a way to avoid the two renders.

Comment (Mamaduka) [reply packages/block-editor/src/components/inner-blocks/use-nested-settings-update.js]: Maybe we could use a state update during the render; that should avoid rendering twice. Cc @kevin940726

Ref: https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes

P.S. The `isShallowEqual` import is missing from the file.

## Example, needs testing
```js
function useShallowMemo( value ) {
	const [ prevValue, setPrevValue ] = useState( value );

	if ( ! isShallowEqual( prevValue, value ) ) {
		setPrevValue( value );
	}

	return prevValue;
}
```

Comment (youknowriad) [reply packages/block-editor/src/components/inner-blocks/use-nested-settings-update.js]: Thanks for sharing @Mamaduka just learned about this :)

**Comment by Mamaduka** [comment]
I can reproduce the e2e test failure locally, manually testing the issue now.

File: packages/e2e-tests/plugins/inner-blocks-allowed-blocks/index.js [hunk 3]
```diff
@@ -26,20 +26,23 @@
 				},
 				[ props.clientId ]
 			);
-            let allowedBlocks = allowedBlocksWhenSingleEmptyChild;
-            if ( props.numberOfChildren === 2 ) {
```
Comment (Mamaduka) [inline packages/e2e-tests/plugins/inner-blocks-allowed-blocks/index.js]: The `props.numberOfChildren` is always undefined.

File: packages/e2e-tests/plugins/inner-blocks-allowed-blocks/index.js [hunk 4]
```diff
@@ -26,20 +26,23 @@
...
+				allowedBlocks = allowedBlocksWhenTreeOrMoreChildren;
+			}
+
 			return el(
 				'div',
-				{
-					...divProps,
-					'data-number-of-children': numberOfChildren,
-				},
+				blockProps,
```
Comment (Mamaduka) [inline packages/e2e-tests/plugins/inner-blocks-allowed-blocks/index.js:43]: A missing `blockProps` triggers an error when hovering on the block.

**Comment by Mamaduka** [comment]
@jorgefilipecosta, it isn't clear if your recent `force-push` changed the code, but it "nuked" my e2e test fixes. Is it okay for me to `force-push` my changes again?

**Comment by jorgefilipecosta** [comment]
> @jorgefilipecosta, it isn't clear if your recent `force-push` changed the code, but it "nuked" my e2e test fixes. Is it okay for me to `force-push` my changes again?

Sorry I was not aware you submitted a fix, it was just a rebase to then work on the fix. I already re-added your fix, thank you a lot :)

**Review by Mamaduka — APPROVED** [review]
The fix works well in my tests 👍

**Comment by jorgefilipecosta** [comment]
Thank you for the feedback, reviews, fixes, and all the help @Mamaduka and @youknowriad.
