### PR TITLE
Fix block & block toolbar vibration on block move

### LINKED ISSUE #20793: Block & toolbar "vibration" during moving animation
It's been brought to my attention that the block toolbar vibrates a bit when you move a block up and down. At first this might seem like it is caused by moving the block toolbar to a popover, but this is not really true. The G2 added much more contrast to the block toolbar, making the vibration more visible. As you can see in the following video, a block that I styled just like the toolbar vibrates just as much as the toolbar itself.

block-vibration-contrast

So what _is_ the problem? The block moving animation sets a sub pixel position to the block, which first of all will make it look slightly blurred than when at a whole pixel position. I think @jasmussen knows more about the specifics of this. Secondly, at the same time we are scrolling the page, making it seem like the block stands still relative to the viewport. Scrolling can only happen at whole pixel positions, not at sub pixel positions.

So on the one hand we have sub pixel movement (of the block), and on the other hand we have whole pixel movement (when scrolling). You can see how this might make it look like it vibrates. The block (and block toolbar) blurring at sub pixel position will only make it look worse. lines might suddenly appear thinner or thicker. When you add more contrast and horizontal lines, it becomes even more visible.

I'm not sure how we can solve this, but here's two ideas:

* We don't animate at sub pixel positions. This might make the animation feel less smooth. :/
* We try to do some magic and keep the block exactly in the same position relative to the viewport, so the only "moving" parts are the scrolling and maybe the rest of the blocks. This is similar to the first point, only that the block won't visibly move at all.

Cc @mtias @youknowriad @jasmussen

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #20793.

The trick here is to only animate with whole pixels, because scrolling doesn't allow sub pixel positions. This also allows us to simplify popover code.

Best is to test for yourself on a retina screen.

Before:

vibration

After:

no-vibration

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ellatrix** [comment]
Btw, this does NOT fix the scroll displacement that sometimes happens on arrow up. Let's look into that separately. I think it has to do with the toolbar being inside thee scroll container.

**Comment by jasmussen** [comment]
This is pretty wild and incredibly incredible. There is zero vibration, the block is locked in place while moving. Let me pause for a brief applause here. Well done.

I'm seeing one issue, though. It's a little hard to explain, so here's a GIF:

gif

As best I can tell, here's how to reproduce:

- Have a very long document
- Scroll
- Then click a block

What appears to happen is that the block toolbar is attached to another block than the one you selected, and when you mouse over the block toolbar to show the mover, the block toolbar seems to jump, thinking it's still attached to the one you actually selected.

As I said, it's hard to explain, but try it out and be sure to _scroll down the page before you select a block_. It's only the _first_ block you select after having scrolled, which has this issue. If you select other blocks after having scrolled, things work fine. 

I'm not seeing that issue in master. Other than that, this seems super duper solid, impressive work!

File: packages/block-editor/src/components/use-moving-animation/index.js [hunk 1]
```diff
@@ -96,21 +98,20 @@ function useMovingAnimation(
 
 			return;
 		}
-		ref.current.style.transform = 'none';
+
+		ref.current.style.left = '';
+		ref.current.style.top = '';
```
Comment (youknowriad) [inline packages/block-editor/src/components/use-moving-animation/index.js:103]: above you reset the values with 0 and here with ''. Any particular reason?

File: packages/block-editor/src/components/use-moving-animation/index.js [hunk 2]
```diff
@@ -144,18 +145,28 @@ function useMovingAnimation(
...
+				} ),
+				top: interpolate( [ animationProps.y ], ( y ) => {
+					y = Math.round( y );
+
+					if ( y === 0 ) {
+						return;
+					}
+
+					return `${ y }px`;
+				} ),
```
Comment (youknowriad) [inline packages/block-editor/src/components/use-moving-animation/index.js:165]: What happens if the block is left/right aligned or potentially absolute positioned... That's my main concern,  it seems that the "transform" trick works no matter how the block is positioned while the "left/top" depends on the positioning of the block? It might not be a big issue because we have "wrappers" for aligned blocks but I wonder if there's third-party absolute positioned block this change could break?

File: packages/block-editor/src/components/use-moving-animation/index.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-editor/src/components/use-moving-animation/index.js:103]: No reason, I think ended up thinking an empty string might be better since that's what you get if no style is set. I'll fix the other lines.

File: packages/block-editor/src/components/use-moving-animation/index.js (hunk 2 above)
Comment (ellatrix) [reply packages/block-editor/src/components/use-moving-animation/index.js:165]: Let me see if it works fine with a transform. I started with trying top/left because some browser automatically round this, not not all. We should be able to just round thee value and use transform.

Comment (ellatrix) [reply packages/block-editor/src/components/use-moving-animation/index.js]: I changed it. Should be the same

**Comment by ellatrix** [comment]
@jasmussen Does the bug appear with the demo content? Are you using Chrome? I tried this in Chrome but I don't see any scrolling on select.

**Comment by jasmussen** [comment]
> Does the bug appear with the demo content? Are you using Chrome? I tried this in Chrome but I don't see any scrolling on select.

Chrome 83 stable, Mac, happened regardless of content. However I can no longer reproduce 🎉 

So it's very possible that it was a ghost on my side, or a bad npm install, or something else. I will return if I find a way to reproduce, however since I can't do that anymore, all this needs is a code review it seems! 👍 👍

File: packages/block-editor/src/components/use-moving-animation/index.js [hunk 3]
```diff
@@ -127,15 +126,15 @@ function useMovingAnimation(
 		reset: triggeredAnimation !== finishedAnimation,
 		config: { mass: 5, tension: 2000, friction: 200 },
 		immediate: prefersReducedMotion,
-		onFrame: ( props ) => {
+		onFrame: () => {
```
Comment (ZebulanStanphill) [inline packages/block-editor/src/components/use-moving-animation/index.js:129]:
```suggestion
		onFrame() {
```

Comment (ellatrix) [reply packages/block-editor/src/components/use-moving-animation/index.js:129]: Do we have a preference? If so, might be nice to have a listing rule. I just left the old code here.

Comment (ZebulanStanphill) [reply packages/block-editor/src/components/use-moving-animation/index.js:129]: Well, the method syntax creates a named function, which is preferable since:

>it helps dramatically in error stack traces, debugger call stacks, and performance audits to quickly identify a function by name (vs. "(anonymous)").

(Quoting @aduth from #22647.)

Also, it's shorter. :stuck_out_tongue:

Whatever the case, I do agree we should probably have a lint rule preferring one or the other. There's a standard ESLint rule that can do this: [`object-shorthand`](https://eslint.org/docs/rules/object-shorthand).

**Comment by ZebulanStanphill** [comment]
Aside from the issue @jasmussen pointed out, this feels really good. Hoping to see this finished and merged soon!

File: packages/block-editor/src/components/use-moving-animation/index.js (hunk 3 above)
Comment (aduth) [reply packages/block-editor/src/components/use-moving-animation/index.js:129]: In this usage, the name still may be able to be inferred, based on the property that the function is assigned to.

```js
const fns = { a: () => {} }
console.log( fns.a.name );
// "a"
```

I haven't tested if it makes a difference in the debugger.

`object-shorthand` is already in use in the default configuration:

https://github.com/WordPress/gutenberg/blob/de4ea80775e57e088a6fbf389b4ec14d165bc883/packages/eslint-plugin/configs/esnext.js#L24

I wasn't aware, but apparently the usage here is an additional option `avoidExplicitReturnArrows`, which isn't enabled by default:

https://eslint.org/docs/rules/object-shorthand#avoidexplicitreturnarrows

I'm not sure how well it would handle a situation where the semantics of arrow function vs. function expression could have an impact (e.g. `this` binding).

In the end, I'd still consider it a minor detail, and not really one blocking a merge, though it'd be good to have some consistency here in the broader project.

File: packages/block-editor/src/components/use-moving-animation/index.js [hunk 4]
```diff
@@ -127,15 +126,15 @@ function useMovingAnimation(
...
 			if (
 				adjustScrolling &&
 				scrollContainer.current &&
-				! prefersReducedMotion &&
-				props.y
```
Comment (youknowriad) [inline packages/block-editor/src/components/use-moving-animation/index.js:135]: Is this check no useful anymore? I can't remember why I introduced it. I guess maybe the idea is to not scroll if the vertical position don't change.

**Review by youknowriad — APPROVED** [review]
So if I understand properly, the only difference with the previous code of the animation is the "Math.round" calls right?

**Comment by ellatrix** [comment]
@youknowriad That's the essence of it. :)

**Comment by ellatrix** [comment]
Restored observing in the popover for the vertical animation of the block and toolbar. There's something broken with that animation, but I see the same in master, so let's look into that separately.

File: packages/block-editor/src/components/block-list/block-popover.js [hunk 5]
```diff
@@ -155,13 +155,8 @@ function BlockPopover( {
...
 			__unstableBoundaryParent
-			// Allow subpixel positioning for the block movement animation.
-			__unstableAllowVerticalSubpixelPosition={
-				moverDirection !== 'horizontal' && node
-			}
-			__unstableAllowHorizontalSubpixelPosition={
-				moverDirection === 'horizontal' && node
-			}
+			// Observe movement for block animations (especially horizontal).
+			__unstableObserveElement={ node }
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-list/block-popover.js:159]: Seems like this is the same thing as `anchorRef`. I wonder if we should instead observe anchor ref when it's a DOM element. I also wonder whether this means the interval inside Popover is useless.
