### PR TITLE
Fix block insertion place after clicking Browse All in the inline inserter

### LINKED ISSUE #24262: Inline Inserter can insert in wrong place depending on block selection and focus
**Describe the bug**

Clicking the inline inserter doesn't by default move the cursor to that spot in the document. This means that if you use the 'Browse all' option in the block list the new block may end up in the last place in the document that had focus instead of the position of the clicked inline inserter

**To reproduce**
1. Open a new page and add column block with some content in each column
2. Add some paragraph blocks under the columns
3. While cursor is still in bottom paragraph click on the inline inserter in the column and use 'browse all' to select a block
4. The block will be inserted at the bottom instead of in the column
5. Click in the column again and make sure cursor is next to the inline insert and select another block via 'browse all'
6. This time it should be inserted in the column

**Expected behavior**
Clicking the inline inserter should move the focus to that point so that using browse all will know the location for inserting new block.

**Screenshots**
browse-all

**Editor version (please complete the following information):**
Happens on 8.5.1 and 8.6.1

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description

Fixes: https://github.com/WordPress/gutenberg/issues/24262

When you click `Browse All` button from inline inserter and then select a block, it inserts it after the previously selected block.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-editor/src/components/inserter/quick-inserter.js [hunk 1]
```diff
@@ -163,12 +163,28 @@ function QuickInserter( {
...
+				'core/block-editor'
+			);
+			// We have to select the previous block because the menu inserter
+			// inserts block after the selected
+			return getBlockOrder( destinationRootClientId )[
+				getBlockIndex( clientId, destinationRootClientId ) - 1
+			];
+		},
+		[ clientId, destinationRootClientId ]
+	);
```
Comment (youknowriad) [inline packages/block-editor/src/components/inserter/quick-inserter.js:178]: Do we really need this, can't we just select `clientId`?

Comment (ntsekouras) [reply packages/block-editor/src/components/inserter/quick-inserter.js:178]: When we click the appender button it has as `clientId` the block below the appender, but inserts above the block.
So if we select with `clientId` it will be one block below from where it should be.

I think that was question, right? Or was it about the dependencies array?

Comment (youknowriad) [reply packages/block-editor/src/components/inserter/quick-inserter.js:178]: Oh got it. So is this equivalent to `getPreviousBlockClientId` ?

Comment (ntsekouras) [reply packages/block-editor/src/components/inserter/quick-inserter.js:178]: Yes! I didn't know that selector which handles so more things. I'll use it. Thanks!

**Review by youknowriad — APPROVED** [review]
LGTM 👍 Thanks for the fix.

Should we try to add an e2e test for this use-case? Might not be the easiest one to write though.
