### PR TITLE
fix pullquote insert error

### LINKED ISSUE #3603: Pullquote: Error when adding a new instance
Gutenberg 1.7.0

## Issue Overview

When inserting Pullquote "This block has encountered an error and cannot be previewed." message appears and there is an error in the console.

## Steps to Reproduce (for bugs)

1. Create new post
2. Add a Pullquote block

## Expected Behavior

Should create a new Pullquote

## Current Behavior

Error message appears

## Possible Solution

Value should be checked for existence before use.

## Screenshot
pullquote-error

### PR DESCRIPTION
**Pull request by vladanost**
## Description

Fixes https://github.com/WordPress/gutenberg/issues/3603
Related PR: https://github.com/WordPress/gutenberg/pull/2400
Error when inserting Pullquote

## How Has This Been Tested?

Manually tested in the browser

## Types of changes

Checked the value for existence before use.

### CODE REVIEW

**Comment by youknowriad** [comment]
👍

File: blocks/library/pullquote/index.js [hunk 1]
```diff
@@ -80,7 +80,7 @@ registerBlockType( 'core/pullquote', {
 			<blockquote key="quote" className={ className }>
 				<Editable
 					multiline="p"
-					value={ toEditableValue( value ) }
+					value={ value && toEditableValue( value ) }
```
Comment (aduth) [inline blocks/library/pullquote/index.js]: Could we make `toEditableValue` handle the empty case? Thinking in case we introduce another usage of it. Would be a simple change to use Lodash's variant, which handles empty values:

```js
const toEditableValue = value => map( value, ( subValue => subValue.children ) );
```

Comment (vladanost) [reply blocks/library/pullquote/index.js]: @aduth Thanks for the suggestion. I'll try that approach. How do I proceed now since it was merged and I deleted the branch? Do I just restore the branch and push again?

Comment (aduth) [reply blocks/library/pullquote/index.js]: It'd be fine to create a new separate branch with the proposed change.
