### PR TITLE
Fix Zoom out should be disabled when Show Template is toggled off

### LINKED ISSUE #71349: Zoom out: should be disabled when "Show Template" is toggled off
### Description

The zoom out toggle button is hidden when the "Show template" is disabled.

However, even though the "Show template" is disabled, the editor canvas may remain zoomed out. I think the zoom out mode should be disabled automatically when "Show template" is changed from enabled to disabled.

### Step-by-step reproduction instructions

- Open a post.
- Enable "Show template".
- Enable zoom out mode.
- Disable "Show template".
- Confirm the editor canvas remains zoomed out even though the zoom out mode button disappears.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/b1467d24-7a30-426d-897e-102719126124

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by lalitkumawat1m**
## What?

Closes #71349 

## Testing Instructions
1. Open a post.
2. Enable "Show template".
3. Enable zoom out mode.
4. Disable "Show template".
5. Confirm that the editor is no longer in zoom-out mode.

## Screenshots 

https://github.com/user-attachments/assets/b230d16c-3a07-48e0-a219-58e6021eed24

### CODE REVIEW

File: packages/editor/src/components/preview-dropdown/index.js [hunk 1]
```diff
@@ -170,6 +170,10 @@ export default function PreviewDropdown( { forceIsAutosaveable, disabled } ) {
 										: 'post-only';
 									setRenderingMode( newRenderingMode );
 									setDefaultRenderingMode( newRenderingMode );
+									// Reset zoom out if show template is being toggled off
+									if ( newRenderingMode === 'post-only' ) {
+										resetZoomLevel();
+									}
```
Comment (t-hamano) [inline packages/editor/src/components/preview-dropdown/index.js]:
```suggestion
									resetZoomLevel();
```

I don't think there's any problem with disabling zoom out whether the template is being toggled off or not. What do you think?

Comment (lalitkumawat1m) [reply packages/editor/src/components/preview-dropdown/index.js]: Makes sense! I've removed the conditional and now resetZoomLevel() runs regardless of rendering mode.

**Review by t-hamano — APPROVED** [review]
LGTM 👍
