### PR TITLE
Edit Site: Fix template lookup

### LINKED ISSUE #22800: PHP notice in the site editor
**Describe the bug**
With 8.2.0 and later, this notice is showing in the site editor
`Notice: Undefined index: front-page in /var/www/html/wp-content/plugins/gutenberg/lib/edit-site-page.php on line 162`

https://github.com/WordPress/gutenberg/blob/master/lib/edit-site-page.php#L162

**To reproduce**
1. Install Gutenberg
2. Enable full site editing
3. Enable a theme that has support for full site editing. 
https://github.com/WordPress/theme-experiments
4. Open the site editor.
5. See PHP notice

**Expected behavior**
I expect experimental features to change often, but not be broken in the plugin releases. :)

Editor version (please complete the following information):
WordPress version: 5.4.1
Gutenberg:  8.2.0,  8.2.1

PHP version: 7.3.13

Desktop (please complete the following information):
Windows 10
Chrome version: 83.0.4103.61

### PR DESCRIPTION
**Pull request by ockham**
## Description
This PR fixes two issues with template lookup:

### 1. Templates with `index.html` block template fallback

When using a theme that came with an `index.html` but not with a `front-page.html` block template, the site editor would show the following `Notice: Undefined index: front-page in /var/www/html/wp-content/plugins/gutenberg/lib/edit-site-page.php on line 162`.
 
The reason is that I was setting the wrong key here: https://github.com/WordPress/gutenberg/blob/710373b254fbcd15d524afdeb31da0d93c4defd4/lib/edit-site-page.php#L158

This would use the name of the template that was _found_, not the name of the key that was looked for. So if we're looking up `front-page`, but don't find any template, and [thus fall](https://github.com/WordPress/gutenberg/blob/710373b254fbcd15d524afdeb31da0d93c4defd4/lib/template-loader.php#L226) back to `index`, the template will be stored under the `index` key, rather than the front-end one. 

The fix for this is to use the template we were looking for as key (rather than the name of the template we actually found).

### 2. Templates without `index.html` block template fallback

When using a theme that doesn't come with any block templates at all, we need to provide a blank `index` template when the user first opens the site editor (see [discussion](https://github.com/WordPress/gutenberg/pull/22893#discussion_r435430149)).

## How has this been tested?
- There shouldn't be any `wp_template` CPTs (neither published nor `auto-draft`s) from previous Site Editor runs. (It's best to start with a fresh install, i.e. `npx wp-env clean all && npx wp-env start`. _Careful, this will wipe your WordPress install's data!_)
- Furthermore, the "Full Site Editing Demo Templates" checkbox in `/wp-admin/admin.php?page=gutenberg-experiments` _must not be ticked_. (Make sure the "Full Site Editing" checkbox is ticked -- since it also gets reset after a wipe.)
- Make sure you have linked your wp-env install to themes from the `theme-experiments` repo (see the [`wp-env` README](https://github.com/WordPress/gutenberg/blob/710373b254fbcd15d524afdeb31da0d93c4defd4/packages/env/README.md)).
- Activate the "Twenty Twenty Blocks" theme, and open the site editor. Verify that the template switcher shows the index template, and no errors or notices are printed. (Don't modify anything in order not to create an auto draft of that template.)
- Activate the "Twenty Twenty" theme, and open the site editor. Verify that the template switcher shows a _blank_ index template, and no errors or notices are printed. This is the template that was autogenerated, since the regular Twenty Twenty theme doesn't come with any block templates.

## Open question

Upon running 

```
npx wp-env run cli "wp post list --post_type=wp_template --post_status=auto-draft"
```

I see a sleuth of `index` template `auto-draft`s. I was hoping that only one would be created :confused: -- maybe my newly added logic is still buggy.

## Types of changes
Bug fix. Fixes #22800.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: lib/template-loader.php [hunk 1]
```diff
@@ -319,6 +319,29 @@ function gutenberg_find_template_post_and_parts( $template_type, $template_hiera
 		}
 	}
 
+	// If we haven't found any template post by here, it means that this theme doesn't even come with a fallback
+	// `index.html` block template. We create one so that people that are trying to access the editor are greeted
+	// with a blank page rather than an error.
+	if( ! $current_template_post && ( is_admin() || defined( 'REST_REQUEST' ) ) ) {
+		// 'index' is the ultimate fallback template. If even this template doesn't exist, we create an empty one for it.
+		$current_template_post = array(
+			//'post_content' => $file_contents,
```
Comment (epiqueras) [inline lib/template-loader.php:328]:
```suggestion
```

File: lib/template-loader.php [hunk 2]
```diff
@@ -319,6 +319,29 @@ function gutenberg_find_template_post_and_parts( $template_type, $template_hiera
...
+		);
+		if ( is_admin() || defined( 'REST_REQUEST' ) ) {
+			$current_template_post = get_post(
+				wp_insert_post( $current_template_post )
+			);
+		} else {
+			$current_template_post = new WP_Post(
+				(object) $current_template_post
+			);
+		}
```
Comment (epiqueras) [inline lib/template-loader.php:342]: This is already checked in the parent scope.

**Review by epiqueras — CHANGES_REQUESTED** [review]

File: lib/template-loader.php (hunk 2 above)
Comment (ockham) [reply lib/template-loader.php:341]: Thanks! I added it to the parent scope later and forgot to remove it here.

Comment (ockham) [reply lib/template-loader.php]: 13b2ca69c2

File: lib/template-loader.php [hunk 3]
```diff
@@ -319,6 +319,22 @@ function gutenberg_find_template_post_and_parts( $template_type, $template_hiera
 		}
 	}
 
+	// If we haven't found any template post by here, it means that this theme doesn't even come with a fallback
+	// `index.html` block template. We create one so that people that are trying to access the editor are greeted
+	// with a blank page rather than an error.
+	if( ! $current_template_post && ( is_admin() || defined( 'REST_REQUEST' ) ) ) {
+		// 'index' is the ultimate fallback template. If even this template doesn't exist, we create an empty one for it.
```
Comment (vindl) [inline lib/template-loader.php:326]: This seems like it has already been covered in the above comment.

**Review by vindl — APPROVED** [review]
This fixed the issue for me. :shipit:

**Review by epiqueras — APPROVED** [review]

File: lib/template-loader.php (hunk 3 above)
Comment (ockham) [reply lib/template-loader.php:326]: Good spot, thanks! I'll remove this line.

**Comment by ockham** [comment]
e2e tests are still [failing](https://travis-ci.com/github/WordPress/gutenberg/jobs/346179219) :confused: 

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

I'll try a rebase.

**Comment by nosolosw** [comment]
:wave: Just noting that this will be backported to Gutenberg 8.3 release as part of https://github.com/WordPress/gutenberg/pull/23026
