### PR TITLE
Fix handling of raw transforms that return multiple blocks

### LINKED ISSUE #28370: Raw transforms that return an array of blocks don't get handled correctly
## Description

When a [`raw` transform](https://developer.wordpress.org/block-editor/developers/block-api/block-transforms/#raw) returns an array of blocks instead of a single block, the result doesn't get handled correctly.

## Step-by-step reproduction instructions

1. In the `registerBlockType()` call of a test block (using `npx @wordpress/create-block test-block` or something), add a transform like so:

    ```js
    transforms: {
		from: [
			{
				type: 'raw',
				isMatch: () => true,
				transform: () => {
					const blocks = [
						createBlock( 'create-block/test-block' ),
						createBlock( 'create-block/test-block' ),
					];

					return blocks; /* doesn't work */
					// return blocks[ 0 ]; /* this works */
				},
			},
		],
	},
    ```
1. Go to the editor at `/wp-admin/post-new.php` and paste a string like `<p>test block</p>`.

## Expected behaviour

The pasted string is transformed into two `'create-block/test-block'` blocks.

## Actual behaviour

Nothing happens (the pasted string just disappears without any error messages).

## WordPress information
- WordPress version: 5.7-alpha-49991
- Gutenberg version: Current `master` (9.8.0 ?)
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: macOS 10.15.7
- Browser: Chrome 87.0.4280.141

### PR DESCRIPTION
**Pull request by mirka**
Fixes #28370

## Description

Flattens the return array in `raw-handling/html-to-blocks.js` so that we don't pass a deeply nested array to the consumer handlers (`rawHandler`, `pasteHandler`), which are only shallowly flattened.

## How has this been tested?

- `test/integration/blocks-raw-handling.test.js` (not sure if the added test is necessary)
- Test cases like the one in the original issue work as expected.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by talldan — APPROVED** [review]
As far as I can tell from looking at the history this has never worked, despite the docs explicitly saying it should. Thanks for fixing and adding the test.

File: packages/blocks/src/api/raw-handling/html-to-blocks.js [hunk 1]
```diff
@@ -19,7 +19,7 @@ export function htmlToBlocks( html ) {
 
 	doc.body.innerHTML = html;
 
-	return Array.from( doc.body.children ).map( ( node ) => {
+	return Array.from( doc.body.children ).flatMap( ( node ) => {
```
Comment (fluiddot) [inline packages/blocks/src/api/raw-handling/html-to-blocks.js:22]: 👋 I tested this changes in the native version and unfortunately the built-in version of `flatpMap` is not 100% supported (Android particularly).

Would it be possible to use the version from the `lodash` library instead? Do you foresee any inconvenience of using that version instead the built-in?

Thanks!

Comment (mirka) [reply packages/blocks/src/api/raw-handling/html-to-blocks.js:22]: Thanks for checking! 🙏

Using the lodash one instead should be fine, but I'm wondering whether our Babel config is intentionally leaving it unhandled. Could it have been an oversight in the [v7 migration](https://babeljs.io/docs/en/v7-migration#remove-proposal-polyfills-in-babelpolyfillhttpsgithubcombabelbabelissues8416)?

I'd think it would be safer if we relied on Babel to handle it, unless there's a project-wide preference to use lodash replacements for built-in functions. I'm not really familiar with the goings-on here though. Do you know?

Comment (mirka) [reply packages/blocks/src/api/raw-handling/html-to-blocks.js:22]: (Noting one more instance, in case we're going the lodash route.)

https://github.com/WordPress/gutenberg/blob/004a32ec09d5b789be694d85725fe49cca385f08/packages/edit-navigation/src/store/utils.js#L136

Comment (fluiddot) [reply packages/blocks/src/api/raw-handling/html-to-blocks.js:22]: > Using the lodash one instead should be fine, but I'm wondering whether our Babel config is intentionally leaving it unhandled. Could it have been an oversight in the v7 migration?

To be honest I'm not sure, the adoption of built-in `flatMap` is quite high (`91.18%` as checked in [caniuse.com](https://caniuse.com/mdn-javascript_builtins_array_flatmap)) and since it has been only used in one place maybe we haven't spotted this issue yet.

> (Noting one more instance, in case we're going the lodash route.)

Good catch! That part should be also incompatible with the native version but most likely it hasn't raised any issue because is not used (I need to check it).

I found interesting that this place was the only one where the built-in `flatMap` was being used so far, maybe as you commented, there's a project-wide preference to use `lodash`.
I'm not familiar neither with this since I'm working more in the native side but I'll ask for help.

Comment (youknowriad) [reply packages/blocks/src/api/raw-handling/html-to-blocks.js:22]: The poly fills are included separate in WordPress in a `wp-polyfill` package. I think that package is probably not included in native, should it be included?

Comment (fluiddot) [reply packages/blocks/src/api/raw-handling/html-to-blocks.js:22]: Yeah we would need to import and inject that package when generating the JS bundle for React native. Could you point me out where I can get that package? Thanks!

Comment (youknowriad) [reply packages/blocks/src/api/raw-handling/html-to-blocks.js:22]: Its setup is a bit complex, it's mainly composed of `babel-polypill` see https://github.com/WordPress/wordpress-develop/blob/master/package.json#L81

but it has other dependencies that are only loaded if the browser doesn't support them https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/script-loader.php#L122-L136

Comment (fluiddot) [reply packages/blocks/src/api/raw-handling/html-to-blocks.js:22]: Thanks @youknowriad for the info!

I'm going to try adding the `core-js` dependency to the `react-native-editor` package (the entry point for the native version) and import the polyfill for `flatMap` from `core-js/features/array/flat-map` as states in the [Babel documentation](https://babeljs.io/docs/en/v7-migration#remove-proposal-polyfills-in-babelpolyfillhttpsgithubcombabelbabelissues8416).

Comment (fluiddot) [reply packages/blocks/src/api/raw-handling/html-to-blocks.js:22]: Finally I've included the polyfill by adding `core-js` to the native package in this [PR](https://github.com/WordPress/gutenberg/pull/28400). In the future if we need to add new polyfills we'll have an entry point there.

Thanks @mirka and @youknowriad for checking this!

Comment (mirka) [reply packages/blocks/src/api/raw-handling/html-to-blocks.js:22]: Thanks for the quick fix @fluiddot 🙌
