### PR TITLE
Fix Inserter: Navigate between blocks with left/right

### LINKED ISSUE #3850: Inserter: Navigate between blocks with left/right
## Issue Overview
In the inserter you can navigate between blocks with the up/down arrow keys. It should also be possible to navigate with left/right arrow keys.

## Steps to Reproduce (for bugs)
1. Open the inserter, press tab to focus a block
2. Press the right arrow key

## Expected Behavior
focus the next block

## Current Behavior
focus stays on the first block

### PR DESCRIPTION
**Pull request by Soean**
## Description
To navigate in NavigableContainer you can now use orientation="both" and use the left/up keys for the previous item and right/down keys for the next item.

Fixes #3850

### CODE REVIEW

File: components/navigable-container/index.js [hunk 1]
```diff
@@ -124,18 +124,10 @@ export class NavigableMenu extends Component {
 		const eventToOffset = ( evt ) => {
 			const { keyCode } = evt;
 
-			const isVertical = orientation === 'vertical';
```
Comment (youknowriad) [inline components/navigable-container/index.js]: I guess this means the "orientation" prop is useless now and we should remove all its references (docs, code...).
I'm not against this personally, we just have to make sure it's something we want for all `NavigableContainer` usage

Comment (youknowriad) [reply components/navigable-container/index.js]: @jasmussen Are we ok with this change? It makes `left` and `up` / `down` and `right` work similarily in the inserter and the toolbar and the dropdowns?

Comment (Soean) [reply components/navigable-container/index.js]: I removed it in d4df52a, but not sure if it is needed anywhere.

Comment (jasmussen) [reply components/navigable-container/index.js]: Looking at the behavior in `master`, I do agree that it's a little weird that pressing _down_ goes _right_ (depending on where you are), whereas pressing _right_ does nothing. As such this _seems_ like a good change. But it also begs the question why down doesn't go down, and right doesn't go right. 

But it is the inserter, and there's a rich history in how we got here, so before I say anything definitive I'd love @afercia's thoughts.

Comment (afercia) [reply components/navigable-container/index.js]: We've received some feedback during WCUS contributor day while testing the inserter, same confusion about _which_ arrows where expected to work. I think the arrow navigation should allow three "modes", depending on the nature of the UI component:
- horizontal: LEFT and RIGHT to go previous and next horizontally, e.g. toolbars
- vertical: UP and DOWN to go previous and next vertically, e.g. single column menus
- both: "spatial" navigation where UP and LEFT go previous, and DOWN and RIGHT go next

And yes, in the Inserter I'd use "both" 🙂

Comment (youknowriad) [reply components/navigable-container/index.js]: @Soean Maybe instead of removing the "orientation" entirely, we keep it and add a third option "both" or "vertical-horizontal". That way we could enable this behavior in the inserter but still keep it as is for the BlockToolbar and the Dropdowns. The Dropdown should probably be only "vertical" while the block toolbar should be "horizontal". Thoughts?

Comment (Soean) [reply components/navigable-container/index.js]: @youknowriad I had a similar thought. In WAI-ARIA 1.1 is a new default value `undefined: The element's orientation is unknown/ambiguous.` https://www.w3.org/TR/wai-aria-1.1/#aria-orientation

File: editor/components/inserter/group.js [hunk 2]
```diff
@@ -77,7 +77,7 @@ export default class InserterGroup extends Component {
 		return (
 			<NavigableMenu
 				className="editor-inserter__category-blocks"
-				orientation="vertical"
+				orientation="undefined"
```
Comment (youknowriad) [inline editor/components/inserter/group.js]: Minor: I know this is the equivalent of the aria value, but it's weird. I'd prefer something like "all" personally

**Review by youknowriad — APPROVED** [review]
Can we have a unit test for this orientation?

Anyway, LGTM 👍

**Comment by Soean** [comment]
@youknowriad Thanks for your feedback. 
- I changed `undefined` to `both`, because there are just two directions.
- I added a test for `both`.
- I added `both` to the docs.

**Comment by youknowriad** [comment]
Nice, might be better to wait for the release before merging
