### PR TITLE
Fix: use WP_Theme_JSON_Gutenberg instead of WP_Theme_JSON class

### LINKED ISSUE #63421: Typo: use WP_Theme_JSON_Gutenberg instead of WP_Theme_JSON class
### Description

Gutenberg code should use the `WP_Theme_JSON_Gutenberg` class instead of the `WP_Theme_JSON` one.

### Step-by-step reproduction instructions

N/A

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress version: 6.5.5
- Gutenberg version: 18.7.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
- Fixes #63421
- Similar to #48648

Per `lib/README.md`, Gutenberg uses the `_Gutenberg` suffix for "evergreen" classes to ensure plugin users get the latest code even on older WordPress versions. 
More specically in this case we should reference in Gutenberg WP_Theme_JSON_Gutenberg instead of WP_Theme_JSON otherwise we will use core code instead of the Gutenberg while when we have Gutenberg it is expected that Gutenberg code is used

This PR does two simple changes
- Replace `WP_Theme_JSON` class references with `WP_Theme_JSON_Gutenberg` in plugin code
- Update PHPDoc type hints to use the correct Gutenberg variant class

## Testing
Do a general smoke testing to global styles.
Do some grepping to confirm we don't have any other WP_Theme_JSON usage.

### CODE REVIEW

File: lib/class-wp-theme-json-data-gutenberg.php [hunk 1]
```diff
@@ -16,7 +16,7 @@ class WP_Theme_JSON_Data_Gutenberg {
 	 * Container of the data to update.
 	 *
 	 * @since 6.1.0
-	 * @var WP_Theme_JSON
+	 * @var WP_Theme_JSON_Gutenberg
```
Comment (Mamaduka) [inline lib/class-wp-theme-json-data-gutenberg.php]: I would probably leave similar comments in place, as it makes it easier to diff backports.

**Review by Mamaduka — APPROVED** [review]

File: lib/class-wp-theme-json-data-gutenberg.php (hunk 1 above)
Comment (jorgefilipecosta) [reply lib/class-wp-theme-json-data-gutenberg.php]: Good point I reverted this change.
