### PR TITLE
Fix navigation link ui close focus management

### LINKED ISSUE #58820: Navigation Link: Handle focus when removing the block
## What problem does this address?
In https://github.com/WordPress/gutenberg/pull/57756 we added an `onClose` event to the LinkUI, which removes the block when the popover closes if the URL is empty. We need to work out how best to handle focus in this scenario.

## What is your proposed solution?
We could return focus to the block, or to the inserter.

### PR DESCRIPTION
**Pull request by jeryj**
Fixes https://github.com/WordPress/gutenberg/issues/58820

## What?

Focus when closing the link ui has not been managed. This PR fixes focus loss from:
- New link (+ appender) -> Escape (doesn't create link) -> Focuses closest sibling (adjacent or parent or navigation block)
- New link (+ appender) -> Create link -> Focuses the newly created navigation item
- Edit link ( primary + k) -> Escape -> Focuses navigation link item 
- Editing link from toolbar -> Focus sent back to link toolbar item
- Empty link click or primary + k -> Focuses navigation link item 
- All the same scenarios for submenus as well
- Bonus: Fixes an issue where having a url-like menu item will always be selected when the popover closes, instead of only on create

It also adds an extensive e2e test that checks for focus management and being able to create, use the link control, and delete navigation items and submenu items.

## Why?

Accessibility, focus management. There were severe focus loss issues across the navigation block, especially when using the link control popover.

## How?

Adds openedBy state to navigation-link and submenu components and handles the various situations.

## Testing Instructions for Keyboard

Check for focus loss when interacting with the navigation block link ui only using your keyboard
- New link (+ appender) -> Escape (doesn't create link) -> Focuses closest sibling (adjacent or parent or navigation block)
- New link (+ appender) -> Create link -> Focuses the newly created navigation item
- Edit link ( primary + k) -> Escape -> Focuses navigation link item 
- Editing link from toolbar -> Focus sent back to link toolbar item
- Empty link click (Add label) or primary + k -> Focuses navigation link item 
- All the same scenarios for submenu items as well as submenu parents

For the navigation label selection issue:
- Create a link like "https//example.com"
- example.com label should be selected when closing the popover using Escape
- deselect the text
- Open the link popover again 
- Escape to close it
- example.com should not be selected

## Screenshots or screencast 
This video shows all the steps in the "navigation manages focus for creating, editing, and deleting items" test in slowMo mode:

https://github.com/WordPress/gutenberg/assets/967608/ec52f469-1f23-4a7e-8535-e7dcb026eee7

### CODE REVIEW

File: packages/block-library/src/navigation-link/edit.js [hunk 1]
```diff
@@ -93,7 +90,7 @@ const useIsDraggingWithin = ( elementRef ) => {
 			ownerDocument.removeEventListener( 'dragend', handleDragEnd );
 			ownerDocument.removeEventListener( 'dragenter', handleDragEnter );
 		};
-	}, [] );
+	}, [ elementRef ] );
```
Comment (jeryj) [inline packages/block-library/src/navigation-link/edit.js:93]: Linting

File: packages/block-library/src/navigation-link/edit.js [hunk 2]
```diff
@@ -226,7 +229,7 @@ export default function NavigationLinkEdit( {
 	/**
 	 * Transform to submenu block.
 	 */
-	function transformToSubmenu() {
+	const transformToSubmenu = () => {
```
Comment (jeryj) [inline packages/block-library/src/navigation-link/edit.js:232]: Linting

File: packages/block-library/src/navigation-link/edit.js [hunk 3]
```diff
@@ -269,20 +272,18 @@ export default function NavigationLinkEdit( {
...
-				// Focus it (but do not select).
-				placeCaretAtHorizontalEdge( ref.current, true );
-			}
+		// We only want to do this when the URL has gone from nothing to a new URL AND the label looks like a URL
+		if (
+			! prevUrl &&
+			url &&
+			isLinkOpen &&
+			isURL( prependHTTP( label ) ) &&
+			/^.+\.[a-z]+/.test( label )
```
Comment (jeryj) [inline packages/block-library/src/navigation-link/edit.js:281]: We only want the label text to be selected if we add a link with a custom url like https://www.example.com. Previously, this would select the label text _every_ time the link popover closed, not just when the link was created. We only want this to happen when the link is created.

File: packages/block-library/src/navigation-link/edit.js [hunk 4]
```diff
@@ -269,20 +272,18 @@ export default function NavigationLinkEdit( {
...
-			// Does this look like a URL and have something TLD-ish?
-			if (
-				isURL( prependHTTP( label ) ) &&
-				/^.+\.[a-z]+/.test( label )
-			) {
-				// Focus and select the label text.
-				selectLabelText();
-			} else {
-				// Focus it (but do not select).
-				placeCaretAtHorizontalEdge( ref.current, true );
```
Comment (jeryj) [inline packages/block-library/src/navigation-link/edit.js:282]: We want the caret to go back to wherever it was. We shouldn't assume it to go to the start.

File: test/e2e/specs/editor/blocks/navigation.spec.js [hunk 5]
```diff
@@ -290,6 +313,220 @@ test.describe( 'Navigation block', () => {
 		await expect( warningMessage ).toBeVisible();
 	} );
 
+	test( 'creating navigation menus via keyboard without losing focus', async ( {
```
Comment (jeryj) [inline test/e2e/specs/editor/blocks/navigation.spec.js]: This test is huge, but it's better that it is:
- Faster than running it in several smaller tests
- We don't need to "redo" work in each test. For example, each test needs to build off the previous one, so there would either be repeating tests or lots of initial menus to start from.
- Creating a navigation block using a keyboard should work. This is a more realistic example of creating a menu and is more likely to catch edge cases.

I tried to break it down into sensible smaller tests, and refactor reusable pieces but keep them readable. I wrote this with the idea that it will likely need to be debugged since I expect focus management bugs to happen. When we debug it or change the implementation, my intent is that this will be easier to understand and maintain.

**Review by scruffian — APPROVED** [review]
I tested this and it works as described. The code makes sense too.

File: packages/block-library/src/navigation-link/edit.js [hunk 6]
```diff
@@ -565,10 +573,24 @@ export default function NavigationLinkEdit( {
 								// If there is no link then remove the auto-inserted block.
 								// This avoids empty blocks which can provided a poor UX.
 								if ( ! url ) {
-									// Need to handle refocusing the Nav block or the inserter?
+									// Select the previous block to keep focus nearby
+									selectPreviousBlock( clientId, true );
```
Comment (t-hamano) [inline packages/block-library/src/navigation-link/edit.js:577]: Perhaps this line is causing the main inserter to not open when you click the "Browse All" button (See #61361).

My guess is that this occurs for the following reasons:

- The main inserter opens when "Browse All" is clicked ([See](https://github.com/WordPress/gutenberg/blob/76851ca1dd07eabe5aba30c1912e29190d26e60f/packages/block-editor/src/components/inserter/quick-inserter.js#L84-L88)).
- `onClose` is called because the focus leaves the popover.
- Since the URL does not exist, this part will be executed and the previous block will be selected.
- The main inserter automatically closes because the block is selected.

I don't understand everything about this PR, but I would suggest [not binding `onSelectBlock` directly to the popover component's `onClose` prop](https://github.com/WordPress/gutenberg/blob/76851ca1dd07eabe5aba30c1912e29190d26e60f/packages/block-library/src/navigation-link/link-ui.js#L211-L213). It might be better to clearly separate `onClose` and `onSelectBlock`, and only move the focus to the previous block when `onSelectBlock` is called.

I haven't tested it thoroughly, but the code below works fine as far as I've tested it. I hope this helps.

```diff
diff --git a/packages/block-library/src/navigation-link/edit.js b/packages/block-library/src/navigation-link/edit.js
index 4902a6cb2b..cb89881f79 100644
--- a/packages/block-library/src/navigation-link/edit.js
+++ b/packages/block-library/src/navigation-link/edit.js
@@ -562,6 +562,15 @@ export default function NavigationLinkEdit( {
                                                        clientId={ clientId }
                                                        link={ attributes }
                                                        onClose={ () => {
+                                                               // When onClose is called, it means that the "Browse all" button
+                                                               // was clicked and the main inserter was opened. In this case,
+                                                               // remove the empty block and close the link UI. It does not return
+                                                               // focus to the previous block to prevent the main inserter from
+                                                               // closing.
+                                                               onReplace( [] );
+                                                               setIsLinkOpen( false );
+                                                       } }
+                                                       onSelectBlock={ () => {
                                                                // If there is no link then remove the auto-inserted block.
                                                                // This avoids empty blocks which can provided a poor UX.
                                                                if ( ! url ) {
diff --git a/packages/block-library/src/navigation-link/link-ui.js b/packages/block-library/src/navigation-link/link-ui.js
index ce79af40e4..64a742e776 100644
--- a/packages/block-library/src/navigation-link/link-ui.js
+++ b/packages/block-library/src/navigation-link/link-ui.js
@@ -208,10 +208,6 @@ export function LinkUI( props ) {
                `link-ui-link-control__description`
        );
 
-       // Selecting a block should close the popover and also remove the (previously) automatically inserted
-       // link block so that the newly selected block can be inserted in its place.
-       const { onClose: onSelectBlock } = props;
-
        return (
                <Popover
                        placement="bottom"
@@ -291,7 +287,7 @@ export function LinkUI( props ) {
                                                setAddingBlock( false );
                                                setFocusAddBlockButton( true );
                                        } }
-                                       onSelectBlock={ onSelectBlock }
+                                       onSelectBlock={ props.onSelectBlock }
                                />
                        ) }
                </Popover>
```

Comment (jeryj) [reply packages/block-library/src/navigation-link/edit.js:577]: Thanks for noticing and debugging this, @t-hamano! The onClose is all work-arounds for focus management, as we couldn't work out a cleaner way to return focus to the + inserter when closing it. [This test covers a lot of scenarios to help show what the onClose code does](https://github.com/WordPress/gutenberg/blob/trunk/test/e2e/specs/editor/blocks/navigation.spec.js#L318). The diff you shared does make the inserter work again, but breaks the focus management. I'm not sure how to keep them both working consistently. Maybe there's a way to tell the onClose to return early if we're opening the all blocks inserter panel?

Comment (t-hamano) [reply packages/block-library/src/navigation-link/edit.js:577]: Yes, when I made this change locally and ran the E2E tests, some tests failed 😅 There may be a better approach.

File: test/e2e/specs/editor/blocks/navigation.spec.js [hunk 7]
```diff
@@ -290,6 +313,215 @@ test.describe( 'Navigation block', () => {
...
+		await navigation.checkLabelFocus( 'Cat' );
+		// Deleting with no more siblings should focus the navigation block again
+		await pageUtils.pressKeys( 'access+z' );
+		await expect( navBlock ).toBeFocused();
+		// Wait until the nav block inserter is visible before we continue.
+		await expect( navBlockInserter ).toBeVisible();
+		// Now the appender should be visible and reachable with an arrow down
+		await pageUtils.pressKeys( 'ArrowDown' );
+		await expect( navBlockInserter ).toBeFocused();
+	} );
```
Comment (ellatrix) [inline test/e2e/specs/editor/blocks/navigation.spec.js:523]: Does this have to be one big test? It's nice to split things into smaller tests if possible, it's quite overwhelming to debug.

Comment (t-hamano) [reply test/e2e/specs/editor/blocks/navigation.spec.js:523]: I think it can certainly be splitted. I submitted #64305.
