### PR TITLE
Fix autocomplete keyboard nav in link popover

### LINKED ISSUE #10689: Insert Link: up/down arrow in link autocomplete crashes block
**Describe the bug**
Pressing the up or down arrow in the link autocomplete field crashes the block

**To Reproduce**
1. In a paragraph, select text
2. Click add link
3. Search to trigger the autocomplete dropdown
4. Press the up or down arrow key (regardless of whether the autocomplete suggestions is above or below)

**Expected behavior**
Up or down arrow key should move focus to an item on the list of suggestions.

I saw issue #10496 with the fix #10500 should be included in 4.0 (was it?), but clicking an autocomplete suggestion doesn't insert a link, it just selects a block or two.

With neither mouse or keyboard selection working, it's not possible to insert link using the autocompleter.

**Screenshots**
screenshot 22
screenshot 23

**Console error**
```
TypeError: Cannot read property 'body' of undefined
    at index.js?ver=1539782380:12
    at s (index.js?ver=1539782380:12)
    at Object.offset (index.js?ver=1539782380:12)
    at e.exports (index.js?ver=1539782380:12)
    at t.value (index.js?ver=1539782380:50)
    at jc (react-dom.min.82e21c65.js:134)
    at gc (react-dom.min.82e21c65.js:127)
    at vb (react-dom.min.82e21c65.js:126)
    at ub (react-dom.min.82e21c65.js:126)
    at wg (react-dom.min.82e21c65.js:137)
```

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version WP 4.9.8, GB 4.0

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #10689

Resolves a regression caused by #10500:
- #10500 changed the type of ref in the URLInput to a `createRef`. To access the underlying element with a createRef, `ref.current` must be used, but an instance of this was missed in that change, causing `scrollIntoView` to throw an error:
https://github.com/WordPress/gutenberg/compare/fix/autocomplete-keyboard-nav-in-link?expand=1#diff-95b4cd296d28092a0710c1d98aee45d8R49

- On further testing, there was also an issue with using the escape key not closing the url input. This was caused by `event` being undefined in the `resetState` method when called from a couple of callsites. The fix for this was to extract a separate onClickOutside handler:
https://github.com/WordPress/gutenberg/compare/fix/autocomplete-keyboard-nav-in-link?expand=1#diff-3fc799f44a8120d79cc3867b1d703822R179

## How has this been tested?
- Manual Testing
- e2e tests added for both issues

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: packages/editor/src/components/url-input/index.js [hunk 1]
```diff
@@ -46,7 +46,7 @@ class URLInput extends Component {
 		// when already expanded
 		if ( showSuggestions && selectedSuggestion !== null && ! this.scrollingIntoView ) {
 			this.scrollingIntoView = true;
-			scrollIntoView( this.suggestionNodes[ selectedSuggestion ], this.autocompleteRef, {
+			scrollIntoView( this.suggestionNodes[ selectedSuggestion ], this.autocompleteRef.current, {
```
Comment (noisysocks) [inline packages/editor/src/components/url-input/index.js]: Doh! 🤦‍♂️

**Review by noisysocks — APPROVED** [review]
Thanks for staying on top of this and for getting a fix up so fast! 🙌

This fixes the bug for me locally and I'm not seeing any regressions. Glad that our war chest of link E2E tests is getting a little bit bigger with each passing day.

One thing I just noticed is that there's an inconsistency between using the keyboard and using the mouse. When you use the keyboard, the link is immediately inserted and you are no longer in _link edit mode_. When you use the mouse, the URL is inserted but you remain in _link edit mode_.

Would be good to address that, but I don't think it's a blocker.

**Comment by gziolo** [comment]
Let's get it in as it's better than what we had before. We have whole RC cycle to improve it :)
