### PR TITLE
Fix:Image Block: Hide 'noreferrer' and 'noopener' in Link Rel

### LINKED ISSUE #15915: Rel attribute: the UI doesn't display the actual set values
Noticed while testing #10128 and it applies to all the links "Rel" attribute fields.

For example, testing on the Image block > Sidebar > Link Settings and playing with "Open in New Tab" and "Link Rel".

Tested steps:

Click "Open in New Tab": noreferrer and noopener values are added to the "Link Rel" field:

Screenshot 2019-05-30 at 10 28 11

OR: enter a custom value:

Screenshot 2019-05-30 at 10 29 13

In both cases the values displayed in the UI and the ones rendered in the front end match. So far so good.

### Enter a custom value _and then_ click "Open in New Tab":
- save
- the UI displays only the custom value
- values on the front end are correct: `myrel noopener noreferrer`

custom + open in new tab

Refresh the page: displayed values are now correct: `myrel noopener noreferrer`

### Click "Open in New Tab" to disable it:
- the UI still displays all the three values `myrel noopener noreferrer`

Screenshot 2019-05-30 at 11 59 04

### Reset everything, restart from scratch: click "Open in New Tab" _and then_ add a custom value:
- save
- the UI displays all the three values and values in the front end are correct 

open in new tab + custom

### Click "Open in New Tab" to disable it:
- save
- the UI still displays all the three values `noreferrer noopener mynewrel`
- values in the front end are still `noreferrer noopener mynewrel`

remove open in new tab

### Recap
There are probably more flows that produce incorrect / mismatched values. Trying to summarize:
- The UI may display incorrect values.
- Values in the front end may be incorrect, especially in combination with the target attribute value. For example there are cases where `target="_blank"` is not rendered but `rel="noreferrer noopener myrel"` is, which is incorrect
- In some cases an empty `rel=""` is rendered, which is a bit pointless

### Thoughts
- I'm not sure the Rel field should display the `noreferrer noopener` values to start with
- From a UI perspective, I'd say "Open in New Tab" and the Rel field should be close each other. Having the CSS class field in between doesn't help users understand these two fields are related.

### PR DESCRIPTION
**Pull request by donmhico**
## Description
1. Hide the 'noreferrer' and 'noopener' in Link Rel field if "Open in New Tab" is toggled on.
2. Do not display empty rel attribute in frontend.
3. Move the Link Rel field below the "Open in New Tab" toggle.

## How has this been tested?
Followed the steps in #15915.

## Types of changes
Fixes #15915.

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style.

### CODE REVIEW

File: packages/block-library/src/image/edit.js [hunk 1]
```diff
@@ -333,6 +334,25 @@ export class ImageEdit extends Component {
...
 	}
 
+	removeNewTabRel( currentRel ) {
+		let newRel = currentRel;
+
+		if ( currentRel !== undefined && ! isEmpty( newRel ) ) {
+			if ( ! isEmpty( newRel ) ) {
+				each( NEW_TAB_REL, function( relVal ) {
+					const regExp = new RegExp( '\\s?\\b' + relVal + '\\b\\s?', 'gi' );
+					newRel = newRel.replace( regExp, '' );
```
Comment (jorgefilipecosta) [inline packages/block-library/src/image/edit.js]: I think we should improve this logic for example if we set rel to `"mycustom1 noreferrer noopener"` this PR shows rel as `"mycustom1noopener"` ( not the default order needs to be manually set), what happens is that the replace removes the first noreferrer and removes all the spacing then the noopener replace does not happen.
I think we can fix this in an easy way by replacing with space instead of an empty string and then perform a trim to remove spaces added on the end or start of the line.

**Review by jorgefilipecosta — COMMENTED** [review]
Thank you @donmhico for submitting this PR 👍 I think the path it is following is a good one we should not show noreferrer noopener to users as even if they remove them WordPress would re-add them.
The PR seems mostly ready I just left a small suggestion.

File: packages/block-library/src/image/edit.js [hunk 2]
```diff
@@ -340,10 +340,15 @@ export class ImageEdit extends Component {
...
-					const regExp = new RegExp( '\\s?\\b' + relVal + '\\b\\s?', 'gi' );
+					const regExp = new RegExp( '\\b' + relVal + '\\b', 'gi' );
 					newRel = newRel.replace( regExp, '' );
 				} );
 
+				// Only trim if NEW_TAB_REL values was replaced.
+				if ( newRel !== currentRel ) {
+					newRel = newRel.trim();
+				}
+
```
Comment (donmhico) [inline packages/block-library/src/image/edit.js]: Thanks for the comment @jorgefilipecosta. This new commit basically has 2 changes.

1. Changed the regex used. I realized that `\b` is enough if we're gonna trim the spaces as well.
2. Trim the resulting rel if a NEW_TAB_REL ('noreferrer', 'noopener') was removed. This is because without this check, it's not possible to type multiple words in the Link Rel field since the whitespace is always trimmed.

Honestly, I think we can find a better solution like the removal of NEW_TAB_REL values should just happen on save. I'll try to look into it more when time permits.

@jorgefilipecosta - Let me know if your tests with this new changes are good.

**Review by jorgefilipecosta — APPROVED** [review]
I rebased this PR and applied some post rebase fixes. But everything seems to be working. Thank you @donmhico for this enhancement.
