### PR TITLE
Query Loop: Fix posts list variation detection

### LINKED ISSUE #58168: Query Loop variations in Core are not detected as active
Steps to reproduce:

Insert the "Posts List" block, which is a variation of Query Loop:

Screenshot 2024-01-24 at 10 03 47

What I expected:
1. The name of the block in the List View in the sidebar is "Posts List", not "Query Loop".
2. After clicking on "Choose" to choose a pattern, the available patterns are searched for `blockTypes` support for `core/query/posts-list` specifically.

But none of that happens, the active variation is not detected by the `getActiveBlockVariation` selector. That's because the `core/query` variations shipped by Core have no `isActive` function.

This functionality was implemented by @ntsekouras in #44197, but for the Core Query Loop block and its variations it doesn't work. On the other hand, Woo ships a "Products Query" variation of `core/query` which implements `isActive` correctly and is detected.

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/58168

Core Query Loop's variation `posts list` was missing a proper way of being detected if is active(by not using the `isActive` API). The reason for that is that the aforementioned API was introduced later.

This PR uses the proper APIs for variations and additionally removes the `__experimentalGetMatchingVariation`(that you could say it evolved into the `getActiveBlockVariation`).

## Testing Instructions
1. Existing Query Loop blocks should remain intact
2. Insert a `Posts List` block(the variation) and observe that as long as you also preserve the queried postType to be `post`, the proper title is shown in all places(list view, block card, breadcrumbs, etc..)

## Bonus testing
1. Register a block patterns with `blockTypes: ['core/query/posts-list'] and when you insert the block in the editor click `Choose`. Your pattern should be suggested.

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]
🚢

File: packages/block-library/src/query/variations.js [hunk 1]
```diff
@@ -53,6 +54,9 @@ const variations = [
 			},
 		},
 		scope: [ 'inserter' ],
+		isActive: ( { namespace, query } ) => {
+			return namespace === 'core/posts-list' && query.postType === 'post';
+		},
 	},
 	{
 		name: 'title-date',
```
Comment (jsnajdr) [inline packages/block-library/src/query/variations.js:62]: The other variations like Title & Date or Title & Excerpt, would they benefit from `isActive`, too?

Comment (ntsekouras) [reply packages/block-library/src/query/variations.js:62]: No, because they use the `scope: [ 'block' ]`, which is used for the placeholder and they essentially are there to add some starting inner blocks.

**Review by jsnajdr — APPROVED** [review]
Nice, thanks for a quick fix :+1:
