### PR TITLE
Fix column moved in itself error

### LINKED ISSUE #13701: Column block can be moved in itself
**Describe the bug**
I moved accidentally the column block in itself. The editor crashes an error message I can't fully read because it redirects me to "about:blank".

**To Reproduce**
1. Add column block
2. Do not add any blocks to the columns
3. Move the column block in one of the column spaces
4. BOOM.

**Expected behavior**
I should not be able to move the column block in itself.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Browser: Firefox
 - Version 65

**Additional context**
WordPress 5.0.3

### PR DESCRIPTION
**Pull request by Naerriel**
## Description
Closes: #13701
The bug is that empty column has no children and `dstClientId` was `undefined`, therefore it could not be recognized as moved block's child.

In solution I assumed that each 2 blocks that can be moved in each other are always separated by a `core/column` block. 

If that assumption is incorrect or unsustainable I can leave:
```jsx
  isSrcBlockAnAncestorOfDstBlock( srcClientId, dstClientId )
```
and just add:
```jsx
  isSrcBlockAnAncestorOfDstBlock( srcClientId, dstRootClientId )
```
along the previous version.

## How has this been tested?
1. Create new column block.
2. Drag it to second column.
3. See that it doesn't crash.

## Types of changes
Bug fix

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style. 
- [X] My code follows the accessibility standards. 
- [X] My code has proper inline documentation. 
- [X] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/editor/src/components/block-drop-zone/index.js [hunk 1]
```diff
@@ -98,7 +98,7 @@ class BlockDropZone extends Component {
 
 		if ( ! isBlockDropType( type ) ||
 			isSameBlock( srcClientId, dstClientId ) ||
-			isSrcBlockAnAncestorOfDstBlock( srcClientId, dstClientId ) ) {
+			isSrcBlockAnAncestorOfDstBlock( srcClientId, dstRootClientId ) ) {
```
Comment (talldan) [inline packages/editor/src/components/block-drop-zone/index.js]: I think the logic is sound `dstClientId` is undefined when the column only contains the default appender, so the root needs to be used as a fallback.

In that case how about the following suggestion so that the previous behaviour is preserved when there is a `dstClientId`?
```suggestion
			isSrcBlockAnAncestorOfDstBlock( srcClientId, dstClientId || dstRootClientId ) ) {
```

**Review by talldan — APPROVED** [review]
Gave this a further test, it works well. I tried a few different blocks with inner blocks including third-party ones from the coblocks and stackable plugins. All were prevented from being dragged inside themselves 😄 

Also confirmed that normal dragging and dropping still works.

**Comment by gziolo** [comment]
Good job @Naerriel, keep up great work 🥇
