### PR TITLE
Grid Interactivity: Fix block mover layout and styles

### LINKED ISSUE #64017: Grid interactivity: Mover layout and styling issues
### Description

When the experimental "Grid interactivity" setting is enabled and a grid block is in manual mode, the mover buttons in the block toolbar are not displayed correctly.

### Step-by-step reproduction instructions

> Enable "Grid interactivity" setting in the Experimental settings page.
> Insert a Grid block.
> Change "Grid Imte Position" setting to "Manual"
> Select a grid item block.

### "Show button text labels" is enabled

- Some border colors are incorrect if the "Move left" or "Move right" button is disabled.

image

### "Show button text labels" is disabled

- The "Move up" and "Move down" buttons are in the wrong position.

image

### "Show button text labels" is enabled

- The "Move up" and "Move down" buttons are in the wrong position.
- Some border colors are incorrect if the "Move left" or "Move right" button is disabled.

image

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #64017

## What?

This PR fixes the block movers layout and style when the experimental "Grid interactivity" setting is enabled and a grid block is in manual mode,

## Why?

The core mover buttons determine their layout and style taking into account scenarios such as browser width, whether Top Toolbar is enabled, whether "Show button text labels" is enabled, etc. I believe similar logic is needed for the mover buttons for grid blocks.

## How?

I applied the same logic as the core mover button, details are commented inline.

## Testing Instructions

We need to test the following scenarios:

- Mobile viewport:
  - "Show button text labels" is disabled
  - "Show button text labels" is enabled
- Tablet viewport:
  - "Show button text labels" is disabled
  - "Show button text labels" is enabled
- Desktop viewport:
  - "Show button text labels" is disabled
    - "Top toolbar" is disabled
    - "Top toolbar" is enabled
  - "Show button text labels" is enabled
    - "Top toolbar" is disabled
    - "Top toolbar" is enabled

For each of these scenarios, make sure that:

- Border colors are consistent across the block toolbar
- Borders are the correct length and position
- Mover buttons themselves are properly positioned
- When focused on a button, the outline is the correct size

### Before

https://github.com/user-attachments/assets/d49a8a0a-10cc-403a-b657-f86c1017fcbc

### After

https://github.com/user-attachments/assets/5c39da95-6ccd-49fb-a451-5acbb7a4b3eb

### CODE REVIEW

File: packages/block-editor/src/components/block-mover/index.js [hunk 1]
```diff
@@ -69,7 +69,11 @@ function BlockMover( {
 		[ clientIds ]
 	);
 
-	if ( ! canMove || ( isFirst && isLast && ! rootClientId ) ) {
+	if (
+		! canMove ||
+		( isFirst && isLast && ! rootClientId ) ||
+		( hideDragHandle && isManualGrid )
+	) {
```
Comment (t-hamano) [inline packages/block-editor/src/components/block-mover/index.js:76]: Prevents a `ToolbarGroup` component that has no children from being rendered.

File: packages/block-editor/src/components/grid/grid-item-movers.js [hunk 2]
```diff
@@ -55,28 +55,29 @@ export function GridItemMovers( {
...
-							gridClientId,
-							gridClientId,
-							getNumberOfBlocksBeforeCell(
-								columnStart - 1,
-								rowStart
-							)
-						);
-					} }
-				/>
+				<div className="block-editor-grid-item-mover__move-horizontal-button-container is-left">
```
Comment (t-hamano) [inline packages/block-editor/src/components/grid/grid-item-movers.js:58]: For the toolbar button, the `::before` pseudo-element is used for the focus outline and the `:::after` pseudo-element is used for the text when "Show button text labels" is enabled.

I wrapped the button in a `div` to render a border as a pseudo-element.

File: packages/block-editor/src/components/grid/style.scss [hunk 3]
```diff
@@ -105,7 +105,6 @@
 	.block-editor-grid-item-mover-button {
 		width: $block-toolbar-height * 0.5;
 		min-width: 0 !important; // overrides default button width.
-		overflow: hidden;
```
Comment (t-hamano) [inline packages/block-editor/src/components/grid/style.scss:108]: To fix incorrect focus outline

image

File: packages/block-editor/src/components/grid/style.scss [hunk 4]
```diff
@@ -173,18 +172,53 @@
...
+.editor-collapsible-block-toolbar {
+	.block-editor-grid-item-mover__move-vertical-button-container {
+		// Move up a little to prevent the toolbar shift when focus is on the vertical movers.
+		@include break-small() {
+			height: $grid-unit-50;
+			position: relative;
+			top: -5px; // Should be -4px, but that causes scrolling when focus lands on the movers, in a 60px header.
+		}
+	}
+}
```
Comment (t-hamano) [inline packages/block-editor/src/components/grid/style.scss:184]: Similar to [this approach](https://github.com/WordPress/gutenberg/blob/159d01a01b61ee76159ab67bc94d0d7cb3d90b35/packages/editor/src/components/collapsible-block-toolbar/style.scss#L65-L72) for the default block mover. the `.editor-collapsible-block-toolbar` selector is used to determine that the Top Toolbar is enabled.

File: packages/block-editor/src/components/grid/style.scss [hunk 5]
```diff
@@ -208,5 +242,21 @@
 		}
 	}
 
+	.block-editor-grid-item-mover-button {
+		white-space: nowrap;
```
Comment (t-hamano) [inline packages/block-editor/src/components/grid/style.scss:246]: To prevent text wrapping when the "Show button text labels" is enabled

image

**Review by noisysocks — APPROVED** [review]
This works great! Thanks for the attention to detail and excellent PR description / inline comments.

**Comment by noisysocks** [comment]
I recently tidied up the list of tasks in https://github.com/WordPress/gutenberg/issues/57478 if you'd like to keep working on Grid 😀

**Comment by t-hamano** [comment]
Thanks for the review! 
> I recently tidied up the list of tasks in https://github.com/WordPress/gutenberg/issues/57478 if you'd like to keep working on Grid

I'll try to find a task that I can tackle 👍
