### PR TITLE
Fix crash when null date passed to TimePicker

### LINKED ISSUE #27246: Time format error using `H:i` format in the editor’s datepicker
**Describe the bug**
See the related ticket: https://core.trac.wordpress.org/ticket/51862

**To reproduce**
1. Open the [Settings]-[General] menu.
2. Select "H:i" in Time Format and save.
3. Edit "Hello world!" In the posted article.
4. Click the date and time in "Publish" of "Status & visibility".
5. Click "Reset" in the displayed calendar.
6. Click "Immediately".
7. Clicking "Date" or "Calendar Help" in the calendar causes an error.

Error: 
```
TypeError: r is not a function
    at http://localhost:8888/wordpress-develop/wordpress-develop/build/wp-includes/js/dist/components.min.js?ver=7b2eb7033cd3c6d2b4ea663e7d4774a7:7:311452
    at Bh (http://localhost:8888/wordpress-develop/wordpress-develop/build/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:126:456)
    at Dj (http://localhost:8888/wordpress-develop/wordpress-develop/build/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:162:476)
    at unstable_runWithPriority (http://localhost:8888/wordpress-develop/wordpress-develop/build/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25:260)
    at Da (http://localhost:8888/wordpress-develop/wordpress-develop/build/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60:280)
    at xb (http://localhost:8888/wordpress-develop/wordpress-develop/build/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:162:231)
    at mk.Events.current (http://localhost:8888/wordpress-develop/wordpress-develop/build/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236:102)
    at Ei (http://localhost:8888/wordpress-develop/wordpress-develop/build/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41:59)
```
**Editor version (please complete the following information):**
- WordPress version: WP 5.6 RC 1
- Using default block editor, no plugin

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by tellthemachines**
## Description

Fixes #27246 
Adds a sad path test to check that a date and time is always output even if the component receives `null` as currentTime. This is needed as the reset function sets the date/time to null. 

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/components/src/date-time/test/time.js [hunk 1]
```diff
@@ -271,4 +271,28 @@ describe( 'TimePicker', () => {
...
+		const dayInput = screen.getByLabelText( 'Day' ).value;
+		const yearInput = screen.getByLabelText( 'Year' ).value;
+		const hoursInput = screen.getByLabelText( 'Hours' ).value;
+		const minutesInput = screen.getByLabelText( 'Minutes' ).value;
+
+		expect( isNaN( monthInput ) ).toBe( false );
+		expect( isNaN( dayInput ) ).toBe( false );
+		expect( isNaN( yearInput ) ).toBe( false );
+		expect( isNaN( hoursInput ) ).toBe( false );
+		expect( isNaN( minutesInput ) ).toBe( false );
```
Comment (kevin940726) [inline packages/components/src/date-time/test/time.js:296]: Nitpicking: Prefer using [`Number.isNaN`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN) here as it's a more robust version. It shouldn't matter in this case though 😅.

**Review by kevin940726 — APPROVED** [review]
LGTM! Just a nitpick.

File: packages/components/src/date-time/test/time.js (hunk 1 above)
Comment (tellthemachines) [reply packages/components/src/date-time/test/time.js:296]: I deliberately used `isNaN` because `Number.isNaN` will return false for any string. We need to check that the value is either a number, or a string that can be parsed into a number, as opposed to something like 'invalid date'. The problem with this approach is that it won't catch an empty string or a `null` value, but that won't change even if we use `Number.isNaN`. It might be worth calling `parseInt` on those variables to make sure anything that's not a number is actually flagged as a NaN 😅

Comment (tellthemachines) [reply packages/components/src/date-time/test/time.js:296]: ... and in that case we _can_ use `Number.isNaN` 😸
