### PR TITLE
Writing flow: allow paste on multiple selected blocks

### LINKED ISSUE #17931: Pasting content while blocks are selected should overwrite selected blocks
**Description**
Pasting content while blocks are selected should overwrite the selected blocks. Right now, copying on selected blocks just copies the pasted content under the selected blocks.

**To reproduce**
Select blocks in the Gutenberg post editor, paste content

**Expected behavior**
Pasted content should overwrite the selected content.

I believe this feature is essential and goes together with the block-style editing that Gutenberg offers. Overwriting is also key feature of copypasting and would have been possible in the Classic Editor.

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #17931.

Currently pasting on multiple selected blocks is buggy. It will leave the selected blocks and split one of them, pasting the content between the split pieces. This is because `RichText` is handling paste. Instead, the block editor should handle paste.

Adds e2e tests. Until now we did not have any e2e test for cut/copy/paste.

## How has this been tested?

Select multiple blocks and paste.
Select a single block without putting focus somewhere and paste.

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

File: packages/block-editor/src/utils/get-paste-event-data.js [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+	} catch ( error1 ) {
+		try {
+			html = clipboardData.getData( 'Text' );
+		} catch ( error2 ) {
+			// Some browsers like UC Browser paste plain text by default and
+			// don't support clipboardData at all, so allow default
+			// behaviour.
+			return;
+		}
+	}
```
Comment (mcsf) [inline packages/block-editor/src/utils/get-paste-event-data.js]: This is a super thorough block in terms of browser support :), what did you base it on?

**Review by mcsf — APPROVED** [review]
This feels really nice! Let's get it in!

File: packages/block-editor/src/utils/get-paste-event-data.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-editor/src/utils/get-paste-event-data.js]: Some of this is actually a copy from rich text. :) We'll need to find a way to allow this function to be reused.
