### PR TITLE
Font Library Modal: Reset the selected font when installing a new font

### LINKED ISSUE #54945: Font Library: Variant list does not update immediately following upload of new variant
### Description

On the font management Library tab, a font variant's detail list is not updated immediately following upload of a new variant to that same font. I expect the variant list to include newly uploaded variants when switching from the Upload tab to Library.

Note that the variant list does update _after_ navigating back to the full registered fonts list and re-entering the font detail screen.

### Step-by-step reproduction instructions

1. Open the font management modal.
2. In the Upload tab, add a single variant of a new font, and confirm the upload succeeded.
3. Click the Library tab, noting "1/1 variants" for the newly added font.
4. Click into the font's variant detail list, noting the single variant that was added.
5. Click the Upload tab, and add a different variant for that same font, and confirm the upload succeeded.
6. Click the Library tab, noting that the new variant is missing from the list.
7. Click the "back" button under the Library tab to view the registered fonts list, then click back into the new font's variant detail list.
8. Note that the list now includes the additional variant.

### Screenshots, screen recording, code snippet

_Demonstration to reproduce issue:_
library-list-refresh

### Environment info

- Hardware: MacBook Pro Apple M1 Pro
- OS: macOS 13.6
- Browser: Safari 16.6, Google Chrome 117.0.5938.132
- Server: nginx/1.25.2
- PHP: 7.4.33
- WordPress: 6.4-beta1-56730-src
- Theme: twentytwentythree v1.2
- Active Plugins:
 - gutenberg v16.7.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by mikachan**
## What?

This is a small PR to reset the selected font (`libraryFontSelected`) when installing a new font.

## Why?

Fixes https://github.com/WordPress/gutenberg/issues/54945.

## How?

Adds a call to `setLibraryFontSelected` in `installFont` which sets the `libraryFontSelected` to `null`. 

This means that when navigating back to the installed fonts list in the Font Library modal, the initial list of fonts is shown rather than the previously selected font. This also means that the list is up to date, including the latest installed font. Previously, you had to navigate back to the list of installed fonts manually in order to reset the selected font.

## Testing Instructions

1. Open the Font Library modal
2. In the Upload tab, add a single variant of a new font, and confirm the upload succeeded.
3. Click the Library tab, noting that you are viewing the full list of installed fonts.
4. Click into the font's variant detail list, noting the single variant that was added.

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/1645628/2e229558-4595-4a86-bf7d-32b63ddd1ef9

### CODE REVIEW

File: packages/edit-site/src/components/global-styles/font-library-modal/context.js [hunk 1]
```diff
@@ -214,6 +214,7 @@ function FontLibraryProvider( { children } ) {
 			] );
 			refreshLibrary();
 			setIsInstalling( false );
```
Comment (vcanales) [inline packages/edit-site/src/components/global-styles/font-library-modal/context.js]: Nit: This can be moved to a `finally` block, along with the same call in the `catch` block, to avoid repeating it.

**Review by vcanales — APPROVED** [review]
This tests well for me. Left a small suggestion, but LGTM

File: packages/edit-site/src/components/global-styles/font-library-modal/context.js (hunk 1 above)
Comment (mikachan) [reply packages/edit-site/src/components/global-styles/font-library-modal/context.js]: Oh yeah! I've moved `setIsInstalling` and `setLibraryFontSelected` to a `finally` block here: https://github.com/WordPress/gutenberg/pull/57817/commits/a9140595cd9462cad4a0b6fa5f4a7aa4a2775032

**Review by jffng — APPROVED** [review]
This works as advertised. 

It does change the behavior of navigating between the tabs. Currently, if you navigate to a specific font + variant list in the Library tab, then you navigate to the Upload tab and install a font, then navigate back to Library, you're at the specific font where you left off.

This changes the behavior so that the Library tab is always reset after trying to install a font, even if it fails. 

I think I'm okay with that, so ✅

**Comment by mikachan** [comment]
Thanks @vcanales and @jffng for the reviews!

> This changes the behavior so that the Library tab is always reset after trying to install a font, even if it fails.

I'm not sure about this behaviour when the installation fails - I've changed it back so `setLibraryFontSelected` is only run after a successful installation in https://github.com/WordPress/gutenberg/pull/57817/commits/55a5a703f640bc9b3ddaf3c6833ed1e354dce844. I think that probably makes more sense.

**Comment by mikachan** [comment]
I think I've found a better way to handle this 👀

I've added a call to `handleSelectFont` in the `useEffect` of the InstalledFonts component. This means that the selected font is set again after the library refresh. The display of the specific font page is then persisted when a new variant is uploaded, and the new variant should also be included in the variant list. 

This keeps the behaviour when switching tabs the same as before, but the variant list is updated immediately.

Sorry for changing my mind - this is ready for another review! 🙇

**Review by jffng — APPROVED** [review]
> This keeps the behaviour when switching tabs the same as before, but the variant list is updated immediately.

👍 Tested and verified the behaviour is same as before when switching tabs, and the variant list is updated immediately after upload.
