### PR TITLE
[Block Library - Social Links]: Use the new `flex` layout

### LINKED ISSUE #34003: Used attribute `itemsJustification` is not declared in block's schema
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

In https://github.com/WordPress/gutenberg/pull/28980 items justification was added to `Social Links` block. This PR though while started using a new attribute(`itemsJustification`) it was never declared in the block's schema(`block.json`).

### Step-by-step reproduction instructions

1. Insert a `Social Links` block and change the justification from the control.
2. Save and reload
3. Change again the value and observe that has both conflicting classes

Also check the blocks `block.json` file.

### Expected Behavior

The attribute should be declared and a migration would be needed based on existing classes. 

I would propose though to hold onto this a bit before fixing, as in this PR: https://github.com/WordPress/gutenberg/pull/33987/ there is exploration of using a `flex` layout for this block. If this PR lands we would need to remove the now missing attribute, so this issue will be resolved.

### Current Behavior

What this means in practice is that the attribute is never saved. When we insert such a block the value is `undefined` so the default behavior felt okay (left align/flex-start). While editing this value by the corresponding control we were setting the value with `setAttributes`, which doesn't sanitize the attributes, and added a css class which was was then saved. On reload though, the same block seemed to be keeping its behavior by the css classname and not the attribute - the attribute is `undefined`. So if you change this value after reload a new css class will be applied that leads to multiple conflicting classes - there is only one winner though with unexpected results 😄 .

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description
Related to: https://github.com/WordPress/gutenberg/pull/33359
Fixes: https://github.com/WordPress/gutenberg/issues/34003

This PR explores the new `flex layout` to be used by `Social Links` block. The goal is to use `flex` layout in a declarative way and not rely on 'hackish` css custom solutions for blocks that a `flex` layout is a good fit.

## Notes
1. I've [found a bug](https://github.com/WordPress/gutenberg/issues/34003) in `Social Icons` block regarding `itemsJustification` attribute which was introduced in https://github.com/WordPress/gutenberg/pull/28980 and wasn't declared in block.json. With this PR the issue will be resolved as we remove it's usage.

2. I observed that also on `trunk` if you select the block, the alignment is different than the one applied at the end (it uses `flex-start`. This PR doesn't have this problem.
3. The `justify content` control will need polishing in regards to `labels` etc..
4. Tests will be updated and/or created..
5. A small visual difference is that `gap` is applied now due to this previous change: https://github.com/WordPress/gutenberg/pull/34493/files#diff-324697e41855298e2f2c74b078f174e0cbc9075cef736ce9c1e2c169bf64652eR70. 

## Testing instructions
1. Insert `Social Links` block and in Inspector controls play with the justify content control.
2. Check that previously created `Social Links` blocks are displayed as before in both editor and front-end.

## Tasks
 - [ ] Check native file

### CODE REVIEW

File: lib/block-supports/layout.php [hunk 1]
```diff
@@ -70,6 +70,14 @@ function gutenberg_get_layout_style( $selector, $layout ) {
...
 		$style .= 'flex-wrap: wrap;';
 		$style .= 'align-items: center;';
+		/**
+		 * Add this style only if is not empty for backwards compatibility,
+		 * since we intend to convert blocks that had flex layout implemented
+		 * by custom css.
+		 */
+		if ( ! empty( $layout['justifyContent'] ) ) {
+			$style .= "justify-content: {$layout['justifyContent']};";
+		}
```
Comment (ntsekouras) [inline lib/block-supports/layout.php:94]: @youknowriad 's comment:
>I was expecting more changes here to retrieve the "default layout" from the block support config and apply it when the "layout" attribute is empty.

The passed `layout` has already checked the existence of default block layout.

File: packages/block-library/src/social-links/edit.js [hunk 2]
```diff
@@ -52,10 +62,23 @@ export function SocialLinksEdit( props ) {
...
+		( select ) => {
+			const { getSettings } = select( blockEditorStore );
+			return {
+				themeSupportsLayout: getSettings()?.supportsLayout,
+			};
+		},
+		[ clientId ]
+	);
+
+	const usedLayout = !! layout || getDefaultBlockLayout( name );
```
Comment (ntsekouras) [inline packages/block-library/src/social-links/edit.js]: @youknowriad 's comment:

>All this logic is something that I wanted to do automatically in the hook for existing blocks using "layout", the problem is that we don't have a filter for InnerBlocks to do it. Maybe we should introduce an unstable filter to be able to inject the layout prop into InnerBlocks.

Comment (ntsekouras) [reply packages/block-library/src/social-links/edit.js]: I'll explore this..

**Comment by jasmussen** [comment]
This is excellent:

Screenshot 2021-09-02 at 13 43 06

Note the above has a pretty spacious (intentionally so to test) margin, but it's applied correctly:

Screenshot 2021-09-02 at 13 44 56

Here's the gap highlighted by the inspector:

Screenshot 2021-09-02 at 13 43 18

Since we are employing gap now, I think we can remove the margin that sits around each item, which was previously there just to space things out:

Screenshot 2021-09-02 at 13 43 28

I did notice in the resting state, this "click plus" prompt is subject to the issue as well:

Screenshot 2021-09-02 at 13 54 31

I never really loved that help text in the first place, I think we'll want to do something different. But a small interim fix we can push in the mean time might just be to set the gap to zero when in that setup state.

Another thing I noticed, which we also don't have to address here, is that the Button component which is intended only for use inside editor UI is used for the markup, when an actual `button` should be used instead. By replacing the button component with the HTML element, we won't have to unstyle all the editor styles attached to the `components-button` style:

Screenshot 2021-09-02 at 13 41 54

I also tried customizing the gap for this block in particular, so that it has its own rules and not those inherited from the block gap defined in `settings`. This:

```
			"core/social-links": {
				"spacing": {
					"blockGap": "0"
				}
			}
```

works as intended:

Screenshot 2021-09-02 at 13 50 24

— though it does show we still have to remove the margins from the individual items still. It also opens another question: should we provide a block gap rule just for this block, or do we want it to be inherited from the default 24px styles rule? I don't have a strong opinion, but my instinct is that people would want large-ish block gaps for the main content, and a somewhat smaller gap inside social links.

File: packages/block-library/src/social-links/edit.js (hunk 2 above)
Comment (youknowriad) [reply packages/block-library/src/social-links/edit.js]: @ntsekouras this is separate from this PR, don't make it block you here.

**Comment by youknowriad** [comment]
> I never really loved that help text in the first place, I think we'll want to do something different. But a small interim fix we can push in the mean time might just be to set the gap to zero when in that setup state.

Can't we wrap the plus and the text in a single element?

**Comment by youknowriad** [comment]
> Another thing I noticed, which we also don't have to address here, is that the Button component which is intended only for use inside editor UI is used for the markup, when an actual button should be used instead. By replacing the button component with the HTML element, we won't have to unstyle all the editor styles attached to the components-button style:

I agree with this but it means we might need a `button` primitive to share with mobile, I wonder if that one is there for this reason.

**Comment by youknowriad** [comment]
> I don't have a strong opinion, but my instinct is that people would want large-ish block gaps for the main content, and a somewhat smaller gap inside social links.

That is a good though but also one that relates more to how block gap works and not specific to this PR. It seems like you're suggesting one of the two

 1- `blockGap` for horizontal blocks should have its own CSS variable different from the global one.
 2- `blockGap` is not inherited at all and should be defined on each container.

For simplicity, I personally prefer the current behavior (consistent blockGap) but if we do want to make the distinction, maybe the first option is better. 

It also related to a previous feedback by @andrewserong : Do we need both "column gap" and "row gap" which also raises the question about whether "row gap" in a "flow" container is equivalent to a "row gap" in a "flex" container

**Comment by jasmussen** [comment]
> I agree with this but it means we might need a button primitive to share with mobile, I wonder if that one is there for this reason.

The search block was recently refactored along the same lines: #33961 — if mobile is an issue, we need to look back to that one as well.

> 1- blockGap for horizontal blocks should have its own CSS variable different from the global one.
> 2- blockGap is not inherited at all and should be defined on each container.

I think maybe I'm suggesting a 3rd option, one where there's a global CSS variable that is inherited, and then a default definition in the bundled lib/theme.json that overrides it. Someting like:

```
		"blocks": {
			"core/social-links": {
				"spacing": {
					"blockGap": "1em"
				}
			},
```

It's not a fully formed thought — mostly just sharing the thought process at this point.

**Comment by youknowriad** [comment]
> The search block was recently refactored along the same lines: #33961 — if mobile is an issue, we need to look back to that one as well.

👍 we need to check with mobile folks here @geriux @fluiddot @hypest if this doesn't produce regressions there. (I'm sure it does if the code is shared)

**Comment by youknowriad** [comment]
> I think maybe I'm suggesting a 3rd option, one where there's a global CSS variable that is inherited, and then a default definition in the bundled lib/theme.json that overrides it. 

That works for me 👍

**Comment by talldan** [comment]
> 1. Insert Social Links block and in Inspector controls play with the justify content control.
> 2. Check that previously created Social Links blocks are displayed as before in both editor and front-end.

This seems to only work in block-based themes. I'm generally using non-block based themes for working on the widgets screen, and noticed justification options are no longer available.

It might be on your radar, but thought I'd mention it.

**Comment by andrewserong** [comment]
Thanks for the ping!

> I think maybe I'm suggesting a 3rd option, one where there's a global CSS variable that is inherited, and then a default definition in the bundled lib/theme.json that overrides it.

That should now work now that #33991 has landed. Adding the block gap value for a specific block in the `theme.json` will render the CSS variable value for that block in the stylesheet. Or, inline to the rendered block markup if it's set within a block's  style attribute, so you can have a separate value for the particular social links block (either via `theme.json` for the block in general, or once we've opted into the block support, via the individual block's attribute).

**Comment by ntsekouras** [comment]
>This seems to only work in block-based themes. I'm generally using non-block based themes for working on the widgets screen, and noticed justification options are no longer available.

Thanks for testing @talldan! I've made some changes to work on all themes. Also `justification` options are related to the `flex` layout, so they now live under the `layout` panel in `Inspector Controls`. So any block with `flex` layout will have this out of the box.

File: test/integration/fixtures/blocks/core__social-links.serialized.html [hunk 3]
```diff
@@ -1,3 +1,3 @@
-<!-- wp:social-links -->
+<!-- wp:social-links {"layout":{"type":"flex"}} -->
```
Comment (youknowriad) [inline test/integration/fixtures/blocks/core__social-links.serialized.html]: I was not expected this change since it's the default value? Do we know why it gets included in the serialization?

Comment (ntsekouras) [reply test/integration/fixtures/blocks/core__social-links.serialized.html]: You're right! I think it's good now as before I was adding the above attribute even if it didn't had any `justify` css classes in the migration function.

Thanks for catching this as it confused me a bit as it was a default from a `supports` flag, but it is used in `edit` function, so it makes sense that this shouldn't be there.

**Comment by jasmussen** [comment]
I pushed a small fix to remove the margin on link items, since they are now spaced apart wiht gap. The gap in the following is intentionally crazy to show that it works, but we'd want a sane default, like 1em, as suggested previously:

Screenshot 2021-09-03 at 14 45 29

The gap looks equally crazy in this case, as noted:

Screenshot 2021-09-03 at 14 41 08

However I wasn't able to immediately figure out how to move that prompt next to the appender only in the empty state. The CSS is a bit gnarly there. Since the gap will make sense in most cases, this might not be worth fixing since we are thinking of other options.

I noted the comments about justification changes, but I'm not sure if they have UI consequences. In this branch I'm seeing justification tools moved to the inspector, like so:

Screenshot 2021-09-03 at 14 41 03

The justification tools as part of the toolbar work better, in my opinion. Can we move them back to how they are in trunk?

Screenshot 2021-09-03 at 14 48 20

**Comment by ntsekouras** [comment]
>I noted the comments about justification changes, but I'm not sure if they have UI consequences. In this branch I'm seeing justification tools moved to the inspector, like so:

I don't have strong opinion here but I'm more inclined to the approach of having the controls related to each `layout` grouped together in one place. This way I think it's clearer for users what controls are coupled with each `layout`. Also with more use cases/additions to come, the change of `layouts` through the `layout switcher` will not cause toolbar items to `appear/disappear`.

In the near future as we augment `layout` features, we could explore more things with controls. What do you think?

**Comment by jasmussen** [comment]
I don't think that there needs to be any conceptual connection between our more advanced layout tools and justifications, I'd group those with alignments and text alignments.

**Comment by youknowriad** [comment]
I agree with Nik for this one here, there's definitely a conceptual link between layout type and these justification controls.

Think of the group block for instance, imagine we enable the control to switch layout type (switch between flow and row) (we already have that it's just hidden), the justification controls will appear when you select "row" but disappear when you select "flow", it's not a great experience for group block to have toolbar buttons appear and disappear when you toggle something on the inspector IMO.

That said, there are blocks that are intrinsically "flex" layouts (or flow layouts) for instance Social Links, Columns, Buttons. For these, it makes sense to have controls for justification in the toolbar for instance (like today).

The problem is in the code architecture, we don't make any difference between these two type of blocks (both use layout). Potentially we could offer two different UIs depending on whether wether the block allow switching layout types. It's not that easy to do and if we can go with the inspector UI while we iterate on these things, I'd be game for it.

**Comment by jasmussen** [comment]
> Think of the group block for instance, imagine we enable the control to switch layout type (switch between flow and row) (we already have that it's just hidden), the justification controls will appear when you select "row" but disappear when you select "flow", it's not a great experience for group block to have toolbar buttons appear and disappear when you toggle something on the inspector IMO.

Good point, it does make sense for things like group, and I can imagine other containers where justification is important but not a primary interaction. In those cases we might be able to show a dropdown like this, rather than the segmented control, as I imagine something similar could be useful for some alignment properties:

Frame 251

> It's not that easy to do and if we can go with the inspector UI while we iterate on these things, I'd be game for it.

I feel somewhat strongly about keeping justification controls in the block toolbar. We could potentially have it sidebar-only for a few plugin releases, but I don't think we'd want to ship 5.9 with justification tools moved away from the block toolbar.

**Comment by youknowriad** [comment]
> I feel somewhat strongly about keeping justification controls in the block toolbar. We could potentially have it sidebar-only for a few plugin releases, but I don't think we'd want to ship 5.9 with justification tools moved away from the block toolbar.

Makes sense

@ntsekouras  I guess we should try to rearchitecture the `edit` function of layouts a bit.  Maybe the responsibility to render the slots (`InspectorControl` and `GroupControl`) should be moved to that function instead of leaving it to the wrapper. And the layout itself could receive some options (like allowSwitching: true/false) to switch between toolbar or inspector depending on the block

**Comment by ntsekouras** [comment]
>@ntsekouras I guess we should try to rearchitecture the edit function of layouts a bit. 

I'll see to it 😄

**Comment by jasmussen** [comment]
In case it's useful, I wouldn't personally mind if justification tools were both in the inspector and block toolbar for something like social links and buttons, but inspector only for something like group.

**Comment by ntsekouras** [comment]
>In case it's useful, I wouldn't personally mind if justification tools were both in the inspector and block toolbar for something like social links and buttons, but inspector only for something like group.

Here are some info about current implementation:
1. We have two controls (`inherit` and `layout switcher`) that only make sense in `Inspector controls` and are only showed conditionally depending on the config and that do not make any sense to live in the `toolbar`.
2. We cannot know (in an efficient way at least) if a layout will render something in `inspector controls` as is a `React` component. An example of this might be the current iteration of `Social Links` which now only support `flex`, which for now has only one control (justify content), and not allow layout switching or `inheriting` and we might end up with a layout that has only `toolbar` controls, resulting in an empty `Layout Panel`.
3. From the above comment of @jasmussen and the notion that `layout` controls would be good to be grouped together, I think it's okay to think that all controls should be displayed in `Inspector` controls, even if in some cases the controls are shown at both places (inspector controls and toolbar).

In future iterations it will become clearer how to form a better API to handle conditionally displaying of a control only in one place. I tried to think of an easy to use, declarative API but this will be mostly guessing for now about our future needs, so I believe it's better to iterate on the simplest solution for now.

My last commits are about:
1. Always show the `Inspector` controls panel and in the specific PR, show the same control in both places. A thing that might be good to include (and would kind of solve the duplicate control problem without introducing any new API) would be to include some info about the block's current layout type in `inspector controls`.
2. Introduce a new `toolBarControls` function in layouts that would be responsible of rendering such controls.
3. In a block that allows switching layouts (like `Group` which is the most probable block to implement this) don't show the toolbar controls.

What do you think?

**Review by aaronrobertshaw — COMMENTED** [review]
The new flex layout for Social Links looks pretty good 👍 

I've given this a test and it generally works well across themes for me whether they are block-based or not.

I did encounter one issue though. When a deprecated version of the Social Links block, with an alignment set, is migrated to the latest version the old alignment is kept in the saved CSS classes. 

This possibly occurs when the old justification classes are stripped out in the `migrateWithLayout` function. The result is CSS classes such as `alignright` interfering with the correct alignment of the block until it's cleared via the Advanced CSS field.


https://user-images.githubusercontent.com/60436221/132152423-34ffd4cd-1a24-49a6-b07e-cd1b0558eab9.mp4

**Comment by youknowriad** [comment]
> Always show the Inspector controls panel and in the specific PR, show the same control in both places. A thing that might be good to include (and would kind of solve the duplicate control problem without introducing any new API) would be to include some info about the block's current layout type in inspector controls.
> Introduce a new toolBarControls function in layouts that would be responsible of rendering such controls.

The problem I have with this is that we have use cases where the same layout could render justification controls in inspector (group) or toolbar (social icons) depending on the block and duplication in the case of group might not be the solution.

What about just a single `edit` function that renders both `<BlockControls>` and `<InspectorControls` depending on the current block. For instance it can check if `allowSwitching` is true, if it's true, it means everything is in the inspector, if it's false, it decides more wisely to put more important things in the toolbar.

**Comment by ntsekouras** [comment]
>The problem I have with this is that we have use cases where the same layout could render justification controls in inspector (group) or toolbar (social icons) depending on the block and duplication in the case of group might not be the solution.

After having a discussion with @youknowriad about the above, I tried an approach of 'calling' or rendering the layout's inspectorControls in combination with the other common controls there, to not display the `InspectorControls` at all.. 

By assigning to a `variable` the rendered component results in the same problem we have now.. We can't know if the React component will render nothing.

By calling the component as a function or by rendering the component to a string (`renderToString` from `wp.element`) will not work either, because if we have a block that allows to switch layouts and they use hooks in their `layoutType.inspectorControls` (`flow` does that and `flex` doesn't) , it results in different hooks being called in the parent component with this logic, the `LayoutPanel`.

By going with the convention(at least for now) that all controls should be rendered at Inspector controls, we can easily hide the `toolbar` controls even with the flag I set now([if can switch layout](https://github.com/WordPress/gutenberg/pull/34493/files#diff-9253b9c34ce16bbff98ab214bb5441a64810d583da82be09a340f1a2a5b718e4R102)) or with a new flag like `hideToolbarControls` in `block.json`.

IMO by having a single edit and moving the common `Inherit default layout` and `layout switcher` controls to every available layout is more convoluted and would mean maintaining the same code in each layout.

Any thoughts?

-----
--edit: I updated the things I tried above 😄

**Comment by ntsekouras** [comment]
>I did encounter one issue though. When a deprecated version of the Social Links block, with an alignment set, is migrated to the latest version the old alignment is kept in the saved CSS classes.

@aaronrobertshaw the migration removes only the `justify content` classes which contained the same styles applied by the `flex` layout. Such conflicts with `align` are still possible. Can you share how your block without this PR and how it changed here?

File: packages/block-editor/src/layouts/flex.js [hunk 4]
```diff
@@ -41,12 +79,71 @@ export default {
...
+				popoverProps={ {
+					position: 'bottom right',
+					isAlternate: true,
+				} }
+			/>
+		);
+	}
+	return (
+		<ToggleGroupControl
+			label={ __( 'Justify content' ) }
```
Comment (youknowriad) [inline packages/block-editor/src/layouts/flex.js:121]: The label seems too close to the buttons in this case,
Also clicking the label doesn't seem to focus the buttons like labels do in general in controls.

I believe these are probably independent of this PR but could use some improvements separately.

**Review by youknowriad — APPROVED** [review]
I don't like the duplication of controls we have right now but maybe it's fine for a start.

**Comment by jasmussen** [comment]
I didn't have time to test the latest version here before landing, but we'll want to follow up on the segmented control if that's still used — the "space between" wrapping on two lines means that widget shouldn't be used. We could potentially use an iconified version of the segmented control that uses the justification icons, and reads a bit like this one:

Screenshot 2021-09-07 at 20 02 34

**Comment by aaronrobertshaw** [comment]
> @aaronrobertshaw the migration removes only the justify content classes which contained the same styles applied by the flex layout. Such conflicts with align are still possible. 

@ntsekouras I was under the impression that there was some additional handling of className attribute. Via the custom class name hooks or in the parser where [custom class names are "fixed"](https://github.com/wordpress/gutenberg/blob/984160d1368695f22222aea4e20527d7699b842c/packages/blocks/src/api/parser/fix-custom-classname.js#L46). My suggestion was that although the current code in the deprecation only stripped out the justification class it might have had this unintended side effect.

> Can you share how your block without this PR and how it changed here?

Before this PR, alignment classes on existing blocks weren't treated as custom CSS classes. After a block is migrated via the new deprecations, the alignment class is saved as a custom CSS class.

I've tested this again by checking out the commit on trunk prior to the merging of this PR. I get the same behaviour consistently.

#### Steps to reproduce

1. Checkout the commit on trunk prior to this PR's merge: 435119c3bed91c10737a574e072d7482e7e5c6bb
2. Add a social links block and align it to the right, then save
3. Reload the editor and note that the Advanced CSS field in the inspector controls is still empty
4. Check out the latest on trunk or just this PR's commit: dd5fd6b2466d33177d46dcdc0733abd0217e044a
5. Reload the editor
6. Reselect the social links block and note that the Advanced CSS field now contains the `alignright` class
7. Try and change the block's alignment to centered via the block's toolbar. It will still appear right aligned
8. Clear the Advanced CSS field and the block's alignment will display correctly again

#### Demo of above steps

https://user-images.githubusercontent.com/60436221/132432836-4839b684-18ba-4d64-a112-68038484d37f.mp4

**Comment by jasmussen** [comment]
Thank you all for the excellent work on this. It's so nice to see the block toolbar affordance for justification still there. Nice work.

social

One thing we should follow up on soon is the segmented control where "Space between" wraps on to two lines:

Screenshot 2021-09-08 at 10 00 44

The segmented control should not be used when there isn't space for the text inside to fit on one line. Some alternatives is a dropdown, or perhaps as alluded to earlier, a small buttongroup with icons. It could look like this:

Frame 279

The above, if we like, could even be a segmented control under the hood since only one item at a time is selected. But the design it emulates is that of toolbar buttons. What do you think, @ntsekouras?

**Comment by ntsekouras** [comment]
>The segmented control should not be used when there isn't space for the text inside to fit on one line. Some alternatives is a dropdown, or perhaps as alluded to earlier, a small buttongroup with icons. It could look like this:

@jasmussen I'll open a follow up really soon.

**Comment by jasmussen** [comment]
Awesome. Would be happy to pair on it 👌

File: test/integration/fixtures/blocks/core__social-links__deprecated-1.html [hunk 5]
```diff
@@ -0,0 +1,7 @@
+<!-- wp:social-links {"customIconColor":"#ffffff","iconColorValue":"#ffffff","customIconBackgroundColor":"#3962e3","iconBackgroundColorValue":"#3962e3","className":"has-icon-color"} -->
+<ul class="wp-block-social-links has-icon-color has-icon-background-color items-justified-space-between">
```
Comment (youknowriad) [inline test/integration/fixtures/blocks/core__social-links__deprecated-1.html:2]: How can this block have `item-justified-*` classname without having the `itemsJustification` attribute?

Comment (youknowriad) [reply test/integration/fixtures/blocks/core__social-links__deprecated-1.html:2]: I guess that attribute has never been registered (was broken)

Comment (ntsekouras) [reply test/integration/fixtures/blocks/core__social-links__deprecated-1.html:2]: Exactly.
>I've [found a bug](https://github.com/WordPress/gutenberg/issues/34003) in `Social Icons` block regarding `itemsJustification` attribute which was introduced in https://github.com/WordPress/gutenberg/pull/28980 and wasn't declared in block.json. With this PR the issue will be resolved as we remove its usage.
