### PR TITLE
Quote Block: Fixing focus transfer between citation and content

### LINKED ISSUE #5081: Quote: impossible to switch between fields by clicking on text
## Issue Overview
When in the quote block, we cannot switch from content to citation if we are already in one of the fields.

## Steps to Reproduce (for bugs)

1. Add a quote block. Write something in the content.
2. Try to switch to the citation, it may be hard as the click looks like not working, there is a bug here affecting RichText selection when clicking placeholders. It is possible to switch to citation using arrow down.
3. Write something in citation try to switch to content, by clicking in the middle of the content text. See it is not possible. Clicking on a non-text white space at the side of the content makes writing in content possible.

If we select another block we are able to select but content and citation by clicking on the text as expected.

## Screenshots / Video

feb-15-2018 16-21-51

### PR DESCRIPTION
**Pull request by youknowriad**
closes #5081

This PR fixes moving focus between citation and content in quote blocks.

**Testing instructions**

 - Add a quote block
 - type content
 - type citation
 - click to switch focus between quote and citation

### CODE REVIEW

File: blocks/rich-text/index.js [hunk 1]
```diff
@@ -740,7 +740,9 @@ export class RichText extends Component {
 			!! this.editor &&
 			this.props.tagName === prevProps.tagName &&
 			this.props.value !== prevProps.value &&
-			this.props.value !== this.savedContent
+			this.props.value !== this.savedContent &&
+			! isEqual( this.props.value, prevProps.value ) &&
+			! isEqual( this.props.value, this.savedContent )
```
Comment (youknowriad) [inline blocks/rich-text/index.js]: This is the real fix. I removed this as part of #4955 but it's necessary to avoid unnecessarily content updates. I don't see any performance loss in adding this and it could even improve performance because we don't use those TinyMCE functions `setBookmark` and `setContent` constantly

File: blocks/library/pullquote/editor.scss [hunk 2]
```diff
@@ -11,6 +11,10 @@
 }
 
 .wp-block-pullquote {
+	cite {
+		display: block;
```
Comment (youknowriad) [inline blocks/library/pullquote/editor.scss]: This just increases the click area of the citation to the whole line (width: 100%)

**Comment by aduth** [comment]
Seeing an issue:

1. Type a paragraph
2. Press enter

Content from the first paragraph disappears.

**Comment by jorgefilipecosta** [comment]
It seems like this solved the problems with the quote. Regarding the problem reported by @aduth I'm also able to replicate it seems to only happen in paragraph other blocks e.g: list works well.

**Comment by youknowriad** [comment]
Good catch @aduth It's fixed now.

It was happening because when you hit "Enter", TinyMCE updates the content of the rich text before even we call onSplit. And since we want to keep the same content as before in this case,  we have to call `updateContent` to make sure the "Enter" key is reverted properly.

Previous `updateContent` was called on rerender because the value prop was failing the strict equality check.

File: blocks/rich-text/index.js [hunk 3]
```diff
@@ -638,8 +639,13 @@ export class RichText extends Component {
 
 			const beforeElement = nodeListToReact( beforeFragment.childNodes, createTinyMCEElement );
 			const afterElement = nodeListToReact( filterEmptyNodes( afterFragment.childNodes ), createTinyMCEElement );
+
+			// Since we need to abort the change done by TinyMCE
+			// we need to call updateContent to restore the initial content before calling onSplit.
+			this.updateContent();
```
Comment (aduth) [inline blocks/rich-text/index.js]: If it's the case that we must call `updateContent` before every `this.props.onSplit`, could be wise to create a separate class function for consistency/safety's sake.

**Review by aduth — APPROVED** [review]

File: blocks/rich-text/index.js (hunk 1 above)
Comment (iseulde) [reply blocks/rich-text/index.js]: @youknowriad I feel like we removed and added this a few times I the last year now. :) Maybe worth leaving a comment?

Comment (iseulde) [reply blocks/rich-text/index.js]: (I was surprised to see these lines again.)

File: blocks/library/pullquote/editor.scss (hunk 2 above)
Comment (iseulde) [reply blocks/library/pullquote/editor.scss]: This kind of tells me that we shouldn't be using cite for this... :)

File: blocks/rich-text/index.js [hunk 4]
```diff
@@ -796,6 +799,19 @@ export class RichText extends Component {
...
+	 * Calling onSplit means we need to abort the change done by TinyMCE.
+	 * we need to call updateContent to restore the initial content before calling onSplit.
+	 *
+	 * @param {Array}  before content before the split position
+	 * @param {Array}  after  content after the split position
+	 * @param {?Array} blocks blocks to insert at the split position
+	 */
+	restoreContentAndSplit( before, after, blocks ) {
+		this.updateContent();
+		this.props.onSplit( before, after, ...blocks );
```
Comment (iseulde) [inline blocks/rich-text/index.js]: Hm, now we have (1) `this.props.onSplit` checks in several places and (2) none here.

File: blocks/rich-text/index.js (hunk 1 above)
Comment (youknowriad) [reply blocks/rich-text/index.js]: Good call 👍

File: blocks/rich-text/index.js [hunk 5]
```diff
@@ -796,6 +799,19 @@ export class RichText extends Component {
 		} ) );
 	}
 
+	/**
+	 * Calling onSplit means we need to abort the change done by TinyMCE.
```
Comment (aduth) [inline blocks/rich-text/index.js]: I don't really understand this function. In most places where it's used, we're also calling `preventDefault`. Shouldn't that be enough to "abort the change" that would otherwise be effected by TinyMCE ?
