### PR TITLE
BorderRadius Presets: Fix Generating wrong variable names in pattern code

### LINKED ISSUE #71628: BorderRadius Presets: Generating wrong variable names in pattern code
### Description

Define RadiusSizes preset(s) in theme.json file, like this:
```
"radiusSizes": [
	{
		"name": "Medium",
		"slug": "medium",
		"size": "clamp(0.25rem, 0.2356rem + 0.0641vw, 0.3125rem)"
	}
]
```

Create new block pattern, insert empty group block and set Top Left and Top Right Radius properties to Medium. Set Bottom ones to None. There are generated pattern code:
```
<!-- wp:group {"style":{"border":{"radius":{"topLeft":"clamp(0.25rem, 0.2356rem + 0.0641vw, 0.3125rem)","topRight":"clamp(0.25rem, 0.2356rem + 0.0641vw, 0.3125rem)","bottomLeft":"var:preset|border-radius|0","bottomRight":"var:preset|border-radius|0"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="border-top-left-radius:clamp(0.25rem, 0.2356rem + 0.0641vw, 0.3125rem);border-top-right-radius:clamp(0.25rem, 0.2356rem + 0.0641vw, 0.3125rem);border-bottom-left-radius:var(--wp--preset--border-radius--0);border-bottom-right-radius:var(--wp--preset--border-radius--0)"></div>
<!-- /wp:group -->
```

- `topLeft` and `topRight` properties have just defined `clamp` values instead of variable name `var:preset|border-radius|medium`;
- `bottomLeft` and `bottomRight` props have wrong and undefined variable name `var:preset|border-radius|0` instead of just `0` (zero).

**ALSO:** The border radius dropdown list is displaying out of the screen borders (to make it visible and clickable need to enable the Shadow property):

Image

### Environment info

WP 6.8.2; Gutenberg 21.6.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by USERSATOSHI**
## What?
Closes https://github.com/WordPress/gutenberg/issues/71628

This PR fixes the handling of border radius presets in block patterns, ensuring that custom `radiusSizes` defined in a theme’s `theme.json` are correctly referenced in generated pattern code. It also adds comprehensive unit tests for the utility functions responsible for this logic.

## Why?
Previously, when using custom border radius presets, the generated block pattern code would sometimes output raw values or invalid preset references (e.g., using the raw clamp value or `var:preset|border-radius|0` instead of `"0"` for "None"). This led to inconsistencies and made it difficult to maintain design token references in patterns.

This PR ensures:
- The "None" preset (slug `"0"`) always serializes as `"0"`, not as a preset reference.
- Preset references are preserved and correctly used in block attributes and pattern serialization.
- The utility functions are robustly tested to prevent regressions.

## How?
- Updated `getPresetValueFromCustomValue` and `getPresetValueFromControlValue` in `border-radius-control/utils.js` to handle the `"0"` slug and preset references correctly.
- Added unit tests to test the changes.

## Testing Instructions
Follow the reproduction steps from https://github.com/WordPress/gutenberg/issues/71628

Other than that Unit tests should suffice.

### CODE REVIEW

**Comment by t-hamano** [comment]
@USERSATOSHI Thanks for the PR!

@aaronrobertshaw @ramonjd @andrewserong, can you take a look at this PR if you have the bandwidth?

File: packages/block-editor/src/components/border-radius-control/utils.js [hunk 1]
```diff
@@ -234,7 +234,13 @@ export function getPresetValueFromControlValue(
...
 		return '0';
 	}
-	return `var:preset|border-radius|${ presets[ controlValue ]?.slug }`;
+
+	const slug = presets[ controlValue ]?.slug;
+	if ( slug === '0' ) {
+		return '0';
+	}
+
+	return `var:preset|border-radius|${ slug }`;
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/components/border-radius-control/utils.js]: I'm not sure on how much this check actually helps.

The `None` preset has a size of `0` so when the control value changes to `"0"` the `parseInt` call will result in `0` and the first conditional returns `"0"`. 

I've quickly tested removing all the new checks added in this PR and the `None` presets and values behave correctly with only the removal of the `decodeValue` calls.

File: packages/block-editor/src/components/border-radius-control/utils.js [hunk 2]
```diff
@@ -258,6 +264,10 @@ export function getPresetValueFromCustomValue( value, presets ) {
 	);
 
 	if ( spacingMatch?.slug ) {
+		if ( spacingMatch.slug === '0' ) {
+			return '0';
+		}
+
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/components/border-radius-control/utils.js]: Similar to the above check.

A new custom value would be a string value and so if `"0"`, would return that in the first conditional here. 

I might be reading this wrong but it seems to me the proposed new check will only catch a preset that matches a non-zero value but has a `"0"` slug. It would then return `"0"` despite the presumably misconfigured preset actually having a non-zero size.

Removing this check as well and only leaving the removal of the `decodeValue` calls has this PR working for me.

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for the PR and especially the added tests @USERSATOSHI 👍 

I've taken this PR for a test drive and it fixes the reported issue for me. 

It appears though that there are some unnecessary code changes which we should probably clean up before merging this one.

Additionally, when attempting to replicate the original issue I found that there were other inconsistencies with the serialization of preset values from this control e.g. sometimes if two corners used the same preset, only one would get the var preset string etc. The removal of the call to `decodeValue` looks to have cleaned this up as well.

File: packages/block-editor/src/components/border-radius-control/utils.js (hunk 1 above)
Comment (USERSATOSHI) [reply packages/block-editor/src/components/border-radius-control/utils.js]: Hi, When I tried to remove the if check on both functions, I am getting

```
<!-- wp:group {"style":{"border":{"radius":{"topLeft":"var:preset|border-radius|medium","topRight":"var:preset|border-radius|medium","bottomLeft":"var:preset|border-radius|0","bottomRight":"var:preset|border-radius|0"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="border-top-left-radius:var(--wp--preset--border-radius--medium);border-top-right-radius:var(--wp--preset--border-radius--medium);border-bottom-left-radius:var(--wp--preset--border-radius--0);border-bottom-right-radius:var(--wp--preset--border-radius--0)"></div>
<!-- /wp:group -->
```

Comment (USERSATOSHI) [reply packages/block-editor/src/components/border-radius-control/utils.js]: nvm, I tested this wrong sorry

File: packages/block-editor/src/components/border-radius-control/utils.js (hunk 2 above)
Comment (USERSATOSHI) [reply packages/block-editor/src/components/border-radius-control/utils.js]: got it I will remove it

File: packages/block-editor/src/components/border-radius-control/test/utils.js [hunk 3]
```diff
@@ -180,3 +182,72 @@ describe( 'mode', () => {
 		expect( mode( values ) ).toBe( 'a' );
 	} );
 } );
+
+describe( 'getPresetValueFromCustomValue', () => {
+	const presets = [
+		{ name: 'None', slug: '0', size: '0' },
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/components/border-radius-control/test/utils.js]: Nit: I think we might want this test preset to mirror what is actually [added in the `BorderRadiusControl`](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/border-radius-control/index.js#L34), i.e. a numeric `0`.

```
{ name: __( 'None' ), slug: '0', size: 0 }
```

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for the quick iterations here @USERSATOSHI 🚀 

This is testing well for me. Border presets are correctly applied:

✅ In block, site, and pattern editors
✅ on the frontend
✅ via global styles
✅ when overriding global styles with block instance styles

There was a failing test that looks unrelated so I've kicked off those tests again. Also, there's a small nit/suggestion for the new tests.

Other than that, I think this is pretty much good to go.

Appreciate all the work on this one 🙇

File: packages/block-editor/src/components/border-radius-control/test/utils.js (hunk 3 above)
Comment (USERSATOSHI) [reply packages/block-editor/src/components/border-radius-control/test/utils.js]: Got it, I will fix this

Comment (aaronrobertshaw) [reply packages/block-editor/src/components/border-radius-control/test/utils.js]: Thanks @USERSATOSHI, my apologies for not being very clear. I only meant to mirror the slug and size values. It's probably best we avoid translations for unit tests.

I've pushed a quick commit in https://github.com/WordPress/gutenberg/pull/71631/commits/9e6f0a44be72f6df7c4ac9cf932e74b77f2d1302. If the tests pass, I'll get this merged.
