### PR TITLE
[Inserter]: Fix focus loss after closing patterns explorer from modal

### LINKED ISSUE #38877: Bloks panel stay open
### Description

Bloks/reusable/patterns panel cant be close after visiting explorer.

### Step-by-step reproduction instructions

Open bloks panel
Go to patterns tab
Clik explorer (don't chose any pattern)
Close Explorer
Try to close panel

### Screenshots, screen recording, code snippet

patternspanel

### Environment info

WordPress 5.9
Tested with Twenty Twenty-Two and Twenty Twenty-One

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ntsekouras**
Fixes: https://github.com/WordPress/gutenberg/issues/38877

As @talldan explains the issue was:
>You can see that when the explore modal is open, the sidebar in the background has no contents (if your browser window is wide enough), so this is no doubt why focus isn't transferred back—there's no element to return focus to.

### Testing instructions

1. Open the main inserter
1. Open the patterns explorer in `patterns` tab (`explore` button)
1. Close the explorer modal from the `close` (x) button
2. Close the main inserter with the `x` button
3. Observe that now it closes as there is no focus loss

https://user-images.githubusercontent.com/16275880/154482406-74442584-341c-46ac-ab7a-b0b43a35a78d.mov

### CODE REVIEW

File: packages/block-editor/src/components/inserter/block-patterns-tab.js [hunk 1]
```diff
@@ -144,23 +144,19 @@ function BlockPatternsTabs( {
...
-						selectedCategory={ patternCategory }
-						populatedCategories={ populatedCategories }
-					/>
-				</>
+				<BlockPatternsCategory
+					rootClientId={ rootClientId }
+					onInsert={ onInsert }
+					selectedCategory={ patternCategory }
+					populatedCategories={ populatedCategories }
+				/>
```
Comment (Mamaduka) [inline packages/block-editor/src/components/inserter/block-patterns-tab.js:159]: Any reason we conditionally render this based on `showPatternsExplorer`?

**Review by Mamaduka — APPROVED** [review]
Thanks, Nik. PR fixes the focus issue 👍

File: packages/block-editor/src/components/inserter/block-patterns-tab.js (hunk 1 above)
Comment (ntsekouras) [reply packages/block-editor/src/components/inserter/block-patterns-tab.js:159]: For performance reasons. If we open the explorer there is no need to continue work on rendering the patterns there, as it's a heavy operation. This makes sense though if we open the explorer before all patterns have rendered in the inserter, which can be the case many times.

Comment (Mamaduka) [reply packages/block-editor/src/components/inserter/block-patterns-tab.js:159]: But if patterns are rendered, and we open/close the modal, they will re-rendered.

It made things a little slow when I was testing the fix.

Comment (ntsekouras) [reply packages/block-editor/src/components/inserter/block-patterns-tab.js:159]: Patterns weren't renderer in inserter before this PR as well, so I don't think that made it slower and to be honest I didn't measure performance for this.. It just seemed to me that is the main flow: open explorer and select... but obviously this seems subjective.. 🤷 I don't know maybe it's fine to show this as well and render the patterns in inserter as well when we open explorer. No strong opinions 😄
