### PR TITLE
Fix accessibility of the Classic block modal dialog

### LINKED ISSUE #50161: Fix accessibility of the Classic Edit modal dialog
### Description

Since a few Gutenberg releases, the Classic Edit block opens in a modal dialog. The modal dialog lacks some important accessibility requirements:

1
The modal dialog is unlabeled.
There is an `aria-labelledby="components-modal-header-0"` attribute but it points to nothing. There have been quite a few unlabeled modal dialogs so far and this is one more instance. This can be fixed on a per-instance basis but, as pointed out in https://github.com/WordPress/gutenberg/issues/47885, it would be best to fix the component in the first place to enforce a proper labeling.

2
The 'Classic Edit' heading contains extraneous content.
The 'Cancel' and 'Save' button are placed within the heading. A heading should be a heading and only contain a meaningful title. Placing buttons within a heading isn't that great. The actual heading text becomes:
`Classic Edit Cancel Save`
which is arguably meaningful, if not confusing. See screenshot.

Screenshot 2023-04-28 at 09 25 40

3
Minor: `<div>` elements within a heading is invalid HTML.

4
The modal dialog heading should be a H1.
When the modal dialog component opens, we do hide from assistive technology all the rest of the content of the page by the means of `aria-hidden="true"`. Worth noting the [aria-modal="true"](https://www.w3.org/TR/wai-aria-1.2/#aria-modal) would be more correct but at the time the component was implemented, `aria-modal` was buggy. Regardless, the modal dialog content is the only content that is perceived by assistive technology. As such, it's best to start the headings hierarchy withih the dialog from scratch by using a H1.

5
Tabbing is not constrained within the modal.
I'm guessing TinyMCE conflicts in some way with the builti-in focus management of the modal dialog component.

### Step-by-step reproduction instructions

- Make sure your active theme is a block-based theme e.g. Twenty Twenty-Three.
- Edit a post.
- Add a Classic block.
- A modal dialog opens.
- In the Chrome dev tools:
  - Inspect the source and select the element with `role="dialog"`.
  - On the right of the dev tools, switch to the Accessibility tab.
  - Observe the accessible name of the dialog is an empty string.
  - Observe the value of the `aria-labelledby` attribute is marked as 'invalid source', meaning there's no element with that ID.
  - Screenshot:

Screenshot 2023-04-28 at 10 45 14

- In the dev tools inspector, select the modal dialog heading.
- Observe it contains the two buttons 'Cancel' and 'Save'.
- In the dev tools Accessibility tab, observe the heading accessible name is `Classic Edit Cancel Save`.
- As such, screen readers announce the heading as `Classic Edit Cancel Save`. Screenshot:

Screenshot 2023-04-28 at 09 25 40

- Observe the heading is a H2. It should be a H1.
- With the modal dialog open, use the Tab key to navigate through the focusable elements.
- Observe that tabbing is not constrained within the modal dialog: when tabbing away from the editable Rich Text area, focus goes to the browser chrome.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by afercia**
Fixes https://github.com/WordPress/gutenberg/issues/50161

## What?

FIxes the accessibility of the Classic block modal dialog. Also improves labeling and design consistency.

## Why?

The modal dialog misses some important accessibility features. Keyboard interaction is broken, labeling is incorrect, etc.
Also improves design consistency with other modal dialogs.

## How?

- Makes sure the modal dialog is labeled.
- Restores the following default features of the modal dialog component as there's no reason to not use them. Also improves consistency with other dialogs.
  - The default modal dialog header.
  - The default modal dialog title so that it's now a H1. This also restores the default title font size.
  - The default X close button.
- Restores the 'close on Escape' behavior. Note: this can't work when focus is in the edit area, as that belongs to the iframe document.
- Keeps the 'close on click outside' behavior disabled, as clicking in the edit area would close the dialog. Actually, the edit area belongs to the iframe document: clicking there is equivalent to 'click outside'. This should be probably addressed separately in the `useFocusOutside` hook.
- Improves the labels:
  - The toolbar button label 'Classic Edit' didn't make much sense. It's also confusing for translators. This is the 'Classic' block, no need to further specify the 'Edit' action. The new 'Edit' label is also consistent with other toolbars used in the (Site) Editor. See screenshot.
  - The modal dialog title is now 'Classic Editor'.
- Uses Flex and FlexItem components for the Cancel/Save buttons to improve spacing and consistency.
- Changes the Cancel button to `tertiary` for consistency.
- Moves the Cancel/Save buttons at the bottom so that constrained tabbing now works as expected. This also improves consistency with other modal dialogs e.g. the Block Lock one.
- Makes sure that on large screens the Cancel/Save buttons are always into view.
- On smaller screens, the modal dialog content is scrollable so that the Cancel/Save buttons will be visible whe scrolling.

## Testing Instructions

- Add a Classic block.
- A modal dialog opens. 
- Enter some text and save.
- Open the Chrome dev tools inspector > select the element with role=dialog > switch the inspector to the accessibility tab
- Observe the dialog Name is 'Classic Editor'. Screenshot:

Screenshot 2023-05-05 at 15 50 48

- Observe the name is determined by the `aria-labelledby` attribute that points to the dialog heading.
- Observe the heading is now a H1.
- Use the Tab key to navigate the modal dialog.
- Observe tabbing is now constrained within the dialog.
- Test also with Shift+Tab.
- When focus is on an element within the dialog (except the TinyMCE edit area), press the Escape key and observe the dialog closes without saving.
- Reopen the dialog and click outside of it: observe the dialog stays open.
- Click the X button and observe the dialog closes without saving.
- Reopen the dialog, make some edit, and click Save. Observe the dialog closes and does save content within the block (actually, this does _not_ save the post content).
- Test with various viewport widths and heights:
  - With short and long content in the block.
  - Expanding and collapsing the TinyMCE toolbar second row (press the TinyMCE 'Toggle toolbar' button).
  - Observe the Cancel/Save buttons are always usable:
  - Either because they're into view on large screens
  - Or because it is possible to scroll the dialog content on small screens.
  - **Important**: test with different browsers.
- Close the dialog
- Select the Classic block: the block toolbar appears.
- Observe the text of the button to open the dialog is now 'Edit'. This is simpler and consistent with other toolbars e.g. some toolbars in the Site Editor. Screenshot: 

Screenshot 2023-05-05 at 16 06 54

Screenshot of a template toolbar:

site editor toolbar with edit button

- Reopen the dialog,
- Observe the Cancel button is now a `tertiary` button, with blue text, like in other dialogs e,g, the Block Lock one.

### Testing Instructions for Keyboard

See above.

### CODE REVIEW

**Comment by afercia** [comment]
Note: of course, there are edge cases with very small viewports and especially very short heights. In these edge cases the Cancel/Save buttons may not be fully usable but the classic editor wouldn't be that usable as well, as the edit area becomes too small to be used. I'd say this is more a limitation of the modal dialog itself.

**Comment by afercia** [comment]
Before:

before

After:

after

**Review by aristath — COMMENTED** [review]
I smoke-tested this and reviewed the code, it looks OK to me!
It does what it's supposed to do, fixes the a11y issue and makes this popover more consistent with other instances.

**Review by alexstine — APPROVED** [review]
This tests really well. 🚢

File: packages/block-library/src/freeform/modal.js [hunk 1]
```diff
@@ -58,35 +59,38 @@ export default function ModalEdit( props ) {
 	} = props;
 	const [ isOpen, setOpen ] = useState( false );
 	const id = `editor-${ clientId }`;
-	const label = __( 'Classic Edit' );
+
+	const onClose = () => ( content ? setOpen( false ) : onReplace( [] ) );
```
Comment (talldan) [inline packages/block-library/src/freeform/modal.js:63]: @afercia Is the block supposed to remove itself when there's no content? That seems to be what the `onReplace` call does.
