### PR TITLE
RichText: change value to have separate keys for line and object formats

### LINKED ISSUE #14123: Errors when inserting inline image since Gutenberg 5.1
**Describe the bug**
Since https://github.com/WordPress/gutenberg/pull/13737, inserting an inline image has some issues.

**To Reproduce**
Issue 1: Insert an inline image at the beginning of a paragraph and directly click on the Apply icon without changing the width. It duplicates the image.

error-duplicate

Issue 2: Insert an inline image at the beginning of a paragraph, change the width and click on the Apply icon. It displays "This block has encountered an error and cannot be previewed."

error-warning

### LINKED ISSUE #14310: Weird nested <ul> behaviour
I built this simple example nested ul structure
`<ul><li>pancake<ul><li></li><li>berries</li><li>ice cream</li></ul></li><li>soup</li><li>main dish</li></ul>`
image

Try insert "pancake" before berries:
image

It becames something new, unused weird format

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #14123, fixes #14310 and https://github.com/WordPress/gutenberg/pull/14001#pullrequestreview-206393193.

This PR adds a new key to the rich text value, `replacements`, which contains object and line information for the replacement character. In the `text`, objects and line separations are represented with a replacement character.

Why?

* Objects and lines do not need boundaries. It requires a lot of extra logic to remove the unwanted boundaries. Currently, in master, images have boundaries.
* There can only be one object at one time at an index, while there can be many formats.
* Separating objects from formats makes it easier to maintain the value. At the moment it would be possible to have `[ em, img, strong ]` in a formats array after applying `strong`. This is impossible; images cannot contain formatting.
* The inline image UI is currently assuming that the image doesn't have any formatting.
* Similarly it shouldn't be possible for line formats to be mixed with normal formats. Line separators cannot be formatted.

## How has this been tested?

Everything should work as before. Inline images should have no boundaries.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by iseulde** [comment]
This PR is now ready for review.

File: packages/editor/src/components/rich-text/index.js [hunk 1]
```diff
@@ -151,10 +151,10 @@ export class RichText extends Component {
 	 * @return {Object} The current record (value and selection).
 	 */
 	getRecord() {
-		const { formats, text } = this.formatToValue( this.props.value );
+		const { formats, lineFormats, objects, text } = this.formatToValue( this.props.value );
```
Comment (mcsf) [inline packages/editor/src/components/rich-text/index.js]: The introduction of `lineFormats` and `objects` makes the role or meaning of `formats` unclear. Should `formats` be renamed to something like `textFormats`, `characterFormats`, `spanFormats` or whatever makes sense?

File: packages/editor/src/components/rich-text/index.js [hunk 2]
```diff
@@ -367,15 +367,20 @@ export class RichText extends Component {
...
+		const { formats, lineFormats, objects, text, start, end } = this.patterns.reduce(
 			( accumlator, transform ) => transform( accumlator ),
 			this.createRecord()
 		);
 
 		if ( this.formatPlaceholder ) {
-			formats[ this.state.start ] = formats[ this.state.start ] || [];
-			formats[ this.state.start ].push( this.formatPlaceholder );
-			selectedFormat = formats[ this.state.start ].length;
+			selectedFormat = this.formatPlaceholder.length;
```
Comment (mcsf) [inline packages/editor/src/components/rich-text/index.js]: From context, `selectedFormat` seems to be used as a boolean. If so:
- it should be renamed as `isSelectedFormat` or `isFormatSelected`, depending on intended meaning
- the RHS of the assignment should cast to boolean, e.g. `!! this.formatPlaceholder.length` or `length > 0`

File: packages/rich-text/README.md [hunk 3]
```diff
@@ -47,7 +46,7 @@ Create an HTML string from a Rich Text value. If a `multilineTag` is provided, t
 apply( {
 	value: Object,
 	current: Element,
-	?multilineTag: string
+	?multilineTag: string,
```
Comment (mcsf) [inline packages/rich-text/README.md]: Do we have stub documentation of the format itself? Would be great to.

**Review by mcsf — COMMENTED** [review]
So far this tests well for me. It's a large diff to review and I can't very confidently comment on things. Left some questions.

File: packages/editor/src/components/rich-text/index.js (hunk 1 above)
Comment (iseulde) [reply packages/editor/src/components/rich-text/index.js]: I guess anything else named formats should be avoided. I'd like to keep `formats` for inline formats and the maybe change `lineFormats` to `lines` or something like that?

File: packages/editor/src/components/rich-text/index.js (hunk 2 above)
Comment (iseulde) [reply packages/editor/src/components/rich-text/index.js]: `selectedFormat` is should be a natural number. How can I make this clearer? I could change the checks for it.

File: packages/editor/src/components/rich-text/index.js (hunk 1 above)
Comment (mcsf) [reply packages/editor/src/components/rich-text/index.js]: `lines` could be good, yeah.

File: packages/editor/src/components/rich-text/index.js (hunk 2 above)
Comment (mcsf) [reply packages/editor/src/components/rich-text/index.js]: I don't know the stack well enough to advise :)

File: packages/editor/src/components/rich-text/format-edit.js [hunk 4]
```diff
@@ -15,13 +15,20 @@ const FormatEdit = ( { formatTypes, onChange, value } ) => {
...
 				return (
 					<Edit
 						key={ name }
 						isActive={ isActive }
-						activeAttributes={ activeAttributes }
+						activeAttributes={
+							isActive ? activeFormat.attributes || {} : {}
+						}
+						isObjectActive={ isObjectActive }
+						objectAttributes={
```
[the remark this answers is not in the document]
Comment (iseulde) [reply packages/editor/src/components/rich-text/format-edit.js]: Hm, I wouldn't change it. It feeds `isActive`, which is a public API. We cannot change that now.

File: packages/rich-text/README.md (hunk 3 above)
Comment (iseulde) [reply packages/rich-text/README.md]: I added something to `create` in the `readme.md`.

File: packages/rich-text/README.md [hunk 5]
```diff
@@ -29,13 +29,27 @@ create( {
 
 Create a RichText value from an `Element` tree (DOM), an HTML string or a plain text string, with optionally a `Range` object to set the selection. If called without any arguments, an empty value will be created. If `multilineTag` is provided, any content of direct children whose type matches `multilineTag` will be separated by a line separator.
 
+A value will have the following shape, which you are strongly encouraced not to modify without the use of helper functions:
```
Comment (mcsf) [inline packages/rich-text/README.md]: Reading this sentence made me wonder whether this sort of private documentation (thanks for adding it, btw) would be better off in, say, a package-specific `CONTRIBUTING.md` file. /cc @gziolo for package stuff

Comment (iseulde) [reply packages/rich-text/README.md]: Yes, this is why I hadn't added it so far, and wanted to add it when explaining how everything works together.

Comment (iseulde) [reply packages/rich-text/README.md]: Perhaps I should move it to the inline documentation for `create` for now?

**Comment by iseulde** [comment]
Rebased and now there's failing history tests. Wondering if it's related to the recent block editor refactoring.

File: packages/rich-text/README.md (hunk 5 above)
Comment (mcsf) [reply packages/rich-text/README.md]: > Perhaps I should move it to the inline documentation for `create` for now?

That works!

File: packages/rich-text/src/test/insert-object.js [hunk 6]
```diff
@@ -17,12 +17,16 @@ describe( 'insert', () => {
...
 			formats: [ , , , , [ em ], [ em ], [ em ], , , , , , , ],
+			lines: [ , , , , , , , , , , , , , ],
+			objects: [ , , , , , , , , , , , , , ],
 			text: 'one two three',
 			start: 6,
 			end: 6,
 		};
 		const expected = {
-			formats: [ , , [ { ...obj, object: true } ], [ em ], , , , , , , ],
+			formats: [ , , , [ em ], , , , , , , ],
```
Comment (aduth) [inline packages/rich-text/src/test/insert-object.js]: I don't know if / how a browser optimizes memory management for allocated arrays, but it appears wasteful to me to create three distinct arrays for each paragraph with a size corresponding to the number of characters (?) in the paragraph. Particularly when it seems that for a given "index", there could be only one qualifying option amongst (a) an array of formats, (b) an object definition, (c) a line descriptor (?). Would it not be possible to represent this as a single array? I guess I'd see it as much the same as it was before, just not called `formats`, and where each "sort" is treated differently. Or is that the root of the issue being addressed?

File: packages/rich-text/src/get-active-object.js [hunk 7]
```diff
@@ -0,0 +1,14 @@
+/**
+ * Gets the active object, if there is any.
+ *
+ * @param {Object} value Value to inspect.
+ *
+ * @return {?Object} Active object, or undefined.
+ */
+export function getActiveObject( { start, end, objects } ) {
```
Comment (aduth) [inline packages/rich-text/src/get-active-object.js]: We have tests for `getActiveFormat`. Should we have tests for `getActiveObject`?

**Review by aduth — COMMENTED** [review]
I feel woefully unprepared to advise on this, but I'd like to assist. Is there anywhere I can read more about what even is an "object" in this context?

The general idea seems to make sense: The way we treat inline formats in the editing interface is very much distinct from how we treat something like an image or a line descriptor. But I can't help feel some redundancy stemming from a thought that ultimately these things are of a classification of the same "describe what exists at the given index" in a single array structure. On the surface, they seem more similar than they are different, evidenced by the fact that much of the new code seems to duplicate existing behavior across this new division: "active" split to `isActive` (`isFormatActive`) and `isObjectActive`, `mergePairs` and `join` doing the same thing to concatenate `formats`, `lines`, `objects`, an identical array structure / length. What I can't speak to is whether the pain in maintaining these redundancies improves upon or counteracts the benefits we gain by treating them as separate from formats, or whether there's some compromise option not yet considered to better support the idea of the singular array structure where each entry can be one of an array of formats, an object, or line descriptors.

**Comment by iseulde** [comment]
> But I can't help feel some redundancy stemming from a thought that ultimately these things are of a classification of the same "describe what exists at the given index" in a single array structure.

You are right. Perhaps we should only keep one array and do something like `[ , , { formats: [], object: {}, line: [], }  ]` or `[ , ,[ [], {}, [], ]  ]`.

File: packages/rich-text/src/test/insert-object.js (hunk 6 above)
Comment (iseulde) [reply packages/rich-text/src/test/insert-object.js]: See also https://github.com/WordPress/gutenberg/pull/13948#issuecomment-468957243.

I think it makes sense regardless of memory use to keep it at one sparse array.

I've also dug a bit further into the memory usage of sparse arrays. Some resources suggest that the browser optimises for these. I checked in Chrome, and it appears that each empty slot takes up 8 bytes.

```
Array( 0 ) = 208 bytes
Array( 1 ) = 232 bytes
Array( 2 ) = 240 bytes
Array( 3 ) = 248 bytes
```

This is very different from how I thought about it. I thought the array length was stored as a number, and empty slots would not take up any space. If it's true that each empty slot takes up 8 bytes per character, then an empty sparse array takes 4 times the space of the text string.

Comment (iseulde) [reply packages/rich-text/src/test/insert-object.js]: Of course, if we merge the three sparse arrays into one, we'd also create extra objects or arrays, so from a certain amount of formats, the size will be bigger.

**Comment by ellatrix** [comment]
@aduth I think there are a few options:

1. We merge `objects` and `lines` as they will never clash. We're storing some information that is linked to the replacement character. We could call this `replacements` or something like that. I can't find a better name that combines both. I have a slight preference for this solution as it feels a bit cleaner to me. Also, if we ever have to introduce another replacement character (I don't think we will), it remains usable.
2. We merge `objects`, `lines` and `formats` all into one sparse array. This is trickier: formats can mix with objects but not with lines (they could mix with lines but will be ignored, in my opinion, this makes it also inferior to 1). Since it's possible to have multiple kinds of information, we'd have to add another level of nesting by using an array or object: [ replacements, formats ] or  [ lines, objects, formats ] or { replacements, formats } or  { lines, objects, formats }, where using an object would increase the size. I don't see much benefits to this solution. Yes, we avoid a second sparse array, but there is other added complexity and the size of the whole value wouldn't always be smaller. Once there are formats at enough indices, all those extra arrays for each of those indices quickly overtake the size of one sparse array.
3. Of course, we could make it so that we _only_ wrap the formats in an extra array _if_ there is more than one kind at a given index, but this would make it even more complex.

In addition to (1), we could also consider dropping the sparse array if it's empty, at the cost of some added complexity.

**Comment by aduth** [comment]
>Since it's possible to have multiple kinds of information, we'd have to add another level of nesting by using an array or object:

If replacements and formats are mutually exclusive, could there be an option where we don't nest, but rather look at the type/shape/constructor of the value at a specified index?

i.e.

```
[ , , instanceof(FORMATS), instanceof(FORMATS), , instanceof(REPLACEMENTS), } ]
```

**Edit:** I realize after the fact you mention "formats can mix with objects but not with lines". What's the use-case for a format+object combination?

**Comment by ellatrix** [comment]
> What's the use-case for a format+object combination?

@aduth You could have an image as part of formatted text, like bolding text that includes an image, or a linked image.

**Comment by aduth** [comment]
>@aduth You could have an image as part of formatted text, like bolding text that includes an image, or a linked image.

Hmm, but even in this case, it can't really be said that the image itself is _bold_. Or at least, the application of "bold" has no impact on the appearance of the image, is that right? Or do we do it this way in part of the logic to determine whether new text would have the format applied, based on the format applied to the preceding entry (i.e. whether text added immediately adjacent the "bold" image becomes bolded).

**Comment by ellatrix** [comment]
@aduth it’s more than appearance. The tag has semantic value. Who am I to say what you should and shouldn’t be able to do? It’s valid HTML.

How about linking an image? Maybe a better real world example.

And no, we don’t look at it for formatting newly added text.

**Comment by ellatrix** [comment]
@aduth @mcsf I rebased. Not sure what else I can do here. You could argue that information to link the image should go in the image object, but I think that complicates everything.

**Comment by aduth** [comment]
I'll plan to give it another review pass, hopefully today.

File: packages/rich-text/src/concat.js [hunk 8]
```diff
@@ -3,6 +3,24 @@
...
+ * Concats a pair of rich text values. Not that this mutates `a` and does NOT
+ * normalise formats!
+ *
+ * @param  {Object} a Value to mutate.
+ * @param  {Object} b Value to add read from.
+ *
+ * @return {Object} `a`, mutated.
+ */
+export function mergePair( a, b ) {
+	a.formats = a.formats.concat( b.formats );
```
Comment (aduth) [inline packages/rich-text/src/concat.js]: Unsure if it makes a practical impact as far as one being more performant than the other, but if you're mutating, you could just as well:

```js
a.formats.push( ...b.formats );
```

File: packages/rich-text/src/get-last-child-index.js [hunk 9]
```diff
@@ -12,8 +12,8 @@ import { LINE_SEPARATOR } from './special-characters';
  *
  * @return {Array} The index of the last child.
  */
-export function getLastChildIndex( { text, formats }, lineIndex ) {
-	const lineFormats = formats[ lineIndex ] || [];
+export function getLastChildIndex( { text, replacements }, lineIndex ) {
+	const lineFormats = replacements[ lineIndex ] || [];
```
Comment (aduth) [inline packages/rich-text/src/get-last-child-index.js]: Variable should be renamed to reflect the fact it doesn't consume from `formats` ?

(Same note below for `formatsAtIndex`)

File: packages/rich-text/src/get-parent-line-index.js [hunk 10]
```diff
@@ -14,8 +14,8 @@ import { LINE_SEPARATOR } from './special-characters';
  *
  * @return {Array} The parent list line index.
  */
-export function getParentLineIndex( { text, formats }, lineIndex ) {
-	const startFormats = formats[ lineIndex ] || [];
+export function getParentLineIndex( { text, replacements }, lineIndex ) {
+	const startFormats = replacements[ lineIndex ] || [];
```
Comment (aduth) [inline packages/rich-text/src/get-parent-line-index.js]: Variable should be renamed to reflect the fact it doesn't consume from `formats` ?

(Same note below for `formatsAtIndex`)

(There are a couple other occurrences of this throughout the pull request)

File: packages/rich-text/src/apply-format.js [hunk 11]
```diff
@@ -52,14 +52,10 @@ export function applyFormat(
...
 			const previousFormat = newFormats[ startIndex - 1 ] || [];
-			const hasType = find( previousFormat, { type: format.type } );
 
 			return {
-				formats,
-				text,
-				start,
-				end,
-				formatPlaceholder: hasType ? undefined : format,
+				...value,
```
Comment (aduth) [inline packages/rich-text/src/apply-format.js]: In the equivalent function in the native implementation, we don't spread to preserve the other properties. Namely, `replacements` would be dropped. I don't think that's expected?

https://github.com/WordPress/gutenberg/blob/2889c29458489876a941cf4aaae093b10c1990e8/packages/rich-text/src/apply-format.native.js#L42-L51

https://github.com/WordPress/gutenberg/blob/2889c29458489876a941cf4aaae093b10c1990e8/packages/rich-text/src/apply-format.native.js#L60

Comment (aduth) [reply packages/rich-text/src/apply-format.js]: I'm finding similar issues in `remove-format.native.js`

File: packages/rich-text/src/test/apply-format.js [hunk 12]
```diff
@@ -61,7 +61,7 @@ describe( 'applyFormat', () => {
 		};
 		const expected = {
 			...record,
```
Comment (aduth) [inline packages/rich-text/src/test/apply-format.js]: The records in this file aren't "correct" in that they lack `replacements`, but I suppose if it's enough to satisfy the tests, it's not that big an issue.

File: packages/rich-text/src/test/change-list-type.js [hunk 13]
```diff
@@ -17,7 +17,8 @@ describe( 'changeListType', () => {
 
 	it( 'should only change list type if list item is indented', () => {
 		const record = {
-			formats: [ , ],
+			formats: [],
```
Comment (aduth) [inline packages/rich-text/src/test/change-list-type.js]: Is this meant to have changed, or should it have remained ?

```suggestion
			formats: [ , ],
```

A few other occurrences in the file. Unsure if it's the same sort of "the implementation doesn't bother with it, so its value doesn't matter" as in my previous comment.

File: packages/rich-text/src/to-dom.js [hunk 14]
```diff
@@ -122,7 +122,6 @@ function prepareFormats( prepareEditableTree = [], value ) {
 export function toDom( {
 	value,
 	multilineTag,
-	multilineWrapperTags,
```
Comment (aduth) [inline packages/rich-text/src/to-dom.js]: We still pass `multilineWrapperTags` to this function here:

https://github.com/WordPress/gutenberg/blob/2889c29458489876a941cf4aaae093b10c1990e8/packages/block-editor/src/components/rich-text/index.js#L941-L946

Can we expect that to continue working as expected?

Comment (aduth) [reply packages/rich-text/src/to-dom.js]: Also here:

https://github.com/WordPress/gutenberg/blob/2889c29458489876a941cf4aaae093b10c1990e8/packages/rich-text/src/test/to-dom.js#L24-L41

**Review by aduth — APPROVED** [review]
I trust you to make changes as necessary. Works great in my testing.

File: packages/rich-text/src/concat.js (hunk 8 above)
Comment (aduth) [reply packages/rich-text/src/concat.js]: > Unsure if it makes a practical impact as far as one being more performant than the other

788x more performant to use `Array#push`, if this is to be believed:

https://jsperf.com/javascript-array-concat-vs-push/4

Comment (ellatrix) [reply packages/rich-text/src/concat.js]: If we do that, each item that is not set will be set to `undefined`.

* `[ , , , ].concat( [ , , , ] )` gives you `[empty × 6]`
* `[ , , , ].push( ...[ , , , ] )` gives you `[empty × 3, undefined, undefined, undefined]`.

Not sure if there's another way.

File: packages/block-editor/src/components/rich-text/index.js [hunk 15]
```diff
@@ -984,7 +989,6 @@ export class RichText extends Component {
 			return toHTMLString( {
 				value,
 				multilineTag: this.multilineTag,
-				multilineWrapperTags: this.multilineWrapperTags,
```
[the remark this answers is not in the document]
Comment (ellatrix) [reply packages/block-editor/src/components/rich-text/index.js]: It's passed down to `toTree`. We no longer need the `multilineWrapperTags` context in `toTree` because we no longer need to go through each line format to determine if it's a regular format or a line format. The formats are separated, so we know for sure that they are line "formats", or information.

File: packages/rich-text/src/get-last-child-index.js (hunk 9 above)
Comment (ellatrix) [reply packages/rich-text/src/get-last-child-index.js]: Yeah, we could rename it. I'm not 100% sure on the naming tbh. What do we call these arrays holding information about a certain index? I left it as `formats` because in my head I still think about it as regular formats, line formats, and object formats. I do agree that this could benefit from better naming.

File: packages/rich-text/src/apply-format.js (hunk 11 above)
Comment (ellatrix) [reply packages/rich-text/src/apply-format.js]: I did not realise there was a `native` version, I think it was added recently. I have no idea why these files differ. There's no comment about it. No we have to maintain two files that do the same thing? Cc @hypest

Comment (ellatrix) [reply packages/rich-text/src/apply-format.js]: It was added in #12249. Cc @koke

File: packages/rich-text/src/test/apply-format.js (hunk 12 above)
Comment (ellatrix) [reply packages/rich-text/src/test/apply-format.js]: Yeah, it's a bit like reducer tests. You don't need a full valid state tree to test one.

File: packages/rich-text/src/test/change-list-type.js (hunk 13 above)
Comment (ellatrix) [reply packages/rich-text/src/test/change-list-type.js]: Thanks! Removed in 8c9def8.

File: packages/rich-text/src/to-dom.js (hunk 14 above)
Comment (ellatrix) [reply packages/rich-text/src/to-dom.js]: Thanks for catching! Removed in abde860.

File: packages/rich-text/src/apply-format.js (hunk 11 above)
Comment (ellatrix) [reply packages/rich-text/src/apply-format.js]: Fixed in 62fa458.

**Review by Tug — APPROVED** [review]
Mobile ✅

File: packages/rich-text/src/get-last-child-index.js (hunk 9 above)
Comment (ellatrix) [reply packages/rich-text/src/get-last-child-index.js]: I'm going to leave this one for now as I'm not sure about the naming. Until now I saw a format as the equivalent of an element. So in that sense, the naming is still correct.

File: packages/rich-text/src/apply-format.js (hunk 11 above)
Comment (ellatrix) [reply packages/rich-text/src/apply-format.js]: Updated everything for mobile, and was approved in https://github.com/WordPress/gutenberg/pull/13948#pullrequestreview-213902940. Thanks for catching this.

File: packages/rich-text/src/get-last-child-index.js (hunk 9 above)
Comment (aduth) [reply packages/rich-text/src/get-last-child-index.js]: > I left it as `formats` because in my head I still think about it as regular formats, line formats, and object formats. I do agree that this could benefit from better naming.

I'd wondered if it'd just be as simple as applying the new "replacement" nomenclature universally.

e.g. `lineReplacements` or `replacementsAtIndex`

File: packages/rich-text/src/concat.js (hunk 8 above)
Comment (aduth) [reply packages/rich-text/src/concat.js]: > If we do that, each item that is not set will be set to `undefined`.

TIL! Sparse arrays are very tricky, it seems 😄 

I don't see it being an issue. Just caught my attention as it seemed like it should behave the same. Since it doesn't, I see no reason to change.
