### PR TITLE
Annotation API: fix __experimentalGetPropsForEditableTreePreparation

### LINKED ISSUE #23428: The RichText __experimentalGetPropsForEditableTreePreparation API break the selection in  the editor
I'm using the "block-editor" package on third-party project. (asblocks)
and when I add  this  custom RichText format (it does nothing, it's just an empty format), I can't select text reliably anymore:

```
import { registerFormatType } from '@wordpress/rich-text';
import './style.css';

const FORMAT_NAME = 'asblocks/caret';

export const settings = {
	title: 'AsBlocks caret',
	tagName: 'mark',
	className: 'asblocks-caret',
	attributes: {
		id: 'id',
		className: 'class',
	},
	edit() {
		return null;
	},
	__experimentalGetPropsForEditableTreePreparation() {
		return {
			carets: [],
		};
	},
	__experimentalCreatePrepareEditableTree() {
		return ( formats ) => {
			return formats;
		};
	},
};

registerFormatType( FORMAT_NAME, settings );
```

Nothing that If I remove the `__experimentalGetPropsForEditableTreePreparation` function, the text selection works properly.

Screenshot of broken text selection:

selection

cc @ellatrix

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Fixes #23428.

When `__experimentalGetPropsForEditableTreePreparation` returns an object with multiple keys, the object itself is not a stable key that can be in turn returned as a key with `useSelect`.

In other words, this ends up being passed to `useSelect`, which will cause excessive rerenders:

```
{
  'core/format-bold': {
    somethingSelected,
    anotherThing,
  }
}
```

Solution: flatten the tree to:

```
{
  'core/format-bold.somethingSelected': somethingSelected,
  'core/format-bold.anotherThing': anotherThing,
}
```

So that `useSelect` can do its shallow equal magic.

## Testing Instructions

See #23428. Create a format that subscribes to the block editor store:

```js
{
 	name: 'asblocks/caret',
 	title: 'Example',
 	tagName: 'mark',
 	className: 'caret',
 	attributes: {},
 	edit() {
 		return null;
 	},
 	__experimentalGetPropsForEditableTreePreparation( select ) {
 		select( 'core/block-editor' );
 		return {};
 	},
 	__experimentalCreatePrepareEditableTree() {
 		return ( formats ) => {
 			return formats;
 		};
 	},
 }
```

> I wanted to add an e2e test, but it seems incredibly hard to write a test case that consistently fails in trunk. I tried to subscribe the test annotation format to the block editor store, which should cause a lot of re-renders on select, but the tests still pass.

https://github.com/WordPress/gutenberg/issues/23428#issuecomment-1192403771

### CODE REVIEW

**Comment by ellatrix** [comment]
Hm, I do notice another problem though. Multi select stopped working.

File: packages/format-library/src/default-formats.js [hunk 1]
```diff
@@ -13,7 +13,35 @@ import { subscript } from './subscript';
...
+	},
+	edit() {
+		return null;
+	},
+	__experimentalGetPropsForEditableTreePreparation(
+		select,
+		{ blockClientId }
+	) {
+		return {
+			carets: select( 'core/block-editor' ).getBlockName( blockClientId ),
```
Comment (ellatrix) [inline packages/format-library/src/default-formats.js]: For testing purposes.

**Comment by ellatrix** [comment]
Tests are passing, so that means the format is no longer causing any issues.

**Comment by ellatrix** [comment]
@msurdi Could you approve this PR if it works for you?

**Review by msurdi — APPROVED** [review]
