### PR TITLE
Fixed Random Collapse of Colors Setting Section

### LINKED ISSUE #32295: Block Settings: Colors section randomly collapses/loses focus
## Description

When setting a custom color in the Block Settings for the first time, the modal is closed and the focus is lost upon selection. This seems to be a regression. This was found as part of the [sixth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/05/12/fse-program-testing-call-6-stick-the-landing-pages/#comment-1648). 

## Step-by-step reproduction instructions

1. Add a paragraph block
2. Open the sidebar settings. 
3. Open Colors and select a custom color from one of the options.
4. Notice the Colors section collapses.

## Expected behaviour

Expect the color settings section to remain open unless I close it out. 

## Actual behaviour

Color settings section randomly closes upon making various selections.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/119908573-253bf380-bf10-11eb-8e7a-0684f6ed4d85.mov

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.7.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Chrome Version 89.0.4389.128

### PR DESCRIPTION
**Pull request by thisissandip**
Fixes https://github.com/WordPress/gutenberg/issues/32295

## Description
Fixed Random Collapse of Colors Setting Section on various selection.

The collapse used to occur when the link color is:
1. selected for the first time
2. removed/cleared and text/Background color settings are selected right after that.

This was happening because the `withElementsStyles` HOC returned different components when the link color is set and when it's not. Instead, `withElementsStyles` HOC should return a single component with different props based on the link color using conditional rendering.

## How has this been tested?
1. Select Block which supports color settings (eg. paragraph block)
2. Open sidebar settings.
3. Open Colors and select a custom color from one of the options.
4. The color settings panel should not collapse like it used to before.

## Screenshots 

https://user-images.githubusercontent.com/69596988/120441568-54d07d00-c3a2-11eb-800e-57c60545be8c.mov

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 

``

### CODE REVIEW

File: packages/block-editor/src/hooks/style.js [hunk 1]
```diff
@@ -246,9 +246,7 @@ export const withBlockControls = createHigherOrderComponent(
 const withElementsStyles = createHigherOrderComponent(
 	( BlockListBlock ) => ( props ) => {
 		const elements = props.attributes.style?.elements;
-		if ( ! elements ) {
-			return <BlockListBlock { ...props } />;
```
Comment (youknowriad) [inline packages/block-editor/src/hooks/style.js:250]: Yes, this causes a remount which is not great for `BlockEdit` components. We had similar issues in other hooks in the past. So yeah the fix here is looking good to me.

File: packages/block-editor/src/hooks/style.js [hunk 2]
```diff
@@ -259,17 +257,23 @@ const withElementsStyles = createHigherOrderComponent(
 
 		return (
 			<>
-				<style
-					dangerouslySetInnerHTML={ {
-						__html: styles,
-					} }
-				/>
+				{ elements && (
+					<style
```
Comment (youknowriad) [inline packages/block-editor/src/hooks/style.js:261]: Aside: (something for other PRs) Also noting that inline styles like that (which we do in layout as well), can cause CSS issues due to the new elements breaking `:first-child` selectors and things like that in editor styles.

@jorgefilipecosta @nosolosw @ellatrix We may need a dedicated way to inject these styles in the editor (and maybe even in the frontend) that doesn't suffer from these issues.

**Review by youknowriad — APPROVED** [review]
Let's get this in. We can address the "style elements" issue separately.

**Comment by thisissandip** [comment]
@youknowriad Thank you for reviewing and merging this PR! 😄

**Comment by youknowriad** [comment]
Check-picked into 10.8 release branch
