### PR TITLE
Try refactoring the reusable blocks to use a separate block editor

### LINKED ISSUE #7119: Reusable Blocks: Reimplement reusable block as embedded editor
At the moment, fetching reusable blocks also parses their content and insert them to the `editor`'s block list state. This approach have some drawbacks:

 - We need to maintain a cycle dependency between `blocks` and `shared blocks`
 - Fetching shared blocks from the server retriggers the parsing which means if it's currently rendered, the block will unmount/remount.

I tried simplifying the state in #7080 but it fails at dealing with the nested blocks.

The idea of the PR is to avoid having to parse the reusable blocks (content property) when loading them, and when we insert a reusable block into the editor, don’t parse it and add the parsed blocks into the editor’s state because these parsed blocks are not part of the post content but just a property of the reusable block and is already present in the state in its serialized form.

So when we insert the reusable block, its edit method is responsible of parsing the content and updating it when the user saves the reusable block’s form.

But the problem happens when we have inner blocks because the way we render the `InnerBlocks` we assume these are present in state, we don’t pass the list of blocks to show explicitly to the `BlockList` as opposed to the `BlockEdit` (root) where we can just pass the attributes of the block to show.

The path forward is not clear:

- My “perfectionism” tells me we should refactor our component to avoid relying too much on state `getBlock( uid )` and accepts blocks as props.
- But this is a lot of work and we lose a lot of flexibility in using selectors etc...
- We can also try to load another Gutenberg instance :man-shrugging: when clicking the “edit” button of a reusable block, but this obviously requires a lot of work to make Gutenberg reusable this way (which should benefit things like multiple Gutenberg instances in a page) and this also means we’d need to figure out where to show the inspector of this inner instance, should it be shown above the outer instance’s inspector.
- Or we should keep our current hack: (load the shared blocks inner blocks into state, but try to improve it in a way that we don’t remount the shared blocks when we update them/trigger another fetch)

related #5010 #5228

### LINKED ISSUE #12272: Undo – Redo: existing reusable blocks create an undo level
Tested on latest master 4.5.1 

- open an existing post that contains reusable blocks
- the reusable blocks take a few moments to fetch content and render, this is expected
- when they're fully rendered, the Undo button is active indicating there's an undo step in the history:

screenshot 2018-11-24 at 17 08 39

- click the Undo button
- the reusable blocks content disappears and a message "Block has been deleted or is unavailable" is shown:

screenshot 2018-11-24 at 17 08 49

- click the Redo button: the reusable blocks content gets restored

Expected: the Undo step to not be created and the reusable blocks content to not disappear

### LINKED ISSUE #12596: Reusable block not editable
**Describe the bug**
When editing a reusable block from a page or post, adding new blocks is impossible because the menu that pops up quickly closes and focus shifts back to the reusable block title. 

**To Reproduce**
1. Create reusable block
2. Insert reusable block on page or post
3. Click the edit button next to reusable block's name.
4. Attempt to add a block inside the reusable block using the plus button.

**Expected behavior**
The menu should stay open until a block is selected.

**Screenshots**
Here is a screencast showing the issue: https://www.dropbox.com/s/7o33s00o6k1qlrc/gutenberg-reusable-issue.mp4?dl=0

**Desktop (please complete the following information):**
 Linux Mint 18.3
 Firefox 63, also happens in Chrome.
 

**Smartphone (please complete the following information):**
Not tested

**Additional context**
Gutenberg 4.6.1
WP 4.9.8 vanilla install 2017 theme.

### LINKED ISSUE #15087: Reusable Blocks: Not working [+] button when there are multiple blocks.
**Describe the bug**

Related: #12596 

Not working [+] button when there are multiple blocks. 

Gutenberg 5.5.

**To reproduce**
1. Select multiple blocks.
2. Add to reusable blocks.
3. Edit contents in the blocks.

**Expected behavior**

a
b

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OS X 10.14.4
 - Browser Chrome 
 - Version 73.0.3683.103

### LINKED ISSUE #15979: Media & text Reusable blocks preview should be display proper
**Describe the bug**
Media & text Reusable blocks preview should be display proper.

**To reproduce**

1. Open Editor'
2. Click on 'Add block option'
3. Add Media & text block.
4. Add Content in the Media & text block.
5. Then Add block to the reusable block.
6. See the Preview of Reusable Block,

**Expected behavior**
 The preview should be display proper.

**Please find below Video**
https://www.screencast.com/t/kQ56g1hp

### LINKED ISSUE #16427: Reusable blocks issue with columns block
Hello everyone,

if you try to save a column block as “reusable block” and try to edit again you are no more able to click on the appender buttons.

The issue is present in the latest Gutenberg plugin 6.0 and also on the WordPress 5.2.2 version.

Here’s a video that explains how to reproduce the issue:
https://www.dropbox.com/s/31hevc639ztz2j6/reusable%20columns%20issue.mov?dl=0

Browse: Chrome

### LINKED ISSUE #16808: Reusable blocks preview not working.
The preview that shows when you hover reusable blocks in the inserter has regressed. It shows:

Capture d’écran 2019-07-30 à 12 13 01 PM

I tried debugging quickly. I think the issue comes from the fact that we use an embedded editor (separate blocks store) but we don't load the content of the reusable blocks in the sub reducer.

**Potential solutions**

 - Refactor the reusable blocks to use an embedded editor (There's some PRs in progress)
 - try to load the reusable blocks in the BlockEditorProvider used for the preview.

**Questions**

This used to work, so I'm curious when it regressed and what's the "hack" that allowed it to work previously.

cc @aduth @jorgefilipecosta

### LINKED ISSUE #17370: Moving a reusable block made of multiple blocks deletes blocks one by one
Create a reusable block composed of more than one block. When attempting to move the whole group, instead of moving the last block is removed until the group is empty.

(Saving the post and reloading makes the issue go away.)

### PR DESCRIPTION
**Pull request by youknowriad**
Closes #7119
Closes #12272 
Closes #12596 
Closes #15087 
Closes #15979
Closes #16427
Closes #16808
Closes #17370

This is the third attempt (and hopefully the last one) to use an embeddable editor to edit the reusable blocks.

**Todo**

 - [x] Extract the parent registry support to its own PR #14369 
 - [x] Extract the withRegistry HoC to its own PR #14370 
 - [x] Support reusable blocks without inner Blocks or with multiple inner blocks 
 - [x] Support the block inspector 
 - [x] Remove the useless core/template block.
 - [x] Tests

### CODE REVIEW

File: packages/block-library/src/block/edit.js [hunk 1]
```diff
@@ -58,65 +59,57 @@ class ReusableBlockEdit extends Component {
...
-				attributes={ { ...block.attributes, ...changedAttributes } }
-				setAttributes={ isEditing ? this.setAttributes : noop }
-			/>
+			<BlockEditorProvider
+				settings={ settings }
+				value={ blocks }
+				onChange={ this.setBlocks }
+				onInput={ this.setBlocks }
+			>
+				<div>test sdfsdf sdf sdf</div>
```
Comment (gziolo) [inline packages/block-library/src/block/edit.js]: 😸

File: packages/block-library/src/block/edit.js [hunk 2]
```diff
@@ -1,49 +1,80 @@
...
 
+/**
+ * Higher-order component which renders the original component with the current
+ * registry context passed as its `registry` prop.
+ *
+ * @param {WPComponent} OriginalComponent Original component.
+ *
+ * @return {WPComponent} Enhanced component.
+ */
+const withRegistry = createHigherOrderComponent(
```
Comment (youknowriad) [inline packages/block-library/src/block/edit.js]: This could be provided by default by the data module, it's used in at least two places.

File: packages/block-editor/src/store/selectors.js [hunk 3]
```diff
@@ -1129,7 +1131,8 @@ const canIncludeReusableBlockInInserter = ( state, reusableBlock, rootClientId )
 		return false;
 	}
 
-	const referencedBlockName = getBlockName( state, reusableBlock.clientId );
+	const referencedBlocks = __experimentalGetParsedReusableBlock( state, reusableBlock.id );
+	const referencedBlockName = referencedBlocks ? referencedBlocks[ 0 ].name : null;
```
Comment (youknowriad) [inline packages/block-editor/src/store/selectors.js]: Missing support for template reusable blocks

File: packages/block-library/src/block/edit.js [hunk 4]
```diff
@@ -52,71 +83,73 @@ class ReusableBlockEdit extends Component {
...
-				setAttributes={ isEditing ? this.setAttributes : noop }
-			/>
+			<RegistryProvider value={ this.registry }>
+				<BlockEditorProvider
+					settings={ settings }
+					value={ blocks }
+					onChange={ this.setBlocks }
+					onInput={ this.setBlocks }
+				>
+					<BlockList />
```
Comment (youknowriad) [inline packages/block-library/src/block/edit.js]: Support for the inspector sidebar is missing.

File: packages/block-editor/src/store/selectors.js [hunk 5]
```diff
@@ -1115,41 +1096,6 @@ const canIncludeBlockTypeInInserter = ( state, blockType, rootClientId ) => {
...
- * @param {?string} rootClientId Optional root client ID of block list.
- *
- * @return {boolean} Whether the given block type is allowed to be shown in the inserter.
- */
-const canIncludeReusableBlockInInserter = ( state, reusableBlock, rootClientId ) => {
-	if ( ! canInsertBlockTypeUnmemoized( state, 'core/block', rootClientId ) ) {
-		return false;
-	}
-
-	const referencedBlockName = getBlockName( state, reusableBlock.clientId );
```
Comment (youknowriad) [inline packages/block-editor/src/store/selectors.js]: Since a reusable block can have contain blocks, no blocks or a single block, I don't think it makes sense to validate if the content is "includable" in the inserter, we should only validate if `core/block` is allowed.

This was inconsistent before because of the `core/template` trick we had.

**Comment by aduth** [comment]
In thinking about this by my related comment at https://github.com/WordPress/gutenberg/pull/14491#issuecomment-474076793 , I might have thought that the purpose of `editor` as a module would align quite well to what the implementation of the reusable block should be: coordinating an underlying block editor as being sourced from and saved to a backing post, where the post happens to be of type `wp_block`. Was this considered? I note here that the implementation renders `BlockEditorProvider` directly.

**Comment by youknowriad** [comment]
> Was this considered?

No I didn't consider this but I can see how it could make sense. I feel that using `BlockEditor` instead can be more flexible/simple but that's just a guess.

File: packages/block-editor/src/store/index.js [hunk 6]
```diff
@@ -17,11 +17,15 @@ import controls from './controls';
  */
 const MODULE_KEY = 'core/block-editor';
 
-const store = registerStore( MODULE_KEY, {
+export const storeConfig = {
```
Comment (aduth) [inline packages/block-editor/src/store/index.js]: An alternative here to exposing all the implementation details (which, on the surface, is not exceedingly worrisome) is, as in #7453, exposing a `createStore` which registers the store given a registry (and I suppose some optional options object for the default case in applying the `persist` option).

https://github.com/WordPress/gutenberg/pull/7453/files#diff-adc2d694b934c0d37f4ae99f4595afc8L26

File: packages/block-editor/src/store/selectors.js (hunk 5 above)
Comment (aduth) [reply packages/block-editor/src/store/selectors.js]: Out of curiosity, is it something which could be extracted to its own pull request, if you're suggesting it ought not have been implemented this way in the first place?

Comment (youknowriad) [reply packages/block-editor/src/store/selectors.js]: No, I don't think it can because right now the reusable block `edit` function uses this parsed block with `BlockEdit` component to render it and update. It's very much tied to the way the reusable blocks are edited today as part of the global editor.

File: packages/block-editor/src/store/index.js (hunk 6 above)
Comment (youknowriad) [reply packages/block-editor/src/store/index.js]: My ideal API is this:

```js
const store1Config = {};
const store2Config = {};
const store1 = createStore( store1Config );
const store2 = createStore( store2Config );
const registry = createRegistry( [ store1, store2 ] );
const store3 = createStore( store2Config );
const subRegistry = createRegistry([ store1, store3 ]);
```

Unfortunately, this is not possible because the current `createStore` is dependent on the `registry` it's being used in. I explored whether we can completely separate the two but it's hard to do with the namespace stores.

--- 
This doesn't reply directly to your comment I guess but yeah, I feel that sharing configs is the way to go in general and registering should be part of the components mounting... The global registry makes this hard to achieve at the moment.

File: packages/block-library/src/block/edit.js [hunk 7]
```diff
@@ -20,30 +27,32 @@ import ReusableBlockEditPanel from './edit-panel';
...
 			// Start in preview mode when we're working with an existing reusable block
 			this.state = {
 				isEditing: false,
 				title: null,
-				changedAttributes: null,
+				blocks: [],
 			};
 		}
+
+		this.registry = createRegistry( { 'core/block-editor': storeConfig }, registry );
```
Comment (aduth) [inline packages/block-library/src/block/edit.js]: Working locally in a separate branch, I observe a few more issues with the cloned registry:

- The copied store will not include the [custom middlewares we apply](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/store/middlewares.js). As I remarked at #14513, we should probably plan to do away with those middlewares altogether.
- The copied registry will not (at least with the current implementation of parent registries) include the plugins used for the parent, so generator actions (controls plugin) will fail. It's unclear to me whether we should (a) inherit plugins from a parent registry or (b) force the implementer who creates a child registry to re-declare the plugins (i.e. include a few following `this.registry.use` here). If we choose to go the "B" route, it should also be noted that we couldn't pre-load the store configuration when calling `createRegistry`, as the control plugin is [implemented](https://github.com/WordPress/gutenberg/blob/27c0d00102341615df838d1df2a40f1e33ff7973/packages/data/src/plugins/controls/index.js#L17) to only handle controls for a store configuration _after_ it's been included as a plugin, not retroactively.

Comment (youknowriad) [reply packages/block-library/src/block/edit.js]: This just reinforces my ideas that:

 - `createNamespaceStore` would be better if it's independent from the registry (no need for registry argument) 
 - `use` is not as useful as it seems and both the controls and persistence plugins should be bundled as opt-in features in the `createNamespaceStore`

**Review by jorgefilipecosta — COMMENTED** [review]
Hi @youknowriad nice work on this changes things worked mostly well on my tests.

I found some bugs but I don't think they are critical and they are probably things we can address.

These firs tree ones are common to PR https://github.com/WordPress/gutenberg/pull/14715: 
- If we select a block inside a reusable block the inspector still says the selected block is the reusable block. It correctly shows the settings of the selected block.
- If we multi-select blocks inside a reusable block, the inspector does not show a multi-select indication. I think we can solve this problem and the previous problem using a new slot that contains all the block inspector UI, similar to what I did in #16203.
- If we have a block selected inside the reusable block editor and we insert a block using the global inserter the block gets inserted after the reusable block and not inside the reusable block.


I think we need the SelectionObserver available on https://github.com/WordPress/gutenberg/pull/14715 and also used as part of the widgets work https://github.com/WordPress/gutenberg//blob/64a8a7c5208324b5308d2298bf0f98c906cfd66f/packages/edit-widgets/src/components/widget-area/selection-observer.js. If we could extract it to be something generic it would be awesome.
Without it, we may have blocks selected on the top level and on multiple reusable blocks but we only have one slot for the inspector and the formats so we may get a broken behavior:
Screenshot 2019-08-15 at 17 57 15


The block drag & drop UI shows indication I can move blocks between the top and reusable blocks but nothing happens on the drop (complex to solve not a blocker).


There is some overflow between to blocks inside reusable blocks and the border of the reusable block and on the preview e.g: when the preview a reusable block with a wide aligned cover block.
image

If I edit a reusable block and select block inside it and then go to the global inserter the previews of other reusable blocks don't appear.

I can now insert a reusable block inside itself which crashes the editor on save of the reusable block, and crashes the editor each time we try to open the post after that. I guess if the post is published it may also crash the website frontend and given that the user can not edit the post, it may be hard to recover from this mistake. The reusable blocks also stop appearing on the inserter even on different posts.

File: packages/block-library/src/block/edit.js [hunk 8]
```diff
@@ -52,79 +60,81 @@ class ReusableBlockEdit extends Component {
...
-				setAttributes={ isEditing ? this.setAttributes : noop }
-			/>
+			<BlockEditorProvider
+				settings={ settings }
+				value={ blocks }
+				onChange={ this.setBlocks }
+				onInput={ this.setBlocks }
+			>
+				<WritingFlow>
+					<BlockList />
```
Comment (jorgefilipecosta) [inline packages/block-library/src/block/edit.js]: I think we need to add ObserveTyping between WritingFlow and BlockList, if I'm in a paragraph inside reusable blocks and I start typing the toolbar never disappears.

File: packages/editor/src/store/actions.js [hunk 9]
```diff
@@ -800,19 +800,19 @@ export function __experimentalDeleteReusableBlock( id ) {
...
  *
- * @param {number} id    The ID of the reusable block to update.
- * @param {string} title The new title.
+ * @param {number} id      The ID of the reusable block to update.
+ * @param {Object} changes The changes to apply.
  *
  * @return {Object} Action object.
  */
-export function __experimentalUpdateReusableBlockTitle( id, title ) {
+export function __experimentalUpdateReusableBlock( id, changes ) {
```
Comment (jorgefilipecosta) [inline packages/editor/src/store/actions.js]: I don't think reusable blocks functionality should be part of the editor store. Why can't we have and edit reusable blocks in the widgets screen? Maybe we should have a store for reusable blocks? I guess the work @epiqueras is doing with entities may also help us, maybe we can update the entity but don't save it right away and just update the entity of that reusable block.

Comment (youknowriad) [reply packages/editor/src/store/actions.js]: Fair question. I think to be honest we can probably remove all of this. Even without the refactor @epiqueras we have all what we need in the core store to fetch and save the reusable blocks (without edits since it's a separate flow). I just didn't want to make a bigger PR and tried to solve the main issue we had which is the fact that we were loading the parsed blocks of the reusable blocks in the default block editor reducer. (Hence the high number of fixed issues)

Comment (epiqueras) [reply packages/editor/src/store/actions.js]: We can use `EntityHandlers` to make a reusable block dead simple. I'm working on some updates that will make its flexibility clearer to you.

**Comment by youknowriad** [comment]
> If we select a block inside a reusable block the inspector still says the selected block is the reusable block. It correctly shows the settings of the selected block.

> If we multi-select blocks inside a reusable block, the inspector does not show a multi-select indication. I think we can solve this problem and the previous problem using a new slot that contains all the block inspector UI, similar to what I did in #16203.

> If we have a block selected inside the reusable block editor and we insert a block using the global inserter the block gets inserted after the reusable block and not inside the reusable block.

All these issues are similar: technically speaking, the selected block is still the reusable block since the inner block is not in the root block list. 

I think we may need something to delimit the two levels in the inspector somehow.
We may also add a new inserter inside the reusable block's header.

It can be difficult to do properly so I'm wondering how blocking are these issues.

**Comment by youknowriad** [comment]
This conversation makes me think whether it's better to use a "Modal" to edit the reusable block instead of trying to edit it inline. (A full screen modal could be better maybe). Because if we think a bout it, we're in a completely different flow once we edit the content of a reusable block. Thoughts @jasmussen @mapk

**Comment by jasmussen** [comment]
> This conversation makes me think whether it's better to use a "Modal" to edit the reusable block instead of trying to edit it inline. (A full screen modal could be better maybe). Because if we think a bout it, we're in a completely different flow once we edit the content of a reusable block. Thoughts 

Yep, agree. I believe this idea has been floated in the past also. Right now there's a use case that makes for a somewhat compromised experience: you can edit a draft post that features a reusable block, and if you edit this reusable block even though the post remains in a draft state, the changes you make affect the _public and published site_. While this is intentional, making the experience of editing distinctly visually different from that of editing a post, we can make it more clear that any changes you make propogate to live site, regardless of post state. 

Whether this is a modal, or a separate section, there might be options here. Given we have been discussing block areas and how those might be edited, it might be worth looking at reusable block editing in the same light.

File: packages/editor/src/store/actions.js (hunk 9 above)
Comment (youknowriad) [reply packages/editor/src/store/actions.js]: I don't think `EntityHandlers` are of any help here because the consumer and the producer are at the same level here so we can just call the `core` module directly.

**Comment by jasmussen** [comment]
Testing the current state of this PR just now, there are only few visual changes for the user. Notably, the sidebar now indicates a reusable block when you're editing the contents:

Screenshot 2019-08-16 at 09 51 10

This is good, for the context specific changes mentioned just a moment ago. I also understand based on the description how many bugs this PR fixes, and how this PR makes for a much better foundation. This is important, and the bugs are good to fix.

The global inserter inserts after the reusable block, rather than inside it where the selected block might be. But right now in master, I can't even get the global inserter to work inside the block, so the fact that it now works, even if it appends after, and the inbetween inserter works now, this is vastly improved.

Honestly this feels like a big step forward, and that the next step should probably involve us thinking about editing reusable blocks entirely in a separate screen (see https://github.com/WordPress/gutenberg/pull/14367#issuecomment-521906630). This PR, as I understand it, will also make that easier to do. In that light, 👍 👍

**Comment by mapk** [comment]
Thanks for the ping, @youknowriad! 

While testing this, as @jorgefilipecosta mentioned above, I feel it's a bit awkward to see the Reusable block description in the sidebar when I'm editing an inner block. That felt disconnected for me, and I'm not entirely sure why that change is happening. So as you mentioned, I also think we should separate them visually in the Inspector somehow.

In FF, the sibling inserter is overlapped with the border of the block in some instances. See screenshot below:

Screen Shot 2019-08-16 at 7 58 39 AM

> This conversation makes me think whether it's better to use a "Modal" to edit the reusable block instead of trying to edit it inline.

Initially I wasn't sure about this, but the more I fiddle with it, the more I agree. @jasmussen makes some good points for this above. Pulling the editing experience into a modal help convey that editing this block may effect other uses of it elsewhere.

**Comment by epiqueras** [comment]
I don't think a modal is the right approach, it would feel really clunky and disconnected.

@jasmussen @mapk @jorgefilipecosta @youknowriad 

This PR: https://github.com/WordPress/gutenberg/pull/17020

Builds a foundation for multi-post editing a lá https://github.com/WordPress/gutenberg/pull/16565

Here is a demo:

https://videopress.com/v/t15UrCR6

This foundation can be used to power any block areas, whether template parts or reusable blocks and doesn't introduce any of the issues breaking up the block list and having multiple block editors does:

>If we select a block inside a reusable block the inspector still says the selected block is the reusable block. It correctly shows the settings of the selected block.

#17020 will show whatever block is selected, because it uses one single block list.

>If we multi-select blocks inside a reusable block, the inspector does not show a multi-select indication. I think we can solve this problem and the previous problem using a new slot that contains all the block inspector UI, similar to what I did in #16203.

Also not a problem in #17020, because I used a single block list.

>If we have a block selected inside the reusable block editor and we insert a block using the global inserter the block gets inserted after the reusable block and not inside the reusable block.

Also not a problem in #17020.

It will also give us the flexibility to have nested save flows. There is no reason you shouldn't be able to edit a reusable block in "draft" mode.

There are lots of things we can do within the context of the same block list (without modals) to emphasize a block is syncing somewhere else than the currently edited post, we could play around with borders, labels, etc, and when we want to focus on a specific block, we can leverage the "modes/zoom" feature introduced in #16565.

File: packages/editor/src/store/actions.js (hunk 9 above)
Comment (epiqueras) [reply packages/editor/src/store/actions.js]: It can do both. Like with the Site Title block: https://github.com/WordPress/gutenberg/pull/17020#issuecomment-521869286

You get a lot more stuff for free than if you use `core` directly.

Comment (youknowriad) [reply packages/editor/src/store/actions.js]: I know but I think it's wrong and useless. (we should probably continue this discussion in the other PR).

**Comment by jasmussen** [comment]
> I don't think a modal is the right approach, it would feel really clunky and disconnected.

I consider a modal dialog to be _one option_, but not necessarily the best one. Separate editors is another, but then the UI needs to be able to accommodate the context, i.e. show relationship between post elements. I can dabble with some mockups if you like?

**Comment by youknowriad** [comment]
Should we move forward here. Granted that it's not perfect but I feel it's already way better than master. (See number of closed issues)

**Review by jorgefilipecosta — COMMENTED** [review]
I agree that what we have in this PR is much better than what we have in master. Most of the problems I identified are not blockers.
Personally, I think that before the merge we should address a block margins problem that we don't have on master:
Screenshot 2019-08-20 at 20 31 37

It would be nice if we can have the SelectionObserver available on #14715 to avoid the bugs of multiple toolbars, multiple block inspectors because we have multiple blocks selected at the same time. But I think it is optional and if you think it is better we can leave for a follow-UP PR.

Maybe, we may find some overlap with our entities refactor when we implement things like template parts but for now, I guess we can advance on this approach, given that it mostly ready and the problems identified are related with multiple block editors which is something we want to be robust even if we end not making use of it.

File: packages/data/src/registry.js [hunk 10]
```diff
@@ -191,5 +191,9 @@ export function createRegistry( storeConfigs = {}, parent = null ) {
 		parent.subscribe( globalListener );
 	}
 
+	if ( parent ) {
```
Comment (epiqueras) [inline packages/data/src/registry.js]: This got duplicated, probably from a bad rebase.

File: packages/editor/src/store/actions.js (hunk 9 above)
Comment (epiqueras) [reply packages/editor/src/store/actions.js]: >we have all what we need in the core store to fetch and save the reusable blocks

Yes, we can do it directly in `core/block`'s `edit`.

**Review by epiqueras — DISMISSED** [review]

**Comment by mapk** [comment]
I've noticed a bit of a problem here. When converting blocks to be reusable, the output in the reusable block becomes extremely long. Can we fix this before merging anything?

reusable

**Comment by paaljoachim** [comment]
I am really looking forward to seeing this merged!
Thanks.

**Comment by youknowriad** [comment]
Good catch @mapk it should be fixed now.

**Comment by senadir** [comment]
this fixes https://github.com/WordPress/gutenberg/issues/17370

**Review by senadir — APPROVED** [review]
I've manually tested this PR against each issue it indicate and it fixed each one of them, also it close other related PRs, it works fine, I cannot see any immediate problems for now, it would close some issues that makes reusable blocks actually reusable (appending, moving, previewing).
fundamentally I think we're all approving this approach, so I'm all in into merging this and seeing what could surface later

**Comment by youknowriad** [comment]
Let's try this. Thanks all.

**Comment by talldan** [comment]
This also seems to fix https://github.com/WordPress/gutenberg/issues/17178 🎉
