### PR TITLE
Rich Text: also strip object replacement character when removing padding

### LINKED ISSUE #34602: Object Replacement Character in post title crashes Gutenberg 11.4.0/11.4.1
### Description

I am able to create a new post with a post title containing the OBJ character, after saving or publishing it and exiting the editor, the editor crashes when trying to re-open the post for editing. I was unable to replicate the issue using Gutenberg 11.3.0

Sample post title: "This post title crashes Gutenberg `&#xfffc;`"

### Step-by-step reproduction instructions

1. Create a new post
2. Use a post title with the OBJ character
3. Save or publish the post
4. Exit the editor
5. Re-open the post for editing
6. Editor crashes

### Screenshots, screen recording, code snippet

Screen Shot 2021-09-06 at 2 34 34 PM
Screen Shot 2021-09-06 at 2 34 25 PM

### Error text from Gutenberg
```
pe@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/rich-text/index.min.js?ver=8f70a366b9cae91a6f5753db0674024a:1:18233
fe@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/rich-text/index.min.js?ver=8f70a366b9cae91a6f5753db0674024a:1:17172
Ee@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/rich-text/index.min.js?ver=8f70a366b9cae91a6f5753db0674024a:1:18650
xe@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/rich-text/index.min.js?ver=8f70a366b9cae91a6f5753db0674024a:1:19083
b@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/rich-text/index.min.js?ver=8f70a366b9cae91a6f5753db0674024a:1:30090
C@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/rich-text/index.min.js?ver=8f70a366b9cae91a6f5753db0674024a:1:30848
nt/L<@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/rich-text/index.min.js?ver=8f70a366b9cae91a6f5753db0674024a:1:32170
x/<@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/compose/index.min.js?ver=0f1f9e9ebb624d4dfb57670a95cb1653:1:22833
A@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/compose/index.min.js?ver=0f1f9e9ebb624d4dfb57670a95cb1653:1:24939
P/<@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/compose/index.min.js?ver=0f1f9e9ebb624d4dfb57670a95cb1653:1:25375
A@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/compose/index.min.js?ver=0f1f9e9ebb624d4dfb57670a95cb1653:1:24939
P/<@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/compose/index.min.js?ver=0f1f9e9ebb624d4dfb57670a95cb1653:1:25375
Qj@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:177:1
unstable_runWithPriority@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26
Za@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8
eb@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:170:165
gf@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:162:319
$g/<@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:230
unstable_runWithPriority@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26
Za@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8
$g@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:178
ja@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:111
Pa@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:157:212
Me@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:110:252
e@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/data/index.min.js?ver=da4272fbc833ab25871c55f89400d555:1:19841
t@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/data/index.min.js?ver=da4272fbc833ab25871c55f89400d555:1:19908
c/t.subscribe/o<@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/data/index.min.js?ver=da4272fbc833ab25871c55f89400d555:1:14312
instantiate/b</<@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/data/index.min.js?ver=da4272fbc833ab25871c55f89400d555:1:13434
y@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/data/index.min.js?ver=da4272fbc833ab25871c55f89400d555:1:6847
o/</</<@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/redux-routine/index.min.js?ver=7a21a7d0e50a3686a159176880d88a37:1:8566
A/</<@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/data/index.min.js?ver=da4272fbc833ab25871c55f89400d555:1:8792
P/</</<@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/data/index.min.js?ver=da4272fbc833ab25871c55f89400d555:1:9138
dispatch@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/data/index.min.js?ver=da4272fbc833ab25871c55f89400d555:1:7707
o/</o</<@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/redux-routine/index.min.js?ver=7a21a7d0e50a3686a159176880d88a37:1:8353
n/<@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/redux-routine/index.min.js?ver=7a21a7d0e50a3686a159176880d88a37:1:3781
n@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/redux-routine/index.min.js?ver=7a21a7d0e50a3686a159176880d88a37:1:3756
u/<@https://ephemeral-mdrovdahl-20210901.atomicsites.blog/wp-content/plugins/gutenberg/build/redux-routine/index.min.js?ver=7a21a7d0e50a3686a159176880d88a37:1:3710
```

### Environment info

```
### wp-core ###

version: 5.8
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /srv/htdocs/__wp__
wordpress_size: 50.37 MB (52816824 bytes)
uploads_path: /srv/htdocs/wp-content/uploads
uploads_size: 0.00 B (0 bytes)
themes_path: /srv/htdocs/wp-content/themes
themes_size: 3.61 MB (3783307 bytes)
plugins_path: /srv/htdocs/wp-content/plugins
plugins_size: 115.32 MB (120922407 bytes)
database_size: 656.00 KB (671744 bytes)
wpcomsh-disk-space-used: 210.9 MB
wpcomsh-disk-space-quota: 200.0 GB

### wp-dropins (2) ###

advanced-cache.php: true
object-cache.php: true

### wp-active-theme ###

name: Twenty Twenty-One (twentytwentyone)
version: 1.4
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, automatic-feed-links, title-tag, post-formats, post-thumbnails, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, custom-background, editor-color-palette, editor-gradient-presets, responsive-embeds, custom-line-height, experimental-link-color, custom-spacing, custom-units, widgets
theme_path: /srv/htdocs/wp-content/themes/twentytwentyone
auto_update: Disabled

### wp-mu-plugins (1) ###

WP.com Site Helper: author: (undefined), version: (undefined)

### wp-plugins-active (1) ###

Gutenberg: version: 11.4.1, author: Gutenberg Team, Auto-updates enabled

### wp-plugins-inactive (9) ###

Akismet Anti-Spam: version: 4.1.11, author: Automattic (latest version: 4.1.12), Auto-updates disabled
AMP: version: 2.1.4, author: AMP Project Contributors, Auto-updates disabled
CoBlocks: version: 2.16.0, author: GoDaddy, Auto-updates disabled
Crowdsignal Forms: version: 1.5.6, author: Automattic (latest version: 1.5.7), Auto-updates disabled
Crowdsignal Polls & Ratings: version: 3.0.0, author: Automattic, Inc., Auto-updates disabled
Jetpack: version: 10.0, author: Automattic, Auto-updates disabled
Layout Grid: version: 1.7, author: Automattic, Auto-updates disabled
Page Optimize: version: 0.5.1, author: Automattic, Auto-updates disabled
WordPress.com Editing Toolkit: version: 3.13942, author: Automattic (latest version: 3.14278), Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 2047M
upload_max_filesize: 2047M
max_effective_size: 2 GB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 4.19.0-17-amd64 x86_64
httpd_software: nginx
php_version: 7.4.23 64bit
php_sapi: fpm-fcgi
max_input_variables: 6144
time_limit: 1200
memory_limit: 512M
max_input_time: 1200
upload_max_filesize: 2047M
php_post_max_size: 2047M
curl_version: 7.78.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: false
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 10.4.20-MariaDB-log
client_version: mysqlnd 7.4.23

### wp-constants ###

WP_HOME: https://ephemeral-mdrovdahl-20210901.atomicsites.blog
WP_SITEURL: https://ephemeral-mdrovdahl-20210901.atomicsites.blog
WP_CONTENT_DIR: /srv/htdocs/wp-content
WP_PLUGIN_DIR: /srv/htdocs/wp-content/plugins
WP_MEMORY_LIMIT: 512M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: latin1
DB_COLLATE: latin1_swedish_ci

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by gwwar**
Fixes https://github.com/WordPress/gutenberg/issues/34602. Rich text instances should ignore the object replacement character U+FFFC, since this is used internally by the package.

Changes here strip this special character when we remove other whitespace characters like `u+feff`,

### Testing Instructions
- related unit tests pass
- Try manually adding an object replacement character to a rich text instance. One way of doing this is pasting in a post title like `This post title crashes Gutenberg &#xfffc;`
- Save the post
- Re-open the post for editing
Verify that no JS errors are thrown

| Before | After |
|-----|-----|
| CleanShot 2021-09-15 at 10 12 21 | CleanShot 2021-09-15 at 10 10 54 |

### CODE REVIEW

File: packages/rich-text/src/create.js [hunk 1]
```diff
@@ -306,15 +306,18 @@ function collapseWhiteSpace( string ) {
...
 
 /**
- * Removes padding (zero width non breaking spaces) added by `toTree`.
+ * Removes padding (zero width non breaking spaces added by `toTree` and object replacement characters).
  *
  * @param {string} string
  */
 function removePadding( string ) {
-	return string.replace( ZWNBSPRegExp, '' );
+	return string.replace( REMOVE_PADDING_REGEX, '' );
```
Comment (mkaz) [inline packages/rich-text/src/create.js]: Thank you for the better name :grin:

File: packages/rich-text/src/create.js [hunk 2]
```diff
@@ -306,15 +306,18 @@ function collapseWhiteSpace( string ) {
 	return string.replace( /[\n\r\t]+/g, ' ' );
 }
 
-const ZWNBSPRegExp = new RegExp( ZWNBSP, 'g' );
+const REMOVE_PADDING_REGEX = new RegExp(
+	`[${ ZWNBSP }${ OBJECT_REPLACEMENT_CHARACTER }]`,
```
Comment (mkaz) [inline packages/rich-text/src/create.js]: Do you want two `?` here, after each character since either can be optional?

Try with this post title: `My test &#xfffc; post title`

**Review by mkaz — CHANGES_REQUESTED** [review]

File: packages/rich-text/src/create.js (hunk 2 above)
Comment (mkaz) [reply packages/rich-text/src/create.js]: It might be different for what this function is doing. So my test title is not relevant.
I still think you will want a `?` at the end of the OBJ character regex in case it didn't get inserted, you still want the padding removed

Comment (gwwar) [reply packages/rich-text/src/create.js]: `[]` notes an allowed character set, so the `?` shouldn't be required. What behavior are you seeing? It could be that I'm not escaping the values here properly.

Comment (gwwar) [reply packages/rich-text/src/create.js]: Hmm interesting, maybe I'll just write this as a literal regex, I do see different behavior.

Comment (gwwar) [reply packages/rich-text/src/create.js]: Good catch @mkaz , updated in https://github.com/WordPress/gutenberg/pull/34851/commits/146f347fa1082ecfa38323177f6cfcc2f7588606

So I think what was happening is that some characters can be expressed as two unicode codepoints, which is why the character classes didn't work as I expected.

Eg the only examples I saw for unicode + character classes use ranges https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes

I added a test case to make sure we're matching what we expect, but I'm open to a simpler regex. Maybe @dmsnell may have an idea?

Comment (mkaz) [reply packages/rich-text/src/create.js]: Looks good :+1:

**Review by mkaz — APPROVED** [review]

File: packages/rich-text/src/create.js (hunk 2 above)
Comment (dmsnell) [reply packages/rich-text/src/create.js]: did you also try adding the `u` flag to this version of the `RegExp`? I only see `g` here but I see `u` in the new pattern.

**Comment by dmsnell** [comment]
Probably I shouldn't get too involved here because I'm sensitive to this stuff _and_ ignorant about what's going on. Still, why are we dealing with `U+FFFC` and why is it even coming into play here? Obviously this prevents a block crash and so it's fine, but isn't it also evident that we have a failure deeper in the stack? Maybe in `RichText`?

File: packages/rich-text/src/create.js (hunk 2 above)
Comment (gwwar) [reply packages/rich-text/src/create.js]: Yes, see: https://github.com/WordPress/gutenberg/pull/34851/files#diff-30f49ba076928df4fcb8cc0fc0e6123fe85a619dcd9721686f5429de8ab1a2ccR313

**Comment by gwwar** [comment]
> Still, why are we dealing with U+FFFC and why is it even coming into play here?

@dmsnell The TL;DR is that it's used internally in rich text. We should ignore any user provided usages to avoid errors being thrown during tree creation.

File: packages/rich-text/src/create.js (hunk 2 above)
Comment (dmsnell) [reply packages/rich-text/src/create.js]: thanks, I was talking about in the [version of the code](https://github.com/WordPress/gutenberg/pull/34851/commits/43d7c2c88f305f14fe22587d78b6e2e619967c44#diff-30f49ba076928df4fcb8cc0fc0e6123fe85a619dcd9721686f5429de8ab1a2ccR309-R312) this comment thread is about.

```ts
const REMOVE_PADDING_REGEX = new RegExp(
 	`[${ ZWNBSP }${ OBJECT_REPLACEMENT_CHARACTER }]`,
 	'g'
 );
```

confused by this "some characters can be expressed as two unicode codepoints"

**Comment by dmsnell** [comment]
> We should ignore any user provided usages to avoid errors being thrown during tree creation.

That makes sense. This isn't really about padding then so much as it is about removing reserved characters…? I guess that's what causes the crash? You enter a `U+FFFC` manually and then `RichText` crashes when processing it.

**Comment by gwwar** [comment]
> This isn't really about padding then so much as it is about removing reserved characters…? I guess that's what causes the crash? You enter a U+FFFC manually and then RichText crashes when processing it.

💯 yes that's the gist of it.

File: packages/rich-text/src/create.js (hunk 2 above)
Comment (dmsnell) [reply packages/rich-text/src/create.js]: Discussed in Slack, sharing here the summary: our RegExp pattern uses the `g` flag and is a globally-shared variable, meaning it stores state in `lastIndex` after every use. While I'm not sure why the updated RegExp is working in the tests (since it also globally shares state), but `[\uFEFF\uFFFC]` works fine _if_ resetting state. I'd argue that it's clearer to have that construction anyway from a readability and semantic view since `(A?|B?)` is a bit weird _and_ introduces alteration which the character class doesn't.

Either way I'd recommend resetting the `RegExp` between calls _or_ changing it to a function that produces that pattern fresh. For instance,

```ts
export const REMOVE_PADDING_REGEX = () => /[\uFEFF\uFFFC]+/gu;
```

The tests will need updating since they are testing the `RegExp` pattern itself and not the behavior of `removePadding`. We could consider shifting the tests to focus on that function and its interface too in order to gain some implementation freedom.

Comment (gwwar) [reply packages/rich-text/src/create.js]: Nice catch on regex state @dmsnell ! I've updated test cases and renamed the function to be clearer as well in 6bb137e

File: packages/rich-text/src/create.js [hunk 3]
```diff
@@ -306,15 +305,14 @@ function collapseWhiteSpace( string ) {
...
- * Removes padding (zero width non breaking spaces) added by `toTree`.
+ * Removes reserved characters used by rich-text (zero width non breaking spaces added by `toTree` and object replacement characters).
  *
  * @param {string} string
  */
-function removePadding( string ) {
-	return string.replace( ZWNBSPRegExp, '' );
+export function removeReservedCharacters( string ) {
+	//with the global flag, note that we should create a new regex each time OR reset lastIndex state.
+	return string.replace( /[\uFEFF\uFFFC]/gu, '' );
```
Comment (getdave) [inline packages/rich-text/src/create.js]: Are we able to variablise the characters so "reserved "characters" is self documenting? At the moment I guess I need to know the char codes to understand which characters are being stripped here.

File: packages/rich-text/src/test/create.js [hunk 4]
```diff
@@ -122,4 +123,24 @@ describe( 'create', () => {
...
 	} );
+
+	it( 'removeReservedCharacters should remove all reserved characters', () => {
+		expect(
+			removeReservedCharacters( `${ OBJECT_REPLACEMENT_CHARACTER }` )
+		).toEqual( '' );
+		expect( removeReservedCharacters( `${ ZWNBSP }` ) ).toEqual( '' );
+		expect(
+			removeReservedCharacters(
+				`${ OBJECT_REPLACEMENT_CHARACTER }c${ OBJECT_REPLACEMENT_CHARACTER }at${ OBJECT_REPLACEMENT_CHARACTER }`
```
Comment (getdave) [inline packages/rich-text/src/test/create.js:134]: 😆 🐈

**Comment by ellatrix** [comment]
> Try manually adding an object replacement character to a rich text instance.

Interesting that users are pasting this character. Where are they getting this from? Maybe it's leaking somewhere when copying text? It's interesting that this only starts happening now, we've been using this character internally for a long time.

File: packages/rich-text/src/create.js (hunk 3 above)
Comment (ellatrix) [inline packages/rich-text/src/create.js]: It would be good to use `OBJECT_REPLACEMENT_CHARACTER` and `ZWNBSP` form './special-characters', both of which are already imported above.

**Review by ellatrix — APPROVED** [review]

**Review by getdave — APPROVED** [review]
Tested and verified this no longer crashes the editor.

File: packages/rich-text/src/create.js (hunk 3 above)
Comment (gwwar) [reply packages/rich-text/src/create.js]: Updated in 4930660 👍 I forgot to go back to the constructor while debugging why the original regex didn't work. (Eg when reusing a regex with the global flag `lastIndex` needs to be reset for a second call).

Comment (gwwar) [reply packages/rich-text/src/create.js]: 👍 updated in https://github.com/WordPress/gutenberg/pull/34851/commits/493066078942f8483e14e91f005d6a0053748137

**Comment by gwwar** [comment]
Thanks for the reviews @ellatrix @getdave @dmsnell @mkaz ! I'll go ahead and merge this once tests are green.

> Interesting that users are pasting this character. Where are they getting this from?

I asked folks and some reports are from users who are copying text from MS Word. It's definitely something to keep an eye on though!
