### PR TITLE
Fix allowed patterns check

### LINKED ISSUE #32139: Some block patterns do not show in the inserter
## Description

When testing the block patterns that are [planned for Twenty Fourteen](https://core.trac.wordpress.org/ticket/51103),
I learnt that the patterns show correctly in 10.6.2 but not in 10.7 RC1.
With 10.7 RC1, only two of the patterns show (summary and contact).

I was able to reproduce this in my own themes. It seems to be related to spacing inside the `content`.

The following does not work, the pattern is not selectable:
```
register_block_pattern(
		'twentyfourteen/list',
		array(
			'title'         => esc_html__( 'List', 'twentyfourteen' ),
			'categories'    => array( 'twentyfourteen' ),
			'viewportWidth' => 1000,
			'content'       => '<!-- wp:columns -->
								<div class="wp-block-columns"><!-- wp:column {"width":"40%"} -->
								<div class="wp-block-column" style="flex-basis:40%">
								... truncated
```

The following does work:
```
register_block_pattern(
		'twentyfourteen/list',
		array(
			'title'         => esc_html__( 'List', 'twentyfourteen' ),
			'categories'    => array( 'twentyfourteen' ),
			'viewportWidth' => 1000,
			'content'       => '<!-- wp:columns --><div class="wp-block-columns"><!-- wp:column {"width":"40%"} --><div class="wp-block-column" style="flex-basis:40%"><!-- wp:heading {"style":{"typography":{"fontSize":45}}} --><h2 style="font-size:45px">' . esc_html__( '2001', 'twentyfourteen' ) . '</h2><!-- /wp:heading --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph --><p><em>' . esc_html__( 'My first year of traveling. I visited China, Thailand, Japan, and India.', 'twentyfourteen' ) . '</em></p><!-- /wp:paragraph --></div><!-- /wp:column --></div>
... truncated

```

## Step-by-step reproduction instructions

1. Download the patch for the patterns in Twenty Fourteen, or copy the pattern code into your current theme.
2. In the editor, open the inserter, select patterns, select the Twenty Fourteen category, and see that only two patterns show.

## Expected behaviour

All registered patterns should show

## Actual behaviour

Only two of the patterns show.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.7.0 RC1
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Twenty Fourteen with above pull request. Armando.

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome Version 90.0.4430.212

### PR DESCRIPTION
**Pull request by youknowriad**
closes #32139 

For performance reasons, we only used a partial parsing to check the blocks used in a pattern, the issue with that is that the second step for parsing performs a lot of block normalizations:

 - apply the fallback block type.
 - rename some old renamed blocks.
 - Run deprecations and upgrade some blocks.

So it has the potential to change the blocks used in a block pattern meaning the performance optimization actually breaks the logic. Potentially we could consider building a dedicated "parse" function that only returns the list of blocks used in an HTML string.

**Testing instructions**

 - Register a pattern with whitespace, example:

```
		register_block_pattern(
			'twentyfourteen/about',
			array(
				'title'         => esc_html__( 'About', 'twentyfourteen' ),
				'categories'    => array( 'buttons' ),
				'viewportWidth' => 1000,
				'content'       => '<!-- wp:image {"id":31,"sizeSlug":"large","linkDestination":"none"} -->
									<figure class="wp-block-image size-large"><img src="' . esc_url( get_template_directory_uri() ) . '/images/person.jpg" alt="' . esc_attr__( 'A person standing in front of a lake', 'twentyfourteen' ) . '" class="wp-image-31"/></figure>
									<!-- /wp:image -->
									<!-- wp:heading {"fontSize":"large","style":{"typography":{"lineHeight":"1.4"}}} -->
									<h2 class="has-large-font-size" style="line-height:1.4">' . esc_html__( 'Hello, my name is Joan. I am passionate about writing, travel, and photography.', 'twentyfourteen' ) . '</h2>
									<!-- /wp:heading -->
									<!-- wp:paragraph -->
									<p>' . esc_html__( 'I’ve traveled to over 60 countries, and have made many friends along the way. I created this website to keep track of the memories I’ve made in my years of traveling.', 'twentyfourteen' ) . '</p>
									<!-- /wp:paragraph -->',
			)
		);
```

Makes sure it appears in the patterns inserter.

### CODE REVIEW

File: packages/block-editor/src/store/selectors.js [hunk 1]
```diff
@@ -1837,10 +1836,14 @@ const getAllAllowedPatterns = createSelector(
 			// the raw blocks parser, also known as the "stage I" block parser.
 			// This is about 250x faster than the full parse that the Block API
 			// offers.
-			blockNodes: parseBlocks( pattern.content ),
+			__unstableBlockNodes: parse( pattern.content ),
```
Comment (ntsekouras) [inline packages/block-editor/src/store/selectors.js]: Should we use `__experimentalGetParsedPattern` selector then in the mapping function, that adds the `blocks` property? The comments needs to go away as well.

**Comment by ryelle** [comment]
💯  This also fixes some (5) of the remote patterns, like Quote - any remote pattern that doesn't have a single parent block, I think. So on trunk, the Quote pattern doesn't load, but on this branch it does.

File: packages/block-editor/src/store/selectors.js (hunk 1 above)
Comment (youknowriad) [reply packages/block-editor/src/store/selectors.js]: Not sure I follow here :) would you mind pushing that change?

**Review by carolinan — APPROVED** [review]
The PR solves the issue for me, thank you.

File: packages/block-editor/src/store/selectors.js (hunk 1 above)
Comment (ntsekouras) [reply packages/block-editor/src/store/selectors.js]: Pushed: https://github.com/WordPress/gutenberg/pull/32376/commits/149e5e1def5cd32ac690c2904819446a88f2bdc3

Comment (youknowriad) [reply packages/block-editor/src/store/selectors.js]: Thanks, very nice simplification.

**Comment by ellatrix** [comment]
@youknowriad I don't get what the issue was in #32376... it was whitespace? How is that related to grammar vs full parse?

**Comment by ellatrix** [comment]
It would be good to have an e2e test.

**Comment by youknowriad** [comment]
Yeah, sorry should have added an e2e test but I guess the testing instructions can be tried again.

I don't recall entirely but I think what happened with the example is that you end up with an "empty" block type which was considered "not allowed" or something like that. But it's also not the only issue that can happen. For instance if you use `core/text` in your pattern, your pattern won't be considered valid unless you use the full parsing which transforms it to `core/paragraph`
