### PR TITLE
Text Editor: Fix inserting blocks

### LINKED ISSUE #1072: Inserter: Inserting content doesn't update in text mode
Steps to reproduce:

- Switch to text mode
- Click inserter, insert a block

Note that no block is seemingly inserted in text mode. But if you switch back to visual mode, you'll see it actually was inserted.

Seems like we need to refresh the text mode, or something. 

GIF:

inserter in text mode

### PR DESCRIPTION
**Pull request by youknowriad**
closes #1072 

This bug is way harder to solve than it seems because for performance reasons, we want to avoid calling parse/serialize as much as we can.

The solution here involves:

 - Making the text editor controlled 
 - Tracking blocks prop updates and serialize the new content each time the prop change
 - Make sure the `getBlocks` selector returns the same array instance if the state didn't change
 - Trigger a "MARK_DIRTY" action each time we change the text editor value (to enable the publish button) even if the blocks value is not dispatched to the store.

### CODE REVIEW

File: editor/selectors.js [hunk 1]
```diff
@@ -3,6 +3,7 @@
  */
 import moment from 'moment';
 import { first, last, get } from 'lodash';
+import { createSelector } from 'reselect';
```
Comment (aduth) [inline editor/selectors.js]: I recently published a Calypso-like memoization library: https://github.com/aduth/rememo

Curious if you have thoughts on whether `reselect` is a better approach or not.

Comment (youknowriad) [inline editor/selectors.js]: To be honest, I don't have any preference. The advantage of `reselect` is that it's kind of the default with Redux, more developers already know how to use it. But at the same time, `rememo` is probably easier to learn.

Comment (aduth) [inline editor/selectors.js]: Fair point. I've always found the examples they chose in their documentation to be overly daunting for the sake of showcasing a complex example, but what you've shown here is much simpler.

Another worry is that they don't really prescribe easy patterns for accepting arguments to a selector:

https://github.com/reactjs/reselect#q-how-do-i-create-a-selector-that-takes-an-argument

Here worked out easy enough because `getBlocks` doesn't accept any anyways.

Comment (youknowriad) [inline editor/selectors.js]: mmm! Good point about the selectors with arguments, I think we'll need this quickly. Though according to their docs, we could write this

```js
const createSelectorWithArguments = ( extractors, resolver ) => {
	const memoizedResolver = memoize( resolver );
	const memoizedSelector = createSelector( extractors, memoizedResolver );
	return ( state, ...args ) => {
		const selector = memoizedSelector( state );
		return selector( ...args );
	};
};
```

Comment (youknowriad) [inline editor/selectors.js]: mmm looks like https://github.com/toomuchdesign/re-reselect do exactly what I've proposed.

But I think I'll just switch to `rememo`

Comment (aduth) [inline editor/selectors.js]: >Though according to their docs, we could write this

Is this something you created, or in their docs? How is it used? Isn't creating and calling `selector` in the inner function expensive?

Comment (youknowriad) [inline editor/selectors.js]: Yes, this is something I came up with after reading the second part here https://github.com/reactjs/reselect#q-how-do-i-create-a-selector-that-takes-an-argument

Comment (youknowriad) [inline editor/selectors.js]: Thought the `memoize` call needs to be updated to compute a hash from all the arguments (instead of the first one only)

Comment (youknowriad) [inline editor/selectors.js]: Actually! forget my implementation it's completely broken I think :)

**Comment by jasmussen** [comment]
Unrelated to the conversation above, this seems to be working well! Thanks for tackling this so fast.

File: editor/selectors.js (hunk 1 above)
Comment (youknowriad) [inline editor/selectors.js]: @aduth I think there's a problem somewhere in `rememo`. I've replaced the selector by this:

```js 
export const getBlocks = createSelector(
	( state ) => {
		return state.editor.blockOrder.map( ( uid ) => (
			state.editor.blocksByUid[ uid ]
		) );
	},
	state => state.editor.blockOrder,
	state => state.editor.blocksByUid,
);
```

and I'm getting a new Instance even if the state didn't change.
I'll probably keep reselect for now, and feel free to update once fixed.

Comment (aduth) [inline editor/selectors.js]: @youknowriad That's incorrect usage. There should be two arguments at most, so the second should be changed to:

```js
( state ) => [
	state.editor.blockOrder,
	state.editor.blocksByUid,
]
```

Comment (youknowriad) [inline editor/selectors.js]: Still not working 🤔

Comment (youknowriad) [inline editor/selectors.js]: updated with the last version of `rememo` it works great.

File: editor/modes/text-editor/index.js [hunk 2]
```diff
@@ -5,55 +5,106 @@ import { connect } from 'react-redux';
...
+
+	onChange( event ) {
+		this.setState( {
+			value: event.target.value,
+		} );
+		this.props.markDirty();
+	}
+
+	onBlur() {
+		const blocks = parse( this.state.value );
```
Comment (aduth) [inline editor/modes/text-editor/index.js]: As noted in chat, can we test here whether the value has changed from what we know to have been the previous value before parsing and assigning new blocks?

**Comment by aduth** [comment]
Total aside but on the note of memoized selectors: I've been quite intrigued by [Vue's approach for change tracking](https://vuejs.org/v2/guide/reactivity.html#How-Changes-Are-Tracked) using `Object.defineProperty`, and I feel like there could be an easy pattern for memoization in Redux applying the same technique; i.e. detecting the structure of state, replacing each key (and subkey) with a getter, and tracking calls within the selector to determine when the cache needs to be busted (effectively replacing the need for the second argument to `createSelector`). I might do some explorations on this separately.

**Comment by aduth** [comment]
Steps to reproduce:

1. Navigate to Demo
2. Switch to Text
3. Insert block

__Expected:__ Serialized block content appended to the end of content
__Actual:__ Serialized block content inserted between first and second blocks, regardless of where focus changes within text

Guessing our visual editor mode insertion point is interfering.

**Comment by youknowriad** [comment]
Good catch @aduth. I've addressed the issue by simplifying the insertion point behaviour and moving the logic to a testable selector in 44f6fe1

**Review by aduth — APPROVED** [review]
I like the refactor. This works well now 👍
