### PR TITLE
Raw Handling: allow list attributes

### LINKED ISSUE #17414: Gutenberg list block says there is an HTML error when <ol start="number"> is used.
**Describe the bug**
Gutenberg list block says there is an HTML error when <ol start="number"> is used.
**To reproduce**
1. Go to 'Gutenberge editor and add a numbered list'
2. Click on 'Edit HTML' and add the start at number attribute to the list
3. Now click on block three dots and try to go back to editing visually
4. Gutenberg throws an error saying HTML is not valid and attempts to convert it unsuccessfully

**Expected behavior**
A list which starts form the desired number appears in visual editor. Generally numbered lists display differently than they would in the front-end anyway. Changing list type doesn't update in editor you keep seeing lists styled as 1,2,3 instead of a,b,c,d although the front end shows the correct format.

**Desktop (please complete the following information):**
 - OS:  Deepin 15.11
 - Browser Chrome
 - Version  76.0.3809.132

**Additional context**
-Gutenberg Version 6.4.0

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Allows `type`, `start` and `reversed` attributes on ordered lists to be pasted and converted to blocks. UI has been added for `start` and `reversed` in #15113.

Also fixes #17414.

## How has this been tested?

I've added a test case.

Copy paste the following list:

<ol start="2"><li>test</li></ol>

It should start at 2.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/block-library/src/list/transforms.js [hunk 1]
```diff
@@ -77,12 +77,35 @@ const transforms = {
...
+				};
+
+				if ( attributes.ordered ) {
+					const type = node.getAttribute( 'type' );
+
+					if ( type ) {
+						attributes.type = type;
+					}
+
+					if ( node.getAttribute( 'reversed' ) !== null ) {
```
Comment (tfrommen) [inline packages/block-library/src/list/transforms.js]: If `reversed` was explicitly set to `false`, this will still reverse the list, right?

While I understand that doing something like that does not make a lot of sense, it is still possible that some component simply passes on a Boolean prop.

What about this?

```suggestion
					const reversed = node.getAttribute( 'reversed' );
					if ( reversed !== null && reversed !== 'false' ) {
```

Comment (ellatrix) [reply packages/block-library/src/list/transforms.js]: You're right, the attribute value doesn't matter.

Comment (ellatrix) [reply packages/block-library/src/list/transforms.js]: But I don't get what you're proposing... I check for the mere presence of the attribute, which seems correct to me. You suggest to check that it is not `false`, which is contrary to what you say:

> While I understand that doing something like that does not make a lot of sense, it is still possible that some component simply passes on a Boolean prop.

Comment (tfrommen) [reply packages/block-library/src/list/transforms.js]:
```
<ol reversed="false">
    <li>Item 1</li>
    <li>Item 2</li>
</ol>
```

This will render like so:

```
2. Item 1
1. Item 2
```

I think this is wrong, or, at least, unexpected. My committable suggestion should fix that, no?

Comment (ellatrix) [reply packages/block-library/src/list/transforms.js]: I disagree. For paste, we should look preserve what is rendered. If a list was reversed, even with an unexpected value, it should stay reversed.

Comment (ellatrix) [reply packages/block-library/src/list/transforms.js]: @tfrommen Does that make sense? We shouldn't alter the code to the rendered result is different. The user doesn't really care what the underlying code is, only that the pasted content looks the same.

**Review by gwwar — APPROVED** [review]
Nice @ellatrix! Turns out a local rebase wasn't too bad after all! This tests well for me and the code makes sense. I also verified that the generated markup matches, and that invalid prop values fail block validation.

Please do rebase though before landing ✅ 

| Before | After |
| ------------- | ------------- |
| current| after |

**Comment by ellatrix** [comment]
Thanks for the review @gwwar! Strange that Github doesn't report any merge conflicts. I'll rebase and merge. Thanks!
