### PR TITLE
Navigation Editor: use 'ajaxurl' global in batchSave action

### LINKED ISSUE #25181: Save navigation not working when site is not in domain root
**Describe the bug**

When trying to "Save navigation" in the navigation screen on my live website, a message pops up saying "There was an error" and the navigation isn't saved.
In the Network tab I can see that the POST request for saving the nav is using an incorrect URL. My website is not in the domain root but in a folder, like `mydomain.com/wp-website`, but the POST URL assumes it's in the root, so it's structured like: `mydomain.com/wp-admin/admin-ajax.php?_locale=user`

The issue seems to be with [this line](https://github.com/WordPress/gutenberg/blob/7dd02c25b41cf30158678c50042621dea7a6235e/packages/edit-navigation/src/store/actions.js#L159)

**To reproduce**
1. In a website that is not located in the domain root, try creating a menu in the navigation screen and saving it.
2. Check that error occurs.
3. Check POST URL in the dev tools network tab.

**Expected behavior**

Expected to be able to save the nav no matter what my URL structure is like.

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- If the Gutenberg plugin is installed, which version is it? Yes, 8.9.3

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
PR fixes navigation saving issue when WordPress is in a subdirectory.

Fixes #25181.

## How has this been tested?
1. On the site where WP is in a subdirectory (you can find instructions [here](https://wordpress.org/support/article/giving-wordpress-its-own-directory/)).
2. Go to the experimental Navigation screen.
3. Create a menu.
4. You should be able to save the menu without an error.

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [n/a] My code follows the accessibility standards. 
- [n/a] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/edit-navigation/src/store/actions.js [hunk 1]
```diff
@@ -184,7 +186,7 @@ function* batchSave( menuId, menuItemsByClientId, navigationBlock ) {
 	);
 
 	return yield apiFetch( {
-		url: '/wp-admin/admin-ajax.php',
+		url: ajaxurl,
```
Comment (getdave) [inline packages/edit-navigation/src/store/actions.js]:
```suggestion
		url: ajaxurl || '/wp-admin/admin-ajax.php',
```

As this relies on the window (easily manipulated) should we include a fallback?

Comment (Mamaduka) [reply packages/edit-navigation/src/store/actions.js]: Thanks, @getdave.

I've added a fallback.

**Review by getdave — APPROVED** [review]
I tested this by following the instructions over at https://wordpress.org/support/article/giving-wordpress-its-own-directory/#method-i-without-url-change.

Menu saving and editing worked perfectly.

The `ajaxurl` was available on `window`. If I manually modified it to remove that property then the fallback also worked.

**Comment by Mamaduka** [comment]
Thanks for the review, @getdave.
