### PR TITLE
Accessibility: Improve Welcome guide and modal component.

### LINKED ISSUE #19078: Welcome Guide: modal should be labelled
**Describe the bug**
From https://github.com/WordPress/gutenberg/pull/18041#issuecomment-562661218

>The modal is not labelled. This is in part a problem with this modal, but should probably be corrected in the component: the Modal component allows the component to be misused.

>We should enforce a label for the modal element with `role=dialog` within the e2e tests, because all modals must be labelled. Additionally, the modal component should enforce `role="document"` on the content of all modal dialogs. This isn't strictly required on all modals, but the component can't know what type of content a modal will contain, this will give the best overall experience.

### PR DESCRIPTION
**Pull request by MarcoZehe**
## Description

Improved the welcome guide so that it labels the modal it creates through the guide component via an unobtrusive aria-label, using the contentLabel property defined in modal. The Guide component now accepts and passes on that contentLabel prop. Normally, it should visually label the modal via title, as title is the required attribute for Modal. But to be unobtrusive, I chose to use the not required contentLabel instead, but make that required for Guide so the modal dialog at least always gets an accessibility label.

I also adjusted the page control to indicate via aria-current which of the pages is the currently active one.

Furthermore, the modal's content block is now a role "document" so screen readers can view it like web content. This makes it easier to review text inside.

Adjusted documentation and story.

Fixes #19078 .
## How has this been tested?

Tested in Story Book to make sure the contentLabel gets added to the modal. Tested the page control so it exposes the current page via aria-current. Also tested that the contents is rendered as a virtual document for screen reader users.

## Types of changes

Bug fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Review by ellatrix — APPROVED** [review]

**Comment by ellatrix** [comment]
Looks good to me

File: packages/components/src/guide/page-control.js [hunk 1]
```diff
@@ -18,7 +18,10 @@ export default function PageControl( { currentPage, numberOfPages, setCurrentPag
 	return (
 		<ul className="components-guide__page-control" aria-label={ __( 'Guide controls' ) }>
 			{ times( numberOfPages, ( page ) => (
-				<li key={ page }>
+				<li
+					key={ page }
+					aria-current={ page === currentPage }
```
Comment (aduth) [inline packages/components/src/guide/page-control.js]: For my own curiosity: Would one of the keywords associated with `aria-current` have been appropriate to use here? Notably, I'm wondering if `'step'` could have been used as an indication of the active step in the set of guide steps?

```jsx
aria-current={ page === currentPage ? 'step' : undefined }
```

>A `step` token used to indicate a link within a step indicator for a step-based process, where the link is visually styled to represent the current step.

https://www.w3.org/TR/wai-aria-1.1/#aria-current

Comment (MarcoZehe) [reply packages/components/src/guide/page-control.js]: Thank you, yes, this is even better. I filed #19290 to change this.
