### PR TITLE
Editor: Shim meta attributes for early block registrations

### LINKED ISSUE #20494: Storing Post Meta with a Block is not working anymore (WordPress 5.4 beta)
This bug only seems to be related to WordPress 5.4 (beta) as it can't be reproduced on WordPress 5.3 (stable).

**Steps to reproduce the behavior:**
1. Create a simple meta block based on the following tutorial: https://developer.wordpress.org/block-editor/tutorials/metabox/meta-block-1-intro/
2. Add some text to the _TextControl_ and save the post
3. Reload the page and notice the empty _TextControl_
3. The post meta key/value can't be found in the database

**Desktop:**
 - OS: macOS
 - Browser: Chrome/Firefox
 - Version: latest stable versions
 - Theme: TwentyTwenty

**Additional context:**

Working 😀
- WordPress 5.3.2
- WordPress 5.3.2 + Gutenberg 7.6

Not working 🙁
- WordPress 5.4 beta3
- WordPress 5.4 beta3 + Gutenberg 7.6

### PR DESCRIPTION
**Pull request by aduth**
Fixes #20494 

This pull request seeks to resolve an issue where blocks which are registered early and use the (now-deprecated) meta attribute source would fail to apply the compatibility shims introduced between #17153 and #20494.

**Testing Instructions:**

There are two ways to test:

Per #20494, following the [meta block tutorial](https://developer.wordpress.org/block-editor/tutorials/metabox/meta-block-1-intro/) should yield a plugin with code such as in the following gist:

https://gist.github.com/aduth/9953fdd7676ce080ab24c2c8a85ae783

From the page, you may be able to <a href="https://gist.github.com/aduth/9953fdd7676ce080ab24c2c8a85ae783/archive/9efb51b8e2887840c8d2cd9454ad4989b105d81c.zip">Download zip</a> to download a ZIP to use as plugin.

Otherwise, you can use the now-updated "Meta Attribute Block" Gutenberg test plugin to verify the behavior. You can do this as a user if you are using the [default development environment](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/getting-started.md) by activating the plugin from the Plugins screen.

You can ensure the end-to-end tests pass:

```
npm run test-e2e packages/e2e-tests/specs/editor/plugins/meta-attribute-block.test.js
```

### CODE REVIEW

File: packages/editor/src/hooks/custom-sources-backwards-compatibility.js [hunk 1]
```diff
@@ -116,3 +116,19 @@ addFilter(
...
+// The following implementation achieves this, albeit with a couple caveats:
+// - Only blocks registered on the global store will be modified.
+// - The block settings are directly mutated, since there is currently no
+//   mechanism to update an existing block registration. This is the reason for
+//   `getBlockType` separate from `getBlockTypes`, since the latter returns a
+//   _copy_ of the block registration (i.e. the mutation would not affect the
+//   actual registered block settings).
+globalSelect( 'core/blocks' )
+	.getBlockTypes()
+	.map( ( { name } ) => globalSelect( 'core/blocks' ).getBlockType( name ) )
```
Comment (epiqueras) [inline packages/editor/src/hooks/custom-sources-backwards-compatibility.js]: Let's add a note to `getBlockType` to make sure that in the future, someone doesn't change it to return a copy.

Or, better yet, let's make an experimental action to update the registration.

**Review by epiqueras — APPROVED** [review]

File: packages/editor/src/hooks/custom-sources-backwards-compatibility.js (hunk 1 above)
Comment (aduth) [reply packages/editor/src/hooks/custom-sources-backwards-compatibility.js]: I thought about this as well, but figured the end-to-end test would be enough to protect ourselves from regression (it would start to fail if `getBlockType` returns a copy).

I do think a function to update a block registration would be a good idea, since it seems like a valid use-case. Needing to resort to mutating the settings object is definitely not ideal. I can create an issue to track this.

Comment (epiqueras) [reply packages/editor/src/hooks/custom-sources-backwards-compatibility.js]: :+1:

Comment (aduth) [reply packages/editor/src/hooks/custom-sources-backwards-compatibility.js]: Issue: #20548

**Comment by mrleemon** [comment]
`use the (now-deprecated) meta attribute source`

So, is `source: 'meta'` not valid anymore? How are we supposed to tell the editor that an attribute comes from a meta field registered via `register_post_meta()`, now?

**Comment by mcsf** [comment]
@mrleemon: There is a dev note in the works which will be published in the next days (see [their drafting](https://github.com/WordPress/gutenberg/issues/20185)). The quick answer is that you can now use:

```js
const [ meta, setMeta ] = useEntityProp( 'postType', 'post', 'meta' );
```

Although, to be clear, the shim in question in this PR is there so that nothing breaks overnight. It just means that `source: 'meta'` is to be considered deprecated starting with WordPress 5.4.
