### PR TITLE
Fix: Page list: Pages without a title has no link text

### LINKED ISSUE #54959: Page list: Pages without a title has no link text
### Description

In the navigation block, posts without titles have the link text `(no title)`.
But in the page list, pages without titles have no default or fallback link text. This happens for page lists inside and outside navigation blocks.

Page lists inside navigation blocks can be "detached", and by selecting the page list item, the user can add a custom "label":
The label input field in the page list block settings sidebar
But this is is not possible for the page list when it is not inside the navigation block.

This is a problem for users because without a link text, the link is not discoverable without using AT like a screen reader.
On the front of the website, neither mouse or keyboard users would be able to identify or access the link.

The empty link would only show as a mysterious blank space, depending on the styling of the parent block.
Navigation:
Navigation block with space instead of a visible link
Page list outside the navigation block is showing an empty list item:
Page list with empty list item

### Step-by-step reproduction instructions

1. Create a page and publish it without adding a title.
2. Place a page list block
3. Place a navigation block with a page list block inside.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

Gutenberg current trunk.
WordPress Beta tester plugin Version 3.5.4.
Only tested on 6.4 beta 1 current nightly: I did not test on older versions of WordPress.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

### PR DESCRIPTION
**Pull request by carolinan**
## What & Why?

This PR adds two placeholder texts when a page is in a page list block, and the page is missing a title.
The text is `(no title)`, which matches the placeholder for posts, and the placeholder for pages that are not inside a page list.
Without a placeholder title, the link text and button was empty, making the item difficult to see and use. Visually, there was only a blank space and no visible item for a sighted user to click on or navigate to.

Closes https://github.com/WordPress/gutenberg/issues/54959

## How?

The PR adds one placeholder title to the editor, and one to the front.

## Testing Instructions

1. Create three pages that have no titles: Make one of the pages a child of the other (That way submenus can be tested).
2. Add a page list block to the template or content. Confirm that the page list items have visible link texts.
3. Add a navigation block.
4. Add one of the untitled pages to the navigation block.
5. Add a page list block to the navigation block.
6. Confirm that both the page and page list items have visible texts.
7.  Save and go to the front of the site. Confirm that both the page and page list items have visible text.

## Screenshots or screencast 
After: The screenshot shows a navigation block with a  page list inside.
A second page list block is also below (outside) the navigation block.
Page list block with link texts that says (no title)

### CODE REVIEW

File: packages/block-library/src/page-list/index.php [hunk 1]
```diff
@@ -192,7 +192,8 @@ function block_core_page_list_render_nested_page_list( $open_submenus_on_click,
 			$css_class .= ' menu-item-home';
 		}
 
-		$title      = wp_kses_post( $page['title'] );
+		$title = wp_kses_post( $page['title'] ) ? wp_kses_post( $page['title'] ) : __( '(no title)' );
```
Comment (Mamaduka) [inline packages/block-library/src/page-list/index.php]: The `wp_kses_post` can be expensive. Maybe we should run it just once. What do you think?

```php
$title =  wp_kses_post( $page['title'] );
$title =  $title ? $title :  __( '(no title)' );
```

P.S. I've not tested this code :)

**Review by t-hamano — APPROVED** [review]
This approach seems reasonable to me 👍

Because it takes into account the case where the title is empty in the [Latest Comments](https://github.com/WordPress/gutenberg/blob/0e49f4793245787e7ccb30cc8808733bdcdcc6fc/packages/block-library/src/latest-comments/index.php#L31), [Latest Posts](https://github.com/WordPress/gutenberg/blob/0e49f4793245787e7ccb30cc8808733bdcdcc6fc/packages/block-library/src/latest-comments/index.php#L31), and [RSS](https://github.com/WordPress/gutenberg/blob/0e49f4793245787e7ccb30cc8808733bdcdcc6fc/packages/block-library/src/rss/index.php#L37) blocks.

I will approve this PR, but I think it would be better to address [this suggestion](https://github.com/WordPress/gutenberg/pull/64297/files#r1726191665).

While not directly related to this PR, I noticed that there are some places where the title doesn't show anything if it contains only spaces. For example, the title when a post is being edited:


empty-title

It might be worth investigating these as well and addressing them in a new PR.

**Comment by carolinan** [comment]
Thank you.
