### PR TITLE
Image: Adds the block controls for uploading image.

### LINKED ISSUE #54867: Image Block: `MediaPlaceholder` / `MediaUpload` component doesn't addapt to small sizes
### Description

When an image block for example is used with a fixed height and width in a Pattern where it doesn't have an image selected yet, the image will render the `MediaPlaceholder`

But since an image can be really small the `MediaPlaceholder` should ideally adapt to the small size and display an alternate layout. 

You can see the overflowing issue in the screencast I attached below

### Step-by-step reproduction instructions

1. Insert this block pattern for example:

<details><summary>Code sample</summary>

```html
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60","left":"var:preset|spacing|60","right":"var:preset|spacing|60"}}},"backgroundColor":"contrast","textColor":"base","layout":{"type":"constrained","contentSize":""}} -->
<div class="wp-block-group alignfull has-base-color has-contrast-background-color has-text-color has-background" style="padding-top:var(--wp--preset--spacing--60);padding-right:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60);padding-left:var(--wp--preset--spacing--60)"><!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"align":"center","style":{"typography":{"lineHeight":"1.2"}},"textColor":"base","fontSize":"x-large","fontFamily":"heading"} -->
<p class="has-text-align-center has-base-color has-text-color has-heading-font-family has-x-large-font-size" style="line-height:1.2"><em>“Études has saved us thousands of hours of work and has unlocked insights we never thought possible.”</em></p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":"var:preset|spacing|10"} -->
<div style="height:var(--wp--preset--spacing--10)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:group {"style":{"spacing":{"blockGap":"0"}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:image {"align":"center","width":"60px","aspectRatio":"1","scale":"cover","sizeSlug":"thumbnail","linkDestination":"none","style":{"border":{"radius":"100px"}}} -->
<figure class="wp-block-image aligncenter size-thumbnail is-resized has-custom-border"><img alt="" style="border-radius:100px;aspect-ratio:1;object-fit:cover;width:60px"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"align":"center","style":{"spacing":{"margin":{"top":"var:preset|spacing|10","bottom":"0"}}}} -->
<p class="has-text-align-center" style="margin-top:var(--wp--preset--spacing--10);margin-bottom:0">Annie Steiner</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center","style":{"typography":{"fontStyle":"normal","fontWeight":"300"}},"textColor":"contrast-3","fontSize":"small"} -->
<p class="has-text-align-center has-contrast-3-color has-text-color has-small-font-size" style="font-style:normal;font-weight:300">CEO, Greenprint</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
```

</details>

2. Try to fill in the image in the pattern via the Media placeholder 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/20684594/ad138693-47cd-4313-84b6-874ee617b94c

Related issue: #64288.

## Suggestion

Apply a minimal version of `Placeholder` that is shown when the block is narrow. Already in place are CSS classes `is-medium` and `is-small`, which can be used to change the appearance based on context. 

Mockup:

image placeholders

Details:

* "Add image" is added to the block toolbar when it's in a placeholder state. This button serves as a dropdown, making it similar in behavior to how Cover, and Site Logo works.
* In the smallest <60px state, the white placeholder material isn't shown at all, even if it's shown on select in the larger states.

Issue updated Aug 7. [Figma](https://www.figma.com/design/f4rGFqRCB2x0v4yo28dSUN/Placeholders?node-id=35-1937&t=VEzKE8I1zjEV6rvi-1).

### LINKED ISSUE #64288: Placeholders look broken when block is narrow, e.g. when used in a grid
Blocks with placeholder states do not scale to very narrow containers. Example here of an Image placeholder in a narrow grid layout:

image

There's a separate issue for updating just the Image block has been updated (#54867), but the problem is present for every block that uses the `Placeholder` component. The same solution can be applied:

i2 Generic placeholders

Key here is leaning into a few principles:

* The placeholder content (title, text, buttons) are available for large and medium contexts.
* In small contexts, we rely on the _block toolbar_ for having a single primary CTA. This affords a text label that will not be cropped.
* In that same small context, either the gray unselected placeholder material is used, or the entire spot is a plus button that opens the quick inserter (as it is in empty columns or groups, for example).

[Figma](https://www.figma.com/design/f4rGFqRCB2x0v4yo28dSUN/Placeholders?node-id=37-3096&t=XlmTnnJA8tsGMFZK-1).

### PR DESCRIPTION
**Pull request by vipul0425**
## What?
Fixes #54867

## Why?
In small width size the image block placeholder looks broken and it's hard to choose an image from there.

## How?
This PR is adding a BlockControl to choose an image which will have all the three options upload, choose from media library or add from a link and will keep the placeholder abstract.

## Testing Instructions
1. Add a columns block or grid block. Choose 6+ columns or grid in a row and add an image block.
2. Now the choose an image option will appear in BlockControls Toolbar.  

## Screenshots or screencast

For Large Size
image

For Medium Size
image

For small Size
image

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice! This makes good progress, but doesn't yet fully fix 54867. Quick GIF:

Image

We need only two changes:

1. Rename "Choose Image" to "Add image" (note the lowercase i)
2. Don't show the "white material" in mobile.

2 should be possible with CSS. Essentially it should look like this:

Screenshot 2024-08-13 at 13 48 37

That maintains the gray placeholder material rather than the white `<Placeholder />` material on-select. You should be able to use the CSS class already present, for this. Something like:

* Change `.wp-block-image.wp-block-image.is-selected .block-editor-media-placeholder` to `.wp-block-image.wp-block-image.is-selected .block-editor-media-placeholder:not(.is-small)`
* Change `.wp-block-image.wp-block-image.is-selected .block-editor-media-placeholder .components-placeholder__illustration` to .wp-block-image.wp-block-image.is-selected .block-editor-media-placeholder .components-placeholder__illustration:not(.is-small)`
* Change `.wp-block-image.wp-block-image.is-selected .block-editor-media-placeholder:before` to `.wp-block-image.wp-block-image.is-selected .block-editor-media-placeholder:not(.is-small):before`
* Change `.is-selected>.components-placeholder.has-illustration .components-placeholder__label` to `.is-selected>.components-placeholder.has-illustration:not(.is-small) .components-placeholder__label`

There are probably better places to do this, this was some quick inspector work. Let me know if you'd like me to try and push some code.

**Comment by vipul0425** [comment]
@jasmussen Thanks for the feedback! I'll work on these changes, or if you'd like to make any updates yourself, feel free to do so 😄. Currently, I'm trying to find a workaround for the grid layout, as the current implementation isn't working with grids due to the lack of inner blocks for the columns. I'm experimenting with the number of columns, the minimum width of columns, etc. If you have any better solutions specifically for grids, please let me know.

**Comment by jasmussen** [comment]
Nice. Took the latest for a spin:

status

In the above I added a `min-height: 60px;` to the placeholder component. The default state is a bit small:

Screenshot 2024-08-14 at 10 16 41

Here's 60px again:

Screenshot 2024-08-14 at 10 14 22

CC: @WordPress/gutenberg-design in case you have opinions on the min-height of this state. 

I noticed one glitch. when you insert the image in a narrow column, there's a brief flash of the white placeholder material:
insert

It's a very brief flash, but enough that it's annoying. Since the CSS would never show it, I wonder if it's the resize-observe applying the is-small CSS class with a slight delay? Is there any trick we can do here?

Separately, I noticed that this PR adds a resizeobserver locally to the Image block. That may be fine (perhaps @WordPress/gutenberg-components would know whether this is best done directly in the Placeholder component or if it's good to keep here). I'm asking mainly because the `Placeholder` component already has one, and it already applies a CSS class. Could we rely on that existing CSS class? It's fine that _every placeholder_ gets the is-small changes you've made here, even if only the Image block makes use of them for now. Make sense?

File: packages/block-library/src/image/edit.js [hunk 1]
```diff
@@ -107,8 +111,16 @@ export function ImageEdit( {
 		align,
 		metadata,
 	} = attributes;
+
 	const [ temporaryURL, setTemporaryURL ] = useState( attributes.blob );
 
+	const [ resizeListener, sizes ] = useResizeObserver();
```
Comment (jasmussen) [inline packages/block-library/src/image/edit.js]: Pretty sure this one is already included in the `Placeholder` component, so it may be best to make these width changes to that component itself, rather than locally here.

File: packages/block-library/src/image/edit.js [hunk 2]
```diff
@@ -364,35 +380,72 @@ export function ImageEdit( {
...
-				mediaPreview={ mediaPreview }
-				disableMediaButtons={ temporaryURL || url }
-			/>
-		</figure>
+		<>
+			<figure { ...blockProps }>
+				{ resizeListener }
+				{ ! ( temporaryURL || url ) && (
+					<BlockControls group="other">
+						<MediaReplaceFlow
```
Comment (t-hamano) [inline packages/block-library/src/image/edit.js]: Is it possible to integrate this code into [the existing `MediaReplaceFlow` component](https://github.com/WordPress/gutenberg/blob/00d1f8afac2e3b9764dc28261462b72794ae5ce0/packages/block-library/src/image/image.js#L590-L602)?

The reason is that, for example, if multiple blocks are selected or if the URL control is locked, the `MediaReplaceFlow` component should not be rendered.

For example, try inserting the following HTML via the code editor:

```html
<!-- wp:image { "metadata":{ "bindings":{ "url":{ "source":"core/post-meta", "args":{ "key":"test" } } } } } -->
<figure class="wp-block-image"><img alt=""/></figure>
<!-- /wp:image -->
```


In this case, the "Add image" control should not be displayed:

image

The existing `MediaReplaceFlow` component has checks for these:

https://github.com/WordPress/gutenberg/blob/00d1f8afac2e3b9764dc28261462b72794ae5ce0/packages/block-library/src/image/image.js#L590

Furthermore, in this PR, it seems that it is no longer possible to replace images by dropping them, as shown by the E2E test failure. This might be related to the fact that the `MediaReplaceFlow` component is separated:

https://github.com/user-attachments/assets/0df35c35-981e-4825-9c62-230d456d7e0c

File: packages/block-library/src/image/edit.js (hunk 1 above)
Comment (mirka) [inline packages/block-library/src/image/edit.js]: > Could we rely on that existing CSS class? It's fine that _every placeholder_ gets the is-small changes you've made here, even if only the Image block makes use of them for now. Make sense?

Technically, yes. But in the long run, I'm thinking it could be cleaner and more flexible if this kind of responsive styling was handled solely by the consumer of Placeholder, using [CSS container queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries) (rather than a resize observer). That way, consumers wouldn't have to depend on a set of arbitrary breakpoints that Placeholder defines.

I'm not intimately familiar with the requirements of this Image block in particular, but on first glance I would say it could make it simpler and more performant. Could be worth trying here. (This is a non-blocking comment, just suggesting in case it hadn't been considered.)

**Comment by vipul0425** [comment]
Hi @jasmussen, I have removed the `ResizeObserver` from this component and refactored the logic using CSS. I also added a min-height for the small variant.

@t-hamano, I have implemented the `lockUrlControls` logic in the external `MediaReplaceFlow`, and now we can also replace images. However, my only concern is that in the small size, the "Connected to post meta" text (lockUrlControlsMessage) is also hidden. Do you have any suggestions on where we can display this? I think there should be some visual distinction apart from just the purple image icon that is visible in the toolbar for this.

image

image

File: packages/block-library/src/image/edit.js (hunk 1 above)
Comment (vipul0425) [reply packages/block-library/src/image/edit.js]: Hi @mirka, this would be a good change, but since it applies more generally to the placeholder component, should we make the change in this PR or address it in a separate issue? Related: https://github.com/WordPress/gutenberg/issues/64288

Comment (ciampo) [reply packages/block-library/src/image/edit.js]: Agreed with Lena — this seems a good fit for CSS Container Queries

_(edit: when I wrote my message, I hadn't seen @vipul0425 's reply, which was posted almost at the same time)_

**Comment by jasmussen** [comment]
> However, my only concern is that in the small size, the "Connected to post meta" text (lockUrlControlsMessage) is also hidden. Do you have any suggestions on where we can display this? I think there should be some visual distinction apart from just the purple image icon that is visible in the toolbar for this.

We should show this in the inspector, if it isn't already. If it's already shown there, it's okay to not show it here, and just show the same gray placeholder material.

Taking a look at the branch again now, thanks for your continued work!

**Comment by jasmussen** [comment]
Works well!

Screenshot 2024-08-15 at 09 57 42

I'll defer to others for a code review. I also imagine that the brief flash of the white material is hard to fully get rid of. I wonder if—and this can be a separate followup PR—the logic should be _inversed_: instead of _hiding_ the elaborate white placeholder states in narrow contexts, we _show_ them in the wider contexts? Perhaps the flash would then also be inverted, so this might not be the best solution. But something to potentially try!

File: packages/block-library/src/image/editor.scss [hunk 3]
```diff
@@ -27,13 +26,25 @@
...
+
+	.block-editor-media-placeholder.is-small {
+		min-height: 60px;
+	}
+
+	.block-editor-media-placeholder:not(.is-small) {
+		.components-placeholder__fieldset,
+		.components-placeholder__label {
+			display: flex;
+		}
```
Comment (ciampo) [inline packages/block-library/src/image/editor.scss]: `.components-*` class names are meant to be a private implementation detail and should not be used outside of the components package.

Overrides like the one highlighter make this usage `Placeholder` component prone to future breakage, should the component update internally (either its classnames, or how its internal layout is organized).

Having said that, I can see that there are more examples of using private classnames and in general applying style overrides in this file, which is a strong indicator that we should completely rethink how the media placeholder is implemented. So, in that sense, my feedback shouldn't considered blocking for this specific PR, but rather a warning about how badly styles are architected for this component and the risks.

It feels like it's trying to bend the `Placeholder` component beyond its limits. Therefore:

- we should determine if there are any features that we can add to the `Placeholder` component so that consumers don't have to resort to style overrides and other hacky practices;
- otherwise, we should re-implement the component in a way that builds _on top_ of `Placeholder` . For example, instead of setting `display:none` to `.components-placeholder__illustration`, why don't we pass the `withIllustration={false}` prop?
- finally, if the designs / feature are diverging too much, we should ask ourselves whether this warrants a new, separate component (in the block library package)

**Comment by t-hamano** [comment]
@vipul0425 Thanks for the update!

> I have implemented the `lockUrlControls` logic in the external `MediaReplaceFlow`, and now we can also replace images.

Sorry if my suggestion was unclear.

What I meant is, I don't think we need to add another `MediaReplaceFlow` component. I mean, I think we can update [here](https://github.com/WordPress/gutenberg/blob/8fc3df806a7e3494937477155fad18f92fdb9538/packages/block-library/src/image/image.js#L592-L600) and add a prop like `name={ ! url ? __( 'Add image' ) : __( 'Replace' ) }`. Such an implementation is also done [here](https://github.com/WordPress/gutenberg/blob/8fc3df806a7e3494937477155fad18f92fdb9538/packages/block-library/src/cover/edit/block-controls.js#L103).

File: packages/block-library/src/image/edit.js (hunk 1 above)
Comment (mirka) [reply packages/block-library/src/image/edit.js]: @vipul0425 I don't have much insight into the current state of things, but it looks like you were able to achieve what you needed in this PR without resize observers or container queries, so yes it seems like something that can be addressed as a separate issue 👍

**Comment by vipul0425** [comment]
@t-hamano I tried to integrate that code [here](https://github.com/WordPress/gutenberg/blob/8fc3df806a7e3494937477155fad18f92fdb9538/packages/block-library/src/image/image.js#L592-L600), but since it is defined within the Image component, which isn't rendered on the first load, the inspector controls aren't visible. Alternatively, we could define MediaReplace at the root level and reuse it in both the cases. Could you please guide me on whether that approach would work?

**Comment by t-hamano** [comment]
@vipul0425 

How about making the following changes to this PR?

- Extract the `MediaReplaceFlow` component from the `control` component as `mediaReplaceFlow`
- Make sure `mediaReplaceFlow` is always rendered

<details><summary>Diff</summary>

```diff
diff --git a/packages/block-library/src/image/edit.js b/packages/block-library/src/image/edit.js
index c2b1755670..e867461f00 100644
--- a/packages/block-library/src/image/edit.js
+++ b/packages/block-library/src/image/edit.js
@@ -375,34 +375,6 @@ export function ImageEdit( {
        return (
                <>
                        <figure { ...blockProps }>
-                               { ! ( temporaryURL || url ) && ! lockUrlControls && (
-                                       <BlockControls group="other">
-                                               <MediaReplaceFlow
-                                                       mediaId={ id }
-                                                       mediaURL={ url }
-                                                       allowedTypes={ ALLOWED_MEDIA_TYPES }
-                                                       accept="image/*"
-                                                       name={ __( 'Add image' ) }
-                                                       onSelect={ onSelectImage }
-                                                       onError={ onUploadError }
-                                               >
-                                                       <form className="block-editor-media-flow__url-input has-siblings">
-                                                               <span className="block-editor-media-replace-flow__image-url-label">
-                                                                       { __( 'Insert from URL:' ) }
-                                                               </span>
-
-                                                               <LinkControl
-                                                                       value={ { url } }
-                                                                       settings={ [] }
-                                                                       showSuggestions={ false }
-                                                                       onChange={ ( value ) => {
-                                                                               onSelectURL( value.url );
-                                                                       } }
-                                                               />
-                                                       </form>
-                                               </MediaReplaceFlow>
-                                       </BlockControls>
-                               ) }
                                <Image
                                        temporaryURL={ temporaryURL }
                                        attributes={ attributes }
diff --git a/packages/block-library/src/image/image.js b/packages/block-library/src/image/image.js
index 7dd03a7fb5..775482f0ab 100644
--- a/packages/block-library/src/image/image.js
+++ b/packages/block-library/src/image/image.js
@@ -551,6 +551,27 @@ export default function Image( {
 
        const showBlockControls = showUrlInput || allowCrop || showCoverControls;
 
+       const mediaReplaceFlow = (
+               <>
+                       { console.log(
+                               isSingleSelected && ! isEditingImage && ! lockUrlControls
+                       ) }
+                       { isSingleSelected && ! isEditingImage && ! lockUrlControls && (
+                               <BlockControls group="other">
+                                       <MediaReplaceFlow
+                                               mediaId={ id }
+                                               mediaURL={ url }
+                                               name={ ! url ? __( 'Add image' ) : __( 'Replace' ) }
+                                               allowedTypes={ ALLOWED_MEDIA_TYPES }
+                                               accept="image/*"
+                                               onSelect={ onSelectImage }
+                                               onSelectURL={ onSelectURL }
+                                               onError={ onUploadError }
+                                       />
+                               </BlockControls>
+                       ) }
+               </>
+       );
        const controls = (
                <>
                        { showBlockControls && (
@@ -587,19 +608,6 @@ export default function Image( {
                                        ) }
                                </BlockControls>
                        ) }
-                       { isSingleSelected && ! isEditingImage && ! lockUrlControls && (
-                               <BlockControls group="other">
-                                       <MediaReplaceFlow
-                                               mediaId={ id }
-                                               mediaURL={ url }
-                                               allowedTypes={ ALLOWED_MEDIA_TYPES }
-                                               accept="image/*"
-                                               onSelect={ onSelectImage }
-                                               onSelectURL={ onSelectURL }
-                                               onError={ onUploadError }
-                                       />
-                               </BlockControls>
-                       ) }
                        { isSingleSelected && externalBlob && (
                                <BlockControls>
                                        <ToolbarGroup>
@@ -1001,12 +1009,18 @@ export default function Image( {
        }
 
        if ( ! url && ! temporaryURL ) {
-               // Add all controls if the image attributes are connected.
-               return metadata?.bindings ? controls : sizeControls;
+               return (
+                       <>
+                               { mediaReplaceFlow }
+                               { /* Add all controls if the image attributes are connected. */ }
+                               { metadata?.bindings ? controls : sizeControls }
+                       </>
+               );
        }
 
        return (
                <>
+                       { mediaReplaceFlow }
                        { controls }
                        { img }
```

</details>

**Comment by vipul0425** [comment]
Thanks @t-hamano I have worked on it as per your suggestion. I apologize for the delay, it was a busy week. Could you please review the changes at your convenience?

Also @jasmussen I tried to remove that initial flash by reversing the logic but couldn't completely remove that can you please look into if this will work for now. 

Thanks 🙇

**Review by jasmussen — APPROVED** [review]
Impressive work, I don't see the flash anymore:

img placeholder

Regardless, this is a substantial improvement!

Needs a quick code check too, but experience wise, this is good to go.

**Review by tyxla — COMMENTED** [review]
The failing e2e tests seem to be related, they're worth taking a look at and fixing before moving forward.

**Comment by t-hamano** [comment]
Thanks for the update! This PR is working well, but I think we need to find a way to avoid overriding many component styles.

From my understanding, the expected behavior of the placeholder in this PR is as follows:

- Display the illustration when the Image block is not selected
- When the placeholder is small, i.e. when it has the `is-small` class, the illustration will always be displayed regardless of whether the Image block is selected or not.

Currently, [the `withIllustration` prop is always true](https://github.com/vipul0425/gutenberg/blob/911e938d480c743fb47219120e666b132180ad6e/packages/block-library/src/image/edit.js#L339), so there are quite a few CSS overrides to achieve the above conditions.

Ideally, I think we need to _dynamically_ control the `withIllustration` prop. If we could do that, we should be able to remove all the CSS that exists [here](https://github.com/vipul0425/gutenberg/blob/911e938d480c743fb47219120e666b132180ad6e/packages/block-library/src/image/editor.scss#L3-L71).

That is, I want to achieve something like this:

```javascript
export function ImageEdit( { isSelected: isSingleSelected } ) {
	// ...

	const placeholder = ( content ) => {
		// There is no function called getBlockWidth...
		const containerWidth = getBlockWidth();
		const isSmallContainer = containerWidth < 160;

		return (
			<Placeholder
				withIllustration={ ! isSingleSelected || isSmallContainer }
				label={ __( 'Image' ) }
			>
				{ content }
			</Placeholder>
		);
	};

	// ...
}
```

As far as I know, the only way to know the width of a placeholder from outside the placeholder is to use the `useResizeObserver` hook.

@WordPress/gutenberg-components If you know of any other way to achieve the above approach other than using useResizeObserver, please let us know 🙏

**Comment by mirka** [comment]
> As far as I know, the only way to know the width of a placeholder from outside the placeholder is to use the `useResizeObserver` hook.

Sounds good to me for the purpose of this PR, and the amount of custom CSS we can shave off seems worth it. We should maybe consider abstracting it into Placeholder itself somehow, but for now a resize observer here feels warranted.

**Comment by t-hamano** [comment]
@mirka Thanks for the feedback!

@vipul0425 Sorry for changing the approach so often, but could you try the approach using `useResizeObserver`?

- Remove most (or all) of [this CSS](https://github.com/vipul0425/gutenberg/blob/911e938d480c743fb47219120e666b132180ad6e/packages/block-library/src/image/editor.scss#L3-L71)
- Use the `useResizeObserver` hook to get the width of the `Placeholder` component
- If the width is below a certain value, consider it a small container size
- Dynamically enable the `withIllustration` prop of the Placeholder component (`withIllustration={ ! isSingleSelected || isSmallContainer }`)
- Some kind of workaround may be necessary to prevent the glitch pointed out in [this comment](https://github.com/WordPress/gutenberg/pull/64320#issuecomment-2288133228).

**Comment by vipul0425** [comment]
Hi @t-hamano, I've updated the logic as you suggested. I used the reverse logic for the small container to prevent the initial flash of content. However, I noticed that this is causing two e2e tests to fail. If I'm understanding this correctly, this is due to the focus shifting to the `image` component instead of the `Upload` button on initial render.

If I remove the [`isLargeContainer && content`](https://github.com/WordPress/gutenberg/pull/64320/files#diff-1ee0f3c9ecb27cc1599a5d4a4020ff32f4e3ad111953a4c0310e35df1ece8854R400) condition inside the placeholder, the focus shifts back to the `Upload` button, but then the buttons also appear on the small container, which we don't want.

Do you have any suggestions? I tried manually focusing on the upload button when the component loads, but that approach didn't seem ideal.

File: packages/block-library/src/image/editor.scss [hunk 4]
```diff
@@ -1,39 +1,13 @@
...
-		&::before {
-			opacity: 0;
-		}
+	.block-editor-media-placeholder.is-small {
+		min-height: 60px;
 	}
+
 	.block-bindings-media-placeholder-message {
 		opacity: 0;
 	}
```
Comment (t-hamano) [inline packages/block-library/src/image/editor.scss]: We also need to remove this CSS, otherwise the message will not be visible when the source is bind:

image

File: packages/block-library/src/image/editor.scss [hunk 5]
```diff
@@ -1,39 +1,13 @@
...
-	&.is-selected .block-bindings-media-placeholder-message {
-		opacity: 1;
-	}
 
 	// Remove the transition while we still have a legacy placeholder style.
 	// Otherwise the content jumps between the 1px placeholder border, and any inherited custom
```
Comment (t-hamano) [inline packages/block-library/src/image/editor.scss]: We should be able to delete this one (`transition: none`) too. See the discussion in #64861 for the reason.

File: packages/block-library/src/image/editor.scss [hunk 6]
```diff
@@ -100,7 +74,9 @@ figure.wp-block-image:not(.wp-block) {
 	}
 }
 
-.block-editor-block-list__block[data-type="core/image"] .block-editor-block-toolbar .block-editor-url-input__button-modal {
+.block-editor-block-list__block[data-type="core/image"]
+.block-editor-block-toolbar
+.block-editor-url-input__button-modal {
```
Comment (t-hamano) [inline packages/block-library/src/image/editor.scss]: Personally, I find this line break confusing because it makes it hard to understand at a glance whether these selectors are one or separate.

File: packages/block-library/src/image/edit.js [hunk 7]
```diff
@@ -330,40 +358,49 @@ export function ImageEdit( {
...
+						...shadowProps.style,
+					} }
+				>
+					{ lockUrlControls ? (
+						<span className="block-bindings-media-placeholder-message">
+							{ lockUrlControlsMessage }
+						</span>
+					) : (
+						isLargeContainer && content
+					) }
```
Comment (t-hamano) [inline packages/block-library/src/image/edit.js]:
```suggestion
					{ lockUrlControls && isLargeContainer && (
						<span className="block-bindings-media-placeholder-message">
							{ lockUrlControlsMessage }
						</span>
					) }
					{ ! lockUrlControls && isLargeContainer && content }
```

Not only for `content` but also for `lockUrlControlsMessage`, I think it's better not to render the message itself if the container is not large.

Otherwise, when a small placeholder is selected, the size of the placeholder will change due to the influence of the invisible message:

https://github.com/user-attachments/assets/2aea26b9-ca4b-4949-9502-a0ae12b4f2d4

File: packages/block-library/src/image/edit.js [hunk 8]
```diff
@@ -108,11 +108,39 @@ export function ImageEdit( {
...
+		if ( parsedPlaceholderWidth !== null && parsedWidth !== null ) {
+			return Math.min( parsedPlaceholderWidth, parsedWidth );
+		}
+		return parsedPlaceholderWidth !== null
+			? parsedPlaceholderWidth
+			: parsedWidth;
+	};
+
+	const effectiveWidth = getEffectiveWidth();
+	const isLargeContainer = effectiveWidth !== null && effectiveWidth > 160;
```
Comment (t-hamano) [inline packages/block-library/src/image/edit.js]: Rather than adding a new `useResizeObserver` hook, can't we reuse the one that already exists (`containerWidth`)? Also, the width/height obtained by the `useResizeObserver()` hook should only be [a number type or null type](https://github.com/WordPress/gutenberg/blob/18164f0fcd09a282157f02bba7fd737012cc44fd/packages/compose/src/hooks/use-resize-observer/index.tsx#L16-L19). Taking this into consideration, I expect the logic here can be simplified further.

**Review by t-hamano — COMMENTED** [review]
Thanks for the update!

I'll look into the E2E test failures later, but I've left some feedback for further improvement.

File: packages/block-library/src/image/edit.js (hunk 8 above)
Comment (vipul0425) [reply packages/block-library/src/image/edit.js]: Thanks, @t-hamano, for the review. I tried using the existing containerWidth, but since it was applied outside the `<figure>`, it always returned the content width. When using an image inside the grid, it didn't provide the exact width of the image block.
I'll update the effective width logic to account for these return types.

File: packages/block-library/src/image/edit.js [hunk 9]
```diff
@@ -108,11 +108,35 @@ export function ImageEdit( {
...
+	// or image attribute width if both are defined. If only one is defined, use that one.
+	const getEffectiveWidth = () => {
+		if ( placeholderWidth !== null && parsedWidth !== null ) {
+			return Math.min( placeholderWidth, parsedWidth );
+		}
+		return placeholderWidth !== null ? placeholderWidth : parsedWidth;
+	};
+
+	const effectiveWidth = getEffectiveWidth();
+	const isLargeContainer = effectiveWidth !== null && effectiveWidth > 160;
```
Comment (t-hamano) [inline packages/block-library/src/image/edit.js]:
```suggestion
	const isLargeContainer = placeholderWidth > 160;
```

Do we need to take into account the width as an attribute? I might be missing something, but can't we simply change it like this?

File: packages/block-library/src/image/edit.js [hunk 10]
```diff
@@ -330,40 +354,48 @@ export function ImageEdit( {
...
+						height: width && aspectRatio ? '100%' : height,
+						objectFit: scale,
+						...borderProps.style,
+						...shadowProps.style,
+					} }
+				>
+					{ lockUrlControls && isLargeContainer && (
+						<span className="block-bindings-media-placeholder-message">
+							{ lockUrlControlsMessage }
+						</span>
```
Comment (t-hamano) [inline packages/block-library/src/image/edit.js]:
```suggestion
					{ lockUrlControls &&
						isLargeContainer &&
						lockUrlControlsMessage }
```

Since this class name is no longer in use, the `span` tag itself is no longer necessary.

**Review by t-hamano — COMMENTED** [review]
Thanks for the update! I left some additional feedback and I think it's pretty close to being finished 👍

I'll investigate how to solve the E2E testing issue in more detail this weekend.

File: packages/block-library/src/image/edit.js (hunk 8 above)
Comment (t-hamano) [reply packages/block-library/src/image/edit.js]: Ah, I misunderstood that the existing hook was for getting the width of the block itself. I think adding a new hook makes sense 👍

File: packages/block-library/src/image/edit.js (hunk 9 above)
Comment (vipul0425) [reply packages/block-library/src/image/edit.js]: Thanks @t-hamano I was actually using the observer outside the placeholder component that's why it was required earlier but if I move inside it then I don't think we will need that. So I will update the PR accordingly.

**Comment by jasmussen** [comment]
@t-hamano apologies for the direct ping, do you still have bandwidth to look at the e2e tests? Otherwise I might be able to find someone else that can help, let me know!

**Comment by t-hamano** [comment]
@jasmussen Sorry for the late reply.

From what I can see, the E2E test failure is definitely as described in [this comment](https://github.com/WordPress/gutenberg/pull/64320#issuecomment-2323937969).

That is, after an Image block is inserted, the Upload button should be focused, as shown below:

image

However, in this PR, to prevent flashing the white placeholder in narrow columns like the one below, the placeholder is initially rendered with the illustration and no focusable elements:

https://github.com/user-attachments/assets/3cb45d00-95de-4f89-a397-6ee6da7ae1be


So after the Image block is inserted, the Image block itself gets focus, not the Upload button:

image

We could modify the E2E tests themselves to fit this PR, but that might not be ideal. Because it would mean making an exception to the specification that is common to all blocks: "focus the first focusable element when a block is inserted."

As of now, I have not found an approach to solve this problem, so if anyone knows a good approach on what changes to make to this PR to achieve the following, I would appreciate your help 🙇‍♂️

- In wide columns, the upload button gets focus when an image block is inserted.
- In narrow columns, the image block placeholder always renders with an illustration and does not cause a flash.

**Comment by jasmussen** [comment]
Thanks so much for the clarification. 

I wonder: can we extract the little trick that changes the focusing to avoid the brief flash? It's one we can live without, at least initially. Fixing that flash may not be worth extra code complexity, and there might be a different approach to placeholders worth looking at separately.

**Comment by t-hamano** [comment]
One suggestion would be to revert the illustration changes from this PR, i.e. just add an upload button to the toolbar. Adding an upload button would at least solve the issue of not being able to upload images in narrow columns.

Also, the problem we are trying to solve now will likely be encountered when applying a similar approach to other blocks (Media & Text block, Video block, etc.) in the future.

So maybe we can address this issue as a follow-up to find a more ideal solution.

What do you think?

**Comment by jasmussen** [comment]
I would hate to lose the fact that the placeholder functions in narrow contexts, it's entirely broken at the moment. What I'm suggesting is we rewind back to maybe [this state of the PR](https://github.com/WordPress/gutenberg/pull/64320#issuecomment-2288133228) (if that helps), where everything seemed to work and the only problem was the brief flash of the full placeholder when inserting from the slash command in a narrow context. The reason being: that insertion is an edge-case, not too common. But the image functioning in narrow contexts is arguably common and would be fantastic to fix.

**Comment by t-hamano** [comment]
> What I'm suggesting is we rewind back to maybe this state of the PR (if that helps), where everything seemed to work and the only problem was the brief flash of the full placeholder when inserting from the slash command in a narrow context.

If we can tolerate this edge case, we can move forward with this PR 👍 As for the flash issue, we can look into an ideal solution in the future.

**Comment by t-hamano** [comment]
@vipul0425 Could you update this PR to move it forward, i.e. pass the E2E tests?

This means the following changes should be made:

- Preferentially render a white placeholder instead of an illustrated placeholder. This means changing `isLargeContainer` to `isSmallContainer`.
- Update any conditional statements that use `isLargeContainer` to use `isSmallContainer` and invert the condition. This will cause flashing in the narrow columns, but should pass the E2E tests.

Apologies for the frequent changes 🙏

**Comment by vipul0425** [comment]
Thank you so much @t-hamano for your suggestions and for helping me move this forward 🙏. I’ve made the necessary changes,  I’ll also try to address fixing the flashing issue alongside the E2E tests. If successful, I’ll create a follow-up PR for the fix.

File: packages/block-library/src/image/edit.js [hunk 11]
```diff
@@ -108,11 +108,17 @@ export function ImageEdit( {
...
+
 	const [ temporaryURL, setTemporaryURL ] = useState( attributes.blob );
 
 	const [ contentResizeListener, { width: containerWidth } ] =
 		useResizeObserver();
 
+	const [ placeholderResizeListener, { width: placeholderWidth } ] =
+		useResizeObserver();
+
+	const isSmallContainer = placeholderWidth ? placeholderWidth < 160 : false;
```
Comment (t-hamano) [inline packages/block-library/src/image/edit.js]:
```suggestion
	const isSmallContainer = placeholderWidth && placeholderWidth < 160;
```

Nit: I think this can be simplified.

**Review by t-hamano — APPROVED** [review]
Thanks for the update! I think everything is working as expected.

One last thing I noticed is that the Enter button for the "Current media URL" field is misaligned:

image

However, I believe this is an issue with the `MediaReplaceFlow` or `LinkControl` component itself, and may be addressed in #65158.

**Comment by t-hamano** [comment]
It appears to have passed all E2E tests 👍
