### PR TITLE
Post Content: Prevent infinite recursion

### LINKED ISSUE #26593: Infinite recursion trying to edit a wp_template with revisions containing wp:post-content blocks
**Describe the bug**
I'm learning how to develop a Full Site Editing theme.  
Sometimes I use the **Site Editor (beta)** and other times **Appearance > Templates** or **Appearance > Template Parts**.

Having created a template-part called `post-content` I encountered problems when I attempting to edit some of the Templates ( wp_template ). The editor never loaded. It either timed out or produced a Fatal error - memory exhausted.

I tracked the problem down to a never ending recursion involving `the_content` and `pre_render_block`, while running `WP_Rest_Revisions_Controller->prepare_item_for_response()`. 

The problem occurs when the `wp:post-content` block is being processed.  

Between them the block rendering in `gutenberg_render_block_with_assigned_block_context()` and `the_content` filtering in
`gutenberg_render_block_core_post_content()` produces a never ending recursive loop which isn't shortcircuited by the current test on the `$block->context['postId']`  in `gutenberg_render_block_core_post_content()`. 

Example: 
This is the content of the `revision` postId = 715 which is an autosaved revision of the `single` wp_template 694.
```
<!-- wp:template-part {"postId":665,"slug":"header-2-columns","theme":""} /-->

<!-- wp:post-title /-->

<!-- wp:post-content /-->

<!-- wp:template-part {"postId":548,"slug":"footer-part","theme":"fizzie"} /-->
```

**To reproduce**
1. Using FSE create a template which contains `wp:post-content` ( e.g. `single` ).
2. Edit it to create a revision  (*)
3. Save and return to the dashboard.
4. Use Appearance > Templates.  
5. Use the Edit link to open the editor.
6. Wait until it goes wrong.

(*) I believe the problem may occur with both autosaved revisions and user saved revisions.

**Expected behavior**
The Editor should display the 'single' Template, with the template parts rendered.
The post content block should say "This is a placeholder for post content."

**Screenshots**
Here I get the Fatal error due to the logic in my tracing plugin. It happens a lot earlier than the time out.

image

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] 5.6-beta1 
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] Gutenber 9.2.2 or latest Gutenberg source with FSE enabled.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] latest

**Additional context**
- I documented my analysis in https://github.com/bobbingwide/fizzie/issues/7
- I found two ways to fix the problem.
- My current workaround is to extend the shortcircuit logic in `gutenberg_render_block_core_post_content()`
- Add the following test after the first one
```
if ( 'revision' === $block->context['postType'] ) {
		return '';
}
```

### PR DESCRIPTION
**Pull request by mcsf**
Fixes #26593.
Analogous to #28405 and #28456.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-library/src/post-content/index.php [hunk 1]
```diff
@@ -14,25 +14,54 @@
...
-	$content = get_the_content( null, false, $block->context['postId'] );
+	$content = get_the_content( null, false, $post_id );
 
 	if ( empty( $content ) ) {
+		unset( $seen_ids[ $post_id ] );
 		return '';
 	}
 
 	$wrapper_attributes = get_block_wrapper_attributes( array( 'class' => 'entry-content' ) );
+	$content            = apply_filters( 'the_content', str_replace( ']]>', ']]&gt;', $content ) );
```
Comment (gziolo) [inline packages/block-library/src/post-content/index.php]: It'd be good to add a comment with a reference to where the filter is documented. It's a common pattern used in WordPress core and this file is going to be soon exposed there as well.

Completely unrelated to this PR but it should be nice to fix here since it isn't that much work.

File: packages/block-library/src/post-content/edit.js [hunk 2]
```diff
@@ -55,19 +57,41 @@ function Placeholder() {
 	);
 }
 
+function RecursionError() {
```
Comment (gziolo) [inline packages/block-library/src/post-content/edit.js:60]: Interesting, maybe something that `useNoRecursiveRenders` should also expose?

**Review by gziolo — APPROVED** [review]
Nice one, I haven't tested yet but code looks good 👍🏻

**Comment by ntsekouras** [comment]
I believe `Post Content` is a special case from the other two (Reusable and Template Part) in the sense that we render the initial post content without the use of `Post Content` block ([see here](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/store/actions.js#L63)). That (I think :) ) makes it have this rather weird behavior:

post content

**Comment by gziolo** [comment]
> I believe Post Content is a special case from the other two (Reusable and Template Part) in the sense that we render the initial post content without the use of Post Content block (see here). That (I think :) ) makes it have this rather weird behavior:

In fact, you can see the same issue when you go to the page where you can edit a given Reusable block or Template Part block. I would have to find my comment where I describe the same issue.

Update: my related comment presenting exactly the same issue for Template Part block:
https://github.com/WordPress/gutenberg/pull/28456#issuecomment-789706633

File: packages/block-library/src/post-content/edit.js (hunk 2 above)
Comment (mcsf) [reply packages/block-library/src/post-content/edit.js:60]: Hm, interesting. Btw, I made it a separate component because otherwise some of the ref-juggling hooks inside `useBlockProps` — specifically, `useScrollIntoView` — throw errors.

> something that `useNoRecursiveRenders` should also expose?

This assumes `apiVersion: 2`, though, because of the use of `useBlockProps`. Is that acceptable?

**Comment by mcsf** [comment]
> I believe `Post Content` is a special case from the other two (Reusable and Template Part) in the sense that we render the initial post content without the use of `Post Content` block ([see here](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/store/actions.js#L63)). That (I think :) ) makes it have this rather weird behavior:

This seems acceptable to me, no? I agree with Grzegorz that this experience will always be a little awkward, but the crucial thing is that we stop the recursion.

File: packages/block-library/src/post-content/edit.js (hunk 2 above)
Comment (gziolo) [reply packages/block-library/src/post-content/edit.js:60]: It would be good to confirm why `useScrollIntoView` causes issues, maybe it was called too late, React is very strict about all the rules of hooks? I don't mind having it in its own component though. I mostly curious to confirm it isn't some sort of bug with the hook.

**Comment by gziolo** [comment]
> > I believe `Post Content` is a special case from the other two (Reusable and Template Part) in the sense that we render the initial post content without the use of `Post Content` block ([see here](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/store/actions.js#L63)). That (I think :) ) makes it have this rather weird behavior:
> 
> This seems acceptable to me, no? I agree with Grzegorz that this experience will always be a little awkward, but the crucial thing is that we stop the recursion.

Yes, it is fine to move forward. Fixing the issue might require changes to how the list of blocks is handled for those special cases. @ellatrix is looking into some slightly related changes to how `BlockList` could be refactored to use `InnerBlock` internally. I left there also a comment related to the issue we discuss here: https://github.com/WordPress/gutenberg/pull/29895#issuecomment-811835278.
