### PR TITLE
Spacer: Fix unit settings filter

### LINKED ISSUE #37758: Adding spacer block in 12.3.0 fails
### Description
 
Seems like the latest updates to the spacer block is causing a bug, after I applied the latest Gutenberg plugin updates (12.3.0) this week I started to see the below message after insert the spacer block:

> This block has encountered an error and cannot be previewed.  

This just started happening this week, last week I've been using the spacer block fine.

### Screenshots, screen recording

SS 2022-01-06 at 12 30 21 PM

https://user-images.githubusercontent.com/38438671/148427901-17852938-6ba4-45c0-a9f2-d28c06522f6c.mp4

`TypeError: (0,Oe.useSetting)("spacing.units").filter is not a function. (In '(0,Oe.useSetting)("spacing.units").filter((e=>"%"!==e))', '(0,Oe.useSetting)("spacing.units").filter' is undefined)`

`The above error occurred in the <Ah> component:`

I also tried uninstalling the Gutenberg 12.3.0 plugin and installing the Gutenberg 12.2.0 and the spacer was working fine, I then updated to latest 12.3.0 version and run into the same issue.

Can someone please confirm and provide info for this issue. Thanks

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
Fixes #37758.

The `useSetting( 'spacing.units' )` can return `false`, which isn't filterable.

## How has this been tested?
1. Activate Twenty Nineteen theme.
2. In the post editor, add Spacer block.
3. Block should be added correctly, and there shouldn't be an error in the console.

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-library/src/spacer/controls.js [hunk 1]
```diff
@@ -25,9 +25,9 @@ function DimensionInput( { label, onChange, isResizing, value = '' } ) {
 	// In most contexts the spacer size cannot meaningfully be set to a
 	// percentage, since this is relative to the parent container. This
 	// unit is disabled from the UI.
-	const availableUnitSettings = useSetting( 'spacing.units' ).filter(
-		( availableUnit ) => availableUnit !== '%'
-	);
+	const availableUnitSettings = (
+		useSetting( 'spacing.units' ) || undefined
+	)?.filter( ( availableUnit ) => availableUnit !== '%' );
```
Comment (Mamaduka) [inline packages/block-library/src/spacer/controls.js:30]: We need to use `undefined` and optional changing to apply defaults below.

**Review by fullofcaffeine — APPROVED** [review]
This tests well!

**Comment by Mamaduka** [comment]
Should be backported with #36186.
