### PR TITLE
Input Interaction: restore collapsing selection before edge calc

### LINKED ISSUE #14871: Input Interaction: ArrowLeft in multi-line selection prematurely triggers multi-selection
Possibly related: #12322, #14450

**Describe the bug**

In a paragraph block containing multiple lines of text, a selection spanning multiple lines may prematurely trigger multi-selection when expanding that selection using Shift+ArrowLeft

**To reproduce**

1. Navigate to Posts > Add New
2. Click the writing prompt
3. Add a paragraph with some text
4. Add a second paragraph with at least two lines of text (does not make a difference whether that occurs naturally or by Shift+Enter line break)
5. Starting in the second line of text, create a selection using Shift+ArrowLeft
6. Continue pressing ArrowLeft while holding Shift
7. Observe that as the selection expands into the first line of text, multi-selection occurs prematurely

**Expected behavior**

I can expand the selection until reaching the start of the first line of the paragraph. Only at that point should another ArrowLeft expand to create the multi-selection.

**Screenshots**

arrow-left-multi

**Desktop:**

 - OS: macOS Mojave 10.14.4 (18E226)
 - Browser: Chrome Version 73.0.3683.103 (Official Build) (64-bit)
 - Version: `master` (1df302121f0ab7df8611d01e28ad41db25f40d52)

**Additional context**

The same issue does not appear to occur in the reverse direction, i.e. Shift+ArrowRight does not trigger multi-selection prematurely. **However**, it _never_ triggers the multi-selection, even when reaching the end of the paragraph, which is similarly an unexpected behavior.

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #14871.
Regression caused by #14871.

Specifically, the following code should not have been removed:

https://github.com/WordPress/gutenberg/blob/0563f6f8f9cc2912b67ed6d9ba4a3c910b70e71b/packages/dom/src/dom.js#L89-L95

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by ellatrix** [comment]
Hm, I ran the e2e test against `master`, but it does not fail. Looking again.

**Comment by ellatrix** [comment]
Fixed. Looks like it needed minimum three characters per line.

**Comment by ellatrix** [comment]
I'm not sure why this code change makes 6fa60b2 needed, but this seems the correct behaviour to me now.

**Comment by ellatrix** [comment]
The fixed test was introduced in caaf20474e7e45a6e6669f3fafb3d57edf61662e, which also introduced the code that was removed. But again, the fixed test in this PR seems like the correct behaviour to me. Twice arrow up from a certain horizontal position should land the caret in the same horizontal position if possible.

**Comment by ellatrix** [comment]
I think the reason is that the range is now cloned, before handing it to `getRectangleFromRange`.

`getRectangleFromRange` may unexpectedly modify the live range:

https://github.com/WordPress/gutenberg/blob/0bc90675bcc1638cbdc393bd2bb2588ecc3e8f7e/packages/dom/src/dom.js#L205-L215

**Comment by aduth** [comment]
>Twice arrow up from a certain horizontal position should land the caret in the same horizontal position if possible.

Yes, I compared the results of the test steps on `master` and this branch before seeing your comment, and it very much seems like the correct / improved behavior (you can see in the comment box here on GitHub that a native textarea behaves the same).

File: packages/dom/src/dom.js [hunk 1]
```diff
@@ -93,7 +93,16 @@ function isEdge( container, isReverse, onlyVertical ) {
 		return false;
 	}
 
-	const rangeRect = getRectangleFromRange( selection.getRangeAt( 0 ) );
+	const range = selection.getRangeAt( 0 ).cloneRange();
+	const isForward = isSelectionForward( selection );
+	const isCollapsed = selection.isCollapsed;
```
Comment (aduth) [inline packages/dom/src/dom.js]: Nit: I'll leave it to your preference, but optionally destructure:

```js
const { isCollapsed } = selection;
```

File: packages/dom/src/dom.js [hunk 2]
```diff
@@ -209,6 +218,8 @@ export function getRectangleFromRange( range ) {
 	// See: https://stackoverflow.com/a/6847328/995445
 	if ( ! rect ) {
 		const padNode = document.createTextNode( '\u200b' );
+		// Do not modify to live range.
+		range = range.cloneRange();
```
Comment (aduth) [inline packages/dom/src/dom.js]: It reminds me of some unrelated testing I'd been doing with Chrome line-ending bugginess, where `Range#cloneRange` wasn't actually avoiding mutations to the original:

https://codepen.io/aduth/pen/WPjQoW

(See comment: "// WIP: Buggy, collapses spaces (mutates original).")

I never did figure out what I was seeing with my demos. I raise only in case there's still a worry about mutating the cloned value.

File: packages/dom/src/dom.js [hunk 3]
```diff
@@ -209,6 +218,8 @@ export function getRectangleFromRange( range ) {
 	// See: https://stackoverflow.com/a/6847328/995445
 	if ( ! rect ) {
 		const padNode = document.createTextNode( '\u200b' );
+		// Do not modify to live range.
```
Comment (aduth) [inline packages/dom/src/dom.js]: I'd kinda wonder why it matters, i.e. while true that we're mutating the range, we're also following up with a mutation to remove the added node, which means it should be effectively the same. I'm not entirely clear from the conversation of the pull request what impact this change is having.

**Review by aduth — APPROVED** [review]
Makes sense, tests well.

Not so sure about where `cloneRange` in `getRectangleFromRange` is necessary, but I don't think it can hurt anyways. I'll leave it to your discretion on my feedback.

File: packages/dom/src/dom.js (hunk 2 above)
Comment (ellatrix) [reply packages/dom/src/dom.js]: I've not tested the Codepen, but when you make this change in master, this test will also fail:

https://github.com/WordPress/gutenberg/blob/917338c56c4414642ab744a112ec3c8490316493/packages/e2e-tests/specs/adding-blocks.test.js#L64-L71

It is true that cloning the range in `isEdge` will also prevent this issue, but I think it is safe to clone here is well in case it is called with a live range.

In my testing `insertNode` doesn't modify the original range.

File: packages/dom/src/dom.js (hunk 1 above)
Comment (ellatrix) [reply packages/dom/src/dom.js]: Sounds good!

File: packages/dom/src/dom.js (hunk 3 above)
Comment (ellatrix) [reply packages/dom/src/dom.js]: We do update the DOM again, but not through the range API which may explain why its not restored.
