### PR TITLE
Fix: Cover Block: Default height cuts off taller content.

### LINKED ISSUE #17339: Cover Block: Default height cuts off taller content published before 6.4
This issue has already been mentioned in the PR #17143, but I thought it'd be good to open a new issue for it so that it won't be forgotten :)

Since the default value of the new setting "Height in pixels" is added to all the existing cover block in a site, taller content published before 6.4 gets cut off in the editor with the update. (6.4 is on the right) 

screen-shot-2019-08-31-at-00 19 47

This is a problem in large sites that have a lot of already published posts and page with the block, and I'm curious about the next step to resolve this if there is any.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/17339

This PR fixes a problem introduced during the addition of cover resizing in https://github.com/WordPress/gutenberg/pull/17143.

The resizing functionality should set a min-height to make sure we don't cut content, on the front end everything worked as expected, but on the editor, given the way, re-resizable works content may end up cut.

We were also relying on a hardcoded default height; themes may set their preferred height, so this PR also removes the usage of a default height.

## How has this been tested?
I added a cover block I added some content inside.
I verified when the resize finishes if it made content not appear, the height automatically increases, to make sure content is always shown.
If I remove content, the height decreases until the min-height that was previously set.
The resizing operation is smooth, and after resizing to several different values, when I start resizing again, there are no "jumps" in the dimensions.

### CODE REVIEW

File: packages/block-library/src/cover/edit.js [hunk 1]
```diff
@@ -220,19 +285,18 @@ class CoverEdit extends Component {
 									type="number"
 									id={ inputId }
 									onChange={ ( event ) => {
-										let coverMinHeight = parseInt( event.target.value, 10 );
-										this.setState( { coverMinHeight } );
```
Comment (senadir) [inline packages/block-library/src/cover/edit.js]: removing this breaks the ability to set heights manually, this behavior (keeping the value in state) was first introduced in https://github.com/WordPress/gutenberg/pull/14785#issuecomment-482042904 by @talldan & @Jackie6 
currently, if you try to insert any value then it will directly be changed to 50 (unless you paste a value greater then 50 directly)

File: packages/block-library/src/cover/edit.js [hunk 2]
```diff
@@ -159,13 +221,16 @@ class CoverEdit extends Component {
...
+		const { temporaryMinHeight } = this.state;
+
 		const style = {
 			...(
 				backgroundType === IMAGE_BACKGROUND_TYPE ?
 					backgroundImageStyles( url ) :
 					{}
 			),
 			backgroundColor: overlayColor.color,
+			minHeight: ( temporaryMinHeight || minHeight ) + 'px',
```
Comment (senadir) [inline packages/block-library/src/cover/edit.js]: I don't think we need px here, React assumes it's pixel if it's not set

File: packages/block-library/src/cover/edit.js [hunk 3]
```diff
@@ -220,19 +285,18 @@ class CoverEdit extends Component {
...
 										}
-										setAttributes( { minHeight: coverMinHeight } );
+										setAttributes( {
+											minHeight: coverMinHeight > COVER_MIN_HEIGHT ?
+												coverMinHeight :
+												COVER_MIN_HEIGHT,
+										} );
 									} }
-									value={ this.state.coverMinHeight || minHeight }
+									value={ temporaryMinHeight || minHeight }
```
Comment (senadir) [inline packages/block-library/src/cover/edit.js]: the input value is now controlled from one size only, the resizer, if you set a value here, then trigger  `onResizeStopEvent` the value you set here will be neglected and the height will be the last height set by resizing.

File: packages/block-library/src/cover/edit.js [hunk 4]
```diff
@@ -329,32 +393,26 @@ class CoverEdit extends Component {
...
-						bottomRight: false,
-						bottomLeft: false,
-						topLeft: false,
-					} }
-					onResizeStop={ ( event, direction, elt, delta ) => {
-						const coverHeight = parseInt( minHeight + delta.height, 10 );
-						this.setState( { coverMinHeight: coverHeight } );
-						setAttributes( {
-							minHeight: coverHeight,
+					onResize={ ( newMinHeight ) => {
```
Comment (senadir) [inline packages/block-library/src/cover/edit.js]: why are we using `onResize`? is it so we update the input live?

File: packages/block-library/src/cover/edit.js [hunk 5]
```diff
@@ -329,32 +393,26 @@ class CoverEdit extends Component {
...
 			<>
 				{ controls }
-				<ResizableBox
+				<ResizableCover
 					className={ classnames(
 						'block-library-cover__resize-container',
 						{ 'is-selected': isSelected },
 					) }
-					size={ {
-						height: minHeight,
```
Comment (senadir) [inline packages/block-library/src/cover/edit.js]: Wouldn't it make sense to just delete this to fix the issue?

File: packages/block-library/src/cover/edit.js [hunk 6]
```diff
@@ -69,11 +73,69 @@ function retrieveFastAverageColor() {
...
+	const [ isResizing, setIsResizing ] = useState( false );
+	const onResizeEvent = useCallback(
+		( event, direction, elt ) => {
+			onResize( elt.clientHeight );
+		},
+		[ onResize ],
+	);
+	const onResizeStartEvent = useCallback(
+		() => {
+			setIsResizing( true );
```
Comment (senadir) [inline packages/block-library/src/cover/edit.js]: there is a weird jump if the content is higher then the current height and we resize to below it, the cover will indeed expand again to fit the content, but if you click the resize handle, there will be a jump

**Review by senadir — CHANGES_REQUESTED** [review]
Hi Jorge, thank you for working on this, there a bit of introduced problems, and I'm fully sure why you introduced some things, I will still look into this issue from my side and see if we can fix it without breaking other things.

File: packages/block-library/src/cover/edit.js (hunk 2 above)
Comment (jorgefilipecosta) [reply packages/block-library/src/cover/edit.js]: Suggestion applied 👍

File: packages/block-library/src/cover/edit.js (hunk 4 above)
Comment (jorgefilipecosta) [reply packages/block-library/src/cover/edit.js]: Exactly to update the input live.

File: packages/block-library/src/cover/edit.js (hunk 5 above)
Comment (jorgefilipecosta) [reply packages/block-library/src/cover/edit.js]: I tried that and many other ways to fix the problem and this was the only solution that worked well. It is not straightforward to use re-resizable with min-heights instead of heights.

File: packages/block-library/src/cover/edit.js (hunk 6 above)
Comment (jorgefilipecosta) [reply packages/block-library/src/cover/edit.js]: Nice catch problem addressed 👍

File: packages/block-library/src/cover/edit.js (hunk 1 above)
Comment (jorgefilipecosta) [reply packages/block-library/src/cover/edit.js]: Hi @senadir the input problems were fixed I also solved an existing problem where it was not possible to remove the min-height setting even if I set the input to empty some value would be set on the attribute.

File: packages/block-library/src/cover/edit.js (hunk 3 above)
Comment (jorgefilipecosta) [reply packages/block-library/src/cover/edit.js]: I'm not sure if I understood, in the input field we can set the height for some value. If later a resizing happens the value set by the resizer is used as expected. After using the resizing the user can use again the input field to other value, the last used interaction is the one that is stored as in all other cases.

**Comment by jorgefilipecosta** [comment]
Hi @senadir, thank you for your review, the problems and suggestions you identified/proposed were addressed.

This problem ends up being complex, and before this solution, I tried many others without success.
Re-resizable always sets a height style value and needs a height during the resizing to work.
We can not set a height we need to set min-height to make sure we don't cut content.
This PR adds an important CSS rule to remove the height inline style set by Re-resizable (excluding when resizing).
If a height value is not passed, re-resizable starts resizing from the true height of the element. So if an element has min-height 50px but needs 1000px when resizing, we will start from 1000px and not from 50px to avoid a jump.
When resizing starts, we add a class to make sure the height set by resizing is applied (we need to allow its application).
During the resize, we set a temporary state value, and at the end, we change the attribute.
Changing the attribute during the resize instead of a state value seemed unreliable. I think when we change attributes, a significant block rerender happens. If some dom element resizable is depending on rerenders during a resize, things may not work as expected.
When the resizing stops we commit the attribute change, we remove the temporary resize value, and we remove the is-resizing class. So at that time, the style rule applied will be a min-height again.
I hope I managed to explain what's bewind the solution I'm proposing if you have any other question/thought feel free to ask/share.

File: packages/block-library/src/cover/edit.js (hunk 4 above)
Comment (senadir) [reply packages/block-library/src/cover/edit.js]: could this have performance issues? especially with scaling large images and firing the event too many times? I don't want to premature optimize something and lose a good UX feature (seeing the input being updated) and I guess this won't have any effect since re-resizable is already firing that event, so I guess we can leave it and see if anyone opens an issue regarding this

File: packages/block-library/src/cover/edit.js (hunk 3 above)
Comment (senadir) [reply packages/block-library/src/cover/edit.js]: to better reproduce this issue on your side, try these steps:
1- resize an image using the handles to something like 1000px.
2- resizing the image in the input to something like 500px, the image will indeed resize.
3- attempt to resize from the handles again, the image will jump to 1000px directly, and the input will update to that value directly, therefore neglecting the previous value 500px.

Comment (jorgefilipecosta) [reply packages/block-library/src/cover/edit.js]: Hi @senadir thank you for detailing the problem 👍  I'm not being able to reproduce it. I think it may have been fixed during the last updates :)

**Review by senadir — APPROVED** [review]
I've checked all the changes and it seems they work fine, I would appreciate another eye on this just to be sure I didn't miss anything.

There is however one tiny problem, not a big deal really, when you try to resize the block to something below its height, the block snap back but the input stay at that value, here is a gif.

this problem happens since `onResizeStop` update the attribute with `elm.clientHeight` but the problem, clientHeight immediately change after to the actual height.

This issue is easily fixed by removing the class before reading the height, might use a callback on `setIsResizing` to be safe but as far as I've seen all of those functions are synchronous so no need.

```js
const onResizeStopEvent = useCallback(
	( event, direction, elt ) => {
		setIsResizing( false );
		onResizeStop( elt.clientHeight );
	},
	[ onResizeStop, setIsResizing ]
);
```

inputNotUpdating

**Comment by jorgefilipecosta** [comment]
Hi @senadir thank you for the review!
> There is however one tiny problem, not a big deal really, when you try to resize the block to something below its height, the block snap back but the input stay at that value, here is a gif.

>this problem happens since onResizeStop update the attribute with elm.clientHeight but the problem, clientHeight immediately change after to the actual height.

This behavior is intended. If we have a content height of 700px, if we set in case A the minimum height to 500px, and in case B to 700px, case A and B look the same. But if in case A we remove some content (remove blocks) the height will decrease until the 500px minimum while case B removing content does not decrease the height.


The case where we resize below its height is case A and although after resizing the minimum height setting takes effect and it expands tbe height, the input should stay the same because that's the minimum height attribute of the block.
I guess we should change the label of the field to reflect that the user is setting a minimum height and not height, but I will propose that in other PR to keep discussions focused.

**Comment by senadir** [comment]
took me a couple of minute to understand that, but now I get it, it's actually brilliant way to do it, but I'm afraid it will be confusing.

>I guess we should change the label of the field to reflect that the user is setting a minimum height and not height

I think we should

>but I will propose that in other PR to keep discussions focused.

yes, let's not block this.

**Comment by jorgefilipecosta** [comment]
Given that a very important release is approaching I'm merging this PR so we get as much as testing as possible. If there are other comments anyone feel free to share and we will iterate on this.
