### PR TITLE
Fixed a problem with double encoding of URLs.

### LINKED ISSUE #32837: Navigation Block outputs incorrect percent-encoded URL, resulting in broken link
## Description

Navigation block -- when a link that has slug with characters that gets URL encoded (such as Japanese), the inserted navigation link become wrongly encoded, thus resulting in incorrect URL link that results in 404 when clicked.

For example;

If you create a Page with title `ポートフォリオ` (en: portfolio) and slug also `ポートフォリオ`, the resulting permalink is as follows: `https://fse.test/%e3%83%9d%e3%83%bc%e3%83%88%e3%83%95%e3%82%a9%e3%83%aa%e3%82%aa/`

スクリーンショット 2021-06-20 23 45 30

The slug `ポートフォリオ` is correctly [percent-encoded](https://en.wikipedia.org/wiki/Percent-encoding).

However, when you insert Page Link block of Navigation link, you can insert but the resulting URL become like so`https://fse.test/%25e3%2583%259d%25e3%2583%25bc%25e3%2583%2588%25e3%2583%2595%25e3%2582%25a9%25e3%2583%25aa%25e3%2582%25aa/`

According to the wiki above, percent-encoded `%` is `%25`, so it looks like either; escape `%` character is encoded, or the string is encoded twice?

Same issue were observed with when using the Category Link block. E.g, a category with slug `東京` (en: tokyo)
`https://fse.test/category/%e6%9d%b1%e4%ba%ac/` get output as 
`https://fse.test/category/%25e6%259d%25b1%25e4%25ba%25ac/`

I observed these when using Navigation block, in both the template editor and post editor.

## Step-by-step reproduction instructions

1. Create Page, with just title. Title can be anything. e.g. `ポートフォリオ` but slug must also be something that will get URL encoded.
2. Go to either template editor or post editor
3. Insert Navigation block, horizontal or vertical, then choose "start from blank"
4. Insert Page Link block, choose the page created in step 1.
5. Save and check on the frontend. 

## Expected behaviour

Link to that Page.

## Actual behaviour

Broken link that results in 404

## Screenshots or screen recording (optional)

step-by-step reproduction.

actual behaviout

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.8.2
- Are all plugins except Gutenberg deactivated? Yes
- Theme: TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS 11.4
- Browser: Chrome 91.0.4472.114

### PR DESCRIPTION
**Pull request by torounit**
## Description
Fixed: #32837

This is a fix for slugs that are URL-encoded strings; it fixes a problem where URLs were being converted twice, destroying the URL.

## How has this been tested?

1. Create Page, with just title. Title can be anything. e.g. ポートフォリオ but slug must also be something that will get URL encoded.
1. Go to either template editor or post editor
1. Insert Navigation block, horizontal or vertical, then choose "start from blank"
1. Insert Page Link block, choose the page created in step 1.
1. Save and check on the frontend.
1. Expected behaviour

## Screenshots 
スクリーンショット 2021-06-21 12 02 14
スクリーンショット 2021-06-21 12 02 33

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-library/src/navigation-link/edit.js [hunk 1]
```diff
@@ -200,7 +200,8 @@ export const updateNavigationLinkBlockAttributes = (
 	const kind = isCustomLink ? 'custom' : newKind;
 
 	setAttributes( {
-		...( url && { url: encodeURI( url ) } ),
+		// To prevent double application of encodeURI, decodeURI is executed to revert to the original string.
```
Comment (getdave) [inline packages/block-library/src/navigation-link/edit.js]: Could you add a note on _when_ it might be possible to end up with double application? I assume it's if someone passes a URL that is already encoded?

Comment (torounit) [reply packages/block-library/src/navigation-link/edit.js]: @getdave 

This is the case when a URL that has already been encoded is passed.
The URL suggested by LinkControl is retrieved using the WP-API. And the output of wp-api is URL encoded.

Comment (getdave) [inline packages/block-library/src/navigation-link/edit.js]:
```suggestion
		// Passed `url` may already be encoded. To prevent double encoding, decodeURI is executed to revert to the original string.
```

Comment (getdave) [reply packages/block-library/src/navigation-link/edit.js]: Thanks for explaining. I've made a suggested change to code comment below. A developer coming to this may not have the context of this PR and so I'd favour being explicit about the reason for the change.

It's minor but I feel it's worth it.

**Review by getdave — COMMENTED** [review]
This change looks good and is a great spot. Thank you 👍 

How would you feel about adding an e2e test to cover this scenario?

The Nav Block tests reside here

https://github.com/WordPress/gutenberg/blob/ee69822d9317d0d4c9ca42b951dbf6700b0dadd6/packages/e2e-tests/specs/experiments/blocks/navigation.test.js

You could mock a search response which contains some pre-encoded URL (as in your test instructions) and then assert that it's handled correctly by the Nav Link block.

**Comment by torounit** [comment]
@getdave I've added a test. Please check it out.

**Review by aristath — APPROVED** [review]
LGTM :+1:

File: packages/e2e-tests/specs/experiments/blocks/navigation.test.js [hunk 2]
```diff
@@ -465,6 +465,64 @@ describe( 'Navigation', () => {
...
+		const isInURLInput = await page.evaluate(
+			() =>
+				!! document.activeElement.matches(
+					'input.block-editor-url-input__input'
+				)
+		);
+		expect( isInURLInput ).toBe( true );
+		await page.keyboard.press( 'Escape' );
+
+		//click the link placeholder
```
Comment (getdave) [inline packages/e2e-tests/specs/experiments/blocks/navigation.test.js]:
```suggestion
		// Click the link placeholder
```

File: packages/e2e-tests/specs/experiments/blocks/navigation.test.js [hunk 3]
```diff
@@ -465,6 +465,64 @@ describe( 'Navigation', () => {
...
+		const placeholder = await page.waitForSelector(
+			'.wp-block-navigation-link__placeholder'
+		);
+		await placeholder.click();
+
+		// For the second nav link block use an existing internal page.
+		// Mock the api response so that it's consistent.
```
Comment (getdave) [inline packages/e2e-tests/specs/experiments/blocks/navigation.test.js]:
```suggestion
		// Mocked response for internal page.
		// We are encoding the slug/url in order
		// that we can assert it is not double encoded by the block.
```

File: packages/e2e-tests/specs/experiments/blocks/navigation.test.js [hunk 4]
```diff
@@ -465,6 +465,64 @@ describe( 'Navigation', () => {
...
+		await mockSearchResponse( [
+			{ title: 'お問い合わせ', slug: encodeURI( 'お問い合わせ' ) },
+		] );
+
+		// Add a link to the default Link block.
```
Comment (getdave) [inline packages/e2e-tests/specs/experiments/blocks/navigation.test.js]:
```suggestion
		// Select the mocked internal page above.
```

File: packages/e2e-tests/specs/experiments/blocks/navigation.test.js [hunk 5]
```diff
@@ -465,6 +465,64 @@ describe( 'Navigation', () => {
...
+		await updateActiveNavigationLink( {
+			url: 'お問い合わせ',
+			type: 'entity',
+		} );
+
+		// Expect a Navigation Block with two Links in the snapshot.
```
Comment (getdave) [inline packages/e2e-tests/specs/experiments/blocks/navigation.test.js:523]:
```suggestion
		// Expect a Navigation Block with two Links in the snapshot.
		// The 2nd link should not be double encoded.
```

**Review by getdave — APPROVED** [review]
Thank you for taking the time to add this e2e test. Great work 👍 

Some minor nits here around code comments in the tests just to make things clearer. Otherwise good to go.

Thank you again for taking the time to address this issue 🙇‍♂️

**Comment by torounit** [comment]
@aristath @getdave Thank you for reviewing !!!!

**Comment by torounit** [comment]
@aristath Can I merge this PR?

**Comment by getdave** [comment]
@torounit If you have a 👍 review and all checks are passing then feel free to merge.
