### PR TITLE
Block editor: iframe/writing flow: change tab index to 0

### LINKED ISSUE #46258: Iframe: Body tag can receive negative tabindex impacting screen reader A11Y
### Description

When I enter the block toolbar and return from it, the screen reader reads all blocks in the block list until it reaches the focus point of the selected block. This is because the focus passes through a `tabindex="-1"` on the `body` tag of the iFrame.

I have a feeling removing this attribute may not be straight forward. Could be tied in with writing flow and it is also possible that removing the attribute could break focus styles inside the `body` tag.

### Step-by-step reproduction instructions

1. Start a screen reader such as NVDA on Windows.
2. Open the site editor.
3. Select a block, second or third one in the list should do.
4. Press shift+tab to focus the block toolbar.
5. Press tab to focus the current block.
6. Notice how the first blocks are read by the screen reader until the block you currently have focus on is reached.

I believe this generally happens because `tabindex="-1"` is not a tabbable index. The screen reader has no choice but to enter it because the content within is tabbable but it likely gets confused. You can always focus -1 but not tab to it.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

Gutenberg: trunk
Browser: Firefox/Google Chrome
Screen reader: NVDA
OS: Windows 10

Probably able to reproduce in other environments as well.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Tries to fix #46258. Changes the tab index of writing flow (which is the body element in case of an iframe) to 0 (from -1).

I've tested with VoiceOver on Mac, but can't really reproduce the issue, so I'm working in the dark.

@alexstine Does this resolve the issue you're experiencing?

## Why?

See https://github.com/WordPress/gutenberg/issues/46258.

## Testing Instructions

See https://github.com/WordPress/gutenberg/issues/46258 for detailed instructions.

### CODE REVIEW

File: packages/block-editor/src/components/writing-flow/index.js [hunk 1]
```diff
@@ -44,7 +44,7 @@ export function useWritingFlow() {
 			useArrowNav(),
 			useRefEffect(
 				( node ) => {
-					node.tabIndex = -1;
+					node.tabIndex = 0;
```
Comment (alexstine) [inline packages/block-editor/src/components/writing-flow/index.js:47]: Hmm, I wonder if this adds an empty tab stop. Not real familiar with how this code works, but doesn't this refer to the virtual DOM div that gets an adjusted tabindex? Maybe this is just the initial value or something.

**Review by alexstine — COMMENTED** [review]
@ellatrix Thanks for the PR. I am on a business trip this week, I will review when I return home next week. One comment below but hard to really say without testing.

File: packages/block-editor/src/components/writing-flow/index.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-editor/src/components/writing-flow/index.js:47]: This is on the writing flow wrapper, so it shouldn't add an extra tab stop because we intercept tab before and after the writing flow container. Alternatively, I think we can set set this tab index only when multiple blocks are selected (because this is where we move focus), but I don't think it hurts to add it permanently.

**Review by alexstine — APPROVED** [review]
@ellatrix Yep, it does look like if you tab from the Options button through the writing flow wrapper, there is now an empty tab stop. I was thinking this might happen. Not really sure how to go about fixing it unless when focus passes through the wrapper, we focus an element vs. the div.

Anyway, this PR fixes the underlying issue and I think this can be revisited as writing flow concepts will likely change down the road.

Sorry for the delay, long backlog after trip.

**Comment by alexstine** [comment]
One other honorable mention, the site editor still does not work for some reason. Not sure what is going on there but this does work for the post editor and the changes you made for the iFrame. I'll likely have to make a Zoom video as I doubt anyone could figure it out visually. There is an unbelievable amount of focus loss in the site editor and not sure why considering the same issues do not exist even with the new iFrame in the post editor.
