### PR TITLE
Fix broken Page title for pages created inline within in Nav block

### LINKED ISSUE #30111: Navigation Block: Creating a draft page with “&” results in HTML Entities
## Description

When using the Create Draft feature in the navigation block, if you add &, it results in a draft being created showing the HTML entities for ampersand instead of &. 

This came up as part of feedback for [the third round of testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/03/09/fse-program-testing-call-3-create-a-fun-custom-404-page/#comment-1430). 

## Step-by-step reproduction instructions

1. Add the navigation block. 
2. Add a new menu item. 
3. Select adding a new link and begin typing the title of a page that doesn't exist. When you do so, include &.
4. Select the option to create a page draft.
5. See that the menu item doesn't show ampersand. 

## Expected behaviour

The & would show in the navigation block.

## Actual behaviour

HTML entities were shown in the navigation block.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/112059251-37b93b80-8b21-11eb-9803-38e7ce6ab36c.mov

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop 
- Operating system: MacOS
- Browser: Chrome Version 88.0.4324.192

### PR DESCRIPTION
**Pull request by getdave**
## What?

Fixes https://github.com/WordPress/gutenberg/issues/30111.

Fixes the output of decoded and/or escaped HTML entities in the Nav block when creating a link (page) from within the Link UI that contains chars such as `&`. 

## Why?

There are two facets to this PR:

- display of encoded HTML entities
- unwanted `escape`ing of the label for draft posts

### Display of encoded HTML entities

Calling `saveEntityRecord` results in an API response which contains a `title` field with the following:

```
// title property is an object
{
    "raw": "Yes & No",
    "rendered": "Yes &#038; No"
}
```

The `handleCreate` function in the Nav Link block consumes the  `title.rendered` field of the newly created Page post type.

https://github.com/WordPress/gutenberg/blob/b4955801f1ea052511c17e71d78f31006611bb60/packages/block-library/src/navigation-link/edit.js#L606-L612

This field contains a version of the post title which has been passed through various WordPress display filters and thus contains HTML entities (e.g. `Yes &#038; No`).

We then render this directly into the Nav link block which means we "see" the entities.

To fix this we now call `decodeEntities` on the `rendered` field. We could just use the `raw` field but the current approach is more consistent with the implementation in `fetchLinkSuggestions` which is also consuming the `rendered` field:

https://github.com/WordPress/gutenberg/blob/a1e1fdc0e6278457e9f4fc0b31ac6d2095f5450b/packages/core-data/src/fetch/__experimental-fetch-link-suggestions.js#L212-L218

### Unwanted `escape`ing of the label for draft posts

The output of the Nav Link block's `label` attribute is handled differently depending on the post status of the post represented by the link.

Posts with a `Published` status they are output into a `<RichText>` field:

https://github.com/WordPress/gutenberg/blob/b83ce72de13b0a0f4b84733bd61a4f91271fee95/packages/block-library/src/navigation-link/edit.js#L741-L745

Posts with a `Draft` status are output into a `<span>`.

https://github.com/WordPress/gutenberg/blob/b83ce72de13b0a0f4b84733bd61a4f91271fee95/packages/block-library/src/navigation-link/edit.js#L798-L803

Unfortunately the following code from `updateNavigationLinkBlockAttributes` which updates the Navigation Link block attributes escapes the title before it is output to the DOM. Indeed, the escaping model here appears to have become inverted, with the content being escaped for storage in block attributes (and ultimately in the database) when it would have been preferable to escape (or not!) at the point of output.

https://github.com/WordPress/gutenberg/blob/b83ce72de13b0a0f4b84733bd61a4f91271fee95/packages/block-library/src/navigation-link/edit.js#L242-L244

The result, is that for draft posts being rendered into a `<span>` we see an escaped version of the label attribute (e.g. `Yes &amp; No`).

This doesn't happen for posts with a `published` status because they are rendered into a `RichText` and thus the escaping isn't "visible" to the user.

To fix this we have to "restore" the data by `unescape`ing the label for draft posts.

## How?

This PR fixes things by:

1. Decoding the the page title returned by `handleCreate` making it consistent with [`fetchLinkSuggestions`](https://github.com/WordPress/gutenberg/blob/a1e1fdc0e6278457e9f4fc0b31ac6d2095f5450b/packages/core-data/src/fetch/__experimental-fetch-link-suggestions.js#L212-L218).
2. Unescaping the (prematurely escaped) `label` attribute before it is output in the `<span>` for Draft pages.

## Testing Instructions

- Add the navigation block.
- Add a new menu item.
- Select adding a new link and begin typing the title of a page that doesn't exist. When you do so, include &.
- Select the option to create a page draft.
- See that the menu item is rendered in the block without any HTML entities or escaped HTML.
- Create some published pages containing `&`. 
- Add these to a Nav block and check that the `&` is still rendered correctly.

## Screenshots or screencast 

https://user-images.githubusercontent.com/444434/168383990-1a56bbc6-3b71-44c9-b9f6-9afc39709791.mov

### CODE REVIEW

File: packages/block-library/src/navigation-link/edit.js [hunk 1]
```diff
@@ -232,16 +233,10 @@ export const updateNavigationLinkBlockAttributes = (
...
 	const normalizedURL = url.replace( /http(s?):\/\//gi, '' );
-	const escapeTitle =
-		title !== '' &&
-		normalizedTitle !== normalizedURL &&
-		originalLabel !== title;
 
-	const label = escapeTitle
-		? escape( title )
-		: originalLabel || escape( normalizedURL );
+	const label = decodeEntities( title ) || originalLabel || normalizedURL;
```
Comment (getdave) [inline packages/block-library/src/navigation-link/edit.js]: The alternative here is using `.raw` instead of `.rendered` on the return value from the API. But I'm still not clear on what the difference is between the two fields in this context.

**Comment by getdave** [comment]
The unit tests are failing due to `it( 'label is javascript escaped', () => {` which expects `updateNavigationLinkBlockAttributes` to be doing the escaping (this was related to https://github.com/WordPress/gutenberg/pull/18617).

However, this PR moves the escaping to render time so as to selectively choose whether it's appropriate to escape or not depending on context.

We should be able to remove the test.

**Comment by getdave** [comment]
@draganescu as you reviewed https://github.com/WordPress/gutenberg/pull/18617 would you mind taking a look at this one?

**Comment by draganescu** [comment]
Why don't we decode in the span?

**Comment by getdave** [comment]
> Why don't we decode in the span?

~I think the decoding is required for both places but we could do that inline as well I guess.~

Decoding is actually only required when we're outputting the `.rendered` field in HTML. Therefore I've moved the decode call to where the draft page title is output.

We're still escaping when we're putting stuff into the `<RichText>` component but that's now done at point of output.

File: packages/block-library/src/navigation-link/edit.js (hunk 1 above)
Comment (getdave) [reply packages/block-library/src/navigation-link/edit.js]: Here's where the fields are constructed by the REST API

https://github.com/WordPress/wordpress-develop/blob/19abcf2c4640ca5660089a6ada5eafbf8e4a5fa3/src/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L1779-L1791

It's basically as follows:

```php
$data['title']['rendered'] = get_the_title( $post->ID );
$data['title']['raw'] = $post->post_title;
```

Essentially [rendered passes through default filters](https://github.com/WordPress/wordpress-develop/blob/613cac5a2d809a4078b23945a6c57750bdebd9b0/src/wp-includes/default-filters.php#L180-L182) whereas raw doesn't:

```php
add_filter( 'the_title', 'wptexturize' );
add_filter( 'the_title', 'convert_chars' );
add_filter( 'the_title', 'trim' );
```

- [convert_chars](https://developer.wordpress.org/reference/functions/convert_chars/) - Converts lone & characters into &#038; (a.k.a. &amp;)
- [wptexturize](https://developer.wordpress.org/reference/functions/wptexturize/) - Replaces common plain text characters with formatted entities.

So the later is why we get entities when rendering I guess.

**Review by draganescu — DISMISSED** [review]
LGTM!

File: packages/block-library/src/navigation-link/edit.js [hunk 2]
```diff
@@ -232,16 +233,10 @@ export const updateNavigationLinkBlockAttributes = (
 		kind: newKind = originalKind,
 		type: newType = originalType,
 	} = updatedValue;
-	const normalizedTitle = title.replace( /http(s?):\/\//gi, '' );
+
 	const normalizedURL = url.replace( /http(s?):\/\//gi, '' );
-	const escapeTitle =
-		title !== '' &&
-		normalizedTitle !== normalizedURL &&
-		originalLabel !== title;
```
Comment (draganescu) [inline packages/block-library/src/navigation-link/edit.js:240]: so don’t escape if:

- title is empty
- the link already has a label which is not the title
- we obtained a title, so we don’t use the URL

probably the conditions here are to avoid double escaping? IDK.

File: packages/block-library/src/navigation-link/edit.js (hunk 1 above)
Comment (getdave) [reply packages/block-library/src/navigation-link/edit.js]: I've stuck with `rendered` but used `decodeEntities` at point of output rather than when saving the attrs.

**Comment by getdave** [comment]
I think we should include an e2e test here as well.

**Comment by adamziel** [comment]
I've walked through all that with Dave and we concluded that the escaping model is inverted. We store the escaped content in the block attributes, then recover the raw data in JS. Instead, I'd like to store the raw data in the block attributes and escape it in JS.

Why? Because there isn't one way to escape data. Depending on the context, you need to do different transforms. It doesn't make sense to me to choose one of them for the purposes of storage.

Now, inverting the escaping model is quite a large project. I think the rendering fix @getdave proposes here is a perfectly good solution for starters.

**Review by adamziel — APPROVED** [review]
E2E failures seem unrelated and the code works and makes sense. Let's leave a note explaining why it's all so confusing and 🚢

File: packages/block-library/src/navigation-link/edit.js [hunk 3]
```diff
@@ -797,8 +817,13 @@ export default function NavigationLinkEdit( {
 										<>
 											<span>
 												{
-													/* Trim to avoid trailing white space when the placeholder text is not present */
-													`${ label } ${ placeholderText }`.trim()
+													// Some attributes are stored in an escaped form due to the escaping model
```
Comment (adamziel) [inline packages/block-library/src/navigation-link/edit.js]:
```suggestion
													// Some attributes are stored in an escaped form.  – It's a legacy issue, ideally they would be stored in a raw, unescaped form.
```

**Review by adamziel — APPROVED** [review]

File: packages/block-library/src/navigation-link/edit.js (hunk 3 above)
Comment (getdave) [reply packages/block-library/src/navigation-link/edit.js]: Thanks for suggestion. I've updated in https://github.com/WordPress/gutenberg/pull/41063/commits/0d0de3a1e3916002f9f98102ef6d4bd90334a070.
