### PR TITLE
`InputControl`: Fix acceptance of falsy values in controlled updates

### LINKED ISSUE #42455: Inspector Controls: Inputs aren't clearing after control is reset via panel menu
### Description

When resetting some of the more complex or compound controls via their panel's menu, their inputs aren't being cleared. This is affecting multiple controls in the Inspector Controls sidebar including padding, margin, borders and border radii etc.

A git bisect shows this regressed when https://github.com/WordPress/gutenberg/pull/40518 landed.

#### Expected Behaviour

When resetting a control, its value is cleared from its field, when that field doesn't have any default value.

#### Actual Behaviour

When resetting the padding control, for example, its individual side controls are not cleared after resetting padding via the panel's menu

### Step-by-step reproduction instructions

1. Edit a post, add a group block and select it
2. In the sidebar, set a padding value under Dimensions, then unlinked the control
3. Reset the padding via the Dimensions panel's menu and note that your previous value is still displayed in the unlinked controls
4. Link the padding control again and notice that the singular padding field is in fact empty.
5. Unlink the fields again and note the fields are now cleared
6. Repeat this process for padding, margin, borders, or border radius. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/60436221/179169262-4ad562ca-80a3-4437-b560-7379fedbfe28.mp4

### Environment info

- WP: 6.0
- Gutenberg: `trunk`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by stokesman**
## What?
Makes `InputControl` handling of updates from props distinct from any other action.

## Why?
To fix #42455. Presently the `RESET` action is used to handle updates from props and that favors a fallback value over a falsy one:
https://github.com/WordPress/gutenberg/blob/875a20481d2329adfb4eb87fe082dce24f2e0f8c/packages/components/src/input-control/reducer/reducer.ts#L98-L101
That means that that falsy values coming from props will not be used which is the cause of the issue.

## How?
- In order to have a test that will fail in case of another regression, an existing test is updated to use a falsy value
- The handling of updates from props made distinct to any other existing action types

## Testing Instructions
1. After fetching and switching to this branch, checkout the first commit
2. run `npm test-unit input-control` to verify the changed test fails
3. Switch back to the whole branch `git switch -`
4. repeat step 2 but note the test passes
5. Try reproducing the issue in #42455 as detailed in its reproduction instructions

### CODE REVIEW

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for the quick turnaround and fix @stokesman 🚀 

✅ Updated unit test fails as expected on initial commit on the branch
✅ Could still replicate the issue in both Storybook & editors
✅ After checking out latest on PR branch the unit tests pass
✅ Fix resolves the original issue in the editor & storybook. 
✅ Components are still functioning in Storybook

| Before | After |
|---|---|
| <video src="https://user-images.githubusercontent.com/60436221/179432197-73e8fe57-ba4d-4569-95d5-eda8dd4d0a96.mp4" /> | <video src="https://user-images.githubusercontent.com/60436221/179432205-4d1f2f58-a59f-4ae0-93c5-149b21e238ff.mp4" /> |

LGTM!

**Comment by ciampo** [comment]
Would it make sense to add a unit test to avoid future regressions?

**Comment by stokesman** [comment]
That was why I tweaked the test in eb9e1bc. I think it suffices but let me know if you see a fault with that.

**Review by ciampo — COMMENTED** [review]
Thank you for the reply — I had missed that small change in my first pass of this PR.

With regards to the changes in this PR, it would be good if we could find an approach that preserves the reducer's "purity" (i.e. accepting action objects).

Since you mentioned this snippet related to the dispatch `RESET` action https://github.com/WordPress/gutenberg/blob/875a20481d2329adfb4eb87fe082dce24f2e0f8c/packages/components/src/input-control/reducer/reducer.ts#L98-L101

Wouldn't be possible to use the null coalescing operator `??` to let falsy values through?

```
nextState.value = action.payload.value ?? state.initialValue;
```

**Comment by stokesman** [comment]
>Wouldn't be possible to use the null coalescing operator ?? to let falsy values through?
>`nextState.value = action.payload.value ?? state.initialValue;`

That would work for empty strings or `0` but I think in the case of `BoxControl` it's actually sending `undefined` on the reset. Other than that you might recall the concern I had with reusing `RESET` https://github.com/WordPress/gutenberg/pull/40518#discussion_r884353346. So it seemed an opportune time to also address that.

>it would be good if we could find an approach that preserves the reducer's "purity" (i.e. accepting action objects).

We can add another action (we used to have `UPDATE` for this). I don't see it as having any significant advantage or disadvantage compared this branch as it is now.

**Comment by ciampo** [comment]
> We can add another action (we used to have UPDATE for this).

That would my preferred solution — if the `UDPATE` action is going to be used for controlled updates for props, then we could rename it to `CONTROLLED_UPDATE` (or at least add a comment explaining what makes that action different from `CHANGE`, for example)

> I don't see it as having any significant advantage or disadvantage compared this branch as it is now.

The advantage that I see is that we would keep `inputControlStateReducer` as a canonical reducer function (i.e.  a function that receives the current `state` and an `action` object, decides how to update the `state` if necessary, and returns the new `state`)

**Comment by mirka** [comment]
> The advantage that I see is that we would keep `inputControlStateReducer` as a canonical reducer function (i.e. a function that receives the current `state` and an `action` object

Same. If there are no significant tradeoffs, I would prefer an explicit action type. At least as a casual code reader, I would expect there to always be a `type`.

File: packages/components/src/input-control/reducer/state.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ export interface InputState {
 	value?: string;
 }
 
-export type StateReducer = Reducer< InputState, InputAction >;
+export type StateReducer = Reducer< InputState, InputAction | ControlAction >;
```
Comment (ciampo) [inline packages/components/src/input-control/reducer/state.ts]: Shouldn't the `ControlAction` be part of the [`InputAction` type](https://github.com/WordPress/gutenberg/blob/cc941d49c9db171a570f19d5afc8034cf522043c/packages/components/src/input-control/reducer/actions.ts#L54) ?

File: packages/components/src/input-control/reducer/reducer.ts [hunk 2]
```diff
@@ -51,21 +50,22 @@ function mergeInitialState(
...
-			};
-		}
 		const nextState = { ...state };
 
 		switch ( action.type ) {
+			/*
+			 * Controlled updates
+			 */
+			case actions.CONTROL:
+				nextState.value = `${ action.payload.value }`;
```
Comment (ciampo) [inline packages/components/src/input-control/reducer/reducer.ts]: For all other actions, `action.payload.value` is assigned to `nextState.value` without it being wrapped in a string — is there a particular reason for it? Otherwise I believe it would be better to keep the same "behavior" as in the rest of the reducer

```suggestion
				nextState.value = action.payload.value;
```

File: packages/components/src/input-control/reducer/reducer.ts [hunk 3]
```diff
@@ -221,7 +221,10 @@ export function useInputControlStateReducer(
 			initialState.value !== currentState.current.value &&
 			! currentState.current.isDirty
 		) {
-			dispatch( { value: initialState.value } );
+			dispatch( {
+				type: actions.CONTROL,
+				payload: { value: initialState.value ?? '' },
```
Comment (ciampo) [inline packages/components/src/input-control/reducer/reducer.ts:232]: Would it make sense for the `?? ''` part to be moved directly in the reducer? e.g

```js
nextState.value = action.payload.value ?? '';
```

**Review by ciampo — COMMENTED** [review]
Changes test well — I just left a few more comments, but this is looking close!

File: packages/components/src/input-control/reducer/state.ts (hunk 1 above)
Comment (stokesman) [reply packages/components/src/input-control/reducer/state.ts]: I can see why you'd ask. Looking at this more closely, given we are okay with the way I've wired up `CONTROL` to be exclusively handled by the base reducer, then I'll say no, and yet it's still not quite right as is. The extending reducers will never receive `CONTROL` actions so `StateReducer` would be too loose a type for those.

<details><summary>I'm thinking we should we keep <code>ControlAction</code> out of both <code>InputAction</code> and <code>StateReducer</code> then make only the base reducer typed to accept it.</summary>

```diff
diff --git a/packages/components/src/input-control/reducer/reducer.ts b/packages/components/src/input-control/reducer/reducer.ts
index 3f3302608d..a5f80026a6 100644
--- a/packages/components/src/input-control/reducer/reducer.ts
+++ b/packages/components/src/input-control/reducer/reducer.ts
@@ -1,7 +1,7 @@
 /**
  * External dependencies
  */
-import type { SyntheticEvent, ChangeEvent, PointerEvent } from 'react';
+import type { SyntheticEvent, ChangeEvent, PointerEvent, Reducer } from 'react';
 
 /**
  * WordPress dependencies
@@ -50,7 +50,7 @@ function mergeInitialState(
  */
 function inputControlStateReducer(
 	composedStateReducers: StateReducer
-): StateReducer {
+): Reducer< InputState, actions.InputAction | actions.ControlAction > {
 	return ( state, action ) => {
 		const nextState = { ...state };
 
@@ -151,7 +151,7 @@ export function useInputControlStateReducer(
 	initialState: Partial< InputState > = initialInputControlState,
 	onChangeHandler: InputChangeCallback
 ) {
-	const [ state, dispatch ] = useReducer< StateReducer >(
+	const [ state, dispatch ] = useReducer(
 		inputControlStateReducer( stateReducer ),
 		mergeInitialState( initialState )
 	);
diff --git a/packages/components/src/input-control/reducer/state.ts b/packages/components/src/input-control/reducer/state.ts
index 53a49aa765..2ca9edaa27 100644
--- a/packages/components/src/input-control/reducer/state.ts
+++ b/packages/components/src/input-control/reducer/state.ts
@@ -6,7 +6,7 @@ import type { Reducer, SyntheticEvent } from 'react';
 /**
  * Internal dependencies
  */
-import type { ControlAction, InputAction } from './actions';
+import type { InputAction } from './actions';
 
 export interface InputState {
 	_event?: SyntheticEvent;
@@ -19,7 +19,7 @@ export interface InputState {
 	value?: string;
 }
 
-export type StateReducer = Reducer< InputState, InputAction | ControlAction >;
+export type StateReducer = Reducer< InputState, InputAction >;
 
 export const initialStateReducer: StateReducer = ( state: InputState ) => state;
 
```
</details>

File: packages/components/src/input-control/reducer/reducer.ts (hunk 2 above)
Comment (stokesman) [reply packages/components/src/input-control/reducer/reducer.ts]: I suppose that when used in a type-checked environment no one will ever provide anything but a string as `InputControl`’s `value` but if we'd like it to ensure it's actually a string at runtime this seemed good.

With your mention of the other actions, it makes me realize they could also be a place that non-string types are slipped in at runtime by an extending reducer and so if we want to ensure string type at runtime we could look at doing it in a single place before the base reducer returns so it would cover all actions.

I'm happy to apply your suggestion and save this for a follow up (or not at all if it doesn't seem worthy of concern).

File: packages/components/src/input-control/reducer/reducer.ts (hunk 3 above)
Comment (stokesman) [reply packages/components/src/input-control/reducer/reducer.ts:232]: It was in the reducer back in ad3cda1. Now reusing `ValuePayload` with `ControlAction` means it would create a type mismatch unless (as done here) the potential `undefined` is eliminated beforehand. The alternatives I can think of:
- add and use a new type that's the same as `ValuePayload` except `value` is optional
- retype `ValuePayload` to make `value` optional

Those are in order of my preference (behind not changing it) but I'm glad to learn if there's a better option and/or of any drawbacks with how it is now.

File: packages/components/src/input-control/reducer/reducer.ts (hunk 2 above)
Comment (ciampo) [reply packages/components/src/input-control/reducer/reducer.ts]: > With your mention of the other actions, it makes me realize they could also be a place that non-string types are slipped in at runtime by an extending reducer and so if we want to ensure string type at runtime we could look at doing it in a single place before the base reducer returns so it would cover all actions.

For the sake of consistency, I believe that we should apply the same strategy to all actions — so this option sounds like a good idea.

> I'm happy to apply your suggestion and save this for a follow up (or not at all if it doesn't seem worthy of concern).

I'd rather do this in a follow-up, so that we keep our PRs small and focused

File: packages/components/src/input-control/reducer/reducer.ts (hunk 3 above)
Comment (ciampo) [reply packages/components/src/input-control/reducer/reducer.ts:232]: Thank you for the extra context — let's keep it like this. I know that there are implications when fallbacking from `undefined` to `''` (ie. switching controlled/uncontrolled mode), so it's probably better to keep the code as is.

Comment (ciampo) [reply packages/components/src/input-control/reducer/reducer.ts:232]: One extra thing I noticed — in this `useInputControlStateReducer` there are several `useLayoutEffect` calls

https://github.com/WordPress/gutenberg/blob/cc941d49c9db171a570f19d5afc8034cf522043c/packages/components/src/input-control/reducer/reducer.ts#L202-L229

It would be great if we could add inline comments for each of these `useLayoutEffect` calls explaining what is their purpose / what they are achieving, as the code is quite convoluted and it can be complicated for a developer that is not familiar with `InputControl` to make sense of it — would you be able to do that? Thank you!

File: packages/components/src/input-control/reducer/state.ts (hunk 1 above)
Comment (ciampo) [reply packages/components/src/input-control/reducer/state.ts]: The approach that you propose sounds reasonable — maybe we could experiment with generics in the `StateReducer` type, so that we keep all type defs in the same file?

<details>

<summary>Something like this</summary>

```diff
diff --git a/packages/components/src/input-control/reducer/reducer.ts b/packages/components/src/input-control/reducer/reducer.ts
index 3f3302608d..c41ae85775 100644
--- a/packages/components/src/input-control/reducer/reducer.ts
+++ b/packages/components/src/input-control/reducer/reducer.ts
@@ -50,7 +50,7 @@ function mergeInitialState(
  */
 function inputControlStateReducer(
 	composedStateReducers: StateReducer
-): StateReducer {
+): StateReducer< actions.ControlAction > {
 	return ( state, action ) => {
 		const nextState = { ...state };
 
@@ -151,7 +151,7 @@ export function useInputControlStateReducer(
 	initialState: Partial< InputState > = initialInputControlState,
 	onChangeHandler: InputChangeCallback
 ) {
-	const [ state, dispatch ] = useReducer< StateReducer >(
+	const [ state, dispatch ] = useReducer(
 		inputControlStateReducer( stateReducer ),
 		mergeInitialState( initialState )
 	);
diff --git a/packages/components/src/input-control/reducer/state.ts b/packages/components/src/input-control/reducer/state.ts
index 53a49aa765..839ac51383 100644
--- a/packages/components/src/input-control/reducer/state.ts
+++ b/packages/components/src/input-control/reducer/state.ts
@@ -6,7 +6,7 @@ import type { Reducer, SyntheticEvent } from 'react';
 /**
  * Internal dependencies
  */
-import type { ControlAction, InputAction } from './actions';
+import type { InputAction } from './actions';
 
 export interface InputState {
 	_event?: SyntheticEvent;
@@ -19,7 +19,10 @@ export interface InputState {
 	value?: string;
 }
 
-export type StateReducer = Reducer< InputState, InputAction | ControlAction >;
+export type StateReducer< TAdditionalAction = {} > = Reducer<
+	InputState,
+	InputAction | TAdditionalAction
+>;
 
 export const initialStateReducer: StateReducer = ( state: InputState ) => state;
 
```
</details>

We should probably also add a comment about `inputControlStateReducer` being the only reducer exposing / handling the `CONTROL` action — which means that it's an action that doesn't get exposed to external reducer middleware, meant to be used only internally. Maybe in the `inputControlStateReducer`'s JSDocs ?

Comment (stokesman) [reply packages/components/src/input-control/reducer/state.ts]: Done in 9aef4eb though it required a touch of the `Action` type as well. At first I didn't favor the idea generalizing the `StateReducer` type for a singular exception to its shape but given that we're interested in refactoring to a hook+component combo https://github.com/WordPress/gutenberg/pull/41264#issuecomment-1139077885 there will be opportunity make more use of the generic.

File: packages/components/src/input-control/reducer/reducer.ts (hunk 2 above)
Comment (stokesman) [reply packages/components/src/input-control/reducer/reducer.ts]: 👍 1456a56

File: packages/components/src/input-control/reducer/state.ts (hunk 1 above)
Comment (stokesman) [reply packages/components/src/input-control/reducer/state.ts]: > …add a comment about inputControlStateReducer being the only reducer exposing / handling the CONTROL action

Done in f394357

File: packages/components/src/input-control/reducer/reducer.ts (hunk 3 above)
Comment (stokesman) [reply packages/components/src/input-control/reducer/reducer.ts:232]: >…add inline comments for each of these useLayoutEffect calls explaining what is their purpose…

Done in 3b54cff

**Comment by stokesman** [comment]
Feedback is hopefully addressed satisfactorily. In case not, I've left the rebase/conflict pending for the moment.

File: packages/components/src/input-control/reducer/state.ts [hunk 4]
```diff
@@ -19,7 +19,10 @@ export interface InputState {
 	value?: string;
 }
 
-export type StateReducer = Reducer< InputState, InputAction >;
+export type StateReducer< SpecializedAction = Action > = Reducer<
+	InputState,
+	InputAction | SpecializedAction
+>;
```
Comment (ciampo) [inline packages/components/src/input-control/reducer/state.ts]: In the current state of this PR, the `StateReducer` type would accept _any_ action-like object (this can be verified by inspecting [`action.type`](https://github.com/WordPress/gutenberg/blob/3b54cff387981613a3074ff3338c9bbbe438566f/packages/components/src/input-control/reducer/reducer.ts#L57) and seeing what possible values are attributed to it by the TypeScript engine).

Instead, what we'd like to achieve is:
- When `SpecializedAction` is not defined, `StateReducer` should only allow actions from the `InputActions` type
- When `SpecializedAction` is defined, `StateReducer` should only allow actions from either the `InputActions` type, or the `SpecializedAction` type (although we need to make sure that `SpecializedAction` is a valid `Action`).

I played around with code a bit and I think this should be a good solution:

```suggestion
export type StateReducer< SpecializedAction = {} > = Reducer<
	InputState,
	SpecializedAction extends Action
		? InputAction | SpecializedAction
		: InputAction
>;
```

**Review by ciampo — COMMENTED** [review]
> Feedback is hopefully addressed satisfactorily. In case not, I've left the rebase/conflict pending for the moment.

I left one last comment, but the changes required should not add runtime changes to this PR. 

When that's addressed, we can rebase and give this PR a final check before merging :)

File: packages/components/src/input-control/reducer/state.ts (hunk 4 above)
Comment (stokesman) [reply packages/components/src/input-control/reducer/state.ts]: Very neat Marco! Applied in 30d7c31. I don't recall having seen such logic in typing. TIL 🙌

Comment (ciampo) [reply packages/components/src/input-control/reducer/state.ts]: Thank you! I learnt this technique by reading the definition of the `WordPressComponentProps` type 
https://github.com/WordPress/gutenberg/blob/33d84b036592a5bf31af05b7710f3b2b14163dc4/packages/components/src/ui/context/wordpress-component.ts#L19-L24

**Review by ciampo — APPROVED** [review]
LGTM 🚀 

Thank you as always for your work, @stokesman !

**Comment by stokesman** [comment]
Thanks for testing and reviewing Aaron and Marco 🙇
