### PR TITLE
Data: Include more details when shallow equality fails in 'useSelect'

### LINKED ISSUE #63608: Data: Log which keys fail shallow equality when 'useSelect' displays a warning
Source https://github.com/WordPress/gutenberg/pull/53666#issuecomment-2056351807.

> Logging which keys actually fail the shallow equality check would me much more useful. When there are two non-identical objects that contain identical data (e.g., from two calls of a non-memoized selector), looking at them in the console doesn't help, because they look the same.

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
This is a follow-up to #53666.
Closes #63608.

PR updates the warning that's logged when `useSelect` returns different values when run with the same state and parameters. The warning now also includes the keys that fail the check.

## Why?
A quality of life improvement when debugging `useSelect` issues.

## Testing Instructions
1. Open a post or page.
2. Add an example plugin via DevTools.
3. Confirm the notice message.

<details><summary>Test plugin</summary>
<p>

```javascript
const { createElement: el, useState } = wp.element;
const { useSelect } = wp.data;
const registerPlugin = wp.plugins.registerPlugin;
const PluginDocumentSettingPanel = wp.editor.PluginDocumentSettingPanel;

function PluginBlocksOnPage() {
    const { names, total } = useSelect( ( select ) => {
        const blocks = select('core/block-editor').getBlocks();

        return {
            names: blocks.map( ( { name } ) => name ),
            total: blocks.length,
        };
    }, [] );

	return el(
		PluginDocumentSettingPanel,
		{
			className: 'test-blocks-on-page',
			title: `Blocks on Page: ${ total }`,
			name: 'test-blocks-on-page'
		},
		el( 'p', {}, 'Placeholder' )
	);
}

registerPlugin( 'test-blocks-on-page', {
	render: PluginBlocksOnPage,
} );
``` 

</p>
</details> 

### Testing Instructions for Keyboard
Same.

## Screenshots or screencast 
CleanShot 2024-12-08 at 15 44 31

### CODE REVIEW

File: packages/data/src/components/use-select/index.js [hunk 1]
```diff
@@ -19,6 +19,23 @@ import useAsyncMode from '../async-mode-provider/use-async-mode';
 
 const renderQueue = createQueue();
 
+function warnOnUnstableReference( a, b ) {
+	let keys = [];
+	if ( a.constructor === Object && b.constructor === Object ) {
+		keys = Object.keys( a ).filter( ( k ) => a[ k ] !== b[ k ] );
+	} else if ( Array.isArray( a ) && Array.isArray( b ) ) {
+		keys = [ ...a.keys() ].filter( ( i ) => a[ i ] !== b[ i ] );
+	}
```
Comment (jsnajdr) [inline packages/data/src/components/use-select/index.js:25]: `Object.keys` should work equally well also for arrays. The only difference is that `.keys()` returns numbers, while `Object.keys` are strings.

The `a.constructor` check will crash when `a` is `null` or `undefined`, we should guard for that.

**Review by jsnajdr — COMMENTED** [review]
Very nice, I often add similar code locally when debugging something. Happy to see it added permanently.

File: packages/data/src/components/use-select/index.js (hunk 1 above)
Comment (Mamaduka) [reply packages/data/src/components/use-select/index.js:25]: > Object.keys should work equally well also for arrays. The only difference is that .keys() returns numbers, while Object.keys are strings.

Yeah. I should have guessed that 😅 

> The a.constructor check will crash when a is null or undefined, we should guard for that.

I've borrowed the check for `isShallowEqual`, so it should be safe in this case.

Based on your suggestion, I think we can simplify logic to the example below. What do you think?

```js
const keys =
	typeof a === 'object' && typeof b === 'object'
		? Object.keys( a ).filter( ( k ) => a[ k ] !== b[ k ] )
		: [];
```

Comment (jsnajdr) [reply packages/data/src/components/use-select/index.js:25]: > I've borrowed the check for `isShallowEqual`, so it should be safe in this case.

But `isShallowEqual` does an `if ( a && b )` check before it starts looking at `a.constructor`.

> `typeof a === 'object' && typeof b === 'object'`

`typeof null` is also `'object'` 🙀 It will all work only if you exit early when `a` or `b` is falsy.

Comment (Mamaduka) [reply packages/data/src/components/use-select/index.js:25]: I should stop ignoring the "everything is an object" JS motto 😄

Pushed update in [39bc8c1](https://github.com/WordPress/gutenberg/pull/67713/commits/39bc8c1c50fd7566f14207b3251c98fb9f1a43b8).

File: packages/data/src/components/use-select/index.js [hunk 2]
```diff
@@ -19,6 +19,25 @@ import useAsyncMode from '../async-mode-provider/use-async-mode';
...
+			? Object.keys( a ).filter( ( k ) => a[ k ] !== b[ k ] )
+			: [];
+
+	// eslint-disable-next-line no-console
+	console.warn(
+		'The `useSelect` hook returns different values when called with the same state and parameters.\n' +
+			'This can lead to unnecessary re-renders and performance issues if not fixed.\n\n' +
+			'Non-equal value keys: %s\n\n',
+		keys.join( ', ' )
+	);
```
Comment (jsnajdr) [inline packages/data/src/components/use-select/index.js:38]: The warning will be confusing when the `b` object has some field that the `a` object doesn't have. Then it will report an empty list of non-equal keys.

It can happen in practice when we write code like this:
```js
useSelect( select => {
  if ( someCondition ) {
    return { loading: false };
  }
  return { loading: false, data: select( store ).getData() };
} );
```
To fix this, we could construct a set of all fields on both objects and then filter it:
```js
const allKeys = Array.from( new Set( [ ...Object.keys( a ), ...Object.keys( b ) ] ) );
const keys = allKeys.filter( ( k ) => a[ k ] !== b[ k ] );
```
But this will fail again for objects like `{}` and `{ a: undefined }` which are not shallow equal but `keys` will be `[]`.

File: packages/data/src/components/use-select/index.js [hunk 3]
```diff
@@ -19,6 +19,25 @@ import useAsyncMode from '../async-mode-provider/use-async-mode';
 
 const renderQueue = createQueue();
 
+function warnOnUnstableReference( a, b ) {
+	if ( ! a && ! b ) {
```
Comment (jsnajdr) [inline packages/data/src/components/use-select/index.js]: Should be `! a || ! b`.

File: packages/data/src/components/use-select/index.js (hunk 2 above)
Comment (Mamaduka) [reply packages/data/src/components/use-select/index.js:38]: > The warning will be confusing when the b object has some field that the a object doesn't have. Then it will report an empty list of non-equal keys.

It means that the `b` run happened with different state or parameters (mostly params, based on your example). That shouldn't be the case for this warning, as it only makes sense with the same state/params.

**Review by jsnajdr — APPROVED** [review]
Looks good, I don't have any further JavaScript quirks to point out 🙂

File: packages/data/src/components/use-select/index.js (hunk 2 above)
Comment (jsnajdr) [reply packages/data/src/components/use-select/index.js:38]: Oh that's true, I've been overthinking it 🙂 Running the `mapSelect` callback twice with the same state shouldn't produce objects like this unless you're doing it on purpose.

**Comment by Mamaduka** [comment]
@jsnajdr, as always, thank you for the thoughtful review.

**Comment by tyxla** [comment]
This is really useful, thank you @Mamaduka 🙌 

Also, thank you both for the discussion on handling language subtleties - it is always useful and a pleasure to read!

**Comment by Mamaduka** [comment]
I'm considering exposing this warning to third-party consumers when the `SCRIPT_DEBUG` is enabled. What do you think?

cc @gziolo

**Comment by gziolo** [comment]
> I'm considering exposing this warning to third-party consumers when the SCRIPT_DEBUG is enabled. What do you think?

Discussed also on WordPress Slack [here](https://wordpress.slack.com/archives/C015GUFFC00/p1733741592121719). It sounds like a great idea to me. For me, `if ( globalThis.SCRIPT_DEBUG ) {` is the best way to go whenever we want to present debug information for developers.
