### PR TITLE
Avoid usage of unguarded getRangeAt and add eslint rule

### LINKED ISSUE #15606: Components: Avoid unguarded getRangeAt (Autocomplete)
Previously: #11457, #15576, #11209

Safari will throw errors when attempting to call [`Selection#getRangeAt`](https://developer.mozilla.org/en-US/docs/Web/API/Selection/getRangeAt) when there are no ranges in the selection. This has resulted in block errors on multiple occasions in the past (#11209, #15576).

**Tasks:**

- [ ] Update all outstanding unguarded references to `Selection#getRangeAt` to be guarded.
   1. https://github.com/WordPress/gutenberg/pull/15576#issuecomment-491924504
- [ ] Consider an ESLint rule or other programmatic enforcement which might help avoid regressions in the future.
   - Proposed implementation at:
      - https://github.com/WordPress/gutenberg/pull/15576#issuecomment-491928130
      - https://astexplorer.net/#/gist/26984b64750ba301178a38680fbce17f/66c7af6eb40fa09446d81d33f4adf3697eb13b47

### PR DESCRIPTION
**Pull request by bor0**
## Description

Closes #15606.

This PR addresses #15606. I ran a grep through all `getRangeAt` calls and fixed all occurrences. It also adds a new eslint rule.

## Types of changes
The PR introduces a Bug fix (non-breaking change which fixes an issue), and also adds a rule 
enforcement to avoid similar problems in the future

### CODE REVIEW

File: packages/eslint-plugin/configs/custom.js [hunk 1]
```diff
@@ -8,6 +8,7 @@ module.exports = {
 		'@wordpress/no-unused-vars-before-return': 'error',
 		'@wordpress/valid-sprintf': 'error',
 		'@wordpress/no-base-control-with-label-without-id': 'error',
+		'@wordpress/avoid-unguarded-getrangeat': 'error',
```
Comment (aduth) [inline packages/eslint-plugin/configs/custom.js]: I wonder if it should be written as `get-range-at`, rather than `getrangeat`, since the camelCase casing would imply that it's in-fact three words in its expanded form ("get range at").

Lodash, for example, would convert this with its `kebabCase` function:

```
_.kebabCase( 'getRangeAt' );
// 'get-range-at'
```

**Review by aduth — COMMENTED** [review]
Thanks for this proposal!

Each custom ESLint rule should have its own documentation:

https://github.com/WordPress/gutenberg/tree/master/packages/eslint-plugin/docs/rules

It should also be included in the "Rules" tab of the `README.md` file:

https://github.com/WordPress/gutenberg/tree/master/packages/eslint-plugin#rules

It's a fairly targeted rule, which makes me wonder if it's the sort of thing where we could generalize the guarding. That said, it's a pretty specific issue with this one function affecting some browsers  and not others. I guess we'd really only care to revise it if there were other range functions which are similarly problematic when unguarded.

**Comment by bor0** [comment]
Thanks @aduth, I updated the PR.

**Review by aduth — APPROVED** [review]
Looks great, thanks! 👍

**Comment by aduth** [comment]
Some last-minute thoughts / feedback:

- We should include a CHANGELOG entry detailing the rule being added (done in afc18a4).
- I considered (and pushed in 2bf8129) that we name this as "no-" prefixed, rather than "avoid-", since we already have a fair number of theses "avoidance" rules which are consistently named as such. Let me know if you have any thoughts on this.

I was also wondering about the developer experience for someone who encounters this warning. Will it be obvious what they need to do to resolve the issue, when the message is simply "Avoid unguarded getRangeAt" ? I wonder if we could expand the message and/or implement a [fixer](https://eslint.org/docs/developer-guide/working-with-rules#applying-fixes) (depending on difficulty).

It still looks good in its current form, and we could merge it as-is if you're okay with the proposed changes.

**Comment by youknowriad** [comment]
Can we unblock this.  It it seems readyish. Just need a refresh/rebase.

**Comment by bor0** [comment]
Conflicts resolved, thanks!
