### PR TITLE
Raw handling: Fix strikethrough formatting when copy/pasting from Google Docs in Safari

### LINKED ISSUE #15805: Pasted text with strikethrough formatting not being tested properly
**Describe the bug**
During execution of the 'google-docs' and 'google-docs-with-comments' tests, text formatted with `text-decoration: line-through` is not wrapped in an `s` tag. The `s` tag is actually missing in both expected-output files, so the tests pass. Everything works as expected in the block editor, however.

I came across this issue while fixing #15590 ('Underline formatting is removed on paste') and trying to add a test for it (`u` tags are not created either).

See also #11207.

**To reproduce**
1. Go to `test/integration/fixtures/google-docs-out` and `test/integration/fixtures/google-docs-with-comments-out`.
2. Change `strikethrough` to `<s>strikethrough</s>` in each file and save the files.
3. Run `npm run test blocks-raw-handling`.
4. The 'google-docs' and 'google-docs-with-comments' tests fail.

**Expected behavior**
These tests should correctly expect an `s` tag to be produced. Further, this tag should be produced during test execution for text formatted with `text-decoration: line-through` just as it is produced in the editor.

Possible fix: The tags are properly created during test execution if `textDecorationLine` is changed to `textDecoration` in `phrasing-content-reducer.js`. I'm not sure why this fixes the issue but I am happy to look further into it. 

**Desktop**
 - OS: Windows 10 & Ubuntu 16.04
 - Browser: Chrome 74

### PR DESCRIPTION
**Pull request by noisysocks**
Fixes https://github.com/WordPress/gutenberg/issues/15805.

Copy and pasting text that has strikethrough formatting from Google Docs into Gutenberg was not working in Safari or in JSDOM. 

This is because there's a difference in how browsers set `textDecorationLine`:

```js
const span = document.createElement( 'span' );
span.setAttribute( 'text-decoration: line-through' );
console.log( span.style.textDecorationLine );
```

In Chrome, the output is `'line-through'`. In Safari and JSDOM, the output is `''`.

Since the markup generated by Google Docs sets only `text-decoration` and none of the other `text-decoraton-*` attributes, my fix is to change the raw handler to look at `.textDecoration` instead of `.textDecorationLine`.

#### How to test

Using Safari:

1. Copy some text from Google Docs that includes strikethrough formatting.
2. Create a new post using Gutenberg and add a paragraph block.
3. Paste what you copied.

The strikethrough formatting should remain.

### CODE REVIEW

File: packages/blocks/src/api/raw-handling/phrasing-content-reducer.js [hunk 1]
```diff
@@ -22,7 +22,7 @@ export default function( node, doc ) {
 			wrap( doc.createElement( 'em' ), node );
 		}
 
-		if ( textDecorationLine === 'line-through' ) {
+		if ( textDecoration === 'line-through' ) {
```
Comment (epiqueras) [inline packages/blocks/src/api/raw-handling/phrasing-content-reducer.js]: Why not check against both? What if this introduces a regression with other tools/browsers?

Comment (ellatrix) [reply packages/blocks/src/api/raw-handling/phrasing-content-reducer.js]: I guess if we check a more general property we should check if the string contains `line-through`. In any case, if `textDecorationLine` doesn't work in some browsers, we should leave a comment here.

Comment (noisysocks) [reply packages/blocks/src/api/raw-handling/phrasing-content-reducer.js]: Updated this to check both attributes, check `textDecoration` using `includes()`, and added a comment.

**Review by ellatrix — APPROVED** [review]

File: packages/blocks/src/api/raw-handling/phrasing-content-reducer.js [hunk 2]
```diff
@@ -22,7 +28,10 @@ export default function( node, doc ) {
 			wrap( doc.createElement( 'em' ), node );
 		}
 
-		if ( textDecorationLine === 'line-through' ) {
+		// Some DOM implementations (Safari, JSDom) don't support
+		// style.textDecorationLine, so we check style.textDecoration as a
+		// fallback.
+		if ( textDecorationLine === 'line-through' || includes( textDecoration, 'line-through' ) ) {
```
[the remark this answers is not in the document]
Comment (noisysocks) [reply packages/blocks/src/api/raw-handling/phrasing-content-reducer.js]: I get where you're coming from but I don't really want to stray into the territory of implementing a CSS parser here. This simple check is correct because, like you say, the only scenario in which `text-decoration` would contain the substring `'line-through'` is iff `text-decoration-line` is `'line-through'`.
