### PR TITLE
Popover: smoothly reposition on scroll

### LINKED ISSUE #16643: Block's Options popover extends off screen and items are inaccessible
**Describe the bug**
This has happened to me on more than one occasion. I'll add a block to the bottom of the document, but then decide to delete it. When I click the block's toolbar options, the popover appears, but I can't access the lower options. The popover extends off the screen. I try to scroll to see more, but that doesn't work.

**To reproduce**
1. Add some blocks to your document.
2. On the last block toward the bottom of the screen, add a block that is not the same height as the block popover.
3. Click into the block's popover to try and delete the block.
4. Observe that the popover extends below the bottom of the document and the last options can't be accessed.

**Expected behavior**
When at the bottom of the document, the popover should pop upward instead of downward.

**Screenshots**

**Example 1**

cant-see-all

**Example 2**

Screen Shot 2019-07-17 at 12 57 43 PM

**Desktop (please complete the following information):**
 - OSX
 - Firefox 68.0
 - Gutenberg 6.1

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #16643.
Blocks #18779.

This PR refactors the `Popover` component so that it smoothly repositions on scroll. Currently we do have logic to reposition it for every scroll frame, but the `Popover` is always rerendered too late (and thus the style attributes reset too late). Why is that? Because currently we set it with React state, which then rerenders the component. Since this is not done synchronously, there's a small delay.

The only way we can fix this is by avoiding setting state. Instead, we should update the DOM immediately. This is also more performant. There's no way around the DOM, unfortunately.

As a result, I think the component has also become simpler. There's no need for the many nested hooks and passing around props. I also swapped out the `is-*` classes in favour of `data-` attributes, which are much easier to update.

## How has this been tested?

Open some popovers and play with scrolling and resizing. Nothing else should be different from `master`.

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
Are you sure you couldn't just use `useLayoutEffect`?

> The signature is identical to useEffect, but it fires synchronously after all DOM mutations. Use this to read layout from the DOM and synchronously re-render. Updates scheduled inside useLayoutEffect will be flushed synchronously, before the browser has a chance to paint.

https://reactjs.org/docs/hooks-reference.html#useref

**Comment by ellatrix** [comment]
@ZebulanStanphill How would you use that for a `scroll` callback? It doesn't fire in that case, it only fires when any props change. In other words, there is no re-render happening, and I'm not sure how you _trigger_ a synchronous render.

**Comment by ZebulanStanphill** [comment]
@ellatrix Good point. I didn't think that through enough.

**Comment by ZebulanStanphill** [comment]
The animation when opening the block <kbd><samp>More options</samp></kbd> or the <kbd><samp>More tools & options</samp></kbd> popovers is gone.

**Comment by ellatrix** [comment]
@ZebulanStanphill I don’t see the animation in master either.

**Comment by youknowriad** [comment]
@ellatrix I didn't test this branch but in master I do see the animation (make sure you're not in prefers reduced mode and the "disable animation" plugin should be disabled)

**Comment by ellatrix** [comment]
@youknowriad Ah, for some reason I had only that test plugin enabled... Strange :)

**Comment by ellatrix** [comment]
@ZebulanStanphill For me the animation works with this branch as well, if you make sure the "disable animation" plugin is disabled.

**Comment by ZebulanStanphill** [comment]
I just checked, and yep, the "Gutenberg Test Plugin, Disables the CSS animations" was enabled. I never enabled it. Is it supposed to be enabled by default when you create a dev environment? (I'm using the `@wordpress/env` environment.)

Anyway, it looks like there are no issues (that I know of) on this branch after all.

**Comment by ellatrix** [comment]
@ZebulanStanphill I have the same issue. The plugin always gets activated for some reason, I suspect by e2e tests? Thank you for testing the PR!

**Review by youknowriad — COMMENTED** [review]
I'm not sure it's specific to this branch but I had an issue on mobile where I can't scroll the Inspector/Document sidebar. I know we fixed something like that recently, so maybe a rebase?

--
I noticed that the popover doesn't reposition properly on resize (mobile)

Capture d’écran 2019-12-04 à 9 12 41 AM

File: packages/components/src/popover/index.js [hunk 1]
```diff
@@ -361,38 +219,109 @@ const Popover = ( {
 } ) => {
 	const anchorRefFallback = useRef( null );
 	const contentRef = useRef( null );
+	const containerRef = useRef();
+	const [ isMobileViewport, setIsMobileViewport ] = useState( false );
```
Comment (youknowriad) [inline packages/components/src/popover/index.js]: This should help here to avoid an Adhoc solution https://github.com/WordPress/gutenberg/pull/18816

File: packages/components/src/popover/index.js [hunk 2]
```diff
@@ -361,38 +219,109 @@ const Popover = ( {
...
+		const intervalHandle = window.setInterval( refresh, 500 );
+		window.addEventListener( 'resize', refresh );
+		window.addEventListener( 'scroll', refresh, true );
+
+		return () => {
+			window.clearInterval( intervalHandle );
+			window.removeEventListener( 'resize', refresh );
+			window.removeEventListener( 'scroll', refresh, true );
+		};
+	} );
```
Comment (youknowriad) [inline packages/components/src/popover/index.js]: Do we want to trigger a refresh on each render?

File: packages/components/src/popover/index.js [hunk 3]
```diff
@@ -451,53 +380,33 @@ const Popover = ( {
...
 	let content = (
 		<PopoverDetectOutside onFocusOutside={ handleOnFocusOutside }>
 			<Animate
-				type={ animate && isReadyToAnimate ? 'appear' : null }
-				options={ { origin: animateYAxis + ' ' + animateXAxis } }
+				type={ animate && animateOrigin ? 'appear' : null }
+				options={ { origin: animateOrigin } }
 			>
 				{ ( { className: animateClassName } ) => (
-					<IsolatedEventContainer
```
Comment (youknowriad) [inline packages/components/src/popover/index.js]: Do you know why we had IsolatedEventContainer and why it's removed now?

**Review by youknowriad — COMMENTED** [review]
@gziolo mentioned https://popper.js.org/ as a great popover lib. I wonder if we could make our Popover component just a wrapper around and avoid the maintainability costs. (It's a separate topic from this PR though)

File: packages/components/src/popover/index.js (hunk 3 above)
Comment (ellatrix) [reply packages/components/src/popover/index.js]: `IsolatedEventContainer` only stops propagation for `mousedown` events, which I added to the `div` element. I'm not sure why propagation needs to be stopped for that event. There was no comment about it. `IsolatedEventContainer` seems a bit like a strange name for this specific behaviour, which should ideally be commented on in this `Popover` component itself.

Comment (youknowriad) [reply packages/components/src/popover/index.js]: I think it's probably @aduth's addition. Pinging him just in case.

Comment (ellatrix) [reply packages/components/src/popover/index.js]: Ok, it looks like the only uses of `IsolatedEventContainer` are `Popover` and `Modal`, and it mentions those, so maybe I should restore it. Too back it creates an extra `div` though.

**Comment by ellatrix** [comment]
@youknowriad I'd love us to have more use cases in Gutenberg for `Popover` before we decide to wrap an external component. There's a few more interesting use cases in #18779.

**Comment by ellatrix** [comment]
@youknowriad I cannot scroll the document sidebar on mobile in `master` either.

File: packages/components/src/popover/index.js (hunk 3 above)
Comment (ellatrix) [reply packages/components/src/popover/index.js]: I restored `IsolatedEventContainer`, rewrote it with hooks, and modified it to forward the DOM ref.

File: packages/components/src/popover/index.js (hunk 2 above)
Comment (ellatrix) [reply packages/components/src/popover/index.js]: I'll add a list of dependencies, but it's pretty much everything :) Still may be worth it to skip the functions.

**Comment by ellatrix** [comment]
> I noticed that the popover doesn't reposition properly on resize (mobile)

This is fixed too.

**Comment by youknowriad** [comment]
This is working well for me. I was hoping it would fix the issue where sometimes the scrollbar in popovers don't appear (you can trigger it inconsistently in the More menu or the block settings menu) but unfortunately, it doesn't, it still happens sometimes. I was curious whether you have an idea why this happens sometimes.

File: packages/components/src/popover/index.js [hunk 4]
```diff
@@ -361,38 +216,122 @@ const Popover = ( {
...
+		return () => {
+			window.clearInterval( intervalHandle );
+			window.removeEventListener( 'resize', refresh );
+			window.removeEventListener( 'scroll', refresh, true );
+		};
+	}, [
+		isMobileViewport,
+		expandOnMobile,
 		contentSize,
+		anchorRefFallback.current,
```
Comment (youknowriad) [inline packages/components/src/popover/index.js]: I'm not certain that adding refs in dependencies is a good practice as changes to these don't rerender anyway.

File: packages/components/src/popover/style.scss [hunk 5]
```diff
@@ -183,6 +183,14 @@ $arrow-size: 8px;
 	height: 100%;
 }
 
+.components-popover {
+	opacity: 0;
+}
+
+.components-popover[data-x-axis][data-y-axis] {
+	opacity: 1;
+}
```
Comment (youknowriad) [inline packages/components/src/popover/style.scss]: I'm not sure I understand why the opacity trick here

Comment (ellatrix) [reply packages/components/src/popover/style.scss]: It's more or less the same as before, where for `master` it's setting `visibility: hidden;` for as long as the position hasn't been calculated. The calculation can only happen when the DOM element has already rendered, but before the calculation happens we don't want the DOM element to show.

Comment (ellatrix) [reply packages/components/src/popover/style.scss]: I'll leave an inline comment.

File: packages/components/src/popover/index.js (hunk 4 above)
Comment (ellatrix) [reply packages/components/src/popover/index.js]: Ah, you're right. I didn't think that through.

**Comment by ellatrix** [comment]
> I was hoping it would fix the issue where sometimes the scrollbar in popovers don't appear (you can trigger it inconsistently in the More menu or the block settings menu) but unfortunately, it doesn't, it still happens sometimes. I was curious whether you have an idea why this happens sometimes.

I see what you mean. Looks like a bug somewhere else in the code, but I'll have a look.

**Comment by youknowriad** [comment]
Capture d’écran 2019-12-04 à 12 16 28 PM

Mmm, I found another little bug here where scrolling the content area don't resize the popover properly (notice that the height of the popover should reach the bottom of the window in the screenshot but t seems stuck.

**Comment by youknowriad** [comment]
so basically, it scales down, but doesn't scale up again.

**Comment by ellatrix** [comment]
@youknowriad I think I fixed both those issues now.

**Comment by youknowriad** [comment]
This is cool. I think there's a small refresh issue still. If you scroll or resize quickly. You'll notice that sometimes the popover is not adjusting its size, sometimes it stops doing so.

Capture d’écran 2019-12-04 à 1 41 25 PM

Notice the scrollbars in the screenshot. I do that by resizing up and down quickly.

**Comment by ellatrix** [comment]
@youknowriad Thank for catching that. It should be fixed now. The problem was that I didn't unset the max height if none was provided (and kept the old one instead).

**Review by youknowriad — APPROVED** [review]
LGTM 👍 

There are some Github issues that will be fixed with this (the scrollbar issues)

**Comment by ellatrix** [comment]
Many thanks for the review, @youknowriad!
