### PR TITLE
Fix importing classic menus

### LINKED ISSUE #52434: Navigation block: importing additional classic menus greyed out after initial import
### Description

After importing an initial classic menu, I'm unable to import or create another with the options visible but greyed out.

### Step-by-step reproduction instructions

To make it faster, you can use  https://app.instawp.io/launch?t=beta-rc&d=v2 which has numerous classic menu options to import and where I initially ran into the bug.

1. Open Site Editor after ensuring you have a few classic menus to import (aka use a classic theme, create a few menus, switch to a block theme).
2. Edit a template.
3. Select the navigation block.
4. Open the block settings sidebar.
5. Try to import a classic menu.
6. Notice you can import one but, if you try to do so again, the options are greyed out.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/26996883/f7bbb36d-e43b-42ad-85dd-65c7f99b5d00

### Environment info

- WP 6.3 beta 3
- TT3
- No GB

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by draganescu**
## What?

Fixes [#52434](https://github.com/WordPress/gutenberg/issues/52434)

## Why?

Because one could not import multiple classic menus in a row.

## How?

Reuses the same creation function from the original `useCreateNavigationMenu` hook instead of instancing a new one. This way the statuses are shared both when creating new menus and when importing then creating new menus.

## Testing Instructions

1. Open Site Editor after ensuring you have a few classic menus to import (aka use a classic theme, create a few menus, switch to a block theme).
2. Edit a template.
3. Select the navigation block.
4. Open the block settings sidebar.
5. Try to import a classic menu.
6. It should import fine and all the others are as well ready to import
7. Create a new menu
8. Use the selector
9. All options are available

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/107534/340667b4-3c47-4c43-8a95-23480c32fab6

### CODE REVIEW

File: packages/block-library/src/navigation/edit/use-convert-classic-menu-to-block-menu.js [hunk 1]
```diff
@@ -21,15 +20,7 @@ export const CLASSIC_MENU_CONVERSION_IDLE = 'idle';
...
-function useConvertClassicToBlockMenu( clientId ) {
-	/*
-	 * The wp_navigation post is created as a draft so the changes on the frontend and
-	 * the site editor are not permanent without a save interaction done by the user.
-	 */
-	const { create: createNavigationMenu } = useCreateNavigationMenu(
-		clientId,
-		'draft'
-	);
+function useConvertClassicToBlockMenu( clientId, createNavigationMenu ) {
```
Comment (getdave) [inline packages/block-library/src/navigation/edit/use-convert-classic-menu-to-block-menu.js]: `clientId` is now unused?
```suggestion
function useConvertClassicToBlockMenu( createNavigationMenu ) {
```

You'd need to amend all calls to the hook.

Comment (getdave) [reply packages/block-library/src/navigation/edit/use-convert-classic-menu-to-block-menu.js]: I've gone ahead and actioned this for you.

**Review by getdave — APPROVED** [review]
I've tested this and it solves the problem at hand. Thanks!

What I don't like this the way we're having to pass in the `createNavigation` handler from another hook.

What this all points to is that the following should be part of Core Data (or [a new `@wordpress/navigation` package](https://github.com/WordPress/gutenberg/pull/52134)):

- createNavigation
- convertClassic

By moving these to global state we can safety make calls and know that the same resolution state will be applicable to _all_ instances. This will avoid future bugs and avoid us playing callback tennis across various hooks.

As these are Core-like actions I think this is more than acceptable.

Do you agree? If so I will create a followup Issue (or you can).

**Comment by getdave** [comment]
@draganescu I found [this bug](https://github.com/WordPress/gutenberg/pull/52591) when reviewing this PR. Would be grateful for a review there 🙇

**Review by scruffian — APPROVED** [review]
LGTM

**Comment by scruffian** [comment]
I created a followup here: https://github.com/WordPress/gutenberg/issues/52596

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the update/first-batch-pre-RC1 branch to get it included in the next release: 95363abd83
