### PR TITLE
Fix pasting content into inner blocks

### LINKED ISSUE #16645: Pasting text into columns isn't showing up on frontend
**Describe the bug**
I'm trying to paste test into the Column block, but that text isn't showing on the frontend. It only shows up if I make a change to the color, size, or another attribute first, then it shows.

**To reproduce**
1. Add Columns block.
2. Copy and paste text from another website into each of the columns.
3. Save the document and preview it.
4. Observe that the text isn't showing on the frontend.

**Expected behavior**
I expect that the text shows without having to change any attributes of it. In the screencast below, I've already copied the text in the Columns block. I've made an attribute change to the text in the first columns making a line bold. But the other two columns I haven't touched. When I check the preview, the two columns of text don't show.

**Screenshots**

columns

**Desktop (please complete the following information):**
 - OSX
 - Firefox 68.0
 - Gutenberg 6.1

### PR DESCRIPTION
**Pull request by talldan**
Fixes #16645

## Description

Resolves an issue where content pasted into inner blocks is not saved correctly.

The issue was caused by a small caching error introduced in https://github.com/WordPress/gutenberg/pull/16407. 

When pasting content into an empty paragraph, a block replacement is triggered. When this action was being carried out in an inner block, cached parent blocks were not being invalidated.

This is the code that attempts to invalidate parents of a replaced block:
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/store/reducer.js#L269-L271

The issue is that `getBlocksWithParentsClientIds` is called with the incorrect clientId. `getBlocksWithParentsClientIds` operates on the old state rather than the new state, so it needs to be called with the block that's about to be removed rather than the block that's about to be added: https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/store/reducer.js#L228-L237

This PR resolves the issue.

## How has this been tested?
Updated the relevant unit test to ensure the parent block is invalidated.

Manual testing:
1. Add Columns block.
2. Copy and paste text from another website into each of the columns.
3. Save the document and preview it.
4. Observe that the text isn't showing on the frontend.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/block-editor/src/store/reducer.js [hunk 1]
```diff
@@ -264,11 +275,12 @@ const withBlockCache = ( reducer ) => ( state = {}, action ) => {
...
 		case 'REPLACE_BLOCKS_AUGMENTED_WITH_CHILDREN':
+			const parentClientIds = fillKeysWithEmptyObject( getBlocksWithParentsClientIds( action.replacedClientIds ) );
+
 			newState.cache = {
 				...omit( newState.cache, action.replacedClientIds ),
-				...fillKeysWithEmptyObject(
-					getBlocksWithParentsClientIds( keys( flattenBlocks( action.blocks ) ) ),
-				),
+				...omit( parentClientIds, action.replacedClientIds ),
+				...fillKeysWithEmptyObject( keys( flattenBlocks( action.blocks ) ) ),
```
Comment (talldan) [inline packages/block-editor/src/store/reducer.js]: To explain a bit what I've done here:
1. The `replacedClientIds` needs to be used to find parentClientIds, but then that clientId needs to be omitted, hence the second call to `omit` here.
2. The new clientId needs to be included in the cache, and there's a unit test `should replace the block even if the new block clientId is the same`, so that's why it's the last item is adding the new client id.

**Review by tellthemachines — APPROVED** [review]
Tested with columns and nested columns, by pasting content in, saving and previewing, and it's working fine. 
Code looks good, thanks for documenting everything so thoroughly! 
A thought about the reducer unit tests in general: I wonder if we shouldn't be more granular with what we're testing. There's a huge amount of assertions inside some of those tests, so if they fail, it's not immediately obvious why. E.g. should we have a test to check caching in block replacement, instead of having that check be part of the block replacement test?

File: packages/block-editor/src/store/reducer.js (hunk 1 above)
Comment (youknowriad) [reply packages/block-editor/src/store/reducer.js]: The logic seems good to me.
