### PR TITLE
Navigation: Avoid content loss when only specific entity fields are edited

### LINKED ISSUE #59991: Site Editor: renaming a navigation menu resets its content
Steps to reproduce:
1. In the Site Editor, go to the Navigation page
2. Verify there is a a navigation item there, and its content is a Page List block, showing the list site's pages.
3. In the navigation's context menu, select Rename
4. Rename the navigation

Result: the navigation is not only renamed, but its content is also reset to empty string (`''`).

Here is a video:

https://github.com/WordPress/gutenberg/assets/664258/b76ed45d-afd7-46ce-9e7a-ac73f6741f9b

Note that the "Sample Page" item (it's part of the Page List block) has disappeared after the rename.

The REST request to rename looks like this:

Screenshot 2024-03-19 at 13 40 21

and this is the response:

Screenshot 2024-03-19 at 13 41 53

Note that not only the `title` field has changed, but also the `content` has been reset.

@tellthemachines Maybe there is something wrong with the `WP_Navigation_Fallback` class in Core? If I understand it correctly, `wp_navigation` is just another custom post type, and its REST requests are handled by the vanilla `posts` controller. Editing individual fields should work without resetting the others. It's only `WP_Navigation_Fallback` that patches the schema somehow, including the `content.*` fields.

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Fixes #59991.

PR fixes the Navigation block content loss when renaming them in the Site Editor. It also fixes PHP warnings when post content isn't set.

```
PHP Warning: Undefined property: stdClass::$post_content in ~/gutenberg/wp-content/plugins/gutenberg/build/block-library/blocks/navigation.php on line 1527

PHP Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in ~/gutenberg/wp-includes/class-wp-block-parser.php on line 252

PHP Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in ~/gutenberg/wp-includes/class-wp-block-parser.php on line 324
```

## Why?
The entities can choose to update only specific fields (See `__experimentalSaveSpecifiedEntityEdits`) via REST API, and the prepared entity update will only contain those properties.

## How?
Bail early when post content isn't set for the prepared update.

## Testing Instructions
1. Open the Site Editor.
2. Navigate to Design > Navigation.
3. Pick any navigation.
4. Click on "Actions" and rename it.
5. Confirm that navigation block content stays intact after renaming.

### Testing Instructions for Keyboard
Same.

### CODE REVIEW

File: packages/block-library/src/navigation/index.php [hunk 1]
```diff
@@ -1520,6 +1520,14 @@ function block_core_navigation_update_ignore_hooked_blocks_meta( $post ) {
 		return $post;
 	}
 
+	/**
+	 * Skip meta generation when consumers intentionally update specific Navigation fields
+	 * and omit the content update.
+	 */
+	if ( ! isset( $post->post_content ) ) {
+		return $post;
+	}
```
Comment (Mamaduka) [inline packages/block-library/src/navigation/index.php:1529]: Do we still want to generate meta when the requests skip content updates?

Comment (jsnajdr) [reply packages/block-library/src/navigation/index.php:1529]: If I understand this correctly, the hook looks at `post_content` and calculates some derived values from it. The `_wp_ignored_hooked_blocks` post meta, and it also modifies the `post_content` itself.

If the REST request doesn't modify `post_content`, the existing values are OK and the hook doesn't need to do anything.

I'm more curious about the `if ( empty( $post->ID ) )`. If I'm creating a `wp_navigation` by POST-ing to the endpoint and not specifying an ID, who will update the `_wp_ignored_hooked_blocks` and the `post_content`? It seems like it will be skipped, although it shouldn't be.

Comment (Mamaduka) [reply packages/block-library/src/navigation/index.php:1529]: That is correct. We could also use the `if ( empty( $post->post_content ) ))` check; it would also cover the case when the post content is set but empty, and the hook doesn't need to do anything.

Unfortunately, I'm not very familiar with the internals of Block Hooks API. @ockham and @tjcafferkey can provide more details.

The `$post->ID` check was introduced in #59875.

**Review by jsnajdr — APPROVED** [review]
This fixes the bug for me, but I must apply the patch to the Core files (`wp-includes/blocks/navigation.php`), because the Gutenberg plugin adds the filter only if your Core is old and hasn't added it already.

Should be a backport to 6.5 RC

File: packages/block-library/src/navigation/index.php (hunk 1 above)
Comment (jsnajdr) [reply packages/block-library/src/navigation/index.php:1529]: `empty()` is bad, because it would miss the cases where the `post_content` is legitimately changed to an empty string. `isset()` is better.

> The $post->ID check was introduced in https://github.com/WordPress/gutenberg/pull/59875.

Ideally the `post_content` should be modified in the `rest_pre_insert` hook and the post meta updated in the `rest_insert` hook.

Because `rest_pre_insert` hook runs before the post was inserted/updated in the database, and the `$post` argument is only the partial post with fields specified in the request. It's a `stdClass`, not `WP_Post`. It might not have an ID yet. And you want to modify the `post_content` before it's written into the database, instead of having to write it twice.

`rest_insert` sees the real `WP_Post` as `$post`, it's the one read from the database and it always has an ID. It's a good place where to update the post meta.

I believe the fix in #59875 is not 100% correct. The code needs the `$post->ID` only to read the existing `ignored_hooked_blocks` meta and then write it into a Navigation block attribute in the serialized `post_content`. But when a `wp_navigation` is freshly created, there is no existing meta.

The current code will fail to set the `ignored_hooked_blocks` meta when the "create" request has a `post_content` where the root nav block has a `$root_nav_block['attrs']['metadata']['ignoredHookedBlocks']` value.

**Comment by getdave** [comment]
> but I must apply the patch to the Core files (wp-includes/blocks/navigation.php

Noting that this file will be automatically synced to WP Core as part of the packages release process _if_ this PR is picked for inclusion in the release. So you shouldn't need to do any manual backports.

File: packages/block-library/src/navigation/index.php (hunk 1 above)
Comment (tjcafferkey) [reply packages/block-library/src/navigation/index.php:1529]: Thanks both. You are right @jsnajdr in saying this.

>The current code will fail to set the ignored_hooked_blocks meta when the "create" request has a post_content where the root nav block has a $root_nav_block['attrs']['metadata']['ignoredHookedBlocks'] value.

The fix in https://github.com/WordPress/gutenberg/pull/59875 was accepted to cover a fatal error happening in what we considered to be an edge-case. It's not 'ideal', and I'm sure there's a solution in what you mentioned above. Unfortunately time was not on our side when this was reported and considered it more important to fix the error.

I'm going to create a follow-up issue to look into a better solution.

cc @ockham incase I've misspoken or there's something further to add 😅

Comment (tjcafferkey) [reply packages/block-library/src/navigation/index.php:1529]: Just to add to this.

>when the "create" request has a post_content where the root nav block has a $root_nav_block['attrs']['metadata']['ignoredHookedBlocks'] value.

We will never get this data in the request since the Navigation block (which contains the metadata) and its inner blocks are detached, the POST request would only contain inner block data.

In the function above we have to mock the Navigation block in order to generate the necessary meta data to save. We do this because we assume the incoming $post data is coming from the Site Editor where the Block Hooks algorithm has already run when preparing the response for the Editor to insert the hooked blocks.

Still, a follow-up issue should be created to look if there's a better solution to tackle the side effect detailed in the description of https://github.com/WordPress/gutenberg/pull/59875.

Comment (ockham) [reply packages/block-library/src/navigation/index.php:1529]: My apologies, I've only seen this now, since I wasn't working on Friday.

Anyway, thanks a lot @jsnajdr for reporting #59991, @Mamaduka for this fix, and @tjcafferkey for the follow-up clarification!

I think your reasoning about the issue is spot-on, as is the fix. I'll try to address some of the concerns that Jarda raised about #59875:

https://github.com/WordPress/gutenberg/pull/60071/files#r1533833240:
> I'm more curious about the `if ( empty( $post->ID ) )`. If I'm creating a `wp_navigation` by POST-ing to the endpoint and not specifying an ID, who will update the `_wp_ignored_hooked_blocks` and the `post_content`? It seems like it will be skipped, although it shouldn't be.

This was covered by Tom in the PR description of #59875:

> A known side effect of this means that the next time this navigation is loaded (if the user is creating it via the REST API outside of the site editor), if it has any anchor blocks it will proceed to insert the hooked blocks since we won't have run the ignored hooked blocks logic for reasons mentioned above. Whether this is a 'bug' or not I think is still a bit of a grey area but given that I believe this is an edge case I think its acceptable until we decide a better course of action.

---

https://github.com/WordPress/gutenberg/pull/60071/files#r1535417586:
> Ideally the `post_content` should be modified in the `rest_pre_insert` hook and the post meta updated in the `rest_insert` hook.
>
> Because `rest_pre_insert` hook runs before the post was inserted/updated in the database, and the `$post` argument is only the partial post with fields specified in the request. It's a `stdClass`, not `WP_Post`. It might not have an ID yet. And you want to modify the `post_content` before it's written into the database, instead of having to write it twice.

Yes, that's something we learned the hard way (as writing twice even causes an [issue](https://github.com/WordPress/gutenberg/issues/59516) with encoding): https://github.com/WordPress/gutenberg/pull/59561.

<details>
<summary>
Aside, with some background.
</summary>

What makes things even trickier is that the mechanism that injects Block Hooks (and the related `ignoredHookedBlocks` metadata) includes some filters that receive a `$context` argument that reflects the containing `wp_navigation` post object, or the containing `WP_Block_Template`. This allows filters to conditionally enable or disable insertion of a given hooked block depending on some properties of that `$context`; e.g. they might check if the `$context` is a single template, a header template part. However, they might also check for the presence of a block in the content of the template/part/navigation object. In the latter case, we'd want `$context` to reflect the updated content (coming in from the REST API as part of the `stdClass` object you mentioned), rather than whatever's already stored in the DB. For templates and template parts (where the `ignoredHookedBlocks` metadata is stored as an attribute on individual blocks rather than in post meta), this has lead to a fairly complex solution where we emulate what the updated post object will look like after it's been inserted into the DB by merging the `stdClass` on top of the existing `WP_Post` object: https://github.com/WordPress/wordpress-develop/pull/6278.

Note that this is _only_ a problem for the filter `$context`; the actual insertion of hooked blocks (and of the `ignoredHookedBlocks` metadata attribute, in case of templates and template parts) is always performed on the `stdClass` object's `content`.
</details>

---

> `rest_insert` sees the real `WP_Post` as `$post`, it's the one read from the database and it always has an ID. It's a good place where to update the post meta.

This would however require us to communicate a bunch of data computed in `rest_pre_insert` to `rest_insert`, or to recompute that data. My alternative suggestion would be to use the `meta_input` field on the `stdClass` object (which is used to communicate that the post meta for the post object should be updated).

**Comment by ockham** [comment]
@tjcafferkey We should probably add some unit test coverage for this (akin to [this](https://github.com/WordPress/gutenberg/pull/59875/files#diff-b092b45c0a871e56f45b19ec417f810d4e93d97d5808d5a8893bdfcde4db32d1R95-R124), but with a pre-existing DB object, and with `$changes->post_content` unset (and probably some other field set instead, to make sure a DB update _is_ performed)).

**Comment by getdave** [comment]
It would be helpful if we did have test coverage for this. It may also aid in being able to land in WP 6.5.

**Comment by getdave** [comment]
This PR was triaged by Editor release leads and contributors in WP Slack as part of the final WordPress 6.5 process.

See https://wordpress.slack.com/archives/C02QB2JS7/p1711369267337079 (requires registration).

The criteria used was:

- Was this bug identified during the RC cycle for WP 6.5?
- Is this bug directly related to one of the blessed features in this release?
- Would this bug cause existing website’s to break/fail upon upgrade to WP 6.5?
- What is the approximate scope of the impact? Scale: (Minimal) 1 - 5 (Severe).
- Is the fix introducing any new features or changes?


**Conclusion**: we propose that this fix _is_ included in WP 6.5. 

**Reason**: Content loss for users.

We now await decision on this from the full release team.

**Comment by ockham** [comment]
> It would be helpful if we did have test coverage for this. It may also aid in being able to land in WP 6.5.

I'm working on one now 👍

**Comment by ockham** [comment]
> > It would be helpful if we did have test coverage for this. It may also aid in being able to land in WP 6.5.
> 
> I'm working on one now 👍

https://github.com/WordPress/gutenberg/pull/60189

**Comment by bph** [comment]
I just cherry-picked this PR to the release/18.0 branch to get it included in the next release: 96ffcf1ec5

File: packages/block-library/src/navigation/index.php [hunk 2]
```diff
@@ -1520,6 +1520,14 @@ function block_core_navigation_update_ignore_hooked_blocks_meta( $post ) {
 		return $post;
 	}
 
+	/**
+	 * Skip meta generation when consumers intentionally update specific Navigation fields
+	 * and omit the content update.
+	 */
+	if ( ! isset( $post->post_content ) ) {
```
Comment (getdave) [inline packages/block-library/src/navigation/index.php:1527]: Noting that this is `stdClass` because it’s hooked to https://developer.wordpress.org/reference/hooks/rest_pre_insert_this-post_type/.

**Comment by getdave** [comment]
I just cherry picked this into WP 6.5 RC 4 branch https://github.com/WordPress/gutenberg/pull/60241/commits/89f4782d361289a13e6a2f8841b72335c75442e4
