### PR TITLE
Fixes block highlight after block move

### LINKED ISSUE #28742: Persistent focus outline after moving a block
## Description

When moving a block there is an outline that appears around the moved block. The problem is that the outline does not disappear when another block is selected.

## Step-by-step reproduction instructions

0. Have the current (Feb 4th 2021) Gutenberg master running.
1. Add a post and add some blocks.
2. Select one block and move it using the movers in the block toolbar.
3. Select another block.
4. Notice the persistent selection outline on the previously moved block.

## Expected behaviour

The selection outline should always follow the current focus.

## Actual behaviour

The selection outline remained on an unfocused block.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/107534/106916093-7892f780-670f-11eb-8262-52890fc020e8.mp4

## WordPress information
- WordPress version: Trunk
- Gutenberg version: Master
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: OSX
- Browser: Firefox latest

### PR DESCRIPTION
**Pull request by draganescu**
Closes #28742

Seems the bug was simply a missed call to a `toggleBlockHighlight`, otherwise a quick fix. I hope I am not missing something, but manual testing shows the bug gone:

https://user-images.githubusercontent.com/107534/154722958-2f9aa57d-bb69-440f-90c3-27c8fe4c662a.mp4

### CODE REVIEW

**Review by getdave — DISMISSED** [review]
https://user-images.githubusercontent.com/444434/154728797-72a636e6-8052-492c-9195-6d9f8cd6370a.mov

I tested the reported issue and was able to verify that this PR fixes it.

It does look very much like it was an accidental omission. 

I was wondering about suggesting some test coverage for this but it might be OTT. What do you think?

File: packages/block-editor/src/components/block-toolbar/utils.js [hunk 1]
```diff
@@ -127,13 +136,15 @@ export function useShowMoversGestures( {
 		const handleOnFocus = () => {
 			if ( isFocusedWithin() ) {
 				setIsFocused( true );
+				toggleBlockHighlight( clientId, true );
```
Comment (talldan) [inline packages/block-editor/src/components/block-toolbar/utils.js]: @draganescu `toggleBlockHighlight` is already called as part of `useShowMoversGestures` here - https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-parent-selector/index.js#L66.

There's probably an issue that prevents `toggleBlockHighight` from being called with `false`, either with the `if` statement here:
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-parent-selector/index.js#L63

or here:
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-toolbar/utils.js#L79

**Review by talldan — DISMISSED** [review]
Sorry to interject! I was curious about `useShowMoversGestures` so had a look at the code and noticed there's some existing code that's supposed to call `toggleBlockHighlight` (see the comment).

It looks like this PR duplicates that rather than fixing the original bug.

It'd be good to try to either remove those duplicate calls to `toggleBlockHighlight` in favour of the ones you've added here. Or do the opposite, fix the issue with the existing code.

**Comment by getdave** [comment]
Thanks for spotting @talldan. That will teach me to review things last thing on a Friday 🧠

**Comment by draganescu** [comment]
> Sorry to interject! 

Good interjection. That puzzled me as well. I will continue to look into this.

**Comment by draganescu** [comment]
So I've investigated this and in the middle of that found that on mobile where top toolbar is forced the highlight is even more erratic. 

After debugging on desktop, I found that when the blur event fired the onChange method that controls the highlight was never called. Turns out that the cleanup function declared in `useDebouncedShowMovers` clears out the timeout which would trigger the effect. On blur the block toolbar component is remounted and so the change that would hide the highlight is never fired.

Also the `debouncedShowMovers` and `debouncedHideMovers` in the blur/focus handlers seem to be pointless as we change state and hence render again.

It is unclear what is the harm of removing that cleanup function, but I opted to just call the change handler with `isFocused` set to false as on cleanup the block has definitely been unfocused.

On mobile with forced top toolbar the selection is highly erratic. I'd suggest we merge this and fix that separately, as the problem there is that our logic effectively assumes a mouse (e.g. checking for block hover). I think the solution for mobile is to refactor our logic to learn from a store which block should have the selection outline. 

Currently on mobile the outline when the keyboard opens the selection is hidden. With a few tries I even managed get two selection boxes.

**Comment by talldan** [comment]
The code in `trunk` is really hard to understand, so it's a tough job to review this! I think it's missing a bunch of important inline documentation. I guess the goal of the `debounce` is to avoid the flicker of showing and hiding and then showing the highlight again when switching hover/focus between the buttons. This should have been documented, as now I'm left wondering why it was done this way 😄 

Anyway, I'm pretty happy with the call to `handleOnChange` on unmount. But I think there's a regression in that the block highlight no longer shows when the toolbar is focused via the keyboard (shift-tab to the block toolbar from the block to reproduce this). That seems related to the two lines that were removed. Do they need to be removed?

Also, let's add some inline documentation around the new code added to explain the motive.

**Comment by draganescu** [comment]
Cool @talldan great catch with the keyboard focus, reading the code it does seem those calls are pointless. Anyway, for now we have a good desktop fix. I'll follow up with some approach for mobile, and possibly try to make things more readable. I'd love to have this fix on desktop as it is really small and seems to be correct as an approach.

Added a comment to explain why we call the change handler.

**Review by scruffian — APPROVED** [review]
I can confirm that this fixes the issue. I don't understand the code well enough to say why :)

**Comment by talldan** [comment]
Thanks for adding those keyboard event handlers back. Looks good now, let's get this in.
