### PR TITLE
Global Style Context: Consider global user styles ready if a theme has none

### LINKED ISSUE #45862: Template Part Editor broken after updating to WordPress 6.1.1
After updating to WordPress 6.1.1 the Block Based Template Editor is loading just a blank white screen. No console error or anything.

This issue was originally reported on the make blog https://make.wordpress.org/core/2022/10/04/block-based-template-parts-in-traditional-themes/#comment-44097

@Mamaduka was successfully able to replicate this issue and has narrowed it down to the changes that were made in https://core.trac.wordpress.org/ticket/56945 specifically the lines here: https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/class-wp-theme-json-resolver.php#L423-L425

The issue happens on both WordPress 6.1.1 without any plugins and also with Gutenberg trunk.

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Fixes #45862.
Also, see #46054.
Report on trac: https://core.trac.wordpress.org/ticket/57193

PR fixes checks for `isUserConfigReady` and marks the config ready state as `true` when a theme has no global user styles.

## Why?
The block themes and now themes that use block-based template parts don't strictly require a `theme.json` file to access the Site Editor. However, after [recent performance improvements](https://core.trac.wordpress.org/ticket/56945) around `theme.json` methods, the global user styles query [bails early](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/class-wp-theme-json-resolver.php#L423-L425) if a theme doesn't support this file.

This caused the global styles `isReady` state to be false for such themes and prevented Site Editor from rendering.

## How?
I adjusted the `isReady` condition in `useGlobalStylesUserConfig` to account for themes that can access Site Editor but don't support `theme.json`.

## Testing Instructions
1. Using TT2 or any block theme
2. Temporarily rename the `theme.json` file.
3. Go to the Site Editor and confirm templates are correctly loading. On the trunk, the editor shows only a white screen.

### CODE REVIEW

File: packages/edit-site/src/components/global-styles/global-styles-provider.js [hunk 1]
```diff
@@ -45,22 +45,35 @@ const cleanEmptyObject = ( object ) => {
...
+			const record = _globalStylesId
+				? getEditedEntityRecord(
+						'root',
+						'globalStyles',
+						_globalStylesId
+				  )
+				: undefined;
+			const activeThemes = getEntityRecords( 'root', 'theme', {
+				status: 'active',
+			} );
```
Comment (Mamaduka) [inline packages/edit-site/src/components/global-styles/global-styles-provider.js]: The endpoint in the prefetched and the same selector is resolved in `__experimentalGetCurrentGlobalStylesId`, so this shouldn't cause any delays.

File: packages/edit-site/src/components/global-styles/global-styles-provider.js [hunk 2]
```diff
@@ -45,22 +45,35 @@ const cleanEmptyObject = ( object ) => {
...
+
+			return {
+				globalStylesId: _globalStylesId,
+				hasGlobalStyles:
+					!! activeThemes?.[ 0 ]?._links?.[
+						'wp:user-global-styles'
+					] ?? false,
```
Comment (Mamaduka) [inline packages/edit-site/src/components/global-styles/global-styles-provider.js]: After recent changes, this link won't be available if a theme doesn't support `theme.json`. See https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/rest-api/endpoints/class-wp-rest-themes-controller.php#L376-L380.

**Comment by Mamaduka** [comment]
@youknowriad, let me know if you prefer a different solution here.

File: packages/edit-site/src/components/global-styles/global-styles-provider.js [hunk 3]
```diff
@@ -45,22 +45,35 @@ const cleanEmptyObject = ( object ) => {
...
-	const { globalStylesId, settings, styles } = useSelect( ( select ) => {
-		const _globalStylesId =
-			select( coreStore ).__experimentalGetCurrentGlobalStylesId();
-		const record = _globalStylesId
-			? select( coreStore ).getEditedEntityRecord(
-					'root',
-					'globalStyles',
-					_globalStylesId
-			  )
-			: undefined;
```
Comment (youknowriad) [inline packages/edit-site/src/components/global-styles/global-styles-provider.js:57]: Can we instead rely on the "isResolving state" of both these two resolvers to mark it ready (instead of checking active themes).

Comment (Mamaduka) [reply packages/edit-site/src/components/global-styles/global-styles-provider.js:57]: I also had that idea; I will test how it works in practice.

Comment (Mamaduka) [reply packages/edit-site/src/components/global-styles/global-styles-provider.js:57]: Update the logic to use resolvers [69f0c34](https://github.com/WordPress/gutenberg/pull/46073/commits/69f0c34c220ceaa499bcc551150de40b28b234e0).

**Review by youknowriad — APPROVED** [review]
LGTM 👍
