### PR TITLE
Disable drop cap control if text is aligned

### LINKED ISSUE #11756: Drop cap and Alignment both option not working properly
**Describe the bug**
Drop cap and text alignment both settings do not work in new editor.

**To Reproduce**
1. Write a sentence in Paragraph block
2. Click on drop cap toggle
3. Click on Align right

**Screenshots**

error

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 69.0.3497.81

**Additional context**
- Gutenberg: latest from master
- WordPress: 5.0 beta 3

### PR DESCRIPTION
**Pull request by carolinan**
## What?

Disables drop cap control for paragraph blocks if the text is aligned to:
- Center
- Left on RTL
- Right on LTR

Fixes https://github.com/WordPress/gutenberg/issues/11756

## Why?

The drop cap did not work if the text was aligned because the first letter was not aligned with the rest of the text.
The drop cap also did not work on RTL where the first letter was in the wrong position.

## How?

When the text is aligned:

- The drop cap control is disabled and displays a help text.
- The block attribute` dropCap` is updated as well as the .has-drop-cap CSS classname.

## Testing Instructions

**Please test the deprecation:**
1. Disable Gutenberg. Activate a theme that has drop cap enabled.
2. Enable a LTR language on the WordPress install.
3. Create a new post or page and add 4 paragraph blocks with the drop cap option enabled:
One each for no alignment, left, center and right alignment.
4. Apply the PR and enable Gutenberg. 
5. Refresh the post or page you just created, and confirm if there are any block validation errors.

**Testing the functionality:**
1. Repeat step 3.
2. Confirm that the drop cap option is available for the left aligned block and the block with no alignment.
3. Confirm that it is disabled for the centered and right alignment.
4. Switch to an RTL language.
5. Refresh the post or page and confirm that there are no block validation errors.

1. Please confirm that when you switch to RTL, the left aligned block still displays the drop cap, but the drop cap control is disabled for this alignment.
2. Open the Advanced panel in the block settings sidebar.
3. Confirm that the has-drop-cap class is in the CSS field. Remove it.
4. Confirm that you were able to remove the visual drop cap.

**Check the front:**
Confirm that the drop cap is placed on the right side of the RTL text and that the spacing (margin) is correct.

## Screenshots or screencast 
Screen Shot 2022-07-14 at 08 20 58

### CODE REVIEW

File: packages/block-library/src/paragraph/save.js [hunk 1]
```diff
@@ -7,11 +7,15 @@ import classnames from 'classnames';
...
+import { isRTL } from '@wordpress/i18n';
 
 export default function save( { attributes } ) {
 	const { align, content, dropCap, direction } = attributes;
 	const className = classnames( {
-		'has-drop-cap': dropCap,
+		'has-drop-cap':
+			align === ( isRTL() ? 'left' : 'right' ) || align === 'center'
+				? false
+				: dropCap,
```
Comment (carolinan) [inline packages/block-library/src/paragraph/save.js:18]: This doesn't work well, there are block validation error when you switch between ltr and rtl. I'll try something else.

File: packages/block-library/src/paragraph/edit.js [hunk 2]
```diff
@@ -64,12 +64,26 @@ function ParagraphBlock( {
...
 			[ `has-text-align-${ align }` ]: align,
 		} ),
 		style: { direction },
 	} );
 
+	let helpText;
+	if ( align === ( isRTL() ? 'left' : 'right' ) || align === 'center' ) {
+		helpText = __( 'Aligned text can not have a drop cap.' );
+		// This attribute change also makes sure that the option is toggled off, not only disabled.
+		setAttributes( { dropCap: undefined } );
```
Comment (carolinan) [inline packages/block-library/src/paragraph/edit.js]: >setAttributes( { dropCap: undefined } );

My gut says that this should be separate and not in the "help text" check, what do you think?

File: packages/block-library/src/paragraph/edit.js [hunk 3]
```diff
@@ -64,12 +64,26 @@ function ParagraphBlock( {
 	const blockProps = useBlockProps( {
 		ref: useOnEnter( { clientId, content } ),
 		className: classnames( {
-			'has-drop-cap': dropCap,
+			'has-drop-cap':
+				align === ( isRTL() ? 'left' : 'right' ) || align === 'center'
```
Comment (aristath) [inline packages/block-library/src/paragraph/edit.js]: Minor thing - not a blocker. Would it be more readable if we wrote it like this?
```suggestion
				align === center || ( isRTL() && align === 'left' ) || ( ! isRTL() && align === 'right' )
```

File: packages/block-library/src/paragraph/edit.js (hunk 2 above)
Comment (Mamaduka) [reply packages/block-library/src/paragraph/edit.js]: That's correct. We shouldn't call `setAttribute` during the render.

Can you give me more details on when we want to set `dropCap` to `undefined`?

File: packages/block-library/src/paragraph/edit.js (hunk 3 above)
Comment (carolinan) [reply packages/block-library/src/paragraph/edit.js]: Personally this is not easier for me to read.

File: packages/block-library/src/paragraph/edit.js (hunk 2 above)
Comment (carolinan) [reply packages/block-library/src/paragraph/edit.js]: If the drop cap is first enabled and then the text is aligned, the control is disabled.
The option should also be toggled off, not remain toggled on, because the drop cap is not used. 

This is what the control looks like if it is disabled but toggled on:
Disabled toggle control with option enabled

I'll try to see if I can just put it on ToggleControl "checked".

Comment (Mamaduka) [reply packages/block-library/src/paragraph/edit.js]: Thanks for the clarification.

I think this `onChange` callback looks more suitable for setting the attribute.

https://github.com/WordPress/gutenberg/blob/9149f524eab181626531981f54ba1ca53447c231/packages/block-library/src/paragraph/edit.js#L92-L94

I also see that this check is repeated in a few places, so it might be good to extract in small function maybe `hasDropCap` or `hasDropCapDisabled`.

```js
// align === ( isRTL() ? 'left' : 'right' ) || align === 'center'
// Maybe something like this.
function hasDropCapDisabled( align ) {
    return align === ( isRTL() ? 'left' : 'right' ) || align === 'center';
}
```

File: packages/block-library/src/paragraph/edit.js [hunk 4]
```diff
@@ -113,7 +111,12 @@ function ParagraphBlock( {
 					>
 						<ToggleControl
 							label={ __( 'Drop cap' ) }
-							checked={ !! dropCap }
+							checked={
+								align === ( isRTL() ? 'left' : 'right' ) ||
+								align === 'center'
+									? false
+									: dropCap
```
Comment (carolinan) [inline packages/block-library/src/paragraph/edit.js]: Unchecks the toggle if the option is disabled.
The option is restored to the previous checked or unchecked state if the text alignment is removed.

The amount of times the if else is repeated is becoming a bit ridiculous 😀

Comment (Mamaduka) [reply packages/block-library/src/paragraph/edit.js]: I left some suggestions above; I hope that helps reduce the number 😄

Comment (carolinan) [reply packages/block-library/src/paragraph/edit.js]: yeah I didn't see your comment until after :)

File: packages/block-library/src/paragraph/edit.js (hunk 2 above)
Comment (carolinan) [reply packages/block-library/src/paragraph/edit.js]: I found that when the dropCap attribute is only updated on change, there is no way to use the drop cap control to remove a previously existing drop cap if the language direction is changed.

If I use a rtl language, enable the drop cap, and then switch the language direction on the WP install to ltr, the `has-drop-cap` class is already on the paragraph. If I use the control to toggle the drop cap off and then on, the paragraph ends up having duplicate `has-drop-cap `classes.
The class can be removed in the Advanced section, under "Additional CSS classes". 

Is this an edge case that can be ignored?

Comment (Mamaduka) [reply packages/block-library/src/paragraph/edit.js]: > Is this an edge case that can be ignored?

I think so. Updating content/attributes based on user language preferences might be more confusing.

**Comment by jasmussen** [comment]
Thanks for working on this! I'm getting an error trying to compile this branch:

```
Uncaught ReferenceError: omit is not defined
    at ./packages/block-library/build-module/paragraph/deprecated.js (deprecated.js:99:15)
    at __webpack_require__ (bootstrap:19:1)
    at ./packages/block-library/build-module/paragraph/index.js (edit.js:172:1)
    at __webpack_require__ (bootstrap:19:1)
    at make namespace object:7:1
    at index.js:276:8
    at index.js:276:8
index.js:133 Uncaught TypeError: Cannot read properties of undefined (reading 'registerCoreBlocks')
    at Module.initializeEditor (index.js:133:2)
    at HTMLDocument.<anonymous> (post-new.php:1817:25)
```

Here's the trunk behavior:
before

Question: if I apply the dropcap when left-aligned, and _then_ center or right aligned, is the drop cap removed?

In principle it makes total sense to remove the drop cap for center and right aligned, as it won't look very good there. Thanks for the PR!

**Comment by carolinan** [comment]
I think something may have gone wrong with the trunk merge, I will check if I can build it.

**Comment by carolinan** [comment]
I found that `omit` was removed from several packages 3 weeks ago I hope I removed it from the PR correctly.

Yes on LTR the drop cap is removed if the text is centered or right aligned and can be added again when left aligned or if no alignment is selected.

https://user-images.githubusercontent.com/7422055/191221091-cf8cd7d6-ed03-42d9-ad32-2e132dcd9bc1.mov

**Comment by jasmussen** [comment]
Looks good. Instead of "Aligned text can not have a drop cap", can we change that to "Not available for aligned text"?

**Review by aristath — APPROVED** [review]
