### PR TITLE
Admin UI: Fix type mismatch between Page title and NavigableRegion ariaLabel

### LINKED ISSUE #75898: Admin UI: Type mismatch between Page title prop and NavigableRegion ariaLabel
### Description

The `Page` component in `@wordpress/admin-ui` accepts `title` as `React.ReactNode`, but passes it directly to `NavigableRegion` as the `ariaLabel` prop, which is typed as `string` and renders it as an `aria-label` DOM attribute.

If a caller passes JSX as `title` (e.g., a title with an icon), the `aria-label` attribute renders as `[object Object]`, breaking accessibility for screen readers.

I expect `aria-label` to always contain a meaningful text string, or be omitted when a text string cannot be determined.

### Step-by-step reproduction instructions

1. Open `packages/admin-ui/src/page/index.tsx`
2. Note that `title` is typed as `React.ReactNode` (line 26)
3. Note that `title` is passed directly as `ariaLabel` to `NavigableRegion` (line 37)
4. Open `packages/admin-ui/src/navigable-region/index.tsx`
5. Note that `ariaLabel` is typed as `string` (line 17) and rendered as `aria-label` on the DOM element (line 29)
6. Use the `Page` component with a JSX title: `<Page title={<><Icon /><span>My Page</span></>}>`
7. Inspect the rendered DOM — the region element's `aria-label` is `[object Object]`

```tsx
// Current behavior — type mismatch allows this, but produces broken a11y
<Page title={<><MyIcon /><span>Dashboard</span></>}>
  <Content />
</Page>
// Renders: <div aria-label="[object Object]" role="region" ...>
```

### Environment info

- Gutenberg trunk (latest)
- This is a TypeScript type/API issue, not browser-specific

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by jeherve**
## What?

Closes #75898

Add an explicit `ariaLabel` prop to the `Page` component and make `NavigableRegion`'s `ariaLabel` optional, fixing a type mismatch between the two components.

## Why?

`Page` accepts `title` as `React.ReactNode` but passes it directly to `NavigableRegion` as `ariaLabel`, which expects a `string` and renders it as an `aria-label` DOM attribute. If a caller passes JSX as `title` (e.g., a title with an icon), the `aria-label` renders as `[object Object]`, breaking accessibility for screen readers.

## How?

- Add an optional `ariaLabel?: string` prop to `Page`.
- When resolving the value for `NavigableRegion`'s `ariaLabel`:
  - Use the explicit `ariaLabel` prop if provided.
  - Fall back to `title` if it's a plain string.
  - Otherwise pass `undefined`, which omits the `aria-label` attribute from the DOM.
- Make `NavigableRegion`'s `ariaLabel` prop optional (`string | undefined`). React naturally omits the attribute when the value is `undefined`.

All existing callers pass string titles and don't use the new `ariaLabel` prop, so behavior is unchanged.

## Testing Instructions

1. Verify existing behavior is preserved: open any admin page that uses the `Page` component (e.g., Templates, Patterns, Styles). Inspect the wrapping region element — it should still have a valid `aria-label` matching the page title.
2. Verify the fix: use the `Page` component with a JSX title and an explicit `ariaLabel`:
   ```tsx
   <Page title={<><Icon /><span>My Page</span></>} ariaLabel="My Page">
   ```
   Inspect the DOM — the region element's `aria-label` should be `"My Page"`, not `[object Object]`.
3. Verify graceful fallback: use `Page` with a JSX title and no `ariaLabel`. The region element should have no `aria-label` attribute rather than a broken one.

### Testing Instructions for Keyboard

No UI changes — this PR fixes a prop type and adds an optional prop. Keyboard interaction is unaffected. Accessibility is improved: screen readers will no longer encounter `[object Object]` as a region label.

## Screenshots or screencast

N/A — this is a type/API fix with no visual changes.

### CODE REVIEW

**Comment by simison** [comment]
Can you also update the [changelog](https://github.com/jeherve/gutenberg/blob/ffb653d9106c32ff811194e42b579a90b6868c58/packages/admin-ui/CHANGELOG.md)?

**Comment by youknowriad** [comment]
Is making the ariaLabel optional in NavigableRegion the right move? Isn't the main idea of that component is to be an accessible aria region and without a label, it's a bug basically?

**Comment by jeherve** [comment]
> Is making the ariaLabel optional in NavigableRegion the right move? Isn't the main idea of that component is to be an accessible aria region and without a label, it's a bug basically?

That's a good point. I suppose there should always be a label. I'm not sure what's the best way to go about it ; I didn't want to make it mandatory because I wasn't sure it was a good idea, since there are already components that rely on `NavigableRegion` out there. What would you recommend?

**Comment by youknowriad** [comment]
Are there components that rely on this component that don't provide the label? I feel like if it's the case, these components should be updated to provide one no?

**Comment by jeherve** [comment]
I would agree, and we can do that in the Gutenberg codebase (I've just done so), and we can then make the new prop mandatory, but how can we account for third-parties using the package and not knowing about those changes? Is it okay to introduce a new mandatory prop like this?

**Comment by youknowriad** [comment]
> Is it okay to introduce a new mandatory prop like this?

I actually thought the prop existed in the component before and was mistyped, but it seems the prop didn't exist but instead "aria-label" prop was being used.

what do you think is best? keep using aria-label or introduce a new ariaLabel. Both options seem possible as long as we keep the previous aria-label passing working (which seems to be the case now)

File: packages/admin-ui/src/page/index.tsx [hunk 1]
```diff
@@ -28,13 +29,14 @@ function Page( {
...
 	actions?: React.ReactNode;
+	ariaLabel: string;
 	hasPadding?: boolean;
 	showSidebarToggle?: boolean;
 } ) {
 	const classes = clsx( 'admin-ui-page', className );
 
 	return (
-		<NavigableRegion className={ classes } ariaLabel={ title }>
+		<NavigableRegion className={ classes } ariaLabel={ ariaLabel }>
```
Comment (youknowriad) [inline packages/admin-ui/src/page/index.tsx]: Where I have trouble with this PR is that I don't think we should force "Page" users to provide two titles (a title and an ariaLabel). Why can't we use the title as ariaLabel? or maybe the ariaLabel should be optional when we want these two things to be different.

File: packages/boot/src/components/app/router.tsx [hunk 2]
```diff
@@ -38,7 +38,11 @@ const {
 function NotFoundComponent() {
 	return (
 		<div className="boot-layout__stage">
-			<Page title={ __( 'Route not found' ) } hasPadding>
+			<Page
+				title={ __( 'Route not found' ) }
+				ariaLabel={ __( 'Route not found' ) }
```
Comment (youknowriad) [inline packages/boot/src/components/app/router.tsx]: This [comment](https://github.com/WordPress/gutenberg/pull/75899/changes#r2858679272) is very visible here, why as a consumer I have to prove my title twice.

File: packages/admin-ui/src/page/index.tsx (hunk 1 above)
Comment (simison) [reply packages/admin-ui/src/page/index.tsx]: +1, as long as `title` is a string, it should be enough:

`<Page title={ <PageNameWithLogo /> } ariaLabel="Page name" />`
and
`<Page title="Page name" />`

Comment (jeherve) [reply packages/admin-ui/src/page/index.tsx]: > Why can't we use the title as ariaLabel? or maybe the ariaLabel should be optional when we want these two things to be different.

I pushed a commit to do just that, let me know what you think.

**Review by youknowriad — APPROVED** [review]

File: packages/admin-ui/src/page/index.tsx (hunk 1 above)
Comment (simison) [reply packages/admin-ui/src/page/index.tsx]: Looks good!

**Review by simison — APPROVED** [review]
