### PR TITLE
Interactivity API: Fix router initialization race condition on Safari/Firefox

### LINKED ISSUE #75778: Interactivity API fails to re-hydrate on iOS Safari after bfcache restoration
## Description
The Interactivity API fails to re-hydrate interactive elements (e.g., Mini Cart, custom buttons) on **iOS Safari** when a page is restored from the **Back-Forward Cache (bfcache)**.

When a user navigates to a page using the `@wordpress/interactivity-router`, closes the tab, and then reopens it (or uses the "Back" button after the page has been evicted from memory and restored), the interactive elements become unresponsive. The JavaScript engine restores the state from the cache, but the Interactivity API's internal state and event listeners appear to be disconnected from the restored DOM.

This issue is specific to iOS Safari. Chrome and Firefox handle bfcache restoration more gracefully, sometimes allowing manual re-initialization via the `pageshow` event, but Safari's restoration mechanism causes a permanent "frozen" state where calls to `getContext()` or interactions fail silently or throw errors because the context stack is invalid.

## Step-by-step reproduction instructions
1.  **Setup:** Use a hybrid theme setup:
    *   A classic PHP theme header containing a WooCommerce Mini-Cart block (rendered via `do_blocks`).
    *   A content area wrapped in `data-wp-interactive` and `data-wp-router-region`.
    *   A custom script module importing `@wordpress/interactivity` and `@wordpress/interactivity-router` to handle AJAX navigation.
2.  **Pre-condition:** Ensure the site is loaded on an **iPhone or iPad (Safari, iOS 17+)**.
3.  **Action:**
    1.  Open the site. Verify the Mini-Cart button works (opens drawer).
    2.  Navigate to a different page using a link handled by the Interactivity Router.
    3.  Verify interactive elements on the new page work.
    4.  **Close the Safari tab.**
    5.  **Reopen the tab** (Safari restores it from bfcache).
    *   *Alternative:* Put the tab in background, open other heavy apps to force memory pressure, then return to the tab.
4.  **Test:** Try clicking the Mini-Cart button or any `data-wp-on--click` element.

## Expected behaviour
Interactive elements should remain functional after the page is restored from bfcache. The Interactivity API should either automatically re-hydrate the DOM or expose a method to manually trigger re-hydration on `pageshow` event (persisted: true).

## Actual behaviour
Interactive elements are completely dead. Clicking on Mini-Cart or Add to Cart buttons does nothing. The DOM is present, but the JS event listeners attached by the Interactivity API are detached or pointing to a stale/undefined context. No errors may appear in the console if the failure is silent, or `TypeError` regarding undefined context may appear if hydration is forced.

## WordPress information
- WordPress version: 6.9.1 (trunk/dev)
- Gutenberg version: Latest (as integrated in WP core / Interactivity API packages)
- Are all plugins except Gutenberg deactivated? Yes (except WooCommerce for Block testing).
- Are you using a default theme? No, custom hybrid theme (Classic Header + Block Content).

## Device information
- Device: iPhone / iPad
- Operating system: iOS 18.x / 17.x
- Browser: Safari Mobile

## Technical Analysis
The issue seems to stem from how the internal `at()` function (used by `getContext`) and the proxy-based state management interact with Safari's freezing mechanism.
When Safari restores from bfcache, it restores the JS heap "as is". However, the Interactivity API relies on a specific initialization order. If the script tries to access context or state after restoration, it encounters a race condition where the DOM is ready, but the internal iAPI context stack is empty or corrupted.

A simplified reproduction script (attached below) shows that attempting to re-trigger `init()` via `pageshow` fails to restore functionality on Safari, whereas it works on Firefox.

References to #76053

### PR DESCRIPTION
**Pull request by markusfoo**
### Description

This PR resolves the race condition issue diagnosed in Firefox and Safari, where `@wordpress/interactivity-router` evaluates before `hydrateRegions()` completes, leading to premature `toVdom()` calls, islands marked as hydrated, and completely non-functional interactive regions (dead DOM).

The root cause and step-by-step solution have been successfully implemented in the commits of this pull request, following the exact structure proposed and refined through detailed discussion in #75778.

The fix has been manually verified on the test site:  

[https://markuss.cu.ma/shop/](https://markuss.cu.ma/shop/)

(All changes were applied directly to the compiled JS equivalent of the presented .ts files, matching the proposed structure.)

Special thanks to @DAreRodz for the insightful feedback, clear architectural guidance, and collaborative help in resolving this longstanding issue with the Interactivity API.

## Summary
Fixes a critical race condition where `@wordpress/interactivity-router` evaluates before `hydrateRegions()` completes on slower JavaScript engines. This resulted in interactive regions being permanently non-functional (dead DOM) on Firefox and Safari.

Fixes #75778.

## The Problem
As extensively documented in [#75778](https://github.com/WordPress/gutenberg/issues/75778), the router accesses `initialVdom` (a `WeakMap`) at module-evaluation time. On Safari (JavaScriptCore) and Firefox (SpiderMonkey), the router often evaluates *before* the hydration phase has populated this map.

The router falls back to calling `toVdom()` on the full document. This function has an intentional side-effect: it calls `hydratedIslands.add()` for every `[data-wp-interactive]` node to handle nested islands. When the actual `hydrateRegions()` subsequently runs, it sees all islands marked as hydrated and skips them.

**Result:** The page renders visually, but all event listeners are missing. The DOM is "dead".

https://github.com/user-attachments/assets/58713fa1-023f-4350-aa11-cba3632a3d54

**Symptoms:**
*   Mini-Cart, Add to Cart buttons, and custom `data-wp-on--click` elements unresponsive.
*   Reproducible on new tabs, warm HTTP cache, and tab restoration.
*   Chrome (V8) typically masked this due to faster module evaluation speeds.

## The Fix
This PR introduces a synchronization promise to enforce the correct initialization order.

*   **`packages/interactivity/src/hydration.ts`**
    Added `initialVdomPromise`, a `Promise` that resolves with the `WeakMap` only after `hydrateRegions()` finishes.
*   **`packages/interactivity/src/index.ts`**
    Exposed `initialVdomPromise` through `privateApis`.
*   **`packages/interactivity-router/src/index.ts`**
    Wrapped the initial `pages.set()` logic in an async IIFE that `await`s `initialVdomPromise`.

The router now explicitly waits for the signal that hydration is complete, removing the dependency on engine execution speed.

## What is not changed
*   **`vdom.ts`**: `hydratedIslands.add()` logic is untouched; it is correct and necessary for nested islands.
*   **Public API**: No breaking changes. `initialVdom` type remains `WeakMap`.

## Testing
Verified on the reproduction site (WordPress 7.0 Beta 2 + WooCommerce + Hybrid Theme):

*   **Firefox 148.0** (Current) / **147.0.4** / **Nightly 150.0a1** ✅ Fixed (previously dead DOM on warm cache).
*   **Chrome 138.0.7204.305** ✅ No regression.
*   **Opera 127.0.5778.76** ✅ No regression.
*   **Safari iOS 18** ✅ Fixed (previously dead DOM on new tabs/restoration).

All interactive elements are now fully functional across all tested engines.

## References
Fixes #75778.

### CODE REVIEW

**Comment by DAreRodz** [comment]
Thanks, @markusfoo!

Could you add an e2e test that reproduces the issue and passes with your changes? It would require a test page enqueuing the iAPI router, so we ensure the router is evaluated before the iAPI runtime in all browsers.

**Comment by markusfoo** [comment]
> Thanks, @markusfoo!
> 
> Could you add an e2e test that reproduces the issue and passes with your changes? It would require a test page enqueuing the iAPI router, so we ensure the router is evaluated before the iAPI runtime in all browsers.

Hi again and thank for review @DAreRodz — done! Added the e2e test in `test/e2e/specs/interactivity/router-race-condition.spec.ts` with a dedicated test block in `packages/e2e-tests/plugins/interactive-blocks/router-race-condition/`.

The fixture uses `'import' => 'static'` for the router in `view.asset.php`, which places `@wordpress/interactivity-router` at the root of the ES module graph — guaranteeing its module-level code runs before `hydrateRegions()` in every browser, making the race deterministic and reproducible in CI (not just Firefox/Safari).

Two tests cover both binding types:
- **context-driven**: `data-wp-on--click` bound to local context
- **global-state**: `data-wp-on--click` bound to global state

**What our test does:**

`view.asset.php` with `'import' => 'static'` is the key. When the router is declared as a static dependency, the browser places it in the initial ES module graph. This guarantees the router executes before `hydrateRegions()` — in Chrome, Firefox, Safari, any browser. This is exactly the race condition we were fixing.

**What happens without the fix:**

- Router executes first → reads empty `initialVdom` WeakMap
- Calls `toVdom()` on the entire document → all islands are added to `hydratedIslands`
- `hydrateRegions()` sees islands already "processed" → skips them
- Dead DOM — buttons don't respond to clicks

**What our test verifies:**

- Clicks a button → expects the counter to change
- If the DOM is dead — the click does nothing → test fails with a timeout

All 32 checks passed, including Playwright 1 – 8. ✅

**Review by DAreRodz — APPROVED** [review]
Thanks, @markusfoo, for this PR!

I did some minor changes to the e2e test files so the actual bug is covered, and also simplified the comments present in the spec file. The rest of the code is good to me, and the bug is fixed. 🙂

@luisherranz, it would be good to have a second approval here before merging the PR, just in case.

**Review by luisherranz — CHANGES_REQUESTED** [review]
We're missing a changelog.

File: packages/interactivity-router/src/index.ts [hunk 1]
```diff
@@ -17,6 +17,7 @@ import {
 const {
 	getRegionRootFragment,
 	initialVdom,
```
Comment (luisherranz) [inline packages/interactivity-router/src/index.ts]: The `initialVdom` no longer needs to be exported as a private API. The router already obtains the value through the promise.

**Review by luisherranz — DISMISSED** [review]

**Comment by markusfoo** [comment]
> Thanks, @markusfoo, for this PR!
> 
> I did some minor changes to the e2e test files so the actual bug is covered, and also simplified the comments present in the spec file. The rest of the code is good to me, and the bug is fixed. 🙂
> 
> @luisherranz, it would be good to have a second approval here before merging the PR, just in case.

Thank you so much, @DAreRodz! Your architectural guidance was invaluable throughout this process. Regarding the changelog — I was aware it was needed, but wanted to wait until the overall solution approach was confirmed and approved before finalizing it. Now that we've aligned on the architecture, the changelog entries have been added for both packages. Really appreciate your thorough review and the improvements you made to the e2e tests! 🙏

**Comment by markusfoo** [comment]
> We're missing a changelog.

Thank you for the feedback, @luisherranz! I've addressed both of your requests:

- ✅ Changelog entries added to both `packages/interactivity/CHANGELOG.md` and `packages/interactivity-router/CHANGELOG.md` under `## Unreleased`.
- ✅ Removed `initialVdom` from `privateApis` exports — the router now obtains the value exclusively through `initialVdomPromise`, as you correctly pointed out.

Appreciate the precise review!

File: packages/interactivity-router/src/index.ts (hunk 1 above)
Comment (markusfoo) [reply packages/interactivity-router/src/index.ts]: Done ✅

**Comment by luisherranz** [comment]
LGTM now, thanks @markusfoo.

I'll leave it to @darerodz to do the final review and merge.

**Review by DAreRodz — APPROVED** [review]
Looks good to me. Thanks, @markusfoo!

**Comment by luisherranz** [comment]
PR with the merge fix:

- https://github.com/WordPress/gutenberg/pull/76191

**Comment by markusfoo** [comment]
Thank you both @DAreRodz and @luisherranz — really appreciate the 
collaborative review process and the architectural guidance throughout. 
Glad this one made it in time for 7.0! 🙏
