### PR TITLE
[ Navigation ] Adds orientation class on front for navigation

### LINKED ISSUE #21890: Vertical navigation block is missing a class on the front
**Describe the bug**
In the editor, the vertical variation of the navigation block can be identified with
`is-vertical` but this CSS class is not present on the front, so there is no way to tell the 
horizontal and vertical styles from the other.

**To reproduce**
1. Add a vertical navigation block to a post or page
2. Add a horizontal navigation block too, in case you wish to compare them.
3. Save
4. View the front

**Expected behavior**
I expect the CSS class and the existing styles to be applied to block.

**Screenshots**
is-vertical-is-missing

**Editor version (please complete the following information):**
- WordPress version: 5.4
Gutenberg 7.9.1

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser: Chrome Version 81.0.4044.122

### PR DESCRIPTION
**Pull request by draganescu**
## Description
Fixes #21890 

## How has this been tested?
Tested locally by:

1. Go to a new post
2. Using the inserter add a horizontal menu and add some items in it
3. Using the inserter add a vertical menu and add some items in it
4. Save the post
5. Check that the rendered front post has one vertical and one horizontal looking menu.

## Screenshots

Screenshot 2020-05-11 at 19 24 44

## Types of changes
Non breaking change that adds a class name to the rendered navigation menu. It adds both `is-horizontal` as a default and `is-vertical` as a variant.

### CODE REVIEW

File: packages/block-library/src/navigation/index.php [hunk 1]
```diff
@@ -157,13 +157,19 @@ function render_block_core_navigation( $content, $block ) {
 		return '';
 	}
 
+	$orientation_class_name = 'is-horizontal';
```
Comment (talldan) [inline packages/block-library/src/navigation/index.php:160]: It doesn't look like `is-horizontal` is added in the `edit.js` file for the block. 

It should ideally be consistent. The class itself seems to be unused, so I don't think it should be added here:
```suggestion
	$orientation_class_name = '';
```

**Comment by draganescu** [comment]
Yes I agree @talldan. It's similar to `is-dark`  / `is-light` style. The default is not applied at all. I committed your suggestion.

File: packages/block-library/src/navigation/index.php [hunk 2]
```diff
@@ -157,13 +157,19 @@ function render_block_core_navigation( $content, $block ) {
...
+	}
+
 	$colors          = block_core_navigation_build_css_colors( $attributes );
 	$font_sizes      = block_core_navigation_build_css_font_sizes( $attributes );
 	$classes         = array_merge(
 		$colors['css_classes'],
 		$font_sizes['css_classes'],
 		array( 'wp-block-navigation' ),
 		isset( $attributes['className'] ) ? array( $attributes['className'] ) : array(),
+		array( $orientation_class_name ),
```
Comment (jorgefilipecosta) [inline packages/block-library/src/navigation/index.php:172]: It seems when orientation class name is not vertical we are not passing an empty array but an array with an empty string. This adds an unexpected space on the class attribute "wp-block-navigation ". What if we simplify things a little and replace `array( $orientation_class_name )`with  `isset( $attributes['orientation'] ) && 'vertical' === $attributes['orientation'] ) ? array( 'is-vertical' ) : array(),`?

Comment (draganescu) [reply packages/block-library/src/navigation/index.php:172]: Thanks @jorgefilipecosta I'll update accordingly.

**Review by adamziel — APPROVED** [review]
