### PR TITLE
RangeControl: Fix space between icons and rail

### LINKED ISSUE #37801: RangeControl: Spacing issue between icons and the rail
### Description

RangeControl spacing is not correct. If you use both beforeIcon and afterIcon, the spacing between icons and the rail is not the same. 

### Step-by-step reproduction instructions

1. Import RangeControl from "@wordpress/components"
2. Add RangeControl to the InspectorControls

```
<RangeControl
    beforeIcon="upload"
    afterIcon="download"
    label="Columns"
    value={ columns }
    onChange={ ( value ) => setColumns( value ) }
    min={ 2 }
    max={ 20 }
/>
```

### Screenshots, screen recording, code snippet

#36935
wp-range-control-style-issue

### Environment info

- WordPress 5.8.3
- Gutenberg 12.3.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by imangm**
## Description

Fixes #37801.

Space between beforeIcon and range control and between afterIcon and range control were not equal.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by Mamaduka** [comment]
Hello, @imangm

Sorry for the late follow-up. Is there an issue we should link to this PR?

**Comment by imangm** [comment]
> Hello, @imangm
> 
> Sorry for the late follow-up. Is there an issue we should link to this PR?

Hi @Mamaduka,

Actually, I hadn't done it since I didn't know about the process. But I did it now: #37801

Thanks

**Review by ciampo — COMMENTED** [review]
Hey @imangm , thank you for opening this PR! I'm not aware if the discrepancy in the spacing between the before and the after icons is there on purpose or not. I wonder if @jasmussen can help out on this (issue reported in #37801)

Also, would you mind adding an entry to the [CHANGELOG](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md)?

File: packages/components/src/range-control/styles/range-control-styles.js [hunk 1]
```diff
@@ -58,7 +58,7 @@ export const BeforeIconWrapper = styled.span`
 export const AfterIconWrapper = styled.span`
 	margin-top: ${ railHeight }px;
 
-	${ rtl( { marginLeft: 16 } ) }
+	${ rtl( { marginLeft: 6 } ) }
```
Comment (jasmussen) [inline packages/components/src/range-control/styles/range-control-styles.js:61]: This change seems fine since it matches the metrics of the BeforeIconWrapper as well.

Comment (ciampo) [reply packages/components/src/range-control/styles/range-control-styles.js:61]: Cool, I just wasn't sure if the difference was on purpose or not.

Comment (ciampo) [reply packages/components/src/range-control/styles/range-control-styles.js:61]: Thank you!

**Comment by jasmussen** [comment]
Thanks for the PR, it looks pretty safe to me. To the best of my knowledge, the `afterIcon` property hasn't been widely used in the block editor itself, and exists only in storybook and tests, which is likely why it might not have received as much attention. Same, honestly, with the `beforeIcon`, so it seems like a good enough patch to make!

Unrelated to this PR, it might be nice to look at using `gap` on the component side, so we could do with a single value rather than two.

**Review by ciampo — APPROVED** [review]
LGTM 🚀 

This can be merged as soon as a changelog entry gets added

**Comment by ciampo** [comment]
> LGTM 🚀
> 
> This can be merged as soon as a changelog entry gets added

Hey @imangm, do you need any help? This is the [CHANGELOG](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md) I was referring to.

**Comment by imangm** [comment]
> > LGTM 🚀
> > This can be merged as soon as a changelog entry gets added
> 
> Hey @imangm, do you need any help? This is the [CHANGELOG](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md) I was referring to.

Hey @ciampo! Not sure if I've done it properly since it's my first time doing it here, but I fetched the latest upstream version and updated changelog and committed it. Is it fine?

**Comment by ciampo** [comment]
> > > LGTM 🚀
> > > This can be merged as soon as a changelog entry gets added
> > 
> > 
> > Hey @imangm, do you need any help? This is the [CHANGELOG](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md) I was referring to.
> 
> Hey @ciampo! Not sure if I've done it properly since it's my first time doing it here, but I fetched the latest upstream version and updated changelog and committed it. Is it fine?

Looks good to me, thank you! Going to merge now
