### PR TITLE
Permit unbounded per_page=-1 requests for Pages and Shared Blocks

### LINKED ISSUE #4632: Saved blocks list doesn't show all saved blocks (only a maximum of 10)
## Issue Overview
Saved blocks list does not show all saved blocks.

Only currently used in post and max. 10 additional saved blocks are shown.

## Steps to Reproduce (for bugs)
1. WordPress 4.9.2, Gutenberg 2.0.0
2. 25 saved blocks
3. Create new post
4. Add block -> saved blocks

## Expected Behavior
List of 25 saved blocks

## Current Behavior
List of 10 saved blocks

## Possible Solution
Use higher per_page (currently 10) and X-WP-TotalPages and/or X-WP-Total headers in REST API response to get missing entries.

### LINKED ISSUE #6487: Page select UI is limited to 101 select items
## Issue Overview

From #6180 

Pages in page editor limits to 101 select items (probably 100 pages) when all top-level

## Steps to Reproduce (for bugs)

I've just tested using the following bookmarklet / console scripts

### Add a page every second

```
setInterval(function() { wp.apiRequest({method:'POST',path:'/wp/v2/pages',credentials:true,data:{'title':'REST-gen-'+Date.now(),'content':'empty','status':'publish'}}) }, 1000)
```

visiting /wp-admin/edit.php?post_status=publish&post_type=page I can see it creates 500+ pages, all published

visiting /wp-admin/post-new.php?post_type=page and running the following content script

### Count pages in side-bar of Gutenberg parent page

```
[].slice.call(document.querySelectorAll('#inspector-select-control-0 option')).length
```

shows 101 (no matter how many pages I add.

## Expected Behavior

Metabox to appear and behave like core WP (or better as I'm sure there is a bug in core for large numbers of pages).

## Current Behavior

Limited to 100 top level pages.

## Possible Solution

* Ideal-case: autocomplete
* Next-best: #6180 scroll-box
* Acceptable: core wordpress matched experience.

## Screenshots / Video

N/A (content script to repeat above), not a visual bug

## Related Issues and/or PRs

#6180 
#4622 
#4022
#5820

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] PR

### PR DESCRIPTION
**Pull request by danielbachhuber**
## Description

Permits requests of `per_page=-1` to `/wp/v2/pages` and `/wp/v2/blocks` in order to fetch all available items; updates corresponding Gutenberg components to fetch all items.

Fixes #6487
Fixes #4632
Related #6627
See https://github.com/WordPress/gutenberg/issues/6180#issuecomment-384511059

## How has this been tested?

I generated 200 pages with:

```
wp post generate --post_type=page --post_status=publish --count=200
```

When I access the Page editor, I can see all items in the dropdown:

image

Similarly, I created more than 10 shared blocks and can see all of them in the inserter UI:

image

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Test failure was unrelated; I cleared cache and restarted.

**Review by rianrietveld — COMMENTED** [review]
@danielbachhuber I don't think I'm the best person to review this PR.

File: lib/rest-api.php [hunk 1]
```diff
@@ -450,6 +458,48 @@ function gutenberg_handle_early_callback_checks( $response, $handler, $request )
...
+ *
+ * @param array  $query_params JSON Schema-formatted collection parameters.
+ * @param string $post_type    Post type being accessed.
+ * @return array
+ */
+function gutenberg_filter_post_collection_parameters( $query_params, $post_type ) {
+	$post_types = array( 'page', 'wp_block' );
+	if ( in_array( $post_type->name, $post_types, true )
+		&& isset( $query_params['per_page'] ) ) {
+		// Change from '1' to '-1', which means unlimited.
```
Comment (tofumatt) [inline lib/rest-api.php]: I don't quite understand this comment; where is `'1'` being checked for?

File: lib/rest-api.php [hunk 2]
```diff
@@ -450,6 +458,48 @@ function gutenberg_handle_early_callback_checks( $response, $handler, $request )
...
+ * @param WP_REST_Request $request       The current request.
+ * @return array
+ */
+function gutenberg_filter_post_query_arguments( $prepared_args, $request ) {
+	$post_types = array( 'page', 'wp_block' );
+	if ( in_array( $prepared_args['post_type'], $post_types, true ) ) {
+		// Avoid triggering 'rest_post_invalid_page_number' error
+		// which will need to be addressed in https://core.trac.wordpress.org/ticket/43998.
+		if ( -1 === $prepared_args['posts_per_page'] ) {
+			$prepared_args['posts_per_page'] = 100000;
```
Comment (tofumatt) [inline lib/rest-api.php]: This looks like a hack that will be hard to debug as there isn't any logging around it.

Also: it seems unbounded requests are only allowed for authorised users... seems like they need `edit_posts` to be able to use this feature but just wanted to make sure that's also a requirement to use Gutenberg (sorry, I'm new here!) or this will have unpredictable results.

**Review by tofumatt — DISMISSED** [review]
This doesn't seem to answer UX questions around large lists or how to approach this, and returning an unbounded list of authors/block types (or really, anything) is dangerous.

The trac issue linked to in this code also mentions that unbounded requests can cause performance issues. I don't see how the proposed patch in Core (https://core.trac.wordpress.org/ticket/43998) or this patch prevent DOS issues from unbounded queries. Aside from straight-up DOS (exhausting the DB, whatever else), this could result in slow load times which would negatively impact Gutenberg UX.

This solution seems to hope that:

* `100000` is enough for `$prepared_args['posts_per_page']`–https://github.com/WordPress/gutenberg/pull/6657/files#diff-d0c65e7ac505d44d8571ddaffc510d98R494
* We don't need to worry about the performance impact this will have

I understand the existing discussion around this issue has been ongoing for awhile and it's quite a frustrating bug, but I'm not sure this addresses many of the issues raised.

**Comment by danielbachhuber** [comment]
> This doesn't seem to answer UX questions around large lists or how to approach this, and returning an unbounded list of authors/block types (or really, anything) is dangerous.

Correct, this is intentional. See conversation in https://github.com/WordPress/gutenberg/issues/6180#issuecomment-384511059

File: lib/rest-api.php (hunk 1 above)
Comment (danielbachhuber) [reply lib/rest-api.php]: > where is `'1'` being checked for?

It doesn't need to be checked for. `'1'` is the default value: https://github.com/WordPress/WordPress/blob/2f792d442bf771a3aade170cc9cae459f024c57b/wp-includes/rest-api/endpoints/class-wp-rest-controller.php#L321

File: lib/rest-api.php (hunk 2 above)
Comment (danielbachhuber) [reply lib/rest-api.php]: > This looks like a hack that will be hard to debug as there isn't any logging around it.

Yes. It's a hack that will only exist until the patch I've yet to prepare for https://core.trac.wordpress.org/ticket/43998 lands in WP 4.9.7

> Also: it seems unbounded requests are only allowed for authorised users... seems like they need `edit_posts` to be able to use this feature but just wanted to make sure that's also a requirement to use Gutenberg (sorry, I'm new here!) or this will have unpredictable results.

Correct. `edit_posts` is a reasonable minimum capability assumption for Gutenberg.

File: lib/rest-api.php (hunk 1 above)
Comment (tofumatt) [reply lib/rest-api.php]: I don't see any checks at all for `minimum` though.

Maybe I just don't get the query params variable here but it looks like it's a dictionary and here you're just checking for `$query_params['per_page']`, not `$query_params['per_page']['minimum']`.

It would be at least handy to say `// Change from default value '1' to '-1', which means unlimited.`

That said this code strikes me as assuming minimum is set to the default if set at all which I can't tell from here.

Comment (tofumatt) [reply lib/rest-api.php]: Oh wait, I understand the code now but it was not obvious at first. I'd suggest changing this function to add a few more comments for context:

```php
function gutenberg_filter_post_collection_parameters( $query_params, $post_type ) {
	$post_types = array( 'page', 'wp_block' );
	// HACK: If 'per_page' is set, ignore it and change the items returned
	// per-page to be '-1'.
	// See: https://github.com/WordPress/gutenberg/issues/6180#issuecomment-384511059
	if ( in_array( $post_type->name, $post_types, true )
		&& isset( $query_params['per_page'] ) ) {
		// Change from '1' (defalut) to '-1', which means unlimited.
		$query_params['per_page']['minimum'] = -1;
		// Default sanitize callback is 'absint', which won't work in our case.
		$query_params['per_page']['sanitize_callback'] = 'rest_sanitize_request_arg';
	}
	return $query_params;
}
```

That seems to be the intent of the code, right?

Comment (TimothyBJacobs) [reply lib/rest-api.php]: I don't think that comment is right. This is adjusting the collection params schema, not the actual request arguments. The schema ( `per_page`) is validated by WordPress itself in `WP_REST_Request`  using `rest_validate_value_from_schema`.

**Comment by danielbachhuber** [comment]
> I'm still concerned here around scalability.

Do your scalability concerns with this pull request differ from those with the `wp_dropdown_pages()` implementation in the classic editor?

> Does this still work if the site has 2,000 pages?

Yes, it works in my testing. The REST API request takes ~7s to fulfill.

> what is memory footprint client/server wise to fulfill these large request?

Is memory utilization a limiting factor here?

**Comment by adamsilverstein** [comment]
> Do your scalability concerns with this pull request differ from those with the wp_dropdown_pages() implementation in the classic editor?

yes, I'm concerned about the additional client side memory requirements added by keeping all of the records in the app memory/state.

> Yes, it works in my testing. The REST API request takes ~7s to fulfill.

good to hear. i hesitate to ask about 20,000 or 200,000.

**Comment by danielbachhuber** [comment]
> yes, I'm concerned about the additional client side memory requirements added by keeping all of the records in the app memory/state.

How much additional memory is this? What percentage of WordPress sites are impacted by this concern? And, given the API request isn't even made until the UI is opened, is this a concern we need to optimize for?

**Comment by adamsilverstein** [comment]
_> How much additional memory is this, over the data that's already present in \<select>?_ 


twice as much vs a select? i'm comparing this to a more search/request based solution that never loads the full set

> What percentage of WordPress sites are impacted by this concern? 


no idea what the percentage is, certainly the total number is not insignificant. For these users, a dropdown may be unusable.

> And, given the API request isn't even made until the UI is opened, is this a concern we need to optimize for?

I'm not sure if its a concern we should ignore. 

If we do take this approach, I'd still love to work on a more scalable search based selector. Since this pattern of selecting from a (potentially very large) list is something we are likely to repeat in different contexts across Gutenberg, I'd love to see it solved in a way that worked very well for all cases. My hope is that something similar to the searchable select i suggested in https://github.com/WordPress/gutenberg/pull/5921 does.

**Comment by danielbachhuber** [comment]
> twice as much vs a select? i'm comparing this to a more search/request based solution that never loads the full set

Just to clarify, is this a _hypothetical_ concern, or something you've tested and have data / methodology for?

> I'm not sure if its a concern we should ignore.

This is an incorrect characterization of my perspective. Rather, I'm suggesting that:

1. It's May 10th, 2018.
2. We have at least two critical bugs to resolve (#6487 and #4632).
3. In the interest of time, we go with the solution we have.

> If we do take this approach, I'd still love to work on a more scalable search based selector.  Since this pattern of selecting from a (potentially very large) list is something we are likely to repeat in different contexts across Gutenberg, I'd love to see it solved in a way that worked very well for all cases.

None of this precludes producing a "better" solution in the future, particularly if new information presents itself. As I mentioned in #5921, changing the UI/UX of these components will need design first, and then be validated for accessibility. This work should be done before development.

File: lib/rest-api.php [hunk 3]
```diff
@@ -423,7 +425,12 @@ function gutenberg_ensure_wp_json_has_theme_supports( $response ) {
  * @param WP_REST_Request  $request  Request used to generate the response.
  */
 function gutenberg_handle_early_callback_checks( $response, $handler, $request ) {
-	if ( '/wp/v2/users' === $request->get_route() ) {
+	$routes = array(
+		'/wp/v2/blocks',
+		'/wp/v2/pages',
+		'/wp/v2/users',
+	);
+	if ( in_array( $request->get_route(), $routes ) ) {
```
Comment (felixarntz) [inline lib/rest-api.php]: This should perform a strict check.

**Review by felixarntz — DISMISSED** [review]
Just a minor strict code issue. I think the approach is fine. For core, this should obviously become part of the respective REST API controllers.

**Comment by danielbachhuber** [comment]
Going ahead and landing this. We can iterate on the UX as solutions become available.

**Comment by nylen** [comment]
@danielbachhuber rather than this "unlimited but not really unlimited" approach that uses -1 as a special value, I think it would be better to set a higher limit for users who have `edit_posts`. This should lead to much simpler code, and setting the limit to a value that is tested and known to work should also prevent bad behavior with extremely large numbers of objects.

**Comment by tofumatt** [comment]
I meant to update this PR to say I approve of the changes after seeing my comments addressed, so retroactive 👍 from me, sorry about that! 😄

**Comment by danielbachhuber** [comment]
> rather than this "unlimited but not really unlimited" approach that uses `-1` as a special value, I think it would be better to set a higher limit for users who have `edit_posts`. This should lead to much simpler code, and setting the limit to a value that is tested and known to work should also prevent bad behavior with extremely large numbers of objects.

@nylen Can you open new issue with the specifics of your proposal?
