### PR TITLE
Fix: block styles preview is not displayed

### LINKED ISSUE #43836: Block Styles: Preview is not displayed
### Description

When I activate the latest Gutenberg, the preview of the block styles does not appear.
If the Gutenberg plugin is deactivated, it appears correctly.

### Step-by-step reproduction instructions

1. Inserts blocks with a block style. (tables, images, button, etc.)
2. When the Gutenberg plugin is activated, confirm that no preview is shown at all when you mouse over the block style button.
3. When the Gutenberg plugin is disabled and the same operation is performed, confirm that the preview is displayed correctly.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/54422211/188315207-af944292-f83d-451b-8e27-52c5c31ccd77.mp4

### Environment info

- WordPress version: 6.1-alpha-53873
- Gutenberg version: 14.0.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fix ##43836
Follow-up on #42454

## What?
This PR fixes a problem with block style previews not displaying properly.

## Why?
In #42454, the block variation `example` is now referenced to enable a preview of template parts.
However, to preview regular block styles, the main block `example` must be referenced.

## How?
If the `example` of the block variation does not exist, the `example` of the main block is referenced. This will ensure that previews of block variations and block styles are displayed correctly.

## Testing Instructions
Open the Global Inserter and confirm that the template part preview is enabled as before.

inserter-preview

Insert a block with a block style and confirm that the preview displays correctly when you mouse over the style button.

style-preview

### CODE REVIEW

File: packages/block-editor/src/components/inserter/preview-panel.js [hunk 1]
```diff
@@ -27,7 +31,7 @@ function InserterPreviewPanel( { item } ) {
 							viewportWidth={ example?.viewportWidth ?? 500 }
 							blocks={
 								example
-									? getBlockFromExample( item.name, {
+									? getBlockFromExample( name, {
```
Comment (t-hamano) [inline packages/block-editor/src/components/inserter/preview-panel.js:30]: This is a small improvement 👍

File: packages/block-editor/src/components/inserter/preview-panel.js [hunk 2]
```diff
@@ -15,8 +16,11 @@ import BlockCard from '../block-card';
 import BlockPreview from '../block-preview';
 
 function InserterPreviewPanel( { item } ) {
-	const { name, title, icon, description, initialAttributes, example } = item;
+	const { name, title, icon, description, initialAttributes } = item;
 	const isReusable = isReusableBlock( item );
+	const hoveredItemBlockType = getBlockType( name );
+	const example = item.example || hoveredItemBlockType.example;
```
Comment (t-hamano) [inline packages/block-editor/src/components/inserter/preview-panel.js]: As far as I know, it is not explicitly stated that the example can be used for block variations.
To clarify what this code is intended to do, should I leave any comments here?

Comment (ramonjd) [reply packages/block-editor/src/components/inserter/preview-panel.js]: It might be worth adding a small comment to explain why you're checking for both, for sure 👍

File: packages/block-editor/src/components/inserter/preview-panel.js [hunk 3]
```diff
@@ -15,8 +16,11 @@ import BlockCard from '../block-card';
 import BlockPreview from '../block-preview';
 
 function InserterPreviewPanel( { item } ) {
-	const { name, title, icon, description, initialAttributes, example } = item;
+	const { name, title, icon, description, initialAttributes } = item;
 	const isReusable = isReusableBlock( item );
+	const hoveredItemBlockType = getBlockType( name );
```
Comment (ramonjd) [inline packages/block-editor/src/components/inserter/preview-panel.js]: Not a blocker, and I don't know if it even makes a huge difference, but it might be possible to avoid calling `getBlockType` if we check if `example` is set.

I was trying to do something like that over in https://github.com/WordPress/gutenberg/pull/43883/files#diff-2f239aff0c373f78c87b3d4930b1fd79277d01ee9a8ab407694fd5c4925d148fR21

**Review by ramonjd — APPROVED** [review]
This is working well for me. 

I think adding a comment to explain why the fallback example block exists would be a good idea before merge.

Code optimization mentioned in https://github.com/WordPress/gutenberg/pull/43837/files#r963186600 optional, probably not required.

**Comment by talldan** [comment]
Thanks for working on this. I think it could be a cleaner fix to add the `example` property to the `item` here:
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-styles/preview-panel.js#L20-L30

That way every place the `InserterPreviewPanel` is used would have the same consistent API, and the component is closer to being a purely presentational component.

**Comment by t-hamano** [comment]
@talldan 

Thanks for the review!

> That way every place the InserterPreviewPanel is used would have the same consistent API, and the component is closer to being a purely presentational component.

I think this makes sense.
It simplified the code and confirmed that the expected results continue to hold.

**Comment by ramonjd** [comment]
I retested this. Thanks @t-hamano and @talldan !!!

LGTM

## Before

Screen Shot 2022-09-06 at 7 59 25 pm

## After
Screen Shot 2022-09-06 at 7 59 38 pm

And a custom template in the site editor:


Screen Shot 2022-09-06 at 8 01 41 pm

**Comment by talldan** [comment]
Looks good to me too. Thanks for fixing the bug that I made 😄
