### PR TITLE
Announce block selection changes manually on windows

### LINKED ISSUE #24121: Accessibility regression: Firefox and NVDA don't announce the blocks in navigation mode any longer
**Describe the bug**

In WordPress 5.5 beta 3, the blocks aren't announced any longer by Firefox+NVDA in the block editor navigation mode.

Since WordPress 5.4, the block "breadcrumbs", i.e. the buttons used to navigate through the blocks when the editor is in "navigation mode", have gone through a substantial refactoring. To my understanding, they now use a Slot/Fill implementation where a Slot is placed above the blocks list and "filled" with the buttons. The focus is then moved to the buttons to allow navigation through the blocks. This still works with other screen readers but doesn't work any longer with Firefox+NVDA.

Here's two animated GIF to compare the behavior. The GIFs don't have audio but you can see what the screen reader announces in the visible "Speech viewer" on the right.

WordPress 5.5: only the first block encountered when entering the list of blocks is announced, all the other ones are ignored:

WordPress 5.4: all blocks are announced correctly:

**To reproduce**
- create a post with some blocks 
- on Windows, use latest Firefox and latest NVDA 
- navigate to the list of blocks
- one on a block, press Escape to switch the block editor to its own "navigation mode"
- you may need to press Escape twice: 1) to exit the screen reader "focus mode", 2) to switch the editor to "navigation mode"
- once in "navigation mode", press the Tab key or Shift + Tab to navigate through the blocks
- see the blocks are not announced
- repeat the steps above on WordPress 5.4
- see all the blocks are announced correctly

### PR DESCRIPTION
**Pull request by youknowriad**
refs #24121 

In NVDA on Windows, the block selection changes are not announced properly on Navigation Mode (Gutenberg's navigation mode).

As discussed on the issue, this solves the issue by announcing the blocks manually.

### CODE REVIEW

File: packages/block-editor/src/components/block-list/block-selection-button.js [hunk 1]
```diff
@@ -63,6 +73,13 @@ function BlockSelectionButton( { clientId, rootClientId, ...props } ) {
 	// Focus the breadcrumb in navigation mode.
 	useEffect( () => {
 		ref.current.focus();
+
+		// NVDA on windows suffers from a bug where focus changes are not announced properly
+		// See WordPress/gutenberg#24121 and nvaccess/nvda#5825 for more details
+		// To solve it we announce the focus change manually.
+		if ( isWindows() ) {
+			speak( label );
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-list/block-selection-button.js:81]: I also wondered whether I should announce something like `label + ', button'`

Comment (ntsekouras) [reply packages/block-editor/src/components/block-list/block-selection-button.js:81]: I think label is good enough.

**Review by ntsekouras — APPROVED** [review]
Thanks 👍
