### PR TITLE
Fix adding links from the autocompleter

### LINKED ISSUE #10496: Unable to insert links when clicking on an autocomplete suggesion
**Describe the bug**
When I insert a link nothing happens 

**To Reproduce**
1. add paragraph
2. select text and click add link
3. trigger the autocomplete dropdown
4. Click on a dropdown item

This has not been a problem in previous versions

**Screenshots**
linkinsert

**Desktop (please complete the following information):**
Chrome
4.0 rc

### PR DESCRIPTION
**Pull request by talldan**
Fixes #10496

## Description
When adding links from the autocompletion list, the `onClickOutside` handler on the LinkContainer popover was being triggered, causing the link not to be set and triggering closure of the popover.

This fix adds a clause at the start of the `onClickOutside` handler, detecting if the click originated from a autocomplete entry and returning early if so.

## How has this been tested?
- Manually tested adding links

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: packages/editor/src/components/rich-text/format-toolbar/link-container.js [hunk 1]
```diff
@@ -142,7 +147,13 @@ class LinkContainer extends Component {
 		event.preventDefault();
 	}
 
-	resetState() {
+	resetState( event ) {
+		// URLInput's autocomplete list can trigger onClickOutside on the link container's popover.
+		// Return early here if the click originated from one of the autocomplete suggestions.
+		if ( hasIn( event, [ 'target', 'classList' ] ) && includes( event.target.classList, 'editor-url-input__suggestion' ) ) {
```
Comment (talldan) [inline packages/editor/src/components/rich-text/format-toolbar/link-container.js]: It'd be nice to be able to avoid checking the class here, but I'm short of other ideas beyond having LinkContainer manage a ref to the URLInput's popover.

**Comment by iseulde** [comment]
1. What commit caused this regression?
2. Could a test be added to ensure we don't make this regression again?

**Comment by talldan** [comment]
Hi @iseulde - the change was added in the RichText refactor:
https://github.com/WordPress/gutenberg/pull/7890/files#diff-3fc799f44a8120d79cc3867b1d703822R179

Before that, there wasn't an `onClickOutside` handler and it was a lot harder to dismiss the popover.

I'll have a look at adding a case to the e2e links test.

**Comment by talldan** [comment]
Added an e2e test, it passes when using PUPPETEER_HEADLESS=false, but fails with PUPPETEER_HEADLESS=true. Seems like there are no autocomplete suggestions when running in headless mode? I tried adding a waitForSelector for an autocomplete suggestion, but it just hangs.

🤷‍♂️

File: packages/editor/src/components/rich-text/format-toolbar/link-container.js (hunk 1 above)
Comment (iseulde) [reply packages/editor/src/components/rich-text/format-toolbar/link-container.js]: Yes this is a bit unfortunate.

**Comment by iseulde** [comment]
Why are the link suggestions not in the same popover? That's a bit strange.

**Comment by talldan** [comment]
@iseulde - Not sure, they're separate components, and I imagine it's based on other autocomplete implementations. I'll try to think of some other ways to fix this today.

**Comment by talldan** [comment]
Hey @iseulde I've changed the implementation to use a ref now instead of checking class names. I did take a look at if it would be possible to un-nest the suggestions from their popover, but it was a bit too involved.

**Comment by iseulde** [comment]
Using ref.contains sounds better!

File: packages/editor/src/components/rich-text/format-toolbar/link-container.js [hunk 2]
```diff
@@ -170,7 +182,19 @@ class LinkContainer extends Component {
...
+	bindAutocompleteRef( ref ) {
+		this.autocompleteRef = ref;
+	}
+
+	resetState( event ) {
+		// The autocomplete suggestions list renders in a separate popover (in a portal),
+		// so onClickOutside fails to detect that a click on a suggestion occured in the
+		// LinkContainer. Detect clicks on autocomplete suggestions using a ref here, and
+		// return early if so.
+		if ( hasIn( this, [ 'autocompleteRef', 'contains' ] ) && this.autocompleteRef.contains( event.target ) ) {
```
[the remark this answers is not in the document]
Comment (talldan) [reply packages/editor/src/components/rich-text/format-toolbar/link-container.js]: If the user attempted to click outside of the popover when the autocomplete list hadn't been displayed, `this.autocompleteRef` would be unset. Checking for `contains` seems to be the safest option.

**Review by noisysocks — CHANGES_REQUESTED** [review]

**Review by noisysocks — APPROVED** [review]
Love it! Thanks for adding tests.

**Comment by talldan** [comment]
Hey @gziolo - this one is merged now. I think it might be something you wanted cherry-picked into v4.0?

Some of the selectors in the e2e tests have changed since 4.0, so you might get conflicts, this commit should help act as a guideline:
https://github.com/WordPress/gutenberg/pull/10500/commits/90b08b2014cb9dc673d920f24f6d1e7d73fd9fec

**Comment by gziolo** [comment]
Awesome, thanks @talldan for the heads up and doing the fix. Let's see how the release process goes :)
