### PR TITLE
Core Data: Bring back support for nested `_fields` values

### LINKED ISSUE #25078: Meta fields undefined after reuse commit
After bfbcc92a207dd6813967bf1eff667f0a1e1bcc56 (#19498, #15114), fetching a REST API field like `meta._wp_page_template` no longer works.

### Reproduction Steps

1. Edit a page and add a template to it. You may need to switch to a theme that has templates, like TwentyTwenty.
1. Make that meta field available in the REST API. Add this to an `mu-plugin`:
	```php
	register_post_meta(
		'page',
		'_wp_page_template',
		array(
			'show_in_rest' => true,
		)
	);
	```
1. Call the following from any block's `Edit` function:
	```js
	function test() {
		const args = {
			_fields: [
				'id',
				'slug',
				'meta._wp_page_template',
			],
		};
	
		const test = useSelect(
			( select ) => {
				return select( 'core' ).getEntityRecords( 'postType', 'page', args );
			},
			[]
		);
	
		console.log( null !== test ? test[ 0 ][ 'meta' ] : test );
	}
	```
1. Add that block to a post/page.
1. `git checkout bfbcc92a207dd6813967bf1eff667f0a1e1bcc56~1` and reload. You should see the meta data available in the console.
1. `git checkout bfbcc92a207dd6813967bf1eff667f0a1e1bcc56`, and reload. You should only see `null` in the console.

cc @youknowriad , @aduth , @mcsf

### PR DESCRIPTION
**Pull request by ryelle**
## Description
Fixes #25078 — The change to `getEntityRecords`'s use of _fields has broken nested meta field requests. In the API, you can pass nested fields for meta, ex: `wp-json/wp/v2/posts?_fields=title,meta.demo,id`, and this used to work for the getEntityRecords request.

It seems the change in #19498 introduced this:

https://github.com/WordPress/gutenberg/blob/8ba0a42e7d461722129c2c21b77b2625a1f8a255/packages/core-data/src/queried-data/selectors.js#L80-L82

Which is returning null, because it's testing for `item['meta.key']`, rather than `item.meta.key`. This PR switches to using the lodash functions `has`, `get`, and `set`, which support string keys like that. I've seen some moves away from lodash, but it seems like the most straightforward fix here.

## How has this been tested?
There's a new test case introduced in `packages/core-data/src/queried-data/test/selectors.js` which catches this case.

You can also test with the code snippet in #25078

## Types of changes
Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/core-data/src/queried-data/selectors.js [hunk 1]
```diff
@@ -76,12 +77,12 @@ function getQueriedItemsUncached( state, query ) {
 				// This accounts for the fact that queried items are stored by
 				// stable key without an associated fields query. Other requests
 				// may have included fewer fields properties.
-				const field = fields[ f ];
-				if ( ! item.hasOwnProperty( field ) ) {
+				const field = fields[ f ].split( '.' );
```
Comment (ryelle) [inline packages/core-data/src/queried-data/selectors.js:80]: If this value is left as a string, it matches an undefined value in the state— in my testing I had both `meta: { key: 'value' }` and `'meta.key': undefined` on `item`, and `get` matches the string key first, returning undefined. I'm not sure where that other key comes from, but preventing that would be a better fix for this workaround.

**Comment by youknowriad** [comment]
>  In the API, you can pass nested fields for meta, ex: wp-json/wp/v2/posts?_fields=title,meta.demo,id, and this used to work for the getEntityRecords request.

Just noting that before #25078 doing this would create subtle bugs where some components could receive "incomplete" entities data. Basically `_fields` was not considered as supported at all. It was more of a coincidence that it "appeared" to be working. That said, I'm not against adding support for nested fields into getEntityRecords.

**Comment by iandunn** [comment]
I tested the PR and it fixed the problem for me 👍🏻

**Review by youknowriad — APPROVED** [review]
Thanks
