### PR TITLE
Correctly handle case where 'post-thumbnails' is array of post types

### LINKED ISSUE #7547: Post Thumbnail panel display should respect supported post types
**Describe the bug**
At the moment, the Post Thumbnail panel is either displayed for all posts types or not displayed.
The editor should respect the second argument which defines the supported post type.

**To Reproduce**
1. Set `add_theme_support( 'post-thumbnails', array( 'post' ) );` in your theme `functions.php`
1. Edit a page
1. See the Post Thumbnail panel is displayed

**Expected behavior**
For post types for which there's no theme support for `post-thumbnails`, the Post Thumbmail panel should not be displayed.

**Desktop (please complete the following information):**
 - OS: macOS 10.13.5
 - Browser : Firefox 60.2

**Additional context**
- Gutenberg 3.1

### PR DESCRIPTION
**Pull request by danielbachhuber**
## Description

Updates `ThemeSupportCheck` to support scenario where `'post-thumbnails'` is an array of post types instead of a straight boolean value.

If `'post-thumbnails'` is an array of post types, then `postType` becomes a required argument for `PostFeaturedImageCheck` (which is the only check referring to `'post-thumbnails'` support.

Fixes #7547

## How has this been tested?

1. Add the following code snippet to your `functions.php`:

```
add_action( 'after_setup_theme', function(){
	remove_theme_support( 'post-thumbnails' );
	add_theme_support( 'post-thumbnails', array( 'post' ) );
}, 11 );
```

2. Verify the "Featured Image" Post Setting is only present on the Post screen and not a Page screen.

Post:

image

Page:

image

## Types of changes

Bug fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: editor/components/post-featured-image/check.js [hunk 1]
```diff
@@ -1,15 +1,30 @@
...
  * Internal dependencies
  */
 import PostTypeSupportCheck from '../post-type-support-check';
 import ThemeSupportCheck from '../theme-support-check';
 
 function PostFeaturedImageCheck( props ) {
+	const { postType } = props;
 	return (
-		<ThemeSupportCheck supportKeys="post-thumbnails">
+		<ThemeSupportCheck supportKeys="post-thumbnails" postType={ postType } >
```
Comment (aduth) [inline editor/components/post-featured-image/check.js]: Should it be the responsibility of the consumer to pass in the `postType` prop? Or should `ThemeSupportCheck` manage this itself?

Otherwise, how would we document what this prop is, and when it's to be passed? It's not really a "thing" so far as theme support goes. It's just one of many possible [miscellaneous `...$args`](https://developer.wordpress.org/reference/functions/add_theme_support/#parameters) which could be passed.

My first inclination was: Maybe we don't have `ThemeSupportCheck` and we just make `PostFeaturedImageCheck` a simple series of higher-order components using `withSelect` (and `getEditedPostAttribute`, `getThemeSupports`, `getPostTypeSupports`) and `ifCondition`. But there is a point to be made about consolidating where we consider something like "post thumbnails is possibly an array".

Which then makes me wonder: Should this be part of a selector? Something like `hasThemeSupport` which includes as part of its internal logic to consider the key and any special considerations to make.

Comment (danielbachhuber) [reply editor/components/post-featured-image/check.js]: Updated [per our Slack conversation](https://wordpress.slack.com/archives/C02QB2JS7/p1530126701000439) 80a27f18a

File: editor/components/theme-support-check/index.js [hunk 2]
```diff
@@ -1,16 +1,35 @@
...
 	const isSupported = some(
-		castArray( supportKeys ), ( key ) => get( themeSupports, [ key ], false )
+		castArray( supportKeys ), ( key ) => {
+			const supported = get( themeSupports, [ key ], false );
+			// 'post-thumbnails' can be boolean or an array of post types.
+			// In the latter case, we need to verify `postType` exists
+			// within `supported`. If `postType` isn't passed, then the check
+			// should fail.
+			if ( 'post-thumbnails' === key && isArray( supported ) ) {
+				if ( ! postType ) {
```
Comment (aduth) [inline editor/components/theme-support-check/index.js]: In what (real-world) conditions do you imagine this condition would be satisfied?

Aside: If we keep it, we don't have a test case for it.

Aside 2: If it were the case that `postType` were undefined / falsey, wouldn't the `includes` logic still be sufficient to return `false` ?

**Review by aduth — APPROVED** [review]
