### PR TITLE
Check if String.prototype.normalize exists

### LINKED ISSUE #6958: Paste: Pasting fails in IE11 on normalize method
Related: #6880

**Steps to reproduce:**

1. Open new post in IE11
2. Paste some copied text into a new paragraph

**Expected result:**

Text is pasted.

**Actual result:**

Nothing happens.

Error in console:

>[SCRIPT438: Object doesn't support property or method 'normalize'](https://github.com/WordPress/gutenberg/blob/a5aad35e8f4aabbf2374c58b2f75eb4b599ab59e/blocks/api/raw-handling/index.js#L94)

**Possible solution:**

- Polyfill `String#normalize` ([browser support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize#Browser_compatibility))
- Avoid calling `normalize` (reopens #433)

### PR DESCRIPTION
**Pull request by ellatrix**
## Description
Fixes #6958. I added a check instead of polyfill because I'm not sure if it's worth adding a dependency just for this. It's nice to have, but we don't have to add it in older browsers.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by noisysocks** [comment]
> I'm not sure if it's worth adding a dependency just for this

The dependency would only be loaded in Internet Explorer, no?

**Review by tofumatt — APPROVED** [review]
Works for me; I agree it's probably simpler to just not use this functionality in unsupported browsers. And IE 11 is reasonably old already.

File: blocks/api/raw-handling/index.js [hunk 1]
```diff
@@ -89,9 +89,12 @@ export default function rawHandler( { HTML = '', plainText = '', mode = 'AUTO',
 	}
 
 	// Normalize unicode to use composed characters.
+	// Unsupported in IE.
```
Comment (aduth) [inline blocks/api/raw-handling/index.js]: Should we clarify why it's okay that we don't normalize in IE? I'm not entirely clear about it myself.

Comment (tofumatt) [reply blocks/api/raw-handling/index.js]: Hopefully #7105 does the trick.
