### PR TITLE
Ensure editor body fits all notes

### LINKED ISSUE #72440: Floating notes sometimes cut off at page bottom
### Description

Fix an issue where a note can overlap the bottom of the screen, making it cut off and making the form submission or cancel button unreachable.

The floating notes mode arranges the notes to ensure there is no overlap and since https://github.com/WordPress/gutenberg/issues/72331 the logic ensures that the focused note is directly beside the active block, pushing other notes up and down to make room.

### Step-by-step reproduction instructions

There are two ways I have found to reproduce this issue:

### Method 1
The simplest is just to add a really long note thread to a short post - 

1. Create a post with several short blocks
2. add a very long comment to a post
3. Try adding long replies

Here is a screencast of this reproduced (note the cutoff at bottom right):

https://github.com/user-attachments/assets/709142f6-50d7-4d0e-8562-28d6244f2e97

### Method 2
Adding a long comment to a block near the bottom of the page

1. create a post with many short blocks
2. add a note to a block near the bottom
3. try opening that note and adding a long reply

Here is a screencast of this bug reproduced:

https://github.com/user-attachments/assets/8729fc25-5502-4e84-a0f5-bcbfb94890bb

**Actual Result**
The block stays pinned next to the block and text the floating thread is cut off at the bottom as the size grows.

**Desired Result**
The block bottom stays slightly above the bottom edge and grows on top as the size changes, pushing other blocks up.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### LINKED ISSUE #72507: Overflowing Notes and visibility in the block sidebar
### Description

When Note threads contain lengthy notes or multiple replies, the sidebar can overflow its available vertical space.  This creates usability issues, especially for Notes positioned near the bottom of the screen, where users cannot easily view or navigate through longer discussions.

At present:

* Long Notes can push newer ones out of view.
* There is no built-in mechanism for scrolling within individual long Notes.
* When replying to a large Note, it is difficult to scroll back to the previous Note for context.

This issue serves as an overarching discussion and implementation tracker for managing overflowing Notes and improving scrolling behavior in the sidebar.

Additional context form @jasmussen in https://github.com/WordPress/gutenberg/pull/72454#issuecomment-3421332648:

> I wouldn't extend the canvas to fit the comments if we can find an alternative. I don't think we character-limit notes, so inevitably they can become very long, and I believe how we elide and collapse is going to be something we evolve over time, such as always collapsing comments with a "read more" when they are longer than n characters, and even collapsing threads when there are more than n comments.
>
> But for the immediate future, I wonder if we can apply a max-height to comments, and then allow them to scroll. We might need canvas extension for extreme cases, after all, but we probably still need to pair that with scrolling.

Additional context form @Mamaduka in https://github.com/WordPress/gutenberg/pull/72454#issuecomment-3421612870:

> Currently, if you have notes with a large body of text, some notes for remaining blocks might not be visible. Also, when replying to a large note, there is no way to scroll up to the previous comment, which will make actual replies harder.

### Open Questions

1. What should the default `max-height` value be for Notes before scrolling activates?
2. Should long Notes collapse automatically behind a “Read more” button, or should that come later?
3. Should entire threads (with many Notes) collapse by default, or only individual Notes?
4. How does scrolling inside Notes interact with the main sidebar scroll, and should nested scroll areas be avoided if possible?

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by adamsilverstein**
Fixes #72440
Fixes https://github.com/WordPress/gutenberg/issues/72507

Alternative to https://github.com/WordPress/gutenberg/pull/72454

Keeps the editor minimum height just tall enough to fit all notes.

### Before

https://github.com/user-attachments/assets/1ab32f9f-3791-4948-bde9-a61b8b328f33

### After

https://github.com/user-attachments/assets/ecfa748b-9a3d-4f5e-bfb3-ca971b34d516

### CODE REVIEW

File: packages/editor/src/components/collab-sidebar/comments.js [hunk 1]
```diff
@@ -271,6 +276,20 @@ export function Comments( {
 					threadTop: threadTop + additionalOffset,
 				};
 			}
+
+			// Ensure the editor has enough height to scroll to all notes.
+			// last note top plus height to determine the bottom position.
+			const iframe = document.querySelector(
```
Comment (adamsilverstein) [inline packages/editor/src/components/collab-sidebar/comments.js]: maybe this should us `getEditorRegion` from `packages/block-editor/src/utils/get-editor-region.js`?

**Comment by jeffpaul** [comment]
This approach more closely mimics Google Docs where lengthy comments scroll the doc content above the fold.  I had originally thought that wouldn't look/work well in the block editor but that After video seems pretty fine to me.

Two questions @adamsilverstein is what happens if you have a drawer active below the post content (e.g. Yoast) as well as what happens if you scroll down past the post content and then click on a comment (will it scroll you back up to where the related block begins such that its back in frame or will the block and post content area still be above the fold)?

**Comment by adamsilverstein** [comment]
> This approach more closely mimics Google Docs where lengthy comments scroll the doc content above the fold.  

Exactly!

>
> Two questions  what happens if you have a drawer active below the post content (e.g. Yoast) 

the code only sets the minimum height (min-height) for the editor frame body, so if an active drawer needs more space that will not be affected by this at all.


> as well as what happens if you scroll down past the post content and then click on a comment (will it scroll you back up to where the related block begins such that its back in frame or will the block and post content area still be above the fold)?

I'm not changing that behavior - when you click on a comment it will scroll to the related block and pin alongside it. threads above will be pushed away above. New with this PR, to reach the bottom, you would just scroll down (in trunk, you can't reach the bottom, its cut off). This part might not be working perfectly in the PR yet, I'm going to work on that more.

**Comment by adamsilverstein** [comment]
> This part might not be working perfectly in the PR yet, I'm going to work on that more. 

I was able to correct the glitches and simplify the calculation in https://github.com/WordPress/gutenberg/pull/72811/commits/e616b5e810e4bd76a72b5350288040cd4c40c8ee. Previously I wasn't taking into account the editor scroll position in the calculations.

This resolves all the edge cases, give it a [test in Playground](https://playground.wordpress.net/?gutenberg-pr=72811#%7B%22landingPage%22:%22/wp-admin/%22,%22features%22:%7B%22networking%22:true%7D,%22steps%22:%5B%7B%22step%22:%22login%22,%22username%22:%22admin%22,%22password%22:%22password%22%7D%5D%7D).

**Comment by adamsilverstein** [comment]
Looking at the codebase, I think we could expose a private API from the editor to set the min-height, this would make the code more reactive. What do you think?

**Comment by adamsilverstein** [comment]
I took a pass at converting the code to use a private API instead of manipulating the DOM directly in https://github.com/WordPress/gutenberg/pull/72811/commits/2e746baa42d91bcec85257b1f93bd3368fda5af9 and https://github.com/WordPress/gutenberg/pull/72811/commits/c854e936199fcea2b12f584b169616c53915ccff. We still need to include the scroll position in the calculation, but we can do that right where its available which is cleaner and more reactive.

**Comment by adamsilverstein** [comment]
Oops, those last commits were off, re-working shortly.

**Comment by adamsilverstein** [comment]
Ok, the reactive implementation is restored.

**Review by jasmussen — APPROVED** [review]
Despite my prior skepticism to extending the canvas, this is clearly the best solution yet:

state

Apologies for the detour. This works very well, kudos, nice work.

I do think there's a point in the future where we elide comments with "Read more" links and collapse long threads, but that's not today, and with this PR the bases are covered.

Approving from an experience perspective, it could use a code gut check by the other folks pinged.

**Comment by Mamaduka** [comment]
Pushed some refactorings:

* Replaced custom context with private store action/selector.
* Updated `calculatedMinHeight` memo to use localRef for getting `scrollTop`, in a more React-way manner.

**Comment by adamsilverstein** [comment]
> Pushed some refactorings:
> 
> * Replaced custom context with private store action/selector.
> * Updated `calculatedMinHeight` memo to use localRef for getting `scrollTop`, in a more React-way manner.

Thanks for the refactoring @Mamaduka - nice improvements! I tested this again and everything works as expected.  

I was only able to trigger the wrong height in a few edge cases I couldn't reproduced and in every case all notes were fully visible (slightly too much space was added).

**Comment by stokesman** [comment]
I briefly tested with playground and found that when adding notes to a block before or after one with a long note there was some behavior that surprised me. The worst was adding a note to a block after one with the long note, where the note was only accessible in the non-floating sidebar. Here’s a recording:

https://github.com/user-attachments/assets/1b00b7f0-a894-4b63-aced-0d2a336d2a08

This seems like it should work quite well though. Good work!

**Comment by adamsilverstein** [comment]
@stokesman Thanks for testing! I was not able to reproduce the behavior you saw and I'm suspicious the playground build is out of date. Here is my screen recording for the record, maybe I missed a step:

https://github.com/user-attachments/assets/19194944-655a-446e-9dad-00003e2231b5

**Comment by adamsilverstein** [comment]
@Mamaduka the backport bot failed so worked on a manual backport for the 6.9 branch, can you please review - should be the same changes as this PR: https://github.com/WordPress/gutenberg/pull/72886

**Comment by adamsilverstein** [comment]
Backported in https://github.com/WordPress/gutenberg/pull/72886
