### PR TITLE
Group: Fix the 'templateLock' attribute type in deprecations

### LINKED ISSUE #49159: Broken Deprecation on `core/block` deletes `templateLock` when `false`
### Description

The [latest deprecation migration for a `core/group` block](https://github.com/WordPress/gutenberg/blob/b7c693b57df1cb89ec2f15ef25cfd2a6d816ecf3/packages/block-library/src/group/deprecated.js#L45-L129) discards the `templateLock` set on that block if the value isn't one of the string values but the also valid `false`.

### Step-by-step reproduction instructions

1. Start a new post
2. Switch to the code editor
3. Paste the following:
   ```
   <!-- wp:group {"templateLock":false} -->
   <div class="wp-block-group"></div>
   <!-- /wp:group -->
   ```
4. Click outside the code editor to apply the deprecation migrations and see the `templateLock` gets removed instantly turning this into:
   ```
   <!-- wp:group -->
   <div class="wp-block-group"></div>
   <!-- /wp:group -->
   ```
---

If you want to see a more real world flow:

1. Create a post with a `core/group` block that doesn't have layout set but a `templateLock` value of `false`.
   There are two ways how to do this:
   - Create the block in an old WP version prior to the default layout, I think 6.0 should already do.
   - Manually edit the `post_content` in the database so it looks like this:
   ```
   <!-- wp:group {"templateLock":false} -->
   <div class="wp-block-group"></div>
   <!-- /wp:group -->
   ```
6. Open the post in WP 6.1.
7. Switch to Code Editor and see `post_content` now looks like this:
   ```
   <!-- wp:group -->
   <div class="wp-block-group"></div>
   <!-- /wp:group -->
   ```

### Screenshots, screen recording, code snippet

Video demonstrating the issue:

[templateLock.webm](https://user-images.githubusercontent.com/2428517/225875396-eb760b64-67d2-489a-ab09-4c484411eb26.webm)

---

The problem seems to be the [deprecation migration to add the default layout](https://github.com/WordPress/gutenberg/blob/b7c693b57df1cb89ec2f15ef25cfd2a6d816ecf3/packages/block-library/src/group/deprecated.js#L45-L129), specifically the fact that the `templateLock` attribute is wrongly defined as string only:

https://github.com/WordPress/gutenberg/blob/b7c693b57df1cb89ec2f15ef25cfd2a6d816ecf3/packages/block-library/src/group/deprecated.js#L52-L54

while it can also be bool:

https://github.com/WordPress/gutenberg/blob/b7c693b57df1cb89ec2f15ef25cfd2a6d816ecf3/packages/block-library/src/group/block.json#L15-L18

This then leads to the bool attribute being dropped since it is considered invalid but any other string value like `all` does indeed survive:

[templateLock2.webm](https://user-images.githubusercontent.com/2428517/225876830-0271228a-4bb9-4d49-b7ef-6b63304120e0.webm)

---

This is further proven by the fact that adding this snippet does resolve the issue at hand:

```
wp.hooks.addFilter(
	'blocks.registerBlockType',
	'fix/template-lock',
	(settings, name) => {
		if(
			name==='core/group'
			&&
			settings.deprecated.length === 5
			&&
			settings.deprecated[0].attributes?.templateLock?.type === 'string'
		){
			settings.deprecated[0].attributes.templateLock.type = [ "string", "boolean" ];
			settings.deprecated[0].attributes.templateLock.enum =  [ "all", "insert", "contentOnly", false ];
		}
		return settings;
	}
);
```

### Environment info

- WordPress 6.1.1, without Gutenberg as well as with Gutenberg 15.3.1 enabled
- Firefox
- Desktop with Ubuntu 22.04

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Fixes #49159.

PR updates the `templateLock` type in the latest block deprecation to avoid losing the attribute when it's set to `false`.

## Testing Instructions
1. Open a Post or Page.
2. Switch to the code editor
3. Paste the following:
   ```
   <!-- wp:group {"templateLock":false} -->
   <div class="wp-block-group"></div>
   <!-- /wp:group -->
   ```
4. Confirm the `templateLock` boolean value is retained.

### CODE REVIEW

File: packages/block-library/src/group/deprecated.js [hunk 1]
```diff
@@ -50,7 +50,8 @@ const deprecated = [
 				default: 'div',
 			},
 			templateLock: {
-				type: 'string',
+				type: [ 'string', 'boolean' ],
+				enum: [ 'all', 'insert', false ],
```
Comment (Mamaduka) [inline packages/block-library/src/group/deprecated.js:54]: I've omitted `contentOnly` since it was introduced after this deprecation.

**Review by ntsekouras — APPROVED** [review]
Looks good, thanks!
