### PR TITLE
wp-build: Fix dynamic base-styles import

### LINKED ISSUE #74433: wp-build: SCSS compilation fails with pnpm due to hardcoded node_modules path
Originally detected in #74135 

## Description

The `@wordpress/build` package fails to compile SCSS files when used in a pnpm monorepo because the SASS load paths are hardcoded to assume npm's hoisted `node_modules` structure.

When using pnpm (which doesn't hoist dependencies by default), SCSS imports like `@import "@wordpress/base-styles/mixins"` fail because the SASS compiler can't find the dependency in the expected location.

**Expected behavior:** SCSS compilation should work regardless of the package manager used.

**Actual behavior:** SCSS compilation fails with errors like:
```
Error: Can't find stylesheet to import.
  @import "@wordpress/base-styles/mixins";
```

## Resproduction link

- Go to https://codesandbox.io/p/devbox/8h24pj
- Open terminal (<kbd>Ctrl</kbd> + <kbd>`</kbd>)
- Run `pnpm install && pnpm run build`

## Step-by-step reproduction instructions

1. Create a new pnpm monorepo:
```bash
mkdir my-wp-plugin && cd my-wp-plugin
pnpm init
```

2. Create `pnpm-workspace.yaml`:
```yaml
packages:
  - "packages/*"
```

3. Create a package at `packages/my-editor/package.json`:
```json
{
  "name": "@my-plugin/editor",
  "version": "1.0.0",
  "wpScript": true,
  "main": "build/index.cjs",
  "module": "build-module/index.js",
  "dependencies": {
    "@wordpress/base-styles": "^5.0.0"
  }
}
```

4. Create `packages/my-editor/src/index.js`:
```js
export const hello = 'world';
```

5. Create `packages/my-editor/src/style.scss`:
```scss
@import "@wordpress/base-styles/mixins";

.my-editor {
  @include break-small() {
    padding: 16px;
  }
}
```

6. Add root `package.json` config:
```json
{
  "name": "my-wp-plugin",
  "private": true,
  "wpPlugin": {
    "scriptGlobal": "myPlugin",
    "packageNamespace": "my-plugin"
  },
  "devDependencies": {
    "@wordpress/build": "^0.4.0"
  }
}
```

7. Install dependencies and build:
```bash
pnpm install
pnpm exec wp-build
```

**Result:** Build fails with the following error:

```
🔨 Building packages...

📝 Phase 1: Transpiling packages...

✘ [ERROR] Error: Can't find stylesheet to import.
  ╷
1 │ @import "@wordpress/base-styles/mixins";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  - 1:9  root stylesheet [plugin sass-plugin]

❌ Build failed: Error: Build failed with 1 error
```

This happens because `@wordpress/base-styles` is in `packages/editor/node_modules/@wordpress/base-styles` (pnpm's non-hoisted structure), but `@wordpress/build` only looks in the root `node_modules/`.

## Root Cause

In [`packages/wp-build/src/build.mjs`](https://github.com/WordPress/gutenberg/blob/3cd52a40505eef031cba9d522ef8d94096f08281/packages/wp-build/src/build.mjs#L119), the SASS load paths are hardcoded:

https://github.com/WordPress/gutenberg/blob/3cd52a40505eef031cba9d522ef8d94096f08281/packages/wp-build/src/build.mjs#L119

This assumes:
1. All dependencies are hoisted to the root `node_modules` (npm behavior)
2. `@wordpress/base-styles` lives in `packages/base-styles` (Gutenberg's internal structure)

Neither assumption holds for external consumers using pnpm.

## Proposed Solution

Use `@manypkg/get-packages` to dynamically discover all workspace packages and include each package's `node_modules` directory in the SASS load paths:

```javascript
import { getPackages } from '@manypkg/get-packages';

async function getSassLoadPaths() {
  const { packages, rootDir } = await getPackages( ROOT_DIR );

  return [
    // Each workspace package's node_modules (for pnpm's non-hoisted deps)
    ...packages.map( ( pkg ) => path.join( pkg.dir, 'node_modules' ) ),
    // Root node_modules
    path.join( rootDir, 'node_modules' ),
    // Direct path to base-styles for @wordpress/base-styles imports
    path.join( PACKAGES_DIR, 'base-styles' ),
  ];
}
```

This ensures SCSS compilation works with:
- npm (hoisted dependencies)
- pnpm (non-hoisted, isolated dependencies)
- yarn (various hoisting modes)

## Environment info

- `@wordpress/build` version: 0.4.0 (trunk)
- Node.js: 20.x
- pnpm: 9.x / 10.x

## Checklist

- [x] I have searched existing issues in the repo
- [x] I have tested with all plugins deactivated except Gutenberg

### PR DESCRIPTION
**Pull request by manzoorwanijk**
## What?

Closes #74433 for #74309

Fix SCSS compilation in `@wordpress/build` when used with pnpm or other package managers that don't hoist dependencies.

## Why?

The current implementation uses hardcoded SASS load paths:

```javascript
loadPaths: [ 'node_modules', path.join( PACKAGES_DIR, 'base-styles' ) ];
```

This assumes all dependencies are hoisted to the root `node_modules`, which is npm's default behavior. However, pnpm uses a stricter, non-hoisted dependency structure where each package's dependencies are installed in their own `node_modules` directory.

When an external consumer uses `@wordpress/build` with pnpm, SCSS imports like `@import "@wordpress/base-styles/mixins"` fail with:

```
Error: Can't find stylesheet to import.
  @import "@wordpress/base-styles/mixins";
```

This happens because `@wordpress/base-styles` is located in `packages/my-package/node_modules/` (pnpm's structure) rather than the root `node_modules/`.

## How?

Use `NodePackageImporter` from `sass-embedded` combined with explicit `loadPaths` for package resolution:

1. Added `NodePackageImporter` from `sass-embedded` which uses Node's module resolution algorithm to find packages - this works with any package manager (npm, pnpm, yarn)
2. Created `createStyleBundlingPlugins(workingDir)` factory function that configures both:
    - `importers: [ new NodePackageImporter( workingDir ) ]` - for package resolution
    - `loadPaths` with package's `node_modules`, root `node_modules`, and `base-styles` directory - for fallback resolution and local imports like `@use "mixins"`
3. Updated all usages in `transpilePackage()`, `compileStyles()`, and `buildRoute()` to pass the working directory

This ensures SCSS compilation works with:

-   npm (hoisted dependencies in root `node_modules`)
-   pnpm (isolated dependencies in package `node_modules`)
-   yarn (various hoisting modes)

## Testing Instructions

1. In this PR's branch, register `@wordpress/build` for linking:
    ```bash
    cd packages/wp-build
    pnpm link
    ```
2. Download the CodeSandbox reproduction: https://codesandbox.io/p/devbox/8h24pj
3. Run `pnpm install`
4. Run `pnpm build` - this will fail with:
    ```
    Error: Can't find stylesheet to import.
      @use "@wordpress/base-styles/variables";
    ```
5. Link the `@wordpress/build` from this PR:
    ```bash
    pnpm link @wordpress/build
    ```
6. Run `pnpm build` again - it should now successfully compile the SCSS

### Testing Instructions for Keyboard

N/A - This is a build tooling change with no UI.

## Screenshots or screencast

N/A - This is a build tooling change.

### CODE REVIEW

**Comment by manzoorwanijk** [comment]
@youknowriad On a side note, that [@manypkg/get-packages](https://www.npmjs.com/package/@manypkg/get-packages) and the [related packages](https://github.com/Thinkmill/manypkg/tree/327e4ac7673134f4d49b8414679849daa2e2eaef/packages) are robust tools and can replace/simplify the utility functions in [`wp-build/src/package-utils.mjs`](https://github.com/WordPress/gutenberg/blob/3cd52a40505eef031cba9d522ef8d94096f08281/packages/wp-build/src/package-utils.mjs).

**Comment by jsnajdr** [comment]
Few months ago I migrated another big project from `npm` to `pnpm` and encountered a similar problem with `SassPlugin` `loadPaths`. There I solved it with removing `loadPaths` option completely and adding `importers` option like:
```js
sassPlugin( {
  importers: [ new NodePackageImporter( absWorkingDir ) ]
} )
```
where `NodePackageImporter` is imported from `sass-embedded` and the `absWorkingDir` is the directory where we're working, i.e., the directory of the package we're building.

Could you try if the same solution works here, too?

**Comment by manzoorwanijk** [comment]
> Few months ago I migrated another big project from `npm` to `pnpm` and encountered a similar problem with `SassPlugin` `loadPaths`. There I solved it with removing `loadPaths` option completely and adding `importers` option

IIRC, `NodePackageImporter` works only for package imports, not the relative imports inside packages.

**Comment by jsnajdr** [comment]
> `NodePackageImporter` works only for package imports, not the relative imports inside packages.

How are relative imports related to this PR? The PR descriptions only mentions resolving imports like `@wordpress/base-styles` from the right `node_modules`. And with this `NodePackageImporter` should be able to help.

**Comment by manzoorwanijk** [comment]
> How are relative imports related to this PR? The PR descriptions only mentions resolving imports like `@wordpress/base-styles` from the right `node_modules`. And with this `NodePackageImporter` should be able to help.

I mean, the internal imports inside base-styles package.

Let me still give it a try.

**Comment by manzoorwanijk** [comment]
`NodePackageImporter` works great. Thank you for the pointer. I have updated the PR and the description.

File: packages/wp-build/lib/build.mjs [hunk 1]
```diff
@@ -107,26 +108,59 @@ const wordpressExternalsPlugin = createWordpressExternalsPlugin(
...
+	return {
+		importers: [ new NodePackageImporter( workingDir ) ],
+		// loadPaths for resolving @wordpress/base-styles imports and local base-styles imports
+		loadPaths: [
+			// Package's own node_modules (for pnpm isolated deps)
+			path.join( workingDir, 'node_modules' ),
+			// Root node_modules (for npm hoisted deps)
+			path.join( ROOT_DIR, 'node_modules' ),
+			// For local imports like @use "mixins"
+			path.join( PACKAGES_DIR, 'base-styles' ),
```
Comment (jsnajdr) [inline packages/wp-build/lib/build.mjs:130]: These `loadPaths` should be redundant:
- `${workingDir}/node_modules` is covered by `NodePackageImporter`, that's what its `workingDir` param is for
- `${ROOT_DIR}/node_modules` should also be covered, the root dir is always a parent of `workingDir`, the resolution algorithm will search there
- `${PACKAGES_DIR}/base-styles` is probably the only one that's needed. But it's a workaround around the fact that packages don't declare a `base-styles` dependency although they should. If it was correctly declared, it would be present, as a symlink to `packages/base-styles`, in either the `workingDir` or `ROOT_DIR` `node_modules` folder.

By the way, how are you testing this when there's still no pnpm on this branch? Together with all the other pnpm changes?

Comment (manzoorwanijk) [reply packages/wp-build/lib/build.mjs:130]: I am testing this with the codesandbox repo I shared in the description and in the linked issue.

Comment (manzoorwanijk) [reply packages/wp-build/lib/build.mjs:130]: After testing, I found that `NodePackageImporter` only handles URLs with the `pkg:` scheme (e.g., `@use "pkg:@wordpress/base-styles/variables"`), not the standard `@use "@wordpress/base-styles/variables"` syntax that the codebase currently uses.

From the [sass-embedded documentation](https://sass-lang.com/documentation/js-api/classes/nodepackageimporter/):

> This importer resolves `pkg:` URLs to the exports defined in the `package.json` file of the package.

So the `loadPaths` are still necessary for resolving standard `@use "@wordpress/..."` imports.

image

Comment (manzoorwanijk) [reply packages/wp-build/lib/build.mjs:130]: Now, after #74450 🚀 , you can directly test this branch in the devbox by updating the dependency to this branch and running `pnpm install && pnpm build`.

```json
"devDependencies": {
  "@wordpress/wp-build": "github:WordPress/gutenberg#fix/wp-build-base-style-import&path:packages/wp-build"
}
```

Comment (aduth) [reply packages/wp-build/lib/build.mjs:130]: How unreasonable would it be to impose a requirement to use `pkg:` prefixes so that we can fully adopt Sass's native support for importing Node module styles and move away from default `node_modules` resolution?

Comment (manzoorwanijk) [reply packages/wp-build/lib/build.mjs:130]: > How unreasonable would it be to impose a requirement to use `pkg:` prefixes so that we can fully adopt Sass's native support for importing Node module styles and move away from default `node_modules` resolution?

It may be difficult for beginners to figure out the build errors in such cases. But, if we can improve the error messages for those, then it should be fine.

Comment (jsnajdr) [reply packages/wp-build/lib/build.mjs:130]: > I found that `NodePackageImporter` only handles URLs with the `pkg:` scheme

That's strange because we have projects with this exact same `esbuild-sass-plugin` and `NodePackageImporter` setup and they are able to resolve imports like this:
```
@use "@wordpress/base-styles/variables";
```
I was debugging the rather weird `sass-embedded` code for this ([importer-registry.js](https://github.com/sass/embedded-host-node/blob/main/lib/src/importer-registry.ts)) a few months ago and I vaguely remember there were some gotchas. The code doesn't ever mention `pkg:` explicitly. I think `file:` URLs or things that map to file URLs are also fine.

Let me have a look at this in the morning.

**Review by jsnajdr — APPROVED** [review]
This looks good. I believe the `loadPaths` should be possible to eliminate, but that's a minor fine-tuning we can do at any time later. The SASS resolution is quite esoteric, similar to classic Node.js resolution but not identical, and difficult to debug.

**Comment by manzoorwanijk** [comment]
I sometimes forget to copy the props into commit message before merge 🤦

**Comment by jsnajdr** [comment]
> I sometimes forget to copy the props into commit message before merge

No worries, you as the author are the most important contributor here 🙂

**Comment by SirLouen** [comment]
> I sometimes forget to copy the props into commit message before merge 🤦

I have a trick to avoid this. Instead of using the commits as a description that are added automatically, force yourself to try to write a line or two about what you did, and you will never  forget :) 

> No worries, you as the author are the most important contributor here 🙂

Not the case here, but every so often the “author” is almost the least relevant player in a PR. In many places, reviewing is higher in the hierarchy than coding (more nowadays that AI is all over the place). So I would be careful with this, to not demotivate contributors.
