### PR TITLE
Multi select: onSelectionStart may trigger too much

### LINKED ISSUE #18881: Focus issue when using select tool on nested blocks
## Description
If you click repeatedly in just the right spot, you can get some weird behavior while using the select tool. Clicking too quickly causes the block to become invalid, and then if you try to click a block again, the editor crashes.

select-mode-weirdness
image

## How to reproduce
1. Create a Group block.
2. Create a Columns block inside the Group block.
3. Use the Select tool to select the Columns block.
4. Click in the area shown in the GIF; if you click in the right spot, you will select the Group block.
5. Keep clicking in the same spot. You will alternate between selecting the Columns and the Group block.
6. Try clicking more quickly; the block will become invalid. If you keep clicking, the editor will crash.

## Environment
- WordPress 5.4-alpha-46810
- Gutenberg `master` as of https://github.com/WordPress/gutenberg/commit/0303999ddc0c798b1c0e3b1a6b750d1f26319b69
- Using Dissenter browser 0.70 (based on Chromium 78)

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #18881.
This fixes a JS error.

## How has this been tested?

Create a column block with two inserters.
Select one of the empty columns.
Escape to enter navigation mode.
Click right _above_ the inserter in the other column. You'll see that the breadcrumb doesn't show because `isMultiSelecting` is `true`. Strange!
Now select again above the first inserter. JS error!

Why is `isMultiSelecting` `true`? It looks like `onMouseUp` is not triggering for some reason, so when the mouse leaves the block, we think that the pointer is pressed. I removed this logic in favour of a more reliable way to check if a button is pressed. `event.buttons` will tell us what button is pressed. We only want to trigger multi selection if the primary button is pressed.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

File: packages/block-editor/src/components/block-list/block.js [hunk 1]
```diff
@@ -372,34 +370,24 @@ function BlockListBlock( {
 				event.preventDefault();
 			}
 
-		// Avoid triggering multi-selection if we click toolbars/inspectors
-		// and all elements that are outside the Block Edit DOM tree.
-		} else if ( blockNodeRef.current.contains( event.target ) ) {
```
Comment (ellatrix) [inline packages/block-editor/src/components/block-list/block.js]: Not sure why this condition is here... `onMouseDown` is already listens to the block-edit node.

File: packages/block-editor/src/components/block-list/block.js [hunk 2]
```diff
@@ -372,34 +370,24 @@ function BlockListBlock( {
...
-	const onMouseUp = () => {
-		isPointerDown.current = false;
-	};
-
-	const onMouseLeave = () => {
-		if ( isPointerDown.current ) {
+	const onMouseLeave = ( event ) => {
+		// The primary button must be pressed to initiate selection.
+		// See https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons
+		if ( event.buttons === 1 ) {
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-list/block.js]: Looks like it might have some issues in Firefox in Mac and won't work in chrome Android https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons ?

File: packages/block-editor/src/components/block-list/block.js (hunk 1 above)
Comment (youknowriad) [reply packages/block-editor/src/components/block-list/block.js]: A long time ago, multiselection used to be triggered super easily while clicking on toolbars, link controls, modals... It might not be the case anymore but we should ensure that it's not being triggered inadvertently.

File: packages/block-editor/src/components/block-list/block.js (hunk 2 above)
Comment (ellatrix) [reply packages/block-editor/src/components/block-list/block.js]: Oh no :)

Comment (ellatrix) [reply packages/block-editor/src/components/block-list/block.js]: Ok, added a fallback. :)

File: packages/block-editor/src/components/block-list/block.js [hunk 3]
```diff
@@ -439,7 +429,7 @@ function BlockListBlock( {
 		! showEmptyBlockSideInserter &&
 		! isPartOfMultiSelection &&
 		! isTypingWithinBlock;
-	const shouldShowBreadcrumb = isNavigationMode && isSelected && ! isMultiSelecting;
```
Comment (ellatrix) [inline packages/block-editor/src/components/block-list/block.js]: This was needed previously to hide the breadcrumb on hover, but this is now gone.

File: packages/block-editor/src/components/block-list/block.js [hunk 4]
```diff
@@ -380,10 +380,12 @@ function BlockListBlock( {
 		}
 	};
 
-	const onMouseLeave = ( event ) => {
-		// The primary button must be pressed to initiate selection.
+	const onMouseLeave = ( { which, buttons = which } ) => {
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-list/block.js]: So I haven't tested to check whether it creates an issue or not but if I understand properly the mozilla docs, the `buttons` property could always return `0` in MacOS which means no fallback to which?

Comment (ellatrix) [reply packages/block-editor/src/components/block-list/block.js]: Hm, that's true. Do you think we should do `buttons || which` instead? So if `buttons` says no button is pressed, we check `which` as well.

Comment (youknowriad) [reply packages/block-editor/src/components/block-list/block.js]: It seems more logical.

Comment (ellatrix) [reply packages/block-editor/src/components/block-list/block.js]: Done :)

**Comment by youknowriad** [comment]
Not sure if I'm doing something wrong, but multi-selection is not really working properly in this branch. It selects just a sub part of the blocks I selected. Sometimes it doesn't trigger at all.

And in master, I've not been able to reproduce the issue using the steps in the description.

**Comment by ellatrix** [comment]
@youknowriad I fixed the partial selection issue.

This is a recording of the error. It's a bit hard to reproduce. I can't trigger it all the time either. I probably has something to do with the block rerendering and not resetting `isPointerDown` on `mouseup` between unmounting and remounting.

**Comment by ellatrix** [comment]
error

**Comment by ZebulanStanphill** [comment]
@ellatrix That GIF looks a lot like #18881.

Speaking of which, it looks like this PR fixes #18881! Well, it mostly fixes it. Instead of weirdly shifting focus back to the parent block, clicking in the "magic spot" unselects the block (or clicks the document background; I'm not sure). That doesn't really make sense either, but it's definitely an improvement over invalidating the block and crashing the editor.

I checked, and the unselects-the-block-when-you-click-in-the-magic-spot behavior is also present Gutenberg 7.0.0, and even earlier in WordPress 5.3. So the remaining issue is one that has been around for a long time, and is probably related to where the various block edit markup divs overlap (or rather, where they don't overlap).

Notably, the specific issue described in #18881 was already fixed in this PR before the latest commit, so I think the one in the GIF posted above isn't the same issue, though it is likely related somehow.

As for the issue that @youknowriad was experiencing, I was having the same issue until the latest commit. In a post like this:

- Paragraph (A)
- Group
  - Columns
    - Column
    - Column
- Group
  - Columns
    - Column
      - Paragraph (B)
    - Column

If you tried to select from Paragraph B to Paragraph A, it would only select the Group block in the middle.

However, that issue is now fixed thanks to the latest commit!

It looks like everything is working better than `master` now in this branch. :tada:

**Comment by ellatrix** [comment]
> So the remaining issue is one that has been around for a long time, and is probably related to where the various block edit markup divs overlap (or rather, where they don't overlap).

Right, hopefully that's something we fix when removing all those nested divs.

**Comment by ellatrix** [comment]
@ZebulanStanphill Thanks for testing again. :)

**Review by youknowriad — APPROVED** [review]

**Comment by ellatrix** [comment]
Thank you! 🎉
