### PR TITLE
Block toolbar: restrict visible child calculation to known blocks 

### LINKED ISSUE #65872: Block toolbar weird shift with beta 6.7
### Description

While testing the new WordPress 6.7 beta with our plugin, I noticed a strange shift in the block toolbar that did not occur in version 6.6.x. 

All the elements inside the block that are generated in the “edit area positions” are absolutely positioned, so there is no width/height change to the block. 

I saw in the Gutenberg repo that the block-popover has been updated with some new calculation methods, so perhaps there is a new restriction for elements inside a block when the toolbar is visible. (possibly related to https://github.com/WordPress/gutenberg/commit/dec82e2dffda718feff8607d0205d2483d2de4be)

I understand this isn’t a bug related to a core block.

### Step-by-step reproduction instructions

1. Install the free Advanced Columns plugin from the WordPress.org repository
2. Add the block to the page
3. Switch the column mode to “Grid.” 
4. With the block selected, click on “Edit Area Positions” in the block toolbar

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/62904ca0-09ba-4a8d-be10-4c773ee4ea16

### Environment info

- WordPress: 6.7-beta1
- PHP: 8.2.24
- Server: nginx/1.25.4
- Database: mysqli (Server: 5.7.23 / Client: mysqlnd 8.2.24)
- Browser: Chrome 129.0.0.0 (macOS)
- Theme: Twenty Twenty-Four 1.2
- MU-Plugins: None activated
- Plugins: 
  * Advanced Columns Block 1.3.0
  * WordPress Beta Tester 3.5.6

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### LINKED ISSUE #66438: Block toolbar position in 6.7 can shift unexpectedly
### Description

This issue is likely the same one displayed in #65872

Changes were made in 6.7 that adjusted the positioning of the block toolbar. I have not yet been able to identify the PR, but the following videos demonstrate the situation. I used a WIP branch of the Icon Block in the videos below, but you can experience the same issue using the [public preview with 6.7 applied](https://playground.wordpress.net/?plugin=icon-block&blueprint-url=https%3A%2F%2Fwordpress.org%2Fplugins%2Fwp-json%2Fplugins%2Fv1%2Fplugin%2Ficon-block%2Fblueprint.json%3Frev%3D3122589%26lang%3Den_US&php=8.0&wp=beta&networking=yes&language=&multisite=no&random=wh9d32hu0kg). The toolbar will bounce up and down when you click the rotate button in the toolbar. 

### Block toolbar in 6.6 

The toolbar does not move.

https://github.com/user-attachments/assets/da2426bf-2e3c-40a8-9457-3836238b0bec

### Block toolbar in 6.7 

The toolbar bounces around. 

https://github.com/user-attachments/assets/80e6f2f8-1366-4934-95cc-625c61f87fb3

### Step-by-step reproduction instructions

1. Preview the Icon Block using the [public preview](https://playground.wordpress.net/?plugin=icon-block&blueprint-url=https%3A%2F%2Fwordpress.org%2Fplugins%2Fwp-json%2Fplugins%2Fv1%2Fplugin%2Ficon-block%2Fblueprint.json%3Frev%3D3122589%26lang%3Den_US&php=8.0&wp=beta&networking=yes&language=&multisite=no&random=wh9d32hu0kg) with 6.7 
2. The preview will open the Editor with the WordPress icon added to the page. Click on the W icon and rotate it using the button in the block toolbar.
3. Notice the toolbar bounces up and down. 
4. Switch to 6.6 and notice that the toolbar remains fixed. 

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 6.7 RC1

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by ramonjd**
Fixes: https://github.com/WordPress/gutenberg/issues/66438

## What?

Refactor `getVisibleElementBounds` to only check visible children for specific blocks that we know overflow. Rename function and update comments. Introduce rudimentary unit tests.

Props to @t-hamano and @stokesman for the ideas and testing.

## Why?

The positioning logic was rolled out to the general block population in https://github.com/WordPress/gutenberg/pull/62711 when the only use case was the navigation block. This hasn't changed.

See discussion: https://github.com/WordPress/gutenberg/issues/66438#issuecomment-2453282333

## How?
Implementing ideas discussed in https://github.com/WordPress/gutenberg/issues/66438#issuecomment-2452980588

### Navigation block

1. Install and activate Emptytheme, or use the Create Block Theme plugin to create a new empty theme.
2. Go to Appearance → Editor and edit the default template.
3. Insert a Navigation block into the first position in the header template part.
4. Edit the Navigation block and add a submenu to one of the navigation items.
5. Try to edit the submenu. The block toolbar should not obscure your cursor.

### Scrollable block toolbars

Follow the nice and detailed instructions on https://github.com/WordPress/gutenberg/issues/66112

TL;DR

1. Edit a post, open dev tools and paste in the snippet from the issue to create some test blocks that scroll
2. Add the test blocks to a long post with several paragraphs
3. Select each of the horizontal and vertical scrolling blocks and confirm their toolbar stays in the correct location
4. Scroll down the page and ensure their toolbars disappear correctly as the block leaves the viewport

### Block Popovers and Visualizers

1. Edit a post and add blocks that have a block popover e.g. Cover block with its resizable popover
2. Add some blocks that support spacing visualizers e.g. Group block with padding and margin support
3. Confirm that the visualizers and popovers display appropriately (visualizers have some problems on trunk not matching the controls value immediately so ignore them)

`npm run test:unit packages/block-editor/src/utils/test/dom.js`

Test coverage is basic so far, just for sanity checking purposes.

### CODE REVIEW

File: packages/block-editor/src/utils/test/dom.js [hunk 1]
```diff
@@ -0,0 +1,56 @@
+/**
+ * Internal dependencies
+ */
+import { getElementBounds } from '../dom';
+
+describe( 'dom', () => {
+	describe( 'getElementBounds', () => {
```
Comment (ramonjd) [inline packages/block-editor/src/utils/test/dom.js:6]: These tests are basic so far. I'll flesh them out, but they provide a small sanity check.

File: packages/block-editor/src/utils/dom.js [hunk 2]
```diff
@@ -134,41 +134,50 @@ function isScrollable( element ) {
...
- * contains nested elements that overflow the block, e.g. the Navigation block,
- * which can contain overflowing Submenu blocks.
+ * Returns the rect of the element.
  *
+ * Note: the function handles special cases for blocks that contain visible,
+ * nested elements that overflow the block, e.g. the Navigation block,
+ * which can have overflowing submenu blocks. Such blocks are defined in
+ * `WITH_OVERFLOW_ELEMENT_BLOCKS`. For such blocks,
+ * the bounds of the visible children are calculated to determine
+ * the full extent of the block including the visible children that overflow the parent.
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/utils/dom.js]:
```suggestion
 * Returns the bounding rectangle of an element, with special handling for blocks
 * that have visible overflowing children (defined in WITH_OVERFLOW_ELEMENT_BLOCKS).
 *
 * For blocks like Navigation that can have overflowing elements (e.g. submenus),
 * this function calculates the combined bounds of both the parent and its visible
 * children. The returned rect may extend beyond the viewport.
```

Nit: It's probably just the fact that my brain is still warming up on a Monday morning but this comment didn't read cleanly to me. Would something like the above be better? Your call.

File: packages/block-editor/src/utils/dom.js [hunk 3]
```diff
@@ -134,41 +134,50 @@ function isScrollable( element ) {
...
-				if ( isElementVisible( child ) ) {
-					const childBounds = child.getBoundingClientRect();
-					bounds = rectUnion( bounds, childBounds );
-					stack.push( child );
+	const dataType = element.getAttribute( 'data-type' );
+
+	/*
+	 * Handle special cases for blocks that have overflow elements.
+	 * The bounds of the visible children are calculated to determine the full extent of the block
+	 * including the visible children that overflow the parent.
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/utils/dom.js]:
```suggestion
	 * For blocks with overflowing elements (like Navigation), include the bounds
	 * of visible children that extend beyond the parent container.
```

Nit: If we're changing the function's docblock description, perhaps a tweak here would also tie this to what has already been read above?

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for continuing to narrow in on solution to the toolbar positioning @ramonjd 👍 

This tests well for me:

✅ Toolbar adjusts as expected for Nav block when it is the top-most block
✅ Toolbar is relocated when expanding Nav block submenus, adding items etc.
✅ Toolbar is correctly positioned when working with scrollable blocks
✅ No regressions around block popovers and visualizers

In general, this is looking good to me. 

> These tests are basic so far. I'll flesh them out, but they provide a small sanity check.

Sounds good. With a few extra tests, I think this is pretty close. 

---

<details>
<summary>Testing nav block in top-most position</summary>

https://github.com/user-attachments/assets/f635c6ba-d176-4992-a287-7afba2c233ab


</details>

<details>
<summary>Testing scrollable blocks</summary>

https://github.com/user-attachments/assets/d30f14b5-ee7c-46d1-a6ee-642577fce2bf


</details>

<details>
<summary>Testing block popover visualizers</summary>

https://github.com/user-attachments/assets/1df3e2f0-8f37-4ac7-b8f0-16de95d262cf


</details>

File: packages/block-editor/src/utils/test/dom.js [hunk 4]
```diff
@@ -0,0 +1,195 @@
...
+					width: 100,
+					height: 100,
+				} ),
+				getAttribute: ( x ) => x,
+			};
+			expect( getElementBounds( element ) ).toEqual(
+				new window.DOMRectReadOnly( 0, 0, 100, 100 )
+			);
+		} );
+		it( 'should return the child DOMRectReadOnly object if it is visible', () => {
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/utils/test/dom.js]: Nit: Does this need to state the child bounds are only for "known" blocks?

File: packages/block-editor/src/utils/test/dom.js [hunk 5]
```diff
@@ -0,0 +1,195 @@
...
+				top: 0,
+				right: 333,
+				bottom: 333,
+				width: 333,
+				height: 333,
+				x: 0,
+				y: 0,
+			} );
+		} );
+		it( 'should return the parent DOMRectReadOnly object if the child block type is not supported', () => {
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/utils/test/dom.js]: Nit: Is this accurate? My understanding is that it is the parent block type that is checked rather than the child's.

File: packages/block-editor/src/utils/test/dom.js [hunk 6]
```diff
@@ -0,0 +1,195 @@
...
+				top: 0,
+				right: 100,
+				bottom: 100,
+				width: 100,
+				height: 100,
+				x: 0,
+				y: 0,
+			} );
+		} );
+		it( 'should return the parent DOMRectReadOnly object if the child element is not visible', () => {
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/utils/test/dom.js]: Nit: Could we add another layer of `describe()` nesting to better group the tests for blocks that are known to have overflowing children vs others?

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for the quick turnaround on the extra tests 🚀 

The coverage is looking a lot better. Another nice addition could be some tests for viewport boundaries and blocks that might partially lie outside them etc.

Other than that, I left a few minor thought bubbles as inline comments around test descriptions.

**Comment by ramonjd** [comment]
Thanks for the suggestions @aaronrobertshaw All implemented in [ae72973](https://github.com/WordPress/gutenberg/pull/66702/commits/ae72973d381e89bf5069a8431d21ded8d3acb48d)

**Review by aaronrobertshaw — APPROVED** [review]
LGTM 👍 

Appreciate the rapid iterations on the tests here. I think they are in decent shape and should help provide some further confidence around this util.

**Review by t-hamano — APPROVED** [review]
LGTM! I have tested five plugins that have scrollable elements and they all seem to work correctly.

- [Advanced Columns Block](https://wordpress.org/plugins/advanced-columns-block/)
- [Piano Block](https://wordpress.org/plugins/piano-block/)
- [Custom HTML Block Extension](https://wordpress.org/plugins/custom-html-block-extension/)
- [The Icon Block](https://wordpress.org/plugins/icon-block/)
- [WordPress Slider Block Gutenslider](https://wordpress.org/plugins/gutenslider/)


https://github.com/user-attachments/assets/8343e169-37e7-4d36-bfc2-c64d41bf7334

**Comment by t-hamano** [comment]
Would it be possible to backport this PR and #66546 into a minor release?

**Comment by ramonjd** [comment]
> Would it be possible to backport this PR 

I'll add it to the 6.7.1 column in the [project board](https://github.com/orgs/WordPress/projects/210/views/1) 👍🏻 

Thanks for testing so thoroughly, everyone!

File: packages/block-editor/src/utils/dom.js [hunk 7]
```diff
@@ -134,41 +134,47 @@ function isScrollable( element ) {
 	);
 }
 
+export const WITH_OVERFLOW_ELEMENT_BLOCKS = [ 'core/navigation' ];
```
Comment (getdave) [inline packages/block-editor/src/utils/dom.js:137]: Not sure if you considered this elsewhere, but I wonder whether in the future we could make this list extensible as an editor setting? That way it can be modified in PHP for custom blocks?

Comment (ramonjd) [reply packages/block-editor/src/utils/dom.js:137]: Thank you for cherry picking this one! 

@t-hamano had an idea to add it to the block api

I think it's worth investigating if it the issue arises again.
