### PR TITLE
Fix Tools icon being 24x24 instead of 20x20.

### LINKED ISSUE #18826: Tools SVG icon is 24x24 when it should be 20x20
## The issue
The SVG icon for the Tools button in the main toolbar is too large. Its height and width should both be set to 20, but instead they are set to 24.

## Screenshot
image

## Envrionment info
- WordPress 5.4-alpha-46797
- Gutenberg `master` as of https://github.com/WordPress/gutenberg/commit/bf6976b8c7b2b85054891c250e9d57571dc93a10
- Using Dissenter browser 0.70 (based on Chromium 78)

### PR DESCRIPTION
**Pull request by ZebulanStanphill**
Fixes #18826.

Before:
image

After:
image

### CODE REVIEW

File: packages/block-editor/src/components/tool-selector/index.js [hunk 1]
```diff
@@ -13,8 +13,8 @@ import { __ } from '@wordpress/i18n';
...
 import { ifViewportMatches } from '@wordpress/viewport';
 
-const editIcon = <SVG xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><Path fill="none" d="M0 0h24v24H0V0z" /><Path d="M14.06 9.02l.92.92L5.92 19H5v-.92l9.06-9.06M17.66 3c-.25 0-.51.1-.7.29l-1.83 1.83 3.75 3.75 1.83-1.83c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.2-.2-.45-.29-.71-.29zm-3.6 3.19L3 17.25V21h3.75L17.81 9.94l-3.75-3.75z" /></SVG>;
-const selectIcon = <SVG xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><Path d="M6.5 1v21.5l6-6.5H21L6.5 1zm5.1 13l-3.1 3.4V5.9l7.8 8.1h-4.7z" /></SVG>;
+const editIcon = <SVG xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><Path fill="none" d="M0 0h24v24H0V0z" /><Path d="M14.06 9.02l.92.92L5.92 19H5v-.92l9.06-9.06M17.66 3c-.25 0-.51.1-.7.29l-1.83 1.83 3.75 3.75 1.83-1.83c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.2-.2-.45-.29-.71-.29zm-3.6 3.19L3 17.25V21h3.75L17.81 9.94l-3.75-3.75z" /></SVG>;
+const selectIcon = <SVG xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><Path d="M6.5 1v21.5l6-6.5H21L6.5 1zm5.1 13l-3.1 3.4V5.9l7.8 8.1h-4.7z" /></SVG>;
```
Comment (ellatrix) [inline packages/block-editor/src/components/tool-selector/index.js]: Should `viewBox` also be updated?

Comment (ellatrix) [reply packages/block-editor/src/components/tool-selector/index.js]: I mean, Ideally the SVG needs to be adjusted for this size, unless all icons use a 24px grid.

Comment (ZebulanStanphill) [reply packages/block-editor/src/components/tool-selector/index.js]: The SVGs used in the other buttons all have the same `viewBox` value as this one, so I didn't change it.

Comment (ellatrix) [reply packages/block-editor/src/components/tool-selector/index.js]: Oh, ok, that's interesting.

**Review by ellatrix — APPROVED** [review]

File: packages/block-editor/src/components/tool-selector/index.js (hunk 1 above)
Comment (youknowriad) [reply packages/block-editor/src/components/tool-selector/index.js]: I guess we could also remove these attributes and use CSS

Comment (jasmussen) [reply packages/block-editor/src/components/tool-selector/index.js]: > I guess we could also remove these attributes and use CSS

This could have adverse effects, because when CSS isn't applied (for whatever reason), the SVG will size to fit the availabl space which usually means it grows giant. 

I think this is another use case for introducing an `<Icon />` component so we can abstract away much of the complexity.
