### PR TITLE
Enhance: Improve pagination logic in core/query-pagination-previous block

### LINKED ISSUE #67748: Query Pagination Previous block appears incorrectly when navigating to page outside of the query's range.
### Description

This is a standard Query Loop block in the TT5 theme. We still show the Query Pagination Previous block whenever a user navigates to a page outside the query's range. However, as there are no results, the block does not make much sense to be shown.

### Step-by-step reproduction instructions

1. Add a Query Loop block to a page or post.
2. Make sure that the Post Template block of the Query Loop includes a Pagination Previous block.
3. Save your post/page.
4. Open your post/page on the frontend.
5. Navigate to a page that is outside of the range of the query. e.g.: `http://example.com&query-5-page=99999999`
6. Note that the **Previous** button is visible and it works but it does not make sense to show it in this context.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/1fea6e8f-835a-481b-9266-b046abdefe0f

### Environment info

- 6.8-alpha-59477
- TT5 theme
- Chrome
- Gutenberg `trunk`

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by yogeshbhutkar**
Fixes: #67748 

## What?
The **Query Pagination Previous** block is displayed even when a user navigates beyond the range of available query results. Since no results are shown in such cases, displaying this block is unnecessary and can be confusing. This PR addresses the issue by ensuring the **Query Pagination Previous** block is hidden when the query has no results, improving user experience and interface clarity.

## How?
The logic has been updated to render the block only when the page number is greater than 1 and less than or equal to the total number of pages, ensuring accurate and appropriate visibility.

## Testing Instructions
1. Add a query loop block.
2. Make sure to add Query Pagination block which contains Query Pagination Previous Block as well.
3. Enter a page range that lies outside the query range.
4. Observe that the block **Query Pagination Previous** is not rendered.

## Screencast

https://github.com/user-attachments/assets/2cf3cc25-215f-4eb6-877d-ac2f6086f7f5

## Screenshots

**Before:**
Screenshot 2024-12-10 at 11 42 10 AM

**After:**
Screenshot 2024-12-10 at 11 41 08 AM

### CODE REVIEW

**Comment by yogeshbhutkar** [comment]
Requesting for a re-review from @ntsekouras as a follow-up to this closed [PR](https://github.com/WordPress/gutenberg/pull/67772).

File: packages/block-library/src/query-pagination-previous/index.php [hunk 1]
```diff
@@ -1,4 +1,5 @@
 <?php
+
```
Comment (ntsekouras) [inline packages/block-library/src/query-pagination-previous/index.php]: We should remove this extra line.

File: packages/block-library/src/query-pagination-previous/index.php [hunk 2]
```diff
@@ -44,13 +45,25 @@ function render_block_core_query_pagination_previous( $attributes, $content, $bl
...
 		$content = get_previous_posts_link( $label );
 		remove_filter( 'previous_posts_link_attributes', $filter_link_attributes );
-	} elseif ( 1 !== $page ) {
-		$content = sprintf(
-			'<a href="%1$s" %2$s>%3$s</a>',
-			esc_url( add_query_arg( $page_key, $page - 1 ) ),
-			$wrapper_attributes,
-			$label
-		);
+	} elseif ( 1 < $page ) {
```
Comment (ntsekouras) [inline packages/block-library/src/query-pagination-previous/index.php]: Why you changed the condition here? I don't think we should.

File: packages/block-library/src/query-pagination-previous/index.php [hunk 3]
```diff
@@ -44,13 +45,25 @@ function render_block_core_query_pagination_previous( $attributes, $content, $bl
...
+
+		$total_pages = $max_page;
+		if ( ! isset( $block->context['query']['inherit'] ) || ! $block->context['query']['inherit'] ) {
```
Comment (ntsekouras) [inline packages/block-library/src/query-pagination-previous/index.php]: The reason I suggested to move this block here is that we could avoid this `if` condition, since it's actually the `else` from above. 

I know realized that we have an `elseif ( 1 !== $page )`, so I guess we could change the `elseif` to `else`, and inside that `else` block handle the `if ( 1 !== $page )`.

This way we wouldn't also need the temp assignment `$total_pages = $max_page;`

I hope I didn't confuse you :)

File: packages/block-library/src/query-pagination-previous/index.php (hunk 2 above)
Comment (yogeshbhutkar) [reply packages/block-library/src/query-pagination-previous/index.php]: Hi @ntsekouras, I was testing out the PR and found another small bug because of the condition `1 !== $page`. Basically, the value of `$page` should always be greater than 1. Otherwise, on negative page numbers (edge case scenario) the previous button is still visible and the navigation is possible infinitely because of the condition. 

Here's a screencast of the same:

https://github.com/user-attachments/assets/5e26432d-747d-4d47-bb42-04fe323b8e72

I went ahead and patched this bug. Although, would love to hear your thoughts on this.

Thanks for reviewing the PR.

Comment (ntsekouras) [reply packages/block-library/src/query-pagination-previous/index.php]: Oh, yes. It makes sense. Let's keep it!

**Comment by yogeshbhutkar** [comment]
Hi @ntsekouras, I've implemented the suggested changes. Here's a screencast of the same:


https://github.com/user-attachments/assets/cde366f1-083f-464f-b0cb-dd12c0b1fac0

The changes seem to be working as expected.

**Review by ntsekouras — APPROVED** [review]
Looks good, thank you!
