### PR TITLE
Fix: Custom button background color not reflected on reload

### LINKED ISSUE #18012: Button Block: Custom background color fails to display correct color in editor
**Describe the bug**
When a button is created with a custom background color, this change is correctly reflected in the block editor.  However, if you reload the page (or return to edit it at a later date) the button background color reverts to a dark grey

I recorded a short video of this behavior here:  https://cld.wthms.co/ribfAh

**To reproduce**
1. Add a button block to a page or post
2. set a custom color for the button
3. Publish (or update the page) the reload the browser window
4. See error:  button is no longer custom color, but a dark grey

**Expected behavior**
Custom button color (correctly shown when setting or editing the background color) be retained when revisiting the editor

Note:  Custom BG color is correctly applied on the published page.  Bug seems to only affect the view in the editor itself.

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.7
 - Browser Chrome 77.0.x and Safari 13.0.2
 - Wordpress 5.2.4
 - Gutenberg 6.7

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/18012

We had a bug where the editor may not reflect the custom button background color after a reload. That happened because the rule background: customGradient, may overwrite the background-color rule even if the custom gradient has not set.
This PR performs a logic update to solve the issue.

cc: @talldan 

## How has this been tested?
- Added a button block to a page or post
- Used custom color for the button, e.g., a red
- Published and reload the browser window
- Verify the color of the button is still red and not the default one.

Props to @jerrysarcastic for reporting this issue.

### CODE REVIEW

File: packages/block-library/src/button/edit.js [hunk 1]
```diff
@@ -140,8 +140,10 @@ function ButtonEdit( {
 					}
 				) }
 				style={ {
-					backgroundColor: ! customGradient && backgroundColor.color,
-					background: customGradient,
+					...( customGradient ?
+						{ background: customGradient } :
+						( { backgroundColor: backgroundColor.color } )
```
Comment (talldan) [inline packages/block-library/src/button/edit.js]: I'm not sure if the extra parentheses were intentional, they don't seem to be applied to the above line, but it might be nice to make it consistent one way or the other.

```suggestion
						{ backgroundColor: backgroundColor.color }
```

**Review by talldan — APPROVED** [review]
Thanks for following up on this one @jorgefilipecosta!
