### PR TITLE
LineHeightControl: Fix application of zero values in editor

### LINKED ISSUE #48768: LineHeightControl: Unexpected decrements and adjustments of zero values
Related:
- https://github.com/WordPress/gutenberg/issues/48766

### Description

The `LineHeightControl` currently behaves in unexpected ways when adjusting via the down arrow key, dragging down, or pressing enter while the value is `0`.

### Actual Behaviour

With a value set in the LineHeightControl, decrementing the value beyond `0` results in the value suddenly being reset to the placeholder default value of `1.5`. 

If you click into the LineHeightControl, type `0`, then press enter, moving focus away from the control will result in it being reset to `1.5`. Note: If you type `0` then move focus away without pressing enter, the `0` value will be retained.

### Expected Behaviour

Decrementing a value in the LineHeightControl to `0` and then attempting to decrement again will keep the `0` value when that is the minimum value set on the field.

If you type `0` into the field, and then press enter before moving focus elsewhere, the `0` value should be retained.

### Step-by-step reproduction instructions

1. Edit a post, select a paragraph, and navigate to the Block Inspector > Styles > Typography panel
2. Toggle on the Line Height control and enter a value e.g. 2
3. Now using either the down arrow key or dragging down on the input, decrement the value past `0` and see it get reset to the default placeholder value of `1.5`
4. Clear the value in the field, then type `0`, press enter, and then transfer focus elsewhere.
5. Note that the `0` value was lost and the placeholder is shown again

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/60436221/223048182-64570977-f641-4eb0-a4ff-096b5680d59a.mp4

### Environment info

- WP 6.1
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Fixes: https://github.com/WordPress/gutenberg/issues/48768

## What?

Prevents LineHeightControl resetting and clearing values when `0` line height selected.

## Why?

While zero line height might be an uncommon use case, as long as we allow zero as the minimum value for the control it should be honoured and remain when continuing to drag down, or use the down arrow key.

## How?

- Updated TypographyPanel's detection of when there is a line-height value set. This is less of a requirement when line-height is saved as a string however, the tweak is small and will handle any numeric line heights saved previously on blocks.
- Tweaked the width of the LineHeightControl input in the Storybook so the custom spin buttons fit
- Updated the LineHeightControl's change handling to ensure it handles an empty string value in a way that will work regardless of if cleanEmptyObject functions as per trunk now (`Boolean()`) or [#49750](https://github.com/WordPress/gutenberg/pull/49750) ( `!== undefined`). The control's `handleOnChange` will then ensure any defined line-height value is passed to it's onChange handler as a string. 

## Testing Instructions

1. Edit a post, select a paragraph, and navigate to the Block Inspector > Styles > Typography panel
2. Toggle on the Line Height control and enter a value e.g. 2
3. Now using either the down arrow key or dragging down on the input, attempt to decrement the value past 0. It should remain zero.
4. Clear the value in the field, then type 0, press enter, and then transfer focus elsewhere.
5. The zero value should still be retained.
6. Manually delete the value within the control
7. Switch to code editor view and ensure the block's style attribute doesn't contain a lineHeight property.

## Screenshots or screencast 

| Before | After |
|---|---|
| <video src="https://user-images.githubusercontent.com/60436221/223672884-174ee7ae-1a61-4dfa-8f2e-faf1090b4a16.mp4" /> | <video src="https://user-images.githubusercontent.com/60436221/223672896-8cea3b1c-a7a7-4d8b-a083-e8acdf5becc3.mp4" /> |

### CODE REVIEW

File: packages/block-editor/src/hooks/utils.js [hunk 1]
```diff
@@ -16,22 +16,28 @@ import { useSetting } from '../components';
...
 	) {
 		return object;
 	}
+	const recursiveCleanObject = ( nestedObject ) =>
+		cleanEmptyObject( nestedObject, { allowZeros } );
 	const cleanedNestedObjects = Object.fromEntries(
-		Object.entries( mapValues( object, cleanEmptyObject ) ).filter(
-			( [ , value ] ) => Boolean( value )
+		Object.entries( mapValues( object, recursiveCleanObject ) ).filter(
+			( [ , value ] ) => Boolean( value ) || ( allowZeros && value === 0 )
```
Comment (talldan) [inline packages/block-editor/src/hooks/utils.js]: It is getting a little unreadable, so I think it might be good to break it onto multiple lines:

```suggestion
			( [ , value ] ) => {
			    if ( options?.allowZeros && value === 0 ) return true;
			    return Boolean( value );
			}
```

File: packages/block-editor/src/hooks/utils.js [hunk 2]
```diff
@@ -16,22 +16,28 @@ import { useSetting } from '../components';
 import { useSettingsForBlockElement } from '../components/global-styles/hooks';
 
 /**
- * Removed falsy values from nested object.
+ * Removed falsy values from nested object. If `allowZeros` is `true`, then
+ * zero values will be allowed within the resulting object.
+ *
+ * @param {*}       object             Object to be cleaned.
+ * @param {Object}  options            Options config.
+ * @param {boolean} options.allowZeros Whether to allow zero values.
```
Comment (talldan) [inline packages/block-editor/src/hooks/utils.js]:
```suggestion
 * @param {Object}  [options]            Options config.
 * @param {boolean} [options.allowZeros] Whether to allow zero values.
```

File: packages/block-editor/src/hooks/utils.js [hunk 3]
```diff
@@ -16,22 +16,28 @@ import { useSetting } from '../components';
...
+export const cleanEmptyObject = ( object, { allowZeros } = {} ) => {
 	if (
 		object === null ||
 		typeof object !== 'object' ||
 		Array.isArray( object )
 	) {
 		return object;
 	}
+	const recursiveCleanObject = ( nestedObject ) =>
+		cleanEmptyObject( nestedObject, { allowZeros } );
```
Comment (talldan) [inline packages/block-editor/src/hooks/utils.js]: It seems more work to destructure the options (and involves creating a new object on each recursion), so not destructuring might be tidier:
```suggestion
export const cleanEmptyObject = ( object, options ) => {
	if (
		object === null ||
		typeof object !== 'object' ||
		Array.isArray( object )
	) {
		return object;
	}
	const recursiveCleanObject = ( nestedObject ) =>
		cleanEmptyObject( nestedObject, options );
```

**Review by talldan — APPROVED** [review]
LGTM, the changes all make sense.

Left some comments, but they're mostly optional, though it'd be good to fix the types in the doc block before merging.

File: packages/block-editor/src/hooks/utils.js [hunk 4]
```diff
@@ -16,22 +16,28 @@ import { useSetting } from '../components';
...
+ *
+ * @param {*}       object             Object to be cleaned.
+ * @param {Object}  options            Options config.
+ * @param {boolean} options.allowZeros Whether to allow zero values.
  *
- * @param {*} object
  * @return {*} Object cleaned from falsy values
  */
-export const cleanEmptyObject = ( object ) => {
+export const cleanEmptyObject = ( object, { allowZeros } = {} ) => {
```
Comment (youknowriad) [inline packages/block-editor/src/hooks/utils.js]: Just saw this change, yeah I think it was never the intent of this function to skip zeros, empty strings or false values. I think this should only check for "undefined" values see https://github.com/WordPress/gutenberg/pull/49750 

That said, there might be some small side effects that we need to check, not sure how well tested this is.

File: packages/block-editor/src/components/line-height-control/index.js [hunk 5]
```diff
@@ -45,7 +45,7 @@ const LineHeightControl = ( {
 			case '0': {
 				// This means the user explicitly input '0', rather than stepped down
 				// from an undefined value state.
-				if ( wasTypedOrPasted ) return nextValue;
+				if ( wasTypedOrPasted ) return parseInt( nextValue, 10 );
```
Comment (youknowriad) [inline packages/block-editor/src/components/line-height-control/index.js]: Do you remember why you had to make this specific change?

Comment (aaronrobertshaw) [reply packages/block-editor/src/components/line-height-control/index.js]: It was added in this [commit](https://github.com/WordPress/gutenberg/pull/48917/commits/3c12a3afdb9eafe9721c1829b5aa482a38a3da02). The line height control was getting inconsistent types back depending on how values were entered. This normalized the next value to a number.

File: packages/block-editor/src/hooks/utils.js (hunk 4 above)
Comment (aaronrobertshaw) [reply packages/block-editor/src/hooks/utils.js]: Locally, I've rebased this PR onto https://github.com/WordPress/gutenberg/pull/49750 (removing the customizations to cleanEmptyObject from this PR) and it works as you'd expect.

As was [noted](https://github.com/WordPress/gutenberg/pull/49750#discussion_r1165457580) by others over on https://github.com/WordPress/gutenberg/pull/49750, I'm not sure we can simply check against undefined for all uses of `cleanEmptyObject`. I'm happy to hold off on this PR until we settle on a direction for https://github.com/WordPress/gutenberg/pull/49750 and whether we are forced to use an options object of some sort after all.

File: packages/block-editor/src/components/line-height-control/index.js (hunk 5 above)
Comment (youknowriad) [reply packages/block-editor/src/components/line-height-control/index.js]: If I'm not wrong, if you normalize it to a string instead, the changes to `cleanEmptyObject` won't be needed in this

Comment (aaronrobertshaw) [reply packages/block-editor/src/components/line-height-control/index.js]: I can make that change.

The other return values around it were numbers and this component is built on the NumberControl, so my understanding was that a numeric value was expected.  I know we have a lot of inconsistencies around `number` vs `string` types for `NumberControl` related components and those are being addressed in https://github.com/WordPress/gutenberg/pull/45982. 

Digging deeper, it seems the values passed to `onChange` vary between strings and numbers a lot based on how the value is edited. For example;
- Typing into the field will pass a string
- If you then press enter after typing a value, onChange is called again this time with a number
- If you press up/down arrow keys, the value will be a number
- If you use the custom spin buttons, the value is a string
- Dragging up or down will pass a number value

Given the point of this PR was to fix the application of zero values, I'll normalize to a string as suggested to limit the scope of change. Any wrangling of the value types passed to the change handlers and state reducers can be a follow-up if there is an appetite for it post #45982.

File: packages/block-editor/src/components/global-styles/typography-panel.js [hunk 6]
```diff
@@ -228,7 +228,7 @@ export default function TypographyPanel( {
 			immutableSet( value, [ 'typography', 'lineHeight' ], newValue )
 		);
 	};
-	const hasLineHeight = () => !! value?.typography?.lineHeight;
+	const hasLineHeight = () => value?.typography?.lineHeight !== undefined;
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/components/global-styles/typography-panel.js:231]: I've kept this tweak to the line height value detection so it can correctly check any old numeric line-height values that might be `0` in existing blocks/styles.

File: packages/block-editor/src/components/line-height-control/index.js [hunk 7]
```diff
@@ -85,12 +85,17 @@ const LineHeightControl = ( {
 		: { marginBottom: 24 };
 
 	const handleOnChange = ( nextValue, { event } ) => {
+		if ( nextValue === '' ) {
+			onChange();
+			return;
+		}
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/components/line-height-control/index.js:91]: This is needed if we land https://github.com/WordPress/gutenberg/pull/49750 which changes `cleanEmptyObject` to keep anything that `!== undefined`. 

It also allows the following onChange calls to simply convert the value to a string improving zero value handling.

**Review by aaronrobertshaw — COMMENTED** [review]
I've updated the approach in light of @youknowriad's [feedback](https://github.com/WordPress/gutenberg/pull/48917#discussion_r1168472424) advising as to how we can avoid the need to update `cleanEmptyObject`.

The latest approach in this PR works for me against trunk's `cleanEmptyObject` or the version in https://github.com/WordPress/gutenberg/pull/49750.

I've left a few inline comments as to the changes that remain but the PR is now more trivial.

File: packages/block-editor/src/components/line-height-control/index.js (hunk 5 above)
Comment (youknowriad) [reply packages/block-editor/src/components/line-height-control/index.js]: I agree with you that the logical thing to do here is to actually use a number because "line height" is a number. But yeah maybe because of the fact that it surfaces the other more generic bug ( The one I hint to here https://github.com/WordPress/gutenberg/pull/49750#issuecomment-1508353263 ), it's better to stick with string for now until we find a good solution for that one.

**Comment by aaronrobertshaw** [comment]
Now https://github.com/WordPress/gutenberg/pull/49750 has been merged, I've re-tested this PR after rebasing on trunk and it still works well. 

I'll get this merged.
