### PR TITLE
Fix image centering in gutenberg 8.2.0

### LINKED ISSUE #22694: Image centering and full width broken in 8.2.0
There are two parts to this regression which happened between 8.1.0 and 8.2.0,
Firstly, when you choose the centered option for an image, it no longer centers correctly. 
May-28-2020 16-04-11

Secondly, when you resize an image, and then use the "Wide Width" setting, the image's width is not changed. 
May-28-2020 19-01-39

I've tested these on the local gutenberg docker based dev environment. An I checked that the issues weren't happening with 8.1.0

It appears that at least the first ( center alignment) issue was [introduced in this PR](https://github.com/WordPress/gutenberg/pull/22360/files#diff-d1d037caeeea85a91038b28fa70cd435L28), by removing `display: inline-block;` from the `.components-resizable-box__container` element.

I created a PR to fix that issue but unfortunately, that alone doesn't fix the "Wide Width" issue
https://github.com/WordPress/gutenberg/pull/22693

### PR DESCRIPTION
**Pull request by roo2**
closes #22694 

## Description
Currently in 8.2.0, image centering is broken, I originally found it testing for wordpress.com and can confirm it also happens in gutenberg's docker testing environment
Before:
May-28-2020 16-04-11

https://github.com/Automattic/wp-calypso/issues/42637

## How has this been tested?
* Installed latest version to the local docker test environment
* Test the other image centering modes
* Tested with resized images
May-28-2020 18-57-21

### Technical Details

It looks like the missing piece was that the `.components-resizable-box__container` element no longer had `display: inline-block;` set on it after this change https://github.com/WordPress/gutenberg/pull/22360/files#diff-d1d037caeeea85a91038b28fa70cd435L28

### Note 

There is currently an issue with resizing the image and then setting it to "Wide width", if you do this, the image is not set to full screen like it should be

### CODE REVIEW

File: packages/block-library/src/image/edit.js [hunk 1]
```diff
@@ -259,7 +259,7 @@ export function ImageEdit( {
 	}
 
 	function updateAlignment( nextAlign ) {
-		const extraUpdatedAttributes = isWideAligned
+		const extraUpdatedAttributes = [ 'wide', 'full' ].includes( nextAlign )
```
Comment (youknowriad) [inline packages/block-library/src/image/edit.js:262]: The wide alignment issue was a different regression introduced here https://github.com/WordPress/gutenberg/commit/1063573c5f1c95f05b4ab8e42b763158c7c79cac#r39498180, I pushed a fix

**Review by ockham — APPROVED** [review]
Works well in my testing! Thanks @roo2 and @youknowriad :slightly_smiling_face:
