### PR TITLE
Iframe / block drag chip: Fix positioning when dragging over an iframe

### LINKED ISSUE #55074: Block draggable chip's position is incorrect when dragging over an iframe
### Description

The drag chip (the little icon that follows the mouse cursor around) is incorrectly positioned when dragging a block over the site editor canvas, or the post editor canvas when the post editor is iframed (i.e. running TT3 theme with core blocks).

This appears to be to do with the `Draggable` component's positioning when dragging over an iframe in particular.

### Step-by-step reproduction instructions

1. Open the site editor
2. Go to edit a template or the site home
3. Open the block inserter
4. Drag a paragraph block to the editor canvas
5. As you drag over the editor canvas, notice that the drag chip position flicks suddenly to the edge of the browser window

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/14988353/619c22e1-3c01-4b12-8760-43de6712ab95

The same issue appears to happen with the Draggable component in Storybook if you use the Docs view that shows all stories. This is a good way to test it because each preview occurs in an iframe, too, it seems. The URL for testing the Draggable component in Storybook is: https://wordpress.github.io/gutenberg/?path=/docs/components-draggable--docs

https://github.com/WordPress/gutenberg/assets/14988353/2be64d83-0456-4e17-b1df-babfeeea5dd7

### Environment info

- Gutenberg trunk on WP 6.3.1 (without GB running, the position is correct in 6.3.1)
- WP 6.4 Beta 1 (without GB running)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by andrewserong**
## What?

Fixes #55074

Fix issue where dragged components would "jump" when dragged over the editor iframe.

## Why?

In #54080 the `bubbleEvents` function for the iframe was refactored so that a reusable `bubbleEvent` handler could be used to enable bubbling up keyboard events. However, that change unintentionally introduced a change to the check that determines whether to add an offset to the `clientX` and `clientY` positions of mouse events. Prior to #54080 the check was to see whether the event was an instance of the `contentDocument`'s `MouseEvent`, however #54080 used `ownerDocument`.

It's a subtle difference, but checking against the `contentDocument` means that we're checking the event was generated within the iframe, whereas checking against the `ownerDocument` checks that the event was generated by the owner document, which is not where we want the offset to be applied. In practice, on `trunk` the logic for the offset was never being hit, because the if statement appeared to always evaluate to `false`.

Note: this PR does _not_ fix the issue in Storybook when using the `Docs` view for the `Draggable` component as described in #55074 — I believe that's because the Docs view in Storybook is not using the `Iframe` component from the block editor package, so it never receives the offset logic for the event.

An alternative could potentially be to include logic like what's in the `Iframe` component for the `Draggable` component, but that's outside the scope of this PR — the goal (and proposal) of this PR is to get back to the working state prior to #54080 🤞 

## How?

* Update the check within `bubbleEvent` to use `contentDocument` instead of `ownerDocument` so that we're checking that the event occurred within the iframe.
* Add an explanatory comment to capture the desired behaviour.

## Testing Instructions

1. On `trunk` drag a block from the list view into the post editor canvas, notice that the drag chip position jumps
2. Repeat in the site editor and / or dragging a block from the block inserter
3. Apply this PR, and check that the positioning is now correct

## Screenshots or screencast 

| Before | After |
| --- | --- |
|  |  |

### CODE REVIEW

**Review by t-hamano — APPROVED** [review]
LGTM! As mentioned in [this comment](https://github.com/WordPress/gutenberg/issues/55074#issuecomment-1752350856), I came to the exact same conclusion as this PR 😄

**Comment by andrewserong** [comment]
Thanks for the quick review @t-hamano! Since we both came to the same conclusion separately and that we're close to a WP beta release, I'll merge this in so we can have the bug fix in place, rather than wait for further reviews. Also it should be a quick revert if there are any issues since it's only a one-liner 🙂

Thanks again for digging into this issue with me! 😀

File: packages/block-editor/src/components/iframe/index.js [hunk 1]
```diff
@@ -38,7 +38,14 @@ function bubbleEvent( event, Constructor, frame ) {
...
 
-	if ( event instanceof frame.ownerDocument.defaultView.MouseEvent ) {
+	// Check if the event is a MouseEvent generated within the iframe.
+	// If so, adjust the coordinates to be relative to the position of
+	// the iframe. This ensures that components such as Draggable
+	// receive coordinates relative to the window, instead of relative
+	// to the iframe. Without this, the Draggable event handler would
+	// result in components "jumping" position as soon as the user
+	// drags over the iframe.
+	if ( event instanceof frame.contentDocument.defaultView.MouseEvent ) {
```
Comment (youknowriad) [inline packages/block-editor/src/components/iframe/index.js:48]: Do we have a way to validate this behavior with an e2e test or something?

**Comment by ciampo** [comment]
> Note: this PR does not fix the issue in Storybook when using the Docs view for the Draggable component as described in https://github.com/WordPress/gutenberg/issues/55074 — I believe that's because the Docs view in Storybook is not using the Iframe component from the block editor package, so it never receives the offset logic for the event.

Yeah I'm not sure how much control we have over the `iframe` used in the docs view. We could look into that and see if Storybook allows for tweaking that aspect. Otherwise we may want to add a little paragraph somewhere to let folks know that the demo doesn't work in docs view.

> An alternative could potentially be to include logic like what's in the Iframe component for the Draggable component, but that's outside the scope of this PR — the goal (and proposal) of this PR is to get back to the working state prior to https://github.com/WordPress/gutenberg/pull/54080 🤞

I'm not sure it should be Draggable's role to account for these nuances, I'd hold off for now.

**Comment by mikachan** [comment]
I just cherry-picked this PR to the 6.4-beta3 branch to get it included in the next release: https://github.com/WordPress/gutenberg/pull/55039/commits/2e4bba141b03b8988989e7091f8df7a009da17df

File: packages/block-editor/src/components/iframe/index.js (hunk 1 above)
Comment (andrewserong) [reply packages/block-editor/src/components/iframe/index.js:48]: Good question! I wonder how far we could get with React Testing Library and mounting an `Iframe` and firing an event, rather than a full e2e test? I'll add it to my list, but will focus on a couple of other bug fixes for 6.4 in the immediate term. For now, I think the addition of the comment here should help us in the interim, so we know what to look for if we encounter a similar issue again.
