### PR TITLE
Fix Link UI incorrect text replacement in Rich Text

### LINKED ISSUE #41771: Link UI: Changing link text can modify the wrong text
### Description

When editing the text of an existing link, sometimes the wrong text can be edited because a simple search and replace disregarding the active selection is done.

I believe the origin of this was #33849.

### Step-by-step reproduction instructions

* Create new paragraph block
* Type `a b c a`
* Select the second occurrence of `a`, at the end of the text, press the link button to create a link, type in a url like `example.com` and press enter. You should now have text `a b c a` with the second `a` linked.
* Highlight the second `a` by selecting with the mouse.
* In the link popup, click the pencil icon to edit the link.
* You should see 'text' and 'url' fields. In the text field, change `a` to `z` and press enter.
* Expected to see: `a b c z`, because I was editing the link on the second `a`.
* Actually see: `z b c a`, because it does find and replace on the text of the link.
Should be easier to understand in the screen recording.

### Screenshots, screen recording, code snippet

**Contrived example (word boundary)**

https://user-images.githubusercontent.com/937354/174169288-e9030942-bf2a-47b1-b9a0-9e9c7de83619.mp4

**Contrived example (within word)**

https://user-images.githubusercontent.com/937354/174169295-0660fde7-92f7-49fb-8378-1ea63a539109.mp4

For a less contrived example, imagine editing a word that was used twice or more in a long paragraph.

### Environment info

982cfc775d15b from 2022-06-16 on trunk branch in wp-env.
Also seen on production wp.com on 2022-06-16.
I tried on earlier versions, going back to 2022-01-01 and still saw the behavior back then.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### Mechanisms

The behavior is caused by this line:

https://github.com/WordPress/gutenberg/blob/982cfc775d15b840c08a06e25cc72c69587185d7/packages/format-library/src/link/inline.js#L158

In the case of `a b c a` with the second `a` selected, and changing the text to `z`, the replace call sees `value` with `.text` of `a b c a`, and runs a replace on it, looking for `a`, and changes the first one it finds; even if it's not what I have selected.

The call to it does have the selection information: 

One idea I had was to make something like `replaceInSelection`, which does the same as `replace`, but only considers text within the start-end range. However, I know so little about gutenberg that I don't know if this is a good approach.

### PR DESCRIPTION
**Pull request by getdave**
## What?

Fixes a bug whereby editing the text of links with identical text content within a rich text field could result in the wrong link's text being updated.

Closes https://github.com/WordPress/gutenberg/issues/41771

## Why?

It's important that only the text of the currently active link (active format) is updated.

## How?

The code was using the `@wordpress/rich-text` `replace()` utility to update the `RichTextValue` object with the modified text. However, `replace` only operates on the first match it finds. Therefore if the same rich text value contained mulitple links all with the same text then the `replace` operation would update the text on the first link even if this was not the one being edited.

This PR fixes this by splitting the value at the boundary of the active link format. The `replace()` is then only run against the  second portion of the split value thereby ensuring that the active link format is the first matched by `replace`.

This PR has to work around what I think may be a bug in `split()` whereby the split point for the second portion of the value is determined based on the `value.end`. As `value`s may have `start` and `end` which don't match this can result in the string being split incorrectly. 

## Testing Instructions

- New Post.
- Switch to code view and paste:
```
<!-- wp:paragraph -->
<p><a href="http://www.wordpress.org" data-type="URL" data-id="www.wordpress.org">example</a> is another <a href="http://www.yahoo.com" data-type="URL" data-id="www.yahoo.com">example</a> and another <a href="http://www.wordpress.com" data-type="URL" data-id="www.wordpress.com">example</a></p>
<!-- /wp:paragraph -->
```
- Switch to visual mode.
- Select the middle link and edit it's text. Hit submit to modify the link.
- See that only the text of the active link was modified.
- Also test against steps in https://github.com/WordPress/gutenberg/issues/41771.

## Screenshots or screencast 

https://user-images.githubusercontent.com/444434/201162175-f9665d79-bd4c-409c-829c-8a1a72a96410.mp4

https://user-images.githubusercontent.com/444434/201162495-307befc6-d2e4-4f60-bb66-acda589f9165.mp4

### CODE REVIEW

File: packages/format-library/src/link/inline.js [hunk 1]
```diff
@@ -148,14 +151,37 @@ function InlineLinkUI( {
...
+
+				// Split the value at the start of the active link format.
+				// Passing "start" as the 3rd parameter is required to ensure
+				// the second half of the split value is split at the format's
+				// start boundary and avoids relying on the value's "end" property
+				// which may not correspond correctly.
+				const [ valBefore, valAfter ] = split(
+					value,
+					boundary.start,
+					boundary.start
```
Comment (getdave) [inline packages/format-library/src/link/inline.js:167]: @ellatrix I don't think passing this should be necessary but it is.

Firstly the `split()` function only accepts 2 args not 3. The only reason this works is that it uses `...arguments` to delegate to the `splitAtSelection` function which _does_ accept a 3rd parameter.

By default the 3rd param of `splitAtSelection` defaults to the passed `value`'s `end` property. In the case of `split()` we always want to split the string at position `X` as defined by the 2nd argument. However in some cases the `start` and `end` of the `value` may not match and thus the `value` is split incorrectly.

I'm _having_ to pass `boundary.start` as the 3rd ("end") argument to ensure that the `value` is split in-two at the start of the boundary. Otherwise the second half of the split value often doesj't match what you'd expect.

**Comment by mreishus** [comment]
In my testing, this is fixing the issue described in #41771 :+1:

**Review by scruffian — DISMISSED** [review]
This makes sense and works as advertised. It does seem unfortunate that it relies on a quirk of `splitAtSelection`, so I think it would also make sense to get a review from @ellatrix.

**Comment by ellatrix** [comment]
@getdave Most important things first, could we add an e2e test please? ☺️

File: packages/format-library/src/link/inline.js (hunk 1 above)
Comment (ellatrix) [reply packages/format-library/src/link/inline.js:167]: Yes, by default all of these functions look at the rich text value's current selection. We allow you to override that, and to do that properly you need to provide both a new selection start and end.

File: packages/format-library/src/link/inline.js [hunk 2]
```diff
@@ -148,14 +151,37 @@ function InlineLinkUI( {
 					newText.length
 				);
```
Comment (ellatrix) [inline packages/format-library/src/link/inline.js:153]: Commenting on folded code above here. What happens to _existing_ formats? I see that you're creating a new rich text value with the new text, and then applying a link format to it. But by replacing the exiting selection with this new rich text value, any existing formatting will be removed (e.g. bold or italic).

Perhaps this is the wrong way to approach the text replacement? I think we should do the replacement in two steps:
1) Replace the link format's URL as we would normally do.
2) Replace the active link's text only.

File: packages/format-library/src/link/inline.js (hunk 1 above)
Comment (getdave) [reply packages/format-library/src/link/inline.js:167]: ...but `split()` doesn't actually have an `end` argument, it just has `string` (which can be used to provide a start index):

https://github.com/WordPress/gutenberg/blob/9e6e8c9cb7e8cf35ea148d28dfb7dc21b1c4b915/packages/rich-text/src/split.js#L19

https://github.com/WordPress/gutenberg/blob/9e6e8c9cb7e8cf35ea148d28dfb7dc21b1c4b915/packages/rich-text/src/split.js#L15

The only reason the method I'm using in this PR works is that `...arguments` is utilised to pass all of `split`'s arguments to `splitAtSelection`:

https://github.com/WordPress/gutenberg/blob/9e6e8c9cb7e8cf35ea148d28dfb7dc21b1c4b915/packages/rich-text/src/split.js#L20-L22

So it's not obvious from the function signature that you can/should provide an `end`. 

> We allow you to override that, and to do that properly you need to provide both a new selection start and end.

Is the intention that you manually update the selection on the `value` being passed into `split` before it's passed in?


I still feel it's confusing...

`endIndex` is set to `value.end` 

https://github.com/WordPress/gutenberg/blob/9e6e8c9cb7e8cf35ea148d28dfb7dc21b1c4b915/packages/rich-text/src/split.js#L57-L61

....which may produce unexpected results when (as instructed in the doc block) you've passed an explicit `Start index` into the `split()` as the 2nd `string` argument. 



If I pass X as `string` then I'd expect the value to be split at X. What can actually happen is the value is split at X but the (remaining) second half of the value is _not_ split at X but at whatever `value.end` is.

https://github.com/WordPress/gutenberg/blob/9e6e8c9cb7e8cf35ea148d28dfb7dc21b1c4b915/packages/rich-text/src/split.js#L71-L77

Could / should we instead default `endIndex` to `startIndex` so that (by default) if a start index is passed to `split` as `string` then it will split where you expect it to?

File: packages/format-library/src/link/inline.js (hunk 2 above)
Comment (getdave) [reply packages/format-library/src/link/inline.js:153]: Yeh clobbering other formats doesn't sound great 😰

**Comment by getdave** [comment]
> @getdave Most important things first, could we add an e2e test please? ☺️

@ellatrix This now has an e2e test which emulates the Issue reported and verifies the result is now as expected (i.e. no bug).

We should still address [your feedback](https://github.com/WordPress/gutenberg/pull/45710#discussion_r1026290231) but in a follow up.

**Review by draganescu — APPROVED** [review]
This PR fixes the problem, but will need one follow up for tweaking how the fix is applied. Most importantly:

- [ ] applying a link on a text that has a link removes all previous formatting

However, the problem it fixes should be worth the trade off for now.
