### PR TITLE
@wordpress/date: Fix ordinal token (S), RFC2822 token (r), and timezone offset handling

### LINKED ISSUE #15221: Ordinal suffix token does not work in `wp.date.format`
`console.log( format( 'l, F jS', Date.now() ) );`

Expected: `Friday, April 26th`
Actual: `Friday, April 26`

### PR DESCRIPTION
**Pull request by noisysocks**
## What?

Fixes three bugs in `@wordpress/date` including https://github.com/WordPress/gutenberg/issues/15221.

1. `wp.date.dateI18n( 'jS' )` should output e.g. `23rd`, but it was outputting `23`.
2. `wp.date.dateI18n( 'r' )` should be in English (per RFC822 spec) when site language is set to a non-English language.
3. `wp.date.format( 'P' )` should be `'+00:00'` when site's timezone offset is `'0'`.

I've also added unit tests for all of the format string characters that `date` and its friends accept.

The fix for https://github.com/WordPress/gutenberg/issues/15221 was my intention. The other two bugs I noticed while writing unit tests.

## Why?

1. WordPress doesn't have enough information about the current locale to translate a date's ordinal, which is why `wp_date( 'jS' )` in PHP always outputs e.g. `23rd` in English even if the site's language is a non-English language. `wp.date.date()` should match the behaviour of `wp_date()` so I did not attempt to fix this. (I have ideas on how we could...)

   Because there isn't any information about the ordinal, we don't set `ordinal` when defining our locale in Moment.js. This means that when Moment.js renders the `jS` token, it will look at the _parent locale_ for information on how to output the ordinal.

   Gutenberg **is** passing `parentLocale` to `moment.updateLocale()`, but this does not work. Only `moment.defineLocale()` accepts `parentLocale`.

2. We were naively translating the `r` token to `ddd, DD MMM YYYY HH:mm:ss ZZ` but that's not right as the day and month shouldn't be localised.

3. `moment.utcOffset()` accepts a string like `'+00:00'` or an integer like `0`. A string like `'0'` is invalid and will cause the created moment instance to be in whatever timezone the user is in.

## How?

1. The fix is to use `defineLocale()` instead of `updateLocale()`.

   Because Core [might have already defined the locale](https://github.com/WordPress/wordpress-develop/blob/d7f9f4405b30be28c026e6a3162b5e0b24f9c8e4/src/wp-includes/script-loader.php#L138), we must delete any existing locale before creating it. We can detect whether it's a locale created by Core or not based on whether it's incorrectly configured. Core (and Gutenberg, until this PR) is setting `LTS`, `L` and `LLLL` to `null` in the locale config, which is not permitted, [according to the type definitions](https://github.com/moment/moment/blob/e96809208c9d1b1bbe22d605e76985770024de42/moment.d.ts#L115).

2. Calling `locale( 'en' )` on the moment instance before rendering it will ensure it's in English.

3. Coercing the site's timezone offset to a number before passing it to `utcOffset` will ensure Moment.js is happy.

## Testing Instructions

Unit tests are included. You could also follow the steps in https://github.com/WordPress/gutenberg/issues/15221 and https://github.com/WordPress/gutenberg/pull/39569.

You could also set your site to a few different languages and make sure dates e.g. in the _Publish_ dropdown look correct.

I ordered the commits in a TDD way so you can `git checkout HEAD^` if you want to see that the new tests I added fail on `trunk`.

### CODE REVIEW

File: packages/date/src/index.js [hunk 1]
```diff
@@ -136,11 +136,34 @@ let settings = {
 export function setSettings( dateSettings ) {
 	settings = dateSettings;
 
-	// Backup and restore current locale.
+	setupWPTimezone();
+
+	// Does moment already have a locale with the right name?
+	if ( momentLib.locales().includes( dateSettings.l10n.locale ) ) {
+		// Is that locale misconfigured, e.g. because we are on a site running
+		// WordPress < 6.0?
```
Comment (noisysocks) [inline packages/date/src/index.js:144]: Noting to myself that I need to submit a Core patch that makes this same fix there. Should also add a comment here to delete this code when the minimum WP version is 6.0.

**Review by talldan — APPROVED** [review]
Looks great, really appreciate all the tests that have been added.
