### PR TITLE
Categories block: fix alignment

### LINKED ISSUE #7910: Alignment: categories block forces `aligncenter` regardless of what is selected in the toolbar
Moved from #4010 h/t @bradyvercher.

Steps to reproduce:

1. Insert a categories block and publish (the class is `aligncenter`).
1. Align it right and save (the class is `alignright`).
1. Unselect alignment and save (the class is `aligncenter`).

<strong>Result:</strong> 

> The PHP render method forces an `aligncenter` class to be applied even when an alignment button isn't selected in the toolbar.

screen shot 2018-07-11 at wed jul 11 5 55 16 pm
<sup>Seen at http://alittletestblog.com/2018/07/11/categories-block/ running WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.5.</sup>

### PR DESCRIPTION
**Pull request by ZebulanStanphill**
## Description
This PR fixes an issue where the Categories block would always use the `aligncenter` class regardless of what alignment you set. It also cleans up some of the code to make it more readable and consistent.

Fixes #7910.

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
Could this be milestoned for 4.1? It's been ready-to-merge (aside from having no reviews) for a month now. Also, the enhancement label is not really correct. This is a bug fix.

File: packages/block-library/src/categories/index.php [hunk 1]
```diff
@@ -16,11 +16,6 @@ function render_block_core_categories( $attributes ) {
 	static $block_id = 0;
 	$block_id++;
 
-	$align = 'center';
-	if ( isset( $attributes['align'] ) && in_array( $attributes['align'], array( 'left', 'right', 'full' ), true ) ) {
```
Comment (aduth) [inline packages/block-library/src/categories/index.php]: I agree we shouldn't want to recreate validation in the render callback. Ideally this is validated at the attribute definition, i.e. [via `enum`](https://json-schema.org/understanding-json-schema/reference/generic.html#enumerated-values).

I expect this is encompassed in part by #2751.

Separately, we can plan to support `enum` validation in the client implementation. Maybe a near-term compromise is adding expected alignments as an `enum` in the attribute definition to be ready when this is "turned on". Though, ideally this would be handled automatically when opting into align supports, not the responsibility of each block implementer to define.

**Review by aduth — APPROVED** [review]
Confirmed this fixes the observed bug. 👍 

Noted some potential ideas for future enhancements to consider.

File: packages/block-library/src/categories/index.php (hunk 1 above)
Comment (aduth) [reply packages/block-library/src/categories/index.php]: The `register_block_type` PHP function can accept the same options as what exists in the client today. They are passed down and shallowly† merged with client registration. With #2751, the idea is that the server would be the primary location where blocks be registered.

† All of `attributes` must be defined in the server or in the client, not fragments amongst both.

Comment (aduth) [reply packages/block-library/src/categories/index.php]: My hope is to actually kill off `getEditWrapperProps` ([example](https://github.com/WordPress/gutenberg/pull/7841#issuecomment-406319849)).

I don't think we want to be validating there either. As-is, I think it'd be sufficient to just pass through any non-`undefined` as `data-align`, not too much unlike how we've done with the frontend class rendering here?

Comment (ZebulanStanphill) [reply packages/block-library/src/categories/index.php]: @aduth Alright then, I have created a new PR to do just that and move the attributes from JS to PHP for the Categories block: #10635.
