### PR TITLE
Navigation: Try always showing appender even when child is selected.

### LINKED ISSUE #37572: Navigation block: missing inline + inserter to add new menu items without selecting parent block
### Description

I cannot see a quick inserter for adding additional navigation items unless I select the overall parent block. Previously, I was able to see a + in line to quickly add menu items. Now I have to add an item and select the overall parent block once more in order to add additional links to the menu. This seems to be a regression at worst and a step backwards for UX either way by adding additional not terribly intuitive steps. cc @jasmussen for insights :D 

### Step-by-step reproduction instructions

1. Add a navigation block.
2. Add a new link to a page or post.
3. See that there isn't a + option to quickly add more items.
4. Select the overall parent navigation block in order to see the option return. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/147023235-103ac2c4-4c7f-4b2a-861b-a795030292f5.mov

### Environment info

- No Gutenberg
- WordPress
- Twenty Twenty-two theme
- WordPress  5.9-beta4-52408

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

Fixes #37572. This PR is a draft as it needs a good sanity check, parts of the code are loaned from a similar change we made to submenus in #36720.

When manually building out a navigation block, the effort in #34041 is geared towards quickly adding items and choosing their destination. A separate effort in #36605 was merged to ensure we avoid layout shifts in the site editor. Those layout shifts occurred because the default appender would appear in the content and take up space when selected.

Both of those efforts are important, improvements are planned for both. But in the mean time, the experience of building out a navigation block from scratch has taken a step backwards, needing for the navigation container block itself to be selected to surface the appender:

nav-before

While there are mitigations (just open the top left inserter and add as many items as you want) it's not an ideal interim state. This PR makes a change to the default appender behavior, and shows it even when a child block is selected:

nav-after

This change has its own tradeoffs:

- It is a nonstandard behavior compared to Buttons and Social Icons.
- It's hacky, re-colorizing and repurposing the ButtonBlock appender to look like the default one.
- The fixed position appender plus benefits from sitting on the blue selection-border (see first GIF), without it it just floats in space.

Ultimately these interfaces all need more work. For example the need to manually build out a menu can be reduced by loading pages by default (see also #36667), or by enabling navigation to be edited in isolation just like template parts. The sibling inserter (the blue line) could also potentially replace the little black in-canvas plus entirely, by enabling it to work before first block or after the last block:

Screenshot 2021-12-28 at 10 12 53

But those aren't near-term changes. In that light, this PR should be thought of (and comments reflect that) as a temporary solution: a bandaid we should work to remove. What do you think?

## How has this been tested?

Insert a navigation block, start empty, then add multiple top level navigation items. 

Test submenus and all other options for good measure.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by annezazu** [comment]
Thanks so much for taking into consideration the feedback a few of us gave. I'm always so impressed by how you dig into the details, surface, and find sound solutions. In testing this out, this feels **a lot** better and smoother. Simply having an easy to see + button in the navigation block experience goes a long way. Without it, it feels clunky or like something is broken. For some reason, this feeling never has come up with the Button or Social Icons block and I can't put my finger on why. I think if I had to guess, it's because the Navigation block feels more like a "builder" or container compared to the button or social icons. I expect to have more options to add since there are more options to build out with it.

**Comment by jasmussen** [comment]
I've rebased this one just to shepard it along, and it still works as originally outlined, showing the parent add button even when a child is selected:
nav

My original concerns remain, this is bespoke software for the navigation block. That should generally be the exception, as it fragments the experience and might paint over issues that should be fixed at the source. At the same time, it's small, and good to have around in case this issue resurfaces. I'll mark this one as ready for review to gather some more thoughts.

File: packages/block-library/src/navigation/edit/inner-blocks.js [hunk 1]
```diff
@@ -39,7 +40,6 @@ const LAYOUT = {
 export default function NavigationInnerBlocks( {
 	isVisible,
 	clientId,
-	appender: CustomAppender,
```
Comment (tellthemachines) [inline packages/block-library/src/navigation/edit/inner-blocks.js:42]: I'm not sure if this is still being used by the navigation screen; might be worth preserving the option of passing in a custom appender.

**Review by tellthemachines — APPROVED** [review]
This works really well, and has the added bonus of making it much easier to add nav items with just the keyboard, which is currently really painful to do. 

It is a hacky approach, but would also be welcome in Social Icons where it's seemingly impossible to add children with keyboard only. Perhaps something like this could be implemented as a toggle on the default appender?

File: packages/block-library/src/navigation/edit/inner-blocks.js (hunk 1 above)
Comment (jasmussen) [reply packages/block-library/src/navigation/edit/inner-blocks.js:42]: I'm not sure how to best address this feedback item, but feel free to push to the branch if you like.

**Comment by jasmussen** [comment]
> It is a hacky approach, but would also be welcome in Social Icons where it's seemingly impossible to add children with keyboard only. 

For social links specifically, right now it's using a custom URL dialog, and could definitely benefit from a bigger refactor, not just to solve the keyboard issue but to improve the whole flow. 

> Perhaps something like this could be implemented as a toggle on the default appender?

I'd like to see this. It's the hackiness and inconsistency about this implementation that worries me the most.

Longer term it still seems possible for the sibling inserter to be improved to a point where it can entirely replace the black plus.

File: packages/block-library/src/navigation/edit/inner-blocks.js (hunk 1 above)
Comment (tellthemachines) [reply packages/block-library/src/navigation/edit/inner-blocks.js:42]: I played around with it and realised the previous code wasn't working on the nav editor (probably due to the changes we made to the block late last year) so I just removed the prop being passed to NavigationInnerBlocks altogether.

**Comment by tellthemachines** [comment]
> It's the hackiness and inconsistency about this implementation that worries me the most.
> Longer term it still seems possible for the sibling inserter to be improved to a point where it can entirely replace the black plus.

Agreed, let's get this in as a quick fix and look at a better long term solution later. The sibling inserter needs work on keyboard a11y too. 
As it is, this PR fixes #20741 too 🎉

**Comment by jasmussen** [comment]
Thank you for the help! I took it for a spin and things are still working as expected. In context of the discussion, I'd be happy to try this, so let's land this one and follow up.
