### PR TITLE
Fix tab panel initial tab selection

### LINKED ISSUE #47079: Navigation Block List View: Open the inspector on the correct tab after editing an item
### Description

When editing an item in the Navigation Block List View, the back button now takes you back to the "styles" tab of the block, not the "list view" tab:

https://user-images.githubusercontent.com/275961/211866551-82d1a23b-de5f-4df7-af6c-81365f0146b3.mov

The experience should be to return to the list view tab.

### PR DESCRIPTION
**Pull request by talldan**
## What?
Fixes https://github.com/WordPress/gutenberg/issues/47079

## Why?
From what I can tell there are two causes of the bug:
1. The Navigation block's List View tab isn't declared on first render, it only becomes present in the `tabs` array on later renders.
2. The TabPanel no longer supports lazily adding initial tabs after #46471, it now always falls back to the first enabled tab in the `tabs` array.

I did try looking to see if this could be fixed by always rendering the tab navigation block, but it's less than straightforward. The tab is added somewhat dynamically when there are fills in a slot. I struggled to see where the issue was coming from.

## How?
This fixes the issue. If `initalTabName` is declared, but there's no matching tab in the `tabs` array, the effect no longer makes a selection until it is in the tabs array.

This does leave a situation where `initalTabName` could be declared and the matching tab is never present, but I'd consider this implementor error (and the same issue could happen before #46471).

I have refactored the code a bit here too. I personally found the code a little hard to understand with the added logic, so it's now a little more verbose, but hopefully easier to follow. 

## Testing Instructions
1. Add a navigation block to a post and add some inner blocks to it
2. In the nav block's block inspector List View interface, select the 'Edit block' button of one of the inner blocks
3. Press the 'Go to parent'  button at the top of the inspector panel when that inner block is selected.

Expected - the List View tab should be selected again on the navigation block.
In trunk - the Appearance tab is selected.

#### Before

https://user-images.githubusercontent.com/677833/211992292-174d6178-aa6d-410b-9ff4-562e29a930c9.mp4

#### After

https://user-images.githubusercontent.com/677833/211992314-910b3316-8e98-4d98-8cea-d19a1aad1666.mp4

### CODE REVIEW

File: packages/components/src/tab-panel/index.tsx [hunk 1]
```diff
@@ -103,25 +103,47 @@ export function TabPanel( {
...
+		// This effect only runs when the selected tab is defined and becomes disabled.
+		if ( ! selectedTab?.disabled ) {
+			return;
+		}
+
+		const firstEnabledTab = tabs.find( ( tab ) => ! tab.disabled );
+
+		// If the currently selected tab becomes disabled, select the first enabled tab.
+		// (if there is one).
+		if ( firstEnabledTab ) {
```
Comment (talldan) [inline packages/components/src/tab-panel/index.tsx:143]: The previous code didn't do so, but the component should probably consider a case where all tabs are disabled.

It might be handled elsewhere in the component though, I haven't really checked.

**Review by scruffian — APPROVED** [review]
LGTM

**Comment by ciampo** [comment]
Thank you both for flagging the issue and working on a fix so quickly 🙏
