### PR TITLE
Layout: Fix issue where saving user global styles included layout definitions in layout settings

### LINKED ISSUE #50238: Site Editor: Export includes layout definitions from lib/theme.json
Extracting from https://github.com/WordPress/create-block-theme/issues/324#issuecomment-1530010529, and related to #49914 with further context in https://github.com/WordPress/gutenberg/issues/49914#issuecomment-1524404291.

When you build a theme in the site editor, then export it using the ellipsis > Export option, the theme.json file includes `settings.layout.definitions` in the export. 

Screenshot 2023-05-02 at 08 43 57

These definitions should only ever be in the core theme.json, as they are used to build the core styles for each layout type. They should never be in theme files, as they are now. #49914 is an example of what can happen when they are included, that is: any bugs present in the layout definitions when the theme was exported get permanently applied to the theme, since those definitions override the core definitions. Additional results could be that any new features applied to layout in newer versions of theme.json will invisibly fail or just not work.

Steps to reproduce:

* Activate a block theme like TT3
* Go to global styles and make a change to the global layout like editing the default content width
* Use the site editor to export the theme

Observe how it includes all definitions copied over from lib/theme.json.

This is urgently in need of fixing, lest every theme created until fixed, will have hard-to-debug future layout issues.

### PR DESCRIPTION
**Pull request by andrewserong**
## What?

Fixes https://github.com/WordPress/gutenberg/issues/50238 (potentially)

Update the global styles logic when settings are updated to exclude layout definitions. This will cause the `definitions` object to no longer be saved within the user data of global styles. For any sites that already have the definition saved in their user data, they can either clear their customizations, or make a change to `contentSize` or `wideSize` and re-save, to flush the `definitions` object from their user data.

## Why?

In https://github.com/WordPress/gutenberg/pull/48070/ the `DimensionsPanel` was refactored to be used across both the block editor and in the site editor / global styles. In that refactor, we missed that before the refactor `contentSize` and `wideSize` were updated individually within the `layout` object, rather than getting and saving the whole layout object when settings were updated. The switch away from this resulted in the `definitions` object accidentally being included in the user data.

As a result, if a user goes to export their theme, the `definitions` object was included in the export, since it was included in the user saved styles.

## How?

* Before updating the global styles settings, strip the updated layout object of the `definitions` object.

## Testing Instructions

* Open up global styles, and make a change to `contentSize` or `wideSize`, then save the global styles.
* In the ellipsis menu of the site editor, select `Export` under `Tools` to download a `.zip` file of your theme.
* In the exported `.zip` file, within the `theme.json` file, there should be no `settings.layout.definitions` key.
* Double-check that on your site, all layout styles are still working as expected (e.g. test that Stack and Row blocks still work, and their block spacing still works)

### CODE REVIEW

**Comment by andrewserong** [comment]
I'll be AFK tomorrow, so if this change looks good to land, please feel free to merge it in if anyone would like to! Separately to this PR, we can also explore follow-ups that strip the layout definitions from being returned by the `theme.json` classes if the origin is not default (the core theme.json data).

@bph I'm not sure if this PR will make it in, in time, but I've added the `Backport to Gutenberg RC` label just in case it lands prior to 15.7 going out.

Thanks, all!

**Comment by tellthemachines** [comment]
I just followed the testing instructions on trunk and don't see a layout definitions object in the downloaded theme.json. Maybe something's wrong with my local dev env?

**Comment by andrewserong** [comment]
Thanks for testing @tellthemachines — I might have missed a step in the Testing Instructions. I had to save the global styles change (with the `contentSize` difference) before I saw the `definitions` in the exported zip file. I've just updated the notes.

**Review by ramonjd — APPROVED** [review]
This works for me. Thanks for the quick fix @andrewserong 

Here's what I'm seeing when I export my theme.json changes:

TRUNK

```json
		"layout": {
			"contentSize": "777px",
			"definitions": {
				"constrained": {
					"baseStyles": [
						{
							"rules": {
								"float": "left",
								"margin-inline-end": "2em",
								"margin-inline-start": "0"
							},
							"selector": " > .alignleft"
						},
						{
							"rules": {
								"float": "right",
								"margin-inline-end": "0",
								"margin-inline-start": "2em"
							},
							"selector": " > .alignright"
						},
...
         },
			"wideSize": "2222px"
```

THIS PR

```json
		"layout": {
			"contentSize": "777px",
			"wideSize": "2222px"
		},
```

**Review by tellthemachines — APPROVED** [review]
Thanks for updating the testing steps! I must have forgotten to save changes before exporting. It's working for me now: I can see the definitions on trunk, and can confirm that following the same steps on this branch results in no definitions.

Code looks good!

**Comment by andrewserong** [comment]
Thanks for the reviews, folks, much appreciated! I'll merge this in now, and happy to look into follow-ups for filtering the theme.json data next week if we feel like we'll need it.

**Comment by bph** [comment]
I just cherry-picked this PR to the release/15.7 branch to get it included in the next release: e1113e547b

File: packages/edit-site/src/components/global-styles/dimensions-panel.js [hunk 1]
```diff
@@ -62,10 +62,14 @@ export default function DimensionsPanel( { name, variation = '' } ) {
...
 
 		if ( newStyle.layout !== settings.layout ) {
-			setSettings( {
-				...rawSettings,
-				layout: newStyle.layout,
-			} );
+			const updatedSettings = { ...rawSettings, layout: newStyle.layout };
+
+			// Ensure any changes to layout definitions are not persisted.
+			if ( updatedSettings.layout?.definitions ) {
```
Comment (youknowriad) [inline packages/edit-site/src/components/global-styles/dimensions-panel.js:68]: What are these definitions? and why do we need them for blocks but not global styles?

**Comment by jasmussen** [comment]
Thanks for this PR, the urgent part was ensuring the definitions were not included in theme.json upon theme export. But it'd be good to follow up on Riad's note.

File: packages/edit-site/src/components/global-styles/dimensions-panel.js (hunk 1 above)
Comment (tellthemachines) [reply packages/edit-site/src/components/global-styles/dimensions-panel.js:68]: The definitions live in `settings.layout` in the [core theme.json](https://github.com/WordPress/gutenberg/blob/trunk/lib/theme.json#L223), and they provide the base styles for each layout type. They're used everywhere layout exists: blocks, root containers and global styles, but they're not meant to be overridden by themes. I suppose it would theoretically be possible for themes to define their own layout rules, but that use case isn't really supported right now.

Comment (youknowriad) [reply packages/edit-site/src/components/global-styles/dimensions-panel.js:68]: What's the reason for these leaving in "core theme.json" if these are meant to be "static". Can't we just put them in a file in our code base?

Comment (tellthemachines) [reply packages/edit-site/src/components/global-styles/dimensions-panel.js:68]: Initially we were operating on the assumption that these definitions would work like default values, and might be extendable by themes at some point in the future. But looking at it now, layout support logic is perhaps too complex to easily allow for extendability, so it might be better to move these somewhere else.

Comment (andrewserong) [reply packages/edit-site/src/components/global-styles/dimensions-panel.js:68]: Agreed. Originally, part of the idea of placing the definitions in `theme.json` was that we might one day be able to make all the layout options declarative and keep the rules in a centralised place so that we could reduce duplication between the JS and PHP implementations of layout. We did reduce some of the duplication by centralising, but as @tellthemachines mentions, the layout support logic is likely too complex to easily support purely declarative layout types. E.g. originally I was wondering if we could get to a point where you might add additional layout types by simply adding an additional definition, and then the editor would know based on that definition which controls to display, etc.

However, that direction is likely a lot more work than the benefits it might yield, and I agree that it could be good to revisit the approach of storing the definitions in `theme.json`. So, if we were to move them elsewhere, what might that look like? One possible idea:

* What if we defined the layout definitions in PHP, say hard-coded in `layout.php` and returned them via `get_layout_definitions`.
* Then, in block editor settings, we could add the definitions, JSON-ified, so that the JS code grabs layout definitions from block editor settings.
* In all PHP usage, we'd use `get_layout_definitions` instead of pulling from the global styles data.

Would something like that sound do-able / preferable to what we have now? If we like that kind of idea, I'm happy to hack around a bit and see how feasible it is.

In terms of extensibility, if or when we ever wanted to allow themes to extend the layout definitions, we could either add hooks to make the layout definitions filterable, _or_ re-introduce the definitions to `theme.json`, but grab them from within `get_layout_definitions`.

Comment (youknowriad) [reply packages/edit-site/src/components/global-styles/dimensions-panel.js:68]: For me, and since these are more implementation details of the layouts instead, I'd move them to the code directly. There's already duplication between a lot of block supports between frontend and backend so I wouldn't mind if they're duplicated too to avoid extra APIs. I also feel like maybe it's a wrong abstraction as I don't see why a layout can be "declarative" but I'll leave that decision to you, the main thing for me is that we should remove these from theme.json.

Comment (andrewserong) [reply packages/edit-site/src/components/global-styles/dimensions-panel.js:68]: Okay, cool, thanks for the feedback. I'll have a play once I'm back from AFK and will explore our options 👍
