### PR TITLE
Block Styles: Fix block style variation styles for blocks with complex selectors

### LINKED ISSUE #62122: Double border on buttons with outline variation applied
### Description

When adding a button and applying the outline variation, a double border is being applied. **(issue exists on front end, not in editor)** It appears that there are two instances of classes/styling being applied—one to the `<div>` and the other to the `<a>`:

```
<div class="wp-block-button is-style-outline is-style-outline--8b999049ec2131a13968b599677970ef">
<a class="wp-block-button__link wp-element-button" href="#">Learn More</a>
</div>
```

First set of styles, to the `<div>`:

```
:root :where(.is-style-outline--cb3c5e7393271d2adb5a2454ddebf7f6) {
    background: transparent none;
    border-color: currentColor;
    border-width: 1px;
    border-style: solid;
    color: currentColor;
    padding-top: calc(0.6rem - 1px);
    padding-right: calc(1rem - 1px);
    padding-bottom: calc(0.6rem - 1px);
    padding-left: calc(1rem - 1px);
}
```

Second set of styles, to the `<a>` (note some specificity overriding happening to the below):

```
:root :where(.wp-block-button.is-style-outline .wp-block-button__link) {
    background: transparent none;
    border-color: currentColor;
    border-width: 1px;
    border-style: solid;
    color: currentColor;
    padding-top: calc(0.6rem - 1px);
    padding-right: calc(1rem - 1px);
    padding-bottom: calc(0.6rem - 1px);
    padding-left: calc(1rem - 1px);
}
:root :where(.wp-element-button, .wp-block-button__link) {
    background-color: var(--wp--preset--color--contrast);
    border-radius: .33rem;
    border-color: var(--wp--preset--color--contrast);
    border-width: 0;
    color: var(--wp--preset--color--base);
    font-family: inherit;
    font-size: var(--wp--preset--font-size--small);
    font-style: normal;
    font-weight: 500;
    line-height: inherit;
    padding-top: 0.6rem;
    padding-right: 1rem;
    padding-bottom: 0.6rem;
    padding-left: 1rem;
    text-decoration: none;
}
```

### Step-by-step reproduction instructions

1. Go to post editor.
2. Add button block, apply outline variation.
3. See issue. (note issue exists on front end, not in editor)

### Screenshots, screen recording, code snippet

image

### Environment info

WordPress 6.5.3, Gutenberg Nightly (Version 18.6.20240529)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Fixes: https://github.com/WordPress/gutenberg/issues/62122

## What?

Fixes the style generation for instanced block style variations for blocks that use complex selectors. For example:
- Button: `.wp-block-button .wp-block-button__link`
- Image: 
   - `.wp-block-image`
   - `.wp-block-image img, .wp-block-image .wp-block-image__crop-area, .wp-block-image .components-placeholder`

## Why?

Without this fix, variation styles when applied to an instance would only be applied to the block's wrapper. This means styles like the Button block's outline block style would get double borders, padding et.c

## How?

Reworks the generation of the instanced block style variation stylesheets so that the result has selectors that apply different types of styles to the block's desired elements. For example, the Button block styles go to the inner `.wp-block-button__link` element or an Image's border goes to the inner `img`

The style load order was also tweaked to ensure the block style variations styles were loaded after the block library styles. 

## Testing Instructions

1. Register some custom block style variations following [#57908](https://github.com/WordPress/gutenberg/pull/57908)'s instructions
2. Apply these in a nested fashion and ensure they still continue to work
3. Make sure you have a button block in your post or page
4. Apply the outline block style to the button
5. Make sure all the blocks display correctly in both editors and the frontend
6. Disable separate core block assets via snippet below or activate a theme which does such as [Powder](https://github.com/bgardner/powder/tree/main)
7. Confirm block library styles do not override the outline block style variation styles for Button blocks

`add_filter( 'should_load_separate_core_block_assets', '__return_false' );`

## Screenshots or screencast 

| Before | After |
|---|---|
| Screenshot 2024-05-30 at 4 25 25 PM | Screenshot 2024-05-30 at 4 25 08 PM |

### CODE REVIEW

**Comment by aaronrobertshaw** [comment]
The changes here have been included within the overall backport for the section styles feature: https://github.com/WordPress/wordpress-develop/pull/6662.

If this PR requires further updates, that backport will also need updating.

File: lib/block-supports/block-style-variations.php [hunk 1]
```diff
@@ -79,31 +79,63 @@ function gutenberg_render_block_style_variation_support_styles( $parsed_block )
...
 	}
 
-	$config = array(
-		'version' => WP_Theme_JSON_Gutenberg::LATEST_SCHEMA,
-		'styles'  => $variation_data,
-	);
-
 	$class_name         = gutenberg_get_block_style_variation_class_name( $parsed_block, $variation );
 	$updated_class_name = $parsed_block['attrs']['className'] . " $class_name";
+	$variation_instance = substr( $class_name, 9 );
```
Comment (talldan) [inline lib/block-supports/block-style-variations.php]: It feels unusual now that the class name is created, to immediately remove part of it here.

Maybe `gutenberg_get_block_style_variation_class_name` could be changed to `gutenberg_get_block_style_variation_instance`, and then the `is-style-` part appended on after (there could still be a `gutenberg_get_block_style_variation_class_name` function if needed for that but it accepts the variation_instance).

File: lib/block-supports/block-style-variations.php [hunk 2]
```diff
@@ -79,31 +79,63 @@ function gutenberg_render_block_style_variation_support_styles( $parsed_block )
...
+	$class_name         = ".$class_name";
+
+	/*
+	 * To support blocks with more complex selectors, that can apply styles to
+	 * inner markup or even different inner elements depending on the feature,
+	 * the variation style data needs to be manipulated some. If the root variation
+	 * styles are moved under a variations property they will generate as desired.
```
Comment (talldan) [inline lib/block-supports/block-style-variations.php]: I'm not quite following this TBH, might need to explain it more. 😄

**Review by talldan — COMMENTED** [review]
It does fix the issue, but I don't understand the fix, so I'd have a hard time approving it.

I do notice there are two sets of identical styles:
Screenshot 2024-05-30 at 4 31 04 pm

If there's any way to avoid that it might be good, but it could be considered a separate change.

File: lib/block-supports/block-style-variations.php (hunk 2 above)
Comment (aaronrobertshaw) [reply lib/block-supports/block-style-variations.php]: I was trying to avoid writing an essay here. Would linking to the issue and PR help?

Comment (aaronrobertshaw) [reply lib/block-supports/block-style-variations.php]: I have a better idea on how best to explain this bit of the code now. I'll update the inline comment shortly.

For the discussion on this PR though:

The crux of the issue is that blocks can define their own selectors to direct certain styles to inner parts of the blocks markup. For example, the inner `img` element for an Image block needs to get the border styles whereas the other styles might still belong on the outer `figure` wrapper for the block.

Previously, the variation's data was treated as its own "theme.json partial". The problem here is that root styles for theme.json don't have the ability to be directed to inner parts as that's what the `styles.elements` and `styles.blocks` properties do.

The fix in this PR essentially moves the variation's root styles to under the `styles.blocks` property so that the block's custom selectors can be honored.

Comment (aaronrobertshaw) [reply lib/block-supports/block-style-variations.php]: Done https://github.com/WordPress/gutenberg/pull/62125/commits/2f33a3d130d8a84f4659c6f94e88abc2f9063430

File: lib/block-supports/block-style-variations.php (hunk 1 above)
Comment (aaronrobertshaw) [reply lib/block-supports/block-style-variations.php]: Done https://github.com/WordPress/gutenberg/pull/62125/commits/a4662f2256a08331ec8685e919e1b97297910a67

I'll update the backport accordingly shortly.

**Comment by aaronrobertshaw** [comment]
Appreciate the thorough review @talldan 🙇 

I believe I've addressed all the feedback so far. Should be good to go for another spin now.

> If there's any way to avoid that it might be good, but it could be considered a separate change.

I think that is definitely best done via a separate follow-up. 

For the record, one set of styles is from the standard theme.json stylesheet but can't be relied upon as if variations are nested the load order needs to be different for the correct variation's styles to take precedence. That's where the second set of styles comes in as they are the styles specific to this individual application or instance of the block style variation.

The code creating the standard set of styles is actually leveraged to generate the individual instance styles. 

It is 100% something that would be good to clean up. Right now though, I think we need to land a fix for the issue affecting outline buttons etc. then I can circle back to this optimisation and clean up.

**Comment by bgardner** [comment]
@aaronrobertshaw 

There seems to still be an issue with specificity and styles. My Powder theme which uses theme.json to style the outline variation (https://github.com/bgardner/powder/blob/main/theme.json#L288) is being overridden by the following:

```
:root :where(.wp-block-button .wp-block-button__link.is-style-outline), :root :where(.wp-block-button.is-style-outline>.wp-block-button__link) {
    border: 2px solid;
    padding: .667em 1.333em;
}
```

**Comment by bgardner** [comment]
The button should have a border of 1px thick, but looks like this (note the lower right side styles being overridden:

image

**Comment by aaronrobertshaw** [comment]
Thanks for the extra information @bgardner, it definitely helps 👍 

After downloading your theme and poking around a bit, it looks like the style load order isn't quite right. The key difference I noted while testing was that Powder disables the separate block assets via the `should_load_separate_core_block_assets` filter.

The `wp-block-library-inline-css` styles are added after the global styles and block style variation styles. When the block styles are separated however their individual stylesheets are loaded before the global styles and variation styles.

I'll work on a fix for this first thing tomorrow. It might also be better as a separate PR.

| Separate Block Assets | All Together |
|---|---|
| Screenshot 2024-05-30 at 11 39 24 PM | Screenshot 2024-05-30 at 11 29 52 PM |

_Note: The separate assets screenshot is actually TT4 but illustrates the point._

**Comment by bgardner** [comment]
@aaronrobertshaw That makes sense, thanks for spelling that out. If there's an alternative (more optimal) way for me to handle things in Powder, I'm all ears.

**Comment by aaronrobertshaw** [comment]
> If there's an alternative (more optimal) way for me to handle things in Powder, I'm all ears.

I don't think you should need to make any changes here. Hopefully, a bit of tweaking to the order styles load in should see this working as expected.

**Comment by aaronrobertshaw** [comment]
@bgardner with fresh eyes this morning it looks like the tweak the load order is rather trivial so I've rolled it into this fix.

| Before | After |
|---|---|
| Screenshot 2024-05-31 at 9 55 29 AM | Screenshot 2024-05-31 at 9 55 09 AM |

**Comment by bgardner** [comment]
@aaronrobertshaw Can confirm, per the below. LGTM!

image

**Review by talldan — APPROVED** [review]
Looks good now, thanks for adding the improved explanations in the code, that helped me understand the issue and fix.

**Comment by aaronrobertshaw** [comment]
Appreciate all the reviews and testing. Thanks @talldan and @bgardner 🙇
