### PR TITLE
Gradient: Fix clearing a custom gradient from throwing a React warning

### LINKED ISSUE #36899: Gradients: errors resulting from clearing or quickly selecting gradient colors in background color
### Description

While working on a fix for #36640, I noticed a couple of errors being generated via the gradient color picker.

#### Issues to resolve

1. [x] With a blocks theme active, while I select between gradients, and then click the Clear button (or deselect the gradient) an error is thrown.
2. [x] If I go to select a custom color for one part of the gradient and then pan quickly while selecting colors, the block crashes. (Fixed in: https://github.com/WordPress/gutenberg/pull/36941)

### Step-by-step reproduction instructions

1. Activate a blocks-based theme (e.g. TwentyTwentyTwo)
2. Add a Group block to a post
3. Add a gradient background color to the block, and see if you can recreate the above two scenarios

## Scenario 1 (error caused by clearing gradient)

Kapture 2021-11-26 at 16 57 06

Error message:

image

## Fixed: Scenario 2 (failure caused by moving the mouse rapidly across the color picker)

Kapture 2021-11-26 at 17 03 44

Error message:

image

### Environment info

- Gutenberg trunk
- TwentyTwentyTwo theme
- macOS, Google Chrome Version 96.0.4664.55 (Official Build) (arm64)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by andrewserong**
## Description

Fixes #36899

This PR updates the `withColorPaletteStyles` function in the Color block support to not return empty `color` and `backgroundColor` keys. This fixes a React warning that gets thrown when clearing a custom gradient used on a block's background color. To provide extra context:

The color gradient gets stored using the `background` shorthand. When we clear a gradient, the `background` style gets cleared, however in `withColorPaletteStyles` the `backgroundColor` is _also_ being set to `undefined`. Unfortunately for us, React treats this undefined value as us updating the style for the component, even though it has no visual effect. We receive the following warning in the console:

image

By explicitly ensuring that we don't set the `backgroundColor` property, we avoid throwing the React warning. Note: this fix is preferable to updating how we store the gradient value, so that we don't have to change how the gradient is saved in post content.

## How has this been tested?

1. Add a custom gradient to a block (e.g. the Group block) — a custom gradient is one that you select from the gradient slider, rather than the circular gradient preset buttons.
2. Before applying this PR, with your browser console window open, click the Clear button on the gradient
3. Notice the React warning in the console
4. With this PR applied, there should be no warning

## Screenshots 

| Before | After |
| --- | --- |
| Kapture 2021-12-02 at 15 51 27 | Kapture 2021-12-02 at 15 49 54 |

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-editor/src/hooks/color.js [hunk 1]
```diff
@@ -454,15 +454,20 @@ export const withColorPaletteStyles = createHigherOrderComponent(
...
-				: undefined,
-			backgroundColor: backgroundColor
-				? getColorObjectByAttributeValues( colors, backgroundColor )
-						?.color
-				: undefined,
-		};
+		const extraStyles = {};
+
+		if ( textColor ) {
+			extraStyles.color = getColorObjectByAttributeValues(
```
Comment (oandregal) [inline packages/block-editor/src/hooks/color.js:460]: This is a good fix.

However, inspecting `getColorObjectByAttributeValues` there's a path in which the resulting `color` value still can be `undefined`: when passing a `textColor` that is not present in the list of `colors`. This can happen upon switching themes, for example. Specific steps:

- Use TwentyTwentyTwo.
- Add a paragraph and select a preset text color from the theme.
- Switch to EmptyTheme.

At this point, the text color is undefined. I wonder if `getColorObjectByAttributeValues` should return `null` instead of `undefined` for such a case.

Though at the moment this is not reproducible because we have a bug in `trunk` by which the preset colors are serialized as inline styles and not as classes. Going to follow up https://github.com/WordPress/gutenberg/issues/36770

**Review by oandregal — APPROVED** [review]

**Comment by oandregal** [comment]
The failing test (`Block_Fixture_Test::test_kses_doesnt_change_fixtures`) is unrelated. Given the time-sensitive period we're in, I'm going to go ahead and merge this PR.

File: packages/block-editor/src/hooks/test/color.js [hunk 2]
```diff
@@ -10,3 +22,100 @@ describe( 'cleanEmptyObject', () => {
...
+						backgroundColor: 'vivid-green-cyan',
+						textColor: 'pale-pink',
+					} }
+					name="core/test-block"
+					getStyleObj={ getStyleObj }
+				/>
+			</BlockEditorProvider>
+		);
+
+		expect( getStyleObj ).toHaveBeenLastCalledWith( {
```
Comment (ntsekouras) [inline packages/block-editor/src/hooks/test/color.js:89]: This test is failing on `trunk` right now. I'm looking at it, but if you have quick thoughts, please share to fix them 😄

Comment (andrewserong) [reply packages/block-editor/src/hooks/test/color.js:89]: Thanks Nik! I _think_ this one might potentially be resolved as of https://github.com/WordPress/gutenberg/pull/37108, which has just been merged in. I'll keep an eye on `trunk` just in case, and happy to follow-up if there are more issues.
