### PR TITLE
Fix entity binding not cleared when unsyncing and entering custom URL in Nav block

### LINKED ISSUE #72203: Navigation: Remove bound url when replacing with a custom link
When testing https://github.com/WordPress/gutenberg/pull/72171 I discovered that editing a bound URL to a custom URL doesn't work. See this video for a demonstration:

https://github.com/user-attachments/assets/9e1dd25e-2ea9-49be-a17d-92dc0a1aec73

### PR DESCRIPTION
**Pull request by getdave**
## What

Fixes #72203

This PR fixes a bug where the entity binding was not properly cleared when a user clicks "Unsync" on an entity link and enters a custom URL.

## Why

When a navigation link is bound to an entity (post, page, taxonomy), users can click the "Unsync" button to unlock the URL field and change it. However, when typing a custom URL (not selecting from suggestions) and submitting, the entity binding was not being cleared. This caused:

1. The `metadata.bindings.url` to remain intact
2. The `id`, `kind`, and `type` attributes to persist
3. The URL to not update to the expected custom value

The root cause was in `LinkControl`'s `handleUnlink()` function. It destructured `id` out of `internalControlValue` but didn't explicitly set it to `undefined`. When `handleSubmit()` spread the values (`...value, ...internalControlValue`), the original entity properties from the `value` prop persisted through the spread, preventing the severing logic in `update-attributes.js` from detecting the change.

## How

Modified the `handleUnlink()` function in `LinkControl` to explicitly set `id`, `kind`, and `type` to `undefined`:

```javascript
const { id, kind, type, ...restValue } = internalControlValue;
setInternalControlValue( {
    ...restValue,
    id: undefined,
    kind: undefined,
    type: undefined,
    url: undefined
} );
```

This ensures these properties override the original entity values when spread in `handleSubmit()`, allowing the severing logic to work correctly.

Added comprehensive test coverage for this specific scenario: "should allow unlinking and entering a custom URL".

### Manual Testing

1. **Create an entity link:**
   - Add a Navigation block to a post/page
   - Add a Navigation Link item
   - Link it to an entity (e.g., select a Page from the suggestions)
   - Save and verify the link has `id`, `kind`, and `type` attributes in block markup

2. **Reproduce the original bug (before fix):**
   - Select the Navigation Link block
   - Open the Link UI (click to edit the link)
   - Click the "Unsync" button (unlink icon) to unlock the URL field
   - Type a custom URL: `www.wordpress.org`
   - Click "Apply" to submit
   - **Expected (with fix):** The URL updates to `www.wordpress.org`, and the entity binding (`metadata.bindings.url`) is removed, along with `id`, `kind`, and `type` attributes
   - **Previous behavior (bug):** The URL would not update, and the entity binding would remain

3. **Verify the existing use case still works:**
   - Create another entity link (link to a Page)
   - Click "Unsync" 
   - Select a **different entity** from the suggestions list
   - Verify the link updates to the new entity with correct `id`, `kind`, and `type`

### Automated Testing

Run the LinkControl unit tests:
```bash
npm run test:unit -- packages/block-editor/src/components/link-control/test/index.js
```

All 115 tests should pass, including the new test: "should allow unlinking and entering a custom URL"

## Screenshots

https://github.com/user-attachments/assets/cc126e2c-3b76-4d3c-8ee0-19eeaa4fa2a4

### CODE REVIEW

File: packages/block-editor/src/components/link-control/index.js [hunk 1]
```diff
@@ -352,9 +352,18 @@ function LinkControl( {
...
+		// the original values when spread in handleSubmit. This ensures that
+		// when the user types a custom URL and submits, the entity link is
+		// properly severed (not just when selecting a different entity from suggestions).
+		const { id, kind, type, ...restValue } = internalControlValue;
+		setInternalControlValue( {
+			...restValue,
+			id: undefined,
+			kind: undefined,
+			type: undefined,
+			url: '',
```
Comment (scruffian) [inline packages/block-editor/src/components/link-control/index.js]: Why set the URL to `''` but the other things to `undefined`?

**Review by scruffian — APPROVED** [review]
Fixes the problem, thank you!

File: packages/block-editor/src/components/link-control/index.js (hunk 1 above)
Comment (getdave) [reply packages/block-editor/src/components/link-control/index.js]: A reasonable point. I was thinking it's "resetting to empty value" but actually that's silly. Maybe it would be fine to make it all `undefined`?

Comment (getdave) [reply packages/block-editor/src/components/link-control/index.js]: I tested and it's better to reset to `undefined`. All tests still pass.

**Comment by getdave** [comment]
Some thing is breaking with PHP tests across the repo. Hopefully a rebase will allow this one to merge
