### PR TITLE
Fix/screen reader text

### LINKED ISSUE #18167: Switch screen-reader-text to use VisuallyHidden
**Describe the Issue**

This issue is to gather all the spots for changing spots using the `screen-reader-text` classname to using the VisuallyHidden component. Per comment in #18127 

A good reference implementation is PR #18165 that converts within the components package the spots that use `screen-reader-text` to `VisuallyHidden` component.

**Why the switch?**

See #18022 which introduced the `VisuallyHidden` component. The usage of `screen-reader-text` assumes a WordPress context with the proper CSS already defined. This may not always be the case, especially when pieces of the Gutenberg project are used elsewhere.

**File list with `screen-reader-text`**

- [ ] packages/block-library/src/categories/edit.js
- [ ] packages/block-library/src/archives/index.php
- [ ] packages/block-library/src/gallery/edit.js
- [ ] packages/components/src/button/style.scss
- [ ] packages/editor/src/components/post-visibility/index.js
- [ ] packages/editor/src/components/post-title/index.js
- [ ] packages/editor/src/components/post-text-editor/index.js
- [ ] packages/editor/src/components/post-preview-button/index.js
- [ ] packages/block-editor/src/components/button-block-appender/index.js
- [ ] packages/e2e-tests/specs/editor/various/taxonomies.test.js
- [ ] packages/block-editor/src/components/inserter/menu.js
- [ ] packages/block-editor/src/components/block-navigation/list.js
- [ ] packages/edit-post/src/components/admin-notices/test/index.js
- [ ] packages/editor/src/components/post-preview-button/test/__snapshots__/index.js.snap

@youknowriad - just wanted to confirm that you do what this updated across all of the above?

### PR DESCRIPTION
**Pull request by adamziel**
## Description

This PR solves https://github.com/WordPress/gutenberg/issues/18167 

See #18022 which introduced the VisuallyHidden component. The usage of `screen-reader-text` assumes a WordPress context with the proper CSS already defined. This may not always be the case, especially when pieces of the Gutenberg project are used elsewhere.

## How has this been tested?

Tested locally. This PR touches a number of blocks and components. For each of them, you need to check if the new `<VisuallyHidden>` part behaves in the same way as the old `.screen-reader-text`. For example, this PR touches a gallery block caption:

https://github.com/WordPress/gutenberg/pull/20607/files#diff-e25f8ba6320e6c1650e6ec1c0ae5ba34L43-L102

To test it, let's follow some steps:

1. Create a new gallery block
1. Confirm the caption is hidden when it's empty and the block is not selected
1. Confirm the caption is visible then it's empty and the block is selected
1. Confirm the caption is visible when it's not empty and the block is not selected
1. Confirm the caption is visible then it's not empty and the block is selected

Without this PR applied it should use CSS class `screen-reader-text` [(gif)](https://78h87h.files.wordpress.com/2020/03/2020-03-03-15-26-31.2020-03-03-15_59_09.gif)

With this PR applied it should use the new `VisuallyHidden` wrapper [(gif)](https://78h87h.files.wordpress.com/2020/03/2020-03-03-15-35-58.2020-03-03-15_43_45.gif)

## Types of changes
Non-breaking change which fixes #18167 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/block-editor/src/components/inserter/menu.js [hunk 1]
```diff
@@ -319,12 +323,13 @@ export class InserterMenu extends Component {
 				onKeyDown={ this.onKeyDown }
 			>
 				<div className="block-editor-inserter__main-area">
-					<label
-						htmlFor={ `block-editor-inserter__search-${ instanceId }` }
-						className="screen-reader-text"
-					>
-						{ __( 'Search for a block' ) }
-					</label>
+					<VisuallyHidden>
```
Comment (talldan) [inline packages/block-editor/src/components/inserter/menu.js]: It looks like this can be defined this as:
```jsx
<VisuallyHidden as="label" htmlFor={ `block-editor-inserter__search-${ instanceId }` }>
    { __( 'Search for a block' ) }
</VisuallyHidden>
```

which avoids the extra span around the label. I saw a few other places in the PR where that would be beneficial.

I noticed the `VisuallyHidden` docs don't mention this, could be a good follow up PR to update those docs 😄

File: packages/block-editor/src/components/link-control/settings-drawer.js [hunk 2]
```diff
@@ -44,9 +44,9 @@ const LinkControlSettingsDrawer = ( {
 
 	return (
 		<fieldset className="block-editor-link-control__settings">
-			<legend className="screen-reader-text">
-				{ __( 'Currently selected link settings' ) }
-			</legend>
+			<VisuallyHidden>
```
Comment (tellthemachines) [inline packages/block-editor/src/components/link-control/settings-drawer.js]: We need `<VisuallyHidden as="legend">` here. A `<legend>` must be the first direct descendant of a `<fieldset>`, so we can't have any intermediate wrappers.

File: packages/block-editor/src/components/responsive-block-control/style.scss [hunk 3]
```diff
@@ -43,5 +31,14 @@
 }
 
 .block-editor-responsive-block-control .components-base-control__help {
```
Comment (tellthemachines) [inline packages/block-editor/src/components/responsive-block-control/style.scss]: This doesn't feel right; if we need these styles here we should be applying them with whatever classname we're currently using to hide stuff from vision. Or we should be using `<VisuallyHidden>` if possible. Probably something to tackle in a follow-up PR though 😅. I don't think ResponsiveBlockControl is being used anywhere atm.

File: packages/block-editor/src/components/responsive-block-control/test/__snapshots__/index.js.snap [hunk 4]
```diff
@@ -1,3 +1,3 @@
...
...\"M0 0h2v6H0z\\"></path></svg></span><label for=\\"inspector-toggle-control-0\\" class=\\"components-toggle-control__label\\">Use the same padding on all screensizes.</label></div><p id=\\"inspector-toggle-control-0__help\\" class=\\"components-base-control__help\\">Toggle between using the same value for all screen sizes or using a unique value per screen size.</p></div><div class=\\"block-editor-responsive-block-control__group\\"><div class=\\"components-base-control\\"><div class=\\"components-base-control__field\\"><label class=\\"components-base-control__label\\" for=\\"inspector-select-control-0\\"><span aria-describedby=\\"rbc-desc-0\\">All</span><div class=\\"components-visually-hidden\\" id=\\"rbc-desc-0\\">Controls the padding property for All viewports.</div></label><select id=\\"inspector-select-control-0\\" class=\\"components-select-control__input\\"><option value=\\"\\">Please select</option><option value=\\"small\\">Small</option><option value=\\"medium\\">Medium</option><option value=\\"large\\">Large</option></select></div></div><p id=\\"all\\">All is used here for testing purposes to ensure we have access to details about the device.</p></div></div></fieldset>"`;
```
Comment (tellthemachines) [inline packages/block-editor/src/components/responsive-block-control/test/__snapshots__/index.js.snap]: Unrelated to this changeset, but these snapshots are not very readable. I wonder why all the spacing has been removed 🤔

File: packages/block-library/src/gallery/gallery.js [hunk 5]
```diff
@@ -91,15 +100,11 @@ export const Gallery = ( props ) => {
...
-				tagName="figcaption"
-				className={ captionClassNames }
-				placeholder={ __( 'Write gallery caption…' ) }
-				value={ caption }
-				unstableOnFocus={ onFocusGalleryCaption }
-				onChange={ ( value ) => setAttributes( { caption: value } ) }
-				inlineToolbar
-			/>
+			{ ! isSelected && RichText.isEmpty( caption ) ? (
+				<VisuallyHidden>{ richTextElem }</VisuallyHidden>
```
Comment (tellthemachines) [inline packages/block-library/src/gallery/gallery.js]: This presents a problem, because `<figcaption>` has to be a direct descendant of `<figure>`. I suspect the best way forward here will be to just pass the `components-visually-hidden` class to RichText directly. We have to support direct use of the class anyway because of the php files 🤷‍♀

File: packages/components/src/color-picker/inputs.js [hunk 6]
```diff
@@ -230,8 +230,8 @@ export class Inputs extends Component {
 		} else if ( this.state.view === 'hsl' ) {
 			return (
 				<fieldset>
-					<VisuallyHidden as="legend">
-						{ __( 'Color value in HSL' ) }
+					<VisuallyHidden>
+						<legend>{ __( 'Color value in HSL' ) }</legend>
 					</VisuallyHidden>
```
Comment (tellthemachines) [inline packages/components/src/color-picker/inputs.js]: This change and the one above will break form semantics; best leave things as they were.

File: packages/components/src/external-link/index.js [hunk 7]
```diff
@@ -35,7 +35,7 @@ export function ExternalLink(
 			ref={ ref }
 		>
 			{ children }
-			<VisuallyHidden as="span">
+			<VisuallyHidden>
```
Comment (tellthemachines) [inline packages/components/src/external-link/index.js]: While `<div>` and `<span>` have no semantic meaning, they do have user agent styling differences, so best not change this.

File: packages/components/src/font-size-picker/index.js [hunk 8]
```diff
@@ -99,9 +100,9 @@ export default function FontSizePicker( {
 	const fontSizePickerNumberId = `components-font-size-picker__number#${ instanceId }`;
 	return (
 		<fieldset className="components-font-size-picker">
-			<legend className="screen-reader-text">
-				{ __( 'Font size' ) }
-			</legend>
+			<VisuallyHidden>
+				<legend>{ __( 'Font size' ) }</legend>
+			</VisuallyHidden>
```
Comment (tellthemachines) [inline packages/components/src/font-size-picker/index.js]: Same as above.

**Review by tellthemachines — CHANGES_REQUESTED** [review]
Thanks for taking this on! I left a bunch of comments below to indicate places where it's particularly important to preserve existing semantics, but the same recommendation applies to practically all of the instances where`<VisuallyHidden>` is being introduced: unless the existing element to be hidden is a `<div>`, we should always use the `as` prop to make `<VisuallyHidden>` itself render the semantically appropriate element, instead of wrapping the existing markup with it. 

The readme for VisuallyHidden doesn't really explain its correct usage, but [the Storybook demo](https://wordpress.github.io/gutenberg/?path=/story/components-visuallyhidden--default) may be helpful (you might have to use devtools to inspect the generated markup though, as some of it is hidden 😄 )

File: packages/block-library/src/gallery/gallery.js (hunk 5 above)
Comment (talldan) [reply packages/block-library/src/gallery/gallery.js]: It's a bit mad, but this should work:
```jsx
<VisuallyHidden as={ RichText } tagName="figcaption" // other RichText props ... />
```

But looking at the VisuallyHidden implementation, it doesn't look like it accepts additional class names. I may knock together a quick PR to fix that.

File: packages/block-library/src/search/index.php [hunk 9]
```diff
@@ -27,7 +27,7 @@ function render_block_core_search( $attributes ) {
 		);
 	} else {
 		$label_markup = sprintf(
-			'<label for="%s" class="wp-block-search__label screen-reader-text">%s</label>',
+			'<label for="%s" class="wp-block-search__label components-visually-hidden">%s</label>',
```
Comment (talldan) [inline packages/block-library/src/search/index.php]: There might be some issues using component class name in this way, since a component's class name isn't meant to be used outside of the component.

This html is also going to be output to a WordPress site's frontend, so would the components styles be loaded? Not sure, I'd need to test it. 😄 

It might be preferable for it to continue using the `screen-reader-text` global style or for the block to have its own visually hidden style.

It may also be an idea to split some of the changes that need more discussion into a separate PR so that they don't hold up the other changes.

File: packages/block-library/src/gallery/gallery.js (hunk 5 above)
Comment (talldan) [reply packages/block-library/src/gallery/gallery.js]: PR to better handle class names in VisuallyHidden:
https://github.com/WordPress/gutenberg/pull/20649

File: packages/components/src/external-link/index.js (hunk 7 above)
Comment (adamziel) [reply packages/components/src/external-link/index.js]: Does the user agent styling matters if `<VisuallyHidden>` is always visually hidden?

File: packages/block-editor/src/components/inserter/menu.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (adamziel) [reply packages/block-editor/src/components/inserter/menu.js]: Is extra `<div>` a bad thing though? I'd say a clear distinction between `<VisuallyHidden>` and a `<label>` is more readable.

File: packages/block-library/src/gallery/gallery.js (hunk 5 above)
Comment (gziolo) [reply packages/block-library/src/gallery/gallery.js]: Yes, let's fix it :) 

In general, you should be able to pass anything you want as `as` and all props should be passed down.

**Comment by gziolo** [comment]
https://github.com/WordPress/gutenberg/blob/81d8afce4b6a85a90941bfc08368e0d4d03d7203/packages/components/src/visually-hidden/index.js#L10-L15

`VisuallyHidden` it's a simple wrapper that defaults to `div`. All existing divs should be replaced with `VisuallyHidden` when they use the WP version of the class name.

In case of any other tag name or component is used, you should pass it as `as` prop.

In the case of PHP implementation, it should use the class name that WordPress core supports to ensure it works properly on the frontend.

File: packages/block-library/src/search/index.php (hunk 9 above)
Comment (gziolo) [reply packages/block-library/src/search/index.php]: > It might be preferable for it to continue using the screen-reader-text global style or for the block to have its own visually hidden style.

Yes, correct. PHP part should be left as is.

File: packages/components/src/external-link/index.js (hunk 7 above)
Comment (tellthemachines) [reply packages/components/src/external-link/index.js]: In practice it won't make a difference because the styles for hiding position the element absolutely, so it's removed from the flow, and it doesn't matter if its display type is block or inline. 
But there's no good reason for making this change either, so best keep the changeset to what is strictly necessary 🙂

File: packages/block-editor/src/components/inserter/menu.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (tellthemachines) [reply packages/block-editor/src/components/inserter/menu.js]: We might have to work on the docs, but it should be clear enough that `<VisuallyHidden>` will render as whatever element it's passed with the `as` prop 😅
As a general principle though, adding extra markup for code readability is not advisable because it has a direct impact on performance for the end user. It's best to keep markup to a minimum and use spacing and (non-rendering) comments where needed for clarification.

File: packages/block-library/src/gallery/gallery.js (hunk 5 above)
Comment (adamziel) [reply packages/block-library/src/gallery/gallery.js]: @talldan I think that makes sense! I added a helper component inline since it's pretty specific to this file, and I prepared a more general helper in https://github.com/WordPress/gutenberg/pull/20928

File: packages/components/src/custom-select-control/index.js [hunk 10]
```diff
@@ -98,19 +98,18 @@ export default function CustomSelectControl( {
...
+			) : (
+				/* eslint-disable-next-line jsx-a11y/label-has-associated-control, jsx-a11y/label-has-for */
+				<label
+					{ ...getLabelProps( {
+						className: 'components-custom-select-control__label',
+					} ) }
+				>
+					{ label }
+				</label>
+			) }
```
Comment (adamziel) [inline packages/components/src/custom-select-control/index.js]: I think https://github.com/WordPress/gutenberg/pull/20928 would be a better solution here

**Comment by adamziel** [comment]
@talldan @mkaz @gziolo @tellthemachines I addressed your feedback and this one is ready for re-review :-)

File: packages/edit-post/src/components/admin-notices/test/index.js [hunk 11]
```diff
@@ -19,7 +19,9 @@ describe( 'AdminNotices', () => {
 					<p>My <strong>notice</strong> text</p>
 					<p>My second line of text</p>
 					<button type="button" class="notice-dismiss">
-						<span class="screen-reader-text">Dismiss this notice.</span>
+						<span class="components-visually-hidden">
```
Comment (tellthemachines) [inline packages/edit-post/src/components/admin-notices/test/index.js]: If we're keeping the original classname as per [this thead](https://github.com/WordPress/gutenberg/pull/20607#discussion_r388153911) then this needn't change either.

**Review by tellthemachines — APPROVED** [review]
Couple of minor comments below; looks good overall 🙂

File: packages/block-library/src/gallery/gallery.js [hunk 12]
```diff
@@ -104,4 +102,12 @@ export const Gallery = ( props ) => {
 	);
 };
 
+function RichTextVisibilityHelper( { isHidden, className, ...richTextProps } ) {
+	return isHidden ? (
+		<VisuallyHidden as={ RichText } { ...richTextProps } />
+	) : (
+		<RichText className={ className } { ...richTextProps } />
```
[the remark this answers is not in the document]
Comment (adamziel) [reply packages/block-library/src/gallery/gallery.js]: I wanted to avoid passing className to `<VisuallyHidden />`, but when I looked into it more `.block-gallery-caption` shouldn't interfere with any styles we have there so I'll simplify this.

File: packages/block-library/src/gallery/gallery.js [hunk 13]
```diff
@@ -40,10 +41,6 @@ export const Gallery = ( props ) => {
 		images,
 	} = attributes;
 
-	const captionClassNames = classnames( 'blocks-gallery-caption', {
```
Comment (gziolo) [inline packages/block-library/src/gallery/gallery.js]: @tellthemachines, can you explain why we need still to render `RichText` when it's hidden visually? I see you introduced this behavior in #17101. In practice, it will never get focused because as soon as you move the focus to the Gallery block, then this condition will evaluate to `false` because `isSelected` will become `true` and the placeholder will show up when the caption is empty.

**Review by gziolo — APPROVED** [review]
Nice work @adamziel. I don't want to disturb the process for this PR, I think it's ready to go.

We should clarify the issue with the wrapper for `VisuallyHidden` separately. I'd like to learn first if it is really necessary or we can simplify the code instead.

File: packages/components/src/button/style.scss [hunk 14]
```diff
@@ -256,7 +256,7 @@
 
 	// Fixes a Safari+VoiceOver bug, where the screen reader text is announced not respecting the source order.
 	// See https://core.trac.wordpress.org/ticket/42006 and https://github.com/h5bp/html5-boilerplate/issues/1985
-	.screen-reader-text {
+	.components-visually-hidden {
```
Comment (gziolo) [inline packages/components/src/button/style.scss]: You probably need to include both. `style.scss` is shared between the front and the editor.

Comment (gziolo) [reply packages/components/src/button/style.scss]: Ignore it, I thought it's code for the Button block 🙃

File: packages/components/src/custom-select-control/index.js (hunk 10 above)
Comment (gziolo) [reply packages/components/src/custom-select-control/index.js]: Keep in mind that you still need to apply a different class name when it's visually hidden so there is going to be some extra logic involved.

File: packages/block-library/src/gallery/gallery.js (hunk 13 above)
Comment (tellthemachines) [reply packages/block-library/src/gallery/gallery.js]: Yup, I did that so it'll show up on the list of form controls for screen reader users. So if you're using a screen reader, you can navigate straight to the caption element through the forms list, even if the gallery block isn't focused. Of course, as soon as you navigate to the element it becomes focused and visible.

I notice that this is inconsistent with how we're treating the citation in the Quote block (which disappears from the DOM when empty not focused) and how we treat empty Paragraph blocks (which have visible placeholder text at all times). I'm not 100% sure which of these solutions is best accessibility and usability-wise. Perhaps this could be discussed further in the weekly accessibility chat? It would be best to have a consistent behaviour for all these cases.

Comment (gziolo) [reply packages/block-library/src/gallery/gallery.js]: It's definitely something worth discussing with the bigger group 👍 

It would be nice to be more consistent if other blocks always show placeholders then maybe we should follow that as well. However, I'm sure it's something that always has trade-offs. In the case of Paragraph without the placeholder, you could miss the fact that the block is even there when using mouse navigation :) On the other hand, if you would display caption placeholders for all images in the Gallery block then it would be very loaded. I think it also translates to the screen read case, too many controls exposed might make it harder to navigate to the currently selected block.

Comment (tellthemachines) [reply packages/block-library/src/gallery/gallery.js]: Update: a similar issue is being discussed in #15308 and seems to be going in the direction of making placeholders visible by default.
