### PR TITLE
Fix dynamic references on the site editor

### LINKED ISSUE #42890: Dynamic references in `theme.json` are not resolved in the site editor
### Description

We've introduced a new mechanism to refer to a different style dynamically at https://github.com/WordPress/gutenberg/pull/41696 which allows us to do things such as:

```json
"styles": {
    "color": {
        "background": { "ref": "styles.color.text" },
        "text": "yellow"
    }
}
```

In the example, the result would be that the text and background colors are the same (yellow).

Captura de ecrã de 2022-08-02 12-29-40

While this works in the front-end it doesn't in the site editor:

- the styles box does not render the background
- the color tools do not render the background
- the site editor breaks if the user tries to edit the background color 

| Styles | Color tools | Site editor
| --- | --- | --- |
| Captura de ecrã de 2022-08-02 12-28-19 | Captura de ecrã de 2022-08-02 12-28-28 | Captura de ecrã de 2022-08-02 12-28-36 |

### Step-by-step reproduction instructions

- Use TwentyTwentyTwo theme and update the styles.color values to be: 

```
"background": { "ref": "styles.color.text" },
"text": "yellow"
```

- Go to the front-end and verify that it works as expected.
- Go to the site editor and open the Global Styles Toolbar. Click on Colors and then in the Backgound element. It'll throw an error.

### Environment info

I can reproduce this is `trunk`.

### PR DESCRIPTION
**Pull request by MaggieCabrera**
## What?

Fixes https://github.com/WordPress/gutenberg/issues/42890

## Why?

https://github.com/WordPress/gutenberg/pull/41696/files implemented references on the frontend but they weren't being resolved in the site editor. In particular, they were breaking Global Styles.

## How?

I created a function that resolved the references into the actual values being referenced. I'm not sure if this is the best place or best method to do this, but it solves the editor crashing because of the bug and keeps the editor consistent with the frontend. A next step would be to discuss how we want to surface this link to the users like @oandregal [mentioned](https://github.com/WordPress/gutenberg/issues/42890#issuecomment-1202318335). 

## Testing Instructions

With this PR checked, follow the instructions from https://github.com/WordPress/gutenberg/issues/42890 and see that the site editor doesn't crash when visiting the links section. 

## Screenshots or screencast 

Rainfall uses refs for links too, you can test it there and see it doesn't crash:

Screenshot 2022-08-04 at 13 13 50

### CODE REVIEW

File: packages/edit-site/src/components/global-styles/use-global-styles-output.js [hunk 1]
```diff
@@ -270,7 +292,11 @@ export function getStylesDeclarations(
 		const cssProperty = rule.key.startsWith( '--' )
 			? rule.key
 			: kebabCase( rule.key );
-		output.push( `${ cssProperty }: ${ compileStyleValue( rule.value ) }` );
+		let ruleValue = rule.value;
+		if ( typeof ruleValue !== 'string' ) {
```
Comment (getdave) [inline packages/edit-site/src/components/global-styles/use-global-styles-output.js]:
```suggestion
		if ( typeof ruleValue !== 'string' && ruleValue?.ref ) {
```

We could avoid assuming it's a ref here as well.

File: packages/edit-site/src/components/global-styles/use-global-styles-output.js [hunk 2]
```diff
@@ -181,6 +181,26 @@ function flattenTree( input = {}, prefix, token ) {
 	return result;
 }
 
+/**
+ * Resolves ref into the value it is pointing to.
+ *
+ * @param {Object} refObj      The reference we are pointing to.
+ *
+ * @param {string} blockStyles Block styles.
```
Comment (getdave) [inline packages/edit-site/src/components/global-styles/use-global-styles-output.js]:
```suggestion
 * @param {string} blockStyles The tree of block styles.
```

The argument passed in is `tree` so maybe we should retain that knowledge of shape here?

File: packages/edit-site/src/components/global-styles/use-global-styles-output.js [hunk 3]
```diff
@@ -181,6 +181,26 @@ function flattenTree( input = {}, prefix, token ) {
 	return result;
 }
 
+/**
+ * Resolves ref into the value it is pointing to.
+ *
+ * @param {Object} refObj      The reference we are pointing to.
```
Comment (getdave) [inline packages/edit-site/src/components/global-styles/use-global-styles-output.js]:
```suggestion
 * @param {Object} refObj      The reference in the block styles tree.
```

Nit: I have made a rule for myself to avoid using "we" in comments. It generally makes them clearer IMHO.

File: packages/edit-site/src/components/global-styles/use-global-styles-output.js [hunk 4]
```diff
@@ -181,6 +181,26 @@ function flattenTree( input = {}, prefix, token ) {
...
+ *
+ * @param {string} blockStyles Block styles.
+ *
+ * @return {string} The resolved referenced value.
+ */
+function resolveRefValue( refObj, blockStyles ) {
+	if ( ! refObj.ref ) {
+		return refObj;
+	}
```
Comment (getdave) [inline packages/edit-site/src/components/global-styles/use-global-styles-output.js]: Is there a benefit to this function knowing about the object that contains the `ref`? Would it be making the function simpler to just pass the ref only?

File: packages/edit-site/src/components/global-styles/use-global-styles-output.js [hunk 5]
```diff
@@ -270,7 +292,11 @@ export function getStylesDeclarations(
 		const cssProperty = rule.key.startsWith( '--' )
 			? rule.key
 			: kebabCase( rule.key );
-		output.push( `${ cssProperty }: ${ compileStyleValue( rule.value ) }` );
+		let ruleValue = rule.value;
+		if ( typeof ruleValue !== 'string' ) {
+			ruleValue = resolveRefValue( rule.value, tree );
```
Comment (getdave) [inline packages/edit-site/src/components/global-styles/use-global-styles-output.js]: This may resolve to an `object` (no ref found on object) or a string value (ref was found and resolved). Is there a use case where we have an object with something other than a ref?

Relates to other comments about simplify the utility function here.

**Comment by getdave** [comment]
Whoops! Forgot to leave a comment on the review.

This is looking really great 👏 

Some nits and suggestions. Main one being tests.

File: packages/edit-site/src/components/global-styles/use-global-styles-output.js (hunk 5 above)
Comment (MaggieCabrera) [reply packages/edit-site/src/components/global-styles/use-global-styles-output.js]: It can be an object in cases like padding where you have `{ "top": "0px, ... }` but I think those are covered right now [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/global-styles/use-global-styles-output.js#L223), I don't know if there might be cases right now that require that check, but maybe in the future?

File: packages/edit-site/src/components/global-styles/use-global-styles-output.js (hunk 4 above)
Comment (MaggieCabrera) [reply packages/edit-site/src/components/global-styles/use-global-styles-output.js]: mmh, I see what you mean, we might not need a function for this at all, it will end up being two lines, I'm not sure if we need the abstraction or if it will need to be reused at some point in time

**Comment by MaggieCabrera** [comment]
Looks like the editor is still crashing, I was looking at the wrong place 🤦‍♀️ I'll keep working on this

**Comment by scruffian** [comment]
> Looks like the editor is still crashing, I was looking at the wrong place 🤦‍♀️ I'll keep working on this

The crash is because of the value being parsed in the UI. I think we need two fixes, and this is one of them...

**Comment by MaggieCabrera** [comment]
> > Looks like the editor is still crashing, I was looking at the wrong place 🤦‍♀️ I'll keep working on this
> 
> The crash is because of the value being parsed in the UI. I think we need two fixes, and this is one of them...

Exactly, I'm not sure where the fix should go for the GS!

File: packages/edit-site/src/components/global-styles/use-global-styles-output.js [hunk 6]
```diff
@@ -270,7 +273,12 @@ export function getStylesDeclarations(
 		const cssProperty = rule.key.startsWith( '--' )
 			? rule.key
 			: kebabCase( rule.key );
-		output.push( `${ cssProperty }: ${ compileStyleValue( rule.value ) }` );
+		let ruleValue = rule.value;
+		if ( typeof ruleValue !== 'string' && ruleValue?.ref ) {
+			const refPath = ruleValue.ref.split( '.' );
+			ruleValue = get( tree, refPath );
```
Comment (scruffian) [inline packages/edit-site/src/components/global-styles/use-global-styles-output.js:279]: I _think_ this will mutate the `rule` variable, which is OK but probably better if we can avoid it. I know this was already an issue before your PR. Maybe an extra function is a good idea, but making it a bit bigger to encapsulate the logic for both the property and the value? That might be better in a follow up PR anyway...

**Comment by scruffian** [comment]
I can confirm this fixes part of the issue - links are now correctly styled in the Site Editor.

**Comment by MaggieCabrera** [comment]
This now fixes the editor crashing on Global Styles. I tested changing the colors, and that works too. @ndiego it looks like this fixes https://github.com/WordPress/gutenberg/issues/43033 too, can you confirm?

Thanks @scruffian for your help figuring this one out

**Comment by ndiego** [comment]
Thanks @MaggieCabrera, just tested this PR against https://github.com/WordPress/gutenberg/issues/43033 and color changes are working as expected in Global Styles. 🙌

File: packages/edit-site/src/components/global-styles/use-global-styles-output.js (hunk 6 above)
Comment (draganescu) [reply packages/edit-site/src/components/global-styles/use-global-styles-output.js:279]: What would mutate it? This:
```
const rule = { value: 1 };
let ruleValue = rule.value;
console.log(ruleValue);
ruleValue = 2;
console.log( rule )
console.log( ruleValue )
```
results in:
```
1
Object { value: 1 }
2
```

**Comment by draganescu** [comment]
I only wonder what about the other uses of `getValueFromVariable` shouldn't they also be turned into `getValueFromVariableOrRef`? Are there places where ref is not allowed?

**Comment by MaggieCabrera** [comment]
> I only wonder what about the other uses of `getValueFromVariable` shouldn't they also be turned into `getValueFromVariableOrRef`? Are there places where ref is not allowed?

`getValueFromVariable` is only ever used inside utils.js and `getValueFromPresetVariable` and `getValueFromCustomVariable`, which in turn are only ever called by `getValueFromVariable` recursively, so I think all existing cases are covered.

**Comment by MaggieCabrera** [comment]
>  Are there places where ref is not allowed?

as for that, I don't think there are at the moment, no

**Comment by MaggieCabrera** [comment]
@scruffian @draganescu I refactored this a bit to avoid the confusing function. I'm not sure that we need a specific function just to get the ref right now, but I don't have a strong opinion on the matter.

**Comment by draganescu** [comment]
I have not tested but it looks better as a patch that solves the missing case in the existing flow instead of introducing duplication. My main question is if there is any performance impact from using a larger object (the whole tree) every time. How can that be tested?

**Comment by MaggieCabrera** [comment]
> I have not tested but it looks better as a patch that solves the missing case in the existing flow instead of introducing duplication. My main question is if there is any performance impact from using a larger object (the whole tree) every time. How can that be tested?

the larger object is never used when it's not needed in the end. It's passed as an argument but only used by the function getting the rev value, the rest of the functions use the settings part of it only.

**Comment by oandregal** [comment]
Hey, tested this a bit and found a case we need to prevent from happening: recursive references.

It can be tested by adding the following to the `styles` section of the TwentyTwentyTwo theme:

```
"color": {
    "background": { "ref": "styles.color.text" },
    "text": {"ref": "styles.color.background" }
},
```

**Comment by MaggieCabrera** [comment]
> "color": {
>     "background": { "ref": "styles.color.text" },
>     "text": {"ref": "styles.color.background" }
> }

This is already covered by [this check](https://github.com/WordPress/gutenberg/blob/300a857cdda05c1da6399706f51ba8426f9f7721/lib/compat/wordpress-6.1/class-wp-theme-json-6-1.php#L939). Should we do something more than that?

**Comment by oandregal** [comment]
The editor still crashes with that check:

Captura de ecrã de 2022-08-10 15-23-47

**Comment by scruffian** [comment]
> The editor still crashes with that check

I think we should merge this as it fixes the main problem and then follow up with another check for this case.

**Review by scruffian — APPROVED** [review]

**Comment by MaggieCabrera** [comment]
> Hey, tested this a bit and found a case we need to prevent from happening: recursive references.
> 
> It can be tested by adding the following to the `styles` section of the TwentyTwentyTwo theme:
> 
> ```
> "color": {
>     "background": { "ref": "styles.color.text" },
>     "text": {"ref": "styles.color.background" }
> },
> ```

I opened https://github.com/WordPress/gutenberg/issues/43154

**Comment by scruffian** [comment]
> I opened https://github.com/WordPress/gutenberg/issues/43154

Ok great, thank you.
