### PR TITLE
DataViews: externalize theme stylesheet

### LINKED ISSUE #74594: @wordpress/dataviews: Externalize design tokens stylesheet dependency
## What problem does this address?

Related discussion: https://github.com/WordPress/gutenberg/pull/74174#discussion_r2644046439

The `@wordpress/dataviews` package currently embeds the `@wordpress/theme/design-tokens.css` stylesheet contents. This can lead to duplication of the stylesheet the design tokens are already provided elsewhere in their application.

## What is your proposed solution?

Remove the design tokens stylesheet from `@wordpress/dataviews` own stylesheet and make it the consumer's responsibility to ensure the stylesheet is included in their application.

Specifically:

- Remove the [embedded stylesheets from DataViews](https://github.com/WordPress/gutenberg/blob/a8182e984b5a241041725a42ce34a3e1dd84d8d3/packages/dataviews/src/style.scss#L1)
- Document the requirement in the package README.md
- Communicate as a breaking change in CHANGELOG.md
- Ensure that existing usage includes the stylesheet to avoid regressions on existing usage within WordPress

### PR DESCRIPTION
**Pull request by oandregal**
Fixes https://github.com/WordPress/gutenberg/issues/74594

## What?

Remove the `@wordpress/theme/design-tokens.css` stylesheet from dataviews.

## Why?

This can lead to duplication of the stylesheet the design tokens are already provided elsewhere in their application.

## How?

- Remove the stylesheet.
- Document the stylesheet dependencies for DataViews.

## Testing Instructions

- Load the site editor and smoke test that it works as before.
- Load the storybook and smoke test that it works as before.

### CODE REVIEW

File: storybook/package-styles/config.js [hunk 1]
```diff
@@ -17,6 +17,7 @@ import fieldsLtr from '../package-styles/fields-ltr.lazy.scss?inline';
 import fieldsRtl from '../package-styles/fields-rtl.lazy.scss?inline';
 import mediaFieldsLtr from '../package-styles/media-fields-ltr.lazy.scss?inline';
 import mediaFieldsRtl from '../package-styles/media-fields-rtl.lazy.scss?inline';
+import theme from '../package-styles/theme.lazy.scss?inline';
```
Comment (mirka) [inline storybook/package-styles/config.js:20]: I would like to [consolidate](https://github.com/WordPress/gutenberg/pull/74899/changes#diff-b42081f75f881d642ecfeac0c12b368f7d076a5da71aa43ecfde8cd2a4ff8389R20) this to a single `designTokens` import.

**Review by mirka — APPROVED** [review]
Looks good and makes sense 👍

File: storybook/package-styles/config.js (hunk 1 above)
Comment (oandregal) [reply storybook/package-styles/config.js:20]: 👍 `designTokens` looks good to me as name, though that link points to the UI stylesheet that is different? I merged in the interest of velocity, but happy to iterate on this or address any other issue if you can't on #74899

File: packages/dataviews/README.md [hunk 2]
```diff
@@ -14,6 +14,19 @@ Install the module
 npm install @wordpress/dataviews --save
 ```
 
+## Stylesheet Dependencies
+
+DataViews depends on stylesheets from `@wordpress/components` and `@wordpress/theme`. In a WordPress admin page context, these are loaded automatically. For applications outside WordPress, you will need to include these stylesheets:
```
Comment (mirka) [inline packages/dataviews/README.md:19]: Sorry I overlooked this point — as far as I know these are not "loaded automatically" in WordPress, they require an `wp_enqueue_style` like we document in the `@wordpress/components` readme:

https://github.com/WordPress/gutenberg/blob/b0548637416101d1bba98fb2ca9dfb993ac5233b/packages/components/README.md?plain=1#L28

This is also wrong in the `@wordpress/ui` readme so I'll fix.

Another point is that I don't think we load the `@wordpress/theme` design tokens stylesheet in Gutenberg yet, so if DataViews actually uses anything that requires a design token, that might be broken right now 😅

(cc @WordPress/gutenberg-components in case I got something wrong here)

File: storybook/package-styles/config.js (hunk 1 above)
Comment (mirka) [reply storybook/package-styles/config.js:20]: No worries, consolidated in #74899!

File: packages/dataviews/README.md (hunk 2 above)
Comment (aduth) [reply packages/dataviews/README.md:19]: I thought this would be handled through the dependency chain from DataViews style loading to the `wp-theme` stylesheet as a dependency, i.e. what was corrected in #74743.

Comment (mirka) [reply packages/dataviews/README.md:19]: Even if the DataViews stylesheet did load the theme stylesheet (which it doesn't anymore in this PR), shouldn't a consumer need to `wp_enqueue_style` the DataViews stylesheet at least? To ensure correct load order, at the very least? That's what's documented in the `@wordpress/components` readme, so if that's wrong I would want to fix it.

Comment (aduth) [reply packages/dataviews/README.md:19]: Hm, the more I dig into this, the more I feel we may in-fact be missing something.

I think there's _some_ partial truth to this. There are examples like `@wordpress/boot` where technically WordPress is handling the "loaded automatically" [by loading theme styles](https://github.com/WordPress/gutenberg/blob/db3b37a28f9e548043c345620cae425be3667249/packages/boot/src/style.scss#L1). But obviously this boot package isn't yet used everywhere.

There may be some incidental behavior where the theme styles are brought in via dependency chains, e.g. `@wordpress/dataviews` -> `@wordpress/ui` -> `@wordpress/theme` which is translated into style dependencies through the build's [`inferStyleDependencies`](https://github.com/WordPress/gutenberg/blob/db3b37a28f9e548043c345620cae425be3667249/packages/wp-build/lib/build.mjs#L770-L831). But it [builds those dependencies out of imports in the JavaScript code](https://github.com/WordPress/gutenberg/blob/trunk/packages/wp-build/lib/wordpress-externals-plugin.mjs#L198-L278), which is fragile and not a strong signal of what _style dependencies_ should be loaded. 

How it should work? I'm not super clear, but maybe one of: 

- Use `@wordpress/boot` in more places as a true boot-point for "WordPress" and all its core styling
- Manually revise dependencies [like what we do in `lib/client-assets.php`](https://github.com/WordPress/gutenberg/blob/db3b37a28f9e548043c345620cae425be3667249/lib/client-assets.php#L137-L166) to include `wp-theme` in more entrypoint packages
- Sprinkle `@use "@wordpress/theme/src/prebuilt/css/design-tokens.css"` throughout some more entrypoint stylesheets
- Invent a way to more explicitly define these dependencies, like a `wpStyleDependencies` field in `package.json` that's respected by the build tool

Some of those options may still require documentation that consumers would be responsible for ensuring the styles are enqueued.

cc @youknowriad @jsnajdr

Comment (youknowriad) [reply packages/dataviews/README.md:19]: The way I see it is:

 -  is any package that renders `<ThemeProvider>` should be also doing `@use "@wordpress/theme/src/prebuilt/css/design-tokens.css"`
 - The "boot" package is one of many entry points in WordPress
 - Most edit-* packages are also entry points and if we want to start using UI components in these, they need to render `ThemeProvider` and include the tokens CSS.
 - Since dataviews is already using UI components and dataviews is used in most of these edit-* packages, we need to follow-up with the addition of `ThemeProvider` and tokens to all of these packages.

Where I think we could improve things:

 - Using `ThemeProvider` should ideally automatically inject the design tokens (once).

Comment (aduth) [reply packages/dataviews/README.md:19]: > * Using `ThemeProvider` should ideally automatically inject the design tokens (once).

It's an option, though as discussed previously in https://github.com/WordPress/gutenberg/pull/74174#issuecomment-3697170495 it feels like it just shifts the dependency from the a stylesheet to a React component. So a project external to WordPress that wants to use DataViews but doesn't care about theming still has to introduce a ThemeProvider wrapper somewhere.

> * Most edit-* packages are also entry points and if we want to start using UI components in these, they need to render `ThemeProvider` and include the tokens CSS.

Yeah, I think this is a logical next step. We may not strictly need the `ThemeProvider` component, just the styles should be enough to start. I also want to be conscious whether this ships with WordPress 7.0 and creates expectations around the theme variables; ideally we'd leave it out, but I also don't want anything to be broken if it was by these changes 😓 

If we did add the styles to the entrypoints, then I think it's accurate to say that this would be handled automatically inside WordPress as mentioned in the changelog note.

Comment (youknowriad) [reply packages/dataviews/README.md:19]: > It's an option, though as discussed previously in https://github.com/WordPress/gutenberg/pull/74174#issuecomment-3697170495 it feels like it just shifts the dependency from the a stylesheet to a React component. So a project external to WordPress that wants to use DataViews but doesn't care about theming still has to introduce a ThemeProvider wrapper somewhere.

Yes, but the main API for these components is React, so it's just simplifies things and ThemeProvider is almost already mandatory. That said, this is not the main thing in this discussion. We can live with or without it.

> Yeah, I think this is a logical next step. We may not strictly need the ThemeProvider component, just the styles should be enough to start.

We do need the ThemeProvider (or more precisely the UserThemeProvider) in order to adapt to the currently selected user profile.

If you think this is too soon for 7.0, the only other option I see is to revert the usage of the UI package in dataviews.

Comment (aduth) [reply packages/dataviews/README.md:19]: > We do need the ThemeProvider (or more precisely the UserThemeProvider) in order to adapt to the currently selected user profile.

I'm not sure if we're using anything where we need the user preference at the moment? Although yes, we should probably just go ahead and get this established.

> If you think this is too soon for 7.0, the only other option I see is to revert the usage of the UI package in dataviews.

I was going to suggest we could revert the changes made in this pull request, but (a) I'm still not entirely sure it's broken as-is, and (b) regardless, the styles would be defining `:root` theme CSS properties, so those are going to be present for everyone.

I think we could probably be okay with what's shipping, especially after the latest rounds of token refinement. I'd like if we had some flexibility for revisions without too much fear of backwards-compatibility even after releasing, though I dunno how others may feel about that.

Comment (ciampo) [reply packages/dataviews/README.md:19]: As of now, `ThemeProvider` is only needed if in need of customizing the default theme — otherwise, the CSS file includes all the required variables with the default theme values. 

I see value in not requiring `ThemeProvider`, and also in the fact that using CSS variables should prevent FUOC while the `ThemeProvider` hasn't calculcated the overridden CSS variables.

Comment (youknowriad) [reply packages/dataviews/README.md:19]: Important thing is that edit-site and edit-post... still update properly the colors when the user profile is modified. So if tomorrow someone starts using any component that uses colors from `@wordpress/ui` in `@wordpress/dataviews` we'd be introducing a bug without knowing.
