### PR TITLE
Fix upload button on overridden empty image block in patterns

### LINKED ISSUE #58708: Pattern Overrides: Image `id` attribute can mismatch the image `url` attribute, which results in buggy behavior
### Description

When using images for pattern overrides, it will be a common use case for the pattern creator to set one image in the pattern e.g take the following pseudocode (image block markup is more complex than this, the code is just to illustrate the point):
```html
<!-- wp:image {"id":215,"url":"https://my.wordpress.site/wp-content/uploads/initial-image.jpg"} /-->
```

In the above markup, both the id and url attributes are correctly set for an image in the media library.

Now in the instance of the same pattern, a user may wish to set a url for a different image, the resulting pseudocode would be:
```html
<!-- wp:image {"id":215,"url":"https://my.wordpress.site/wp-content/uploads/override-image.jpg"} /-->
```

Not that the url has changed, but the id hasn't. There's now a mismatch, the id represents one image in the media library, while the url represents another.

This happens because `url` has a block binding, but `id` doesn't.

This mismatch could cause unpredictable bugs.

### Step-by-step reproduction instructions

There's one bug I've spotted so far, it happens when an image block is added to a pattern source but left empty. When a user overrides that image, the image has no `id`, so the 'upload' option is visible on the toolbar.

1. Create a new post and insert an image block and leave it empty (in the placeholder state)
2. From the block settings menu for the image block, create a new pattern, making it synced.
3. Choose the 'Edit original' button from the toolbar to edit the pattern
4. Select the image block, and from the advanced inspector options, check the 'Allow instance overrides' option
5. Save changes
6. Click the back button to go back to the post you were initially editing
7. Add an image to image block in the pattern (use a media library image, so upload a new one or choose an existing one).
8. Save the post.
9. Reload, select the image in the pattern

Expected: because the image added in step 7 is from the media library, there's no upload button on the block toolbar.
Actual: there is an 'upload' button on the block toolbar

### Screenshots, screen recording, code snippet

Screenshot 2024-02-06 at 11 07 00 am

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by kevin940726**
## What?

Fix https://github.com/WordPress/gutenberg/issues/58708.

Fix the confusing upload button on the block toolbar for overridden empty image in patterns.

## Why?

The upload button is confusing and it creates bad UX.

## How?

Add `id` as a binding attribute for the image block as well.

## Testing Instructions

Follow the testing instructions in https://github.com/WordPress/gutenberg/issues/58708.
Also added an e2e test.

## Screenshots or screencast 
N/A

### CODE REVIEW

**Review by aaronrobertshaw — APPROVED** [review]
This tests well for me @kevin940726 👌 

In early explorations (https://github.com/WordPress/gutenberg/pull/53887) I found the `id` needed to be tracked as well to make sure when replacing an image via the media library, the correct original selection was shown.

I can replicate that issue of the missing image selection in the media library on trunk and confirm that this PR fixes it as well.

---

✅ Upload button is no longer incorrectly shown
✅ Crop button now displays correctly
✅ Image selection within media library is now correct

| Before | After |
|---|---|
| Screenshot 2024-02-20 at 12 11 04 pm | Screenshot 2024-02-20 at 12 10 51 pm |

**Comment by talldan** [comment]
@SantosGuillamot @gziolo @michalczaplinski @artemiomorales Just a heads up that this adds the image block's `id` as another binding attribute.

**Comment by talldan** [comment]
I notice this caused a PHP error due to the `id` attribute not having a `source` property:
Screenshot 2024-02-20 at 10 53 40 am

So I think along with this change the processing code would also need to skip attributes without a source.

**Comment by getdave** [comment]
I just cherry-picked this PR to the cherry-pick-beta-2 branch to get it included in the next release: 4fcb480f5c

File: packages/patterns/src/constants.js [hunk 1]
```diff
@@ -31,6 +31,7 @@ export const PARTIAL_SYNCING_SUPPORTED_BLOCKS = {
 		rel: __( 'Link Relationship' ),
 	},
 	'core/image': {
+		id: __( 'Image ID' ),
```
Comment (gziolo) [inline packages/patterns/src/constants.js:34]: There is a note in the code:

```js
// TODO: This should not be hardcoded. Maybe there should be a config and/or an UI.
```

@talldan and @SantosGuillamot, I contemplated the other day whether we should add labels to block attributes schema and annotate them as translatable in `block.json`. That could also be considered as one of the conditions to opt into block bindings in the future.

Comment (gziolo) [reply packages/patterns/src/constants.js:34]: By the way, I think you should use `_x()` with the context so it's easier to translate these labels.

https://github.com/WordPress/gutenberg/blob/a04a8e94e8b93ba60441c6534e21f4c3c26ff1bc/packages/blocks/src/api/registration.js#L271-L274

The context could be similar to:

https://github.com/WordPress/gutenberg/blob/a04a8e94e8b93ba60441c6534e21f4c3c26ff1bc/packages/blocks/src/api/i18n-block.json#L7

`block attribute label` could work. That simpler part might make sense to update still before WP 6.5 beta 3.

Comment (kevin940726) [reply packages/patterns/src/constants.js:34]: Yeah, I always have some doubts about including the translation strings here. Currently, they are not used in any way but are still kept. Should we just remove them for this release to not cause confusion for translators?

Comment (gziolo) [reply packages/patterns/src/constants.js:34]: Let's remove them to prevent unnecessary work for translators. 16 most popular locales need to have 100% coverage before the major release starts 😅
