### PR TITLE
Adjust clashing shortcuts used for character input

### LINKED ISSUE #13118: CZ quotation marks in Gutenberg don’t work
**Describe the bug**
Gutenberg doesn’t react to Czech quotation marks: „ and “

**To Reproduce**
1. Press cmd+n (for „) or cmd+h (for “)
2. See that nothing happens
3. Be sad and start your GitHub account to report this bug

**Desktop (please complete the following information):**
 - OS: MAC OS Mojave
 - Browser: Chrome
 - Version: 70.0.3538.110

**Additional context**
- Gutenberg version: 4.7.1

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #13118. Replaces the `shift+alt` combination with the "standard" WordPress `access` combination.

Also adds a check to `KeyboardShortcuts` to prevent this mistake from happening in the future.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by draganescu** [comment]
This is great! It globally replaces Shift+Alt with Ctrl+Alt (on OSX). This is also the basic behaviour (Ctrl+Alt) that the HTML accesskey has:

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey

I tested and it worked as described, but I am not aware if this has other implications.

**Comment by draganescu** [comment]
@afercia @mcsf would you think is is actually a better solution than solving one individual shortcut? It also addresses @talldan 's suggestion to update all shortcuts. 'accesskey' seems a viable way to handle generic shortcuts that use one letter.

**Comment by afercia** [comment]
It has already been pointed out that the "standard" WordPress `access` combination is a problem, as it conflicts with native shortcuts used on macOS for VoiceOver. See for example:

**Keyboard shortcuts that use the `access` modifier don't work with VoiceOver**
https://github.com/WordPress/gutenberg/issues/11154

**Help shortcut conflicts with VoiceOver Help shortcut (Mac)**
https://core.trac.wordpress.org/ticket/39271

So this is a known issue, and I'm not sure why we'd want to keep using `access`. 

In #11154 I've also linked to a useful resource by the W3C: in the new WAI-ARIA Authoring Practices 1.1 there's a section dedicated to keyboard shortcuts. It's more about what not to do, see: https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_shortcuts_assigning

There's a list of combinations to avoid and, among others, it's clearly stated to avoid:
> macOS only: Control+Option + any combination of other keys.

Also:

> It globally replaces Shift+Alt with Ctrl+Alt (on OSX)

This actually means all these shortcuts are not available to VoiceOver users so I'm afraid I can't support this change as it creates an accessibility barrier.

**Comment by ellatrix** [comment]
@afercia I'm very well aware that `access` has its own problems, and that we should move away from that combination as well. For now, this is the quickest solution. The `shift+alt` combination needs to go away as soon as possible.

Which VoiceOver commands will clash with these two?

Other options:

* ctrl+option+↑ and ctrl+option+↓
* ctrl+option+tab and ctrl+option+shift+tab

**Comment by afercia** [comment]
@ellatrix thanks. Can you please clarify `globally replaces Shift+Alt with Ctrl+Alt`? At a first reading, I got it was going to use `access` everywhere. Looking at the code, seems to me it's changing only the navigate region shortcuts.

Anyways, here's a list of the VoiceOver commands, where `VO` stands for `Control+Alt`:
https://www.apple.com/voiceover/info/guide/_1131.html

> Other options:
> 
> - ctrl+option+↑ and ctrl+option+↓
> - ctrl+option+tab and ctrl+option+shift+tab

VO + Down and Up arrows are widely used for navigation and to change settings;
VO + Tab is used to "Tell VoiceOver to ignore the next key combination"

**Comment by talldan** [comment]
@ellatrix This looks good. There's one extra place to update the documented shortcut:
https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/faq.md#editor-shortcuts

**Comment by talldan** [comment]
>  Looking at the code, seems to me it's changing only the navigate region shortcuts.

@afercia - I can help answer that. My understanding is that the two navigate regions shortcuts are the only ones bound in Gutenberg that are using `shift+alt` on mac os, which is where the problem is.

**Review by draganescu — APPROVED** [review]
Hi @ellatrix there is this doc file that should be updated once the shortcuts are changed,
https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/faq.md#editor-shortcuts

Do you have the time to update it or may I edit your PR?

Otherwise with the follow-up confirmation from @talldan I think we're good to go!

**Comment by talldan** [comment]
@draganescu yep, I'm happy. It might be worth just pushing the changes to that file in a commit and then merging. I'm sure @ellatrix won't mind.

File: packages/components/src/keyboard-shortcuts/index.js [hunk 1]
```diff
@@ -21,7 +35,12 @@ class KeyboardShortcuts extends Component {
 		const { keyTarget = document } = this;
 
 		this.mousetrap = new Mousetrap( keyTarget );
+
 		forEach( this.props.shortcuts, ( callback, key ) => {
+			if ( process.env.NODE_ENV === 'development' ) {
+				throwForInvalidCombination( key );
```
Comment (aduth) [inline packages/components/src/keyboard-shortcuts/index.js]: FWIW, if the logic of the function was inlined here, this could benefit from dead code removal for production environments.

https://gist.github.com/aduth/f6e7ae516310f60ebda6c93998713254

**Comment by draganescu** [comment]
rebased, updated the docs and inlined the script based on @aduth suggestion

File: packages/components/src/keyboard-shortcuts/index.js (hunk 1 above)
Comment (draganescu) [reply packages/components/src/keyboard-shortcuts/index.js]: done it.

**Comment by ellatrix** [comment]
Thanks for the updates @draganescu!

File: packages/components/src/keyboard-shortcuts/index.js [hunk 2]
```diff
@@ -21,7 +21,22 @@ class KeyboardShortcuts extends Component {
 		const { keyTarget = document } = this;
 
 		this.mousetrap = new Mousetrap( keyTarget );
+
 		forEach( this.props.shortcuts, ( callback, key ) => {
+			if ( process.env.NODE_ENV === 'development' ) {
+				const keys = key.split( '+' );
+				const modifiers = new Set( keys.filter( ( value ) => value.length > 1 ) );
```
Comment (aduth) [inline packages/components/src/keyboard-shortcuts/index.js]: Won't this capture much more than just modifiers, like `escape`, or `space`, or `tab` ? While ultimately it has no impact one way or the other since the subsequent lines only care to check for `alt` or `shift` specifically, it begs the question at that point why to filter at all (vs. `hasAlt = keys.includes( 'alt' )`).

File: packages/components/src/keyboard-shortcuts/index.js [hunk 3]
```diff
@@ -21,7 +21,22 @@ class KeyboardShortcuts extends Component {
...
+				const hasAlt = modifiers.has( 'alt' );
+				const hasShift = modifiers.has( 'shift' );
+
+				if (
+					( modifiers.size === 1 && hasAlt ) ||
+					( modifiers.size === 2 && hasAlt && hasShift )
+				) {
+					throw new Error( `Cannot bind ${ key }. Alt and Shift+Alt modifiers are reserved for character input.` );
```
Comment (aduth) [inline packages/components/src/keyboard-shortcuts/index.js]: I guess it's _expected_ this should crash the application (to make the problem exceedingly obvious)? As there's been some prior conversation at #13405 and alternative approaches at #14151 to address these sorts of "wrong usage" violations, it seems we might consider having a unified approach to when and how they should be introduced. Personally I'd favor ESLint rules since they can be captured at build-time than at runtime, but I could grant that (a) there's more effort involved in creating the rules ([though not always](https://github.com/WordPress/gutenberg/blob/774713c0467779a9651983ec96609a6637811132/.eslintrc.js#L27-L100)) and (b) this assumes that the developer has opted into using ESLint and the custom rules, which is not a given.
