### PR TITLE
Fixes #26010 - Template Part Not Found message on Windows server

### LINKED ISSUE #26010: Template Part Not Found message from gutenberg_render_block_core_template_part() on Windows server
**Describe the bug**
I'm following the instructions to develop a theme for Full Site Editing at
https://developer.wordpress.org/block-editor/tutorials/block-based-themes/
and received the following message "Template Part Not Found" on my Windows server.

I discovered that `validate_file()` returns 2 for a fully qualified file e.g.
`C:/apache/htdocs/wp56/wp-content/themes/fizzie/block-template-parts/header.html`.

gutenberg_render_block_core_template_part() doesn't cater for this value.
So the function fails to load the template part.

**To reproduce**
1. On a Windows server
2. Follow instructions to develop a theme for Full Site Editing
3. View some content. e.g. Visit site.
4. See the `Template Part Not Found` as part of the output.

**Expected behavior**
Code should be able to load template part files in a Windows server environment.

I suggest either change the logic to support a return value of 2 from validate_file().
or don't call validate_file() and validate the value for the `slug` attribute.

**Screenshots**
image

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] Gutenberg 5.5.1 with Full Site Editing selected.
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

I've implemented a local fix
```
$valid = validate_file( $template_part_file_path );
if ( ( 0 === $valid || 2 == $valid )  && file_exists( $template_part_file_path ) ) {
	$content = file_get_contents( $template_part_file_path );
}
```

### PR DESCRIPTION
**Pull request by bobbingwide**
## Description
In `gutenberg_render_block_core_template_part` when trying to find the template part from the theme's files, rather than calling `validate_file()` against the full file name, we just validate the slug part. This overcomes the problem that in a Windows server the return code is 2 when the file name contains the drive letter ( eg `C:` ).

## How has this been tested?
- Tested in a WordPress Multi Site environment with the TwentyTwenty-One Blocks theme.
- Only active plugin Gutenberg
- Not tested 

## Screenshots
- Without the fix the Template Part Not Found message is displayed twice.
image

- With the fix the header and footer templates are found. 

image

## Types of changes
Bug fix for #26010. This only fixes the problem as reported.

It does not improve on the message "Template Part Not Found". 
That's for later.

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-library/src/template-part/index.php [hunk 1]
```diff
@@ -40,7 +40,7 @@ function render_block_core_template_part( $attributes ) {
 			// Else, if the template part was provided by the active theme,
 			// render the corresponding file content.
 			$template_part_file_path = get_stylesheet_directory() . '/block-template-parts/' . $attributes['slug'] . '.html';
-			if ( 0 === validate_file( $template_part_file_path ) && file_exists( $template_part_file_path ) ) {
+			if ( 0 === validate_file( $attributes['slug'] ) && file_exists( $template_part_file_path ) ) {
```
Comment (youknowriad) [inline packages/block-library/src/template-part/index.php:43]: Do you know what's the purpose of this validate_file call? Why not just remove it?

Comment (bobbingwide) [reply packages/block-library/src/template-part/index.php:43]: It's to stop directory traversal.

**Review by youknowriad — APPROVED** [review]
Thanks for being patient here even for a small change. I appreciate it.
