### PR TITLE
Author, Author Bio, Author Name: Add a fallback for Author Archive Template

### LINKED ISSUE #55410: Author Name / Author Bio / Avatar: Not displayed in author archive template
### Description

@them-es reported this problem in [this comment](https://github.com/WordPress/gutenberg/pull/55352#issuecomment-1763832410).

When the following three blocks are inserted into the author archive template, the information is not displayed correctly on the front end.

- Avatar
- Author Name
- Author Biography

On the other hand, the Post Author block displays the correct information. This is probably because it uses the author query parameter when no post context exists.

I think similar fallbacks are needed for these three blocks as well:

https://github.com/WordPress/gutenberg/blob/017d1ad368b0a0c4dcd9d148fa196919ebe43246/packages/block-library/src/post-author/index.php#L17-L21

### Step-by-step reproduction instructions

- Add Author Archive template.
- Enter the following code in the template's code editor and save it.
  ```
  <!-- wp:post-author {"showBio":true} /-->
  <!-- wp:post-author-name /-->
  <!-- wp:post-author-biography /-->
  <!-- wp:avatar /-->
  ```
- Create a user with the bio. Please note your user ID.
- Access `http://localhost:8888/?author={user_id}`.
- The three blocks listed above should not display author information.
- At the same time, you should see the following error:
  ```
  Warning: Undefined array key "postId" in /var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/avatar.php on line 34
  ```

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 6.4-RC1
- I also reproduce it with the latest Gutenberg trunk.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #55410
Similar to #40648

Props to @them-es for reporting the issue with [this comment](https://github.com/WordPress/gutenberg/pull/55352#issuecomment-1763832410).

## What?

This PR fixes an issue where the block is not displayed in the Author Archive template or a warning error occurs when the author has no posts in the following three blocks.

- Avatar
- Author Name
- Author Biography

## Why?

These three blocks assume that a post ID context (`$block->context['postId']`) exists. But my understanding is that if that author hasn't posted any articles yet, the post ID context doesn't exist, so the block won't show up or you'll get an error.

Since the Author Archive page is accessible, I think they should be rendered correctly even in cases where they don't have any posts.

## How?

Use `author` query parameter as ID when no post context exists.

## Testing Instructions

- First, create a user with an avatar. For example, if you register as a user using the email address below, the avatar will be displayed.
  - `test1@example.com`
  - `test2@example.com`
  - `test3@example.com`
- Enter the user's biography (Also, please note the author ID).
- Create the Author Archive template in the Site Editor.
- Enter the following code in the code editor and save it.
  ```
  <!-- wp:post-author-name /-->
  <!-- wp:post-author-biography /-->
  <!-- wp:avatar /-->
  ```
- Access `http://localhost:8888/?author={user_id}`.
- Although this author does not have any posts, their avatar, name, and biography should all be displayed correctly.

### CODE REVIEW

File: packages/block-library/src/post-author-biography/index.php [hunk 1]
```diff
@@ -15,10 +15,11 @@
  */
 function render_block_core_post_author_biography( $attributes, $content, $block ) {
 	if ( ! isset( $block->context['postId'] ) ) {
-		return '';
+		$author_id = get_query_var( 'author' );
+	} else {
+		$author_id = get_post_field( 'post_author', $block->context['postId'] );
 	}
```
Comment (aaronrobertshaw) [inline packages/block-library/src/post-author-biography/index.php]: Nit: Now this conditional is more than a simple guard clause, perhaps it should test for the positive scenario? Sort of like the code style guidelines recommend for [ternary operators](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#ternary-operator). 

I don't feel strongly about this but it might be good to have all three locations logic match at least 🤷

**Review by aaronrobertshaw — APPROVED** [review]
This tests as advertised for me. Nice work @t-hamano 👍 

✅ Could replicate issue on trunk
✅ Avatar, Post Author Biography, and Post Author Name blocks render correctly in author archive
✅ Updated blocks continue to work as intended in other contexts where query string arg isn't provided
✅ Couldn't spot any other blocks or locations needing the same tweak

I left one tiny nit/suggestion. Whether you adopt it or not, I'll leave up to you.

File: packages/block-library/src/post-author-biography/index.php (hunk 1 above)
Comment (t-hamano) [reply packages/block-library/src/post-author-biography/index.php]: Thanks for the review!

I rewrote the two places by [8151386](https://github.com/WordPress/gutenberg/pull/55451/commits/81513868e918c6c9865f668a63d44c98ee3265d1). If I rewrite [this part](https://github.com/WordPress/gutenberg/pull/55451/files#diff-4221bdc24052b61ece34522bef8a97b93315c029841b6dbdf44ac6d301a999c5R34-R40) using the ternary operator, nested conditional statements will occur, so I think it's fine as is, but what do you think?

Comment (aaronrobertshaw) [reply packages/block-library/src/post-author-biography/index.php]: Apologies if I wasn't clear with my suggestion. I didn't mean that you needed to change these if/else statements to ternaries, just that we should check the positive case first. Like what is suggested for when you do use ternary operators. 

This is such a minor detail, don't feel you need to keep changing the code over it.

Below is a quick diff to illustrate what I was originally suggesting:

<details>
<summary>Example diff</summary>

```diff
diff --git a/packages/block-library/src/post-author-biography/index.php b/packages/block-library/src/post-author-biography/index.php
index 6c4cdc301e..23f5f16cbc 100644
--- a/packages/block-library/src/post-author-biography/index.php
+++ b/packages/block-library/src/post-author-biography/index.php
@@ -14,7 +14,11 @@
  * @return string Returns the rendered post author biography block.
  */
 function render_block_core_post_author_biography( $attributes, $content, $block ) {
-	$author_id = isset( $block->context['postId'] ) ? get_post_field( 'post_author', $block->context['postId'] ) : get_query_var( 'author' );
+	if ( isset( $block->context['postId'] ) ) {
+		$author_id = get_post_field( 'post_author', $block->context['postId'] );
+	} else {
+		$author_id = get_query_var( 'author' );
+	}
 
 	if ( empty( $author_id ) ) {
 		return '';
diff --git a/packages/block-library/src/post-author-name/index.php b/packages/block-library/src/post-author-name/index.php
index 92d37f70f9..a5fadfcbf3 100644
--- a/packages/block-library/src/post-author-name/index.php
+++ b/packages/block-library/src/post-author-name/index.php
@@ -14,7 +14,11 @@
  * @return string Returns the rendered post author name block.
  */
 function render_block_core_post_author_name( $attributes, $content, $block ) {
-	$author_id = isset( $block->context['postId'] ) ? get_post_field( 'post_author', $block->context['postId'] ) : get_query_var( 'author' );
+	if ( isset( $block->context['postId'] ) ) {
+		$author_id = get_post_field( 'post_author', $block->context['postId'] );
+	} else {
+		$author_id = get_query_var( 'author' );
+	}
 
 	if ( empty( $author_id ) ) {
 		return '';

```

</details>

Comment (t-hamano) [reply packages/block-library/src/post-author-biography/index.php]: Ah, I mistakenly thought that I should use ternary operators itself. I understand what you mean 😅

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for your patience here @t-hamano 👍 

I've given this another quick smoke test and it LGTM!

🚢
