### PR TITLE
Cover: Padding: Fix reset + Visualize on hover

### LINKED ISSUE #23030: Cover: Reset should remove all user changes
**Describe the bug**

The new Padding controls should remove user changes when "Reset" is clicked. At the moment, it only removes session based changes.

This issue was originally discussed here:
https://github.com/WordPress/gutenberg/pull/21492#issuecomment-641236713

**To reproduce**

* sets a value for padding to 20
* saves the post
* reloads the editor
* click reset
* at this point, the padding value is 20 but reset doesn't work (I expected I'd be able to reset them)

**Expected behavior**

* sets a value for padding to 20
* saves the post
* reloads the editor
* click reset
* Padding should be 0. No padding inline styles

### PR DESCRIPTION
**Pull request by ItsJonQ**
Screen Shot 2020-06-09 at 2 09 32 PM

This update fixes the  **reset** handling for the new experimental Padding controls for the **Cover** block.

### ♻️ Reset Handling

Clicking reset now removes padding values completely.

It sets the values to `null`, which removes inline styling rendering into the Cover. This is an important detail, as we should **still allow** for users to set values of `0px`, which is different than no value (`null`).

### ✨ Improved Visualizers

Screen Capture on 2020-06-09 at 14-37-40

The Padding visualizers have been enhanced to show when the user hovers any one of the Padding controls. The visualizers also maintain the ability to flash during changes. Previously, the visualizers only revealed themselves on change.

### 📖 Update padding style (hook) namespace

This update changes the style hook of padding to be namespaced as:

```
style.spacing.padding = { ... }
```

Previously, it existed as

```
style.padding = { ... }
```

In order for the visualizers to be programmatically triggered (by hover interactions), the show/hide values have also been added to the style Object as:

```
style.visualizers.padding = { ... }
```

This works. However, I feel like there could be a better way to connect these 2 Components (while avoiding adding state to the global `wp.data`). The solution I'm imagining would look similar to [Zustand](https://github.com/react-spring/zustand)

## How has this been tested?
* Tested locally in Storybook
* Tested in local Gutenberg

To test...

* run `npm run dev`
* Add `add_theme_support( 'experimental-custom-spacing' )` (a place could be the `normalize-theme.php` file, under `normalize_theme_init`)
* Add a Cover block
* Change the padding to 10px
* Visualizers should flash
* Hover the padding input
* Visualizers should show
* Click reset
* Padding input value should be empty
* Change padding value to 20px
* Save
* Refresh
* Check the Cover post padding
* It should be 20px
* Click reset
* Padding input value should be empty

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. 

Resolves: https://github.com/WordPress/gutenberg/issues/23030

### CODE REVIEW

File: packages/components/src/box-control/index.js [hunk 1]
```diff
@@ -43,17 +48,21 @@ export default function BoxControl( {
...
 
-	const [ isDirty, setIsDirty ] = useState( false );
-	const [ isLinked, setIsLinked ] = useState( ! isValuesMixed( values ) );
-	const [ side, setSide ] = useState( isLinked ? 'all' : 'top' );
+	const [ isDirty, setIsDirty ] = useState( hasInitialValue );
+	const [ isLinked, setIsLinked ] = useState(
+		! hasInitialValue || ! isValuesMixed( inputValues )
+	);
 
-	const initialValuesRef = useRef( values );
```
Comment (ItsJonQ) [inline packages/components/src/box-control/index.js:56]: No longer needed. It was previously used to hold onto the initial value for the session.
We need the reset action to completely nullify the box values.

File: packages/components/src/box-control/unit-control.js [hunk 2]
```diff
@@ -8,12 +14,22 @@ export default function BoxUnitControl( {
 	isFirst,
 	isLast,
 	isOnly,
+	onHoverOn = noop,
+	onHoverOff = noop,
 	label,
 	value,
 	...props
 } ) {
+	const bindHoverGesture = useHover( ( { event, ...state } ) => {
```
Comment (ItsJonQ) [inline packages/components/src/box-control/unit-control.js:23]: Thank you `react-use-gesture` 🙏 !

**Comment by paaljoachim** [comment]
Will this be added to 8.3.1?

**Comment by jasmussen** [comment]
This is cool, Q! My local dev env is a bit challenged at the moment so I can't reliably test this. But based on the images, this seems to just need a code review! 👍 👍

> Will this be added to 8.3.1?

Given this is still strictly opt-in and probably not yet on anyone's radar, it does not seem to warrant a point release.

**Review by oandregal — APPROVED** [review]

**Comment by nosolosw** [comment]
This will be backported for 8.3 release as part of https://github.com/WordPress/gutenberg/pull/23026 as the other bugfixes we prepared during RC testing (the hook namespace change is a must-have to avoid block deprecations in future releases).

Certainly, the visualizers improvement is not a bugfix but a lovely feature! :star2: As a general rule, I think it'd be good to only land bugfixes after RC. However, in this specific case, given that the PR does all the things at once and that it's a new feature yet to be released, I'm ok going ahead with this. Worst-case scenario, we have to do a 8.3.1.
