### PR TITLE
Site Editor: Run inject and remove theme attribute recursively

### LINKED ISSUE #28814: FSE: Template parts included in template parts are not found
## Description

When a template part includes another template part, the "Template part not found" message is displayed on the front.

In the site editor, the template part is visible as an empty selectable template part block. There is no content in the template part. The console shows:
```
index.php?rest_route=%2Fwp%2Fv2%2Ftemplate-parts%2Fundefined%2F%2Fmeta&context=edit&_locale=user:1 Failed to load resource: the server responded with a status of 404 (Not Found)
index.php:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

The template part slug is meta:
https://github.com/WordPress/theme-experiments/pull/199/files#diff-655c9902613a59b3d9282cbfcc4a4efbd7dec8dd16a77b0911a0a0bbf181e297L3

The theme folder is in the  wp-content/themes/ folder, not a subfolder.
If I add the theme attribute to the template part, the template part works as expected.

## Step-by-step reproduction instructions
1. Activate a full site editing theme that has been updated to work with 9.9.0, or you can try Armando from the theme experiments repo.
2. Add a template part inside a template part.
3. View the template in the site editor, see that the template part is empty.
4. View the template on the front, see the error message.

## Expected behaviour

I expect the template part to display without errors.

## Actual behaviour

The template part is not found.

## Screenshots or screen recording (optional)

Site editor, template part without content:
template part

## WordPress information
- WordPress version: WordPress 5.7 Beta 1.
- Gutenberg version: Tested with 9.9.0 and current master.
- Are all plugins except Gutenberg deactivated?  No, the beta tester plugin is installed
- Are you using a default theme (e.g. Twenty Twenty-One)? No, Armando: 
https://github.com/WordPress/theme-experiments/pull/199/files#diff-655c9902613a59b3d9282cbfcc4a4efbd7dec8dd16a77b0911a0a0bbf181e297L3

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome Version 88.0.4324.150

### PR DESCRIPTION
**Pull request by david-szabo97**
Fixes #28814 

## Description
`_inject_theme_attribute_in_content` and `_remove_theme_attribute_from_content` didn't take nested template parts into account. This PR adjusts these functions to walk through all the nested blocks as well.

## How has this been tested?
You can use the following block template theme file:

```html
<!-- wp:group -->
<div class="wp-block-group">
  <!-- wp:group -->
  <div class="wp-block-group">
    <!-- wp:group -->
    <div class="wp-block-group">
      <!-- wp:group -->
      <div class="wp-block-group">
        <!-- wp:group -->
        <div class="wp-block-group">
          <!-- wp:template-part {"slug":"header","tagName":"header","className":"site-header","layout":{"inherit":true}} /-->
        </div>
        <!-- /wp:group -->
      </div>
      <!-- /wp:group -->
    </div>
    <!-- /wp:group -->
  </div>
  <!-- /wp:group -->
</div>
<!-- /wp:group -->
```

1. Open wp-admin
2. Enable a theme that you have access to
3. Add the template above to `block-templates` directory
4. Open site editor
5. Open the template you created/modified in step 3
6. Make sure template part loads

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by youknowriad** [comment]
This looks like a duplicate of https://github.com/WordPress/gutenberg/pull/30413 ? you guys should review each other's PRs and decide what's the best path :P

File: lib/full-site-editing/block-templates.php [hunk 1]
```diff
@@ -137,6 +137,35 @@ function _gutenberg_add_template_part_area_info( $template_info ) {
...
+ * @return array block references to the passed blocks and their inner blocks.
+ */
+function _get_blocks_recursive( &$blocks ) {
+	$all_blocks = array();
+	$queue      = array();
+	foreach ( $blocks as &$block ) {
+		$queue[] = &$block;
+	}
+
+	for ( $i = 0; $i < count( $queue ); $i++ ) {
```
Comment (vindl) [inline lib/full-site-editing/block-templates.php]: I found growing the queue size in the loop a bit weird, but couldn't think of a better way to deal with these that would preserve the references.

File: lib/full-site-editing/block-templates.php [hunk 2]
```diff
@@ -137,6 +137,35 @@ function _gutenberg_add_template_part_area_info( $template_info ) {
...
 
+/**
+ * Returns an array containing the references of
+ * the passed blocks and their inner blocks.
+ *
+ * @param array $blocks array of blocks.
+ *
+ * @return array block references to the passed blocks and their inner blocks.
+ */
+function _get_blocks_recursive( &$blocks ) {
```
Comment (vindl) [inline lib/full-site-editing/block-templates.php]:
```suggestion
function _flatten_blocks( &$blocks ) {
```

File: lib/full-site-editing/block-templates.php [hunk 3]
```diff
@@ -150,18 +179,19 @@ function _inject_theme_attribute_in_content( $template_content ) {
 	$new_content         = '';
 	$template_blocks     = parse_blocks( $template_content );
```
Comment (vindl) [inline lib/full-site-editing/block-templates.php:181]: Not related to this PR, but I noticed that `parse_blocks` returns a few empty blocks/elements in the array (with `blockName` => `NULL` and other elements empty). Is it just me and is this a known/expected thing?

**Review by vindl — APPROVED** [review]
Fixes the issue as described. 👍

File: lib/full-site-editing/block-templates.php (hunk 1 above)
Comment (Addison-Stavlo) [reply lib/full-site-editing/block-templates.php]: I found it a little odd at first too, but after a minute it sits pretty well imo.  

> couldn't think of a better way to deal with these that would preserve the references.

Perhaps the recursive function approach would still work here since we are assigning by reference?  I don't think its necessary though.  This reads just as well as that would.

**Review by Addison-Stavlo — APPROVED** [review]
Looks good and tests well on my end! 🎉

File: lib/full-site-editing/block-templates.php (hunk 1 above)
Comment (david-szabo97) [reply lib/full-site-editing/block-templates.php]: I prefer iteration over recursion. That's why the growing queue array.

File: lib/full-site-editing/block-templates.php (hunk 2 above)
Comment (david-szabo97) [reply lib/full-site-editing/block-templates.php]: Nice! Thanks!

File: lib/full-site-editing/block-templates.php (hunk 1 above)
Comment (Addison-Stavlo) [reply lib/full-site-editing/block-templates.php]: > I prefer iteration over recursion. 

I tend to agree with you on that. 😁

File: lib/full-site-editing/block-templates.php (hunk 3 above)
Comment (david-szabo97) [reply lib/full-site-editing/block-templates.php:181]: Looks like those are used to catch text between blocks.
See here first block is a template part, then there is an empty line in the code before the group block:
```html
<!-- wp:template-part {"slug":"header","tagName":"header","className":"site-header","layout":{"inherit":true}} /-->

<!-- wp:group {"tagName":"main","layout":{"inherit":true}} -->
......
......

This is represented in "blocks" like this:
```
image

**Comment by carolinan** [comment]
The template part in the sample content above works well.
But template parts inside other template parts are not working on the front, only in the site editor. The "Template part has been deleted or is unavailable" message is showing.

This can be tested in TT1 Blocks for example by copy pasting the template part call for the footer,
`
` into the header template part.

**Comment by david-szabo97** [comment]
Thanks for catching that @carolinan ! Can you give it a second round with the latest commit?

File: packages/block-library/src/template-part/index.php [hunk 4]
```diff
@@ -60,7 +60,7 @@ function render_block_core_template_part( $attributes ) {
 			// render the corresponding file content.
 			$template_part_file_path = get_stylesheet_directory() . '/block-template-parts/' . $attributes['slug'] . '.html';
 			if ( 0 === validate_file( $attributes['slug'] ) && file_exists( $template_part_file_path ) ) {
-				$content = file_get_contents( $template_part_file_path );
+				$content = _inject_theme_attribute_in_content( file_get_contents( $template_part_file_path ) );
```
Comment (david-szabo97) [inline packages/block-library/src/template-part/index.php:63]: This makes sure that nested template parts' theme is injected as well.

**Comment by carolinan** [comment]
Both nested blocks and template parts inside template parts are working for me now. Any chance this can go into 10.4 ?

**Review by carolinan — APPROVED** [review]

**Comment by youknowriad** [comment]
@carolinan sure, I can do that
