### PR TITLE
Resizable editor: fix height setting bug

### LINKED ISSUE #42226: Canvas height in focus mode should wrap document contents
I'm sure we discussed this elsewhere but I am struggling to find the issue. Apologies in advance if this is a duplicate.

---

When you enter focus mode to edit something like a header, the canvas stretches to fill the viewport. This can make it difficult to understand the boundaries of the entity you're editing:

https://user-images.githubusercontent.com/846565/177759317-4c5f936a-2be3-48bc-83dc-c95af92d4930.mp4

Ideally the canvas should wrap its contents more precisely, something like:

Screenshot 2022-07-07 at 12 09 08

### PR DESCRIPTION
**Pull request by glendaviesnz**
## What?
Simplifies the code which sets the initial height of the resizable iframed editor

## Why?
Fixes: #42226

## How?
Removes additional timeouts that wait for iframe page load and rely on the iframe load event listener

## Testing Instructions

- Load the site editor and select to edit a template part, eg. header
- Check that the isolated header iframe loads the correct size
- Try multiple page loads and make sure it loads the same size each time

## Screenshots or screencast 

Before:

https://user-images.githubusercontent.com/677833/191464237-dcea53df-fda6-428b-bff3-209fc60abcf4.mp4

After:

https://user-images.githubusercontent.com/3629020/193698904-d3f7465a-df89-4a85-a33d-20d05664c499.mp4

### CODE REVIEW

File: packages/edit-site/src/components/block-editor/resizable-editor.js [hunk 1]
```diff
@@ -57,54 +57,32 @@ function ResizableEditor( { enableResizing, settings, children, ...props } ) {
...
-						// 30 frames per second.
-					}, 1000 / 30 );
-				}
+			const iframe = iframeRef.current;
+
+			function setFrameHeight() {
+				setHeight( iframe.contentDocument.body.scrollHeight );
 			}
 
+			iframe.addEventListener( 'load', setFrameHeight );
```
Comment (talldan) [inline packages/edit-site/src/components/block-editor/resizable-editor.js]: It looks like this ends up duplicating the call to `setFrameHeight` in `registerObserver`, which is also triggered by the 'load' event. It'd be good to remove one of those calls. Maybe consolidate everything into the one function.

**Review by talldan — COMMENTED** [review]
It definitely seems a lot more reliable, and the code is a lot simpler.

I did manage to trigger the issue once or twice right at the start of my testing, but I must have switched between templates another 30 times and refreshed the page another 50 times and didn't see any problems again.

File: packages/edit-site/src/components/block-editor/resizable-editor.js (hunk 1 above)
Comment (glendaviesnz) [reply packages/edit-site/src/components/block-editor/resizable-editor.js]: ah, true, have removed the extra listener.

File: packages/edit-site/src/components/block-editor/resizable-editor.js [hunk 2]
```diff
@@ -97,28 +73,23 @@ function ResizableEditor( { enableResizing, settings, children, ...props } ) {
...
 				// have a height of `100%`.
 				resizeObserver.observe( iframe.contentDocument.body );
-
-				resizeHeight();
+				setFrameHeight();
 			}
 
-			// This is only required in Firefox for some unknown reasons.
 			iframe.addEventListener( 'load', registerObserver );
-			// This is required in Chrome and Safari.
```
Comment (glendaviesnz) [inline packages/edit-site/src/components/block-editor/resizable-editor.js:112]: this doesn't seem to be the case anymore, and actually causes `registerObserver` to run twice - the single event listener seems to work across Chrome, Safari and Firefox in my testing

**Comment by glendaviesnz** [comment]
It would be nice to get rid of the jankyness of the load, eg. show a loading animation until the initial height is set, but that is probably an enhancement to look at for 6.2

**Comment by talldan** [comment]
> It would be nice to get rid of the jankyness of the load, eg. show a loading animation until the initial height is set, but that is probably an enhancement to look at for 6.2

Hopefully it's addressed as part of the ongoing work in https://github.com/WordPress/gutenberg/issues/35503 and https://github.com/WordPress/gutenberg/pull/42525.

**Review by talldan — APPROVED** [review]
Looks good, nice work!

**Comment by ockham** [comment]
I just cherry-picked this PR to the wp/6.1 branch to get it included in the next release: eba279ed9f
