### PR TITLE
Hide the columns count control on empty columns block

### LINKED ISSUE #16343: Columns block errors when interacting with sidebar slider in placeholder mode
**Describe the bug**

When creating a new column block, when the placeholder is showing, trying to interact with the sidebar "Columns" slider that allows us to adjust the number of columns causes the placeholder to disappear and the block to become unusable.

**To reproduce**
1. Create a new post.
2. Add a "Columns" block.
3. Open the sidebar and click on "Columns" slider.
4. Verify that placeholder has now disappeared from block and nothing happens when clicking inside it.

**Expected behavior**

Expected either that clicking on "Columns" slider would allow me to adjust the number of columns, or else the slider to be disabled when block is in placeholder mode.

**Screenshots**

ezgif-4-ce1535f3d746

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 75

**Additional context**

This is happening in my development environment on the master branch.
The browser console shows `Uncaught TypeError: Cannot read property 'clientId' of undefined
    at Object.blockSelection (reducer.js:768)` followed by `The above error occurred in the <InnerBlocks> component`.

### PR DESCRIPTION
**Pull request by youknowriad**
Small regression introduced by #16129 

closes #16343

When the columns block is in the "setup state", the columns count range control should be hidden.

### CODE REVIEW

**Comment by Soean** [comment]
Fixes #16343

File: packages/block-library/src/columns/edit.js [hunk 1]
```diff
@@ -170,9 +172,7 @@ export function ColumnsEdit( {
 						setForceUseTemplate( true );
 					} }
 					__experimentalAllowTemplateOptionSkip
-					// setting the template to null when the inner blocks
```
Comment (aduth) [inline packages/block-library/src/columns/edit.js]: Seems like this comment is still valid?

File: packages/block-library/src/columns/edit.js [hunk 2]
```diff
@@ -135,9 +135,11 @@ export function ColumnsEdit( {
 		[ `are-vertically-aligned-${ verticalAlignment }` ]: verticalAlignment,
 	} );
 
+	const showTemplateSelector = ( count === 0 && ! forceUseTemplate ) || ! template;
+
 	return (
 		<>
-			{ template && (
+			{ ! showTemplateSelector && (
```
Comment (aduth) [inline packages/block-library/src/columns/edit.js]: Alternatively, I wonder what it is about choosing columns that causes the issue in the first place. If someone wanted to skip the layout selection and just start setting columns (assuming of an equal width), why prevent them?

**Review by aduth — APPROVED** [review]

File: packages/block-library/src/columns/edit.js (hunk 2 above)
Comment (youknowriad) [reply packages/block-library/src/columns/edit.js]: yeah I'm not sure what. I decided to remove the selector not only because of the bug because based on the previous check here. I assumed that removing the inspector controls was an intentional behavior.
