### PR TITLE
Try the link control in the link format

### LINKED ISSUE #19056: Submitting a link in the navigation block using the enter key causes a console warning.
**Describe the bug**
Submitting a navigation link causes the warning 'Form submission canceled because the form is not connected' to appear in the console.

**To reproduce**
1. Add a navigation block
2. Choose the 'Create empty' option on the placeholder
3. Type in a URL and use the 'Enter' key to submit it.
4. See error in the console

**Expected behavior**
The console error does not occur.

### LINKED ISSUE #19270: Rich text blocks: add new link interface
Currently, paragraph block looks like this:

image

It would be good to bring in the new link interface from navigation:

link

This should be done across all rich text blocks, for example,  quote, heading, paragraph and quote.

### PR DESCRIPTION
**Pull request by youknowriad**
The LinkControl component has been developed specifically for the Navigation block but unless we use it everywhere elsewhere we need links, it's going to become very specific to the Navigation block.

So before adding a lot of features there that might not be generic enough, let's try to use it to replace the current Link control and other link UIs in other blocks.

This PR works but is still very bug. I'd appreciate help from experts :P cc @ellatrix @getdave 

closes #19056
closes #19270

### CODE REVIEW

File: packages/block-editor/src/components/link-control/index.js [hunk 1]
```diff
@@ -202,9 +205,9 @@ function LinkControl( {
 										className="block-editor-link-control__search-item-title"
 										href={ value.url }
 									>
-										{ value.title }
+										{ value.title || displayURL }
```
Comment (youknowriad) [inline packages/block-editor/src/components/link-control/index.js]: I don't think we have a "title" for the link in the case of the format link. So LinkControl should handle properly the case where there's no title.

File: packages/block-editor/src/components/link-control/index.js [hunk 2]
```diff
@@ -78,8 +80,8 @@ function LinkControl( {
 
 		// Populate input searcher whether
 		// the current link has a title.
-		if ( value && value.title && mode === 'edit' ) {
-			setInputValue( value.title );
+		if ( value && value.url && mode === 'edit' ) {
+			setInputValue( value.url );
```
Comment (youknowriad) [inline packages/block-editor/src/components/link-control/index.js]: I went back to url here @getdave since it's the most common denominator between all links.

**Review by youknowriad — COMMENTED** [review]
I noticed that you can't resubmit a link you want to edit without making any modification, it seems like the Input is missing a submit button or something. Otherwise choosing a suggestion becomes mandatory so we need to type again.

File: packages/block-editor/src/components/link-control/index.js (hunk 2 above)
Comment (getdave) [reply packages/block-editor/src/components/link-control/index.js]: I see. I see why you are doing this, but do you think we should document an Issue regarding re-population of the text box with the most appropriate thing for a given link depending on it's `type`?

As mentioned previously, if we search for a `Post` and then select one of the search results, the resulting URL is of little concern to us. Therefore imagine my surprise as a user when having click "change" I'm presented with the URL of my `Post` rather than the original search text I entered.

File: packages/block-editor/src/components/link-control/index.js [hunk 3]
```diff
@@ -181,6 +183,7 @@ function LinkControl( {
 			onClose={ closeLinkUI }
 			position="bottom center"
 			focusOnMount="firstElement"
+			{ ...popoverProps }
```
Comment (getdave) [inline packages/block-editor/src/components/link-control/index.js]: This seems logical.

File: packages/block-editor/src/components/link-control/index.js (hunk 1 above)
Comment (getdave) [reply packages/block-editor/src/components/link-control/index.js]: Good catch. Thank you.

**Review by getdave — COMMENTED** [review]
Thanks for doing this. I'm surprised as to how nice this feels.

One thing I noticed was that once I created a link of portion of text in a paragraph block I couldn't easily dismiss the popover UI.

I do wonder whether an explicit "close" icon could be required even if it adds a little extra clutter to the UI.

File: packages/block-editor/src/components/link-control/index.js (hunk 2 above)
Comment (youknowriad) [reply packages/block-editor/src/components/link-control/index.js]: If we do what you suggest, what happens when you click "edit". I expect three things:

 - the "type" of the link need to be persisted in value/onChange to know how to apply it back
 - if I edit the link, I expect the selected post to be highlighted in the suggestions and I think the  text/title is not enough to perform this as it's ambiguous 
 - If I edit the link, I should be able to submit it again without any change,  keeping the exact same value, which doesn't seem possible today as well.

For these reasons, I think it's probably better to start with the "URL" (more deterministic so easier for resubmits, searches), we can explore an alternative though.

File: packages/block-editor/src/components/link-control/index.js (hunk 3 above)
Comment (youknowriad) [reply packages/block-editor/src/components/link-control/index.js]: I actually think, there's something wrong in the control for now. I feel instead of directly being a "Popover", we need two components:

 - LinkControl,  which is an inline UI to edit links. (like all controls, TextControl, SelectControl, CustomSelectControl... )
 - LinkControlPopover, potentially this is useless and can be easily replaced with just Popover wrapping LinkControl.

File: packages/block-editor/src/components/link-control/index.js (hunk 2 above)
Comment (getdave) [reply packages/block-editor/src/components/link-control/index.js]: Yes sorry in this PR I think URl is the best all-round solution. 

I'm mainly highlighting the potential UX issue here. I still feel it's relevant despite the technical and design hurdles. I'll raise an Issue unless you object?

**Comment by getdave** [comment]
> I noticed that you can't resubmit a link you want to edit without making any modification, it seems like the Input is missing a submit button or something. Otherwise choosing a suggestion becomes mandatory so we need to type again.

Noted. Shall we fix this here? I think just a simple submit button?

**Comment by youknowriad** [comment]
This is looking cool, there's still some e2e tests to fix (probably due to different interactions, new UI) but we should get some design eyes. @jasmussen @karmatosed

File: packages/block-editor/src/components/link-control/index.js (hunk 3 above)
Comment (getdave) [reply packages/block-editor/src/components/link-control/index.js]: Yes, `LinkControl` should be independent of `Popover`. You should be able to render the control wherever you want.

This PR or another one @youknowriad ?

Comment (youknowriad) [reply packages/block-editor/src/components/link-control/index.js]: Let's keep it for another one.

**Comment by karmatosed** [comment]
Wow, this is great work @youknowriad! It really fits in better than I thought it would without much adjusting.

image

I don't see this yet on images so I guess this hasn't been added yet there?

image

I can test each block once we do have it added though, for now, the feeling I have is that this is a great way forward to unify the link interface and stop having so many.

File: packages/format-library/src/link/inline.js [hunk 4]
```diff
@@ -17,20 +18,27 @@ import {
...
+	useEffect( () => {
+		return () => stopAddingLink();
+	}, [] );
+
+	useEffect( () => {
+		// Should remount the popover to focus it properly when isAdddingLink changes
+		if ( addingLink ) {
+			setMountingKey( uniqueId() );
+		}
+	}, [ addingLink ] );
```
Comment (youknowriad) [inline packages/format-library/src/link/inline.js]: I noticed in e2e tests that there's an expectation that the focus move back to the Popover if we hit "ctrl+k" on an existing link. This is a hack that does that (a similar more implicit hack was used before)

File: packages/format-library/src/link/inline.js [hunk 5]
```diff
@@ -56,181 +64,55 @@ const URLPopoverAtLink = ( { isActive, addingLink, value, ...props } ) => {
...
-		this.setState( { editLink: false } );
-	}
-
-	render() {
-		const { isActive, activeAttributes: { url }, addingLink, value } = this.props;
-
-		if ( ! isActive && ! addingLink ) {
-			return null;
+		if ( addingLink ) {
+			stopAddingLink();
```
Comment (youknowriad) [inline packages/format-library/src/link/inline.js]: Calling this here ensures that the focus moves back to the RichText somehow 🤷‍♂which is expected in e2e tests.

My personal expectation was that the focus should stay in the popover and potentially when I hit "Escape" it moves back to RichText. I decided to not pursue this right now in this PR because:

 - There's no explicit API for a Format to say "move back to RichText"
 - The RichText autofocus on format hack is still not removed
 - I didn't want to change the behavior compared to master in this refactoring PR.

File: packages/e2e-tests/specs/editor/various/links.test.js [hunk 6]
```diff
@@ -364,42 +370,6 @@ describe( 'Links', () => {
 		expect( assertiveContent.trim() ).toBe( 'Warning: the link has been inserted but may have errors. Please test it.' );
 	} );
 
-	it( 'link popover remains visible after a mouse drag event', async () => {
```
Comment (youknowriad) [inline packages/e2e-tests/specs/editor/various/links.test.js]: I removed it because I believe it's not useful with the new UI.

File: packages/format-library/src/link/inline.js (hunk 4 above)
Comment (ellatrix) [reply packages/format-library/src/link/inline.js]: Sounds good. We can iterate later on a better solution.

File: packages/block-editor/src/components/link-control/index.js [hunk 7]
```diff
@@ -43,16 +43,18 @@ const MODE_EDIT = 'edit';
 
 function LinkControl( {
 	className,
-	value,
+	value = {},
```
Comment (ellatrix) [inline packages/block-editor/src/components/link-control/index.js]: What properties can this object have? Can they not be normal props instead of nested props?

Comment (youknowriad) [reply packages/block-editor/src/components/link-control/index.js]: right now, url, title, openInNewTab but it supports custom settings adding custom properties there.

File: packages/format-library/src/link/inline.js (hunk 5 above)
Comment (ellatrix) [reply packages/format-library/src/link/inline.js]: See https://github.com/WordPress/gutenberg/pull/19536. We can address it later.

**Review by ellatrix — APPROVED** [review]
This is awesome! I tested and its looks very nice. Love the reduction in code.

**Comment by youknowriad** [comment]
Looks like the links test is failing but not consistently, not sure what's causing this.

**Comment by ellatrix** [comment]
@youknowriad I do see a warning when inserting a link manually (not automated test)

> Form submission canceled because the form is not connected

**Comment by ellatrix** [comment]
Screenshot 2020-01-10 at 13 54 40

I can reproduce it consistently.

**Comment by youknowriad** [comment]
@ellatrix this should be fixed by the last commit. The LinkControl could be simplified a lot by removing the usage of URLInput. Basically "suggestions" are handled twice, by LinkControl and by URLInput causing a submission of an unmounted form, it should be fixed now.

**Comment by ellatrix** [comment]
This is a strange error... It almost looks like the value is not updated in time for the form submission. Is the state set after a delay maybe?

```
● Links › can be created by selecting text and using keyboard shortcuts
845
846    expect(received).toMatchSnapshot()
847
848    Snapshot name: `Links can be created by selecting text and using keyboard shortcuts 1`
849
850    - Snapshot
851    + Received
852
853      "<!-- wp:paragraph -->
854    - <p>This is <a href="https://wordpress.org/gutenberg">Gutenberg</a></p>
855    + <p>This is <a href="https://wordpress.org/gute">Gutenberg</a></p>
856      <!-- /wp:paragraph -->"
```

**Comment by youknowriad** [comment]
I don't know. @getdave might?

**Comment by youknowriad** [comment]
There's a lot of indirection between the LinkControl component and the URLInput one making this very hard to reason about and debug, I feel solving this issue #19523 would solve these fragile tests too.

File: packages/e2e-tests/specs/editor/blocks/__snapshots__/buttons.test.js.snap [hunk 8]
```diff
@@ -3,7 +3,7 @@
 exports[`Buttons can jump to the link editor using the keyboard shortcut 1`] = `
 "<!-- wp:buttons -->
 <div class=\\"wp-block-buttons\\"><!-- wp:button -->
-<div class=\\"wp-block-button\\"><a class=\\"wp-block-button__link\\">WordPress</a></div>
+<div class=\\"wp-block-button\\"><a class=\\"wp-block-button__link\\" href=\\"https://www.wordpress.org/\\" title=\\"\\">WordPress</a></div>
```
Comment (aduth) [inline packages/e2e-tests/specs/editor/blocks/__snapshots__/buttons.test.js.snap]: Probably logical, not sure if it's explicitly related here. Also implemented in #19490.

File: packages/e2e-tests/specs/editor/blocks/navigation.test.js [hunk 9]
```diff
@@ -134,12 +134,5 @@ describe( 'Navigation', () => {
 
 		// Expect a Navigation Block with two Navigation Links in the snapshot.
 		expect( await getEditedPostContent() ).toMatchSnapshot();
-
-		// TODO - this is needed currently because when adding a link using the suggestion list,
-		// a submit button is used. The form that the submit button is in is unmounted when submission
-		// occurs, resulting in a warning 'Form submission canceled because the form is not connected'
-		// in Chrome.
-		// Ideally, the suggestions wouldn't be implemented using submit buttons.
-		expect( console ).toHaveWarned();
```
Comment (aduth) [inline packages/e2e-tests/specs/editor/blocks/navigation.test.js]: Related: #19056

Also: #19551 (not sure yet if and how it relates to this effort)

File: packages/block-editor/src/components/link-control/index.js [hunk 10]
```diff
@@ -161,7 +163,8 @@ function LinkControl( {
 							key={ `${ suggestion.id }-${ suggestion.type }` }
 							itemProps={ buildSuggestionItemProps( suggestion, index ) }
 							suggestion={ suggestion }
-							onClick={ () => {
+							onClick={ ( event ) => {
+								event.preventDefault();
```
Comment (aduth) [inline packages/block-editor/src/components/link-control/index.js]: There's been a bit of back and forth with this (#18933, #19056), but at least with this edit, it has me wondering: If the intention here is to prevent the form submission caused by `<button type="submit">`, then why should we assign `type="submit"` at all? What are the cases where we _want_ the default behavior to be allowed?

At the very least, if we keep it, we should include some inline comment which explains what we're doing with `preventDefault` and why.

File: packages/block-editor/src/components/link-control/index.js (hunk 3 above)
Comment (aduth) [reply packages/block-editor/src/components/link-control/index.js]: It's a bit weird that we grant that we want to remove the Popover rendering, in the same pull request where we're adding a new `popoverProps` prop. I guess we don't think it's an issue in that the component is already "experimental" anyways?

File: packages/block-editor/src/components/link-control/index.js (hunk 7 above)
Comment (aduth) [reply packages/block-editor/src/components/link-control/index.js]: 1. This should be documented (granted, not really the responsibility of the refactor)
2. In this current implementation, there's some added chance of extra work on the React reconciler, since the value is [passed through to `LinkControlSettingsDrawer`](https://github.com/WordPress/gutenberg/blob/2d1add52ec4f179b5e2fca0814a48c255f84da2b/packages/block-editor/src/components/link-control/index.js#L236), and it would be different each time if not provided explicitly (not a consistent default object reference).

**Comment by aduth** [comment]
> There's a lot of indirection between the LinkControl component and the URLInput one making this very hard to reason about and debug, I feel solving this issue #19523 would solve these fragile tests too.

Coming to this relatively fresh, I definitely sympathize with this. There seems to be a lot of different components which manage link editing in various ways, and it is very unclear to me what role each is intended to serve. How does `LinkControl` even relate to `URLInput` ? If they're made to be distinct as proposed in #19523, which should be used and in what situations? What about #19551 which seeks to introduce another component `BaseURLInput` for link management?

I'm glad someone decided to [include a README file for `LinkControl`](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/link-control/README.md), but it must assume some prior knowledge of how it's expected to be used, because it doesn't provide any context for why it exists.

File: packages/e2e-tests/specs/editor/blocks/navigation.test.js (hunk 9 above)
Comment (youknowriad) [reply packages/e2e-tests/specs/editor/blocks/navigation.test.js]: yes, this solves the first one (clicking a suggestion was removing the form but the same click was also submitting the form).

The second one, I believe we should just make sure LinkControl  (and its search subcomponent) replaces URLInput entirely instead of the weird relationship they have right now where almost everything is overridden with props.

File: packages/block-editor/src/components/link-control/index.js (hunk 10 above)
Comment (youknowriad) [reply packages/block-editor/src/components/link-control/index.js]: Agreed, ideally this onClick should be removed entirely but again because of the weird relation between LinkControl and URLInput we can't. And yes it prevents the submit. See https://github.com/WordPress/gutenberg/pull/19462#discussion_r365880414

File: packages/block-editor/src/components/link-control/index.js (hunk 3 above)
Comment (youknowriad) [reply packages/block-editor/src/components/link-control/index.js]: Exactly, that was my thinking. Trying to limit the changes to implement this and separate the Popover from the Control in its own PR.

**Comment by youknowriad** [comment]
@aduth yes, that's the root issue we should normalize these link components. My thinking is that we should use LinkControl for everything and provide a deprecation strategy for the others. We're not there yet though.

**Comment by aduth** [comment]
The current build failures can be pretty reliably reproduced locally using the [`THROTTLE_CPU` environment variable](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/testing-overview.md#end-to-end-testing).

From what I can tell so far, it seems there is not-too-unsurprisingly some unintended side effects of the many `preventDefault` and `stopPropagation` pervasive through these components.

The [`onSubmit` changes in this pull request](https://github.com/WordPress/gutenberg/pull/19462/files#diff-b1dcc68a57b0f94413a4e191bc161f8dL49-R58) have no effect because, as best I can tell, the `onSubmit` would never be called. From what I can observe, I believe this is because, when <kbd>Enter</kbd> is pressed, it actually calls the `onClick` of the `type="submit"` button (TIL!), where with these new changes, [the default behavior of the event is prevented](https://github.com/WordPress/gutenberg/blob/2d1add52ec4f179b5e2fca0814a48c255f84da2b/packages/block-editor/src/components/link-control/index.js#L167), and the submit handler is aborted.

If I had to guess why it's failing intermittently, it's because [only under certain conditions](https://github.com/WordPress/gutenberg/blob/2d1add52ec4f179b5e2fca0814a48c255f84da2b/packages/block-editor/src/components/url-input/index.js#L143-L224) (when suggestion is loaded and ready) will the <kbd>Enter</kbd> evaluate the link as entered in the input (race condition with `fetchLinkSuggestions`). It might be something which could be fixed by the [suggested changes in #19490](https://github.com/WordPress/gutenberg/pull/19490/files#diff-7f80e90a821240f277aae4a7d2d9e778R186-R190) (cc @jorgefilipecosta). I guess it may be [using an outdated `suggestion`](https://github.com/WordPress/gutenberg/blob/2d1add52ec4f179b5e2fca0814a48c255f84da2b/packages/block-editor/src/components/link-control/index.js#L169)?

It still leaves the question of what to do about `onSubmit`, which appears to be dead code currently. Personally, I'd love to see `preventDefault` and `stopPropagation` removed as much as possible, for reason of the exact sort of bugginess we're dealing with right now.

**Comment by aduth** [comment]
Working through some changes related to https://github.com/WordPress/gutenberg/pull/19462#issuecomment-573749427 , I notice an issue which doesn't appear to be present in `master` (for the Navigation block's use of `LinkControl`):

1. Select some text in a paragraph
2. Click to add link
3. Enter a URL (e.g. "http://example.com")
4. Press <kbd>ArrowDown</kbd> to select the suggestion
5. Press <kbd>Enter</kbd>

Expected: Link is applied and link editor is closed
Actual: Link is applied, but link editor remains open, and shifts to the top-left corner

image

**Comment by aduth** [comment]
Another odd one:

1. Add a link to a paragraph
2. Select the link
3. Press the "Edit" button
4. Press <kbd>ArrowDown</kbd>

Expected: Arrow keys should only trigger default behaviors of an input, i.e. text caret would move to the end of the input (where it already is)
Actual: The post title is selected

title

**Comment by aduth** [comment]
> @aduth yes, that's the root issue we should normalize these link components. My thinking is that we should use LinkControl for everything and provide a deprecation strategy for the others. We're not there yet though.

Not directed at you specifically, but: I would still like to know what these components are meant to represent. Are they different? How are they different? Or are they meant to serve the same purpose? And if so, why can't we just improve `URLInput` ?

**Comment by aduth** [comment]
Regression: Tabbing is no longer constrained within the popover as of this pull request.

File: packages/block-editor/src/components/link-control/search-input.js [hunk 11]
```diff
@@ -70,14 +73,24 @@ const LinkControlSearchInput = ( {
...
-				onClick={ onReset }
-			/>
+			<div className="block-editor-link-control__search-actions">
+				<Button
+					disabled={ ! value.length }
+					type="submit"
+					label={ __( 'Submit' ) }
+					icon="editor-break"
+					className="block-editor-link-control__search-submit"
+				/>
```
Comment (aduth) [inline packages/block-editor/src/components/link-control/search-input.js]: I'm guessing the position of the loading indicator is hard-coded, but now that we're adding an extra submit button here, there's an overlap which occurs when fetching the link suggestions.

loading-indicator

File: packages/block-editor/src/components/link-control/search-input.js [hunk 12]
```diff
@@ -46,13 +46,16 @@ const LinkControlSearchInput = ( {
 		}
```
Comment (aduth) [inline packages/block-editor/src/components/link-control/search-input.js]: It wasn't implemented here, but it's especially noticeable in reusing this for paragraph links: `selectItemHandler`'s treatment of `suggestion` doesn't really conform to the intended semantics of `URLInput`.

In this implementation: If a `suggestion` is provided as an argument to `selectItemHandler`, it's assumed to be the intended final result to be applied as the link, that the popover should be closed, and the transaction be considered "completed".

In the previous implementation: The closing of the popover is separate from the link selection.

Consider tabbing (related to https://github.com/WordPress/gutenberg/pull/19462#issuecomment-573828833). In the `master` branch, if I press <kbd>Tab</kbd> after having used arrow keys to find a suggestion, the link is "selected", but the tab proceeds to navigate through items in the popover, not close the popover.

tabbing

But in this branch: When I press <kbd>Tab</kbd> after having selected a suggestion using arrow keys, the popover will close prematurely. That's because [the handling of <kbd>Tab</kbd>](https://github.com/WordPress/gutenberg/blob/4aad528337cff1bf7a20168fb442de613c9ea1e0/packages/block-editor/src/components/url-input/index.js#L208-L215) considers it as having made a selection.

tabbing-2


I guess this is why the `<form onSubmit>` handling was implemented separate from `URLInput`, since we want the <kbd>Enter</kbd> press to be considered as both a selection (via `URLInput`) and as a completion of the transaction (from this component).

File: packages/format-library/src/link/inline.js [hunk 13]
```diff
@@ -56,181 +64,55 @@ const URLPopoverAtLink = ( { isActive, addingLink, value, ...props } ) => {
...
-		this.resetState();
-
-		if ( ! isValidHref( url ) ) {
+		if ( ! isValidHref( newUrl ) ) {
 			speak( __( 'Warning: the link has been inserted but may have errors. Please test it.' ), 'assertive' );
 		} else if ( isActive ) {
 			speak( __( 'Link edited.' ), 'assertive' );
 		} else {
 			speak( __( 'Link inserted.' ), 'assertive' );
 		}
```
Comment (aduth) [inline packages/format-library/src/link/inline.js]: Not sure if you have any thoughts on: What generalized behaviors can we extract around communicating link selection to the user.

There are a few issues I see with how this is currently implemented:

- The handling is split, where [`URLInput` will announce](https://github.com/WordPress/gutenberg/blob/adf6735f85858eb83e56bdcb7d21c25c6eee9742/packages/block-editor/src/components/url-input/index.js#L211-L212) when a suggestion link is "selected" using the <kbd>Tab</kbd> key, but then the application of that link is implemented in the submission handler
- Problem: If `URLInput` is supposed to behave like a raw input field, what should happen when <kbd>Enter</kbd> is pressed and there is no submission handler (i.e. a default/fallback behavior)?
- Case in point: There is no handler that communicates selection in either the Navigation block or Buttons block link editors. Therefore, the user is not informed when a selection is made.

It's difficult, because I think the message might need to change depending on where it's used (like here, "Link inserted" based on the changes applied in the paragraph).

A possible compromise solution:

- Always announce "Link selected" in URLInput for _both_ <kbd>Tab</kbd> and <kbd>Enter</kbd> handling
- Either:
   a. If that's sufficient information to indicate that a link can be assumed to have been applied, then remove this custom handling. I don't really think we want to make this assumption, considering that there are many other ways that a link can be applied (_clicking a suggestion_, tabbing to the "Submit" button and pressing Enter, etc).
   b. Otherwise, be more consistent in how we implement spoken messages for communicating how those selections are used. In other words, implement `speak` in the Navigation/Button blocks' [`onChange` handling](https://github.com/WordPress/gutenberg/blob/adf6735f85858eb83e56bdcb7d21c25c6eee9742/packages/block-library/src/navigation-link/edit.js#L170-L179) (or `onClose` ? Not sure when it should be considered as "persisted").

It might risk over-communicating though, since in many cases it would announce two messages of "Link selected", "Link inserted" when pressing <kbd>Enter</kbd>.

Related: https://github.com/WordPress/gutenberg/pull/10838#issuecomment-573774362

**Comment by draganescu** [comment]
Hi @youknowriad @aduth since you're both refactoring the `LinkControl` I wanted to ask about this #19504  In this PR `MediaReplaceControl` should show the URL of the media and allow user to edit them, obviously with no suggestions.

I accomplished that using `LinkEditor` and `LinkViewer` from the `URLInput`  component, but to a mediocre visual outcome. What @shaunandrews suggests looks very much like what `LinkControl` offers, but this component does not expose it's `LinkEditor` and `LinkViewer` parts.

How do you advise I should continue there:

- make something specific to `MediaReplaceControl`
- visually update `LinkEditor` and `LinkViewer` from the `URLInput` 
- try to expose some `LinkEditor` and `LinkViewer` from `LinkControl`
- some other way?

Thank you very much >o.o<

**Comment by youknowriad** [comment]
@draganescu wouldn't LinkControl work as is if we had a prop to disable suggestions?

**Comment by draganescu** [comment]
@youknowriad no, and plus, using `LinkControl` gives me the whole UI with the `Popover`, that's what it renders by default, you cannot use `LinkControl` without `Popover`

**Comment by youknowriad** [comment]
@draganescu see here about the Popover https://github.com/WordPress/gutenberg/pull/19462#discussion_r363775398 (we're planning to remove it)

File: packages/block-editor/src/components/link-control/search-input.js (hunk 11 above)
Comment (draganescu) [reply packages/block-editor/src/components/link-control/search-input.js]: @karmatosed noticed this as well and there is an issue for it #19544

Comment (getdave) [reply packages/block-editor/src/components/link-control/search-input.js]: This was my bad. Apologies!

File: packages/block-editor/src/components/link-control/index.js (hunk 7 above)
Comment (aduth) [reply packages/block-editor/src/components/link-control/index.js]: This is a cause of some confusion.

The documentation refers to this as an "item", and the example includes some reference to an `id` property:


https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/link-control/README.md#onchange

Presumably, this is referring to some post object, like in the underlying URLInput `onChange` second argumnet:

https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/url-input#onchange-url-string-post-object--function

However: Even for `URLInput`, this value is acknowledged to be _null unless the user selects a post_. So, what should the value be for when a user chooses to enter a raw URL? An `id` won't exist, because there's no post associated with this URL.

@youknowriad , based on your comment, we could choose to make some custom shape which is an amalgamation of a post and various other link-specific values (`opensInNewTab` appears to be one).

>right now: url, title, openInNewTab but it supports custom settings adding custom properties there.

On this line of thinking, we should:

- Be very specific with what these are (I think the set you mention is agreeable)
- Explicitly _omit_ any other property values. Right now, we're [spreading post properties](https://github.com/WordPress/gutenberg/blob/b55605e32180b874ef34afa86f830fe0fa1bef7f/packages/block-editor/src/components/link-control/index.js#L166) into the changed value. I don't think we should want to set any expectation that these values will be available, as otherwise it becomes very error-prone when the user enters a custom URL which is not associated with a post.
- Fix any inaccuracies (i.e. remove the reference to `item.id` in the current documentation)

Comment (youknowriad) [reply packages/block-editor/src/components/link-control/index.js]: @aduth This makes a lot of sense to me, I wasn't aware that we had these extra properties added there as well.

File: packages/e2e-tests/specs/editor/blocks/__snapshots__/buttons.test.js.snap (hunk 8 above)
Comment (aduth) [reply packages/e2e-tests/specs/editor/blocks/__snapshots__/buttons.test.js.snap]: Noted also at https://github.com/WordPress/gutenberg/pull/19490#discussion_r366558464, but:

- An empty `title` is not useful here. In fact, depending on how it's interpreted, it could be actively harmful in stripping "WordPress" text as being the link's informative description.
- To that end: I'm not sure we really want to be messing with `title` at all. There are many resources which reinforce that `title` should _never_ be used on a link [[1]](https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute) [[2]](https://silktide.com/blog/2013/i-thought-title-text-improved-accessibility-i-was-wrong) [[3]](https://developer.paciellogroup.com/blog/2012/01/html5-accessibility-chops-title-attribute-use-and-abuse/) [[4]](https://www.24a11y.com/2017/the-trials-and-tribulations-of-the-title-attribute/) [[5]](https://a11yproject.com/posts/title-attributes/)
- Concerning the discussion at https://github.com/WordPress/gutenberg/pull/19462#discussion_r365204493 , we might thus want to not include `title` in the value object. Combine this with the fact that `opensInNewTab` is not always relevant for `value` (because it is only used when `settings` is the default), it really makes me wonder whether we should be representing a `value` as an object vs. as a string URL , and the settings values be managed separately (`onSettingsChange`?)

Comment (aduth) [reply packages/e2e-tests/specs/editor/blocks/__snapshots__/buttons.test.js.snap]: > * To that end: I'm not sure we really want to be messing with `title` at all. There are many resources which reinforce that `title` should _never_ be used on a link [[1]](https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute) [[2]](https://silktide.com/blog/2013/i-thought-title-text-improved-accessibility-i-was-wrong) [[3]](https://developer.paciellogroup.com/blog/2012/01/html5-accessibility-chops-title-attribute-use-and-abuse/) [[4]](https://www.24a11y.com/2017/the-trials-and-tribulations-of-the-title-attribute/) [[5]](https://a11yproject.com/posts/title-attributes/)

Also: https://core.trac.wordpress.org/ticket/24766

Comment (youknowriad) [reply packages/e2e-tests/specs/editor/blocks/__snapshots__/buttons.test.js.snap]: in advanced situations in the Navigation block (and maybe others), we'll want to differentiate between relative links (post ids, category ids...) and absolute links using the same component. In that case, I believe an object is better to differentiate the different types of links.

Comment (aduth) [reply packages/e2e-tests/specs/editor/blocks/__snapshots__/buttons.test.js.snap]: > in advanced situations in the Navigation block (and maybe others), we'll want to differentiate between relative links (post ids, category ids...) and absolute links using the same component. In that case, I believe an object is better to differentiate the different types of links.

Yeah, I can see this. I think the challenge here is in how we represent this, and if that's part of the `value` shape, how it's done in a way which is consistent and well-understood and also accommodates links which _aren't_ associated with known resources.

This ties in to the discussion at https://github.com/WordPress/gutenberg/pull/19462#discussion_r365204493 , but I don't think we had a complete understanding of the intended shape there, since I see [many references in code which seem to try to coerce everything into a post-like entity](https://github.com/WordPress/gutenberg/blob/b5c9419ed839a5f6735d65f35ab08d14ec933977/packages/block-editor/src/components/link-control/index.js#L96-L101).

It's taken me a while to get to this point, but I think I finally understand that this is inheriting from the [REST API search endpoint](https://github.com/WordPress/WordPress/blob/57fbd3c847c2499f6795e039d2be77c6ff5e323b/wp-includes/rest-api/endpoints/class-wp-rest-search-controller.php#L19-L42). I'm still trying to sort through some of the history there ([Trac#39965](https://core.trac.wordpress.org/ticket/39965)) because it seems to try to be generalized in a way which doesn't necessarily assume that these should be implied to always be _WordPress post entities_, which would certainly be helpful to support the "raw URL" usage.

With that in mind, maybe it's fine that the value contain all these fields. Merging them with the settings value gets a little more muddy, but I can see the value in convenience. I just wish we could define this in a way which is much more explicit (and consistent!) about what the consumer should be expecting to be available.

To the specific point about using `title` attributes, maybe it's not the problem that the search result includes a `title` property (I could see how it would be valuable to know the title of a resource associated with a search result), but more in how we use that property value to generate markup.

**Comment by getdave** [comment]
> I'm glad someone decided to [include a README file for `LinkControl`](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/link-control/README.md), but it must assume some prior knowledge of how it's expected to be used, because it doesn't provide any context for why it exists.

That was me. Shall I re-write the README with all the context?

**Comment by aduth** [comment]
> > I'm glad someone decided to [include a README file for `LinkControl`](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/link-control/README.md), but it must assume some prior knowledge of how it's expected to be used, because it doesn't provide any context for why it exists.
> 
> That was me. Shall I re-write the README with all the context?

First, re-reading my original comment, it was a bit snarkier than it should have been, so apologies for that.

To your question: I think it's something we should want to improve, yes. It's still unclear to me whether there are any blocking changes we'd first need to work through if some of the specifics are still unsettled.

For me, looking at something like:

image

Interpretation: I can see it expects an object, but I've no sense what that object should contain. This introduces a challenge not only for someone who'd seek to implement a `LinkControl`, but also for future maintainers of the component itself in understanding the guarantees which are expected to be upheld.

Or:

image

Interpretation: What's an "item", and does it relate to `value`? From the example, I see this `item` has a property `id`. Is it a post entity? (spoiler: it's not, or at least not really) When should I expect `null`, as the documentation hints? (spoiler: We don't actually ever pass `null`, some implementations of this assume it [could be `undefined`](https://github.com/WordPress/gutenberg/blob/c4b2590409c60aedd32bff1b280ce87af91f25c7/packages/block-library/src/navigation-link/edit.js#L177), but in fact the current implementation is such that we never pass either: it will always be an object).

I think this is something where JSDoc and associated types-checking (#18838) can help. I spent a good part of yesterday implementing these, and it definitely helped to highlight and clarify some of my own uncertainties, resolve some inconsistencies in the code, and generally toward improving the documentation (if even just adapting the JSDoc descriptions verbatim into the README file).

**Comment by getdave** [comment]
Ok thanks @aduth. No worries about the tone - I assumed good intent, but I appreciate the clarification 😄 

I've started on a PR to improve the docs here https://github.com/WordPress/gutenberg/pull/19677. I shall try and include your requested changes.

File: packages/block-editor/src/components/link-control/index.js [hunk 14]
```diff
@@ -43,16 +43,18 @@ const MODE_EDIT = 'edit';
...
 	settings,
 	fetchSearchSuggestions,
 	instanceId,
 	onClose = noop,
 	onChange = noop,
+	popoverProps,
 } ) {
 	// State
 	const [ inputValue, setInputValue ] = useState( '' );
 	const [ isEditingLink, setIsEditingLink ] = useState( ! value || ! value.url );
```
Comment (aduth) [inline packages/block-editor/src/components/link-control/index.js]: `! value` would now never happen as a result of the change in component signature to provide a default empty object value.

```suggestion
	const [ isEditingLink, setIsEditingLink ] = useState( ! value.url );
```

But what was the motivation behind making the change to provide a default value? Was it for convenience of direct property access on `value`?

Comment (aduth) [reply packages/block-editor/src/components/link-control/index.js]: `value` is documented as being required, so I wonder why we need existence checks at all.

https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/link-control/README.md#value

Comment (youknowriad) [reply packages/block-editor/src/components/link-control/index.js]: > But what was the motivation behind making the change to provide a default value? Was it for convenience of direct property access on value?

I think the motivation was failing tests after the refactor. It was a temporary change, I think we can remove the default value and fix the unit tests by providing a value everywhere.

Comment (youknowriad) [reply packages/block-editor/src/components/link-control/index.js]: The reason this check exists in this line is different though. Basically we're saying if you're adding a new value, (empty url), the control should be in "edit mode" on mount.

Comment (aduth) [reply packages/block-editor/src/components/link-control/index.js]: > The reason this check exists in this line is different though. Basically we're saying if you're adding a new value, (empty url), the control should be in "edit mode" on mount.

Oh, that's fine, I'm not concerned with the state or how it's initialized. I'm more concerned with the specific types we're anticipating for `value`.

Comment (aduth) [reply packages/block-editor/src/components/link-control/index.js]: > > But what was the motivation behind making the change to provide a default value? Was it for convenience of direct property access on value?
> 
> I think the motivation was failing tests after the refactor. It was a temporary change, I think we can remove the default value and fix the unit tests by providing a value everywhere.

Initially I was inclined to agree with this, and it was my first thought as well. But as I started to implement it, I have some concern about its impact on usability.

Does it make the component less usable if I (as a consumer) am forced to construct this value object? What _is_ an initial value? Is an empty object sufficient? How am I supposed to know that?

Contrast this with the experience of any other input, which it's typically fairly straight-forward to initialize it as an undefined state and feed the `onChange` directly back into the state setter.

```jsx
const [ value, setValue ] = useState();
return <SomeInputControl value={ value } onChange={ setValue } />
```

So having a default might improve usability. I'm not sure yet if the internal implementation of the component should apply that default in the props signature, or if it might be useful to consider it before accessing any properties (to force awareness of that value shape, or allow distinct behavior depending on whether it's unset).

File: packages/block-editor/src/components/link-control/index.js (hunk 1 above)
Comment (aduth) [reply packages/block-editor/src/components/link-control/index.js]: > I don't think we have a "title" for the link in the case of the format link. So LinkControl should handle properly the case where there's no title.

I pulled this revision out as a separate pull request: #19739

File: packages/format-library/src/link/inline.js (hunk 4 above)
Comment (aduth) [reply packages/format-library/src/link/inline.js]: > I noticed in e2e tests that there's an expectation that the focus move back to the Popover if we hit "ctrl+k" on an existing link. This is a hack that does that (a similar more implicit hack was used before)

There might be another option here, based on the fact that the issue occurs because the popover is shown both when the caret is within a link (`isActive`) and when adding/editing a link (`addingLink`). We want to shift focus into the popover when editing the link, but not when we simply select it (click on it, or use arrow keys to change selection into it).

So ultimately it seems a question of: When the Popover's `focusOnMount` prop [changes from `false` to `'firstElement'`](https://github.com/WordPress/gutenberg/blob/2d1add52ec4f179b5e2fca0814a48c255f84da2b/packages/format-library/src/link/inline.js#L112), should we trigger the focus if the popover is already mounted? That would be enough to resolve the issue, and could be a valid way to control the focus behavior while the popover is already mounted (that's what's happening here). The main concern is... well, the name. It's called `focusOnMount`, so it would be odd if we're enhancing it to support functionality specifically serving the use-case that the popover is already mounted 😅

**Comment by aduth** [comment]
I just force-pushed a rebased branch which should bring this up to date with the current master. There have been _many_ changes to the affected components here, notably `LinkControl`. I expect there could still be many more of the remaining changes which could make sense in their own pull requests, but I'm also conscious with the looming WordPress 5.4 feature deadline to try to get _something_ in place for the base consistent link editing changes we're wanting to introduce with the new `LinkControl` component.

There's at least one remaining end-to-end test which is a legitimate, reproducible failure (links "should contain a label when it should open in a new tab"). I haven't quite figured out what's going wrong here. It could be related to circumstances where the caret selection is just within the inline boundary of a link.

There's also a few rough edges which could be nice to improve, though I don't necessarily see as blocking:

- The loading indicator overlaps with the new "Submit" button.
- The popover width will adjust based on the input value (it could also be related to the addition of the "Submit" button).
- Questioning whether we even want the "Submit" button (I'm unsure if its original purpose is still valid).
- The Popover animations are a bit too frequent and excessive, related to discussion at https://github.com/WordPress/gutenberg/pull/19462#discussion_r365176357 due to Popover mounting behavior.
- I have seen at least one occurrence of the Popover floating away, though I haven't been able to reproduce it reliably, and I know there have been some issues with this on `master`, so it's unclear whether it's caused by this pull request.

File: packages/format-library/src/link/inline.js (hunk 4 above)
Comment (aduth) [reply packages/format-library/src/link/inline.js]: A compromise solution might be to manually shift focus back into one of the popover elements when starting to edit the link. I could see this being something where:

- Either `Popover` or `LinkControl` offer a `focus` method. React's [documented `useImperativeHandle` example](https://reactjs.org/docs/hooks-reference.html#useimperativehandle) is exactly what we'd want in this case.
- Or, the `InlineLinkUI` renders its own `ref`-referenced DOM wrapper to `LinkControl`, then tries to [find a focusable target](https://github.com/WordPress/gutenberg/blob/master/packages/dom/src/focusable.js) within the container to shift focus.

Comment (youknowriad) [reply packages/format-library/src/link/inline.js]: Reading this, It doesn't seem like there's a perfect solution. I might think a `focus` method is maybe the most explicit and understandable solution. What do you think?

**Comment by shaunandrews** [comment]
image

image


Here's another case where the submit button gets in the way — when you edit a link, the URL can easily be very long, and overlaps with the submit button.

File: packages/format-library/src/link/inline.js (hunk 4 above)
Comment (aduth) [reply packages/format-library/src/link/inline.js]: I'm thinking the simplest "non-decision" option would just be to add a `div` wrapper within the popover content, wrapping `LinkControl`, then call `wp.dom.focus.focusable.find`. Seems like that would be pretty straight forward.

The main downsides might be:

- It may be a common pattern for this sort of use of LinkControl in Popover
   - If it becomes a worry, we could consider again some abstraction like URLPopover
- It duplicates a behavior inherent to Popover

Neither are really overly concerning to me. Maybe it could make sense to expose a `focus` from Popover at some point, if it's a common need. It could even be reused internally for the component's own `focusOnMount` behavior. I don't think we need to commit to that API now though. Similarly, creating a `ref` behavior with `LinkControl` isn't something I'd want to do without considering how to make this consistent with other `*Control` components.

File: packages/e2e-tests/specs/editor/various/links.test.js [hunk 15]
```diff
@@ -335,16 +333,21 @@ describe( 'Links', () => {
...
-		expect( await page.$( '.block-editor-url-popover' ) ).not.toBeNull();
+		expect( await page.$( '.components-popover__content .block-editor-link-control' ) ).not.toBeNull();
 
 		// Press Cmd+K to edit the link and the url-input should become
 		// focused with the value previously inserted.
 		await pressKeyWithModifier( 'primary', 'K' );
+		await page.waitForSelector( '.components-popover__content .block-editor-link-control' );
+		// Click on the Edit button
+		const [ editButton ] = await page.$x( '//button[text()="Edit"]' );
+		await editButton.click();
```
Comment (aduth) [inline packages/e2e-tests/specs/editor/various/links.test.js]: Do we want to make this change in behavior?

Notably, before these changes, upon pressing <kbd>Cmd+K</kbd>, the user would be able to edit the link immediately. Now, Cmd+K basically acts as a way to shift focus into the Popover attached to the link in the paragraph, but still in the "view"/"read-only" mode.

Before|After
---|---
cmd-k-before|cmd-k-after

It might be an okay change to make, if at least a conscious one.

I see both pros and cons:

- Con: More steps to get to the point of editing a link by keyboard alone.
- Pro: Avoids needing to create a way to forcefully control LinkControl's internal state (something like a `forceIsEditing` prop), which itself could lead to more consistency in using this component in general.
- Pro: If one _wanted_ to get to the "view" mode details of a link by keyboard alone, this change would make that workflow easier.

Comment (aduth) [reply packages/e2e-tests/specs/editor/various/links.test.js]: I wasn't aware of this previously, but apparently <kbd>Ctrl+K</kbd> is pretty well-established as being associated with the intention of editing a link. So we probably want to retain the previous behavior.

>control-K is often used to add, edit, or modify a hyperlink to a Web page

https://en.wikipedia.org/wiki/Control-K

The article notes Microsoft Word, and I've also confirmed it works this way in Google Docs.

**Comment by aduth** [comment]
The "Submit" button changes were sort of incidental to the primary goal of this pull request if I understand correctly. And since they were contributing to a number of the "Known issues", I extracted them separately to #19971 for more focused review and discussion.

In the meantime, I think I will plan to rebase to remove that commit from this branch to try to consolidate the changes here.

File: packages/e2e-tests/specs/editor/various/links.test.js (hunk 15 above)
Comment (aduth) [reply packages/e2e-tests/specs/editor/various/links.test.js]: > I wasn't aware of this previously, but apparently Ctrl+K is pretty well-established as being associated with the intention of editing a link. So we probably want to retain the previous behavior.

There's a bit of a conflict here that we need to sort out.

Consider the following:

1. Insert a paragraph with some text
2. Select some or all of that text
3. Press <kbd>Cmd+K</kbd> to start applying a link
4. Input a URL and press <kbd>Enter</kbd>

Where should focus be at this point?

In the current plugin, the focus is moved back to the paragraph, so you can proceed to continue editing the text of the paragraph. I've observed this behavior in Google Docs as well.

But there's a problem with this for the new link editing experience, which is: How do I toggle "Open in New Tab" if I'm only using the keyboard? The only way for me to shift focus into the link popover is using <kbd>Cmd+K</kbd>, but this immediately puts me into editing the URL, and there's no way for me to access the "Open in New Tab" toggle, because we (no longer) show the toggle when editing the URL. 

The options I might consider are:

- <kbd>Cmd+K</kbd> should just shift focus into the Popover. This breaks some widespread conventions / expectations around how <kbd>Cmd+K</kbd> tends to work, based on my [earlier comment](https://github.com/WordPress/gutenberg/pull/19462#discussion_r373156209).
- Or: Pressing <kbd>Enter</kbd> when editing a link should keep focus within the Popover. This could work, but it could slow the workflow for those who might expect to be able to proceed with their writing immediately upon pressing <kbd>Enter</kbd> (I would expect pressing <kbd>Escape</kbd> at this point would be enough to put the caret back into the paragraph). There's also a technical challenge here, in that the formatting implementation seems to become confused when focus stays within the popover after the new link is applied.
- Or: <kbd>Cmd+K</kbd> can continue to immediately start editing the link, and <kbd>Enter</kbd> once finished editing a link will still shift focus back to the paragraph, but then we also add an additional way to be able to navigate into the Popover from an active link without triggering it as an edit.

I was curious how Google Docs handles this, since they have a similar "popup", their behavior of <kbd>Cmd+K</kbd> is to immediately edit the URL, and their behavior of <kbd>Enter</kbd> once finished editing a URL is to shift focus back into the paragraph:

g-docs-cmd-k

I'm actually not sure how one would be expected to access those "Copy Link" and "Remove Link" buttons in the popup using only keyboard:

image

There's a Keyboard Shortcuts panel accessible pressing <kbd>Cmd+?</kbd>, and it includes an entry for "Move focus to popup", but the key combination does not appear to work for these link popups.

image

Maybe it's assumed since there are other means to Remove or Copy a link in Google Docs, it's not necessary to have these buttons be accessible via keyboard. In our case, we're not able to make the same compromise, because there's no other way to toggle "Opens in New Tab".

**Comment by aduth** [comment]
I've rebased and pushed another set of changes which I think should put this in an acceptable state. As far as I can tell, all tests should pass now.

The "Submit" button changes were removed from the branch and proposed for separate discussion at #19971. 

I still have some uncertainty around the specific behaviors of <kbd>Cmd+K</kbd> and where focus should land after pressing <kbd>Enter</kbd> to finish editing a link. With the current set of changes, <kbd>Cmd+K</kbd> will shift focus into the popover, but the user will still need to click the "Edit" button to start modifying the link. Pressing <kbd>Enter</kbd> will shift focus back to the link in the paragraph so the user can continue typing. This aligns with the current behavior of the Navigation Link block, and ensures that the "Open in New Tab" toggle is still accessible by keyboard. Separately, we may still want to explore some of the alternative options discussed at https://github.com/WordPress/gutenberg/pull/19462#discussion_r373694597.

The use of `key` in forcing a remounting Popover is another thing I would like to improve upon separately. I mentioned some ideas for this at https://github.com/WordPress/gutenberg/pull/19462#discussion_r365176357. Implementing these did not have much help on the excessive animations of the popover, and it seems it might be an underlying issue with Popover (it's similarly problematic on master).

File: packages/e2e-tests/specs/editor/various/links.test.js (hunk 15 above)
Comment (youknowriad) [reply packages/e2e-tests/specs/editor/various/links.test.js]: I don't feel like I'm capable of choosing which behavior makes the most sense. 

My cartesian logic (and technical one probably) prefers that this popover behaves like any other popover which is:

 - Ctrl + k or click to open popover in its initial state (input for new links, view for edited links)
 - Enter in the input mode keeps focus in the popover
 - Escape moves focus back to the paragraph

I believe this behavior is also good a11y wise but I understand that this could be confusing.

Any thoughts here @jasmussen @karmatosed

Comment (jasmussen) [reply packages/e2e-tests/specs/editor/various/links.test.js]: Excellent conversation here. I would love input from skilled keyboard users on what is the most intuitive and elegant here. @MarcoZehe if you have time, perhaps? Your input would be valuable.

Google Docs and the popover that appears when you select a link does not seem like the best pattern to emulate as, and Andrew touches on this, focus remains in text, which means that pressing "tab" inserts a tab in the text.

However both the classic editor, and the specific ⌘K dialog in Google Docs, both seem like they could provide a pattern to follow here as well. In my reading, if focus is in an input field, pressing Enter closes the dialog and brings focus back to text. If focus is on a button, it toggles that button. With that heuristic, the following could work:

- Select text, press ⌘K, paste URL, press Enter and you're back in text.
- Select text, press ⌘K, paster URL, press Tab to set focus on the advanced dropdown. Press enter to open it. Press tab to set focus on "Open in new window". Press shift tab to go back to the Submit button, press Enter and you're back in text. 

To my understanding, this is also the behavior of the classic editor:

classic

It's entirely possible I'm missing some context from the new link dialog, but if not, does the above heuristic make sense?

Comment (youknowriad) [reply packages/e2e-tests/specs/editor/various/links.test.js]: > Select text, press ⌘K, paster URL, press Tab to set focus on the advanced dropdown. Press enter to open it. Press tab to set focus on "Open in new window". Press shift tab to go back to the Submit button, press Enter and you're back in text.

The problem is that this behavior won't work here do the design of the new LinkControl component. The component is now a "two steps" popover, you enter the link, once you submit it, you choose other options (new tab...).

This new component can be used today in the navigation and buttons block.

Comment (jasmussen) [reply packages/e2e-tests/specs/editor/various/links.test.js]: I see it now. Took it for a spin:

new behavior

To me this suggests the primary challenge is: how do you enter the popover that appears when the link has been created? Strawman suggestion: why doesn't Tab enter that dialog? Since it doesn't add tabs in the text, it might as well tab into that dialog.

Comment (MarcoZehe) [reply packages/e2e-tests/specs/editor/various/links.test.js]: Keyboard focus can only be in one place at a time, and tab should always act predictably. Besides, why that extra step if I don't even want to set extra options? That sounds to me like an anti-pattern. So, I want to select text, press CTRL+K or CMD+K, paste the URL, enter to submit, or tab to the submit button and hit Enter or Space, and be back in the text to continue working. Shoving another dialog in my face to set options I might not even need would annoy me big times as a user, and also confuse me. That previous Link dialog that's also in the Classic editor where I can expand the advanced options if I need to, worked fine. If it must be a separate popover, make it a button in the main popover that opens this secondary one, and then submits the link with these set options once I okay/submit that secondary popover. Otherwise, keep the interaction as simple and straight-forward as possible.

**Comment by aduth** [comment]
I'll plan to follow-up by creating discrete tasks out of the improvements I've mentioned in previous comments, but I would like to have this one included as part of this week's plugin release, ahead of next week's WordPress 5.4 feature freeze. Noting that there is another plugin release planned for next week as well, to include improvements.

**Comment by youknowriad** [comment]
Thanks Andrew for the great work here.

File: packages/e2e-tests/specs/editor/various/links.test.js (hunk 15 above)
Comment (aduth) [reply packages/e2e-tests/specs/editor/various/links.test.js]: I admit I totally missed the replies here before merging (GitHub threads can be hard to follow, especially for such a large pull request). Trying to follow the conversation as it's evolved here, I want to make sure that nothing is lost for consideration and that we don't regress behaviors. I'm also conscious that this link experience is being proposed to support more advanced use cases of the Navigation Link and Buttons blocks, and brought to the paragraph to ensure a consistent experience for editing links.

From what I'm gathering in this discussion, one thing that seems important is to restore the workflow that <kbd>Cmd+k</kbd> immediately puts the user into editing a link, and ideally to treat "Opens in New Tab" as part of a set of advanced options. I think it might require something of a rethink for how we present the link preview when the current selection is within a link. With the discussion here, it feels that it might be problematic to include the "Open in New Tab" as part of this preview, when it's more of an advanced editing feature.

I will make sure to follow up with relevant tasks and/or pull requests.

Comment (aduth) [reply packages/e2e-tests/specs/editor/various/links.test.js]: To clarify how the current behavior will be after merging this pull request:

1. Select some text
2. Press <kbd>Cmd+K</kbd>
3. Now focus is inside the popover in its preview state. From here, the user can tab to the "Edit" button or to the "Open in New Tab" button
4. After clicking "Edit", the user can change the URL
5. Pressing <kbd>Enter</kbd> to submit the changes will place focus back in the paragraph

To me, it seems the most problematic of these is the 3rd step, where pressing <kbd>Cmd+K</kbd> will shift focus into the preview popover, but there's still another step required before the user is able to edit the link. This was necessary, however, since in the current implementation of this link component, it's the only place where "Open in New Tab" can be toggled, and otherwise the option would not be reachable by keyboard. The alternative where focus remains in the popup after pressing <kbd>Enter</kbd> seems that it would be equally problematic. 

It appears the problem may be more about where the "Open in New Tab" toggle is placed. If it's something we think should be part of the link editing workflow (optionally as an advanced step), then I don't think it makes sense that it's shown as part of this preview state. Pressing <kbd>Cmd+K</kbd> should allow me to immediately edit a link, and I should still be able to toggle the option to "Open in New Tab" without also breaking my expectation that submitting my changes by pressing <kbd>Enter</kbd> would put the focus back in the paragraph.

This is my understanding of the problem, but I would appreciate any thoughts or corrections. I would also require some design help to accommodate this change.

Comment (jeryj) [reply packages/e2e-tests/specs/editor/various/links.test.js]: Thanks for all your careful consideration here, @aduth. I agree with @MarcoZehe about keeping the flow as simple as possible while allowing for access to the advanced options if necessary.

Comment (aduth) [reply packages/e2e-tests/specs/editor/various/links.test.js]: To make sure this is tracked, I created an issue at #20007 to follow up on work related to this discussion.
