### PR TITLE
Reusable blocks: Use view context, always include title.raw and content.raw

### LINKED ISSUE #11343: Fetch reusable blocks in the view context on first render.
**Describe the bug**
When inserting, the editor fetches reusable blocks in via the API in the `view` context. This permits authors and contributors to insert blocks created by other users.

On first render, the editor fetches reusable blocks via the REST API in the `edit` context. When an author goes back to edit a post that uses another user's block, the block renders with the error "Block has been deleted or is unavailable"

Originally logged in the discussion of [WP#45098 (comment)](https://core.trac.wordpress.org/ticket/45098#comment:24).

**To Reproduce**
1. Create two users, `user1` (any role) and `user2` (author role)
1. Log in as `user1` and create a reusable block
1. Log in as `user2` and create a post using `user1`'s block
1. The block renders correctly.
1. Save the post and refresh the edit screen.
1. The block fails to render and displays the error "Block has been deleted or is unavailable." The REST API returns a 403 error.

It looks to be happening around these lines but when I change the context to view, the REST API returns a 200 but the blocks still fail to render.

https://github.com/WordPress/gutenberg/blob/b7d8fbfd0b97d579f732d9fc8f026e2919c2642d/packages/editor/src/store/effects/reusable-blocks.js#L65-L70

**Expected behavior**
Reusable blocks render in the view context when first loading the edit screen.

**Screenshots**
Screencast of author creating a post that re-uses a block created by an admin. **This is recorded against WordPress 5.0**

author

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 63

### PR DESCRIPTION
**Pull request by noisysocks**
Supersedes https://github.com/WordPress/gutenberg/pull/11891. Fixes #11343.

Existing reusable blocks on a post would not render if the user was an author or a contributor. This happened because requests to fetch a single block or post are blocked when `?context=edit` is passed and the current user is not an editor.

The fix is to stop passing `?context=edit` to block requests, but this causes another problem which is that Gutenberg needs access to both `title.raw` and `content.raw` in the API response.

We therefore both stop passing `?context=edit` to block requests *and* modify the blocks API so that `title.raw` and `content.raw` are always provided.

#### How to test

1. Create two users, `user1` (any role) and `user2` (author role)
1. Log in as `user1` and create a reusable block
1. Log in as `user2` and create a post using `user1`'s block
1. The block should render correctly.
1. Save the post and refresh the edit screen.
1. The block should again render correctly.

### CODE REVIEW

**Comment by noisysocks** [comment]
Wasn't able to re-open #11891 so this is a new PR to replace it.

I updated the inline comment to explain how `unset()` achieves what we want, and have tweaked the Reusable Block's description in the sidebar with an aim to better explain that blocks can be seen and used by non-editors:

screen shot 2018-11-20 at 11 45 22

cc. @mtias @pento @peterwilsoncc

**Comment by kadamwhite** [comment]
The restrictions around .raw were implemented for security purposes; it is possible to have content within the raw versions of title and (more commonly) content that would leak potentially sensitive data using this approach. This PR therefore changes the WordPress permissions model.  I understand the constraints of shared blocks which suggest an approach like this but I cannot endorse sidestepping the mindfully-designed permissions checks that restrict these fields.

File: lib/class-wp-rest-blocks-controller.php [hunk 1]
```diff
@@ -33,4 +33,28 @@ public function check_read_permission( $post ) {
...
+	 * Retrieves the block's schema, conforming to JSON Schema.
+	 *
+	 * @since 4.4.0
+	 *
+	 * @return array Item schema data.
+	 */
+	public function get_item_schema() {
+		$schema = parent::get_item_schema();
+
+		// To use a reusable block in the editor, one needs access to its raw markup.
```
Comment (pento) [inline lib/class-wp-rest-blocks-controller.php]: Multiline comments should be in long comment form:

```php
/*
 * foo
 * bar
 */
```

File: phpunit/class-rest-blocks-controller-test.php [hunk 2]
```diff
@@ -176,4 +176,35 @@ public function test_capabilities( $action, $role, $expected_status ) {
 			self::delete_user( $user_id );
 		}
 	}
+
+	/**
+	 * Check that the raw title and content of a block can be accessed by a
+	 * low-privileged role when no `context` param is provided.
+	 */
+	public function test_includes_raw_title_and_content() {
+		$user_id = $this->factory->user->create( array( 'role' => 'author' ) );
```
Comment (pento) [inline phpunit/class-rest-blocks-controller-test.php]: User creation (and deletion at the end of this function) should be in the `::wpSetUpBeforeClass()` and `::wpTearDownAfterClass()` methods.

If the `::assertEquals()` call fails it will throw an exception, causing the test method to exit immediately, so the user wouldn't be properly deleted.

**Review by pento — COMMENTED** [review]
Given that we should really only ever need the `raw` post data, and not the `rendered` post data, I'm inclined to think that we should remove `rendered` from the returned data. This will help to avoid the confusion from an API perspective.

File: lib/class-wp-rest-blocks-controller.php [hunk 3]
```diff
@@ -33,4 +33,28 @@ public function check_read_permission( $post ) {
...
+		// This means that reusable blocks differ from posts in that all contexts can
+		// access the `title.raw` and `content.raw` properties.
+		//
+		// `title.raw` and `content.raw` are stripped out by WP_REST_Posts_Controller
+		// because its schema specifies `'context' => array( 'edit' )`. Here, we use
+		// `unset()` to modify the schema so that the properties do not have this
+		// `context` restriction.
+		unset( $schema['properties']['title']['properties']['raw']['context'] );
```
[the remark this answers is not in the document]
Comment (noisysocks) [reply lib/class-wp-rest-blocks-controller.php]: 👍 makes it a lot easier to understand, too.

File: phpunit/class-rest-blocks-controller-test.php (hunk 2 above)
Comment (noisysocks) [reply phpunit/class-rest-blocks-controller-test.php]: I've moved user deletion to `::wpTearDownAfterClass`. The user we require is different for every test case so I've kept user creation as is.

File: lib/class-wp-rest-blocks-controller.php (hunk 1 above)
Comment (noisysocks) [reply lib/class-wp-rest-blocks-controller.php]: 👍 done.

**Comment by noisysocks** [comment]
> Given that we should really only ever need the raw post data, and not the rendered post data, I'm inclined to think that we should remove rendered from the returned data. This will help to avoid the confusion from an API perspective.

I've made this change and added some comments explaining the rationale.

File: phpunit/class-rest-blocks-controller-test.php (hunk 2 above)
Comment (noisysocks) [reply phpunit/class-rest-blocks-controller-test.php]: Oops, the fake user being different for every test case means we should be deleting it in `::tearDown()`, not `::wpTearDownAfterClass()`. Fixed in f8ebe5f72.

Comment (pento) [reply phpunit/class-rest-blocks-controller-test.php]: It's fine to create a bunch of users in the setup and teardown methods, even when they're only used in one test. Kind of like what we do in [`WP_REST_Themes_Controller_Test`](https://github.com/WordPress/gutenberg/blob/master/phpunit/class-wp-rest-themes-controller-test.php).

It's easier to read if those methods are balanced, too: teardown just undoes whatever setup did.

File: lib/class-wp-rest-blocks-controller.php [hunk 4]
```diff
@@ -33,4 +33,55 @@ public function check_read_permission( $post ) {
...
+	 * @since 4.4.0
+	 *
+	 * @param array  $data    Response data to fiter.
+	 * @param string $context Context defined in the schema.
+	 * @return array Filtered response.
+	 */
+	public function filter_response_by_context( $data, $context ) {
+		$data = parent::filter_response_by_context( $data, $context );
+
+		/**
```
Comment (pento) [inline lib/class-wp-rest-blocks-controller.php]:
```suggestion
		/*
```

🙂

File: lib/class-wp-rest-blocks-controller.php [hunk 5]
```diff
@@ -33,4 +33,55 @@ public function check_read_permission( $post ) {
...
+		 */
+		$schema['properties']['title']['properties']['raw']['context']   = array( 'view', 'edit' );
+		$schema['properties']['content']['properties']['raw']['context'] = array( 'view', 'edit' );
+
+		/*
+		 * Remove `content.rendered` from the schema. It doesn’t make sense for a
+		 * reusable block to have rendered content on its own, since rendering a
+		 * block requires it to be inside a post or a page.
+		 */
+		unset( $schema['properties']['content']['properties']['rendered'] );
```
Comment (pento) [inline lib/class-wp-rest-blocks-controller.php]: Do we need to keep the rendered title?

File: phpunit/class-rest-blocks-controller-test.php (hunk 2 above)
Comment (noisysocks) [reply phpunit/class-rest-blocks-controller-test.php]: 👍 changed in 4394eeb99.

**Comment by noisysocks** [comment]
I removed `title.rendered` in 55c7800ed. It's not very relevant in the case of blocks since we don't ever render a block by itself on the front-end.

**Comment by gziolo** [comment]
What about `contributor` role? I did the following:

1. Create a post as a contributor.
2. Added a paragraph.
3. Saved as a draft.
4. Switched to the admin role.
5. Turned the existing paragraph into a reusable block.
6. Saved updates.
7. Logged into the contributor account.
8. I still can edit my post, but reusable blocks don't load at all.

screen shot 2018-11-20 at 08 03 16

**Comment by gziolo** [comment]
I can confirm it works perfectly fine for the `editor` role.

**Comment by gziolo** [comment]
```<!-- wp:block {"ref":47} /-->

<!-- wp:block /-->```

I turned paragraph block into a reusable one when using admin role. It looks like you can't load existing reusable blocks as a contributor.

**Comment by gziolo** [comment]
I added a fix for the contributor role in b0333f3.

I have no idea whether it is valid or not. @youknowriad I would appreciate your feedback.

**Review by gziolo — APPROVED** [review]
I added the last commit to fix the issue for the contributor role. I would appreciate a sanity check from someone else and we can 🚢 

Let's work on UI improvements in the follow-up PRs.
