### PR TITLE
Show publish panel only in edit mode

### LINKED ISSUE #62702: [WP6.6] Publish Panel: Unexpected Behavior in the Site Editor
### Description

Originally reported on Slack: https://wordpress.slack.com/archives/C02QB2JS7/p1718858165581179

In the editor, you can use the tab key to focus on the "Open publish panel" button that appears in the bottom right. Clicking this button will show the Publish panel.

This is expected behavior in the post editor, but may cause unexpected behavior in the site editor.

This issue does not occur in WP6.5.

### Step-by-step reproduction instructions

- Access the site editor.
- Click the tab key repeatedly to move focus to the "Open puglish panel" button.
- Click that button.
- The Publish panel appears.
- When you hover the mouse over the editor canvas, the Publish panel moves inside the canvas.

The following issue occurs whether the canvas is in view or edit mode.

- Open any template.
- Click the tab key repeatedly to move focus to the "Open puglish panel" button.
- Click that button.
- The Publish panel appears.
- URL is undefined.
- Copy button doesn't work.
- The 'View Template' button doesn't work.
- Clicking the 'Add New Template' button shows an error.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/a2352eb5-ba1e-4699-b1f0-d7e297eeb542

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/62702

>In the editor, you can use the tab key to focus on the "Open publish panel" button that appears in the bottom right. Clicking this button will show the Publish panel.

This PR fixes that by only rendering this when we're in edit mode, which is the default for post editor.

## Testing Instructions
1. In site editor using the `tab` key you shouldn't be able to reproduce this:

https://github.com/WordPress/gutenberg/assets/54422211/a2352eb5-ba1e-4699-b1f0-d7e297eeb542

2. Using `tab` key in post editor should work as before and show the `open publish panel` button.

### CODE REVIEW

File: packages/edit-site/src/components/editor/index.js [hunk 1]
```diff
@@ -207,6 +207,7 @@ export default function EditSiteEditor( { isLoading } ) {
 					extraSidebarPanels={
 						! isEditingPage && <PluginTemplateSettingPanel.Slot />
 					}
+					isEditMode={ isEditMode }
```
Comment (youknowriad) [inline packages/edit-site/src/components/editor/index.js]: Let's avoid this prop please. "edit mode" doesn't really make sense in the editor package.

File: packages/editor/src/components/editor-interface/index.js [hunk 2]
```diff
@@ -212,14 +213,18 @@ export default function EditorInterface( {
...
 			actions={
-				<SavePublishPanels
-					closeEntitiesSavedStates={ closeEntitiesSavedStates }
-					isEntitiesSavedStatesOpen={ entitiesSavedStatesCallback }
-					setEntitiesSavedStatesCallback={
-						setEntitiesSavedStatesCallback
-					}
-					forceIsDirtyPublishPanel={ forceIsDirty }
-				/>
+				isEditMode ? (
```
Comment (youknowriad) [inline packages/editor/src/components/editor-interface/index.js]: This can be replaced with `isPreviewMode`

File: packages/edit-site/src/components/editor/index.js (hunk 1 above)
Comment (ntsekouras) [reply packages/edit-site/src/components/editor/index.js]: Of course. I wasn't aware that we have this info in `isPreviewMode`. Updated.

**Review by youknowriad — APPROVED** [review]

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

Not a blocker, but from what I understand, this PR fixes part of #62702. There is another problem with #62702:

> The following issue occurs whether the canvas is in view or edit mode.
> 
> - Open any template.
> - Click the tab key repeatedly to move focus to the "Open puglish panel" button.
> - Click that button.
> - The Publish panel appears.
> - URL is undefined.
> - Copy button doesn't work.
> - The 'View Template' button doesn't work.
> - Clicking the 'Add New Template' button shows an error.

image
