### PR TITLE
Format Library: Assign Popover anchorRect to update selection position

### LINKED ISSUE #11092: Link popover moves sideways following the caret
**Describe the bug**
The link popover moves horizontally with the caret.

**To Reproduce**
1. Add a link to a paragraph (with some reasonably long text)
2. Use the left and right cursor keys to move the caret within the link text
3. Observe that the popover moves from left to right, following the caret

**Expected behavior**
The popover should be positioned at the middle bottom of the formatted text

**Screenshots**
sideways-move
**Additional context**
- 4.1
- The desired behaviour was discussed on this issue -https://github.com/WordPress/gutenberg/issues/8266#issuecomment-431301854
- Fixing related issue #11091 could help with this (as it would be possible to use the inline boundary to position the popover)

### LINKED ISSUE #14872: Components: URL input popover animates repeatedly on text/selection change
Previously: #13617

**Describe the bug**

When changing the text within a linked segment, or moving the selection caret using arrow keys, the link popover animates repeatedly.

**To reproduce**

1. Navigate to Posts > Add New
2. Click the writing prompt
3. Insert some text
4. Apply a link to said text
5. Select within the linked fragment of text
6. Change the linked text, or simply use arrow keys within to change caret position
7. Note that the popover animates in response to each input

**Expected behavior**

The Popover should only animate once when first shown, not on input.

**Screenshots**

url-animation

**Desktop:**

 - OS: macOS Mojave 10.14.4 (18E226)
 - Browser: Chrome Version 73.0.3683.103 (Official Build) (64-bit)
 - Version: `master` (1df302121f0ab7df8611d01e28ad41db25f40d52)

### PR DESCRIPTION
**Pull request by aduth**
Fixes #14872 
Fixes #11092 
Alternative to #14921
Cherry-picks fc1fec7 from #14851

This pull request seeks to resolve an issue where repeated mounting of the link URLPopover component would cause excessive animations to occur in response to changes of selection or content within the formatted link. In doing so, it updates the behavior of link Popover to anchor to the link element itself, rather than follow the position of the caret.

**Implementation Notes:**

This reimplements the positioning to behave similar to `Autocomplete` in passing `getAnchorRect` to the rendered Popover, computed from the current selection. This replaces use of `PositionedAtSelection`.

#14872 is partly caused by the fact that to update `PositionedAtSelection`, we must assign a new `key` value, which would unmount and remount the component, causing the animation to restart.

It may be simpler to review using GitHub's ["Hide whitespace changes"](https://user-images.githubusercontent.com/1779930/55990506-cf475b80-5c75-11e9-8e8d-7265a8d1fe38.png) diff options, given the changes in `inline.js` are largely indentation changes.

**Testing instructions:**

Repeat Steps to Reproduce from #14872, verifying that the animation only occurs once when within the link formatting.

### CODE REVIEW

**Review by gziolo — DISMISSED** [review]
It doesn't work for me as expected. The popover moves on the screen...:

link-test

macOS, Chrome 73

**Comment by aduth** [comment]
@gziolo Good catch. It's not reliable to continuously update the caret positioning when link interactions (add, edit) will place selection into the editing popover.

@ellatrix I've pushed some updates which converge a bit more with your #14921, but still opts to render `URLPopover` with the `getAnchorRect` than to update `PositionedAtSelection`. It works well, though I did note the one case of pressing ArrowRight into the anchor node, it will not show the popover when first entering. I noticed this is what you'd [accounted for](https://github.com/WordPress/gutenberg/pull/14921/files#diff-b377a4a4d884f4bbccdb926d4283021bR34) with considering `nextElementSibling`, but I was a bit worried about the possibility of elements _within_ the link yielding an unexpected value (the bolded element, for example, instead of the anchor). Although, now that I type this, I guess if it eventually uses `Element#closest( 'a' )` anyways, it would match the anchor node.

File: packages/format-library/src/link/inline.js [hunk 1]
```diff
@@ -91,6 +77,35 @@ const LinkViewerUrl = ( { url } ) => {
...
+		if ( closest ) {
+			return closest.getBoundingClientRect();
+		}
+	}, [ isActive, addingLink, value.start, value.end ] );
+
+	if ( ! anchorRect ) {
+		return null;
+	}
+
+	return <URLPopover getAnchorRect={ () => anchorRect } { ...props } />;
```
Comment (ellatrix) [inline packages/format-library/src/link/inline.js]: I wonder if passing `anchorRect` directly to `URLPopover` could prevent the delays: `Popover` could simply check object equality? The calculation already happened anyway, so the `setInterval` doesn't really make much sense if there's no calculation needed to be done.

**Comment by ellatrix** [comment]
> I noticed this is what you'd [accounted for](https://github.com/WordPress/gutenberg/pull/14921/files#diff-b377a4a4d884f4bbccdb926d4283021bR34) with considering `nextElementSibling`, but I was a bit worried about the possibility of elements _within_ the link yielding an unexpected value (the bolded element, for example, instead of the anchor). Although, now that I type this, I guess if it eventually uses `Element#closest( 'a' )` anyways, it would match the anchor node.

Yes, it's an edge case. I think it could work reliably though, you'd always end up with the right element.

File: packages/format-library/src/link/inline.js (hunk 1 above)
Comment (aduth) [reply packages/format-library/src/link/inline.js]: > I wonder if passing `anchorRect` directly to `URLPopover` could prevent the delays: `Popover` could simply check object equality? The calculation already happened anyway, so the `setInterval` doesn't really make much sense if there's no calculation needed to be done.

Yeah, I think that could work. It would require some updates to the `Popover` component, but they seem relatively small. I'll give it a shot.

File: packages/format-library/src/link/inline.js [hunk 2]
```diff
@@ -221,37 +250,36 @@ class InlineLinkUI extends Component {
 		const showInput = isShowingInput( this.props, this.state );
 
 		return (
-			<PositionedAtSelection
```
Comment (ellatrix) [inline packages/format-library/src/link/inline.js]: Minor thing, but since `PositionedAtSelection` is exposed and will be introduced this WordPress release, could we removed it?

We have one more similar use of it:

https://github.com/WordPress/gutenberg/blob/7964f381e07e06b2ac13698fd1465a4d0c16da1b/packages/format-library/src/image/index.js#L116-L120

So I would either adjust that one too, or temporarily mark the component as unstable.

Comment (ellatrix) [reply packages/format-library/src/link/inline.js]: (If you want I can also take this over.)

Comment (aduth) [reply packages/format-library/src/link/inline.js]: Hm, I thought we'd already been exposing the component, so I didn't think too much about it. I might agree that if we're uncertain about its future, to mark is as unstable.

Comment (ellatrix) [reply packages/format-library/src/link/inline.js]: I think it doesn't have much purpose if `Popover` has this ability as well.

File: packages/components/src/popover/README.md [hunk 3]
```diff
@@ -123,6 +123,20 @@ Opt-in prop to show popovers fullscreen on mobile, pass `false` in this prop to
  - Required: No
  - Default: `false`
 
+### getAnchorRect
```
Comment (ellatrix) [inline packages/components/src/popover/README.md]: Are we certain about the future of `getAnchorRect` before documenting it? Perhaps we could work towards only supporting `anchorRect`.

File: packages/components/src/popover/index.js [hunk 4]
```diff
@@ -87,6 +87,15 @@ class Popover extends Component {
 		if ( prevProps.position !== this.props.position ) {
 			this.computePopoverPosition( this.state.popoverSize, this.anchorRect );
 		}
+
+		if ( prevProps.anchorRect !== this.props.anchorRect ) {
+			this.refreshOnAnchorMove();
+		}
+
+		const hasAnchorRect = this.props.hasOwnProperty( 'anchorRect' );
+		if ( hasAnchorRect !== prevProps.hasOwnProperty( 'anchorRect' ) ) {
```
Comment (ellatrix) [inline packages/components/src/popover/index.js]: Why use `hasOwnProperty`?

**Review by ellatrix — APPROVED** [review]
This works really well in my testing!

File: packages/format-library/src/link/inline.js (hunk 1 above)
Comment (ellatrix) [reply packages/format-library/src/link/inline.js]: This works great! Much smoother. :)

File: packages/format-library/src/link/inline.js [hunk 5]
```diff
@@ -77,6 +77,39 @@ const LinkViewerUrl = ( { url } ) => {
 	);
 };
 
+const URLPopoverAtLink = ( { isActive, addingLink, value, ...props } ) => {
+	const anchorRect = useMemo( () => {
```
Comment (ellatrix) [inline packages/format-library/src/link/inline.js]: Just wondering... Does this have a limit on cache size? Sounds like it should have a limit of exactly one.

File: packages/components/src/popover/README.md (hunk 3 above)
Comment (aduth) [reply packages/components/src/popover/README.md]: > Are we certain about the future of `getAnchorRect` before documenting it? Perhaps we could work towards only supporting `anchorRect`.

I don't mind to remove the documentation, if even just to keep the changes well-contained. I don't have much a problem with this prop, at least in that it's a useful way to also base the computed anchor rect relative the passed default `anchor` argument. I'm also not entirely comfortable with the prospect of removing functionality based on the absence of it from documentation either.

File: packages/format-library/src/link/inline.js (hunk 5 above)
Comment (aduth) [reply packages/format-library/src/link/inline.js]: > Just wondering... Does this have a limit on cache size? Sounds like it should have a limit of exactly one.

It's not entirely clear, but it seems like something they would have considered as being the default behavior, but I also recall some similar discussion with @gziolo recently where he was showing a separate project which, by its name, might imply a different behavior 🤷‍♂️ 

https://github.com/alexreardon/use-memo-one#readme

>You may rely on useMemo as a performance optimization, not as a semantic guarantee. In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. Write your code so that it still works without useMemo — and then add it to optimize performance.

https://reactjs.org/docs/hooks-reference.html#usememo

>**useMemo and useCallback cache the most recent result**. However, this cache can be destroyed by React when it wants to:

File: packages/components/src/popover/index.js (hunk 4 above)
Comment (aduth) [reply packages/components/src/popover/index.js]: > Why use `hasOwnProperty`?

Because we expect the value could change over time, but scheduling the interval doesn't depend on the value, it just depends on whether a value _exists_.

File: packages/format-library/src/link/inline.js (hunk 5 above)
Comment (ellatrix) [reply packages/format-library/src/link/inline.js]: Yeah, to me it sounded like it was not the intention of `useMemo` to limit the cache to one by default. So I would consider swapping it. I'm generally wary of things that create cache without any limit. We're just taking more and more space from memory for no reason.

Comment (aduth) [reply packages/format-library/src/link/inline.js]: > Yeah, to me it sounded like it was not the intention of `useMemo` to limit the cache to one by default. So I would consider swapping it. I'm generally wary of things that create cache without any limit. We're just taking more and more space from memory for no reason.

Oh, I was thinking the opposite by my interpretation; that yes, it would only store the one latest result in memory. I'll plan to double-check, though.

Comment (aduth) [reply packages/format-library/src/link/inline.js]: From what I can discern, it only maintains a single value.

https://github.com/facebook/react/blob/3438e5ce879883590f68370b9ad6448a8ffdfdc1/packages/react-dom/src/server/ReactPartialRendererHooks.js#L338-L365

File: packages/format-library/src/link/inline.js [hunk 6]
```diff
@@ -77,6 +77,39 @@ const LinkViewerUrl = ( { url } ) => {
...
+
+		while ( element.nodeType !== window.Node.ELEMENT_NODE ) {
+			element = element.parentNode;
+		}
+
+		const closest = element.closest( 'a' );
+		if ( closest ) {
+			return closest.getBoundingClientRect();
+		}
+	}, [ isActive, addingLink, value.start, value.end ] );
```
Comment (aduth) [inline packages/format-library/src/link/inline.js]: I don't know that `isActive` needed to be listed as a dependency. It's not ever used in the `useMemo` callback.
