### PR TITLE
Hide inserter's block preview when searching

### LINKED ISSUE #23596: Block preview doesn't go away when searching for blocks
**Describe the bug**
When searching for blocks to use (like from the block directory), hovering over a block button shows a preview. The preview then stays visible even if the block is filtered out of the list (unless another block is hovered over). If no blocks are found, there's no way to reset the hovered item, so the preview can't be closed.

**To reproduce**
1. Open the main block inserter +
2. Click into the search field
3. Hover over a block icon
4. See the preview
5. Start searching, the preview stays around, or maybe switches to another block preview
6. If no installed blocks are found, the preview never goes away
7. Same happens even if blocks are found in the block directory, which might be confused for a preview of the block directory result

**Expected behavior**
When the selected block is filtered out, the preview should disappear

**Screenshots**
Once i'm in the "no blocks found" state, there's no way to remove the preview - no matter where I click.

Recorded on 5.5-alpha + GB master; also happens on WP 5.4 & GB 8.4.

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description

Fixes https://github.com/WordPress/gutenberg/issues/23596

When searching for blocks to use, from the inserter menu, hovering over a block button shows a preview.

If we start typing/searching, the preview stays visible and If no blocks are found, there's no way to reset the hovered item, so the preview can't close.

Details steps to reproduce are in the related issue https://github.com/WordPress/gutenberg/issues/23596

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by youknowriad** [comment]
I wonder if the right fix is more "call setHoveredItem( null )" when the hovered element gets "unmounted" as searching is just one way of unmounting the block element. That said, I'm not sure how simple is it to implement.

**Comment by ntsekouras** [comment]
Hey @youknowriad  ! 

If we start typing, even if the previous block is still in the filtered list, it doesn't help us on selecting it, since the block has no focus and we cannot select it ( by pressing `Enter` ). 

We can only select a block by clicking it or with `tab` navigation, that also change the Previews.

So in general I'm not sure if there is any value to the user to see a previous hovered block's Preview. What do you think?

**Comment by youknowriad** [comment]
I agree that when searching, even if we're hovering the block, it's not that important to show the preview but I'm more thinking if there are other interactions where the preview can linger because the "onMouseOut" event don't trigger. For example:

 - Hover block
 - Navigate with keyboard to the inserter tabs
 - Click arrow to switch tabs.

**Comment by ntsekouras** [comment]
> if there are other interactions where the preview can linger because the "onMouseOut" event don't trigger.

You are right about that! I'll look into it

**Comment by ntsekouras** [comment]
Hey @youknowriad! What do you think of this approach?

File: packages/block-editor/src/components/inserter/block-types-tab.js [hunk 1]
```diff
@@ -106,6 +108,9 @@ export function BlockTypesTab( {
 		return result;
 	}, [ filteredItems, collections ] );
 
+	// hide block preview on unmount
+	useEffect( () => () => onUnmount(), [] );
```
Comment (youknowriad) [inline packages/block-editor/src/components/inserter/block-types-tab.js:112]: Shouldn't we just call `onHover( null )` here instead of a  new prop?

Comment (ntsekouras) [reply packages/block-editor/src/components/inserter/block-types-tab.js:112]: Yes! Thank you @youknowriad. I was thinking at first to have a handler for `unMount`, but since it can be achieved internally, there is no need for the extra prop for now.

**Review by youknowriad — APPROVED** [review]
Thanks, LGTM
