### PR TITLE
Fix/form toggle accessibility

### LINKED ISSUE #906: Switch toggle accessibility
The "switch toggle", used for example for the "Pending review" setting, would need some improvements. This is the current markup output:
```
<label class="editor-post-status__row">
	<span>Pending review</span>
	<div class="components-form-toggle">
		<input type="checkbox" class="components-form-toggle__input" id="toggle-2" value="false">
		<label class="components-form-toggle__label" for="toggle-2"></label>
	</div>
</label>
```

Invalid HTML, two errors:
- div elements can't be placed inside label elements
- nested labels are not allowed

I understand this was meant to make the text "Pending review" text change the checkbox state when clicked, unfortunately the `FormToggle` component already outputs a label (and it's empty).

From an accessibility perspective, screen readers ignore the outer label and take into consideration the inner one. Since it's empty, there's nothing to announce:

screen shot 2017-05-25 at 19 10 09

For sighed users, the state change is indicated just with a color change:

screen shot 2017-05-24 at 09 28 00

screen shot 2017-05-24 at 09 27 53

Yes, the "knob" position changes but in absence of color, or with color perception impairments, users wouldn't know which of the two positions is which. When exactly is "off" or "on"?

I've recently worked on a switch control on another project that is taking inspiration from Google Material design guidelines where these kind of custom controls are well documented. For reference, in a first version they recommended to use visible "on" and "off" text, but then that was deprecated. [In the current version](https://material.io/guidelines/components/selection-controls.html#selection-controls-switch), they recommend:
> The option that the switch controls, as well as the state it’s in, should be made clear from the corresponding inline label. 

That's a bit controversial, as a real label element shouldn't dynamically change its content. For this reasons, our decision was to keep using visible "on" and "off" text, hidden to assistive technologies with `aria-hidden="true"` because the state change is already announced by screen readers. That was needed for the visual part though. I'm not saying this solution should necessarily be the one Gutenberg will use 🙂  I'd recommend to consider visual improvements too, though.

Aside:
one of the reasons why I'm concerned about the educational value of React, it's because it just happens (and happened also to me a lot of times) to forget the actual HTML output. This code:

```
<label className="editor-post-status__row">
	<span>{ __( 'Pending review' ) }</span>
	<FormToggle
		checked={ status === 'pending' }
		onChange={ onToggle }
	/>
</label>
```

doesn't tell me at first sight that I'm actually going to produce invalid HTML. It's wonderfully abstracted and re-usable but so easy to be abused. What when, a few months or years from now, developers that haven't built this component will try to use it? They're not required to actually know what HTML it outputs, they are just supposed to use it otherwise what's the point in re-usability? And if they have to check each time what a component actually does, what's the point in abstracting it? Just thoughts from an old-school guy 😉

### PR DESCRIPTION
**Pull request by youknowriad**
This PR closes #906 by:

 - Adding an optional "On/Off" Toggle to the `FormToggle` component
 - Transforming the `FormToggle` component to an inline component
 - Dropping the embedded `label` from the `FormToggle` component
 - Explicitly use `id/for` for the input/label of the "Pending review" toggle.

### CODE REVIEW

File: components/form-toggle/index.js [hunk 1]
```diff
@@ -21,27 +22,35 @@ class FormToggle extends Component {
...
 					type="checkbox"
 					value={ checked }
 					onChange={ onChange }
 				/>
-				<label className="components-form-toggle__label" htmlFor={ id }>
-					{ children }
-				</label>
-			</div>
+				{ showHint &&
+					<span className="components-form-toggle__hint">
```
Comment (aduth) [inline components/form-toggle/index.js]: Per #906, it seemed the recommendation would be to disable this from being read by screen readers, I presume because the input's own value state would suffice.

>For this reasons, our decision was to keep using visible "on" and "off" text, hidden to assistive technologies with `aria-hidden="true"` because the state change is already announced by screen readers.

Also discussing the hint more generally at https://github.com/WordPress/gutenberg/issues/906#issuecomment-304297513

File: components/form-toggle/index.js [hunk 2]
```diff
@@ -21,27 +22,35 @@ class FormToggle extends Component {
...
 
 	render() {
-		const { className, checked, children, onChange = noop } = this.props;
-		const id = 'toggle-' + this.id;
+		const {
+			className,
+			checked,
+			onChange = noop,
+			showHint = true,
+			id = 'toggle-' + this.id,
```
Comment (aduth) [inline components/form-toggle/index.js]: Should we need to suffix this or manipulate it in any way, or can we treat it as verbatim presumed unique from the parent passing the prop?

Comment (youknowriad) [inline components/form-toggle/index.js]: I think we should treat it as unique from the parent to allow its usage for the label `htmlFor` without the need to "know" the prefix.

Comment (aduth) [inline components/form-toggle/index.js]: Ohhh, I missed that this was assigning the default. But why do we need a default? If the parent component isn't passing an ID, what purpose does the ID have?

Comment (youknowriad) [inline components/form-toggle/index.js]: You're right. It's probably safe to delete.

File: components/form-toggle/style.scss [hunk 3]
```diff
@@ -52,11 +38,35 @@ $toggle-border-width: 2px;
...
+.components-form-toggle__input[type=checkbox] {
+	position: absolute;
+	top: 0;
+	left: 0;
+	width: 100%;
+	height: 100%;
+	opacity: 0;
+	margin: 0;
+	padding: 0;
+	z-index: z-index( '.components-form-toggle__input' );
```
Comment (aduth) [inline components/form-toggle/style.scss]: Can you explain the need for z-index? Does it need to be higher than a dialog?

Comment (youknowriad) [inline components/form-toggle/style.scss]: yes, this is a trick to allows the `onChange` handler to trigger when we click on the invisible input.

Comment (youknowriad) [inline components/form-toggle/style.scss]: Oh Higher than the dialog probably not. I'm updating

Comment (aduth) [inline components/form-toggle/style.scss]: I'm wondering if some logical groupings in the `_z-index.scss`, even just a comment, could help avoid this temptation of assigning it a value _a little more than the next highest_. Like "Relative Siblings", "Layout", "Dialogs", etc. We have some grouping already, but mostly by related components. Dunno if that's a more sustainable pattern than lower-to-highest. It's a difficult problem, and one which I don't think needs to be solved here, but I expect will continue to surface over time.

Related discussion at #637

Comment (youknowriad) [inline components/form-toggle/style.scss]: Yes, I like the idea of grouping by "type" and inside the lower type "relative siblings" group by related components.

File: editor/sidebar/post-status/index.js [hunk 4]
```diff
@@ -20,45 +21,55 @@ import PostSchedule from '../post-schedule';
...
+				</div>
+				<div className="editor-post-status__row">
+					<PostTrash />
+				</div>
+			</PanelBody>
+		);
+	}
 }
 
+PostStatus.instances = 1;
```
Comment (aduth) [inline editor/sidebar/post-status/index.js]: It's not a terribly complex pattern, but unfortunate in how it forces a class component. What do you think about a higher-order component for convenience?

```js
withUniqueId( 'prefix-' )( function( { id } ) {
	return <div id={ id } />;
} );
```

Not to be solved here.

**Review by aduth — APPROVED** [review]
I like the idea of treating these components as inputs and leaving it to the developer to create the associated label. Or at least I think this helps avoid the sorts of issues observed in #906. We should start to look at how to document components as such. Code-wise I think this looks good. Still curious to see where #906's discussion goes, but with current usage not making use of the hint, I think it can be reevaluated later (or dropped now and introduced later? Not really sure its value if we choose not to use it).

File: editor/sidebar/post-status/index.js (hunk 4 above)
Comment (youknowriad) [inline editor/sidebar/post-status/index.js]: Funny, because I was thinking the exact same thing 👍 (maybe `uid` is better as prop or `uniqueId`)

Comment (aduth) [inline editor/sidebar/post-status/index.js]: > (maybe `uid` is better as prop or `uniqueId`)

I don't feel strongly that it's necessary, but between the two I might prefer `uniqueId` just for clarity by verbosity.
