### PR TITLE
Editor: Fix the scroll position when reordering blocks

### LINKED ISSUE #2936: Moving blocks no longer adjusts scroll position
## Issue Overview
We used to adjust scroll position after moving (a) block(s). This is no longer the case.

## Steps to Reproduce (for bugs)
Move any block.

## Expected Behavior
Arrows stay under the pointer.

## Current Behavior
Blocks move up/down relative to the pointer.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #2936

This regressed when we changed the scrollable area (from the global window to the editor's layout).
The fix here scroll's the editor's layout instead.

**Caveats**

 - A selector to the editor's layout node is hard-coded in the `Block.js` file. This is not ideal, should we provide this node as prop? Should this be something in the editor's settings?

**Teseting instructions**

 - Try moving a block
 - The scroll position should be adjusted to keep the block at the same position

### CODE REVIEW

File: editor/modes/visual-editor/block.js [hunk 1]
```diff
@@ -87,6 +87,9 @@ class VisualEditorBlock extends Component {
 		if ( this.props.isTyping ) {
 			document.addEventListener( 'mousemove', this.stopTypingOnMouseMove );
 		}
+
+		// Not Ideal, but it's the easiest way to get the scrollable container
+		this.editorLayout = document.querySelector( '.editor-layout__editor' );
```
Comment (mtias) [inline editor/modes/visual-editor/block.js]: Any other ideas here?

Comment (iseulde) [reply editor/modes/visual-editor/block.js]: Multi-select also broke because of the same scroll container change. I've changed that so it's independent of the scroll position, but in this case you need the container to do a scroll... Maybe better to pass the container down as a prop?

Comment (iseulde) [reply editor/modes/visual-editor/block.js]: We can use the prop in block-list too then, and avoid calculating the dimension on scroll and mousemove.

Comment (aduth) [reply editor/modes/visual-editor/block.js]: Popover achieved this (specifying DOM target) with a context provider, though I'm seeking to move away from it in favor of Slot-Fill:

https://github.com/WordPress/gutenberg/tree/master/components/popover#usage

**Review by aduth — APPROVED** [review]
Re: Explicitly referencing the DOM node, could use a blaring `TODO: Not this` (or associated issue) but if we want this fixed in the next release, this could be a good interim solution.
