### PR TITLE
Preview: Enable published posts preview

### LINKED ISSUE #2544: Preview link broken until post is saved for the first time
## Issue Overview

Gutenberg 0.9
Preview link at top of page does not work unless I update the page first. I get a new browser tab -
 about:blank.  

## Steps to Reproduce (for bugs)

1. Create Gutenberg post
2. add content
3. publish post
4. edit post in Gutenberg
5. make change in post
6. click Preview link at top of page
7. Chrome opens a new tab with about:blank URL
8. This occurs in both author and admin roles
9. If I Update the post first, then the Preview link works.

## Expected Behavior

If I make changes in a post I should be able to preview the post before Updating, especially if this is a Published post and not a Draft post.

Preview link should work like it does currently.

## Current Behavior

Preview link at top of page does not work unless I update the page first. I get a new browser tab about:blank.  

## Todos
- [ ] Tests
- [ ] Documentation

### LINKED ISSUE #7179: REST API: Autosaves entities should include `preview_link`
Related: #2544

In order to preview a published post, we need to create an autosave revision. The preview behavior in Gutenberg relies on the addition of a `preview_link` field to the post endpoint, which calls `get_preview_post_link`.

https://github.com/WordPress/gutenberg/blob/423dbed98af82de110af2992806dffff754c8ecb/lib/rest-api.php#L441-L478

This field is not included in the autosaves endpoint return value, however, so it can't be known where the user should be directed on a published post autosave.

Thus, we should:

- Make the preview link available on the autosaves endpoint response
- Consider whether this should be included as a `_links` field (not sure what the standard practice is here)

Alternatively, we could attempt to recreate this logic in the client, which relies on:

- [Knowing that the post exists](https://github.com/WordPress/WordPress/blob/6fd8080e7ee7599b36d4528f72a8ced612130b8c/wp-includes/link-template.php#L1295-L1298)
   - Can be assumed when editing
- [That the post type is visible](https://github.com/WordPress/WordPress/blob/6fd8080e7ee7599b36d4528f72a8ced612130b8c/wp-includes/link-template.php#L1300-L1308)
   - Would need something like `visibility` field added for taxonomies (#2654, [Trac#42707](https://core.trac.wordpress.org/ticket/42707))
- [Filtering `preview_post_link`](https://github.com/WordPress/WordPress/blob/6fd8080e7ee7599b36d4528f72a8ced612130b8c/wp-includes/link-template.php#L1310-L1319)
   - Not possible to recreate in the client

### PR DESCRIPTION
**Pull request by aduth**
Closes (when #7130 is merged): #7179
Closes (when #7130 is merged): #2544
Related: #6257, #6882

**Note:** Merges to `fix/autosave-preview` (#7130) as base branch.
**Note:** As best I can tell, this branch is fully functional, but I have plans to include new end-to-end tests for various preview circumstances prior to merge.

This pull request seeks to allow the user to preview changes to a published post without first updating the post (i.e. the autosave revision preview).

In doing so, it...

- Refactors the `PostPreviewButton` component to avoid relying on a specific save workflow, and instead leverage the mere availability of a preview link
- Removes `preview_link` from the posts endpoints and adds instead to the autosaves endpoint (see #7179)

To the latter point, I landed at the conclusion that `preview_link` only makes sense in the context of autsosaves on consideration of:

- The post endpoints reflect the value of the canonical saved post. If there are no unsaved changes, the user should be directed to `post.link` as its preview.
- It does not belong in the revisions endpoints because it is not the case that any revision can be previewed. A preview only occurs for the latest revision of a post ([`_set_preview`](https://github.com/WordPress/WordPress/blob/6fd8080e7ee7599b36d4528f72a8ced612130b8c/wp-includes/revision.php#L556), [`wp_get_post_autosave`](https://github.com/WordPress/WordPress/blob/6fd8080e7ee7599b36d4528f72a8ced612130b8c/wp-includes/revision.php#L232-L246)).

Related Trac tickets:

- [REST API: Support autosaves](https://core.trac.wordpress.org/ticket/43316) (43316)
- [REST API: Expose 'preview_link' for viewable post types](https://core.trac.wordpress.org/ticket/44180) (44180)

Thus, if there are no unsaved changes for a post, the Preview button is effectively a link to `post.link`. If there are unsaved changes, the autosave is triggered and once its responses' `autosave.preview_link` becomes accessible, it is used in the redirect (regardless of whether or not the autosave occurred as a full save as described in #7124).

### CODE REVIEW

**Comment by danielbachhuber** [comment]
> To the latter point, I landed at the conclusion that preview_link only makes sense in the context of autsosaves on consideration of:

This is an interesting idea. I hadn't considered it this way before, but it seems like a reasonable decision to me (particularly because I don't think core's existing implementation of previews is this well-considered).

File: editor/store/test/reducer.js [hunk 1]
```diff
@@ -2298,13 +2298,15 @@ describe( 'state', () => {
 						raw: 'The Excerpt',
 					},
 					status: 'draft',
+					preview_link: 'https://wordpress.org/?p=1',
```
Comment (danielbachhuber) [inline editor/store/test/reducer.js]: Nit: Should this include `&preview=true` for clarity?

File: lib/class-wp-rest-autosaves-controller.php [hunk 2]
```diff
@@ -339,6 +349,18 @@ public function prepare_item_for_response( $post, $request ) {
 
 		$response = $this->revisions_controller->prepare_item_for_response( $post, $request );
 
+		$schema = $this->get_item_schema();
+
+		if ( ! empty( $schema['properties']['preview_link'] ) ) {
+			$response->data['preview_link'] = get_preview_post_link( $post->post_parent, array(
+				'preview_id'    => $post->post_parent,
```
Comment (danielbachhuber) [inline lib/class-wp-rest-autosaves-controller.php]: Is `preview_id` supposed to be `$post->post_parent`? This ends up as `0` on a draft post:

image

**Review by danielbachhuber — COMMENTED** [review]
Couple small nits. I also ran into an issue where the preview doesn't reflect the title:

image

image

It's not immediately obvious to me why that discrepancy exists.

File: editor/store/test/reducer.js (hunk 1 above)
Comment (aduth) [reply editor/store/test/reducer.js]: >Nit: Should this include `&preview=true` for clarity?

Yep, sounds good.

File: lib/class-wp-rest-autosaves-controller.php (hunk 2 above)
Comment (aduth) [reply lib/class-wp-rest-autosaves-controller.php]: >Is `preview_id` supposed to be `$post->post_parent`? This ends up as `0` on a draft post:

Good call. We might consider using something like [`wp_is_post_autosave`](https://developer.wordpress.org/reference/functions/wp_is_post_autosave/) to vary the logic. Though in this context since we assume the `$post` is the result of either an autosave (`get_item`) or generated by an autosave intent, maybe just testing its type `$post->post_type === 'revision'`.

Comment (aduth) [reply lib/class-wp-rest-autosaves-controller.php]: Hmm the `-autosave` post name suffix checking in `wp_is_post_autosave` makes me think it might be better to rely on that. Guessing it might be possible for a non-autosave revision to be attached to a post parent?

**Comment by aduth** [comment]
>Couple small nits. I also ran into an issue where the preview doesn't reflect the title:

I can reproduce this, and it seems to affect where we're previewing a post we'd already previewed once before in the same session:

1. Navigate to Posts > Add New
2. Enter a title
3. Hit preview
4. Return to editor tab
5. Change title
6. Hit preview

Expected: Preview is shown with updated title
Actual: Preview reflects original title.

The problem is that the second time we preview, we already have a `preview_link` available because we reset the autosave after the first preview. I think we either need to:

- Clear the `preview_link` before an autosave starts so it isn't considered for the popup window
- Consider change detection and invalidate the preview link as soon as the user makes an edit
- Force the autosave and interstitial screen if the post is dirty, even if a preview link is already available
   - Might be the simplest approach for now. Technically this is wasted for repeatedly hitting "Preview" on a published post, since it remains dirty after an autosave.

**Comment by aduth** [comment]
Another complication: For repeated previews of a draft post, even if I make changes, the preview URL will never change (e.g. `?p=123&preview=true`), so it's hard to know that the preview is ready without either (re-)integrating awareness of the save process, or invalidating the preview link at some point (e.g. on edit or pre-autosave)

**Comment by adamsilverstein** [comment]
Thanks for working on this @aduth - I'll give it a test and review as soon as possible!

File: editor/store/effects.js [hunk 3]
```diff
@@ -157,49 +157,14 @@ export default {
...
 			( newPost ) => {
+				const reset = isAutosave ? resetAutosave : resetPost;
+				dispatch( reset( newPost ) );
+
 				// An autosave may be processed by the server as a regular save
 				// when its update is requested by the author and the post was
 				// draft or auto-draft.
 				const isRevision = newPost.id !== post.id;
 
-				// Thus, the following behaviors occur:
```
Comment (aduth) [inline editor/store/effects.js]: Note that these removed changes were introduced as part of the base branch to which this merges (#7130) so there is effectively no difference between this callback and what's in master at the moment.

**Comment by aduth** [comment]
Going to merge this into the `fix/autosave-preview` branch (#7130) it has assigned as base, so as to be able to work on these related changes in one place.
