### PR TITLE
Transform: select all blocks if the result has more than one block

### LINKED ISSUE #13600: List block: p to list to p breaks the p in multiple blocks
gif - list block split in p

When a paragraph block is converted to a list block and back, each item in the list is split into multiple paragraph blocks instead of reverting to the initial state.

1. (Optional) make a paragraph with multiple list items (separated by &lt;br&gt;), convert to list.
2. Convert the list back to paragraphs

Note: the transformation isn't wrong by itself. It follows a certain logic to have the list split in this way. Yet, it also felt odd the first time I saw it happening. So take this more of a discussion:

* to clarify what should be the intended behaviour
* if we can do something to make it less odd

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Fixes #13600. When a transform results in more than one block, select all those blocks so the result is clear and it can easily be transformed back.

### CODE REVIEW

File: packages/block-editor/src/components/block-switcher/index.js [hunk 1]
```diff
@@ -95,11 +95,22 @@ export const BlockSwitcherDropdownMenu = ( { clientIds, blocks } ) => {
 	const isTemplate = blocks.length === 1 && isTemplatePart( blocks[ 0 ] );
 
 	// Simple block tranformation based on the `Block Transforms` API.
-	const onBlockTransform = ( name ) =>
-		replaceBlocks( clientIds, switchToBlockType( blocks, name ) );
+	function onBlockTransform( name ) {
+		const newBlocks = switchToBlockType( blocks, name );
+		replaceBlocks( clientIds, newBlocks );
+		multiSelect(
```
Comment (ntsekouras) [inline packages/block-editor/src/components/block-switcher/index.js]: Nit: we could not call this if newBlocks is just one block.

File: packages/block-editor/src/components/block-switcher/index.js [hunk 2]
```diff
@@ -95,11 +95,22 @@ export const BlockSwitcherDropdownMenu = ( { clientIds, blocks } ) => {
...
+			newBlocks[ 0 ].clientId,
+			newBlocks[ newBlocks.length - 1 ].clientId
+		);
+	}
 	// Pattern transformation through the `Patterns` API.
-	const onPatternTransform = ( transformedBlocks ) =>
+	function onPatternTransform( transformedBlocks ) {
 		replaceBlocks( clientIds, transformedBlocks );
+		multiSelect(
```
Comment (ntsekouras) [inline packages/block-editor/src/components/block-switcher/index.js]: We might not want to do this for pattern transforms because patterns can contain many other blocks that doesn't necessarily provide a transformation back. This could be okay if the reasoning is to have more clarity about what has been inserted from a transformation.

Comment (ellatrix) [reply packages/block-editor/src/components/block-switcher/index.js]: It's not just about having a transformation. It's about consistency too and as you say, to see what exactly has been inserted.

File: packages/e2e-test-utils-playwright/src/editor/transform-block-to.ts [hunk 3]
```diff
@@ -7,26 +7,38 @@ import type { Editor } from './index';
  * Clicks the default block appender.
  *
  * @param {Editor} this
- * @param {string} name Block name.
+ * @param {string} name Block name or title.
  */
 export async function transformBlockTo( this: Editor, name: string ) {
```
Comment (ellatrix) [inline packages/e2e-test-utils-playwright/src/editor/transform-block-to.ts]: Rewrites this to match
https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-test-utils/src/transform-block-to.js

File: packages/e2e-test-utils-playwright/src/editor/transform-block-to.ts [hunk 4]
```diff
@@ -7,26 +7,38 @@ import type { Editor } from './index';
...
-			window.wp.data.dispatch( 'core/block-editor' ).replaceBlocks(
-				clientIds,
-				// @ts-ignore (Reason: wp isn't typed)
-				window.wp.blocks.switchToBlockType( blocks, blockName )
-			);
-		},
-		[ name ]
+		() =>
+			// @ts-ignore (Reason: window global).
+			new Promise( requestIdleCallback )
```
Comment (ntsekouras) [inline packages/e2e-test-utils-playwright/src/editor/transform-block-to.ts]: Why do we need this?

Comment (ellatrix) [reply packages/e2e-test-utils-playwright/src/editor/transform-block-to.ts]: Copied over from https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-test-utils/src/transform-block-to.js

**Review by ntsekouras — APPROVED** [review]
LGTM, thanks! I actually had a [conversation](https://github.com/WordPress/gutenberg/pull/39807#discussion_r1009468113) about e2e utils doing programmatically actions with @kevin940726 and it seems this is a case where it showed up(and I think we'll have many more).

In your case the previous util didn't select all the transformed blocks, like the block switcher behavior is now and we would have as alternatives:
1. Sync the dispatched action to the util to multiselect(maintenance overhead)
2. Manually select the transformed blocks and transform again(so bad IMO for so many reasons)
3. Add a second util to do what a user would do and keep that one as well(also bad IMO)

This change seems to have broken some other tests, so when fixed - green CI, let's ship.

**Comment by kevin940726** [comment]
> Manually select the transformed blocks and transform again(so bad IMO for so many reasons)

Why is this bad? I honestly think this is the best approach of all. This makes the test readable since we don't hide some user flow in the utils.

I believe we should make explicit assertions of what we're trying to test against. Playwright's API makes it easy to do so, I think we should leverage that and restructure our tests accordingly.

In this case, we're not testing if the edited content matches a specific output after some operations (snapshot testing). Instead, we want to test if the blocks get selected after the transformation: we should explicitly test that.

The "transform" flow can be done in two steps when the block tools bar is opened.

```js
await page
	.getByRole( 'region', { name: 'Block tools' } ) // Targeting the block tools
	.getByRole( 'button', { name: 'List' } ) // Targeting the "List" button in the block tools
	.click();
await page
	.getByRole( 'group', { name: 'Transform to' } ) // Targeting the "Transform to" group
	.getByRole( 'menuitem', { name: 'Paragraph' } ) // Targeting the paragraph button in the group
	.click();

// ...or we can use string-based selectors:
await page.click( 'role=region[name="Block tools"i] >> role=button[name="List"i]' );
await page.click( 'role=group[name="Transform to"i] >> role=menuitem[name="Paragraph"i]' );
```

This is readable and accessible and contains no implementation details. We can just inline it in the test to test that specific user flow.

What about repeating? I don't think repeating code is bad in testing, especially when there are just two lines. If we still want to make an abstraction, we can do that in the same file with a POM-style fixture. If it's repeating in many tests then we can abstract them away into the `e2e-test-utils-playwright` package if necessary. But defaulting every abstraction to the `e2e-test-utils-playwright` package from the start is often overkill and makes it harder to maintain both the utils package and the tests.

The ideal assertion we want to make in this test is to check for the selected blocks, we can use public APIs for that.

```js
const selectedBlocksNames = await page.evaluate( () => {
	return window.wp.data.select( 'core/block-editor' )
		.getMultiSelectedBlocks()
		.map( ( block ) => block.name );
} );

// Or something more semantic then checking block names.
expect( selectedBlocksNames ).toEqual( [ 'core/paragraph', 'core/paragraph' ] );
```

Whether or not to repeat the transformation operation again is optional (though I think adding it is a nice touch!). We should still keep the explicit assertions there for better readability, and we can also skip snapshot testing altogether. IMO, snapshot testing is only useful if the output is directly related to the assertions. Making long and multiple snapshots is hard to review and read.

With all that said, these are just my suggestions and they are up for discussion. I recommend reading the current [best practices](https://github.com/WordPress/gutenberg/blob/trunk/test/e2e/README.md#best-practices) guide and raise any issues if you spot something that you disagree with. Hope that we can reach a consensus and eliminate the confusing parts :).

File: packages/block-editor/src/components/block-switcher/index.js [hunk 5]
```diff
@@ -89,12 +89,27 @@ export const BlockSwitcherDropdownMenu = ( { clientIds, blocks } ) => {
...
 	const isTemplate = blocks.length === 1 && isTemplatePart( blocks[ 0 ] );
 
+	function selectForMultipleBlocks( insertedBlocks ) {
+		if ( insertedBlocks.length > 1 ) {
+			multiSelect(
+				insertedBlocks[ 0 ].clientId,
+				insertedBlocks[ insertedBlocks.length - 1 ].clientId
+			);
+		}
+	}
```
Comment (kevin940726) [inline packages/block-editor/src/components/block-switcher/index.js:99]: I wonder if this would be good to be added to the `replaceBlocks` thunk so that everywhere else will get the consistent behavior? The `insertBlocks` action has a similar `updateSelection` optional options to this, so it might make sense to do something similar to `replaceBlocks` as well?

File: packages/e2e-test-utils-playwright/src/editor/transform-block-to.ts (hunk 3 above)
Comment (kevin940726) [reply packages/e2e-test-utils-playwright/src/editor/transform-block-to.ts]: I should probably rewrite or remove the e2e-test-utils section in the [MIGRATION](https://github.com/WordPress/gutenberg/blob/trunk/test/e2e/MIGRATION.md#migration-steps-for-test-utils) guide. The utils are not meant to be one-to-one mapping and they don't necessarily have to behave the same. We try to match the names and the APIs because it's easier for the migration, but they should still follow the [best practices](https://github.com/WordPress/gutenberg/blob/trunk/test/e2e/README.md#best-practices). This is totally up for debate though as I mentioned in the [comment](https://github.com/WordPress/gutenberg/pull/45015#issuecomment-1300028659) 🙂.

File: test/e2e/specs/editor/blocks/list.spec.js [hunk 6]
```diff
@@ -1231,4 +1231,25 @@ test.describe( 'List', () => {
 
 		expect( await editor.getEditedPostContent() ).toMatchSnapshot();
 	} );
+
+	test( 'selects all transformed output', async ( { editor, page } ) => {
+		await page.click( 'role=button[name="Add default block"i]' );
+		await page.keyboard.type( '* 1' );
+		await page.keyboard.press( 'Enter' );
+		await page.keyboard.type( '2' );
```
Comment (kevin940726) [inline test/e2e/specs/editor/blocks/list.spec.js]: Since these are just setting up the state for the test, it's not related to the goal of this test. We can use `editor.insertBlock` or `editor.setContent` instead.

File: packages/block-editor/src/components/block-switcher/index.js (hunk 5 above)
Comment (ellatrix) [reply packages/block-editor/src/components/block-switcher/index.js:99]: That's what I would love to do as well, but we can't change the behaviour now, unless we introduce yet another option to select all blocks. I think we shouldn't do that just yet until we find more use cases.

File: test/e2e/specs/editor/blocks/list.spec.js [hunk 7]
```diff
@@ -1231,4 +1231,38 @@ test.describe( 'List', () => {
...
+		await editor.selectBlocks(
+			page.locator( 'role=document[name="Block: List"i]' )
+		);
+
+		await page
+			.getByRole( 'button', {
+				name: 'List',
+				description: 'List: Change block type or style',
+			} )
+			.click();
```
Comment (kevin940726) [inline test/e2e/specs/editor/blocks/list.spec.js]: I think the `description` field is only needed because we're not limiting the results. Selectors are strict by default, which means if a selector matches multiple elements then it will fail. We can chain selectors to filter out those that are not what we're targeting. 

In this case, I think we can do this:

```suggestion
		await page
			.getByRole( 'region', { name: 'Block tools' } )
			.getByRole( 'button', { name: 'List' } )
			.click();
```

Comment (ellatrix) [reply test/e2e/specs/editor/blocks/list.spec.js]: It's not that the description was needed, it's that I'd like to use it over more specificity. I would have liked to simply use `page.getByRole( 'button', { description: 'List: Change block type or style' } )`, but it did not work ("Error: strict mode violation: "role=button" resolved to 20 elements"). Do you know why? I though the description should limit the results to 1.

Comment (kevin940726) [reply test/e2e/specs/editor/blocks/list.spec.js]: I see!

I think the `description` field is never a valid option in [`getByRole`](https://playwright.dev/docs/api/class-page#page-get-by-role)?

Comment (ellatrix) [reply test/e2e/specs/editor/blocks/list.spec.js]: Ah! I was looking at the [wrong API docs](https://testing-library.com/docs/queries/byrole/). Strange that it's not an option here, it would be useful.

Comment (kevin940726) [reply test/e2e/specs/editor/blocks/list.spec.js]: I still think we should chain selectors here though. Selecting `getByRole('button', { name: 'List' })` is not immediately readable for which element exactly is being selected. The test will break if there's a random button with the same name added to the page. To increase the specificity level, we should make it clear that the button is from the `Block tools` region as suggested above. WDYT?

File: test/e2e/specs/editor/blocks/list.spec.js [hunk 8]
```diff
@@ -1231,4 +1231,28 @@ test.describe( 'List', () => {
...
+		} );
+
+		await editor.selectBlocks(
+			page.locator( 'role=document[name="Block: List"i]' )
+		);
+
+		await page.getByRole( 'button', { name: 'List' } ).click();
+		await page.getByRole( 'menuitem', { name: 'Paragraph' } ).click();
+
+		expect( await editor.getEditedPostContent() ).toMatchSnapshot();
```
Comment (kevin940726) [inline test/e2e/specs/editor/blocks/list.spec.js:1251]: As per https://github.com/WordPress/gutenberg/pull/45015#issuecomment-1300028659, I don't think snapshot testing makes much sense here. The assertions here are not readable and feel disconnected from the title of the test case. Instead, we should prioritize explicit assertions and make them target the selected blocks. The same goes for the last snapshot assertion in this test case.
