### PR TITLE
Patterns: use existing download function for JSON downloads to fix non-ASCII encoding

### LINKED ISSUE #55746: Site Editor bug exporting patterns as JSON
### Description

Reporting this upstream after investigating [Trac ticket 59771](https://core.trac.wordpress.org/ticket/59771).

On the trac ticket to the OP notes that when exporting a pattern in the site editor (w/ 6.4 RC2, no GB plugin) and then trying to import that pattern into another site he gets an "Invalid JSON" error.  He also notes that exporting the **same** pattern from the "Manage all my patterns" list table he is able to successfully import the pattern into another site.

Neither I nor @hellofromtonya could replicate the problem at first.  So, I asked the OP to attach his JSON files to the trac ticket.  Indeed, the JSON files he exported in the site editor and from the list table where different.  After some investigation I determined that the problem is that an em-dash character (codepoint U+2014) that appears in the pattern is not being correctly UTF-8 encoded in the JSON export from the site editor (which makes the JSON invalid), but is being encoded correctly from the list table export.

Note that in the OP's pattern, there are other non-ASCII chars that are being correctly UTF-8 encoded.

After some further investigation, I noticed that the JS that does the JSON export in the 2 cases is different.

* site editor uses `exportAsJSON()` in `wp-includes/js/dist/edit-site.js`
* list table row action uses `exportReusableBlock()` in `wp-includes/js/dist/list-reusable-blocks.js`

Note: In both cases, the source of that JS is somewhere else and those files are generated by webpack.  I haven't been able to figure where the un-mangled source JS is...I'm sure someone more familiar with the codebase will know ;-)

While the JS is the 2 cases is slightly different, in looks "equivalent" to me at first glance...basically, doing `JSON.stringify()` on a JS object, one property of which is `post.content.raw`.  That leads me to think that the problem is in how that `post.content.raw` is retrieved in the 2 cases.

### Step-by-step reproduction instructions

1. create a pattern that contains an em-dash
2. go into Editor > Patterns and click the "3 dots" under the pattern created in step 1 and choose "Export as JSON"
3. go into Editor > Manage all of my patterns, when on the list table click the "Export as JSON" row action (be sure to save the site will a different name than in step 2)
4. on the Patterns list table screen, click the "Import from JSON" button and import the file exported in step 2 and receive a "Invalid JSON" error
5. on the Patterns list table screen, click the "Import from JSON" button again and import the file exported in step 3 and receive a success message

### Screenshots, screen recording, code snippet

On the trac ticket, the OP linked to videos of him doing the steps in "Step-by-step reproduction instructions" above.

### Environment info

WP 6.4-RC2
Windows WAMP-like server setup (PHP 8.1, MySQL 8.0, apache 2.4)
Lastest Windows Chrome, Edge, Firefox

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ramonjd**
## What?
Maybe resolves https://github.com/WordPress/gutenberg/issues/55746

Patterns that contain non-ASCII characters are corrupted on download.

## Why?
The downloadjs module patterns is using seems to have a non-resolved bug where it [cannot properly encode non-ASCII characters](https://github.com/rndme/download/issues/56).

## How?
Use the same, [internal function](https://github.com/WordPress/gutenberg/blob/f4389b9851256d1f02b513d8379ee544e446af98/packages/list-reusable-blocks/src/utils/file.js#L8-L8) as the reusable blocks. 

We're downloading only JSON so we don't need any special functionality I gather?

## Testing Instructions
Create a new pattern with the following content: 

```html
<!-- wp:paragraph -->
<p>This is a pattern containing non-ASCII characters 文字出版社 ~=[]()%+{}@;’#!$_&amp;- éè ;∞¥₤€ ワードプレス We hopè you find it inform@tiv€ Thank You!</p>
<!-- /wp:paragraph -->
```

Save the pattern.

Export the pattern.

Re-import the pattern.

Import should work!

### Before
```json
{
  "__file": "wp_block",
  "title": "Non ASCII",
  "content": "<!-- wp:paragraph -->\n<p>This is a pattern containing non-ASCII characters �W�H> ~=[]()%+{}@;#!$_&amp;- �� ;��� ����� We hop� you find it inform@tiv� Thank You!</p>\n<!-- /wp:paragraph -->",
  "syncStatus": ""
}
```

### After

```json
{
  "__file": "wp_block",
  "title": "Non ASCII",
  "content": "<!-- wp:paragraph -->\n<p>This is a pattern containing non-ASCII characters 文字出版社 ~=[]()%+{}@;’#!$_&amp;- éè ;∞¥₤€ ワードプレス We hopè you find it inform@tiv€ Thank You!</p>\n<!-- /wp:paragraph -->",
  "syncStatus": ""
}
```

### CODE REVIEW

File: packages/edit-site/src/components/page-patterns/grid-item.js [hunk 1]
```diff
@@ -52,6 +51,33 @@ import { store as editSiteStore } from '../../store';
...
+ * @param {string} fileName    File Name.
+ * @param {string} content     File Content.
+ * @param {string} contentType File mime type.
+ */
+function download( fileName, content, contentType ) {
+	const file = new window.Blob( [ content ], { type: contentType } );
+
+	// IE11 can't use the click to download technique
+	// we use a specific IE11 technique instead.
+	if ( window.navigator.msSaveOrOpenBlob ) {
```
Comment (glendaviesnz) [inline packages/edit-site/src/components/page-patterns/grid-item.js]: Given we don't officially support IE11 anymore I wonder if we can remove this IE specific code?

**Review by glendaviesnz — APPROVED** [review]
Tested well for me. It could potentially be better placed in the `page-patterns/utils` folder or in the `@wordpress/patterns` package, but given this is the only use of it so far it probably makes sense to keep it here - can be easily moved later if the export option is added in other places.

File: packages/edit-site/src/components/page-patterns/grid-item.js (hunk 1 above)
Comment (ramonjd) [reply packages/edit-site/src/components/page-patterns/grid-item.js]: Oh yeah, good call!

Comment (ramonjd) [reply packages/edit-site/src/components/page-patterns/grid-item.js]: Tested on Edge just in case. LGTM to remove

Comment (glendaviesnz) [reply packages/edit-site/src/components/page-patterns/grid-item.js]: Still tested well for me across chrome/safari/firefox/safari with the IE code removed.

**Comment by swissspidy** [comment]
This dependency could just as well be replaced in `SiteExport` too, then we could remove it entirely from `package.json`

**Comment by ramonjd** [comment]
> This dependency could just as well be replaced in SiteExport too, then we could remove it entirely from package.json

I saw that in there and hesitated as it's used to download `*.zip` files and didn't feel like opening a can of worms yesterday 😄 

But yes, it's worth testing to see if we can remove altogether.

**Comment by ramonjd** [comment]
PR to remove `downloadjs` dependency here: https://github.com/WordPress/gutenberg/pull/56024

**Comment by talldan** [comment]
I saw this was reported again in #56066. @ramonjd do you think it might be a good candidate for a backport to a minor WP version?

**Comment by ramonjd** [comment]
Ah yes, very possibly. The [issue](https://github.com/WordPress/gutenberg/issues/55746) is on the 6.4 editor tasks list I see.

I've added the label and will ping in the WP Slack channel.

Thanks!

**Comment by ramonjd** [comment]
6.4.2 point release PR going on here:

- https://github.com/WordPress/gutenberg/pull/56010

**Comment by mikachan** [comment]
I just cherry-picked this PR to the 6.4-next-point-release branch to get it included in the next release: 6f2a988487
