### PR TITLE
useBlockSync: Fix race condition when onChange callback changes

### LINKED ISSUE #23967: Site Editor - editing a specific Post dirties the home page instead.
**Describe the bug**
In the Site Editor: Editing and saving changes to a post dirties/saves the home page instead.

**To reproduce**
1. Go to the site editor.
2. Navigate to a specific Post via the top nav toolbar.
3. Edit the content of the post.
4. Click 'Update Design' to open the save sidebar.
5. Click 'review changes' in the save sidebar.
6. Verify that the entity staged for changes is a page and not the post.
7.  Save and verify the page content was overwritten and the post content unchanged.

**Expected behavior**
The post to be the dirtied / saved entity.

**Screenshots**

wrong-thing-saved

**Editor version (please complete the following information):**
- WordPress version: 5.5
- If the Gutenberg plugin is installed, which version is it? Master (~8.5+)

### PR DESCRIPTION
**Pull request by noahtallen**
## Description
In the `useBlockSync` hook, if the `onChange` or `onInput` callbacks changed while the same component instance was being used, the old `onChange`/`onInput` callbacks were used instead of the updated ones.

For more context, in #23292, we started setting a ref with the latest onChange/onInput callbacks, but we unfortunately never consumed that ref. cc @youknowriad. This updates the block-editor subscription such that it uses the `onChange` and `onInput` refs. This way, it always uses the latest versions of the callbacks.

Specifically, this fixes #23967 (a result of the race condition).

## How has this been tested?
Locally, in edit-site.

### Before:
gif of before state

### After:
gif of after state

## Types of changes
Bug fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-editor/src/components/provider/test/use-block-sync.js [hunk 1]
```diff
@@ -362,4 +362,78 @@ describe( 'useBlockSync hook', () => {
...
+			);
+		} );
+
+		// Create a persistent change.
+		registry
+			.dispatch( 'core/block-editor' )
+			.updateBlockAttributes( 'b', { foo: 3 } );
+
+		// The first callback should not be called with the new change.
+		expect( onChange1 ).toHaveBeenCalledWith( updatedBlocks1, {
```
Comment (epiqueras) [inline packages/block-editor/src/components/provider/test/use-block-sync.js:428]: I don't think this checks that this was the only call to this function.

You might need to add `toHaveBeenCalledTimes` or other matchers.

**Comment by youknowriad** [comment]
😬 ayy sorry for the miss.

File: packages/block-editor/src/components/provider/test/use-block-sync.js (hunk 1 above)
Comment (noahtallen) [reply packages/block-editor/src/components/provider/test/use-block-sync.js:428]: I don't totally understand why the first `onChange1` callback is firing at all here. the store change should not affect it. Perhaps there is still a stale callback hanging around? (in this case, it is ok because it is the same object as the previous change, so it's not receiving the new block control value)

are you saying it should be fine to check if it was just called once?

Comment (noahtallen) [reply packages/block-editor/src/components/provider/test/use-block-sync.js:428]: Ah, my bad. I just needed to reset the mock before updating the component. Then we can check that it was not called at all.

File: packages/block-editor/src/components/provider/test/use-block-sync.js [hunk 2]
```diff
@@ -362,4 +362,77 @@ describe( 'useBlockSync hook', () => {
...
+			.updateBlockAttributes( 'a', { foo: 2 } );
+
+		const updatedBlocks1 = [
+			{ clientId: 'a', innerBlocks: [], attributes: { foo: 2 } },
+		];
+
+		expect( onChange1 ).toHaveBeenCalledWith( updatedBlocks1, {
+			selectionEnd: {},
+			selectionStart: {},
+		} );
```
Comment (Addison-Stavlo) [inline packages/block-editor/src/components/provider/test/use-block-sync.js:401]: Does this update and assertion make sense for this test?  I think the bug and change aren't specific to the first onChange having to be called first.  On one hand it adds an extra assertion and some safety in case there are other issues with the initial onChange... on the other it biases the the following assertions based on the original onChange having been called (although in this case I wouldn't expect that to cause any problems).  

Philosophically speaking -  maybe this should be a separate test, or just removed if it is already covered elsewhere?  🤔

**Review by Addison-Stavlo — APPROVED** [review]
Awesome!  I can confirm this fixes #23967.  The changes make sense to me, onChange/onInput should no longer become outdated in the subscribed function using these refs.  And thank you for adding the test! 😄 

(small nit Q on the test but this looks good!)

File: packages/block-editor/src/components/provider/test/use-block-sync.js (hunk 2 above)
Comment (noahtallen) [reply packages/block-editor/src/components/provider/test/use-block-sync.js:401]: > maybe this should be a separate test

Thankfully, there is a test that covers this by itself :)

I wanted to add this to test the whole lifecycle of a callback becoming stale -- basically, you have one callback and works, and then you switch to another callback which also works (and then makes the first callback stop working).

I could see a case for just removing this assertion, but I feel like the test is more robust without it. But I think it also makes sense to add a test for the scenario when there has not been a change first

File: packages/block-editor/src/components/provider/test/use-block-sync.js (hunk 1 above)
Comment (epiqueras) [reply packages/block-editor/src/components/provider/test/use-block-sync.js]: Yes
