### PR TITLE
Site Editor: Fix the 'Browse all' link in the template details modal

### LINKED ISSUE #48289: Template Details group "Browse all templates" not opening templates
### Description

The "Browse all templates" button from within the Template Details group is not currently functioning. The expectation is that the the button opens the "All templates" view within the Site Editor (as it did previously). 

### Step-by-step reproduction instructions

1. Go to the Site Editor.
2. Click on the Template Details dropdown.
3. Click on the "Browse all templates" button.
4. See error (templates are not shown). 

### Screenshots, screen recording, code snippet

Template details group button: 

CleanShot 2023-02-21 at 17 43 31

Expected: 
CleanShot 2023-02-21 at 17 49 43

### Environment info

- WordPress Beta 2
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Fixes #48289.

PR fixes the "Browse" all link in the template details modal.

## Why?
The `useLink` hook now requires the `path` argument and canvas to be in the `view` mode.

A possible regression after #48063.

## Testing Instructions

1. Go to the Site Editor.
2. Click on the Template Details dropdown.
3. Click on the "Browse all templates" button.
4. Confirm that the "Manage all templates" page is rendered.
5. Repeat the steps with Template Parts

## Screenshots or screencast 
CleanShot 2023-02-22 at 10 32 44

### CODE REVIEW

File: packages/edit-site/src/components/template-details/index.js [hunk 1]
```diff
@@ -31,10 +31,12 @@ export default function TemplateDetails( { template, onClose } ) {
 	);
 	const { revertTemplate } = useDispatch( editSiteStore );
 
+	// TODO: We should update this to filter by template part's areas as well.
 	const browseAllLinkProps = useLink( {
-		// TODO: We should update this to filter by template part's areas as well.
+		canvas: 'view',
 		postType: template.type,
 		postId: undefined,
+		path: '/' + template.type + '/all',
```
Comment (Mamaduka) [inline packages/edit-site/src/components/template-details/index.js:39]: The `broweAllLink` version from the sidebar navigation component doesn't work in the edit mode.

https://github.com/WordPress/gutenberg/blob/b80d84863e93c2d9b6464718d9e6374f8db0f963/packages/edit-site/src/components/sidebar-navigation-screen-templates/index.js#L63-L65

**Comment by Mamaduka** [comment]
@youknowriad, the new required `path` argument will probably break any "hardcoded" links to Template list pages.

I'll fix the "Template Parts" link for hybrid themes and include E2E tests to catch similar regressions sooner, but an alternative solution would be to handle this BC breakage somewhere in the router.

**Comment by youknowriad** [comment]
> an alternative solution would be to handle this BC breakage somewhere in the router.

The reason I didn't handle the path is because we now have two template lists pages. The one that shows all the templates in the frame and the one that shows all the templates in the sidebar. So there's an ambiguity about which to load.

That said, it's arguable that we could default to "browse all" but it might add some complex logic to `useSyncPathWithURL`.

**Review by youknowriad — APPROVED** [review]

**Comment by Mamaduka** [comment]
That's a good point, and I don't think we want to introduce complex logical changes in `useSyncPathWithURL` this late in the release.

Linking these pages probably isn't that useful outside of the core cases.

I'll create a core patch to fix regression for hybrid themes.

**Comment by ntsekouras** [comment]
I just cherry-picked this PR to the wp/6.2 branch to get it included in the next release: d5dbe59fea
