### PR TITLE
RTC: Fix cursor index sync with rich text formatting

### LINKED ISSUE #76057: RTC: [Engine] Cursor position mismatch with inline HTML formatting in diffWithCursor
## What?

When syncing rich-text edits via RTC, the cursor position passed to `diffWithCursor` is in rendered-text coordinates (visible characters only), but the diff operates on the serialized HTML string (which includes tags like `<strong>`, `<em>`, `<a href="...">`, etc.). This coordinate space mismatch can cause the cursor-aware diff to place insertions or deletions at the wrong position in the HTML string.

## Why?

In `mergeRichTextUpdate` (`packages/core-data/src/utils/crdt-blocks.ts`), `cursorPosition` comes from `selectionStart.offset`, which the `@wordpress/rich-text` package computes by walking the DOM and counting only visible text characters — HTML tags are not counted.

However, `diffWithCursor` compares this cursor position against offsets in the raw HTML string, where tags like `<strong>` occupy 8 additional characters. When the cursor offset points into the middle of a tag, the verification step in `tryMoveInsertionToCursor` usually catches the mismatch and falls back to the regular diff. But if the inserted character happens to match a character inside a tag at that offset (e.g., typing `s` near `<strong>`, or `/` near a closing tag), it produces a false match and splits the HTML tag, garbling the output.

### Example

- Content: `s<strong>x</strong>b` (rendered: `sxb`)
- User types `s` after the bold text → `s<strong>x</strong>sb` (rendered: `sxsb`, cursor at 3)
- `diffWithCursor` receives cursor=3, which points to position 3 in the HTML string: the `s` in `<strong>`
- `tryMoveInsertionToCursor` finds `s` === `s` → false match
- Result: `s<sstrong>x</strong>b` (garbled HTML)

## How?

Convert the cursor position from rendered-text offset to HTML-string offset before passing it to `diffWithCursor`. The conversion walks the HTML string, skipping tag characters, to map the rendered position to the correct HTML position.

## Related

Follow-up to #76049.

### PR DESCRIPTION
**Pull request by alecgeatches**
## What?

Closes https://github.com/WordPress/gutenberg/issues/76057

Currently when two users are editing in the same rich text area, adding formatting causes the other user's cursor to jump:

https://github.com/user-attachments/assets/8aeb1819-67cd-4444-b26d-c61eecfb62e1

This is because we retrieve a user's selection from `getSelectionStart()`, which returns their logical selection within text, not including formatting. However this selection offset is incorrectly anchored to the HTML `Y.Text` used by rich text attributes. That means there's a disconnect when formatting is applied. When text is bolded, `<strong>`/`</strong>` tags are added within the HTML, causing cursors later in text to jump 17 characters, and italics `<em>`/`</em>` cause a 9-character jump due to the mismatch in indexes.

In this branch we correctly translate between selection (rich text) offsets and actual HTML offsets:

https://github.com/user-attachments/assets/05142042-00e7-4694-8255-4f564ac9dcc1

## Why?

The CRDT layer stores block content as raw HTML in `Y.Text`, where a relative position index counts every character including HTML. The block editor uses rich-text offsets that count only visible text characters. These two coordinate systems were being used interchangeably, which worked by accident when no formatting changes occurred. However, when a remote user added or removed formatting, the indexes went out of sync and caused weird jumping behavior. Combined with [typing in the same rich text field](https://github.com/WordPress/gutenberg/pull/75703), this can break interaction within text if any users start to use HTML formatting.

## How?

The two main functions added to switch between text index and HTML indexes are `htmlIndexToRichTextOffset()` and `richTextOffsetToHtmlIndex()`. These go through Gutenberg's `@wordpress/rich-text` parser and avoids [hand-rolling HTML tag counting](https://github.com/WordPress/gutenberg/pull/76058). A marker character is inserted at the target position and its location is found after parsing/serializing, which gives us the index in the other coordinate system.

These conversions are applied at four boundary points where the mismatch occurs: two write paths (`block-selection-history.ts` and `crdt-user-selections.ts`) where rich-text offsets are stored into Y.Text positions, and two read paths (`crdt-selection.ts` and `post-editor-awareness.ts`) where `Y.Text` positions are resolved back into rich-text offsets. The field was also renamed from `textIndex` to `richTextOffset` for clarity on what "index" refers to.

I also added a [periodic cursor redraw](https://github.com/WordPress/gutenberg/blob/6193657df13c67e754f032a80ff6a00b453945ca/packages/editor/src/components/collaborators-overlay/overlay.tsx#L238-L252) to deal with cases where formatting changes the width of previous characters but doesn't actually affect another user's relative position:

https://github.com/user-attachments/assets/28e211e6-0a68-4470-858b-c32e90094f2a

Above, the visible user bolds a line of text, which causes another user's cursor to briefly appear in the incorrect location. Rather than listen for every formatting change and attempting a redraw, this solution allows cursors to catch-up without much performance overhead. This will also handle cases where editor content changes in other unexpected ways and allow RTC cursors and selections to automatically catch-up after a short time.

## Testing Instructions

1. Ensure RTC is enabled via Settings -> Writing -> " Enable real-time collaboration" checkbox.
1. Open a post in two tabs.
2. User 1 types a paragraph of text, e.g. `Vivamus diam purus, volutpat id auctor nec, vehicula nec eros.`
3. User 1 places their cursor somewhere in the middle of the paragraph (e.g. after "nec,").
4. Confirm that User 2 sees User 1's awareness cursor at the correct position.
5. User 2 selects a word earlier in the paragraph (e.g. "purus") and applies formatting.
6. Verify that User 1's cursor does not jump forward and remains after "nec,".
7. Verify that User 1's awareness cursor on User 2's screen also stays in the correct position and does not shift.
8. Repeat steps 5-7 with italic, strikethrough, and other inline formatting to confirm the fix is general.
9. Test with text containing HTML entities (e.g. `Tom & Jerry` or `<>`) and verify cursors behave correctly when formatting is applied near the entity.

### CODE REVIEW

**Comment by alecgeatches** [comment]
@dmsnell I'd love your review on this approach! It's not exactly what you described in https://github.com/WordPress/gutenberg/pull/76058#issuecomment-4006679068, but it uses marker characters in a similar way. Thanks!

File: packages/core-data/src/utils/crdt-utils.ts [hunk 1]
```diff
@@ -104,6 +105,125 @@ export function findBlockByClientIdInDoc(
...
+	if ( lastAmp !== -1 ) {
+		const nextSemi = html.indexOf( ';', lastAmp );
+		if (
+			nextSemi !== -1 &&
+			nextSemi >= safeIndex &&
+			nextSemi - lastAmp < 10
+		) {
+			safeIndex = lastAmp;
+		}
+	}
```
Comment (dmsnell) [inline packages/core-data/src/utils/crdt-utils.ts]: this function is a bit confusing to me, so I think I might be misunderstanding. it looks like it’s recreating the same kind of string-based HTML parsing we had before; with the assumption that `<` opens a tag and `>` closes a tag.

it also appears to traverse backwards through the HTML which is even more fraught because some text genuinely represents HTML non-text nodes in some context while not in others, something that cannot be revealed when walking backwards.

File: packages/core-data/src/utils/crdt-utils.ts [hunk 2]
```diff
@@ -104,6 +105,125 @@ export function findBlockByClientIdInDoc(
 	return findBlockByClientIdInBlocks( blockId, blocks );
 }
 
+// Candidate markers for insertion. We try each in order and pick the first
+// one that does not already appear in the text, so existing content cannot
+// collide with the marker we search for after parsing.
+const MARKER_CANDIDATES = [ '\uFFFD', '\uFFFE', '\uFFFF' ] as const;
```
Comment (dmsnell) [inline packages/core-data/src/utils/crdt-utils.ts]: this approach should work, but this is a curious set of characters to use, particularly U+FFFD which serves in so many common roles.

as non-characters, U+FFFE and U+FFFF should work, but also we can try any of the private-use area characters, the easiest being those starting at U+E000

for what reasons did you choose these characters?

Comment (alecgeatches) [reply packages/core-data/src/utils/crdt-utils.ts]: `\uFFFD` is just the classic replacement character, but I wanted to add some backups in the unlikely case real content contained it. Happy to do whatever here though, would you recommend `U+E000`-`U+E002`?

File: packages/core-data/src/utils/crdt-utils.ts (hunk 1 above)
Comment (alecgeatches) [reply packages/core-data/src/utils/crdt-utils.ts]: Thank you for reviewing, I'd love to improve this. This is intended to correct when the given `htmlIndex` is within a tag. Given:

```
some <strong>words</strong> test
```

If we receive `htmlIndex = 9`, then our marker would fall within the `<strong>` tag:

```
some <str\uFFFDong>words</strong> test
```

When we parse HTML later with `create()`, a marker in the HTML content itself could break parsing if it's mid-tag. The goal is to avoid inserting our marker character in a place that would break either the HTML tag or entities e.g. `&am\uFFFDp;`.

---

But you're right, this edge-case workaround still bakes in the assumption that we can per-character parse HTML without context. Ideally `htmlIndex` is never within a tag though. Maybe we can just ignore that case, since we're getting `htmlIndex` from another user's `richTextOffsetToHtmlIndex()` that should be correctly anchored in HTML. We also might be able to return some default value if `create()` returns invalid markup.

Open to any ideas if you have them!

File: packages/core-data/src/utils/crdt-utils.ts (hunk 2 above)
Comment (dmsnell) [reply packages/core-data/src/utils/crdt-utils.ts]: the private-use characters are for special purposes like this, contained within a system. they intentionally have no meaning and should never have meaning _between_ systems.

U+FFFD has a very specific universal meaning and a lot of texts will contain it, oftentimes by accident (because, while it should be reserved for display-only, many tools end up replacing invalid byte sequences with it anyway)

File: packages/core-data/src/utils/crdt-utils.ts (hunk 1 above)
Comment (dmsnell) [reply packages/core-data/src/utils/crdt-utils.ts]: if we’re using the marker-based approach, how are we ending up inside a tag?

the problem with using `<` and `>` like this is that is gives hardly any guarantee that it will slide in front of or behind a tag. it’s also incredibly likely that it will move markers that were already in a text node _into_ a tag.

many definitely try to parse HTML this way. we have forty years of prior art…

Comment (alecgeatches) [reply packages/core-data/src/utils/crdt-utils.ts]: > if we’re using the marker-based approach, how are we ending up inside a tag?

We're receiving these markers from other peers with possibly different CRDTs, so this was an attempt to add some edge-case detection. You're correct though, this doesn't catch "edge cases" as much as it will probably make problems with regular content to a greater degree.

Thank you for the wisdom here, it's really helpful. I'm going to modify `htmlIndexToRichTextOffset()` not to use this method for tag detection. At very least we can remove manual parsing and just fall back to some default, or maybe we can look at the output of `create()` to determine if something unexpected happened.

**Comment by alecgeatches** [comment]
@dmsnell I pushed up some changes to use private-use entities and remove the unhelpful manual HTML parsing. Currently `htmlIndexToRichTextOffset()` doesn't really care if the `htmlIndex` is invalid and I [added some pinning tests](https://github.com/WordPress/gutenberg/pull/76418/commits/fd796e23a9f76b30d51e4f33aa460dca1bd28ebb) for the current behavior.

I thought of a potential way to detect invalid HTML. We could parse the HTML once before adding the character and once after, and if the length isn't `+1`, that means a tag or something broke and it's invalid. We could potentially increment the insertion position in a loop until the result is the input length plus 1. I think this is a reasonable strategy, but it does add a lot of overhead `create()` calls and complexity to solve a problem we might not actually encounter. For now my plan is to see how this works without any correction and maybe simplicity is good enough.

Please let me know if you have any more feedback here, it's been appreciated.

File: packages/editor/src/components/collaborators-overlay/overlay.tsx [hunk 3]
```diff
@@ -68,6 +68,22 @@ export function Overlay( {
...
+	useEffect( () => {
+		if ( ! cursors.length ) {
+			return;
+		}
+		const interval = setInterval(
+			rerenderCursorsAfterDelay,
+			CURSOR_REDRAW_INTERVAL_MS
+		);
+		return () => clearInterval( interval );
+	}, [ cursors.length, rerenderCursorsAfterDelay ] );
```
Comment (dmsnell) [inline packages/editor/src/components/collaborators-overlay/overlay.tsx:88]: we should be careful with interval functions, especially if there’s any potential for long compute time. the problem is that they can stack up in the even queue and if the system experiences high load, it may not be able to run them fast enough to clear it out.

another available approach is to set a mean time between _runs_ instead of _schedulings_

```ts
let timerHandle;
const runner = () => {
	rerenderCursorsAfterDelay();
	timerHandle = setTimeout( runner, CURSOR_REDRAW_INTERVAL_MS );
};
return () => clearTimeout( timerHandle );
```

the benefit here is natural deferral of these updates when the editor is laggy and decreased pressure on the main thread. the risk is that if there’s an exception in that execution context then the timer won’t be reset. this is easy to fix by creating a light-weight scheduler on `setInterval()` whose only purpose is to ensure that the timer is set if it hasn’t been reset.

```ts
let timerHandle;
setInterval( () => {
	if ( timerHandle ) {
		return;
	}

	timerHandler = setTimeout( () => {
		timerHandle = null;
		runner();
	}, 0 );
}, CURSOR_REDRAW_INTERVAL_MS );
```

and should anyone find this intermingling ugly, there are ways to separate the recursion.

```ts
const setDelayedInterval( runner, CURSOR_REDRAW_INTERVAL_MS );
```

File: packages/core-data/src/utils/crdt-utils.ts [hunk 4]
```diff
@@ -104,6 +105,100 @@ export function findBlockByClientIdInDoc(
...
+const MARKER_CANDIDATES = [ '\uE000', '\uE001', '\uE002' ] as const;
+
+/**
+ * Pick a marker character that does not appear in `text`. Returns the marker
+ * or `null` if all candidates are present (extremely unlikely in practice).
+ *
+ * @param text The string to check for existing marker characters.
+ */
+function pickMarker( text: string ): string | null {
+	for ( const candidate of MARKER_CANDIDATES ) {
```
Comment (dmsnell) [inline packages/core-data/src/utils/crdt-utils.ts]: just a considerably less-significant thought, but at this point is there an incredible need to predefined these? if we pick a candidate from the private-use area, of which we are almost certainly able to find one (typically the first try), we could just spin on the loop. is a count of three important?

```ts
for ( let marker = 0xE000; marker <= 0xF8FF; marker++ ) {
	if ( ! text.includes( marker ) ) {
		return marker;
	}
}

return null;
```

will it matter to us if we have distant markers for the start and end of the selection? (anchor and focus, of which the “start” can be after the “end” in the document for backwards selections).

if so, this candidate selection can test for pairs and there are simple schemes like even/odd to determine anchor and focus/start and end. a RegExp could even be faster, but probably isn’t.

File: packages/editor/src/components/collaborators-overlay/overlay.tsx (hunk 3 above)
Comment (alecgeatches) [reply packages/editor/src/components/collaborators-overlay/overlay.tsx:88]: Cool pattern, and makes sense to me. Implemented in https://github.com/WordPress/gutenberg/pull/76418/changes/648b72ad5eec6743c939be615eb520ca1f89d52b.

File: packages/core-data/src/utils/crdt-utils.ts (hunk 4 above)
Comment (alecgeatches) [reply packages/core-data/src/utils/crdt-utils.ts]: There's no reason that we have exactly 3, used this pattern in https://github.com/WordPress/gutenberg/pull/76418/changes/5a6d5357bf2b011f9b92d1e0da9a395be5f99c76 but with a limit of `0x10` guesses.

Comment (dmsnell) [reply packages/core-data/src/utils/crdt-utils.ts]: nice. you noticed and accounted for the defect in my code snippet. 👏

Comment (alecgeatches) [reply packages/core-data/src/utils/crdt-utils.ts]: I figured `'\uE000'` wasn't exactly the same as `0xE000` but I did have to test to find out.

File: packages/editor/src/components/collaborators-overlay/timing-utils.ts [hunk 5]
```diff
@@ -0,0 +1,36 @@
+/**
+ * Like setInterval but measures the delay between the end of one run and the
+ * start of the next, so callbacks never stack up when the main thread is busy.
```
Comment (chriszarate) [inline packages/editor/src/components/collaborators-overlay/timing-utils.ts]: it does not appear to do this

Comment (chriszarate) [reply packages/editor/src/components/collaborators-overlay/timing-utils.ts]: but i understand it as written, maybe just update this docblock for clarity

File: packages/editor/src/components/collaborators-overlay/overlay.tsx (hunk 3 above)
Comment (chriszarate) [reply packages/editor/src/components/collaborators-overlay/overlay.tsx:88]: just noting that this function is already debounced (currently by 500ms)

File: packages/editor/src/components/collaborators-overlay/timing-utils.ts [hunk 6]
```diff
@@ -0,0 +1,36 @@
...
+ */
+export function setDelayedInterval( callback: () => void, delayMs: number ) {
+	let timerHandle: ReturnType< typeof setTimeout > | null = null;
+
+	const runner = () => {
+		callback();
+		timerHandle = setTimeout( runner, delayMs );
+	};
+
+	// Restart the runner if an exception killed it
```
Comment (chriszarate) [inline packages/editor/src/components/collaborators-overlay/timing-utils.ts]: if we're worried about an exception in the callback, why not `try / catch`?

File: packages/editor/src/components/collaborators-overlay/overlay.tsx [hunk 7]
```diff
@@ -68,6 +69,22 @@ export function Overlay( {
 		};
 	}, [ rerenderCursorsAfterDelay, rerenderHighlightsAfterDelay ] );
 
+	// Periodically recompute cursor positions to account for DOM layout
+	// changes that don't trigger awareness state updates (e.g. a collaborator
+	// applying formatting shifts text but the cursor's logical position is
+	// unchanged). Only active when remote cursors are visible.
+	const CURSOR_REDRAW_INTERVAL_MS = 10_000;
```
Comment (ingeniumed) [inline packages/editor/src/components/collaborators-overlay/overlay.tsx]: Minor: Worth pulling this outside the component to line 12?

File: packages/editor/src/components/collaborators-overlay/timing-utils.ts (hunk 5 above)
Comment (alecgeatches) [reply packages/editor/src/components/collaborators-overlay/timing-utils.ts]: I can see how "measures the delay" might not convey what I intended. I tried another go in https://github.com/WordPress/gutenberg/pull/76418/changes/7ddd2fcd56650ad4f3985ad4ad5fd86695af9167!

File: packages/editor/src/components/collaborators-overlay/timing-utils.ts (hunk 6 above)
Comment (alecgeatches) [reply packages/editor/src/components/collaborators-overlay/timing-utils.ts]: This appears to work the same, with a bit less code: https://github.com/WordPress/gutenberg/pull/76418/commits/0dd859f7324657b042cd5f7ff4d1741e2e42cc42. Good idea.

File: packages/editor/src/components/collaborators-overlay/overlay.tsx (hunk 7 above)
Comment (alecgeatches) [reply packages/editor/src/components/collaborators-overlay/overlay.tsx]: Done in https://github.com/WordPress/gutenberg/pull/76418/commits/26631e84a239a3e183ef341b67da1e546139a75c!

File: packages/editor/src/components/collaborators-overlay/timing-utils.ts (hunk 6 above)
Comment (alecgeatches) [reply packages/editor/src/components/collaborators-overlay/timing-utils.ts]: Also removed the console.log in https://github.com/WordPress/gutenberg/pull/76418/commits/9fefe8c2694ef12bb3af45335f63ab9b6019c437.

**Review by chriszarate — COMMENTED** [review]
Tested, working very well

**Review by chriszarate — APPROVED** [review]
