### PR TITLE
Fix default unit issue for tag cloud block

### LINKED ISSUE #58885: Tag cloud: if you change size unit you can't reselect PT
### Description

By default, the size option in the tag cloud block uses PT as a unit. But if you change the unit and want to change it back to PT, then PT is not available.

### Step-by-step reproduction instructions

Add a Tag cloud block.
In the settings panel, in the options "smallest size" and "largest size", change the unit.
Now open the unit option again and try to select PT.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WordPress 6.4.3. with and without Gutenberg
6.5-alpha-56966-src with and without Gutenberg

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by akasunil**
Fixed https://github.com/WordPress/gutenberg/issues/58885

## What?

Tag cloud block default size is set in PT unit, but when PT unit is not available, it vanish on unit change.

## Why?

Converting default value into first available unit.

also modified `parseQuantityAndUnitFromRawValue()` to return default unit value when match not found. Before it was returning undefined even when match isn't found.
 
## Testing Instructions
 - Add a Tag cloud block.
 - In the settings panel, in the options "smallest size" and "largest size", change the unit.

### CODE REVIEW

**Comment by akasunil** [comment]
@Mamaduka can you please review this PR ?

**Comment by carolinan** [comment]
@sunil25393 Hi. Did you explore if it was possible to make the pt unit available?

**Comment by akasunil** [comment]
@carolinan Here, the PT unit is utilized as the default font size value, and available units are obtained from the [spacing.units](https://github.com/WordPress/gutenberg/pull/59122/files#diff-52194085c13584d0f86aa62bf9b512f41abe5842b30c366e06b5c8f81c24015aL52) setting, which can be changed by the theme.

As you can see, the [twentyTwentyFour theme's spacing units](https://github.com/WordPress/twentytwentyfour/blob/trunk/theme.json#L196) do not include the PT unit. So, even if I add PT units to [this](https://github.com/WordPress/gutenberg/pull/59122/files#diff-52194085c13584d0f86aa62bf9b512f41abe5842b30c366e06b5c8f81c24015aL54) list, the problem will persist. 

To overcome this problem, I have used `getValidParsedQuantityAndUnit` to determine whether the unit is available or not. If the unit is not made available by the theme. Then we may select the first unit from the list as the default unit.

Please let me know if you have any alternative approaches.

**Comment by carolinan** [comment]
Spacing units are separate from **font size units**. If spacing units affects typography then that is a separate bug that needs to be reported and solved separately from this issue and pr.

**Comment by akasunil** [comment]
If we remove the use of [spacing.units](https://github.com/WordPress/gutenberg/pull/59122/files#diff-52194085c13584d0f86aa62bf9b512f41abe5842b30c366e06b5c8f81c24015aR53) ( as you mentioned spacing units should not be used for font sizes ), then i guess we can include PT unit in default units.

Also, we don't have global styles setting for font size units like spacing.units, so we just have to use an array of hard coded units like [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/font-size-picker/index.tsx#L39).

i'll update my PR accordingly.

File: packages/block-library/src/tag-cloud/edit.js [hunk 1]
```diff
@@ -49,10 +49,10 @@ function TagCloudEdit( { attributes, setAttributes } ) {
 		largestFontSize,
 	} = attributes;
 
-	const [ availableUnits ] = useSettings( 'spacing.units' );
 	const units = useCustomUnits( {
-		availableUnits: availableUnits || [ '%', 'px', 'em', 'rem' ],
+		availableUnits: [ 'px', 'em', 'rem', 'vw', 'vh', 'pt' ],
```
Comment (akasunil) [inline packages/block-library/src/tag-cloud/edit.js]: Added same units as we use for [font size picker](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/font-size-picker/index.tsx#L39) including PT unit. And removed use of spacing units setting for font sizes.

**Comment by akasunil** [comment]
@carolinan can you please review this PR and let me know your thoughts.

**Comment by carolinan** [comment]
Let's ping @amustaque97 and @ntsekouras to ask if there are any important reasons to why the spacing units was used for this font size control, that I may have missed. And @jasmussen who I believe requested that the pt size was removed. Original PR: https://github.com/WordPress/gutenberg/pull/37311.

**Comment by jasmussen** [comment]
Thanks for the ping, that lets me clarify this part:

> But one single recommedation I'd make is to adopt the unit-selector input field. That would both let us remove the (pt) from the label, and pick other units. Is that feasible?

I meant that allowing the unit selector would allow us to change the _label of the previous implementation_ to omit the hardcoded mention of PT:

Screenshot 2024-07-03 at 10 26 39

I don't personally mind if someone wants to use the pt unit for font sizes.

**Comment by ntsekouras** [comment]
>Let's ping @amustaque97 and @ntsekouras to ask if there are any important reasons to why the spacing units was used for this font size control, that I may have missed.

It's been a while since that [PR](https://github.com/WordPress/gutenberg/pull/37311), but I think it's because in the block's render function(dynamic) we use [wp_tag_cloud](https://developer.wordpress.org/reference/functions/wp_tag_cloud/) where the default unit is `pt`. So if we changed the default unit, it would affect all previous instances of that block..

**Comment by akasunil** [comment]
Hello, @ntsekouras I appreciate your response. Actually, the default unit is not being changed. The array of units used in the front size picker have taken the role of the spacing units settings, and the PT unit has been included in that array. PT unit support will still be available in tag cloud block.

**Comment by carolinan** [comment]
Yes the default unit should still be PT, what we are trying to solve here is that right now, on trunk, you can't switch back to PT if you select a different unit. On trunk PT is not available in the control.

File: packages/block-library/src/tag-cloud/edit.js (hunk 1 above)
Comment (ntsekouras) [reply packages/block-library/src/tag-cloud/edit.js]: It feels to me that we should always honor the spacing units and we shouldn't remove this. Having said that, since the tag cloud has this nuance with the previous default value, maybe we should just append the `pt` to the `availableUnits` in either case (spacing.units or defaults). What do you think?

Comment (carolinan) [reply packages/block-library/src/tag-cloud/edit.js]: It is not logical to me that **spacing** units are used as the **font size** unit and I would like to understand why they were used this way?

I don't think pt is used for spacing.

Comment (ntsekouras) [reply packages/block-library/src/tag-cloud/edit.js]: That's a good question!  Do we have a different theme.json setting for font size units? I searched a bit and I think not.. We should probably use the same values we use for setting font sizes in typography panel (size).

My point is, if we have such a setting and we were using the wrong one, we should honor it. I'll cc @MaggieCabrera if she can provide some feedback.

Comment (carolinan) [reply packages/block-library/src/tag-cloud/edit.js]: I vaguely remember having a discussion about font size unit block support with @t-hamano but I can't find that issue or PR now.

BTW unit support is broken in block.json https://github.com/WordPress/gutenberg/issues/47519

Comment (t-hamano) [reply packages/block-library/src/tag-cloud/edit.js]: > It is not logical to me that **spacing** units are used as the **font size** unit

I completely agree with this point, but given that theme.json doesn't support **font size** units, I think we need to respect `spacing.units` for now to maintain backward compatibility.

How about keeping the current specs but adding the `pt` unit?

```javascript
// The `pt` unit is used as the default value and is therefore
// always considered an available unit.
const units = useCustomUnits( {
availableUnits: availableUnits
	? [ ...availableUnits, 'pt' ]
	: [ '%', 'px', 'em', 'rem', 'pt' ],
} );
```

Comment (akasunil) [reply packages/block-library/src/tag-cloud/edit.js]: Thank you @t-hamano, Let me know If we all are agree with the above proposed solution, ill update the PR

Also, Shouldn't we consider having a unit setting for font size in `theme.json`?

Comment (t-hamano) [reply packages/block-library/src/tag-cloud/edit.js]: I believe this approach is the best one to maintain backward compatibility and users to reselect the `pt` unit.
allow

> Shouldn't we consider having a unit setting for font size in "theme.json"?

Of course, this is a feature improvement that should be considered in a separate PR.

**Review by ntsekouras — APPROVED** [review]
Looks good, thank you!

**Comment by carolinan** [comment]
Nik was faster :)
Thank you for working on this @akasunil. I'm glad the initial calculations were not needed.
This works well both when the theme sets spacing units with theme.json, and when it does not.

**Comment by akasunil** [comment]
Thanks @carolinan and @ntsekouras 

Just wondering, though: wouldn't it be confusing if a user removed a PT unit from theme.json yet it continued to show up on the tag cloud block? 

The initial calculations were to prevent this by setting the PT unit's default value to the first accessible unit's value.
