### PR TITLE
fix: Remove block alignment from paragraph block (fix #6476)

### LINKED ISSUE #6476: Move paragraph alignment to toolbar
We now have the alignment just in one place on the paragraph block, which is great.

alignp

The problem though is all other blocks have this by the toolbar. Let's bring this back to the toolbar and remove from the sidebar please. Like image for example has:

aligni

### PR DESCRIPTION
**Pull request by tofumatt**
## Description
Remove the block alignment control for the paragraph block. This was requested in #6476.

## How has this been tested?
Ran locally on Firefox/Chrome thus far. This is my first PR and there didn't seem to be unit tests around this file I could find, so I suspect I need to edit e2e tests.

### Before
screenshot 2018-05-01 00 32 32

### After
screenshot 2018-05-01 00 32 52

## Types of changes
Removes the block alignment from the paragraph block completely. Simplifies alignment for the block but means it must rely on a container block for layout.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by tofumatt** [comment]
I had a look at testing the `InspectorControls` (writing a test that checked for the component I removed, and then making sure it failed when removed, and just generally adding test coverage for that section of the component), but it looks like this isn't done elsewhere and I didn't want a simple change to become a rabbit hole.

I would like to find a way to test the inspector controls, but I figured for now this is still getting rid of the confusing layout control as requested in the issue, so ready for review 😄

**Comment by youknowriad** [comment]
> I would like to find a way to test the inspector controls, but I figured for now this is still getting rid of the confusing layout control as requested in the issue, so ready for review

I guess I'd personally do it by calling directly the `edit` property of the block and by adding the "InspectorControls" slot in the wrapping test component. But yeah, let's try this separately.

👍

**Review by youknowriad — APPROVED** [review]
LGTM 👍

**Comment by gziolo** [comment]
> I think we should remove the block alignment toolbar from paragraphs altogether, as I feel like these should be reserved for a container block. So you select the container to choose the layout, and you can then choose individual paragraphs inside to change the text alignment.

@jasmussen, what about `full` and `wide` alignments for Paragraph block?

**Comment by jasmussen** [comment]
Yes, per some discussion in https://github.com/WordPress/gutenberg/pull/6473#issuecomment-385883010, I think we should remove the block alignments from the paragraph. It made sense back when we had a "Cover Text" block, and it might make sense for other blocks. But the interface is not ideal, and it is especially confusing to have _two_ types of alignments on the same block.

The Blockquote with nested paragraphs _possibly_ can help define a path forward. The block alignment can be applied to the block quote itself, and text alignments can be applied to children. How we deal with paragraphs that need the same type of block alignments is a worthy challenge, though, but probably needs a different solution.

**Comment by gziolo** [comment]
@youknowriad, should `width` attribute be also removed from `attributes` and included only in the list of those deprecated. The same applies to the usage in `save` method?

**Comment by jasmussen** [comment]
CC: @mtias

**Comment by youknowriad** [comment]
@gziolo no, I noticed this too but thought we should keep it to avoid breaking existing paragraph. We don't have container blocks yet (section).

**Comment by gziolo** [comment]
My only concern is what will happen if someone set paragraph as aligned `left` or `full` and they won't be able to change that anymore. Maybe we should be more aggressive and reset it?

**Comment by jasmussen** [comment]
> My only concern is what will happen if someone set paragraph as aligned left or full and they won't be able to change that anymore.

Wouldn't that invalidate the block and add the button to convert to blocks?

**Comment by gziolo** [comment]
> Wouldn't that invalidate the block and add the button to convert to blocks?

This PR removes only the control, everything else is still there, so it won't invalidate the block.

**Comment by jasmussen** [comment]
I think that's fine. Users can edit the HTML here. 

In general, I think we shouldn't be too scared of removing features, if we feel they add confusion or complexity, especially in this beta phase.

**Comment by gziolo** [comment]
@tofumatt, can you leave comment next to `width` definition that it should be moved to the deprecated list at some point, in here: https://github.com/WordPress/gutenberg/blob/master/core-blocks/paragraph/index.js#L300 before we merge?

**Comment by tofumatt** [comment]
I can move it to the deprecated list right now if that makes sense, but otherwise I can leave the comment.

**Comment by gziolo** [comment]
As discussed, let's see if it is easy to add deprecation. If that is too much hassle, let's leave a comment and move on to other things :)

**Comment by tofumatt** [comment]
I (think) I added deprecation properly and I tested it with blocks that had the old alignment set–they continued to save/load/work.

File: core-blocks/paragraph/index.js [hunk 1]
```diff
@@ -287,7 +279,23 @@ const supports = {
 	className: false,
 };
 
+const deprecatedSchema = {
```
Comment (youknowriad) [inline core-blocks/paragraph/index.js]: I'm not sure I understand why these were extracted, from my point of view the `custom*` attributes should remain in the schema because they are still being used. The `width` attribute should not though and should only be added to the deprecated version's attributes.

**Comment by tofumatt** [comment]
Okay I think I did the deprecation right now, it's good for another look.

**Comment by tofumatt** [comment]
I got the thumbs-up for the deprecation from @youknowriad on Slack, so gonna merge this. 😄
