### PR TITLE
Fix: save custom template with non-latin slug

### LINKED ISSUE #41214: Unable to save new custom template when using none Latin characters
### Description

When you try to add new template from post settings inside the post editor, then you try to save it, it gives you a message "saving failed". I tried to investigate the problem and it seems to me that rest url is wrong, there is double // in the middle instead of one.  **This only happens with non-latin characters.**

### Step-by-step reproduction instructions

1. Go to edit post or page
2. Go to post settings > Template
3. click "new" to add new Template, and name it with none-latin characters.
4. make changes to the template and save it. 
5. see if were able to save the template.

### Screenshots, screen recording, code snippet

image
image

### Environment info

- Gutenberg  13.2.2
- Wordpresss 5.9.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
## What?

Similar to #38861
Closes #41214

Fix the error occurring in the post editor when creating a new template with non-latin slug

## Why?

In my understanding, templates and template parts don't allow non-Latin characters as a slug. `cleanForSlug()` function preserves non-latin characters, so an error occurs.

## How?

Use the same logic as [here](https://github.com/WordPress/gutenberg/blob/bdb16796eb85051b9d5d7b00fcb773973642a5e7/packages/edit-site/src/components/add-new-template/add-custom-generic-template-modal-content.js#L31-L33).

In the future, we may want to allow non-Latin characters.

## Testing Instructions

- Open the post editor
- Post sidebar > Post tab > Click the button next to the Template label
- Click the Create new template button
- Create custom template with non-latin characters (Example: テンプレート, 😄😄😄)
- Check the error message logged in the bowser console
- Access phpMyAdmin: http://localhost:9000/index.php?route=/sql&pos=0&db=wordpress&table=wp_posts
- Confirm that the template has been saved with the `wp-custom-template` slug
- If you create a template again with non-latin characters, the slug will be `wp-custom-template-2`.

### CODE REVIEW

**Comment by Mamaduka** [comment]
I wonder if there's an actual use case for non-Latin template slugs, but it could be a limitation of using custom template titles to generate slugs instead of having a separate input.

P.S. I'm not dissmissing non-Latin languages; my native Georgian is one, but I never liked using it for slugs and URLs 😅

**Comment by t-hamano** [comment]
@Mamaduka Thanks for the feedback!

> it could be a limitation of using custom template titles to generate slugs instead of having a separate input.

Yes, ideally, We may need to prepare the additional input field for the slug. (Related discussion: https://github.com/WordPress/gutenberg/pull/65568#issuecomment-2370808049)

This PR just makes the logic in the post editor consistent with the logic in the site editor. It might be a temporary fix in some sense.

File: packages/editor/src/components/post-template/create-new-template-modal.js [hunk 1]
```diff
@@ -92,7 +96,7 @@ export default function CreateNewTemplateModal( { onClose } ) {
 			] );
 
 		const newTemplate = await createTemplate( {
-			slug: cleanForSlug( title || DEFAULT_TITLE ),
+			slug: 'wp-custom-template-' + kebabCase( title || DEFAULT_TITLE ),
```
Comment (Mamaduka) [inline packages/editor/src/components/post-template/create-new-template-modal.js]:
```suggestion
			slug: kebabCase( title || DEFAULT_TITLE ) || 'wp-custom-template',
```

This would avoid prefixing the custom template when the title is with Latic chars. What do you think?

**Review by Mamaduka — APPROVED** [review]
Left a minor note, but besides that, the fix works as expected ✅ 

Thank you, @t-hamano!

File: packages/editor/src/components/post-template/create-new-template-modal.js (hunk 1 above)
Comment (t-hamano) [reply packages/editor/src/components/post-template/create-new-template-modal.js]: It's a good idea, because the template part creation uses a similar logic:

https://github.com/WordPress/gutenberg/blob/f12ba660ed2fb14766f81716fee7fd0d1ce10103/packages/fields/src/components/create-template-part-modal/utils.js#L66-L68

In f12ba660ed2fb14766f81716fee7fd0d1ce10103, I've also updated the logic in the site editor for consistency, what do you think?

Comment (Mamaduka) [reply packages/editor/src/components/post-template/create-new-template-modal.js]: Thanks, @t-hamano!
