### PR TITLE
Fix custom patterns console error

### LINKED ISSUE #51873: Block Inserter: Error displayed in browser console when opening custom pattern categories
### Description

Note: I initially tried to resolve this issue with #51870, but since I could not find an ideal solution, I am submitting it here as an issue.

When opening a custom pattern category from the main block inserter, an error appears in the browser console.

248545202-39a57a49-3806-45bb-a3fd-75327145fe89

<details><summary>Log</summary>

```
react_devtools_backend_compact.js:2367 Warning: Encountered two children with the same key, `core/block`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    at div
    at Comp (http://localhost:8888/wp-content/plugins/gutenberg/build/components/index.min.js?ver=ce65b624bfa003890a5d:72773:26)
    at BlockPatternList (http://localhost:8888/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=a7304d534910f4ac477a:19258:3)
    at div
    at BlockPatternsCategoryPanel (http://localhost:8888/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=a7304d534910f4ac477a:37924:3)
    at div
    at BlockPatternsCategoryDialog (http://localhost:8888/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=a7304d534910f4ac477a:37898:3)
    at div
    at InserterMenu (http://localhost:8888/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=a7304d534910f4ac477a:39881:3)
    at InserterLibrary (http://localhost:8888/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=a7304d534910f4ac477a:38984:3)
    at div
    at div
    at InserterSidebar (http://localhost:8888/wp-content/plugins/gutenberg/build/edit-site/index.min.js?ver=dccd84a46a5e6812f016:15682:67)
    at div
    at NavigableRegion (http://localhost:8888/wp-content/plugins/gutenberg/build/edit-site/index.min.js?ver=dccd84a46a5e6812f016:29252:3)
    at div
    at div
    at div
    at InterfaceSkeleton (http://localhost:8888/wp-content/plugins/gutenberg/build/edit-site/index.min.js?ver=dccd84a46a5e6812f016:29006:3)
    at BlockContextProvider (http://localhost:8888/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=a7304d534910f4ac477a:13462:3)
    at EntityProvider (http://localhost:8888/wp-content/plugins/gutenberg/build/core-data/index.min.js?ver=0335a67734cd7ff3e5b9:2617:3)
    at EntityProvider (http://localhost:8888/wp-content/plugins/gutenberg/build/core-data/index.min.js?ver=0335a67734cd7ff3e5b9:2617:3)
    at Editor (http://localhost:8888/wp-content/plugins/gutenberg/build/edit-site/index.min.js?ver=dccd84a46a5e6812f016:6109:3)
    at div
    at MotionComponent (http://localhost:8888/wp-content/plugins/gutenberg/build/components/index.min.js?ver=ce65b624bfa003890a5d:89145:65)
    at div
    at MotionComponent (http://localhost:8888/wp-content/plugins/gutenberg/build/components/index.min.js?ver=ce65b624bfa003890a5d:89145:65)
    at Resizable (http://localhost:8888/wp-content/plugins/gutenberg/build/components/index.min.js?ver=ce65b624bfa003890a5d:20997:28)
    at UnforwardedResizableBox (http://localhost:8888/wp-content/plugins/gutenberg/build/components/index.min.js?ver=ce65b624bfa003890a5d:55985:3)
    at ResizableFrame (http://localhost:8888/wp-content/plugins/gutenberg/build/edit-site/index.min.js?ver=dccd84a46a5e6812f016:14731:3)
    at ErrorBoundary (http://localhost:8888/wp-content/plugins/gutenberg/build/edit-site/index.min.js?ver=dccd84a46a5e6812f016:6270:5)
    at div
    at MotionComponent (http://localhost:8888/wp-content/plugins/gutenberg/build/components/index.min.js?ver=ce65b624bfa003890a5d:89145:65)
    at div
    at div
    at div
    at Layout (http://localhost:8888/wp-content/plugins/gutenberg/build/edit-site/index.min.js?ver=dccd84a46a5e6812f016:12334:100)
    at RouterProvider (http://localhost:8888/wp-content/plugins/gutenberg/build/router/index.min.js?ver=0f50332f42b79121e4e2:183:3)
    at GlobalStylesProvider (http://localhost:8888/wp-content/plugins/gutenberg/build/edit-site/index.min.js?ver=dccd84a46a5e6812f016:6870:3)
    at SlotFillProvider (http://localhost:8888/wp-content/plugins/gutenberg/build/components/index.min.js?ver=ce65b624bfa003890a5d:57903:3)
    at SlotFillProvider (http://localhost:8888/wp-content/plugins/gutenberg/build/components/index.min.js?ver=ce65b624bfa003890a5d:58326:5)
    at Provider (http://localhost:8888/wp-content/plugins/gutenberg/build/components/index.min.js?ver=ce65b624bfa003890a5d:58258:3)
    at div
    at ShortcutProvider (http://localhost:8888/wp-content/plugins/gutenberg/build/keyboard-shortcuts/index.min.js?ver=86111e37c161eaba276a:41:87)
    at App (http://localhost:8888/wp-content/plugins/gutenberg/build/edit-site/index.min.js?ver=dccd84a46a5e6812f016:4143:67)
overrideMethod @ react_devtools_backend_compact.js:2367
printWarning @ react-dom.js?ver=18:73
error @ react-dom.js?ver=18:47
warnOnInvalidKey @ react-dom.js?ver=18:15303
reconcileChildrenArray @ react-dom.js?ver=18:15340
reconcileChildFibers @ react-dom.js?ver=18:15831
reconcileChildren @ react-dom.js?ver=18:19184
updateHostComponent @ react-dom.js?ver=18:19934
beginWork @ react-dom.js?ver=18:21628
beginWork$1 @ react-dom.js?ver=18:27436
performUnitOfWork @ react-dom.js?ver=18:26567
workLoopSync @ react-dom.js?ver=18:26476
renderRootSync @ react-dom.js?ver=18:26444
performConcurrentWorkOnRoot @ react-dom.js?ver=18:25748
workLoop @ react.js?ver=18:2653
flushWork @ react.js?ver=18:2626
performWorkUntilDeadline @ react.js?ver=18:2920
queue.<computed> @ wp-polyfill.js?ver=3.15.0:1977
run @ wp-polyfill.js?ver=3.15.0:1953
listener @ wp-polyfill.js?ver=3.15.0:1964
```

</details> 

### Step-by-step reproduction instructions

- Create a non-synced pattern.
- Open the main block inserter and open "Custom patterns" from the Patterns tab.
- Confirm that errors are output to the browser console.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/47e7b566-5fe5-4205-8e5e-bfe1bec039e6

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by glendaviesnz**
## What?
Fixes console error when browsing `Custom patterns` in the inserter patterns panel.

## Why?
An alternative fix to #51877 for the following issues.
Fixes: #51873 and #51872

## How?
If the pattern is a `core/block` sets the pattern `name` to `id`.

Includes a larger refactor compared to #51877 based on feedback there. Rather than trying to combined patterns and reusable blocks in components, instead moves to doing so in any pattern related selectors.

## Testing Instructions
For #51873
- Create a non-synced pattern.
- Open the main block inserter and open "Custom patterns" from the Patterns tab.
- Confirm that no errors are output to the browser console.

For #51872 
- Register two patterns with Synced turned off from the Library menu in the Site Editor.
- Open the main block inserter.
- Click Patterns tab.
- Click Custom patterns category.
- Two patterns should appear correctly.
- Switch to other categories.
- Make sure the custom patterns do not appear in other categories.
- Return to Custom patterns category.
- Make sure the number of custom patterns has not increased to three.
- Repeat to switch categories.
- Each iteration check the number of custom patterns has not increased.

## Screenshots or screencast 
Before:

https://github.com/WordPress/gutenberg/assets/54422211/47e7b566-5fe5-4205-8e5e-bfe1bec039e6

https://github.com/WordPress/gutenberg/assets/54422211/2d14f46b-fc0a-4f41-bf04-b486cd17f75e

After:

https://github.com/WordPress/gutenberg/assets/3629020/04a9de17-26c9-4006-9ad6-e7483be6f89c

https://github.com/WordPress/gutenberg/assets/3629020/a2282831-4bdb-4280-927e-baf773c14919

### CODE REVIEW

File: packages/block-editor/src/store/selectors.js [hunk 1]
```diff
@@ -2052,6 +2042,20 @@ export const getInserterItems = createSelector(
 					.map( buildReusableBlockInserterItem )
 			: [];
 
+		if ( syncStatus === 'unsynced' ) {
+			return reusableBlockInserterItems;
+		}
```
Comment (talldan) [inline packages/block-editor/src/store/selectors.js]: In hindsight, there should have been some previous feedback against the addition of the `sync_status` argument to this selector.

With this change, it feels like a good idea to go ahead and remove it. The `unsynced` patterns could be returned by a new private selector.

edit: I tried something out in https://github.com/WordPress/gutenberg/pull/51955, which is now merged into this PR.

File: packages/block-editor/src/components/inserter/block-patterns-tab.js [hunk 2]
```diff
@@ -208,21 +165,15 @@ export function BlockPatternsCategoryPanel( {
...
-		category.name === 'reusable'
-			? filteredUnsyncedPatterns
-			: currentCategoryPatterns;
-	const currentShownPatterns = useAsyncList( patterns );
+
+	const categoryPatternsList = useAsyncList( currentCategoryPatterns );
 
 	// Hide block pattern preview on unmount.
-	useEffect( () => () => onHover( null ), [] );
+	useEffect( () => () => onHover( null ), [ onHover ] );
```
Comment (kevin940726) [inline packages/block-editor/src/components/inserter/block-patterns-tab.js]: This might be a bit dangerous since we didn't require `onHover` to be a stable function instance. Which means someone might accidentally pass in an unmemoized function and trigger this effect every render.

We might want to:
1. Use a ref to create a (semi-)stable reference to the function
2. Ignore the eslint warning and add comment above explaining why.

**Review by kevin940726 — APPROVED** [review]
Code looks good to me! Only a small suggestion but that's not blocking 👍

File: packages/block-editor/src/store/selectors.js [hunk 3]
```diff
@@ -2082,7 +2083,7 @@ export const getInserterItems = createSelector(
 			{ core: [], noncore: [] }
 		);
 		const sortedBlockTypes = [ ...coreItems, ...nonCoreItems ];
-		return [ ...sortedBlockTypes, ...reusableBlockInserterItems ];
+		return [ ...sortedBlockTypes, ...syncedPatternInserterItems ];
```
Comment (youknowriad) [inline packages/block-editor/src/store/selectors.js:2086]: Does it still make sense to keep the "reusable blocks" in this selector, now that they're supposed to be treated as a pattern instead (and are part of the other selector)?

**Review by youknowriad — COMMENTED** [review]
I didn't do much testing but this looks good to me.

File: packages/block-editor/src/store/selectors.js (hunk 3 above)
Comment (glendaviesnz) [reply packages/block-editor/src/store/selectors.js:2086]: Currently, the synced blocks still appear in the quick inserter list so are needed here. We can pull in from another selector of course,  but there are some inconsistencies with when/where the different patterns appear which need to be sorted out, [eg.](https://github.com/WordPress/gutenberg/issues/51945) so I suggest we leave this as is for this PR and circle back once we have finalised exactly how/when the different sync status types will be listed.

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the update/wp6-3-beta3 branch to get it included in the next release: db15884623
