### PR TITLE
Fix aria-checked attribute not set for plugin settings buttons in Options dropdown

### LINKED ISSUE #65666: Bug: `aria-checked` is not set on the Plugin settings buttons in Options menu
### Description

The pinned plugin buttons at the top toolbar have the `aria-pressed` and `aria-expanded` attributes denoting whether the corresponding plugin section is open or not.
But, that is not the case with the same buttons in Options menu (3 dots).

There is no indication for folks with assistive technology that the corresponding sidebar is already open.

### Step-by-step reproduction instructions

- Install a plugin that adds a sidebar, e.g. Jetpack
- Click on the options menu (3 dots)
- Inspect the plugin settings button
- You can see the `role` is set to `menuitemcheckbox` but there is no `aria-checked` attribute

### Screenshots, screen recording, code snippet

image

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by manzoorwanijk**
## What?

It fixes the a11y issue with plugin buttons in the options menu in the post editor where there is no indication of whether the plugin sidebar is already open or not.

## Why?

Fixes #65666 

## How?

It updates `ComplementaryAreaToggle` to pass `aria-checked` if the role is set to `menuitemcheckbox` or `menuitemradio`

## Testing Instructions
- Install a plugin that adds a plugin menu/sidebar, e.g. Jetpack
- Click on the options menu (3 dots)
- Inspect the plugin settings button
- Confirm that `aria-checked` attribute is set correctly

## Screenshots or screencast 

image

### CODE REVIEW

File: packages/interface/src/components/complementary-area-toggle/index.js [hunk 1]
```diff
@@ -35,6 +35,13 @@ function ComplementaryAreaToggle( {
 		<ComponentToUse
 			icon={ selectedIcon && isSelected ? selectedIcon : icon }
 			aria-controls={ identifier.replace( '/', ':' ) }
+			// Make sure aria-checked matches spec https://www.w3.org/TR/wai-aria-1.1/#aria-checked
+			aria-checked={
+				props.role === 'menuitemcheckbox' ||
+				props.role === 'menuitemradio'
+					? isSelected
+					: undefined
+			}
```
Comment (manzoorwanijk) [inline packages/interface/src/components/complementary-area-toggle/index.js]: This is the same approach used in

https://github.com/WordPress/gutenberg/blob/8c5a0b6a4f5e0802d0c84d1f8e6e4934c7a449b3/packages/components/src/menu-item/index.tsx#L60-L65

**Comment by manzoorwanijk** [comment]
I wanted to add unit tests for that case but the component doesn't seem to have any tests at all.

We can cover that case when we add tests to this component.

**Review by Mamaduka — APPROVED** [review]
Makes sense. Thank you, @manzoorwanijk!

File: packages/interface/src/components/complementary-area-toggle/index.js (hunk 1 above)
Comment (ciampo) [reply packages/interface/src/components/complementary-area-toggle/index.js]: Since this component is more generic than `MenuItem`, should we check for all of the roles are compatible with `aria-checked` ? Ie. `checkbox`, `option`, `radio`, `switch`, `menuitemcheckbox`, `menuitemradio`, `treeitem` ? ([source](https://www.w3.org/TR/wai-aria-1.1/#aria-checked))

Comment (Mamaduka) [reply packages/interface/src/components/complementary-area-toggle/index.js]: I think the component rendered by plugins will always be `MenuItem`. See:

https://github.com/WordPress/gutenberg/blob/69efbca3ba4522b9b11c56a5e517d123fe9a9071/packages/interface/src/components/complementary-area-more-menu-item/index.js#L13-L50

Comment (manzoorwanijk) [reply packages/interface/src/components/complementary-area-toggle/index.js]: Updated. Thanks.

Comment (ciampo) [reply packages/interface/src/components/complementary-area-toggle/index.js]: > I think the component rendered by plugins will always be `MenuItem`

That's true, but `<ComplementaryAreaToggle />` is a generic component that technically can be rendered `as` anything, and therefore I don't think that checking for more roles can do any harm in this case

**Review by ciampo — APPROVED** [review]
LGTM 🚀

**Comment by sirreal** [comment]
Hmm… the flow to cherry-pick this failed:

https://github.com/WordPress/gutenberg/actions/runs/11232232902/job/31223400904

**Comment by cbravobernal** [comment]
I just cherry-picked this PR to the wp/6.7 branch to get it included in the next release: https://github.com/WordPress/gutenberg/commit/381ada5240aa84c9331e22e3b32c576a6dfb7f0f
