### PR TITLE
Pages DataViews: Fix content preview field after global styles refactor

### LINKED ISSUE #73139: Pages DataView broken when content preview was enabled
#73064 removed the ability to swap from featured image to a 'content preview' for the `mediaField` in the Pages DataView. I had that option enabled, and since #73064 merged I can no longer access the Pages DataView at all.
 
Here's the console error:

Screenshot 2025-11-10 at 09 56 00

cc @youknowriad

### PR DESCRIPTION
**Pull request by youknowriad**
closes #73139

## What?

Fix the content preview field on pages dataviews. useGlobalStyle hook has been removed and was still being used in a field.

### CODE REVIEW

**Comment by jameskoster** [comment]
This fixed a bug I was seeing, thanks!

There's no option to show the Featured image as the `mediaField` now though, is that intended? Loading the full preview is quite slow, and doesn't work particularly well in Table layout.

**Comment by youknowriad** [comment]
> There's no option to show the Featured image as the mediaField now though, is that intended?

That was an unintended debugging change sorry I'll revert that part :)

File: packages/editor/src/components/global-styles/hooks.js [hunk 1]
```diff
@@ -188,8 +188,8 @@ export function useGlobalStyles() {
 /**
  * Hook to get a style value from global styles
  *
- * @param {string} path      Style path (e.g., 'color.background')
- * @param {string} blockName Optional block name
+ * @param {string}  path      Style path (e.g., 'color.background')
+ * @param {string=} blockName Optional block name
```
Comment (andrewserong) [inline packages/editor/src/components/global-styles/hooks.js:192]: Tiniest of tiny nits: is this meant to be a `?`? (Same with the doc comment for `useSetting`)

Comment (andrewserong) [reply packages/editor/src/components/global-styles/hooks.js:192]: Ah, ignore me, I just wasn't familiar with this syntax 😄

Comment (youknowriad) [reply packages/editor/src/components/global-styles/hooks.js:192]: no `=` is actually better because TS can understand that is optional. I think TS doesn't understand `?`

Comment (andrewserong) [reply packages/editor/src/components/global-styles/hooks.js:192]: Good to know, thanks! TIL

**Review by andrewserong — APPROVED** [review]
I wasn't able to switch to the content preview manually (possibly related to this comment: https://github.com/WordPress/gutenberg/pull/73064/files#r2511053514) so hard-coded it in locally to test. LGTM 👍
