### PR TITLE
RichText: don't use DOM to add line padding

### LINKED ISSUE #13982: Weird backspace behavior in Firefox
## Issue description
Pressing <kbd>Backspace</kbd> on empty lines has some weird behavior in Firefox.
firefox-backspace-weirdness

## Steps to reproduce
1. Insert a Paragraph block.
2. Type a single character.
3. Press <kbd>Backspace</kbd>.
4. Notice that the Paragraph now has 2 lines.
5. Type two characters in the first line.
6. Move focus to the second line.
7. Press <kbd>Backspace</kbd> again.
8. Notice that both the second line and the last character of the first line are removed.

This bug also occurs with other blocks that use RichText.

## Testing environment
 - OS: Antergos Linux
 - Browser: Firefox Developer Edition 66.0b8
 - WordPress: 5.0.3
 - Gutenberg: 5.1 (the bug also occurred in 5.0... possibly earlier)

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #13982 and #7630. Blocks #13838.

* It reduces complexity in `insertLineBreak`, which would no longer have to insert two line breaks when at the end of a line. This can lead to strange behaviour: you can never really get rid anymore of this second line break. With an "invisible" line break already there, there's no need for it any longer.
* Reduces complexity in adding the padding. Previously it was only added for empty lines and we used the DOM for it. Now we use `toTree` for it.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by iseulde** [comment]
@gziolo I consider this to be a bug.

**Comment by gziolo** [comment]
I applied it based on the parent issue:)

File: packages/dom/src/dom.js [hunk 1]
```diff
@@ -134,9 +134,21 @@ export function isHorizontalEdge( container, isReverse ) {
...
+		// `<p>test<br></p>` looks the same as `<p>test</p>`.
+		while (
+			next && (
+				( next.nodeType === TEXT_NODE && next.data === '' ) ||
+				( ! isReverse && next.nodeName === 'BR' && ! hadBR )
+			)
+		) {
+			if ( ! isReverse && next.nodeName === 'BR' ) {
+				hadBR = true;
+			}
```
Comment (iseulde) [inline packages/dom/src/dom.js]: I wonder if this can be written any better.

File: packages/editor/src/components/rich-text/index.js [hunk 2]
```diff
@@ -497,15 +497,7 @@ export class RichText extends Component {
 			return;
 		}
 
-		const empty = this.isEmpty();
-
-		// It is important to consider emptiness because an empty container
-		// will include a padding BR node _after_ the caret, so in a forward
-		// deletion the isHorizontalEdge function will incorrectly interpret the
-		// presence of the BR node as not being at the edge.
-		const isEdge = ( empty || isHorizontalEdge( this.editableRef, isReverse ) );
```
Comment (iseulde) [inline packages/editor/src/components/rich-text/index.js]: This is no longer needed with the changes to `isHorizontalEdge`. It's now generalised. `isHorizontalEdge` should return true for the visual edge (you can never reach empty text nodes or trailing BR elements), not for the true DOM edge.

File: packages/dom/src/dom.js [hunk 3]
```diff
@@ -134,9 +134,21 @@ export function isHorizontalEdge( container, isReverse ) {
 
 	while ( node !== container ) {
 		let next = node[ `${ order }Sibling` ];
+		let hadBR;
+
+		// Skip over empty text nodes and at most one BR element if not checking
+		// the reverse. One BR element at the end is ok as it is invisible.
+		// `<p>test<br></p>` looks the same as `<p>test</p>`.
```
Comment (iseulde) [inline packages/dom/src/dom.js]: Note that we would have to fix this issue _regardless_ of whether or not we add the trailing and padding `<br>` element. When inserting a double line break at the end of line (two are needed to see a new line), and you continue to write, you also end up with a trailing line break (which will wrongly be saved). `isHorizontalEdge` also requires this fix in that case.

**Comment by iseulde** [comment]
This PR is ready for review now.

**Comment by youknowriad** [comment]
This seems to close #14114 for me too :)

**Review by youknowriad — APPROVED** [review]
This works great in my testing. It's hard to test everything but the more we have a "state based" approach instead of "dom based" one, the better is for browser compatibility...

**Comment by ellatrix** [comment]
Thanks @youknowriad! This one also brings us one step closer to using React for all the rich text content too :)
