### PR TITLE
Site Editor: Fix selected featured image when opening media library

### LINKED ISSUE #59768: Featured Image in site editor is not selected when opening media library
With our unification efforts for site and post editor the featured image panel is reused now in both editors. The featured image panel in site editor results in showing an extra empty thumbnail when opening the media library.

https://github.com/WordPress/gutenberg/assets/16275880/384679c5-94fc-48ff-9dfa-1ee5a2f11c07

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/59768

With our unification efforts for site and post editor the featured image panel is reused now in both editors. The featured image panel in site editor results in showing an extra empty thumbnail when opening the media library.

It turns out it all starts with `wp_enqueue_media` where in post editor we pass the proper post id, which is responsible for many many things, [including setting options](https://github.com/ntsekouras/wordpress-develop/blob/trunk/src/wp-includes/media.php#L4763) for the [proper selection too](https://github.com/ntsekouras/wordpress-develop/blob/trunk/src/js/media/controllers/featured-image.js#L107). I don't think that would be the way for site editor as the script loads once and in site editor we update the `postId` without reloading.

In my approach I update the needed settings when we open the media library modal client side.

## Testing Instructions
1. In a page in site editor verify that the featured image flow works as expected(proper selection, update, removal)
2. Observe that in post editor everything keeps working as expected.

### Before

https://github.com/WordPress/gutenberg/assets/16275880/22529c4c-dba1-46ac-b2fc-5d952a838d97

### After

https://github.com/WordPress/gutenberg/assets/16275880/90227fd2-251c-4cb8-9b35-7d2423da2f7c

### CODE REVIEW

File: packages/media-utils/src/components/media-upload/index.js [hunk 1]
```diff
@@ -300,19 +300,34 @@ class MediaUpload extends Component {
...
+			editing: featuredImageId,
 		} );
 		wp.media.frame = this.frame;
+		// In order to select the current featured image when opening
+		// the media library we have to set the appropriate settings.
+		// Currently they are set in php for the post editor, but
+		// not for site editor.
+		wp.media.view.settings.post = {
+			...wp.media.view.settings.post,
+			id: postId,
```
Comment (youknowriad) [inline packages/media-utils/src/components/media-upload/index.js]: postId is a new prop right? I'm thinking that maybe in some flows, the postId is not passed properly to the component and in which case, we may want to keep the globally applied one no?

Comment (youknowriad) [reply packages/media-utils/src/components/media-upload/index.js]: Also should we check other `<MediaUpload` usage in the site editor to check whether we might be missing the postId. For instance uploading regular images while editing a post in the post editor marks the image as attached to the post, but it might not be the case in the site editor. (I'm assuming this latest part is not specific to 6.5 though)

Comment (ntsekouras) [reply packages/media-utils/src/components/media-upload/index.js]: Makes sense and the complexity in those flows in core is big. I removed the postId for now, since the changes are specific to the featured image flow(`unstableFeaturedImageFlow`) and the featured image prop is enough for proper selection.

File: packages/media-utils/src/components/media-upload/index.js [hunk 2]
```diff
@@ -300,19 +300,28 @@ class MediaUpload extends Component {
...
+			editing: featuredImageId,
 		} );
 		wp.media.frame = this.frame;
+		// In order to select the current featured image when opening
+		// the media library we have to set the appropriate settings.
+		// Currently they are set in php for the post editor, but
+		// not for site editor.
+		wp.media.view.settings.post = {
+			...wp.media.view.settings.post,
+			featuredImageId: featuredImageId || -1,
```
Comment (youknowriad) [inline packages/media-utils/src/components/media-upload/index.js:323]: Now the question, what happens when you open the media library for featured image then you open it for a regular image. do we need to `unset` this global property? What will be its impact otherwise?

Comment (ntsekouras) [reply packages/media-utils/src/components/media-upload/index.js:323]: From what I understood from the code this prop is used for the featured image flow and would not affect anything else. It seems the flow for featured image in wp.media fine tunes some things under the hood, like `single selection`,  confirm button to have `set featured image`, etc..

**Review by youknowriad — APPROVED** [review]

**Comment by youknowriad** [comment]
This is a regression introduced during the 6.5 cycle, so let's include in RC2.

**Comment by getdave** [comment]
I just manually cherry-picked this PR to the pick/wp-65-rc-2 branch to get it included in the next release

https://github.com/WordPress/gutenberg/pull/59756
