### PR TITLE
Check for allowed blocks recursively in patterns

### LINKED ISSUE #23275: Patterns should not display if their blocks are not allowed
**Describe the bug**
In the current version of Gutenberg (8.3.0) and several earlier versions, block patterns display even if the blocks they are composed of are not "allowed" on the post type (via the `allowed_block_types` filter). Patterns should be hidden if they are composed of disallowed blocks.

**To reproduce**
1. Create a post type
2. Use `allowed_block_types` filter to limit blocks down to one or two
3. Observe patterns displaying

**Expected behavior**
Patterns should only display if all their constituent blocks are available.

**Screenshots**
Screen Shot 2020-06-18 at 8 58 18 AM

### PR DESCRIPTION
**Pull request by david-szabo97**
Fixes https://github.com/WordPress/gutenberg/issues/23275

## Description
Currently, patterns show up in the inserter even if they contain a block that's not on the allowed blocks list. Blocks aren't checked recursively in the patterns, only top level blocks. Even though they show up, we can't insert them since the blocks are disallowed. This PR checks recursively for disallowed blocks.

A new (private) selector is introduced: `getAllAllowedPatterns`. This intermediary function memoizes the available allowed patterns. This is used to avoid iterating over patterns that contain disallowed blocks and to avoid parsing all the patterns every time we call the `__experimentalGetAllowedPatterns` with a different `clientId`.

We use "Stage I" parser here for performance reasons. See 
https://github.com/WordPress/gutenberg/pull/30366#issuecomment-814225001
https://github.com/WordPress/gutenberg/pull/30366#issuecomment-832720472

**Why don't we use `canInsertBlockType` instead of `checkAllowListRecursive`?**
Recursively checking all blocks with `canInsertBlockType` every time we select a different block would have a huge performance impact. That's why we only check top level blocks with `canInsertBlockType` and the nested ones with `checkAllowListRecursive`.

## How has this been tested?
1. Open Post Editor
2. Open global inserter -> Patterns
3. Search for "Contact Information" pattern
4. Make sure it shows up
5. Open settings dropdown -> Block Manager
6. Now disable "Social Icons" block 
7. Open global inserter -> Patterns
8. Search for "Contact Information" pattern
9. Make sure it doesn't show up anymore

## Types of changes
Bug Fix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-editor/src/store/selectors.js [hunk 1]
```diff
@@ -1798,12 +1798,59 @@ export const __experimentalGetParsedPattern = createSelector(
...
+				const block = blocksQueue.shift();
+				const isBlockAllowedInEditor = checkAllowList(
+					allowedBlockTypes,
+					block.name,
+					true
+				);
+				if ( ! isBlockAllowedInEditor ) {
+					return false;
+				}
+				block.blocks?.forEach( ( innerBlock ) => {
```
Comment (ntsekouras) [inline packages/block-editor/src/store/selectors.js]:
```suggestion
				block.innerBlocks?.forEach( ( innerBlock ) => {
```

File: packages/block-editor/src/store/selectors.js [hunk 2]
```diff
@@ -1798,12 +1798,59 @@ export const __experimentalGetParsedPattern = createSelector(
 		if ( ! pattern ) {
 			return null;
 		}
+
+		const { allowedBlockTypes } = getSettings( state );
+
+		const blocks = parse( pattern.content );
+		const isAllowed = ( () => {
```
Comment (ntsekouras) [inline packages/block-editor/src/store/selectors.js]: Let's remove the IIFE here.

File: packages/block-editor/src/store/selectors.js [hunk 3]
```diff
@@ -1798,12 +1798,59 @@ export const __experimentalGetParsedPattern = createSelector(
...
-			blocks: parse( pattern.content ),
+			blocks,
+			isAllowed,
 		};
 	},
-	( state ) => [ state.settings.__experimentalBlockPatterns ]
+	( state ) => [
+		state.settings.__experimentalBlockPatterns,
+		state.settings.allowedBlockTypes,
+		state.settings.templateLock,
```
Comment (ntsekouras) [inline packages/block-editor/src/store/selectors.js]: Why do we need `templateLock` as a dependency?

File: packages/block-editor/src/store/selectors.js [hunk 4]
```diff
@@ -1798,12 +1798,59 @@ export const __experimentalGetParsedPattern = createSelector(
...
+	]
+);
+
+export const __experimentalGetAvailableParsedPatterns = createSelector(
```
Comment (ntsekouras) [inline packages/block-editor/src/store/selectors.js]: Why do we need this intermediary function?

**Review by ntsekouras — COMMENTED** [review]
In general, besides the recursion for innerBlocks that wasn't taken into account this solution seems to align with my previous commit here: https://github.com/WordPress/gutenberg/pull/30300/commits/48b703fb53bcc497777e3c65a979a00a4d87379a.

This was only there because `__experimentalGetParsedPattern` is called in `BlockPreview`. The `allowed` should be checked with `canInsertBlockType` I think. The problem though is that `canInsertBlockType` uses information from the state, that the parsed patterns are not in :) 

Finally in `__experimentalGetAllowedPatterns` we still check for top level blocks only. `canInsertBlockType` makes more checks besides the `allowedBlockTypes`, based on the provided `rootClientId`.

A bit confusing, no 😄

File: packages/block-editor/src/store/selectors.js [hunk 5]
```diff
@@ -1798,12 +1798,47 @@ export const __experimentalGetParsedPattern = createSelector(
 		if ( ! pattern ) {
 			return null;
 		}
+
+		const blocks = parse( pattern.content );
+		const { allowedBlockTypes } = getSettings( state );
+		let isAllowed = isBoolean( allowedBlockTypes )
```
Comment (ntsekouras) [inline packages/block-editor/src/store/selectors.js]: I think it was more clear before. I think you should just declare the previous IIFE into a separate function and call it - that was my intent for the IIFE comment.

Also now it will loop through blocks even if `allowedBlockTypes` is boolean and `true`.

**Review by ntsekouras — COMMENTED** [review]
Hey David, this looks good to me and it might the time to update PR's description, add some tests probably and I was wondering if we can have some performance checks.

File: packages/e2e-tests/plugins/allowed-patterns.php [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+		),
+		'content' => '<!-- wp:heading --><h2>Hello!</h2><!-- /wp:heading -->',
+	)
+);
+
+register_block_pattern(
+	'test-allowed-patterns/lone-paragraph',
+	array(
+		'title'   => 'Test: Single paragraph',
+		'scope'   => array(
```
Comment (ntsekouras) [inline packages/e2e-tests/plugins/allowed-patterns.php]: experimental `scope` has been removed from patterns (https://github.com/WordPress/gutenberg/pull/30471)

File: packages/e2e-tests/plugins/allowed-patterns.php [hunk 7]
```diff
@@ -0,0 +1,41 @@
...
+		),
+		'content' => '<!-- wp:paragraph --><p>Hello!</p><!-- /wp:paragraph -->',
+	)
+);
+
+register_block_pattern(
+	'test-allowed-patterns/paragraph-inside-group',
+	array(
+		'title'   => 'Test: Paragraph inside group',
+		'scope'   => array(
```
Comment (ntsekouras) [inline packages/e2e-tests/plugins/allowed-patterns.php]: same here for `scope`

File: packages/e2e-tests/plugins/allowed-patterns.php (hunk 6 above)
Comment (david-szabo97) [reply packages/e2e-tests/plugins/allowed-patterns.php]: Thanks! Removed it and rebased

**Comment by mcsf** [comment]
I have a question for @david-szabo97 and @ntsekouras: would it be helpful to distinguish “stage I” parsing from “stage II” parsing when it comes to deciding which patterns to display? Let me explain:

1. We have `state.settings.__experimentalBlockPatterns` with a bunch of objects containing serialised blocks trees (`content: '<!-- wp…`)
2. In order to decide which patterns are allowed in a given context, we need more information. Right now we just call `wp.blocks.parse`, which is the full parser (“stage I+II”). But what if instead we just use `wp.blockSerializationDefaultParser.parse`? That way we have access to the structure (`blockName` + `innerBlocks`) of each pattern's blocks — which, unless I'm mistaken, is all we need.
3. Based on the above, we can filter (dis)allowed patterns.
4. Then, once we only have the allowed patterns left, we have to fully parse them for rendering, transforming, etc. That's when we switch to `wp.blocks.parse`.

I am asking this for two reasons:

* There are performance concerns around patterns (e.g. #28872). “Stage I” parsing is much simpler and is faster than “stage II”, so that could help. (Note: of course, we would need to test these claims.)
* Because the output of stage I is dumber (it doesn’t do full attribute resolution/sourcing, doesn’t validate, migrate, doesn’t provide clientIds, etc.), I wonder if this could contribute to **a simpler contract around block patterns, allowed blocks and transforms**, by preventing us from building something too sophisticated.

What are your thoughts?

**Comment by david-szabo97** [comment]
@mcsf

stage 2
https://github.com/WordPress/gutenberg/blob/b88ae765bacd596ff77392159d909de34c653151/packages/blocks/src/api/parser.js#L467

> Because the output of stage I is dumber (it doesn’t do full attribute resolution/sourcing, doesn’t validate, migrate, doesn’t provide clientIds, etc.), I wonder if this could contribute to a simpler contract around block patterns, allowed blocks and transforms, by preventing us from building something too sophisticated.

Because of this, we might end up with different blocks in stage 1 and stage 2. So if we use stage 1 blocks to do the check, then that might report a false positive. Is that correct?

**Comment by mcsf** [comment]
> Because of this, we might end up with different blocks in stage 1 and stage 2. So if we use stage 1 blocks to do the check, then that might report a false positive. Is that correct?

@david-szabo97: no, the difference should only be in the amount of information available for each block in the pattern. See the screenshot below. On the left is the arrangement of blocks we are dealing with. On the right, in the console, we use the serialised markup of those blocks and run it through the stage I parser and then the full parser. Notice how both represent the same tree structure, but compare the attributes for the Heading block: in the first output, `attrs` is empty, because the Heading block contains no attributes in its HTML comment boundary (`<!-- wp:heading {...} -->`); indeed the attributes `content` and `level` are sourced from the markup at the latter stage. Also notice that, for the top-level Group block, the `attrs` contains `backgroundColor` but not `tagName`.

These are the differences at play, along with knowledge of whether each block is considered _valid_, i.e. in conformance with its own definitions.

Captura de ecrã 2021-05-05, às 15 03 14

**Comment by david-szabo97** [comment]
@mcsf 
Am I doing something wrong, or stage 1 only parse is really that fast? 🤔 

stage 1 only: 42ms

stage 1 + 2: 11329ms

```js
let startTime;

startTime = Date.now()
for (let i = 0; i < 10_000; i++) wp.blockSerializationDefaultParser.parse(markup + `<p>Stage 1 ${i}</p>`);
console.log(Date.now() - startTime) // 42

startTime = Date.now()
for (let i = 0; i < 10_000; i++) wp.blocks.parse(markup + `<p>Stage 1 + 2 ${i}</p>`);
console.log(Date.now() - startTime) // 11329
```

**Comment by mcsf** [comment]
>  Am I doing something wrong, or stage 1 only parse is really that fast? 🤔

I am not **too** surprised, but it's a delight to see it. 😄 (cc @dmsnell just for fun — no input required).

File: packages/block-editor/package.json [hunk 8]
```diff
@@ -31,6 +31,7 @@
 		"@babel/runtime": "^7.13.10",
 		"@wordpress/a11y": "file:../a11y",
 		"@wordpress/blob": "file:../blob",
+		"@wordpress/block-serialization-default-parser": "file:../block-serialization-default-parser",
```
Comment (david-szabo97) [inline packages/block-editor/package.json:37]: Had to add this to pass commit verification. This definitely shouldn't be here.

Should we export this in `@wordpress/blocks`? @gziolo @youknowriad

Comment (gziolo) [reply packages/block-editor/package.json:37]: It's imported in `packages/block-editor/src/store/selectors.js` so it's correctly listed as a dependency.

Comment (david-szabo97) [reply packages/block-editor/package.json:37]: I don't think we should directly depend on this package. It would be better to export this from `blocks`, the same way as we export the `parse` from `blocks`.

Comment (gziolo) [reply packages/block-editor/package.json:37]: Good catch. I didn't think about it. So you want to use the parser for the content that doesn't convert them to blocks (with parsed inner HTML to attributes). The one imported in: 
https://github.com/WordPress/gutenberg/blob/82527384d9c1c0a3f096cd819d9c454c40183dd0/packages/blocks/src/api/parser.js#L12

@mcsf and @dmsnell might have the best answer.

File: packages/block-editor/src/store/selectors.js [hunk 9]
```diff
@@ -1806,26 +1833,50 @@ export const __experimentalGetParsedPattern = createSelector(
...
+
+				return isAllowed;
+			} );
+	},
+	( state ) => [
+		state.settings.__experimentalBlockPatterns,
+		state.settings.allowedBlockTypes,
+	]
+);
+
```
Comment (mcsf) [inline packages/block-editor/src/store/selectors.js]: @david-szabo97: I don't know if it's residual or intentional, but I don't think we should break out the parsing into a new selector. The parsing should just happen inside `getAllowedPatterns`, which incidentally means we don't have to map data, just filter it:

```js
patterns.filter( ( pattern ) => {
  const parsedBlocks = parse( pattern.content );
  return (
      checkAllowListRecursive( parsedBlocks, allowedBlockTypes ) &&
      parsedBlocks.every( ( { blockName } ) =>
        canInsertBlockType( state, blockName, rootClientId )
  );
} )
```

My concerns are: conceptually, `__experimentalGetAvailableStageOneParsedPatterns` will on its own be a confusing selector for most people; in terms of API, it's an added burden for the consumers and for us to maintain; and it's an unnecessary performance penalty, as the least concern.

Finally, you're raising an interesting question: in Gutenberg, we haven't been good at properly distinguishing, in documentation and in-code terminology, between what I described as stage I and stage II parsing. This notion of stages comes from early discussions and presentations until @mtias and I included them in [The Language of Gutenberg](https://lamda.blog/2018/04/22/the-language-of-gutenberg/), but it's not official. The result is at times quite awkward, as can be seen in the name `stageOneParser`. :) Traditionally, over time, we have seen `parsedBlocks` as one of the names for those raw blocks (stage I), hence my suggestion in the snippet.

File: packages/block-editor/package.json (hunk 8 above)
Comment (mcsf) [reply packages/block-editor/package.json:37]: > I don't think we should directly depend on this package. It would be better to export this from blocks, the same way as we export the parse from blocks.

No, these are separate things from separate modules, so I agree with Grzegorz.

`blocks` corresponds to the complete Blocks API, the one that provides blocks with all of their attributes, with automatic validation and migration, etc. Basically, _stage II_, per our previous discussion.

`block-serialization-default-parser` is a parser for the HTML-based block format, so _stage I._ It's not the only parser; in fact, it's not Gutenberg's original parser. The original one is based on the actual Gutenberg grammar specification and is known as the [spec parser](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-serialization-spec-parser/README.md). But PEG parsers are slow, so @dmsnell handcrafted  `block-serialization-default-parser` in both JS and PHP so that we would have a fast implementation by default. There is even a [Rust-based parser](https://github.com/Hywan/gutenberg-parser-rs) that compiles to WebAssembly and other native targets written by former contributor Ivan!

The important thing is that these parsers are all independent of block semantics, i.e. they are distinct from block-specific knowledge such as attribute schemas. They convert HTML into a tree of raw block nodes. And these parsers should all be interchangeable so that developers have the freedom to choose the parsers that best suit their needs. So yes, if `block-editor` now wants to quickly parse HTML into raw blocks, it should list `block-serialization-default-parser` as an explicit dependency. That's the goal of these small packages. :)

Comment (mcsf) [reply packages/block-editor/package.json:37]: GitHub didn't show Greg's reply, so my answer may look a bit weird. Anyway, I talked to him in a DM and I still think that `block-editor` should list `block-serialization-default-parser` as a dependency and directly import its parser, and not via `blocks`.

Comment (dmsnell) [reply packages/block-editor/package.json:37]: I concur with that what @gziolo and @mcsf said. stage I and stage II are confusing - maybe it's time to get back #15674

File: packages/block-editor/src/store/selectors.js (hunk 9 above)
Comment (dmsnell) [reply packages/block-editor/src/store/selectors.js]: > Traditionally, over time, we have seen parsedBlocks as one of the names for those raw blocks (stage I), hence my suggestion in the snippet.

Possibly a thought more for #15674 but I also had trouble with this naming, which is what led me to toss out `block object` vs. `block`. "Blocks" as we know them don't exist apart from the coupling of their JavaScript code and the data contained in the attributes, _the other thing we also call the block_.

File: packages/block-editor/src/store/selectors.js [hunk 10]
```diff
@@ -1791,6 +1792,32 @@ export const __experimentalGetAllowedBlocks = createSelector(
...
+			return false;
+		}
+
+		block.innerBlocks?.forEach( ( innerBlock ) => {
+			blocksQueue.push( innerBlock );
+		} );
+	}
+
+	return true;
+};
```
Comment (dmsnell) [inline packages/block-editor/src/store/selectors.js:1812]: When would we not want this to be recursive? Would it make sense to leave the call the same, that is, `checkAllowList`, instead of creating a new idea/term/function to call?

File: packages/block-editor/src/store/selectors.js [hunk 11]
```diff
@@ -1791,6 +1792,32 @@ export const __experimentalGetAllowedBlocks = createSelector(
...
+	const blocksQueue = [ ...blocks ];
+	while ( blocksQueue.length > 0 ) {
+		const block = blocksQueue.shift();
+
+		const isAllowed = checkAllowList(
+			allowedBlockTypes,
+			block.name || block.blockName,
+			true
+		);
+		if ( ! isAllowed ) {
```
Comment (dmsnell) [inline packages/block-editor/src/store/selectors.js:1802]: I'm noting that if we leave off the boolean-blinded `true` as the default value, we can trap the exact condition in the response of "If this block was explicitly rejected" vs. "if this block wasn't explicitly allowed" (which is what we have at the moment)

```ts
if (false === isAllowed) {
    return false;
}
```

File: packages/block-editor/src/store/selectors.js (hunk 10 above)
Comment (david-szabo97) [reply packages/block-editor/src/store/selectors.js:1812]: We use the `checkAllowList` in `canInsertBlockTypeUnmemoized`. It was never a recursive function.

File: packages/block-editor/src/store/selectors.js (hunk 9 above)
Comment (david-szabo97) [reply packages/block-editor/src/store/selectors.js]: `__experimentalGetAvailableStageOneParsedPatterns` is an optimization here. We want to use memoization here to avoid reparsing all the patterns again. Since `getAllowedPatterns` memoizes based on `clientId`, it would reparse all the patterns for every different `clientId`.

I really had no idea how to name these functions and variables 😄 A comment would definitely help here.

File: packages/block-editor/package.json (hunk 8 above)
Comment (david-szabo97) [reply packages/block-editor/package.json:37]: Thanks for the explanation, it makes sense! We will leave this as-is then!

File: packages/block-editor/src/store/selectors.js (hunk 11 above)
Comment (david-szabo97) [reply packages/block-editor/src/store/selectors.js:1802]: Does that make any difference though? 🤔 This is the same way we use it in `canInsertBlockTypeUnmemoized`.

Comment (dmsnell) [reply packages/block-editor/src/store/selectors.js:1802]: it only impacts code readability, not behavior. I brought up the idea because the dangling `true` confused me, hence "boolean blindness."

File: packages/block-editor/src/store/selectors.js (hunk 10 above)
Comment (dmsnell) [reply packages/block-editor/src/store/selectors.js:1812]: sure, I get that we might use this already, but is there a reason they shouldn't be recursive? It sounds like you identified an issue _because_ it wasn't recursive, and do we end up with special rules for different circumstances?

Comment (david-szabo97) [reply packages/block-editor/src/store/selectors.js:1812]: ~It's not an issue. In `canInsertBlockTypeUnmemoized` only works with block types, so it can't work in a recursive way.~

~Patterns are special in this case, since they contain multiple block types. We don't have any other way to insert multiple kinds of block types in a single action.~

That was my thought, but reusable blocks are pretty similar 🤔 Like saving a Group as reusable block and then inserting it. This needs more testing and we shouldn't do such a huge change to the core in this PR.

File: packages/block-editor/src/store/selectors.js (hunk 9 above)
Comment (mcsf) [reply packages/block-editor/src/store/selectors.js]: Ah, of course, I didn't think about how the first part is independent of `clientId`. That seems like something useful to cache if many patterns are registered. So in terms of naming I would focus more on the data relationships and less on the parsing. For instance, `getAllowedBlockPatterns`.

Keeping it private to the module is also a useful signal, just like `checkAllowListRecursive` — which is made more difficult by testing, I know. But it's something to weigh. :)

Comment (mcsf) [reply packages/block-editor/src/store/selectors.js]: Edit: My naming suggestion would require the _existing_ `getAllowedPatterns` to undergo a naming adjustment. :P 

So perhaps we'd have `getAllAllowedPatterns` + `getAllowedPatterns`?

Comment (david-szabo97) [reply packages/block-editor/src/store/selectors.js]: That sounds good to me! Pushed a commit. Also made the selector private.

File: packages/block-editor/src/store/selectors.js [hunk 12]
```diff
@@ -1799,26 +1826,48 @@ export const __experimentalGetParsedPattern = createSelector(
...
+const __experimentalGetAllAllowedPatterns = createSelector(
+	( state ) => {
+		const patterns = state.settings.__experimentalBlockPatterns;
+		const { allowedBlockTypes } = getSettings( state );
+		const parsedPatterns = patterns.map( ( pattern ) => ( {
+			...pattern,
+			// We use the Stage I parser here for performance reasons.
+			// Since we only need the structure of the parsed content,
+			// Stage I parsing is enough here.
+			stageOneBlocks: stageOneParse( pattern.content ),
```
Comment (mcsf) [inline packages/block-editor/src/store/selectors.js]:
```suggestion
			// We only need the overall block structure of the pattern. So, for
			// performance reasons, we can parse the pattern's content using
			// the raw blocks parser, also known as the "stage I" block parser.
			// This is about 250x faster than the full parse that the Block API
			// offers.
			blockNodes: parseBlocks( pattern.content ),
```

File: packages/block-editor/src/store/selectors.js [hunk 13]
```diff
@@ -1799,26 +1826,48 @@ export const __experimentalGetParsedPattern = createSelector(
 	( state ) => [ state.settings.__experimentalBlockPatterns ]
 );
 
+const __experimentalGetAllAllowedPatterns = createSelector(
```
Comment (mcsf) [inline packages/block-editor/src/store/selectors.js]: Since this is now private, we can drop the `__experimental` prefix. :)

**Review by mcsf — COMMENTED** [review]
I'm happy about where this is. :) Left some (last?) suggestions.

File: packages/e2e-tests/specs/editor/various/allowed-patterns.test.js [hunk 14]
```diff
@@ -0,0 +1,74 @@
...
+ */
+import {
+	activatePlugin,
+	createNewPost,
+	deactivatePlugin,
+	searchForPattern,
+	toggleGlobalBlockInserter,
+} from '@wordpress/e2e-test-utils';
+
+const checkPatternExistance = async ( name, available = true ) => {
```
Comment (mcsf) [inline packages/e2e-tests/specs/editor/various/allowed-patterns.test.js]: Misspelling at _existence_:

```suggestion
const checkPatternExistence = async ( name, available = true ) => {
```

**Review by mcsf — APPROVED** [review]
Code-wise, looks good! It just needs CI to turn green — I don't know if it's a matter of rebasing or if they are (could be) legitimate failures. Feel free to merge once all tests pass.

File: packages/e2e-tests/specs/editor/various/allowed-patterns.test.js (hunk 14 above)
Comment (david-szabo97) [reply packages/e2e-tests/specs/editor/various/allowed-patterns.test.js]: Thank you!

**Comment by david-szabo97** [comment]
Had to fix a few usages of `getAllowedPatterns`. Since we aren't returning `blocks` now, I had to change the implementation of pattern transformations and pattern carousel. @ntsekouras Can you take a look to make sure I didn't miss anything?

Any smoke tests are appreciated.
- Query block: Pattern carousel
- Heading, Paragraph block: Pattern transformation dropdown

File: packages/block-editor/src/components/block-pattern-setup/index.js [hunk 15]
```diff
@@ -72,7 +72,12 @@ const SetupContent = ( {
 
 function BlockPattern( { pattern, onSelect, composite } ) {
 	const baseClassName = 'block-editor-block-pattern-setup-list';
-	const { blocks, title, description, viewportWidth = 700 } = pattern;
+	const { name, title, description, viewportWidth = 700 } = pattern;
```
Comment (ntsekouras) [inline packages/block-editor/src/components/block-pattern-setup/index.js]: Regarding the `BlockPatternSetup` component it's better to leave things as they were before and just change the hook that retrieves the patterns to fill the `blocks` property here: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-pattern-setup/use-patterns-setup.js#L11


```
function usePatternsSetup( clientId, blockName, filterPatternsFn ) {
	return useSelect(
		( select ) => {
			const {
				getBlockRootClientId,
				__experimentalGetPatternsByBlockTypes,
				__experimentalGetParsedPattern,
				__experimentalGetAllowedPatterns,
			} = select( blockEditorStore );
			const rootClientId = getBlockRootClientId( clientId );
			let patterns = [];
			if ( filterPatternsFn ) {
				patterns = __experimentalGetAllowedPatterns(
					rootClientId
				).filter( filterPatternsFn );
			} else {
				patterns = __experimentalGetPatternsByBlockTypes(
					blockName,
					rootClientId
				);
			}
			return patterns.map( ( { name } ) =>
				__experimentalGetParsedPattern( name )
			);
		},
		[ clientId, blockName, filterPatternsFn ]
	);
}
```

**Review by ntsekouras — COMMENTED** [review]
Thanks for your work here David and  @mcsf for the great stage 1 input 😄 !

I've left a comment for a change regarding the `BlockPatternSetup` component, but other than that this looks great!

File: packages/block-editor/src/components/block-pattern-setup/index.js (hunk 15 above)
Comment (david-szabo97) [reply packages/block-editor/src/components/block-pattern-setup/index.js]: Thanks Nik! It's a lot better now!

**Review by ntsekouras — APPROVED** [review]
🚀
