### PR TITLE
Fix block error when transforming blocks with Link Popover opened

### LINKED ISSUE #28111: Converting a paragraph into a heading (or viceversa) will break the block if it contains a link
Trying to convert a paragraph block into a heading (or the other way around) will cause the block to break if it includes a link

**To reproduce**

1. Create a new post
2. Add a paragraph
3. Add a link inside the paragraph
4. Convert the paragraph block into a heading.

**Expected behavior**
The paragraph should convert into a heading without issues but instead, it broke.

**Screenshots**
Kapture 2021-01-11 at 15 13 27

**Editor version:**
- WordPress version 5.6
- Gutenberg plugin version 9.7.0
- The problem does not occur without the plugin
- I was also able to reproduce this exact error on a free (simple) WordPress.com site
  
The exact same problem arises if you do the opposite: create a heading, add a link and try to convert it into a paragraph.

The console returns this error:

```
react-dom.min.de439aae.js:125 TypeError: Cannot read property 'ownerDocument' of undefined
    at index.js?ver=5f012ae2a1c6dc1a4b432c305b2be604:1
    at Object.useMemo (react-dom.min.de439aae.js:216)
    at d.useMemo (react.min.e713ea3b.js:32)
    at st (index.js?ver=5f012ae2a1c6dc1a4b432c305b2be604:1)
    at index.js?ver=16801eb7527d46a7b6c21552167c80f5:1
    at we (react-dom.min.de439aae.js:84)
    at zj (react-dom.min.de439aae.js:226)
    at Th (react-dom.min.de439aae.js:152)
    at tj (react-dom.min.de439aae.js:152)
    at Te (react-dom.min.de439aae.js:146)
```

If I switch to the "Code View" I see this markup:

```
 <a href="react-dom.min.de439aae.js:125 TypeError: Cannot read property 'ownerDocument' of undefined
    at index.js?ver=5f012ae2a1c6dc1a4b432c305b2be604:1
    at Object.useMemo (react-dom.min.de439aae.js:216)
    at d.useMemo (react.min.e713ea3b.js:32)
    at st (index.js?ver=5f012ae2a1c6dc1a4b432c305b2be604:1)
    at index.js?ver=16801eb7527d46a7b6c21552167c80f5:1
    at we (react-dom.min.de439aae.js:84)
    at zj (react-dom.min.de439aae.js:226)
    at Th (react-dom.min.de439aae.js:152)
    at tj (react-dom.min.de439aae.js:152)
    at Te (react-dom.min.de439aae.js:146)">Ut enim ad minim veniam</a>
```

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/28111

## To reproduce

1. Create a new post
2. Add a paragraph
3. Add a link inside the paragraph
4. While the URL PopOver is opened, convert the paragraph block into a heading (or viceversa).

I'm not sure if there is a better fix here, but I'd love any ideas if you have any...
The change in code come from this PR: https://github.com/WordPress/gutenberg/pull/26782

### CODE REVIEW

File: packages/rich-text/src/component/use-anchor-ref.js [hunk 1]
```diff
@@ -31,8 +31,10 @@ export function useAnchorRef( { ref, value, settings = {} } ) {
 	const activeFormat = name ? getActiveFormat( value, name ) : undefined;
 
 	return useMemo( () => {
-		const { ownerDocument } = ref.current;
-		const { defaultView } = ownerDocument;
+		if ( ! ref.current ) return;
```
Comment (ellatrix) [inline packages/rich-text/src/component/use-anchor-ref.js:34]: When is this null? On first render?

**Review by ellatrix — APPROVED** [review]
Makes sense

File: packages/rich-text/src/component/use-anchor-ref.js (hunk 1 above)
Comment (youknowriad) [reply packages/rich-text/src/component/use-anchor-ref.js:34]: Seems like rewriting as a callback ref would fix it, this is typically the kind of bugs passing "ref" to hooks can create.

Comment (youknowriad) [reply packages/rich-text/src/component/use-anchor-ref.js:34]: (just a small remark, not necessarily for now)

Comment (ntsekouras) [reply packages/rich-text/src/component/use-anchor-ref.js:34]: No. It's `undefined` when clicking the transform item.
