### PR TITLE
RTC: Fix inline inserter reset on update sync

### LINKED ISSUE #76977: RTC: Inline block inserter disappears in collaborative session
From @opr:

> While showing the block inserter, it kept closing when other people did things, maybe someone else inserting a block?

Image

### PR DESCRIPTION
**Pull request by alecgeatches**
## What?

Fixes #76977.

Currently, the inline block inserter disappears during RTC sessions when another user is actively editing:

https://github.com/user-attachments/assets/11c92ee2-f9d3-481a-bbe0-cd0992382bff

## Why?

The root cause is `useLastDifferentValue` in the autocomplete component. This hook tracks whether the user has changed something by keeping a history of the last 2 rich-text record objects in a `Set`. Since `Set` uses object reference equality, when `RESET_BLOCKS` fires during RTC sync and rebuilds the block tree from scratch, the resulting new record objects (same text, different references) append to the history rather than it staying the same. The "previous" record ends up having the same `.text` as the current one, so `didUserInput` evaluates to `false` and the popover is removed.

## How?

This is a `RESET_BLOCKS`-related bug like https://github.com/WordPress/gutenberg/pull/76025, a class of bugs we've seen where the editor will reset local editor state on sync in a way that doesn't make sense in a collaborative model.

This PR changes `useLastDifferentValue` to compare by `.text` value instead of object reference. The new implementation uses two refs: one for the previous record and one for the last record that had a different `.text`. When a re-render produces a new record object with the same text content (as happens during `RESET_BLOCKS` in an RTC sync), the function correctly recognizes that no actual text change occurred and preserves the earlier record that had different text. This keeps `didUserInput` as `true` and the popover stays visible.

### Automated

```
npm run test:unit -- --testPathPattern='packages/components/src/autocomplete'
```

### Manual

1. Enable RTC via Settings -> Writing -> "Enable real-time collaboration" checkbox.
2. Open a post collaboratively in two tabs.
3. In one session, begin continuously typing in a paragraph block. Here's a JS one-liner that can do that:

    ```js
    // First, click into block text, then paste:
    (function(){var s="Lorem ipsum dolor sit amet. ",i=0,doc=document.querySelector('.block-editor-iframe__scale-container iframe').contentDocument,el=doc.activeElement;window._typer=setInterval(function(){el.focus();doc.execCommand('insertText',false,s[i%s.length]);i++;},200);})();

    // To stop typing:
    // clearInterval(window._typer)
    ```

4. In the other session, click into a separate paragraph block and type `/`.
5. Verify the inline block inserter popover stays open while the other user is typing:

    https://github.com/user-attachments/assets/98a1a115-1c3a-4954-9633-85f0dc331c39

7. Select an option from the inserter and verify it inserts correctly:

## Use of AI Tools

AI assistance: Yes
Tool(s): Claude Code
Used for: Root cause analysis and implementation

### CODE REVIEW

File: packages/components/src/autocomplete/index.tsx [hunk 1]
```diff
@@ -393,17 +393,48 @@ export function useAutocomplete( {
...
+/**
+ * Checks whether two records represent the same user-visible state
+ * (same text content and cursor position).
+ */
+function recordValuesMatch(
+	a: UseAutocompleteProps[ 'record' ],
+	b: UseAutocompleteProps[ 'record' ]
+) {
+	return a.text === b.text && a.start === b.start && a.end === b.end;
+}
```
Comment (Mamaduka) [inline packages/components/src/autocomplete/index.tsx:306]: I guess this technically can produce a false positive: same text, different formats. Though probably not important for this case.

P.S. Seems like the `rich-text` component should have similar utility. Basically, shallow equality for RichText records.

Comment (alecgeatches) [reply packages/components/src/autocomplete/index.tsx:306]: You're right that this misses some of the text record attributes. I considered adding them all, but `formats` and `replacements` are arrays. These are newly created from `RESET_BLOCKS`, so we'd also need deep equality checking in order to fix the bug. This isn't awful but is a lot more expensive than the previous object ref comparison.

Comparing text + start/end will let us know if the last `.text` changed meaningfully and the popover should change. Otherwise, as you said, the formats aren't important for this behavior or related tests.

File: packages/components/src/autocomplete/index.tsx [hunk 2]
```diff
@@ -393,17 +393,48 @@ export function useAutocomplete( {
...
+ * Tracks the last record whose value differed from the current one.
+ * Used to determine whether the user has actually typed something
+ * (as opposed to a re-render producing a new record object with
+ * identical content, e.g. during a block reset).
+ *
+ * Maintains a sliding window of 2 records, similar to the original
+ * Set-based approach but using value comparison instead of reference
+ * equality so that new objects with the same content (text, start, end)
+ * are treated as duplicates.
+ */
```
Comment (Mamaduka) [inline packages/components/src/autocomplete/index.tsx:311]: I think we can simplify the JSDoc block here. There's no need to mention previous methods or anything else. Just what it does currently.

**Review by Mamaduka — COMMENTED** [review]
The focus fix for this particular bug is good ✅ 

I think the general problem with `REST_BLOCKS` might need more attention, as it will affect any consumer code that keeps track of `record` and triggers side effects based on it.

Can we keep the same reference for blocks that aren't affected by RTC? Will this bookkeeping be expensive?

cc @jsnajdr, @youknowriad

**Comment by jsnajdr** [comment]
> I think the general problem with `RESET_BLOCKS` might need more attention [...] Can we keep the same reference for blocks that aren't affected by RTC?

The `RESET_BLOCKS` actions is used mainly by the `useBlockSync` hook and the `useEntityBlockEditor` hook, whose return value is passed as input the `useBlockSync`. These hooks perform a two-way sync between an entity in the `core-data` store and block tree state in `block-editor` store.

Tt's used for two purposes:
1. Reset the block editor state when we start editing a certain entity, or when we switch from editing entity A to editing entity B.
2. Update the block editor state when the entity in `core-data` is updated, from an "external source".

Technically these two cases are almost the same (`getEditedEntityRecord` return value changes), but semantically they are very different.

And the second use case, updating the existing entity, although it has always been present, started to be seriously used only now, when RTC was implemented. Because the "updates from external sources" didn't really happen before.

This is why `RESET_BLOCKS` is suddenly a problematic action behind several bugs. For a long time we could get away with assuming that reset is done only when switching from editing entity A to editing entity B, but that doesn't work any more.

One of the typical recent fixes is #76025. Here `RESET_BLOCKS` was resetting the UI state of list view sidebars. That's a good idea when navigating to a different entity, but a bad idea when merely receiving RTC updates for an existing post.

The original version of #76025 added an `isExternal` flag to `RESET_BLOCKS`, maybe we'll eventually need to implement something like this, to distinguish between the two types of reset.

File: packages/components/src/autocomplete/index.tsx (hunk 2 above)
Comment (alecgeatches) [reply packages/components/src/autocomplete/index.tsx:311]: Removed most of the lines in https://github.com/WordPress/gutenberg/pull/76980/changes/7d47aa3821a32fa574592d7ddef2c7c504a635f7!

**Review by Mamaduka — APPROVED** [review]
Let's add a changelog entry, and I think this is good to merge.

File: packages/components/CHANGELOG.md [hunk 3]
```diff
@@ -4,12 +4,16 @@
 
 ### Bug Fixes
 
+<<<<<<< fix/rtc-inline-inserter
```
Comment (oandregal) [inline packages/components/CHANGELOG.md:7]: The changelog here has git conflict markers. I'm removing them at https://github.com/WordPress/gutenberg/pull/77127

Comment (Mamaduka) [reply packages/components/CHANGELOG.md:7]: This should be fixed on trunk.

Comment (alecgeatches) [reply packages/components/CHANGELOG.md:7]: @oandregal Thank you for fixing this, I'm not sure how this got by me.

**Comment by alecgeatches** [comment]
Cherry-pick conflict fixed in https://github.com/WordPress/gutenberg/pull/77706.

**Comment by t-hamano** [comment]
This PR was backported to `wp/7.0` in #77706.
