### PR TITLE
Navigation: Handle block menu items

### LINKED ISSUE #24675: Navigation: Handle block menu items when creating a Navigation block from a menu
If you have a menu item with `type = 'block'`, creating a Navigation block from that menu won't properly handle the block menu item.

block-menu-item

**Steps to reproduce**

1. Add a Search block to a menu using the Navigation screen. See https://github.com/WordPress/gutenberg/pull/24503 for instructions.
1. Save the menu.
1. Go to a post and insert a Navigation block.
1. Select the menu and click _Create_.

**Expected behaviour**

The Navigation block appears exactly as it does in the Navigation screen.

**Actual behaviour**

The Search block is turned into a Link block with its title set to "Block".

### LINKED ISSUE #25087: Selecting an existing menu for the Navigation Block doesn't create links
**Describe the bug**

When adding the navigation block and choosing an existing menu, the block doesn't bring the links over into the menu causing the menu to be added without any links. 

**To reproduce**
1. Turn on all gutenberg experiments in Gutenberg > Experiments
2. Create a menu under Gutenberg > Navigation (beta) and make sure to link to items
3. Head to the Site Editor (beta)
4. Add the navigation block and choose to select from an existing menu
5. Hit publish and try to select menu items only to find nothing is linked. 

**Expected behavior**

I expected the navigation block to include the links I added in the navigation screen including after editing the menu items after adding the block. 

**Screenshots**

Here's a video of me talking through the experience: https://cloudup.com/cvhi8PkkoJZ

Here's a screenshot showing that I did indeed add links in the Navigation Screen before adding the navigation block to the Site Editor:

Screen Shot 2020-09-04 at 1 07 11 PM

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 8.9.1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Version 84.0.4147.135

### PR DESCRIPTION
**Pull request by noisysocks**
Fixes https://github.com/WordPress/gutenberg/issues/24675. Fixes https://github.com/WordPress/gutenberg/issues/25087.

block-menu-items

Updates the Navigation block to properly convert menu items with `type = 'block'` when creating a Navigation block from an existing menu.

I also made it pull the `description`, `rel` and `className` over from the menu item.

### How to test

1. Patch your current theme to support block navigation. Here's how that looks for Twenty Twenty:

```diff
Index: src/wp-content/themes/twentytwenty/functions.php
===================================================================
--- src/wp-content/themes/twentytwenty/functions.php	(revision 48655)
+++ src/wp-content/themes/twentytwenty/functions.php	(working copy)
@@ -142,6 +142,7 @@
 	$loader = new TwentyTwenty_Script_Loader();
 	add_filter( 'script_loader_tag', array( $loader, 'filter_script_loader_tag' ), 10, 2 );
 
+	add_theme_support( 'block-nav-menus' );
 }
 
 add_action( 'after_setup_theme', 'twentytwenty_theme_support' );
Index: src/wp-content/themes/twentytwenty/header.php
===================================================================
--- src/wp-content/themes/twentytwenty/header.php	(revision 48655)
+++ src/wp-content/themes/twentytwenty/header.php	(working copy)
@@ -83,25 +83,25 @@
 
 					<?php
 					if ( has_nav_menu( 'primary' ) || ! has_nav_menu( 'expanded' ) ) {
-						?>
 
-							<nav class="primary-menu-wrapper" aria-label="<?php esc_attr_e( 'Horizontal', 'twentytwenty' ); ?>" role="navigation">
+						if ( has_nav_menu( 'primary' ) ) {
 
-								<ul class="primary-menu reset-list-style">
+							wp_nav_menu(
+								array(
+									'container'      => '',
+									'items_wrap'     => '%3$s',
+									'theme_location' => 'primary',
+								)
+							);
 
-								<?php
-								if ( has_nav_menu( 'primary' ) ) {
+						} elseif ( ! has_nav_menu( 'expanded' ) ) {
+							?>
 
-									wp_nav_menu(
-										array(
-											'container'  => '',
-											'items_wrap' => '%3$s',
-											'theme_location' => 'primary',
-										)
-									);
+							<nav class="primary-menu-wrapper" aria-label="<?php esc_attr_e( 'Horizontal', 'twentytwenty' ); ?>" role="navigation">
 
-								} elseif ( ! has_nav_menu( 'expanded' ) ) {
+								<ul class="primary-menu reset-list-style">
 
+									<?php
 									wp_list_pages(
 										array(
 											'match_menu_classes' => true,
@@ -110,15 +110,14 @@
 											'walker'   => new TwentyTwenty_Walker_Page(),
 										)
 									);
+									?>
 
-								}
-								?>
-
 								</ul>
 
 							</nav><!-- .primary-menu-wrapper -->
 
-						<?php
+							<?php
+						}
 					}
 
 					if ( true === $enable_header_search || has_nav_menu( 'expanded' ) ) {
```

2. Add a Search block to a menu using the Navigation screen. See https://github.com/WordPress/gutenberg/pull/24503 for instructions.

3. Save the menu.

4. Go to a post and insert a Navigation block.

5. Select the menu and click _Create_.

6. Note that the Search block is properly added.

### CODE REVIEW

**Comment by noisysocks** [comment]
Looks like there's some legitimate E2E test failures. I'll look into them tomorrow.

File: packages/block-library/src/navigation/placeholder.js [hunk 1]
```diff
@@ -78,28 +78,51 @@ function getSelectedMenu( selectedCreateOption ) {
...
+		}
+
+		if ( menuItem.xfn?.length && some( menuItem.xfn ) ) {
+			attributes.rel = menuItem.xfn.join( ' ' );
+		}
+
+		if ( menuItem.classes?.length && some( menuItem.classes ) ) {
+			attributes.className = menuItem.classes.join( ' ' );
+		}
+
```
Comment (noisysocks) [inline packages/block-library/src/navigation/placeholder.js:120]: Ideally we'd also set `id` and `type` here so that the URL can be dynamic. Need to think about these attributes some more, though. I've added a note to do this in 

I'll add a note to come back to this in https://github.com/WordPress/gutenberg/issues/18345.

**Comment by noisysocks** [comment]
I've updated the E2E test snapshots. This is ready for review.

File: packages/block-library/src/navigation/placeholder.js (hunk 1 above)
Comment (talldan) [reply packages/block-library/src/navigation/placeholder.js:119]: I'm unclear on the reasoning behind dropping these attributes, what's the background?

Comment (noisysocks) [reply packages/block-library/src/navigation/placeholder.js:119]: So the existing code in `master` has a few problems:

- We're setting the `type` attribute to be `menuItem.type`, but this is incorrect because the attribute should be one of `'page'`, `'post'`, `'category'`, `'tag'`, or `undefined` and `menuItem.type` returns `'post_object'` or `'taxonomy'` IIRC.

- We're setting `id` to `menuItem.id`, but this is incorrect because for a link to dynamically render its URL it will need the _ID of the post_, not the _ID of the menu item_. It should probably be set to `menuItem.object_id`.

Instead of fixing these issues, though, I added a note to address them when we address https://github.com/WordPress/gutenberg/issues/18345 as there's some thinking to be done around what attributes are needed for dynamically rendering a link. IMO we should be storing three things with the block: the menu item type, the object type, the object ID. See https://github.com/WordPress/gutenberg/issues/18345#issuecomment-682335969.

File: packages/block-library/src/navigation/placeholder.js [hunk 2]
```diff
@@ -76,26 +77,51 @@ function getSelectedMenu( selectedCreateOption ) {
...
-				type,
-				id,
-				url,
-				label: ! title.rendered ? __( '(no title)' ) : title.rendered,
-				opensInNewTab: false,
-			},
-			innerBlocks
-		);
+			if ( ! block ) {
+				return createBlock( 'core/freeform', {
```
[the remark this answers is not in the document]
Comment (noisysocks) [reply packages/block-library/src/navigation/placeholder.js:89]: I do wonder if, instead, we should simply fail (loudly?) in this case. It's undefined behaviour for the menu item to have 0 or > 1 blocks in it. Thoughts?

[the remark this answers is not in the document]
Comment (talldan) [reply packages/block-library/src/navigation/placeholder.js:89]: Oh right, I think I've misunderstood what it's for. It actually looks like `parse` gives you a freeform block anyway if it's valid HTML that doesn't contain a block.

I think you're right, it should probably fail, but in a way that still makes the navigation recoverable. Not sure what the best option would be.

File: packages/block-library/src/navigation/placeholder.js (hunk 1 above)
Comment (talldan) [reply packages/block-library/src/navigation/placeholder.js:119]: Thanks for the explanation, sounds like it's not something to tackle here.

It'd be good to rewrite the description on the issue with these details. 👍

**Review by talldan — APPROVED** [review]
Looks good in testing. The two review points can be addressed separately.
