### PR TITLE
Pressing left in docked-link dialog closes dialog

### LINKED ISSUE #3822: Pressing Horizontal Arrow Keys in Link Dialog in Fixed To Toolbar Mode closes Link Dialog
## Issue Overview

When presssing `left` and `right` inside the linked dialog input, the linked dialog disappears. This only happens in "Fixed to Toolbar" mode for the toolbar. It is probably due to a propagating event.

## Steps to Reproduce (for bugs)

1. Switch Toolbar mode to "Fixed to Toolbar"
2. Create paragraph block
3. Create link in paragraph block
4. Press arrow keys in the input

## Expected Behavior

The arrow moves through the input.

## Current Behavior
The dialog disappears altogether.

### PR DESCRIPTION
**Pull request by ephox-mogran**
Fixes #3822 

## Description

This stops arrow keys propagating past the link dialog. It also removes the global key handlers in the link dialog. There are also some e2e tests for it.

### CODE REVIEW

**Comment by ephox-mogran** [comment]
So the cause of this bug is that pressing the `left` key is being handled by 

```
>> editor/components/block-list/block.js

case LEFT:
				// Arrow keys do not fire keypress event, but should still
				// trigger typing mode.
				this.maybeStartTyping();
				break;
```

Which hides the dialog. This is a common problem. This `maybeStartTyping` concept probably shouldn't happen at the block level, otherwise you will have to stop events from everything propagating to it. Recently, #3796 needed to stop keypress to avoid firing it. I feel that the `maybeStartTyping` triggers either need to be a bit smarter about the source of the event, or need to be closer to the Editable layer.

The other way you could handle it is still make `maybeStartTyping` not render the toolbar, but still render the things inside the Toolbar (e.g. link dialog).

At the moment, we are stuck having to stop any event propagating that is going to be handled by an outer component. In Gutenberg, this outer component can be many things. The two major culprits of recent bugs are:

1. `WritingFlow` handles up and down arrows (probably #3783)
2. Block handles `maybeStartTyping` and hides entire toolbar and any subcomponents regardless of which slot they are rendered in (#3795, #3822)

@aduth @mcsf @youknowriad @iseulde 

I think we need to really consider how `maybeStartTyping` should work. Should it only apply to arrow keys firing inside `Editable`. Would you want the main toolbar to show/hide as a user is typing inside some separate toolbar UI?

File: test/e2e/integration/004-managing-links.js [hunk 1]
```diff
@@ -0,0 +1,29 @@
+describe( 'Managing blocks', () => {
```
Comment (ephox-mogran) [inline test/e2e/integration/004-managing-links.js]: Oops. Rename.

File: test/e2e/integration/004-managing-links.js [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+	before( () => {
+		cy.newPost();
+	} );
+
+	it( 'Switch to "Fixed to toolbar" mode', () => {
```
Comment (ephox-mogran) [inline test/e2e/integration/004-managing-links.js]: Probably should change this test name too.

**Comment by ephox-mogran** [comment]
So I've implemented this by just cancelling arrow events at the form wrapping the input. I've also removed the ESC handling global listeners, because I'm really not sure why they are there? Is the reason they are global because you want every other handler to have a go at the event first? If it is, those other handlers would have to call `stopImmediatePropagation` on the `nativeEvent` which they are probably not doing. My view (2c) is just that you don't need the global handlers in the first place.

File: blocks/editable/format-toolbar/index.js [hunk 3]
```diff
@@ -66,21 +66,16 @@ class FormatToolbar extends Component {
...
-	}
-
 	onKeyDown( event ) {
 		if ( event.keyCode === ESCAPE ) {
 			if ( this.state.isEditingLink ) {
 				event.stopPropagation();
 				this.dropLink();
 			}
 		}
+		if ( event.keyCode >= LEFT && event.keyCode <= DOWN ) {
```
Comment (ephox-mogran) [inline blocks/editable/format-toolbar/index.js]: Are you OK with this? It requires knowledge about the key codes. I'd probably prefer to do four individual or conditions, but I wasn't sure what you'd prefer.

Comment (youknowriad) [reply blocks/editable/format-toolbar/index.js]: I think I'd prefer white listing the keys instead of assuming they are ordered `[ LEFT, DOWN, RIGHT, UP ].indexOf` but it's minor

File: test/e2e/integration/004-managing-links.js [hunk 4]
```diff
@@ -0,0 +1,59 @@
+describe( 'Managing links', () => {
+	before( () => {
+		cy.newPost();
+	} );
+
+	const fixedIsOn = 'button.is-selected:contains("Fix toolbar to block")';
+	const fixedIsOff = 'button:contains("Fix toolbar to block"):not(".is-selected")';
+
+	const switchToMode = ( setFixed ) => {
```
Comment (youknowriad) [inline test/e2e/integration/004-managing-links.js]: Nice! If we find it useful in other tests, we might want to create a command for this one.

**Review by youknowriad — APPROVED** [review]
Nice work here 👍

**Comment by youknowriad** [comment]
> I think we need to really consider how maybeStartTyping should work. Should it only apply to arrow keys firing inside Editable. 

I don't think so, I think it should apply to anything inside the block, the block are not forced to use `Editable`, the can use inputs, textareas and it's still "typing mode". That said, I'm curious why the formatting toolbar is shown inside the ".editor-block-list__block-edit" container, I was think it's shown outside and thus shouldn't trigger this.

File: test/e2e/integration/004-managing-links.js (hunk 4 above)
Comment (mcsf) [reply test/e2e/integration/004-managing-links.js]: May I suggest improving the naming. Examples:
- `switchToolbarMode( 'fixed' )`, `'block'` to mimic user language
- `setFixedToolbar( b: boolean )` to mimic internal structure (`state.preferences.features.fixedToolbar`)

File: blocks/editable/format-toolbar/index.js (hunk 3 above)
Comment (mcsf) [reply blocks/editable/format-toolbar/index.js]: I second making the entire key set explicit.

**Review by mcsf — APPROVED** [review]
Looks good, especially with the e2e test.
