### PR TITLE
Fixed : Modal dialog: small improvement for elementShouldBeHidden 

### LINKED ISSUE #65829: Modal dialog: small improvement for `elementShouldBeHidden`
### Description

The modal dialog component uses some logic to determine what body children should be `aria-hidden` when the modal dialog is open.

https://github.com/WordPress/gutenberg/blob/559391a6f1451e68124c9a18925ab784bca80e29/packages/components/src/modal/aria-helper.ts#L23-L54

Some elements are correctly filtered out as they should not get the `aria-hidden` attribute. It looks like elements with the `hidden` HTML attribute could be filtered out as well, as they're already completely hidden from assistive technologies.

Currentlty, `aria-hidden` is added and then removed also to these elements, which seems unnecessary:

Image

### Step-by-step reproduction instructions

- Go to the post editor.
- Inspect the DOM.
- For the purpose of this test, make sure no `speak` messages have been sent to the aria-live regions.
- When no messages have been sent yet, observe the element with id `a11y-speak-intro-text` does have an HTML attribute `hidden`.
- Open a modal dialog e.g. the Keyboard Shortcuts one by pressing the keys Control+Option+H.
- Observe the `a11y-speak-intro-text` element gets an `aria-hidden="true"` attribute, which is unnecessary as the element is already hidden.
- There may be other elements with a `hidden` HTML attribute e.g. added by plugins that don't need `aria-hidden="true"`.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### PR DESCRIPTION
**Pull request by vk17-starlord**
fixes #65829 

Fix: Avoid redundant aria-hidden on elements with hidden attribute

This PR updates the elementShouldBeHidden function to skip applying aria-hidden="true" to elements that already have the hidden attribute, as they are already hidden from both visual and assistive technologies. This prevents unnecessary DOM manipulations and ensures cleaner, more efficient accessibility handling.
Changes:

Added a check for the hidden attribute in the function to avoid redundant aria-hidden application.

### CODE REVIEW

File: packages/components/src/modal/aria-helper.ts [hunk 1]
```diff
@@ -44,12 +44,22 @@ export function modalize( modalElement?: HTMLDivElement ) {
  * @return Whether the element should not be hidden from screen-readers.
  */
 export function elementShouldBeHidden( element: Element ) {
+	// If the element has the 'hidden' attribute, it should already be hidden from assistive tech
+	if ( element.hasAttribute( 'hidden' ) ) {
```
Comment (up1512001) [inline packages/components/src/modal/aria-helper.ts]: @vk17-starlord can we please combine this check within the return statement as suggested by @afercia

**Review by up1512001 — CHANGES_REQUESTED** [review]
Added one suggestion please check.

File: packages/components/src/modal/aria-helper.ts (hunk 1 above)
Comment (vk17-starlord) [reply packages/components/src/modal/aria-helper.ts]: ok @up1512001

**Review by up1512001 — APPROVED** [review]
LGTM

**Comment by up1512001** [comment]
@vk17-starlord can you please add this PR info to changelog.md, it will go under `Unreleased > Bug Fixes`
https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md

File: packages/components/src/modal/aria-helper.ts [hunk 2]
```diff
@@ -45,11 +45,16 @@ export function modalize( modalElement?: HTMLDivElement ) {
...
-		element.hasAttribute( 'aria-hidden' ) ||
-		element.hasAttribute( 'aria-live' ) ||
-		( role && LIVE_REGION_ARIA_ROLES.has( role ) )
+		(
+			element.tagName === 'SCRIPT' || // Skip <script> tags
+			element.hasAttribute( 'hidden' ) || // Skip elements with 'hidden' attribute
+			element.hasAttribute( 'aria-hidden' ) || // Skip elements marked as aria-hidden
+			element.hasAttribute( 'aria-live' ) || // Skip live regions
+			( role && LIVE_REGION_ARIA_ROLES.has( role ) )
+		) // Skip elements with live region roles
```
Comment (afercia) [inline packages/components/src/modal/aria-helper.ts]: This comment should be moved to the appropriate line. However, I'd consider to remove all these comments because the code is pretty self-explanatory.

File: packages/components/CHANGELOG.md [hunk 3]
```diff
@@ -3,7 +3,7 @@
 ## Unreleased
 
 ### Bug Fixes
-
+-   `Modal` : Modal dialog small improvement for elementShouldBeHidden - PR ([#65941](https://github.com/WordPress/gutenberg/pull/65941)).
```
Comment (afercia) [inline packages/components/CHANGELOG.md]: The changelog entry should follow a specific format:
- Please remove the space before the colon.
- Please remove the `- PR `.
- I'd consider to move the entry to the `Enhancements` section as it's not a bug fix.

**Review by afercia — CHANGES_REQUESTED** [review]
Thank you @vk17-starlord from a code perspective lookks good to me.
I left two small comments to address minor things, please have a look when you have a chance.

**Comment by vk17-starlord** [comment]
@afercia have a look at latest commit , i have implemented the suggestions you gave

**Review by afercia — APPROVED** [review]
LGTM, can be merged after tests pass.

**Review by afercia — CHANGES_REQUESTED** [review]
I spoke to soon. There's now a merge conflict in `packages/components/CHANGELOG.md` that needs to be solved.

**Comment by vk17-starlord** [comment]
@afercia anything left to be done from my side ?

**Comment by afercia** [comment]
> @afercia anything left to be done from my side ?

@vk17-starlord yes: the changelog entry must be in the `Unreleased` section, under `Enhancements`. It was probably moved down when merging trunk. Thanks for your patience.

**Comment by vk17-starlord** [comment]
@afercia done with changes !!

**Review by afercia — APPROVED** [review]
LGTM to me.
Thanks @vk17-starlord
