### PR TITLE
Fixes to append items via toolbar

### LINKED ISSUE #18299: Navigation Menu: Nested menu-items are prepended instead of appended
**Describe the bug**
A new toolbar button was recently added to navigation menu items, to allow adding other nested menu items underneath them.

Screen Shot 2019-11-06 at 5 50 17 pm

However, this seems to prepending the nested blocks. Instead they should be appended. It's pretty apparent when using the button to build a menu that the behaviour isn't correct, the user has to add their menu in reverse, or add the items and then re-order them.

**To reproduce**
1. Add a navigation menu block (enable it as an experimental feature first).
2. Add a menu item to the navigation menu.
3. Try adding multiple nested menu items within the menu item created in step 2.
4. Note that the button prepends blocks

**Expected behavior**
The button appends blocks

### PR DESCRIPTION
**Pull request by getdave**
Closes https://github.com/WordPress/gutenberg/issues/18299

Updates the Nav Block toolbar "insert" button to _append_ items at the end of the currently selected Nav Block Item.

Previously this was hardcoded to `0` which meant they were always prepended.

## How has this been tested?
Manual testing.

## Screenshots 

Screen Capture on 2019-11-08 at 17-31-26

## Types of changes
Bug fix (non-breaking change which fixes an issue) 

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

File: packages/block-library/src/navigation-menu-item/edit.js [hunk 1]
```diff
@@ -245,7 +245,7 @@ export default compose( [
 			hasDescendants: !! getClientIdsOfDescendants( [ clientId ] ).length,
 		};
 	} ),
-	withDispatch( ( dispatch, ownProps ) => {
+	withDispatch( ( dispatch, ownProps, registry ) => {
```
Comment (obenland) [inline packages/block-library/src/navigation-menu-item/edit.js]: I think the only suggestion I'd have would be to maybe consider destructuring `registry` to just pick `select`?

**Review by obenland — APPROVED** [review]

File: packages/block-library/src/navigation-menu-item/edit.js (hunk 1 above)
Comment (getdave) [reply packages/block-library/src/navigation-menu-item/edit.js]: I had some advice from @mcsf that Gutenberg prefers being explicit about where you are accessing the properties of data controls. I took this as avoiding unnecessary destructuring in/around `select`/`dispatch`/`registry`. I could be wrong.

**Comment by getdave** [comment]
Waiting on build issues to merge...

File: packages/block-library/src/navigation-menu-item/edit.js (hunk 1 above)
Comment (mcsf) [reply packages/block-library/src/navigation-menu-item/edit.js]: > I had some advice from @mcsf that Gutenberg prefers being explicit about where you are accessing the properties of data controls. I took this as avoiding unnecessary destructuring in/around `select`/`dispatch`/`registry`. I could be wrong.

Thanks for thinking about my advice 😄. In this case I don't really have an opinion, since, in the context of `withDispatch`, `select` could only come from one place.

My main point — which was merely stylistic — in the other PR was about not extracting the selectors into their own variable, e.g. `const { getFoos } = select( store )`, and instead always calling `select( store ).getFoos( ...args )`.

**Review by mcsf — COMMENTED** [review]
Have you tried calling `insertBlock` with an undefined `index`? I had noticed that the argument was considered optional so I tried dropping it, and I think the same effect is achieved.

You can see in the `order` reducer where `index` defaults to the substate's length:

https://github.com/WordPress/gutenberg/blob/bf5c1638af5881a415f84b79476e3451ad50bb64/packages/block-editor/src/store/reducer.js#L731

Quick check with @youknowriad: the documentation for `insertBlock(s)` isn't super explicit about appending when `index` is missing, but the [signature](https://github.com/WordPress/gutenberg/blob/bf5c1638af5881a415f84b79476e3451ad50bb64/packages/block-editor/src/store/actions.js#L393-L394) does state "inserted, optionally at a specific index respective a root block list". We can recommend this usage, right?
