### PR TITLE
Zoom Out: Fix bouncy drop zones

### LINKED ISSUE #65927: Zoom out: drag and drop zones behave strangely (disappear, bounce, etc)
When playing around with drag and drop, I noticed that the zones behave a bit strangely:

-  Appearing then disappearing.
- "Bouncing" where the drop zone quickly moves up and down trying to expand.
- Patterns with grid block causes a large overlay to appear with grid lines

https://github.com/user-attachments/assets/51c8359f-5dc9-44b7-99f0-f5cfd70e8fcc

This was found using WordPress 6.7 nightly.

### PR DESCRIPTION
**Pull request by talldan**
## What?
Fixes #65927 (or at least one of the main issues)

## Why?
Block drag and drop uses the `useBlockDropZone` hook. Rather than each block being a drop zone, each block list is a drop zone.

For Zoom Out, only the 'section' blocks are interactive—the only block list that's supposed to be active as a drop zone is the one represented by the `sectionRootClientId`. This is handled by the `useSelect` in the `useInnerBlocksProps` hook, it returns `isDropZoneDisabled: true` for any block lists that are not the section root, and that's used to prevent binding the `useBlockDropZone` hook.

The bug - that hook has an early `if ( ! clientId )` return in the `useSelect`, which always returns a falsey for the `isDropZoneDisabled` value, so in a lot of cases zoom out would accidentally have two blocks lists acting as drop zones - the actual 'root' block list and the section root.

This extra drop zone causes some rogue `onDragLeave` events triggering `hideInsertionPoint`.

## How?
Adds some extra logic in the selector for the root block list when zoom out is active. It is valid for the sectionRoot to be the actual root, so this is checked.

Separately I've also added some extra safety to the `isInsertionPoint` check, as this only tests against the outer element and not nested elements of the insertion point.

## Testing Instructions
1. Edit a template like Blog Homepage in the site editor
2. Insert some patterns as sections. Add lots of top margin above one section
3. Open the inserter on patterns tab, select a category
4. Try dragging one of the patterns over the pattern with the margin, then drag into the margin area and back again repeatedly

In trunk: The Insertion Points shows and hides itself as you drag between the block and the margin
In this PR: The Insertion Point stays present as you drag back and forth.

#### Before
https://github.com/user-attachments/assets/26bd5232-e2a8-4cdd-b067-29c93b73679f

#### After
https://github.com/user-attachments/assets/e3d6b165-6f00-47f5-9b75-5e128cb85648

### CODE REVIEW

**Comment by annezazu** [comment]
Tested this and it feels much better! Some oddness I noticed (using Chrome and WP Playground to test) is that sometimes the dropzone under the header and above the footer randomly disappears:

https://github.com/user-attachments/assets/6f76a9d0-6cbc-43bc-8674-5c678e492b9e

I'm not quite sure why it happens and can't quite replicate it clearly. Here's more of the same, along with a VERY tiny notice at the end to "drop files to upload":

Screenshot 2024-10-24 at 12 17 06 PM


https://github.com/user-attachments/assets/a7982ec8-3737-4763-b1d8-34bcd7fc2b50

File: packages/block-editor/src/components/use-block-drop-zone/index.js [hunk 1]
```diff
@@ -287,7 +287,7 @@ function isInsertionPoint( targetToCheck, ownerDocument ) {
 	return !! (
 		defaultView &&
 		targetToCheck instanceof defaultView.HTMLElement &&
-		targetToCheck.dataset.isInsertionPoint
+		targetToCheck.closest( '[data-is-insertion-point]' )
```
Comment (getdave) [inline packages/block-editor/src/components/use-block-drop-zone/index.js:290]: I assume the change was needed because sometimes the target (the element receiving the drag event) is a child of the insertion point element? Maybe the text or a nested element?

Just wanted to check as it stood out.

File: packages/block-editor/src/components/inner-blocks/index.js [hunk 2]
```diff
@@ -202,10 +202,15 @@ export function useInnerBlocksProps( props = {}, options = {} ) {
 				getBlockSettings,
 				getSectionRootClientId,
 			} = unlock( select( blockEditorStore ) );
-			let _isDropZoneDisabled;
 
 			if ( ! clientId ) {
-				return { isDropZoneDisabled: _isDropZoneDisabled };
+				const sectionRootClientId = getSectionRootClientId();
+				// Disable the root drop zone when zoomed out and the section root client id
+				// is not the root block list (represented by an empty string).
```
Comment (getdave) [inline packages/block-editor/src/components/inner-blocks/index.js:209]:
```suggestion
				// Disable the root drop zone when zoomed out and the section root client id
				// is not the root block list (represented by an empty string).
				// This avoids drag handling bugs caused by having two block lists acting as 
				// drop zones - the actual 'root' block list and the section root.
```

Just wanted to add some more context here.

**Review by getdave — APPROVED** [review]
This is so much better! Thank you for tracking this down and fixing @talldan.

For me this is a vast improvement and we should ship it and backport to 6.7.

If there's another edge case with what Anne noticed then we can circle back to that. I certainly cannot replicate it in my testing.

**Comment by ndiego** [comment]
Infinitely better 🎉

File: packages/block-editor/src/components/use-block-drop-zone/index.js (hunk 1 above)
Comment (talldan) [reply packages/block-editor/src/components/use-block-drop-zone/index.js:290]: Yep, there's a child `div` in the insertion point that has the text 'Drop pattern.', so this function would return `false` for it, even though it's part of the insertion point.

**Comment by talldan** [comment]
> Tested this and it feels much better! Some oddness I noticed (using Chrome and WP Playground to test) is that sometimes the dropzone under the header and above the footer randomly disappears

I tried a few times, but it's definitely a tricky one to replicate.

> I'm not quite sure why it happens and can't quite replicate it clearly. Here's more of the same, along with a VERY tiny notice at the end to "drop files to upload"

Oh yep, that one's easy to reproduce using that Patton pattern. I think this is an issue with the cover block's media drop zone.  I'll try to debug it, and if I can make a separate PR.

File: packages/block-editor/src/components/use-block-drop-zone/index.js (hunk 1 above)
Comment (getdave) [reply packages/block-editor/src/components/use-block-drop-zone/index.js:290]: Good catch 👍

**Comment by talldan** [comment]
Seems like the cover block issue is non zoom out related. You can drag any blocks into a cover block, and it seems to think blocks are files 😱 

https://github.com/user-attachments/assets/1f526c78-504c-4a5a-bb0a-2ed9a25ff909

File: packages/block-editor/src/components/inner-blocks/index.js [hunk 3]
```diff
@@ -202,10 +202,17 @@ export function useInnerBlocksProps( props = {}, options = {} ) {
...
+				// This avoids drag handling bugs caused by having two block lists acting as
+				// drop zones - the actual 'root' block list and the section root.
+				return {
+					isDropZoneDisabled:
+						isZoomOut() && sectionRootClientId !== '',
```
Comment (getdave) [inline packages/block-editor/src/components/inner-blocks/index.js:214]: @talldan After this merged I kept getting an error on the `wp/6.7` branch that `isZoomOut` wasn't defined. I'm super confused because during testing it all seemed to work fine but I guess `wp/6.7` removed the `isZoomOut` line on 198.

Fix in https://github.com/WordPress/gutenberg/pull/66420

**Comment by talldan** [comment]
I've made an issue for the Cover Block problems - https://github.com/WordPress/gutenberg/issues/66422

I'm not sure if this is something to include in the 6.7 cycle, it might be an old bug, but it is affecting Zoom Out.

**Comment by getdave** [comment]
> but it is affecting Zoom Out.

Worth a look. Thanks Dan!
