### PR TITLE
TinyMCE use the Core TinyMCE version to avoid conflicts

### LINKED ISSUE #6809: Classic Editor breaks - WP 4.9.6+Gutenberg+Yoast
**Describe the bug**
I just updated one of my sites in my dev environment to WP 4.9.6 and the Classic Editor no longer shows the toolbars, or loads any content.

To narrow down the issue I deactivated all plugins except for Gutenberg and switched my theme to TwentySeventeen.

It seems to be an issue with Yoast. Disabling all plugins except for Gutenberg and it works fine.
As soon as I activate Yoast, the content and TinyMCE no longer load.

The console shows the following error:

**Loading failed for the <script> with source “http://dev.maddisondesigns.com/wp-content/plugins/gutenberg/vendor/themes/modern/theme.min.js?wp-mce-4711-20180425”.**

**To Reproduce**
1. Activate Yoast SEO
2. Update WP to 4.9.6
3. Try to create a new Post using the Classic Editor

**Expected behavior**
The TinyMCE Editor should load properly with all the toolbars and the content should load

**Screenshots**
gutenberg_tinymcenotworking

screenshot_659

macOS Sierra 10.12.1 (16B2659)
Firefox Quantum 60.0 (64-bit)

WordPress 4.9.6
Gutenberg 2.8.0
Yoast SEO  7.5.1

### PR DESCRIPTION
**Pull request by youknowriad**
This PR uses the TinyMCE core scripts instead of using TinyMCE from the CDN to avoid conflicts between the classic editor/wysiwyg metaboxes and the Gutenberg editor.

We're still loading the TinyMCE script two times because there's no registered script for TinyMCE in Core but at least this fixes the compatibility issues.

closes #6809 #6847 #3302 #3731

### CODE REVIEW

**Comment by iseulde** [comment]
Should we require WordPress 4.9.6 with this change?

**Comment by youknowriad** [comment]
@iseulde I thought about this and I think it's fine if we don't, an older version of TinyMCE will be used with probably some small writing flow bugs but Gutenberg still works. @mtias Thoughts?

**Comment by iseulde** [comment]
Hm, not sure if we have a list of all the bugs it will cause. I think it'd be good to avoid a bunch of reports caused merely by an older WordPress version.

File: lib/client-assets.php [hunk 1]
```diff
@@ -76,6 +76,8 @@ function gutenberg_register_scripts_and_styles() {
 	gutenberg_register_vendor_scripts();
 
 	// WordPress packages.
+	wp_register_script( 'wp-tinymce', includes_url( 'js/tinymce/' ) . 'wp-tinymce.php', array( 'jquery' ) );
```
Comment (iseulde) [inline lib/client-assets.php]: Does anything break without the jQuery dependency?

Comment (youknowriad) [reply lib/client-assets.php]: I don't know :) Probably not. It started as a copy/paste from my old PR

File: lib/client-assets.php [hunk 2]
```diff
@@ -495,25 +497,21 @@ function gutenberg_register_vendor_scripts() {
...
 	);
-	$tinymce_version = '4.7.2';
-	gutenberg_register_vendor_script(
-		'tinymce-latest',
-		'https://unpkg.com/tinymce@' . $tinymce_version . '/tinymce' . $suffix . '.js'
-	);
+	$tinymce_version = '4.7.11';
 	gutenberg_register_vendor_script(
 		'tinymce-latest-lists',
 		'https://unpkg.com/tinymce@' . $tinymce_version . '/plugins/lists/plugin' . $suffix . '.js',
```
Comment (iseulde) [inline lib/client-assets.php]: We could load these from core too, except the table plugin. Maybe better like this though.

Comment (youknowriad) [reply lib/client-assets.php]: I thought they were loaded automatically so I removed this but it didn't work. I believe we could use the Core provided once but it's not as urgent as TinyMCE.

File: lib/client-assets.php [hunk 3]
```diff
@@ -495,25 +497,21 @@ function gutenberg_register_vendor_scripts() {
 		'https://unpkg.com/moment@2.22.1/' . $moment_script,
 		array()
 	);
-	$tinymce_version = '4.7.2';
-	gutenberg_register_vendor_script(
-		'tinymce-latest',
-		'https://unpkg.com/tinymce@' . $tinymce_version . '/tinymce' . $suffix . '.js'
-	);
+	$tinymce_version = '4.7.11';
```
Comment (iseulde) [inline lib/client-assets.php]: Ugh too bad we can't base that on https://github.com/WordPress/wordpress-develop/blob/186bb7c8a908de977934d77fc5633b493ba2223f/src/wp-includes/version.php#L21

File: lib/client-assets.php (hunk 1 above)
Comment (iseulde) [reply lib/client-assets.php]: I think it's required for some custom WordPress plugins, but we're not loading those.

**Comment by iseulde** [comment]
Testing with:

```php
add_action( 'add_meta_boxes', function() {
	add_meta_box( 'wp_editor_test_box_1', 'wp_editor() test box', function( $post ) {
		wp_editor( $post->post_content, 'wp_editor_test_1' );
	} );
} );
```

**Review by ellatrix — APPROVED** [review]
Works for me! Just wondering if we should maybe load an unminified version for script debug mode.

**Comment by mtias** [comment]
It's fine to bump the version. But maybe let's wait until 3.0 for doing the bump.

**Comment by rilwis** [comment]
@youknowriad Thanks a lot for the merge!
