### PR TITLE
Ensure that errors reported from uploading font files are not duplicated

### LINKED ISSUE #59484: Font Library: Multiple Fetch errors uploading fonts are difficult to read
### Description

When uploading multiple font files, the error message can be difficult to read if there are multiple fetch errors.

Rather than combing identical messages and formatting different errors as a list, the error message is shown as a single long string, for example:

> No font faces were installed. Fetch error: Demonstration of multiple identical fetch errors. Fetch error: Demonstration of multiple identical fetch errors. Fetch error: Demonstration of multiple identical fetch errors. Fetch error: Demonstration of multiple identical fetch errors. Fetch error: Demonstration of multiple identical fetch errors.

Ideally I think the following would happen in the case of multiple errors:
* duplicate errors are removed
* each error is shown as a list item

No change in the event only one error occurs.

### Step-by-step reproduction instructions

1. Modify `WP_REST_Font_Faces_Controller::handle_font_file_upload()` to simply return a `WP_Error` object
   ```php
   protected function handle_font_file_upload( $file ) {
   return new WP_Error( 'rest_font_fetch_errors', __( 'Demonstration of multiple identical fetch errors.', 'gutenberg' ) );
   }
   ```
2. Open the site editor > Styles > Typography > Typography Manager > Upload
3. Drag multiple font files into the upload window
4. Observe the long string of errors, one for each file

### Screenshots, screen recording, code snippet

Screen Shot 2024-03-01 at 11 35 17 am

### Environment info

- Gutenberg trunk 9957b858fb0657f234b8b392a91996f654256fcf
- WordPress 6.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by pbking**
## What?
Ensure that errors reported from uploading font files are not duplicated

## Why?
Fixes #59484

## How?
Only concat strings that don't exist in the error message string.

## Testing Instructions
Using the 'Upload' tab of the Font Library upload multiple fonts at once.
After the fonts are successfully uploaded upload the SAME fonts again.
Note that the message "A font face matching those settings already exists" is only shown a single time.

image

NOTE: If there are multiple KINDS of messages then those are shown as a list.  (I'm... not sure how to replicate this however, in the below example I just removed the reducing logic and am showing the same message multiple times... which wouldn't actually happen now...)

image

### CODE REVIEW

File: packages/edit-site/src/components/global-styles/font-library-modal/context.js [hunk 1]
```diff
@@ -305,7 +305,14 @@ function FontLibraryProvider( { children } ) {
 						__( 'There were some errors installing fonts. %s' ),
 						installationErrors.reduce(
 							( errorMessageCollection, error ) => {
-								return `${ errorMessageCollection } ${ error.message }`;
+								if (
```
Comment (peterwilsoncc) [inline packages/edit-site/src/components/global-styles/font-library-modal/context.js]: I think it would be good to display them as a list if there remain multiple errors after this. I'm not sure if it's native yet or would require lodash uniq.

Comment (pbking) [reply packages/edit-site/src/components/global-styles/font-library-modal/context.js]: I have formatted multiple errors as a list and changed the language for single error types.  Updated description to show expected output styling.

File: packages/edit-site/src/components/global-styles/font-library-modal/utils/index.js [hunk 2]
```diff
@@ -225,7 +225,7 @@ export async function batchInstallFontFaces( fontFamilyId, fontFacesData ) {
 			// Handle network errors or other fetch-related errors
 			results.errors.push( {
 				data: fontFacesData[ index ],
-				message: `Fetch error: ${ result.reason.message }`,
+				message: result.reason.message,
```
Comment (getdave) [inline packages/edit-site/src/components/global-styles/font-library-modal/utils/index.js:228]: 👍 to passing the real error message without the prefix.

Is it worth guarding against empty reason messages and providing a fallback such as `Unknown error`?

**Review by getdave — APPROVED** [review]
I tested this multiple ways via the UI and I couldn't break it.

Principally I modified `WP_REST_Font_Faces_Controller::handle_font_file_upload()` to simply return a WP_Error object.

I would have liked to have instructions to replicate a scenario where there are multiple _different_ errors so that I could validate the error message printing so if there's a way to do that please let me know.

This is an improvement.

<details>
<summary>Results</summary>

### Before

Multiple duplicated messages which are hard to read and contain a hard coded string `Fetch error`.

https://github.com/WordPress/gutenberg/assets/444434/905c52d9-b286-4bb6-ac1c-8a180bbfa7cb


### After (this PR)

Error messages normalized and formatted.

https://github.com/WordPress/gutenberg/assets/444434/34aec784-b397-4cec-80ec-fc50e92675d1

</details>

I am however noting that a new string is proposed here `There was an error installing fonts. %s` and this is [not allowed during the RC period](https://make.wordpress.org/core/handbook/about/release-cycle/releasing-major-versions/#release-candidate) due to the string freeze.

@pbking are you proposing this is included in WP 6.5 during the RC period? If so could you provide a brief justification for this and it will need to be discussed with the release team? 🙏 

-----

Aside: I fixed the lint error in https://github.com/WordPress/gutenberg/pull/59564/commits/32c20abb809e8f4cc2e2b467911ca21d28c16248.

File: packages/edit-site/src/components/global-styles/font-library-modal/context.js [hunk 3]
```diff
@@ -298,17 +306,27 @@ function FontLibraryProvider( { children } ) {
...
-						installationErrors.reduce(
-							( errorMessageCollection, error ) => {
-								return `${ errorMessageCollection } ${ error.message }`;
-							},
-							''
-						)
+						'<ul>' +
+							installationErrors.reduce(
+								( errorMessageCollection, errorMessage ) => {
+									return `${ errorMessageCollection }<li>${ errorMessage }</li>`;
```
Comment (getdave) [inline packages/edit-site/src/components/global-styles/font-library-modal/context.js]: I noticed that if I

- upload 3 fonts
- upload the same 3 fonts again 

...I see only a single error message `A font face matching those settings already exists.` despite the fact that all three of the fonts were invalid (already existed).

It's a nit: but I wonder if we could include information in the error about the specific font that caused the error?

**Comment by getdave** [comment]
I am however noting that a new string is proposed here `There was an error installing fonts. %s` and this is techically not allowed during the RC period. 

@pbking are you proposing this is included in WP 6.5 during the RC period? If so could you provide a brief justification for this and it will need to be discussed with the release team? 🙏

File: packages/edit-site/src/components/global-styles/font-library-modal/context.js [hunk 4]
```diff
@@ -283,6 +283,14 @@ function FontLibraryProvider( { children } ) {
...
 			}
 
+			installationErrors = installationErrors.reduce(
+				( unique, item ) =>
+					unique.includes( item.message )
+						? unique
+						: [ ...unique, item.message ],
+				[]
+			);
+
```
Comment (matiasbenedetto) [inline packages/edit-site/src/components/global-styles/font-library-modal/context.js:293]: I think this can be simplified 
```js
installationErrors = [ ...new Set( installationErrors.map( item => item.message ) ) ];
```

**Comment by peterwilsoncc** [comment]
> I am however noting that a new string is proposed here `There was an error installing fonts. %s` and this is [not allowed during the RC period](https://make.wordpress.org/core/handbook/about/release-cycle/releasing-major-versions/#release-candidate) due to the string freeze.

It's grammatically incorrect but how do you feel about using the existing string `__( 'There were some errors installing fonts. %s' ),` that is in the wp/6.5 branch? It may be possible to improve in a minor release, although I'd check that with the polyglot team.

**Review by peterwilsoncc — COMMENTED** [review]
This tests well and looks much neater for single and multiple errors.

For the list, would it be possible to add this to the components styles so the list has bullets:

```diff
diff --git a/packages/edit-site/src/components/global-styles/font-library-modal/style.scss b/packages/edit-site/src/components/global-styles/font-library-modal/style.scss
index cfc42aa63a..4f7dce3b8c 100644
--- a/packages/edit-site/src/components/global-styles/font-library-modal/style.scss
+++ b/packages/edit-site/src/components/global-styles/font-library-modal/style.scss
@@ -27,6 +27,11 @@
 	.components-navigator-screen {
 		padding: 3px;
 	}
+
+	.components-notice ul {
+		margin-left: $grid-unit-15;
+		list-style: disc;
+	}
 }
 
 .font-library-modal__tabpanel-layout {
```

The code makes sense to me but I'll let one of the regulars approve it as others have much stronger knowledge of the JavaScript code base.

For testing multiple errors, I changed the return value in the rest controller to:

```php
return new WP_Error( 'rest_font_fetch_errors', __( 'Demonstration of multiple fetch errors ' . rand( 0, 15 ), 'gutenberg' ) );
```

File: packages/edit-site/src/components/global-styles/font-library-modal/context.js [hunk 5]
```diff
@@ -298,17 +306,27 @@ function FontLibraryProvider( { children } ) {
...
+					sprintf(
+						/* translators: %s: Specific error messages returned from server. */
 						__( 'There were some errors installing fonts. %s' ),
-						installationErrors.reduce(
-							( errorMessageCollection, error ) => {
-								return `${ errorMessageCollection } ${ error.message }`;
-							},
-							''
-						)
+						'<ul>' +
```
Comment (youknowriad) [inline packages/edit-site/src/components/global-styles/font-library-modal/context.js]: Isn't it a bit weird to use HTML in error messages?

Comment (getdave) [reply packages/edit-site/src/components/global-styles/font-library-modal/context.js]: If we don't then the multiple message appear on a single line and thus this PR wouldn't solve the problem.

Is there a better way to display multiple error messages whilst controlling the rendered result?

Comment (youknowriad) [reply packages/edit-site/src/components/global-styles/font-library-modal/context.js]: Where is the rendering happening? If we're retrieving this value elsewhere, and we absolutely need to throw an error here, we can create a custom Error class

```
class FontErrors extends Error {
  constructor(serverErrors, ...params) {
    super(...params);
    this.serverErrors = serverErrors;
  }
}
```

Comment (youknowriad) [reply packages/edit-site/src/components/global-styles/font-library-modal/context.js]: Simpler:

```
async function installFonts() { throw { errors: installationErrors } };
installFonts().catch( ( ( { errors } ) => console.log( errors ) );
```

Comment (getdave) [reply packages/edit-site/src/components/global-styles/font-library-modal/context.js]: I should have checked this more carefully and you are of course correct.

We should format the errors are the point of _rendering_ and not in the place where they are processed.

Ideally the component which renders the errors should receive the raw data and then choose how it renders rather than printing HTML.

Comment (getdave) [reply packages/edit-site/src/components/global-styles/font-library-modal/context.js]: @pbking I moved the error formatting in https://github.com/WordPress/gutenberg/pull/59564/commits/18c1af78e782ce5ba87c814cd2ea39f4c50bf84e.

So the errors object that is returned will contain the same error message and potentially the dedicated messages about the specific errors.

I did consider returning [`AggregateError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError) but that looks to be too new to rely on at this time.

Please feel free to tidy and improve my code or reject it.

**Comment by getdave** [comment]
I just cherry-picked this PR to the pick/wp-65-rc-2 branch to get it included in the next release: 77aff9dee7
