### PR TITLE
Fix: QuickEdit: consolidate how "Status > Scheduled" works 

### LINKED ISSUE #76103: QuickEdit: consolidate how "Status > Scheduled" works
Part of https://github.com/WordPress/gutenberg/issues/76076

## What

In the editor inspector, when users set the status field to "Scheduled" they can inmediately set the date as well. They cannot achieve the same in QuickEdit, but they should:

QuickEdit | Editor inspector
--- | ---
Image | Image

## Why

See https://github.com/WordPress/gutenberg/issues/76076 

## How

Replicate the existing behaviour of the editor inspector: make the date field visible when status is scheduled.

### PR DESCRIPTION
**Pull request by hbhalodia**
## What?

Closes https://github.com/WordPress/gutenberg/issues/76103

## Why?
- Need to show the date field, when status in quick edit data form changes to scheduled or future.

## How?

- PR adds the new field called scheduledDateField, which is being rendered only when status is future.

## Testing Instructions

1. Open site editor.
2. View pages in table dataviews.
3. Click on quick edit.
4. Click on status and change status to scheduled.
5. You will notice that we have date selection same as we have in post editor.

### Testing Instructions for Keyboard

- None

## Screenshots or screencast 

https://github.com/user-attachments/assets/8bcdc296-3b51-4301-b8a4-3247c7eecd32

### CODE REVIEW

File: packages/fields/src/fields/date/scheduled/edit.tsx [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+	return (
+		<PrivatePublishDateTimePicker
+			currentDate={ currentDate }
+			onChange={ ( newDate: any ) => onChange( { date: newDate } ) }
+			is12Hour={ is12HourTime }
+			dateOrder={
+				/* translators: Order of day, month, and year. Available formats are 'dmy', 'mdy', and 'ymd'. */
+				_x( 'dmy', 'date order' )
+			}
+			isCompact
```
[the remark this answers is not in the document]
Comment (hbhalodia) [reply packages/fields/src/fields/date/scheduled/edit.tsx]: False positive, had checked the editor it uses the compact one.

File: packages/fields/src/fields/date/scheduled/index.tsx [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+ */
+import type { BasePost } from '../../../types';
+import ScheduledDateEdit from './edit';
+
+const scheduledDateField: Field< BasePost > = {
+	id: 'scheduled_date',
+	type: 'datetime',
+	label: __( 'Scheduled Date' ),
+	getValue: ( { item } ) => item.date,
+	Edit: ScheduledDateEdit,
```
Comment (oandregal) [inline packages/fields/src/fields/date/scheduled/index.tsx]: It'd be best that the existing `date` field and this one use the same Edit component. Meaning that we don't need this custom Edit, we can just reuse the bundled one.

File: packages/editor/src/dataviews/store/private-actions.ts [hunk 3]
```diff
@@ -267,6 +268,7 @@ export const registerPostTypeSchema =
 					discussionField,
 				templateField,
 				passwordField,
+				scheduledDateField,
```
[the remark this answers is not in the document]
Comment (oandregal) [reply packages/editor/src/dataviews/store/private-actions.ts]: This suggestion by copilot is actually a good one that we should apply.

File: packages/fields/src/fields/date/scheduled/index.tsx (hunk 2 above)
Comment (hbhalodia) [reply packages/fields/src/fields/date/scheduled/index.tsx]: Hi @oandregal, Thanks for the suggestion. I initially tend to use the same one, `datetime` on the new scheduled_date field, but the thing is it does not match with the exact post editor screen that we are intend to.

If we need to match the funcationality then datetime will work, but if need to match exact same consistency to post editor screen, customEdit would be the thing to go.

For now, not updating the PR with bundled theme, will wait for the way to go.

See the below screenshots,

| With bundled datetime | With custom Edit | Post Editor screen |
|--------------|------------------|------------------|
| Screenshot 2026-03-06 at 11 06 32 AM | Screenshot 2026-03-06 at 11 08 09 AM | Screenshot 2026-03-06 at 11 09 54 AM |

File: packages/editor/src/dataviews/store/private-actions.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (hbhalodia) [reply packages/editor/src/dataviews/store/private-actions.ts]: Yes, Not sure how its missed, but yes I had applied, may be forget to push the changes 😄. Hence I did resolve from here thinking its pushed.

File: packages/fields/src/fields/date/scheduled/index.tsx (hunk 2 above)
Comment (oandregal) [reply packages/fields/src/fields/date/scheduled/index.tsx]: It's best to start with the bundle one, and iterate from there.

Then, in a follow-up PR, we may offer a compact variant of the `datetime` that only displays the datetime-local input, not the calendar via configuration. Essentially, we'd support something along these lines:

```jsx
Edit: {
  isCompact: true
}
```

and the result would be that only the datetime-local component is displayed.

Comment (hbhalodia) [reply packages/fields/src/fields/date/scheduled/index.tsx]: That makes sense @oandregal, Thanks for the review. I will update the PR shortly with the change and use the bundled one instead of custom edit for now.

Comment (hbhalodia) [reply packages/fields/src/fields/date/scheduled/index.tsx]: Hi @oandregal, The above is now updated. Used the bundled datetime component for both date and scheduled date field.

Comment (hbhalodia) [reply packages/fields/src/fields/date/scheduled/index.tsx]: I do have created a followup issue to track the same - https://github.com/WordPress/gutenberg/issues/76234

**Review by oandregal — APPROVED** [review]
