### PR TITLE
RichText: improve format boundary style

### LINKED ISSUE #14023: Better format boundary design
**Describe the bug**

Currently, the format boundary design is an added, or in some cases an updated, background colour. This doesn't really work well with all formats.

* The link format is an exception, it changes the colour to blue.
* The code format is an exception, it changes the colour to a different gray.
* Custom format would need to include their own styles as it may not work for them. E.g. a colour background button cannot have a background as a boundary style.
* It doesn't work great on different backgrounds, such as the cover image.

**Ideally**, we would need something that:

* Works well with all themes, so that themes do not need to update format boundaries.
* Works well with all formats and potential custom formats.
* Works well on all backgrounds.

I would suggest using:

* `currentColor` as it inherits the text colour, so the contrast will automatically work.
* Something that is *additional* foreground, not background. This is more difficult as it should not interfere with anything the format does. So no underline, as that interferes with links. It should also spread over the whole length. Perhaps an overline? This might not look so good.

The design of this is quite challenging. Cc @jasmussen @karmatosed @kjellr and maybe others (?) for ideas.

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #14023. As discussed in #14023, the boundary style should be updated to inherit the current colour with opacity applied, so the style works in all contexts. This can be done in JS (unfortunately not CSS) but calculating the current colour and applying opacity, then setting it is a global stylesheet.

## How has this been tested?

Format | Before | After
--- | --- | ---
Link in Cover Image | screenshot 2019-02-22 at 11 47 07 | screenshot 2019-02-22 at 11 45 19
Bold in Cover Image | screenshot 2019-02-22 at 11 47 14 | screenshot 2019-02-22 at 11 45 27
Bold in Button | screenshot 2019-02-22 at 11 48 00 | screenshot 2019-02-22 at 11 46 21
Link | screenshot 2019-02-22 at 11 47 46 | screenshot 2019-02-22 at 11 45 54
Colour | screenshot 2019-02-22 at 11 47 21 | screenshot 2019-02-22 at 11 25 00
Bold | screenshot 2019-02-22 at 11 47 29 | screenshot 2019-02-22 at 11 45 41

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by jasmussen** [comment]
Love it. You're the greatest.

I've a bit on my plate today, so I can't do a thorough test. But based on the screenshots, this change is 100% good to go visually.

**Comment by kjellr** [comment]
This is looking great, @ellatrix! I tested it out with a bunch of different color/image backgrounds, and it works well. The only issue I'm seeing is that it's outputting the color as `rgb()` with an extra alpha parameter. For example: `rgb(25, 30, 35, 0.2);`.

Firefox and Chrome are fine with this, but Safari drops this rule entirely: 

Screen Shot 2019-03-20 at 4 58 13 PM

If we can get that to spit out a `rgba()` color instead, this should be good to go.

**Comment by ellatrix** [comment]
@kjellr Nice catch! Fixed now.

**Review by kjellr — APPROVED** [review]
🎉 Works great. Thanks @ellatrix!

File: packages/block-editor/src/components/rich-text/index.js [hunk 1]
```diff
@@ -793,6 +820,9 @@ export class RichText extends Component {
 			}
 		}
 
+		// Wait for boundary class to be added.
+		setTimeout( () => this.recalculateBoundaryStyle() );
```
Comment (aduth) [inline packages/block-editor/src/components/rich-text/index.js]: This is not a safe timeout, despite the component being wrapped with `withSafeTimeout`. I suspect it may be the reason behind some failings I'm seeing in master E2E tests:

https://travis-ci.com/WordPress/gutenberg/jobs/187954533

```
FAIL packages/e2e-tests/specs/blocks/quote.test.js (41.221s)
  ● Quote › can be merged into from a paragraph
    TypeError: Cannot read property 'querySelector' of undefined
      at t.value (../../http:/localhost:8889/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=1553629058:55:141215)
      at ../../http:/localhost:8889/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=1553629058:55:144735
      at Suite.it (specs/blocks/quote.test.js:180:2)
```

Where one of the few occurrences of `querySelector` in `block-editor` is within `recalculateBoundaryStyle` ([referencing the component's `ref`](https://github.com/WordPress/gutenberg/blob/59b03c0c549619d8561e2d1c0d6d6c6b4c008d31/packages/block-editor/src/components/rich-text/index.js#L504), which would be [unset after unmount](https://github.com/WordPress/gutenberg/blob/59b03c0c549619d8561e2d1c0d6d6c6b4c008d31/packages/block-editor/src/components/rich-text/index.js#L169)). It seems reasonable that it could cause an error, if the component were to become unmounted after the `setTimeout` is scheduled.
