### PR TITLE
Block toolbar: fix error

### LINKED ISSUE #20429: The Block Toolbar is not showing up properly in the new widgets screen
There's also this JavaScript error

Capture d’écran 2020-02-25 à 9 33 41 AM

I think it's due to the BlockToolbar extraction to a Popover.

cc @ellatrix @jorgefilipecosta 

(Same in the customizer view)

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #20429.

This is a potential solution, but I'm not sure if it's the best.

The problem is that a popover slot may not always be provided, so the popover may not have a parent element with the `popover-slot` class.

Either we:

* Add the `popover-slot` class to the root container. Not a very clean solution, but it work when the popover is rendered in place (not in a slot). We could change the class to something else if necessary.
* Require the toolbar to render in the slot. (I don't think we should require this.)
* Not use the popover slot div at all, but use a reference or class provided to `Popover` to determine what the boundary container is.

Perhaps the last solution is the best?

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by youknowriad** [comment]
Something I don't understand I do see `<Popover.Slot />` used in both `edit-widgets` and `edit-site` though?

**Comment by ellatrix** [comment]
@youknowriad But not `<Popover.Slot name="block-toolbar" />`?

**Comment by ellatrix** [comment]
I think we might have to require it. Rendering the toolbar inline is not good since tabbing to it is broken then.

**Comment by youknowriad** [comment]
Can we render it automatically at the beginning of `<BlockList />` ?

**Comment by ellatrix** [comment]
That wouldn't work. It needs to be rendered outside of the writing flow. More specifically, outside the focus capture elements. It could be built into WritingFlow though. I do wish WritingFlow was built into BlockList...

**Comment by youknowriad** [comment]
> I do wish WritingFlow was built into BlockList...

Me too :) I think the only thing prevent this is the PostTitle component in Gutenberg which in theory we could fix by duplicating some "arrow navigation handling in PostTitle" maybe?

**Comment by ellatrix** [comment]
I think ideally the post title needs to be some sort of real block. We can also not move the post title out of writing flow, otherwise reverse tabbing from the content will focus it. :) Either it needs to be a block, or we should provide a slot at the top of the block list to render the title in it from the outside?

**Comment by ellatrix** [comment]
I actually had already tried to move the popover slot to writing flow in #19431, but ran into some issues with reusable blocks I think.

**Comment by youknowriad** [comment]
So maybe for now, let's just add the slot to the right position in the different screen/playground?

**Comment by ellatrix** [comment]
Yes, either that, or we explicitly pass the boundary container to the popover. I'll add the slots for now so it's at least no longer broken

File: packages/edit-widgets/src/components/layout/index.js [hunk 1]
```diff
@@ -38,6 +38,7 @@ function Layout( { blockEditorSettings } ) {
 							content={
 								<>
 									<Notices />
+									<Popover.Slot name="block-toolbar" />
```
Comment (youknowriad) [inline packages/edit-widgets/src/components/layout/index.js]: I'm wondering if we want one slot per widget area here or a single slot for the whole page. It's not clear how we should reason about this particular slot, where to put it if you're building your own editor. (maybe needs some docs)

Also, do we want to expose it as a `BlockToolbarSlot` in @wordpress/block-editor package?

Comment (ellatrix) [reply packages/edit-widgets/src/components/layout/index.js]: That's the thing... I was hoping that we could build it into WritingFlow or BlockList (together with WritingFlow or something) to avoid exposing it. But maybe there's no other way. I also had an earlier idea to unify it with the top toolbar, in which case exposing it maybe makes more sense.

Comment (youknowriad) [reply packages/edit-widgets/src/components/layout/index.js]: Ok, got it. I'm fine if we wait more and see if we can consolidate.

Comment (youknowriad) [reply packages/edit-widgets/src/components/layout/index.js]: What about the widgets screen question?

Comment (ellatrix) [reply packages/edit-widgets/src/components/layout/index.js]: I don't know so much about the widgets. Did I currently add one slot for all areas? If that works, that seems fine? What do you think?

Comment (youknowriad) [reply packages/edit-widgets/src/components/layout/index.js]: I think the tabbing order might not be great with this solution but at least the toolbar is showing.

**Review by youknowriad — APPROVED** [review]

File: packages/edit-widgets/src/components/layout/index.js (hunk 1 above)
Comment (ellatrix) [reply packages/edit-widgets/src/components/layout/index.js]: Oh, I guess it might be better to have one per area then. Let's iterate on it. Worth noting that previously, it wasn't possible to tab to the toolbar at all because it was mounted inside WritingFlow.

**Comment by ellatrix** [comment]
Thanks!
