### PR TITLE
[Block: Navigation link] Fix PHP notice

### LINKED ISSUE #34883: Error with navigation-link.php
### Description

I am getting the following error in the front end.
Notice: Trying to get property 'post_status' of non-object in /Users/lwangdu/Sites/fullsiteediting/wp-content/plugins/gutenberg/build/block-library/blocks/navigation-link.php on line 133

### Step-by-step reproduction instructions

Create new post. Permalink section > click on view post.

### Screenshots, screen recording, code snippet

Screen Shot 2021-09-16 at 7 40 12 AM

### Environment info

WordPress 5.8.1, Gutenberg version 11.5.0 Theme TT1 Blocks
Browser: Chrome
MAC OS Version 11.6

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by carolinan**
## Description

Closes #34883.
Avoid checking for post status if the post ID does not exist.

Post ID's that does not exist can occur for example when a template with a navigation block is saved and exported and used on 
another website, or if someone edits the ID incorrectly.

## How has this been tested?

1. Create a new post or page. Open the code editor.
2. Copy & paste this example code for the navigation link. **The ID needs to be a post ID that does not exist.**
```
<!-- wp:navigation -->
<!-- wp:navigation-link {"label":"Test","type":"page","id":111111,"url":"http://localhost:8888/test/","kind":"post-type","isTopLevelLink":true} /-->
<!-- /wp:navigation -->
```
3. Save and view the front, there should be no PHP notice.
4. View the post or page in the site editor, there should be no PHP notice.

## Types of changes

Bug fix 

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-library/src/navigation-link/index.php [hunk 1]
```diff
@@ -127,10 +127,10 @@ function render_block_core_navigation_link( $attributes, $content, $block ) {
 	$is_post_type           = isset( $attributes['kind'] ) && 'post-type' === $attributes['kind'];
 	$is_post_type           = $is_post_type || isset( $attributes['type'] ) && ( 'post' === $attributes['type'] || 'page' === $attributes['type'] );
 
-	// Don't render the block's subtree if it is a draft.
+	// Don't render the block's subtree if it is a draft or if the ID does not exist.
 	if ( $is_post_type && $navigation_link_has_id ) {
 		$post = get_post( $attributes['id'] );
-		if ( 'publish' !== $post->post_status ) {
+		if ( ! isset( $post ) || 'publish' !== $post->post_status ) {
```
Comment (spacedmonkey) [inline packages/block-library/src/navigation-link/index.php]:
```suggestion
		if ( ! ( $post instanceof WP_Post ) || 'publish' !== $post->post_status ) {
```

Comment (spacedmonkey) [reply packages/block-library/src/navigation-link/index.php]:
```suggestion
		if ( 'publish' !== get_post_status( $attributes['id'] ) ) {
```

Comment (carolinan) [reply packages/block-library/src/navigation-link/index.php]: Thank you for the review @spacedmonkey. Can you include a note about which of the two proposed changes is the preferred solution, and why? It would help me out.

Comment (carolinan) [reply packages/block-library/src/navigation-link/index.php]: I am leaning towards `get_post_status` (and removing `$post = get_post( $attributes['id'] );` 
but I do not know which is most performant. Untested.

Comment (spacedmonkey) [reply packages/block-library/src/navigation-link/index.php]: isset is simple not the right check here. Isset is used to check if key is set on an array. ``` isset( $array['key'] )```. 

You need to check if `get_post` returns a `WP_Post` object. 

I agree that `get_post_status( $attributes['id'] )` is very clean.

Comment (aristath) [reply packages/block-library/src/navigation-link/index.php]: Technically, `isset` will work, so it's not wrong... According to the PHP docs,
> Determine if a variable is considered set, this means if a variable is declared and is different than **null**.

but on the other hand, `isset()` is not required here.
Since `get_post` returns either `WP_Post` or `null`, `! isset( $post )` can just be written `! $post`. Or `null === $post`. But that's just a matter of personal preference and there's nothing wrong with it 🤷

**Review by Mamaduka — APPROVED** [review]
