### PR TITLE
Navigation Block: Fix erroneous escaping of ampersands (etc)

### LINKED ISSUE #59516: Ampersand's in the Navigation block are converted to u0026
### Description

Adding ampersands '&' to the label field of a link (page & custom) in the Navigation block converts it to u0026, which displays on the frontend and backend once refreshed.

### Step-by-step reproduction instructions

1. Go to the latest 6.5-beta3 (or nightly) on your test site, or in playground: https://playground.wordpress.net/?php=8.0&wp=beta&storage=none
2. Edit site, and add a link to the navigation block.
3. Include an ampersand in the label of a link in the block, an example being 'News & Events'
4. View the frontend of the site and see it converted to 'u0026'

### Screenshots, screen recording, code snippet

Screenshot 2024-03-01 at 4 39 24 PM
Screenshot 2024-03-01 at 4 38 17 PM

### Environment info

- WordPress 6.5 beta3 & Nightly
- Tested and seen with both Gutenberg not installed, and installed and activated.
- Tested in both latest Chrome & Firefox

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ockham**
## What?
Fix erroneous escaping of ampersands to `u0026amp;`. 

## Why?
To fix #59516. Since these "entities" are missing a leading backslash, it them to show up verbatim on the frontend!

Screenshot 2024-03-01 at 4 38 17 PM

## How?
By using the [`rest_pre_insert_{$this->post_type}`](https://developer.wordpress.org/reference/hooks/rest_pre_insert_this-post_type/) _filter_ rather than the `rest_insert_wp_navigation` _action_. This avoids calling `wp_update_post` twice, which was the original reason of the issue, as it removed the backslash from the already-encoded entity.

(Note that the fact that encoded entities are sent over the wire in the first place is due to a quirk in the Navigation block: https://github.com/WordPress/gutenberg/pull/41063.)

## Testing Instructions
(See CI, or run `npm run test:php` locally.)

## Related

https://core.trac.wordpress.org/ticket/60671 seems to be related

### CODE REVIEW

File: phpunit/blocks/block-navigation-block-hooks-test.php [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+				'block_hooks' => array(
+					'core/navigation' => 'last_child',
+				),
+			)
+		);
+
+		$post = get_post( self::$navigation_post );
+
+		gutenberg_block_core_navigation_update_ignore_hooked_blocks_meta( $post );
+		$this->assertSame( self::$original_markup . '<!-- wp:tests/my-block /-->', $post->post_content );
```
Comment (ockham) [inline phpunit/blocks/block-navigation-block-hooks-test.php]: This is currently failing, but apparently _not_ because of #59516:

 ```
1) Block_Navigation_Block_Hooks_Test::test_block_core_navigation_update_ignore_hooked_blocks_meta
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'<!-- wp:navigation-link {"label":"News & About","type":"page","id":2,"url":"http://localhost:8888/?page_id=2","kind":"post-type"} /--><!-- wp:tests/my-block /-->'
+'<!-- wp:navigation-link {"label":"News \u0026amp; About","type":"page","id":2,"url":"http://localhost:8888/?page_id=2","kind":"post-type"} /-->'
```

(Note that `&` is being escaped to `\u0026amp;`, which seems correct. Most importantly, the leading slash is retained.)

**Comment by ockham** [comment]
cc/ @tjcafferkey @t-hamano

File: phpunit/blocks/block-navigation-block-hooks-test.php [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+		$this->assertSame( array( 'tests/my-block' ), get_post_meta( $post, '_wp_ignored_hooked_blocks' ) );
```
Comment (ockham) [inline phpunit/blocks/block-navigation-block-hooks-test.php]: This assertion is currently failing, so it looks like hooked blocks aren't properly injected (and the `_wp_ignored_hooked_blocks` meta field isn't properly set).

Comment (t-hamano) [reply phpunit/blocks/block-navigation-block-hooks-test.php]: Is the first argument of `get_post_meta` `$post->ID`? Additionally, it looks like `get_post_meta` should be retrieved as a single value and the JSON should be decoded.

```php
$this->assertSame( array( 'tests/my-block' ), json_decode( get_post_meta( $post->ID, '_wp_ignored_hooked_blocks', true ), true ) );
```

There may be an easier way to write.

Comment (ockham) [reply phpunit/blocks/block-navigation-block-hooks-test.php]: Ah, you're right! 😄 I thought `get_post_meta` was one of those functions that accepted either an ID or a `WP_Post` object, but I was wrong 😅 

Fixed in 25285414a04.

**Comment by ockham** [comment]
Okay, I've now managed to fix the assertions, and to [add a new one](https://github.com/WordPress/gutenberg/pull/59561/commits/d08b830b7193629856c1f32e4bdd29f31ecf8846) that actually fails and captures the problem in https://github.com/WordPress/gutenberg/issues/59516.

This should hopefully make it easier to track down the problem.

**Comment by ockham** [comment]
(Oops, fat-fingered the Close button, and then "Delete branch" 😅 )

**Comment by ockham** [comment]
> Okay, I've now managed to fix the assertions, and to [add a new one](https://github.com/WordPress/gutenberg/pull/59561/commits/d08b830b7193629856c1f32e4bdd29f31ecf8846) that actually fails and captures the problem in #59516.
> 
> This should hopefully make it easier to track down the problem.

I also just reverted https://github.com/WordPress/gutenberg/commit/467aade14ccae801b96778740666ef2298972a59 (i.e. #59021) locally and ran the tests again. This makes the first two assertions pass (and only the post meta related one fail, as expected), confirming that the unit test covers the bug 👍

**Comment by ockham** [comment]
Here are some tests I ran against https://github.com/WordPress/wordpress-develop:

```diff
diff --git a/tests/phpunit/tests/post/getTheContent.php b/tests/phpunit/tests/post/getTheContent.php
index 91f0b621f3..d9030080db 100644
--- a/tests/phpunit/tests/post/getTheContent.php
+++ b/tests/phpunit/tests/post/getTheContent.php
@@ -84,4 +84,24 @@ class Tests_Post_GetTheContent extends WP_UnitTestCase {
 
 		$this->assertSame( 'Foo', get_the_content() );
 	}
+
+	public function test_the_content_block_attribute_escaping_1() {
+		$unescaped = '<!-- wp:navigation-link {"label":"News & About","type":"page","id":2,"url":"http://localhost:8888/?page_id=2","kind":"post-type"} /-->';
+		$escaped   = str_replace( '&', '\u0026amp;', $unescaped );
+
+		$post = self::factory()->post->create_and_get( array( 'post_content' => $unescaped ) );
+
+		$actual = get_the_content( null, true, $post );
+		$this->assertSame( $escaped, $actual );
+	}
+
+	public function test_the_content_block_attribute_escaping_2() {
+		$unescaped = '<!-- wp:navigation-link {"label":"News & About","type":"page","id":2,"url":"http://localhost:8888/?page_id=2","kind":"post-type"} /-->';
+		$escaped   = str_replace( '&', '\u0026amp;', $unescaped );
+
+		$post = self::factory()->post->create_and_get( array( 'post_content' => $escaped ) );
+
+		$actual = get_the_content( null, true, $post );
+		$this->assertSame( $escaped, $actual );
+	}
 }
```

(Note that `test_the_content_block_attribute_escaping_1` creates the post object with the `&` unescaped, whereas `test_the_content_block_attribute_escaping_2` creates it with the `&` replaced by `\u0026amp;`.)

This results in:

```
There was 1 failure:

1) Tests_Post_GetTheContent::test_the_content_block_attribute_escaping_2
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'<!-- wp:navigation-link {"label":"News \u0026amp; About","type":"page","id":2,"url":"http://localhost:8888/?page_id=2","kind":"post-type"} /-->'
+'<!-- wp:navigation-link {"label":"News u0026amp; About","type":"page","id":2,"url":"http://localhost:8888/?page_id=2","kind":"post-type"} /-->'

/var/www/tests/phpunit/tests/post/getTheContent.php:105
```

**I think this means that we need to run `wp_update_post` with the `&` unescaped, as it appears that slashes are otherwise stripped from the content.**

This is backed up by a finding that @tjcafferkey just relayed to me: https://github.com/WordPress/wordpress-develop/blob/7002bce8abe6f6f1858bdd2f02cd1168ef50e4d8/src/wp-includes/post.php#L4532

**Comment by ockham** [comment]
Heads-up @getdave @youknowriad -- this is a WIP fix for https://core.trac.wordpress.org/ticket/60671, which is IMO problematic enough that we should get it into RC1. I think we're pretty close to resolving it (within the next 1-2 hours 🤞); it will then require a package sync. Does that work for y'all?

**Comment by youknowriad** [comment]
> (within the next 1-2 hours 🤞);

That seems very tight, because we'll need one hour more to do the package release commit approximately and the commit freeze is approaching. Worst case, it lands in RC2.

**Comment by ockham** [comment]
> > (within the next 1-2 hours 🤞);
> 
> That seems very tight, because we'll need one hour more to do the package release commit approximately and the commit freeze is approaching. Worst case, it lands in RC2.

Gotcha, thank you! I'll keep you posted on our progress.

**Comment by ockham** [comment]
I think I have an idea how to solve this. I don't think there's a function in WP to _un_escape stuff like `\u0026amp;`, so instead, let's try to find a _filter_ to hook `block_core_navigation_update_ignore_hooked_blocks_meta` into (rather than an action). This should allow us to avoid the extraneous call to `wp_update_post`.

(We'll still call `update_post_meta` from the filter, which is probably okay to have as a side-effect.)

**Comment by ockham** [comment]
The fix should be essentially working now. I'll have to update the unit test to reflect the changes (plus the PR title and description).

File: packages/block-library/src/navigation/index.php [hunk 3]
```diff
@@ -1497,8 +1496,15 @@ function block_core_navigation_update_ignore_hooked_blocks_meta( $post ) {
 
 // Injection of hooked blocks into the Navigation block relies on some functions present in WP >= 6.5
 // that are not present in Gutenberg's WP 6.5 compatibility layer.
-if ( function_exists( 'set_ignored_hooked_blocks_metadata' ) && ! has_filter( 'rest_insert_wp_navigation', $rest_insert_wp_navigation_core_callback ) ) {
-	add_action( 'rest_insert_wp_navigation', 'block_core_navigation_update_ignore_hooked_blocks_meta', 10, 3 );
+if ( function_exists( 'set_ignored_hooked_blocks_metadata' ) && ! has_filter( 'rest_pre_insert_wp_navigation', $rest_insert_wp_navigation_core_callback ) ) {
+	add_filter( 'rest_pre_insert_wp_navigation', 'block_core_navigation_update_ignore_hooked_blocks_meta', 10, 2 );
```
Comment (ockham) [inline packages/block-library/src/navigation/index.php]: We're now only passing one argument ($post), which happens to be the default value for [`add_filter`](https://developer.wordpress.org/reference/functions/add_filter/)'s `$accepted_args`.

```suggestion
	add_filter( 'rest_pre_insert_wp_navigation', 'block_core_navigation_update_ignore_hooked_blocks_meta', 10 );
```

**Review by tjcafferkey — APPROVED** [review]
This change tests well for me, thanks @ockham! 🙏🏻 

One TODO for later I think we can do to make this more clear is documenting the differences between the purposes of the incoming `$post` (the `stdClass`) which is being prepared to be written to the DB vs the `get_post( $post->ID )` (the `WP_Post` class) which is being retrieved from the DB. The latter mainly (I say _mainly_ because its also used to retrieve meta) being used to provide context to the Block Hooks API

**Comment by ockham** [comment]
Note to self: Unit tests aside, we should verify that this also fixes https://core.trac.wordpress.org/ticket/60671.

**Comment by draganescu** [comment]
Why does using the `rest_insert_wp_navigation` action result in calling `wp_update_post` twice?

**Comment by ockham** [comment]
> Why does using the `rest_insert_wp_navigation` action result in calling `wp_update_post` twice?

See the [diff](https://github.com/WordPress/gutenberg/pull/59561/files#diff-90cb5b64c95087ded3c7bb160e38189c8499b0f14f61beb884c887452449fa12L1485-L1490).

The reason we needed it in the first place was that we needed to persist the post content to the DB, after having inserted hooked blocks. We originally chose the `rest_insert_wp_navigation` action as it gave direct access to the post object that had been created previously, which allowed us to avoid [this logic](https://github.com/WordPress/gutenberg/pull/59561/files#diff-90cb5b64c95087ded3c7bb160e38189c8499b0f14f61beb884c887452449fa12R1467-R1472).

However, since the duplicated `wp_update_post` call has the nasty side effect of messing up entities, it's preferable to go with the filter (which allows operating on the post content before it is written to the DB, thus limiting the number of `wp_update_post` calls to only one).

**Comment by getdave** [comment]
This fix is critical to ensure correct behaviour of the Navigation block in WP 6.5. Without this blocks would start outputting erroneous characters on the front of the site which would constitute a bug in 6.5 but also break backwards compatbility with previous releases.

I was also identified during the RC 1 phase.

For these reasons I believe this PR is suitable for inclusion in WP 6.5 during the RC phase.

**Comment by getdave** [comment]
I just cherry-picked this PR to the pick/wp-65-rc-2 branch to get it included in the next release: b455d76820
