### PR TITLE
Stop trying to autosave when title and classic block content both are empty.

### LINKED ISSUE #6556: 400 bad request trying to autosave empty content
## Issue Overview

When adding a new post I got an unexpected "Updating failed" message.
The console log showed  400 bad request.
The response being 
```
{"code":"empty_content","message":"Content, title, and excerpt are empty.","data":{"status":400}}
```

## Steps to Reproduce (for bugs)

1. Add a new post.
2. Insert a Classic block
3. Wait a while

## Expected Behavior

Either no attempt to save the post or allow the empty content to be saved.

## Current Behavior
Autosave kicks in. Since none of the following have been entered... Title, Content and Excerpt
we get the 400 Bad request. which leads to the display of the unexpected "Updating failed" message. 

## Related Issues and/or PRs

#1201

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by rahulsprajapati**
## Description

Fixes: #6556

Add check in getBlocksForSerialization when single classic block ( core/freeform ) is available with empty content. 

https://github.com/WordPress/gutenberg/blob/69ced17277dceca17b3253a6d53f5cfb35eecfad/packages/editor/src/store/selectors.js#L372-L381

## How has this been tested?

Post autosave is not triggerd when one classic block content is availble and it's empty.
Screencast: https://drive.google.com/file/d/1p6HfNi7I6_57y8mbLhe9J8HTU4lAq--6/view

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Review by danielbachhuber — APPROVED** [review]
👍 I've tested this locally and confirm autosave doesn't run until some text is entered in the post content.

I'll defer to @aduth or @youknowriad on the underlying JavaScript

**Review by aduth — CHANGES_REQUESTED** [review]
My suggestion noted at https://github.com/WordPress/gutenberg/issues/6556#issuecomment-427099695 would avoid the need to inspect specific attributes of the block, rather relying on the existing serializer behavior to be performed, testing the result of which as being non-empty to determine whether a save can occur.

Pseudo-code:

```js
const isEditedPostEmpty = ( state ) => ! hasKnownBlock( state ) && ! getEditedPostAttribute( state, 'content' ) 

const hasKnownBlock = ( state ) => getBlockOrder( state ).some( ( clientId ) => (
	state.editor.current.blocksByClientId[ clientId ].name !== getUnknownTypeHandlerName()
) );
```

(In second function, I avoid `getBlocks` because it has a non-trivial cost to execute)

**Comment by rahulsprajapati** [comment]
Sure @aduth, I'll look into this feedbacks and update this PR soon.

**Comment by danielbachhuber** [comment]
@rahulsprajapati Any chance you can finish this up Thursday (10/17) IST so we can get this landed?

File: packages/editor/src/store/selectors.js [hunk 1]
```diff
@@ -1419,6 +1420,17 @@ export function getBlocksForSerialization( state ) {
 		return [];
 	}
 
+	// A single empty core/freeform block equivalent to an empty post.
+	const isSingleEmptyFreeformBlock = (
+		blocks.length === 1 &&
+		blocks[ 0 ].name === 'core/freeform' &&
```
[the remark this answers is not in the document]
Comment (rahulsprajapati) [reply packages/editor/src/store/selectors.js]: Updated this with `getUnknownTypeHandlerName`,

File: packages/editor/src/store/selectors.js [hunk 2]
```diff
@@ -1419,6 +1420,17 @@ export function getBlocksForSerialization( state ) {
...
+		( isEmpty( blocks[ 0 ].attributes ) || blocks[ 0 ].attributes.content === '' )
```
[the remark this answers is not in the document]
Comment (rahulsprajapati) [reply packages/editor/src/store/selectors.js]: Hey, I think I'm confused about this. Can you give me more( simple ) detail? 
Sorry, Gutenberg and react is still new for me so I might not be doing this right.

[the remark this answers is not in the document]
Comment (aduth) [reply packages/editor/src/store/selectors.js]: Sorry for being unclear. In short: We shouldn't pretend to know anything about what attributes do or don't exist here, because it will make our lives more difficult later if we ever need to change the attributes.

It's not entirely relevant if we consider the recommendation at https://github.com/WordPress/gutenberg/pull/10404#pullrequestreview-163431784

**Review by aduth — CHANGES_REQUESTED** [review]
As of #8274, `getUnknownTypeHandlerName` has been replaced by two functions `getFreeformFallbackBlockName` and `getUnregisteredFallbackBlockName`.

You'll need to [update your branch](https://www.atlassian.com/git/tutorials/merging-vs-rebasing) to bring in the latest `master` changes.

File: packages/editor/src/store/selectors.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (rahulsprajapati) [reply packages/editor/src/store/selectors.js]: ok, yeah sure. Got it we should not use specific attribute name from a direct object and dependent on that. Also, this one is just checking for one empty block there might be more so it would be better if we check in all blocks in the current state. https://github.com/WordPress/gutenberg/pull/10404#pullrequestreview-163431784

I'll update this occordingly.

**Comment by rahulsprajapati** [comment]
> As of #8274, getUnknownTypeHandlerName has been replaced by two functions getFreeformFallbackBlockName and getUnregisteredFallbackBlockName.

sure, will update this.

File: packages/editor/src/store/selectors.js [hunk 3]
```diff
@@ -360,6 +361,20 @@ export function isEditedPostSaveable( state ) {
 	);
 }
 
+/**
```
Comment (aduth) [inline packages/editor/src/store/selectors.js]: One of the test failures is due to the fact that documentation needs to be regenerated by `npm run docs:build`.

File: packages/editor/src/store/selectors.js [hunk 4]
```diff
@@ -375,7 +390,7 @@ export function isEditedPostEmpty( state ) {
 	// operation by comparison. Since this function can be called frequently,
 	// optimize for the fast case where saveable blocks are non-empty.
 	return (
-		! getBlocksForSerialization( state ).length &&
```
Comment (aduth) [inline packages/editor/src/store/selectors.js]: Hmm, in retrospect my original suggestion may have been made at a time before we'd considered the extra condition added by `getBlocksForSerialization` to consider the empty paragraph (see #9808). I've got to imagine this change here regresses on that intended behavior. 

Maybe we should update `hasKnownBlocks` to accept `blocks` as an argument, so we can pass the result of `getBlocksForSerialization` to use in place of `getBlockOrder`.

File: packages/editor/src/store/selectors.js [hunk 5]
```diff
@@ -360,6 +361,20 @@ export function isEditedPostSaveable( state ) {
...
+ * Determines whether all the block available in post are known or registered block or not.
+ *
+ * @param {Object} state Global application state.
+ *
+ * @return {boolean} whether all the block available in post are known block or not.
+ */
+export function hasKnownBlocks( state ) {
+	return getBlockOrder( state ).some( ( clientId ) => (
+		state.editor.present.blocksByClientId[ clientId ].name !== getFreeformContentHandlerName() &&
+		state.editor.present.blocksByClientId[ clientId ].name !== getUnregisteredTypeHandlerName()
```
Comment (aduth) [inline packages/editor/src/store/selectors.js]: The split of these two functions has me wondering if the semantics are meaningfully different enough to consider. "Unknown" would be _truly_ a block, with demarcations, and thus non-empty for save. I think what we're really targeting is specifically freeform content.

Thus, I think we don't need this line and it could be dropped.

In doing so, and in reconsideration of targeting specifically freeform content, I wonder if the function name we've chosen `hasKnownBlocks` is very accurate. I'll need to sit and think on this one...

Comment (rahulsprajapati) [reply packages/editor/src/store/selectors.js]: > I wonder if the function name we've chosen hasKnownBlocks is very accurate. I'll need to sit and think on this one...

If we are just going to check that the post have any freeform block or not then `hasFreeFromBlock` name will be more suitable for this.

Comment (aduth) [reply packages/editor/src/store/selectors.js]: That name seems to suit the purpose, but it highlights to me that it's _so specific_ to the `isEditedPostEmpty` use-case that we might be better off to include the logic there, rather than to expose a new separate selector.

Thinking something like (haven't verified the logic):

```js
export function isEditedPostEmpty( state ) {
	const blocks = getBlocksForSerialization( state );
	if ( ! blocks.length ) {
		return true;
	}

	const freeformBlockName = getFreeformContentHandlerName();
	if ( ! some( blocks, { name: freeformBlockName } ) ) {
		return false;
	}

	// Content serialization is considered an expensive operation, and should
	// only be considered after more trivial operations of assuming presence of
	// non-freeform blocks as implying that serializable content exists.
	return ! getEditedPostAttribute( state, 'content' );
}
```

Comment (rahulsprajapati) [reply packages/editor/src/store/selectors.js]: @aduth This works correctly.

**Comment by aduth** [comment]
There appear to be some test failures for the impacted selectors.

**Comment by rahulsprajapati** [comment]
Great. I'll look into tests failure.

File: packages/editor/src/store/selectors.js (hunk 5 above)
Comment (sanketio) [reply packages/editor/src/store/selectors.js]: @rahulsprajapati @aduth : You, the code works correctly, but while writing test cases for this, existing test case `should return false if edits include a non-empty content property` fails. So I think need to check for a more suitable solution. What do you guys say?

**Comment by aduth** [comment]
I looked over the tests and found that we had a few issues in their authoring:

- We assumed `core/freeform` was the name of the freeform handler, but this is not assigned in the test environment (intentionally so).
   - The tests now register and set a freeform content handler test block
- The block entries lacked a necessary `isValid` flag which is important for [consideration by the block serializer](https://github.com/WordPress/gutenberg/blob/3503c0d08a18ad2036fc0329be82dcbbd8e03e4e/packages/blocks/src/api/serializer.js#L210)

I also discovered a completely separate bug in our optimization of blocks existing, in that a `content` edit should always take precedence. This can occur if, for example, the post has blocks but the user switches to the Code Editor mode and removes all content. It's my understanding based on the current implementation in `master` that this would be an existing issue, solved in the most recent commit by considering the `content` edit.

I've further revised the implementation to avoid `Array#some`, since we can be certain that if there is more than one block, even if both blocks are the freeform block, and both freeform blocks produce an empty save result, that the overall serialized result would still be non-empty thanks to the [`Array#join` which occurs in the serializer](https://github.com/WordPress/gutenberg/blob/3503c0d08a18ad2036fc0329be82dcbbd8e03e4e/packages/blocks/src/api/serializer.js#L283). This allows us to consider a trivial operation (and common occurrence) of `blocks.length > 1` as non-empty.

**Review by aduth — APPROVED** [review]

**Comment by rahulsprajapati** [comment]
Thank you @aduth for the explanation. 🙂

I was looking over the test only and was wondering why it's failing when the test case was correct and then just found that free-form was not detected with `getFreeformContentHandlerName()`  but I guess got too slow 😅

**Comment by danielbachhuber** [comment]
I've manually verified that autosave doesn't fire when Title is empty and the post only has a Classic Block.

Thanks for your work on this @rahulsprajapati, @aduth, @sanketio
