### PR TITLE
Updates the behavior of the top toolbar fixed setting

### LINKED ISSUE #40450: Top Toolbar improvements
The top toolbar has stagnated a bit while the feature set of the editor has evolved. The following design addresses the most pertinent issues including:

1. The lack of parent selector for nested blocks
2. The overall increase in editor UI footprint

Screenshot 2023-01-04 at 11 35 42

<details><summary>Original issue</summary>
In particular, the now established block parent selector is missing when top toolbar is enabled, which makes selecting some wrappers particularly challenging (group and gallery, for example). The layout also doesn't feel quite right with the block type not being aligned with the [+], and it becoming somewhat inconvenient on larger screens.

I propose we explore these two changes:

- [ ] Add direct parent selector on the left.
- [ ] Try center layout and/or floating docked toolbar.

If the docked-floated treatment works, we should have to do anything else for the parent selector. If it doesn't, we'd need some visual treatment between the parent and current block types.</summary>

### PR DESCRIPTION
**Pull request by draganescu**
## What?

Closes #40450 

Updates the behavior of the top toolbar fixed setting.

## Why?

Because verical screen estate is scarce and.

## How?
- updates on desktop sized viewports the position of the fixed toolbar
- updates the z-index of the interface header to be lower to that block toolbar shows up on top
- implements a toggle expanded/collapsed for block contextual toolbar

## Testing Instructions

1. Enable the Top Toolbar setting from the top right dot menu
2. Select a block
3. Notice the block tools (toolbar) replaces the document tools (toolbar)
4. This also works by default in the Site editor

### Testing Instructions for Keyboard

1. Select a block
2. Press Shift + Tab, the focus should move to the block toolbar
3. Select a block
5. Press Alt + F10 , the focus should move to the block toolbar
6. Select a block
7. Press Ctrl + Shift + ~ to select 1st navigable region
8. Press Tab, the focus should move to the inserter
9. Use arrow right, the focus should move to document tools buttons
10. Select a block
11. Press Shit + Tab
12. In the block toolbar press the Collapse Block Tools button, the focus should be on Expand Block Tools button
13. Press the Expand Block Tools button, the focus should be on Collapse Block Tools button

## Screenshots or screencast 

https://user-images.githubusercontent.com/107534/230375260-49afcfe0-7148-4bd7-b536-b5c9b8b912d1.mp4

## Known issues

- [x] When the post edtor is not full screen 💥 it's all wrong 
- [x] The Collapse Block Tools button sometimes gets focus when it shouldn't
- [ ] When the block toolbar is focused the tooltip of document tools appears 🤷🏻 
- [ ] Distraction Free does not inherit this, there still are no block tools when DFM is on
- [x] In the Site Editor there is a vertical allignment issue
- [x] In the Site Editor focusing the header region does not hide the block toolbar

### CODE REVIEW

**Comment by richtabor** [comment]
Tightening up some of the design: 

1. Should it say "toolbar" instead of "Block Tools"? May add more context, as the "Top toolbar" option was enabled. We use "Tools" labels elsewhere, but not "Toolbar" (unless referring to the toolbar). "Expand toolbar" / "Collapse toolbar"

2. The gray borders on the "Expand Block Toolbar" and "Collapse Block Toolbar" buttons should not have rounded ends:

CleanShot 2023-04-06 at 10 03 34
CleanShot 2023-04-06 at 10 04 34

3. Toolbar should be better aligned with the Inserter:

CleanShot 2023-04-06 at 10 06 13

4. Parent selector area could be condensed (to use the same spacing as the block toolbar):

CleanShot 2023-04-06 at 10 10 09
CleanShot 2023-04-06 at 10 11 49
CleanShot 2023-04-06 at 10 11 40
230404721-73c9badd-e2fd-453e-b629-b2e6e9493bcb

**Comment by richtabor** [comment]
Perhaps as a follow-up we could try exploring a more graceful expand/collapse with animation. Would make it clearer for visual-based users to understand context of the controls/swapping the toolbars.

**Comment by richtabor** [comment]
One bit I'm not sure about, but would appreciate context, is if you collapse the toolbar, its always collapsed. Is that the expected behavior?

https://user-images.githubusercontent.com/1813435/230407310-d706e4ba-5070-4cb6-ab0a-910266c4dda1.mp4

**Comment by draganescu** [comment]
> One bit I'm not sure about, but would appreciate context, is if you collapse the toolbar, its always collapsed. Is that the expected behavior?

I don't know but I think it's better if the toggle sticks.

**Comment by sabernhardt** [comment]
Please do not move the **fixed** toolbar. Vertical screen estate can be scarce, even on my 1366×643 window, but this option is worth the 49 pixels so I know exactly where the block toolbar is at **all** times. And I would continue to use the document-related buttons without needing to toggle that toolbar open and then open either the block inserter or outline view. I know the keyboard shortcut for Undo, but adding another button to activate before showing the undo and redo buttons (which also have arrow icons) is not helpful for anyone who needs them.

**Comment by draganescu** [comment]
@sabernhardt I totally agree the collapsing is not ideal, but is is in my opinion a good trade off: 

- the buttons that are hidden are:
  - undo/redo which most users access via the universal keyboard shortcuts
  - the list view, which is not as used as undo or redo or the inserter, but it is very important
- yet due to collapsing
  - the inserter is always visible
  - we now have room for parent selector
  - we still hold to header room for other header items, but still allow the block toolbar to grow
  - you have the option to keep the block toolbar collapsed, for when you need to work with the list view more, for instance
  - the dropdowns that open from the toolbar (block switcher, align menus, duotone etc) are closer to the top of the screen, saving even more screen estate and minimizing the annoying overlap which obscurs the destination of the change

It looks like a worth it trade off. 

It's not only about the 49 pixels in height (out of 643, which are even less for the canvas) - but even this number on such screens is pretty big - in your case it's ~50 pixels out of ~420 vertical available, 11% of screen area won back. That is quite significant at low screen resolutions.

But beyond this it's a gain in functionality which, yes, adds a complication, but it makes a setting less broken. The block editors are not desktop applications, and even less document processors. They live inside other chrome and need new models of interaction adjusted to the nature of their primary interface which is the block.

What do you think?

**Comment by jasmussen** [comment]
Took this for a spin. GIF showing how it's covering the content on the right:

test top toolbar

I think this is moving in the right direction, and lets us keep a single unified toolbar as long as possible, while still accommodating the breadth of very very wide block toolbars possible.

This is especially true when the "show text labels" option is enabled:
Screenshot 2023-04-10 at 11 14 10

While that option deserves a ton of love on its own, the fact that it nevertheless somewhat works in this view does suggest it's moving in a decent direction.

It shows an issue though:

Screenshot 2023-04-10 at 11 15 22

See "Options/Options" on the right. It seems like if we are going with this "cover the content" mechanism, we should add a gradient on the right to indicate what's in the front. I think that might be worth it, because then you'd still have access to preview/publish buttons on the wide screens, instead of simply hiding those entirely as was discussed in some of these mockups:

Top Toolbar

Just for reference, another alternative to covering the content on the right, is to compact the block toolbar into a dropdown. This is almost certainly non trivial, but sharing for posterity how Docs does it:

docs

On a design note, the vertical separators are a bit too tall.

Nice work! Coming together well.

**Comment by draganescu** [comment]
The vertical separators being smaller seems more difficult than hiding the toolbar in a dropdown 😂 (not seriously but seriously the way they are done do not allow for much wiggle room in terms of shrinking them - we are using _the same_ toolbar).

The fact that we're positioning the toolbar fixed it cannot be fluid. I can only respond to breakpoints.

**Comment by draganescu** [comment]
@jasmussen @jameskoster although I love this visually, to me all these problems with responsiveness, text labels, hiding and showing so many affordances, point at this having some hidden UX problem that instead of addressing we force this UX to fit :)

**Comment by jasmussen** [comment]
> although I love this visually, to me all these problems with responsiveness, text labels, hiding and showing so many affordances, point at this having some hidden UX problem that instead of addressing we force this UX to fit :)

Can you elaborate? Although maybe not the most elegant, the mockup I shared in that thread above that hides instead of covers at a particular breakpoint seems like it should work, no?

I agree there are numerous ux problems to fix around text labels and responsiveness in general. But I don't think they are unique to the top toolbar option, and are worth fixing separately.

**Comment by draganescu** [comment]
> Can you elaborate?

- there are possible situations where text labels are turned on and even with 100% width block tools we may need to scroll or collapse them
- having an editor open and resizing a window will hide your save, publish, options, buttons - pretty unexpected and easy to miss

Hm, what if, just what if, the top toolbar remains as it is today and we introduce a new affordance similar to this:

https://user-images.githubusercontent.com/107534/230892773-4da614ef-7dc8-4b7a-9d05-98aadabdf780.mp4


https://user-images.githubusercontent.com/107534/230892780-d0b9c407-daf9-4e20-b137-4c8da9ed676c.mp4

So we add a new button to the top toolbar that hides the editor header ?

**Comment by jasmussen** [comment]
> there are possible situations where text labels are turned on and even with 100% width block tools we may need to scroll or collapse them

I don't think we should optimize too much for the text labels option. As noted, it needs separate love, and I'd treat it as a separate project.

I don't think we should throw out the baby with the bathwater in terms of introducing new collapsing affordances, honestly I feel like this PR as is, is pretty close!

File: packages/block-editor/src/components/block-tools/block-contextual-toolbar.js [hunk 1]
```diff
@@ -7,17 +7,68 @@ import classnames from 'classnames';
...
 import NavigableToolbar from '../navigable-toolbar';
 import BlockToolbar from '../block-toolbar';
 import { store as blockEditorStore } from '../../store';
+import BlockIcon from '../block-icon';
+
+const CollapseFixedToolbarButton = forwardRef( ( { onClick }, ref ) => {
+	return (
+		<ToolbarItem
+			as={ Button }
+			className="components-button components-toolbar-button block-editor-block-toolbar__collapse-fixed-toolbar"
```
Comment (ciampo) [inline packages/block-editor/src/components/block-tools/block-contextual-toolbar.js]: The `components-*` classnames are intended to be internal to the `@wordpress/components` package — could we avoid adding them explicitly here?

Comment (draganescu) [reply packages/block-editor/src/components/block-tools/block-contextual-toolbar.js]: But I want it to be like the other toolbar buttons and I am using `as` to be a button component. I don't think I am styling the `CollapseFixedToolbarButton`, but simply reusing styles. If `components-*` classnames result in visual updates so should this button follow.

File: packages/block-editor/src/components/block-tools/style.scss [hunk 2]
```diff
@@ -119,6 +118,94 @@
...
+			.is-fullscreen-mode & {
+				top: $grid-unit - 2;
+				// leave room for block inserter
+				left: $grid-unit-80 + $grid-unit-70;
+				&.is-collapsed {
+					left: $grid-unit-10 * 35;
+				}
+			}
+
+			& > button.components-button.has-icon {
```
Comment (ciampo) [inline packages/block-editor/src/components/block-tools/style.scss]: Similarly, we should try to avoid targeting those `components-*` classes when writing styles. Can we use a custom classname instead (eg. `.block-editor-block-toolbar__button` or similar) ?

File: packages/block-editor/src/components/block-tools/block-contextual-toolbar.js (hunk 1 above)
Comment (ciampo) [reply packages/block-editor/src/components/block-tools/block-contextual-toolbar.js]: > But I want it to be like the other toolbar buttons

Have you considered re-using the same component as the other toolbar buttons, or abstracting a component out of those buttons so that it can be reused here?

> I am using as to be a button component.

Have you considered using the `ToolbarButton` component? You can see in action in [this Storybook example](https://wordpress.github.io/gutenberg/?path=/story/components-toolbar--default) ([source code](https://github.com/WordPress/gutenberg/blob/e948f63cc44a7d85fb581e2ab8765c512fe37f2e/packages/components/src/toolbar/stories/index.tsx))

> If components-* classnames result in visual updates so should this button follow.

`components-*` class names are meant to be a private implementation detail of the `@wordpress/components` package, and as such they shouldn't be used in other parts of Gutenberg. They are not a public API of the package, nor of each single component.

Using them to apply a given look to a different component is conceptually and architecturally wrong, and can lead to style leaks and future UI breakages.

To quote [the wp-calypso CSS guidelines](https://github.com/Automattic/wp-calypso/blob/cccee83b60c87824f1a0de2d77c2ae6f820d2b28/docs/coding-guidelines/css.md?plain=1#L56) , when interacting with a component system we shouldn't reuse classes, but rather reuse components.

File: packages/block-editor/src/components/block-tools/style.scss (hunk 2 above)
Comment (draganescu) [reply packages/block-editor/src/components/block-tools/style.scss]: But this is already the case in other parts of the codebase, this pattern is also used by the inserter button whene compomnent's css has to be altered for a very particula purpose. So you're explaining that we just recreate everything in a custom CSS class whenever we need to tweak a component?

File: packages/block-editor/src/components/block-tools/block-contextual-toolbar.js (hunk 1 above)
Comment (draganescu) [reply packages/block-editor/src/components/block-tools/block-contextual-toolbar.js]: I will look into using the `ToolbarButton` but it's weird that I don't see how using within the codebase for the chrome of the editor itself where we want X to always respond to updates in styling across the base component system, it is bad to reuse classnames. It's the core product using a private API, not using a private API from an extending product :)

Comment (draganescu) [reply packages/block-editor/src/components/block-tools/block-contextual-toolbar.js]: Used `ToolbarButton` with success in [6663a49](https://github.com/WordPress/gutenberg/pull/49634/commits/6663a499f3bf6cc528bdc68f250afaf6dcd1f7e3), thank you!

File: packages/block-editor/src/components/block-tools/style.scss (hunk 2 above)
Comment (draganescu) [reply packages/block-editor/src/components/block-tools/style.scss]: For instance: https://github.com/WordPress/gutenberg/blob/ac871a255805c922f780fb125ab2104b2dbcb664/packages/edit-post/src/components/header/header-toolbar/style.scss#L40

File: packages/block-editor/src/components/block-tools/block-contextual-toolbar.js (hunk 1 above)
Comment (ciampo) [reply packages/block-editor/src/components/block-tools/block-contextual-toolbar.js]: > where we want X to always respond to updates in styling across the base component system, it is bad to reuse classnames

That is because our system is components based, and not classname-based — ie. the public APIs of the package are the React Components.

> It's the core product using a private API, not using a private API from an extending product :)

From the point of view of an external consumer of the `@wordpress/components` package, those classnames should not exist (this applies also to other packages in Gutenberg like block editor).

Re-using such classnames across the editor just to "borrow" styles completely breaks the assumption of having a components system that abstracts semantics and design.

File: packages/block-editor/src/components/block-tools/style.scss (hunk 2 above)
Comment (ciampo) [reply packages/block-editor/src/components/block-tools/style.scss]: > But this is already the case in other parts of the codebase, 
> [...]
> For instance:

That is true, and in fact @mirka and have been already advocating folks against this bad practice for quite some time. The example code that you linked to is also an example of what we should try to avoid.
It may be hard to improve existing code, but we can at least try to avoid adopting these same bad practices as we write more code.

Relying on such classnames (and more in general, similar style overrides) often leads to very brittle UIs that break as soon as there are some updates in `@wordpress/components`.

In fact, since we don't consider classnames and dom structure part of the public API of our components, it is very likely that those will change in the future.

> So you're explaining that we just recreate everything in a custom CSS class whenever we need to tweak a component?

My feedback here, and therefore my expectations, are that we adopt good CSS practices and more in general consume components in such a way that can scale well throughout the app, with good encapsulation and semantics.

For example, if we find ourselves "recreating" and "tweaking" a component, maybe we're either not using the components for their original purpose, or those components are out of date and don't serve the editor's purpose as closely as they should.

For example, if we need something that looks like a button from `@wordpress/components`, we should use the `Button` component, and not the `components-button` classname.

File: packages/block-editor/src/components/block-tools/block-contextual-toolbar.js (hunk 1 above)
Comment (draganescu) [reply packages/block-editor/src/components/block-tools/block-contextual-toolbar.js]: Yea you are perfectly right and I understand what you say. I was a bit hot headed in the beginning of our conversation. ;))

File: packages/block-editor/src/components/block-tools/style.scss (hunk 2 above)
Comment (draganescu) [reply packages/block-editor/src/components/block-tools/style.scss]: Yes. Thank you for the detailed explanations. I should have thought of that. I was just badly inspired by parts of the code base.

I'll see how I can achieve the same thing without using this bad pattern. Thank you. :)

**Comment by draganescu** [comment]
@ciampo I solved the cases when I _introduced_ the use of `components-*` classes in the wrong places. But trying to make the border smaller for the desktop and fixed toolbar I had to override how the block toolbar in block editor handles `components-*` classes in the wrong places. Instead of fixing this here, may I come back and use custom classes in the block toolbar in one specific PR?

**Comment by draganescu** [comment]
@jasmussen with the exception of mobile which I'd do later, I have added the behavior for tablet and desktop (to cover and not to cover the publish tools while expanded, and never to cover while contracted). There still is a way in the site editor to overlap the document thing in the middle. Maybe that too should only show in large viewports?

Either way when show icon labels is toggled the toolbar is now horrible dimensioned, not sure what's up with that.

**Comment by jasmussen** [comment]
Wow, with these last few updates, things are really coming together. A quick GIF showing selecting and unselecting a paragraph, as well as using the block tools selector and back. 

status

A few details. This state you should only ever see if you click the "Collapse block tools" button — it should not be seen as a permanent toggle. I.e. if you deselect a block and select it again, you should see the full range of block tools. Here's a GIF showing the collapsed state persisting:

selecting and deselecting

Deselecting here should "reset" the state.

For the tooltips:

Screenshot 2023-04-12 at 10 12 04
Screenshot 2023-04-12 at 10 12 10

We should use sentence case here, so "Collapse block tools" and "Expand block tools".

I realize this is really tricky to get right, and the shorter separators look really beautiful, thank you! We migh also be able to refine the following as a followup PR if that makes things simpler, but the spacing between items looks slightly off. Too little spacing left of the separator before the paragraph icon:

Screenshot 2023-04-12 at 10 11 42

Too little space between the "Up arrow" and the separator:

Screenshot 2023-04-12 at 10 11 56

I think if we can just improve the spacing in those cases, this is good to land. Some of those block toolbar metrics likely require larger refactors, including tackling some of the work outlined in #46734. For reference, here are the metrics:

Top toolbar metric sheet

Nice work!

**Comment by jameskoster** [comment]
> "Collapse block tools" and "Expand block tools".

Does this sound a little ambiguous? 🤔 A potentially simpler alternative could be:

"Show document tools", "Show block tools".

**Comment by jasmussen** [comment]
With the most recent change, the block toolbar shows again after you deselect and select:

top toolbar

This feels completely intuitive to me, and feels great, as it is the same behavior as when the toolbar is close to the block. I dig it!

**Comment by draganescu** [comment]
Ok this is ready for code review. It has at least one known code related issue - the one @ciampo noticed where I target `components-*` classes, but I will have to iterate in a future PR to change how the block toolbar component from the block editor packages  targets `components-*` classes instead of just having their own classnames.

Other than that there is a failing test which is correct. The problem the test has is that now in fixed mode on desktop thre is an extra button which gets the focus, which is outside the block toolbar. This is correct. Not sure if I should fix the test to only look at non fixed toolbar and write a new one for fixed toolbar or .. if thre is another way,

Finally, there is a lot, I mean a lot, of CSS tweaking with some magic numbers. Because this PR works with an absolutely positioned element trying to cover things under it, it always comes to nudging stuff. I don't think I can fix everything with our SASS vars for now.

Note: to obtain the nice short separators I had to remove the boders and use pseudo elements. Borders cannot be shorter than the box and the boxes of toolbar elements have all kinds of height, padding and margin constraints. It's not very elegant but it works.

File: packages/edit-site/src/components/layout/index.js [hunk 3]
```diff
@@ -23,6 +23,7 @@ import { useState, useRef } from '@wordpress/element';
 import { NavigableRegion } from '@wordpress/interface';
 import { store as keyboardShortcutsStore } from '@wordpress/keyboard-shortcuts';
 import { CommandMenu } from '@wordpress/commands';
+import { store as prefferencesStore } from '@wordpress/preferences';
```
Comment (jeryj) [inline packages/edit-site/src/components/layout/index.js]: Typo: `prefferences` -> `preferences`

File: packages/block-editor/src/components/block-tools/block-contextual-toolbar.js [hunk 4]
```diff
@@ -7,19 +7,74 @@ import classnames from 'classnames';
...
  */
 import NavigableToolbar from '../navigable-toolbar';
 import BlockToolbar from '../block-toolbar';
 import { store as blockEditorStore } from '../../store';
+import BlockIcon from '../block-icon';
+
+const CollapseFixedToolbarButton = forwardRef( ( { onClick }, ref ) => {
+	return (
+		<ToolbarItem
+			as={ ToolbarButton }
```
Comment (ciampo) [inline packages/block-editor/src/components/block-tools/block-contextual-toolbar.js:32]: Out of curiosity, have you tried using `ToolbarButton` directly (instead of using the `as` prop) ?

```suggestion
		<ToolbarButton
```

This suggestion would apply for the other instances of `ToolbarItem` in this file too

**Review by ciampo — COMMENTED** [review]
> I had to override how the block toolbar in block editor handles components-* classes in the wrong places.

Thank you! The behavior that you describe is unfortunately the consequence of having lots of hacky style overrides (not a fault of this PR). 

> Instead of fixing this here, may I come back and use custom classes in the block toolbar in one specific PR?

A follow-up PR to clean those classes up sounds good, thank you!

**Comment by scruffian** [comment]
This isn't working for me in the Post Editor: 

Screenshot 2023-04-18 at 11 44 54

File: packages/block-editor/src/components/block-tools/style.scss [hunk 5]
```diff
@@ -119,6 +118,169 @@
...
+		}
+	}
+
+	// on desktop viewports the toolbar is fixed
+	// on top of interface header and leaves room
+	// for the block inserter the publish button
+	@include break-large() {
+		&.is-fixed {
+			// leave room for block inserter and the dashboard navigation
+			left: $grid-unit-80 + $grid-unit-40 + ( $grid-unit-80 * 2 );
```
Comment (scruffian) [inline packages/block-editor/src/components/block-tools/style.scss]: I had to add an extra 160 grid units to account for the dashboard navigation on larger viewports. @draganescu does this seem reasonable?

File: packages/edit-post/src/components/layout/style.scss [hunk 6]
```diff
@@ -99,3 +99,15 @@
...
 	height: $header-height + $border-width;
 }
+
+.edit-post-layout.has-fixed-toolbar {
+	// making the header be lower than the content
+	// so the fixed toolbar can be positioned on top of it
+	// but only on desktop
+	@include break-medium() {
+		.interface-interface-skeleton__header:not(:focus-within) {
+			z-index: 19;
```
Comment (scruffian) [inline packages/edit-post/src/components/layout/style.scss:109]: Does it make sense to use variables for these z-index values so that we can see how they relate to each other?

**Review by scruffian — APPROVED** [review]
Code looks good to me.

File: packages/block-editor/src/components/block-tools/style.scss (hunk 5 above)
Comment (draganescu) [reply packages/block-editor/src/components/block-tools/style.scss]: Ha yet more CSS fiddling. I think I never opened the sidebar when not in full screen 😱

File: packages/block-editor/src/components/block-tools/block-contextual-toolbar.js (hunk 4 above)
Comment (draganescu) [reply packages/block-editor/src/components/block-tools/block-contextual-toolbar.js:32]: Of course not, I am a robot doing things as instructed 😂 that was `as Button`, suggested use `ToolbarButton` so I did. 🤦🏻

File: packages/block-editor/src/components/block-tools/style.scss (hunk 5 above)
Comment (draganescu) [reply packages/block-editor/src/components/block-tools/style.scss]: It's not OK because it now breaks when the sidebar is collapsed. I hope there is a body class for that!

File: packages/edit-post/src/components/layout/style.scss (hunk 6 above)
Comment (draganescu) [reply packages/edit-post/src/components/layout/style.scss:109]: Maybe ... but how would the variable name explain it better than the comment? It's a weird situation.

Comment (MaggieCabrera) [reply packages/edit-post/src/components/layout/style.scss:109]: We have a file for this. I believe when I was looking for the z-index values the line I looked for was [this one](https://github.com/WordPress/gutenberg/blob/trunk/packages/base-styles/_z-index.scss#L32). It would make sense to store them in context.

Comment (draganescu) [reply packages/edit-post/src/components/layout/style.scss:109]: How? Swap the values?

Comment (MaggieCabrera) [reply packages/edit-post/src/components/layout/style.scss:109]: Like this:

`z-index: z-index(".interface-interface-skeleton__header:not(:focus-within)");`

And add the relevant comments to the z-index file, having the new selector next to the ones that are relevant to it.

File: packages/block-editor/src/components/block-tools/style.scss [hunk 7]
```diff
@@ -119,6 +118,226 @@
...
+				// Add a border as separator in the block toolbar.
+				&::after {
+					content: "";
+					width: $border-width;
+					height: 24px;
+					margin-top: $grid-unit + $grid-unit-05;
+					margin-bottom: $grid-unit + $grid-unit-05;
+					background-color: $gray-300;
+					position: absolute;
+					left: 44px;
```
Comment (MaggieCabrera) [inline packages/block-editor/src/components/block-tools/style.scss:164]: This is probably the sketchiest value of them all, maybe it needs a comment? Is it icon width + icon padding?

**Review by MaggieCabrera — APPROVED** [review]
I think you did a great job with the CSS here

File: packages/edit-post/src/components/layout/style.scss (hunk 6 above)
Comment (draganescu) [reply packages/edit-post/src/components/layout/style.scss:109]: Ok I'll do that. Tho to me it only seems I add more hoops to jump through for the future developer reading this hack :)

**Comment by mtias** [comment]
Thanks for all the work here! Let's see how it fares :)

**Comment by aristath** [comment]
I'm late to the party since this has already been merged, but after testing this new implementation, I ran into some usability issues and it looks like a significant regression. The most noticeable and easy to test regression is when trying to undo multiple changes.
To test this: Add multiple paragraph blocks on a page, then start editing the page like a normal user would: Add a bold word here, some italics there, change the styling of a block and so on. Then, just try to undo 4-5 of the changes you made, and you'll immediately notice the issue; You undo one change, then the toolbar changes to the block toolbar. You need to think and start looking "where did the undo button go"? Then after some searching and trial-and-error, see that you need to go one level up to access the top toolbar, then undo the next change and repeat the process. It's impossible to just undo multiple changes at once.
The context of the toolbar keeps shifting, and it makes day-to-day tasks more difficult to the point of frustration... 

Would it be possible to _append_ the block toolbar instead of replacing the top-level one? 🤔 This constant back-and-forth is not a good experience

a11y-wise, I only did a quick 5-minute test, I didn't have the time to do a full review, but it was apparent that this completely broke keyboard navigation, it's not at all easy to do simple tasks 😞

**Comment by draganescu** [comment]
@aristath the undo problem that you found is a bug: undoing should not expand the collapsed block toolbar. I'll see why that is.

> Would it be possible to append the block toolbar instead of replacing the top-level one?

There are screen estate constraints that prevent this.

> a11y-wise, I only did a quick 5-minute test

My main concern with this chance was to not break any a11y expectation and this weird implementation which absolutely positions the block toolbar is the only one that managed to keep a11y expectations intact.

The bug that you found is not an a11y bug, it's an UX bug, a poor experience. It's also surprising, not sure what resets the state of the block toolbar.

**Comment by ciampo** [comment]
Thank you @draganescu for working on this PR and addressing the feedback, it's greatly appreciated!

>  I will have to iterate in a future PR to change how the block toolbar component from the block editor packages targets components-* classes instead of just having their own classnames.

Happy to help reviewing that PR once it's ready :)

**Comment by annezazu** [comment]
>To test this: Add multiple paragraph blocks on a page, then start editing the page like a normal user would: Add a bold word here, some italics there, change the styling of a block and so on. Then, just try to undo 4-5 of the changes you made, and you'll immediately notice the issue; You undo one change, then the toolbar changes to the block toolbar. You need to think and start looking "where did the undo button go"? Then after some searching and trial-and-error, see that you need to go one level up to access the top toolbar, then undo the next change and repeat the process. It's impossible to just undo multiple changes at once.

Is there any issue open for this? Curious what's being done to follow up here and close the loop. This does seem like a bug. Happy to report an issue if no one else does. @aristath @draganescu

**Comment by afercia** [comment]
> There are screen estate constraints that prevent this.

There are other options that can be evaluated to work with the space constraints.

On a general note, the accessibility team has always been reporting that an UI that continuously changes making controls continuously appear and disappear is a problem. Nonetheless, this change goes in that direction. While I do understand the good intent, in my experience this kind of 'smart' UIs may seem good at first, but they rarely work for users. I doube this new implementation is any better than what we have now.

A11y-wise there are more issues with this implementation at the point that I wouldn't know where to start. Some quick testing with the keyboard surfaces only some of the most evident ones. I'd encourage everyone to test this new UI with the keyboard first to get an idea of the main issues so that we can continue the conversation with some more context.

On top of keyboard navigation, there are other issues related to the `NavigableToolbar` ARIA toolbar usage, placement of elements in the DOM, usage of the icons, etc.
