### PR TITLE
Capture state changes scheduled between render and effect

### LINKED ISSUE #32154: Wrong insertion point after selecting blog's title
## Description

Selecting a block after having selected the blog's title, the insertion point (`Add block here` line) is displayed in the wrong position. It should be shown after the selected block but it's displayed between the title and the first block.

**NOTE:** If the selected block is text type (for example a Paragraph block), after editing the text, the insertion point is displayed in the proper location (after the block). Looks like there's an issue related to updating the insertion point after the blog's title gets unselected 👀 .

## Step-by-step reproduction instructions

1. Add some blocks
2. Select blog's title
3. Tap on the ➕ button
4. Observe that the insertion point is displayed between the title and the first block
5. Tap on any block
6. Tap on the ➕ button
7. Observe that the insertion point is displayed in the same location (between the title and the first block)

## Expected behaviour
The insertion point should be displayed after the selected item.

## Actual behaviour
The insertion point remains displayed between the title and the first block when a block is selected after having the blog's title selected.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/4885740/119321027-7df35e00-bc7c-11eb-801b-fcde42c94dcc.mov

_Shared by @geriux in this [PR](https://github.com/WordPress/gutenberg/pull/32110), thanks!_

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: iPhone 12 Pro (simulator)
- Operating system: 14.4
- WordPress app version: 17.3

### PR DESCRIPTION
**Pull request by dcalhoun**
## What?
Fixes #32154. Supersedes #32831.  Avoid stale mappings overwriting new state in specific contexts where `onStoreChange` updates the state before the effect writes the initial mapping.

## Why?
In the event that a child component dispatched an action modifying the store before the selector mapping was written, the changes in the store were lost due to `useSelect`'s `useIsomorphicLayoutEffect` referencing a stale value.

A specific example of this issue occurring is the following code where `onUnselect` is called. This call triggers an update to the store the occurs in between `useSelect`'s reading and writing the selector value, resulting in a stale `isTitleSelected` value. This resulted in the blocks inserted to the incorrect location, which is captured in https://github.com/WordPress/gutenberg/issues/32154. 

https://github.com/WordPress/gutenberg/blob/3987f612a77fd346093de1a1239aea11a6dc8e38/packages/editor/src/components/post-title/index.native.js#L36-L48

https://github.com/WordPress/gutenberg/blob/3987f612a77fd346093de1a1239aea11a6dc8e38/packages/editor/src/components/provider/use-block-editor-settings.native.js#L31

## How?
Avoid setting a reference to the selector output mapping until after the selector is run. 

## Testing Instructions
The following was manually tested: 

1. Launch the native Demo editor.
2. Focus the first block. 
3. Tap the + button to add a block.
4. **Expected:** The "ADD BLOCK HERE" insertion point is displayed beneath the selected block.
5. Focus the title for the post.
6. Tap the + button to add a block.
7. **Expected:** The "ADD BLOCK HERE" insertion point is displayed beneath the title. 
2. Focus the first block.
3. Tap the + button to add a block.
4. **Expected:** The "ADD BLOCK HERE" insertion point is displayed beneath the selected block.

## Screenshots or screencast 

<details><summary>Before</summary>

https://user-images.githubusercontent.com/438664/190246371-85c9d7bf-500a-4409-9b1b-597ac7d8eeb1.mov

</details>

<details><summary>After</summary>

https://user-images.githubusercontent.com/438664/190246407-e31b51d0-740a-4962-9d00-51882a4fb914.mov

</details>

### CODE REVIEW

**Comment by dcalhoun** [comment]
Hey @nerrad and @youknowriad. 👋🏻 This change touches fairly low-level logic. From what I found, you both have discussed the existing code a good bit. I would appreciate your perspective on these changes. It is not a rush, so please review at your convenience. Thank you! 🙇🏻

**Comment by jsnajdr** [comment]
Hi @dcalhoun :wave: seems you're really up to something 🙂 The `useSelect` code does something like
```js
// read the current value
const mapOutput = latestMapOutput.current;

// indiscriminately write the read value back into the ref in an effect
useIsomorphicLayoutEffect( () => {
  latestMapOutput.current = mapOutput;
} );

// write to the ref also in subscription callback
subscribe( function onStoreChange() {
  latestMapOutput.current = newValue;
} );
```
Your test example works in such a way that the `onStoreChange` callback is called between the reading and the effect writing. We read an old value (0), then `onStoreChange` changes the value from 0 to 1 and finally the effect changes it back from 1 to 0 (!!).

> action modifying the store before the `useSelect` subscription is set,

At the moment when the action is being dispatched the `useSelect` subscription is already set: the `onStoreChange` callback gets called. But the timing of the update is such that the value is overwritten with a stale one.

**Comment by jsnajdr** [comment]
I remembered that the `react-redux`'s `useSelector` hook uses the same approach: writing `latestSelectedState.current` in an effect on each call, no matter if the selector was run or not. Then it should have the same bug. Does it?

I rewrote the unit test that this PR is adding to Redux and observed that a stale value is really written: `useSelector` reads old value from ref, schedules an effect, executes a listener, writes a new value to the ref, and then the effect writes the stale value. But there is one crucial difference. `useSelector` stores not only the selected state in a ref, but also the "source" Redux state. And a `useSelector` calls whether that stored source state is equal to the current one, and if it isn't, it will call the selector. So, the order of events is:
1. Read old value and old state
2. Schedule a write in effect
3. Return old value from the hook
4. Listener gets called, writes new value and new state
5. Effect writes old value and old state (bad!)
6. The next call to `useSelector` reads old value and old state
7. Finds out that current state != old (stored) state
8. Calls the selector, which returns new value
9. Schedules a write in effect, which is going to write new value and new state
10. Return new value

So, the stale value is written, but it will never be used. On the other hand, `@wordpress/data` `useSelect` doesn't have a source state to compare. It will not and can not do the comparison in step 7 and call the selector. It will trust the stored value, which is wrong.

File: packages/data/src/components/use-select/index.js [hunk 1]
```diff
@@ -191,10 +191,17 @@ export default function useSelect( mapSelect, deps ) {
...
 	} );
 
+	useIsomorphicLayoutEffect( () => {
+		if ( ! hasMappingFunction ) {
+			return;
+		}
+
+		latestMapOutput.current = mapOutput;
+	}, [ mapOutput ] );
+
```
Comment (jsnajdr) [inline packages/data/src/components/use-select/index.js]: A little more elegant fix would be to keep the `latestMapOutput.current` write in the original hook, but do it only if the selector was already called:
```js
let selectorRan = false;
if ( conditions ) {
  mapOutput = wrapSelect( mapSelect );
  selectorRan = true;
}

useIsomorphicLayoutEffect( () => {
  if ( selectorRan ) {
    latestMapOutput.current = mapOutput;
  }
  // ... other writes in this hook stay intact
} );
```
I tried it locally and all `useSelect` unit tests are passing. Let's see how the entire Gutenberg unit and e2e suite will do.

Also, we should the same changes in `useSuspenseSelect`. Its implementation is similar but slightly different, and we didn't unify them together yet.

File: packages/data/src/components/use-select/test/index.js [hunk 2]
```diff
@@ -434,6 +434,67 @@ describe( 'useSelect', () => {
 			);
 		} );
 
+		it( 'captures state changes before the subscription is set', () => {
+			registry.registerStore( 'store-1', counterStore );
+			registry.registerStore( 'store-2', counterStore );
+			registry.registerStore( 'store-3', counterStore );
```
Comment (jsnajdr) [inline packages/data/src/components/use-select/test/index.js]: You only need to register `store-1` here.

File: packages/data/src/components/use-select/test/index.js [hunk 3]
```diff
@@ -434,6 +434,67 @@ describe( 'useSelect', () => {
...
+			}
+
+			const TestComponent = jest.fn( () => {
+				[ childShouldDispatch, setChildShouldDispatch ] =
+					useState( false );
+				const state = useSelect(
+					( select ) =>
+						selectCount1AndDep() || {
+							count1: select( 'store-1' ).getCounter(),
+						},
```
Comment (jsnajdr) [inline packages/data/src/components/use-select/test/index.js]: The calls to the `mapSelect` function can be tracked more elegantly with:
```js
const selectCount1AndDep = jest.fn( ( select ) => ( {
  count1: select( 'store-1' ).getCounter(),
} ) );

/* ... */

const state = useSelect( selectCount1AndDep, [] );
```

File: packages/data/src/components/use-select/test/index.js [hunk 4]
```diff
@@ -434,6 +434,67 @@ describe( 'useSelect', () => {
...
+						registry.dispatch( 'store-1' ).increment();
+					}
+				}
+
+				render() {
+					return null;
+				}
+			}
+
+			const TestComponent = jest.fn( () => {
```
Comment (jsnajdr) [inline packages/data/src/components/use-select/test/index.js]: We never look at how many times `TestComponent` was called or what its arguments were, so wrapping it with `jest.fn()` is not needed.

File: packages/data/src/components/use-select/test/index.js [hunk 5]
```diff
@@ -434,6 +434,67 @@ describe( 'useSelect', () => {
...
+				[ childShouldDispatch, setChildShouldDispatch ] =
```
Comment (jsnajdr) [inline packages/data/src/components/use-select/test/index.js]: Instead of storing a reference to `setChildShouldDispatch` and then calling it, we could achieve the same by rendering a button and triggering an event:
```js
<button onClick={ () => setChildShouldDispatch( true ) }>trigger</button>

fireEvent.click( rendered.getbyText( 'trigger' ) );
```
That's more in the spirit of React unit tests, working only with the DOM UI that any other user can also use, without accessing internals.

**Comment by dcalhoun** [comment]
Thank you for the thorough review and investigation, @jsnajdr. 🙇🏻 

> Your test example works in such a way that the `onStoreChange` callback is called between the reading and the effect writing. We read an old value (0), then `onStoreChange` changes the value from 0 to 1 and finally the effect changes it back from 1 to 0 (!!).
> 
> > action modifying the store before the `useSelect` subscription is set,
> 
> At the moment when the action is being dispatched the `useSelect` subscription is already set: the `onStoreChange` callback gets called. But the timing of the update is such that the value is overwritten with a stale one.

This makes sense now that you explain it so clearly. 

> So, [in `react-redux`] the stale value is written, but it will never be used. On the other hand, `@wordpress/data` `useSelect` doesn't have a source state to compare. It will not and can not do the comparison in step 7 and call the selector. It will trust the stored value, which is wrong.

This is very interesting, and very educational for me in regards to how `@wordpress/data` operates.

File: packages/data/src/components/use-select/test/index.js [hunk 6]
```diff
@@ -434,6 +434,63 @@ describe( 'useSelect', () => {
 			);
 		} );
 
+		it( 'captures state changes before the subscription is set', () => {
```
Comment (dcalhoun) [inline packages/data/src/components/use-select/test/index.js]: @jsnajdr I am struggling to identify a concise way to describe this test based upon your findings. What do you think is an appropriate description for this test?

Comment (jsnajdr) [reply packages/data/src/components/use-select/test/index.js]: I would say something like "captures state changes scheduled between render and effect." The key part of `useSelect` here is that it reads a ref in render and writes it in effect:
```js
function useSelect() {
  const value = ref.current;
  useEffect( () => {
    ref.current = value;
  } );
}
```
And then there is some `Inner` component that writes the ref in effect, too:
```js
function Inner() {
  useEffect( () => {
    ref.current = newValue;
  } );
  return null;
}
```
Now when you combine them together:
```js
function Outer() {
  useSelect();
  return <Inner />;
}
```
the effects are executed in children first and in parents second, so the order of operations is:
1. outer render reads
2. inner effect writes new value
3. outer effect writes stale value

In reality the `useSelect` effects are layout effects and the `Inner` component uses `componentDidUpdate`, but it leads to the same scheduling.

File: packages/data/src/components/use-select/index.js [hunk 7]
```diff
@@ -188,20 +190,16 @@ export default function useSelect( mapSelect, deps ) {
 			return;
 		}
 
+		if ( selectorRan ) {
+			latestMapOutput.current = mapOutput;
+		}
```
Comment (jsnajdr) [inline packages/data/src/components/use-select/index.js]: It's probably just for aesthetics sake, but I'd rather keep the assignments to `latestMapOutput` and `latestMapOutputError` close to each other.

**Review by jsnajdr — APPROVED** [review]
Looks good :+1:
