### PR TITLE
ToggleGroupControl: Fix focus and selected style to support Windows High Contrast mode

### LINKED ISSUE #50782: ToggleGroupControl: No focus style and selected style in Windows high contrast mode
### Description

Discovered while reviewing #50772

The ToggleGroupControl component has the following two problems in Windows high contrast mode:

- Cannot see that the control group is in focus
- It is impossible to know which one is selected

### Step-by-step reproduction instructions

- Enable Windows High Contrast mode.
- Access [the Storybook](https://wordpress.github.io/gutenberg/?path=/story/components-experimental-togglegroupcontrol--default).
- Perform mouse and keyboard operations on the component.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/1462135e-ceb1-44e1-b832-a91d0cd4c484

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes: #50782
Similar to #50772
## What?
This PR displays the focus outline and selected outline in ToggleGroupControl when Windows is in high contrast mode.

## Why?
Windows high contrast mode does not show box-shadow when focused. In addition, which button is selected or not is not visible in high contrast mode because it is represented only by the background color.

## How?
I have added a transparent outline as a focus style. I added a similar transparent outline for which button is selected or not, because the background color is not available.

## Screenshots or screencast

https://github.com/WordPress/gutenberg/assets/54422211/662483cf-1dbd-4081-b6c3-82c4344f34dc

### CODE REVIEW

File: packages/components/src/toggle-group-control/toggle-group-control/styles.ts [hunk 1]
```diff
@@ -80,6 +82,9 @@ export const BackdropView = styled.div`
 	transition: transform ${ CONFIG.transitionDurationFast } ease;
 	${ reduceMotion( 'transition' ) }
 	z-index: 1;
+	// Windows High Contrast mode will show this outline, but not the box-shadow.
+	outline: 2px solid transparent;
+	outline-offset: -3px;
```
Comment (t-hamano) [inline packages/components/src/toggle-group-control/toggle-group-control/styles.ts:87]: At `-2px`, the space between outlines seemed too narrow:

offset-2-component

offset-2-block-editor

**Comment by joedolson** [comment]
This looks great - thanks @t-hamano! The -3px offset seems good to me.

**Review by afercia — APPROVED** [review]
LGTM! ❤️

**Review by mirka — APPROVED** [review]
Thank you!
