### PR TITLE
Fix 13776: Format is already registered to handle class name

### LINKED ISSUE #13776: Format is already registered to handle class name error log
**Describe the bug**
Custom formats are logging this error : https://github.com/WordPress/gutenberg/blob/01be7ac89b97b76c490d57a15c16466657240770/packages/rich-text/src/register-format-type.js#L95 even when classNames were defined.

**To Reproduce**
1. Install https://wordpress.org/plugins/coblocks/
2. Load editor with 5.0
3. Uppercase and code formats are working perfectly but those errors were logging

**Expected behavior**
No error logs

**Screenshots**
screen shot 2019-02-08 at 12 57 06 pm

### PR DESCRIPTION
**Pull request by gziolo**
## Description
Fixes #13776.

Custom formats are logging this error: https://github.com/WordPress/gutenberg/blob/01be7ac89b97b76c490d57a15c16466657240770/packages/rich-text/src/register-format-type.js#L95 even when classNames were defined.

**To Reproduce**

1. Format type with a class name A and tag name B gets registered.
1. Another format type without any class name but the same tag name B gets registered.

Example format type to test with:

```js
const { registerFormatType } = window.wp.richText;
const { RichTextToolbarButton } = window.wp.editor;

registerFormatType( 'wk/no-icon', {
	edit( { isActive } ) {
		return (
			<RichTextToolbarButton
				icon={ 'editor-link' }
				title={ 'Link ohne Icon' }
				isActive={ isActive }
				/>
		);
	},
  	tagName: 'a',
  	className: 'without-icon',
  	title: 'Link ohne Icon'
} );
```

Props to @pascalknecht for sharing.

**Expected behavior**
No error logs and all format types are properly registered. In the example provided core link should be there.

**Screenshots**
screen shot 2019-02-08 at 12 57 06 pm

### CODE REVIEW

**Comment by technote-space** [comment]
This PR will also fix #13687

File: packages/rich-text/src/store/test/selectors.js [hunk 1]
```diff
@@ -6,33 +6,69 @@ import deepFreeze from 'deep-freeze';
...
+		className: 'class-name',
+		tagName: 'strong',
+	};
 	const defaultState = deepFreeze( {
 		formatTypes: {
-			'core/test-format': { name: 'core/test-format' },
-			'core/test-format-2': { name: 'core/test-format-2' },
+			'core/test-format': formatType,
+			'core/test-format-bare-tag': formatTypeBareTag,
+			'core/test-format-class-name': formatTypeClassName,
```
Comment (ellatrix) [inline packages/rich-text/src/store/test/selectors.js]: Wouldn't this pass in `master` as well, in this order?

**Comment by ellatrix** [comment]
Do you think this is something that should still be part of WordPress 5.2?

File: packages/rich-text/src/store/test/selectors.js (hunk 1 above)
Comment (ellatrix) [reply packages/rich-text/src/store/test/selectors.js]: It looks like it does pass there as well.

Comment (ellatrix) [reply packages/rich-text/src/store/test/selectors.js]: Fixed in 0f9e0f9.

**Review by ellatrix — APPROVED** [review]

**Comment by gziolo** [comment]
Thanks @ellatrix, Good catch 👍

**Comment by gziolo** [comment]
> Do you think this is something that should still be part of WordPress 5.2?

Yes, it seems like a major inconvenience for plugin developers.

**Comment by pbiron** [comment]
> > Do you think this is something that should still be part of WordPress 5.2?
> 
> Yes, it seems like a major inconvenience for plugin developers.

Looks like this did not make it into 5.2.  I'm using 5.2-RC1-45273 and I still get the error.

**Comment by aduth** [comment]
> Looks like this did not make it into 5.2. I'm using 5.2-RC1-45273 and I still get the error.

That's correct. It did not make it for 5.2 . I would assume it could be included in a subsequent minor release (5.2.x), which if I recall correctly from a previous #core dev chat should follow not-long-after the upcoming major release.

**Comment by mahnunchik** [comment]
Any news? I've the same error with `a` tag.

**Comment by mattmilburn** [comment]
@mahnunchik I fixed this issue by providing a non-null `className` in the format settings. I had it set to `null` at first but using a string value for `className` got rid of that error. I'm curious if that would help resolve it for you.

**Comment by mahnunchik** [comment]
@mattmilburn Thank you! Wordpress 5.3 and not null `className` helps me.
