### PR TITLE
Fix overlay issue when empty featured image is used in Cover Block

### LINKED ISSUE #57887: Cover Block: Overlay doesn't show when empty featured image is used
## Description

When selecting to use the featured image in a cover block and choosing an overlay, the overlay doesn't show unless the featured image is defined. This seems to only happen in the editor, not the frontend.

In this example, you can see that the overlay is selected in the sidebar, but it doesn't show in the block.

image

### PR DESCRIPTION
**Pull request by akasunil**
## What?

Fixes https://github.com/WordPress/gutenberg/issues/57887

## Why?

Overlay doesn't show when empty featured image is used in cover block.
  
## Testing Instructions

1. Add cover block
2. Select featured image option as cover background, Keeping featured image blank.
3. Notice overlay
 
## Screenshots or screencast 
CleanShot 2024-03-14 at 11 00 46@2x

### CODE REVIEW

**Comment by akasunil** [comment]
@draganescu need you to review this PR.

File: packages/block-library/src/cover/edit/index.js [hunk 1]
```diff
@@ -500,7 +500,9 @@ function CoverEdit( {
 				data-url={ url }
 			>
 				{ resizeListener }
-				{ ( ! useFeaturedImage || url ) && (
+				{ ( ( ! url && useFeaturedImage ) ||
+					! useFeaturedImage ||
+					url ) && (
```
Comment (aaronrobertshaw) [inline packages/block-library/src/cover/edit/index.js]: Nit: This condition isn't the easiest to read. Perhaps we could refactor this a little and move it out of the JSX?

For example:

`const showOverlay = url || ! useFeaturedImage || ( useFeaturedImage && ! url );`

Then use that variable here. What do you think?

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for putting this PR together @sunil25393 👍 

It's testing nicely for me.

✅ Could replicate original issue
✅ This PR displays the overlay in the editor

| Before | After |
|---|---|
| Screenshot 2024-03-14 at 4 18 05 PM | Screenshot 2024-03-14 at 4 20 26 PM |


It looks like the overlay was deliberately omitted previously in this scenario in favour of the placeholder for the featured image. 

Perhaps it is worth getting some quick design feedback as if we are looking for parity here between the editor and the frontend, having both the overlay and the background color for the placeholder results in a different color in the editor when the overlay is semi-transparent.

cc @jasmussen given your past work around image placeholders do you have any thoughts?

I don't think that small discrepancy is a blocker. This PR is a step in the right direction.

I've left one small suggestion as an inline comment but this PR looks almost ready to me.

**Comment by jasmussen** [comment]
Thank you for the PR 🙏 

This tentatively looks good to me. Before:

Screenshot 2024-03-14 at 08 53 06

After:

Screenshot 2024-03-14 at 08 54 43

I believe some of the challenges were around border and radius, that appears to still work as intended:

Screenshot 2024-03-14 at 08 55 11

— even if there's still a bug around how Chromium renders backdrop-filter/blur causing the edges to blur inwards. That's separate.

The following is entirely separate, but in testing this I'm noticing that the color tint from duotone, which used to affect the Featured Image block is no longer working either there or on the site logo. I wonder when that regressed.

It still works on the Image block, but that is now smaller than it used to:

Screenshot 2024-03-14 at 08 57 13

I'll investigate. But tentative 👍 👍 on this one, and thanks again.

File: packages/block-library/src/cover/edit/index.js (hunk 1 above)
Comment (akasunil) [reply packages/block-library/src/cover/edit/index.js]: ill update this. Thanks for feedback.

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for taking a look at this one @jasmussen 👍 

I've given it another smoke test after the latest tweaks and it still tests well for me. 

I'm happy to approve this one. The noted issues or regressions (unrelated) can be iterated on in follow-ups.

**Comment by draganescu** [comment]
I don't remember having a specific requirement to _not_ allow overlay over featured image, it's just how it was implemented at the time. I think the addition is good and makes the experience of using the cover block more consistent.
