### PR TITLE
Document Settings: Lazy load post authors' data

### LINKED ISSUE #27103: The author list for PostAuthor should be loaded on demand
**Describe the bug**

When loading the post editing screen, the `<PostAuthor/>` component triggers a REST API request (via `getAuthors()`) to fetch the authors to list to populate its filterable list. If the user isn't planning on changing the post author, this is an unnecessary REST API request and a waste of resources.

This request should be performed on-demand, for example when the field gains focus.

**To reproduce**

1. Go to the post editing screen on a site with several users
2. Observe that a request to `wp-json/wp/v2/users` is performed
3. Don't change the post author
4. Wonder why that request was needed

**Editor version (please complete the following information):**
- WordPress version: 5.6 beta

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes #27103.

PR updates `post-author` components to lazy load selection data. This became possible after recent refactoring in #61362.

## Why?
This should improve the initial editor loading time for sites with a large number of users.

## Testing Instructions
1. Open a post.
2. Confirm that no request is made for the `wp-json/wp/v2/users` endpoint.
3. Open the post author's popover.
4. Confirm that the authors are fetched and displayed in the popover.

### Testing Instructions for Keyboard
Same.

## Screenshots or screencast 

https://github.com/user-attachments/assets/03279058-5fa0-4317-9631-b57bc6e185bd

### CODE REVIEW

File: packages/editor/src/components/post-author/check.js [hunk 1]
```diff
@@ -21,20 +19,17 @@ import { AUTHORS_QUERY } from './constants';
...
+	const { hasAssignAuthorAction } = useSelect( ( select ) => {
 		const post = select( editorStore ).getCurrentPost();
 		const canAssignAuthor = post?._links?.[ 'wp:action-assign-author' ]
 			? true
 			: false;
 		return {
 			hasAssignAuthorAction: canAssignAuthor,
-			hasAuthors: canAssignAuthor
-				? select( coreStore ).getUsers( AUTHORS_QUERY )?.length >= 1
-				: false,
```
Comment (Mamaduka) [inline packages/editor/src/components/post-author/check.js:33]: Can't think of a case when a WP installation won't have at least one author.

Comment (t-hamano) [reply packages/editor/src/components/post-author/check.js:33]: I think that's true, but removing this variable from the conditional statement seems to change the behaviour of the initial render. I don't have a strong opinion, but which do you prefer?

trunk: The Author row itself is not visible until the fetch is complete.

https://github.com/user-attachments/assets/4839cfb7-aed0-4331-8bd0-968d296d7c55

This PR: The post author's name is "(No author)" until the fetch is complete.

https://github.com/user-attachments/assets/74351c7f-f933-4d6a-b34f-63e138be00b5

Comment (Mamaduka) [reply packages/editor/src/components/post-author/check.js:33]: Yes, this behavior is expected and shouldn't be noticeable most of the time.

**Review by t-hamano — APPROVED** [review]
LGTM 👍
