### PR TITLE
Revert: Fix unable to remove empty blocks on merge (#65262) + alternative

### LINKED ISSUE #65174: Difficulty removing empty heading blocks
When editing templates in the Site Editor I cannot easily delete a Heading block. I don't get this behavior when editing a page; I'm pretty sure it's only when editing a template.

In this video I'm pressing the delete button and it's moving the block up the tree. 

https://github.com/user-attachments/assets/21406b53-bbf1-4884-9a8c-2d454102f575

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

In #45075, I added a writing flow behaviour that would unwrap the first paragraph or heading inside a list, quote or group block. #65174 suggests that this behaviour is a bit too much for group blocks. It seems the boundary around group blocks needs to be a little stronger (it's always hard to strike a good balance). The solution would be to exclude the group block from this behaviour. This can easily be done by restricting the behaviour to blocks within the `text` category block (includes quote and list, but excludes group). I have made this change in 9d5dde44213fa640120fb36ffdeb3aed692ca190.

#65262 took an alternative, much more complex, approach. It basically checks if the content of the block to be moved/merged/deleted is empty, but applies this behaviour also to quote blocks. Another issue is that non-empty blocks will still be moved. The added complexity is also significant, so I opted to revert it in c432469e1a7e1865b27462fa018e435c8fa146ae.

Closes https://github.com/WordPress/gutenberg/issues/65174.

## Why?

See #65174 and the explanation above.

## How?

See above, let's exclude non textual blocks from this behaviour.

## Testing Instructions

* Set up a group block with an empty paragraph at the top. Press backspace. The empty paragraph should be deleted.
* This time use a non-empty paragraph. Press backspace at the start. Nothing should happen.
* Then use a non-empty heading. Press backspace at the start. It should be converted to a paragraph.

Now to the following for list and quote

* Try both a non-empty and empty line at the start. Press backspace. It should be moved outside of the list or quote.

Additionally, this provides a generalised solution for removing an aligned paragraph. Test the following content:

```
<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center"></p>
<!-- /wp:paragraph -->
```

In trunk, backspace from this paragraph will not do anything. With this PR, it will remove the alignment.

### CODE REVIEW

**Review by ntsekouras — APPROVED** [review]
This tests well for me and I like the usage of block's category. Thank you!

**Comment by ellatrix** [comment]
Thank you Nik!

File: packages/block-editor/src/components/block-list/block.js [hunk 1]
```diff
@@ -47,8 +47,6 @@ import { PrivateBlockContext } from './private-block-context';
 
 import { unlock } from '../../lock-unlock';
 
-const { isUnmodifiedBlockContent } = unlock( blocksPrivateApis );
```
Comment (jsnajdr) [inline packages/block-editor/src/components/block-list/block.js:50]: Nice to see that we have one less private API now 👍
