### PR TITLE
[Tiny PR] Text patterns: fix undo after mouse move

### LINKED ISSUE #18492: Typing 1, followed by a dot, then space forces a list
Typing 1, followed by a dot, then space forces a list.  See https://wordpress.org/support/topic/5-3-is-forcing-list-creation/?view=all#post-12129804

**To reproduce**
1.  type "1." then space
2.  The line becomes an ordered list
3.  Changing the block to a paragraph block undoes the ordered list, but removes the "1."

**Expected behavior**
I should be able to type listy-looking things without being forced into another block, or at least have an easy way to undo the change.

**Screenshots**

Version: WP 5.3

### PR DESCRIPTION
**Pull request by ellatrix**
## Description
Fixes #18492.

## How has this been tested?

1. Type `1. `  inside a paragraph. The block should convert to a list block.
2. Move the mouse outside the block.
3. Press `Backspace`. The block transform should be undone.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

File: packages/block-editor/src/store/reducer.js [hunk 1]
```diff
@@ -1315,6 +1315,12 @@ export function automaticChangeStatus( state, action ) {
...
 			}
+
+			return;
+		// Undoing an automatic change should still be possible after mouse
+		// move.
+		case 'STOP_TYPING':
+			return state;
 	}
 
 	// Reset the state by default (for any action not handled).
```
Comment (youknowriad) [inline packages/block-editor/src/store/reducer.js]: I think the root problem here is that this is dangerous in reducers in general. I'm pretty sure this error can happen again if we introduce new random actions. That said,  now we have an e2e test to be aware of it at least.

**Review by youknowriad — APPROVED** [review]
While this fixes the issue, the fact that the caret is not in the paragraph after the undo is disturbing but I guess this is a different issue.

File: packages/block-editor/src/store/reducer.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-editor/src/store/reducer.js]: Right, a newly introduced action might need to be added here, but it's more likely that it shouldn't be added here. If we do the opposite, it might be that we do the wrong action on `Backspace`, which I think is worse. I think it's better to whitelist the actions that should be ignored (which there are way less of).

**Comment by ellatrix** [comment]
@youknowriad Right, there a separate PR for that: #17824. Looks like one e2e test needs to be fixed and needs a rebase, but is otherwise looking good. I'll try to fix it sometime soon.

**Comment by ellatrix** [comment]
A transformation e2e tests seem to be consistently failing... and I have no idea why. It seems to be around the full site editing blocks. @jorgefilipecosta or @epiqueras Do you have any idea?

```
FAIL packages/e2e-tests/specs/experimental/block-transforms.test.js (383.667s)
997  ● Block transforms › should contain the expected transforms
998
999    expect(received).toEqual(expected)
1000
1001    Difference:
1002
1003    - Expected
1004    + Received
1005
1006    @@ -374,10 +374,22 @@
1007            "Preformatted",
1008            "Verse",
1009          ],
1010          "originalBlock": "Paragraph",
1011        },
1012    +   "core__post-content": Object {
1013    +     "availableTransforms": Array [
1014    +       "Group",
1015    +     ],
1016    +     "originalBlock": "Post Content",
1017    +   },
1018    +   "core__post-title": Object {
1019    +     "availableTransforms": Array [
1020    +       "Group",
1021    +     ],
1022    +     "originalBlock": "Post Title",
1023    +   },
1024        "core__preformatted": Object {
1025          "availableTransforms": Array [
1026            "Group",
1027            "Paragraph",
1028          ],
```

**Comment by jorgefilipecosta** [comment]
Hi @ellatrix, I'm submitting a fix.

**Comment by epiqueras** [comment]
Thank you @jorgefilipecosta !

Sorry, I read the failures too quickly and thought they were the unrelated group transform failures PRs always get.

**Comment by ellatrix** [comment]
Thanks for the review, @youknowriad!
