### PR TITLE
Decode permalinks with URL encoding

### LINKED ISSUE #13229: Permalinks with RTL on them, displaying their codes instead of the characters
When publishing a post with a non-standard ASCII char (for instance, using RTL) the permalink appears with the character code instead of the character itself

**To Reproduce**
1. Go to a wp site and create a new post with an arabic title (which creates an arabic permalink). I use this to copy the text: https://translate.google.com/#view=home&op=translate&sl=auto&tl=ar&text=hello%20world
2. Publish the post with Gutenberg active
3. On the permalink field, see the codes there: http://cld.wthms.co/5sjUvt
4. Activate the Classic Editor plugin and head to the exact same post - the permalink appears with the characters instead: http://cld.wthms.co/rKe1Y8

**Expected behavior**
I expected the characters to appear as the title show them (as they'll appear in the URL).

**Screenshots**
Codes appearing with Gutenberg active: http://cld.wthms.co/5sjUvt

screen shot on 2019-01-07 at 17_10_23

Chars appearing correctly with Classic Editor: http://cld.wthms.co/rKe1Y8

screen shot on 2019-01-07 at 17_11_39

**Desktop (please complete the following information):**
 - OS MAC Os
 - Firefox

### PR DESCRIPTION
**Pull request by Naerriel**
## Description
Fixes #13229.
Currently slug for the permalink is encoded and that PR simply decodes it.

## How has this been tested?
Ran `npm run test` and looked on the permalinks that were previously encoded and saw that they were decoded.

## Screenshots 
image

## Types of changes
Bug fix.

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style. 
- [X] My code follows the accessibility standards. 
- [X] My code has proper inline documentation. 
- [X] I've included developer documentation if appropriate. 

## Questions:
I've had doubts where in the code this decoding should be done and I've chose the view, as it probably isn't needed elsewhere. Please let me know, what you think.

### CODE REVIEW

File: packages/edit-post/src/components/sidebar/post-link/index.js [hunk 1]
```diff
@@ -33,7 +33,7 @@ function PostLink( {
 } ) {
 	const { prefix, suffix } = permalinkParts;
 	let prefixElement, postNameElement, suffixElement;
-	const currentSlug = postSlug || cleanForSlug( postTitle ) || postID;
+	const currentSlug = decodeURIComponent( postSlug ) || cleanForSlug( postTitle ) || postID;
```
Comment (gziolo) [inline packages/edit-post/src/components/sidebar/post-link/index.js]: @iseulde in other places we use `safeDecodeURI` from `@wordpress/url` package, should we introduce something similar for `decodeURIComponent`?

**Comment by gziolo** [comment]
I think @earnjam or @jorgefilipecosta should be the best suited to help to validate the changes proposed.

**Review by jorgefilipecosta — COMMENTED** [review]
Hi @Naerriel,
Thank you for this improvement.
I noticed there is another place we need to fix. If we go to title the permalink editor appears above it. If we press edit we see the field with the encoded representation. Probably we should add another decodeURIComponent call.

**Comment by Naerriel** [comment]
Hi @jorgefilipecosta 
I have made another decodeURIComponent call in permalink editor, as you have suggested it. During that fix I have also found that `post-publish-panel/panel.js` also requires decoding. Maybe we could just decode it straight in the store?

If I'm correct, I could just decode it in reducer to action `REQUEST_POST_UPDATE_SUCCES`. What do you think?

File: packages/edit-post/src/components/sidebar/post-link/index.js (hunk 1 above)
Comment (earnjam) [reply packages/edit-post/src/components/sidebar/post-link/index.js]: I think that's probably a good idea. If something else modifies `post_name` directly and there was an issue with the encoded string, it would lead to a full editor crash. Better in that case just to return the encoded string. 

@Naerriel can you add a new `safeDecodeURIComponent` function to use for this with `safeDecodeURI` as a model?

**Review by earnjam — CHANGES_REQUESTED** [review]

File: packages/edit-post/src/components/sidebar/post-link/index.js (hunk 1 above)
Comment (Naerriel) [reply packages/edit-post/src/components/sidebar/post-link/index.js]: Naturally. Thank you for feedback.

**Comment by Naerriel** [comment]
Hey @earnjam,
Are those changes satisfactory?

**Review by earnjam — APPROVED** [review]

**Comment by earnjam** [comment]
Sorry for the delay @Naerriel. Just did some testing and this PR looks good to me!

**Comment by rachidev84** [comment]
there's another issue when you switching wordpress to arabic language : 
about RTL :
the permalink display in RTL not in LTR, it must be in LTR because that how it show on all browser.
this is how it look like on wordpress in edit post :
https://prnt.sc/o76dkn

and this is how must be : https://www.byarabic.com/مقالة-الموقع/
Another issue is if someone copy my post link from website and past it in other place via facebook messenger or any browser it show them url with %%%% like this :
https://www.byarabic.com/%d9%85%d9%82%d8%a7%d9%84%d8%a9-%d8%a7%d9%84%d9%85%d9%88%d9%82%d8%b9/

**Comment by aduth** [comment]
@rachidev84 Can you please create a new issue so that this is properly tracked, since this pull request is already merged and will not likely receive much future attention from collaborators?

https://github.com/WordPress/gutenberg/issues/new/choose
