### PR TITLE
Fix: Expose TypeScript types for subcomponents 

### LINKED ISSUE #69615: Popover: Expose TypeScript types for subcomponents
The subcomponents of the `Popover` component are not exposing their TypeScript types, for example as we can witness here:

https://github.com/WordPress/gutenberg/blob/179c868469cb20141f5071a5b8985b88e921be02/packages/components/src/popover/test/utils/index.tsx#L49-L50

This is due to how the component is put together and exported:

https://github.com/WordPress/gutenberg/blob/179c868469cb20141f5071a5b8985b88e921be02/packages/components/src/popover/index.tsx#L520-L525

As we can see [demonstrated](https://github.com/WordPress/gutenberg/blob/179c868469cb20141f5071a5b8985b88e921be02/packages/components/src/menu/index.tsx#L101) in the `Menu` component, there are ways to expose the types correctly with dot-notation subcomponents. When done correctly, the subcomponents can also be documented in the Storybook props tables, as we can see in the one for [`Menu`](https://wordpress.github.io/gutenberg/?path=/docs/components-menu--docs).

There is also some more information in the [Naming Conventions](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CONTRIBUTING.md#naming-conventions) section of the Contributing Guide.

### PR DESCRIPTION
**Pull request by Rishit30G**
## What?
Closes https://github.com/WordPress/gutenberg/issues/69615

## Why?
This PR solves the issue of the subcomponents of the Popover component not exposing their TypeScript type

## How?
Just like the [Menu](https://github.com/WordPress/gutenberg/blob/179c868469cb20141f5071a5b8985b88e921be02/packages/components/src/menu/index.tsx#L101), types for the subcomponents of the Popover are also exposed and no longer require `@ts-expect-error`

## Testing Instructions
N/A

## Screenshots or screencast 
N/A

### CODE REVIEW

File: packages/components/src/popover/index.tsx [hunk 1]
```diff
@@ -501,7 +501,27 @@ const UnforwardedPopover = (
...
  */
-export const Popover = contextConnect( UnforwardedPopover, 'Popover' );
+export const Popover = Object.assign(
+	contextConnect( UnforwardedPopover, 'Popover' ),
+	{
+		/**
+		 * Renders a slot that is used internally by Popover for rendering content.
+		 *
+		 * This should not be used directly in consumer code.
+		 */
```
Comment (mirka) [inline packages/components/src/popover/index.tsx]: Is this true? `Popover.Slot` is documented in the README so I assumed it was official (cc @ciampo who might have extra context).

Comment (Rishit30G) [reply packages/components/src/popover/index.tsx]: @mirka, thanks for the review! 
I'll revert it back as it can be used in the consumer code

Comment (ciampo) [reply packages/components/src/popover/index.tsx]: As much as I'd like to [rely less on `Popover.Slot`](https://github.com/WordPress/gutenberg/issues/56482), it's been part of the public APIs of the package for a long time and I don't think we should explicitly discourage its usage.

Comment (Rishit30G) [reply packages/components/src/popover/index.tsx]: Agreed @ciampo, removed the statement 👍🏻

**Comment by ciampo** [comment]
Refactoring all compound components to use the `Object.assign` syntax would be great — probably best to have a tracking issue to coordinate the effort, and then tackle each component one by one?

**Review by mirka — COMMENTED** [review]
Looking good!

We also want to list `Popover.Slot` in the Storybook `subcomponents`. For the props table to work, this will require a named export for the `PopoverSlot` function before `Object.assign`ing it. So something like:

```tsx
export const PopoverSlot = forwardRef(
	( { name = SLOT_NAME }: { name?: string }, ref: ForwardedRef< any > ) => {
		return (
			<Slot
				bubblesVirtually
				name={ name }
				className="popover-slot"
				ref={ ref }
			/>
		);
	}
);
```

**Comment by Rishit30G** [comment]
Thanks for the review @mirka! 

I have added the `PopoverSlot` subcomponent, however I'm not sure how to and what to add in the prop description for `PopoverSlot`

**Comment by ciampo** [comment]
@Rishit30G you can take inspiration from existing compound components such as [`Tabs`](https://github.com/WordPress/gutenberg/blob/ab89b44cc421d2783840712f8133948bdb6d3aee/packages/components/src/tabs/index.tsx)

**Comment by Rishit30G** [comment]
Thanks @ciampo! 🙇🏻 

I have updated the PR accordingly, sharing a screenshot of the `Popover.Slot` storybook: 

image

File: packages/components/src/popover/index.tsx [hunk 2]
```diff
@@ -481,18 +482,19 @@ const UnforwardedPopover = (
...
-				name={ name }
-				className="popover-slot"
-				ref={ ref }
-			/>
-		);
-	}
-);
+export const PopoverSlot = forwardRef<
+	HTMLDivElement,
+	WordPressComponentProps< PopoverSlotProps, 'div', false >
```
Comment (ciampo) [inline packages/components/src/popover/index.tsx]: No need to use `WordPressComponentProps` here since we're only parsing and using `name`.

```suggestion
	PopoverSlotProps
```

File: packages/components/src/popover/index.tsx [hunk 3]
```diff
@@ -478,6 +479,22 @@ const UnforwardedPopover = (
 	);
 };
 
+/**
+ * `PopoverSlot` is a component that renders a slot that is used by Popover for rendering content.
+ */
```
Comment (ciampo) [inline packages/components/src/popover/index.tsx]: No need to have the JSDocs here, we only need them inside the `Obect.assign` call

File: packages/components/src/popover/index.tsx [hunk 4]
```diff
@@ -478,6 +479,22 @@ const UnforwardedPopover = (
...
+export const PopoverSlot = forwardRef< HTMLDivElement, PopoverSlotProps >(
```
Comment (ciampo) [inline packages/components/src/popover/index.tsx:483]: No need to `export` here, the slot subcomponent can be accessed via `Popover.Slot`

Comment (Rishit30G) [reply packages/components/src/popover/index.tsx:483]: But this component is used in the `index.story.tsx`, removing the export gives an error.

Comment (ciampo) [reply packages/components/src/popover/index.tsx:483]: You should be able to use it via `Popover.Slot`

Comment (Rishit30G) [reply packages/components/src/popover/index.tsx:483]: @ciampo, I did try this approach, but I'm not able to see the props after doing this
It would be helpful if you can share a diff to explain it better 
Thanks! 

```jsx
subcomponents: {
   'Popover.Slot': Popover.Slot,
},
```

image

Comment (ciampo) [reply packages/components/src/popover/index.tsx:483]: Storybook quirks 😅 

In order for Storybook to pick the types up, `PopoverSlot` needs to be name-exported.  So you could simply change the Storybook file:

```diff
diff --git i/packages/components/src/popover/index.tsx w/packages/components/src/popover/index.tsx
index 9c6fc9bddf..63c24b4c1f 100644
--- i/packages/components/src/popover/index.tsx
+++ w/packages/components/src/popover/index.tsx
@@ -479,6 +479,7 @@ const UnforwardedPopover = (
 	);
 };
 
+// Export the PopoverSlot individually to allow typescript to pick the types up.
 export const PopoverSlot = forwardRef< HTMLDivElement, PopoverSlotProps >(
 	( { name = SLOT_NAME }, ref ) => {
 		return (
diff --git i/packages/components/src/popover/stories/index.story.tsx w/packages/components/src/popover/stories/index.story.tsx
index 78c2446d2d..2496e4e506 100644
--- i/packages/components/src/popover/stories/index.story.tsx
+++ w/packages/components/src/popover/stories/index.story.tsx
@@ -12,7 +12,7 @@ import { useState, useRef, useEffect } from '@wordpress/element';
  * Internal dependencies
  */
 import Button from '../../button';
-import { Popover, PopoverSlot } from '..';
+import { Popover } from '..';
 import { PopoverInsideIframeRenderedInExternalSlot } from '../test/utils';
 import type { PopoverProps } from '../types';
 
@@ -38,7 +38,7 @@ const meta: Meta< typeof Popover > = {
 	component: Popover,
 	subcomponents: {
 		// @ts-expect-error - See https://github.com/storybookjs/storybook/issues/23170
-		'Popover.Slot': PopoverSlot,
+		'Popover.Slot': Popover.Slot,
 	},
 	argTypes: {
 		anchor: { control: false },


```

We could also consider moving `PopoverSlot` to a separate file (similar to how, for example, [`Menu.Group` is implemented in a separate file](https://github.com/WordPress/gutenberg/blob/ddfc0258d0891d302c3965238ac711fa02bdde62/packages/components/src/menu/group.tsx)) — but that's optional.

Comment (Rishit30G) [reply packages/components/src/popover/index.tsx:483]: This works 🚀 
Updated the PR!

**Review by ciampo — COMMENTED** [review]
This is looking good, code-wise! We just need to add a CHANGELOG entry

**Comment by Rishit30G** [comment]
Sure, I have added the entry 👍🏻

File: changelog.txt [hunk 5]
```diff
@@ -115,6 +115,7 @@
 
 ### Documentation
 
+- Storybook: Expose Popover TypeScript types for subcomponents. ([69615](https://github.com/WordPress/gutenberg/issues/69615))
```
Comment (ciampo) [inline changelog.txt]: The entry needs to go in `packages/components/CHANGELOG.md`, under the `## Unreleased` section. You can create a `### Documentation` sub-section there.

Comment (Rishit30G) [reply changelog.txt]: Updated, thanks! 👍🏻

**Review by ciampo — APPROVED** [review]
LGTM 🚀

File: packages/components/CHANGELOG.md [hunk 6]
```diff
@@ -2,11 +2,14 @@
 
 ## Unreleased
 
+### Documentation 
+
+-   `Popover`: Expose Popover TypeScript types for subcomponents. ([69615](https://github.com/WordPress/gutenberg/issues/69615))
```
Comment (ciampo) [inline packages/components/CHANGELOG.md]: Actualy refer to this PR

```suggestion
-   `Popover`: Expose Popover TypeScript types for subcomponents. ([69619](https://github.com/WordPress/gutenberg/issues/69619))
```

File: packages/components/CHANGELOG.md [hunk 7]
```diff
@@ -2,11 +2,14 @@
 
 ## Unreleased
 
+### Documentation 
+
+-   `Popover`: Expose Popover TypeScript types for subcomponents. ([69619](https://github.com/WordPress/gutenberg/issues/69619))
```
Comment (ciampo) [inline packages/components/CHANGELOG.md]: Usa same formatting

```suggestion
-   `Popover`: Expose Popover TypeScript types for subcomponents. ([#69619](https://github.com/WordPress/gutenberg/issues/69619))
```

File: packages/components/CHANGELOG.md [hunk 8]
```diff
@@ -2,11 +2,14 @@
 
 ## Unreleased
 
+### Documentation 
+
+-   `Popover`: Expose Popover TypeScript types for subcomponents. ([#69619](https://github.com/WordPress/gutenberg/issues/69619))
```
Comment (ciampo) [inline packages/components/CHANGELOG.md]:
```suggestion
-   `Popover`: Expose Popover TypeScript types for subcomponents. ([#69619](https://github.com/WordPress/gutenberg/pull/69619))
```
