### PR TITLE
Reusable blocks: fix performance of __experimentalGetAllowedPatterns

### LINKED ISSUE #64219: Performance Degradation in the Block Editor after version 18.0.1 for instances with 3000+ block patterns
### Description

I was able to detect significant performance degradation after inserting 3000 block patterns in a clean install of WordPress 6.6. I tested different versions of the Gutenberg plugin, and it looks like this behavior was not present before (and including) version 18.0.1 and was likely introduced after (and including) version 18.1.0 of Gutenberg.

There are delays in multiple actions in the editor, and they all seem to be JS-related, the post editor page loads with no problems, but, after running all the `wp-json/wp/v2/blocks?context=edit&per_page=100&_locale=user&page=<index>` REST requests to load the block patterns in the background the slowness begins - for example: clicking/focusing on a block that is being edited takes around 1 second.

I ran some performance tests on Chrome. I have a hard time figuring out what can be wrong there though - this is the time it takes to focus on a button and for the top context bar to show up:
image

### Step-by-step reproduction instructions

1. Create 3000+ reusable blocks with the CLI using `wp eval 'for ($i = 1; $i <= 3000; $i++) { wp_insert_post(["post_title" => "Reusable Block " . $i, "post_content" => "<!-- wp:paragraph --><p>This is block " . $i . "</p><!-- /wp:paragraph -->", "post_status" => "publish", "post_type" => "wp_block"]); }'`
2. Open the post editor, create two button blocks with some text in it
3. After all the `wp-json/wp/v2/blocks?context=edit&per_page=100&_locale=user&page=<index>` REST requests run in the background (for me it takes around 10 seconds) the editor lag should begin. Click on one button, then click on another button. The context bar for the button should take a long time to show up, more than 1 second.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/67ea9b58-3754-4036-94e8-69cef61a419d

### Environment info

- WordPress 6.6
- Gutenberg plugin 18.1.0
- Google Chrome (127.0.6533.89)
- macOS Sonoma 14.6
- [VIP Local Development Environment](https://docs.wpvip.com/vip-local-development-environment/)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Should fix #64219 and #64732 (which are the same issue I think).

## Why?

The editor freezes when there are thousands of reusable blocks.

## How?

The problem comes from `__experimentalGetParsedPattern`, but more specifically the invalidation function `getPatternBySlug( patternName )`, which in turn uses `getReusableBlocks()` in its invalidation function. Normally this should simply return the existing state, but maybe there's more going on in the underlying `getEntityRecords` call.

In any case, `__experimentalGetParsedPattern` is a terrible selector. It seems more appropriate to cache the parsed patterns in a weak map, which is what I did here. The performance problems seem to be resolved.

## Testing Instructions

Add a huge amount of reusable blocks:
```
wp eval 'for ($i = 1; $i <= 3000; $i++) { wp_insert_post(["post_title" => "Reusable Block " . $i, "post_content" => "<!-- wp:paragraph --><p>This is block " . $i . "</p><!-- /wp:paragraph -->", "post_status" => "publish", "post_type" => "wp_block"]); }'
```

Then click around the editor. What I found particularly lagging in not selecting a block but opening the appender. What I tested was the demo content, then click on the first cover and then on the + appender.

### CODE REVIEW

File: packages/block-editor/src/store/selectors.js [hunk 1]
```diff
@@ -2348,6 +2348,34 @@ export function __experimentalGetDirectInsertBlock(
...
+		blocks,
+	};
+}
+
+function getParsedPattern( pattern ) {
+	const parsedPattern = parsedPatternCache.has( pattern );
+	return parsedPattern ? parsedPattern : parsePattern( pattern );
+}
+
 export const __experimentalGetParsedPattern = createRegistrySelector(
```
Comment (ellatrix) [inline packages/block-editor/src/store/selectors.js:2351]: To do, maybe in a follow-up: deprecate this selector and update all uses.

Comment (ellatrix) [reply packages/block-editor/src/store/selectors.js:2351]: Actually, I just removed the memoization and it seems fine to leave for the remaining use case (pattern block).

File: packages/block-editor/src/store/selectors.js [hunk 2]
```diff
@@ -2349,40 +2349,12 @@ export function __experimentalGetDirectInsertBlock(
...
-			},
-			( state, patternName ) => [
-				unlock( select( STORE_NAME ) ).getPatternBySlug( patternName ),
-			]
-		)
+	( select ) => ( state, patternName ) => {
+		const pattern = unlock( select( STORE_NAME ) ).getPatternBySlug(
+			patternName
+		);
+		return pattern ? getParsedPattern( pattern ) : null;
```
Comment (ellatrix) [inline packages/block-editor/src/store/selectors.js:2356]: This is fine now without memoization, it will always return the same ref.

**Review by jsnajdr — APPROVED** [review]
Nice simplification :+1:

**Comment by vcanales** [comment]
> I just cherry-picked this PR to the wp/6.6 branch to get it included in the next release: [c7f1e8e](https://github.com/WordPress/gutenberg/commit/c7f1e8e1eef9107495474544fa5d0d4fa0a50a7b)

The [Backport to WP Minor Release](https://github.com/WordPress/gutenberg/labels/Backport%20to%20WP%20Minor%20Release) label was not removed; removing manually.
