### PR TITLE
Make sure Social icons links aren't empty and improve UI clarity

### LINKED ISSUE #60044: Social links: Prevent empty links and improve UI description
### Description

After users edit and empty a social link 'label', the link on the front end is empty. No text, no aria-label. Just an empty link.

WordPress should always output semantic, SEO friendly, and accessible HTML. No empty links should ever be allowed.

The resulting HTML output may end up being, for example:
```
<a href="https://github.com/myusername" class="wp-block-social-link-anchor"><svg ...></svg><span class="wp-block-social-link-label"></span></a>
```

Rendering empty links on the front end doesn't help produce high quality, SEO friendly and accessible content. This must be avoided.

Users already have the option to visually hide the social link text and only show the icon. As such, there is no reason to make this link text empty.  It must always be populated with some meaningful text.

This issue is even worse when 'Show labels' in the block setttings panel is disabled as the fact the link is empty is not visible to editors. There's no feedback at all the link is empty. 

Technically, this:

https://github.com/WordPress/gutenberg/blob/c434659b89d9319b7f490aa0405803cfcb12957c/packages/block-library/src/social-link/edit.js#L116

doesn't work very well _after_ users edit the link text.
- The `label` prop is initially undefined, so the default link text is the social network name. So far so good.
- After users edit the link text and then empty it, the `label` prop is set to empty string.
- As such, the empty string is assigned to the link text.

### Step-by-step reproduction instructions

- Add a Social Icons block.
- To better understand this bug, enable 'Show labels' in the block settings panel. Screenshot:

Screenshot 2024-03-20 at 15 50 07

- The social icon links will show their default label, which is the social network name.
- Note: the term 'label' is a bit inappropriate here because this is actually the _link text_.
- Click the plus icon in the block placeholder and add a social link, for example GitHub.
- Click the link placeholder to add an actual link.
- Note: the link input field placeholder is `Enter address` which is inconsistent with other terminology used across the editor.
- Enter a link e.g. `https://github.com/myusername` and save.
- In the block settings panel, expand the 'GitHub label' section. 
- Observe the Link label input field is empty. Expected: to be populated with the default link text e.g. `GitHub`. 
- Note: the description `Briefly describe the link to help screen reader users.` isn't appropriate when 'Show labels' is enabled. In this case, this is the _visible_ link text. Not something only for screen readers. Also, we should rarely mention specific assistive technology. This is the actual link text and should be clarified to users.
- Enter something in the input field.
- Observe the social link text in the editor canvas updates on the fly with the value you entered.
- Empty the input field and save.
- Observe the social link text in the editor canvas disappeared. Expected: to be restored to the default social name.
- Go to the front end and inspect the social link.
- Observe the link is an empty link with no text or any aria-label.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by afercia**
Fixes https://github.com/WordPress/gutenberg/issues/60044

## What?

Social links can be empty when users save the link text input field with an empty value or only spaces.

## Why?

Empty links are far from ideal for semantics. SEO, and accessibility.

## How?

- Makes sure the social link text isn't empty by implementing a fallback to the social name.
- The fallback is transparently shown in the editing UI: Users can still empty the link text input field or save only spaces but the UI will show the social name fallback.
- Terminology: changes 'social media' to 'social' 
- The popover input field placeholder changes from 'Enter address' to 'Enter social link'
- Changes labeling of the input field from default 'URL' to 'Enter social link' so that it matches the visibile placeholder 
- Simplifies the settings panel title to 'Settings'
- Changes the label of the input field from 'Link label' to 'Link text'
- Changes the input description to 'The link text is visible when enabled from the parent Social Icons block.'
- Adds a placeholder to the input field with the social name, as that's the default value 
- Moves the `SocialLinkURLPopover` outside of the social link `Button` so that the tooltip of the button within the popover works.
- In the parent Social Links block, changes the label 'Show labels' to 'Show text'.

## Testing Instructions

- Add a Social Icons block.
- To better test, enable 'Show labels' in the block settings panel.
- Add a Social link.
- Observe the social link shows the social name.
- Click the social link to open the popover and apply a social link URL.
- Hover or focus the 'Apply' button in the popover and observe it shows a tooltip.
- In the block settings inspector, observe the Link Text input field is empty and shows a placeholder with the social name instead of being entirely empty.
- Publish the post.
- Go to the front end and observe the social link does have a link text (the social name).
- In the editor, change the link text to some custom value and save.
- Observe that both the editor and the front end show the new link text.
- In the editor, change the link text to only spaces and save.
- Observe that both the editor and the front end show the social name as the link text.
- In the editor, empty the link text and save.
- Observe that both the editor and the front end show the social name as the link text.
- Check all the new labels and descriptions listed in the 'How' section.

### CODE REVIEW

File: packages/block-library/src/social-link/edit.js [hunk 1]
```diff
@@ -58,7 +58,9 @@ const SocialLinkURLPopover = ( {
 						onChange={ ( nextURL ) =>
 							setAttributes( { url: nextURL } )
 						}
-						placeholder={ __( 'Enter address' ) }
+						placeholder={ __( 'Enter social media link' ) }
```
Comment (richtabor) [inline packages/block-library/src/social-link/edit.js]: I don't think "Enter social media link" is the right placeholder text. Although this is the Social Links block, not all of these are 100% social media links. Meetup, Skype, Mail, to name a few. 

Perhaps "Enter social link" is clearer.

File: packages/block-library/src/social-link/edit.js [hunk 2]
```diff
@@ -128,19 +130,19 @@ const SocialLinkEdit = ( {
 				<PanelBody
 					title={ sprintf(
 						/* translators: %s: name of the social service. */
-						__( '%s label' ),
+						__( '%s link text' ),
```
Comment (richtabor) [inline packages/block-library/src/social-link/edit.js]: I actually think we don't need the social service name here, as it's clear that this is the %s block. Perhaps just the standard "Settings" label is more than enough.

CleanShot 2024-03-20 at 13 47 08

File: packages/block-library/src/social-link/edit.js [hunk 3]
```diff
@@ -128,19 +130,19 @@ const SocialLinkEdit = ( {
...
 						socialLinkName
 					) }
 					initialOpen={ false }
 				>
 					<PanelRow>
 						<TextControl
 							__nextHasNoMarginBottom
-							label={ __( 'Link label' ) }
+							label={ __( 'Link text' ) }
```
Comment (richtabor) [inline packages/block-library/src/social-link/edit.js:139]: We don't use "Link text" as a control label elsewhere. Perhaps we should just use "Text" and allow for the `help` prop to communicate what it is.  

LinkControl uses "Text" and the navigation link block uses "Label" (which needs to be changed to "Text", to map to the LinkControl). I suspect we can do the same here for consistency.

File: packages/block-library/src/social-links/edit.js [hunk 4]
```diff
@@ -203,7 +203,7 @@ export function SocialLinksEdit( props ) {
 					/>
 					<ToggleControl
 						__nextHasNoMarginBottom
-						label={ __( 'Show labels' ) }
+						label={ __( 'Show links text' ) }
```
Comment (richtabor) [inline packages/block-library/src/social-links/edit.js]: "Show links text" doesn't quiet land comprehension-wise. "Show labels" is much more understandable, even though it's not consistent verbiage. Perhaps "Show text" is sufficient.

File: packages/block-library/src/social-link/edit.js (hunk 2 above)
Comment (richtabor) [reply packages/block-library/src/social-link/edit.js]: As an aside, we could probably make the PanelBody start open, like most of the other blocks. There's no reason to really hide it here.

File: packages/block-library/src/social-link/edit.js [hunk 5]
```diff
@@ -128,19 +130,19 @@ const SocialLinkEdit = ( {
...
 							help={ __(
-								'Briefly describe the link to help screen reader users.'
+								'The link text is only visible when Show links text is enabled.'
```
Comment (richtabor) [inline packages/block-library/src/social-link/edit.js]: Perhaps something a bit clearer, like "Visible when enabled from the parent Social Icons block."

**Review by richtabor — COMMENTED** [review]
Nice effort. I left a few notes, leading to this result: 

CleanShot 2024-03-20 at 14 05 22

File: packages/block-library/src/social-link/edit.js (hunk 2 above)
Comment (afercia) [reply packages/block-library/src/social-link/edit.js]: > As an aside, we could probably make the PanelBody start open, like most of the other blocks. There's no reason to really hide it here.

Thanks @richtabor yes good point, will look into it.
For the labels, I'd lean towards 'link text' as that's how most users call a link text.

File: packages/block-library/src/social-link/index.php [hunk 6]
```diff
@@ -21,7 +21,7 @@ function render_block_core_social_link( $attributes, $content, $block ) {
 
 	$service     = ( isset( $attributes['service'] ) ) ? $attributes['service'] : 'Icon';
 	$url         = ( isset( $attributes['url'] ) ) ? $attributes['url'] : false;
-	$label       = ( isset( $attributes['label'] ) ) ? $attributes['label'] : block_core_social_link_get_name( $service );
+	$label       = ( ! empty( $attributes['label'] ) ) ? $attributes['label'] : block_core_social_link_get_name( $service );
```
Comment (ramonjd) [inline packages/block-library/src/social-link/index.php]: Sorry! I had already created a [PR](https://github.com/WordPress/gutenberg/pull/60060) for this, with an extra check in edit.js. It's been merged, but I attributed you in the commit.

Comment (afercia) [reply packages/block-library/src/social-link/index.php]: @ramonjd yes I saw https://github.com/WordPress/gutenberg/pull/60060 this morning, thanks. 
It would be nice to better coordinate. Creating an issue before any non trivial PR, as required by the contributing guidelines of this project, would help avoid duplicated efforts. I don't see any issue associated to https://github.com/WordPress/gutenberg/pull/60060. Thanks.

File: packages/block-library/src/social-link/edit.js (hunk 1 above)
Comment (afercia) [reply packages/block-library/src/social-link/edit.js]: OK then I guess we have to remove 'media' from other descriptions as well, e.g. in the block cards:

Screenshot 2024-03-21 at 10 53 54

File: packages/block-library/src/social-link/edit.js (hunk 2 above)
Comment (afercia) [reply packages/block-library/src/social-link/edit.js]: > I actually think we don't need the social service name here, 

Nice, that would also simplify the label and avoid strings with variable placeholders like `__( '%s label' )`. Those should always be avoided because they're not fully translatable. They are problematic when translators need to swap the order or adjust to genre etc. Example from the current Italian translation:

Screenshot 2024-03-21 at 14 09 03

File: packages/block-library/src/social-link/edit.js (hunk 3 above)
Comment (afercia) [reply packages/block-library/src/social-link/edit.js:139]: > We don't use "Link text" as a control label elsewhere. 

We should. See also https://github.com/WordPress/gutenberg/issues/59993

**Comment by afercia** [comment]
Looks like there is a problem with the 'Mail' icon and text color. Not sure why. Will double check all social icons as well. 

Update: this happens with the following social links:
- Link
- Mail
- RSS feed 
- Goodreads

They're the only ones that by default have dark text on light background. As such, they behave differently when setting a  background color for all the social links, which makes it a bit useless as theny users are forced to set again also the text color. Will create a separate issue.

Screenshot:

Screenshot 2024-03-21 at 14 23 19

**Comment by afercia** [comment]
As a final improvement, I would like to prevent users from saving a link text made of only spaces and fallback to the social name. Will look into it tomorrow.

File: packages/block-library/src/social-link/edit.js (hunk 1 above)
Comment (richtabor) [reply packages/block-library/src/social-link/edit.js]: That's a bit more descriptive with "or site", but sure, I'm fine with that. It's not a particularly great description as-is, if you have ideas on that front.

File: packages/block-library/src/social-link/edit.js (hunk 2 above)
Comment (richtabor) [reply packages/block-library/src/social-link/edit.js]: > For the labels, I'd lean towards 'link text' as that's how most users call a link text.

I'm not sure I'd characterize this as terminology that most users use, but I'm ok with it.

File: packages/block-library/src/social-link/edit.js (hunk 3 above)
Comment (richtabor) [reply packages/block-library/src/social-link/edit.js:139]: I disagree. In LinkControl, it's duplicative to have "Link text" and "Link URL" when you're opening/editing a link.

But what we should do here is the same controls as the Navigation Item blocks (like Custom Link), where you have the same "Text" and "Link" fields, in the same order.

File: packages/block-library/src/social-link/edit.js (hunk 2 above)
Comment (afercia) [reply packages/block-library/src/social-link/edit.js]: I would like to remind everyone 'Link Text' is what users are familiar with since quite a few years as that's what Classic editor always used:

Screenshot 2024-03-22 at 13 46 54

**Comment by afercia** [comment]
In the latest commit I'm trying to make the editing UI reflect what happens on the front end, where an empty link text now always fallbacks to the social name. I'd appreciate some eyes on it and any better idea is welcome.

Basically:
- We want to avoid empty links on the front end.
- The PHP render callback already takes care of the front end.
- In the UI, let users do whatever they want with the inputu field, also save it empty or with only spaces but...
- Make the UI show that en empty value (or only spaces) will fallback to the social name.
- To reflect in the UI the actual behavior, the input field is now initially empty.
- The input placeholder shows the default value (the social name).

Screenshot of the input placeholder that shows the default to the social name:

Screenshot 2024-04-15 at 12 20 21

**Comment by afercia** [comment]
@WordPress/gutenberg-core I'd appreciate a review, when you have a chance 🙇🏽‍♂️

File: packages/block-library/src/social-link/edit.js [hunk 7]
```diff
@@ -125,25 +132,19 @@ const SocialLinkEdit = ( {
...
-								'Briefly describe the link to help screen reader users.'
+								'The link text is visible when enabled from the parent Social Icons block.'
 							) }
-							value={ label || '' }
+							value={ label }
 							onChange={ ( value ) =>
-								setAttributes( { label: value || undefined } )
+								setAttributes( { label: value } )
 							}
+							placeholder={ socialLinkName }
```
Comment (Mamaduka) [inline packages/block-library/src/social-link/edit.js:147]: A nice addition!

**Review by Mamaduka — APPROVED** [review]
Thank you, @afercia!

The changes test well and look good to me from the code perspective ✅

I see there's [an ongoing discussion](https://github.com/WordPress/gutenberg/pull/60047#discussion_r1532550643) regarding new input labels. I'll defer to you and @richtabor on that one.

**Comment by afercia** [comment]
@mamaduka 👋🏽  thanks for your review.

> We don't use "Link text" as a control label elsewhere.

I think [I already mentioned](https://github.com/WordPress/gutenberg/pull/60047#discussion_r1535522540) that's somehow an inaccurate feedback. WordPress always used the terminology 'Link text' since ages. That is what users have been used to see for years in the Classic Editor. I'm not sure looking only at Gutenberg is the best way to provide users with what they _expect_. 

Screenshot of the link editing dialog in Classic Editor:

Screenshot 2024-04-15 at 14 25 13

**Comment by Mamaduka** [comment]
@afercia, I rarely have strong opinions about the labels. I am happy to trust the a11y and the design teams :)

@richtabor, can you have another look on proposed label changes? 🙇

**Comment by afercia** [comment]
Lack of or late feedback should not block this improvement. I'm going to merge it. Labels can always be discussed later and adjusted in the scope of a broader audit of the link editing labels.

**Comment by richtabor** [comment]
> I think https://github.com/WordPress/gutenberg/pull/60047#discussion_r1535522540 that's somehow an inaccurate feedback. WordPress always used the terminology 'Link text' since ages. That is what users have been used to see for years in the Classic Editor. I'm not sure looking only at Gutenberg is the best way to provide users with what they expect.

> Screenshot of the link editing dialog in Classic Editor:

My feedback is accurate. The classic editor is **not** the same experience. 

We should not be making inconsistent one-off changes based on much older iterations. I am always on the side of consistency, with a holistic approach to revising. We don't use "Link text" anywhere in the current WordPress editor.

**Comment by afercia** [comment]
> My feedback is accurate. 

On a general note, honestly I think all contributors should be more open to the fact that other contributors may have different ideas. Disagreement in an open source project is totally fine. Sharing different ideas may even lead to better results. What is not great in a collaborative open source project is to pretend to be always right.

To me, changing long established conventions based on _personal opinions_ isn't great for users.

I'm not opposed to changes _a priori_. But, changes that are only based on _personal opinions_ should at the very least be validated with some _user testing_. In WordPress, the text of a link is called 'Link text' and I don't see any good reason to change it.

**Comment by richtabor** [comment]
> In WordPress, the text of a link is called 'Link text' and I don't see any good reason to change it.

It's not about being right or wrong. Opinions aside, throughout the WordPress editor it's not called "Link text" — except for this one instance. That's objectively a departure from the rest of the editor experience, which I consider a regression.

**Comment by afercia** [comment]
I agree the terminology should be consistent throughout the _entire_ WordPress user interface. That's not only the Gutenberg editor. Looking only at the editor doesn't help providing users with a consistent experience.
I will create a new issue to address this terminology more holistically.
