### PR TITLE
Font size picker: Fix Reset button focus loss

### LINKED ISSUE #57169: Font size picker: the Reset button triggers a focus loss
### Description

The font size picker component can optionally render a 'Reset' button.
When clicked, the reset button gets disabled dynamically with the addition of a `disabled` HTML attribute. Current code:

https://github.com/WordPress/gutenberg/blob/34dbbe4226d1d2bcc99c0eb33a48e42a5064edcd/packages/components/src/font-size-picker/index.tsx#L278-L293

As such, when using a keyboard, the button becomes not focusable _while_ it is focused thus triggering a focus loss.

There have been several occurrences so far where contributors used the `disabled` attribute on elements that are supposed to be focused while they get disabled. We need to avoid this pattern at all costs. Cc @ciampo 

Long time ago we established to use another, more accessible, pattern instead:
- Used `aria-disabled` instead of `disabled`.
- Noop the control.

### Step-by-step reproduction instructions

- Go to the storybook at https://wordpress.github.io/gutenberg/?path=/docs/components-fontsizepicker--docs
- Set the `withReset` prop to `true`.
- Click the icon button `Set custom size`.
- Set a custom size.
- Using the keyboard, move focus to the 'Reset' button.
- Activate the button with the Spacebar key.
- Note: the button doesn't seem to work with the Enter key, this needs to be investigated.
- Observe the button gets disabled dynamically.
- Observe focus is lost.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/57169

From the issue:

> The font size picker component can optionally render a 'Reset' button. When clicked, the reset button gets disabled dynamically with the addiction of a `disabled` HTML attribute.  As such, when using a keyboard, the button becomes not focusable _while_ it is focused thus triggering a focus loss.

>Long time ago we established to use another, more accessible, pattern instead:
>- Used `aria-disabled` instead of `disabled`.
>- Noop the control.

### Step-by-step reproduction instructions

- Go to the storybook at https://wordpress.github.io/gutenberg/?path=/docs/components-fontsizepicker--docs
- Set the `withReset` prop to `true`.
- Click the icon button `Set custom size`.
- Set a custom size.
- Using the keyboard, move focus to the 'Reset' button.
- Activate the button with the Spacebar key.
- Observe focus is not lost.

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]
LGTM 🚢

File: packages/components/src/font-size-picker/index.tsx [hunk 1]
```diff
@@ -276,10 +277,14 @@ const UnforwardedFontSizePicker = (
 						{ withReset && (
 							<FlexItem>
 								<Button
-									disabled={ value === undefined }
-									onClick={ () => {
-										onChange?.( undefined );
-									} }
+									aria-disabled={ isDisabled }
```
Comment (ciampo) [inline packages/components/src/font-size-picker/index.tsx:280]: For the time being, it's probably better to use the current set of props that `Button` makes available:

```suggestion
									disabled={ isDisabled }
									__experimentalIsFocusable
```

Comment (ntsekouras) [reply packages/components/src/font-size-picker/index.tsx:280]: Sounds good. I opened a follow up.
