### PR TITLE
Fix HTML preview for themes applying global margins

### LINKED ISSUE #13414: HTML Preview not displaying correctly for some themes
**Describe the bug**
This seems to be a regression introduced by #13080

For some themes (Twenty Seventeen, Twenty Sixteen, Twenty Fifteen) the Custom HTML block's preview is not displaying correctly:
screen shot 2019-01-22 at 12 01 16 pm

The cause seems to be that those themes have some styles on the `body` element that are now being included in the preview. In the case of Twenty Seventeen:
```
body {
    // ...
    margin: 20px 40px;
    // ...
}
```
This margin is causing the content to overflow the preview.

**To Reproduce**
1. Activate Twenty Seventeen
2. Create a custom html block with some basic content `<div>test</div>`
3. Preview the classic block
4. Observe that the content is not shown in the preview (or is clipped), but the preview does have an inner element with some scrollbars (due to the content overflow) and if you scroll around you'll find the content.

**Expected behavior**
The preview should be displayed clearly without the need to scroll.

**Screenshots**

**Additional context**
- reproduced with 4.9 release candidate 1
- Twenty Nineteen doesn't seem to have this issue (it doesn't have the body margin)

### PR DESCRIPTION
**Pull request by youknowriad**
Some themes might apply global margins/paddings... For the HTML block preview, we need to reset those styles and only apply the content's editor styles.

Fixes #13414

Repeat instructions from the issue to ensure that it's working properly.

### CODE REVIEW

File: packages/block-library/src/html/edit.js [hunk 1]
```diff
@@ -20,7 +20,22 @@ class HTMLEdit extends Component {
...
-		this.setState( { styles: transformStyles( styles ) } );
+
+		// Default styles used to unset some of the styles
+		// that might be inherited from the editor style.
+		const defaultStyles = `
+			html,body,:root {
+				margin: 0 !important;
+				padding: 0 !important;
+				overflow: visible !important;
+				min-height: auto !important;
```
Comment (talldan) [inline packages/block-library/src/html/edit.js]: Did the overflow and min-height solve other issues, or are they pre-emptive?

**Review by talldan — APPROVED** [review]
Thanks for looking into it so quickly. I gave it a test with a couple of the affected themes and it solved the issue. Good that the change is fairly minimal as well.

**Comment by gziolo** [comment]
Should it be 5.0 milestone?

**Comment by youknowriad** [comment]
No, because this will be backported to 4.9 before the actual release.

File: packages/block-library/src/html/edit.js (hunk 1 above)
Comment (jasmussen) [reply packages/block-library/src/html/edit.js]: Yeah good question. 

The two questionable rules are overflow and min-height, and I _believe_ I added those because many themes use overflow as an "auto clearing" measure, and min-height for sites that need to leverage the full viewport height above the fold. 

I can't recall why I unstyled those for the block styles preview but I know they were necessary. 

@kjellr sorry for pinging you the third time today, you're my CSS Yoda — what side effects might there be to changing the overflow and min-height properties? I'm leaning towards these being fine for the purposes of teh HTML preview tab, but would appreciate your thoughts.

**Comment by jasmussen** [comment]
Thank you for fast work here. After a sanity check in https://github.com/WordPress/gutenberg/pull/13416#discussion_r249772442, I think this is probably good to ship.

In testing this, I noticed a separate unrelated issue as a result of the HTML block using the sandbox component. I remember adding this offending rule myself, when working on embeds with @notnownikki, so I'm to blame. Notice how we use an important asterisk rule to unset the top and bottom margins on, in this case, paragraph blocks?

screenshot 2019-01-22 at 14 07 55

Pretty sure I added those rules, _and_ made them important, because I believed that the sandbox component would only ever be used for embeds, where we can't be sure what markup we'll be presented with, and we level the playing field. But we probably need to revisit those rules, and either make them embed only (possible), or at least revisit the problem they were solving.

File: packages/block-library/src/html/edit.js (hunk 1 above)
Comment (kjellr) [reply packages/block-library/src/html/edit.js]: >  what side effects might there be to changing the overflow and min-height properties? I'm leaning towards these being fine for the purposes of teh HTML preview tab, but would appreciate your thoughts.

I did some general testing, and the styles didn't seem to cause any issues either way (keeping these `!important` styles, or removing them). I don't necessarily think it'll be a problem to include them, but I can't figure out what problem they're solving.

Comment (youknowriad) [reply packages/block-library/src/html/edit.js]: The problem they may solve is if the editor styles include things like `html body` or something, which is definitely very rare but I just thought about being certain as the intent is to override the styles no matter what.

Comment (kjellr) [reply packages/block-library/src/html/edit.js]: Ah, I see. Yeah, it probably makes sense to include these as a preventative measure then.
