### PR TITLE
Fix: Gallery does not link to full size images

### LINKED ISSUE #13398: Thumbs in gallery not linking to full images
Hello,

I added a gallery with the thumbs linking to their corresponding images.

In the front end, thumbs are linking to corresponding `large` size images, but not the full resolution ones.

Ex.:

```
<a href="https://demo2.ebadvisormarketing.com/wp-content/uploads/2019/01/rawpixel-760037-unsplash-1024x682.jpg"><img src="https://demo2.ebadvisormarketing.com/wp-content/uploads/2019/01/rawpixel-760037-unsplash-1024x682.jpg" alt="" data-id="56" data-link="https://demo2.ebadvisormarketing.com/homepage-gutenberg/rawpixel-760037-unsplash/" class="wp-image-56" srcset="https://demo2.ebadvisormarketing.com/wp-content/uploads/2019/01/rawpixel-760037-unsplash-1024x682.jpg 1024w, https://demo2.ebadvisormarketing.com/wp-content/uploads/2019/01/rawpixel-760037-unsplash-300x200.jpg 300w, https://demo2.ebadvisormarketing.com/wp-content/uploads/2019/01/rawpixel-760037-unsplash-768x512.jpg 768w, https://demo2.ebadvisormarketing.com/wp-content/uploads/2019/01/rawpixel-760037-unsplash-1200x800.jpg 1200w, https://demo2.ebadvisormarketing.com/wp-content/uploads/2019/01/rawpixel-760037-unsplash-600x400.jpg 600w" sizes="(max-width: 1024px) 100vw, 1024px"></a>
```

Shouldn't the default behaviour be that to link to full sized images?

If it is not, is there a way to edit this behaviour so the gallery images link to full images?

Running WP 5.0.3.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/13398

Currently, when we select a link Media File for the gallery, each image links to large size, that size is one already being seen by the user, the correct link to use should be the full-size image.
Classic editor galleries use the full-size image, and the image block too.
This PR makes sure full-size images are used.

We are changing the save and attributes logic but we don't need to add a deprecation because we are still compatibility with the previous gallery.
That compatibility is ensured because when "link to" is set to "media file" and the fullUrl attribute is not set we fall back to the image URL the value that was previously used.

## How has this been tested?
I added some galleries I verified that when the "link to" option is set to "media file" the gallery links to full-size images.
I changed the galleries above to link to "attachment page" I saved and I reloaded the page, I changed "link to" to "media file" again. I verified the gallery still links to full-size images.
I created some galleries using Gutenberg master (including some galleries that link to "media file" ). I opened the post and verified there were no invalid blocks.

### CODE REVIEW

File: packages/block-library/src/gallery/save.js [hunk 1]
```diff
@@ -17,14 +17,23 @@ export default function save( { attributes } ) {
...
 						break;
 				}
 
-				const img = <img src={ image.url } alt={ image.alt } data-id={ image.id } data-link={ image.link } className={ image.id ? `wp-image-${ image.id }` : null } />;
+				const img = (
+					<img
+						src={ image.url }
+						alt={ image.alt }
+						data-id={ image.id }
+						data-full-url={ image.fullUrl }
```
Comment (ellatrix) [inline packages/block-library/src/gallery/save.js]: Why should this be saved in the HTML?

File: packages/block-library/src/gallery/save.js [hunk 2]
```diff
@@ -17,14 +17,23 @@ export default function save( { attributes } ) {
 
 				switch ( linkTo ) {
 					case 'media':
-						href = image.url;
+						href = image.fullUrl || image.url;
```
Comment (ellatrix) [inline packages/block-library/src/gallery/save.js]: In what cases is there no full size?

Comment (jorgefilipecosta) [reply packages/block-library/src/gallery/save.js]: Current galleries don't have the fullUrl attribute set, this is a simple way to be back-compatible in these cases. Another even more important case where this may happen is when the gallery links to external images e.g: a set of image blocks linking to external URL's is transformed into a gallery.

File: packages/block-library/src/gallery/save.js (hunk 1 above)
Comment (jorgefilipecosta) [reply packages/block-library/src/gallery/save.js]: I replicated exactly the same mechanism used in Attachment page links (data-link attribute), even if the user sets the link to none we save data-link attribute. This happens because the user may create a gallery set the link to none publish, and later come back to the editor and set the link to "Attachment page" or "Media File". When that happens, we need to have the full image URL, and the attachment page URL available so we can link to these destinations. It may also be useful for third-party plugins having these attributes available.

**Comment by jorgefilipecosta** [comment]
Thank you for the review and for the important questions asked @ellatrix 👍  I provided answers to both of them.

File: packages/block-library/src/gallery/save.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-library/src/gallery/save.js]: Why not set it as a block level attribute?

**Comment by ChoccyHobNob** [comment]
Can someone PLEASE approve this!

File: packages/block-library/src/gallery/save.js (hunk 1 above)
Comment (jorgefilipecosta) [reply packages/block-library/src/gallery/save.js]: Hi @ellatrix the only way to set this attribute as a block-level attribute would be by using an attribute that is an array of strings containing the full URL of each image. But, then if the user reordered the images in code (which is something users may expect to work), it will break the block. We do something similar for image id's so the server parser can have access to attributes, but, even for this case we save a data-id attribute in HTML, and we have an attribute sync mechanisms to make sure the reording works. Given that the server has access to image id's, it can quickly get the full URL, so there is no need to perform this mechanism another time.

I guess the ideal solution would be using nested image blocks so these attributes can be normal block attributes of the nested images. But, until we can implement that, I guess this solution is fine as it just replicates what we were doing for another attribute and solves a big problem affecting our users.

**Review by ellatrix — APPROVED** [review]
