### PR TITLE
Update postcss-prefixwrap dependency to 1.51.0 to fix prefixing in `:where` selectors

### LINKED ISSUE #63829: Non-iframed Editor: Compound selectors within `:where` are not prefixed correctly
### Description

When the editor is not iframed, styles have their selectors prefixed with `.editor-styles-wrapper`. An issue arises when the style's selector being processed contains a compound selector within a `:where()` css function. 

The result is incorrect as the selectors within the `:where()`, other than the first, also get the `.editor-styles-wrapper` prefixed. This means part of the final selector doubles up on the `.editor-styles-wrapper` class causing those styles to not be applied as intended.

### Step-by-step reproduction instructions

1. Activate TT4 (which has button styles) and navigate to the post editor
2. Ensure the editor is not iframed. This can be done by enabling the Custom Fields preference via the top right menu More > Preferences > Custom Fields, then reloading the editor.
3. Edit a post and add some buttons, then save
4. Inspect the buttons and find the matched style with the following selector:
`.editor-styles-wrapper :where(.wp-element-button, .editor-styles-wrapper .wp-block-button__link)`
5. Note the injection of the second `.editor-styles-wrapper` within that

### Screenshots, screen recording, code snippet

Screenshot 2024-07-23 at 11 21 58 AM

### Environment info

- 6.6.0
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### LINKED ISSUE #64395: Transform styles utility doesn't prefix CSS selectors correctly for some complex selectors
### Description

`transformStyles()` styles utility works incorrectly for some special selectors. I assume this is because of an issue in `postcss-prefixwrap` which is used by `transformStyles()`. I did try to reproduce this issue in `postcss-prefixwrap` but their test setup is giving me some headaches.

### Step-by-step reproduction instructions

Easiest way to reproduce it is to add the following CSS snippet in the block editor while the iframe **isn't** present, so that the prefixing with `.editor-styles-wrapper` takes place.

```css
:is(.is-layout-flow, .is-layout-constrained) > *:where(:not(h1, h2, h3, h4, h5, h6)) {
  margin-block-start: 0;
}
:is(.is-layout-flow, .is-layout-constrained) :where(h1, h2, h3, h4, h5, h6) {
  margin-block-end: 0
}
```

The resulting CSS is this (**WRONG**):

```css
.test :is(.is-layout-flow, .test .is-layout-constrained) > *:where(:not(h1, .test h2, .test h3, .test h4, .test h5, .test h6)) {
  margin-block-start: 0;
  margin-block-end: var(--theme-content-spacing);
}
.test :is(.is-layout-flow, .test .is-layout-constrained) :where(h1, .test h2, .test h3, .test h4, .test h5, .test h6) {
  margin-block-end: calc(var(--has-theme-content-spacing, 1) * (0.3em + 10px));
}
```

As you can see, the `.test` prefix is added after every comma, which is obviously incorrect. The correct output would be this (**CORRECT**):

```css
.test :is(.is-layout-flow, .is-layout-constrained) > *:where(:not(h1, h2, h3, h4, h5, h6)) {
  margin-block-start: 0;
  margin-block-end: var(--theme-content-spacing);
}
.test :is(.is-layout-flow, .is-layout-constrained) :where(h1, h2, h3, h4, h5, h6) {
  margin-block-end: calc(var(--has-theme-content-spacing, 1) * (0.3em + 10px));
}
```

I know this potentially involves work on the parser but I'm happy to do it if you give me some pointers on where to start looking. If the way is debugging `postcss-prefixwrap`, I will do that.

### Screenshots, screen recording, code snippet

Easiest way to reproduce this problem is to add the following test case in the `packages/block-editor/src/utils/test/transform-styles.js` test file:

```javascript
it( 'should prefix complex selector correctly', () => {
	const input = `:is(.is-layout-flow, .is-layout-constrained) > *:where(:not(h1, h2, h3, h4, h5, h6)) {
margin-block-start: 0;
margin-block-end: var(--theme-content-spacing);
}
:is(.is-layout-flow, .is-layout-constrained) :where(h1, h2, h3, h4, h5, h6) {
margin-block-end: calc(var(--has-theme-content-spacing, 1) * (0.3em + 10px));
}`;

	const output = transformStyles(
		[
			{
				css: input,
			},
		],
		'.test'
	);

	console.log( 'here', { output } );

	expect( output ).toBeTruthy();
} );
```

You will see that the output is as above.

### Environment info

- Latest gutenberg repo, `trunk` branch

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by talldan**
## What?
Fixes #63829
Fixes #64395
Alternative to #63972

Fixes the bug reported in the above issues by updating to the latest version of postcss-prefixwrap so that it includes the fix for this issue - https://github.com/dbtedman/postcss-prefixwrap/issues/515.

## Testing Instructions
Note: Make sure you run `npm i` after checking out this PR locally.

1. Activate TT4 (which has button styles) and navigate to the post editor
2. Ensure the editor is not iframed. This can be done by enabling the Custom Fields preference via the top right menu More > Preferences > Custom Fields, then reloading the editor.
3. Edit a post and add some buttons, then save
4. Inspect the buttons and find the matched style with the following selector:
`.editor-styles-wrapper :where(.wp-element-button, .editor-styles-wrapper .wp-block-button__link)`

In trunk: Note the injection of the second `.editor-styles-wrapper` within that
In this PR: The style should be `.editor-styles-wrapper :where(.wp-element-button, .wp-block-button__link)`

### CODE REVIEW

File: packages/block-editor/src/utils/test/transform-styles.js [hunk 1]
```diff
@@ -125,6 +125,21 @@ describe( 'transformStyles', () => {
 			expect( output ).toMatchSnapshot();
 		} );
 
+		it( `should not try to replace 'body' in the middle of a classname`, () => {
```
Comment (talldan) [inline packages/block-editor/src/utils/test/transform-styles.js:128]: Added this unrelated test as I noticed there wasn't coverage for it.

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for wrangling this fix @talldan 👍 

This is testing as advertised for me.

✅ Before running `npm i`, `.editor-styles-wrapper` was incorrectly inserted within `:where()` as per issues.
✅ After updating `postcss-prefixwrap`, the selector is correctly prefixed.
✅ Selectors for global styles and block style variations are prefixed correctly
✅ Unit tests are passing

Bonus points for the extra tests 🥇 

While testing this PR I also added one to easily confirm pseudo elements on `:where()` selectors were maintained correctly. They were.

If you're interested in an explicit test covering that, I'll include a snippet below.

```JS
		it( 'should not try to prefix pseudo elements on `:where` selectors', () => {
			const input = `:where(.wp-element-button, .wp-block-button__link)::before { color: blue; }`;
			const prefix = '.my-namespace';
			const expected = [ `${ prefix } ${ input }` ];

			const output = transformStyles(
				[
					{
						css: input,
					},
				],
				prefix
			);

			expect( output ).toEqual( expected );
		} );

```

LGTM 🚢

**Comment by sergiu-radu** [comment]
Hey guys, thank you very much for fixing this issue!

I see the fix is added for Gutenberg 19.1, could you please let me know in which version of WP will this fix be included and when I can approximately expect the release?

I have to inform a few of our users, that's why I need to know this.

Thank you one more time 🙏

**Comment by talldan** [comment]
@sergiu-radu The plan is for this to go into a prospective WordPress 6.6.2 release. There was some mention in the release leads channel in slack of 26th August for release (https://wordpress.slack.com/archives/C06U06K50Q5/p1723040995063149), but I'm not sure it has been confirmed yet.

**Comment by sergiu-radu** [comment]
Hi @talldan, got it, thank you very much for letting me know.

**Comment by cbravobernal** [comment]
Removing the label as it was already included in 6.6.2

**Comment by cbravobernal** [comment]
Removing the label as it was already included in 6.6.2
