### PR TITLE
Fix Dropdown/DropdownMenu toggle closing in all UAs

### LINKED ISSUE #29746: Dropdown: always toggles ON when toggle button is clicked in FireFox or Safari on macOS
## Description
When using the Dropdown or [Dropdown Menu](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/dropdown-menu) components, clicking the toggle button always toggles into the `is-opened` state in FireFox and Safari **on macOS**. This behaviour is different when using Chrome, where the component toggles open/closed when the button is clicked.

## Step-by-step reproduction instructions
1. Use the `Dropdown` or `DropdownMenu` components as described in the documentation (https://developer.wordpress.org/block-editor/reference-guides/components/dropdown-menu/#usage-2)
2. In FireFox or Safari on macOS, click on the toggle button to open the dialog and click it again to close the dialog.
3. Note that the dialog closes but is immediately reopened.

## Expected behavior
When the toggle button is clicked, the component should assume the opposite state.

## Screen recording

This screen recording uses Storybook but the issue was also seen in a separate plugin.

| Browser  | OS |  GIF |
| ------------- | ------------- |  ------------- | 
| Chrome (Version 89.0.4389.82 (Official Build) (x86_64))  | macOS (Catalina, 10.15.6) |   |
| FireFox 86 (64-bit)  | macOS (Catalina, 10.15.6) |   |

## WordPress information
- WordPress version: (5.8-alpha-50521)
- Gutenberg version:  trunk@https://github.com/WordPress/gutenberg/commit/79b576be1b17c9896ea3c0e0de10082eafbe6ecd

### PR DESCRIPTION
**Pull request by stokesman**
The Dropdown (and DropdownMenu) components have broken toggle behavior in some browsers (notably Safari and Firefox on macOS). Making the root element of the `Dropdown` component focusable makes its current toggling logic work as intended.

Before this PR, I'd tried alternate approaches (#30397, #30786) that were not nearly as simple.

## Explainer
The intended behavior depends on testing that the focused element is inside of the dropdown component:
https://github.com/WordPress/gutenberg/blob/745399800a3e894016ab547127d90ef502d9b127/packages/components/src/dropdown/index.js#L68
The UAs in which the current logic fails do not focus buttons when pressed. Instead, focus goes to the closest focusable containing element and ends up outside of the component. The change here ensures that focus won't leave the component and thus the current logic will work.

## Extra
I threw in an extraneous but related change b67dbcf469d1c962da305e755a3c79ee7267ab7b to remove a workaround that had been made due to the buggy dropdown behavior.

## How has this been tested?
Manually in Chrome, Firefox and Safari on macOS. In the post editor and site editor, toggling all the dropdowns.

## Types of changes
Bug fix #29746

## Screenshots
Before: the broken toggling of various dropdowns in Safari on macOS.

https://user-images.githubusercontent.com/9000376/115271103-d53c6680-a0f1-11eb-997f-0fc677149c1b.mp4

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by aristath** [comment]
Changing the tabindex affects a11y so this will PR needs a11y feedback. Added the related tag :+1:

**Comment by ellatrix** [comment]
@stokesman I came to the same conclusion in #30392. Could you rebase this PR?

File: packages/components/src/dropdown/index.js [hunk 1]
```diff
@@ -85,6 +85,7 @@ export default function Dropdown( {
 		<div
 			className={ classnames( 'components-dropdown', className ) }
 			ref={ containerRef }
+			tabIndex="-1"
```
Comment (ellatrix) [inline packages/components/src/dropdown/index.js:91]: Could you leave a comment here? Maybe

```suggestion
			// Safari sometimes moves focus to a focusable parent when clicking
			// a button. By making this div focusable, we can detect if the
			// toggle has been clicked in Safari for `closeIfFocusOutside`.
			tabIndex="-1"
```

**Review by ellatrix — APPROVED** [review]
Works great!

**Comment by mtias** [comment]
@diegohaz can you take a brief look as well?

**Comment by stokesman** [comment]
Thanks for reviewing @ellatrix! It's rebased with a comment like the suggested.

**Review by diegohaz — APPROVED** [review]
The ideal solution would be ignoring clicks on the toggle button when the popover is open (without using `disabled`). But this looks like an easier workaround, so let's go for it for now.

**Comment by stokesman** [comment]
Thanks for reviewing @diegohaz 🙇 

> The ideal solution would be ignoring clicks on the toggle button when the popover is open

Tricky since a `click` comes after the popover has already closed via `blur`. So it might be simpler if we made the toggle button act on `pointerdown` instead of `click`. I think then its action would not need ignored when the popover is open, as it would beat `onFocusOutside`/`blur` to the punch.
