### PR TITLE
Make the core color palette opt-in for themes with not `theme.json`

### LINKED ISSUE #36489: Core palette can no longer be overridden from PHP
### Description

Setting brand colours no longer works in gutenberg it's working fine in WP 5.8.2  it is not working in Gutenberg Version 11.9.0 

Core colours can no longer be removed. 

Removing "core" colours is VITAL for branded corporate sites.

PHP support is VITAL for established sites and those being developed away from your bleeding edge

### Step-by-step reproduction instructions

METHOD

in PHP enter this in a theme functions.php

`
function sc_custom_gutenberg_custom_color_palette() {
	add_theme_support( 'editor-color-palette', array(
		array(
			'name'  => __( 'Light Text', 'sc' ),
			'slug'  => 'light-text',
			'color'	=> '#FFFFFF',
		),
		array(
			'name'  => __( 'Darker Text', 'sc' ),
			'slug'  => 'darker-text',
			'color'	=> '#535353',
		),
		array(
			'name'  => __( 'Amaranth', 'sc' ),
			'slug'  => 'main-amaranth',
			'color'	=> '#E23448',
		),
		)
	);
}
add_action( 'after_setup_theme', 'sc_custom_gutenberg_custom_color_palette', 20 );
`

the editor will continue to show the awful "core" colours + the new array

### WP 5.8.2 core - colours can be set correctly
core-cols-override-wp-582

 **Gutenberg Version 11.9.0 - awful colours persist**
gut-col-disaster

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by oandregal**
Follow-up to https://github.com/WordPress/gutenberg/pull/36492 https://github.com/WordPress/gutenberg/pull/35970

In https://github.com/WordPress/gutenberg/pull/35970 we introduced the ability to show three different palettes (default, theme, user) in the color UI component. We also have a couple of flags for themes to disable this should they want (`corePalette`, `coreGradients`). However, by introducing this change, themes that don't use `theme.json` will now see the default colors as well.

This PR introduces the following changes:

- Hides the default palette for themes with no `theme.json` that declare its own palette.
- Adds new theme supports for themes with no `theme.json` to opt-in into the default solid and gradient palettes, so they can show both the default and the theme one:
  - `default-color-palette` which mimic the existing `editor-color-palette` theme supports
  - `default-gradient-presets` which mimics the existing `editor-gradient-presets` theme support

## How to test

Test a theme that does not provide a palette:

- Use Storefront.
- Load the editor and verify that the color component shows the default palette.

Test a theme that provides a palette:

- Use TwentyTwentyOne.
- Load the editor and verify that the color component only shows the theme solids&gradients but not the default ones (they'll be shown without this PR).

Test a theme that provides a palette and opts-in into the core palette:

- Use TwentyTwentyOne.
- Add `add_theme_support( 'default-color-palette' )` and `add_theme_support( 'default-gradient-presets' )` in its `functions.php`.
- Load the editor and verify that the color component shows both the default and the theme palettes for solids & gradients.

### CODE REVIEW

**Review by fabiankaegy — APPROVED** [review]

**Comment by fabiankaegy** [comment]
Closes #36489

File: phpunit/class-wp-theme-json-resolver-test.php [hunk 1]
```diff
@@ -118,8 +118,8 @@ function test_translations_are_applied() {
 	}
 
 	function test_switching_themes_recalculates_data() {
-		// By default, the theme for unit tests is "default",
-		// which doesn't have theme.json support.
+		// The "default" theme doesn't have theme.json support.
+		switch_theme( 'default' );
```
Comment (Mamaduka) [inline phpunit/class-wp-theme-json-resolver-test.php:122]: It might not be accurate in the future, but it works for now.

**Review by Mamaduka — APPROVED** [review]
It works as expected.

| Before | After |
| --- | --- |
| CleanShot 2021-11-16 at 14 39 40 | CleanShot 2021-11-16 at 14 40 15 |

**Comment by oandregal** [comment]
This is not ready to land. We need to also cover the case in which the theme does not provide any theme palette: in that case, we still need to show the core one. Updated PR description with instructions for testing.

**Comment by Mamaduka** [comment]
@oandregal, I'm going to add the "In Progress", so we don't merge it by accident 😄

**Comment by oandregal** [comment]
@fabiankaegy @Mamaduka This is now ready to test.

I've run this by some folks (Matías and others) and they think it's best to add new theme supports that classic themes can use to opt-in into this, so I've done that as well. Another point of feedback was that we should rename `core` into `defaults` everywhere. I'll create a separate follow-up PR for that change.

**Comment by oandregal** [comment]
I'm going to go ahead and merge this one to unblock https://github.com/WordPress/gutenberg/pull/36622 Please, feel free to do post-merge reviews and I'll address any issue left.

**Comment by Mamaduka** [comment]
I did another test run and works as expected 👍

**Comment by steveangstrom** [comment]
This is not fixed in Gutenberg 12.0.1

What I see
Screenshot 2021-11-26 at 00-01-00 Add New Page ‹ Sitename — WordPress

I need to hide core colours completely.

**Comment by steveangstrom** [comment]
This is not fixed in Gutenberg 12.0.1 . Still broken there.  I have a wall of ugly "core".

I assume that's intentional?

Is there a timeline for this patch to make it into the released plugin?

**Comment by oandregal** [comment]
Hey Steve, this is going to be part of the 12.1 release, which should be a few days away.
