### PR TITLE
Components: Track scroll position of all parent scrollable nodes

### LINKED ISSUE #2999: Tooltips do not preserve position on scroll
## Issue Overview
Tooltips do not scroll with the element they're supposed to attached to.

## Steps to Reproduce (for bugs)
1. Hover over or focus something with a tooltip.
2. Scroll. The tooltip won't scroll with the page.

## Possible Solution
I assume the tooltip is fixed positioned. Maybe absolute positioning works out better?

### PR DESCRIPTION
**Pull request by youknowriad**
Try to fix #2999 

Not sure if there are performance concerns about this, or if it's a good solution but this tries to fix popovers position if we scroll one of their parents.

**Testing instructions**

 - Hover a button with a tooltip,
 - Scroll slightly
 - The tooltip should adapt its position

### CODE REVIEW

File: components/popover/index.js [hunk 1]
```diff
@@ -25,6 +25,17 @@ const { ESCAPE } = keycodes;
  */
 const ARROW_OFFSET = 20;
 
+function getScrollParents( node ) {
+	if ( ! node ) {
+		return [];
+	}
+	const parentScrollables = getScrollParents( node.parentNode );
+	if ( node.scrollHeight > node.clientHeight ) {
```
Comment (youknowriad) [inline components/popover/index.js]: Thinking this doesn't solve the issue if the parent has no scrollbars yet unless we add content later.

**Comment by youknowriad** [comment]
Ok simplified this, it looks like using the "capturing" flag catches all scroll events over the page. and it fixes the issue.

**Comment by iseulde** [comment]
If I know _that_ was the issue... https://github.com/WordPress/gutenberg/pull/2858/files#diff-a7dcd2d17f454484a328ec65ca81486aR142 :)

File: components/popover/index.js [hunk 2]
```diff
@@ -123,10 +123,10 @@ export class Popover extends Component {
 
 	setOffset() {
 		const { anchor, popover } = this.nodes;
-		const { parentNode } = anchor;
-		if ( ! parentNode ) {
+		if ( ! anchor || ! anchor.parentNode ) {
 			return;
 		}
+		const { parentNode } = anchor;
```
Comment (iseulde) [inline components/popover/index.js]: Both `anchor.parentNode` and `{ parentNode } = anchor` in one place feels a bit weird to me.

**Review by ellatrix — APPROVED** [review]
🎉 Works great now.

File: components/popover/index.js (hunk 2 above)
Comment (youknowriad) [reply components/popover/index.js]: yep we could avoid destructuring
