### PR TITLE
Author: Show only users capable of authoring posts

### LINKED ISSUE #2157: REST API: List users by capability or level for author selection
Related: #2100 (specifically https://github.com/WordPress/gutenberg/pull/2100#discussion_r130392615)

The author selection should not present options for users without the [`edit_posts`](https://codex.wordpress.org/Roles_and_Capabilities#edit_posts) capability. In default installations, this means excluding the Subscriber role. The [users listing endpoint](https://developer.wordpress.org/rest-api/reference/users/#list-users) currently supports filtering by role. However, we ought not to hard-code default roles since plugins or themes can [add their own custom roles](https://developer.wordpress.org/plugins/users/roles-and-capabilities/#adding-roles). Therefore, we should seek to enhance the user listing endpoint with one of a few options:

- Support filtering by capability
- Support filtering by `authors` type
- Support filtering by [`user_level`](https://codex.wordpress.org/Roles_and_Capabilities#User_Levels)
   - `authors` is equivalent to `user_level != 0`

The latter two mimic the behavior of the [`wp_dropdown_users` function](https://github.com/WordPress/WordPress/blob/a193916/wp-includes/user.php#L973-L1147) used in the current editor to display user options. The `who` values is an undocumented parameter supported by the `WP_User_Query` class which [filters by `user_level != 0`](https://github.com/WordPress/WordPress/blob/a193916/wp-includes/class-wp-user-query.php#L322).

References:

- [`post_author_meta_box`](https://github.com/WordPress/WordPress/blob/26fcea4/wp-admin/includes/meta-boxes.php#L761-L782)
- [`wp_dropdown_users`](https://github.com/WordPress/WordPress/blob/a193916/wp-includes/user.php#L973-L1147)
- [`WP_User_Query`](https://github.com/WordPress/WordPress/blob/a193916/wp-includes/class-wp-user-query.php)

### LINKED ISSUE #2491: Authors Dropdown Lists Names That Can't Publish Posts
In Gutenberg 0.9.0, the Authors drop-down box lists names that shouldn't be listed. I expect to see only names who have the ability to publish posts and or pages on the site. The list of names I'm seeing are subscribers. I don't think users with the Subscriber role should be listed in this box. 
authorsbug

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

### LINKED ISSUE #2524: Post Author: Post becomes perpetually flagged as dirty ("Save Post")
## Issue Overview

When assigning a user to a post, the post will forever be flagged as having unsaved changes, even after pressing Save Changes.

[Screencast](https://cloudup.com/cPtbdgVXBcE)

## Steps to Reproduce (for bugs)

1. (Prerequisite) Ensure there are two or more users on the site
2. Navigate to Gutenberg > New Post
3. Enter a title
4. Assign an author
5. Save the post

## Expected Behavior

The post is saved and reflected as such with a "Saved" label, and no option to Save.

## Current Behavior

The post saves, but immediately shows Save Draft again, indicating there are unsaved changes. Attempting to navigate away will prompt.

## Possible Solution

Cursory review shows that this is caused by the PostAuthor component assigning user ID as a string:

https://github.com/WordPress/gutenberg/blob/7a19916deed3e8c0f9d1944927bf17dc434cf2d7/editor/sidebar/post-author/index.js#L63

When the dirty detection compares against the saved post value (a numeric ID), they are not strictly equal.

### PR DESCRIPTION
**Pull request by aduth**
Related: #2029
Closes #2491 
Closes #2157 
Fixes #2524 

This pull request seeks to account for user capabilities in deciding which options to show in the Author select dropdown. It also refactors the component to use the `withAPIData` higher-order component introduced in #1974, fixes an issue with author selection permanently causing a post to be flagged as dirty, and adds unit tests.

__Testing instructions:__

Repeat testing instructions from #2100

### CODE REVIEW

File: editor/sidebar/post-author/index.js [hunk 1]
```diff
@@ -73,15 +74,23 @@ class PostAuthor extends Component {
...
+			users: '/wp/v2/users?context=edit&per_page=100',
 		};
-	},
-	{
-		onUpdateAuthor( author ) {
-			return editPost( { author } );
-		},
-	},
-)( withInstanceId( PostAuthor ) );
+	} ),
```
Comment (youknowriad) [inline editor/sidebar/post-author/index.js]: Do you think we should enforce a convention here, something like this;

```js
const connectComponent = connect( ... );
const fetchAPIData = withApiData( ... );

export default flowRight( [
  connectComponent,
  fetchAPIData,
] )( Component );
```

Comment (aduth) [inline editor/sidebar/post-author/index.js]: Maybe. Naming things is hard :smile: For example, the API data higher-order component doesn't necessarily incur a fetch (might be used only for updating), and itself doesn't perform the fetch. All it does is apply a wrapping (higher-order) component.

I think if we were to, we'd want some easy convention for naming, like a consistent prefix. Maybe "apply": `applyConnect`, `applyWithAPIData`

Comment (youknowriad) [inline editor/sidebar/post-author/index.js]: sound good to me. I'll follow the convention chosen here in my PRs

Comment (aduth) [reply editor/sidebar/post-author/index.js]: Out of curiosity, what's your reason for wanting a convention here? Are you finding this could be difficult to interpret?

Comment (youknowriad) [reply editor/sidebar/post-author/index.js]: My primary reason is to avoid indentation changes when moving from one HoC to composed HOCs. But I also find it more readable.
