### PR TITLE
RichText: useAnchor: Fix TypeError in virtual element

### LINKED ISSUE #75897: Popover: JS error triggers on autocomplete popovers when used at the end of blocks lines
### Description

When you type `@admin` close to the edge of a long paragraph, a popover is supposed to render to show you the matched users, very often a JS error is triggered causing the whole block to collapse.

### Step-by-step reproduction instructions

1- Create a block
2- Insert a long paragraph
3- Focus close to the edge of the first row
4- Type `@admin`
5- Noticed the block collapsing.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/9e9c2701-491c-4532-8451-152c0de3ca95

### Environment info

Tested on Chrome, not sure if reproducible on others.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by mcsf**
## What?

Fixes #75897

Steps to reproduce are in the parent issue

### CODE REVIEW

**Comment by mcsf** [comment]
I'll note that this one would have readily been caught by our type checker if it were enabled in that file (by converting it to `.ts` or simply by using the `// @ts-check` directive. Try it yourself: you'll see more errors in the file.

**Comment by mcsf** [comment]
While debugging I noticed this:

https://github.com/user-attachments/assets/0f0eacaf-4210-477f-b147-2450f868fded

Is it a smell that the virtual element's `getBoundingClientRect` is called so often?

File: packages/rich-text/src/hook/use-anchor.js [hunk 1]
```diff
@@ -87,9 +87,14 @@ function createVirtualAnchorElement( range, editableContentElement ) {
...
 		contextElement: editableContentElement,
 		getBoundingClientRect() {
-			return editableContentElement.contains( range.startContainer )
-				? getRectangleFromRange( range )
-				: editableContentElement.getBoundingClientRect();
+			if ( editableContentElement.contains( range.startContainer ) ) {
+				const rect = getRectangleFromRange( range );
+				if ( rect ) {
+					return rect;
+				}
```
Comment (Mamaduka) [inline packages/rich-text/src/hook/use-anchor.js]: > Use instead of `Range.getBoundingClientRect()`, which is often broken, especially for collapsed ranges.

Based on this documentation part, I wonder which is better in this case. Returning `editableContentElement.getBoundingClientRect()` as a fallback or trying `Range.getBoundingClientRect()`. Ref: #73853.

Comment (mcsf) [reply packages/rich-text/src/hook/use-anchor.js]: Not sure. Does it matter much? Also cc @ntsekouras

Comment (Mamaduka) [reply packages/rich-text/src/hook/use-anchor.js]: With the cursor/text-selection rects, inline popovers should have better (more accurate) positioning.

Comment (mcsf) [reply packages/rich-text/src/hook/use-anchor.js]: Yeah, I see what you mean. So, to confirm, the chain of fallbacks you were thinking of was:

1. getRectangleFromRange 
2. Range.getBoundingClientRect
3. editableContentElement.getBoundingClientRect

Yes?

Comment (Mamaduka) [reply packages/rich-text/src/hook/use-anchor.js]: Yeah, seems "safest" approach.

Though it would be nice to get a second opinion from folks who are more familiar with this anchor logic. cc @ellatrix, @ciampo

```diff
diff --git a/packages/rich-text/src/hook/use-anchor.js b/packages/rich-text/src/hook/use-anchor.js
index 4746b15d95f..36d7390af3e 100644
--- a/packages/rich-text/src/hook/use-anchor.js
+++ b/packages/rich-text/src/hook/use-anchor.js
@@ -88,10 +88,10 @@ function createVirtualAnchorElement( range, editableContentElement ) {
 		contextElement: editableContentElement,
 		getBoundingClientRect() {
 			if ( editableContentElement.contains( range.startContainer ) ) {
-				const rect = getRectangleFromRange( range );
-				if ( rect ) {
-					return rect;
-				}
+				return (
+					getRectangleFromRange( range ) ??
+					range.getBoundingClientRect()
+				);
 			}
 
 			return editableContentElement.getBoundingClientRect();
```

Comment (ciampo) [reply packages/rich-text/src/hook/use-anchor.js]: This feels like a good approach to me. From what I recall, `getRectangleFromRange` returns `null`in a very specific edge case (multiple rects for a collapsed range), and in that case, `range.getBoundingClientRect()` feels like a reasonable fallback (always guaranteed to return a `DomRect`, and also not too far from the cursor).

**Comment by ciampo** [comment]
> Is it a smell that the virtual element's `getBoundingClientRect` is called so often?

I think that's expected behaviour (the underlying `floating-ui` library polling the location of its anchor to make sure the popover is always following it). I remember testing different options a few years ago and finding that this strategy, albeit computationally expensive, was the most reliable. Not sure if things have changed since then.

> I'll note that this one would have readily been caught by our type checker if it were enabled in that file (by converting it to `.ts` or simply by using the `// @ts-check` directive. Try it yourself: you'll see more errors in the file.

1000%. IMO we should try to convert these files to TS as much as possible, as we get an extra layer of static linting that can really iron out a lot of subtle bugs, such as the one fixed in this PR.

**Comment by mcsf** [comment]
Thanks for the feedback, everyone! I've pushed the change with the fallback.

I also have a Git stash that fixes all type errors in the module, will put up a PR after lunch.

**Review by Mamaduka — APPROVED** [review]

**Comment by youknowriad** [comment]
I appreciate the quick fix folks ❤️

**Comment by Mamaduka** [comment]
Added the backport label for the bugfix. It's a bug that affects the Gutenberg version included in this release.
