### PR TITLE
Zoom Out: fix crash due to absence of selected block

### LINKED ISSUE #63456: Editor crash from block deselection in “Zoom Out” mode
### Description

While zoomed out, deselecting a block crashes the editor. I first happened across this by undoing a pattern insertion. Now I found that just clicking somewhere that doesn’t select a new block but does deselect the currently selected one will crash it too.

Here’s the error from the crash boundary:

```
TypeError: Cannot destructure property 'name' of 'getBlock(...)' as it is null.
    at http://localhost:8888/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=0739551982adc596213c:28422:7
    at http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.min.js?ver=65dd8ddc0f9260605b50:1705:70
    at __unstableMarkListeningStores (http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.min.js?ver=65dd8ddc0f9260605b50:4402:23)
    at Object.__unstableMarkListeningStores (http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.min.js?ver=65dd8ddc0f9260605b50:4477:30)
    at updateValue (http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.min.js?ver=65dd8ddc0f9260605b50:1705:34)
    at http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.min.js?ver=65dd8ddc0f9260605b50:1746:5
    at useMappingSelect (http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.min.js?ver=65dd8ddc0f9260605b50:1771:7)
    at useSelect (http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.min.js?ver=65dd8ddc0f9260605b50:1855:58)
    at ZoomOutToolbar (http://localhost:8888/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=0739551982adc596213c:28409:78)
    at renderWithHooks (webpack://gutenberg/./node_modules/react-dom/cjs/react-dom.development.js?:15486:18)
```

### Via block deselection
1. With the Zoom Out experiment enabled
2. Open a post that has content
3. Open the inserter, select a pattern category
4. Select a block
5. Click somewhere that will deselect the block without selecting another
6. Note the crashed editor

### Via Undo
1. With the Zoom Out experiment enabled
2. Go to the Site editor and select a page to edit
3. Open the inserter, select a pattern category and insert a pattern
4. Undo
5. Note the crashed editor

### Via block deselection

https://github.com/user-attachments/assets/5410ad0e-90ea-4b53-9354-be68247ed2e2

### Via Undo

https://github.com/WordPress/gutenberg/assets/9000376/9b9c8e4f-201c-4c5e-89e3-1c2758a67101

### Environment info

- WP 6.5 / Gutenberg Trunk / Twenty Twenty-Four
- Chrome
- Desktop macOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by stokesman**
## What?
A fix for crashes in the editor while zoomed out when either a block is removed or a block is deselected.

## Why?
Without this it’s fairly easy to crash the editor in Zoom Out. To fix #63456.

## How?
Revises the show block tools hook to avoid returning `true` for `showZoomOutToolbar` when no block is selected.

### Undo while zoomed out
1. With the Zoom Out experiment enabled
2. Go to the Site editor and select a page to edit
3. Open the inserter, select a pattern category and insert a pattern
4. Undo
5. Note there is no crash

### Deselect a block while zoomed out
1. With the Zoom Out experiment enabled
2. Open a post that has content
3. Open the inserter, select a pattern category
4. Select a block
5. Click somewhere that will deselect the block without selecting another
6. Note there is no crash

### CODE REVIEW

File: packages/block-editor/src/components/block-tools/use-show-block-tools.js [hunk 1]
```diff
@@ -57,7 +59,8 @@ export function useShowBlockTools() {
 				! _showEmptyBlockSideInserter && maybeShowBreadcrumb,
 			showBlockToolbarPopover: _showBlockToolbarPopover,
 			showZoomOutToolbar:
-				editorMode === 'zoom-out' &&
+				hasSelectedBlock &&
```
Comment (stokesman) [inline packages/block-editor/src/components/block-tools/use-show-block-tools.js:62]: So this was probably the only key change to fix the issue. The other changes I felt were minor code quality improvements.

File: packages/block-editor/src/components/block-tools/use-show-block-tools.js [hunk 2]
```diff
@@ -29,10 +29,11 @@ export function useShowBlockTools() {
 		const clientId =
 			getSelectedBlockClientId() || getFirstMultiSelectedBlockClientId();
 
-		const block = getBlock( clientId ) || { name: '', attributes: {} };
+		const block = getBlock( clientId );
```
Comment (jeryj) [inline packages/block-editor/src/components/block-tools/use-show-block-tools.js:32]: If I recall, we wanted to keep the structure the same if nothing was found due to memoization: `{ name: '', attributes: {} };`. I think @Mamaduka recommended this.

File: packages/block-editor/src/components/block-tools/use-show-block-tools.js [hunk 3]
```diff
@@ -29,10 +29,11 @@ export function useShowBlockTools() {
...
 		const editorMode = __unstableGetEditorMode();
-		const hasSelectedBlock = clientId && block?.name;
-		const isEmptyDefaultBlock = isUnmodifiedDefaultBlock( block );
+		const hasSelectedBlock = !! clientId && !! block;
+		const isEmptyDefaultBlock =
+			hasSelectedBlock && isUnmodifiedDefaultBlock( block );
```
Comment (jeryj) [inline packages/block-editor/src/components/block-tools/use-show-block-tools.js:36]: I don't think we should tie the `hasSelectedBlock` condition here to the `isEmptyDefaultBlock`.

File: packages/block-editor/src/components/block-tools/use-show-block-tools.js [hunk 4]
```diff
@@ -29,10 +29,11 @@ export function useShowBlockTools() {
 		const clientId =
 			getSelectedBlockClientId() || getFirstMultiSelectedBlockClientId();
 
-		const block = getBlock( clientId ) || { name: '', attributes: {} };
+		const block = getBlock( clientId );
 		const editorMode = __unstableGetEditorMode();
-		const hasSelectedBlock = clientId && block?.name;
-		const isEmptyDefaultBlock = isUnmodifiedDefaultBlock( block );
+		const hasSelectedBlock = !! clientId && !! block;
```
Comment (jeryj) [inline packages/block-editor/src/components/block-tools/use-show-block-tools.js:34]: I think the `!!` for this line is a good change, but undo the other refactoring.

File: packages/block-editor/src/components/block-tools/use-show-block-tools.js (hunk 1 above)
Comment (jeryj) [reply packages/block-editor/src/components/block-tools/use-show-block-tools.js:62]: Nice find!

**Review by jeryj — COMMENTED** [review]
I was going to fix this and found you had already put in a PR. Thanks for the zoom out improvements! I think let's fix just the root issue and maybe add the double bang on `hasSelectedBlock`. Otherwise I think we should leave the rest of the hook the same for now.

File: packages/block-editor/src/components/block-tools/use-show-block-tools.js (hunk 2 above)
Comment (stokesman) [reply packages/block-editor/src/components/block-tools/use-show-block-tools.js:32]: It seems like the only reason for this is so that `block` can be passed to `isUnmodifiedDefaultBlock` which doesn’t guard against nullish values. Beyond that `block` is unused so it’s okay to be nullish.

File: packages/block-editor/src/components/block-tools/use-show-block-tools.js (hunk 3 above)
Comment (stokesman) [reply packages/block-editor/src/components/block-tools/use-show-block-tools.js:36]: Why even call `isUnmodifiedDefaultBlock` if there is no selected block? I.e. without a selection it can’t be a empty default block right?

**Comment by stokesman** [comment]
Thanks for the review 🙇 

> I think let's fix just the root issue and maybe add the double bang on `hasSelectedBlock`. Otherwise I think we should leave the rest of the hook the same for now.

I know I've made the review less simple so I'm okay with that. Though maybe it’s not too much to ask letting this get a second look before that.

File: packages/block-editor/src/components/block-tools/use-show-block-tools.js (hunk 2 above)
Comment (Mamaduka) [reply packages/block-editor/src/components/block-tools/use-show-block-tools.js:32]: Yeah, it's just safe guard - https://github.com/WordPress/gutenberg/pull/58979#discussion_r1502978699.

**Review by scruffian — APPROVED** [review]
LGTM. Thanks for the fix.

**Review by Mamaduka — APPROVED** [review]
The fix tests well for me ✅

Note: I noticed that the undoing pattern insertion is somewhat broken. @jeryj, do you know it's being tracked somewhere?

## Screencast

https://github.com/user-attachments/assets/ba2dad91-d048-4ff7-8757-6c01e3ff8df3

**Comment by stokesman** [comment]
> I noticed that the undoing pattern insertion is somewhat broken. @jeryj, do you know it's being tracked somewhere?

Aki had made #63479 regarding the undo, maybe it was closed prematurely or this problem is distinct.

**Comment by stokesman** [comment]
Thanks to everyone who tested and reviewed. Especially Jerry, whose apt scrutiny of the unnecessary changes made great starting points to explain them.
