### PR TITLE
Fix/title encoding bug

### LINKED ISSUE #38362: Gutenberg: Post Titles with Apostrophe Turn to `&#039;` When Published
#### Steps to reproduce
1. Create a new post or page on a non-AT WordPress.com site
2. Add a title that includes an apostrophe
3. Publish the post or page

#### What I expected
That the title of the post/page would display the apostrophe in the post title in the editor

#### What happened instead
The apostrophe in the post title was turned into the `&#039;` code

#### Browser / OS version
Firefox 71/Google Chrome 78.0.3904.108
macOS 10.15.2

#### Screenshot / Video
[GIF of Issue](https://d.pr/i/JqpUt8)

#### Context / Source
User report (#17239929-hc)

### PR DESCRIPTION
**Pull request by glendaviesnz**
## Description

The encoding that was recently added to the post title block works fine on standalone wp installs, but not on wpcom - https://github.com/Automattic/wp-calypso/issues/38362  - this is because for some reason wpcom adds leading zeros to the html entity codes, and lodash unescape does not account for this.

Switching from the lodash unescape to WordPress decodeEntities resolves the issue without causing any problems that I can see.

## How has this been tested?
Tested manually, and also added an additional unit test to make sure decodeEntities accounts for leading zeros.

## Screenshots

Before:

encode-before

After:

encode-after

## Types of changes

Change string decoding method

Fixes https://github.com/Automattic/wp-calypso/issues/38362

### CODE REVIEW

File: packages/editor/src/components/post-title/index.js [hunk 1]
```diff
@@ -123,7 +123,7 @@ class PostTitle extends Component {
 							<Textarea
 								id={ `post-title-${ instanceId }` }
 								className="editor-post-title__input"
-								value={ unescape( title ) }
+								value={ decodeEntities( title ) }
```
Comment (gwwar) [inline packages/editor/src/components/post-title/index.js]: What are the differences in implementation? Can we add a unit test to catch the broken case here?

Comment (glendaviesnz) [reply packages/editor/src/components/post-title/index.js]: Some level of filtering on wpcom converts  `#39;` to `#039;`. lodash `unescape` only looks for an exact match of `#39;`. WP `decodeEntities` on the other hand, doesn't search for specific entity strings, it just throws everything into a temporary text field in the dom and then extracts, so relies entirely on the browsers own encoding/decoding, which handles both `#39;` and `#039;`

Comment (glendaviesnz) [reply packages/editor/src/components/post-title/index.js]: Added an additional test to cover this variation in entity codes.

Comment (aduth) [inline packages/editor/src/components/post-title/index.js]: I wonder a bit about the corresponding `escape` which happens in the `onUpdate` dispatch below. In truth, I'm not actually sure why it's needed at all. But at least previously, there was a duality between `unescape` and `escape` which is no longer guaranteed.

**Review by aduth — APPROVED** [review]

File: packages/editor/src/components/post-title/index.js (hunk 1 above)
Comment (gwwar) [reply packages/editor/src/components/post-title/index.js]: Hmm I wonder why we added only decodeEntities in https://github.com/WordPress/gutenberg/pull/7977. I think an upstream patch to lodash (as including leading zeros is okay), and dependency update would work too, but I think I'm missing some context here.

**Review by gwwar — APPROVED** [review]
I think changes here make sense @glendaviesnz 👍

File: packages/editor/src/components/post-title/index.js (hunk 1 above)
Comment (glendaviesnz) [reply packages/editor/src/components/post-title/index.js]: >I wonder a bit about the corresponding escape

Yes, it would be good to update that to an internal encoding method once one is available.
