### PR TITLE
wp-build: Do not remove Core's default script modules registration

### LINKED ISSUE #75704: WP Build: Page crashes when Gutenberg is not activated
### Description

When a plugin uses `@wordpress/build` on a site where Gutenberg is not installed, the pages fail to load with a console error: `Uncaught (in promise) TypeError: The specifier “@wordpress/a11y” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.`

### Step-by-step reproduction instructions

1. Install a plugin that uses wp-build and registers a page (https://github.com/dhasilva/minimal-wp-build-test is a minimal plugin made to test this).
2. Go to its page (Tools → Minimal WP-Build Test with the test plugin above)
3. Check that it loads correctly if Gutenberg is installed, but fails to load if Gutenberg is not activated

### Screenshots, screen recording, code snippet

Image

### Environment info

"@wordpress/build": "0.7.0"
No Gutenberg installed

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by dhasilva**
## What?

Closes #75704

It deletes the removal of the default script modules registration

## Why?

Wp-build removes WordPress Core's built-in function that registers default script modules (like @wordpress/a11y), and it assumes that Gutenberg is installed and activated to replace it with its own modules, but if Gutenberg is not activated this replacement never happens, and the import of `@wordpress/a11y` fails, as the specifier is not mapped.

## How?

By deleting the removal entirely, as it is not necessary.

## Testing Instructions

1 - Clone https://github.com/dhasilva/minimal-wp-build-test locally
2 - `pnpm install` and build the test plugin with `pnpm run build`
3 - Go to Tools > Minimal WP-Build Test
4 - Check that you see the error in the linked issue
5 - Symlink wp-build to the plugin's dependencies:
```
cd <your-wp-plugins-folder>/minimal-wp-build-test
rm -rf node_modules/@wordpress/build
ln -s <your-gutenberg-folder>/packages/wp-build node_modules/@wordpress/build
```
6 - Rebuild the test plugin: `pnpm run build`
7 - Check `/build/modules.php`, it should have the added `if` block.
8 - Go to Tools > Minimal WP-Build Test again
9 - Check that the page loads
10 - Activate Gutenberg
11 Go to Tools > Minimal WP-Build Test again
12 - Check that the page loads

## Screenshots or screencast 

|Before|After|
|-|-|
|Screenshot from 2026-02-18 20-26-27|Screenshot from 2026-02-18 20-37-43|

### CODE REVIEW

**Comment by dhasilva** [comment]
@youknowriad Is this the correct approach? Currently we are bypassing this issue in Jetpack with [this](https://github.com/Automattic/jetpack/pull/47035/changes#diff-41747e0a7ba674182bd30bae648930ec220c2d48f26970b783234a57cc2525d7R36-R42).

File: packages/wp-build/templates/module-registration.php.template [hunk 1]
```diff
@@ -42,5 +42,9 @@ if ( ! function_exists( '{{PREFIX}}_register_script_modules' ) ) {
 	}
 
 	add_action( 'wp_default_scripts', '{{PREFIX}}_register_script_modules' );
-	remove_action( 'wp_default_scripts', 'wp_default_script_modules' );
+
+	if ( defined( 'IS_GUTENBERG_PLUGIN' ) && IS_GUTENBERG_PLUGIN ) {
+		// Remove Core's default script modules registration so Gutenberg can replace them with its own.
+		remove_action( 'wp_default_scripts', 'wp_default_script_modules' );
```
Comment (youknowriad) [inline packages/wp-build/templates/module-registration.php.template]: I actually wonder why this is needed at all? Can we just remove this code from here (or if it's really required in Gutenberg, we should move it to client-assets.php file since it's gutenberg specific.

Comment (dhasilva) [reply packages/wp-build/templates/module-registration.php.template]: I assumed it was, but it seems it is not. Testing with Gutenberg installed works as long as [this other fix](https://github.com/WordPress/gutenberg/pull/75650) is applied, so at first glance there seems to be no regression.

Comment (dhasilva) [reply packages/wp-build/templates/module-registration.php.template]: Updated the PR to remove it.

**Review by youknowriad — APPROVED** [review]
LGTM but I guess the PR is blocked by the failures on trunk for now.

**Comment by dhasilva** [comment]
Rebased, tests are passing now.

**Comment by scruffian** [comment]
I think this caused an issue when we want to change modules in Gutenberg: https://github.com/WordPress/gutenberg/pull/75909
