### PR TITLE
onWriting Flow: Remove the provisional block behavior

### LINKED ISSUE #8678: Writing Flow: Block merges twice on empty intermediary paragraphs
**To Reproduce**

1. Navigate to Posts > Add New
2. Click writing prompt
3. Press Enter twice
4. Press Backspace
5. Observe two paragraphs are deleted, and caret is placed back to first paragraph

**Expected behavior**

Only one paragraph is removed, leaving user in the second empty paragraph.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #8678

I admit I never been fan of the provisional block behavior: The fact to remove an empty paragraph right upon its creation if it's unselected though I understood it was useful when it was too easy to create in between paragraphs which is not the case anymore.

I think it's better to remove it to avoid any unwanted side effect it can create like #8678. Thoughts @jasmussen @aduth 

**Testing instructions**

Repeat instructions in #8678 and check that it works properly.

### CODE REVIEW

File: packages/editor/src/store/selectors.js [hunk 1]
```diff
@@ -1749,18 +1749,6 @@ export function isPublishingPost( state ) {
...
 
-/**
- * Returns the provisional block client ID, or null if there is no provisional
- * block.
- *
- * @param {Object} state Editor state.
- *
- * @return {?string} Provisional block client ID, if set.
- */
-export function getProvisionalBlockClientId( state ) {
```
Comment (youknowriad) [inline packages/editor/src/store/selectors.js]: I hesitated to keep this selector fo BC but the probability for it to be used outside Gutenberg is 0 IMO

**Comment by youknowriad** [comment]
I want my badge @tofumatt 😄

**Comment by aduth** [comment]
Thoughts ahead of my review: I agree this has added complexity and therefore caused fragility. It's interesting to consider this as the cause for #8678.

Usage-wise, I'm trying to remember back to #5417 / #5396 and the issues this was meant to address:

- The inserter line was certainly easier to hit at the time (it spanned the full content width and was quite large).
- I guess we don't show the sibling inserter if there's already a blank new paragraph between two other blocks? I recall one of the issues being that you could easily add many empty paragraphs and the placeholders would be visually ugly.
- In retrospect, the auto-deletion seems quite extreme, though it is a bit strange to see the writing placeholder "Add text or type / to add content" when clicking sibling inserter and then to another block; perhaps the best avenue here is to limit the effect of the placeholder. Or maybe it's completely fine as it is.

**Comment by aduth** [comment]
There's still one instance of the phrase "provisional" in the codebase in `writing-flow.test.js`. Unsure if we want to abandon the terminology altogether. In the test, I believe it's more accurately referring to an unmodified default block.

https://github.com/WordPress/gutenberg/blob/ee6060f97fc738295f791d6a0b7633db549b39d0/test/e2e/specs/writing-flow.test.js#L151-L153

File: packages/editor/src/store/selectors.js (hunk 1 above)
Comment (aduth) [reply packages/editor/src/store/selectors.js]: Alternatively, we could keep the function, and have it return `null` (the default reducer state) so it would at least not throw an error and be as close as possible to a real value with the state no longer existing.

But I'd probably agree it's unlikely that this is used.

**Review by aduth — APPROVED** [review]
