### PR TITLE
Ensure contributors can create tags and manage categories

### LINKED ISSUE #5879: Category, tag, and taxonomy controls don't respect the correct capabilities
## Issue Overview
If a user has the `assign_terms` capability for a given taxonomy, but not the `manage_terms` capability for the taxonomy, they are unable to assign terms.

## Steps to Reproduce (for bugs)
1. Create a custom taxonomy that uses the following capabilities array, or filter the capabilities for Categories or Tags to do the same:

	```php
	'capabilities' => array(
		'assign_terms' => 'edit_posts',
		'delete_terms' => 'do_not_allow',
		'edit_terms'   => 'do_not_allow',
		'manage_terms' => 'do_not_allow',
	),

	```
2. Create a new post and note that the taxonomy is not shown in the editor, despite the user having the `edit_posts` capability and therefore being allowed to assign terms.

## Expected Behavior
The user should be able to assign terms in the taxonomy.

## Current Behavior
The user cannot assign terms in the taxonomy, not see the currently assigned terms.

## Possible Solution
Respect the user's capabilities for `assign_terms`.

Note that there is quite a lot of logic in the Categories and Tags meta boxes on WordPress' current editing screen, all of which needs to be replicated in Gutenberg in order to respect the underlying capabilities API.

See:
* `post_tags_meta_box()`
* `post_categories_meta_box()`

## Related Issues and/or PRs
* #4787
* #2545

### PR DESCRIPTION
**Pull request by danielbachhuber**
## Description

Ensures contributors and authors can create tags and manage categories. More specifically, this pull request:

* Incorporates REST API capability changes [identified in this Trac ticket](https://core.trac.wordpress.org/ticket/44096). Doing so required a series of amazing hacks.
* Migrates taxonomy data to `core-data`.
* Uses `wp:action-*` targetSchema to expose whether or not the current user can create or assign terms for each taxonomy.

See #6361
Fixes #5879

## How has this been tested?

When signed in as a contributor, you should be able to create tags and assign categories:

image

When signed in as an editor, you should be able to also create new categories:

image

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: core-data/actions.js [hunk 1]
```diff
@@ -71,6 +71,20 @@ export function receiveEntityRecords( kind, name, records ) {
...
+ * Returns an action object used in signalling that taxonomies have been received.
+ *
+ * @param {Array} taxonomies Taxonomies received.
+ *
+ * @return {Object} Action object.
+ */
+export function receiveTaxonomies( taxonomies ) {
+	return {
+		type: 'RECEIVE_TAXONOMIES',
+		taxonomies: taxonomies,
```
Comment (pento) [inline core-data/actions.js]: This could just be `taxonomies`, instead of `taxonomies: taxonomies`.

File: editor/components/post-taxonomies/flat-term-selector.js [hunk 2]
```diff
@@ -174,6 +174,10 @@ class FlatTermSelector extends Component {
 		const termRemovedLabel = sprintf( _x( '%s removed', 'term' ), singularName );
 		const removeTermLabel = sprintf( _x( 'Remove %s', 'term' ), singularName );
 
+		if ( ! hasAssignAction ) {
```
Comment (pento) [inline editor/components/post-taxonomies/flat-term-selector.js]: It's a tiny micro-optimisation, but this check could happen immediately after `hasAssignAction` is declared, to avoid the processing needed to declare all the other local variables.

File: editor/components/post-taxonomies/hierarchical-term-selector.js [hunk 3]
```diff
@@ -242,10 +242,14 @@ class HierarchicalTermSelector extends Component {
 		const newTermSubmitLabel = newTermButtonLabel;
 		const inputId = `editor-post-taxonomies__hierarchical-terms-input-${ instanceId }`;
 
+		if ( ! hasAssignAction ) {
```
Comment (pento) [inline editor/components/post-taxonomies/hierarchical-term-selector.js]: Same as in `flat-term-selector.js`, this check could happen earlier.

File: lib/rest-api.php [hunk 4]
```diff
@@ -637,3 +684,115 @@ function gutenberg_filter_user_query_arguments( $prepared_args, $request ) {
...
+			}
+		}
+		// Handle POST /wp/v2/tags (and non-hiearchical taxonomies) when user
+		// can assign_terms but not manage terms. Users should be able to create
+		// terms.
+		if ( 'rest_cannot_create' === $response->get_error_code()
+			&& is_array( $handler['permission_callback'] )
+			&& is_a( $handler['permission_callback'][0], 'WP_REST_Terms_Controller' ) ) {
+			// 'taxonomy' is a protected attribute, and PHP 5.2 doesn't support
+			// ReflectionProperty->setAccessible(), so we need to get really dirty.
```
Comment (pento) [inline lib/rest-api.php]: I'm not going to lie, I'm impressed with this hack.

But, can't you get the value of `::taxonomy` from the data returned by `::get_item_schema()`?

**Review by pento — COMMENTED** [review]
I can see how it was an interesting challenge to implement the PHP side of things: I left one comment, but I'm generally fine with it being super hacky in Gutenberg, as the actual core changes are fairly straightforward.

I'm not sure how I feel about all the additional processing happening in `PostTaxonomies` now. Maybe it'll look at little less like a wall of text once #6655 is fixed.

File: core-data/reducer.js [hunk 5]
```diff
@@ -73,6 +73,23 @@ export function users( state = { byId: {}, queries: {} }, action ) {
...
+ * @return {Object} Updated state.
+ */
+export function taxonomies( state = [], action ) {
+	switch ( action.type ) {
+		case 'RECEIVE_TAXONOMIES':
+			return action.taxonomies;
+	}
+
+	return state;
+}
```
Comment (youknowriad) [inline core-data/reducer.js]: Instead of adding a new reducer/selectors/actions, we could just leverage the new entities abstraction to automatically generate those. https://github.com/WordPress/gutenberg/blob/master/core-data/entities.js#L6

Currently, the entities only support fetching by id `getEntityRecord` but we should definitely introduce a findAll/findQuery as well `getEntityRecords( state, kind, entity, query )`

If you think it's too much work, it's fine to do it separately.

File: editor/components/post-taxonomies/index.js [hunk 6]
```diff
@@ -17,18 +16,23 @@ import './style.scss';
...
-export function PostTaxonomies( { postType, taxonomies, taxonomyWrapper = identity } ) {
-	const availableTaxonomies = filter( taxonomies.data, ( taxonomy ) => includes( taxonomy.types, postType ) );
+export function PostTaxonomies( { post, postType, taxonomies, taxonomyWrapper = identity } ) {
+	const availableTaxonomies = filter( taxonomies, ( taxonomy ) => includes( taxonomy.types, postType ) );
 	const visibleTaxonomies = filter( availableTaxonomies, ( taxonomy ) => taxonomy.visibility.show_ui );
 	return visibleTaxonomies.map( ( taxonomy ) => {
 		const TaxonomyComponent = taxonomy.hierarchical ? HierarchicalTermSelector : FlatTermSelector;
+		const restBase = taxonomy.rest_base;
+		const hasCreateAction = get( post, [ '_links', 'wp:action-create-' + restBase ], false );
+		const hasAssignAction = get( post, [ '_links', 'wp:action-assign-' + restBase ], false );
```
Comment (youknowriad) [inline editor/components/post-taxonomies/index.js]: Cane we move these two variables inside  `withSelect` instead?. Boolean change less often than a objects which avoid rerenders.

Comment (youknowriad) [reply editor/components/post-taxonomies/index.js]: Oh I guess it's per taxonomy, This is for me an indication that these checks should be moved to the `TaxonomyComponent` instead.

Comment (danielbachhuber) [reply editor/components/post-taxonomies/index.js]: Moved in 04aa6e52d

File: editor/components/post-taxonomies/hierarchical-term-selector.js (hunk 3 above)
Comment (danielbachhuber) [reply editor/components/post-taxonomies/hierarchical-term-selector.js]: ac803ad85dc5dfd2cbe70a92f5fb09cf2483deb7

File: editor/components/post-taxonomies/flat-term-selector.js (hunk 2 above)
Comment (danielbachhuber) [reply editor/components/post-taxonomies/flat-term-selector.js]: ac803ad85dc5dfd2cbe70a92f5fb09cf2483deb7

File: core-data/actions.js (hunk 1 above)
Comment (danielbachhuber) [reply core-data/actions.js]: 9a96bed94e2f07b53ac409e0a3d01acf989c4e19

File: lib/rest-api.php (hunk 4 above)
Comment (danielbachhuber) [reply lib/rest-api.php]: > But, can't you get the value of `::taxonomy` from the data returned by `::get_item_schema()`?

You can, in fact. I'd forgotten about that. 0c9c3294347220707e73979ad2d3425b4b39c044

File: core-data/reducer.js (hunk 5 above)
Comment (danielbachhuber) [reply core-data/reducer.js]: I'd like to handle separately (and also include more tests within `core-data`). I've filed an issue #6780

**Comment by danielbachhuber** [comment]
@youknowriad @pento Good to go now.

**Review by youknowriad — COMMENTED** [review]
LGTM  for the JS part of things. I'll defer to @pento for the endpoint updates.

**Comment by tofumatt** [comment]
FYI I'm away on holiday for the next week or so; feel free to un-assign me for review and have someone else take a look. Otherwise I can have a look come May 28-ish...

**Review by pento — APPROVED** [review]
Noice. Let's do it.

File: editor/components/post-taxonomies/flat-term-selector.js [hunk 7]
```diff
@@ -202,7 +207,10 @@ export default compose(
 		};
 	} ),
 	withSelect( ( select, ownProps ) => {
+		const { getCurrentPost } = select( 'core/editor' );
 		return {
+			hasCreateAction: get( getCurrentPost(), [ '_links', 'wp:action-create-' + ownProps.restBase ], false ),
```
Comment (aduth) [inline editor/components/post-taxonomies/flat-term-selector.js]: Should this logic be its own selector? Something like `canUserForPost( actionType, restBase )` ?

Minor: `getCurrentPost` as implemented is trivial, though nothing guarantees it is, in which case assigning a single variable of `const currentPost = getCurrentPost()` to use across the two merged props would be marginally more performant.

Comment (danielbachhuber) [reply editor/components/post-taxonomies/flat-term-selector.js]: > Should this logic be its own selector? Something like `canUserForPost( actionType, restBase )` ?

See #6655
