### PR TITLE
File block: Handle drag-and-drop errors

### LINKED ISSUE #8025: Blocks: File block doesn't handle unallowed file types
**Describe the bug**

The Files block fails to handle the case where a user drops a file type not allowed by the server. It presents the loading display forever. If the user then proceeds to save the post and reload the page, the block fails with an unhandled error.

**To Reproduce**

1. Navigate to Posts > Add New
2. Drag an unsupported file from your computer to the editor (maybe `.exe`)
3. Observe that a file block is inserted (since it handles any files dropped), but that it pulses forever
4. Save the post
5. Reload the editor
6. Observe that the File block has encountered an error

**Expected behavior**

- The Files block should not attempt to handle unsupported file types
- Insertion point shouldn't be offered
- Even if it tried to handle, if the upload failed for any reason, this should at least be communicated to the user
- There should be no block errors when reloading the saved post

**Screenshots**

Uploading (indefinitely):

loading

Error:

image

Error text:

>[mediaupload.js:83 Uncaught TypeError: Cannot read property 'type' of undefined](https://github.com/WordPress/gutenberg/blob/b06a33569a2b860110cb8d3f113ccf6c2b36e492/utils/mediaupload.js#L83)
>    at mediaupload.js:83
>    at Array.forEach (<anonymous>)
>    at mediaUpload (mediaupload.js:82)
>    at editorMediaUpload (index.js:33)
>    at FileEdit.componentDidMount (edit.js:58)
>    at commitLifeCycles (react-dom.24169eaf.js:14939)
>    at commitAllLifeCycles (react-dom.24169eaf.js:16040)
>    at HTMLUnknownElement.callCallback (react-dom.24169eaf.js:140)
>    at Object.invokeGuardedCallbackDev (react-dom.24169eaf.js:178)
>    at invokeGuardedCallback (react-dom.24169eaf.js:227)

**Desktop (please complete the following information):**

 - OS: macOS High Sierra 10.13.6 (17G65)
 - Browser: Chrome Version 67.0.3396.99 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by noisysocks**
## Description
Fixes #8025.

Handle any errors that occur when a File block is created via a `files` transform. That is, when a file is drag-and-dropped into the editor.

## How has this been tested?
1. Drag an unsupported file (e.g. `.js`, `.diff`, `.json`, `.exe`) into the editor
2. Insert a File block and drag an unsupported file onto the block
3. Drag a supported file (e.g. `.zip`, `.pdf`) into the editor
4. Insert a File block and drag a supported file onto the block

## Screenshots 
drag-and-drop

### CODE REVIEW

File: core-blocks/file/edit.js [hunk 1]
```diff
@@ -59,6 +61,10 @@ class FileEdit extends Component {
 				allowedType: '*',
 				filesList: [ file ],
 				onFileChange: ( [ media ] ) => this.onSelectFile( media ),
+				onError: ( message ) => {
+					this.setState( { hasError: true } );
```
Comment (noisysocks) [inline core-blocks/file/edit.js]: I had to use local state here because we don't support calling `this.props.setAttributes()` in `componentDidMount`.

**Review by talldan — APPROVED** [review]
Looks good. 👍 

I did wonder if `isMatch` could be used to disallow the transform, but I think showing an appropriate error and the behaviour being similar to when using the MediaPlaceholder are benefits to this approach.

**Comment by noisysocks** [comment]
Good spotting! There's a whole lot of bugs that exist because we store blob URLs in blocks attributes. We definitely should move away from doing this. https://github.com/WordPress/gutenberg/issues/8119 was created as an umbrella issue for this.

**Comment by noisysocks** [comment]
> I did wonder if isMatch could be used to disallow the transform, but I think showing an appropriate error and the behaviour being similar to when using the MediaPlaceholder are benefits to this approach.

Yeah, totally. I experimented with not allowing the drag-and-drop at all if it's an invalid transform, but decided against it because it makes it feel like the browser is not responsive.
