### PR TITLE
Block Editor: Skip focusTabbable if no active element

### LINKED ISSUE #21276: IE11: browser crashes on pressing Enter to switch to edit mode
**Describe the bug**

On IE11, with a block selected and with the editor in select mode, pressing Enter to switch to edit mode causes the editor to crash with the following error message:

```
TypeError: Unable to get property 'closest' of undefined or null reference
   at vi (http://isabel:8888/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=4af3ae3fe13f697ebe49daa5a278cc59:49:122078)
   at Anonymous function (http://isabel:8888/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=4af3ae3fe13f697ebe49daa5a278cc59:49:142265)
   at Anonymous function (http://isabel:8888/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=4af3ae3fe13f697ebe49daa5a278cc59:49:142254)
   at commitHookEffectList (http://isabel:8888/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:20124:9)
   at commitPassiveHookEffects (http://isabel:8888/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:20154:11)
   at callCallback (http://isabel:8888/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:341:9)
```
The console also reports:

```
The above error occurred in the <ForwardRef> component:
    in ForwardRef (created by ForwardRef)
    in ForwardRef
    in Unknown (created by t)
    in t (created by WithInstanceId(t))
    in WithInstanceId(t) (created by WithSpokenMessages(WithInstanceId(t)))
    in WithSpokenMessages(WithInstanceId(t))
    in Unknown (created by Context.Consumer)
    in WithBlockEditContext(Component) (created by t)
    in t
    in Unknown (created by WithSafeTimeout(Component))
    in WithSafeTimeout(Component) (created by ForwardRef)
    in ForwardRef (created by ForwardRef(e))
    in ForwardRef(e)
    in Unknown
    in Unknown (created by WithToolbarControls(Component))
    in WithToolbarControls(Component) (created by WithInspectorControl(WithToolbarControls(Component)))
    in WithInspectorControl(WithToolbarControls(Component)) (created by WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))))
    in WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))) (created by WithToolba
```

**To reproduce**
1. On IE11, navigate to a post in the editor.
2. With a block selected, press Esc to switch select mode, then press Enter to switch back to edit mode
3. See error

**Expected behavior**

Expected all keyboard shortcuts to work correctly.

### PR DESCRIPTION
**Pull request by aduth**
Fixes #21276

This pull request seeks to resolve an error which occurs in Internet Explorer when pressing <kbd>Enter</kbd> whilst a block is selected in Select interaction mode.

For full debugging details, see comment at https://github.com/WordPress/gutenberg/issues/21276#issuecomment-608039276 .

**Implementation notes:**

The changes as proposed follow the second of the two proposed fixes from https://github.com/WordPress/gutenberg/issues/21276#issuecomment-608039276 .

**Testing Instructions:**

Repeat Steps to Reproduce from #21276, verifying that no crash occurs in Internet Explorer.

### CODE REVIEW

**Comment by youknowriad** [comment]
I also fixed a recent issue on `focusTabbable` recently. While doing so I was thinking that actually `focusTabbable` might not be needed anymore (or at least the logic to find the textual elements) as we refactor all textual blocks to use the light block DOM wrapper (it might still be needed for BC)

File: packages/block-editor/src/components/block-list/block-wrapper.js [hunk 1]
```diff
@@ -98,6 +98,10 @@ const BlockComponent = forwardRef(
 		 * When a block becomes selected, transition focus to an inner tabbable.
 		 */
 		const focusTabbable = () => {
+			if ( ! document.activeElement ) {
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-list/block-wrapper.js:101]: I'm not sure I understand this change, if we select a block, we still want it to be focused regardless of whether there was an activeElement before?

Comment (aduth) [reply packages/block-editor/src/components/block-list/block-wrapper.js:101]: That's a good point. I think I was misled by the early `return;` of the condition following this one. Maybe instead, it should be this?

```js
if (
	document.activeElement && isInsideRootBlock( wrapper.current, document.activeElement )
) {
	return;
}
```

Comment (youknowriad) [reply packages/block-editor/src/components/block-list/block-wrapper.js:101]: makes sense yes

Comment (aduth) [reply packages/block-editor/src/components/block-list/block-wrapper.js]: cc607cf53a

**Review by youknowriad — APPROVED** [review]
Code looks good. I'm not in capacity to test this in IE11 but I'm confident about the changes.

**Comment by aduth** [comment]
> I also fixed a recent issue on `focusTabbable` recently. While doing so I was thinking that actually `focusTabbable` might not be needed anymore (or at least the logic to find the textual elements) as we refactor all textual blocks to use the light block DOM wrapper (it might still be needed for BC)

Would that depend on the block, based on what its root element is? A quote block, for example, would have multiple focusable fields, none of which are the root element (`<p>` or `<cite>` within `<blockquote>`). Won't that still need `focusTabbable`?

In any case, as you mention, since there always will third-party blocks relying on the current behavior, I think it will need to stick around in one form or another.

**Comment by youknowriad** [comment]
@aduth Right :) I thought about whether using inner blocks for Quote would fix but it's not even the case, we might even need to surface it as an API (opt-in or opt-out) as I can image that some container blocks would want to focus their first textual inner blocks in some cases.
