### PR TITLE
Navigation: Try removing absorb toolbar prop.

### LINKED ISSUE #36538: Navigation Block: align block toolbar closer to currently selected nested block
## What problem does this address?

Seems a regression happened at some point as the block toolbar now doesn't align with the currently block being edited. Here's a quick video to demonstrate:

https://user-images.githubusercontent.com/26996883/142045018-9041960b-11e6-4d09-b88c-583a519bffd0.mov

## What is your proposed solution?

Have the toolbar align with the current nested block being edited within the nav block. cc @talldan

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

Fixes #36538, mitigates #36977 and #36701. But the primary reason for creating this PR was #36701. Props to @getdave for [pointing me in the right direction](https://github.com/WordPress/gutenberg/issues/36977#issuecomment-982426491).

The absorb toolbar prop exists for the parent block to absorb the block toolbar of children. This is useful for some blocks that feature very compact or intricate child blocks, or for some use cases such as a sketching block where child blocks are blocks you insert and rotate inside as innerblocks. 

It was created for the older version of the navigation block, where the block UI was much heavier to the point that borders were overlaying and creating confusion on their own. With the simpler handling of borders on focus, this is less of a concern with the navigation block than it was at the time, and on the flipside, the change comes with its own tradeoffs:

- Absorbing toolbar keeps the block toolbar from covering content such as preceding submenu items, and it keeps the mover control still as you move items around. But it can also be spatially far removed from the menu item you're actually editing.
- Not absorbing the toolbar can cover preceding content, and the mover control moves with the block. But it is in spatially in perfect context of the menu item.

Due to the balance tipping, I'm currently leaning back towards not absorbing the toolbar, in part also because of the two important bugs that the change mitigates. I also think we could keep a semblance of the absorb behavior, for example absorb the toolbar only for submenu blocks. 

Before:

before

After:

after

## How has this been tested?

Insert a navigation block and observe the toolbar being in spatial context of the child block selected. 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by getdave — COMMENTED** [review]
Thanks for pursuing the best possible UX ✨ 

I'd love to see a screenshot before/after showing the behaviour on **_submenus_**. 

It looks great when there's only a _single_ level but how does that work when you are trying to edit a Nav item several levels deep?

The original purpose of adding the capture toolbars functionality was to improve UX for nested items so we should test that scenario heavily.

**Comment by jasmussen** [comment]
Absolutely, sorry for not including that. Here's building submenus with the toolbar absorbed:

before

_Note that the behavior of the appender requiring you to select the parent first is separate, and being looked at in #36720._

Here's with the toolbar not absorbed:

after

**Comment by jasmussen** [comment]
I pushed a tweak to capture the toolbars for submenus. I think it works incredibly well:
capture submenus

It feels like the toolbar is exactly where it should be for that use case. What do you think?

Note that this means it no longer mitigates #36977, but it looks like the "moving toolbars below" change did not work as well as we had hoped anyway.

File: packages/block-library/src/navigation-submenu/edit.js [hunk 1]
```diff
@@ -508,6 +508,12 @@ export default function NavigationSubmenuEdit( {
 			allowedBlocks: ALLOWED_BLOCKS,
 			__experimentalDefaultBlock: DEFAULT_BLOCK,
 			__experimentalDirectInsert: true,
+
+			// Ensure block toolbar is not too far removed from item
+			// being edited when in vertical mode.
+			// see: https://github.com/WordPress/gutenberg/pull/34615.
+			__experimentalCaptureToolbars: true,
```
Comment (getdave) [inline packages/block-library/src/navigation-submenu/edit.js]:
```suggestion
			// Ensure block toolbar is not too far removed from item
			// being edited.
			// see: https://github.com/WordPress/gutenberg/pull/34615.
			__experimentalCaptureToolbars: true,
```

**Review by getdave — APPROVED** [review]
To me this seems logical. Allow the toolbar to move to individual items at the topmost level, but fix it to the top level parent when editing submenus.

My only other question is what happens when you nest submenus? Does it still stick to the topmost parent?

Thanks for working on this.

PS: is this a "bug fix" we want to backport or an enhancement?

**Comment by jasmussen** [comment]
> My only other question is what happens when you nest submenus? Does it still stick to the topmost parent?

The toolbar still gets captured in the topmost version. I know the GIF goes long, but it shows that use case towards the end, and I think it works rather well honestly.

Does it need to land for 5.9? I don't know. I think it's a good and harmless enhancement, but it also fixes #36538, which I honestly feel is a buggy experience. But I also don't have a strong opinion. Taking the long view to where we want to be, this will be a good fix. Will the experience in the mean time be compromised without it? Maybe not, it's always a sum of things. Happy to defer!

Thank you for the review and code suggestion!

**Comment by getdave** [comment]
I say we land it as a "bugfix". The rationale you present is strong. We should make sure the PR description clearly describes which bug it "fixes" though.

Also...sorry for not watching the GIF towards the end 😅
