### PR TITLE
switch hex-rgb to polished parseToRgb

### LINKED ISSUE #18719: Editor broken on IE11
**Describe the bug**

Gutenberg is not rendering at all on IE11. I traced the breakage to [this commit](https://github.com/WordPress/gutenberg/commit/87c44f7332b5cb6702b6684fb39b50cae250c4b6); the error messages point to the problem being with the newly-added `hex-rgb` package using template literals.

Screen Shot 2019-11-25 at 12 25 05 pm

**To reproduce**
1. Using IE, navigate to "new post" page.
2. Verify that page remains blank after loading, and errors appear in the browser console.

**Expected behavior**
Expected the post editor to render normally.

**Desktop (please complete the following information):**
 - OS: Windows 7 - 10
 - Browser: IE11
 - Version: all versions

### PR DESCRIPTION
**Pull request by jameslnewell**
## Description

Temporary fix for the issue discussed in https://github.com/WordPress/gutenberg/pull/17963#discussion_r349374328

Replaced the `hex-rgb` package+function for `polished`'s `parseToRgb` function since the `hex-rgb` package doesn't provide any transpiled modules.

[Polished is 10kb gziped but highly treeshakable.](https://bundlephobia.com/result?p=polished@3.4.2)

## How has this been tested?

Ran unit tests, checked the storybooks.

## Screenshots 
No visual changes.

## Types of changes

Bug fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

closes #18719

### CODE REVIEW

**Comment by aduth** [comment]
One downside here is that it's about a 1400% size increase from `hex-rgb` ([0.7kb](https://bundlephobia.com/result?p=hex-rgb@4.1.0) to [10.6kb](https://bundlephobia.com/result?p=polished@3.4.2)).

I can plan to look a little closer in my morning. It'd be good to have this resolved in time for next week's release, so if it comes down to it, we can live with the larger bundle until another solution presents itself.

**Comment by jameslnewell** [comment]
Yeah treeshaking isn't supported its a big hit. I can see a few alternatives but they're only 50% better:

- `color-convert` - [5kb, no treeshaking](https://bundlephobia.com/result?p=color-convert@2.0.1), updated 3 months ago
- `tinycolor2` - [5kb, no treeshaking](https://bundlephobia.com/result?p=tinycolor2@1.4.1), updated 3 years ago

File: packages/components/src/utils/colors.js [hunk 1]
```diff
@@ -2,7 +2,7 @@
  * External dependencies
  */
 import { get } from 'lodash';
-import hexRgb from 'hex-rgb';
+import { parseToRgb } from 'polished';
```
Comment (youknowriad) [inline packages/components/src/utils/colors.js]: I think we already have tinycolor2 in our bundles. We could use it instead right?

Comment (ItsJonQ) [reply packages/components/src/utils/colors.js]: @jameslnewell Ah, you folks are so fast! You jumped on this before I could :)
I was going to suggest using `tinycolor2` since it was already there. My apologies for not realizing that when I submitted my original PR.

Thanks for the heads up @youknowriad + @aduth !

**Comment by aduth** [comment]
>Polished is 10kb gziped but highly treeshakable.

The package is tree-shakeable, yes, but the 10kb number was the specific tree-shooken `parseToRgb` export (the full package is 34kb gzipped).

As mentioned, since we're already using `tinycolor2`, I think that's the way to go. I'll push up a change here shortly to help get the ball rolling in time for Monday's RC.

**Review by aduth — APPROVED** [review]
Assuming latest changes look good to you, I think we can merge this 👍
