### PR TITLE
Block: fix html mode for non light blocks

### LINKED ISSUE #23511: Table can't change to edit visually after selecting Edit as HTML and clicking out of the table
**Describe the bug**
After selecting `Edit as HTML` in `Table` block and clicking outside, you can't see the button with the options if clicking back in.

This has a similar effect on `Buttons` block, that errors when clicking out of the block, after having selected `Edit as HTML`.

This probably has to do with blocks that utilize `RichText` inside and if that's the case more blocks are affected by this.

**To reproduce**
1. Go to a post/page
2. Add a `Table` block
3. Select `Edit as HTML`
4. See that the options block is visible
5. Click outside and then back in the `Table`
6. The options block is not there..

For the `Buttons` block just select `Edit as HTML` and click outside

**Expected behavior**
The options button after `Edit as HTML` should be visible in `Table`.
The `Buttons` block should not result in error.

**Screenshots**
Screenshot(2)

**Editor version (please complete the following information):**
- Gutenberg version [8.4]

**Desktop (please complete the following information):**
 - OS: [Linux Mint]
 - Browser [chrome, firefox]

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #23511 and #24331.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-editor/src/components/block-list/block.js [hunk 1]
```diff
@@ -219,33 +219,37 @@ function BlockListBlock( {
...
+			);
+		}
+	} else {
+		block = (
+			<Block.div>
+				<BlockInvalidWarning clientId={ clientId } />
+				<div>{ getSaveElement( blockType, attributes ) }</div>
+			</Block.div>
+		);
+	}
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-list/block.js:247]: We can flatten the if/else by inverting `if ( !isValid ) { } else if ...`

**Review by ntsekouras — APPROVED** [review]
LGTM 👍
