### PR TITLE
Try: use 'frecency' to sort items in the inserters

### LINKED ISSUE #5320: Use 'frecency' in the inserter?
screen shot 2018-03-01 at 10 58 10

Currently, blocks in the _Recent_ tab are ordered from most recently used to least recently used. This works, but fails to take into account how frequently a block is used. It might be worth exploring sorting these blocks by [_frecency_](https://en.wikipedia.org/wiki/Frecency).

I like this definition used by [z](https://github.com/rupa/z):

> Frecency is a portmanteau of ‘recent’ and ‘frequency’. It is a weighted rank  that depends on how often and how recently something occurred. As far as I know, Mozilla came up with the term.
>
> To z, a directory that has low ranking but has been  accessed  recently will  quickly  have  higher rank than a directory accessed frequently a long time ago.

The [sorting function that z uses](https://github.com/rupa/z/blob/ea5ec7834398ee2244de26953b3d1ef785d3f942/z.sh#L138-L145) looks like it might work well for us, as well:

```awk
function frecent(rank, time) {
    # relate frequency and time
    dx = t - time
    if( dx < 3600 ) return rank * 4
    if( dx < 86400 ) return rank * 2
    if( dx < 604800 ) return rank / 2
    return rank / 4
}
```

Thoughts? Is this worth trying? cc. @karmatosed @jasmussen @mtias

### PR DESCRIPTION
**Pull request by noisysocks**
Closes #5320.

screen shot 2018-03-01 at 10 58 10

Quick attempt at using [_frecency_](https://en.wikipedia.org/wiki/Frecency)—a heuristic that combines frequency and recency—to sort the items that appear in both the main inserter and the quick inserter.

The scoring function I used is borrowed from [z](https://github.com/rupa/z), an open source command line tool. We'll likely want to adjust the algorithm based on what feels right.

To test, insert a few different blocks and look at how that affects the _Recent_ tab in the inserter. Recently inserted blocks should move to the top of the list, but they shouldn't displace very frequently used blocks.

### CODE REVIEW

**Review by youknowriad — COMMENTED** [review]
Code wise, this is looking good. I'll defer to @jasmussen and @karmatosed for the algorithm.

**Comment by jasmussen** [comment]
This seems good to me, though it's hard to test quickly as almost by definition we have to let this run for a while to test it. 👍 👍

**Comment by mtias** [comment]
Should we change the label?

**Comment by karmatosed** [comment]
> Should we change the label?

Yes good point, it's not recent anymore. Stumbling as to what though. Maybe we just don't have a label and say blocks,  the library?

**Comment by folletto** [comment]
It's too long, but for reference Slack uses "Frequently Used".

**Comment by youknowriad** [comment]
What about just "Frequent" to make it shorter?

**Comment by jasmussen** [comment]
Frequent 👍

(Or "Frecent"? 😉)

**Comment by StaggerLeee** [comment]
"Popular"

**Comment by noisysocks** [comment]
I've renamed the tab to _Frequent_ 🙂

**Review by youknowriad — APPROVED** [review]
Nice 👍

File: editor/store/reducer.js [hunk 1]
```diff
@@ -656,17 +656,12 @@ export function preferences( state = PREFERENCES_DEFAULTS, action ) {
...
 				return {
 					...prevState,
-					recentInserts: [
-						insert,
-						...reject( prevState.recentInserts, isSameAsInsert ),
-					],
 					insertUsage: {
 						...prevState.insertUsage,
 						[ id ]: {
+							time: Date.now(),
```
Comment (aduth) [inline editor/store/reducer.js]: Pedantry: `Date.now` is impure:

https://en.wikipedia.org/wiki/Functional_programming#Pure_functions

>If a pure function is called with arguments that cause no side-effects, the result is constant with respect to that argument list ... i.e., if calling the pure function again with the same arguments returns the same result.

Violating a core principle of Redux:

>Reducers are just pure functions that take the previous state and an action, and return the next state.

https://redux.js.org/introduction/three-principles#changes-are-made-with-pure-functions

Comment (noisysocks) [reply editor/store/reducer.js]: You're totally right. I'll move this to the action creator.

File: editor/store/test/reducer.js [hunk 2]
```diff
@@ -1211,21 +1210,19 @@ describe( 'state', () => {
 			} );
 
 			expect( state ).toEqual( {
-				recentInserts: [
-					{ name: 'core-embed/twitter' },
-				],
 				insertUsage: {
 					'core-embed/twitter': {
+						time: expect.any( Number ),
```
Comment (aduth) [inline editor/store/test/reducer.js]: To the [above point](https://github.com/WordPress/gutenberg/pull/5342/files#r172350724), we shouldn't have any need for `expect.any` in this file, given that a reducer should be deterministic.

**Comment by noisysocks** [comment]
Good point. `duration` will be `NaN` which means that `calculateFrecency` will fall through to the `default` case and treat the block as if it were used a long long time ago. This isn't incorrect per se, but I'll update the function to more explicitly handle this case.
