### PR TITLE
Fix Navigation Link block variations to show correct labels instead of generic 'Post Link'

### LINKED ISSUE #72523: Nav Link block variations Title/Desc not correctly generated for CPTs and Taxonomies
When registering 

- Custom Post Types
- Custom Taxonomies

...the Nav Link block should generate block variations for each. This allows for Nav Link items which represent those entities and makes it easier to search for specific types.

However in my testing these variations are all being creating with identical Title and Description properties. This results in:

`Post Link - a link to a post` for each variations making them virtually indistinguishable in the UI.

I believe this is due to default labels being used as fallbacks for `item_link` and `item_link_description` on the CPT `labels` configuration. That's fine for most of WP Admin but the Nav Link block variations is a unique use case.

## Screenshot

Screen Shot 2025-10-21 at 11 11 32

### PR DESCRIPTION
**Pull request by getdave**
### What
Fixes Navigation Link block variations to display correct titles and descriptions instead of generic "Post Link" labels. This addresses confusion in the Editor where all variations appeared with the same generic label.

Fixes https://github.com/WordPress/gutenberg/issues/72523

### Why
Currently, Navigation Link block variations for different post types and taxonomies all display as "Post Link" in the Editor, making it impossible for users to distinguish between different content types when adding navigation links. This creates a poor user experience and makes navigation management confusing.

The issue occurs because the system was using hardcoded default labels instead of generating appropriate labels based on the specific post type or taxonomy being linked to.

### How
- **Enhanced label generation**: Updated `build_variation_for_navigation_link()` function to generate custom labels using the entity's `singular_name` when default generic labels are detected
- **Fallback mechanism**: Implemented intelligent fallback that creates descriptive labels like "Product Link" or "Event Link" instead of generic "Post Link"
- **Default label detection**: Added logic to detect when entities are using WordPress core's default generic labels and replace them with more descriptive alternatives
- **Test coverage**: Added comprehensive PHPUnit tests to verify the function works correctly with both post types and taxonomies

## Before/After

| Before | After |
|--------|-------|
| Screen Shot 2025-10-21 at 11 11 32 | Screen Shot 2025-10-21 at 11 12 17 |

### Testing

<details>
<summary>Test Environment Setup</summary>

To test this fix, you can use the following MU plugin code to register custom post types and taxonomies:

```php
<?php
/*
Plugin Name: Navigation Link Test MU Plugin
Description: Test plugin for Navigation Link block variations
*/

function register_test_post_types() {
	$post_types = array(
		'books'    => array(
			'singular'  => 'Book',
			'plural'    => 'Books',
			'menu_icon' => 'dashicons-book-alt',
		),
		'people'   => array(
			'singular'  => 'Person',
			'plural'    => 'People',
			'menu_icon' => 'dashicons-admin-users',
		),
		'products' => array(
			'singular'  => 'Product',
			'plural'    => 'Products',
			'menu_icon' => 'dashicons-cart',
		),
		'events'   => array(
			'singular'  => 'Event',
			'plural'    => 'Events',
			'menu_icon' => 'dashicons-calendar',
		),
	);

	foreach ( $post_types as $post_type => $details ) {
		$labels = array(
			'name'               => $details['plural'],
			'singular_name'      => $details['singular'],
			'menu_name'          => $details['plural'],
			'name_admin_bar'     => $details['singular'],
			'add_new'            => 'Add New',
			'add_new_item'       => 'Add New ' . $details['singular'],
			'new_item'           => 'New ' . $details['singular'],
			'edit_item'          => 'Edit ' . $details['singular'],
			'view_item'          => 'View ' . $details['singular'],
			'all_items'          => 'All ' . $details['plural'],
			'search_items'       => 'Search ' . $details['plural'],
			'parent_item_colon'  => 'Parent ' . $details['plural'] . ':',
			'not_found'          => 'No ' . strtolower( $details['plural'] ) . ' found.',
			'not_found_in_trash' => 'No ' . strtolower( $details['plural'] ) . ' found in Trash.',
		);

		$args = array(
			'labels'        => $labels,
			'public'        => true,
			'has_archive'   => true,
			'supports'      => array( 'title', 'editor', 'thumbnail', 'excerpt', 'comments' ),
			'menu_position' => 5,
			'menu_icon'     => $details['menu_icon'],
			'show_in_rest'  => true,
			'show_in_nav_menus' => true,
		);

		register_post_type( $post_type, $args );
	}
}
add_action( 'init', 'register_test_post_types' );

function register_test_taxonomies() {
	$taxonomies = array(
		'product_category' => array(
			'singular'     => 'Product Category',
			'plural'       => 'Product Categories',
			'hierarchical' => true,
			'slug'         => 'product-category',
		),
		'product_brand'    => array(
			'singular'     => 'Brand',
			'plural'       => 'Brands',
			'hierarchical' => false,
			'slug'         => 'brand',
		),
	);

	foreach ( $taxonomies as $taxonomy => $details ) {
		$labels = array(
			'name'              => $details['plural'],
			'singular_name'     => $details['singular'],
			'search_items'      => 'Search ' . $details['plural'],
			'all_items'         => 'All ' . $details['plural'],
			'parent_item'       => $details['hierarchical'] ? 'Parent ' . $details['singular'] : null,
			'parent_item_colon' => $details['hierarchical'] ? 'Parent ' . $details['singular'] . ':' : null,
			'edit_item'         => 'Edit ' . $details['singular'],
			'update_item'       => 'Update ' . $details['singular'],
			'add_new_item'      => 'Add New ' . $details['singular'],
			'new_item_name'     => 'New ' . $details['singular'] . ' Name',
			'menu_name'         => $details['plural'],
		);

		$args = array(
			'hierarchical'      => $details['hierarchical'],
			'labels'            => $labels,
			'show_ui'           => true,
			'show_admin_column' => true,
			'query_var'         => true,
			'rewrite'           => array( 'slug' => $details['slug'] ),
			'show_in_rest'      => true,
			'public'            => true,
			'show_in_nav_menus' => true,
		);

		register_taxonomy( $taxonomy, array( 'products' ), $args );
	}
}
add_action( 'init', 'register_test_taxonomies' );
```

1. Save this code as a `.php` file in your `wp-content/mu-plugins/` directory
2. Create some test content for the custom post types (I used FakerPress to generate posts in all the types registered).
3. In the Editor, insert a Navigation Link block
4. Click "Add block" in the Link UI dialog
5. Click "Browse" to see all blocks
6. Verify that variations now show "Book Link", "Product Link", "Event Link", etc. instead of "Post Link"
7. In the Link UI check that you can see search suggestions for the CPT that is relevant to your block variation type.
8. Test with different post types and taxonomies to ensure all show appropriate labels

</details>

This ensures users can easily identify and select the correct content type when building navigation menus, significantly improving the editing experience.

### CODE REVIEW

**Comment by getdave** [comment]
Problem here is that I can get the PHPUnit tests to pick up the gutenberg version of the function. I believe this is because it's already present in Core so we can't redeclare or something. I've forgotten how this works.

**Comment by scruffian** [comment]
I tested this without adding posts for each of the custom types and it works great.

File: packages/block-library/src/navigation-link/index.php [hunk 1]
```diff
@@ -312,11 +312,45 @@ function build_variation_for_navigation_link( $entity, $kind ) {
...
+
+	// Get description and check if it's default
+	$description            = '';
+	$is_default_description = false;
 	if ( property_exists( $entity->labels, 'item_link_description' ) ) {
 		$description = $entity->labels->item_link_description;
+		if ( $default_labels && isset( $default_labels['item_link_description'] ) ) {
+			$is_default_description = in_array( $description, $default_labels['item_link_description'], true );
+		}
+	}
```
Comment (scruffian) [inline packages/block-library/src/navigation-link/index.php:339]: We could refactor this into something more generic but I think it would decrease readability for the sake of saving a few lines of code.

File: packages/block-library/src/navigation-link/index.php [hunk 2]
```diff
@@ -312,11 +312,45 @@ function build_variation_for_navigation_link( $entity, $kind ) {
...
+
+	// Calculate singular name once (used for both title and description)
+	$singular = isset( $entity->labels->singular_name ) ? $entity->labels->singular_name : ucfirst( $entity->name );
+
+	// Set default title if needed
+	if ( $is_default_title || '' === $title ) {
+		$title = sprintf( /* translators: %s: Singular label of the entity. */ __( '%s Link' ), $singular );
```
Comment (scruffian) [inline packages/block-library/src/navigation-link/index.php]: I thought the translators comment was meant to go on the previous line?

Comment (scruffian) [reply packages/block-library/src/navigation-link/index.php]:
```suggestion
		$title = sprintf( /* translators: %s: Singular label of the entity. */ __( '%s link' ), $singular );
```
I think we prefer sentence case.

File: packages/block-library/src/navigation-link/index.php [hunk 3]
```diff
@@ -312,11 +312,45 @@ function build_variation_for_navigation_link( $entity, $kind ) {
...
+	// Get default labels based on entity type
+	$default_labels = null;
+	if ( $entity instanceof WP_Post_Type ) {
+		$default_labels = WP_Post_Type::get_default_labels();
+	} elseif ( $entity instanceof WP_Taxonomy ) {
+		$default_labels = WP_Taxonomy::get_default_labels();
+	}
+
+	// Get title and check if it's default
+	$title            = '';
```
Comment (scruffian) [inline packages/block-library/src/navigation-link/index.php]: We do this already on line 312, do we need to do it again?

File: packages/block-library/src/navigation-link/index.php [hunk 4]
```diff
@@ -312,11 +312,45 @@ function build_variation_for_navigation_link( $entity, $kind ) {
...
+	$is_default_title = false;
 	if ( property_exists( $entity->labels, 'item_link' ) ) {
 		$title = $entity->labels->item_link;
+		if ( $default_labels && isset( $default_labels['item_link'] ) ) {
+			$is_default_title = in_array( $title, $default_labels['item_link'], true );
+		}
 	}
+
+	// Get description and check if it's default
+	$description            = '';
```
Comment (scruffian) [inline packages/block-library/src/navigation-link/index.php]: We do this already on line 313, do we need to do it again?

File: packages/block-library/src/navigation-link/index.php [hunk 5]
```diff
@@ -312,11 +312,45 @@ function build_variation_for_navigation_link( $entity, $kind ) {
...
+	} elseif ( $entity instanceof WP_Taxonomy ) {
+		$default_labels = WP_Taxonomy::get_default_labels();
+	}
+
+	// Get title and check if it's default
+	$title            = '';
+	$is_default_title = false;
 	if ( property_exists( $entity->labels, 'item_link' ) ) {
 		$title = $entity->labels->item_link;
+		if ( $default_labels && isset( $default_labels['item_link'] ) ) {
```
Comment (scruffian) [inline packages/block-library/src/navigation-link/index.php]: Does this need to be inside the `if ( property_exists( $entity->labels, 'item_link' ) ) {` check?

File: packages/block-library/src/navigation-link/index.php [hunk 6]
```diff
@@ -375,7 +409,9 @@ function block_core_navigation_link_filter_variations( $variations, $block_type
 	}
 
 	$generated_variations = block_core_navigation_link_build_variations();
-	return array_merge( $variations, $generated_variations );
+	// Merge with existing variations - put our generated variations first
+	// so they override any generic labels from existing variations
```
Comment (scruffian) [inline packages/block-library/src/navigation-link/index.php]:
```suggestion
	// so they override any generic labels from existing variations.
```

File: phpunit/blocks/class-build-variation-for-navigation-link-test.php [hunk 7]
```diff
@@ -0,0 +1,496 @@
...
+	 * Test that the function returns an array with expected structure.
+	 */
+	public function test_function_returns_array() {
+		// Test with a real built-in post type
+		$post_type = get_post_type_object( 'post' );
+		$this->assertNotNull( $post_type, 'Post type object should exist' );
+
+		$variation = gutenberg_build_variation_for_navigation_link( $post_type, 'post-type' );
+
+		// Verify it returns an arraygs
```
Comment (scruffian) [inline phpunit/blocks/class-build-variation-for-navigation-link-test.php]:
```suggestion
		// Verify it returns an array.
```

File: phpunit/blocks/class-build-variation-for-navigation-link-test.php [hunk 8]
```diff
@@ -0,0 +1,496 @@
...
+	public function test_custom_post_type_variation_format() {
+		// Create a mock custom post type object
+		$post_type                        = new stdClass();
+		$post_type->name                  = 'product';
+		$post_type->labels                = new stdClass();
+		$post_type->labels->singular_name = 'Product';
+
+		$variation = gutenberg_build_variation_for_navigation_link( $post_type, 'post-type' );
+
+		// Verify the title format
```
Comment (scruffian) [inline phpunit/blocks/class-build-variation-for-navigation-link-test.php]:
```suggestion
		// Verify the title format.
```

File: phpunit/blocks/class-build-variation-for-navigation-link-test.php [hunk 9]
```diff
@@ -0,0 +1,496 @@
...
+		$this->assertEquals( 'Product Link', $variation['title'], 'Custom post type should have appropriately named title' );
+
+		// Verify the description format
```
Comment (scruffian) [inline phpunit/blocks/class-build-variation-for-navigation-link-test.php]:
```suggestion
		// Verify the description format.
```

File: phpunit/blocks/class-build-variation-for-navigation-link-test.php [hunk 10]
```diff
@@ -0,0 +1,496 @@
...
+		// Test with a real built-in post type
+		$post_type = get_post_type_object( 'post' );
+		$this->assertNotNull( $post_type, 'Post type object should exist' );
+
+		$variation = gutenberg_build_variation_for_navigation_link( $post_type, 'post-type' );
+
+		// Verify it returns an arraygs
+		$this->assertIsArray( $variation, 'Function should return an array' );
+
+		// Verify it has the expected keys
```
Comment (scruffian) [inline phpunit/blocks/class-build-variation-for-navigation-link-test.php]:
```suggestion
		// Verify it has the expected keys.
```

File: phpunit/blocks/class-build-variation-for-navigation-link-test.php [hunk 11]
```diff
@@ -0,0 +1,496 @@
...
+		$this->assertArrayHasKey( 'name', $variation, 'Variation should have name key' );
+		$this->assertArrayHasKey( 'title', $variation, 'Variation should have title key' );
+		$this->assertArrayHasKey( 'description', $variation, 'Variation should have description key' );
+		$this->assertArrayHasKey( 'attributes', $variation, 'Variation should have attributes key' );
+
+		// Verify attributes is an array with expected keys
```
Comment (scruffian) [inline phpunit/blocks/class-build-variation-for-navigation-link-test.php]:
```suggestion
		// Verify attributes is an array with expected keys.
```

File: packages/block-library/src/navigation-link/index.php (hunk 1 above)
Comment (getdave) [reply packages/block-library/src/navigation-link/index.php:339]: That's the conclusion I came to 👍

File: packages/block-library/src/navigation-link/index.php (hunk 5 above)
Comment (getdave) [reply packages/block-library/src/navigation-link/index.php]: It is inside? Are you saying we should move it outside? If so why?

File: packages/block-library/src/navigation-link/index.php (hunk 3 above)
Comment (getdave) [reply packages/block-library/src/navigation-link/index.php]: ✅

File: packages/block-library/src/navigation-link/index.php (hunk 4 above)
Comment (getdave) [reply packages/block-library/src/navigation-link/index.php]: ✅

**Comment by getdave** [comment]
@ellatrix This is quite a nasty bug in the UI (see screenshots in description) and it makes for a very confusing experience. 

This wasn't introduced in 6.9 (AFAIK) but it might be worth considering for inclusion if we've made the RC cut off.

File: packages/block-library/src/navigation-link/index.php [hunk 12]
```diff
@@ -312,11 +312,45 @@ function build_variation_for_navigation_link( $entity, $kind ) {
...
+		$default_labels = WP_Post_Type::get_default_labels();
+	} elseif ( $entity instanceof WP_Taxonomy ) {
+		$default_labels = WP_Taxonomy::get_default_labels();
+	}
+
+	// Get title and check if it's default
+	$is_default_title = false;
 	if ( property_exists( $entity->labels, 'item_link' ) ) {
 		$title = $entity->labels->item_link;
+		if ( $default_labels && isset( $default_labels['item_link'] ) ) {
```
Comment (talldan) [inline packages/block-library/src/navigation-link/index.php]: I believe `isset` will already check the existence of `$default_labels` so there's a small (optional) change you could make here:

```suggestion
		if ( isset( $default_labels['item_link'] ) ) {
```

File: packages/block-library/src/navigation-link/index.php [hunk 13]
```diff
@@ -312,11 +312,45 @@ function build_variation_for_navigation_link( $entity, $kind ) {
...
+			$is_default_title = in_array( $title, $default_labels['item_link'], true );
+		}
 	}
+
+	// Get description and check if it's default
+	$is_default_description = false;
 	if ( property_exists( $entity->labels, 'item_link_description' ) ) {
 		$description = $entity->labels->item_link_description;
+		if ( $default_labels && isset( $default_labels['item_link_description'] ) ) {
```
Comment (talldan) [inline packages/block-library/src/navigation-link/index.php]:
```suggestion
		if ( isset( $default_labels['item_link_description'] ) ) {
```

File: packages/block-library/src/navigation-link/index.php [hunk 14]
```diff
@@ -375,7 +409,9 @@ function block_core_navigation_link_filter_variations( $variations, $block_type
 	}
 
 	$generated_variations = block_core_navigation_link_build_variations();
-	return array_merge( $variations, $generated_variations );
+	// Merge with existing variations - put our generated variations first
+	// so they override any generic labels from existing variations.
+	return array_merge( $generated_variations, $variations );
```
Comment (talldan) [inline packages/block-library/src/navigation-link/index.php:439]: 🤔 Shouldn't it be the other way around based on the comment? If `$generated_variations` should override `$variations` I think it should be second:
https://www.php.net/manual/en/function.array-merge.php

File: packages/block-library/src/navigation-link/index.php [hunk 15]
```diff
@@ -312,11 +312,45 @@ function build_variation_for_navigation_link( $entity, $kind ) {
...
+	// Set default title if needed
+	if ( $is_default_title || '' === $title ) {
+		/* translators: %s: Singular label of the entity. */
+		$title = sprintf( __( '%s link' ), $singular );
+	}
+
+	// Set default description if needed
+	if ( $is_default_description || '' === $description ) {
+		/* translators: %s: Singular label of the entity. */
+		$description = sprintf( __( 'A link to a %s' ), strtolower( $singular ) );
```
Comment (talldan) [inline packages/block-library/src/navigation-link/index.php]: This interpolation creates a chance of grammatical errors (e.g. "A link to a event"). I'm not sure the description adds much, so perhaps it's better to show nothing:
Image

File: packages/block-library/src/navigation-link/index.php (hunk 14 above)
Comment (talldan) [reply packages/block-library/src/navigation-link/index.php:439]: I tested with it the other way around and it didn't make any difference, but maybe the test code doesn't trigger the problem.

Oh, though I'm assuming the variations have string keys, if they have numeric keys then I guess the generated variations may need to be first so that they're processed first. 💡 

I guess the comment could be updated to make that clearer. It's a case where the code would be more readable if PHP had separate `array_concat` and `array_merge` functions, but it doesn't.

**Review by talldan — COMMENTED** [review]
Looks pretty good, but I think the generated description text doesn't work unfortunately. No drama, I think it's fine for the variations to have no descriptions.

File: packages/block-library/src/navigation-link/index.php (hunk 14 above)
Comment (getdave) [reply packages/block-library/src/navigation-link/index.php:439]: Variations have indicies so this is effectively ensuring that the generated versions come first and are thus prioritised in the JavaScript which dedupes by name starting from the _beginning_ of the array.

I added a clearer comment. 

It's very confusing.

File: packages/block-library/src/navigation-link/index.php (hunk 15 above)
Comment (getdave) [reply packages/block-library/src/navigation-link/index.php]: Good spot. Thank you.

I have had to use an empty space as the default description to force it to empty otherwise it falls back to the `core/navigation-link` block description from `block.json`.

Open to alternative suggestions

**Review by scruffian — APPROVED** [review]
This is looking good, thanks!

**Comment by getdave** [comment]
@scruffian The tests broke here 😢
