### PR TITLE
Fix Global styles overriding block's element styles

### LINKED ISSUE #39010: Global styles override block level element styles when in Editor
### Description

If we have global styles applied for block color `text` and `link` and then provide local block style overrides by changing the color of the `link` the global styles take higher precedence because of css selector higher specificity and override local styles. 

Styles for block level selectors work fine, just element level styles fail to be resolved proeprly.

This is related to other styles (reset, global styles etc.) being prefixed with `.editor-styles-wrapper` class and I've found these changes started being introduced around [March 2021](https://github.com/WordPress/gutenberg/pull/30038/files) and persist until now ([1](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/layouts/utils.js), [2](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/hooks/duotone.js#L284), [3](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/editor-styles/index.js#L71) etc.)

Element level block styles do not have the prefixed class present causing element level style to be overwritten by global styles if present.

Possibly related to https://github.com/WordPress/gutenberg/issues/37262

### Step-by-step reproduction instructions

1. Go to `Site Editor`.
2. Edit `Global Styles` for `Paragraph` block - set custom color for text and link.
3. Add new `Page`.
4. Create a `Paragraph` - it should have global styles applied.
5. Create new `Paragraph` and edit its color styles using different text and link color.

- 🚫  Link color will be ignored when in Editor (Front-End works ok)
- ✅  Text color overrides correctly 

### Screenshots, screen recording, code snippet

Screenshot 2022-02-23 at 09 56 57

### Environment info

- WordPress 5.9.1, Gutenberg 12.6.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by tomasztunik**
## Description

This fixes #39010

This fixes issue where global styles would override local block level style settings for block element styles (ie. link color). For more details please see #39010. 

Fix is applied by prefixing css selectors with `.editor-styles-wrapper` in the `compileElementsStyles` used by `withElementsStyles` HOC which is used only in the editor.

## Testing Instructions
1. Go to Site Editor.
2. Edit Global Styles for Paragraph block - set custom color for text and link.
3. Add new Page.
4. Create a Paragraph - it should have global styles applied.
5. Create new Paragraph and edit its color styles using different text and link color.

- [ ] Link color should override global styles
- [ ] Text color should override global styles

## Screenshots 

| before | after |
| - | - |
|  Screenshot 2022-02-23 at 09 56 57 |  Screenshot 2022-02-23 at 09 18 30 |

## Checklist:
- [x] My code is (manually)  tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

File: packages/block-editor/src/hooks/style.js [hunk 1]
```diff
@@ -122,8 +122,11 @@ function compileElementsStyles( selector, elements = {} ) {
 	return map( elements, ( styles, element ) => {
 		const elementStyles = getInlineStyles( styles );
 		if ( ! isEmpty( elementStyles ) ) {
+			// The .editor-styles-wrapper selctor is required on elements styles. As it is
```
Comment (jorgefilipecosta) [inline packages/block-editor/src/hooks/style.js]: selctor -> selector

**Review by jorgefilipecosta — APPROVED** [review]
Thank you for this fix @tomasztunik 👍  I'm not sure if a single class specificity increase is going to be enough long term. But I think for sure it is a simple solution we can apply for now and see what feedback we get.

File: packages/block-editor/src/hooks/style.js (hunk 1 above)
Comment (tomasztunik) [reply packages/block-editor/src/hooks/style.js]: Thanks for the catch!

**Comment by tomasztunik** [comment]
I agree @jorgefilipecosta. When trying to find the source of this I've tracked the usage throughout the code and it wasn't obvious outside of one place (that also moved around over time) about the need for this.

Maybe there could be a more centralised CSS processing pipeline? (maybe this would be part of style-engine effort?)

I've noticed that template/theme editor is opened in its own iframe context but regular post editor is not. Curious if maybe having editor always in its own context could be an alternative that wouldn't require class namespacing the editor and would possibly open up new possibilities for more uniform target device simulation across different types of editors.

(not backed by any research into why it is the way it is now!)

**Comment by jorgefilipecosta** [comment]
> I've noticed that template/theme editor is opened in its own iframe context but regular post editor is not. Curious if maybe having editor always in its own context could be an alternative that wouldn't require class namespacing the editor and would possibly open up new possibilities for more uniform target device simulation across different types of editors.

Long term we may expand the iframe for the normal post editor, and one of the reasons is to fix this type of issues.
