### PR TITLE
[Heading Block] Fix double alignment controls in toolbar

### LINKED ISSUE #26335: Heading Block: Double alignment controls in toolbar
**Describe the bug**
After #25917 was merged, the block alignment toolbar is automatically added to the Heading block toolbar, and it controls the `align` attribute. This attribute was already in use for text alignment, so now there are two controls which both control `align`.

**To reproduce**

1. Add a Heading block
2. Click the text alignment to center the text
3. Decide you also want it wide, so click the block alignment & select wide
4. The text is now left-aligned

**Expected behavior**
Probably text alignment and block size (default/wide/full) should be separate, so that you can have a wide centered heading. Otherwise, maybe use just the `BlockAlignmentToolbar` & remove the text alignment, so it's clear that you can't have wide + center.

**Screenshots**

Screen Shot 2020-10-20 at 4 36 19 PM

If you have a wide heading like above, then click text align center, it goes back to default width.

Screen Shot 2020-10-20 at 4 36 30 PM

**Editor version (please complete the following information):**
- WordPress version: 5.6-alpha
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Plugin
- If the Gutenberg plugin is installed, which version is it? master

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/26335

After #25917 was merged, the block alignment toolbar is automatically added to the Heading block toolbar, and it controls the `align` attribute. This attribute was already in use for text alignment, so now there are two controls which both control `align`.

This PR renames the previous `align` attribute used for text alignment to `textAlign` and handles the deprecated block.

Steps to reproduce are on the issue. Basically just add a `heading` block and try to add both `text-align` and `block-align` from its Toolbar.

## How has this been tested?
1. Create some headings from master with different alignments, both text and block.
2. In this branch go to edit the same post and see that there are no errors and the migration works.
3. Also test that both alignments are supported now.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-library/src/heading/deprecated.js [hunk 1]
```diff
@@ -48,7 +52,52 @@ const migrateCustomColors = ( attributes ) => {
...
+				'core/heading/h1': 'h1',
+				'core/heading/h2': 'h2',
+				'core/heading/h3': 'h3',
+				'core/heading/h4': 'h4',
+				'core/heading/h5': 'h5',
+				'core/heading/h6': 'h6',
+			},
+			__unstablePasteTextInline: true,
+		},
+		attributes: { ...blockAttributes },
```
Comment (gziolo) [inline packages/block-library/src/heading/deprecated.js:83]: What's the reason for using shallow copy here?

File: packages/block-library/src/heading/deprecated.js [hunk 2]
```diff
@@ -48,7 +52,52 @@ const migrateCustomColors = ( attributes ) => {
...
 };
 
+const migrateTextAlign = ( attributes ) => {
+	const { align, ...rest } = attributes;
+	return TEXT_ALIGN_OPTIONS.includes( align )
+		? { ...rest, textAlign: align }
+		: attributes;
+};
+
+const TEXT_ALIGN_OPTIONS = [ 'left', 'right', 'center' ];
```
Comment (gziolo) [inline packages/block-library/src/heading/deprecated.js:62]: It might be easier to follow code if this const was defined before it is used.

File: packages/block-library/src/heading/deprecated.js [hunk 3]
```diff
@@ -48,7 +52,52 @@ const migrateCustomColors = ( attributes ) => {
...
+
 const deprecated = [
+	{
+		supports: {
+			className: false,
```
Comment (gziolo) [inline packages/block-library/src/heading/deprecated.js:67]: It would be easier to review if those settings were in the same order as in `block.json` file. Just saying for future, no need to update :)

**Review by gziolo — APPROVED** [review]
Great work, I left some nitpicks to look at before merging but overall it resolves the issue with legacy usage of the `align` attribute for this block.

File: packages/block-library/src/heading/deprecated.js (hunk 1 above)
Comment (ntsekouras) [reply packages/block-library/src/heading/deprecated.js:83]: No reason. Left it there early on my first changes. I'll change it, thanks!

File: packages/block-library/src/heading/deprecated.js (hunk 2 above)
Comment (ntsekouras) [reply packages/block-library/src/heading/deprecated.js:62]: You're definitely right.

File: packages/block-library/src/heading/deprecated.js (hunk 3 above)
Comment (ntsekouras) [reply packages/block-library/src/heading/deprecated.js]: I changed that as well since I addressed the other feedback. Will keep in mind for the future too :)
