### PR TITLE
fix: Undefined index "colors" warning

### LINKED ISSUE #2198: Theme Options: Undefined index "colors" when not defined in theme supports
Introduced in: #2186 

## Issue Overview

If a theme defines `gutenberg` theme support, but does not include a `'colors'` setting, a warning is logged:

```
<b>Notice</b>:  Undefined index: colors in <b>/srv/www/editor/htdocs/wp-content/plugins/gutenberg/lib/client-assets.php</b> on line <b>654</b><br />
```

https://github.com/WordPress/gutenberg/blob/b9deeb8/lib/client-assets.php#L654

## Steps to Reproduce

1. In an `after_setup_theme` action handler, add: `add_theme_support( 'gutenberg', array() );`
2. Navigate to Gutenberg editor
3. Depending on logging level, you may see the above notice

## Possible Solution

Check that key exists in settings before accessing, or provide abstraction (function getter) to retrieve Gutenberg theme options.

### PR DESCRIPTION
**Pull request by ayoolatj**
Check that key exists and is not empty.

resolves: #2198

### CODE REVIEW

**Review by gziolo — CHANGES_REQUESTED** [review]
Thanks for opening this PR. It fixes the bug described in #2198:

```html
<b>Notice</b>:  Undefined index: colors in <b>/srv/www/editor/htdocs/wp-content/plugins/gutenberg/lib/client-assets.php</b> on line <b>654</b><br />
```

but there is still another `PHP notice` in this code that needs to be fixed:

```html
<b>Notice</b>:  Undefined index: wide-images in <b>/srv/www/wordpress-default/public_html/wp-content/plugins/lib/client-assets.php</b> on line <b>791</b><br>
```

**Comment by ayoolatj** [comment]
I've updated my code to fix the second php notice

File: lib/client-assets.php [hunk 1]
```diff
@@ -783,12 +783,12 @@ function gutenberg_editor_scripts_and_styles( $hook ) {
 	$gutenberg_theme_support = get_theme_support( 'gutenberg' );
 	$color_palette = gutenberg_color_palette();
 
-	if ( $gutenberg_theme_support && $gutenberg_theme_support[0]['colors'] ) {
+	if ( $gutenberg_theme_support && ! empty( $gutenberg_theme_support[0]['colors'] ) ) {
```
Comment (gziolo) [inline lib/client-assets.php]: I'm wondering if `empty` isn't powerful enough to make it possible to simplify it to:
```php
if ( ! empty( $gutenberg_theme_support[0]['colors'] ) ) {
```

**Comment by gziolo** [comment]
That was quick, thanks. Testing your changes :)

File: lib/client-assets.php (hunk 1 above)
Comment (ayoolatj) [reply lib/client-assets.php]: Sorry, I'm a little lost. Can you explain further?

Comment (gziolo) [reply lib/client-assets.php]: > Determine whether a variable is considered to be empty. A variable is considered empty if it does not exist or if its value equals FALSE. empty() does not generate a warning if the variable does not exist.

You don't need to check if `$gutenberg_theme_support` is truthy, because `empty` does that, too.

Comment (gziolo) [reply lib/client-assets.php]: Just tested with the following code:

```php
function mytheme_setup_theme_supported_features() {
	add_theme_support( 'gutenberg', null );
}

add_action( 'after_setup_theme', 'mytheme_setup_theme_supported_features' );
```

File: lib/client-assets.php [hunk 2]
```diff
@@ -783,12 +783,12 @@ function gutenberg_editor_scripts_and_styles( $hook ) {
...
 		$color_palette = $gutenberg_theme_support[0]['colors'];
 	}
 
 	$editor_settings = array(
-		'wideImages' => $gutenberg_theme_support ? $gutenberg_theme_support[0]['wide-images'] : false,
+		'wideImages' => ( $gutenberg_theme_support && ! empty( $gutenberg_theme_support[0]['wide-images'] ) ) ? $gutenberg_theme_support[0]['wide-images'] : false,
```
Comment (gziolo) [inline lib/client-assets.php]: In this place it would get simplified to the following:
```php
'wideImages' => ! empty( $gutenberg_theme_support[0]['wide-images'] ) ),
```

**Review by gziolo — APPROVED** [review]
I tested with the latest changes. I no longer see PHP notices. Nicely done @ayoolatj. I will leave it open to let you respond to my feedback. Let me know if you want to try to save some keystrokes as I suggested :)

File: lib/client-assets.php (hunk 1 above)
Comment (ayoolatj) [reply lib/client-assets.php]: Yeah that's right, should I update the PR with this?

Comment (gziolo) [reply lib/client-assets.php]: If you like it, then go for it. Totally up to you :)

Comment (ayoolatj) [reply lib/client-assets.php]: Updated :)

**Comment by gziolo** [comment]
Thanks for another update. It looks great now. 🎉
