### PR TITLE
Input Interaction: only consider selection at edge if directed towards it

### LINKED ISSUE #12322: Text selection with keyboard triggers blocks multi-selection unexpectedly
Tested on latest master 4.5.1.

Looks like selecting text with the keyboard works differently from selecting text with the mouse. At some point the blocks multi-selection kicks in and breaks the expected behavior.

Selecting text with Shift and Arrow keys is a pretty common expectation for all users, and it's also the only selection method for users who don't use the mouse.

In the GIF below, I'm following 3 steps:
- mouse: selection on 4 lines works as expected
- keyboard: as soon as the selection reaches the 4th line, multi-selection kicks in and doesn't allow to complete the selection as desired
- keyboard on a shorter text: a bit surprisingly, seems the previous incorrect behavior doesn't happen when the selection spans on a shorter text, e.g. only 3 lines

selection short

Additionally, if the selection happens on the last block there's one more breaking behavior. In the GIF below:
- if the selection is on the last 3 lines, I'm able to reach the last line in the text
- if I start from the fourth line from the bottom, I'm unable to reach the last line:

selection last

A similar behavior happens when starting the selection from bottom to top in the first block.

### PR DESCRIPTION
**Pull request by ellatrix**
Closes #12322

## Description

An alternative to #13638. I chose to make the selection direction check inside `isVerticalEdge`, as we do the same for `isHorizontalEdge`. ~~Still needs tests.~~

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/dom/src/dom.js [hunk 1]
```diff
@@ -169,7 +169,18 @@ export function isVerticalEdge( container, isReverse ) {
 	}
 
 	const selection = window.getSelection();
+
+	// Only consider the selection at the edge if the direction is towards the
+	// edge.
```
Comment (aduth) [inline packages/dom/src/dom.js]: Love the dedication to the 80 column 👍

**Review by aduth — APPROVED** [review]
Generally, this is great.

There's one small imperfection by the logic, and it's OS-specific as well. Per https://github.com/WordPress/gutenberg/pull/13638#issuecomment-464754327 , the behavior of Shift+Up in a non-collapsed selection in a line of a text in non-macOS environments is that it should expand to the previous line (or in our case, if in the first line of a paragraph and a block preceded it, triggering multi-selection). Right now, the behavior is that _nothing happens_. Effectively in this scenario, I think it might be correct to say that it _is_ at the vertical edge, even if the selection is non-collapsed.

That being said, what exists here is a huge improvement all the same, so I'd like to see it merged.

**Comment by ellatrix** [comment]
@aduth Thanks for the review! I'll have a look into the issue you're describing, maybe we can fix it separately.

**Comment by ellatrix** [comment]
@aduth Looking at your GIF, it seems like a consecutive `shift+arrowUp` press would trigger multi-block selection? The behaviour is slightly different, but you can still select blocks?

chrome

**Comment by ellatrix** [comment]
Or am I missing something that would block multi-block selection after these steps?

**Comment by aduth** [comment]
The specific point I'm trying to make could do for a better / different animation, I think.

Essentially: Everywhere except macOS, if an uncollapsed selection exists within a single line, the effect of pressing ArrowUp (with Shift held) should be to expand the selection to the previous line.

In terms of blocks, that may mean triggering a multi-selection. Or, at the very least, it's contradictory to the idea here that a vertical edge traversal cannot occur with an uncollapsed selection.

**Comment by ellatrix** [comment]
@aduth I think I slowly get what you mean. It would be good to have an issue with the steps to reproduce the issue, and what you'd expect to happen vs what happens now in `master`. After playing on macOS a bit, it does seem strange that the OS completely disregards the selection direction when using the keyboard after having set it with a pointer device.

**Comment by aduth** [comment]
I created an issue at #14463 . Noting that it's improved a bit more from what I was observing, as a result of the changes from #14453, but still not quite as expected.
