### PR TITLE
Block API: Add support for transforms prioritization

### LINKED ISSUE #5620: Embed block: pasting an URL doesn't transform to embed block any more (Example: Tweet)
## Issue Overview

To embed a Tweet into a post you used to be able to just paste the URL into an empty block and it would transform it into an embed block and display the tweet. The webdeveloper console displays: "firefox can’t establish a connection to the server at wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data."
The network view shows a 403 Forbidden error.
## Steps to Reproduce (for bugs)

1. Add post
2. paste: https://twitter.com/Tarendai/status/974028740249432064
3. 
4.

Browser FireFox Developer Edition 60.0b1
Gutenberg 2.4

## Expected Behavior

pasting url transforms to embed block 
## Current Behavior

Nothing happens when you paste
## Screenshots / Video

mvj6zxcgql

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by aduth**
Fixes #5620

This pull request seeks to add a prioritization mechanism to block transforms, addressing two current issues with reliance on block registration order (paragraph and shortcode transforms as fallback). From a block implementer perspective, this simply adds a new property `priority` to the transform object, which behaves nearly identical to hooks prioritization (the similarity is not coincidental, as it uses hooks under the hood as the basis). At a code level, it introduces two new functions `getBlockTransforms` and `findTransform` which respectively return/normalize transforms and return a predicate-matching transform considering priority.

There may be room for further optimization here (e.g. sorting at registration time, caching transforms) but after a few failed attempts, I landed on this as a more direct/simple implementation.

__Testing instructions:__

Verify that there are no regressions in transform behavior. Notably, this impacts:

- Block transforms
- Paste transforms
- Shortcode transforms 
- Use-once validation
- File drop

### CODE REVIEW

File: blocks/library/index.js [hunk 1]
```diff
@@ -36,26 +36,6 @@ import * as video from './video';
...
-		//
-		// This isn't a proper solution, as it is at odds with the
-		// specification of shortcode conversion, in the sense that conversion
-		// is explicitly independent of block order. Thus, concurrent parse
-		// rules (i.e. a same text input can yield two different transforms,
-		// like `[gallery] -> { Gallery, Shortcode }`) are unsupported,
-		// yielding non-deterministic results. A proper solution could be to
-		// let the editor (or site owners) determine a default block handler of
-		// unknown shortcodes — see `setUnknownTypeHandlerName`.
-		shortcode,
```
Comment (mcsf) [inline blocks/library/index.js]: \o/

File: test/unit/setup-wp-aliases.js [hunk 2]
```diff
@@ -1,7 +1,8 @@
 // Set up `wp.*` aliases.  Handled by Webpack outside of the test build.
 global.wp = {
 	shortcode: {
-		next: () => {},
+		next() {},
+		regexp() {},
```
Comment (mcsf) [inline test/unit/setup-wp-aliases.js]: This needs proper stubbing for tests.

**Review by mcsf — COMMENTED** [review]
Nice. I find the reuse of `hooks` clever. Outside this PR, it would be interesting to have some perf tests that we could incorporate into the test suite to track improvements and regressions. Right now, we only have anecdotal evidence to judge the impact of something like these changes (no apparent regression on my end).

**Comment by aduth** [comment]
Thanks for the review @mcsf .

>This needs proper stubbing for tests.

Just slightly more accurate stubbing; at least returning a RegExp. This is resolved in the rebased 777f7b6. Of course, the fact that the stubbed RegExp is enough to allow tests to pass is a good signal we have poor test coverage for this functionality.

Longer-term, we'd want to extract `wp.shortcode` as a reusable module that we can reference from npm.

**Review by mcsf — APPROVED** [review]

**Comment by aduth** [comment]
Re: Performance, in fact I might suspect a net performance improvement from the changes here, merely by dropping all the `_.get` calls.
