### PR TITLE
Dependency Extraction Webpack Plugin: Make the plugin work when using `optimizations.runtimeChunk = 'single'`

### LINKED ISSUE #24352: dependency-extraction-webpack-plugin breaks when using optimizations.runtimeChunk = 'single'
**Describe the bug**

`@wordpress/dependency-extraction-webpack-plugin` breaks in two ways when using `optimizations.runtimeChunk = 'single'`.

1. The asset files are named based on the runtime chunk's name, i.e. `runtime.asset.php`.
2. All asset files are added to the runtime chunk.

The first issue results in only the last entrypoint's asset being saved (as it overwrites the previous ones').

The second issue makes it impossible to correlate an asset file with its entrypoint.

**To reproduce**

I've created an example project here: https://github.com/stefanfisk/wordpress-dependency-extraction-webpack-plugin-runtimechunk-single-bug

**Expected behavior**

The asset files should be named according to the entrypoint names, and only be added to the entrypoint chunks.

Preferably it should be possible to configure the asset file names. For example it would be nice if using hashes in `output.filename` did not result in the asset filename containing a hash.

**Plugin version:**

- `@wordpress/dependency-extraction-webpack-plugin` 2.8.0
- `webpack` 4.44.1

### PR DESCRIPTION
**Pull request by stefanfisk**
## Description
A quick proof of concept for fixing https://github.com/WordPress/gutenberg/issues/24352, as requested by @sirreal.

## How has this been tested?
I'm currently using this patch daily, and it works for me. Beyond that I don't know.

## Types of changes
The asset filename logic has been modified, and the assets are now pushed to the entrypoint chunks instead of the runtime chunk.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [ ] My code follows the accessibility standards.
- [x] My code has proper inline documentation
- [x] I've included developer documentation if appropriate.
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by sirreal** [comment]
Thanks for this @stefanfisk 👍 

What do you think of adding a test that fails like in your example repository? You can add a directory here with a minimal example project: https://github.com/WordPress/gutenberg/tree/master/packages/dependency-extraction-webpack-plugin/test/fixtures

**Comment by stefanfisk** [comment]
@sirreal I've added a test, but it is not failing since the PR already contained a fix.

I also added a small change to which chunk's hash is used in the asset file.

**Comment by stefanfisk** [comment]
Oh, and I changed the snapshot format to contain the asset filenames, as that was part of the issue.

File: packages/dependency-extraction-webpack-plugin/lib/index.js [hunk 1]
```diff
@@ -214,23 +214,26 @@ class DependencyExtractionWebpackPlugin {
 					}
 				}
 
-				const runtimeChunk = entrypoint.getRuntimeChunk();
+				const entrypointChunk = entrypoint.chunks.find(
```
Comment (stefanfisk) [inline packages/dependency-extraction-webpack-plugin/lib/index.js:217]: This is a method for finding the entrypoint chunk that I found through trial and error, but I don't now the webpack internals enough to say if it is reliable.

Comment (sirreal) [reply packages/dependency-extraction-webpack-plugin/lib/index.js:217]: I'm doing my best to follow up on this but don't lot of time to spare, so thanks for your patience.

This does look questionable and I don't have a deep understanding of webpack internals either (they're mysterious).

It looks like webpack 5 introduces `Entrypoint.getEntrypointChunk()` which would be helpful here 🙄 

https://github.com/webpack/webpack/blob/ec8e1bb0b3b8203818741f731fdf654e1583b2d4/lib/Entrypoint.js#L80-L87

I'm tempted to wait for #26382.

Comment (stefanfisk) [reply packages/dependency-extraction-webpack-plugin/lib/index.js:217]: I was also drawn to `Entrypoint.getEntrypointChunk()` until I realised that it wasn't available in Webpack 4, so I totally agree that waiting for Webpack 5 support makes sense instead of praying that the weird hack that seems to work doesn't break in weird and wonderful ways :)

**Comment by stefanfisk** [comment]
I just cleaned the code up, and added use of the Webpack 5 `Entrypoint.getEntrypointChunk()` function. For Webpack 4 it still uses the dodgy way of finding the entrypoint chunk. 

I also added an option for specifying the asset output filename separately, so that one can use hashes in the js output filenames and still have predictable asset filenames.

File: packages/dependency-extraction-webpack-plugin/lib/index.js (hunk 1 above)
Comment (gziolo) [reply packages/dependency-extraction-webpack-plugin/lib/index.js]: It might take another couple of weeks to land webpack 5. Once it happens we should drop support for webpack 4 to simplify this plugin.

**Comment by gziolo** [comment]
@stefanfisk, many thanks for opening this PR. It seems like a complex issue to address so I appreciate all the time invested on it since it works for you already 😃

I have one general question to better understand the context. What’s the purpose of `runtimeChunk` set to `single`?

**Comment by stefanfisk** [comment]
`runtimechunk='single'` results in all loaded entrypoints sharing instances of modules, rather than Webpack initialising every module separately for each entrypoint if multiple entrypoints are loaded at the same time. So *runtime* in this context refers to the Webpack runtime.

This for example allows you to use an entrypoint for admin that is always loaded for admin pages, a block-editor entrypoint that is only loaded by the block editor, all while they share instances of stateful modules.

File: packages/dependency-extraction-webpack-plugin/lib/index.js (hunk 1 above)
Comment (gziolo) [reply packages/dependency-extraction-webpack-plugin/lib/index.js]: We are sort out our second attempt to upgrade webpack from v4 to v5 in https://github.com/WordPress/gutenberg/pull/33818. The remaining question would be if we are going to keep support for both versions v4 and v5 of webpack on the plugin.

Comment (stefanfisk) [reply packages/dependency-extraction-webpack-plugin/lib/index.js]: Is there anything I can do to help get this PR going again?

File: packages/dependency-extraction-webpack-plugin/lib/index.js [hunk 2]
```diff
@@ -178,16 +184,30 @@ class DependencyExtractionWebpackPlugin {
...
 				}
 
-				const assetFilename = buildFilename.replace(
-					/\.js$/i,
-					'.asset.' + ( outputFormat === 'php' ? 'php' : 'json' )
-				);
+				let assetFilename;
+
+				if ( outputFilename ) {
+					assetFilename = compilation.getPath( outputFilename, {
```
Comment (gziolo) [inline packages/dependency-extraction-webpack-plugin/lib/index.js]: Should we enforce a matching `outputFormat` based on the extension used in the file? At least when it ends with `.php` or `.json`. We could also leave it as is - the developer using the plugin still would have to pass two options to set everything correctly when using non-default output format.

File: packages/dependency-extraction-webpack-plugin/test/build.js [hunk 3]
```diff
@@ -61,9 +61,13 @@ describe.each( configFixtures )( 'Webpack `%s`', ( configCase ) => {
 
 				// Asset files should match.
 				assetFiles.forEach( ( assetFile ) => {
+					const assetBasename = path.basename( assetFile );
+
 					expect(
 						fs.readFileSync( assetFile, 'utf-8' )
-					).toMatchSnapshot( 'Asset file should match snapshot' );
+					).toMatchSnapshot(
+						`Asset file '${ assetBasename }' should match snapshot`
```
Comment (gziolo) [inline packages/dependency-extraction-webpack-plugin/test/build.js:69]: Looks like a good idea in general 👍🏻

File: packages/dependency-extraction-webpack-plugin/README.md [hunk 4]
```diff
@@ -116,6 +116,13 @@ module.exports = {
 
 The output format for the generated asset file. There are two options available: 'php' or 'json'.
 
+##### `outputFilename`
```
Comment (gziolo) [inline packages/dependency-extraction-webpack-plugin/README.md:110]: With this new option proposed `combinedOutputFile` plays a nearly identical role. At some point, we might want to deprecate `combinedOutputFile` and consolidate the handling in `outputFilename`.

**Review by gziolo — COMMENTED** [review]
@slightlyfaulty left a comment on the https://github.com/WordPress/gutenberg/issues/24352 confirming that this PR  fixes the issue. I went through the proposed changes and they look good. All the newly added unit tests bring a lot of value. I think we can proceed with merging those changes as soon as the PR gets rebased with `trunk` and all conflicts are resolved. @stefanfisk, thank you for keeping this PR opened for so long.

**Review by gziolo — APPROVED** [review]

**Comment by gziolo** [comment]
@stefanfisk, thas was quick! CI checks are still green which means we are good to go 🎉

**Comment by stefanfisk** [comment]
@gziolo maintaining a local copy of the plugin in my site repos has been a thorn in my side for over a year now (npm keeps installing webpack 4 and 5 at the same time when I least expect it).

At this point I am not missing any chance of getting this merged 😸

**Comment by stefanfisk** [comment]
I'm not clear on the release schedule for the packages, do you have any idea of when this PR will be available?

**Comment by gziolo** [comment]
It's hard to tell because the WordPress 5.9 release was moved to January 25th: https://make.wordpress.org/core/2021/11/22/wordpress-5-9-revised-release-schedule/. We are now in feature freeze mode and the @noisysocks (the editor tech lead for WordPress 5.9 release) manually cherry-picks only bug fixes to the branch that is used for npm releases. It all depends on when he decides to create a `wp/5.9` branch so we could get back to the regular cadences of releasing changes every two weeks. I plan to propose a revised approach for the next major WordPress releases starting from 6.0, so we can continue doing more regular npm publishing from `trunk`.

**Comment by sirreal** [comment]
Thanks for the work on this @stefanfisk and especially thank you for your patience and perseverance ❤️

**Comment by noisysocks** [comment]
> It all depends on when he decides to create a wp/5.9 branch so we could get back to the regular cadences of releasing changes every two weeks. I plan to propose a revised approach for the next major WordPress releases starting from 6.0, so we can continue doing more regular npm publishing from trunk.

I'll stick to the documented process which is to branch `wp/trunk` → `wp/5.9` at the time of WP 5.9 RC 1 (January 4). I think best not to tinker with our processes mid-release. Agree that we ought to revise it for future releases though.

**Comment by jsnajdr** [comment]
Hi @stefanfisk :wave: I noticed this PR now, long after it was merged, when working on something else in the dependency extraction plugin, and I wanted to ask: how does a practical project that runs into this issue look like?

Suppose there is a project that produces two entrypoint scripts, `a.js` and `b.js`, and also an entrypoint script, `runtime.js`, and the dependency extraction plugin produces two asset files, `a.asset.php` and `b.asset.php`. Who consumes such a project and how? How are the scripts delivered and executed? If I use the [documented](https://github.com/WordPress/gutenberg/blob/trunk/packages/dependency-extraction-webpack-plugin/README.md#wordpress) way to enqueue the scripts in WordPress, then only the `a.js` and `b.js` scripts will ever be enqueued, but PHP doesn't know about the `runtime.js`, because no `.asset.php` file mentions it. The code will likely fail, because part of it is missing.

So, if it's not WordPress enqueuing the scripts in a standard way, who else cares about the `.asset.php` files?

A similar issue will arise if there are two entrypoints that have any shared chunk in common, not just runtime. To load the entrypoint, the consumer is supposed to load 2+ JS files, but any `.assets.php` currently mentions only one.

**Comment by gziolo** [comment]
@jsnajdr, the interesting part is that I was exploring using `optimization.runtimeChunk` set to `single` in the context of React Fast Refresh which needs it to work correctly with multiple entry points. See my comment for more details https://github.com/WordPress/gutenberg/issues/25188#issuecomment-1104898123. I included how my `build` folder looked like during testing and indeed it didn't care to create an asset file for `runtime.js` nor mark it as a dependency:

**Comment by stefanfisk** [comment]
@jsnajdr I already had my own script loader that parsed a JSON manifest generated by `webpack-bundle-analyzer`, so I was only using the `*.asset.php` files for getting the WordPress dependencies. I gave it a go, but I couldn't figure out any way of getting the equivalent functionality without using `dependency-extraction-webpack-plugin`.

The reason for using the custom script loader was that I was splitting the npm deps from the main bundle to minimize the impact of doing deploys that modified the site's JS code (which I was doing almost daily at the time).

**Comment by jeffpaul** [comment]
@stefanfisk checking back to see if you can confirm your WordPress.org username so we can ensure you are properly credited in the WordPress 6.0 release coming out on May 24th. You can use the links above or share information directly with me and I'll ensure it's included correctly within the release. And thanks again for your contribution, it's greatly appreciated!

**Comment by stefanfisk** [comment]
@jeffpaul done!

**Comment by jsnajdr** [comment]
Thanks @stefanfisk, that helps me a lot. In other words, you were looking at the `asset.php` files only to learn what are an entrypoint's external dependencies, and that info is indeed reliable. But if the entrypoint has two or more chunks, like it always has with a shared runtime chunk, the `asset.php` file won't tell you that you need to load the runtime script, too. But you are getting the information from another source. That explains everything :+1:

**Comment by stefanfisk** [comment]
@jsnajdr I'm no longer using this code, so I'm not sure if it works, but here's a gist describing exactly how it all worked: https://gist.github.com/stefanfisk/bb4e045f3d15829a377916dc5fee9acc

Feel free to use it as you wish.

**Comment by jsnajdr** [comment]
> here's a gist describing exactly how it all worked

Thanks, that gist shows very well the shortcomings of the current `asset.php` files. The gist has 300 lines of code, while ideally it would be 7 lines like this:
```php
$assets = require( "$dir/assets.php" );
foreach ( $assets['scripts'] as $script ) {
  wp_enqueue_script( $script['handle'], $script['src'], $script['deps'], $script['ver'] );
}
foreach ( $assets['styles'] as $style ) {
  wp_enqueue_style( $style['handle'], $style['src'], $style['deps'], $style['ver'] );
}
```

**Comment by gziolo** [comment]
> > here's a gist describing exactly how it all worked
> 
> Thanks, that gist shows very well the shortcomings of the current `asset.php` files. The gist has 300 lines of code, while ideally it would be 7 lines like this:
> 
> ```
> $assets = require( "$dir/assets.php" );
> foreach ( $assets['scripts'] as $script ) {
>   wp_enqueue_script( $script['handle'], $script['src'], $script['deps'], $script['ver'] );
> }
> foreach ( $assets['styles'] as $style ) {
>   wp_enqueue_style( $style['handle'], $style['src'], $style['deps'], $style['ver'] );
> }
> ```

That's a simplified version because you don't want always to enqueue all those assets, but I agree on a principle that it would be great to have a way to register (`wp_register_script` or `wp_register_style`) all of them this way.

**Comment by jsnajdr** [comment]
> That's a simplified version because you don't want always to enqueue all those assets

Not sure what you mean, because in general I need to enqueue all the scripts that webpack produced? There are some additional assets like sourcemaps or `.LICENCE.txt` files, but if something is a script or style, it needs to be there.

**Comment by gziolo** [comment]
> > That's a simplified version because you don't want always to enqueue all those assets
> 
> Not sure what you mean, because in general I need to enqueue all the scripts that webpack produced? There are some additional assets like sourcemaps or `.LICENCE.txt` files, but if something is a script or style, it needs to be there.

It might be correct for your use case. In general, when you have multiple entry points you might want to consume only a subset of them on different pages. That's why I suggested that you register all assets but enqueue only the entry points when necessary and WP would pick all dependencies out of the box.

**Comment by stefanfisk** [comment]
A basic example is splitting editor assets from frontend assets.

**Comment by jsnajdr** [comment]
> That's why I suggested that you register all assets but enqueue only the entry points when necessary and WP would pick all dependencies out of the box.

I see, there can be a big project with multiple entrypoints and it always registers all its assets, but when requesting "please enqueue stuff for entrypoint `a`," it will enqueue only a subset.

**Comment by jsnajdr** [comment]
I created #41002 where I'm trying to solve some issues discussed here.
