### PR TITLE
Site Editor: Fix template resolution for templates assigned as home page

### LINKED ISSUE #56267: Site Editor: Static homepage not connected to the Front Page template
Discovered in https://github.com/WordPress/gutenberg/issues/56244

The Front Page template will always resolve to display the homepage, regardless of whether reading settings dictate that it should display latest posts or a static page (see the [template hierarchy](https://developer.wordpress.org/files/2014/10/Screenshot-2019-01-23-00.20.04.png) for more info). 

However, if you set a static homepage, and Front Page exists, the Site Editor doesn't make this connection, and even tells you that an incorrect template is used when you view and edit that page. The post editor works as expected. 

Here's a video that hopefully demonstrates the issue clearly:

https://github.com/WordPress/gutenberg/assets/846565/709682b4-2c74-4e44-80f5-eeff5f11d114

To reproduce:

1. In reading settings select a static homepage
2. In the Site editor create a Front Page template (if one doesn't already exist)
3. Navigate to Pages > [your static homepage] and notice that Front Page isn't listed as the template in the details panel
4. Edit [your static homepage] and notice that Front Page isn't listed as the template in the Inspector

### PR DESCRIPTION
**Pull request by youknowriad**
closes #56267 
Alternative to #56326 

## What

If a page was set as "static home page", and you had a "front page" template on your theme, this template was not being picked as the template to use for your home page, instead we were always using the default "page" template regardless of whether that template exited.

This PR fixes that by checking for the existence of the front page template if the page that we're resolving is the one set as "fixed home page".

## Why?

I initially tried to solve this problem by relying on a server API to resolve the template, the problem is that unsaved user changes might impact the resolved template and we do want to reflect these changes in the site editor.

## Testing Instructions

1- Create a random page and use it as "static home page" in your "reading" settings
2- Ensure that you have a front page template on your theme
3- Open the site editor: The front page template should be loaded for your page.

### CODE REVIEW

**Comment by draganescu** [comment]
I probably am missing how it should work. What I did:

- on a site that had its reading settings set as Your homepage displays 	- Your latest posts 
- I changed that to be a page P
- I went to the site editor > Templates
- Created a homepage template
- I went to page P and it was still using the Pages template
- I tried to swap and the front page template didn't show

How should I actually test this?

File: packages/edit-site/src/components/sync-state-with-url/use-init-edited-entity-from-url.js [hunk 1]
```diff
@@ -62,6 +87,22 @@ function useResolveEditedEntityAndContext( { postId, postType } ) {
 				postTypeToResolve,
 				postIdToResolve
 			) {
+				// For the front page, we alwayse use the front page template if existing.
```
Comment (ramonjd) [inline packages/edit-site/src/components/sync-state-with-url/use-init-edited-entity-from-url.js]:
```suggestion
				// For the front page, we always use the front page template if existing.
```

I can help it. It's a sickness.

File: packages/edit-site/src/components/sync-state-with-url/use-init-edited-entity-from-url.js [hunk 2]
```diff
@@ -62,6 +87,22 @@ function useResolveEditedEntityAndContext( { postId, postType } ) {
...
+				) {
+					// We're still checking whether the front page template exists.
+					// Don't resolve the template yet.
+					if ( frontPageTemplateId === undefined ) {
+						return undefined;
+					}
+
+					if ( !! frontPageTemplateId ) {
+						return frontPageTemplateId;
+					}
```
Comment (ramonjd) [inline packages/edit-site/src/components/sync-state-with-url/use-init-edited-entity-from-url.js:103]: Are there any other values that `frontPageTemplateId` could be other than `undefined|string`? 

Could we just `return frontPageTemplateId;` without the two `if`s?

**Review by ramonjd — DISMISSED** [review]
Would be good to get a second review, but this works nicely for me, and now allow us to edit the template of a page that has been set as "home" in the reading settings.


https://github.com/WordPress/gutenberg/assets/6458278/13210d95-cff8-4046-92fe-99616fc1409d

Thanks!!

> I tried to swap and the front page template didn't show

_Edit_: I didn't see @draganescu's comment:

Here, I'm editing the front page's template, but nothing apparent happens. What it's doing however, is changing the template of my static home page (set in reading settings)


https://github.com/WordPress/gutenberg/assets/6458278/65933058-b3a6-4ecd-bdbc-912058a3140e

File: packages/edit-site/src/components/sync-state-with-url/use-init-edited-entity-from-url.js (hunk 2 above)
Comment (andrewserong) [reply packages/edit-site/src/components/sync-state-with-url/use-init-edited-entity-from-url.js:103]: Further up in the `useSelect` the value `false` is used to denote that no templates match the front page template. In this case, a page is set to be the front page, but there's no front page template, so these two if statements (and early returns) should be skipped, with the rest of this function continuing to execute to find the right template to use.

I _think_ that's what's happening, anyway!

**Review by andrewserong — COMMENTED** [review]
This feels closer to me, thanks for the follow-up:

| Trunk (uses Pages template) | This PR (uses Front Page template) |
| --- | --- |
| image | image |

I also ran into a bit of friction using the Template controls. Perhaps since we know that when accessing the root of the site editor in this way, where the template is forced to override whatever is set at the page level, we could disable the control to Swap Template from this view (at the root of the site, versus explicitly editing that page), possibly with an info icon or something to hover over that flags that the front page template is fixed in position due to what's set under Reading settings? Otherwise I can imagine folks getting confused, as it looks like you can change which template you're using, but you can't _really_ do that, since it's being overwritten.

Hope that all makes sense, I've tried rewriting that paragraph a couple times, but it still reads in a jumbled way 😅! Here's a screengrab of what I'm seeing for a user who attempts to switch templates when accessing the site editor when a page is set to front page and a front page template exists:

https://github.com/WordPress/gutenberg/assets/14988353/618a0065-1caf-46f3-9c11-396a563dacab

In the above screengrab, it _looks_ like you can change the template, and the Swap Template modal seems to reflect that you have (for that particular page), but the UI always shows "front page" since it's (correctly) being overwritten. In this case, this is where I'm wondering if the Swap Template option should be disabled with a note that it's locked due to the Reading setting.

**Comment by andrewserong** [comment]
> I went to page P and it was still using the Pages template

Ah, I see — looks like it's different behaviour when we go to access the page via the Pages menu, too (versus the root of the site editor). Perhaps it should be consistent there as well, since the URL for the page winds up pointing to the root of the site, anyway, once we set a page to front page?

File: packages/edit-site/src/components/sync-state-with-url/use-init-edited-entity-from-url.js (hunk 1 above)
Comment (youknowriad) [reply packages/edit-site/src/components/sync-state-with-url/use-init-edited-entity-from-url.js]: I can't help but make mistakes :P

**Comment by youknowriad** [comment]
> Swap Template from this view (at the root of the site, versus explicitly editing that page), possibly with an info icon or something to hover over that flags that the front page template is fixed in position due to what's set under Reading settings? Otherwise I can imagine folks getting confused, as it looks like you can change which template you're using, but you can't really do that, since it's being overwritten.

Yeah, I noticed that too and I kind of wanted it to be a follow-up but I'll see if I can hide the swap or something quickly.

> Ah, I see — looks like it's different behaviour when we go to access the page via the Pages menu, too (versus the root of the site editor). Perhaps it should be consistent there as well, since the URL for the page winds up pointing to the root of the site, anyway, once we set a page to front page?

Yes, this should be consistent, I'll take a look.

**Comment by jameskoster** [comment]
Something doesn't seem to be working correctly for me. Static homepage is set, Front Page exists, I'm still seeing the `page` template applied to the static homepage 🤔 


https://github.com/WordPress/gutenberg/assets/846565/15e9ac36-6c46-4844-b341-d358dc811916

**Comment by youknowriad** [comment]
@jameskoster it should be fixed (string to number comparison)

**Comment by jameskoster** [comment]
Works now 👍 

I noticed another issue; in the Inspector for the static homepage, if you toggle off the template preview the menu item vanishes so you cannot toggle it back on again:


Screenshot 2023-11-23 at 11 16 35

**Comment by youknowriad** [comment]
> I noticed another issue; in the Inspector for the static homepage, if you toggle off the template preview the menu item vanishes so you cannot toggle it back on again:

yes, this is the same issue I mentioned in the original PR (if there's no post blocks in the front page template outside query loop). It's an issue that exists in trunk and that will be fixed separately.

**Review by ntsekouras — APPROVED** [review]
LGTM, thanks!

**Review by andrewserong — COMMENTED** [review]
Nice fix, thanks for the follow-up!
