### PR TITLE
Fix issue of HTML entities rendering in command menu

### LINKED ISSUE #62603: HTML entities rendering in command titles rather than characters
### Description:

When searching for commands containing apostrophes or similar characters, the search results display HTML entities instead of the proper characters. For example, “Test’s” is shown as “Test’s”.

### Expected:

The search results should display the text with properly rendered apostrophes and related characters.

### Actual:

The search results display HTML entities for apostrophes and related characters.

### Step-by-step reproduction instructions

1.	Open the search bar.
2.	Type a query containing an apostrophe (e.g., “Test’s”).
3.	Observe the search results.

### Screenshots, screen recording, code snippet

CleanShot 2024-06-16 at 15 46 37

### Environment info

WordPress trunk
Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by amitraj2203**
## What?
Fixes: #62603

## Why?
When searching for commands containing apostrophes or similar characters, the search results display HTML entities instead of the proper characters. For example, `Test’s &` is shown as `Test &#8217;s &amp;`.

## Screenshots or screencast 
Before:
image

After:
image

### CODE REVIEW

File: packages/commands/src/components/command-menu.js [hunk 1]
```diff
@@ -62,7 +63,7 @@ function CommandMenuLoader( { name, search, hook, setLoader, close } ) {
 						{ command.icon && <Icon icon={ command.icon } /> }
 						<span>
 							<TextHighlight
-								text={ command.label }
+								text={ decodeEntities( command.label ) }
```
Comment (youknowriad) [inline packages/commands/src/components/command-menu.js]: For me, this feels like the wrong place to decode entities. Commands can come from anywhere and the entities might already be correct here and we should avoid double decoding. So maybe do this call in the place that actually registers the faulty commands.

**Review by youknowriad — COMMENTED** [review]
Thanks for the PR. I left a small comment.

File: packages/commands/src/components/command-menu.js (hunk 1 above)
Comment (amitraj2203) [reply packages/commands/src/components/command-menu.js]: Thanks for the review. Can we call it [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/core-commands/src/site-editor-navigation-commands.js#L96) as it will decode the entities for page/posts?

For example: ⬇️ 

```diff
diff --git a/packages/core-commands/src/site-editor-navigation-commands.js b/packages/core-commands/src/site-editor-navigation-commands.js
index ba34fffd988..1b6de1293c9 100644
--- a/packages/core-commands/src/site-editor-navigation-commands.js
+++ b/packages/core-commands/src/site-editor-navigation-commands.js
@@ -25,6 +25,7 @@ import { useDebounce } from '@wordpress/compose';
 import { useIsBlockBasedTheme } from './hooks';
 import { unlock } from './lock-unlock';
 import { orderEntityRecordsBySearch } from './utils/order-entity-records-by-search';
+import { decodeEntities } from '@wordpress/html-entities';
 
 const { useHistory } = unlock( routerPrivateApis );
 
@@ -93,7 +94,7 @@ const getNavigationCommandLoaderPerPostType = ( postType ) =>
 					name: postType + '-' + record.id,
 					searchLabel: record.title?.rendered + ' ' + record.id,
 					label: record.title?.rendered
-						? record.title?.rendered
+						? decodeEntities( record.title?.rendered )
 						: __( '(no title)' ),
 					icon: icons[ postType ],
 				};

```

Comment (youknowriad) [reply packages/commands/src/components/command-menu.js]: yes, that looks like a good place to me.

Comment (amitraj2203) [reply packages/commands/src/components/command-menu.js]: Thanks, I have made the changes accordingly.

File: packages/core-commands/package.json [hunk 2]
```diff
@@ -34,6 +34,7 @@
 		"@wordpress/core-data": "file:../core-data",
 		"@wordpress/data": "file:../data",
 		"@wordpress/element": "file:../element",
+		"@wordpress/html-entities": "file:../html-entities",
```
Comment (youknowriad) [inline packages/core-commands/package.json:37]: I think you need to do `npm install` after this change.

**Review by youknowriad — APPROVED** [review]

File: packages/core-commands/package.json (hunk 2 above)
Comment (amitraj2203) [reply packages/core-commands/package.json:37]: Done.

**Comment by ellatrix** [comment]
Should this be backported to 6.6?

**Comment by amitraj2203** [comment]
@youknowriad Should we go ahead and merge it?

**Comment by youknowriad** [comment]
@amitraj2203 yes, you have the rights to merge no? I see that some tests didn't run, maybe you need to rebase the PR first.

**Comment by amitraj2203** [comment]
> @amitraj2203 yes, you have the rights to merge no? I see that some tests didn't run, maybe you need to rebase the PR first.

I rebased it. Don't know why PHP unit tests are failing since this PR didn't touched any PHP

**Comment by youknowriad** [comment]
I'm trying to restart one last time but yeah it looks independent to this PR, maybe network related or something in the different docker repositories we use. (docker, linux...)

**Comment by youknowriad** [comment]
Just a small reminder for the next time you merge PRs to include the props in the commit message https://github.com/WordPress/gutenberg/pull/62606#issuecomment-2171813555

**Comment by amitraj2203** [comment]
Sure 😄
