### PR TITLE
Gallery: Fix missing captions shortcode transform

### LINKED ISSUE #30698: Classic Gallery conversion to Block Gallery is not done fully.
## Description
When converting from Classic Gallery to Block Gallery the converted Gallery is missing the captions i wrote for images and image size selection, which was available in Classic post.

## Step-by-step reproduction instructions
1. Go to post in backend.
2. Click on Edit (Block Editor)
3. The post appear in editor.
4. then i select the classic content.
5. and then i press Convert to Blocks.
6. after this convert is done with missing image Captions i wrote and Size selection of images.

## Expected behavior
The expected result is that everything works as it was with Classic post editor.

## Actual behavior
The converted Gallery is missing the caption i wrote and image size selection.

## Screenshot
Screenshot (2513)

## WordPress information
- WordPress version: 5.7
- Gutenberg version: it comes with last WP

- Are all plugins except Gutenberg deactivated? = "No"
- Are you using a default theme (e.g. Twenty Twenty-One)? = "No" GeneratePress last version.

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Epic based on Chromium 84.0

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes #30698.
Alternative to #73744.

PR fixes the condition in `buildImageAttributes` so it correctly falls back to the image caption from the media library. This prevents captions from being lost when transforming the gallery shortcode into a block.

## Why?
The `imageAttributes.caption` has the `rich-text` type, which uses the `RichTextData` object internally; therefore, the previous fallback value was never used.

When working with `RichTextData`, it's better to use `value.length` check or other RichText data methods.

## Testing Instructions
1. Open a post or page.
2. Insert a classic block and add a gallery to it.
3. Ensure at least some images have captions.
4. Convert Classic to Blocks.
5. Confirm that images in the gallery block have captions.

### Testing Instructions for Keyboard
Same.

## Screenshots or screencast 

https://github.com/user-attachments/assets/92586309-b405-49b6-b763-0dcda55f1d88

### CODE REVIEW

**Comment by youknowriad** [comment]
What about the frontend?

**Comment by youknowriad** [comment]
Also more importantly, how do I unset a caption.

**Comment by Mamaduka** [comment]
> What about the frontend?

Captions will be displayed on the front-end after the shortcode is converted and saved.

> Also more importantly, how do I unset a caption.

What do you mean? If you delete the caption and save the post, it's unset.

Give it a test. After conversions, everything works as a standard Gallery block.

File: packages/block-library/src/gallery/edit.js [hunk 1]
```diff
@@ -290,7 +290,10 @@ export default function GalleryEdit( props ) {
 			...newLinkTarget,
 			className: newClassName,
 			sizeSlug,
-			caption: imageAttributes.caption || image.caption?.raw,
+			caption:
+				imageAttributes.caption.length > 0
+					? imageAttributes.caption
+					: image.caption?.raw,
```
Comment (youknowriad) [inline packages/block-library/src/gallery/edit.js:296]: I misunderstood the fix originally, so this function is triggered on each "transform", I thought it was during the rendering of the gallery/image. It's unclear because it's defined in "edit"

**Comment by youknowriad** [comment]
Ok this works great :)

**Review by youknowriad — APPROVED** [review]

File: packages/block-library/src/gallery/edit.js (hunk 1 above)
Comment (Mamaduka) [reply packages/block-library/src/gallery/edit.js:296]: Yeah, we should probably clean this up a bit and add clearer comments on when `newImages` gets a value.

P.S. I remembered a similar PR when checking the issue, which gave me the clue - #42001 😄

**Comment by andrewserong** [comment]
Oh, nice fix, thanks for handling this!
