### PR TITLE
Fix paste after focus

### LINKED ISSUE #15724: RichText: copy paste inside same field sometimes duplicates text
**Describe the bug**

Sometimes when I copy and paste a piece of text within the same RichText instance, the rest of the text is duplicated. I'm not sure what the cause of this is, I'll need to investigate it later. Just creating this ticket so I don't forget about it. Perhaps others have experienced the same.

Gutenberg v5.7 on Mac n Chrome

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #15724.

This is a small fix for the bug that duplicates the rich text contents after pasting in a rich text instance that just received focus.

## How has this been tested?

Copy a small amount of text.
Open the Gutenberg demo content.
Place the caret at the end of the first paragraph.
Move selection out of the window: e.g. place the caret in the address bar.
Place the caret again at the end of the first paragraph.
Now paste the text.
No content should be duplicated.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/rich-text/src/component/index.js [hunk 1]
```diff
@@ -300,6 +301,12 @@ class RichText extends Component {
 		this.props.onSelectionChange( index, index );
 		this.setState( { activeFormats } );
 
+		// Update selection as soon as possible, which is at the next animation
+		// frame. The event listener for selection changes may be added too late
+		// at this point, but this focus event is still too early to calcutate
+		// the selection.
```
Comment (kadamwhite) [inline packages/rich-text/src/component/index.js]: Small typo: “calculate”

Comment (gziolo) [reply packages/rich-text/src/component/index.js]: Fixed in 9cb57e40d41adfc203aaa089926b5d6822744beb 👍

**Review by gziolo — APPROVED** [review]
I tested the exact same action as posted in the issue and I could reproduce it on `master` but not in this branch. Great change 💯 

I tested pasting at the beginning, in the middle and at the end of the Paragraph block. Tried also with Heading and List blocks.

**Comment by ellatrix** [comment]
I’ll attempt to create an e2e test in just a bit. Thanks for the review!

**Comment by gziolo** [comment]
> I’ll attempt to create an e2e test in just a bit. Thanks for the review!

Sounds great, I merged this change as I want to play again with Puppeteer upgrade and this might h (or not) elp with some of the intermittent issues :)

**Comment by ellatrix** [comment]
It doesn't seem possible to me to create an e2e test for this fix.

```js
	it.only( 'should update internal selection after fresh focus', async () => {
		await page.keyboard.press( 'Enter' );
		await page.keyboard.type( '1' );
		// Focus the address bar (move focus out of the window).
		await pressKeyWithModifier( 'primary', 'l' );
		// Focus the rich text instance again (not at the start).
		await page.click( '.wp-block-paragraph', { button: 'middle' } );
		// Should internally set bold at selection.
		await pressKeyWithModifier( 'primary', 'b' );
		// "2" should be bold.
		await page.keyboard.type( '2' );

		expect( await getEditedPostContent() ).toMatchSnapshot();
	} );
```

Doing this this manually fails, but in Puppeteer it succeeds. :)
Perhaps in some cases the `selectionchange` event is triggered, I'm not sure.

**Comment by ellatrix** [comment]
Blurring the element seems to trigger it to fail. And it succeeds with this branch. Yay!

**Comment by ellatrix** [comment]
@gziolo I doubt it will fix the intermittent failures. Puppeteer won't wait for an animation frame. Let me think about that. :D
