### PR TITLE
Fix loss of focus when navigating from a multi selection

### LINKED ISSUE #4605: Unexpected focus transition when arrow up/down from focused multi-selection
## Issue Overview

After creating a multi-selection, focus is transitioned to the multi-selection controls. If the user then proceeds to press Up/Left or Down/Right on their keyboard, focus is transitioned to an unexpected field on the page.

## Steps to Reproduce

1. Create a post with 4 paragraph blocks

_Move Down:_

1. Focus the first paragraph block
2. Shift-Down to create a multi-selection
3. Press Down

_Move Up:_

1. Focus the last paragraph block
2. Shift-Up to create a multi-selection
3. Press Up

## Expected Behavior

In the _Move Down_ case, either the focused multi-control menu should open, or at the very least, the block immediately following the multi-selection is focused.

In the _Move Up_ case, either the focused multi-control menu should open, or the block immediately preceding the multi-selection is focused.

## Current Behavior

In the _Move Down_ case, the very last block is focused.

In the _Move Up_ case, the title field is focused.

## Possible Solution

Maybe a default behavior of WritingFlow to try to iterate over focusables, running out of options, and using the last available focusable in the desired direction as the focus target?

## Video

multi-select

### PR DESCRIPTION
**Pull request by noisysocks**
### ⭐️ What this is

Fixes #4605.

multi-selection

When there is a active multi selection and the user navigates with the keyboard (e.g. presses UP or DOWN), the focus should move to the next or previous block. Previously the focus was lost entirely.

### 🤓 How this works

This bug occurred because, when there is a multi selection, the target DOM node (i.e. the node that triggers the key down event) is the block's More Options toggle button. Since this button is not listed in `getVisibleTabbables()`, `getClosestTabbable()` does not correctly return the editable element that is above or before the selection.

I looked at patching `getClosestTabbable()` to accomodate for this case, but it's difficult since the More Options button is not a descendant of an editable element.

Instead, I added code to `WritingFlow` that explicitly handles moving from a multiple block selection to a single block selection . This matches the code that we already have that handles the inverse case.

### ✅ How to test

1. Create a post with 4 paragraph blocks

_Move Down:_

1. Focus the first paragraph block
2. Shift-Down to create a multi-selection
3. Press Down
4. The focus should move to the third block

_Move Up:_

1. Focus the last paragraph block
2. Shift-Up to create a multi-selection
3. Press Up
4. The focus should move to the second block

### CODE REVIEW

File: editor/components/writing-flow/index.js [hunk 1]
```diff
@@ -140,6 +140,12 @@ class WritingFlow extends Component {
 		this.props.onMultiSelect( currentStartUid, blocks[ nextIndex ] );
 	}
 
+	moveSelection( blocks, currentUid, delta ) {
+		const currentIndex = blocks.indexOf( currentUid );
+		const nextIndex = Math.max( 0, Math.min( blocks.length - 1, currentIndex + delta ) );
```
Comment (mcsf) [inline editor/components/writing-flow/index.js]: Minor: could use `lodash#clamp`.

**Review by mcsf — APPROVED** [review]
LGTM!

File: editor/components/writing-flow/index.js (hunk 1 above)
Comment (noisysocks) [reply editor/components/writing-flow/index.js]: TIL! Changed in 548d23115c5432ce0ec37371943108187b4d038c.
