### PR TITLE
Fix focus return when closing the Post publish panel

### LINKED ISSUE #45417: Publish sidebar focus loss and modal behavior
### Description

When using the keyboard and closing the publish sidebar, focus is lost. 

A focus loss is a very confusing and frustrating experience for keyboard users, as they are forced to  start navigating the user interface from the beginning of the document.

Also, tabbing with the Tab key is constrained within the publish sidebar, which is good. However, screen reader users can navigate outside the sidebar by arrowing or by using other screen readers navigation mechanisms. If we want all users to stay within the publish sidebar while they're in the publishing flow, the sidebar should have a modal behavior. This can be accomplished by adding an `aria-modal=true` attribute.

### Step-by-step reproduction instructions

Test 1:
- Edit a post draft or create a new one.
- Navigate to the Publish button by using the keyboard Tab key.
- Press Enter to open the Publish sidebar.
- Press Tab to move to the Cancel button and press Enter.
- The Publish sidebar closes.
- Press the Tab key again and observe focus is now on the browser interface.
- See the first animated GIF that illustrates the focus loss. 

Test 2:
- Edit a post draft or create a new one.
- Navigate to the Publish button by using the keyboard Tab key.
- Press Enter to open the Publish sidebar.
- Press Enter again to Publish the post. 
- The sidebar switches to the 'post publish' flow. Focus is now on the link to view the post.
- Press Shift + Tab to move to the 'Close panel' X button. Press Enter to close the sidebar.
- Press the Tab key again and observe focus is now on the browser interface.
- See the first animated GIF that illustrates the focus loss. 

Test 3, Optional:
- Use a screen reader e.g. VoiceOver with Safari on macOS.
- Navigate using the keyboard and press the Publish button to open the Publish sidebar.
- Press Tab multiple times to navigate within the sidebar and observe tabbing is constrained within the sidebar, so far so good.
- Use the screen reader arrow keys navigation *with VoiceOver it's Control+Option+Right arrow or Control+Option+Left arrow).
- Observe with arrows navigation you can navigate away from the Publish sidebar.

### Screenshots, screen recording, code snippet

Test 1 animated GIF:

focus-loss

Test 2 animated GIF:

focus-loss2

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by afercia**
Fixes https://github.com/WordPress/gutenberg/issues/45417

## What?

When closing the Post publish panel, focus is supposed to be moved back to the Publish button within the top bar. This is broken since a while, probably since the refactoring of `withFocusReturn` to use React hooks. The root cause is a timing issue. This PR seeks to solve it avoiding major refactoring.

## Why?

A focus loss is a frustrating experience for all keyboard users as they are forced to start keyboard navigation again from the document root.

## How?

To my understanding:
- When the publish panel opens, `PostPublishButton` sets focus on the Publish button _within_ the panel. It does that on `componentDidMount`.
- After that,`withFocusReturn` (which internally uses `useFocusReturn`) checks what the `document.activeElement` is. Actually, this is now the Publish button _within_ the panel, while `useFocusReturn` is supposed to get the element that was focused _before_ the panel opens (the Publish button within the top bar).
- When closing the Publish panel, `withFocusReturn` tries to set focus on the wrong button thus there's a focus loss.

Basically, it appears that the `useFocusReturn` hook can't work well with class components that manage focus internally with `componentDidMount`. In fact, `useEffect` runs after `componentDidMount` and at that point the `document.activeElement` is not the expected one. 

Instead of refactoring `PostPublishButton`, this PR just makes sure that `PostPublishButton` sets focus at a later time so that `withFocusReturn` gets the correct button.

- Added two Playwright tests.
- Fixed what appears to be a typo in the publishPost Playwright utility. /Cc @kevin940726 @tellthemachines could you please check this, when you have a chance? 🙏 

## Testing Instructions

- Make sure the `Options > Preferences > Include pre-publish checklist` preference is enabled.
- Create a new post, add some content, and click the Publish button within the top bar.
- The Publish panel opens.
- Click the Cancel button within the panel.
- The Publish panel closes.
- Check focus is moved back to the Publish button within the top bar.
- Click the Publish button within the top bar again.
- The Publish panel opens.
- Click the Publish button within the panel.
- Wait for the Post to be published.
- The post-publish panel appears.
- Click the X button at the top right of the post-publish panel to close it.
- Check focus is moved back to the Update button within the top bar.

Optionally:
- Run the 2 new tests with `npm run test:e2e:playwright -- --headed editor/various/publish-panel.spec.js`
- See the tests pass.
- Revert the changes to `PostPublishButton`.
- Run the 2 new tests again and see they fail.

### CODE REVIEW

**Comment by afercia** [comment]
For reference: previous PRs that refactored `withfocusreturn`:
- https://github.com/WordPress/gutenberg/pull/27572
- https://github.com/WordPress/gutenberg/pull/27705

The focus loss regression is present since WordPress 5.7, Gutenberg versions 9.3-9.9.

File: packages/e2e-test-utils-playwright/src/editor/publish-post.ts [hunk 1]
```diff
@@ -12,7 +12,7 @@ import type { Editor } from './index';
 export async function publishPost( this: Editor ) {
 	await this.page.click( 'role=button[name="Publish"i]' );
 	const publishEditorPanel = this.page.locator(
-		'role=region[name="Publish editor"i]'
+		'role=region[name="Editor publish"i]'
```
Comment (kevin940726) [inline packages/e2e-test-utils-playwright/src/editor/publish-post.ts:15]: Yep, I think this is a typo 😅 . It's causing the `isPublishEditorVisible` check always to return false. Thanks for fixing it!

**Review by alexstine — APPROVED** [review]
@afercia Thanks for the PR. That was certainly a sneaky bug.

**Comment by afercia** [comment]
Yep, and it was a bit tricky to debug. Thanks for the review.
