### PR TITLE
DataViews: Update actions menu structure to group primary and regular actions

### LINKED ISSUE #72840: DataViews: Update actions menu structure
| Before | After |
| --- | --- |
| Image | Image |

### Changes
* Group all primary actions at the top of the menu
* Introduce a divider between primary and regular actions
* Remove exception that applies custom order to trash actions

### Why
I suspect this will make the relationship between primary actions (which appear conditionally in table layout) and other actions a bit easier to reason about. Particularly now that primary actions are presented as text buttons.

### PR DESCRIPTION
**Pull request by hbhalodia**
## What?

Closes https://github.com/WordPress/gutenberg/issues/72840

## Why?
- To group primary and regular actions in DataViews table, list and grid.

## How?

- Group all primary actions at the top of the menu.
- Introduce a divider between primary and regular actions.

## Testing Instructions
1. Checkout to PR branch.
2. Open the site editor.
3. Go to DataViews, and check the actions.
4. The actions would be grouped together and would have a separator line.

### Testing Instructions for Keyboard
- None

## Screenshots or screencast 

|Before|After|
|-|-|
| Screenshot 2025-10-31 at 3 06 00 PM | Screenshot 2025-10-31 at 3 05 37 PM |

### CODE REVIEW

File: packages/dataviews/src/components/dataviews-item-actions/index.tsx [hunk 1]
```diff
@@ -132,22 +132,45 @@ export function ActionsMenuGroup< Item >( {
...
+			( action ) => ! action.isPrimary
+		);
+
+		return {
+			primaryActions: _primaryActions,
+			regularActions: _regularActions,
+		};
+	}, [ actions ] );
+
+	const handleActionClick = ( action: Action< Item > ) => () => {
```
Comment (ntsekouras) [inline packages/dataviews/src/components/dataviews-item-actions/index.tsx]: Nit: why move this to a different const?

File: packages/dataviews/src/components/dataviews-item-actions/index.tsx [hunk 2]
```diff
@@ -132,22 +132,45 @@ export function ActionsMenuGroup< Item >( {
 	registry,
 	setActiveModalAction,
 }: ActionsMenuGroupProps< Item > ) {
+	const { primaryActions, regularActions } = useMemo( () => {
+		const _primaryActions = actions.filter(
```
Comment (ntsekouras) [inline packages/dataviews/src/components/dataviews-item-actions/index.tsx]: Nit: we could use `reduce` to iterate over the actions once.

**Review by ntsekouras — COMMENTED** [review]
Thanks! This LGTM, but I'd appreciate a quick look from @oandregal, since it's been a while I worked on this part.

File: packages/dataviews/src/components/dataviews-item-actions/index.tsx (hunk 1 above)
Comment (hbhalodia) [reply packages/dataviews/src/components/dataviews-item-actions/index.tsx]: This is updated.

File: packages/dataviews/src/components/dataviews-item-actions/index.tsx (hunk 2 above)
Comment (hbhalodia) [reply packages/dataviews/src/components/dataviews-item-actions/index.tsx]: Updated to use the reduce.

**Comment by jameskoster** [comment]
Thanks! Looks good to me. 

Down the road I think we might want to _consider_ an additional `isDestructive` flag for actions, to position things like 'Move to trash' at the bottom of the menu, even when primary. Fine to tackle that separately though.

**Review by ntsekouras — APPROVED** [review]
Looks good, thanks!
