### PR TITLE
Image block: unwrap img element in editor

### LINKED ISSUE #38381: Custom Image sizes are not responsive in the editor
In the editor, by default, image blocks are 100% the width of their container, regardless of their actual dimensions. As soon as the user adds a custom width to their image however, that responsive guardrail is gone, and the image will flow off-screen.

https://user-images.githubusercontent.com/1202812/151834663-e36e3e72-1aa0-400d-b89a-3a620a665795.mp4

The max-width guardrail works on the frontend. The editor discrepancy appears to be related to the in-canvas resize handles ([see also](https://github.com/WordPress/gutenberg/issues/38381#issuecomment-1026689999)).

---

Tested with a clean install of WordPress 5.9.
[First reported over in the Twenty Twenty-Two support forums](https://wordpress.org/support/topic/images-are-not-responsive-3/).

### LINKED ISSUE #52219: Image block: Incorrect image width with aspect ratio in block editor
### Description

In the post editor, if you have an image block with an image that is smaller than the width of the post container and you specify an aspect ratio without selecting a width or height dimension, the image is incorrectly scaling up to fill the width of the container.

### Step-by-step reproduction instructions

Screenshots use https://github.com/WordPress/wordpress-develop/blob/62b286f9b2ebc7bb609827a09fcf5136cac5fa01/tests/phpunit/data/images/a2-small.jpg for testing.

1. Use the following image block content or create a block includes an aspect ratio (and scale), but no width or height.

```html
<!-- wp:image {"id":443,"aspectRatio":"3/4","scale":"cover","sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full"><img src="http://wp.local/wp-content/uploads/2023/06/a2-small.jpg" alt="" class="wp-image-443" style="aspect-ratio:3/4;object-fit:cover"/></figure>
<!-- /wp:image -->
```

3. See that the image fills the width of the editor instead of the width of the image.

### Screenshots, screen recording, code snippet

image-block-aspect-ratio-width-bug

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #67506: Image changes sizes upon selection
### Description 

When an image is selected within row or stack blocks, its size occasionally changes unpredictably. This issue disrupts the editing experience and makes alignment or sizing adjustments more challenging.

### Steps to reproduce

I also included the pattern below for testing. 

1.	Add a row or stack block to a page or post
2.	Insert an image block within the row or stack.
3.	Select the image block.
4.	Observe any unexpected size changes when the image is selected.

<details>
<summary>Here's the pattern (just add your own image to it)</summary>

```
<!-- wp:group {"metadata":{"categories":["link-in-bio"],"patternName":"assembler/link-in-bio-4","name":"Profile"},"align":"full","className":"is-style-section-3","style":{"spacing":{"padding":{"right":"var:preset|spacing|40","left":"var:preset|spacing|40","top":"var:preset|spacing|40","bottom":"var:preset|spacing|40"},"margin":{"top":"0","bottom":"0"},"blockGap":"0"},"elements":{"link":{"color":{"text":"var:preset|color|contrast"}}},"dimensions":{"minHeight":"100vh"}},"backgroundColor":"base","textColor":"contrast","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","flexWrap":"nowrap","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull is-style-section-3 has-contrast-color has-base-background-color has-text-color has-background has-link-color" style="min-height:100vh;margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--40);padding-right:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--40)"><!-- wp:columns {"verticalAlignment":"center","className":"alignfull","style":{"spacing":{"blockGap":{"top":"48px","left":"var:preset|spacing|50"}},"layout":{"selfStretch":"fit","flexSize":null}}} -->
<div class="wp-block-columns are-vertically-aligned-center alignfull"><!-- wp:column {"verticalAlignment":"center","width":"50%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:50%"><!-- wp:image {"id":29,"aspectRatio":"2/3","scale":"cover","sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full"><img src="https://themes.test/wp-content/uploads/2024/11/visualelectric-1729024953029-2.jpg" alt="" class="wp-image-29" style="aspect-ratio:2/3;object-fit:cover"/><figcaption class="wp-element-caption">Made with <a href="https://w.link/">w.link</a></figcaption></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","width":"50%","style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}}},"layout":{"type":"constrained","justifyContent":"left"}} -->
<div class="wp-block-column is-vertically-aligned-center" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0;flex-basis:50%"><!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:heading {"textAlign":"left","level":1,"fontSize":"x-large"} -->
<h1 class="wp-block-heading has-text-align-left has-x-large-font-size">田中愛子</h1>
<!-- /wp:heading -->

<!-- wp:spacer {"height":"16px","style":{"layout":[]}} -->
<div style="height:16px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>幼い頃から自然や文化に触れることが大好きで、カメラを手に旅に出るたびに新しい発見や感動があります。美しい景色だけでなく、その土地の歴史や人々の暮らし、隠れた魅力を探し出すことが私の喜びです。</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>私の目を通して見る世界の一端を感じていただければ幸いです。このブログでは、旅行ガイドとしての実用的な情報はもちろん、写真を楽しんでいただけるギャラリーもご用意しています。また、心に響いたエピソードや出会いもエッセイとして綴っています。</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>新しい冒険を探求し、皆さんのインスピレーションとなるようなストーリーをお届けすることを目指しています。一緒に世界の美しさを見つけましょう。</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>どうぞごゆっくりお楽しみください！</p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":"16px","style":{"layout":[]}} -->
<div style="height:16px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:social-links {"size":"has-normal-icon-size","className":"is-style-logos-only","style":{"spacing":{"blockGap":{"left":"8px"}}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"left"}} -->
<ul class="wp-block-social-links has-normal-icon-size is-style-logos-only"><!-- wp:social-link {"url":"#","service":"instagram"} /-->

<!-- wp:social-link {"url":"#","service":"x"} /-->

<!-- wp:social-link {"url":"#","service":"tumblr"} /-->

<!-- wp:social-link {"url":"#","service":"twitch"} /--></ul>
<!-- /wp:social-links --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->
```
</details>

### Expected

The image should maintain its size and proportions upon selection, ensuring a stable editing experience. 

### Visual 

https://github.com/user-attachments/assets/bd8f1d3e-6cd0-40be-bb57-0184933d41f7

### LINKED ISSUE #68057: Image in row block shrinks on front end but not in the editor
### Description

In a row block, if an image is resized to a specific width and placed next to a multi-lined paragraph, the image appears small on the front end, but is the correct size in the editor. This is confusing for folks learning how to use the row block for layout because the published page is different from what they expect.

Reproduced in the Twenty Twenty Four theme.

### Step-by-step reproduction instructions

1. Add a row block 
2. Add an image inside and give it a fixed width (300px)
3. Add a multi-line paragraph next to that image block
4. Image is 300px wide in the editor but is only 45px wide in the published front end

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WP 6.7.1 
Gutenberg plugin not active
Tested in both Twenty Twenty Four Theme and custom Hybrid theme
Mac, Chrome

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### LINKED ISSUE #68668: Image may disappear when cropping
### Description

The Image block may disappear when attempting to crop it in a few scenarios:
- It is inside a Row or Stack and has no size specified
- It is aligned left/center/right and has no size specified

#### Aligned images
1. Insert an image
2. Select local media for the Image
3. Align the image left, right or center
4. Press "Crop" from the block toolbar

#### Inside Row / Stack
1. Insert a Row / Stack
2. Insert an Image within the Row / Stack
3. Select local media for the Image
4. Press "Crop" from the block toolbar

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/da67ff6c-9091-419e-b571-2d792148bf03

### Environment info

- WP 6.7.1 / Gutenberg plugin trunk
- Firefox / Chrome
- MacOS

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### LINKED ISSUE #69316: Image Block: Resize container outline does not match block when border is applied
### Description

This problem appears to have first appeared in 6.7. Let's figure out where the regression occurred and fix it.

### Step-by-step reproduction instructions

Insert an Image block.

- Apply a border
- Make sure the image does not match the outline of the resize container

### WordPress 6.6, 6.5

https://playground.wordpress.net/?wp=6.6
https://playground.wordpress.net/?wp=6.5

This issue does not exist.

https://github.com/user-attachments/assets/e2fb4da8-9213-4632-8f34-fd9aa1028df7

### WordPress 6.7, Latest Gutenberg

https://playground.wordpress.net/?wp=6.7
https://playground.wordpress.net/?wp=6.7&plugin=gutenberg

This issue occurs.

https://github.com/user-attachments/assets/661fb8bd-e30f-4f90-a7b5-c22004fb5ab4

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by stokesman**
## What?
An attempt to fix several issues with the Image block in the editor by:
- Making the editor markup more similar to the front end (removes `div` wrapper around `img`).
- Omitting size controls of Image block when inside flex layouts.
I don’t think there’s as strong a reason to do this but I tried it because the size controls seem likely to be confusing in flex layouts.

There is also a few minor changes related to code quality.

## Why?
Most generally this seems like a good idea because the markup becomes more similar to that of the front end.
- Fixes #38381
- Fixes #52219
- Fixes #68057
- Fixes #68668
- Fixes #67506

## How?
1. Removes wrapping divs from the `img` in the editor markup.
   - The `ResizableBox` component is made a sibling (instead of a parent).
   - Removes the wrapping div that was there when not resizable.
2. Adds logic/state to ensure overlaid placement of the `ResizableBox` on the `img`.
   -  a mount effect on `ResizableBox`
   -  resize observation on the `img`
3. In flex layouts, omits the `ResizableBox` and width/height inspector controls.

## Testing Instructions

- Follow the reproduction steps for the linked issues and verify that you cannot reproduce them
- Test everything you can think of having to do with the Image block

<details><summary>Markup I used in testing these issues. You’ll have to replace the images with your own though.</summary>

```html
<!-- wp:paragraph -->
<p>The following are editor specific bugs or incongruities as compared to the front end.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"style":{"spacing":{"padding":{"top":"var:preset|spacing|20"}}},"fontSize":"large"} -->
<h2 class="wp-block-heading has-large-font-size" style="padding-top:var(--wp--preset--spacing--20)">⛔️ Resize handle placement is incorrect for an non-resized image whose natural width is less than the theme’s content width</h2>
<!-- /wp:heading -->

<!-- wp:image {"id":19,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full"><img src="http://localhost:8888/wp-content/uploads/2024/05/pine-flower.webp" alt="" class="wp-image-19"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"style":{"spacing":{"padding":{"top":"var:preset|spacing|20"},"margin":{"top":"40vh"}}},"fontSize":"large"} -->
<h2 class="wp-block-heading has-large-font-size" style="margin-top:40vh;padding-top:var(--wp--preset--spacing--20)">⛔️ Width stretched to content width for an non-resized image whose natural width is less than the theme’s content width when aspect ratio is specified</h2>
<!-- /wp:heading -->

<!-- wp:image {"id":19,"aspectRatio":"16/9","scale":"cover","sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full"><img src="http://localhost:8888/wp-content/uploads/2024/05/pine-flower.webp" alt="" class="wp-image-19" style="aspect-ratio:16/9;object-fit:cover"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"style":{"spacing":{"padding":{"top":"var:preset|spacing|20"},"margin":{"top":"40vh"}}},"fontSize":"large"} -->
<h2 class="wp-block-heading has-large-font-size" style="margin-top:40vh;padding-top:var(--wp--preset--spacing--20)">⛔️ Wrong size in flex and grid layouts</h2>
<!-- /wp:heading -->

<!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:image {"id":135,"width":"130px","height":"auto","scale":"cover","sizeSlug":"full","linkDestination":"none","style":{"layout":{"selfStretch":"fit","flexSize":null}}} -->
<figure class="wp-block-image size-full is-resized"><img src="http://localhost:8888/wp-content/uploads/2024/07/image.jpeg" alt="" class="wp-image-135" style="object-fit:cover;width:130px;height:auto"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"style":{"layout":{"selfStretch":"fit","flexSize":null}}} -->
<p>In a row block, if an image is resized to a specific width and placed next to a potentially wide block like a multi-lined paragraph, it maintains its specified size yet the appears small on the front end. This breaks WYSIWYG expectations.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"layout":{"type":"grid","columnCount":3,"rowCount":2,"isManualPlacement":true,"minimumColumnWidth":null}} -->
<div class="wp-block-group"><!-- wp:image {"id":19,"width":"504px","height":"auto","sizeSlug":"full","linkDestination":"none","style":{"layout":{"columnStart":1,"rowStart":1,"rowSpan":2}}} -->
<figure class="wp-block-image size-full is-resized"><img src="http://localhost:8888/wp-content/uploads/2024/05/pine-flower.webp" alt="" class="wp-image-19" style="width:504px;height:auto"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"style":{"color":{"background":"#ffffffa8"},"layout":{"columnStart":2,"rowStart":1}},"fontSize":"medium"} -->
<p class="has-background has-medium-font-size" style="background-color:#ffffffa8">In a grid block, it’s a similar situation.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"color":{"background":"#ffffffa8"},"layout":{"columnStart":3,"rowStart":1}},"fontSize":"medium"} -->
<p class="has-background has-medium-font-size" style="background-color:#ffffffa8">Another sibling.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:heading {"style":{"spacing":{"padding":{"top":"var:preset|spacing|20"},"margin":{"top":"40vh"}}},"fontSize":"large"} -->
<h2 class="wp-block-heading has-large-font-size" style="margin-top:40vh;padding-top:var(--wp--preset--spacing--20)">⛔️ If the image is shorter than the line-height so too is the figure and vertical alignment is incongruent with the front end</h2>
<!-- /wp:heading -->

<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|20","bottom":"var:preset|spacing|20","left":"var:preset|spacing|20","right":"var:preset|spacing|20"}},"color":{"background":"#f3d5f1"}},"fontSize":"xx-large","layout":{"type":"constrained"}} -->
<div class="wp-block-group has-background has-xx-large-font-size" style="background-color:#f3d5f1;padding-top:var(--wp--preset--spacing--20);padding-right:var(--wp--preset--spacing--20);padding-bottom:var(--wp--preset--spacing--20);padding-left:var(--wp--preset--spacing--20)"><!-- wp:image {"id":63,"width":"32px","sizeSlug":"full","linkDestination":"none","style":{"spacing":{"margin":{"left":"var:preset|spacing|20","right":"0"}}}} -->
<figure class="wp-block-image size-full is-resized" style="margin-right:0;margin-left:var(--wp--preset--spacing--20)"><img src="http://localhost:8888/wp-content/uploads/2024/06/transparent-site-icon.png" alt="" class="wp-image-63" style="width:32px"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|20","bottom":"var:preset|spacing|40","left":"var:preset|spacing|20","right":"var:preset|spacing|20"}},"typography":{"letterSpacing":"21px"},"color":{"background":"#f3d5f1"}},"fontSize":"xx-large","layout":{"type":"constrained","justifyContent":"center"}} -->
<div class="wp-block-group has-background has-xx-large-font-size" style="background-color:#f3d5f1;padding-top:var(--wp--preset--spacing--20);padding-right:var(--wp--preset--spacing--20);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--20);letter-spacing:21px"><!-- wp:image {"id":63,"width":"32px","height":"auto","sizeSlug":"full","linkDestination":"none","align":"left","style":{"spacing":{"margin":{"left":"var:preset|spacing|20","right":"var:preset|spacing|20"}}}} -->
<figure class="wp-block-image alignleft size-full is-resized" style="margin-right:var(--wp--preset--spacing--20);margin-left:var(--wp--preset--spacing--20)"><img src="http://localhost:8888/wp-content/uploads/2024/06/transparent-site-icon.png" alt="" class="wp-image-63" style="width:32px;height:auto" title="fub"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>SOMETHING</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:heading {"style":{"spacing":{"padding":{"top":"var:preset|spacing|20"},"margin":{"top":"50vh"}}},"fontSize":"large"} -->
<h2 class="wp-block-heading has-large-font-size" style="margin-top:50vh;padding-top:var(--wp--preset--spacing--20)">⛔️ Image may disappear when cropping/rotating in flex layouts</h2>
<!-- /wp:heading -->

<!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:image {"id":74,"scale":"cover","sizeSlug":"full","linkDestination":"none","style":{"layout":{"selfStretch":"fit","flexSize":null}}} -->
<figure class="wp-block-image size-full"><img src="http://localhost:8888/wp-content/uploads/2024/06/Example-Background-Image.jpg" alt="" class="wp-image-74" style="object-fit:cover"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>It happens if the image lacks a specified size and even without other siblings in the row.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->
```

</details>

#### Wrong size in flex and grid layouts (#68057 is open for this but is Row specific) 
|Before|Front end|After|
|-|-|-|
| image-block-size-in-grid-flex-before | image-block-size-in-grid-flex-front | image-block-size-in-grid-flex-after |

#### Image incorrectly filling the content-width #52219
An image block with an image that is smaller than the width of the post container with a specified aspect ratio and no specified size is incorrectly filling the width of the container.
|Before|Front end|After|
|-|-|-|
| image-block-stretch-w-aspect-ratio-before | image-block-stretch-w-aspect-ratio-front | image-block-stretch-w-aspect-ratio-after |

#### Layout incorrect for images that are shorter than line-height (no open issue, I think)
If the image is shorter than the line-height so too is the figure and vertical alignment is incongruent with the front end
|Before|Front end|After|
|-|-|-|
| image-block-short-before | image-block-short-front | image-block-short-after |

#### Resize handles out of place (I think there’s no open issue)
It affects images that are narrower than the content width with no size specified.
|Before|After|
|-|-|
| image-block-resize-handle-before | image-block-resize-handle-after |

#### Disappearing image when editing (crop/rotate) auto-sized images inside flex layouts #68668

https://github.com/user-attachments/assets/da67ff6c-9091-419e-b571-2d792148bf03

#### Layout shifts when editing (crop/rotate) auto-sized images
In trunk, an image without any specified size doesn’t maintain its displayed size when cropping/rotating. In this branch the image size will be maintained. This is an incidental change but might be hard to separate from the fix for the preceding issue. Besides it seems like a nice thing for consistency with how it works in most other scenarios (no layout shift).

|Before|After|
|-|-|
| image-block-crop-unsized-before | image-block-crop-unsized-after |

### CODE REVIEW

**Comment by himanshupathak95** [comment]
Hey @stokesman, Thanks for the PR.

This is testing well for me and covering multiple issues. 

✅  The flicker issue is resolved 

https://github.com/user-attachments/assets/25066abb-6de6-482d-8aca-ada57b1096f5


✅  The image disappearing when cropping inside a row/stack is also resolved

https://github.com/user-attachments/assets/c1c00647-74da-419c-b532-da2fdcc38d48

**Comment by Infinite-Null** [comment]
Hi @stokesman,

Thank you for the PR, I have tested for disappearing image when editing (crop/rotate) auto-sized images inside flex layouts and this PR seems to solve the issue:

## Screencast:

https://github.com/user-attachments/assets/7a5e8d92-281a-47ab-ba62-c52ddec2c570

File: packages/block-library/src/image/image.js [hunk 1]
```diff
@@ -280,12 +284,13 @@ export default function Image( {
 		lightbox,
 		metadata,
 	} = attributes;
-
-	// The only supported unit is px, so we can parseInt to strip the px here.
-	const numericWidth = width ? parseInt( width, 10 ) : undefined;
-	const numericHeight = height ? parseInt( height, 10 ) : undefined;
```
Comment (stokesman) [inline packages/block-library/src/image/image.js:286]: These became unneeded with the introduction of `pixelSize` that stays in sync with the displayed size of the `img`.

File: packages/block-library/src/image/image.js [hunk 2]
```diff
@@ -280,12 +284,13 @@ export default function Image( {
...
-
-	const imageRef = useRef();
+	const [ imageElement, setImageElement ] = useState();
```
Comment (stokesman) [inline packages/block-library/src/image/image.js:287]: Switching to state instead of a ref for the `img`. I suppose this isn’t strictly necessary but because the value is read during render putting it in state follows the guidance of not reading refs in render.

File: packages/block-library/src/image/image.js [hunk 3]
```diff
@@ -369,34 +374,18 @@ export default function Image( {
...
-		imageRef.current?.complete,
-	] );
-
-	function onResizeStart() {
-		toggleSelection( false );
-	}
-
-	function onResizeStop() {
-		toggleSelection( true );
-	}
```
Comment (stokesman) [inline packages/block-library/src/image/image.js:399]: Moved into the bodies of the handlers at the actual `ResizableBox` JSX.

File: packages/block-library/src/image/image.js [hunk 4]
```diff
@@ -926,17 +915,14 @@ export default function Image( {
 					alt={ defaultedAlt }
 					onError={ onImageError }
 					onLoad={ onImageLoad }
-					ref={ imageRef }
+					ref={ setRefs }
 					className={ borderProps.className }
+					width={ naturalWidth }
+					height={ naturalHeight }
```
Comment (stokesman) [inline packages/block-library/src/image/image.js:924]: Adding these img attributes is congruent with the front end and I'm pretty sure helped in some layout context though I forget the specifics.

File: packages/block-library/src/image/image.js [hunk 5]
```diff
@@ -530,49 +530,49 @@ export default function Image( {
...
-				// doesn't do anything with keys that aren't set.
-				setAttributes( {
-					// CSS includes `height: auto`, but we need
-					// `width: auto` to fix the aspect ratio when
-					// only height is set due to the width and
-					// height attributes set via the server.
-					width: ! newWidth && newHeight ? 'auto' : newWidth,
+	const dimensionsControl =
+		isResizable &&
+		( SIZED_LAYOUTS.includes( parentLayoutType ) ? (
```
Comment (stokesman) [inline packages/block-library/src/image/image.js:544]: This is extraneous but it bugged me that the condition for which dimension controls would be visible was repeated in a couple places and both versions of the controls were being invoked regardless. If it helps to see it was done atomically in 6b28210df80aa66cd5a88497c2bfe11749651da6.

**Review by stokesman — COMMENTED** [review]
I’ve added some comments that I hope can aid review.

**Comment by Mamaduka** [comment]
Fantastic work, @stokesman!

I'm going to add this to the WP 6.8 project. I think this is an excellent improvement for one of the most used blocks.

**Comment by carolinan** [comment]
I have manually tested this in different combinations of image sizes, with or without links, with borders, shadows, aspect ratios etc.
I have not found any **new** issues: What makes this difficult to test is that there are some problems both without Gutenberg active and with this PR applied, such as the resize handles being in the wrong position when the "Contain" option is enabled. Without more specific testing instructions, it makes it difficult to know what the expected result is.

**Comment by stokesman** [comment]
Thank you for testing Carolina 🙇 

> the resize handles being in the wrong position when the "Contain" option is enabled

I looked into this and found the same behavior here as on trunk. I think that the position is technically correct but is likely to be confusing. The actual `img` size matches the resize handles but not visually because that’s what "contain" does. I'm not sure if there’s anything that can be done better in this case. If the handles match the apparent `img` size they would be inaccurate in regards to the aspect ratio.

<details><summary>Screenshot of Image block scale set to "Contain" with actual <code>img</code> size highlighted</summary>

image-block-contain-highlight-img

</details>

> Without more specific testing instructions, it makes it difficult to know what the expected result is

I take it you mean that generally and not just for the "contain" case. I find the idea of writing exhaustive specific testing instructions daunting since there are so many permutations. If I tried I’d surely miss some. I hope that we can pick out any scenarios where the expected result is unclear and come to an agreement as we go.

**Comment by carolinan** [comment]
What I am not finding, is a conversation about why the element was needed in the first place, and if everything that the element _once solved,_ is now fixed.

For example, this line in the removed CSS:
`// This is necessary for the editor resize handles to accurately work on a non-floated, non-resized, small image.`

Is this scenario resolved?

**Comment by carolinan** [comment]
And I think that issues should be created before pull requests. If the div created problems, they are not listed, and it makes it more difficult to review.

**Comment by stokesman** [comment]
> What I am not finding, is a conversation about why the element was needed in the first place, and if everything that the element _once solved,_ is now fixed.

I’ve looked into it and haven’t found it either. For me it’s reasonable to believe the wrapper element was introduced merely for easing the implementation of the in-canvas resizing. To create a resizable element with handles the most obvious way is to have the handles be children of the element. Yet an `img` element can’t have children and thus adding a wrapper is the easiest workaround. For reference #2213 introduced the resizable wrapper on the `img` element but I didn’t see discussion along this aspect.

> For example, this line in the removed CSS:
> `// This is necessary for the editor resize handles to accurately work on a non-floated, non-resized, small image.`

I believe I tested that well enough but I can recheck. Assuming it is resolved, I’ll get back with more detail on how it can be tested. For reference, it comes from #7721.

> I think that issues should be created before pull requests. If the div created problems, they are not listed, and it makes it more difficult to review.

I'm with you and it’s part of the guidelines for non-trivial PRs. Yet there are issues that were created before this PR and are linked here so I’m not certain what I can do better. I appreciate your feedback and will consider any suggestions on how to improve this.

**Comment by aaronrobertshaw** [comment]
Thanks for the ping for review @carolinan, unfortunately, I don't have the bandwidth to help review or test here in the near future.

I'll remove myself from the reviewers list, but it might pay to try pinging other contributors for additional eyes 🤞

File: packages/block-library/src/image/editor.scss [hunk 6]
```diff
@@ -48,19 +48,6 @@ figure.wp-block-image:not(.wp-block) {
 	}
 }
 
-// This is necessary for the editor resize handles to accurately work on a non-floated, non-resized, small image.
-.wp-block-image .components-resizable-box__container {
-	// Using "display: table" because:
-	// - it visually hides empty white space in between elements
-	// - it allows the element to be as wide as its contents (instead of 100% width, as it would be with `display: block`)
-	display: table;
```
Comment (stokesman) [inline packages/block-library/src/image/editor.scss:56]: I'm adding some commentary here since it was [asked about](https://github.com/WordPress/gutenberg/pull/68666/#:~:text=Is%20this%20scenario%20resolved%3F)

Currently the comment and style are outdated because `display: table` is overridden by inline styles. For reference, according to https://github.com/WordPress/gutenberg/pull/44965#issuecomment-1278770289 it was added to hide some empty space below the image (that made the selected block outline look wrong) while also avoiding a regression of broken center alignments. In trunk, it’s overridden with `display: block` from inline styles that were added in #51545 and I couldn’t find discussion on that particular change but it seems to have been okay and did not regress anything. 

In regards to this PR, this selector and rule applied to the wrapper around the `img` and now there is no wrapper. Since there is no wrapper it’s worth considering the the `display` of the `img` itself and that is not specified. From my testing everything around this works. That is, resizing "non-floated, non-resized small images" works fine. Better than on trunk since the resize handles are initially out of place on small images (less than the container’s content width) there. Also:
- center aligned images work as expected
- there is no empty space below the image between the selected block outline

<details><summary>Some markup that can be used to test such images.</summary>

```html
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|20","bottom":"var:preset|spacing|20","left":"var:preset|spacing|20","right":"var:preset|spacing|20"}},"color":{"background":"#f3d5f1"}},"fontSize":"xx-large","layout":{"type":"constrained"}} -->
<div class="wp-block-group has-background has-xx-large-font-size" style="background-color:#f3d5f1;padding-top:var(--wp--preset--spacing--20);padding-right:var(--wp--preset--spacing--20);padding-bottom:var(--wp--preset--spacing--20);padding-left:var(--wp--preset--spacing--20)"><!-- wp:image {"width":"32px","sizeSlug":"large","linkDestination":"none","style":{"spacing":{"margin":{"left":"var:preset|spacing|20","right":"0"}}}} -->
<figure class="wp-block-image size-large is-resized" style="margin-right:0;margin-left:var(--wp--preset--spacing--20)"><img src="https://placehold.co/10x10/crimson/white?text=%23" alt="" style="width:32px"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|20","bottom":"var:preset|spacing|40","left":"var:preset|spacing|20","right":"var:preset|spacing|20"}},"typography":{"letterSpacing":"21px"},"color":{"background":"#f3d5f1"}},"fontSize":"xx-large","layout":{"type":"constrained","justifyContent":"center"}} -->
<div class="wp-block-group has-background has-xx-large-font-size" style="background-color:#f3d5f1;padding-top:var(--wp--preset--spacing--20);padding-right:var(--wp--preset--spacing--20);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--20);letter-spacing:21px"><!-- wp:image {"width":"32px","height":"auto","sizeSlug":"large","linkDestination":"none","align":"left","style":{"spacing":{"margin":{"left":"var:preset|spacing|20","right":"var:preset|spacing|20"}}}} -->
<figure class="wp-block-image alignleft size-large is-resized" style="margin-right:var(--wp--preset--spacing--20);margin-left:var(--wp--preset--spacing--20)"><img src="https://placehold.co/10x10/crimson/white?text=%23" alt="" style="width:32px;height:auto" title="fub"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>SOMETHING</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```

**Comment by t-hamano** [comment]
It turns out that this PR also resolves issue #69316. Use the following markup to apply a border to an image:

```html
<!-- wp:image {"sizeSlug":"large","linkDestination":"none","style":{"border":{"width":"0px","style":"none"}}} -->
<figure class="wp-block-image size-large has-custom-border"><img src="https://placehold.jp/1000x400.png" alt="" style="border-style:none;border-width:0px"/></figure>
<!-- /wp:image -->
```

#### trunk

Image height and resizable box height don't match:

<details><summary>Details</summary>

https://github.com/user-attachments/assets/ede135f9-7377-4a9b-82bb-5254e7a9522e

</details> 


#### This PR

There is a slight delay, but the resizable box fits the actual image size:

<details><summary>Details</summary>

https://github.com/user-attachments/assets/b31af64f-0be2-4f74-9c82-259609a19f0c

</details>

**Comment by himanshupathak95** [comment]
Thanks everybody for working on this. Here is how this PR tests for me - 

✅ Issue #38381 - Images maintain proper responsive behavior and stay within their containers, even after manual resizing.

https://github.com/user-attachments/assets/2773598f-710a-48ca-847b-53174d7f792a


----

✅ Issue #52219 - Images with aspect ratio display at their natural size without incorrectly stretching to fill the container width.

https://github.com/user-attachments/assets/32d8e12f-6e95-4d3f-b0e3-c4f292113f01


----

✅ Issue #67506 - Images maintain consistent size when selected/deselected in various layout contexts.

https://github.com/user-attachments/assets/1cef6c09-cae1-4c28-9e3f-b60d300e406c


----

🟨 Issue #68057 - Images inside Row/Stack blocks maintain consistent sizing between editor and frontend views. However, as can be seen, if a very large paragraph is pasted, the image shrinks almost completely which might be unexpected but I think this is a separate issue to take care of.


https://github.com/user-attachments/assets/a1080068-d8c3-4840-af3c-7b1b77b50a89



----

✅ Issue #68668 - Images no longer disappear when cropping in Row/Stack blocks or when aligned without specified size.


https://github.com/user-attachments/assets/60bb9c48-4c0c-4767-9fb0-2c223a23e02c



----

✅ Issue #69316 - Resize container outline properly aligns with image borders when borders are applied.



https://github.com/user-attachments/assets/1b95dacd-53da-4e56-bb76-d2917398ebbb

**Review by Mamaduka — APPROVED** [review]
Thank you, @stokesman!

Could you rebase this on top of the latest trunk? Then, I think it's ready to merge.

* The code looks good.
* It tests well for me and others.
* If we missed something, we could follow up with a fix.

**Comment by stokesman** [comment]
Thanks for the review George 🙇. I’ve rebased on trunk.

> * If we missed something, we could follow up with a fix.

I have one fix in mind. The issue is technically not introduced here but I’m bringing it up because it could seem like it was. It’s a bug that manifests differently on this branch but is present on trunk. It may not be an issue on every theme but is on TT5, TT4, TT3 and TT2. It pertains to unsized images that are aligned left or right and whose innate width is larger than the content width. Thus, It’s fairly obscure. Moreover, for an image that’s aligned left or right it’s expected that the user will size it narrower than the content width and then there is no issue.

| Trunk | This branch |
|--------|--------|
| <video src="https://github.com/user-attachments/assets/fe66c549-3fc5-4230-9115-5f06bedbf1ca"/> | <video src="https://github.com/user-attachments/assets/cbc7363a-973d-4b4a-b789-3e85b4c47eb1" /> |
| The image resizes when selected (the first time) and the size (at least on some themes) doesn’t match the frontend. | The resizable box’s size is constrained by the content width but the image  matches what the the theme allows on the frontend |

The cause is the [`useMaxWidthObserver`](https://github.com/WordPress/gutenberg/blob/18a4c0d236b751084d406871a5ad7ab846938c40/packages/block-library/src/image/use-max-width-observer.js) hook. I’ll try a fix. I think we’d have to get it in before beta though because the problem was present in 6.7.

UPDATE: I’ve opened #69364 for this.

**Comment by stokesman** [comment]
Folks, please pardon me. I failed to paste the props.

**Comment by Mamaduka** [comment]
No worries, @stokesman! Happens to everyone at some point.

Note: It looks like we missed the "deadline" for WP 6.8 inclusion. Pros: We'll have more time to test this with Gutenberg installations, avoiding possible bugs in beta/RC releases. Cons: It won't ship with WP 6.8.

@stokesman, any strong opinions about including this in WP 6.8 or not?

**Comment by stokesman** [comment]
> any strong opinions about including this in WP 6.8 or not?

No. It would have been nice yet at least we don’t have to sweat new bugs before the release. I found one already 😅 #69381.
