### PR TITLE
Fix the site editor breaking in firefox

### LINKED ISSUE #33873: Site Editor is empty in firefox
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

With the latest release 11.2.0 the Site Editor returns an empty white screen in Firefox browser. Chrome not affected.

Console shows error: "Uncaught (in promise) TypeError: e.current is undefined" /build/block-editor/index.min.js:81:23487

### Step-by-step reproduction instructions

Activate a FSE/block based theme.
Click 'Site Editor'.
Notice the editor is completely empty.

### Expected Behavior

The Site Editor to load.

### Current Behavior

The Site Editor does not load.

### Screenshots or screen recording (optional)

_No response_

### Code snippet (optional)

_No response_

### WordPress Information

5.8

### Gutenberg Information

11.2.0

### What browsers are you seeing the problem on?

Firefox

### Device Information

Desktop

### Operating System Information

Windows 10

### PR DESCRIPTION
**Pull request by youknowriad**
closes #33873 

I'm not entirely certain that this is a good solution but in Firefox the ref is null initially meaning that it's probably not being attached on mount.

Guarding against the ref solves the issue but doesn't explain why the ref is empty in the first place.

**Note:** It seems we don't have an error boundary in the site editor or if we do, it's not working well.

**Testing instructions**

 - Open the site editor in firefox
 - Make sure you don't get just a crash/

### CODE REVIEW

**Comment by Mamaduka** [comment]
> Note: It seems we don't have an error boundary in the site editor or if we do, it's not working well.

Yes, we don't have an error boundary in the site editor.

Update: Created and issue #33899 and will follow up with PR shortly.

File: packages/block-editor/src/components/writing-flow/use-multi-selection.js [hunk 1]
```diff
@@ -87,6 +87,10 @@ export default function useMultiSelection() {
 	 * select the entire block contents.
 	 */
 	useEffect( () => {
```
Comment (Mamaduka) [inline packages/block-editor/src/components/writing-flow/use-multi-selection.js]: Maybe we should use `useRefEffect` here instead of `useEffect`?

Both `useSelectAll` and `useArrowNav` are using `useRefEffect` hook.

https://github.com/WordPress/gutenberg/blob/9e2fc57fe27dfca594bdff358853a0a0acaf8efe/packages/block-editor/src/components/writing-flow/index.js#L35-L37

P.S. I haven't got a chance to use this hook in action yet, but this seems like a good use case.

**Review by Mamaduka — APPROVED** [review]
Tested it, and I don't see an error in Firefox.

P.S. Created PR for the error boundary - #33921.

**Review by creativecoder — APPROVED** [review]
This fixes the Template and Site editor crashes for me, as well.

Though note another error is triggered (and more after that if you apply the same kind of fix).

```
Uncaught TypeError: can't access property "getAlignments", layoutType is undefined
    useAvailableAlignments use-available-alignments.js:30
```

I think it makes sense to merge this now, though, to prevent the crash while we try to figure out a better solution.

File: packages/block-editor/src/components/writing-flow/use-multi-selection.js (hunk 1 above)
Comment (youknowriad) [reply packages/block-editor/src/components/writing-flow/use-multi-selection.js]: I updated to use useRefEffect and indeed, it seems to work.

**Comment by youknowriad** [comment]
@creativecoder I haven't been able to get the second error you shared, it might be theme specific. Consider opening an issue with more details.

**Comment by creativecoder** [comment]
> @creativecoder I haven't been able to get the second error you shared, it might be theme specific. Consider opening an issue with more details.

Thanks @youknowriad , I'm no longer able to replicate it testing on current `trunk`, so it seems to be resolved.
