### PR TITLE
[Widgets Editor] Add a filter function to `registerCoreBlock`

### LINKED ISSUE #26178: [Widgets Screen] Remove "Read More" block from being added
**Describe the bug**

The Read More block can be added to the widgets screen and it seems unlikely to be needed in this setting at any point. It would be good to prevent this from being used. Similar to the navigation block work where only certain blocks can be added, it's important to make clear what's allowed/not allowed for different screens/experiences. This is discussed a bit here: https://github.com/WordPress/gutenberg/issues/24007

**To reproduce**
1. Create a new test site.
2. Install Gutenberg and activate.
3. Go to Appearance > Widgets
4. Use the + to add a new block and search for "Read More"

**Expected behavior**

I expect to not to be able to add this block. 

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg Plugin
- If the Gutenberg plugin is installed, which version is it? 9.1.1 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 86.0.4240.75

### PR DESCRIPTION
**Pull request by kevin940726**
## Description

Fix #26178.

Add a `filter` function to `registerCoreBlock` and filter out `core/more` block in widgets editor.

I'm not sure this is the right approach. Another option I can think of is to add a `disallowedBlocks` to `<InnerBlocks>` and `widget-area`. Or remove `more` block from core, and register them manually one-by-one in each usage. I figured to open this PR first to gain more discussion and suggestions.

## How has this been tested?

1. Go to Widgets editor
2. Insert a new block
3. Search for the "more" block
4. Observe that there's no "more" block

## Screenshots 
image

## Types of changes

Bug fix

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by talldan** [comment]
An alternative might be adding new functions `getCoreBlocks` and `__experimentalGetExperimentalCoreBlocks` for returning the available blocks in the library. `edit-widgets` could then filter those lists and handle registration.

IMO, the biggest problem the existing functions solve is the maintenance of keeping up-to-date with the available blocks from the block-library package rather than registration. Registration itself is relatively straightforward.

**Comment by kevin940726** [comment]
@talldan I added a new function `__experimentalGetCoreBlocks`. Not sure if that is what you meant?

**Review by talldan — APPROVED** [review]
@kevin940726 Nice! A bit different to what I was thinking, but I think this is better. Offers lots of granularity for users of the package, they can use a completely custom list of blocks, filter out particular core blocks, or use all core blocks.

I was also thinking we'd go for the same API for experimental blocks which are registered a little later in the file, but there's no urgency on that as not related to this bug.

File: packages/block-library/src/index.js [hunk 1]
```diff
@@ -104,66 +104,82 @@ const registerBlock = ( block ) => {
...
+ * Function to get all the core blocks in an array.
+ *
+ * @example
+ * ```js
+ * import { __experimentalGetCoreBlocks } from '@wordpress/block-library';
+ *
+ * const coreBlocks = __experimentalGetCoreBlocks();
+ * ```
+ */
+export const __experimentalGetCoreBlocks = () => [
```
Comment (talldan) [inline packages/block-library/src/index.js:117]: I'm not convinced it needs to be experimental, but it does no harm (other than later maintenance).

File: packages/block-library/src/index.js [hunk 2]
```diff
@@ -104,66 +104,82 @@ const registerBlock = ( block ) => {
...
-		textColumns,
-		verse,
-		video,
-	].forEach( registerBlock );
+export const registerCoreBlocks = (
+	blocks = __experimentalGetCoreBlocks()
+) => {
+	blocks.forEach( registerBlock );
 
 	setDefaultBlockName( paragraph.name );
```
Comment (talldan) [inline packages/block-library/src/index.js:184]: I note that there'd be issues if one of these blocks was not passed in the blocks param.

That could be considered using the function incorrectly, but we could also add some guards to prevent errors.
