### PR TITLE
PostSchedule: Do not allow an invalid time

### LINKED ISSUE #3273: You can 'break' the date time picker
## Issue Overview

If you try to 'delete' the date value, you can break it.

## Steps to Reproduce (for bugs)
1. Create a post
2. Edit the publish date
3. DELETE the date value (select and delete)

## Expected Behavior

The interface should allow me to pick a date

## Current Behavior

Invalid date:

screen shot 2017-10-31 at 31 oct - 12 21 26 pm

Once you hit this problem, you cannot pick a new date AND you can't save your post. You're dead in the water.

## Related Issues and/or PRs
Related to DST issues - https://github.com/WordPress/gutenberg/issues/3271

### PR DESCRIPTION
**Pull request by youknowriad**
closes #3273

This PR fixes the post schedule component by forbidding any invalidate date/time including empty times. This means you can't "remove" the time but you can select and replace it instead.

An alternative would be to make the input "uncontrolled" and only call `onChange` if the value is valid.

**Testing instructions**

 - Create a post
 - Edit the publish date
 - DELETE the date value (select and delete)
 - You should not be able to delete it but you should be able to update it.

### CODE REVIEW

File: editor/post-schedule/clock.js [hunk 1]
```diff
@@ -12,6 +17,7 @@ function PostScheduleClock( { is12Hour, selected, onChange } ) {
 	const updateHours = ( event ) => {
 		const value = parseInt( event.target.value, 10 );
 		if (
+			! isInteger( value ) ||
```
Comment (aduth) [inline editor/post-schedule/clock.js]: Simpler to do `isNaN( value )`? Here and below.

**Review by aduth — APPROVED** [review]

File: editor/post-schedule/clock.js (hunk 1 above)
Comment (youknowriad) [reply editor/post-schedule/clock.js]: I wanted to guard against `1.345`

Comment (aduth) [reply editor/post-schedule/clock.js]: But `parseInt` wouldn't return a float?

```js
parseInt( '1.345', 10 )
// 1
```

Comment (youknowriad) [reply editor/post-schedule/clock.js]: Right! I missed that :)
