### PR TITLE
FocalPointPicker: Supply default value as initial percentages state to fix NaN warning

### LINKED ISSUE #15136: FocalPointPicker warning: Received NaN for the `value` attribute.
**Describe the bug**

When plugins use the [FocalPointPicker](https://github.com/WordPress/gutenberg/blob/4472b1bf3da10f3e382b68f6e7f8894757d7c395/packages/components/src/focal-point-picker/index.js#L38) component and the `FocalPointPicker` displays for the first time, it looks to cause a console warning. This isn't present at all without the `FocalPointPicker`:

```
react-dom.165d5c53.js:500 Warning: Received NaN for the `value` attribute. If this is expected, cast the value to a string.
    in input
    in div (created by De)
    in div (created by De)
    in De
    in Unknown (created by WithState(Component))
    in WithState(Component) (created by WithInstanceId(WithState(Component)))
    in WithInstanceId(WithState(Component)) (created by t)
    in div (created by t)
    in t (created by ForwardRef(PanelBody))
    in ForwardRef(PanelBody) (created by t)
    in t (created by Context.Consumer)
    in se (created by InspectorControlsSlot)
    in InspectorControlsSlot
    in div
    in Unknown (created by n)
    in n (created by Context.Consumer)
    in WithSelect(Component)
    in div (created by t)
    in t (created by ForwardRef(PanelBody))
    in ForwardRef(PanelBody)
    in div (created by sn)
    in sn
    in div (created by sn)
    in sn (created by n)
    in div (created by n)
    in n (created by Context.Consumer)
    in Unknown (created by b)
    in b
    in t (created by Context.Consumer)
    in se (created by SidebarSlot)
    in SidebarSlot
    in div (created by t)
    in t
    in Unknown (created by n)
    in n (created by Context.Consumer)
    in WithViewportMatch(Component) (created by NavigateRegions(WithViewportMatch(Component)))
    in div (created by NavigateRegions(WithViewportMatch(Component)))
    in NavigateRegions(WithViewportMatch(Component)) (created by r)
    in r (created by Context.Consumer)
    in WithDispatch(NavigateRegions(WithViewportMatch(Component))) (created by n)
    in n (created by Context.Consumer)
    in WithSelect(WithDispatch(NavigateRegions(WithViewportMatch(Component)))) (created by t)
    in t (created by t)
    in div (created by t)
    in t (created by t)
    in t (created by t)
    in t (created by r)
    in r (created by Context.Consumer)
    in WithDispatch(t)
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(WithDispatch(t)) (created by t)
    in t (created by r)
    in r (created by Context.Consumer)
    in WithDispatch(t) (created by n)
    in n (created by Context.Consumer)
    in WithSelect(WithDispatch(t)) (created by t)
    in StrictMode (created by t)
    in t (created by n)
    in n (created by Context.Consumer)
    in WithSelect(t)
```

**To reproduce**

# With AMP Plugin
1. Install the [AMP plugin](https://github.com/ampproject/amp-wp) by running `git clone -b amp-stories-redux https://github.com/ampproject/amp-wp.git amp`
2. Possibly `ssh` into your environment, and `cd` to the `amp/` directory
3. `composer install && npm install && npm run dev`
4. `wp plugin activate amp`
5. In `/wp-admin` > AMP, check "Enable experimental support for AMP Stories." (or go to /wp-admin/admin.php?page=amp-options)
6. In the admin bar, click New > AMP Story
7. Click the page, click Background Media > Select Media, select an image
8. Expected: there is no console warning
9. Actual: there is a console warning, as shown above. Here's the [location of the FocalPointPicker](https://github.com/ampproject/amp-wp/blob/amp-stories-redux/assets/src/blocks/amp-story-page/edit.js#L293).

focal-point-picker-error

# With CoBlocks Plugin
1. Download and activate the [CoBlocks](https://wordpress.org/plugins/coblocks/) plugin
2. Create a new post
3. Add a "Media Card" block
4. Add a background image
media-card
5. Expected: there's no console warning
6. Actual: there's a similar warning to the one in the AMP plugin. Here's the [location of the FocalPointPicker](https://github.com/godaddy/coblocks/blob/3d9d9c8a39a582dae5f458792489ddee5eaa3ea3/src/components/background/index.js#L142).

```
react-dom.165d5c53.js:500 Warning: Received NaN for the `value` attribute. If this is expected, cast the value to a string.
    in input
    in div (created by De)
    in div (created by De)
    in De
    in Unknown (created by WithState(Component))
    in WithState(Component) (created by WithInstanceId(WithState(Component)))
    in WithInstanceId(WithState(Component)) (created by t)
    in div (created by t)
    in t (created by ForwardRef(PanelBody))
    in ForwardRef(PanelBody) (created by t)
    in t (created by Context.Consumer)
    in se (created by InspectorControlsSlot)
    in InspectorControlsSlot
    in div
    in Unknown (created by n)
    in n (created by Context.Consumer)
    in WithSelect(Component)
    in div (created by t)
    in t (created by ForwardRef(PanelBody))
    in ForwardRef(PanelBody)
    in div (created by sn)
    in sn
    in div (created by sn)
    in sn (created by n)
    in div (created by n)
    in n (created by Context.Consumer)
    in Unknown (created by b)
    in b
    in t (created by Context.Consumer)
    in se (created by SidebarSlot)
    in SidebarSlot
    in div (created by t)
    in t
    in Unknown (created by n)
    in n (created by Context.Consumer)
    in WithViewportMatch(Component) (created by NavigateRegions(WithViewportMatch(Component)))
    in div (created by NavigateRegions(WithViewportMatch(Component)))
    in NavigateRegions(WithViewportMatch(Component)) (created by r)
    in r (created by Context.Consumer)
    in WithDispatch(NavigateRegions(WithViewportMatch(Component))) (created by n)
    in n (created by Context.Consumer)
    in WithSelect(WithDispatch(NavigateRegions(WithViewportMatch(Component)))) (created by t)
    in t (created by t)
    in div (created by t)
    in t (created by t)
    in t (created by t)
    in t (created by r)
    in r (created by Context.Consumer)
    in WithDispatch(t)
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(WithDispatch(t)) (created by t)
    in t (created by r)
    in r (created by Context.Consumer)
    in WithDispatch(t) (created by n)
    in n (created by Context.Consumer)
    in WithSelect(WithDispatch(t)) (created by t)
    in StrictMode (created by t)
    in t (created by n)
    in n (created by Context.Consumer)
    in WithSelect(t)
```

**Expected behavior**
There should be no console warning. Though otherwise, this works fine.

**Desktop**
 - OS: MacOS 10.13.6 (17G65)
 - Browser: Chrome 73.0.3683.103 (Official Build) (64-bit)

**Additional context**
Gutenberg Version: 5.5.0

### PR DESCRIPTION
**Pull request by westonruter**
The `FocalPointPicker` component can result in a React warning being emitted from the console:

> Warning: Received NaN for the `value` attribute. If this is expected, cast the value to a string.

The reason for this that the `state` for the component has an empty `percentages` by default:

https://github.com/WordPress/gutenberg/blob/77b8234222f6c900d76e8087f863fe276c5a638e/packages/components/src/focal-point-picker/index.js#L30

Because of this `percentages.x` is initially `undefined` and in this code:

https://github.com/WordPress/gutenberg/blob/77b8234222f6c900d76e8087f863fe276c5a638e/packages/components/src/focal-point-picker/index.js#L220

The `this.fractionToPercentage( percentages.x )` call will return `NaN`.

The fix seems to be as simple as using the default prop `value` as the initial state for `percentages`.

Fixes #15136.

### CODE REVIEW

File: packages/components/src/focal-point-picker/index.js [hunk 1]
```diff
@@ -27,7 +27,7 @@ export class FocalPointPicker extends Component {
 		this.state = {
 			isDragging: false,
 			bounds: {},
-			percentages: {},
+			percentages: FocalPointPicker.defaultProps.value,
```
Comment (aduth) [inline packages/components/src/focal-point-picker/index.js]: It's neither here nor there to the specific fix, but this looks to me like a classic violation of an previously-documented anti-pattern:

http://web.archive.org/web/20160430110308/http://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html

Comment (aduth) [inline packages/components/src/focal-point-picker/index.js]: To the specific fix however: It's terribly confusing to me that we assign this value and immediately override it in `componentDidMount` with a `setState`.

I think this should just be changed to `props.value` (`props` being the first argument of the `constructor`) and eliminate `componentDidMount` altogether. Otherwise, we're completely disregarding `value` from the `props` for the initial (albeit ultimately wasteful) render.

>You may call setState() immediately in componentDidMount(). It will trigger an extra rendering, but it will happen before the browser updates the screen. This guarantees that even though the render() will be called twice in this case, the user won’t see the intermediate state. Use this pattern with caution because it often causes performance issues. **In most cases, you should be able to assign the initial state in the constructor() instead**. It can, however, be necessary for cases like modals and tooltips when you need to measure a DOM node before rendering something that depends on its size or position.

https://reactjs.org/docs/react-component.html#componentdidmount

_(Emphasis mine)_

Comment (westonruter) [reply packages/components/src/focal-point-picker/index.js]: Done in 9b1b02993b8216bb79b912d5aea3f1cd4e25d12d

Comment (jeffersonrabb) [reply packages/components/src/focal-point-picker/index.js]: This looks good to me and tests just fine. Thinking back, I believe I set the percentages in `componentDidMount` because of an earlier approach to determining the image's dimensions, which I moved away from before submitting the initial Pull Request. Agree with @westonruter it's not necessary.

**Review by swissspidy — APPROVED** [review]

**Review by aduth — APPROVED** [review]
