### PR TITLE
FIX: Link Dialog's position appears randomly generated

### LINKED ISSUE #3211: Link Dialog's position appears randomly generated
## Issue Overview

When activating the inline link dialog, it appears in an unexpected position.

## Steps to Reproduce (for bugs)

1. Enter a paragraph block
2. Click on the link icon in the docked toolbar

## Expected Behavior

Either the link popup would show near the content being linked, or the link popup would show in the same position with respect to the docked toolbar. I'm not sure ... @jasmussen @karmatosed ?

## Current Behavior

The popup appears mostly near the toolbar, with a horizontal position that seems related to the selection rectangle.

## Possible Solution

There may have been some additional CSS that `getFocusPosition` now needs to consider when calculating a position.

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by tg-ephox**
## Description

fixes: https://github.com/WordPress/gutenberg/issues/3211

Moving the FormatToolbar out of the block caused the LinkDialog's offsetParent to be incorrect.

## How Has This Been Tested?

Manual browser testing

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by tg-ephox** [comment]
Not sure if this is the best approach... it might make more sense to move the positioning styles to the `Slot` (or wrapper). 

An alternative would be to add the current node's (within Editable) position to redux global state, although this could be costly as arrowing through a block's text would cause a lot to re-render (I believe its only fired on word or format change though). 

One thing still broken is links within a table block, the `overflow-x: auto` style would need to be removed from `wp-block-table` for the link dialog to appear.

File: blocks/editable/index.js [hunk 1]
```diff
@@ -709,6 +709,7 @@ export default class Editable extends Component {
 						{ MultilineTag ? <MultilineTag>{ placeholder }</MultilineTag> : placeholder }
 					</Tagname>
 				}
+				{ focus && <Slot name="Formatting.LinkDialog" /> }
```
Comment (youknowriad) [inline blocks/editable/index.js]: Should we rename the slot. I think it's meaning should be something related to its position and not what's inside it. Maybe something like `Editable` or  `Editable.Siblings`

**Review by youknowriad — APPROVED** [review]
Nice Fix, Left a minor comment but this work great
