### PR TITLE
[RTC] Fix performance regression on post save

### LINKED ISSUE #76352: RTC: WordPress 7.0 critical performance drop in save function
### Description

I found that latest beta 7.0-beta3-61869 has huge performance issue that will kill performance of almost every site in editor

Currently, it's rerendering everything that in save function near 80 times per each block

[https://cleanshot.com/share/1xMjMNVJ](https://cleanshot.com/share/1xMjMNVJ)

Condition - no plugins, except test plugin, 7.0 beta, any theme

code of plugin for testing is simple, just console.log in edit and save function. 

```ja
(function (blocks, element) {
    var el = element.createElement;

    blocks.registerBlockType('simple/text-block', {
        title: 'Simple Text Block',
        icon: 'universal-access-alt',
        apiVersion: 3,
        category: 'common',

        edit: function (props) {
            console.log('Block properties:', props);
            return el('p', {}, 'This is a simple text block.');
        },

        save: function (props) {
            console.log(props)
            return el('p', {}, 'This is a simple text block.');
        }
    });
})(
    window.wp.blocks,
    window.wp.element
);
```

### Step-by-step reproduction instructions

1. Install 7.0 beta 3
2. Create simple gutenberg custom block with only console.log in edit and save
3. Add test block and save post
4. Reload and check console.log
5. It will show near 70-80 logs from save function (not normal), and near 2-3 from edit function (normal)

Switching back to 6.9 will return everything to normal

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [x] Classic
- [x] Hybrid (e.g. classic with theme.json)
- [x] Not sure

### PR DESCRIPTION
**Pull request by maxschmeling**
## What?

Fixes #76352 

## Why?

The CRDT sync system always includes blocks in the changes it dispatches to the entity store on initialization, even when the blocks haven't changed. This is by design — the comment in getPostChangesFromCRDTDoc notes that "consumers of blocks have memoization that renders optimization here unnecessary."

However, the `getEditedPostContent` selector — one such consumer — had no memoization. It's a createRegistrySelector that calls `__unstableSerializeAndClean(record.blocks)` on every access, which invokes each block's save function. Before collaboration, this code path was rarely hit because blocks was never set directly in entity edits (it was derived from content via the transient read callback). With collaboration enabled, the sync system sets blocks in entity edits on load, causing this branch to run on every selector access across all subscribed components.

## How?

Wraps `getEditedPostContent` with `createSelector`, using `[record?.content, record?.blocks]` as dependants. The expensive serialization now runs once per unique blocks/content reference and returns the cached result for all subsequent accesses within the same state.

## Testing Instructions

Follow the reproduction steps from the linked issue. There is a simple plugin that registers a block that will `console.log` every time the `save` function is called. Before this fix you will see it fire many times on post save, and then much fewer after this fix.

### CODE REVIEW

**Comment by ingeniumed** [comment]
Confirmed that the `getDependents` function is working as intended when the content/blocks are changed, which in turn triggers a new value for the selector.

**Review by ingeniumed — APPROVED** [review]

**Comment by Mamaduka** [comment]
The `[record?.content, record?.blocks]` as dependants can be problematic. These values change as the user types, and if the cached value isn't garbage-collected, we can run into memory issues. @aduth, any recommendations here? 

P.S. @jsnajdr, this reminded me of our recent conversation from #75894.

**Comment by jsnajdr** [comment]
> These values change as the user types, and if the cached value isn't garbage-collected, we can run into memory issues.

When the dependant is an object, like `record.blocks` is, then `rememo` stores it as a weakmap key. Such a cache record gets GC-ed automatically when `record.blocks` becomes outdated and goes out of scope. Therefore, this looks fine.

With `record.content`, the value can be a function. Memoizing by the function value is not 100% correct, because the function is called with the `record` as an argument. The same function can produce different results. But looking how the function is created and assigned:

https://github.com/WordPress/gutenberg/blob/75e9b0c1c8d352ab2f9e407b73ea77c5192cdcf2/packages/core-data/src/hooks/use-entity-block-editor.js#L97-L102

there is a new instance on each change, so in practice the memoization should be ok.

However, what we are _really_ trying to memoize here is not the `getEditedPostContent` selector, but just the `__unstableSerializeAndClean` function. It can be called either directly by the selector, or indirecty inside the `record.content` callback.

So, a better approach would be to memoize the `__unstableSerializeAndClean` function. Store the single `blocks` argument as a weakmap key, and cache the serialized string as the weakmap value. That's more straightforward and more universal: it optimizes all usages.

**Comment by maxschmeling** [comment]
@jsnajdr that was actually the first approach. I wanted to try for something that felt a little more idiomatic which led to the second commit in this PR, but you're right that the goal is really to memoize the internal call to `__unstableSerializeAndClean `. I've reverted back to the `WeapMap` cache for `__unstableSerializeAndClean`

Thanks for the feedback.

**Comment by maxschmeling** [comment]
@jsnajdr it was pointed out to me by @ingeniumed that my first approach was memoizing inside of `getEditedPostContent` and that you meant memoize further down inside of `__unstableSerializeAndClean` so I pushed [fd97049](https://github.com/WordPress/gutenberg/pull/76370/commits/fd97049461b53b18e556b0a5e195a0d9b027ed8a) to push the memoization down to that level.

File: packages/editor/src/store/selectors.js [hunk 1]
```diff
@@ -929,7 +929,7 @@ export const getEditedPostContent = createRegistrySelector(
 			if ( typeof record.content === 'function' ) {
 				return record.content( record );
 			} else if ( record.blocks ) {
-				return __unstableSerializeAndClean( record.blocks );
+				return __unstableSerializeAndClean( record.blocks ) || '';
```
Comment (ingeniumed) [inline packages/editor/src/store/selectors.js]: Would this change now be needed anywhere where `__unstableSerializeAndClean` is used? If yes, would make it so that `__unstableSerializeAndClean` returns that rather than updating all the usages.

Comment (maxschmeling) [reply packages/editor/src/store/selectors.js]: It isn't needed, or at least isn't part of this fix.

Removed 63c880c89ef

**Review by ingeniumed — APPROVED** [review]

**Review by jsnajdr — COMMENTED** [review]
Yes, the latest version of the patch looks nice, thanks for working on this :+1:
