### PR TITLE
Fix styles declarations returning before all properties output

### LINKED ISSUE #42913: Site Editor: Root padding support in theme.json and no colors
### Description

Adding support for root padding in theme.json causes no color rendering in the Site Editor.

### Step-by-step reproduction instructions

Depending on the setting in `useRootPaddingAwareAlignments` in theme.json, follow the video demonstration below.

### Screenshots, screen recording, code snippet

**Before:**
```
"settings": {
   "useRootPaddingAwareAlignments": false
}
```
before

**After:**

```
"settings": {
   "useRootPaddingAwareAlignments": true
}
```

after

### Environment info

WordPress version: **6.0.1** and **6.1-alpha-53810**
Gutenberg version: **13.9.20220731**

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

Fixes #42913.

## Why?

When `useRootPaddingAwareAlignments` is set, `getStylesDeclarations` returns before all the global style properties are output. This means colour changes in global styles aren't reflected in the editor.

## How?

Change the function logic so it only omits `padding` properties when `useRootPaddingAwareAlignments` is enabled, as well as _not_ outputting the variables if the setting is disabled.

Adds tests to check for correct behaviour.

## Testing Instructions

1. In theme.json settings, add `"useRootPaddingAwareAlignments": true`;
2. In the global styles sidebar in the site editor, change the color or background settings;
3. Check that those changes have a visible effect in the editor;
4. Change `"useRootPaddingAwareAlignments"` back to `false`;
5. Check that everything still works as expected.
6. As a bonus, check that either the variables _or_ the padding properties are output for `.editor-styles-wrapper`, but not both.

### CODE REVIEW

File: packages/edit-site/src/components/global-styles/use-global-styles-output.js [hunk 1]
```diff
@@ -211,6 +211,16 @@ function getStylesDeclarations(
 
 			const styleValue = get( blockStyles, pathToValue );
 
+			// Root-level padding styles don't currently support strings with CSS shorthand values.
+			// This may change: https://github.com/WordPress/gutenberg/issues/40132.
+			if (
+				( key === '--wp--style--root--padding' &&
+					typeof styleValue === 'string' ) ||
+				! useRootPaddingAlign
```
Comment (andrewserong) [inline packages/edit-site/src/components/global-styles/use-global-styles-output.js]: For this condition, is it possible that more declarations will be skipped than desired if `! useRootPaddingAlign` evaluates to `true`? I was wondering if the condition is meant to be just for the `--wp--style--root--padding` key, like:

```js
			if (
				key === '--wp--style--root--padding' &&
				( typeof styleValue === 'string' || ! useRootPaddingAlign )
			) {
				return declarations;
			}
```

Apologies if I'm not understanding the logic here correctly!

Comment (andrewserong) [reply packages/edit-site/src/components/global-styles/use-global-styles-output.js]: It looks like `fontFamily` is one of the few ones that isn't using the style engine, so I found it a little challenging to work out an error state for this one, but I _think_ the following test seems to catch it:

```js
		it( 'Should output padding and font family properties if useRootPaddingAwareAlignments is disabled', () => {
			const blockStylesWithFontFamily = {
				...blockStyles,
				typography: {
					fontFamily: 'sans-serif',
				},
			};
			expect(
				getStylesDeclarations(
					blockStylesWithFontFamily,
					'body',
					false
				)
			).toEqual( [
				'font-family: sans-serif',
				'background-color: var(--wp--preset--color--light-green-cyan)',
				'padding-top: 33px',
				'padding-right: 33px',
				'padding-bottom: 33px',
				'padding-left: 33px',
			] );
		} );
```

**Review by andrewserong — COMMENTED** [review]
Nice work figuring out this one @tellthemachines (and for adding additional tests 🎉 )! Skipping the output in the loop over `extraRules` looks like a good approach to me 👍. I just left a comment about the condition to skip the variable output, as it looks like it might be unexpectedly returning early.

Aside from that though, this is otherwise testing nicely for me manually in the site editor with TwentyTwentyTwo and Emptytheme and resolves the issue with color output.

File: packages/edit-site/src/components/global-styles/use-global-styles-output.js (hunk 1 above)
Comment (andrewserong) [reply packages/edit-site/src/components/global-styles/use-global-styles-output.js]: Oh, I've found a better real world example with the Duotone feature. In TwentyTwentyTwo, if you add the following to the `theme.json` file (from https://github.com/WordPress/gutenberg/pull/37727) to switch on a particular Duotone for image blocks:

```json
{
	"styles": {
		"blocks": {
			"core/image": {
				"filter": {
					"duotone": "var(--wp--preset--duotone--foreground-and-secondary)"
				}
			}
		}
	}
}
```

| Expected | Actual |
| --- | --- |
| image | image |

The above change appears to fix it.

Comment (tellthemachines) [reply packages/edit-site/src/components/global-styles/use-global-styles-output.js]: Oh, good catch! Yes, the parentheses should be around the OR as you suggested 😄

**Comment by tellthemachines** [comment]
@andrewserong thanks for reviewing and kindly providing the extra test! I fixed the issue, and added font-family to the initial block styles in the test, so now we can check that it gets output on all three tests.

**Review by andrewserong — APPROVED** [review]
Excellent, thanks for fixing that up, this is working nicely for me now @tellthemachines! 🎉 

image

LGTM 🚀

**Review by aristath — APPROVED** [review]

**Comment by ndiego** [comment]
@tellthemachines, @andrewserong, @andrewserong would this be a candidate for a 13.8.x release? The root issue is impacting quite a range of things. I just discovered that some theme.json style settings are not getting output, notably those for template parts. With this fix, everything now works like a charm.

**Comment by tellthemachines** [comment]
@ndiego it's not a huge change so should be fine to add to the next minor release, yes!
