### PR TITLE
Edit Widgets: Don't run Customizer setup on every preview refresh.

### LINKED ISSUE #16538: Gutenberg 6.1.0 breaks the customizer ( blank screen ) after deactivation of the plugin
Hi guys, after playing a little bit with the latest widget block in the customizer, I could not access the customizer anymore.
I tested several times on a fresh WP install, and could reproduce the problem.
Here's the detailed problem + screenshot.

**Describe the bug**
After activating Gutenberg plugin ( v6.1.0 ), doing some customizations, and deactivating Gutenberg, it is not possible to customize the site anymore. 
The customizer preview frame is blank. And the console log displays the error : _Uncaught SyntaxError: Unexpected token <_

In the Html code of the page, the PHP error is 

> <br />
> <b>Warning</b>:  array_intersect(): Argument 1 is not an array in <b>/srv/www/wp-betas/htdocs/wp-includes/class-wp-customize-widgets.php</b> on line <b>1380</b><br />
> <br />
> <b>Warning</b>:  array_values() expects parameter 1 to be array, null given in <b>/srv/www/wp-betas/htdocs/wp-includes/class-wp-customize-widgets.php</b> on line <b>1380</b><br />

**To reproduce**
Start from a fresh install ( not mandatory ) with the latest WP version
1. Activate the Twenty Nineteen theme
2. Activate Gutenberg latest version
3. Open the customizer
4. Open the Homepage settings ( Screenshot 1 )
   - select "A static page" and pick "Sample page"
   - publish
   - exit the customizer
5. deactivate Gutenberg plugin
6. open the customizer : you should see a blank screen with a console.log error : Screenshot 2 and 3

**Expected behavior**
The customizer should work after deactivating Gutenberg.

**Screenshots**
### Screenshot 3

**Desktop :**
 - OS: Windows
 - Browser : chrome
 

**Additional context**
- Gutenberg v6.1.0
- WordPress v5.2.2
- Twenty Nineteen v1.4

Thanks

### PR DESCRIPTION
**Pull request by epiqueras**
cc @jorgefilipecosta 

Fixes #16538 

## Description

The Customizer runs the `preview-ready` event that was being used to sync the store with Changeset data on every preview refresh. This meant that changing any setting that triggered a refresh would convert all sidebars to block widget areas, because on subsequent calls, the handler would see the newly loaded data as different and add it to the widget blocks Changeset entry.

This was an issue because block widget areas break legacy widget editing when Gutenberg is disabled and the conversion to widget blocks here was not explicit.

## How has this been tested?

The steps in #16538 were followed and everything worked as expected.

## Types of Changes

*Bug Fix:* Don't run Customizer setup on every preview refresh to avoid implicitly saving sidebars as block widget areas.

## Checklist:

- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows the accessibility standards.
- [x] My code has proper inline documentation.
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/edit-widgets/src/components/customizer-edit-widgets-initializer/sync-customizer.js [hunk 1]
```diff
@@ -78,9 +78,19 @@ const updateSettingInputValue = throttle( ( nextWidgetAreas ) => {
 
 // Check that all the necessary globals are present.
 if ( window.wp && window.wp.customize && window.wp.data ) {
+	let ran = false;
 	// Wait for the Customizer to finish bootstrapping.
 	window.wp.customize.bind( 'ready', () =>
```
Comment (jorgefilipecosta) [inline packages/edit-widgets/src/components/customizer-edit-widgets-initializer/sync-customizer.js]: Can't we defer all this initialization until the Widget Blocks section is opened for the first time?

**Review by jorgefilipecosta — APPROVED** [review]
I was not able to replicate the issue where the customizer totally crashed, but following the exact same steps, the widgets disappeared from the website during a non-related customizer change when the plugin was deactivated and with these changes that's not the case.

File: packages/edit-widgets/src/components/customizer-edit-widgets-initializer/sync-customizer.js (hunk 1 above)
Comment (epiqueras) [reply packages/edit-widgets/src/components/customizer-edit-widgets-initializer/sync-customizer.js]: I couldn't find any relevant events in the API. We could manually add a listener to the section title element. Should I explore that?

Comment (jorgefilipecosta) [reply packages/edit-widgets/src/components/customizer-edit-widgets-initializer/sync-customizer.js]: I don't think that's a blocker but it would be nice to explore that, as it provides an extra layer to avoid problems for users that never opened the section.

Comment (epiqueras) [reply packages/edit-widgets/src/components/customizer-edit-widgets-initializer/sync-customizer.js]: I've given this more thought.

>Imaging a scenario where some plugin disables/removes the filters to add the new widget block section, in this case, we should not execute this code.

It wouldn't conflict or throw any errors, because all the element selecting and referencing happens inside a try block or has if guards.

I think we should avoid the complexity of selecting yet another element with a css selector if possible, specially the one that boots everything up. I can see a scenario where the click handler is not attached because the section is not rendered in the UI yet, but it wouldn't have been a problem with the current code, because it would have just started syncing once all the necessary elements are rendered.

**Comment by Nikeo** [comment]
( I first posted in #16538, but I think this is a better place here ! )
@epiqueras in your fix, from what I understand, you prevent the problem from happening. But what about websites that have been broken already ?
Can you confirm that this fix will "clean" the broken widgets, and then allow users to disable Gutenberg and let them open the customizer without activating Gutenberg permanently again ?

**Comment by youknowriad** [comment]
@Nikeo I think you may be able fix the issue by doing this:

 - Active Gutenberg
 - Go the widgets screen
 - Remove all the widgets and add your own widgets back
 - Disable Gutenberg.

**Comment by Nikeo** [comment]
OK thanks. This fix process might be potentially useful for many users that have disabled Gutenberg and find themselves locked with a broken customizer, without understanding why.

**Comment by epiqueras** [comment]
Note that you can still explicitly/intentionally save block widget areas, disable Gutenberg, and find that your Customizer and old Widgets screen are broken.

If you are using widget blocks and need to disable Gutenberg, you need to first go to the old widgets screen and delete all widgets.

We should document this somewhere for users if you think it will be common.

**Comment by Nikeo** [comment]
yes, at least document it is important. But I'm not comfortable with the idea that WP core features like the customizer can be broken when disabling a plugin. It took me time to understand where the problem could come from, and I'm a developer. A non developer user won't know where to look for.
To me disabling Gutenberg should leave WordPress without bugs.

**Comment by epiqueras** [comment]
Yeah we should also have code that deletes the sidebars for them (after warning them) when they disable Gutenberg and have widget blocks saved.

**Comment by Nikeo** [comment]
yes this makes totally sense to me.
