### PR TITLE
Include namespace in layout classname for non-core blocks

### LINKED ISSUE #53295: Compound block and layout type classname incorrect for custom blocks
### Description

As per [Layout updates in the editor for WordPress 6.3](https://make.wordpress.org/core/2023/07/14/layout-updates-in-the-editor-for-wordpress-6-3/):

> In 6.3, a new classname is added to the inner wrapper of all blocks with layout, comprised of block classname + layout classname, e.g.: `.wp-block-cover-is-layout-constrained`.

However, this does not work for third-party blocks since the vendor prefix of the block gets cut off in the class name generated in markup, but the CSS generated from the style engine has the prefix.

Given the block detailed in the code snippet further down, you'll get markup like this in the block editor:

```html
<div … class="block-editor-block-list__block wp-block wp-block-foo-bar">
  <div class="block-editor-block-list__layout is-layout-flow wp-block-bar-is-layout-flow" …>
```

With the associative CSS (where `settings.styles.blocks.foo/bar.spacing.blockGap` has been set to `var(--wp--preset--spacing--12)` in `theme.json`):

```css
…
.editor-styles-wrapper .wp-block-foo-bar-is-layout-flow > :first-child:first-child {
  margin-block-start: 0;
}

.editor-styles-wrapper .wp-block-foo-bar-is-layout-flow > :last-child:last-child {
  margin-block-end: 0;
}

.editor-styles-wrapper .wp-block-foo-bar-is-layout-flow > * {
  margin-block-start: var(--wp--preset--spacing--12);
  margin-block-end: 0;
}
…
```
Notice how the combined CSS classes like `wp-block-foo-bar-is-layout-flow` have `wp-block-foo-bar-` but the class name on the HTML block itself is `wp-block-bar-`.

This difference seems to be due to the `packages/block-editor/src/hooks/layout.js` only looking at the second part of the block name after the slash (`/`):

https://github.com/WordPress/gutenberg/blob/00a1b6e06c02bb546667017a70f2f72dc64d4127/packages/block-editor/src/hooks/layout.js#L69-L76

when building the class name for HTML.

This behavior is mirrored for server side layout supports PHP code, from [the `6.3` branch](https://github.com/WordPress/wordpress-develop/blob/3c8b106084d55e2a9da22492ecd9a5812b1cdf64/src/wp-includes/block-supports/layout.php#L701-L703):

```php
// Add combined layout and block classname for global styles to hook onto.
$block_name    = explode( '/', $block['blockName'] );
$class_names[] = 'wp-block-' . end( $block_name ) . '-' . $layout_classname;
```
Again, only looking at the second part of the block name after the slash (`/`).

The CSS I believe comes from [`WP_Theme_JSON::get_layout_styles()`](https://github.com/WordPress/wordpress-develop/blob/3c8b106084d55e2a9da22492ecd9a5812b1cdf64/src/wp-includes/class-wp-theme-json.php#L1263-L1438) and we can see the difference with how the CSS is constructed:

```php
$selector = isset( $block_metadata['selector'] ) ? $block_metadata['selector'] : '';
// $selector = '.wp-block-foo-bar'

// …

$format          = static::ROOT_BLOCK_SELECTOR === $selector ? ':where(%s .%s) %s' : '%s-%s%s';
$layout_selector = sprintf(
  $format,                  // = '%s-%s%s'
  $selector,                // = '.wp-block-foo-bar'
  $class_name,              // = 'is-layout-flow'
  $spacing_rule['selector'] // = ' > *', 
);
// $layout_selector = '.wp-block-foo-bar-is-layout-flow > *'
```

### Step-by-step reproduction instructions

1. Create a custom block like the example provided in the code snippets further down.
2. Insert into a post.
3. See that an incorrect compound block and layout type class name is applied to the inner `<div>`, both in the editor or in the live webpage.

### Screenshots, screen recording, code snippet

Example block:

`block.json`:
```json
{
  "apiVersion": 3,
  "name": "foo/bar",
  "title": "Foo Bar",
  "supports": {
    "layout": true
  },
  "editorScript": "file:./index.js"
}
```
`index.js`:
```jsx
import { useBlockProps, useInnerBlocksProps } from '@wordpress/block-editor';
import { registerBlockType } from '@wordpress/blocks';

registerBlockType( 'foo/bar', {
  edit: function FooBarEdit() {
    const blockProps = useBlockProps();
    const innerProps = useInnerBlocksProps();
  
    return (
      <div { ...blockProps }>
        <div { ...innerProps } />
      </div>
    );
  },
  save: function FooBarSave() {
    const blockProps = useBlockProps.save();
    const innerProps = useInnerBlocksProps.save();

    return (
      <div { ...blockProps }>
        <div { ...innerProps } />
      </div>
    );
  },
}
```
`index.js` (no build step neccessary):
```js
const { useBlockProps, useInnerBlocksProps } = wp.blockEditor;
const { createElement } = wp.element;

wp.blocks.registerBlockType( 'foo/bar', {
  edit: function FooBarEdit() {
    const blockProps = useBlockProps();
    const innerProps = useInnerBlocksProps();
  
    return createElement( 'div', blockProps, [
      createElement( 'div', innerProps ),
    ] );
  },
  save: function FooBarSave() {
    const blockProps = useBlockProps.save();
    const innerProps = useInnerBlocksProps.save();

    return createElement( 'div', blockProps, [
      createElement( 'div', innerProps ),
    ] );
  },
}
```

### Environment info

WordPress 6.3-RC3-56344

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

Fixes #53295.

The compound [block name]-[layout name] classname generated for layout blocks should take into account the block namespace if it's not a core block.

## Testing Instructions

1. Install and activate a custom block with layout and block spacing support, or use [this test one](https://github.com/WordPress/gutenberg/files/12287041/layouty.zip).
2. Add the custom block to a post and check that the compound classname includes the block namespace in the editor and front end.
3. In global styles, set a global spacing value for the custom block.
4. Check that the spacing styles are attached to the correct compound classname in the editor and front end.

### CODE REVIEW

File: lib/block-supports/layout.php [hunk 1]
```diff
@@ -686,8 +686,9 @@ function gutenberg_render_layout_support_flag( $block_content, $block ) {
 	}
 
 	// Add combined layout and block classname for global styles to hook onto.
-	$block_name    = explode( '/', $block['blockName'] );
-	$class_names[] = 'wp-block-' . end( $block_name ) . '-' . $layout_classname;
+	$split_block_name = explode( '/', $block['blockName'] );
+	$full_block_name  = 'core' === $split_block_name[0] ? $split_block_name[1] : implode( '-', $split_block_name );
```
Comment (andrewserong) [inline lib/block-supports/layout.php]: Tiny nit: `$split_block_name[1]` assumes the array will have at least two elements. Should we re-use `end()` to account for a custom block registered with the whole name `core`? I think that might wind up being something like:

```suggestion
	$full_block_name  = 'core' === $split_block_name[0] ? end( split_block_name ) : implode( '-', $split_block_name );
```

File: packages/block-editor/src/hooks/layout.js [hunk 2]
```diff
@@ -69,9 +69,12 @@ export function useLayoutClasses( blockAttributes = {}, blockName = '' ) {
 	if ( LAYOUT_DEFINITIONS[ usedLayout?.type || 'default' ]?.className ) {
 		const baseClassName =
 			LAYOUT_DEFINITIONS[ usedLayout?.type || 'default' ]?.className;
-		const compoundClassName = `wp-block-${ blockName
-			.split( '/' )
-			.pop() }-${ baseClassName }`;
+		const splitBlockName = blockName.split( '/' );
+		const fullBlockName =
+			splitBlockName[ 0 ] === 'core'
+				? splitBlockName[ 1 ]
```
Comment (andrewserong) [inline packages/block-editor/src/hooks/layout.js]: Similar to the other comment, to account for a potential custom block called `core` (with no namespace), should we retain the use of `.pop()` in this side of the ternary?

**Review by andrewserong — COMMENTED** [review]
Oh good catch! Just left a couple of comments about whether we can avoid accessing the second element of an array in case anyone winds up registering a block with name `core` with no namespace. Probably very edge-casey, though!

File: lib/block-supports/layout.php (hunk 1 above)
Comment (tellthemachines) [reply lib/block-supports/layout.php]: Sure we can do that!

**Comment by tellthemachines** [comment]
Thanks for reviewing @andrewserong ! Feedback has been addressed.

**Comment by ramonjd** [comment]
Testing after [feedback](https://github.com/WordPress/gutenberg/pull/53404#issuecomment-1668887126):

### Before

`wp-block-my-test-block-is-layout-constrained` (no block namespace)

Screenshot 2023-08-08 at 2 28 48 pm

### After

`wp-block-create-block-my-test-block-is-layout-constrained` (with block namespace)

Screenshot 2023-08-08 at 2 29 53 pm


👍🏻

File: lib/block-supports/layout.php (hunk 1 above)
Comment (ramonjd) [reply lib/block-supports/layout.php]: I'm not sure it's possible to have more than one `/` in a block name anyway? It'll throw a `Notice: Function WP_Block_Type_Registry::register was called incorrectly.` warning.

Only mentioning because accessing via index might be a tick faster? Probably by `0.00000001` of a nanosecond 😄

**Review by andrewserong — APPROVED** [review]
Thanks for the update, this is testing well for me, too!

✅ Namespace on non-core blocks is included in the classname in the editor:

image

✅ Namespace on non-core blocks is included in the classname in the site frontend:

image

✅ Core blocks (Group, Cover, etc) are unaffected by the change in logic

LGTM! ✨

File: lib/block-supports/layout.php (hunk 1 above)
Comment (andrewserong) [reply lib/block-supports/layout.php]: Hrm, good point! I'd assumed you could register a block without a namespace (so, no `/` character), but it looks like you can't: https://github.com/WordPress/wordpress-develop/blob/5ebe28966e5decbe1862c147bf98db0d8094038e/src/wp-includes/class-wp-block-type-registry.php#L73

I was quite possibly overthinking this! I'm usually quite scared of PHP notices surrounding accessing indexes that aren't available, largely due to my own past mistakes 😅

Comment (ramonjd) [reply lib/block-supports/layout.php]: Me too! I think it's fine to leave all the same. `end()` does change the index pointer, but I don't think that's a problem for the rest of the code in this instance.

I was also curious to see whether I could register a custom block with the name `core/something` but it turns out I can't. 🤷🏻

**Comment by cb3rnard** [comment]
Any idea when theses changes will be passed on to Wordpress' block-supports/layout.php ?
It might not be the right place to ask about that, but the issue is still active and I can't find any info about it.

**Comment by t-hamano** [comment]
I think this PR needs to be backported to the core. See https://core.trac.wordpress.org/ticket/63839

**Comment by tellthemachines** [comment]
> I think this PR needs to be backported to the core.

Yes! Here's a PR: https://github.com/WordPress/wordpress-develop/pull/9532
