### PR TITLE
File block: Fix editing of empty file name 

### LINKED ISSUE #50421: File block: Can not select and edit the link text
### Description

When you add a file block, select a file, delete the link text, _and click anywhere outside the block_, you can no longer select the placeholder text. Instead, the cursor is placed on the download button.

### Step-by-step reproduction instructions

1. Add a new file block in the block editor.
2. Select a file.
3. Delete the link text so that the placeholder text shows.
4. Click anywhere in the editor; outside the block.
5. Try to place the mouse cursor in the placeholder to add a new text.
6. Find that the download button is selected instead.

(Navigating to the placeholder with the keyboard still works).

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/7422055/236742986-20c19b73-93a8-4b97-b887-5c98ca0c4635.mov

### Environment info

WordPress 6.2
Gutenberg 15.7.0
Chrome
Twenty Twenty-Three

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by n2erjo00**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/50421

Added wrapper element "wp-block-file__button-richtext-wrapper" for the RichText component.

## Why?
Issue was pointed out by #50421 

## How?
If File block was added and then file name was erased from RichText user was unable to re-edit the RichText content.

## Testing Instructions
1. Open post or page and File block
2. Once added name of the file is added as the name of file in the editor
3. Erase that to see placeholder
4. Click on some other block
5. Re-edit the name of file in the File block.
   - If checkout trunk and do same steps you are unable to re-edit the name of the file

### CODE REVIEW

File: packages/block-library/src/file/edit.js [hunk 1]
```diff
@@ -271,16 +271,18 @@ function FileEdit( { attributes, isSelected, setAttributes, clientId } ) {
...
-						tagName="a"
-						value={ fileName }
-						placeholder={ __( 'Write file name…' ) }
-						withoutInteractiveFormatting
-						onChange={ ( text ) =>
-							setAttributes( { fileName: text } )
-						}
-						href={ textLinkHref }
-					/>
+					<div className="wp-block-file__button-richtext-wrapper">
```
Comment (ntsekouras) [inline packages/block-library/src/file/edit.js]: Thanks for the PR @n2erjo00! We don't need to add an extra wrapper here. I don't remember the reason, but there where some issues with RichText and `inline` elements(a), so applying a `display:inline-block` would suffice.

Since we would need to target both front and back end, and there are different selectors, maybe something like that in `style.scss` could do the job.

```
.wp-block-file {
	a:not(.wp-block-file__button) {
		display: inline-block;
	}
}
```

Comment (n2erjo00) [reply packages/block-library/src/file/edit.js]: Cool 👍 You were right about this one. Added the css fix for this

**Review by ntsekouras — APPROVED** [review]
LGTM, thank you @n2erjo00 !
