### PR TITLE
`@wordpress/components`: lint and fix `@wordpress/components-no-missing-40px-size-prop` rule

### LINKED ISSUE #71683: Button: Suppress  `__next40pxDefaultSize` warning if the variant is link
## What problem does this address?

Related to #65840

The Gutenberg project has an ESLint rule that displays a warning message if a component is the default size and does not have a `__next40pxDefaultSize` prop:

https://github.com/WordPress/gutenberg/blob/aa3b96150333d9102fe3bbb07cff3041fda69a3b/.eslintrc.js#L342-L346

This rule applies to `Button` components whose variant is `link`:

Image

However, this prop is not actually necessary for `Button` components with the `link` variant, as their height is auto:

Image

Personally, I find this warning a bit annoying.

## What is your proposed solution?

My suggestions are:

- Make an exception to the ESLint rule, and in the case of the variant link button, do not output a warning even though `__next40pxDefaultSize` is missing.
- Don't apply the `is-next-40px-default-size` css class for `Button` components with the `link` variant. For example:

  ```diff
  diff --git a/packages/components/src/button/index.tsx b/packages/components/src/button/index.tsx
  index 0ab6b24b4d..38af680468 100644
  --- a/packages/components/src/button/index.tsx
  +++ b/packages/components/src/button/index.tsx
  @@ -146,7 +146,8 @@ export function UnforwardedButton(
          ];
   
          const classes = clsx( 'components-button', className, {
  -               'is-next-40px-default-size': __next40pxDefaultSize,
  +               'is-next-40px-default-size':
  +                       __next40pxDefaultSize && variant !== 'link',
                  'is-secondary': variant === 'secondary',
                  'is-primary': variant === 'primary',
                  'is-small': size === 'small',
  ```

cc @WordPress/gutenberg-components

### PR DESCRIPTION
**Pull request by ciampo**
## What?

Following up the work from https://github.com/WordPress/gutenberg/pull/74611, this PR applies the `@wordpress/components-no-missing-40px-size-prop` ESLint rule to the `@wordpress/components` package and then applies all the necessary changes to fix all the resulting violations.

## Why?

The code in the `@wordpress/components` package should be using its own components correctly too, holding itself to the same standards as its consumers.

This has a few advantages:

- better Storybook examples (including code snippets)
- less expections, more clarity

## How?

- Enabled the `@wordpress/components-no-missing-40px-size-prop` for local imports in the `@wordpress/components`
- Tweaked the rule to exempt `Button` components with `variant="link"`
- Fixed all errors one by one

## Testing Instructions

- Review the code
- Try to introduce a lint error (ie. omitting the `__next40pxDefaultSize` prop), make sure that the linter correctly reports it

### CODE REVIEW

File: packages/eslint-plugin/rules/components-no-missing-40px-size-prop.js
Comment (ciampo) [inline packages/eslint-plugin/rules/components-no-missing-40px-size-prop.js:1]: Changes to the lint rule:

- lint local default imports
- exempt `<Button variant="link" />` 
- add more component to the list of components to check

File: .eslintrc.js [hunk 1]
```diff
@@ -245,7 +245,7 @@ module.exports = {
 				'packages/*/src/**/*.[tj]s?(x)',
 				'storybook/stories/**/*.[tj]s?(x)',
 			],
-			excludedFiles: [ '**/*.native.js' ],
+			excludedFiles: [ '**/*.@(android|ios|native).[tj]s?(x)' ],
```
Comment (ciampo) [inline .eslintrc.js:248]: I decided to use `**/*.@(android|ios|native).[tj]s?(x)` everywhere, as it seems like the most complete glob for native files

**Comment by ciampo** [comment]
In a lot of cases, I opted for adding an explicit `__next40pxDefaultSize`, even when:

- the prop wouldn't make any difference (like in unit tests)
- the component would already receive the `__next40pxDefaultSize` (for example, via Storybook args)

I otherwise decided to skip the rule check if the parent component is also linted for the same rule and is forwarding the `__next40pxDefaultSize` prop.

**Review by mirka — APPROVED** [review]
Looks good 👍
