### PR TITLE
Fix MediaReplaceFlow to select media in media library on replace

### LINKED ISSUE #20040: Image Replace - Open Media Library - Media Library does not open with the current image selected
**Describe the bug**
When wanting to edit the caption/description/title associated with an image in the media library, you cannot do so easily from within a post because the only way to edit that data is to click on Replace which does not select the image when you arrive in the Media Library. In previous versions, the image was selected in the Media Library.

**To reproduce**
1. Go to a post written a long time ago, on a site with several thousand images.
2. Click on replace for the image
3. Now find the image whose details you wanted to edit -- It's  almost impossible 

**Expected behavior**
When clicking Replace -> Open Media Library; the current image should be selected. This was the previous behavior of this function before the 'Replace' button was introduced.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Firefox
 - Version: latest/irrelevant.

**Additional context**
- Gutenberg 7.3.0

### PR DESCRIPTION
**Pull request by draganescu**
## Description
Closes #20040

Props: @Ringish Thank you for the quick fix.

## How has this been tested?
Tested locally.

To test:

- add any media block
- select media from library
- try to replace from library
- the current media should be selected

## Types of changes
I have fixed all the media blocks which implement `MediaReplaceControl` to have this behavior.

### CODE REVIEW

File: packages/block-editor/src/components/media-replace-flow/index.js [hunk 1]
```diff
@@ -28,6 +28,7 @@ import LinkViewer from '../url-popover/link-viewer';
 
 const MediaReplaceFlow = ( {
 	mediaURL,
+	mediaId,
```
Comment (jorgefilipecosta) [inline packages/block-editor/src/components/media-replace-flow/index.js]: mediaId is passed to MediaUpload as value and here is passed as mediaId. Should we be consistent and update the name here?

**Review by jorgefilipecosta — APPROVED** [review]
The change works well, I left a small suggestion.
