### PR TITLE
List: copy wrapper when multi selecting items

### LINKED ISSUE #59381: List block: Cmd+A to select all items then paste fails, pasting nothing
Pulling this specific issue out of https://github.com/WordPress/gutenberg/issues/52743 as I can replicate with 6.5 beta 2. @ellatrix can you track this down?

**Replication steps:**

1. Create four list items.
2. Use Cmd + a to select them and copy.
3. Try to paste. Notice nothing pastes.

**Screen recording:**

https://github.com/WordPress/gutenberg/assets/26996883/f19e105f-92b7-4dca-a5f3-289aebedafd7

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Fixes #59381. The problem is that the logic setting the wrapper does not execute when there a multi selection of list items, because it's based on a ref and event listeners.

## Why?

Fixes #59381.

## How?

Add a block type setting and check inside `setClipboardBlocks` instead, which will work for both single and multi selection.

## Testing Instructions

Added a test that fails in trunk. press cmd+a twice in a list to select all list items, then paste into an empty paragraph.

### CODE REVIEW

File: packages/block-editor/src/components/writing-flow/utils.js [hunk 1]
```diff
@@ -8,36 +8,53 @@ import {
...
+
+		if ( firstBlockType[ requiresWrapperOnCopy ] ) {
+			const { getBlockRootClientId, getBlockName, getBlockAttributes } =
+				registry.select( blockEditorStore );
+			const wrapperBlockClientId = getBlockRootClientId(
+				firstBlock.clientId
+			);
+			const wrapperBlockName = getBlockName(
+				getBlockRootClientId( firstBlock.clientId )
+			);
```
Comment (t-hamano) [inline packages/block-editor/src/components/writing-flow/utils.js]:
```suggestion
			const wrapperBlockName = getBlockName( wrapperBlockClientId );
```

File: packages/block-library/src/list-item/index.js [hunk 2]
```diff
@@ -27,6 +29,7 @@ export const settings = {
 		};
 	},
 	transforms,
+	[ unlock( privateApis ).requiresWrapperOnCopy ]: true,
```
Comment (t-hamano) [inline packages/block-library/src/list-item/index.js:32]: Does this implicitly expose the block's new configuration? Or do we need to add new support like `__unstableRequiresWrapperOnCopy` to block.json, similar to `__unstablePasteTextInline` etc?

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR! I did a quick test and it appears to be working as expected.

I think we should also remove the `useCopy` hook export:

https://github.com/WordPress/gutenberg/blob/184e4ad4f7cb063fd628b20024a621221d3edb5c/packages/block-library/src/list-item/hooks/index.js#L7

File: packages/block-library/src/list-item/index.js (hunk 2 above)
Comment (t-hamano) [reply packages/block-library/src/list-item/index.js:32]: For example, when I copied and pasted Button, Column, etc. that depend on the parent block, I found that the block could not be pasted like this problem. I imagine that similar problems can be solved by adding it as block support.

https://github.com/WordPress/gutenberg/assets/54422211/a596c483-4bfc-42bd-8b91-3624e6464f38

Comment (ellatrix) [reply packages/block-library/src/list-item/index.js:32]: > Does this implicitly expose the block's new configuration?

What do you mean? How is it exposed? You need the key to be able to retrieve it.

Sure, we could add it to column and button in the same way. I still prefer using a symbol until we properly stabilise it.

Comment (t-hamano) [reply packages/block-library/src/list-item/index.js:32]: For example, developers may discover and use this new key when creating custom blocks. Since it is a private API, is it okay not to take that into account?

Comment (ellatrix) [reply packages/block-library/src/list-item/index.js:32]: > Since it is a private API, is it okay not to take that into account?

Sorry, I'm not sure what you mean by not taking it into account? Since it's a private symbol, you can't access or set it unless you have know to the symbol (unlike strings).

Comment (t-hamano) [reply packages/block-library/src/list-item/index.js:32]: I see, then there's no problem. Maybe I didn't understand what a Symbol was 😅

**Review by t-hamano — APPROVED** [review]
LGTM! It also works with nested list items and correctly inherits the parent's attributes.


https://github.com/WordPress/gutenberg/assets/54422211/e8acd60f-4c7d-47ae-9ac9-433197b8a9a9

**Comment by ellatrix** [comment]
Thanks @t-hamano!

**Comment by youknowriad** [comment]
I just cherry-picked this PR to the update/packages-6.5-rc1 branch to get it included in the next release: 13e2c3f292
