### PR TITLE
Block Library - Post Excerpt: Fix toolbar for post excerpt warning

### LINKED ISSUE #30279: The post excerpt warning can not be selected
## Description

When a post excerpt block is added directly in the site editor and the warning "Post excerpt block: no post found." is shown, 
the block can not be selected by keyboard or mouse click, and it can not be deleted or moved.

It can be selected via the list view, and this opens the block settings sidebar, but the warning has no toolbar.

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Activate a theme with support for full site editing.
2. Open the site editor, make sure the index template is selected.
3. Add a post excerpt block. Make sure this is not inside a query/loop.
4. See the warning and try to select the block.

## Expected behaviour

I expected the warning to be selectable and have a block toolbar

## Actual behaviour

The warning can not be selected

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/7422055/112600354-62511000-8e11-11eb-93e6-e301b4d4a49b.mp4

## WordPress information
WordPress version: 5.7
Gutenberg version: current trunk at https://github.com/WordPress/gutenberg/commit/53d1ebb904402afc213b0ddf0af6cf8302ce57c0
Are all plugins except Gutenberg deactivated? yes
Are you using a default theme (e.g. Twenty Twenty-One)? Empty theme

## Device information
Device: Desktop
Operating system: Windows 10

### PR DESCRIPTION
**Pull request by carolinan**
## Description

Fixes https://github.com/WordPress/gutenberg/issues/30279
Moves the warning and wraps it inside a div with blockProps.

## How has this been tested?

Follow the instructions in the issue.

Confirm that the warning now has a block toolbar; that the toolbar is still present when moved to top,
and that the block still works when placed in a post context for example query/loop.

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-library/src/post-excerpt/edit.js [hunk 1]
```diff
@@ -146,11 +154,6 @@ export default function PostExcerptEdit( {
 	isSelected,
 	context,
 } ) {
-	if ( ! context.postType || ! context.postId ) {
-		return (
-			<Warning>{ __( 'Post excerpt block: no post found.' ) }</Warning>
-		);
-	}
 	return (
 		<PostExcerptEditor
```
Comment (youknowriad) [inline packages/block-library/src/post-excerpt/edit.js]: It seems that component is useless, we can just remove it and embed everything here?

**Comment by LoseWeightWithAng** [comment]
Great, thanks.

**Review by youknowriad — APPROVED** [review]
