### PR TITLE
Blocks: Update ToggleControl to pass boolean onChange

### LINKED ISSUE #4613: InspectorControls.ToggleControl onChange callback is passed whole event object as argument
## Issue Overview

ToggleControl of block `InspectorControls` passes event object as parameter to `onChange`. Whereas other InspectorControls controls pass value of the control.

## Steps to Reproduce (for bugs)

1. Add `ToggleControls` and any other control e.g. `RangeControl`
2. Make `onChange` callback console log the argument received.
3. Compare ToggleControl and Range control outputs.

## Expected Behavior

`onChange` callback should be passed `event.target.checked` as argument (Other controls pass `event.target.value`).

## Current Behavior

Whole event object is passed which is not consistent with other controls.

## Possible Solution

Well... Will try to do a PR... Idea is to do an anonymous function that calls `onChange` callback with `checked` property of the event target.

## Screenshots / Video

image

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by aduth**
Closes #4613 

This pull request seeks to change the argument signature of the `onChange` callback of `InspectorControls.ToggleControl`, passing a boolean value instead of the event object, for consistency with other inspector controls.

Existing core blocks tend to ignore this argument altogether, instead opting to infer the change as toggle of the current value (i.e. `setAttributes( { checked: ! checked } );` ).

__Testing instructions:__

Verify there are no regressions in behavior of any block using the `InspectorControls.ToggleControl` block helper component:

https://github.com/WordPress/gutenberg/search?utf8=%E2%9C%93&q=togglecontrol&type=

### CODE REVIEW

File: blocks/inspector-controls/toggle-control/index.js [hunk 1]
```diff
@@ -9,19 +10,39 @@ import { withInstanceId, FormToggle } from '@wordpress/components';
...
-		</BaseControl>
-	);
+				help={ help }
+				className="blocks-toggle-control"
+			>
+				<FormToggle
+					id={ id }
+					checked={ checked }
+					onChange={ this.onChange }
+					aria-describedby={ !! help ? id + '__help' : undefined }
```
Comment (noisysocks) [inline blocks/inspector-controls/toggle-control/index.js]: Nit: this `!!` isn't necessary.

**Review by noisysocks — APPROVED** [review]
Looks great. Works great. Thanks for adding tests!
