### PR TITLE
Fix: Block manager doesn't respect allowed_block_types hook

### LINKED ISSUE #15598: Block manager doesn't respect allowed_block_types hook
**Describe the bug**
When using the allowed_block_types filter hook to whitelist block types, any blocks not included in the returned array still appear checked in the block manager, implying they're active and usable.

**To reproduce**
My code:

```php
public function whitelistBlocks($allowed){
	$allowed = [
		'core/paragraph',
		'core/image',
		'core/gallery',
		'core/list',
		'core/button',
		'core/columns',
		'core/column',
		'core-embed/youtube',
		'core-embed/vimeo',
		'core/separator',
		'core/text-columns',
		'core/heading',
		'core/subhead',
		'core/block',
		'core/shortcode',
	];
	return $allowed;
}
```
**Expected behavior**
Ideally, the blocks not in the whitelist array should appear inactive (grayed-out) if they appear in the list at all. At a minimum, they should be unchecked (although I do think this option is confusing as it implies that the block will be active once checked, which it shouldn't).

**Screenshots**
block_manager

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome, safari, firefox
 - Version: WP - 5.2.2; GB  - 5.6.1

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
Fix: https://github.com/WordPress/gutenberg/issues/15598

Currently, the block manager shows blocks that are not allowed by the allowed_block_types filter.
This PR fixes this problem by removing hiding these blocks from the block manager. The user should not notice the existence of blocks not allowed by the allowed_block_types so not showing them in the block manager seems the best approach.

## How has this been tested?
I tested these changes without applying any filter, and things worked exactly as before.
I added the following code to functions.php of the currently enabled theme:
```php
function whitelistBlocks( $allowed ) {
	$allowed = [
		'core/image',
		'core/gallery',
		'core/list',
		'core/button',
		'core/columns',
		'core/column',
		'core-embed/youtube',
		'core-embed/vimeo',
		'core/separator',
		'core/text-columns',
		'core/heading',
		'core/subhead',
		'core/block',
		'core/shortcode',
	];
	return $allowed;
}

add_filter( 'allowed_block_types', 'whitelistBlocks' );
```
I verified only blocks that are returned by whitelistBlocks are part of the block manager; all other blocks don't appear at all.

### CODE REVIEW

File: packages/edit-post/src/components/manage-blocks-modal/category.js [hunk 1]
```diff
@@ -23,6 +25,17 @@ function BlockManagerCategory( {
...
+	const settings = useContext( EditPostSettings );
+	const { allowedBlockTypes } = settings;
+	blockTypes = useMemo( () => {
+		if ( allowedBlockTypes === true ) {
+			return blockTypes;
+		}
+		return blockTypes.filter( ( { name } ) => {
+			return includes( allowedBlockTypes || [], name );
+		} );
+	} );
```
Comment (aduth) [inline packages/edit-post/src/components/manage-blocks-modal/category.js]: I would think we need some dependencies (a second argument) here, at least `blockTypes` and probably `allowedBlockTypes` (or `settings`)?

File: packages/edit-post/src/components/edit-post-settings/index.js [hunk 2]
```diff
@@ -0,0 +1,7 @@
+/**
+ * WordPress dependencies
+ */
+import { createContext } from '@wordpress/element';
```
Comment (aduth) [inline packages/edit-post/src/components/edit-post-settings/index.js]: I guess this is more for convenience in making the settings available to the modal component? I thought whether we had this tracked in state, but I guess that's only in the `editor` and `block-editor` modules. We _could_ do the same in this module as well, but it might be a bit overkill for the one setting we're interested in (I also feel it's already become difficult to manage in the two modules it is present).

**Review by aduth — COMMENTED** [review]
How feasible would it be to include end-to-end tests here?

File: packages/edit-post/src/components/manage-blocks-modal/category.js (hunk 1 above)
Comment (jorgefilipecosta) [reply packages/edit-post/src/components/manage-blocks-modal/category.js]: Updated 👍

File: packages/edit-post/src/components/edit-post-settings/index.js (hunk 2 above)
Comment (jorgefilipecosta) [reply packages/edit-post/src/components/edit-post-settings/index.js]: Yes, I used context as a convenience. Adding it to the edit-post store seemed overkill, and it seemed it would just bring more confusion, I guess we can reconsider later if we have other reasons to add it. While if we add now, I think we can not easily remove them because of o back-compatibility.

**Comment by jorgefilipecosta** [comment]
Hi @aduth, your feedback was addressed and an end 2 end test was added.

**Review by aduth — APPROVED** [review]

File: packages/edit-post/src/components/manage-blocks-modal/category.js [hunk 3]
```diff
@@ -23,18 +25,32 @@ function BlockManagerCategory( {
 	toggleVisible,
 	toggleAllVisible,
 } ) {
-	if ( ! blockTypes.length ) {
+	const settings = useContext( EditPostSettings );
+	const { allowedBlockTypes } = settings;
```
Comment (youknowriad) [inline packages/edit-post/src/components/manage-blocks-modal/category.js]: These are all available in the editor store why not just use that store instead of adding a new context provider?

Comment (jorgefilipecosta) [reply packages/edit-post/src/components/manage-blocks-modal/category.js]: Hi @youknowriad, when a user disables a block in the block manager the block is removed from the editor store allowed blocks. Using just the editor store, it is not possible to differentiate between a block disabled by the user and a block restricted on the server using a plugin. In this case, we need to distinguish both cases.

Comment (youknowriad) [reply packages/edit-post/src/components/manage-blocks-modal/category.js]: It's minor but It feels like something that can be solved in the store somehow instead of adding a new context for sharing data while we already have a context for that (the store).
