### PR TITLE
Image block: wrap images with hrefs in an A tag

### LINKED ISSUE #55336: Image block with link displays the wrong border color in the editor
### Description

The border settings for the image block can be used without defining a border color.
When the image block is linked, and a border is set without a color, the border uses the link color as the border color.

The link color works correctly on the front but not in the editor, because the markup in the editor does not use the `<a>` element.
Editor:
```
<figure>
<div for resizing>
<image>
</div>
</figure

```

Front:

```
<figure>
<a>
<image>
</a>
</figure

```

### Step-by-step reproduction instructions

This is easiest to see in a theme that has different text and link colors, like Twenty Twenty-Three.

1. Add an image block
2. Add a link to the image
3. Add a border width in the image block settings sidebar.
4. Confirm that the border is visible, note the color.
5. Save and view the front of the website. Confirm that the border color is now the link color.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WordPress 6.4 beta 3, nightly, through the beta tester plugin.
Gutenberg current trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

### PR DESCRIPTION
**Pull request by ramonjd**
Maybe resolves: https://github.com/WordPress/gutenberg/issues/55336

## What?
This commit sees what happens when we wrap the image element in an A tag in the editor. 

## Why?
To ensure any inherited styles from the link element, such as border color, apply to the image in the editor. The goal is to match frontend behavior.

Where a border color hasn't been defined, it will default to the closest color. In the frontend, it will be the link element's color due to the wrapping `<a />`. 

In the editor, it's the body color as the img is not wrapped by a link element.

## Testing Instructions
It's best to use the 2023 theme, whose link elements have a different color to the editor body color.

1. Add an Image block
2. Add a link to the image
3. Add a border width in the image block settings sidebar. **Don't apply an color.**
4. Confirm that the border is visible, note the color.
5. Save and view the front of the website. Confirm that the border color matches the editor.
6. Check with the Gallery block

Ensure that Image block settings work in the editor, especially the resizer and other styles.

<details>

<summary>Some example block HTML (replace with your own image)</summary>

```html
<!-- wp:gallery {"linkTo":"none","sizeSlug":"full"} -->
<figure class="wp-block-gallery has-nested-images columns-default is-cropped"><!-- wp:image {"id":23,"sizeSlug":"full","linkDestination":"custom","style":{"border":{"radius":"22px","width":"53px"}}} -->
<figure class="wp-block-image size-full has-custom-border"><a href="https://wordpress.org"><img src="http://localhost:8888/wp-content/uploads/2023/10/california-condor.jpg" alt="" class="wp-image-23" style="border-width:53px;border-radius:22px"/></a></figure>
<!-- /wp:image --></figure>
<!-- /wp:gallery -->

<!-- wp:image {"id":23,"width":"456px","height":"auto","sizeSlug":"full","linkDestination":"custom","style":{"border":{"width":"30px"}}} -->
<figure class="wp-block-image size-full is-resized has-custom-border"><a href="https://wordpress.org"><img src="http://localhost:8888/wp-content/uploads/2023/10/california-condor.jpg" alt="" class="wp-image-23" style="border-width:30px;width:456px;height:auto"/></a></figure>
<!-- /wp:image -->

<!-- wp:image {"id":23,"width":"509px","height":"auto","sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full is-resized"><img src="http://localhost:8888/wp-content/uploads/2023/10/california-condor.jpg" alt="" class="wp-image-23" style="width:509px;height:auto"/></figure>
<!-- /wp:image -->

```

</details>

#### Before

https://github.com/WordPress/gutenberg/assets/6458278/b73e8113-3488-4bb3-9041-9d771ead2ee4

#### After

https://github.com/WordPress/gutenberg/assets/6458278/844fe279-57cd-47bd-9fd0-fa76d33a6eb8

### CODE REVIEW

File: packages/block-library/src/image/image.js [hunk 1]
```diff
@@ -770,7 +769,9 @@ export default function Image( {
 				} }
 				resizeRatio={ align === 'center' ? 2 : 1 }
 			>
-				{ img }
+				{ /* If the image has a href, wrap in an <a /> tag to trigger any inherited link element styles */ }
+				{ /* eslint-disable-next-line jsx-a11y/anchor-is-valid */ }
```
Comment (alexstine) [inline packages/block-library/src/image/image.js]: Can we remove this line and add `href="#"` instead? Then you can disable the link click as my PR shows.

https://github.com/WordPress/gutenberg/pull/54322

This method has been implemented for a couple different blocks now. Trying to match styles is not a good reason to have an invalid link markup.

**Review by alexstine — COMMENTED** [review]
@ramonjd If this is the solution, I left a comment below that should be considered blocking for A11Y. Easy to implement though.

File: packages/block-library/src/image/image.js (hunk 1 above)
Comment (ramonjd) [reply packages/block-library/src/image/image.js]: Thanks, I was just coming back to this PR to ask whether the single `<a />` was sufficiently accessible. Good to have my question answered in advance! Thank you!

**Review by michalczaplinski — APPROVED** [review]
Tests fine for me with images of a heron too!


https://github.com/WordPress/gutenberg/assets/5417266/8ccab546-b365-4fe8-82f7-7e0f116ee7fd



In all seriousness, it does work as expected. Thanks Ramon! 👍

**Review by artemiomorales — APPROVED** [review]
Look good to me 👍

**Comment by SiobhyB** [comment]
Cherry-picked to the 6.4 branch in https://github.com/WordPress/gutenberg/pull/55481/commits/3ade049486928d95cbb9743f29472ceef8577546.
