### PR TITLE
Publish Button: Submit for review as pending for contributor

### LINKED ISSUE #2029: Account for user capabilities in publishing flow
Currently we do not account for user capabilities when deciding if and how to show the "Publish" button. A contributor, for example, must Submit for Review, and does not have access to publishing a post. Currently when trying to Publish a post as a Contributor role, the save attempt fails with a notice.

## Suggestion

When current user does not have `publish_posts` capability...

- Show "Submit for Review" text in place of "Publish"
- When "Publish" is clicked, set status as "pending" (if not already)

## Related Resources

https://codex.wordpress.org/Roles_and_Capabilities#publish_posts

### LINKED ISSUE #2547: Contributor Role can't create a new post using Gutenberg
## Issue Overview
Users with the "Contributor" role who use Gutenberg see errors when trying to save new posts (only Publish button is available, no "submit for review")

## Steps to Reproduce (for bugs)

1. Log in as a "Contributor" user
2. Click on Gutenberg
3. Add some text to your post
4. Observe that the "Publish" button is lit up.
5. Click on Publish button
6. Note error Message:  Publishing Failed.
7. Go to Posts list.  The post appears as "draft".

This is using 
WordPress 4.8.1
Gutenberg 0.9.0
Firefox browser

## Expected Behavior
When adding a new post as a contributor, the "Publish" button should be replaced with "Save Draft" and/or "Submit for Review".
The correct post status should be displayed when editing the post in Gutenberg.

## Current Behavior

When adding a new post (or editing using Gutenberg) the "Publish" button appears.  Clicking that button saves the post, generating a new revision, and shows an error.

I also tried clicking the switch for  "Pending Review", then "publish".  Again, the same error.
When I went to the Posts List screen, I see my post as "Pending Review". 

## Related Issues and/or PRs

https://github.com/WordPress/gutenberg/issues/2029

### PR DESCRIPTION
**Pull request by aduth**
Closes #2029
Closes #2547 

This pull request seeks to account for user capability in deciding the behavior of the Publish button. Specifically, if a user is not capable of publishing posts, they must Submit for Review instead, flagging the post as Pending.

__Testing instructions:__

1. Navigate to the post editor
2. Note that...
   - If your current user has ability to publish posts, the Publish button shows as Publish
   - Otherwise, the Publish button shows as Submit for Review

The "Submit for Review" label should take priority over all other scenarios, including updating an existing post and setting a post into the future.

### CODE REVIEW

File: editor/header/tools/test/publish-button.js [hunk 1]
```diff
@@ -0,0 +1,203 @@
+/**
```
Comment (youknowriad) [inline editor/header/tools/test/publish-button.js]: Thanks a lot for these tests, these are very useful.

File: editor/header/tools/publish-button.js [hunk 2]
```diff
@@ -59,25 +74,32 @@ function PublishButton( {
...
+			isPublishable: isEditedPostPublishable( state ),
+		} ),
+		{
+			onStatusChange: ( status ) => editPost( { status } ),
+			onSave: savePost,
+		}
+	),
+	withAPIData( () => {
+		return {
+			user: '/wp/v2/users/me?context=edit',
```
Comment (youknowriad) [inline editor/header/tools/publish-button.js]: The context `edit` is awesome :). Seems like a hidden feature

**Review by youknowriad — APPROVED** [review]
Works great for me!

I don't know if we want a special notice for this, or if the "saved" status is enough.

**Comment by aduth** [comment]
>I don't know if we want a special notice for this, or if the "saved" status is enough.

Yeah, we should probably want some messaging. The current editor shows a "Post submitted" after submitting for review. We can do similarly in the effects for publishing a post, but we'll want to think through ramifications of considering "pending" as a published state.

https://github.com/WordPress/gutenberg/blob/5f0fe6f62ed03f162801d1f36970f6c72eb38b15/editor/effects.js#L91-L97

I'll plan to create a separate issue.
