### PR TITLE
Keep id on paste if internal link points to it

### LINKED ISSUE #12784: Footnote Anchoring
**Describe the bug**
In the classic editor, when copying a document that has footnotes from Microsoft word, it was simple to paste, as the classic editor would automatically anchor to the respective foot note (I.e., when clicking foot note 1, the page would automatically take you to foot note 1 and vice versa), In the Gutenberg tool, this does not happen automatically. Instead, you would have to go through each footnote individually and anchor it. Why is this? It makes it tedious when you have 100+ footnotes. It would be helpful if this was fixed.

### PR DESCRIPTION
**Pull request by juanruitina**
## Description

With these changes, the block editor will keep the IDs in links when there's another link pointing to that ID. This is useful when pasting documents with internal links, e.g. when pasting text with footnotes from Microsoft Word, which used to work with the TinyMCE editor. Fixes #12784.

Sometimes internal links leverage the "name" attribute as the anchor instead of "id". However, the use of the `name` attribute for `a` elements [is obsolete in HTML5](https://html.spec.whatwg.org/multipage/obsolete.html#obsolete-but-conforming-features); use of `id` is recommended instead; [W3C Markup Validator](https://validator.w3.org/) also shows a warning. This code also saves the `name` attribute in links as the link's `id` (unless there's an `id` attribute already), and then removes it.

(Following @ellatrix feedback in #27677, these changes affect all links, not only footnotes and endnotes)

## How has this been tested?

Tested locally with wp-env.

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. (Doesn't apply)

### CODE REVIEW

**Comment by juanruitina** [comment]
@ellatrix, I accidentally removed the branch I used for #27677, so the PR closed. I took the chance to name the new branch following the developer guidelines. Apologies for the inconvenience.

File: packages/dom/src/phrasing-content.js [hunk 1]
```diff
@@ -32,7 +32,7 @@ const textContentSchema = {
 	s: {},
 	del: {},
 	ins: {},
-	a: { attributes: [ 'href', 'target', 'rel' ] },
+	a: { attributes: [ 'href', 'target', 'rel', 'id', 'name' ] },
```
Comment (ellatrix) [inline packages/dom/src/phrasing-content.js]: I think it's not necessary to add `name` here, because the removal of HTML only happens after the phrasing content reducer.

**Review by ellatrix — APPROVED** [review]
I think we can remove `name` from the schema.

Otherwise this is great. Simple and generalised so that's really nice.

**Comment by ellatrix** [comment]
Looks like there's something going wrong with the tests so you might have to rebase to re-run them again at a later time.

File: packages/blocks/src/api/raw-handling/phrasing-content-reducer.js [hunk 2]
```diff
@@ -56,5 +56,25 @@ export default function phrasingContentReducer( node, doc ) {
...
+		// Keeps id only if there is an internal link pointing to it
+		if (
+			node.id &&
+			! node.ownerDocument.querySelector( `[href="#${ node.id }"]` )
+		) {
+			node.removeAttribute( 'id' );
+		}
+
+		// Remove anchor tag if no href nor id
+		if ( ! node.id && ! node.href ) {
```
Comment (ellatrix) [inline packages/blocks/src/api/raw-handling/phrasing-content-reducer.js]: Hm, shouldn't this only unwrap only if there's no link _elsewhere_? Why would a node have both an id and href?

Also, I'm not sure if we should concern ourselves with removing nodes here. That's something the `removeInvalidHTML` filter will (or should) take care of.

File: packages/blocks/src/api/raw-handling/phrasing-content-reducer.js [hunk 3]
```diff
@@ -56,5 +56,25 @@ export default function phrasingContentReducer( node, doc ) {
 			node.removeAttribute( 'target' );
 			node.removeAttribute( 'rel' );
 		}
+
+		// Saves anchor elements name attribute as id
+		if ( node.name && ! node.id ) {
+			node.id = node.name;
+		}
+		// Removes obsolete name attribute in any case
+		node.removeAttribute( 'name' );
```
Comment (ellatrix) [inline packages/blocks/src/api/raw-handling/phrasing-content-reducer.js]: If we remove `name` from the schema, `removeInvalidHTML` should take care of this.

File: packages/blocks/src/api/raw-handling/phrasing-content-reducer.js (hunk 2 above)
Comment (juanruitina) [reply packages/blocks/src/api/raw-handling/phrasing-content-reducer.js]: Understood. I removed this check as well, let's have `removeInvalidHTML` take care of this.

File: packages/dom/src/phrasing-content.js (hunk 1 above)
Comment (juanruitina) [reply packages/dom/src/phrasing-content.js]: I didn't know this, that's great. Just removed it.

**Comment by juanruitina** [comment]
Thanks a lot @ellatrix for your indications and suggestions, I incorporated them and rebased as suggested. It seems I need approval for rerunning tests, can you do that?

**Comment by ellatrix** [comment]
@juanruitina You need to rebase to re-run them :)

**Comment by ellatrix** [comment]
Oh, one last thing, could you add an paste integration test? I think they're in `test/integration`. You can put the MS Word data in an HTML file like the other tests.

File: test/integration/fixtures/ms-word-out.html [hunk 4]
```diff
@@ -37,3 +37,43 @@ <h2>This is a heading level 2</h2>
...
+<!-- wp:paragraph -->
+<p><a id="anchor">This is the paragraph with the anchor.</a></p>
+<!-- /wp:paragraph -->
+
+<!-- wp:paragraph -->
+<p><a href="#nowhere">This is an anchor link</a> that leads nowhere.</p>
+<!-- /wp:paragraph -->
+
+<!-- wp:paragraph -->
+<p><a>This is a paragraph with an anchor with no link pointing to it.</a></p>
```
Comment (juanruitina) [inline test/integration/fixtures/ms-word-out.html]: @ellatrix Could you provide some more guidance on how could we unwrap text within links with no attributes (therefore with no use)? You mentioned removeInvalidHTML should handle it but I couldn't figure out how we could make sure it achieves that (it doesn't at the moment). It would be nice to clean it up a bit.

**Comment by juanruitina** [comment]
I added a test in `test/integration` for the Word paste, seems to work.

(I did something wrong with the rebase and Github automatically asked for reviews from many code owners. I could undo the error, but not those review requests. Sorry for that!!! Geez, I need to get more familiar with git)

**Comment by Mamaduka** [comment]
Thanks for working on this, @juanruitina, and congratulations on the first merged PR 🎉
