### PR TITLE
[RNMobile] Fix visual glitch when loading Aztec view

### LINKED ISSUE #2976: Visual glitch when loading multiple paragraph blocks within a Reusable block
**Describe the bug**
Having multiple paragraph blocks in a Reusable block produces a visual glitch the first time the block is loaded.

**This bug will be introduced when merging the PR: [[RNMobile] Add support Reusable blocks](https://github.com/WordPress/gutenberg/pull/25265) and registering the Reusable block type.**

**To Reproduce**
1. Create a post in the web version
1. Add at least four or five paragraph blocks and create a Reusable block
1. Open the app
1. Open the post previously created in the web version

**Expected behavior**
The loading of the blocks shouldn't produce any visual glitch.

**Screenshots**

The glitch only happens for some frames so the video's speed has been reduced to 10% to watch it properly. For debugging purposes I changed the background color of the paragraph blocks to red so it's easier to see the blocks' content size.

https://user-images.githubusercontent.com/14905380/103903074-b1818180-50fb-11eb-870c-0af68ce3240f.mov

As you can see in the video the blocks height is bigger than the content at the first frames and then they fits the content.

**Smartphone (please complete the following information):**
 - Device: iPhone 8 (Simulator)
 - OS: 14.0
 - Version 16.4 (DEV)

**Additional context**

### PR DESCRIPTION
**Pull request by fluiddot**
## Description

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/2976.

React Native Aztec view is initialized by default with size (width: 10, height: 10), this produces weird sizes when calculating the content size via the [`sizeThatFits` method](https://developer.apple.com/documentation/uikit/uiview/1622625-sizethatfits?language=objc).

As an example, here are the different sizes produced when a block using Aztec is rendered and calls [`sizeThatFits`](https://github.com/WordPress/gutenberg/blob/2864336523a3053d1e76f7894e53ababd5c68ab8/packages/react-native-aztec/ios/RNTAztecView/RCTAztecView.swift#L200-L206):

### Values with current changes

<details><summary>Paragraph block with one line content</summary>

Content: `<p>Hello world!</p>`

**First render:**
`size: (w: 10, h: 10)` [Initial size]
`fittingSize: (w: 10.0, h: 218.0)` [For some reason it calculates a bigger height that it should 🤷‍♂️]
`minimumHeight: 22.0`
`resultSize: (w: 10.0, h: 218.0)`

**Second render:**
`size:(w: 343.0, h: 218.0)`
`fittingSize:(w: 95.5, h: 22.0)` [On the second pass it gets the correct height, in this case it's the minimum because the content is one line]
`minimumHeight: 22.0`
`result: (w: 95.5, h: 22.0)`

</details>

<details><summary>Paragraph block with three lines content</summary>

Content: `<p>Line 1<br>Line 2<br>Line 3</p>`

**First render:**
`size:(w: 10.0, 10.0)`
`fittingSize:(w: 10.0, 327.0)` [Same as in the previous example, the height is bigger than it should]
`minimumHeight: 22.0`
`result: (w: 10.0, 327.0)`

**Second render:**
`size:(w: 343.0, 327.0)`
`fittingSize:(w: 47.5, 65.5)` [Same as in the previous example, the height is properly calculated on the second pass, in this case bigger because the content is three lines]
`minimumHeight: 22.0`
`result: (w: 47.5, 65.5)`

</details>

### Values with changes from this PR

Surprisingly if the initial size is set to zero `(w: 0, h: 0)`, the calculations are correct:

<details><summary>Paragraph block with one line content</summary>

Content: `<p>Hello world!</p>`

**First render:**
`size:(0.0, 0.0)`
`fittingSize:(95.5, 22.0)` [The size is properly calculated in the first pass]
`minimumHeight: 22.0`
`result: (95.5, 22.0)`

**Second render:**
`sizeThatFits: size:(343.0, 22.0)`
`fittingSize:(95.5, 22.0)`
`minimumHeight: 22.0`
`result: (95.5, 22.0)`

</details>

<details><summary>Paragraph block with three lines content</summary>

Content: `<p>Line 1<br>Line 2<br>Line 3</p>`

**First render:**
`size:(0.0, 0.0)`
`fittingSize:(47.5, 65.5)` [Same as in the previous example, the size is properly calculated in the first pass]
`minimumHeight: 22.0`
`result: (47.5, 65.5)`

**Second render:**
`size:(343.0, 65.5)`
`fittingSize:(47.5, 65.5)`
`minimumHeight: 22.0`
`result: (47.5, 65.5)`

</details>

## How has this been tested?

The visual glitch can be hard to identify because it only happens on a second’s fraction, the way I tested it involves the following:

### Check size calculation
1. Added the following code to [this line](https://github.com/WordPress/gutenberg/blob/0fa010e5cf4a37076c9ab65daeb6a9aa305f2e0d/packages/react-native-aztec/ios/RNTAztecView/RCTAztecView.swift#L205) in the RN Aztec view:
`print("sizeThatFits: size:\(size), fittingSize:\(fittingSize), minimumHeight: \(minimumHeight), content: \(storage.getHTML()), result: \(CGSize(width: fittingSize.width, height: height))")`
2. Create a paragraph block with some text
3. Copy the block
4. Clean the Xcode console logs
4. Paste it via the inserter menu
5. Check the size calculations logs in the the Xcode console logs

### Visual glitch
1. Add the following code in [this line](https://github.com/WordPress/gutenberg/blob/0fa010e5cf4a37076c9ab65daeb6a9aa305f2e0d/packages/block-library/src/paragraph/edit.native.js#L34), this will help to identify the size of the block:
`...{ backgroundColor: 'red' },`
2. Create a post in the web version
3. Add at least four or five paragraph blocks and create a Reusable block
4. Open the app
5. Start to record a video
6. Open the post previously created in the web version (it's recommended to do it a couple of times just in case it happens too fast)
7. Stop recording and open the video
8. Go frame by frame and observe that the block's size doesn't go too big

## Screenshots 

**NOTE: Play it frame by frame to verify the fix.**

https://user-images.githubusercontent.com/14905380/114896145-5ce35600-9e10-11eb-8620-3ff3fed87776.mp4

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/react-native-aztec/ios/RNTAztecView/RCTAztecView.swift [hunk 1]
```diff
@@ -135,6 +135,7 @@ class RCTAztecView: Aztec.TextView {
         textContainerInset = .zero
         contentInset = .zero
         textContainer.lineFragmentPadding = 0
+        frame.size = CGSize(width: 0, height: 0);
```
Comment (guarani) [inline packages/react-native-aztec/ios/RNTAztecView/RCTAztecView.swift]:
```suggestion
        frame.size = CGSize(width: 0, height: 0)
```

Comment (guarani) [reply packages/react-native-aztec/ios/RNTAztecView/RCTAztecView.swift]:
```suggestion
        frame.size = .zero
```

Comment (guarani) [reply packages/react-native-aztec/ios/RNTAztecView/RCTAztecView.swift]: Just nitpicks 😄

**Review by guarani — COMMENTED** [review]
> React Native Aztec view is initialized by default with size (width: 10, height: 10), this produces weird sizes when calculating the content size via the [`sizeThatFits` method](https://developer.apple.com/documentation/uikit/uiview/1622625-sizethatfits?language=objc).

I was wondering where the size of 10x10 was coming from and it looks like it's from in Aztec [here](https://github.com/wordpress-mobile/AztecEditor-iOS/blob/e0cb3c96ada0bed9fab5d3e93952e8375b29d97e/Aztec/Classes/TextKit/TextView.swift#L426). Viewing the previous commit for that [suggests an arbitrary default size might have been used](https://github.com/wordpress-mobile/AztecEditor-iOS/commit/20e65c34ca6d3ac66c04f3c0744598becd6c4b1d#diff-f0cace15743da555005f278eb24e29113177be0a82ccfb58a437e770cc48819dL33-L34). (I'm not 100% sure if that comment is still valid, after all it was deleted).

Do you think setting a zero default size in Aztec would be a viable alternative to doing it here in Aztec's RN wrapper?

File: packages/react-native-aztec/ios/RNTAztecView/RCTAztecView.swift (hunk 1 above)
Comment (fluiddot) [reply packages/react-native-aztec/ios/RNTAztecView/RCTAztecView.swift]: Oh good catch! I forgot to run the autocorrect on styling, thanks!

**Comment by fluiddot** [comment]
> > React Native Aztec view is initialized by default with size (width: 10, height: 10), this produces weird sizes when calculating the content size via the [`sizeThatFits` method](https://developer.apple.com/documentation/uikit/uiview/1622625-sizethatfits?language=objc).
> 
> I was wondering where the size of 10x10 was coming from and it looks like it's from in Aztec [here](https://github.com/wordpress-mobile/AztecEditor-iOS/blob/e0cb3c96ada0bed9fab5d3e93952e8375b29d97e/Aztec/Classes/TextKit/TextView.swift#L426). Viewing the previous commit for that [suggests an arbitrary default size might have been used](https://github.com/wordpress-mobile/AztecEditor-iOS/commit/20e65c34ca6d3ac66c04f3c0744598becd6c4b1d#diff-f0cace15743da555005f278eb24e29113177be0a82ccfb58a437e770cc48819dL33-L34). (I'm not 100% sure if that comment is still valid, after all it was deleted).

Yeah, the 10x10 frame is set when the view is initialized from Aztec (thanks for pointing the code reference 🙇 ) but I couldn't find either the reason of having that specific size. It's still unclear to me the implications of having a zero vs random frame but surprisingly this affects the calculations for the `sizeThatFits` method 🤷‍♂️ .

> Do you think setting a zero default size in Aztec would be a viable alternative to doing it here in Aztec's RN wrapper?

I thought about applying this change in Aztec at the beginning, but since this is a workaround for calculating the view's size for RN, I finally decided to apply it only here. I guess it would be safe to move the fix to the Aztec repo but I wanted to reduce the potential side effects of this change, wdyt?

**EDIT:** I'm thinking to add a comment in this line explaining the workaround.

**Review by guarani — APPROVED** [review]
I agree it's fine to merge this change here. I tested this and all looks good, I think the change makes sense given that it's a zero default size which is more reasonable than the arbitrary default size of 10x10 this had before.

I tested on WPiOS using reusable blocks and all good! Thanks a lot for the fix.
