### PR TITLE
Templates: Only include templates for the current post types

### LINKED ISSUE #31704: FSE - Template meta information and post type support do not work
## Description
Custom template configuration in `experimental-theme.json` file does not work neither in default themes nor in custom ones.

## Step-by-step reproduction instructions
1. Create `my-custom-template.html` file within current active theme's "block-templates" folder
2. Add configuration from `Code snippet` part to active theme's `experimental-theme.json` file
3. Go to admin panel and go to "Posts -> Add New"
4. In the opened screen open "Template dropdown"

## Expected behaviour
1. `Template` dropdown should not contain above mentioned `my-custom-template` as an option because it should not be available for any post type but `page`.
2. The template name must be read as `The template title` instead of `my-custom-template` based on `experimental-theme.json` file configuration

## Actual behaviour
1. Template is available in all post types: `postTypes` restriction does not work
2. Template name is read as `my-custom-template` instead of `The template title`

## Screenshots or screen recording (optional)
image
image
image

## Code snippet (optional)
```
...
"customTemplates": [
    {
      "name": "my-custom-template",
      "title": "The template title",
      "postTypes": [
        "page"
      ]
    }
  ]
...
```

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.5.4
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome 90.0.4430.93 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
Updates block templates loading logic only to include templates for the current post type. These post types can be defined using the `customTemplates` [setting](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#customtemplates) in the theme.json.

Fixes #31704

## How has this been tested?
1. Clone TT2 theme and checkout to `update/templates` [branch](https://github.com/WordPress/twentytwentytwo/pull/136).
2. Create a page.
3. The "Single Post (No Separators)" custom template should be available in the template dropdown.

## Screenshots 
CleanShot 2021-10-20 at 16 06 27

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: lib/full-site-editing/class-gutenberg-rest-templates-controller.php [hunk 1]
```diff
@@ -141,8 +141,17 @@ public function get_items( $request ) {
 		if ( isset( $request['area'] ) ) {
 			$query['area'] = $request['area'];
 		}
+
 		$templates = array();
 		foreach ( gutenberg_get_block_templates( $query, $this->post_type ) as $template ) {
+			if (
+				isset( $request['post_type'] ) &&
```
Comment (Mamaduka) [inline lib/full-site-editing/class-gutenberg-rest-templates-controller.php]: I was planning to include `post_type` in the schema but then noticed that `area` isn't included. Is the `area` exception, or do we only want to display `wp_id` in the schema?

cc @TimothyBJacobs @spacedmonkey

P.S. I think we should also change `$this->post_type` to `$this->template_type`.

**Comment by youknowriad** [comment]
The other related thing that would be good is to exclude the hierarchy templates from the dropdown (things like index, single, archive..., we should only load the custom templates that don't have any "hierarchy" meaning like we do in classic themes)

File: lib/full-site-editing/class-gutenberg-rest-templates-controller.php (hunk 1 above)
Comment (spacedmonkey) [reply lib/full-site-editing/class-gutenberg-rest-templates-controller.php]: Sorry, I don't have any context to this REST API. Can you provide more detail about what you need feedback for here?

Comment (Mamaduka) [reply lib/full-site-editing/class-gutenberg-rest-templates-controller.php]: Sorry, @spacedmonkey.

I'm introducing a new argument, `post_type` - a post type to get the templates for. However, I'm not sure if I need to include it in the collection params.

We also have an `area` argument, which is left out from[ collection params](https://github.com/WordPress/wordpress-develop/blob/40fd54aedee161cbfa10d352053082ccc1d2c02a/src/wp-includes/rest-api/endpoints/class-wp-rest-templates-controller.php#L508-L516).

**Comment by Mamaduka** [comment]
@youknowriad added exclusion logic in be7686b.

**Comment by Mamaduka** [comment]
> Do you mean like how I shouldn't be able to assign "Archive" as a template in this dropdown?

@jasmussen, that's correct.

@youknowriad updated logic as you suggested.

File: lib/full-site-editing/class-gutenberg-rest-templates-controller.php (hunk 1 above)
Comment (youknowriad) [reply lib/full-site-editing/class-gutenberg-rest-templates-controller.php]: I think the filtering should move to `gutenberg_get_block_templates` like all the other filters.

**Comment by aristath** [comment]
I haven't tested this in action yet, but the code looks good 👍

**Comment by Mamaduka** [comment]
@youknowriad, re-filtering: I think parts of `gutenberg_get_block_templates` needs some refactoring. I can try to do it as part of this PR later today/tomorrow or as a separate PR.

Question: When do we usually start moving PHP parts into WP Core PRs/patches from the plugin?

**Comment by youknowriad** [comment]
>  I can try to do it as part of this PR later today/tomorrow or as a separate PR.

I'm worried about splitting filtering logic into two places, so I'd prefer if we move the filtering there (even without refactoring) if possible.

> Question: When do we usually start moving PHP parts into WP Core PRs/patches from the plugin?

It seems we're 20 days before "alpha", I think that's a good time to start thinking about these things. Ideally we should have an editor lead defined though to coordinate with them and make decisions about what to include... I'm not sure when we'll get that information.

**Comment by carolinan** [comment]
I agree with hiding index, archive, 404, but not single post type templates. Only because having them there makes it easier for users to edit the default for post/page when they are editing that content.

**Comment by youknowriad** [comment]
> I agree with hiding index, archive, 404, but not single post type templates. Only because having them there makes it easier for users to edit the default for post/page when they are editing that content.

The "default template" is already added automatically in the frontend, so I think this covers your point here.

**Comment by carolinan** [comment]
I mean I agree that if there is a custom template assigned to page in theme.json, it should only show for page.
But the template "page.html" if it is in the theme should also be there when editing a page.

**Comment by carolinan** [comment]
> > I agree with hiding index, archive, 404, but not single post type templates. Only because having them there makes it easier for users to edit the default for post/page when they are editing that content.
> 
> The "default template" is already added automatically in the frontend, so I think this covers your point here.

Isn't default the "default" that you use when you create a new template? that the theme can define?

**Comment by youknowriad** [comment]
> Isn't default the "default" that you use when you create a new template? that the theme can define?

No, it's the template inherited from the template hierarchy, so `page.html` if defined otherwise `index.html`...

**Comment by carolinan** [comment]
Can we change that label to what it actually is? (in a different PR) So if I am editing a page it says page automatically, not "default".

**Comment by youknowriad** [comment]
I think that should be doable, right now the right label is actually rendered on the header of the panel

Screen Shot 2021-10-21 at 11 28 46 AM

I don't remember exactly where the "Default template" label comes from though.

**Comment by carolinan** [comment]
Tested with a few different themes and with custom post types, works well.

**Comment by Mamaduka** [comment]
I updated the filtering logic, and now it's all done inside `gutenberg_get_block_templates.`

Thanks, everyone, for the feedback and testing ❤️

**Review by youknowriad — APPROVED** [review]
LGTM 👍

File: lib/full-site-editing/class-gutenberg-rest-templates-controller.php [hunk 2]
```diff
@@ -141,6 +141,10 @@ public function get_items( $request ) {
 		if ( isset( $request['area'] ) ) {
 			$query['area'] = $request['area'];
 		}
+		if ( isset( $request['post_type'] ) ) {
```
Comment (TimothyBJacobs) [inline lib/full-site-editing/class-gutenberg-rest-templates-controller.php:144]: This needs to be added to `get_collection_params()`.

**Review by TimothyBJacobs — DISMISSED** [review]

File: lib/full-site-editing/class-gutenberg-rest-templates-controller.php (hunk 2 above)
Comment (Mamaduka) [reply lib/full-site-editing/class-gutenberg-rest-templates-controller.php:144]: Thanks for the confirmation, @TimothyBJacobs. I wasn't sure about this since `$request['area']` isn't there.

Comment (TimothyBJacobs) [reply lib/full-site-editing/class-gutenberg-rest-templates-controller.php:144]: `area` should be added too :)

Comment (Mamaduka) [reply lib/full-site-editing/class-gutenberg-rest-templates-controller.php:144]: Good point 😄

I'm going to update the PR.

Comment (Mamaduka) [reply lib/full-site-editing/class-gutenberg-rest-templates-controller.php:144]: Updated in 9af8ab423aa1a889a24ce30efb0e3b650961ebaf

File: lib/full-site-editing/page-templates.php [hunk 3]
```diff
@@ -8,20 +8,22 @@
...
  * @return array (Maybe) modified page templates array.
  */
-function gutenberg_load_block_page_templates( $templates ) {
+function gutenberg_load_block_page_templates( $templates, $theme, $post, $post_type ) {
 	if ( ! gutenberg_supports_block_templates() ) {
 		return $templates;
 	}
 
-	$block_templates = gutenberg_get_block_templates( array(), 'wp_template' );
+	$block_templates = gutenberg_get_block_templates( array( 'post_type' => $post_type ), 'wp_template' );
```
Comment (youknowriad) [inline lib/full-site-editing/page-templates.php:22]: I think this change hasn't been backported properly into Core yet.
