### PR TITLE
Block Comments: Ensure sort order matches blocks

### LINKED ISSUE #71957: Comments in sidebar appear in wrong order
### Description

When viewing comments in the sidebar, they currently show in the order they were entered. Instead, they should show in the order of the blocks they are associated with.

As a user this feels confusing to me, the order of the sidebar comments should match the order of the associated blocks.

### Step-by-step reproduction instructions

1. Create a post with 5 paragraphs
2. Add a numbered comment (comment1, comment 2...) to each paragraph
3. Check the comments sidebar to see what order the comments are shown in

### Expected results
The comments show in the same order as the blocks they are associated with

### Actual Results
The comments show in the order they were entered. 

### Screenshots, screen recording, code snippet

Here I left comments on each paragraph starting at the first paragraph with comment 1, then adding comment 2 to paragraph 2 and so on.

Image

The result is the comment associated with the top block (comment 1)  is at the bottom of the list. The comment associated with the bottom block (Comment 5) is at the bottom of the list.

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by adamsilverstein**
## What?

Ensure comment order matches block order.

Closes https://github.com/WordPress/gutenberg/issues/71957

## Why?
Comments  should show in the order of the blocks they are associated with.

## How?
Fix an issue where `blocksWithComments` was an indexed array, causing it to be inherently (and unexpectedly) to be ordered by comment id. `blocksWithComments` is now an object and expected sort order is preserved.

## Testing Instructions
1. Create a post with several paragraphs
2. add a comment to each paragraph 
3. confirm that the order the comments are displayed matches the order of the blocks
4. save the comment and re-open, verifying order is intact
5. test re-arranging blocks, note the comments in the sidebar also re-arrange themselves in the correct order
6. try resolving comments - confirm they shift below the unresolved comments in the pinned sidebar (while remaining in block order).

## Screenshots or screencast 

https://github.com/user-attachments/assets/89892797-2e80-4eee-a8b1-3bd5e987fd73

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
I might be missing something, but how about a simple change like this:

```diff
diff --git a/packages/editor/src/components/collab-sidebar/hooks.js b/packages/editor/src/components/collab-sidebar/hooks.js
index 6d8e8b5c0c..515adf7506 100644
--- a/packages/editor/src/components/collab-sidebar/hooks.js
+++ b/packages/editor/src/components/collab-sidebar/hooks.js
@@ -85,8 +85,20 @@ export function useBlockComments( postId ) {
                                        thread !== undefined && thread.status !== 'approved'
                        );
 
+               const sortedResultComments = Object.keys( blocksWithComments )
+                       .map( ( id ) => threadIdMap.get( id ) )
+                       .filter( ( thread ) => thread !== undefined )
+                       .sort( ( a, b ) => {
+                               const IsResolvedA = a.status === 'approved';
+                               const IsResolvedB = b.status === 'approved';
+                               if ( IsResolvedA !== IsResolvedB ) {
+                                       return IsResolvedA ? 1 : -1;
+                               }
+                               return 0;
+                       } );
+
                return {
-                       resultComments: updatedResult,
+                       resultComments: sortedResultComments,
                        unresolvedSortedThreads: unresolvedSortedComments,
                };
        }, [ threads, blocksWithComments ] );
```

**Comment by adamsilverstein** [comment]
> I might be missing something, but how about a simple change like this:

What you might have missed is that _ `blocksWithComments` is not sorted in the order of the blocks_. Although `getClientIdsWithDescendants` returns the blocks in the correct order, when we put them into the indexed array (`results[ commentId ] = clientId;`) the array is _inherently sorted by the index_ so the order becomes the order of the comment ids (generally an ascending number based on the order they were added). I tested your code and it did not help the currect sort order problem.

To fix this, my PR changes `blocksWithComments` to an object with two values - block id and comment id. This keeps the original sort order intact and the logic then works as expected.

Also, note that I have broken out resovledComments and unresolvedComments to make the ordering of the final list explicit. This will help when we add a third type at the very bottom (I expect) - orphaned comments (where the original block was deleted).

**Review by t-hamano — APPROVED** [review]
I see, thanks for the detailed explanation! I think the current logic makes more sense 👍

**Comment by t-hamano** [comment]
Note: It looks like the comments have been reordered, causing the E2E tests to fail, so we'll need to fix those too.

**Comment by adamsilverstein** [comment]
Thanks, I'll get those fixed.

**Comment by adamsilverstein** [comment]
Tests fixed in https://github.com/WordPress/gutenberg/pull/72069/commits/486e01c5ef2e341ba960e62aee293c7b9715593d. The remaining failures are unrelated to this PR.

File: packages/editor/src/components/collab-sidebar/hooks.js [hunk 1]
```diff
@@ -29,10 +29,13 @@ export function useBlockComments( postId ) {
 			const commentId =
 				getBlockAttributes( clientId )?.metadata?.commentId;
 			if ( commentId ) {
-				results[ commentId ] = clientId;
+				results.push( {
+					blockId: clientId,
+					commentId,
+				} );
```
Comment (Mamaduka) [inline packages/editor/src/components/collab-sidebar/hooks.js]: We should not do this as it can affect the performance. The array/object shape was intentional. Related: https://github.com/WordPress/gutenberg/pull/71869#discussion_r2375349748.

Can we do `results[ clientId ] = commentId`, if we want to match block order instead of comment order?

P.S. If you're running a local install with `SCRIPT_DEBUG` enabled, you should see the warning in the DevTools console.

## Screenshot
CleanShot 2025-10-06 at 09 34 52

**Review by Mamaduka — CHANGES_REQUESTED** [review]

File: packages/editor/src/components/collab-sidebar/hooks.js (hunk 1 above)
Comment (adamsilverstein) [reply packages/editor/src/components/collab-sidebar/hooks.js]: > We should not do this as it can affect the performance.

I did realize there is a slight performance hit here, however it felt minimal. That said...

> Can we do results[ clientId ] = commentId, if we want to match block order instead of comment order?

Thats a great idea, I didn't consider that. I can give that a try.

> P.S. If you're running a local install with SCRIPT_DEBUG enabled, you should see the warning in the DevTools console.

I do run with SCRIPT_DEBUG, what warning are you referring to?

Comment (Mamaduka) [reply packages/editor/src/components/collab-sidebar/hooks.js]: > I do run with SCRIPT_DEBUG, what warning are you referring to?

One in the screenshot. Though due to SlotFill's nature, trace isn't ideal 😢 More details: https://make.wordpress.org/core/2025/03/12/data-a-helpful-performance-warning-for-developers-in-the-useselect-hook/

> I did realize there is a slight performance hit here, however it felt minimal. That said...

The `block-editor` is the most active store in the project. Every papercut eventually adds up.

Comment (adamsilverstein) [reply packages/editor/src/components/collab-sidebar/hooks.js]: Missed the screenshot before, I have seen that error. Thanks for explaining.

Comment (adamsilverstein) [reply packages/editor/src/components/collab-sidebar/hooks.js]: I restored the indexed approach in b2bb4e9428b7697c7cf6b923e4c5541b2c238e43 - one thing I noticed after this change is that if I rearrange the blocks, the comments do not rearrange their order (so they become out of order). If i save and reload the editor, the order is correct again.

Previous to that commit, the comments would react live to changes in the block order. What do you think @Mamaduka ?

Comment (Mamaduka) [reply packages/editor/src/components/collab-sidebar/hooks.js]: It looks like my workaround was too "optimized" 😄 since technically key -> values didn't change with block order, it wasn't rerendering. The [a0a29e8](https://github.com/WordPress/gutenberg/pull/72069/commits/a0a29e8571f05d67083db8e7c8b82d2dd215e03c) should fix that.

File: packages/editor/src/components/collab-sidebar/hooks.js [hunk 2]
```diff
@@ -21,19 +21,25 @@ export function useBlockComments( postId ) {
...
+		const { getClientIdsWithDescendants } = select( blockEditorStore );
 
-		return getClientIdsWithDescendants().reduce( ( results, clientId ) => {
+		return {
+			clientIds: getClientIdsWithDescendants(),
+		};
+	}, [] );
+
+	const blocksWithComments = useMemo( () => {
+		return clientIds.reduce( ( results, clientId ) => {
```
Comment (Mamaduka) [inline packages/editor/src/components/collab-sidebar/hooks.js]: @adamsilverstein, here you can return more complex object shapes if you want, in case that helps with lookup when sorting the comments.

File: packages/editor/src/components/collab-sidebar/hooks.js (hunk 1 above)
Comment (Mamaduka) [reply packages/editor/src/components/collab-sidebar/hooks.js]: It appears that the other solution has a different issue. The new comments aren't reflected, and `blocksWithComments` remains stale. We would need to find a different solution.

We could revert https://github.com/WordPress/gutenberg/pull/72069/commits/a0a29e8571f05d67083db8e7c8b82d2dd215e03c and fix the reordering issue in a follow-up; I'm happy to handle that myself.

**Review by Mamaduka — APPROVED** [review]

File: packages/editor/src/components/collab-sidebar/hooks.js (hunk 1 above)
Comment (Mamaduka) [reply packages/editor/src/components/collab-sidebar/hooks.js]: Just realized how to fix this. Here's the PR - #72112.
