### PR TITLE
Fix: Custom color picker popover position

### LINKED ISSUE #36542: Global Styles: improvements to color picker design
## What problem does this address?

Currently, the color picker opens over top of the rest of the color palette obscuring the ability to see the entire set of colors:

Screen Shot 2021-11-16 at 2 17 41 PM

Additionally, the target design doesn't have any padding.

## What is your proposed solution?

- [ ] Move the color picker to the left of the sidebar to provide a clearer editing flow.
- [ ] Remove padding.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Fixes https://github.com/WordPress/gutenberg/issues/36542

Currently, the custom color picker popover appears over the sidebar on the block inspector and on the global styles.
This PR fixes the issue and makes the custom color picker appear on the side as shown on the screenshot below.

In order to fix the issue, we are introducing an experimental __experimentalCorrectPositionForSidebar flag, that when true applies a special positioning for the popover. We are adding an option flag and not using this behavior by default because the component may be used outside of a sidebar and in that case that behavior should not apply.

## How has this been tested?
I verified that in all the following cases the custom color picker appears at the side of the sidebar:
- Global styles elements.
- Paragraph background, color, and link colors. (implemented using the color support hook)
- Cover block overlay color ( custom color functionality implementation).

## Screenshots 
image

### CODE REVIEW

**Review by oandregal — APPROVED** [review]

File: packages/components/src/color-palette/index.js [hunk 1]
```diff
@@ -135,7 +137,12 @@ export default function ColorPalette( {
 		<VStack spacing={ 3 } className={ className }>
 			{ ! disableCustomColors && (
 				<Dropdown
-					contentClassName="components-color-palette__custom-color-dropdown-content"
+					contentClassName={ classnames(
```
Comment (ntsekouras) [inline packages/components/src/color-palette/index.js:140]: Could we just pass down a css class instead of introducing a new API?

File: packages/components/src/color-palette/style.scss [hunk 2]
```diff
@@ -25,3 +25,10 @@
 		padding: 0;
 	}
 }
+
+@include break-medium() {
+	.components-dropdown__content.components-color-palette__custom-color-dropdown-content.is-rendered-in-sidebar.is-from-top .components-popover__content {
```
Comment (ntsekouras) [inline packages/components/src/color-palette/style.scss:30]: This is really coupled with internal class names of other components. Do you think we could avoid them or extract them somehow?

File: packages/components/src/color-palette/index.js (hunk 1 above)
Comment (jorgefilipecosta) [reply packages/components/src/color-palette/index.js:140]: We would need add a property like customColorContentClassName, to ColorPalette, and ColorGradientPanels etc. A block wanting to have the color picker appear in the correct position would need to explicitly know the class to add.
It seems preferable to have a flag that changes the positioning behavior. The fact we use a class to do that is an implementation detail, e.g: on mobile, the way to do it may be different.

File: packages/components/src/color-palette/style.scss (hunk 2 above)
Comment (jorgefilipecosta) [reply packages/components/src/color-palette/style.scss:30]: Here we are changing the position of a popover, I'm not sure how we can avoid relying on the classes the component defines. And unfortunately, this is not the first time we do it, searching for ".components-popover__content" on the codebase we find lots of matches used on each place we change something related to the popover, in some cases even outside the components package while on this case we are inside the components package.
It is not an ideal solution but it seems to be consistent with what we are doing on similar cases.

**Comment by pablohoneyhoney** [comment]
Nice work!

When we have the chance, it's worth aligning the corners of the flyout to have that slight consistent chape. 

Screen Shot 2021-11-30 at 3 05 09 PM


Like this:

Screen Shot 2021-11-30 at 3 05 16 PM

**Review by youknowriad — COMMENTED** [review]
The Popover component has logic in place to switch its position if there's not enough room in the canvas at the chosen one. Can't we just rely on this behavior and set the default position to the left instead of adding this weird prop everywhere.
