### PR TITLE
Rich Text: Set applied format as active in applyFormats

### LINKED ISSUE #15503: Can't add 'open in new tab' directly and need to click edit first
**Describe the bug**
There is bug when you want to add 'open in new tab' directly from the dropdown, you can't enable the option. You first have to click edit and then you open up the extra dropdown function and it works.

**To reproduce**
1. Create a link in a post. 
2. Save the post
3. Try to change the 'open in new tab' function directly with the dropdown function.
4. You can see it won't work.

**Expected behavior**
You can add the 'open in new tab' directly without interfering with the URL behind it.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS X latest stable
 - Browser [e.g. chrome, safari] Chrome

**Additional context**
- Experienced this while editing a page on a Rosetta site.

### LINKED ISSUE #15522: Edited link URL doesn't reflect new value until after refresh
**Describe the bug**

When copying a page and then editing the value of a link, the change is saved, but not  reflected in the UI until after refresh. 

**To reproduce**

1. Open a page that contains a Classic block and has links in it
1. Go to code editor and copy the raw markup
1. Create a new page and open the code editor, paste the raw markup, switch back to the code editor
1. Convert the existing Classic block into regular blocks
1. Click on a link inside one of the paragraph blocks, the toolbar and popover appear
1. Click on the pencil icon in the popover
1. Change the value of the URL
1. Hit enter
1. Notice that the value has not changed.
1. Save page, refresh, notice that the value has changed.

**Expected behavior**

The new value should be reflected in the UI immediately.

### PR DESCRIPTION
**Pull request by aduth**
Fixes #15503 
Fixes #15522 

This pull request seeks to resolve an issue where updates to links (and presumably any applied format?) may not immediately appear as having taken effect in the UI.

**Implementation notes:**

I'm not entirely comfortable in this realm of the code, but judging by some existing logic which modifies active formats in `applyFormats` for formats applied to collapsed text where the format was not already applied, I thought it might be safe to extrapolate this out to include the format as being considered active for any provided value. Alternative suggestions welcome.

**Testing instructions:**

Repeat Steps to Reproduce from #15503 and #15522, verifying expected results.

Ensure unit tests pass:

```
npm run test-unit packages/rich-text
```

### CODE REVIEW

File: packages/rich-text/src/apply-format.js [hunk 1]
```diff
@@ -92,5 +85,12 @@ export function applyFormat(
...
 	}
 
-	return normaliseFormats( { ...value, formats: newFormats } );
+	return normaliseFormats( {
+		...value,
+		formats: newFormats,
+		// Always revise active formats. This serves as a placeholder for new
+		// inputs with the format so new input appears with the format applied,
+		// and ensures a format of the same type uses the latest values.
+		activeFormats: [ format, ...activeFormats ],
```
Comment (ellatrix) [inline packages/rich-text/src/apply-format.js]: I wonder if order could matter here. Could be not just copy the formats at the selection start? Or perhaps use `getActiveFormats`?

Comment (aduth) [reply packages/rich-text/src/apply-format.js]: In my testing, it did matter: Where due to the behavior of `normaliseFormats`, the 'latest' format must occur first, since `normaliseFormats` defers to the previous entry:

https://github.com/WordPress/gutenberg/blob/4108e37d3771b5871cd720216432b5bbd5255551/packages/rich-text/src/normalise-formats.js#L27-L29

I suppose I ought to document this more clearly.

Comment (aduth) [reply packages/rich-text/src/apply-format.js]: Although looking closer at `isFormatEqual`, it's odd that it would have made any effective difference for me... considering that "latest" shouldn't matter if the attribute values (i.e. `target="_blank"` was not the same between formats anyways).

**Comment by aduth** [comment]
> Although looking closer at `isFormatEqual`, it's odd that it would have made any effective difference for me... considering that "latest" shouldn't matter if the attribute values (i.e. `target="_blank"` was not the same between formats anyways).

I was looking at this wrong: `activeFormats` isn't considered for `normaliseFormats`. What I was seeing was explained by the fact that the active format was duplicated, and order mattered for how it was chosen for the UI. The changes in c8c5ed4 avoid duplication by ensuring that an equivalent format by type is first rejected.

I also found that `removeFormats` ought to be updated as well. This change was included in c4ebe80.

Generally I'm still a bit wary about how this all works, mostly because "active formats" seems like a UI concern which shouldn't be considered in this module. But given the precedent, this seems an improvement all the same.

> Could be not just copy the formats at the selection start? Or perhaps use `getActiveFormats`?

I tried using `getActiveFormats` but it was problematic both because (a) it only considered formats at the start (not expected?) and (b) some difficulty around implementing the "placeholder" effect (I don't recall specifically if it was something of my own doing). Generating the `activeFormats` argument for this is essentially doing all the work already. In the end, I'm not really sure what purpose this function serves.

**Comment by youknowriad** [comment]
Anyone tested if this affects WP 5.2?

**Comment by ellatrix** [comment]
I'll have a closer look Monday.

**Comment by youknowriad** [comment]
In my testing, this is looking good.

**Review by youknowriad — APPROVED** [review]

**Comment by aduth** [comment]
d1843ee includes an updated end-to-end test which should verify regression fix against both #15503 and #15522 .

In scanning for other references to active formats within the `rich-text` module, I observe there are native equivalents to these files:

- https://github.com/WordPress/gutenberg/blob/master/packages/rich-text/src/apply-format.native.js
- https://github.com/WordPress/gutenberg/blob/master/packages/rich-text/src/remove-format.native.js

The changes in this pull request shouldn't introduce conflicts, though it is likely that if the logic was meant to align, the revisions here would not be reflected. I don't personally understand well enough why these files exist as native-specific to judge whether changes to those files are necessary (cc @koke , @hypest ).

**Comment by aduth** [comment]
I observe there is a utility function `updateFormats` which isn't used internal to the `rich-text` module itself, but could potentially prove a useful abstraction to normalizing how active formats are updated:

https://github.com/WordPress/gutenberg/blob/master/packages/rich-text/src/update-formats.js

This seems more as a general refactoring / consolidation point, however.

**Comment by koke** [comment]
> The changes in this pull request shouldn't introduce conflicts, though it is likely that if the logic was meant to align, the revisions here would not be reflected. I don't personally understand well enough why these files exist as native-specific to judge whether changes to those files are necessary (

@Tug I don't remember why these were introduced, can you comment here?

**Review by ellatrix — APPROVED** [review]

**Comment by aduth** [comment]
Thanks @koke , @Tug . Since I'd not expect these changes to conflict with that effort, I'll operate on the assumption that I don't need to make any revisions to account for these files.
