### PR TITLE
Editor Store: Have refreshPost() effect bypass caching

### LINKED ISSUE #12055: Editor Store: refreshPost() returns cached post
**Describe the bug**
Contrarily to what its name suggests, `refreshPost` doesn't actually refetch post data from the network. Found here: https://github.com/Automattic/wp-calypso/issues/28664

**To Reproduce**
1. Edit a post
2. Open your browser console's 'Network' tab, and clear it
3. In the browser console, enter `wp.data.dispatch( 'core/editor' ).refreshPost()`
4. Go back to the 'Network' tab. Note that no network request has been fired.

**Reason**
This is happening because of `apiFetch`'s [`preloading` middleware](https://github.com/WordPress/gutenberg/blob/b198e5c4791b2282332def0de89841cd64d75f8e/packages/api-fetch/src/middlewares/preloading.js), which is used to preload and cache data for some REST API routes -- among them, posts. Specifically, try commenting out https://github.com/WordPress/gutenberg/blob/b198e5c4791b2282332def0de89841cd64d75f8e/lib/client-assets.php#L1075-L1079 and running through the above steps again -- verify that `refreshPost` then actually fires a network request.

**Additional context**
- Using Gutenberg 4.4.0.
- This is sort of a follow-up to #11879, related to work on Jetpack's Publicize Gutenberg extension (which is mostly happening in the Automattic/wp-calypso repo)

/cc @tyxla

### PR DESCRIPTION
**Pull request by ockham**
## Description
Make `refreshPost()` effect bypass caching (by adding a `timestamp` query arg)

## How has this been tested?
See  #12055 for instructions to reproduce the issue (on `master`).
Verify that on this branch, entering `wp.data.dispatch( 'core/editor' ).refreshPost()` into your browser console _does_ fire a network request.
Verify that any other network requests for routes that are preloaded still use cached data, i.e. don't fire network requests -- for a list, see https://github.com/WordPress/gutenberg/blob/b198e5c4791b2282332def0de89841cd64d75f8e/lib/client-assets.php#L1038-L1047 

## Types of changes
Bug fix -- fixes #12055. Alternative approach to #12058, prompted by @youknowriad's [suggestion](https://github.com/WordPress/gutenberg/pull/12058#discussion_r234601808).

## Checklist
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 

/cc @tyxla

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
I think I prefer this one personally, but I'd appreciate other opinions @gziolo @aduth @danielbachhuber

**Review by tyxla — APPROVED** [review]
This tests well and code seems reasonable 👍

File: packages/editor/src/store/effects/posts.js [hunk 1]
```diff
@@ -312,7 +312,8 @@ export const refreshPost = async ( action, store ) => {
 	const postTypeSlug = getCurrentPostType( getState() );
 	const postType = await resolveSelector( 'core', 'getPostType', postTypeSlug );
 	const newPost = await apiFetch( {
-		path: `/wp/v2/${ postType.rest_base }/${ post.id }?context=edit`,
+		// Use timestamp to bypass caching
+		path: `/wp/v2/${ postType.rest_base }/${ post.id }?context=edit&timestamp=${ Date.now() }`,
```
Comment (danielbachhuber) [inline packages/editor/src/store/effects/posts.js]: Can we change `timestamp` to `_timestamp` to denote its magical nature?

File: packages/editor/src/store/effects/posts.js [hunk 2]
```diff
@@ -312,7 +312,8 @@ export const refreshPost = async ( action, store ) => {
 	const postTypeSlug = getCurrentPostType( getState() );
 	const postType = await resolveSelector( 'core', 'getPostType', postTypeSlug );
 	const newPost = await apiFetch( {
-		path: `/wp/v2/${ postType.rest_base }/${ post.id }?context=edit`,
+		// Use timestamp to bypass caching
```
Comment (danielbachhuber) [inline packages/editor/src/store/effects/posts.js]: Should this "bust cache" behavior be a feature of `apiFetch()` instead of being handled by the caller?

Comment (youknowriad) [reply packages/editor/src/store/effects/posts.js]: I suggest this change because the preloading middleware is not part of `apiFetch` which means users of `apiFetch` shouldn't be aware of its existence. Having a `timestamp` seems like a middle ground solution between being aware of a caching mechanism and explicitely stating that this call being time dependent.

Comment (danielbachhuber) [reply packages/editor/src/store/effects/posts.js]: Ok. This rationale makes sense to me. We should update the code comment to explain _why_ instead of what (which is obvious by the code).

Comment (danielbachhuber) [reply packages/editor/src/store/effects/posts.js]: Maybe something like:
> // Allows caller to bypass browser caching, which is expected for this specific function.

Comment (gziolo) [reply packages/editor/src/store/effects/posts.js]: I agree with @danielbachhuber that in the long run, it should be possible to invalidate the cache on demand in the preloading middleware.

Comment (youknowriad) [reply packages/editor/src/store/effects/posts.js]: For me it almost feels like the preloading middleware should invalidate itself on first call.

Comment (gziolo) [reply packages/editor/src/store/effects/posts.js]: Hmm, if you assume that all fetched data is stored in data stores then we could make it work it this way.

Comment (ockham) [reply packages/editor/src/store/effects/posts.js]: > For me it almost feels like the preloading middleware should invalidate itself on first call.

I can try and work on that, but I'm a bit short on time since we're trying to get this fixed in time for Jetpack's code freeze tomorrow, and the self-invalidation seems to have more impact, and cases that need testing. Would it be okay to go with this PR for now and implement the self-invalidation later?

Comment (youknowriad) [reply packages/editor/src/store/effects/posts.js]: yes, let's get it in.

**Comment by youknowriad** [comment]
Would you mind rebasing the branch? We had a e2e test failure in master that should be fixed now.

**Comment by ockham** [comment]
Rebased
