### PR TITLE
Remove "block" from "Hide Block Settings" and "Show Block Settings" labels

### LINKED ISSUE #22920: Hide Block Settings - should be Hide Settings
**Describe the bug**
Today, during WordCamp Europe Contributor Day I was reviewing the documentation for the items in the `More options` menu.  I was considering the documentation for Hide Block Settings and realised that it's not just the Block settings that are hidden, it's the whole of the Settings sidebar.
Ditto for the reverse action - Show Block Settings.

So I suggest the menu items be changed to reflect what they actually do.

From | To
---- | --- 
Hide Block Settings | Hide Settings
Show Block Settings | Show Settings

**To reproduce**
1. Go to the Toolbar for any block
2. Click on the More options tool
3. Click on Hide Block Settings
4. Notice that the Settings sidebar is hidden
5. Click on Show Block Settings
6. Notice that the Settings sidebar is redisplayed

**Expected behavior**
Unchanged. Just different labels.

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] Either
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6] 8.2.1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 -

**Additional context**

### PR DESCRIPTION
**Pull request by bartczyz**
## Description
Update labels from "Hide Block Settings" and "Show Block Settings" to "Hide More Settings" and "Show More Settings".

Closes #22920.

## Types of changes
Just labels update, no change in functionality of the component.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
Since the button opens the block inspector, where advanced block settings go, I think the wording should be "Show advanced settings".

**Comment by michelleweber** [comment]
Personally, I'd vote for leaving "Block" in for extra clarity since blocks are still relatively new, but if you're going to be changing it, "Show advanced settings" looks fine.

**Comment by bartczyz** [comment]
I would go with either "Show advanced settings" or "Show additional settings".

**Comment by marceloaof** [comment]
Considering that Advanced settings is a group of block settings among other possible ones, it may be better to use a broader term, to refer to all metaboxes that are presented to users.

image

It is good the simplicity and consistency of Show Settings/Hide Settings, as mentioned above and on #22920

Regarding the proposal of Show Additional Settings/Hide Additional Settings, simpler translations are achieved with the synonym Show More Settings/Hide More Settings.

**Comment by bartczyz** [comment]
@marceloaof I really like the "Show More Settings/Hide More Settings" option. Should we go with that?

**Comment by marceloaof** [comment]
Hi @bartczyz If no more considerations are offered in the next hours, it is safe to ask a reviewer to approve "Show More Settings/Hide More Settings". It is a good balance. It serves all mentioned ideas. 👍 Easy-to-read outside english and immediately-understood for screen readers too.

**Comment by ZebulanStanphill** [comment]
I'm definitely a fan of "Show more settings". It's simple and gets the point across.

File: packages/edit-post/src/components/visual-editor/block-inspector-button.js [hunk 1]
```diff
@@ -43,8 +43,8 @@ export function BlockInspectorButton( {
 	};
 
 	const label = areAdvancedSettingsOpened
-		? __( 'Hide Block Settings' )
-		: __( 'Show Block Settings' );
+		? __( 'Hide More Settings' )
+		: __( 'Show More Settings' );
```
Comment (ZebulanStanphill) [inline packages/edit-post/src/components/visual-editor/block-inspector-button.js:47]: The label should use sentence case to match other controls.
```suggestion
		? __( 'Hide more settings' )
		: __( 'Show more settings' );
```

Comment (bartczyz) [reply packages/edit-post/src/components/visual-editor/block-inspector-button.js:47]: I wanted to be consisted with other labels in that menu:
image

Comment (ZebulanStanphill) [reply packages/edit-post/src/components/visual-editor/block-inspector-button.js:47]: Oh, well in that case I guess it's fine for now. I guess we can change all of those at once in a separate PR.

**Review by ZebulanStanphill — APPROVED** [review]

**Comment by mariohamann** [comment]
Do we need this option at all?

- It is just a duplicate of the existing button in the toolbar.
- This option changes the UI and therefore – in my opinion – does not really fit to the other actions, which "do something" with or around the selected block.

**Comment by ZebulanStanphill** [comment]
@mariohamann The "Show block settings" option was added as a sort of accessibility compromise to make toggling the inspector's visibility easier for keyboard users, who would otherwise have to navigate to the top bar and toggle the sidebar there.

(From an accessibility perspective, the block inspector shouldn't even function as sidebar in the first place. Rather, the block inspector should function as a dialog/popover, and it should be accessed from a button in the block toolbar, _not_ the top toolbar. But that's a separate topic.)

I think this PR needs to be rebased to get tests to run/pass.

**Comment by mariohamann** [comment]
@ZebulanStanphill Thank you very much for clarification – I assumed it might have something to do with keyboard controls.

Still I'm a bit irrititated: Is the goal of the button to (a) _open/close_ the sidebar or (b) to _get access_ to the sidebar? If the goal is to access the sidebar, might it be more convenient to replace the this option with a "jump link" to the sidebar (always opening the sidebar, even if it's closed)? I tested the current behaviour with keyboard and if the sidebar is open, one has to close and open the sidebar again to get access to it from block level (seeing no focus for a moment).

Furthermore I'm asking myself if there is any possibility to show items only if Gutenberg is being used with keyboard (e. g. as described [in this StackOverflow comment](https://stackoverflow.com/a/51093815)), but I think this again is another topic. :)

**Comment by bartczyz** [comment]
@ZebulanStanphill I'm on it. 

Sorry, was away for a while there. 😉

**Comment by bartczyz** [comment]
@ZebulanStanphill rebased and ready to go. 👍
