### PR TITLE
[Inserter]: Fix reset of registered media categories

### LINKED ISSUE #52832: Registered inserter media categories are reset
### Description

When registering new inserter media categories with `dispatch( 'core/block-editor' ).registerInserterMediaCategory()`, they are removed by the editor initialization.

Consider this snippet of code that is loaded by a plugin which registers an "Openverse 2" media category:

```php
add_action( 'enqueue_block_editor_assets', function() {
	wp_add_inline_script( 'wp-editor', "
wp.domReady( function() {
	wp.data.dispatch( 'core/block-editor' ).registerInserterMediaCategory( {
		name: 'openverse-2',
		labels: {
			name: 'Openverse 2',
			search_items: 'Search Openverse',
		},
		mediaType: 'image',
		async fetch( query = {} ) {
			const defaultArgs = {
				mature: false,
				excluded_source: 'flickr,inaturalist,wikimedia',
				license: 'pdm,cc0',
			};
			const finalQuery = { ...query, ...defaultArgs };
			const mapFromInserterMediaRequest = {
				per_page: 'page_size',
				search: 'q',
			};
			const url = new URL( 'https://api.openverse.engineering/v1/images/' );
			Object.entries( finalQuery ).forEach( ( [ key, value ] ) => {
				const queryKey = mapFromInserterMediaRequest[ key ] || key;
				url.searchParams.set( queryKey, value );
			} );
			const response = await window.fetch( url, {
				headers: {
					'User-Agent': 'WordPress/inserter-media-fetch',
				},
			} );
			const jsonResponse = await response.json();
			const results = jsonResponse.results;
			return results.map( ( result ) => ( {
				...result,
				sourceId: result.id,
				id: undefined,
				caption: result.caption,
				previewUrl: result.thumbnail,
			} ) );
		},
		getReportUrl: ( { sourceId } ) =>
			'https://wordpress.org/openverse/image/' + sourceId + '/report/',
		isExternalResource: true,
	} );
	console.log( 'Registered inserter media categories', wp.data.select( 'core/block-editor' ).getSettings().inserterMediaCategories );
} );
	" );
} );
```

There is a `console.log` call at the end to confirm that indeed the media category has been registered.

However, it never shows up in the Media tab of the inserter menu because it has been replaced by the default categories (which can be confirmed by checking `wp.data.select( 'core/block-editor' ).getSettings().inserterMediaCategories`):

Screenshot 2023-07-21 at 12 10 36

Screenshot 2023-07-21 at 12 07 12

Seems that any category registered before the default categories are added [here](https://github.com/WordPress/gutenberg/blob/87ef1df04d024ccb53d8c4755b1b27725aa700e6/packages/editor/src/components/provider/use-block-editor-settings.js#L205) is completely ignored and removed, and they need to be registered afterwards.

The problem is that there isn't any straightforward way to know when it is safe to register new categories.

There are several ways to solve this:
- Ensure that previously registered categories remain registered after adding the default categories.
- Provide an API function (not a `core/block-editor` action) that guarantees that custom media categories are registered and remain registered.
- Provide a hook that is triggered when default categories have been registered and it's safe to register new categories.

cc @ntsekouras 

### Step-by-step reproduction instructions

- Add the code above to your testing site.
- Go to `wp-admin/post-new.php`.
- Open the browser JS console.
- Note how there is a message indicating that the "Openverse 2" category has been registered.
- Open the inserter menu.
- Activate the Media tab.
- Note how "Openverse 2" is missing.
- Execute `wp.data.select( 'core/block-editor' ).getSettings().inserterMediaCategories` in the browser JS console.
- Note how only the default categories are registered.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/52832

In https://github.com/WordPress/gutenberg/pull/51542 a new `registerInserterMediaCategory` API to make media categories extensible was introduced. Since `inserterMediaCategories` is a block editor setting though there was an issue that if we register new categories before the initialization of the block editor store's settings or we updated another setting that triggers a settings reset(ex spotlight mode), the added categories were lost.

This PR introduces a new reducer in block editor(`registeredInserterMediaCategories`) and merges the registered ones and the settings when consuming the media categories in media tab.

## Testing Instructions
1. Register categories with PHP and JS
2. Update a setting like `Spotlight mode`
3. Observe that the categories are preserved.

PHP registration code:
```php
add_action( 'enqueue_block_editor_assets', function() {
	wp_add_inline_script( 'wp-editor', "
wp.domReady( function() {
	wp.data.dispatch( 'core/block-editor' ).registerInserterMediaCategory( {
		name: 'openverse-2',
		labels: {
			name: 'Openverse 2',
			search_items: 'Search Openverse',
		},
		mediaType: 'image',
		async fetch( query = {} ) {
			const defaultArgs = {
				mature: false,
				excluded_source: 'flickr,inaturalist,wikimedia',
				license: 'pdm,cc0',
			};
			const finalQuery = { ...query, ...defaultArgs };
			const mapFromInserterMediaRequest = {
				per_page: 'page_size',
				search: 'q',
			};
			const url = new URL( 'https://api.openverse.engineering/v1/images/' );
			Object.entries( finalQuery ).forEach( ( [ key, value ] ) => {
				const queryKey = mapFromInserterMediaRequest[ key ] || key;
				url.searchParams.set( queryKey, value );
			} );
			const response = await window.fetch( url, {
				headers: {
					'User-Agent': 'WordPress/inserter-media-fetch',
				},
			} );
			const jsonResponse = await response.json();
			const results = jsonResponse.results;
			return results.map( ( result ) => ( {
				...result,
				sourceId: result.id,
				id: undefined,
				caption: result.caption,
				previewUrl: result.thumbnail,
			} ) );
		},
		getReportUrl: ( { sourceId } ) =>
			'https://wordpress.org/openverse/image/' + sourceId + '/report/',
		isExternalResource: true,
	} );
	console.log( 'Registered inserter media categories', wp.data.select( 'core/block-editor' ).getSettings().inserterMediaCategories );
} );
	" );
} );
```

JS code to run in dev tools:
```
wp.data.dispatch( 'core/block-editor' ).registerInserterMediaCategory( {
	name: 'openverse from JS',
	labels: {
		name: 'Openverse JS',
		search_items: 'Search Openverse',
	},
	mediaType: 'image',
	async fetch( query = {} ) {
		const defaultArgs = {
			mature: false,
			excluded_source: 'flickr,inaturalist,wikimedia',
			license: 'pdm,cc0',
		};
		const finalQuery = { ...query, ...defaultArgs };
		// Sometimes you might need to map the supported request params according to `InserterMediaRequest`.
		// interface. In this example the `search` query param is named `q`.
		const mapFromInserterMediaRequest = {
			per_page: 'page_size',
			search: 'q',
		};
		const url = new URL( 'https://api.openverse.engineering/v1/images/' );
		Object.entries( finalQuery ).forEach( ( [ key, value ] ) => {
			const queryKey = mapFromInserterMediaRequest[ key ] || key;
			url.searchParams.set( queryKey, value );
		} );
		const response = await window.fetch( url, {
			headers: {
				'User-Agent': 'WordPress/inserter-media-fetch',
			},
		} );
		const jsonResponse = await response.json();
		const results = jsonResponse.results;
		return results.map( ( result ) => ( {
			...result,
			// If your response result includes an `id` prop that you want to access later, it should
			// be mapped to `InserterMediaItem`'s `sourceId` prop. This can be useful if you provide
			// a report URL getter.
			// Additionally you should always clear the `id` value of your response results because
			// it is used to identify WordPress media items.
			sourceId: result.id,
			id: undefined,
			caption: result.caption,
			previewUrl: result.thumbnail,
		} ) );
	},
	getReportUrl: ( { sourceId } ) =>
		`https://wordpress.org/openverse/image/${ sourceId }/report/`,
	isExternalResource: true,
} );
```

### CODE REVIEW

File: packages/edit-site/src/components/block-editor/use-site-editor-settings.js [hunk 1]
```diff
@@ -128,10 +133,26 @@ export default function useSiteEditorSettings() {
...
+			( { name } ) => name
+		);
+		return [
+			...inserterMediaCategories,
+			...settingsInserterMediaCategories.filter(
+				( { name } ) =>
+					! coreInserterMediaCategoriesNames.includes( name )
+			),
+		];
+	}, [ settingsInserterMediaCategories ] );
```
Comment (youknowriad) [inline packages/edit-site/src/components/block-editor/use-site-editor-settings.js]: I don't really like this fix personally, basically to pass the correct setting to the block editor, we retrieve the same settings from the block editor. I think that's a bad approach and that would force us to apply the same fix for all block editor instances. 

Instead we should do something similar to what @ellatrix did for the "styles" setting of the block editor setting. Basically have a dedicated reducer in the block editor store that is only about the "registered categories" and "merge" both in the consumer level, not when passing the "settings" prop to the block editor provider.

Comment (ntsekouras) [reply packages/edit-site/src/components/block-editor/use-site-editor-settings.js]: I don't like this fix either TBH. So you mean leave the edit-post and edit-site settings as they are and have a new prop(reducer) in block editor, right?

Comment (ntsekouras) [reply packages/edit-site/src/components/block-editor/use-site-editor-settings.js]: I updated the code. If that's what you had in mind, it feels way more elegant. Thanks!

File: packages/block-editor/src/components/inserter/media-tab/hooks.js [hunk 2]
```diff
@@ -55,22 +55,40 @@ function useInserterMediaCategories() {
...
 			allowedMimeTypes: settings.allowedMimeTypes,
 			enableOpenverseMediaCategory: settings.enableOpenverseMediaCategory,
+			registeredInserterMediaCategories:
+				getRegisteredInserterMediaCategories(),
 		};
 	}, [] );
 	// The allowed `mime_types` can be altered by `upload_mimes` filter and restrict
 	// some of them. In this case we shouldn't add the category to the available media
 	// categories list in the inserter.
 	const allowedCategories = useMemo( () => {
```
Comment (youknowriad) [inline packages/block-editor/src/components/inserter/media-tab/hooks.js]: Don't you think, all this logic in this hook should be a selector. `getInserterMediaCategories`. We might not need the `getRegisteredInserterMediaCategories` selector at all.

**Review by youknowriad — COMMENTED** [review]
Yes, this is exactly what I had in mind. Left a small a comment but it's good.

File: packages/block-editor/src/components/inserter/media-tab/hooks.js (hunk 2 above)
Comment (ntsekouras) [reply packages/block-editor/src/components/inserter/media-tab/hooks.js]: Yes it could. I'll create one. `getRegisteredInserterMediaCategories` selector though would still be needed because it's used in the register action to make checks about duplicate names/labels.

Comment (youknowriad) [reply packages/block-editor/src/components/inserter/media-tab/hooks.js]: it could be a private one

**Review by youknowriad — APPROVED** [review]
LGTM 👍

**Comment by mikachan** [comment]
I just cherry-picked this PR to the 6.4-beta3 branch to get it included in the next release: aca3f6d171
