### PR TITLE
Widgets editor: Display Widget Area's name and description in the sidebar

### LINKED ISSUE #24838: Widgets editor: Is it "Block Areas" or "Widgets"?
In some places we call the new block-based widgets editor screen _Widgets_ and in other places we call it _Block Areas_. We ought to settle on one name so as to avoid user confusion.

Screen Shot 2020-08-27 at 11 15 40

### LINKED ISSUE #25190: Widget screen: Widget area description is not present.
**Describe the bug**
If I include a description for the widget area when I register it using register_sidebar, the description is not seen in the widget screen.

(-It is also not present in the customizer widget block panel.)

**To reproduce**
1. Enable a theme with a widget area and widget area description.
2. Enable Gutenberg 
3. Open the widgets screen
4. Try to figure out the difference between "sidebar 1" and "sidebar 2"

**Expected behavior**
A description is added to help the user learn where the widget area is visible on the front, or to give hints 
for what type of block and widget that is suitable.

The description needs to be visible in the UI.

**Editor version (please complete the following information):**
WordPress version: 5.5.1
Gutenberg: Version 8.9.3

**Desktop (please complete the following information):**
PC windows 10
Chrome Version 85.0.4183.83

### LINKED ISSUE #25745: Jump positions unexpected within widget editor when clicking edit
I was exploring the new interface for widgets and saw the 'edit' actions. This was interesting to me as I initially expected it to 'edit' or open. I did notice the screen move a little, but because I had a larger widget area as you can see in this gif, it was a little disjointed.

My recommendations would be:

- Review if 'edit' is the right term for this here. Perhaps 'goto' or 'interact'? It certainly had me expecting to edit inline.
- Offset the jump point on the screen to maybe jump a little below the object. This would avoid the issue of having to scan to the bottom of the page.
- Potentially consider animations to draw focus to the interaction point.

There is also a further bug when the edit action has to jump up to the top, as shown in gif included. It doesn't quite get there.

### PR DESCRIPTION
**Pull request by noisysocks**
Fixes https://github.com/WordPress/gutenberg/issues/25745.
Closes https://github.com/WordPress/gutenberg/issues/24838.
Closes https://github.com/WordPress/gutenberg/issues/25190.

sidebar

This PR implements the mockup in https://github.com/WordPress/gutenberg/issues/25745#issuecomment-705016495.

- Renames _Block Areas_ to _Widget Areas_.
- Removes the list of Widget Areas from the sidebar.
- Displays the currently selected Widget Area's name and description in the sidebar.

### How to test

1. Navigate to Appearance → Widgets.
2. Look at the sidebar. Experiment with opening the sidebar, closing the sidebar, selecting blocks, selecting widget areas, and selecting nothing.

### CODE REVIEW

**Comment by noisysocks** [comment]
@mapk: How's this look to you?

File: packages/edit-widgets/src/components/sidebar/widget-areas.js [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+		);
+
+	let description;
+	if ( ! selectedWidgetArea ) {
+		description = __(
+			'Widget Areas are global parts in your site’s layout that can accept blocks. These vary by theme, but are typically parts like your Sidebar or Footer.'
+		);
+	} else if ( selectedWidgetAreaId === 'wp_inactive_widgets' ) {
+		description = __(
+			'Blocks in this Widget Area will not be displayed in your site.'
```
[the remark this answers is not in the document]
Comment (noisysocks) [reply packages/edit-widgets/src/components/sidebar/widget-areas.js:28]: I made this copy up on the fly 😅 

@mapk: What should it say?

File: packages/edit-widgets/src/components/sidebar/widget-areas.js [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+	const selectedWidgetArea =
+		selectedWidgetAreaId &&
+		widgetAreas?.find(
+			( widgetArea ) => widgetArea.id === selectedWidgetAreaId
+		);
+
+	let description;
+	if ( ! selectedWidgetArea ) {
+		description = __(
+			'Widget Areas are global parts in your site’s layout that can accept blocks. These vary by theme, but are typically parts like your Sidebar or Footer.'
```
[the remark this answers is not in the document]
Comment (noisysocks) [reply packages/edit-widgets/src/components/sidebar/widget-areas.js:24]: Yes this comes from the design in https://github.com/WordPress/gutenberg/issues/25745#issuecomment-705016495.

**Review by mapk — APPROVED** [review]
Looks good! 👍 

sidebar

A weird glitch happened when I first clicked away from the Inactive Widget area as you can see in the video, but seemed to work afterwards.

File: packages/edit-widgets/src/components/sidebar/index.js [hunk 3]
```diff
@@ -128,9 +134,28 @@ export default function Sidebar() {
...
-					activeComplementaryArea={ currentArea }
-				/>
+				<ul>
+					<li>
+						<ComplementaryAreaTab
+							identifier={ WIDGET_AREAS_IDENTIFIER }
+							label={
+								selectedWidgetAreaBlock
+									? selectedWidgetAreaBlock.attributes.name
+									: __( 'Widget Areas' )
```
Comment (kevin940726) [inline packages/edit-widgets/src/components/sidebar/index.js:144]: Nitpick: Maybe just `selectedWidgetAreaBlock?.attributes?.name || __( 'Widget Areas' )`?

File: packages/edit-widgets/src/components/sidebar/widget-areas.js [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+	const widgetAreas = useSelect(
+		( select ) => select( 'core/edit-widgets' ).getWidgetAreas(),
+		[]
+	);
+
+	const selectedWidgetArea =
+		selectedWidgetAreaId &&
+		widgetAreas?.find(
+			( widgetArea ) => widgetArea.id === selectedWidgetAreaId
+		);
```
Comment (kevin940726) [inline packages/edit-widgets/src/components/sidebar/widget-areas.js:19]: Nitpick: Not sure about the performance impact, but maybe we would want to `useMemo` this so that we don't have to recalculate `.find` every time this component renders.

File: packages/edit-widgets/src/components/sidebar/widget-areas.js [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+		description = selectedWidgetArea.description;
+	}
+
+	return (
+		<div className="edit-widgets-widget-areas">
+			<div className="edit-widgets-widget-areas__top-container">
+				<BlockIcon icon={ blockDefault } />
+				<div>
+					<p>{ description }</p>
+					{ widgetAreas?.length === 0 && (
```
Comment (kevin940726) [inline packages/edit-widgets/src/components/sidebar/widget-areas.js:40]: What if `widgetAreas` is nullish? Do we want to display the empty message in this case?

I think that depends on whether we treat this state as a _loading_ state or an _error_ state 🤔 ?

File: packages/edit-widgets/src/components/sidebar/index.js (hunk 3 above)
Comment (talldan) [reply packages/edit-widgets/src/components/sidebar/index.js:144]: I'm not sure that seems right, wouldn't that return the `attributes` object if `name` is not defined?

Comment (noisysocks) [reply packages/edit-widgets/src/components/sidebar/index.js:144]: I think I prefer the explicitness that `?:` gives. Also if `attributes.name` is `''` we can see easily that there's a bug.

File: packages/edit-widgets/src/components/sidebar/widget-areas.js (hunk 5 above)
Comment (noisysocks) [reply packages/edit-widgets/src/components/sidebar/widget-areas.js:40]: If we display the empty message when `widgetAreas` is nullish (`! widgetAreas || widgetAreas.length === 0`) then we'll see a flash of the empty message when the page loads, which is quite jarring. It's more common that there are widget areas so I think best to be optimistic about that.

File: packages/edit-widgets/src/components/sidebar/widget-areas.js (hunk 4 above)
Comment (noisysocks) [reply packages/edit-widgets/src/components/sidebar/widget-areas.js]: Done in 4b44c1b006!

**Review by talldan — APPROVED** [review]
Looks good from testing and code review point of view.

Not sure if you're still waiting for copy review, but that can always be a follow up.
