### PR TITLE
Parser: Parse superfluous classes as custom classes

### LINKED ISSUE #5028: Persist custom CSS classes during block conversion when block supports additional classes
## Issue Overview
When converting a Classic block to blocks, existing classes are removed. CSS classes can have been added manually (edit as HTML or TinyMCE text mode) and should be kept to preserve the appearance of the content.

## Steps to Reproduce (for bugs)
1. Add a Classic bloc and copy the code below when editing as HTML
1. Convert to blocks

```
<h2>Paragraph with CSS classes</h2>
<p class="custom-class-1 custom-class-2">Sed quae tandem ista ratio est? Ipse Epicurus fortasse redderet, ut Sextus Peducaeus, Sex. Aberat omnis dolor, qui si adesset, nec molliter ferret et tamen medicis plus quam philosophis uteretur. Ne amores quidem sanctos a sapiente alienos esse arbitrantur. Hoc non est positum in nostra actione. Quacumque enim ingredimur, in aliqua historia vestigium ponimus. <i>Non quam nostram quidem, inquit Pomponius iocans;</i></p>
<h2>List with CSS class</h2>
<ul class="custom-class">
<li>Utrum igitur tibi litteram</li>
<li>Videor an totas paginas commovere</li>
<li>Videamus animi partes, quarum est conspectus</li>
</ul>
```

## Expected Behavior
Each block should keep its classes.

## Current Behavior
Block classes are removed

Tested with Gutenberg 2.1

### PR DESCRIPTION
**Pull request by aduth**
Closes #5028
Maybe addresses #6826 (?)
Related: https://github.com/aduth/hpq/pull/2

This pull request seeks to enable a block which supports `customClassName` (default `true`) to inherit as part of its `className` attribute any classes which the user has added manually. This avoids a block being marked as having been modified externally, and further treats the extra classes the same as any other custom class (specifically in exposing by its Inspector > Advanced > Additional CSS Class).

**Implementation notes:**

This adds a new filter on the parsed block attributes, determining if there is a difference between how classes were parsed and what was received as original markup of the block.

Noting that there is some relation between this and https://github.com/aduth/hpq/pull/2 , particularly in how we retrieve the class attribute from the root element of the markup. Currently this requires adding a dummy wrapper node. The changes proposed in https://github.com/aduth/hpq/pull/2 may still be in our interest to explore, but would be a significant breaking change affecting a large number of existing blocks. At this point, we may just want to be content with the current behavior, despite its drawbacks.

**Testing instructions:**

Verify that adding a class to a block which supports custom class names (e.g. paragraph) via the block menu's Edit as HTML view does not invalidate the block, is persisted between editor sessions, and is displayed in its Additional CSS Class advanced inspector field.

### CODE REVIEW

**Comment by youknowriad** [comment]
Correct if I'm wrong but we're still persisting the custom className in the comment of blocks. I wonder if it's possible to drop it entirely from there with this new filter. I'm thinking of this extra filter as a way to define custom "source" in the block parser.

**Comment by aduth** [comment]
>Correct if I'm wrong but we're still persisting the custom className in the comment of blocks. I wonder if it's possible to drop it entirely from there with this new filter. I'm thinking of this extra filter as a way to define custom "source" in the block parser.

It may be possible, yes, though I'm actually motivated to not allow for custom sources, particularly with how it impacts the viability of ever being able to parse blocks from the server. The current set of supported sources could be recreated on the server; if we allow for custom sources, not so much.

File: blocks/api/parser.js [hunk 1]
```diff
@@ -148,7 +149,13 @@ export function getBlockAttributes( blockType, innerHTML, attributes ) {
 		return getBlockAttribute( attributeKey, attributeSchema, innerHTML, attributes );
 	} );
 
-	return blockAttributes;
+	return applyFilters(
+		'blocks.getBlockAttributes',
```
Comment (youknowriad) [inline blocks/api/parser.js]: Do we want to document this or keep it "secret" for now :)

**Review by youknowriad — APPROVED** [review]
LGTM 👍 

I think I'd prefered to drop the className comment attribute entirely but I'm fine with this too.

File: blocks/api/parser.js (hunk 1 above)
Comment (aduth) [reply blocks/api/parser.js]: >Do we want to document this or keep it "secret" for now :)

I'm fine to document. Will add.

File: editor/hooks/custom-class-name.js [hunk 2]
```diff
@@ -93,6 +97,65 @@ export function addSaveProps( extraProps, blockType, attributes ) {
...
+
+		const filteredClassName = compact( [
+			blockAttributes.className,
+			...customClasses,
+		] ).join( ' ' );
+
+		if ( filteredClassName ) {
+			blockAttributes.className = filteredClassName;
+		} else {
+			delete blockAttributes.className;
```
Comment (youknowriad) [inline editor/hooks/custom-class-name.js]: I'm not certain why we're deleting the className attribute in this case? This creates this bug #9991. Can you clarify a bit?

Comment (youknowriad) [reply editor/hooks/custom-class-name.js]: Oh actually the filsterClassName variable have been removed at some point which is causing the bug.

Comment (youknowriad) [reply editor/hooks/custom-class-name.js]: #8232

**Comment by Buddierdl** [comment]
Hi, this seems to have been broken in the upgrade from WP 5.8 to 5.9. Now custom classes on HTML content are being dropped again when converting to blocks using the rawHandler. Anyone else seeing this?
