### PR TITLE
Fix parent popover not closing on click outside

### LINKED ISSUE #74154: Selecting a custom color might prevent the color palette from closing.
### Description

Selecting a custom color might prevent the color palette from closing.

### Step-by-step reproduction instructions

1. Place a paragraph block.
2. Select a custom color for the text.
3. Click on the background color.
4. The custom text color will not close.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/db289273-4edb-4696-9ec6-281bb2e4e3f7

### Environment info

- WordPress 6.9 
- Gutenberg trunk branch

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

Fixes #74154; alternative to #74179.

## Testing Instructions

To check that the bug fix from #72376 hasn't regressed:

1. Enable the Dataviews: new media modal experiment.
2. In the editor, add an Image block and populate it with an image.
3. Click the "Replace" button in the block toolbar, then "Open media library" - you should see the modal containing the dataviews picker.
4. Click the filter button and then click outside the resulting dropdown to close it. The modal should stay open.

To check that #74154 is fixed:

1. With a paragraph block selected,  and add a custom color for the text.
2. Click on the background color. Both the color popovers should close.
3. Open the custom color dialog again, and this time click on the paragraph itself in the canvas. Both the popovers should close.

### CODE REVIEW

**Review by SirLouen — APPROVED** [review]
Yes, I can confirm that this solution is way more surgical. I wanted to cover nested scenarios through portals but I've tested some other edge cases with `fireEvent`, and it seems that they are not triggering the expected errors.

**Review by andrewserong — APPROVED** [review]
This is looking good to me as well. Thanks for adding the test to capture the case, too!

File: packages/components/src/popover/test/index.tsx [hunk 1]
```diff
@@ -578,4 +578,89 @@ describe( 'Popover', () => {
...
+					screen.getByTestId( 'nested-popover' )
+				).toBeInTheDocument();
+			} );
+
+			await user.click( screen.getByTestId( 'nested-dummy-button' ) );
+
+			await user.click( screen.getByTestId( 'external-button' ) );
+
+			await waitFor( () => {
+				expect( onNestedFocusOutside ).toHaveBeenCalled();
```
Comment (ramonjd) [inline packages/components/src/popover/test/index.tsx]: optional `expect( onNestedFocusOutside ).toHaveBeenCalledTimes( 1 );` just to ensure the order and count of clicks

File: packages/components/src/popover/test/index.tsx [hunk 2]
```diff
@@ -578,4 +578,89 @@ describe( 'Popover', () => {
...
+			} );
+
+			await waitFor( () => {
+				expect( onParentFocusOutside ).toHaveBeenCalled();
```
Comment (ramonjd) [inline packages/components/src/popover/test/index.tsx]: Completely optional `expect( onParentFocusOutside ).toHaveBeenCalledTimes( 1 );`

**Review by ramonjd — APPROVED** [review]
Thanks for the quick fix! 

I also checked that the added tests failed on trunk (they do) to assert the fixed code path

test suggestions can be ignored as pedantic :D

**Comment by tellthemachines** [comment]
> Thanks for adding the test to capture the case, too!

The test was just copied over from @SirLouen's PR 😄 

Thanks for the reviews folks! I'll push a changelog update for this before merging.

**Comment by andrewserong** [comment]
> The test was just copied over from @SirLouen's PR 😄

Ah, nice work @SirLouen!
