### PR TITLE
Fix selection of font size presets if presets have the same `size` value

### LINKED ISSUE #42683: Font size selector doesn't work if you have more than one font size with the same default value.
### Description

When you have more than one font size with the same value the font size selector doesn't work as expected. When you are not using fluid font sizes API probably it makes sense to consolidate both font sizes defined in only one, after all, it's exactly the same value. But, it's a different story when you are using the fluid typography API `theme.json`, because in this case you could have the same default value but the `min` and `max` values could be very different.

Example `settings.typography` in `theme.json`:
```json
"fluid": true,
"fontSizes": [
{
    "size": "1.25rem",
    "slug": "default",
    "name": "Default"
},
{
    "size": "1.25rem",
    "fluid": {
        "min": "1.25rem",
        "max": "2.5rem"
    },
    "slug": "default-title",
    "name": "Default Title"
}
]
```

### Step-by-step reproduction instructions

See the video below. There you will be able to see that I'm not able to select the "Default title" font size because the "Default" font size is selected because of the shared base font size.

I expect to be able to select any of the font sizes, no matter if the base font size is repeated from another font size definition or not.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1310626/180837187-392e53e6-6c86-4aa4-b2d8-32b6955b46d7.mp4

### Environment info

- WordPress 6.0.1
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #52191: Fluid "fontSizes" in theme.json break when "size" attribute for two sizes is identical
### Description

When creating custom fluid `fontSizes` in theme.json, sometimes it's desirable to have the same `min` size but increase to a larger `max` size. Currently, if you set the `size` attribute to be the same across different `fontSizes`, this causes a bug in the editor where you can't select the size that has a matching size applied.

**theme.json Example Code:**
```
"fontSizes": [
	{
		"fluid": {
			"min": "1rem",
			"max": "1.25rem"
		},
		"size": "1rem",
		"slug": "small"
	},
	{
		"fluid": {
			"min": "1rem",
			"max": "1.5rem"
		},
		"size": "1rem",
		"slug": "medium"
	}
]
```

**Editor error:**
fontSizes-bug

This issue can be fixed by setting different `size` attributes, but for code readability and consistency sometimes it's desirable to assign this number based on the `min` or `max` size, and there are niche instances where a developer might be forced to set this to an arbitrary number to avoid the editor bug.

### Step-by-step reproduction instructions

1. Create a clean install of WordPress, with the `twentytwentythree` theme.
2. Edit `theme.json`, setting multiple `fontSizes` to the same number (e.g., set line `255` to `1rem` and line `263` to `1rem`)
3. Try to assign these sizes within the editor, e.g. on a Paragraph block.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 6.2.2
- twentytwentythree, version 1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #64760: Font size picker fails to set a font size if there's another preset with the same value.
### Description

If there is more than one font size preset with the same value, the font size picker component fails to select it.

Example:
Multiple font sizes with the same `size` value but different fluid options could exist, and the font size picker fails to select the right one.

```json
{
	"settings": {
		"typography": {
			"fluid": true,
			"fontSizes": [
				{
					"fluid": {
						"max": "59px",
						"min": "11px"
					},
					"name": "New Font Size 1",
					"size": "59px",
					"slug": "custom-1"
				},
				{
					"name": "New Font Size 2",
					"size": "60px",
					"slug": "custom-2"
				}
			]
		},
	},
	"version": 3,
	"$schema": "https://schemas.wp.org/trunk/theme.json"
}
```

### Step-by-step reproduction instructions

1. Create more than one font size preset with the same value in the `size` key
2. Try to select that font size preset as in the screencast.

### Screenshots, screen recording, code snippet

In this example, both font sizes have the same (`59px`) value. The second one can't be selected:

https://github.com/user-attachments/assets/602ac43c-7b77-46e9-9972-3c8a78a5e467

In this video, we can see how, after changing one of the values of the font size preset, it can be selected using the font size picker:

https://github.com/user-attachments/assets/7b0ecbe2-11a5-45d4-8e7d-b9eaa432ccb0

### Environment info

- Gutenberg trunk
- WordPress 6.6.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### LINKED ISSUE #69939: Fluid Font size digit value in font selector dropdown is confusing
## What problem does this address?
In font size presets when we add a fluid font size, we have a range of font size  instead of a constant font size. For example I am creating a font size with max 80px and min 32px. In this case the font size is neither 80px nor 32px, it is actually (32px - 80px) range. But when we try to choose a font in drop down in site editor, we always see min font size for fluid fonts. This is confusing, as it appear like the font size is 32px and not 80px for larger desktop view.

## What is your proposed solution?
Whenever we create a fluid font size, the digit value of font size in font selector dropdown should be something like [min digit - max digit ] ( 32 - 80 in above case ) for static font size its ok to show just the font size.
For more clearification see this image

Image
I have renamed the font size with (80px) so that i got the idea that this font size max value is 80px, otherwise I always get confused that this is actually a fluid font size or not? and what is the max value of that font fluid size?

### LINKED ISSUE #71510: Custom Font Size Presets with custom fluid values can't be selected in the editor
### Description

When adding a custom font size preset via Styles → Typography in the Site Editor, I've experienced an issue when using custom fluid values.

When I directly set the toggle "Custom fluid values" to on, the size input above gets disabled and the value this field has disappears. Instead, below the toggle two more fields are added for minimum and maximum values. Saving this works. However if I add a second font size preset the exakt same way, without deleting the top size value first and directly adding custom fluid values, I run into an issue when trying to select the second font. See the video below.

https://github.com/user-attachments/assets/feec0685-9136-4839-a616-970516cc7481

This is the exact same behaviour as described in #64760 and #42683.

The difference here is the user experience. I've had two people this week bring that to my attention. In both cases, the size next to the font size preset name in the selection showed `16px` instead of the fluid values that were actually added.

If the `16px` gets removed before the custom fluid values toggle is turned on, then this is not a problem. However the current interface behaviour does not indicate that this field has to be emptied in order to use the custom fluid values.

In #69939, a UX improvement is discussed to properly show fluid values.

### Step-by-step reproduction instructions

1. Open up the Site Editor.
2. Go to Styles → Typography → Font Size Presets.
3. Add a new custom preset.
4. Ignore the 16px in the size field and directly toggle the "Custom fluid values" option.
5. Insert any fluid values, I used em and rem.
6. Go back to the preset overview and repeat adding a custom font size with some different values.
7. Go to whatever block is available in the editor and try to select the second custom value you just added. You should not be able to, and both custom font size presets will show `16px` as size, instead of the actual fluid value.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 6.8.2
- Gutenberg plugin NOT active, but makes no difference if Gutenberg is active
- Twenty Twenty-Five theme

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by luminuu**
## What?

Closes #42683
Closes #64760
Closes #71510
Closes #52191
Closes #69939

## Why?

This PR solves multiple issues regarding the selection of font size preset, if those presets have the same size. Right now selecting a font size preset in the editor will result in always falling back to the first item in the list that has the exact same `size` set.

Even if a user sets custom fluid values, the original `size` value is stored and used as a selection reference. This causes issues in the user experience of the custom fluid values not working correctly as they just can not be selected, if the size value (which will be disabled) is not changed before entering custom fluid values.

## How?

This PR introduces a `selectedSlug` variable that is used in every relevant spot to hold the actual selection, instead of falling back on a specific `size` that can be added multiple times through the font size presets interface. 

The code fixes this issue in both selection variations: the horizontal S - M - L - XL - XXL selection like in Twenty Twenty-Five, as well as in the dropdown, if more font size presets exist than the horizontal selection can show.

I also went ahead on updating the display of the font size preset name and actual value in the dropdown, despite the issue is waiting for more Design feedback. The reason for this is I found that when not adjusting this, if the preset name was short (like `Small`) and it had a fixed value, it would all be in one line. Together with items that break into two lines, this would have looked confusing, as information for different items have showed differently. I went ahead and added feedback by @karmatosed already, but this can be discussed here too.

## Testing Instructions

Depending on the theme it's tested and optionally additional font size presets added, both variations can be tested:

### Horizontal view
CleanShot 2025-09-16 at 17 57 07

1. This can be tested with Twenty Twenty-Five without any additional font size presets added.
2. Go to Styles -> Typography -> Font size presets.
3. You can pick any existing font size. Small has a fixed value, so you can edit for example Medium, by deactivating both toggles and adding `0.875rem` as font size.
4. Save settings.
5. Go to any paragraph or heading and select the font size preset. Without this PR, you should not be able to select it, with this PR, both original and updated selections are possible.

### Dropdown view
CleanShot 2025-09-16 at 18 04 40

1. In order to test this view, you need to add at least one additional font size preset, two to make it easier testing.
2. Go to Styles -> Typography -> Font size presets.
3. Add a new custom font size with a fixed value of `1rem` for example.
4. Add a second custom font size with adding `1rem` in the size input as well, before activating both of the fluid toggles and adding `1rem` and `3rem` as respective values.
5. Save settings.
6. Go to any paragraph or heading and select the second font size with the fluid values added. It should stay selected and not fall back on the first custom font size with the fixed value. 

## Screenshots or screencast 

The screencasts only show the dropdown version.

### Before

https://github.com/user-attachments/assets/8589da36-7ea8-47e5-9371-043c182a0478

### After
https://github.com/user-attachments/assets/7588c5dd-3e32-483c-a0d4-648def30ca7e

### CODE REVIEW

**Comment by hanneslsm** [comment]
Thanks for working on this @luminuu!
By the way, I think this would be also useful spacing sizes: https://github.com/WordPress/gutenberg/issues/51110

File: packages/components/src/font-size-picker/font-size-picker-select.tsx [hunk 1]
```diff
@@ -13,20 +18,79 @@ import type {
...
+						String( fontSize.fluid.min! )
+					);
+				} else if ( hasMax ) {
+					hint = sprintf(
+						// translators: %s: the maximum fluid font size value.
+						__( '<= %s' ),
+						String( fontSize.fluid.max! )
+					);
+				}
+			}
```
Comment (t-hamano) [inline packages/components/src/font-size-picker/font-size-picker-select.tsx]: The code to generate hint text should be outside of the component, as some consumers may want to display other information as hints that are unrelated to the fluid typography.

This means adding a hint property to the FontSize type instead of a fluid property.

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

Like many other components, I think that which items are selected or not should be determined by a single source.

> Even if a user sets custom fluid values, the original `size` value is stored and used as a selection reference.

This is the fundamental problem we need to address. This may be difficult, but can we generate a unique size value from fluid.min and fluid.max? Or, when passing a prop to the FontSizePicker component, can we pass the actual clamp value as the size value instead of 16px?

> Together with items that break into two lines, this would have looked confusing, as information for different items have showed differently.

If this is a real problem, it should be fixed in the CustomSelectControl component itself, rather than overriding the CustomSelectControl behavior. Perhaps we can discuss the design in a separate issue or PR.

**Comment by luminuu** [comment]
Thank you for your feedback @t-hamano!

> This is the fundamental problem we need to address. This may be difficult, but can we generate a unique size value from fluid.min and fluid.max? Or, when passing a prop to the FontSizePicker component, can we pass the actual clamp value as the size value instead of 16px?

I don't think generating a unique size will solve the problem. It would make most sense to me to have the entire `clamp()` statement in there, just as it is generated on the frontend.

> > Together with items that break into two lines, this would have looked confusing, as information for different items have showed differently.
> 
> If this is a real problem, it should be fixed in the CustomSelectControl component itself, rather than overriding the CustomSelectControl behavior. Perhaps we can discuss the design in a separate issue or PR.

Would this be a blocker now for this PR?

**Comment by t-hamano** [comment]
> > > Together with items that break into two lines, this would have looked confusing, as information for different items have showed differently.
> > 
> > If this is a real problem, it should be fixed in the CustomSelectControl component itself, rather than overriding the CustomSelectControl behavior. Perhaps we can discuss the design in a separate issue or PR.
> 
> Would this be a blocker now for this PR?

I don't think this is a blocker, but I don't understand why a special layout is needed just for the font size picker 🤔

**Comment by luminuu** [comment]
> I don't think this is a blocker, but I don't understand why a special layout is needed just for the font size picker 🤔

Let's call it "path of least resistance" 😅 Let me try to figure out a better way in the `CustomSelectControl` component.

File: packages/components/src/font-size-picker/font-size-picker-select.tsx (hunk 1 above)
Comment (luminuu) [reply packages/components/src/font-size-picker/font-size-picker-select.tsx]: I have just added a commit where I moved the hint text.

**Comment by mirka** [comment]
> If this is a real problem, it should be fixed in the CustomSelectControl component itself, rather than overriding the CustomSelectControl behavior. Perhaps we can discuss the design in a separate issue or PR.

Agreed. Also, there are plans for a new and improved CustomSelectControl which will allow for easier layout customization like this at the instance-level, so there's also an option to wait until that's ready.

**Comment by luminuu** [comment]
> > If this is a real problem, it should be fixed in the CustomSelectControl component itself, rather than overriding the CustomSelectControl behavior. Perhaps we can discuss the design in a separate issue or PR.
> 
> Agreed. Also, there are plans for a new and improved CustomSelectControl which will allow for easier layout customization like this at the instance-level, so there's also an option to wait until that's ready.

Is there already an issue for improving the CustomSelectControl?

**Comment by mirka** [comment]
> Is there already an issue for improving the CustomSelectControl?

Sorry, hard to find 😅 #55023

**Comment by karmatosed** [comment]
@mirka is there a timeline on that being implemented? I know that is a hard ask but I am wondering if that is going to be a blocker to getting this in or if this could be something worked around within this PR to not require changes to a global component. That might be asking a lot and the other option is to get some timing on this with the other issue if that is possible. 

What I see in review is an issue started in 2023, with quite a bit of work going on lately (which is great), does this mean it is going to land in the next few versions or hope to?

**Comment by mirka** [comment]
I'm not in a position to say about the timeline, but I don't think it necessarily has to be a blocker for this PR.

If we only need to wrap the `hint` to the next line, could we just do the minimum possible style override, for example set `width: 100%` on `.components-custom-select-control__item-hint`? I think we can stomach a temporary style override if it's only a line or two.

**Comment by luminuu** [comment]
> I'm not in a position to say about the timeline, but I don't think it necessarily has to be a blocker for this PR.
> 
> If we only need to wrap the `hint` to the next line, could we just do the minimum possible style override, for example set `width: 100%` on `.components-custom-select-control__item-hint`? I think we can stomach a temporary style override if it's only a line or two.

I have now reduced the CSS to that one line changing the `width` to `100%` and it just works fine.

I've tried to get the remaining checks passing but for some reason it always gets stuck on this:
```
You are trying to create a styled element with an undefined component.
    You may have forgotten to import it.
``` 

But the component is imported as an external dependency a few lines above. Or am I doing something else wrong here? @mirka @t-hamano @Mamaduka

**Comment by luminuu** [comment]
I've now investigated into the failing checks myself with the help of Cursor and locally the checks have now passed with a minor change, here's Cursors summary of it:

## Summary

I've successfully fixed the failing GitHub PR checks! Here's what was done:

### The Problem
The test was failing with this error:
```
You are trying to create a styled element with an undefined component.
You may have forgotten to import it.
```

This was caused by a **circular dependency** in the import chain:

1. `font-size-picker-select.tsx` imports `CustomSelectControl` from `../custom-select-control`
2. `custom-select-control/index.tsx` imports from `../custom-select-control-v2/custom-select`
3. `custom-select-control-v2/custom-select.tsx` imports `VisuallyHidden` from `..` (the main components index)
4. The main components index exports both `CustomSelectControl` and `FontSizePicker`

This created a circular dependency where the FontSizePicker depended on CustomSelectControl, but CustomSelectControl's dependencies eventually led back to the main index that exports FontSizePicker.

### The Solution
I fixed the circular dependency by changing the import in `/packages/components/src/custom-select-control-v2/custom-select.tsx`:

**Before:**
```typescript
import { VisuallyHidden } from '..';
```

**After:**
```typescript
import { VisuallyHidden } from '../visually-hidden';
```

This breaks the circular dependency by importing `VisuallyHidden` directly from its source instead of going through the main components index.

### Verification
- ✅ The specific failing test now passes (46/46 tests passed)
- ✅ Font size picker tests still pass (91/91 tests passed)  
- ✅ Custom select control v2 tests still pass (22/22 tests passed)
- ✅ No linting errors introduced
- ✅ All packages built successfully

The fix is minimal, targeted, and resolves the circular dependency without affecting any functionality. The GitHub PR checks should now pass!

File: packages/components/src/custom-select-control-v2/custom-select.tsx [hunk 2]
```diff
@@ -12,7 +12,7 @@ import { __, _n, sprintf } from '@wordpress/i18n';
 /**
  * Internal dependencies
  */
-import { VisuallyHidden } from '..';
+import { VisuallyHidden } from '../visually-hidden';
```
Comment (mirka) [inline packages/components/src/custom-select-control-v2/custom-select.tsx:15]: Thanks for fixing this!

File: packages/components/src/font-size-picker/font-size-picker-select.tsx [hunk 3]
```diff
@@ -11,7 +16,15 @@ import type {
...
-import { isSimpleCssValue } from './utils';
+import { generateFontSizeHint } from './utils';
+
+// Custom styled component to force line break between name and hint while keeping checkmark on the right
+const StyledCustomSelectControl = styled( CustomSelectControl )`
+	.components-custom-select-control__item
+		.components-custom-select-control__item-hint {
+		width: 100%;
+	}
+`;
```
Comment (mirka) [inline packages/components/src/font-size-picker/font-size-picker-select.tsx]: Let's move this to the `styles.ts` file like the others.

**Review by mirka — COMMENTED** [review]
> Like many other components, I think that which items are selected or not should be determined by a single source.

What @t-hamano said here ☝️ also stood out to me upon review. Ideally, we don't break the convention of having a single `value` prop that determines the selection. If we need some kind of `valueMode: 'literal' | 'slug'` prop that toggles whether the `value` prop expects literal values like before or instead expects slug values, I think that would be preferable to having essentially two props that could carry the selected value. What do you all think?

File: packages/components/src/font-size-picker/font-size-picker-select.tsx (hunk 3 above)
Comment (luminuu) [reply packages/components/src/font-size-picker/font-size-picker-select.tsx]: Moved it to the `styles.ts` file as suggested.

**Comment by luminuu** [comment]
> > Like many other components, I think that which items are selected or not should be determined by a single source.
> 
> What @t-hamano said here ☝️ also stood out to me upon review. Ideally, we don't break the convention of having a single `value` prop that determines the selection. If we need some kind of `valueMode: 'literal' | 'slug'` prop that toggles whether the `value` prop expects literal values like before or instead expects slug values, I think that would be preferable to having essentially two props that could carry the selected value. What do you all think?

I understand the issue with the two props holding the selected value. I have now changed the code to use your suggested `valueMode` prop. Can you have a look at it again @mirka ?

File: packages/block-editor/src/components/global-styles/typography-panel.js [hunk 4]
```diff
@@ -433,6 +447,7 @@ export default function TypographyPanel( {
 				>
 					<FontSizePicker
 						value={ fontSize }
+						selectedSlug={ currentFontSizeSlug }
```
Comment (t-hamano) [inline packages/block-editor/src/components/global-styles/typography-panel.js]: Let's remove any logic that we no longer need.

File: packages/block-editor/src/components/global-styles/typography-panel.js [hunk 5]
```diff
@@ -212,6 +212,20 @@ export default function TypographyPanel( {
...
+		const rawValue = inheritedValue?.typography?.fontSize;
+		if (
+			rawValue &&
+			typeof rawValue === 'string' &&
+			rawValue.startsWith( 'var:preset|font-size|' )
+		) {
+			return rawValue.replace( 'var:preset|font-size|', '' );
+		}
+		return undefined;
+	} )();
```
Comment (ramonjd) [inline packages/block-editor/src/components/global-styles/typography-panel.js:237]: Any reason for the self-executing function?

This would also work the same way:

```js
	const currentFontSizeSlug =
		inheritedValue?.typography?.fontSize?.startsWith(
			'var:preset|font-size|'
		)
			? inheritedValue.typography.fontSize.replace(
					'var:preset|font-size|',
					''
			  )
			: undefined;
```

File: packages/block-editor/src/components/global-styles/typography-panel.js (hunk 4 above)
Comment (t-hamano) [inline packages/block-editor/src/components/global-styles/typography-panel.js]: The `selectedSlug` prop isn't used anywhere anymore, right?

File: packages/block-editor/src/hooks/font-size.js [hunk 6]
```diff
@@ -125,6 +128,7 @@ export function FontSizeEdit( props ) {
 		<FontSizePicker
 			onChange={ onChange }
 			value={ fontSizeValue }
+			selectedSlug={ fontSize }
```
Comment (ramonjd) [inline packages/block-editor/src/hooks/font-size.js]: This prop doesn't appear to be used by `<FontSizePicker />`

File: packages/block-editor/src/components/global-styles/typography-panel.js (hunk 4 above)
Comment (ramonjd) [inline packages/block-editor/src/components/global-styles/typography-panel.js]: This prop doesn't appear to be used by `<FontSizePicker />`

File: packages/components/src/font-size-picker/types.ts [hunk 7]
```diff
@@ -96,17 +104,33 @@ export type FontSize = {
...
+	 */
+	fluid?: {
+		min?: string | number;
+		max?: string | number;
+	};
+	/**
+	 * The `hint` property is an optional string that provides additional information
+	 * about the font size, such as fluid typography ranges or custom descriptions.
+	 */
+	hint?: string;
```
Comment (t-hamano) [inline packages/components/src/font-size-picker/types.ts]: As I might have mentioned before, I think the `FontSizePicker` component itself should only support the `hint` property. The `FontSizePicker` component is not just for the global styles, it is something that consumers can freely use. I don't think specific properties should be included in the component itself. As long as there is a `hint` property, consumers can freely control their own preferred hints.

File: packages/components/CHANGELOG.md [hunk 8]
```diff
@@ -9,6 +9,7 @@
 -   `SearchControl`: Normalize styles ([#72072](https://github.com/WordPress/gutenberg/pull/72072)).
 -   `Badge`: Avoid propagating text-decoration styles from ancestors into the component ([#72097](https://github.com/WordPress/gutenberg/pull/72097)).
 -   `CheckboxControl`, `RadioControl`, `ToggleControl` (`FormToggle`): Ensure elements are focused when clicked in Safari ([#72115](https://github.com/WordPress/gutenberg/pull/72115)).
+-   `FontSizePicker`: Change selection of font size presets to `selectedSlug`, not `size` ([#71703](https://github.com/WordPress/gutenberg/pull/71703))
```
Comment (t-hamano) [inline packages/components/CHANGELOG.md]: Let's update it along with the latest code implementation.

File: packages/components/src/font-size-picker/font-size-picker-toggle-group.tsx [hunk 9]
```diff
@@ -14,23 +14,77 @@ import { T_SHIRT_ABBREVIATIONS, T_SHIRT_NAMES } from './constants';
 import type { FontSizePickerToggleGroupProps } from './types';
 
 const FontSizePickerToggleGroup = ( props: FontSizePickerToggleGroupProps ) => {
-	const { fontSizes, value, __next40pxDefaultSize, size, onChange } = props;
+	const {
+		fontSizes,
+		value,
+		valueMode = 'literal',
```
Comment (ramonjd) [inline packages/components/src/font-size-picker/font-size-picker-toggle-group.tsx:20]: When I hardcode this value to "slug" it does apply the correct preset where there are duplicate size values, but I think there's a regression as the selected preset is then interpreted as a custom value, and therefore the custom value control displays:

https://github.com/user-attachments/assets/5cb55ab4-1285-4e02-9f25-bd0fe6d9fee1

This is the same for block and global styles controls.

File: packages/components/src/font-size-picker/index.tsx [hunk 10]
```diff
@@ -46,6 +46,7 @@ const UnforwardedFontSizePicker = (
 		size = 'default',
 		units: unitsProp = DEFAULT_UNITS,
 		value,
+		valueMode = 'literal',
```
Comment (ramonjd) [inline packages/components/src/font-size-picker/index.tsx:49]: Is there a condition for which this should be `'slug'`?

**Review by t-hamano — COMMENTED** [review]
Sorry for the late reply.

> If we need some kind of `valueMode: 'literal' | 'slug'` prop that toggles whether the `value` prop expects literal values like before or instead expects slug values, I think that would be preferable to having essentially two props that could carry the selected value. What do you all think?

I think this is a good idea!

Either way, I think we need unit tests to ensure the new prop works correctly.

File: packages/components/src/font-size-picker/types.ts [hunk 11]
```diff
@@ -40,6 +40,14 @@ export type FontSizePickerProps = {
...
 	 */
 	value?: number | string;
+	/**
+	 * Determines how the `value` prop should be interpreted.
+	 * - `'literal'`: The `value` prop contains the actual font size value (number or string)
+	 * - `'slug'`: The `value` prop contains the slug of the selected font size
+	 *
+	 * @default 'literal'
+	 */
+	valueMode?: 'literal' | 'slug';
```
Comment (ramonjd) [inline packages/components/src/font-size-picker/types.ts:50]: Does `selectedSlug` need to be in this type def as well?

E.g., 

```ts
	/**
	 * The slug of the currently selected font size.
	 *
	 * @default null
	 */
	selectedSlug?: string;
```

File: packages/components/src/font-size-picker/font-size-picker-select.tsx [hunk 12]
```diff
@@ -38,11 +42,30 @@ const FontSizePickerSelect = ( props: FontSizePickerSelectProps ) => {
...
 
-	const selectedOption =
-		options.find( ( option ) => option.value === value ) ?? DEFAULT_OPTION;
+	const selectedOption = ( () => {
+		if ( value === undefined ) {
+			return DEFAULT_OPTION;
+		}
+
+		// If valueMode is 'slug', find by slug
+		if ( valueMode === 'slug' ) {
```
Comment (ramonjd) [inline packages/components/src/font-size-picker/font-size-picker-select.tsx:52]: Should this use the selectedSlug?

E.g., 

```tsx
		// If valueMode is 'slug', find by slug
		if ( valueMode === 'slug' && !! selectedSlug ) {
			const optionBySlug = options.find(
				( option ) => option.key === selectedSlug
			);
			if ( optionBySlug ) {
				return optionBySlug;
			}
		}
```

Here's what I'm seeing right now:

https://github.com/user-attachments/assets/45111ab7-c589-4fa8-a873-e2d32212e8f0

File: packages/components/src/font-size-picker/utils.ts [hunk 13]
```diff
@@ -17,3 +22,52 @@ export function isSimpleCssValue(
...
+
+/**
+ * Generates hint text for a font size based on its fluid typography properties.
+ * This function can be used by consumers to generate hint text for font sizes
+ * that have fluid typography properties.
+ *
+ * @param fontSize The font size object to generate hint text for.
+ * @return The generated hint text, or undefined if no hint should be shown.
+ */
+export function generateFontSizeHint( fontSize: FontSize ): string | undefined {
```
Comment (ramonjd) [inline packages/components/src/font-size-picker/utils.ts:29]: Would be good to have unit test coverage for these new changes.

Also in packages/components/src/font-size-picker/test/index.tsx

File: packages/components/src/font-size-picker/font-size-picker-select.tsx [hunk 14]
```diff
@@ -38,11 +42,30 @@ const FontSizePickerSelect = ( props: FontSizePickerSelectProps ) => {
 		} ),
 	];
 
-	const selectedOption =
-		options.find( ( option ) => option.value === value ) ?? DEFAULT_OPTION;
+	const selectedOption = ( () => {
```
Comment (ramonjd) [inline packages/components/src/font-size-picker/font-size-picker-select.tsx]: This might be better placed in `useMemo`, e.g., 

```tsx
const selectedOption = useMemo(() => {
    if ( value === undefined ) {
        return DEFAULT_OPTION;
    }
    // ... logic
}, [value, valueMode, options]);
```

**Review by ramonjd — COMMENTED** [review]
Thanks a lot for tackling this tricky problem!! 🙏🏻 

Sorry if a lot of my comments are premature - I know you're working on the internals. 

I think things are on the right track with the valueMode as folks have suggested, I was just having trouble testing the functionality in both block and global styles. 

From what I can gather we're going to refer to `selectedSlug` and then set `valueMode` to `"slug"` if there is one? 

In my opinion, unit tests would greatly help reason about the logic here (and catch bugs!). Also updating the storybook examples to cover these cases. If this is to get into 6.9 then I think both are required, even as follow ups to this PR.

But I understand things are still in motion so take what I've said with as much salt as you need right now 😄 

Here' an example of some presets I was testing:

<details>

<summary>theme.json typography settings</summary>

```json

		"typography": {
			"defaultFontSizes": false,
			"fluid": true,
			"fontSizes": [
				{
					"name": "Tiny Test",
					"slug": "tiny",
					"size": "12px"
				},
				{
					"name": "Small Test",
					"slug": "small", 
					"size": "12px"
				},
				{
					"name": "Base Test",
					"slug": "base",
					"size": "16px"
				},
				{
					"name": "Medium Test",
					"slug": "medium",
					"size": "18px"
				},
				{
					"name": "Large Test",
					"slug": "large",
					"size": "20px"
				},
				{
					"name": "Extra Large Test",
					"slug": "extra-large",
					"size": "24px"
				},
				{
					"name": "Huge Test",
					"slug": "huge",
					"size": "32px",
					"fluid": {
						"min": "16px",
						"max": "32px"
					}
				},
				{
					"name": "Giant Test",
					"slug": "giant",
					"size": "48px"
				},
				{
					"name": "Display Small Test",
					"slug": "display-small",
					"size": "32px"
				},
				{
					"name": "Display Large Test",
					"slug": "display-large",
					"size": "48px"
				}
			]
		}
	},

```

</details>

File: packages/block-editor/src/components/global-styles/typography-panel.js (hunk 4 above)
Comment (ramonjd) [reply packages/block-editor/src/components/global-styles/typography-panel.js]: Oh, I was under the impression that it's actually required to tell the consuming components (select and toggle) to set the valueMode and lookup selected control value using the current slug?

Sorry, I just started looking at this PR today so might be way off.

It was hard to tell via manual testing since the current state doesn't seem complete? Or at least the bug is still there for me.

Comment (luminuu) [reply packages/block-editor/src/components/global-styles/typography-panel.js]: I missed this yesterday, so I just fixed it in the code and replaced that with the `valueMode` prop.

File: packages/components/CHANGELOG.md (hunk 8 above)
Comment (luminuu) [reply packages/components/CHANGELOG.md]: Done!

File: packages/block-editor/src/hooks/font-size.js (hunk 6 above)
Comment (luminuu) [reply packages/block-editor/src/hooks/font-size.js]: Fixed!

File: packages/block-editor/src/components/global-styles/typography-panel.js (hunk 4 above)
Comment (luminuu) [reply packages/block-editor/src/components/global-styles/typography-panel.js]: Fixed!

**Comment by luminuu** [comment]
> Thanks a lot for tackling this tricky problem!! 🙏🏻
> 
> Sorry if a lot of my comments are premature - I know you're working on the internals.
> 
> I think things are on the right track with the valueMode as folks have suggested, I was just having trouble testing the functionality in both block and global styles.
> 
> From what I can gather we're going to refer to `selectedSlug` and then set `valueMode` to `"slug"` if there is one?
> 
> In my opinion, unit tests would greatly help reason about the logic here (and catch bugs!). Also updating the storybook examples to cover these cases. If this is to get into 6.9 then I think both are required, even as follow ups to this PR.
> 
> But I understand things are still in motion so take what I've said with as much salt as you need right now 😄
> 
> Here' an example of some presets I was testing:
> theme.json typography settings
> 
> ```
> 
> </details>
> ```

Thank you for your feedback @ramonjd! I think the code was a bit confusing, I just removed the remaining `selectedSlug` values, which were in the code of my first iteration. As @t-hamano and @mirka pointed out, it makes no sense to have the value stored in two variables, as there's no single source of truth. So I went ahead and changed the code yesterday to work with the `valueMode` prop. I just removed the remaining instances of `selectedSlug`, so maybe the code is now a bit clearer to understand.

File: packages/components/src/font-size-picker/types.ts (hunk 7 above)
Comment (luminuu) [reply packages/components/src/font-size-picker/types.ts]: I have addressed your feedback in this commit: https://github.com/WordPress/gutenberg/pull/71703/commits/d51729df48527fbc8f329d1ab1f31a8dcd393445

File: packages/block-editor/src/components/global-styles/typography-panel.js (hunk 4 above)
Comment (luminuu) [reply packages/block-editor/src/components/global-styles/typography-panel.js]: I did not completely remove the `selectedSlug` yesterday, sorry for that. It's now fixed.

File: packages/block-editor/src/components/global-styles/typography-panel.js (hunk 5 above)
Comment (aaronrobertshaw) [reply packages/block-editor/src/components/global-styles/typography-panel.js:237]: > Any reason for the self-executing function?

Maybe only in that the current code guards against non-string types. 

I believe the `typography.fontSize` value must be a string so I don't see a lot of difference here, even in terms of performance.

File: packages/components/src/font-size-picker/font-size-picker-toggle-group.tsx (hunk 9 above)
Comment (aaronrobertshaw) [reply packages/components/src/font-size-picker/font-size-picker-toggle-group.tsx:20]: I wasn't able to recreate this bug in testing the latest changes but I'm not sure I followed the same steps as you. Can you confirm if this is still an issue @ramonjd?

File: packages/components/src/font-size-picker/types.ts (hunk 11 above)
Comment (aaronrobertshaw) [reply packages/components/src/font-size-picker/types.ts:50]: I believe this has been cleaned up now. I no longer find any references to `selectedSlug`.

File: packages/components/src/font-size-picker/font-size-picker-select.tsx (hunk 12 above)
Comment (aaronrobertshaw) [reply packages/components/src/font-size-picker/font-size-picker-select.tsx:52]: I can no longer replicate this issue and `selectedSlug` has been removed entirely now so I'll resolve this conversation.

File: packages/components/src/font-size-picker/utils.ts (hunk 13 above)
Comment (aaronrobertshaw) [reply packages/components/src/font-size-picker/utils.ts:29]: +1

File: packages/block-editor/src/components/global-styles/typography-panel.js (hunk 5 above)
Comment (aaronrobertshaw) [reply packages/block-editor/src/components/global-styles/typography-panel.js:237]: Would any other components benefit from a util for extracting slugs from var preset strings? Just wondering if refactoring this in a follow up might be useful 🤷

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for all the hard work on this @luminuu 🙇 

I'm not fully up-to-date on the history and context of this PR but I've taken the latest changes for a spin in both the site editor with global styles and the block editor.

It is testing as per the test instructions for me.

✅ Could replicate issue with toggle group control on trunk
✅ Could replicate issue with font size picker dropdown on trunk
✅ This PR fixes selection of preset font sizes for the toggle group control
✅ This PR fixes selection when picker is using the dropdown
✅ When using this PR I could not replicate [reported custom value issue](https://github.com/WordPress/gutenberg/pull/71703#discussion_r2438156449)

This is very close I think. Just a few remaining pieces of earlier feedback to address and it should be good to go.

The unit tests don't need to be a blocker and could be added via a follow-up.

File: packages/components/src/font-size-picker/font-size-picker-toggle-group.tsx (hunk 9 above)
Comment (ramonjd) [reply packages/components/src/font-size-picker/font-size-picker-toggle-group.tsx:20]: Thanks for testing. I can't reproduce this bug now either! 🌮

**Comment by ramonjd** [comment]
> I just removed the remaining selectedSlug values, which were in the code of my first iteration.

Ah got it, thanks for that. I retested and things are working well. 

Just curious if other folks can see the selected preset disappearing after save (this is for toggle + select, block + global styles)

https://github.com/user-attachments/assets/9ff94f73-c527-456d-80ca-95095ea69f30


Here's the JSON I'm using to test:


```json
		"typography": {
			"defaultFontSizes": false,
			"fluid": true,
			"fontSizes": [
				{
					"name": "Extra Large Test",
					"slug": "extra-large",
					"size": "24px"
				},
				{
					"name": "Huge Test",
					"slug": "huge",
					"size": "32px",
					"fluid": {
						"min": "16px",
						"max": "32px"
					}
				},
				{
					"name": "Giant Test",
					"slug": "giant",
					"size": "48px"
				},
				{
					"name": "Display Small Test",
					"slug": "display-small",
					"size": "32px"
				},
				{
					"name": "Display Large Test",
					"slug": "display-large",
					"size": "48px"
				}
			]
		}
	},
```

**Comment by aaronrobertshaw** [comment]
@ramonjd Thanks for the extra debugging and testing here. I can replicate the issue you reported.

I used empty theme and simply added two font size presets with matching font size values.

From my debugging so far the issue is related to the different preset data formats between global styles and block supports. I believe block supports will encode to a `var:preset:*` string whereas global styles uses `var(--wp--preset--*)`.

Quickly updating the `currentFontSizeSlug` logic to handle this appears on the surface to fix the selection however the persisting of the font size still isn't correct so the selection is lost on refreshing the page.

**Comment by aaronrobertshaw** [comment]
@luminuu I hope you don't mind but I took the liberty of pushing a quick commit that I believe fixes the issue @ramonjd [highlighted](https://github.com/WordPress/gutenberg/pull/71703#issuecomment-3420095520).

This quick fix has the selection of font size presets working again for me in the Global Styles typography panel.

https://github.com/user-attachments/assets/4f832ac0-2307-41ce-bafe-5e1544b6d420

It appears our CI is down due to an AWS outage. @ramonjd if you can re-test and confirm this fix, could you also then kick off the e2es as well?

**Comment by luminuu** [comment]
Thank you for the quick fix @aaronrobertshaw! I'll work on the other feedback @ramonjd has provided today, if there's anything no longer relevant just mark it as resolved.

File: packages/block-editor/src/components/global-styles/typography-panel.js (hunk 5 above)
Comment (luminuu) [reply packages/block-editor/src/components/global-styles/typography-panel.js:237]: I'm marking this as resolved for now as @aaronrobertshaw has added a fix for this section in his recent commit, so I'm not breaking anything.

File: packages/components/src/font-size-picker/font-size-picker-select.tsx (hunk 14 above)
Comment (luminuu) [reply packages/components/src/font-size-picker/font-size-picker-select.tsx]: Done in https://github.com/WordPress/gutenberg/pull/71703/commits/da2c0977b3334cac93720652db6929e97893d0ff

File: packages/components/src/font-size-picker/index.tsx (hunk 10 above)
Comment (luminuu) [reply packages/components/src/font-size-picker/index.tsx:49]: It's `literal` when you use a custom font size that is not a preset, but it's `slug` when you use a preset. Previously the font size was only working with `size`, so you were not able to select a different font size if the `size` property held the same value, even if it was a fixed vs. a fluid value. Now it differentiates on the slugs of you use a preset, so when using for example TT5 it can hold `small`, `medium`, `large` and so on, and custom sizes well you can add via the typography interface.

File: packages/components/src/font-size-picker/utils.ts (hunk 13 above)
Comment (luminuu) [reply packages/components/src/font-size-picker/utils.ts:29]: Added unit tests in https://github.com/WordPress/gutenberg/pull/71703/commits/d85704ef1a19de031c713352c1c7f59607cd0d54

**Comment by luminuu** [comment]
I've now figured out why the one Playwright test is failing: in trunk, when selecting a font size preset from the dropdown, the `size` prop is added to the input field when you switch from presets to "Set custom size" (the toggle on the right next to the "Size" heading). With this PR, this is no longer happening and therefore the test is failing. I haven't looked into the other tests in detail but I assume there might be similar issues.

I assume this needs to be fixed and we're not changing the Playwright tests, is that correct? @ramonjd

**Comment by luminuu** [comment]
Figured out the issue with the failing checks myself and did another commit. I think I have addressed all feedback, let me know if there's still something unclear / I should take a look at.

**Comment by ramonjd** [comment]
Thanks @luminuu and @aaronrobertshaw 

This is testing well for me! 

- selected presets persist in the controls where there are duplicates
- global styes/block styles are applied as expected
- no regressions on fluid typography values as far as I can see

I appreciate all the hard work 🙇🏻 

@t-hamano do you think we can still get this PR into 6.9 in the next package update?

**Review by ramonjd — APPROVED** [review]
Thanks for sticking with this one @luminuu 

And for the tests! 

I think this is going to be a high-impact bug fix.

**Comment by t-hamano** [comment]
> do you think we can still get this PR into 6.9 in the next package update?

This PR adds a new prop to a component, so it's strictly an enhancement. Gutenberg 21.9 RC1 and RC2 have already been released, but if RC3 is planned before 6.9 Beta1, this PR could be cherry-picked. cc @ellatrix @priethor 

However, since this PR fixes many bugs at the same time, I think it would be fine to backport it to Beta1 or later.

**Comment by Mamaduka** [comment]
I think it's okay to include this in beta cycles.

**Comment by priethor** [comment]
Confirming we are having a GB RC3 with the latest cherry-picked PRs, but I agree it's fine to ship this post-Beta1.

File: packages/components/src/font-size-picker/types.ts (hunk 11 above)
Comment (t-hamano) [inline packages/components/src/font-size-picker/types.ts:50]: It would be a good idea to add the `valueMode` prop and `hint` prop to the README.md.

**Review by t-hamano — COMMENTED** [review]
Is there anything else we should do? If not, let's backport it to 6.9 Beta2.

File: packages/components/src/font-size-picker/types.ts (hunk 11 above)
Comment (ramonjd) [reply packages/components/src/font-size-picker/types.ts:50]: I can do this quickly, then merge this PR if folks have no objections.
