### PR TITLE
Zoom out: hide toolbar icon on smaller viewports

### LINKED ISSUE #65431: Zoom out view: Toggle button should be disabled in mobile view
### Description

The toggle button doesn't work in mobile view.
I think it should be disabled in mobile view, like the device dropdown.

### Step-by-step reproduction instructions

- Enable "Zoom out experiments" on the Gutenberg Experiments page
- open the post editor
- Narrow the browser width
- Click the Zoom out mode button

### Screenshots, screen recording, code snippet

image

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by MaggieCabrera**
## What?

Closes https://github.com/WordPress/gutenberg/issues/65431

## Why?

Zoom out doesn't make sense on mobile, so we might as well hide it

## How?

Checks for the viewport width to conditionally render the zoom out button on the toolbar

## Testing Instructions

Check that the icon is not showing when on smaller viewports

## Screenshots or screencast 

Before | After 
--- | ---
Screenshot 2024-09-18 at 11 54 24 | Screenshot 2024-09-18 at 11 54 32

### CODE REVIEW

**Review by draganescu — APPROVED** [review]
LGTM 🚢 it

File: packages/editor/src/components/header/index.js [hunk 1]
```diff
@@ -143,7 +143,7 @@ function Header( {
 				/>
 				<PostViewLink />
 
-				<ZoomOutToggle />
+				{ isWideViewport && <ZoomOutToggle /> }
```
Comment (t-hamano) [inline packages/editor/src/components/header/index.js:146]: Sorry for the late review.

Isn't this `isLargeViewport`? Otherwise, it won't match the visibility of the device preview button.

The device preview dropdown appears when the browser width is `783px` or more, while the zoom out toggle appears when the browser width is `960px` or more:


https://github.com/user-attachments/assets/48c4eeef-3e6b-4074-a05d-ba9ade005225

Comment (MaggieCabrera) [reply packages/editor/src/components/header/index.js:146]: I'm not so sure zoom out and device preview need to behave exactly the same. I would worry more about: is the viewport large enough for zoom out to be a good experience?

Comment (t-hamano) [reply packages/editor/src/components/header/index.js:146]: If the zoom out mode requires a wide viewport to work properly, shouldn't that be the case in device preview as well? Either way, I would expect device preview and zoom out mode to follow consistent viewport rules.
