### PR TITLE
Code Block should not render embeds (or shortcodes)

### LINKED ISSUE #13927: Code Block renders embeds
**Describe the bug**
The Code Block renders embeds. 

**To Reproduce**
1. Create a code block.
2. Insert the following shortcode.

`[embed width="560" height="315"]
    https://www.youtube.com/watch?v=YuOBzWF0Aws
[/embed]`

3. Update the post.
4. You will see a YouTube Video inside a Code Block in your frontend.

**Expected behavior**
I expected the code block to display every character of (pseudo) code inside it. Nothing should render at all.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser: Any

**Additional context**
- WordPress 5.0.3

### PR DESCRIPTION
**Pull request by davilera**
## Description
Fixes #13927 - _"The Code Block renders embeds"_. As OP said:

> I expected the code block to display every character of (pseudo) code inside it. Nothing should render at all.

Not only should block codes not render embeds, but also they should not render shortcodes.

## How has this been tested?

I've reproduced the bug described in #13927.

The PR prevents shortcodes from running by changing an embed's opening character `[` to `&#91;`.

It also prevents isolated URLs from becoming an embed by changing `https://` to `https:&#47;&#47;`.

## Types of changes

Bug fix. In a code block:

* `&` is saved as `&amp;`.
* `[` is saved as `&#91;`.
* `/` is saved as `&#47;` (in isolated URLs only).

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows the accessibility standards.
- [x] My code has proper inline documentation.
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/block-library/src/code/index.js [hunk 1]
```diff
@@ -68,6 +69,24 @@ export const settings = {
...
+}
+
+function escapeOpeningSquareBrackets( content ) {
+	// This replicates the escaping of HTML tags, where
+	// a tag like <strong> becomes &lt;strong>
+	return content.replace( /\[/g, '&#91;' );
+}
+
+function escapeProtocolInIsolatedUrls( content ) {
+	return content.replace( /(^[^.]^https?:)\/\/([^\s]+$[^.]$)/m, '$1&#47;&#47;$2' );
```
Comment (aduth) [inline packages/block-library/src/code/index.js]: While the function names are to an extent self-documenting, it still took me more than a few moments to determine what's happening here and why. I think it could be improved with a JSDoc block for the functions and perhaps some unit tests to describe the expected behavior.

I'm still a bit lost on the regular expression itself, specifically the `[^.]` bits, since I would think they'd be expecting some non-period (`.`) content on the lines prior to or following the URL?

**Review by aduth — COMMENTED** [review]
Part of me wonders if this is not something the server should be considering when evaluating whether to transform an embed or shortcode.

Namely, even after these changes, I'd still be able to produce fascinating results when manually crafting a post with the content:

```html
<pre><code>

https://www.youtube.com/watch?v=YuOBzWF0Aws

</code></pre>
```

File: packages/block-library/src/code/index.js [hunk 2]
```diff
@@ -3,6 +3,7 @@
  */
 import { __ } from '@wordpress/i18n';
 import { createBlock } from '@wordpress/blocks';
+import { compose } from '@wordpress/compose';
```
[the remark this answers is not in the document]
Comment (davilera) [reply packages/block-library/src/code/index.js]: Thanks for the tip! I didn't know about `lodash`'s function. Fixed in 68e78db.

File: packages/block-library/src/code/index.js [hunk 3]
```diff
@@ -68,6 +69,24 @@ export const settings = {
 	edit,
 
 	save( { attributes } ) {
-		return <pre><code>{ attributes.content }</code></pre>;
+		const content = compose(
+			escapeOpeningSquareBrackets,
+			escapeProtocolInIsolatedUrls
+		)( escapeAmpersands( attributes.content || '' ) );
```
[the remark this answers is not in the document]
Comment (davilera) [reply packages/block-library/src/code/index.js]: I wanted `escapeAmpersands` to be the first function to run, and `compose` seems to work the other way around. Anyway, 68e78db uses `lodash`'s `flow` function, which runs each function as it appears in the source code so... fixed.

File: packages/block-library/src/code/index.js (hunk 1 above)
Comment (davilera) [reply packages/block-library/src/code/index.js]: I modified the RegExp in 4f97f2c so that it matches the RegExp used in PHP. I also documented the functions in d11537f.

**Comment by davilera** [comment]
> Part of me wonders if this is not something the server should be considering when evaluating whether to transform an embed or shortcode.

I agree. AFAIK, though, WordPress transforms embeds/shortcodes in the post content ignoring the fact that they might be in a block.

If you feel like tweaking code block's save method isn't a good idea, I'd recommend a different approach: run a filter in the post content with a higher priority and escape the characters before embed/shortcodes run. That is, doing the same this PR does, but in PHP and performing the escape on the fly (without committing them to the DB).

This alternative solution, however, would require a few more additional changes: we would also need to add a new filter or extend the blocks API so that developers could specify which blocks accept embed/shortcodes and which blocks don't.

So, how should I/we proceed?

File: packages/block-library/src/code/index.js [hunk 4]
```diff
@@ -68,6 +73,58 @@ export const settings = {
...
+
+/**
+ * Converts the first two forward slashes of any isolated URL into their HTML
+ * counterparts (i.e. // => &#47;&#47;). For instance, https://youtube.com/watch?x
+ * becomes https:&#47;&#47;youtube.com/watch?x.
+ *
+ * An isolated URL is a URL that sits in its own line, surrounded only by spacing
+ * characters.
+ *
+ * See wp-includes/class-wp-embed.php:387 (function autoembed)
```
Comment (aduth) [inline packages/block-library/src/code/index.js]: Line numbers without an associated version/tag/commit are very likely to fall out of sync as future changes are made to the file. In fact, in the current trunk version it currently points to a line which has no content:

https://github.com/WordPress/wordpress-develop/tree/master/src/wp-includes/class-wp-embed.php#L387

A link like this may work better, as it's pinned to a specific version:

https://github.com/WordPress/wordpress-develop/blob/5.0.3/src/wp-includes/class-wp-embed.php#L387

**Review by aduth — COMMENTED** [review]
>So, how should I/we proceed?

I think as implemented here is fine.

Worth noting, however, that it relies on the specific behavior of `@wordpress/element`'s `renderToString` behavior departing from that of React, where `React.renderToStaticMarkup` may result in double-escaping if given the block element input here.

```
⇒ node       
> var { renderToStaticMarkup } = require( 'react-dom/server' );
> var { createElement, renderToString } = require( '@wordpress/element' );
> renderToStaticMarkup( createElement( 'code', null, '&#91;myshortcode/]' ) );
'<code>&amp;#91;myshortcode/]</code>'
> renderToString( createElement( 'code', null, '&#91;myshortcode/]' ) );
'<code>&#91;myshortcode/]</code>'
```

It's not strictly an issue, but may become problematic if the behavior changes over time. I might like to see some tests here to avoid future regressions to this point, or even just enhancing / adding additional variations to the existing code block fixtures:

https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/fixtures/blocks/core__code.html

(Running `npm run fixtures:regenerate` after changing / adding new fixtures)

File: packages/block-library/src/code/index.js (hunk 4 above)
Comment (davilera) [reply packages/block-library/src/code/index.js]: Fixed in c2a352cdaabf7b7d5ffe4dd71fdd72220e00feaf

**Comment by davilera** [comment]
Thanks for all the tips, @aduth. Finally, I've decided to follow a different approach.

Instead of escaping shortcode and link characters in `save`, I'm now escaping them when `CodeEdit` runs `setAttributes`. This allows me to undo this action when the content is about to be shown in `CodeEdit`.

I think this solution fixes the issue that you said could arise in the future, and it's probably more elegant.

What do you think?

File: packages/block-library/src/code/utils.js [hunk 5]
```diff
@@ -0,0 +1,117 @@
...
+ * characters.
+ *
+ * See https://github.com/WordPress/wordpress-develop/blob/5.1.1/src/wp-includes/class-wp-embed.php#L403
+ *
+ * @param {string}  content The content of a code block.
+ * @return {string} The given content with the first two forward slashes of any
+ *                  isolated URL from the HTML entity &#73; into /.
+ */
+function unescapeProtocolInIsolatedUrls( content ) {
+	return content.replace( /^(\s*https?:)&#47;&#47;([^\s<>"]+\s*)$/m, '$//$2' );
```
Comment (aduth) [inline packages/block-library/src/code/utils.js]: I don't think this works as expected. Namely, I'm guessing `$` should be `$1`.

```js
'https:&#47;&#47;www.youtube.com/watch?v=YuOBzWF0Aws'.replace( /^(\s*https?:)&#47;&#47;([^\s<>"]+\s*)$/m, '$//$2' );
// "$//www.youtube.com/watch?v=YuOBzWF0Aws"
```

```suggestion
	return content.replace( /^(\s*https?:)&#47;&#47;([^\s<>"]+\s*)$/m, '$1//$2' );
```

On that note, are you able to take a pass at including some unit tests for these functions?

**Review by aduth — CHANGES_REQUESTED** [review]
Apologies for the delay in revisiting this.

I think the general approach seems agreeable. There's certainly some prior art in this sort of "value dance", like seen in the [preformatted block](https://github.com/WordPress/gutenberg/blob/3d6fe8e3d9816b0017b9e1d69ced4103f67e7059/packages/block-library/src/preformatted/edit.js#L13-L22).

I observed an issue in testing this with a code block consisting of newlines + YouTube URL, noted in the review comments.

File: packages/block-library/src/code/utils.js (hunk 5 above)
Comment (davilera) [reply packages/block-library/src/code/utils.js]: Thanks for catching that bug! I fixed it in d86123aea177254a8ee5996cbe834c7ace169efc.

> On that note, are you able to take a pass at including some unit tests for these functions?

Sure, I'll give it a shot and commit them later on today.

Comment (aduth) [reply packages/block-library/src/code/utils.js]: > Sure, I'll give it a shot and commit them later on today.

No rush from my end, but just curious if you'd still planned to make these revisions?

Comment (davilera) [reply packages/block-library/src/code/utils.js]: Oops, sorry! I tried to create the tests, but I don't know where they should be... I've seen some blocks have a `test` folder, but have no idea what's the correct approach. Any tips?

Comment (aduth) [reply packages/block-library/src/code/utils.js]: > Oops, sorry! I tried to create the tests, but I don't know where they should be... I've seen some blocks have a `test` folder, but have no idea what's the correct approach. Any tips?

The general pattern is to create a file with the same name under a `test` directory relative to the file under test.

Example:

```
packages/block-library/src/code/utils.js
packages/block-library/src/code/test/utils.js
```

This could be better documented 😄

Comment (davilera) [reply packages/block-library/src/code/utils.js]: Cool! I created a few unit tests in commit 1cb6ff810371f1f621b1cf19cb8a958d136da5cd. Oh, and I then renamed the test file from `index.js` to `utils.js` in 03e618dc6c547517a9b154313c8642199eac879a.

Is there anything left?

Comment (davilera) [reply packages/block-library/src/code/utils.js]: Fixed in 1cb6ff810371f1f621b1cf19cb8a958d136da5cd and 03e618dc6c547517a9b154313c8642199eac879a.

**Comment by davilera** [comment]
I created a few unit tests in commit 1cb6ff810371f1f621b1cf19cb8a958d136da5cd. Oh, and I then renamed the test file from `index.js` to `utils.js` in 03e618dc6c547517a9b154313c8642199eac879a.

Is there anything left?

**Review by aduth — APPROVED** [review]
This looks great and works well in my testing 👍 

I'd considered whether overlap with the `escape` name in the JavaScript specification may be of concern ([reference](https://www.ecma-international.org/ecma-262/6.0/#sec-escape-string)). While it could be a problem for future maintainability on the point of confusion around whether the symbols refer to the global or the imported value, it doesn't have an effective impact as long as the imported values are in scope. For that reason, I'd not consider it to be a blocker.

Thanks for your patience in the reviews on this one.
