### PR TITLE
Writing Flow: allow undo of patterns with BACKSPACE and ESC

### LINKED ISSUE #8942: Rich Text: Patterns transform should undo on subsequent Backspace or Esc
Given the following set of steps, I would expect that the "Backspace" key press should result in the list being reverted back into a paragraph.

1. Navigate to Posts > Add New
2. Click the writing prompt to add a paragraph
3. Type "- " (dash, space) or "# " (number sign, space)
4. Observe that a list transform is applied
5. Press Backspace
6. Observe that nothing happens

When a pattern transform is applied, we should consider it a tentative transformation until the user takes further action. If that further action is an immediate Backspace keypress, the transformation should be reverted.

Many WYSIWYG behave this way, for example Google Docs. 

Open questions:

- At what point do we no longer consider the transform tentative?
- What is responsible for maintaining the state of this tentative transaction?
   - Is it internal state of RichText ? Since a transform is a replacement, the RichText may no longer exist after the transformation is applied.
   - Is it the top-level editor state ? It could be integrated into the `replaceBlocks` action creator as an option, perhaps leveraging `redux-optimist` for the start / commit states.

cc @iseulde

### LINKED ISSUE #16649: Adding a `>` to the beginning of a line forces a conversion to a Quote block
**Describe the bug**
I'm trying to create my own list of items and add my own bullet point, a `>` character. Every time I do this, Gutenberg converts the Paragraph block to a Quote block. If I was in some sort of markdown editor, I'd expect this, but I'm not. I'm just trying to add a `>` to the beginning of my paragraph.

**To reproduce**
1. Add a Paragraph block.
2. Add a `>` character to the beginning of the text.
3. Add a `space` after that character.
4. Observe the block switch to a Quote block.

**Expected behavior**
I expect to add any character I want anywhere on the page without triggering a markdown switch of blocks.

**Screenshots**

bullet

**Desktop (please complete the following information):**
 - OSX
 - Firefox 68.0
 - Gutenberg 6.1

### LINKED ISSUE #17038: List block: Can't start the first sentence with "1. " without the block changing to List
I'm trying to write a list of steps that includes block quotes between each numbered step. This breaks expected behavior for the list block, which is fine — I didn't expect the list block to be able to format around my additional blocks between numbered items (though that would be nice). 

The problem comes in when I try to start a text block like "**2.** Then we did this thing..." Starting the first sentence in a block with `number + . + space` results in the block turning into a list block (and thus indenting, which I don't want it to do, because then it looks weird with my block quotes). If I try to convert it back to a text block, the number goes away. >:-(

My workaround is to open up "code mode" and painstakingly find the paragraph I'm looking for, and add the number, period, and space. Yuck!

I wish the convert-to-list-block feature were smart enough to detect that if I revert back from List block a few times in a row, I don’t want the List block.

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #8942.
Fixes #16649.
Fixes #17038.

Sets a flag when an automatic change (input rule) happened, so it can be used to undo when `Backspace`, `Delete` or `Escape` is pressed. The flag is removed as soon any action follows.

This will hopefully alleviate the frustration when something automatically changes based on an input rule. It doesn't restore the selection though, only the content. For that, we'll need #16428.

## How has this been tested?

See e2e tests.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by draganescu** [comment]
Hi @ellatrix I have tested the branch and it worked but it behaved in a strange way:

undo-with-backspace-focus-lost

When the Undo is applied the focus is lost and I can't continue typing.

**Comment by ellatrix** [comment]
@draganescu That's "normal". We don't have the ability yet to restore selection after undo, for that we'll need #14640. :) To test: try to undo anything in the editor, like typing a word, and you'll see that selection will be lost.

Thanks for reviewing!

**Review by draganescu — APPROVED** [review]
@ellatrix you are correct, that is the "normal" behavior, which makes this change set good to go. There are some conflicts though, but that it all

**Comment by mapk** [comment]
I'm really hoping this is the solution for #16649, but it appears there are some conflicts. Can this get rebased? I'd love to test against #16649.

**Comment by ellatrix** [comment]
Last time I checked I ran into some issues. I'll have to look into this again.

**Comment by ellatrix** [comment]
> When the Undo is applied the focus is lost and I can't continue typing.

For that we'll need #16428, which is ready for final review.

**Comment by mapk** [comment]
🎉 😄

File: packages/block-editor/src/components/rich-text/index.js [hunk 1]
```diff
@@ -293,6 +296,16 @@ class RichTextWrapper extends Component {
 		return formattingControls.map( ( name ) => `core/${ name }` );
 	}
 
+	/**
+	 * Marks the last change as an automatic change at the next idle period to
+	 * ensure all selection changes have been recorded.
+	 */
+	markAutomaticChange() {
+		window.requestIdleCallback( () => {
```
Comment (mcsf) [inline packages/block-editor/src/components/rich-text/index.js]: Do we polyfill `requestIdleCallback`? It doesn't seem [ready for primetime](https://caniuse.com/#feat=requestidlecallback). Elsewhere in the codebase we have a fallback for it:

https://github.com/WordPress/gutenberg/blob/9c58193621b4bb913bcc6991426c1e9b97dcc9f7/packages/priority-queue/src/index.js#L1

Comment (mcsf) [reply packages/block-editor/src/components/rich-text/index.js]: Addressed in #17213
