### PR TITLE
fix: Downgrade Docker image for WordPress

### LINKED ISSUE #8418: Updating WordPress fails causing local pretest, CI, etc. failures
Argh everything is broken! 😡

Nearly any CI test that relies on the `bin/install-wordpress.sh` script is failing across branches: https://travis-ci.org/WordPress/gutenberg/jobs/411608028#L1164

Additionally, `npm run test-e2e` will fail because `pretest-e2e` runs `bin/install-wordpress.sh --e2e_tests`. `bin/setup-local-env.sh` also fails.

It seems very obscure because we hide Docker output... maybe we should stop. This is the offending line: https://github.com/WordPress/gutenberg/blob/master/bin/install-wordpress.sh#L52

If you uncomment the output being sent to `/dev/null` you'll see:

```
STATUS: Installing WordPress...
Warning: Unable to create directory wp-content/uploads/2018/08. Is its parent directory writable by the server?
Success: WordPress installed successfully.
Updating to version 4.9.8 (en_US)...
Downloading update from https://downloads.wordpress.org/release/wordpress-4.9.8-no-content.zip...
Unpacking the update...
Error: Could not create directory.
```

### PR DESCRIPTION
**Pull request by tofumatt**
## Description
I've forced our Docker image to be WordPress 4.9.7. If anything, it's possible we want to stick to pinning versions; this sort of upset to our CI/dev environments because of upstream changes is not good.

Fixes #8418.

## How has this been tested?
Run `./bin/setup-local-env.sh`; it worked. Run `npm run test-e2e`; they work.

## Testing instructions

1. Run `./bin/setup-local-env.sh`; it should output the "Gutenberg is ready" text.
2. Run `npm run test-e2e`; the tests should run.

### CODE REVIEW

**Comment by sarahmonster** [comment]
I broke it!

```
STATUS: Installing WordPress...
Success: WordPress installed successfully.
Updating to version 4.9.8 (en_US)...
Downloading update from https://downloads.wordpress.org/release/wordpress-4.9.8-no-content.zip...
Unpacking the update...
Error: Could not create directory.
```

Also, you may want to fix that CI build that's failing. 😜 🙃

**Comment by tofumatt** [comment]
BLARG, I'm so dumb. I had `docker-compose run --rm $CLI core update >/dev/null` commented out locally so it worked for me. Hmmm... maybe something is just up with 4.9.8? 🤔

**Comment by tofumatt** [comment]
I'm wondering if the permissions issue is related to 0b368452b84a309e416f3a312d969ed8156e4e88... testing now. If so I'll add a comment back to it and maybe it won't get deleted by me thinking it's not needed 😓

**Comment by notnownikki** [comment]
I found an issue switching to php5.2, so deleted the cached build and now there's an issue _building_ it.

Expect more 80s/90s lyrics themed debug commit messages from me. A _lot_ more.

**Comment by aduth** [comment]
>I'm wondering if the permissions issue is related to 0b36845...

But we no longer assign the `-u` flag in master?

**Comment by tofumatt** [comment]
> But we no longer assign the `-u` flag in master?

Sorry, I wasn't clear. That was my point; maybe not assigning it is the issue.

And, in fact, if I supply it the update script totally works. I then run into an issue with the PHPUnit Docker:

```
STATUS: Attempting to connect to WordPress.....
STATUS: Installing WordPress...
Success: WordPress installed successfully.
Success: WordPress is up to date.
STATUS: Activating Gutenberg...
Plugin 'gutenberg' activated.
Success: Activated 1 of 1 plugins.
STATUS: Installing PHPUnit test scaffolding...
env: can't execute 'bash -x -v': No such file or directory
```

**Comment by notnownikki** [comment]
`env: can't execute 'bash -x -v': No such file or directory` was me getting debug wrong. That's fixed now.

File: bin/install-php-phpunit.sh [hunk 1]
```diff
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -e -x
```
Comment (tofumatt) [inline bin/install-php-phpunit.sh]: Can we use `set` for this instead? It breaks locally so makes things hard to test locally 🤷‍♂️

Comment (notnownikki) [reply bin/install-php-phpunit.sh]: gone now, we're back to building and using php5.2 with the latest commit

**Comment by tofumatt** [comment]
Looks like the same test is still failing, even for 4.9.7: https://travis-ci.org/WordPress/gutenberg/jobs/411763137#L1106

😢

**Comment by notnownikki** [comment]
Ok, I can reproduce this locally now, there's something going on with the docker path that's different to the non-docker path we use when we switch php versions.

**Comment by notnownikki** [comment]
one of the images that runs phpunit has 4.9.8 on it.
￼￼￼￼￼
```
nikki@tardis:~/code/test-4.9.7-g$ docker-compose run --rm wordpress_phpunit cat /tmp/wordpress/wp-includes/version.php
<?php
/**
 * The WordPress version string
 *
 * @global string $wp_version
 */
$wp_version = '4.9.8';
```

**Review by youknowriad — APPROVED** [review]
Honestly, I don't really understand the changes here, but I guess since we're trying to fix the e2e tests environment, the most important validation is that the tests pass. So I'm approving
