### PR TITLE
Fix unexpected movements, and closing on first click in the color picker

### LINKED ISSUE #35640: New color picker: Overview of the bugs
### Description

- When slowly dragging the color picker the is some unexpected movement on the color picking circle.
- During the first interaction if we click right away on the color picker if it is inside a popover the popover closes unexpectedly.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #35675: Components: `ColorPicker` "vibrates" when moving the circle slowly
Initially flagged by @mtias in #35662

https://user-images.githubusercontent.com/548849/137453165-6a360e0c-2ae9-4272-804e-d65d2576af97.mov

### LINKED ISSUE #35677: Components: `ColorPicker` closes randomly on occasions when trying to interact with it
Initially flagged by @mtias in #35662

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Fixes: https://github.com/WordPress/gutenberg/issues/35640, https://github.com/WordPress/gutenberg/issues/35677, https://github.com/WordPress/gutenberg/issues/35675

The color picker was having some random movements during small dragging interaction as we can see on this video shared by @mtias

https://user-images.githubusercontent.com/11271197/137486154-694cceb6-483b-49c9-bd54-16093a3df833.mov

At first, I thought it could be related to debouce usage but when I removed the debounce usage the component started to crash. Because of recursive setState calls.

What was happening is that the react-colorful picker components expect that if there are no outside changes in the color the object passed to the component is the same as the component passed on the onChange.
In our usages we receive an object on the onChange then that color is serialized in the block attributes and we pass an object with the same color but the object may have some differences and is not the same object so the component thinks an outside change happened and recomputes the position of the picker that may be some pixels on the side (e.g: multiple pixels may be representing the same color and there is random movement between this pixels).
A simple way to resolve this issue is to use the string-based pickers so we always pass an equivalent string to the one we received on the onChange and the position is not recomputed and the component does not enter on recursive setState so we can remove the debounce.

It is not clear why the issue of the component when inside a popover closing during the first click is fixed. But I guess a combination of the debouce removal and fewer rerenders because of prop changes may explain it.

## Testing

I replicated the steps shared on the video above and verified there are no random movements.
I used the component to choose colors by dragging the color picker fast and verified the UI was responsive so we can remove debounce usage safely.
I opened the color picker in a place where the color was not set before and rapidly clicked on the color area to select some color. I verified the custom color popover did not randomly close.

### CODE REVIEW

File: packages/components/src/color-picker/picker.tsx [hunk 1]
```diff
@@ -15,8 +15,10 @@ interface PickerProps {
 }
 
 export const Picker = ( { color, enableAlpha, onChange }: PickerProps ) => {
-	const Component = enableAlpha ? HslaColorPicker : HslColorPicker;
-	const hslColor = useMemo( () => color.toHsl(), [ color ] );
+	const Component = enableAlpha
+		? RgbaStringColorPicker
+		: RgbStringColorPicker;
+	const hslColor = useMemo( () => color.toRgbString(), [ color ] );
```
Comment (noisysocks) [inline packages/components/src/color-picker/picker.tsx]:
```suggestion
	const rgbColor = useMemo( () => color.toRgbString(), [ color ] );
```

**Review by noisysocks — APPROVED** [review]
Tests well! Code changes look good—should be backwards compatible.

File: packages/components/src/color-picker/component.tsx [hunk 2]
```diff
@@ -59,32 +57,23 @@ const ColorPicker = (
 ) => {
 	const {
 		enableAlpha = false,
-		color: colorProp,
+		color,
 		onChange,
-		defaultValue,
+		defaultValue = '#fff',
```
Comment (ciampo) [inline packages/components/src/color-picker/component.tsx:62]: We should update the [README](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/color-picker/README.md?plain=1#L43) and any potential JSDocs types to add the Default value of the `defaultValue` prop — @jorgefilipecosta would you be able to follow up with this small change?

File: packages/components/src/color-picker/component.tsx [hunk 3]
```diff
@@ -59,32 +57,23 @@ const ColorPicker = (
...
 		copyFormat,
 		...divProps
 	} = useContextSystem( props, 'ColorPicker' );
 
-	const [ color, setColor ] = useControlledValue( {
-		onChange,
-		value: colorProp,
-		defaultValue,
-	} );
```
Comment (ciampo) [inline packages/components/src/color-picker/component.tsx:73]: I'm not sure if moving away from `useControlledValue` caused any regressions — @diegohaz could you take a quick look?

File: packages/components/src/color-picker/picker.tsx [hunk 4]
```diff
@@ -15,12 +15,14 @@ interface PickerProps {
 }
 
 export const Picker = ( { color, enableAlpha, onChange }: PickerProps ) => {
-	const Component = enableAlpha ? HslaColorPicker : HslColorPicker;
-	const hslColor = useMemo( () => color.toHsl(), [ color ] );
+	const Component = enableAlpha
```
Comment (ciampo) [inline packages/components/src/color-picker/picker.tsx:18]: While I understand why we switched from an object-based to a string-based picker, I don't understand why we switched also from an HSL-based to an RBG-based picker — could you explain why?

**Review by ciampo — COMMENTED** [review]
Late to the (review) party — I was AFK for the past 2 weeks. While I'm catching up, I thought I'd leave some inline feedback.

Also, as a general rule of thumb, it'd be better to get some feedback from components-folks before merging PRs that involve components, especially when these components are not experimental, in order to make sure that we avoid introducing breaking changes as much as possible and we keep the docs up to date (cc @griffbrad)

File: packages/components/src/color-picker/component.tsx (hunk 3 above)
Comment (diegohaz) [reply packages/components/src/color-picker/component.tsx:73]: Hmm! I don't understand why we need to move away from `useControlledValue` in this case, but maybe this is an issue with the `useControlledValue` function itself.

I wonder if the fact that we're not memoizing the state updater here is causing any problem since the original updater from `useState` is supposed to be stable:
https://github.com/WordPress/gutenberg/blob/8ccd5e159c2ed90318601eef1c8e5e26d5cea76f/packages/components/src/utils/hooks/use-controlled-value.ts#L35-L38

File: packages/components/src/color-picker/picker.tsx (hunk 4 above)
Comment (jorgefilipecosta) [reply packages/components/src/color-picker/picker.tsx:18]: The format we use outside the component is hex code which maps directly to RGB just by converting hex to decimal. Since we are changing to a string-based picker why not use the RGB one when it maps more directly? What advantage do we get in using an HSL string-based picker?

File: packages/components/src/color-picker/component.tsx (hunk 3 above)
Comment (jorgefilipecosta) [reply packages/components/src/color-picker/component.tsx:73]: The only reason I removed the useControlledValue call was that everything seemed to be working as before without it. It seems on this case it is not needed.

File: packages/components/src/color-picker/component.tsx (hunk 2 above)
Comment (jorgefilipecosta) [reply packages/components/src/color-picker/component.tsx:62]: Sure I will work on a PR with this change.

File: packages/components/src/color-picker/component.tsx (hunk 3 above)
Comment (ciampo) [reply packages/components/src/color-picker/component.tsx:73]: Just cc'ing @sarayourfriend who wrote this part of the `ColorPicker` component, just to make sure that removing `useControlledValue` was ok in this scenario

File: packages/components/src/color-picker/picker.tsx (hunk 4 above)
Comment (ciampo) [reply packages/components/src/color-picker/picker.tsx:18]: Ok, it looks like the only difference would be about the input string format — while the underlying `ColorPicker` would still be the same. I guess using a HSL picker made sense previously, when this component used HSL internally to represent color values — but with the current state of the component, this change should be fine :)

Thank you for explaining!

File: packages/components/src/color-picker/component.tsx (hunk 3 above)
Comment (sarayourfriend) [reply packages/components/src/color-picker/component.tsx:73]: The idea behind using `useControlledValue` was to allow the color picker to behave like a standard React input, that is, with or without a controlled external value.

```jsx
<ColorPicker onChange={setColor} />
```

Should work even though the `color` prop isn't being passed. Just like `<input onChange={setValue} />` works.

Comment (ciampo) [reply packages/components/src/color-picker/component.tsx:73]: This makes sense, thank you Sara!

@jorgefilipecosta , would it possible to add the `useControlledValue` hook back to the component?

Comment (ciampo) [reply packages/components/src/color-picker/component.tsx:73]: Hey @jorgefilipecosta , just wondering if you've had any time to work on this, or if you plan to anytime soon? Thank you!

File: packages/components/src/color-picker/component.tsx (hunk 2 above)
Comment (ciampo) [reply packages/components/src/color-picker/component.tsx:62]: Hey @jorgefilipecosta , have you had any time yet to work on a PR with this change ? Thank you!

File: packages/components/src/color-picker/component.tsx (hunk 3 above)
Comment (andrewserong) [reply packages/components/src/color-picker/component.tsx:73]: @ciampo and @jorgefilipecosta, I was investigating an issue with the color picker and gradients (reported in #36899) and it looks like re-instating `useControlledValue` and the `debounce` call resolves the issue, so I've opened up a PR in #36941 if either or you get the chance to take a look. I'm not very familiar with the `ColorPicker` component, so it can probably use some 👀 from folks who've worked with it before 🙂

Comment (ciampo) [reply packages/components/src/color-picker/component.tsx:73]: Thank you @andrewserong , I'll definitely have a look
