### PR TITLE
 Fix to  text color picker

### LINKED ISSUE #29848: From WordPress 5.7, the cursor of the custom color picker cannot be moved.
Thank you for your development.

## Description

1. Select "Text Color" from the toolbar when editing text.
2. Select "Custom Color".
3. Attempts to move the cursor in the color palette.
4. The cursor cannot be moved and the panel will be closed automatically.

## Screenshots

The following video shows the behavior in v.5.6.

And the following video shows the problematic behavior in v.5.7.

## WordPress information
- WordPress version: 5.7
- Gutenberg version: "Not installed"
- Are you using a default theme (e.g. Twenty Twenty-One)? "Yes"

## Device information
- Device: MacBook Pro
- Operating system: MacOS Catalina
- Browser:Chrome

### PR DESCRIPTION
**Pull request by Quintis1212**
Hello ) this is a fix to "From WordPress 5.7, the cursor of the custom color picker cannot be moved" #29848 issue

### CODE REVIEW

**Comment by Mamaduka** [comment]
Hello, @Quintis1212

I've tested this PR, and it works as expected.

I'm going to restart the checks as well. It looks like they've failed for unrelated reasons.

**Comment by Quintis1212** [comment]
Hello @Mamaduka ) Thank you for help ) can you  restart the checks once more )

**Comment by stokesman** [comment]
This should work given that it is effectively a revert of 98c9d38e79de4399ab0e2f4fdc3739b6904619d1. It will undo the fix for #27412 but that seems like a preferable trade-off because this regression #29848 seems more likely to be encountered. An actual `git revert` might have been nicer to provide historical context.

File: packages/format-library/src/text-color/index.js [hunk 1]
```diff
@@ -89,7 +89,6 @@ function TextColorEdit( {
 					value={ value }
 					onChange={ ( ...args ) => {
```
Comment (stokesman) [inline packages/format-library/src/text-color/index.js]: Just a clean-up suggestion, doesn't effect anything:
```suggestion
					onChange={ onChange }
```
And remove lines 91 and 92.

File: packages/format-library/src/text-color/index.js [hunk 2]
```diff
@@ -89,7 +89,6 @@ function TextColorEdit( {
...
 						onChange( ...args );
```
Comment (stokesman) [inline packages/format-library/src/text-color/index.js]:
```suggestion
```

File: packages/format-library/src/text-color/index.js [hunk 3]
```diff
@@ -89,7 +89,6 @@ function TextColorEdit( {
...
-						disableIsAddingColor();
 					} }
```
Comment (stokesman) [inline packages/format-library/src/text-color/index.js]:
```suggestion
```

**Comment by stokesman** [comment]
I've pushed an e2e test update 5065b6bc8057e2816d4e6b581d9cdeb340720519. The test would not complete as intended with this PR because an extra keypress needs to be included.

**Comment by Quintis1212** [comment]
@ stokesman  @Mamaduka  , it seems all tests are passed , PR can be merged ?

**Comment by Mamaduka** [comment]
Hi, @Quintis1212

Changes need to be approved by someone from the "Gutenberg Core" team.

**Comment by Quintis1212** [comment]
> Hi, @Quintis1212
> 
> Changes need to be approved by someone from the "Gutenberg Core" team.

Thank you for help )

**Comment by stokesman** [comment]
Since the linked issue was part of a project, I expected this would get reviewed by a core member. Now that the project has been closed and this seems like an important fix, I've requested such review.

**Review by stokesman — APPROVED** [review]
To sum this up it's a (manual) revert of 98c9d38e79de4399ab0e2f4fdc3739b6904619d1 with an e2e test update. The test had been [created](https://github.com/WordPress/gutenberg/pull/27967/files#diff-5bef1754793c62c38aca86d9acfc38f324614e4fa815b1080be1c4469a71ecf1R379) after that commit so required one more step in order to complete as intended (with the reversion of the commit in this PR).

**Review by ntsekouras — APPROVED** [review]
Thanks @Quintis1212 ! This is definitely better from the current behavior.

The root problem for [the original PR that introduced this](https://github.com/WordPress/gutenberg/pull/27596),  seems to be with some `ref` issue, I believe in `useAnchorRef`. The `ref` is not calculated properly since it searches for `span` where we haven't created yet. In my gif you can see that the `popover` is somewhere there but in the wrong position/z-index etc..

color

@ellatrix any thoughts about this?
