### PR TITLE
Unslash post content before parsing during save

### LINKED ISSUE #3426: Centered button identified as "modified externally"
## Issue Overview

A centered button is misreported as having been modified externally, offering an overwrite.

## Steps to Reproduce (for bugs)

1. Insert a button, add a label
2. Save
3. Center button, save
4. Reload

Now it identifies the button as modified externally, and if you click "overwrite", it will left align the button.

### PR DESCRIPTION
**Pull request by mcsf**
Fixes #3426

See #2806 for context on wpautop filter.

## Description

Per the comment in the fix, _WP_REST_Posts_Controller [slashes](https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L668) post data before inserting/updating a post. This data gets [unslashed](https://github.com/WordPress/WordPress/blob/4e320fe0087e8df83e6ba7f7765dbc7100c20067/wp-includes/post.php#L3359) by `wp_insert_post` right before saving to the DB. The PEG parser expects unslashed input in order to properly parse JSON attributes._

## How Has This Been Tested?

Try reproducing the parent issue.

## Types of changes

Bug fix.

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: lib/blocks.php [hunk 1]
```diff
@@ -220,6 +220,11 @@ function gutenberg_wpautop_block_content( $content ) {
  */
 function gutenberg_wpautop_insert_post_data( $data ) {
 	if ( ! empty( $data['post_content'] ) && gutenberg_content_has_blocks( $data['post_content'] ) ) {
+		// WP_REST_Posts_Controller slashes post data before inserting/updating
+		// a post. This data gets unslashed by `wp_insert_post` right before
+		// saving to the DB. The PEG parser needs unslashed input in order to
+		// properly parse JSON attributes.
```
Comment (youknowriad) [inline lib/blocks.php]: Does this mean we need to "slash" data back after our custom behavior?

Comment (mcsf) [reply lib/blocks.php]: Ah, yes, I left that line out. Amended. (Initially, not slashing back didn't break anything for me, but obviously any other piece consuming the hook should expect slashed data, as the signature for the hook states.)

File: lib/blocks.php [hunk 2]
```diff
@@ -220,7 +220,13 @@ function gutenberg_wpautop_block_content( $content ) {
...
+		$data['post_content'] = wp_unslash( $data['post_content'] );
 		$data['post_content'] = gutenberg_wpautop_block_content( $data['post_content'] );
+		$data['post_content'] = wp_slash( $data['post_content'] );
```
Comment (youknowriad) [inline lib/blocks.php]: Minor but It might be better to avoid storing any unslashed data in `$data[ 'post_content' ]` and use a temporary variable.

**Review by youknowriad — APPROVED** [review]
Confirmed this fixes the issue, Thanks 👍

File: lib/blocks.php [hunk 3]
```diff
@@ -220,7 +220,15 @@ function gutenberg_wpautop_block_content( $content ) {
  */
 function gutenberg_wpautop_insert_post_data( $data ) {
 	if ( ! empty( $data['post_content'] ) && gutenberg_content_has_blocks( $data['post_content'] ) ) {
-		$data['post_content'] = gutenberg_wpautop_block_content( $data['post_content'] );
+		// WP_REST_Posts_Controller slashes post data before inserting/updating
```
Comment (aduth) [inline lib/blocks.php]: We can expect this filter (`wp_insert_post_data `) will be called not in the context of a REST API save, but generally any save for post content. Do we need to account for this? Is it wasteful (or worse, breaking) for us to be unslashing in these other contexts?

Comment (mcsf) [reply lib/blocks.php]: Good questions.

Is it breaking? My reasoning:
- A [comment](https://github.com/WordPress/WordPress/blob/4e320fe0087e8df83e6ba7f7765dbc7100c20067/wp-includes/post.php#L3324-L3325) in `wp_insert_post()`, upon creating `$data` from a bunch of fields, reads _Expected slashed_, referring to said fields.
- At the end, `wp_insert_post()` blindly unslashes all of `$data`, with no prior check for certain kinds of formatting in `$data`, which I took as another sign that it _is_ expected that `wp_insert_post` be passed slashed data.
- It would be odd if saving via the REST API would silently differ in such a crucial aspect.
- Assuming that all other actors (incl. third parties) play well and provide slashed data, there shouldn't be anything breaking about this, as that would imply that `$x !== wp_slash( wp_unslash( $x ) )`.

Is it wasteful? Plausibly; we'd have to measure this. We could bypass this for non-REST-API contexts, but from my first paragraph it seems like the better default to leave it on.
