### PR TITLE
Revert "Honor the Disable Visual Editor setting (#12000)"

### LINKED ISSUE #12148: Blank page when editing custom post type
**Describe the bug**
CPT edit screen is no longer working. 
White screen (not of death). 
ACF is completely broken. 
You can no longer edit a field group.

**To Reproduce**
1. Install Gutenberg 4.5.
2. Install ACF (any version).
3. Navigate to the "Custom Fields > Add New" page .
4. Notice the lack of anything.

**Expected behavior**
ACF CPT should appear as expected with the classic editor edit page.

**Screenshots**
screen shot 2018-11-21 at 2 11 14 pm

**Additional context**
- This was not an issue with Gutenberg version 4.4

### PR DESCRIPTION
**Pull request by noisysocks**
Fixes https://github.com/WordPress/gutenberg/issues/12148 by reverting https://github.com/WordPress/gutenberg/pull/12000.

From https://github.com/WordPress/gutenberg/issues/12148#issuecomment-440522253:

> I suspect that #12000 was the wrong approach here: rather than falling back to classic when rich editing is disabled, we should still load the block editor, but default to the code editor view, or perhaps a HTML block.
>
> The fix for this should also include e2e tests confirming that CPTs that don't work in the block editor won't try to load it.

### CODE REVIEW

**Review by gziolo — APPROVED** [review]

**Comment by youknowriad** [comment]
I pushed a commit adding the RichText support in Gutenberg itself.

**Comment by gziolo** [comment]
Code in 97ffd1b looks good, I'm testing it.

**Review by gziolo — APPROVED** [review]
Gooood, let's :shipit:

File: packages/edit-post/src/components/text-editor/index.js [hunk 1]
```diff
@@ -3,23 +3,26 @@
...
-					onClick={ onExit }
-					icon="no-alt"
-					shortcut={ displayShortcut.secondary( 'm' ) }
-				>
-					{ __( 'Exit Code Editor' ) }
-				</IconButton>
-			</div>
+			{ isRichEditingEnabled && (
+				<div className="edit-post-text-editor__toolbar">
+					<h2>{ __( 'Editing Code' ) }</h2>
```
Comment (ocean90) [inline packages/edit-post/src/components/text-editor/index.js]: @youknowriad Should this headline maybe still be displayed (without the button)? See https://github.com/WordPress/gutenberg/issues/12182 for a related report.

Comment (youknowriad) [reply packages/edit-post/src/components/text-editor/index.js]: Sure no strong opinion.
