### PR TITLE
Legacy Widget: Don't display "No preview" when widget has image tags

### LINKED ISSUE #32523: Legacy widget preview iframe request is sometime cancelled by the browser
## Description
When we choose some options in our language legacy switcher legacy widget, its preview doesn't render anything because the preview iframe request is cancelled by the browser.

## Step-by-step reproduction instructions
1. Go to Appearance > Widgets
2. Open the browser developer toolbar on the network tab
3. Add only the language switcher legacy widget
4. Delete all the requests in the browser developer toolbar network tab
5. Check only the `Displays flags` option alone or `Hides languages with no translation`.
You can simply uncheck the `Displays language names` option which checks automatically the `Displays flags` option
6. See what happens on the `widgets.php?legacy-widget-preview....` request in the browser developer toolbar network tab
7. Click outside the language legacy widget to see what is previewed
8. See the legacy widget notice: `No preview available.`
9. Click right on the `widgets.php?legacy-widget-preview....` request in the browser developer toolbar network tab and choose `Open in new tab` on the contextual menu
10. See that the request return correctly the content result of the language switcher legacy widget

## Expected behaviour
Legacy widget preview have to be rendered regardless of the options choosen in the language switcher legacy widget.

## Actual behaviour
Preview doesn't work when:
- `Displays flags` option is checked alone
- `Hides languages with no translation` option is checked

## Screenshots
image

image

https://user-images.githubusercontent.com/1003778/121234293-d9843500-c893-11eb-8be5-e2b57360682f.mp4

## What's needed?
To reproduce the issue you need the Polylang plugin in its development version retrieved from our github repository master branch because this is, at the moment, the branch which is compatible with the new block-based widgets screen.

You can follow instructions from its [readme.md file](https://github.com/polylang/polylang#how-to-set-up-polylang) to install Polylang, make it ready and activate it on your WordPress environment.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: built from trunk because [this correction](https://github.com/WordPress/gutenberg/pull/32300) on legacy widget preview isn't reported in the latest v10.7.4
- Are all plugins except Gutenberg deactivated? No: Polylang dev branch is needed to be compatible with the block-based widgets screen and see the issue reported
- Are you using a default theme ? Yes: Twenty Twenty-One

Or

- WordPress version: ~~5.8-alpha-51081~~ 5.8-beta1-51132
- Gutenberg version: none installed
- Plugins: Polylang and WordPress Beta Tester
- Are you using a default theme ? Yes: Twenty Twenty-One

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome 91.0 or Firefox 89.0

### PR DESCRIPTION
**Pull request by noisysocks**
## Description

Fixes part of https://github.com/WordPress/gutenberg/issues/32523.

The Legacy Widget block displays a "No preview." message when it detects that the widget preview HTML has no text. This fails to account for a widget which consists entirely of ``s, though.

The fix is to recurse through a DOM built from the HTML and look for `IMG` tags. This is similar to `wp.dom.isEmpty()` except that, in this case, we consider an empty element with attributes to be empty.

## How has this been tested?

To reproduce the issue you need the Polylang plugin in its development version retrieved from our github repository master branch because this is, at the moment, the branch which is compatible with the new block-based widgets screen.

You can follow instructions from its readme.md file to install Polylang, make it ready and activate it on your WordPress environment.

1. Go to Appearance > Widgets
3. Add only the language switcher legacy widget
5. Check only the `Displays flags` option alone or `Hides languages with no translation`.
You can simply uncheck the `Displays language names` option which checks automatically the `Displays flags` option
7. Click outside the language legacy widget to see what is previewed
8. You should see some country flags

## Screenshots 

https://user-images.githubusercontent.com/612155/121618623-6f91a880-caaa-11eb-814c-0e41fe616ebe.mp4

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-library/src/legacy-widget/edit/control.js [hunk 1]
```diff
@@ -361,7 +361,24 @@ async function encodeWidget( { idBase, instance, number, formData = null } ) {
...
-	return element.innerText.trim() === '';
+	return isEmptyNode( element );
+}
+
+function isEmptyNode( node ) {
+	switch ( node.nodeType ) {
+		case node.TEXT_NODE:
+			return node.nodeValue.trim() === '';
+		case node.ELEMENT_NODE:
+			if ( node.tagName === 'IMG' ) {
```
Comment (talldan) [inline packages/block-library/src/legacy-widget/edit/control.js]: Will there be the same issue with other types of element (video, svg)?

**Comment by manooweb** [comment]
I tested with our case - `` tag - by patching my v10.8.0 branch and it works correctly now.

For the part of http request cancellation, I wonder if it isn't link to the fact that the content we want to insert in the iframe is empty. The browser consider there is nothing to do to update the iframe.

The other case I mentioned in the issue show us maybe we wrongly return an empty content and explain, I think, this cancellation.
We're working on it in our side and let you know if it definitively solve the problem.

File: packages/block-library/src/legacy-widget/edit/control.js (hunk 1 above)
Comment (noisysocks) [reply packages/block-library/src/legacy-widget/edit/control.js]: Yes good point. Fixed in c07e34d.

**Comment by noisysocks** [comment]
Thanks for testing @manooweb. This is ready for re-review.

File: packages/block-library/src/legacy-widget/edit/control.js (hunk 1 above)
Comment (talldan) [reply packages/block-library/src/legacy-widget/edit/control.js]: Cool. 👍

**Review by talldan — APPROVED** [review]
LGTM!

**Comment by manooweb** [comment]
FYI about http iframe request cancellation, I confirm it come from a empty content returned back by the widget. Then the browser considers there is nothing to do to update the iframe and then cancel the request.
For the other option in our widget, we fix the problem in our side.

Thanks a lot for the reactivity.

**Comment by manooweb** [comment]
@youknowriad you removed the `Backport to WP Beta/RC` PR label.
Does it mean you backported it  in the WP beta-2 realease ?

Edit: sorry I updated to WP 5.8 beta-2 and I have my answer. It works correctly 👍
