### PR TITLE
Fix blue line indicator not showing at the end

### LINKED ISSUE #25785: Block insertertion point blue line isn't visible when inserting at end of block list
**Describe the bug**
When inserting blocks using the main block library, usually a blue line displays where the block will be inserted.
Screenshot 2020-10-02 at 10 42 42 am

This blue line doesn't appear when a block is being inserted at the end of a list of blocks.
Screenshot 2020-10-02 at 10 41 51 am

Debugging:
It looks like this is because the `InsertionPoint` shows above the block it'll insert before:
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/block-list/insertion-point.js#L110

But not after the last block.

**To reproduce**
1. Add multiple paragraphs to a post
2. Select a block that's not the last block
3. Try inserting a block using the Add Block button in the header
4. Observe the blue line is displayed
5. Select the last block
6. Try inserting a block using the Add Block button in the header
7. Observe no blue line is shown

**Expected behavior**
The blue line appears consistently

### PR DESCRIPTION
**Pull request by kevin940726**
**This PR is based on #25727 to make sure e2e passes. It should be rebased to master once #25727 merged.**

## Description

Fix #25785, related to #25727. Also fixes https://github.com/WordPress/gutenberg/issues/25785#issuecomment-702659374.

Fix the blue line indicator is not showing at the end when using the global inserter to try to insert a block in a post or in a widget area.

This is more complicated than I thought, I couldn't think of any better way to do this, please feel free to give me some suggestions and guidance.

Internally, I use a `AppenderContext` to store a `Map` to keep the Appender's references. Then we can inject the blue line indicator alongside the appender, which usually lives at the end of the block list.

## How has this been tested?

Run the e2e test, or...

1. Go to Post editor, create a new post
2. Click the global inserter, hover over the Heading block
3. Observe the blue line indicator is showing at the end
4. Create some blocks, observe that (2) and (3) still works
5. Select any block in between
6. Click the global inserter, hover over the Heading block
7. Observe that the blue line indicator is showing in between blocks

The same steps can also be tested in the widget editor.

## Screenshots 

**Post editor**
Kapture 2020-10-06 at 11 17 15

**Widget editor**
Kapture 2020-10-06 at 11 18 32

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-editor/src/components/block-list-appender/index.js [hunk 1]
```diff
@@ -16,6 +17,9 @@ import { getDefaultBlockName } from '@wordpress/blocks';
 import DefaultBlockAppender from '../default-block-appender';
 import ButtonBlockAppender from '../button-block-appender';
 
+// A Context to store the map of the appender map.
+export const AppenderContext = createContext();
```
Comment (talldan) [inline packages/block-editor/src/components/block-list-appender/index.js:21]: This seems pretty similar to the way `BlockNodes` context works.

If we decide to go this way it could be worth making the code similar and also naming it `AppenderNodes` for consistency.

File: packages/block-editor/src/components/block-list/insertion-point.js [hunk 2]
```diff
@@ -94,13 +95,24 @@ function InsertionPointInserter( {
...
+	const appenderMap = useContext( AppenderContext );
+	const element = useMemo( () => {
+		if ( clientId ) {
+			return getBlockDOMNode( clientId );
+		}
+
+		// Can't find the element, might be at the end of the block list, or inside an empty block list.
+		// We instead try to find the "Appender" and place the indicator above it.
+		// `rootClientId` could be null or undefined when there's no parent block, we normalize it to an empty string.
+		return appenderMap.get( rootClientId || '' );
```
Comment (talldan) [inline packages/block-editor/src/components/block-list/insertion-point.js:114]: Thinking of some different approaches,`getBlockDOMNode` just does a `getElementById` call, could it be an option to do something similar for the appender using `querySelector`? e.g 
```js
document.querySelector( `#block-${ rootClientId } .block-list-appender` );
```

File: packages/block-editor/src/components/block-list-appender/index.js (hunk 1 above)
Comment (kevin940726) [reply packages/block-editor/src/components/block-list-appender/index.js:21]: Yeah, I have noticed that too! Renaming sounds good to me.

File: packages/block-editor/src/components/block-list/insertion-point.js (hunk 2 above)
Comment (kevin940726) [reply packages/block-editor/src/components/block-list/insertion-point.js:114]: That's actually my first attempt. However, I just don't feel like it's "react"ive enough as we'll be relying on the DOM structure and classnames.

File: packages/block-editor/src/components/block-list/insertion-point.js [hunk 3]
```diff
@@ -98,13 +99,24 @@ function InsertionPointInserter( {
...
+	const appenderNodesMap = useContext( AppenderNodesContext );
+	const element = useMemo( () => {
+		if ( clientId ) {
+			return getBlockDOMNode( clientId );
+		}
+
+		// Can't find the element, might be at the end of the block list, or inside an empty block list.
+		// We instead try to find the "Appender" and place the indicator above it.
+		// `rootClientId` could be null or undefined when there's no parent block, we normalize it to an empty string.
+		return appenderNodesMap.get( rootClientId || '' );
```
Comment (ellatrix) [inline packages/block-editor/src/components/block-list/insertion-point.js:118]: The insertion point is added at the root of the whole tree of blocks, so I think `rootClientId` will always be `''`, never an id?

Comment (ellatrix) [reply packages/block-editor/src/components/block-list/insertion-point.js:118]: In other words, does the indicator work for nested appenders?

File: packages/block-editor/src/components/block-list/insertion-point.js (hunk 2 above)
Comment (ellatrix) [reply packages/block-editor/src/components/block-list/insertion-point.js]: I think we should go for the simpler solution. We're doing the same for block nodes, and this should be revised together if we'd like to avoid querying the DOM.

File: packages/block-editor/src/components/block-list/insertion-point.js (hunk 3 above)
Comment (kevin940726) [reply packages/block-editor/src/components/block-list/insertion-point.js:118]: It could be an id if it's in the Widget Editor though, `widget-area` is kind of like a special case for this 😜.

Also, `<InsertionPoint>` only handles _getting_ of the appender nodes. `<BlockList>` is where _setting_ happens, which can be in `<InnerBlocks>` or `widget-area`. What I'm trying to say here is that a `<InsertionPoint>` could have multiple `<BlockList>` hence could also have multiple `<BlockListAppender>`.

**Comment by paaljoachim** [comment]
From what I am seeing in the Post Editor. Creating a new post, adding a heading and adding a paragraph block. Having the second to last block active when clicking the Inserter and hovering over a block will show a line below the second to last block. IF I have the last block active no blue line will be seen below that. 

The second to last block is selected. So one sees the blue line below.
Screen Shot 2020-10-06 at 11 48 06

The last block is selected. One can not see the blue line below the text.
Screen Shot 2020-10-06 at 11 48 36


--------

Widget screen.

Current 9.1. Which has the blue line error.
Screen Shot 2020-10-06 at 11 52 49

This PR.
I added a Heading block then clicked the Inserter and hovered over a block.
(For whatever reason Line Height control in Heading is not seen in this PR but is seen in 9.1)
Screen Shot 2020-10-06 at 11 54 50


Another test. Having Footer 2 open. Closing footer 1.
Screen Shot 2020-10-06 at 11 57 44

From what I see the blue line only shows up if the first widget area is open. Closing the first widget area and having in this example Footer 2 open will not show a blue line in the top of footer 2.

**Comment by kevin940726** [comment]
@paaljoachim I can't seem to reproduce those 🙀, see my screenshots/GIFs in the PR description above.

> Closing the first widget area and having in this example Footer 2 open will not show a blue line in the top of footer 2.

The blue line should be at the bottom of the footer 2 though. See #25708 for more info. It's likely that the blue line is at the bottom of the widgets and since the viewport doesn't auto-scroll to it it's not visible.

File: packages/block-editor/src/components/block-list/insertion-point.js (hunk 3 above)
Comment (kevin940726) [reply packages/block-editor/src/components/block-list/insertion-point.js:118]: > In other words, does the indicator work for nested appenders?

It should, at least for my testing below.

image

File: packages/block-editor/src/components/block-list/insertion-point.js (hunk 2 above)
Comment (kevin940726) [reply packages/block-editor/src/components/block-list/insertion-point.js]: It's not as _simple_ as just a `querySelector` call though. Since `clientId` could be `null`, also could `rootClientId`. We have to add some more code to be able to select the parent of the appender.

**Comment by paaljoachim** [comment]
@kevin940726 Kevin
Then it is on my end as I am lately getting npm run build errors. Making it very difficult for me to test PR's. As some seems to work while others not.

**Review by draganescu — APPROVED** [review]
In my testing this behaved as expected.

**Comment by draganescu** [comment]
@ellatrix I got a bit trigger happy :) if you have objections to merging this we can revert!

**Comment by ellatrix** [comment]
It's ok, we can adjust it later.
