### PR TITLE
[Block Library - Query Loop]: Fix broken preview in specific category template

### LINKED ISSUE #44156: Post Template block errors after creating a template for a specific category
To reproduce:

1. Have a functioning Archive template
2. Have a category that contains some posts
3. From the Templates list in the Site Editor click Add New -> Category
4. Choose a specific category
5. Observe the following result:

Screenshot 2022-09-14 at 14 53 51

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/44156

In a specific category template in site editor if we have a Query Loop which inherits the global query (`inherit:true`), we try to show a better preview by extracting the current template's category(introduced [here](https://github.com/WordPress/gutenberg/pull/43699)). Currently this can cause an infinite loop and break the block.

Screenshot 2022-09-14 at 14 53 51

## Testing Instructions
1. Create a specific category template in site editor and add a Query Loop which inherits the global query (`inherit:true`)
5. Observe that the preview is. correct and the blocks doesn't break

### CODE REVIEW

File: packages/block-library/src/post-template/edit.js [hunk 1]
```diff
@@ -123,12 +110,22 @@ export default function PostTemplateEdit( {
...
+					slug: templateSlug.replace( 'category-', '' ),
+				} );
 			const query = {
 				offset: perPage ? perPage * ( page - 1 ) + offset : 0,
 				order,
 				orderby: orderBy,
 			};
-			if ( taxQuery ) {
+			// There is no need to build the taxQuery if we inherit.
+			if ( taxQuery && ! inherit ) {
```
Comment (Mamaduka) [inline packages/block-library/src/post-template/edit.js:128]: It is a general improvement and not related to this issue. Am I correct?

File: packages/block-library/src/post-template/edit.js [hunk 2]
```diff
@@ -123,12 +110,22 @@ export default function PostTemplateEdit( {
 				per_page: -1,
 				context: 'view',
 			} );
+			const templateCategory =
+				inherit &&
+				templateSlug?.startsWith( 'category-' ) &&
+				getEntityRecords( 'taxonomy', 'category', {
+					context: 'view',
+					per_page: 1,
```
Comment (Mamaduka) [inline packages/block-library/src/post-template/edit.js:118]: Nice 🚀

**Review by Mamaduka — APPROVED** [review]
I can reproduce the issue on the trunk, and it's fixed on this branch.

I also like that query is now run conditionally. That's one less request for non-category templates 🎉

File: packages/block-library/src/post-template/edit.js (hunk 1 above)
Comment (ntsekouras) [reply packages/block-library/src/post-template/edit.js:128]: You're correct, it become more obvious to me after checking this issue. We could probably skip some other args if we `inherit`, like `search` etc..

Comment (Mamaduka) [reply packages/block-library/src/post-template/edit.js:128]: Makes sense.

**Review by oandregal — APPROVED** [review]
Works nicely, thanks for the fix.

**Comment by ockham** [comment]
I just cherry-picked this PR to the wp/6.1 branch to get it included in the next release: e1786b9cb8
