### PR TITLE
Fix: text color dropdown not showing up after clicking for the first time

### LINKED ISSUE #27412: Text color toolbar button doesn't open color picker
**Describe the bug**
Color toolbar behaves strangely when used without a text range selected. It seems to work fine when a text range is selected.

**To reproduce**
1. Select a text color from the paragraph toolbar _without_ a text range selected.
2. Click on the text color button that appears.
3. See that the color dropdown doesn't open.
4. Continue typing to see that the dropdown only opens then.

**Expected behavior**
Color dropdown should open on button press.

**Screenshots**
text-color-bug

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? plugin
- If the Gutenberg plugin is installed, which version is it? master (fbb000fcb4)

### PR DESCRIPTION
**Pull request by rafaelgallani**
## Description
Just a bugfix that will probably fix #27412. Not sure if this is the right behavior though.

## How has this been tested?
Just running `npm run test` and making sure it wouldn't break.

## Screenshots 
ezgif com-gif-maker

## Types of changes
Bugfix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/format-library/src/text-color/index.js [hunk 1]
```diff
@@ -87,7 +87,10 @@ function TextColorEdit( {
 					onClose={ disableIsAddingColor }
 					activeAttributes={ activeAttributes }
 					value={ value }
-					onChange={ onChange }
+					onChange={ () => {
+						onChange( ...arguments );
+						disableIsAddingColor();
+					} }
```
Comment (ajlende) [inline packages/format-library/src/text-color/index.js:93]: The `arguments` object isn't available in arrow functions, so what you're passing here is actually the props. Use [rest parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters) instead.

```suggestion
					onChange={ ( ...args ) => {
						onChange( ...args );
						disableIsAddingColor();
					} }
```

**Review by ajlende — CHANGES_REQUESTED** [review]

File: packages/format-library/src/text-color/index.js (hunk 1 above)
Comment (rafaelgalani) [reply packages/format-library/src/text-color/index.js:93]: To be honest, I tested locally as: 
```javascript
onChange={ ( e ) => { 
    onChange( e ); 
    disableIsAddingColor();
} }
```
And later changed to `...arguments` 😅

Comment (rafaelgalani) [reply packages/format-library/src/text-color/index.js:93]: I didn't know it wasn't available in arrow functions. Or I forgot it... 😅 
Also, I tested it with `...arguments`, and it looked like it worked... But I just tested again, and it's not. 
Probably forgot to build or something, since I wasn't running `npm run dev`...

Anyway, thanks. I'll correct it right away.

**Comment by rafaelgalani** [comment]
For the failing E2E test:



I believe that the proposed changes are not responsible for it...

**Comment by rafaelgalani** [comment]
@ajlende Does it look alright now? Also, I believe that it would be better if you could test it locally since I'm not entirely sure if that was the intended behavior. 😅

**Review by ajlende — APPROVED** [review]
It's working as I expect 👍

**Comment by stokesman** [comment]
Looks like this caused #29848. I think the change here may be reverted soon (in #30039).  Heads up to @ajlende or @rafaelgalani in case you'd like to figure out an alternate fix for #27412.

**Comment by rafaelgallani** [comment]
@stokesman Hello! I haven't noticed this issue... Sorry about it. I can work on the alternate fix right away. Should we reopen the issue?

**Comment by rafaelgallani** [comment]
I'll reopen #27412 as soon as #30039 is merged. Concurrently, I'll work on an alternate fix for it.
