### PR TITLE
Fix: Remove parent block selector while in Write mode

### LINKED ISSUE #65577: Remove parent selector when Edit mode is active
When Edit mode is active, you can select the parent block and nested inner blocks that are expressed as content. 

That's great, but I question if the parent selector on the block toolbar is necessary in this mode, as it's much easier to select the parent now that each pattern is "flattened". 

CleanShot 2024-09-23 at 13 00 56

### LINKED ISSUE #66684: Remove parent block selector while in Write mode
### Brief 

The current implementation of the parent block selector in [Write mode](#60021 ) disrupts the editing paradigm, as selecting the parent block leads to editing design-level (the parent `<main>` group block in a template or the post/content block otherwise. 

Write mode is designed to simplify content input and prioritize content-focused interactions, but editing the top-most parent block while in this mode breaks this intended separation between writing and design.

Additionally, the parent block selector becomes less useful in Write mode for patterns. Write mode already flattens patterns, allowing easier selection and interaction, making the parent block selector nearly redundant in this context.

### Steps to Reproduce

1. Enter Write mode.
2. Select text in a pattern. 
3. Select the parent block selector to select the current pattern. 
4. Select the parent block selector again to select the block surrounding all patterns. 
5. Now you're at the top-level container group, or the post/content block—no longer editing content. 

### Expected Behavior

In Write mode, the focus remains on writing and direct interaction with patterns and their content blocks only.

### Actual Behavior

Selecting a top-most parent block shifts the interaction toward design-oriented edits, misaligning with the Write mode’s purpose.

### Visual 

Note how using the parent block selector gets you to the Post Content block, which is not within the Write mode conditions, allowing design tooling while in Write mode. Also note how selecting the pattern in Write mode is as effective—if not more—than using the parent block selector. 

https://github.com/user-attachments/assets/75850edd-a8b1-4770-8389-69e21293b273

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Fixes: https://github.com/WordPress/gutenberg/issues/66684
Fixes: https://github.com/WordPress/gutenberg/issues/65577

Removes the parent selector while in write mode.
cc: @richtabor 

## Testing Instructions
Enable the write mode under experiments.
Change the post to write mode.
Add a pattern e.g: a call to action.
Select a paragraph block and verify the parent selector is not available.

### CODE REVIEW

**Comment by Mamaduka** [comment]
@jorgefilipecosta, #65577 seems something that can be implemented here as well

**Comment by jorgefilipecosta** [comment]
> @jorgefilipecosta, #65577 seems something that can be implemented here as well

Hi @Mamaduka, I think this PR also fixes #65577, if a pattern is content-locked now we don't render the parent selector when inside that parent.

**Comment by jorgefilipecosta** [comment]
@Mamaduka would you be able to review this PR 😊?

**Comment by Mamaduka** [comment]
@jorgefilipecosta, it's on my list, and I will do a proper review first thing tomorrow morning.

File: packages/block-editor/src/components/block-parent-selector/index.js [hunk 1]
```diff
@@ -44,6 +44,8 @@ export default function BlockParentSelector() {
 			isVisible:
 				_parentClientId &&
 				getBlockEditingMode( _parentClientId ) !== 'disabled' &&
+				getBlockEditingMode( selectedBlockClientId ) !==
+					'contentOnly' &&
```
Comment (Mamaduka) [inline packages/block-editor/src/components/block-parent-selector/index.js]: I think we should add this condition to the `PrivateBlockToolbar` component. It already has the same logic, and we're just duplicating it here. That will also void adding the `has-parent` class to the toolbar and fix its position.


https://github.com/WordPress/gutenberg/blob/ce00a5ff22c775b04aa5521687719f689996f45c/packages/block-editor/src/components/block-toolbar/index.js#L134-L143

Also, we can remove the `isVisible` logic from this component since the check already happens parent.

## Screenshot
CleanShot 2024-12-04 at 22 02 12

Comment (jorgefilipecosta) [reply packages/block-editor/src/components/block-parent-selector/index.js]: Thank you @Mamaduka good point, your feedback was applied.

File: packages/block-editor/src/components/block-toolbar/index.js [hunk 2]
```diff
@@ -137,6 +137,8 @@ export function PrivateBlockToolbar( {
 				! _isZoomOut &&
 				parentBlockType &&
 				getBlockEditingMode( parentClientId ) !== 'disabled' &&
+				getBlockEditingMode( selectedBlockClientId ) !==
+					'contentOnly' &&
```
Comment (Mamaduka) [inline packages/block-editor/src/components/block-toolbar/index.js]: Nit (non-blocking): the block editing mode for the selected one is already available here. See the `editingMode` variable above.

Comment (Mamaduka) [reply packages/block-editor/src/components/block-toolbar/index.js]: Updated in [8a0be0e](https://github.com/WordPress/gutenberg/pull/67395/commits/8a0be0e77298698fb2ac4c68c44a3b96ffec5cea).

**Review by Mamaduka — APPROVED** [review]
