### PR TITLE
Fix incorrect targeting of block wrappers for root padding in the edi…

### LINKED ISSUE #46724: Root padding is missing for nested row block in the editor
### Description

The root padding is missing for a nested row block in the post and the site editor, and the content bumps on the edge of the screen.

**Test markup**
```
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50"}}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"space-between"}} -->
<div class="wp-block-group alignfull" style="padding-top:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50)"><!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:paragraph -->
<p>Localhost</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Just another WordPress site</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"align":"right"} -->
<p class="has-text-align-right">Designed with WordPress</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```
I expected the nested row block on the left to have the root padding, just like the paragraph block on the right. However, the padding is missing at the moment therefore, the content bumps on the edge of the screen.

Screenshot 2022-12-21 at 23 10 40

This happens in the post and the site editor. The root padding was added correctly on the front of the site.

Screenshot 2022-12-21 at 23 12 13

### Step-by-step reproduction instructions

1. Go to the post editor
2. Paste the test content
3. See the missing paddings for the nested row block on the left
4. Publish the page and see the front of the site.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WP: 6.1.1
Gutenberg: trunk
Tested in TT3, but this is not a theme-specific issue, as I can reproduce it with other themes.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

Fixes #46724

## Why?

In the editor, blocks are given classnames such as `wp-block`, `block-editor-block-list__block` and `block-editor-block-list__layout`, that aren't carried through to the front end. Because of this, the rules added by `useRootPaddingAwareAlignments` have to be slightly different for editor and front end. 

Problem: in the front end, there is no generic class applied to all block wrappers, such as `wp-block`, so outer block wrappers had to be targeted with `[class*="wp-block-"]:not([class*="__"])` (where the `not` part rules out any inner wrapper with a classname starting with `wp-block` such as `wp-block-cover__inner-container`). This creates a problem in the editor, because all block wrappers have a classname with a double underscore such as `block-editor-block-list__block`.
But because the `wp-block` class is also applied to all block wrappers in the editor, we can target that instead.

## Testing Instructions

1. Insert the test markup from #46724 at the root level of a site, using a theme that sets `"useRootPaddingAwareAlignments": true` in its theme.json e.g. Twenty Twenty Three.
2. Check that root padding displays correctly on the test markup, and looks the same in both editor and front end.
3. Check that nothing has changed on the original template markup and editor still matches front end.

### CODE REVIEW

**Review by andrewserong — COMMENTED** [review]
Oh, what a challenging problem! I like the direction of the fix, but a challenge is that the JS version of the global styles output only exists in the site editor and not the post editor. Within the post editor, the PHP version of the global styles rules is output in that context instead, so the fix doesn't appear to be present there:

Site editor:

image

Post editor:

image

Unfortunately I can't quite think of a universal way we could fix the site-frontend-facing rule so that it'd also work in the post editor 🤔

**Comment by tellthemachines** [comment]
> Within the post editor, the PHP version of the global styles rules is output in that context instead

Maybe we could switch to using the JS version in the post editor instead? 

Or we could implement #6639 😂 

Or we could remove `wp-block` from all inner containers - which would be a breaking change for themes that have styled those classes - or we could change `block-editor-block-list__block` and `block-editor-block-list__layout` to not use underscores, which _shouldn't_ cause any external problems. 

Any of these solutions seems like overkill for such a small bug though. I'll try fiddling with the PHP selectors a bit more.

**Comment by tellthemachines** [comment]
I think that's fixed it. It should be fine to add the `.wp-block` selector as it won't target anything in the front end 🤔 

`.has-global-padding > .alignfull:where(:not(.has-global-padding)) > :where([class*="wp-block-"]:not(.alignfull):not([class*="__"]),.wp-block:not(.alignfull),p,h1,h2,h3,h4,h5,h6,ul,ol)` is one ugly selector and everytime we touch it it gets worse 😅

File: packages/block-editor/src/components/global-styles/use-global-styles-output.js [hunk 1]
```diff
@@ -669,8 +669,8 @@ export const toStyles = (
...
 			.has-global-padding :where(.has-global-padding) > .alignfull { margin-right: 0; margin-left: 0; }
-			.has-global-padding > .alignfull:where(:not(.has-global-padding)) > :where([class*="wp-block-"]:not(.alignfull):not([class*="__"]),p,h1,h2,h3,h4,h5,h6,ul,ol) { padding-right: var(--wp--style--root--padding-right); padding-left: var(--wp--style--root--padding-left); }
-			.has-global-padding :where(.has-global-padding) > .alignfull:where(:not(.has-global-padding)) > :where([class*="wp-block-"]:not(.alignfull):not([class*="__"]),p,h1,h2,h3,h4,h5,h6,ul,ol) { padding-right: 0; padding-left: 0;`;
+			.has-global-padding > .alignfull:where(:not(.has-global-padding)) > :where(.wp-block:not(.alignfull),p,h1,h2,h3,h4,h5,h6,ul,ol) { padding-right: var(--wp--style--root--padding-right); padding-left: var(--wp--style--root--padding-left); }
+			.has-global-padding :where(.has-global-padding) > .alignfull:where(:not(.has-global-padding)) > :where(.wp-block:not(.alignfull),p,h1,h2,h3,h4,h5,h6,ul,ol) { padding-right: 0; padding-left: 0;`;
```
Comment (andrewserong) [inline packages/block-editor/src/components/global-styles/use-global-styles-output.js:677]: Small nit: now that the PHP rules use `.wp-block` would it be worth copying the PHP rules over to the JS code here? These JS rules work perfectly fine, but I was wondering if it's worth it for the two sets of rules to be identical, so that anyone in the future looking at these rules doesn't wonder why they're different. Alternately, we could add a code comment explaining why they differ?

**Review by andrewserong — APPROVED** [review]
Nice one, that's done the trick @tellthemachines! The rules are applying consistently for me now in both the post and site editors, and on the site frontend 👍

Just left a tiny nit about whether we should ensure the rules are the same between the PHP and JS implementations, but otherwise this LGTM! ✨

File: packages/block-editor/src/components/global-styles/use-global-styles-output.js (hunk 1 above)
Comment (tellthemachines) [reply packages/block-editor/src/components/global-styles/use-global-styles-output.js:677]: I think I'd prefer to add a comment explaining the logic; it feels weird to add a useless selector just for the sake of making the rules identical. It's not impossible that they will diverge further in the future if more bugs are found 😅

Comment (andrewserong) [reply packages/block-editor/src/components/global-styles/use-global-styles-output.js:677]: Sounds good, an explanatory comment is a reasonable way to go about it. LGTM!

**Comment by iamtakashi** [comment]
Awesome, thank you, @tellthemachines!

**Comment by oandregal** [comment]
While comparing theme.json classes in Gutenberg and WordPress core I've noticed this PR was missing in core. I understand we want to backport this, so I'm tagging it as such. 

cc @ntsekouras @Mamaduka 

(I see this PR requires a release of the JS packages. I don't know how we want to manage that, otherwise, I'd prepare the backport myself for timezones to play to our advantage).

**Comment by Mamaduka** [comment]
@oandregal, as the development diverges, the class won't always match in core and plugin. If the bug was introduced in WP 6.2, then we should be good to land a fix in RC1.

**Comment by oandregal** [comment]
> as the development diverges, the class won't always match in core and plugin. If the bug was introduced in WP 6.2, then we should be good to land a fix in RC1.

Absolutely. If something is slated to 6.3, it's fine they are different.

I don't know whether this is for 6.2 or 6.3, though, hence why I raised :) We missed [important backports](https://github.com/WordPress/gutenberg/pull/46579) in the 6.1 cycle, and I don't want us to repeat the same mistake in 6.2.

As a general note, until we can find a better (automated) mechanism, we should aim for the theme.json classes in Gutenberg and core to be the same (other than minor things such as `gutenberg_` vs `wp_` prefixes). If we don't do this little mowing, so to speak, the backport process will become untenable at some point for the next editor tech leads.

**Comment by tellthemachines** [comment]
This bug wasn't introduced in 6.2; it's been there since the root padding logic was built. As we were already in Beta at the point this was merged, I didn't bother adding the backport label. Though if folks feel it's important to fix for this release anyway, I'm happy to do a backport PR for the PHP changes!
