### PR TITLE
State: Merge multi selection and selection reducer into a unique blockSelection reducer

### LINKED ISSUE #2122: Able to select multiple blocks and edit a block at the same time in Chrome 59
## Issue Overview

With a very specific sequence of mouse movements and selections, it's possible to have the cursor active in a block, and have multiple blocks selected, resulting in unexpected behaviour.

## Steps to Reproduce (for bugs)

Using Chrome 59 (exact version, 59.0.3071.109)

1) Create three text blocks, with the text "top", "middle", and "bottom".
2) In the bottom block, place the text cursor at the end of the word "bottom".
3) Drag to the beginning of the word "bottom" to select it.
4) Release the mouse button.
5) Move the mouse cursor to the end of the word "bottom".
6) Drag straight upward to select all three blocks.
7) Drag the mouse cursor to the beginning of the word "top" in the top block.
8) Drag the mouse cursor straight down to the bottom block so it is at the beginning of the word "bottom". 
 You should see the word "bottom" is no longer selected, and the text cursor is at the start of the word "bottom".
9) Continue dragging upward to select all three blocks. You should see the text cursor is still active in the bottom block, but all three blocks are selected.
10) Press backspace, and the bottom block will merge into the block above it and lose focus.

weird selection bug

## Expected Behavior

I shouldn't be able to edit a block while having multiple blocks selected

## Current Behavior

But, in Chrome 59, I can. (But not in 60, or Firefox)

## Todos
- [ ] Tests

### PR DESCRIPTION
**Pull request by youknowriad**
This prevents issues where we could have multi-selection and a block selection at the same time

closes #2122

### CODE REVIEW

**Comment by notnownikki** [comment]
This fixes the issue, but introduces a flicker between block focus and multi selection focus, again only in chrome 59, not in FF or chrome 60.

So, same reproduction steps as in the original bug, and once it's triggers and you drag the cursor around, you can see the state flicker between block focus and multi block selection in a headache inducing way.

flicker

**Comment by notnownikki** [comment]
And I just noticed, there's a moment when two blocks have the tools and delete menu buttons showing as well.

File: editor/state.js [hunk 1]
```diff
@@ -366,17 +309,15 @@ export function isTyping( state = false, action ) {
...
 /**
- * Reducer returning multi selected block state.
+ * Reducer returning the block selection's state.
  *
  * @param  {Object} state  Current state
  * @param  {Object} action Dispatched action
  * @return {Object}        Updated state
  */
-export function multiSelectedBlocks( state = { start: null, end: null }, action ) {
+export function blockSelection( state = { start: null, end: null }, action ) {
```
Comment (iseulde) [inline editor/state.js]: Would it be good practice to describe the full initial state here?

Comment (youknowriad) [inline editor/state.js]: Not sure I understand the note. Do you mean adding a comment to explain the initial state?

**Comment by iseulde** [comment]
To me this sounds good as long as it doesn't introduce any new issues. I cannot find any additional issues.

File: editor/state.js (hunk 1 above)
Comment (iseulde) [inline editor/state.js]: I mean, should there also be `focus: {}`?

Comment (youknowriad) [inline editor/state.js]: Oh!! it's not mandatory, the `focus` prop is only needed if a block is selected.

Comment (iseulde) [inline editor/state.js]: Yeah, so then it's `null`? Just thought it might be nice to define all possible keys the state can have.

Comment (youknowriad) [inline editor/state.js]: Fair enough, updating

**Comment by youknowriad** [comment]
I'm going to merge this, it slightly improves the selection behaviour in chrome 59. Not sure where the flickering comes from
