### PR TITLE
Navigation Link: Improve performance by only requesting entities when selected

### LINKED ISSUE #42904: Large navigation menus load slowly and exhaust server resources
### Description

Our website has a menu with several submenus linking 30-40 pages in all. Loading the full site editor triggers API requests for ALL the pages. This is quite slow and results in multiple HTTP 508 Resource Limit Is Reached. Requests are CPU-limited on the server and our shared hosting environment limits pending requests to 20. This is ample server resources for everything we need except loading the site editor.

The cause seems to be this feature which decorates items if they point at invalid pages. Each page in the menu gets loaded.
https://github.com/WordPress/gutenberg/pull/31716/files

The HTTP 508 responses typically come from page requests with this stack trace:
useSelect @ data.js
useIsInvalidLink @ block-library.js
NavigationLinkEdit @ block-library.js

I would suggest that loading each page in a menu doesn't scale well. I don't know enough to suggest a path forward, but batching requests or at least limiting their concurrency would solve this.

### Step-by-step reproduction instructions

1. Create a template containing a menu with multiple page links
2. Open the template in the full site editor.
3. Note network requests to each referenced page, e.g. wp-json/wp/v2/pages/##?context=edit&_locale=user

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WordPress 6.0.1
Chrome 103.0.5060.134
Windows 10.0.19043 Build 19043
Theme twentytwentytwo Version 1.2
Server Linux 3.10.0-962.3.2.lve1.5.38.el7.x86_64 x86_64
Web server Apache
PHP 7.4.30

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes #42904.
Related #69627.

PR improves Navigation Link block performance when loading editors and avoids preemptively requesting item status metadata.

This approach is similar to #17504.

## Why?
See: #42904 and #69563.

## Testing Instructions
1. Create a Navigation menu with multiple links to page items.
2. Add it to the default header template part.
3. Refresh that template part in the Site Editor.
4. Inspect the network requests.
5. Confirm there are no HTTP requests made for each page item.
6. Select the parent Navigation block or individual link item.
7. Confirm that status metadata is fetched.

### Testing Instructions for Keyboard
Same.

## Screenshots or screencast 

| Before | After |
|--------|--------|
| CleanShot 2025-03-19 at 14 10 27 | CleanShot 2025-03-19 at 14 09 59 |

### CODE REVIEW

File: packages/block-library/src/navigation-link/edit.js [hunk 1]
```diff
@@ -111,14 +111,14 @@ const useIsInvalidLink = ( kind, type, id ) => {
 			// Fetching the posts status is an "expensive" operation. Especially for sites with large navigations.
 			// When the block is rendered in a template or other disabled contexts we can skip this check in order
 			// to avoid all these additional requests that don't really add any value in that mode.
-			if ( blockEditingMode === 'disabled' ) {
+			if ( blockEditingMode === 'disabled' || ! enabled ) {
```
Comment (Mamaduka) [inline packages/block-library/src/navigation-link/edit.js:118]: Left `blockEditingMode` check. This handles cases when the Navigation block can be selected, but its children have editing disabled.

**Review by fabiankaegy — COMMENTED** [review]
@Mamaduka This is a nice improvement :) I think we need to fine tune it a little bit more though 🤔 

In testing this I find it odd that the "invalid" indicator disappears when I have another child of the navigation block selected... 

I would kind of like to check if the navigation block is selected or if it has a selection within any of it's child blocks (deeply nested) 🤔 

https://github.com/user-attachments/assets/f634df2c-3e08-4440-961a-b3ab19f70245

**Comment by Mamaduka** [comment]
@fabiankaegy, I updated the checks, and they should be working better. Note: The validation info will disappear when the selection moves out of the navigation block.

**Comment by t-hamano** [comment]
thanks for the PR!

> Note: The validation info will disappear when the selection moves out of the navigation block.

To solve the performance problem, we need to tolerate this behavior, right?

**Comment by Mamaduka** [comment]
> To solve the performance problem, we need to tolerate this behavior, right?

Yes, it's a trade-off, but minor, in my opinion.

**Review by t-hamano — APPROVED** [review]
If we can't solve both problems, I prefer to prioritize improving performance 👍

**Review by fabiankaegy — APPROVED** [review]
This works well now :) Thank you!

**Comment by fabiankaegy** [comment]
@Mamaduka I think this one might be worth flagging for a point release.

**Comment by t-hamano** [comment]
I am checking the PRs with the "Backport to WP Minor Release" label applied to clarify which PRs should be backported to [the WordPress 6.8.2 release](https://make.wordpress.org/core/2025/06/17/wordpress-6-8-2-release-schedule/).

This PR does not fix the issues that first appeared in 6.8, but is just a performance improvement and may be a candidate for a minor release.

However, note that there is a slight visual change:

> The validation info will disappear when the selection moves out of the navigation block.

**Comment by Mamaduka** [comment]
I think similar performance fixes are okay to backport into a minor release, especially now that there won't be another major release until next year. This is similar to #69627.

**Comment by t-hamano** [comment]
This PR was cherry-picked into the `wp/6.8` branch for the WP 6.8.2 release: #70557
