### PR TITLE
Fix: use `viewportWidth` in pattern preview data view

### LINKED ISSUE #60314: Pattern Preview in Site Editor Pattern Manager does not respect viewportWidth defined in Patterns
One of the metadata headers that can be defined in Patterns is `viewportWidth`. It is used to configure the width of the `BlockPreview` component. 

Currently all patterns regardless of what `viewportWidth` they have defined render with a width of `1200px` which is the default value.

You can see the missing prop here: 

https://github.com/WordPress/gutenberg/blob/2f88a192d83f4966cc8d0ebf725baf04fb565f10/packages/edit-site/src/components/page-patterns/index.js#L174

The `BlockPreview` component accepts the `viewportWidth` as you can see here: https://github.com/WordPress/gutenberg/blob/2f88a192d83f4966cc8d0ebf725baf04fb565f10/packages/block-editor/src/components/block-preview/index.js#L27

### PR DESCRIPTION
**Pull request by fabiankaegy**
## What?

Closing #60314 

## Why?

In order to respect the patterns defined `viewportWidth`

## How?

Passing the `viewportWidth` setting of the pattern into the `BlockPreview` component

## Testing Instructions

1. Register a custom pattern in code and add a custom `viewportWidth` to the metadata header
2. Navigate to the pattern data view and see that the preview uses the correct viewport width.

### CODE REVIEW

File: packages/edit-site/src/components/page-patterns/index.js [hunk 1]
```diff
@@ -171,7 +171,12 @@ function Preview( { item, categoryId, viewType } ) {
 				>
 					{ isEmpty && isTemplatePart && __( 'Empty template part' ) }
 					{ isEmpty && ! isTemplatePart && __( 'Empty pattern' ) }
-					{ ! isEmpty && <BlockPreview blocks={ item.blocks } /> }
+					{ ! isEmpty && (
+						<BlockPreview
+							blocks={ item.blocks }
+							viewportWidth={ item?.viewportWidth }
```
Comment (ntsekouras) [inline packages/edit-site/src/components/page-patterns/index.js]:
```suggestion
							viewportWidth={ item.viewportWidth }
```

**Review by ntsekouras — APPROVED** [review]
Looks good, thanks!
