### PR TITLE
Distraction Free Mode: Don't show the metaboxes

### LINKED ISSUE #48909: Distraction free mode does not hide the Custom Fields panel
### Description

When switching to the new distraction-free mode in WordPress 6.2, if the user has enabled the Custom Fields panel, the panel is not hidden when the distraction-free mode is enabled.

To reproduce, enable the Custom Fields panel in the Editor preferences, and then enable Distraction-free mode.

Tested on WordPress 6.2-beta5. 

### Step-by-step reproduction instructions

1. Create a new post or page
2. Enable the Custom Fields panel for the block editor
3. Enable Distraction free mode

### Screenshots, screen recording, code snippet

custom-fields-enabled-scaled

### Environment info

- WordPress 6.2-beta5
- Gutenberg plugin is not enabled

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #48909

## What?
This PR fixes a problem with the metabox panel when switching to distraction-free mode.

## How?
In the Layout component of the post editor, the layout is controlled by the value of the `isDistractionFree` variable. However, this variable includes the viewport width as a condition, as shown below.

```
const isDistractionFree = isDistractionFreeMode && isLargeViewport;
```

This variable cannot be used because the metabox should be hidden in distraction-free mode, regardless of the width of the viewport. Also, it appears that the name of the variable does not exactly match what is intended by the name of the variable and the result of its value.

Therefore, I changed the name of the variable `isDistractionFreeMode` to `isDistractionFree`, which purely determines the mode, and this variable now controls the display state of the metabox.  At the same time, I adjusted the conditional statements in the areas affected by this change.

## Testing Instructions

In advance, run the following code in the browser console to display the notis messages.

```
 wp.data.dispatch( 'core/notices' ).createErrorNotice( 'error' )
```

Then, activate the Custom Fields panel from the Options menu.

#### Viewport width greater than 960px

- Header bar should appear
- Notices message should appear
- Custom field panel should appear
- Breadcrumb list should appear.

default-large

#### Viewport width smaller than 960px

- Header bar should appear
- Notices message should appear
- Custom field panel should appear
- Breadcrumb list should appear.

default-medium

#### Viewport width smaller than 782px

- Breadcrumb list should not appear.

### Distraction Free Mode

I noticed that the distraction-free mode could not be released unless the notice message bar was turned off, because it overlapped the header area. This may be a bug, but I think it should be addressed in a separate issue.

#### Viewport width greater than 960px

- Header bar should not appear
- Notices message should appear
- Custom field panel should not appear (**Changes by this PR**)
- Breadcrumb list should not appear.

distraction-free-large

#### Viewport width smaller than 960px

- Header bar should appear
- Notices message should appear
- Custom field panel should not appear (**Changes by this PR**)
- Breadcrumb list should not appear

distraction-free-medium

#### Viewport width smaller than 782px

- Breadcrumb list should not appear.

### CODE REVIEW

File: packages/edit-post/src/components/layout/index.js [hunk 1]
```diff
@@ -265,8 +266,8 @@ function Layout( { styles } ) {
 				}
 				footer={
 					! isDistractionFree &&
-					showBlockBreadcrumbs &&
 					! isMobileViewport &&
+					showBlockBreadcrumbs &&
```
Comment (t-hamano) [inline packages/edit-post/src/components/layout/index.js:270]: Nothing appears to have changed here, but the `isDistractionFree` variable no longer contains the viewport width condition.

This fixes another problem. In trunk, there is a "gap" in the viewport width generated by this conditional statement, so the breadcrumb list is displayed when the viewport width is between 782px and 960px, even in distraction-free mode, as shown below.

https://user-images.githubusercontent.com/54422211/223905311-f0ed5a15-d403-4de1-9501-0a0503b7e862.mp4

File: packages/edit-post/src/components/layout/index.js [hunk 2]
```diff
@@ -265,8 +266,8 @@ function Layout( { styles } ) {
...
 					isRichEditingEnabled &&
 					mode === 'visual' && (
```
Comment (t-hamano) [inline packages/edit-post/src/components/layout/index.js:269]: Nothing appears to have changed here, but the `isDistractionFree` variable no longer contains the viewport width condition.

This fixes another problem. In trunk, there is a "gap" in the viewport width generated by this conditional statement, so the breadcrumb list is displayed when the viewport width is between 782px and 960px, even in distraction-free mode, as shown below.

https://user-images.githubusercontent.com/54422211/223905311-f0ed5a15-d403-4de1-9501-0a0503b7e862.mp4

File: packages/edit-post/src/components/layout/index.js [hunk 3]
```diff
@@ -245,14 +243,16 @@ function Layout( { styles } ) {
 				notices={ <EditorSnackbars /> }
 				content={
 					<>
-						{ ! isDistractionFree && <EditorNotices /> }
+						{ ( ! isDistractionFree || ! isLargeViewport ) && (
+							<EditorNotices />
+						) }
```
Comment (Mamaduka) [inline packages/edit-post/src/components/layout/index.js]: Does this fix another issue? Because it doesn't match `isDistractionFreeMode && isLargeViewport`.

Comment (t-hamano) [reply packages/edit-post/src/components/layout/index.js]: If the original condition is rewritten as is, it will be `! ( isDistractionFree && isLargeViewport )`.
Isn't this the same as `( ! isDistractionFree || ! isLargeViewport )`? 🤔 Personally, I think this writing style is easier to read.

Comment (Mamaduka) [reply packages/edit-post/src/components/layout/index.js]: I think we only want to hide the notices in "distraction-free" mode. We can remove the `! isLargeViewport` part.

Comment (t-hamano) [reply packages/edit-post/src/components/layout/index.js]: Your're right, I have confirmed that removing that section will produce the same expected results as before.

In addition, I have made the following changes in 77ab658 to address the following issues:

> I noticed that the distraction-free mode could not be released unless the notice message bar was turned off, because it overlapped the header area. This may be a bug, but I think it should be addressed in a separate issue.

This should completely hide the notice message in distraction-free mode.

File: packages/edit-post/src/components/layout/index.js [hunk 4]
```diff
@@ -217,7 +217,7 @@ function Layout( { styles } ) {
 						}
 					/>
 				}
-				editorNotices={ <EditorNotices /> }
+				editorNotices={ ! isDistractionFree && <EditorNotices /> }
```
Comment (Mamaduka) [inline packages/edit-post/src/components/layout/index.js]: There's no need for a condition; it was intentional - https://github.com/WordPress/gutenberg/pull/41740/files#diff-8933c0b377d83066f7dde9c8b573bab9a7bfe60f73919e4e5e80aff92a88800cR224.

File: packages/edit-post/src/components/layout/index.js (hunk 3 above)
Comment (Mamaduka) [reply packages/edit-post/src/components/layout/index.js]: I would prefer if we address those issues separately. Let's just fix the metabo issue in this PR.

Comment (Mamaduka) [reply packages/edit-post/src/components/layout/index.js]: I would prefer if we address those issues separately. Let's just fix the metabox issue in this PR.

File: packages/edit-post/src/components/layout/index.js (hunk 4 above)
Comment (t-hamano) [reply packages/edit-post/src/components/layout/index.js]: Okay, I reverted 👍

**Review by Mamaduka — APPROVED** [review]
Thank you, @t-hamano! This works well in my tests.

**Comment by Mamaduka** [comment]
I just cherry-picked this PR to the wp/6.2 branch to get it included in the next release: e125710eab

**Comment by draganescu** [comment]
Thank you @t-hamano 👍🏻
