### PR TITLE
Fix: Preset controls need the preset CSS variables in scope

### LINKED ISSUE #26511: Preset controls need the preset CSS variables in scope
Reported at https://github.com/Automattic/themes/pull/2659/files#r512186187

Theme authors can use CSS Custom Properties to define the presets, for example, to make the gradients depend on the solid colors:

```
{
  "color": {
    "gradients": [
      {
        "slug": "some-gradient",
        "gradient": "linear-gradient(to bottom, transparent 20%, var(--wp--preset--color--secondary) 20%, var(--wp--preset--color--secondary) 80%, transparent 80%)"
      }
    ],
    "palette": [
      {
        "slug": "primary",
        "color": "#000000"
      },
      {
        "slug": "secondary",
        "color": "#3C8067"
      }
    ]
  }
}
```

These definitions end up attached to the user-facing UI tools. The problem is that these tools aren't part of the editor canvas (wrapper by the `.editor-styles-wrapper` class), so the CSS Custom Properties aren't defined, hence it doesn't work. See what would happen in this case:

97214074-eaff4d80-1798-11eb-9969-18182f7a9939

This is because, both in the post-editor and the site-editor, the global styles are prefixed by the editor wrapper, hence its scope doesn't reach the UI controls.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Fixes: https://github.com/WordPress/gutenberg/issues/26511

This PR makes sure presets and CSS vars are available in the scope of editor UI. These styles are just defining CSS variables and specific classes they should not impact anything in the UI. But if a UI component needs a variable e.g: a gradient preset that depends on a color preset having the variable available makes the UI components look as expected.

## How has this been tested?
I enabled 2021 blocks.
I added the following declaration to theme.json:
```
{
  "color": {
    "gradients": [
      {
        "slug": "some-gradient",
        "gradient": "linear-gradient(to bottom, transparent 20%, var(--wp--preset--color--secondary) 20%, var(--wp--preset--color--secondary) 80%, transparent 80%)"
      }
    ],
    "palette": [
      {
        "slug": "primary",
        "color": "#000000"
      },
      {
        "slug": "secondary",
        "color": "#3C8067"
      }
    ]
  }
}
```
I verified the gradient control circle renders as expected.

### CODE REVIEW

**Comment by nosolosw** [comment]
:wave: I've tested this and these are my thoughts:

1. The fix only works in the site editor.
2. It regresses an issue we fixed recently at https://github.com/WordPress/gutenberg/pull/27065 with the HTML block.

The first issue seems solvable by following the proposal at https://github.com/WordPress/gutenberg/issues/26511#issuecomment-717428069

The second one is a bit more convoluted. On the one hand, in the site editor, we need to grab the preset styles to update their values upon user changes ― so far, we've done this by creating our own style node in the client. On the other hand, the stylesheet needs to be ready for when the HTML block (and potentially others such as classic?) grabs them to use in its iframe. I'm not sure how to balance the two needs without looking at how the HTML preview works.

I can perhaps offer some ideas about how to address this but they need some investigation:

- It looks like adding presets to the `settings.style` key as it works now wouldn't work. Perhaps we can teach this code to avoid wrapping some styles? This would have the benefit that observers of the styles would still work as expected.

- Creating a named embedded stylesheet in the server that we can grab in the client to update its values should it be necessary. It could work to fix the initial render of the HTML preview, but without looking at how the HTML preview works, I'm not sure whether it'll work for subsequent re-renders (user changes values of the theme presets).

- Add a style node in the client, but in a way that's hooked up to the way the HTML preview (and other blocks?) work.

**Comment by nosolosw** [comment]
Issues for the HTML block that may relevant to look at together with this

- https://github.com/WordPress/gutenberg/issues/9129
- https://github.com/WordPress/gutenberg/issues/27112

**Comment by jorgefilipecosta** [comment]
Hi @nosolosw thank you for the review and for suggesting possible paths to address the issues.

I updated this PR and it follows the path "It looks like adding presets to the settings.style key as it works now wouldn't work. Perhaps we can teach this code to avoid wrapping some styles? This would have the benefit that observers of the styles would still work as expected.".

**Comment by nosolosw** [comment]
To avoid CSS conflicts, in the editors, we should have this:

- Block styles: **with** wrapper.
- CSS variables: **without** wrapper.
- Classes generated by the CSS variables: **with** wrapper.

Code-wise:

- the explosion of methods for every style use case makes me uneasy. I'd like a more compact approach but unsure how to articulate this better. Any ideas? Perhaps we can have a parametrizable `get_stylesheet( $styles )` where `$styles` indicates what we need: all (default), only CSS vars, etc.

- can we also consolidate the use of cache & CSS for link attachment to the new situation? This is minor compared to the above.

**Comment by jorgefilipecosta** [comment]
> To avoid CSS conflicts, in the editors, we should have this:
> 
> * Block styles: **with** wrapper.
> * CSS variables: **without** wrapper.
> * Classes generated by the CSS variables: **with** wrapper.
> 
> Code-wise:
> 
> * the explosion of methods for every style use case makes me uneasy. I'd like a more compact approach but unsure how to articulate this better. Any ideas? Perhaps we can have a parametrizable `get_stylesheet( $styles )` where `$styles` indicates what we need: all (default), only CSS vars, etc.
> * can we also consolidate the use of cache & CSS for link attachment to the new situation? This is minor compared to the above.

Hi @nosolosw,

Thank you for the review, all your feedback was applied 👍

**Comment by nosolosw** [comment]
Going to take a look at the code now, but here's what I've found:

- Some block contexts are duplicated in the front & post-editor => first, they are included with empty styles, then with proper styles. It seems that the CSS var stylesheet generation is messing with things.

```css
h1 {
}

// ...

h1 {
  font-size: var(--wp--preset--font-size--gigantic);
  line-height: 1.1;
}
```

File: lib/class-wp-theme-json.php [hunk 1]
```diff
@@ -910,10 +940,18 @@ function ( $element ) {
 	 * Returns the stylesheet that results of processing
 	 * the theme.json structure this object represents.
 	 *
+	 * @param string $type Type of stylesheet we want accepts 'all', 'block_styles', and 'css_variables'.
 	 * @return string Stylesheet.
 	 */
-	public function get_stylesheet() {
-		return array_reduce( $this->contexts, array( $this, 'to_stylesheet' ), '' );
+	public function get_stylesheet( $type = 'all' ) {
```
Comment (nosolosw) [inline lib/class-wp-theme-json.php:946]: I'd like us to keep adding tests for the new things. In this case, get_stylesheet( 'block_styles' ) and get_stylesheet( 'css_variables' ). I believe that would have caught the issue with the empty rulesets.

File: lib/class-wp-theme-json.php [hunk 2]
```diff
@@ -910,10 +940,18 @@ function ( $element ) {
...
+		switch ( $type ) {
+			case 'all':
```
Comment (nosolosw) [inline lib/class-wp-theme-json.php:948]: What if instead of using the `case all` we move this code to the `default` fallback? We'd have every code path covered.

File: lib/class-wp-theme-json.php [hunk 3]
```diff
@@ -816,13 +816,14 @@ function ( $carry, $element ) {
 	/**
 	 * Converts each context into a list of rulesets
 	 * to be appended to the stylesheet.
+	 * These rulesets contain the all css variables (custom variables and preset variables)
+	 * and all the preset classes.
```
Comment (nosolosw) [inline lib/class-wp-theme-json.php:820]: This comment seems to need updating?

File: lib/class-wp-theme-json.php [hunk 4]
```diff
@@ -846,31 +847,60 @@ function ( $carry, $element ) {
...
+		$declarations = array();
+		self::compute_style_properties( $declarations, $context );
+
+		if ( ! empty( $declarations ) ) {
+			// Attach the ruleset for style and custom properties.
+			$stylesheet .= self::to_ruleset( $context['selector'], $declarations );
+		}
+
 		// Attach the rulesets for the classes.
 		self::compute_preset_classes( $stylesheet, $context );
```
Comment (nosolosw) [inline lib/class-wp-theme-json.php:905]: Conceptually, I don't like that we output the preset classes here. In practical terms, I guess it's fine? Flagging in case you have thoughts.

File: lib/global-styles.php [hunk 5]
```diff
@@ -135,9 +136,9 @@ function gutenberg_experimental_global_styles_get_stylesheet( $tree ) {
 		}
 	}
 
-	$stylesheet = $tree->get_stylesheet();
+	$stylesheet = $tree->get_stylesheet( $type );
```
Comment (nosolosw) [inline lib/global-styles.php:139]: So, now, the resulting stylesheet can be actually 3 different stylesheets, however, we only have 1 cache. I presume that can be a source of conflicts we need to fix?

Comment (jorgefilipecosta) [reply lib/global-styles.php:140]: Nice catch we should only cache type all which is the one used on the front end.

**Comment by jorgefilipecosta** [comment]
All the feedback was addressed before the merge.
