### PR TITLE
Fix default featured image size

### LINKED ISSUE #15842: Featured image uses wrong default size
**Describe the bug**
By default gutenberg tries to load the featured image with the image size `post-thumbnail` in the editor sidebar:
https://github.com/WordPress/gutenberg/blob/c4cd4d8877087d08a80bbba9d4bf5f4f45cd6e83/packages/editor/src/components/post-featured-image/index.js#L34

This image size does not exist by default. The correct image size would be `thumbnail`.
See the default image sizes in the Codex: https://codex.wordpress.org/Post_Thumbnails#Thumbnail_Sizes

Because the specified image size does not exist, the `full` size is used as a fallback. 
This causes a performance issue, because a potentially far too large image is loaded.

**To reproduce**
1. Create a Post
2. Add a Featured image in a large size e.g. 2000px wide
3. Right-click on the image and choose "open image in new window"
4. You can see the image in full size.

**Expected behavior**
The Featured image should be loaded in a smaller version/thumnail site within the editor sidebar.

**Desktop:**
 - OS: OS X 10.13.6
 - Browser Chrome
 - Version 74.0.3729.169

**Additional context**
- Gutenberg Version 5.8.0-rc.1

### PR DESCRIPTION
**Pull request by derweili**
## Description
Fixed the default image sizes used for featured images displayed in the editor:
Fixes: #15842, #14084

## How has this been tested?
Verified with a linter on my local environment.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/editor/src/components/post-featured-image/index.js [hunk 1]
```diff
@@ -31,7 +31,7 @@ function PostFeaturedImage( { currentPostId, featuredImageId, onUpdateImage, onR
 
 	let mediaWidth, mediaHeight, mediaSourceUrl;
 	if ( media ) {
-		const mediaSize = applyFilters( 'editor.PostFeaturedImage.imageSize', 'post-thumbnail', media.id, currentPostId );
+		const mediaSize = applyFilters( 'editor.PostFeaturedImage.imageSize', 'thumbnail', media.id, currentPostId );
```
Comment (jorgefilipecosta) [inline packages/editor/src/components/post-featured-image/index.js]: Hi @derweili, thank you for your contribution 👍
I verified that the classic editor also loads post thumbnail when it is available.
E.g: this is the markup classic editor provided (the src is for the post-thumbnail size):
Screenshot 2019-05-27 at 22 19 23

I verified that if post_thumbnail is not available thumbnail size used in the classic editor while in Gutenberg full size is used. I think maybe we should follow the same logic verify if post_thumbnail is available and if yes we should use it, if not Gutenberg verifies if thumbnail is available.

Comment (swissspidy) [reply packages/editor/src/components/post-featured-image/index.js]: Makes sense to me. The `post-thumbnail` image size is available if the theme adds support for post thumbnails.

`thumbnail` on the other hand is always there, but is usually something like 150x150 big.

Comment (derweili) [reply packages/editor/src/components/post-featured-image/index.js]: @swissspidy `thumbnail` is not always there. 

If the uploaded image is smaller than `thumbnail` size (defaut 150 x 150) the thumbnail size is missing.
`full` is the only size that's always available.

I think that the image sizes should be chosen in the following order:
1. Load `post-thumbnail` (still use the `editor.PostFeaturedImage.imageSize` filter)
2. If `post-thumbnail` is not available, load `thumbnail`
3. If both `post-thumbnail` and `thumbnail` are not available, use the `full` size.

Comment (jorgefilipecosta) [reply packages/editor/src/components/post-featured-image/index.js]: Hi @derweili, that seems a good plan 👍

Comment (derweili) [reply packages/editor/src/components/post-featured-image/index.js]: @jorgefilipecosta I implemented the changes as described.
I reset the `mediaSize` to `post-thumbnail` and added a new `fallbackMediaSize` which has the value `thumbnail` by default.

I also added a new filter `editor.PostFeaturedImage.fallbackImageSize` to modify the new `fallbackMediaSize`, similar to the existing filter `editor.PostFeaturedImage.imageSize`

Comment (pablinos) [reply packages/editor/src/components/post-featured-image/index.js]: > `full` is the only size that's always available.

The frustrating thing here is that `media.media_details.sizes` is an empty object when the image is smaller than the `thumbnail` size. If it always contained a size then we could do something to pick the appropriate size in the order of preference. 

Given the current structure of the `media.media_details` object, this change looks good to me.

Alternatively, we could make another change so `sizes` always contains `full` at a minimum. 

Any thoughts?

File: packages/editor/src/components/post-featured-image/index.js [hunk 2]
```diff
@@ -32,11 +32,20 @@ function PostFeaturedImage( { currentPostId, featuredImageId, onUpdateImage, onR
 	let mediaWidth, mediaHeight, mediaSourceUrl;
 	if ( media ) {
 		const mediaSize = applyFilters( 'editor.PostFeaturedImage.imageSize', 'post-thumbnail', media.id, currentPostId );
+		const fallbackMediaSize = applyFilters( 'editor.PostFeaturedImage.fallbackImageSize', 'thumbnail', media.id, currentPostId );
```
Comment (jorgefilipecosta) [inline packages/editor/src/components/post-featured-image/index.js]: Do we really need a new filter for the fallback? Can't we use the existing filter e.g:
```
const fallbackMediaSize = applyFilters( 'editor.PostFeaturedImage. imageSize', 'thumbnail', media.id, currentPostId );
````
Another thing to consider is that the filters used here may have complex logic it would be nice to only compute the fallbackMediaSize if the mediaSize does not exist.

File: packages/editor/src/components/post-featured-image/index.js (hunk 1 above)
Comment (jorgefilipecosta) [reply packages/editor/src/components/post-featured-image/index.js]: Thank you for the improvements @derweili this PR seems to be on a good path I left a suggestion.

> Alternatively, we could make another change so sizes always contains full at a minimum.

It would be good if originally that was the case but now it may be risky to change the structure as there may be external code/filters that is expecting and empty array.
I think the current direction addresses the problem well.

**Review by jorgefilipecosta — COMMENTED** [review]
Thank you for all the interactions @derweili I left a suggestion but other than that the PR seems to be very close to the finish line.

File: packages/editor/src/components/post-featured-image/index.js (hunk 2 above)
Comment (derweili) [reply packages/editor/src/components/post-featured-image/index.js]: @jorgefilipecosta 

I implemented you suggestions in the latest commit.

- The fallback size now uses the same filter as the default size.
- The fallback size now get computed only when default size is missing

**Review by jorgefilipecosta — APPROVED** [review]
LGTM 👍
