### PR TITLE
Filters are incorrectly applied in the __experimental/menu-items controller

### LINKED ISSUE #25095: REST API: Audit menus route filters.
We need to make sure that menus and menu items are having the correct filters applied when being saved.

Something that stood out to me was the `_save_pre` filters in `prepare_item_for_database`, https://github.com/WordPress/gutenberg/blob/458277c376d9b0402ea04034a055c98d7e18625e/lib/class-wp-rest-menu-items-controller.php#L516. To me it looks like those filters are duplicates, since they will eventually be applied when `wp_insert_post` calls `sanitize_post`. The `wp_update_nav_menu_item` function does takes care of moving `menu-item-title` and friends into their correct variable names for `wp_insert_post`. Of note, we don't apply these filters in the base `WP_REST_Posts_Controller` class.

There may be other instances, but I didn't find any in a cursory glance. It'd be good to have another set of eyes or two to look over the code path as well.

### PR DESCRIPTION
**Pull request by anton-vlasenko**
## Description

This PR fixes an issue with the filters in the `WP_REST_Menu_Items_Controller::prepare_item_for_database` method.
We explicitly apply `title_save_pre`, `exceprt_save_pre`, `content_save_pre` filters in there.
But later, we apply the same filters in the `wp_insert_post` function, so we don't need to apply them in the `WP_REST_Menu_Items_Controller::prepare_item_for_database` method.
Fixes https://github.com/WordPress/gutenberg/issues/25095

## How has this been tested?
Two regression unit tests have been written to cover this case. So I would say no testing is needed.
However, If you still want/need to test this, you can do it as described below.
**Prerequisite**: you will need XDebug to test it.
1. Go to the Gutenberg -> Experiments page and enable `Navigation screen` feature.
2. Save the changes.
3. Open `/wp-includes/plugin.php` file in your IDE and place a conditional breakpoint at the beginning of the `apply_filters` function (somewhere around line 166).
4. Use the following condition for your breakpoint:
```php
$hook_name === 'content_save_pre'
```

5. Go back to your browser, and open the Gutenberg  -> Navigation page.
6.  Run the following JavaScript code in your browser's console:
```javascript
wp.apiFetch( {
    path: '/__experimental/menu-items',
    method: 'POST',
    data: { title: 'Some Link', url: 'https://my.test.url' },
} ).then( ( res ) => {
    console.log( res );
} );
```

7. Make sure that `apply_filters` function gets called only once (with $hook_name === 'content_save_pre').

## Screenshots 
No screenshots are needed for this issue.

## Types of changes
Bug fix.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by spacedmonkey** [comment]
Have you validated we don't need these filters?

I also, think, we do not need to add a unit test here. These menu endpoints are still in development and not stable yet, so removing filters doesn't need a unit test.

File: lib/class-wp-rest-menu-items-controller.php [hunk 1]
```diff
@@ -542,17 +542,6 @@ protected function prepare_item_for_database( $request ) {
...
-
-		/** This filter is documented in wp-includes/post.php */
-		$prepared_nav_item['menu-item-title'] = wp_unslash( apply_filters( 'title_save_pre', wp_slash( $prepared_nav_item['menu-item-title'] ) ) );
-
-		/** This filter is documented in wp-includes/post.php */
-		$prepared_nav_item['menu-item-attr-title'] = wp_unslash( apply_filters( 'excerpt_save_pre', wp_slash( $prepared_nav_item['menu-item-attr-title'] ) ) );
-
-		/** This filter is documented in wp-includes/post.php */
-		$prepared_nav_item['menu-item-description'] = wp_unslash( apply_filters( 'content_save_pre', wp_slash( $prepared_nav_item['menu-item-description'] ) ) );
-
```
Comment (spacedmonkey) [inline lib/class-wp-rest-menu-items-controller.php:556]: This is copied from [here](https://github.com/WordPress/wordpress-develop/blob/653790b83c335998cea5083cc3b07faa4e207d0b/src/wp-includes/customize/class-wp-customize-nav-menu-item-setting.php#L717-L726). 

Do you know why they are there?

Comment (anton-vlasenko) [reply lib/class-wp-rest-menu-items-controller.php:556]: > Do you know why they are there?

I guess they are there to call `apply_filters` function before saving values to the database.
But that is not needed in `lib/class-wp-rest-menu-items-controller.php`  file because we apply those filters later (yes, I've checked that, please see `How has this been tested?` section).

**Comment by anton-vlasenko** [comment]
> Have you validated we don't need these filters?

Yes, I've validated that. Please see `How has this been tested?`. We do apply the same filters later. I believe we don't want to apply these filters twice.

> I also, think, we do not need to add a unit test here. These menu endpoints are still in development and not stable yet, so removing filters doesn't need a unit test.

We don't want to apply the same filters twice, and my unit test ensures that it will not happen again. It's a regression unit test.
If we change something in the endpoint we can always refactor the unit test.
But if we remove the unit test the same bug could appear again undetected.

**Comment by spacedmonkey** [comment]
> We don't want to apply the same filters twice 

I was the one who originally added the filter and wrote this whole endpoint. I am happy to remove them. But the unit test is pointless and should be removed. The only way that the filter would be double applied, if someone adds it. Remove the tests, I will approve the PR.

**Comment by TimothyBJacobs** [comment]
Code changes look good to me, thanks for the fix @anton-vlasenko! I agree the unit tests here aren't strictly necessary, but I don't think there is much of a cost to having them. I'll leave the final decision up to @spacedmonkey as he's been the main driver of this endpoint.

**Comment by spacedmonkey** [comment]
Can you remove the tests for now @anton-vlasenko. 

I have created a breakout issue, https://github.com/WordPress/gutenberg/issues/34992 for improving test coverage for these endpoints. If it makes sense, we can add these tests back in that ticket. Agreed?

**Comment by anton-vlasenko** [comment]
@spacedmonkey 

> But the unit test is pointless and should be removed

Let me disagree with that. It's a valid regression unit test and it's not pointless.
Having more unit tests doesn't harm anything.
Even a "bad" unit test is better than no unit tests at all.

> The only way that the filter would be double applied, if someone adds it. 

Yes, and it can happen again.
The probability of this is not zero.
How can someone guarantee it will not happen again in, e.g., four years?
Unit tests are the only way to ensure that.

> Can you remove the tests for now @anton-vlasenko.

Yes, I will remove it, but I haven't heard clear arguments against it.
So, hopefully, we can add it back as part of the https://github.com/WordPress/gutenberg/issues/34992.

**Review by spacedmonkey — APPROVED** [review]
