### PR TITLE
Fix Link UI displaying out of sync results

### LINKED ISSUE #56695: Creating a post / page from the link control provides incomplete post title
### Description

When inserting a link with the LinkControl from the block toolbar, the UI provides the ability to _create_ a new post or pag edirectly from the LinkControl UI, at the bottom of the suggested links.

That is certainly a convenient way to create new post or pages. However, there seems to be a problem with the new title that get suggested for the new post or page. Depending on the styping speed, the suggested title is incomplete.

Minor:
Additionally, regardless whether I'm creating a post or page or custom post, the lablel text shown in the UI always saye:

`Create page: {suggested title here}`

Ideally, it should use a new default post label or use the existing [new_item](https://github.com/WordPress/wordpress-develop/blob/4d19f6c23fab4a0ad0638eb6e626c6a882f2947c/src/wp-includes/class-wp-post-type.php#L968) label.

### Step-by-step reproduction instructions

- Edit a post or page.
- Select some text in a paragraph and click the 'Link' button in the block toolbar.
- Type at an 'average fast' speed (sorry for making assumption on personal abilities) a title for teh pate you want to create.
- Observe at the bottom of the suggested links (if any) the suggested title is incomplete.
- Try again with other titles, with and without dashes: regardless, the suggested title looks incomplete.
- At this point, clicking 'Create page' will create a new draft post / page with the incomplete title.
- Try again but this time type very very slowly: the suggested title now looks correct.

Note that this appears to be triggered by the typing speed and likely by the speed of the suggestions response. Likely, your mileage may vary depending on the response speed.

### Screenshots, screen recording, code snippet

Title with spaces:

Screenshot 2023-11-30 at 16 27 24

Title with dashes:

Screenshot 2023-11-30 at 16 48 42

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by getdave**
## What?

Ensures requests to fetch link suggestions are kept in sync with the current value in the `<input>` used in the `<URLInput>` component. Avoids value becoming out of sync with displayed results.

This fixes a problem evidenced in the Link UI `<LinkControl>` component which _may_ have been introduced in https://github.com/WordPress/gutenberg/pull/45806.

Fixes https://github.com/WordPress/gutenberg/issues/56695

## Why?

Currently [it is possible](https://github.com/WordPress/gutenberg/issues/56695#issuecomment-1875540051) to have a value in the Link Control which is out of sync with the results being displayed. This is most obvious when the "Create page" option is displayed as it's possible to have the text of the Page being offered for creation to be out of sync with the value shown in the `<input>`.

We always want the search results to be reflective of whatever is typed into the input by the user, even if that means more  fetch requests are dispatched overall.

## How?

Removes unwanted state which has historically been used to "block" additional fetch requests being dispatched when the input value changes _if_ a current request is in progress. 

After some investigation I realised that this state is not serving the component well. Currently if you type in the input (the initial search) and a fetch request gets dispatched (note: you have to wait for the `200ms` debounce) and then you immediately type something else there is only a request for the initial search query. The updated link value never triggers a fetch for search results because it is blocked by the state conditional.

By removing this state, we allow the most _recent_ value of the input to trigger a fetch request for search results. It is then this request which fulfills the search suggestons in the UI. 

Race conditions are already handled as the code of `updateSuggestions` will abort in the `.then/catch` if the current request is not the same as the request stored in the instance property. 

## Testing Instructions

First on `trunk` ensure you can [replicate the Issue](https://github.com/WordPress/gutenberg/issues/56695#issuecomment-1875540051).

Then verify the fix in **this PR**:

- New Post
- Add some text
- Using dev tools set your network speed to Slow
- Select text and press Cmd + K to trigger the Link UI.
- The next bit requires good typing speed and timing so prepare in advance!
- Type `wordpress is` then _as soon as_ you see the **loading spinner** display, type ` so cool` (note the specific text doesn't matter - you just need to ensure you type more text when the loading spinner first shows).
- You should see the UI "resolve" and display a search result for `Create: wordpress is so cool`.
- Now try testing searching for pages and make sure you can still find them and things work as per `trunk`.

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/444434/51aba733-8b20-4118-bc1a-d2aa4487965e

### CODE REVIEW

**Comment by getdave** [comment]
@jsnajdr I'm not 100% sure but it looks like this state was added in https://github.com/WordPress/gutenberg/pull/45806 so I'd appreciate your 👀 on this 🙇

File: packages/block-editor/src/components/url-input/index.js [hunk 1]
```diff
@@ -258,7 +250,6 @@ class URLInput extends Component {
 		if (
 			value &&
 			! disableSuggestions &&
-			! this.state.isUpdatingSuggestions &&
```
Comment (jsnajdr) [inline packages/block-editor/src/components/url-input/index.js:261]: This `onFocus` handler is the only place where `state.isUpdatingSuggestions` does something useful: it prevents the REST request from being triggered on focus when there is another one already running.

Could be replaced with checking `this.suggestionsRequest === null`. But first we need to start resetting `this.suggestionsRequest` back to `null` when the request is finished. That's not currently done.

**Review by jsnajdr — COMMENTED** [review]
Looks good, the component should indeed call `updateSuggestions` on value change, even when a request for old value is already running.

I think that #45806 merely refactored the already existing `isUpdatingSuggestions` value, the bug was probably already there. But it's hard to tell after such a long time.

One thing that should be fixed is the `onFocus` handler.

File: packages/block-editor/src/components/url-input/index.js (hunk 1 above)
Comment (getdave) [reply packages/block-editor/src/components/url-input/index.js:261]: I've used `Promise.finally()` to reset `this.suggestionsRequest` to `null` and then conditionalised the focus logic based on that.

**Comment by scruffian** [comment]
I tried everything I could think of to break this - it definitely fixes the issue for me.

**Review by scruffian — APPROVED** [review]
This is looking good. I'm not sure if the 200ms debounce is the right number but that's outside of the scope of this PR anyway.

**Review by jsnajdr — APPROVED** [review]
Looks good to me now, thanks for addressing the feedback :+1:
