### PR TITLE
Video: Avoid an error when removal is locked

### LINKED ISSUE #19311: Broken "Insert from URL" Behavior when using Video block with templateLock = 'all'
**Describe the bug**
I have a block template defined to use `core/video` and I have the InnerBlocks templateLock set to `'all'`. Upon using my custom block and attempting to set the video from the "Insert from URL" option, the following console error is received.

```
Uncaught TypeError: this.props.onReplace is not a function
    at VideoEdit.onSelectURL (block-library.js?ver=2.9.6:19380)
    at MediaPlaceholder.onSubmitSrc (dmp.js:19)
    at HTMLUnknownElement.callCallback (react-dom.js?ver=16.9.0:341)
    at Object.invokeGuardedCallbackDev (react-dom.js?ver=16.9.0:391)
    at invokeGuardedCallback (react-dom.js?ver=16.9.0:448)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.js?ver=16.9.0:462)
    at executeDispatch (react-dom.js?ver=16.9.0:594)
    at executeDispatchesInOrder (react-dom.js?ver=16.9.0:616)
    at executeDispatchesAndRelease (react-dom.js?ver=16.9.0:719)
    at executeDispatchesAndReleaseTopLevel (react-dom.js?ver=16.9.0:727)
```

**To reproduce**
1. Create a new block via InnerBlocks. Define the block template with a video block. And make sure to set the templateLock to 'all'.
```
const TEMPLATE = [
  [ 'core/video', {} ],
];
<InnerBlocks
  template={ TEMPLATE }
  templateInsertUpdatesSelection={ false }
  templateLock="all"
/>
```
2. Create new post
3. Add custom block
4. Set video from "Insert from URL" option and smash Enter.

**Expected behavior**
Video loads properly based on source (whether it be YouTube, Vimeo, etc)

**Screenshots**
Currently, nothing happens and a JS error is thrown every time you smash Enter.
image

**Desktop**
- OS: MacOS
- Browser Chrome
- Version 79.0.3945.88 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Fixes #19311.
It's similar to #38282.

PR fixes an error if using the "Insert from URL" option with the Video block if block removal is locked.

## Why?
The replace action counts as original block removal; the `onReplace` prop will be `undefined` when block removal is locked.

## Testing Instructions
1. Open a Post or Page.
2. Insert a Video Block. 
3. Lock the block removal.
4. Use the "Insert from URL" to insert any embeddable service URL. Example: https://www.youtube.com/watch?v=m6ppAe-DjvU
5. Confirm that there are no errors in the console.

### Testing Instructions for Keyboard
Doesn't affect the UI interface.

### CODE REVIEW

File: packages/block-library/src/video/edit.js [hunk 1]
```diff
@@ -161,7 +161,7 @@ function VideoEdit( {
 			const embedBlock = createUpgradedEmbedBlock( {
 				attributes: { url: newSrc },
 			} );
-			if ( undefined !== embedBlock ) {
+			if ( undefined !== embedBlock && onReplace ) {
```
Comment (ntsekouras) [inline packages/block-library/src/video/edit.js:164]: Do you think it would be better to check explicitly if it's locked?

Comment (Mamaduka) [reply packages/block-library/src/video/edit.js:164]: Currently, `onReplace` is only undefined when a block cannot be removed, but there might be more conditions in the future. I think it makes more sense to check if replace callback is available before calling it.

BlockEdit condition: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-list/block.js#L148-L149

Comment (ntsekouras) [reply packages/block-library/src/video/edit.js:164]: Sounds good, thanks!

**Review by ntsekouras — APPROVED** [review]
👍
