### PR TITLE
Components: Fix the Snackbar auto-dismissal timers

### LINKED ISSUE #58594: Component: The Snackbar auto-dismissal timeout is reset on every rerender
Currently, the Snackbar auto-dismissal timeout is reset on every rerender. The timers are reset when a notice is added or removed from the `SnackbarList`. This causes them to be visible a lot longer than expected.

## Why
The `onRemove` callback has a new reference on each rerender, triggers [side-effect cleanup](https://github.com/WordPress/gutenberg/blob/b21b88dfe4a95222b9f64e0a665cdba34fce778d/packages/components/src/snackbar/index.tsx#L91-L101), and resets timers.

## Possible Solution
Omit `onDismiss` and `onRemove` from the side-effect dependencies.

* I think it is safe to assume that the `onDismiss` callback snapshot won't change after the action is dispatched.
* We can't memoize the curried `onRemove` function. It will always return a new function.

## Step-by-step reproduction instructions
1. Open a post or page.
2. Insert a block.
3. Trigger a few snackbar notices. Copying a block can do that.

### Expected behavior

_Let's assume there is a one-second difference between message triggers._

```
Message 1 - 10s
Message 2 - 10s + 1s
Message 3 - 10s + 2s
```

### Current behavior

```
Message 1 - 10s
Message 2 - 20s (10s after first message)
Message 3 - 30s (10s after second message)
```

cc @WordPress/gutenberg-components

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Resolves #58594.

PR removes `onDismiss/onRemove` callbacks from side-effect dependencies to avoid resetting timers on re-render.

## Why?
See #58594.

## Testing Instructions
1. Open a post or page.
2. Insert a block.
3. Trigger a few snackbar notices. Copying a block can do that.

### Expected behavior

_Let's assume there is a one-second difference between message triggers._

```
Message 1 - 10s
Message 2 - 10s + 1s
Message 3 - 10s + 2s
```

### CODE REVIEW

File: packages/components/src/snackbar/index.tsx [hunk 1]
```diff
@@ -98,7 +98,10 @@ function UnforwardedSnackbar(
 		}, NOTICE_TIMEOUT );
 
 		return () => clearTimeout( timeoutHandle );
-	}, [ onDismiss, onRemove, explicitDismiss ] );
+		// The `onDismiss/onRemove` can have unstable references,
+		// trigger side-effect cleanup, and reset timers.
+		// eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (ciampo) [inline packages/components/src/snackbar/index.tsx]: Disabling exhaustive deps checks is risky because it will prevent ESlint from catching potential bugs for this hook in the future. Could we instead use refs for `onDismiss` and `onRemove` ? Something like:

```js
const onRemoveRef = useRef( onRemove );
useEffect( () => {
  onRemoveRef.current = onRemove;
, [ onRemove ] );

const onDismissRef = useRef( onDismiss );
useEffect( () => {
  onDismissRef.current = onDismiss;
, [ onDismiss ] );

// ..useEffect handling the auto-dismissal timers
```

**Review by ciampo — COMMENTED** [review]
Could also add a CHANGELOG entry? Thank you!

File: packages/components/src/snackbar/index.tsx (hunk 1 above)
Comment (Mamaduka) [reply packages/components/src/snackbar/index.tsx]: I was just thinking about using the same pattern 😅 I will push updates shortly.

Comment (Mamaduka) [reply packages/components/src/snackbar/index.tsx]: Updated in [6bacb67](https://github.com/WordPress/gutenberg/pull/58604/commits/6bacb67d1baa6f0a7aada90fd22d960e4369bb1a).

File: packages/components/src/snackbar/index.tsx [hunk 2]
```diff
@@ -88,17 +94,24 @@ function UnforwardedSnackbar(
 
 	useSpokenMessage( spokenMessage, politeness );
 
-	// Only set up the timeout dismiss if we're not explicitly dismissing.
+	// The `onDismiss/onRemove` can have unstable references,
+	// trigger side-effect cleanup, and reset timers.
+	const callbackRefs = useRef( { onDismiss, onRemove } );
+	useLayoutEffect( () => {
```
Comment (ciampo) [inline packages/components/src/snackbar/index.tsx:100]: What's the reason for `useLayoutEffect` instead of `useEffect` ?  In theory `useEffect`s should be called in order, so we should be guaranteed that the `onDimiss` and `onRemove` refs are always up to date

Comment (Mamaduka) [reply packages/components/src/snackbar/index.tsx:100]: Nothing specific. This is just a common pattern; we even have [a `useLatestRef` hook](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/utils/hooks/use-latest-ref.ts), but I don't use here because returned value isn't recognized as Ref and linter complains.

Related: https://epicreact.dev/the-latest-ref-pattern-in-react/

Comment (ciampo) [reply packages/components/src/snackbar/index.tsx:100]: Thank you for the link, super interesting read!

I took a look back at [this article](https://kentcdodds.com/blog/useeffect-vs-uselayouteffect) by Kent that I usually refer to when talking `useEffect` and `useLayoutEffect`, I noticed the ["special case"](https://kentcdodds.com/blog/useeffect-vs-uselayouteffect#one-special-case) section too!

**Review by ciampo — APPROVED** [review]
🚀 

Code changes LGTM and tests well as per instructions.
I also realised that we don't have unit tests for this component, which would have been handy here — but not in the scope for this PR.

Thank you for working on this, @Mamaduka 🙏

**Comment by Mamaduka** [comment]
Thanks for testing and review, @ciampo!
