### PR TITLE
wp-env: Fix chown cannot access 'wp-config.php'

### LINKED ISSUE #29814: env: chown: cannot access 'wp-config.php' when running wp-env start
## Description
While testing the fixes from https://github.com/WordPress/gutenberg/pull/29800 using the `trunk` version of wp-env, running `wp-env start` fails with the following error:

```
✖ Error while running docker-compose command.
chown: cannot access 'wp-config.php': No such file or directory
```

Using this `.wp-env.json` file:

```
{
  "plugins": [
    "."
  ]
}
```

I think there might be a timing issue with the docker image not having finished copying the WordPress files, when listing the contents of /var/www/html right before the chown is executed, only three directories are listed, and no files. Also, it seems to be working on another machine, but not on my (not so beefy) laptop.

Furthermore, adding `"core": "WordPress/WordPress"` to `.wp-env.json` seems to be a workaround, which makes sense because wp-env does wait for WP files to be copied when using external core sources.

## Step-by-step reproduction instructions
1. Create a directory containing the `.wp-env.json` described above.
2. Run `wp-cli start` (using the version from `trunk`) in the created directory.

## Expected behaviour
wp-env environment comes up successfully

## Actual behaviour
command fails

## WordPress information
- WordPress version: latest from docker image
- Gutenberg version: `trunk`
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

### PR DESCRIPTION
**Pull request by ribaricplusplus**
## Description

**IMPORTANT**: Do not merge this until https://github.com/docker-library/wordpress/pull/587 gets pushed to Docker Hub. **Update**: The change has been pushed to Docker Hub and this PR is safe to merge. 

This PR fixes #29814. We used to manually run `chown` on `wp-config.php` because Docker Hub Wordpress image would create it with root being the owner, which means we can't access `wp-config.php` with wp cli and that caused problems. The problem with this manual solution was that there was a race condition: After containers start, the files are not actually ready, and if we run `chown` before files are copied, the issue #29814 happens.

Since the permission problem is now solved at the root, in the Docker Hub image in the aforementioned PR, there's no longer any need for manually doing `chown`, so this PR removes that.

## How is this tested

EDIT: Now that the Docker Hub image has been updated, this PR can be tested by simply getting it locally and trying `wp-env start`

I manually built the WordPress image from the aforementioned PR https://github.com/docker-library/wordpress/pull/587 and used this PR for `wp-env`. If you want to test the same way, it will be necessary to change `FROM` in the Dockerfile to the image that you manually build, that is here:

https://github.com/WordPress/gutenberg/blob/8a43a9091911ea2ea78a156a5c486108364f3bed/packages/env/lib/init-config.js#L106-L108

### CODE REVIEW

File: packages/env/lib/commands/start.js [hunk 1]
```diff
@@ -141,23 +139,10 @@ module.exports = async function start( { spinner, debug, update, xdebug } ) {
...
-	await Promise.all( [
-		makeConfigWritable( 'development', config ),
-		makeConfigWritable( 'tests', config ),
-	] );
-
 	// Only run WordPress install/configuration when config has changed.
 	if ( shouldConfigureWp ) {
 		spinner.text = 'Configuring WordPress.';
 
-		if ( config.coreSource === null ) {
```
Comment (ribaricplusplus) [inline packages/env/lib/commands/start.js:153]: From reading the code and experimenting, it seems that `config.coreSource` is always undefined, and this code never gets executed. I tested with `core: null`, and `core: WordPress/WordPress` in `.wp-env.json`, and filesystem permissions were always fine (this conditional claims to solve filesystem permissions).

It seems that the issues this conditional was meant to resolve have been resolved in the Docker Hub wordpress image:  https://github.com/docker-library/wordpress/issues/436

Also, nowhere else in the code is `config.coreSource` mentioned.

Comment (noahtallen) [reply packages/env/lib/commands/start.js:153]: Cool. I think `config.coreSource` is used in `buildDockerComposeConfig` to map over local or git/remote WordPress sources. But if that issue is resolved, it's great that we can remove it. I believe this conditional was added here: https://github.com/WordPress/gutenberg/pull/20406.

cc @noisysocks, do you know how to test the problem this was solving?

Comment (ribaricplusplus) [reply packages/env/lib/commands/start.js:153]: Note that `config.coreSource` in `buildDockerComposeConfig` is not actually `config.coreSource` but `config.env.development.coreSource` or `config.env.tests.coreSource`

**Comment by noahtallen** [comment]
Some related issues this might solve (or open a path towards solving): #22515, #28201, #29929

**Comment by ribaricplusplus** [comment]
I had a quick look at #28201 and I think I can guess why the upload folder wouldn't be writable.

WordPress (php-fpm, to be exact) runs as user `www-data` UID 33. When `core` is not-null in `.wp-config.json`, meaning the files are on the local filesystem, files will be owned by the user who ran docker, usually that is UID 1000. UID 33 cannot access stuff owned by UID 1000, and the entire wp-content folder is owned by UID 1000.

A solution might be to use groups and place both www-data and the real user(UID 1000) in the same group. This might need to be resolved in the Docker Hub image.

File: packages/env/lib/commands/start.js (hunk 1 above)
Comment (ribaricplusplus) [reply packages/env/lib/commands/start.js:153]: Actually that's nonsense, sorry, it is actually `config.coreSource`. I was looking at a wrong thing

That means those usages should also be altered accordingly if it is indeed always undefined, I'll look into it tomorrow.

Comment (ribaricplusplus) [reply packages/env/lib/commands/start.js:153]: No this is all completely wrong, I'll update it

Comment (ribaricplusplus) [reply packages/env/lib/commands/start.js:153]: I fixed the incorrect usage of `config.coreSource` in `buildDockerComposeConfig`, added unit tests for it, and tested manually that everything still works fine

**Comment by ribaricplusplus** [comment]
The needed change to Docker Hub wordpress image has been pushed: https://github.com/docker-library/official-images/pull/9833

This PR can now be merged (as far as I'm concerned).

**Review by noahtallen — APPROVED** [review]
I did a lot of testing on this, and everything is working very well (both with and without specifying core sources). Thanks for investigating this!
