### PR TITLE
Site editor: style the selected template pattern

### LINKED ISSUE #65127: Add "selected" styling to active elements in the design selector.
## What problem does this address?

While working on TT5, I noticed no visual indication of the design chosen for templates. It would be nice to know at a first glance which design is active.

https://github.com/user-attachments/assets/36163b7c-6a96-4851-b3c7-4836e9ff8a34

To reproduce:

1. Download Twenty Twenty-Five, or use a theme that comes with different designs for some templates.
2. Locate that template in the site editor.
3. Change the design, and see that there's no indication.

## What is your proposed solution?

We could leverage what we already have. The `:focus` style for that same element already has a visual hint (border with the admin accent color). We know with the `data-active-item` which element is active.

The other option, which can also be in line with the design patterns we already have in place, could be replicating what we have for the "selected" state in the "Templates" page of the site editor.

https://github.com/user-attachments/assets/5b42ea7f-6ed3-4d63-9e8a-7e7dd9314d8d

### PR DESCRIPTION
**Pull request by benazeer-ben**
### What?

Fixes #65127

Enhance the template selector section by adding "selected" styling to active elements based on the issue raised in [GitHub Ticket #65127](https://github.com/WordPress/gutenberg/issues/65127).

### Why?

This improvement addresses the issue raised in [GitHub Ticket #65127]

Users had difficulty identifying which templates they had selected. Adding styling to active elements provides a clearer and better user experience.

### How?

To resolve this, two files were updated:

index.js [packages/block-editor/src/components/block-patterns-list/index.js]:
Modified the code to update the active pattern selection when a template is clicked. The is-active class is now added to active elements.

style.scss [packages/block-editor/src/components/block-patterns-list/style.scss ]: 
Styled the selected templates by targeting the is-active class, visually distinguishing them from unselected ones.

The proposed solution in the ticket could not resolve the issue using data-active-item because it wasn’t updating when templates were clicked. 
Hence, the JS code was updated to manage the active state and apply the is-active class on selected patterns. The styling in the CSS reflects these changes.

### Testing Instructions
1. Navigate to the template section in the site editor.
2. Change the template for any page.
3. Select a template pattern from the design section.
4. The selected pattern will have a blue border to indicate its active state.

### Testing Instructions for Keyboard

1. Navigate to the template section:
Use the Tab key to move through the site editor interface until you reach the template section.

2. Change the template:
Use the Tab key to navigate through the list of available templates.
Once focused on a template, press Enter to select it.

3. Select a template pattern:
Use Tab to navigate to the design section, where different template patterns are displayed.
Use the arrow keys (Up, Down, Left, Right) to move between the available patterns.
Press Enter to select a pattern. The active pattern should now be styled with a blue border.

Screenshot
[](url)

Kindly let me know if anyone has any feedbacks or any improvements needed. 

Thanks,
Benazeer

### CODE REVIEW

File: packages/block-editor/src/components/block-patterns-list/index.js [hunk 1]
```diff
@@ -77,7 +79,12 @@ function BlockPattern( {
 		>
 			{ ( { draggable, onDragStart, onDragEnd } ) => (
 				<div
-					className="block-editor-block-patterns-list__list-item"
+					className={ clsx(
+						'block-editor-block-patterns-list__list-item',
+						{ 'is-active': isActive } // Apply 'is-active' class if this pattern is active
+					) }
+					role="button" // Add role to make it behave like a button
+					tabIndex={ 0 } // Make the element focusable by keyboard
```
Comment (ciampo) [inline packages/block-editor/src/components/block-patterns-list/index.js]: The child `Composite.Item` already renders an interactive item with `role="option"` and its "tabbability" is already managed internally by the `Composite` component. Therefore, I don't think this approach is correct in terms of UX, semantics and accessibility

File: packages/block-editor/src/components/block-patterns-list/index.js [hunk 2]
```diff
@@ -77,7 +79,12 @@ function BlockPattern( {
 		>
 			{ ( { draggable, onDragStart, onDragEnd } ) => (
 				<div
-					className="block-editor-block-patterns-list__list-item"
+					className={ clsx(
+						'block-editor-block-patterns-list__list-item',
+						{ 'is-active': isActive } // Apply 'is-active' class if this pattern is active
```
Comment (ciampo) [inline packages/block-editor/src/components/block-patterns-list/index.js]: I think we should separate the concepts of "active" and "selected":

- active, in this context, refers to the active composite item, ie,. the composite item that has focus when the parent composite widget is focused;
- selected, which is, I believe, the new feature that this PR wants to add (ie. the pattern that is being used)

If we were to continue with the current approach, I'd rename the variable to `selected`

File: packages/block-editor/src/components/block-patterns-list/index.js [hunk 3]
```diff
@@ -92,6 +99,20 @@ function BlockPattern( {
...
+					} }
+					onKeyDown={ ( event ) => {
+						// Simulate button click with Enter or Space key press
+						if ( event.key === 'Enter' || event.key === ' ' ) {
+							event.preventDefault(); // Prevent default behavior for spacebar
+							setActivePattern( id );
+							onClick( pattern, blocks );
+							onHover?.( null );
+						}
+					} }
```
Comment (ciampo) [inline packages/block-editor/src/components/block-patterns-list/index.js]: As mentioned above, `Composite.Item` is already an interactive element, and all interaction-related code should happen there.

File: packages/block-editor/src/components/block-patterns-list/index.js [hunk 4]
```diff
@@ -199,23 +221,49 @@ function BlockPatternsList(
...
+				}
+			}
+		}
+	}, [ shownPatterns, blockPatterns ] );
+	const handleClickPattern = ( pattern ) => {
+		// Check if we are in a browser environment and localStorage is available
+		if ( typeof window !== 'undefined' && window.localStorage ) {
+			// eslint-disable-next-line no-undef
+			localStorage.setItem( 'savedPattern', pattern.name ); // Save the selected pattern in localStorage
+		}
```
Comment (ciampo) [inline packages/block-editor/src/components/block-patterns-list/index.js]: I'm not an expert on best practices to save/restore data, but I don't think we usually use `localStorage`. I believe we should use data stores, but @ntsekouras @youknowriad @ellatrix may be able to give more tailored advice on which store/selector/action could be potentially used.

File: packages/block-editor/src/components/block-patterns-list/style.scss [hunk 5]
```diff
@@ -71,3 +71,10 @@
 		}
 	}
 }
+// Solution for "Add "selected" styling to active elements in the design selector."
+// https: //github.com/WordPress/gutenberg/issues/65127
+.block-editor-block-patterns-list__list-item.is-active {
+	border: 2px solid #007cba;
+	/* Custom styles for active item */
+	background-color: #eaf5ff;
+}
```
Comment (ciampo) [inline packages/block-editor/src/components/block-patterns-list/style.scss]: Let's make sure we uniform to how we apply focused/selected styles in other parts of the editor. Just looking [a few lines above](https://github.com/WordPress/gutenberg/blob/cd77dd950b7762ebfa99987ffb0b3ed8f9888d94/packages/block-editor/src/components/block-patterns-list/style.scss#L53-L55), I see that we're already using `outline` (and not border), and that we're consuming a bunch of CSS variables for the color and thickness.

**Review by ciampo — CHANGES_REQUESTED** [review]
Hey @benazeer-ben , thank you so much for working on your first contribution to Gutenberg 🙏 

I have some reservations about the proposed approach — I have left more details in each inline comment. I will also leave a comment in the original issue

File: packages/block-editor/src/components/block-patterns-list/style.scss (hunk 5 above)
Comment (benazeer-ben) [reply packages/block-editor/src/components/block-patterns-list/style.scss]: Thanks for mentioning this point @ciampo 

I will update this css in the next commit.

File: packages/block-editor/src/components/block-patterns-list/index.js (hunk 1 above)
Comment (benazeer-ben) [reply packages/block-editor/src/components/block-patterns-list/index.js]: Thanks for mentioning this point @ciampo 

I will update this line of codes by removing it since these are already handling in Composite component.

File: packages/block-editor/src/components/block-patterns-list/index.js (hunk 2 above)
Comment (benazeer-ben) [reply packages/block-editor/src/components/block-patterns-list/index.js]: @ciampo Thanks for the clarification.

I will rename the active to selected in the above mentioned code snippets.

Along with that, I will work on some updates which will handle the styling of active element that has focus when the parent composite widget is focused.

File: packages/block-editor/src/components/block-patterns-list/index.js (hunk 3 above)
Comment (benazeer-ben) [reply packages/block-editor/src/components/block-patterns-list/index.js]: Thanks for mentioning this point @ciampo 

I will update this line of codes by removing it since these are already handling in Composite component.

File: packages/block-editor/src/components/block-patterns-list/index.js (hunk 1 above)
Comment (benazeer-ben) [reply packages/block-editor/src/components/block-patterns-list/index.js]: I have added these lines since I got  `wp-scripts lint-js` errors while committing the code.

`81:5  error  Visible, non-interactive elements with click handlers must have at least one keyboard listener  jsx-a11y/click-events-have-key-events
  81:5  error  Static HTML elements with event handlers require a role                                         jsx-a11y/no-static-element-interactions`
  
  So shall I keep this?
  
  Please share your thought on this @ciampo 
  
  Thanks.

File: packages/block-editor/src/components/block-patterns-list/index.js (hunk 3 above)
Comment (benazeer-ben) [reply packages/block-editor/src/components/block-patterns-list/index.js]: @ciampo 

Added `onKeyDown` to resolve the pre-commit issues connected with `wp-scripts lint-js` issues.

So shall I keep this?

Please share your thought on this @ciampo

Thanks.

File: packages/block-editor/src/components/block-patterns-list/index.js (hunk 4 above)
Comment (benazeer-ben) [reply packages/block-editor/src/components/block-patterns-list/index.js]: Thanks for the suggestion @ciampo 

I have updated the code with `sessionStorage` since it is using in various scenarios. Please correct me if I'm 
following something wrong.

Comment (ciampo) [reply packages/block-editor/src/components/block-patterns-list/index.js]: Can we avoid using local or session storage entirely? Ideally we would either save this information in local react state (without persisting it to the browser), or otherwise retrieve this information from a data store.
The folks that I pinged above should be able to give more info on this

File: packages/block-editor/src/components/block-patterns-list/index.js (hunk 1 above)
Comment (ciampo) [reply packages/block-editor/src/components/block-patterns-list/index.js]: We should be able to simplify the code — this div (the one with class `block-editor-block-patterns-list__list-item`) should be left untouched: no `button` role, no `tabindex`, on `onclick` and `onkeydown` handlers, and no active styles.

There is already a component that is representing the interactive bit of UI, and that is the `Composite.Item` component a few lines below.  We should apply the selected styles to it (similarly to how we already apply focused styles). No need to apply roles or tabindexes, and there is already an `onClick` handler too. The `onkeydown` handler would also be unnecessary, given how the underlying `button` element behaves natively in the browser

File: packages/block-editor/src/components/block-patterns-list/index.js (hunk 3 above)
Comment (ciampo) [reply packages/block-editor/src/components/block-patterns-list/index.js]: I don't think we need the `onKeyDown` — see answer in https://github.com/WordPress/gutenberg/pull/65917#discussion_r1794960682

File: packages/block-editor/src/components/block-patterns-list/style.scss (hunk 5 above)
Comment (benazeer-ben) [reply packages/block-editor/src/components/block-patterns-list/style.scss]: CSS has been updated as mentioned.

File: packages/block-editor/src/components/block-patterns-list/index.js (hunk 3 above)
Comment (benazeer-ben) [reply packages/block-editor/src/components/block-patterns-list/index.js]: Updated.

File: packages/block-editor/src/components/block-patterns-list/index.js (hunk 1 above)
Comment (benazeer-ben) [reply packages/block-editor/src/components/block-patterns-list/index.js]: Done

File: packages/block-editor/src/components/block-patterns-list/index.js (hunk 2 above)
Comment (benazeer-ben) [reply packages/block-editor/src/components/block-patterns-list/index.js]: - Renamed the active to selected ignorer to handle the selected pattern.
- Changes applied to focus the active element while navigating through keyboard.

File: packages/block-editor/src/components/block-patterns-list/index.js (hunk 4 above)
Comment (benazeer-ben) [reply packages/block-editor/src/components/block-patterns-list/index.js]: Hi @ciampo 

Now  I have removed the use of local/session storage for storing the selected pattern across page reloads after saving the template. Now, the selected pattern is managed using local React state. 

This ensures that the selection persists after saving the template but resets when the page is reloaded 
( similar behaviour of Block --> Design selection ). 

I think this needs further discussion to determine if we should maintain the selected item across page reloads even after saving. I'm open to feedback and suggestions from the team regarding this approach.

Looking forward to input from others, and I will make updates based on that.

Thanks!

**Comment by ciampo** [comment]
@benazeer-ben as there are still quite a few aspects that need addressing — at a high level:
- no need for extra `onClick` handlers, `Composite.Item` already has one;
- no need to add a `tabindex=0`, `Composite` already handles that
- the `setSelectedPattern` call already happens in the list component, no need to call the function in each item;
- `selectedId` and `setSelectedId` are not valid props of the `Composite` component;
- the `is-selected` class can be added directly to `Composite.Item`

I've pushed a draft PR where I applied some changes — you should take a look at [the changes across those commits](https://github.com/WordPress/gutenberg/pull/66185/files/09e25d9a692ba80f47dd86cadda523a74fe52916..5b91306f73ad7b5420092ecb115dbdb6e26dbf1b) and apply them to this PR (I tried pushing the changes directly here, but didn't have permissions).

<details>

<summary>Alternatively, here's a diff of all the changes that I recommend you apply to this PR:</summary>

```diff
diff --git a/packages/block-editor/src/components/block-patterns-list/index.js b/packages/block-editor/src/components/block-patterns-list/index.js
index d19bacf31f..f95d6a3a50 100644
--- a/packages/block-editor/src/components/block-patterns-list/index.js
+++ b/packages/block-editor/src/components/block-patterns-list/index.js
@@ -42,8 +42,7 @@ function BlockPattern( {
 	showTitle = true,
 	showTooltip,
 	category,
-	isSelected, // new prop to manage active state
-	setActivePattern, // function to set the active pattern
+	isSelected,
 } ) {
 	const [ isDragging, setIsDragging ] = useState( false );
 	const { blocks, viewportWidth } = pattern;
@@ -79,10 +78,7 @@ function BlockPattern( {
 		>
 			{ ( { draggable, onDragStart, onDragEnd } ) => (
 				<div
-					className={ clsx(
-						'block-editor-block-patterns-list__list-item',
-						{ 'is-selected': isSelected } // Apply 'is-selected' class if this pattern is active
-					) }
+					className="block-editor-block-patterns-list__list-item"
 					draggable={ draggable }
 					onDragStart={ ( event ) => {
 						setIsDragging( true );
@@ -97,10 +93,6 @@ function BlockPattern( {
 							onDragEnd( event );
 						}
 					} }
-					onClick={ () => {
-						onClick( pattern, blocks );
-						onHover?.( null );
-					} }
 				>
 					<WithToolTip
 						showTooltip={
@@ -126,13 +118,13 @@ function BlockPattern( {
 												pattern.type ===
 													INSERTER_PATTERN_TYPES.user &&
 												! pattern.syncStatus,
+											'is-selected': isSelected,
 										}
 									) }
 								/>
 							}
 							id={ id }
 							onClick={ () => {
-								setActivePattern( id ); // Set active pattern when clicked
 								onClick( pattern, blocks );
 								onHover?.( null );
 							} }
@@ -223,17 +215,15 @@ function BlockPatternsList(
 
 		setActiveCompositeId( firstCompositeItemId );
 	}, [ shownPatterns, blockPatterns ] );
-	const handleClickPattern = ( pattern ) => {
-		setActivePattern( pattern.name ); // Set the clicked pattern as active
-		onClickPattern( pattern ); // Original onClick logic
+	const handleClickPattern = ( pattern, blocks ) => {
+		setActivePattern( pattern.name );
+		onClickPattern( pattern, blocks );
 	};
 	return (
 		<Composite
 			orientation={ orientation }
 			activeId={ activeCompositeId }
 			setActiveId={ setActiveCompositeId }
-			selectedId={ activePattern }
-			setSelectedId={ setActivePattern }
 			role="listbox"
 			className="block-editor-block-patterns-list"
 			aria-label={ label }
@@ -252,8 +242,9 @@ function BlockPatternsList(
 						showTitle={ showTitle }
 						showTooltip={ showTitlesAsTooltip }
 						category={ category }
-						isSelected={ activePattern === pattern.name } // Highlight the active pattern
-						setActivePattern={ setActivePattern } // Function to set the active pattern
+						isSelected={
+							!! activePattern && activePattern === pattern.name
+						}
 					/>
 				) : (
 					<BlockPatternPlaceholder key={ pattern.name } />
diff --git a/packages/block-editor/src/components/block-patterns-list/style.scss b/packages/block-editor/src/components/block-patterns-list/style.scss
index 57dd5893af..534f5a5fa2 100644
--- a/packages/block-editor/src/components/block-patterns-list/style.scss
+++ b/packages/block-editor/src/components/block-patterns-list/style.scss
@@ -14,13 +14,6 @@
 	&[draggable="true"] {
 		cursor: grab;
 	}
-
-	// Solution for "Add "selected" styling to selected pattern in the design selector."
-	// https: //github.com/WordPress/gutenberg/issues/65127
-
-	&.is-selected {
-		border: $border-width solid var(--wp-admin-theme-color);
-	}
 }
 
 .block-editor-block-patterns-list__item {
@@ -52,16 +45,21 @@
 		}
 	}
 
-	&:hover:not(:focus) .block-editor-block-preview__container::after {
-		outline-color: rgba($black, 0.3);
+	&:hover:not( [data-focus-visible] )
+		.block-editor-block-preview__container::after {
+		outline-color: rgba( $black, 0.3 );
 	}
 
-	&:focus .block-editor-block-preview__container::after {
-		outline-color: var(--wp-admin-theme-color);
-		outline-width: var(--wp-admin-border-width-focus);
-		outline-offset: calc((-1 * var(--wp-admin-border-width-focus)));
+	&[data-focus-visible] .block-editor-block-preview__container::after {
+		outline-color: var( --wp-admin-theme-color );
+		outline-width: var( --wp-admin-border-width-focus );
+		outline-offset: calc( ( -1 * var( --wp-admin-border-width-focus ) ) );
 		transition: outline 0.1s linear;
-		@include reduce-motion("transition");
+		@include reduce-motion( 'transition' );
+	}
+
+	&.is-selected .block-editor-block-preview__container::after {
+		background-color: rgba( var( --wp-admin-theme-color--rgb ), 0.04 );
 	}
 
 	.block-editor-patterns__pattern-details:not(:empty) {

```
</details>

I still recommend you go through the commits linked above one by one, to understand a bit better the reason why those changes where made.

Also, you should rebase on top of trunk (or merge trunk into this PR's branch) to make sure you include the latest changes from `trunk`.

I also reworked the styles a bit, so that the selected pattern is now highlighted with a semi-transparent overlay, similarly to what we do in other parts of the app — although I'm not 100% convinced (invoking @WordPress/gutenberg-design and @juanfra for feedback)


https://github.com/user-attachments/assets/5ee894f5-872a-40be-b26c-b3681dfeae0d

**Comment by benazeer-ben** [comment]
Hi @ciampo ,

Thanks for your detailed explanations in the PR. I've incorporated the changes you suggested. However, I wanted to clarify one point you mentioned:

`"No need to add a tabindex=0, Composite already handles that."
`

From my testing, it seems that adding tabindex=0 ensures that the design pattern is highlighted while navigating through the items using the keyboard. Without it, only the first item in the pattern list receives focus.

I've attached a video for reference showing the behavior with and without tabindex=0. Could you please take a look and share your thoughts on this?


https://github.com/user-attachments/assets/5fc56ce9-15e9-4a73-a0b7-32c5fd144e49



Thanks again for your insights!

Best regards,
Benazeer

**Comment by ciampo** [comment]
The list of pattern previews is a composite widget, and as such, users can navigate through its items via arrow keys. See the [`Composite` component](https://wordpress.github.io/gutenberg/?path=/docs/components-composite--docs) and the related [MDN docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/composite_role).

Does that explain it?

---

On a separate node, could you make sure you rebase on top of trunk (or merge trunk into this PR's branch) to make sure you include the latest changes from trunk? Thank you 🙏

File: packages/block-editor/src/components/block-patterns-list/index.js (hunk 4 above)
Comment (ntsekouras) [reply packages/block-editor/src/components/block-patterns-list/index.js]: Thank you for your PR @benazeer-ben!


I should start by saying that the suggestions in that `Design` panel are just patterns that are 'connected' to the current active template with the [templateTypes](https://developer.wordpress.org/news/2023/04/13/using-template-patterns-to-build-multiple-homepage-designs/) prop. 

What this means in practice that when we click on one of the suggestions, the current template's content is only updated and it's just blocks without having any information about patterns etc.. So on refresh there isn't a way to tell if the content was actually inserted before with that mechanism.

There is a similar use case with patterns that we add some metadata in the top level block and use that to perform some actions like shuffle, etc.. That has already some limitations because it also expects these patterns to have a single wrapping block.

Having said that, while we could explore a similar solution here, I'm not sure we should. I think it would be still fragile and dependant on the provided templates and its usage is probably a lot less than the patterns case. I don't have strong opinion though for that and if more folks believe we need that info, let's try it.

Comment (ciampo) [reply packages/block-editor/src/components/block-patterns-list/index.js]: Thank you, Nik!

I propose that we don't try to implement a solution for the time being. And if we even _really_ feel the need for this feature, we should look at it holistically, ie. implementing it in a way that works across all places in the editor.

**Comment by ciampo** [comment]
Also, following [design feedback](https://github.com/WordPress/gutenberg/issues/65127#issuecomment-2422445422), you could apply these changes to tweak focus and hover styles

<details>
<summary>Click to expand</summary>

```diff
diff --git a/packages/block-editor/src/components/block-patterns-list/style.scss b/packages/block-editor/src/components/block-patterns-list/style.scss
index 534f5a5fa2..b7e75754b7 100644
--- a/packages/block-editor/src/components/block-patterns-list/style.scss
+++ b/packages/block-editor/src/components/block-patterns-list/style.scss
@@ -42,24 +42,29 @@
 			outline: $border-width solid rgba($black, 0.1);
 			outline-offset: -$border-width;
 			border-radius: $radius-medium;
+
+			transition: outline 0.1s linear;
+			@include reduce-motion( 'transition' );
 		}
 	}
 
-	&:hover:not( [data-focus-visible] )
-		.block-editor-block-preview__container::after {
+	// Selected
+	&.is-selected .block-editor-block-preview__container::after {
+		outline-color: $gray-900;
+		outline-width: var( --wp-admin-border-width-focus );
+		outline-offset: calc( -1 * var( --wp-admin-border-width-focus ) );
+	}
+
+	// Hover state
+	&:hover .block-editor-block-preview__container::after {
 		outline-color: rgba( $black, 0.3 );
 	}
 
+	// Focused state
 	&[data-focus-visible] .block-editor-block-preview__container::after {
 		outline-color: var( --wp-admin-theme-color );
 		outline-width: var( --wp-admin-border-width-focus );
-		outline-offset: calc( ( -1 * var( --wp-admin-border-width-focus ) ) );
-		transition: outline 0.1s linear;
-		@include reduce-motion( 'transition' );
-	}
-
-	&.is-selected .block-editor-block-preview__container::after {
-		background-color: rgba( var( --wp-admin-theme-color--rgb ), 0.04 );
+		outline-offset: calc( -1 * var( --wp-admin-border-width-focus ) );
 	}
 
 	.block-editor-patterns__pattern-details:not(:empty) {

```
</details>

**Comment by benazeer-ben** [comment]
Hi @ciampo ,

Updated the code with latest style changes. 

Also, the branch enhancement/selected-template-style is up to date with trunk.

Thanks.

**Comment by ciampo** [comment]
> Updated the code with latest style changes.
> 
> Also, the branch enhancement/selected-template-style is up to date with trunk.

Hey @benazeer-ben , thank you for working on it!

Unfortunately, it looks like something didn't go as it should have when updating the branch with latest `trunk`.

I don't seem to have write access to your branch (in your fork), so I can't help with that. If for some reason you can't figure  it out, feel free to open a new PR with the relevant changes.  Alternatively, I can open a PR myself and I will credit you in it.

Let me know!

**Comment by ciampo** [comment]
Hey @benazeer-ben , sorry for the radio silence. I had a couple of things that kept me away from work.

I've rebased your PR, solved a few conflicts, and now I'm going to test changes. Hopefully we can land it soon!

**Review by ciampo — APPROVED** [review]
LGTM 🚀  The new styles follow the feedback shared in https://github.com/WordPress/gutenberg/issues/65127#issuecomment-2422445422

Screenshot 2024-11-27 at 13 01 09

@juanfra , are you ok to merge this PR with the current changes?

**Comment by t-hamano** [comment]
@benazeer-ben Thank you for your work!

> Refresh and check:
> After saving, refresh the page.
> Use Tab and the arrow keys to navigate back to the design section and verify that the previously selected pattern still has the active styling.

This doesn't seem to work properly.

Looking at the code, the selected pattern is [only managed in state](https://github.com/WordPress/gutenberg/pull/65917/files#diff-e24949b00cac037aacf5a314d639f0482c76a108cea05ebb9ad05b45345cf971R197). This means that if we reload the browser or reopen the Design tab, the component will be re-rendered and the pattern will no longer be selected.

Did this issue not occur early on in this PR?

**Comment by benazeer-ben** [comment]
Hi @t-hamano 

Thanks for raising this!

During initial stage, we were  handling this scenarios then based on the some discussions we decided to avoid it.

Please have a look on these discussions in this PR:
https://github.com/WordPress/gutenberg/pull/65917#discussion_r1799863229
https://github.com/WordPress/gutenberg/pull/65917#discussion_r1806588088

Sorry for the confusions that happened from the wrong testing instruction .I have modified the details for testing.

**Comment by t-hamano** [comment]
@benazeer-ben 

Thanks for letting me know this! If the current behavior is what we intended, then it's fine 👍

**Comment by ciampo** [comment]
Hey @t-hamano , thank you for testing! Indeed, we discussed and concluded that we don't currently have a good way to persist and retrieve this information on page reload, and that we should explore a solution (if needed) separately. ([context](https://github.com/WordPress/gutenberg/pull/65917#discussion_r1806588088)).

Based on your positive feedback about the rest of the PR, I'm going to go ahead and merge.

Thank you @benazeer-ben for the collaboration!

**Comment by juanfra** [comment]
Thank you! it's testing nicely to me
