### PR TITLE
Layout Support: Replace incremental IDs with hashes

### LINKED ISSUE #67308: Layout styles are incompatible with Interactivity API client-side navigation
### Description

Blocks relying on [layout styles](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/layout.php), for example Stack, may be corrupted when used with the client-side navigation (in Query Loop).

This happens if for any reason, the number of items displayed initially may grow over time. There are iterative classes applied to the content

Image

generated [in here](https://github.com/WordPress/gutenberg/blob/trunk/lib/block-supports/layout.php#L577-L583). And only those classes with those IDs that are initially displayed are loaded (for example last page that doesn't display all of the posts). Hence if  you change the page to previous one displaying full page of posts, there will be posts with "new" IDs not loaded initially and they will be missing styles.

### Step-by-step reproduction instructions

1. Create new post
2. Add Query Loop block
3. Go to Inspector Controls > Advanced > disable Reload full page (to enable client-side navigation)
4. Add Stack block to Post Template and change some setting, for example align to right. Example:

Image

5. Save and go to frontend
6. Go to the very last page of Query Loop. For bug to occur there should be less posts displayed than the "posts per page". If the last page is full, please change the "posts per page" so the last page displays less posts.
7. Refresh the page (mimicking you just start your flow here)
8. Change the page to previous one

Expected: All the posts have the same layout
Actual: Some posts have broken layout as their styles weren't initially loaded and are not available on the page change

### Screenshots, screen recording, code snippet

Last page. All the posts have right-align layout | Previous page, some posts have broken layout
-- | --
Image | Image

### Environment info

- WordPress 6.7
- Theme: TT5

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by DAreRodz**
## What?

Changes how class names for layout containers are generated, replacing per-block, incrementally-generated IDs with hashes obtained from the layout styles definition.

Will fix https://github.com/WordPress/gutenberg/issues/67308.

## Why?

This currently affects the style of elements outside of router regions, even when navigating between pages generated with the same template, because layout class names depend on the number of blocks rendered using them (see https://github.com/WordPress/gutenberg/pull/67826), which can vary.

## How?

The PR adds a new function named `gutenberg_unique_id_from_values`, which basically generates a short hash from the passed array.

This function is used to generate the layout container class, receiving all the data required to generate the style output. That guarantees hashes to be unique for each layout style combination.

Similar examples can be found in the WordPress codebase already:
- [/src/wp-includes/bookmark.php#L154](https://github.com/WordPress/wordpress-develop/blob/f444639e0852f7c0635a09d0dcee561af22a6515/src/wp-includes/bookmark.php#L154)
- [/src/wp-includes/class-wp-oembed-controller.php#L176](https://github.com/WordPress/wordpress-develop/blob/f444639e0852f7c0635a09d0dcee561af22a6515/src/wp-includes/class-wp-oembed-controller.php#L176)
- [/src/wp-includes/block-supports/elements.php#L19](https://github.com/WordPress/wordpress-develop/blob/f444639e0852f7c0635a09d0dcee561af22a6515/src/wp-includes/block-supports/elements.php#L19)
- [/src/wp-includes/global-styles-and-settings.php#L266](https://github.com/WordPress/wordpress-develop/blob/f444639e0852f7c0635a09d0dcee561af22a6515/src/wp-includes/global-styles-and-settings.php#L266)

## Testing Instructions

1. Create a new post.
2. Add four different groups to test each of the different types: flow, constrained, flex and grid. The layout settings can be found in the right-side panel under the "block" tab. Follow these steps to configure each of the types:
   - Flow: disable "Inner blocks use content width".
   - Constrained: enable "Inner blocks use content width".
   - Flex: transform the Group into a Row or a Stack.
   - Grid: transform the Group into a Grid.
3. For the flow and constrained types, you would have to add more settings in order to generate classes with hashes:
   - Flow: add a custom block spacing in the block styles.
   - Constrained: change justification to left or right.
4. Save and visit the post.
5. Ensure the `div` container for these groups has a class name similar to `wp-container-core-group-is-layout-634f0b9d` (a different hash is OK).
6. Edit the post and duplicate all Group elements. Save and visit the post.
7. Ensure the duplicated Group elements have the same hashes as the original Group elements.
8. Edit the post again, modifying some layout settings in the duplicated elements.
9. Ensure the duplicated Group elements now have different hashes.

## Screenshots or screencast 

|Before|After|
|-|-|
|<video width="480" src="https://github.com/user-attachments/assets/da0ba463-7793-46b2-9d5b-500b2f61739a"></video>|<video width="480" src="https://github.com/user-attachments/assets/d5e6a1db-6ccf-46fb-93d7-e2129c7be0d7"></video>|

### CODE REVIEW

**Comment by talldan** [comment]
Added some potential reviewers for when this is ready.

File: lib/block-supports/layout.php [hunk 1]
```diff
@@ -838,6 +846,25 @@ function gutenberg_render_layout_support_flag( $block_content, $block ) {
...
+				$used_layout,
+				$has_block_gap_support,
+				$gap_value,
+				$should_skip_gap_serialization,
+				$fallback_gap_value,
+				$block_spacing,
+			),
+			'wp-container-' . sanitize_title( $block['blockName'] ) . '-is-layout-'
+		);
+
```
Comment (gziolo) [inline lib/block-supports/layout.php:893]: Looking at the implementation, could the entire code be simplified to:

```php
		// Only add container class and enqueue block support styles if unique styles were generated.
		if ( ! empty( $style ) ) {
			$class_names[] = 'wp-container-' . sanitize_title( $block['blockName'] ) . '-is-layout-' . substr( md5( $style ), 0, 8 );
		}
```

In theory, that approach might also help to avoid running the logic when no class is needed.

Comment (gziolo) [reply lib/block-supports/layout.php:893]: OK, I missed that you must generate the class name before calling `gutenberg_get_layout_style`. That's a limitation as it prevents writing more optimal code. However, using a util to generate a hash based on the params should be good, too.

**Comment by gziolo** [comment]
There are more places where incremental IDs are used. Example for layouts in child blocks. Should the strategy change there as well?

https://github.com/WordPress/gutenberg/blob/9c568adaf34b3a57e9c6811fda0d548b0254c9fc/lib/block-supports/layout.php#L624

File: lib/block-supports/layout.php [hunk 2]
```diff
@@ -582,6 +582,24 @@ function gutenberg_incremental_id_per_prefix( $prefix = '' ) {
...
+ * the generated ID for context or categorization.
+ *
+ * @param array  $data   The input array to generate an ID from.
+ * @param string $prefix Optional. A prefix to prepend to the generated ID. Default ''.
+ *
+ * @return string The generated unique ID for the array.
+ */
+function gutenberg_unique_prefixed_id_from_array( array $data, string $prefix = '' ): string {
+	$serialized = wp_json_encode( $data );
+	$hash       = substr( md5( $serialized ), 0, 8 );
```
Comment (gziolo) [inline lib/block-supports/layout.php:599]: Have you considered using `wp_hash` instead?

```php
$hash = substr( wp_hash( serialize( $data ) ), 0, 8 );
```

It's how it's used in WordPress core in a few places.

File: lib/block-supports/layout.php (hunk 1 above)
Comment (DAreRodz) [reply lib/block-supports/layout.php:893]: Yup, exactly. That's why I decided to compute the hash using all the parameters required to generate `$style` rather than `$style` itself.

File: lib/block-supports/layout.php (hunk 2 above)
Comment (DAreRodz) [reply lib/block-supports/layout.php:599]: Whatever is more "correct" is fine with me, haha. If the standard is to use the second one, I don't mind replacing `md5` with `wp_hash`.

We could also replace `wp_json_encode` with `serialize` (it seems you're also suggesting that, right?). I remember reading that `json_encode` was lighter than `serialize`, so I chose that function. However, I don't have a strong opinion.

**Comment by DAreRodz** [comment]
> There are more places where incremental IDs are used. Example for layouts in child blocks. Should the strategy change there as well?
> 
> https://github.com/WordPress/gutenberg/blob/9c568adaf34b3a57e9c6811fda0d548b0254c9fc/lib/block-supports/layout.php#L624

@gziolo Good catch! Yes, `gutenberg_incremental_id_per_prefix` and `wp_unique_prefixed_id` have the same problem. We should also replace `wp_unique_prefixed_id` calls.

File: lib/block-supports/layout.php (hunk 2 above)
Comment (gziolo) [reply lib/block-supports/layout.php:599]: I'm not entirely sure. I copied a similar usage from the existing codebase. I just shared that to help you make the final decision. The more important aspect might be the need to pass also keys in the array with data in case we would have to change the way class names get generated in other places in the codebase to minimize the risk the same hash is returned for a different set of params that happen to be represented with the same set of values.

**Comment by Mamaduka** [comment]
@westonruter, do you have any thoughts on this proposal? I remember you suggested switching to `wp_unique_id`, which improved performance in specific scenarios.

File: lib/block-supports/layout.php (hunk 2 above)
Comment (westonruter) [reply lib/block-supports/layout.php:599]: Using `wp_hash()` is overkill because it is concerned with cryptographic security, and it combines the hashed value with a secret (to compute an HMAC). If you just want a hash, then `md5()` I think is better because it is faster.

**Comment by westonruter** [comment]
@Mamaduka I fully endorse this proposal! Long ago Gutenberg was using `uniqid()` which was problems because the CSS on the page could not be cached since it was different with every page load (https://github.com/WordPress/gutenberg/issues/38889). So switching to `wp_unique_id()` fixed that problem in that the class names were then stable across page loads. However, creating a class name out of hashed data will be even more stable since changes to the block order then won't matter. So yeah, +1 for using a hash to compute the class name.

Related, the Embed Optimizer plugin in Performance Lab is also using `md5()` in a similar way, except to [create an element ID](https://github.com/WordPress/performance/blob/d21b74d7d12d4a378fe676a29c6e28ef1d0f9dae/plugins/embed-optimizer/class-embed-optimizer-tag-visitor.php#L182) instead of a class name.

File: lib/block-supports/layout.php (hunk 2 above)
Comment (westonruter) [reply lib/block-supports/layout.php:599]: Also, `md5()` will be consistent across all WP installs for a given input which may be important for snapshot testing. If using `wp_hash()` you'd have to make sure the underlying secrets are the same across all testing environments.

File: lib/block-supports/layout.php [hunk 3]
```diff
@@ -582,6 +582,24 @@ function gutenberg_incremental_id_per_prefix( $prefix = '' ) {
...
+ * This function serializes the array into a JSON string and generates a hash
+ * that serves as a unique identifier. Optionally, a prefix can be added to
+ * the generated ID for context or categorization.
+ *
+ * @param array  $data   The input array to generate an ID from.
+ * @param string $prefix Optional. A prefix to prepend to the generated ID. Default ''.
+ *
+ * @return string The generated unique ID for the array.
+ */
+function gutenberg_unique_prefixed_id_from_array( array $data, string $prefix = '' ): string {
```
Comment (Mamaduka) [inline lib/block-supports/layout.php]: Nit (non-blocking): I think we could use a more generic name here, `wp_unique_id_from_values`. Since the prefix is optional, we could also remove it.

File: lib/block-supports/layout.php (hunk 2 above)
Comment (DAreRodz) [reply lib/block-supports/layout.php:599]: Thanks for your input, @westonruter! Let's continue using the `md5` function.

Do you have any insights regarding `wp_json_encode`? Would `serialize` (or `json_encode`) better suit this purpose?

Comment (Mamaduka) [reply lib/block-supports/layout.php:599]: I would check existing examples in core to see which is used most for similar hash patterns. I vaguely remember serialize being faster than json_encode, that might improved in recent PHP versions.

Comment (westonruter) [reply lib/block-supports/layout.php:599]: PHPCS complains if you try using `serialize()` since `unserialize()` can have security problems, although this is only relevant when calling `unserialize()` with untrusted data. WPCS for PHPCS will warn when using `serialize()`:

https://github.com/WordPress/WordPress-Coding-Standards/blob/b8d2089c8c5f372fa72e0d9a726eba72c31ae7db/WordPress/Sniffs/PHP/DiscouragedPHPFunctionsSniff.php#L38-L45

So I think it's better to use `wp_json_encode()`.

Comment (westonruter) [reply lib/block-supports/layout.php:599]: The small size of the data being serialized here most likely makes any performance difference between `serialize()` and `json_encode()` moot.

**Comment by DAreRodz** [comment]
Setting this PR ready for review.

The logic for generating layout styles is complex, so I've added some test cases instead of testing the feature extensively. More test cases are welcome. 🙂

File: lib/block-supports/layout.php (hunk 2 above)
Comment (gziolo) [reply lib/block-supports/layout.php:599]: Excellent feedback @westonruter.

File: phpunit/block-supports/layout-test.php [hunk 4]
```diff
@@ -501,7 +501,47 @@ public function data_layout_support_flag_renders_classnames_on_wrapper() {
 						),
 					),
 				),
-				'expected_output' => '<p class="wp-container-content-1">Some text.</p>', // The generated classname number assumes `wp_unique_prefixed_id( 'wp-container-content-' )` will not have run previously in this test.
+				'expected_output' => '/<p class="wp-container-content-[a-f0-9]{8}">Some text.<\\/p>/',
```
Comment (gziolo) [inline phpunit/block-supports/layout-test.php]: md5 is predictable so it should stay the same between the test runs. What is the reasoning behind using pattern matching here? I expected the tests would ensure that these values don't accidentally change as long as params provided remain the same.

Comment (DAreRodz) [reply phpunit/block-supports/layout-test.php]: No problem. I can change that. I wasn't sure if it would be a good idea to update the tests every time the passed parameters change, but that's not going to happen often, right? 😅

PS: I copied what is being done for the [duotone classes](https://github.com/WordPress/gutenberg/blob/7a90b32cfef27873e2ed069776d9f05d8e37785b/phpunit/class-wp-duotone-test.php#L45) (although, in that case, the IDs might not be predictable).

Comment (DAreRodz) [reply phpunit/block-supports/layout-test.php]: I've just updated the tests to check the generated hashes with their expected values.

File: phpunit/block-supports/layout-test.php [hunk 5]
```diff
@@ -642,61 +642,49 @@ public function data_restore_group_inner_container() {
...
-			// Items are repeated to test hash consistency for the same attributes.
-			array( $attrs1, $attrs1, $attrs2, $attrs2 )
-		);
+			}
+		}
 
-		$this->assertSame( $ids[0], $ids[1] );
-		$this->assertSame( $ids[2], $ids[3] );
-		$this->assertNotSame( $ids[0], $ids[2] );
+		$this->assertSame( $expected_hash, $hash );
```
Comment (gziolo) [inline phpunit/block-supports/layout-test.php]: Can you assert whether output contains `'wp-container-core-group-is-layout-' . $expected_hash`? That would drastically simplify the implementation and potentially provide a similar level of verification.

File: phpunit/block-supports/layout-test.php (hunk 4 above)
Comment (gziolo) [reply phpunit/block-supports/layout-test.php]: Cool, it seems like it's doable for the use cases in this PR. We could leave a note in the tests that the hash might change if the conditions provided get refined in the future.

**Comment by gziolo** [comment]
In my opinion, this PR is shaping up nicely, and my recent comments are mostly stylistic. I don't think I have any major feedback left at this point. I would appreciate some additional review on how the hash is calculated by someone more familiar with layout processing.

File: phpunit/block-supports/layout-test.php (hunk 5 above)
Comment (DAreRodz) [reply phpunit/block-supports/layout-test.php]: Done in https://github.com/WordPress/gutenberg/pull/68210/commits/ed07a177b688995c82533832e198bb01dcb0f0f5

File: lib/block-supports/layout.php (hunk 3 above)
Comment (gziolo) [reply lib/block-supports/layout.php]: I see the name was changed to `gutenberg_unique_id_from_values`. @DAreRodz, can you clarify your intentions regarding the prefix?

File: lib/block-supports/layout.php [hunk 6]
```diff
@@ -838,6 +872,25 @@ function gutenberg_render_layout_support_flag( $block_content, $block ) {
...
+		$container_class = gutenberg_unique_id_from_values(
+			array(
+				$used_layout,
+				$has_block_gap_support,
+				$gap_value,
+				$should_skip_gap_serialization,
+				$fallback_gap_value,
+				$block_spacing,
+			),
+			'wp-container-' . sanitize_title( $block['blockName'] ) . '-is-layout-'
```
Comment (gziolo) [inline lib/block-supports/layout.php:891]: **Not a blocker**: I have a general thought after looking at the generated CSS. The fact that the class name contains the name of the block might be no longer needed. It's currently a general-purpose class that groups similar styles. It might be interesting to explore in the follow-up PR whether the class name prefix can be simplified to the `wp-container-block-is-layout-`. That would be also similar to the child layouts and the `wp-container-content-` prefix.

Screenshot 2025-02-26 at 11 07 00

**Comment by gziolo** [comment]
Overall, everything works as expected on the frontend. PHP code properly generates predictable hashes taking into account how the block is configured. I noticed that the editor uses different algorithm for generating class names. I would expect that JavaScript gets updated to mirror the changes in PHP. Example:

Markup:

```html
<!-- wp:group {"borderColor":"contrast","layout":{"type":"constrained"}} -->
<div class="wp-block-group has-border-color has-contrast-border-color"><!-- wp:paragraph -->
<p>Group</p>
<!-- /wp:paragraph -->

<!-- wp:group {"borderColor":"accent-3","layout":{"type":"default"}} -->
<div class="wp-block-group has-border-color has-accent-3-border-color"><!-- wp:paragraph -->
<p>Nested Group</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"layout":{"columnSpan":2}}} -->
<p>Child layout</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"borderColor":"contrast","layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group has-border-color has-contrast-border-color"><!-- wp:paragraph -->
<p>Row</p>
<!-- /wp:paragraph -->

<!-- wp:group {"borderColor":"accent-3","layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"space-between","orientation":"horizontal"}} -->
<div class="wp-block-group has-border-color has-accent-3-border-color"><!-- wp:paragraph -->
<p>Nested Row</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"layout":{"columnSpan":2}}} -->
<p>Child layout</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"borderColor":"contrast","layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group has-border-color has-contrast-border-color"><!-- wp:paragraph -->
<p>Stack</p>
<!-- /wp:paragraph -->

<!-- wp:group {"borderColor":"accent-3","layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group has-border-color has-accent-3-border-color"><!-- wp:paragraph -->
<p>Nested Row</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"layout":{"columnSpan":2}}} -->
<p>Child layout</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"borderColor":"contrast","layout":{"type":"grid"}} -->
<div class="wp-block-group has-border-color has-contrast-border-color"><!-- wp:paragraph -->
<p>Grid</p>
<!-- /wp:paragraph -->

<!-- wp:group {"borderColor":"accent-3","layout":{"type":"grid","columnCount":null,"minimumColumnWidth":"23rem"}} -->
<div class="wp-block-group has-border-color has-accent-3-border-color"><!-- wp:paragraph -->
<p>Nested Grid</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"layout":{"columnSpan":2}}} -->
<p>Child layout</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```

Editor:

Screenshot 2025-02-26 at 11 22 11

Frontend:

Screenshot 2025-02-26 at 11 25 30

What are your thoughts on these differences `wp-container-content-b5f5adbb` vs `wp-container-content-17`? 

Edit: it looks like there is also `wp-elements-17` that has no styles assigned to it, which isn't present on the front end. I see a similar nuanced difference for the `wp-container-core-group-is-layout-55` in the editor vs the version with hash on the front end.

**Review by fabiankaegy — APPROVED** [review]
From my POV this here is a great fix that works as advertised that we should get into WordPress 6.8. 

I'm about to start the RC for 20.4 which is the last release to make it into 6.8 so ideally I would have wanted to merge this before then. But since it is a bugfix we should be able to still get it in after today. So I'll hold merging and wait a few more days for additional feedback  👍

**Comment by gziolo** [comment]
Fabian, feel free to land it if you confirmed it works correctly. We can discuss my feedback separately as the more I think about it, the less it's of an issue that editors encapsulates the styles under different class names. It doesn't impact visual aspects and developers can't target them anyway.

**Comment by fabiankaegy** [comment]
> Fabian, feel free to land it if you confirmed it works correctly. We can discuss my feedback separately as the more I think about it, the less it's of an issue that editors encapsulates the styles under different class names. It doesn't impact visual aspects and developers can't target them anyway.

Yeah I agree we should align the class name generation in JS to match. But since they are auto generated already and users cannot target them for me the two are separate and one doesn't need to block the other :) 

And yes in my testing this solves the issue it was intended to solve and I am not noticing any regressions on the sample content I have as testing data :)

**Comment by DAreRodz** [comment]
@fabiankaegy, feel free to merge this PR once it's ready. 😊

**Comment by Mamaduka** [comment]
I think aligning class name generation between JS and PHP would be a lovely addition. @DAreRodz, @gziolo, do you have time to work on this?

Considering the bug status of this PR, it should be safe to merge in release betas.

@joemcgill, @desrosj, what do you think?

**Comment by gziolo** [comment]
> I think aligning class name generation between JS and PHP would be a lovely addition. @DAreRodz, @gziolo, do you have time to work on this?

Unfortunately, I don't have the capacity to work on it during the Beta phase.

**Comment by luisherranz** [comment]
> Yeah I agree we should align the class name generation in JS to match. But since they are auto generated already and users cannot target them for me the two are separate and one doesn't need to block the other :)

I agree with Fabian that, although aligning JS class name generation would be a nice addition, it shouldn't block merging this PR.

**Comment by Mamaduka** [comment]
What are the remaining items here? Just aligning JS class name generation? Also, is the core backport PR up to date?

@desrosj, @joemcgill, what do you think about shipping this fix in WP 6.8?

**Comment by joemcgill** [comment]
@Mamaduka

> what do you think about shipping this fix in WP 6.8?

Just confirming what I've [mentioned in Slack](https://wordpress.slack.com/archives/C02QB2JS7/p1741654973935059?thread_ts=1741588973.686649&cid=C02QB2JS7), that I've added [the related Trac issue](https://core.trac.wordpress.org/ticket/62985) to the 6.8 milestone. 

Given that this is a bug fix that can be entirely handled in [WP-develop](https://github.com/WordPress/wordpress-develop/), I don't think including [the PR for WP](https://github.com/WordPress/wordpress-develop/pull/8353) is dependent on this PR being merged first (or at all). I'll leave it to your judgement to decide whether you want to include a this compatibility shim in the plugin to fix this bug for WP versions prior to WP 6.8.

**Comment by Mamaduka** [comment]
Yes, let's merge this ship in the plugin.

@fabiankaegy, @gziolo, do you mind creating an issue for [the client-side followup](https://github.com/WordPress/gutenberg/pull/68210#issuecomment-2684548969)?
