### PR TITLE
`FormTokenField`: Fix focus lost on tab when `__experimentalExpandOnFocus` is set

### LINKED ISSUE #66571: Create Pattern Modal: Tab focus is lost
> [!NOTE]
> This may only be a reproducible issue on Windows OS. Additional testing on Windows OS would be welcome.

### Description

The "Add New Pattern"  modal allows us to select a pattern category that is rendered by the `FormTokenField` component.

When I press the tab key in this pattern category, I would expect the "Synced" toggle to get focus, but instead the modal disappears and focus is lost.

I have not been able to identify the cause, but I suspect it might be an issue that occurs when the Modal component and the FormTokenField component are used together.

This issue appears to have occurred since WP 6.4, when pattern categories were implemented.

### Step-by-step reproduction instructions

- Select "Create pattern" from a block toolbar.
- Press the tab key repeatedly.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/0d22944d-d2e4-4a74-912a-c26f0e4d5a1e

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by yogeshbhutkar**
## What, Why, and How?
Closes #66571

This PR fixes a focus loss issue triggered during `tab` navigation when the `FormTokenField` component is used inside a `Modal`.

The problem arises because, when tabbing, the `SuggestionList` briefly receives focus. This triggers the `onBlur` logic, which collapses the `SuggestionList` prematurely and results in a loss of focus.

To address this, the PR introduces a `keydown` handler for the `Tab` key. This ensures the `SuggestionList` is collapsed before the default `Tab` behaviour is executed, allowing the focus to correctly move to the next focusable element.

## Testing Instructions

1. Create a new post.
2. Insert a paragraph within it.
3. From its Block Toolbar, click on `Options`, then `Create pattern`.
4. Try tabbing through the Modal and confirm that the modal does not close abruptly, and also that the focus is preserved within the modal.

### Testing Instructions for Keyboard
Same.

## Screencast

https://github.com/user-attachments/assets/9dc1f73c-be43-43ef-9436-9ba8cbf1a75a

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

Although this PR works fine, I think this issue is not directly related to the `Modal` component. That is, it is an issue with the component itself that the focus is lost when pressing the Tab key when the `__experimentalExpandOnFocus` property is `true`. So, according to the PR title and changelog entry, some may misunderstand that the issue only occurs in the `Modal` component, so it would be good to fix that.

Another thing worth noting is that this PR changes the behavior when the `__experimentalExpandOnFocus` prop is `false`.

trunk - Pressing the Tab key doesn't close the suggestions list:

https://github.com/user-attachments/assets/eb06ca0f-c4b2-4c0c-9e5b-02fa5cf41f60

This PR - Pressing the Tab key closes the suggestions list:

https://github.com/user-attachments/assets/9b30cbe2-da42-4527-bb36-832270e95a68

The behavior in trunk looks like a bug to me 🤔

File: packages/components/src/form-token-field/index.tsx [hunk 1]
```diff
@@ -383,6 +386,11 @@ export function FormTokenField( props: FormTokenFieldProps ) {
 		return true; // PreventDefault.
 	}
 
+	function handleTabKey( event: KeyboardEvent ) {
+		handleEscapeKey( event );
```
Comment (tyxla) [inline packages/components/src/form-token-field/index.tsx]: Minor nit: Right now, the fact that tab handling uses escape handling is a bit weird. I'd suggest we have a separate helper function for this part:

```js
if ( event.target instanceof HTMLInputElement ) {
	setIncompleteTokenValue( event.target.value );
	setIsExpanded( false );
	setSelectedSuggestionIndex( -1 );
	setSelectedSuggestionScroll( false );
}
```

and then both `handleEscapeKey` and `handleTabKey` would use that, and would just return a different boolean to either prevent or not prevent the default behavior.

**Review by tyxla — APPROVED** [review]
This works well for me 👍 Thanks @yogeshbhutkar!

I'd suggest reorganizing the code a bit differently, but I don't think it is a major blocker for this fix.

**Review by t-hamano — APPROVED** [review]
LGTM 👍
