### PR TITLE
Fix using the classic block in nested contexts

### LINKED ISSUE #13187: Adding a classic block inside a columns block causes a block validation failure.
Hello, I came across an issue with Columns Block when Classic Block is added. Follow the below steps in WordPress Admin to reproduce.

1. Add Columns Block into a page
2. Add Classic Block into one of the columns
3. Add some copy into the Classic Block
4. Save page

The below console error appears
Block validation: Block validation failed for `core/column`
image

Is there a workaround for this issue as this is currently blocking my progress of building a website?

Thanks :)

### PR DESCRIPTION
**Pull request by youknowriad**
At the root level, the classic block omits its delimiters in order to support posts written with alternative editors. In nested contexts though, the classic editor should be rendered with delimiters otherwise the parser won't be able to reparse the post properly.

closes #13187

**Testing instructions**

 - Use a classic block in a columns block
 - Save and refresh
 - Everything should work as intended.

### CODE REVIEW

File: packages/blocks/src/api/serializer.js [hunk 1]
```diff
@@ -280,9 +281,12 @@ export function serializeBlock( block ) {
  * Takes a block or set of blocks and returns the serialized post content.
  *
  * @param {Array} blocks Block(s) to serialize.
+ * @param {Object} options Serialization options.
```
Comment (aduth) [inline packages/blocks/src/api/serializer.js]: We should document these options. I think the "best" way would to define a JSDoc typedef of something like `WPBlockSerializationOptions` with each property described. Unfortunately `docgen` won't yet output these, but it seems prime for a future enhancement.

File: packages/blocks/src/api/serializer.js [hunk 2]
```diff
@@ -255,17 +255,18 @@ export function getCommentDelimitedContent( rawBlockName, attributes, content )
...
  * serialized attributes and content form from the current state of the block.
  *
- * @param {Object} block Block instance.
+ * @param {Object} block   Block instance.
+ * @param {Object} options Serialization options.
  *
  * @return {string} Serialized block.
  */
-export function serializeBlock( block ) {
+export function serializeBlock( block, { isNested = false } = {} ) {
```
Comment (aduth) [inline packages/blocks/src/api/serializer.js]: Nit: I think we should try to consolidate our vocabulary around "inner blocks". Do we have many other references of "nested" in code? I know there's a tendency to refer to them this way in casual conversation. Is `isInnerBlock` reasonable as an alternative here?

File: packages/blocks/src/api/serializer.js [hunk 3]
```diff
@@ -255,17 +255,18 @@ export function getCommentDelimitedContent( rawBlockName, attributes, content )
...
 	const blockName = block.name;
 	const saveContent = getBlockContent( block );
 
-	switch ( blockName ) {
-		case getFreeformContentHandlerName():
-		case getUnregisteredTypeHandlerName():
+	switch ( true ) {
```
Comment (aduth) [inline packages/blocks/src/api/serializer.js]: At this point, I think we'd just not want to bother with a `switch` and use `if` instead. Alternatively, we could intentionally use fallthrough to allow the nested case to fall through to `default`.

```js
switch ( blockName ) {
	case getUnregisteredTypeHandlerName():
		return saveContent;

	case getFreeformContentHandlerName():
		if ( ! isNested ) {
			return saveContent;
		}

	default: {
		const blockType = getBlockType( blockName );
		const saveAttributes = getCommentAttributes( blockType, block.attributes );
		return getCommentDelimitedContent( blockName, saveAttributes, saveContent );
	}
}
```

It's pretty confusing though. Maybe less-so if `default` was just code following the `switch` instead of a case, but still confusing I think.

File: packages/blocks/src/api/serializer.js [hunk 4]
```diff
@@ -255,33 +261,32 @@ export function getCommentDelimitedContent( rawBlockName, attributes, content )
...
  *
- * @param {Object} block   Block instance.
- * @param {Object} options Serialization options.
+ * @param {Object}                      block   Block instance.
+ * @param {WPBlockSerializationOptions} options Serialization options.
  *
  * @return {string} Serialized block.
  */
-export function serializeBlock( block, { isNested = false } = {} ) {
+export function serializeBlock( block, { isInnerBlocks = false } = {} ) {
```
Comment (aduth) [inline packages/blocks/src/api/serializer.js]: Should be singular `isInnerBlock`?

**Edit:** Oh, I guess in the context that this is an option just passed along from `serialize` which is for multiple blocks, it makes sense as written, unless we wanted to rename the option as it applies to the context of the singular block being serialized. I think that comes with its own confusion. I'll leave it to you to judge, but I'm fine either way.

**Review by aduth — APPROVED** [review]
Pretty simple fix 👍

File: packages/blocks/src/api/serializer.js (hunk 4 above)
Comment (youknowriad) [reply packages/blocks/src/api/serializer.js]: I think I'd leave it as is.
