### PR TITLE
Fix: Restrict block insert, move, and replace attending to allowedBlocks, locking, and child blocks

### LINKED ISSUE #10186: Clicking enter when non-textual blocks are selected creates a new paragraph even if not allowed.
Related https://github.com/WordPress/gutenberg/pull/10136#pullrequestreview-158137812

Create a container block where the paragraph block is not allowed 

```js
wp.blocks.registerBlockType('test/container', {
	title: 'container',
	category: 'common',
	description: 'container',
	icon: 'yes',

	edit() {
		return wp.element.createElement(wp.editor.InnerBlocks, {
			allowedBlocks: ['core/image', 'core/gallery']
		});
	},

	save() {
		return wp.element.createElement(wp.editor.InnerBlocks.Content);
	},
})
``` 

 - Add an image block inside this container
 - Select the image placeholder and hit enter
 - A new paragraph block is inserted even if not allowed

### LINKED ISSUE #13099: Blocks not defined in allowedBLocks shuld not be draggable inside
I have registered custom block `N`, passed `allowedBlocks` to `InnerBlocks` and inside the block I can only add what I specified. 

However, after the `N` block I can create something that I did not allowed and drag it inside the `N`. 

Is there anyway to disallow such behaviour?

### LINKED ISSUE #14568: Pressing enter in page title ignores page level template lock and creates paragraph block.
**Describe the bug**
When the enter key is pressed while editing the page title, the editor creates a paragraph at the top of the content, ignoring the post-type level template lock. This paragraph can't be deleted and invalidates the content when next loaded.

**To Reproduce**
1. Setup a template + template_lock for a post type as per https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-templates/#locking
```php
<?php
function myplugin_register_template() {
    $post_type_object = get_post_type_object( 'post' );
    $post_type_object->template = array(
        array( 'core/gallery'),
    );
    $post_type_object->template_lock = 'all';
}
add_action( 'init', 'myplugin_register_template' );
```
2. Go to the post editor
3. type into the title, and press enter
4. A paragraph gets added before the gallery.

**Expected behavior**
Should do either nothing, or focus into the first block in the content.

**Additional context**
- Wordpress version: 5.1.1

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Supersedes: https://github.com/WordPress/gutenberg/pull/7301/files
Uses the select control implemented in https://github.com/WordPress/gutenberg/pull/13924.
This PR changes the action creators to be a generator and have all the required validations before yielding the action.

Fixes: https://github.com/WordPress/gutenberg/issues/14568;
Fixes: https://github.com/WordPress/gutenberg/issues/10186;
Fixes: https://github.com/WordPress/gutenberg/issues/13099;

Missing the update to the unit tests.

## How has this been tested?
Test block: [gist.github.com/jorgefilipecosta/b7194daac3ce26827522694fb4252c1c#file-testallowedblocksmiddleware-js](https://gist.github.com/jorgefilipecosta/b7194daac3ce26827522694fb4252c1c#file-testallowedblocksmiddleware-js)

I pasted the test block referred in the browser console.
I added the Product block.
I verified I cannot move using drag & drop the Buy button out of the Product block. (child block restriction.
I verified I cannot move using drag & drop a paragraph created outside of the Product block inside the product block. (allowed blocks restriction).
I verified that if I press enter in the buy button or image inside the product block, a paragraph is not created (allowed blocks restriction).
I added two galleries outside the product block, multi-selected them, and copied them ( ctrl + c ), I pasted them inside the list block inside the Product block and I verified they were not added (allowed blocks restriction).

I verified that when we have a template lock and we press enter on the title we now do not insert unallowed blocks.
Template lock code:

```
add_filter( 'allowed_block_types', function( $allowed_block_types, $post ) {
	if ( $post->post_type === 'post' ) {
	    return $allowed_block_types;
	}
	return [ 'core/image', 'core/button' ];
}, 10, 2 );
```
I verified that if we disable the paragraph, e.g., with a filter or inside the test block, pressing enter on the title or in placeholders does not add paragraph blocks. Pressing the sibling inserter also does not insert the paragraph (PR #7226).
Code to disable paragraph:

```
function myplugin_register_book_lock_post_type() {
    $args = array(
        'public' => true,
	  	'template_lock' => 'all',
        'label'  => 'Books Lock',
        'show_in_rest' => true,
        'template' => array(
            array( 'core/image', array(
            ) ),
            array( 'core/heading', array(
                'placeholder' => 'Add Author...',
            ) ),
            array( 'core/paragraph', array(
                'placeholder' => 'Add Description...',
            ) ),
        ),
    );
    register_post_type( 'book_lock', $args );
}
add_action( 'init', 'myplugin_register_book_lock_post_type' );
```
I added two image blocks, multi-selected them, copied them and tried to paste them on the list inside the test block. I checked the image blocks were not added inside the test block.

All these actions are possible in master.

Todo: If we accept this approach, end 2 end tests will be created before the merge that replicate this manual tests.

### CODE REVIEW

File: packages/block-editor/src/store/actions.js [hunk 1]
```diff
@@ -248,61 +300,139 @@ export const moveBlocksDown = createOnMove( 'MOVE_BLOCKS_DOWN' );
...
-		time: Date.now(),
-		updateSelection,
-	};
+ * @param {Object[]} blocks                        Block objects to insert.
+ * @param {?number}  index                         Index at which block should be inserted.
+ * @param {?string}  rootClientId                  Optional root client ID of block list on which to insert.
+ * @param {?boolean} updateSelection               If true block selection will be updated.  If false, block selection will not change. Defaults to true.
+ * @param {?boolean} ignoreAllowedBlocksValidation If true the block will be inserted even if the insertion was not allowed e.g: because of allowed blocks restrictions.
+ */
+export function* insertBlocks(
```
Comment (gziolo) [inline packages/block-editor/src/store/actions.js]: It might be easier to introduce a new action `replaceInnerBlocks` which will skip validation by duplicating some logic from the existing methods rather than increasing the complexity of the existing actions by introducing another boolean param. It also seems like this new param is a special case required only to keep inner blocks working as before.

File: packages/block-editor/src/store/actions.js [hunk 2]
```diff
@@ -201,16 +220,41 @@ export function toggleSelection( isSelectionEnabled = true ) {
...
+export function* replaceBlocks( clientIds, blocks ) {
+	clientIds = castArray( clientIds );
+	blocks = castArray( blocks );
+	const rootClientId = yield select(
+		'core/block-editor',
+		'getBlockRootClientId',
+		first( clientIds )
+	);
+	// Replace is valid if the new blocks can be inserted in the root block
+	// or if we had a block of the same type in the position of the block being replaced.
```
Comment (aduth) [inline packages/block-editor/src/store/actions.js]: >or if we had a block of the same type in the position of the block being replaced.

Is there an occasion of this you had in mind that led you to implement this exception? It's not clear to me for what reason we'd want it, and it adds some complexity to the implementation.

Comment (jorgefilipecosta) [reply packages/block-editor/src/store/actions.js]: Hi @aduth,
Initially, I followed your suggestion, but on a second thought, I think the condition has some benefits for the merging of blocks.
In the following gist we see a sample block with InnerBlocks:
https://gist.github.com/jorgefilipecosta/6d8c1620b46d916d8a16a23e730a2ab6


If we have this condition the user can merge paragraphs by pressing backspace or delete. Without this condition, merge is not possible. But the same result is possible to achieve by removing a paragraph and appending its content to the content of another paragraph -- So I think merging should be possible.

**Comment by jorgefilipecosta** [comment]
This PR was updated after the PR's it depended on were merged and is ready for a new look.

**Comment by aduth** [comment]
Noting some overlap between this and #14594 , cc @nerrad

File: packages/block-editor/src/store/actions.js [hunk 3]
```diff
@@ -201,16 +220,41 @@ export function toggleSelection( isSelectionEnabled = true ) {
  *
  * @param {(string|string[])} clientIds Block client ID(s) to replace.
  * @param {(Object|Object[])} blocks    Replacement block(s).
- *
- * @return {Object} Action object.
```
Comment (aduth) [inline packages/block-editor/src/store/actions.js]: `@yields` is available as a valid substitute in JSDoc.

http://usejsdoc.org/tags-yields.html

File: packages/block-editor/src/store/actions.js (hunk 2 above)
Comment (aduth) [reply packages/block-editor/src/store/actions.js]: > In the following gist we see a sample block with InnerBlocks:
> https://gist.github.com/jorgefilipecosta/6d8c1620b46d916d8a16a23e730a2ab6

This seems like an invalid use of InnerBlocks, by the fact the template contains blocks not valid per `allowedBlocks`. At the very least, we shouldn't optimize to anticipate this use-case.

File: packages/block-editor/src/store/actions.js [hunk 4]
```diff
@@ -258,14 +302,48 @@ export const moveBlocksUp = createOnMove( 'MOVE_BLOCKS_UP' );
...
+	const canInsertBlock = yield select(
+		'core/block-editor',
+		'canInsertBlockType',
+		blockName,
+		toRootClientId
+	);
+
+	// If moving to other parent block, the move is possible if we can insert a block of the same type inside the new parent block.
+	if ( canInsertBlock ) {
+		return action;
```
Comment (aduth) [inline packages/block-editor/src/store/actions.js]: Should we `yield`, not `return`? Unclear to me what behavior is expected from `redux-routine` for the `return`.

File: packages/block-editor/src/store/actions.js (hunk 1 above)
Comment (aduth) [reply packages/block-editor/src/store/actions.js]: > It might be easier to introduce a new action `replaceInnerBlocks` which will skip validation by duplicating some logic from the existing methods rather than increasing the complexity of the existing actions by introducing another boolean param. It also seems like this new param is a special case required only to keep inner blocks working as before.

Had you considered this feedback, @jorgefilipecosta ?

File: packages/block-editor/src/store/actions.js [hunk 5]
```diff
@@ -292,17 +380,39 @@ export function insertBlock( block, index, rootClientId, updateSelection = true
...
+export function* insertBlocks(
+	blocks,
+	index,
+	rootClientId,
+	updateSelection = true
+) {
+	blocks = castArray( blocks );
+	const allowedBlocks = [];
+	for ( const block of blocks ) {
+		if ( block ) {
```
Comment (aduth) [inline packages/block-editor/src/store/actions.js]: Why are there falsey entries in `blocks` ?

File: packages/block-editor/src/store/actions.js (hunk 2 above)
Comment (jorgefilipecosta) [reply packages/block-editor/src/store/actions.js]: Hi @aduth there are InnerBlocks scenarios where I expect this situation to happen.
For example, I just want to allow a maximum of 3 headings inside my InnerBlocks area. The way to implement this restriction would be remove heading from the allowed blocks if we already have 3 headings.

Comment (jorgefilipecosta) [reply packages/block-editor/src/store/actions.js]: But I agree even this last scenario I referred is not normal and maybe something we should not optimize for.
I thought replacements would be needed to paste a block in the same position as an existing block. Paste HTML heading in a heading block, but that's not the case. I will reflect a little bit to make sure I'm not missing anything but I find don't any "normal" case I will simplify the logic.

File: packages/block-editor/src/store/actions.js (hunk 5 above)
Comment (jorgefilipecosta) [reply packages/block-editor/src/store/actions.js]: I guess it is never falsey, I updated the code to remove this check.

File: packages/block-editor/src/store/actions.js (hunk 1 above)
Comment (jorgefilipecosta) [reply packages/block-editor/src/store/actions.js]: Hi @aduth yes I followed this suggestion and the new action was already merged.

**Comment by jorgefilipecosta** [comment]
Hi @aduth thank you for the review, I updated the code to follow your suggestions.

**Review by aduth — APPROVED** [review]
A few questions, but functionally this works well in my testing.

Your "fixes" syntax from the original comment will not auto-close all the related issues. It would need to be separate individual "Fixes" one-per-line.

File: packages/block-editor/src/store/actions.js [hunk 6]
```diff
@@ -256,16 +296,51 @@ export const moveBlocksUp = createOnMove( 'MOVE_BLOCKS_UP' );
...
+	}
+
+	const action = {
 		type: 'MOVE_BLOCK_TO_POSITION',
 		fromRootClientId,
 		toRootClientId,
 		clientId,
 		index,
 	};
+	// If moving inside the same root block the move is always possible.
```
[the remark this answers is not in the document]
Comment (jorgefilipecosta) [reply packages/block-editor/src/store/actions.js]: Hi @aduth although this could be seen as optimization as the majority of cases will return here, this is also required.
The case this covers is locking=insert, in that case, we can not insert blocks but we can move the blocks, canInsertBlockType will return false but the move is in fact possible. Without this condition when locking = insert we would not be able to move the blocks as expected.

File: packages/block-editor/src/store/actions.js [hunk 7]
```diff
@@ -256,16 +296,51 @@ export const moveBlocksUp = createOnMove( 'MOVE_BLOCKS_UP' );
...
-export function moveBlockToPosition( clientId, fromRootClientId, toRootClientId, index ) {
-	return {
+export function* moveBlockToPosition( clientId, fromRootClientId, toRootClientId, index ) {
+	const templateLock = yield select(
+		'core/block-editor',
+		'getTemplateLock',
+		fromRootClientId
+	);
+
+	// If locking is equal to all on the original clientId (fromRootClientId),
```
[the remark this answers is not in the document]
Comment (jorgefilipecosta) [reply packages/block-editor/src/store/actions.js]: Yes, we need this condition -- If the user is moving the block from a parent with locking=all to a block without locking, canInsertBlockType will return true, but the move is not possible.

**Comment by jorgefilipecosta** [comment]
Thank you for the reviews, if there is anything I missed feel free to comment and I will iterate on this.
