### PR TITLE
Fix inserter with block pattern categories

### LINKED ISSUE #27249: Block Patterns without a category crashes the block editor
**Describe the bug**

Accessing a registered block pattern that has doesn't have a categories objects crashes the block editor. 

According to the [existing documentation](https://developer.wordpress.org/block-editor/developers/block-api/block-patterns/) , a category is not required. 

If categories is now required; it needs to be documented at https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/block-api/block-patterns.md

**To reproduce**
1. place this block pattern in your functions.php file. 

```
register_block_pattern(
	'skorasaurus/test-case-block-pattern',
	array(
		'title'       => __( 'a simple heading', 'what should this be' ),
		'description' => _x( 'mmm..cake', ' this is slang and has more nuance in english', ''),
		'content'     => '<!-- wp:heading -->
		<h2>The history of cake</h2>
		<!-- /wp:heading -->',
	)
);
```

2. create a new post or page in block-editor
3. Go to the patterns tab
4. "The editor has encountered an unexpected error." appears; and in console, the following:

```
Uncaught TypeError: t.categories is undefined
    s https://local.wordpress.test/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=fdb8c27842d6665c8f717ab07efd9458:30
    s https://local.wordpress.test/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=fdb8c27842d6665c8f717ab07efd9458:30
    s https://local.wordpress.test/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=fdb8c27842d6665c8f717ab07efd9458:30
    mountMemo https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:15577
    useMemo https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:15873
    useMemo https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react.af754d50.js:1607
    is https://local.wordpress.test/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=fdb8c27842d6665c8f717ab07efd9458:30
    renderWithHooks https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:14938
    mountIndeterminateComponent https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:17617
    beginWork https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:18731
    callCallback https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:182
    invokeGuardedCallbackDev https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:231
    invokeGuardedCallback https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:286
    beginWork$1 https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:23338
    performUnitOfWork https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:22289
    workLoopSync https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:22265
    performSyncWorkOnRoot https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:21891
    flushSyncCallbackQueueImpl https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:11224
    unstable_runWithPriority https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react.af754d50.js:2685
    runWithPriority$1 https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:11174
    flushSyncCallbackQueueImpl https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:11219
    flushSyncCallbackQueue https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:11207
    discreteUpdates$1 https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:22028
    discreteUpdates https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:803
    dispatchDiscreteEvent https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:4291
```

**Expected behavior**
The block pattern to load.

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", 
- If the Gutenberg plugin is installed, which version is it? 9.4.1

I was also able to replicate this with wordpress 5.6 and Gutenberg 9.5.2.

I was able to reproduce this in [Gutenberg 9.1.0](https://github.com/WordPress/gutenberg/releases/tag/v9.1.0); I was not able to reproduce this in Gutenberg 9.0.0

### PR DESCRIPTION
**Pull request by youknowriad**
closes #27249 

Right now, if there are no registered pattern categories and a pattern available without any category, it breaks the patterns inserter. This PR fixes by improving the logic to add the "uncategorized" category.

**Testing instructions**

Add the following code somewhere:

```
remove_theme_support('core-block-patterns');
register_block_pattern(
	'skorasaurus/test-case-block-pattern',
	array(
		'title'       => __( 'a simple heading', 'what should this be' ),
		'description' => _x( 'mmm..cake', ' this is slang and has more nuance in english', ''),
		'content'     => '<!-- wp:heading -->
		<h2>The history of cake</h2>
		<!-- /wp:heading -->',
	)
);
```

 - Open the pattern inserter
 - The editor shouldn't break

### CODE REVIEW

File: packages/block-editor/src/components/inserter/block-patterns-tab.js [hunk 1]
```diff
@@ -28,43 +28,52 @@ function BlockPatternsCategory( {
...
-					)
-				)
-				.sort( ( { name: currentName }, { name: nextName } ) => {
-					if ( ! [ currentName, nextName ].includes( 'featured' ) ) {
-						return 0;
-					}
-					return currentName === 'featured' ? -1 : 1;
-				} ),
-		[ allPatterns, allCategories ]
+	const hasCategory = useCallback(
```
Comment (ntsekouras) [inline packages/block-editor/src/components/inserter/block-patterns-tab.js]: Would renaming to `hasRegisteredCategory` be more fitting here? 🤔

**Review by ntsekouras — APPROVED** [review]
Looks good, thanks Riad!
