### PR TITLE
iAPI: fix unexpected browser warning for withSyncEvent() wrapper

### LINKED ISSUE #69975: Interactivity API shows incorrect deprecation warning in 6.8 when Gutenberg plugin not active
### Description

Description:
The Interactivity API shows a deprecation warning in WordPress 6.8 `(Using the synchronous event.preventDefault() function in a store action without wrapping it in withSyncEvent() is deprecated and will stop working in WordPress 6.9. Please wrap the store action in withSyncEvent().)` even when:

The action is properly wrapped in` withSyncEvent()`

Following all documented best practices

The warning disappears when [Gutenberg plugin](https://wordpress.org/plugins/gutenberg/) is active

This contradicts the [Interactivity API best practices post](https://make.wordpress.org/core/2025/03/24/interactivity-api-best-practices-in-6-8/) which states these warnings shouldn't appear in 6.8.

### Step-by-step reproduction instructions

1. Install fresh WordPress 6.8 (without Gutenberg plugin)
2. Enable a block using Interactivity API navigation (like Query Loop with enhanced pagination)
3. Open browser console
4. Click on pagination links
5. Observe deprecation warning

### Expected Behavior:

- No deprecation warnings should appear in WordPress 6.8 when:

- Using withSyncEvent() properly

- Following documented best practices

- Consistent behavior between core and plugin versions

### Actual Behavior:

- Warning appears in WordPress 6.8 core

- Warning disappears when Gutenberg plugin is active

- Warning appears even in correct implementations

### Screenshots, screen recording, code snippet

https://drive.google.com/file/d/1hnftbr0Xg8phYXNFHDis-A5giIbB5wT5/view?usp=sharing

### Environment info

- Affected version: WordPress 6.8
- Components affected:
  -  Interactivity API runtime
  -  Router implementation
- Console warning: `Using the synchronous event.preventDefault() function in a store action without wrapping it in withSyncEvent() is deprecated and will stop working in WordPress 6.9. Please wrap the store action in withSyncEvent().`

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by t-hamano**
Closes #69975
Related to #68097

## What?
This PR fixes an issue where a browser warning occurs even when the `withSyncEvent` action wrapper is used correctly in iAPI.

## Why?

As I understand it, the property that is added to the function itself, i.e. the `sync` field, is lost by the code below:

```javascript
const functionResult = value( ...functionArgs );
```

Here, the result of the function execution is obtained as a variable, so any unique properties that the function originally had are not inherited.

Therefore, consumers have no way to avoid the browser warning even if they use the `withSyncEvent` action wrapper correctly.

## How?

Create a wrapper function and preserve the original `sync` property there. However, there are two concerns with this approach:

- If we have a negative operator, the `sync` property will not be preserved. Negative operators are deprecated, but do we need to add the same processing?
- Custom properties other than the `sync` property will not be preserved.

If we want to inherit all the custom properties from the original function, the following approach might be possible:

<details><summary>Details</summary>

```javascript

export const getEvaluate: GetEvaluate =
	( { scope } ) =>
	// TODO: When removing the temporarily remaining `value( ...args )` call below, remove the `...args` parameter too.
	( entry, ...args ) => {

		if ( typeof value === 'function' ) {
			//...

			// Reset scope before return and wrap the function so it will still run within the correct scope.
			resetScope();
			const wrappedFunction: SyncAwareFunction = (
				...functionArgs: any[]
			) => {
				setScope( scope );
				const functionResult = value( ...functionArgs );
				resetScope();
				return functionResult;
			};

			// Preserve all properties from the original function.
			Object.setPrototypeOf(
				wrappedFunction,
				Object.getPrototypeOf( value )
			);
			Object.defineProperties(
				wrappedFunction,
				Object.getOwnPropertyDescriptors( value )
			);
			return wrappedFunction;
		}

		// ...
	};
```

</details> 

Please advise if there are any other good approaches.

## Testing Instructions

Inserts a button-only style Search button:

```html
<!-- wp:search {"label":"Search","buttonText":"Search","buttonPosition":"button-only","isSearchFieldHidden":true} /-->
```

Click the button on the front end and verify that **no errors are displayed** in the browser.

Unwrap the `openSearchInput` action. Click a button on the front end and see **the error displayed** in the browser.

```diff
diff --git a/packages/block-library/src/search/view.js b/packages/block-library/src/search/view.js
index 617e179b1d..be1725e825 100644
--- a/packages/block-library/src/search/view.js
+++ b/packages/block-library/src/search/view.js
@@ -36,7 +36,7 @@ const { actions } = store(
                        },
                },
                actions: {
-                       openSearchInput: withSyncEvent( ( event ) => {
+                       openSearchInput: ( event ) => {
                                const ctx = getContext();
                                const { ref } = getElement();
                                if ( ! ctx.isSearchInputVisible ) {
@@ -44,7 +44,7 @@ const { actions } = store(
                                        ctx.isSearchInputVisible = true;
                                        ref.parentElement.querySelector( 'input' ).focus();
                                }
-                       } ),
+                       },
                        closeSearchInput() {
                                const ctx = getContext();
                                ctx.isSearchInputVisible = false;
```

### CODE REVIEW

**Comment by t-hamano** [comment]
Since the 6.8 RC1 release is just around the corner, let's punt this PR to 6.9.

File: packages/interactivity/src/hooks.tsx [hunk 1]
```diff
@@ -257,12 +257,19 @@ export const getEvaluate: GetEvaluate =
 			}
 			// Reset scope before return and wrap the function so it will still run within the correct scope.
 			resetScope();
-			return ( ...functionArgs: any[] ) => {
+			const wrappedFunction: SyncAwareFunction = (
+				...functionArgs: any[]
+			) => {
```
Comment (felixarntz) [inline packages/interactivity/src/hooks.tsx]: Small nit: I'm slightly wary of any side effects from typing this function unconditionally, even if the function isn't supposed to be `sync`.

Maybe safer to only do this `if ( value.sync )`?

I think you could assign it to an untyped variable here, and later reassign it, but only `if ( value.sync )`. This could be in the same clause where you actually set `wrappedFunction.sync = true`.

**Review by felixarntz — APPROVED** [review]
@t-hamano Overall this looks right.

One suggestion that feels slightly more appropriate, but probably shouldn't be a blocker.

File: packages/interactivity/src/hooks.tsx (hunk 1 above)
Comment (t-hamano) [reply packages/interactivity/src/hooks.tsx]: Thanks for the review! Updated in 0e4ec891d2d1cff552554819a349e0c04932acd3
