### PR TITLE
Fix entity deletion in widgets screen

### LINKED ISSUE #31263: Widgets editor: Deleting a block should delete it, not move it to Inactive Widgets
## Description
Right now if you delete a block in the Widgets editor screen then that widget will be moved to the Inactive Widgets area. It should be deleted permanently.

## Step-by-step reproduction instructions
1. Navigate to Appearance → Widgets.
2. Delete a block from a widget area.
3. Press _Save_.
4. Refresh the page.
5. Expand Inactive Widgets.

## Expected behaviour
The block you deleted should not be there.

## Actual behaviour
It's there!

### PR DESCRIPTION
**Pull request by tellthemachines**
## Description

Fixes #31263. 
Also fixes issue where saving edits twice without reloading the page created new blocks instead of changing the existing ones.

Adds `__internalWidgetId` to all blocks on save; checks for removed blocks and calls `deleteEntityRecord` on them.

## How has this been tested?

Tested in widgets screen: 
1. Add two blocks
2. Save page
3. Delete one of the blocks
4. Save and reload
5. Check deleted widget doesn't appear in the Inactive widgets section

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/edit-widgets/src/store/actions.js [hunk 1]
```diff
@@ -101,6 +101,11 @@ export function* saveWidgetArea( widgetAreaId ) {
 		buildWidgetAreaPostId( widgetAreaId )
 	);
 
+	// Get all widgets from this area
+	const areaWidgets = Object.values( widgets ).filter(
```
Comment (noisysocks) [inline packages/edit-widgets/src/store/actions.js:105]: Is `Object.values` necessary? I think that the `getWidgets()` selector already returns an array.

File: packages/edit-widgets/src/store/actions.js [hunk 2]
```diff
@@ -113,6 +118,17 @@ export function* saveWidgetArea( widgetAreaId ) {
...
 	} );
 
+	// Get all widgets that have been deleted
+	const deletedWidgets = areaWidgets.filter( ( widget ) => {
+		const { id } = widget;
+		return (
+			widgetsBlocks.findIndex(
+				( { attributes: { __internalWidgetId } } ) =>
+					__internalWidgetId === id
+			) === -1
```
Comment (noisysocks) [inline packages/edit-widgets/src/store/actions.js]: Nit: It's clearer (or maybe just more common?) I think to use `! widgetsBlocks.some(...)` instead of `widgetsBlocks.findIndex(...) === -1`.

File: packages/edit-widgets/src/store/actions.js [hunk 3]
```diff
@@ -113,6 +118,17 @@ export function* saveWidgetArea( widgetAreaId ) {
 		return true;
 	} );
 
+	// Get all widgets that have been deleted
+	const deletedWidgets = areaWidgets.filter( ( widget ) => {
+		const { id } = widget;
```
Comment (noisysocks) [inline packages/edit-widgets/src/store/actions.js]: Nit: Could remove this line and do the destructuring in the function's arguments.

File: packages/edit-widgets/src/store/actions.js [hunk 4]
```diff
@@ -168,15 +184,32 @@ export function* saveWidgetArea( widgetAreaId ) {
 			clientId: block.clientId,
 		} );
 	}
+	for ( let i = 0; i < deletedWidgets.length; i++ ) {
```
Comment (noisysocks) [inline packages/edit-widgets/src/store/actions.js]: Since we're not using `i` outside of `deletedWidgets[ i ]`, this can be a `for ... of` loop.

**Review by noisysocks — APPROVED** [review]
Works great! Only some minor comments.

File: packages/edit-widgets/src/store/actions.js (hunk 1 above)
Comment (tellthemachines) [reply packages/edit-widgets/src/store/actions.js:105]: It's an object with `id` as key and the widget as value.
