### PR TITLE
Firefox: fix disappearing toolbar

### LINKED ISSUE #25526: Block toolbar disappears when hovering over it in Firefox
**To reproduce**
1. Open the post editor
2. Ensure 'Top toolbar' mode is disabled
3. Add a block, any block
4. Try interacting with the block toolbar
5. Observe the block toolbar disappears

**Expected behavior**
The block toolbar stays visible

**Screenshots**
toolbar

Observed in `master` (latest commit was d2dfcffab6b75043d92c4a389a795816e4592210), using Mac OS Firefox

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #25526.

The cause of this bug is the switch from a React synthetic event to a native event. It seems that the `buttons` property didn't work correctly in the past for Firefox, but it works correctly for the native event.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by aristath — APPROVED** [review]
LGTM. Tested on Ubuntu using Firefox, it now works as expected :+1:

**Review by ZebulanStanphill — APPROVED** [review]
Thanks for getting on this so quickly, @ellatrix! And thanks for spotting and reporting, @talldan and @aristath.

Tested on KDE Neon with Firefox 80.0.1. Also tested on Chromium to make sure it's still working there. Everything seems to be working correctly again!

There's a failing test in the Static Analysis GitHub action:
```
[1] /home/runner/work/gutenberg/gutenberg/packages/block-library/src/navigation/index.js
[1]   24:18  error  Replace `·'A·collection·of·blocks·that·allow·visitors·to·get·around·your·site.'·` with `⏎↹↹'A·collection·of·blocks·that·allow·visitors·to·get·around·your·site.'⏎↹`  prettier/prettier
```

However, it's just a formatting issue that is totally unrelated to this PR. So we should merge this as soon as it lets us.

**Comment by ZebulanStanphill** [comment]
(I think it just needs a rebase.)

File: packages/block-editor/src/components/block-list/block-wrapper.js [hunk 1]
```diff
@@ -203,13 +203,11 @@ export function useBlockWrapperProps( props = {}, { __unstableIsHtml } = {} ) {
...
 		}
 
-		function onMouseLeave( { which, buttons } ) {
-			// The primary button must be pressed to initiate selection. Fall back
-			// to `which` if the standard `buttons` property is falsy. There are
-			// cases where Firefox might always set `buttons` to `0`.
+		function onMouseLeave( { buttons } ) {
+			// The primary button must be pressed to initiate selection.
 			// See https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons
 			// See https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/which
```
Comment (ZebulanStanphill) [inline packages/block-editor/src/components/block-list/block-wrapper.js:209]: I think this link can be removed since it's no longer relevant.

Comment (ZebulanStanphill) [reply packages/block-editor/src/components/block-list/block-wrapper.js:209]: I made a separate PR for this: #25589.
