### PR TITLE
FIX: Remove image resizing on mobile

### LINKED ISSUE #2675: Remove image resizing on mobile
The experience of resizing an image in my iPhone 7 Plus testing wasn't great. I would suggest for now, we remove this functionality on mobile. We can test if we have to also on iPad/tablets.

img_1442

### PR DESCRIPTION
**Pull request by tg-ephox**
## Description

fixes https://github.com/WordPress/gutenberg/issues/2675

## How Has This Been Tested?

Manual testing on devices

## Types of changes

Bug fix - Image resizing disabled on extra small devices (< 768px)
## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by codebykat** [comment]
Hmm. I just tested this on both iPhone 7 and iPhone 7 Plus, but I can still resize images on this branch. I still see the blue corner handles and can drag them to change the image size (well, not consistently, but as well as in master).

File: utils/viewport.js [hunk 1]
```diff
@@ -0,0 +1,3 @@
+export function isExtraSmall() {
+	return window && window.innerWidth < 768;
```
Comment (youknowriad) [inline utils/viewport.js]: We have a similar check in `editor/state/store-defaults.js` we should be consistent, I think.

File: editor/store-defaults.js [hunk 2]
```diff
@@ -1,7 +1,9 @@
+import { viewPort } from '../utils';
```
Comment (aduth) [inline editor/store-defaults.js]: We shouldn't traverse into another top-level directory like this, and should instead treat is as a "WordPress dependency", i.e.:

```js
/**
 * WordPress dependencies
 */
import { viewPort } from '@wordpress/utils';
```
