### PR TITLE
Only check MediaPlaceholder allowedTypes array length if prop exists

### LINKED ISSUE #11692: MediaPlaceholder component errors when allowedTypes is not set.
**Describe the bug**

When the `MediaPlaceholder` component is used and no `allowedTypes` property is provided, the component throws an error because it tries to access `.length` on an `undefined` value.

**To Reproduce**
1. Create a custom block with the `edit()` method 
2. Attempt to insert your custom block into the editor
3. Observe "The block has encountered an error and cannot be previewed" message.
4. Observe a `TypeError: Cannot read property 'length' of undefined` in the console.

**Expected behavior**
The `MediaUpload` component [specifies that `allowedTypes` an optional property](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/media-upload/README.md#allowedtypes); I would therefore expect `MediaPlaceholder` to behave the same, especially given that there is already code to check whether `allowedTypes` is unset elsewhere in `MediaPlaceholder`.

**Screenshots**

**Desktop (please complete the following information):**
- Ubuntu 18.04 / Chrome 70

**Additional context**
- Gutenberg version: **master**

### PR DESCRIPTION
**Pull request by kadamwhite**
## Description
Adds an existence check to `allowedTypes` before attempting to access `allowedTypes.length` to fix #11692.

## How has this been tested?
- tested this patch against three custom blocks which utilize `MediaPlaceholder` without `allowedTypes` and confirmed that in all cases the patch allows these custom blocks to load as they did several weeks ago.
- introduced a basic unit test to catch the bug described in the issue

## Types of changes
Bug fix: Add an undefined/null check to an array before accessing `.length`.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] N/A ~~My code follows the accessibility standards.~~ 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: packages/editor/src/components/media-placeholder/index.js [hunk 1]
```diff
@@ -142,7 +142,7 @@ class MediaPlaceholder extends Component {
 		let instructions = labels.instructions || '';
 		let title = labels.title || '';
 		if ( ! instructions || ! title ) {
-			const isOneType = 1 === allowedTypes.length;
+			const isOneType = 1 === allowedTypes && allowedTypes.length;
```
Comment (ocean90) [inline packages/editor/src/components/media-placeholder/index.js]: You probably wanted to do this:

```suggestion
			const isOneType = allowedTypes && 1 === allowedTypes.length;
```

Comment (ocean90) [reply packages/editor/src/components/media-placeholder/index.js]: What do you think about [defining `allowedTypes`](https://github.com/WordPress/gutenberg/blob/fe51bd08684462690988de7ec61a3cdda083710a/packages/editor/src/components/media-placeholder/index.js#L134) as an empty array by default?

Comment (kadamwhite) [reply packages/editor/src/components/media-placeholder/index.js]: Right you are on the boolean :man_facepalming: And I considered initializing `allowedTypes` to `[]` in the destructuring assignment, but then backed off because we do a `if ( ! this.props.allowedTypes )` check elsewhere. Upon reflection, since the default initialization won't mutate the value of the prop, the two approaches aren't incompatible and I think your suggestion's the way to go. Will push a commit momentarily.

File: packages/editor/src/components/media-placeholder/index.js [hunk 2]
```diff
@@ -142,7 +142,7 @@ class MediaPlaceholder extends Component {
 		let instructions = labels.instructions || '';
 		let title = labels.title || '';
 		if ( ! instructions || ! title ) {
-			const isOneType = 1 === allowedTypes.length;
+			const isOneType = allowedTypes.length;
```
Comment (ocean90) [inline packages/editor/src/components/media-placeholder/index.js]: The check needs to stay :)

**Review by ocean90 — CHANGES_REQUESTED** [review]

File: packages/editor/src/components/media-placeholder/index.js (hunk 2 above)
Comment (kadamwhite) [reply packages/editor/src/components/media-placeholder/index.js]: :man_facepalming:

**Comment by kadamwhite** [comment]
@ocean90 Thanks for the review, apologies for the sloppy commits! Pushed up a fix, should be ready for review again once Travis has its say.

**Review by ocean90 — APPROVED** [review]

File: packages/editor/src/components/media-placeholder/index.js [hunk 3]
```diff
@@ -131,7 +131,7 @@ class MediaPlaceholder extends Component {
 			onHTMLDrop = noop,
 			multiple = false,
 			notices,
-			allowedTypes,
+			allowedTypes = [],
```
Comment (youknowriad) [inline packages/editor/src/components/media-placeholder/index.js]: I see that the prop is also used in `onlyAllowsImages` and `onlyAllowsImages` methods, should we add the default values there too?

Comment (kadamwhite) [reply packages/editor/src/components/media-placeholder/index.js]: I looked into that earlier, and I don't think changes are necessary in either of those cases. On `onlyAllowsImages` and `onFilesUpload` both, the existing logic should handle both `[]` and `null`/`false`/`undefined`/etc. (`onlyAllowsImages` has the checks in the media placeholder component, while `onFilesUpload` passes the prop value through to be checke within the `mediaUpload` method)
