### PR TITLE
Handle zoom out when changing device preview

### LINKED ISSUE #65411: Zoom out view: Device preview button doesn't work when zoom out view is enabled
### Description

The device preview button is not clickable when the experimental zoom out view is enabled.

From my understanding, when the zoom out view is enabled, one of the following is the expected behavior:

- Disablethe device preview dropdown
- Turn off the zoom out mode when the device preview button is clicked

### Step-by-step reproduction instructions

- Enable "Zoom out experiments" on the Gutenberg Experiments page
- open the post editor
- Click the Zoom out mode button
- Click on Tablet or Mobile in the Device Preview dropdown

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/1190949b-a452-4edf-8b3c-0d3c0b22c768

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by draganescu**
## What?

Fixes #65411

## Why?

Bug fix.

## How?

The device preview and zoom out toggle are two components that live in the same place in the component tree so they can be aware of the same mechanism and states of the UI. So I added a call to disable zoom out if a preview size is selected.

## Testing Instructions

- in the site editor
- select from the top right device dropdown a preview size (mobile)
- toggle the control next to it on (zoom out)
- change the preview size (tablet)
- notice zoom out is disengaged

### Testing Instructions for Keyboard

N/A

## Screenshots or screencast 

https://github.com/user-attachments/assets/5b59739f-5a9b-41e1-aa41-6694d7d1e5d8

### CODE REVIEW

**Review by t-hamano — APPROVED** [review]
LGTM! 

Another thing I was wondering is whether a follow-up PR should address the _reverse_ operation as well:

That is, whether or not to reset the device type to desktop when we enable the zoom out mode.

Currently, the zoom out toggle button doesn't reset the device type, which is why the device preview icon changes:


https://github.com/user-attachments/assets/884ac5bf-c170-4452-a21e-a1413010b5fe

File: packages/editor/src/components/preview-dropdown/index.js [hunk 1]
```diff
@@ -44,6 +45,12 @@ export default function PreviewDropdown( { forceIsAutosaveable, disabled } ) {
 			};
 		}, [] );
 	const { setDeviceType } = useDispatch( editorStore );
+	const { __unstableSetEditorMode } = useDispatch( blockEditorStore );
+
+	const handleDevicePreviewChange = ( newDeviceType ) => {
```
Comment (AhmarZaidi) [inline packages/editor/src/components/preview-dropdown/index.js:50]: Should we add doc comment for the new function?
This is what I was thinking:
```
/**
* Handles the selection of a device type from preview dropdown.
*
* Turns off the zoom out mode after setting the device type.
*
* @param {string} newDeviceType The selected device type.
*/
```

Comment (t-hamano) [reply packages/editor/src/components/preview-dropdown/index.js:50]: @AhmarZaidi 

I think there are no clear rules about JSDoc, but this is an internal function that is not exposed, and the process it performs is just two lines.

I personally don't think JSDoc is necessary because we can see what it's doing at a glance and I feel like JSDoc is a bit over the top. 😄
