### PR TITLE
Make block more menu transformations consistent

### LINKED ISSUE #5049: "Turn into" repetition in block actions
## Issue Overview
In the block actions menu there are options to switch block type. When there is more than one transformation option the repetition creates unnecessary visual noise.

## Steps to Reproduce
1. Select block (text blocks are the best example)
2. Open block actions menu (`...` icon)
3. Notice repetition of "Turn into..." string

## Possible Solution
Perhaps when there's more than one transformation option we include a single "Turn into" heading with the options beneath it. IE;

> Turn into Heading
> Turn into List
> Turn into Preformatted
> Turn into Quote
> Turn into Subhead
> Turn into Verse

becomes

> **Turn into**
> Heading
> List
> Preformatted
> Quote
> Subhead
> Verse

## Bonus points
"Turn into" is a phrase with multiple interpretations which might cause issues during localisation. If we chose to run with this idea we might use something like "Change block type" for the heading instead.

EDIT: Of course, as soon as I open this issue I notice we have the same menu in the toolbar which already [implements](https://cldup.com/VLdXYIKVXJ-3000x3000.png) this suggestion :)

### PR DESCRIPTION
**Pull request by jasmussen**
This fixes #5049. It removes the "Turn into" repetitive titles, in favor of a single header, like there is for the Block menu switcher.

turn into

### CODE REVIEW

**Comment by aduth** [comment]
I thought there might have been a related issue, but I expect this could worsen scenarios where the menu opens off-screen and it's impossible to reach transform options (by virtue of the fact that this makes the menu longer).

**Comment by mtias** [comment]
@jasmussen do you still want to explore having a fly-out menu for these so it doesn't pile at the bottom?

**Comment by jasmussen** [comment]
> do you still want to explore having a fly-out menu for these so it doesn't pile at the bottom?

A strong _maybe_ on that one. I do think there are more "at the root" improvements we can make to transformations. Some are being discussed in https://github.com/WordPress/gutenberg/pull/5585, and @iseulde also suggested we consider only having _one_ way to transform, the block toolbar or the ellipsis. 

I could definitely see it becoming a scalabililty issue.

File: editor/components/block-settings-menu/block-transformations.js [hunk 1]
```diff
@@ -27,9 +27,12 @@ function BlockTransformations( { blocks, small = false, onTransform, onClick = n
 	return (
 		<Fragment>
 			<div className="editor-block-settings-menu__separator" />
+			<span
+				className="editor-block-switcher__menu-title"
+			>
+				{ __( 'Transform into:' ) }
```
Comment (mtias) [inline editor/components/block-settings-menu/block-transformations.js]: Should we preserve the translators comment?

File: editor/components/block-settings-menu/block-transformations.js [hunk 2]
```diff
@@ -27,9 +27,12 @@ function BlockTransformations( { blocks, small = false, onTransform, onClick = n
 	return (
 		<Fragment>
 			<div className="editor-block-settings-menu__separator" />
+			<span
+				className="editor-block-switcher__menu-title"
```
Comment (mtias) [inline editor/components/block-settings-menu/block-transformations.js]: Are you using this class for something? We try not to inherit styles by reusing classes.

File: editor/components/block-settings-menu/block-transformations.js (hunk 1 above)
Comment (jasmussen) [reply editor/components/block-settings-menu/block-transformations.js]: I felt like it was unnecessary given the label was changed from sprintf( __( 'Turn into %s' ), title ) into __( 'Transform into:' ) — and also because I can't show the translator comment in context of the label because it's no longer a variable that gets inserted.

File: editor/components/block-settings-menu/block-transformations.js (hunk 2 above)
Comment (jasmussen) [reply editor/components/block-settings-menu/block-transformations.js]: I did use it to inherit, indeed. Pushed a change which simply duplicates the styles, but I'm not sure that's the best way to do it either. 

It seems like the More Menu, and the Block More Menu (block ellipsis menu) and the Block Switcher should all use a generic Menu component. But I'm not sure I have the skills necessary to make that happen, or whether it should happen in this PR. If yes then feel free to push to this branch.

**Review by gziolo — APPROVED** [review]
> I thought there might have been a related issue, but I expect this could worsen scenarios where the menu opens off-screen and it's impossible to reach transform options (by virtue of the fact that this makes the menu longer).

It is already long :) I think the biggest issue is that we have it in two places. However, I like this change because it makes them look similar.

I'm fine with merging it as it is. In the long run, we should explore having a fly-out menu or remove it completely from the block's drop-down menu to avoid the issue where half of the drop-down goes off-screen.
