### PR TITLE
Image block: fix replace link control styling

### LINKED ISSUE #33096: Image Block: URL preview layout is broken
## Description
When opening the "Replace" dropdown for an Image block, the Link/URL preview styling is broken. See screenshot.

## Step-by-step reproduction instructions
1. Create a post.
2. Add Image block and select media
3. Click on the "Replace" toolbar button.
4. See the "glob" icon.

## Expected behaviour
The layout should look more "stacked" without overlapping elements. It should not be visually "broken".

## Actual behaviour
It looks visually broken.

## Screenshots or screen recording (optional)
CleanShot 2021-06-30 at 16 43 12

## WordPress information
- WordPress version: 5.8 RC1
- Gutenberg version: 10.9.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

### PR DESCRIPTION
**Pull request by getdave**
## Description

The DOM and styling updates to `<LinkControl>` necessitated by the introduction of the the rich link previews feature caused the Image block `Replace` flow dropdown to suffer a visual layout regression.

123964709-c82ad600-d9c4-11eb-87f0-9378698b1c3f

This PR resolves this by aligning everything nicely again. See screenshots below.

Fixes https://github.com/WordPress/gutenberg/issues/33096

## How has this been tested?

* Add an Image block.
* Upload an Image and set it.
* Click `Replace` on the Image block.
* See the link UI without any obvious visual layout glitches.

## Screenshots 

| Before | After |
| ------ | ------ | 
| 123964709-c82ad600-d9c4-11eb-87f0-9378698b1c3f | Screenshot 2021-07-09 at 11 08 49 |

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by getdave** [comment]
Fixing those tests now...

File: packages/block-editor/src/components/link-control/index.js [hunk 1]
```diff
@@ -261,23 +266,26 @@ function LinkControl( {
...
-						className="block-editor-link-control__unlink"
-						isDestructive
-						variant="link"
-						onClick={ onRemove }
-					>
-						{ __( 'Unlink' ) }
-					</Button>
-				) }
-			</div>
+			{ showSettingsDrawer ||
```
Comment (getdave) [inline packages/block-editor/src/components/link-control/index.js]: Whoops! This introduces a regression. Thank you unit tests (which I wrote 😉 )!

So...let me think about this.

Comment (getdave) [reply packages/block-editor/src/components/link-control/index.js]: Fixed.

**Comment by getdave** [comment]
@javierarce a quick 👀 from a design perspective would be good here if you have any time.

**Comment by javierarce** [comment]
This looks much better, @getdave. 

I just saw a couple of things:

image

- I think we should have the same spacing between the `Current media URL` label and the input field. 8px would be perfect. 
(I also noticed that there's a weird 1px padding around the `.block-editor-url-input` element.)
- If I edit the URL the box shrinks (I understand this could difficult to fix).
- We are showing the URL of the image twice, which is not very useful. Could we have something similar to the previous component?

Screenshot 2021-07-09 at 13 23 03

I also discovered that if you enter a Base64 encoded image, the URL that appears in the `.block-editor-link-control__search-item-info` doesn't get shortened like other URLs. This is probably an extreme case, but I just thought it was worth mentioning. 

Screenshot 2021-07-09 at 13 11 12

**Review by draganescu — APPROVED** [review]
This works as described. Code looks good. 👍🏻

**Comment by getdave** [comment]
Thanks for the review @javierarce!

> * I think we should have the same spacing between the `Current media URL` label and the input field. 8px would be perfect.

I've added a consistent 8px margin in both edit and preview mode.

>   (I also noticed that there's a weird 1px padding around the `.block-editor-url-input` element.)

Removed that.

> * If I edit the URL the box shrinks (I understand this could difficult to fix).

I set a hardcoded 200px width which avoids this. 

> * We are showing the URL of the image twice, which is not very useful. Could we have something similar to the previous component?

I don't think we should attempt to "fix" this here but in a follow up. Essentially we do have much more data available but it's not being passed to the component so it isn't being displayed.

Screen Shot 2021-07-09 at 14 35 16


> I also discovered that if you enter a Base64 encoded image, the URL that appears in the `.block-editor-link-control__search-item-info` doesn't get shortened like other URLs. This is probably an extreme case, but I just thought it was worth mentioning.

I think that should be resolved by the fixed width above.

**Comment by getdave** [comment]
Rebasing FTW

**Comment by javierarce** [comment]
The changes look good to me! 🚀

> I don't think we should attempt to "fix" this here but in a follow up. Essentially we do have much more data available but it's not being passed to the component so it isn't being displayed.

Ok!

**Review by Mamaduka — APPROVED** [review]
LGTM :shipit:

Thanks for working on this, @getdave.

**Comment by getdave** [comment]
Tests failing probably needs a rebase. Please could someone merge this so it makes 11.1 RC?

**Comment by Mamaduka** [comment]
@getdave, all failing tests should be skipped soon. Maybe one more rebase after #33353.

**Comment by JustinyAhin** [comment]
@getdave this works as expected. Fine for me :).

Thanks

**Review by fullofcaffeine — APPROVED** [review]
This tests well! 🚢

**Comment by getdave** [comment]
Tests finally passed. I didn't do anything so I guess these were upstream issues on `trunk`.

**Comment by getdave** [comment]
@youknowriad This might be a good one for cherry picking in `11.1.0`.

cc @gwwar who I think is shadowing the release.

**Comment by youknowriad** [comment]
Changed the milestone to consider cherry-picking this.

**Comment by getdave** [comment]
Thanks @youknowriad. Wasn't sure whether to go ahead and do that without confirming with the release lead first.
