### PR TITLE
Fix error triggering after duplicating a block making it unselectable.

### LINKED ISSUE #38759: 'Duplicate' blocks from "List View" throws an error.
### Description

Clicking on the 'Duplicate' menu throws an error in the console.

The error message is: 

`Uncaught (in promise) TypeError: event.stopPropagation is not a function`

### Step-by-step reproduction instructions

1. Open List View
2. Open block dropdown menu
3. Click "Duplicate"

### Screenshots, screen recording, code snippet

Screen Shot 2022-02-12 at 6 14 39 PM

### Environment info

- WordPress: 5.9
- Gutenberg: 12.6.0-rc.1
- Browser: Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by delowardev**
Fixes: #38759

## Description

After duplicating a block from List View, it doesn't select that block and throws an error.

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

File: packages/block-editor/src/components/list-view/block.js [hunk 1]
```diff
@@ -103,11 +103,8 @@ function ListViewBlock( {
 	}, [ clientId, setIsHovered, highlightBlock ] );
 
 	const selectEditorBlock = useCallback(
```
Comment (delowardev) [inline packages/block-editor/src/components/list-view/block.js]: FYI this function is being called with `id` argument in here https://github.com/WordPress/gutenberg/blob/9f73be0aad5ac81e4798aef9666849b3e7ed3e0c/packages/block-editor/src/components/block-settings-menu/block-settings-dropdown.js#L83

Comment (talldan) [reply packages/block-editor/src/components/list-view/block.js]: The problem is this also gets used here:
https://github.com/WordPress/gutenberg/blob/9543b72e701a452858b1434977275bc3fbf3a8bd/packages/block-editor/src/components/list-view/block.js#L179

And if you drill down there's no `clientId` param, it's just an `onClick` event handler:
https://github.com/WordPress/gutenberg/blob/9543b72e701a452858b1434977275bc3fbf3a8bd/packages/block-editor/src/components/list-view/block-select-button.js#L75

Comment (talldan) [reply packages/block-editor/src/components/list-view/block.js]: I think it might be better to remove the `clientId` arg when `__experimentalSelectBlock` is called in `BlockSettingsDropdown`.

Then the only other thing that would be needed to fix this bug is to make event an optional param by adding a `?` in front of `stopPropagation`:
```jsx
	const selectEditorBlock = useCallback(
		( event ) => {
			event?.stopPropagation();
			selectBlock( clientId );
		},
		[ clientId, selectBlock ]
	);
```

**Comment by talldan** [comment]
Thanks for looking into this issue @delowardev.

The more I look at the code in `trunk`, the more it looks broken, and I'm also not sure what the right way to fix it is.

As you mention, `selectEditorBlocks` is sometimes called with `clientIds` as a param, sometimes with an `event` as a param. I'm also not sure what the original intention of the call to select blocks was in the block settings dropdown. Perhaps to prevent a focus loss?

I'm going to add some reviewers that have worked on this in the past for some further opinions. If I recall correctly @adamziel  and @noisysocks worked on the `BlockSettingsDropdown` in List View.

File: packages/block-editor/src/components/list-view/block.js (hunk 1 above)
Comment (noisysocks) [reply packages/block-editor/src/components/list-view/block.js]: > Then the only other thing that would be needed to fix this bug is to make event an optional param by adding a `?` in front of `stopPropagation`:

That will result in an error when `selectEditorBlock` is called by `BlockSettingsDropdown` and passed a client ID as the first argument. `event` will be defined, but it will be a string that doesn't contain any function named `stopPropagation`

I think it would be clearest to quit trying to use the one callback in both `ListViewBlockContents` and `BlockSettingsDropdown`, as the former requires a prop of the form `( Event ) => void` and the latter a prop of the form `( string ) => void`. They're incompatible.

```diff
diff --git a/packages/block-editor/src/components/list-view/block.js b/packages/block-editor/src/components/list-view/block.js
index a7746463c5..43458c3acf 100644
--- a/packages/block-editor/src/components/list-view/block.js
+++ b/packages/block-editor/src/components/list-view/block.js
@@ -102,14 +102,6 @@ function ListViewBlock( {
 		highlightBlock( clientId, false );
 	}, [ clientId, setIsHovered, highlightBlock ] );
 
-	const selectEditorBlock = useCallback(
-		( event ) => {
-			event.stopPropagation();
-			selectBlock( clientId );
-		},
-		[ clientId, selectBlock ]
-	);
-
 	const toggleExpanded = useCallback(
 		( event ) => {
 			event.stopPropagation();
@@ -176,7 +168,10 @@ function ListViewBlock( {
 					<div className="block-editor-list-view-block__contents-container">
 						<ListViewBlockContents
 							block={ block }
-							onClick={ selectEditorBlock }
+							onClick={ ( event ) => {
+								event.stopPropagation();
+								selectBlock( clientId );
+							} }
 							onToggleExpanded={ toggleExpanded }
 							isSelected={ isSelected }
 							position={ position }
@@ -235,7 +230,9 @@ function ListViewBlock( {
 								onFocus,
 							} }
 							disableOpenOnArrowDown
-							__experimentalSelectBlock={ selectEditorBlock }
+							__experimentalSelectBlock={ () =>
+								selectBlock( clientId )
+							}
 						/>
 					) }
 				</TreeGridCell>
```

**Comment by noisysocks** [comment]
> I'm also not sure what the original intention of the call to select blocks was in the block settings dropdown. Perhaps to prevent a focus loss?

I'm not 100% sure either. This bit of the codebase has had a lot of iteration so very possible it's not used anymore. Feel free to remove it and see what happens 😀 just be sure to test List View in the site editor, post editor, widgets editor, navigation block toolbar, and experimental navigation editor.

File: packages/block-editor/src/components/list-view/block.js (hunk 1 above)
Comment (talldan) [reply packages/block-editor/src/components/list-view/block.js]: > That will result in an error when selectEditorBlock is called by BlockSettingsDropdown and passed a client ID as the first argument. event will be defined, but it will be a string that doesn't contain any function named stopPropagation

That's why I said we should remove the `clientId` argument. 😄 

> I think it would be clearest to quit trying to use the one callback in both ListViewBlockContents and BlockSettingsDropdown, as the former requires a prop of the form ( Event ) => void and the latter a prop of the form ( string ) => void. They're incompatible.

That does also seem like a good option, but we'd still have the `clientId` being passed from `BlockSettingsDropdown` to `selectBlock`. Seems like we both agree that it could be removed, or maybe your code snippet had an error in omitting the parameter?

It'd be good to use `useCallback` too, as this is performance sensitive code.

**Comment by talldan** [comment]
After looking at the code for a while, I think I have a good idea for a fix.

It looks like all that needs to be changed is this line:
https://github.com/WordPress/gutenberg/blob/9543b72e701a452858b1434977275bc3fbf3a8bd/packages/block-editor/src/components/list-view/block.js#L239

Which can be changed to this:
```jsx
__experimentalSelectBlock={ selectBlock }
```

Reasoning: `selectBlock` already accepts a `clientId` as the first param and doesn't expect an event, so seems to match the code in `BlockSettingsDropdown`. I can't be sure, but I think this is probably what was intended, but someone made a typo and accidentally typed `selectEditorBlock`.

File: packages/block-editor/src/components/list-view/block.js (hunk 1 above)
Comment (talldan) [reply packages/block-editor/src/components/list-view/block.js]: I think this might be the right solution - https://github.com/WordPress/gutenberg/pull/38760#issuecomment-1038692197.

**Review by talldan — APPROVED** [review]
That seems to work well now, thanks for spotting the bug and fixing it.
