### PR TITLE
Navigation Editor: Move selected menu ID to the store

### LINKED ISSUE #22623: Load last edited menu by default
**Describe the bug**
On the current nav-menus.php page, the last edited menu is selected by default when you load the nav-menus.php page. The same behaviour should be applied to the new experimental menus screen.

**To reproduce**
1. Go to Gutenberg > Navigation (experimental)
2. Select a different menu from the dropdown
3. Save the navigation
4. Leave the page
5. Return to Gutenberg > Navigation (experimental)

**Expected behavior**
The last edited menu should be selected by default

**Editor version (please complete the following information):**
- WordPress version: latest
- Plugin
- If the Gutenberg plugin is installed, which version is it? 8.2

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
Attempt to move currently selected menu ID to the store. Value is synced to localStorage as suggested here https://github.com/WordPress/gutenberg/pull/31132#issuecomment-827353433.

PR introduces new actions/selector for working with selected menu ID.

### Other changes
* Adds `useSelectedMenuId` hook for convenience.
* Removes `useSelectedMenuData` hook and `MenuIdContext`.

Fixes #22623.

## How has this been tested?
1. Got to the new experimental Navigation screen.
2. Create few menus.
3. Select the last menu created.
4. Refreshing page should display the same menu.

Testing the store changes:

`npm run test-unit -- packages/edit-navigation/src/store/test`

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/edit-navigation/src/hooks/use-navigation-editor.js [hunk 1]
```diff
@@ -73,7 +75,7 @@ export default function useNavigationEditor() {
 			force: true,
 		} );
 		if ( didDeleteMenu ) {
-			setSelectedMenuId( null );
+			setSelectedMenuId( 0 );
```
Comment (getdave) [inline packages/edit-navigation/src/hooks/use-navigation-editor.js:78]: Just checking...is it safe to set this to `0`? What if there are no menus left?

**Review by getdave — APPROVED** [review]
I tested this and it did indeed select the last menu I had selected displayed when reloading. I also saw the value in `localStorage`.

This also works if you delete all menus - there are no errors.

I don't know much about the persistence plugin but it seemed to work well.

**Update**: looks like you have a failing e2e test.

File: packages/edit-navigation/src/hooks/use-navigation-editor.js (hunk 1 above)
Comment (Mamaduka) [reply packages/edit-navigation/src/hooks/use-navigation-editor.js:78]: If there are no menus left, the screen will display create menu placeholder. I'm using `0` here so we can have a single type for selectedMenuId. But having `null` as in no menu was selected also makes sense to me.
