### PR TITLE
Layout: merge CSS rule for block gap

### LINKED ISSUE #43046: Batching gap styles is causing Block Spacing settings to fail
### Description

It looks like since the introduction of https://github.com/WordPress/gutenberg/pull/42452, block spacing settings are applied incorrectly when batched. 

In looking at the [original code](https://github.com/WordPress/gutenberg/blob/9e3767cc217542d4e4926280a91feb584b3f7a7b/lib/block-supports/layout.php#L110), the order is important. 

```
if ( $gap_value && ! $should_skip_gap_serialization ) {
	array_push(
		$layout_styles,
		array(
			'selector'     => "$selector > *",
			'declarations' => array(
				'margin-block-start' => '0',
				'margin-block-end'   => '0',
			),
		),
		array(
			'selector'     => "$selector > * + *",
			'declarations' => array(
				'margin-block-start' => $gap_value,
				'margin-block-end'   => '0',
			),
		)
	);
}
```

However, when multiple containers with custom block spacing get batched, the batched `$selector > *` styles can get placed after the `$selector > * + *` styles. 

### Step-by-step reproduction instructions

1. Using trunk or [Gutenberg Nightly](https://gutenbergtimes.com/need-a-zip-from-master/#nightly), add a Columns block with a single Column block.
2. Add two Paragraph blocks and then Group the Paragraph blocks. 
3. Set the Block Spacing on the Column block to 40px.
4. On the Group block inside of the Column block, set the Block Spacing 20px.
5. Everyone looks ok in Editor, but on the Frontend, the styles are rendered incorrect. See the screenshot below, the batched batched `$selector > *` styles are rendering after the `$selector > * + *` styles which gives them higher priority. 

### Screenshots, screen recording, code snippet

image

### Environment info

- WordPress 6.0.1 
- Gutenberg Nightly/Trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ramonjd**
Resolves https://github.com/WordPress/gutenberg/issues/43046

Alternative to
- https://github.com/WordPress/gutenberg/pull/43051

## What?

In the layout abstraction, merge `$selector > *,$selector > * + *` selectors, only set `margin-block-start` if a gap value is available.

```css

.wp-block-group.wp-container-1 > * + * {
	margin-block-start: 137px;
}
.wp-block-group.wp-container-2 > * + * {
	margin-block-start: 71px;
}
.wp-block-column.wp-container-3 > * + * {
	margin-block-start: 120px;
}
.wp-block-group.wp-container-5 > * + * {
	margin-block-start: 118px;
}
/* some styles... */
.wp-block-group.wp-container-1 > *,
.wp-block-group.wp-container-1 > * + *,
.wp-block-group.wp-container-2 > *,
.wp-block-group.wp-container-2 > * + *,
.wp-block-column.wp-container-3 > *,
.wp-block-column.wp-container-3 > * + *,
.wp-block-group.wp-container-5 > *,
.wp-block-group.wp-container-5 > * + * {
	margin-block-end: 0;
}

```

## Why?
So that the style engine optimization engine prints out the rules separately. 

**Note**: this doesn't address to root cause, that is, the style engine doesn't care about the order of rules when combining selectors. Combined selectors are printed at the bottom of the stylesheet.

## Testing Instructions

(Taken from #43046)

1. Using trunk or [Gutenberg Nightly](https://gutenbergtimes.com/need-a-zip-from-master/#nightly), add a Columns block with a single Column block.
2. Add two Paragraph blocks and then Group the Paragraph blocks.
3. Set the Block Spacing on the Column block to 40px.
4. On the Group block inside of the Column block, set the Block Spacing 20px.
5. Check that the correct block gap is applied to the inner elements of the Group block.

<details>

<summary>Example block code </summary>

```html
<!-- wp:columns {"style":{"spacing":{"blockGap":"1px"}}} -->
<div class="wp-block-columns"><!-- wp:column {"width":"100%"} -->
<div class="wp-block-column" style="flex-basis:100%"><!-- wp:group {"style":{"color":{"background":"#9eebbc"},"spacing":{"blockGap":"137px"}},"layout":{"contentSize":"342px"}} -->
<div class="wp-block-group has-background" style="background-color:#9eebbc"><!-- wp:paragraph {"style":{"elements":{"link":{"color":{"text":"#cd31d6"}}}}} -->
<p class="has-link-color"><a href="https://word">Test</a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Test</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns {"style":{"spacing":{"blockGap":"1px"}}} -->
<div class="wp-block-columns"><!-- wp:column {"width":"100%"} -->
<div class="wp-block-column" style="flex-basis:100%"><!-- wp:group {"style":{"color":{"background":"#1a4a2d"},"spacing":{"blockGap":"118px"}},"layout":{"contentSize":"342px"}} -->
<div class="wp-block-group has-background" style="background-color:#1a4a2d"><!-- wp:paragraph {"style":{"elements":{"link":{"color":{"text":"#cd31d6"}}}}} -->
<p class="has-link-color"><a href="https://word">Test</a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Test</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

</details>

### Trunk 
Screen Shot 2022-08-08 at 8 42 43 am

### This PR

Screen Shot 2022-08-08 at 8 43 01 am

### CODE REVIEW

**Comment by ndiego** [comment]
I tested this one as well, and it works as expected. Thanks!

That said, as you mentioned in [your comment](https://github.com/WordPress/gutenberg/issues/43046#issuecomment-1207508505), things definitely get a bit tricky here. I think I would be inclined to disable optimization for now until more testing is done. The batching is pretty slick, but I'm worried about other issues related to style order. I'll be doing more testing this week to see if I can find anything else.

**Comment by andrewserong** [comment]
> That said, as you mentioned in https://github.com/WordPress/gutenberg/issues/43046#issuecomment-1207508505, things definitely get a bit tricky here. I think I would be inclined to disable optimization for now until more testing is done.

Same here. Thanks for getting the multiple PRs up, though, so we've got options!

**Comment by ramonjd** [comment]
I guess it wouldn't hurt to merge this one anyway, what do you think @andrewserong ? Or should we keep it to use as a test case for follow up tweaks to the optimization code?

**Comment by andrewserong** [comment]
> Or should we keep it to use as a test case for follow up tweaks to the optimization code?

I haven't had a chance to test this yet, but I'd lean toward keeping it as a test case, personally. Ideally we're adding a single selector at a time? Happy to give it a test later on today if you think it's better to get it technically working first, though!

File: lib/block-supports/layout.php [hunk 1]
```diff
@@ -108,17 +108,15 @@ function gutenberg_get_layout_style( $selector, $layout, $has_block_gap_support
...
-						'selector'     => "$selector > *",
+						'selector'     => "$selector > *,$selector > * + *",
 						'declarations' => array(
-							'margin-block-start' => '0',
-							'margin-block-end'   => '0',
+							'margin-block-end' => '0',
 						),
 					),
 					array(
 						'selector'     => "$selector > * + *",
```
Comment (aristath) [inline lib/block-supports/layout.php]: We could simply change this selector to be more specific... Since this needs to override the other one and they both have the same specificity, we should raise the specificity of this one
```suggestion
						'selector'     => "$selector.$selector > * + *",
```

Comment (ramonjd) [reply lib/block-supports/layout.php]: Works great! Committed (without the extra `.`)

I'm happy to go with either if we think we should merge this one.

Comment (andrewserong) [reply lib/block-supports/layout.php]: Nice that this one fixes the current use case, and it feels a bit neater than combining the selectors in the first rule. Since this is only output when there is a real gap value, I don't at all object to upping the specificity here 👍

I'm wondering if it reveals a drawback or potential issue for the optimisation that we should look into separately, though. It's possibly going to be fairly common for themes to expect styles to override earlier styles with the same specificity due to the order in which they're added. In the case of this particular gap rule, I believe it might have been originally implemented based on the rules from the following article / generator: https://every-layout.dev/layouts/stack/#the-generator

Also, once we go to implement optimisation in global styles, we'll need to be careful about the specificity of the rules, as upping the specificity at one level of the style chain might make it harder for rules at other levels. (e.g. base layout gap, versus block-level in theme gap, versus block-level in block attributes gap).

**Review by aristath — APPROVED** [review]
