### PR TITLE
Post title: fix single line paste

### LINKED ISSUE #38637: Issues when pasting into post title field
### Description

While doing some in-depth testing around copy + pasting into the post title field of the editor, I noticed a few issues:

1. When pasting headings with a lot of formatting from Google Docs into the post title field, a bunch of the original formatting is initially displayed in the editor. This is really just a visual issue, as it doesn't cause issues on the frontend and goes away when a post is re-visited in the editor.
2. When pasting strings with certain characters into the post title field, it's possible to generate permalinks that can cause redirection issues or crash browsers.
3. When pasting a full line heading from Google Docs into the post title field in Safari, certain headings crash the editor and the whole browser.

### Step-by-step reproduction instructions

**To reproduce issue 1 around pasting formatted content from Google Docs into the title field:**
1.  Create a Google Doc. Add some headings with a bunch of formatting to the doc.
2. Copy one of the headings. Paste it into the title field of the editor. Observe much of the styling carries over (color, sometimes size, sometimes font weight, etc.)
3. Save post. Re-open editor. Observe post title doesn't have all that extra formatting applied and looks normal.
This screen recording demonstrates this issue well:
gutenbergpastetitle1

**To reproduce issue 2 around permalink generation when certain characters are in the title:**
1.  Copy this string, including the character at the end which displays as [`[obj]`](https://www.compart.com/en/unicode/U+FFFC) or an empty space, depending on your browser: 

Orange County Cities Continue Grappling With State Mandated Housing Goals This Week￼

2. Paste it into the title field. Publish the post. The generated permalink and title will look like this in different browsers:

**Chrome**:
Screen Shot 2022-02-08 at 11 36 58 AM

**Safari**:

Screen Shot 2022-02-08 at 11 38 50 AM
Screen Shot 2022-02-08 at 11 38 57 AM

The presence of this character in URLs seems to cause difficulties for some users' browsers, and can crash the tab when a user visits a link with the character in it. I am unsure how to get that character "naturally" in the clipboard, but it seems to happen when copy + pasting from something (I've encountered it on a number of sites I manage following the WP 5.9 release).

**To reproduce issue 3 around the Safari crashing when a heading is pasted into the title field:**

1. This doesn't seem to happen with every Google Doc, but it does happen with many in my testing. In Safari, copy the full heading line to the clipboard and paste it into the post title field. Observe the browser crashes. In the below screen recording, I copy the heading line, paste it, Safari crashes and reloads, I paste it again, Safari crashes and doesn't reload:
gutenbergtitlepaste2

### Screenshots, screen recording, code snippet

See steps to reproduce

### Environment info

I tested on a clean site running only WP 5.9 (using the version of Gutenberg that ships with WP 5.9). Theme was Twenty Twenty Two, but I can reproduce with other themes. I tested with Safari and Chrome. Device was a MacBook Pro.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Fixes #38637. The problem is that we forgot to handle the case when the pasteHandler outputs a string. Since we also didn't prevent default behaviour, the browser is handling it, which makes it seems like everything is working fine. But the browser will paste unfiltered HTML.

I guess we should add an e2e test?

### CODE REVIEW

File: packages/editor/src/components/post-title/index.js [hunk 1]
```diff
@@ -149,7 +149,13 @@ function PostTitle( _, forwardedRef ) {
 			plainText,
 		} );
 
-		if ( typeof content !== 'string' && content.length ) {
+		event.preventDefault();
```
Comment (mcsf) [inline packages/editor/src/components/post-title/index.js:152]: There's a duplicate `preventDefault` call inside the `if ( typeof content !== 'string' )` block that can be removed.

**Review by mcsf — APPROVED** [review]
Just from a strict code review, LGTM. I agree with adding a quick test.

**Review by dmsnell — APPROVED** [review]
Worth getting the fix in.

Do you think the `content.slice(1)` could be the issue? I noticed that when selecting a single line we receive and empty `<span>` from Google Docs with some ref id in it. That was moved to the beginning of the `pieces` in the raw handler even though it came _after_ the HTML.

Maybe we can continue to explore this after merge and see if there isn't something going on with `shortcodeConverter` or another part of the process.

**Comment by ellatrix** [comment]
> Do you think the `content.slice(1)` could be the issue?

No, that only happens when the pasted content is an array of blocks, in which case we're taking out the first block if it's a heading or paragraph and paste that into the title. In this case the HTML is already filtered through the `pasteHandler` (we're getting an array of cleaned up blocks).

The problem was that for single lines of content, we were accidentally letting the browser insert the unfiltered HTML instead of preventing default and inserting our cleaned up HTML.

**Comment by ellatrix** [comment]
Added a test, I'll merge when it passes.

**Comment by dmsnell** [comment]
> we were accidentally letting the browser insert the unfiltered HTML instead of preventing default and inserting our cleaned up HTML.

ah this makes more sense; I had this suspicion I hadn't yet confirmed that we were losing track of the content input into the `contenteditable` and that's where the extra _stuff_ came from that the `OBJ` replacement character represented. thanks for explaining!
