### PR TITLE
InputControl: Fix text direction for URL and email fields in block editor for RTL languages

### LINKED ISSUE #65893: InputControl/TextControl: Force direction to LTR for certain fields
## What problem does this address?

For example, in the `email` and `url` fields, the text direction is usually expected to be `ltr`.

There is a style in WordPress core that will change the direction to ltr:

https://github.com/t-hamano/wordpress-develop/blob/a51f2e45c4a76878dbd0ab90782d44a07b29d13a/src/wp-content/themes/twentytwentyone/assets/sass/04-elements/forms.scss#L57-L62

However, this style does not necessarily apply to the block editor.

For example, in the Embed block that uses the `InputControl` with a `url` type, the direction is RTL, as shown below:

Image

## What is your proposed solution?

As with core, if the type attribute is `url` or `email`, I suggest adding `direction: ltr`.

However, there seem to be various approaches to making form fields RTL-compatible. Please refer to the following article:

[Interface localisation: adapting text fields for RTL languages | by Mitya Kuznetsov | Bumble Tech | Medium](https://medium.com/bumble-tech/interface-localisation-adapting-text-fields-for-rtl-languages-67a386006a17)

### PR DESCRIPTION
**Pull request by im3dabasia**
Closes : https://github.com/WordPress/gutenberg/issues/65893

## What?
Adds `direction: ltr` for URL and email input fields in the block editor to ensure correct text alignment, especially for RTL languages.

## Why?
Currently, in RTL languages, the block editor shows URL and email fields from right to left, which is not ideal. As suggested in the issue, these fields should be displayed left to right (LTR) regardless of the language direction for consistency and better usability. 

## Screenshots or screencast 
Here are a few samples which I tested out. 

### Embed Block
|Before|After|
|-|-|
|image|image|

### RSS Block

|Before|After|
|-|-|
|image|image|

### Audio Block which uses url-popover component
|Before|After|
|-|-|
|image|image|

### CODE REVIEW

**Comment by im3dabasia** [comment]
Hey @t-hamano ,

Thank you for pointing out this https://github.com/WordPress/gutenberg/issues/65893. When you have a moment, could you please check this PR and provide your feedback?

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

I think the purpose of this PR is reasonable, but it is not desirable to write styles for input elements in the stylesheet of a specific block (Form Input block).

In my opinion, it might be better to solve this problem at the component level.

That is, add `direction:ltr` [here](https://github.com/WordPress/gutenberg/blob/61d7404ceaee8153414677b868ccb40a3571d1a7/packages/components/src/input-control/styles/input-control-styles.tsx#L268) in the `InputControl` component if the `type` is `email` or `url`.

Also, if we want to solve a similar problem with the Textcontrol component, I think we would need to add CSS [here](url).

**Comment by im3dabasia** [comment]
> Also, if we want to solve a similar problem with the Textcontrol component, I think we would need to add CSS [here](url).

Hi @t-hamano,

For the TextControl component, we’ll need to add the type prop wherever the input type is set to url or email. Currently, the type prop isn't passed, which is why the CSS is not being applied. I’ve compiled a list of places where this prop can be added. Could you please review it and let me know if I've missed any?

<details>
<summary> form </summary>

https://github.com/WordPress/gutenberg/blob/48b862424f99ba63d05c9286b3d1b3cd3d86fe7e/packages/block-library/src/form/edit.js#L109-L126

https://github.com/WordPress/gutenberg/blob/48b862424f99ba63d05c9286b3d1b3cd3d86fe7e/packages/block-library/src/form/edit.js#L148-L162

</details>


<details>
<summary> navigation-link </summary>

https://github.com/WordPress/gutenberg/blob/48b862424f99ba63d05c9286b3d1b3cd3d86fe7e/packages/block-library/src/navigation-link/edit.js#L192-L205

</details>



<details>
<summary> navigation-submenu </summary>

https://github.com/WordPress/gutenberg/blob/48b862424f99ba63d05c9286b3d1b3cd3d86fe7e/packages/block-library/src/navigation-submenu/edit.js#L422-L431

</details>


There are several places where the rel attribute is used for links. I'm not entirely sure if the type prop is necessary in these cases. Could you please clarify if adding type="url" is required here?

<details>
<summary> Sample Link rel </summary>

https://github.com/WordPress/gutenberg/blob/48b862424f99ba63d05c9286b3d1b3cd3d86fe7e/packages/block-library/src/post-title/edit.js#L164-L172

</details>


### Screenshots for navigation-link

| Before | After |
|--------|-------|
| Screenshot 2024-12-26 at 7 36 21 PM | Screenshot 2024-12-26 at 7 42 31 PM |

File: packages/components/src/input-control/styles/input-control-styles.tsx [hunk 1]
```diff
@@ -287,6 +287,12 @@ export const Input = styled.input< InputProps >`
 		&::-webkit-input-placeholder {
 			line-height: normal;
 		}
+
+		&[type='email'],
+		&[type='url'] {
+			/* rtl:ignore */
+			direction: ltr;
+		}
```
Comment (t-hamano) [inline packages/components/src/input-control/styles/input-control-styles.tsx:295]: If you reference the props directly, you should be able to output CSS conditionally. A possible approach would be something like this:

<details><summary>Details</summary>

```diff
diff --git a/packages/components/src/input-control/styles/input-control-styles.tsx b/packages/components/src/input-control/styles/input-control-styles.tsx
index 39eea8fdb0..ece01451db 100644
--- a/packages/components/src/input-control/styles/input-control-styles.tsx
+++ b/packages/components/src/input-control/styles/input-control-styles.tsx
@@ -4,7 +4,7 @@
 import type { SerializedStyles } from '@emotion/react';
 import { css } from '@emotion/react';
 import styled from '@emotion/styled';
-import type { CSSProperties, ReactNode } from 'react';
+import type { CSSProperties, ReactNode, HTMLInputTypeAttribute } from 'react';
 
 /**
  * Internal dependencies
@@ -141,6 +141,7 @@ type InputProps = {
        dragCursor?: CSSProperties[ 'cursor' ];
        paddingInlineStart?: CSSProperties[ 'paddingInlineStart' ];
        paddingInlineEnd?: CSSProperties[ 'paddingInlineEnd' ];
+       type?: HTMLInputTypeAttribute;
 };
 
 const disabledStyles = ( { disabled }: InputProps ) => {
@@ -262,6 +263,15 @@ const dragStyles = ( { isDragging, dragCursor }: InputProps ) => {
        `;
 };
 
+const directionStyles = ( { type }: InputProps ) => {
+       if ( type !== 'url' && type !== 'email' ) {
+               return '';
+       }
+       return css`
+               direction: ltr;
+       `;
+};
+
 // TODO: Resolve need to use &&& to increase specificity
 // https://github.com/WordPress/gutenberg/issues/18483
 
@@ -283,6 +293,7 @@ export const Input = styled.input< InputProps >`
                ${ fontSizeStyles }
                ${ sizeStyles }
                ${ customPaddings }
+               ${ directionStyles }
 
                &::-webkit-input-placeholder {
                        line-height: normal;
```

</details>

**Review by t-hamano — COMMENTED** [review]
Thanks for the update!

Sorry, I'm starting to think that since the `TextControl` component is so widely used, it might be better to address it in a separate PR. Can this PR address just the `InputControl` component?

**Comment by im3dabasia** [comment]
Hey @t-hamano , 

Thank you for your insightful suggestions on conditionally implementing the CSS. I truly appreciate the feedback, and I’m learning a lot from it.

I have made the changes you requested and have created this PR specifically to incorporate the updates to the `<InputControl>` component. However, there are two instances where I’m unsure if `type="url"` is strictly necessary. The code suggests it’s for handling URL-related input, but I would appreciate your input on whether it's needed in these cases.

Looking forward to your thoughts!

<details>
<summary> InputControl component</summary>

https://github.com/WordPress/gutenberg/blob/d517683279c03b306b7047bce4510691889874e6/packages/fields/src/fields/slug/slug-edit.tsx#L88-L119

https://github.com/WordPress/gutenberg/blob/d517683279c03b306b7047bce4510691889874e6/packages/editor/src/components/post-url/index.js#L111-L162

</details>

File: packages/components/src/input-control/styles/input-control-styles.tsx (hunk 1 above)
Comment (mirka) [reply packages/components/src/input-control/styles/input-control-styles.tsx:295]: Any reason why we would prefer this over plain CSS selectors? I think in general we should use plain CSS instead of JS when possible, since it will be simpler both in terms of lines of code and runtime work. Another reason is that we are actually planning to move off of CSS-in-JS (#66806).

Comment (t-hamano) [reply packages/components/src/input-control/styles/input-control-styles.tsx:295]: > Any reason why we would prefer this over plain CSS selectors?

I did it for consistency with existing approaches (`sizeStyles`, `customPaddings`, etc.). But if we are planning to move off of CSS-in-JS, I think the plain CSS is better.

Comment (im3dabasia) [reply packages/components/src/input-control/styles/input-control-styles.tsx:295]: Hey @t-hamano , I have reverted back to using CSS. Please review my work once again.

**Comment by im3dabasia** [comment]
@t-hamano, I’ll be opening a new PR with the changes to the <TextControl> component shortly and will link it here once it's ready.

**Review by t-hamano — COMMENTED** [review]
@im3dabasia Thanks for the update. Finally, it would be nice to add a [CHANGELOG](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/README.md) entry. In my opinion, this is a bug fix.

@WordPress/gutenberg-components 

I think this PR is OK to ship, but please note that it will make a visual change to the placeholder. The text will be left-aligned regardless of whether it is an LTR or RTL language:

image

Ideally maybe only the placeholder should be right-aligned, but for some reason the code below didn't work for me:

```diff
diff --git a/packages/components/src/input-control/styles/input-control-styles.tsx b/packages/components/src/input-control/styles/input-control-styles.tsx
index db24a5e60f..3fc293e9c3 100644
--- a/packages/components/src/input-control/styles/input-control-styles.tsx
+++ b/packages/components/src/input-control/styles/input-control-styles.tsx
@@ -292,6 +292,11 @@ export const Input = styled.input< InputProps >`
                &[type='url'] {
                        /* rtl:ignore */
                        direction: ltr;
+
+                       &::-webkit-input-placeholder {
+                               // For RTL languages, the value changes to "rtl".
+                               direction: ltr !important;
+                       }
                }
        }
 `;
```

Furthermore, we cannot know in advance whether the text that goes into the placeholder is for an RTL language or whether it is something that is meant to be displayed in LTR, such as a URL.

In any case, since the text doesn't become unreadable, I think it's fine to always left-aligned the placeholder.

**Comment by im3dabasia** [comment]
> @im3dabasia Thanks for the update. Finally, it would be nice to add a [CHANGELOG](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/README.md) entry. In my opinion, this is a bug fix.

@t-hamano , I'm not quite sure how to create a CHANGELOG entry or which CHANGELOG I should add an entry to. I'd really appreciate it if you could guide me here.

**Comment by t-hamano** [comment]
@im3dabasia No need to create a new file, just access [this file](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md) and add the new line [here](https://github.com/WordPress/gutenberg/blob/b4304f8bf6bd9b890b4108adcc326cd586a3ab4e/packages/components/CHANGELOG.md#L21).

Essentially, if any changes are made to the `@wordpress/components` package, those changes must be added to a changelog file. Otherwise, [CI will fail](https://github.com/WordPress/gutenberg/actions/runs/12525340560/job/34936804178?pr=68188) (although this CI is not required check).

**Comment by tyxla** [comment]
> @im3dabasia Thanks for the update. Finally, it would be nice to add a [CHANGELOG](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/README.md) entry. In my opinion, this is a bug fix.
> 
> @WordPress/gutenberg-components
> 
> I think this PR is OK to ship, but please note that it will make a visual change to the placeholder. The text will be left-aligned regardless of whether it is an LTR or RTL language:
> 
> image
> 
> Ideally maybe only the placeholder should be right-aligned, but for some reason the code below didn't work for me:
> 
> ```diff
> diff --git a/packages/components/src/input-control/styles/input-control-styles.tsx b/packages/components/src/input-control/styles/input-control-styles.tsx
> index db24a5e60f..3fc293e9c3 100644
> --- a/packages/components/src/input-control/styles/input-control-styles.tsx
> +++ b/packages/components/src/input-control/styles/input-control-styles.tsx
> @@ -292,6 +292,11 @@ export const Input = styled.input< InputProps >`
>                 &[type='url'] {
>                         /* rtl:ignore */
>                         direction: ltr;
> +
> +                       &::-webkit-input-placeholder {
> +                               // For RTL languages, the value changes to "rtl".
> +                               direction: ltr !important;
> +                       }
>                 }
>         }
>  `;
> ```
> 
> Furthermore, we cannot know in advance whether the text that goes into the placeholder is for an RTL language or whether it is something that is meant to be displayed in LTR, such as a URL.
> 
> In any case, since the text doesn't become unreadable, I think it's fine to always left-aligned the placeholder.

According to the spec, when the placeholder needs to be with a different directionality than the content, we wrap contents with `&#x202B;` and `&#x202E;`, so that might be a better alternative, see [spec here](https://html.spec.whatwg.org/multipage/input.html#the-placeholder-attribute:~:text=In%20situations%20where%20the%20control%27s%20content%20has%20one%20directionality%20but%20the%20placeholder%20needs%20to%20have%20a%20different%20directionality%2C%20Unicode%27s%20bidirectional%2Dalgorithm%20formatting%20characters%20can%20be%20used%20in%20the%20attribute%20value%3A).

**Comment by im3dabasia** [comment]
Hey @t-hamano and @tyxla, I’ve made the requested changes. Please take a look when you have a moment.

**Comment by tyxla** [comment]
@im3dabasia thanks for working on it!

However, @t-hamano mentioned that the `&::-webkit-input-placeholder` approach didn't work for him. Also, this could only work for webkit browsers, so it wouldn't work for Firefox for example. 

Furthermore, as I mentioned [above](https://github.com/WordPress/gutenberg/pull/68188#issuecomment-2565244728), the spec recommends a different approach, have you tried that?

**Comment by im3dabasia** [comment]
I tried a combination of approaches.. sharing with you the results

### trunk
The entire placeholder text is right-aligned, and the ellipsis is placed first, followed by the text itself.
 
image


### Current branch
The placeholder is left-aligned, with the text displayed first, followed by the ellipsis.

image



These are the 3 approaches I tried:

1.` placeholder={ "&#x202B; " + __( 'Enter URL here…' ) + " &#x202E;" }`  

The entire placeholder is left-aligned, and the ellipsis appears after the text.

image


2. ```placeholder={ `&#x202B; ${ __( 'Enter URL here…' ) } &#x202E;` }```  

The entire placeholder is left-aligned, and the ellipsis appears after the text.

image

3. `placeholder="&#x202B; Enter URL here… &#x202E;"` 

The placeholder is left-aligned, but the ellipsis appears before the text.

Screenshot 2024-12-30 at 6 33 54 PM


Based on my understanding, the goal is for the placeholder text to be in RTL (right-to-left), just like plain text would be, and for the placeholder to be right-aligned within the input box. This means the placeholder text should be displayed in RTL, but the input box itself should remain rendered in LTR, with only the placeholder text aligned and displayed in RTL.

During my experimentation, I was able to achieve the RTL text alignment as shown in Case 3 with what @tyxla suggested. However, I found that when I removed the __() translation function and used plain text, the text direction switched to RTL. The resulted text was RTL but was left aligned, which is not the desired behavior. The alignment still remains incorrect. Also  removing the translation function isn't a suitable solution. 


### EDIT: 

It's also worth mentioning that after adding the HTML entities in the placeholder (as shown in Case 3), the output for an LTR language is as follows:

Hardcoding the entities will cause an override for all languages, both LTR and RTL. While adding them will fix the alignment in RTL languages, it will disrupt the alignment in LTR languages.

image


- I believe the approach of using `&#x202B;` and `&#x202E;` may not be ideal for this scenario, as the placeholder text will vary based on the user's language, and the entire text will switch between LTR and RTL. This method seems more appropriate when the website is primarily in a base language (e.g., English), with occasional RTL words embedded. In such cases, the entities approach ensures correct directionality for those specific words. However, it may not be suitable when the entire placeholder text changes based on the language.


Please let me know your thoughts on this.

**Comment by tyxla** [comment]
Thanks for trying it out 👍 If that approach doesn't work, we might want to resort to the placeholder one.

I know we've historically used all (`&::-webkit-input-placeholder`, `&::-moz-placeholder`, `&:-ms-input-placeholder`) or used `::placeholder` which should have browser-wide support at this time. Perhaps that might be something to try out.

**Comment by im3dabasia** [comment]
> I know we've historically used all (`&::-webkit-input-placeholder`, `&::-moz-placeholder`, `&:-ms-input-placeholder`) or used `::placeholder` which should have browser-wide support at this time. Perhaps that might be something to try out.

I tried the approaches you mentioned (using `&::-webkit-input-placeholder`, `&::-moz-placeholder`, `&:-ms-input-placeholder`, or `::placeholder`), but none of them worked. They do not allow us to explicitly set the placeholder and the input box to have different directions.

As an alternative, I used `text-align: right`. This works, but I’m not sure whether it is the most correct approach. 


|trunk| with text-align:right|
|-|-|
|image|image|


</details>

I have added screenshots comparing the text with `direction: rtl` and `text-align: right`, specifically in Arabic. The difference lies in how the punctuation (the full stop) is placed.




Though the text is rendered correctly, the placement of the final punctuation (.) differs.


|Text align right| direction: rtl|
|-|-|
|Screenshot 2025-01-01 at 9 19 36 PM|Screenshot 2025-01-01 at 9 21 49 PM|


Here is a screen recording showing the result after I applied this CSS:

<details>
<summary> Final Code </summary>

```css
&[type='email'],
&[type='url'] {
	/* rtl:ignore */
	direction: ltr;

	[dir='rtl'] &::placeholder {
		text-align: right;
	}
}
```

</details>

https://github.com/user-attachments/assets/de8fe23b-02a2-46cb-af2b-468c13375740

I would love to hear your thoughts on this approach. Would setting the text-align of the placeholder to right when dir=rtl work as expected, or do you see any potential issues?



cc: @tyxla and @t-hamano

**Comment by t-hamano** [comment]
@im3dabasia Thank you for testing various things.

> Based on my understanding, the goal is for the placeholder text to be in RTL (right-to-left), just like plain text would be, and for the placeholder to be right-aligned within the input box. This means the placeholder text should be displayed in RTL, but the input box itself should remain rendered in LTR, with only the placeholder text aligned and displayed in RTL.

Perhaps we should first discuss whether this is an ideal behavior.

If the placeholder text is normal RTL text, it is expected to be RTL and right-aligned:

image

But the placeholder can be changed. Some developers may want to display a sample URL as the placeholder text. In this case, the right alignment may feel a bit unnatural:

image

Probably the ideal solution would be to parse the placeholder property and make it left-aligned and LTR if it's a url/email, and right-aligned and RTL otherwise, but that would be a bit more complicated to implement.

Personally, I'd prefer to always left-align regardless of what the placeholder text is. What do you think?

**Comment by im3dabasia** [comment]
> Personally, I'd prefer to always left-align regardless of what the placeholder text is. What do you think?

I agree that keeping it left-aligned would be a good option, as having different alignments for the placeholder and the input box can make things unnecessarily complicated.

Out of curiosity, I checked how other sites handle RTL languages for email input fields specifically. Here's what I found—I’ll attach some screenshots for reference. Interestingly, I noticed that they align the Arabic text to the left.

<details>
<summary> Screenshots </summary>


image

image

</details>


As @t-hamano rightly pointed out, the end developer might use a URL or email as a placeholder. In such cases, aligning the text to the right would indeed be incorrect.

**Comment by mirka** [comment]
> Personally, I'd prefer to always left-align regardless of what the placeholder text is. What do you think?

Agreed. Let's go with this for now, especially because it is simpler 😄

**Comment by tyxla** [comment]
Happy to go with the simplest way 👍

File: packages/components/CHANGELOG.md [hunk 2]
```diff
@@ -25,6 +25,7 @@
 -   `BoxControl`: Better respect for the `min` prop in the Range Slider ([#67819](https://github.com/WordPress/gutenberg/pull/67819)).
 -   `FontSizePicker`: Add `display:contents` rule to fix overflowing text in the custom size select. ([#68280](https://github.com/WordPress/gutenberg/pull/68280)).
 -   `BoxControl`: Fix aria-valuetext value ([#68362](https://github.com/WordPress/gutenberg/pull/68362)).
+-   `InputControl`: Ensures email and url inputs have consistent LTR alignment in RTL languages ([#65893](https://github.com/WordPress/gutenberg/issues/65893)).
```
Comment (t-hamano) [inline packages/components/CHANGELOG.md]:
```suggestion
-   `InputControl`: Ensures email and url inputs have consistent LTR alignment in RTL languages ([#68188](https://github.com/WordPress/gutenberg/pull/68188)).
```

This must be the pull request number, not the issue number.

**Review by t-hamano — APPROVED** [review]
LGTM! I think this is the best approach for now.

Audio block and Embed block:

| LTR language | RTL language |
|--------|--------|
| ltr-language | rtl-language |

Storybook:

https://github.com/user-attachments/assets/8ec73d71-0773-4541-9de3-beebd2cfd7ab

@WordPress/gutenberg-components I would be grateful for any additional feedback on whether it's OK to ship this PR.

File: packages/components/CHANGELOG.md (hunk 2 above)
Comment (tyxla) [reply packages/components/CHANGELOG.md]: In addition to that, it needs to be put under the "Unreleased" section, instead of under an already released one.

**Review by tyxla — COMMENTED** [review]
LGTM 👍 

Should be good to go once the CHANGELOG issues are addressed.

File: packages/components/CHANGELOG.md (hunk 2 above)
Comment (t-hamano) [reply packages/components/CHANGELOG.md]: @im3dabasia 

It would be a good idea to add a Bug Fixes section under the Unreleased section and add an entry there. Like this:

```md
<!-- Learn how to maintain this file at https://github.com/WordPress/gutenberg/tree/HEAD/packages#maintaining-changelogs. -->

## Unreleased

### Bug Fixes

-   `InputControl`: Ensures email and url inputs have consistent LTR alignment in RTL languages ([#68188](https://github.com/WordPress/gutenberg/pull/68188)).

## 29.1.0 (2025-01-02)
```

Comment (im3dabasia) [reply packages/components/CHANGELOG.md]: @tyxla and @t-hamano ,
Thank you for the guidance; I appreciate it!

File: packages/components/CHANGELOG.md [hunk 3]
```diff
@@ -25,6 +29,7 @@
 -   `BoxControl`: Better respect for the `min` prop in the Range Slider ([#67819](https://github.com/WordPress/gutenberg/pull/67819)).
 -   `FontSizePicker`: Add `display:contents` rule to fix overflowing text in the custom size select. ([#68280](https://github.com/WordPress/gutenberg/pull/68280)).
 -   `BoxControl`: Fix aria-valuetext value ([#68362](https://github.com/WordPress/gutenberg/pull/68362)).
+-   `InputControl`: Ensures email and url inputs have consistent LTR alignment in RTL languages ([#68188](https://github.com/WordPress/gutenberg/pull/68188)).
```
Comment (tyxla) [inline packages/components/CHANGELOG.md]: Sorry for the trouble, but we can now remove this one now that it's included in the "Unreleased" section.


```suggestion
```

Comment (im3dabasia) [reply packages/components/CHANGELOG.md]: @tyxla , Fixed it . Thank you for the quick review!

**Review by tyxla — APPROVED** [review]
LGTM 👍 

Thanks again @im3dabasia 🙌

**Comment by im3dabasia** [comment]
> Sorry, I'm starting to think that since the `TextControl` component is so widely used, it might be better to address it in a separate PR. Can this PR address just the `InputControl` component?

Thank you for the feedback @t-hamano ! Since the changes to the `InputControl` component have already been approved and are in the process of being merged, I was wondering if it would be okay to open a follow-up PR to address the `TextControl` component.

I can prepare a comprehensive list of all the places where changes would be required and continue working on this issue specifically for the `TextControl` component.

Let me know your thoughts on this.

**Comment by t-hamano** [comment]
@im3dabasia Can you rebase this PR so we can merge it? That should pass all the CIs (See #68484).

> I can prepare a comprehensive list of all the places where changes would be required and continue working on this issue specifically for the `TextControl` component.

Thanks, I think that's a good idea 👍

**Comment by im3dabasia** [comment]
@t-hamano , I have rebased the PR, and all the tests seem to be passing.

I request you to please merge it into trunk. 

Thank you :bow:
