### PR TITLE
Fix Spacer orientation when inside a block with default flex layout.

### LINKED ISSUE #58894: Spacer block no longer inherits orientation
### Description

When a spacer block is inserted in a navigation block which has a default horizontal orientation, the spacer block is oriented vertically.

### Step-by-step reproduction instructions

1. In a tempalte
2. Insert a navigation block
3. Add a link or two
4. Add a spacer block
5. **Notice the spacer spaces only up and down**

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/107534/27124018-bec2-4a80-9e1d-2f93b80d6779

### Environment info

Gutenberg trunk.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

Fixes #58894.

We should be checking the default layout type as well as the non-default when trying to determine Spacer block orientation based on parent layout.

This was particularly evident in the Navigation block because its default layout type is flex.

## Testing Instructions

1. Add a Spacer inside a Navigation block and check it has the correct orientation.
2. Repeat with a Row block and other blocks with layout the Spacer can be inserted into.

## Screenshots or screencast 
Screenshot 2024-02-12 at 4 28 59 pm

### CODE REVIEW

File: packages/block-library/src/spacer/edit.js [hunk 1]
```diff
@@ -93,9 +93,13 @@ const SpacerEdit = ( {
...
 	const { orientation } = context;
-	const { orientation: parentOrientation, type } = parentLayout || {};
+	const {
+		orientation: parentOrientation,
+		type,
+		default: { type: defaultType } = {},
+	} = parentLayout || {};
 	// Check if the spacer is inside a flex container.
-	const isFlexLayout = type === 'flex';
+	const isFlexLayout = type === 'flex' || defaultType === 'flex';
```
Comment (andrewserong) [inline packages/block-library/src/spacer/edit.js]: Theoretically could a block have a type that is not `flex` but also have a `defaultType` of `flex`?

For example, further down the track, if we were to add both spacers and grid layout to the Gallery block, there could be a situation where `type` is `grid` but the block still has a `defaultType` of `flex` 🤔

If we need to guard against something like that, would the following work?

```suggestion
	const isFlexLayout = type === 'flex' || ( ! type && defaultType === 'flex' );
```

Apologies if I'm overthinking it!

Comment (tellthemachines) [reply packages/block-library/src/spacer/edit.js]: Hmm yea that's a good point, it's unlikely but possible that a block sets its default as flex and enables `allowSwitching`. And your suggestion won't do any harm!

**Comment by andrewserong** [comment]
Thanks for pushing my suggestion — unfortunately it broke the linting rule, so I've just pushed a tiny commit to fix that up in https://github.com/WordPress/gutenberg/pull/58921/commits/bed3611d494b286baeb20a2a44f3d4a1aa2105ae — hope you don't mind!

**Review by andrewserong — APPROVED** [review]
All testing nicely for me, thanks for fixing this up! ✨

**Review by t-hamano — COMMENTED** [review]
While researching this issue, I found that even though this issue was occurring, the block mover button was still pointing in the correct direction.

block-mover

https://github.com/WordPress/gutenberg/blob/2325d227142624723461f0b8410da1239eb8c6a7/packages/block-editor/src/components/block-mover/index.js#L48

Maybe I'm missing something, but do you think it makes sense to apply this logic?

```javascript
	const { orientation } = useSelect(
		( select ) => {
			const {
				getBlockListSettings,
				getBlockRootClientId,
			} = select( blockEditorStore );
			const _rootClientId = getBlockRootClientId( clientId );
			return {
				orientation: getBlockListSettings( _rootClientId )?.orientation,
			};
		},
		[ clientId ]
	);
```

**Comment by t-hamano** [comment]
Immediately after I posted this comment, I found out that it had been approved 😄 I'm fine with this approach if it works as expected with the current implementation 👍

**Comment by andrewserong** [comment]
Good point @t-hamano! In this case, I think the layout logic likely still needs to be updated because whether or not it's within a flex layout will dictate if the block updates the `width/height` attributes or the `layout.flexSize` attribute?

**Comment by andrewserong** [comment]
> Immediately after I posted this comment, I found out that it had been approved 😄

Likewise, I only saw your comment after I hit the button! Very good points and observations as always 🙂

**Review by t-hamano — APPROVED** [review]
LGTM!  Sorry for confusing 🙇

**Comment by tellthemachines** [comment]
> I found that even though this issue was occurring, the block mover button was still pointing in the correct direction.
> Maybe I'm missing something, but do you think it makes sense to apply this logic?

The parent layout passed into block edit will give us the orientation, the problem was I wasn't checking the layout type in all the places it might appear. I think we should avoid using selectors if we already have what we need via the props passed to block edit.

Thanks for the suggestion in any case! And thanks everyone for reviewing!

**Comment by fabiankaegy** [comment]
Question, is this a fix that should get back ported into WordPress 6.5? 

I think given that it is a bug fix it would qualify.

**Comment by getdave** [comment]
Definitely. I see Riad has now added the label.

**Comment by youknowriad** [comment]
I just cherry-picked this PR to the backports/beta1 branch to get it included in the next release: 781dc3bf9d
