### PR TITLE
Fluid typography: ensure max viewport width is used in the editor

### LINKED ISSUE #50929: Fluid font size bug
### Description

When using Gutenberg 15.8.1 on WordPress 6.2.2, and using a FSE Block Theme (theme.json), setting a fluid font-size is producing different values in the editor vs the theme side. (Reproduced on Twenty Twenty-Three, updated description.)

In the FSE editor, its outputting 
`--wp--preset--font-size--xx-large: clamp(4rem, 4rem + ((1vw - 0.2rem) * 7.5), 10rem);`

and in the theme (and page editor), it's outputting
`--wp--preset--font-size--xx-large: clamp(4rem, 4rem + ((1vw - 0.2rem) * 10.909), 10rem);`

Difference being `7.5` vs `10.909`

I believe the FSE version is the correct value, and the page editor and theme side is incorrect.

### Step-by-step reproduction instructions

 1. Use the XX-Large font size in content
 2. Note font size in FSE editor
 3. Look at theme side (or page editor), and note different (wrong) font size.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 6.2.2
- Gutenberg 15.8.1
- Twenty Twenty-Three 1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ramonjd**
Tracking issue: 
- https://github.com/WordPress/gutenberg/issues/44888

Fixes https://github.com/WordPress/gutenberg/issues/50929

## What?
#49815 added `settings.layout.wideSize` as the default value for the maximum viewport size in relation to calculating fluid font-size values.

Unfortunately this `maxViewPortWidth` value was not being passed to `getTypographyFontSizeValue()`.

This commit correct this omission and adds extra unit tests to both the JS and PHP versions.

Props to @WraithKenny for spotting it 🙇 

## Why?
As described in #50929, the site editor is outputting the wrong value when a `settings.layout.wideSize` value is set for the  theme. This is because it is completely ignored said value.

The backend outputs the correct value since it is taking into account `settings.layout.wideSize`.

## How?
Ensuring that `settings.layout.wideSize` is passed to `getTypographyFontSizeValue()`.

## Testing Instructions

Run tests!

```shell
npm run test:unit:php -- --filter WP_Block_Supports_Typography_Test
npm run test:unit packages/block-editor/src/components/global-styles/test/use-global-styles-output.js
npm run test:unit packages/block-editor/src/components/global-styles/test/typography-utils.js 
```

You can test using twentytwentythree theme!

Add some text to the site editor and to a post. Apply a font size, e.g., `xx-large`

```html
<!-- wp:paragraph {"fontSize":"xx-large"} -->
<p class="has-xx-large-font-size">Extra extra large</p>
<!-- /wp:paragraph -->
```

Save the post/site.

Now inspect the font-size CSS value while still in the editor.

Compare this value with what you see on the frontend.

The CSS preset value should match in the post editor, site editor and frontend.

Here's the class:

```css
.has-xx-large-font-size {
	font-size: var(--wp--preset--font-size--xx-large) !important;
}
```

And the preset:

```css
-wp--preset--font-size--xx-large: clamp(4rem, 4rem + ((1vw - 0.2rem) * 10.909), 10rem);
```

If you'd like to play around with the values, here is some test HTML and JSON.

<details>

<summary>Here is some example HTML</summary>

```html
<!-- wp:paragraph {"fontSize":"medium"} -->
<p class="has-medium-font-size">Medium</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"large"} -->
<p class="has-large-font-size">Large</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"x-large"} -->
<p class="has-x-large-font-size">Extra large</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"xx-large"} -->
<p class="has-xx-large-font-size">Extra extra large</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->
```

</details>

<details>

<summary>Here is some example theme.json</summary>

```json
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"settings": {
		"appearanceTools": true,
		"layout": {
			"contentSize": "840px",
			"wideSize": "1100px"
		},
		"typography": {
			"fluid": true,
			"fontSizes": [
				{
					"fluid": {
						"min": "0.875rem",
						"max": "1rem"
					},
					"size": "1rem",
					"slug": "small"
				},
				{
					"fluid": {
						"min": "1rem",
						"max": "1.125rem"
					},
					"size": "1.125rem",
					"slug": "medium"
				},
				{
					"fluid": {
						"min": "1.75rem",
						"max": "1.875rem"
					},
					"size": "1.75rem",
					"slug": "large"
				},
				{
					"fluid": {
						"max": "125px",
						"min": "70px"
					},
					"size": "80px",
					"slug": "x-large"
				},
				{
					"fluid": {
						"max": "7.8125rem",
						"min": "4.375rem"
					},
					"size": "7.8125rem",
					"slug": "xx-large"
				}
			]
		}
	}
}

```

</details>

### CODE REVIEW

File: packages/block-editor/src/components/global-styles/utils.js [hunk 1]
```diff
@@ -73,8 +73,20 @@ export const PRESET_METADATA = [
 	},
 	{
 		path: [ 'typography', 'fontSizes' ],
-		valueFunc: ( preset, { typography: typographySettings } ) =>
-			getTypographyFontSizeValue( preset, typographySettings ),
+		valueFunc: ( preset, settings ) =>
+			getTypographyFontSizeValue(
+				preset,
+				!! settings?.typography?.fluid && settings?.layout?.wideSize
```
Comment (ramonjd) [inline packages/block-editor/src/components/global-styles/utils.js:79]: To avoid backwards compat problems I'm trying to keep the function signature the same, hence the gymnastics here.

Because we support `fluid: true` and `fluid: {...values}`, we have to ensure the param object is correctly set so that we can know if fluid typography is enabled or not.

Also, we need to pass `settings?.layout?.wideSize` if available only when fluid font sizes are enabled. 😵 

The alternative could be a third argument to the `getTypographyFontSizeValue()` function, e.g., `isFluidEnabled`. 

Or add a prop and pass the following second argument to `getTypographyFontSizeValue`:

```
{
    ....settings?.typography,
    layoutWideSize: settings?.layout?.wideSize
}

```

and move the logic there? I think that might be better.

File: packages/block-editor/src/components/global-styles/typography-utils.js [hunk 2]
```diff
@@ -20,17 +20,16 @@ import { getComputedFluidTypographyValue } from '../font-sizes/fluid-utils';
  * @property {?string|?number}               size  A default font size.
  * @property {string}                        name  A font size name, displayed in the UI.
  * @property {string}                        slug  A font size slug
- * @property {boolean|FluidPreset|undefined} fluid A font size slug
+ * @property {boolean|FluidPreset|undefined} fluid Specifics the minimum and maximum font size value of a fluid font size.
```
Comment (andrewserong) [inline packages/block-editor/src/components/global-styles/typography-utils.js]: Tiny typo

```suggestion
 * @property {boolean|FluidPreset|undefined} fluid Specifies the minimum and maximum font size value of a fluid font size.
```

File: packages/block-editor/src/components/global-styles/use-global-styles-output.js [hunk 3]
```diff
@@ -396,9 +396,22 @@ export function getStylesDeclarations(
...
 			 * and therefore the original $value will be returned.
 			 */
+			const typographySettings =
+				!! tree?.settings?.typography?.fluid &&
+				tree?.settings?.layout?.wideSize
+					? {
+							fluid: {
+								maxViewPortWidth:
+									tree?.settings?.layout?.wideSize,
+								...tree?.settings?.typography?.fluid,
```
Comment (andrewserong) [inline packages/block-editor/src/components/global-styles/use-global-styles-output.js]: Tiniest of nits, and probably no need to worry about it: the ternary for this path means that both `fluid` and `wideSize` are truthy, so I don't think we need the optional chaining on these two lines? (we still do need it below)

File: packages/block-editor/src/components/global-styles/utils.js (hunk 1 above)
Comment (andrewserong) [reply packages/block-editor/src/components/global-styles/utils.js:79]: It is a bit of gymnastics to maintain back compat, but I actually don't mind it how it's written as-is, as it means that the calling code is responsible for ensuring that the spread `settings.typography.fluid` overrides the `maxViewPortWidth` set via the layout `wideSize`, and the `getTypographyFontSizeValue` doesn't have to work too hard to figure it out.

That said, adding `layoutWideSize` to `TypographySettings` could be a clever way to do it, then it'd be fairly straightforward to use `layoutWideSize` only if `maxViewPortWidth` doesn't exist.

Whatever you think works best, I don't think I mind either way, personally!

**Review by andrewserong — APPROVED** [review]
Nice work @ramonjd, this is testing well for me. I see in #50929 the issue report mentioned thinking that the FSE version looked correct, but the page editor / site frontend version seemed inconsistent. I think the change in this PR is the right way around, as it's rolling out the `wideSize` max viewport width approach to the site editor 👍

✅ Confirmed the issue on `trunk` using TT3
✅ Confirmed with this PR applied, the calculated fluid sizes now match between site editor and site frontend

| Before (the font size is smaller in the site editor) | After (the font size is larger in the site editor) |
| --- | --- |
| image | image |

LGTM! ✨

File: packages/block-editor/src/components/global-styles/typography-utils.js (hunk 2 above)
Comment (ramonjd) [reply packages/block-editor/src/components/global-styles/typography-utils.js]: Whoops, copy and pasta from [theme.json schema](https://github.com/WordPress/gutenberg/blob/2afe3577c8e8764d228749817985bd026c87d203/schemas/json/theme.json#L490-L490) 😮‍💨 I'll fix both. Thanks!

File: packages/block-editor/src/components/global-styles/use-global-styles-output.js (hunk 3 above)
Comment (ramonjd) [reply packages/block-editor/src/components/global-styles/use-global-styles-output.js]: By gum, you're right! Good spotting. Fixing...

File: packages/block-editor/src/components/global-styles/utils.js (hunk 1 above)
Comment (noisysocks) [reply packages/block-editor/src/components/global-styles/utils.js:79]: Not all that familiar with this part of the codebase so take this with a large grain of salt.

What if we extract all of the code in `getTypographyFontSizeValue` that transforms the `settings.typography` object into an object that's suitable for passing to `getComputedFluidTypographyValue` into a new function?

That way `valueFunc` can set `maximumViewPortWidth` on a normalised object and not have to deal with the intricacies of parsing the `settings.typography.fluid` boolean / object.

```js
valueFunc: ( preset, settings ) => {
	const fluidTypographySettings = getFluidTypographySettings( settings?.typography );
	fluidSettings.maximumViewPortWidth = settings?.layout?.wideSize;
	return getComputedFluidTypographyValue( fluidSettings );
},
```

Comment (noisysocks) [reply packages/block-editor/src/components/global-styles/utils.js:79]: I don't think what you have is that bad though. This suggestion is for if it's really bugging you 😀

Comment (ramonjd) [reply packages/block-editor/src/components/global-styles/utils.js:79]: > What if we extract all of the code in getTypographyFontSizeValue that transforms the settings.typography object into an object that's suitable for passing to getComputedFluidTypographyValue into a new function?

yes

#### yes


### YES!


`packages/block-editor/src/components/global-styles/typography-utils.js` exists for a reason 😄

Comment (ramonjd) [reply packages/block-editor/src/components/global-styles/utils.js:79]: > I don't think what you have is that bad though. This suggestion is for if it's really bugging you 😀

Thanks for helping @noisysocks and @andrewserong 

I might merge as is and mark [this suggestion ](https://github.com/WordPress/gutenberg/pull/51146#discussion_r1212602061)for a follow up, since it might come in handy down the track.

**Comment by WraithKenny** [comment]
This didn't make it into 16.0.0? 

Edit: Never mind; I see that it did, but it didn't take into account values for content width that are css functions.

**Comment by ramonjd** [comment]
> I see that it did, but it didn't take into account values for content width that are css functions.

Thanks, I'll take a look. For now I think we should ignore CSS functions in the layout object for the purposes of calculating the linear scale factor.

**Comment by andrewserong** [comment]
> For now I think we should ignore CSS functions in the layout object for the purposes of calculating the linear scale factor.

Same — it's good to know that there's the use case of themes that use css functions in these values, but I think it's probably best to ignore them for now as it'd be difficult to reliably use them for the calculation.

**Comment by WraithKenny** [comment]
Alternatively, we could use css calc directly, and not have to deal with php calculations. My understanding that it was a simple enhancement (using log) that created this overhead, and maybe we could reduce a ton of complexity by not doing that.

Regardless, I've "solved" my problem by maintaining my own duplicated css overrides and not using the WP calculations at all.

**Comment by ramonjd** [comment]
> My understanding that it was a simple enhancement (using log) that created this overhead, and maybe we could reduce a ton of complexity by not doing that.

I believe the calculation was always going to run into trouble with CSS functions, even before the [log change](https://github.com/WordPress/wordpress-develop/pull/4605). The way the linear factor is calculated hasn't changed. The log calculation only affected the minimum font size.

See: 

https://github.com/WordPress/wordpress-develop/pull/4605/files#diff-5a0816c84e79d4906f109a954660c8548243cf0aad0f0aa06fadf1f204d608c4L441

Once things have stabilized, there's also the opportunity to introduce some filters that might open the doors to greater flexibility and control for devs/theme authors.

> Regardless, I've "solved" my problem by maintaining my own duplicated css overrides and not using the WP calculations at all.

👍

**Comment by WraithKenny** [comment]
The linear version is possible in css using calc() and var()s. I have a separate ticket about it 😄

**Comment by WraithKenny** [comment]
@ramonjd Thanks for all your work here.

In case you are interested, I have a working version of the CSS only equation:
```CSS
:root {
	--large: 1600;
	--small: 960;

	--max: 25;
	--min: 10;

	--rem: 16;
}

* {
	--func--fluid-rem: clamp(
		calc(var(--min) * 1px),
		calc((var(--min) / var(--rem) * 1rem) + ( ( 100vw - (var(--small) * 1px) ) * ((var(--max) - var(--min)) / (var(--large) - var(--small))) )),
		calc(var(--max) * 1px)
	);
}

.use-css-func {
	--max: 22;
	--min: 18;
	font-size: var(--func--fluid-rem);
}
```

```html
<div class="use-css-func" style="--max: 50;--min: 20;">
```
Bonus: It takes into account both breakpoints, and is customizable via `var()`s which can be passed in via `style` attributes (rather than rules with `!important` declarations in a style sheet).

**Comment by ramonjd** [comment]
Nice, thanks for posting that. It might come in handy down the track ;)
