### PR TITLE
Core Data: Fix errors when the entities list doesn't contain config key

### LINKED ISSUE #62311: Data: Stores become unresponsive when batched actions trigger an error
### Description

Possible solution: change from `catch` statement to `finally` statement in this line https://github.com/WordPress/gutenberg/blob/trunk/packages/core-data/src/resolvers.js#L298

### Step-by-step reproduction instructions

Execute `useEntityRecords('root', 'site')` inside the edit function of a block.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WordPress 6.6 beta 1
Twenty-Twenty Four
Chrome
Desktop with Windows 11

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes #62311.

PR fixes errors when data returned by the endpoint for `getEntityRecords` doesn't contain config or default `key` property.

## Testing Instructions
1. Open a post or page.
2. Run selector via Console - `wp.data.select( 'core' ).getEntityRecords( 'root', 'site' );.`
3. Check the errors via - `wp.data.select( 'core' ).getResolutionError( 'getEntityRecords', [ 'root', 'site' ] );`.
4. You can also set a logpoint [here](https://github.com/WordPress/gutenberg/blob/0011ca615e4d5424e7220fc363a443bf62fe0852/packages/core-data/src/resolvers.js#L299). 

### Testing Instructions for Keyboard
Same.

### CODE REVIEW

**Comment by Mamaduka** [comment]
I think I broke a few things, I will investigate them tomorrow.

File: packages/core-data/src/queried-data/reducer.js [hunk 1]
```diff
@@ -110,7 +110,8 @@ export function items( state = {}, action ) {
 				[ context ]: {
 					...state[ context ],
 					...action.items.reduce( ( accumulator, value ) => {
-						const itemId = value[ key ];
+						const itemId = value?.[ key ];
```
Comment (Mamaduka) [inline packages/core-data/src/queried-data/reducer.js:113]: It turns out that `undefined` is a "valid" item ID, and site settings are keyed using it.

## Screenshot
CleanShot 2024-06-06 at 00 13 33

File: packages/core-data/src/queried-data/reducer.js [hunk 2]
```diff
@@ -232,7 +233,7 @@ const receiveQueries = compose( [
 	return {
 		itemIds: getMergedItemIds(
 			state?.itemIds || [],
-			action.items.map( ( item ) => item[ key ] ),
+			action.items.flatMap( ( item ) => item?.[ key ] ?? [] ),
```
Comment (tyxla) [inline packages/core-data/src/queried-data/reducer.js]: Won't `action.items` be an array of objects? If that's the case, it feels odd if `item?.[ key ]` falls back to an empty array.

**Review by tyxla — COMMENTED** [review]
While the proposed changes look mostly safe, I wasn't able to reproduce the original error, so I can't confirm that this PR resolves it. I've been following the testing instructions from this PR on `trunk`, but no error appears. Any idea what I might be missing?

**Comment by Mamaduka** [comment]
@tyxla, if you log errors [here](https://github.com/WordPress/gutenberg/blob/0011ca615e4d5424e7220fc363a443bf62fe0852/packages/core-data/src/resolvers.js#L299) on trunk and call the selector from testing instructions you should be able to reproduce the error.

File: packages/core-data/src/queried-data/reducer.js (hunk 2 above)
Comment (Mamaduka) [reply packages/core-data/src/queried-data/reducer.js]: This line extracts the `nextItemIds` array. It's usually an array of `key` items. When every key is `undefined` we want to pass an empty array.

This `flatMap` pattern is from [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#mapped_array_contains_undefined). It's the same as `items.map( ( item ) => item?.[ key ] ).filter( ( itemId ) => itemId !== undefined );`

Should I use explicit iteration?

Comment (tyxla) [reply packages/core-data/src/queried-data/reducer.js]: Thanks for confirming. I think this is too idiomatic for most tastes though - I know the pattern and still didn't think of it when I first saw it. I think when one sees `.flatMap()` they expect this works with nested arrays, and this isn't the case here, so it could create false expectations. The fact that this area of the code isn't properly typed doesn't make it better. So yes, if I could choose, I'd prefer being more explicit here.

**Comment by tyxla** [comment]
> @tyxla, if you log errors [here](https://github.com/WordPress/gutenberg/blob/0011ca615e4d5424e7220fc363a443bf62fe0852/packages/core-data/src/resolvers.js#L299) on trunk and call the selector from testing instructions you should be able to reproduce the error.

Correct, when I add logging there, I see the error logged, but I still don't understand in what circumstances it will actually be manifested as an error - it's supposed to be caught there, no?

**Comment by Mamaduka** [comment]
The error can occur when a response for `getEntityRecords` doesn't return a correctly shaped object. The requirement should be a list of objects containing a primary key (defined in config, defaulting to `id`). Related discussion: #61348.

The example site entity used here returns a single object with properties for the `/settings` endpoint, which triggers an error in reducers.

File: packages/core-data/src/queried-data/reducer.js [hunk 3]
```diff
@@ -232,7 +233,9 @@ const receiveQueries = compose( [
 	return {
 		itemIds: getMergedItemIds(
 			state?.itemIds || [],
-			action.items.map( ( item ) => item[ key ] ),
+			action.items
+				.map( ( item ) => item?.[ key ] )
+				.filter( ( itemId ) => itemId ),
```
Comment (tyxla) [inline packages/core-data/src/queried-data/reducer.js]: `filter( Boolean )` is yet another idiomatic way to do the same thing:

```suggestion
				.filter( Boolean ),
```

**Review by tyxla — APPROVED** [review]
Changes look safe and good to go 👍 

Thanks @Mamaduka 🚀

File: packages/core-data/src/queried-data/reducer.js (hunk 3 above)
Comment (Mamaduka) [reply packages/core-data/src/queried-data/reducer.js]: Yeah, that's a nice shorthand. I went back and forth with filter's predicate, then decided to keep the current version.

Comment (tyxla) [reply packages/core-data/src/queried-data/reducer.js]: Up to you, it's not a big deal. Thanks 👍

Comment (Mamaduka) [reply packages/core-data/src/queried-data/reducer.js]: I had to rebase and included the update.

**Comment by ellatrix** [comment]
Worth backporting?

**Comment by Mamaduka** [comment]
This is probably not a new bug, but it's worth backporting alongside the #62322.

**Comment by ellatrix** [comment]
This was cherry-picked to the wp/6.6 branch.
