### PR TITLE
Fix: Missing 'No blocks found.' message for block search in editor 

### LINKED ISSUE #69035: Editor: Missing 'No blocks found.' message for block search in editor
### Description

Discovered while working on https://github.com/WordPress/gutenberg/issues/68688

Currently, when searching for a block in the Block option inside the Styles section, a blank white column appears if no results are found. This creates an inconsistency, as other search options provide feedback messages like “No Results” or “No blocks found.” To maintain consistency and improve user experience, introducing a message such as “No blocks found.” in this case would be a great enhancement.

### Step-by-step reproduction instructions

1. Open Editor 
2. Go to styles 
3. Open Blocks
3. Search for a block that doesn't exist 
4. Notice the absence of text 'No blocks found.' on the blank white column 

### Screenshots, screen recording, code snippet

Image

### Environment info

- WordPress 6.7.1
- Gutenberg 20.2.0-rc.1
- MacOS 15.2 
- Chrome 

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by Rishit30G**
## What?
Closes #69035 

## Why?
This PR is intended to resolve the issue of absence of 'No blocks found.' text when there is an unsuccessful search for the blocks  

## How?
Added a check to ensure that when no search results are found, the text “No blocks found.” is rendered.

## Testing Instructions
1. Open Editor 
2. Go to styles 
3. Open 'Blocks'
3. Search for a block that doesn't exist 
4. Notice the presence of text 'No blocks found.' on the blank white column 

## Screenshots 

|Before|After|
|------|------|
Image | image

### CODE REVIEW

File: packages/edit-site/src/components/global-styles/screen-block-list.js [hunk 1]
```diff
@@ -138,12 +138,18 @@ function BlockList( { filterValue } ) {
...
-			{ filteredBlockTypes.map( ( block ) => (
-				<BlockMenuItem
-					block={ block }
-					key={ 'menu-itemblock-' + block.name }
-				/>
-			) ) }
+			{ filteredBlockTypes.length === 0 ? (
+				<div className="block-editor-inserter__no-results">
+					<p>{ __( 'No blocks found.' ) }</p>
+				</div>
```
Comment (Mamaduka) [inline packages/edit-site/src/components/global-styles/screen-block-list.js]: Do we want to use the `block-editor-inserter__no-results`, the Inserter-specific class name in Global Styles components?

I think the same design can be achieved by using the [`Text`](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-text--docs) component, and no additional CSS should be required.

Comment (Rishit30G) [reply packages/edit-site/src/components/global-styles/screen-block-list.js]: Thanks for the feedback @Mamaduka 👍🏻 

The current implementation in my code follows the approach used for rendering other “no result” blocks on different pages, utilising the `className="block-editor-inserter__no-results"`. I implemented it the same way to maintain consistency. 🙇🏻 

Based on the feedback I'm sharing some code snippet and screenshot, tho we don't require additional CSS but we need that `className`, please let me know which one should go with 

Code: 
```jsx
<Text>
    { __( 'No blocks found.' ) }
</Text>
```
Screenshot: 
image


Code: 
```jsx
<div className="block-editor-inserter__no-results">
	<Text>
		{ __( 'No blocks found.' ) }
	</Text>
</div>
```

Screenshot: 
image

Comment (Mamaduka) [reply packages/edit-site/src/components/global-styles/screen-block-list.js]: The `block-editor-inserter__no-results` is a subclass of a different component; it's not a generic class name. It can be removed or changed if the block editor inserter is refactored, which will break styling in Global Styles.

The plain `Text` wrapper won't work; the [Stylebook](https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-text--docs) lists various properties you can use. Try using following.

```js
<Text
  align="center"
  as="p"
>
  ...
</Text>
```

Comment (Rishit30G) [reply packages/edit-site/src/components/global-styles/screen-block-list.js]: Makes sense, I was relying on that classname as I could find it evident across the codebase for the "no results" sections, my bad 🙇🏻 

I have updated my PR with the feedback, thanks!

Comment (Mamaduka) [reply packages/edit-site/src/components/global-styles/screen-block-list.js]: Thanks for the followup, @Rishit30G!

**Review by Mamaduka — APPROVED** [review]
