### PR TITLE
wp-env: Correctly parse basename for wporg zip sources

### LINKED ISSUE #22301: env: Using Zip file URLs for plugins prevents their assets from being served
**Describe the bug**
When I use `.zip` file URLs from WordPress.org for plugins in the `.wp-env.json` file, the mounted directory name contains characters that prevent WordPress from accessing the plugin's static assets.

**To reproduce**
1. Create a new blank project with a `.wp-env.json` file
2. Add `https://downloads.wordpress.org/plugin/woocommerce.4.1.0.zip` as a plugin dependency for the environment
3. Run `wp-env start`
4. Log in and browse to `http://localhost:8888/wp-admin/index.php?page=wc-setup`
5. The browser's dev tools show the requests for scripts and styles return a 404 response.

**Expected behavior**
I expected the browser to be able to access these assets the way it accesses the core static assets. 

**Screenshots**
Screen Shot 2020-05-12 at 10 04 00 AM
Screen Shot 2020-05-12 at 4 11 49 PM

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default (I think)
- If the Gutenberg plugin is installed, which version is it? N/A

**Desktop (please complete the following information):**
 - OS: OS X Mojave
 - Browser Firefox
 - Version 76.0.1 (64-bit)

**Additional context**
- I _think_ this might stem from the characters in the name of the mounted plugin directory.  If I download and unzip the file myself, I can specify the local path to the resulting folder,  and `wp-env` works as expected.
- Based on some cursory testing, it looks like the characters don't pose a problem locally; it's only when they're used as part of the virtual directory name on the container that they cause issues.

### PR DESCRIPTION
**Pull request by torounit**
## Description
In the case of plugin/theme from downloads.wordpress.org,  use the directory name as the name of the plugin/theme.

``` wp-env.json
{
	"plugins": [
		"https://downloads.wordpress.org/plugin/wordpress-importer.0.7.zip"
	],
}
```

before
```
downloads.wordpress.org%2Fplugin%2Fwordpress-importer.0.7
```

after
```
wordpress-importer
```

## How has this been tested?

config wp-env.json

```
{
	"core": "WordPress/WordPress",
	"plugins": [
		".",
		"https://downloads.wordpress.org/plugin/wordpress-importer.zip",
		"https://downloads.wordpress.org/plugin/debug-bar.1.0.zip"
	],
	"themes": [
		"https://downloads.wordpress.org/theme/go.zip",
		"https://downloads.wordpress.org/theme/chaplin.2.4.2.zip"
	]
}
```

run ` ./packages/env/bin/wp-env start`

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/env/lib/config.js [hunk 1]
```diff
@@ -257,9 +257,25 @@ function parseSourceString( sourceString, { workDirectoryPath } ) {
...
+	);
+	if ( wpOrgFields ) {
+		return {
+			type: 'zip',
+			url: sourceString,
+			path: path.resolve(
+				workDirectoryPath,
+				encodeURIComponent( wpOrgFields[ 2 ] )
+			),
+			basename: encodeURIComponent( wpOrgFields[ 2 ] ),
```
Comment (noahtallen) [inline packages/env/lib/config.js:271]: should we just make this apply to the `zipFields` thing below, and use the second index instead of the first? I guess a reason to not do that would be to allow zip sources from elsewhere to continue working :)

**Review by noahtallen — APPROVED** [review]
I think this is a good addition. It should make zip sources a lot easier to work with.

**Comment by noahtallen** [comment]
I think this needs rebased and it is probably good to go. Imo, it would also be ideal if we just use the zip type for this instead of creating new source types. E.g. inside the zip type condition, check to see if it is also a wporg source, and then set the basename & path correctly in that situation.

**Comment by torounit** [comment]
Fix to use zip source type. @noahtallen

File: packages/env/lib/config.js [hunk 2]
```diff
@@ -293,9 +293,25 @@ function parseSourceString( sourceString, { workDirectoryPath } ) {
 		};
 	}
 
+	const wpOrgFields = sourceString.match(
+		/^https?:\/\/downloads\.wordpress\.org\/(?:plugin|theme)\/([^\s\.]*)([^\s]*)?\.zip$/
+	);
+	if ( wpOrgFields ) {
+		return {
+			type: 'zip',
```
Comment (noahtallen) [inline packages/env/lib/config.js:301]: could this just be added to the zipFields section below?

**Comment by noisysocks** [comment]
Should we do this for **all** ZIP URLs and not just ones hosted on `downloads.wordpress.org`? For example, `example.com/uploads/my-plugin.2.zip` can extract into `my-plugin.2`.

File: packages/env/lib/config.js [hunk 3]
```diff
@@ -293,9 +293,25 @@ function parseSourceString( sourceString, { workDirectoryPath } ) {
...
+			url: sourceString,
+			path: path.resolve(
+				workDirectoryPath,
+				encodeURIComponent( wpOrgFields[ 1 ] )
+			),
+			basename: encodeURIComponent( wpOrgFields[ 1 ] ),
+		};
+	}
+
```
Comment (noisysocks) [inline packages/env/lib/config.js:310]: `parseSourceString` has unit tests. These should be updated to test this new functionality.

Comment (torounit) [reply packages/env/lib/config.js]: added unit tests.

**Comment by torounit** [comment]
@noisysocks Is it better to keep the version number in the directory name?

**Comment by noahtallen** [comment]
> Should we do this for all ZIP URLs

since we can know (being a WordPress tool and all) that wporg URLs always look this way, maybe that makes it easier to just support the wporg format? Do we know enough to guarantee a different zip source will use a format we can understand?

Though, I guess if it's just `https://someurl/path/to/x-y-z.zip`, then we could just match everything between the last `/` and `.zip`.

**Comment by noahtallen** [comment]
I'm gonna merge this so that it can at least be fixed for wporg sources for now. I think we can expand this behavior as a follow up without blocking it for wporg sources :)

**Comment by epiqueras** [comment]
I think that other URLs are more likely to have conflicting basenames.
