### PR TITLE
Embed: fix select on focus

### LINKED ISSUE #29374: Embed: Can't focus Embed block when empty
## Description

In certain cases, the Embed block may fail to embed a source and not realise that it has failed (https://github.com/WordPress/gutenberg/issues/29429). When this happens, the Embed block is rendered as an invisible rectangle that can't be focused with the cursor.

## Step-by-step reproduction instructions
1. In an empty post, paste `https://woocommerce.com/experts/neuralab/`.
2. The console should reveal the following failure: `Refused to display 'https://woo...' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.`.
3. An Embed block "appears" as an invisible rectangle.
4. Try unselecting the block and re-selecting it using the cursor. **No selection occurs.**

## Screenshots or screen recording (optional)

Captura de ecrã 2021-02-26, às 12 38 17

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #29374. We switched to using the `focusin` event type instead of `focus` for detecting block selection.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ellatrix** [comment]
I tried to write an e2e test, but I can't emulate clicking in an iframe that is loading another web page.

**Comment by mcsf** [comment]
Thanks for looking at this! I'm still unable to re-focus the Embed block, though:

failed-embed-focus

1. Paste URL that generates faulty Embed. Embed is focused: good.
2. Click below the Embed. Paragraph is focused: good.
3. Click on the Embed's empty canvas. Embed does not receive focus: not good.

**Comment by ellatrix** [comment]
@mcsf What browser are you using? It seems to work fine for me.

embed-select

**Comment by ellatrix** [comment]
I think #29892 is affecting testing here too.

**Comment by ellatrix** [comment]
@mcsf I rebased the PR. Does it work correctly now?

File: packages/block-library/src/embed/wp-embed-preview.js [hunk 1]
```diff
@@ -58,8 +58,15 @@ export default function WpEmbedPreview( { html } ) {
...
-			activeElement.dispatchEvent( focusEvent );
+			// The focus event should *not* bubble:
+			// https://w3c.github.io/uievents/#event-type-focus
+			activeElement.dispatchEvent( new FocusEvent( 'focus' ) );
+
+			// The focusin event *should* bubble:
+			// https://w3c.github.io/uievents/#event-type-focusin
+			activeElement.dispatchEvent(
+				new FocusEvent( 'focusin', { bubbles: true } )
+			);
```
Comment (diegohaz) [inline packages/block-library/src/embed/wp-embed-preview.js]: Can't we just do this?
```suggestion
			activeElement.focus();
```

**Review by diegohaz — COMMENTED** [review]
I tested it on Chrome and Safari and it's working.

Two things though (not necessarily blockers):

- I can't see the blue border when selecting the block with the mouse. And, because of that, I guess, I can't remove the block by pressing delete.
- I'm not sure if we have some kind of polyfill or something, but the `FocusEvent` constructor doesn't work on IE11. It's better if we can just use `activeElement.focus()`.

File: packages/block-library/src/embed/wp-embed-preview.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-library/src/embed/wp-embed-preview.js]: This was first introduced in 5730. I didn't think it would work, but it does. The right window seems to stay focussed and I can keyboard navigate as you would expect.

File: packages/components/src/focusable-iframe/index.js [hunk 2]
```diff
@@ -23,21 +22,15 @@ export default function FocusableIframe( { iframeRef, onFocus, ...props } ) {
 				return;
 			}
 
-			const focusEvent = new FocusEvent( 'focus', { bubbles: true } );
-
-			iframe.dispatchEvent( focusEvent );
-
-			if ( onFocus ) {
-				onFocus( focusEvent );
```
Comment (ellatrix) [inline packages/components/src/focusable-iframe/index.js:31]: We no longer need this since React will fire the right handlers when the element receives focus.

**Comment by ellatrix** [comment]
Once this is approved and merged, I'll rebase #26753 to make this API better and reduce duplication.

File: packages/components/src/focusable-iframe/index.js (hunk 2 above)
Comment (ellatrix) [reply packages/components/src/focusable-iframe/index.js:31]: Note that React will even call the right handlers with `new FocusEvent`. I'm not sure why this was ever added, but it was assumed React wouldn't pick it up.

**Comment by mcsf** [comment]
> @mcsf I rebased the PR. Does it work correctly now?

@ellatrix: yes, thank you! I was/am on Safari, for the record.

**Comment by ellatrix** [comment]
Ok, merging since the intention of this PR is fulfilled. I'll have a look into why Backspace is not removing the embed separately.
