### PR TITLE
Global Styles: Presets: Show the default empty variation as well as the other presets

### LINKED ISSUE #59574: Typography presets in global styles: unexpected behavior
### Description

The typography presets recently added by https://github.com/WordPress/gutenberg/pull/56622 seem to behave unexpectedly.

- [x] When you click on a font, you get a list of available font faces for another font in the modal. In the video when user clicks on, let's say, "Instrument Sans" depending of the preset selected previously the modal open showing "Inter", "Cardo" or other font face list. It feels buggy and we should certainly improve that.
Potentially fixed by: https://github.com/WordPress/gutenberg/pull/59959

- [x] Once selected, a preset can not be unselected.
Pontentially fixed by: https://github.com/WordPress/gutenberg/pull/59717

- [x] Font faces defined in variations aren't loaded in the browser until the variation switch is saved and the page is refreshed.
Issue: https://github.com/WordPress/gutenberg/issues/59965

- [ ] Custom-installed font families are unactivated when switching to a style variation.
Potentially fixed by: https://github.com/WordPress/gutenberg/pull/59921

### Step-by-step reproduction instructions

1. Activate a theme using style variations.
2. Navigate to the global styles panel
3. Use the typography presets recently added.

### Screenshots, screen recording, code snippet

Changing the name of fonts and opening the modal with a different font name:

https://github.com/WordPress/gutenberg/assets/1310626/056d9810-f166-473f-89fe-b4cac5027779

Once set, a preset can not be unset:

https://github.com/WordPress/gutenberg/assets/1310626/b90c8998-e2ce-4e11-bd8c-ace4fc8381ff

### Environment info

- WordPress 6.4.3
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by scruffian**
## What?
This shows the default preset as well as the variations...

## Why?
...so that users can set them back to the original settings that came with the theme.

## How?
Add empty default variations to the ones we fetch from the store.

Fixes https://github.com/WordPress/gutenberg/issues/59574

## Testing Instructions
1. Open the Site Editor
2. Open Global Styles > Colors
3. Check that the first item is the default theme setting
2. Open Global Styles > Typography
3. Check that the first item is the default theme setting

## Screenshots or screencast 
Screenshot 2024-03-08 at 17 19 15
Screenshot 2024-03-08 at 17 19 08

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
I think this is a very important step that could open up solutions for multiple problems. One of those is the fact that whenever a user makes changes to their global styles, those get lost if the user changes to a different style variation. This makes sense in a way since the user changes are being saved on top of the default variation, which we had no way to go back to before this PR besides undoing the user changes.

I wonder if the next step is to create a "user" variation under the presets that is independent of the default presets and can persist regardless of the default preset chosen by the user.

File: packages/edit-site/src/components/global-styles/hooks.js [hunk 1]
```diff
@@ -99,15 +99,35 @@ export function useSupportedStyles( name, element ) {
...
+		property: 'color',
+	} );
+	/*
+	 * Filter out variations with no settings or styles.
+	 */
+	return colorVariations?.length
+		? colorVariations.filter( ( variation ) => {
+				const { settings, styles, title } = variation;
+				return (
+					title === 'Default' || // Always preseve the default variation.
```
Comment (MaggieCabrera) [inline packages/edit-site/src/components/global-styles/hooks.js]: We probably need this to be translateable

Comment (scruffian) [reply packages/edit-site/src/components/global-styles/hooks.js]: Done in [3a0eb63](https://github.com/WordPress/gutenberg/pull/59717/commits/3a0eb635446cb944102a74fdef2c3db7fdb6184c)

**Review by MaggieCabrera — APPROVED** [review]
LGTM! I think this is a very nice adition

**Comment by ndiego** [comment]
Somehow, it looks like this functionality was reverted. The most recent GB release looks like this. Note that the default color "empty" variation is no longer displayed. 

image

**Comment by scruffian** [comment]
It seems to be working OK on the latest trunk.
