### PR TITLE
Replace placeholder handling for MediaPlaceholder instructions

### LINKED ISSUE #10855: Don't use string fragments to build instructions in MediaPlaceholder
**Describe the bug**

Components which are using `MediaPlaceholder` are passing a string like ["an image or a video"](https://github.com/WordPress/gutenberg/blob/c3501c7bb70093495d9977cf37c3ef71112e9a38/packages/block-library/src/cover/index.js#L324) which is used to replace the placeholder in the [instructions](https://github.com/WordPress/gutenberg/blob/9066b8c81a79e286be43c17f3b5cd84f8d459a9b/packages/editor/src/components/media-placeholder/index.js#L166) string. This should be avoided in general due to different grammar rules in other languages.

**Screenshots**
cover

**Additional context**
We should use separate strings for this and maybe use a generic one as default.

### PR DESCRIPTION
**Pull request by ocean90**
## Description
Fixes #10855.

* Removes `labels.name`
* Builds `instructions` string based on allowed types
* Adds support for `labels.instructions`

## How has this been tested?
Add blocks with media uploads and verify that all instructions still make sense. Run `npm run test` to check unit tests.

### CODE REVIEW

File: packages/editor/src/components/media-placeholder/index.js [hunk 1]
```diff
@@ -158,12 +158,26 @@ class MediaPlaceholder extends Component {
...
+
+			if ( isEmpty( difference( allowedTypes, [ 'video' ] ) ) ) {
+				instructions = __( 'Drag a video, upload a new one or select a file from your library.' );
+			} else if ( isEmpty( difference( allowedTypes, [ 'image' ] ) ) ) {
+				instructions = __( 'Drag an image, upload a new one or select a file from your library.' );
+			} else if ( isEmpty( difference( allowedTypes, [ 'audio' ] ) ) ) {
+				instructions = __( 'Drag an audio, upload a new one or select a file from your library.' );
+			} else if ( isEmpty( difference( allowedTypes, [ 'image', 'video' ] ) ) ) {
+				instructions = __( 'Drag an image or a video, upload a new one or select a file from your library.' );
+			}
```
Comment (youknowriad) [inline packages/editor/src/components/media-placeholder/index.js]: Instead of adding all these if/else here, can we use just a generic string here and pass these as props where appropriate? that way we stay consistent in how we deal with labels in this component.

Comment (youknowriad) [reply packages/editor/src/components/media-placeholder/index.js]: I also wonder if we should have a generic "Media" in the text if the `allowedTypes` contains more than one item.

File: packages/editor/src/components/media-placeholder/index.js [hunk 2]
```diff
@@ -158,12 +158,46 @@ class MediaPlaceholder extends Component {
...
+			if ( ! instructions ) {
+				instructions = __( 'Drag a media file, upload a new one or select a file from your library.' );
+
+				if ( isVideo ) {
+					instructions = __( 'Drag a video, upload a new one or select a file from your library.' );
+				} else if ( isImage ) {
+					instructions = __( 'Drag an image, upload a new one or select a file from your library.' );
+				} else if ( isAudio ) {
+					instructions = __( 'Drag an audio, upload a new one or select a file from your library.' );
+				} else if ( isImageAndAudio ) {
```
Comment (youknowriad) [inline packages/editor/src/components/media-placeholder/index.js]: Do you think we should leave this one as a prop (image and video) as it seems too specific to be bundled in the component?

Comment (ocean90) [reply packages/editor/src/components/media-placeholder/index.js]: Good point, I already left out the title definition for this case.

File: packages/editor/src/components/media-placeholder/index.js (hunk 1 above)
Comment (ocean90) [reply packages/editor/src/components/media-placeholder/index.js]: This is already the case in https://github.com/WordPress/gutenberg/pull/10861/files#diff-56d6af193779467f7a4cb10e85c26ef3R170, unless I'm missing something.

**Review by youknowriad — APPROVED** [review]
Thanks for the updates. LGTM 👍

File: packages/editor/CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,13 @@
+## 6.0.0 (unreleased)
+
+### Breaking Changes
+
+- The `labels.name` property has been removed from `MediaPlaceholder` in favor of the new `labels.instructions` prop.
```
[the remark this answers is not in the document]
Comment (ocean90) [reply packages/editor/CHANGELOG.md]: I agree, the deprecation handling is actually the new handling for default title/instructions. No JS errors or similar will be produced by this change.
