### PR TITLE
Templates: Fix empty block templates output string

### LINKED ISSUE #20276: Empty Block Templates output string on front-end stating "Empty Template".
**Describe the bug**
If a block template has no content in post_content, instead of seeing a blank page (which would match the template), a string is output on the front-end stating "Empty Template", even for logged-out users.

Screen Shot 2020-02-17 at 4 42 30 PM

**To reproduce**
1. On a fresh install, create a Block Based Theme with just a single.html file, and put no content in that file. 
2. View the "Hello World" post.
3. See the message that states "Empty template.".
4. Log out. 
5. Notice you still see that message.

**Expected behavior**
I would expect 2 things here:
- If logged-out, I would expect to see a blank page on the front-end, which matches the template.
- If logged-in with admin-level capabilities, an error might appear stating "The single.html template was blank", thought this is likely better shown in wp-admin, rather than on the front-end.

**Desktop (please complete the following information):**
- OS: MacOS Catalina
- Browser: Chrome
- Version 79.0.3945.130 (Official Build) (64-bit)

**Additional context**
The code for this is happening here:
https://github.com/WordPress/gutenberg/blob/a8e49fc6deea5fb72a16666ec32d287d431e5697/lib/template-loader.php#L99

- Gutenberg version: `master`.

### PR DESCRIPTION
**Pull request by carolinan**
## Description

Fixes https://github.com/WordPress/gutenberg/issues/20276

Hides the "empty template" messages from logged out visitors.
Adds the template title to the message. Example message: Empty template: Index.

## How has this been tested?

1. Follow the instructions in the GitHub issue to reproduce the problem.
2. When logged in:  confirm that the message shows on the front and that the title of the template is included.
3. When logged out: confirm that the message does not show on the front.

## Types of changes

Enhancement

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: lib/full-site-editing/template-loader.php [hunk 1]
```diff
@@ -79,8 +79,16 @@ function gutenberg_override_query_template( $template, $type, array $templates =
 	}
 
 	if ( $current_template ) {
-		$_wp_current_template_content = empty( $current_template->content ) ? __( 'Empty template.', 'gutenberg' ) : $current_template->content;
-
+		if ( empty( $current_template->content ) && isset( $current_template->title ) && is_user_logged_in() ) {
```
Comment (ntsekouras) [inline lib/full-site-editing/template-loader.php]: I like the addition of showing the title but I'm not sure if there is a flow that could lead to no `$current_template->title`. If there isn't we should skip this check. If there is, we should still show a message, no?

Comment (carolinan) [reply lib/full-site-editing/template-loader.php]: I was not able to confirm, so I removed the check.
When you attempt to create a template without a title, or remove a title, it reverts to the text "Auto Draft".

**Review by ntsekouras — APPROVED** [review]
LGTM 👍 - thanks Carolina!
