### PR TITLE
Fix initial focus on the first NUX tip popover

### LINKED ISSUE #8205: DotTip initial focus doesn't work any longer
**Describe the bug**

In Gutenberg 3.2.0 the **first** NUX "tip" used to get focused on mount. Setting initial focus within the first tip "popover" is essential for keyboard and screen reader users. Basically all the tips must behave like sort of a modal dialog and focusing the first one is important to make users able to use the tip.

**To Reproduce**
- revert to Gutenberg 3.2.0
- clear the local storage in your browsers in order to get again the "tips"
- create a new post
- on page load, when the first tip renders, it should get the initial focus on its `container` (see screenshot below)
- press the Tab key and you will see focus is on the tip and tabbing is constrained within the tip

The initial focus on the first tip in 3.2.0:

screen shot 2018-07-25 at 18 59 28

- switch to Gutenberg current master
- repeat the steps above
- initial focus is not set on the first tip
- press Tab and you will see focus is on the first element in the page: tabbing starts normally from the skip link (see screenshot below)

screen shot 2018-07-25 at 20 17 19

Both the DotTip and the popover component have gone through some recent refactoring. Especially the popover `focusOnMount` prop has changed. Seems to me the real cause of this regression is about timings though.

Note: I've tested the other usages of popovers with `focusOnMount` and they all seem to work to me, so this issue seems specific to the DotTip.

To my understanding:
- DotTip was a class component and [used a setTimeout](https://github.com/WordPress/gutenberg/commit/c85e3f98bcfdf9dd8a687d0fa6b501f0dab79dc0#diff-664e6197e2d4352dfedbaa4411d4a0e2L21) to recalculate its position, refresh, and focus
- it doesn't use setTimeout any longer but `withSafeTimeout` is still imported and used, I guess it should be removed
- seems to me there's now the need to ensure the popover itself uses a safe timeout before calling `refresh()` and `focus()` on `componentDidMount()`

/Cc @aduth

### PR DESCRIPTION
**Pull request by afercia**
## Description

This PR seeks to fix a regression in the way initial focus is set on the first NUX "tip". In Gutenberg 3.2.0 initial focus was set on the tip container:

screen shot 2018-07-25 at 18 59 28

This doesn't appear to happen any longer after recent refactoring of some related components. For more details, please see the related issue #8205.

- uses `setTimeout()` in the popover component on the call to the function that sets focus; worth noting the `focus()` function was already using `setTimeout()` internally but seems that now it must be used on the call to the function itself
- removes `withSafeTimeout` from the DotTip component, as it doesn't use a `setTimeout()` any longer
- adjusts a related test

To test:
- first, verify the bug on current master
- clear your browser local storage to make the tips appear
- create a new post: the first tooltip appears
- verify initial focus is _not_ on the first tip (e.g. press Tab and see the first focused element is the admin "skip link")

Then switch to this branch, build and:
- clear your browser local storage 
- create a new post: the first tooltip appears
- verify focus _is_ on the first tip (e.g. press Tab and see the tab order starts from the tip container; tabbing is also constrained within the tooltip)
- check all the other cases where the popover `focusOnMount` prop is used, for example: inserter, more menu, publish panel, block add link popover, etc., and that there are no regressions

Fixes #8205

### CODE REVIEW

File: packages/components/src/popover/index.js [hunk 1]
```diff
@@ -61,7 +61,13 @@ class Popover extends Component {
 	componentDidMount() {
 		this.toggleWindowEvents( true );
 		this.refresh();
-		this.focus();
+		/*
+		 * Without the setTimeout, the dom node is not being focused. Related:
```
Comment (aduth) [inline packages/components/src/popover/index.js]: I know you didn't author it, but the original comment reads to me as "I encountered an issue, couldn't figure out why it was happening, but by pure chance this alternative seems to do what I want"; we should strive for a higher level of quality.

File: packages/components/src/popover/index.js [hunk 2]
```diff
@@ -61,7 +61,13 @@ class Popover extends Component {
...
+		 * https://stackoverflow.com/questions/35522220/react-ref-with-focus-doesnt-work-without-settimeout-my-example
+		 */
+		setTimeout( () => {
```
Comment (aduth) [inline packages/components/src/popover/index.js]: `setTimeout` in a component is a code smell. And in the very worst cases where we decide it's needed, it should always be unset when the component unmounts. This is what's intended with the [`withSafeTimeout` higher-order component](https://github.com/WordPress/gutenberg/tree/master/packages/compose/src/with-safe-timeout). I'm aware you didn't introduce this. I'll see if I can refactor it simply while we're here.

Comment (afercia) [reply packages/components/src/popover/index.js]: Yep I know. I've tried `withSafeTimeout` but it didn't work. I guess it can't with popovers.

Comment (aduth) [reply packages/components/src/popover/index.js]: Yes, always. `setTimeout`, even with a duration of `0`, occurs only after the current execution stack completes, meaning that anything else after the `setTimeout` is scheduled which would cause the component to become unmounted (which occurs very frequently in a React context) would cause an error to occur when the callback of the `setTimeout` assumes that the component still exists.

Demo: https://codepen.io/aduth/pen/ejyyyN?editors=1111

**Review by aduth — APPROVED** [review]
Summarized my findings of the `setTimeout` at https://github.com/WordPress/gutenberg/pull/6799/files#r206211471 . It's going to be a more complicated solution than what we should try to tackle here. In the interim, I've added the necessary `clearTimeout`.

There were merge conflicts introduced. I've rebased and force pushed the branch to resolve them.

Looks good otherwise if my changes are acceptable to you. 👍

**Comment by afercia** [comment]
> Looks good otherwise if my changes are acceptable to you.

Of course they're. Thanks!

File: packages/components/src/popover/index.js (hunk 2 above)
Comment (afercia) [reply packages/components/src/popover/index.js]: OK thanks.
