### PR TITLE
Fix undefined variable warning in gutenberg.php

### LINKED ISSUE #12061: $post not defined in gutenberg_menu()
**Describe the bug**
`gutenberg_menu()` calls `gutenberg_can_edit_post()` with `$post` as an argument but it is not defined at that point.

**To Reproduce**
1. Load the wp-admin or single post
2. See error

**Expected behavior**
Check for the existing of `$post` before using it or using `global $post` so `$post` will at least be defined even if it's value is `NULL`

**Screenshots**
(added `die()` after call to `gutenberg_can_edit_post()` so error can be seen)
image

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Chrome

**Additional context**
- Master

### PR DESCRIPTION
**Pull request by earnjam**
Introduced an undefined global `$post` variable in 095d18fe5f1b55ab243cdba947740542e5b0fe47. 

Quick fix for that. 

closes #12061

### CODE REVIEW

File: gutenberg.php [hunk 1]
```diff
@@ -67,6 +67,7 @@ function the_gutenberg_project() {
  * @since 0.1.0
  */
 function gutenberg_menu() {
+	global $post;
 	if ( ! gutenberg_can_edit_post( $post ) ) {
```
Comment (youknowriad) [inline gutenberg.php]: I think it doesn't make sense to keep the check actually because this menu is always rendered in the admin and not only when there's a global  $post variable (post being edited).

I think the reasoning for the PR was to hide the menu if the rich-text preference is disabled But I don't think it's very important to check for it anyway.

Comment (youknowriad) [reply gutenberg.php]: I pushed a commit to remove the check entirely.

**Review by youknowriad — APPROVED** [review]
LGTM 👍
