### PR TITLE
Fix visibility of the template Welcome Guide in the Site Editor

### LINKED ISSUE #62525: Site editor: Welcome Guide apparition
### Description

In trunk and the site editor I'm seeing a brief flash of the template editing Welcome Guide anytime I’ve reloaded the site and go from view mode to edit a page. It doesn’t happen on subsequent switches between the modes.

It works as expected if I create a new user and login. So it probably works right for fresh installs too.

### Step-by-step reproduction instructions

1. Start from the WP admin Dashboard.
2. Visit the site editor.
3. Go to "Pages" view
4. Use the "Edit" button (pencil icon) to edit the page directly (without first having selected the page)
5. Watch for the flash of the Welcome Guide

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/9000376/12d92c22-6f75-45d9-aafe-6033f5c94061

### Environment info

- Trunk
- Chrome
- macOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by stokesman**
## What?
Makes the Welcome guide for page templates actually show up when editing a page template.

## Why?
To fix that the Welcome guide for a page template does not show up when expected as it was originally implemented in #52014. Also, to fix #62525, that describes how the Welcome guide flashes briefly at an unexpected moment.

## How?
- Adds a condition that the editor has a previous entity in its history in order to show the Welcome Guide
- Prevents showing the snackbar notice for template editing if the Welcome Guide is active

## Testing Instructions
1. Start from the WP admin Dashboard
2. Visit the site editor
3. Ensure the preference to show the template Welcome Guide is set by running the following snippet in the console:
```js
if ( ! wp.data.select('core/preferences').get('core/edit-site', 'welcomeGuideTemplate' ) ) {
	wp.data.dispatch('core/preferences').toggle('core/edit-site', 'welcomeGuideTemplate')
}
```
4. Go to "Pages" view
5. Use the "Edit" button (pencil icon) to edit the page directly (without first having selected the page)
6. Watch intently for the flash of the Welcome Guide and verify it does not
7. Open the Page settings sidebar
8. Choose "Edit template" from the "Template Options" dropdown menu
9. Verify that the Welcome Guide shows up and that the snackbar notice is not shown
10. Go back one step in browser history
11. Choose "Edit template" from the "Template Options" dropdown menu
12. Verify that the snackbar notice for template editing is shown and the Welcome Guide is not.

### CODE REVIEW

**Review by ramonjd — COMMENTED** [review]
Thanks for the PR! 

This is working as described for me. The Edit Template welcome guide now appears when I edit a page template in the site editor, and there's no flash from Page > Edit.

For other entities however I'm now seeing the "flash".  For example,

1. Open the site editor and edit the default template
2. Create a pattern and then click "Edit original" to edit the pattern
3. See our flashy friend appear

https://github.com/user-attachments/assets/fa73d51b-d036-4f45-b06b-30a054365555

It doesn't happen when I create a template part in situ. 

I'm not 100% on all the possible conditions, so it'd be good to get a second pair of eyes on it cc @noisysocks

**Comment by stokesman** [comment]
> For other entities however I'm now seeing the "flash"

Thanks for catching that! I’ve tinkered around more and have yet to find a set of conditions that work cleanly. I thought of a hackish solution that seems to work and pushed that 6a2bb80bcb271e2f3384c14abf34437315f8b0d0. I'd be keen to see if anyone can figure out a better way.

**Comment by stokesman** [comment]
I put this on the 6.7 board as the template welcome guide has had these issues since 6.6 it seems.

File: packages/edit-site/src/components/welcome-guide/template.js [hunk 1]
```diff
@@ -24,16 +21,24 @@ export default function WelcomeGuideTemplate() {
...
+			getCurrentPostType() === 'wp_template' &&
+			hasBackNavigation
 		);
 	}, [] );
 
+	// The visibility conditions change in such a way that it’s tricky to avoid
+	// an unexpected flash of the component. Using state and debouncing writes
+	// to it works around the issue.
+	const [ isVisible, setIsVisible ] = useState();
+	const debouncedSetIsVisible = useDebounce( setIsVisible, 32 );
```
Comment (ramonjd) [inline packages/edit-site/src/components/welcome-guide/template.js]: Is this effectively a timeout before reading the `useSelect` return value? Can we guarantee that `32` is always going to work? Otherwise it might end up being fragile.


According to the original PR https://github.com/WordPress/gutenberg/pull/52014 this welcome guide appears

> to the user when they open a page in the site editor and when they edit that page's template.

I'm wondering if we need to rethink how this is triggered, e.g, someone on the click events themselves.

cc @noisysocks / @SaxonF

Comment (stokesman) [reply packages/edit-site/src/components/welcome-guide/template.js]: It’s like a timeout but a self-adjusting one. The effective "timeout" increases each time the latest call to `debouncedSetIsVisible` was within `32` milliseconds of the last. I can’t see how it would fail to present the Welcome guide as intended. Though maybe it could still flash when not intended if someone’s device is really stuttering.

> I'm wondering if we need to rethink how this is triggered, e.g, someone on the click events themselves.

I had wanted to try that but shied away from it due to thinking it’d likely be a greater number of changes. That was before this hack seemed necessary, so I'd be glad to look into it further.

Comment (stokesman) [reply packages/edit-site/src/components/welcome-guide/template.js]: The latest in approach in d23d85cca3f8f640875417d2d759b16df81114b5 works well in my testing and is much cleaner. For now we can neglect this conversation.

File: packages/edit-site/src/components/welcome-guide/template.js [hunk 2]
```diff
@@ -6,36 +6,27 @@ import { Guide } from '@wordpress/components';
...
+			isActive: get( 'core/edit-site', 'welcomeGuideTemplate' ),
+			hasPreviousEntity:
 				!! getEditorSettings().onNavigateToPreviousEntityRecord,
 		};
 	}, [] );
-	const priorPostId = usePrevious( postId );
-	const isVisible =
-		postId !== priorPostId &&
-		isTemplateActive &&
-		! isEditorActive &&
```
Comment (stokesman) [inline packages/edit-site/src/components/welcome-guide/template.js]: I’ve removed the `! isEditorActive` condition because `hasPreviousEntity` makes it redundant. The editor welcome guide can’t be visible when editing an entity that was arrived at through another entity.

File: packages/edit-site/src/components/welcome-guide/template.js [hunk 3]
```diff
@@ -10,29 +10,23 @@ import { store as editorStore } from '@wordpress/editor';
...
-		const { isPage } = select( editSiteStore );
-		const { getCurrentPostType } = select( editorStore );
-		return (
-			isTemplateActive &&
-			! isEditorActive &&
-			isPage() &&
-			getCurrentPostType() === 'wp_template'
-		);
+	const edited = useEditedEntityRecord();
+	const isPostTypeTemplate = edited.record.type === 'wp_template';
```
Comment (ramonjd) [inline packages/edit-site/src/components/welcome-guide/template.js]:
```suggestion
	const isPostTypeTemplate = edited.record?.type === 'wp_template';
```

`edited.record` can be `false` on the first load.

File: packages/edit-site/src/components/welcome-guide/template.js [hunk 4]
```diff
@@ -10,29 +10,23 @@ import { store as editorStore } from '@wordpress/editor';
...
+	const { isActive, hasPreviousEntity } = useSelect( ( select ) => {
+		const { getEditorSettings } = select( editorStore );
+		const { get } = select( preferencesStore );
+		return {
+			isActive: get( 'core/edit-site', 'welcomeGuideTemplate' ),
+			hasPreviousEntity:
+				!! getEditorSettings().onNavigateToPreviousEntityRecord,
+		};
 	}, [] );
```
Comment (ramonjd) [inline packages/edit-site/src/components/welcome-guide/template.js:28]: Completely optional, just a bit neater:

```suggestion
	const { isActive, hasPreviousEntity } = useSelect(
		( select ) => ( {
			isActive: select( preferencesStore ).get(
				'core/edit-site',
				'welcomeGuideTemplate'
			),
			hasPreviousEntity:
				!! select( editorStore ).getEditorSettings()
					.onNavigateToPreviousEntityRecord,
		} ),
		[]
	);
```

**Review by ramonjd — APPROVED** [review]
Thanks for persevering with this one! 

Things are working well for me so far, and it's a definite improvement.

File: packages/edit-site/src/components/welcome-guide/template.js (hunk 3 above)
Comment (stokesman) [reply packages/edit-site/src/components/welcome-guide/template.js]: Aw, good catch. Yet in this case the optional chaining operator isn’t truly suited. Still, I’m not against trying to make this more explicit. I decided to leverage the `isLoaded` property in the return value 29bfbc06f8380cd3a729f55efe0b0add7539069f. Once that becomes `true` then `record` won’t be `false`.

File: packages/edit-site/src/components/welcome-guide/template.js (hunk 4 above)
Comment (stokesman) [reply packages/edit-site/src/components/welcome-guide/template.js:28]: I waffle on this. On one hand, I do appreciate assignments aren’t needed. On the other, in many cases I would prefer to leave them there in hopes it helps avoid any future additions of `select` calls that reproduce one of the existing ones—not that it guarantees it or a duplicate is too concerning.

Therefore, fewer lines wins out for me 😝.

**Comment by stokesman** [comment]
> Thanks for persevering with this one!

Thanks for sticking it out with me Ramon!

File: packages/edit-site/src/components/welcome-guide/template.js (hunk 4 above)
Comment (ramonjd) [reply packages/edit-site/src/components/welcome-guide/template.js:28]: Yeah I get you. Either way is fine in the end as it's all transpiled into goo 😄
