### PR TITLE
Try: Fix overzealous aspect ratio scaling for embeds

### LINKED ISSUE #27720: Embeds sometimes appear with lots of additional space underneath
**Describe the bug**

Sometimes embeds appear with far too much space below them. I've seen this with Spotify and Soundcloud. In these cases, the embed's `figure` is much taller than the actual iframe inside. This appears to be due to the aspect ratio padding here, since modifying those values can lead to fixing this: 

https://github.com/WordPress/gutenberg/blob/52db498780b153029dc9f811df5dd780dbbd650f/packages/block-library/src/embed/style.scss#L56-L84

**Screenshots**

_Spotify embed in Twenty Twenty-One_
Screen Shot 2020-12-14 at 10 50 47 AM

_Spotify embed in Twenty Twenty_
Screen Shot 2020-12-14 at 10 51 27 AM

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Gutenberg version: 9.5.2

_[Originally reported in the Twenty Twenty-One forums](https://wordpress.org/support/topic/too-much-white-space-after-spotify-and-soundcloud-embeds/)_

### LINKED ISSUE #28347: Spotify Embed: Aspect ratio incorrectly identified
Steps to reproduce:

- Paste an amazing song from Spotify into the editor, for example this one: `https://open.spotify.com/track/7b4yGtR0rujvLi5EBfKKJ2`
- Observe how the embed is way taller than it should be

Screenshot 2021-01-20 at 10 26 12

If we look under the "Advanced" panel, we can see these classes are applied:

`wp-embed-aspect-9-16 wp-has-aspect-ratio`

Looking at the Spotify embed, it appears to calculate the height it needs to show and apply that directly to the iframe. So there's probably a bit of a race condition going on there. 

Some potential solutions:

- Except the Spotify embed from the aspect ratio correction, just allow it to be 100% width.
- Improve the aspect ratio detection to detect the spotify embed as 1:1 aspect ratio.

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

Fixes #27720.
Fixes #28347.

Spotify embeds default to 300x380, but the embed is smart enough to resize itself to the context it ends up in.

In the block editor, the aspect ratio of an embed is detected, so that 4:3 or 16:9 videos can be smartly scaled up or down, responsively, according to their intrinsic dimensions:

Screenshot 2021-03-03 at 12 31 33

However this scaling behavior applies even to embeds that aren't really meant to scale according to an aspect ratio, such as Spotify playlists:

Screenshot 2021-03-03 at 12 24 34

What happens currently is this:

- The width/height reported from the embed is calculated to an aspect ratio. 
- This aspect ratio is looped through and assigned a [predefined aspect ratio](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/embed/constants.js) according to its closest match.

This PR changes that, so unless a _very_ close match is found, the embed is not scaled according to any aspect ratio at all:

Screenshot 2021-03-03 at 12 24 09

In the case of the Spotify embed used in this example, its calculated aspect ratio is 0.78, and its closest match is 0.56 which is 9:16 (meant for portrait mode video).

However the feature should still work for actually close matches. Here's a 4:3 video, for example, it should still be detected as 4:3:

Screenshot 2021-03-03 at 12 26 46

## How has this been tested?

This needs to be tested with a wide range of supported embeds, ideally all of them. Right now I've set the threshold for "close match" to `0.1` (for the spotify example, the actual aspect ratio was 0.78, the closest match was 0.56, and the diff between the two comes to 0.22, i.e. above the threshold). But we need to have a sense of how many embed blocks might be affected by this, because this PR touches not just the Spotify embed, but all embeds.

You can test with this Spotify playlist: `https://open.spotify.com/artist/7BJ4OeS4NgyI4M87ZijwBI`, or this 4.3 aspect ratio YouTube video: `https://www.youtube.com/watch?v=ftxP_KDqvnc`.

Please verify that embeds look correct — i.e. videos have correct aspect ratios, and things like Spotify embeds don't look super tall.

Please test editor and frontend.

## Types of changes

This PR is in a draft mode, and I will need code help landing it:

- Is the threshold good? Is the method for comparing them sound?
- I believe the way this PR handles bad matches (i.e. Spotify) is broken, because the post is marked "dirty" as soon as the embed loads, even if saved and reloaded.

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-library/src/embed/util.js [hunk 1]
```diff
@@ -198,6 +198,14 @@ export function getClassNames(
 		) {
 			const potentialRatio = ASPECT_RATIOS[ ratioIndex ];
 			if ( aspectRatio >= potentialRatio.ratio ) {
+				// Evaluate the difference between actual aspect ratio and closest match.
+				// If the difference is too big, do not scale the embed according to aspect ratio.
+				const ratioDiff = aspectRatio - potentialRatio.ratio;
+				if ( ratioDiff > 0.1 ) {
```
Comment (jasmussen) [inline packages/block-library/src/embed/util.js:204]: We want to find a balance with this differential where actual matches are handled with nice aspect ratio scaling, but incorrect ones are not. `0.05` was also fine for identifying a 4:3 YouTube video correctly, but bailing on the Spotify one.

File: packages/block-library/src/embed/util.js [hunk 2]
```diff
@@ -198,6 +198,14 @@ export function getClassNames(
...
+					// No close aspect ratio match found.
+					return removeAspectRatioClasses( existingClassNames );
```
Comment (jasmussen) [inline packages/block-library/src/embed/util.js:206]: This seems incorrect, as it marks the post dirty, all the time.

Comment (stokesman) [reply packages/block-library/src/embed/util.js:206]: This already was the case in trunk for some other embeds (I've tested twitter and reddit, could be more). #13706 is an old (now conflicted) PR to fix it and the description there does nicely detail the cause. The changes needed to resolve it are pretty simple and I could push them if you'd like. It could also be tackled separately.

Comment (jasmussen) [reply packages/block-library/src/embed/util.js:206]: Oh wow, great investigative work. I would be very grateful if you pushed the fixes!

**Comment by stokesman** [comment]
This approach does work to avoid an inappropriate aspect ratio being applied. Though currently, it creates a new defect in that for embeds that aren't close enough to a preset aspect ratio, the setting "Resize for smaller devices" becomes ineffectual. That is, it can be switched on yet the aspect ratio of the embed will not be maintained (as promised by the help text) when resized (in the editor—for the frontend it depends on the theme).

I think the preferred resolution for that would be to make the setting work even for the cases in which the embed doesn't closely match a preset aspect ratio. It seems doable but may prompt more scrutiny and work around related bits.

File: packages/block-library/src/embed/util.js (hunk 2 above)
Comment (stokesman) [reply packages/block-library/src/embed/util.js:212]: Should be resolved. I added a couple of unit tests to help keep it that way. There were some failures in CI from snapshot tests. I verified the changes are expected and updated the snapshots. I've also rebased this in hopes it would clear up some lint failures that had also come up 🤞 .

**Comment by jasmussen** [comment]
This is excellent! Thanks so much for the help @stokesman. I'm going to make this one ready for review.

**Comment by noisysocks** [comment]
This is a really neat solution and I confirmed that it indeed fixes the linked issues.

To test, I tried to insert three types of embeds:

1. Things with a landscape aspect ratio: For this I used videos on YouTube and Vimeo. All worked properly and properly scaled up/down when I had 'Resize for smaller devices' enabled. ✅
2. Things with a portrait aspect ratio: For this I used videos on YouTube, TikTok and Tumblr. Unfortunately I wasn't ever able to see the video scale up/down when I had 'Resize for smaller devices' enabled. I'm not sure if it's a bug in the block editor or if the third party embed code plain doesn't allow for this. ❌
2. Things without an aspect ratio. For this I used posts on Twitter and Tumblr. I also added the Spotify playlist you linked to. The block editor correctly identified that they didn't match any aspect ratio and so 'Resize for smaller devices' did not do anything. ✅

A passing though: I wonder if it's impossible for us to correctly guess what the aspect ratio should be in 100% of cases. For example, Tumblr posts have no predictable height. It could, just by chance, be a 16:9 or 4:3 text post. Maybe instead we should have a dropdown where the user can manually select the aspect ratio and have it so that this checkbox defaults to our best guess.

**Comment by jasmussen** [comment]
Thanks a ton for testing.

> Things with a portrait aspect ratio: For this I used videos on YouTube, TikTok and Tumblr. Unfortunately I wasn't ever able to see the video scale up/down when I had 'Resize for smaller devices' enabled. I'm not sure if it's a bug in the block editor or if the third party embed code plain doesn't allow for this. Or maybe I wasn't doing it properly. ❌

Do you have a link example I can test? Did it work in trunk?

> I wonder if it's impossible for us to correctly guess what the aspect ratio should be in 100% of cases. 

It is, and we shouldn't. The thing is, the Spotify embed in the example isn't ever _meant_ to scale according to the aspect ratio. Its intrinsic dimensions are 300x380, which is 15:19 aspect ratio, or "quite tall". So although the original image in this PR is not accurate to that — remember, it maps to nearest match — even if it had a perfect map, it would not be what you expected from a Spotify embed.

For that reason, I think it's best we have a list of known _desirable_ aspect ratios, like we do now, even if they are often skewed to video. And when we don't find a match, don't invoke the aspect ratio scaling at all.

_On that note, it'd be nice to move to `aspect-ratio` in the future: https://web.dev/aspect-ratio/_

**Comment by noisysocks** [comment]
Vertical videos:

- YouTube: https://www.youtube.com/watch?v=pakLFQ61omE
- TikTok: https://www.tiktok.com/@winniethecattledog/video/6929571530972073217?sender_device=pc&sender_web_id=6914804789063648770&is_from_webapp=v3&is_copy_url=0 (This is a good one, by the way.)
- Tumblr: https://tiktoksthataregood-ish.tumblr.com/post/645736175297003520

All don't seem to scale when I embed them. It doesn't look like things are any better on `trunk`, though, so I think let's go ahead with this PR.

**Review by noisysocks — APPROVED** [review]

**Comment by jasmussen** [comment]
Let's land this one. It's a big headache, and lets follow up with tickets and PRs for anything else. Thank you Robert!
