### PR TITLE
Writing Flow: Avoid horizontal writing flow navigation in native inputs

### LINKED ISSUE #6468: WritingFlow should exclude standard input fields
In some cases, having WritingFlow kicking in risks to disrupt the standard interaction with standard input fields and moves the caret outside of the field, even it that's not what users would expect.

Consider for example the permalink edit field:

screen shot 2018-04-27 at 16 05 26

when the mini-form opens, it should be possible to use the arrow keys normally, as users are used to. Instead, when the caret is at the end or at the beginning of the field, pressing the right arrow or the left arrow key moves the caret to the following block or to the post title.

In the post permalink, this behavior is more evident because this UI is, in a way, visually "detached" fro the post. What about other input fields, for example in the shortcode, embeds, video, etc. blocks?

screen shot 2018-04-27 at 17 15 55

I'd say the most expected behavior would be trying to emulate the native behavior as much as possible. When pressing left, right, Home, End (and related keys combination e.g. Cmd+Left), the caret should stay within the input field. Being unexpectedly kicked out from the input field is a very confusing experience also for assistive technology users.

In this case, when the caret is within native input fields, I'd propose to use just the Up and Down keys for WritingFlow (doing nothing when modifier keys are used). Would this be an acceptable trade-off?

### PR DESCRIPTION
**Pull request by aduth**
Closes #6468

This pull request seeks to update the writing flow behavior to allow only unmodified vertical arrow key presses for consideration in a browser native input (textarea, input).

**Testing instructions:**

Verify that horizontally navigating between non-input fields still works.

1. Insert two paragraph
2. At the beginning of the second paragraph, press ArrowLeft
3. Ensure that focus is placed at the end of the first paragraph

Verify that only unmodified vertical arrow press in native input transitions focus:

1. Click editor title
2. Press ArrowRight
3. Observe no focus change
4. Press Ctrl/Cmd + ArrowDown
5. Observe no focus change
6. Press ArrowDown
7. Ensure that focus is placed in a new default paragraph

Ensure unit tests and end-to-end tests pass:

```
npm run test-unit
```

```
npm run test-e2e
```

### CODE REVIEW

File: packages/editor/src/components/writing-flow/index.js [hunk 1]
```diff
@@ -49,6 +49,29 @@ const isTabbableTextField = overEvery( [
...
+	const isVertical = ( keyCode === UP || keyCode === DOWN );
+
+	// Currently, all elements support unmodified vertical navigation.
+	if ( isVertical && ! hasModifier ) {
+		return true;
+	}
+
+	// Native inputs should not navigate horizontally.
+	const { tagName } = element;
+	return tagName !== 'INPUT' && tagName !== 'TEXTAREA';
```
Comment (jorgefilipecosta) [inline packages/editor/src/components/writing-flow/index.js]: Would it make sense to apply this to all the editables?

**Review by jorgefilipecosta — APPROVED** [review]
Implements the desired behaviour in my tests 👍

File: packages/editor/src/components/writing-flow/index.js (hunk 1 above)
Comment (aduth) [reply packages/editor/src/components/writing-flow/index.js]: Can you elaborate on what you mean? Are you thinking to reverse this condition so that we test whether the candidate is explicitly contentEditable ? Or do you mean we should include editables In the excluded set of candidates? That would cause issues for navigating between paragraphs, where we do want ArrowRight to navigate between blocks.
