### PR TITLE
RichText: Fix dead key input on Windows

### LINKED ISSUE #35086: Windows - US International keyboard layout modifier (dead keys) don't correctly register
### Description

It appears when you have US International keyboard layouts active in Windows that the modifier keys (pressing either ' or ` on a US layout keyboard, followed by a letter such as e should then output either é or è) don't register correctly if you want to output the actual symbol character (usually done by clicking modifier + space).

Instead, it appears the editor outputs a space character only.

### Step-by-step reproduction instructions

1. Ensure you have US International keyboard selected in Windows (I tested with a US layout keyboard with US Internation selected in language settings)
2. Create a new page or post
3. Try out `'` then `e` which should correctly output `é`
4. Try out `'` then `space` which should output the `'` character but instead a space character is output instead.

### Screenshots, screen recording, code snippet

Markup on 2021-09-23 at 14:59:42

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

### PR DESCRIPTION
**Pull request by mcsf**
Fixes https://github.com/WordPress/gutenberg/issues/35086

## Description

In `useSpace`, don't intercept character composition that involves the Space key. For example, to input a standalone diacritic (like <kbd>´</kbd> or <kbd>`</kbd>) using a keyboard with dead keys, one must first press the dead key and then press the Space key.

Many operating systems handle this in such a way that the second KeyboardEvent contains the property `keyCode: 229`. According to the spec, 229 allows the system to indicate that an Input Method Editor (IDE) is processing some key input.

However, Windows doesn't use `keyCode: 229` for dead key composition, instead emitting an event with values `keyCode: SPACE` and `key: '´'`. That is why checking the `key` property for values other than `SPACE` is important.

This should serve as a reminder that the `KeyboardEvent.keyCode` attribute is officially deprecated and that we should consider more consistent interfaces.

cc @ellatrix @Flameeyes 

## How has this been tested?

See parent issue (#35086).

* Make sure you switch to a keyboard layout with dead keys (e.g. US International w/ dead keys).
* Start a new post.
* Input text that contains spaces, accented letters (pressing an accent's dead key followed by a vowel key), and standalone diacritics (pressing an accent's dead key followed by the Space key). Make sure everything behaves as intended.
  * On non-Windows systems, no changes should be observed.
  * On Windows, it should now be possible to input a standalone diacritic. No other changes should be observed.

## Types of changes
Bug fix (regression) affecting a particular system.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by lukegb — APPROVED** [review]
Tested this in Storybook on Windows, this fixes the issue for both Firefox and Chrome.

File: packages/rich-text/src/component/use-space.js [hunk 1]
```diff
@@ -21,13 +21,38 @@ export function useSpace() {
 				return;
 			}
 
-			const { keyCode, altKey, metaKey, ctrlKey } = event;
+			const { keyCode, altKey, metaKey, ctrlKey, key } = event;
 
 			// Only consider the space key without modifiers pressed.
 			if ( keyCode !== SPACE || altKey || metaKey || ctrlKey ) {
```
Comment (ellatrix) [inline packages/rich-text/src/component/use-space.js:27]: Should we remove `keyCode !== SPACE`, or will that cause problems?

**Review by ellatrix — APPROVED** [review]
Thank you so much for looking into this issue! 🙂 Everything looks good to me.

**Comment by Mamaduka** [comment]
@noisysocks should we pick this up for RC 2?

File: packages/rich-text/src/component/use-space.js (hunk 1 above)
Comment (mcsf) [reply packages/rich-text/src/component/use-space.js:27]: Right now I just patched the existing approach, so I wouldn't touch that condition. But ideally we would ditch `keyCode` altogether and rely mostly on `key`, which is the [main non-deprecated property](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent) for this stuff. Then we'll know what shortcomings `key` presents, and we could mitigate them with properties like `code`, `location`, etc.

Comment (mcsf) [reply packages/rich-text/src/component/use-space.js:27]: We should also mind the [composition events](https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event).

Comment (Mamaduka) [reply packages/rich-text/src/component/use-space.js:27]: I was just reading this interesting thread on `keydown` and `event.key` - https://twitter.com/jaffathecake/status/1480493537112248325.

**Comment by youknowriad** [comment]
I also support backporting this one as it's a very bad bug.
