### PR TITLE
Fix: useColors crash when themes remove the color pallete

### LINKED ISSUE #18232: Heading block "encountered an error" since 6.8.0
**Describe the bug**
Upon installing the 6.8.0 plugin update, all of my heading blocks returned the "This block has encountered an error and cannot be previewed." error in the editor.

**To reproduce**
1. Have a site where the headings exist in the editor, with extra classes defined (unsure if it is relevant but all of my headings do have extra classes defined)
2. Upgrade the plugin to 6.8.0
3. Check the heading block and see the error returned

**Expected behavior**
Normal heading block display

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/18232

The useColors hook did not handle the case where themes disable color palette using:
```
add_theme_support( 'editor-color-palette' );
```

This PR fixes the issue.

## How has this been tested?
I added the following code to the functions.php file of the currently enabled theme (removing the code it contained setting a color palette):
```
add_theme_support( 'editor-color-palette' );
```
I opened the editor, added a heading block, verified the block did not crash (on master it crashes), verified no preset colors were available.

### CODE REVIEW

File: packages/block-editor/src/components/colors/use-colors.js [hunk 1]
```diff
@@ -30,6 +30,8 @@ import ContrastChecker from '../contrast-checker';
 import InspectorControls from '../inspector-controls';
 import { useBlockEditContext } from '../block-edit';
 
+const DEFAULT_COLORS = [];
+
```
Comment (epiqueras) [inline packages/block-editor/src/components/colors/use-colors.js]:
```suggestion
```

**Review by epiqueras — APPROVED** [review]
