### PR TITLE
Only split block styles loading for block themes

### LINKED ISSUE #31293: Base Block Styles Loaded Differently for PHP templates than Block-based HTML templates.
## Description
When a block-based HTML template is used to render a page base block styles are loaded inline, and are loaded prior to the styles generated based on theme.json.
i.e.
```
<head>
...
<style id='wp-block-button-inline-css' type='text/css'>
.wp-block-button__link{color:#fff;background-color:#32373c;border-radius:9999px;box-shadow:none;cursor:pointer;display:inline-block;font-size:1.125em;padding:calc(.667em + 2px) calc(1.333em + 2px);text-align:center;text-decoration:none;overflow-wrap:break-word;box-sizing:border-box}.wp-block-button__link:active,.wp-block-button__link:focus,.wp-block-button__link:hover,.wp-block-button__link:visited{color:#fff}.wp-block-button__link.aligncenter{text-align:center}.wp-block-button__link.alignright{text-align:right}.wp-block-buttons>.wp-block-button.has-custom-width{max-width:none}.wp-block-buttons>.wp-block-button.has-custom-width .wp-block-button__link{width:100%}.wp-block-buttons>.wp-block-button.has-custom-font-size .wp-block-button__link{font-size:inherit}.wp-block-buttons>.wp-block-button.wp-block-button__width-25{width:calc(25% - .5em)}.wp-block-buttons>.wp-block-button.wp-block-button__width-50{width:calc(50% - .5em)}.wp-block-buttons>.wp-block-button.wp-block-button__width-75{width:calc(75% - .5em)}.wp-block-buttons>.wp-block-button.wp-block-button__width-100{margin-right:0;width:100%}.wp-block-button.is-style-squared,.wp-block-button__link.wp-block-button.is-style-squared{border-radius:0}.wp-block-button.no-border-radius,.wp-block-button__link.no-border-radius{border-radius:0!important}.is-style-outline>.wp-block-button__link,.wp-block-button__link.is-style-outline{border:2px solid;padding:.667em 1.333em}.is-style-outline>.wp-block-button__link:not(.has-text-color),.wp-block-button__link.is-style-outline:not(.has-text-color){color:currentColor}.is-style-outline>.wp-block-button__link:not(.has-background),.wp-block-button__link.is-style-outline:not(.has-background){background-color:transparent}
</style>
...
<style id='global-styles-inline-css' type='text/css'>
...
</head>
```
When a php-based template is used to render a page the base block styles are loaded from CSS files instead, and are loaded at the bottom of the body.
```
<style id='global-styles-inline-css' type='text/css'>
...
</head>
<body>
   ... content ...
   <link rel='stylesheet' id='wp-block-button-css'  href='http://localhost:4759/wp-content/plugins/gutenberg/build/block-library/blocks/button/style.css?ver=1619619707' type='text/css' media='all' />
...
</body>
```
The result is incorrect application of styles as the 'base' supersedes the 'generated global styles' in most scenarios.

## Step-by-step reproduction instructions
Load (or create) a theme that leverages Global Styles via theme.json but renders PHP templates.  ([Here is a simple theme as an example.](https://github.com/WordPress/theme-experiments/tree/example/try-broken-php-global-styles/try-broken-php-global-styles))
Ensure button styles are expressed in the theme.

## Expected behavior
Ideally the block base classes would be provided rendered inline in the same fashion for PHP rendered templates as block-based HTML templates.
Ensure a 'button' style is applied (such as background color)
Load a page rendered from a PHP template and observe the styles on a button block in the view.
image

## Actual behavior
image

## WordPress information
- WordPress version: latest
- Gutenberg version: trunk (10.5.0)
- Are all plugins except Gutenberg deactivated? yes

This appears to work as expected on `10.4.1`.

Also note that disabling block support in the theme also causes it to operate as expected.

`remove_theme_support( 'block-templates' );`

### PR DESCRIPTION
**Pull request by aristath**
## Description

If the theme is using `theme.json` - so has global styles enabled, but is NOT a block theme, global styles get overridden by other styles.
See https://github.com/WordPress/gutenberg/issues/31293 for a detailed description of the issue.

This PR fixes the issue by making sure that separate styles are only used in FSE themes - or when the theme opts in.

## How has this been tested?
Followed the instructions in #31293 and confirmed this fixes the issue.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [-] My code follows the accessibility standards. 
- [-] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [-] I've included developer documentation if appropriate. 
- [-] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by oandregal** [comment]
By looking at https://github.com/WordPress/gutenberg/issues/31293 it seems the issue is that the block styles are rendered in different places. Can we make it so they are always rendered in the same place (in the header)?

I'm not sure where things such as `wp-block-button-inline-css` come from, any pointer to investigate would be welcome.

I presume these come from core. My concern with enqueuing core styles in the footer (both these block styles + global styles) is that it's more difficult for 3rd parties to override them (themes, plugins, etc) should they need it.

**Comment by aristath** [comment]
Pushed an alternative fix that makes more sense for non-FSE themes :+1:

File: lib/compat.php [hunk 1]
```diff
@@ -14,7 +14,7 @@
  * @return bool
  */
 function gutenberg_should_load_separate_block_assets() {
-	$load_separate_styles = gutenberg_supports_block_templates();
+	$load_separate_styles = gutenberg_is_fse_theme();
```
Comment (jffng) [inline lib/compat.php:17]: So I understand, this will make it so that only themes with an `block-templates/index.html` will get the block style loading optimization?

**Review by jffng — APPROVED** [review]
I tested that this fixes the issue described in #31293 — block styles for non-FSE themes are loaded in the header + in the correct order (before global styles).

**Comment by jffng** [comment]
> Can we make it so they are always rendered in the same place (in the header)? I'm not sure where things such as wp-block-button-inline-css come from, any pointer to investigate would be welcome.

+1 to this, I was confused why sometimes those inline styles would be loaded in the footer vs always the header, and could not figure out where they were coming from.

File: lib/compat.php (hunk 1 above)
Comment (aristath) [reply lib/compat.php:17]: Yes :)
