### PR TITLE
Site logo: Fix range control on landscape logos

### LINKED ISSUE #37716: Site Logo: Adjusting image width with toolbar causes strange number calculations
### Description

When adjusting the image width for the site logo, the calculations for how wide the image is both get cut off and get set to very strangely exact numbers. 

### Step-by-step reproduction instructions

1. Add a site logo block.
2. Open block settings.
3. Try dragging the toolbar to adjust the width.
4. Notice problem

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/148146999-5767bc60-2acb-459c-9204-9cee2fc0acd6.mov

### Environment info

- WordPress 5.9 RC1
- Happens with GB 12.2 activated and deactivated
- Twenty Twenty-Two
- MacOS
- Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by walbo**
## Description
Make sure the minimum width is an integer when calculating the minimum logo size. This fixes a bug where the range controller returned numbers that wasn't an integer on landscape logos.

Fixes #37716 

## How has this been tested?

1. Add a site logo (a logo that has landscape orientation).
2. Open block settings.
3. Try dragging the toolbar to adjust the width.
4. Confirmed that the number is an integer.

## Types of changes
Bug fix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]
It works as expected. Thanks, @walbo.

File: packages/block-library/src/site-logo/edit.js [hunk 1]
```diff
@@ -166,7 +166,8 @@ const SiteLogo = ( {
 	const currentWidth = width || defaultWidth;
 	const ratio = naturalWidth / naturalHeight;
 	const currentHeight = currentWidth / ratio;
-	const minWidth = naturalWidth < naturalHeight ? MIN_SIZE : MIN_SIZE * ratio;
+	const minWidth =
+		naturalWidth < naturalHeight ? MIN_SIZE : Math.ceil( MIN_SIZE * ratio );
 	const minHeight =
 		naturalHeight < naturalWidth ? MIN_SIZE : MIN_SIZE / ratio;
```
Comment (Mamaduka) [inline packages/block-library/src/site-logo/edit.js]: Should we round this value as well?

**Comment by Mamaduka** [comment]
@noisysocks should we backport this into RC or label it for minor release?

File: packages/block-library/src/site-logo/edit.js (hunk 1 above)
Comment (walbo) [reply packages/block-library/src/site-logo/edit.js]: Thanks @Mamaduka! I was thinking same. Did some more testing and do see that the `minHeight` isn't a integer on portrait images.

I update the PR.

**Comment by noisysocks** [comment]
The bug was spotted during the beta period and I don't see any string changes so all good to backport 👍
