### PR TITLE
Editor: Merge meta attributes in getEditedPostAttribute

### LINKED ISSUE #12289: Two checkbox controls in PluginPostStatusInfo – clicking one triggers both
**Describe the bug**

I have two plugin installed, that both add a checkbox to the publish area via `PluginPostStatusInfo`. If one of both is already clicked and I reload the editor, both get triggered if I click the box that is not checked. If both are checked, both get unchecked. After the first click, it works.

But the changed status of the not-clicked checkbox does not get saved – after clicking update, the correct status gets highlighted again.

**To Reproduce**

Not so easy, the checkbox values are depending on custom meta values.

I created a Gist with the code of both checkboxes in one file, so you can take a look how the code is: https://gist.github.com/florianbrinkmann/2c1fd1b7477f28354d65380dcc8c4170

**Expected behavior**
Only the one checkbox should be triggered.

**Screenshots**

two-checkbox-issue

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 65.0a1 (2018-11-24) (64-Bit)

**Additional context**
- Gutenberg 4.5.1.

### PR DESCRIPTION
**Pull request by aduth**
Fixes #12289
Regression of #10827

This pull request seeks to resolve an issue where `getEditedPostAttribute( 'meta' )` would return only the edited value, not including other unedited values from the current saved post.

While in #10827 we'd introduced the "merge" concept to the `edits` reducer, we'd not considered to account for it being a partial fragment in the return value of `getEditedPostAttribute`. The changes here apply that behavior.

**Implementation notes:**

I made the implementation perhaps more complicated than necessary in a pursuit of avoiding returning a new reference object from each call to `getEditedPostAttribute`. Elsewhere we use `createSelector` for similar effect, but in this instance I thought it may be too heavy-handed given that this is a rarer use-case (not present in core code) and given the fitness of `WeakMap` as a cache given the edited object value as key (since the value is guaranteed to be an object, and guaranteed to never change reference unless its value actually changes).

**Testing instructions:**

Repeat Steps to Reproduce from #12289

Ensure unit tests pass:

```
npm test
```

cc @florianbrinkmann

### CODE REVIEW

File: packages/editor/src/store/selectors.js [hunk 1]
```diff
@@ -297,10 +298,38 @@ export function getEditedPostAttribute( state, attributeName ) {
...
+		// long as the merge property has the same edit value). Over `rememo`,
+		// this has the benefit of (a) optimizing as the less common case and
+		// (b) being a more performant cache lookup.
+		let { mergeCache } = getEditedPostAttribute;
+		if ( ! mergeCache ) {
+			mergeCache = getEditedPostAttribute.mergeCache = new WeakMap;
+		}
+
+		if ( ! mergeCache.has( edits[ attributeName ] ) ) {
+			mergeCache.set(
```
Comment (youknowriad) [inline packages/editor/src/store/selectors.js]: I'm not certain I understand how this cache gets invalidated when the edited value or the persisted value change?

Comment (aduth) [reply packages/editor/src/store/selectors.js]: > I'm not certain I understand how this cache gets invalidated when the edited value or the persisted value change?

It doesn't need to be. Given the nature of a `WeakMap`, invalidation occurs automatically by garbage collection as soon as the key is no longer referenced (i.e. as soon as it becomes replaced in state by another value).

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

**Comment by florianbrinkmann** [comment]
Thanks @aduth, I will try to test this with my plugins tomorrow!

File: packages/editor/src/store/test/selectors.js [hunk 2]
```diff
@@ -174,6 +174,7 @@ describe( 'selectors', () => {
 		setFreeformContentHandlerName( 'core/test-freeform' );
 
 		cachedSelectors.forEach( ( { clear } ) => clear() );
+		invoke( getEditedPostAttribute.mergeCache, [ 'clear' ] );
```
Comment (aduth) [inline packages/editor/src/store/test/selectors.js]: I guess this doesn't exist:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap/clear

Given how the tests are written, it might not really be necessary to clear the cache. Alternatively, we could manually assign into `getEditedPostAttribute` a new `WeakMap` in `beforeEach`.

File: packages/editor/src/store/selectors.js (hunk 1 above)
Comment (youknowriad) [reply packages/editor/src/store/selectors.js]: Gotcha. Shouldn't we account for the `currentPost` value as well? I guess the reasoning is if it changes, the edited value would have changed as well?

Comment (aduth) [reply packages/editor/src/store/selectors.js]: > Gotcha. Shouldn't we account for the `currentPost` value as well? I guess the reasoning is if it changes, the edited value would have changed as well?

That's a good point, and I don't think we could rely on that assumption. I'm starting to wonder if we should bother caching here at all. It's not something which would have much impact on the stock editor, but could have a negative impact on integrations which make heavy use of `getEditedPostAttribute( 'meta' )`. An alternative may be to just use `createSelector` as we normally do, but I worry this _would_ have a negative performance impact on stock editor usage.

Comment (youknowriad) [reply packages/editor/src/store/selectors.js]: I won't bother caching for now. If we ever need a performant version we could create a `getEditedPostMeta( metaKey )`

File: packages/editor/src/store/selectors.js [hunk 3]
```diff
@@ -297,10 +298,23 @@ export function getEditedPostAttribute( state, attributeName ) {
...
 
+	// Merge properties are objects which contain only the patch edit in state,
+	// and thus must be merged with the current post attribute.
+	if ( EDIT_MERGE_PROPERTIES.has( attributeName ) ) {
+		// [TODO]: Since this will return a new reference on each invocation,
+		// consider caching in a way which would not impact non-merged property
+		// derivation. Alternatively, introduce a new selector for meta lookup.
+		return {
+			...edits[ attributeName ],
+			...getCurrentPostAttribute( state, attributeName ),
```
Comment (youknowriad) [inline packages/editor/src/store/selectors.js]: Should we change the order here?

Comment (youknowriad) [reply packages/editor/src/store/selectors.js]: I mean edits should override the current values?

Comment (aduth) [reply packages/editor/src/store/selectors.js]: Yes 🤦‍♂️

Comment (youknowriad) [reply packages/editor/src/store/selectors.js]: Also makes me wonder how we unset values, are we supposed to pass `null` as a value in these cases?

**Review by youknowriad — APPROVED** [review]
LGTM 👍

File: packages/editor/src/store/selectors.js (hunk 3 above)
Comment (aduth) [reply packages/editor/src/store/selectors.js]: > Should we change the order here?

Fixed in d711318.

> Also makes me wonder how we unset values, are we supposed to pass `null` as a value in these cases?

Unsetting would only occur when updating the post. It's worked this way since the beginning for any edit, so I'm not sure it's critical to change now.

I might imagine either assigning to `undefined` or assigning to the value in `currentPost` could unset the edit property.

Comment (aduth) [reply packages/editor/src/store/selectors.js]: > I might imagine either assigning to `undefined` or assigning to the value in `currentPost` could unset the edit property.

It seems like a sensible, easy enhancement to consider. I'll make an issue for it.

Comment (aduth) [reply packages/editor/src/store/selectors.js]: > > I might imagine either assigning to `undefined` or assigning to the value in `currentPost` could unset the edit property.
> 
> It seems like a sensible, easy enhancement to consider. I'll make an issue for it.

#12334
