### PR TITLE
fix: Correct the margins of embed block content

### LINKED ISSUE #7150: Embed block editor style regressed
The embed block styles regressed a bit. It's probably tiny, a classname change or something. It looks like this:

screen shot 2018-06-05 at 17 21 57

It should look like this:

screen shot 2018-06-05 at 17 23 29

As we are fixing this, be sure to test wide and fullwide alignments, mobile, and the frontend.

### PR DESCRIPTION
**Pull request by tofumatt**
Fixes #7150

## Description
Removed the margins around the `<figure>` element, which gets the content to expand to fill the content box.

## How has this been tested?
Tested in browser and things still work and display as they should. Tried with a YouTube and Vimeo embed.

## Screenshots (after)
screenshot 2018-06-06 14 33 03
screenshot 2018-06-06 14 32 56

## Types of changes
Bug fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: core-blocks/embed/index.js [hunk 1]
```diff
@@ -255,7 +255,7 @@ function getEmbedBlockSettings( { title, description, icon, category = 'embed',
 				return (
 					<Fragment>
 						{ controls }
-						<figure className={ classnames( className, { 'is-video': 'video' === type } ) }>
+						<figure className={ classnames( className, 'wp-block-embed__figure', { 'is-video': 'video' === type } ) }>
```
Comment (tofumatt) [inline core-blocks/embed/index.js]: I have no clue as to how to name classes in Gutenberg–is there a doc that points me toward what's right?

Comment (jasmussen) [reply core-blocks/embed/index.js]: @aduth pointed me to two links that might help:

- https://github.com/Automattic/eslint-plugin-wpcalypso/blob/master/lib/rules/jsx-classname-namespace.js
- https://github.com/WordPress/gutenberg/blob/master/docs/reference/coding-guidelines.md#css

**Review by jasmussen — CHANGES_REQUESTED** [review]
I checked out this branch. Turns out that the regression itself was caused by the removal of the `wp-block-embed` class. Simply adding that back fixes everything. Note that both the editor.scss and style.scss for the embed block both refer to `wp-block-embed`.

Should we simply rename your `wp-block-embed__figure` to `wp-block-embed` and be done with it?

**Comment by jasmussen** [comment]
screen shot 2018-06-06 at 09 05 16

👆after renaming `wp-block-embed__figure` to `wp-block-embed`. Note that there are also loading specific styles, as well as some for embed alignments. So we need to test those in a fix.

**Comment by tofumatt** [comment]
screenshot 2018-06-06 16 14 18

Makes sense, I've restored the original class. 👍 Above is the screenshot.

**Review by jasmussen — APPROVED** [review]
👍 👍

Nice work!
