### PR TITLE
Fix edited Classic block's content deletion when switching to Code editor

### LINKED ISSUE #23924: Edited classic block content removed when switching to Code Editor
**Describe the bug**
Any content added to the classic block seems to be deleted when switching to the Code Editor view.

**To reproduce**
1. Add a classic block and type in it
2. Click on the Code Editor view
3. Observe that classic block content is removed

**Expected behavior**
Classic block content is retained

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Gutenberg version: 8.5.1

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description

Fixes: https://github.com/WordPress/gutenberg/issues/23924

If you edit the content of a `Classic` block and then switch to `Code editor`, the content disappears.

This was happening because with the switch ( and possibly other actions as well? ) the `Classic` block unmounts and calls the `wp.oldEditor` ( tinymce ) function `remove`. This function in a series of internal actions with `save` ended up calling our debounced function. Since it was set to execute to another `tick`, the editor had already cleared its content (caused by the above `remove` call) resulting in the disappearance of the content.

There might be some performance issues on "edge" cases, as previously discussed here: https://github.com/WordPress/gutenberg/pull/23408#discussion_r445881412, in the PR that introduced this side effect.

> We didn't actually start to see any visible performance degradation until you got upwards of 50,000 words in a post, and adding a debounce made it performant again even with a massive post.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by mcsf** [comment]
Can you run a performance comparison between the base branch and this one, per [Testing Overview § Performance Testing](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/testing-overview.md#performance-testing)? Thanks!

**Comment by ntsekouras** [comment]
Screenshot 2020-07-15 at 11 41 53 AM

Performance seems to not be affected negatively. Even more seems to be a tiny bit faster now.

**Comment by youknowriad** [comment]
@mcsf The performance test actually runs on each PR now, unfortunately, the job doesn't post the result as a comment or something, so you'd have to dig in the github action to see the results.

**Comment by youknowriad** [comment]
The performance test don't rely on classic blocks though 🤷

**Comment by mcsf** [comment]
> The performance test don't rely on classic blocks though 🤷

D'oh, I'm silly. Unconsciously I probably thought "RichText" instead of "Classic".

File: packages/block-library/src/classic/edit.js [hunk 1]
```diff
@@ -149,9 +154,13 @@ export default class ClassicEdit extends Component {
 						content: value,
 					} );
 				}
-			}, 250 )
+			} )
```
Comment (mcsf) [inline packages/block-library/src/classic/edit.js:157]: I notice the duration was removed. Was it intentional?

File: packages/block-library/src/classic/edit.js [hunk 2]
```diff
@@ -141,6 +141,11 @@ export default class ClassicEdit extends Component {
 		editor.on(
 			'Paste Change input Undo Redo',
 			debounce( () => {
+				// We need this check because when we remove the editor (onUnmount)
+				// due to the usage of `debounce`, this callback is executed in
+				// another tick. This results in setting the content to empty.
+				if ( editor._isRemoved ) return;
```
Comment (mcsf) [inline packages/block-library/src/classic/edit.js:147]: I personally like this style, but I'm surprised the linter didn't complain about this `if` statement with no curly braces:

```js
if ( A ) {
  return;
}
```

File: packages/block-library/src/classic/edit.js [hunk 3]
```diff
@@ -149,9 +154,13 @@ export default class ClassicEdit extends Component {
 						content: value,
 					} );
 				}
-			}, 250 )
+			} )
 		);
 
+		editor.on( 'remove', () => {
+			editor._isRemoved = true;
```
Comment (mcsf) [inline packages/block-library/src/classic/edit.js:161]: Really minor suggestion, but maybe `_hasBeenRemoved`? Also, is there any property already in the TinyMCE API that would give us this information? (I don't know, I haven't found one yet)

Comment (ntsekouras) [reply packages/block-library/src/classic/edit.js:161]: I've search but I didn't find neither a property or a function to get that information.

File: packages/block-library/src/classic/edit.js (hunk 2 above)
Comment (ntsekouras) [reply packages/block-library/src/classic/edit.js:147]: It might have `allowSingleLine` set. I'll check the rules.

File: packages/block-library/src/classic/edit.js (hunk 1 above)
Comment (ntsekouras) [reply packages/block-library/src/classic/edit.js:157]: Great catch Miguel. No it wasn't.

File: packages/block-library/src/classic/edit.js (hunk 2 above)
Comment (ntsekouras) [reply packages/block-library/src/classic/edit.js]: It seems that allows the omission of curly braces when a block contains only one statement by default, if not explicitly set. I'm not sure yet though.

There are other similar cases in the codebase as well. So if this is a problem, we should check and fix the linter config/rules.

File: packages/block-library/src/classic/edit.js [hunk 4]
```diff
@@ -141,6 +141,11 @@ export default class ClassicEdit extends Component {
 		editor.on(
 			'Paste Change input Undo Redo',
 			debounce( () => {
+				// We need this check because when we remove the editor (onUnmount)
+				// due to the usage of `debounce`, this callback is executed in
+				// another tick. This results in setting the content to empty.
+				if ( editor._hasBeenRemoved ) return;
```
Comment (ellatrix) [inline packages/block-library/src/classic/edit.js:147]: Could we use `cancel`? https://lodash.com/docs/#debounce

**Review by ellatrix — CHANGES_REQUESTED** [review]

File: packages/block-library/src/classic/edit.js (hunk 4 above)
Comment (ntsekouras) [reply packages/block-library/src/classic/edit.js:147]: Yes. Actually I had considered at first ( before deciding to utilise editor's `onRemove` event ), so in my mind was too ugly to implement outside.. That said, since we are keeping lodash's `debounce` it's the way to go.

Thanks @ellatrix!

**Review by mcsf — APPROVED** [review]
Looks great now :)

File: packages/block-library/src/classic/edit.js (hunk 2 above)
Comment (mcsf) [reply packages/block-library/src/classic/edit.js]: Yeah, apparently it's not enforced in code, but for reference here are the guidelines:

https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/#blocks-and-curly-braces

**Review by ellatrix — APPROVED** [review]
