### PR TITLE
Security: Update npm dependencies to fix issues reported by audit

### LINKED ISSUE #54895: @wordpress/scripts has some deprecated NPM modules
### Description

"intl-messageformat-parser@1.8.1: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser"

### Step-by-step reproduction instructions

1. delete folder "node_modules" and file "package-lock.json" at project root directory
2. "ncu"
3. "ncu -u"
4. "npm install --force"

### Screenshots, screen recording, code snippet

image

## System:
 - OS: macOS 14.0
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 4.41 GB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 20.7.0 - ~/.nodebrew/current/bin/node
 - Yarn: 1.22.19 - ~/.nodebrew/current/bin/yarn
 - npm: 10.1.0 - ~/.nodebrew/current/bin/npm
 - pnpm: 8.6.12 - ~/.nodebrew/current/bin/pnpm
## npmPackages:
 - @wordpress/scripts: ^26.13.0 => 26.13.0 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

### LINKED ISSUE #56069: [@wordpress/script]jest-dev-server has some severity vulnerabilities
### Description

The "npm audit" just said severity vulnerabilities:

axios  0.8.1 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
fix available via `npm audit fix --force`
Will install @wordpress/scripts@18.0.1, which is a breaking change
node_modules/axios
  wait-on  >=5.0.0-rc.0
  Depends on vulnerable versions of axios
  node_modules/wait-on
    jest-dev-server  >=5.0.0
    Depends on vulnerable versions of wait-on
    node_modules/jest-dev-server
      @wordpress/scripts  >=18.1.0
      Depends on vulnerable versions of jest-dev-server
      node_modules/@wordpress/scripts

4 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

### Step-by-step reproduction instructions

Delete the "node_modules" folder and "package-lock.json".
Next, execute "ncu", "ncu -u", "npm install --force", and "npm audit" in order.

### Screenshots, screen recording, code snippet

image

## System:
 - OS: macOS 14.1.1
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 135.64 MB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 21.1.0 - ~/.nodebrew/current/bin/node
 - Yarn: 1.22.19 - ~/.nodebrew/current/bin/yarn
 - npm: 10.2.3 - ~/.nodebrew/current/bin/npm
 - pnpm: 8.6.12 - ~/.nodebrew/current/bin/pnpm
## npmPackages:
 - @wordpress/scripts: ^26.16.0 => 26.16.0 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

### LINKED ISSUE #62002: [@wordpress/scripts][puppeteer-core] Some internal modules are deprecated.
### Description

npm warn deprecated rimraf@3.0.2:
Rimraf versions prior to v4 are no longer supported

npm warn deprecated glob@7.2.3:
Glob versions prior to v9 are no longer supported

### Step-by-step reproduction instructions

1. After deleting the folder 'node_modules' and file 'package-lock.json', run 'ncu', 'ncu -u' and 'npm install -force' in turn.
2. Run 'npm ls <module names>' for each of the module names listed in the warn warning presented by npm.

### Screenshots, screen recording, code snippet

puppeteer-core@13 7 0

babel-jest@29 7 0

## System:
 - OS: macOS 14.5
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 24.13 MB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 22.2.0 - ~/.nodebrew/current/bin/node
 - Yarn: 1.22.22 - /usr/local/bin/yarn
 - npm: 10.8.0 - ~/.nodebrew/current/bin/npm

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

### LINKED ISSUE #63771: [wordpress/scripts] 5 high severity vulnerabilities
### Description

Installing `@wordpress/scripts` package throws vulnerability errors with npm.

Terminal responds with “5 high severity issues” that appear to stemming from `ws`, `puppeteer-core`, and `lighthouse`. 

**What I’ve tried:**

- Running `npm audit fix --force` downgrades @wordpress/scripts to v19.2.4, unsurprisingly causing 47 other vulnerabilities.
- Using the `overrides` param in `package.json` fixes the issue.

```json
"overrides": {
  "ws": "^8.18.0",
  "lighthouse": "^12.1.0",
  "puppeteer-core": "^22.13.1"
}
```

---

### Step-by-step reproduction instructions

1. run `npm install @wordpress/scripts` or go through `npx @wordpress/create-block`
2. run `npm audit`

### Screenshots, screen recording, code snippet

```zsh
ws  8.0.0 - 8.17.0
Severity: high
ws affected by a DoS when handling a request with many HTTP headers - https://github.com/advisories/GHSA-3h5v-q93c-6h6q
fix available via `npm audit fix --force`
Will install @wordpress/scripts@19.2.4, which is a breaking change
node_modules/lighthouse/node_modules/puppeteer-core/node_modules/ws
node_modules/puppeteer-core/node_modules/ws
  puppeteer-core  11.0.0 - 22.11.1
  Depends on vulnerable versions of ws
  node_modules/lighthouse/node_modules/puppeteer-core
  node_modules/puppeteer-core
    @wordpress/scripts  >=20.0.0
    Depends on vulnerable versions of @wordpress/e2e-test-utils-playwright
    Depends on vulnerable versions of puppeteer-core
    node_modules/@wordpress/scripts
    lighthouse  9.6.1 - 11.5.0
    Depends on vulnerable versions of puppeteer-core
    node_modules/lighthouse
      @wordpress/e2e-test-utils-playwright  >=0.9.1-next.5a1d1283.0
      Depends on vulnerable versions of lighthouse
      node_modules/@wordpress/e2e-test-utils-playwright
```

### Environment info

Unsure if this bit matters, but for what's worth:
- Tested on 2 MacBook Pros with macOS 14.5 (Sonoma) with (respectively) i9 and M1 architecture
- Node versions ^20 and ^22
- npm versions 10.7 & ^10.8.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by gziolo**
## What?

Fixes https://github.com/WordPress/gutenberg/issues/56069 (updates `jest-dev-server`).
Fixes https://github.com/WordPress/gutenberg/issues/54895 (updates `lighthouse`).
Fixes https://github.com/WordPress/gutenberg/issues/62002 (updates `puppeteer-core`).
Fixes #63771.
Supersedes and fixes #65488.

## Why?

`npm audit` reports several vulnerabilities. Some of them can be fixed with `npm audit fix`.

## How?

Executed `npm audit fix` and manually resolved a few issues that required manual intervention. After this PR there are still issues reported:

Screenshot 2024-12-09 at 09 44 38

It should help when installing development tools like `@wordpress/scripts`, where all reported issues should be addressed.

The biggest concern I had was with `rimraf` as it had several breaking changes that forced updates in the code:
- The function returns a Promise instead of taking a callback.
- There is no default export anymore. Import the functions directly using, e.g., import { rimrafSync } from 'rimraf'.

I didn't update to the latest version v6, because it requires node 20 or higher, and WordPress packages still allow node 18, which is in maintenance mode until April 2025.

## Testing Instructions

All CI checks should pass. In the development process, there were some issues reported due to breaking changes in `rimraf`. The rest should be less problematic, but these type of changes are usually difficult to test as they mostly impact dev tooling that doesn't have so detailed testing coverage. There should be zero impact on production code.

### CODE REVIEW

File: bin/plugin/commands/packages.js [hunk 1]
```diff
@@ -599,7 +588,7 @@ async function runPackagesRelease( config, customMessages ) {
 			await Promise.all(
 				temporaryFolders
 					.filter( ( tempDir ) => fs.existsSync( tempDir ) )
-					.map( ( tempDir ) => rimraf( tempDir, rethrow ) )
+					.map( ( tempDir ) => rimraf( tempDir ) )
```
Comment (gziolo) [inline bin/plugin/commands/packages.js:591]: I'm not entirely sure if this is exactly the same handling, so I would appreciate some verification. The updated version of `rimraf` is Promise-based now, so it seems correct to me.

**Comment by gziolo** [comment]
By the way, I removed the automated update from `npx audit fix` for `@appium/base-driver` as the most recent version depends on packages licensed under LGPL-3.0-or-later. I see that we have LGPL-2.1 listed as GPL-2.0 compatible license, so it's probably fine. However, we need to verify that before proceeding.

File: bin/plugin/commands/packages.js (hunk 1 above)
Comment (sirreal) [reply bin/plugin/commands/packages.js:591]: I don't see why `Promise.all` was there before, but it makes sense now if there are promises being used.

File: patches/lighthouse+12.2.2.patch [hunk 2]
```diff
@@ -1,11 +1,12 @@
...
- export = lighthouse;
- /** @type {import('./index.js')['default']} */
+@@ -7,5 +7,7 @@ export = lighthouse;
+  * @property {import('./index.js')['snapshot']} snapshot
+  */
+ /** @type {import('./index.js')['default'] & ExportType} */
 +// Otherwise TS is confused when using ES types in CJS.
 +// @ts-ignore
- declare const lighthouse: typeof import("./index.js")['default'];
+ declare const lighthouse: typeof import("./index.js")["default"] & ExportType;
```
Comment (sirreal) [inline patches/lighthouse+12.2.2.patch:11]: This patch was still necessary? That's too bad… it would be nice to dig into why it's needed and try to address that.

**Review by sirreal — APPROVED** [review]
This seems reasonable, thanks for handling it 👍

File: patches/lighthouse+12.2.2.patch (hunk 2 above)
Comment (gziolo) [reply patches/lighthouse+12.2.2.patch:11]: Yes, I initially removed the old patch completely, but I had to re-apply it to the new version 😞

**Comment by gziolo** [comment]
@swissspidy, can you double-check the `lighthouse` changes? I'm not entirely sure how to test them.

**Comment by swissspidy** [comment]
> @swissspidy[](https://profiles.wordpress.org/swissspidy), can you double-check the `lighthouse` changes? I'm not entirely sure how to test them.

Done 👍 Pushed a small config change for LH.

**Comment by sirreal** [comment]
I think this rimraf upgrade is causing problems on windows, [you can see it here](https://github.com/WordPress/wordpress-develop/actions/runs/12273327100/job/34243904735).

```
> gutenberg@19.9.0-rc.1 clean:packages
> rimraf "./packages/*/@(build|build-module|build-wp|build-style)"

Error: Illegal characters in path.
    at pathArg (file:///D:/a/wordpress-develop/wordpress-develop/src/wp-content/plugins/gutenberg/node_modules/rimraf/dist/esm/path-arg.js:38:33)
    at file:///D:/a/wordpress-develop/wordpress-develop/src/wp-content/plugins/gutenberg/node_modules/rimraf/dist/esm/index.js:17:54
    at Array.map (<anonymous>)
    at file:///D:/a/wordpress-develop/wordpress-develop/src/wp-content/plugins/gutenberg/node_modules/rimraf/dist/esm/index.js:17:42
    at main (file:///D:/a/wordpress-develop/wordpress-develop/src/wp-content/plugins/gutenberg/node_modules/rimraf/dist/esm/bin.mjs:[24](https://github.com/WordPress/wordpress-develop/actions/runs/12273327100/job/34243904735#step:8:25)3:15)
    at file:///D:/a/wordpress-develop/wordpress-develop/src/wp-content/plugins/gutenberg/node_modules/rimraf/dist/esm/bin.mjs:[25](https://github.com/WordPress/wordpress-develop/actions/runs/12273327100/job/34243904735#step:8:26)1:5 {
  path: 'D:\\a\\wordpress-develop\\wordpress-develop\\src\\wp-content\\plugins\\gutenberg\\packages\\*\\@(build|build-module|build-wp|build-style)',
  code: 'EINVAL'
```

I'll investigate.

**Comment by t-hamano** [comment]
Sorry I couldn't test it on Windows. Perhaps the `glob` option specification has changed in rimraf v4?

https://github.com/isaacs/rimraf/blob/main/README.md

image

Update: The following should fix the issue, but I'm curious why the problem didn't occur on Mac OS and Linux:

```diff
diff --git a/package.json b/package.json
index dbf69043c5..5ebdcd29bb 100644
--- a/package.json
+++ b/package.json
@@ -181,7 +181,7 @@
                "postbuild:packages": " npm run --if-present --workspaces build:wp",
                "build:plugin-zip": "bash ./bin/build-plugin-zip.sh",
                "clean:package-types": "tsc --build --clean && rimraf \"./packages/*/build-types\"",
-               "clean:packages": "rimraf \"./packages/*/@(build|build-module|build-wp|build-style)\"",
+               "clean:packages": "rimraf --glob \"./packages/*/@(build|build-module|build-wp|build-style)\"",
                "component-usage-stats": "node ./node_modules/react-scanner/bin/react-scanner -c ./react-scanner.config.js",
                "dev": "cross-env NODE_ENV=development npm run build:packages && concurrently \"wp-scripts start\" \"npm run dev:packages\"",
                "dev:packages": "cross-env NODE_ENV=development concurrently \"node ./bin/packages/watch.js\" \"tsc --build --watch\"",
```

**Comment by sirreal** [comment]
Fix in https://github.com/WordPress/gutenberg/pull/67829.

**Comment by sirreal** [comment]
> I'm curious why the problem didn't occur on Mac OS and Linux:

I believe the shells were handling the glob expansion which I also attempt to address in #67829. I also think that other systems are more permissive with characters allowed in paths so may not error, for example I can make a directory named `*`.
