### PR TITLE
Parser: Optimize JSON-attribute parsing

### LINKED ISSUE #11066: WordPress 5.0 beta1 - Block now causing Fatal Errors
**Describe the bug**
I am running into a problem with WP 5.0 beta1 which I do not see in Gutenberg 4.1.0 or earlier. My custom block is a simple syntax highlighter and everything works fine with small amounts of code, but once I add say more than 10 lines of code into the block all saving fails with the Chrome console showing:
```
POST http://wp.local.com/wp-json/wp/v2/posts/22/autosaves 500 (Internal Server Error)
POST http://wp.local.com/wp-json/wp/v2/posts/22/autosaves 500 (Internal Server Error)
POST http://wp.local.com/wp-json/wp/v2/posts/22 500 (Internal Server Error)
```
If I try to refresh the post edit page, or re-navigate to it, the admin fatal errors with:
```
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) in /var/www/html/wp-includes/class-wp-block-parser.php on line 385
```

**To Reproduce**
1. Install WordPress 5.0 beta1
2. Install the Kebo Code plugin - [https://wordpress.org/plugins/kebo-code/](https://wordpress.org/plugins/kebo-code/)
3. Create a new post, add the `Kebo Code` block and copy some code into it (over 10 lines).
4. Set the language and click off the block (lose focus).
5. You should now see autosaves and publish failing.
6. If you try to refresh the post edit page it should show an OOM error.

**Expected behavior**
The previous and current versions of Gutenberg all work fine. I would expect WordPress 5.0 beta1 to work too.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 69.0.3497.100 / Firefox 62.0.3

**Additional context**
I am using a blank WordPress 5.0 beta1 install with no plugins other than the one mentioned above (required to reproduce the bug). 

My custom block does not do anything particularly fancy, it uses CodeMirror's runMode function to perform syntax highlighting live as the block is changed. The resulting HTML is stored in an attribute, which may mean that there is far more stored in the attribute than usual.

### PR DESCRIPTION
**Pull request by dmsnell**
Alternate approach to #11355
Fixes: #11066

## Status
 - I'm confused by the failing test saying `here are local uncommitted changes after one or both of 'npm install' or 'npm run docs:build'!` - can someone help me understand this?

## Description

Parsing JSON-attributes in the existing parsers can be slow when the
attribute list is very long. This is due to the need to lookahead at
each character and then backtrack as the parser looks for the closing
of the attribute section and the block comment closer.

In this patch we're introducing an optimization that can eliminate
a significant amount of memory-usage and execution time when parsing
long attribute sections by recognizing that _when inside the JSON
attribute area_ any character that _isn't_ a `}` can be consumed
without any further investigation.

I've added a test to make sure we can parse 100,000 characters inside
the JSON attributes. The default parser was fine in testing with more
than a million but the spec parser was running out of memory. I'd
prefer to keep the tests running on all parsers and definitely let our
spec parser define the acceptance criteria so I left the limit low for
now. It'd be great if we found a way to update php-pegjs so that it
could generate the code differently. Until then I vote for a weaker
specification.

The default parser went from requiring hundreds of thousands of steps
and taking seconds to parse the attack to taking something like 35
steps and a few milliseconds.

There should be no functional changes to the parser outputs and no
breaking changes to the project. This is a performance/operational
optimization.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows the accessibility standards. (N/A?)
- [ ] My code has proper inline documentation. (? not sure)

### CODE REVIEW

**Comment by dmsnell** [comment]
Comparing the default PHP parser from `master` against the one in this branch (using #6831)

comparator-fnuoaerzsg now sh_

Comparing the default JS parser from `master` against the one in this branch (using #6831)

comparator-fnuoaerzsg now sh_

My conclusion is that there is no significant change in runtime performance in the normal cases. I don't have the catastrophic cases in the document library.

**Review by pento — APPROVED** [review]
Thanks for this, @dmsnell!

Let's go with this change, it's a solid improvement of #11355.

File: packages/block-serialization-default-parser/parser.php [hunk 1]
```diff
@@ -347,7 +347,7 @@ function next_token() {
 		 * match back in PHP to see which one it was.
 		 */
 		$has_match = preg_match(
-			'/<!--\s+(?<closer>\/)?wp:(?<namespace>[a-z][a-z0-9_-]*\/)?(?<name>[a-z][a-z0-9_-]*)\s+(?<attrs>{(?:(?!}\s+-->).)+?}\s+)?(?<void>\/)?-->/s',
+			'/<!--\s+(?<closer>\/)?wp:(?<namespace>[a-z][a-z0-9_-]*\/)?(?<name>[a-z][a-z0-9_-]*)\s+(?<attrs>{(?:[^}]+|}+(?=})|(?!}\s+-->).)+?}\s+)?(?<void>\/)?-->/s',
```
Comment (mcsf) [inline packages/block-serialization-default-parser/parser.php]: I don't think I understand this term: `}+(?=})`. Among other things, I don't understand why `+` should be applied to that first `}`.

Comment (dmsnell) [reply packages/block-serialization-default-parser/parser.php]: the history is in #11355

I guess we could go in and add some explanatory comments here but we're creating two new matching groups here based on a "fast parse" pathway

we know that _specifically_ we want to consume `((?!}\s+-->).)`, but the problem with that is that for every position in the input we're allocating some memory to hold the match group and then we also start backtracking once the match fails. this is unlike the autogenerated PEG parser because PEGs don't backtrack.

therefore, I looked at what was causing things to be slow and realized that we know more about our inputs than the RegExp does, that is, the majority of our characters won't even be `}`. taking this knowledge lets us encode that fast-path and fallback to the slow path

> if the input isn't a `}`, then directly consume it and proceed.

we can compare these two methods with a simplified test.
we'll use the simple test data `< {"a": "b"} >`.
make sure to click on the debugger in these to see what's
happening inside the RegExp engine.

`(?:<\s+)({(?:(?!}\s+>).)*})(?:\s+>)` - 1 match, 51 steps - https://regex101.com/r/UmdrvA/1
`(?:<\s+)({(?:(?:[^}]+)|(?:(?!}\s+>).))*})(?:\s+>)` - 1 match, 26 steps - https://regex101.com/r/cXcMFw/1

if we make the input bigger we can watch in the debugger how the `[}]+` can consume a long string of text in one step and skip all the backtracking.

that leaves us a bad case where we end up with deeply-nested JSON though and in the content we could imagine `}}}}}}}}} -->`. the `}+(?=})` bit then is a second-order optimization to consume a string of closing brackets up to the last one in the string (`?=` is the positive lookahead to say "match the closer but don't consume it).

by introducing a new alternation group we've made a new possible branch in the execution but on the other hand it's fast to consume a string of closers. the goal is mainly to remove the backtracking which opens a denial-of-service attack and can dramatically bloat the execution.

Comment (mcsf) [reply packages/block-serialization-default-parser/parser.php]: thanks for the thorough explanation <3
