### PR TITLE
Check if spacing tool is defined before displaying controls.

### LINKED ISSUE #52909: Columns Block: Spacing control visible in classic themes in WP 6.3 RC 1, but doesn't work
### Description

In the WordPress 6.3 RC 1, the Block Spacing control appears for the Columns block in the editor when using a classic theme, but it doesn't do anything  -- no styles are output when you change its values. 

Since it's the only block with this open when using a classic theme, and that it doesn't work, it seems like it shouldn't be visible after all. 

### Step-by-step reproduction instructions

1. Start on a test site running WP 6.3 RC 1, and using a classic theme like Twenty Twenty One.
2. Create a page, and add the Columns block.
3. Change the horizontal Block Spacing value to either one of the 1-7 values, or a fixed PX value.
4. See the gap doesn't change in the editor, or on the front-end. If you inspect the front-end, the usual styles that would be output to change the gap aren't there. 

### Screenshots, screen recording, code snippet

columns-block 2023-07-24 16_41_17

### Environment info

I can recreate this with:
- WordPress 6.3 RC 1 and the Twenty Twenty One theme, without Gutenberg.
- WordPress 6.2.2 and the Twenty Twenty One theme, with Gutenberg 16.2.1.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

 Fixes #52909.

In classic themes, block spacing controls don't work so they shouldn't be displayed. 

This PR adds a check for whether the spacing tool is defined before outputting any sizes setting it may have. In classic themes, `spacing.blockGap` is undefined so this should prevent blockGap sizes from being added to settings.

I'm not sure this is the best fix, but it was the simplest I could think of for now 😅 

Arguably we _should_ support blockGap in classic themes, but that's beyond the scope of this bug fix.

## Testing Instructions

1. Activate a classic theme such as Twenty Twenty.
2. In a post, add a Columns block.
3. Check that in the Styles section of the sidebar, under Dimensions, there are no block spacing controls displayed.

### CODE REVIEW

File: packages/block-editor/src/components/global-styles/hooks.js [hunk 1]
```diff
@@ -326,7 +326,11 @@ export function useSettingsForBlockElement(
 			const sides = Array.isArray( supports?.spacing?.[ key ] )
 				? supports?.spacing?.[ key ]
 				: supports?.spacing?.[ key ]?.sides;
-			if ( sides?.length ) {
+			// Check if spacing type actually exists before adding sides.
+			if (
+				sides?.length &&
+				typeof updatedSettings.spacing?.[ key ] !== 'undefined'
```
Comment (andrewserong) [inline packages/block-editor/src/components/global-styles/hooks.js]: Should this be a truthy check instead of not undefined? E.g. something like `!! updatedSettings.spacing?.[ key ]`?

**Review by andrewserong — COMMENTED** [review]
Oh, thank you for looking into this one!

This actually appears to expose a bug for `margin` and `padding`, too.

In `theme.json`, we should be able to set `settings.spacing.margin` to `false` to hide margin controls, (and padding, blockGap to `false`, too, to hide them). However in testing this PR, I see that setting to `false` doesn't currently hide them.

To reproduce, update the Columns block's `block.json` to use the following spacing settings (so that they each specify sides):

```
		"spacing": {
			"blockGap": {
				"__experimentalDefault": "2em",
				"sides": [ "horizontal", "vertical" ]
			},
			"margin": [ "top", "bottom" ],
			"padding": [ "top", "bottom" ],
			"__experimentalDefaultControls": {
				"padding": true,
				"blockGap": true
			}
		},
```

Then, in `theme.json`, try setting each of the values to false:

```
		"spacing": {
			"margin": false,
			"padding": false,
			"blockGap": false,
```

It looks like the controls are still visible:

image

I'm pretty sure if we change the `typeof` check for a truthy check, we might be able to fix that at the same time?

File: packages/block-editor/src/components/global-styles/hooks.js (hunk 1 above)
Comment (tellthemachines) [reply packages/block-editor/src/components/global-styles/hooks.js]: Ah, I thought about it but wasn't sure if that was just the way of exposing only top and bottom margin controls 😅 

I'll give it a try.

Comment (tellthemachines) [reply packages/block-editor/src/components/global-styles/hooks.js]: I've updated it, but now no dimensions controls seem to be showing for any blocks in classic themes 🤔 which I don't think is the intended result.

Comment (tellthemachines) [reply packages/block-editor/src/components/global-styles/hooks.js]: Oh wait, actually that might be a Twenty Twenty thing, because I'm seeing padding controls for some blocks in Twenty Twenty One.

Comment (andrewserong) [reply packages/block-editor/src/components/global-styles/hooks.js]: Hrm... most likely not the intended result!

Comment (andrewserong) [reply packages/block-editor/src/components/global-styles/hooks.js]: One way to test it could be to try adding `add_theme_support( 'appearance-tools' );` to the classic theme you're testing?

Comment (tellthemachines) [reply packages/block-editor/src/components/global-styles/hooks.js]: Yeah, confirmed it's a Twenty Twenty issue. So I guess this is working as expected?

Comment (andrewserong) [reply packages/block-editor/src/components/global-styles/hooks.js]: Good to hear!

**Review by aaronrobertshaw — APPROVED** [review]
LGTM! ✨ 

Tested with a few classic themes e.g. TwentyTwentyOne, emptyhybrid etc. and this PR fixes the reported issue.

Block themes and their display of spacing controls have now also been fixed.

Nice work!

**Review by andrewserong — APPROVED** [review]
Works nicely for me, too. Tested in Classic themes (looks like `add_theme_support( 'custom-spacing' );` adds in padding support for classic themes), and block themes in the post and site editors. Thanks for fixing this up! ✨

**Comment by tellthemachines** [comment]
Thanks for the reviews folks!

**Comment by ramonjd** [comment]
I just cherry-picked this PR to the update/packages-wp-6-3-RC3 branch to get it included in the next release: 8aa3a214ca
