### PR TITLE
FIX: Links: Can't add plain text after insert link at end of paragraph 

### LINKED ISSUE #1246: Links:  Can't add plain text after insert link at end of paragraph
It appears to be impossible to add any plain text after an external link is added at the end of a paragraph.

2017-06-19_01b

Any text added at the end of a paragraph is added to the link - even if I hit return to create a new line.

### PR DESCRIPTION
**Pull request by tg-ephox**
fixes https://github.com/WordPress/gutenberg/issues/1246

### CODE REVIEW

File: blocks/editable/index.js [hunk 1]
```diff
@@ -51,6 +51,12 @@ function createTinyMCEElement( type, props, ...children ) {
 	);
 }
 
+function isLinkBoundary( fragment ) {
+	return fragment.childNodes && fragment.childNodes.length === 1 &&
+		fragment.childNodes[ 0 ].nodeName === 'A' && fragment.childNodes[ 0 ].text.length === 1 &&
+		fragment.childNodes[ 0 ].text[ 0 ] === '\uFEFF';
```
Comment (youknowriad) [inline blocks/editable/index.js]: It's fine for now, but maybe this character could be included in a constant somewhere in TinyMCE to avoid issues if it's changed.

**Review by youknowriad — APPROVED** [review]
This fixes the remaining link when splitting paragraphs. The other part of the issue is still unsolved but we may consider it "won't fix" (Entering text at the end of the paragraph)

File: blocks/editable/index.js (hunk 1 above)
Comment (tg-ephox) [inline blocks/editable/index.js]: @youknowriad there's a function in TinyMCE we can look at exposing

**Comment by tg-ephox** [comment]
@youknowriad at the moment you need to right arrow after the link to escape it
