### PR TITLE
fix: Display heading level dropdown icons and labels

### LINKED ISSUE #51996: Heading level dropdown missing icons and text
## Description

After inserting a Heading block, the toolbar button does not display an icon.
Also, after opening the heading level dropdown, the level icons and text are
missing. 

This regression appears to have been introduced through #46003.

## Step-by-step reproduction instructions

1. Add a Heading block to a post.
1. In the toolbar above the keyboard, note the heading level button does not
   display an icon.
1. Tap the heading level button.

## Expected behaviour

The heading level dropdown displays a list of buttons with an icon and label for
each heading level.

## Actual behaviour

The heading level dropdown displays an list of empty buttons.

## Screenshots or screen recording (optional)

| Toolbar Button | Dropdown List |
| - | - |
| heading-level-button-empty | heading-level-dropdown-empty |

## WordPress information
- WordPress version:  6.2.2
- Gutenberg version:  16.0.0
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? 
  Yes

## Device information
- Device:  iPhone 13 mini
- Operating system:  iOS 16.5.1
- WordPress app version:  22.7.0.0

### PR DESCRIPTION
**Pull request by dcalhoun**
## Related PRs

* https://github.com/wordpress-mobile/gutenberg-mobile/pull/5911

## What?

Fix the heading level dropdown menu to display the active selection, as well as
icons and labels for all options.

## Why?

Fixes #51996. The heading level dropdown was near-impossible to use due to its
broken state.

## How?

- fix: Heading level dropdown displays active selection
    A recent refactor for web was only partially applied to the sibling
    native files. This finishes the application so that the active selection
    is displayed, passed through via the `value` prop.

    https://github.com/WordPress/gutenberg/pull/46003
- fix: Heading level dropdown leverages Icon
    Without using Icon, the SVG elements rendered without a width, causing
    layout issues and invisible icons.

## Testing Instructions

1. Add a Heading block. 
1. Tap the "Change level" button (displayed with an `H2` icon).
1. Verify the current selection has a checkmark and all icons and labels display.

### Testing Instructions for Keyboard

n/a

## Screenshots or screencast 
See #51996.

### CODE REVIEW

File: packages/block-editor/src/components/block-heading-level-dropdown/heading-level-icon.js [hunk 1]
```diff
@@ -39,5 +40,9 @@ const LEVEL_TO_PATH = {
  * @return {?WPComponent} The icon.
  */
 export default function HeadingLevelIcon( { level } ) {
-	return LEVEL_TO_PATH[ level ] ?? null;
+	if ( LEVEL_TO_PATH[ level ] ) {
+		return <Icon icon={ LEVEL_TO_PATH[ level ] } />;
+	}
```
Comment (dcalhoun) [inline packages/block-editor/src/components/block-heading-level-dropdown/heading-level-icon.js:45]: This fixes the invisible icons for the mobile editor. 

From testing the web editor, this change did not appear to cause issues. @carolinan would you please confirm this is appropriate? Thanks! 🙇🏻

Comment (carolinan) [reply packages/block-editor/src/components/block-heading-level-dropdown/heading-level-icon.js:45]: It works as expected, thank you.

File: packages/block-editor/src/components/block-heading-level-dropdown/index.native.js [hunk 2]
```diff
@@ -53,9 +57,9 @@ export default function HeadingLevelDropdown( { selectedLevel, onChange } ) {
 
 	return (
 		<DropdownMenu
-			icon={ <HeadingLevelIcon level={ selectedLevel } /> }
-			controls={ HEADING_LEVELS.map( ( index ) =>
-				createLevelControl( index, selectedLevel, onChange )
+			icon={ <HeadingLevelIcon level={ value } /> }
+			controls={ options.map( ( index ) =>
```
Comment (carolinan) [inline packages/block-editor/src/components/block-heading-level-dropdown/index.native.js:61]: This is embarrassing, thank you.

**Review by geriux — APPROVED** [review]
LGTM! Thanks for fixing this regression 🚀 Tested the changes using the demo app on both iOS and Android.
