### PR TITLE
Fix legacy widget previews

### LINKED ISSUE #31935: Legacy widgets are not visible on the widget screen until clicked
## Description

If I place widgets and then activate Gutenberg, the legacy widgets are not visible in the widget areas until I click on the widget
(I don't mean clicking on the widget area to expand a closed widget area, but clicking inside it).

## Step-by-step reproduction instructions

1. Activate a theme with widget areas.
2. Place widgets.
3. Activate Gutenberg.
4. Go to the widget screen, see that the widget areas look empty.

## Expected behaviour

I expect the widgets to be visible.

## Actual behaviour

The legacy widget is not visible in the widget area until I click on the widget.

## Screenshots or screen recording (optional)

legacy-widgets

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: Tested with current trunk and 10.6.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Tested with both Twenty Twenty and Aaron.

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome Version 90.0.4430.212

### PR DESCRIPTION
**Pull request by talldan**
## Description
Closes #31935
Addresses half of #31960

The problem was that the code that dynamically resizes preview iframes didn't take into account that all but the first widget area is collapsed when loading the screen. The height was resolving to `0` in those collapsed widget areas and not being recalculated when the widget area expanded.

This PR does a couple of things:
- Use an IntersectionObserver to calculate height when an iframe becomes visible (yay! No IE11)
- Adjust the height calculation to solve another issue where previews were being cut-off at the bottom

## How has this been tested?
1. Use a theme with enough widget areas
2. Add a legacy widget to an area that's not the first and save
3. Reload
4. Expand the widget area with the legacy widget, the preview should be displayed

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by critterverse** [comment]
Nice, I'm no longer seeing the "ghost widget" issue 😁

~Spotted a couple of bugs using Twenty-Twenty theme~ Nevermind! Seeing these bugs in `trunk` as well and opened a new issue in https://github.com/WordPress/gutenberg/issues/32279

**Review by noisysocks — APPROVED** [review]
Nice work!

File: packages/block-library/src/legacy-widget/edit/preview.js [hunk 1]
```diff
@@ -6,13 +6,44 @@ import classnames from 'classnames';
...
+				// alone doesn't take that margin into account.
+				setIframeHeight( boundingRect.top + boundingRect.height );
+			}
+		}
+
+		const { IntersectionObserver } = iframe.ownerDocument.defaultView;
+
+		// Observe for intersections that might cause a change in the height of
+		// the iframe, e.g. a Widget Area becoming expanded.
+		const intersectionObserver = new IntersectionObserver( onChange, {
```
Comment (kevin940726) [inline packages/block-library/src/legacy-widget/edit/preview.js:35]: Should we also call `intersectionObserver.disconnect()` to free up the memory?

File: packages/block-library/src/legacy-widget/edit/preview.js [hunk 2]
```diff
@@ -6,13 +6,44 @@ import classnames from 'classnames';
...
+	// Resize the iframe on either the load event, or when the iframe becomes visible.
+	const ref = useRefEffect( ( iframe ) => {
+		function onChange() {
+			const boundingRect = iframe?.contentDocument?.body?.getBoundingClientRect();
+			if ( boundingRect ) {
+				// Include `top` in the height calculation to avoid the bottom
+				// of widget previews being cut-off. Most widgets have a
+				// heading at the top that has top margin, and the `height`
+				// alone doesn't take that margin into account.
+				setIframeHeight( boundingRect.top + boundingRect.height );
```
Comment (kevin940726) [inline packages/block-library/src/legacy-widget/edit/preview.js:27]: I'm still seeing scrollbars when expanding a widget area though.

image

Maybe we need to do something like this:

```js
const height = Math.max(
  boundingRect.top + boundingRect.height,
  iframe.contentDocument.documentElement.scrollHeight,
);
```

File: packages/block-library/src/legacy-widget/edit/preview.js [hunk 3]
```diff
@@ -6,13 +6,44 @@ import classnames from 'classnames';
...
  */
+import { useRefEffect } from '@wordpress/compose';
 import { addQueryArgs } from '@wordpress/url';
 import { useState } from '@wordpress/element';
 import { Placeholder, Spinner, Disabled } from '@wordpress/components';
 import { __ } from '@wordpress/i18n';
 
 export default function Preview( { idBase, instance, isVisible } ) {
-	const [ iframeHeight, setIframeHeight ] = useState( null );
+	const [ iframeHeight, setIframeHeight ] = useState();
```
Comment (kevin940726) [inline packages/block-library/src/legacy-widget/edit/preview.js:16]: Why removing `null`? I believe it was served to be the default initial value as the loading state.

Maybe we should just use a loading state here, and set the height directly via DOM API (`iframe.style.height`).

File: packages/block-library/src/legacy-widget/edit/preview.js (hunk 2 above)
Comment (tellthemachines) [reply packages/block-library/src/legacy-widget/edit/preview.js:27]: Haha I was just popping in to say we could use `contentDocument.documentElement.scrollHeight` instead of the body boundingRect to simplify calculations and get rid of the scrollbar 😄

Comment (talldan) [reply packages/block-library/src/legacy-widget/edit/preview.js:27]: scrollHeight is how it used to work, but it doesn't take into account margins.

I didn't see any scrollbars in testing, but I guess it needs to be iterated.

File: packages/block-library/src/legacy-widget/edit/preview.js (hunk 1 above)
Comment (talldan) [reply packages/block-library/src/legacy-widget/edit/preview.js:35]: Sounds good. First time using `intersectionObserver`, so wasn't aware it needed to be `disconnect`ed.

File: packages/block-library/src/legacy-widget/edit/preview.js (hunk 3 above)
Comment (talldan) [reply packages/block-library/src/legacy-widget/edit/preview.js:16]: Ah, ok, didn't notice that. I think using `null` in that way is definitely confusing. I appreciate the change in #33191, which improves that.

File: packages/block-library/src/legacy-widget/edit/preview.js (hunk 2 above)
Comment (tellthemachines) [reply packages/block-library/src/legacy-widget/edit/preview.js:27]: The idea was to measure the scrollHeight of the `html` element, so it includes the margins of all the elements inside, whereas with the `body` they sometimes collapse out of it.

File: packages/block-library/src/legacy-widget/edit/preview.js (hunk 1 above)
Comment (tellthemachines) [reply packages/block-library/src/legacy-widget/edit/preview.js:35]: What does `IntersectionObserver` actually do? There seem to be no docs for it and the name confuses the heck out of me. I don't understand what an intersection might be in this context 😅

Comment (talldan) [reply packages/block-library/src/legacy-widget/edit/preview.js:35]: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

It's usually used for lazily showing stuff that's scrolled into view, but also works in this case. The idea is to observe for when the block preview element becomes visible (the widget area is expanded) and only calculate the height of the content when that happens. This was the first time I've had the chance to use it because I've always had to support IE before. 😄

File: packages/block-library/src/legacy-widget/edit/preview.js (hunk 2 above)
Comment (talldan) [reply packages/block-library/src/legacy-widget/edit/preview.js:27]: Ah yeah, sorry, I missed that bit of nuance.

File: packages/block-library/src/legacy-widget/edit/preview.js (hunk 1 above)
Comment (tellthemachines) [reply packages/block-library/src/legacy-widget/edit/preview.js:35]: Oooh nice, I didn't realise it was an actual web API!

**Comment by a4jp-com** [comment]
I'm having the same problem in WordPress 6.6.1.
