### PR TITLE
Fix applying backgrounds and colors to the columns block in the editor

### LINKED ISSUE #20804: Gutenberg 7.7 Adding background color to columns bug.
**Describe the bug**
Adding background color to the Columns block only works on the front end, and not in the editor.

**To reproduce**
1. Create a columns block.
2. Add contents to the columns, but NOT paragraph block, as adding a paragraph block to a column will result in column selection problems !
3. Add a background color to the columns block.
4. Observe that the background color is not displayed in the editor, but it is correctly displayed on the front end.

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro
 - Browser Chrome
- Fresh installation on Xampp (localhost), WP 5.3.2, Gutenberg 7.7 plugin, default 20/20 theme, php 7.x.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #20804 

The problem was that the components returned by the useColors hook try to magically apply props to their children. This works in most case but doesn't here since InnerBlocks doesn't accept extra props.

**Solution**

I updated the useColors components to support children as function pattern and just pass the props to add to that function leaving the merge responsibiity to the caller.

### CODE REVIEW

File: packages/block-library/src/columns/edit.js [hunk 1]
```diff
@@ -102,17 +102,29 @@ function ColumnsEditContainer( {
...
-						__experimentalMoverDirection="horizontal"
-						ref={ ref }
-						__experimentalTagName={ Block.div }
-						__experimentalPassedProps={ {
-							className: classes,
-						} }
-					/>
-				</TextColor>
+				{ ( backgroundProps ) => (
+					<TextColor>
```
Comment (youknowriad) [inline packages/block-library/src/columns/edit.js]: @jorgefilipecosta Do you think you can help to update the useColors API to avoid producing multiple components and just return a single `ApplyColors` instead? I think that flexibility is harming the API and making things more complex than they should be.

Comment (ellatrix) [reply packages/block-library/src/columns/edit.js]: I don't love the implicitness of these components. It's very unclear how these work at first.

File: packages/block-library/src/columns/edit.js [hunk 2]
```diff
@@ -102,17 +102,29 @@ function ColumnsEditContainer( {
...
+						{ ( textColorProps ) => (
+							<InnerBlocks
+								allowedBlocks={ ALLOWED_BLOCKS }
+								__experimentalMoverDirection="horizontal"
+								ref={ ref }
+								__experimentalTagName={ Block.div }
+								__experimentalPassedProps={ {
```
Comment (ellatrix) [inline packages/block-library/src/columns/edit.js]: I've been wondering how to best improve this API... Maybe we should just spread the props like we do for `RichText`.

Comment (youknowriad) [reply packages/block-library/src/columns/edit.js]: @aduth do you have thoughts here?

File: packages/block-library/src/columns/edit.js (hunk 1 above)
Comment (youknowriad) [reply packages/block-library/src/columns/edit.js]: I don't either, though merging style and classname props can be tricky if left to the consumer. I believe that's the main reason for the implicitness. 

I do believe though that we should have a single component and not multiple ones.

Comment (youknowriad) [reply packages/block-library/src/columns/edit.js]: Implicitness can be good if we have multiple hooks:

```
ApplyColors
ApplyFontSizes
ApplyGlobalStyles
```

merging could become a nightmare.

File: packages/block-library/src/columns/edit.js (hunk 2 above)
Comment (aduth) [reply packages/block-library/src/columns/edit.js]: Could we just have a render prop?

```jsx
<InnerBlocks
    allowedBlocks={ ALLOWED_BLOCKS }
    __experimentalMoverDirection="horizontal"
    ref={ ref }
>
    { ( { children } ) => (
        <div 
            className={ classnames(
                classes,
                backgroundProps.className,
                textColorProps.className
            ) }
            style={ {
                ...backgroundProps.style,
                ...textColorProps.style,
            } }
        >
            { children }
        </div>
    ) }
</InnerBlocks>
```

Comment (youknowriad) [reply packages/block-library/src/columns/edit.js]: The columns block doesn't. have any other wrapper rendered by InnerBlocks, so that div rendered inside the render function here should be the same one rendered by the BlockList component. I believe a render prop makes this more complex.

**Comment by youknowriad** [comment]
I'm thinking we should merge this PR as it's an important bug fix and continue on the API discussion.

**Review by aduth — APPROVED** [review]

File: packages/block-library/src/columns/edit.js (hunk 1 above)
Comment (jorgefilipecosta) [reply packages/block-library/src/columns/edit.js]: > @jorgefilipecosta Do you think you can help to update the useColors API to avoid producing multiple components and just return a single ApplyColors instead? I think that flexibility is harming the API and making things more complex than they should be.


We can plan on making this change but I think it is a big API change. Currently "TextColor" is a component that applies styles and classes to descendants but TextColor.setColor contains a function to change the TextColor value, TextColor.slug displays the slug of the color. What would be the ideal return API? Should we return ApplyStyles and then have ApplyStyles.textColor.setColor? Should we return an object with { ApplyStyles, textColor, backgroundColor } ?
The colors may not all be applied to the same elements, in this case, the expectation is that users will use multiple hook calls?
Doing this with ApplyColors also some use cases more difficult. For example, a case where we have a backgroundColor applied to a div, and textColor applied to a descendent of the div will require two multiple hook calls and in that case, contrast checking will not work right away (the developer will need to use the contrast checking components).

Comment (youknowriad) [reply packages/block-library/src/columns/edit.js]: `{ ApplyStyles, textColor, backgroundColor }` This is closer to what I think the AAPI should be but before returning these extra values, It would be good to understand if and how they're used today.

> The colors may not all be applied to the same elements, in this case, the expectation is that users will use multiple hook calls?

This is very rare but yes.

> Doing this with ApplyColors also some use cases more difficult. For example, a case where we have a backgroundColor applied to a div, and textColor applied to a descendent of the div will require two multiple hook calls and in that case, contrast checking will not work right away (the developer will need to use the contrast checking components).

Contrast checking could be its own hook that is used internally by useColors or used externaly;

--- 
I agree that both approaches have drawbacks but we should monitor the existing use-cases, I believe it will become clearer which API is best.
