### PR TITLE
Core Data: Support server side save filters.

### LINKED ISSUE #17491: Editor stuck in dirty mode due to received sanitized data
Gutenberg 6.4 introduced the following bug:
When (meta) data is saved along a post, which is sanitized server side, the returned updated data is not available/synced in the core/editor data store as it was pre-6.4. 

**Steps to reproduce the buggy behavior/output**
1. In WP 5.2.3 (with Gutenberg 6.4 or 6.5 active) register the test meta field:
`add_action( 'init', function() {
    register_post_meta( 'page', 'test_key', array(
        'show_in_rest' => true,
        'single' => true,
        'type' => 'string',
        'sanitize_callback' => 'sanitize_key',
    ));
});`
_Please note the sanitize callback_ 

2. Add and publish a test page 

3. Open the console and enter:
`> wp.data.dispatch('core/editor').editPost({ meta: { test_key: 'TEST!!!' } })`

4. Press the `[Update]` button 
The post will be saved but please note that the button will stay active! ... so the document is still 'dirty'

5. Paste in console:
`> wp.data.select('core/editor').getEditedPostAttribute('meta')`
The console will show:
`< {test_key: "TEST!!!"}`
So it still shows the old data
If you have a look at the Network output you'll see that the back-end *did* return the expected sanitized data correctly though:
network-response

**Expected behavior/output**
If your repeat the same steps without Gutenberg active or with a pre-6.4 version then the 
console output will be as expected showing the sanitized data:
`< {test_key: "test"}`
+ the `[Update]` button will be greyed-out after the post has been saved. 
+ The document is no longer dirty.

**Screenshots**
Console output (bugged) with Gutenberg 6.4 or 6.5:
bug-console-content

Console output (correct) without Gutenberg or pre-6.4:
no-bug-console-content

**Notes:**
Please also note that the pre GB 6.4 test returns 'undefined' after the dispatch while
the GB 6.5 test returns: 'Promise {<resolved>: undefined}'
Maybe that is an indication where the bug originates?

This bug leads to a very bad user experience in real world situations:
- withSelect(TextControl) related to the meta won't be updated with the server returned sanitized value 
- the editor will remain in dirty state:
  - the Update button will stay active, no matter how often you click it. 
  - when the user in the end moves away from the edited page they get a warning alert about lossing unsaved data.

I don't know of any work-around.
Not sanitizing the data would be unsafe and also user unfriendly.

P.S. tested in real world situation and in simplified local test situation with blank WP 5.2.3 installation and WP 5.3beta1, with and without Gutenberg plugin active (tested with versions 6.3,6.4 and 6.5). No other plugins and Twenty Nineteen theme.

### PR DESCRIPTION
**Pull request by epiqueras**
## Description

`core-data` saving had an issue where edits (and dirtyness) would be kept after saving when the server had filters that modified the data. This happened because the client did not recognize the edits as persisted if the API responded with different values to what was sent.

This PR fixes this by considering that the API can change values while saving, and it changes `core-data` so it will not keep the corresponding edits unless they were made after the request was sent.

## How has this been tested?

This filter was added to test the behavior with a post title filter:

```php
function test_filter_post_data( $data, $postarr ) {
	if ( 'error' === $data['post_title'] ) {
		throw new Exception();
	}

	$data['post_title'] .= '_filtered!';
	return $data;
}
add_filter( 'wp_insert_post_data', 'test_filter_post_data', 10, 2 );
```

It was then verified that saving `error` keeps everything as is, but saving any other title clears dirty state and sets the current title to whatever you saved with ` '_filtered!'` concatenated at the end.

## Types of Changes

*New Feature:* `core-data` now plays nice with server side save filters.

## Checklist:

- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 

closes #17491

### CODE REVIEW

**Comment by youknowriad** [comment]
Unrelated, but it would be good to clear the "saving error notice" if the next save is successful.

File: packages/core-data/src/actions.js [hunk 1]
```diff
@@ -333,6 +334,18 @@ export function* saveEntityRecord(
...
+			// We perform an optimistic update here to clear all the edits that
+			// will be persisted so that if the server filters them, the new
+			// filtered values are always accepted.
+			persistedEntity = yield select(
+				'getEntityRecord',
+				kind,
+				name,
+				recordId
+			);
+			yield receiveEntityRecords( kind, name, { ...persistedEntity, ...data }, undefined, true );
```
Comment (youknowriad) [inline packages/core-data/src/actions.js]: data doesn't have the "raw" keys, and persistedEntity does, which means we'll end up with a persisted entity with a separate format. Do you think we should just merge into the "raw" values instead?

File: packages/core-data/src/actions.js [hunk 2]
```diff
@@ -342,6 +355,13 @@ export function* saveEntityRecord(
 		}
 	} catch ( _error ) {
 		error = _error;
+
+		// If we got to the point in the try block where we made an optimistic update,
+		// we need to roll it back here.
+		if ( persistedEntity ) {
+			yield receiveEntityRecords( kind, name, persistedEntity, undefined, true );
+			yield editEntityRecord( kind, name, recordId, record, { undoIgnore: true } );
```
Comment (youknowriad) [inline packages/core-data/src/actions.js]: This is make the assumption that `record` was part of the `edits` but that's not necessarily the case here since anyone can call ` saveEntityRecord` with any set of values.

I'm thinking a more logical place for all these optimisic updates and rollback is `saveEditedEntityRecord`

**Review by youknowriad — COMMENTED** [review]
Tested and works well

File: packages/core-data/src/actions.js (hunk 1 above)
Comment (epiqueras) [reply packages/core-data/src/actions.js]: It shouldn't be a problem. Merging seems riskier.

Comment (youknowriad) [reply packages/core-data/src/actions.js]: we just have to make sure the expectations are correct in the selectors relying on that value.

File: packages/core-data/src/actions.js (hunk 2 above)
Comment (epiqueras) [reply packages/core-data/src/actions.js]: Maybe that's a good thing, because of how we use it in `editor` to send the latest serialized content?

Comment (youknowriad) [reply packages/core-data/src/actions.js]: I think it's broken tbh because the API does more that what it's supposed to do. Imagine someone calling that function from a plugin and polluting the edit state?

Isn't it possible to refactor the editor store to rely on `saveEditedEntityRecord` (maybe with an `editEntityRecord` call before)?

Comment (epiqueras) [reply packages/core-data/src/actions.js]: Most of the data we need is also already in `saveEntityRecord`.

How does this look to you: https://github.com/WordPress/gutenberg/pull/17532/commits/ecf3b843aa2596163ea81f0c1f18d6ddaeefaa9c?

Comment (youknowriad) [reply packages/core-data/src/actions.js]: It is better I think, if we were to ship this I'd mark this option as experimental as I still think it's not the right place for this behavior entirely.

Comment (epiqueras) [reply packages/core-data/src/actions.js]: Nevermind, the issue is that we are restoring `record`, we should just restore the previous edit state and we won't have any issues.

File: packages/core-data/src/actions.js (hunk 1 above)
Comment (epiqueras) [reply packages/core-data/src/actions.js]: Yeah

File: packages/core-data/src/actions.js (hunk 2 above)
Comment (epiqueras) [reply packages/core-data/src/actions.js]: https://github.com/WordPress/gutenberg/pull/17532/commits/aa967a0ed1ad2bba6da6235dac772d5215badfdc Done!

File: packages/core-data/src/actions.js [hunk 3]
```diff
@@ -342,6 +362,22 @@ export function* saveEntityRecord(
...
+		// we need to roll it back here.
+		if ( persistedEntity && currentEdits ) {
+			yield receiveEntityRecords( kind, name, persistedEntity, undefined, true );
+			yield editEntityRecord(
+				kind,
+				name,
+				recordId,
+				{
+					...currentEdits,
+					...( yield select( 'getEntityRecordEdits', kind, name, recordId ) ),
```
Comment (youknowriad) [inline packages/core-data/src/actions.js]: Do we really need this though? Isn't it the regular behavior of `editEntityRecord` to merge?

Comment (epiqueras) [reply packages/core-data/src/actions.js]: Yes, but the old values would overwrite the new ones made in-flight.

Comment (youknowriad) [reply packages/core-data/src/actions.js]: Right 👍

**Review by youknowriad — APPROVED** [review]
LGTM 👍 Thanks for the fixes Enrique

This is probably something that could use an e2e test but not a blocker for this PR. We can work on it later if needed.

**Comment by epiqueras** [comment]
>Unrelated, but it would be good to clear the "saving error notice" if the next save is successful.

I thought it would happen automatically, because they use the same notice ID, is this not expected of the notices package?

>This is probably something that could use an e2e test but not a blocker for this PR. We can work on it later if needed.

Yeah.

**Comment by youknowriad** [comment]
> I thought it would happen automatically, because they use the same notice ID, is this not expected of the notices package?

It would but there's no success notices for draft saves :)

**Comment by epiqueras** [comment]
Should I add an explicit `removeNotice` here?

**Comment by youknowriad** [comment]
We could add a remove on successful saves (but probably something in the editor store instead, I'm also fine for it being a separate PR)

**Comment by epiqueras** [comment]
Sounds good.

**Comment by glendaviesnz** [comment]
FYI - this fixes an issue we were having with full site editing - https://github.com/Automattic/wp-calypso/issues/36015 - the FSE posts currently have the header and footer template blocks added and stripped server side, and this was causing the edits/dirty state to be retained following a successful save. I am not able to replicate this issue after applying this patch locally.

**Comment by epiqueras** [comment]
@glendaviesnz That's great. I'll merge this as soon as the CI issues are resolved.
