### PR TITLE
Prevent autocompleter from letting users insert two More blocks

### LINKED ISSUE #4225: Autocompleter lets you insert multiple More blocks
more-bug

#### Steps to reproduce
1. Create a new post
2. Insert a More block using the /slash shortcut.
3. Insert another More block using the /slash shortcut.

#### Expected result
Step (3) should be impossible as only one More is allowed in a post.

#### Actual result
[More, More, More!](https://www.youtube.com/watch?v=hVZKJt4WzxM&feature=youtu.be&t=51)

#### Root cause
Autocompleter doesn't respect the `useOnce` property.

### PR DESCRIPTION
**Pull request by noisysocks**
Fixes #4225.

Makes autocompleters respect the `isDisabled` property that's set by `getInserterItems()`. This means that one can no longer insert two More blocks via the / autocompleter.

more-fix

## How has this been tested?
1. Create a new post
2. Insert a More block using the / shortcut.
3. Insert another More block using the / shortcut—ha ha, you can't! 😏

### CODE REVIEW

File: components/autocomplete/index.js [hunk 1]
```diff
@@ -242,6 +250,10 @@ export class Autocomplete extends Component {
 		const { open, range, query } = this.state;
 		const { getOptionCompletion } = open || {};
 
+		if ( option.isDisabled ) {
```
Comment (brandonpayton) [inline components/autocomplete/index.js]: I wondered why this was necessary due to the button actually being disabled. Now I see it is due to the fact that our keyboard listener calls `select` with indiscriminately when ENTER is pressed. I wonder if it would be clearer to conditionally call `select` in `handleKeyDown`. Just sharing my experience in case you concur.

File: components/autocomplete/index.js [hunk 2]
```diff
@@ -345,6 +357,7 @@ export class Autocomplete extends Component {
 				value: optionData,
 				label: completer.getOptionLabel( optionData ),
 				keywords: completer.getOptionKeywords ? completer.getOptionKeywords( optionData ) : [],
+				isDisabled: completer.isOptionDisabled ? completer.isOptionDisabled( optionData ) : false,
 			} ) );
 
 			const filteredOptions = filterOptions( this.state.search, keyedOptions );
```
Comment (brandonpayton) [inline components/autocomplete/index.js]: It may be a pathological case, but since we show a limited number of options at a time, it is technically possible for all shown options to be disabled. Maybe we should update filterOptions to sort disabled options to the end.

**Review by brandonpayton — APPROVED** [review]
Thanks for fixing this!

I left a couple of comments, but I don't think either should be blockers for getting this in.

File: components/autocomplete/index.js (hunk 1 above)
Comment (noisysocks) [reply components/autocomplete/index.js]: Yeah, we re-use `select()` in both the `keyDown` and `onClick` handlers. I think it's OK to leave as is.

File: components/autocomplete/index.js (hunk 2 above)
Comment (noisysocks) [reply components/autocomplete/index.js]: Really like this idea, but let's punt on it until disabled items are a more common occurrence. Right now it's really only the More block case that we have to support.

**Comment by noisysocks** [comment]
Thanks Brandon! ❤️
