### PR TITLE
fix/3795: Stop the link modal from triggering maybeStartTyping

### LINKED ISSUE #3795: Link modal closes upon typing into UrlInput when toolbar is docked to the paragraph
## Issue Overview
The link dialog only works when the toolbar is docked to the top. When the toolbar is docked to the block the link dialog is closed as soon as any attempt to type into it.

## Steps to Reproduce (for bugs)

1. Set the "Toolbar" setting to "Fix toolbar to block"
2. Create a paragraph block and type some words.
3. Place the cursor in the middle of a word and click the link button
4. Try to type into the link URL input field.

I have replicated this in Chrome and Firefox on Linux Mint.

## Expected Behavior
I expect that the link dialog will remain visible and the letters typed will appear in the URL input.

## Current Behavior
The link dialog is closed immediately.

## Possible Solution
I suspect this bug is being caused by the slot/fill system causing the events to be sent to a different element.

### link dialog closing when attached to the block
link-dialog-with-toolbar-on-block

### link dialog working when docked to the top
link-dialog-with-toolbar-docked-to-top

## Related Issues and/or PRs
No known related issues.

### PR DESCRIPTION
**Pull request by BoardJames**
## Description
When the toolbar is attached to the block any typing in the link modal would trigger the maybeStartTyping event which would hide the toolbar and in process also hide the link modal. This fixes the problem by suppressing the KeyPress event.

Fixes #3795 

## How Has This Been Tested?
Manually tested in Firefox and Chrome on Linux mint.

## Types of changes
Bug fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: blocks/editable/format-toolbar/index.js [hunk 1]
```diff
@@ -42,6 +42,13 @@ const FORMATTING_CONTROLS = [
 // Default controls shown if no `enabledControls` prop provided
 const DEFAULT_CONTROLS = [ 'bold', 'italic', 'strikethrough', 'link' ];
 
+/* We need to stop the keypress event here, because block.js is firing
+	 a maybeStartTyping on keypress, and that hides the "fixed-to-block" toolbar
+	 which unregisters the slot, so when Editable tries to re-render its input
+	 dialog, the slot is no longer in the system, and the dialog disappears
+ */
```
Comment (noisysocks) [inline blocks/editable/format-toolbar/index.js]: nit: Could you shorten this to a one line comment? It's enough that the comment gives the reader a quick heads up so that they can e.g. run a `git blame` if they'd like to learn more about the bug fix.

My suggestion:

```js
// Stop the keypress event from propagating up to maybeStartTyping in BlockListBlock
const stopKeyPressPropagation = ( event ) => event.stopPropagation();
```

**Review by noisysocks — APPROVED** [review]
Thanks for looking into this! 

👍 I was able to reproduce the issue and confirm that this PR fixes it.
