### PR TITLE
Exclude reusable blocks from the global block count

### LINKED ISSUE #11744: Content Structure: Reusable blocks that aren't in the page are counted
**Describe the bug**
The _Content Structure_ component mistakenly includes reusable blocks that aren't attached to the page in its _Blocks_ count.

**To Reproduce**
1. Create a new post
2. Insert a block
3. Convert it to a reusable block
5. Click _Content Structure_
6. It reports that there are 2 blocks

**Expected behavior**
_Content Structure_ should report that there is 1 block in the post.

**Screenshots**
screen shot 2018-11-12 at 10 40 05

### PR DESCRIPTION
**Pull request by noisysocks**
Fixes #11744.

Modifies `getGlobalBlockCount()` to exclude reusable blocks from its count. This fixes the block count including reusable blocks that have been parsed and stored into `blocks.byClientId` but not inserted into the post or page.

#### How to test

1. Create a new post
2. Insert a block
3. Convert it to a reusable block
5. Click _Content Structure_
6. It should report that there is 1 block

### CODE REVIEW

**Review by jorgefilipecosta — COMMENTED** [review]
Hi @noisysocks, this seems an improvement and addresses some problems.
But we need to take into consideration the descendants of the child blocks.
If we convert a columns block with two columns and with one paragraph inside each column to a reusable block, the columns block is not counted but the 2 "column" blocks and 2 paragraph blocks are counted so we have an additional four blocks in the global block count.
We are also taking into account all paragraphs and headings inside reusable blocks in the global headings and paragraphs counts.

**Comment by mtias** [comment]
> We are also taking into account all paragraphs and headings inside reusable blocks in the global headings and paragraphs counts.

I'd consider this a nice to have and not high priority. The most important is to fix the surplus in the counts.

**Comment by noisysocks** [comment]
Thanks Jorge! Good catch. I've modified the selector to use `getClientIdsWithDescendants` which does exactly what we need here.

File: packages/editor/src/store/selectors.js [hunk 1]
```diff
@@ -728,16 +727,17 @@ export const getClientIdsWithDescendants = createSelector(
...
-			0
-		);
+		return reduce( clientIds, ( count, clientId ) => {
+			const block = state.editor.present.blocks.byClientId[ clientId ];
+			return block.name === blockName ? count + 1 : count;
+		}, 0 );
 	},
 	( state ) => [
+		state.editor.present.blocks.order,
 		state.editor.present.blocks.byClientId,
```
Comment (youknowriad) [inline packages/editor/src/store/selectors.js]: Is it really worth memoizing selectors if they depend on these two elements particularly? I feel `state.editor.present.blocks.byClientId` changes so often that it's just a waste of time to memoize these selectors.

Comment (youknowriad) [reply packages/editor/src/store/selectors.js]: Thoughts on this @aduth?

Comment (noisysocks) [reply packages/editor/src/store/selectors.js]: But it seems wasteful to have this selector run when something unrelated e.g. a post attribute is modified, no?

Comment (youknowriad) [reply packages/editor/src/store/selectors.js]: I don't know honestly, it feels like typing in blocks is the most impactful thing in terms of performance, changing an attribute only get triggered once and not extensively. 

Anyway, just something to keep in mind for now, there's no clear "winner"

**Review by youknowriad — APPROVED** [review]
LGTM 👍
