### PR TITLE
Fix media placeholder to only activate for media objects.

### LINKED ISSUE #66422: Cover block MediaPlaceholder interferes with block inserter drag and drop
### Description

The cover block's `MediaPlaceholder` seems to prevent dragging and dropping blocks or patterns from the block inserter.

Additionally, it seems to interpret these blocks/patterns as files and shows incorrect messaging in the UI.

This issue may also happen for other blocks that use `MediaPlaceholder` but it's hard to say as I haven't tested widely.

### Step-by-step reproduction instructions

1. Insert a cover block
2. Open the inserter and try dragging a paragraph block over the placeholder
3. Observe it shows a message 'Drop files to upload' even though files aren't being dragged
4. Select a color from the placeholder
5. Try dragging a block or pattern from the inserter into the cover block (which is now not showing the placeholder and should accept blocks)
6. Observe the 'Drop files to upload' still shows and prevents inserting any blocks or patterns into the cover block

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/c7add642-492c-454f-b214-17c84dc315ff

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

Fixes #66422.

Currently, any block or pattern being dragged from the inserter onto a Cover block activates its media placeholder. This PR changes the behaviour to activate the placeholder only if the object being dragged is an image, video or audio. (Audio won't work for Cover, but the same placeholder serves Audio blocks as well, so it needs to work for them.)

* Checks the block type in `InserterDraggableBlocks`, and sets its dataTransfer type to 'media' instead of 'html' if it's a media object. 
* Adds a new `onMediaDrop` handler type to `DropZoneComponent`, which is used if the dataTransfer type is 'media'
* Updates `MediaPlaceholder` to pass an `onMediaDrop` handler to `Dropzone` instead of `onHTMLDrop`.

## Testing Instructions

1. Pick a template with one or more Cover blocks;
2. Open the inserter and try dragging things onto the Cover blocks;
3. Only images, video and audio should activate the media placeholder.

Note that currently there's an unrelated bug in the Cover block edit function that's preventing images and videos from properly being added to the block, but at least the placeholder should be activated 😅 
I'll look into that other bug as a separate task.

## Screenshots or screencast 

https://github.com/user-attachments/assets/a08ceec5-8516-4511-92c7-32f3b9bef054

### CODE REVIEW

File: packages/block-editor/src/components/inserter-draggable-blocks/index.js [hunk 1]
```diff
@@ -29,6 +29,15 @@ const InserterDraggableBlocks = ( {
 		blocks,
 	};
 
+	const blocksContainMedia =
+		blocks.filter(
+			( block ) =>
+				( block.name === 'core/image' ||
+					block.name === 'core/audio' ||
+					block.name === 'core/video' ) &&
```
Comment (ramonjd) [inline packages/block-editor/src/components/inserter-draggable-blocks/index.js:37]: Is it worth adding `core/file` here too?

Comment (tellthemachines) [reply packages/block-editor/src/components/inserter-draggable-blocks/index.js:37]: I don't believe files should ever be handled by the media placeholder. Anything in the Media inserter tab should be either image, audio or video.

**Comment by ramonjd** [comment]
This PR fixes the bug where I can't drag blocks onto the cover block. The media placeholder isn't shown for non-media blocks. 👍🏻 

Maybe you can set me straight on something though: are the items in the "Media" columns already uploaded?

If so, maybe dragging and dropping them should create the appropriate blocks rather than trigger the upload placeholder.

Don't want to derail progress on this, so if that makes sense it could be a good follow up.

**Comment by tellthemachines** [comment]
> Maybe you can set me straight on something though: are the items in the "Media" columns already uploaded?

Yes if they appear in the "Images" "Video" or "Audio" sections, but not if they're under "Openverse". In that case, they get auto-uploaded when they're dragged in.

> If so, maybe dragging and dropping them should create the appropriate blocks rather than trigger the upload placeholder.

For Cover, the intention is that the images get added as background images, not that they're added as Image blocks inside it. I guess what we could do is change the message in the media placeholder if it's being shown by a Cover block.

File: packages/block-editor/src/components/media-placeholder/index.js [hunk 2]
```diff
@@ -288,7 +288,7 @@ export function MediaPlaceholder( {
 		}
 	}
 
-	async function onHTMLDrop( HTML ) {
+	async function onMediaDrop( HTML ) {
 		const blocks = pasteHandler( { HTML } );
 		return await handleBlocksDrop( blocks );
 	}
```
Comment (talldan) [inline packages/block-editor/src/components/media-placeholder/index.js]: Nit - it might good to make it consistent with the docs for `onMediaDrop` (though my second comment would make this unnecessary)
```suggestion
	async function onMediaDrop( media ) {
		const blocks = pasteHandler( { media } );
		return await handleBlocksDrop( blocks );
	}
```

File: packages/components/src/drop-zone/types.ts [hunk 3]
```diff
@@ -26,4 +26,9 @@ export type DropZoneProps = {
 	 * It receives the HTML being dropped as an argument.
 	 */
 	onHTMLDrop?: ( html: string ) => void;
+	/**
+	 * The function is called when dropping media into the `DropZone`.
+	 * It receives the media being dropped as an argument.
+	 */
+	onMediaDrop?: ( media: string ) => void;
```
Comment (talldan) [inline packages/components/src/drop-zone/types.ts]: I'm not sure about the idea of this new `onMediaDrop` event handler in the components package. It feels like something that's handling a very specific block editor use case. It still receives an HTML string, which might be confusing. Some consumers of the component might be confused about why it doesn't work when they're dragging media items, and it'd take some digging to find they have to set the `dataTransfer` type to `media`.

Looking at precedence, this component doesn't have an `onBlocksDrop`, that's handled via `onDrop` (in `useBlockDropZone`, and this custom dataTransfer type could work similarly?

Comment (tellthemachines) [reply packages/components/src/drop-zone/types.ts]: Hmm do you mean leveraging onDrop for the media type instead of adding a custom handler? I can give it a go!

Comment (tellthemachines) [reply packages/components/src/drop-zone/types.ts]: I updated to use `onDrop` as well as the `default` type which avoids any change to the components package. I think it's working well!

**Review by ramonjd — APPROVED** [review]
Looking good! 🚀 
Dragging blocks onto the cover block works a treat.

Here's what I'm seeing in zoomed out mode (for media items):

https://github.com/user-attachments/assets/20856856-fa6d-4279-a892-1e04894f4ccb


Not for this PR, but I think one day it'd be a good user experience to change the message from "Drop files to upload" to something else when already-uploaded media can't be dropped.

File: packages/components/src/drop-zone/types.ts (hunk 3 above)
Comment (talldan) [reply packages/components/src/drop-zone/types.ts]: I'm not really sure what the right value is for the dataTransfer type but using `onDrop` in this way looks better, thanks for changing it!

Comment (tellthemachines) [reply packages/components/src/drop-zone/types.ts]: Yeah `media` is nice because it's explicit, but here we just need something to distinguish between media and non-media; whatever value we give it, DropZone will interpret it as `default` anyway.

**Review by talldan — APPROVED** [review]
Tested a bunch of things, and it's working great now:
- When in placeholder mode, blocks insert above and below as expected
- In placeholder mode, media can be dragged in to the cover and set as the background
- With a background, blocks/patterns from the inserter can be dragged in as inner blocks
- Files and other media can still be dragged in to replace the background

Nice work!
