### PR TITLE
Writing flow: gradually 'select all' layers of nested blocks

### LINKED ISSUE #22689: unregisterShortcut doesn't work
**Describe the bug**

I want to disable the keyboard shortcut "Ctrl+A" when the focus is on a certain block that I'm creating, because it interferes with its behavior: the block has a textarea inside, and when doing "Ctrl+A" inside the textarea I want to select all text inside, but now all blocks are being selected.

So I attempted to use function `unregisterShortcut` to remove the keyboard shortcut with name `"core/block-editor/select-all"` using the code below, but it doesn't work.

Btw, I searched for an instance of `unregisterShortcut` in the Gutenberg project, but it's not used at all, there are no tests for it either, and the documentation doesn't explain how to use it.

**To reproduce**

Code:

```javascript
/**
 * WordPress dependencies
 */
import { useEffect } from '@wordpress/element';
import { useDispatch } from '@wordpress/data';

function KeyboardShortcuts() {
    return null;
}

function KeyboardShortcutsUnregister() {
    const {
        unregisterShortcut,
    } = useDispatch( 'core/keyboard-shortcuts' );
    useEffect( () => {
        console.log('inside effect');
        unregisterShortcut( 'core/block-editor/select-all' );
    }, [ unregisterShortcut ] );
    return null;
}

KeyboardShortcuts.Unregister = KeyboardShortcutsUnregister;

export default KeyboardShortcuts;
```

And then, inside my block, I include the component:

```javascript
const EditBlock = ( props ) => {
    return (
        <>
            <KeyboardShortcuts.Unregister />
            <div className={ className }>
                ...
            </div>
        </>
    );
}
```

The `console.log()` work well, printing `"inside effect"`, but the shortcut is not removed.

**Expected behavior**

Pressing "Ctrl+A" should not execute the "Select all blocks" shortcut

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? I tried both with and without the plugin, it fails with both
- If the Gutenberg plugin is installed, which version is it? 8.2.0

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.15.5
 - Browser Firefox
 - Version 76.0.1

### LINKED ISSUE #28267: Pressing Cmd+A 2 times in widget areas selects all of the widget areas rather than the widgets
## Description

Pressing <kbd>Cmd</kbd> + <kbd>a</kbd> 2 times in widget areas selects all the widget areas, but not all the widgets inside the currently selected widget area. See the below screenshot for more info.

## Step-by-step reproduction instructions

1. Go to the widgets screen
2. Select a widget area
3. Focus on a random widget inside the widget area
4. Press <kbd>Cmd</kbd> + <kbd>a</kbd> 2 times
5. Notice all the widget areas get selected

## Expected behaviour

It should instead selects all the widgets inside the currently focused widget area.

## Actual behaviour

All the widget areas and all the widgets get selected

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/7753001/104884538-7d327e80-59a1-11eb-9932-ac8283953a77.mp4

## WordPress information
- WordPress version: 5.7-alpha-49956 (`wp-env`)
- Gutenberg version: master branch
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device:  Desktop
- Operating system:  macOS
- Browser:  Chrome 87

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #28267.
Fixes #22689.

Allows you to gradually select blocks through layers of nested blocks.

gradual-select-all

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-editor/src/components/keyboard-shortcuts/index.js [hunk 1]
```diff
@@ -142,20 +135,6 @@ function KeyboardShortcuts() {
 		{ isDisabled: clientIds.length < 2 }
 	);
 
-	useShortcut(
-		'core/block-editor/select-all',
-		useCallback(
-			( event ) => {
-				event.preventDefault();
-				multiSelect(
```
Comment (ellatrix) [inline packages/block-editor/src/components/keyboard-shortcuts/index.js:150]: I only saw now that these shortcuts are duplicated here, while also being in writing flow. This doesn't make any sense. The select all shortcut should only work from a focussed block upwards. These global shortcuts will also give problems when you focus something outside the block editor and press cmd+a. In other words, it should never be a global behaviour. Additionally it will give problems in the iframe editor when we remove event bubbling through the iframe.

Comment (talldan) [reply packages/block-editor/src/components/keyboard-shortcuts/index.js:150]: There are some related issues. I found https://github.com/WordPress/gutenberg/issues/19102 and  https://github.com/WordPress/gutenberg/issues/22689 in a quick search.

I think `registerShortcut` should ideally still be called as I believe that makes the shortcut display in the shortcut help modal. And then the code in `useSelectAll` could reference that registered shortcut.

That would also have the side effect of allowing a plugin to unregister the shortcut or change the shortcut keys. This is an interesting one because it uses the same key combination as the browser shortcut, so there's a question over how that would work..

Comment (ellatrix) [reply packages/block-editor/src/components/keyboard-shortcuts/index.js:150]: You're right, I modified it to use registerShortcut again.

**Review by talldan — APPROVED** [review]
This works really well, thanks!

I also tested unregistering the shortcut and that issue is now fixed too.

File: packages/block-editor/src/components/writing-flow/use-select-all.js [hunk 2]
```diff
@@ -7,38 +7,62 @@ import { first, last } from 'lodash';
...
+		}
+
+		const [ firstSelectedClientId ] = selectedClientIds;
+		const rootClientId = getBlockRootClientId( firstSelectedClientId );
+		let blockClientIds = getBlockOrder( rootClientId );
+
+		if ( selectedClientIds.length === blockClientIds.length ) {
+			blockClientIds = getBlockOrder(
+				getBlockRootClientId( rootClientId )
+			);
```
Comment (mcsf) [inline packages/block-editor/src/components/writing-flow/use-select-all.js:51]: A comment linking to this PR would be a nice bonus to explain this little sleight of hand:

```suggestion
		// If we have selected all sibling nested blocks, try selecting up a level.
		// See: https://github.com/WordPress/gutenberg/pull/31859/
		if ( selectedClientIds.length === blockClientIds.length ) {
			blockClientIds = getBlockOrder(
				getBlockRootClientId( rootClientId )
			);
```

**Review by mcsf — APPROVED** [review]
Looks pretty good.
