### PR TITLE
Fix infinite render of inline block preview

### LINKED ISSUE #46793: Global Styles: The preview of the image block trembles
### Description

In the global style block preview, when I select an image block, the preview area does not display properly.
Scroll bars appear and disappear, and the preview area trembles.

This issue occurs when **the preview is displayed for the first time with the browser's developer tools displayed**.

https://user-images.githubusercontent.com/54422211/209616921-c320e60b-dc5b-4869-a8d1-7e5a4efa8456.mp4

When this issue occurs, the display area style calculation appears to be looping:

https://user-images.githubusercontent.com/54422211/209617146-b295b23a-9da2-4fce-8be8-78126716269f.mp4

Perhaps this problem only occurs in Windows. Because I believe that Windows scrollbars reserve width, which may affect the calculation of the style.

### Environment info

- Gutenberg version: 14.9.0
- OS: Windows 11
- Browser: Chrome

### PR DESCRIPTION
**Pull request by madhusudhand**
## What?

This fixes #46793 where inline preview re-renders infinitely.
Issue happens for blocks such as
* image
* calendar
* latest comments

## Testing Instructions

Issue happens when scrollbar is always visible.

Operating system settings:
Windows: scrollbar is visible by default.
Mac: System Preferences -> General -> show scrollbars (set the value to always)

1. Navigate to global styles in site editor
2. open settings for the blocks such as image, calendar, latest comments
3. Observe that the component renders without any issues.

#### Before

cal-preview-before

#### After

cal-preview-after

### CODE REVIEW

**Review by mikachan — APPROVED** [review]
This fixes the issue for me 👍

File: packages/edit-site/src/components/global-styles/block-preview-panel.js [hunk 1]
```diff
@@ -3,14 +3,9 @@
  */
 import { BlockPreview } from '@wordpress/block-editor';
 import { getBlockType, getBlockFromExample } from '@wordpress/blocks';
-import { useResizeObserver } from '@wordpress/compose';
 import { __experimentalSpacer as Spacer } from '@wordpress/components';
 
 const BlockPreviewPanel = ( { name, variation = '' } ) => {
-	const [
```
Comment (ntsekouras) [inline packages/edit-site/src/components/global-styles/block-preview-panel.js:10]: Hm.. why we needed `useResizeObserver` in the first place here?

Comment (madhusudhand) [reply packages/edit-site/src/components/global-styles/block-preview-panel.js:10]: To set the min-height of the preview iframe container, so that block preview (like button) is vertically center aligned.
It was captured using `useResizeObserver`, but seems like it was a bad idea for non-floating scrollbars that change with and height when they appear on content overflow.

**Review by t-hamano — APPROVED** [review]
LGTM 👍

✅ Image, Calendar, Latest Comments: Infinite loop doesn't occur
✅ Table: If `viewportWidth` is defined with example, It will still be displayed as before.
✅ Button: It will be displayed in the center as before.
✅ Quote: If the block is less than the height of the preview area, the scroll bar will not be displayed as before.


https://user-images.githubusercontent.com/54422211/216972477-22ddc82e-d381-4a7e-b485-e319a8ea1fe3.mp4

**Comment by ntsekouras** [comment]
Cherry-picked this PR to the wp/6.2 branch.
