### PR TITLE
Make responsive embeds a theme option

### LINKED ISSUE #10109: Giant space above all Youtube video in Posts
**Describe the bug**
Giant space above all Youtube video when VIEWING Posts in Gutenberg: Version 3.9.0

**To Reproduce**
1. Go to 'ALL POSTS.'
2. Click on 'EDIT'  A POST YOU KNOW HAS A YOUTUBE VIDEO
3. Scroll down to 'YOUTUBE VIDEO BLOCK'
4. You CAN'T SEE the error in the actual Post Edit, but you can see the giant space when VIEWING the post.

**Expected behavior**
There should be reasonable space around the Youtuve video.

**Screenshots**
error - space above youbue video

**Desktop (please complete the following information):**
 - OS: WINDOWS 10
 - Browser CHROME
 - Version 68.0.3440.106 (Official Build) (64-bit)

**Additional context**
Latest version of Gutenberg: Version 3.9.0

### PR DESCRIPTION
**Pull request by notnownikki**
## Description

Fixes: https://github.com/WordPress/gutenberg/issues/10109

This adds a new style, `wp-embed-responsive` to the `<body>` if the theme has opted in to `responsive-embeds`.

This allows the editor to keep the styles in the saved html and allows themes to either opt in, supply their own responsive solution, use the gutenberg provided aspect ratio styles for their own responsive solution, or to ignore them completely.

## How has this been tested?

Make a new post and embed a video from youtube, e.g. https://www.youtube.com/watch?v=lXMskKTw3Bc

Check that the published post renders fine, and the body does not have the `wp-embed-responsive` class.

Opt the theme in to `responsive-embeds`

Check the body has the `wp-embed-responsive` class and the video is responsive.

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by jasmussen** [comment]
Very nice work. 

I can confirm that for a theme that hasn't opted in, embeds are untouched, and that when opting in by pasting `add_theme_support( 'responsive-embeds' );` into functions.php, the responsive magic happens again. 

Although it would be nice if we could offer this without opt-in, I think this is the safe, and right approach. Perhaps we can remove the opt-in in a future version, and make it on by default? One can dream. And let's be sure to enable this in the Twenty themes as a "best practice", CC: @kjellr. 

We have 3 todo's:

1. We should update the theme support document as part of this PR. https://github.com/WordPress/gutenberg/blob/master/docs/extensibility/theme-support.md

Under "opt-in" features we could add:

### Responsive Embeds:

The new editor can make sure video embeds (YouTube, Vimeo) scale responsively according to viewport and aspect ratio. This will work without issue in most themes, especially themes that don't already provide some responsive mechanims. If you'd like to offer this in your theme, you can opt into this feature by calling:

```php
add_theme_support( 'responsive-embeds' );
```

---

2. We should hide this toggle if a theme hasn't opted in:

screenshot 2018-10-11 at 09 32 39

Question about that: is it sufficient to apply `display: none;` to that option, or might screenreaders pick it up regardless? I _think_ it should be fine, but we should make sure. 

3. I _think_ the body class approach is the right one, but want to make sure with @pento or @mtias. And if it is, is `wp-embed-responsive` the right classname? Should it be something along the lines of `has-responsive-embeds`? @tofumatt any thoughts?

Thanks so much for working on this Nikki!

**Comment by notnownikki** [comment]
`display: none` should stop screenreaders reading it, from working on the category filter, I know the label had to be visible for the reader to read it.

I'm not sure how to access the theme options from Gutenberg though. It's probably (hopefully) straightforward?

**Comment by notnownikki** [comment]
Ah, ignore me, I haven't had coffee yet. Just need to modify the rest api to add in info about this theme option. Simple :)

**Comment by notnownikki** [comment]
So I didn't go with `display: none` here. If the theme doesn't support the option, the toggle doesn't render at all. That's fine, because the toggle isn't required for anything apart from switching the responsive classes on/off on an individual block, so things work as expected.

**Comment by jasmussen** [comment]
Yes that does make sense, thanks for the clarification. And I'm not sure the following is possible, but I'll ask regardless. Instead of adding `wp-embed-responsive` as a class to the `body`, can we add it on a per-block basis? 

For example right now, a random YouTube video I embed has these classes:

`wp-block-embed-youtube wp-block-embed is-type-video is-provider-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio`

Could we either add an additional class to that list when the theme has opted-in, or perhaps even coopt the `wp-has-aspect-ratio` class to only show up when a theme has opted in, just to be sanitary in how many classes we add?

A theme would still be able to provide custom aspect-ratio based responsiveness based on the presence of the `wp-embed-aspect-16-9`, even if it hasn't opted into Guten-provided responsiveness.

**Comment by notnownikki** [comment]
The problem with doing it at the block level is that we'd either need to republish every post with responsive blocks in them if the theme option changes, or parse the blocks and add the classnames based on the theme option, which is expensive to do.

**Comment by jasmussen** [comment]
Given the feature has only been in one version, and that there's a fix (update post), I think that's actually fine.

**Comment by notnownikki** [comment]
With this PR, we don't even need to update the posts published with the previous version. Because the stylesheet changes only to match the responsive content if the body element as the classname, then it'll just get switched off without any further changes needed. And as soon as the theme opts in, all published posts will benefit without having to republish anything.

**Comment by jasmussen** [comment]
Yes I understand, and I've verified this works as well. If this is what we have to go with, that's fine.

My concern is that we are stuffing additional css classes into an already loaded element. And this class would be present on every single WordPress page and post, regardless of whether it included an embed or not.

It seems like it we could add this class at the block level, even if it requires updating currently published posts, this would be better for the next decade of WordPress. I just want to be sure we're looking at the long term and picking the best solution, not just the near term.

Given there are three ways to fix the additional whitespace for currently published posts affected, the toggle, removing css classes, and soon just updating the post, this seems like a small price to pay for a leaner body element.

**Comment by notnownikki** [comment]
I'm not sure that people who have a decade's worth of posts would agree there :) Loading each one into the editor to republish if they want to switch to a theme that supports responsive embeds?

If we could only output the body classname if the current post has an embed with an aspect ratio, would that be ok?

**Comment by jasmussen** [comment]
> I'm not sure that people who have a decade's worth of posts would agree there :) Loading each one into the editor to republish if they want to switch to a theme that supports responsive embeds?

But how would they? Old posts aren't affected by this are they? 

Already now older posts would need to be converted to blocks, that seems outside the scope of this issue.

**Comment by notnownikki** [comment]
> But how would they? Old posts aren't affected by this are they?

As you said, we want to plan ahead for the next decade. If someone is using a theme that doesn't opt in for the next decade, and then wants to opt in, then they'd have that problem.

**Comment by jasmussen** [comment]
>  If someone is using a theme that doesn't opt in for the next decade, and then wants to opt in, then they'd have that problem.

Oh I see, right. Solid point, I'm daft.

**Comment by notnownikki** [comment]
So if we only output the class on pages that have an embed, that means parsing the post to determine if the class should be there, and that's going to be a tough sell to systems people who run WordPress at scale, when we could include a few extra characters in the body element and save all those CPU cycles.

**Comment by jasmussen** [comment]
Yep. Probably every page is okay. But now that I finally understood the point, I think this is open to wider feedback.

**Comment by chrisvanpatten** [comment]
I wish HTML had a better method of handling these sort of pseudo-"feature flags" but since it doesn't, a body class seems like a reasonable approach for the time being.

File: lib/rest-api.php [hunk 1]
```diff
@@ -307,6 +307,43 @@ function gutenberg_register_taxonomy_prepare_functions( $taxonomy ) {
 }
 add_filter( 'registered_taxonomy', 'gutenberg_register_taxonomy_prepare_functions' );
 
+/**
+ * Ensure that the wp-json index contains the 'theme-supports' setting as
+ * part of its site info elements.
+ *
+ * @see https://core.trac.wordpress.org/ticket/45016
```
Comment (aduth) [inline lib/rest-api.php]: Based on recent discussion in the ticket, it appears the current approach for these details is via a `?status=active` parameter on the `/wp/v2/themes` endpoint, not exposing on the root.

Comment (notnownikki) [reply lib/rest-api.php]: I wondered what was going on, because I had to add this in two places for it to show up everywhere. Do I just need to remove it from here?

Comment (aduth) [reply lib/rest-api.php]: I assume we'd need to also bring in any necessary revisions to support the `status` parameter as well.

Comment (notnownikki) [reply lib/rest-api.php]: Could that be done as a separate PR? I'm a little concerned that the discussion on that ticket is still ongoing, and I don't want to delay getting this fix out to the peeps who are having theme conflicts.

**Review by desrosj — CHANGES_REQUESTED** [review]
Added some feedback to help. After this PR is finalized, the changes to `lib/class-wp-rest-themes-controller.php` need to be committed to WordPress core. I can help with that whent the time comes!

File: lib/rest-api.php [hunk 2]
```diff
@@ -307,6 +307,43 @@ function gutenberg_register_taxonomy_prepare_functions( $taxonomy ) {
...
+ *
+ * @param WP_REST_Response $response WP REST API response of the wp-json index.
+ * @return WP_REST_Response Response that contains theme-supports.
+ */
+function gutenberg_ensure_wp_json_has_theme_supports( $response ) {
+	$site_info = $response->get_data();
+	if ( ! array_key_exists( 'theme_supports', $site_info ) ) {
```
[the remark this answers is not in the document]
Comment (desrosj) [reply lib/rest-api.php]: Also, the property needs to be added to the schema for the endpoint.

File: lib/rest-api.php (hunk 1 above)
Comment (desrosj) [reply lib/rest-api.php]: Just to clarify, the changes on 45016 were merged into Gutenberg before they were committed to core. See #10518

**Comment by notnownikki** [comment]
@desrosj thank you, that's cleared it up for me, i'll get on those changes :)

File: lib/rest-api.php [hunk 3]
```diff
@@ -307,6 +307,40 @@ function gutenberg_register_taxonomy_prepare_functions( $taxonomy ) {
...
+/**
+ * Ensure that the wp-json index contains the 'theme-supports' setting as
+ * part of its site info elements.
+ *
+ * @see https://core.trac.wordpress.org/ticket/45016
+ *
+ * @param WP_REST_Response $response WP REST API response of the wp-json index.
+ * @return WP_REST_Response Response that contains theme-supports.
+ */
+function gutenberg_ensure_wp_json_has_theme_supports( $response ) {
```
[the remark this answers is not in the document]
Comment (notnownikki) [reply lib/rest-api.php]: Looks like it's there to me

[the remark this answers is not in the document]
Comment (notnownikki) [reply lib/rest-api.php]: This PR no longer modifies it, so shouldn't be an issue anyway :)

File: lib/rest-api.php (hunk 2 above)
[the remark this answers is not in the document]
Comment (notnownikki) [reply lib/rest-api.php]: Done

File: lib/rest-api.php (hunk 3 above)
Comment (danielbachhuber) [inline lib/rest-api.php]: This `gutenberg_ensure_wp_json_has_theme_supports()` function needs to be removed from the pull request because it no longer exists in `master`.

**Review by danielbachhuber — CHANGES_REQUESTED** [review]

File: lib/rest-api.php (hunk 3 above)
Comment (notnownikki) [reply lib/rest-api.php]: Whoa, sorry about that! I must have changed things _just_ enough for the merge of master to keep them instead of removing them. Changes to `lib/rest-api.php` have been reverted.

**Review by desrosj — APPROVED** [review]
This looks good to me. I opened https://core.trac.wordpress.org/ticket/45125 to update core. The tests are failing, but it appears to be a problem upstream as well.

**Comment by notnownikki** [comment]
Oh boy, that `splitting-merging.test.js` is a race condition that gets triggered sometimes. It's on my list to look at a workaround at least. Rerunning.

**Comment by notnownikki** [comment]
@danielbachhuber I think everything has been resolved now.

**Review by danielbachhuber — APPROVED** [review]

**Comment by Soean** [comment]
The docs are missing, I opened an issue: #10759

**Comment by rickcurran** [comment]
Hi, is this change going to make it into a full release? I've encountered the issue with embedded WordPress pages (such as embedding a WordPress plugin url in a page as on my page here: https://suburbia.org.uk/projects), I've had to manually disable the responsiveness on all embeds on this page to stop the gap appearing below them. But it appears this default responsive setting is incorrect at least for this type of embedded page, at least on the standard 2017 theme anyway.

**Comment by rickcurran** [comment]
Hi, is this change going to make it into a full release? I've encountered the issue with embedded WordPress pages (such as embedding a WordPress plugin url in a page), I've had to manually disable the responsiveness on all embeds on this page to stop the gap appearing below them. But it appears this default responsive setting is incorrect at least for this type of embedded page, at least on the standard 2017 theme anyway.

**Comment by notnownikki** [comment]
Yes, this will be in the 4.1 release.

**Comment by notnownikki** [comment]
Yes, this will be in the 4.1 release.

**Comment by notnownikki** [comment]
Yes, this will be in the 4.1 release.

**Comment by timhibberd** [comment]
@notnownikki - Do you know when this enhancement will get migrated into the core (V5.0)? I will be honest...as a theme designer I am having trouble trying to keep up with the changes in two places and when to raise an issue here and when to raise an issue in Trac for the core Gutenberg. I am working with the bleeding edge core 5.0 (no Gutenberg plug-in installed) and I am finding the wp-embed-responsive class is being attached to the body for the (backend) admin edit view of a page but not the (front-end) display view of a page. Is the theme supposed to add the wp-embed-responsive class to the body in the page display view or is the core supposed to do that and its omission is just a bug?

Thanks in advance. Much appreciated :-)

**Comment by notnownikki** [comment]
@timhibberd I'm not sure on how things are getting merged into 5.0, to be honest. If you're seeing `wp-embed-responsive` in the admin (as it should be, so the editor is nice on smaller screens and mobile) but not on the front end, then that would suggest this has been merged and the theme would need to opt in to this option.

@pento you would know better than me how these merges are handled, would you be able to comment here please?

**Comment by danielbachhuber** [comment]
@timhibberd The `wp-embed-responsive` class is added to the `<body>` tag currently on the `5.0` branch:

image

Notably, core development is happening on the `5.0` branch, not trunk. [See this post](https://make.wordpress.org/core/2018/10/05/wordpress-5-0-commit-management/) for more details.

The `wp-embed-responsive` body class is also added by the Gutenberg plugin as of version 4.1.

You'll want to check that you're running Gutenberg's latest version and the latest nightly WordPress build. If both of those are correct, it might be that your theme registration isn't working as expected.

**Comment by timhibberd** [comment]
Cheers @danielbachhuber. I saw that post previously but the WordPress beta documentation says to use bleeding edge via WordPress Beta Tester plugin (which pulls the release from the trunk). So I was somewhat confused as to which instruction was accurate. So I assume the WordPress Beta Tester plugin should be left in "Point release nightlies" mode.

image

Also, if I pull the nightly build (wordpress-latest.zip) from the "nightly build" link on the Beta testing page (https://make.wordpress.org/core/handbook/testing/beta/ ) I get 5.1-alpha-43678 but if I do an update from the WordPress Beta Tester plugin set to "Point release nightlies" mode I get 5.0-beta1-43832.

Are we leaping past 5.0 and going right to 5.1?

So I'm just finding the process a bit muddled w.r.t what GB is in the core vs. what gb is in the plug-in and whether I need to pull the nightly GB plug-in release to match up with the nightly core 5.1 release and whether I still need the GB plug-in installed to test my theme on core v5.x.

Thanks for clarifying that the core is adding the `wp-embed-responsive` body class to the user page view and not just the admin page view. At least I know now that is the correct end-state I am testing for.

Much appreciated :-)

**Comment by danielbachhuber** [comment]
> I saw that post previously but the WordPress beta documentation says to use bleeding edge via WordPress Beta Tester plugin (which pulls the release from the trunk). So I was somewhat confused as to which instruction was accurate. So I assume the WordPress Beta Tester plugin should be left in "Point release nightlies" mode.

To be honest, I'm not totally sure of the current state of the WordPress Beta Tester plugin right now. Might be worth popping into `#core` on Slack to ask.

> Are we leaping past 5.0 and going right to 5.1?

Nope, we're shipping 5.0.

> So I'm just finding the process a bit muddled w.r.t what GB is in the core vs. what gb is in the plug-in and whether I need to pull the nightly GB plug-in release to match up with the nightly core 5.1 release and whether I still need the GB plug-in installed to test my theme on core v5.x.

You can install the WordPress 5.0-betas to test against what will be released in 5.0. For theme development, this should be sufficient. Alternatively, if you want to test against the bleeding edge, you can install the [Gutenberg nightly build](https://danielbachhuber.com/2018/10/02/gutenberg-nightly-build/) (or any of the stable Gutenberg releases).

**Comment by timhibberd** [comment]
Much appreciated @danielbachhuber. I got it sorted with your adept guidance. I am the custodian of the abandoned MySiteMyWay theme suite (forked as BackStop Themes in Gitlab.com). The process of modernising those themes is a gradual process. I'm Gutenising them at present. It turned out, on detailed re-examination that the original theme designers created their own html body statement in isolation and did not append the default WP body classes. Once I knew the core was definitely adding them it was simple to sort out. Thanks again for your help. Whenever I see your comments in WordPress they are always spot on. Thanks for being there when people need you...your WP knowledge & advice is invaluable :-)

**Comment by danielbachhuber** [comment]
@timhibberd You're welcome :)
