### PR TITLE
Site Hub: Fixed navigation redirect on mobile devices for classic themes

### LINKED ISSUE #66844: On Patterns screen for classic theme, site icon does not return to admin dashboard on mobile
### Description

With a classic theme active, clicking the site icon to return to the admin dashboard yields a different result between desktop and mobile.

On desktop, the site icon returns to the dashboard. On mobile, however, it opens the site editor sidebar menu, revealing other screens that are not compatible with non-block themes. For instance, a blank page results when attempting to access Styles. The issue appears to have been introduced in 6.6 when the Patterns link was updated to resolve in the site editor.

### What I expected
The expected result is that on mobile screens (728px or narrower) the site icon should return to the admin dashboard, like on desktop.

Props @kebbet for raising this in the `#core` channel.

### Step-by-step reproduction instructions

1. Open WordPress 6.6+ on a mobile device, _OR_ on desktop, shrink the viewport to 728px width or less.
2. Activate a classic theme, such as `twentytwenty`.
3. Navigate to _Appearance > Patterns_.
4. Inspect the site icon (typically the WordPress "W") in the upper left, and observe that it is the "Go to Site Editor" button (via `aria-label` attribute).
5. Click the site icon and observe that the left site editor panel opens.

Here are some test links that activate classic theme `twentytwenty` and navigate to the Patterns screen directly:
- [Playground link to test Core](https://playground.wordpress.net/?theme=twentytwenty&url=%2Fwp-admin%2Fsite-editor.php%3Fpath%3D%2Fpatterns)
- [Playground link including Gutenberg latest](https://playground.wordpress.net/?plugin=gutenberg&theme=twentytwenty&url=%2Fwp-admin%2Fsite-editor.php%3Fpath%3D%2Fpatterns)

### Screenshots, screen recording, code snippet

Animated GIF demonstrating clicking the site icon when viewing the Patterns screen with Twenty Twenty activated:
Image

### Environment info

- Playground
- Browser: Safari 17.6, Google Chrome 130.0.6723.92
- Theme: `twentytwenty` and `twentyten`
- Plugin: w/ and w/o `gutenberg`

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [x] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by yogeshbhutkar**
Resolves: #66844 

## What?
The PR addresses a UI bug that doesn't let the users get redirected to the dashboard from mobile devices on classic themes.

## Why?

1. The user would otherwise need to double-click on the site logo from mobile devices to navigate to the dashboard page.
2. The PR retains the functionality to open the Design panel on the new theme and retains the functionality to navigate to the dashboard from mobile devices in classic themes.

## How?

I've used the dashboard link and a condition to determine if the block theme is activated or not and based on that am rendering onClick and href attributes of the button which can then redirect the user to the Dashboard if using the classic theme or can open the Design panel when using the Block Theme.

## Testing Instructions
1. Open WordPress 6.6+ on a mobile device, OR on desktop, shrink the viewport to 728px width or less.
2. Activate a classic theme, such as twentytwenty.
3. Navigate to Appearance > Patterns.
3. Inspect the site icon (typically the WordPress "W") in the upper left, and observe that it is the "Go to Site Editor" button (via aria-label attribute).
4. Click the site icon and observe that the left site editor panel opens.

https://github.com/user-attachments/assets/b0138d47-518c-49d6-ac03-e57b2351e679

### CODE REVIEW

File: packages/edit-site/src/components/site-hub/index.js [hunk 1]
```diff
@@ -121,17 +121,27 @@ export const SiteHubMobile = memo(
...
+				const { getSettings } = unlock( select( editSiteStore ) );
+
+				const { getEntityRecord, getCurrentTheme } =
+					select( coreStore );
+				const _site = getEntityRecord( 'root', 'site' );
+				return {
+					dashboardLink:
+						getSettings().__experimentalDashboardLink ||
+						'index.php',
+					isBlockTheme: getCurrentTheme()?.is_block_theme ?? false,
```
Comment (t-hamano) [inline packages/edit-site/src/components/site-hub/index.js]:
```suggestion
					isBlockTheme: getCurrentTheme()?.is_block_theme,
```

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR! I think this PR is working fine.

File: packages/edit-site/src/components/site-hub/index.js (hunk 1 above)
Comment (yogeshbhutkar) [reply packages/edit-site/src/components/site-hub/index.js]: @t-hamano, I've added a patch with your suggestions to the latest commit. Thanks for your review.

**Review by t-hamano — APPROVED** [review]
LGTM! Thanks for the fix 👍
