### PR TITLE
Fix create menu after menu switch

### LINKED ISSUE #59604: NavigationMenuSelector: Can't create new menu after switching to another menu
### Description

Splitting this out from https://github.com/WordPress/gutenberg/pull/59440

As noted in https://github.com/WordPress/gutenberg/pull/59440 I'm not sure some state propertis used by the `NavigationMenuSelector` component work as expected. 

Specifically, `isCreatingMenu` is always `true` after switching to another, existing, menu. This triggers at least two bugs:
- After switching to another menu, it is not possible to create a new menu as the 'Create new menu' button is disabled based on `isCreatingMenu`. [See the code here](https://github.com/WordPress/gutenberg/blob/e89fceffab765902e0162a1e3359d88501e72005/packages/block-library/src/navigation/edit/navigation-menu-selector.js#L179-L188).
- The 'loading' indicator when creating a new menu doesn't work correctly: it always stays to 'Loading'. While this will be mitigated in https://github.com/WordPress/gutenberg/pull/59440 I suspecd that also `isResolvingNavigationMenus` and `hasResolvedNavigationMenus` don't work as expected, at least in terms of _timing_.

Cc @getdave 🙏🏽 

### Step-by-step reproduction instructions

- Make sure you have at least two menus.
- Go to the Site editor, edit mode.
- Select a Navigation, assuming it already contains a menu.
- In the Settings panel, click the ellipsis button after the heading 'Menu' to open the actions dropdown menu.
- Observe the 'Create new menu' button at the bottom of the dropdown menu is enabled. Screenshot:

Screenshot 2024-03-05 at 16 26 09

- Switch to another existing menu.
- Reopen the dropdown menu.
- Observe the 'Create new menu' button is now disabled. At this point, it's not possible to create a new menu. Screenshot:

Screenshot 2024-03-05 at 16 26 22

- In the settings panel, click the 'Settings' tab, the one with the gear icon.
- Then click the List view tab, this way the `NavigationMenuSelector` component re-renders.
- Open the dropdown menu and observe the 'Create new menu' button is now enabled again.
- Click 'Create new menu'.
- Adger the new menu is created, hover the dropdown ellipsis toggle button to reveal its tooltip.
- Observe the tooltip text hangs on 'Loading...' forever. Note: this will be changed in https://github.com/WordPress/gutenberg/pull/59440

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by draganescu**
## What?

Closes #59604 - create menu is available as an option after menu switching.

## Why?

Bug fix.

## How?

Removes a seemingly useless? call to setting a state about creating a menu (`setIsCreatingMenu`) which makes no sense in the context of switching a menu.

## Testing Instructions

1. Have two menus
2. Go to the site editor
3. In a template add a navigation block
4. Open block settings
5. Above the navigation tree click the dot menu in the top right
6. Switch to another menu
7. Open the he dot menu in the top right again
8. Notice "Create new menu" option at the bottom is enabled and works

### Testing Instructions for Keyboard

N/A

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/107534/c8aa4142-08d9-4818-8027-df7e0e51f1d2

### CODE REVIEW

**Review by scruffian — DISMISSED** [review]
Makes perfect sense and fixes the issue.

**Comment by getdave** [comment]
@scruffian @afercia @draganescu As this bug was uncovered during the RC phase do you feel that it should be included in the WP 6.5? If so why?

Noting that if required, we will need to present a rationale to the release team to clear this to land. As a member of that team I would prefer not to cast my opinion without first receiving your feedback. Much appreciated.

**Comment by draganescu** [comment]
100% it should be included in PW 6.5 because it's a severe bug (unable to access the create functionality) of a block central to developing a website which is what WP does. It also is a bug that I think was there for at least one release.

**Comment by draganescu** [comment]
In c2c53d1523e40de7f759e5d8198ce19e83c1c155 I've updated the approach to:

- return a promise from the event handlers that alter the ref of the nav menu
- renamed the state to what it really is
- used the resolver to properly update the state.

File: packages/block-library/src/navigation/edit/navigation-menu-selector.js [hunk 1]
```diff
@@ -177,11 +193,16 @@ function NavigationMenuSelector( {
...
+									isUpdatingMenuRef ||
+									! hasResolvedNavigationMenus
+								}
 								onClick={ () => {
-									onClose();
-									onCreateNew();
-									setIsCreatingMenu( true );
+									setIsUpdatingMenuRef( true );
+									onCreateNew().then( () => {
+										setIsUpdatingMenuRef( false );
```
Comment (jeryj) [inline packages/block-library/src/navigation/edit/navigation-menu-selector.js]: Removing this line allows the 'should handle disabled state of the create menu button during the creation process' test to pass. I think it's because the promise onCreateNew is resolving to `false` before the unit test can check for the disabled state.

I believe [this is the line in the unit test](https://github.com/WordPress/gutenberg/pull/59630/files?diff=split&w=1#diff-5acf9be3bfd5e32ba550339fe797b11880fdb50271e88810c2e879ded5f9cddbR278-R282) that both sets the button to be disabled and then resolves to no longer be disabled, so the unit test doesn't even "see" the state of it being disabled.

File: packages/block-library/src/navigation/edit/index.js [hunk 2]
```diff
@@ -342,20 +345,28 @@ function Navigation( {
...
-			classicMenu.id,
-			classicMenu.name,
-			'draft'
-		);
-		if ( navMenu ) {
-			handleUpdateMenu( navMenu.id, {
-				focusNavigationBlock: true,
-			} );
-		}
+		return new Promise( async ( resolve ) => {
```
Comment (getdave) [inline packages/block-library/src/navigation/edit/index.js]: Async functions _always_ return a `Promise` so this isn't required.

File: packages/block-library/src/navigation/edit/index.js [hunk 3]
```diff
@@ -154,7 +154,10 @@ function Navigation( {
 	} = useCreateNavigationMenu( clientId );
 
 	const createUntitledEmptyNavigationMenu = () => {
-		createNavigationMenu( '' );
+		return new Promise( async ( resolve ) => {
+			await createNavigationMenu( '' );
+			resolve();
+		} );
```
Comment (getdave) [inline packages/block-library/src/navigation/edit/index.js]: Async functions will always return a `Promise` so you can remove the wrapper and just mark the function as async.

File: packages/block-library/src/navigation/edit/index.js [hunk 4]
```diff
@@ -342,20 +345,28 @@ function Navigation( {
...
 	};
 
 	const onSelectNavigationMenu = ( menuId ) => {
-		handleUpdateMenu( menuId );
+		return new Promise( ( resolve ) => {
+			handleUpdateMenu( menuId, {
+				focusNavigationBlock: true,
+			} );
+			resolve();
+		} );
```
Comment (getdave) [inline packages/block-library/src/navigation/edit/index.js]: Why are we using a `Promise` here when there are no async actions occuring?

Comment (getdave) [reply packages/block-library/src/navigation/edit/index.js]: `handleUpdateMenu` is sync right?

Comment (draganescu) [reply packages/block-library/src/navigation/edit/index.js]: it's not needed indeed, it just liked the exaggerated consistency 😂

**Comment by draganescu** [comment]
I have updated the `NavigationMenuSelector` to NOT disable the menu items when changing the menu. It is a state change in what appears to be a sync operation, so disabling and enabling the UI happens all in the click handler via a local update. If by some magic the same thing is repeated it's just gonna change to the last clicked one.

I've updated the tests accordingly to take into account that the disabled state depends on `hasResolvedNavigationMenus`. 

The more I spend time here the more useless `isUpdatingMenuRef` as a state feels, but as a bug fix this looks ok.

File: packages/block-library/src/navigation/edit/index.js [hunk 5]
```diff
@@ -355,7 +355,9 @@ function Navigation( {
 	};
 
 	const onSelectNavigationMenu = ( menuId ) => {
-		handleUpdateMenu( menuId );
+		handleUpdateMenu( menuId, {
+			focusNavigationBlock: true,
+		} );
```
Comment (getdave) [inline packages/block-library/src/navigation/edit/index.js]: When testing I found that - as per the code - this focuses the Nav block in the canvas when switching menus.

I wanted to question this, because surely if you are within the list view and you switch menus you'd expect focus to the remain on the menu switching UI? Or at the very least within the editable List View in the block inspector controls?

This change also _appears_ to be outside the scope of this PR. Maybe I missed something but it feels like we should tackle this aspect separately.

**Review by getdave — COMMENTED** [review]
Thanks for this PR and working on a fix to this bug.

I see the original bug is resolved with the `Create menu` option enabled even when you switch menus.

However, if I click `Create new menu` I would expect the options to switch my menu to be disabled during that process's resolution. Currently they are not for both block and classic menus you might have.

File: packages/block-library/src/navigation/edit/test/navigation-menu-selector.js [hunk 6]
```diff
@@ -271,6 +271,16 @@ describe( 'NavigationMenuSelector', () => {
 					} )
 				);
 
+				useNavigationMenu.mockReturnValue( {
+					navigationMenus: [],
+					hasResolvedNavigationMenus: false,
+					isResolvingNavigationMenus: true,
+					canUserCreateNavigationMenu: true,
+					canSwitchNavigationMenu: true,
+				} );
```
Comment (getdave) [inline packages/block-library/src/navigation/edit/test/navigation-menu-selector.js:283]: Nit: I know this is not your fault, but these tests would be a lot easier to read if there were comments above these mocks explaining the state they create. For example: "Set menus to resolving"

File: packages/block-library/src/navigation/edit/index.js (hunk 5 above)
Comment (draganescu) [reply packages/block-library/src/navigation/edit/index.js]: You're right that it's outside the scope of the PR but I also think it's inconsistent that we focus on the canvas when we create and on the inspector when we switch. I think in both cases we should probably not move focus, it should be returned tot he toggle of the dropdown. I'll remove this change from here.

**Review by getdave — COMMENTED** [review]
The UI doesn't seem blocked to me when creating a menu. 

If I switch to slow network this becomes very obvious

https://github.com/WordPress/gutenberg/assets/444434/0a72bdf1-892c-4245-ada1-8c1438845b3f

**Review by getdave — APPROVED** [review]
Tested and it is now working correctly. I couldn't break it no matter what I triend with slow network or otherwise.

Thanks for your persistence with this problem 👍

File: packages/block-library/src/navigation/edit/navigation-menu-selector.js [hunk 7]
```diff
@@ -111,17 +121,17 @@ function NavigationMenuSelector( {
...
 	}, [
 		hasResolvedNavigationMenus,
 		createNavigationMenuIsSuccess,
 		canUserCreateNavigationMenu,
 		createNavigationMenuIsError,
-		isCreatingMenu,
+		isUpdatingMenuRef,
 		menuUnavailable,
 		noBlockMenus,
 		noMenuSelected,
```
Comment (getdave) [inline packages/block-library/src/navigation/edit/navigation-menu-selector.js:137]: We should be able to remove all the unused deps from this effect. 

I propose we do this in a _followup_.

**Comment by getdave** [comment]
A reminder of [the full rationale behind why this PR should be included in WP 6.5 during the RC period](https://github.com/WordPress/gutenberg/pull/59630#issuecomment-1980869737).

**Comment by getdave** [comment]
I just manually cherry-picked this PR to the pick/wp-65-rc-2 branch to get it included in the next release

https://github.com/WordPress/gutenberg/pull/59756

**Comment by afercia** [comment]
While this PR fixes the disabled state of the 'Create new menu' button, it introduces a regression. There is now a focus loss when creating a new menu because the whole dropdown menu stays open but all menu items gets 'disabled', including the menu item that had keyboard focus.

It is important to point out, once again, a very important principle:

> [!IMPORTANT]
> Never, ever, disable controls dynamically while they have focus.

I'd appreciate that this kind of changes are _tested with keyboard_ as clearly this wasn't the case in this PR. Thanks.

I will create a separate issue, and this needs to be addressed soon as it's a regression in RC.

**Comment by draganescu** [comment]
@afercia how was this a regression? Isn't it more like ... the bug being fixed unearthed the existing problem?

**Comment by getdave** [comment]
> and this needs to be addressed soon as it's a regression in RC.

Agreed. Are you able to tackle this one? 

The next RC is RC3 on 19th March.
