### PR TITLE
Fix Parent Check Condition in `buildTermsTree`

### LINKED ISSUE #65704: hierarchical term selector for flat taxonomies not working properly - problem with utils/terms.js
### Description

If following the example in [gutenberg/packages/editor/src/components/post-taxonomies/README.md](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/post-taxonomies/README.md) to use the hierarchical term selector with a non-hierarchical taxonomy, non-hierarchical taxonomy does not render terms at all. 

Problem lies in [gutenberg/packages/editor/src/utils/terms.js](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/utils/terms.js). termsByParent is somehow not an array, but an object with one 'undefined' key. 

So the return statement:
`return fillWithChildren( termsByParent[ '0' ] || [] );`
in function buildTermsTree() always returns empty array.

If the return statement is replaced with:
`return fillWithChildren( Object.values(termsByParent)[0] || [] );`
the terms function properly again.

It would be also nice if HierarchicalTermsSelector automatically removed rendering of dropdown for parent term if using non-hierarchical taxonomy. Will post a comment to the issue, if I am able to propose a solution.

### Step-by-step reproduction instructions

1. add code to theme as per instructions in [gutenberg/packages/editor/src/components/post-taxonomies/README.md](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/post-taxonomies/README.md)
2. open any post in gutenberg editor
3. observe that taxonomies with flat terms do not render any terms

### Screenshots, screen recording, code snippet

_No response_

### Environment info

Wordpress version: 6.6.2
Theme: custom theme in development with no other changes to the gutenberg editor so far

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by torounit**
## What?

The buildTermsTree function skips the process of converting terms into a tree structure if all terms in the passed array have no parent. Previously, this condition was determined by checking if `parent === null`, but it failed to evaluate correctly when parent was undefined. We will modify it to handle both null and undefined correctly.

## Why?

fix: #65704.

## How?

Check `parent === undefiend`

## Testing Instructions

Try #65704.

### CODE REVIEW

File: packages/editor/src/utils/terms.js [hunk 1]
```diff
@@ -14,14 +14,16 @@ export function buildTermsTree( flatTerms ) {
 	const flatTermsWithParentAndChildren = flatTerms.map( ( term ) => {
 		return {
 			children: [],
-			parent: null,
+			parent: undefined,
```
Comment (torounit) [inline packages/editor/src/utils/terms.js:17]: Terms fetched by getEntityRecords use `parent: undefined`, so we match them.

File: packages/editor/src/utils/test/terms.js [hunk 2]
```diff
@@ -4,14 +4,14 @@
 import { buildTermsTree } from '../terms';
 
 describe( 'buildTermsTree()', () => {
-	it( 'Should return same array as input with null parent and empty children added if parent is never specified.', () => {
+	it( 'Should return same array as input with undefined parent and empty children added if parent is never specified.', () => {
```
Comment (Mamaduka) [inline packages/editor/src/utils/test/terms.js:7]: Should we test both cases of `null` and `undefined`?

**Review by Mamaduka — APPROVED** [review]
Thank you, @torounit!

Left minor comment, but fix looks good to me ✅

File: packages/editor/src/utils/terms.js [hunk 3]
```diff
@@ -14,14 +14,16 @@ export function buildTermsTree( flatTerms ) {
...
 			...term,
 		};
 	} );
 
 	// All terms should have a `parent` because we're about to index them by it.
 	if (
-		flatTermsWithParentAndChildren.some( ( { parent } ) => parent === null )
+		flatTermsWithParentAndChildren.some(
+			( { parent } ) => parent === undefined || parent === null
```
Comment (Mamaduka) [inline packages/editor/src/utils/terms.js]: In which case will the `parent: null` be?

Comment (torounit) [reply packages/editor/src/utils/terms.js]: @Mamaduka I checked both HierarchicalTermSelector and PageAttributesParent and parent is undefined if parent does not exist. can we remove `parent === null` ?

Comment (Mamaduka) [reply packages/editor/src/utils/terms.js]: > can we remove parent === null?

If it's never `null` then I guess we can remove it.

Comment (Mamaduka) [reply packages/editor/src/utils/terms.js]: Thank you, @torounit!
