### PR TITLE
FocalPointPicker: Fix rendering and dragging experience

### LINKED ISSUE #25814: Focal point picker drag handle sets incorrect coordinates in macOS Safari
**Describe the bug**
When using macOS Safari and attempting to set a focal point for Cover Block media via the drag handle, it incorrectly sets the coordinates to (0, 0) regardless of where you drag your cursor.

**To reproduce**
1. Navigate to create a new post.
1. Add a Cover Block.
1. Set the media for the Cover Block.
1. Click the Cover Block to reveal the media settings in the right sidebar.
1. Click and drag within the "Focal point picker" media settings section.
1. Focal point coordinates are set to (0, 0) regardless of where you drag your cursor.

**Expected behavior**
The focal point is correctly updated as you drag. The "Left" and "Top" input fields display the correct X and Y coordinates to match the position of your drag. The Cover Block rendering updates accordingly to position the media relative to the focal point coordinates.

**Screenshots**
| Safari | Chrome |
| --- | --- |
| focal-point-picker-safari | focal-point-picker-chrome |

**Editor version (please complete the following information):**
- WordPress version: WordPress.com
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? n/a
- If the Gutenberg plugin is installed, which version is it? n/a

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Browser: Safari
 - Version: 14.0

**Additional context**
- This behavior does not occur while using macOS Chrome.

### PR DESCRIPTION
**Pull request by ItsJonQ**
## Description

This update improves the FocalPointPicker component to ensure that the focal point UI is visible during dragging.
The solution involved removing (an old) `.is-dragging` class that was attached to the focal point UI.
At some point, `.is-dragging` (globally) was forced to be `display: none !important`.

Also, `InputControl` drag update stability has been improved by removing the `pointer-event: none` disabling during drag.

Resolves https://github.com/WordPress/gutenberg/issues/25814

## Tasks

* [x] Fix render visibility of Focal Pointer UI when dragging
* [x] Fix interaction issues for Safari
* [x] Improve text-selection handling on dragging

## How has this been tested?

Locally in Gutenberg and Storybook

* `npm run dev`
* Add a cover blog
* Add an image background
* Adjust the position by dragging the focal point UI

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [n/a] My code has proper inline documentation. 
- [n/a] I've included developer documentation if appropriate. 
- [n/a] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/components/src/input-control/utils.js [hunk 1]
```diff
@@ -41,10 +41,10 @@ export function useDragCursor( isDragging, dragDirection ) {
 	useEffect( () => {
 		if ( isDragging ) {
 			document.documentElement.style.cursor = dragCursor;
-			document.documentElement.style.pointerEvents = 'none';
+			document.documentElement.style.userSelect = 'none';
```
Comment (youknowriad) [inline packages/components/src/input-control/utils.js:44]: Not sure how important is this property or if it's just a progressive enhancement but for IE11 and safari, I might need a prefix.

**Comment by ItsJonQ** [comment]
Need to fix the interaction weirdness for Safari (https://github.com/WordPress/gutenberg/issues/25814#issuecomment-732499531)

---

### Replicating in Safari

* Begin with a Cover focal pointer value that **is not** `0,0`
* Drag the focal pointer

---

Still debugging, but this note may help others who are curious.

At the start of the drag event, the `bound` values register as `0` in Safari:

Screen Shot 2021-01-11 at 8 20 09 AM

Alternatively, in Chrome, the `bounds` values are correct to start:

Screen Shot 2021-01-11 at 8 22 50 AM

File: packages/components/src/input-control/utils.js (hunk 1 above)
Comment (ItsJonQ) [reply packages/components/src/input-control/utils.js:44]: Just checked. It doesn't look like it does anything for this particular interaction.

I thought that by dragging outside the element, we would experience text selection issues (or undesired cursor interaction issues). It doesn't look like that's the case.

I'll remove it :).

**Review by youknowriad — APPROVED** [review]
Looks great in my testing :)

**Comment by ItsJonQ** [comment]
Wonderful! Thank you @youknowriad 🙏

**Comment by ItsJonQ** [comment]
It looks like we're having random E2E failures in this PR. (First E2E Admin 3, then E2E Admin 2)
I don't think they're related to my changes, as I'm seeing E2E failures on the commits on master (🙈)

In that case, I'm going to move forward with the merge.
