### PR TITLE
Better inline paste

### LINKED ISSUE #2459: Copying image from Classic Text and pasting in Paragraph doesn't create new block
GIF:

pasteimage

Steps to reproduce: copy an image from the current editor, or a classic text block, then paste in a paragraph block.

Expected result: it creates an image block. 

Actual result: it inserts the image in the paragraph block.

### PR DESCRIPTION
**Pull request by ellatrix**
Fixes #2459, and inline Editable paste.

* The pasteHandler now really handles all paste. Before, the Editable component handled block paste and inline paste.
* We pass `{ inline: true }` if the editable expects inline content. If so, we strip everything that is not text or inline tags.
* Images are now seen as non inline content, so a block will be created.

To test:

* Copy an image from the old editor (click, copy), then paste it in a paragraph. An image block should be created.
* Copy some content that is not all inline. This can be some blocks, or some content from a site. Paste it in a caption or another single line Editable. The content should be pasted in the caption, but only as text and formatting.

### CODE REVIEW

**Comment by iseulde** [comment]
I feel like it might be better to have one loop over all nodes and then apply filters on each node (except for normalising blocks). I'll explore that in a separate PR.

File: utils/index.js [hunk 1]
```diff
@@ -1,9 +1,7 @@
 import * as keycodes from './keycodes';
-import * as nodetypes from './nodetypes';
```
Comment (georgeh) [inline utils/index.js]: Good! I like the imports from `window.Node` better. One less piece of duplication

**Review by georgeh — APPROVED** [review]
:shipit:
