### PR TITLE
Drag & Drop: Fix unexpected row/gallery creation logic

### LINKED ISSUE #64227: In-between inserter: Unexpected vertical inserter display
### Description

In #56186, a vertical inserter was introduced to create Rows and Galleries. However, this causes unintended behavior in some scenarios.

For example, we should consider the following scenarios:

- Group block is not registered
- Row variation is not registered
- Gallery block is not registered
- Cannot be wrapped in a Row block

### Step-by-step reproduction instructions

From what I have seen, the scenarios that cause the problem are:

### Create galleries from Image blocks

If both the Gallery block and the Row variation are not enabled:

- Expected: The inserter should not be displayed
- Actual: ❌ The inserter is displayed and you will get a browser console error like this once the drop is complete:

```
Uncaught Error: Block type 'core/gallery' is not registered.`
```

https://github.com/user-attachments/assets/7637e666-560b-4411-94ac-3b35f8baf3c2

### Create Rows from selected blocks

If the Row variation is not enabled:

- Expected: The inserter should not be displayed
- Actual: ❌ The inserter is displayed and the Row block with `layout.type` as flex appears to be created correctly, but the block name remains Group.

https://github.com/user-attachments/assets/843a8ac1-d4a5-4358-9b73-866aa2cc28ca

### When a Row block cannot be created

For example, if the button orientation is vertical:

- Expected: Since we cannot create a Row block from the Button block (not the Buttons block), the inserter itself should not be displayed.
- Actual: ❌ The inserter appears. Buttons get duplicated and/or the browser freezes.

https://github.com/user-attachments/assets/781cc4b4-bd26-486c-8b57-e641e402286f

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #64227

## What?

This PR prevents the unintended appearance of the dropzone (vertical inserter) for creating rows or galleries in certain scenarios.

## Why?

We need to consider the following scenarios:

- Group block is not registered
- Row variation is not registered
- Gallery block is not registered
- Cannot be wrapped in a Row block

For example, if the Gallery block, Group block, and Row variation are not all registered, the dropzone itself should not be displayed.

## How?

Check in advance whether the Row block or the Gallery block can be created. If there are no creatable blocks, the dropzone itself will not be displayed.

## Testing Instructions

Test the following scenarios:

### Default

- Insert a Buttons block and orient it vertically.
- Drag the button to the side of the other button.
  - ❌ trunk: The dropzone appears. Blocks get duplicated or the browser freezes.
  - ✅ This PR: The dropzone should not be displayed.

### Row variation is not registered

```javascript
wp.blocks.unregisterBlockVariation( 'core/group', 'group-row' );
```

- Insert two Paragraph blocks.
- Drag the second Paragraph block to the side of the first Paragraph block.
  - ❌ trunk: The dropzone is displayed and the Row block with `layout.type` as `flex` appears to be created correctly, but the block name remains Group.
  - ✅ This PR: The dropzone should not be displayed.

### Group block is not registered

```javascript
wp.blocks.unregisterBlockType( 'core/group');
```
- Insert two Paragraph blocks.
- Drag the second Paragraph block to the side of the first Paragraph block.
  - ❌ trunk: The dropzone appears. Blocks get duplicated or the browser freezes.
  - ✅ This PR: The dropzone should not be displayed.

### Gallery block and Row variation are not registered

```javascript
wp.blocks.unregisterBlockType( 'core/gallery');
wp.blocks.unregisterBlockVariation( 'core/group', 'group-row' );
```

- Insert two Image blocks.
- Drag the second Image block to the side of the first Image block.
  - ❌ trunk: The dropzone is displayed and the Row block with `layout.type` as `flex` appears to be created correctly, but the block name remains Group.
  - ✅ This PR: The dropzone should not be displayed.

### Gallery block, Group block, and Row variations are not registered

```javascript
wp.blocks.unregisterBlockType( 'core/gallery');
wp.blocks.unregisterBlockType( 'core/group');
wp.blocks.unregisterBlockVariation( 'core/group', 'group-row' );
```

- Insert two Image blocks.
- Drag the second Image block to the side of the first Image block.
  - ❌ trunk: The inserter appears. Blocks get duplicated or the browser freezes.
  - ✅ This PR: The dropzone should not be displayed.

### CODE REVIEW

File: packages/block-editor/src/components/use-on-block-drop/index.js [hunk 1]
```diff
@@ -255,17 +254,11 @@ export default function useOnBlockDrop(
...
 			const clientIds = getBlockOrder( targetRootClientId );
 			const clientId = clientIds[ targetBlockIndex ];
-			const blocksClientIds = blocks.map( ( block ) => block.clientId );
-			const areGroupableBlocks = isGroupable( [
-				...blocksClientIds,
-				clientId,
-			] );
 			if ( operation === 'replace' ) {
 				replaceBlocks( clientId, blocks, undefined, initialPosition );
-			} else if ( operation === 'group' && areGroupableBlocks ) {
```
Comment (t-hamano) [inline packages/block-editor/src/components/use-on-block-drop/index.js:268]: At this point, it is guaranteed that at least one of the Row block or Gallery block can be created, so `areGroupableBlocks`  is not necessary.

File: packages/block-editor/src/components/use-block-drop-zone/index.js [hunk 2]
```diff
@@ -274,6 +274,27 @@ export function isDropTargetValid(
...
+/**
+ * Check if the Row or the Gallery can be created with the dragged
+ * blocks and the target block.
+ * @param {boolean} areAllImages
+ * @param {boolean} canInsertGalleryBlock
+ * @param {boolean} areGroupableBlocks
+ * @param {boolean} canInsertRow
+ * @return {boolean} Whether Row block or Gallery can be created.
+ */
+function canCreateRowOrGallery(
```
Comment (t-hamano) [inline packages/block-editor/src/components/use-block-drop-zone/index.js]: This process might not even need to be made into a function.

Comment (ramonjd) [reply packages/block-editor/src/components/use-block-drop-zone/index.js]: "Either or" I think. 

It doesn't abstract much and could be inline and just as neat. Unless it needs unit testing.

File: packages/block-editor/src/components/use-block-drop-zone/index.js [hunk 3]
```diff
@@ -385,21 +409,59 @@ export default function useBlockDropZone( {
...
-							parentBlockClientId,
-							parentBlockOrientation: parentBlockClientId
-								? getBlockListSettings( parentBlockClientId )
-										?.orientation
-								: undefined,
-							rootBlockIndex: getBlockIndex( targetRootClientId ),
-						}
+					dropTargetPosition;
+
+				// Checks if it is creatable either a Row variation or a Gallery block from
```
Comment (ramonjd) [inline packages/block-editor/src/components/use-block-drop-zone/index.js]: Just checking, so this condition checks if a Row (Group) block or a Gallery block can be created after drop?

**Review by ramonjd — COMMENTED** [review]
I did a smoke test on trunk and this PR and things are working as you describe. Thanks for the PR!

In trunk, adding a button block to a vertical row of button completely smashed by browser 😅 

I'm not an expert in this area, so it might be good to see if @andrewserong or @kevin940726 have time to run their eyes over it.

File: packages/block-editor/src/components/use-block-drop-zone/index.js (hunk 3 above)
Comment (t-hamano) [reply packages/block-editor/src/components/use-block-drop-zone/index.js]: No, it checks if it can be created _before_ the drop. This prevents unintended inserters from appearing.

File: packages/block-editor/src/components/use-block-drop-zone/index.js (hunk 2 above)
Comment (andrewserong) [reply packages/block-editor/src/components/use-block-drop-zone/index.js]: Same. Since it's only used in one place, I'd lean slightly toward inlining unless it needs unit testing.

File: packages/block-editor/src/components/use-on-block-drop/index.js (hunk 1 above)
Comment (andrewserong) [reply packages/block-editor/src/components/use-on-block-drop/index.js:268]: Just double-checking, is that because this check is now happening in the `throttle`'d function instead, prior to displaying the drop indicator and setting the drop target?

It looks like that other code also calls `isGroupable`, too 👍. From memory the other thing we needed to check was that the hovered over block can be removed, so as long as the check is happening _somewhere_ that sounds good to me!

**Review by andrewserong — APPROVED** [review]
Nice work @t-hamano, this is testing great for me and I could reproduce each of the issues in `trunk` and those cases behaved as expected with this PR applied 👍

✅ Dragging a Button to the side of the vertical Buttons block no longer shows the dropzone
✅ The dropzone is not displayed when dragging a paragraph and the Row variation is not registered
✅ The dropzone is not displayed when dragging a paragraph and the Group block is not registered
✅ The dropzone is not displayed when dragging an image onto another image and the Gallery block and Row variations are not registered
✅ The dropzone is not displayed when dragging an image onto another image and the Gallery block, Group block and Row variations are not registered

Smoke tested dragging and dropping in the post and site editors, and otherwise all appears to be working well for me.

LGTM! 🚀

File: packages/block-editor/src/components/use-block-drop-zone/index.js (hunk 2 above)
Comment (t-hamano) [reply packages/block-editor/src/components/use-block-drop-zone/index.js]: I removed the function and inlined it [here](https://github.com/WordPress/gutenberg/pull/64241/files#diff-43d4fac82b9f9255055e90135a8dfe36f59a2c9de24b731dae8b9d5fcd3581b1R433-R449) 👍

File: packages/block-editor/src/components/use-on-block-drop/index.js (hunk 1 above)
Comment (t-hamano) [reply packages/block-editor/src/components/use-on-block-drop/index.js:268]: > Just double-checking, is that because this check is now happening in the "throttle"'d function instead, prior to displaying the drop indicator and setting the drop target?

Yes. If the `areGroupableBlocks` check is present here, the gallery block will not be created when the following conditions are met:

- The Group block is unregistered
- he dragged blocks and the target block are all images

Comment (andrewserong) [reply packages/block-editor/src/components/use-on-block-drop/index.js:268]: Thanks for clarifying!
