### PR TITLE
[Widgets Screen] Fix WP Admin Bar Widgets screen link

### LINKED ISSUE #25828: The widgets link in admin top bar is wrong
### To reproduce:

- have Gutenberg plugin installed and updated to 9.1
- be sure you're logged in
- visit the website's front-end
- on the black top bar hover over the website's name
- in the menu click on Widgets
- notice you are in the old editor

### Expected:

- when enabled the widgets editor should be linked from all the places we refer to it

### Screenshots:

Screenshot 2020-10-05 at 14 49 09

### PR DESCRIPTION
**Pull request by kevin940726**
## Description

Fix #25828.

Fix the link of the Widgets Screen in the admin bar.

## How has this been tested?

1. Go to the frontend (http://localhost:8888)
2. Hover over the site's name in the top admin bar
3. Click the "Widgets" item
4. Observe that we're being redirected to the Widgets screen block editor

## Screenshots 
image

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: gutenberg.php [hunk 1]
```diff
@@ -105,6 +105,23 @@ function gutenberg_menu() {
...
+ * Modify WP admin bar.
+ *
+ * @param WP_Admin_Bar $wp_admin_bar Core class used to implement the Toolbar API.
+ */
+function modify_admin_bar( $wp_admin_bar ) {
+	if ( gutenberg_use_widgets_block_editor() ) {
+		$wp_admin_bar->add_menu(
+			array(
+				'id'   => 'widgets',
+				'href' => admin_url( 'themes.php?page=gutenberg-widgets' ),
```
Comment (adamziel) [inline gutenberg.php:118]: This link is in two places now, maybe let's use a constant or a variable instead of hardcoding it? It would be easier to change if needed and we would also reduce the risk of making a typo.

Comment (kevin940726) [reply gutenberg.php:118]: Sure, I'm not familiar with PHP though, any suggestion on where to put this constant?

Comment (adamziel) [reply gutenberg.php:118]: I think at the top of gutenberg.php should be fine

Comment (kevin940726) [reply gutenberg.php]: Is 265ddc1 what you meant?

Comment (noisysocks) [reply gutenberg.php]: I think I disagree with @adamziel 😇

The problem is that, because WordPress doesn't use namespaces, every top level variable, function, and constant we add becomes, for better or worse, a part of the public API that we have to maintain backwards compatibility for.

I don't think the repetition is severe enough in this case to warrant that kind of a commitment.

---

Having said that, if we still want to use a constant, let's avoid `define()` which is, in WordPress, used for configuration constants. 

Instead let's use the `const` keyword which should support arbitrary expressions as of PHP 5.6.

5.6 is the minimum PHP version that WordPress supports.

We can also mark it `@access private` so that we're not exposing this as part of our public API.

```php
/**
 * @access priavte
 */
const GUTENBERG_WIDGETS_LINK = admin_url( 'themes.php?page=gutenberg-widgets' ) );
```

https://www.php.net/const

Comment (kevin940726) [reply gutenberg.php]: Wow TIL! `define` is just the very first result from my Google search 😆 

Do we want to go with `const` keyword and `@access private`? Or just inline it everywhere? I don't have a strong preference of this 🤔 .

Comment (kevin940726) [reply gutenberg.php]: > Like any other PHP static variable, static properties may only be initialized using a literal or constant before PHP 5.6; expressions are not allowed. In PHP 5.6 and later, the same rules apply as const expressions: some limited expressions are possible, provided they can be evaluated at compile time.

Hmmm, seems like we can't use `admin_url()` in `const` expressions.

Comment (noisysocks) [reply gutenberg.php]: I think just keep the duplication. It's very common 🙂

https://github.com/WordPress/wordpress-develop/search?q=admin_url

Comment (draganescu) [reply gutenberg.php]: @kevin940726 I tend to agree with @noisysocks and just use the admin_url call with the value in multiple places. It's cheaper than defining a constant which people will use for whatever reason. Plus it does not solve @adamziel 's main problem which is the hardcoding part. Unfortunately there is no place to bring that route from `'themes.php?page=gutenberg-widgets'` as it's a made up, more or less, route.

```
$wp_admin_bar->add_menu(
			array(
				'id'   => 'widgets',
				'href' => admin_url( 'themes.php?page=gutenberg-widgets' ),
...
```

This is better imo, no `define` no `const`.

Comment (kevin940726) [reply gutenberg.php:118]: Done! Reverted back to the old commit.

**Review by talldan — APPROVED** [review]
Looks good!
