### PR TITLE
Pasting: Dismiss pasted image if file:// schema detected

### LINKED ISSUE #42783: Pasting from Microsoft Word wrongly inserts screenshot image instead of content
### Description

The general issue was fixed in #38992. This issue covers an edge case not covered by that fix.

See original report in https://github.com/Automattic/wp-calypso/issues/61295#issuecomment-1197904958.

### Step-by-step reproduction instructions

In short:

* copying a document from **Microsoft Word**
* said document contains text and **exactly one image**
* pasting onto the block editor using **Google Chrome** or **Microsoft Edge**
* results in the pasting of a Word-generated snapshot of the copied document, which is unexpected
  * the expected result would be the insertion of blocks corresponding to the copied content

Gutenberg should ignore that attached snapshot.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/150562/181598162-e0e0b266-cfec-4102-a4d3-b7e32a8c15be.mp4

_Courtesy of @ahegyes_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by mcsf**
## What?

Fixes #42783

This isn't the fix that I would like, and I am not sure that it should be merged.

IMO, the underlying issue is that Google Chrome (and Chromium derivatives, including Microsoft Edge) decides to attach to the clipboard data the fallback snapshot provided by Microsoft Word. Other browsers ignore that data, only passing attachments of type `text/plain`, `text/html`, and sometimes `text/rtf`.

## Why?

Quoting the bug report from the parent issue:

In short:

* copying a document from **Microsoft Word**
* said document contains text and **exactly one image**
* pasting onto the block editor using **Google Chrome** or **Microsoft Edge**
* results in the pasting of a Word-generated snapshot of the copied document, which is unexpected
  * the expected result would be the insertion of blocks corresponding to the copied content

Gutenberg should ignore that attached snapshot.

## How?

This PR extends the `shouldDismissPastedFiles` predicate to detect cases where the image tag found in the pasted HTML payload has a source with schema `file://`. For example, `{ html: '<p>text</p>' }`. Notes:

* I wonder what kind of false positives this might catch, though.
* Ideally, looking at `clipboardData.files` would be enough and we wouldn't have to guess based on `clipboardData.getData( 'text/html' )`. However, I haven't spotted any (meta)data in there that we could use.

## Testing Instructions

See parent issue.

## Caveat

I'm confident that this PR fixes that particular edge case, but it makes assumptions that I don't like, potentially creating new classes of false positives.

There's always the possibility of filing an issue / asking around in the Chromium project, to determine whether we could consider this a browser bug.

### CODE REVIEW

File: packages/block-editor/src/utils/pasting.js [hunk 1]
```diff
@@ -70,7 +70,16 @@ export function shouldDismissPastedFiles( files, html /*, plainText */ ) {
 		// other elements found, like <figure>, but we assume that the user's
 		// intention is to paste the actual image file.
 		const IMAGE_TAG = /<\s*img\b/gi;
-		return html.match( IMAGE_TAG )?.length !== 1;
+		if ( html.match( IMAGE_TAG )?.length !== 1 ) return true;
```
Comment (ellatrix) [inline packages/block-editor/src/utils/pasting.js:73]: Why does this mean we should dismiss files? Should we check if the length is the same as the amount of files provided?

Comment (ellatrix) [reply packages/block-editor/src/utils/pasting.js:73]: Oh I see the `files?.length === 1` check now.

**Review by ellatrix — APPROVED** [review]
Seems fine to me. I guess we'll get reports if file dropping or pasting no longer works under some circumstances? It would be cool to collect various samples from different configurations and add them to the integration tests like we do for HTML paste.

File: packages/block-editor/src/utils/pasting.js (hunk 1 above)
Comment (mcsf) [reply packages/block-editor/src/utils/pasting.js:73]: Yeah, the two if-statements combined mean that we can only dismiss files when there is a mismatch between the number of files and the number of IMG tags in the HTML. The first if-statement just reduces the surface area of this helper, making it more conservative (e.g. there haven't been reports of unexpected file pastes when there is more than one file, so might as well only check with `files.length == 1`).

**Comment by mcsf** [comment]
> Seems fine to me. I guess we'll get reports if file dropping or pasting no longer works under some circumstances? It would be cool to collect various samples from different configurations and add them to the integration tests like we do for HTML paste.

Thanks for the vote of confidence! Yeah, let's keep a close eye on possible regressions, and if this comes back we should look into developing an integration suite.
