### PR TITLE
Make it possible to undo prefix transforms

### LINKED ISSUE #11358: Paragraph with starting 1. (e. g. for dates) not possible
**Describe the bug**
I tried to begin a new paragraph with the current date in German format (1. November 2018). What happens is that as soon as you write `1. ` it will switch the block to a list block with an ordered list and you can’t get it working to be a paragraph with a starting string like `1.`.

In the screenshot following below I also started by writing 01. November 2018 and tried to remove the leading zero (which is usually only used in programming contexts but not written by humans) but that didn’t work either.

**To Reproduce**
1. Add a new block.
2. Write `1.` following by a space.

**Expected behavior**
You should be able to press `CTRL + Z` or `⌘ + Z` to switch back to the paragraph mode while the `1. ` is still visible as regular text instead of being bound to an ordered list.

**Screenshots**
date-not-as-list

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Browser: Safari
 - Version: 12.0 (14606.1.36.1.9)

**Additional context**
- Gutenberg version 4.1.1

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #11358.

This PR adjusts the prefix transforms so that they only execute when they match text right at the caret, so that they are undoable, and makes the check faster checking if the previous character is a space and not using any regular expressions otherwise on the whole text. Also adds e2e tests for all prefix and enter transforms, and adds some documentation.

## How has this been tested?
Extra e2e tests have been added, but ensure e.g. list shortcuts like `1. ` still work and it's possible to undo them and have it so that the prefix can be at the start without it being transformed.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: packages/block-library/src/code/index.js [hunk 1]
```diff
@@ -39,8 +39,7 @@ export const settings = {
 	transforms: {
 		from: [
 			{
-				type: 'pattern',
-				trigger: 'enter',
+				type: 'enter',
```
Comment (ZebulanStanphill) [inline packages/block-library/src/code/index.js]: I think this is a typo?
```suggestion
				type: 'prefix',
```

Comment (iseulde) [reply packages/block-library/src/code/index.js]: No, it should be enter, it's a different transform.

**Review by youknowriad — COMMENTED** [review]
Seems like a good enhancement but I'd appreciate a second opinion as I'm not very familiar with this code.

**Comment by youknowriad** [comment]
Going to punt this for 4.4 as well. Tests are failing and this is just a way to divide work an ship.

**Comment by iseulde** [comment]
Yes, let’s merge the other undo PR first :)

File: packages/block-library/src/separator/index.js [hunk 2]
```diff
@@ -27,8 +27,7 @@ export const settings = {
 	transforms: {
 		from: [
 			{
-				type: 'pattern',
```
[the remark this answers is not in the document]
Comment (iseulde) [reply packages/block-library/src/separator/index.js]: I don't know. It was never official/documented.

File: test/e2e/specs/blocks/list.test.js [hunk 3]
```diff
@@ -9,6 +9,7 @@ import {
 	convertBlock,
 	pressWithModifier,
 	insertBlock,
+	META_KEY,
```
Comment (gziolo) [inline test/e2e/specs/blocks/list.test.js]: It needs to be rebased with the `master` branch.

With the latest refactoring, we are able to reuse logic from `@wordpress/keycodeds` package and express this using `primary` modifier:

```js
await pressWithModifier( 'primary`, 'z' );
```

**Comment by youknowriad** [comment]
I'm not certain I understand what's different between this PR and master in terms of behavior.

**Review by youknowriad — APPROVED** [review]
I noticed that this fixes some issues with focus jumps.

**Comment by iseulde** [comment]
> This is still very hard to do as if you add a space it's still transformed, I wonder if the undo should reset to the value with a space in it.

Haven't looked deeper, but probably some browsers, like Chrome, fail to visualise the trailing space. We might have to pad it with a non breaking space.
