### PR TITLE
Patterns: Fix issue with template in replace template screen

### LINKED ISSUE #56380: Pattern icon misuse in the swap template UI
Screenshot 2023-11-21 at 12 03 13

When editing a page in the site editor there's a template swapping modal accessed via the Inspector. Beneath each preview in the modal is the template name and an icon. I don't think any icon is required here.

### PR DESCRIPTION
**Pull request by glendaviesnz**
## What?
Fixes an issue with some templates displaying as synced patterns by mistake.

## Why?
In the switch templates screen on the page editor the templates show the synced pattern icon and highlighting which is confusing to users.

Fixes: #56380

## How?
This screen was identifying user patterns by the presence of `pattern.id` but it turns out that some templates also have an `id` field set. This PR adds a `type=user` field to user patterns to more reliably identify them.

## Testing Instructions

- In the site editor add or edit a page
- In the inspector panel click on the page template and choose the option to switch templates
- Check that that templates that display do not have a purple highlight when hovered and do not have the purple synced pattern icon
- In the inserter Patterns tab make sure that synced user patterns still display with purple icon and highlight and that the sou source filters for `User` still work as expected
- Check that duplicating a theme pattern and a user pattern in the site editor causes the new patterns to be assigned to the correct categories and that they have the correct sync status - theme patterns should be unsynced by default and user patterns should have the same sync status of pattern copied
- Check that the sync filters work as expected in the site editor Patterns section

## Screenshots or screencast 

Before:

https://github.com/WordPress/gutenberg/assets/3629020/b63de640-d462-477d-9bd6-24fd54e2c5e0

After:

https://github.com/WordPress/gutenberg/assets/3629020/5eeaa342-304b-44b3-8ffd-ebc784561e55

### CODE REVIEW

File: packages/block-editor/src/components/block-patterns-list/index.js [hunk 1]
```diff
@@ -71,7 +72,9 @@ function BlockPattern( {
 					} }
 				>
 					<WithToolTip
-						showTooltip={ showTooltip && ! pattern.id }
```
Comment (glendaviesnz) [inline packages/block-editor/src/components/block-patterns-list/index.js:74]: The existing bug really only needed the change to `pattern.type` in this file, but I thought it was better to update all the uses of the `pattern.id` check  now as the issue may appear in other areas if we start mixing patterns and templates more in the future.

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for the fix here @glendaviesnz 👍 

Looks like there are a couple of places in the code that still need to be switched to user `pattern.type`:

- [Duplicate pattern modal](https://github.com/WordPress/gutenberg/blob/trunk/packages/patterns/src/components/duplicate-pattern-modal.js#L17)
- [usePatterns hook](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/page-patterns/use-patterns.js#L162)

That was only after an quick search so I wouldn't take that list as exhaustive. There could be others.

**Comment by aaronrobertshaw** [comment]
🚀 Looks like you pushed those required updates while I was typing up the review. I'll give it another review in a moment.

**Comment by glendaviesnz** [comment]
> Looks like there are a couple of places in the code that still need to be switched to user pattern.type:

Snap, had decided to extend this out of the block-editor package  and had just pushed those fixes when I saw your comment 😄 

The other instances I could find seemed to be valid uses of `id` but let me know if you spot any more.

**Comment by glendaviesnz** [comment]
> 🚀 Looks like you pushed those required updates while I was typing up the review. I'll give it another review in a moment.

Thanks. The other instances I could find seemed to be valid uses of id but let me know if you spot any more. I have updated test instructions to cover the site editor changes.

**Review by aaronrobertshaw — COMMENTED** [review]
We're still missing one use of `pattern.id` to determine the difference between user & theme patterns:

- https://github.com/WordPress/gutenberg/blob/trunk/packages/patterns/src/components/duplicate-pattern-modal.js#L55

Other than that, I couldn't find any further uses of the id check approach.

**Comment by glendaviesnz** [comment]
Thanks, not sure how I missed that. I have fixed and updated test instructions to check duplicated pattern sync status to cover this.

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for the iterations here.

I couldn't find any further uses of `pattern.id` or `item.id` to check for theme patterns. After checking out the latest commits everything is testing as advertised for me.

✅ When switching templates, the options do not have a purple highlight or pattern icon
✅ The pattern inserter displays the correct icons and highlights for user patterns
✅ Pattern inserter's sync filters work as expected
✅ Site editor's pattern management page sync filters continue to work
✅ Duplicating user and theme patterns work correctly

**Comment by glendaviesnz** [comment]
For backporting there have been quite a few changes in the affected areas since 6.4, so it might be easier to just do a small patch for the specific bug rather than this wider refactor. Ping me when the next 6.4.* build it being done and I can co-ordinate this.

**Comment by mikachan** [comment]
> Ping me when the next 6.4.* build it being done and I can co-ordinate this.

👋 @glendaviesnz, 6.4.2 is currently being worked on. We have a PR here for the package updates: https://github.com/WordPress/wordpress-develop/pull/5698. It hasn't been committed yet, so this change could still be included.

I'm at a meetup next week so may be slow to reply, but it may be worth coordinating the patch for this change next week. cc. @karmatosed @SiobhyB @tellthemachines

**Comment by tellthemachines** [comment]
> may be worth coordinating the patch for this change next week

I'm happy to help where needed! Is there a date set for 6.4.2 yet?

**Comment by glendaviesnz** [comment]
@tellthemachines, @SiobhyB, @karmatosed  I think it is probably best to only include the bug fix changes in 6.4.2 rather than the full refactor in this PR, eg. just the changes in [this file](https://github.com/WordPress/gutenberg/pull/56407/files#diff-e24949b00cac037aacf5a314d639f0482c76a108cea05ebb9ad05b45345cf971). Is the best way to do that to open a PR with just that change against wp/6.4 branch?

**Comment by tellthemachines** [comment]
> Is the best way to do that to open a PR with just that change against wp/6.4 branch?

I'd say so, yes. Definitely let's avoid adding new features in a minor release 😅

**Comment by glendaviesnz** [comment]
Have added a minimal fix here https://github.com/WordPress/gutenberg/pull/56538
