### PR TITLE
Core Data: Shallow merge, not deep merge meta.

### LINKED ISSUE #17692: core/editor store having issues updating meta if register_meta single option is false (if its multiple)
**Describe the bug**
Previous Gutenberg versions could update multiple-value meta without problem. Since one of the latest versions there is an issue were meta is not saved correctly. Let me expalin with an example:

**To reproduce**
Register a multi-value meta:
````
add_action( 'init', __NAMESPACE__ . '\register_meta' );
function register_meta() {
	register_post_meta(
		'post',
		'my_meta_multiple',
		array(
			'show_in_rest' => true,
			'single' => false,
			'type' => 'string',
		)
	);
}
````
Inside a post using the console update the meta value:

````
wp.data.dispatch("core/editor").editPost({ meta: { my_meta_multiple: ['aaa','bbb','ccc'] } })
````
This will save correctly, the Update button of the Post will be enabled and if saved the value updates.

Now, if we try to update the value it acts in the following ways:

- `['aaa']` -> `['aaa','bbb','ccc']` removing the last/s already-saved elements will not receive any update. Changing the content and saving the post, will keep showing the previous value.
- `['bbb','ccc']` -> `['bbb','ccc','ccc']`
- `['xxx','yyy','zzz']` -> `['xxx','yyy','zzz']` I believe the issue is with removing elements

**Version**
- Gutenberg 6.6.0 RC1
- WordPress 5.2.3

### PR DESCRIPTION
**Pull request by epiqueras**
Fixes #17692

cc @youknowriad 

## Description

This PR changes Core Data so that it merges `mergedEdits` like `meta` shallowly instead of deeply.

Meta is set through a setter dispatching function and all of these take a new value and set the target to it. If we merged deeply, it would not line up with this behavior and cause issues like #17692 for non-primitive meta values.

## How has this been tested?

It was verified that non-primitive meta value edits work as expected and are not merged into the previous value.

## Types of Changes

*Bug Fix:* Fix an issue where non-primitive meta edits would get deeply merged into their previous value.

## Checklist:

- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/core-data/src/actions.js [hunk 1]
```diff
@@ -159,7 +159,7 @@ export function* editEntityRecord( kind, name, recordId, edits, options = {} ) {
 			const recordValue = record[ key ];
 			const editedRecordValue = editedRecord[ key ];
 			const value = mergedEdits[ key ] ?
-				merge( {}, editedRecordValue, edits[ key ] ) :
```
Comment (jorgefilipecosta) [inline packages/core-data/src/actions.js]: Was the behavior until now to always perform a deep merge? If yes should we provide a note in case someone was relying on the previous deep merge behavior?

Comment (epiqueras) [reply packages/core-data/src/actions.js]: I don't think anyone noticed, it's not very useful to rely on it and it breaks things. Think about what would happen if the value was an array for example.

We should still add a note just in case though. Where should we do that?

**Review by youknowriad — APPROVED** [review]
This makes sense, Maybe we can unit-test it somehow.

**Comment by leogermani** [comment]
Hi @epiqueras ,

I think I just stumbled upon this now.

I have a multi-valued metadata in which each value is an object.

When I try to `dispatch` to `wp.data.dispatch('core/editor').editPost( ... ` passing the new array of meta values, it seems that the core thinks there are no differences at all and ignores it.

The array has the same length as the original, and each object has the same keys, but I edited some attributes inside each object...

Is this the case described by this PR? Do you see a workaround or a better way to do this?

Thank you

**Comment by epiqueras** [comment]
>When I try to dispatch to wp.data.dispatch('core/editor').editPost( ... passing the new array of meta values

You mean new object right?

>The array has the same length as the original, and each object has the same keys, but I edited some attributes inside each object...

`currentMeta = { ...currentMeta, ...newMeta }` so even if you just mutated the values, things should work. Can you share some code?

**Comment by leogermani** [comment]
I mean array, because I'm sending all the values of this multi-valued metadata.

The code looks similar to this (using a React component):

```js
constructor() {
	// ...
	const metadata = wp.data.select('core/editor').getCurrentPost().meta;
	this.state = {
		// ...
		myMultiMeta: metadata.myMultiMeta 
		// this is an array of values. each value an object 
		// ( I know this because I use this.state.myMultiMeta.map() to render them )
	};
}

myModalSaveButtonClicked() {

	// state has been modified, the objects inside myMultiMeta have changed

	wp.data.dispatch('core/editor').editPost({meta: {
		myMultiMeta: this.state.myMultiMeta
	}});
}
```

Thanks again!

**Comment by epiqueras** [comment]
Right, that value is an array, but you are passing the new meta object.

If you mutate `metadata.myMultiMeta`, `core/data` can't infer that it's different from the previous value, because the previous value is the same one. Just update things immutably: https://redux.js.org/recipes/structuring-reducers/immutable-update-patterns/.

**Comment by leogermani** [comment]
Perfect @epiqueras , you got it. Thanks!

**Comment by epiqueras** [comment]
No problem :smile:
