### PR TITLE
Block Editor: Fix 'isBlockVisibleInTheInserter' selector helper performance

### LINKED ISSUE #68875: Slow site editor when navigation block has multiple submenu items
### Description

There is a performance issue in the site editor when editing a template that contains a navigation block with multiple submenu items.

The performance issue is practically unnoticeable by default, but it gets worse when activating plugins that register additional blocks (e.g. CoBlocks or WooCommerce).

Upon bisecting the latest changes, it seems that this is a regression introduced by https://github.com/WordPress/gutenberg/pull/67734.

### Step-by-step reproduction instructions

- Open the site editor
- Edit the navigation menu
- Add multiple submenu items:

Image

- Save the changes and test the following scenarios.

**Scenario 1 – A**

- Active plugins: Gutenberg
- The performance issue is practically unnoticeable here.

https://github.com/user-attachments/assets/1ef00d70-a510-4303-b064-e96a590765b2

**Scenario 1 - B**

- Active plugins: Gutenberg, CoBlocks
- The performance issue is way more noticeable now. When hovering a menu item, the submenu is not immediately visible. When selecting a block from the list view, it takes a long time for the block to be selected.

https://github.com/user-attachments/assets/6f51833d-569f-43b2-92aa-496bda7665c7

**Scenario 1 - C**

- Active plugins: Gutenberg, WooCommerce
- The site editor is almost unresponsive now. Hovering any block takes a long time to have some effect. Selecting a block from the list view takes an even longer time

https://github.com/user-attachments/assets/361fd5e6-0dcd-4da4-8e47-725a71d4d9ff

**Scenario 2 – A**

- Active plugins: Gutenberg with 8042535d851f7f01d0850a13e23823b7df2d345b reverted
- Since the issue was practically unnoticeable before, no difference can be observed

https://github.com/user-attachments/assets/0a6e8167-4445-4c25-b2b7-3523df3c9f74

**Scenario 2 - B**

- Active plugins: Gutenberg with 8042535d851f7f01d0850a13e23823b7df2d345b reverted, CoBlocks
- The performance issue is gone

https://github.com/user-attachments/assets/be7ab167-9aad-45cd-9e2b-c3ddc79637ee

**Scenario 3 - C**

- Active plugins: Gutenberg with 8042535d851f7f01d0850a13e23823b7df2d345b reverted, WooCommerce
- The performance issue is gone

https://github.com/user-attachments/assets/5af83b20-b6ee-4627-ace6-9cb85079b94f

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 6.7.1, Gutenberg 20.1.0, Twenty Twenty-Three
- Chrome
- Desktop with macOS Sequoia 15.2

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Resolves #68875.

Fixes recent performance regression in the Block Editor package.

## Why?
The `isBlockVisibleInTheInserter` function is often called even when the inserter isn't visible. The internal function `getBlockParentsByBlockName` is a memoized selector but receives a new `parents` array reference on every call.

Calling a memoized selector with an unstable argument reference can degrade performance.

## Testing Instructions
1. Open the Site Editor.
2. Edit Navigation menu
3. Add multiple submenu items.
4. Open List View.
5. Test block hover and selection multiple times.
6. Actions should be snappy.

Notes:
* The issue can be reproduced in the post editor, but it's more noticeable in the site editor.
* React DevTools also affect performance for the best results test via incognito mode

### Testing Instructions for Keyboard
Same.

## Screenshots or screencast 

CleanShot 2025-01-27 at 16 35 21

### CODE REVIEW

File: packages/block-editor/src/store/selectors.js [hunk 1]
```diff
@@ -622,6 +622,33 @@ export const getBlockParents = createSelector(
...
+ *
+ * @return {Array} ClientIDs of the parent blocks.
+ */
+function getBlockParentsByBlockNameUnmemoized(
+	state,
+	clientId,
+	blockName,
+	ascending = false
+) {
+	const parents = getBlockParents( state, clientId, ascending );
```
Comment (youknowriad) [inline packages/block-editor/src/store/selectors.js]: This makes a loop internally, I think a better solution would have been to use do while loop to avoid double loops. 
We also are interested only about the first parent, so we could stop the loop at the first parent that validates the condition instead of returning all the parents. So I'd personally avoid this function entirely and just add a do/while loop in the other selector just like the Jetpack patch.

**Comment by youknowriad** [comment]
It would be cool to be able to catch this kind of regression in the perf metrics at some point (maybe we should add a nested navigation block or something)

File: packages/block-editor/src/store/selectors.js (hunk 1 above)
Comment (Mamaduka) [reply packages/block-editor/src/store/selectors.js]: You're right. Simple = better! :) I'll update the code.

**Comment by Mamaduka** [comment]
> It would be cool to be able to catch this kind of regression in the perf metrics at some point (maybe we should add a nested navigation block or something)

100%. Maybe a separate metric to avoid accidentally affecting other metrics.

**Comment by Mamaduka** [comment]
@youknowriad, @mmtr, is this good to merge?

**Comment by mmtr** [comment]
This fixes the issue for me when I test locally with both CoBlocks and WooCommerce active:


https://github.com/user-attachments/assets/8fc21159-2219-4630-b6a5-e602cab9cbf8

**Review by mmtr — APPROVED** [review]

**Comment by Mamaduka** [comment]
Thanks for the confirmation and for providing the patch in the hotfix ticket!

**Comment by Mamaduka** [comment]
@mmtr, @youknowriad, I've found another potential bottle next - #69631.
