### PR TITLE
Block Toolbar: update position when moving blocks

### LINKED ISSUE #44220: Mover control: Block toolbar no longer sticks to block that's being moved until you scroll
Steps to reproduce:

* Insert several paragraphs
* Select a paragraph and click the mover control to move it

Observe that the block toolbar scrolls out of view and stays in place, until you scroll the page.

mover

### PR DESCRIPTION
**Pull request by ciampo**
## What?

Fixes #44220
Fixes partially #44281 (only the disappearing part is left)

Use a `MutationObserver` to make sure that the Block Toolbar updates its position correctly when a block is moved up / down

## Why?

Restoring the intended behaviour of the block toolbar.

## How?

Using a Mutation Observer to track the changes to the block's `transform` inline style attribute, so that we can re-compute the Popover's `anchor` (which causes the `Popover` to recompute its position correctly).

This technique was previously implemented directly in the `Popover` component via the `__unstableObservedElement` prop, which we decided to remove in #43617 while trying to simplify the component's logic.

## Testing Instructions

 - Create a new post
 - Add enough blocks to fill the whole page
 - Start moving blocks around, in particular focus on moving blocks that would cause the editor to scroll
 - Make sure that the block toolbar is always anchored to the selected block correctly

## Screenshots or screencast 

https://user-images.githubusercontent.com/1083581/191295807-61a3cef8-a057-4d4c-9f8c-db9a16bb9de6.mp4

### CODE REVIEW

File: packages/block-editor/src/components/block-popover/index.js [hunk 1]
```diff
@@ -47,8 +52,34 @@ function BlockPopover(
 		};
 	}, [ selectedElement, lastSelectedElement, __unstableRefreshSize ] );
 
+	const [ popoverAnchorRecomputeCounter, forceRecomputePopoverAnchor ] =
+		useReducer( ( s ) => s + 1, 0 );
```
Comment (talldan) [inline packages/block-editor/src/components/block-popover/index.js]: I guess it's unlikely, but I'm always concerned about the integer overflowing with this kind of code (`Number.MAX_VALUE === Number.MAX_VALUE + 1`).

Would a boolean that flips work just as well? Or perhaps using a modulo so that it loops back to zero when it reaches a particular number (`Number.MAX_SAFE_INTEGER`).

File: packages/block-editor/src/components/block-popover/index.js [hunk 2]
```diff
@@ -47,8 +52,34 @@ function BlockPopover(
...
+		observer.observe( selectedElement, { attributes: true } );
+
+		return () => {
+			observer.disconnect();
+		};
+	}, [ selectedElement ] );
+
 	const popoverAnchor = useMemo( () => {
 		if (
+			popoverAnchorRecomputeCounter < 0 ||
```
Comment (talldan) [inline packages/block-editor/src/components/block-popover/index.js:91]: Ah, I see that this wouldn't work so well if the counter looped back to zero or if it were a boolean. Though it could start out as `null` and the check could be `popoverAnchorRecomputeCounter === null`.

**Review by talldan — APPROVED** [review]
Works very smoothly now. Thanks for fixing it!

I left a nitpick, but it's up to you if you want to fix it.

**Comment by talldan** [comment]
@ciampo I think it also fixes #44281. I'm no longer able to reproduce that one.

Sometimes the toolbar is still not visible after dropping, but I think that might be a separate bug. The positioning issue seems solved.

**Review by ntsekouras — APPROVED** [review]
Works well! Thanks Marco!

File: packages/block-editor/src/components/block-popover/index.js (hunk 1 above)
Comment (ciampo) [reply packages/block-editor/src/components/block-popover/index.js]: Good point! I've done that in https://github.com/WordPress/gutenberg/pull/44301/commits/5b72aeefb53432db79100183976da5e9ee3752c1

File: packages/block-editor/src/components/block-popover/index.js (hunk 2 above)
Comment (ciampo) [reply packages/block-editor/src/components/block-popover/index.js:91]: That check is actually mostly there to make sure that every dependency that is listed for `useMemo` is actually used in the hook. Technically, the counter would always be equal or greater than 0 — so that check would always be `false`.

I've added an inline comment to explain this in https://github.com/WordPress/gutenberg/pull/44301/commits/6a9bd8c8899c643bca39082557366df01c3a0828

Comment (talldan) [reply packages/block-editor/src/components/block-popover/index.js:91]: I see, I completely misread `< 0` as `> 0` for some reason!

**Comment by ciampo** [comment]
> @ciampo I think it also fixes https://github.com/WordPress/gutenberg/issues/44281. I'm no longer able to reproduce that one.
> 
> Sometimes the toolbar is still not visible after dropping, but I think that might be a separate bug. The positioning issue seems solved.

That's great to hear, I had the same feeling! 

I also decided to apply the same enhancements suggested by @talldan  and apply them to the inbetween inserter, which was using the same technique for updating the popover correctly: https://github.com/WordPress/gutenberg/pull/44301/commits/cae13768cccd0a12b69cb9c1867b10605aaa9860


Let me know if you'd like to give this PR a final look, otherwise I'll do some testing myself and merge once CI is ✅

**Comment by ciampo** [comment]
@c4rl0sbr4v0 @ockham this one should also be backported if possible. Thank you 🙏

**Comment by ockham** [comment]
Too late for Beta 1 I'm afraid. We'll review the next round of PRs with the Backport label for inclusion in Beta 2 in about a week's time 😊

**Comment by ciampo** [comment]
> Too late for Beta 1 I'm afraid. We'll review the next round of PRs with the Backport label for inclusion in Beta 2 in about a week's time 😊

That's fine! Is there any action needed from my side (i.e changing the label), or can I assume it will considered for Beta 2 already?

**Comment by ockham** [comment]
No action needed, the label is enough! 👍

**Comment by mtias** [comment]
Thanks for fixing this, it's a very important part of the experience

**Comment by ockham** [comment]
I just cherry-picked this PR to the wp/6.1 branch to get it included in the next release: 1845fda864
