### PR TITLE
Navigation Editor: Fix saving locations using the "Manage Locations" popup

### LINKED ISSUE #33815: "Manage Locations" doesn't work on the Navigation screen
### Description

Currently, it's not possible to assign menu locations to a different menu using the "Manage Locations" modal.

### Step-by-step reproduction instructions

Tested using TT1 theme.

1. Go to the experimental Navigation screen.
2. Create two menus.
3. Assign both locations to the first menu.
4. Open the "Manage Locations" modal.
5. Assing both locations to the second menu.
6. Save menu and refresh page.
7. Locations aren't reassigned.

### Expected Behavior

The editor shouldn't assign menu locations to the second menu.

### Current Behavior

The editor doesn't assign menu locations to the second menu.

### Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/240569/127863099-06516efa-dd71-4947-8ec7-9a5e605495f9.mp4

### PR DESCRIPTION
**Pull request by anton-vlasenko**
## Description

This PR aims to give users the ability to assign all available menus to an arbitrary location inside the `Manage Locations` popup.
Currently it's only possible to assign a location to a menu that is being edited.
Fixes #33815.
This PR doesn't fix the issue with the main "Save" button because we have [another issue](https://github.com/WordPress/gutenberg/issues/31813) for that.

## How has this been tested?
1. This has been tested using the `Twenty Twenty-One` WordPress theme.
2. Go to the experimental Navigation screen.
3. Create two menus.
4. Switch to the first menu using the `Switch Menu` link at the top of the page.
5. Open the `Manage Locations` popup.
Screenshot 2021-09-10 at 10 47 40
6. Assign the first location to the first menu.
7. Assign the second location to the second menu.
8. Click the `Update` button.
Screenshot 2021-09-10 at 10 48 21

9. You should see `Menu locations have been updated` message at the bottom of the page.
Screenshot 2021-09-10 at 10 48 18

10. Refresh the page.
11. Make sure that the first menu is assigned to the first location.
12. Switch to the second menu using the `Switch Menu` link at the top of the page.
13. Make sure that the second menu is assigned to the second location. 

## Types of changes
Bug fix ( but this also can be considered as a new feature).

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: lib/class-wp-rest-menus-controller.php [hunk 1]
```diff
@@ -22,6 +22,76 @@ public function __construct( $taxonomy ) {
 		$this->namespace = '__experimental';
 	}
 
+	/**
+	 * Overrides the route registration to support "allow_batch".
+	 *
+	 * @since 11.5.0
+	 */
+	public function register_routes()
+	{
```
Comment (spacedmonkey) [inline lib/class-wp-rest-menus-controller.php]:
```suggestion
	/**
	 * Overrides the route registration to support "allow_batch".
	 *
	 * @since 11.5.0
	 *
	 * @see register_rest_route()
	 */
	public function register_routes() {
```

File: lib/class-wp-rest-menus-controller.php [hunk 2]
```diff
@@ -22,6 +22,76 @@ public function __construct( $taxonomy ) {
...
+					'permission_callback' => array( $this, 'delete_item_permissions_check' ),
+					'args'                => array(
+						'force' => array(
+							'type'        => 'boolean',
+							'default'     => false,
+							'description' => __( 'Required to be true, as terms do not support trashing.' ),
+						),
+					),
+				),
+				'allow_batch' => array( 'v1' => true ),
```
Comment (spacedmonkey) [inline lib/class-wp-rest-menus-controller.php:90]: 👍

File: phpunit/class-wp-rest-menus-controller-test.php [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+ * @package    Gutenberg
+ */
+
+/**
+ * Core class used to manage menus via the REST API.
+ *
+ * @see WP_REST_Controller
+ */
+class WP_REST_Menus_Controller_Test extends WP_REST_Menus_Controller {
+	public function test_it_allows_batch_requests_when_updating_menus() {
```
Comment (spacedmonkey) [inline phpunit/class-wp-rest-menus-controller-test.php]: Move this method to [class-rest-nav-menus-controller-test.php](https://github.com/WordPress/gutenberg/blob/trunk/phpunit/class-rest-nav-menus-controller-test.php) and delete this class.

**Comment by spacedmonkey** [comment]
Some small tweaks to PHP, but the JS looks and works well!

File: phpunit/class-wp-rest-menus-controller-test.php (hunk 3 above)
Comment (anton-vlasenko) [reply phpunit/class-wp-rest-menus-controller-test.php]: Thank you for the review.
I thought the test class must be named according to the class it is testing.
`/__experimental/menus/(?P<id>[\d]+)` endpoint is defined inside the `WP_REST_Menus_Controller` class.
Shouldn't we name the test class `WP_REST_Menus_Controller_Test` then?

**Comment by anton-vlasenko** [comment]
@kevin940726 @getdave @adamziel 
I would need some help from experienced React developers, as I'm still learning React.
I'm not sure if [that](https://github.com/WordPress/gutenberg/pull/34714/files#diff-79b99a8d7c3a031279a7525e86ea44bf9c98a062825d335c73438c649b2399b8R79)'s the best way to export `createBatch` function. 
I need to use `createBatch` because it parses batch responses correctly and I just don't want to duplicate that functionality elsewhere.
Does [this export statement](https://github.com/WordPress/gutenberg/pull/34714/files#diff-79b99a8d7c3a031279a7525e86ea44bf9c98a062825d335c73438c649b2399b8R79
) seem correct to you?
Is there a better way to export it?
Yet another question, do I need to update core-data's [README.md](https://github.com/WordPress/gutenberg/blob/trunk/packages/core-data/README.md) file because we export `createBatch` function now?

File: packages/edit-navigation/src/components/sidebar/manage-locations.js [hunk 4]
```diff
@@ -31,6 +34,42 @@ export default function ManageLocations( {
...
+		} );
+
+		const isSuccess = await batch.run();
+		if ( isSuccess ) {
+			createSuccessNotice( __( 'Menu locations have been updated.' ), {
+				type: 'snackbar',
+			} );
+			closeModal();
+			return;
+		}
```
Comment (adamziel) [inline packages/edit-navigation/src/components/sidebar/manage-locations.js]: @anton-vlasenko  The bad news is that `createBatch` is an experimental API and we don't want to export it from core-data – this would make it a public API that developers may start relying on.

The good news is that you don't need to do that. You could add something along these lines to actions.js:

```js
export const updateMenuLocations = ( menus, menuLocations ) => async ({ registry }) => {
	const tasks = menus.map( ( { id } ) => {
		const locations = menuLocations
			.filter( ( menuLocation ) => menuLocation.menu === id )
			.map( ( menuLocation ) => menuLocation.name );

		return ({ saveEntityRecord }) => saveEntityRecord( 'root', 'menu', {
			locations
		} );
	} );

	return await registry
		.dispatch( 'core' )
		.__experimentalBatch( tasks );
}
```

And then do something like this to your component:

```js
const { updateMenuLocations } = useDispatch( navigationStore );
const handleUpdate = async () => {
	try {
		await updateMenuLocations( menus, menuLocations );

		createSuccessNotice( __( 'Menu locations have been updated.' ), {
			type: 'snackbar',
		} );
		closeModal();
	} catch( e ) {
		createErrorNotice( __( 'There was an error.' ), {
			type: 'snackbar',
		} );
	}
}
```

You will also need to add [`__experimentalUseThunks: true`](https://github.com/WordPress/gutenberg/pull/34541/files#diff-dd8dc10b4147447239a00e1904b08cfa0dc8d3480ec8fed0bbcdbbd48c13cf5cR30) to store definition.


There are a few caveats here. For once, handling errors is pretty tricky. You will need to check for `getLastEntitySaveError` for each saved menu:

```js
	registry
		.select( 'core' )
		.getLastEntitySaveError( kind, entityType, change.id )
```

Ideally the batch would just throw an exception when things fail, but unfortunately this isn't a case now. We may [rework batching soon](https://github.com/WordPress/gutenberg/pull/34295), but it is what it is for now.

Comment (adamziel) [reply packages/edit-navigation/src/components/sidebar/manage-locations.js]: We don't have much documentation on __experimentalBatch, but we use it in the edit-widgets package: https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-widgets/src/store/actions.js#L95

(It's all based in generators so you'll see a lot of `yield` statements, that's an old way. New code can all rely on `async/await`)

File: phpunit/class-wp-rest-menus-controller-test.php (hunk 3 above)
Comment (adamziel) [reply phpunit/class-wp-rest-menus-controller-test.php]: @anton-vlasenko ideally that would be the case. In reality, we don't follow this structure in tests at the moment. All the tests for that `/__experimental/menus` endpoint are in the file @spacedmonkey mentioned so it makes sense to keep adding new tests there.

As for why we have such a naming structure, I am not sure. Perhaps it's to avoid name conflicts when these classes are later migrated to WP core? @gziolo might have more context here.

File: packages/edit-navigation/src/components/sidebar/manage-locations.js (hunk 4 above)
Comment (draganescu) [reply packages/edit-navigation/src/components/sidebar/manage-locations.js]: @adamziel how come it does not have an experimental name?

File: phpunit/class-wp-rest-menus-controller-test.php (hunk 3 above)
Comment (spacedmonkey) [reply phpunit/class-wp-rest-menus-controller-test.php]: When me and Tim migrate this to core, I will make sure to name the test class correctly

Comment (anton-vlasenko) [reply phpunit/class-wp-rest-menus-controller-test.php]: Thank you for the explanation, @adamziel .
I was just curious why we don't follow that structure.

Fixed in 67ea4e4e06d8efbb6df6036800c336d4856ae249

File: packages/edit-navigation/src/components/sidebar/manage-locations.js (hunk 4 above)
Comment (adamziel) [reply packages/edit-navigation/src/components/sidebar/manage-locations.js]: @draganescu I think the purpose of __experimental is to warn others. It makes sense for exported things, but `createBatch()` is not exported anywhere. @noisysocks who implemented it may have more context

Comment (anton-vlasenko) [reply packages/edit-navigation/src/components/sidebar/manage-locations.js]: Thank you for such a great comment, @adamziel ! I owe you. I've learned a lot from it.
I've refactored my code and now it doesn't depend on the `createBatch` function.
I have a question.
1. Is your suggestion to add a new method to the `actions.js` something that is **nice** to have? Or we **must** do it? I'm asking because I'm not sure how much time I'm allowed to spend on this task. I'm not so familiar with the core-data package.
2. We've [agreed](https://github.com/WordPress/gutenberg/issues/33815#issuecomment-908710847) that we will use `experimental/menus/${menuId}` endpoint to send requests to update menus' locations. Do you know if your suggestion uses that endpoint to update menus under the hood?

Comment (adamziel) [reply packages/edit-navigation/src/components/sidebar/manage-locations.js]: @anton-vlasenko
1. we **can't** export createBatch() from core-data so this one is a blocker
2. I haven't actually tested that but I think so, refer to entities.js in core-data whenever in doubt. I'll only be able to confirm on Tuesday so might be faster for you to check than wait for me

Comment (anton-vlasenko) [reply packages/edit-navigation/src/components/sidebar/manage-locations.js]: Thank you for such a great comment, @adamziel ! I owe you. I've learned a lot from it.
I've refactored my code and now it doesn't depend on the `createBatch` function.
I have a question.
 
1. Is your suggestion to add a new method to the `actions.js` something that is **nice** to have? Or we **must** do it? I'm asking because I'm not sure how much time I'm allowed to spend on this task. I'm not so familiar with the core-data package.
2. We've [agreed](https://github.com/WordPress/gutenberg/issues/33815#issuecomment-908710847) that we will use `experimental/menus/${menuId}` endpoint to send requests to update menus' locations. Do you know if your suggestion uses that endpoint to update menus under the hood?

Comment (anton-vlasenko) [reply packages/edit-navigation/src/components/sidebar/manage-locations.js]: @adamziel I would leave it as is because I've refactored my PR and it doesn't depend on `createBatch()` now.
If you insist that we need to add a new method to the `actions.js` file and use core-data package, so be it. Please let me know and I'll go that route.
I'd like to leave this PR as is mainly because of the amount of time I've already spent on it. Time is my main concern here.
Thank you again for all the input.

**Review by spacedmonkey — APPROVED** [review]
Worked in my testing.

**Comment by talldan** [comment]
Thanks @anton-vlasenko!
