### PR TITLE
Ensure that a selection exists before attempting to execCommand

### LINKED ISSUE #1751: Table block causes errors when no table elements are selected
- Add a new table block
- Do not focus any elements (the block is selected, but no elements within it are focused)
- Click the table dropdown menu and click an operation such as "Insert Row Before"
- Observe console errors, and that nothing happens:

2017-07-05t21 24 00 0200

cc @EphoxJames

### LINKED ISSUE #1795: Regression: placeholder remains visible after typing
Commit causing the regression: fa810e26c56a0aba809d8a5038608cfd2d053b5c.

To reproduce, open the demo content, insert a text block, and start typing. If you remove the table from the demo content, everything works fine.

cc @jasmussen @EphoxJames

### LINKED ISSUE #2077: Table block: row/column controls don't do anything if a table cell isn't previously focused
More an interaction flaw than a bug. To my understanding, the TinyMCE table plugin needs a reference to a table cell in order to be able to add/delete rows and columns. That is, when clicking on a table cell or tabbing with the keyboard to a table cell, it then "remembers" the cell that was focused. This is necessary to have a sort of "reference" to determine where to add rows/columns or delete them. 

Thus, the commands in the Table drop-down menu work only if a table cell had focus before using the controls. However, it is possible to make the toolbar and drop-down appear even when no cell has focus. This depends on the integration of the table plugin in Gutenberg, since in TinyMCE the implementation of the table controls is a bit different.

For example, clicking anywhere in the area highligthed in the screenshot below or tabbing without actually focusing the table cells:

screen shot 2017-07-28 at 18 56 53

To reproduce:
- click on the highlighted area
- the toolbar appeares
- open the drop-down menu
- click on any command to add/delete rows or columns
- nothing happens

this is potentially confusing for users, and even more confusing for assistive technologies users.

Not sure about the best option to address this issue. Maybe it should be addressed upstream for example: when there's no reference to a cell, fallback to the first cell in the first row?

### PR DESCRIPTION
**Pull request by BoardJames**
In normal TinyMCE the table toolbar is not shown unless a table is selected. For the table block we want to always show the toolbar even when the editor does not have a table selected so we have to check if a selection is present and supply a default selection when one is not available.

- Fixes #1751 
- Fixes #1795 
- Closes #1798 
- Fixes #2077

### CODE REVIEW

File: blocks/library/table/table-block.js [hunk 1]
```diff
@@ -3,9 +3,28 @@ import BlockControls from '../../block-controls';
 import { Toolbar, DropdownMenu } from 'components';
 import { __ } from 'i18n';
 
+function isTableSelected( editor ) {
+	return editor.dom.getParent(
+		editor.selection.getStart( true ),
+		'table'
```
Comment (aduth) [inline blocks/library/table/table-block.js]: Do we know in this case that the table ancestor here is from _this_ table block, and not another table on the page?

Comment (EphoxJames) [inline blocks/library/table/table-block.js]: Good point. DomUtils.getParent can take a root node as the third parameter so I'll set it to the editor container.

Comment (EphoxJames) [inline blocks/library/table/table-block.js]: Turned out that it needed to be the parent of the editor body otherwise it would not consider the table. Otherwise I think this issue is fixed.

**Comment by nylen** [comment]
Thanks for the fix.  It works well for me.

I added the table back to the demo content (#1806).

This PR should close a few other issues; I've edited them into the original post.  Let's wait until after today's release to merge it though, so we get some testing ahead of a release.

**Review by nylen — APPROVED** [review]
