### PR TITLE
TinyMCE: Fix script registration

### LINKED ISSUE #7133: Error loading TinyMCE scripts through `wp-tinymce.php`
**Describe the bug**

Some servers may expect that TinyMCE is loaded with static JavaScript files rather than `wp-tinymce.php`.

In WordPress core, TinyMCE is loaded as "compressed" via `wp-tinymce.php` or uncompressed (?) via `tinymce.min.js` depending on a [handful of conditions](https://github.com/WordPress/wordpress-develop/blob/29a63fe774c4db4bbc253bbbb723eab9d1b65761/src/wp-includes/class-wp-editor.php#L1422-L1433).

I haven't tracked down the conditions that are causing my server to request the uncompressed version, but I do know that at some point I applied an Nginx configuration that blocks direct access to PHP files in `wp-includes/` and `wp-admin/includes/`. As of Gutenberg 3.0.0, the TinyMCE script results in a 403 forbidden and the editor doesn't work.

My guess is that this problem will go away when Gutenberg is merged into core, but in the meantime it may be good to use the same logic from `class-wp-editor.php` to load TinyMCE.

**To Reproduce**
1. `define( 'COMPRESS_SCRIPTS', false );`
2. Block public access to `wp-includes/*.php`
3. Open new post screen.
4. Click in first paragraph block.
5. See error.

**Expected behavior**
I'd expect to be able to leave my server configuration the same and access the editor.

**Additional context**
- Gutenberg 3.0.0
- WordPress 4.9.6

### PR DESCRIPTION
**Pull request by youknowriad**
closes #7133

In WordPress core, TinyMCE is loaded as "compressed" via `wp-tinymce.php` or uncompressed (?) via `tinymce.min.js` depending on a [handful of conditions](https://github.com/WordPress/wordpress-develop/blob/29a63fe774c4db4bbc253bbbb723eab9d1b65761/src/wp-includes/class-wp-editor.php#L1422-L1433). (Whether the browser supports gzip or not etc...)

This PR mimics the way Core loads TinyMCE in Gutenberg. I expect this PR might fix the issues where people are having "The block has encountered an error" message in all RichText blocks #8936 #8690

### CODE REVIEW

**Review by tofumatt — APPROVED** [review]
Code makes sense to me, but I'm not sure I can reproduce those users issues, so I can't say for sure if it fixes it.

Still, makes sense to me. Worst case is we could 🚢  and then see if they still have the issue in 3.7.

**Comment by Aldebaran10** [comment]
Hi, this morning I found a workaround for this issue: as you said it seems to be related with the server environment using Plesk and Gutenberg 3.6.2. On the same server I tried another WP-Installation where I still have Gutenberg 3.6.1 installed and I don't have any problems with adding blocks there. 

Based on your proposal I found several other threads and specially in #7133 I found a solution that works on my server environment: I just set **define( 'COMPRESS_SCRIPTS', true );** in wp-config.php and now I can add and work with blocks without any problems. 

Hope, this can help others with the same issue.

File: lib/client-assets.php [hunk 1]
```diff
@@ -66,6 +66,28 @@ function gutenberg_get_script_polyfill( $tests ) {
...
 
+/**
+ * Registers the main TinyMCE scripts.
+ */
+function register_tinymce_scripts() {
+	global $tinymce_version, $concatenate_scripts, $compress_scripts;
+	if ( ! isset( $concatenate_scripts ) ) {
+		script_concat_settings();
+	}
+	$suffix     = SCRIPT_DEBUG ? '' : '.min';
```
Comment (iseulde) [inline lib/client-assets.php]: Just wondering: is this intentional or are we meant to make it like this?

Comment (youknowriad) [reply lib/client-assets.php]: It's intentional in the sense of this is mirroring exactly what's done on WP Core

File: lib/client-assets.php [hunk 2]
```diff
@@ -66,6 +66,28 @@ function gutenberg_get_script_polyfill( $tests ) {
...
+	$compressed = $compress_scripts && $concatenate_scripts && isset( $_SERVER['HTTP_ACCEPT_ENCODING'] )
+		&& false !== stripos( $_SERVER['HTTP_ACCEPT_ENCODING'], 'gzip' );
+	// Load tinymce.js when running from /src, otherwise load wp-tinymce.js.gz (in production) or
+	// tinymce.min.js (when SCRIPT_DEBUG is true).
+	$mce_suffix = false !== strpos( get_bloginfo( 'version' ), '-src' ) ? '' : '.min';
```
Comment (iseulde) [inline lib/client-assets.php]: I think there are similar pieces of code in Gutenberg that grab the WP version string. Maybe it would be good to create a separate function for it. We should probably include the version file so we're sure it's not modified by plugins. See `gutenberg_pre_init`.

File: lib/client-assets.php [hunk 3]
```diff
@@ -66,6 +66,28 @@ function gutenberg_get_script_polyfill( $tests ) {
...
+ */
+function register_tinymce_scripts() {
+	global $tinymce_version, $concatenate_scripts, $compress_scripts;
+	if ( ! isset( $concatenate_scripts ) ) {
+		script_concat_settings();
+	}
+	$suffix     = SCRIPT_DEBUG ? '' : '.min';
+	$compressed = $compress_scripts && $concatenate_scripts && isset( $_SERVER['HTTP_ACCEPT_ENCODING'] )
+		&& false !== stripos( $_SERVER['HTTP_ACCEPT_ENCODING'], 'gzip' );
+	// Load tinymce.js when running from /src, otherwise load wp-tinymce.js.gz (in production) or
```
Comment (iseulde) [inline lib/client-assets.php]: I'm not sure I understand what the core version has to do with this. Shouldn't we register the unminified file when Gutenberg is in development mode, not core?

File: lib/client-assets.php (hunk 2 above)
Comment (youknowriad) [reply lib/client-assets.php]: > We should probably include the version file so we're sure it's not modified by plugins

Why? I mean if Core uses this function `get_bloginfo( 'version' )` why not just use this function in `gutenberg_pre_init` as well?

File: lib/client-assets.php (hunk 3 above)
Comment (youknowriad) [reply lib/client-assets.php]: I just wanted to mimic exactly what core does, so we end up loading the exact same URL in Gutenberg and in Core no matter the setup (`src` core with gutenberg for instance) . That way we deduplicate the loading of the script and ensure TinyMCE is loaded in the exact same conditions (use `wp-tinymce.php` when Core does so or use the `js` files)

File: lib/client-assets.php (hunk 2 above)
Comment (iseulde) [reply lib/client-assets.php]: > so we're sure it's not modified by plugins

File: lib/client-assets.php (hunk 3 above)
Comment (iseulde) [reply lib/client-assets.php]: Okay, makes sense

**Review by ellatrix — APPROVED** [review]

File: lib/client-assets.php (hunk 2 above)
Comment (youknowriad) [reply lib/client-assets.php]: > so we're sure it's not modified by plugins

I guess if plugins modifies this, the classic editor would already break right?

Comment (iseulde) [reply lib/client-assets.php]: I'm not sure why? If this is the same code as core then it's fine I guess :)

**Comment by youknowriad** [comment]
Ok merging, let's see if people continue to raise this issue after 3.7
