### PR TITLE
Block support: Add anchor support for dynamic blocks

### LINKED ISSUE #51402: Explore how to re-add anchor support to dynamic blocks
In #44771, anchor support was added to dynamic blocks, but static blocks with existing anchor were broken (See #48232, #49382, and #49578).

This feature was originally planned to be included in WordPress 6.2, but #48232 was the first to report this issue during the Beta phase. Therefore, by #48592, this feature was excluded in the WordPress 6.2 release.

However, this feature still remains on the Gutenberg plugin, which will be bundled with WordPress 6.3 and will cause similar problems. A solution was attempted in #48438, but we reverted in #51288 anchor support for dynamic blocks in the Gutenberg plugin as well, in order to find a more ideal solution.

One approach I have explored is described in [this comment](https://github.com/WordPress/gutenberg/pull/48438#issuecomment-1486234187):

> - The allowed values for `supports.anchor` are `false`, `true`, `"html"`, or "`delimiter`". The `block.json` schema and document have also been updated.
> - If the value is `true` or `"html"`, the attribute is taken from the markup of the root element.
> - If the value is `delimiter`, the attribute is taken from the comment delimiter.
> - Based on these specifications, in dynamic blocks where anchor support was added in [#44771](https://github.com/WordPress/gutenberg/pull/44771), the value of the anchor property was changed to `"delimiter"`.
> - With the increased selection of possible values for `anchor`, several tests have been added to the unit test for `addAttribute()`.

### PR DESCRIPTION
**Pull request by t-hamano**
Closes https://github.com/WordPress/gutenberg/issues/51402

## What?

This PR adds anchor support to almost all dynamic blocks.

## Why?

Efforts to add anchor support to dynamic blocks were made in the past in #44771. However, that work also affected static blocks, potentially breaking them, so it was eventually reverted.

To add consistent anchor support regardless of whether the block is dynamic or static, the anchor is now always kept in comment delimiters (See #70993). This means we can now add anchor support to dynamic blocks.

## How?

- Add anchor support to almost all dynamic blocks.
- Add server-side rendering of anchor support.
- Add unit tests.

As a result, these are the blocks that do not support anchors. The reason I didn't enable it is either:

- It's a static block, so it's outside the scope of this PR.
- It's an experimental block.
- Deprecated block.
- The anchor doesn't work on this block.

| Name | Title |
|------|-------|
| `core/navigation-overlay-close` | Navigation Overlay Close |
| `core/tabs` | Tabs |
| `core/accordion-panel` | Accordion Panel |
| `core/accordion-item` | Accordion Item |
| `core/pattern` | Pattern Placeholder |
| `core/template-part` | Template Part |
| `core/missing` | Unsupported |
| `core/freeform` | Classic |
| `core/block` | Pattern |
| `core/html` | Custom HTML |
| `core/shortcode` | Shortcode |
| `core/text-columns` | Text Columns (deprecated) |
| `core/post-comment` | Comment (deprecated) |
| `core/form-submission-notification` | Form Submission Notification |
| `core/form-submit-button` | Form Submit Button |
| `core/comment-author-avatar` | Comment Author Avatar (deprecated) |

## Testing Instructions

- Insert any of the dynamic blocks.
- Open the Advanced panel and apply an anchor string.
- Save the post and open the post.
- Confirm that the block has an id attribute.

### CODE REVIEW

**Comment by Mamaduka** [comment]
> The anchor doesn't work on this block.

Is this due to the nature of the block (Classic, HTML, blocks without a wrapper) or some other limitation with the feature?

**Review by SirLouen — DISMISSED** [review]
@t-hamano I've tested it, and it's looking good. ✅ 

But there are two proposed changes to the unit tests:

1. The file should end in `-test.php` so in this case `anchor-test.php`
2. Can you add this test to the data provider?
```
'anchor with zero string is applied' => array(
	'support'  => true,
	'value'    => '0',
	'expected' => array( 'id' => '0' ),
),
```

And test it?

**Review by aaronrobertshaw — COMMENTED** [review]
This is testing well for me 👍 

Other than the suggested rename of the test file and the additional test cases, I think this is pretty close. While updating the test cases I think we could cover some more edge cases there.

<details>
<summary>Some possible test cases</summary>

```php
public function data_anchor_block_support() {
    return array(
        'anchor id attribute is applied' => array(
            'support'  => true,
            'value'    => 'my-anchor',
            'expected' => array( 'id' => 'my-anchor' ),
        ),
        'anchor id attribute is not applied if block does not support it' => array(
            'support'  => false,
            'value'    => 'my-anchor',
            'expected' => array(),
        ),
        'empty anchor value returns empty array' => array(
            'support'  => true,
            'value'    => '',
            'expected' => array(),
        ),
        'null anchor value returns empty array' => array(
            'support'  => true,
            'value'    => null,
            'expected' => array(),
        ),
        'whitespace-only anchor value is applied' => array(
            'support'  => true,
            'value'    => '   ',
            'expected' => array( 'id' => '   ' ),
        ),
        'anchor with hyphen and numbers' => array(
            'support'  => true,
            'value'    => 'section-123',
            'expected' => array( 'id' => 'section-123' ),
        ),
        'anchor with underscore' => array(
            'support'  => true,
            'value'    => 'my_anchor_id',
            'expected' => array( 'id' => 'my_anchor_id' ),
        ),
        'anchor with colon (valid in HTML5)' => array(
            'support'  => true,
            'value'    => 'my:anchor',
            'expected' => array( 'id' => 'my:anchor' ),
        ),
        'anchor with period (valid in HTML5)' => array(
            'support'  => true,
            'value'    => 'my.anchor',
            'expected' => array( 'id' => 'my.anchor' ),
        ),
        'numeric anchor value' => array(
            'support'  => true,
            'value'    => '123',
            'expected' => array( 'id' => '123' ),
        ),
        'zero value is treated as empty' => array(
            'support'  => true,
            'value'    => 0,
            'expected' => array(),
        ),
        'false value is treated as empty' => array(
            'support'  => true,
            'value'    => false,
            'expected' => array(),
        ),
    );
}
```
</details>

I primarily tested with the Calendar, Latest Comments, Search, and Navigation blocks but did randomly try several more. Each worked as per the test instructions.

https://github.com/user-attachments/assets/aba929bb-3d89-4c07-ae11-25c4296d4570

**Comment by t-hamano** [comment]
Thanks everyone for the reviews!

> Is this due to the nature of the block (Classic, HTML, blocks without a wrapper) or some other limitation with the feature?

These blocks don't seem to work because they don't have a block wrapper in the first place.

On the other hand, I thought we could add anchor support to the Template Part block, but it didn't work properly. Perhaps there's a problem with the server-side rendering code. I'll investigate this in a follow-up.

> But there are two proposed changes to the unit tests:
> While updating the test cases I think we could cover some more edge cases there.

Updated the test cases 👍

File: phpunit/block-supports/anchor-test.php [hunk 1]
```diff
@@ -0,0 +1,135 @@
...
+			'numeric anchor value'                    => array(
+				'support'  => true,
+				'value'    => '123',
+				'expected' => array( 'id' => '123' ),
+			),
+			'zero string anchor value is applied'     => array(
+				'support'  => true,
+				'value'    => '0',
+				'expected' => array( 'id' => '0' ),
+			),
```
Comment (t-hamano) [inline phpunit/block-supports/anchor-test.php:127]: While this test result is correct, it doesn't actually produce the expected results. That is, when you set an ID value of zero, it doesn't actually render.

This is likely an issue with `get_block_wrapper_attributes()` function, which causes falsy values ​​to be skipped.

https://github.com/WordPress/wordpress-develop/blob/814279bbce8c938e437d3c7a12976419ca8a0c8a/src/wp-includes/class-wp-block-supports.php#L187

This issue should also occur with `className` support and `ariaLabel` support.

I'll submit a follow-up core ticket regarding this.

Comment (Mamaduka) [reply phpunit/block-supports/anchor-test.php:127]: Right, `empty()` will return true for `'0'` and `0`.

**Review by Mamaduka — APPROVED** [review]
This is test well for me ✅
