### PR TITLE
Fix: Rewrite the license check scripts to use Node's native module resolution

### LINKED ISSUE #74429: Automatically exclude dev-tool transitive dependencies from license checks
See https://github.com/WordPress/gutenberg/pull/74310#discussion_r2658117046

## What problem does this address?

The `bin/check-licenses.mjs` script currently requires manually maintaining an ignore list for packages like `@ampproject/remapping`, `webpack`, `bser`, `fb-watchman`, and `walker` (Jest internals with Apache-2.0 license). Some of these packages appear in the license check because:

1. `@wordpress/scripts` has `jest` as a **production dependency** (because it's a tooling package that provides Jest to consumers)
2. The npm query `.workspace:attr([wpScript],[wpScriptModuleExports]) :is(.prod)` includes all transitive dependencies
3. Jest's internal packages have Apache-2.0 license which isn't GPL2-compatible

These packages are only used for testing and are not distributed with WordPress, so they shouldn't require GPL2 compatibility checks. Currently, we manually add them to the `ignored` array, but this approach doesn't scale well as new dev-tool dependencies are added.

## What is your proposed solution?

Automatically filter out transitive dependencies that come exclusively from dev-only packages (like `@wordpress/scripts`).

### Implementation approach:

1. Add a `devOnlyPackages` configuration listing packages whose transitive deps should be excluded:
   ```javascript
   const devOnlyPackages = [ '@wordpress/scripts' ];
   ```

2. Run two npm queries:
   - Get all prod deps of packages with `wpScript`/`wpScriptModuleExports`
   - Get all deps of dev-only packages

3. Filter out packages that are only reachable through dev-only packages:
   ```javascript
   function filterDevOnlyDeps( allDeps, devOnlyDeps ) {
       const devOnlyNames = new Set( devOnlyDeps.map( ( dep ) => dep.name ) );
       return allDeps.filter( ( dep ) => ! devOnlyNames.has( dep.name ) );
   }
   ```

4. Add unit tests for the filtering function

### Benefits:
- No need to manually add Jest packages (or other dev-tool deps) to the ignore list
- Future dev-tool dependencies are automatically handled
- More maintainable and less error-prone

### PR DESCRIPTION
**Pull request by manzoorwanijk**
Closes #74429, inspired by #74309

## What?

Alternative to #74694, fixing the issue in the `scripts` package itself.

Rewrite the license check scripts to use Node's native module resolution, with support for `findPackageJSON` (Node.js 22.14.0+).

## Why?

The current implementation uses `npm query` to find production dependencies, but the query logic has issues:

1. **Incorrect transitive dependency inclusion**: The query captures all transitive dependencies, including those from dev-tool packages like Jest (via `@wordpress/scripts`). This causes packages like `@ampproject/remapping`, `bser`, `fb-watchman`, and `walker` to be incorrectly flagged, requiring manual maintenance of an `ignored` list.

2. **Package manager dependency**: The `npm query` approach only works with npm, not with pnpm or yarn.

The new implementation:
- Uses Node's native module resolution (`findPackageJSON` when available, with fallback)
- Works with npm, pnpm, and yarn classic (not yarn PnP which doesn't use `node_modules`)
- Consolidates the resolution logic in `packages/scripts/utils/license.js` for reuse
- Eliminates the need for the `ignored` list

## How?

1. **Added shared utilities to `packages/scripts/utils/license.js`**:
   - `resolvePackagePath()` - resolves a package using `findPackageJSON` (Node 22.14+) or `createRequire` fallback
   - `readPackageJson()` - reads and parses package.json from a directory

2. **Updated `bin/check-licenses.mjs`** (Gutenberg CI):
   - Uses the shared utilities instead of `npm query`
   - Iterates over workspace packages with `wpScript`/`wpScriptModuleExports`
   - Recursively resolves production dependencies

3. **Updated `packages/scripts/scripts/check-licenses.js`** (`wp-scripts check-licenses`):
   - Now also uses the shared utilities instead of `npm query`
   - Makes it package-manager agnostic for external users

4. **Added `MIT-0` to GPL2-compatible licenses**:
   - MIT-0 (MIT No Attribution) is more permissive than MIT, so it's GPL2 compatible

## Testing Instructions

1. Run the license check to verify it passes:
   ```bash
   node bin/check-licenses.mjs
   ```

**Test 1: Direct dependency with incompatible license**

2. Add `typescript` (Apache-2.0, not GPL-compatible) as a prod dependency:
   ```bash
   npm install --workspace=@wordpress/a11y typescript@5.9.3
   ```

3. Run the license check - it should fail:
   ```bash
   node bin/check-licenses.mjs
   # Should output an error about typescript having Apache-2.0 license
   ```

4. Move typescript to devDependencies (which are not checked):
   ```bash
   npm install --workspace=@wordpress/a11y --save-dev typescript@5.9.3
   ```

5. Run the license check again - it should pass:
   ```bash
   node bin/check-licenses.mjs
   # Should pass since devDependencies are not checked
   ```

6. Restore:
   ```bash
   git checkout packages/a11y/package.json
   npm install
   ```

**Test 2: Transitive dependency with incompatible license**

7. Add `jest` (MIT license, but has transitive deps with Apache-2.0) as a prod dependency:
   ```bash
   npm install --workspace=@wordpress/a11y jest@29.6.2
   ```

8. Run the license check - it should fail due to transitive dependencies like `@ampproject/remapping` (Apache-2.0):
   ```bash
   node bin/check-licenses.mjs
   # Should output an error about Apache-2.0 license
   ```

9. Move jest to devDependencies (which are not checked):
   ```bash
   npm install --workspace=@wordpress/a11y --save-dev jest@29.6.2
   ```

10. Run the license check again - it should pass:
    ```bash
    node bin/check-licenses.mjs
    # Should pass since devDependencies are not checked
    ```

11. Restore the original state:
    ```bash
    git checkout packages/a11y/package.json
    npm install
    ```

12. Repeat the above steps for a package without `wpScript` or `wpScriptModuleExports`. For example, `@wordpress/env` and confirm that the license check doesn't fail in any case.

**Test 3: wp-scripts check-licenses**

13. Test that `wp-scripts check-licenses` also works:
    ```bash
    cd packages/a11y
    node ../../packages/scripts/scripts/check-licenses.js --prod --gpl2
    ```

### CODE REVIEW

**Comment by manzoorwanijk** [comment]
This works better than `npm query`. This now [caught a license](https://github.com/WordPress/gutenberg/actions/runs/21466628317/job/61830059261?pr=75039) that was not whitelisted - `MIT-0`

**Comment by manzoorwanijk** [comment]
@aduth any feedback on this?

**Comment by aduth** [comment]
Hey @manzoorwanijk , sorry I haven't had a chance to look at this yet. It's been sitting in my "todo" pile but I've had other obligations that have kept me from reviewing it. I'll try to find some time next week to give it a proper review.

File: bin/check-licenses.mjs [hunk 1]
```diff
@@ -3,36 +3,117 @@
...
+const ROOT_DIR = path.resolve( __dirname, '..' );
 
 const ignored = [
-	'@ampproject/remapping',
-	// Jest internals with Apache-2.0 license - only used for testing, not distributed.
-	'bser',
-	'fb-watchman',
-	'walker',
+	// Nothing ignored for now
 ];
```
Comment (aduth) [inline bin/check-licenses.mjs]: I think it's reasonable to expect we shouldn't want to allow ignoring as long as the script is working correctly, which it is now. We only had this previously for false positives for faulty script behavior that we're addressing here.

tl;dr Can we remove this array?

File: bin/check-licenses.mjs [hunk 2]
```diff
@@ -3,36 +3,117 @@
...
-const licenses = getLicenses( true );
-const query = `.workspace:attr([wpScript],[wpScriptModuleExports]) :is(.prod):not(${ licenses
-	.map( ( license ) => `[license=${ JSON.stringify( license ) }]` )
-	.join( ',' ) })`;
+/**
+ * Get all production dependencies for packages with wpScript or wpScriptModuleExports.
+ *
+ * @return {Array} Array of dependency objects with name, version, path, and license
+ */
+function getDependenciesToProcess() {
```
Comment (aduth) [inline bin/check-licenses.mjs]: Is there opportunities to DRY this up, e.g. exporting this from the package and using it here? Recognizing it's not entirely the same, but there's a good amount of overlap. e.g. `collectDeps` looks mostly the same, minus the "ignore" behavior, which could be parameterized.

File: bin/check-licenses.mjs [hunk 3]
```diff
@@ -3,36 +3,117 @@
...
+			const depPath = resolvePackagePath( depName, fromDir );
+			if ( ! depPath ) {
+				continue;
+			}
+
+			// Avoid infinite loops
+			if ( visited.has( depPath ) ) {
+				continue;
+			}
+			visited.add( depPath );
```
Comment (aduth) [inline bin/check-licenses.mjs]: Is the idea of tracking `depPath` instead of `depName` that we could have multiple copies (multiple versions) with different licenses and we need to check all of the individual copies? Just wondering if there's an optimization opportunity to skip before running `resolvePackagePath`.

File: packages/scripts/utils/license.js [hunk 4]
```diff
@@ -370,9 +373,83 @@ function detectTypeFromLicenseFiles( path ) {
...
+	try {
+		const resolved = localRequire.resolve(
+			`${ packageName }/package.json`
+		);
+		return realpathSync( path.dirname( resolved ) );
+	} catch {
+		try {
+			const mainResolved = localRequire.resolve( packageName );
+			let dir = path.dirname( mainResolved );
+			while ( dir !== path.parse( dir ).root ) {
```
Comment (aduth) [inline packages/scripts/utils/license.js:421]: Should this go all the way to the filesystem root, or should we stop it at a place like `process.cwd` / project root somehow?

File: packages/scripts/utils/license.js [hunk 5]
```diff
@@ -370,9 +373,83 @@ function detectTypeFromLicenseFiles( path ) {
...
+
+	// Fallback for older Node.js versions
+	const localRequire = createRequire( path.join( fromDir, 'package.json' ) );
+	try {
+		const resolved = localRequire.resolve(
+			`${ packageName }/package.json`
+		);
+		return realpathSync( path.dirname( resolved ) );
+	} catch {
+		try {
```
Comment (aduth) [inline packages/scripts/utils/license.js:418]: What's the situation this `catch` is handling? As I was reading, I was wondering how `require.resolve` handles packages that have `exports`, if `package.json` isn't one of its `exports`. Is that what this is accounting for?

File: packages/scripts/utils/license.js [hunk 6]
```diff
@@ -370,9 +373,83 @@ function detectTypeFromLicenseFiles( path ) {
...
+function readPackageJson( dir ) {
+	const pkgJsonPath = path.join( dir, 'package.json' );
+	if ( existsSync( pkgJsonPath ) ) {
+		try {
+			return JSON.parse( readFileSync( pkgJsonPath, 'utf8' ) );
+		} catch {
+			return null;
+		}
+	}
+	return null;
```
Comment (aduth) [inline packages/scripts/utils/license.js]: Minor: Rather than an extra stats call to check that the file exists, could we just try reading the file and absorb the non-existing file case into the existing error catching? i.e. `try` handles both invalid JSON as well as file not existing.

```suggestion
	try {
		return JSON.parse( readFileSync( pkgJsonPath, 'utf8' ) );
	} catch {}
	return null;
```

**Review by aduth — APPROVED** [review]
Nice work 👍 Thanks for the detailed testing instructions, and sorry again for the delay reviewing this.

Glad that we're making this more reliable and portable across package managers. A few ideas and suggestions but nothing especially blocking.

File: bin/check-licenses.mjs (hunk 1 above)
Comment (manzoorwanijk) [reply bin/check-licenses.mjs]: Removed. Thanks

File: bin/check-licenses.mjs (hunk 2 above)
Comment (manzoorwanijk) [reply bin/check-licenses.mjs]: Extracted. Thanks

File: bin/check-licenses.mjs (hunk 3 above)
Comment (manzoorwanijk) [reply bin/check-licenses.mjs]: Yes, exactly. With `linked` or `nested` install strategies, the same package name can exist at multiple paths with different versions (and potentially different licenses)

File: packages/scripts/utils/license.js (hunk 4 above)
Comment (manzoorwanijk) [reply packages/scripts/utils/license.js:421]: Good catch - updated the loop to break at a `node_modules` directory boundary.

File: packages/scripts/utils/license.js (hunk 5 above)
Comment (manzoorwanijk) [reply packages/scripts/utils/license.js:418]: Yes, exactly - this handles packages that use exports in their `package.json` without exporting `./package.json`.

File: packages/scripts/utils/license.js (hunk 6 above)
Comment (manzoorwanijk) [reply packages/scripts/utils/license.js]: Done. Thanks
