### PR TITLE
Fix clicking on the toggle button not closing the block inserter

### LINKED ISSUE #43090: Unable to dismiss block inserter panel after inserting a V2 block
### Description

After using the block inserter panel to insert a V2 block like the Buttons block, it is not possible to dismiss the panel.

### Step-by-step reproduction instructions

- Start a new post.
- Click on the `+` icon to open the block inserter panel.
- Search for Buttons.
- Select the Buttons block.
- Click on the `x` icon to close the block inserter panel.
- The panel remains visible.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1233880/183873149-ed396187-2d54-41f9-847a-7904a9bef0e1.mov

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by kevin940726**
## What and why?

Fix https://github.com/WordPress/gutenberg/issues/43090.

## How?
 This PR takes an ad-hoc approach to fix the issue. There might be better solutions with focus handling, but it'd be nice to land this until we find a better solution.

## Testing Instructions

1. Create a new post
2. Click on the block inserter toggle button
3. Click on the "Buttons" option to insert a buttons block
4. Click on the block inserter toggle button again
5. Expect the block inserter to be closed

Also added an e2e test.

### Testing Instructions for Keyboard

This issue is not reproducible on keyboard.

## Screenshots or screencast 

https://user-images.githubusercontent.com/7753001/217820201-9637d940-3271-4c58-9603-775df69b7b21.mp4

### CODE REVIEW

**Review by apeatling — CHANGES_REQUESTED** [review]
This is working well in the post editor, but I still see the same issue in the site editor so you'll need to adjust it there too. :+1:

**Review by alexstine — APPROVED** [review]
@kevin940726 Thanks for the fix. This has been annoying me for some time. Glad the button toggles now.

File: packages/e2e-test-utils-playwright/src/editor/get-blocks.ts [hunk 1]
```diff
@@ -12,10 +12,19 @@ import type { Editor } from './index';
  */
 export async function getBlocks( this: Editor ) {
 	return await this.page.evaluate( () => {
+		const blocks = window.wp.data.select( 'core/block-editor' ).getBlocks();
+
 		// The editor might still contain an unmodified empty block even when it's technically "empty".
-		if ( window.wp.data.select( 'core/editor' ).isEditedPostEmpty() ) {
```
Comment (kevin940726) [inline packages/e2e-test-utils-playwright/src/editor/get-blocks.ts:16]: `isEditedPostEmpty()` is always returning an empty array in the site editor for some reason 🤔 .

Comment (Mamaduka) [reply packages/e2e-test-utils-playwright/src/editor/get-blocks.ts:16]: I think `isEditedPostEmpty` depends on the current post, which we don't set up in Site Editor.

Comment (kevin940726) [reply packages/e2e-test-utils-playwright/src/editor/get-blocks.ts:16]: Yep, but I don't think there's an alternative for the site editor, or is there? Probably doesn't need it though 🤔 ?

Comment (Mamaduka) [reply packages/e2e-test-utils-playwright/src/editor/get-blocks.ts:16]: There's no alternative, as far as I know. So I guess there's no need for it.

**Review by Mamaduka — APPROVED** [review]
Fixes issue in both Post and Site editor ✅

**Review by ntsekouras — DISMISSED** [review]
Thanks for the PR @kevin940726!

This PR though doesn't solve the root issue([described here](https://github.com/WordPress/gutenberg/issues/43090#issuecomment-1218286314)) which is related to focus loss.

The inserter behaves like a Popover and this PR checks only the `click` handler.
In the exact same scenario when focus is lost, you can still not close it by focusing outside or by clicking `Escape` etc..

The proper solution is handle this scenario and restore the focus to a different element inside the inserter. It might be convoluted in general though...


--- 

-- edit
It seems there is a consensus to land this ad hoc fix, so feel free to land..

**Review by apeatling — APPROVED** [review]

**Comment by apeatling** [comment]
Working in the site editor now, LGTM! 👍

**Comment by ntsekouras** [comment]
I just cherry-picked this PR to the wp/6.2 branch to get it included in the next release: 7c87d68c55
