### PR TITLE
Interactivity API: Break up long hydration task in interactivity init

### LINKED ISSUE #58225: Interactivity API: Hydration causes long task
### Description

When there are a number of interactive blocks on the page, there is a good chance that browsers will experience a significant long task caused by [`init()`](https://github.com/WordPress/gutenberg/blob/2e01f2208e1e43492236684315f1654cb54e2973/packages/interactivity/src/init.js#L24-L35), especially on lower-powered devices.

On a page with 20 interactive blocks and without any throttling on my HP Elite Dragonfly Chromebook (Intel i7), profiling a page load in DevTools results in a 64 ms long task ([trace.cafe](https://trace.cafe/t/BMWwy09a9k)):

image

Not terrible, but when I throttle the CPU 6x then the task gets looooong at 309 ms ([trace.cafe](https://trace.cafe/t/kRCbxxDFH5)):

image

Reminder that a [task is considered long](https://web.dev/articles/optimize-long-tasks) if it is longer than 50 ms.

There is a [discussion about lazy-hydration of interaction blocks](https://github.com/WordPress/gutenberg/discussions/52723) in which @luisherranz  acknowledges this:

> It'd be great to delay the hydration of some of the interactive blocks to improve the time-to-interactive metrics of the site.

However, lazy hydration may not be sufficient if there are too many interactive blocks in the initial viewport. To deal with this, the work in the `init()` function could be broken up so that iteration over an interactive block [yields](https://web.dev/articles/optimize-long-tasks?utm_source=devtools#use_asyncawait_to_create_yield_points) after hydration.

### Step-by-step reproduction instructions

I configured a site with 20 interactive blocks:

* 1 Search block with `"buttonPosition":"button-only","buttonUseIcon":true,"isSearchFieldHidden":true`
* 1 Navigation block with `"openSubmenusOnClick":true,"overlayMenu":"always"`
* 1 Navigation block with `"openSubmenusOnClick":true,"overlayMenu":"never"`, where there are two submenus (each of which is an interactive block), so 2 interactive blocks here
* 1 File block with `"displayPreview":true`
* 15 Image blocks with `"lightbox":{"enabled":true}`

Then I opened DevTools and ran performance profiling with 6x CPU throttling and without any throttling.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WordPress 6.5-alpha-57345
Gutenberg 17.6.0-rc.1
HP Dragonfly Elite Chromebook
Twenty Twenty-Three theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #58225.

## What?

Avoid long task during interactivity initialization

## Why?

Long tasks create a poor user experience and can negatively impact Largest Contentful Paint (LCP), Total Blocking Time (TBT), First Input Delay (FID), and Interaction to Next Paint (INP).

## How?

As outlined in [Optimize Long Tasks](https://web.dev/articles/optimize-long-tasks), this breaks up the long task in the `init()` by yielding to main after each node is hydrated.

## Testing Instructions

1. Add 20 blocks using interactivity to a post.
2. Run profiling in DevTools with and without 6x CPU slowdown.
3. Check for improvements to whether initialization causes a long task.

### Without CPU Throttling

Before | After
-----|-----
image | image

### With 6x CPU Throttling

Before | After
-----|-----
image | image

### Lighthouse Performance Audit

Before | After
--|--
image | image

### CODE REVIEW

File: packages/interactivity/src/init.js [hunk 1]
```diff
@@ -21,15 +21,25 @@ export const getRegionRootFragment = ( region ) => {
...
+	const nodes = document.querySelectorAll(
+		`[data-${ directivePrefix }-interactive]`
+	);
+
+	for ( const node of nodes ) {
+		if ( ! hydratedIslands.has( node ) ) {
+			await yieldToMain();
+			const fragment = getRegionRootFragment( node );
+			const vdom = toVdom( node );
+			hydrate( vdom, fragment );
```
Comment (luisherranz) [inline packages/interactivity/src/init.js]: If necessary, these two tasks could also be broken down:

```suggestion
			const vdom = toVdom( node );
			await yieldToMain();
			hydrate( vdom, fragment );
```

File: packages/interactivity/src/init.js [hunk 2]
```diff
@@ -21,15 +21,25 @@ export const getRegionRootFragment = ( region ) => {
 	return regionRootFragments.get( region );
 };
 
+function yieldToMain() {
+	return new Promise( ( resolve ) => {
+		// TODO: Use scheduler.yield() when available.
```
Comment (luisherranz) [inline packages/interactivity/src/init.js:26]: What about `isInputPending`? Can both be used here?

**Review by luisherranz — COMMENTED** [review]
This is fantastic 👏 👏 

I didn't know breaking down tasks like this was so simple.

---

Could you please add an entry in [the package Changelog](https://github.com/WordPress/gutenberg/blob/trunk/packages/interactivity/CHANGELOG.md)?

File: packages/interactivity/src/init.js (hunk 1 above)
Comment (westonruter) [reply packages/interactivity/src/init.js]: It looks like `toVdom` takes about a third of the amount of time as `hydrate`. But breaking it up here will further ensure that there are no long tasks:

image

File: packages/interactivity/src/init.js (hunk 2 above)
Comment (westonruter) [reply packages/interactivity/src/init.js:26]: Humm. Good question. Since `init` runs at `DOMContentLoaded` it seems like it would be unlikely that there would be input pending at this early point, but it could happen. But if we're already yielding with each `toVdom()` and `hydrate()`, then it seems `isInputPending()` would only be used to decide whether or not to skip yielding, right?

**Comment by westonruter** [comment]
> Could you please add an entry in [the package Changelog](https://github.com/WordPress/gutenberg/blob/trunk/packages/interactivity/CHANGELOG.md)?

Done in https://github.com/WordPress/gutenberg/pull/58227/commits/cffdb4dd93d962957e7c01e3e236eff7505f6f1a!

File: packages/interactivity/src/init.js (hunk 2 above)
Comment (westonruter) [reply packages/interactivity/src/init.js:26]: Also, it would seem like `isInputPending()` would be much more important in the context of actions, since they are more inherently running at the time of user input.

File: packages/interactivity/src/init.js [hunk 3]
```diff
@@ -21,15 +21,26 @@ export const getRegionRootFragment = ( region ) => {
...
+	const nodes = document.querySelectorAll(
+		`[data-${ directivePrefix }-interactive]`
+	);
+
+	for ( const node of nodes ) {
+		if ( ! hydratedIslands.has( node ) ) {
+			await yieldToMain();
+			const fragment = getRegionRootFragment( node );
+			const vdom = toVdom( node );
+			await yieldToMain();
```
Comment (westonruter) [inline packages/interactivity/src/init.js:42]: @luisherranz Actually, what is the purpose of `hydratedIslands` here? Could it be that the check for `! hydratedIslands.has( node )` could be done so that the condition is entered, but then yielding occurs so that it's possible that the island could be hydrated by another task? Could it be that `toVdom()` accidentally gets called on a hydrated island?

File: packages/interactivity/src/init.js (hunk 2 above)
Comment (westonruter) [reply packages/interactivity/src/init.js:26]: I've incorporated `isInputPending()` into #58284 for lazy-hydration. There, since hydration could happen at any point of the lifecycle of the page when a user is potentially doing an input, I think it makes more sense to check for input there.

Comment (luisherranz) [reply packages/interactivity/src/init.js:26]: Ok, thanks Weston.

File: packages/interactivity/src/init.js (hunk 3 above)
Comment (luisherranz) [reply packages/interactivity/src/init.js:42]: > what is the purpose of hydratedIslands here?

Islands that are inside other islands belong to the same _Preact application_ so they can share context and such. When an island is already hydrated as part of a parent, we skip its own hydration.

> that it's possible that the island could be hydrated by another task?

I actually [spotted a bug yesterday](https://github.com/WordPress/wordpress-develop/pull/5922#issuecomment-1910673494) due to the fact that [the router store was calling `toVdom`](https://github.com/WordPress/gutenberg/blob/ebab5b682ff9aa5eccbf630747a6f41ce79fa5db/packages/interactivity-router/src/index.js#L78-L82) before the `init`. It's a rare edge case, but I'll fix it.

As `toVdom` is going to be a private, core-only API in WP 6.5, there should no be more problems. But in the future, if `toVdom` is exposed publicly, we can add a second argument to `toVdom( node, isHydrating = false )` to know if it should add the nodes to the `hydratedIslands` map or not.

**Review by luisherranz — APPROVED** [review]
I think this is an easy win and I wouldn't mind including it for WP 6.5.

Feel free to merge.
