### PR TITLE
Fix Link UI popover positioning when inspector control input is focused

### LINKED ISSUE #45009: Link popup is misplaced if editor is not focussed
### Description

If the editor itself isn't focussed then the link popup UI appears in an incorrect position.

image

### Step-by-step reproduction instructions

1. Start a new post and enable top toolbar mode
2. Click into the first paragraph to show the formatting tools
3. Click out of the paragraph to remove focus (i.e. open block settings, click into a text field)
4. Click the link button in the top toolbar formatting tools
7. Note the popup appears in the top left corner

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1277682/196129050-e6980fcc-210c-4ca7-83fb-9f29c4959513.mp4

### Environment info

- WordPress 6.0.2
- Gutenberg 14.3.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by getdave**
## What?

Fixes the Link UI popover to be positioned correctly if user selection is not within the block's editable element.

Fixes https://github.com/WordPress/gutenberg/issues/45009

## Why?

The popover was disappearing out of view.

## How?

If the current window `Selection` object's `anchorNode` is not contained within the editable element then use the editable element itself as the anchor point for the popover.

## Testing Instructions

- Activate Top Toolbar mode
- Add a paragraph block.
- Click on `Link` button in the block toolbar.
- See popover positioned correctly relative to the paragraph block.
- Now click into the block's inspector controls and focus within an `<input>` (such as the one within the `Advanced` section).
- Now click on `Link` button in the block toolbar.
- See popover positioned correctly relative to the paragraph block.
- Try the same with other types of blocks.

## Screenshots or screencast 

https://user-images.githubusercontent.com/444434/200925000-c7fc7060-7fd9-4293-9534-653df5d34a18.mp4

### CODE REVIEW

File: packages/rich-text/src/component/use-anchor.js [hunk 1]
```diff
@@ -45,13 +45,18 @@ export function useAnchor( { editableContentElement, value, settings = {} } ) {
...
+			editableContentElement?.contains( selection?.anchorNode );
+
 		const range = selection.getRangeAt( 0 );
 
 		if ( ! activeFormat ) {
 			return {
 				ownerDocument: range.startContainer.ownerDocument,
 				getBoundingClientRect() {
-					return range.getBoundingClientRect();
+					return ! selectionWithinEditableContentElement
```
Comment (draganescu) [inline packages/rich-text/src/component/use-anchor.js]: nit: can we start with 'yes'? I mean remove the negation and reverse the ternary?

**Review by draganescu — APPROVED** [review]
Tested and it fixes the problem. The code makes sense as it treats the edge case correctly.

File: packages/rich-text/src/component/use-anchor.js [hunk 2]
```diff
@@ -45,13 +45,18 @@ export function useAnchor( { editableContentElement, value, settings = {} } ) {
...
+						? editableContentElement.getBoundingClientRect()
+						: range.getBoundingClientRect();
```
Comment (getdave) [inline packages/rich-text/src/component/use-anchor.js:59]:
```suggestion
					return selectionWithinEditableContentElement
						? range.getBoundingClientRect()
						: editableContentElement.getBoundingClientRect();
```

File: packages/rich-text/src/component/use-anchor.js (hunk 1 above)
Comment (getdave) [reply packages/rich-text/src/component/use-anchor.js]: ✅
