### PR TITLE
Meta boxes absent when script enqueued in head depends on `wp-edit-post`

### LINKED ISSUE #6963: Meta Boxes: Meta boxes absent when script enqueued in head depends on `wp-edit-post`
**Describe the bug**

If a plugin registers a script which depends on `'wp-edit-post'` and does not explicitly pass [`$in_footer` as `true` in its script registration](https://developer.wordpress.org/reference/functions/wp_register_script/), meta boxes will not be displayed.

**To Reproduce**

1. Create a file at `wp-content/mu-plugins/demo-breakage.php` with the following content:

```php
<?php

/**
 * Plugin Name: Demo Breakage
 */

add_action( 'init', function() {
    wp_enqueue_script( 'demo-breakage', '/', [ 'wp-edit-post' ] );
} );
```

2. Activate at least one plugin which adds a meta box (e.g. Yoast)
3. Navigate to the editor
4. Note that the meta box is not shown

**Expected behavior**

Meta boxes should be shown regardless of whether plugin author passes `$in_footer => true`, or this should be very clearly documented, as it is too easy to overlook and too difficult to debug (speaking from experience).

**Suspected cause**

#5943 changed Gutenberg script registration to enqueue in footer (cc @pento)

Meta boxes rely on this because they are not registered until Gutenberg content is output:

https://github.com/WordPress/gutenberg/blob/1e689af43b6e29336678eac29278de8afaf5808c/gutenberg.php#L33

https://github.com/WordPress/gutenberg/blob/1e689af43b6e29336678eac29278de8afaf5808c/lib/meta-box-partial-page.php#L327-L330

So when a plugin depends on `wp-edit-post` and it does not register itself to be enqueued into the footer, it effectively pulls the `wp-edit-post` enqueuing into the head instead. Since the meta boxes' `wp_add_inline_script` is called after the `wp-edit-post` inline scripts have already been printed, it is never output to the page (and thus never called).

Alternative solution: Should late `wp_add_inline_script` be accounted for in some fashion, similar to `print_footer_script`'s handling of ["scripts that were queued [...] too late for the HTML head"](https://developer.wordpress.org/reference/functions/print_footer_scripts/) ?

**Additional context**

- Gutenberg 2.9.2

### PR DESCRIPTION
**Pull request by desrosj**
Manually print inline metabox initialization JavaScript when the `wp-edit-post` script is printed in the `<head>`.

Currently, metaboxes do not display when any registered script is dependent on the `wp-edit-post` script and output in the page's `<head>` tag (causing the `wp-edit-post` script to also be printed in the `<head>`. This is because the head scripts and styles are being printed before the inline script is added to `wp-edit-post`, and WordPress cannot print what is not yet registered.

The plugin will now check if the `wp-edit-post` script is `done` and manually output the inline script to ensure metaboxes are properly initialized and displayed.

I played around with `WP_Scripts()->print_inline_script( 'wp-edit-post' )`, but there is no way to print a single inline script attached to a registered script. This causes _every_ inline script to be re-printed and breaks the app. I could not find a function that exists in core to print a one-off inline script not attached to specific registered script. The needed part of `WP_Scripts()->print_inline_script()` is only one line, so I have copied that into the plugin.

## How has this been tested?
To test, follow the steps detailed in #6963 to reproduce the issue. Then apply the changes in this branch to verify it fixes the issue.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows the accessibility standards.
- [x] My code has proper inline documentation.

Fixes #6963.

### CODE REVIEW

**Review by pento — APPROVED** [review]
I sure do enjoy the hacks we need to do to work around all of the weird things we run into. 🙂

Nice work on digging into this, @desrosj.

File: lib/meta-box-partial-page.php [hunk 1]
```diff
@@ -324,10 +324,19 @@ function the_gutenberg_metaboxes() {
...
-	wp_add_inline_script(
-		'wp-edit-post',
-		'window._wpLoadGutenbergEditor.then( function( editor ) { editor.initializeMetaBoxes( ' . wp_json_encode( $meta_box_data ) . ' ) } );'
-	);
+	$script = 'window._wpLoadGutenbergEditor.then( function( editor ) { editor.initializeMetaBoxes( ' . wp_json_encode( $meta_box_data ) . ' ) } );';
+
+	wp_add_inline_script( 'wp-edit-post', $script );
+
+	/**
+	 * When `wp-edit-post` is output in the `<head>`, the inline script needs to be manually printed. Otherwise,
```
Comment (youknowriad) [inline lib/meta-box-partial-page.php]: Can't we force `wp-edit-post` to print in the footer? I thought the last `true` argument serves this purpose?

Comment (pento) [reply lib/meta-box-partial-page.php]: `wp-edit-post` will default to printing in the footer, but if a script that prints in the header depends on it, then `WP_Script`'s dependency handling will move it to the header.

Comment (youknowriad) [reply lib/meta-box-partial-page.php]: Got it, makes me wonder if there should be a way to "force" dependencies in the footer as well. Thanks for the clarification.

Comment (pento) [reply lib/meta-box-partial-page.php]: It's one of those back compat issues. Historically, JS would be written in a way that required it to be loaded in the header. Then more modern practices came along, JS would be written to run asynchronously with the page render, so it could be loaded in the footer, instead.

However, we still had a world of JS that needed to be run synchronously. And if that JS required some other JS that could run asynchronously, the only safe option was to move the async JS to the header.

Comment (desrosj) [reply lib/meta-box-partial-page.php]: @youknowriad Check out https://core.trac.wordpress.org/ticket/44709. Hoping to find a better alternative long term solution to this issue.
