### PR TITLE
Set scroll velocity from drag distance

### LINKED ISSUE #18498: Cannot drag and scroll
**Describe the bug**

It's not possible to drag and drop block to a point outside the viewport.
I've run into this several times before, and I'm surprised I hadn't reported it yet.

drag-scroll

Support thread: https://wordpress.org/support/topic/drag-scroll-impossible-not-working/

**To reproduce**
Drag a block up or down the page. The page doesn't scroll.

### PR DESCRIPTION
**Pull request by gravityrail**
## Description

Current scrolling behaviour is somewhat unintuitive. The user needs to drag the item to the top of the viewport, and only then does scrolling begin. Also, the scroll placeholder is fully opaque. These two effects combine to make it hard to know where you're scrolling to, and to control scroll velocity.

This PR sets the vertical scroll velocity of the nearest suitable parent according to a function F of the vertical distance between the current mouse position and the Y position where the drag started. 

It also sets the opacity of the drag placeholder to 0.7.

## How has this been tested?

I just messed with it til it worked, sorry.

## Screenshots 

Video of previous behaviour: https://cloudup.com/cMcikA6icrw

Video of new behaviour: https://cloudup.com/c7UJlVgp5ry

## Types of changes

Changes how scroll velocity reacts to cursor position while dragging.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by gravityrail** [comment]
btw I have done very little testing and zero cross browser testing, this PR should serve as inspiration rather than a complete solution. I would love for someone to put it through its paces. Happy to chip away at it if nobody else volunteers.

**Comment by ellatrix** [comment]
That's not a bad idea. I was initially hoping to just allow the user to scroll at least, because currently, you cannot scroll at all while you're dragging a block. What you're doing is essentially replacing mouse behaviour to scroll instead of move around the page. One problem I could see with this: if you already have the trackpad button pressed, and you which to cover a distance greater than the distance between where you pressed and the edge of the trackpad, you cannot simply let go to restart scrolling from the opposite side, because you'd drop the block.

Maybe it's better to start small and at least allow the user to scroll the page while dragging.

**Comment by folletto** [comment]
I'm not sure I get the trackpad issue. The new behaviour seems start moving when the mouse cursor moves from the initial position, and slows down when the cursor goes back to that initial position. So in theory the trackpad movement never reaches the edge. If anything, this scrolling behaviour seems requiring less trackpad space, as a higher velocity is reached in far less space then getting to the edge of the screen, no?

**Comment by ellatrix** [comment]
Ah, you are right, sorry about that! I had it playing out wrong in my head when thinking about possible problems. :)

I do like the interaction. What would happen if the block position is "live" updated? in the block list?

**Comment by folletto** [comment]
That's ok! That's why we discuss and cross check ❤️ 

> I do like the interaction. What would happen if the block position is "live" updated in the block list?

I would fear it would jump around too much, and I would worry what happens if one moves a very large block. Maybe still worth a try to see how it feels?

**Comment by ellatrix** [comment]
Yeah, I think I agree. I see this is what the Github project boards do, but these are much smaller items.

**Comment by mtias** [comment]
This looks good! It seems it could benefit from a larger area around the place where you drag where there is no scroll. From the video it seems like going back to the same position is tricky because it immediately starts scrolling the other way.

**Comment by gravityrail** [comment]
@mtias good suggestion. I can add it to this PR if you like

**Comment by chrisvanpatten** [comment]
This looks EXCELLENT. So so excited to see this — this has been a persistent micro-annoyance for some time :)

**Comment by gravityrail** [comment]
@mtias I just added a 50px non-scrolling region around the drag start point. Let me know how this feels for you. I don't have experience with Gutenberg so I don't know the best way to:

- get the first scrollable parent
- adapt this for horizontal scrolling situations
- do testing

Any pointers to people or examples that I could get this info from?

**Comment by ellatrix** [comment]
Let's try to do this for 5.5 :)

File: packages/block-editor/src/components/block-draggable/index.js [hunk 1]
```diff
@@ -5,7 +5,41 @@ import { Draggable } from '@wordpress/components';
...
+	}, SCROLL_INTERVAL_MS );
+}
+
+function getVerticalScrollParent( node ) {
+	if ( node === null ) {
+		return null;
+	}
+
+	// @todo - remove this hack and get a real reference to the scroll parent
+	return node.closest( '.interface-interface-skeleton__content' );
```
Comment (talldan) [inline packages/block-editor/src/components/block-draggable/index.js:33]: Important to replace this as the block editor can be used without the `.interface-interface-skeleton__content`.

Looks like the DOM package has a `getScrollContainer` function that should hopefully do the job. I found that by checking the `Typewriter` component, which also performs scrolling ... there might also be more reusable code in that component.

File: packages/components/src/draggable/index.js [hunk 2]
```diff
@@ -150,7 +154,9 @@ class Draggable extends Component {
 		document.body.classList.add( 'is-dragging-components-draggable' );
 		document.addEventListener( 'dragover', this.onDragOver );
 
-		this.props.setTimeout( onDragStart );
+		this.props.setTimeout(
+			onDragStart.bind( this, event.clientX, event.clientY )
```
Comment (talldan) [inline packages/components/src/draggable/index.js:158]: It might be good to pass the event object rather than the clientX and Y. 

Maybe also the same for `onDragEnd` so that the interface is consistent for each of the callbacks.

**Review by talldan — COMMENTED** [review]
Thanks for working on this 🎉

File: packages/block-editor/src/components/block-list/block-popover.js [hunk 3]
```diff
@@ -166,7 +178,7 @@ function BlockPopover( {
 			shouldAnchorIncludePadding
 			// Popover calculates the width once. Trigger a reset by remounting
 			// the component.
-			key={ shouldShowContextualToolbar }
+			key={ shouldShowContextualToolbar || isToolbarForced }
```
[the remark this answers is not in the document]
Comment (gravityrail) [reply packages/block-editor/src/components/block-list/block-popover.js:181]: Basically, if `isToolbarForced` isn't part of the key, then the component will still be unmounted unexpectedly when `shouldShowContextualToolbar` changes. 

I will push a change that explains this.

File: packages/block-editor/src/components/block-draggable/index.js [hunk 4]
```diff
@@ -60,13 +107,51 @@ const BlockDraggable = ( { children, clientIds, cloneClassname } ) => {
...
+					velocityY.current =
+						VELOCITY_MULTIPLIER *
+						( distanceY - SCROLL_INACTIVE_DISTANCE_PX );
+				} else if ( distanceY < -SCROLL_INACTIVE_DISTANCE_PX ) {
+					velocityY.current =
+						VELOCITY_MULTIPLIER *
+						( distanceY + SCROLL_INACTIVE_DISTANCE_PX );
+				} else {
+					velocityY.current = 0;
+				}
```
[the remark this answers is not in the document]
Comment (gravityrail) [reply packages/block-editor/src/components/block-draggable/index.js:139]: Those are great suggestions. Given that this patch is already considered to be an improvement, I would suggest we raise those as tickets for future work and get this merged. That way we can compare multiple strategies while not missing the 5.5 window.

File: packages/block-editor/src/components/block-draggable/index.js (hunk 1 above)
Comment (gravityrail) [reply packages/block-editor/src/components/block-draggable/index.js]: Great suggestion - thanks!

File: packages/components/src/draggable/index.js (hunk 2 above)
Comment (gravityrail) [reply packages/components/src/draggable/index.js:158]: Unfortunately I couldn't get that to work - something happens to the event object when I pass it, and it ends up with null clientX and clientY props. I don't know enough to about React, javascript or how browsers work to precisely know why. I would love for someone else to fix it because I agree - that API shape ain't the cleanest.

**Comment by jasmussen** [comment]
I'm seeing an issue in the master branch where the draggable clone disappears when you're dragging around the edge of the screen:

dragondrop

Does this PR address or improve that situation?

**Comment by ellatrix** [comment]
I'm fine with merging this sooner rather than later, iterate on it, and get some exposure in the master branch.

**Comment by gravityrail** [comment]
@jasmussen yes, this PR does address the disappearing clone issue.

**Comment by jasmussen** [comment]
Let's get this in 👌

**Review by youknowriad — COMMENTED** [review]
I'm testing on the demo post and when I drop an element being dragged, the editor scrolls to a completely different location.

File: packages/block-editor/src/components/block-draggable/index.js [hunk 5]
```diff
@@ -30,6 +64,14 @@ const BlockDraggable = ( { children, clientIds, cloneClassname } ) => {
 		[ clientIds ]
 	);
 	const isDragging = useRef( false );
+
+	// @todo - do this for horizontal scroll
+	const dragStartY = useRef( null );
+	const velocityY = useRef( null );
+	const scrollParentY = useRef( null );
+
+	const scrollEditorInterval = useRef( null );
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-draggable/index.js:73]: Do you think there's away to extract the logic into a dedicated hook as it's kind of obscures the code of the component. Would something like that (or close) work?

```
const [ onDragStart, onDragOver, onDragEnd ] = useScrollOnDrag()
```

File: packages/block-editor/src/components/block-list/block-popover.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (youknowriad) [reply packages/block-editor/src/components/block-list/block-popover.js:183]: @ellatrix Maybe we don't need this key anymore since now we compute recompute when the width/height changes in Popover?

File: packages/block-editor/src/components/block-draggable/index.js (hunk 5 above)
Comment (gravityrail) [reply packages/block-editor/src/components/block-draggable/index.js:73]: Maybe. I don't have a ton of bandwidth to refine this so you should feel free to mess around with it and propose a better-factored alternative.

**Comment by gravityrail** [comment]
> I'm testing on the demo post and when I drop an element being dragged, the editor scrolls to a completely different location.

@youknowriad do you have a sense of what the cause/solution of this bug is?

File: packages/components/src/draggable/index.js (hunk 2 above)
Comment (talldan) [reply packages/components/src/draggable/index.js:158]: @gravityrail It's possibly related to React's event pooling behavior given the event is being passed to a timeout:
https://reactjs.org/docs/events.html#event-pooling

I'll do some debugging.

Comment (talldan) [reply packages/components/src/draggable/index.js:158]: Yep, it was related to the event pooling.

I pushed a commit that makes the change. If you want to `git fetch` from this repo and then `git cherry-pick db82900` will bring it onto your branch.

File: packages/block-editor/src/components/block-draggable/index.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (talldan) [reply packages/block-editor/src/components/block-draggable/index.js:139]: @gravityrail I do still have concerns about usability, I feel like it's pretty easy to make the page start scrolling, but harder to make it stop in the right place.

Given others have said they're happy with the change, lets push on and address this as a follow-up 👍 

You mentioned that you don't have a lot of time to work on this, would it be better if I try out the suggestion in a follow-up PR?

**Comment by mtias** [comment]
> I'm testing on the demo post and when I drop an element being dragged, the editor scrolls to a completely different location.

This happens in master as well, I've run into it trying to demo some drag and drop features.

File: packages/block-editor/src/components/block-draggable/index.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (gravityrail) [reply packages/block-editor/src/components/block-draggable/index.js:139]: I would love it if you could do a follow up PR with your suggestions. Happy to pitch in and test.

File: packages/components/src/draggable/index.js (hunk 2 above)
Comment (gravityrail) [reply packages/components/src/draggable/index.js]: Done! Thanks for the patch 👍

**Review by talldan — APPROVED** [review]
I can't see anything blocking merge here, and the consensus from those testing seems to be good.

Thanks for all your work @gravityrail, it's great to get some much needed drag and drop improvements into WordPress 5.5.

I'm happy to work on a couple of follow-up PRs as @gravityrail mentioned not having much time:
- Encapsulate the scrolling behavior in a React Hook
- Try some minor adjustments to the scroll velocity

**Comment by ellatrix** [comment]
Thanks @gravityrail and @talldan! 🎉

**Comment by lelas** [comment]
Came here because drag and drop is a complete hit and miss now (Chrome + Firefox). As soon as I start dragging, scrolling begins and it is super difficult to drop a block in the right position. It's pure "Drag and _random_ drop". Headlines landing 4 blocks down, in the wrong columns, etc. etc. Incredible difficult to work with as-is.

**Comment by gravityrail** [comment]
Thanks for the report. Sounds like a regression. Scrolling is only meant to
begin once you have dragged towards the top or bottom of the screen, though
maybe there's something weird about how your browser computes screen sizes
that is throwing off the algorithm

What is your browser, operating system, and screen resolution? (With
versions)

**Comment by lelas** [comment]
> Thanks for the report. Sounds like a regression. Scrolling is only meant to begin once you have dragged towards the top or bottom of the screen, though maybe there's something weird about how your browser computes screen sizes that is throwing off the algorithm What is your browser, operating system, and screen resolution? (With versions)

Thanks for the swift response, Daniel. And apologies for cross posting. I commented on issue [24770](https://github.com/WordPress/gutenberg/issues/24770) afterwards and was going to delete my comment on this issue.

OS: Windows 10 Pro, version 10.0.19042, Build 19042
Browser: Chrome, version 89.0.4389.128 (Official Build) (64-bit)
Screen resolution: 3440 x 1440 Pixels
Browser window size: 1734 x 1417 (while experiencing these issues earlier)

I only briefly tried Firefox. Experienced issues there too, so continued in Chrome. I'll see if I experience the same problems on my laptop tomorrow -- to rule out issues with my Chrome installation and mouse settings.
