### PR TITLE
useMultiSelection: Avoid crashing editor when block refs aren't available

### LINKED ISSUE #34409: Drag’n’Drop inside a reusable block breaks the editor if the dragged content contains another reusable block
### Description

If you drag multiple blocks where at least one of these blocks is a reusable block into another reusable block, the editor breaks with the following error message:

```
getDeepestNode@http://localhost/wp/test-1234/wp-includes/js/dist/block-editor.js?ver=390a9f83b606a55e8b523c4d16bdb08c:38566:14
@http://localhost/wp/test-1234/wp-includes/js/dist/block-editor.js?ver=390a9f83b606a55e8b523c4d16bdb08c:38658:37
commitHookEffectListMount@http://localhost/wp/test-1234/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:19866:34
commitPassiveHookEffects@http://localhost/wp/test-1234/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:19904:38
callCallback@http://localhost/wp/test-1234/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:182:21
dispatchEvent@[native code]
invokeGuardedCallbackDev@http://localhost/wp/test-1234/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:231:31
invokeGuardedCallback@http://localhost/wp/test-1234/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:286:38
flushPassiveEffectsImpl@http://localhost/wp/test-1234/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:22988:32
unstable_runWithPriority@http://localhost/wp/test-1234/wp-includes/js/dist/vendor/react.js?ver=16.13.1:2685:26
performSyncWorkOnRoot@http://localhost/wp/test-1234/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:21872:24
performSyncWorkOnRoot@[native code]
@http://localhost/wp/test-1234/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:11224:34
unstable_runWithPriority@http://localhost/wp/test-1234/wp-includes/js/dist/vendor/react.js?ver=16.13.1:2685:26
flushSyncCallbackQueueImpl@http://localhost/wp/test-1234/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:11219:26
flushSyncCallbackQueue@http://localhost/wp/test-1234/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:11207:31
scheduleUpdateOnFiber@http://localhost/wp/test-1234/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:21334:33
dispatchAction@http://localhost/wp/test-1234/wp-includes/js/dist/vendor/react-dom.js?ver=16.13.1:15795:19
dispatchAction@[native code]
onStoreChange@http://localhost/wp/test-1234/wp-includes/js/dist/data.js?ver=7bfa3a673439e85e459d5ec92d30fdda:3393:20
onChange@http://localhost/wp/test-1234/wp-includes/js/dist/data.js?ver=7bfa3a673439e85e459d5ec92d30fdda:3409:22
@http://localhost/wp/test-1234/wp-includes/js/dist/data.js?ver=7bfa3a673439e85e459d5ec92d30fdda:2101:21
dispatch@http://localhost/wp/test-1234/wp-includes/js/dist/data.js?ver=7bfa3a673439e85e459d5ec92d30fdda:952:15
unhandledActionControl@http://localhost/wp/test-1234/wp-includes/js/dist/redux-routine.js?ver=7f20dbcdb5d5645c977063e356eb95cf:200:13
some@[native code]
next@http://localhost/wp/test-1234/wp-includes/js/dist/redux-routine.js?ver=7f20dbcdb5d5645c977063e356eb95cf:892:22
@http://localhost/wp/test-1234/wp-includes/js/dist/redux-routine.js?ver=7f20dbcdb5d5645c977063e356eb95cf:884:17
@http://localhost/wp/test-1234/wp-includes/js/dist/redux-routine.js?ver=7f20dbcdb5d5645c977063e356eb95cf:189:16
some@[native code]
next@http://localhost/wp/test-1234/wp-includes/js/dist/redux-routine.js?ver=7f20dbcdb5d5645c977063e356eb95cf:892:22
@http://localhost/wp/test-1234/wp-includes/js/dist/redux-routine.js?ver=7f20dbcdb5d5645c977063e356eb95cf:884:17
@http://localhost/wp/test-1234/wp-includes/js/dist/redux-routine.js?ver=7f20dbcdb5d5645c977063e356eb95cf:189:16
some@[native code]
next@http://localhost/wp/test-1234/wp-includes/js/dist/redux-routine.js?ver=7f20dbcdb5d5645c977063e356eb95cf:892:22
@http://localhost/wp/test-1234/wp-includes/js/dist/redux-routine.js?ver=7f20dbcdb5d5645c977063e356eb95cf:884:17
iterate@http://localhost/wp/test-1234/wp-includes/js/dist/redux-routine.js?ver=7f20dbcdb5d5645c977063e356eb95cf:897:24
runtime@http://localhost/wp/test-1234/wp-includes/js/dist/redux-routine.js?ver=7f20dbcdb5d5645c977063e356eb95cf:919:12
Promise@[native code]
@http://localhost/wp/test-1234/wp-includes/js/dist/redux-routine.js?ver=7f20dbcdb5d5645c977063e356eb95cf:207:31
@http://localhost/wp/test-1234/wp-includes/js/dist/data.js?ver=7bfa3a673439e85e459d5ec92d30fdda:2215:42
@http://localhost/wp/test-1234/wp-includes/js/dist/block-editor.js?ver=390a9f83b606a55e8b523c4d16bdb08c:24218:27
@http://localhost/wp/test-1234/wp-includes/js/dist/block-editor.js?ver=390a9f83b606a55e8b523c4d16bdb08c:24309:14
onDrop@http://localhost/wp/test-1234/wp-includes/js/dist/compose.js?ver=6284a4846a73f9c3e3ff2d7bd0b47be7:2033:26
```

### Step-by-step reproduction instructions

1. Create a paragraph and transform it to a reusable block
2. Create a new paragraph
3. Create two new paragraphs and transform both to a reusable block
4. Drag the first reusable block and the normal paragraph inside the reusable block

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1018979/131486638-e150bcb9-db62-463a-8859-6a66a1a2f78a.mp4

### Environment info

– WordPress 5.8
– No Gutenberg plugin installed
– Safari 14/Chrome 92
– macOS 11.5

### Pre-checks

- [X] I have searched the existing issues.
- [ ] I have tested with all plugins deactivated except Gutenberg.

### LINKED ISSUE #34631: Drag’n’Drop multiple blocks in a column breaks the editor
### Description

If you drag multiple blocks inside a column block, it results in a broken editor with the following error message:

```
pp@http://localhost/wp-clean/wp-includes/js/dist/block-editor.min.js?ver=390a9f83b606a55e8b523c4d16bdb08c:12:393567
@http://localhost/wp-clean/wp-includes/js/dist/block-editor.min.js?ver=390a9f83b606a55e8b523c4d16bdb08c:12:394549
Bh@http://localhost/wp-clean/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:126:457
Dj@http://localhost/wp-clean/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:162:478
unstable_runWithPriority@http://localhost/wp-clean/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25:261
Te@http://localhost/wp-clean/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146:81
Te@[native code]
@http://localhost/wp-clean/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61:69
unstable_runWithPriority@http://localhost/wp-clean/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25:261
Pg@http://localhost/wp-clean/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61:16
ha@http://localhost/wp-clean/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60:453
Ja@http://localhost/wp-clean/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:224:402
ch@http://localhost/wp-clean/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:93:81
ch@[native code]
e@http://localhost/wp-clean/wp-includes/js/dist/data.min.js?ver=7bfa3a673439e85e459d5ec92d30fdda:2:20892
t@http://localhost/wp-clean/wp-includes/js/dist/data.min.js?ver=7bfa3a673439e85e459d5ec92d30fdda:2:20959
@http://localhost/wp-clean/wp-includes/js/dist/data.min.js?ver=7bfa3a673439e85e459d5ec92d30fdda:2:15083
b@http://localhost/wp-clean/wp-includes/js/dist/data.min.js?ver=7bfa3a673439e85e459d5ec92d30fdda:2:8589
@http://localhost/wp-clean/wp-includes/js/dist/redux-routine.min.js?ver=7f20dbcdb5d5645c977063e356eb95cf:2:1354
some@[native code]
r@http://localhost/wp-clean/wp-includes/js/dist/redux-routine.min.js?ver=7f20dbcdb5d5645c977063e356eb95cf:2:9237
@http://localhost/wp-clean/wp-includes/js/dist/redux-routine.min.js?ver=7f20dbcdb5d5645c977063e356eb95cf:2:9187
@http://localhost/wp-clean/wp-includes/js/dist/redux-routine.min.js?ver=7f20dbcdb5d5645c977063e356eb95cf:2:1321
some@[native code]
r@http://localhost/wp-clean/wp-includes/js/dist/redux-routine.min.js?ver=7f20dbcdb5d5645c977063e356eb95cf:2:9237
@http://localhost/wp-clean/wp-includes/js/dist/redux-routine.min.js?ver=7f20dbcdb5d5645c977063e356eb95cf:2:9187
@http://localhost/wp-clean/wp-includes/js/dist/redux-routine.min.js?ver=7f20dbcdb5d5645c977063e356eb95cf:2:1321
some@[native code]
r@http://localhost/wp-clean/wp-includes/js/dist/redux-routine.min.js?ver=7f20dbcdb5d5645c977063e356eb95cf:2:9237
@http://localhost/wp-clean/wp-includes/js/dist/redux-routine.min.js?ver=7f20dbcdb5d5645c977063e356eb95cf:2:9187
c@http://localhost/wp-clean/wp-includes/js/dist/redux-routine.min.js?ver=7f20dbcdb5d5645c977063e356eb95cf:2:9288
t@http://localhost/wp-clean/wp-includes/js/dist/redux-routine.min.js?ver=7f20dbcdb5d5645c977063e356eb95cf:2:9544
Promise@[native code]
@http://localhost/wp-clean/wp-includes/js/dist/redux-routine.min.js?ver=7f20dbcdb5d5645c977063e356eb95cf:2:1416
@http://localhost/wp-clean/wp-includes/js/dist/data.min.js?ver=7bfa3a673439e85e459d5ec92d30fdda:2:13326
@http://localhost/wp-clean/wp-includes/js/dist/block-editor.min.js?ver=390a9f83b606a55e8b523c4d16bdb08c:12:239116
@http://localhost/wp-clean/wp-includes/js/dist/block-editor.min.js?ver=390a9f83b606a55e8b523c4d16bdb08c:12:239914
h@http://localhost/wp-clean/wp-includes/js/dist/compose.min.js?ver=6284a4846a73f9c3e3ff2d7bd0b47be7:2:13597
```

This symptom is similar to #34409.

### Step-by-step reproduction instructions

1. Create this structure:

```html
<!-- wp:heading -->
<h2>Überschrift</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Weit hinten, hinter den Wortbergen, fern der Länder Vokalien und Konsonantien leben die Blindtexte. Abgeschieden wohnen sie in Buchstabhausen an der Küste des Semantik, eines großen Sprachozeans. Ein kleines Bächlein namens Duden fließt durch ihren Ort und versorgt sie mit den nötigen Regelialien. Es ist ein paradiesmatisches Land, in dem einem gebratene Satzteile in den Mund fliegen. Nicht einmal von der allmächtigen Interpunktion werden die Blindtexte beherrscht – ein geradezu unorthographisches</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Weit hinten, hinter den Wortbergen, fern der Länder Vokalien und Konsonantien leben die Blindtexte. Abgeschieden wohnen sie in Buchstabhausen an der Küste des Semantik, eines großen Sprachozeans. Ein kleines Bächlein namens Duden fließt durch ihren Ort und versorgt sie mit den nötigen Regelialien. Es ist ein paradiesmatisches Land, in dem einem gebratene Satzteile in den Mund fliegen. Nicht einmal von der allmächtigen Interpunktion werden die Blindtexte beherrscht – ein geradezu unorthographisches</p>
<!-- /wp:paragraph -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
````

2. Select the two paragraph blocks and drag’n’drop them into the first column of the columns block.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1018979/132449887-f68d228f-3df0-4d78-8632-48cf02a6e753.mp4

### Environment info

– WordPress 5.8
– No Gutenberg plugin installed
– Safari 14/Chrome 92
– macOS 11.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #35128: Media & Text Block error while dragging inside it more than one block
### Description

"The editor has encountered an unexpected error" and the recovery attempt is not working. I've got this error with no plugins on WordPress version 5.8.1 and the Twenty Twenty-One theme.

### Step-by-step reproduction instructions

1. Add in the Block Editor some text or/and images (more the one block)
2. Add Media & Text block
3. Select several blocks and try to move them inside the content part of the Media & Text block.

### Screenshots, screen recording, code snippet

Demo: https://disk.yandex.ru/i/WTYH94aslSYTug

### Environment info

WordPress 5.8.1 and the Twenty Twenty-One 1.4 theme, no plugins.

I've checked in Google Chrome 93.0.4577.82 (Official Build) (64-bit) and Firefox 92.0 (64-bit).

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
When dragging multiple blocks into another block (inner blocks area), first and last block refs might not be available and cause the editor to crash.

This PR adds a guard clause for this scenario.

Fixes #34409.
Fixes #34631.
Fixes #35128.

## How has this been tested?
1. Create several blocks in a post.
2. Add "Media & Text" blocks.
3. Select and drag other blocks into the "Media & Text" content area.
4. Editor shouldn't crash with the following error.

```
Uncaught TypeError: Cannot read properties of null (reading 'firstChild') at getDeepestNode
```

## Example blocks
```
<!-- wp:media-text -->
<div class="wp-block-media-text alignwide is-stacked-on-mobile"><figure class="wp-block-media-text__media"></figure><div class="wp-block-media-text__content"><!-- wp:paragraph {"placeholder":"Content…","fontSize":"large"} -->
<p class="has-large-font-size"></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:media-text -->

<!-- wp:heading -->
<h2>Gutenberg</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><meta charset="utf-8">We call the new editor Gutenberg. The entire editing experience has been rebuilt for media rich pages and posts. Experience the flexibility that blocks will bring, whether you are building your first site, or write code for a living.</p>
<!-- /wp:paragraph -->
```

## Screenshots 
https://user-images.githubusercontent.com/240569/135058245-a14c20a1-9159-4854-bd3b-781604e766c5.mp4

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by Mamaduka** [comment]
Sorry for the ping, @ellatrix. Do you think we can use a different approach here?

**Review by gwwar — APPROVED** [review]
Thanks for looking into this @Mamaduka! I'm giving tentative approval. The code check here looks reasonable to me, but let's get a +1 from @ellatrix to make sure we're not missing other use cases.

Before:

https://user-images.githubusercontent.com/1270189/135894646-86ba9b22-f2ce-48ed-b3b6-cae6c62fdc12.mp4

After:

https://user-images.githubusercontent.com/1270189/135894889-cb862302-d025-4be3-a600-41b5bc4f0aee.mp4

File: packages/block-editor/src/components/writing-flow/use-multi-selection.js [hunk 1]
```diff
@@ -122,6 +122,12 @@ export default function useMultiSelection() {
 				return;
 			}
 
+			// The block refs might not be immediately available
+			// when dragging blocks into another block.
+			if ( ! startRef.current || ! endRef.current ) {
+				return;
```
Comment (ellatrix) [inline packages/block-editor/src/components/writing-flow/use-multi-selection.js:128]: It sounds like we'll need a state based alternative to `useBlockRef`. Updating the refs won't trigger a re-render here, so nothing will happen.

It's good enough for now though, if it prevents an error.

**Review by ellatrix — APPROVED** [review]

File: packages/block-editor/src/components/writing-flow/use-multi-selection.js (hunk 1 above)
Comment (Mamaduka) [reply packages/block-editor/src/components/writing-flow/use-multi-selection.js:128]: I tried using `useBlockElement`, which I think is the state-based alternative but was getting the same results.

**Comment by Mamaduka** [comment]
Thanks for the reviews @gwwar and @ellatrix 🙇
