### PR TITLE
Fix issue where block inserted in wrong place when selection is in nested block list, but root appender is used.

### LINKED ISSUE #23263: Trailing appender/inserter inserts blocks in the wrong place when Button or Navigation Link are selected
**Describe the bug**
The appender that appears at the end of the post inserts in the wrong place when particular types of block are selected. I've observed this with both Navigation Link in a Navigation Block and Button in a Buttons block.

It seems as though this inserter is 'scoped' to the selected block rather than the root context.

**To reproduce**
1. Start a new post
2. Add a buttons block
3. Make sure a button block in the buttons block is selected
4. Click the '+' appender that appears at the end of the post
5. Notice a button is inserted within the buttons block

**Expected behavior**
The inserter menu is displayed and a block can be added after the buttons block.

**Screenshots**
*Note that the tooltip says 'Add Button' on the appender at the bottom, and clicking it inserts a block in the wrong place:*
Screenshot 2020-06-18 at 3 47 04 pm

### PR DESCRIPTION
**Pull request by talldan**
## Description

Fixes #23263. This also seems to fix an issue where the trailing inserter is sometimes on the left and sometimes on the right.

When clicking the trailing root appender while selection is in an inner blocks list, the block will be inserted where selection is instead of at the root level.

I did some digging and it looks like the code was added in #22140 for the widgets screen, so this PR essentially reverted part of that. This change might break things there, but it's hard to tell what.

## How has this been tested?
1. Start a new post
2. Add a buttons block
3. Make sure a button block in the buttons block is selected
4. Click the '+' appender that appears at the end of the post
5. Notice a button is inserted within the buttons block

## Screenshots 
Screenshot 2020-06-18 at 3 47 04 pm

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-editor/src/components/inserter/index.js [hunk 1]
```diff
@@ -183,14 +183,11 @@ export default compose( [
 			getBlockRootClientId,
 			hasInserterItems,
 			__experimentalGetAllowedBlocks,
-			getBlockSelectionEnd,
 		} = select( 'core/block-editor' );
 		const { getBlockVariations } = select( 'core/blocks' );
 
 		rootClientId =
-			rootClientId ||
-			getBlockRootClientId( clientId || getBlockSelectionEnd() ) ||
```
Comment (talldan) [inline packages/block-editor/src/components/inserter/index.js:192]: The issue was that `rootClientId` and `clientId` are `undefined` for the root appender, so this fallback to `getBlockSelectionEnd` would result in blocks being inserted in the wrong place (and potentially the wrong inserter items displayed).

**Comment by ellatrix** [comment]
Would it be possible to add an e2e test?

**Comment by talldan** [comment]
@ellatrix E2E tests now added.

**Review by youknowriad — APPROVED** [review]
LGTM 👍

**Comment by youknowriad** [comment]
@talldan Looks like this PR broke the global inserter in the widgets screen. I'm not sure what's the best path forward to avoid both issues in both places.

**Comment by youknowriad** [comment]
Fix here https://github.com/WordPress/gutenberg/pull/24045
