### PR TITLE
FSE: Template resolution for new posts and pages

### LINKED ISSUE #27391: FSE Template resolution doesn't not work for auto-draft posts.
Say you have an auto-draft post with `id = 42`. Appending `_wp-find-template=true` to the post URL example: `http://localhost:8889/?p=42&_wp-find-template=true` is supposed to trigger the template resolution for that link and return the FSE template used to render that post. I would expect that by default, the returned template would be "single" or "post". Instead, it seems the algorithm is fetching the `404` template (which defaults to index if inexistant).

The current resolution algorithm is a hook on top of the frontend resolution that comes from Core and I believe this must fallback to 404 for a reason but it doesn't translate well for us. 

Also, ideally, template resolution should be extracted from Core into a nice low-level API we could work with `resolveTemplate( url )` instead of a hack on top of the frontend rendering.

I also believe having a dedicated REST API endpoint would be better than what we currently have. (hacking a regular page load and return JSON)

cc @WordPress/gutenberg-core @noahtallen @vindl

### PR DESCRIPTION
**Pull request by creativecoder**
## Description

Resolve the block based template when editing a new post or page.

The template resolution system makes a request like `/?page_id=1234&_wp-find-template=true`, depending on WP_Query to resolve a page or post using the `page_id` or `p` (post_id) in the query string. With new posts/pages, a placeholder post with the status `auto-draft` is created. But by default WP_Query will not resolve these posts, unless the query is specifically set to look for them (the post is removed from the query output on this line: https://github.com/WordPress/wordpress-develop/blob/abb27bc8daf03cebb5e39abad986177d77377416/src/wp-includes/class-wp-query.php#L3117)

Resolves #27391

## How has this been tested?

- Activate a block based theme, such as tt1-blocks
- Open a new post or page in the editor (including for custom post types)
- See that the template resolves in the Template settings (in the sidebar)

## Screenshots 

| **Before** | **After** |
| - | - |
| Screen Shot 2021-06-03 at 15 12 27 | Screen Shot 2021-06-03 at 15 12 45 |

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: lib/full-site-editing/template-loader.php [hunk 1]
```diff
@@ -236,3 +241,34 @@ function gutenberg_template_render_without_post_block_context( $context ) {
...
+	// Posts, including custom post types.
+	$p = isset( $wp_query->query['p'] ) ? $wp_query->query['p'] : null;
+
+	$post_id = $page_id ? $page_id : $p;
+	$post    = get_post( $post_id );
+
+	if (
+		$post &&
+		'auto-draft' === $post->post_status &&
+		current_user_can( 'edit_post', $post->ID )
```
Comment (creativecoder) [inline lib/full-site-editing/template-loader.php:270]: Adding a user capability check here, since it's normally run for non-public posts, when the post_status isn't provided by the query, see: https://github.com/WordPress/wordpress-develop/blob/abb27bc8daf03cebb5e39abad986177d77377416/src/wp-includes/class-wp-query.php#L3097

**Comment by youknowriad** [comment]
This closes #27391 right?

**Comment by creativecoder** [comment]
> This closes #27391 right?

@youknowriad Yes, thanks for finding that issue! I've linked it to the PR.

We probably want to have a separate issue to track solving some of the underlying concerns around template resolution described in that issue, e.g.

> Also, ideally, template resolution should be extracted from Core into a nice low-level API we could work with resolveTemplate( url ) instead of a hack on top of the frontend rendering.

But the use of a filter in this PR gets it working with the current template resolution system.

**Comment by youknowriad** [comment]
While testing this I noticed a couple related bugs that also exists in trunk I think.

Screen Shot 2021-06-10 at 9 05 33 AM

The "Default template" is actually the "Single Post" template there, we should probably hide the "Default template" from the list when we were able to resolve the current template. (This might be visible now because of this PR)

The other bug, is that the list there should probably exclude all the hierarchy templates like "index", "404" and only show the potential custom templates for current CPT. (This might be something that needs its own issue/PR)

**Review by youknowriad — APPROVED** [review]
I'd appreciate a second check from @ockham if possible. 

I think the duplicated "default template" and "single post" is something that we could consider solving in the current PR.

Regardless, this looks good to me, a bit hacky but there's no way around it in the plugin. A better fix could be done in Core directly.

**Review by ockham — APPROVED** [review]
LGTM too!
