### PR TITLE
Fix search block html handling for label and button text

### LINKED ISSUE #38644: Search Block: Formatting applied to button text encoded in frontend
### Description

If formatting is applied to the Search block button, it appears as encoded html tags in the frontend.

Reported here https://core.trac.wordpress.org/ticket/55102

### Step-by-step reproduction instructions

- Add a Search block
- Apply 'Bold' formatting to the button text via the block toolbar
- Save post and view in the frontend

### Screenshots, screen recording, code snippet

search-formatting-bug

### Environment info

WordPress 5.9, Gutenberg Trunk and TwentyTwentyTwo theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #38644

The search block was outputting escaped html in its label and button text, when it should have been outputting the tags.

In this PR I've swapped out `esc_html` for `wp_kses`.

## Testing Instructions
1. Add a search block to a post
2. Use formatting on the label and button text (e.g. bold, italic)
3. Preview the post

Expected - the formatting should be displayed correctly

#### Before
Screen Shot 2022-02-09 at 10 01 05 am

#### After
Screen Shot 2022-02-09 at 10 39 20 am

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [x] I've updated related schemas if appropriate.

### CODE REVIEW

File: packages/block-library/src/search/index.php [hunk 1]
```diff
@@ -42,16 +42,38 @@ function render_block_core_search( $attributes ) {
...
+			'src'   => array(),
+			'alt'   => array(),
+		),
+		's'      => array(),
+		'span'   => array(
+			'style' => array(),
+		),
+		'strong' => array(),
+	);
+
```
Comment (peterwilsoncc) [inline packages/block-library/src/search/index.php]:
```suggestion
	$wp_kses_formatting_tags = array_map( '_wp_add_global_attributes', $wp_kses_formatting_tags );

```

Will allow advanced users to add classes, IDs and other pretty safe attributes. See

https://github.com/WordPress/wordpress-develop/blob/f745cc551bb0a54d7df72ec97d23e3359c56048d/src/wp-includes/kses.php#L2559-L2571

**Review by peterwilsoncc — COMMENTED** [review]
Minor suggestion re globally allowed attributes. 

Any reason you're not using `wp_kses_post()` and the default set of tags? It saves maintaining a separate allow list if the spec gets more tags.

**Comment by talldan** [comment]
> Any reason you're not using wp_kses_post() and the default set of tags? It saves maintaining a separate allow list if the spec gets more tags.

I unashamedly copied the Navigation Link block's code. 😄 

It looks like that wasn't the best code to copy. I found this discussion about it - https://github.com/WordPress/gutenberg/pull/19477#issuecomment-572094711.

I'll make a separate PR to update any other blocks that might be using `wp_kses` that could be using `wp_kses_post`.

File: packages/block-library/src/search/index.php (hunk 1 above)
Comment (talldan) [reply packages/block-library/src/search/index.php]: I've switched it over to `wp_kses_post` now, and it looks like it implicitly has the global attributes:
https://github.com/WordPress/wordpress-develop/blob/f745cc551bb0a54d7df72ec97d23e3359c56048d/src/wp-includes/kses.php#L736

Thanks for the advice!

**Review by carolinan — APPROVED** [review]
