### PR TITLE
Fix nested pattern overrides and disable editing inner pattern

### LINKED ISSUE #58291: Patterns: nested pattern block with overrides will not load
### Description

If you have a synced pattern block with overrides and you nest another synced pattern with overrides within it the nested block causes an exception.

### Step-by-step reproduction instructions

- Add a synced pattern with overrides set on at least one block
- Create a second pattern with overrides and nest the first block in it
- In a post insert the second pattern and notice the nested pattern causes and exception

### Screenshots, screen recording, code snippet

Screenshot 2024-01-26 at 1 13 33 PM

### Environment info

WP 6.4.2 and GB trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by kevin940726**
## What?

Alternative to https://github.com/WordPress/gutenberg/pull/58359. Fix https://github.com/WordPress/gutenberg/issues/58291.

This PR does a few things:

1. Fix the error when editing patterns with nested inner patterns.
2. Disable editing the inner pattern even with overrides.
3. Refactor the logic a bit.
4. Disable editing the pattern with overrides if the pattern instance itself is disabled.

The first two are the same with #58359. This PR also fixes the fourth but it's just a nice-to-have.

## Why?

To prevent unexpected broken page. See #58291.

## How?

Just some small refactorings.

## Testing Instructions

Added an e2e test.

1. Follow the instructions in https://github.com/WordPress/gutenberg/issues/53705#issuecomment-1882305331 to create two synced patterns with overrides.
2. The "outer" pattern should include the "inner" pattern.
3. Insert the outer pattern in a post.
4. The overridable part in the outer pattern should be editable.
5. The overridable part in the inner pattern should not be editable.
6. Editing the outer pattern should be able to edit the overridable part of the inner pattern.

### CODE REVIEW

File: packages/block-library/src/block/edit.js [hunk 1]
```diff
@@ -215,10 +220,18 @@ export default function ReusableBlockEdit( {
 		  } )
 		: {};
 
-	useEffect(
-		() => setBlockEditMode( setBlockEditingMode, innerBlocks ),
-		[ innerBlocks, setBlockEditingMode ]
-	);
+	// Sync the editing mode of the pattern block with the inner blocks.
+	useEffect( () => {
+		const currentInnerBlocks = registry
```
Comment (kevin940726) [inline packages/block-library/src/block/edit.js]: Get the `innerBlocks` from the registry so that we don't have to put it in the dependency. That is, we don't have to reset the editing mode for every inner block whenever something changes as a small performance improvement. Since we shouldn't be able to add or remove blocks in the pattern instance, this should be fine. @glendaviesnz Do you spot any concerns?

File: packages/block-library/src/block/edit.js [hunk 2]
```diff
@@ -309,7 +322,6 @@ export default function ReusableBlockEdit( {
 	}, [ syncDerivedUpdates, patternClientId, registry, setAttributes ] );
 
 	const handleEditOriginal = ( event ) => {
-		setBlockEditMode( setBlockEditingMode, innerBlocks, 'default' );
```
Comment (kevin940726) [inline packages/block-library/src/block/edit.js:326]: This is removed because we no longer need it.

File: packages/block-library/src/block/edit.js (hunk 1 above)
Comment (kevin940726) [reply packages/block-library/src/block/edit.js]: Well, nvm. Seems like it's still needed for some reason 😅.

**Comment by kevin940726** [comment]
The e2e test failure is related to an existing known issue in the HTML Tag Processor API.

**Comment by glendaviesnz** [comment]
I thought I posted a comment on this last week, but don't see it now 🤔 This is testing well for me in the editor, but changes to the nested pattern overrides do not show in the frontend for me still - but I think you might still be working on that.

**Comment by kevin940726** [comment]
@glendaviesnz Could you test it again with the latest WP core? I just tested it and the e2e test passed on CI as well.

File: packages/block-library/src/block/edit.js [hunk 3]
```diff
@@ -134,6 +135,7 @@ function getContentValuesFromInnerBlocks( blocks, defaultValues ) {
 	/** @type {Record<string, { values: Record<string, unknown>}>} */
 	const content = {};
 	for ( const block of blocks ) {
+		if ( block.name === blockName ) continue;
```
Comment (talldan) [inline packages/block-library/src/block/edit.js]: I think this check could be clearer to the reader (I had to scroll up to find where `blockName` comes from to understand what value it has).

Perhaps calling it `patternBlockName` or adding a comment above this code could help.

File: packages/block-library/src/block/edit.js [hunk 4]
```diff
@@ -250,7 +260,9 @@ export default function ReusableBlockEdit( {
 	// Apply the initial overrides from the pattern block to the inner blocks.
 	useEffect( () => {
 		defaultContent.current = {};
-		const editingMode = getBlockEditingMode( patternClientId );
+		const { getBlockEditingMode } = registry.select( blockEditorStore );
```
Comment (talldan) [inline packages/block-library/src/block/edit.js]: Why use `registry.select` here over the alternatives?

It might be worth explaining it in a comment.

**Review by talldan — APPROVED** [review]
This is working really well for me, just a few small comments, but nothing major.

(edit: to confirm, I didn't have the issues @glendaviesnz noticed, and I used a fairly up-to-date verison of WordPress trunk)

File: packages/block-library/src/block/edit.js (hunk 4 above)
Comment (kevin940726) [reply packages/block-library/src/block/edit.js]: It's basically the same thing as the alternative (using `getBlockEditingMode` from `useSelect`). I don't mind switching over just to make it easier to understand though!

Comment (talldan) [reply packages/block-library/src/block/edit.js]: No real preference for me, just my curiosity.
