### PR TITLE
Components: Try to make the order of fills stable in regular slots

### LINKED ISSUE #28546: Pinned items should remember their place, at least the Settings sidebar should
#28526 fixed an issue where plugins that add a sidebar and pin items to the toolbar would show up on mobile. That was a regression from a past behavior where it was decided that pinned items are only accessible from the More menu on mobile (see also #14457).

While the issue is fixed, the solution isn't solid. If you unpin a plugin sidebar, then pin it again, it's now the first pinned item, which is problematic as the Settings cog should always be the first icon:

106005578-a4c9cb00-60b4-11eb-98c6-bd731ce38582

The fact that upon a page reload, the pinned item is back where it "should" be, suggests it's a bug.

There are some thoughts to ponder as far as solutions go:

- The cog could be moved out of the "pinned items" group, that would always make it first.
- However in https://github.com/WordPress/gutenberg/issues/27847 it's being explored how you can move from editing a post, to editing a template. When that shift happens, pinned items should fade out, and things such as the global styles panel could fade in. 

Both of those use cases need to be considered when finding a good solution.

### PR DESCRIPTION
**Pull request by gziolo**
## Description

This PR tries to resolve #28546.

> If you unpin a plugin sidebar, then pin it again, it's now the first pinned item, which is problematic as the Settings cog should always be the first icon:
> 
> 106005578-a4c9cb00-60b4-11eb-98c6-bd731ce38582
> 
> The fact that upon a page reload, the pinned item is back where it "should" be, suggests it's a bug.

## How has this been tested?

Register a few sidebar plugins that are pinnable, for example, plugins that offer integration: Yoast, Jetpack. Make sure that the order of pinned items remains the same when you pin and unpin them several times.

## Screenshots 

https://user-images.githubusercontent.com/699132/108962719-70c4d400-7679-11eb-83ec-8148d690550a.mov

bug

## Types of changes
Enhancement.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/components/src/slot-fill/test/__snapshots__/slot.js.snap [hunk 1]
```diff
@@ -155,13 +155,21 @@ exports[`Slot should render in expected order 1`] = `
   <div>
     first
     second
+    third
```
Comment (gziolo) [inline packages/components/src/slot-fill/test/__snapshots__/slot.js.snap:158]: This test fails at the moment with both the old implementation and the revised approach that ignores the concept of `occurrences`.

File: packages/plugins/src/components/plugin-area/index.js [hunk 2]
```diff
@@ -54,6 +55,12 @@ class PluginArea extends Component {
 		super( ...arguments );
 
 		this.setPlugins = this.setPlugins.bind( this );
+		this.memoizedContext = memoize( ( name, icon ) => {
```
Comment (gziolo) [inline packages/plugins/src/components/plugin-area/index.js:58]: While it decreases the number of rerenders it doesn't quite solve the issue when using the concept of `occurrences`.

**Comment by gziolo** [comment]
PR in the actual form resolves the issue reported by @jasmussen in #28546:
https://user-images.githubusercontent.com/699132/108961889-44f51e80-7678-11eb-8626-29fb831f7273.mov

It also works with dynamically registered plugins that declare a corresponding pinned item:

https://user-images.githubusercontent.com/699132/108962719-70c4d400-7679-11eb-83ec-8148d690550a.mov

**Comment by gziolo** [comment]
It looks like the order of fills in the inspector controls is predictable as well:

https://user-images.githubusercontent.com/699132/108964344-a4086280-767b-11eb-892b-cb846ed9d095.mov

All e2e tests pass.

@youknowriad – what do you think about the changes proposed? The flaw of the previous implementation is that as soon as a fill is unregistered, all other fills get their `occurrences` value unset. Given that the sort order of fills was based on the value of `occurrences` then all previously existing fills are automatically moved to the end of the list because any number has higher priority than `undefined`. I will record another demo for this behavior to better picture it.

**Comment by jasmussen** [comment]
Thanks so much for working on this! This is what I see:

bug

This appears to work excellently well for me!

**Comment by gziolo** [comment]
I did another test using the approach from #22027 where slots use `bubblesVirtually` prop set to `true`. Code:

```diff
diff --git a/packages/interface/src/components/pinned-items/index.js b/packages/interface/src/components/pinned-items/index.js
index 59fc700030..d15602414b 100644
--- a/packages/interface/src/components/pinned-items/index.js
+++ b/packages/interface/src/components/pinned-items/index.js
@@ -7,28 +7,32 @@ import classnames from 'classnames';
 /**
  * WordPress dependencies
  */
-import { Slot, Fill } from '@wordpress/components';
+import {
+	Slot,
+	Fill,
+	__experimentalUseSlot as useSlot,
+} from '@wordpress/components';
 
 function PinnedItems( { scope, ...props } ) {
 	return <Fill name={ `PinnedItems/${ scope }` } { ...props } />;
 }
 
 function PinnedItemsSlot( { scope, className, ...props } ) {
+	const name = `PinnedItems/${ scope }`;
+	const slot = useSlot( name );
+	const hasFills = Boolean( slot.fills?.length );
+
+	if ( ! hasFills ) {
+		return null;
+	}
+
 	return (
-		<Slot name={ `PinnedItems/${ scope }` } { ...props }>
-			{ ( fills ) =>
-				! isEmpty( fills ) && (
-					<div
-						className={ classnames(
-							className,
-							'interface-pinned-items'
-						) }
-					>
-						{ fills }
-					</div>
-				)
-			}
-		</Slot>
+		<Slot
+			{ ...props }
+			name={ name }
+			bubblesVirtually
+			className={ classnames( className, 'interface-pinned-items' ) }
+		/>
 	);
 }
```

It's better than in the main branch in terms of the order of pinned items that is predictable when registering a new plugin, However, the order changes when unpinning and pinning the sidebar, and goes back to the previous order when refreshing the page:

https://user-images.githubusercontent.com/699132/108978500-f0f33580-7689-11eb-81e3-3c931ae1acbd.mov

@diegohaz, any hints on how to ensure that the order of fills doesn't change when using `bubblesVirtually`? As far as I can tell, the biggest difference would be that when it doesn't bubble virtually, we always render the wrapping `Fill` for the pinned item but it returns `null` when it's unpinned (disabled) so that's why it is able to retain its order. As discussed with @youknowriad, we would prefer to migrate to `bubblesVirtually` for the web and leave the old implementation for React Native only wherever possible. Although as presented on the diff above it might be very difficult for the shared code. `PinnedItems` aren't used in RN code so far.

**Comment by youknowriad** [comment]
I guess for `bubblesVirtually` (portals), React might just append dom nodes when the "children" is not empty, so it seems our only way to keep the order in that case is to have a fallaback that render an empty div or something if the fill renders nothing https://github.com/WordPress/gutenberg/blob/master/packages/components/src/slot-fill/bubbles-virtually/fill.js#L38

**Comment by diegohaz** [comment]
Maintaining the order of elements with React Portal is tricky. There's a related discussion here: https://github.com/WordPress/gutenberg/pull/19242#discussion_r381152030

I was experimenting with the `key` prop here: https://codesandbox.io/s/keeping-react-portal-order-uk9xb?file=/src/App.js

Rendering an empty element as @youknowriad suggested looks like a good alternative too. But I think there will be some styling issues (`:last-child` and similar) and the `Fill` component couldn't be omitted.

**Comment by gziolo** [comment]
> Rendering an empty element as @youknowriad suggested looks like a good alternative too. But I think there will be some styling issues (`:last-child` and similar) and the `Fill` component couldn't be omitted for the hidden items.

I'm afraid there is more. There is logic in many places that render wrappers for the slot if there are no fills rendered. At the moment, when fills render nothing (something falsy like `null`) they are omitted from the list of fills and we can reliably count the number of fills with content. If we were to use a dummy element, we would need to account for it. For example, in the diff shared in https://github.com/WordPress/gutenberg/pull/29287#issuecomment-784936766, the following check would get more complex:
```js
const slot = useSlot( name );
const hasFills = Boolean( slot.fills?.length );
```

@youknowriad, how about we land this PR with the latest updates that contain unit tests for the slot that doesn't bubble virtually. They clarify how the slot behaves with fills that are always mounted and what happens when a fill gets unmounted.

In the long run, we should try to migrate all slots to bubble virtually as the default for the web, and use the other implementation for the mobile (RN).

File: packages/components/src/slot-fill/context.js [hunk 3]
```diff
@@ -109,19 +108,13 @@ class SlotFillProvider extends Component {
 		if ( this.slots[ name ] !== slotInstance ) {
 			return [];
 		}
-		return sortBy( this.fills[ name ], 'occurrence' );
```
Comment (gwwar) [inline packages/components/src/slot-fill/context.js:112]: What problem were we solving earlier that we needed to count instances?

File: packages/plugins/src/components/plugin-area/index.js (hunk 2 above)
Comment (gwwar) [reply packages/plugins/src/components/plugin-area/index.js:58]: Is this related to ordering, or did we notice a chance to reduce rerenders?

**Review by gwwar — COMMENTED** [review]
This is a fun one. I'm going to as a few basic questions, since I'm not familiar with this area. I also had trouble reproducing the original issue in trunk. Did I need to install more than 2 plugins?

File: packages/plugins/src/components/plugin-area/index.js (hunk 2 above)
Comment (gziolo) [reply packages/plugins/src/components/plugin-area/index.js:58]: It doesn't have any impact on the ordering but prevents excessive rerenders.

File: packages/components/src/slot-fill/context.js (hunk 3 above)
Comment (gziolo) [reply packages/components/src/slot-fill/context.js:112]: It's very difficult to tell even when you go through past commits and related discussions. There was definitely something that is covered with the unit test I updated. It was discussed in some of the PRs I studied but there wasn't a clear answer why this particular test needs to be kept:
https://github.com/WordPress/gutenberg/blob/9111ad51e3f123b0b60cc75666412991e834a46b/packages/components/src/slot-fill/test/slot.js#L170-L209

I extended this test to see how it behaves in the `trunk` branch, and I realized that the test is too specific and doesn't cover more complex cases. The updated version of the test produces the following order that is far from perfect:

```
<div>
    third
    first (rerendered)
    second
    fourth (new)
</div>
```

The code of the test:
https://github.com/WordPress/gutenberg/blob/255928e066cf530d6ea6e62ee71814cf45eb780d/packages/components/src/slot-fill/test/slot.js#L231-L273

**Comment by gziolo** [comment]
> This is a fun one. I'm going to as a few basic questions, since I'm not familiar with this area. I also had trouble reproducing the original issue in trunk. Did I need to install more than 2 plugins?

Yes, it's a very complex piece of software and crucial to how many things are architected 😄 I did most of my tests using `wp-env` and the test instance of WordPress that you should have at `http://localhost:8889`. There is a plugin that registers two pinnable sidebars:
Screen Shot 2021-03-02 at 08 18 56

You can also install some plugins like @jasmussen: Jetpack and Yoast. I would say you need at least 3-4 different plugins to notice this behavior.

File: packages/components/src/slot-fill/context.js (hunk 3 above)
Comment (gwwar) [reply packages/components/src/slot-fill/context.js:112]: Curious, if we can't remember, it does make sense to update the expectation here

**Review by gwwar — APPROVED** [review]
Thanks for looking into this @gziolo! Giving tentative approval here, since I didn't spot any issues while smoke testing in a few places. Getting another +1 review for a confidence check would be helpful.

This is a little bit on the riskier side to land, since we don't remember the original reason for counting fill instances. I'm in favor of removing the instance counting if it doesn't actually fix a case. If we decide to land, maybe pick a time where folks can keep an eye on any behavior differences.

File: packages/components/src/slot-fill/context.js (hunk 3 above)
Comment (diegohaz) [reply packages/components/src/slot-fill/context.js:112]: <blockquote>

```
<div>
    third
    first (rerendered)
    second
    fourth (new)
</div>
```

</blockquote>

@gziolo Does this happen on the main branch or only on this PR? I think rendering `Fill`s conditionally (instead of just omitting its contents) like in that test is a pretty common thing.

Comment (gziolo) [reply packages/components/src/slot-fill/context.js:112]: @diegohaz, I copied the result from the main branch. I wrongly assumed that it's easy to find the result in the diff section for the same test, that is in this branch:

```
<div>
     second
     third
     first (rerendered)
     fourth (new)
</div>
```

It's slightly better as more predictable, but it's still far from perfect. This is also why fills for `PinnedItems` are optimized to be always rendered, and they conditionally show its content. This way, the order doesn't change in my testing, and as I can tell, it can be confirmed by others.

**Comment by gziolo** [comment]
I'm merging this PR hoping that it will help to better align the behavior between two versions of SlotFill implementation. Let's observe if it doesn't cause any regressions in the block toolbar or block inspector.

Most importantly this PR fixes the issue with the unstable order of pinned items that is very confusing for users as reported by @jasmussen.

**Comment by jasmussen** [comment]
Thank you 🚀

**Comment by gziolo** [comment]
I left a message on WordPress Slack about this change (link requires registration at https://make.wordpress.org/chat/):
https://wordpress.slack.com/archives/C02QB2JS7/p1614854420062600
