### PR TITLE
Fix: Fixed styling tab not opening on themes without style variations on mobile & desktop

### LINKED ISSUE #67532: Styles: top level styles does not open on mobile for sites using themes without style variations
When a block theme doesn't have style variations, the newer experience for top level styles in the Site Editor does not open on mobile when using GB 19.7 and GB nightly. 

**Steps to replicate**

1. Use a block theme without style variations, like https://wordpress.org/themes/onyxpulse/
2. Ensure you're using at least GB 19.7.
3. Open this on your phone or use browser tools to pull up on mobile. 
4. Open Appearance > Editor
5. Try to select Styles. Notice it doesn't respond.
6. Switch to a theme with style variations, like https://wordpress.org/themes/twentytwentyfive/
7. Open Appearance > Editor
8. Try to select Styles and notice it properly opens up the Styles panel.

**Videos**

With GB 19.7 and OnyxPulse:

https://github.com/user-attachments/assets/f1bcfef2-0702-4df8-afd0-c0f50a653fbe

With GB nightly and OnyxPulse:

https://github.com/user-attachments/assets/439b99af-ae3b-4678-bd30-cbf3d0e7b7fd

cc @tellthemachines @aaroncampbell @ramonjd @talldan as you all have been working on this!

### PR DESCRIPTION
**Pull request by Mayank-Tripathi32**
resolves #67532

## What?
This PR adds to="/styles" and aria-current={ name === 'styles' } to SidebarNavigationItem to ensure the Styles tab works correctly on mobile devices.

## Why?
When a block theme lacks global style variations, the top-level Styles panel in the Site Editor does not open on mobile when using Gutenberg 19.7 or the nightly build. This PR resolves the issue to ensure consistent behavior across all themes.

## How?
The conditional rendering for SidebarNavigationItem was updated. The onClick logic was removed with the introduction of the Styles panel in `2a18aae3768da80f94e437c16e8d56e5a9a45e03 `, but it made it work only for themes with global variations. This patch ensures the SidebarNavigationItem opens the Styles panel for all themes, regardless of variations.
 
 ```JS
 if ( hasGlobalStyleVariations ) {
		return (
			<SidebarNavigationItem
				{ ...props }
				to="/styles"
				uid="global-styles-navigation-item"
				aria-current={ name === 'styles' }
			/>
		);
	}
	return <SidebarNavigationItem { ...props } to="/styles" aria-current={ name === 'styles' } />;
```

## Testing Instructions

1. Use a block theme without style variations, like https://wordpress.org/themes/onyxpulse/
2. Ensure you're using at least GB 19.7.
3. Open this on your phone or use browser tools to pull up on mobile.
4. Open Appearance > Editor
5. Try to select Styles and notice it properly opens up the Styles panel.
6. Switch to a theme with style variations, like https://wordpress.org/themes/twentytwentyfive/
7. Open Appearance > Editor
8. Try to select Styles and notice it properly opens up the Styles panel.

## Screenshots or screencast 

https://github.com/user-attachments/assets/f7a696b5-926c-4484-ae6e-8f1496007962

### CODE REVIEW

**Comment by Mayank-Tripathi32** [comment]
@annezazu  @supernovia Please have a look at PR. Thank you

**Comment by annezazu** [comment]
Thanks so much for working on this! It works great for me in my testing. I can't speak to the code though.

**Comment by annezazu** [comment]
Video for good measure: 

https://github.com/user-attachments/assets/c92a29be-69db-4b46-89e5-19d56672d8a8

File: packages/edit-site/src/components/sidebar-navigation-screen-global-styles/index.js [hunk 1]
```diff
@@ -41,7 +41,13 @@ export function SidebarNavigationItemGlobalStyles( props ) {
 			/>
 		);
 	}
-	return <SidebarNavigationItem { ...props } />;
+	return (
```
Comment (ramonjd) [inline packages/edit-site/src/components/sidebar-navigation-screen-global-styles/index.js:44]: Thanks for getting this PR up! I'll test further later today.

I'm wondering if we need the `hasGlobalStyleVariations` condition at all. 🤔 

E.g., 

```jsx
export function SidebarNavigationItemGlobalStyles( props ) {
	const { name } = useLocation();
	return (
		<SidebarNavigationItem
			{ ...props }
			to="/styles"
			uid="global-styles-navigation-item"
			aria-current={ name === 'styles' }
		/>
	);
}
```

I'll investigate later. 

Also, not related to this PR, but there's a persistent JS error for sidebar items on mobile: https://github.com/WordPress/gutenberg/pull/67467#issuecomment-2513472204

Just mentioning in case you see it and are wondering 👍🏻

Comment (Mayank-Tripathi32) [reply packages/edit-site/src/components/sidebar-navigation-screen-global-styles/index.js:44]: I thought about removing the condition too. But after looking at the original code, I saw that the condition was there and the uid was missing in the default return. To keep the code consistent and working as expected, I decided to leave it as is.

Comment (ramonjd) [reply packages/edit-site/src/components/sidebar-navigation-screen-global-styles/index.js:44]: Ah, thanks for the context. That's a good point. Anyway, I'll test as soon as I can today and we'll aim to get the fix in ASAP.

Comment (ramonjd) [reply packages/edit-site/src/components/sidebar-navigation-screen-global-styles/index.js:44]: I still think a lot of this code is superfluous and doubles up on things.

For example, most of the props could be passed to `SidebarNavigationItemGlobalStyles` in [MainSidebarNavigationContent](https://github.com/WordPress/gutenberg/blob/40b865333994a9cc1f239d0f4cfd817be138d4b4/packages/edit-site/src/components/sidebar-navigation-screen-main/index.js#L30-L30).

```jsx
			<SidebarNavigationItemGlobalStyles
				to="/styles"
				uid="global-styles-navigation-item"
				icon={ styles }
			>
				{ __( 'Styles' ) }
			</SidebarNavigationItemGlobalStyles>
```

With the same effect.

Removing the condition doesn't have any side effects as far as I can see, but I agree that we can take the cautious route to fix the bug. 

I can get a follow up to clean up the code and we can get folks who have commented on [recent changes](https://github.com/WordPress/gutenberg/commit/c9a5cab0e2e9063054ed4f299bde734a242e3794#diff-13a4b1af1602640c2d5f796fc64e29f6756168a5299458db6b09f3584cf34024R38) to routing here to chime in.

cc @youknowriad and @t-hamano for visibility

**Review by ramonjd — APPROVED** [review]
Fixes the issue for me, thanks a lot @Mayank-Tripathi32 

I'll add a clean up PR as a follow up as I suspect that the props can be tidied up and we don't need the `hasGlobalStyleVariations` condition.

**Comment by ramonjd** [comment]
Now I remember 😄 The style panel used to _only_ contain variations. 

See: https://github.com/WordPress/gutenberg/pull/50573

Since https://github.com/WordPress/gutenberg/pull/65619 it's no longer the case.

I'll throw up a clean up PR

**Comment by ramonjd** [comment]
> I'll throw up a clean up PR

https://github.com/WordPress/gutenberg/pull/67545
