### PR TITLE
Fix issue where resetBlocks can result in an incorrect block selection

### LINKED ISSUE #21445: Resetting blocks can cause an incorrect selection state
**Describe the bug**
When the resetBlocks action is dispatched, selection state isn't updated accordingly, which can cause an incorrect selection state.

This can cause issues when using the top toolbar option, a ghost toolbar for the since removed block is displayed, which when clicked results in an error being thrown.

This was first noticed in the Navigation Menu page that's being built - https://github.com/WordPress/gutenberg/pull/21340#pullrequestreview-386228844.

In that page, the entire list of blocks can be changed by the `BlockEditorProvider`, which internally uses the `resetBlocks` action.

**To reproduce**
1. Enable the Top Toolbar option
2. Add a paragraph with some text to a post and ensure it stays selected so that the block toolbar is shown at the top
3. In the browser dev tools open up the console and execute the following to reset blocks: 
```js
wp.data.dispatch('core/block-editor').resetBlocks([]);
```
4. Observe in the top toolbar the block movers and block settings menu are still displayed.
5. Click the settings menu. Notice that the editor crashes.

**Expected behavior**
The toolbar is no longer shown if a block no longer exists (and internally, selection state is cleaned up appropriately.)

**Additional Info**
I originally tried a fix for this in https://github.com/WordPress/gutenberg/pull/21371.

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #21445. Alternative to #21371. Bug discovered while working on #21340.

When RESET_BLOCKS is dispatched and results in the selected blocks being replaced, selection state in the store is not cleared, which can cause the top toolbar to be shown for a block that no longer exists.

<strike>This PR converts the resetBlocks action into a generator action, and adds additional logic for resetting selection when needed.</strike>

This PR adds a higher order reducer for selection that updates the selection state as necessary when RESET_BLOCKS is dispatched.

## How has this been tested?
Unit tests added.

Steps to reproduce:
1. Enable the Top Toolbar option
2. Add a paragraph with some text to a post and ensure it stays selected so that the block toolbar is shown at the top
3. In the browser dev tools open up the console and execute the following to reset blocks: 
```js
wp.data.dispatch('core/block-editor').resetBlocks([]);
```
4. Observe in the top toolbar the block toolbar is no longer displayed. Previously the movers and more menu were displayed and clicking the more menu caused the editor to crash.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by draganescu** [comment]
@dan I tested this and it works perfectly! It solves the bug and the code looks like a good improvement. Why is this still a draft?

File: packages/block-editor/src/store/actions.js [hunk 1]
```diff
@@ -37,19 +37,48 @@ function* ensureDefaultBlock() {
...
+		'core/block-editor',
+		'getBlock',
+		selectionEndClientId
+	);
+
+	// If there was a selected block, but it no longer exists after
+	// RESET_BLOCKS, clear the block selection state.
+	if ( ! selectionStartBlock || ! selectionEndBlock ) {
+		yield clearSelectedBlock();
+	}
```
Comment (youknowriad) [inline packages/block-editor/src/store/actions.js:81]: Do you think it'd be better to solve this with a Higher-order reducer instead to avoid two dispatches?

Comment (talldan) [reply packages/block-editor/src/store/actions.js:81]: @youknowriad Initially looked into making it part of the reducer using the `selection` helper that's already there (https://github.com/WordPress/gutenberg/pull/21371), but the trouble I had is that `selectionStart` and `selectionEnd` are two separate reducers, but the code needs to access both bits of state to determine if selection should be cleared.

Not sure if that's something that can be solved at reducer level without combining the two reducers.

**Comment by talldan** [comment]
@draganescu I forgot about this one a little bit!

I need to look at why the tests are failing really before it's ready for review.

File: packages/block-editor/src/store/actions.js (hunk 1 above)
Comment (youknowriad) [reply packages/block-editor/src/store/actions.js:81]: @talldan yes it can we have a few instances of this `withBlockReset` is one example.

Comment (talldan) [reply packages/block-editor/src/store/actions.js:81]: Ah, ok great, will take a look 👍

**Comment by talldan** [comment]
I've updated this to use a higher order reducer as suggested. It's quite a big diff now as the `selectionStart` and `selectionEnd` reducers are combined, but they're very routine changes.

File: packages/block-editor/src/store/reducer.js [hunk 2]
```diff
@@ -1237,54 +1237,105 @@ function selection( state = {}, action ) {
...
+)( {
+	/**
+	 * Reducer returning the block selection's start.
+	 *
+	 * @param {Object} state  Current state.
+	 * @param {Object} action Dispatched action.
+	 *
+	 * @return {Object} Updated state.
+	 */
+	selectionStart( state = {}, action ) {
```
Comment (youknowriad) [inline packages/block-editor/src/store/reducer.js:1297]: Do you think it should be just "start" and "end"  to avoid the redundancy

**Review by youknowriad — APPROVED** [review]
Left a small comment but the code looks good.

File: packages/block-editor/src/store/reducer.js (hunk 2 above)
Comment (talldan) [reply packages/block-editor/src/store/reducer.js]: @youknowriad I've tried that out in ead6d1a. It also allowed for refactoring the higher-order reducer into the main selection reducer.

I don't think it resulted in much reduced repetition, but I like that the code is a little easier to follow now that there's no higher order reducer.
