### PR TITLE
Split the comment

### LINKED ISSUE #12139: Translator Comments
**Describe the bug**
While translating the latest strings from Gutenberg 4.5 I found that there's a case where the translator comment in the code isn't parsed properly so doesn't appear on translate.wordpress.org.

This may be related to #9464 but doesn't seem to be an exact match.

Code - https://plugins.trac.wordpress.org/browser/gutenberg/trunk/lib/client-assets.php#L1215
Translate Row - https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6925481&filters%5Btranslation_id%5D=59162362

I feel the issue is probably the translator comment in the code has text in the comment string prior to 'Translators:' prefix. May just need the comment split into two with the 'Translators:' comment in it's own comment block.

**To Reproduce**
1. Go to translate.wordpress.org, specifically this example;
https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6925481&filters%5Btranslation_id%5D=59162362
2. Note there's no translator comment on the row
3. Open the reference;
https://plugins.trac.wordpress.org/browser/gutenberg/trunk/lib/client-assets.php#L1215
4. Note there's a translator comment in the code.

**Expected behavior**
The translators comment should appear in translate.wordpress.org similar to the other one for Noto Serif font;
screen shot 2018-11-20 at 3 33 33 pm

**Screenshots**
Here's the translator row which is missing the comment;
screen shot 2018-11-20 at 3 34 21 pm

Here's the code which shows the comment;
screen shot 2018-11-20 at 3 34 31 pm

**Additional context**
Gutenberg Version - 4.5

### PR DESCRIPTION
**Pull request by garretthyder**
## Description
Separate the comment so translator comment is in it's own block.

## How has this been tested?
This is a change to comments so aside from loading to make sure nothing broke the test will be done as part of parsing.

## Types of changes
Bug fix #12139 corrects the translator comments for i18n

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

File: lib/client-assets.php [hunk 1]
```diff
@@ -1211,8 +1211,8 @@ function gutenberg_editor_scripts_and_styles( $hook ) {
 		),
 	);
 
+	// Set a locale specific default font.
 	/*
-	 * Set a locale specific default font.
 	 * Translators: Use this to specify the CSS font family for the default font
```
Comment (swissspidy) [inline lib/client-assets.php]: PHPCS currently fails: `Empty line required before block comment`.

The `Set a locale specific default font.` comment is a bit redundant as the translator comment kinda explains that anyway.

I'd simply remove it.

Also, I'd write the translator comment like this:

```php
/* Translators: Use this to specify the CSS font family for the default font. */
```

Comment (garrett-eclipse) [reply lib/client-assets.php]: Thanks @swissspidy make complete sense thanks, I've adjusted accordingly.

**Review by swissspidy — APPROVED** [review]
