### PR TITLE
[Writing Flow]: Try to fix multi-selection with `shift+click`

### LINKED ISSUE #40636: Selecting multiple non-text blocks using the shift key is no longer possible
### Description

Previously, you could hold down the shift key and select multiple blocks at once. This still works if you "start" with a paragraph or similar text-based block. However, if you try and select two non-text blocks using the shift key, such as two images, it is no longer possible. This is a bit hard to explain, so see the video below. 

I believe this may be related to the new functionality that allows you to select text across multiple blocks. As such, we should really try and get this resolved for 6.0. 

### Step-by-step reproduction instructions

1. Use the latest version of Gutenberg and 6.0 Beta 3 and Twenty Twenty-Two
2. Add two image blocks to the Editor
3. Hold down the shift key and try to select both, it **won't** work
4. Now revert to 5.9.3 and disable Gutenberg
5. Add two image blocks to the Editor
3. Hold down the shift key and try to select both, it **will** work

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/4832319/165428766-24e596fc-d895-4ead-b34d-958b7c5c1b7a.mp4

### Environment info

- WordPress 6.0 Beta 3
- Gutenberg 13.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/40636

From the issue:
>Previously, you could hold down the shift key and select multiple blocks at once. This still works if you "start" with a paragraph or similar text-based block. However, if you try and select two non-text blocks using the shift key, such as two images, it is no longer possible.

Partial selection across blocks is handled mostly with the help of [getSelection API](https://developer.mozilla.org/en-US/docs/Web/API/Window/getSelection). This creates some problems for blocks that have no text selection(ex Spacer) and things get even more complicated when we have blocks that have a Placeholder state, which actually contains text nodes. See @priethor 's [comment](https://github.com/WordPress/gutenberg/issues/40636#issuecomment-1110900870):
>One extra use test case:
>Partially select text in a paragraph -> Shift+click on an Image/Cover block that has an image -> it doesn't work
Partially select text in a paragraph -> Shift+click on an empty Image/Cover block -> it works

## How?

At first I tried adding some changes in [use-click-selection](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/writing-flow/use-click-selection.js), but couldn't make it work well at all, because selection changes in other events after that, and there are even [more nuances](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/writing-flow/use-selection-observer.js#L149) to that for handling RichText selection first, before `use-selection-observer` kicks in.

I don't think this solution is perfect and handles all cases, and that's why suggestions and feedback is more than welcome.  I have added comments in the code that will be helpful hopefully 😄 

## Testing Instructions
1. Add various blocks both text-based like paragraphs, headings, etc.. and others like Image, Cover, Spacer. Also you could group some blocks.
2. Make sure in testing to also have the list view open to see the actual selected blocks from the store
3. Try different selections by holding `shift+click`

#### Before

https://user-images.githubusercontent.com/16275880/165758559-738da5af-0bc1-4ad6-9d0a-57a4b5274ab9.mov

#### After

https://user-images.githubusercontent.com/16275880/165758573-f4592f07-57cb-473c-bb0d-622b87e867bb.mov

### CODE REVIEW

File: packages/block-editor/src/components/writing-flow/use-click-selection.js [hunk 1]
```diff
@@ -11,10 +11,9 @@ import { store as blockEditorStore } from '../../store';
 import { getBlockClientId } from '../../utils/dom';
 
 export default function useClickSelection() {
-	const { multiSelect, selectBlock } = useDispatch( blockEditorStore );
+	const { selectBlock } = useDispatch( blockEditorStore );
 	const {
 		isSelectionEnabled,
-		getBlockParents,
```
Comment (ntsekouras) [inline packages/block-editor/src/components/writing-flow/use-click-selection.js:17]: These changes are unrelated - just some cleaning up.

**Review by priethor — APPROVED** [review]
Thanks for the quick fix, @ntsekouras ❤️ 

I tested the use cases mentioned in #40636 and the issue is solved. I'm approving from a functional perspective but a technical review would be appreciated.

**Comment by ntsekouras** [comment]
Thanks for testing @priethor! A technical review is required here for sure! 😄

Also in the end of reviews I'll add some e2e tests.

File: packages/block-editor/src/components/writing-flow/use-selection-observer.js [hunk 2]
```diff
@@ -76,43 +76,80 @@ export default function useSelectionObserver() {
...
 					extractSelectionStartNode( selection )
 				);
-				const endClientId = getBlockClientId(
+				let endClientId = getBlockClientId(
 					extractSelectionEndNode( selection )
 				);
+				// If the selection has changed and we had pressed `shift+click`,
+				// we need to check if in an element that doesn't support
+				// selection has been clicked.
+				if ( event.shiftKey ) {
```
Comment (talldan) [inline packages/block-editor/src/components/writing-flow/use-selection-observer.js]: I wonder if this code should also check that it was a mouse event. While `shiftKey` doesn't seem to be defined for `selectionchange` events, I'm pretty sure it can be for other keyboard events. Event payloads can also be quite inconsistent between browsers.

File: packages/block-editor/src/components/writing-flow/use-selection-observer.js [hunk 3]
```diff
@@ -76,43 +76,80 @@ export default function useSelectionObserver() {
...
 				// contentEditable wrapper.
-				if ( ! selection.rangeCount || selection.isCollapsed ) {
+				if ( ! selection.rangeCount ) {
+					setContentEditableWrapper( node, false );
+					return;
+				}
+				// If selection is collapsed and we haven't used `shift+click`,
+				// end multi selection and disable the contentEditable wrapper.
+				// We have to check about `shift+click` case because elements
+				// that doesn't support selection might be involved, and we might
```
Comment (talldan) [inline packages/block-editor/src/components/writing-flow/use-selection-observer.js]: I think it'd be good to clarify this is just about text selection:
```suggestion
				// that don't support text selection might be involved, and we might
```

File: packages/block-editor/src/components/writing-flow/use-selection-observer.js [hunk 4]
```diff
@@ -76,43 +76,80 @@ export default function useSelectionObserver() {
...
+				let startClientId = getBlockClientId(
 					extractSelectionStartNode( selection )
 				);
-				const endClientId = getBlockClientId(
+				let endClientId = getBlockClientId(
 					extractSelectionEndNode( selection )
 				);
+				// If the selection has changed and we had pressed `shift+click`,
+				// we need to check if in an element that doesn't support
+				// selection has been clicked.
```
Comment (talldan) [inline packages/block-editor/src/components/writing-flow/use-selection-observer.js]:
```suggestion
				// text selection has been clicked.
```

File: packages/block-editor/src/components/writing-flow/use-selection-observer.js [hunk 5]
```diff
@@ -76,43 +76,80 @@ export default function useSelectionObserver() {
...
+					// Handle the case when we have a non-selectable block
+					// selected and click another one.
+					if ( startClientId !== selectedClientId ) {
+						startClientId = selectedClientId;
+					}
+				}
 
-				// If the selection did not involve a block, return early.
-				if ( clientId === undefined && endClientId === undefined ) {
+				const isSingularSelection = startClientId === endClientId;
```
Comment (talldan) [inline packages/block-editor/src/components/writing-flow/use-selection-observer.js]: I think this line can still go below the following `if` statement, like it was in `trunk`.

**Review by talldan — APPROVED** [review]
This works well, thanks for fixing this one!

I left a few comments but they're all very minor and none are blockers.

In testing I noticed a few other multi-selection bugs, but they all seem to be in `trunk` so I'll make new issues.

File: packages/block-editor/src/components/writing-flow/use-selection-observer.js (hunk 2 above)
Comment (ntsekouras) [reply packages/block-editor/src/components/writing-flow/use-selection-observer.js]: I added an extra check about being a `mouseup` event for now and let's see how this goes 😄

**Comment by ndiego** [comment]
This is great, thanks for fixing so quickly @ntsekouras!

**Comment by adamziel** [comment]
I cherry picked this change into `wp/6.0` branch to be included in WordPress 6.0 Beta 4 on Monday: 687bd1cb80

File: packages/block-editor/src/components/writing-flow/use-selection-observer.js [hunk 6]
```diff
@@ -76,43 +76,81 @@ export default function useSelectionObserver() {
...
+						! endClientId ||
+						focusNodeIsNonSelectable
+					) {
+						endClientId = clickedClientId;
+					}
+					// Handle the case when we have a non-selectable block
+					// selected and click another one.
+					if ( startClientId !== selectedClientId ) {
+						startClientId = selectedClientId;
+					}
```
Comment (mcsf) [inline packages/block-editor/src/components/writing-flow/use-selection-observer.js:135]: This block could just as well be refactored to:

```js
startClientId = selectedClientId;
```

… as there is no cost nor any side effect to the assignment.

And this brings me to asking the broader question: couldn't we simplify the logic here into something more straightforward, with fewer conditionals, as close as possible to:

```js
if ( isClickShift ) { // This is the only branching that matters
  startClientId = getBlockSelectionStart();
  endClientId = getBlockClientId( event.target );
}
```

wdyt, @ntsekouras?
