### PR TITLE
Pasting: Fix performance regression due to removeWindowsFragments

### LINKED ISSUE #41826: It takes more than 20 seconds to paste not-so-large HTML document.
### Description

Copy-pasting a **not-so-large** HTML document takes more than **20 seconds**.

[**A same issue has already been reported**](https://github.com/WordPress/gutenberg/issues/14079#issuecomment-1156516305
), but I have created a new issue to **isolate the problem**.

### Step-by-step reproduction instructions

1. Create new wordpress site by Flywheel Local (wordpress version is 6.0)
2. Install gutenberg plugin and activate it. (gutenberg version is 13.4.0)
3. Goto https://docusaurus.io/docs and copy the document
4. Create new post and paste the copied HTML document

### Screenshots, screen recording, code snippet

The following gif is when copy-and-pasting https://docusaurus.io/docs content.

### Environment info

- Wordpress version: 6.0
- Gutenberg version: 13.4.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by mcsf**
Fixes #41826.
Alternative to #41881.

In RichText's `usePasteHandler`, `removeWindowsFragments` was running two `String#replace` with regular expressions made computationally expensive due to the use of `.*` and the `s / dotAll` flag, resulting in severe performance degradations when handling larger strings of HTML.

The solution is to manually trim the strings via a combination of `String#indexOf` and `String#substring`.

## Testing Instructions
See parent issue, #41826, confirm that pasting is now reasonably fast (~ 1s) for the attached sample.

### CODE REVIEW

File: packages/block-editor/src/components/rich-text/use-paste-handler.js [hunk 1]
```diff
@@ -254,17 +254,26 @@ export function usePasteHandler( props ) {
...
  *
  * @param {string} html the html to be normalized
  * @return {string} the normalized html
  */
 function removeWindowsFragments( html ) {
-	const startReg = /.*<!--StartFragment-->/s;
-	const endReg = /<!--EndFragment-->.*/s;
+	const startStr = '<!--StartFragment-->';
+	const startIdx = html.indexOf( startStr );
+	if ( startIdx > -1 ) {
```
Comment (ntsekouras) [inline packages/block-editor/src/components/rich-text/use-paste-handler.js:266]: I think we could return early here if no match found.

**Review by ntsekouras — APPROVED** [review]

**Comment by Mamaduka** [comment]
The failing Static Analysis checks should be resolved now - https://github.com/WordPress/gutenberg/pull/41916.

**Comment by mcsf** [comment]
> The failing Static Analysis checks should be resolved now - #41916.

Thanks! Rebased.

**Comment by getdave** [comment]
Thank you. TIL something important 🙇‍♂️

**Comment by mtias** [comment]
Thanks for the fix! It might be worth commenting within the function that this is a hot path and can affect pasting performance for all, hence the importance of being extra lean in operations.

**Comment by adamziel** [comment]
I just cherry-picked this PR to the wp/6.0 branch to get it included in the next release: ae46fef373
