### PR TITLE
Block Menu: Fix arrow navigation

### LINKED ISSUE #5245: Blocks "More Options" menu: arrow navigation doesn't work on all the menu items
When opening the blocks "More Options" menu, it is possible to use the arrow keys to navigate through the items in the menu.

However, the content changes depending on the context and it's made of more than one component. Seems arrow navigation works only on the first items in the menu, I guess they're the ones from the "main" component, while it doesn't work at all on the additional items:

screen shot 2018-02-25 at 11 25 46

Easier way to reproduce:
- go in Add New post
- click the ellipsis button in the default block
- use the arrow keys to navigate the menu items
- arrows navigation works only on the first 4 items

### PR DESCRIPTION
**Pull request by youknowriad**
closes #5245

This PR fixes the arrow navigation in the block settings menu by making all the button children of the menu (which is recommended). 

**Testing instructions**

 - Repeat the instructions in #5245

### CODE REVIEW

File: editor/components/block-settings-menu/block-transformations.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ function BlockTransformations( { blocks, small = false, onTransform, onClick = n
 		return null;
 	}
 	return (
-		<div className="editor-block-settings-menu__section">
+		<Fragment>
```
Comment (jorgefilipecosta) [inline editor/components/block-settings-menu/block-transformations.js]: Minor: Is there a special reason for having a fragment here and not use array return?

**Review by jorgefilipecosta — COMMENTED** [review]
Hi @youknowriad, right now it is possible to use arrow navigation on the transforms, so this PR fixes that part 👍 
But there is still a bug that makes arrow navigation not work as expected. If we have 2 blocks and we select one block, then we open the menu of a non selected block, it is impossible to use arrow navigation in that case, because the first item does not get the focus as expected.
This PR does not cause regressions so I think we can merge it and attack the other problem as separate work.

File: editor/components/block-settings-menu/block-transformations.js (hunk 1 above)
Comment (youknowriad) [reply editor/components/block-settings-menu/block-transformations.js]: I prefer Fragment to avoid having to add keys and commas :)

**Comment by youknowriad** [comment]
I know about this bug @jorgefilipecosta I think it's tracked in a separate issue though

File: editor/components/block-settings-menu/block-transformations.js (hunk 1 above)
Comment (jorgefilipecosta) [reply editor/components/block-settings-menu/block-transformations.js]: Ok it makes sense :)

Comment (youknowriad) [reply editor/components/block-settings-menu/block-transformations.js]: Oh I guess, your right here, since it's a just a map inside, we could drop it entirely 👍

Comment (youknowriad) [reply editor/components/block-settings-menu/block-transformations.js]: Initially, the separator was here :)

**Comment by jorgefilipecosta** [comment]
Yes, there is a separate issue for that problem, but as the screen of https://github.com/WordPress/gutenberg/issues/5245 does not show the focus I thought it also referred the autofocus problem, but it looks like it does not refer to that problem and just refers the problem of not being able to use arrows in transforms.

**Review by jorgefilipecosta — APPROVED** [review]
Fixes the problem described in https://github.com/WordPress/gutenberg/issues/5245.
And it looks like it does not cause regressions.
Arrow navigation may still be affected by https://github.com/WordPress/gutenberg/issues/5107.

**Comment by jorgefilipecosta** [comment]
I found a small problem in the last version 
image.

File: editor/components/block-settings-menu/index.js [hunk 2]
```diff
@@ -66,6 +66,7 @@ function BlockSettingsMenu( {
 						<BlockRemoveButton key="remove" uids={ uids } />,
 						<BlockDuplicateButton key="duplicate" uids={ uids } rootUID={ rootUID } />,
 						count === 1 && <ReusableBlockSettings key="reusable-block" uid={ uids[ 0 ] } onToggle={ onClose } />,
+						<div key="separator" className="editor-block-settings-menu__separator" />,
```
Comment (jorgefilipecosta) [inline editor/components/block-settings-menu/index.js]: We need to hide this line if no possible transformations exist maybe easier if we do it inside block-transformations.js.

**Review by jorgefilipecosta — DISMISSED** [review]

**Comment by youknowriad** [comment]
@jorgefilipecosta What's the problem, not seeing anything strange. Also there's no difference with the first code aside the removal of Fragment which doesn't have any incidence.

**Comment by youknowriad** [comment]
Gotcha, yep updating

**Review by jorgefilipecosta — APPROVED** [review]
Seems to work fine 👍 Thank you for the fixes.

**Comment by jorgefilipecosta** [comment]
> Also there's no difference with the first code aside the removal of Fragment which doesn't have any incidence.

yes @youknowriad you are right, the problem was not related to the fragment change it was me that did not catch it in the first review and just caught it when retesting after the seconda changes.
Anyway it is working fine now :)
