### PR TITLE
Image Block: Hide controls while in upload state

### LINKED ISSUE #25805: Image block: Duplicate copies of media files created in library
**Describe the bug**
Changing alignment of an image block while the image is still uploading, causes duplicate copies of the image to be created in the media library. This does not happen if one waits for the upload to complete before changing alignment settings.

**To reproduce**
1. Create a new post/page
2. Drag an image file from your computer into the editor
3. While the image is still uploading, change the alignment for the image block
4. Exit the editor and view the media library
5. There will be two copies of the image, one with `-1` appended to the file name.

**Expected behavior**
For just one copy of the image file I just uploaded to appear in the library

**Screenshots**
Screen Capture on 2020-10-03 at 09-45-17

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Happens with both the default editor, and with Gutenberg 9.1.0

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.6
 - Browser Firefox
 - Version 81.0

**Additional context**
Discovered and reported by a WordPress.com user in https://wordpress.com/forums/topic/wordpress-uploads-double-images/

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
If a user changes alignment while an image is uploading, it remounts the component and triggers a duplicate upload.

Ideally, we would cancel previous media upload via the `useEffect` cleanup function.

Fixes #25805.

## How has this been tested?
1. Throttle network to 3G via DevTools.
2. Drag the image to the editor.
3. Image Block and Inspector shouldn't be visible while an image is uploading.

## Types of changes
Bugfix (kind of).

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by youknowriad — COMMENTED** [review]
This doesn't sound like a satisfying solution for me (at least not until we explore alternative solutions :P), we're just hiding some controls, what If I switch to code editor mode and come back to visual, there are so many factors that could trigger a remount.

Is it possible to cancel the request on "unmount"?

**Comment by Mamaduka** [comment]
I agree. This PR solves one case, but there can be more.

> Is it possible to cancel the request on "unmount"?

Not sure. The `mediaUpload` doesn't return anything. We can try [`AbortController`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController).

**Comment by Mamaduka** [comment]
@youknowriad I did some initial testing, and I think we can use `AbortController` to cancel upload on unmount. But this would require changes to [`uploadMedia`](https://github.com/WordPress/gutenberg/blob/trunk/packages/media-utils/src/utils/upload-media.js).

Should I go ahead and update PR with PoC?

**Comment by youknowriad** [comment]
yes, sounds good to me. Let's try that.

**Comment by Mamaduka** [comment]
Updated the code to use `AbortController` and cancel the upload request on component unmount.

While this technically cancels the request, I think it still happens too late to prevent actual image upload. So we still end up with duplicated images.

I pushed changes just in case anyone has alternative ideas on how to handle cancelation.

P.S. I've removed my initial change to make this easier to test.

File: packages/block-library/src/image/edit.js [hunk 1]
```diff
@@ -224,32 +229,49 @@ export function ImageEdit( {
...
+			return;
+		}
+
+		const abortController = new AbortController();
 
-		if ( file ) {
-			mediaUpload( {
-				filesList: [ file ],
-				onFileChange: ( [ img ] ) => {
+		mediaUpload( {
```
Comment (youknowriad) [inline packages/block-library/src/image/edit.js]: Should we return the abortController instead of having it be an argument?

**Comment by Mamaduka** [comment]
Hi, @youknowriad

I did some more testing. I don't think `AbortController` can be effective for canceling image uploads or with `POST` requests in general.

**Problem:** Most of the time, when we cancel a request, it is too late. The server has already received data, and the only thing cancelation does is that we don't receive a response.

I'm not 100% sure what alternative solutions are here, but having the ability to cancel uploads can be helpful.

Should I revert to my original solution and create a new issue for future discussion on this subject?

**Comment by youknowriad** [comment]
I wonder if we should  just accept this bug for now, it's not the easiest one to reproduce and I don't want to us to introduce complex things because of it. The original approach could be acceptable as a stop gap measure. We might want to comment properly to explain the logic but seeing the toolbar disappear and then appear might not be a great UX though.

**Comment by Mamaduka** [comment]
> I wonder if we should just accept this bug for now, it's not the easiest one to reproduce and I don't want to us to introduce complex things because of it.

Makes sense.

Personally, I don't expect image editing tools to be available while an image is still uploading.

**Comment by paaljoachim** [comment]
Perhaps @mcsf Miguel and @ockham Bernie might have some additional input they can share.
Thanks!

**Comment by mcsf** [comment]
> Perhaps Miguel and Bernie might have some additional input they can share.
> Thanks!

Unnecessary; George and Riad have got it covered.

**Comment by Mamaduka** [comment]
I've reverted `AbortController` changes since it's wasn't working, and in case anyone wants to test the original solution.

**Review by youknowriad — APPROVED** [review]
I think that's a fine solution given the constraints, we might add an inline comment explaining the reasoning.

**Comment by Mamaduka** [comment]
Thanks, @youknowriad

Added the inline comment and will merge this once all checks are finished.
