### PR TITLE
Sibling inserter: Fix the inserter position for floated blocks

### LINKED ISSUE #4142: Left & Right aligned Button Blocks don't show Insert Block icon
## Issue Overview
At the bottom of each block is supposed to be an Insert Block icon, used for inserting a block immediately after the selected block. Left and Right Aligned Button blocks don't have this icon.

gutenberg-buttonalignmentblock2

## Steps to Reproduce (for bugs)
1. Insert Button Block
2. Align Left or Right
3. Attempt to add a block imediately after Button Block using the Insert Block icon.

## Expected Behavior
Every block is supposed to have an Insert Block icon at the bottom of the block.
 
## Current Behavior
When a Button block is left or right aligned, the Insert Block icon is missing.

_Gutenberg 1.9.1
Firefox Quantum 57.0.1 (64-bit)
WordPress 4.9.1_

### PR DESCRIPTION
**Pull request by youknowriad**
closes #4142  

This PR fixes the sibling inserter for floated blocks by moving the sibling inserter inside the `BlockEdit` component, that way we can position it relative to its container.

**Testing instructions**

 - Add a block button
 - Alight it right
 - Check that the inserter is showing up when you hover the border bottom of the block.

### CODE REVIEW

**Comment by jasmussen** [comment]
Impressive! This is working well for me. Can't speak for the code but experience wise this seems to fix it.

Does it also fix some of the float issues @gziolo reported? (Not that it has to) — #3870 #3869 #3868

**Comment by youknowriad** [comment]
Unfortunately, it doesn't solve these issues. These will be much harder to solve since it's related to how "floating" works. We may have to think about "workarounds"

**Comment by jasmussen** [comment]
> Unfortunately, it doesn't solve these issues. These will be much harder to solve since it's related to how "floating" works. We may have to think about "workarounds"

Yep, they're still on my todo list, and someting I'd like to think about over the holidays. Perhaps we need to go back to a fixed-width main column, and use JavaScript to make full-wide images :(

**Comment by youknowriad** [comment]
> Perhaps we need to go back to a fixed-width main column, and use JavaScript to make full-wide images :(

I agree with this, we need a fixed-width main column.

File: editor/components/block-list/block.js [hunk 1]
```diff
@@ -439,6 +440,7 @@ export class BlockListBlock extends Component {
 					{ showUI && <BlockMobileToolbar uid={ block.uid } /> }
 				</div>
 				{ !! error && <BlockCrashWarning /> }
+				<BlockListSiblingInserter uid={ block.uid } />
```
Comment (jorgefilipecosta) [inline editor/components/block-list/block.js]: I am not certain moving sibling inserter inside block-list will not have the undesirable side effect of making sibling inserter unusable for locked blocks cc: @gziolo.

**Review by jorgefilipecosta — COMMENTED** [review]
I left a concern related to locked blocks. But other than that everything works as expected in my tests and I did not find any problem. Nice work 👍

File: editor/components/block-list/block.js (hunk 1 above)
Comment (youknowriad) [reply editor/components/block-list/block.js]: What do you mean by "locked blocks"?

Comment (youknowriad) [reply editor/components/block-list/block.js]: I guess you mean "template locking". In which case, this change doesn't change the current behavior which is: The `Inserter` component does not show anything if the template is locked. This component is included in the `BlockListSiblingInserter` component.

Comment (jorgefilipecosta) [reply editor/components/block-list/block.js]: In PR https://github.com/WordPress/gutenberg/pull/3493 BlockListBlock was made extensible to allow the creation of Frozen/locked blocks. Blocks that are temporarily not editable because of co-editing for example. It looks like the hook allows us to "change" BlockListBlock, so in places that use this hook, we may be disabling sibling inserter.

Comment (youknowriad) [reply editor/components/block-list/block.js]: Good point! If that means the hook should be "smarter" or the hook should target `BlockEdit` instead?

Comment (jorgefilipecosta) [reply editor/components/block-list/block.js]: In accordance with the conversation on PR https://github.com/WordPress/gutenberg/pull/3493 adding the hook to BlockEdit does not fit the needs, because it would not be possible to lock the toolbar or the block transform mechanism. So we can make the hook smarter or we can try to add a component that wraps BlockListBlock and the sibling inserter.

File: editor/components/block-list/index.js [hunk 2]
```diff
@@ -211,20 +211,16 @@ class BlockList extends Component {
 		return (
 			<div>
 				{ !! blocks.length && <BlockListSiblingInserter /> }
-				{ flatMap( blocks, ( uid ) => [
+				{ flatMap( blocks, ( uid ) => (
```
Comment (aduth) [inline editor/components/block-list/index.js]: This can be `map` now instead of `flatMap` if we're just returning a single value from the mapper.

File: editor/components/block-list/block.js (hunk 1 above)
Comment (gziolo) [reply editor/components/block-list/block.js]: @jorgefilipecosta thanks for raising this issue. Yes, it might be a bit inconvenient, but I'm sure we can find workarounds :) Don't treat it as a blocker as we can figure out solutions later.

> So we can make the hook smarter or we can try to add a component that wraps BlockListBlock and the sibling inserter.

It seems like a wrapping div would work perfectly fine. I like the idea. I didn't think about it too much though :)

**Comment by youknowriad** [comment]
Ok this should be ready to go, merging
