### PR TITLE
[Tiny PR] Verse: save line breaks as characters

### LINKED ISSUE #18364: Verse: Block example should be a single string for translators to handle
## Context

See context for _block examples_:
* Design issue #17488
* API implementation #17124
* First examples #17493 

## Issue

Currently, the example for the Verse block is made up of distinct translatable strings:

https://github.com/WordPress/gutenberg/blob/59da6ed091222a0e3e9cabe188b37bfe92b77205/packages/block-library/src/verse/index.js#L24-L33

This harms the translating experience greatly, as becomes clear by looking up any of its verses in GlotPress (see [Portuguese (Portugal)](https://translate.wordpress.org/projects/wp/dev/pt/default/?filters%5Bterm%5D=great+god&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) for instance):
* Translators need to find verses separately
* Translators need to make sense of them and understand the context of each string
* Translators are bound to translating each verse independently

As a consequence, **translators lose the freedom to _adapt_** rather than translate, i.e. free themselves from a verse-by-verse translation — which is a difficult to do and of low value to users of that locale — and possibly provide a comparable block example that is fitting of the locale at hand, such as a local poem.

## Solutions

The motivation to keep verses separate may have come from the fact that they need to be stitched with HTML, namely the line breaks (`<br>`). In the broader Gutenberg codebase, this is an internalisation challenge requiring element interpolation that is tracked in #9846.

However, when dealing with block examples, we are in the unusual case of translating not UI, not _code_ in a stricter sense, but serialised data representing user content. Thus, the example strings can in fact contain HTML elements. In fact, I'd argue that this is the most correct thing to do, as it fits the idea that we're letting content be translated.

**Questions:** What care should be exercised in such a scenario? Should we beware of ill-intentioned translators seeking to inject unexpected content?

/cc @swissspidy and anyone you'd like to add to the conversation

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Same as #14653, but for verse.
Related: #18099.
Fixes #18364.

This should be the behaviour when using `pre`, which makes me wonder if we should build it in `RichText` if the `tagName` is set to `pre`. Thoughts? I do like to keep complexity out of `RichText`, but maybe it just makes more sense.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/block-library/src/verse/edit.js [hunk 1]
```diff
@@ -28,10 +28,14 @@ export default function VerseEdit( { attributes, setAttributes, className, merge
 			</BlockControls>
 			<RichText
 				tagName="pre"
-				value={ content }
+				// Ensure line breaks are normalised to HTML.
+				value={ content.replace( /\n/g, '<br>' ) }
```
Comment (ellatrix) [inline packages/block-library/src/verse/edit.js]: Note that this is the same as #14653, see the preformatted block.

**Comment by mcsf** [comment]
Needs rebase. :)

**Comment by ellatrix** [comment]
Rebased. :)

File: packages/block-library/src/verse/index.js [hunk 2]
```diff
@@ -23,8 +23,7 @@ export const settings = {
 	icon,
 	example: {
 		attributes: {
-			// translators: Sample content for the Verse block. Can be replaced with a locale-appropriate work.
```
Comment (mcsf) [inline packages/block-library/src/verse/index.js]: Can you preserve the `translators` note? Possibly even add that "\n" indicates line breaks?

**Review by mcsf — CHANGES_REQUESTED** [review]
Hm, the changes are interfering with block merges. In the following comparison, I just press <kbd>Backspace</kbd> in an empty Paragraph below a Verse:

`<br>`-separated | `\n`-separated
-|-
gut-1 | gut-2

**Comment by ellatrix** [comment]
@mcsf Yes, this problem was noticed in the preformatted block as well, and it's been fixed in #18656. I'll update this PR to use the new prop.

File: packages/block-library/src/verse/index.js (hunk 2 above)
Comment (ellatrix) [reply packages/block-library/src/verse/index.js]: Whoops, sorry. Might have been a bad rebase.

**Review by mcsf — APPROVED** [review]
Thanks!
