### PR TITLE
Interactivity API: fix property modification from inherited context two or more levels above

### LINKED ISSUE #65623: Interactivity API: Context not updating properly from radio button click with nested contexts
### Description

This is a bit of a weird one, but hopefully the minimal repro example below makes sense. I'm trying to update the context of a parent from a radio button change. In the example below, you will see that when changing a radio button, `context.trigger` will not update to `radio`, but `context.filters.radioValue` will update correctly. However, when doing the exact same action from the button, `context.trigger` updates correctly.

If you remove the dummy context (the one with "somethingNew" => "example") it suddenly works fine for both the radio and the button. However, in my real world usage I do need the values in that context, so deleting it is not an option.

### Step-by-step reproduction instructions

view.js
```js
import { store, getContext, getElement } from '@wordpress/interactivity';

store( 'playground', {
	state: {
		get isRadioChecked() {
			const context = getContext();
			const { filters, value } = context;
			return value === filters.radioValue;
		},
	},
	actions: {
		onRadioChange( event ) {
			const context = getContext();
			context.trigger = 'radio';
			context.filters.radioValue = event.target.value;
		},
		onButtonClick() {
			const context = getContext();
			context.trigger = 'reset';
			context.filters.radioValue = '';
		},
	},
	callbacks: {
		*logRadioValue() {
			const context = getContext();
			const { trigger, filters } = context;
			console.log( trigger );
			console.log( filters.radioValue );
		},
	},
} );
```

render.php
```php
<?php
$context = [
	'trigger' => 'page-load',
	'filters' => [
		'radioValue' => 'two',
	],
];

$radios = [
	[
		'value' => 'one',
		'label' => 'One',
	],
	[
		'value' => 'two',
		'label' => 'Two',
	],
	[
		'value' => 'three',
		'label' => 'Three',
	],
];
?>

<div
	data-wp-interactive="playground"
	data-wp-watch="callbacks.logRadioValue"
	<?php echo wp_interactivity_data_wp_context( $context, 'playground' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
	<?php echo get_block_wrapper_attributes(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
>
	<div <?php echo wp_interactivity_data_wp_context( [ 'somethingNew' => 'example' ], 'playground' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>>
		<?php foreach ( $radios as $radio ) : ?>
			<label>
				<input
					type="radio"
					name="radio"
					value="<?php echo esc_attr( $radio['value'] ); ?>"
					data-wp-bind--checked="state.isRadioChecked"
					data-wp-on-async--click="actions.onRadioChange"
					<?php
					echo wp_interactivity_data_wp_context(
						[
							'value' => $radio['value'],
							'playground',
						]
					); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
					?>
				>
				<?php echo esc_html( $radio['label'] ); ?>
			</label>
		<?php endforeach; ?>

		<button data-wp-on-async--click="actions.onButtonClick">Reset</button>
	</div>
</div>
```

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 6.6.2
- Gutenberg 19.2.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by DAreRodz**
## What?

The Interactivity API context can be nested, and inherited properties are supposed to be modified in the contexts where they are defined. This was not the case for properties inherited from contexts defined two or more levels above.

More info at https://github.com/WordPress/gutenberg/issues/65623#issuecomment-2464519158.

Fixes #65623.

This PR also fixes a bug in the Navigation block that seems related to the bug fix; see https://github.com/WordPress/gutenberg/pull/66872#issuecomment-2470585837.

## How?

Applying the proposed fix mentioned in https://github.com/WordPress/gutenberg/issues/65623#issuecomment-2464560001.

## Testing Instructions

You can follow the "Step-by-step reproduction instructions" at https://github.com/WordPress/gutenberg/issues/65623#issue-2546194860 to reproduce the issue and check it disappears with the bug fix.

I've added unit tests to ensure the issue has been addressed and prevent it from happening again.

### CODE REVIEW

File: packages/interactivity/src/proxies/context.ts [hunk 1]
```diff
@@ -38,6 +38,9 @@ const contextHandlers: ProxyHandler< object > = {
 	getOwnPropertyDescriptor: ( target, key ) =>
 		descriptor( target, key ) ||
 		descriptor( contextObjectToFallback.get( target ), key ),
+	has: ( target, key ) =>
+		Reflect.has( target, key ) ||
+		Reflect.has( contextObjectToFallback.get( target ), key ),
```
Comment (sirreal) [inline packages/interactivity/src/proxies/context.ts:43]: https://github.com/WordPress/gutenberg/blob/636710ba98514345009d7aab2de1dc5471c69a2c/packages/interactivity/src/proxies/context.ts#L27

> And the problem arises when the `key in fallback` expression is evaluated.
>
> I think the solution is to define a [trap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/has) for the [[HasProperty]] internal method, returning true for inherited properties. We already have a trap for [[OwnPropertyKeys]] that returns the list of "own keys," which includes the inherited properties as well.
(from https://github.com/WordPress/gutenberg/issues/65623#issuecomment-2464519158)

This is confusing, but I think it makes sense. It _does_ fix the issue in my testing. Are there tests already for the case where the value should be set on fallback?

With all the overrides to object behavior with proxies, it probably makes sense to add more special behaviors.

I was confused a bit since the `has` proxy changes the behavior of the `in` operator. It appears that it would change the behavior of the lines above, however those lines are on the unproxied objects so that usage of `in` is not impacted. Is that correct?

**Review by sirreal — APPROVED** [review]

**Comment by sirreal** [comment]
Reset to draft, @DAreRodz is investigating the navigation block issue: https://github.com/WordPress/gutenberg/issues/65623#issuecomment-2464897993

**Comment by DAreRodz** [comment]
Okay, this is interesting. The failing test passes without the fix, but the tested behavior (tab outside a nested submenu) doesn't work when the case is manually reproduced, both _with_ and _without_ the fix. 🤔

**Comment by DAreRodz** [comment]
I've found it! It was the `modal` property inside submenu contexts. The property should be defined explicitly to prevent it from being inherited and thus manipulated in a parent context.

Note that although tests passed before without this bug fix, it seemed the tested behavior I mentioned above (using the `tab` key to move outside a nested submenu) was broken anyway.

| In `trunk` (with tests passing) | After https://github.com/WordPress/gutenberg/pull/66872/commits/78c8b2086096ffb5318484e973ebcae705db2876 |
| --- | --- |
| <video src=https://github.com/user-attachments/assets/d26308a0-6d64-44c1-84a2-db30d2c173db> | <video src=https://github.com/user-attachments/assets/dc07430c-94a3-433c-a4d9-27a8b8dca38e> |

File: packages/interactivity/src/proxies/context.ts (hunk 1 above)
Comment (DAreRodz) [reply packages/interactivity/src/proxies/context.ts:43]: > those lines are on the unproxied objects so that usage of `in` is not impacted. Is that correct?

Correct. 🙂



> Are there tests already for the case where the value should be set on fallback?

Yes, there are. We have a couple of unit tests checking prop modifications on fallback contexts:

https://github.com/WordPress/gutenberg/blob/67b7e0450e3569346c276fc2b8ed664bf485127c/packages/interactivity/src/proxies/test/context-proxy.ts#L77-L158

**Comment by t-hamano** [comment]
Removing `Backport to WP Minor Release` label because #67259, which is equal to this PR, has already been merged into `wp/6.7` branch.
