### PR TITLE
Paste: only link selection if URL protocol is http(s)

### LINKED ISSUE #24895: Raw Handling: Text with colon incorrectly interpreted as a link
**Describe the bug**
When pasting over existing text, if the new text has a colon in it without first having a space character, Gutenberg will assume you are pasting a link and will open the link insertion dialog box.

**To reproduce**
1. Add some text to a paragraph block.
1. Copy the following text to your clipboard: Bug: This text is not a link
1. Select the text you added to the paragraph block.
1. Paste the text you copied.
1. Notice that you are prompted to insert a link.

**Expected behavior**
The text should paste without inserting it as a link.

**Screenshots**
paste-text-link-bug

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 84

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Fixes #24895. `isURL` returns true for any sort of protocol, which results in false positives such as `movie: something`, where `movie` would be assumed as the protocol. To leave the flexibility of `isURL` and avoid changing this API, we can just add an additional check if the protocol is http(s) for just the link pasting feature. In this case, it's only really meant for these two protocols.

If there's more demand, we could add an argument to `isURL` in the future to check for whitelisted protocols.

OR we could return the URL instance so you can check as follows: 
```js
new Set( 'http', 'https' ).has( isURL( text )?.protocol ) )
```

OR we just use `new URL( text )` directly. What do you think?

Anyway, this needs to be fixed, we can thing about the best approach later.

## Why?

Pasting anything with a colon over a selection results in a link.

## How?

Described above.

## Testing Instructions

Copy anything with a colon and paste over a selection. An e2e test has been added.

### CODE REVIEW

**Comment by kevin940726** [comment]
Does this also fix #46287? Should we also consider `tel:` and `mailto:` protocols as URLs?

Though slightly unrelated, it would be nice to tackle (in a different PR possibly) https://github.com/WordPress/gutenberg/issues/49636 as well.

**Comment by ellatrix** [comment]
> Should we also consider `tel:` and `mailto:` protocols as URLs?

Imo no, it's better to let the user add these explicitly since these are much rarer.

File: packages/block-editor/src/components/rich-text/use-paste-handler.js [hunk 1]
```diff
@@ -224,10 +224,14 @@ export function usePasteHandler( props ) {
...
 
+			const trimmedPlainText = plainText.trim();
+
 			if (
 				__unstableEmbedURLOnPaste &&
 				isEmpty( value ) &&
-				isURL( plainText.trim() )
+				isURL( trimmedPlainText ) &&
+				// For the link pasting feature, allow only http(s) protocols.
+				/^https?:/.test( trimmedPlainText )
```
Comment (jorgefilipecosta) [inline packages/block-editor/src/components/rich-text/use-paste-handler.js:234]: Would it make sense to include the two other prevalent types of links, FTP(s) and "mailto:". I think besides HTTP these two would cover the needs of most people and given that we are using a regex if is just a matter of adding these two protocols to the regex the code does not become much harder.

**Review by jorgefilipecosta — APPROVED** [review]
The change looks good to me and fixes the issue.
