### PR TITLE
Media Thumbnail Field: Optimise image loading

### LINKED ISSUE #75406: Media Thumbnail Field: Optimise loading of the thumbnail image
Part of:

* #73085 

While testing the new infinite scroll work for DataViews with the experimental media modal (https://github.com/WordPress/gutenberg/pull/74378), I noticed some performance issues with loading in the media thumbnails while scrolling up and down the media library.

There are some performance improvements we could do to help here:

* Avoid using the full `source_url` where possible (i.e. max out at a large size)
* Explore asynchronously / lazy loading the images via JS for smoother pop in / fade out of the media thumbnails

To reproduce the issue:

* With a media library with _lots_ of images
* Activate the media modal experiment in Gutenberg settings, and fire up #74378 to try out the infinite scroll
* Adjust the Grid settings in the modal to have a really small preview (so that each "page" of the scrolling loads in lots of images at once)
* Scroll down (or up and down) really fast, and note that things lock up a little bit rather than loading in smoothly
* If you're not noticing this, maybe try some CPU or network throttling to see if you can replicate (I'm testing on a MacBook Air)

### A screengrab

Note the points where the loader appears to be a little stuck / the images sort of pop in:

https://github.com/user-attachments/assets/1ae5399f-ac01-4fc9-a394-b8898a332170

### PR DESCRIPTION
**Pull request by andrewserong**
## What?

Closes #75406

Note: this is a _slightly_ speculative PR, very happy for feedback if it seems like not the right approach!

Try optimising image loading for the media thumbnail field (e.g. used by the media upload modal), by doing the following:

* Borrow the fade-in approach used by the Author field so that images are only shown after they're loaded (this avoids the clunky pop-in effect seen on trunk when paging through lots of results)
* Try using JS to determine the correct image size to use, and no longer use `srcSet` for this field (I'll explain more below)

## Why?

It turns out that using `srcSet` for large grid images can have an unintended effect on large high-dpi screens. If we assume a grid size of `900px` but the device is of at least a `2x` pixel density, then the browser will attempt to render images that are at least `1800px` across. For a page of 20+ results, this can quickly add up to rendering a lot of large images all at once. I _think_ this is the primary source of the performance issue in #75406.

While not _ideal_, the idea in this PR is to pick a size much closer to the final grid size. The impact is that the images will be slightly less sharp, but we should be loading smaller images overall with better performance. In my local testing, this results in displaying image sizes that are around `1024px` (e.g. large size, instead of full size). Though not `2x` the grid, they're still larger enough than original full-size images that (to my eyes at least) they seem _reasonably_ sharp, while being more performant.

The general idea behind this PR is: performance of loading is a better trade-off than sharpness. But there's still a balance to be had here, so again, happy for feedback / differing opinions 🙂

## How?

* Add the logic (similar to the author field) to fade-in the media thumbnail
* Refactor _slightly_ so that we have a separate `ImageView` that contains the loading logic
* Add a `getBestImageUrl()` function that just grabs the next larger image than the target size — this is what gets us (for example) a `1024px` width image for a `900px` container

## Testing Instructions

Enable the media upload modal experiment in Gutenberg settings:

image

* Add a File block to a post or page (so that you can test non-image media, too)
* Make sure your media library has a whole bunch of images in it so you can experiment with paging through results
* Open up dev tools and throttle your network
* Try paging through the results, and see how it feels and loads
* Switch to the table view and do the same
* Images should (generally) smoothly load in, and it should be more performant than on `trunk`
* When going "back" to a page that you already loaded, images should (generally) be instantly displayed with no fade (browsers can wind up unloading things, so this isn't _always_ the case, but hopefully it happens most of the time)
* Non-image media should be unaffected and just show their previews like they did previously

## Screenshots or screencast 

Grid view:

https://github.com/user-attachments/assets/642c62be-ce56-42a7-b7a2-a54f533875f2

And here's the table view while throttled (to make the behaviour a bit clearer):

https://github.com/user-attachments/assets/a6cff59c-3eee-4fb1-abc2-c675c9d679a7

### CODE REVIEW

File: packages/media-fields/src/media_thumbnail/view.tsx [hunk 1]
```diff
@@ -50,6 +97,64 @@ function FallbackView( {
...
+	 * fade-in animation entirely.
+	 */
+	const imgRef = useRef< HTMLImageElement >( null );
+	const [ loadingState, setLoadingState ] = useState<
+		'instant' | 'loading' | 'loaded'
+	>( 'loading' );
+
+	useLayoutEffect( () => {
+		if ( imgRef.current?.complete ) {
+			setLoadingState( 'instant' );
```
Comment (ramonjd) [inline packages/media-fields/src/media_thumbnail/view.tsx:137]: What about 'complete' as well? No biggie. Shame there's no `loaded` property on the IMG instance as well, then we'd have the complete set!

https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/complete

File: packages/media-fields/src/media_thumbnail/view.tsx [hunk 2]
```diff
@@ -18,6 +23,48 @@ import type { DataViewRenderFieldProps } from '@wordpress/dataviews';
...
+	}
+
+	const sizeEntries = Object.values( sizes );
+
+	if ( ! sizeEntries.length ) {
+		return featuredMedia.source_url;
+	}
+
+	// Parse target width from config.sizes (e.g. '900px' → 900).
+	const targetWidth = configSizes ? parseInt( configSizes, 10 ) : NaN;
```
Comment (ramonjd) [inline packages/media-fields/src/media_thumbnail/view.tsx:50]: This is working pretty well for grid and table sizes:

https://github.com/user-attachments/assets/f2e8d707-92f5-4988-941b-908e78c35334

🎉

**Comment by tellthemachines** [comment]
Does this make any real difference for the table layout? In my testing of the site editor pages view on trunk it always loads the 150px image which I think is the smallest default size?

Another possible approach if we want to continue using srcset (and not lower image resolution) is to use a calculation similar to how we're [counting grid columns](https://github.com/WordPress/gutenberg/blob/trunk/packages/dataviews/src/components/dataviews-layouts/grid/preview-size-picker.tsx#L48) to pass the actual image size instead of the hardcoded 900px (the biggest possible size the grid images can attain, which will probably almost never be used). The downside is having to load new images if you change the preview size (I hardcoded the value in the first place to avoid that).

**Comment by andrewserong** [comment]
> Does this make any real difference for the table layout? In my testing of the site editor pages view on trunk it always loads the 150px image which I think is the smallest default size?

I think the only bits that make a difference for the table layout are the added opacity animation (they display a little smoother) and the `loading="lazy"` so that on _really_ long lists it only loads them when they become visible.

The switch to JS instead of `srcset` only _practically_ benefits the Grid layout, but I figure it's cleaner if we go with one approach for the media thumbnail field rather than forking based on the kind of layout in use.

> Another possible approach if we want to continue using srcset (and not lower image resolution) is to use a calculation similar to how we're [counting grid columns](https://github.com/WordPress/gutenberg/blob/trunk/packages/dataviews/src/components/dataviews-layouts/grid/preview-size-picker.tsx#L48) to pass the actual image size instead of the hardcoded 900px

Good point. Do you prefer the idea of using `srcset`? Initially I was slightly skeptical of the approach in this PR (using JS instead), but after playing around with it a little bit, one possible benefit of the approach here is that the browser won't wind up swapping out images as a user changes the preview size (which might be the case if we use actual image size instead of the hardcoded value).

I'm not wedded to any _particular_ approach here, other than helping getting the images to feel nice and smooth as they load in, whichever way we go about it 🙂

So, happy to keep iterating!

**Comment by tellthemachines** [comment]
> Good point. Do you prefer the idea of using `srcset`?

Not particularly, especially give the potential to load new images on resize. I think it's fine to try the JS approach and see how it works!

File: packages/media-fields/src/media_thumbnail/view.tsx (hunk 1 above)
Comment (andrewserong) [reply packages/media-fields/src/media_thumbnail/view.tsx:137]: I mostly picked `instant` here since we'd already used it in the Author field, but this state is effectively a no-op — it doesn't output any classname at all, so it skips applying an `is-loaded` classname. This way we can avoid the animation altogether for images that were complete (loaded) at the time of the component mounting.

All of which is to say, the model we have of loading state here is _slightly_ different to the states of the `img` element itself.

Happy to rename this one to `complete` if it feels clearer... I mostly wanted to capture a state which says "don't do any animation, just display the image immediately if it's already loaded when we mounted" 😄

**Review by tellthemachines — APPROVED** [review]
LGTM! It works well in testing with all the different layout types, so I think 🚢

**Comment by andrewserong** [comment]
Nice one, thanks for reviewing! As always, happy to keep tweaking in follow-ups 👍
