### PR TITLE
Fix legacy widget height overflow

### LINKED ISSUE #33115: Widget Editor: Legacy widget scrollbars
## Description

Legacy widgets show scrollbars in a variety of themes.

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Make sure several legacy widgets are added to sidebars, then update to WP 5.8 RC1.
2. Activate various themes and note scrollbars.

This appears to be from margin on elements inside, including .widget.

Previously seen on https://github.com/WordPress/gutenberg/pull/32260#discussion_r641180062

## Expected behaviour

Scrollbars will not be present.

## Actual behaviour

Scrollbars are present.

## Screenshots or screen recording (optional)

From Twenty X themes:
Screen Shot 2021-06-30 at 11 03 41 AM

From Margin on the ul
Screen Shot 2021-06-30 at 11 04 44 AM

Margin on li
Screen Shot 2021-06-30 at 3 33 46 PM

Non-Twenty themes
Screen Shot 2021-06-30 at 10 04 19 AM

Screen Shot 2021-06-30 at 10 04 55 AM

Screen Shot 2021-06-30 at 3 50 48 PM

## WordPress information
- WordPress version: 5.8 RC1
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme Yes and No

## Device information
- Device: Mac
- Operating system: 10.15.x
- Browser: Chrome

### LINKED ISSUE #33123: Text widget renders large empty space
When upgrading from a site that used text widgets, sometimes these text widgets render a preview containing a large empty space. In TwentyTwenty the space is in all widget areas, in other themes, the space is only in the inactive widgets area.

### To reproduce

1. Use the latest WordPress 5.8 RC
2. Install the Classic Widgets plugin
3. Activate the Classic Widgets plugin
4. Go to Appearance > Widgets
5. Add a text widget and put content in it
6. Deactivate the Classic Widgets plugin
7.  Go to Appearance > Widgets
8. Observe the text widget
9. If it renders correctly try moving it into another widget area, then refreshing the page 

### Screenshots

https://user-images.githubusercontent.com/107534/124063263-22ff1480-da3b-11eb-8076-545bfc466cc8.mp4

### Expected behavior

The text widget to render only its contents.

### PR DESCRIPTION
**Pull request by kevin940726**
## Description

Fix #33115. Fix #33123.

Fix legacy widget height overflow. I also refactored the code a bit to make it simpler.

The margins are a bit high, Most of them are coming from the preview. We'll need to add some custom styling in the preview frame to remove the margins. It probably will have to be done in core though.

Please note that I don't think this is the optimal solution. I believe we should migrate away from iframes in the future, so probably don't worth much time trying to fix every edge case here.

## How has this been tested?

1. Go to Appearance -> Widgets
2. Try to add some legacy widgets
3. Verify that there're no scrollbars in the preview mode.

## Screenshots 
image

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by talldan** [comment]
I'm still seeing scrollbars on the Gallery widget, is there anything that can be done to resolve that?
Screenshot 2021-07-05 at 12 19 49 pm

Though it does also have a horizontal scrollbar, so maybe that's causing issues.

File: packages/widgets/src/blocks/legacy-widget/edit/preview.js [hunk 1]
```diff
@@ -13,34 +13,35 @@ import { Placeholder, Spinner, Disabled } from '@wordpress/components';
...
-			const boundingRect = iframe?.contentDocument?.body?.getBoundingClientRect();
-			if ( boundingRect ) {
-				// Include `top` in the height calculation to avoid the bottom
-				// of widget previews being cut-off. Most widgets have a
-				// heading at the top that has top margin, and the `height`
-				// alone doesn't take that margin into account.
-				setIframeHeight( boundingRect.top + boundingRect.height );
-			}
+		function setHeight() {
+			iframe.style.height = `${ iframe.contentDocument.documentElement.offsetHeight }px`;
```
Comment (talldan) [inline packages/widgets/src/blocks/legacy-widget/edit/preview.js]: As mentioned in the comment, still seeing some scrollbars on the gallery widget. For that widget, the iframe's `body` is taller than its `document`, which is why this calculation makes it too short. Probably why I needed to do something different in the previous PR.

I think it might be worth checking both the document and the body and taking the `max` value. That would hopefully work just using `offsetHeight` instead of `getBoundingClientRect`, but I don't know for sure 😓 .

Comment (kevin940726) [reply packages/widgets/src/blocks/legacy-widget/edit/preview.js]: Yeah, that's my first thought too. I'll run some test for the gallery block. Thanks!

Comment (kevin940726) [reply packages/widgets/src/blocks/legacy-widget/edit/preview.js]: It seems like the gallery block has negative margins that make `<body>` larger than `<html>`. Even if we set the height of the iframe to the height of `<body>`, there's still going to have scrollbars because `<html>`'s size doesn't change.

I believe we have to fix it in core 🤔.

Comment (talldan) [reply packages/widgets/src/blocks/legacy-widget/edit/preview.js]: Are you sure? When I checked, `iframe.contentDocument.documentElement.body.offsetHeight` had the correct height for the gallery.

Comment (kevin940726) [reply packages/widgets/src/blocks/legacy-widget/edit/preview.js]: Oops I was wrong. The issue remained though.

1. There still are negative margins which stretch the width to be greater than 100%, result in a horizontal scrollbar.
2. The value we get from `offsetHeight` seems to be truncated to an integer, which is not enough for floating point heights.

I guess we can solve the vertical scrollbar issue but might have to do more work on the horizontal scrollbar.

Comment (kevin940726) [reply packages/widgets/src/blocks/legacy-widget/edit/preview.js]: I wonder if I can just set overflow to hidden for the preview frame, is it too aggressive: 48a5b4e?

Comment (talldan) [reply packages/widgets/src/blocks/legacy-widget/edit/preview.js]: > I wonder if I can just set overflow to hidden for the preview frame, is it too aggressive: 48a5b4e?

I personally think it's ok to modify the document or the body, as long as the content isn't being touched.

It could be wrapped in a try/catch to prevent any cross origin issues if that's a concern.

File: packages/widgets/src/blocks/legacy-widget/edit/preview.js [hunk 2]
```diff
@@ -13,36 +13,46 @@ import { Placeholder, Spinner, Disabled } from '@wordpress/components';
...
-				setIframeHeight( boundingRect.top + boundingRect.height );
-			}
-		}
+	const ref = useRefEffect(
+		( iframe ) => {
+			// Only set height if the iframe is loaded,
+			// or it will grow to an unexpected large height in Safari if it's hidden initially.
+			if ( isLoaded ) {
+				function setHeight() {
+					iframe.style.height = `${ iframe.contentDocument.body.offsetHeight }px`;
```
Comment (talldan) [inline packages/widgets/src/blocks/legacy-widget/edit/preview.js]: I think it'd be good to still consider something like:
```
Math.max( iframe.contentDocument.body.offsetHeight, iframe.contentDocument.documentElement.offsetHeight )
```

to get the right value. The body seems to have the right value for negative margins (I guess you could say they're collapsing inwards?), but the document for positive margins (collapsing outwards).

The rounding issues are a bit of a frustration. Could consider something like adding 1px to the value to cover that. Or switch back to `getBoundingClientRect` again.

**Review by talldan — APPROVED** [review]
I couldn't spot any issues in testing and code looks good too, thanks @kevin940726!
