### PR TITLE
Background Image Panel: fix focus loss

### LINKED ISSUE #69745: Background Image Panel: fix focus loss
I'd suggest the following two point to improve the background image panel.

### Fix focus loss

The focus is lost when the following actions occur, which can confuse users who rely on screen readers or the keyboard:

- Add new image
- Reset image

https://github.com/user-attachments/assets/45c224d3-b244-4ccc-8ba1-b40a7288f085

The add background image button should be focused after adding/resetting the image ([Example of the color panel](https://github.com/WordPress/gutenberg/blob/4ee2d92d2cfea8fc9938d41821ab9e2fdf4fa240/packages/block-editor/src/components/colors-gradients/dropdown.js#L136-L137)).

### ~Add reset button~

**Update: There are already two reset options in the dropdown, so we don't need to add an additional reset button.**

All the other similar panels (Color, Shadow. Duotone) have a reset button to the right of the button:

Image

It would be good to add the button to the Background Image Panel as well.

Image

Note that the following spec is required:

- The reset button should only be displayed when:
  - the image is set and the toggle button is hovered
  - the image is set and the reset button is focused
- When the image is reset, the toggle button should be focused

### PR DESCRIPTION
**Pull request by Mayank-Tripathi32**
## What?
Closes #69745

Fixes focus management in the Background Image Control component by improving ref handling and focus timing.

## Why?
The focus was not being properly maintained after image operations in the Background Image Control because:
1. The ref was being created but not properly attached to the parent container as it unmounted.
2. Focus timing issues occurred during DOM updates and state changes
3. The component structure made it difficult to reliably find and focus the toggle button

## How?
- Moved the `containerRef` attachment to the parent container div in `BackgroundImagePanel`
- Ensured proper ref propagation through component hierarchy
- Modified the `closeAndFocus` function to use `requestAnimationFrame` for reliable timing
- Removed the immediate click operation after focus (as that didn't feel consistent with other settings)
- Added proper null checks for the container ref
- Added `closeAndFocus` handler call to `onSelectMedia` flow to ensure that focus returns correctly.

The architectural change of moving the ref to the parent container provides a more reliable way to find focusable elements within the component's DOM structure.

## Testing Instructions (keyboard)
1. Open any post, add "group block"
3. Open the Inspector and navigate to "background image"
4. Click "Add background image" and select an image, complete the flow for adding image
5. Verify that focus returns to the toggle button (preview button) after image selection
6. Click the toggle button to open the dropdown
7. Click "Reset" via modal
8. Verify that focus returns to the toggle button
9. Repeat steps 4-8 multiple times to ensure consistent behavior

The focus should consistently return to the toggle button after any image operation (select/reset/remove) and the dropdown should close properly.

## ScreenCast

https://q7utzrengv.ufs.sh/f/Wgl9eBAmTj29aD9Oh8fFRjF31d07GtqsWNpK4IXH6Z9OnbyQ

### CODE REVIEW

File: packages/block-editor/src/components/background-image-control/index.js [hunk 1]
```diff
@@ -342,14 +344,19 @@ function BackgroundImageControls( {
...
-		const [ toggleButton ] = focus.tabbable.find(
-			replaceContainerRef.current
-		);
-		// Focus the toggle button and close the dropdown menu.
-		// This ensures similar behaviour as to selecting an image, where the dropdown is
-		// closed and focus is redirected to the dropdown toggle button.
-		toggleButton?.focus();
-		toggleButton?.click();
+		// Use requestAnimationFrame to ensure DOM updates are complete
+		window.requestAnimationFrame( () => {
```
Comment (Mamaduka) [inline packages/block-editor/src/components/background-image-control/index.js:348]: In my experience, rAFs or `setTimeout` tasks aren't entirely reliable for focus management.

**Review by Mamaduka — COMMENTED** [review]
I think there are a couple of other tricks we might use, which, in theory, should reduce the complexity of this component.

1. Refactor/re-arrange components so that the Media modal returns focus "naturally." It is usually my preferred method. Example: #68621.
2. Use flag and ref callback. Example: #67236.

File: packages/block-editor/src/components/background-image-control/index.js (hunk 1 above)
Comment (Mayank-Tripathi32) [reply packages/block-editor/src/components/background-image-control/index.js:348]: I will check out the other implementations in that case, should we also look into updating existing uses of rAFs in that case?

**Comment by t-hamano** [comment]
Thanks for the PR!

This problem might be more difficult than I thought.

I was wondering why this block needs special focus handling because the `MediaRplaceFlow` component should automatically return focus to the proper element.

From what I've researched, different components are rendered depending on whether media is set or not. If media is not set, the MediaReplaceFlow component is rendered. If media is set, a Dropdown component is rendered and the MediaReplaceFlow component is rendered in a popover.

Although they look the same button at first glance, different components are rendered, so I think special focus handling is required.

Considering that, we may not be able to use the same approach as the site logo.

Is my understanding correct?

**Comment by Mayank-Tripathi32** [comment]
> Although they look the same button at first glance, different components are rendered, so I think special focus handling is required.

> Considering that, we may not be able to use the same approach as the site logo.

Yes, its using different buttons, So while the component should return focus but it cannot as original button might be unmounted.

We can probably refactor the component.

```JS
		{ shouldShowBackgroundImageControls ? (
				<BackgroundControlsPanel
					label={ title }
					filename={ title }
					url={ url }
					onToggle={ setIsDropDownOpen }
					hasImageValue={ hasImageValue }
				>
					<VStack spacing={ 3 } className="single-column">
						<BackgroundImageControls
							onChange={ onChange }
							style={ value }
							inheritedValue={ resolvedInheritedValue }
							displayInPanel
							onResetImage={ () => {
								setIsDropDownOpen( false );
								resetBackground();
							} }
							onRemoveImage={ () => setIsDropDownOpen( false ) }
							defaultValues={ defaultValues }
							containerRef={ containerRef }
						/>
						<BackgroundSizeControls
							onChange={ onChange }
							style={ value }
							defaultValues={ defaultValues }
							inheritedValue={ resolvedInheritedValue }
						/>
					</VStack>
				</BackgroundControlsPanel>
			) : (
				<BackgroundImageControls
					onChange={ onChange }
					style={ value }
					inheritedValue={ resolvedInheritedValue }
					defaultValues={ defaultValues }
					onResetImage={ () => {
						setIsDropDownOpen( false );
						resetBackground();
					} }
					onRemoveImage={ () => setIsDropDownOpen( false ) }
					containerRef={ containerRef }
				/>
			) }
```

I think following code might be causing it.

**Comment by Mayank-Tripathi32** [comment]
@t-hamano Should I go ahead with changing the structure a little bit so that focus returns automatically?

**Comment by t-hamano** [comment]
> Should I go ahead with changing the structure a little bit so that focus returns automatically?

Yes, as long as there are no visual changes, I think refactoring to achieve our purpose is acceptable.

**Comment by Mayank-Tripathi32** [comment]
> > Should I go ahead with changing the structure a little bit so that focus returns automatically?
> 
> Yes, as long as there are no visual changes, I think refactoring to achieve our purpose is acceptable.

I tried to refactor the component to remove then "unmounting" of toggle button but it wont look the same as internally its using two different popovers.
image
or we can refactor "MediaReplaceFlow" to use Dropdown component as well.



-----------------------------------------------------------------------------------------
Also, 

image

This should be using dropdown component too to match other components where it opens on the side?
image

**Comment by t-hamano** [comment]
@Mayank-Tripathi32 Thanks for investigating!

> Yes, as long as there are no visual changes, I think refactoring to achieve our purpose is acceptable.

I have tried to find an ideal approach, but I haven't found it yet 😅 For now, I can think of three approaches:

**The first approach**: Don't unmount the components, but visually hide the components that shouldn't be displayed with `visibility: hidden`. That way, we won't lose the ref and we should be able to focus on the button when the image is uploaded or reset.

**The second approach**: create a separate toggle button for the popover, which may not be acceptable since it introduces a visual change. Two examples:

image

image

**The third approach**: As already tried, use `window.requestAnimationFrame`. This seems like it might be unreliable for focus management, but as far as I've tested, this approach seems to work stably.

@Mamaduka @Mayank-Tripathi32 

I think it might be a good idea to try the third approach, what do you think?

**Comment by Mamaduka** [comment]
Agreed. Let's try the third approach for now.

**Review by t-hamano — APPROVED** [review]
This PR works fine for me.

@Mamaduka Are there any further improvements regarding this approach using `requestAnimationFrame `?

**Comment by t-hamano** [comment]
Let's go ahead with this PR for now, and if the rAF approach is unstable, consider a different approach in follow-up.

**Comment by Mamaduka** [comment]
Sorry, somehow I missed the latest pings. No further feedback on rAF, besides the initial comment.

I think this is a good hotfix. When I have time, I might look into refactoring the whole component, but it's not a priority at the moment.
