### PR TITLE
[LatestPosts] Fixes the excerpt length

### LINKED ISSUE #20311: Latest Posts block: Excerpt doesn't respect the excerptLength attribute (WP 5.4 Beta 2)
On front-end, the excerpt for the Latest Posts block isn't trimmed to the length given by the user with the excerptLength attribute.
This bug was introduced in https://github.com/WordPress/gutenberg/pull/19669

### PR DESCRIPTION
**Pull request by draganescu**
## Description
Closes #20311

It is a bug introduced by #19669

## How has this been tested?
Tested locally by:

- add a post
- add a latest posts block
- set the block to show excerpt
- set the limit of excerpt words to be 10
- save the post
- check that the rendering does not exceed 10 words in the excerpt

## Types of changes
Introduces an excerpt_length filter in the `LatestPosts` block.

### CODE REVIEW

File: packages/block-library/src/latest-posts/index.php [hunk 1]
```diff
@@ -21,6 +21,12 @@ function render_block_core_latest_posts( $attributes ) {
 		'suppress_filters' => false,
 	);
 
+	$excerpt_length        = $attributes['excerptLength'];
+	$excerpt_length_filter = function ( $length ) use ( $excerpt_length ) {
+		return $excerpt_length;
+	};
+	add_filter( 'excerpt_length', $excerpt_length_filter, 999 );
```
Comment (youknowriad) [inline packages/block-library/src/latest-posts/index.php]: Why do we need a filter here?

**Review by youknowriad — COMMENTED** [review]
Shouldn't we apply the trimming according to the defined length to this line instead?

```
			$trimmed_excerpt = get_the_excerpt( $post );
```

**Comment by draganescu** [comment]
As discussed in the [design channel](https://wordpress.slack.com/archives/C02S78ZAL/p1582127396039300) on Slack we should stick to the following process:

- blocks that work with excerpts, right now `PostExcerpt` and `LatestPosts`
- should default to the global excerpt setting (set by the excerpt_length) filter
- but have a local setting
- which only affects their rendered content
- but only generated excerpts
- manual excerpts should be rendered integrally, independent of what the `excerpt_length` setting is.

This behavior is both consistent to how WordPress currently handles excerpts and also with what a user would expect from the system.

There are two new issues that spawn from this:

- the `LatestPosts` block should also render full manual excerpts in the editor preview
- the `PostExcerpt` block should implement the above behavior

File: packages/block-library/src/latest-posts/index.php (hunk 1 above)
Comment (draganescu) [reply packages/block-library/src/latest-posts/index.php]: I used a filter to respect what the theme might do with the excerpt, and I don't trim later in the actual `get_the_excerpt` call so that manual excerpts are not trimmed.

Comment (jorgefilipecosta) [reply packages/block-library/src/latest-posts/index.php]: We are adding a filter but never removing the filter. Aren't we creating a bug where if the theme or plugin calls get_the_excerpt after the latest block is rendered we may be changing the length of that call?
It seems the render function of the latest blocks is having an unexpected side-effect of adding a filter and the filter may affect things outside of the latest post block that is being rendered.
Another concern I have is that I think in WordPress we should not add anonymous functions as filters, because it makes it impossible for a plugin to remove the filter. Maybe @azaozz can confirm if that's the case?

To me, it seems the safest bet, for now, is to call wp_trim_words on the result of get_the_excerpt without using a filter. We may trim even if the user wrote a manual excerpt but that seems expected because an excerptLength is being set also it was what happened before. So following this solution we still fix https://github.com/WordPress/gutenberg/issues/19418 without the risk of introducing a new bug in 5.4.
Any thoughts on this @draganescu, @youknowriad?

Comment (draganescu) [reply packages/block-library/src/latest-posts/index.php]: Hey @jorgefilipecosta or I can remove the filter, after we get the contents and implement the proper behavior. Also good to know the detail on anonymous functions I didn't know that.

Comment (jorgefilipecosta) [reply packages/block-library/src/latest-posts/index.php]: > Hey @jorgefilipecosta or I can remove the filter, after we get the contents and implement the proper behavior


Hi @draganescu, does it mean not using a filter at all, or does it mean calling removing filter after it is not needed?
Either I think we need to update this PR soon so it can be part of Beta 3.

File: packages/block-library/src/latest-posts/index.php [hunk 2]
```diff
@@ -5,6 +5,13 @@
  * @package WordPress
  */
 
+$block_core_latest_posts_excerpt = 0;
+
+function get_block_core_latest_posts_excerpt() {
```
Comment (jorgefilipecosta) [inline packages/block-library/src/latest-posts/index.php]: I think we need to add documentation to this function so it can be part of core.

Comment (draganescu) [reply packages/block-library/src/latest-posts/index.php]: Added PHPDoc to both new things. Thanks!

File: packages/block-library/src/latest-posts/index.php (hunk 1 above)
Comment (draganescu) [reply packages/block-library/src/latest-posts/index.php]: I've updated the PR to not use an anonymous function but still use a filter. Also now the filter is removed after the block is rendered.

**Review by jorgefilipecosta — COMMENTED** [review]
Hi @draganescu, I think the reason we were using a filter was to make sure manual excerpts are respected but in my tests, while this PR makes the excerpts not trimmed on the frontend, it seems manual excerpts are not respected on the editor.

I created a post with the following manual except: `aaaaa1 bbbb2 cccc3 dddd4 eeee5 ffff6 gggg7 hhhhh8 iiiiii9 jjjjjj10 llllll11 mmmmmm12 nnnnnn13`, and published it.

I created another post with the latest posts block with except length of 10. The excerpt displayed as `aaaaa1 bbbb2 cccc3 dddd4 eeee5 ffff6 gggg7 hhhhh8 iiiiii9 jjjjjj10 ... Read more` instead of showing the complete excerpt I wrote on the editor.

File: packages/block-library/src/latest-posts/index.php [hunk 3]
```diff
@@ -5,6 +5,26 @@
  * @package WordPress
  */
 
+/**
+ * The excerpt length set by the Latest Posts core block
+ * set at render time and used by the block itself.
+ *
+ * @var int
+ */
+$block_core_latest_posts_excerpt = 0;
```
[the remark this answers is not in the document]
Comment (aduth) [reply packages/block-library/src/latest-posts/index.php]: Okay, I see now how the global variable is being used to account for the block attribute.

But:

- I don't know that we need to declare this variable here at all. If there's a default, it should be provided through the attributes schema.
- With PHP support now bumped, we might be able to implement this without resorting to a global variable.

I'm not sure if it works to add filters using a function assigned to a variable, but if it does, it may be possible to implement inline in `render_block_core_latest_posts ` as:

```php
$filter_excerpt_length = function( $length ) use ( $attributes ) {
	if ( ! empty( $attributes['excerptLength'] ) ) {
		return $attributes['excerptLength'];
	}

	return $length;
};

add_filter( 'excerpt_length', $filter_excerpt_length );

// ...

remove_filter( 'excerpt_length', $filter_excerpt_length );
```

File: packages/block-library/src/latest-posts/index.php [hunk 4]
```diff
@@ -21,6 +43,9 @@ function render_block_core_latest_posts( $attributes ) {
 		'suppress_filters' => false,
 	);
 
+	$block_core_latest_posts_excerpt = $attributes['excerptLength'];
+	add_filter( 'excerpt_length', 'get_block_core_latest_posts_excerpt', 999 );
```
Comment (aduth) [inline packages/block-library/src/latest-posts/index.php]: Can we locate this to somewhere in closer proximity to where we're expecting the filter to be applied? i.e. the `get_the_excerpt` function call.

Comment (aduth) [inline packages/block-library/src/latest-posts/index.php]: Should we want to fall back to the default behavior of excerpt length when the attribute isn't explicitly assigned?

File: packages/block-library/src/latest-posts/index.php (hunk 3 above)
[the remark this answers is not in the document]
Comment (aduth) [reply packages/block-library/src/latest-posts/index.php]: Related: https://make.wordpress.org/core/2019/03/26/coding-standards-updates-for-php-5-6/

>Anonymous functions must not be passed as filter or action callbacks in WordPress Core, as they cannot be removed by remove_action() / remove_filter() (see #46635 for a proposal to address this). Outside of Core, developers may pass anonymous functions as filter or action callbacks at their own discretion.

This specific usage is a bit unique though, in that the filter is only temporarily added for the purpose of controlling the behavior of excerpt length, then immediately removed. It's not something which we would expect plugins to be able to have access to referencing for removal anyways (IIRC, manipulating peer filters in the context of a filter callback will not have an effect within the same callback execution).

File: packages/block-library/src/latest-posts/index.php (hunk 4 above)
[the remark this answers is not in the document]
Comment (draganescu) [reply packages/block-library/src/latest-posts/index.php]: I remember it from the docs of the `excerpt_length` filter: 

> Make sure to set the priority correctly, such as 999, otherwise the default WordPress filter on this function will run last and override what you set here.

[the remark this answers is not in the document]
Comment (aduth) [reply packages/block-library/src/latest-posts/index.php]: That would be surprising to me. The default filter is applied in `default-filters.php`:

https://github.com/WordPress/wordpress-develop/blob/822167a42b1a81bd94cf4c1e4ecaf958dc5233ae/src/wp-includes/default-filters.php#L185

As long as the code which adds the filter executes after this file (which I think is most common?), if it uses the same priority, it should take precedent over the default.

In any case, I don't think it needs to be quite so strong. If the primary goal is to take effect after the default, any value `11` or higher can suffice. Using some sensible increment (e.g. by `10`) can allow plugins to still insert "between" as well. A value like `20` might be a reasonable alternative.

File: packages/block-library/src/latest-posts/index.php [hunk 5]
```diff
@@ -5,6 +5,7 @@
  * @package WordPress
  */
 
+
```
Comment (jorgefilipecosta) [inline packages/block-library/src/latest-posts/index.php]: Could we remove this new line?

File: packages/block-library/src/latest-posts/index.php [hunk 6]
```diff
@@ -13,6 +14,7 @@
  * @return string Returns the post content with latest posts added.
  */
 function render_block_core_latest_posts( $attributes ) {
+
```
Comment (jorgefilipecosta) [inline packages/block-library/src/latest-posts/index.php]: Could we remove this new line?

File: packages/block-library/src/latest-posts/index.php (hunk 4 above)
Comment (draganescu) [reply packages/block-library/src/latest-posts/index.php]: hmm, indeed, this might not be always set.

Comment (draganescu) [reply packages/block-library/src/latest-posts/index.php]: I've tested without setting it seems that LP block always has that attribute at render time.

Comment (draganescu) [reply packages/block-library/src/latest-posts/index.php]: I want to set the filter outside of the foreach loop.

**Comment by draganescu** [comment]
@aduth regarding the use of anonymous functions as filters I tested the implementation of filtering excerpt_length in the latest post block with an anonymous function assigned to a variable:
```
	$block_core_latest_posts_excerpt_length = function( $length ) use ( $attributes ) {
		if ( ! empty( $attributes['excerptLength'] ) ) {
			return $attributes['excerptLength'];
		}
		return $length;
	};
	add_filter( 'excerpt_length', $block_core_latest_posts_excerpt_length, 999 );
```
then removing it with
```
remove_filter( 'excerpt_length', $block_core_latest_posts_excerpt_length );
```

then in `single.php` I created at the end (after displaying the single post) a new loop:

```
$my_query = new WP_Query( $args );
if ( $my_query->have_posts() ) {
    while ( $my_query->have_posts() ) {
        $my_query->the_post();
		echo '<hr>';
		echo get_the_excerpt();
		echo '<hr>';
    }
}
```
and these posts had their excerpt stuck to the length set by the block latest posts contained in the single post. So it means we can't do it any other way but with named functions so that we can remove them after we render the blocks.

Using a global reference and a named function the same test reverts OK to the default WP excerpt length.

File: packages/block-library/src/latest-posts/index.php (hunk 4 above)
[the remark this answers is not in the document]
Comment (draganescu) [reply packages/block-library/src/latest-posts/index.php]: I've set this to 20, although only because 999 did indeed sound like the new z-index wars. Otherwise, it should be the last one applied as we want the rendering of this block to respect whatever that attribute is set to.

**Comment by draganescu** [comment]
@jorgefilipecosta there is another PR that fixes the block's edit to respect manual excerpts: #20432

**Review by jorgefilipecosta — APPROVED** [review]
LGTM 👍

**Comment by raQai** [comment]
Just because customers flooded my e-mail and didn't know this was design by choice: is there any way to also trim manual excerpts in the block or do i have to edit the core files? 

> This behavior is both consistent to how WordPress currently handles excerpts and also with what a user would expect from the system

I can verify at least 12 of my customers do not agree after updating to 5.4. All of them expected the manual excerpt to be trimmed as well.

**Comment by draganescu** [comment]
Howdy @raQai and thank you for the feedback!

This change to the LatestPosts block may have broken some fixed layouts, is this your customer's case as well?

It is important why would a manual excerpt be trimmed. How would this benefit your customers?

**Comment by raQai** [comment]
I was finally able to check all the sites "affected" by this. Some of them used fixed layouts, some have been wondering because they used the "read more" link in form of a button to give better feedback to site visitors showing them "hey, you can continue reading here."

The main issue for most of them relates to the latter.
Relying on the users to understand that a fully written text might not be the full post (while also hoping for them to click on the link of the title) feels kind of strange.

As far as I can tell, there is no direct hook to append this button, is it?
Do i have to register my own block type then or can I somehow hook into the renderer?

**Comment by draganescu** [comment]
Just to make sure I understand: 

- the problem is that:
 - in pages using the `LatestPosts` block
  - for posts that have manual excerpts
   - there is no read more link
    - and users don't know there is more?

**Comment by raQai** [comment]
@draganescu correct.

A simple checkbox to allow to "always display read more link" would solve this issue. That's what I am currently working on but since I never worked on custom gutenberg blocks before, I first have to dig into the documentation :)
