### PR TITLE
Fix: ServerSideRender remains in loading state when nothing is rendered.

### LINKED ISSUE #13870: ServerSideRender remains in loading state when nothing is rendered
**Describe the bug**
When `<ServerSideRender />` receives a successful AJAX response `{"rendered":""}` it remains in the "loading" state instead of rendering nothing or rendering a message `No output` or similar.

This is slightly confusing because it doesn't provide user the feedback that "With these particular settings your block doesn't output anything" but instead it appears as if it's still working on getting the output:

image

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/13870

The server-side render component stayed loading forever if the block rendered an empty string. This PR addresses this problem.

## How has this been tested?
I added return ""; to the archives block:
```
function render_block_core_archives( $attributes ) {
	return "";
...
```

I added the archives block in the editor and verified the block does not stay loading forever.
## Screenshots 
After:
image

Before:
image

### CODE REVIEW

File: packages/components/src/server-side-render/index.js [hunk 1]
```diff
@@ -86,7 +86,7 @@ export class ServerSideRender extends Component {
 	render() {
 		const response = this.state.response;
 		const { className } = this.props;
-		if ( ! response ) {
+		if ( ! response && response !== '' ) {
```
Comment (gziolo) [inline packages/components/src/server-side-render/index.js]: This check is confusing. Is it possible to get a `response` which isn't an object or `null`? If `response` would be a non-empty string then condition `response.error` and `response.length` will work quite randomly.

File: packages/components/src/server-side-render/index.js [hunk 2]
```diff
@@ -109,7 +109,7 @@ export class ServerSideRender extends Component {
 				<Placeholder
 					className={ className }
 				>
-					{ __( 'No results found.' ) }
+					{ __( 'Block rendered an empty area.' ) }
```
Comment (gziolo) [inline packages/components/src/server-side-render/index.js]: Is `area` a good choice to describe this case?

Comment (Tofandel) [reply packages/components/src/server-side-render/index.js]: Some thoughts, what about "Block rendered as empty" or no text at all if it's empty ?
If on the contrary you want to emphasize that an empty render shouldn't happen then maybe "The block failed to render"

File: packages/components/src/server-side-render/index.js (hunk 1 above)
Comment (jorgefilipecosta) [reply packages/components/src/server-side-render/index.js]: Hi @gziolo, I updated the flow of logical conditions to make the code easier to understand.

File: packages/components/src/server-side-render/index.js (hunk 2 above)
Comment (jorgefilipecosta) [reply packages/components/src/server-side-render/index.js]: I updated to use the string "Block rendered as empty", I also think not rendering anything is an option to consider, but as blocks may not expecting it, I thought to add a message is the safest bet.

**Review by gziolo — APPROVED** [review]
This looks good with the changes applied. Thanks for all improvements 👍
