### PR TITLE
Font Library: fix fonts not displaying correctly

### LINKED ISSUE #54706: Font Library: Some installed Google fonts don't display in editor or frontend
### Description

Some fonts display correctly in the Typography fonts list and Font Library dialog, but the faces are not applied in the editor or the frontend. At first I thought it might be related to mixed alpha/numeric characters in the font name, but received inconsistent results.

I've tested the following fonts, assigned to Headings in the editor, *before and after* refreshing the editor and checking the site frontend. Included are the generated CSS variables, which can differ between when the font is assigned and reloading the page 🤔:

- ✅ Gothic A1
    - `var(--wp--preset--font-family--gothic-a1)`
    - same after refresh
- ❌ Libre Barcode 128 Text
    - `var(--wp--preset--font-family--libre-barcode-128-text)`
    - same after refresh
- ❌ Press Start 2P
    - `var(--wp--preset--font-family--press-start-2-p)`
    - `var(--wp--preset--font-family--press-start-2p)`
- ❌ Rock 3D
    - `var(--wp--preset--font-family--rock-3-d)`
    - `var(--wp--preset--font-family--rock-3d)`
- ❌ Rubik 80s Fade
    - `var(--wp--preset--font-family--rubik-80-s-fade)`
    - `var(--wp--preset--font-family--rubik-80s-fade)`
- ⚠️ VT323
    - ✅`var(--wp--preset--font-family--vt-323)`
    - ❌`var(--wp--preset--font-family--vt323)` (stopped displaying properly after save/reload)

### Step-by-step reproduction instructions

1. In the site editor, open *Styles > Typography*.
2. Open the font manager dialog, and select the "Install Fonts" tab.
3. Search for and install any of the fonts identified above (you must check each variant and click the blue Install button).
4. Close the font manager, and select the Headings in the *ELEMENTS* section.
5. 👀 Use the select box to assign one of the fonts, then observe changes to the headings on in the editor.
6. 👀 Click the Save button to apply the new global styles, then observe changes to the headings on in the editor.
7. 👀 Refresh the page, then observe changes to the headings on in the editor.
8. 👀 Open the site frontend, then observe changes to headings.

For Steps 5-8, you might also check the generated CSS variables assigned to headings.

### Screenshots, screen recording, code snippet

This video shows installation of VT323 and the odd behavior between assigning it to Headings and saving global styles. It also shows how neither Press Start P2 or Libre Barcode 128 Text display correctly when assigned in the editor.

https://github.com/WordPress/gutenberg/assets/824344/4c7004a4-2727-4534-9356-f1bb430f0f3a

### Environment info

- Hardware: MacBook Pro Apple M1 Pro
- OS: macOS 13.5.2
- Browser: Safari 16.6
- Server: nginx/1.25.2
- PHP: 7.4.33
- WordPress: 6.4-alpha-56267-src
- Theme: twentytwentythree v1.2
- Active Plugins:
  - gutenberg v16.7.0-rc.1 `trunk`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by jffng**
This PR fixes #54706.

**Background**
There are two issues occurring, specific to font families with numbers and spaces inside their names / slugs:

1. The presets / CSS variable names and associated styles are output inconsistently between the editor and front-end
2. Font family names that include numbers and spaces are currently not wrapped in quotes, resulting in invalid CSS and the font family not being applied as expected.

**Solution**

Alter the `sanitize` method of the Font Family Class to:

1. Wrap slugs in `_wp_to_kebab_case`
2. Wrap font family names in quotes

Part of the solution includes a small bug fix in the `getIntersectingFontFaces`, as well as adding a test case.

**How to test**
See #54706 — test all reported fonts, in the site editor, post editor, and front end. Verify they appear as expected.

### CODE REVIEW

**Comment by jffng** [comment]
Another approach could be to ensure that all font family slugs get `_wp_to_kebab_case`d when creating the post in the db. Maybe that's better 🤔

**Comment by creativecoder** [comment]
> Another approach could be to ensure that all font family slugs get _wp_to_kebab_cased when creating the post in the db. Maybe that's better 🤔

I'm still learning exactly how font collections and related plumbing work, but addressing this "closer to the source" with the goal of there needing to be less places in code that are concerned manipulating the font family slug and/or name seems better to me.

**Review by mikachan — COMMENTED** [review]
I've tested this with some of the font families mentioned in https://github.com/WordPress/gutenberg/issues/54706 - Gothic A1, Libre Barcode 128 Text, Press Start 2P. They all worked well and I can see both the preset and the font family names are as you describe they should be with this PR.

However, I also agree with your follow-up comment and @creativecoder's, in that it may be best to solve this closer to the source and hopefully have fewer places where the font names and slugs are manipulated.

But I did want to confirm that this fix works 👏

**Comment by jffng** [comment]
@mikachan @creativecoder I altered the approach, would you be able to give this another review?

**Review by mikachan — COMMENTED** [review]
Tested on a fresh install with:

- Gothic A1: `--wp--preset--font-family--gothic-a-1`
- Libre Barcode 128 Text: `--wp--preset--font-family--libre-barcode-128-text`
- Press Start 2P: `--wp--preset--font-family--press-start-2-p`
- Rubik 80s Fade: `--wp--preset--font-family--rubik-80-s-fade`

~However, I'm seeing an intermittent issue where I need to refresh the editor in order for the newly installed fonts to apply correctly. I can see the CSS variables are saved and applied correctly, and the font file is loaded in the network tab, but the font isn't applied. If I save my changes and reload, the font is applied. It seems to happen with any font, not just fonts like the above. Do you know if the reload issue is related to this PR?~

Edit: I've just managed to reproduce the reload issue on trunk, and found this issue is already reported 🙈 https://github.com/WordPress/gutenberg/issues/55018. In that case, I think this PR is working well!

**Review by mikachan — APPROVED** [review]

File: lib/experimental/fonts/font-library/class-wp-font-family.php [hunk 1]
```diff
@@ -304,14 +304,41 @@ private function sanitize() {
...
+		$theme_json = new WP_Theme_JSON_Gutenberg( $fonts_json );
+		$theme_data = $theme_json->get_data();
+
 		$sanitized_font = ! empty( $theme_data['settings']['typography']['fontFamilies'] )
 			? $theme_data['settings']['typography']['fontFamilies'][0]
 			: array();
-		$this->data     = $sanitized_font;
+
+		// Ensure slugs are kebab-cased and font families are wrapped in quotes.
+		if ( isset( $sanitized_font['slug'] ) ) {
```
Comment (matiasbenedetto) [inline lib/experimental/fonts/font-library/class-wp-font-family.php]: Could this be a method?

Comment (jffng) [reply lib/experimental/fonts/font-library/class-wp-font-family.php]: @matiasbenedetto I moved this formatting functionality to utils, what do you think? https://github.com/WordPress/gutenberg/pull/55393/commits/efa76025c2c7d8a42134032923b24713702bbde5

Comment (matiasbenedetto) [reply lib/experimental/fonts/font-library/class-wp-font-family.php]: Tha's better. I reduced the function's scope to only one thing instead of 2 and renamed it accordingly: https://github.com/WordPress/gutenberg/pull/55393/commits/a414e3f40391793fb1372a769109875e561bf926

Comment (matiasbenedetto) [reply lib/experimental/fonts/font-library/class-wp-font-family.php]: We would need to add PHP unit tests to the function.

**Comment by matiasbenedetto** [comment]
I added a commit ( https://github.com/WordPress/gutenberg/commit/0d8330cd61ea159b9c78427599a2b8f1482a5261 ) in this PR  that seems to be solving the issue around 'live preview', too: https://github.com/WordPress/gutenberg/issues/55018

After adding tests to `format_font_family` this seems to be ready to go :)

**Comment by jffng** [comment]
> After adding tests to format_font_family this seems to be ready to go :)

Done in [9f65a16](https://github.com/WordPress/gutenberg/pull/55393/commits/9f65a167c6eb43c01ca3c68d811fe669bcc89230) and [729a8d8](https://github.com/WordPress/gutenberg/pull/55393/commits/729a8d8d3ae590844811f65835a4fdac7617718e).
