### PR TITLE
CustomSelectControl: Restore `describedBy` functionality

### LINKED ISSUE #63568: CustomSelectControl: fix `describedBy` implementation and docs
### Description
Discovered while investigating https://github.com/WordPress/gutenberg/issues/63483

The `CustomSelectControl` component has a `describedBy` prop that accepts a string.

It is supposed to provide an accessible description for the toggle button that opens the custom select.

Unfortunately, both the implementation and the docs are wrong and the component renders non-accessible markup.

An example can be seen for the font appearance setting. It can be reproduced in the Storybook as well.

Turns out the value passed to the `describedBy` prop is just rendered as the value of the `aria-describedby` attribute.

https://github.com/WordPress/gutenberg/blob/c54c0020a7a8ebf22738aa96cb398ea4cf17a30a/packages/components/src/custom-select-control/index.tsx#L157

Instead, the `aria-describedby` attribute accepts an ID reference that points to an element containing the description.

For example, the font appearance setting renders this markup:

`aria-describedby="Currently selected font appearance: Medium"`

The correct usage would be:

```
... aria-describedby="an-unique-id-here" ...

<div hidden id="an-unique-id-here">Currently selected font appearance: Medium</div>

```

The component should be refactored to actually render another element that contains the description, referenced by an ID, much like what [the Button component](https://github.com/WordPress/gutenberg/blob/c54c0020a7a8ebf22738aa96cb398ea4cf17a30a/packages/components/src/button/index.tsx) does.

At that point, the `describedBy` prop should be renamed to `description`.

The readme and types.ts must be fixed as well. For example, this prop description doesn't appear to be correct:
> Description for the select trigger button used by assistive technology. If no value is passed, the text "Currently selected: selectedItem.name" will be used fully translated.

### Step-by-step reproduction instructions

- Select a Group block
- Go to the block Inspector > Styles, and activate the Appearance settings in the Typography options.
- Set a font appearance value e.g. 'Medium',
- Inspect the CustomSelectControl toggle button source.
- Oberve it has an incorrect `aria-describedby="Currently selected font appearance: Medium"`
- Alternatively go to the Storybook: https://wordpress.github.io/gutenberg/?path=/docs/components-customselectcontrol--docs
- Set the `describedBy` prop to `la la la`.
- Inspect the CustomSelectControl toggle button source.
- Oberve it has an incorrect `aria-describedby="la la la"`

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by mirka**
Fixes #63568

## What?

Restores the `describedBy` functionality in CustomSelectControl (v1) that was broken when we switched the underlying implementation in #63258.

## How?

See code comments.

## Testing Instructions

New unit tests should pass. You can also manually inspect the rendered HTML in Storybook.

### CODE REVIEW

File: packages/components/src/custom-select-control/index.tsx [hunk 1]
```diff
@@ -153,23 +174,30 @@ function CustomSelectControl( props: CustomSelectProps ) {
...
+				isLegacy
+				{ ...restProps }
+			>
+				{ children }
+			</_CustomSelect>
+			<VisuallyHidden>
+				<span id={ descriptionId }>
+					{ getDescribedBy( currentValue, describedBy ) }
+				</span>
+			</VisuallyHidden>
```
Comment (mirka) [inline packages/components/src/custom-select-control/index.tsx:199]: The original implementation passed the `describedBy` prop down to `Button`. Therefore, we want to replicate how Button rendered the `describedBy` text.

https://github.com/WordPress/gutenberg/blob/cad81e428aed155fa3e490cc9c8d9673a170c3fd/packages/components/src/button/index.tsx#L282-L284

File: packages/components/src/custom-select-control/index.tsx [hunk 2]
```diff
@@ -35,6 +42,15 @@ function applyOptionDeprecations( {
...
 }
 
+function getDescribedBy( currentValue: string, describedBy?: string ) {
+	if ( describedBy ) {
+		return describedBy;
+	}
+
+	// translators: %s: The selected option.
+	return sprintf( __( 'Currently selected: %s' ), currentValue );
+}
```
Comment (mirka) [inline packages/components/src/custom-select-control/index.tsx:52]: This function copies the original logic, which looked like this:

https://github.com/WordPress/gutenberg/blob/9bb75b35ec0daa46e8cd60c46619f522c7edd453/packages/components/src/custom-select-control/index.js#L130-L141

I removed the case for no selection, because that won't happen in this Ariakit-based version.

File: packages/components/src/custom-select-control/index.tsx [hunk 3]
```diff
@@ -48,8 +64,13 @@ function CustomSelectControl( props: CustomSelectProps ) {
...
 	} = useDeprecatedProps( props );
 
+	const descriptionId = useInstanceId(
+		CustomSelectControl,
+		'custom-select-control__description'
+	);
+
 	// Forward props + store from v2 implementation
-	const store = Ariakit.useSelectStore( {
+	const store = Ariakit.useSelectStore< string >( {
```
Comment (mirka) [inline packages/components/src/custom-select-control/index.tsx:73]: The Ariakit store allows `string | string[]` because it can handle multiple selection. Since this v1 never supported multiple selection, let's narrow the type to just `string`. (This has the effect of narrowing the type of `store.getState().value` to string.)

**Review by tyxla — APPROVED** [review]
✅ Code looks good, and this tests well:

|Without `describedBy`|With `describedBy`|
|---|---|
|Screenshot 2024-07-26 at 13 00 42|Screenshot 2024-07-26 at 13 01 03|

**Comment by afercia** [comment]
Please remember to manually add props to @rohitmathur-7 for the alternative PR at https://github.com/WordPress/gutenberg/pull/63884
