### PR TITLE
Navigation: consistently provide fallback variations

### LINKED ISSUE #29984: Page Link block appears to be missing from the inserter
When running the latest `trunk`, it appears that the "Page Link" block is missing from the Navigation block's inserter. This happens in both the Site Editor and the Post editor. 

## To reproduce

1. Add a Navigation block, hit "Start empty". 
2. Select the plus icon to add a child block.
3. See that the Page Link block is missing. 

## Screenshot

Screen Shot 2021-03-18 at 11 26 49 AM

---

Tested with WordPress 5.7, Gutenberg `trunk` (Version 10.2.0)

### PR DESCRIPTION
**Pull request by gwwar**
Fixes https://github.com/WordPress/gutenberg/issues/29984 where navigation link variations are missing in production builds.

The problem is that the following is called as a side effect of importing hooks.js in trunk. Since nothing is calling anything from hooks.js this was shaken out of the final build. This means that we saw links in our development build `npm run dev` but not when using `npm run build`
```js
addFilter(
	'blocks.registerBlockType',
	'core/navigation-link',
	enhanceNavigationLinkVariations
);
```

Props to @kjellr for finding this.

#### WP 5.7
| before | after |
|-----|-----|
| Screen Shot 2021-03-23 at 1 35 52 PM | 5 7-after | 

- Make sure your local instance is on WP 5.7 or below
- Checkout this branch `npm run build` and enable the gutenberg plugin. Note use the **build** and not  **dev** command.
- Add a navigation block
- Add a navigation link
Expected: all fallback variations appear: (link, post link, page link, category, tag)

#### WP Latest 
| before | after |
|-----|-----|
| before-latest | after-latest | 

- Make sure your local instance is on WP latest
- Checkout this branch `npm run build` and enable the gutenberg plugin. Note use the **build** and not  **dev** command.
- Add a navigation block
- Add a navigation link
Expected: variations appear (including custom variations from plugins). Each variation has the correct icon. Note that when using custom variations, there's a new post label that plugin authors have not had a chance to add:

To see the right labels, we can edit the plugin and add `item_link` and `item_link_description` to the taxonomy or post-type definition.

109557321-cbe93300-7a8c-11eb-87d5-e7c169b88581

### CODE REVIEW

File: packages/block-library/src/navigation-link/hooks.js [hunk 1]
```diff
@@ -30,14 +30,14 @@ function getIcon( variationName ) {
 	}
 }
 
-function enhanceNavigationLinkVariations( settings, name ) {
+export function enhanceNavigationLinkVariations( settings, name ) {
 	if ( name !== 'core/navigation-link' ) {
 		return settings;
 	}
```
Comment (gwwar) [inline packages/block-library/src/navigation-link/hooks.js:35]: cc @kjellr @shaunandrews if this branch doesn't work, it's much appreciated if folks add a `console.log( settings.variations )` here OR `debugger;` and send me a screenshot of what you see. Feel free to DM me if that didn't make sense.

**Review by talldan — APPROVED** [review]
😱 Wow, great catch—this is something I could imagine spending hours debugging to find!

**Comment by gziolo** [comment]
You probably should also whitelist the file in:

https://github.com/WordPress/gutenberg/blob/1d89cd94a3f07f56d9f4f8a02dd556535acfdc61/packages/block-library/package.json#L24-L27

to tell webpack that it contains side effects otherwise, tree-shaking might still trigger in the future.

**Comment by kjellr** [comment]
Thank you for figuring this one out, @gwwar! 🙌

**Comment by gwwar** [comment]
TIL there's a whitelist for side-effects, @gziolo I can follow up 👍

**Comment by gziolo** [comment]
> TIL there's a whitelist for side-effects, @gziolo I can follow up 👍

There is a lot to learn there:

https://github.com/WordPress/gutenberg/tree/trunk/packages#optimizing-for-bundlers
https://github.com/WordPress/gutenberg/blob/trunk/packages/side-effects.md
