### PR TITLE
Make Write mode and Zoom out block options menus consistent

### LINKED ISSUE #67658: Make Write mode and Zoom out block options menus consistent
### Description 

The block options menus in write mode and zoom out mode differ in available actions today. To ensure consistency, the menu in write mode should be updated to match the zoom out menu, which includes options for “Copy,” “Duplicate,” and “Delete.”

### Steps to Reproduce:

1.	Open the editor in write mode.
2.	Click on the options menu for a top-level group block (i.e. pattern).
3.	Note the available menu options.
4.	Switch to zoom out mode.
5.	Click on the options menu for a top-level group block (i.e. pattern).
6.	Compare the menu options between write mode and zoom out mode.

### Expected:

The block options menus in both modes should be identical, with options for “copy,” “duplicate,” and “delete.”

### Visuals 

Write Mode: 

Image

Zoom out (correct one): 

Image

### PR DESCRIPTION
**Pull request by draganescu**
## What?

Closes  #67658

## Why?

 To ensure consistency, the menu in write mode should be updated to match the zoom out menu, which includes options for “Copy,” “Duplicate,” and “Delete.”

## How?

* Hide the patterns menu items when block editing mode is content only
* Allow copy to show when block editing mode is content only

## Testing Instructions

1. Enable the write mode experiment
2. Go to a page
3. Enable write mode
4. Select some block
5. Click on the three vertical dots menu in the toolbar
6. Notice only copy, duplicate, delete are available
7. Enable zoom out
8. Select some section
9. Click on the three vertical dots menu in the toolbar
10. Notice only copy, duplicate, delete are available

### Testing Instructions for Keyboard

N/A

## Screenshots or screencast 

https://github.com/user-attachments/assets/b372ee02-aa45-4756-8e86-71d264b154f4

### CODE REVIEW

File: packages/block-editor/src/components/block-settings-menu/block-settings-dropdown.js [hunk 1]
```diff
@@ -316,14 +314,16 @@ export function BlockSettingsDropdown( {
...
 								) }
-								<BlockSettingsMenuControls.Slot
-									fillProps={ {
-										onClose,
-										count,
-										firstBlockClientId,
-									} }
-									clientIds={ clientIds }
-								/>
+								{ ! isContentOnly && ! isZoomOut && (
```
Comment (talldan) [inline packages/block-editor/src/components/block-settings-menu/block-settings-dropdown.js]: I wonder if `&& ! isZoomedOut` can be removed, because I think all the enabled blocks in Zoom Out are in content only mode anyway.

**Review by talldan — APPROVED** [review]
This is a good improvement over trunk.

I think it'd be good to consider adding e2e tests for this kind of change as it's very specific behavior, and regressions are hard to spot. I don't think it has to be complicated, probably just some simple assertions that sections in content only and zoom out show the right settings menu options, and paragraphs don't have a settings menu.

I did manually test the settings menu in different scenarios that utilize content only:
- Write Mode works as expected
- Zoom Out works as expected
- Page Editing / Synced Patterns / Template Locking don't show any regressions

----

As an aside, I still notice some unusual behaviors that might be good to follow up on, but I don't think they were introduced by this PR, they're also present in trunk:

### Button blocks have a settings menu
Most content blocks don't have a settings menu in write mode:
Screenshot 2024-12-10 at 12 50 45 pm

But for some reason the button block does have one, with just the copy option:
Screenshot 2024-12-10 at 12 51 11 pm

### List Item blocks have a settings menu and can be inserted/removed
I'm not sure this is on purpose or not, but list items also have a settings menu:
Screenshot 2024-12-10 at 12 53 28 pm

They can also be inserted/removed in Write Mode. They can be indented, but not un-indented. I have no idea what's going on here!

File: packages/block-editor/src/components/block-settings-menu/block-settings-dropdown.js (hunk 1 above)
Comment (draganescu) [reply packages/block-editor/src/components/block-settings-menu/block-settings-dropdown.js]: Great spot. Removed as zoom out does inteed set sections as content only.
