### PR TITLE
`ToggleGroupControl`: react correctly to external controlled updates

### LINKED ISSUE #56667: `ToggleGroupControlAsRadioGroup` value is always undefined
### Description

The `ChildLayoutControl` has [an effect](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/child-layout-control/index.js#L43) that runs only on first mount, and resets the value of the control if in incorrect combination of attributes is detected. It then passes that value to `ToggleGroupControl`. 

The problem is that `ToggleGroupControlAsRadioGroup` inside `ToggleGroupControl` never re-renders after the value changes. Looking into it a bit, it seems that this happens due to the effect in `useComputeControlledOrUncontrolledValue` running after [the code beneath it](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/toggle-group-control/toggle-group-control/utils.ts#L41), so that the component returns its original value as it the effect had never run.

This regression seems to have been introduced in #50278, which made its way into WP 6.4. The `ToggleGroupControl` was working correctly in previous releases.

### Step-by-step reproduction instructions

1. Create a Row block and add a Paragraph inside it;
2. Select the paragraph and in the sidebar, under Dimensions, set width to "Fixed";
3. An input should become visible underneath. Don't add anything in there for now;
4. Save and reload the page;
5. Reselect the Paragraph and see that the width is still set to "Fixed" but no input is now visible, and the help text is incorrect, as can be seen in this screenshot:
Screenshot 2023-11-30 at 5 17 22 pm

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ciampo**
Fixes #56667
Fixes the issue described in #56500

## What?

This PR improves the internal logic in `ToggleGroupControl` used to detect whether the component is used in controlled or uncontrolled more

## Why?

The previous logic wasn't reacting correctly to new values being passed to the component, and as a result it wasn't causing the component to update with the new values.

## How?

Using `useState` instead of `useRef` to track internal state causes the component to re-render more eagerly when the "controlled" flag flips.

## Testing Instructions

- In the editor:
    1. Apply changes from this PR
    2. Follow the steps described in #56667
    3. Check that the ToggleGroupControl component resets correctly
- With unit tests:
    1. Undo the [fix commit](https://github.com/WordPress/gutenberg/pull/56678/commits/4fe589f83e9b71fa0d4b3b6560d99cfa467fb1d5)
    2. Run `ToggleGroupControl`'s unit tests — the [newly added test](https://github.com/WordPress/gutenberg/pull/56678/commits/3d998efe0db53ab6935d8e2387c4b22dc8e0349a) should fail without the fix in place.
    3. Add the fix back
    4. All ToggleGroupControl unit tests should pass

### CODE REVIEW

File: packages/components/src/toggle-group-control/toggle-group-control/utils.ts [hunk 1]
```diff
@@ -21,24 +21,28 @@ type ValueProp = ToggleGroupControlProps[ 'value' ];
...
 			// - the `value` prop is not `undefined`
 			// - the `value` prop was not previously `undefined` and was given a new value
-			hasEverBeenUsedInControlledMode.current =
+			setHasEverBeenUsedInControlledMode(
 				valueProp !== undefined &&
-				previousValueProp !== undefined &&
-				valueProp !== previousValueProp;
+					previousValueProp !== undefined &&
+					valueProp !== previousValueProp
+			);
```
Comment (jsnajdr) [inline packages/components/src/toggle-group-control/toggle-group-control/utils.ts]: I'd change this to:
```js
if ( ! hasEver && definedAndDifferent( prevVal, val ) {
  setHasEver( true );
}
```
That prevents scheduling `setState` calls that will be noops anyway, changing `false` to `false`.

Also, once in controlled mode, the component can't change back to uncontrolled, right? The component always starts as uncontrolled, and switches to controlled on the first re-render that has a different `valueProp`.

Then a better name for `hasEver...` is simply `inControlledMode`.

**Review by jsnajdr — APPROVED** [review]
Yes, this fixes the bug. The problem was that the render where `valueProp` changed from `foo` to `bar` was still returning `value: undefined`, because the `hasEver` value is still `false`. It's updated only a bit later in the effect.

This PR immediately schedules a next render where `hasEver` will be `true` and it will return `value: 'bar'`.

An implementation that doesn't need the extra render but returns the right value immediately when `valueProp` changes:
```js
function useComputedControlled( value ) {
  const prevValue = usePrevious( value );
  const prevControlled = useRef( false );
  const isControlled = prevControlled.current || ( prevValue.current !== undefined && value !== undefined && prevValue.current !== value );
  useEffect( () => {
    prevControlled.current = isControlled;
  }, [ isControlled ] );
    
  if ( isControlled ) {
    return { value: value ?? '', defaultValue: undefined };
  }

  return { value: undefined, defaultValue: value };
}

File: packages/components/src/toggle-group-control/toggle-group-control/utils.ts (hunk 1 above)
Comment (ciampo) [reply packages/components/src/toggle-group-control/toggle-group-control/utils.ts]: > That prevents scheduling setState calls that will be noops anyway, changing false to false.

That's a good suggestion, thank you!

> Also, once in controlled mode, the component can't change back to uncontrolled, right?

Yes, this custom behaviour was necessary to be backwards compatible with how the component used to work before supporting uncontrolled mode.

I'm not going to implement this suggestion since I decided to refactor the hook following your other suggestion

**Comment by ciampo** [comment]
> An implementation that doesn't need the extra render but returns the right value immediately when valueProp changes:

I like this! I went ahead and refactored the hook following your suggestion, plus with some minor adjustments (for example, `prevValue` doesn't have a `current` property).

I'll wait for folks to have a final round of review before merging

**Review by tellthemachines — APPROVED** [review]
This fixes the issue and doesn't seem to break other instances of `ToggleGroupControl`. Changes LGTM and thanks for adding the test!

**Review by jsnajdr — APPROVED** [review]
Thanks for accepting my suggestions :wink: Now I approve the PR even more.
