### PR TITLE
Block Editor: fix BlockSwitcher to prevent transforms on reusable blocks

### LINKED ISSUE #67710: Extraneous transforms on synced patterns
### Description:

Transforms for synced patterns are overly generous, even if transforms simply wrap content. This behavior can create confusion and lead to unintended transformations. Limiting transforms from synced patterns would provide a more intuitive experience.

### Steps to Reproduce:
1.	Insert a synced pattern.
2.	Attempt to transform the pattern.
3.	Observe the availability of excessive transform options.

### Expected:

Transform options should be limited for synced patterns to avoid unnecessary or unintended transformations.

### Visual 

Image

### PR DESCRIPTION
**Pull request by shrivastavanolo**
## What?

Closes https://github.com/WordPress/gutenberg/issues/67710

This PR updates the BlockSwitcher component to disable block transformations for reusable (synced) blocks. Template parts were already excluded; now reusable blocks will also hide transform options in the dropdown.

## Why?

Currently, the BlockSwitcher allows transformations on reusable blocks. Transforming a reusable block can cause unexpected behavior, since all instances of the block are linked. Preventing transforms for these blocks ensures consistency across instances and prevents accidental data loss.

See https://github.com/WordPress/gutenberg/issues/67710#issuecomment-2550799023

## How?

- Added an isReusable check in BlockSwitcherDropdownMenuContents.
- Updated hasPossibleBlockTransformations to be false for reusable blocks

## Testing Instructions
1. Create a reusable block (or synced pattern).
2. Select it in the editor and open the Block Switcher.
    - Before: Transform options are available.
    - After: Transform options are hidden/disabled.
3. Select a normal block. Verify that the transform dropdown still works as expected.

### Before 
https://github.com/user-attachments/assets/6931c0ee-ad7e-483e-8e55-32b25a29721c

### After
https://github.com/user-attachments/assets/2528380b-b141-4f29-9aff-f104f05e991d

### CODE REVIEW

File: packages/block-editor/src/components/block-switcher/index.js [hunk 1]
```diff
@@ -108,8 +108,12 @@ function BlockSwitcherDropdownMenuContents( {
 	 */
 	const isSingleBlock = blocks.length === 1;
 	const isTemplate = isSingleBlock && isTemplatePart( blocks[ 0 ] );
+	const isReusable = isSingleBlock && isReusableBlock( blocks[ 0 ] );
 	const hasPossibleBlockTransformations =
-		!! possibleBlockTransformations.length && canRemove && ! isTemplate;
+		!! possibleBlockTransformations.length &&
+		canRemove &&
+		! isTemplate &&
+		! isReusable;
```
Comment (Mamaduka) [inline packages/block-editor/src/components/block-switcher/index.js]: Let's generalize the check and update the comment above; otherwise, it looks outdated.

Here's an example diff:

```diff
diff --git a/packages/block-editor/src/components/block-switcher/index.js b/packages/block-editor/src/components/block-switcher/index.js
index 8bd02e9357d..537d919c270 100644
--- a/packages/block-editor/src/components/block-switcher/index.js
+++ b/packages/block-editor/src/components/block-switcher/index.js
@@ -102,18 +102,16 @@ function BlockSwitcherDropdownMenuContents( {
 		selectForMultipleBlocks( transformedBlocks );
 	}
 	/**
-	 * The `isTemplate` check is a stopgap solution here.
+	 * The `isSynced` check is a stopgap solution here.
 	 * Ideally, the Transforms API should handle this
 	 * by allowing to exclude blocks from wildcard transformations.
 	 */
 	const isSingleBlock = blocks.length === 1;
-	const isTemplate = isSingleBlock && isTemplatePart( blocks[ 0 ] );
-	const isReusable = isSingleBlock && isReusableBlock( blocks[ 0 ] );
+	const isSynced =
+		isSingleBlock &&
+		( isTemplatePart( blocks[ 0 ] ) || isReusableBlock( blocks[ 0 ] ) );
 	const hasPossibleBlockTransformations =
-		!! possibleBlockTransformations.length &&
-		canRemove &&
-		! isTemplate &&
-		! isReusable;
+		!! possibleBlockTransformations.length && canRemove && ! isSynced;
 	const hasPossibleBlockVariationTransformations =
 		!! blockVariationTransformations?.length;
 	const hasPatternTransformation = !! patterns?.length && canRemove;
```

**Review by Mamaduka — APPROVED** [review]
Thanks for working on this, @shrivastavanolo!
