### PR TITLE
Env: Fix loopback requests when running on non-default ports

### LINKED ISSUE #20569: @wordpress/env: Loopback requests fail
**Describe the bug**
WordPress isn't able to complete a loopback request when running under `wp-env`.

**To reproduce**
1. `npx wp-env start`
2. Navigate to http://localhost:8888/wp-admin/site-health.php

There's two errors related to this:

- The REST API encountered an error
- Your site could not complete a loopback request

**Expected behavior**
There should only be one critical error (the one about debug mode.)

**Additional context**
WordPress is trying to make a request to `http://localhost:8888` from the underlying Docker container but this fails because Apache is listening on port 80. One solution would be to set up the `docker-compose.yml` config to map `localhost` to the host machine.

### PR DESCRIPTION
**Pull request by nerrad**
## What?

Makes Apache inside the wp-env WordPress container also listen on the host-mapped port, so PHP loopback requests (WP-Cron, REST API loopback, Site Health diagnostic, `add_editor_style()`) succeed instead of getting `cURL error 7: Connection refused`.

Fixes #20569

## Why?

Docker maps host port (e.g. `8888`) → container port `80`. wp-env sets `WP_HOME = http://localhost:8888`. But Apache inside the container only listens on `80`. When PHP code does `wp_remote_get( WP_HOME )`, it hits `localhost:8888` on the container's loopback interface where nothing is listening.

This has been a known issue since 2020 (#20569) with various workarounds (`ALTERNATE_WP_CRON`, `host.docker.internal` hosts hack, etc.), but the proper fix — validated in the upstream [docker-library/wordpress#611 comment](https://github.com/docker-library/wordpress/issues/611#issuecomment-1378316911) — is to make Apache listen on both ports.

## How?

Adds a `getLoopbackPortConfig( port )` helper to `docker-config.js` that returns two Dockerfile RUN steps:

```dockerfile
RUN echo 'Listen <PORT>' >> /etc/apache2/ports.conf
RUN sed -i 's|<VirtualHost \*:80>|<VirtualHost *:80 *:<PORT>>|' /etc/apache2/sites-enabled/000-default.conf
```

These are injected into the generated `WordPress.Dockerfile` and `Tests-WordPress.Dockerfile` only when `port !== 80 && port !== 443`. The helper returns `''` for port 80/443, keeping the Dockerfile identical to today's output for those cases.

The port comes from `config.env[env].port`, which is already finalised by the time `writeDockerFiles` runs and is the same integer used in the docker-compose port mapping.

**Containers not touched:** `cli`/`tests-cli` (Alpine, no Apache), `phpmyadmin`, `mysql`/`tests-mysql`.

### Unit tests (new)

8 tests in `packages/env/lib/test/docker-config.js`:
- `getLoopbackPortConfig` returns correct Apache directives for non-default port
- Uses anchored sed pattern (no greedy `80` replacement)
- Returns `''` for port 80 and 443
- `wordpressDockerFileContents` injects per-env port for development and tests
- Does not inject anything when port is 80
- Still emits base FROM line and dependency steps

```sh
npx wp-scripts test-unit-js --config test/unit/jest.config.js --testPathPattern='packages/env/lib/test/docker-config' --no-coverage
```

All 153 tests across the full env package pass.

### Manual verification steps

1. **Apache listening:** `npx wp-env run wordpress 'cat /etc/apache2/ports.conf'` → shows both `Listen 80` and `Listen <port>`
2. **VirtualHost updated:** `npx wp-env run wordpress 'cat /etc/apache2/sites-enabled/000-default.conf' | grep VirtualHost` → `<VirtualHost *:80 *:<port>>`
3. **Loopback succeeds:** `npx wp-env run wordpress 'curl -sS -o /dev/null -w "%{http_code}\n" http://localhost:<port>/wp-login.php'` → 200/302
4. **WP-Cron runs:** `npx wp-env run cli wp cron event run --due-now` → no cURL errors
5. **Site Health:** `http://localhost:<port>/wp-admin/site-health.php` → no loopback failure
6. **Port 80 is a no-op:** only default `Listen 80` and `<VirtualHost *:80>`
7. **Rebuild on port change:** switching `WP_ENV_PORT` rebuilds with new port

## Known limitation — `wp cron test` from the CLI container

`npx wp-env run cli wp cron test` still fails with `cURL error 7`. `wp cron test` spawns a loopback from inside the CLI container, whose `localhost` is the CLI container itself (Alpine, no Apache) — not the wordpress container. Fixing this needs a different mechanism (e.g. resolving `WP_HOME`'s host to the wordpress service from the CLI container).

**Question for reviewers:** handle in this PR, or split into a follow-up? I'm on the fence but leaning toward followup.

### CODE REVIEW

File: packages/env/lib/test/docker-config.js [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+const baseConfig = ( port, testsPort = port + 1 ) => ( {
+	xdebug: 'off',
+	spx: 'off',
+	env: {
+		development: { port, phpVersion: null },
+		tests: { port: testsPort, phpVersion: null },
+	},
+} );
+
+describe( 'getLoopbackPortConfig', () => {
```
Comment (nerrad) [inline packages/env/lib/test/docker-config.js]: Isn't there an existing test file that this test can be added to?

Comment (nerrad) [reply packages/env/lib/test/docker-config.js]: Addressed in 9cfe7d2

**Comment by nerrad** [comment]
I'm looking into the failing E2E tests because they seem to only be failing on this branch. It might be a side-effect of fixing the loopback requests but I'll double-check.

**Comment by nerrad** [comment]
So I ran the failing tests locally both with the fix in this branch and without and got a failure both times. It doesn't appear that the failing E2E test is related to the work in this branch. It seems like the issue is the test itself.

**Comment by nerrad** [comment]
@jeryj pinging you because I think you've had some involvement with the test specs that are failing. Anything stand out to you about why they might be failing? Or is it something that should be looked into as an artifact of all the work that has been done around the areas being tested (or is there someone else who should be pinged)?

**Comment by jeryj** [comment]
@nerrad I bet it has to do with permalinks. The failure is related to the expected URL returned:

```
Expected substring: "localhost"
Received string:    "Link to:Test Page 1 – gutenberg/?page_id=345Homepage"
```

For testing entity bound links, we needed to use pretty permalinks to reliably test that updates to the slug would be picked up by bound navigation links, so the expected returned URL had a format like `http://localhost:8889/test-page-1-2/`.  Based on this test result, my guess is that pretty permalinks aren't working correctly. 

The `localhost` failure above isn't that important. The important one is [checking if the slug updated](https://github.com/WordPress/gutenberg/blob/add/shared-site-editor-list-vew/test/e2e/specs/editor/blocks/navigation.spec.js#L1253).

**Review by ObliviousHarmony — APPROVED** [review]
Thanks @nerrad,

I ran through all of the testing instructions and it works great, the code is aligned with existing functionality.

Regarding the E2E failure, like you, I reproduced it on both `trunk` and this branch. For testing purposes I destroyed my entire local environment when switching branches to make sure nothing from these changes persisted in the container. I poked at it with Claude and @jeryj's feedback but it has absolutely no idea how this branch could relate.

**Comment by t-hamano** [comment]
This PR appears to affect the behavior of the Navigation block. Please follow these steps:

1. Open a post.
2. Insert the navigation block.
3. Open the inserter and add the "Sample Page".
4. Confirm the preview title text.

If my local environment setup is correct, the test results should be as follows. Would this information be helpful?

## Before

The link title is `postTitle`. 

image


I am also seeing the following 404 error.

```
{"code":"rest_cannot_view_url_details","message":"Sorry, you are not allowed to process remote URLs.","data":{"status":401}}
```

## After

The ling thjtle is `{postTile} – {siteTitle}`

Please disregard the different port numbers, as this is intentional.

image

**Comment by jeryj** [comment]
Good find @t-hamano! `{postTile} – {siteTitle}` likely means the URL is being evaluated as an external link. It may be because entity binding is broken. Pinging @getdave for insights on this too.

**Comment by jeryj** [comment]
The local navigation block e2e test failures were due to the Home keypress wasn't working in Playwright for Mac OS. I have a fix in https://github.com/WordPress/gutenberg/pull/77102 that should help make debugging the test failures here more reliable.

**Comment by t-hamano** [comment]
I rebased this PR on top of trunk. This ensures that artifacts are correctly generated when E2E tests fail, which should help in investigating the problem. See #77093

**Comment by t-hamano** [comment]
> `{postTile} – {siteTitle}` likely means the URL is being evaluated as an external link.

According to Playwright's report, this hypothesis seems correct. The preview title, which was previously `Cat`, has changed to `Cat – gutenberg` in this PR.

399b26b05b239fbb115e6f84715251bb3968c9dd

However, upon further consideration, isn't this the intended behavior? That is, the loopback request is fixed in the local environment updated by this PR, causing [the request to `/wp-block-editor/v1/url-details`](https://github.com/WordPress/gutenberg/blob/f959ed24e9dc1fb0fd75f73740a6994986d1fdd7/packages/core-data/src/fetch/__experimental-fetch-url-data.js#L48) to return the correct response.

I tested this on my own site, and the link preview displays the site title even though it's my own site page:

navigation


Perhaps we should fix navigation block tests?

**Comment by jeryj** [comment]
@t-hamano Thanks for more debugging! I see what you mean that this would be the expected behavior with the loopback fix. The LinkControl [LinkPreview prioritizes richData?title over the navigation link block title](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/link-control/link-preview.js#L71-L73). 

I think we want bound links to show the page title, and not the rich data title though, so I don't think we should update the navigation tests. I opened https://github.com/WordPress/gutenberg/pull/77155/ to show the bound entity page title instead of the rich data title. 

If #77155 can get merged and rebased here, then I think tests will start passing.

Sorry for all the back and forth on this one. I've had the flu the last couple days, so I'm trying not to work much :)

**Comment by nerrad** [comment]
Thanks @jeryj and @t-hamano for the reviews and figuring out the issue with the failing test 🙌🏻  It's a good signal that fixing the loopback issue in `wp-env` is an important thing to get in so behaviour in testing is closer to live sites. I had held off merging the PR because I wasn't satisfied that the failing test was understood fully yet and intended to get back to it today.

**Comment by jeryj** [comment]
I rebased now that https://github.com/WordPress/gutenberg/pull/77102 and https://github.com/WordPress/gutenberg/pull/77155 are merged. Hopefully tests will pass or at least give clearer signal to what the root is 🤞🏻

**Comment by nerrad** [comment]
The Playwright failure on `navigation.spec.js:1865` (`toContainText('localhost')`) is a side effect of this PR's loopback fix, not unrelated flake. The chain:

1. The test creates a page-bound nav link and asserts the inspector "Link to:" preview button contains `'localhost'`.
2. `useLinkPreview` (`packages/block-library/src/navigation-link/shared/use-link-preview.js`) computes its display title as `entityRecord.title || richData.title || safeDecodeURI(url)`.
3. During the assertion's 5s window the page `entityRecord` hasn't resolved yet, so the chain falls through to `useRemoteUrlData`, which calls `/wp-block-editor/v1/url-details` — a server-side **loopback** fetch back to `http://localhost:<port>/?page_id=X`.
4. **Pre-fix:** Apache inside the container only listened on 80, so loopback to the wp-env port failed. `richData` stayed empty, `displayTitle` fell to the raw URL string, which contained `'localhost'`. The assertion passed *by accident*.
5. **Post-fix:** Loopback succeeds, `richData.title` resolves, and the URL no longer leaks into the preview text. `'localhost'` disappears and the assertion fails.

Fixed in e0a60df by asserting on the entity title (`'Test Page 1'`), which is the stable invariant in both resolution paths and matches what the test fixture itself creates. Supersedes the closed #77144.

*\*left by agent on behalf of Darren*

**Comment by nerrad** [comment]
Okay, I had my agent post a summary of what a debugging session surfaced. I tweaked the test to just check for the existence of the title. It looks like it was still dependent on a failing loopback - switching to check for whether the title contains the text from the test post should address this. I'm assuming the point of this test is to verify that the correct post is bound on the link.
