### PR TITLE
contentOnly: Fix canInsertBlockType dependencies to fix selector caching issues

### LINKED ISSUE #71955: No add before/after option after Edit contents click from inner block selection
### Description

If an inner block is selected when Edit contents is pressed, the block that is selected is not updated to offer the add before/after block option.

### Step-by-step reproduction instructions

1. Turn on the Gutenberg > Experiment: contentOnly: make patterns contentOnly by default upon insertion
2. Go to the site editor
3. Open the sidebar inspector
4. Select a pattern that defaults to contentOnly (or insert a new pattern, most should work)
4. Select a block within the pattern (not the top level group)
3. Press Edit contents button
5. Click three dots from toolbar
6. No add/before after option is available on the selected block

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/1e255a47-9e53-47a2-822c-f3169127db3a

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### LINKED ISSUE #71956: Can't drag into group after pressing Edit Contents when inner block is selected
### Description

The same root issue may be causing https://github.com/WordPress/gutenberg/issues/71955 as well, as both are caused when clicking Edit contents with an inner block selection.

Dragging into groups and columns is very erratic after clicking Edit contents while an inner block is selected. Testing this with a more complex column setting really highlights the confusion, for this bug report, I reproduced this with a minimal case of a group block. My guess is that fixing that case will also fix the more complex column situations too.

### Step-by-step reproduction instructions

1. Turn on the Gutenberg > Experiment: contentOnly: make patterns contentOnly by default upon insertion
2. Go to the site editor
3. Open the sidebar inspector
4. Select a pattern that defaults to contentOnly (or insert a new pattern, most should work) that has multiple columns or at least a group block within it (most patterns satisfy this)
4. Select a block within the pattern (not the top level group)
3. Press Edit contents button
4. Open the list view
5. Try dragging the blocks from the pattern around into various groups/columns in the pattern
6. Some will work, some will not. Usually there's at least one group or column that is blocked from accepting new blocks. It seems to be the first column more often than not, but I'm having a hard time isolating the exact steps. 

### Screenshots, screen recording, code snippet

_No response_

### Environment info

https://github.com/user-attachments/assets/c01084f3-289f-4ff5-bd29-310b73403cc2

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by andrewserong**
## What?

Fixes #71955
Fixes #71956

Fix issues with contentOnly mode when clicking "Edit contents" after selecting a block within a pattern.

In `trunk`, doing so results in the Add Before / Add After / Duplicate options being unavailable, and it not being possible to drag blocks within groups within the pattern.

## Why?

This appears to be because when we update the parent block to no longer be recognised as a pattern for the purposes of content only mode, the cache for the canInsertBlockType selector is not invalidated.

To put it differently, the unmemoized version of the selector performs lookups to see if its parents are section blocks / tries to figure out the block editing mode. However the current list of cache values does not include anything about the state of the parents or the _derived_ block editing mode of the block in question.

## How?

~In the list of `getInsertBlockTypeDependants` add a call to `getParentSectionBlock` so that we check that for the current clientId. This ensures that if the parent section block is changed, the cache is (effectively) invalidated.~

~However, this is likely an expensive call, so is probably not the ideal fix. My hope is that this PR can help us come up with a better fix. (The unit tests are failing because this change expects a broader set of things in `state`, I've left them failing while we investigate the right fix for this)~

Thanks to Dan's suggestion, I've updated this PR to use the `getBlockEditingMode( state, rootClientId )` which is relatively inexpensive as it just uses `has` checks on the computed values that are (elsewhere) updated via `getDerivedBlockEditingModesForTree`. This appears to be the right fix now, I believe, as the check is inexpensive, but it's looking in the right place for determining the current state of the block.

## Testing Instructions

1. Turn on the Gutenberg > Experiment: contentOnly: make patterns contentOnly by default upon insertion
2. Go to the site editor
3. Open the sidebar inspector
4. Select a pattern that defaults to contentOnly (or insert a new pattern, most should work)
5. Select a block within the pattern (not the top level group)
6. Press Edit contents button
7. Click three dots from toolbar
8. You should see the Add Before, Add After, and Duplicate options
9. You should also be able to drag within the pattern

## Screenshots or screencast 

For before videos, see #71955 and #71956. With this PR applied, this is possible:

https://github.com/user-attachments/assets/55f9f388-efa8-431d-846d-e2042b218cbb

### CODE REVIEW

File: packages/block-editor/src/store/utils.js [hunk 1]
```diff
@@ -141,5 +144,6 @@ export const getInsertBlockTypeDependants =
 			state.blockEditingModes,
 			select( STORE_NAME ).__unstableGetEditorMode( state ),
 			getSectionRootClientId( state ),
+			getParentSectionBlock( state, rootClientId ),
```
Comment (talldan) [inline packages/block-editor/src/store/utils.js]: It makes sense that it's a memoization issue, though I can't see where `getParentSectionBlock` is used in `canInsertBlockTypeUnmemoized`.

I do see `isSectionBlock`, so I wondered if that should be present ... and also whether it solves the bugs if it's in place of `getParentSectionBlock`.

Comment (talldan) [reply packages/block-editor/src/store/utils.js]: `derivedBlockEditingModes` are also missing, so that might be another one (and it might be the cause of the bug, since section blocks result in `derivedBlockEditingModes` being set on their inner blocks). `state.blockEditingModes` is present in the list, but I notice any block receiving a blockEditingMode will invalidate the selector, whereas I think it should only care about `rootClientId`. 

Makes me wonder if it should be replaced with `getBlockEditingMode( state, rootClientId )`, which returns both the explicit blockEditingModes and the derived ones. That's a much cheaper selector now after all the refactoring.

Comment (andrewserong) [reply packages/block-editor/src/store/utils.js]: Thanks for the review, Dan! I ran out of time to try these out today, but I'll continue on with this next week 👍

Comment (andrewserong) [reply packages/block-editor/src/store/utils.js]: Thanks again @talldan, I've updated this to use `getBlockEditingMode( state, rootClientId )` instead of `state.blockEditingModes` and that appears to have done the trick.

To clarify why I reached for `getParentSectionBlock` when the unmemoized selector doesn't use it — `isSectionBlock` was insufficient as I needed to perform a lookup on the parents of the block in question. That is, from the block we're currently looking at, we need to know if something has changed further up the tree. `getBlockEditingMode( state, rootClientId )` appears to work perfectly for this (as you suggest), as it's using inexpensive `has` checks on state that is updated when the parent changes mode via the regeneration of the derived block editing modes in `getDerivedBlockEditingModesForTree`, rather than us performing expensive lookups when checking the block itself.

So that was exactly the kind of check I was hoping we could do! I've updated the unit tests in a few places where we weren't setting `blockEditingModes: new Map()`, and they're passing. I'll just see if the e2es pass now.

**Review by talldan — APPROVED** [review]
Two bugs with one PR, nice work!

**Comment by andrewserong** [comment]
Thanks for the help, Dan! 🙇
