### PR TITLE
Fix center aligned images styles

### LINKED ISSUE #39291: Image Block: Image with `aligncenter` class no longer centered when used in a nested block
### Description

When you add an image block into a group or column and set the alignment to center the image is no longer centered. It's only centered if the block is added on the top-level.

This was likely introduced by #38613 and/or #38657 while the top-level alignment is working due to changes in #38947.

This style is now no longer applied: https://github.com/WordPress/gutenberg/blob/e8639285e2a60a86fc5979fffcf202c746029d0d/packages/block-library/src/image/style.scss#L59-L62

Only this, which has no effect: https://github.com/WordPress/gutenberg/blob/e8639285e2a60a86fc5979fffcf202c746029d0d/packages/block-library/src/image/style.scss#L15-L17

@youknowriad, @jasmussen What would be the correct fix here?

### Step-by-step reproduction instructions

1. Add a group block, set some background color
2. Add an image block into the group block
3. Resize the image so it's smaller than the group block width
4. Change image alignment to center
5. Notice that the image is not centered

### Environment info

- Gutenberg 12.7 and trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by youknowriad**
closes #39291 

## What?

Centered image blocks inside containers (group blocks) in a block theme were not centered properly. This PR fixes that.

## How?

The "flow" (default) layout didn't have explicit styles for centered blocks that said, the default rule targeting all children implicitly targeted the centered blocks and added margin autos. That default rule is mainly there for wide/full aligned blocks. That said, that default rule is conditionally rendered, it's only added if the layout of the current container defines "widths", meaning it supports wide and full widths and has a centered content area. 

So the PR defines an explicit rule adding the margins for centered aligned blocks.

## Testing Instructions

1- Insert a group block
2- Insert an image block inside that group block
3- Resize the image so it's small
4- Center the image block
5- It should appear centered on both frontend and editor.

Ideally we should test on different themes (classic and block themes)

### CODE REVIEW

File: lib/block-supports/layout.php [hunk 1]
```diff
@@ -62,8 +62,9 @@ function gutenberg_get_layout_style( $selector, $layout, $has_block_gap_support
 			$style .= "$selector .alignfull { max-width: none; }";
 		}
 
-		$style .= "$selector .alignleft { float: left; margin-inline-start: 0; margin-inline-end: 2em; }";
-		$style .= "$selector .alignright { float: right; margin-inline-start: 2em; margin-inline-end: 0; }";
+		$style .= "$selector > .alignleft { float: left; margin-inline-start: 0; margin-inline-end: 2em; }";
+		$style .= "$selector > .alignright { float: right; margin-inline-start: 2em; margin-inline-end: 0; }";
```
Comment (youknowriad) [inline lib/block-supports/layout.php:66]: I updated the the two selectors above and added the `>` there to match the editor. For me that's the right thing to do, it was just something that has been missed originally. We don't intended to define styles for any grand children here, only direct children. (Technically it's not related to this PR but I thought I'd just fix it here)

**Comment by jasmussen** [comment]
This is testing well for me. Here's a fresh block theme:
Screenshot 2022-03-14 at 11 26 12
Screenshot 2022-03-14 at 11 26 16

Here's an older block theme that hasn't been updated in a while:
Screenshot 2022-03-14 at 11 26 31
Screenshot 2022-03-14 at 11 26 35

Here's TwentyFourteen and TwentyTwenty classic themes:
Screenshot 2022-03-14 at 11 26 48
Screenshot 2022-03-14 at 11 26 52

Screenshot 2022-03-14 at 11 27 14
Screenshot 2022-03-14 at 11 27 20

**Review by ocean90 — CHANGES_REQUESTED** [review]
For me the image is still not centered when used in a column.

Bildschirmfoto 2022-03-15 um 09 44 23

Also left/right only works in the editor but not on the frontend in the column.

That's maybe the reason why the `>` doesn't exist for left/right alignment classes?

**Comment by youknowriad** [comment]
@ocean90 I think both of these issues are the same. The column block doesn't output "layout" styles. I think the ideal solution would be for the column block to opt-in into the layout but there might be some side effects to that change.

**Comment by youknowriad** [comment]
The last commit solves that. It adds "layout" support to the column block. It also means this panel is visible on the sidebar of the column block

Screen Shot 2022-03-15 at 10 32 44 AM

I think that's fine but wanted to confirm with @jasmussen here

**Comment by jasmussen** [comment]
I think it's fine as Columns is a container block like group.

I do think there's an opportunity to further refine and clarify the layout panel, and also to generally give a lot of love and attention to the Columns block. But those are separate issues.

**Comment by ocean90** [comment]
With the layout setting it's now working for me too. It may can get a bit confusing when seeing three inputs for setting a width though.



Saying that, the editor seems not to respect the width set for the image. Is this a known issue?

| Editor | Frontend |
| --- | --- |
|  |  |

**Comment by youknowriad** [comment]
> Saying that, the editor seems not to respect the width set for the image. Is this a known issue?

I'm not sure I understand the issue here, would you be able to send me some content with that? Those widths define the max-width for child blocks but I know that image blocks can grow beyond their container in Gutenberg (on purpose)

**Comment by ocean90** [comment]
> Those widths define the max-width for child blocks but I know that image blocks can grow beyond their container in Gutenberg (on purpose)

I guess you mean when they are resized by the user? Looks like I had mine resized at some point which was causing this. Inserting an image without resizing respects the max-width.

<details>
<summary>Example content</summary>


```html
<!-- wp:image {"align":"center","id":14,"width":512,"height":342,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image aligncenter size-full is-resized"><img src="https://user-images.githubusercontent.com/617637/158354719-55822d17-9449-46f8-a84f-20df1d5b8de3.jpeg" alt="" class="wp-image-14" width="512" height="342"/><figcaption>r3e3ed3</figcaption></figure>
<!-- /wp:image -->

<!-- wp:group {"backgroundColor":"pale-cyan-blue"} -->
<div class="wp-block-group has-pale-cyan-blue-background-color has-background"><!-- wp:image {"align":"center","id":14,"width":512,"height":342,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image aligncenter size-full is-resized"><img src="https://user-images.githubusercontent.com/617637/158354719-55822d17-9449-46f8-a84f-20df1d5b8de3.jpeg" alt="" class="wp-image-14" width="512" height="342"/><figcaption>r3e3ed3</figcaption></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. </p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"200px","backgroundColor":"pale-cyan-blue","layout":{"inherit":false,"contentSize":"100px"}} -->
<div class="wp-block-column has-pale-cyan-blue-background-color has-background" style="flex-basis:200px"><!-- wp:image {"align":"center","id":14,"width":205,"height":137,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image aligncenter size-full is-resized"><img src="https://user-images.githubusercontent.com/617637/158354719-55822d17-9449-46f8-a84f-20df1d5b8de3.jpeg" alt="" class="wp-image-14" width="205" height="137"/></figure>
<!-- /wp:image -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">ffffff</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:image {"align":"center","id":14,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image aligncenter size-full"><img src="https://user-images.githubusercontent.com/617637/158354719-55822d17-9449-46f8-a84f-20df1d5b8de3.jpeg" alt="" class="wp-image-14"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

</details>

**Review by ocean90 — APPROVED** [review]
