### PR TITLE
Fix Nav Block bug as Contributor user via fix to `*loadPostTypeEntities`

### LINKED ISSUE #18659: Navigation Block: not fully functional for contributor role due to `getEntityRecords` records issue
When using the Nav Block as a user with the `Contributor` Role to the "Create from Pages" option in the placeholder will never work. This is because of a potential "bug" with `getEntityRecords` (which is infact potentially a bug with the REST API - @youknowriad may be able to shed additional light on this).

As it stands Blocks need to avoid `getEntityRecords` in favour of `apiFetch` directly until this bug is resolved.

In order that Nav Block can land we need to swap out the usage of [this selector](https://github.com/WordPress/gutenberg/blob/d0e3c26ec295924d96a658640e2cc6fb118b2eca/packages/block-library/src/navigation/edit.js#L208) for `apiFetch()` directly.

**To reproduce**

1. Create a User with `Contributor` Role.
2. Create some Pages (_not_ Posts!).
3. Create a new Post and add the Nav Block.
4. See the `Create from all Top Pages` button is always disabled.

**Expected behavior**
The Block placeholder should load and show the option to create from Pages for all Roles.

**Screenshots**

Screen Capture on 2019-11-21 at 09-59-52

**Additional Context**

See also:

* https://github.com/WordPress/gutenberg/issues/18661
* https://core.trac.wordpress.org/ticket/45252

### PR DESCRIPTION
**Pull request by getdave**
Closes https://github.com/WordPress/gutenberg/issues/18659

The Nav Block placeholder has a button for `Create from all Top Pages`. To work the Block must have Page data available. If it isn't available then the button is `disabled`.

For higher Role users with greater permissions, this works absolutely fine. However, for the `Contributor` user the Pages data cannot be accessed. This appears to be due to the way we are accessing the Page data in our selectors/resolvers. Primarily the call to [`getEntityRecords` sets `context` to `edit` for the Page post type REST API query](https://github.com/WordPress/gutenberg/blob/c67cb27a3ea9e2ba3f5a569a864cd8c14df3097e/packages/core-data/src/resolvers.js#L75). Lower user types don't have permission to access the endpoint under the `edit` context and so the request fails.

The (new) direction for this PR is to use `apiFetch` directly within the component to avoid the selectors entirely and make a request to the API. This ensures the `Pages` data is _local_ to the component and allows us to set the `context` to `view` to ensure Pages are returned for all user Roles.

## Screenshots

This shows me as a User with the `Contributor` Role inserting the Block:

Screen Capture on 2019-11-21 at 16-26-28

## More Detail
Ultimately this traces back to [`loadPostTypeEntities`](https://github.com/WordPress/gutenberg/blob/d0e3c26ec295924d96a658640e2cc6fb118b2eca/packages/core-data/src/entities.js#L33).

On `master` the [`loadPostTypeEntities` resolver](https://github.com/WordPress/gutenberg/blob/d0e3c26ec295924d96a658640e2cc6fb118b2eca/packages/core-data/src/entities.js#L33) is returning a `WP_Error` REST API response.

The problem here is this line:

```js
yield apiFetch( { path: '/wp/v2/types?context=edit' } );
```

The usage of the `edit` context on the request URL is what is causing this. Try toggling the following request between `edit` and `view` in the URL param:

```
http://localhost:8889/wp-json/wp/v2/types?context=edit
```

You will see a different response. You can do the same by 

1. Create a `Contributor` User.
2. Switch to (login as) that User.
3. Create a New Post
4. Open your Console and type:

```js
fetch('http://localhost:8889/wp-json/wp/v2/types?context=edit')
```

5. Switch to the Network tab and inspect the resulting http request. You'll see an error status code.
6. Now do the same but change the `context` to `view`. You'll see all the Post Types returned.
7. Switch back to your `Admin` user and repeat from `#2` above. It works fine for this permission level.

This is caused by the [permissions check in the WP_REST_Post_Types_Controller REST API endpoint](https://github.com/WordPress/WordPress/blob/01c05f6ba4ca596db3a504948fbf29f6317f0b9a/wp-includes/rest-api/endpoints/class-wp-rest-post-types-controller.php#L82). Specifically 

```php
current_user_can( $post_type->cap->edit_posts )
```

It appears that Contributor Role is not allowed `edit_posts` access to the `Pages` post type. As a result the error is returned on this REST permission check. This is in turn because we are passing the `?context=edit` param in the `apiFetch` call.

Originally this PR tried to circumvent this by using the `view` context on the API request to retrieve the custom post type entities thereby avoiding the permissions check which _seems_ unnecessary. But this was not a good option.

------------

## How has this been tested?
Manually testing that the Nav Block now has access to Pages data.

## Types of changes
Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

File: packages/block-library/src/navigation/edit.js [hunk 1]
```diff
@@ -199,6 +199,7 @@ export default compose( [
 			parent: 0,
 			order: 'asc',
 			orderby: 'id',
+			context: 'view',
```
Comment (youknowriad) [inline packages/block-library/src/navigation/edit.js]: We can't just switch to using the "view" context because it means we're having inconsistent entities format in the state depending on the caller. I think right now, we just can't use `getEntityRecords`. Instead, we should use `apiFetch` in these components directly. One way to make this easier and avoid repeating the same lifecycle/state handling for all apiFetch usage is to consider a `useApiFetch` hook.

```
const { data, status, error } = apiFetch( { path: 'url' } )
```

Comment (getdave) [reply packages/block-library/src/navigation/edit.js]: @youknowriad So using `apiFetch` directly and not updating the "Redux" state at all, only local component state?

Also even if we do use a more direct method to make the API request, the data will still be wrong unless we switch the context to `view`. Is this what you are recommending?

Comment (youknowriad) [reply packages/block-library/src/navigation/edit.js]: yes, local state + view context.

And API fetch is just a simple wrapper around wp.fetch to make it work in WP context https://developer.wordpress.org/block-editor/packages/packages-api-fetch/

Comment (getdave) [reply packages/block-library/src/navigation/edit.js]: Looks like Latest Posts uses it https://github.com/WordPress/gutenberg/blob/d0e3c26ec295924d96a658640e2cc6fb118b2eca/packages/block-library/src/latest-posts/edit.js#L49

File: packages/block-library/src/navigation/edit.js [hunk 2]
```diff
@@ -76,6 +84,49 @@ function Navigation( {
...
+				}
+				// We've stopped fetching
+				isRequestingPages = false;
+			}
+		);
+
+		return () => {
+			isMounted = false;
+		};
+	}, [] );
```
Comment (youknowriad) [inline packages/block-library/src/navigation/edit.js]: I assume any component using apiFetch will hhave the same state, the same effects (status, data, error), should we extract this into a reusable `useApiFetch` hook like suggested?

Comment (getdave) [reply packages/block-library/src/navigation/edit.js]: Yes we could should but I wanted to check the basics were on track first before commiting additional effort.

Ill take this as thumbs up to proceed with the hook 😁

**Comment by getdave** [comment]
@youknowriad Looks like I'll need to be focused elsewhere for the next week so unlikely I'll get to this soon. Apologies.

**Comment by mtias** [comment]
@getdave what's the status of this one? I think we should hide this block for contributors (possibly also for authors).

File: packages/block-library/src/navigation/use-api-fetch.js [hunk 3]
```diff
@@ -0,0 +1,31 @@
+/**
```
Comment (tellthemachines) [inline packages/block-library/src/navigation/use-api-fetch.js]: I added the reusable apiFetch hook in the navigation folder as I'm not sure what the best place for it would be, or where it might be reused. Feedback appreciated!

Comment (talldan) [reply packages/block-library/src/navigation/use-api-fetch.js]: Hmm, I suppose if it went in the api-fetch package, react would have to be added as a dependency to that.

Comment (noisysocks) [reply packages/block-library/src/navigation/use-api-fetch.js]: What do you think, @youknowriad? Adding `@wordpress/element` as a dependency of `@wordpress/api-fetch` isn't totally out of the question since e.g. `@wordpress/data` depends on `@wordpress/element`.

File: packages/block-library/src/navigation/edit.js [hunk 4]
```diff
@@ -134,7 +155,7 @@ function Navigation( {
 		selectBlock( clientId );
 	}
 
-	const hasPages = hasResolvedPages && pages && pages.length;
+	const hasPages = pages && pages.length;
```
Comment (noisysocks) [inline packages/block-library/src/navigation/edit.js]: I think best to cast this to a boolean so that there's no surprises down the road when someone uses `hasPages` expecting a boolean but gets e.g. a number.

```suggestion
	const hasPages = !! pages && !! pages.length;
```

File: packages/block-library/src/navigation/use-api-fetch.js [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+				setData( dataList );
+				// We've stopped fetching
+				setIsRequesting( false );
+			} )
+			.catch( () => {
+				setData( [] );
+				// We've stopped fetching
+				setIsRequesting( false );
+			} );
+	}, [] );
```
Comment (noisysocks) [inline packages/block-library/src/navigation/use-api-fetch.js]: Right now this won't re-fetch if `path` changes. Is that right? It's probably a use case worth supporting for e.g. components where `path` is computed dynamically based on user input.

**Comment by noisysocks** [comment]
Pulling `master` so that this PR includes https://github.com/WordPress/gutenberg/pull/21118 should fix the PHP unit test failures that Travis CI is reporting.

**Comment by noisysocks** [comment]
This works well when I test it locally! 👍

At first I thought switching to `?context=view` would have implications in that we would no longer receive `title.raw` in the API response, but it looks like we're already using `title.rendered` and that HTML in the title isn't stripped out or rendered when setting `title.rendered `. (From memory, HTML isn't actually supported in page titles, it's just that most themes let you do it.)

Screen Shot 2020-03-30 at 16 43 59

I'd like https://github.com/WordPress/gutenberg/pull/18669#discussion_r397562216 and https://github.com/WordPress/gutenberg/pull/18669#discussion_r399931494 to be addressed and then this is a ✅ for me.

File: packages/block-library/src/navigation/use-api-fetch.js [hunk 6]
```diff
@@ -0,0 +1,31 @@
...
+import apiFetch from '@wordpress/api-fetch';
+
+/**
+ * Function that fetches data using apiFetch, and updates the status.
+ *
+ * @param {Function} setIsRequesting function to set requesting state to true or false.
+ * @param {Function} setData Function to set data being returned, or empty array on error.
+ * @param {string} path Query path.
+ */
+export default function useApiFetch( setIsRequesting, setData, path ) {
```
Comment (youknowriad) [inline packages/block-library/src/navigation/use-api-fetch.js]: Instead of setIsRequesting and setData why not an API like this:

```
const { isLoading, data, error } = useApiFetch( queryObject )
```

similar to https://github.com/marcin-piela/react-fetching-library
I've used this on a side project and it was very nice.

File: packages/block-library/src/navigation/use-api-fetch.js (hunk 3 above)
Comment (youknowriad) [reply packages/block-library/src/navigation/use-api-fetch.js]: Yeah, maybe it's fine. It does increase bundle size if loaded on the frontend without react need but I don't have a better alternative here.

**Comment by tellthemachines** [comment]
Hmm, I moved the hook to `@wordpress/api-fetch` but now it's not getting imported correctly in the navigation block, not sure why. I added it as a named export to the index file in api-fetch, `so import { useApiFetch } from '@wordpress/api-fetch'` _should_ work? It works fine if I change it to the direct path 😕

**Comment by noisysocks** [comment]
Might need to set it as a property of the default export.

```js
apiFetch.useApiFetch = useApiFetch;
...
export default apiFetch;
```

File: packages/api-fetch/src/index.js [hunk 7]
```diff
@@ -166,3 +167,35 @@ apiFetch.fetchAllMiddleware = fetchAllMiddleware;
...
+ * @param {string} path Query path.
+ */
+export function useApiFetch( path ) {
+	// Indicate the fetching status
+	const [ isLoading, setIsLoading ] = useState( true );
+	const [ data, setData ] = useState( [] );
+	const [ error, setError ] = useState( null );
+
+	useEffect( () => {
+		apiFetch( { path } )
```
Comment (talldan) [inline packages/api-fetch/src/index.js]: I might be wrong, but I'm wondering if the state should be reset prior to calling `apiFetch` by calling `setIsLoading`, `setData` and `setError` again with the initial values, as I think if the `path` changes, useState won't override any existing values being stored.

File: packages/api-fetch/src/index.js [hunk 8]
```diff
@@ -166,3 +167,35 @@ apiFetch.fetchAllMiddleware = fetchAllMiddleware;
...
+
+/**
+ * Function that fetches data using apiFetch, and updates the status.
+ *
+ * @param {string} path Query path.
+ */
+export function useApiFetch( path ) {
+	// Indicate the fetching status
+	const [ isLoading, setIsLoading ] = useState( true );
+	const [ data, setData ] = useState( [] );
```
Comment (talldan) [inline packages/api-fetch/src/index.js]: I noticed the data is referred to as dataList later on as well. The data returned from an API might also be an object, like when fetching an individual post. I think this could just be kept as an undefined initial value `useState()`.

File: packages/api-fetch/src/index.js (hunk 7 above)
Comment (tellthemachines) [reply packages/api-fetch/src/index.js:172]: Oooh good point, it probably won't because only the effect will re-run.

File: packages/block-library/src/navigation/edit.js [hunk 9]
```diff
@@ -57,10 +55,10 @@ function Navigation( {
 	//
 	// HOOKS
 	//
-	/* eslint-disable @wordpress/no-unused-vars-before-return */
 	const ref = useRef();
 	const { selectBlock } = useDispatch( 'core/block-editor' );
 
+	/* eslint-disable @wordpress/no-unused-vars-before-return */
```
Comment (noisysocks) [inline packages/block-library/src/navigation/edit.js:61]: Do we find ourselves having to disable this often in components? If it's not a useful rule then we should just remove it...

(Not relevant to this PR!)

**Review by noisysocks — APPROVED** [review]
Looks good! 👍

File: packages/block-library/src/navigation/use-api-fetch.js (hunk 6 above)
Comment (getdave) [reply packages/block-library/src/navigation/use-api-fetch.js]: I have a question. What if I need to make my fetch call cancelable? As far as I know the only way to do that is via something like this

https://github.com/WordPress/gutenberg/blob/ddd3fffdd327d2f9c5202481345fb7427d4a822b/packages/block-editor/src/components/link-control/index.js#L62

How could I mirror that behaviour with this hook?

File: packages/api-fetch/src/index.js [hunk 10]
```diff
@@ -156,6 +157,42 @@ function apiFetch( options ) {
 	} );
 }
 
+/**
+ * Function that fetches data using apiFetch, and updates the status.
+ *
+ * @param {string} path Query path.
+ */
+function useApiFetch( path ) {
```
Comment (aduth) [inline packages/api-fetch/src/index.js:165]: By naming standards, this should be `useAPIFetch`.

See: https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/#abbreviations-and-acronyms

File: packages/block-library/src/navigation/edit.js (hunk 9 above)
Comment (aduth) [reply packages/block-library/src/navigation/edit.js:61]: The value of the rule is explained here:

https://github.com/WordPress/gutenberg/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars-before-return.md

Based on specific instances, we can choose to improve it as well. For example, it should probably be exempting hooks as a special circumstances, due to constraints imposed on us externally via [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html).

**Comment by aduth** [comment]
My initial reaction here is that we should be encouraging to use [core data entities](https://github.com/WordPress/gutenberg/tree/master/packages/core-data) and the [data mechanisms](https://github.com/WordPress/gutenberg/tree/master/packages/data) consistently, and not to make arbitrary API requests from components. If there's insufficiencies in these patterns, we should aim to resolve those.

I see there was a conversation early on at https://github.com/WordPress/gutenberg/pull/18669#discussion_r349126531 about how this is a particularly troublesome example of where we're unable to get data due to constraints of the REST API and its `context` parameter. Even if it's something we're okay to relent on, I think it would be important to be very conscious that it's an _exception to the rule_. We may want to use a hook like `useAPIFetch`, but it doesn't seem to me we should want to be making this publicly available. Making it part of the public API would tacitly condone this as a valid/encouraged means of making data available within a component, and I don't know that we're prepared to make that decision, especially considering that:

- This was prepared for a case that we consciously considered as an exception, and only after relenting on a point where we grant that we'd _prefer_ to use data and not a direct API request.
- There's no clear guidelines on which is appropriate to use and when, so we now have multiple and inconsistent methods to retrieve data.

File: packages/api-fetch/src/index.js [hunk 11]
```diff
@@ -156,6 +157,42 @@ function apiFetch( options ) {
...
+			.then( ( fetchedData ) => {
+				setData( fetchedData );
+				// We've stopped fetching
+				setIsLoading( false );
+			} )
+			.catch( ( err ) => {
+				setError( err );
+				// We've stopped fetching
+				setIsLoading( false );
+			} );
```
Comment (aduth) [inline packages/api-fetch/src/index.js:186]: There's no guarantee that the component is still mounted at the point we're calling `setState` here. If it was removed in the time between the request starting and its completion, the state setters will fail, and React will log a warning to the console.

See also: https://reactjs.org/docs/hooks-reference.html#cleaning-up-an-effect

**Comment by noisysocks** [comment]
@aduth: What do you suggest we do as a next step?

File: packages/api-fetch/src/index.js (hunk 11 above)
Comment (getdave) [reply packages/api-fetch/src/index.js:186]: Can I also reinforce that this anti pattern is super easy to introduce. I wonder whether we could make the hook handle this edge cases automatically by:

1. Wrapping the fetch Promise to allow to be cancelled.
2. Automatically calling the `.cancel()` on unmount.
3. Checking for `isCancelled` state in `.then` / `.catch` handlers and exiting early ( to avoid state updates).

For an example see https://github.com/Automattic/jetpack/pull/15228

Comment (nerrad) [reply packages/api-fetch/src/index.js:186]: This point makes me think of the behaviour of resolvers in `wp.data` which often include making fetch requests. This same issue can surface there (and I think [already is](https://github.com/WordPress/gutenberg/issues/21049)). We probably should be looking into that too.

**Comment by aduth** [comment]
@noisysocks In my view, I think the most immediate next step could be to simply move `useAPIFetch` to be inlined within `navigation/edit.js`, in order to remove it from the public API. This is the most pressing for me.

There are other points mentioned about async state updates where we should consider making improvements. I believe the specific implementation may be blocking @getdave in some way, though to me it's not entirely clear if his original implementation had migrated from core entities to apiFetch if there was some plans for how to reconcile this.

File: packages/block-library/src/navigation/edit.js (hunk 9 above)
Comment (aduth) [reply packages/block-library/src/navigation/edit.js:61]: > The value of the rule is explained here:

I should have also mentioned there was previously quite a few _offending_ cases that were cleaned up as part of the introduction of the rule, in case that's a more convincing method for interpreting the value.

See: #12827

Comment (aduth) [reply packages/block-library/src/navigation/edit.js:61]: It might not have been necessary to disable the rule here anyways? It was removed in #20884. If I recall correctly, the rule makes exceptions for object destructuring.

To the general problem: 

> we can choose to improve it as well. For example, it should probably be exempting hooks as a special circumstances, due to constraints imposed on us externally via [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html).

This already exists as of #16737:

https://github.com/WordPress/gutenberg/blob/1f00c74c193253c2706f2729f5470573345ed823/packages/eslint-plugin/configs/react.js#L10-L15

The problem here is that the hook is named as experimental, `__experimentalUseColors`. There are two ways we could accommodate for this:

1. We can adopt a convention to reference the slot by its non-experimental name in the implementation of the component, renaming via the import ([example](https://github.com/WordPress/gutenberg/blob/1f00c74c193253c2706f2729f5470573345ed823/packages/block-editor/src/components/block-inspector/index.js#L12))
2. We can expand the pattern above to include `__experimental` and `__unstable` naming conventions

File: packages/api-fetch/src/index.js (hunk 11 above)
Comment (noisysocks) [reply packages/api-fetch/src/index.js:186]: Maybe we could promote good behaviour here by having `apiFetch` return a function that cancels the request.

```js
useEffect( () => {
	setIsLoading( true );
	setData( null );
	setError( null );

	const cancelFetch = apiFetch( { path } )
		.then( ( fetchedData ) => {
			setData( fetchedData );
			// We've stopped fetching
			setIsLoading( false );
		} )
		.catch( ( err ) => {
			setError( err );
			// We've stopped fetching
			setIsLoading( false );
		} );

	return cancelFetch;
}, [ path ] );
```

Comment (aduth) [reply packages/api-fetch/src/index.js:186]: I'm motivated toward anything which keeps `apiFetch` cumbersome to use in a component, if it means that the preferred core data entities are the more obvious solution by virtue of their ergonomics advantage. Which isn't to say there's not issues there as well (https://github.com/WordPress/gutenberg/pull/18669#discussion_r402223905), but I think we're in a better position to solve those internal to those implementations, even if it's [something like this](https://github.com/WordPress/gutenberg/blob/63a2e776f73c6cc626bc827802341c1178ee2814/packages/block-editor/src/components/link-control/index.js#L55-L80).

**Comment by getdave** [comment]
@noisysocks @aduth @draganescu I'm thinking that we sholuld:

1. Revert this PR via [commit](https://github.com/WordPress/gutenberg/commit/f2b677851aed870fa8216861561b3ce0197c03c4).
2. Raise followup PR to incorporate [the `context` fix in this PR](https://github.com/WordPress/gutenberg/commit/f2b677851aed870fa8216861561b3ce0197c03c4#diff-cfe334a821ad12721a129f61005669c3R95), but using the Core entities methods.

This will:

1. Remove `useApiFetch` - this will be a deprecation of a public API so what's the procedure here?
2. Avoid relying on apiFetch which causes errors on unmount if not given special treatment.
3. Ensure we continue utilising Core data and entities as the preferred data fetch method.

Any objections?
