### PR TITLE
Deprecate PanelColor components

### LINKED ISSUE #10367: Maybe deprecate @wordpress/editor PanelColor?
I'm working on some definitive documentation of color palettes in Gutenberg (revising/extending #7906), and in the process noticed that we have two versions of colour inspector panels inside the `@wordpress/editor` package right now:

## `PanelColor`

+ [Code here](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/panel-color/index.js)
+ Has a small CSS float bug w/ the clear button

Screenshot:

edit_page_ _tomodomo_ _wordpress

## `PanelColorSettings`

+ [Code here](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/panel-color-settings/index.js)
+ Nicely supports multiple colors
+ No CSS float bug

Screenshot:

edit_page_ _tomodomo_ _wordpress

## Consolidate/deprecate?

Overall `PanelColorSettings` seems superior because of its support for multiple color values and for not having the clear button float issue. Since the two are so similar, does it make sense to deprecate and remove the less-powerful/visually-broken `PanelColor` and standardize on `PanelColorSettings`?

`PanelColor` also wrapped a component of the same name inside `@wordpress/components` which could also be deprecated/removed.

If desired, `PanelColorSettings` could also be updated to hide the smaller color name label if only one color "type" is set, which would more closely reflect the current look of `PanelColor`.

Curious to hear thoughts on this!

cc'ing @jorgefilipecosta since I know he's done a lot of work on color stuff!

### PR DESCRIPTION
**Pull request by chrisvanpatten**
Fixes #10367.

This PR deprecates `wp.components.PanelColor` and `wp.editor.PanelColor` in favour of `wp.editor.PanelColorSettings`, which is a more robust component for the reasons documented in #10367:

> Overall `PanelColorSettings` seems superior because of its support for multiple color values and for not having the clear button float issue.

It also updates the `@wordpress/editor` and `@wordpress/components` changelogs to mention the deprecation.

One note is that deprecating `wp.components.PanelColor` will mean there's no component to provide a color panel that isn't wrapped inside `withColorContext`. Users who wish to have a panel with a color palette that uses a separate set of colors than what's defined with `add_theme_support('editor-color-palette');` will need to build their own panel component.

As such, it may be desired to deprecate `wp.editor.PanelColor`, while _keeping_ `wp.components.PanelColor` and simply fixing the visual bug noted in #10367. However, this would be a use-case that Gutenberg itself does not need/use, so it might not be worth continuing to support.

I've never done a deprecation like this… I think I got everything but would very much appreciate a close look/review 😄

### CODE REVIEW

File: packages/editor/src/components/panel-color/index.js [hunk 1]
```diff
@@ -17,6 +18,12 @@ import withColorContext from '../color-palette/with-color-context';
 import { getColorObjectByColorValue } from '../colors';
 
 function PanelColor( { colors, title, colorValue, initialOpen, ...props } ) {
+	deprecated( 'wp.editor.PanelColor', {
```
Comment (jorgefilipecosta) [inline packages/editor/src/components/panel-color/index.js]: Here we should have wp.components.PanelColor.

File: packages/editor/src/components/panel-color/index.js [hunk 2]
```diff
@@ -17,6 +18,12 @@ import withColorContext from '../color-palette/with-color-context';
...
+		version: '4.2',
+		alternative: 'wp.editor.PanelColorSettings',
```
Comment (jorgefilipecosta) [inline packages/editor/src/components/panel-color/index.js]: Unfortunately wp.editor.PanelColorSettings is not a viable alternative to wp.components.PanelColor. wp.components.PanelColor allows a block to specify the colors that appear instead of using the default or theme specified ones which is useful for some blocks that only make sense with some colors or blocks that should expand the color options, e.g., a drawing block.

File: packages/components/CHANGELOG.md [hunk 3]
```diff
@@ -4,6 +4,10 @@
 
 - Added a new `ResizableBox` component.
 
+### Deprecation
+
+- `wp.components.PanelColor` has been deprecated in favor of `wp.editor.PanelColorSettings`.
```
Comment (jorgefilipecosta) [inline packages/components/CHANGELOG.md]: We should also add the deprecation information to /docs/reference/deprecated.md.

**Review by jorgefilipecosta — COMMENTED** [review]
Hi @chrisvanpatten thank you for creating a PR with this deprecations. I agree that this component should be deprecated so we are not shipping unused code on 5.0 and we don't have multiple UI's for color picking.
Unfortanelety our new component does not completely replace what the old components offered. I will look into adding the missing functionality to the new component so we can merge this PR 👍
Thank you for your contribution.

File: packages/editor/src/components/panel-color/index.js (hunk 2 above)
Comment (chrisvanpatten) [reply packages/editor/src/components/panel-color/index.js]: Right, I noted that we could have an alternate option in the PR:

> One note is that deprecating `wp.components.PanelColor` will mean there's no component to provide a color panel that isn't wrapped inside `withColorContext`. As such, it may be desired to deprecate `wp.editor.PanelColor`, while _keeping_ `wp.components.PanelColor` and simply fixing the visual bug noted in #10367.

Happy to tackle that in this PR too, if you'd like @jorgefilipecosta :)

Comment (chrisvanpatten) [reply packages/editor/src/components/panel-color/index.js]: Also just to clarify, it makes sense to me to keep the version in `components` and get rid of the one in `editor` but is there any reason to do the reverse instead?

File: packages/components/CHANGELOG.md (hunk 3 above)
Comment (chrisvanpatten) [reply packages/components/CHANGELOG.md]: Done!

File: packages/editor/src/components/panel-color/index.js (hunk 2 above)
Comment (chrisvanpatten) [reply packages/editor/src/components/panel-color/index.js]: This will be fixed by #10457!

File: packages/editor/src/components/panel-color/index.js (hunk 1 above)
Comment (chrisvanpatten) [reply packages/editor/src/components/panel-color/index.js]: Fixed!

**Comment by talldan** [comment]
Thanks for picking this up @chrisvanpatten! 

I think to resolve the test failure it'll be something along the lines of adding `expect( console ).toHaveWarnedWith( // ... )`, as has been done here:
https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/text-columns/test/index.js#L12

**Comment by chrisvanpatten** [comment]
This _should_ pass the failing test now, but I think is likely to miss the 4.0 milestone, so the deprecation version may need to be updated.

**Comment by chrisvanpatten** [comment]
Updated the version numbers with the assumption it can land in 4.1.

**Review by talldan — APPROVED** [review]
I think now that #10457 has been merged, this is good to go. Thanks again for picking this up @chrisvanpatten!

**Comment by chrisvanpatten** [comment]
Thanks @talldan! 🚢

File: packages/components/CHANGELOG.md [hunk 4]
```diff
@@ -1,3 +1,9 @@
+## 4.2.0 (Unreleased)
+
+### Deprecation
+
+- `wp.components.PanelColor` has been deprecated in favor of `wp.editor.PanelColorSettings`.
```
Comment (aduth) [inline packages/components/CHANGELOG.md]: In the context of `packages`, we should avoid references to WordPress-specific globals when possible (at least for changelog). Console messaging is trickier since we can't yet customize for the WordPress context, but it's a hope there we could.

See: #9753
