### PR TITLE
Omit serializing block attributes that match any default attribute values

### LINKED ISSUE #1768: Dropcap tag doesn't get cleaned up
## Issue Overview
This is a minor thing, but something that triggered my clean markup spidey sense.

## Steps to Reproduce
1. Create a text block with some text
2. Look in the code view and see: `<!-- wp:core/text -->`
3. Turn the Dropcap toggle on
4. Look in the code view and see: `<!-- wp:core/text {"dropCap":true} -->`
5. Turn the Dropcap toggle off
6. Look in the code and see that it says `<!-- wp:core/text {"dropCap":false} -->`

version 0.3.0

## Expected Behavior
That the tag gets cleaned up after you turn dropcaps off. By default, when the tag is absent, it should assume that dropcaps are not wanted.

## Current Behavior
The tag remains in the block definition.

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #1768.

Before the patch, the Text block that gets `dropCap` toggled from `true` to `false` gets serialized as:

image

With the changes, it gets serialized as (note the absence of the default value among the serialized attributes), and the fixed `class` in the Text block:

image

When dropCap is toggled back on, it gets serialized to:

image

### CODE REVIEW

**Comment by westonruter** [comment]
Rebased. d14e0b5 rewritten to 1b10e54.

**Comment by westonruter** [comment]
Working on resolving the conflicts…

**Comment by aduth** [comment]
I'd been waiting to review this pending #1905, but I think it might be good to get this in and I can rebase #1905 separately. Let me know when conflicts are resolved and I'll take a look.

**Comment by westonruter** [comment]
@aduth before I work on fixing the conflict, does this change get a 👍?

File: blocks/api/serializer.js [hunk 1]
```diff
@@ -115,7 +115,12 @@ export function serializeBlock( block ) {
 	const blockName = block.name;
 	const blockType = getBlockType( blockName );
 	const saveContent = getSaveContent( blockType, block.attributes );
-	const saveAttributes = getCommentAttributes( block.attributes, parseBlockAttributes( saveContent, blockType.attributes ) );
+	let saveAttributes = getCommentAttributes( block.attributes, parseBlockAttributes( saveContent, blockType.attributes ) );
+
+	// Remove attributes that are the same as the defaults.
+	if ( blockType.defaultAttributes ) {
+		saveAttributes = pickBy( saveAttributes, ( value, key ) => ! isEqual( value, blockType.defaultAttributes[ key ] ) );
```
Comment (aduth) [inline blocks/api/serializer.js]: I don't think we need (or want) this to be a deep equality `isEqual`, but rather just strict equality `!==`

**Review by aduth — COMMENTED** [review]
Seems like a good idea.

File: blocks/api/serializer.js (hunk 1 above)
Comment (westonruter) [inline blocks/api/serializer.js]: What about when an attribute contain an object? Then this will fail `!==` matching.

Comment (westonruter) [inline blocks/api/serializer.js]: In other words, `value !== blockType.defaultAttributes[ key ]` will always be `true` for objects.

**Review by timmyc — COMMENTED** [review]
I gave this branch a spin too and it seems like a great change.  One minor comment.

**Comment by westonruter** [comment]
Rebased. 1b10e54 rewritten as 03e92f1.

File: blocks/library/text/index.js [hunk 2]
```diff
@@ -108,7 +112,7 @@ registerBlockType( 'core/text', {
 
 	save( { attributes } ) {
 		const { align, content, dropCap } = attributes;
-		const className = dropCap && 'has-drop-cap';
+		const className = dropCap ? 'has-drop-cap' : null;
```
Comment (westonruter) [inline blocks/library/text/index.js]: No reason, other than it was using a `className` var to begin with.

File: blocks/api/serializer.js (hunk 1 above)
Comment (westonruter) [inline blocks/api/serializer.js]: @aduth 👍?

Comment (aduth) [inline blocks/api/serializer.js]: >In other words, `value !== blockType.defaultAttributes[ key ]` will always be `true` for objects.

Well, not necessarily; not if the attribute value is never updated. But it's a fair point that if they _are_ updated, and their nested structure matches the default value, it should probably be omitted all the same. I'm fine with `isEqual`.

File: blocks/api/test/serializer.js [hunk 3]
```diff
@@ -195,13 +199,14 @@ describe( 'block serializer', () => {
 				{
 					name: 'core/test-block',
 					attributes: {
+						foo: false,
```
Comment (aduth) [inline blocks/api/test/serializer.js]: One of two things should be done here:

- We should set a `bar: false` value in the attributes here. As is we're not really testing that the default value is omitted, because the attribute isn't set anyways.
- We should use `createBlock` to construct the block object and rely on its behavior to set the defaults into attributes.

My preference is toward the latter.

**Review by aduth — DISMISSED** [review]

File: blocks/api/test/serializer.js (hunk 3 above)
Comment (westonruter) [inline blocks/api/test/serializer.js]: @aduth thanks for the feedback. Done in 71a07fc9bac6348a28545ad9cfe23e91c6c50a26.

**Review by aduth — COMMENTED** [review]
By failing test, it appears we need to update markup for cover image fixture.

Otherwise LGTM 👍

**Comment by westonruter** [comment]
Thanks, I amended that `cover-image` block fix onto d272cbd1a116a07cb952ba36ba7bae1d3173e1ed.
