### PR TITLE
Fix `DisableNonPageContentBlocks`

### LINKED ISSUE #59359: Template Preview: blocks used in page Content lack contextual menu if they're locked at the top (Title, Featured Image)
### Description

When testing Template Preview I spotted that blocks that are locked at a top level (Title, Featured Image) lack contextual menus when used in Content

### Step-by-step reproduction instructions

1. Add new Page
2. Add some blocks to the page, for example:
  - Separator
  - Featured Image
3. Enable "Template Preview" mode
4. Open List View
5. Focus on Separator - it has contextual menu and block Toolbar
6. Focus on Featured Image - it has no contextual menu and there's no block Toolbar so you can't move the block etc.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/20098064/8e0eddf1-7c9a-47f8-ab68-634e55f41fe7

### Environment info

- WordPress - 6.5-beta2-57707
- Gutenberg - 17.7.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by noisysocks**
## What?
Fixes a bug noticed by @andrewserong in https://github.com/WordPress/gutenberg/pull/59295#pullrequestreview-1897181974.

When editing a page we lock all blocks except for Title, Featured Image, and Content which are put into "content only" mode meaning that you can't interact with its non-content controls, e.g. you can't set a background or an alignment. This doesn't apply to blocks within the Content block which are fully editable. 

Currently, Title or Featured Image blocks that are _nested within_ a Content block are erroneously in "content only" mode. This is because of a flaw in the `DisableNonPageContentBlocks` component.

`DisableNonPageContentBlocks` will:

- Disable all block editing at the root level by calling `setBlockEditingMode( '', 'disabled' )`.
- _Re-enable_ editing of content blocks by calling `setBlockEditingMode( clientId, 'contentOnly' )`.

The bug is in how `DisableNonPageContentBlocks` selects which content blocks to re-enable. It's naive and selects all blocks matching a given name. This includes blocks nested within Content, which isn't right.

## How?
This PR fixes the issue by rewriting `DisableNonPageContentBlocks` to use a more explicit `useSelect` function to select content blocks. I think the extra explicitness will avoid confusion and future bugs of this nature. I also added unit tests.

## Testing Instructions
1. Go to Appearance → Editor → Pages and edit a page.
2. Select the Title, Featured Image, and Content blocks. Only minimal controls to do with editing the content should appear in the block toolbar and block inspector.
3. Insert a Title or Featured Image block into the Content block.
4. Select the block you just inserted. You should see all of the controls.

### CODE REVIEW

File: packages/editor/src/store/private-selectors.js [hunk 1]
```diff
@@ -49,3 +49,26 @@ export const getInsertionPoint = createRegistrySelector(
...
+					contentIds.push( clientId );
+				} else if ( blockName !== 'core/query' ) {
+					contentIds.push(
+						...getPageContentBlocks( state, clientId )
+					);
+				}
+			}
+			return contentIds;
+		}
+);
```
Comment (Mamaduka) [inline packages/editor/src/store/private-selectors.js]: This looks like a `block-editor` store selector, which should be memoized; otherwise, `clientIds` will be a new array on each call. 

Sidenote: Recursively calling memoized selectors could impact performance - #58356.

**Review by fabiankaegy — COMMENTED** [review]
I can confirm that this does indeed fix the issue described :) Good find! 


https://github.com/WordPress/gutenberg/assets/20684594/957f68db-557d-430c-b7eb-b6646f33fd77

File: packages/editor/src/store/private-selectors.js (hunk 1 above)
Comment (noisysocks) [reply packages/editor/src/store/private-selectors.js]: I don't like putting this in `@wordpress/block-editor` because I feel `block-editor` shouldn't know about "post title", "post featured image", "post content", the concept of page content, etc.

Unfortunately we can't combine `createSelector` and `createRegistrySelector`.

I'll go back to a solution that doesn't involve a new selector 👍 0af14addd13093038b7ca9e9f18a56eb3ae0a63f

File: packages/editor/src/components/provider/disable-non-page-content-blocks.js [hunk 2]
```diff
@@ -2,54 +2,52 @@
...
- */
-import { PAGE_CONTENT_BLOCK_TYPES } from './constants';
+const PAGE_CONTENT_BLOCKS = [
+	'core/post-title',
+	'core/post-featured-image',
+	'core/post-content',
+];
+
+function useDisableNonPageContentBlocks() {
+	const contentIds = useSelect( ( select ) => {
```
Comment (andrewserong) [inline packages/editor/src/components/provider/disable-non-page-content-blocks.js:15]: Just a question for my own understanding: it looks like this is safely not creating a new reference too frequently (i.e. it's used in the `useEffect`'s dependencies and doesn't cause any issues). I'm used to the idea of trying to avoid `.filter()` calls within a `useSelect` because we then wind up with a new reference. In this case, is the reason that it's safe that `contentIds` is the value returned by the callback here, rather than destructuring a value within an object?

**Review by andrewserong — APPROVED** [review]
This is testing nicely for me, and the approach of checking the block parents for a match looks good to me 👍

One of the e2e tests was failing, but I've kicked it off again. It didn't look related to me, so let's see if it passes with another attempt.

Thanks for the follow-up! 🎉

File: packages/editor/src/components/provider/disable-non-page-content-blocks.js (hunk 2 above)
Comment (Mamaduka) [reply packages/editor/src/components/provider/disable-non-page-content-blocks.js:15]: Correct, this is a "hack"; `mapSelect` returns an array of `clientId` strings, which can correctly pass shallow equality check.

> I'm used to the idea of trying to avoid .filter() calls within a useSelect because we then wind up with a new reference.

File: packages/editor/src/store/private-selectors.js (hunk 1 above)
Comment (Mamaduka) [reply packages/editor/src/store/private-selectors.js]: Good point.

> Unfortunately we can't combine createSelector and createRegistrySelector.

I can't find PR right now, but I thought @ellatrix or @jsnajdr resolved that issue.

File: packages/editor/src/components/provider/disable-non-page-content-blocks.js (hunk 2 above)
Comment (andrewserong) [reply packages/editor/src/components/provider/disable-non-page-content-blocks.js:15]: Ah, gotcha. Thanks for confirming!

**Comment by andrewserong** [comment]
Hrm, it looks like [`allows navigation through each item using arrow keys`](https://github.com/WordPress/gutenberg/blob/d3f2c77d64a3ae2138e3788c38fecbe47f2f4d0d/test/e2e/specs/editor/various/dropdown-menu.spec.js#L24) is still failing. I can't immediately see why it'd be affected by this PR. Is it worth giving this a rebase to see if that fixes it up?

**Comment by ramonjd** [comment]
> I can't immediately see why it'd be affected by this PR. Is it worth giving this a rebase to see if that fixes it up?

It's failing on all my recent PRs too 😄 So maybe not related?

**Comment by Mamaduka** [comment]
Here's the fix for e2e test failure - #59356.

**Comment by andrewserong** [comment]
> Here's the fix for e2e test failure - https://github.com/WordPress/gutenberg/pull/59356.

Ah, perfect. Thanks for fixing it @Mamaduka! 🙇

File: packages/editor/src/store/private-selectors.js (hunk 1 above)
Comment (jsnajdr) [reply packages/editor/src/store/private-selectors.js]: Yes, they can be combined now, since #57888:
```js
createRegistrySelector( ( select ) => createSelector( ( state, rootClientId = '' ) => {
  ...
} );
```

Comment (jsnajdr) [reply packages/editor/src/store/private-selectors.js]: The `useSelect` solution still lacks memoization, returning a new `.filter` result on each call, even if the underlying block editor state didn't change at all. It will probably trigger the "returns different values when called with the same state and parameters" warning.

Comment (Mamaduka) [reply packages/editor/src/store/private-selectors.js]: The `useSelect` solution should be okay in this case. A `mapSelect` returns an array of `clientId` strings, which will pass shallow equality. There are few places in the core where we use similar "hacks"

File: packages/editor/src/components/provider/disable-non-page-content-blocks.js (hunk 2 above)
Comment (noisysocks) [reply packages/editor/src/components/provider/disable-non-page-content-blocks.js:15]: Huh, I didn't know it was a "hack" 😀 I just prefer not returning multiple things from `useSelect` where possible as I think it's easier to read.

There's a warning if you do it wrong so I just let the computer do the thinking about this stuff.

https://github.com/WordPress/gutenberg/blob/8f61b9ba5e1e898626a6b94f52411222e3c2f463/packages/data/src/components/use-select/index.js#L163-L165

**Comment by getdave** [comment]
Nice work folks 👏

File: packages/editor/src/components/provider/disable-non-page-content-blocks.js (hunk 2 above)
Comment (Mamaduka) [reply packages/editor/src/components/provider/disable-non-page-content-blocks.js:15]: I mean “hack” because it’s not obvious why it’s okay to use `filter` in current situation if you’re not familiar with `useSelect` internals.

**Comment by getdave** [comment]
I just cherry-picked this PR to the cherry-pick-wp-6-5-beta-3 branch to get it included in the next release: b9020fa812

**Comment by ramonjd** [comment]
Thank you, folks!
