### PR TITLE
Store: Reset change detection on post update

### LINKED ISSUE #6112: Dirty state is still cleared if post is edited while prolonged save request is made
## Issue Overview

If you make a change to a post, then press update and the update request is slow to respond (either due to connectivity or server issues), and make another change while `isPostSaving` then when the response finishes the dirty state is erroneously cleared and I am unable to save the new changes I made the save request was pending.

## Steps to Reproduce

Tested using `master` at ab7a429db76c3484da91012714648f592b09fae0.

1. To aid with testing, add `sleep(5)` to the top of `\WP_REST_Posts_Controller::update_item()`.
2. Open a post draft.
3. Make a change to a post.
4. Hit Save Draft
5. While the save request is happening make another change to the post.
6. Once the save request finishes, try to save the change you just made.

## Expected Behavior
The Save Draft button should be re-shown to the user after the save request completes when a change was made during the request. Additionally, there should be the “Are you sure?” dialog when leaving the page at this point so that the user does not lose their changes.

## Possible Solution
Introduce a new state flag for `isEditedWhileSaving` and if when the response completes, check this before resetting `isDirty` to `false`.

## Screenshots / Video

Screencast of issue: https://youtu.be/HLF7VTd8gjY

### PR DESCRIPTION
**Pull request by aduth**
Fixes #6112 

This pull request seeks to resolve an issue where changes made while a post is saving are not accurately reflected in change detection, resulting in the potential for data loss if the user attempts to navigate away after a save completes.

In doing so, it also introduces...

- E2E tests for various "dirty post" prompt conditions.
- A fix for the `withChangeDetection` higher-order reducer where ignored action types may have resulted in the `isDirty` value being lost.

__Testing instructions:__

Verify that end-to-end tests pass:

```
npm run test-e2e
```

Repeat steps to reproduce from #6112, verifying that the editor prompts about unsaved changes if they were introduced in the time between save start and save success.

### CODE REVIEW

File: editor/store/selectors.js [hunk 1]
```diff
@@ -88,7 +88,7 @@ export function isEditedPostNew( state ) {
  * @return {boolean} Whether unsaved values exist.
  */
 export function isEditedPostDirty( state ) {
-	return state.editor.isDirty;
+	return state.editor.isDirty || isSavingPost( state );
```
Comment (youknowriad) [inline editor/store/selectors.js]: Can you clarify why it should return true on mid-save?

**Comment by aduth** [comment]
>I thought meta would trigger "Ctrl" on windows?

Meta exists and has its own meaning in Windows (Windows key), though not always consistently applied by browsers apparently in treating `event.metaKey`.

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey

File: editor/store/selectors.js (hunk 1 above)
Comment (aduth) [reply editor/store/selectors.js]: >Can you clarify why it should return true on mid-save?

The fix here is moving the change detection reset from `RESET_POST` to `UPDATE_POST`, so immediately upon hitting save, before the request has finished. This means that we can track changes that occur while the save is in-flight. Conversely, we need to make sure that if the user attempts to navigate away while the save is still pending, they're notified.

Another (better?) way to express this might be to consider whether there are any transactions in `redux-optimist` where `isDirty: true`; i.e. is there a possibility that if the transaction (save attempt) was to be reverted (save fail), would the user be put back into a state of dirtiness?

I'd also considered if we could track changes more like what we had, with it being a condition of the current state: This is simple enough to check if there are any entries in `state.editor.entries`, but `state.editor.blocksByUid` and `state.editor.blockOrder` is harder to track for changes (without comparing to an initial value).

**Comment by aduth** [comment]
Rebased.

e7f6b1c adds a new utility for end-to-end tests, `pressWithModifier`, which accepts "Mod" as an argument to translate to the platform-specific key. Existing usage has been updated, along with that in the newly-introduced tests.

978f8d5 avoids `isSavingPost` in the `isEditedPostDirty` selector, instead deferring to a new `inSomeHistory` selector which accepts state and a predicate function. Essentially this is the alternative behavior described in https://github.com/WordPress/gutenberg/pull/6209#discussion_r182420676, where dirtiness is a condition of whether the editor is currently dirty, or a pending-but-not-committed transaction could put the editor back into a dirty state.

File: editor/store/selectors.js [hunk 2]
```diff
@@ -89,7 +89,7 @@ export function isEditedPostNew( state ) {
  * @return {boolean} Whether unsaved values exist.
  */
 export function isEditedPostDirty( state ) {
-	return state.editor.isDirty;
+	return state.editor.isDirty || inSomeHistory( state, isEditedPostDirty );
```
Comment (youknowriad) [inline editor/store/selectors.js]: This is causing a regression for the post publish panel, it's getting closed right after publish
