### PR TITLE
Editor: Extend PostTrashCheck with canUser() check for delete action

### LINKED ISSUE #23144: Don't show "Move to Trash" link if current user cannot delete posts
**Describe the bug**
Noticed this while working on #23119. The [current component](https://github.com/WordPress/gutenberg/tree/4857ad58c1241b3d63d21a6880c989b85746c3dc/packages/editor/src/components/post-trash) has no checks for current user's capabilities. But there are three that need to be checked: `delete_posts`, `delete_others_posts`, and `delete_published_posts`.

**To reproduce**
* Create a user with only `read` and `edit_posts` capabilities
* Create a new post and click the trash link.
* You'll get the "Sorry, you are not allowed to delete this post." error notice.

**Expected behavior**
If the user has no access to delete posts the link should not be displayed.

**Screenshots**
image

**Additional context**
This probably needs a patch for core to extend the checks in [`WP_REST_Posts_Controller::get_available_actions()`](https://github.com/WordPress/wordpress-develop/blob/9c0fd945582622506312aafbd8079a5b933218a5/src/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L1984-L1986) too.

### PR DESCRIPTION
**Pull request by ocean90**
## Description
Fixes #23144.

This is a version which doesn't require a new `action-delete` action on the resource.

## How has this been tested?
* Create a user with only `read` and `edit_posts` capabilities
* Create a new post and notice that there's no longer a trash link.

For testing you can use WP-CLI to create a user "author" with the role "author_only_edit" which can only create/edit draft posts.

```
npx wp-env run cli wp role create author_only_edit AuthorOnlyEdit
npx wp-env run cli wp cap add author_only_edit read edit_posts
npx wp-env run cli wp user create author author@example.com
npx wp-env run cli wp user set-role author@example.com author_only_edit
```

## Types of changes
Bug fix

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/editor/src/components/post-trash/check.js [hunk 1]
```diff
@@ -3,18 +3,27 @@
...
 
 export default withSelect( ( select ) => {
-	const { isEditedPostNew, getCurrentPostId } = select( 'core/editor' );
+	const { isEditedPostNew, getCurrentPostId, getCurrentPostType } = select(
+		'core/editor'
+	);
+	const { getPostType, canUser } = select( 'core' );
+	const postId = getCurrentPostId();
+	const postType = getPostType( getCurrentPostType() );
+	const resource = postType?.[ 'rest_base' ] || '';
```
Comment (youknowriad) [inline packages/editor/src/components/post-trash/check.js:21]: Nit: I'd have avoided this temporary variable and just used postType in the check line 27.

**Review by youknowriad — COMMENTED** [review]
Code looks good. Do you know how we can test this easily? How can I create such user?

File: packages/editor/src/components/post-trash/check.js (hunk 1 above)
Comment (ocean90) [reply packages/editor/src/components/post-trash/check.js:21]: Hm, `resource` is used twice in line 27. Or do mean doing this instead?

`postId && postType ? canUser( 'delete', postType[ 'rest_base' ], postId ) : false,`

**Comment by ocean90** [comment]
> How can I create such user?

@youknowriad I have extended the description with four WP-CLI commands to create the role and user for testing.

File: packages/editor/src/components/post-trash/check.js (hunk 1 above)
Comment (youknowriad) [reply packages/editor/src/components/post-trash/check.js:21]: yep, that's exactly what I meant. It's just a very small detail without importance though.

**Review by youknowriad — APPROVED** [review]
👍
