### PR TITLE
Replaced "MenuGroup" with "NavigableMenu" in Warning Component. (Fixed:#12503)

### LINKED ISSUE #12503: Warning component should use a normal Menu instead of MenuGroup
Maybe more a visual inconsistency rather than an actual bug. The `Warning` component that appears, for example, when a block has invalid content, uses a `MenuGroup` component. 

`MenuGroup` renders also a sort of "title" for the wrapped "group" of menu items. However, I'm not sure this menu is supposed to have groups in the first place. Also, the visible title "More Options" doesn't make much sense:

screenshot 2018-12-01 at 16 29 26

It should probably use a `NavigableMenu` component instead of `MenuGroup`.

### PR DESCRIPTION
**Pull request by iamdharmesh**
## Description
Replaced "MenuGroup" with "NavigableMenu" in Warning Component. which get rid of menu group title "More options" and fixes #12503

## Screenshots
editor_warning_popover

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Review by jorgefilipecosta — APPROVED** [review]
Thank you for your contribution @iamdharmesh the code and tests look good to me.

Before:
screenshot 2018-12-03 at 15 03 04

After:
screenshot 2018-12-03 at 15 14 40

File: packages/editor/src/components/warning/index.js [hunk 1]
```diff
@@ -40,13 +40,13 @@ function Warning( { className, actions, children, secondaryActions } ) {
 						/>
 					) }
 					renderContent={ () => (
-						<MenuGroup label={ __( 'More options' ) }>
+						<NavigableMenu orientation="vertical" className="editor-warning-menu__content">
```
Comment (youknowriad) [inline packages/editor/src/components/warning/index.js]: This seems like a lower-level component and API-wise it seems better to have a `MenuGroup` wrapping `MenuItem`s which makes me wonder if we can't just support no passing a label to `MenuGroup` instead of this?

Comment (iamdharmesh) [reply packages/editor/src/components/warning/index.js]: @youknowriad Thanks for reviewing. Yes, you are right. better to use `MenuGroup` without label as `NavigableMenu` is lower-level component. I will make this change soon.

**Comment by afercia** [comment]
@youknowriad a `MenuGroup` without label will produce a `NavigableMenu` with an `aria-labelledby` attribute that points to nothing. That's against the ARIA spec, will be reported by accessibility automated tools as an error, and might confuse assistive technologies.

Also, I can understand high-level argumentations but I don't see the need to have a wrapping `<div>` element in the DOM that doesn't do anything.

I'd say either the `MenuGroup` should be changed to not render an `aria-labelledby` attribute if the "label" elements it points to is absent, or the `NavigableMenu` menu should be made a full citizen "high level" component.

**Comment by youknowriad** [comment]
> I'd say either the MenuGroup should be changed to not render an aria-labelledby attribute if the "label" element it points to is absent

This is what I had on my mind. People shouldn't have to think too much to understand how to use a given component.

**Comment by youknowriad** [comment]
Code wise, this looks good. Can we get another check after the recent changes?
