### PR TITLE
Fix zoom out not persisting while switching between editor and code editor

### LINKED ISSUE #65783: Zoom out mode doesn't persist when switching to code editor or between templates
### Description

When in zoomed-out view and switching to the code editor, the zoomed-out mode doesn't persist when closing the code editor. However, the button in the header remains active.

### Step-by-step reproduction instructions

Enable zoomed-out view (tested in post editor):

Screenshot 2024-10-01 at 14 13 48

Switch to code editor:

Screenshot 2024-10-01 at 14 13 59

Exit code editor:

Screenshot 2024-10-01 at 14 14 33

Note how the editor isn't in zoomed-out mode but the zoomed-out button remains active:

Screenshot 2024-10-01 at 14 14 46

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- Gutenberg `trunk` as of Oct 1
- Chrome

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### LINKED ISSUE #66157: Zoom-Out Screen Alignment and Toggle Behaviour Inconsistent Between Visual and Code Editors in Gutenberg
### Description

- When editing a post in the Gutenberg editor, the screen zooms out as expected if the "Zoom Out" toggle is selected in the visual editor.
- However, after switching to the code editor, the editor zooms back in, but the "Zoom Out" toggle remains selected.
- When switching back from the code editor to the visual editor, the editor screen aligns to the right instead of returning to its original zoomed-out state.

### Step-by-step reproduction instructions

1. Open a post in the Gutenberg editor.
2. Toggle the "Zoom Out" mode to zoom out the editor.
3. Switch from the visual editor to the code editor.
4. Notice the screen zooms back in, but the "Zoom Out" toggle remains selected instead of in-active "Zoom Out" toggle.
5. Switch back to the visual editor.
6. Notice the editor screen is right-aligned instead of returning to the zoomed-in state.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/1fc50f46-d248-4724-904d-f6fe906fff72

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### PR DESCRIPTION
**Pull request by madhusudhand**
## What?

This fixes the issue where zoom out isn't persisting while switching between 
* editor and code editor
* templates

Closes: #65783

## Why?

When the editor is switched, component gets destroyed and the value of `prevContainerWidthRef.current` is set to undefined.

The hook doesn't set the value because it is in ZoomedOut mode.

```
useEffect( () => {
	if ( ! isZoomedOut ) {
		prevContainerWidthRef.current = containerWidth;
	}
}, [ containerWidth, isZoomedOut ] );
```

## Testing Instructions

1. Enter to zoom out mode
2. switch to code editor and exit code editor
3. Now, it should get back to zoom out mode
4. It should work the same when templates are switched while in zoom out mode.

## Screenshots or screencast 

zoom-out-fix

### CODE REVIEW

**Comment by madhusudhand** [comment]
Looks like it is bring back the issue fixed in https://github.com/WordPress/gutenberg/pull/64478 after switching to code editor and back to editor.

This is because the scale calculation now directly depends on containerWidth (which is variable value)

I have put [this condition](https://github.com/WordPress/gutenberg/pull/65932/files#diff-ab17abd38e687edd56573694ae3017e105e96b319571c190e9d4705c1872bc9cR245), it works for code editor switching (because the container width doesn't change), but fails when switching to different template.

May be we have to preserve the previous container width outsize of component context?
Please suggest.

**Comment by draganescu** [comment]
I would suggest that we disable zoom out (scaling and mode) when we enter code editing - the bug now is that the mode is still on, the scaling is off. Let's approach like _all off_ because swithching to code is a sort of reset in terms of UI. Ideally we'll preserve the satate, but that is an enhancement. To fix the bug just set it all to off when switching to code.

**Comment by madhusudhand** [comment]
> I would suggest that we disable zoom out (scaling and mode) when we enter code editing

Makes sense. Editor now dispatches reset action in cleanup step (when component is unmounted).
It resets zoom out in cases of switching to code editor, switching to template viewer etc..

File: packages/block-editor/src/components/iframe/index.js [hunk 1]
```diff
@@ -310,7 +318,7 @@ function Iframe( {
 			'--wp-block-editor-iframe-zoom-out-scale',
 			scale === 'default'
 				? Math.min( containerWidth, maxWidth ) /
-						prevContainerWidthRef.current
+						( prevContainerWidthRef.current || containerWidth )
```
Comment (draganescu) [inline packages/block-editor/src/components/iframe/index.js]: Do we still need this?

File: packages/block-editor/src/components/iframe/index.js [hunk 2]
```diff
@@ -293,8 +295,14 @@ function Iframe( {
 		const _src = URL.createObjectURL(
 			new window.Blob( [ html ], { type: 'text/html' } )
 		);
-		return [ _src, () => URL.revokeObjectURL( _src ) ];
-	}, [ html ] );
+		return [
+			_src,
+			() => {
+				URL.revokeObjectURL( _src );
+				resetZoomLevel();
```
Comment (draganescu) [inline packages/block-editor/src/components/iframe/index.js]: Should we reset both zoom _and_ the mode? Check out the useZoomOut hook for all the stuff that is related.

**Review by draganescu — COMMENTED** [review]
Left some questions 🤝

File: packages/block-editor/src/components/iframe/index.js (hunk 2 above)
Comment (madhusudhand) [reply packages/block-editor/src/components/iframe/index.js]: Yes, thanks for pointing. Included `__unstableSetEditorMode('edit')`.

File: packages/block-editor/src/components/iframe/index.js (hunk 1 above)
Comment (madhusudhand) [reply packages/block-editor/src/components/iframe/index.js]: Right, this is no longer requires as zoom out is reset on component unmount, and `prevContainerWidthRef.current` is always set when component is mounted.

Removed in e6303353ebd6c4562dc7fb064e6f90446b25f31f

**Review by getdave — COMMENTED** [review]
Thanks for ongoing work here.

Tested and this now resets the Zoom when toggling Visual -> Code and back.

When moving between `Pages` Zoom Out is still persisted. I think we should be consistent with Templates and just reset it as soon as you change the post type / post ID.

Do you agree?


https://github.com/user-attachments/assets/70de8c0a-3cf2-47f0-80ad-d53ae00b40ab

File: packages/block-editor/src/components/iframe/index.js (hunk 2 above)
Comment (youknowriad) [reply packages/block-editor/src/components/iframe/index.js]: Can someone explain why we're resetting zoom-out in the iframe component? That feels like a random place.

**Comment by madhusudhand** [comment]
> When moving between Pages Zoom Out is still persisted. I think we should be consistent with Templates and just reset it as soon as you change the post type / post ID.

I think you are referring to switching pages from command bar (screenshot doesn't load for me)

In cases such as code editor, switching to other templates, pages etc from data views, user is moved out of editor and presented with something else and so zoom-out isn't valid in that context. (Hence adopted reset on exit of the editor)

Where as switching a page from command bar, user stays in the current view of the editor. 
I agree that it would be consistent to reset zoom-out in this case, but I think by doing so for consistency, I think it effects the zoom-out user experience.

File: packages/block-editor/src/components/iframe/index.js (hunk 2 above)
Comment (madhusudhand) [reply packages/block-editor/src/components/iframe/index.js]: I thought `iframe` to be better place because It is handling all zoom-out related calculations when component is mounted + on changes, and cleanup is naturally can go in there when it is unmounted.

Comment (madhusudhand) [reply packages/block-editor/src/components/iframe/index.js]: `useZoomOut` seems to be breaking with this changes (e.g. clicking on browse styles under global styles) triggers `zoom-out` and exits. This is likely because the hook triggered twice in dev mode.

**Comment by getdave** [comment]
I updated the comment above to include the screencapture.

I think we should exit zoom out when:

- switching Visual/Code Editor
- switching between Templates/Pages in Visual Site Editor mode

This PR is 99% of the way there.

File: packages/block-editor/src/components/iframe/index.js (hunk 2 above)
Comment (youknowriad) [reply packages/block-editor/src/components/iframe/index.js]: I think what's not clear to me is who is responsible for enabling/disabling zoom-out. Is it the "block editor" itself or is it something that the implementation (a button in the UI of the editor ... does). 

Switching to "code editor" is not a "block editor" thing, so sure the iframe is destroyed when you move to block editor but that doesn't mean you moved to "code editor". Maybe it's a "preview iframe". So you just wanted to render something else temporarily...

Comment (getdave) [reply packages/block-editor/src/components/iframe/index.js]: It's both. The design direction indicated a requirement for a manual toggle button. However, there are also scenarios where we want to be "intelligent" and enter/exit room out for certain actions.

I feel Zoom Out is a fairly opinionated state so we shouldn't leave it active if the users moves to do something else.

> Switching to "code editor" is not a "block editor" thing, so sure the iframe is destroyed when you move to block editor but that doesn't mean you moved to "code editor". Maybe it's a "preview iframe". So you just wanted to render something else temporarily...

I'm sorry but I wasn't fully able to follow what you meant here...

Comment (youknowriad) [reply packages/block-editor/src/components/iframe/index.js]: > I'm sorry but I wasn't fully able to follow what you meant here...

The iFrame is a component that can be used in several context to render "block content". It's shouldn't be related to zoom-out (aside receiving a "scale" prop to adapt). 

Also block-editor has zoom-out state but doesn't have "code editor" state. So if we want to exit zoom-out when we go into the code editor, it should be done at the highest common level (where the code editor state lives)

Comment (getdave) [reply packages/block-editor/src/components/iframe/index.js]: Thanks for elaborating 👍 

My understanding of the code in this PR is that the "zoom out mode" and "zoom level" will be reset when the iframe component is unmounted. This happens as part of a cleanup operation.

Your concern is that this is a blanket solution which will now apply each time the iframe is unmounted even in context's outside of the WordPress Editor implementation (this is because `@wordpress/block-editor` can be used to make an standalone editor). 

What you are recommending is that we act _specifically_ to exit zoom out where necessary based on the state that owns the action.

For example:

**Requirement**: exit Zoom Out when switching in/out of "Code Editor" mode.
**Solution**: add necessary code to exit Zoom Out to the `switchEditorMode` action.

**Requirement**: exit Zoom Out when switching between posts / templates in the Editor.
**Solution**: add necessary code to exit Zoom Out to `setEditedEntity` or perhaps `useInitEditedEntityFromURL`?

That seems logical. Rather than implement a blanket solution, allowing the consuming Editor instance to control when to exit Zoom Out rather than forcing on all implementations of block-editor.

Comment (youknowriad) [reply packages/block-editor/src/components/iframe/index.js]: Yes, thanks for expanding. "unmounting the iframe" seems too broad. As you can unmount the iframe in block previews too when you render and show them... you could argue block previews have their own "block editor state" which is true, but the point here is that the iframe is about rendering the blocks, not controlling which state we're in.

**Comment by getdave** [comment]
@madhusudhand I think this needs changes based on [this discussion](https://github.com/WordPress/gutenberg/pull/65932#discussion_r1799575309). Do you think you could get these resolved by Friday? That will allow us to ensure there is time to get this merged by Monday in time for WP 6.7 RC1 🙏

**Comment by madhusudhand** [comment]
@getdave Moved the logic to TextEditor to reset zoom-out mode, instead of resetting in iframe.

Also, with latest trunk, switching templates or anything in data views, preserves the zoom-out. 
(earlier behaviour was editor resets to full screen, but the zoom-out button was still in pressed state)

I think, the new behavior is intentional. I am excluding it from the current PR since it is no longer a bug. We can iterate it in a separate PR if it doesn't feel right.

**Comment by yani-** [comment]
I tried to test this by:
1. Going to https://playground.wordpress.net/gutenberg.html
2. Enter 65932 in the input and click Go
3. Go to pages -> All pages -> Edit Sample page
4. Clicked the zoom-out, clicked Code-Editor
5. Zoom-out button state changed to unchecked

Is this a playground issue where the patch is not being applied correctly?

**Comment by ironprogrammer** [comment]
In response to @yani-:
> 5. Zoom-out button state changed to unchecked
>
> Is this a playground issue where the patch is not being applied correctly?

The patch seems to have applied correctly 👍🏻 That is the expected behavior as suggested in https://github.com/WordPress/gutenberg/pull/65932#issuecomment-2399436997. Thanks for testing!

@madhusudhand and @getdave, I'd also like to confirm that the patch works as expected (since https://github.com/WordPress/gutenberg/pull/65932#issuecomment-2419129940).

## Test Report

### Environment
- Hardware: MacBook Pro Apple M1 Pro
- OS: macOS 14.6.1
- Browser: Safari 17.6
- Playground test link: https://playground.wordpress.net/gutenberg.html?pr=65932

### Actual Results
- ✅ Zoom Out toggle is reset after entering Code editor.
- ✅ When Code editor is active, setting Zoom Out toggle (on) is respected once Code editor is exited (i.e. you can turn it back on and it will be active on the template).
- ✅ When switching between templates or pages, the Zoom Out toggle mode is maintained.

### Screenshot
zoom-out-mode

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for addressing the feedback on this one @madhusudhand 👍 

I've taken it for a spin and it is working for me also.

✅ Switching to the Code Editor resets zoom out correctly
✅ If zoom out is toggled back on it is honored when leaving the Code Editor
✅ Zoom out is still maintained while switching between templates etc.

The PR appears to be in line with the discussion and [feedback received](https://github.com/WordPress/gutenberg/pull/65932#discussion_r1799618933) so far.

It might help others reviewing or trying to debug in the future if the PR title and description was updated to reflect the current state of this PR. 

That minor nit aside, the only odd behaviour I noticed was the ability to toggle on zoom out in a context where it shouldn't apply. This is the same currently for the Style Book and Global Styles Revisions. I think it's fine to address that via a follow-up and the related issue: https://github.com/WordPress/gutenberg/issues/66127.

If it helps land this fix for 6.7, I'm happy to give this a green light but feel free to seek a second approval from those that have been more involved up to this point.



https://github.com/user-attachments/assets/7f06e8cb-6ac9-4473-a4aa-bc28827e270c

**Comment by getdave** [comment]
Thanks for all the work here and reviews everyone 👍
