### PR TITLE
Fix Image block lightbox missing alt attribute and improve accessibility

### LINKED ISSUE #54971: Image: Lightbox buggy retrieval of alt attribute and insufficient accessibility
### Description

See also discussion on https://github.com/WordPress/gutenberg/pull/53026

The image lightbox needs some fixes and improvements:

1
Bug: at this point:

https://github.com/WordPress/gutenberg/blob/3e260aa41d3c50684efac9728bdbba918658d131/packages/block-library/src/image/index.php#L123-L127

the alt attribute is always null because the HTML processor points to the first element of the block content, which is a `figure` element: no alt attribute can be retrieved. As such, the button to open the lightbox is always labeled `Enlarge image` even when the image does have an alt attribute. Right now, the `Enlarge image` button doesn't tell anything about what the image is.

2
The button to open the lightbox should be moved _after_ the image in the DOM order. This is important especially for screen reader users. In a linearized content navigation experienc, it makes sense to place the 'what' first and then the action button after.

3
I'd argue the `Enlarge image` button placement inside the `<figure>` element isn't great from a semantics perspective. Ideally, the button should be moved outisde of the figure.

4
I still see an empty `role` attribute in the DOM before the lightbox is open. This is invalid HTML. Although seems to me this does not have an actual impact on accessibility because the modal dialog is `aria-hidden="true"`, WordPress has a tradition to always output valid markup on the front end. It would be great to focus more on the quality of the actual output markup.
`Bad value for attribute role on element [div]`

5
In the same way, an empty `src=""` attribute is output in the DOM. This is invalid HTML.
`Bad value for attribute src on element [img]: Must be non-empty.`
Edut: to clarify, this applies to the second image within the modal dialog, i.e. the 'scaled' one. Initially, the `src` attribute is empty and it gets populated only when opening the modal dialog and the second image gets loaded.

6
The `div` element meant to be used for the modal dialog of the enlarged image is either labelled `Image` or it is labelled witht he image alt attribute:
`<div role="" ... aria-label="Image" ...`
`<div role="" ... aria-label="{image alt attribute}" ...`
Some more meaningful labelling would be nice. This is the dialog element, not the image. The labelling should clarify what the dialog is about. ~Users click a button that says `Enlarge image: {alt text}` and they get a modal dialog that is only labelled `Image`.~

7 
The Close button target size is too small. With Twenty Twenty-Four is aproximately only 15 by 18 pixels.

8
The Close button dosn't visually expose its accessible name. All icon buttons _must_ always visually expose their name in some way. In the editor, we use the Tooltip component for this reason and it's already a compromise between design and accessibility. If this isn't possible on the front end, then tbe button must have visible text.

9
The enlarged image doesn't scale when resizing the window or changing device orientation. See the attached GIF for better clarity.

10
~Performance: with large images, the modal dialog contains two images: the `responsive-image` and the `enlarged-image`. While I do realize why two images are necessary, I'm not sure this is OK from a performance perspective, as there is always one image that is unnecessary given a certain viewport size.~
Edit: after a testing session together with @carolinan @aristath and @SergeyBiryukov we noticed this. may be not an issue, as on page load only one image is loaded. The second image is loaded when opening the modal dialog.

### Step-by-step reproduction instructions

- Add an image block to a post and set it to open in a lightbox.
- Publish the post and see the front end.
- Inspect the source, use the lightbox and check the points reported above.

### Screenshots, screen recording, code snippet

When changing device orientation (or resizine the browser window), the image in the open modal dialog doesn't scale correctly. It is cut-off on the left and right edges:

ligthbox scaling

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by afercia**
Addresses part of the issues from https://github.com/WordPress/gutenberg/issues/54971

## What?

- Fixes retrieval of the image alt attribute.
- Move the button to open the Lightboz _after_ the image.
- Better labelling for the Lightbox modal dialog: it must describe the dialog purpose, not the image itself.
- Removes `aria-hidden` from the closed modal dialog. This appears to be redundant as the closed modal dialog is already hidden from assistiv technology by the means of the `visibility: hidden` CSS property.
- Sets the `aria-modal` attribute dynamically instead of hardcoding on hte PHP side. This is also consistent with similar code in the navigation block.
- Sets the `aria-label` attribute dynamically.
- Increases the target size of the modal dialog Close button to be at least 40 by 40 pixels.
- Avoids to render an empty `role=""` attribute.
- Avoids to render an empty `src=""` attribute. A small base64 encoded gif is now used as 'placeholder' for the enlarged image.
- Minor docblocks improvements.

## Why?

- The retrieval of the image alt attribute to be added to the button to open the modal dialog was broken. Adding context to the button helps screen reader users understand what the button is about.
- Gaving the button before the image was not ideal for users who perceive content in a linearized way.
- The modal dialog labelling was set to the image alt text (if any) or the string 'Image' otherwise. This wasn not ideal, as the modal dialog labelling must explaiin what the dialog is about and not describe the image.
- Rendering incorrect or unnecessary `aria=*` attributes and `role` whren the modal dialog is closed is either invalid HTML or not ideal.
- The target size od the close button was really too small and dependent on inherited styles. 

## How?

See description above.

## Testing Instructions

- Create a post and add two images: one with alt attribute and the other one without.
- Set both images to open in the Ligthbox.
- Publish and see the front end.
- Inspect the source and make sure the button to open the modal dialog is labelled:
  - `Enlarge image` for the image without alt attribute.
  - `Enlarge image: {image alt text here}` for the image with alt attribute.
- Observe the button to open the modal dialog is now after the image in the DOM order.
- Open the modal dialog and observe the dialog is labelled `Enlarged image`.
- Observe the X close button size is not at least 40 by 40 pixels.

Additionally:
- After first page load and when the modal dialog is still closed, observe the modal dialog markup:
  - Does not have a `role` attribute.
  - Does not have an `aria-modal` attribute.
  - Does not have an `aria-hidden` attribute.
  - Does not have an `aria-label` attribute.
  - The `src` attribute of the enlarged image is a base64 encoded image.
- Open the modal dialog and observe that the dialog markup:
  - Does have a `role="dialog"` attribute.
  - Does have an `aria-modal="true"` attribute.
  - Does not have an `aria-hidden` attribute.
  - Does have an `aria-label="Enlarged image"` attribute.
  - The `src` attribute of the enlarged image is now the one of the actual enlarged image.

### CODE REVIEW

File: lib/block-supports/behaviors.php [hunk 1]
```diff
@@ -84,17 +84,22 @@ function gutenberg_render_behaviors_support_lightbox( $block_content, $block ) {
 
 	$aria_label = __( 'Enlarge image', 'gutenberg' );
 
+	$processor->next_tag( 'img' );
 	$alt_attribute = $processor->get_attribute( 'alt' );
 
+	// An empty alt attribute `alt=""` is valid for decorative images.
```
Comment (dmsnell) [inline lib/block-supports/behaviors.php:90]: excellent comment, and excellent fix above. one small note: `null` indicates that the `alt` attribute is missing, but an empty value would be `''` or if it's only present as a name like `src="…" alt loading=eager` then the value would be `true`

```php
if ( is_string( $alt_attribute ) ) {
```

this might be more appropriate, as it ensures that that we're dealing with an `alt=something` situation

File: lib/block-supports/behaviors.php [hunk 2]
```diff
@@ -84,17 +84,22 @@ function gutenberg_render_behaviors_support_lightbox( $block_content, $block ) {
...
 	}
 
+	// It only makes sense to append the alt text to the button aria-label when the alt text is non-empty.
 	if ( $alt_attribute ) {
 		/* translators: %s: Image alt text. */
 		$aria_label = sprintf( __( 'Enlarge image: %s', 'gutenberg' ), $alt_attribute );
 	}
-	$content = $processor->get_updated_html();
+
+	$processor = new WP_HTML_Tag_Processor( $block_content );
```
Comment (dmsnell) [inline lib/block-supports/behaviors.php]: is this line a mistake here? I think we still have the processor above in line 83

File: lib/block-supports/behaviors.php [hunk 3]
```diff
@@ -84,17 +84,22 @@ function gutenberg_render_behaviors_support_lightbox( $block_content, $block ) {
...
+	$content   = $processor->get_updated_html();
```
Comment (dmsnell) [inline lib/block-supports/behaviors.php]: if we don't have any calls to `set_attribute()` or other functions that modify the content, then this line isn't necessary. it should be equivalent to setting `$content = $block_content;`

am I missing some lines where we set the `alt` attribute or aria label before this line?

File: packages/block-library/src/image/index.php [hunk 4]
```diff
@@ -113,28 +115,34 @@ function block_core_image_get_lightbox_settings( $block ) {
...
  */
 function block_core_image_render_lightbox( $block_content, $block ) {
 	$processor = new WP_HTML_Tag_Processor( $block_content );
 
 	$aria_label = __( 'Enlarge image' );
 
+	$processor->next_tag( 'img' );
 	$alt_attribute = $processor->get_attribute( 'alt' );
 
+	// An empty alt attribute `alt=""` is valid for decorative images.
```
Comment (dmsnell) [inline packages/block-library/src/image/index.php:133]: see above comment about `is_string()`

File: packages/block-library/src/image/index.php [hunk 5]
```diff
@@ -113,28 +115,34 @@ function block_core_image_get_lightbox_settings( $block ) {
...
 
+	// It only makes sense to append the alt text to the button aria-label when the alt text is non-empty.
 	if ( $alt_attribute ) {
 		/* translators: %s: Image alt text. */
 		$aria_label = sprintf( __( 'Enlarge image: %s' ), $alt_attribute );
 	}
-	$content = $processor->get_updated_html();
+
+	$processor = new WP_HTML_Tag_Processor( $block_content );
+	$content   = $processor->get_updated_html();
```
Comment (dmsnell) [inline packages/block-library/src/image/index.php]: see above comments about recreating the processor and getting unmodified contents.

**Review by dmsnell — COMMENTED** [review]
I know it's early, but there are a few small nudges here w.r.t. the Tag Processor. happy to help with them if there's anything confusing about the comments or how to use it.

File: lib/block-supports/behaviors.php (hunk 2 above)
Comment (afercia) [reply lib/block-supports/behaviors.php]: I'm not familiar with the processor inner workings. To my understanding, after the `next_tag( 'img' )` the processor points to the image and not to the entire chunk of HTML. Would `get_updated_html();` work anyways. Or am I supposed to create a new instance of the processor? I see several instances od the processor being created, I assumed for this reason. Also, the instances are assigner to variables that I'd argue could be better named. Variable names like `$w`, `$m`, `$q` are very confusing and aren't sekf-explanatory. While those short variable names used to be broadely adopted in the early ages of WordPress, I thought that is nwo considered a non-ideal practice. Certainly doesn't help beginners understand how the processor is supposed ot be used.

File: lib/block-supports/behaviors.php (hunk 1 above)
Comment (afercia) [reply lib/block-supports/behaviors.php:90]: In a way, the check is a  bit redundant in the first place. As far as I know, WordPress enforces at least an empty `alt=""` attribute everywhere. I'd agree to check for string anyways, just in case.

File: lib/block-supports/behaviors.php (hunk 3 above)
Comment (afercia) [reply lib/block-supports/behaviors.php]: I'm not sure I understand how the processor is used in this file. If that's true, then why creating one more instance at line 111 and assigning it to `$z`? Is the content modified in any way before that point?

**Comment by afercia** [comment]
A few notes:

- I'm not sure whether all the markup changes need to be applied also to the `lib/block-supports/behaviors.php` file. So far, I made only a few changes there. 
- It's still not fully clear to me how the tag processor is supposed to be used. Currently, the class `WP_HTML_Tag_Processor` is instantiated 6 times in the image block `index.php` file and 5 times in the `behaviors.php` file. That seems a bit too much to me. Some help would be greatly appreciated @dmsnell 
- Regarding the `aria-label` I could use the same approach taken in https://github.com/WordPress/gutenberg/pull/54816 for consistency, even though in this case the element is hidden and does not impact accessibility.

File: lib/block-supports/behaviors.php (hunk 3 above)
Comment (artemiomorales) [reply lib/block-supports/behaviors.php]: > if we don't have any calls to set_attribute() or other functions that modify the content, then this line isn't necessary. it should be equivalent to setting $content = $block_content;
>
> am I missing some lines where we set the alt attribute or aria label before this line?

It looks like this line is no longer necessary and was from an earlier implementation — we can remove this.

> I'm not sure I understand how the processor is used in this file. If that's true, then why creating one more instance at line 111 and assigning it to $z? Is the content modified in any way before that point?

This new instance also looks like it is not necessary — it can be removed and we can reuse the first instance.

File: lib/block-supports/behaviors.php (hunk 2 above)
Comment (artemiomorales) [reply lib/block-supports/behaviors.php]: > Would get_updated_html(); work anyways. Or am I supposed to create a new instance of the processor?

Good catch — we no longer need $content here, and we we're not modifying any HTML yet, so we don't need to do the `$processor->get_updated_html()` call either.

> I see several instances od the processor being created, I assumed for this reason.

> Also, the instances are assigner to variables that I'd argue could be better named. Variable names like $w, $m, $q are very confusing and aren't sekf-explanatory.

The other instances of the processor are created because we need to do different processing on the `figure` and `img` elements for each instance. 

Note: We create new instances of the processor for these three scenarios because the processor is [unable to back up or reverse](https://github.com/WordPress/gutenberg/blob/0816b4cdf016f64f580853dbd39c9228eec5c5f4/lib/compat/wordpress-6.3/html-api/class-gutenberg-html-tag-processor-6-3.php#L77).

There is an exception to that though — we could [create a bookmark](https://github.com/WordPress/gutenberg/blob/0816b4cdf016f64f580853dbd39c9228eec5c5f4/lib/compat/wordpress-6.3/html-api/class-gutenberg-html-tag-processor-6-3.php#L171) for the `figure` element and use that to refactor the code for clarity, removing the need for the different instances and cutting down on the variable names if you think that would be clearer. I believe that should work.

Another option: We could rename the `$w`, `$m`, and `$q` variables to `$lightbox_container_processor`, `$initial_image_processor`, and `$enlarged_image_processor`, or something along those lines.

In either case, we can just use `$block_content` for the new instance(s) rather than `$content` — which is [no longer necessary](https://github.com/WordPress/gutenberg/pull/55010/files#r1347947873) — and that should help make the code clearer as well.

**Comment by artemiomorales** [comment]
@afercia Tbanks for opening this PR! Here are some notes:

> I'm not sure whether all the markup changes need to be applied also to the lib/block-supports/behaviors.php file. So far, I made only a few changes there.

All the changes would need to be applied to the `behaviors.php` as well.

> It's still not fully clear to me how the tag processor is supposed to be used. Currently, the class WP_HTML_Tag_Processor is instantiated 6 times in the image block index.php file and 5 times in the behaviors.php file. That seems a bit too much to me. Some help would be greatly appreciated @dmsnell

I left comments [here](https://github.com/WordPress/gutenberg/pull/55010#discussion_r1347982050) and [here](https://github.com/WordPress/gutenberg/pull/55010#discussion_r1347947873) on the usage of the processor. In short, 1.) some of the code is outdated and can be removed, and 2.) we could make use of a [bookmark](https://github.com/WordPress/gutenberg/blob/0816b4cdf016f64f580853dbd39c9228eec5c5f4/lib/compat/wordpress-6.3/html-api/class-gutenberg-html-tag-processor-6-3.php#L171) to cut down on instantiating new Tag Processor instances if that would help with readability.

File: lib/block-supports/behaviors.php (hunk 2 above)
Comment (dmsnell) [reply lib/block-supports/behaviors.php]: > I see several instances od the processor being created, I assumed for this reason. Also, the instances are assigner to variables that I'd argue could be better named. Variable names like $w, $m, $q are very confusing and aren't sekf-explanatory. While those short variable names used to be broadely adopted in the early ages of WordPress, I thought that is nwo considered a non-ideal practice. Certainly doesn't help beginners understand how the processor is supposed ot be used.

Yeah this code is ripe for refactoring. Maybe next week @artemiomorales and I can try and do that. The names, the duplicate processors, they can all be improved.

> Would get_updated_html(); work anyways.

@afercia `get_updated_html()` will always return the full HTML document. if nothing has been modified it will be identical to what was passed in when creating the Tag Processor. if modifications have been made, it will return the result of applying all requested changes to that document.

**Review by artemiomorales — COMMENTED** [review]
@afercia I followed the test instructions and everything seems to be working.

I pushed up a change removing some obsolete code that should hopefully make the usage of the Tag Processor clearer.

I also added some changes to `block-support/behaviors.php`, and also added its inclusion in `load.php`, which was apparently mistakenly removed at some point.

Note: I'm finding the block supports hard to test since we no longer use it for any part of the image or lightbox. Since we fire a `_deprecated_function()` call that breaks the layout on the front end anyway, it makes me think that keeping the `behaviors.php` up-to-date is actually not strictly necessary, but I'm happy to hear other thoughts on this.

I can approve this PR pending a decision on how to handle code cleanup on the multiple instances of the Tag Processor. Thanks! 🙏

File: lib/block-supports/behaviors.php (hunk 2 above)
Comment (artemiomorales) [reply lib/block-supports/behaviors.php]: @dmsnell Sure, we can do that 👍

**Comment by artemiomorales** [comment]
> Regarding the aria-label I could use the same approach taken in https://github.com/WordPress/gutenberg/pull/54816 for consistency, even though in this case the element is hidden and does not impact accessibility.

@afercia As of this writing, what's in this PR at the moment for the aria-label looks good to me 👍

**Comment by dmsnell** [comment]
It seems fitting to me to let this slide through without addressing all the Tag Processor issues. We can hit those up in a single pass after updating the `alt` attributes. This is the exact reason the existing uses haven't been cleaned up, because I didn't want to distract the lightbox work, but I think the time is right to circle back and address them.

**Comment by artemiomorales** [comment]
> It seems fitting to me to let this slide through without addressing all the Tag Processor issues. We can hit those up in a single pass after updating the alt attributes. This is the exact reason the existing uses haven't been cleaned up, because I didn't want to distract the lightbox work, but I think the time is right to circle back and address them.

This actually sounds good to me, as there's already a fair amount happening in this PR. I'll go ahead and approve it.

**Review by artemiomorales — APPROVED** [review]

**Comment by dmsnell** [comment]
Thanks both of you!

**Comment by afercia** [comment]
Thanks everyone for your feedback and clarifications.

**Comment by mikachan** [comment]
I just cherry-picked this PR to the 6.4-beta3 branch to get it included in the next release: https://github.com/WordPress/gutenberg/pull/55039/commits/89f5e338f217e3ab67a35fb7f778f4af46f78079

**Comment by getdave** [comment]
✅ I updated the [PHP Sync Tracking Issue for WP 6.5](https://github.com/WordPress/gutenberg/issues/57959) to note this PR does not require a backport for WP 6.5 as it seems to have been cherry picked into WP 6.4 by @mikachan.
