### PR TITLE
[Block Library - Query Loop]: Render `replace` button only if eligible patterns exist 

### LINKED ISSUE #41673: Removing theme support for core-block-patterns breaks query loop block "replace" button
### Description

In 6.0, when using remove_theme_support('core-block-patterns'), the query loop block still renders a "replace" button in its toolbar, however the functionality appears to depend on core-block-patterns. Clicking it will error and take down the query block.

```
Uncaught Error: Gb(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at react-dom.js?ver=6.0:1:125895
    at op (react-dom.js?ver=6.0:1:152204)
    at react-dom.js?ver=6.0:1:168586
    at Up (react-dom.js?ver=6.0:1:168617)
    at HTMLUnknownElement.g (react-dom.js?ver=6.0:1:47905)
    at Object.An (react-dom.js?ver=6.0:1:48230)
    at $n (react-dom.js?ver=6.0:1:49191)
    at ev (react-dom.js?ver=6.0:1:216800)
    at Lm (react-dom.js?ver=6.0:1:208503)
    at Im (react-dom.js?ver=6.0:1:208388)

The above error occurred in the <Gb> component:

    at Gb (http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:83:7913)
    at div
    at div
    at Zr (http://localhost:8333/wp-content/plugins/gutenberg/build/components/index.min.js?ver=41354114565391fde42d:1:267518)
    at div
    at e (http://localhost:8333/wp-content/plugins/gutenberg/build/components/index.min.js?ver=41354114565391fde42d:22:1608)
    at edit (http://localhost:8333/wp-content/plugins/gutenberg/build/block-library/index.min.js?ver=d9ca0462d9d463c59e15:113:16100)
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:7:11280
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:7:3994
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:7:5903
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:7:7477
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:73:2524
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:73:8182
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:73:10952
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-library/index.min.js?ver=d9ca0462d9d463c59e15:113:14928
    at http://localhost:8333/wp-content/plugins/gutenberg/build/edit-post/index.min.js?ver=ec8b0ebb9e6aa14099ef:1:5665
    at http://localhost:8333/wp-content/plugins/gutenberg/build/data/index.min.js?ver=1521e4b605f0ac3bf60d:1:25068
    at http://localhost:8333/wp-content/plugins/gutenberg/build/data/index.min.js?ver=1521e4b605f0ac3bf60d:1:24548
    at <anonymous> (http://localhost:8333/wp-content/plugins/gutenberg/build/compose/index.min.js?ver=6a957e31a1a9ec093751:1:18340)
    at o (http://localhost:8333/wp-content/plugins/gutenberg/build/components/index.min.js?ver=41354114565391fde42d:57:11514)
    at hl (http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:7:11725)
    at Bl (http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:10:427)
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:10:52605
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:7:4612
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:64:21068
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:66:6218
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:71:5698
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:73:2860
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:73:8426
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:73:11161
    at o (http://localhost:8333/wp-content/plugins/gutenberg/build/components/index.min.js?ver=41354114565391fde42d:57:11514)
    at http://localhost:8333/wp-content/plugins/gutenberg/build/compose/index.min.js?ver=6a957e31a1a9ec093751:1:18120
    at http://localhost:8333/wp-content/plugins/gutenberg/build/data/index.min.js?ver=1521e4b605f0ac3bf60d:1:25068
    at http://localhost:8333/wp-content/plugins/gutenberg/build/data/index.min.js?ver=1521e4b605f0ac3bf60d:1:24548
    at <anonymous> (http://localhost:8333/wp-content/plugins/gutenberg/build/compose/index.min.js?ver=6a957e31a1a9ec093751:1:18250)
    at Ff (http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:64:10507)
    at zf
    at div
    at Df (http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:64:9292)
    at kf (http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:64:2454)
    at Of (http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:64:10383)
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:108:11445
    at div
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:10:68645
    at qt (http://localhost:8333/wp-content/plugins/gutenberg/build/edit-post/index.min.js?ver=ec8b0ebb9e6aa14099ef:19:1668)
    at div
    at t (http://localhost:8333/wp-content/plugins/gutenberg/build/components/index.min.js?ver=41354114565391fde42d:1:364146)
    at http://localhost:8333/wp-content/plugins/gutenberg/build/components/index.min.js?ver=41354114565391fde42d:1:364927
    at div
    at t (http://localhost:8333/wp-content/plugins/gutenberg/build/components/index.min.js?ver=41354114565391fde42d:1:364146)
    at http://localhost:8333/wp-content/plugins/gutenberg/build/components/index.min.js?ver=41354114565391fde42d:1:364927
    at Op (http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:30:5433)
    at div
    at wy (http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:108:3481)
    at jt (http://localhost:8333/wp-content/plugins/gutenberg/build/edit-post/index.min.js?ver=ec8b0ebb9e6aa14099ef:19:2225)
    at div
    at div
    at div
    at div
    at http://localhost:8333/wp-content/plugins/gutenberg/build/edit-post/index.min.js?ver=ec8b0ebb9e6aa14099ef:1:19247
    at co (http://localhost:8333/wp-content/plugins/gutenberg/build/edit-post/index.min.js?ver=ec8b0ebb9e6aa14099ef:53:65)
    at Ho (http://localhost:8333/wp-content/plugins/gutenberg/build/editor/index.min.js?ver=6bee187f195e8fe48330:3:6891)
    at vo (http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:3:15121)
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:10:58449
    at http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:10:58088
    at WithRegistryProvider(Component)
    at pl (http://localhost:8333/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=5ac2be4f88511bdea30c:7:11043)
    at yn (http://localhost:8333/wp-content/plugins/gutenberg/build/core-data/index.min.js?ver=4904924922eddb0c37df:1:45829)
    at yn (http://localhost:8333/wp-content/plugins/gutenberg/build/core-data/index.min.js?ver=4904924922eddb0c37df:1:45829)
    at http://localhost:8333/wp-content/plugins/gutenberg/build/editor/index.min.js?ver=6bee187f195e8fe48330:39:1602
    at http://localhost:8333/wp-content/plugins/gutenberg/build/editor/index.min.js?ver=6bee187f195e8fe48330:39:775
    at WithRegistryProvider(Component)
    at ro (http://localhost:8333/wp-content/plugins/gutenberg/build/components/index.min.js?ver=41354114565391fde42d:1:268564)
    at oo (http://localhost:8333/wp-content/plugins/gutenberg/build/components/index.min.js?ver=41354114565391fde42d:1:269412)
    at so (http://localhost:8333/wp-content/plugins/gutenberg/build/components/index.min.js?ver=41354114565391fde42d:1:271185)
    at div
    at U (http://localhost:8333/wp-content/plugins/gutenberg/build/keyboard-shortcuts/index.min.js?ver=cc02bc92e52e72d357cb:1:4216)
    at mo (http://localhost:8333/wp-content/plugins/gutenberg/build/edit-post/index.min.js?ver=ec8b0ebb9e6aa14099ef:57:819)

React will try to recreate this component tree from scratch using the error boundary you provided, Bl.
```

### Step-by-step reproduction instructions

1. Use remove_theme_support('core-block-patterns') in your theme
2. Create a post/page
3. Add a query block
4. Click "replace" in the query block's toolbar.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WP 6.0
- Occurs with or without activating Gutenberg 13.4.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/41673

If we don't have eligible Query Loop patterns we shouldn't show the `replace` toolbar button.

## Testing Instructions
1. Use a theme without Query Loop semantic patterns (with `blockTypes` property)
2. Remove the core Query Loop patterns(`remove_theme_support( 'core-block-patterns' );`)
3. Insert a Query Loop block, or select an existing one 
4. You should not see the `Replace` toolbar button, in block's toolbar

### CODE REVIEW

**Comment by mcsf** [comment]
Should we also fix the offending component from the [original report](https://github.com/WordPress/gutenberg/issues/41673)? From the React error ("Nothing was returned from render."), there is likely a component somewhere that is failing to return any output (even if just `null`) when there are no patterns available.

**Comment by ntsekouras** [comment]
>Should we also fix the offending component from the https://github.com/WordPress/gutenberg/issues/41673? From the React error ("Nothing was returned from render."), there is likely a component somewhere that is failing to return any output (even if just null) when there are no patterns available.

I updated the code to not render anything and noticed that in the last update by @jorgefilipecosta there, we don't use `startBlankComponent` as it was originally designed for. I think there were still some discussions about some of the design here, but if we end up that we don't need it, we should consider removing this functionality altogether. 

Personally I think it's okay to keep it there a bit more as I'm not sure the designs/flow are finalized, and are a bit different from Template Parts that we might want to consolidate. We can do it in a follow up if we need to, no?

**Comment by mcsf** [comment]
Yeah, I'm good with that, thanks for the context and fix.

File: packages/block-editor/src/components/block-pattern-setup/index.js [hunk 1]
```diff
@@ -145,7 +145,7 @@ const BlockPatternSetup = ( {
 	clientId,
 	blockName,
 	filterPatternsFn,
-	startBlankComponent,
+	startBlankComponent = null,
```
Comment (jorgefilipecosta) [inline packages/block-editor/src/components/block-pattern-setup/index.js:148]: I think we can remove the startBlankComponent, it is not being used anywhere, so I guess it is just something leftover from a chance and we missed its removal.

**Review by mcsf — APPROVED** [review]

**Review by jorgefilipecosta — APPROVED** [review]
The code change looks good to me. I left a comment related to the startBlankComponent removal.

File: packages/block-editor/src/components/block-pattern-setup/index.js (hunk 1 above)
Comment (ntsekouras) [reply packages/block-editor/src/components/block-pattern-setup/index.js:148]: Let's do this in a follow up.
