### PR TITLE
Fix: Comment Query Loop's inner block selection and duplicate inspector control settings

### LINKED ISSUE #38080: Duplicated settings in inspector controls on Comments Query Loop block
### Description

When I add a Comments Query Loop, if we set more than 2 items per page. Most of the sidebars options of all inner elements appear `n` times, being `n` equal to `items per page -1`.

### Step-by-step reproduction instructions

1. Go to a page or a post with comments, you need to have at least 3 comments.
2. Use the toolbar option to change the comments per page.
3. Click on any inner block of the Comment Template and check sidebar for duplicated settings.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/37012961/150172814-a2c82ca9-8792-4b8d-ac2f-1671ba7a2272.mov

### Environment info

- WordPress version 5.9-beta3-52380
- Gutenberg version "trunk"

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #39443: Cannot select inner blocks in the Comments Query Loop block
### Description

Comments Query Loop block contains inner blocks like Comment Content, Comment Date, etc.

It is currently not possible to select those blocks after inserting the Comments Query Loop.

### Step-by-step reproduction instructions

1. Insert a new Comments Query Loop block.
2. Click on one of it's inner blocks like Comment Date.
3. The inner block does not get selected.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/5417266/158282398-bc2ce8f3-3112-4067-844f-6fe36dff94f4.mov

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by michalczaplinski**
## What?
Fixing those two issues:
- #39443
- #38080

## Why?
Those issues were preventing forther work on the Comments Query Loop and Comments Template.

## How?
1. Change how the active comment is being compared to current comment in `CommentTemplateInnerBlocks`
2. Move the `firstComment` one level higher in the component tree.

(More detailed comments below)

## Testing Instructions
1. Create a post and add some comments to it
2. Open the post using any FSE theme
3. Try to insert the Comments Query Loop block

## Screenshots or screencast 

Now, the selection works just fine with no duplicate Inspector Controls:

https://user-images.githubusercontent.com/5417266/158495315-379f5686-5334-4cbb-a422-844b1c72229a.mp4

### CODE REVIEW

File: packages/block-library/src/comment-template/edit.js [hunk 1]
```diff
@@ -200,7 +210,7 @@ const CommentsList = ( {
 						activeComment={ activeComment }
 						setActiveComment={ setActiveComment }
 						blocks={ blocks }
-						firstComment={ comments[ 0 ] }
```
Comment (michalczaplinski) [inline packages/block-library/src/comment-template/edit.js:203]: We have to remove this and add a `firstComment` prop to the `CommentList` directly (one level higher in the tree). This is because otherwise, **at each level of comment nesting** we would create an active comment block! And this causes both the duplicate Inspector controls to show up and the weird selection issues.

You can compare it with [how this works](https://github.com/WordPress/gutenberg/blob/2323eeca3d0bc8b2723333ccb831ae731ae841aa/packages/block-library/src/post-template/edit.js#L211-L224) in the `post-template` block.

File: packages/block-library/src/comment-template/edit.js [hunk 2]
```diff
@@ -103,7 +103,10 @@ function CommentTemplateInnerBlocks( {
 	);
 	return (
 		<li { ...innerBlocksProps }>
-			{ comment === ( activeComment || firstComment ) ? children : null }
+			{ comment.commentId ===
```
Comment (michalczaplinski) [inline packages/block-library/src/comment-template/edit.js]: The comments have to be compared by `commentId` which is a string (compared by value) rather than comparing comment objects (which are compared by reference).

**Comment by cbravobernal** [comment]
# Test Report: Fix comment query Loop's duplicate inspector controls

Env:
- Localhost: wp-env
- Browser: Chrome
- WordPress: latest trunk
- Gutenberg: latest trunk and without the plugin activated
- OS: macOS Monterey
   
## Steps to reproduce:
- Go to Posts > Add New
- Add some comments to the post
- Add a Comments Query Loop Block - use the default `Inherit` option
- Check that the settings are appearing duplicated and that we cannot select the inner blocks.

## Before applying the PR on the default page:
- Inner blocks are not clickable ❌
- Appears duplicated inspector control settings ❌

Able to reproduce the issue ✅ 

Screenshot 2022-03-16 at 11 29 09

After applying the PR:
- Inner blocks are clickable  ✅ 
- Inspector control settings appear only once ✅ 
Screenshot 2022-03-16 at 11 34 25


## Findings

- Able to reproduce the issue ✅ 
- Confirm the PR resolves the issue ✅

File: packages/block-library/src/comment-template/edit.js [hunk 3]
```diff
@@ -103,7 +103,10 @@ function CommentTemplateInnerBlocks( {
...
+			( activeComment?.commentId || firstComment?.commentId )
```
Comment (ockham) [inline packages/block-library/src/comment-template/edit.js]: I find it a bit uncommon to put the logical `||` on the RHS of the comparison (`===`). Can we maybe rewrite it as

```suggestion
			{ ( comment.commentId === activeComment?.commentId ) ||
			( ( comment.commentId === firstComment?.commentId )
```

or alternatively

```suggestion
			{ [ activeComment?.commentId, firstComment?.commentId ].includes ( comment.commentId )
```

File: packages/block-library/src/comment-template/edit.js [hunk 4]
```diff
@@ -116,7 +119,10 @@ function CommentTemplateInnerBlocks( {
 				blocks={ blocks }
 				comment={ comment }
 				setActiveComment={ setActiveComment }
-				isHidden={ comment === ( activeComment || firstComment ) }
+				isHidden={
+					comment.commentId ===
+					( activeComment?.commentId || firstComment?.commentId )
```
Comment (ockham) [inline packages/block-library/src/comment-template/edit.js]: Same as https://github.com/WordPress/gutenberg/pull/39472/files#r827921344

**Comment by gziolo** [comment]
Excellent detectie work. It feels so great to see it sorted out.

**It's totally outside of the scope of this PR.** On the recorded screencast in the description, I'm still seeing that you need to click twice when you select a block from the block template for another comment than the one currently selected. At first, the Comment Template block gets selected and you need to click again to select the inner block. I guess it's expected with the current implementation because we probably re-render the clicked Comment Template block after the interaction. Maybe the only change we need is some sort of UI indicator that helps users to better guide users since the wrapping Comment Template block can have a lot of content and the toolbar shows up sometimes at the top of the page. Example from the screencast:

Screenshot 2022-03-16 at 13 03 49

File: packages/block-library/src/comment-template/edit.js (hunk 3 above)
Comment (michalczaplinski) [reply packages/block-library/src/comment-template/edit.js]: I've never heard of such a rule to be honest! Since they are logically equivalent so I just prefer the shorter version 🙂

But I'm happy to change it - I went with the version number 1 from above.

**Comment by michalczaplinski** [comment]
There is some more weirdness happening so this issue is not really fixed yet! :( 

I did some further testing and it appears that if there are multiple comments (not nested), the duplicate inspector controls do not appear for the first comment, but they **do appear** for the 2nd , 3rd and subsequent comments 🤷 

https://user-images.githubusercontent.com/5417266/158654061-7c18d15f-609f-4a46-8533-b3d45fb59753.mp4

**Comment by michalczaplinski** [comment]
>  On the recorded screencast in the description, I'm still seeing that you need to click twice when you select a block from the block template for another comment than the one currently selected.

@gziolo I've opened a new issue to track that separately: https://github.com/WordPress/gutenberg/issues/39510

File: packages/block-library/src/comment-template/edit.js (hunk 3 above)
Comment (michalczaplinski) [reply packages/block-library/src/comment-template/edit.js]: Oh, I should have been a bit more vigilant here because those are not actually logically equivalent 🤦 The original version expresses the correct logic whereas the "new" one does not. Let me explain.

Let's give the variables some values so let's say that:

```js
comment.commentId = 1;
activeComment?.commentId = 2,
firstComment?.commentId = 1;

// This is the "new" version
console.log(
  comment.commentId === activeComment?.commentId || 
  comment.commentId === firstComment?.commentId
); 
// true

// This is the "old" version
console.log(
  comment.commentId ===
    ( activeComment?.commentId || firstComment?.commentId )
); 
// false
```

In the old version, we short-circuit the RHS! This translates to:

If `activeComment?.commentId` is truthy (meaning that an active comment exists) compare it with `comment.commentId`. Otherwise, if the active comment does not exist, try to use the firstComment and compare it with `comment.commentId`.

Comment (ockham) [reply packages/block-library/src/comment-template/edit.js]: Ah, gotcha 🤔  Sorry for the accidental breakage introduced by my request! 😅

**Comment by ockham** [comment]
Unfortunately, the problem still persists in the _Site_ Editor -- probably because we're using the "generic"/"empty" version of the Comment blocks, i.e. with no actual comments set -- and `commentId` thus being `null` for all of them.

I wonder if there's some prior art to this problem, e.g. in the (Post) Query block...

File: packages/block-library/src/comment-template/edit.js [hunk 5]
```diff
@@ -178,6 +185,8 @@ const MemoizedCommentTemplatePreview = memo( CommentTemplatePreview );
  * @param {Array}  [props.activeComment]    - The block that is currently active.
  * @param {Array}  [props.setActiveComment] - The setter for activeComment.
  * @param {Array}  [props.blocks]           - Array of blocks returned from
+ * @param {Object} [props.firstComment]     - The first comment in the array of
+ *                                          comment objects.
  *                                          getBlocks() in parent .
```
Comment (ockham) [inline packages/block-library/src/comment-template/edit.js]: Looks like the JSDoc for `[props.blocks]` was torn apart 😅 

```suggestion
 * @param {Array}  [props.blocks]           - Array of blocks returned from
 *                                          getBlocks() in parent .
 * @param {Object} [props.firstComment]     - The first comment in the array of
 *                                          comment objects.
```

**Comment by ockham** [comment]
> Unfortunately, the problem still persists in the _Site_ Editor -- probably because we're using the "generic"/"empty" version of the Comment blocks, i.e. with no actual comments set -- and `commentId` thus being `null` for all of them.

Trying to think our comment criteria through, based on [this comment](https://github.com/WordPress/gutenberg/pull/39472/files#r828558492).

> If `activeComment?.commentId` is truthy (meaning that an active comment exists) compare it with `comment.commentId`. Otherwise, if the active comment does not exist, try to use the firstComment and compare it with `comment.commentId`.

I understand that this is the criterion for _rendering_ a comment's nested child comments, vs. just [previewing](https://github.com/WordPress/gutenberg/blob/e3f1d99559ebfe9de9d23424124818d032cc9bc6/packages/block-library/src/comment-template/edit.js#L108-L120) it (in which case we don't render its inspector controls).

Trying to capture what else we know:

If the current comment's ID is `null`, it's a placeholder. This can either mean either mean that we're still loading comments, or that _all_ comments are placeholders. Either way, there'll be more comments with `commentId === null` (unless this one is the last to load, but let's ignore that for now).

To be continued.

**Comment by ockham** [comment]
While not immediately fixing the issue at hand, how about we make a small change to our `firstComment` fallback handling? While I understand it after looking at the code for a while, I find that our logic could be easier to grasp if we only compared (the IDs of) `comment` to `activeComment` everywhere, and instead initialized top-level `activeComment` state as `commentTree[0]`:

```diff
diff --git a/packages/block-library/src/comment-template/edit.js b/packages/block-library/src/comment-template/edit.js
index 6f0e61adbe..7d901fdd40 100644
--- a/packages/block-library/src/comment-template/edit.js
+++ b/packages/block-library/src/comment-template/edit.js
@@ -85,7 +85,6 @@ const getCommentsPlaceholder = ( {
  * @param {Array}  [props.comment]          - A comment object.
  * @param {Array}  [props.activeComment]    - The block that is currently active.
  * @param {Array}  [props.setActiveComment] - The setter for activeComment.
- * @param {Array}  [props.firstComment]     - First comment in the array.
  * @param {Array}  [props.blocks]           - Array of blocks returned from
  *                                          getBlocks() in parent .
  * @return {WPElement}                 		Inner blocks of the Comment Template
@@ -94,7 +93,6 @@ function CommentTemplateInnerBlocks( {
 	comment,
 	activeComment,
 	setActiveComment,
-	firstComment,
 	blocks,
 } ) {
 	const { children, ...innerBlocksProps } = useInnerBlocksProps(
@@ -103,10 +101,7 @@ function CommentTemplateInnerBlocks( {
 	);
 	return (
 		<li { ...innerBlocksProps }>
-			{ comment.commentId ===
-			( activeComment?.commentId || firstComment?.commentId )
-				? children
-				: null }
+			{ comment.commentId === activeComment?.commentId ? children : null }
 
 			{ /* To avoid flicker when switching active block contexts, a preview
 			is ALWAYS rendered and the preview for the active block is hidden.
@@ -119,10 +114,7 @@ function CommentTemplateInnerBlocks( {
 				blocks={ blocks }
 				comment={ comment }
 				setActiveComment={ setActiveComment }
-				isHidden={
-					comment.commentId ===
-					( activeComment?.commentId || firstComment?.commentId )
-				}
+				isHidden={ comment.commentId === activeComment?.commentId }
 			/>
 
 			{ comment?.children?.length > 0 ? (
@@ -131,7 +123,6 @@ function CommentTemplateInnerBlocks( {
 					activeComment={ activeComment }
 					setActiveComment={ setActiveComment }
 					blocks={ blocks }
-					firstComment={ firstComment }
 				/>
 			) : null }
 		</li>
@@ -185,8 +176,6 @@ const MemoizedCommentTemplatePreview = memo( CommentTemplatePreview );
  * @param {Array}  [props.activeComment]    - The block that is currently active.
  * @param {Array}  [props.setActiveComment] - The setter for activeComment.
  * @param {Array}  [props.blocks]           - Array of blocks returned from
- * @param {Object} [props.firstComment]     - The first comment in the array of
- *                                          comment objects.
  *                                          getBlocks() in parent .
  * @return {WPElement}                 		List of comments.
  */
@@ -196,7 +185,6 @@ const CommentsList = ( {
 	activeComment,
 	setActiveComment,
 	blocks,
-	firstComment,
 } ) => (
 	<ol { ...blockProps }>
 		{ comments &&
@@ -210,7 +198,6 @@ const CommentsList = ( {
 						activeComment={ activeComment }
 						setActiveComment={ setActiveComment }
 						blocks={ blocks }
-						firstComment={ firstComment }
 					/>
 				</BlockContextProvider>
 			) ) }
@@ -229,7 +216,6 @@ export default function CommentTemplateEdit( {
 } ) {
 	const blockProps = useBlockProps();
 
-	const [ activeComment, setActiveComment ] = useState();
 	const { commentOrder, threadCommentsDepth, threadComments } = useSelect(
 		( select ) => {
 			const { getSettings } = select( blockEditorStore );
@@ -270,14 +256,6 @@ export default function CommentTemplateEdit( {
 			: topLevelComments
 	);
 
-	if ( ! topLevelComments ) {
-		return (
-			<p { ...blockProps }>
-				<Spinner />
-			</p>
-		);
-	}
-
 	if ( ! postId ) {
 		commentTree = getCommentsPlaceholder( {
 			perPage,
@@ -286,6 +264,16 @@ export default function CommentTemplateEdit( {
 		} );
 	}
 
+	const [ activeComment, setActiveComment ] = useState( commentTree[ 0 ] );
+
+	if ( ! topLevelComments ) {
+		return (
+			<p { ...blockProps }>
+				<Spinner />
+			</p>
+		);
+	}
+
 	if ( ! commentTree.length ) {
 		return <p { ...blockProps }> { __( 'No results found.' ) }</p>;
 	}
@@ -297,7 +285,6 @@ export default function CommentTemplateEdit( {
 			blocks={ blocks }
 			activeComment={ activeComment }
 			setActiveComment={ setActiveComment }
-			firstComment={ commentTree[ 0 ] }
 		/>
 	);
 }

```

**Comment by ockham** [comment]
Ignore the above, it would need to update `activeComment` state once comments have actually loaded (rather than dumbly initializing it with `commentTree[ 0 ]`).

**Comment by ockham** [comment]
> Unfortunately, the problem still persists in the _Site_ Editor -- probably because we're using the "generic"/"empty" version of the Comment blocks, i.e. with no actual comments set -- and `commentId` thus being `null` for all of them.

The following seems to work (per our video call discussion). Not super-elegant, and I'm not sure the array-based pseudo-indices are the most performant thing:

```diff
diff --git a/packages/block-library/src/comment-template/edit.js b/packages/block-library/src/comment-template/edit.js
index 6f0e61adbe..e895aabb66 100644
--- a/packages/block-library/src/comment-template/edit.js
+++ b/packages/block-library/src/comment-template/edit.js
@@ -85,16 +85,15 @@ const getCommentsPlaceholder = ( {
  * @param {Array}  [props.comment]          - A comment object.
  * @param {Array}  [props.activeComment]    - The block that is currently active.
  * @param {Array}  [props.setActiveComment] - The setter for activeComment.
- * @param {Array}  [props.firstComment]     - First comment in the array.
  * @param {Array}  [props.blocks]           - Array of blocks returned from
  *                                          getBlocks() in parent .
  * @return {WPElement}                 		Inner blocks of the Comment Template
  */
 function CommentTemplateInnerBlocks( {
 	comment,
+	commentIndex,
 	activeComment,
 	setActiveComment,
-	firstComment,
 	blocks,
 } ) {
 	const { children, ...innerBlocksProps } = useInnerBlocksProps(
@@ -103,8 +102,10 @@ function CommentTemplateInnerBlocks( {
 	);
 	return (
 		<li { ...innerBlocksProps }>
-			{ comment.commentId ===
-			( activeComment?.commentId || firstComment?.commentId )
+			{ commentIndex.length === activeComment.length &&
+			commentIndex.every(
+				( value, index ) => value === activeComment[ index ]
+			)
 				? children
 				: null }
 
@@ -118,20 +119,23 @@ function CommentTemplateInnerBlocks( {
 			<MemoizedCommentTemplatePreview
 				blocks={ blocks }
 				comment={ comment }
+				commentIndex={ commentIndex }
 				setActiveComment={ setActiveComment }
 				isHidden={
-					comment.commentId ===
-					( activeComment?.commentId || firstComment?.commentId )
+					commentIndex.length === activeComment.length &&
+					commentIndex.every(
+						( value, index ) => value === activeComment[ index ]
+					)
 				}
 			/>
 
 			{ comment?.children?.length > 0 ? (
 				<CommentsList
 					comments={ comment.children }
+					commentIndex={ commentIndex }
 					activeComment={ activeComment }
 					setActiveComment={ setActiveComment }
 					blocks={ blocks }
-					firstComment={ firstComment }
 				/>
 			) : null }
 		</li>
@@ -141,6 +145,7 @@ function CommentTemplateInnerBlocks( {
 const CommentTemplatePreview = ( {
 	blocks,
 	comment,
+	commentIndex,
 	setActiveComment,
 	isHidden,
 } ) => {
@@ -149,7 +154,7 @@ const CommentTemplatePreview = ( {
 	} );
 
 	const handleOnClick = () => {
-		setActiveComment( comment );
+		setActiveComment( commentIndex );
 	};
 
 	// We have to hide the preview block if the `comment` props points to
@@ -185,18 +190,16 @@ const MemoizedCommentTemplatePreview = memo( CommentTemplatePreview );
  * @param {Array}  [props.activeComment]    - The block that is currently active.
  * @param {Array}  [props.setActiveComment] - The setter for activeComment.
  * @param {Array}  [props.blocks]           - Array of blocks returned from
- * @param {Object} [props.firstComment]     - The first comment in the array of
- *                                          comment objects.
  *                                          getBlocks() in parent .
  * @return {WPElement}                 		List of comments.
  */
 const CommentsList = ( {
 	comments,
+	commentIndex,
 	blockProps,
 	activeComment,
 	setActiveComment,
 	blocks,
-	firstComment,
 } ) => (
 	<ol { ...blockProps }>
 		{ comments &&
@@ -207,10 +210,10 @@ const CommentsList = ( {
 				>
 					<CommentTemplateInnerBlocks
 						comment={ comment }
+						commentIndex={ [ ...commentIndex, index ] }
 						activeComment={ activeComment }
 						setActiveComment={ setActiveComment }
 						blocks={ blocks }
-						firstComment={ firstComment }
 					/>
 				</BlockContextProvider>
 			) ) }
@@ -229,7 +232,7 @@ export default function CommentTemplateEdit( {
 } ) {
 	const blockProps = useBlockProps();
 
-	const [ activeComment, setActiveComment ] = useState();
+	const [ activeComment, setActiveComment ] = useState( [ 0 ] );
 	const { commentOrder, threadCommentsDepth, threadComments } = useSelect(
 		( select ) => {
 			const { getSettings } = select( blockEditorStore );
@@ -293,11 +296,11 @@ export default function CommentTemplateEdit( {
 	return (
 		<CommentsList
 			comments={ commentTree }
+			commentIndex={ [] }
 			blockProps={ blockProps }
 			blocks={ blocks }
 			activeComment={ activeComment }
 			setActiveComment={ setActiveComment }
-			firstComment={ commentTree[ 0 ] }
 		/>
 	);
 }
```

**Comment by ockham** [comment]
I don't like [my solution](https://github.com/WordPress/gutenberg/pull/39472#issuecomment-1072709320) too much.

If the alternative solution we discussed (using negative comment IDs for placeholder comments) works, I'd say let's go with that.

**Comment by ockham** [comment]
Negative comment IDs seem to work for me:

```diff
diff --git a/packages/block-library/src/comment-template/edit.js b/packages/block-library/src/comment-template/edit.js
index 6f0e61adbe..f2e2ac31a6 100644
--- a/packages/block-library/src/comment-template/edit.js
+++ b/packages/block-library/src/comment-template/edit.js
@@ -54,12 +54,12 @@ const getCommentsPlaceholder = ( {
 		perPage <= commentsDepth ? perPage : commentsDepth;
 	if ( ! threadComments || defaultCommentsToShow === 1 ) {
 		// If displaying threaded comments is disabled, we only show one comment
-		return [ { commentId: null, children: [] } ];
+		return [ { commentId: -1, children: [] } ];
 	} else if ( defaultCommentsToShow === 2 ) {
 		return [
 			{
-				commentId: null,
-				children: [ { commentId: null, children: [] } ],
+				commentId: -1,
+				children: [ { commentId: -2, children: [] } ],
 			},
 		];
 	}
@@ -67,11 +67,11 @@ const getCommentsPlaceholder = ( {
 	// In case that the value is set but larger than 3 we truncate it to 3.
 	return [
 		{
-			commentId: null,
+			commentId: -1,
 			children: [
 				{
-					commentId: null,
-					children: [ { commentId: null, children: [] } ],
+					commentId: -2,
+					children: [ { commentId: -3, children: [] } ],
 				},
 			],
 		},
```

**Comment by ockham** [comment]
BTW, we don't need to store an entire comment object in `activeComment` state (nor in the `firstComment` prop) -- the corresponding `commentId` is enough. (Unless we're going with an approach that's not `commentId` based, such as the [comment index based approach](https://github.com/WordPress/gutenberg/pull/39472#issuecomment-1072709320).)

```diff
diff --git a/packages/block-library/src/comment-template/edit.js b/packages/block-library/src/comment-template/edit.js
index 6f0e61adbe..2b7ade1b5e 100644
--- a/packages/block-library/src/comment-template/edit.js
+++ b/packages/block-library/src/comment-template/edit.js
@@ -103,8 +103,7 @@ function CommentTemplateInnerBlocks( {
 	);
 	return (
 		<li { ...innerBlocksProps }>
-			{ comment.commentId ===
-			( activeComment?.commentId || firstComment?.commentId )
+			{ comment.commentId === ( activeComment || firstComment )
 				? children
 				: null }
 
@@ -117,11 +116,10 @@ function CommentTemplateInnerBlocks( {
 			block. */ }
 			<MemoizedCommentTemplatePreview
 				blocks={ blocks }
-				comment={ comment }
+				commentId={ comment.commentId }
 				setActiveComment={ setActiveComment }
 				isHidden={
-					comment.commentId ===
-					( activeComment?.commentId || firstComment?.commentId )
+					comment.commentId === ( activeComment || firstComment )
 				}
 			/>
 
@@ -140,7 +138,7 @@ function CommentTemplateInnerBlocks( {
 
 const CommentTemplatePreview = ( {
 	blocks,
-	comment,
+	commentId,
 	setActiveComment,
 	isHidden,
 } ) => {
@@ -149,7 +147,7 @@ const CommentTemplatePreview = ( {
 	} );
 
 	const handleOnClick = () => {
-		setActiveComment( comment );
+		setActiveComment( commentId );
 	};
 
 	// We have to hide the preview block if the `comment` props points to
@@ -297,7 +295,7 @@ export default function CommentTemplateEdit( {
 			blocks={ blocks }
 			activeComment={ activeComment }
 			setActiveComment={ setActiveComment }
-			firstComment={ commentTree[ 0 ] }
+			firstComment={ commentTree[ 0 ]?.commentId }
 		/>
 	);
 }
```

(We also might wanna rename `activeComment`, `setActiveComment`, and `firstComment` to `...Id`.)

**Comment by michalczaplinski** [comment]
Awesome work @ockham . Thanks for helping out with this one :) 

> BTW, we don't need to store an entire comment object in activeComment state

You're right. Not a big difference, but would be a tiny bit more performant :) 

> (We also might wanna rename activeComment, setActiveComment, and firstComment to ...Id.)

👍 

> Negative comment IDs seem to work for me:

They work just fine for me too! I'm gonna go with this approach.

Incidentally, I have initially inserted the Comment Query Loop inside of the Post Template, in which case it does **not** actually work:

https://user-images.githubusercontent.com/5417266/159095400-9333d571-70ea-4dc1-a866-e45863397597.mov

I think that they **should** work in that context. From a UX perspective, It probably does not make a ton of sense to place the Comment Query Loop there, but they I don't see a technical reason why they should not render.

File: packages/block-library/src/comment-template/edit.js (hunk 5 above)
Comment (michalczaplinski) [reply packages/block-library/src/comment-template/edit.js]: I've also fixed this 👍

**Comment by DAreRodz** [comment]
Hey :wave: regarding the negative IDs for comment placeholders, I've noticed that comments end up being requested from the REST API. It happens when the negative ID reaches inner blocks, like in [Comment Author Avatar](https://github.com/WordPress/gutenberg/blob/8aeeac2641451b4ed8fbda92769ae61d20b6ddf9/packages/block-library/src/comment-author-avatar/edit.js#L23-L28).

Screenshot 2022-03-21 at 13 42 11

Is there something we can do to prevent that? 🤔

**Comment by DAreRodz** [comment]
BTW, I was testing it and, apart from what I mentioned above and the [selection issue](https://github.com/WordPress/gutenberg/issues/39510) (which this PR would partially fix), everything seems to work fine.

Even what you said @michalczaplinski of including the Comment Query Loop inside the Post Template works for me. Maybe the post you show in the video doesn't have any comment? 🤔 

Anyway, good work here, everyone! 🙌

**Comment by ockham** [comment]
> Hey 👋 regarding the negative IDs for comment placeholders, I've noticed that comments end up being requested from the REST API. It happens when the negative ID reaches inner blocks, like in [Comment Author Avatar](https://github.com/WordPress/gutenberg/blob/8aeeac2641451b4ed8fbda92769ae61d20b6ddf9/packages/block-library/src/comment-author-avatar/edit.js#L23-L28).
> 
> Screenshot 2022-03-21 at 13 42 11
> 
> Is there something we can do to prevent that? 🤔

Ah, good spot, @DAreRodz! Yeah, definitely something we need to prevent 😕 

We might have to go back to the [index-based approach](https://github.com/WordPress/gutenberg/pull/39472#issuecomment-1072709320) after all. We can probably make it more efficient by using a different way of building the nested index (instead of using arrays of indices).

**Comment by ockham** [comment]
> We might have to go back to the [index-based approach](https://github.com/WordPress/gutenberg/pull/39472#issuecomment-1072709320) after all. We can probably make it more efficient by using a different way of building the nested index (instead of using arrays of indices).

The alternative would probably be to check if a comment's `commentId` is negative [around here](https://github.com/WordPress/gutenberg/pull/39472/files#diff-885985bee90d7d51f079b99d59d8562cba40b4a6f64258e86fc81b0dc0f11b87R212) before using it as context for the nested blocks, and if so, setting it to `null` 🤔

**Comment by ockham** [comment]
> > We might have to go back to the [index-based approach](https://github.com/WordPress/gutenberg/pull/39472#issuecomment-1072709320) after all. We can probably make it more efficient by using a different way of building the nested index (instead of using arrays of indices).
> 
> The alternative would probably be to check if a comment's `commentId` is negative [around here](https://github.com/WordPress/gutenberg/pull/39472/files#diff-885985bee90d7d51f079b99d59d8562cba40b4a6f64258e86fc81b0dc0f11b87R212) before using it as context for the nested blocks, and if so, setting it to `null` 🤔

This seems to work:

```diff
diff --git a/packages/block-library/src/comment-template/edit.js b/packages/block-library/src/comment-template/edit.js
index 3833cc82d9..1b693438ce 100644
--- a/packages/block-library/src/comment-template/edit.js
+++ b/packages/block-library/src/comment-template/edit.js
@@ -203,20 +203,26 @@ const CommentsList = ( {
 } ) => (
 	<ol { ...blockProps }>
 		{ comments &&
-			comments.map( ( comment, index ) => (
-				<BlockContextProvider
-					key={ comment.commentId || index }
-					value={ comment }
-				>
-					<CommentTemplateInnerBlocks
-						comment={ comment }
-						activeCommentId={ activeCommentId }
-						setActiveCommentId={ setActiveCommentId }
-						blocks={ blocks }
-						firstCommentId={ firstCommentId }
-					/>
-				</BlockContextProvider>
-			) ) }
+			comments.map( ( { commentId, ...commentFields }, index ) => {
+				const comment = {
+					commentId: commentId < 0 ? null : commentId,
+					...commentFields,
+				};
+				return (
+					<BlockContextProvider
+						key={ comment.commentId || index }
+						value={ comment }
+					>
+						<CommentTemplateInnerBlocks
+							comment={ { commentId, ...commentFields } }
+							activeCommentId={ activeCommentId }
+							setActiveCommentId={ setActiveCommentId }
+							blocks={ blocks }
+							firstCommentId={ firstCommentId }
+						/>
+					</BlockContextProvider>
+				);
+			} ) }
 	</ol>
 );

```

It's potentially confusing though, since it still needs to pass through the unchanged `commentId` to `CommentTemplateInnerBlocks` (in order for the editor to discern between blocks)... 😕

**Comment by DAreRodz** [comment]
> It's potentially confusing though, since it still needs to pass through the unchanged `commentId` to `CommentTemplateInnerBlocks` (in order for the editor to discern between blocks)... 😕

Perhaps the only place where `commentId` should be changed is here (the `value` prop). That's the actual context inner blocks receive.

https://github.com/WordPress/gutenberg/blob/704d0badb54ef96bec41365f0a462ceeffd0225e/packages/block-library/src/comment-template/edit.js#L207-L211

It could be replaced by something like you shared above. 🙂 

```jsx
value={ {
	commentId: comment.commentId < 0 ? null : comment.commentId,
} }

**Comment by ockham** [comment]
Thanks @DAreRodz, good point!

BTW, do we even need to pass an entire `comment` object as `value` to the `BlockContextProvider`? Most Comment child blocks specify `"usesContext": [ "commentId" ]`, so maybe the `commentId` alone would be enough? 🤔 

(I'm not totally sure where the `commentId` is extracted from the `comment` context value, would you know where that happens?)

**Edit:** Ah, I think that's what you were basically saying with

```js
value={ {
	commentId: comment.commentId < 0 ? null : comment.commentId,
} }
```

😅

**Comment by ockham** [comment]
Updated patch based on the above:

```diff
diff --git a/packages/block-library/src/comment-template/edit.js b/packages/block-library/src/comment-template/edit.js
index 3833cc82d9..14a18c866f 100644
--- a/packages/block-library/src/comment-template/edit.js
+++ b/packages/block-library/src/comment-template/edit.js
@@ -203,13 +203,15 @@ const CommentsList = ( {
 } ) => (
 	<ol { ...blockProps }>
 		{ comments &&
-			comments.map( ( comment, index ) => (
+			comments.map( ( { commentId, ...comment }, index ) => (
 				<BlockContextProvider
-					key={ comment.commentId || index }
-					value={ comment }
+					key={ commentId || index }
+					value={ {
+						commentId: commentId < 0 ? null : commentId,
+					} }
 				>
 					<CommentTemplateInnerBlocks
-						comment={ comment }
+						comment={ { commentId, ...comment } }
 						activeCommentId={ activeCommentId }
 						setActiveCommentId={ setActiveCommentId }
 						blocks={ blocks }
```

**Comment by ockham** [comment]
And, for good measure, here's an alternative approach based on the comment index idea -- using strings instead of arrays, i.e. the index for a nested comment would look like this: `'1-4-2'` rather than `[1, 4, 2]` (i.e. choose the child comment at index one of the root; choose that comment's child comment at index 4; choose that's comment child comment at index 2. Or, in other words: The 3rd child of the 5th child of the 2nd child of the root). In this notation, the `firstComment` is simply `'0'` (first child of the root). This makes index comparison much easier.

(Diff requires reverting the last 3 commits per this writing)

```diff
diff --git a/packages/block-library/src/comment-template/edit.js b/packages/block-library/src/comment-template/edit.js
index 6f0e61adbe..adec7cdd0b 100644
--- a/packages/block-library/src/comment-template/edit.js
+++ b/packages/block-library/src/comment-template/edit.js
@@ -85,16 +85,15 @@ const getCommentsPlaceholder = ( {
  * @param {Array}  [props.comment]          - A comment object.
  * @param {Array}  [props.activeComment]    - The block that is currently active.
  * @param {Array}  [props.setActiveComment] - The setter for activeComment.
- * @param {Array}  [props.firstComment]     - First comment in the array.
  * @param {Array}  [props.blocks]           - Array of blocks returned from
  *                                          getBlocks() in parent .
  * @return {WPElement}                 		Inner blocks of the Comment Template
  */
 function CommentTemplateInnerBlocks( {
 	comment,
+	commentIndex,
 	activeComment,
 	setActiveComment,
-	firstComment,
 	blocks,
 } ) {
 	const { children, ...innerBlocksProps } = useInnerBlocksProps(
@@ -103,10 +102,7 @@ function CommentTemplateInnerBlocks( {
 	);
 	return (
 		<li { ...innerBlocksProps }>
-			{ comment.commentId ===
-			( activeComment?.commentId || firstComment?.commentId )
-				? children
-				: null }
+			{ commentIndex === activeComment ? children : null }
 
 			{ /* To avoid flicker when switching active block contexts, a preview
 			is ALWAYS rendered and the preview for the active block is hidden.
@@ -118,20 +114,18 @@ function CommentTemplateInnerBlocks( {
 			<MemoizedCommentTemplatePreview
 				blocks={ blocks }
 				comment={ comment }
+				commentIndex={ commentIndex }
 				setActiveComment={ setActiveComment }
-				isHidden={
-					comment.commentId ===
-					( activeComment?.commentId || firstComment?.commentId )
-				}
+				isHidden={ commentIndex === activeComment }
 			/>
 
 			{ comment?.children?.length > 0 ? (
 				<CommentsList
 					comments={ comment.children }
+					commentIndex={ commentIndex }
 					activeComment={ activeComment }
 					setActiveComment={ setActiveComment }
 					blocks={ blocks }
-					firstComment={ firstComment }
 				/>
 			) : null }
 		</li>
@@ -141,6 +135,7 @@ function CommentTemplateInnerBlocks( {
 const CommentTemplatePreview = ( {
 	blocks,
 	comment,
+	commentIndex,
 	setActiveComment,
 	isHidden,
 } ) => {
@@ -149,7 +144,7 @@ const CommentTemplatePreview = ( {
 	} );
 
 	const handleOnClick = () => {
-		setActiveComment( comment );
+		setActiveComment( commentIndex );
 	};
 
 	// We have to hide the preview block if the `comment` props points to
@@ -185,18 +180,16 @@ const MemoizedCommentTemplatePreview = memo( CommentTemplatePreview );
  * @param {Array}  [props.activeComment]    - The block that is currently active.
  * @param {Array}  [props.setActiveComment] - The setter for activeComment.
  * @param {Array}  [props.blocks]           - Array of blocks returned from
- * @param {Object} [props.firstComment]     - The first comment in the array of
- *                                          comment objects.
  *                                          getBlocks() in parent .
  * @return {WPElement}                 		List of comments.
  */
 const CommentsList = ( {
 	comments,
+	commentIndex,
 	blockProps,
 	activeComment,
 	setActiveComment,
 	blocks,
-	firstComment,
 } ) => (
 	<ol { ...blockProps }>
 		{ comments &&
@@ -207,10 +200,10 @@ const CommentsList = ( {
 				>
 					<CommentTemplateInnerBlocks
 						comment={ comment }
+						commentIndex={ `${ commentIndex }-${ index }` }
 						activeComment={ activeComment }
 						setActiveComment={ setActiveComment }
 						blocks={ blocks }
-						firstComment={ firstComment }
 					/>
 				</BlockContextProvider>
 			) ) }
@@ -229,7 +222,7 @@ export default function CommentTemplateEdit( {
 } ) {
 	const blockProps = useBlockProps();
 
-	const [ activeComment, setActiveComment ] = useState();
+	const [ activeComment, setActiveComment ] = useState( '0' );
 	const { commentOrder, threadCommentsDepth, threadComments } = useSelect(
 		( select ) => {
 			const { getSettings } = select( blockEditorStore );
@@ -293,11 +286,11 @@ export default function CommentTemplateEdit( {
 	return (
 		<CommentsList
 			comments={ commentTree }
+			commentIndex={ '' }
 			blockProps={ blockProps }
 			blocks={ blocks }
 			activeComment={ activeComment }
 			setActiveComment={ setActiveComment }
-			firstComment={ commentTree[ 0 ] }
 		/>
 	);
 }

```

**Comment by michalczaplinski** [comment]
Thanks for your vigilance @DAreRodz and @ockham ! 😃 

> I've noticed that comments end up being requested from the REST API. It happens when the negative ID reaches inner blocks, like in Comment Author Avatar.

Ohh, yeah that was an issue before and another reason why we didn't use the negative indices! 🤦 I should have remembered that!

> Even what you said @michalczaplinski of including the Comment Query Loop inside the Post Template works for me. Maybe the post you show in the video doesn't have any comment? 🤔

That's it 🙂 . I thought that the posts had comments!

> here's an alternative approach based on the comment index idea

I don't really have a strong preference but I went with the original idea from @DAreRodz to add the `commentId: commentId < 0 ? null : commentId,`. Mostly because this way there is only 1 place in the code where there is placeholder-specific behaviour and I can leave a comment there.

File: packages/block-library/src/comment-template/edit.js [hunk 6]
```diff
@@ -81,29 +86,32 @@ const getCommentsPlaceholder = ( {
...
- * @param {Array}  [props.activeComment]    - The block that is currently active.
- * @param {Array}  [props.setActiveComment] - The setter for activeComment.
- * @param {Array}  [props.firstComment]     - First comment in the array.
- * @param {Array}  [props.blocks]           - Array of blocks returned from
- *                                          getBlocks() in parent .
+ * @param {Object} props                      Component props.
+ * @param {Array}  [props.comment]            - A comment object.
+ * @param {Array}  [props.activeCommentId]    - The ID of the comment that is currently active.
+ * @param {Array}  [props.setActiveCommentId] - The setter for activeCommentId.
+ * @param {Array}  [props.firstCommentId]     - First ID of the first comment in the array.
```
Comment (ockham) [inline packages/block-library/src/comment-template/edit.js]:
```suggestion
 * @param {Array}  [props.firstCommentId]     - ID of the first comment in the array.
```

File: packages/block-library/src/comment-template/edit.js [hunk 7]
```diff
@@ -172,35 +183,44 @@ const MemoizedCommentTemplatePreview = memo( CommentTemplatePreview );
...
+			comments.map( ( { commentId, ...comment }, index ) => (
 				<BlockContextProvider
 					key={ comment.commentId || index }
-					value={ comment }
+					value={ {
+						// If the commentId is negative it means that this comment is a
+						// "placeholder" and that the block is most likely being used in the
+						// site editor. In this case, we have to set the commentId to `null`
+						// because otherwise the (non-existent) comment with a negative ID
+						// would be reqested from the REST API.
```
Comment (ockham) [inline packages/block-library/src/comment-template/edit.js:214]: 👍

**Review by ockham — APPROVED** [review]
Thanks a lot for working on this (and bearing with me 😅 )!

LGTM. In case there are some more glitches -- such as the one you described when inserting the Comments Query Loop inside a Post Template -- we can address them separately 😄
