### PR TITLE
Notes: Fix 'View notes' on mobile screens

### LINKED ISSUE #72531: Block notes: "View notes" on mobile does nothing
Steps to reproduce: open a document with notes on mobile. Select a block that has notes, and click the "View notes" in the toolbar:

Image

Result: it doesn't do anything in my testing. I would expect it to open the block note sidebar.

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
This is a follow-up to #71834.
Closes #72531.

PR fixes "View notes" and "Add note" block toolbar/option items when editor is rendered in smaller viewports.

## Why?
Floating notes are disabled on smaller screens since they're not dismissible and prevent content editing. 

## Testing Instructions
1. Open a post.
2. Add a block and note.
3. Resize the screen to the mobile viewport.
4. Click the "View note" block toolbar item.
5. Confirm that the Notes pinned sidebar is opened and the note selected.

### Testing Instructions for Keyboard
Same.

## Screenshots or screencast 

https://github.com/user-attachments/assets/5b990f7d-c17e-451f-a244-82b4627321b3

### CODE REVIEW

File: packages/editor/src/components/collab-sidebar/index.js [hunk 1]
```diff
@@ -117,7 +117,8 @@ export default function CollabSidebar() {
 		commentLastUpdated,
 	} = useBlockComments( postId );
 	useEnableFloatingSidebar(
-		unresolvedSortedThreads.length > 0 || showCommentBoard
+		isLargeViewport &&
+			( unresolvedSortedThreads.length > 0 || showCommentBoard )
```
Comment (Mamaduka) [inline packages/editor/src/components/collab-sidebar/index.js:121]: There's no point in enabling the `useEnableFloatingSidebar` hook logic on smaller screens.

**Review by t-hamano — APPROVED** [review]
LGTM 👍

**Comment by Mamaduka** [comment]
Thanks for the review, @t-hamano!

**Comment by talldan** [comment]
I've cherry-picked this manually onto the `wp/6.9` branch.

**Comment by jasmussen** [comment]
Thanks for this!
