### PR TITLE
Fix duotone render in non-fse themes

### LINKED ISSUE #37598: Duotone filter does not work on front end for non FSE themes as of 12.1.0
### Description

As the title says, the Duotone filter does not work (display) on front end for non FSE themes as of 12.1.0, which now includes 12.2.0. In the backend (Editor), the duotone filters work fine.

Deactivating the Gutenberg plugin, the duotone works fine for ALL themes.

### Step-by-step reproduction instructions

1. Install and activate Gut. 12.1.x or 12.2.0
2. Create a duotone for an image or on a Background image of the Cover block.
3. Make sure you are using a non FSE theme.
3. Notice that the duotone is working in the Editor.
4. On the front end the duotone is not showing up, you just get the original image without the filter.
5. To fix the issue, EITHER replace the activated theme with a FSE theme, or deactivate the Gutenberg plugin.

NOTE: I did not check with the latest (beta 3) version of WP 5.9 (but I'm guessing the issue will be there too)...

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WP 5.8.2, Gutenberg 12.2.0, Xampp with PHP 7.4.x, on a Windows 7 PRO, or Windows 10 Home editions, Chrome browser.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ajlende**
## Description

Fixes #37598 

It seems that the `render_block` filter is being called after the `wp_body_open` hook in non-fse themes, so this change will fall back on `wp_footer` if it has already been called.

We switched from `wp_footer` to `wp_body_open` in #36754 because Safari renders blocks incorrectly when the SVG filter comes after the content that it is filtering. Switching back unfortunately means that duotone rendering will be incorrect for non-fse themes when viewed from Safari.

## How has this been tested?

1. Activate a non-fse theme like Blank Canvas.
2. In a post, add an image with a duotone filter.
3. Publish and view the post to see the filter applied.

## Screenshots 

Using the Blank Canvas theme using the one of the default duotone filters applied to the block

Before:
image does not render at all

After:
duotone filter is correctly applied to the image

## Types of changes

Bug Fix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by youknowriad** [comment]
Is there a way to force a repaint in safari (since it seems that fixes the issue according to the link PR)

**Comment by ajlende** [comment]
> Is there a way to force a repaint in safari (since it seems that fixes the issue according to the link PR)

It's going to get messy if we do. We'd have to do a user agent check and add a script for each duotone filter to hide and show the filtered content in Safari according to a [blog post](https://martinwolf.org/before-2018/blog/2014/06/force-repaint-of-an-element-with-javascript/) that I found.

**Comment by youknowriad** [comment]
My main concern with `wp_body_open` is that we're creating inconsistencies between the different ways we render server side styles. Layout block support use `wp_footer` right now and ideally we could share code between all these server side styles to enqueue the styles in the exact same way.

Anyway, my comments shouldn't block you here but as part of the discussion here #37495 I think ultimately enqueue this kind of styles should be consistent.

**Comment by ajlende** [comment]
@youknowriad, I gave the repaint a go in Safari. It's a little messy, and I sometimes see the images flash, but it seems to work.

> ideally we could share code between all these server side styles to enqueue the styles in the exact same way.

It would be nice to have a better system for adding things like this—I keep thinking about other SVG filter opportunities because there's a lot of things that they can do, but it's kind of clunky to add them right now.

File: lib/block-supports/duotone.php [hunk 1]
```diff
@@ -459,20 +459,30 @@ function gutenberg_render_duotone_support( $block_content, $block ) {
...
-	// Render any custom filter the user may have added.
 	add_action(
-		// There are a couple of known rendering quirks in Safari.
-		// 1. Filters won't render at all when the SVG is in the head of
-		// the document.
-		// 2. Filters display incorrectly when the SVG is defined after
-		// where the filter is used in the document, so the footer does
-		// not work.
-		'wp_body_open',
+		is_admin() ? 'admin_footer' : 'wp_footer',
```
Comment (youknowriad) [inline lib/block-supports/duotone.php]: Why the check for `is_admin`. Isn't this filter only needed in the frontend?

File: lib/block-supports/duotone.php [hunk 2]
```diff
@@ -459,20 +459,30 @@ function gutenberg_render_duotone_support( $block_content, $block ) {
...
+	// filter comes after the content that it is filtering, so we force
+	// a repaint by resetting the display style which solves the issue.
+	global $is_safari;
+	if ( $is_safari ) {
+		wp_register_script( $filter_id, false, array(), null, true );
+		wp_enqueue_script( $filter_id );
+		wp_add_inline_script(
+			$filter_id,
+			sprintf(
+				'( function() { var el = document.querySelector( %s ); var display = el.style.display; el.style.display = "none"; setTimeout( function() { el.style.display = display; } ); } )();',
```
Comment (youknowriad) [inline lib/block-supports/duotone.php]: Is the setTimeout necessary here?

File: lib/block-supports/duotone.php [hunk 3]
```diff
@@ -459,20 +459,30 @@ function gutenberg_render_duotone_support( $block_content, $block ) {
...
-		// There are a couple of known rendering quirks in Safari.
-		// 1. Filters won't render at all when the SVG is in the head of
-		// the document.
-		// 2. Filters display incorrectly when the SVG is defined after
-		// where the filter is used in the document, so the footer does
-		// not work.
-		'wp_body_open',
+		is_admin() ? 'admin_footer' : 'wp_footer',
 		function () use ( $filter_svg ) {
 			echo $filter_svg;
```
Comment (youknowriad) [inline lib/block-supports/duotone.php:465]: Can't we just render a `<script>` here instead of using a separate mechanism (wp_add_inline_script) which might not trigger the script at the right moment.

Comment (youknowriad) [reply lib/block-supports/duotone.php:465]: (I'm hoping this and the removal of setTimeout could solve the flashes)

File: lib/block-supports/duotone.php (hunk 2 above)
Comment (ajlende) [reply lib/block-supports/duotone.php]: Simply setting and resetting the display property doesn't do anything. We're not dealing with layout like the blog post I shared. And all other "repaint this element" tricks I found used `setTimeout`. So I assumed it was necessary. However, it seems the `offsetHeight` trick works fine to flush the style changes without `setTimeout`.

I dug into the WebKit source to get to the bottom of why this works. I found that some of the element accessors, including [`Element::offsetHeight`](https://github.com/WebKit/WebKit/blob/4121ca9891ada0a3deaba8ee70e3a575407f508d/Source/WebCore/dom/Element.cpp#L1296-L1304), call [`Document::updateLayoutIgnorePendingStylesheets`](https://github.com/WebKit/WebKit/blob/4121ca9891ada0a3deaba8ee70e3a575407f508d/Source/WebCore/dom/Document.cpp#L2237-L2254) which, not only does a reflow, but also immediately recalculates styles with [`Document::updateStyleIfNeeded`](https://github.com/WebKit/WebKit/blob/4121ca9891ada0a3deaba8ee70e3a575407f508d/Source/WebCore/dom/Document.cpp#L2185-L2200). I couldn't find any other easy ways to flush the style changes without reflow, but I don't see a flash anymore with the `offsetHeight` trick, at least on my MacBook Pro M1 Max. 🤷

File: lib/block-supports/duotone.php (hunk 1 above)
Comment (ajlende) [reply lib/block-supports/duotone.php]: That was how it was prior to `wp_body_open`, but you're right, the filter is only needed for the frontend now.

File: lib/block-supports/duotone.php (hunk 3 above)
Comment (ajlende) [reply lib/block-supports/duotone.php:465]: I moved it for now. All of the floating nameless script and style tags in the body are beginning to feel a bit messy for me. Hopefully that's something that the system for loading this stuff could solve. Or maybe it'll eventually bother me enough to swing back around for a follow-up PR to clean it up a bit.

**Review by youknowriad — APPROVED** [review]
This seems like the best fix I can think of. Thanks

**Comment by noisysocks** [comment]
I can't backport this PR as it depends on https://github.com/WordPress/gutenberg/pull/36236 which was not backported into 5.9. Ordinarily I would backport both PRs but https://github.com/WordPress/gutenberg/pull/36236 contains quite a bit of new PHP code and we are very late into the RC period.

I've put the Backport to WP Minor Release on both PRs so that both fixes are included in 5.9.1 which should follow 5.9 very quickly.
