### PR TITLE
Fixed issue of background min height

### LINKED ISSUE #41660: Cover block HTML error using featured image, fixed background, minimum height
### Description

When a cover block uses the featured image, is set to fixed background, and has a minimum height, the minimum height is ignored because the block is generating invalid HTML.

In this scenario, the front end `<div class="wp-block-cover">` tag contains two `style` attributes. This is because the editor inserts `style="min-height:nnnpx"` with “Minimum height of cover”, and the **cover.php** file is inserting a second one, containing `style="background-image:url(https://example.com/image.jpg)"` with the `preg_replace()` call in lines 46-51. That `preg_replace()` call erroneously assumes there's not already a `style` attribute in the HTML tag.

This could be fixed either with a much more complex regular expression, or by adding a conditional that first checks for the presence of `style="` in the string and then two different regular expressions.

### Step-by-step reproduction instructions

1. Create a Cover block.
2. Set the block to “Use featured image”.
3. Turn on “Fixed background” under “Media settings”.
4. Set a “Minimum height of cover” under “Dimensions”.
5. View the front end page.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WordPress 6.0. Not using Gutenberg plugin, but I've verified this code is unchanged in the latest release version of the plugin.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by akasunil**
When a cover block uses the featured image as background image, Fixed background toggle is ON in media settings, and Minimum height of cover in back-end, Min height is getting ignored in front-end. 
## What?
Fixed [41660](https://github.com/WordPress/gutenberg/issues/41660)
 
## Testing Instructions
Please include step by step instructions on how to test this PR.

1. Create a Cover block.
2. Set the block to “Use featured image”.
3. Turn on “Fixed background” under “Media settings”.
4. Set a “Minimum height of cover” under “Dimensions”.
5. View the front end page.

## Screenshots 
CleanShot 2022-06-13 at 20 14 09@2x
or screencast

### CODE REVIEW

**Comment by akasunil** [comment]
Can you please review the PR. @ciampo @Mamaduka

**Comment by Mamaduka** [comment]
Thanks for the ping, @sunil25393. I'm adding this to my to-do list.

File: packages/block-library/src/cover/index.php [hunk 1]
```diff
@@ -43,12 +43,18 @@ function render_block_core_cover( $attributes, $content ) {
 			update_post_thumbnail_cache();
 		}
 		$current_featured_image = get_the_post_thumbnail_url();
-		$content                = preg_replace(
-			'/class=\".*?\"/',
-			'${0} style="background-image:url(' . esc_url( $current_featured_image ) . ')"',
```
Comment (Mamaduka) [inline packages/block-library/src/cover/index.php:48]: @sunil25393, can we use the `minHeight` attribute directly and avoid using the `DOMDocument`? See this comment for more details - https://github.com/WordPress/gutenberg/pull/28791#issuecomment-825819648.

Comment (akasunil) [reply packages/block-library/src/cover/index.php:48]: I have updated code.

File: packages/block-library/src/cover/index.php [hunk 2]
```diff
@@ -43,9 +43,19 @@ function render_block_core_cover( $attributes, $content ) {
 			update_post_thumbnail_cache();
 		}
 		$current_featured_image = get_the_post_thumbnail_url();
-		$content                = preg_replace(
+
+		$styles = 'background-image:url(' . esc_url( $current_featured_image ) . '); ';
+
+		if ( isset( $attributes['minHeight'] ) ) {
+			$height_unit = $attributes['minHeightUnit'] ?? 'px';
+			$height		 = " min-height:{$attributes['minHeight']}{$height_unit}";
```
Comment (Mamaduka) [inline packages/block-library/src/cover/index.php]: Can't use the null coalescing operator. The minimum required PHP version for WP is still 5.6.

P.S. I think this will fail coding standard tests. Try running `composer lint packages/block-library/src/cover/index.php` in the project directory.

File: packages/block-library/src/cover/index.php (hunk 1 above)
Comment (Mamaduka) [reply packages/block-library/src/cover/index.php:48]: Thanks, @sunil25393.

I left another comment and will try to do a final review tomorrow.

**Comment by ciampo** [comment]
Hey @sunil25393 , thank you for the ping and for working on this bug fix!

I'm not the most suited person to review changes to this part of the repository, but you're going to be in good hands with @Mamaduka's review!

File: packages/block-library/src/cover/index.php (hunk 2 above)
Comment (aristath) [inline packages/block-library/src/cover/index.php]: 2 things here: The null-coalescing operator that @Mamaduka mentioned above, and alignment of the `=` signs 👍 

```suggestion
			$height_unit = empty( $attributes['minHeightUnit'] ) ? 'px' : $attributes['minHeightUnit'];
			$height      = " min-height:{$attributes['minHeight']}{$height_unit}";
```

Comment (akasunil) [reply packages/block-library/src/cover/index.php]: I have updated the code.

**Review by Mamaduka — APPROVED** [review]
This looks good to me. Thanks, @sunil25393.

**Review by aristath — APPROVED** [review]
