### PR TITLE
`useDisabled` hook: Fix problem with not working in iframe

### LINKED ISSUE #47293: Randomly duplicating design tools
### Description

When selecting different blocks in the Site Editor using Gutenberg 15.0 (and all experiments turned off), I found by clicking more than once on a block, I can make the design tools duplicate in the sidebar. From what I can tell, I think it's happening when you click on a block of one type (featured image) and then click on another of the same block (featured image) but I'm not quite sure.  cc @ndiego in case you have time to help test. Trying to share this ASAP to get more eyes.

### Step-by-step reproduction instructions

1. Use Gutenberg 15.0. 
2. Open the Site Editor under Appearance > Editor.
3. Click on a featured image block in a query loop with the block settings open.
4. Click on a different featured image block in the query loop. Notice design tools randomly double. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/213501873-c6e8c825-a4b5-4da4-977f-5fe593bd5b3d.mov

### Environment info

- WP 6.1.1
- GB 15.0
- TT3
- MacOS
- Chrome Version 108.0.5359.124 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes: #47293
More fundamental solution than #47331

## What?
This PR solves the problem of the `useDisabled` hook not working on iframes and ensures that the `inert` attribute is properly applied to the child element.

As a result, the issue reported in #47293, where tools are duplicated, will be fixed.

## Why?
The `useDisabled` hook grants the inert attribute if its child element is a instance of `HTMLElement`. However, as far as I know,  `instanceof HTMLElement` is implicitly treated as a `window.HTMLElement`, so it does not meet this condition in an iframe.
As a result, within the iframe, this hook does not grant the `inert` attribute.

As you can see in the video below, in the classic theme, the post editor is not an iframe, so the inert attribute is given and the issue reported in #47293 does not occur. However, in the case of the block theme, because it is an iframe, the inert attribute is not given and the problem occurs:

https://user-images.githubusercontent.com/54422211/214849737-d131a724-595b-480d-982f-e2d3f5834a3d.mp4

## How?
Refer to `defaultView` to check instances relative to the `defaultView`.

More fundamentally, as pointed out in [this comment](https://github.com/WordPress/gutenberg/pull/47331#issuecomment-1403131645), the problem might be that the clientId is shared within the hoge block.
This issue may need to be investigated separately.

## Testing Instructions

- Activate Thwenty Twenty Three theme.
- Open the site editor.
- Open the Home template containing the query loop block.
- Click on various locations in the query loop to confirm that the problem reported in #47293 does not occur.
- Paste this query loop into the content of the post editor.
- Similarly, confirm that no problems occur.

### CODE REVIEW

File: packages/compose/src/hooks/use-disabled/index.ts [hunk 1]
```diff
@@ -39,11 +39,16 @@ export default function useDisabled( {
 				return;
 			}
 
+			const defaultView = node?.ownerDocument?.defaultView;
```
Comment (youknowriad) [inline packages/compose/src/hooks/use-disabled/index.ts:42]: Could this ever be falsy?

**Review by youknowriad — APPROVED** [review]

File: packages/compose/src/hooks/use-disabled/index.ts (hunk 1 above)
Comment (t-hamano) [reply packages/compose/src/hooks/use-disabled/index.ts:42]: I don't know in practical cases, but TypeScript will output errors if this check is not present.

falsy
