### PR TITLE
Widgets editor: Fix error when saving empty Legacy Widget block

### LINKED ISSUE #28561: When an empty legacy widget is added the widget area can't be saved
## Steps to reproduce:

- have the current master of Gutenberg
- have a default WordPress install with no extra plugins
- go to Appearance -> Widgets
- at the end of a widget area add a legacy widget block
  - the legacy widget block should say there are no available widgets
- save the page
- see the error

## Screenshots

https://user-images.githubusercontent.com/107534/106173222-60b1f580-619c-11eb-98e9-2e95a2f28553.mp4

### PR DESCRIPTION
**Pull request by noisysocks**
## Description

Fixes https://github.com/WordPress/gutenberg/issues/28561.

Changes the Widgets editor to store an empty Legacy Widget block as a block widget instead of as a non-block widget. By definition one cannot convert an empty Legacy Widget block to a non-block widget as you cannot have a widget without a widget type.

Similar logic already exists in the Customizer. Unfortunately we can't really reuse logic because the Customizer and the REST API represent widgets in a different way.

## How has this been tested?

Follow steps in https://github.com/WordPress/gutenberg/issues/28561.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/edit-widgets/src/store/transformers.js [hunk 1]
```diff
@@ -56,13 +60,6 @@ export function transformBlockToWidget( block, relatedWidget = {} ) {
 		};
 	}
 
-	// Delete deprecated properties.
-	delete widget.description;
-	delete widget.name;
-	delete widget.number;
-	delete widget.settings;
-	delete widget.widget_class;
```
Comment (noisysocks) [inline packages/edit-widgets/src/store/transformers.js:64]: I missed these in https://github.com/WordPress/gutenberg/pull/30853 🙂

**Review by kevin940726 — APPROVED** [review]
Tested it and it works as expected 👍
