### PR TITLE
Comments Pagination: Fix warning returned by comments pagination blocks

### LINKED ISSUE #65424: Undefined array key "paged" in comments-pagination-previous.php
### Description

I encountered the following error while working on https://github.com/WordPress/gutenberg/pull/64067 (the problem itself is unrelated to that PR).

```
( ! ) Warning: Undefined array key "paged" in /Users/czapla/Projects/gutenberg/build/block-library/blocks/comments-pagination-previous.php on line 33
```

This issue is likely related to the recent changes in this PR: [#63698](https://github.com/WordPress/gutenberg/pull/63698).

It appears that the `paged` property of the `$comment_vars` can be undefined because it's not always included in the output of `build_comment_query_vars_from_block()` : 

https://github.com/WordPress/wordpress-develop/blob/4dafd584c91524f0cfd743f728d5f334df761e11/src/wp-includes/blocks.php#L2553-L2572

### Step-by-step reproduction instructions

The issue appears on any post/page the contains the `comments pagination previous/next` block.

### PR DESCRIPTION
**Pull request by SantosGuillamot**
## What?
Fixes https://github.com/WordPress/gutenberg/issues/65424

## Why?
It shouldn't return a warning in that scenario.

## How?
I added a safety check to return null when `$comment_vars['paged']` is not defined.

I couldn't adapt the e2e tests because the testing instance has `WP_DEBUG` set to false and doesn't show warnings.

## Testing Instructions
1. Go to Settings->Discussion and check you have "Break comments into pages with **2** top level comments per page and the **last** page displayed by default.
2. Go to a post with NO comments and add the comments block.
3. Go to the frontend and check that the warning is not there anymore.

### CODE REVIEW

File: packages/block-library/src/comments-pagination-next/index.php [hunk 1]
```diff
@@ -37,7 +37,7 @@ function render_block_core_comments_pagination_next( $attributes, $content, $blo
 		$label .= $pagination_arrow;
 	}
 
-	$next_comments_link = get_next_comments_link( $label, $max_page, $comment_vars['paged'] );
+	$next_comments_link = get_next_comments_link( $label, $max_page, $comment_vars['paged'] ?? null );
```
Comment (gziolo) [inline packages/block-library/src/comments-pagination-next/index.php:40]: Finally, we can use PHP 7 features everywhere. How nice!

**Review by gziolo — APPROVED** [review]
