### PR TITLE
Fix: Alt and caption text written on images while the image was temporary is deleted.

### LINKED ISSUE #12202: Alt text entered during image upload is lost when image finishes uploading
**Describe the bug**

When uploading an image and alt text is entered during the image upload it is completely lost when the upload completes

**To Reproduce**
Steps to reproduce the behavior you'll need a big image or slow down your chrome network settings:
1. Go to http://localhost:8888/wp-admin/post.php 
2. Click on insert image block
3. Add a large image or small image on slow connection
4. As image is uploading add alt text

**Expected behavior**

Alt text is retained when image is uploaded
If this isn't possible disable alt field when image is uploading to prevent data loss
Current behaviour is that alt text is lost - non retrievable
Also, image dimensions sometimes are lost - not sure why

**Screenshots**

upload alt text

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 70,9

**Additional context**

Found converting WordPress.com e2e tests to use Gutenberg

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Fixes: https://github.com/WordPress/gutenberg/issues/12202, https://github.com/WordPress/gutenberg/issues/16746

Currently, the image alt text written while the image is temporary (points to a blob URL) is deleted as soon as the upload finishes.

This PR fixes the problem.
Alt attribute is not set when the upload is complete if the current image is temporary and an alt already exists.

## How has this been tested?
(to make the upload slow I used chrome dev tools network throttling) 
I added an image block, I pressed the upload button, while the image is uploading I wrote some alt text. I verified that the al text was persisted when the upload finished.
I repeated the same test but instead of adding an image block I drag&dropped an image directly to the editor.
I added an image I wrote some alt text. I drag & dropped another image to replace the current image, I waited for the upload to complete and I verified the alt text was removed.

### CODE REVIEW

File: packages/block-library/src/image/edit.js [hunk 1]
```diff
@@ -186,11 +187,20 @@ class ImageEdit extends Component {
...
-		this.props.setAttributes( {
+		let mediaAttributes = {
 			...pickRelevantMediaFiles( media ),
 			width: undefined,
 			height: undefined,
-		} );
+		};
+
+		const { id, url, alt } = this.props.attributes;
+		// If the current image is temporary but an alt text was meanwhile wrotten by the user,
```
Comment (epiqueras) [inline packages/block-library/src/image/edit.js]:
```suggestion
		// If the current image is temporary but an alt text was meanwhile written by the user,
```

File: packages/block-library/src/image/edit.js [hunk 2]
```diff
@@ -186,11 +187,20 @@ class ImageEdit extends Component {
...
+		// make sure the text is not overwritten.
+		if ( alt && isTemporaryImage( id, url ) ) {
```
Comment (epiqueras) [inline packages/block-library/src/image/edit.js]: Let's also take care of the `caption` here so that this can also close #16746 .

**Review by epiqueras — DISMISSED** [review]

**Comment by jorgefilipecosta** [comment]
Hi @epiqueras, thank you for reviewing this PR! The PR was rebased and updated to also deal with the caption.
