### PR TITLE
Image: Manually update resizable box state when we don't have dimenssions

### LINKED ISSUE #23985: Image Block: When replacing a resized image by another image, the image proportions are preserved inside the editor but not on the front-end (WP 5.5 beta2)
**To reproduce**

1. Inside the editor, insert an image.
2. Resize the image to a smaller size using the resize handles.
3. Replace the image by another one.
4. Observe that visually the new image is distorted and has the same proportions as the replaced one. If you preview the front-end (or if you switch back and forth between the code editor and the visual editor), you’ll see that the image has, in reality, its own dimensions.

resized-image-replace

Tested using WordPress 5.5 beta 2 and WP 5.4.2 + Gutenberg 8.5.1.
The bug happens on Chrome, Firefox and Edge on both Windows and Mac.
It's working fine on Safari.

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
When changing to a different image, we reset dimension attributes, including size props for the resizable box. But this doesn't automatically reset dimensions in the resizable box state, which is used for inline styles. So we have to do it manually.

Fixes #23985.

P.S. This might be an issue with the upstream package - `re-resizable`.

## How has this been tested?
1. Add image block and set image
2. Resize the image.
3. Replace it with a different image.
4. See if a resizable box is reset.

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [N/A] My code follows the accessibility standards. 
- [N/A] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [N/A] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-library/src/image/image.js [hunk 1]
```diff
@@ -177,6 +178,17 @@ export default function Image( {
...
+	// Set resizable box dimensions to "auto" when we don't have width/height.
+	// This is done to reset inline styles after changing to a different image.
+	useEffect( () => {
+		if ( url && resizableBoxRef.current && ! width && ! height ) {
+			resizableBoxRef.current.updateSize( {
+				width: 'auto',
+				height: 'auto',
+			} );
+		}
+	}, [ url, width, height ] );
```
Comment (ajlende) [inline packages/block-library/src/image/image.js]: Why is this being called in a `useEffect` instead of in `updateImage` where the attributes are reset?

Comment (ajlende) [reply packages/block-library/src/image/image.js]: Or better yet, could we just set the `width` and `height` of the `ResizableBox` component to be `'auto'` when `attributes.width` and `attributes.height` are `undefined`?

```jsx
<ResizableBox
  size={ {
    width: width ?? 'auto',
    height: height ?? 'auto',
  } }
  ...
/>
```

Comment (Mamaduka) [reply packages/block-library/src/image/image.js]: Hi, @ajlende

Thanks for the review.

> Why is this being called in a useEffect instead of in updateImage where the attributes are reset?

The attributes are reset in `onSelectImage` and `updateImage`. Using the `useEffect` seemed more optimal at the time.

> Or better yet, could we just set the width and height of the ResizableBox component to be 'auto' when attributes.width and attributes.height are undefined?

Thanks for suggesting a clearer approach 🙇  This is the reason I love reviews.

**Review by ajlende — APPROVED** [review]
Looks good to me!

https://user-images.githubusercontent.com/5129775/112585878-c71f5280-8d9e-11eb-8665-58d661b9b651.mp4
