### PR TITLE
Font Library: fix duplicate variants with different file types

### LINKED ISSUE #54253: Font Library: Same font faces with different file extensions are added as a separated variant.
## What ?

> Font with the same name but different type as existing custom font (e.g. guillon_normal_400.ttf and guillon_normal_400.woff2) is added as a separate variant. 

Originally reported by @ironprogrammer in https://github.com/WordPress/gutenberg/pull/53884#issuecomment-1709315408

## Expected:
- There should not be 2 variants if you are uploading the same family weight and style.
- The old file should be removed or overwritten.

## Current behavior 
Currently, we compare the incoming variant with the existing one in the backend. We use a string-based approach around the entire font face data, so if something of the font face data is different (the file name in this case), it will be treated as a new variant.

https://github.com/WordPress/gutenberg/blob/e7b7c83216524ac9714aed6949b43043970d0512/lib/experimental/fonts/font-library/class-wp-font-family-utils.php#L65-L73

## What needs to be changed
- Consider the variants by their font style and weight to know if they are repeated.
- If we update the file asset, the old should be removed or overwritten.

### PR DESCRIPTION
**Pull request by jffng**
## What?
This PR adds checks to ensure that multiple file types of the same font variant are not added, so that only one variation per font style and weight is stored. 

## Why?
Fixes #54253

## How?
For fonts where the font family does not yet exist, checks the list of new font faces and compares their font weight and style, and if there is already an existing font face, skips adding the incoming one.

For font faces where the font family exists, adds a new function `get_intersecting_font_faces` which returns an array of font faces to be deleted and replaced by the incoming font face.

## Testing Instructions
1. Simultaneously (batch) upload two or more font faces of the same family, style, and weight, but different file types. 
2. Ensure only the first variant is added / used.
3. Upload a font face to an existing font family with the same style and weight, but different file type.
4. Ensure the uploaded version is used / replaces the existing one, and an additional variant is not created.

### CODE REVIEW

**Review by pbking — APPROVED** [review]
This is working as expected for me.  Fonts are limited to a single format.  When adding a new it seems to always replace the existing, whatever format it is.  

When uploading multiple at the same time the format chosen seems to be... alphabetical? 

Either way, I can confirm that it fixes the issue at hand.

File: lib/experimental/fonts/font-library/class-wp-font-family.php [hunk 1]
```diff
@@ -493,7 +530,21 @@ private function create_font_post() {
 	private function update_font_post( $post ) {
 		$post_font_data = json_decode( $post->post_content, true );
 		$new_data       = WP_Font_Family_Utils::merge_fonts_data( $post_font_data, $this->data );
-		$this->data     = $new_data;
+		$intersecting   = $this->get_intersecting_font_faces( $post_font_data['fontFace'], $new_data['fontFace'] );
```
Comment (jffng) [inline lib/experimental/fonts/font-library/class-wp-font-family.php]: Can we expect that the data will always contain a `fontFace` key, or should we be more defensive here?

Comment (matiasbenedetto) [reply lib/experimental/fonts/font-library/class-wp-font-family.php]: Good catch, nope, there can be font families without a fontFace array defined or an empty array. So a check for that seems necessary,

**Comment by matiasbenedetto** [comment]
The tests I made manually are working great.
Currently, we are testing the case when two font faces have the same characteristics but different font files in the same request.
Could we add one more unit test case to cover the addition of font faces with the same characteristics in different requests? That's covered in the implementation but not in the unit tests.

File: lib/experimental/fonts/font-library/class-wp-font-family.php (hunk 1 above)
Comment (jffng) [reply lib/experimental/fonts/font-library/class-wp-font-family.php]: Thanks, done in [b07fdd0](https://github.com/WordPress/gutenberg/pull/54490/commits/b07fdd083687c250a396588cb9b525d6c3cb568c)

File: phpunit/tests/fonts/font-library/wpRestFontLibraryController/installFonts.php [hunk 2]
```diff
@@ -414,4 +414,91 @@ public function data_install_with_improper_inputs() {
...
+		$install_request    = new WP_REST_Request( 'POST', '/wp/v2/fonts' );
+		$font_families_json = json_encode( $font_families );
+		$install_request->set_param( 'fontFamilies', $font_families_json );
+		$install_request->set_file_params( $files );
+
+		$response = rest_get_server()->dispatch( $install_request );
+		$this->assertSame( 200, $response->get_status(), 'The response status is not 200.' );
+		$data = $response->get_data();
+		$this->assertCount( 1, $expected_response[0]['fontFace'], 'Duplicate font faces were not removed / added incorrectly.' );
+		$this->assertStringEndsWith( $expected_response[0]['fontFace'][0]['src'], $data[0]['fontFace'][0]['src'], 'The src attribute does not match the expected font file.' );
```
Comment (matiasbenedetto) [inline phpunit/tests/fonts/font-library/wpRestFontLibraryController/installFonts.php]: As the de-duplication functionality is not in the Rest controller but in the Font Family class, it may be better to move this test to the install tests file: `phpunit/tests/fonts/font-library/wpFontFamily/install.php`.

Apart from that, as we are not testing the API endpoint, I think the requests are not necessary because we are not testing that. Probably it would be better to add the data we want to test like this:


```
$font = new WP_Font_Family( $the_font_data_im_testing )
$font->install();
```

See this test as an example: https://github.com/WordPress/gutenberg/blob/761c390e3ce0a92a9f4183509074d634799711ef/phpunit/tests/fonts/font-library/wpFontFamily/install.php#L86-L101

**Comment by jffng** [comment]
@matiasbenedetto I moved these tests to the `Tests_Fonts_WpFontFamily_Install` class, added a case to cover installing multiple font faces that contain duplicates, and one test to cover the addition of font faces with the same characteristics in different requests.

File: phpunit/tests/fonts/font-library/wpRestFontLibraryController/installFonts.php (hunk 2 above)
Comment (jffng) [reply phpunit/tests/fonts/font-library/wpRestFontLibraryController/installFonts.php]: Good call, done in [ce5a4a9](https://github.com/WordPress/gutenberg/pull/54490/commits/ce5a4a9cd393ebed176c6bf2df9a72be86c1daf5).

**Review by jeffikus — APPROVED** [review]
LGTM - I tested with with Cardo font.

- Regular 
- Italic
- Bold

Used ttf, woff, woff2 file types for each.

This created 3 variants within Cardo, tried uploading 9 files total.
