### PR TITLE
Firefox: fix input rules (React async state issue)

### LINKED ISSUE #48207: Firefox: List block loses content when created via shortcuts
### Description

When writing `- ` or `* 1` I expect:

- for `- ` to end up with a list block immediately 
  - instead the list block is inserted only after I type
- for `* 1` to end up with a list block with the content `1` in it
  - instead an empty list block is created

### Step-by-step reproduction instructions

See description

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/107534/219666971-708912c7-cec4-4d59-831a-f73052b0e977.mp4

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #49741: Heading shortcut broken in 6.2 in Firefox
### Description

In WordPress < 6.2, typing ## followed by a space followed by some text results in that text becoming a heading block.

In Firefox in WordPress 6.2, the transformation does not occur until after you type another character after the space, and eats that character, preventing it from showing up.

Have tested and it works in the same browser in WordPress 6.1, as well as in Chrome in WordPress 6.2, so it's some connection between Firefox and 6.2. (Have also tested with all extensions disabled).

### Step-by-step reproduction instructions

Type `## Heading` into the editor.

In WordPress < 6.2 with Firefox, or 6.2 with Chrome, you will see **Heading**.

In WordPress 6.2 with Firefox, you will see **eading**.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WordPress 6.2, no Gutenberg plugin, all themes
Firefox 112.0 (64-bit), desktop Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Currently the `useRichText` hook outputs a rich text value which is normally immediately updated when the state changes on input. However, React may update the state async, which mean other `input` event handlers may be getting an old state.

One way to work around this would be returning a ref in the `useRichText` hook _alongside_ the normal value (because some components will still rely on a value change).

~~A better way to work around this is with with getters: replace all the rich text value properties with getters so it's guaranteed to get the latest value. Since having the latest value immediately available is only important for event handlers, we don't need to find a way for the re-rendering to be synchronous.~~

Edit: I switched to adding a `getValue` function to get the latest value between re-renders in event handlers.

## Why?

Fixes #48207.

### CODE REVIEW

**Comment by ellatrix** [comment]
Thinking about this more, this could introduce problems if we want to compare these values, for example in `useEffect` dependencies. Maybe it's better to create a separate `getValue` for use in event callbacks.

**Review by draganescu — APPROVED** [review]
Tested this and it solves the problem 👍🏻 🙌🏻

File: packages/rich-text/src/component/index.js [hunk 1]
```diff
@@ -248,6 +248,12 @@ export function useRichText( {
 
 	return {
 		value: record.current,
+		// A function to get the most recent value so event handlers in
+		// useRichText implementations have access to it. For example when
+		// listening to input events, we internally update the state, but this
+		// state is not yet available to the input event handler because React
+		// may re-render asynchronously.
+		getValue: () => record.current,
```
Comment (kevin940726) [inline packages/rich-text/src/component/index.js:256]: Would the same work if instead of passing `ref.current` or `() => ref.current`, we just pass `ref` here and access `ref.current` in the event handlers?

Comment (ellatrix) [reply packages/rich-text/src/component/index.js:256]: Yes, but it might get confusing if that ref is passed to another ref? I also think the naming of `getValue` is clearer than `valueRef.current` or something like that.

Comment (kevin940726) [reply packages/rich-text/src/component/index.js:256]: > but it might get confusing if that ref is passed to another ref?

What do you mean by this?

Personally, I would prefer `ref.current` as it is just the standard idiomatic React's ref. But I also wouldn't mind `getValue()` as it's also simple and clear enough 👍 .

Comment (ellatrix) [reply packages/rich-text/src/component/index.js:256]: We're passing all props within a ref here, so it's a nested ref: https://github.com/WordPress/gutenberg/pull/48210/files#diff-8ba153e0dccbf25a179a794cb63aacd09e575d5dcfa819f8aefa33086ddbbb6eR52

**Comment by Mamaduka** [comment]
I just cherry-picked this PR to the wp/6.2 branch to get it included in the next release: 1413816f2f
