### PR TITLE
Used align hook in columns block; Fixed columns alignment bug;

### LINKED ISSUE #5117: Alignment class missing from column block save function.
## Issue Overview
The columns block adds support for wide and full-width alignment and works in the editor, but the class does not get added and saved in the save function.

## Steps to Reproduce (for bugs)
1. Add the column block to a post or page.
2. Add content to the block and set the alignment to wide or full-width.
3. Save the post and view the columns on the front end of your site.

Chrome 64.0.3282.167

## Expected Behavior
The alignment class should be saved to the column container to be displayed accordingly on the front end. 

## Current Behavior
The alignment class does not get saved to the column container.

## Possible Solution
Add the alignment class to [this line](https://github.com/WordPress/gutenberg/blob/34aaa3924882bdfe0392a5cdd6615a0b088129bc/blocks/library/columns/index.js#L109) of the column save function.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
This PR makes column class make use of the align hook, by using `supports: align`. This change fixes a bug where align classes were not passed to the frontend.

Fixes: https://github.com/WordPress/gutenberg/issues/5117

## How has this been tested?
Verify the columns block continue to work as expected, verify it is possible to align it to 'wide' or 'full' and then the corresponding class is passed to the frontend.

### CODE REVIEW

File: blocks/library/columns/index.js [hunk 1]
```diff
@@ -70,20 +69,11 @@ export const settings = {
 	},
 
 	edit( { attributes, setAttributes, className } ) {
-		const { align, columns } = attributes;
+		const { columns } = attributes;
```
Comment (gziolo) [inline blocks/library/columns/index.js]: I wanted to introduce a similar change in #5099. If you look at https://github.com/WordPress/gutenberg/pull/5099/files#diff-89d3b001ccbb88ada880aa2d5db1c55bR58, `getEditWrapperProps` was also removed because it is handled by hooks.

**Comment by gziolo** [comment]
I did the same in #5099, we use `align` with Paragraph block. However, we didn't roll this out to all blocks because we didn't find a solid way to tackle server-side rendered blocks. The issue is that those hooks that modify blocks to add support for `align` are executed only on the client. There needs to be a way to have the same behavior on the server to make sure that `align` attributes is listed when rendering dynamic block.

On the technical level, this PR is good to go after no longer needed `getEditWrapperProps` is removed. The question remains if we should do it or wait as @aduth suggested until this solution is bullet-proof.

**Comment by jorgefilipecosta** [comment]
Hi @gziolo, I'm sorry I did not remember that your PR also did this change. Given that your PR is on hold until we solve the server side blocks challenge, I think it would be ok to merge this one as it solves a bug. We are already using `supports: align` in some blocks like audio so it would basically be one more block using it :)

**Review by gziolo — APPROVED** [review]
It's good to go as I mentioned earlier.
