### PR TITLE
Avoid change in RichText when possible

### LINKED ISSUE #5103: Rich Text: Unnecessarily dispatching change actions
## Issue Overview

The RichText component dispatches more change actions than necessary.

## Steps to Reproduce

1. Create a post with a single paragraph and save it
2. Refresh the page and open [Redux DevTools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en)
3. Select the first paragraph and type a single letter
4. Deselect the block by clicking the title

## Expected Behavior

A single change action is dispatched.

## Current Behavior

Three change actions are dispatched:

- Two at the keypress
- One at the deselect

This wouldn't be entirely problematic if the value weren't a new array each time, as the reducer considers it a new value and updates references accordingly (thus triggering rerenders).

## Possible Solution

Should we be checking that content has changed from `RichText` before triggering an update?

## Related

Possibly related to #4956

cc @iseulde @youknowriad

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #5103.

1. Don't create a history record when TinyMCE fires a change event on typing the first character.
2. Avoid updating the content on a change event when the content is the same. ~~This introduces a deep equality check, but the change event does not fire often (only MCE commands and internal undo levels). I don't like this check much; the alternative is to just let it dispatch an action.~~ This happens when the source event was blurs, so we can filter that out.

## How has this been tested?

Follow the steps in #5103 and ensure only one action is dispatched.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

File: blocks/rich-text/index.js [hunk 1]
```diff
@@ -375,15 +375,33 @@ export class RichText extends Component {
 	 * Handles any case where the content of the tinyMCE instance has changed.
 	 */
 
-	onChange() {
+	onChange( options ) {
+		const { checkEquality = false } = options;
+
 		this.savedContent = this.getContent();
+
+		if ( checkEquality && isEqual( this.props.value, this.savedContent ) ) {
```
Comment (youknowriad) [inline blocks/rich-text/index.js]: Curious when does this thing happen. I mean `this.props.value` and `this.savedContent` being equal but not strictly equal. this.savedContent was introduced exactly to avoid this kind of changes, so I'm wondering if we're missing a `this.savedContent` assignment somewhere?

File: blocks/rich-text/index.js [hunk 2]
```diff
@@ -375,15 +375,33 @@ export class RichText extends Component {
...
+		// In other cases TinyMCE won't fire a `change` with at least a previous
+		// record present, so this is a reliable check.
+		// https://github.com/tinymce/tinymce/blob/4.7.11/src/core/main/ts/api/UndoManager.ts#L272-L275
+		if ( event.lastLevel === null ) {
+			return;
+		}
+
+		// Always ensure the content is up-to-date, but avoid dispatching an
+		// action if it is (by way of input).
+		this.onChange( { checkEquality: true } );
```
Comment (youknowriad) [inline blocks/rich-text/index.js]: Won't this be a duplicate of the same call triggered by the `input` event handler?

Comment (iseulde) [reply blocks/rich-text/index.js]: > Avoid updating the content on a change event when the content is the same. This introduces a deep equality check, but the change event does not fire often (only MCE commands and internal undo levels). I don't like this check much; the alternative is to just let it dispatch an action.

It fires on TinyMCE commands, so this is needed in those cases.

File: blocks/rich-text/index.js (hunk 1 above)
Comment (iseulde) [reply blocks/rich-text/index.js]: Hm, that's in the updateContent function to avoid setting the content. This function does not do a strict equal check. `isEqual( this.props.value, this.savedContent )` will be true when the content is in sync, e.g. blurring the field.

Comment (aduth) [reply blocks/rich-text/index.js]: >`isEqual( this.props.value, this.savedContent )` will be true when the content is in sync, e.g. blurring the field.

When and why is this causing `onChange` to be called? Doesn't seem like it should be.

Comment (iseulde) [reply blocks/rich-text/index.js]: I changed it. It was to prevent dispatching actions when the content is the same (coming from a TinyMCE change event). This only happens on blur, so we can filter that one out.

File: editor/components/rich-text/index.js [hunk 3]
```diff
@@ -411,9 +411,24 @@ export class RichText extends Component {
...
+		// https://github.com/tinymce/tinymce/blob/4.7.11/src/core/main/ts/api/UndoManager.ts#L272-L275
+		if ( event && event.lastLevel === null ) {
+			return;
+		}
+
+		// Always ensure the content is up-to-date, but avoid dispatching an
+		// action if the original event is blur because the content will already
+		// be up-to-date.
+		if ( ! event || ! event.originalEvent || event.originalEvent.type !== 'blur' ) {
+			this.onChange();
```
Comment (youknowriad) [inline editor/components/rich-text/index.js]: I tested and it works well for me, but just confirming one last thing. In which case the `onCreateUndoLevel` triggers while the `input` doesn't trigger? or is it related to the order of the events?

Comment (iseulde) [reply editor/components/rich-text/index.js]: E.g. making something bold will trigger change but not input, so generally for any "command" in TinyMCE. Maybe we can also do the opposite here and call onChange for any command and other events that need a change.

Comment (youknowriad) [reply editor/components/rich-text/index.js]: I see, I think it sounds good to me 👍

**Review by youknowriad — APPROVED** [review]
LGTM 👍

File: editor/components/rich-text/index.js (hunk 3 above)
Comment (iseulde) [reply editor/components/rich-text/index.js]: @youknowriad I updated the comment so it's clearer now.
