### PR TITLE
api-fetch: Add Accept json header to l10n requests

### LINKED ISSUE #11327: GET requests are not localized
**Describe the bug**
Following up to #10811. `GET` requests are not localized because they don't pass `Accept: application/json` to the server.

Because of the difficulties of determining when a REST request is occurring early enough to support locale switching, the decision was made to use `wp_is_json_request()` which checks for the `content-type` and `accept` headers to determine if this is a JSON request. 

**To Reproduce**
1. Enable a language for your user in Admin → Profile.
2. Load Gutenberg on a post.
3. Observe that the response for the taxonomies endpoint does not return results in the desired language despite `&_locale=user` being included in the URL.

**Expected behavior**
The results to be returned in the user's locale.

**Screenshots**
user locale

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 12.0

**Additional context**
I'm having trouble getting the labels to be replaced in the UI. As you can see from the screenshot, the hierarchical panel seems to pull the new labels, but the flat panel seems to keep the same labels which were set when preloading? I have verified that the strings for both taxonomies are untranslated in the developer tools.

**Suggested Solution**
Add an `Accept: application/json` header in the `userLocaleMiddleware()` or in the `raw` handler the like `content-type` is. Happy to PR either.

### PR DESCRIPTION
**Pull request by TimothyBJacobs**
## Description
Fixes #11327. The server side localization switching requires an 'Accept' or
'Content-Type' header set to 'application/json` to detect that it is a JSON
request.

## How has this been tested?
Manually verify that `Accept: application/json` is in the `apiFetch` requests and the UI is properly localized.
With a unit test verifying that the `headers` option is mutated as expected.

## Screenshots 
fix localization

## Types of changes
Bug Fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 

I'm not sure if this can be properly unit tested. I considered trying to check that the `headers` passed into options is properly mutated, but my local install is currently failing when trying to run tests.

### CODE REVIEW

File: packages/api-fetch/src/index.js [hunk 1]
```diff
@@ -36,6 +36,10 @@ function apiFetch( options ) {
 			headers[ 'Content-Type' ] = 'application/json';
 		}
 
+		if ( ! headers.Accept ) {
+			headers.Accept = 'application/json';
```
Comment (youknowriad) [inline packages/api-fetch/src/index.js]: Are all api-fetch requests `application/json` requests? I'm not sure about that? One I can think of is the metabox save request. I wonder if there's others?

Why is it necessary for the server side localization switching to have an 'Accept' header?

Comment (TimothyBJacobs) [reply packages/api-fetch/src/index.js]: > Are all api-fetch requests application/json requests? I'm not sure about that? One I can think of is the metabox save request. I wonder if there's others?

I'm not sure. I proposed this, or doing it in the locale middleware.

> Why is it necessary for the server side localization switching to have an 'Accept' header?

The server side localization requires the Accept header because it uses `wp_is_json_request()`. Core does not currently have a method to check whether the current request is a REST request early enough for the locale switching to work and adding a reliable one would be quite difficult.

Comment (youknowriad) [reply packages/api-fetch/src/index.js]: > The server side localization requires the Accept header because it uses `wp_is_json_request()`.

Maybe a crazy question but can't we just do the switch for all requests :) and not only REST requests? Seems like a `_locale` argument is explicit enough for all requests :) 

I'd understand the hesitation though and would be ok with the change but we should just test it properly. It's also unfortunate because this means we can't have APIs returning something else that is not JSON?

Comment (TimothyBJacobs) [reply packages/api-fetch/src/index.js]: > Maybe a crazy question but can't we just do the switch for all requests :) and not only REST requests? Seems like a _locale argument is explicit enough for all requests :)

Something for @pento and @danielbachhuber. I image we wouldn't really want to touch front-end localization as that opens up a whole new can of worms, but ¯\\\_(ツ)\_/¯.

>  It's also unfortunate because this means we can't have APIs returning something else that is not JSON?

We could adjust the `Accept` header slightly to `Accept: application/json, */*;q=0.1` that would indicate we'd prefer a JSON response, but fallback to everything. `wp_is_json_request` just checks that `application/json` is present in the accept header.

Comment (danielbachhuber) [reply packages/api-fetch/src/index.js]: > > The server side localization requires the Accept header because it uses wp_is_json_request().
> 
> Maybe a crazy question but can't we just do the switch for all requests :) and not only REST requests? Seems like a _locale argument is explicit enough for all requests :)

This probably isn't a good idea.

Comment (aduth) [reply packages/api-fetch/src/index.js]: > Are all api-fetch requests `application/json` requests? I'm not sure about that? One I can think of is the metabox save request. I wonder if there's others?

The REST API is a JSON API, so I personally think it's perfectly reasonable to say "Yes, all requests are `application/json`" (or, more realistically, "should be").

Comment (youknowriad) [reply packages/api-fetch/src/index.js]: The question is whether `apiFetch` is limited to the REST API (which is not the case in our usage for the moment).

File: packages/api-fetch/src/index.js [hunk 2]
```diff
@@ -36,6 +36,10 @@ function apiFetch( options ) {
 			headers[ 'Content-Type' ] = 'application/json';
 		}
 
+		if ( ! headers.Accept ) {
```
Comment (aduth) [inline packages/api-fetch/src/index.js]: Minor: Rather than adding a bunch of `if` statements, we could simplify this using [`Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) in assigning these as defaults:

```js
const headers = {
	Accept: 'application/json, */*;q=0.1',
	'Content-Type': 'application/json',
	...remainingOptions.headers
};
```

File: packages/api-fetch/src/index.js [hunk 3]
```diff
@@ -36,6 +36,10 @@ function apiFetch( options ) {
...
+			headers.Accept = 'application/json, */*;q=0.1';
```
Comment (aduth) [inline packages/api-fetch/src/index.js]: Do we _want_ the "any" fallback?

**Comment by TimothyBJacobs** [comment]
Hmm. It's working for me.
screen shot 2018-11-01 at 1 41 19 pm
screen shot 2018-11-01 at 1 41 32 pm
screen shot 2018-11-01 at 1 41 36 pm

File: packages/api-fetch/src/index.js (hunk 2 above)
Comment (TimothyBJacobs) [reply packages/api-fetch/src/index.js]: Makes sense, will update.

**Comment by aduth** [comment]
@danielbachhuber Have you downloaded language packs for the plugin (checking Updates screen)?

**Comment by danielbachhuber** [comment]
@TimothyBJacobs Ok, I trust you. Might be a browser cache or something else on my end.

**Comment by TimothyBJacobs** [comment]
I double checked and did a fresh build, it seems to be working properly. Given how fragile the whole locale system works, it'd be nice if someone could give it another check to make sure I'm not the odd one out 😄.

I adjusted it to use the spread assign syntax. This breaks the tests, which were probably too brittle anyways.

**Comment by danielbachhuber** [comment]
> Given how fragile the whole locale system works, it'd be nice if someone could give it another check to make sure I'm not the odd one out 😄.

I was the odd one out: I had Gutenberg the plugin deactivated 😭

**Review by danielbachhuber — APPROVED** [review]

File: packages/api-fetch/src/index.js (hunk 3 above)
Comment (TimothyBJacobs) [reply packages/api-fetch/src/index.js]: Sorry, I thought that was resolved in the message with @youknowriad. Previously, `*/*` would be sent. Since I guess `apiFetch` isn't only intended for use with JSON APIs, I think it makes sense to use `*/*` as a fallback. Particularly since they can disable `parse` to allow them to handle their own responses as necessary, meaning that requiring JSON would no longer be true.

Comment (aduth) [reply packages/api-fetch/src/index.js]: >Since I guess `apiFetch` isn't only intended for use with JSON APIs

But I shall prove that it is _!_

Since the API Fetch module is a ["utility to make WordPress REST API requests"](https://github.com/WordPress/gutenberg/tree/master/packages/api-fetch) and the REST API operates by ["sending and receiving JSON"](https://developer.wordpress.org/rest-api/) we can conclude that — via transitive relation — the API Fetch module sends and receives JSON.

Comment (TimothyBJacobs) [reply packages/api-fetch/src/index.js]: I don't have any strongly held opinion here, just going off of @youknowriad's feedback.

File: packages/api-fetch/src/index.js [hunk 4]
```diff
@@ -31,10 +31,11 @@ function checkCloudflareError( error ) {
 function apiFetch( options ) {
 	const raw = ( nextOptions ) => {
 		const { url, path, body, data, parse = true, ...remainingOptions } = nextOptions;
-		const headers = remainingOptions.headers || {};
-		if ( ! headers[ 'Content-Type' ] && data ) {
-			headers[ 'Content-Type' ] = 'application/json';
-		}
+		const headers = {
+			Accept: 'application/json, */*;q=0.1',
+			'Content-Type': 'application/json',
```
Comment (youknowriad) [inline packages/api-fetch/src/index.js]: Image uploads are not JSON, this could have broke image uploads in media blocks.

Comment (danielbachhuber) [reply packages/api-fetch/src/index.js]: @youknowriad Sorry, not sure I follow. What's your point?

Is it:

* That we should have e2e tests covering image uploads?
* That we should have unit tests in this package ensuring multiple content types are supported?
* Something else?

Comment (youknowriad) [reply packages/api-fetch/src/index.js]: Just that uploading images is broken in master now because of this :)

Comment (aduth) [reply packages/api-fetch/src/index.js]: I'm working on a fix currently.

Comment (aduth) [reply packages/api-fetch/src/index.js]: Fix at #11437
