### PR TITLE
Fix empty url value from unbinding entity from inspector sidebar

### LINKED ISSUE #72481: Navigation Link: Issues with unlinking Page Link from Sidebar (reset of caption, input focus loss)
### Description

When unlinking a Page Link block from the block inspector, a number of strange things happen:

- The label (in the editor canvas) is reset. See the screenshot: Upon unlinking, the label changes to "Select page". (This is unexpected for me -- I'd expect the label to remain unchanged.)
- The URL input field is cleared. (It might make sense to keep the previous value and simply make it editable.) _More importantly, when you start manually entering a new URL, after pressing one letter, focus is stolen by the block label input in the canvas, and any subsequent keypresses will go there -- see screencast._

@jeryj and I observed these issues while discussing https://github.com/WordPress/gutenberg/pull/72165.

### Step-by-step reproduction instructions

1. Go to the Site Editor. Make sure you have a Navigation block with at least one Page Link block.
2. Open the block inspector for the Page Link block.
3. Click the "Unlink" button. It will clear the "Link" field. Note that it will also remove the label from the block in the editor canvas (it will fall back to "Select page").
4. Start typing a new URL. Observe that after you've pressed one letter (e.g. the `h` in `https://`), focus will be stolen by the block label input in the canvas, and the rest of the URL you're typing will end up there.

### Screenshots, screen recording, code snippet

Image

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by jeryj**
Fixes https://github.com/WordPress/gutenberg/issues/72481

Unbinding the navigation link entity from the sidebar updates the url value to be '', which causes the canvas to go into its empty URL state, which removes the label. Then, when you start typing in the url link input, it would steal focus back to the canvas. This changes the flow when unbinding to set the url as the previously linked url, which avoids an empty link issue. However, you can still get to the messed up state by deleting the url value. To fix this, instead of updating the attribute onChange, update it onBlur so we can restore the last known url.

## What?

When unsyncing the entity of a navigation link from the inspector sidebar:
1. the on-canvas label becomes the placeholder (select page) even though the text field in the sidebar still preserves the page name
2. When you start typing in the link url field the first time, focus is stolen to the canvas after the first keypress

This PR fixes the issue by filling the url field with the existing entity link url so it doesn't get an empty value, which means the placeholder on the canvas does not show.

## Why?

The current flow is clearly not the ideal behavior. It's a bug.

## How?
This does not need to be the final solution, as I think integrating the link control with this field will ultimately be better. However, the behavior on trunk is very buggy, and this PR does not feel buggy.

- Instead of clearing the URL, set it as the entity url that was just unsynced
- Don't update the url value onChange, wait until the blur event. Otherwise, if they delete their URL while still focused on the input, the canvas will show the label placeholder again
- Update the url onBlur (it already is anyways). If the value is empty onBlur, revert to the previous link value instead.

## Testing Instructions

- From an entity bound navigation link
- Go to its inspector sidebar
- Click the Unsync and edit button
- The link text should be whatever the previously bound url is
- The link text should be selected so you can easily delete it
- Update the link
- Move focus away from the link.
- Check it works as expected

- From an entity bound navigation link
- Go to its inspector sidebar
- Click the Unsync and edit button
- Delete the url
- The on canvas text label should remain
- Tab away from the field
- The url link input should revert to the value it was before editing began

## Screenshots or screencast 

**Before**

https://github.com/user-attachments/assets/f06028de-a122-4d34-bf2c-6478df8d8ca6 

**After**

https://github.com/user-attachments/assets/19ec6720-d2b2-451c-9950-a11a569a5e8f

### CODE REVIEW

**Comment by jeryj** [comment]
I'd rather wait to merge this until https://github.com/WordPress/gutenberg/pull/72436 is merged.

File: packages/block-library/src/navigation-link/shared/controls.js [hunk 1]
```diff
@@ -77,6 +77,14 @@ export function Controls( { attributes, setAttributes, clientId } ) {
 	const inputId = useInstanceId( Controls, 'link-input' );
 	const helpTextId = `${ inputId }__help`;
 
+	// Local state to control the input value
+	const [ inputValue, setInputValue ] = useState( url );
+
+	// Sync local state when url prop changes (e.g., from undo/redo or external updates)
+	useEffect( () => {
+		setInputValue( url );
+	}, [ url ] );
```
Comment (getdave) [inline packages/block-library/src/navigation-link/shared/controls.js:87]: Should we also update the ref here? Additional hardening against edge cases.

File: packages/block-library/src/navigation-link/shared/controls.js [hunk 2]
```diff
@@ -95,12 +103,17 @@ export function Controls( { attributes, setAttributes, clientId } ) {
 		// setAttributes is actually setBoundAttributes, a wrapper function that
 		// processes attributes through the binding system.
 		// See: packages/block-editor/src/components/block-edit/edit.js
-		updateBlockAttributes( clientId, { url: '', id: undefined } );
+		updateBlockAttributes( clientId, {
+			url: lastURLRef.current,
```
Comment (getdave) [inline packages/block-library/src/navigation-link/shared/controls.js]: I think we should include a comment here to explain why we use the ref value.

File: packages/block-library/src/navigation-link/shared/controls.js [hunk 3]
```diff
@@ -149,18 +162,20 @@ export function Controls( { attributes, setAttributes, clientId } ) {
...
 					type="url"
 					disabled={ hasUrlBinding }
+					onChange={ ( newValue ) => {
+						if ( hasUrlBinding ) {
+							return;
+						}
+
+						// Don't update the actual url attribute yet, defer to onBlur so we
+						// don't end up with the canvas thinking the url is empty, which causes
+						// the label to be replaced by the placeholder text.
```
Comment (getdave) [inline packages/block-library/src/navigation-link/shared/controls.js]:
```suggestion
						// Defer updating the url attribute until onBlur to prevent the canvas from 
						// treating it as empty and replacing the label with placeholder text.
```

Nit

File: packages/block-library/src/navigation-link/shared/test/controls.js [hunk 4]
```diff
@@ -95,18 +95,22 @@ describe( 'Controls', () => {
...
+	it( 'calls updateAttributes with new URL on blur', () => {
 		render( <Controls { ...defaultProps } /> );
 
 		const urlInput = screen.getByLabelText( 'Link' );
 
+		fireEvent.focus( urlInput );
 		fireEvent.change( urlInput, {
 			target: { value: 'https://example.com/test page' },
 		} );
+		fireEvent.blur( urlInput );
```
Comment (getdave) [inline packages/block-library/src/navigation-link/shared/test/controls.js]: Are we able to do this via interactions with elements rather than programmatically? If not then why? I'm curious about why we do it via APIs here.

**Review by getdave — APPROVED** [review]
I tested this and the flow does feel less jarring and it's easier to avoid ending up in a bad state.

I agree, LinkControl is the goal post-6.9 but for now this is an improvement.

I note that it's now _not_ possible to end up with an empty URL as the logic always restores the last value if the blur happens and the value is empty. I was thinking of this as a bug but actually it's a good safety catch. Worst case folks have to use at least `#` so we avoid possibility of true empty links.

File: packages/block-library/src/navigation-link/shared/controls.js (hunk 1 above)
Comment (jeryj) [reply packages/block-library/src/navigation-link/shared/controls.js:87]: Yes, that makes sense. Good catch.

File: packages/block-library/src/navigation-link/shared/test/controls.js (hunk 4 above)
Comment (jeryj) [reply packages/block-library/src/navigation-link/shared/test/controls.js]: Nope - updated to userEvents 👍🏻

**Comment by ellatrix** [comment]
I've manually cherry-picked this in 6a7bf43134230b854fe697b6dc275a659e2a9db0.
