### PR TITLE
Nested blocks: Show the side inserter on empty paragraphs

### LINKED ISSUE #5134: Impossible to add a block to Columns without also adding a Paragraph block, using the Inserter menu
## Issue Overview
I wanted to add a Columns block with multiple images. When I insert a Columns block, it automatically adds a paragraph block, which I don't want. When I then use the Inserter menu to insert my Image block, I'm still left with a Paragraph block which I neither inserted or wanted!

gutenberg-multicolumns5

If I use the Slash Command in the paragraph block, it converts to an Image block, but that's not good enough. Very few people are going to use the Slash Command. Unless you're used to using keyboard commands, most users are going to use the Inserter Menu. Using the Inserter menu though, it's impossible to add a columns block with just the blocks that I want. I'm always left with an extra Paragraph block, forcing me to have to delete something that I never even inserted in the first place!

## Steps to Reproduce (for bugs)
1. Insert Columns Block
2. Using the Inserter menu, insert an Image block
3. Note that the Columns block now also contains a Paragraph block which I neither inserted or wanted

## Expected Behavior
I expect to be able to add just the blocks that I want. Columns should not default to adding random blocks which I dont want

## Current Behavior
Columns Block adds unwanted blocks when inserted

_Firefox Quantum 58.0.2 (64-bit)
Gutenberg 2.2.0
WP 4.9.4_

### PR DESCRIPTION
**Pull request by youknowriad**
When checking if a block is empty or not, we should ignore the "layout" attribute as it's not really a block attribute but more something related to the position of the block inside the parent block. (which makes me think it should be best stored separately cc @aduth )

While this PR fix the issue where we needed at least one paragraph block inside the columns block to be able to insert another type of block type, it surfaces the styling issues in the columns block where there's not enough room for the side-inserter.

A workaround could be to hide this inserter in the columns block, you'd still be able to use the global inserter to replace the first block instead of appending a new block.

**Testing instructions**

 - Add a columns block
 - Select the first block in a column
 - Use the inserter 
 - It should replace the block and not insert a new one.

closes #5134

### CODE REVIEW

**Comment by jasmussen** [comment]
This just makes the empty-paragraph in-canvas inserter show up inside columns also, right? I think that's a superb solution.

By the way I'm working, right now, on a refactor of both floats and block boundaries. This should improve the nested UI also, allowing us to use negative margins. It's difficult, but it's overdue.

**Comment by aduth** [comment]
>which makes me think it should be best stored separately cc @aduth 

Have anything in mind? Earlier implementations of the columns block took the approach of having the parent manage its child locations, but in changing to target CSS Grid, inherited behavior of element assigning itself into particular layout (corresponding to `grid-column`, `grid-row` assignments).

We still could do something along these lines, except managed by the parent component, where the parent tracks which child indices are assigned into which layout:

https://codepen.io/aduth/pen/ZamBWO

In this example, the block markup might look more like:

```html
<!-- wp:columns {"layouts":{"column-1":[0,1,2],"column-2":[3,4,5,6,7]}} -->
<style>
.wp-block-columns.is-block-lkj1anzl > :nth-child( 1 ),
.wp-block-columns.is-block-lkj1anzl > :nth-child( 2 ),
.wp-block-columns.is-block-lkj1anzl > :nth-child( 3 ) {
  grid-column: 1;
}

.wp-block-columns.is-block-lkj1anzl > :nth-child( 4 ),
.wp-block-columns.is-block-lkj1anzl > :nth-child( 5 ),
.wp-block-columns.is-block-lkj1anzl > :nth-child( 6 ),
.wp-block-columns.is-block-lkj1anzl > :nth-child( 7 ),
.wp-block-columns.is-block-lkj1anzl > :nth-child( 8 ), {
  grid-column: 2;
}
</style>
<div class="wp-block-columns is-block-lkj1anzl">
  <span>one</span>
  <span>two</span>
  <span>three</span>
  <span>four</span>
  <span>five</span>
  <span>six</span>
  <span>seven</span>
  <span>eight</span>
</div>
<!-- /wp:columns -->
```

This would require some form of inline styles support as explored in #3669, #2862

File: blocks/api/utils.js [hunk 1]
```diff
@@ -25,10 +25,11 @@ export function isUnmodifiedDefaultBlock( block ) {
 	}
 
 	const newDefaultBlock = createBlock( defaultBlockName );
-	const attributeKeys = [
+	// Omit the layout attribute because it's a special attribute used for nested blocks.
```
Comment (aduth) [inline blocks/api/utils.js]: Could we generalize this with a filter so we can keep the logic for layout consolidated in `blocks/hooks/layout.js`?

**Review by aduth — DISMISSED** [review]

**Comment by youknowriad** [comment]
> We still could do something along these lines, except managed by the parent component, where the parent tracks which child indices are assigned into which layout:

Yes, that's what I was thinking, I don't know if it's totally legit though :)

File: blocks/api/utils.js [hunk 2]
```diff
@@ -25,10 +30,11 @@ export function isUnmodifiedDefaultBlock( block ) {
 	}
 
 	const newDefaultBlock = createBlock( defaultBlockName );
-	const attributeKeys = [
+
+	const attributeKeys = applyFilters( 'blocks.unmodifiedBlockAttributes', [
```
Comment (aduth) [inline blocks/api/utils.js]: Need some naming convention for these. I've been doing roughly `[module].[function].[modifier]`. Thoughts?

**Review by aduth — APPROVED** [review]

File: blocks/api/utils.js (hunk 2 above)
Comment (youknowriad) [reply blocks/api/utils.js]: I like this convention, updating
