### PR TITLE
Fix floating date status inferred for posts where the status has been edited

### LINKED ISSUE #28083: Show date incorrect when switching a post from private to public
**Describe the bug**

When you switch an old post from "private" to "public", its initial publication date as private is kept but the "Publish" panel on the sidebar shows "Immediately" in the link.  When you click the link though and open the date picker, the  old date is still applied. And when you  hit "update" to save the post, the old date is shown everywhere.

**Expected behavior**

I expect one  of two things:

 - Don't  show "Immediately" in the publish panel when switching to private and just show old publication date everywhere.
 - Alternatively, we could decide that switching from "private" to "public" means we should change the data to "now" but this might be more complex and require more thoughts.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #28083 

The algorithm to infer the "floating" status of post dates have been introduced in #9967. It works well but it should be using the persisted post status and not the edited one. 

See #28083 for the testing instructions.

### CODE REVIEW

File: packages/editor/src/store/selectors.js [hunk 1]
```diff
@@ -757,7 +757,12 @@ export function isEditedPostBeingScheduled( state ) {
 export function isEditedPostDateFloating( state ) {
 	const date = getEditedPostAttribute( state, 'date' );
 	const modified = getEditedPostAttribute( state, 'modified' );
-	const status = getEditedPostAttribute( state, 'status' );
+
+	// This should be the status of the persitedd post
```
Comment (ockham) [inline packages/editor/src/store/selectors.js:761]:
```suggestion
	// This should be the status of the persisted post
```

**Review by ockham — APPROVED** [review]
Working well! Thanks a lot :shipit:
