### PR TITLE
Rich text: enable if multi selection is aborted

### LINKED ISSUE #19731: Clicking into text blocks doesn't always allow you to edit.
**Describe the bug**

Using the latest version of `master`, I've noticed that sometimes I'm unable to click into RichText blocks and edit them (Paragraph, Header, List, etc.). 

I haven't been able to track down exact replication steps yet, but I've seen it happen a handful of times now, usually while composing longer posts. When it occurs, the only remedy I've found is to save the post and reload the page. 

**Screenshots**

In the GIF below, it's possible to edit the code block, but not the paragraph block:

editing

**Desktop (please complete the following information):**
 - MacOS 10.15.2
- Safari 13.0.4

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #19731.

This bug is really hard to reproduce, I cannot even find any specific steps to reproduce it, but I do find it happening after a while when rapidly clicking around in the edit, especially around navigation block items.

I did the same thing with this PR, and I see that multi selection is attempted, aborted, and now rich text fields are properly re-enabled.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

File: packages/block-editor/src/components/block-list/use-multi-selection.js [hunk 1]
```diff
@@ -150,8 +150,10 @@ export default function useMultiSelection( ref ) {
 	const onSelectionChange = useCallback( ( { isSelectionEnd } ) => {
 		const selection = window.getSelection();
 
-		// If no selection is found, end multi selection.
+		// If no selection is found, end multi selection and enable all rich
+		// text areas.
 		if ( ! selection.rangeCount || selection.isCollapsed ) {
+			toggleRichText( ref.current, true );
```
Comment (ellatrix) [inline packages/block-editor/src/components/block-list/use-multi-selection.js]: Looking back, it is obvious that rich text fields should have been re-enabled here.

**Comment by kjellr** [comment]
I did a bunch of rapid clicking around for a few minutes, and wasn't able to reproduce the error anymore. 👍 I'd hold off for another test it before merging though — as you noted, it's generally pretty difficult to reproduce. 

Thanks for diving into this issue!

**Comment by ZebulanStanphill** [comment]
I just tested this branch, and it looks like this fixes #18977, which I guess must be the same issue as #19731. :tada:

**Review by talldan — APPROVED** [review]
I did more clicking around and wasn't able to reproduce the issue. Selection seems to still be working well, so I think this is good to go. Thanks @ellatrix!

Another things this seems to have fixed, clicking on Navigation Link placeholders wasn't causing the text to be editable, that's working now, so another added bonus.
