### PR TITLE
Fix: theme colors cannot override defaults

### LINKED ISSUE #36772: Theme colors can override default colors
In testing https://github.com/WordPress/gutenberg/issues/36770 there's an issue with the theme palette that may override the default palette, creating weird interactions in the editor.

## How to reproduce:

- Use the empty theme and add a color with the same slug as one in the default palette. For example (note that I use red as the color value for debugging purposes, the important bit is that I'm using the `black` slug):

```json
{
	"version": 2,
	"settings": {
		"color": {
			"palette": [
				{
					"name": "Black",
					"slug": "black",
					"color": "red"
				}
			]
		},
```
- Go to the post editor and add a paragraph.
- Select the black color from the default palette.

Notice that the text color becomes red instead.

## Future

In the future, we may consider adding an explicit API for themes to override colors in the default palette.

### PR DESCRIPTION
**Pull request by oandregal**
Fixes https://github.com/WordPress/gutenberg/issues/36772

This PR removes the theme presets that have the same slug as a core preset of the same type. For example, the color theme presets can't have a `black` slug, which is already part of the color default presets.

### Global presets are filtered

- Use the TT1-blocks theme.
- In its `theme.json` update the value of the colors whose slug is `black` and `white` to a color that is easily inspectable for debugging purposes. For example:
```json
{
  "slug": "black",
  "color": "#FF69B4",
  "name": "Black"
},
{
  "slug": "white",
  "color": "#FF69B4",
  "name": "White"
}
```
- Go to the front-end and inspect the `global-styles-inline-css` embedded stylesheet.
  - Verify that there's only a single `--wp--preset--color--black` whose value is `#000000` and a single `--wp--preset--color--white` whose value is `#FFFFFF` (they come from the default palette).
  - Before this PR the value for both would be `#FF69B4`.
- Go to the editors and verify that the theme palette does not contain the black & white colors in the theme palette.

| Before | After |
| --------- | ------- |
| Captura de ecrã de 2021-11-24 10-35-44 |  Captura de ecrã de 2021-11-24 10-38-16 |

### Block-level presets are filtered

- In the `theme.json` file of the TT1-blocks, add the following palette under `settings.blocks.core/paragraph.color.palette`:
```json
[
  {
    "slug": "black",
    "color": "#FF69B4",
    "name": "Black"
  },
  {
    "slug": "yellow",
    "color": "#EEEADD",
    "name": "Yellow"
  },
  {
    "slug": "white",
    "color": "#FF69B4",
    "name": "White"
  }
]

```

- In the editors, the expected result is that the palette for the paragraph only contains one color (the yellow).
- In the front, within the `global-styles-inline-css` embedded stylesheet the expected result is that there's new CSS Custom Properties and classes scoped to the paragraph block:

```css
p {
  --wp--preset--color--yellow: #eeeadd;
}

p.has-yellow-color {
  color: var(--wp--preset--color--yellow) !important;
}
p.has-yellow-background-color {
  background-color: var(--wp--preset--color--yellow) !important;
}
p.has-yellow-border-color {
  border-color: var(--wp--preset--color--yellow) !important;
}
```

### CODE REVIEW

**Comment by oandregal** [comment]
Marking as "needs dev note" to share that theme overriding theme colors is not expected and creates conflicts with the current direction for the UI color component (showing all palettes).

**Review by jorgefilipecosta — APPROVED** [review]
LGTM 👍

**Comment by oandregal** [comment]
Pushed a change to limit this to the `palette` and `gradient` presets, the only ones for which we display different sources of data at the moment.

File: lib/class-wp-theme-json-gutenberg.php [hunk 1]
```diff
@@ -1354,32 +1362,127 @@ public function merge( $incoming ) {
...
+		 */
+		$slugs_global = self::get_slugs_not_to_override( $this->theme_json );
+
 		$nodes = self::get_setting_nodes( $this->theme_json );
 		foreach ( $nodes as $metadata ) {
 			foreach ( $to_replace as $property_path ) {
 				$path = array_merge( $metadata['path'], $property_path );
 				$node = _wp_array_get( $incoming_data, $path, null );
 				if ( isset( $node ) ) {
+					if ( 'theme' === $path[ count( $path ) - 1 ] ) {
```
Comment (jorgefilipecosta) [inline lib/class-wp-theme-json-gutenberg.php]: Could we check if $metadata['override'] is set on this if condition and avoid all the filter logic after (also removing the check for override inside get_slugs_not_to_override)?

Comment (oandregal) [reply lib/class-wp-theme-json-gutenberg.php]: Pushed changes to do this.

File: lib/class-wp-theme-json-gutenberg.php [hunk 2]
```diff
@@ -1354,32 +1362,137 @@ public function merge( $incoming ) {
...
+		 * We rather replace the existing with the incoming value, if it exists.
+		 * This happens, for example, when we merge data from theme.json upon existing
+		 * theme supports or when we merge anything coming from the same source twice.
+		 * This is the case of color.palette, color.gradients, color.duotone,
+		 * typography.fontSizes, or typography.fontFamilies.
+		 *
+		 * Additionally, for some preset types, we also want to make sure the
+		 * values they introduce don't conflict with default values. We do so
+		 * by checking the incoming slugs for theme presets and compare them
+		 * with the equivalent dfefault presets: if a slug is present as a default
```
Comment (jorgefilipecosta) [inline lib/class-wp-theme-json-gutenberg.php:1384]: Typo: dfefault

**Comment by jorgefilipecosta** [comment]
Did another test after the updates and things seem to work well.
