### PR TITLE
Fix: Categories Block: hierarchical Dropdown

### LINKED ISSUE #13560: Categories Block: hierarchical Dropdown
**Describe the bug**
If I select the dropdown and the hierarchical option the Categories block, second level categories are rendered twice and third level categories are rendered three times.

Backend
bildschirmfoto 2019-01-29 um 11 23 37

Frontend
bildschirmfoto 2019-01-29 um 11 24 04

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/13560

Previously higher than second levels categories here rendered multiple times on the categories block, when "Show Hierarchy" and "Display as Dropdown" options here true.
This PR fixes that problem.

## How has this been tested?
I created a Level 1 category without parent category.
I created a Level 2 category child of Level 1.
I created a Level 3 category child of Level 2.
I added a post with a Level 3 category.
I added the Category block and enable "Show Hierarchy" and "Display as Dropdown".
I checked the dropdown as displayed as expected without Level 2 and Level 3 being repeated.
## Screenshots 
Before:
screenshot 2019-01-29 at 18 56 20
After:
screenshot 2019-01-29 at 18 55 24

### CODE REVIEW

File: packages/block-library/src/categories/edit.js [hunk 1]
```diff
@@ -116,7 +116,11 @@ class CategoriesEdit extends Component {
 					{ __( 'Categories' ) }
 				</label>
 				<select id={ selectId } className="wp-block-categories__dropdown">
-					{ categories.map( ( category ) => this.renderCategoryDropdownItem( category, 0 ) ) }
+					{ categories.map( ( category ) => {
```
Comment (gziolo) [inline packages/block-library/src/categories/edit.js]: This is the case where you can also use more functional approach and combine `filter` and `map`:
```js
{ categories.filter( ( { parent } => parent === 0 ).map( ( category ) => this.renderCategoryDropdownItem( category, 0 ) ) }
```

Still the same code, just coded differently and I haven't tested :)

Comment (jorgefilipecosta) [reply packages/block-library/src/categories/edit.js]: Hi @gziolo, I applied the refactor to use a functional code style. Thank you for your suggestion!

File: packages/block-library/src/categories/edit.js [hunk 2]
```diff
@@ -116,7 +116,13 @@ class CategoriesEdit extends Component {
 					{ __( 'Categories' ) }
 				</label>
 				<select id={ selectId } className="wp-block-categories__dropdown">
-					{ categories.map( ( category ) => this.renderCategoryDropdownItem( category, 0 ) ) }
+					{ categories.filter(
```
Comment (gziolo) [inline packages/block-library/src/categories/edit.js]: This made me think we could filter inside `getCategories` method to make it easier to follow here.

I will test this PR by tomorrow.

Comment (jorgefilipecosta) [reply packages/block-library/src/categories/edit.js]: I made a new check in the logic of the code and it looks like the filtering was already being accounted in the logic. The existing logic only had a bug when accessing a prop that caused the filtering to not be performed. The fix was simplified.

Comment (gziolo) [reply packages/block-library/src/categories/edit.js]: This is nice, thanks for investigating further, testing your changes soon.

**Review by gziolo — APPROVED** [review]
Code changes look great after 2 iterations 😃 
It tests well, I can confirm that issue is resolved.
