### PR TITLE
Fix dev build for fresh checkouts (or with  build/scripts/block-library missing)

### LINKED ISSUE #75107: Dev build error on new checkout or after `rm -R build`
## Description

When running a dev build with `npm run dev` in a fresh Gutenberg repository checkout (or after running `rm -R build/scripts/block-library`), an error is thrown:

```
Building blocks manifests...
 ERROR  Input directory "/Users/adamsilverstein/repositories/gutenberg-new2/build/scripts/block-library" does not exist.

❌ Dev build failed: Command failed: wp-scripts build-blocks-manifest --input=build/scripts/block-library --output=build/scripts/block-library/blocks-manifest.php
```

## Additional details
Running `npm run build` works fine, and subsequent calls to `npm run dev` also work, the build command apparently created the missing folder the dev build complains about being missing.

Likely there is a missing build step that checks for the folder and creates it if missing needs to be added to `bin/dev.mjs`; I recently fixed a similar issue I had introduced in https://github.com/WordPress/gutenberg/pull/75104 

##  Steps to reproduce
1. Check out a fresh copy of the Gutenberg repository
2. Run `nvm use && npm install && npm run dev`

### Expected result
Build completes successfully

### Actual result
Error notes above

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by adamsilverstein**
## What?
Fix a dev build issue with fresh checkouts.

Closes https://github.com/WordPress/gutenberg/issues/75107

## How?
Claude suggested running the failing step later, which worked in my testing. I'm uncertain if this the right spot or best approach, but I did verify this fixes the issue.

## Testing Instructions
1. remove previous build artifacts: `rm -R build`
2. run a dev build: `npm run dev`

Build should complete and wait for changes.

### CODE REVIEW

File: bin/dev.mjs [hunk 1]
```diff
@@ -239,11 +211,40 @@ async function dev() {
...
 		let isReady = false;
-		buildWatch.stdout.on( 'data', ( data ) => {
+		buildWatch.stdout.on( 'data', async ( data ) => {
 			const output = data.toString();
 			process.stdout.write( output );
 			if ( ! isReady && output.includes( 'Watching for changes' ) ) {
 				isReady = true;
+
+				// Build blocks manifests after initial build completes
+				console.log( '\n📦 Building blocks manifests...' );
```
Comment (Mamaduka) [inline bin/dev.mjs]: Maybe we should skip logging this message in dev mode. Having it after "Watching for changes" feels a bit odd, as if another process has also started but never finished.

## Screenshot

CleanShot 2026-02-02 at 08 42 39

**Review by Mamaduka — APPROVED** [review]
Can confirm that this fixes the issue ✅ 

The [build process also generates a manifest](https://github.com/WordPress/gutenberg/blob/50ba3eb351467b7e016634bbe62a2deb5f106bba/bin/build.mjs#L139-L144) after the `wp-build` call, so the solution here seems logical to me.

File: bin/dev.mjs (hunk 1 above)
Comment (adamsilverstein) [reply bin/dev.mjs]: Good point, I will remove that. It also looked odd to me.

Comment (adamsilverstein) [reply bin/dev.mjs]: removed in https://github.com/WordPress/gutenberg/pull/75108/commits/a15c69876209ba2ea1921ba7b28cabbce932cb90

Merging once CI passes.
