### PR TITLE
Block custom CSS: Fix incorrect CSS when multiple root selectors

### LINKED ISSUE #53597: Adding css property for core/list markers in theme.json has unexpected css output
### Description

I added the following in theme.json for the core/list block:

```json
"styles": {
  "blocks": {
    "core/list": {
      "css": "& ::marker {color: var(--wp--preset--color--pink);}"
    }
  }
}
```

Works great on unordered lists, but it unexpectedly affects the text for ordered lists.

screen-capture 2023-08-11 at 7 17 55 PM

When you take a look at the CSS produced, you can see why.

```css
ol, ul ::marker {
    color: var(--wp--preset--color--pink);
}
```

I expect the following to be produced instead:

```css
ol ::marker, ul ::marker {
    color: var(--wp--preset--color--pink);
}
```

### Step-by-step reproduction instructions

1. Style list markers using the `css` property on the `core/list` block in theme.json
2. Observe that the wrong css rule is output - `ol, ul ::marker` instead of `ol ::marker, ul ::marker`

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 6.3, bundled version of Gutenberg, a barebones block theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes: #53597

### <samp>🤖 Generated by Copilot at 65d02b2</samp>

This pull request refactors the PHP and JS functions that process nested CSS rules for global styles, and adds a unit test for the PHP function. The refactor fixes a bug that caused invalid CSS output when multiple root selectors were present, and improves the code readability and consistency.

## Why?

~The custom CSS for the block uses `__experimentSelector` in block.json as the root selector.~ The custom CSS for the block uses the selector obtained via the [Selectors API](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/block-api/block-selectors.md) as the root selector. For the List block, for example, there will be multiple selectors separated by commas, such as `ul,ol`.

However, when nested CSS is defined in the global styles or `css` properties in `theme.json`, the current implementation does not take multiple selectors into account and treats them as a single selector, causing the issue reported in #53597.

## How?

When generating nested CSS, I first convert the root selectors into an array by splitting them with commas. Then, the nested selector is added to each root selector, which is an element of the array, and converted back into a comma-separated string.

### preparation

- Activate emptytheme.
- If you have customized global styles, reset them once.
- Insert two types of Listing blocks in the post editor.

```html
<!-- wp:list -->
<ul><!-- wp:list-item -->
<li>List Item</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>List Item</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>List Item</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:list {"ordered":true} -->
<ol><!-- wp:list-item -->
<li>List Item</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>List Item</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>List Item</li>
<!-- /wp:list-item --></ol>
<!-- /wp:list -->
```

### Via theme.json

- Update theme.json as follows:

```json
{
	"version": 2,
	"settings": {
		"layout": {
			"contentSize": "840px",
			"wideSize": "1100px"
		}
	},
	"styles": {
		"blocks": {
			"core/list": {
				"css": "background: #ccc; & ::marker{ color: red;}"
			}
		}
	}
}
```

The gray background color and red marker style should be correctly applied to both the Ordered and Unordered lists.

### Via the Site Editor

- Undo theme.json.
- Go to the Site Editor and access the Additional CSS menu for the List block from the Global Styles menu.
- Enter the following styles: `background: #ccc; & ::marker{ color: red;}`
- The gray background color and red marker style should be correctly applied to both the Ordered and Unordered lists.

### CODE REVIEW

File: lib/class-wp-theme-json-gutenberg.php [hunk 1]
```diff
@@ -1138,9 +1138,27 @@ protected function process_blocks_custom_css( $css, $selector ) {
...
+			$is_root_css = ( ! str_contains( $part, '{' ) );
+			if ( $is_root_css ) {
+				// If the part doesn't contain braces, it applies to the root level.
+				$processed_css .= trim( $selector ) . '{' . trim( $part ) . '}';
+			} else {
+				// If the part contains braces, it's a nested CSS rule.
+				$part = explode( '{', str_replace( '}', '', $part ) );
+				if ( count( $part ) !== 2 ) {
+					continue;
+				}
```
Comment (t-hamano) [inline lib/class-wp-theme-json-gutenberg.php:1157]: This is to exclude strings with invalid braces, such as the following, and to ensure that they are correctly split into selector and value.

```
& ::marker{{ color: red;}
```

File: lib/class-wp-theme-json-gutenberg.php [hunk 2]
```diff
@@ -1138,9 +1138,27 @@ protected function process_blocks_custom_css( $css, $selector ) {
...
+				$nested_selector    = $part[0];
+				$css_value          = $part[1];
+				$root_selectors     = explode( ',', $selector );
+				$combined_selectors = array_map(
+					static function( $root_selector ) use ( $nested_selector ) {
+						return $root_selector . $nested_selector;
+					},
+					$root_selectors
+				);
+				$processed_css     .= implode( ',', $combined_selectors ) . '{' . trim( $css_value ) . '}';
```
Comment (aaronrobertshaw) [inline lib/class-wp-theme-json-gutenberg.php]: Can we reuse the [`scope_selector`](https://github.com/WordPress/gutenberg/blob/20a6fd4939a8732615b59504f667d130d9165f64/lib/class-wp-theme-json-gutenberg.php#L1624) function here?
```suggestion
				$part_selector     = static::scope_selector( $selector, $nested_selector );
				$processed_css .= $part_selector . '{' . trim( $css_value ) . '}';
```

File: packages/block-editor/src/components/global-styles/use-global-styles-output.js [hunk 3]
```diff
@@ -1127,9 +1127,26 @@ const processCSSNesting = ( css, blockSelector ) => {
...
+			}
+
+			const [ nestedSelector, cssValue ] = splittedPart;
+			const rootSelectors = blockSelector.split( ',' );
+			const combinedSelectors = rootSelectors.map(
+				( rootSelector ) => rootSelector + nestedSelector
+			);
+			processedCSS += `${ combinedSelectors.join(
+				', '
+			) }{${ cssValue.trim() }}`;
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/components/global-styles/use-global-styles-output.js]: This can reuse the existing `scopeSelector` util as well, I think.
```suggestion
			const [ nestedSelector, cssValue ] = splittedPart;
			const combinedSelector = scopeSelector(
				blockSelector,
				nestedSelector
			);
			processedCSS += `${ combinedSelector }{${ cssValue.trim() }}`;
```

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for fixing this @t-hamano 👍 

It tests well for me although I think there are a couple of tweaks we can make to the code. 

There are existing util functions to help scope selectors on both the PHP and JS side. Using those will make the code easier to read and maintain etc. What do you think?

| Before | After |
|---|---|
| Screenshot 2023-09-27 at 11 10 08 am | Screenshot 2023-09-27 at 11 10 33 am |


> The custom CSS for the block uses __experimentSelector in block.json as the root selector.

It might be worth clarifying that the `__experimentalSelector` is only one (deprecated) source for the block's selector. The root selector for a block comes from the [Selectors API](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/block-api/block-selectors.md). The Selectors API does provide support for, and falls back to, the `__experimentalSelector` block.json property though for backwards compatibility purposes.

**Comment by t-hamano** [comment]
Thanks for the review, @aaronrobertshaw!

> There are existing util functions to help scope selectors on both the PHP and JS side. Using those will make the code easier to read and maintain etc. What do you think?

Oops, I didn't know that such a utility exists for both PHP and JS 😅 However, I found that the _nested_ selector has two meanings:

- `&::before` : apply to root selector (e.g. `ul::before` )
- `& ::before`: apply to children (e.g. `ul ::before`)

My understanding is correct, right?

So I used `scope_selector()` method when there is a space at the beginning of the nested selector, and `append_to_selector()` when there is no space.

Based on these, I updated the PR as follows:

- Updated PHP unit tests to cover more variations with and without a space after `&`.
- I applied similar logic in JavaScript, but since there was no function equivalent to `append_to_selector()`, I added a new `appendToSelector()` function.
- Added JavaScript unit tests that are equivalent to PHP unit tests. This unit test evaluates the `processCSSNesting()` function.

File: packages/block-editor/src/components/global-styles/test/use-global-styles-output.js [hunk 4]
```diff
@@ -967,4 +968,42 @@ describe( 'global styles renderer', () => {
 			] );
 		} );
 	} );
+
+	describe( 'processCSSNesting', () => {
+		it( 'should return a processed CSS without any nested selectors', () => {
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/components/global-styles/test/use-global-styles-output.js]:
```suggestion
		it( 'should return processed CSS without any nested selectors', () => {
```

Nit: typo

File: packages/block-editor/src/components/global-styles/test/use-global-styles-output.js [hunk 5]
```diff
@@ -967,4 +968,42 @@ describe( 'global styles renderer', () => {
...
+			expect(
+				processCSSNesting( 'color: red; margin: auto;', '.foo' )
+			).toEqual( '.foo{color: red; margin: auto;}' );
+		} );
+		it( 'should return a processed CSS with nested selectors', () => {
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/components/global-styles/test/use-global-styles-output.js]:
```suggestion
		it( 'should return processed CSS with nested selectors', () => {
```

Nit: typo

File: packages/block-editor/src/components/global-styles/test/use-global-styles-output.js [hunk 6]
```diff
@@ -967,4 +968,42 @@ describe( 'global styles renderer', () => {
...
+			expect(
+				processCSSNesting(
+					'color: red; margin: auto; &.one{color: blue;} & .two{color: green;}',
+					'.foo'
+				)
+			).toEqual(
+				'.foo{color: red; margin: auto;}.foo.one{color: blue;}.foo .two{color: green;}'
+			);
+		} );
+		it( 'should return a processed CSS with pseudo elements', () => {
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/components/global-styles/test/use-global-styles-output.js]:
```suggestion
		it( 'should return processed CSS with pseudo elements', () => {
```

Nit: typo

File: packages/block-editor/src/components/global-styles/test/use-global-styles-output.js [hunk 7]
```diff
@@ -967,4 +968,42 @@ describe( 'global styles renderer', () => {
...
+			expect(
+				processCSSNesting(
+					'color: red; margin: auto; &::before{color: blue;} & ::before{color: green;}  &.one::before{color: yellow;} & .two::before{color: purple;}',
+					'.foo'
+				)
+			).toEqual(
+				'.foo{color: red; margin: auto;}.foo::before{color: blue;}.foo ::before{color: green;}.foo.one::before{color: yellow;}.foo .two::before{color: purple;}'
+			);
+		} );
+		it( 'should return a processed CSS with multiple root selectors', () => {
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/components/global-styles/test/use-global-styles-output.js]:
```suggestion
		it( 'should return processed CSS with multiple root selectors', () => {
```

Nit: typo

File: packages/block-editor/src/components/global-styles/utils.js [hunk 8]
```diff
@@ -393,6 +393,27 @@ export function scopeSelector( scope, selector ) {
 	return selectorsScoped.join( ', ' );
 }
 
+/**
+ * Appends a sub-selector to an existing one.
+ *
+ * Given the compounded $selector "h1, h2, h3"
+ * and the $to_append selector ".some-class" the result will be
+ * "h1.some-class, h2.some-class, h3.some-class".
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/components/global-styles/utils.js]:
```suggestion
 * Given the compounded `selector` "h1, h2, h3"
 * and the `toAppend` selector ".some-class" the result will be
 * "h1.some-class, h2.some-class, h3.some-class".
```

**Review by aaronrobertshaw — APPROVED** [review]
This is looking in pretty good shape @t-hamano 👍 

It's working well for me although there are a few typos that we can tweak before landing. Bonus points for the updated tests, thank you!

✅ Blocks with selector lists as their primary selector now function correctly with custom CSS
✅ Works with simple selectors in custom CSS
✅ Works with nested sub-selectors
✅ Works with nested selectors that are appended to root selectors
✅ Unit tests pass

It might also be worth getting this fix into the 6.4 beta, what do you think?

**Comment by t-hamano** [comment]
Thank you for the test and typo correction, @aaronrobertshaw!

> It might also be worth getting this fix into the 6.4 beta, what do you think?

I think so too. Should I just submit a core ticket and attach a patch with similar changes to `src/wp-includes/class-wp-theme-json.php`?

**Comment by aaronrobertshaw** [comment]
> I think so too. Should I just submit a core ticket and attach a patch with similar changes to src/wp-includes/class-wp-theme-json.php?

Yep, sounds like a plan.

I've added the backport to WP Beta label to this PR for the JS side of things.

**Comment by t-hamano** [comment]
I have submitted a core patch and would like to merge this PR 🚀

https://core.trac.wordpress.org/ticket/59499

**Comment by mikachan** [comment]
I just cherry-picked this PR to the commits-for-6.4-beta2 branch to get it included in the next release: c35b6d0ecb

**Comment by bgardner** [comment]
> I just cherry-picked this PR to the commits-for-6.4-beta2 branch to get it included in the next release: [c35b6d0](https://github.com/WordPress/gutenberg/commit/c35b6d0ecb35873bb6c11da503ab0910a1f105b3)

Did this make it into Beta 2 @mikachan? I tested to check, but still seeing this:

```
ol, ul .is-style-no-style {
    list-style-type: none;
    padding-left: 0;
}
```

**Comment by bgardner** [comment]
Using this in theme.json, for context:

```
"core/list": {
	"css": "& .is-style-no-style {list-style-type: none;padding-left: 0;}",
},
```

**Comment by t-hamano** [comment]
@bgardner

Looking at your code, it looks like you want to target a Llist block that has a style variation named `no-styles` applied. If so, remove the space after the ampersand.

```json
"core/list": {
	"css": "&.is-style-no-style {list-style-type: none;padding-left: 0;}",
},
```

Additionally, in 6.4 Beta2, this issue is not yet fixed on **the frontend side**. The patch attached to [this ticket](https://core.trac.wordpress.org/ticket/59499) must be committed to core.

**Comment by mikachan** [comment]
> Did this make it into Beta 2 @mikachan?

Yes, the GB change was included in Beta 2 with this group of backports: https://github.com/WordPress/gutenberg/pull/54914.

> Additionally, in 6.4 Beta2, this issue is not yet fixed on the frontend side. The patch attached to [this ticket](https://core.trac.wordpress.org/ticket/59499) must be committed to core.

I'll see if I can help get some eyes on the trac ticket, it possibly needs to be brought up in a [Bug Scrub](https://make.wordpress.org/core/2023/08/17/bug-scrub-schedule-for-wordpress-6-4/).

**Comment by getdave** [comment]
✅ I updated this PR with the `Backported to Core` label to indicate that the backport has successfully merged into WP Core. I also updated the [PHP Sync Tracking Issue for WP 6.5](https://github.com/WordPress/gutenberg/issues/57959).

**Comment by t-hamano** [comment]
@getdave

This PR contains the actual fix and unit test updates. The fix itself has been [backported](https://github.com/WordPress/wordpress-develop/pull/5427), but the unit test chages have [not yet been backported](https://github.com/WordPress/wordpress-develop/pull/5902) to the core. Even in the tracking issue, one of the two has not been checked yet.

Therefore, I would like to Remove the "Backported" label for now. Once the unit test changes are committed to the core, I would like to add the "Backported" label again.

**Comment by getdave** [comment]
Looks like @youknowriad has completed the backport of the unit tests so we're all good now.
