### PR TITLE
Legacy Widget: Refactor Form to not use React

### LINKED ISSUE #31249: Adding a legacy widget and saving right away fails
## Description
Adding a Woo Product Tag Cloud and savind directly fails with the messahe `There was an error. f. is undefined.` I think it applies to any widget that does not need any configuration and you just want to save it,

## Step-by-step reproduction instructions
0. Have Gutenberg `trunk`
1. Install Woo
2. Go to Appearance > Widgets
3. Add a Woo Product Tag Cloud
4. Save
5. See error

## Expected behaviour
The added widget should be saved and just work

## Actual behaviour
It appears that if you edit the defaults AND preview the widget the save function works again.

https://user-images.githubusercontent.com/107534/116288554-4dfa8d00-a79a-11eb-8d8d-08feb68add48.mp4

### PR DESCRIPTION
**Pull request by noisysocks**
Removes `useForm` and `Form` in favour of `Control` which uses regular DOM APIs (not React) to create the harness that a legacy widget is mounted into.

It doesn't make much sense to use React here because:

- We can't use React's event system as widgets expect jQuery events.
- We can't use React's reconciliation as widgets expect that they can safely add event listeners to DOM elements.

With this refactor, it's trivial to fix https://github.com/WordPress/gutenberg/issues/31249 by calling `onChangeInstance` if there is no instance after the form first loads.

To do:

- [x] Test this with non-`WP_Widget` widgets.
- [x] Add back the inline comments I removed.

### CODE REVIEW

File: packages/block-library/src/legacy-widget/edit/create-control.js [hunk 1]
```diff
@@ -0,0 +1,242 @@
...
+				setHasPreview( ! isEmptyHTML( preview ) );
+
+				if ( ! instance.hash ) {
+					const { instance: nextInstance } = await encodeWidget(
+						idBase,
+						instance,
+						serializeForm( form )
+					);
+					setInstance( nextInstance );
+				}
```
Comment (noisysocks) [inline packages/block-library/src/legacy-widget/edit/create-control.js:127]: This is what fixes https://github.com/WordPress/gutenberg/issues/31249.

File: packages/block-library/src/legacy-widget/edit/index.js [hunk 2]
```diff
@@ -20,17 +20,16 @@ import { store as coreStore } from '@wordpress/core-data';
...
 import Preview from './preview';
 import NoPreview from './no-preview';
-import useForm from './use-form';
 import ConvertToBlocksButton from './convert-to-blocks-button';
 
 export default function Edit( props ) {
 	const { id, idBase } = props.attributes;
 	return (
 		<div { ...useBlockProps() }>
+			{ JSON.stringify( props.attributes ) }
```
Comment (noisysocks) [inline packages/block-library/src/legacy-widget/edit/index.js]: Oops, remove this.

File: packages/block-library/src/legacy-widget/edit/form.js [hunk 3]
```diff
@@ -1,143 +1,73 @@
...
-
-	// We can't use the real widget number as this is calculated by the server
-	// and we may not ever *actually* save this widget. Instead, use a fake but
-	// unique number.
-	const number = useInstanceId( Control );
+		return () => {
+			ref.current.removeChild( control.element );
+			control.destroy();
+		};
+	}, [] );
```
Comment (noisysocks) [inline packages/block-library/src/legacy-widget/edit/form.js]: This needs deps.

File: packages/block-library/src/legacy-widget/edit/form.js [hunk 4]
```diff
@@ -1,143 +1,73 @@
...
-		onSave( serializeForm( event.target ) );
-	};
-
-	// We can't use the real widget number as this is calculated by the server
-	// and we may not ever *actually* save this widget. Instead, use a fake but
-	// unique number.
-	const number = useInstanceId( Control );
+		return () => {
+			ref.current.removeChild( control.element );
+			control.destroy();
```
Comment (kevin940726) [inline packages/block-library/src/legacy-widget/edit/form.js:69]: Nit: We could embed `element.remove()` in `control.destroy()` and just call `destroy` here.

File: packages/block-library/src/legacy-widget/edit/create-control.js [hunk 5]
```diff
@@ -0,0 +1,242 @@
...
+ * External dependencies
+ */
+import { debounce } from 'lodash';
+
+/**
+ * WordPress dependencies
+ */
+import apiFetch from '@wordpress/api-fetch';
+
+export default function createControl( {
```
Comment (kevin940726) [inline packages/block-library/src/legacy-widget/edit/create-control.js]: I would probably write it as a class but this works too 😆

Comment (noisysocks) [reply packages/block-library/src/legacy-widget/edit/create-control.js]: I can never decide lol. I like that not using a class means that the "private" methods are actually not accessible. But then it's definitely silly to create a class-like thing and not use a class.

Comment (noisysocks) [reply packages/block-library/src/legacy-widget/edit/create-control.js]: One day...

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

File: packages/block-library/src/legacy-widget/edit/create-control.js [hunk 6]
```diff
@@ -0,0 +1,242 @@
...
+	onChangeInstance,
+	onChangeHasPreview,
+	onError,
+} ) {
+	let control, form, content, hasPreview;
+
+	function initDOM() {
+		const number = ++lastNumber;
+
+		control = document.createElement( 'div' );
```
Comment (kevin940726) [inline packages/block-library/src/legacy-widget/edit/create-control.js]: I have no issues with all these `createElement` boilerplate, as they probably won't have impact on size/performance after gzip. But for readability sake, what do you think if we create a `createElement` helper function for these 😆. Could look like something like this.

```js
function createElement(tag, attributes = {}, children = []) {
  const element = document.createElement(tag);

  for (const [attribute, value] of Object.entries(attributes)) {
    element.setAttribute(attribute, value);
  }

  for (const child of children) {
    element.appendChild(child);
  }
}

const control = createElement('div', { class: 'widget open' }, [
  createElement('form', { class: 'widget-inside', method: 'post' }, ...),
]);
```

File: packages/block-library/src/legacy-widget/edit/create-control.js (hunk 5 above)
Comment (kevin940726) [reply packages/block-library/src/legacy-widget/edit/create-control.js]: We could still wrap the class in a static method so that we can control what we really want to expose.

```js
class Control {
  static create(args) {
    const control = new Control(args);

    return {
      element: control.element,
      destroy: control.destroy,
    };
  }
  // ...
}

const { element, destroy } = Control.create(args);
```

File: packages/block-library/src/legacy-widget/edit/create-control.js (hunk 6 above)
Comment (noisysocks) [reply packages/block-library/src/legacy-widget/edit/create-control.js]: I umm'd and ahh'd about doing this. It's more readable but you force the reader to learn something new. I'll try it and see if I like it 😀

Comment (kevin940726) [reply packages/block-library/src/legacy-widget/edit/create-control.js]: We could go a step further and use jsx to simplify all these:

```jsx
/** @jsx createElement */

const control = <div className="widget open">
  <form className="widget-inside" method="post">
    // ...
  </form>
</div>
```

The readability improves but now it might be confused with React 😅 .

Another idea would be using [`htm`](https://www.npmjs.com/package/htm). It's under 450 bytes (we don't need caching so probably can use the mini version) so I think it's totally acceptable. It could be an overkill just for readability though.

```js
const html = htm.bind(createElement);

const control = html`
  <div class="widget open">
    <form class="widget-inside" method="post">
      // ...
    </form>
  </div>
`;
```

Comment (noisysocks) [reply packages/block-library/src/legacy-widget/edit/create-control.js]: That looks really nice but I'm not sure about adding `htm` as a dependency to `block-library` when only one block needs it.

I don't hate the `createElement` thing: ff40bb4d45. What do you think?

Comment (kevin940726) [reply packages/block-library/src/legacy-widget/edit/create-control.js]: Looking great! 👍

File: packages/block-library/src/legacy-widget/edit/control.js [hunk 7]
```diff
@@ -0,0 +1,367 @@
...
+				// happens when creating a new Legacy Widget block.
+				if ( ! this.instance.hash ) {
+					const { instance } = await encodeWidget(
+						this.idBase,
+						this.instance,
+						serializeForm( this.form )
+					);
+					this.instance = instance;
+				}
+			}
```
Comment (noisysocks) [inline packages/block-library/src/legacy-widget/edit/control.js:199]: This is what fixes #31249.

**Review by kevin940726 — APPROVED** [review]
LGTM 👍
