### PR TITLE
Auto-refresh Popovers

### LINKED ISSUE #11194: Tips are misplaced in Fullscreen Mode
**Describe the bug**
Tips displayed when the Gutenberg editor is used first time are misplaced when switching to the Fullscreen Mode.

**To Reproduce**
1. Create a new post after installing Gutenberg so the Welcome tips are displayed
2. Switch to the Fullscreen Mode without dismissing the tip
3. Position of the tip is not moved under the '+' icon (see screenshot 1 below).
4. Reload the editor
5. The tip is placed now in a different position but it is not still under the '+' icon (see screenshot 2 below).

**Expected behavior**
Tip is placed below the '+' icon.

**Screenshots**
Screenshot 1
screen shot 2018-10-29 at 11 05 36

Screenshot 2
screen shot 2018-10-29 at 11 05 55

**Desktop**
 - OS: macOS Mojave
 - Browser: Safari
 - Version: 12

**Additional context**
Steps 3 and 5 might sound like unnatural (users will likely dismiss the tips before changing the view mode), but there are other applications like [Jetpack](https://github.com/Automattic/jetpack/pull/10368#pullrequestreview-168954111) which are embedding the Gutenberg editor directly in Fullscreen Mode where this issue is present.

### PR DESCRIPTION
**Pull request by mmtr**
## Description
The `Popover` components are now refreshed every 500ms in order to recalculate their size or position.

Fixes WordPress/gutenberg#11194.

## How has this been tested?
Manually following these steps:
1. Activate the tips on More > Options > Enable tips
2. Switch to the Fullscreen Mode without dismissing the tip
3. Make sure the tip is placed under the '+' icon (see After screenshot below).

## Screenshots 
**Before**
screen shot 2018-10-29 at 11 05 36

**After**
screen shot 2018-10-30 at 19 22 34

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: packages/components/src/popover/index.js [hunk 1]
```diff
@@ -80,21 +81,28 @@ class Popover extends Component {
...
 
-	toggleWindowEvents( isListening ) {
+	toggleEvents( isListening ) {
 		const handler = isListening ? 'addEventListener' : 'removeEventListener';
 
 		window.cancelAnimationFrame( this.rafHandle );
 		window[ handler ]( 'resize', this.throttledComputePopoverPosition );
 		window[ handler ]( 'scroll', this.throttledComputePopoverPosition, true );
+
+		const hookNamespace = uniqueId( 'core/components/popover/toggle-events-' );
```
Comment (Copons) [inline packages/components/src/popover/index.js]: I'm not very familiar with how hooks work, but I'm wondering if this works as intended.
If I'm not mistaken, we're creating a namespace when we mount the component and a different one when we unmount it.
In other words:
- On mount: `addAction( 'foo', 'bar-1', () => {} )`
- On unmount: `removeAction( 'foo', 'bar-2' )`

This probably is not a big deal anyway, but I've tried moving the definition in the constructor, changing it into:
```es6
this.hookNamespace = uniqueId( 'core/components/popover/toggle-events-' );
```
and it seems to keep working in the same way. 🤔

**Comment by Copons** [comment]
@mmtr nice job here, this indeed works as expected and fixes the incorrect positioning of the NUX popovers when toggling the fullscreen mode.

Though, I've got an observation: we're adding some logic directly tied to Gutenberg into a component that's supposed to work outside Gutenberg as well.
(please core Guten-folks correct me if I'm wrong! 🙂 )

What if instead we added a new prop to `Popover` to make it listen to a custom hook, regardless of its origin?
Example (please note that I'm bad at variable naming 😄 ):

```es6
// packages/components/src/popover/index.js

const { repositionHook } = this.props;
if ( isListening && repositionAction ) {
	addAction( repositionAction, hookNamespace, () => this.throttledComputePopoverPosition() );
} else {
	removeAction( repositionAction, hookNamespace );
}
```

```jsx
// packages/nux/src/components/dot-tip/index.js

<Popover
	className="nux-dot-tip"
	position="middle right"
	// ...
	repositionHook="fullscreenModeToggled"
>
```

(Note also that in this case we'd need to update the `Popover` readme)

File: packages/components/src/popover/index.js (hunk 1 above)
Comment (mmtr) [reply packages/components/src/popover/index.js]: You're right! Probably it's not needed to remove the action hook for having this working. Anyway, it makes sense to use the same namespace for adding/removing the same hook so I moved it to the constructor as suggested.

**Comment by mmtr** [comment]
Thanks for the review @Copons and for that great suggestion of the custom hooks. It makes this feature more solid and decoupled, so I have applied it on 14d165a352e4c2d81dfbc811b4e73229ec6fd012

File: packages/edit-post/src/components/fullscreen-mode/index.js [hunk 2]
```diff
@@ -17,11 +18,15 @@ class FullscreenMode extends Component {
 
 	sync() {
 		const { isActive } = this.props;
+		let delay = 0;
 		if ( isActive ) {
 			document.body.classList.add( 'is-fullscreen-mode' );
+			delay = 300; // .is-fullscreen-mode has a fade in animation of 0.3s
```
Comment (gziolo) [inline packages/edit-post/src/components/fullscreen-mode/index.js]: I'm not happy about this solution proposed here. What if CSS overrides animation to finish in 0.4s? Is there any other way to ensure that this event is properly triggered?

File: packages/edit-post/src/components/fullscreen-mode/index.js [hunk 3]
```diff
@@ -17,11 +18,15 @@ class FullscreenMode extends Component {
...
 		} else {
 			document.body.classList.remove( 'is-fullscreen-mode' );
 		}
+
+		setTimeout( () => doAction( 'fullscreenModeToggled' ), delay );
```
Comment (gziolo) [inline packages/edit-post/src/components/fullscreen-mode/index.js]: It's an interesting usage of action hooks. Combined with `recalculatePositionHook` prop it makes it nicely decoupled from `edit-post`. However, I'm wondering if we should programmatically trigger `resize` event on `window` object instead to simulate what in reality happens in here. @aduth or @youknowriad any thoughts on that?

Comment (youknowriad) [reply packages/edit-post/src/components/fullscreen-mode/index.js]: I personally think this is not the right way to go about it. We already have `refresh` functions in `Popover` and `DropDown` component to be able to trigger a refresh when necessary. I agree though that it's not usable here because there's no directly relation between the "fullsize toggle" and any other popover shown in the screen.

My idea solution would be to drop this `refresh` method and this hook entirely and make sure the Popover updates itself when the position of its wrapper node change or its content is resized. I know this is not achievable easily as there's no event to detect such changes but I think we should at least try a `setInterval` check (see if it's not impactful performance wise).

Thoughs?

Comment (jasmussen) [reply packages/edit-post/src/components/fullscreen-mode/index.js]: I would agree this is the wrong fix for the issue at hand, as it adds complexity. It also assumes specific editor interface configurations, that although they are relatively stable might change in the future in which case this implementation will need to be revisited.

I would suggest a copule of other possible approaches to fixing this issue:

1. Toggle off the tips when fullscreen mode is engaged — similar to pressing the X button. Essentially a click that isn't dismiss or next, in this case "fullscreen", feels like an implicit "I'm done with tips" click.
2. Toggle them off and on again.
3. Change how the tips work so they are either inline, or perhaps even truly modal — i.e. you HAVE to click next or dismiss them before you can proceed. 
4. Consider this more or less a non-issue. The tips aren't _that_ disconnected, and as soon as you press Next, the subsequent tooltip is correctly positioned.

Overall, I would imagine so many changes happening to tips in Phase 2 that I don't think it would be too healthy for the code to optimize for this particular configuration right at this point. 

Option 3 is my personal favorite at it might also have benefits for accessibility. More than that, there are a bunch of issues filed in the Tips label at the moment, that are related to the fact that you _can change content below the tips without dismissing them_. For example you can toggle on or off the settings tab multiple times while still reading the tip that suggests you toggle them on.

Comment (mmtr) [reply packages/edit-post/src/components/fullscreen-mode/index.js]: Thanks for all the ideas! Yeah, I agree this can lead to an over-engineered solution, although I tried to make it as simple as possible (my initial attempt was dispatching actions for connecting `edit-post` with `nux`).

Before considering what approach we should consider for going ahead, let me summarize where this issue is coming from. 

Calypso is integrating the Gutenberg editor but there is a lot of work to do in order to have something stable. So, in the meantime, we're going to redirect the users to the WP Admin Gutenberg editor (Automattic/wp-calypso#27317) using Calypsoify.

Calypsoify changes the WP Admin UI so it looks like Calypso, and the way of doing that for the Gutenberg editor is by enabling the Fullscreen mode (the Calypso editor is pretty similar to the Gutenberg editor in Fullscreen mode).

This means that the Fullscreen mode will be enabled programmatically. The user is not doing anything so I don't think we can hide the tips or force the user to dismiss them.

That's why I'd go for the @gziolo or @youknowriad suggestions, but I'm also wondering if this not really an issue as @jasmussen pointed and it's very related to Calypsoify and we should fix it there.

Comment (youknowriad) [reply packages/edit-post/src/components/fullscreen-mode/index.js]: I personally would love a generic solution in `Popover` if possible because this refresh can be necessary in a wide range of situations.

Comment (mmtr) [reply packages/edit-post/src/components/fullscreen-mode/index.js]: I'm thinking in using [`ResizeObserver`](https://alligator.io/js/resize-observer/) (and its [polyfill](https://github.com/que-etc/resize-observer-polyfill)) for detecting when the anchor of the popover changes, instead of using `setInterval`.

What are your thoughts about that?

Comment (youknowriad) [reply packages/edit-post/src/components/fullscreen-mode/index.js]: @mmtr Worth a try, I think we need both a resize and a position observer though, I don't know if it takes into account all the use-cases.

Comment (Copons) [reply packages/edit-post/src/components/fullscreen-mode/index.js]: Just to be clear though, this is not a Calypso-only fix. 🙂 
If folks toggle into fullscreen with the NUX (or any other popovers, for that matter) visible, the popover doesn't reposition.

I think this solution is still a worthwhile extension for the `Popover` component, but I have to agree the better one would be to observe the anchor position.

We already use `MutationObserver` in Gutenberg, so we might want to try listening with something roughly like this:

```es6
const observer = new MutationObserver( mutations => {
  if ( _.find( mutations, { type: 'attributes', attributeName: 'style' } ) ) {
    this.refresh();
  }
} );

observer.observe( this.anchorRef, { attributes: true } );
```

(I'm not super familiar with `MutationObserver`, maybe there's a better way to check if only the anchor position has changed, instead of any style?)

Also, I'd probably still only enable the observer if some sort of `repositionWhenAnchorRepositions` prop is true, to keep the existing behaviour untouched, and avoid performance issues.

Comment (mmtr) [reply packages/edit-post/src/components/fullscreen-mode/index.js]: `MutationObserver` won't work since it only detects changes done in the DOM and we don't manipulate the DOM of the anchor. 

I'm investigating the new `ResizeObserver` and `IntersectionObserver` observers, which apparently detects changes in the sizes and positions respectively.

Comment (Copons) [reply packages/edit-post/src/components/fullscreen-mode/index.js]: @mmtr Ah yup, that makes sense 🙁

File: packages/components/src/dropdown/index.js [hunk 4]
```diff
@@ -39,17 +36,6 @@ class Dropdown extends Component {
 		}
 	}
 
-	/**
-	 * When contents change height due to user interaction,
-	 * `refresh` can be called to re-render Popover with correct
-	 * attributes which allow scroll, if need be.
-	 */
-	refresh() {
```
Comment (youknowriad) [inline packages/components/src/dropdown/index.js]: I wonder if we should deprecate it first before removing it :)

File: packages/components/src/popover/index.js [hunk 5]
```diff
@@ -80,24 +81,21 @@ class Popover extends Component {
...
 		clearTimeout( this.focusTimeout );
+		this.toggleAutoRefresh();
 	}
 
-	toggleWindowEvents( isListening ) {
-		const handler = isListening ? 'addEventListener' : 'removeEventListener';
-
-		window.cancelAnimationFrame( this.rafHandle );
-		window[ handler ]( 'resize', this.throttledComputePopoverPosition );
-		window[ handler ]( 'scroll', this.throttledComputePopoverPosition, true );
```
Comment (youknowriad) [inline packages/components/src/popover/index.js]: Another possibility would be to keep those events and increase the interval timeout for advanced use-cases (like Fullscreen).

I'll give it a try in its current form though and see how it goes.

File: packages/components/src/dropdown/index.js (hunk 4 above)
Comment (mmtr) [reply packages/components/src/dropdown/index.js]: Indeed ;)

File: packages/components/src/popover/index.js (hunk 5 above)
Comment (mmtr) [reply packages/components/src/popover/index.js]: Sounds a good alternative to have in consideration if this causes a bad performance

File: packages/components/src/popover/index.js [hunk 6]
```diff
@@ -80,24 +81,21 @@ class Popover extends Component {
 	}
 
 	componentWillUnmount() {
-		this.toggleWindowEvents( false );
-
 		clearTimeout( this.focusTimeout );
+		this.toggleAutoRefresh();
```
[the remark this answers is not in the document]
Comment (youknowriad) [reply packages/components/src/popover/index.js]: No, it's more about the position and size of the popover, I think it should be on by default.

File: packages/components/src/popover/index.js [hunk 7]
```diff
@@ -80,24 +81,21 @@ class Popover extends Component {
...
-			return;
+	toggleAutoRefresh() {
+		if ( this.autoRefresh ) {
+			clearInterval( this.autoRefresh );
+			this.autoRefresh = null;
+		} else {
+			// Checks every 0.2s if the popover needs to be resized or repositioned
+			this.autoRefresh = setInterval( () => {
+				window.cancelAnimationFrame( this.rafHandle );
+				this.rafHandle = window.requestAnimationFrame( () => this.refresh() );
```
Comment (youknowriad) [inline packages/components/src/popover/index.js]: I think we should store the last position of the anchor element and the last size of the popover content and compare with the previous value before calling refresh :)

I'm having a weird behavior where the scrollbars appear/disappear continuously and I suspect that this change will fix it :)

crazy-popover

Comment (mmtr) [reply packages/components/src/popover/index.js]: Good catch! 

We were already checking that the size and position didn't change in the `updatePopoverSize` and `computePopoverPosition` methods. 

The problem was on how the size was being calculated, as it was not having in consideration the actual height of the content, just the visible the part.

I fixed it by checking the `scrollHeight` property instead of using `getBoundingClientRect().height`.

File: packages/components/src/popover/index.js (hunk 5 above)
Comment (mmtr) [reply packages/components/src/popover/index.js]: I finally applied this, since I didn't like how the popovers were repositioned when scrolling the window.

File: packages/components/src/popover/index.js [hunk 8]
```diff
@@ -80,24 +80,32 @@ class Popover extends Component {
...
-		window[ handler ]( 'scroll', this.throttledComputePopoverPosition, true );
+	toggleAutoRefresh( isActive ) {
+		// Resize and scroll window events
+		const handler = isActive ? 'addEventListener' : 'removeEventListener';
+		window[ handler ]( 'resize', this.throttledRefresh );
+		window[ handler ]( 'scroll', this.throttledRefresh, true );
+
+		// Auto refresh every 0.5s
+		if ( isActive ) {
+			this.autoRefresh = setInterval( () => {
```
Comment (youknowriad) [inline packages/components/src/popover/index.js]: Should we add a comment explaining why we're using `setInterval` (no resize and position events)

Comment (mmtr) [reply packages/components/src/popover/index.js]: Yup, it is not obvious. Added in https://github.com/WordPress/gutenberg/pull/11257/commits/8c5645b6d134c02227fb68bfd691c3bbb7cf0df1

**Review by youknowriad — APPROVED** [review]
LGTM 👍 

@aduth What do you think performance wise?

**Review by youknowriad — COMMENTED** [review]
Would be good to add a note to the CHANGELOG.md of the package.

File: packages/components/src/dropdown/index.js [hunk 9]
```diff
@@ -43,8 +43,13 @@ class Dropdown extends Component {
 	 * When contents change height due to user interaction,
 	 * `refresh` can be called to re-render Popover with correct
 	 * attributes which allow scroll, if need be.
+	 * @deprecated
 	 */
 	refresh() {
+		deprecated( 'refresh', {
+			plugin: 'Dropdown',
```
Comment (aduth) [inline packages/components/src/dropdown/index.js]: `plugin` should be `'Gutenberg'`

Comment (aduth) [reply packages/components/src/dropdown/index.js]: This lacks a version. Needs `version: '4.5'`

Comment (aduth) [reply packages/components/src/dropdown/index.js]: Any deprecations must be accompanied by a note in `docs/deprecated.md`

File: packages/components/src/popover/index.js [hunk 10]
```diff
@@ -80,24 +80,38 @@ class Popover extends Component {
...
 
-	throttledComputePopoverPosition( event ) {
-		if ( event.type === 'scroll' && this.contentNode.current.contains( event.target ) ) {
+	throttledRefresh( event ) {
+		window.cancelAnimationFrame( this.rafHandle );
+		if ( event && event.type === 'scroll' && this.contentNode.current.contains( event.target ) ) {
 			return;
 		}
-		this.rafHandle = window.requestAnimationFrame( () => this.computePopoverPosition() );
+		this.rafHandle = window.requestAnimationFrame( () => this.refresh() );
```
Comment (aduth) [inline packages/components/src/popover/index.js]: This needs to be cancelled on unmount. At present, I don't think that occurs.

File: packages/components/src/popover/index.js [hunk 11]
```diff
@@ -80,24 +80,38 @@ class Popover extends Component {
...
-		window[ handler ]( 'scroll', this.throttledComputePopoverPosition, true );
+		/*
+		 * There are sometimes we need to reposition or resize the popover that are not
+		 * handled by the resize/scroll window events (i.e. CSS changes in the layout
+		 * that changes the position of the anchor).
+		 *
+		 * For these situations, we refresh the popover every 0.5s
+		 */
+		if ( isActive ) {
+			this.autoRefresh = setInterval( () => {
```
Comment (aduth) [inline packages/components/src/popover/index.js]: Do we need the wrapping function?

vs.

```js
setInterval( this.throttledRefresh, 500 )
```

File: packages/components/src/popover/index.js (hunk 10 above)
Comment (aduth) [inline packages/components/src/popover/index.js]: While it existed previously, I might wonder the same about "Do we need the wrapping function?"

**Review by aduth — CHANGES_REQUESTED** [review]
>@aduth What do you think performance wise?

It should be fine as long as popovers are meant to be displayed temporarily, and typically one (or few at most) at a time. Otherwise we risk layout thrashing via reflow on the `scrollWidth`, `scrollHeight` access ([reference](https://gist.github.com/paulirish/5d52fb081b3570c81e3a)).

File: packages/components/src/popover/index.js (hunk 11 above)
Comment (mmtr) [reply packages/components/src/popover/index.js]: you're right, not needed :)

**Comment by mmtr** [comment]
Thanks for the reviews @youknowriad @aduth! I have updated both the changelog and the deprecation documents.

File: packages/components/CHANGELOG.md [hunk 12]
```diff
@@ -1,3 +1,13 @@
+## 5.0.3 (Unreleased)
+
+### Polish
```
Comment (aduth) [inline packages/components/CHANGELOG.md]: "Polish" to me seems like it should be used exclusively for non-impacting refactorings. This seems more an enhancement.

File: packages/components/src/dropdown/index.js [hunk 13]
```diff
@@ -43,8 +43,14 @@ class Dropdown extends Component {
...
 	 * attributes which allow scroll, if need be.
+	 * @deprecated
 	 */
 	refresh() {
+		deprecated( 'Dropdown.refresh()', {
+			plugin: 'Gutenberg',
+			version: '4.5',
+			hint: 'Popover is now automatically re-rendered without needing to execute "refresh"',
+		} );
 		if ( this.popoverRef.current ) {
```
Comment (aduth) [inline packages/components/src/dropdown/index.js]: Does this even need to occur? Could we change the function to a noop? Could be a good opportunity to highlight potential issues, as treating this as a noop forces reliance on the default behavior.

**Review by aduth — APPROVED** [review]

File: packages/components/CHANGELOG.md [hunk 14]
```diff
@@ -1,3 +1,13 @@
+## 5.0.3 (Unreleased)
```
Comment (aduth) [inline packages/components/CHANGELOG.md]: A deprecation must bump the minor version, not patch.

>Minor version Y (x.Y.z | x > 0) should be changed when you add functionality or change functionality in a backwards-compatible manner. It must be incremented if any public API functionality is marked as deprecated.

https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTING.md#maintaining-changelogs

**Review by aduth — CHANGES_REQUESTED** [review]

File: packages/components/src/dropdown/index.js (hunk 13 above)
Comment (mmtr) [reply packages/components/src/dropdown/index.js]: what if we just remove the rest of the function, so only `deprecated()` is executed?

Comment (aduth) [reply packages/components/src/dropdown/index.js]: > what if we just remove the rest of the function, so only `deprecated()` is executed?

Yes, sorry it wasn't clear. I mean precisely that.

File: packages/components/src/dropdown/index.js [hunk 15]
```diff
@@ -43,11 +43,14 @@ class Dropdown extends Component {
 	 * When contents change height due to user interaction,
 	 * `refresh` can be called to re-render Popover with correct
 	 * attributes which allow scroll, if need be.
+	 * @deprecated
 	 */
 	refresh() {
-		if ( this.popoverRef.current ) {
```
Comment (aduth) [inline packages/components/src/dropdown/index.js]: This `popoverRef` is now unused. Can we remove it? 

- The dependency on `createRef`
- The assignment in `constructor`
- The `ref` prop in `render`

**Comment by noisysocks** [comment]
Could we use `MutationObserver` for this?

File: packages/components/src/dropdown/index.js (hunk 15 above)
Comment (mmtr) [reply packages/components/src/dropdown/index.js]: Done in 3b34fc47606f448ac642108e0f2436baf55d3b56

**Review by aduth — APPROVED** [review]
There were some nasty merge conflicts. I've squashed your commits in a rebase, and force pushed. You'll need to delete your local copy if you want to pull down the latest.

**Comment by youknowriad** [comment]
The bug should be fixed by #11751
