### PR TITLE
Text Editor: Fix switching to the text editor mode

### LINKED ISSUE #434: Text mode broken + JS error
<details><summary>Uncaught TypeError: Cannot read property 'querySelector' of undefined</summary>

```
index.js:61 Uncaught TypeError: Cannot read property 'querySelector' of undefined
    at http://localhost:8888/wp/shared/plugins/gutenberg/blocks/build/index.js?ver=4.8-alpha-39357-src:4117:16
    at parse (http://localhost:8888/wp/shared/plugins/gutenberg/blocks/build/index.js?ver=4.8-alpha-39357-src:4084:10)
    at http://localhost:8888/wp/shared/plugins/gutenberg/blocks/build/index.js?ver=4.8-alpha-39357-src:4094:15
    at Array.reduce (native)
    at Object.parse (http://localhost:8888/wp/shared/plugins/gutenberg/blocks/build/index.js?ver=4.8-alpha-39357-src:4093:31)
    at getBlockAttributes (http://localhost:8888/wp/shared/plugins/gutenberg/blocks/build/index.js?ver=4.8-alpha-39357-src:4002:135)
    at http://localhost:8888/wp/shared/plugins/gutenberg/blocks/build/index.js?ver=4.8-alpha-39357-src:4375:178
    at Array.reduce (native)
    at Object.serialize (http://localhost:8888/wp/shared/plugins/gutenberg/blocks/build/index.js?ver=4.8-alpha-39357-src:4371:16)
    at TextEditor (http://localhost:8888/wp/shared/plugins/gutenberg/editor/build/index.js?ver=4.8-alpha-39357-src:8216:28)
(anonymous) @ index.js:61
parse @ index.js:28
(anonymous) @ index.js:38
parse @ index.js:37
getBlockAttributes @ parser.js:29
(anonymous) @ serializer.js:78
serialize @ serializer.js:68
TextEditor @ index.js:32
(anonymous) @ react-dom.js:4812
measureLifeCyclePerf @ react-dom.js:4581
_constructComponentWithoutOwner @ react-dom.js:4811
_constructComponent @ react-dom.js:4786
mountComponent @ react-dom.js:4694
mountComponent @ react-dom.js:11598
performInitialMount @ react-dom.js:4877
mountComponent @ react-dom.js:4764
mountComponent @ react-dom.js:11598
updateChildren @ react-dom.js:4396
_reconcilerUpdateChildren @ react-dom.js:10455
_updateChildren @ react-dom.js:10559
updateChildren @ react-dom.js:10546
_updateDOMChildren @ react-dom.js:6455
updateComponent @ react-dom.js:6273
receiveComponent @ react-dom.js:6235
receiveComponent @ react-dom.js:11677
_updateRenderedComponent @ react-dom.js:5260
_performComponentUpdate @ react-dom.js:5230
updateComponent @ react-dom.js:5151
receiveComponent @ react-dom.js:5053
receiveComponent @ react-dom.js:11677
_updateRenderedComponent @ react-dom.js:5260
_performComponentUpdate @ react-dom.js:5230
updateComponent @ react-dom.js:5151
performUpdateIfNecessary @ react-dom.js:5067
performUpdateIfNecessary @ react-dom.js:11709
runBatchedUpdates @ react-dom.js:12997
perform @ react-dom.js:14816
perform @ react-dom.js:14816
perform @ react-dom.js:12936
flushBatchedUpdates @ react-dom.js:13019
closeAll @ react-dom.js:14882
perform @ react-dom.js:14829
batchedUpdates @ react-dom.js:8862
batchedUpdates @ react-dom.js:12944
dispatchEvent @ react-dom.js:9260
```
</details>

### PR DESCRIPTION
**Pull request by youknowriad**
closes #434

This PR fixes the following error we're having when switching to the text editor

screen shot 2017-04-17 at 10 20 18

The problem was that we were using the `rawContent` from the block state object to serialize its attributes. And this property is no longer stored in the block state and even if it's stored , i'll be outdated.

### CODE REVIEW

File: blocks/api/serializer.js [hunk 1]
```diff
@@ -68,17 +68,18 @@ export default function serialize( blocks ) {
...
+		const saveContent = getSaveContent( settings.save, block.attributes );
 
 		return memo + (
 			'<!-- wp:' +
 			blockType +
 			' ' +
 			getCommentAttributes(
 				block.attributes,
-				getBlockAttributes( block, settings )
+				parseBlockAttributes( saveContent, settings )
```
Comment (youknowriad) [inline blocks/api/serializer.js]: This is the actual fix

**Review by ellatrix — APPROVED** [review]
Yay 👍
