### PR TITLE
Changed installFont to installFonts so that multiple font families can be installed at once

### LINKED ISSUE #58689: Font Library: allow assets upload of multiple variants from multiple font families.
## What problem does this address?
The font library is currently unable to handle file uploads of multiple font families simultaneously. If you upload multiple variants (files) of a single font family, it works as expected, but, multiple variants of multiple font families are not allowed.

image

## What is your proposed solution?
To improve the user experience around uploading font assets I think it should work the same for multiple variants of one font family or multiple variants of multiple font families.

### LINKED ISSUE #59138: "Variants from only one font family can be uploaded at a time." is a very unhelpful error message.
### Description

When uploading multiple font files, it's possible to get the error message "Variants from only one font family can be uploaded at a time".

This is really unhelpful copy for users unfamiliar with font categorization, especially when the difference between files uploaded is standard, condensed, semi-condensed, etc.

If a user attempts to upload fonts from multiple families at once, then multiple font families should be created.

While the reproduction steps below use standard & condensed fonts as an example, the same should apply across families. For example attempting to upload both Open Sans and Source Code Pro.

### Step-by-step reproduction instructions

1. Download [Open Sans from Google Fonts](https://fonts.google.com/specimen/Open+Sans) - using the Install fonts tab will not demonstrate the issue
2. Open the fonts manager > Uploads
3. Unzip the open sans download
4. Select a mix of condensed, semi-condensed and standarfd the fonts in the static folder
5. Drag them to the upload drop zone
6. the error message is displayed

### Screenshots, screen recording, code snippet

unhelpful-error

### Environment info

- WordPress 6.4
- Gutenberg trunk @ 96cb434382c2a70d991eab85ceb542b76c30a94a

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by pbking**
## What?
Refactor installation logic to not just install multiple font faces at once, but multiple font families. 

This is done so that any combination of font faces can be dropped onto the upload panel to install then all-at-once.

## Why?
Fixes: #58689
Fixes: #59138

## How?
Refactor installFont to support a collection of fontFamiles, all of which will be installed in a single user action

## Testing Instructions
Use the upload panel to upload font faces from different font families in a single action.
All of those font faces should be installed.

### CODE REVIEW

File: packages/edit-site/src/components/global-styles/font-library-modal/font-collection.js [hunk 1]
```diff
@@ -214,7 +214,7 @@ function FontCollection( { slug } ) {
 		}
 
 		try {
-			await installFont( fontFamily );
+			await installFonts( [ fontFamily ] );
```
Comment (mikachan) [inline packages/edit-site/src/components/global-styles/font-library-modal/font-collection.js:217]:
```suggestion
			await installFonts( fontFamily );
```

Only a small nitpick but I think I'd rather the `installFonts` function handled converting arguments to an array (e.g. checking if `fontFamiliesToInstall` is an array, if not then converting it), as I think it would slightly improve the readability here.

**Review by mikachan — COMMENTED** [review]
I've just tested this by trying to install two fonts from two different font families (Commissioner and Noto Serif). The fonts are installed but neither are activated:

image

Looks like they're successfully passed to `activateCustomFontFamilies` but `setFontFamilies` isn't working as expected.

File: packages/edit-site/src/components/global-styles/font-library-modal/font-collection.js (hunk 1 above)
Comment (pbking) [reply packages/edit-site/src/components/global-styles/font-library-modal/font-collection.js:217]: I'm generally opposed to passing different types of arguments into a function.  If we need to change how that value is passed to offer clarity I would rather do that (i.e. `fontFamiliesToInstall = []; fontFamiliesToInstall.push( fontFamily ); installFonts( fontFamiliesToInstall ); `

**Comment by pbking** [comment]
> Looks like they're successfully passed to activateCustomFontFamilies but setFontFamilies isn't working as expected.

This was what I spent 90% of the time working on for this feature. :/ I thought I had it lined up but I'll take another look.

**Comment by pbking** [comment]
Made a silly async error (and an even sillier length check).  The result was that it worked fine when I had breakpoints. :P Less so otherwise.

It is fixed now.  Another look would be appreciate. :)

File: packages/edit-site/src/components/global-styles/font-library-modal/font-collection.js (hunk 1 above)
Comment (mikachan) [reply packages/edit-site/src/components/global-styles/font-library-modal/font-collection.js:217]: Yeah I think that's a good alternative too 👍

**Review by mikachan — APPROVED** [review]
> Made a silly async error (and an even sillier length check). The result was that it worked fine when I had breakpoints. :P Less so otherwise.

The length check confused me when I was debugging 😆

This is working great for me now 🎉

image

**Comment by youknowriad** [comment]
I just cherry-picked this PR to the update/packages-6.5-rc1 branch to get it included in the next release: 122d14c75a
