### PR TITLE
Post Terms: Fix fatal error when 'get_the_term_list' returns 'WP_Error'

### LINKED ISSUE #65832: Fatal error when gutenberg_render_block_core_post_terms is not returning string
### Description

The `gutenberg_render_block_core_post_terms` function is supposed to return `string` and other code is expecting a string. However, the function directly returns the output of the `get_the_term_list` which may return `string|false|WP_Error`.

When a `WP_Error` is returned, there is a fatal error emitted in WordPress core's [`WP_Block::render` where the output is typecasted to string](https://github.com/WordPress/WordPress/blob/f63068d5ba5d807fae460f5d7b1a0a9de0fa4b87/wp-includes/class-wp-block.php#L537):

```
Uncaught Error: Object of class WP_Error could not be converted to string
```

IMHO, the code of the `gutenberg_render_block_core_post_terms` should check the output value of the `get_the_term_list` and eventually change the output similarly how WordPress core [handles the `WP_Error` situations when dealing with the function](https://github.com/WordPress/WordPress/blob/f63068d5ba5d807fae460f5d7b1a0a9de0fa4b87/wp-includes/category-template.php#L1460).

### Step-by-step reproduction instructions

1. Have a block rendered by the  `gutenberg_render_block_core_post_terms` on a page.
2. Make the `get_the_term_list` to return an instance of `WP_Error` (eg.: by filtering the `get_the_terms`)
3. Load the page

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WordPress 6.7 alpha, Gutenberg 19.2.0, PHP 8.1

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### PR DESCRIPTION
**Pull request by up1512001**
## What?
update the `core/post-term` `render_block_core_post_terms` function to handle `WP_Error` and not throw a fatal error.

## Why?
fixes https://github.com/WordPress/gutenberg/issues/65832

## How?
- store `get_the_term_list` as a separate variable and check if it's `WP_Error` then simply return false otherwise return actual output.

## Testing Instructions
- Add the `Terms List` block to the post.
- make `get_the_term_list` to return `WP_Error`.
- on the front end, you will not see any fatal error. 

## Screenshots or screencast 

https://github.com/user-attachments/assets/87c6cbed-beff-4a3c-8b09-8d8f9476b5da

### CODE REVIEW

File: packages/block-library/src/post-terms/index.php [hunk 1]
```diff
@@ -51,13 +51,19 @@ function render_block_core_post_terms( $attributes, $content, $block ) {
...
+	$post_terms = get_the_term_list(
 		$block->context['postId'],
 		$attributes['term'],
 		wp_kses_post( $prefix ),
 		'<span class="wp-block-post-terms__separator">' . esc_html( $separator ) . '</span>',
 		wp_kses_post( $suffix )
 	);
+
+	if ( is_wp_error( $post_terms ) ) {
+		return false;
```
Comment (Mamaduka) [inline packages/block-library/src/post-terms/index.php]:
```suggestion
		return '';
```

The render method should return an empty string. See examples above.

**Comment by Mamaduka** [comment]
Thanks for contributing, @up1512001!

Can you share a code snippet for `get_the_term_list` to return a `WP_Error`?

The issue mentions filtering the `get_the_terms`, in which case an error should be caught early, and code execution shouldn't reach `get_the_term_list`.

https://github.com/WordPress/gutenberg/blob/20f35ddd8ad178ce0ee086048fed86300fdd5267/packages/block-library/src/post-terms/index.php#L27-L30

cc @david-binda

**Comment by david-binda** [comment]
@Mamaduka sorry for the confusion on my end. The thing is that the `get_the_term_list` can return a `WP_Error` even in case the `get_the_terms` does not.

It would be the case when the `get_term_link` called from  the `get_the_term_list` would return an instance of `WP_Error`.

As I have mentioned in the related issue, checking the return value of the `get_the_term_list` is what WordPress also does.

In order to reproduce the issue I've noticed in production logs, we could filter the `get_the_terms` in following fashion:

```
add_filter( 'get_the_terms', function( $terms, $post_id, $taxonomy ) {
    if ( array_key_exists( 0, $terms ) ) {
        $terms[0] = null;
    }
    return $terms;
}, 10, 3 );
```

**Review by Mamaduka — APPROVED** [review]
Thanks for the additional details, @david-binda!

I can confirm that this fixes the bug ✅
