### PR TITLE
RTC: Fix syncing of emoji / surrogate pairs

### LINKED ISSUE #76044: RTC: [Engine] Multi-byte characters corrupted to � during real-time collaboration sync
When two users are collaboratively editing a post via RTC, emoji characters (and other multi-code-unit Unicode characters) get corrupted into � (U+FFFD replacement characters) when synced between peers.

For example, if User A types “Hello 😀 World”, User B may see “Hello � World” or other garbled output.

### PR DESCRIPTION
**Pull request by chriszarate**
## What?

When two users are collaboratively editing a post via RTC, correctly sync emoji characters and other multi-code-unit Unicode characters.

Closes https://github.com/WordPress/gutenberg/issues/76044

## Why?

The Quill Delta diff engine in `@wordpress/sync` uses `diffChars` from the `diff` library (v8.0.3). In `diff` v7+, `diffChars` uses `Intl.Segmenter` (when available) to tokenize by grapheme cluster, so an emoji like 😀 counts as `1` token. However, the `Delta Op.length()` and `OpIterator` use JavaScript’s `.length`, which counts UTF-16 code units — where the same emoji counts as `2`.

This mismatch occurs in `convertChangesToDelta()` (`packages/sync/src/quill-delta/Delta.ts`), where `component.count` from `diffChars` is used to advance the `OpIterator`. Since the iterator measures in UTF-16 code units but count is in grapheme clusters, `.substr()` calls in `OpIterator.next()` split surrogate pairs, producing lone surrogates that render as � or result in data corruption.

The same mismatch affects cursor position arithmetic in `diffWithCursor()`, where `lastDiffPosition` is tracked in grapheme clusters but `cursorAfterChange` is in UTF-16 code units.

## How?

Add a single normalization step after each call to `diffChars` that replaces `count` (grapheme clusters) with `value.length` (UTF-16 code units).

## Testing Instructions

1. Settings > Writing > Enable real-time collaboration
1. Open a post in two browser tabs as two different users.
1. In User A’s tab, type an emoji (e.g. 😀) into a paragraph block.
1. Observe User B’s tab and ensure it syncs correctly.

### Before

https://github.com/user-attachments/assets/ca306c8d-f36a-4e51-a5a0-92f99dda57b5

### After

https://github.com/user-attachments/assets/e10cf146-b372-48a3-943e-86592bb7738c

### CODE REVIEW

**Review by alecgeatches — APPROVED** [review]
Confirmed that the `trunk` implementation caused syncing issues with emojis (`�`), and that this fix addresses them.

File: test/e2e/specs/editor/collaboration/fixtures/index.ts [hunk 1]
```diff
@@ -25,6 +25,8 @@ export const test = base.extend< Fixtures >( {
 			page,
 		} );
 		await utils.setCollaboration( true );
+		// Clean up any leftover users from previous runs before creating.
```
Comment (alecgeatches) [inline test/e2e/specs/editor/collaboration/fixtures/index.ts:28]: I've run into this bug once before, thanks for the fix!

**Review by maxschmeling — APPROVED** [review]
