### PR TITLE
`PaletteEdit`: dedupe palette element slugs

### LINKED ISSUE #43197: ColorPalette: make component more resilient to color entries with same color `value` and/or `name`
## What problem does this address?

Initially flagged and discussed in #43096

While working on separate issues, I noticed that the `ColorPalette` component can receive a list `colors` where two or more color entries can have the same `value` (e.g `#ffffff`).

When this happens, currently the `ColorPalette` component is not able to correctly highlight as "selected" the color that was actually picked by the user — instead, it highlights _all_ color entries sharing that same `value` as "selected":

image

_(image taken from [this comment](https://github.com/WordPress/gutenberg/pull/43096#issuecomment-1209748181)_

Having different entries sharing the same color `value` (and potentially even the same color `name`) should be considered as a totally valid scenario:

 - Scenario n. 1: there's an entry named `Text` with value `#000000`, and another entry called `ButtonText` with value `#000000`
 - Scenario n. 2: The theme defines an entry with name `Primary` and value `#ff0000`. The user then also defines an entry with the same and same value

This means that the `ColorPalette` component _should not_ attempt to introduce any logic to alter the list of color entries in order to mitigate this issue, as that could result in an unexpected behavior to the user.

## What is your proposed solution?

While there isn't a commonly agreed solution yet, one way to look at this issue is to make sure that the data representing the color entries (passed to `ColorPalette`) is improved in a way that makes each color entry uniquely identifiable, even if it shares the same `name` and `value` as another entry (e.g. an `id` prop).

I can only imagine that this wouldn't be a trivial change, since it would involve potentially changing the schema of the data, and making sure that the `id` is generated correctly regardless of how the color is added to the list of available colors for a site (e.g. via the global styles UI, by editing theme.json...).

Since I'm not very knowledgeable about this part of the Gutenberg app, I'll let other folks chime in and discuss potential solutions (I'll keep an eye in case the conversation involves the `ColorPalette` component)

### LINKED ISSUE #49593: Global Styles - Custom Colors given the same name cannot be applied properly
### Description

If custom colors are added in the global styles theme settings with the same name (eg Color 1), it becomes impossible to select any color but the last custom color of that name.

### Step-by-step reproduction instructions

1. Start in site editor
2. Select global styles
3. Colors>Palettes>Custom Colors, add custom colors
4. Select "Show Details" in the menu for custom colors, and rename all the colors to the same name, such as "Color 1"
5. Return to the editor, and try selecting one of these custom color for any block color setting 

### Screenshots, screen recording, code snippet

**Setup**

Markup on 2023-04-04 at 13:35:31

**Result**

Markup on 2023-04-04 at 13:37:48

### Environment info

Originally reported here: https://github.com/Automattic/wp-calypso/issues/75197
Replicated in WP version 6.2 with all Gutenberg plugin active and deactivated.
Theme: Twenty Twenty-Three

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ramonjd**
## What?

Part of https://github.com/WordPress/gutenberg/issues/43197

First pass at deduping palette slugs

## Why?
The color palette uses the palette item name to generate a slug. So, `Test 1` will be `custom-test-1`.

If there are identical names, the slugs would normally be the same. Slugs should be unique identifiers so they can be correctly applied as CSS vars.

## How?
When updating palette item names, check for duplicate slugs. If duplicates are found, update those slugs.

## Testing Instructions

In _Site Editor > Global Styles > Colors > Palette_ create multiple custom colors and gradients.

Give all or some of each the same name. 

Save and try to apply your custom colors in the editor.

They should work in the front and backend.

## Screenshots or screencast 

Given a series of duplicate names:

Screenshot 2024-10-01 at 4 44 13 pm

The custom palette is still operable due to unique slugs:

https://github.com/user-attachments/assets/617cf731-e39d-487c-bd27-8113af143092

Which are saved to global styles and output in the frontend

Screenshot 2024-10-01 at 4 45 59 pm

### CODE REVIEW

File: packages/components/src/palette-edit/index.tsx [hunk 1]
```diff
@@ -70,6 +70,29 @@ function NameInput( { value, onChange, label }: NameInputProps ) {
...
+/*
+ * Deduplicates the slugs of the provided elements.
+ */
+export function deduplicateElementSlugs< T extends PaletteElement >(
+	elements: T[]
+): T[] {
+	const slugCounts: { [ slug: string ]: number } = {};
+	const updatedElements = elements.map( ( element: T ) => ( {
+		...element,
+	} ) ) as T[];
```
Comment (aaronrobertshaw) [inline packages/components/src/palette-edit/index.tsx]:
```suggestion
	const updatedElements = elements.map( ( element: T ) => ( {
		...element,
	} ) );
```

I'm no TypeScript expert but I think the `T[]` type here for `updatedElements` can be inferred.

File: packages/components/src/palette-edit/index.tsx [hunk 2]
```diff
@@ -70,6 +70,29 @@ function NameInput( { value, onChange, label }: NameInputProps ) {
...
+
+	updatedElements.forEach( ( element, index ) => {
+		const { slug } = element;
+		slugCounts[ slug ] = ( slugCounts[ slug ] || 0 ) + 1;
+
+		if ( slugCounts[ slug ] > 1 ) {
+			element.slug = `${ slug }-${ index }`;
```
Comment (aaronrobertshaw) [inline packages/components/src/palette-edit/index.tsx]:
```suggestion
			element.slug = `${ slug }-${ slugCounts[ slug ] - 1 }`; 
```

If `deduplicateElementSlugs` is intended to be reusable as a utility, would it be more robust to leverage the `slugCounts` value rather than the array index when deduping? 

The idea is to ensure consistent, predictable, behaviour, even if the input array contains elements that have been deleted or rearranged. Using `index` might produce inconsistent slug suffixes otherwise.

Obviously, this is only a minor nit thinking about whether this util could be exposed publicly in the future. Feel free to take it or leave it 🤷

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for fixing this one @ramonjd, I'm sure it was annoying for people maintaining color palettes 👍 

This PR tests well for me. I didn't run into any issues and only left a couple of very minor nits as inline comments.

✅ Custom colors with various duplicate slugs now work
✅ Same for custom gradients
✅ Duplicate named colors work both frontend and in the editors (site/post)

LGTM 👍 

https://github.com/user-attachments/assets/7ec17c5d-e5cd-4aca-95d6-da5f4e1fd21d

File: packages/components/src/palette-edit/index.tsx (hunk 1 above)
Comment (ciampo) [reply packages/components/src/palette-edit/index.tsx]: Yup, that's correct!

Even the `T` type for the `element` argument is unnecessary, TypeScript is able to infer it from the `elements` array.

I would go a step further and suggest this simplification to the code, which removes the need for making the `updatedElements` copy:

```tsx
	const slugCounts: { [ slug: string ]: number } = {};

	return elements.map( ( element, index ) => {
		let newSlug: string | undefined;

		const { slug } = element;
		slugCounts[ slug ] = ( slugCounts[ slug ] || 0 ) + 1;

		if ( slugCounts[ slug ] > 1 ) {
			newSlug = `${ slug }-${ index }`;
		}

		return { ...element, slug: newSlug ?? slug };
	} );
```

File: packages/components/src/palette-edit/index.tsx (hunk 2 above)
Comment (ciampo) [reply packages/components/src/palette-edit/index.tsx]: Agreed. We could also think about moving the `slugCounts` outside of the function, so that it persists across multiple calls.

Separately, if we wanted to be even more robust, we could add a unique slug through the `useId` hook as well.

File: packages/components/src/palette-edit/index.tsx [hunk 3]
```diff
@@ -70,6 +70,29 @@ function NameInput( { value, onChange, label }: NameInputProps ) {
 	);
 }
 
+/*
+ * Deduplicates the slugs of the provided elements.
+ */
+export function deduplicateElementSlugs< T extends PaletteElement >(
+	elements: T[]
+): T[] {
```
Comment (ciampo) [inline packages/components/src/palette-edit/index.tsx]: No need to specify a return type, TypeScript will infer it automatically

```suggestion
) {
```

File: packages/components/src/palette-edit/index.tsx [hunk 4]
```diff
@@ -70,6 +70,29 @@ function NameInput( { value, onChange, label }: NameInputProps ) {
 	);
 }
 
+/*
+ * Deduplicates the slugs of the provided elements.
+ */
+export function deduplicateElementSlugs< T extends PaletteElement >(
```
Comment (ciampo) [inline packages/components/src/palette-edit/index.tsx:75]: Not really related to the changes in this PR, but I noticed that the `PaletteElement` type is `Color | Gradient`. There are multiple mentions of `Color | Gradient` in the file — so I think, for better consistency, we should either replace those instances with `PaletteElement`, or replace `PaletteElement` with `Color | Gradient`.

Comment (aaronrobertshaw) [reply packages/components/src/palette-edit/index.tsx:75]: Switched over `Color | Gradient` to `PaletteElement` in [7e66c86](https://github.com/WordPress/gutenberg/pull/65772/commits/7e66c861345dfaaad0872810f203f467c92cf787). If people would prefer the other way around it can be a separate follow-up.

File: packages/components/src/palette-edit/index.tsx (hunk 3 above)
Comment (aaronrobertshaw) [reply packages/components/src/palette-edit/index.tsx]: Done via https://github.com/WordPress/gutenberg/pull/65772/commits/67e1d75282d0c316e462478b19245c8405010ec6

File: packages/components/src/palette-edit/index.tsx (hunk 2 above)
Comment (aaronrobertshaw) [reply packages/components/src/palette-edit/index.tsx]: Done via [526fc89](https://github.com/WordPress/gutenberg/pull/65772/commits/526fc896f3266c3f2ef443b1b34c5b500a5fab08).

I'll leave it up to @ramonjd though whether he wants to go the extra mile for `useId` etc.

File: packages/components/src/palette-edit/index.tsx (hunk 1 above)
Comment (aaronrobertshaw) [reply packages/components/src/palette-edit/index.tsx]: Good idea, thanks!

Done via [67e1d75](https://github.com/WordPress/gutenberg/pull/65772/commits/67e1d75282d0c316e462478b19245c8405010ec6)

**Comment by aaronrobertshaw** [comment]
I believe I've addressed the remaining feedback. 

@ramonjd should be back online later next week but if you're happy enough with this PR @ciampo, it might be a nice one to land and get included in the next 6.7 beta. What do you think?

**Comment by ciampo** [comment]
Sounds good! I rebased, fixed conflicts, and will merge as soon as CI is green

**Comment by ciampo** [comment]
> it might be a nice one to land and get included in the next 6.7 beta

@aaronrobertshaw I tried but there's a conflict when merging. I'm about to go offline for the week — would you be able to take care of manually backporting when you're back offline? Otherwise I'll do it myself when I come back online on Monday

**Comment by ciampo** [comment]
Manual backport https://github.com/WordPress/gutenberg/pull/65905
