### PR TITLE
Latest Posts: Fix selected category on existing blocks

### LINKED ISSUE #21357: Latest Posts: Category restriction not working on existing blocks
**Describe the bug**

An existing Latest Posts block that shows posts from a category no longer filters the category, it shows all posts. Previous GB versions saved the category as a string, but the change in #20781 switched this to an array.

**To reproduce**

1. Using Gutenberg 7.7.1 (or other previous version), add a Latest Posts block with a selected category
2. Update to master, view your post — it's no longer respecting the category restriction
3. On the frontend, you get a PHP warning: `array_column() expects parameter 1 to be array, string given in /var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/latest-posts.php on line 50`
4. Switch into the editor, your category is no longer selected (and the attribute is removed, since it's invalid)

### PR DESCRIPTION
**Pull request by ryelle**
## Description

Fixes #21357 — The selected category attribute in Latest Posts was changed to an array, but no upgrade path was added for existing blocks. This caused problems on the frontend and in the editor, so this PR attempts to fix those. For the frontend, add an `array` check before using the categories attribute, and handle the non-array case. For the editor, I've added a deprecation that should kick in if categories is a string, which will convert categories into the array-of-objects format it expects.

This migration ideally needs the whole category object, as right now it displays the selected category as an empty token — would appreciate suggestions on this.
Screen Shot 2020-04-02 at 12 32 46 PM

## To test

1. Add a Latest Posts block with GB 7.7.1 or below, then check out & build this branch
2. View your post, it should show only that category of posts
3. Switch to the editor, again it should only show that category of posts in the preview
4. Click the block, and look at the selected categories — it should have a token (though empty now, see above)

## Types of changes

Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by youknowriad** [comment]
Do you know If this bug is present on WP 5.4 too? (whether to add the "backport" label or not)

**Comment by ryelle** [comment]
@youknowriad No, it looks like 5.4 doesn't have the muli-select category feature, so it isn't an issue.

**Comment by draganescu** [comment]
Hi @ryelle and thank you for fixing this. This PR keeps the category filter in place.

I tested and, aside from the empty label in the category list, following the steps you provided, I now see `Notice: Undefined index: items in /var/www/html/wp-includes/rest-api.php on line 1262 ` on the frontend on the page that has the filtered LatestPosts block. 

The editor also shows up the same error. I'm trying to track this down as well :) as it was reported by @bph in #21550

**Comment by aduth** [comment]
>This migration ideally needs the whole category object, as right now it displays the selected category as an empty token — would appreciate suggestions on this.

While I can see that it would make the UI easier to implement if the full objects were immediately available, I believe the category ID is enough to be able to get these details from the REST API. To me, the attribute data should include the minimal data necessary to be able to reconstruct the block. Or, at least, all the rest of these details can be considered redundant if the ID is known, and redundancy may lead to excessive storage and risk of desync. The second of these is more concerning since, for example, details about the category can change while the ID remains static (including the label).

From my understanding of #20781, if all that was needed to support multi-select was the storage of the category ID, then I think ideally the attribute would be an array of numbers. Generally I'd discourage the use of schemaless object attributes whenever possible, as the lack of a well-defined and enforced structure can be a source of bugs (gallery block comes to mind).

That all being said, the changes here do seem sensible given the current state of the block, and assuming that this has already shipped in a version of the plugin, this would still be necessary regardless if there's a future change in direction to how the attribute is stored.

To the bug itself of the empty label, given all of the above, my ideal implementation would be one where the suggestions passed to the token field are constructed based on entities fetched from the API corresponding to the ID of the category.

There appears to be some prior art of this in the Post Tags block:

https://github.com/WordPress/gutenberg/blob/f73151e2bc1776016ed873495bf638c0a59b9b30/packages/block-library/src/post-tags/edit.js#L14-L15

File: packages/block-library/src/latest-posts/index.php [hunk 1]
```diff
@@ -173,3 +173,34 @@ function register_block_core_latest_posts() {
...
+ * is removed.
+ *
+ * @param array $block A single parsed block object.
+ *
+ * @return array The migrated block object.
+ */
+function block_core_latest_posts_migrate_categories( $block ) {
+	if (
+		'core/latest-posts' === $block['blockName'] &&
+		isset( $block['attrs']['categories'] ) &&
```
Comment (aduth) [inline packages/block-library/src/latest-posts/index.php:196]: I believe it may not be safe to assume `$block['attrs']` is set, given that in the implementation of `render_block`, its presence is checked _after_ the `render_block_data` filter we're hooking here.

https://github.com/WordPress/wordpress-develop/blob/90b0f49/src/wp-includes/blocks.php#L481-L483

I'm not actually sure when (or if) this can occur, since as best I can tell from the implementation of the block parsing, it always attempts to assign a value for a block:

https://github.com/WordPress/wordpress-develop/blob/90b0f49/src/wp-includes/class-wp-block-parser.php#L440-L446

A simple alternative to consider is `empty`, which is unique in that it will happily accept any input (e.g. `empty( $block['this']['definitely']['doesnt']['exist'] )`). Assuming we're only wanting to deal with a non-empty-string value of `categories`, this could be:

```suggestion
		! empty( $block['attrs']['categories'] ) &&
```

**Review by draganescu — COMMENTED** [review]
This comment was for 16169. Sorry.

**Review by draganescu — COMMENTED** [review]
I tested this locally and with @ryelle 's and @mcsf 's updates this fixes both #21357 and #21550, the only remaining issue is the empty category label after migration.

**Comment by mcsf** [comment]
> the only remaining issue is the empty category label after migration

Let's address it separately.

**Review by draganescu — APPROVED** [review]
This fixes two open issues, works as expected and it further removes some code duplication as well. Let's merge it.

**Comment by ryelle** [comment]
@mcsf's changes are working great in testing, if the empty category label isn't necessary for this PR, is it ready to merge?

**Comment by Jan-Jacobs** [comment]
Sad to see this wasn't added in the [8.6.0 release](https://github.com/WordPress/gutenberg/releases/tag/v8.6.0).
Is there any ETA for this fix to be released?

**Comment by mcsf** [comment]
> Sad to see this wasn't added in the [8.6.0 release](https://github.com/WordPress/gutenberg/releases/tag/v8.6.0).
> Is there any ETA for this fix to be released?

This PR was merged in April, landing in Gutenberg 8.0.

**Comment by JJ-Coding** [comment]
> > Sad to see this wasn't added in the [8.6.0 release](https://github.com/WordPress/gutenberg/releases/tag/v8.6.0).
> > Is there any ETA for this fix to be released?
> 
> This PR was merged in April, landing in Gutenberg 8.0.

Oh, my bad then. I still have this issue on the latest Gutenberg release & WordPress release.
Or is this only going to be added once WordPress releases v5.5?

(Apologies if this isn't the right place for asking these questions - this seemed to be the only place where I could find anything about this bug.)

**Comment by draganescu** [comment]
Howdy @JJ-Coding  - this is the best place! If you install the _Gutenberg plugin_ you should have the update ready. If you use the default Gutenberg shipped with WordPress 5.4 (which is Gutenberg 7.5) you will have to wait for WordPress 5.5 to get the update.

**Comment by mcsf** [comment]
I re-tested on the latest Gutenberg version and found no issues with this. For the record, I tested with the following deprecated content:

```html
<!-- wp:latest-posts {"categories":"6"} /-->
```

**Comment by JJ-Coding** [comment]
> Howdy @JJ-Coding - this is the best place! If you install the _Gutenberg plugin_ you should have the update ready. If you use the default Gutenberg shipped with WordPress 5.4 (which is Gutenberg 7.5) you will have to wait for WordPress 5.5 to get the update.

Hey @draganescu ! Thanks for confirming that I'm not posting in the wrong place - I'd rather not be _that guy_... 

I've got the latest Gutenberg plugin installed (v8.6.0) but I'm still experiencing this problem it seems.

Just now I copied @mcsf 's code and pasted it into my page and then updated the page. Once the updating was finished I reloaded the editing page and the code that I had pasted in turned into:
`<!-- wp:latest-posts /-->`

So it seems to just remove the categories code completely when it updates.
Any idea what could cause this strange behaviour? (A plugin perhaps?)

Thanks for the quick responses by the way! I really appreciate the help.

**Comment by JJ-Coding** [comment]
> > Howdy @JJ-Coding - this is the best place! If you install the _Gutenberg plugin_ you should have the update ready. If you use the default Gutenberg shipped with WordPress 5.4 (which is Gutenberg 7.5) you will have to wait for WordPress 5.5 to get the update.
> 
> Hey @draganescu ! Thanks for confirming that I'm not posting in the wrong place - I'd rather not be _that guy_...
> 
> I've got the latest Gutenberg plugin installed (v8.6.0) but I'm still experiencing this problem it seems.
> 
> Just now I copied @mcsf 's code and pasted it into my page and then updated the page. Once the updating was finished I reloaded the editing page and the code that I had pasted in turned into:
> `<!-- wp:latest-posts /-->`
> 
> So it seems to just remove the categories code completely when it updates.
> Any idea what could cause this strange behaviour? (A plugin perhaps?)
> 
> Thanks for the quick responses by the way! I really appreciate the help.

Alright - I've disabled all my plugins and added the code on a seperate test page. That seems to do the trick. 
I'm just going to assume there's some misbehaving plugin which doesn't like categories on the latest post block.

Consider my question solved. Thanks again for the responses @draganescu & @mcsf !
