### PR TITLE
Standardise and fix parsing and serialization of blocks and nav menu items

### LINKED ISSUE #29793: Navigation Editor: Navigation links added to menu only preserve url and label attributes
I'm not sure if this is intentional or not, but we only preserve the label and url attributes of a navigation link, when we save this in the navigation editor.

This means saving in the navigation editor is a bit lossy. For example, draft links will render on the frontend because id and type is not available to check. This may also be an issue for any future functionality that's added to navigation links.

Post links and other types of links added in customer or nav-menu also lose information when saved in the navigation editor and get turned into custom links.

#### Enabling the Navigation Editor

To enable the Navigation Editor:
- Install and activate the Gutenberg plugin
- Visit experiments /wp-admin/admin.php?page=gutenberg-experiments
- Check "Enable Navigation screen" and save
Screen Shot 2021-03-11 at 9 56 52 AM

### Post links from customizer/nav menu turning into custom links

https://user-images.githubusercontent.com/1270189/110835076-318aab80-8253-11eb-9aeb-22a4057bc42b.mp4

- Add a post link in customizer (/wp-admin/customize.php) or menu nav (/wp-admin/nav-menus.php) and save
- Load the menu in the Navigation Editor (/wp-admin/admin.php?page=gutenberg-navigation) and Save
- Load it again in customizer or menu nav

Expected: Menu contains a single post link
Actual: Menu contains a custom link

### Losing Properties When Loading a Menu into the Navigation Block

https://user-images.githubusercontent.com/1270189/110828911-6b0be880-824c-11eb-866b-53431a063559.mp4

As a quick example here's a navigation block loaded from a menu:
```
<!-- wp:navigation {"orientation":"horizontal"} -->
<!-- wp:navigation-link {"label":"Metal Cats","url":"http://wordpress.local/metal-cats/"} /-->
<!-- /wp:navigation -->
```

And here's one built in the post editor:
```
<!-- wp:navigation {"orientation":"horizontal"} -->
<!-- wp:navigation-link {"label":"Metal Cats","type":"post","id":43,"url":"http://wordpress.local/metal-cats/"} /-->
<!-- /wp:navigation -->
```

If I spotted this correctly serialization/hydration occurs in:

https://github.com/WordPress/gutenberg/blob/b7f341628facdc4b5c46aaf9c8745039dc6aa774/packages/edit-navigation/src/store/utils.js#L132-L147
https://github.com/WordPress/gutenberg/blob/b7f341628facdc4b5c46aaf9c8745039dc6aa774/packages/edit-navigation/src/store/resolvers.js#L146-L155
We might also need server changes if menu items cannot save arbitrary properties.

### PR DESCRIPTION
**Pull request by getdave**
## Description
Aims to fix https://github.com/WordPress/gutenberg/issues/29793.

This PR does two things:

1. Updates the Nav Editor _and_ Nav Block to create the correct `core/navigation-link` block variations based on the menu item data from the database.
2. Correctly converts the blocks back to matching nav menu objects for storage in the database, preserving the data necessary to ensure they:
  - can be converted back into the correct `core/navigation-link` block _variation_.
  - have the correct object id assigned to match the entity ID which they represent (eg: a `Post` or a `Page`...etc).

### Known Bugs

**Note** in the process of working on this PR I've uncovered a few more bugs which I won't attempt to fix in this PR lest it get too large. I'm noting for future reference here:
* Post type variations display as `Post link
` in the block sidebar ([screenshot](https://user-images.githubusercontent.com/444434/115868981-266f9180-a435-11eb-8707-ac75528d7ad2.png)). They should probably use the title of the Custom Post Type (eg: `Portfolio link`)
* There is no post type variation for `Post Type Archive` as a result these are saved as `Custom`. We need a new variation to be created. [Here's how you add a `Post Type Archive` to a menu](https://www.wpbeginner.com/wp-tutorials/how-to-add-post-type-archive-in-wordpress-navigation-menus/). See https://github.com/WordPress/gutenberg/issues/31452
* ~Other attributes aren't always parsed/serialized correctly from block -> menuItem and menuItem -> block (eg: `attr_label`...etc). Once this PR is merged, we need to audit these and write some automated tests to ensure they are adding to the mapping for conversion.~ **Update**: this is now resolved as part of this PR.
* Post Format's save as `Custom` because the REST API endpoint for `v2/search` doesn't return numeric IDs for the post formats. See https://github.com/WordPress/gutenberg/issues/31380

### Setup
* Install this Plugin on your local env https://wordpress.org/plugins/portfolio-post-type/ and activate.
* Create some Posts, Pages and Categories - I used FakerPress plugin.
* Create some Portfolio items, Portfolio Categories and Porfolio Tags - I used FakerPress plugin.
* Create a menu at http://localhost:8889/wp-admin/nav-menus.php and populate with a mixture of:
  - Posts
  - Pages
  - Categories
  - Tags
  - Custom Links
  - Portfolio posts.
  - Portfolio Categories
  - Portfolio Archive ([here's how you do that](https://www.wpbeginner.com/wp-tutorials/how-to-add-post-type-archive-in-wordpress-navigation-menus/))
* Save your Menu!

### Test
* Open the Navigation editor at http://localhost:8889/wp-admin/admin.php?page=gutenberg-navigation.
* You should see the nav menu appear and all the `core/navigation-link`s should appear with the correct block variation (eg: `Post Link, `Page Link`, `Custom`...etc. There are a few known exceptions that don't work which - given that they have _never_ worked - I will tackle in a follow up. These are:
  - `Post Type Archive` this will not work because we don't have a variation setup for this yet.
  - Post Type Categories (eg: anything you created under `Portfolio Categories` will show up with the block variation name being `Category`. This needs fixing.
* Save your Navigation - this will resave all the items that are currently blocks in the Navigation Editor back to menu items in the database. This will expose any saving errors.
* Go back to the old Menus page at http://localhost:8889/wp-admin/nav-menus.php.
* Check the menu items have been correctly persisted and retained their original "types". 

### Menu -> Nav Editor -> Menu
https://user-images.githubusercontent.com/444434/115868532-8154b900-a434-11eb-9c04-03846ff0fd91.mov

### Menu -> Nav Block

https://user-images.githubusercontent.com/444434/115868720-c973db80-a434-11eb-9f43-71a97716d5d6.mov

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-library/src/navigation-link/hooks.js [hunk 1]
```diff
@@ -46,7 +46,11 @@ export function enhanceNavigationLinkVariations( settings, name ) {
 	// Otherwise decorate server passed variations with an icon and isActive function
 	if ( settings.variations ) {
 		const isActive = ( blockAttributes, variationAttributes ) => {
-			return blockAttributes.type === variationAttributes.type;
+			const normalizedVariationKind = variationAttributes.kind.replace(
```
Comment (getdave) [inline packages/block-library/src/navigation-link/hooks.js]: I'm not clear why we have two versions of this code...

File: packages/block-library/src/navigation-link/fallback-variations.js [hunk 2]
```diff
@@ -58,8 +58,14 @@ const fallbackVariations = [
...
-	variation.isActive = ( blockAttributes, variationAttributes ) =>
-		blockAttributes.type === variationAttributes.type;
+
+	variation.isActive = ( blockAttributes, variationAttributes ) => {
+		const normalizedVariationKind = variationAttributes.kind.replace(
+			'-',
+			'_'
+		);
+		return blockAttributes.type === normalizedVariationKind;
+	};
```
Comment (talldan) [inline packages/block-library/src/navigation-link/fallback-variations.js]: I'm not sure comparing the kind to the type like this will work (e.g. for a post the kind is `postType` and the type `post`).

What was the problem that required this change?

File: packages/block-library/src/navigation-link/hooks.js (hunk 1 above)
Comment (talldan) [reply packages/block-library/src/navigation-link/hooks.js]: I think the fallback variations will be removed in a later WP version, they're being kept for back compat.

File: packages/block-library/src/navigation-link/fallback-variations.js (hunk 2 above)
Comment (getdave) [reply packages/block-library/src/navigation-link/fallback-variations.js]: Thanks for calling this out. Turns out I needed to be storing/retrieveing data from the `object` field instead. With that change we can now revert both the variations `isActive` comparisons to how they were previously.

**Comment by getdave** [comment]
I've realised this is more complex than I thought.

Essentially we have x2 fields on the `nav_menu_item` coming from the database

1. `type` - can either be: `post_type`, `post_type_archive`, `taxonomy` (otherwise it falls back to `custom`).
2. `object`  - refers to the _specific_ object type eg: `post`, `page`.

We also have `object_id` which is a reference to the ID of the `object`. This is currently mapped to the `block.attributes.id` field.

On our `core/navigation-link` block we have:

1. `type` - this PR updates it to map to the `object` field.
2. `kind` - this sort of maps to the `type` field on the `nav_menu_item` but the format is different.

I think we need to update everything as follows:

* Update `type` to map 1:1 from block to `nav_menu_item` object.
* Add a new `object` attribute to the `block.attirbutes` that maps 1:1 with the `object` field on the `nav_menu_item`.
* Update the variations so that the variation is matched against the `object` type which is the most specific identifier to the "type" of the item.

I'll dive into this again tomorrow.

**Comment by getdave** [comment]
Watch out for 

1. post formats. testing instructoins in https://github.com/WordPress/gutenberg/pull/29692
2. post type archives - https://www.wpbeginner.com/wp-tutorials/how-to-add-post-type-archive-in-wordpress-navigation-menus/

File: packages/block-library/src/navigation-link/hooks.js (hunk 1 above)
Comment (gwwar) [reply packages/block-library/src/navigation-link/hooks.js]: The fallback is only used for versions of WP 5.7 and below. Using WP 5.8+ variations are provided by navigation-link in `register_block_type_from_metadata`

https://github.com/WordPress/gutenberg/blob/e65038afdf575eede1b6ebde37afd18e977b1c0d/packages/block-library/src/navigation-link/index.php#L293-L333

We'll be able to remove the entire hook.js file, after [`isActive` supports an array of strings](https://github.com/WordPress/gutenberg/pull/30913) as option, icons map to a string, AND the when the gutenberg plugin moves past <= 5.7 support.

**Comment by gwwar** [comment]
> On our core/navigation-link block we have:

Leaving a brain dump of the current values. I think all props are optional (we render placeholders in the editor). Some older data might be missing `kind` information.

`label` : This the text value of the link. May contain rich text formatting.
`type` :  `{ 'post' | 'page' | 'category' | 'tag' }` or `$taxonomy->name` or `$post_type->name` for a CPT. Note the exception for `tag` instead of `post_tag`.
`description`: Menu description if the theme supports it
`rel`: link rel, see https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types
`id`: term id OR post id. Also an optional attribute.
`opensInNewTab`: sets link `target="_blank"`
`url`: link url is set even if we have enough information to generate this, for example having an id, type and kind value. This is probably open for iteration. (A custom link is simply a label+url set, but we can be more explicit in noting the custom type in `kind`.)
`title`: the [title attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) set on a link
`kind`: `{ 'post-type' | 'taxonomy' }` `post-format` is also passed around in the kind variable internally, but doesn't get serialized. We're likely missing `post_type_archive` support.

https://github.com/WordPress/gutenberg/blob/ee84e9447f3f148684d29573558a69314b90274e/packages/block-library/src/navigation-link/block.json#L1-L35

**Comment by gwwar** [comment]
I think we have some flexibility in the data formats, what might help drive this is adding unit test cases for our common scenarios. If it makes sense, I think we'll want three suites:

- MenuData -> MenuData ( Are values retained when I save in the navigation editor? This is especially noticeable when going from customizer/old menu editor -> navigation editor  )
- MenuData-> NavigationLink (When I load a menu in the site/post editor using the navigation block).
- NavigationLink -> MenuData (A user started from a named menu in the site/post editor, we then edit the menu in the navigation editor).

Each suite would likely cover cases like:
- Custom Links
- PostType/Taxonomy Links
- Tag test for the hardcoded value
- Drafts
- Home Link (Might need to wait for this to be fully implemented/a bit further along).

**Comment by getdave** [comment]
Currently working on fixing the e2e tests.

**Comment by getdave** [comment]
Still working through the e2e tests and fixing issue with `id` attribute being persisted for links with `custom` type.

File: packages/block-library/src/navigation/placeholder.js [hunk 3]
```diff
@@ -56,6 +56,12 @@ function mapMenuItemsToBlocks( menuItems ) {
 				? __( '(no title)' )
 				: menuItem.title.rendered,
 			opensInNewTab: menuItem.target === '_blank',
+			type: menuItem?.object,
+			...( menuItem?.object !== 'custom' && {
```
Comment (getdave) [inline packages/block-library/src/navigation/placeholder.js]: Only set id if it's an entity type (ie: not the `custom` type).

File: packages/e2e-tests/specs/experiments/__snapshots__/navigation-editor.test.js.snap [hunk 4]
```diff
@@ -10,36 +10,36 @@ exports[`Navigation editor allows creation of a menu when there are no current m
...
 <!-- /wp:navigation-link -->
 <!-- /wp:navigation-link -->
 <!-- /wp:navigation-link -->
 
-<!-- wp:navigation-link {\\"label\\":\\"WordPress.org\\",\\"description\\":\\"\\",\\"rel\\":\\"\\",\\"url\\":\\"https://wordpress.org\\",\\"title\\":\\"\\",\\"className\\":\\"\\"} -->
-<!-- wp:navigation-link {\\"label\\":\\"Google\\",\\"description\\":\\"\\",\\"rel\\":\\"\\",\\"url\\":\\"https://google.com\\",\\"title\\":\\"\\",\\"className\\":\\"\\"} /-->
+<!-- wp:navigation-link {\\"label\\":\\"WordPress.org\\",\\"type\\":\\"custom\\",\\"description\\":\\"\\",\\"rel\\":\\"\\",\\"id\\":108,\\"url\\":\\"https://wordpress.org\\",\\"title\\":\\"\\",\\"kind\\":\\"custom\\",\\"className\\":\\"\\"} -->
+<!-- wp:navigation-link {\\"label\\":\\"Google\\",\\"type\\":\\"custom\\",\\"description\\":\\"\\",\\"rel\\":\\"\\",\\"id\\":109,\\"url\\":\\"https://google.com\\",\\"title\\":\\"\\",\\"kind\\":\\"custom\\",\\"className\\":\\"\\"} /-->
 <!-- /wp:navigation-link -->
 <!-- /wp:navigation -->"
```
Comment (getdave) [inline packages/e2e-tests/specs/experiments/__snapshots__/navigation-editor.test.js.snap]: All changes due to setting of block attributes when converting from menus.

File: packages/e2e-tests/specs/experiments/blocks/__snapshots__/navigation.test.js.snap [hunk 5]
```diff
@@ -2,36 +2,36 @@
...
 <!-- /wp:navigation-link -->
 <!-- /wp:navigation-link -->
 
-<!-- wp:navigation-link {\\"label\\":\\"WordPress.org\\",\\"url\\":\\"https://wordpress.org\\"} -->
-<!-- wp:navigation-link {\\"label\\":\\"Google\\",\\"url\\":\\"https://google.com\\"} /-->
+<!-- wp:navigation-link {\\"label\\":\\"WordPress.org\\",\\"type\\":\\"custom\\",\\"url\\":\\"https://wordpress.org\\",\\"kind\\":\\"custom\\"} -->
+<!-- wp:navigation-link {\\"label\\":\\"Google\\",\\"type\\":\\"custom\\",\\"url\\":\\"https://google.com\\",\\"kind\\":\\"custom\\"} /-->
 <!-- /wp:navigation-link -->
 <!-- /wp:navigation -->"
 `;
```
Comment (getdave) [inline packages/e2e-tests/specs/experiments/blocks/__snapshots__/navigation.test.js.snap:37]: Changes due to setting block attributes such as `id` on entity block variations (eg: `Page`, `Category`) that need to store a reference to the database object which they represent.

**Comment by getdave** [comment]
@gwwar I think this is now in a better place. Note the PR description which now has various caveats which were required to keep this PR size down. I'd really appreciate another review, particularly around Custom Post Types and how we can add some tests to cover these.

**Comment by Mamaduka** [comment]
Hi, @getdave

I followed your testing instructions. I can see that original menu item types are correctly retained when saving the menu in the experimental editor. 🎉 

I see "Custom Link" variation for the following menu item types: "Tag," "Portfolio Item," "Portfolio Category," "Portfolio Tag." I expected those to be "Category Link" and "Post Link" based on your screencast.

**Comment by getdave** [comment]
Thank you for the review 👍 

> I see "Custom Link" variation for the following menu item types: "Tag," "Portfolio Item," "Portfolio Category," "Portfolio Tag." I expected those to be "Category Link" and "Post Link" based on your screencast.

~Let me check those again. I might have broken something.~

@Mamaduka I checked and I found that saving in the Navigation Editor preserve the types for the custom `Portfolio Item/Category/Tag`.


https://user-images.githubusercontent.com/444434/116268911-a8cdbd80-a775-11eb-8ca7-c606cccf9498.mov

Did I miss something?

**Comment by gwwar** [comment]
> Post type variations display as Post link in the block sidebar (screenshot). They should probably use the title of the Custom Post Type (eg: Portfolio link)

These are new post type labels `item_link` and `item_link_description` and should be added during CPT registration. If we glue together two translated strings, the translation is often very poor for specific languages. CPTs with missing labels fallback to the default post or category label.

**Comment by gwwar** [comment]
We can probably cover pieces of this in a follow up PRs but wanted to note some extra options in the old menu editor (hiding under screen options):

Screen Shot 2021-04-27 at 9 31 19 AM

Currently open in new tab doesn't appear to reflect between the two old menu nav/navigation editor:

| menu editor | navigation editor |
|-----|-----|
| Screen Shot 2021-04-27 at 9 31 07 AM | Screen Shot 2021-04-27 at 9 35 33 AM |

**Comment by getdave** [comment]
> We can probably cover pieces of this in a follow up PRs but wanted to note some extra options in the old menu editor (hiding under screen options):
> 
> Screen Shot 2021-04-27 at 9 31 19 AM
> 
> Currently open in new tab doesn't appear to reflect between the two old menu nav/navigation editor:
> 
> menu editor	navigation editor
> Screen Shot 2021-04-27 at 9 31 07 AM	Screen Shot 2021-04-27 at 9 35 33 AM

Agreed 👍 I will definitely be covering those in a separate PR to avoid this one getting too large. Thus PR adds the mechanics and fixes the immediate Issue. Follows will tie this all together.

File: packages/block-library/src/navigation/placeholder.js (hunk 3 above)
Comment (gwwar) [reply packages/block-library/src/navigation/placeholder.js]: Minor: It looks like we're trying to avoid adding an id prop. When menuItem.object is undefined this will set `id` to undefined. Eg `{ id:undefined }` instead of `{}`

File: packages/block-library/src/navigation/placeholder.js [hunk 6]
```diff
@@ -56,6 +56,12 @@ function mapMenuItemsToBlocks( menuItems ) {
...
+				id: menuItem?.object_id,
+			} ),
+			// the equivalent on `nav_menu_item` is "type" but it is stored with underscores whereas the block attr uses hyphens.
+			kind: menuItem.type.replace( '_', '-' ),
```
Comment (gwwar) [inline packages/block-library/src/navigation/placeholder.js]: 🐍 snake vs kebab case. Are values here going to be `post-type`, `taxonomy` and now `custom`? Should the navigation block now also set the `custom` type?

Note that while the custom link variation is an option in the block editor, this really means that we don't set initial search parameters. Folks might end up adding a custom link or a specific type like a post link.

File: packages/edit-navigation/src/store/utils.js [hunk 7]
```diff
@@ -172,3 +187,85 @@ export function computeCustomizedAttribute(
...
 }
+
+/**
+ * Maps a given block attribute to its equivalent menu item field.
+ *
+ * @param {string} blockAttributeName the name of the block attribute to be mapped.
+ * @param {string} blockAttributeValue the value of the block attribute to be mapped.
+ * @return {Object} block attribute mapped to correct menu item.
+ */
+export const mapBlockAttributeToMenuItemField = function mapBlockAttributeToMenuItemField(
```
Comment (gwwar) [inline packages/edit-navigation/src/store/utils.js]: Minor: What benefits do we get from using a named function expression here?

Screen Shot 2021-04-27 at 1 44 52 PM

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name

File: packages/edit-navigation/src/store/utils.js [hunk 8]
```diff
@@ -172,3 +187,85 @@ export function computeCustomizedAttribute(
...
+		id: 'object_id',
+		type: 'object',
+		// `nav_menu_item` may be one of:
+		// 1. `post_type`,
+		// 2. `post_type_archive`,
+		// 3. `taxonomy`,
+		// 4. `custom`.
+		kind: {
+			attr: 'type', // the equivalent on `nav_menu_item` is "type" but it is stored with underscores whereas the block attr uses hyphens.
+			mapper: () => blockAttributeValue.replace( '-', '_' ),
```
Comment (gwwar) [inline packages/edit-navigation/src/store/utils.js]: 🤔 from the usage above, it might make sense to write this as an object to object transform vs per field. I think doing this per field adds some indirection and makes it a bit harder to read. A good exercise would be to port over the other items like title to see if what pattern we like better. Readability is subjective of course, so folks are welcome to chime in too

Note that data is also likely to be missing or malformed. A json schema might make sense in the transform function, though we'd prefer a decent attempt at fixing the data vs throwing an error (say if `kind` does not match the enum of values).

```jsx
const blockAttributesToMenuItem = ( { label, url, description, id, kind } ) => { 
    return {
        title: label,
        object_id: id,
        type: kind.replace( '-', '_' ),
        // and so on...
    }
}
```

**Review by gwwar — COMMENTED** [review]
This is looking good @getdave ✨  I still need to finish manual testing, but my overall take is that we can probably fix the most obvious things and set aside some other cases for immediate follow up.

I left a few suggestions on the transform patterns. We might want a few more 👀s there on what folks prefer for readability and handling of malformed data. (For example, I just spotted this one: https://github.com/WordPress/gutenberg/issues/31254 that I'll fix tomorrow unless someone gets to it first.)

**Comment by Mamaduka** [comment]
Hi, @getdave

For some reason, I still see the same results. Attaching the screen recording:

https://user-images.githubusercontent.com/240569/116354498-943b0500-a809-11eb-8f71-49814fa0550c.mp4

File: packages/edit-navigation/src/store/utils.js [hunk 9]
```diff
@@ -172,3 +187,85 @@ export function computeCustomizedAttribute(
...
+			attr: 'kind', // the equivalent on `nav_menu_item` is "type" but it is stored with underscores whereas the block attr uses hyphens.
+			mapper: () => menuItemVal.replace( '_', '-' ),
+		},
+	};
+
+	return convertAttribute( MAPPING, menuItemField, menuItemVal );
+};
+
+/**
+ * Converts a given key in an object to it's mapped equivalent.
```
Comment (Aljullu) [inline packages/edit-navigation/src/store/utils.js]: Typo?
```suggestion
 * Converts a given key in an object to its mapped equivalent.
```

**Review by Aljullu — COMMENTED** [review]
I did some testing of this PR with WooCommerce, because it has its own custom post types and taxonomies, and everything worked well on my end, I couldn't spot any issues. I also took a look at the code but will let the code review for somebody with more expertise.

**Comment by gwwar** [comment]
Can't save a post-format in navigation editor:

This takes a bit of setup:

1. Activate a theme that supports post-formats, like Twenty Thirteen
2. Create some posts that use a post format like quote or gallery
3. Enable the navigation editor and create a new menu
4. Insert a post-format link (points to the post format archive). Note that this should be using the post-format variation:

https://user-images.githubusercontent.com/1270189/116439517-7e771100-a804-11eb-9a54-8ba904284db0.mp4

A custom link works out okay but we should avoid the 500 here:

| 500 | Sent values |
|-----|-----|
| Screen Shot 2021-04-28 at 9 30 31 AM | Screen Shot 2021-04-28 at 9 26 46 AM |

**Comment by gwwar** [comment]
Tag type is saved as "post_tag"

1. Visit the Navigation Editor
2. Add a tag variation and select a tag
3. Notice that this renders as a "custom" link type
4. Save and use the menu to prepopulate a navigation block in the post or site editor
5. type is saved as "post_tag" instead of "tag"

See general testing:

https://user-images.githubusercontent.com/1270189/116442513-6d7bcf00-a807-11eb-8d1c-37e290fae29a.mp4

**Comment by gwwar** [comment]
Link Title is not persisted if we save a value in the navigation editor, then load in the navigation block on post/site editor

**Comment by gwwar** [comment]
Pretty close @getdave! Thanks for tackling this one. I verified some CPTs, post, tags, category, pages, drafts created in the nav editor, and some custom formats like tel/mailto.

Some things I think we'll need before merge:
- [x] Get another code review on the per-field transform, I think it adds unnecessary indirection, but I'm okay to defer if other folks don't mind it. Eg it sticks out to me, but it's not blocking.
- [x] Fix [tag type serialization](https://github.com/WordPress/gutenberg/pull/31004#issuecomment-828613993)
- [x] Fix [link title serialization](https://github.com/WordPress/gutenberg/pull/31004#issuecomment-828634139)

Can be done as follow up or in this PR:
- [ ] Fix [post-format serialization](https://github.com/WordPress/gutenberg/pull/31004#issuecomment-828601727) (currently 500s)
- [x] Fix [open in new tab serialization](https://github.com/WordPress/gutenberg/pull/31004#issuecomment-827747951)

🤔 As a side note, I had trouble trying to setup a post type archive. I curious to see what this persisted as in the menu editor. 

Since we're trying to persist the custom type now, I also spun up https://github.com/WordPress/gutenberg/pull/31259 for the navigation block. 👀 are appreciated there.

For other folks reviewing if you're wondering where CPTs are in the menu editor, there's a lot of options hiding in "Screen Options"

Screen Shot 2021-04-28 at 10 13 53 AM

**Comment by getdave** [comment]
> * Get another code review on the per-field transform, I think it adds unnecessary indirection, but I'm okay to defer if other folks don't mind it. Eg it sticks out to me, but it's not blocking.

I was using this approach in order to keep the PR limited in scope. However, in hindsight it has made things necessarily complex. I'm going to refactor along the lines you suggest and deal with all the attributes in one hit.

File: packages/edit-navigation/src/store/utils.js (hunk 8 above)
Comment (getdave) [reply packages/edit-navigation/src/store/utils.js]: I've now changed this to use a model similar to that which you suggest here.

I went the other way mainly to avoid having to introduce too many changes into this PR but it ended up introducing unwanted complexity and indirection (as you correctly pointed out).

File: packages/block-library/src/navigation/placeholder.js (hunk 6 above)
Comment (getdave) [reply packages/block-library/src/navigation/placeholder.js]: The `kind` attribute on the block basically maps to [the `type` attribute on the nav menu item](https://core.trac.wordpress.org/browser/tags/5.7.1/src/wp-includes/nav-menu.php#L802). The main difference is that the values use `_` instead of `-` as separators.

Note that this is _not_ an identifier of the object type (ie: `Post`, `Page`, `Category`, `{Custom Post Type} Category`...etc) but rather an enum of:

* [`post-type`](https://core.trac.wordpress.org/browser/tags/5.7.1/src/wp-includes/nav-menu.php#L822).
* [`post-type-archive`](https://core.trac.wordpress.org/browser/tags/5.7.1/src/wp-includes/nav-menu.php#L862)
* [`taxonomy`](https://core.trac.wordpress.org/browser/tags/5.7.1/src/wp-includes/nav-menu.php#L877)

The use of `custom` is simply a convention rather than part of the `enum` which allows users to set a custom link without having to associate it with any given "entity" within WordPress. 

I would have thought it would be best for the block to use `custom` as the fallback case.

> Note that while the custom link variation is an option in the block editor, this really means that we don't set initial search parameters

This makes sense because you aren't searching for an entity.

> ...or a specific type like a post link.

I don't follow this sorry. Can you help me to understand?

**Comment by getdave** [comment]
> * Fix [tag type serialization](https://github.com/WordPress/gutenberg/pull/31004#issuecomment-828613993)

I'm not sure we should look to fix in this PR. It's already getting quite large and fixing this would touch several other files. Moreover, the issue was not introduced by this PR and can be replicated in `trunk`. I have a fix and will create a separate PR in order that we can keep this one simple.

> Fix link title serialization
> Fix open in new tab serialization

There were a few issues here which should have been resolved as a result of the wider refactor.

File: packages/block-library/src/navigation/placeholder.js (hunk 3 above)
Comment (getdave) [reply packages/block-library/src/navigation/placeholder.js]: Fixed as part of refactor.

**Comment by getdave** [comment]
Ok @gwwar - thanks for your reviews and comments. Super helpful and much appreciated.

I've revised everything now and I think it's all working better.

The only things I'm not sure we need to cover in _this_ PR are:

* post formats
* post tags

These seem to both be existing issues and we'd be growing this PR very large if we tackle them here. 

Happy to raise and follow up immediately afterwards.

Will ping again in [the nav editor Slack channel ](https://wordpress.slack.com/archives/C01KDAZJMQ9) for review.

File: packages/edit-navigation/src/store/test/utils.js [hunk 10]
```diff
@@ -299,12 +341,269 @@ describe( 'computeCustomizedAttribute', () => {
...
+			attr_title: '',
+			object: 'custom',
+			type: 'custom',
+			target: '_blank',
+		},
+	];
+
+	const blockAttrs = blocks.map( ( block ) => block.attributes );
+
+	describe( 'mapping block attributes to menu item fields', () => {
```
Comment (talldan) [inline packages/edit-navigation/src/store/test/utils.js:647]: Another option for these tests is to convert to A to B and then B back to A and compare the results. E.g. for block attributes:
```js
const blockAttributes = { // ... some fixture data };
const menuItem = blockAttributesToMenuItem( blockAttributes );
const blockAttributes2 = menuItemToBlockAttributes( menuItem );
expect( blockAttributes ).toEqual( blockAttributes2 );
```

And the same for menu items:
```js
const menuItem = { // ... some fixture data };
const blockAttributes = menuItemToBlockAttributes( menuItem );
const menuItem2 = blockAttributesToMenuItem( blockAttributes );
expect( menuItem ).toEqual( menuItem2 );
```

That will ensure no data is lost/corrupted in conversion. I would say it might be worth having that in addition to the other tests.

File: packages/edit-navigation/src/store/utils.js [hunk 11]
```diff
@@ -172,3 +160,99 @@ export function computeCustomizedAttribute(
...
+		className: classes.join( ' ' ).trim(),
+		title: attr_title,
+		type: object || 'custom',
+		...( 'custom' !== object && {
+			id: object_id,
+		} ),
+		description,
+		url,
+		kind: menuItemTypeField?.replace( '_', '-' ) ?? 'custom',
+		opensInNewTab: target === NEW_TAB_TARGET_ATTRIBUTE,
```
Comment (talldan) [inline packages/edit-navigation/src/store/utils.js]: I wonder if the code should be a bit safer in handling some potentially `undefined` values here (`menuItemTitleField`, `xfn`, `classes`). I think I'd consider any menuItem data outside this code's control, so it should be ready for anything 😄 

Especially given we don't know what plugins or users have done previously to set these values.

Falling back to an empty string would probably be fine.

File: packages/edit-navigation/src/store/test/resolvers.js [hunk 12]
```diff
@@ -189,4 +231,105 @@ describe( 'getNavigationPostForMenu', () => {
...
+				parent: 0,
+				classes: [],
+				xfn: [],
+				description: '',
+				attr_title: '',
+				object: 'custom',
+			},
+		];
+
+		// Feed a known value to the generator yield result
```
Comment (talldan) [inline packages/edit-navigation/src/store/test/resolvers.js]: I always find the generator tests hard to read, so would be great for the comment to hint at what code this generator.next is for - e.g. which control/selector/action is being triggered.

File: packages/block-library/src/navigation/map-menu-items-to-blocks.js [hunk 13]
```diff
@@ -0,0 +1,83 @@
...
+	object_id,
+	description,
+	url,
+	type: menuItemTypeField,
+	target,
+} ) => {
+	return {
+		label: menuItemTitleField.rendered,
+		rel: xfn.join( ' ' ).trim(),
+		className: classes.join( ' ' ).trim(),
```
Comment (talldan) [inline packages/block-library/src/navigation/map-menu-items-to-blocks.js]: Similar comment here to the previous one, it'd be good to handle `undefined` values.

**Review by talldan — COMMENTED** [review]
Looks really good so far, it's definitely nice to see this code move toward something more maintainable (and correct).

I did some testing by saving various types of menu items in the current menu screen, then loaded up the new nav screen, and then the reverse of that process.

There are a couple of things I've noticed:
- A tag created in the current menu screen becomes a custom Link when loaded in the new nav screen
- A label edited in the new nav screen isn't saved, loading up the current menu screen Custom Link labels are deleted and changes to other types aren't saved.

I didn't read all of the previous comments, so that may have been mentioned already.

File: packages/edit-navigation/src/store/test/utils.js (hunk 10 above)
Comment (getdave) [reply packages/edit-navigation/src/store/test/utils.js:647]: Great idea @talldan. Thanks!

File: packages/edit-navigation/src/store/utils.js (hunk 11 above)
Comment (getdave) [reply packages/edit-navigation/src/store/utils.js]: Yes that is a very good point. I'll add some safety checks and fallbacks.

File: packages/block-library/src/navigation/map-menu-items-to-blocks.js (hunk 13 above)
Comment (getdave) [reply packages/block-library/src/navigation/map-menu-items-to-blocks.js]: I was looking at block attrs <--> menu item fields conversion. I couldn't decide whether we should:

1. Set a default value at the point of conversion.
2. Omit missing values on the source object on the target and allow them to fall through to whatever defaults are provided.

I've gone with option 2 because often the defaults are set by Core and thus we shouldn't set our own duplicate defaults here. 

For example block attrs -> menu item. [The menu item code in Core actually has a tonne of defaults](https://core.trac.wordpress.org/browser/tags/5.7.1/src/wp-includes/nav-menu.php#L438) so we don’t need to pass these. In fact there’s a good argument we should allow Core to define the defaults and just pass anything the block has overridden.

I've updated the code and associated tests to reflect this.

File: packages/edit-navigation/src/store/utils.js (hunk 11 above)
Comment (getdave) [reply packages/edit-navigation/src/store/utils.js]: See https://github.com/WordPress/gutenberg/pull/31004#discussion_r623756348

File: packages/edit-navigation/src/store/test/utils.js (hunk 10 above)
Comment (getdave) [reply packages/edit-navigation/src/store/test/utils.js:647]: I've decided to not include these types of tests because following [this discussion](https://github.com/WordPress/gutenberg/pull/31004#discussion_r623756348) we now no longer have lossless conversion in our code because we allow Core to set the defaults. Therefore a 1:1:1 conversion will no longer produce the results we expect.

File: packages/edit-navigation/src/store/test/resolvers.js (hunk 12 above)
Comment (getdave) [reply packages/edit-navigation/src/store/test/resolvers.js]: TBH I still find the [values being passed into `yield`](https://javascript.info/generators#yield-is-a-two-way-street) confusing as it can seem out of step. I've attempted to document the code to explain what is happening.

**Comment by getdave** [comment]
> A tag created in the current menu screen becomes a custom Link when loaded in the new nav screen

✅ Fixed

https://user-images.githubusercontent.com/444434/116694418-2d5b4e80-a9b7-11eb-922a-75146666fb62.mp4

Good catch. Another one which @gwwar also noticed. I've been through again and I was able to replicate. The issue is that the block variation is `tag` whereas WP Core uses `post_tag` when storing in the DB.

I've decided to avoid a block migration by simply doing the conversion on the fly when mapping blocks -> menu items (and vica versa). I've added x2 specific tests to provide coverage on these and documented the reasons behind the decision in code.

> * A label edited in the new nav screen isn't saved, loading up the current menu screen Custom Link labels are deleted and changes to other types aren't saved.

✅ Fixed

https://user-images.githubusercontent.com/444434/116694437-33e9c600-a9b7-11eb-956f-95013cd193c6.mov

Got it! I think @gwwar picked this one up as well. I've just worked out the cause, fixed the issue and added some test coverage.

**Comment by getdave** [comment]
@gwwar @talldan I looked into the `post-format` issue. Looks like we have [a bug in the REST API response ](https://github.com/WordPress/gutenberg/issues/31380)which I can't fix in this PR.

Other than that I believe all the previous points have now been addressed, namely:

✅  Updated to use per block/menu item transforms rather than per property.
✅  Fix tag type serialization
✅  Fix link title serialization
✅  Fix open in new tab serialization

So the only issue left is `Fix post-format serialization (currently 500s)` which as I say above we can't address in this PR.

I'd say I'm ready for a final review 🤞 🙇

File: packages/block-library/src/navigation/map-menu-items-to-blocks.js [hunk 14]
```diff
@@ -0,0 +1,97 @@
...
+ * @param {Object} menuItem.title stores the raw and rendered versions of the title/label for this menu item.
+ * @param {Array} menuItem.xfn the XFN relationships expressed in the link of this menu item.
+ * @param {Array} menuItem.classes the HTML class attributes for this menu item.
+ * @param {string} menuItem.attr_title the HTML title attribute for this menu item.
+ * @param {string} menuItem.object The type of object originally represented, such as 'category', 'post', or 'attachment'.
+ * @param {string} menuItem.object_id The DB ID of the original object this menu item represents, e.g. ID for posts and term_id for categories.
+ * @param {string} menuItem.description The description of this menu item.
+ * @param {string} menuItem.url The URL to which this menu item points.
+ * @param {string} menuItem.type The family of objects originally represented, such as 'post_type' or 'taxonomy'.
+ * @param {string} menuItem.target The target attribute of the link element for this menu item.
```
Comment (gwwar) [inline packages/block-library/src/navigation/map-menu-items-to-blocks.js]: This is optional, but would it be easier to use a typescript `@typedef` definition for menuItem?

https://developer.wordpress.org/block-editor/contributors/code/coding-guidelines/#custom-types

File: packages/edit-navigation/src/store/utils.js [hunk 15]
```diff
@@ -172,3 +159,147 @@ export function computeCustomizedAttribute(
...
+ * See: https://core.trac.wordpress.org/browser/tags/5.7.1/src/wp-includes/nav-menu.php#L438.
+ *
+ * @param {Object} blockAttributes the block attributes of the block to be converted into menu item fields.
+ * @param {string} blockAttributes.label the visual name of the block shown in the UI.
+ * @param {string} blockAttributes.url the URL for the link.
+ * @param {string} blockAttributes.description a link description.
+ * @param {string} blockAttributes.rel the XFN relationship expressed in the link of this menu item.
+ * @param {string} blockAttributes.className the custom CSS classname attributes for this block.
+ * @param {string} blockAttributes.title the HTML title attribute for the block's link.
+ * @param {string} blockAttributes.type the type of variation of the block used (eg: 'Post', 'Custom', 'Category'...etc).
```
Comment (gwwar) [inline packages/edit-navigation/src/store/utils.js:199]: Also optional, since we can always follow up later, but a typedef also works well for any enums we need to define:

https://developer.wordpress.org/block-editor/contributors/code/coding-guidelines/#custom-types

File: packages/edit-navigation/src/store/utils.js [hunk 16]
```diff
@@ -172,3 +159,147 @@ export function computeCustomizedAttribute(
...
+	// To avoid writing a block migration we perform a conversion here.
+	// See also inverse equivalent in `blockAttributesToMenuItem`.
+	if ( object && object === 'post_tag' ) {
+		object = 'tag';
+	}
+
+	return {
+		label: menuItemTitleField?.rendered || '',
+		type: object || 'custom',
+		kind: menuItemTypeField?.replace( '_', '-' ) || 'custom',
```
Comment (gwwar) [inline packages/edit-navigation/src/store/utils.js:286]: 👏 thanks this is much easier to read in one place!

File: packages/block-library/src/navigation-link/edit.js [hunk 17]
```diff
@@ -552,7 +552,12 @@ export default function NavigationLinkEdit( {
 											return escape( normalizedURL );
 										} )(),
 										opensInNewTab: newOpensInNewTab,
-										id,
+										// `id` represents the DB ID of the entity which this link represents (eg: Post ID).
+										// Therefore we must not inadvertently set it to `undefined` if the `onChange` is called with no `id` value.
+										// This is possible when a setting changes such as the `opensInNewTab`.
```
Comment (gwwar) [inline packages/block-library/src/navigation-link/edit.js:557]: 🤔 I think we'll want to unit test what's being passed through to on change in a different PR. It's likely that other fields may need a similar guard.

File: packages/edit-navigation/src/store/utils.js [hunk 18]
```diff
@@ -172,3 +159,147 @@ export function computeCustomizedAttribute(
...
+		...( kind?.length && {
+			type: kind?.replace( '-', '_' ),
+		} ),
+		// Only assign object_id if it's a entity type (ie: not "custom").
+		...( id &&
+			'custom' !== type && {
+				object_id: id,
+			} ),
+		...( opensInNewTab && {
+			target: NEW_TAB_TARGET_ATTRIBUTE,
```
Comment (gwwar) [inline packages/edit-navigation/src/store/utils.js]: If opensInNewTab is false, target should be added as '' to allow the navigation editor to unset this value. This is because of how to how we're applying these values in https://github.com/WordPress/gutenberg/blob/7497fa6a524b4c366bea540b0dd619236dc89782/packages/edit-navigation/src/store/utils.js#L147-L149 

Menu editor ✅ 
Navigation Editor ❌ (Can't unset)
Post Editor ✅

I tested this in each editor with the following steps:

1. set opens in new tab
2. save
3. reload
4. verify opens in new tab
5. unset this value
6. save
7. reload




https://user-images.githubusercontent.com/1270189/116735837-eca60a00-a9a3-11eb-88f6-778bb2afaf89.mp4

**Review by gwwar — APPROVED** [review]
Nice work @getdave this is a huge improvement on our serialization and data handling in the navigation editor! ✨

I'm giving tentative approval. ✅ **Please fix the `opensInNewTab` case before merge**. No need for another look from me for that case if that's sorted.

I tested this by some manual smoke testing starting from various editors, and seeing if values were persisted starting from one editor or another.

Here's a quick example case:

https://user-images.githubusercontent.com/1270189/116737214-ced9a480-a9a5-11eb-84c8-19f340319cf2.mp4

File: packages/block-library/src/navigation-link/edit.js (hunk 17 above)
Comment (getdave) [reply packages/block-library/src/navigation-link/edit.js:557]: Agreed. Indeed I raised this Issue for that

https://github.com/WordPress/gutenberg/issues/31379

File: packages/block-library/src/navigation/map-menu-items-to-blocks.js [hunk 19]
```diff
@@ -0,0 +1,97 @@
...
+	object_id,
+	description,
+	url,
+	type: menuItemTypeField,
+	target,
+} ) => {
+	return {
+		label: menuItemTitleField?.rendered || '',
+		type: object || 'custom',
+		kind: menuItemTypeField?.replace( '_', '-' ) || 'custom',
```
Comment (gwwar) [inline packages/block-library/src/navigation/map-menu-items-to-blocks.js:52]: Looking at this again, maybe it makes more sense to only set `kind` to custom? Instead of both kind and type.

File: packages/block-library/src/navigation/map-menu-items-to-blocks.js (hunk 14 above)
Comment (getdave) [reply packages/block-library/src/navigation/map-menu-items-to-blocks.js]: Done 👍

File: packages/edit-navigation/src/store/utils.js (hunk 15 above)
Comment (getdave) [reply packages/edit-navigation/src/store/utils.js:199]: Created followup Issue.

File: packages/block-library/src/navigation/map-menu-items-to-blocks.js (hunk 19 above)
Comment (getdave) [reply packages/block-library/src/navigation/map-menu-items-to-blocks.js:52]: Yep ok agreed. Done.

File: packages/edit-navigation/src/store/utils.js (hunk 18 above)
Comment (getdave) [reply packages/edit-navigation/src/store/utils.js]: Great spot. Fixed and added specific test coverage.

File: packages/edit-navigation/src/store/utils.js (hunk 15 above)
Comment (getdave) [reply packages/edit-navigation/src/store/utils.js:199]: https://github.com/WordPress/gutenberg/issues/31450
