### PR TITLE
Fix SyntaxError in Autocompleter UI when pasting matching content

### LINKED ISSUE #76948: Autocompleter calls useAnchor without settings, crashes on empty CSS selector
## Description

The `AutocompleterUI` component in `@wordpress/components` calls `useAnchor()` without passing `settings`, which causes `getFormatElement()` in `@wordpress/rich-text` to crash with an empty CSS selector.

## Steps to reproduce

1. Register a custom autocompleter with `triggerPrefix: '#'` (or any single character that can appear in URLs)
2. Open the block editor with rich text content
3. Type some text in a list item
4. Paste a URL containing a `#` fragment (e.g., `https://example.com/path/#section`)
5. The `#` triggers the autocompleter, which renders `AutocompleterUI`

**Result:** Editor crashes with "This block has encountered an error"

**Expected:** The autocompleter should either not crash, or `useAnchor` should handle missing settings gracefully.

## Error

```
SyntaxError: Failed to execute 'matches' on 'Element': The provided selector is empty.
    at getFormatElement (rich-text/index.js)
    at getAnchor (rich-text/index.js)
    at useAnchor (rich-text/index.js)
    at AutocompleterUI (components/index.js)
```

## Root cause

In `packages/components/src/autocomplete/index.tsx`, the `AutocompleterUI` component calls:

```js
const popoverAnchor = useAnchor({
    editableContentElement: contentRef.current,
    // settings is NOT passed
});
```

In `packages/rich-text/src/component/use-anchor.js`, when `settings` is undefined:

```js
const { tagName, className } = settings ?? DEFAULT_SETTINGS;
// DEFAULT_SETTINGS = { tagName: "", className: "" }
```

This produces an empty selector string `""`, which is passed to `Element.matches("")` and throws a `SyntaxError`.

## Suggested fix

Guard against empty selectors in `getFormatElement()`:

```js
const selector = tagName + (className ? "." + className : "");
if (!selector) {
    return;
}
```

Or pass valid default settings from `AutocompleterUI`.

## Environment

- Gutenberg versions: v22.7.0, v22.8.0-rc.1 (confirmed on both)
- Browser: Chrome, Firefox
- Context: WordPress.com P2 sites (custom `#` autocompleter triggers the bug, but the crash is in core)

### PR DESCRIPTION
**Pull request by Swanand01**
## What?
Closes #76948
Guard against empty CSS selector in `getFormatElement` in `use-anchor.ts`.

## Why?
`AutocompleterUI` calls `useAnchor()` without passing `settings`, which falls back to `DEFAULT_SETTINGS = { tagName: '', className: '' }`. This produces an empty selector that causes `element.matches('')` to throw a `SyntaxError`, crashing the block.

## How?
Added an early return in `getFormatElement` when `selector` is empty. An empty selector can never match a format element, so returning `undefined` is correct — `getAnchor` falls through to `createVirtualAnchorElement` and positions the popover at the cursor as expected.

## Testing Instructions
1. Open a new post, add a List block.
2. In the browser console, register a `#` autocompleter:
```js
wp.hooks.addFilter(
    'editor.Autocomplete.completers',
    'test/hash',
    ( completers ) => [
        ...completers,
        {
            name: 'test-hash',
            triggerPrefix: '#',
            options: [ 'foo', 'bar', 'baz' ],
            getOptionLabel: ( o ) => o,
            getOptionKeywords: ( o ) => [ o ],
            getOptionCompletion: ( o ) => o,
        },
    ]
);
```
3. Paste https://example.com/path/#section into a list item.

### CODE REVIEW

**Comment by Mamaduka** [comment]
Thanks for working on this, @Swanand01!

Haven't tested this, but I think it might be better to re-arrange the return logic in `getAnchor`.  We could return early if the anchor isn't a good fit for the format.

I'm also not sure whether the new unit tests add real value; we're mocking the DOM and running most tests in simulation.

## Example patch

```diff
diff --git a/packages/rich-text/src/hook/use-anchor.ts b/packages/rich-text/src/hook/use-anchor.ts
index 7a9c1b9c7f7..004538eddb5 100644
--- a/packages/rich-text/src/hook/use-anchor.ts
+++ b/packages/rich-text/src/hook/use-anchor.ts
@@ -151,18 +151,14 @@ function getAnchor(
 		return;
 	}
 
-	const formatElement = getFormatElement(
-		range,
-		editableContentElement,
-		tagName,
-		className
-	);
-
-	if ( formatElement ) {
-		return formatElement;
+	if ( ! tagName && ! className ) {
+		return createVirtualAnchorElement( range, editableContentElement );
 	}
 
-	return createVirtualAnchorElement( range, editableContentElement );
+	return (
+		getFormatElement( range, editableContentElement, tagName, className ) ??
+		createVirtualAnchorElement( range, editableContentElement )
+	);
 }
 
 const DEFAULT_SETTINGS = {
```

**Review by Mamaduka — APPROVED** [review]
Thanks, @Swanand01!

This looks good to me, but I would like to get a second opinion from @mcsf.

**Review by mcsf — CHANGES_REQUESTED** [review]
Thanks for the patch, @Swanand01! While it does prevent the issue, I'd like the fix to be closer to the source of the problem, which is `getFormatElement`'s poor handling of `Element#matches`.

It's already established that `getFormatElement` may return undefined, in which case `getAnchor` falls back to `createVirtualAnchorElement`. So we just need to ensure that `getFormatElement` bails gracefully.

The two ways to do it are to either check that `selector` is not empty, or to wrap the `Element#matches` call in a `try` and bail on error.

**Comment by Mamaduka** [comment]
@mcsf, I guess we can restore the check from 3a5788890ef4e73cb07b7fda2868cfc647afb608. With a combination of early returns, it should cover all cases.

**Comment by mcsf** [comment]
> @mcsf, I guess we can restore the check from [3a57888](https://github.com/WordPress/gutenberg/commit/3a5788890ef4e73cb07b7fda2868cfc647afb608). With a combination of early returns, it should cover all cases.

But is that check in itself not enough? Do we need more case handling? (I'd favour the simplest fix if possible.)

**Comment by Mamaduka** [comment]
The current ` ! tagName && ! className ` is pretty much the same, and usually WP coding style favors similar early returns. The additional check in `getFormatElement` would serve as a safeguard if this diverges in the future.

P.S. Please share a diff, I'm totally missunderstanding your suggestion :)

**Comment by mcsf** [comment]
When I submitted my review I hadn't seen the commit list, only the final diff, but essentially the fix I was suggesting was exactly what was first committed as 3a5788890ef4e73cb07b7fda2868cfc647afb608.

- My strong preference is that the _locus_ that calls the throwable API method be the one responsible, especially because consumers of `getFormatElement` can't tell from its signature that it could lead to a syntax error. Thus: 3a5788890ef4e73cb07b7fda2868cfc647afb608
- My soft preference is that we avoid the small complexity penalty of "fixing the issue twice". That is, I don't like the guard in `getAnchor` (`if ( ! tagName && ! className ) {`). But I also understand your motivation for avoiding superfluous function calls, and I would be OK with it. :)

So ultimately I think this PR should be either:
- return early in `getFormatElement`
- return early in `getFormatElement` + avoid calling `getFormatElement` in `getAnchor`

File: packages/rich-text/src/hook/use-anchor.ts [hunk 1]
```diff
@@ -62,6 +62,11 @@ function getFormatElement(
 
 	const selector = tagName + ( className ? '.' + className : '' );
 
+	// Element#matches will throw SyntaxError on an empty selector
+	if ( ! selector ) {
+		return;
+	}
```
Comment (mcsf) [inline packages/rich-text/src/hook/use-anchor.ts:68]: I've pushed this bit.

**Review by mcsf — APPROVED** [review]
