### PR TITLE
Change the filtervalue to lowercase

### LINKED ISSUE #13250: Searching for and adding existing categories is case-sensitive
**Describe the bug**
We can only search for and add existing categories to blog posts if we use lowercase letters, uppercase letters (even when they're a part of the original category name) yield no results.

**To Reproduce**
1. Setup at minimum 8 categories on your website (this is what makes the search feature appear in the blog post editor): https://wordpress.com/settings/taxonomies/category/
2. Create or edit an existing blog post
3. Since you have at least 8 categories we will see a search bar available to search for and add categories to this blog post. [Screenshot](https://user-images.githubusercontent.com/33190975/50862376-19602e80-1361-11e9-9ed1-269bf49b1eb1.jpg)
4. Search for an existing category, like "festival" in my example. The category will appear, as expected. [Screenshot](https://user-images.githubusercontent.com/33190975/50862457-4ca2bd80-1361-11e9-9e5f-7a127ee450fa.jpg)
5. However, if we search for the same category by entering "Festival" (capital "F") then it will not appear from my list. [Screenshot](https://user-images.githubusercontent.com/33190975/50862543-807de300-1361-11e9-926b-eacf69d5270c.jpg)

**Expected behavior**
In Calypso this behavior did not exist, we could search for use categories by upper or lower case letters regardless of the case used on the original category. 

We should be able to type any variant of the category to find and use it from our category list. For example, if the category name is "Festival" then I should be able to find and add it by entering any version:
festival, Festival, FESTIVAL, fEsTiVaL.

Currently we can only enter the all-lowercase version of the word "festival" to get the result. This is confusing to our users, especially when their actual category name has a capital letter (like "Festival") already in it.

**Screenshots**
Screenshots are inline, above.

**Extra information:**
This only occurs with categories in Gutenberg, I could not replicate the problem with tags.

**Additional context**
This problem was originally reported and confirmed on 9351413-hc. The behavior was replicated and tests were compared to Calypso on my own test site.

### PR DESCRIPTION
**Pull request by Jackie6**
## Description
Fix #13250 

## How has this been tested?
- [X] local test
- [X] browser test

## Types of changes
Change the filterValue to lower case

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style. 
- [X] My code follows the accessibility standards. 
- [X] My code has proper inline documentation. 
- [X] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by aduth** [comment]
I'm not super familiar with its implementation, but should this be incorporated into what `getFilterMatcher` is intended to serve? cc @notnownikki re: #10138

**Review by draganescu — CHANGES_REQUESTED** [review]
I think this should be treated in the function, not as a quickfix in the function's param. If we look at the `getFilterMatcher` function this part appears to be the problem:

```
// If the term's name contains the filterValue, or it has children
// (i.e. some child matched at some point in the tree) then return it.
if ( -1 !== term.name.toLowerCase().indexOf( filterValue ) || term.children.length > 0 ) {
	return term;
}
```

this condition lowercases the term but allows the filterValue to remain as is. I think it should be::

```
// If the term's name contains the filterValue, or it has children
// (i.e. some child matched at some point in the tree) then return it.
if ( -1 !== term.name.toLowerCase().indexOf( filterValue.toLowerCase() ) || term.children.length > 0 ) {
	return term;
}
```

Does this sound right? @Jackie6 @youknowriad

**Comment by Jackie6** [comment]
Hi @draganescu thanks for your review. I think you are right. It is better to put `toLowerCase()` functions together.

**Review by draganescu — APPROVED** [review]

File: packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js [hunk 1]
```diff
@@ -302,7 +302,7 @@ class HierarchicalTermSelector extends Component {
 
 			// If the term's name contains the filterValue, or it has children
 			// (i.e. some child matched at some point in the tree) then return it.
-			if ( -1 !== term.name.toLowerCase().indexOf( filterValue ) || term.children.length > 0 ) {
+			if ( -1 !== term.name.toLowerCase().indexOf( filterValue.toLowerCase( ) ) || term.children.length > 0 ) {
```
Comment (aduth) [inline packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js]: Nitpick: There should be no spaces between the parentheses here.

>No filler spaces in empty constructs (e.g., {}, [], fn()).

https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/#spacing

```suggestion
			if ( -1 !== term.name.toLowerCase().indexOf( filterValue.toLowerCase() ) || term.children.length > 0 ) {
```

Comment (draganescu) [reply packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js]: Yes @Jackie6, just remove that or commit the suggestion and we're good to go!
