### PR TITLE
Multi-entity saving: Allow publishing a post while not saving changes to non-post entities

### LINKED ISSUE #36096: Multi-entity saving: Cannot publish a post with site entity deselected
### Description

Before publishing a new post that contains post and site entities, deselecting the site entity, then hitting Publish triggers a Javascript error. The result is that I cannot publish a post.

The error is `this.props.setEntitiesSavedStatesCallback is not a function`
It looks like the prop `setEntitiesSavedStatesCallback` is not passed to the [post publish button](https://github.com/WordPress/gutenberg/blob/release/11.8/packages/editor/src/components/post-publish-button/index.js#L56) from the [post publish panel](https://github.com/WordPress/gutenberg/blob/release/11.8/packages/editor/src/components/post-publish-panel/index.js#L93).

First noticed while testing **Site Logo: Add option to set site icon from Site Logo block**
#35892 in https://github.com/WordPress/gutenberg/pull/35892#issuecomment-955811322

### Step-by-step reproduction instructions

1. Create a new post 
2. Insert a Site Logo block. Add or upload an image.
3. Insert some text or a heading.
4. Hit **Publish** to publish the post.
5. In the pre-publish save menu, deselect Logo, then hit **Save**, then **Publish**.
Screen Shot 2021-11-01 at 12 24 09 pm

### What I expected

That I could publish the post, or that I'd be given feedback as to why I couldn't publish the post without saving the site logo.

### What happened
Nothing in the editor, but the console throws the following error:

Screen Shot 2021-11-01 at 8 55 31 am

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/6458278/139608805-fc072ef9-519c-4cd9-8787-8fd84e3c0aae.mp4

### Environment info

- WordPress 5.8.1
- Gutenberg trunk
- TwentyTwentyOne and TT1 Blocks

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by stacimc**
Fixes #36096

## Description

This PR provides a quick fix for a bug which makes it impossible to publish a new post that makes changes to non-post entities (like a template part or the Site Logo), but does not save them. Eg:

* Create a new post
* Add a Site Logo block
* Update the image in the Site Logo
* Click 'Publish', and deselect 'Site Logo' in the pre-publish panel
* Click `Save`, then `Publish`.

This PR resolves the error by checking for the existence of the `setEntitiesSavedStatesCallback` prop before attempting to open the pre-publish panel.

### Explanation of the bug

We were getting an error at [this line](https://github.com/WordPress/gutenberg/blob/22814c75b0c0041493f791399c70299a037bf3f3/packages/editor/src/components/post-publish-button/index.js#L56). The problem is that when the Publish button is clicked, we check `hasNonPostEntityChanges` to see if there are changes to non-post entities, and then perform some logic to open the pre-publish panel that allows you to check what entities you'd like saved (see screenshot). But if those entities _aren't_ saved (user deselected them), they will still be dirty and the logic will attempt to run again when you hit `Publish` the second time.

When the `Publish` button is rendered the second time, it's [rendered by the `PostPublishPanel`](https://github.com/WordPress/gutenberg/blob/22814c75b0c0041493f791399c70299a037bf3f3/packages/editor/src/components/post-publish-panel/index.js#L93) and the `setEntitiesSavedStatesCallback` prop is not passed. It's the absence of this prop (which is used to open the pre-publish panel) that causes the error. Notably it doesn't make sense to pass it here, since at this point we don't expect to open that panel.

## How has this been tested?

**It is important to always test with a _new_ post, publishing for the first time.**
Verify that you can reproduce the bug on trunk. Then:

### Test that you can publish while deselecting non-post Entities
* Create a new post and add a Site Logo block
* Update the image in the Site Logo
* Click `Publish` and deselect `Site Logo`. Hit `Save`, then `Publish` again.
* Verify that the post was published and any changes other than the Site Logo were saved. Verify that the post is still dirty (the `Update` button can be clicked), and shows the option to save Site Logo.

### Test that you can publish when you *do* save non-post Entities
* Create a new post and add a Site Logo block.
* Update the image in the Site Logo
* Click `Publish` and do _not_ deselect anything. Hit `Save` then `Publish`
* Verify the post was published and changes to Site Logo were saved.

## Screenshots 
Screen Shot 2021-12-14 at 11 55 22 AM

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/editor/src/components/post-publish-button/index.js [hunk 1]
```diff
@@ -41,19 +41,28 @@ export class PostPublishButton extends Component {
 
 	createOnClick( callback ) {
 		return ( ...args ) => {
-			const { hasNonPostEntityChanges } = this.props;
-			if ( hasNonPostEntityChanges ) {
+			const {
+				hasNonPostEntityChanges,
+				setEntitiesSavedStatesCallback,
+			} = this.props;
+			// If a post with non-post entitities is published, but the user
```
Comment (ramonjd) [inline packages/editor/src/components/post-publish-button/index.js]:
```suggestion
			// If a post with non-post entities is published, but the user
```

**Comment by ramonjd** [comment]
Nice work @stacimc This is working well for me so far and an improvement on the current experience.

Kapture 2021-12-15 at 10 57 01

✅ When I deselect the site entity the post saves, but the site logo is not set (checked in the Customizer).
✅ Similarly when I deselect the post entity (but leave the site entity checked) the site logo is saved.
✅ Leaving both checked saves the post and site entities as expected.

**Comment by paaljoachim** [comment]
Thank you @stacimc Staci! 
This is a very helpful PR!

Testing the PR Gutenberg Build.
Chrome - Desktop Server.
OSX 11.6.1
Theme: Twenty Twenty Two

1- Made a new post.
2- Added the Site Logo block and added an image.
3- Clicked Publish and deselected the Site Logo.

**Before:**
Site - Logo block
Post - (showing post title)
**Deselecting** the Site Logo Block. Save button is active. Clicking Save leads to next screen with Publish button and the dot in the Publish button. **The Publish button is not active. One is stuck.**

**After - This PR:**
Site - Logo block
Post - (showing post title)
**Deselecting** the Site Logo Block. Save button is active. Clicking Save leads to next screen with Publish button and the dot in the Publish button. **The Publish button is active/clickable**. One can move onward and publish the post. Moving onward. Back to regular sidebar area. There is now a dot and the button "Update...". Clicking Update leads to the Save screen where Site Logo is active.

4- Clicked Save.
5- Clicked Publish.
6- Post published and one can move onward.
7- Button says "Update..." 
8- Clicking Update leads to the Save screen where the Site Logo block shows up and wants to be saved.
9- Opened a new tab and went to the All Posts screen. The post was published. Going to edit the post the Site Logo block is seen but with no image. (The site does not use an image logo).


1- Creating a new post.
2- Added a Site Logo block. Added an image.
3- Clicked Publish (see the dot in the Publish button).
4- Clicked Save (did not uncheck Site - Logo or Post - (post title) )
5- Clicked Publish.
6- Changes to Site Logo was changed.

----

One is not stuck in the Publish process when a Site item such as the Site Logo block is unchecked.
One can move on and Publish the post.

**Comment by paaljoachim** [comment]
I added the Backport label as I assume this PR will be backported to WP 5.9. (If it is merged within short period of time.)

**Comment by ockham** [comment]
Nice! 🎉  I'll test in a moment. Chipping in my (unfinished) e2e test: https://github.com/WordPress/gutenberg/pull/37408

**Comment by ockham** [comment]
Adding that we should also test the Site Editor after modifying the multi-entity saving logic.

- Select a block-based theme, such as TT1 Blocks.
- Open the Site Editor to edit the Index template.
- In the header, modify the site title.
- In the header, add a new paragraph block with some content.
- At template level, add a new paragraph block with some content.
- Click 'Save', and try to save with different combinations of unselected entities.

Seems to work well! 🎉

**Review by ockham — APPROVED** [review]
This LGTM! (Though we might wanna apply @ramonjd's [typo fix](https://github.com/WordPress/gutenberg/pull/37383/files#r769140019).)

Thanks for the great explanation and the fix! This is both helpful in the short-term and longer-term, if we end up refactoring some of the logic at some point.

**Comment by stacimc** [comment]
Thanks for all the reviews! Updated to include the typo fix :)

> Adding that we should also test the Site Editor after modifying the multi-entity saving logic.

@ockham I tested making changes to multiple entities and saving them individually in the site editor (eg: modify several template parts and the Site Logo, test saving everything but the Site Logo), and this is working for me. Anything else you were thinking of to test here?

I would like to get the e2e tests in #37408 in with this PR, but I took a look to see if I could help with the false positive and I'm afraid I'm stumped. Are you comfortable merging this without the tests for now?

**Comment by ockham** [comment]
> > Adding that we should also test the Site Editor after modifying the multi-entity saving logic.
> 
> @ockham I tested making changes to multiple entities and saving them individually in the site editor (eg: modify several template parts and the Site Logo, test saving everything but the Site Logo), and this is working for me. Anything else you were thinking of to test here?

Not really -- that sounds pretty good :)
 
> I would like to get the e2e tests in #37408 in with this PR, but I took a look to see if I could help with the false positive and I'm afraid I'm stumped. Are you comfortable merging this without the tests for now?

Yeah, let's merge this as-is -- I'd rather not have it blocked by the tests, since it could take a while to sort those out, and I think we want to backport this PR to Core sooner rather than later.
