### PR TITLE
Fix rich text value for nested lists

### LINKED ISSUE #10701: List block: list breaks when a new subitem is added using the keyboard.
**Describe the bug**
Using the keyboard to add a new subitem in a list breaks the list.

**To Reproduce**
1. Create a new "List" block.
2. Add any text to create some items.
3. Select at least one of these items and click on the "Indent list item" icon to create one o more subitems.
4. Now, click on the end of one of the subitems and hit "Return" in your keyboard.
5. The list will break as a result.

**Expected behavior**
To create new subitems, would be sufficient to hit "Return" while the cursor is at the end of a subitem. This is how main items on the list are created by default, but it doesn't work for subitems.

You can only create subitems by clicking on the "Indent list item" icon. The keyboard can't be used for this at all or the list will break.

**Screenshots**

list-block-subitem-issue

**Desktop:**
 - MacOS X 10.12
 - Chrome 69

**Additional context**
 - Gutenberg 4.0.0
 - WordPress 4.9.8
 - Twenty Seventeen.
 - No other plugins.

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

* Fixes #10701. Adjusts the rich text value for lists to have separators for nested lists items. This is needed to be able to split nested list items.
* Improves the handling of multiline values in general on split and merge by manipulating the value ourselves rather than relying on browser/TinyMCE behaviour.
* Fixes transforms to other blocks when a list has nested list items.

A big part of the added lines are unit and e2e tests.

## How has this been tested?
See #10701.

## Types of changes
Bug fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: packages/rich-text/src/to-dom.js [hunk 1]
```diff
@@ -110,6 +105,33 @@ function remove( node ) {
 	return node.parentNode.removeChild( node );
 }
 
+function createBogusBR( doc ) {
```
Comment (aduth) [inline packages/rich-text/src/to-dom.js]: If 'br' is an abbreviation of "break" (unsure), correct capitalization would be `createBogusBr`

File: packages/rich-text/src/to-dom.js [hunk 2]
```diff
@@ -110,6 +105,33 @@ function remove( node ) {
...
+	const br = doc.createElement( 'br' );
+	br.setAttribute( 'data-mce-bogus', '1' );
+	return br;
+}
+
+function pad( node ) {
```
Comment (aduth) [inline packages/rich-text/src/to-dom.js]: What is being padded, and with what. This isn't obvious.

File: packages/rich-text/src/create.js [hunk 3]
```diff
@@ -274,14 +275,27 @@ function createFromElement( {
...
-		const value = createFromElement( {
-			element: node,
-			range,
-			removeNode,
-			unwrapNode,
-			filterString,
-			removeAttribute,
-		} );
+		if ( node.nodeName === 'UL' || node.nodeName === 'OL' ) {
+			value = createFromMultilineElement( {
```
Comment (aduth) [inline packages/rich-text/src/create.js]: Are `UL` and `OL` the only multiline tags we support?

If not, where do we account for the others?

File: packages/rich-text/src/create.js [hunk 4]
```diff
@@ -363,6 +377,7 @@ function createFromMultilineElement( {
 	unwrapNode,
 	filterString,
 	removeAttribute,
+	startSeparator = false,
```
Comment (mcsf) [inline packages/rich-text/src/create.js]: New arg missing in JSDoc

File: packages/rich-text/src/to-tree.js [hunk 5]
```diff
@@ -33,27 +10,73 @@ export function toTree( value, multilineTag, settings ) {
...
 	const formatsLength = formats.length + 1;
-	const tree = createEmpty( tag );
+	const tree = createEmpty();
+	const multilineFormat = { type: multilineTag };
 
-	append( tree, '' );
+	let lastCharacterFormats;
+	let lastCharacter;
+
+	// If we're building a multiline tree, start off with a multiline element.
```
Comment (aduth) [inline packages/rich-text/src/to-tree.js]: Why?

This almost reads in direct contrast to what was discussed at https://github.com/WordPress/gutenberg/pull/10678#discussion_r226456573 .

File: packages/rich-text/src/to-tree.js [hunk 6]
```diff
@@ -33,27 +10,73 @@ export function toTree( value, multilineTag, settings ) {
...
+		let characterFormats = formats[ i ];
+
+		// Set multiline tags in queue for building the tree.
+		// For list items we need to take into account nested list items.
+		if ( multilineTag === 'li' ) {
+			characterFormats = ( characterFormats || [] ).reduce( ( accumulator, format ) => {
+				if ( format.type === 'ol' || format.type === 'ul' ) {
+					accumulator.push( format );
+					accumulator.push( multilineFormat );
+				} else if ( character !== '\u2028' ) {
```
Comment (aduth) [inline packages/rich-text/src/to-tree.js]: Can we give this magic string a named constant? Out of context, it means nothing to me.

File: test/e2e/specs/blocks/list.test.js [hunk 7]
```diff
@@ -155,4 +155,18 @@ describe( 'List', () => {
 
 		expect( await getEditedPostContent() ).toMatchSnapshot();
 	} );
+
+	it( 'should split indented list item', async () => {
+		await insertBlock( 'List' );
+		await page.keyboard.type( 'one' );
+		await page.keyboard.press( 'Enter' );
+		await page.mouse.move( 200, 300, { steps: 10 } );
+		await page.mouse.move( 250, 350, { steps: 10 } );
```
Comment (aduth) [inline test/e2e/specs/blocks/list.test.js]: Why must we move the mouse? Is there a keyboard-only workflow?

File: packages/rich-text/src/to-dom.js [hunk 8]
```diff
@@ -110,6 +105,33 @@ function remove( node ) {
 	return node.parentNode.removeChild( node );
 }
 
+function createBogusBR( doc ) {
+	const br = doc.createElement( 'br' );
+	br.setAttribute( 'data-mce-bogus', '1' );
```
Comment (aduth) [inline packages/rich-text/src/to-dom.js]: I'm sure it's known / been discussed before, but this is quite the implied dependency to TinyMCE.

File: packages/rich-text/src/to-dom.js [hunk 9]
```diff
@@ -110,6 +105,33 @@ function remove( node ) {
...
+	return br;
+}
+
+function pad( node ) {
+	const length = node.childNodes.length;
+
+	// Optimise for speed.
```
Comment (aduth) [inline packages/rich-text/src/to-dom.js]: As opposed to?

**Review by aduth — COMMENTED** [review]
Is there anywhere we've said that the multi line support is only intended for lists? Based on the prop name `multilineTag`, I would expect that no, it's not just for lists, but any tag. However, everything we build around it seems to be specifically only to support lists. Why is that?

File: packages/rich-text/src/create.js [hunk 10]
```diff
@@ -391,7 +406,7 @@ function createFromMultilineElement( {
 		} );
 
 		// Multiline value text should be separated by a double line break.
-		if ( index !== 0 ) {
+		if ( index !== 0 || startSeparator === true ) {
```
Comment (mcsf) [inline packages/rich-text/src/create.js]: Perhaps `shouldPrependSeparator` would be a better name? `should` signals a boolean, and with _prepend_ it seems clearer to me.

File: packages/rich-text/src/to-dom.js (hunk 2 above)
Comment (mcsf) [inline packages/rich-text/src/to-dom.js]: The function is a little hard to decipher. Perhaps defining some terminology if terminology is needed (e.g. padding), and making the high-level purpose evident.

**Review by mcsf — COMMENTED** [review]
I need to do a better review of this later. It's a very domain-specific change, which makes it a bit harder to get into.

**Comment by iseulde** [comment]
> Is there anywhere we've said that the multi line support is only intended for lists? Based on the prop name multilineTag, I would expect that no, it's not just for lists, but any tag. However, everything we build around it seems to be specifically only to support lists. Why is that?

It's not, its for both `p` and `li`.

**Comment by iseulde** [comment]
Reworking this PR right now.

**Comment by iseulde** [comment]
Reworking this PR right now.

**Comment by iseulde** [comment]
Reworking this PR right now.

**Comment by iseulde** [comment]
Reworking this PR right now.

**Comment by iseulde** [comment]
Reworking this PR right now.

File: packages/rich-text/src/create.js (hunk 3 above)
Comment (iseulde) [reply packages/rich-text/src/create.js]: I changed this so that the wrapper tags are defined by `RichText` instead.

File: packages/rich-text/src/to-tree.js (hunk 5 above)
Comment (iseulde) [reply packages/rich-text/src/to-tree.js]: No, this is purely for the creation of an *editable* DOM tree, which needs the multiline element if there is one only. If we change the output HTML, it will be changed in `toHTMLString`, which is purely for the output.

File: test/e2e/specs/blocks/list.test.js (hunk 7 above)
Comment (iseulde) [reply test/e2e/specs/blocks/list.test.js]: It didn't work for me otherwise. Shift+Tab shows the toolbar but does not focus it. Any fix is outside the scope of this PR.

File: packages/rich-text/src/to-dom.js (hunk 8 above)
Comment (iseulde) [reply packages/rich-text/src/to-dom.js]: Moved to `RichText`.

File: test/e2e/specs/blocks/list.test.js (hunk 7 above)
Comment (aduth) [reply test/e2e/specs/blocks/list.test.js]: Can we leave an inline comment if it's undesirable, and/or check for an existing issue?

Would it be fixed by #10906 ?

File: packages/rich-text/src/to-dom.js (hunk 8 above)
Comment (aduth) [reply packages/rich-text/src/to-dom.js]: Is the idea of a "line padding" something which is broadly applicable to support rich text editing? Still seems a bit oriented to TinyMCE specifically, even if not directly by name in the `rich-text` package.

File: packages/rich-text/src/create.js (hunk 3 above)
Comment (aduth) [reply packages/rich-text/src/create.js]: I guess my main question / concern would be: Are there going to be similar issues if someone uses any other multiline tag because we only have built-in correcting for the list usage?

File: packages/rich-text/src/to-html-string.js [hunk 11]
```diff
@@ -18,13 +18,18 @@ import { toTree } from './to-tree';
...
+ * @param {Object} value                Rich text value.
+ * @param {string} multilineTag         Multiline tag.
+ * @param {Array}  multilineWrapperTags Tags where lines can be found if nesting
+ *                                      is possible.
  *
  * @return {string} HTML string.
  */
-export function toHTMLString( value, multilineTag ) {
-	const tree = toTree( value, multilineTag, {
+export function toHTMLString( value, multilineTag, multilineWrapperTags ) {
```
Comment (aduth) [inline packages/rich-text/src/to-html-string.js]: `toDOM( { value, multilineTag, multilineWrapperTags } );` ✅ 
`toTree( { value, multilineTag, multilineWrapperTags } );` ✅ 
`toHTMLString( value, multilineTag, multilineWrapperTags );` 🤔

File: packages/rich-text/src/to-dom.js (hunk 8 above)
Comment (aduth) [reply packages/rich-text/src/to-dom.js]: Is it something that could be contained within the `createEmpty` procedure?

**Comment by aduth** [comment]
1. Insert list block
2. Add two list items
3. Indent second list item
4. Position caret at end of second (indented) list item
5. Press Enter
6. Press Backspace
7. Press Enter

Expected: Adds new indented list item
Actual: Adds new indented list item, deleting text of first list item

list

File: packages/rich-text/src/to-dom.js (hunk 8 above)
Comment (iseulde) [reply packages/rich-text/src/to-dom.js]: > Is the idea of a "line padding" something which is broadly applicable to support rich text editing?

Yes, it's not specific to TinyMCE. It should be part of the output to edit so you can always place the caret correctly in empty lines.

**Comment by aduth** [comment]
1. Insert list block
2. Add two list items
3. Indent second list item
4. Position caret at end of second (indented) list item
5. Press Enter
6. Press Up
7. [Bug One: Caret moves to previous block / title ?]
8. Reposition caret to beginning of second (indented) list item
9. Press forward delete to remove all text
10. Press forward delete once more

Expected: Deletes the third list item, but keeps caret in second (indented)
Actual: Deletes the second and third list item and moves caret to first

list

File: packages/rich-text/src/to-html-string.js (hunk 11 above)
Comment (iseulde) [reply packages/rich-text/src/to-html-string.js]: The problem is that `toHTMLString` is now a public API. Fine to change it though, and make sure everything keeps working.

**Comment by aduth** [comment]
1. Insert list block
2. Press Enter
3. Press Backspace
4. Press Enter

Expected: Same occurs at step 4 as does at step 2: Caret moves to new paragraph.
Actual: New (undeletable) list items are added

list

File: packages/rich-text/src/create.js (hunk 3 above)
Comment (iseulde) [reply packages/rich-text/src/create.js]: I can't see why there would be issues. They could use a different `multilineTag` and `multilineWrapperTags`. The value no longer has any built in logic for lists after your suggested change.

**Comment by aduth** [comment]
1. Insert list block
2. Add item
3. Press Enter
4. Indent new second item
5. Press Up
6. [Bug One: Caret moves to previous block / title ?]
7. Reposition caret to end of first item
8. Press forward Delete
9. Note indented item is removed
10. Press Enter

Expected: List has two, un-indented items
Actual: Deleted indented item reappears, with three items total

list

**Comment by iseulde** [comment]
@aduth, thanks, looking at the issues.

**Comment by iseulde** [comment]
@aduth It's because we're handling ENTER behaviour, but not BACKSPACE. I pushed a fix, which I'm still polishing.

**Comment by youknowriad** [comment]
Bug:

  - Type "something"
  - Press "enter"
  - Type "a"
  - Backspace
  - Press "enter"
 - The content of the list is duplicated and the caret moves unexpectedly.

**Review by youknowriad — APPROVED** [review]
Tested and works well for me 👍 

Code-wise, it's a bit complex for me to dive in. cc @aduth since you reviewed earlier.

File: packages/editor/src/components/rich-text/index.js [hunk 12]
```diff
@@ -582,32 +600,52 @@ export class RichText extends Component {
...
+				const record = this.createRecord();
+				let newValue;
+
+				if ( keyCode === BACKSPACE ) {
+					newValue = removePreviousLineSeparator( record );
+				} else {
+					newValue = removeNextLineSeparator( record );
+				}
+
+				if ( newValue ) {
```
[the remark this answers is not in the document]
Comment (aduth) [reply packages/editor/src/components/rich-text/index.js]: Okay, looking over the internal implementation of the functions, I see they handle this internally. Makes me wonder if we could (a) express this behavior better in its name or (b) move _some_ of this handling to the consumer, e.g. something like:

```js
if ( keyCode === BACKSPACE ) {
	if ( charAt( record, value.start - 1 ) === LINE_SEPARATOR ) {
		newValue = remove( record, value.start - 1 );
```

It's more verbose, but I think it hides less of what's actually occurring than what we have here.

File: packages/rich-text/src/test/remove-previous-line-separator.js [hunk 13]
```diff
@@ -0,0 +1,88 @@
...
+
+/**
+ * Internal dependencies
+ */
+
+import { removePreviousLineSeparator } from '../remove-previous-line-separator';
+import { LINE_SEPARATOR } from '../special-characters';
+import { getSparseArrayLength } from './helpers';
+
+describe( 'removePreviousLineSeparator', () => {
```
Comment (aduth) [inline packages/rich-text/src/test/remove-previous-line-separator.js]: What's the expected behavior of an uncollapsed selection? I'd expect it to be different, at least based on the behavior of backspace in a traditional textarea field.

File: packages/rich-text/src/test/remove-previous-line-separator.js [hunk 14]
```diff
@@ -0,0 +1,88 @@
+/**
+ * External dependencies
+ */
+import deepFreeze from 'deep-freeze';
+
+/**
+ * Internal dependencies
+ */
+
```
Comment (aduth) [inline packages/rich-text/src/test/remove-previous-line-separator.js]: There's no consistency to the newline placement after these blocks. While technically against the standard, most else of the application omits the newline. We should at the very least be consistent within the same file.

File: packages/rich-text/src/to-dom.js [hunk 15]
```diff
@@ -110,11 +105,44 @@ function remove( node ) {
...
+function padEmptyLines( { element, createLinePadding, multilineWrapperTags } ) {
+	const length = element.childNodes.length;
+	const doc = element.ownerDocument;
+
+	for ( let index = 0; index < length; index++ ) {
+		const child = element.childNodes[ index ];
+
+		if ( child.nodeType === TEXT_NODE ) {
+			if ( length === 1 && ! child.nodeValue ) {
+				element.appendChild( createLinePadding( doc ) );
```
Comment (aduth) [inline packages/rich-text/src/to-dom.js]: What are we doing here and why? (As an inline comment)

File: packages/rich-text/src/to-tree.js (hunk 5 above)
Comment (aduth) [reply packages/rich-text/src/to-tree.js]: The "Why" should probably be made clear in the code comment. The "What" is usually pretty obvious already anyways, so doesn't add much on its own as a comment.

File: test/e2e/specs/blocks/list.test.js (hunk 7 above)
Comment (aduth) [reply test/e2e/specs/blocks/list.test.js]: The comment doesn't read as though there's anything bad to be fixed. I'd expect either making it clear in the comment ("todo: fix badness") or create as a separate issue.

Comment (iseulde) [reply test/e2e/specs/blocks/list.test.js]: There are instances of this spread across the tests. I don't really see it as something bad this PR is introducing but an necessity because of how current things works. This is a perfectly valid way to convert a block, by moving them mouse and clicking the button?

I'll update the comment tomorrow.

File: packages/editor/src/components/rich-text/index.js [hunk 16]
```diff
@@ -582,32 +600,52 @@ export class RichText extends Component {
...
-		}
-
 		const isHorizontalNavigation = keyCode === LEFT || keyCode === RIGHT;
 		if ( isHorizontalNavigation ) {
 			this.onHorizontalNavigationKeyDown( event );
 		}
 
+		if ( keyCode === DELETE || keyCode === BACKSPACE ) {
+			if ( this.multilineTag ) {
+				const record = this.createRecord();
```
[the remark this answers is not in the document]
Comment (iseulde) [reply packages/editor/src/components/rich-text/index.js]: I'm not sure what you mean? Do you mean that we're calling this when we're the selection is not at the edge of a line? We need to have the value to check if we are in the first place, so I don't see a problem with this.

File: packages/editor/src/components/rich-text/index.js (hunk 12 above)
[the remark this answers is not in the document]
Comment (iseulde) [reply packages/editor/src/components/rich-text/index.js]: That sounds reasonable to me. I'll rewrite it. :)

File: packages/rich-text/src/test/remove-previous-line-separator.js (hunk 14 above)
Comment (iseulde) [reply packages/rich-text/src/test/remove-previous-line-separator.js]: Yes. I thought there should be a newline in between, so I try to be consistent with that. It would be good to have a linting rule for it.

File: packages/rich-text/src/test/remove-previous-line-separator.js (hunk 13 above)
Comment (iseulde) [reply packages/rich-text/src/test/remove-previous-line-separator.js]: I'll add tests for it as well. I guess it shouldn't remove the line.

**Comment by iseulde** [comment]
There's just a `covecov` failure, which we decided to ignore. Probably because I introduces a few files that are something like:

```js
export function getSelectionEnd( { end } ) {
 	return end;
 }
```

We can add more tests separately if needed.

I think this is a big improvement for multiline values. Let's merge and iterate. I'll keep an eye on any bugs popping up.

**Comment by talldan** [comment]
This change seems to have resulted in this bug:
https://github.com/WordPress/gutenberg/issues/11348

Looking into it now, seems a pretty urgent one to fix.
