### PR TITLE
Rich text: fix useAnchor (remove nextElementSibling)

### LINKED ISSUE #53641: Incorrectly anchored popover due to useAnchor hook finding wrong formatElement
When working with a rich text popovers it is common to make a text selection and then click an action to bring up a `@wordpress/format-library` editing UI in order that the format can be applied to the text selection.

For UX reasons, this edit UI is often contained within a popover which needs to be "anchored" to the text selection made by the user.

However, I have discovered that such popovers may be passed the "wrong" anchor ref because the `useAnchor` hook finds and uses an _existing_ format element as the target when calculating the anchor point. 

This happens when there is a single rich text block and the link being _created_ is _before_ another link that exists later in the same block of text. An example would be if my _selection_ was the word "Hello" in the following text - the "existing" format for `I am an existing link` would be found.

> Hello world [I am an existing link](https://wordpress.org).

Instead of anchoring to the selection range of the new link being created, instead the `getFormatElement` function finds the _existing_ link format `<a>` tag in the rich text block. 

https://github.com/WordPress/gutenberg/blob/676f25961bfab695bacb5dd7ebb10443e49bce23/packages/rich-text/src/component/use-anchor.js#L102-L107

It appears that this line causes the problem:

https://github.com/WordPress/gutenberg/blob/676f25961bfab695bacb5dd7ebb10443e49bce23/packages/rich-text/src/component/use-anchor.js#L24

This is because `nextElementSibling` may return an _existing_ format that exists after the selection. This format may be of the same type as the format you are looking to create (e.g. `core/link`) and so it will be returned even though it is outside the selection.

The resulting anchor is then passed to `Popover` as `anchor` meaning that it is incorrectly placed relative to the wrong link.

https://github.com/WordPress/gutenberg/blob/676f25961bfab695bacb5dd7ebb10443e49bce23/packages/format-library/src/link/inline.js#L212-L215

https://github.com/WordPress/gutenberg/blob/676f25961bfab695bacb5dd7ebb10443e49bce23/packages/format-library/src/link/inline.js#L254-L255

This was discovered when [I noticed `Popover` was being placed very strangely for the Link UI](https://github.com/WordPress/gutenberg/pull/53566).

## Replication

- New Post
- Add the following text:
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nulla malesuada pellentesque elit eget. Vitae et leo duis ut diam quam nulla porttitor. Id nibh tortor id aliquet lectus proin nibh nisl. Sed augue lacus viverra vitae. Feugiat in ante metus dictum at tempor commodo ullamcorper. Vitae nunc sed velit dignissim sodales ut eu sem. Massa tempor nec feugiat nisl pretium fusce id velit ut. Eros in cursus turpis massa tincidunt. Lacinia at quis risus sed vulputate odio ut enim blandit.Placerat vestibulum lectus mauris ultrices eros in cursus turpis. Nascetur ridiculus mus mauris vitae ultricies leo integer. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Urna porttitor rhoncus dolor purus. Aliquet bibendum enim facilisis gravida neque convallis. Risus ultricies tristique nulla aliquet enim tortor at. Scelerisque fermentum dui faucibus in ornare quam viverra. Nisl vel pretium lectus quam id leo in vitae turpis. Vulputate enim nulla aliquet porttitor lacus luctus accumsan. Morbi tristique senectus et netus et malesuada.
- Highlight a word in the first line of text and starting create a link using the editor (no need to submit it).
- See link UI popover anchor correctly positioned on text selection range boundary.
- Dismiss/remove any link (in case you created one).
- Now create a link to `w.org` on any word in the last sentance of the block of text.
- Now returning to the _first_ line of text try to create a link.
- This time notice that the link UI popover is positioned near the first link rather than the text selection for the new link.

## Screencapture

https://github.com/WordPress/gutenberg/assets/444434/8688da3b-9e4e-491c-a46b-744dba294047

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Fixes https://github.com/WordPress/gutenberg/issues/53641, alternative to #53642.

The root of the problem is `element.nextElementSibling`, which is selecting whatever next _element_ sibling of the range's start container, which could be an element way down the line, resulting in an element returned that is not connected to the given range.

The solution is to restrict this more: only if the selection is at the end of a text node, use the next sibling (not next _element_ sibling, because there might be other things in between), then select the deepest first child so it works with nested formatting.

Why do we need this is the first place? Well, format boundaries are purely visual and when you put the caret in front of a link, the collapsed selection is actually _outside_ the link, even though we've made it to look inside the link when you press arrow right.

Worth noting for testing: there's some other issue going on with popovers being mispositioned when selecting a link (I'm not sure if this is just for me locally, but it's an issue in trunk too and should be fixed separately).

### CODE REVIEW

File: packages/rich-text/src/component/use-anchor.js [hunk 1]
```diff
@@ -20,8 +20,22 @@ import { useState, useLayoutEffect } from '@wordpress/element';
...
 	let element = range.startContainer;
 
-	// If the caret is right before the element, select the next element.
-	element = element.nextElementSibling || element;
+	// One issues with format boundaries is that the caret can be right before
+	// the element while we make it look to be inside the element. So if the
+	// startContainer is a text node and the caret is at the end of the text,
+	// we should use the next sibling and the deepest first child so we can
+	// select the correct format element. Do not use nextElementSibling, it must
+	// otherwise you may be matching an element further away.
```
Comment (getdave) [inline packages/rich-text/src/component/use-anchor.js]:
```suggestion
	// An issue with format boundaries is that the caret can be immediately before
	// the element whilst it can appear to be **inside** the element. Therefore if the
	// startContainer is a text node and the caret is at the end of the text,
	// we should use the next sibling and the deepest first child so we can
	// select the correct format element. This avoids potential bugs where 
	// an element (such as another pre-existing format) is incorrectly matched.
	// See: https://github.com/WordPress/gutenberg/issues/53641.
```

Nit: some wording tweaks.

**Review by getdave — COMMENTED** [review]
This fixes the issue I described in https://github.com/WordPress/gutenberg/issues/53641 but there are bugs (read on)...

From what I can see the reason this works for the specific use-case I mentioned is that `getFormatElement` skips the `which` loop because the conditional no longer passes.

Therefore the `getFormatElement` ends up creating a "virtual anchor element" using `createVirtualAnchorElement` which returns a anchor based on the selected range (`range.getBoundingClientRect()`). This ensures the popover gets positioned correctly.

However, I have found a bug whereby `element` is `null` which causes the editor to crash. You can replicate using the following:

```
<!-- wp:paragraph -->
<p>Hello <a href="http://www.wordpress.org" data-type="link" data-id="www.wordpress.org">w<strong>or</strong>ld</a></p>
<!-- /wp:paragraph -->
```

Notice the bold text within the link. If you place your caret at the rightmost edge of the link text and then use arrows to move the caret into the link you'll see the editor crash.


https://github.com/WordPress/gutenberg/assets/444434/c7c657fc-7838-496b-ba88-099f9b6590fa



I'm not sure why this is yet.

**Comment by ellatrix** [comment]
Thanks! That's because the end of the text in the link element is selected, so `nextSibling` is null. Added a check for that.

**Review by getdave — COMMENTED** [review]
https://github.com/WordPress/gutenberg/assets/444434/046fd8e4-f75b-41ad-aa13-e8966c5cade4

This PR still causes crashes when moving around the active link format using arrows

**Review by getdave — APPROVED** [review]
With the recent change to fix the `null` element I cannot replicate the original bug reported in https://github.com/WordPress/gutenberg/issues/53641 or any further bugs.

It would be good to update the wording as per https://github.com/WordPress/gutenberg/pull/54013/files#r1309699624 otherwise we're good to go.

File: packages/rich-text/src/component/use-anchor.js (hunk 1 above)
Comment (getdave) [reply packages/rich-text/src/component/use-anchor.js]: @ellatrix Are you happy with this suggested change?

**Comment by getdave** [comment]
Thank you for fixing this Ella.
