### PR TITLE
Font Library: fix font uninstallation

### LINKED ISSUE #56166: Font Library: uninstalled fonts remain active
### Description

After uninstalling (deleting) an active font, that font still appears in the fonts panel.

### Step-by-step reproduction instructions

1. Install VT323
2. Verify it is activated
3. Return to Global Styles > Typography > Fonts, open the fonts modal, go to VT323, select Delete
4. Verify VT323 still shows in the fonts panel.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/5375500/0fcdb982-c362-4833-82e1-f480298e0bd4

### Environment info

Chrome Version 116.0.5845.187 (Official Build) (arm64)
MacOS 13.0.1 (22A400)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by jffng**
## What?
This PR fixes a bug in the `uninstallFont` function of the FontLibraryProvider class. 

~It also adds some logic to ensure that only custom fonts that are actually installed are ever rendered to the client.~

## Why?
Fixes https://github.com/WordPress/gutenberg/issues/56166

## How?
In the uninstallFonts function, check the response errors array for length.

~In the context, filter out fonts that are not installed.~

## Testing Instructions
- Install some custom fonts
- Go to each font, select "Delete" followed by "Yes, uninstall."
- Verify those fonts do not appear in the fonts modal or Typography sidebar preview.

### CODE REVIEW

File: packages/edit-site/src/components/global-styles/font-library-modal/context.js [hunk 1]
```diff
@@ -101,15 +101,18 @@ function FontLibraryProvider( { children } ) {
...
 		: [];
 
-	const baseCustomFonts = libraryFonts
-		? libraryFonts
+	const customFonts = fontFamilies?.custom
+		? fontFamilies.custom
 				.map( ( f ) => setUIValuesNeeded( f, { source: 'custom' } ) )
+				.filter( ( f ) =>
+					baseCustomFonts.some( ( bf ) => bf.slug === f.slug )
+				) // Ensures that the font actually exists in the library.
```
Comment (matiasbenedetto) [inline packages/edit-site/src/components/global-styles/font-library-modal/context.js]: Do you think this is necessary? I think it could lead to some inconsistencies like not displaying a font that is still activated (in global styles) but not installed.

File: packages/edit-site/src/components/global-styles/font-library-modal/context.js [hunk 2]
```diff
@@ -229,7 +232,7 @@ function FontLibraryProvider( { children } ) {
 			// Uninstall the font (remove the font files from the server and the post from the database).
 			const response = await fetchUninstallFonts( [ font ] );
 			// Deactivate the font family (remove the font family from the global styles).
-			if ( ! response.errors ) {
+			if ( 0 === response.errors.length ) {
```
Comment (matiasbenedetto) [inline packages/edit-site/src/components/global-styles/font-library-modal/context.js:232]: Nice catch

**Review by matiasbenedetto — COMMENTED** [review]
This is working as expected with the `if ( 0 === response.errors.length )` check. I think it would be better to omit the other change because it could lead to confusion in cases where, for some reason, there are fonts in global styles that are not installed in the library.

File: packages/edit-site/src/components/global-styles/font-library-modal/context.js (hunk 1 above)
Comment (jffng) [reply packages/edit-site/src/components/global-styles/font-library-modal/context.js]: > I think it could lead to some inconsistencies like not displaying a font that is still activated (in global styles) but not installed.

This is what happens now / on trunk. Without this line — if the font uninstallation fails, it will still display the activated font in the typography sidebar.

Comment (jffng) [reply packages/edit-site/src/components/global-styles/font-library-modal/context.js]: I see what you mean though, I'll remove it for now and find another way to address it if there are issues later.

Comment (matiasbenedetto) [reply packages/edit-site/src/components/global-styles/font-library-modal/context.js]: > if the font uninstallation fails, it will still display the activated font in the typography sidebar.

I think that's correct, if the font was not uninstalled, it should still render because it will continue being active, right?

**Review by matiasbenedetto — APPROVED** [review]
It looks good to me and is working as expected.

File: packages/edit-site/src/components/global-styles/font-library-modal/context.js (hunk 1 above)
Comment (jffng) [reply packages/edit-site/src/components/global-styles/font-library-modal/context.js]: Not quite — the way this is failing, is that the font gets uninstalled successfully on the server side, but not in global styles since that is handled client side and that's where the bug is. The result is the font family is uninstalled and deleted, but is still defined in global styles / shows up in the sidebar.
