### PR TITLE
Properly apply styles and classes to the experimental form block

### LINKED ISSUE #57328: Experimental Block: Form - can't add custom CSS class
### Description

Can't seem to get a custom class to appear for the experimental form block.

### Step-by-step reproduction instructions

1. Check _Form and input blocks_ in Gutenberg > Experiments
2. In a new page, add _/form_ block
3. In the block panel, add a custom CSS class in _Additional CSS Class(es)_
4. Publish page
5. View console and notice the CSS class is not there

### Screenshots, screen recording, code snippet

Screenshot 2023-12-21 at 6 48 28 PM
- 
Screenshot 2023-12-21 at 6 48 39 PM

### Environment info

- wp 6.4.2
- gutenberg 17.3.0
- chrome
- mac sonoma

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #59045: Form Block: register block style not working
### Description

The register block style option appears but when checked, the class is not applied to the form block.

### Step-by-step reproduction instructions

1. Add the following to your functions.php:
```
// REGISTER BLOCK STYLES
function yourtheme_register_block_styles() {
	register_block_style(
		'core/form',
		array(
			'name'         => 'dark-background',
			'label'        => __( 'Dark Background', 'yourtheme' )
		)
	);
}
add_action( 'init', 'yourtheme_register_block_styles' );
```

2. Make sure you have Gutenberg > Experiments > form and input blocks checked
3. Add a new page
4. Add a form block
5. Check the custom style in the components panel for the "Dark Background" style
6. Update
7. View source in front-end and notice the wp-block-form does not also include is-style-dark-background

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- wp 6.4.3
- gutenberg 17.7.0
- chrome
- mac

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by aristath**
## What?
Properly applies styles and classes to the experimental form block. In https://github.com/WordPress/gutenberg/pull/44214#issuecomment-1786948891 it shows that styles don't get properly applied to the `core/form` block. This PR fixes that issue.

## Why?
Because it's a bug - or rather something that wasn't properly implemented in the initial PR introducing the experiment.

## How?
* ~Removes the default `style` and `classes` attributes from the `<form>` element, and then adds them using `get_block_wrapper_attributes()`.~

---

Updated by @t-hamano:

- Remove the hard-coded `className` prop in the save function. This means that styles, classes, etc. from useblockProps will be respected, and block support will work properly.
- Add a block deprecation process so as not to break existing blocks in the contents. This deprecation is unusual and intentionally leaves the block support empty. See [this comment](https://github.com/WordPress/gutenberg/pull/55755/files#diff-f5e02f945f8e2ade1188bf021549961746ef35a7b7d1ae6e0c7a43d3b7dce201R13-R23) for the reason.

---

## Testing Instructions
* Enable the forms-blocks experiment, create a post and add a form in there.
* Change the background colors, padding, margin, typography... whatever you want.
* Save the post and visit it on the front (in the editor it was working properly, but not when viewing the post)
* Confirm that your styles were properly applied.

---

Added by @t-hamano:

### Testing for Block Deprecation

- Check out the trunk branch.
- Insert a Form block in the Post Editor. Apply a background color or change the font size.
- Save the post.
- Check out this branch.
- Reload the browser in the Post Editor.
- The block should not break, and your browser console logs that the migration process has been done correctly.
---

### Testing Instructions for Keyboard
Not applicable

### CODE REVIEW

**Review by carolinan — DISMISSED** [review]
This is an improvement. The style-related class names are now added to the `<form` tag.  Spacing, color, and typography settings work on the front.
The way the attributes are removed is unconventional but it is working.
I can see that the order of the `style` and `class` attributes is not the same as in other blocks. On the front, the `style` is before the `class`. This is unexpected but I am not sure it matters.

In the editor, the typography > font family setting is not working, hence the request for changes.
When I change the font family setting, the inner blocks still use the body font family
(The font family is correct on the front).

**Comment by aristath** [comment]
Thank you for the thorough check @carolinan!
I pushed an additional commit, fixing the issue 👍

**Comment by t-hamano** [comment]
What is the root cause of styles and classes not being applied on both the editor side and the front end side? My understanding is that the `useblockProps` hook should automatically give them those styles and classes.

Does it have something to do with this block being experimental? 🤔

**Comment by aristath** [comment]
> What is the root cause of styles and classes not being applied on both the editor side and the front end side? My understanding is that the useblockProps hook should automatically give them those styles and classes.

It was an error of omission... In the initial POC implementation, I just forgot to add them. The `style` was missing completely, and the classname was hardcoded to `wp-block-form` without getting any of the other ones added from colors, borders etc

**Comment by t-hamano** [comment]
I understand why. Although the blockProps hook has already been introduced, the `className` is false and the class name `wp-block-form` is hard-coded.

Is there any reason to make className false? If not, I think all we need to do is make the following changes.

```diff
diff --git a/packages/block-library/src/form/block.json b/packages/block-library/src/form/block.json
index 0c6451f495..b79c9f9249 100644
--- a/packages/block-library/src/form/block.json
+++ b/packages/block-library/src/form/block.json
@@ -27,7 +27,6 @@
        },
        "supports": {
                "anchor": true,
-               "className": false,
                "color": {
                        "gradients": true,
                        "link": true,
:...skipping...
diff --git a/packages/block-library/src/form/block.json b/packages/block-library/src/form/block.json
index 0c6451f495..b79c9f9249 100644
--- a/packages/block-library/src/form/block.json
+++ b/packages/block-library/src/form/block.json
@@ -27,7 +27,6 @@
                "anchor": true,
-               "className": false,
                "color": {
                        "gradients": true,
                        "link": true,
diff --git a/packages/block-library/src/form/edit.js b/packages/block-library/src/form/edit.js
index 7fded64837..7f479a9b2c 100644
--- a/packages/block-library/src/form/edit.js
+++ b/packages/block-library/src/form/edit.js
@@ -172,7 +172,6 @@ const Edit = ( { attributes, setAttributes, clientId } ) => {
                        ) }
                        <form
                                { ...innerBlocksProps }
-                               className="wp-block-form"
                                encType={ submissionMethod === 'email' ? 'text/plain' : null }
                        />
                </>
diff --git a/packages/block-library/src/form/save.js b/packages/block-library/src/form/save.js
index a824fc076d..9d944f13ef 100644
--- a/packages/block-library/src/form/save.js
+++ b/packages/block-library/src/form/save.js
@@ -10,7 +10,6 @@ const Save = ( { attributes } ) => {
        return (
                <form
                        { ...blockProps }
-                       className="wp-block-form"
                        encType={ submissionMethod === 'email' ? 'text/plain' : null }
                >
                        <InnerBlocks.Content />
~
~
```

Also, this PR requires deprecation because it changes the save markup, but as reported by #56590 there is an issue with fixture tests not working correctly.

**Comment by aristath** [comment]
You're right, the `className` in `block.json` should not be false. I pushed a commit to fix that.
However, I tried your suggestion and it didn't work... It looks like all the other stuff is needed too. Upon further examination, I saw we do the same thing in the [button](https://github.com/WordPress/gutenberg/blob/e3ef008e62dc52ada2fda9f203bcf12d18fe85de/packages/block-library/src/button/edit.js#L250-L267) block,  the [search](https://github.com/WordPress/gutenberg/blob/e3ef008e62dc52ada2fda9f203bcf12d18fe85de/packages/block-library/src/search/edit.js#L276-L287) block, as well as various others like image and so on.

**Comment by t-hamano** [comment]
> Upon further examination, I saw we do the same thing in the [button](https://github.com/WordPress/gutenberg/blob/e3ef008e62dc52ada2fda9f203bcf12d18fe85de/packages/block-library/src/button/edit.js#L250-L267) block,  the [search](https://github.com/WordPress/gutenberg/blob/e3ef008e62dc52ada2fda9f203bcf12d18fe85de/packages/block-library/src/search/edit.js#L276-L287) block, as well as various others like image and so on.

I think this kind of approach is mainly used when styles need to be applied to the elements _inside_ the block rather than the wrapper. Styles and classes should be applied correctly to the block wrapper unless we are using [__experimentalSkipSerialization](https://github.com/WordPress/gutenberg/blob/trunk/docs/explanations/architecture/styles.md#current-limitations-of-the-block-supports-api).

I pushed f8ee53e with the changes. In my testing, both global and block-specific styles appear to be applied correctly. Could you test this commit once?

https://github.com/WordPress/gutenberg/assets/54422211/c441fb34-812f-4e97-9eb0-71cd22dc0711

**Comment by aristath** [comment]
Huh... Confirmed, it works ❤️ 
Thank you!

**Comment by t-hamano** [comment]
I'm glad to know it worked correctly.

The code looks good, but in order to ship this PR, I think the following two actions are necessary:

- Rebase this PR with the latest trunk branch: This is because [#56590](https://github.com/WordPress/gutenberg/issues/56590), which ensures form-related fixtures are generated correctly in the fixture test, is included.
- Regenerate the fixture file via the `npm run fixtures:regenerate` command.

**Comment by aristath** [comment]
Done.
`npm run fixtures:regenerate` didn't change anything so I assume we're OK :+1:

**Comment by t-hamano** [comment]
Sorry, I forgot to tell you one more thing 😅

This PR is updating the `save` function, so you need to add [a block deprecation](https://github.com/WordPress/gutenberg/blob/HEAD/docs/reference-guides/block-api/block-deprecation.md). This will update existing fixture files when you run `npm run fixtures:regenerate`. Additionally, there is a need to add [a new fixture](https://github.com/WordPress/gutenberg/blob/HEAD/test/integration/fixtures/blocks/README.md) as well.

**Comment by aristath** [comment]
> This PR is updating the `save` function, so you need to add [a block deprecation](https://github.com/WordPress/gutenberg/blob/HEAD/docs/reference-guides/block-api/block-deprecation.md). This will update existing fixture files when you run `npm run fixtures:regenerate`. Additionally, there is a need to add [a new fixture](https://github.com/WordPress/gutenberg/blob/HEAD/test/integration/fixtures/blocks/README.md) as well.

Hmmm my apologies but I don't understand...
We need new fixtures and deprecations, when the markup/HTML of a block gets updated, correct?
But in this case, nothing actually changes... We removed the hardcoded `wp-block-form` class, and now Gutenberg automatically adds it. So the end result is still the same, the block gets that class, and the markup remains unchanged. :thinking:

**Comment by t-hamano** [comment]
Sorry for the late reply.

I tested this PR again and still think the new deprecation is necessary. This is because the current trunk has only one `className`: `wp-block-form`. However, if you remove the hard-coded `className` in this PR, the `className `may change.
You can confirm that the block is broken by following the steps below.

- Check out the trunk branch.
- Insert a Form block in the Post Editor. Apply a background color or change the font size.
- Save the post.
- Check out this branch.
- Reload the browser in the Post Editor.
- The block should break with an error similar to the one below.

image

The reason is that this PR adds a new (expected) class name when you apply a color or font size to the Form block.

**Comment by aristath** [comment]
Just an update here:
I've tried to fix the deprecation implementation for days but I can't figure it out.
After a discussion with @t-hamano on Slack, I pushed in this PR some code that in theory _should_ work, but doesn't. The code _looks_ correct, but following the instructions on https://github.com/WordPress/gutenberg/pull/55755#issuecomment-1905388558 I'm still getting an invalid-block error in the editor.
Nevertheless, I pushed it here so that if anyone has any ideas on what's wrong and how to fix it, they'd have some context.

Any help would be appreciated :heart: :pray: 

On a sidenote however, I'm not sure we even need a deprecation... I mean sure, there's a deprecation, but this is an experimental block and as such, it is not in a stable state. Breaking changes are expected and I'm not sure they should be a blocker. Clicking on the "Attempt Block Recovery" button works correctly.

**Comment by draganescu** [comment]
I don't have the full context but we really shouldn't care about deprecations for experiemnts - it beats the whole "experiment" idea :) the goal is fast iteration and feedback collection not backcompat.

**Comment by t-hamano** [comment]
> we really shouldn't care about deprecations for experiemnts

That may certainly be the case.

@aaronrobertshaw We're running into an issue where the deprecation doesn't work well in the form block. Ideally, we should investigate the cause, but what do you think about not adding deprecation to blocks that are marked as "experimental"?

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for the ping @t-hamano 👍 

Under normal circumstances, the deprecation here should work. The bug this PR aims to fix though causes some serious problems though.

> We're running into an issue where the deprecation doesn't work well in the form block. Ideally, we should investigate the cause, but what do you think about not adding deprecation to blocks that are marked as "experimental"?

100% we should investigate the cause. I don't think we can or should avoid that.

Regarding the experimental nature of the block to date. I agree the fact it is experimental should give us more freedoms but I still believe we owe it to early adopters to prevent breakages where possible. 

In this case, adding a working deprecation is possible, so my vote is that we do so.

> I've tried to fix the deprecation implementation for days but I can't figure it out.

@aristath I believe I've tracked down the root of the issue with why the current version of the deprecation isn't working. I'll try and summarize it all here clearly but it is a tricky area, so feel free to challenge anything, ask questions etc.

Deprecations only run when their old version of the block's `save` function generates the same content as what's saved in the block's markup.

The catch is that it does this through a series of utils: `validateBlock` > `getSaveContent` > `getSaveElement`. 

The last of those, [`getSaveElement`](https://github.com/WordPress/gutenberg/blob/trunk/packages/blocks/src/api/serializer.js#L124), will generate the content from the `save` function first, it then [applies any extra props](https://github.com/WordPress/gutenberg/blob/trunk/packages/blocks/src/api/serializer.js#L149-L172) via the `blocks.getSaveContent.extraProps` filters. The block supports in the editor are applied via that filter. 

This is why originally the block supports appeared to work in the editor and not on the frontend. It is also why then the deprecation is determined to not generate "valid" block markup and so isn't applied.

This is where the nature of the mistake in the original implementation really starts to cause some problems.

While I'm not very familiar with this area of the code, I don't think we can change the order of the application of block supports. It is likely being relied on as is and changing it to accommodate a bug fix is probably a non-starter.

There is an approach that has worked for me while hacking at this PR locally.

1. Remove the block supports config from the deprecation (well, make it empty and comment as to why, to demonstrate this is deliberate despite the block originally having supports enabled).
2. Manually define the block support attributes within the deprecation's attributes. This is required to maintain the data for the block support styles so they get migrated. Again, the hacked attributes should be heavily documented inline.

I'm running out of time today but in the simple testing I've done so far for a few different types of color; background, text, link etc. and the font size typography setting. It successfully migrates for me.

#### Proposal

1. Update the deprecation to omit the supports config and documented why.
2. Manually add the attribute definitions for all the block supports to the deprecation and document why again
3. Add a fixture for the form block that covers this deprecation i.e. one that has the old markup with only the `wp-block-form` class despite containing block support data e.g. `backgroundColor` in its attributes.

**Comment by aristath** [comment]
Hey @aaronrobertshaw, thank you for looking into this!
I'm afraid I don't quite understand this part:
> Manually define the block support attributes within the deprecation's attributes. This is required to maintain the data for the block support styles so they get migrated. Again, the hacked attributes should be heavily documented inline.

You mentioned that you got it working locally... Could you please post some code? Doesn't need to be complete, just enough for me to understand what's on your mind and what worked for you structurally.
My apologies if I'm wasting your time, but usually code makes more sense than words to me, and currently I don't understand what should go where 😅

**Comment by aaronrobertshaw** [comment]
My apologies for not adding code snippets, I'm a bit short on time and bandwidth at the moment.

> I'm afraid I don't quite understand this part:
> ...
> Manually define the block support attributes within the deprecation's attributes. This is required to maintain the data for the block support styles so they get migrated. Again, the hacked attributes should be heavily documented inline.

What I mean, is that the deprecation defines its attributes. Those deprecation attributes could be updated to include the attributes that the block supports inject. For example, the [background color support adds](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/hooks/color.js#L94) a number of attributes such as.

```
			backgroundColor: {
				type: 'string',
			},
			textColor: {
				type: 'string',
			},
			gradient: {
				type: 'string',
			},
```

If we only updated the deprecation's `supports` definition to be `{}` these sorts of attributes wouldn't be added to the deprecated version of the block. So they would be lost when migrating the block unless we add them to the deprecation's attributes manually.

> You mentioned that you got it working locally... Could you please post some code? Doesn't need to be complete, just enough for me to understand what's on your mind and what worked for you structurally.

I didn't stash the local changes as they were so far from complete but I'll put together something quick to illustrate the thrust of what I'm proposing.

<details>
<summary>Example diff</summary>

```diff
diff --git a/packages/block-library/src/form/deprecated.js b/packages/block-library/src/form/deprecated.js
index 4109ddf442..5db53b66ec 100644
--- a/packages/block-library/src/form/deprecated.js
+++ b/packages/block-library/src/form/deprecated.js
@@ -5,37 +5,18 @@ import { InnerBlocks, useBlockProps } from '@wordpress/block-editor';
 
 const deprecated = [
 	{
-		supports: {
-			anchor: true,
-			className: false,
-			color: {
-				gradients: true,
-				link: true,
-				__experimentalDefaultControls: {
-					background: true,
-					text: true,
-					link: true,
-				},
-			},
-			spacing: {
-				margin: true,
-				padding: true,
-			},
-			typography: {
-				fontSize: true,
-				lineHeight: true,
-				__experimentalFontFamily: true,
-				__experimentalTextDecoration: true,
-				__experimentalFontStyle: true,
-				__experimentalFontWeight: true,
-				__experimentalLetterSpacing: true,
-				__experimentalTextTransform: true,
-				__experimentalDefaultControls: {
-					fontSize: true,
-				},
-			},
-			__experimentalSelector: 'form',
-		},
+		// The block supports here are deliberately empty despite this
+		// deprecated version of the block having adopted block supports.
+		// The attributes added by these supports have been manually
+		// added to this deprecated version's attributes definition so
+		// that the data isn't lost on migration. All this is so that the
+		// automatic application of block support classes doesn't occur
+		// as this version of the block had a bug that overrode those
+		// classes. If those block support classes are applied during the
+		// deprecation process, this deprecation doesn't match and won't
+		// run.
+		// @see https://github.com/WordPress/gutenberg/pull/55755
+		supports: {},
 		attributes: {
 			submissionMethod: {
 				type: 'string',
@@ -51,6 +32,12 @@ const deprecated = [
 			email: {
 				type: 'string',
 			},
+			// The following attributes have been added to match the block
+			// supports at the time of the deprecation. See above for details.
+			backgroundColor: {
+				type: 'string',
+			},
+			// ... rest of block support attributes.
 		},
 		save( { attributes } ) {
 			const blockProps = useBlockProps.save();

```
</details>

I hope that helps 🤞

**Comment by t-hamano** [comment]
This PR will also fix #59045.

File: packages/block-library/src/form/deprecated.js [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+				default: 'post',
+			},
+			action: {
+				type: 'string',
+			},
+			email: {
+				type: 'string',
+			},
+			// The following attributes have been added to match the block
+			// supports at the time of the deprecation. See above for details.
```
Comment (aaronrobertshaw) [inline packages/block-library/src/form/deprecated.js]: I appreciate the commit adding these is labelled WIP, but just in case it isn't already on the radar, it looks like we still need the `anchor` block supports attribute as added [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/hooks/anchor.js#L38), given that support was previously adopted.

Comment (aristath) [reply packages/block-library/src/form/deprecated.js]: Good  catch! Thanks, added 👍

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for continuing to iterate on this @aristath 👍 

The deprecation looks good and the attributes contained within it match those provided by block supports currently. 

I think the only thing we need now is a fixture that covers this deprecated version of the form block.

**Comment by aristath** [comment]
I removed the deprecation as it was not working.
Since this is an experimental block, a deprecation is not strictly required... 

I don't know how to build this deprecation and make it work both in real-world use as well as in automated tests. If I make it pass the automated tests, then it doesn't work when I try to do it in the editor itself and vice-versa. 🤷 

Granted, the deprecation bug in this PR is an edge-case, but it's been a blocker for this PR for months so I completely removed it, as I find no way forward if we try to enforce it.

**Comment by aaronrobertshaw** [comment]
> I removed the deprecation as it was not working.

Can you expand at all on what wasn't working with the deprecation? Some steps to replicate the problem would be helpful.

> Since this is an experimental block, a deprecation is not strictly required...

I think this is a bit of a grey area. If we can sort out the deprecation and not break blocks for early adopters, that sounds like our best bet. From memory, the deprecations were pretty close last I reviewed this PR.

> make it work both in real-world use as well as in automated tests

If there is a disconnect between our fixture tests and how deprecations are working in the editor, that sounds like something we should probably get to the bottom of to maintain confidence in those tests.


I'm a little tied up on other things for WP 6.6 at the moment but I'd be more than happy to help out after the 6.6 beta.

**Comment by aristath** [comment]
Thank you for replying @aaronrobertshaw

> Can you expand at all on what wasn't working with the deprecation? Some steps to replicate the problem would be helpful.

The main issue I faced is in the UI.
Steps to replicate:
* Using trunk add a form block in the editor
* Change background-color, text-color and play with the styles a bit
* Switch to this branch and reload the editor

The error: Expecting the deprecation to kick-in and work, migrating the content. What actually happens: Still getting the invalid-block error. As soon as I hit the recovery button everything works, but that's not what we expect when adding migrations

**Comment by aaronrobertshaw** [comment]
Thanks for the extra details 👍 

It still sounds like an issue we should be able to fix with the deprecation. Have you by any chance done some debugging around where [block deprecations are applied](https://github.com/WordPress/gutenberg/blob/trunk/packages/blocks/src/api/parser/apply-block-deprecated-versions.js?plain=1#L32) to see what's going on in this case?

My understanding is that the form block isn't being stabilized for WP6.6, so there is no urgency to have this sorted before the WP6.6. beta, correct? I'd be happy to dig deeper in a week or two if that's the case.

**Comment by aristath** [comment]
> Have you by any chance done some debugging around where [block deprecations are applied](https://github.com/WordPress/gutenberg/blob/trunk/packages/blocks/src/api/parser/apply-block-deprecated-versions.js?plain=1#L32) to see what's going on in this case?

Yeah, tried to understand it for weeks and couldn't understand what goes on there... so to be honest I gave up. Deprecations make my head spin, so I moved on to other issues 😅 

> My understanding is that the form block isn't being stabilized for WP6.6, so there is no urgency to have this sorted before the WP6.6. beta, correct?

That is correct. this is not an urgent task 👍

**Comment by aaronrobertshaw** [comment]
> Deprecations make my head spin

Don't worry, you aren't alone there. Happens every time I have to revisit the area.

> That is correct. this is not an urgent task 👍

Great, then in that case let's see what we can come up with once I can free up some bandwidth. 

Appreciate your patience on this one.

**Comment by t-hamano** [comment]
I also investigated this issue again. I tried the deprecation suggested in this comment and it seems to work in some scenarios, but not completely.

For example, this deprecation works if the original markup does not include inline styles:

image

However, if the markup contains inline styles, deprecation will cause an error.

image
It feels like one more step, but I'm pushing the deprecated code again so you can test this issue.

**Comment by t-hamano** [comment]
Interesting #61833 submitted. It is mentioned that deprecation fails when `blockProps` is not used.

The Form block has `blockProps` applied, but [the class name is overridden](https://github.com/WordPress/gutenberg/blob/4da057ecd6958d40b8f2a83db1152320e5f161e6/packages/block-library/src/form/save.js#L12-L13). Maybe this PR is also related to #61833.

**Comment by paaljoachim** [comment]
Any thoughts on continuing the work on this PR?
As well as doing some additional work on the Form block?
The questions goes out to anyone....

**Comment by t-hamano** [comment]
The reason we can't rework this PR is that we haven't yet found a way to prevent this PR from breaking blocks. We haven't yet identified the cause, whether it's an error in our block deprecation code or a problem with the core deprecation logic itself 😅

File: test/integration/fixtures/blocks/core__form__deprecated-v1.html [hunk 2]
```diff
@@ -0,0 +1,7 @@
...
+<!-- /wp:form -->
+
+<!-- wp:form {"className":"custom-class","style":{"elements":{"link":{"color":{"text":"var:preset|color|contrast"}}},"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|40","right":"var:preset|spacing|40"},"margin":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}},"backgroundColor":"accent-1","textColor":"contrast","fontSize":"x-large"} -->
+<form id="anchor" class="wp-block-form" style="margin-top:var(--wp--preset--spacing--40);margin-right:var(--wp--preset--spacing--40);margin-bottom:var(--wp--preset--spacing--40);margin-left:var(--wp--preset--spacing--40);padding-top:var(--wp--preset--spacing--40);padding-right:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--40)" enctype="text/plain"></form>
+<!-- /wp:form -->
```
Comment (t-hamano) [inline test/integration/fixtures/blocks/core__form__deprecated-v1.html:7]: I have prepared two types of HTML: The first block has custom values, and the second block has preset values.

**Comment by t-hamano** [comment]
OK, I think 3e9c06acd8391dc92fc2c24f1680b3687541f1b9  fixed the problem.

> However, if the markup contains inline styles, deprecation will cause an error.

We explicitly left the supports field empty to properly enforce deprecation. As a result, even if the Form block has custom values via block supports, the useBlockProps.save hook will not output inline styles. This results in the deprecation not matching and not executing.

To avoid this, I explicitly generate the inline styles that useBlocksProps.save would have added, and applied them to the wrapper element. Similarly, this issue also occurred with anchor support, so I revised the anchor attribute definition to explicitly apply an ID to it.

Based on my testing, deprecation should now work in all scenarios!

File: test/integration/fixtures/blocks/core__form__deprecated-v1.html (hunk 2 above)
Comment (t-hamano) [inline test/integration/fixtures/blocks/core__form__deprecated-v1.html]: I have prepared two types of HTML: The first block has custom values, and the second block has preset values.

**Comment by t-hamano** [comment]
@aaronrobertshaw Ultimately, I believe we've applied the block deprecation correctly, and would appreciate your reviewing this PR for shipping 🙏

File: test/integration/fixtures/blocks/core__form__deprecated-v1.html (hunk 2 above)
Comment (aaronrobertshaw) [reply test/integration/fixtures/blocks/core__form__deprecated-v1.html]: I think I prefer the approach other blocks have taken where individual use cases are split into separate fixtures. It makes what the fixture represents and what you're testing clearer.

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for the ping and apologies for the delay 🙇 

I've only had a chance to give this an initial review. At first glance it looks pretty good to me. The fixtures pass although I think keeping a 1:1 between the fixture and use case could be a good thing e.g. custom values vs presets.

The approach to not define the block supports for the deprecation makes sense.

I'll give this a further test tomorrow with a view to approve. If anyone else gives this the tick of approval before then, feel free to go with it.

File: test/integration/fixtures/blocks/core__form__deprecated-v1.html (hunk 2 above)
Comment (t-hamano) [reply test/integration/fixtures/blocks/core__form__deprecated-v1.html]: Updated: 8be747e5839d8e61d51ec7318c4020de901ffe95

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for all the hard work here 👍 

I've given this more of a test:

✅ Forms created on trunk continue to look & function the same without error before migrating
✅ Deprecated forms migrate successfully and now display correctly on the frontend
✅ Fixture tests pass

Before merging this can we update the PR description so that it matches what this PR now does, has up-to-date test instructions etc? 

When it comes to any PR involving deprecations I've found it really helpful to have a clear accurate history to follow if further issues arrive or even just to inform other deprecations.

That aside, this looks good to me.

🚢
