### PR TITLE
ResizableFrame: Fix styling in Firefox

### LINKED ISSUE #52516: Site Editor: Oversized resizable editor canvas looks wrong in Firefox
In Firefox, resizing the Editor Canvas to a wider width behaves differently than on Chrome/Safari.

- The mouse position is out of sync with the left edge of the resizable frame.
- The right edge of the resizable frame overflows the right edge of the viewport. It should stay anchored to the right edge.

## Screen recording

https://github.com/WordPress/gutenberg/assets/555336/ab508a2f-931d-4526-97c9-b40db5dfdb2a

### PR DESCRIPTION
**Pull request by mirka**
Fixes #52516

## What?

Fixes the broken styling when the Editor Canvas is resized to a wider width in Firefox.

## Why?

Some CSS rules were not applying correctly in Firefox because it doesn't support `:has()` yet (#52699).

## How?

Restructures the CSS so it doesn't rely on `:has()` and follows BEM more cleanly.

## Testing Instructions

1. Open the [Site Editor](http://localhost:8888/wp-admin/site-editor.php).
2. Using your pointing device, drag resize the editor canvas to be wider.
3. The right edge of the editor canvas should be aligned with the right edge of the window, and the Site Hub should hide itself. (In other words, the behavior should be the same as in Chrome.)

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/555336/180824d2-79a9-45ad-93d4-5bd4e7bb7cb4

### CODE REVIEW

File: packages/edit-site/src/components/layout/index.js [hunk 1]
```diff
@@ -332,6 +341,12 @@ export default function Layout() {
 													}
 													isFullWidth={ isEditing }
 													oversizedClassName="edit-site-layout__resizable-frame-oversized"
```
Comment (stokesman) [inline packages/edit-site/src/components/layout/index.js]: It looks like the use of this prop could be removed now and further that the prop itself could be removed from `ResizableFrame`. Of course I could've missed something.
```suggestion
```

**Review by stokesman — APPROVED** [review]
I tried this out and it worked well. Looks 🚢 shape to me.

**Review by tellthemachines — COMMENTED** [review]
Hmm testing these changes on Chrome I'm now seeing the same buggy behaviour `:has` was causing in Firefox 🤔 can anyone else reproduce this?



https://github.com/WordPress/gutenberg/assets/8096000/07660c5c-8ac1-4b29-8475-360b2178b32e

**Comment by stokesman** [comment]
> can anyone else reproduce this?

I tried again and wasn't able to until I narrowed the browser window after load. Widening it after load has a funny effect too. I tried on trunk and can get the same thing.

File: packages/edit-site/src/components/layout/index.js (hunk 1 above)
Comment (mirka) [reply packages/edit-site/src/components/layout/index.js]: Good catch, thanks! 6ecff493

**Comment by mirka** [comment]
Thanks for testing!

The glitches you are seeing, if they're due to window resizing, is should be fixed in #52697.
