### PR TITLE
fix(modal): refactors all occurances of isDismissable to isDismissible

### LINKED ISSUE #17687: Inconsistent naming of the isDismissable/isDismissible property
**Describe the bug**
The Modal component uses [isDismissable](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/modal/index.js#L111) as a property, whereas the Notice component uses [isDismissible](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/notice/index.js#L23). 

I believe that `isDismissible` is the more correct spelling? We should probably create an alias in the Modal block for the correct spelling so as to fix the inconsistency without breaking existing usages.

### PR DESCRIPTION
**Pull request by agawish**
## Description
Refactors all occurences of `isDismissable` to `isDismissible` within `packages/components/src/modal` and `editor/src/components/post-locked-modal`

## How has this been tested?
- Reran all unit tests `npm test`
- Reran the wordpress locally after the changes (docker version 19.03.2, wordpress development version (5.3-beta2-46366))

## Types of changes
- Simple refactoring potentially 🤞 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 

## Picture of a cute animal:
chicks-4003579_640

Fixes #17687

### CODE REVIEW

**Comment by swissspidy** [comment]
What about back compat?

**Comment by Soean** [comment]
What about plugins using the the current prop `isDismissable`? This breaks the feature.

File: packages/components/src/modal/index.js [hunk 1]
```diff
@@ -108,7 +108,7 @@ class Modal extends Component {
 			children,
 			aria,
 			instanceId,
-			isDismissable,
+			isDismissible,
```
Comment (youknowriad) [inline packages/components/src/modal/index.js]: This is a breaking change, do we want to support both for sometime and deprecate the `isDismissable`?

(check `@wordpress/deprecated` usage to see how we deprecate things)

Comment (agawish) [reply packages/components/src/modal/index.js]: Sure, sorry for the mis-sight on my behalf, I will work on supporting both and deprecate `isDismissable`

**Comment by agawish** [comment]
I will make an update to support `isDismissable` for backward compatability, thanks for the pointers and sorry for the troubles.

File: packages/components/src/modal/index.js [hunk 2]
```diff
@@ -108,14 +109,20 @@ class Modal extends Component {
...
+			isDismissable, //Deprecated
 			// Many of the documented props for Modal are passed straight through
 			// to the ModalFrame component and handled there.
 			...otherProps
 		} = this.props;
 
 		const headingId = aria.labelledby || `components-modal-header-${ instanceId }`;
 
+		if ( isDismissable ) {
+			deprecated( 'isDismissable property', {
```
Comment (youknowriad) [inline packages/components/src/modal/index.js]: Can we clarify a bit more here? Maybe: `isDismissable prop of the Modal component`

**Review by youknowriad — APPROVED** [review]

File: packages/components/src/modal/index.js (hunk 2 above)
Comment (agawish) [reply packages/components/src/modal/index.js]: surething

**Comment by youknowriad** [comment]
Thanks for the updates and congrats for your first contribution
