### PR TITLE
Core Data: Add __experimentalBatch()

### LINKED ISSUE #27173: Widgets editor: "There was an error. object Object" on save
**Describe the bug**
In the widgets area, I do not get access to the Save button unless i duplicate a whole block and then edit that save everything and then go back and delete the original block. 

Since the last gutenberg update even after duplicating the block and editing it, when i get the save button, it changes to Saving ... and in the bottom left i get a very quick error message saying "There was an error. object Object" 

Having googled and checked here, i can confirm i get access to wp-json with no issue 

and as soon as i deactivate Gutenburg plugin, go back to the block editor ... i paste the text in where i want it, hit save and all done. 

**To reproduce**
1. Go to 'widgets'
2. Edit anything ... 
3. No access to save button 
4. Duplicate block to edit
5. Edit the duplicate block
6. Click save 
7. Quickly check for error message in bottom left 

Error message : "There was an error. object Object" 

and the save button sticks on "Saving" 

**Expected behavior**
Well i have been living with the having to duplicate edit, save, return, delete old copy, save again, check ... 

But clearly i would prefer the save to work with out having to go through all of that. Just a working save button after i edit some thing would be better.  

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version:  5.5.3–en_GB
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? Version 9.4.1 

**Desktop (please complete the following information):**
 - OS: windows 10 latest updates
 - Browser chrome 
 - Version Version 86.0.4240.198 (Official Build) (64-bit)

**Additional context**
Hosted on 20i's wordpress cloud. 
With jetpack installed
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

### LINKED ISSUE #28186: Error when saving widgets
## Description

There's an error when saving widgets from editing a clean state in the new widgets screen. Found when writing tests in #28160.

## Step-by-step reproduction instructions

1. Go to the new widgets screen.
2. Delete **all** widgets, including widgets in the **inactive widgets** section.
3. Save, reload, and confirm that there's no widgets left.
4. Add a new block (e.g. paragraph block) in the first widget area.
5. Toggle to open the second widget area (could be inactive widgets or others).
6. Add another block to the second widget area.
7. Hit "Update", see the error pops up in the snackbar.

## Expected behaviour

There shouldn't be any errors.

## Actual behaviour

There's an error and the widgets are not correctly saved.

## Screenshots or screen recording (optional)

image

## WordPress information
- WordPress version: 5.7-alpha-49956
- Gutenberg version: master branch
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Tested in both Twenty Twenty-One and Twenty Twenty

## Device information
- Device: Desktop
- Operating system: macOS
- Browser: Chrome 87

### PR DESCRIPTION
**Pull request by noisysocks**
Fixes https://github.com/WordPress/gutenberg/issues/27173.
Fixes https://github.com/WordPress/gutenberg/issues/28186.
Alternative to https://github.com/WordPress/gutenberg/pull/27241.

- Replaces the `batch-processing` data store with a stripped back API based on https://github.com/WordPress/gutenberg/pull/27241/files#r555573124 that doesn't use any persistence.

   ```js
   const batch = createBatch();
   const dunePromise = batch.add( {
     path: '/v1/books',
     method: 'POST',
     data: { title: 'Dune' }
   } );
   const lotrPromise = batch.add( {
     path: '/v1/books',
     method: 'POST',
     data: { title: 'Lord of the Rings' }
   } );
   const isSuccess = await batch.run(); // Sends one POST to /v1/batch.
   if ( isSuccess ) {
     console.log(
       'Saved two books:',
       await dunePromise,
       await lotrPromise
     );
   }
   ```

- Adds `__experimentalBatch()` to core-data.

   ```js
   const [ savedRecord, updatedRecord, deletedRecord ] =
     await dispatch( 'core' ).__experimentalBatch( [
       ( { saveEntityRecord } ) => saveEntityRecord( 'root', 'widget', widget ),
       ( { saveEditedEntityRecord } ) => saveEntityRecord( 'root', 'widget', 123 ),
       ( { deleteEntityRecord } ) => deleteEntityRecord( 'root', 'widget', 123, null ),
     ] );
   ```

- Changes `saveWidgetArea()` to use `__experimentalBatch()`.

- Properly fixes https://github.com/WordPress/gutenberg/issues/27173 by ensuring that `batch.run()` waits for all inputs to be added before proceeding.

@youknowriad @TimothyBJacobs @kevin940726 @talldan 

A ✅ should be sufficient for testing as until tests are included and `adding-widgets.test.js` includes a test for saving widgets.

### CODE REVIEW

File: packages/core-data/src/actions.js [hunk 1]
```diff
@@ -441,11 +443,18 @@ export function* saveEntityRecord(
...
 				);
-				updatedRecord = yield apiFetch( {
+				const request = {
 					path: `${ path }/autosaves`,
 					method: 'POST',
 					data,
-				} );
+				};
+				if ( __experimentalBatch ) {
+					updatedRecord = yield __unstableAwaitPromise(
```
Comment (noisysocks) [inline packages/core-data/src/actions.js:452]: Not sure why `__unstableAwaitPromise` is marked unstable.

Comment (noisysocks) [reply packages/core-data/src/actions.js:452]: Also, thinking it might be more "rungen-ey" to make this a dedicated control.

```js
updatedRecord = yield addToBatch( batch, request );
```

File: packages/core-data/src/actions.js [hunk 2]
```diff
@@ -543,6 +558,34 @@ export function* saveEntityRecord(
...
+				__experimentalBatch: batch,
+			} );
+		} else {
+			throw new Error(
+				"saveEntityRecords: 'recordId' or 'record' is required."
+			);
+		}
+	}
+
+	yield __unstableAwaitPromise( batch.waitForSize( spec.length ) );
```
Comment (noisysocks) [inline packages/core-data/src/actions.js:580]: This is what fixes https://github.com/WordPress/gutenberg/issues/27173 properly.

File: packages/data/src/batch.js [hunk 3]
```diff
@@ -0,0 +1,77 @@
+/**
```
Comment (noisysocks) [inline packages/data/src/batch.js:1]: I put this in `@wordpress/data` but am not sure about that.

File: packages/core-data/src/actions.js [hunk 4]
```diff
@@ -543,6 +558,34 @@ export function* saveEntityRecord(
 	}
 }
 
+export function* __experimentalBatchSaveEntityRecords( spec ) {
```
Comment (noisysocks) [inline packages/core-data/src/actions.js:561]: This doesn't handle deletes. Not sure how the API for that should look.

File: packages/core-data/src/actions.js [hunk 5]
```diff
@@ -543,6 +558,34 @@ export function* saveEntityRecord(
...
+	const batch = __experimentalCreateBatch( batchProcessor );
+
+	for ( const { kind, name, recordId, record } of spec ) {
+		if ( recordId ) {
+			dispatch( 'core' ).saveEditedEntityRecord( kind, name, recordId, {
```
Comment (noisysocks) [inline packages/core-data/src/actions.js:566]: This uses the global `dispatch`. Probably need to add a control which invokes `dispatch` from the current registry but doesn't wait for it to finish resolving.

```js
yield controls.dispatchAsync( 'core', 'saveEditedEntityRecord', kind, name, recordId, { __experimentalBatch: batch } );
```

File: packages/edit-widgets/src/store/actions.js [hunk 6]
```diff
@@ -160,17 +159,16 @@ export function* saveWidgetArea( widgetAreaId ) {
...
-				'root',
-				'widget',
-				widgetId,
-				widget
-			);
+			batchSpec.push( {
+				kind: 'root',
+				name: 'widget',
+				recordId: widgetId,
+			} );
```
Comment (talldan) [inline packages/edit-widgets/src/store/actions.js:166]: That's curious, was `saveEditedEntityRecord` being called incorrectly before? (with the last `widget` param).

File: packages/core-data/src/actions.js (hunk 4 above)
Comment (talldan) [reply packages/core-data/src/actions.js:561]: Hmm, yeah, I think whatever executes the batch shouldn't have to be aware of what's in the batch.

I was thinking that creation of the batch would happen in `saveEditedWidgetArea`:

```jsx
export function* saveWidgetArea( widgetAreaId ) {
    // ...
    // ... experimentalCreateBatch is a version of `createBatch` preconfigured with our batch 'processor'.
    const batch = __experimentalCreateBatch();
    // ...
    dispatch( 'core' ).saveEditedEntityRecord( 'root', 'widget', widgetId, { batch } );
    // ...
    // batch.run implicitly `waitsForSize`.
    batch.run();
}
```

Is it that we need to know the full batch size before calling `batch.run()`?

Potentially the batch could be made to be internally aware of that:
```jsx
// createItem increments the batchers internal count
const batchItem = batch.createItem();
// batchItem can add an item to a batch via its own method, e.g. `batchItem.addRequest`.
dispatch( 'core' ).saveEditedEntityRecord( 'root', 'widget', widgetId, { batchItem } );
```

The alternative is that the batch spec knows which method to call:
```jsx
batchSpec.push( {
    action: dispatch( 'core' ).saveEditedEntityRecord,
    args: [ 'root', 'widget', widgetId ],
} );
```

File: packages/data/src/batch.js (hunk 3 above)
Comment (talldan) [reply packages/data/src/batch.js:1]: Yeah, seems generic enough to be used for any kind of batching exercise.

I did a bit of staring at package names, but couldn't come up with anything better. Could probably live here in data while it's maturing. 🤷

File: packages/core-data/src/actions.js (hunk 4 above)
Comment (youknowriad) [reply packages/core-data/src/actions.js:561]: > I was thinking that creation of the batch would happen in saveEditedWidgetArea:

I'm not sure I understand why you  think the batch should be created out of core-data. Having the way it's now n the PR has the advantage of being an implementation detail and can make this useful for all screens (multi-entity  saving  flow).

Comment (talldan) [reply packages/core-data/src/actions.js:561]: > I'm not sure I understand why you think the batch should be created out of core-data. Having the way it's now n the PR has the advantage of being an implementation detail and can make this useful for all screens (multi-entity saving flow).

The way I'm describing, the batch processor would still be part of core data, so that indeed it can be used by all consumers of that package. We can have a generic `createBatch( processor )` function that can be used in any project. Core data can export a version of that that's preconfigured with its processor that uses the batch endpoint. That way it wouldn't have to be re-configured when imported.

What I was describing is that I think the way the batch is assembled could be different. At the moment `__experimentalBatchSaveEntityRecords` has to know how to call `saveEditedEntityRecord`, `saveEntityRecord`, `deleteEntityRecord` and so on, but I don't think it needs to, and I don't think this approach is scaleable. The processor should have just enough information to run the batch, but shouldn't need knowledge of our data API.

Comment (youknowriad) [reply packages/core-data/src/actions.js:561]: > I don't think it needs to, and I don't think this approach is scaleable

Why do you think it's not scalable enough?  For me `__experimentalBatchSaveEntityRecords` could be named just  `__experimentalSaveEntityRecords` and the batch be just an implementation detail external users of core-data might not even need to know about.

Comment (talldan) [reply packages/core-data/src/actions.js:561]: What if we want a batch that's not just for saving? I think that was the original main use case on the navigation screen where we want to be able to create, edit and delete menu items in a particular order.

Comment (youknowriad) [reply packages/core-data/src/actions.js:561]: > What if we want a batch that's not just for saving?

That's a good point, but I don't see how we could have a nice API for that while keeping the processor inside core-data.

File: packages/core-data/src/batch-processor.js [hunk 7]
```diff
@@ -0,0 +1,36 @@
+/**
+ * WordPress dependencies
+ */
+import apiFetch from '@wordpress/api-fetch';
+
+export default async function batchProcessor( requests ) {
```
Comment (TimothyBJacobs) [inline packages/core-data/src/batch-processor.js:6]: The only really comment I have is that this would be helpful to anyone who wants to use the REST API batching, not just those using the `core-data` package. So it'd be nice if it would live elsewhere, though I'm not sure where.

File: packages/core-data/src/batch-processor.js [hunk 8]
```diff
@@ -0,0 +1,36 @@
...
+		},
+	} );
+
+	if ( batchResponse.failed ) {
+		return batchResponse.responses.map( ( response ) => ( {
+			error: response?.body,
+		} ) );
+	}
+
+	return batchResponse.responses.map( ( response ) => {
```
Comment (TimothyBJacobs) [inline packages/core-data/src/batch-processor.js:27]: It'd be nice if those also checked against `request.parse` and when `false` created the full response object.

File: packages/core-data/src/actions.js (hunk 4 above)
Comment (noisysocks) [reply packages/core-data/src/actions.js]: Good ideas here! Seems there's three criteria:

1. The caller needs to be able to do different types of requests at once. (Save, delete, ...possibly more?)
2. The caller shouldn't have to care about what a "batch" is as that's implementation detail-ey.
3. The API should be "nice" 😛

Here's where I ended up after some iteration this afternoon:


```js
const [ newRecord, savedRecord, deletedRecord ] = await wp.data.dispatch( 'core' ).performBatch( [
	( { saveEntityRecord } ) => saveEntityRecord( 'root', 'widget', widget ),
	( { saveEditedEntityRecord } ) => saveEditedEntityRecord( 'root', 'widget', 123 ),
	( { deleteEntityRecord } ) => deleteEntityRecord( 'root', 'widget', 456 ),
] )
// Can use getLastEntitySaveError() or getLastEntityDeleteError() here if needed.
```

094e6e3363 implements this. I'm pretty happy with it as it feels to me like a pretty natural extension of the existing `core-data` API. Let me know what you think though.

Comment (youknowriad) [reply packages/core-data/src/actions.js]: Seing this make me wonder if it could be a "data" API

```
wp.data.batch( [
	( dispatch ) => dispatch('core').saveEntityRecord( 'root', 'widget', widget ),
	( dispatch ) => dispatch('core').saveEditedEntityRecord( 'root', 'widget', 123 ),
	( dispatch ) => dispatch('core').deleteEntityRecord( 'root', 'widget', 456 ),
] )
```

In an ideal world this would only trigger a single "subscribe" call at the end of the call.
It could also serve as a performance  optimization: for instance RichText does both onChange and onSelectionChange on the same tick. good candidate for a batch.

That said, it does seem a bit ambitious to start with so maybe we can just go with what we have as "experimental"

File: packages/core-data/src/actions.js (hunk 1 above)
Comment (adamziel) [reply packages/core-data/src/actions.js:452]: > Not sure why __unstableAwaitPromise is marked unstable.

I think it was initially merged with the locks PR, and all the APIs there were marked as unstable. Feel free to "stabilize" it :-)

**Comment by adamziel** [comment]
I like how it's more succinct, it's much easier to follow without going through the store for data. What I don't like is that we're losing the power of redux devtools. Maybe it could dispatch redux actions without any reducers as a compromise solution? There would be at least some visibility as to what's happening.

File: packages/core-data/src/actions.js (hunk 4 above)
Comment (noisysocks) [reply packages/core-data/src/actions.js]: That would be really cool 🙂

**Comment by noisysocks** [comment]
Not sure that it makes sense to dispatch an action if there's no reducer or control that does anything with it?

I agree with you though that this stuff is a pain to debug. It's because rungen adds a lot of indirection to the call stack which makes it difficult to use DevTools. I'd probably prefer that we fix that by moving away from rungen/controls to async functions i.e. https://github.com/WordPress/gutenberg/pull/27276.

File: packages/core-data/src/actions.js (hunk 1 above)
Comment (noisysocks) [reply packages/core-data/src/actions.js:468]: Going to keep it unstable because I hope we can remove it if https://github.com/WordPress/gutenberg/pull/27276 lands.

File: packages/data/src/batch.js (hunk 3 above)
Comment (noisysocks) [reply packages/data/src/batch.js]: It's all experimental and in `@wordpress/core-data` for now. We'll see how it evolves.

File: packages/edit-widgets/src/store/actions.js (hunk 6 above)
Comment (noisysocks) [reply packages/edit-widgets/src/store/actions.js]: Yeah the fourth argument of `saveEditedEntityRecord` is `options` so this just did nothing.

File: packages/core-data/src/batch-processor.js (hunk 7 above)
Comment (noisysocks) [reply packages/core-data/src/batch-processor.js]: Yeah, totally. Going to leave it as an experimental API in `core-data` for now though while the API matures. Maybe one day we'll do something like this https://github.com/WordPress/gutenberg/pull/28210#discussion_r559511878.

File: packages/core-data/src/batch-processor.js (hunk 8 above)
Comment (noisysocks) [reply packages/core-data/src/batch-processor.js]: Sorry not sure what you mean here?

**Comment by noisysocks** [comment]
I'm fairly happy with this. Just working on tests and documentation now and then I'll un-draft the PR.

I don't really like the `__unstableAwaitPromise` and `getDispatch` controls that I'm using in `__experimentalBatch`:

```js
export function* __experimentalBatch( tasks ) {
	const batch = createBatch();
	const dispatch = yield getDispatch();
	const api = { ... };
	const results = tasks.map( ( task ) => task( api ) );
	yield __unstableAwaitPromise( batch.run() );
	return yield __unstableAwaitPromise( Promise.all( results ) );
}
```

But I'm hopeful that something will come of https://github.com/WordPress/gutenberg/pull/27276 which will let us remove both of those:

```js
export const __experimentalBatch = ( tasks ) => ( { dispatch } ) => {
	const batch = createBatch();
	const api = { ... };
	const results = tasks.map( ( task ) => task( api ) );
	await batch.run();
	return await Promise.all( results );
};
```

**Comment by noisysocks** [comment]
All ready! I added tests, wrote some docs, and updated the PR description.

File: packages/core-data/src/actions.js [hunk 9]
```diff
@@ -543,6 +580,73 @@ export function* saveEntityRecord(
...
+						...options,
+						__unstableFetch: add,
+					}
+				)
+			);
+		},
+	};
+	const results = requests.map( ( request ) => request( api ) );
+	yield __unstableAwaitPromise( batch.run() );
+	return yield __unstableAwaitPromise( Promise.all( results ) );
```
Comment (jsnajdr) [inline packages/core-data/src/actions.js:647]: By adding some delay (caused by `await batch.run()`) between creating the `results` promises and awaiting them (in other words, adding `.then` and `.catch` handlers), you are opening your code to the following issue:
```js
const p = Promise.reject( 'myerror' );
setTimeout( () => {
  p.catch( error => {
    console.log( 'p failed with:', error );
  } );
}, 1000 );
```
Even though the `p` error is always caught and reported, you'll get a console warning about uncaught promise rejection:
```
Uncaught (in promise) myerror
```
Because the `catch` handler was attached too late. It wasn't present at the time when the promise rejected.

I don't know how to solve this in this specific case. Just wanted to point out that these warnings will happen.

**Comment by kevin940726** [comment]
Haven't looked into the diff yet, but after testing locally, seems like this PR fixes #28186 as well! 🎉

File: packages/core-data/src/batch/create-batch.js [hunk 10]
```diff
@@ -0,0 +1,146 @@
...
+				new Promise( ( resolve, reject ) => {
+					queue.push( {
+						input,
+						resolve,
+						reject,
+					} );
+
+					if ( ++actualSize === expectedSize ) {
+						onFull();
+					}
```
Comment (jsnajdr) [inline packages/core-data/src/batch/create-batch.js:85]: Comparing the `actualSize` and `expectedSize` solves the pressing issue with saving widgets, but as a general-purpose utility, it makes some assumptions that don't need to be always true.

Namely, it assumes that each call like:
```js
batch.add( add => {
  dispatch( 'core' ).saveSomething( { __fetch: add } );
} );
```
does exactly one fetch and calls the `add` callback exactly once. If the `saveSomething` action does two fetches or no fetch at all, it will break -- either by waiting forever or stopping the wait too early.

`saveEditedEntityRecord` will skip the fetch if the record supplied doesn't have any edits, for example.

I don't know how to solve this better. Maybe after rewritten from generators to normal async functions, the code will be clearer and easier to reason about and some solutions will pop up.

Comment (noisysocks) [reply packages/core-data/src/batch/create-batch.js]: Good catch @jsnajdr. I've tweaked it so that `run` will unpause if `thunk` resolves or returns without calling `add()`. See 79d9829b2f.

Agree that switching to `async` functions will at least make this easier to follow.

File: packages/core-data/src/actions.js (hunk 9 above)
Comment (noisysocks) [reply packages/core-data/src/actions.js:647]: Hmmm. I don't know enough about how `Promise` detects uncaught errors. Would something like this work?

```js
const [ , ...results ] = yield __unstableAwaitPromise(
	Promise.all( [
		batch.run(),
		...requests.map( ( request ) => request( api ) ),
	] )
);
return results;
```

Comment (adamziel) [reply packages/core-data/src/actions.js:647]: @noisysocks the warning will happen when the rejection happen before error handler is bound; your example would probably work

Comment (noisysocks) [reply packages/core-data/src/actions.js]: 👍 23bc3f2d6b

File: packages/core-data/src/batch/test/create-batch.js [hunk 11]
```diff
@@ -0,0 +1,106 @@
...
+		const processor = async ( inputs ) =>
+			inputs.map( ( input ) => ( {
+				output: input,
+			} ) );
+		const batch = createBatch( processor );
+		const promise1 = batch.add( 1 );
+		const promise2 = batch.add( 2 );
+		expect( await batch.run() ).toBe( true );
+		expect( await promise1 ).toBe( 1 );
+		expect( await promise2 ).toBe( 2 );
```
Comment (kevin940726) [inline packages/core-data/src/batch/test/create-batch.js:23]: Maybe we would also want to test if both `promise1` and `promise2` have been fulfilled if `batch.run()` has been fulfilled. Something like:

```js
let promise1Value = null;
let promise2Value = null;
batch.add(1).then((value) => { promise1Value = value });
batch.add(2).then((value) => { promise2Value = value });
expect(await batch.run()).toBe(true);
expect(promise1Value).toBe(1):
expect(promise2Value).toBe(2):
```

**Review by kevin940726 — COMMENTED** [review]
Great work! Just some tiny code suggestions for now.

File: packages/core-data/src/batch/create-batch.js [hunk 12]
```diff
@@ -0,0 +1,189 @@
...
+		},
+
+		/**
+		 * Runs the batch. This calls `batchProcessor` and resolves or rejects
+		 * all promises returned by `add()`.
+		 *
+		 * @return {Promise} A promise that resolves to a boolean that is true
+		 *                   if the processor returned no errors.
+		 */
+		async run() {
```
[the remark this answers is not in the document]
Comment (adamziel) [reply packages/core-data/src/batch/create-batch.js:106]: Or just return cached `isSuccess` value early

File: packages/core-data/src/batch/create-batch.js [hunk 13]
```diff
@@ -0,0 +1,189 @@
...
+
+	get size() {
+		return this.set.size;
+	}
+
+	add( ...args ) {
+		this.set.add( ...args );
+		for ( const subscriber of this.subscribers ) {
+			subscriber();
+		}
```
[the remark this answers is not in the document]
Comment (adamziel) [reply packages/core-data/src/batch/create-batch.js:171]: A-ha, another place using observables – we're getting closer to using Rx.js or kefir at some point :-)

[the remark this answers is not in the document]
Comment (noisysocks) [reply packages/core-data/src/batch/create-batch.js:171]: I had this inlined but split it out into `ObservableSet` because I think it's easier to follow when `createBatch` has less state in it to manage. Plus, this is future proof in that we can delete `ObservableSet` if we ever add an observable library to Gutenberg 🙂

File: packages/core-data/src/batch/test/create-batch.js (hunk 11 above)
Comment (noisysocks) [reply packages/core-data/src/batch/test/create-batch.js:23]: Doesn't this test the same thing? Not sure I understand.

File: packages/core-data/src/batch/create-batch.js (hunk 12 above)
[the remark this answers is not in the document]
Comment (noisysocks) [reply packages/core-data/src/batch/create-batch.js:106]: I made it so that `run()` empties the queue when finished.

8217c05af7

File: packages/core-data/src/batch/create-batch.js [hunk 14]
```diff
@@ -0,0 +1,189 @@
...
+		return isSuccess;
+	}
+
+	subscribe( subscriber ) {
+		this.subscribers.push( subscriber );
+		return () => {
+			this.subscribers = without( this.subscribers, subscriber );
```
[the remark this answers is not in the document]
Comment (noisysocks) [reply packages/core-data/src/batch/create-batch.js:186]: I didn't do this because insertion order is probably important but turns out the spec guarantees that iterating a set is done in insertion order! TIL.

36274d4625

File: packages/core-data/src/batch/test/create-batch.js (hunk 11 above)
Comment (kevin940726) [reply packages/core-data/src/batch/test/create-batch.js:23]: I don't think the original way tests that the promises would fulfilled once `batch` has finished.

`promise1` and `promise2` could still be pending after `batch.run()` has been fulfilled.

Comment (noisysocks) [reply packages/core-data/src/batch/test/create-batch.js:23]: Ah! Gotcha. That's probably what I want to do for all tests.

Comment (noisysocks) [reply packages/core-data/src/batch/test/create-batch.js:23]: 34db07a19b

**Review by kevin940726 — APPROVED** [review]
LGTM 👍. Thanks a lot!

**Comment by TimothyBJacobs** [comment]
Is this respecting the batch size limit? See https://make.wordpress.org/core/2020/11/20/rest-api-batch-framework-in-wordpress-5-6/

**Comment by noisysocks** [comment]
No, oops. I'll turn your comment into an issue.

File: packages/core-data/src/batch/create-batch.js [hunk 15]
```diff
@@ -0,0 +1,187 @@
...
+		 * // Both are allowed:
+		 * batch.add( { path: '/v1/books', ... } );
+		 * batch.add( ( add ) => add( { path: '/v1/books', ... } ) );
+		 * ```
+		 *
+		 * If a thunk is passed, `batch.run()` will pause until either:
+		 *
+		 * - The thunk calls its `add` argument, or;
+		 * - The thunk returns a promise and that promise resolves, or;
+		 * - The thunk returns a non-promise.
```
Comment (dmsnell) [inline packages/core-data/src/batch/create-batch.js:67]: @noisysocks can you clarify the intention of the second and third options here? it seems to suggest that we can do this…

```ts
batch.add( () => Promise.resolve({ path: '/v1/books', ... }) );
```

or this…

```ts
batch.add( () => ({ path: '/v1/books', ... }) );
```

…however, if we do that, then `Promise.resolve(fetchOptionsProducer( queueForResolution))` will return the API request description and not the data requested in the batch operation.

- Am I misunderstanding the comment?
- Did we intend on eventually providing this functionality?
- Is this an un-noticed bug in the code?

I'm working on the types for this module and got stuck trying to understand the purpose here. I'm inclined to remove the second and third options since the only examples and existing core code only demonstrate the first.

File: packages/core-data/src/batch/create-batch.js [hunk 16]
```diff
@@ -0,0 +1,187 @@
...
+
+			for ( const [ result, { resolve, reject } ] of zip(
+				results,
+				queue
+			) ) {
+				if ( result?.error ) {
+					reject( result.error );
+					isSuccess = false;
+				} else {
+					resolve( result?.output ?? result );
```
Comment (dmsnell) [inline packages/core-data/src/batch/create-batch.js:148]: this seems to be a violation of the contract we provide for the output `Promise`. It seems possible that we added this so we could write tests that violate the input contract.

I noticed that the tests pass values like `1` and `2` and we test processors that return non-object. Are these intentionally valid use-cases of the function? if so, what are the reasons for allowing that? should we require that alternative processors conform to the `{ output } | { error }` structure?

Do we know of any alternative processors in use (apart from the core tests here)?

File: packages/core-data/src/batch/create-batch.js (hunk 15 above)
Comment (noisysocks) [reply packages/core-data/src/batch/create-batch.js:67]: > …however, if we do that, then `Promise.resolve(fetchOptionsProducer( queueForResolution))` will return the API request description and not the data requested in the batch operation.

I'm not sure what you mean here. What's `fetchOptionsProducer`?

---

From memory this was all about preventing `run()` from pausing infinitely if `add()` is called with a thunk and that thunk never calls the function passed to it.

The comment is describing the effect of this code below:

```js
return Promise.resolve( inputOrThunk( add ) ).finally( () => {
	pending.delete( id );
} );
```

> - The thunk calls its `add` argument, or;

```js
const batch = createBatch();
batch.add( ( add ) => async {
	await sleep( 100 );
	add( {} ); // run() will resume here
	await sleep( 100 );
} );
batch.run(); // will pause for 100 ms
```

> - The thunk returns a promise and that promise resolves, or;

```js
const batch = createBatch();
batch.add( ( add ) => async {
	await sleep( 100 );
	await sleep( 100 );
	// run() will resume here when promise resolves
} );
batch.run(); // will pause for 200 ms
```

> - The thunk returns a non-promise.

```js
const batch = createBatch();
batch.add( ( add ) => {
	// run() will resume here as a non-promise is returned
} );
batch.run(); // will pause for 0 ms
```

---

> I'm working on the types for this module

I think it'd be something like this.

```typescript
interface Batch<TInput, TOutput> {
    add<TThunkResult>( inputOrThunk: TInput|( ( add: ( input: TInput ) => Promise<TOutput> ) => TThunkResult|Promise<TThunkResult> ) ): Promise<TOutput>|Promise<TThunkResult>;
}

function createBatch<TInput, TOutput>( processor: ( inputs: TInput[] ) => Promise<{output?: TOutput, error?: any}[]> ): Batch<TInput, TOutput> {
}
```

> I'm inclined to remove the second and third options since the only examples and existing core code only demonstrate the first.

Feel free to simplify! It's `__experimental` so should be okay to change. I believe the unit tests and usage in `@wordpress/core-data` cover everything we need `createBatch` to do.

File: packages/core-data/src/batch/create-batch.js (hunk 16 above)
Comment (noisysocks) [reply packages/core-data/src/batch/create-batch.js:148]: Good catch, this is an undocumented shorthand for specifying a result.

I'm fine with updating the tests and removing the shorthand so that this is simply `resolve( result.output )`. 

Alternatively, `processor` could have a type of `( inputs: TInput[] ) => Promise<({output: TOutput}|{error: any}|TOutput)[]>`. Why make it hard for ourselves though? 😀

> Do we know of any alternative processors in use (apart from the core tests here)?

I believe only the default processor is used by Gutenberg. I'd be surprised if third parties have used this API as it's pretty niche.
