### PR TITLE
UnitControl: Fix an issue where keyboard shortcuts unintentionally shift focus on Windows OS

### LINKED ISSUE #62967: [Input] - Impossible to paste a value in all input fields with CTRL +V
### Description

It's impossible to paste a value in all input fields with CTRL +V, it seems to trigger a TAB

### Step-by-step reproduction instructions

1. Go to admin right panel 
2. Copy a value CTRL + C
3. Try to paste this value in another field with CTRL + V

### Screenshots, screen recording, code snippet

[353c2e5b-36ab-4848-a1d2-e4aa6ffd3995.webm](https://github.com/WordPress/gutenberg/assets/62699215/26edecf8-8b5f-424e-b12e-f5559c581af0)

### Environment info

- WP 6.5.5
- Every themes
- Windows 10
- Chrome 126.0.0.0, Firefox 127.0, Edge 126.0.2592.68

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Follow-up #39303
Fixes #62967

## What?

This PR fixes an issue where the focus unintentionally moves to the unit when executing the paste shortcut (`Ctrl+V`) in an input field on Windows OS.

## Why?
Only `event.metaKey` is checked to give focus to the unit, which may work on MacOS, but on Windows OS the `Ctrl` key is `event.ctrlKey`.

## Testing Instructions

The following are test procedures for Windows OS, but they should continue to work as expected on MacOS.

- Run the Storybook.
- Access `localhost:50240/?path=/docs/components-experimental-unitcontrol--docs`
- Copy the numbers beforehand.
- Run `Ctrl+V` in the input field.
- The copied numbers should be pasted.
- Press only the `p`, `v` or `e` key.
- The focus should move to the unit, and the unit should change according to the key pressed.

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/54422211/536a7482-90e5-4ebd-98ab-83557b403626

### CODE REVIEW

File: packages/components/src/unit-control/index.tsx [hunk 1]
```diff
@@ -172,6 +172,7 @@ function UnforwardedUnitControl(
 			// matches the first character of a unit.
 			if (
 				! event.metaKey &&
+				! event.ctrlKey &&
```
Comment (tyxla) [inline packages/components/src/unit-control/index.tsx:175]: Let's also update the comment above (to reference the `ctrl` key in addition to the `meta` key).

**Review by tyxla — APPROVED** [review]
LGTM, thanks @t-hamano 🙌 

I'd only update the inline comment above your change before shipping.

Otherwise, ready to 🚀

File: packages/components/src/unit-control/index.tsx (hunk 1 above)
Comment (t-hamano) [reply packages/components/src/unit-control/index.tsx:175]: Thanks for the review! Updated by b90cc5a
