### PR TITLE
Fix site editor redirection after creating new template or template part

### LINKED ISSUE #49346: Add Template modal: inconsistent behavior on WP 6.2
### Description

When creating a new template for an individual post, the user is not always led to the edit screen:

### Scenario 1 (expected):

https://user-images.githubusercontent.com/15730971/227565922-e10729c3-77be-45ce-a136-dd36b7c1a800.mov

### Scenario 2 (the new template is still created, but the user is not directed to it, and the modal doesn't close):

https://user-images.githubusercontent.com/15730971/227566061-c00f6cce-300c-4123-a571-2503ecbfb089.mov

### Step-by-step reproduction instructions

1. Make sure you have an install running with the Twenty Twenty three theme and WordPress version 6.2
2. As demonstrated on the screencasts above, head over to Edit site > Templates >  Manage All Templates > Add New > Single item: Post
3. Select a post to create a template for it
4. Notice how the modal doesn't close, and you are not directed to the new template after creation. Important: given the random nature of the issue, it is possible that you won't be able to reproduce on the first attempt; continue to create a few more templates for individual posts until you do.

### Environment info

- WordPress 6.2
- Twenty Twenty-Three theme
- Browser: Chrome Version 111.0.5563.110 (Official Build) (arm64)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/49346

From the issue:
>When creating a new template for an individual post, the user is not always led to the edit screen:

Noting that this is the case for `Template Parts` too.

### Scenario 1 (expected):

https://user-images.githubusercontent.com/15730971/227565922-e10729c3-77be-45ce-a136-dd36b7c1a800.mov

### Scenario 2 (the new template is still created, but the user is not directed to it, and the modal doesn't close):

https://user-images.githubusercontent.com/15730971/227566061-c00f6cce-300c-4123-a571-2503ecbfb089.mov

### Step-by-step reproduction instructions

1. Make sure you have an install running with the Twenty Twenty three theme and WordPress version 6.2
2. As demonstrated on the screencasts above, head over to Edit site > Templates >  Manage All Templates > Add New > Single item: Post
3. Select a post to create a template for it
4. Notice how the modal doesn't close, and you are not directed to the new template after creation. Important: given the random nature of the issue, it is possible that you won't be able to reproduce on the first attempt; continue to create a few more templates for individual posts until you do.

## How?

When we create a new template or template part in site editor we first update the `canvas mode`(setCanvasMode( 'edit' )) to the store before pushing to the `history`.  This sometimes can lead to race conditions with `useSyncCanvasModeWithURL` hook that then replaces the proper url with the previous one and just adding the `canvas=edit` param. The current syncing is susceptible to race conditions in different parts of code, but I didn't investigate in depth for now. It's something we need to have in mind.

This PR adds the correct `canvas` mode directly so we don't need the syncing logic there. 

## Testing Instructions in this PR
1. Make sure the redirection happens always and history(back in sidebar and browser) still works as expected.

### CODE REVIEW

File: packages/edit-site/src/components/add-new-template/new-template.js [hunk 1]
```diff
@@ -125,20 +123,19 @@ export default function NewTemplate( {
...
 				postType: newTemplate.type,
+				canvas: 'edit',
 			} );
 
 			createSuccessNotice(
 				sprintf(
 					// translators: %s: Title of the created template e.g: "Category".
 					__( '"%s" successfully created.' ),
-					title
+					newTemplate.title?.rendered || title
```
Comment (ntsekouras) [inline packages/edit-site/src/components/add-new-template/new-template.js]: This is not related to the main bug, but it's a minor change to show the proper new template title and not the `slug`.

Comment (ntsekouras) [reply packages/edit-site/src/components/add-new-template/new-template.js]: I removed this from this PR and will just open a small follow up, since this might be included in 6.2 and should have just the fix.

**Comment by youknowriad** [comment]
Do we have an e2e test that cover this part? Feels like a good one to add (if we don't have) to avoid regressions.

**Review by youknowriad — APPROVED** [review]

**Review by Mamaduka — APPROVED** [review]

**Review by aristath — APPROVED** [review]

**Comment by ntsekouras** [comment]
>Do we have an e2e test that cover this part? 

I'll write one and then land. Thanks for the reviews!

File: test/e2e/specs/site-editor/site-editor-url-navigation.spec.js [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+								.includes(
+									'/index.php?rest_route=%2Fwp%2Fv2%2Fposts&context=view'
+								) && resp.status() === 200
+					),
+					page.click( 'role=button[name="Templates"]' ),
+				] );
+				await page.click( 'role=button[name="Add New Template"i]' );
+				await page
+					.getByRole( 'menuitem', {
+						name: /Single item: Post./i,
```
Comment (kevin940726) [inline test/e2e/specs/site-editor/site-editor-url-navigation.spec.js]: Nit: In `getByRole`'s `name` field, it defaults to case-insensitive partial text match, so it's the same here as `Single item: Post.`.

Note that though, `.` in regex has a different meaning, that's probably not you wanted here?

The same goes for other regex-based `name`s below.

File: test/e2e/specs/site-editor/site-editor-url-navigation.spec.js [hunk 3]
```diff
@@ -0,0 +1,86 @@
...
+			} ) => {
+				await requestUtils.createPost( {
+					title: 'Demo',
+					status: 'publish',
+				} );
+				await admin.visitSiteEditor();
+				// We need to wait the response from the `posts` request in order to click the augmented menu item,
+				// that includes the options for creating templates for specific posts.
+				await Promise.all( [
+					page.waitForResponse(
```
Comment (kevin940726) [inline test/e2e/specs/site-editor/site-editor-url-navigation.spec.js]: Just being curious, do we have a UI hint for such things? Is waiting for the post list enough in this case?

File: test/e2e/specs/site-editor/site-editor-url-navigation.spec.js [hunk 4]
```diff
@@ -0,0 +1,86 @@
...
+		await requestUtils.activateTheme( 'emptytheme' );
+	} );
+
+	test.afterAll( async ( { requestUtils } ) => {
+		await Promise.all( [
+			requestUtils.activateTheme( 'twentytwentyone' ),
+			// Fallback clean-up in case of failure.
+			requestUtils.deleteAllPosts(),
+			requestUtils.deleteAllTemplates( 'wp_template' ),
+			requestUtils.deleteAllTemplates( 'wp_template_part' ),
```
Comment (kevin940726) [inline test/e2e/specs/site-editor/site-editor-url-navigation.spec.js]: How about cleaning up in `afterEach` so that we don't have to do the same in each test below?

File: test/e2e/specs/site-editor/site-editor-url-navigation.spec.js (hunk 3 above)
Comment (ntsekouras) [reply test/e2e/specs/site-editor/site-editor-url-navigation.spec.js]: No we don't. This should be improved, but it's out of scope of this PR.

File: test/e2e/specs/site-editor/site-editor-url-navigation.spec.js (hunk 4 above)
Comment (ntsekouras) [reply test/e2e/specs/site-editor/site-editor-url-navigation.spec.js]: Normally this wouldn't be needed if the testing environment is recreated, but I'm not sure about that. Locally it doesn't so it kept the created entities.

What do you think it's better?
1. `afterEach` even we don't create all the type of entities in each test
2. remove it completely from an `after` block

File: test/e2e/specs/site-editor/site-editor-url-navigation.spec.js (hunk 2 above)
Comment (ntsekouras) [reply test/e2e/specs/site-editor/site-editor-url-navigation.spec.js]: Good catch, thanks! I'll update.

File: test/e2e/specs/site-editor/site-editor-url-navigation.spec.js (hunk 4 above)
Comment (kevin940726) [reply test/e2e/specs/site-editor/site-editor-url-navigation.spec.js]: We share the same WordPress instance for all tests, unfortunately. I would love to have isolated testing environments too, but that's difficult for WordPress environment I guess 🤔 .

Normally, cleaning up things in `afterEach` is better, because even if the test fails it could still run the necessary tasks to clean up the state. And since that we use `requestUtils`, which calls REST API internally, it should be fast even if we are over-cleaning.

File: test/e2e/specs/site-editor/site-editor-url-navigation.spec.js [hunk 5]
```diff
@@ -0,0 +1,81 @@
...
+								.includes(
+									'/index.php?rest_route=%2Fwp%2Fv2%2Fposts&context=view'
+								) && resp.status() === 200
+					),
+					page.click( 'role=button[name="Templates"]' ),
+				] );
+				await page.click( 'role=button[name="Add New Template"i]' );
+				await page
+					.getByRole( 'menuitem', {
+						name: /Single item: Post/,
```
Comment (kevin940726) [inline test/e2e/specs/site-editor/site-editor-url-navigation.spec.js]: Oops, I mean the original was the same as string literal:

```suggestion
						name: 'Single item: Post',
```

By using the regex syntax we are effectively opting out of the default text-matching behavior.

Comment (ntsekouras) [reply test/e2e/specs/site-editor/site-editor-url-navigation.spec.js]: Got it. I updated the rest usages too.

**Comment by Mamaduka** [comment]
I just cherry-picked this PR to the wp/6.2 branch to get it included in the next release: 2bb49889ce
