### PR TITLE
Polish menus and focus styles

### LINKED ISSUE #6734: More Menu shows overly verbose shortcut
**Describe the bug**
Shortcut menu shows too long shortcut description.

screen shot 2018-05-14 at 11 22 30

**Expected behavior**

Something like this:

screen shot 2018-05-14 at 11 28 20

**Desktop (please complete the following information):**

MacOS and Chrome

@tofumatt  @iseulde I think maybe you were looking at this recently?

### PR DESCRIPTION
**Pull request by jasmussen**
This fixes a regression in menu focus styles that was introduced as part of some focus fixes to the movers way back.

It also fixes #6734, as it changes how the shortcuts are spelled out.

screen shot 2018-05-18 at 09 37 06

screen shot 2018-05-18 at 09 37 12

### CODE REVIEW

**Comment by gziolo** [comment]
Nice, `More Menu` is getting fixed. I'm not sure why those keyboard shortcuts were updated in the first place, so I will leave review to others :)

**Comment by jasmussen** [comment]
I think I also fixed the Block More Menu btw.

**Review by karmatosed — APPROVED** [review]
👍 on design review

**Comment by jasmussen** [comment]
Rebased, and fixed an issue as a result of the buttons refactor. I think this is ready to go.

File: utils/keycodes.js [hunk 1]
```diff
@@ -74,10 +74,10 @@ export const displayShortcut = mapValues( modifiers, ( modifier ) => {
 	return ( character, _isMac = isMacOS ) => {
 		const isMac = _isMac();
 		const replacementKeyMap = {
-			[ ALT ]: isMac ? '⌥option' : 'Alt',
-			[ CTRL ]: isMac ? '⌃control' : 'Ctrl',
+			[ ALT ]: isMac ? 'Option' : 'Alt',
+			[ CTRL ]: isMac ? 'Ctrl' : 'Ctrl',
 			[ COMMAND ]: '⌘',
-			[ SHIFT ]: isMac ? '⇧shift' : 'Shift',
+			[ SHIFT ]: isMac ? 'Shift' : 'Shift',
```
Comment (iseulde) [inline utils/keycodes.js]: This could be simplified to `[ SHIFT ]: 'Shift',`.

**Review by ellatrix — APPROVED** [review]

**Comment by jasmussen** [comment]
Addressed feedback, rebased, and merging if the checks pass. Thanks!
