### PR TITLE
BaseControl: Fix VisualLabel styles

### LINKED ISSUE #35785: Video block settings: Poster image label needs spacing
### Description

In the Video block settings, the Poster image label has no bottom margin or padding. The margin was intentionally increased from 4px to 8px in #20754, but that has been missing since WordPress 5.6.

Should the label use `StyledLabel` instead of `BaseControl.VisualLabel`?
https://github.com/WordPress/gutenberg/blob/e192d5058b90cd906e4955a24640f0c94a541a77/packages/block-library/src/video/edit.js#L201-L203

(originally [reported on Trac](https://core.trac.wordpress.org/ticket/54263))

### Step-by-step reproduction instructions

1. Open the post editor.
2. Add a Video block, and upload or select a video.
3. Make sure the settings sidebar is open and scroll to view the Poster image control with no spacing between the label and the button.
4. Select a poster image to see the focus outline obscure part of the label text.

### Screenshots, screen recording, code snippet

Before selecting a poster image:

poster image label in sidebar

With the poster image:

poster image label with Replace button and its focus outline

(screenshots taken in my 5.9 trunk installation, without the plugin)

### Environment info

- WP 5.8.1, with and without Gutenberg 11.7.0
- Firefox 93
- Windows 10 20H2 Home

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
PR adds missing styles for `BaseControl.VisualLabel`. It was regression after #25842.

Resolves #35785.

## How has this been tested?
I tested based on issue instructions:

1. Open post editor.
2. Add a video block, upload, or select video.
3. Check that the "Poster image" visual label, in Video Settings, has a bottom margin.

## Screenshots 
| Before | After |
| --- | --- |
|CleanShot 2022-01-06 at 17 41 49|CleanShot 2022-01-06 at 17 36 11|

## Types of changes
Regression

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by ciampo** [comment]
> It was regression after #25842

Out of curiosity, could you point out the offending code that introduced the regression in #25842 ?

The changes overall LGTM, but I'd appreciate if folks who recently worked on ensuring label alignment also had a look (cc @andrewserong @aaronrobertshaw @mirka )

**Comment by Mamaduka** [comment]
With #25842, we started using styled-components, and #29550 removed styles files. So I guess regression was caused by both PRs together.

File: packages/components/src/base-control/styles/base-control-styles.js [hunk 1]
```diff
@@ -32,3 +32,8 @@ export const StyledHelp = styled.p`
 	font-style: normal;
 	color: ${ COLORS.mediumGray.text };
 `;
+
+export const StyledVisualLabel = styled.span`
+	display: inline-block;
+	margin-bottom: ${ space( 2 ) };
+`;
```
Comment (ciampo) [inline packages/components/src/base-control/styles/base-control-styles.js]: Since this label shares the same styles as the `StyledLabel`, we could refactor the code to something like:

```diff
diff --git a/packages/components/src/base-control/styles/base-control-styles.js b/packages/components/src/base-control/styles/base-control-styles.js
index c46c5e7ddb..c64272a17c 100644
--- a/packages/components/src/base-control/styles/base-control-styles.js
+++ b/packages/components/src/base-control/styles/base-control-styles.js
@@ -2,6 +2,7 @@
  * External dependencies
  */
 import styled from '@emotion/styled';
+import { css } from '@emotion/react';
 
 /**
  * Internal dependencies
@@ -22,11 +23,15 @@ export const StyledField = styled.div`
 	}
 `;
 
-export const StyledLabel = styled.label`
+const labelStyles = css`
 	display: inline-block;
 	margin-bottom: ${ space( 2 ) };
 `;
 
+export const StyledLabel = styled.label`
+	${ labelStyles };
+`;
+
 export const StyledHelp = styled.p`
 	font-size: ${ font( 'helpText.fontSize' ) };
 	font-style: normal;
@@ -34,6 +39,5 @@ export const StyledHelp = styled.p`
 `;
 
 export const StyledVisualLabel = styled.span`
-	display: inline-block;
-	margin-bottom: ${ space( 2 ) };
+	${ labelStyles };
 `;
```

**Review by ciampo — COMMENTED** [review]
> With #25842, we started using styled-components, and #29550 removed styles files. So I guess regression was caused by both PRs together.

Gotcha! Thank you for the explanation.

I went ahead and left a comment while [waiting for other folks to have a look too](https://github.com/WordPress/gutenberg/pull/37747#issuecomment-1007303143).

**Comment by ciampo** [comment]
Would you mind also adding a CHANGELOG entry for the components package?

File: packages/components/src/base-control/styles/base-control-styles.js (hunk 1 above)
Comment (Mamaduka) [reply packages/components/src/base-control/styles/base-control-styles.js]: Updated in c74c9fe.

**Review by andrewserong — APPROVED** [review]
Thanks for the ping @ciampo and for the PR @Mamaduka!

This tests well for me, the `8px` bottom margin is consistent with the other label margins that I've looked at recently (e.g. the [TextTransformControl](https://github.com/wordpress/gutenberg/blob/a7e2895829c16ecd77a5ba22d84f1dee1cfb0977/packages/block-editor/src/components/text-transform-control/index.js#L41)), and I've tested this change with all the Typography controls that use the ToolsPanel and can't find any other obvious inconsistencies there.

I think the main other label margin that looks different is the `SelectControl`'s label which currently uses a `4px` bottom padding via the `InputControl` component [here](https://github.com/wordpress/gutenberg/blob/efc523f8fc216b654b79ffb3fffa67b58dd37cd6/packages/components/src/input-control/styles/input-control-styles.tsx#L236). It's visible on the Preload dropdown in the Video block:



But I think we could look at improving the consistency there in a separate PR if we'd like to follow-up on that component. This change LGTM!

**Comment by Mamaduka** [comment]
Thanks for testing, @andrewserong and @ciampo.

**Review by aaronrobertshaw — COMMENTED** [review]
Looks like I was a few minutes too late to the party 🙂 

This tested well for me. I couldn't spot any issues other than the minor difference with the SelectControl's label that @andrewserong mentioned. Everything else checked out for me in terms of various block supports' ToolsPanels and the Global Styles.

Thanks for putting this one together 👍
