### PR TITLE
Button Block: Add back compat for WP6.4 regarding HTML Tag Processor

### LINKED ISSUE #62986: Gutenberg 18.6.1 causes fatal error with WordPress 6.4.5
### Description

This is a problem that first appeared on a Multisite with ~500 sites, but was then replicated on a fresh WordPress multisite with no other plugins enabled. 

Gutenberg plugin is causing a fatal error when activated on a WordPress running 6.4.5

```
Fatal error: Uncaught Error: Call to undefined method WP_HTML_Tag_Processor::next_token() in /home/edbecksu/demo.ed-beck.com/gutenberg/wp-content/plugins/gutenberg/build/block-library/blocks/button.php:44 Stack trace: #0 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/class-wp-block.php(258): gutenberg_render_block_core_button(Array, '\n\t\t\t<div class=...', Object(WP_Block)) 
#1 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/class-wp-block.php(244): WP_Block->render() 
#2 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/class-wp-block.php(244): WP_Block->render() 
#3 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/class-wp-block.php(244): WP_Block->render() 
#4 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/blocks.php(1512): WP_Block->render() 
#5 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/blocks.php(1550): render_block(Array) 
#6 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-content/plugins/gutenberg/build/block-library/blocks/pattern.php(70): do_blocks('\n<!-- wp:group ...') 
#7 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/class-wp-block.php(258): gutenberg_render_block_core_pattern(Array, '', Object(WP_Block)) 
#8 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/blocks.php(1512): WP_Block->render() 
#9 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/blocks.php(1550): render_block(Array) 
#10 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-content/plugins/gutenberg/build/block-library/blocks/pattern.php(70): do_blocks('\n<!-- wp:patter...') 
#11 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/class-wp-block.php(258): gutenberg_render_block_core_pattern(Array, '', Object(WP_Block)) 
#12 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/class-wp-block.php(244): WP_Block->render() 
#13 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/blocks.php(1512): WP_Block->render() 
#14 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/blocks.php(1550): render_block(Array) 
#15 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-content/plugins/gutenberg/build/block-library/blocks/pattern.php(70): do_blocks('\n<!-- wp:templa...') 
#16 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/class-wp-block.php(258): gutenberg_render_block_core_pattern(Array, '', Object(WP_Block)) 
#17 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/blocks.php(1512): WP_Block->render() 
#18 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/blocks.php(1550): render_block(Array) 
#19 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/block-template.php(263): do_blocks('<!-- wp:pattern...') 
#20 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/template-canvas.php(12): get_the_block_template_html() 
#21 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-includes/template-loader.php(106): include('/home/edbecksu/...') 
#22 /home/edbecksu/demo.ed-beck.com/gutenberg/wp-blog-header.php(19): require_once('/home/edbecksu/...') 
#23 /home/edbecksu/demo.ed-beck.com/gutenberg/index.php(17): require('/home/edbecksu/...') 
#24 {main} thrown in /home/edbecksu/demo.ed-beck.com/gutenberg/wp-content/plugins/gutenberg/build/block-library/blocks/button.php on line 44
```

### Step-by-step reproduction instructions

1. Install a fresh WordPress Multisite running WordPress 6.4.5
2. Install and activate the Gutenberg plugin
3. The site will have a critical error / white screen

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress Version 6.4.5 
- Gutenberg Version 18.6.1
- Theme Twenty Twenty Four

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #62986

## What?
This PR fixes a fatal error in the Button block, caused by the `WP_HTML_Tag_Processor` class in WP6.4 not yet having the `next_token()` method.

```
Fatal error: Uncaught Error: Call to undefined method WP_HTML_Tag_Processor::next_token() in /var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/button.php:44
```

## How?

A class with the next_token method exists in the Gutenberg plugin as `Gutenberg_HTML_Tag_Processor_6_5`. I set it up so that this class is used if the `IS_GUTENBERG_PLUGIN` variable is `true`. This prevents a critical error that occurs when the Gutenberg plugin is used in WP6.4.

In my opinion, the following flow would allow us to maintain full backward compatibility:

1. July 3rd (today): Gutenberg 18.7 was released.
2. Merge this PR.
3. July 16th: WordPress 6.6 will be officially released.
4. July 17th: Gutenberg 18.8 will be shipped with this PR included, which will fix the issue with WP6.4.
5. The Gutenberg plugin will drop support for WP6.4.
6. (TODO) Remove the fallback approach made in this PR.

## Testing Instructions

- Deactivate the Gutenberg plugin and downgrade to WP 6.4.
- Insert a Button block into a post and publish it.
- Activate the Gutenberg plugin and visit the post.
  - trunk: You will get a critical error.
  - This PR: You should not get a critical error and the Button block should render.

### CODE REVIEW

File: packages/block-library/src/button/index.php [hunk 1]
```diff
@@ -17,7 +17,20 @@
...
+	 *
+	 * TODO: After the Gutenberg plugin drops support for WordPress 6.4, this
+	 * conditional statement will be removed and the core class `WP_HTML_Tag_Processor`
+	 * should be used.
+	 */
+	if ( defined( 'IS_GUTENBERG_PLUGIN' ) && IS_GUTENBERG_PLUGIN && class_exists( 'Gutenberg_HTML_Tag_Processor_6_5' ) ) {
+		$p = new Gutenberg_HTML_Tag_Processor_6_5( $content );
+	} else {
+		$p = new WP_HTML_Tag_Processor( $content );
+	}
```
Comment (dmsnell) [inline packages/block-library/src/button/index.php:33]: I don't think we want to do this here, preferring instead to just rely on the compatibility layer. When this code gets brought into Core the `Gutenberg_` function should be replaced by the `WP_` one. See `WP_Interactivity_API_Directives_Processor` for another example

Comment (t-hamano) [reply packages/block-library/src/button/index.php:33]: Thanks for the review!

As far as I can tell, the only class that inherits the `Gutenberg_HTML_Tag_Processor_6_5` class is `WP_Interactivity_API_Directives_Processor`.

Does this mean that the `WP_Interactivity_API_Directives_Processor` class should also be used in this part?

Comment (dmsnell) [reply packages/block-library/src/button/index.php:33]: No I only meant that we should be fine here using

```php
$p = new Gutenberg_HTML_Tag_Processor_6_5( $content );
```

…and skipping the conditional. Switching back to `WP_HTML_Tag_Processor()` should be part of the porting-into-Core process.

Comment (t-hamano) [reply packages/block-library/src/button/index.php:33]: I updated via 7835c9f. Are these changes appropriate?

File: packages/block-library/src/button/index.php [hunk 2]
```diff
@@ -17,7 +17,15 @@
...
-	$p = new WP_HTML_Tag_Processor( $content );
+	/*
+	 * The current Gutenberg plugin supports WordPress 6.4, but the next_token()
+	 * method does not exist in WordPress 6.4. Therefore, use the Gutenberg
+	 * class that has the `next_token()` method.
+	 *
+	 * TODO: After the Gutenberg plugin drops support for WordPress 6.4, this
+	 * class should be replaced with `WP_HTML_Tag_Processor`.
+	 */
+	$p = new Gutenberg_HTML_Tag_Processor_6_5( $content ); // phpcs:ignore Gutenberg.CodeAnalysis.ForbiddenFunctionsAndClasses.ForbiddenClassUsage
```
Comment (dmsnell) [inline packages/block-library/src/button/index.php]: what's the ForbiddenClassUsage warning here?
is this something new?


I want to make sure we don't sneak through the package import process accidentally.

@ellatrix do you have insight here?

File: packages/block-library/src/button/index.php (hunk 1 above)
Comment (dmsnell) [reply packages/block-library/src/button/index.php:33]: Yes they are, but I've asked for some additional help from @ellatrix who ran the last release because I'm concerned about the need to add the ignore statement. Maybe something else is new and I'm unaware.

File: packages/block-library/src/button/index.php (hunk 2 above)
Comment (t-hamano) [reply packages/block-library/src/button/index.php]: This sniff seems to have been introduced in #57738.

Without this comment, PHPCS will emit the following warning.

```
It's not allowed to use the "Gutenberg_HTML_Tag_Processor_6_5" class as its name matches the forbidden pattern: "/^[Gg]utenberg.*$/".
```

On the other hand, I found that no warning is displayed if the code is like this:

```php
if ( defined( 'IS_GUTENBERG_PLUGIN' ) && IS_GUTENBERG_PLUGIN && class_exists( 'Gutenberg_HTML_Tag_Processor_6_5' ) ) {
	$p = new Gutenberg_HTML_Tag_Processor_6_5( $content );
} else {
	$p = new WP_HTML_Tag_Processor( $content );
}
```

Comment (dmsnell) [reply packages/block-library/src/button/index.php]: @anton-vlasenko can you comment on this?

Comment (anton-vlasenko) [reply packages/block-library/src/button/index.php]: 👋 @dmsnell,
PHP code in the `block-library` folder must not use `(G|g)utenberg` prefixed classes or functions, as these blocks are backported to the WordPress release package, where Gutenberg classes/functions are not available.
This rule doesn't apply to experimental blocks since they are not backported.
Gutenberg prefixed classes/methods should only be used if the Gutenberg plugin is available, ensured by the `if ( defined( 'IS_GUTENBERG_PLUGIN' ) && IS_GUTENBERG_PLUGIN )` check.
Related discussion: https://github.com/WordPress/gutenberg/pull/54509#discussion_r1332282682

Comment (dmsnell) [reply packages/block-library/src/button/index.php]: thanks @anton-vlasenko - this is the first time I've seen code ported into Core that checks if it's running the plugin and then changes its behavior. I guess this is intentional?

Comment (anton-vlasenko) [inline packages/block-library/src/button/index.php]: @t-hamano, I recommend using the [code](https://github.com/WordPress/gutenberg/pull/63082/files#r1664311551) from your own example, as `Gutenberg_HTML_Tag_Processor_6_5` isn't available in WordPress Core. This will help avoid any fatal errors when the code is backported to WordPress Core. Thanks. 
```suggestion
	if ( defined( 'IS_GUTENBERG_PLUGIN' ) && IS_GUTENBERG_PLUGIN && class_exists( 'Gutenberg_HTML_Tag_Processor_6_5' ) ) {
	$p = new Gutenberg_HTML_Tag_Processor_6_5( $content );
} else {
	$p = new WP_HTML_Tag_Processor( $content );
}
```

Comment (anton-vlasenko) [reply packages/block-library/src/button/index.php]: Yes, this is intentional (not sure if I got your question right) in the sense that this is needed to avoid fatal errors in WordPress Core. There are several such checks in WordPress Core: https://github.com/search?q=repo%3AWordPress%2Fwordpress-develop++%22if+%28+defined%28+%27IS_GUTENBERG_PLUGIN%27+%29+%26%26+IS_GUTENBERG_PLUGIN%22&type=code"

**Review by anton-vlasenko — COMMENTED** [review]
@t-hamano I'd be grateful if you could address my comment below. Thank you.

File: packages/block-library/src/button/index.php (hunk 2 above)
Comment (dmsnell) [reply packages/block-library/src/button/index.php]: very good. I thought we were rewriting these calls when importing into Core instead of bleeding the plugin code into it. thanks for confirming that this was intentional.

**Comment by talldan** [comment]
Thanks for addressing this. I realize it was my mistake that's lead to this situation.

> July 16th: WordPress 6.6 will be officially released.
> July 17th: Gutenberg 18.8 will be shipped with this PR included, which will fix the issue with WP6.4.

Given 18.8 is released after WordPress 6.6, I think support for WordPress 6.4 can be dropped in 18.8.

Perhaps this PR can be shipped in a Gutenberg 18.7.1 release (I'm happy to handle the release process).

**Review by dmsnell — APPROVED** [review]

**Comment by t-hamano** [comment]
Thank you everyone for your feedback. I think I've made the appropriate changes to the code, but I'd appreciate it if you could also check that [this comment](https://github.com/WordPress/gutenberg/pull/63082/files#diff-d56fab2f8121c04e1c7d5147c684973d03892a43ef30c0dfb98b60f95d656d8fR20-R28) is clear.

> Perhaps this PR can be shipped in a Gutenberg 18.7.1 release (I'm happy to handle the release process).

That is very much appreciated 🙇‍♂️

**Comment by talldan** [comment]
> I'd appreciate it if you could also check that [this comment](https://github.com/WordPress/gutenberg/pull/63082/files#diff-d56fab2f8121c04e1c7d5147c684973d03892a43ef30c0dfb98b60f95d656d8fR20-R28) is clear.

Yep, I think it's very clear 👍

**Comment by talldan** [comment]
I've cherry picked this to the 18.7 release branch - b6310be0a26903812c573635bdc5b021d58a9d40

File: packages/block-library/src/button/index.php (hunk 1 above)
Comment (ellatrix) [reply packages/block-library/src/button/index.php:33]: What is the question? I'm not really familiar with any of this

Comment (dmsnell) [reply packages/block-library/src/button/index.php:33]: it's okay @ellatrix - question was answered. mainly I was unaware that we are sending Gutenberg plugin code into Core now, but apparently that's how people are avoiding name clashes
