### PR TITLE
Blocks: Fix quote block (parsing, serializing and transforming)

### LINKED ISSUE #1255: Quote Block: Moving to text block adds paragraphs inside paragraphs
When I convert a quote to a text element the result markup is like:

```html
<p>
   <p>quote content</p>
  </p>more quote content</p>
citation</p>
```

Inside TinyMCE this is usually (tested in Safari & Chrome) rendered on a single line. My guess is  that it’s because paragraphs inside paragraphs is not valid HTML  – `p` can't contain block level elements in the HTML sense.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #1255 

I've noticed several issues with the quote block:

 - We were dropping the `p` when parsing the quote content
 - We were serializing double `p`s
 - Transforming to text block was broken when we moved the text block to single p.

This PR adds a new parsing helper `node` which is similar to `children` but includes the wrapper node.

### CODE REVIEW

File: blocks/api/test/query.js [hunk 1]
```diff
@@ -32,4 +32,21 @@ describe( 'query', () => {
...
+			expect( matcher ).to.be.a( 'function' );
+		} );
+
+		it( 'should return HTML equivalent WPElement of matched element', () => {
+			// Assumption here is that we can cleanly convert back and forth
+			// between a string and WPElement representation
+			const html = '<blockquote><p>A delicious sundae dessert</p></blockquote>';
+			const match = parse( html, query.node() );
+
+			expect( wp.element.renderToString( match ) ).to.equal( `<body>${ html }</body>` );
```
Comment (youknowriad) [inline blocks/api/test/query.js]: @aduth The extra `body` here seemed weird to me. Is this something automatically added by the `parse` function or something?

Also in the test above, the `children` helper is returning the whole HTML while I expected it to return only the inner `p`.

Comment (aduth) [inline blocks/api/test/query.js]: The `body` comes from hpq assigning `innerHTML` of a new document on which to perform the querying:

https://github.com/aduth/hpq/blob/a5bda80/src/index.js#L22

I seem to recall there may be alternatives to consider here to be able to avoid it.

Comment (youknowriad) [inline blocks/api/test/query.js]: Ok, doesn't bother me a lot now, but yeah maybe we should drop it somehow.

File: blocks/library/quote/index.js [hunk 2]
```diff
@@ -59,9 +64,23 @@ registerBlockType( 'core/quote', {
 			{
 				type: 'block',
 				blocks: [ 'core/text' ],
-				transform: ( { value, citation } ) => {
+				transform: ( { value, citation, ...attrs } ) => {
+					const textElement = Array.isArray( value ) ? value[ 0 ] : value;
```
Comment (aduth) [inline blocks/library/quote/index.js]: `query` should always return an array. When would the falsey flow occur here?

File: blocks/library/quote/index.js [hunk 3]
```diff
@@ -13,15 +18,15 @@ import AlignmentToolbar from '../../alignment-toolbar';
...
+const { children, node, query } = hpq;
 
 registerBlockType( 'core/quote', {
 	title: wp.i18n.__( 'Quote' ),
 	icon: 'format-quote',
 	category: 'common',
 
 	attributes: {
-		value: query( 'blockquote > p', children() ),
+		value: query( 'blockquote > p', node() ),
```
Comment (aduth) [inline blocks/library/quote/index.js]: Would it be enough to change this to `children( 'p' )` ?

File: blocks/library/quote/index.js (hunk 2 above)
Comment (youknowriad) [inline blocks/library/quote/index.js]: You were right, it seems like the ternary is not necessary here. I only needed a defaultValue for newly inserted quotes.

File: blocks/api/query.js [hunk 4]
```diff
@@ -36,11 +36,11 @@ export const html = withKnownMatcherFlag( originalHtml );
 export const text = withKnownMatcherFlag( originalText );
 export const query = withKnownMatcherFlag( originalQuery );
 export const children = withKnownMatcherFlag( ( selector ) => {
-	return ( node ) => {
-		let match = node;
+	return ( domNode ) => {
```
Comment (iseulde) [inline blocks/api/query.js]: Why rename?

Comment (youknowriad) [inline blocks/api/query.js]: to avoid the lint errors with the newly created `node` helper.

File: blocks/api/query.js [hunk 5]
```diff
@@ -50,3 +50,14 @@ export const children = withKnownMatcherFlag( ( selector ) => {
...
 } );
+export const node = withKnownMatcherFlag( ( selector ) => {
+	return ( domNode ) => {
+		let match = domNode;
+
+		if ( selector ) {
+			match = domNode.querySelector( selector );
+		}
+
+		return nodeToReact( match, wp.element.createElement );
```
Comment (iseulde) [inline blocks/api/query.js]: I guess we don't want `wp.element.createElement` anymore?

Comment (youknowriad) [inline blocks/api/query.js]: Good catch

File: blocks/test/fixtures/core-quote-style-1.json [hunk 6]
```diff
@@ -5,9 +5,10 @@
         "attributes": {
             "style": "1",
             "value": [
-                [
-                    "The editor will endeavour to create a new page and post building experience that makes writing rich posts effortless, and has “blocks” to make it easy what today might take shortcodes, custom HTML, or “mystery meat” embed discovery."
-                ]
+                {
```
Comment (iseulde) [inline blocks/test/fixtures/core-quote-style-1.json]: Could we do a test with multiple children?

**Comment by iseulde** [comment]
I'm having some issues going from a quote => heading. Also, isn't it strange to do such a transformation?

**Comment by youknowriad** [comment]
@iseulde The transform to text also splits in two if there are multiple `p` in the quote block. Yes these are strange

**Comment by iseulde** [comment]
So this is not a bug? I don't understand why it splits right in the middle of the text.

**Comment by youknowriad** [comment]
@iseulde The first paragraph is transformed to a heading while the others stay in the quote.

**Comment by iseulde** [comment]
No, it's not the first one. There was only one.

**Comment by iseulde** [comment]
It's splitting right before the italicised text.

**Comment by youknowriad** [comment]
Oh ok, that's a bug.

**Comment by youknowriad** [comment]
@iseulde MM I can't seem to reproduce the bug here.

**Comment by iseulde** [comment]
@youknowriad Go to the "The Inserter Tool" heading in the demo, switch to quote, then back to heading.

**Comment by youknowriad** [comment]
@iseulde I can reproduce now Thanks.

I accidentally pushed the fix for this bug in master. Rebased here so this should be ok https://github.com/WordPress/gutenberg/commit/599970ee79fb30002d7ff80257e7ddf0cbf02058

**Comment by youknowriad** [comment]
@iseulde Going to merge this if no concerns?

**Comment by iseulde** [comment]
Hm, now quote ==> heading no longer works.

**Comment by youknowriad** [comment]
Fixed, Let's hope this one is the good one.

File: blocks/library/heading/index.js [hunk 7]
```diff
@@ -41,9 +41,9 @@ registerBlockType( 'core/heading', {
 				transform: ( { content, ...attrs } ) => {
 					const isMultiParagraph = Array.isArray( content ) && isObject( content[ 0 ] ) && content[ 0 ].type === 'p';
 					if ( isMultiParagraph ) {
-						const headingContent = isString( content[ 0 ] )
-							? content[ 0 ]
-							: content[ 0 ].props.children;
+						const headingContent = isObject( content[ 0 ] ) && content[ 0 ].type === 'p'
```
Comment (iseulde) [inline blocks/library/heading/index.js]: I guess it doesn't matter much here, but not sure why we should change it, the string check being faster.

File: blocks/library/quote/index.js [hunk 8]
```diff
@@ -63,9 +89,13 @@ registerBlockType( 'core/quote', {
 				blocks: [ 'core/heading' ],
 				transform: ( { value, citation, ...attrs } ) => {
 					const isMultiParagraph = Array.isArray( value ) && isObject( value[ 0 ] ) && value[ 0 ].type === 'p';
+					const headingElement = isMultiParagraph ? value[ 0 ] : value;
+					const headingContent = isObject( headingElement ) && value[ 0 ].type === 'p'
```
Comment (iseulde) [inline blocks/library/quote/index.js]: Similarly here, sometimes we seem to check for string, other times object. Nitpicking now though. :D

**Review by ellatrix — APPROVED** [review]

**Comment by iseulde** [comment]
Good to merge once tests pass.
