### PR TITLE
Fix: empty style attribute issue in navigation block

### LINKED ISSUE #62358: The Navigation Block has an Inline Style Without Declarations.
### Description

The bug is an inline style attribute without [declarations](https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax#css_declarations).
The Bug is in the [Navigation Block](https://wordpress.org/documentation/article/navigation-block/). And the issue lies within the [Overlay Menu](https://wordpress.org/documentation/article/navigation-block/#display). Furthermore, the bug appears with the Overlay Menu options:
    • Mobile
    • Always
The bug appears in the page's (rendered) HTML. The HTML with the empty style attribute is below.
`<div class="wp-block-navigation__responsive-container" style="" id="modal-1" data-wp-class--has-modal-open="state.isMenuOpen" data-wp-class--is-menu-open="state.isMenuOpen" data-wp-watch="callbacks.initMenu" data-wp-on--keydown="actions.handleMenuKeydown" data-wp-on--focusout="actions.handleMenuFocusout" tabindex="-1">`

### Step-by-step reproduction instructions

You can see the following steps in the screen recording below.
## Steps
Log Into WordPress and activate Theme Twenty Twenty-Four.
### Edit The Navigation Block
Edit the Navigation Block via the Home Page. 
    • Home Page
    • Edit site
    • Edit Blog Home
    • In the Header area, select the Navigation Block.
    • Go to the Navigation Block Settings
### Change The Overlay Menu Settings
The bug is in the Overlay Menu settings Mobile or Always. 
    • Overlay Menu = Always
    • Save
    • View Site
### View The Bug In (Rendered) HTML
Open your browser Developer Tools and find the webpage's HTML DOM Tree. 
The empty inline style attribute is in a div element containing the class wp-block-navigation__responsive-container. (See below.)

`<div class="wp-block-navigation__responsive-container" style="" id="modal-1" data-wp-class--has-modal-open="state.isMenuOpen" data-wp-class--is-menu-open="state.isMenuOpen" data-wp-watch="callbacks.initMenu" data-wp-on--keydown="actions.handleMenuKeydown" data-wp-on--focusout="actions.handleMenuFocusout" tabindex="-1">`

### Screenshots, screen recording, code snippet

inline-block-inline-style

### Environment info

    • WordPress 6.5.3 (No plug-ins).
    • I have not installed the Gutenberg plug-in.
    • Theme Twenty Twenty-Four
    • Google Chrome browser Version 125.0.6422.142 (Official Build) (64-bit)
    • Desktop with Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by up1512001**
## What?
- checking if `$colors['overlay_inline_styles']` is not empty then only adding style attribute.

## Why?
https://github.com/WordPress/gutenberg/issues/62358

## How?
```php
( ! empty( esc_attr( safecss_filter_attr( $colors['overlay_inline_styles'] ) ) ) ) ? ( 'style="' . esc_attr( safecss_filter_attr( $colors['overlay_inline_styles'] ) ) . '"' ) : ''
```

## Testing Instructions
- create page
- add navigation block
- see div with `wp-block-navigation__responsive-container` previously having empty style will not have style attribute.

## Screenshots or screencast 
Screenshot 2024-06-15 at 23 51 01

### CODE REVIEW

**Review by artemiomorales — COMMENTED** [review]
I tested this and it works as expected 👍

That being said, I'm not sure it's necessary to remove the empty `style` tag or if there may be unforeseen side effects, so I'll defer approval until we get other thoughts and/or someone with more context on the navigation block can weigh in. It seems like this shouldn't cause any issues though, and it does produce cleaner markup.

File: packages/block-library/src/navigation/index.php [hunk 1]
```diff
@@ -537,7 +537,7 @@ private static function get_responsive_container_markup( $attributes, $inner_blo
 			$toggle_aria_label_close,
 			esc_attr( implode( ' ', $responsive_container_classes ) ),
 			esc_attr( implode( ' ', $open_button_classes ) ),
-			esc_attr( safecss_filter_attr( $colors['overlay_inline_styles'] ) ),
+			( ! empty( esc_attr( safecss_filter_attr( $colors['overlay_inline_styles'] ) ) ) ) ? ( 'style="' . esc_attr( safecss_filter_attr( $colors['overlay_inline_styles'] ) ) . '"' ) : '',
```
Comment (talldan) [inline packages/block-library/src/navigation/index.php]: This works, but a couple of suggestions to make the code more readable. 

- The styles could be assigned to a variable first to avoid escaping/filtering the value twice.
- In PHP, if you use double quotes, you can expand variables within the string so that you don't have to concatenate with `.` (https://www.php.net/manual/en/language.types.string.php#language.types.string.parsing)

```php
$overlay_inline_styles = esc_attr( safecss_filter_attr( $colors['overlay_inline_styles'] ) );

// ...

! empty( $overlay_inline_styles  ) ? "style=$overlay_inline_styles" : '',
```

Comment (up1512001) [reply packages/block-library/src/navigation/index.php]: @talldan updated.

File: packages/block-library/src/navigation/index.php [hunk 2]
```diff
@@ -537,7 +539,7 @@ private static function get_responsive_container_markup( $attributes, $inner_blo
 			$toggle_aria_label_close,
 			esc_attr( implode( ' ', $responsive_container_classes ) ),
 			esc_attr( implode( ' ', $open_button_classes ) ),
-			esc_attr( safecss_filter_attr( $colors['overlay_inline_styles'] ) ),
+			( ! empty( $overlay_inline_styles ) ) ? "style=$overlay_inline_styles" : '',
```
Comment (talldan) [inline packages/block-library/src/navigation/index.php]: The PR isn't working at the moment, this is just missing some quotes around the style to make it a valid html attribute:
```suggestion
			( ! empty( $overlay_inline_styles ) ) ? "style=\"$overlay_inline_styles\"" : '',
```

To reproduce:
1. Set a navigation block to Overlay - 'Always'
2. Add some custom colors for the overlay menu
3. Save and view the frontend - observe the custom colors aren't applied.

Comment (up1512001) [reply packages/block-library/src/navigation/index.php]: @talldan added missing quotes.
Thanks for suggestion.

**Review by talldan — APPROVED** [review]
Looks great, thanks for your contribution @up1512001!

**Comment by ellatrix** [comment]
I just cherry-picked this PR to the wp/6.6-rc-1 branch to get it included in the next release: f6c73370ee

**Comment by jeffpaul** [comment]
@convolutedkdlkf mind sharing your WordPress.org username so I can ensure it appears in the 6.7 credits listing?
