### PR TITLE
[Block Editor]: Fix block variation registration when `icon` is an `object` and contains `transform` scope

### LINKED ISSUE #41453: WordPress 6.0 - Cannot add a block's variation when its `icon` attribute is an Object and the `scope` attribute includes 'transform'
### Description

Hi there, I'm one of the developer of the [LifterLMS plugin](https://wordpress.org/plugins/lifterlms/). One of our customers [reported an issue](https://github.com/gocodebox/lifterlms-blocks/issues/170) as they were unable to edit one of our specific blocks since updating to WordPress 6.0.
We've been able to troubleshoot the issue and reduce it to something that happens with whatever block when registering a variation whose:
- `icon` attribute is an Object (which is allowed according to https://developer.wordpress.org/block-editor/reference-guides/block-api/block-variations/),
- `scope` attribute includes `'transform'`.

Whem removing `'transform'` from the `scope` list the issue doesn't occur, but of course the variation is not available in the inspector.

error logged in the console:
```js
Error: Objects are not valid as a React child (found: object with keys {src, foreground}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (https://mywp-stable.loc/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:13261:17)
    at reconcileChildFibers (https://mywp-stable.loc/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:14163:9)
    at reconcileChildren (https://mywp-stable.loc/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:17020:30)
    at mountIndeterminateComponent (https://mywp-stable.loc/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:17920:7)
    at beginWork (https://mywp-stable.loc/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:19079:18)
    at HTMLUnknownElement.callCallback (https://mywp-stable.loc/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:3942:16)
    at Object.invokeGuardedCallbackDev (https://mywp-stable.loc/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:3991:18)
    at invokeGuardedCallback (https://mywp-stable.loc/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:4053:33)
    at beginWork$1 (https://mywp-stable.loc/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:23994:9)
    at performUnitOfWork (https://mywp-stable.loc/wp-includes/js/dist/vendor/react-dom.js?ver=17.0.1:22806:14)
```
```js
react_devtools_backend.js:4026 The above error occurred in the <Icon> component:

    at Icon (https://mywp-stable.loc/wp-includes/js/dist/components.js?ver=79d190e9af232aeaa59c1b40aa22932c:19262:5)
    at button
    at Tooltip (https://mywp-stable.loc/wp-includes/js/dist/components.js?ver=79d190e9af232aeaa59c1b40aa22932c:23958:5)
    at Button (https://mywp-stable.loc/wp-includes/js/dist/components.js?ver=79d190e9af232aeaa59c1b40aa22932c:22282:7)
    at fieldset
    at VariationsButtons (https://mywp-stable.loc/wp-includes/js/dist/block-editor.js?ver=39c7981dd22ec80281080455892940e6:40639:5)
    at __experimentalBlockVariationTransforms (https://mywp-stable.loc/wp-includes/js/dist/block-editor.js?ver=39c7981dd22ec80281080455892940e6:40703:5)
    at div
    at BlockInspectorSingleBlock (https://mywp-stable.loc/wp-includes/js/dist/block-editor.js?ver=39c7981dd22ec80281080455892940e6:48408:5)
    at BlockInspector (https://mywp-stable.loc/wp-includes/js/dist/block-editor.js?ver=39c7981dd22ec80281080455892940e6:48329:5)
    at div
    at Panel (https://mywp-stable.loc/wp-includes/js/dist/components.js?ver=79d190e9af232aeaa59c1b40aa22932c:69076:5)
    at div
    at SlotComponent (https://mywp-stable.loc/wp-includes/js/dist/components.js?ver=79d190e9af232aeaa59c1b40aa22932c:22575:5)
    at Slot
    at https://mywp-stable.loc/wp-includes/js/dist/components.js?ver=79d190e9af232aeaa59c1b40aa22932c:23221:5
    at ComplementaryAreaSlot (https://mywp-stable.loc/wp-includes/js/dist/edit-post.js?ver=0066e2a76eff88129280c12c9a52b6b4:1365:5)
    at div
    at div
    at div
    at div
    at InterfaceSkeleton (https://mywp-stable.loc/wp-includes/js/dist/edit-post.js?ver=0066e2a76eff88129280c12c9a52b6b4:1600:5)
    at Layout (https://mywp-stable.loc/wp-includes/js/dist/edit-post.js?ver=0066e2a76eff88129280c12c9a52b6b4:8669:5)
    at ErrorBoundary (https://mywp-stable.loc/wp-includes/js/dist/editor.js?ver=3f6371e7599e6cefa5d43fae1b61f643:5669:5)
    at BlockRefsProvider (https://mywp-stable.loc/wp-includes/js/dist/block-editor.js?ver=39c7981dd22ec80281080455892940e6:9763:5)
    at BlockEditorProvider (https://mywp-stable.loc/wp-includes/js/dist/block-editor.js?ver=39c7981dd22ec80281080455892940e6:19413:5)
    at https://mywp-stable.loc/wp-includes/js/dist/block-editor.js?ver=39c7981dd22ec80281080455892940e6:19112:7
    at WithRegistryProvider(BlockEditorProvider)
    at BlockContextProvider (https://mywp-stable.loc/wp-includes/js/dist/block-editor.js?ver=39c7981dd22ec80281080455892940e6:12871:5)
    at EntityProvider (https://mywp-stable.loc/wp-includes/js/dist/core-data.js?ver=95df951bbac4c9f2fd2e6da80561595d:5570:5)
    at EntityProvider (https://mywp-stable.loc/wp-includes/js/dist/core-data.js?ver=95df951bbac4c9f2fd2e6da80561595d:5570:5)
    at EditorProvider (https://mywp-stable.loc/wp-includes/js/dist/editor.js?ver=3f6371e7599e6cefa5d43fae1b61f643:11575:5)
    at https://mywp-stable.loc/wp-includes/js/dist/editor.js?ver=3f6371e7599e6cefa5d43fae1b61f643:11343:5
    at WithRegistryProvider(EditorProvider)
    at SlotFillProvider (https://mywp-stable.loc/wp-includes/js/dist/components.js?ver=79d190e9af232aeaa59c1b40aa22932c:23058:5)
    at provider_SlotFillProvider (https://mywp-stable.loc/wp-includes/js/dist/components.js?ver=79d190e9af232aeaa59c1b40aa22932c:23086:5)
    at Provider (https://mywp-stable.loc/wp-includes/js/dist/components.js?ver=79d190e9af232aeaa59c1b40aa22932c:23235:5)
    at div
    at ShortcutProvider (https://mywp-stable.loc/wp-includes/js/dist/keyboard-shortcuts.js?ver=418fddac042f08102c4110f70e13cd47:763:75)
    at Editor (https://mywp-stable.loc/wp-includes/js/dist/edit-post.js?ver=0066e2a76eff88129280c12c9a52b6b4:8949:5)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
 ```

### Step-by-step reproduction instructions

- Register a variation, e.g. for the quote core block with the snippet in the section:
- Edit a page/post, and add a Quote block 
- The editor breaks, you'll get a blank page with the classic "The editor has encountered an unexpected error." alert.

### Screenshots, screen recording, code snippet

Variation registration for the Quote block.
```js
wp.blocks.registerBlockVariation(
	'core/quote',
	{
		name: 'custom-quote',
		title: 'Custom Quote',
		icon: { src: 'email', foreground: '#ff0000' },
		scope: [ 'block', 'inserter', 'transform' ]
	},
);
```

### Environment info

WordPress 6.0
Theme: Twenty Twenty-Two

no other plugins installed.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/41453
Introduced in: https://github.com/WordPress/gutenberg/pull/40036

## Why?
Currently if we register a block variation with an `object` `icon` and include `transform` in `scope`, there is a check to show only `icons` in the block variations transform control in inspector controls, which breaks the editor. We don't take into account that the `icon` can be an `object` so I updated the code to use `BlockIcon` which does and seems a better choice either way for this use case.

## Testing Instructions
1. In the editor open the `console` and add the below snippet
2. Then add a `Group` block and observe that in inspector controls show the variation's icon. 

### Snippet to add in console
```
wp.blocks.registerBlockVariation(
	'core/group',
	{
		name: 'custom-group',
		title: 'Custom Group',
		icon: { src: 'email', foreground: '#ff0000' },
		scope: [ 'block', 'inserter', 'transform' ]
	},
);
```

#### Before

https://user-images.githubusercontent.com/16275880/171186148-a1f1c643-8c8d-48aa-8872-8d444768041d.mov

#### After

https://user-images.githubusercontent.com/16275880/171186174-2fdcdca3-bc9a-43be-ba4c-23532cd131f8.mov

### CODE REVIEW

File: packages/block-editor/src/components/block-variation-transforms/index.js [hunk 1]
```diff
@@ -33,7 +34,7 @@ function VariationsButtons( {
 			{ variations.map( ( variation ) => (
 				<Button
 					key={ variation.name }
-					icon={ variation.icon }
+					icon={ <BlockIcon icon={ variation.icon } /> }
```
Comment (ntsekouras) [inline packages/block-editor/src/components/block-variation-transforms/index.js]: Should we also `showColors` here? 🤔 --cc @jameskoster @shaunandrews

**Review by Mamaduka — APPROVED** [review]
This fixes the issue. Thanks, Nik!

File: packages/block-editor/src/components/block-variation-transforms/index.js (hunk 1 above)
Comment (jameskoster) [reply packages/block-editor/src/components/block-variation-transforms/index.js]: @ntsekouras could you elaborate a little? I'm struggling to make the connection between colors and these icons :D

Comment (ntsekouras) [reply packages/block-editor/src/components/block-variation-transforms/index.js]: Sure! By running the above snippet we pass `icon: { src: 'email', foreground: '#ff0000' },`. You can observe that in the `slash inserter(/)` we show the passed colors(if any). Try typing `/custom group` and you'll see that the color of the icon will be red.

Now, all core variations don't use colors and by allowing  colors for custom variations could possibly meddle with the design and result in a mix of `black icons` and colored ones.

Comment (jameskoster) [reply packages/block-editor/src/components/block-variation-transforms/index.js]: So just to clarify, if in some strange world the Spotify block was a variation of the Group block, you would see this:

Screenshot 2022-05-31 at 17 14 24

Rather than this:

Screenshot 2022-05-31 at 17 16 16

If that's case I think we probably should `showColors`, so that block familiarity is strengthened.

Comment (ntsekouras) [reply packages/block-editor/src/components/block-variation-transforms/index.js]: Thanks Jay! I pushed the update.

**Review by andrewserong — APPROVED** [review]
Thanks for fixing this up @ntsekouras, the code change looks good to me, too!

I noticed that with the testing instructions, the added dashicon based icon button appears to be rendered slightly lower than the other buttons for some reason:

image

Not a blocker for landing this fix, but could be good for us to look into in a follow-up — I couldn't quite work out why it's sitting lower, but the difference appears to be that the other block icons render an inline `svg` and dashicons uses a `span` with a `::before` rule. 🤔
