### PR TITLE
Fix: Changing URL in link after changing text outside the popover resets it

### LINKED ISSUE #52659: Changing URL in link after changing text outside the popover resets it
### Description

If you change the text of a link in the editor itself and afterwards changing the URL of said link in the popover, the URL change won’t save.

### Step-by-step reproduction instructions

1. Add a paragraph and add content.
2. Add a link to the paragraph, e.g. with text "test" and URL "#test".
3. Save the page and reload.
4. Click behind the link.
5. Move the cursor with the arrow keys until you placed it inside the link.
6. Remove the last "t" with something different.
7. Edit the URL from "#test" to "test2".
8. Press enter.

The URL is still "#test" afterwards.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1018979/27b3e7de-5f2d-4215-97c1-95ff43f2f600

### Environment info

- WordPress 6.2.2, no Gutenberg plugin
- macOS 13.4.1 (c)
- Safari 16.5.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes #52659.
Closes #53533.

PR fixes a bug where URL changes weren't persistent after changing the link text in canvas. The bug has diverged slightly from the original report, but it still exists on trunk.

P.S. I wanted to include e2e test coverage, but for some reason, tests were always passing on trunk. It was a similar case for #53533.

## How?
Use explicit format boundaries rather than relying on the current selection, which may be collapsed or misaligned.

## Testing Instructions
1. Open a post or page. 
2. Add a paragraph with a link.
3. Change the link text.
4. Open the link popover and change the URL.
5. Apply changes and confirm they're persisted.

### Testing Instructions for Keyboard
Same.

## Screenshots or screencast 

**Before**

https://github.com/user-attachments/assets/4cb0a3c5-928f-4261-9a2a-fb5a272493de

**After**

https://github.com/user-attachments/assets/f2458c16-640c-491d-9b36-4fab990a88c3

### CODE REVIEW

**Comment by Mamaduka** [comment]
Investigating why some e2e tests are failing here, though they seem to be passing for me locally.

**Update:** Regression should be fixed now.

File: packages/format-library/src/link/inline.js [hunk 1]
```diff
@@ -167,7 +169,22 @@ function InlineLinkUI( {
...
+				? getFormatBoundary( value, {
+						type: 'core/link',
+				  } )
+				: undefined;
+			newValue = applyFormat(
+				value,
+				linkFormat,
+				boundary?.start,
+				boundary?.end
+					? boundary.end + FORMAT_BOUNDARY_EDGE_OFFSET
```
Comment (jeryj) [inline packages/format-library/src/link/inline.js]: Would it be helpful to avoid bugs to have `boundary.end + FORMAT_BOUNDARY_EDGE_OFFSET` be a const or set `textEnd` higher up in this flow? I'm not familiar with this code - just a drive-by comment :)

Comment (Mamaduka) [reply packages/format-library/src/link/inline.js]: Sorry, @jeryj, not sure I follow. Do you mean to avoid ternaries here?

This fix is specific to this case: the URL text remains the same, but the selection can be collapsed because focus moves to the popover.

Comment (jeryj) [reply packages/format-library/src/link/inline.js]: No, I just a saw `boundary.end + FORMAT_BOUNDARY_EDGE_OFFSET;` was written twice, and it might help clarify to have `const ______ = boundary.end + FORMAT_BOUNDARY_EDGE_OFFSET;` to clarify when to use `boundary.end` vs `boundary.end + FORMAT_BOUNDARY_EDGE_OFFSET`.

Comment (Mamaduka) [reply packages/format-library/src/link/inline.js]: Got it. It's used in two different places. I moved the offset to `FORMAT_BOUNDARY_EDGE_OFFSET` and added a comment to clarify its need. Happy to add more inline comments if needed.

**Comment by Mamaduka** [comment]
Added correct e2e test, now the fix can be confirmed by running it on trunk and on this branch. It will fail on trunk.

File: packages/format-library/src/link/inline.js (hunk 1 above)
Comment (jeryj) [reply packages/format-library/src/link/inline.js]: Yeah, I think something that explains more about why we need the `+ FORMAT_BOUNDARY_EDGE_OFFSET` and what it's purpose is. Do we use `boundary?.end` without `FORMAT_BOUNDARY_EDGE_OFFSET`? 

Also, for this line, how about we use `boundary?.end !== undefined` instead of relying on a falsey check? If the text for a link is only one character long, the boundary.end gets reported as 0, which would end up returning `undefined` in the current code.

Comment (Mamaduka) [reply packages/format-library/src/link/inline.js]: Updated inline comments and checked. An extra offset accounts for this special case, but it's hard to explain in a one-liner. Here's additional context https://github.com/WordPress/gutenberg/pull/33849/changes#r727096998.

cc @ellatrix, @getdave 

https://github.com/WordPress/gutenberg/blob/b4a952dccf9865e00f287d3f8e5822c72b526de4/packages/format-library/src/link/utils.js#L190-L195

File: packages/format-library/src/link/inline.js [hunk 2]
```diff
@@ -318,10 +333,8 @@ function getRichTextValueFromSelection( value, isActive ) {
 		} );
 
 		textStart = boundary.start;
-
-		// Text *selection* always extends +1 beyond the edge of the format.
-		// We account for that here.
-		textEnd = boundary.end + 1;
+		// Text *selection* always extends +1 beyond the edge of the format. Account for it.
+		textEnd = boundary.end + FORMAT_BOUNDARY_EDGE_OFFSET;
```
Comment (ellatrix) [inline packages/format-library/src/link/inline.js]: Not sure what you mean here. If I have "text" selected, the selection is start: 0, end: 4?

File: packages/format-library/src/link/inline.js (hunk 1 above)
Comment (ellatrix) [reply packages/format-library/src/link/inline.js]: Not sure I understand what https://github.com/WordPress/gutenberg/blob/b4a952dccf9865e00f287d3f8e5822c72b526de4/packages/format-library/src/link/utils.js#L190-L195 is for

File: packages/format-library/src/link/inline.js (hunk 2 above)
Comment (Mamaduka) [reply packages/format-library/src/link/inline.js]: If you have "text" selected and focus moves to the Link popover, selection collapses - start: 4, end: 4. The `getFormatBoundary` tries to expand start/end to the actual format, but because of a linked edge case it returns `start: 0, end: 3` and we had to add the offset.

You can log something using `console.log( { start: value.start, end: value.end }, boundary );` and run the current e2e test.

File: packages/format-library/src/link/inline.js (hunk 1 above)
Comment (Mamaduka) [reply packages/format-library/src/link/inline.js]: To my knowledge, the collapsed format expansion doesn't work from the edges in this case, so util tries from the `endIndex - 1` position.

File: packages/format-library/src/link/inline.js (hunk 2 above)
Comment (ellatrix) [reply packages/format-library/src/link/inline.js]: Yes, you have a format at index 0, 1, 2, 3. There's no index 4 in the text? Also, if the selection resets after moving focus to the link popover, that sounds like a bug. Selection should not change

Comment (Mamaduka) [reply packages/format-library/src/link/inline.js]: If you select the whole linked text with a double-click and change it while the popover is open. Selection will be collapsed, which is `start: 4, end: 4`. I assume it should `start: 3, end: 3`, and then `applyFormat` will handle it correctly, but as noted in the inline comments, the collapsed selection extends +1 beyond the edge of the format.

I understand it's an odd case, but it's definitely a bug somewhere.

P.S. It is easy to view the text changing flow via e2e test UI mode.

Comment (ellatrix) [reply packages/format-library/src/link/inline.js]: If selection starts with start:0 and end:4, and it's collapsed, then the result will either be start:0 end:0 or start:4 end:4. Not sure why it should be start:3 end:3. I don't know anything about `getFormatBoundary`, this utility is new to me, but if it's supposed to return a boundary then that util should be responsible for converting content length to a boundary and doing +1

Comment (Mamaduka) [reply packages/format-library/src/link/inline.js]: Moved logic into `getFormatBoundary` and tried to add better inline explanation with some help from Claude.

Comment (ellatrix) [reply packages/format-library/src/link/inline.js]: Oh interesting, we're only using `getFormatBoundary` here?

**Review by ellatrix — APPROVED** [review]
Makes sense to me now, thanks for fixing the utility issue instead

File: packages/format-library/src/link/inline.js (hunk 2 above)
Comment (ellatrix) [reply packages/format-library/src/link/inline.js]: Or is it used elsewhere and is this fix also fixing a bug elsewhere?

Comment (Mamaduka) [reply packages/format-library/src/link/inline.js]: Yes, it's internal utility for the Link format, which has a more complex editing flow compared to other formats.

**Comment by Mamaduka** [comment]
Thanks for the feedback and review, @ellatrix, @jeryj 🙇

## Update
I'm going to merge this. Happy to follow-up as needed.

File: packages/format-library/src/link/inline.js (hunk 2 above)
Comment (ellatrix) [reply packages/format-library/src/link/inline.js]: So there was a bug wherever else that util is used?

Comment (Mamaduka) [reply packages/format-library/src/link/inline.js]: It was introduced in #33849. @getdave might have more context on the matter.

Comment (getdave) [reply packages/format-library/src/link/inline.js]: Thanks for wrangling this. I only noticed the ping today I'm afraid and I didn't get time to input. I appreciate the fix 🙇
