### PR TITLE
Block API: Pasting content that results in a new block shouldn't be treated as inline content.

### LINKED ISSUE #18390: Block API: pasteHandler() incorrectly treats single-line pastes as inline content.
**Describe the bug**

When pasting a single line of content that is transformed into a block, `pasteHandler()` will treat the resulting block as inline content.

**To reproduce**
1. Create a block with a `raw` transform which returns that block.
2. Paste content that matches the transform's `isMatch` rule.
3. Observe that the block is not inserted into the editor.

### PR DESCRIPTION
**Pull request by pento**
## Description

When pasting text, the paste handler currently assumes that if the text doesn't have a line break, and it results in one block, it can be treated as inline text, instead.

This may be correct for core, but is not necessarily correct for plugins that may wish to transform a single line of text into a custom block.

This PR tightens the paste handler assumption to only allow a selection of blocks to be treated as an inline paste.

Fixes #18390.

## How has this been tested?

Tested with the sample plugin in #18390.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows the accessibility standards.
- [x] My code has proper inline documentation.
- [x] I've included developer documentation if appropriate.
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/blocks/src/api/raw-handling/paste-handler.js [hunk 1]
```diff
@@ -244,10 +244,17 @@ export function pasteHandler( { HTML = '', plainText = '', mode = 'AUTO', tagNam
 		return htmlToBlocks( { html: piece, rawTransforms } );
 	} ) );
 
-	// If we're allowed to return inline content and there is only one block
+	// If `blocks` contains a single entry of one of these blocks,
+	// it can potentially be treated as an inline paste.
+	const inlineableBlocks = [
+		'core/paragraph',
```
Comment (ellatrix) [inline packages/blocks/src/api/raw-handling/paste-handler.js]: Could this be a block setting instead? We should also add it to any block that is just a text field, such as headings.

**Comment by ellatrix** [comment]
Could some sort of test be added?

File: packages/blocks/src/api/raw-handling/paste-handler.js (hunk 1 above)
Comment (pento) [reply packages/blocks/src/api/raw-handling/paste-handler.js]: Good suggestion, thanks @ellatrix! I've added that in 0b75d02c6.

**Comment by pento** [comment]
The new `supports.pasteTextInline` property defaults to `false`, so blocks will need to opt-in to being overridden when pasting inline text.

I've added some tests, too.

File: docs/designers-developers/developers/block-api/block-registration.md [hunk 2]
```diff
@@ -654,3 +654,12 @@ By default all blocks can be converted to a reusable block. If supports reusable
 reusable: false,
 ```
 
+- `pasteTextInline` (default `false`): If a single line of text is pasted into the block editor, resulting
+in this block being created, setting `pasteTextInline` to `true` will instead extract the text content of
+what is being pasted, and insert that into the currently selected block, instead.
```
Comment (ellatrix) [inline docs/designers-developers/developers/block-api/block-registration.md]: > If a single line of text is pasted into the block editor, resulting in this block being created [...]

This is not entirely true. It will do this for any block created when the pasted plain text had no line breaks. Additionally, this option is quite difficult to understand when to apply it correctly. Maybe `containsOnlyRichText` might be easier to understand?

**Comment by ellatrix** [comment]
@pento I marked `pasteTextInline` as an unstable API as I'm not expecting any non core blocks to use this feature (as you have noted yourself). Let's see if there are more cases popping up.

**Review by ellatrix — APPROVED** [review]
Thanks for the PR, this makes sense! :)
