### PR TITLE
MetaBoxes: Remove dirty-checking metaboxes state

### LINKED ISSUE #3975: Old metabox handling and JS updating text fields
## Issue Overview
When inserting a value via JavaScript into a text field in a form in the editor-meta-boxes-area div in Gutenberg doesn't trigger the changedMetaBoxState() function to mark the metabox-contained data dirty.

In this instance, I've created a gallery CPT - a meta box contains thumbnails of any previously selected images, add/edit/remove buttons, and a hidden field that contains a json-encoded string of selected image IDs. I use the wp.media.frames.file_frame update event to update the content of the hidden field with the IDs of the selected images. However, isDirty is not set to true when the value is updated. If I type directly into the field, the value of isDirty is updated as expected.

## Steps to Reproduce (for bugs)
1. Create a metabox (old-school style) with a text field.
2. Update the value of the field via JavaScript.

## Expected Behavior
isDirty is set to true and the value of the field is saved on Update.

## Current Behavior
Nothing. IsDirty is not set to true and the editor doesn't know it needs to save the metabox data. Again, if you type directly into the field everything works as expected.

### LINKED ISSUE #4183: Default values in meta boxes are never saved for new posts
## Issue Overview

When a plugin adds a meta box to the editor and the meta box has some default values the default values are not saved when creating a new post. The values are only saved if the default values are changed. This is not the normal behaviour with the classic editor. The default values are always saved.

Using master branch.

## Steps to Reproduce (for bugs)
1. Use the following plugin code
2. Click on new page
3. Add a title
4. Publish the post

```
<?php
/*
Plugin Name: Example for meta box with gutenberg
Author: OnTheGoSystems
Version: 1.0
*/

global $pagenow;

if ( in_array( $pagenow, array( 'post.php', 'post-new.php', 'edit.php' ), true ) ) {
	add_action( 'admin_head', 'gutenberg_new_post_add_meta_box' );
}

function gutenberg_new_post_add_meta_box() {
	add_meta_box( 'gutenberg_div', 'Options', 'gutenberg_meta_box', null, 'side', 'high' );
}

function gutenberg_meta_box() {
	?>
		<select name="gutenberg_select_test">
			<option value="1">Value 1</option>
			<option value="2">Value 2</option>
			<option value="3">Value 3</option>
		</select>

	<?php
}

add_action( 'save_post', 'gutenberg_save_post_example' );

function gutenberg_save_post_example( $post_id ) {

	if ( isset( $_POST['gutenberg_select_test'] ) ) {
		update_post_meta( $post_id, 'gutenberg_select_test', $_POST['gutenberg_select_test'] );
	}
}
```

## Expected Behavior
The 'save_post' action should be triggered and the `update_post_meta` function is called. This is what happens with the classic editor

## Current Behavior
The 'save_post' action is not triggered and the post meta is not updated.

## Possible Solution
I think all meta boxes should be considered as 'dirty' for new posts and all the meta box data should be submitted when saving the initial post.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #4183 and closes #3975 

Due to how MetaBoxes work it's not possible to dirty-check them properly. It's not possible to know if they contain default values as well. Thus, this PR removes the meta boxes dirty checking making Gutenberg work like the classic editor when there are active meta boxes which means:

 - The "save draft" and "update" button are never disabled
 - If you try to leave the editor's page with changes in the meta boxes area, you're not prompted with the confirmation box.

### CODE REVIEW

**Comment by spencerfinnell** [comment]
This allows some of my custom meta boxes to continue working as before. 👍

**Comment by wsydney76** [comment]
> you're not prompted with the confirmation box.

If that means it might happen to loose a ton of edited content by accident with one wrong click, i don't think that's an option.

If it is not possible to detect a dirty state correctly, i would instead prefer to be always prompted, even if there is no change at all.

**Comment by youknowriad** [comment]
> If that means it might happen to loose a ton of edited content by accident with one wrong click, i don't think that's an option.

That's how the current editor works, and it doesn't seem to bother anyone. The confirmation box is still enabled for changes to the post content and the post settings though.

**Comment by wsydney76** [comment]
> That's how the current editor works

If so, that is bad and should be fixed.

>  it doesn't seem to bother anyone

Except all the users who lost their edits.

Using ACF Pro, there is obviously an inconsistent behaviour, changes in most field types cause a prompt,
but some do not (simple textfield for example). 

It should at least be documented what plugin authors have to do to cause a prompt (something like a setDirty() call?)

**Comment by youknowriad** [comment]
> It should at least be documented what plugin authors have to do to cause a prompt (something like a setDirty() call?)

Sounds like a good idea to add an API like that. I think it's out of the scope of the current PR thought since this brings us to a similar behavior to the current Editor.

**Comment by youknowriad** [comment]
Can I have some thoughts here @aduth @mtias

**Comment by aduth** [comment]
>Due to how MetaBoxes work it's not possible to dirty-check them properly.

Is it possible to check whether there are "unsaved" changes during the `beforeunload` event? Unsaved meaning we serialize metabox forms when first loading, then compare serialized form values when user tries to leave?

(I should perhaps note I don't have the clearest understanding of the meta boxes behaviors)

That said, if it's prohibitively difficult, my preference would be toward resolving the bugs of #4183 and #3975 even if it means losing the dirtiness prompts.

**Comment by youknowriad** [comment]
> Is it possible to check whether there are "unsaved" changes during the beforeunload event? Unsaved meaning we serialize metabox forms when first loading, then compare serialized form values when user tries to leave?

Good proposal, I might try it, it may be difficult to achieve though since the "state" of the metaboxes is dispatched through several areas and if the areas are not visible, the DOM is in a hidden node.

But it has a downside. Some metaboxes come with default values, even if they do not have any change, they are still "dirty" (needs to be saved)

**Comment by aduth** [comment]
>Some metaboxes come with default values, even if they do not have any change, they are still "dirty" (needs to be saved)

I'd agree these are "dirty" only in that they need to be included in the save payload, but wouldn't agree that they'd need to stop the user from navigating away. If we're not already, couldn't we just send the entire metabox form of fields in the save request, whether or not any changes have been made?

**Comment by youknowriad** [comment]
>  If we're not already, couldn't we just send the entire metabox form of fields in the save request, whether or not any changes have been made?

Yes, that's what I'm doing in this PR alongside the the removal of the dirty checking to prevent leaving the editor (which matchers the old editor's behavior). 

I'll try to update the PR to make it work similarily to what you propose. But the only way to make it behave properly is to avoid relying on the "onChange" event and check the state when the user wants to leave the page because we can't catch updates done programmatically with onChange events.

**Comment by youknowriad** [comment]
@aduth I added the check in 39364A0 I'm not totally satisfied with the code but can't think of a good alternative right now

File: editor/store/selectors.js [hunk 1]
```diff
@@ -351,7 +354,7 @@ export function isCurrentPostPublished( state ) {
  */
 export function isEditedPostPublishable( state ) {
 	const post = getCurrentPost( state );
-	return isEditedPostDirty( state ) || [ 'publish', 'private', 'future' ].indexOf( post.status ) === -1;
+	return isEditedPostDirty( state ) || hasMetaBoxes( state ) || [ 'publish', 'private', 'future' ].indexOf( post.status ) === -1;
```
Comment (aduth) [inline editor/store/selectors.js]: Might recommend splitting this long line:

```js
return (
	isEditedPostDirty( state ) ||
	hasMetaBoxes( state ) ||
	[ 'publish', 'private', 'future' ].indexOf( post.status ) === -1
);
```

Minor: I like semantic readability of `includes`:

```js
return (
	isEditedPostDirty( state ) ||
	hasMetaBoxes( state ) ||
	! includes( [ 'publish', 'private', 'future' ], post.status )
);
```

File: editor/store/test/selectors.js [hunk 2]
```diff
@@ -2086,6 +1996,21 @@ describe( 'selectors', () => {
 
 			expect( isSavingPost( state ) ).toBe( false );
 		} );
+
+		it( 'should return true if the post is notcurrently being saved but meta boxes are saving', () => {
```
Comment (aduth) [inline editor/store/test/selectors.js]: Minor: Typo: Needs space between "not" and "currently"

File: editor/store/selectors.js [hunk 3]
```diff
@@ -65,32 +66,34 @@ export function getMetaBox( state, location ) {
...
- *
- * @param  {Object}  state Global application state
- * @return {Boolean}       Whether state is dirty. True if dirty, false if not.
+ * @param  {Object} state Global application state
+ * @return {Boolean}      Whether the metaboxes are being saved.
  */
-export const isMetaBoxStateDirty = ( state ) => getDirtyMetaBoxes( state ).length > 0;
+export const isSavingMetaBoxes = createSelector(
+	( state ) => {
+		return some( getMetaBoxes( state ), ( metaBox ) => {
```
Comment (aduth) [inline editor/store/selectors.js]: Same note as previous.

File: editor/edit-post/meta-boxes.js [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+ * @param   {String} location Meta Box location
+ * @returns {String}          HTML content
+ */
+export const getLocationHtml = ( location ) => {
+	const area = document.querySelector( `.editor-meta-boxes-area.is-${ location } .editor-meta-boxes-area__container` );
+	if ( area ) {
+		return area.innerHTML;
+	}
+
+	return document.querySelector( '.metabox-location-' + location ).innerHTML;
```
Comment (aduth) [inline editor/edit-post/meta-boxes.js]: When would we expect this line to be reached? (Can we add a comment explaining this?)

Comment (aduth) [reply editor/edit-post/meta-boxes.js]: And if we're expecting the first query selector might return an empty result, is there any reason to think this one might as well?

File: editor/store/reducer.js [hunk 5]
```diff
@@ -668,6 +668,7 @@ export function metaBoxes( state = defaultMetaBoxState, action ) {
 					...state[ location ],
 					isLoaded: false,
 					isActive: action.metaBoxes[ location ],
+					html: getLocationHtml( location ),
```
Comment (aduth) [inline editor/store/reducer.js]: Rather than calling into DOM from the reducer:

- Could the `MetaBoxesArea` component dispatch a "set HTML" action when it mounts?
- Should this at least be modeled as an effect? (Minding that with #3983 we should respect that effects occur after the original action)

File: editor/components/meta-boxes/meta-boxes-area/index.js [hunk 6]
```diff
@@ -84,30 +74,13 @@ class MetaBoxesArea extends Component {
...
 
 	getFormData() {
 		return jQuery( this.form ).serialize();
 	}
 
-	checkState() {
-		const { loading } = this.state;
-		const { isDirty, changedMetaBoxState, location } = this.props;
-
-		const newIsDirty = ! isEqual( this.originalFormData, this.getFormData() );
```
Comment (aduth) [inline editor/components/meta-boxes/meta-boxes-area/index.js]: Seems `this.originalFormData` is defunct now and can be removed, along with `getFormData`.

**Review by aduth — COMMENTED** [review]
I don't love the DOM querying where we expect to know the class structure of meta box elements. The only idea I can think of as an alternative is a pattern similar to slots where dirtyable areas (components) can register themselves with `UnsavedChangesWarning`, and the initial HTML is tracked when the (dirtyable) component first mounts. At this point there'd be no need for the Redux property tracking.

Can you explain what it is about the changes here that resolves #4183?

File: editor/edit-post/meta-boxes.js (hunk 4 above)
Comment (youknowriad) [reply editor/edit-post/meta-boxes.js]: The metaboxes are rendered to an initial hidden dom node (the later here) but when their panel is visible (it's not always the case for the sidebar), they are moved to their new location and when closed moved back to the original location.

**Comment by youknowriad** [comment]
@aduth this closes #4183 because we never check for dirtyness before saving the metaboxes, each time we save a post, we save them. So by default the save button is visible.

**Comment by aduth** [comment]
>@aduth this closes #4183 because we never check for dirtyness before saving the metaboxes, each time we save a post, we save them. So by default the save button is visible.

My reading of #4183 is not related to the Save button being unavailable, but rather that the default values aren't included in the payload of the save request.

**Comment by youknowriad** [comment]
@aduth I think the request for saving the metaboxes is not triggered at all because they are considered "non-dirty"

**Comment by youknowriad** [comment]
Ok, I think the PR is better now. I updated it. It still uses the DOM direct access. It's not great but since the metaboxes are kind of "weird chunk fo HTML" we have to deal with, it's acceptable IMO.
I added a comment to clarify its behavior.

Also,

 - I moved the save behavior of the metaboxes to an affect
 - If we have multiple areas, they're all saved together now fixing the bug where hidden metaboxes were not saved.
 - Some usage of `jQuery.serialize` to merge the different forms (I prefer this over having a custom code).

What do y'all think?

File: editor/components/meta-boxes/meta-boxes-area/index.js [hunk 7]
```diff
@@ -1,153 +1,85 @@
...
+				'is-loading': isSaving,
 			}
 		);
 
 		return (
 			<div className={ classes }>
-				{ loading && <Spinner /> }
-				<div ref={ this.bindNode } />
+				{ isSaving && <Spinner /> }
+				<div className="editor-meta-boxes-area__container" ref={ this.bindNode } />
```
Comment (aduth) [inline editor/components/meta-boxes/meta-boxes-area/index.js]: Unrelated: When I see `bindNode`, I assume it's assigning the `ref` of the root return value, not a child of the element. A minor thing, but I think it can be nice to clarify in the function name, e.g. `bindContainerNode`.

File: editor/components/meta-boxes/meta-boxes-area/index.js [hunk 8]
```diff
@@ -1,153 +1,85 @@
...
 	}
 
+	/**
+	 * @inheritdoc
+	 */
 	componentDidMount() {
-		this.mounted = true;
-		this.fetchMetaboxes();
+		this.form = document.querySelector( '.metabox-location-' + this.props.location );
+		this.node.appendChild( this.form );
```
Comment (aduth) [inline editor/components/meta-boxes/meta-boxes-area/index.js]: Not sure if we care to be guarded here, but if I pass an invalid `location` prop, this will error.

File: editor/store/actions.js [hunk 9]
```diff
@@ -438,11 +438,11 @@ export function removeNotice( id ) {
  * not render the meta box area.
  *
  * Example: metaBoxes = { side: true, normal: false }
- * This indicates that the sidebar has a meta box but the normal area does not.
+ * this indicates that the sidebar has a meta box but the normal area does not.
  *
- * @param {Object} metaBoxes Whether meta box locations are active.
+ * @param   {Object} metaBoxes Whether meta box locations are active.
```
Comment (aduth) [inline editor/store/actions.js]: I think there was a faulty rebase here, I wouldn't expect these doc changes (i.e. we don't want the extra whitespace here, or in the `@returns` below)

File: editor/store/actions.js [hunk 10]
```diff
@@ -452,60 +452,38 @@ export function initializeMetaBoxState( metaBoxes ) {
...
  *
- * @param {String}  location   Location of meta box: 'normal', 'side' or 'advanced'.
- * @param {Boolean} hasChanged Whether the meta box has changed.
- *
- * @returns {Object} Action object.
+ * @param   {Object} dataPerLocation Meta Boxes Data per location.
+ * @returns {Object}                 Action object.
  */
-export function metaBoxStateChanged( location, hasChanged ) {
+export function metaBoxSetSavedData( dataPerLocation ) {
```
Comment (aduth) [inline editor/store/actions.js]: Unrelated: I prefer when the action creators are prefixed with the verb of what's happening, i.e. "set", `setMetaBoxSavedData`

File: editor/store/effects.js [hunk 11]
```diff
@@ -452,4 +455,38 @@ export default {
...
+		store.dispatch( metaBoxSetSavedData( dataPerLocation ) );
+	},
+	REQUEST_META_BOX_UPDATES( action, store ) {
+		const dataPerLocation = reduce( getMetaBoxes( store.getState() ), ( memo, metabox, location ) => {
+			if ( metabox.isActive ) {
+				memo[ location ] = jQuery( getMetaBoxContainer( location ) ).serialize();
+			}
+			return memo;
+		}, {} );
+		store.dispatch( metaBoxSetSavedData( dataPerLocation ) );
```
Comment (aduth) [inline editor/store/effects.js]: Could be [DRY'd](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) up a bit with the `INITIALIZE_META_BOX_STATE` effect logic.

File: editor/store/reducer.js [hunk 12]
```diff
@@ -661,60 +661,55 @@ const locations = [
...
 	};
 
 	return result;
 }, {} );
 
+/**
+ * Reducer keeping track of the meta boxes saving state.
+ *
+ * @param {boolean} state  Previous state.
+ * @param {Object } action Action Object.
```
Comment (aduth) [inline editor/store/reducer.js]: Extra space before the `}` is unexpected (here and in the DocBlock below)

File: editor/store/reducer.js [hunk 13]
```diff
@@ -661,60 +661,55 @@ const locations = [
...
+			return true;
+		case 'META_BOX_UPDATES_SUCCESS':
+			return false;
+		default:
+			return state;
+	}
+}
+
+/**
+ *
```
Comment (aduth) [inline editor/store/reducer.js]: This line is unnecessary.

File: editor/store/reducer.js [hunk 14]
```diff
@@ -661,60 +661,55 @@ const locations = [
...
 		isActive: false,
-		isDirty: false,
-		isUpdating: false,
 	};
 
 	return result;
 }, {} );
 
+/**
+ * Reducer keeping track of the meta boxes saving state.
```
Comment (aduth) [inline editor/store/reducer.js]: Personally I don't find this comment to be particularly helpful beyond pointing out that it's a reducer, and would encourage elaborating on the purpose for why we track a meta box saving state.

File: lib/meta-box-partial-page.php [hunk 15]
```diff
@@ -334,28 +304,29 @@ function the_gutenberg_metaboxes( $locations = array( 'advanced', 'normal', 'sid
...
+					);
+					?>
 				</div>
-			</form>
-			<?php
-		}
-	}
+			</div>
+		</form>
+		<?php } ?>
```
Comment (aduth) [inline lib/meta-box-partial-page.php]: I don't see a rule for it, but I'd conventionally have expected `if` and `endif` statements for conditions / loops within a PHP template:

>Note that requiring the use of braces just means that single-statement inline control structures are prohibited. You are free to use the alternative syntax for control structures (e.g. if/endif, while/endwhile)—especially in your templates where PHP code is embedded within HTML, for instance:
>
>```php
><?php if ( have_posts() ) : ?>
>    <div class="hfeed">
>        <?php while ( have_posts() ) : the_post(); ?>
>            <article id="post-<?php the_ID() ?>" class="<?php post_class() ?>">
>                
>            </article>
>        <?php endwhile; ?>
>    </div>
><?php endif; ?>
>```

https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#brace-style

**Review by aduth — COMMENTED** [review]
I'm generally fine with the direction here.

File: editor/store/effects.js (hunk 11 above)
Comment (youknowriad) [reply editor/store/effects.js]: Not so simple because the effect is triggering before the action. Didn't you make an update to `refx` to update this?

Comment (aduth) [reply editor/store/effects.js]: >Not so simple because the effect is triggering before the action. Didn't you make an update to `refx` to update this?

Yes: #3983

**Comment by youknowriad** [comment]
Any other concern here?

**Comment by emdashftw** [comment]
While using [Contextual Related Posts](https://github.com/WebberZone/contextual-related-posts) plugin I've noted I was able to **infinitely** save unmodified posts & pages.

After reporting them as a bug https://github.com/WebberZone/contextual-related-posts/issues/205 they linked back to this issue.

This feels bad for the UX / Workflow in my humble opinion. It gives me peace of mind when I see the button disabled. And the contrary creates me doubts, and insecurity on if I saved the last modification. I saw myself saving more than once, just in case......

This issue was from ~7 years ago. Many things may have changed around metaboxes / core.
So I'm wondering If Is there any possibility to reconsider how this work so the button can be disabled if there are no changes ?
Or if there's any other solution, that maybe the plugin developer could apply to address this problem.

cc @youknowriad @aduth @mtias

**Comment by youknowriad** [comment]
The best path forward for me is to move away from metaboxes. While we did ensure that metaboxes work in the block editor, they were and will never be first class citizen extensibility APIs. So I would recommend moving away from metaboxes in favor of regular block editor extensibility APIs. (for instance slots https://developer.wordpress.org/block-editor/reference-guides/slotfills/ ) and using the Data package to access and manipulate data.
