### PR TITLE
Fix inconsistent response when preloading OPTIONS type requests

### LINKED ISSUE #37966: `apiFetch` returns different types for preloaded, unparsed OPTIONS requests
### Description

In #35527, the preloading middleware was updated to use preloaded `OPTIONS` requests only once, which matched a previous change for `GET` requests.

When the middleware returns preloaded data for a `GET` request with `{ parse: false }`, it wraps the data in a `Response` object. But for `OPTIONS` requests, the middleware always returns a plain object, which means that preloaded `OPTIONS` requests return an object on the first call and a `Response` for all subsequent calls. As a developer, this inconsistency can affect me when:

1. I attempt to preload an `OPTIONS` request, but some other code makes the same request first.
2. Some other code preloads the `OPTIONS` request without my knowledge, but my code makes the request first.

At first glance, it seems to me that the expected behavior would be for the preloading middleware to return `Response` objects for unparsed `OPTIONS` requests like it does for `GET` requests.

Returning a `Response` would be a backwards compatibility break, but, on the other hand, #35527 itself is already a compatibility break (as was acknowledged at the time).

### Step-by-step reproduction instructions

Run in the console:

```js
wp.apiFetch.use(wp.apiFetch.createPreloadingMiddleware(
	{
		"OPTIONS": {
			"/someUrl": {
				'body': 'From middleware',
				'headers': {}
			}
		}
	}));
```

Then, run twice in the console:

```js
wp.apiFetch( {
	path: "/someUrl",
	method: 'OPTIONS',
	parse: false,
} ).then( res  => {
	console.log( res );
} );
```

Observe that the first request resolves to `{ body: ..., headers: ... }`, and the second request resolves to `Response { type: ... }`.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 5.9-RC2
- Gutenberg plugin not installed
- Chrome 96
- macOS 10.14

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by anton-vlasenko**
## Description
Preloading middleware doesn't return consistent responses for `OPTIONS` type requests if the `parse` option is set to `false.`

This PR aims to fix the preloading middleware so that it returns `window.Response` object if the `parse` option is set to false.
Although this is a breaking change I haven't noticed any issues with preloading.

Fixes https://github.com/WordPress/gutenberg/issues/37966

## How has this been tested?
1. Go to the Gutenberg -> Experiments page and enable the Navigation screen feature.
2. Save the changes.
3. Open the Gutenberg -> Navigation page.
4. Open the console, run the following code:
```js
wp.apiFetch.use(wp.apiFetch.createPreloadingMiddleware(
	{
		"OPTIONS": {
			"/someUrl": {
				'body': 'From middleware',
				'headers': {}
			}
		}
	}));
```
5. Run the following code in the console:
```js
wp.apiFetch( {
	path: "/someUrl",
	method: 'OPTIONS',
        parse: false
} ).then( res  => {
	console.log( res );
} );
```
#### Expected result (after the fix):
You should see `Response` object in the console (please see the screenshot), because we chose not to parse the response (`parse: false`).
#### Actual result (before this fix):
You will see `From middleware` text in the console as if the response was parsed.

## Screenshots 
Screenshot 2022-01-19 at 21 36 00

## Types of changes

Bug fix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
See also #28862

**Comment by anton-vlasenko** [comment]
> See also #28862

@chrisvanpatten 
Would you like to draw attention to something specific related to that PR?

**Comment by chrisvanpatten** [comment]
Just noting that it's related.

**Comment by noisysocks** [comment]
Let's note the breaking change in `packages/api-fetch/CHANGELOG.md` so that the major version of `@wordpress/api-fetch` is bumped next time packages are released.

**Review by getdave — COMMENTED** [review]
I just did a quick confidence check in `@wordpress/core-data` and the only `OPTIONS` request is in `canUser` resolver when requesting a singular resource with an ID. That request already uses `parse: false` so this should be safe.

Have yet to manually test.

**Comment by anton-vlasenko** [comment]
> Let's note the breaking change in `packages/api-fetch/CHANGELOG.md` so that the major version of `@wordpress/api-fetch` is bumped next time packages are released.

I've completely forgotten that I need to update the changelog. Thank you.
Fixed in 73ece20c9745530ddeb5b3e08a83675eceaa3a45

**Comment by anton-vlasenko** [comment]
> I just did a quick confidence check in `@wordpress/core-data` and the only `OPTIONS` request is in `canUser` resolver when requesting a singular resource with an ID. That request already uses `parse: false` so this should be safe.
> 
> Have yet to manually test.

Thank you for the review, @getdave.
Yes, I tested it too and didn't find any issues with this particular code.

File: packages/api-fetch/src/middlewares/preloading.js [hunk 1]
```diff
@@ -23,44 +23,52 @@ function createPreloadingMiddleware( preloadedData ) {
...
+			delete cache[ method ][ path ];
+
+			return prepareResponse( cacheData, !! parse );
 		}
 
 		return next( options );
 	};
 }
 
+/**
```
Comment (getdave) [inline packages/api-fetch/src/middlewares/preloading.js:57]: Add a comment here explaining the purpose of the function. Mainly the "why".

**Review by getdave — COMMENTED** [review]
I tested as per the instructions and it worked as expected.

I also searched the codebase for `parse: false` instances and almost all of them do not use `OPTIONS` requests. [I noted already](https://github.com/WordPress/gutenberg/pull/38051#pullrequestreview-858254138) that `canUser` does use `OPTIONS` but that seems ok.

I would appreciate a confidence check from @adamziel or someone else experienced with the data layer.

**Review by kevin940726 — APPROVED** [review]
LGTM 👍

**Review by adamziel — APPROVED** [review]
It looks good. Note that it's a breaking change – you can no longer preload the status or headers of the OPTIONS request. I think that's fine. It wasn't possible for the GET requests anyway, and as others noticed it wasn't even used. 🚢

File: packages/api-fetch/src/middlewares/preloading.js (hunk 1 above)
Comment (anton-vlasenko) [reply packages/api-fetch/src/middlewares/preloading.js:57]: Thanks.
Fixed in a7b12216b117e469b6f2af48c41c57f19727c4f2

**Review by getdave — APPROVED** [review]
LGTM
