### PR TITLE
Fix DropdownMenu arrows navigation and add missing aria-label.

### LINKED ISSUE #1874: DropdownMenu arrow navigation doesn't work with up/left arrow keys
The DropdownMenu component, currently used in the Table Block, implements arrow navigation, which is pretty good for accessibility. Pressing the DOWN or RIGHT arrow keys, the next item in the menu gets focused:

screen shot 2017-07-12 at 18 04 32

However, when pressing the UP or LEFT arrow keys, focus is lost.

### PR DESCRIPTION
**Pull request by afercia**
Fixes the DropdownMenu navigation with arrows. 
DOWN and RIGHT arrows were working, UP and LEFT weren't. Not sure why the difference, but this is probably related to the recent introduction of arrows navigation through blocks.
If so, there are probably more places where `stopPropagation()` will be needed.

Also, adds a missing label on the button that opens the drop down menu: it was completely empty... Uses `wp.i18n.__()` for consistency with what is already used in the file.

Todo: when one of the menu items is focused, pressing Escape should close the menu but it also makes the whole toolbar disappear. Will keep investigating and open a separate issue for this, probably together with other a11y improvements.

Fixes #1874

### CODE REVIEW

File: blocks/library/table/table-block.js [hunk 1]
```diff
@@ -89,6 +89,7 @@ export default class TableBlock extends wp.element.Component {
 						<li>
 							<DropdownMenu
 								icon="editor-table"
+								label={ wp.i18n.__( 'Edit Table' ) }
```
Comment (aduth) [inline blocks/library/table/table-block.js]: Per #1332 (#1205), we should be explicit about dependencies on the i18n module, i.e. use `import { __ } from 'i18n';` instead of assuming global.

**Review by aduth — COMMENTED** [review]
Yeah, appears this is needed because of the behavior of `onKeyDown` and block navigation in `VisualEditorBlock`.

https://github.com/WordPress/gutenberg/blob/af63d4eaceb8d6b0cc3c235da3b7fa30ac57dcfe/editor/modes/visual-editor/block.js#L341

We could move `onKeyDown` handler to the block's immediate wrapper element (i.e. not handling events in toolbar), but since the root element in this component can receive focus, we probably want arrow navigation to apply to the entire thing.

Which is all to say, this is probably a good solution, though problematic that descendants of the VisualEditorBlock component need to be aware of the behavior.

File: blocks/library/table/table-block.js (hunk 1 above)
Comment (afercia) [inline blocks/library/table/table-block.js]: Yep I know, I didn't want to change also all the other ones, because outside of the scope of this PR. But since we're here, I can do that if you agree.

Comment (aduth) [inline blocks/library/table/table-block.js]: >I didn't want to change also all the other ones, because outside of the scope of this PR.

Sure, especially in smaller pull requests like this one, I'm fine with some general refactoring sprinkled in as well. In an ideal world we'd have separate individual pull requests to refactor, but alas the world is not ideal and I find such PRs are few and far between.

But agree with the sentiment generally 👍
