### PR TITLE
Fix unexpected autosave for published posts

### LINKED ISSUE #27939: Autosaves are created even when no changes to a post have been made.
**Describe the bug**
If you open a post then relatively soon an autosave is always created, even if no changes have been made to the post. If you then wait around 60 seconds for the first heartbeat that autosave will be saved.

If you refresh the page you'll get a warning that there is an autosave that's more recent even though you've never edited anything at all.

**To reproduce**
1. Open a published post.
2. Do not make any changes or do anything
3. After a short time you should be able to see an autosave in the session storage.
4. After a little longer you should see a request saving that autosave to the database.
5. Refresh the page.
6. Observe a warning regarding a more recent autosave even though you've not done anything.

**Expected behavior**
There to be no autosaves or warning on posts that haven't been edited.

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Only in the gutenberg plugin.
- If the Gutenberg plugin is installed, which version is it? Seems to have been introduced in 9.6.0, tested on 9.6.2 as well as the 9.7-RC1 in both cases it's still present.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #27939 

I was not able to understand exactly where the  regression happened but for me, autosave shouldn't happen at all when the post is not dirty, this PR makes that change which fixes the issue reported in #27939 

See testing instructions in  #27939

### CODE REVIEW

File: packages/editor/src/components/autosave-monitor/index.js [hunk 1]
```diff
@@ -29,15 +29,11 @@ export class AutosaveMonitor extends Component {
 	}
 
 	componentDidUpdate( prevProps ) {
-		if (
-			this.props.disableIntervalChecks &&
-			this.props.editsReference !== prevProps.editsReference
-		) {
-			this.props.autosave();
+		if ( this.props.disableIntervalChecks ) {
```
Comment (ntsekouras) [inline packages/editor/src/components/autosave-monitor/index.js:32]: This will break native app that uses `<AutosaveMonitor disableIntervalChecks />`, so it expects to autosave at every edit, as per above comment:
`The timer may be disabled by setting `props.disableIntervalChecks` to `false`. In that mode, any change will immediately trigger props.autosave()`

Comment (youknowriad) [reply packages/editor/src/components/autosave-monitor/index.js:32]: Ohhh I get it now, I'll restore it. I thought it was used to disable autosaves.

Comment (ntsekouras) [reply packages/editor/src/components/autosave-monitor/index.js:32]: Can you also update the above comment that is wrong to:
```
by setting `props.disableIntervalChecks` to `true`
```

**Review by ntsekouras — APPROVED** [review]
Looks good! Will be good to update the previous wrong comment though :)

File: packages/editor/src/components/autosave-monitor/index.js (hunk 1 above)
Comment (dratwas) [reply packages/editor/src/components/autosave-monitor/index.js:32]: @ntsekouras is right. This change will break the autosave for the mobile app.

**Review by dratwas — APPROVED** [review]
