### PR TITLE
Core Data: Fix selectors returning stale results for different 'per_page' queries

### LINKED ISSUE #56355: Core data: selectors return stale data despite different query parameters
### Description

Unresolved core data selectors will return `null` if records are not found in state. They'll then go off and "resolve" the query (fetch the data from the API) and update the state.

When using query params such as `per_page`  — params that normally should trigger a new API call given that it can request records not yet available in the state — the selectors will not return `null` but return whatever it finds in the state until the resolvers are done.

From what I can gather, the `queries` reducer state for each entity [creates "stableKeys"](https://github.com/WordPress/gutenberg/blob/d4c367d25a87d46e26183f5958d384f350279b28/packages/core-data/src/queried-data/get-query-parts.js#L100-L100) to cache IDs for certain queries. Currently only `_fields` and `includes` queries are cached, otherwise the key is `""`. 

Props to @andrewserong for finding and reporting here: https://github.com/WordPress/gutenberg/pull/54046#pullrequestreview-1739021045

### Step-by-step reproduction instructions

Make sure you have a few posts or pages or other entities saved.

In your browser's console, fetch those entities:

```js
 // 1. API call, returns null
await wp.data.select( 'core' ).getEntityRecords( 'postType', 'post', { per_page: 2 } )

 // 2. No API call, returns expected results
await wp.data.select( 'core' ).getEntityRecords( 'postType', 'post', { per_page: 2 } )

 // 3.  API call, returns results from previous command 2
await wp.data.select( 'core' ).getEntityRecords( 'postType', 'post', { per_page: 3 } )

 // 4.  No API call, returns expected results
await wp.data.select( 'core' ).getEntityRecords( 'postType', 'post', { per_page: 3 } )

 // 5.  API call, returns results from previous command 3
await wp.data.select( 'core' ).getEntityRecords( 'postType', 'post', { per_page: 4 } )

 // 6.  No API call, returns expected results
await wp.data.select( 'core' ).getEntityRecords( 'postType', 'post', { per_page: 4 } ) 
```

### What I expected
For commands 3 and 4, we'd expect either `null` or `[]` or some other result to indicate that the selector cannot find these records.

Instead it returns the last known query.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 6.5 alpha
- Gutenberg latest (trunk)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes #56355.

Queries with different `per_page` values share the same `stableKey`, causing selectors to return cached items from a prior query instead of `null` while the new query resolves. Add a check in `getQueriedItemsUncached` that returns `null` when stored `itemIds` can't satisfy the requested pagination range and `totalItems` confirms more items exist.

Note: The new guardrail might fail when `totalItems` and the query return stale data, but that should be very rare.

## How
Tries to fix the bug without changing the query `cacheKey`.

## Testing Instructions

```js
 // 1. API call, returns null
await wp.data.select( 'core' ).getEntityRecords( 'postType', 'post', { per_page: 2 } )

 // 2. No API call, returns expected results
await wp.data.select( 'core' ).getEntityRecords( 'postType', 'post', { per_page: 2 } )

 // 3.  API call, returns null
await wp.data.select( 'core' ).getEntityRecords( 'postType', 'post', { per_page: 3 } )

 // 4.  No API call, returns expected results
await wp.data.select( 'core' ).getEntityRecords( 'postType', 'post', { per_page: 3 } )

 // 5.  API call, returns null
await wp.data.select( 'core' ).getEntityRecords( 'postType', 'post', { per_page: 4 } )

 // 6.  No API call, returns expected results
await wp.data.select( 'core' ).getEntityRecords( 'postType', 'post', { per_page: 4 } ) 
```

### Testing Instructions for Keyboard
Same.

### CODE REVIEW

File: packages/core-data/src/queried-data/selectors.js [hunk 1]
```diff
@@ -34,12 +34,8 @@ const queriedItemsCacheByState = new WeakMap();
 function getQueriedItemsUncached( state, query ) {
 	const { stableKey, page, perPage, include, fields, context } =
 		getQueryParts( query );
-	let itemIds;
-
-	if ( state.queries?.[ context ]?.[ stableKey ] ) {
-		itemIds = state.queries[ context ][ stableKey ].itemIds;
-	}
 
+	const itemIds = state.queries?.[ context ]?.[ stableKey ]?.itemIds;
```
Comment (Mamaduka) [inline packages/core-data/src/queried-data/selectors.js:38]: Unrelated. Just a minor cleanup.

File: packages/core-data/src/queried-data/selectors.js [hunk 2]
```diff
@@ -50,6 +46,17 @@ function getQueriedItemsUncached( state, query ) {
 			? itemIds.length
 			: Math.min( startOffset + perPage, itemIds.length );
 
+	// If the requested page range exceeds the stored itemIds, the data for
+	// this specific pagination window may not have been fetched yet. Return
+	// null unless totalItems confirms we already have all available items.
+	if ( perPage !== -1 && itemIds.length < startOffset + perPage ) {
+		const totalItems =
+			state.queries[ context ][ stableKey ]?.meta?.totalItems;
```
Comment (ramonjd) [inline packages/core-data/src/queried-data/selectors.js]: Incredibly minor, but I think we already know that `stableKey` exists from the `itemIds` check.

So `const totalItems = state.queries[ context ][ stableKey ].meta?.totalItems`

File: packages/core-data/src/queried-data/selectors.js [hunk 3]
```diff
@@ -50,6 +46,17 @@ function getQueriedItemsUncached( state, query ) {
...
+		if ( Number.isFinite( totalItems ) && itemIds.length < totalItems ) {
+			return null;
+		}
```
Comment (ramonjd) [inline packages/core-data/src/queried-data/selectors.js]: Reckon this is worth a test in packages/core-data/src/queried-data/test/selectors.js?

Something like this fails on trunk for me

```js
	it( 'should return null when per_page exceeds stored itemIds and more items exist', () => {
		const state = {
			items: {
				default: {
					1: { id: 1 },
					2: { id: 2 },
				},
			},
			itemIsComplete: {
				default: { 1: true, 2: true },
			},
			queries: {
				default: {
					'': {
						itemIds: [ 1, 2 ],
						meta: { totalItems: 5 },
					},
				},
			},
		};

		const result = getQueriedItems( state, { per_page: 3 } );
		expect( result ).toBe( null );
	} );
```

**Review by ramonjd — COMMENTED** [review]
What magic is this?! I can confirm it fixes https://github.com/WordPress/gutenberg/issues/56355 

I also created 100 pages and couldn't find any regressions using the data views-driven page list in the site editor.

I'll yield the floor to @andrewserong, who reported the issue, and/or @jsnajdr to double check but it LGTM. Thank you!!

File: packages/core-data/src/queried-data/selectors.js (hunk 3 above)
Comment (Mamaduka) [reply packages/core-data/src/queried-data/selectors.js]: Good point and thanks for the test!

**Review by andrewserong — APPROVED** [review]
> I'll yield the floor to @andrewserong, who reported the issue

Wow, that was so long ago, I can barely remember! 😄

I like the fix thanks for working on it @Mamaduka 👍 

✅ If the `per_page` is smaller than the items we've already got, then the cached value is returned
✅ If the `per_page` is larger than the items we've already got, then we get `null` in the first call, and in subsequent calls we get the cached results

This feels like how I'd expect it to work, and nice that you came up with a way to fix it without changing the `stableKey` (returning `null` effectively means that the value won't be treated as cached, so the change here correctly increases the cache misses) 🎉 

LGTM! 🚀

**Comment by Mamaduka** [comment]
Thanks for testing and feedback, everyone 🙇

**Comment by andrewserong** [comment]
Looks like we missed that `offset` will affect the effective number of title items for our calculation. I've opened a bug fix over in https://github.com/WordPress/gutenberg/pull/76613
