### PR TITLE
Fix : Snackbar Notice Inconsistency

### LINKED ISSUE #66364: View options: Distraction free is the only option to trigger a snackbar notice
### Description

In the top bar 'Options' ellipsis menu, the first 4 options are related to 'view modes' of the editor:
- Top toolbar
- Distraction free
- Spotlight mode
- Fullscreen more

Image

The 'Distraction free' mode is the only one to trigger a snackbar notice. The other ones don't.

Image

The snackbar notice is a little unexpected to me. Also, not sure how the 'Undo' control in the notice is any valuable, given the Options menu is still open and users can just click again there to undo.

On top of that, activating and deactivating these options triggers an audible `speak` message for screen reader users. However, the message for distraction free mode is duplicated. Actually, two different components trigger a message for this same feature. Also, the wording of the message is inconsistent.

Screenshot when dumping all the `speak` messages to the console:

Image

## Proposal

Either all these options should trigger a snackbar notice or none.
I'd like to propose to remove the snackbar notice of the Distraction free mode for consistency and simplicity. I'm not sure this snackbar notice adds much value. 

Note: recommended to check what happens when toggling these options via the Command palette.

### Step-by-step reproduction instructions

- Edit a post.
- Go to the top bar > Options.
- Toggle on and off each view option.
- Observe only Distraction free mode triggers a snackbar notice.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by Vrishabhsk**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/66364

- Enable `View Options` other than `Distraction Fee` to show a `snackbar notice` when they are `toggled`
- `View Options` affected : `Top toolbar`  `Spotlight mode`  `Fullscreen mode`

## Why?

- https://github.com/WordPress/gutenberg/issues/66364
> Either all these options should trigger a snackbar notice or none.
I'd like to propose to remove the snackbar notice of the Distraction free mode for consistency and simplicity. I'm not sure this snackbar notice adds much value.

> Note: recommended to check what happens when toggling these options via the Command palette.

## How?

- Create toggle actions similar to `toggleDistractionFree` for other `View Options`
- Replace hardcoded functionality with these `toggles` which allows `Snackbar Notice` to be visible when these options are toggled via the `More Menu`

## Testing Instructions

1. Edit a post.
2. Go to the top bar > Options.
3. Toggle on and off each view option.
4. Observe all modes triggers a snackbar notice.

### CODE REVIEW

File: packages/edit-post/src/components/more-menu/index.js [hunk 1]
```diff
@@ -14,12 +14,17 @@ import { unlock } from '../../lock-unlock';
...
 import EditPostPreferencesModal from '../preferences-modal';
+import { store as editorStore } from '../../store';
+import { useDispatch } from '@wordpress/data';
 
 const { ToolsMoreMenuGroup, ViewMoreMenuGroup } = unlock( editorPrivateApis );
 
 const MoreMenu = () => {
 	const isLargeViewport = useViewportMatch( 'large' );
 
+	// Action to toggle the FullscreenMode with a Notice for visual feedback.
```
Comment (ntsekouras) [inline packages/edit-post/src/components/more-menu/index.js]: Nit: no need for this comment I think.

File: packages/edit-post/src/components/more-menu/index.js [hunk 2]
```diff
@@ -14,12 +14,17 @@ import { unlock } from '../../lock-unlock';
 import ManagePatternsMenuItem from './manage-patterns-menu-item';
 import WelcomeGuideMenuItem from './welcome-guide-menu-item';
 import EditPostPreferencesModal from '../preferences-modal';
+import { store as editorStore } from '../../store';
```
Comment (ntsekouras) [inline packages/edit-post/src/components/more-menu/index.js]: I was so confused at this first... This is the `editPostStore`, so you need to rename.

File: packages/edit-post/src/components/more-menu/index.js [hunk 3]
```diff
@@ -29,6 +34,8 @@ const MoreMenu = () => {
 						name="fullscreenMode"
 						label={ __( 'Fullscreen mode' ) }
 						info={ __( 'Show and hide the admin user interface' ) }
+						handleToggling={ false }
```
Comment (ntsekouras) [inline packages/edit-post/src/components/more-menu/index.js]: This prop existed from before, but it's so weird..

File: packages/edit-post/src/store/actions.js [hunk 4]
```diff
@@ -509,3 +511,45 @@ export const toggleDistractionFree =
 		} );
 		registry.dispatch( editorStore ).toggleDistractionFree();
 	};
+
+/**
+ * Action that toggles the Fullscreen Mode view option.
+ * Shows a notice when option is toggled.
```
Comment (ntsekouras) [inline packages/edit-post/src/store/actions.js]: Nit: I think we can skip the `Shows a notice when option is toggled` in all new actions.

File: packages/edit-post/src/store/actions.js [hunk 5]
```diff
@@ -509,3 +511,45 @@ export const toggleDistractionFree =
...
+ */
+export const toggleFullscreenMode =
+	() =>
+	( { registry } ) => {
+		// Determine the current state of the Fullscreen Mode option.
```
Comment (ntsekouras) [inline packages/edit-post/src/store/actions.js]: Nit: no need for these comments in the whole function.

File: packages/editor/src/store/actions.js [hunk 6]
```diff
@@ -873,6 +873,82 @@ export const toggleDistractionFree =
...
 	};
 
+/**
+ * Action that toggles the Spotlight Mode view option.
+ * Shows a notice when option is toggled.
+ */
+export const toggleSpotlightMode =
+	() =>
+	( { registry } ) => {
+		// Determine the current state of the Spotlight Mode option.
```
Comment (ntsekouras) [inline packages/editor/src/store/actions.js]: Nit: same as above regarding the removal of these comments..

File: packages/editor/src/components/commands/index.js [hunk 7]
```diff
@@ -162,28 +145,8 @@ function useEditorCommandLoader() {
 		name: 'core/toggle-top-toolbar',
 		label: __( 'Toggle top toolbar' ),
 		callback: ( { close } ) => {
-			toggle( 'core', 'fixedToolbar' );
-			if ( isDistractionFree ) {
```
Comment (ntsekouras) [inline packages/editor/src/components/commands/index.js:168]: You didn't include this in the new action, but it seems you're correct as I couldn't find any reason for doing that.. It seems as a leftover, but I'll cc @draganescu to make sure.

**Review by ntsekouras — COMMENTED** [review]
Thanks for the PR, it looks good! My comments are mostly nits about inline comments :).

The thing that is not handled here though is the duplicate speak message. I think for these use cases it makes most sense to just use `MenuItem` component directly and avoid the weird `handleToggling` and `messageActivated/messageDeactivated` messages.

File: packages/edit-post/src/components/more-menu/index.js (hunk 3 above)
Comment (Vrishabhsk) [reply packages/edit-post/src/components/more-menu/index.js]: This will be required since `handleToggling` prop has default set to `true` and will cause `ambiguity` during `toggling`

File: packages/editor/src/components/commands/index.js (hunk 7 above)
Comment (Vrishabhsk) [reply packages/editor/src/components/commands/index.js:168]: - This functionality was already implemented in the `actions.js` so I removed it from here
- There is a dependency between `Top toolbar` and `Distraction Free` view options
-  I have handled and tested all `possible combinations` for the `trunk` and `fix/options-snackbar` branch

**Comment by Vrishabhsk** [comment]
Hi @ntsekouras 👋. Thanks for the detailed review
- I have added a couple of changes to fix the duplicate `speak` message issue
- Added `disableSpeech` prop to `PreferenceToggleMenuItem component` to prevent `speakMessage()` from executing
- Added `speakMessage` option to the `createNotice` function called by `createInfoNotice` for custom message capability

Let me know your thoughts on the changes. Thanks

**Comment by Vrishabhsk** [comment]
To confirm and validate the `A11y Speak` message, you can use the following script : [`a11y-speak-monitor.js`](https://codefile.io/f/OQBymdlwjD)

File: packages/edit-post/src/components/more-menu/index.js (hunk 3 above)
Comment (ntsekouras) [reply packages/edit-post/src/components/more-menu/index.js]: It just shouldn't be there in a component that has `toggle` in its name `PreferenceToggleMenuItem` :)

File: packages/preferences/src/components/preference-toggle-menu-item/index.js [hunk 8]
```diff
@@ -23,6 +23,7 @@ export default function PreferenceToggleMenuItem( {
 	handleToggling = true,
 	onToggle = () => null,
 	disabled = false,
+	disableSpeech = false,
```
Comment (ntsekouras) [inline packages/preferences/src/components/preference-toggle-menu-item/index.js]: We should be conservative when adding props to components and especially public ones, like this one. My comment related to `handleToggling` was about the same thing - it shouldn't be added in the first place.

>it makes most sense to just use MenuItem component directly and avoid the weird handleToggling and messageActivated/messageDeactivated messages.

`PreferenceToggleMenuItem` in essence is a thin wrapper of `MenuItem` for toggling preferences and speak the messages. In these cases we handle both of these in the action, so there is no need to use `PreferenceToggleMenuItem` at all, and instead use `MenuItem` directly.

Comment (Vrishabhsk) [reply packages/preferences/src/components/preference-toggle-menu-item/index.js]: Hi @ntsekouras 👋 Thanks for review
- I have addressed the changes in the latest commit

Let me know your thoughts on it. Thanks

File: packages/notices/src/store/actions.js [hunk 9]
```diff
@@ -69,6 +71,7 @@ let uniqueId = 0;
 export function createNotice( status = DEFAULT_STATUS, content, options = {} ) {
 	const {
 		speak = true,
+		speakMessage = null,
```
Comment (ntsekouras) [inline packages/notices/src/store/actions.js]: I don't get why we would need this - at least in this case. We shouldn't have two different messages.

Comment (Vrishabhsk) [reply packages/notices/src/store/actions.js]: - The messages used for the `PreferenceToggleMenuItem` were different from the `label` used, which is why I implemented this
- If we remove this for the `Menu Items`, the message would be `Distraction Free off / Distraction Free on` which does not provide much context.
- Although for argument's sake, even `Distraction Free mode activated` also does not provide much context. 
- I would suggest expanding this custom message to give more context for e.g. : `Distraction Free view option is enabled/disabled for your editor`

**Review by ntsekouras — COMMENTED** [review]
Thank you for iterating!

Related though to the [latest feedback ](https://github.com/WordPress/gutenberg/issues/66364#issuecomment-2439963931)on the issue, maybe it's better **not** to show a notice on the more menu clicks, but also preserve the spoken messages.

So some refactoring will be needed. I think by adding a `createNotice` param (with default `true) in `toggleDistractionFree` and revert to use `PreferenceToggleMenuItem` in the more menu items would be enough.

File: packages/notices/src/store/actions.js (hunk 9 above)
Comment (ntsekouras) [reply packages/notices/src/store/actions.js]: >Although for argument's sake, even Distraction Free mode activated also does not provide much context.

Yeah, I don't think we would need two different messages for now.

**Comment by Vrishabhsk** [comment]
So just that we are on the same page :
- Add `createNotice` param in `toggleDistractionFree` function
- Revert `MenuItem` back to `PreferenceToggleMenuItem` and remove the need to use `onToggle` as it was setup initially
- Leave the newly created `actions` and `notice` related changes as they are for now

**Comment by Vrishabhsk** [comment]
I also noticed quite a few changes made to the labels here : https://github.com/WordPress/gutenberg/pull/66371

**Comment by ntsekouras** [comment]
>So just that we are on the same page :

>Add createNotice param in toggleDistractionFree function
Revert MenuItem back to PreferenceToggleMenuItem and remove the need to use onToggle as it was setup initially
Leave the newly created actions and notice related changes as they are for now

That were my first thoughts but didn't spent time in code. Probably it will be enough.

To elaborate a bit.. 
1. The new actions are needed to use in context of commands etc.. They just toggle a single preference and speak the message.
2. `PreferenceToggleMenuItem` handles a preference toggling as is and handles speaking a message. So in the more menu items we don't need to dispatch the action. We need though the messages to match the ones in the actions.
3. `toggleDistractionFree` is already an action and is also triggered through other user actions. Since we have extra logic in that one, we should probably have a param(createNotice) in the action not to create a notice in the more menu item.

Makes sense?

File: packages/editor/src/components/more-menu/index.js [hunk 10]
```diff
@@ -30,11 +30,13 @@ export default function MoreMenu() {
 	const { openModal } = useDispatch( interfaceStore );
 	const { set: setPreference } = useDispatch( preferencesStore );
 	const { toggleDistractionFree } = useDispatch( editorStore );
-	const showIconLabels = useSelect(
-		( select ) =>
-			select( preferencesStore ).get( 'core', 'showIconLabels' ),
-		[]
-	);
+	const { showIconLabels } = useSelect( ( select ) => {
```
Comment (ntsekouras) [inline packages/editor/src/components/more-menu/index.js]: Is this a leftover from other commits? Nothing really changed here.

File: packages/editor/src/store/actions.js [hunk 11]
```diff
@@ -837,42 +839,122 @@ export const toggleDistractionFree =
...
+									label: __( 'Undo' ),
+									onClick: () => {
+										registry.batch( () => {
+											registry
+												.dispatch( preferencesStore )
+												.set(
+													'core',
+													'fixedToolbar',
+													isDistractionFree
+														? true
```
Comment (ntsekouras) [inline packages/editor/src/store/actions.js]: That was from before, but let's just remove the ternary operator and keep `isDistractionFree`.

File: packages/notices/src/store/actions.js (hunk 9 above)
Comment (ntsekouras) [reply packages/notices/src/store/actions.js]: Let's please remove this `speakMessage` prop. We don't need it as it already speaks the content.

File: packages/editor/src/store/actions.js [hunk 12]
```diff
@@ -812,9 +812,11 @@ export function setIsListViewOpened( isOpen ) {
  * Action that toggles Distraction free mode.
  * Distraction free mode expects there are no sidebars, as due to the
  * z-index values set, you can't close sidebars.
+ *
+ * @param {boolean} createNotice Whether to create a notice when this action is triggered.
  */
 export const toggleDistractionFree =
-	() =>
+	( createNotice = true ) =>
```
Comment (ntsekouras) [inline packages/editor/src/store/actions.js]:
```suggestion
	( { createNotice = true } = {} ) =>
```

Let's make this an object to be safer (in case of future additions) and have more clarity about the params we pass.

**Review by ntsekouras — COMMENTED** [review]
This is really close, thank you!

Besides the comments I left, we need to do:
1. Remove `scope and name` [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/more-menu/index.js#L76) as we don't use them. Also pass the new param at `onToggle` like this: `toggleDistractionFree( { createNotice: false } )`. 
2. We should have consistent messages in both more menus and actions. That means either have `${option} off/on` or `${option activated/deactivated`. I'd go for `on/off` personally.
3. Commented about it, but very important to remove the `speakMessage` prop you added here.

With these addressed, I think we can land.

**Comment by Vrishabhsk** [comment]
Thanks @ntsekouras for the review 👍 
- I went ahead with `${option} activated/deactivated.` to keep the messages consistent.
- Disabled the notice for `Distraction Free` Menu Item
- We cannot remove `scope and name` since it determines its `isActive` attribute which renders the `check` icon
- I have removed the `speakMessage` prop

**Review by ntsekouras — APPROVED** [review]
Great work here, thanks!
