### PR TITLE
DataViews: Fix pagination on manual input

### LINKED ISSUE #55937: Data View: Pagination error on manual input
Relates to #55083.

## What?

When manually entering a page number in the pagination control, an invalid page number incorrectly enables the _previous_ pagination controls, allowing the user to "access" pages below 1.

## Expectations

When manually entering a page number, an invalid number should be reset to within range, and the pagination controls should be enabled appropriately:
* If it is reset to the first page, the _previous_ controls should be disabled.
* If it is reset to the last page, the _next_ controls should be disabled.
* If it is reset to both (that is, there is only one page), both the _previous_ and _next_ controls should be disabled.

## Reproduction

1. Navigate to the pagination control, and enter a page number out of range (e.g. `0`).
   A set of greyed-out pagination controls, with a text box reading "0"
2. Note that the value will reset to a number within range (e.g. `1`), but that the "First page" and "Previous page" buttons will be enabled.
   A set of pagination controls, the double-left and single-left arrows enabled, with a text box reading "1"
3. Pressing the "First page" button will reset appropriately to the first page
   A set of greyed-out pagination controls, with a text box reading "1"
4. Pressing the "Previous page" button will move backwards through non-existent pages
   A set of pagination controls, all enabled, with a text box reading "-7"

https://github.com/WordPress/gutenberg/assets/159848/01d38b88-f2d7-4ad5-b01d-1ab994cb1f67

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/55937

When manually entering a page number in the pagination control, an invalid page number incorrectly enables the previous pagination controls, allowing the user to "access" pages below 1.

## Testing Instructions
1. Navigate to the pagination control, and enter a page number out of range (e.g. 0).
2. Note that the value will reset to a number within range (e.g. 1), but that the "First page" and "Previous page" buttons will be disabled.

### CODE REVIEW

File: packages/edit-site/src/components/dataviews/pagination.js [hunk 1]
```diff
@@ -83,16 +83,17 @@ function Pagination( {
 										min={ 1 }
 										max={ totalPages }
 										onChange={ ( value ) => {
+											const _value = +value;
```
Comment (youknowriad) [inline packages/edit-site/src/components/dataviews/pagination.js:86]: This is the fix? Can you explain it. It's a bit obscure?

Comment (ntsekouras) [reply packages/edit-site/src/components/dataviews/pagination.js:86]: The value of the input on the `onChange` callback is a `string` and we keep an integer in our view config. That made some strict checks to fail.

Comment (youknowriad) [reply packages/edit-site/src/components/dataviews/pagination.js:86]: Ah ok, maybe we should do `parseInt` instead of the `+` trick. (as you wish)

**Review by youknowriad — APPROVED** [review]
