### PR TITLE
fix: Enable access to block settings within UBE

### LINKED ISSUE #47966: Unsupported block: Post title is displayed in UBE (Unsupported block editor) when editing an unsupported block
## Description

When editing unsupported blocks in the app using UBE (Unsupported Block Editor), it should only display the block. However, I recently noticed that the Post title is also being shown which adds confusion to the experience.

## Step-by-step reproduction instructions

1. Create a post in the web version of the editor.
2. Add an unsupported block like a Table block.
3. Save the post.
4. Open the same post in the app.
5. Observe that the block is unsupported.
6. Tap on the unsupported block and tap on _Edit using web editor_.
7. When the content is loaded, observe that the Post title is displayed.

**NOTE:** UBE (Unsupported Block Editor) is only available in WPCOM or self-hosted sites connected with Jetpack.

## Expected behaviour

The Post title shouldn't be displayed when editing an unsupported block using UBE (Unsupported Block Editor).

## Actual behaviour

The Post title is displayed when editing an unsupported block using UBE (Unsupported Block Editor).

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: iPhone 11
- Operating system: iOS 15.4
- WordPress app version:  `21.7`

### LINKED ISSUE #48298: Blocks settings unavailable within the Unsupported Block Editor
## Description

When editing a block with the mobile app's Unsupported Block Editor (UBE), the "Show more settings" option is not available. 

The source of this issue is likely similar to https://github.com/WordPress/gutenberg/issues/33592 and related to the inherent brittleness of the foundational implementation referenced in https://github.com/WordPress/gutenberg/issues/21874. There may have been a change the web editor's DOM hierarchy/class names or a browser-specific issue introduced. 

## Step-by-step reproduction instructions

1. Create a post in the web editor and add a block that is not supported by the mobile app, e.g. Archives. 
2. Open the same post with the mobile app. 
3. Select the block.
4. Tap the <kbd>?</kbd> button. 
5. Tap "Edit using web editor." 
6. Tap the three-dot menu in the block toolbar. 

## Expected behaviour

The "Show more settings" option is available. 

## Actual behaviour

The "Copy block" option is available. 

## Screenshots or screen recording (optional)

<details><summary>Screenshot</summary>

ube-block-settings-missing

</details>

## WordPress information
- WordPress version:  6.1
- Gutenberg version:  15.1.1
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  Yes

## Device information
- Device:  iPhone SE
- Operating system:  iOS 16.3
- WordPress app version:  21.8.0.0

### PR DESCRIPTION
**Pull request by dcalhoun**
## Related PRs

* https://github.com/wordpress-mobile/gutenberg-mobile/pull/5508

## What?

Repair access to the block settings sidebar within the unsupported block editor
(UBE). Fixes #48298. 

Repair hiding of unrelated editor UI in the UBE. Fixes #47966. 

## Why?

Without access to the block settings, a user cannot modify important settings
for a given block. 

Also, displaying UI elements unrelated to the sole block is
confusing and unnecessary. 

### Block Settings
Previously, the UBE relied upon the presence of the "Show more settings" button,
but that was removed in #46709. This updates the UBE to rely upon the sidebar
toggle button that is present in the post editor header. Because the sidebar toggle 
button can also reveal the post settings, this only displays the sidebar toggle 
button whenever a block is selected.

### Post Title Visibility

The override styles used by the UBE were no longer successfully applied once https://github.com/WordPress/gutenberg/pull/46212 
wrapped the editor within an `iframe`. It is not possible to style `iframe` 
children elements from the parent `document` context. These changes no 
copy the override styles to reside within the `iframe` document so they are 
applied to the children elements. 

### Unrelated Changes

This also updates existing Android-specific scripts to only run when Android
devices are detected by parsing the user agent string. Previously, the entire
`editor-behavior-overrides` script was only loaded by the Android platform. 
Now, both platforms load the script, and portions of it only run for Android. 

## Testing Instructions

> **Note**
> There is one known issue. On iOS, tapping towards the bottom of the screen — between the sole block and the keyboard toolbar — clears the block selection, but the sidebar toggle button remains erroneously displayed. This does not occur for Android. This can be seen at the end of the screencast below. 

Verify the steps outlined in #48298, #34668, and #47966 pass.

1. Using the WordPress mobile app, open a post containing unsupported blocks,
   e.g. Archives, Table.
1. Select an unsupported block.
1. Tap the <kbd>?</kbd> button.
1. Tap "Edit using web editor."
1. Verify the sidebar toggle button is not present in the top-right corner.
1. Select the unsupported block.
1. Tap the sidebar toggle button in the top-right corner.
1. Verify the block settings are displayed.

### Testing Instructions for Keyboard

n/a

## Screenshots or screencast 

https://user-images.githubusercontent.com/438664/221731846-229b3e08-321d-417f-aa4e-68b1338ec86e.mov

### CODE REVIEW

**Comment by dcalhoun** [comment]
Hey @geriux. 👋🏻 There is one known issue referenced in the PR description, but I wanted to seek your feedback on the approach here. Also, if you have any ideas on known issue let me know. 😬😄 Thanks!

**Comment by dcalhoun** [comment]
For the known issue, it appears [the logic](https://github.com/WordPress/gutenberg/blob/f64379314802d2d4b64077ca6b980e9df824b762/packages/block-editor/src/components/block-selection-clearer/index.js) clearing block selection does dispatch `CLEAR_SELECTED_BLOCK`, but for whatever reason that is not received by the store extending logic in this PR. Clicking elsewhere _does_ cause the dispatched event to arrive to the store extending logic. 

Additionally, I attempted to leverage the [`clearBlockSelection` settings](https://github.com/WordPress/gutenberg/blob/4b4b4ca96f201a06cf7fffb9921041957f070fac/packages/block-editor/src/store/defaults.js#L30) to prevent removing selection from the sole block. However, the [setting value](https://github.com/WordPress/gutenberg/blob/f64379314802d2d4b64077ca6b980e9df824b762/packages/block-editor/src/components/block-selection-clearer/index.js#L23) is stale/incorrect _only_ when clicking in this space between the title and block toolbar. 

It is like this space is a "twilight zone." 😄 Not sure what is going on.

**Comment by geriux** [comment]
> There is one known issue. On iOS, tapping in-between the block toolbar and the post title clears the block selection, but the sidebar toggle button remains erroneously displayed. This does not occur for Android. This can be seen at the end of the screencast below.

One thing that noticed from this comment was the mention of the post title and then I realized from testing and seeing the demo video that the Post title and the (+) Button are there.

I guess something changed in Gutenberg Web and how it loads the editor but it looks like other things we have for the UBE are not working correctly, like the CSS rules to hide the Post title, (+) button, etc.

Maybe if we check why that's not working it could solve the issue you mentioned about the post title clearing the selection, what do you think?

I looked for an older screenshot of the UBE and this is what it looked like:

<kbd>Screenshot 2023-02-27 at 13 10 17</kbd>

As you can see only the toolbar and the block are visible.

**Comment by dcalhoun** [comment]
> One thing that noticed from this comment was the mention of the post title and then I realized from testing and seeing the demo video that the Post title and the (+) Button are there.

Yes, I noticed the same and [investigated it a bit](https://github.com/WordPress/gutenberg/issues/47966#issuecomment-1444264356). 

> Maybe if we check why that's not working it could solve the issue you mentioned about the post title clearing the selection, what do you think?

I had considered them separate issues, but you are right that solving https://github.com/WordPress/gutenberg/issues/47966 might have an impact on the clear selected block issue. I'll look into it more. 👀

**Comment by geriux** [comment]
> Yes, I noticed the same and [investigated it a bit](https://github.com/WordPress/gutenberg/issues/47966#issuecomment-1444264356).
> >

Ohh I missed that issue, thanks for sharing the link 😃 

>I had considered them separate issues, but you are right that solving https://github.com/WordPress/gutenberg/issues/47966 might have an impact on the clear selected block issue. I'll look into it more. 👀

I wonder if we could use the iFrame's address to render the content in the UBE directly 🤔 I haven't tested this but maybe it could be a possible fix if trying to inject content within the iframe becomes difficult.

**Comment by geriux** [comment]
> I wonder if we could use the iFrame's address to render the content in the UBE directly 🤔 I haven't tested this but maybe it could be a possible fix if trying to inject content within the iframe becomes difficult.

Nevermind, it is setting the editor's content using `srcdoc` instead of an URL 😅

File: packages/react-native-bridge/android/react-native-bridge/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/GutenbergWebViewActivity.java [hunk 1]
```diff
@@ -327,16 +327,16 @@ private void injectCssScript() {
         mWebView.evaluateJavascript(injectCssScript, message -> {
             if (message != null) {
                 String editorStyle = getFileContentFromAssets("gutenberg-web-single-block/editor-style-overrides.css");
-                editorStyle = removeWhiteSpace(removeNewLines(editorStyle));
```
Comment (dcalhoun) [inline packages/react-native-bridge/android/react-native-bridge/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/GutenbergWebViewActivity.java:330]: This rudimentary stripping of whitespace inadvertently modifies the CSS selectors, causing them to be interpreted as completely different selectors. E.g. `.ancestor .descendent` is different from `.sibling-1.sibling-2`. Ideally, a proper CSS minification is utilized long term.

File: packages/react-native-bridge/common/gutenberg-web-single-block/content-functions.js [hunk 2]
```diff
@@ -25,19 +25,12 @@ window.getHTMLPostContent = () => {
...
-		window.getBlockEditorStore();
-
 	// Setup the editor with the inserted block.
 	const post = window.wp.data.select( 'core/editor' ).getCurrentPost();
 	window.wp.data
 		.dispatch( 'core/editor' )
 		.setupEditor( post, { content: blockHTML } );
 
-	// Select the first block.
-	const clientId = blockEditorSelect.getBlocks()[ 0 ].clientId;
```
Comment (dcalhoun) [inline packages/react-native-bridge/common/gutenberg-web-single-block/content-functions.js:38]: This often threw an error where the first block was `undefined`. This logic was relocated to `editor-behavior-overrides` to await the `iframe` render.

File: packages/react-native-bridge/common/gutenberg-web-single-block/editor-behavior-overrides.js [hunk 3]
```diff
@@ -1,59 +1,167 @@
...
+		},
+	};
+}
+
+window.wp.data.use( toggleBlockSelectedStyles );
+
+// The editor-canvas iframe relies upon `srcdoc`, which does not trigger a
+// `load` event. Thus, we must poll for the iframe to be ready.
+let overrideAttempts = 0;
+const overrideInterval = setInterval( () => {
```
Comment (dcalhoun) [inline packages/react-native-bridge/common/gutenberg-web-single-block/editor-behavior-overrides.js:129]: I explored a few different approaches for awaiting the `iframe` render. Unfortunately, none of them succeeded.

- `iframe.onload` does not work when the `iframe` uses `srcdoc` instead of `src`. 
- Awaiting a "ready Gutenberg" via [subscribing to the store](https://github.com/WordPress/gutenberg/blob/a7eb9a220f7105d6a194b0e0228fbbe2484ae727/packages/react-native-bridge/common/gutenberg-web-single-block/content-functions.js#L60-L68) runs before the `iframe` renders.

File: packages/react-native-bridge/common/gutenberg-web-single-block/editor-behavior-overrides.js [hunk 4]
```diff
@@ -1,59 +1,167 @@
...
+	) {
+		clearInterval( overrideInterval );
+
+		// Clone the editor styles so that they can be copied to the iframe, as
+		// elements within an iframe cannot be styled from the parent context.
+		const overrideStylesClone = overrideStyles.cloneNode( true );
+		overrideStylesClone.id = 'editor-styles-overrides-2';
+		// Append to document rather than the head, as React will remove this
+		// mutation.
+		canvasIframe.contentDocument.documentElement.appendChild(
```
Comment (dcalhoun) [inline packages/react-native-bridge/common/gutenberg-web-single-block/editor-behavior-overrides.js:150]: The `iframe` implementation "manages" the `head` element. So, we must avoid mutating that element, otherwise React may remove any changes we make.

**Comment by dcalhoun** [comment]
👋🏻 @geriux. I updated this PR to address the missing styles hiding the unrelated editor UI. Unfortunately, doing so did not resolve the issue where tapping certain areas of the do not properly trigger a `CLEAR_SELECTED_BLOCK` action and toggle the sidebar button. 

That said, while I am not too proud of the implementation presented in this PR, I am wondering it makes sense to land this in a beta fix for the time being. It improves the UX a good bit IMO and we are approach the app release. If desired, we could iterate further on the implementation at a future time.  

For future iterations, there are a lot of oddities that occur due to the new `iframe`. It is a bit of a "dance" to get the UBE functioning as we expect. It may be worthwhile to push again for a first-party mechanism for rendering a single block with a streamlined interface to support it that doesn't involve overriding existing styles and scripts.

**Comment by geriux** [comment]
> That said, while I am not too proud of the implementation presented in this PR, I am wondering it makes sense to land this in a beta fix for the time being. It improves the UX a good bit IMO and we are approach the app release. If desired, we could iterate further on the implementation at a future time.

I agree we should land this for now and see what we do afterward, I'll focus on reviewing and testing today, thanks!

>For future iterations, there are a lot of oddities that occur due to the new iframe. It is a bit of a "dance" to get the UBE functioning as we expect. It may be worthwhile to push again for a first-party mechanism for rendering a single block with a streamlined interface to support it that doesn't involve overriding existing styles and scripts.

I was thinking maybe we could add a flag so it doesn't load the iFrame for the UBE, I saw this PR so maybe we [could do the same](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-post/src/components/visual-editor/index.js#L342-L350).

**Comment by dcalhoun** [comment]
> I agree we should land this for now and see what we do afterward, I'll focus on reviewing and testing today, thanks!

Great — thanks! 

> I was thinking maybe we could add a flag so it doesn't load the iFrame for the UBE, I saw this PR so maybe we [could do the same](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-post/src/components/visual-editor/index.js#L342-L350).

Possibly. I did see the flag as well. However, It seems the [`iframe ` initiative](https://github.com/WordPress/gutenberg/issues/33346) is being done for very specific reasons, some of which are outlined in more detail in https://github.com/WordPress/gutenberg/issues/20797. While not all the reasons may be relevant for the UBE, some of them may be relevant. E.g. avoiding leaked admin styles overriding theme styles in the editor. So, I am unsure if disabling the `iframe` is a good long-term solution or if the flag will even be available long term.

**Review by geriux — APPROVED** [review]
LGTM! 🚀  Nice work and thanks for working on a fix so quickly 👏 

The new code and organization changes make sense to me, I also tested this on both iOS and Android, and I shared what I tested over this [comment](https://github.com/wordpress-mobile/gutenberg-mobile/pull/5508#issuecomment-1448584811) in Gutenberg mobile.
