### PR TITLE
Footnotes: Fix recursion into updating attributes when attributes is not an object

### LINKED ISSUE #53212: Auto-save performed when manipulating a footnotes block breaks attributes in other blocks.
### Description

In function **updateAttributes**(attributes) in const **updateFootnotes** called in the footnote block,

Recursive calls to the updateAttributes function

```
        if (Array.isArray(value)) {
          attributes[key] = value.map(updateAttributes);
          continue;
        }
```
If there is an attribute of an array of strings at this time

```
                imgSizes : {
                    type: "array",
                    items: {
                        type: "string"
                    },
                    default: []
                },
```
For example, the string "1024x768" is converted to {0: "1", 1: "0", 2: "2", 3: "4", 4: "x", 5: "7", 6: "6", 7: "8"} and an error occurs

### Step-by-step reproduction instructions

This happens when you manipulate the footnote block in the editor.

This happens in blocks that use an array of strings in the attributes, but does not seem to be used in the core block.

### Screenshots, screen recording, code snippet

gutenberg-footnotes-attribute

### Environment info

WordPress 6.3 RC2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

### PR DESCRIPTION
**Pull request by andrewserong**
## What?

Fixes #53212 

Fix the footnotes logic from unintentionally converting an array of strings block attribute into an object keyed by numerical string index. Currently, custom blocks that use an array of strings will likely break when a user goes to add a footnote anywhere else on the same post or page as the custom block.

## Why?

When passed a string, the expansion of `attributes = { ...attributes }` results in an object keyed by string index. This happens due to the recursive call to `updateAttributes` for attributes that are an array. The problem is most noticeable with an attribute that is set to be an array of strings.

## How?

Within the footnotes' logic to update attributes (contained within `updateFootnotes`) check that `attributes` is an object before expanding it into an object.

## Testing Instructions

There could likely be a simpler way to test this (i.e. add an array of attributes to an existing block in the Gutenberg repo), but to be complete about it, I did the following to create a custom block for testing:

* Create a new custom block plugin via [`create-block`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/) (`npx @wordpress/create-block my-test-block`)
* In `block.json` add the following to `attributes`:

```
	"attributes": {
		"items": {
			"type": "array",
			"items": {
				"type": "string"
			},
			"default": [ "apples", "oranges" ]
		}
	},
```

* Then, in the block's `edit.js` file, add the following to output the array of strings within the edit view:

```
export default function Edit( { attributes } ) {
	const { items } = attributes;
	console.log( items );
	return (
		<div { ...useBlockProps() }>
			{ items.map( ( item, index ) => {
				return <p key={ index }>{ item }</p>
			} ) }
		</div>
	);
}
```

This creates a custom block that renders out an array of strings within the edit view for the block. With the block plugin built and activated, go to add a Paragraph to the same post or page as the custom block. Within that Paragraph block go to add Footnotes. Without this PR, the block will error out.

In case it helps testing, I've pushed the above example custom block to a public repo over in https://github.com/andrewserong/andy-test-block

In addition to the above: check that adding Footnotes to nested blocks works as on `trunk` (e.g. paragraphs, quotes (especially the citation within the quote), and lists within multiple levels of nesting in Group blocks, etc)

## Screenshots or screencast 

| Before | After |
| --- | --- |
|  |  |

### CODE REVIEW

File: packages/core-data/src/entity-provider.js [hunk 1]
```diff
@@ -221,6 +221,15 @@ export function useEntityBlockEditor( kind, name, { id: _id } = {} ) {
 			);
 
 			function updateAttributes( attributes ) {
+				// Only attempt to update attributes, if attributes is an object.
+				if (
+					! attributes ||
```
Comment (andrewserong) [inline packages/core-data/src/entity-provider.js:226]: Note: this falsy check is required because `typeof null` equals `object` so this catches if somehow this function is called with `null`.

Comment (ramonjd) [reply packages/core-data/src/entity-provider.js:226]: I haven't tested this yet, but just staring at it makes me think it's a safe change regardless since we're destructuring `attributes` below.

File: packages/core-data/src/entity-provider.js [hunk 2]
```diff
@@ -221,6 +221,15 @@ export function useEntityBlockEditor( kind, name, { id: _id } = {} ) {
...
+					Array.isArray( attributes ) ||
```
Comment (ramonjd) [inline packages/core-data/src/entity-provider.js:227]: Will attributes ever be an Array?

_Edit_: okay, I just re-read the PR description. Ignore me.

File: packages/core-data/src/entity-provider.js (hunk 1 above)
Comment (andrewserong) [reply packages/core-data/src/entity-provider.js:226]: Yeah, one of the things that tripped me up when looking at this function is that when passed anything other than an object, the destructuring winds up converting (or attempting to convert) to an object.

Hopefully it's a fairly safe-ish change! The thing that took me the longest was testing it out in a custom block 😅

Thanks for taking a look!

**Comment by andrewserong** [comment]
Update: in case it helps with testing, I've pushed the example test block from the PR description to a public repo, which you can check out / symlink into your local dev environment's `wp-content/plugins` directory: https://github.com/andrewserong/andy-test-block

**Review by ramonjd — APPROVED** [review]
LGTM

It'd be good to get @ellatrix's learned eye to run over it. 

## Before

Strings are destructured

Screenshot 2023-08-02 at 4 48 33 pm


## After


Screenshot 2023-08-02 at 4 59 12 pm

File: packages/core-data/src/entity-provider.js [hunk 3]
```diff
@@ -221,6 +221,15 @@ export function useEntityBlockEditor( kind, name, { id: _id } = {} ) {
...
+					typeof attributes !== 'object'
```
Comment (ramonjd) [inline packages/core-data/src/entity-provider.js:228]: I just had to double check for my own benefit: this could catch `null` but I think it'd be okay since `{ ...null }` returns `{}`

👍🏻

**Review by ellatrix — APPROVED** [review]
Thanks! I guess we should add an e2e test in a follow-up that registers such block.

File: packages/core-data/src/entity-provider.js (hunk 3 above)
Comment (andrewserong) [reply packages/core-data/src/entity-provider.js:228]: Thanks for the extra checking!

The problem for `null` values is a little edge-casey, but an example would be if a block had an attribute that's a list of items where `null` is a valid value. For a somewhat contrived example, if we update the attributes in the test block's `block.json` to the following:

```
  "attributes": {
    "items": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": [
        "apples",
        null,
        "oranges"
      ]
    }
  },
```

Then, if we remove the `! attributes` check in this `if` block so that we don't handle null / falsy values, then when `{ ...null }` turns the value into an empty object, the attributes are mutated.

Before / after:

image

In practice, I think it's fairly unlikely that there'll be blocks out in the wild affected by it, but good to catch `null` values here and return as-is just in case. I reckon a good next step will be to add some extra tests like Ella mentioned so that we're covering these sorts of edge cases 🙂

**Comment by andrewserong** [comment]
Thanks for the reviews, folks! I'll merge this in now, and happy to help look into follow-up tests 👍

File: packages/core-data/src/entity-provider.js (hunk 3 above)
Comment (ramonjd) [reply packages/core-data/src/entity-provider.js:228]: Thanks for taking the time to double check!

**Comment by andrewserong** [comment]
> Thanks! I guess we should add an e2e test in a follow-up that registers such block.

I worked out how to test it without needing more e2e tests over in #53376 🙂

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the update/bugfixes-6-3-1 branch to get it included in the next release: ab04074d18
