### PR TITLE
Autocomplete: Fix Voiceover not announcing suggestions

### LINKED ISSUE #47767: Autocomplete: Must move inside iFrame for slash block insert
### Description

When trying to insert a block with the /block name syntax, the list box is no longer read to screen readers. This is because the `aria-owns` and `aria-activedescendent` attributes contain IDs out of the current iFrame scope causing a null error.

### Step-by-step reproduction instructions

1. Open a post or page.
2. Go to insert a block by typing in the empty paragraph field. Something like /ima should do.
3. Arrow up and down.
4. Check to see the field now has the 2 ARIA attributes as mentioned in the description above.
5. Try to do a `document.getElementByID()` or `document.querySelector()` using the IDs from the ARIA attributes. The commands will return null.
6.I believe this is because the Autocomplete component renders outside the iFrame. Needs a fix as this feature is completely broken for screen reader users. 

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WordPress: 6.2-alpha-54678
Browser: Firefox
Screen reader: NVDA
OS: Windows 10 Professional

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by alexstine**
## What?

Fixes #47767

## Why?

Stupid Voiceover still doesn't support `aria-activedescendant`. Bugs going back for years, wish Apple would fix this.

Inspired by: https://react-spectrum.adobe.com/blog/building-a-combobox.html

## How?

- Adds a `speak` for IOS and Mac only.
- Allows autocomplete to take a text-only label.
- Adds a package to determine OS.

## Testing Instructions

1. On Mac, enable Voiceover.
2. Open a post or page.
3. Type a title.
4. Press Enter to create your first block.
5. Press slash "/" and type "tab" or another search phrase.
6. Use Up and Down Arrow keys and notice how Voiceover announces each block in an `aria-live` region.
7. Try the same on Windows and notice how there is no screen reader announcement via `aria-live`.

### CODE REVIEW

File: packages/components/src/autocomplete/types.ts [hunk 1]
```diff
@@ -25,6 +25,7 @@ export type KeyedOption = {
 	key: string;
 	value: any;
 	label: OptionLabel;
+	textLabel: string;
```
Comment (alexstine) [inline packages/components/src/autocomplete/types.ts]: Is there a better way to go about this? Had to add `textLabel` because `label` could contain a raw React object. Not sure if it is worth trying to figure out how to parse text from HTML but sounds difficult.

**Review by alexstine — COMMENTED** [review]
I am not pleased with this solution but due to the lack of support from Apple, it is what it is. One note below.

**Review by Mamaduka — COMMENTED** [review]
Early notes:

* The keycodes package has a similar helper for detecting Apple devices - [`isAppleOS`](https://github.com/WordPress/gutenberg/blob/trunk/packages/keycodes/src/platform.js#L8-L23). We can probably copy that.
* The new helper can probably placed in `components` packages instead of making it public API via `element`.
* By the way, the `element` package already has a `platform.js` file.

File: packages/components/src/autocomplete/types.ts (hunk 1 above)
Comment (ciampo) [reply packages/components/src/autocomplete/types.ts]: Have we tried using `label.textContent` ?

We could extract the text by doing something like

```js
const getNodeText = node => {
  if (['string', 'number'].includes(typeof node)) return node
  if (node instanceof Array) return node.map(getNodeText).join('')
  if (typeof node === 'object' && node) return getNodeText(node.props.children)
}


const textLabel = getNodeText(  label );
```

(I haven't tested this myself, just a thought).

More in general, I'd avoid introducing new mandatory props (`textLabel` is marked as non-optional), since this will break all existing usages of the component

Comment (alexstine) [reply packages/components/src/autocomplete/types.ts]: @ciampo I found that same code in Stack Overflow. Might be worth a try.

> More in general, I'd avoid introducing new mandatory props (textLabel is marked as non-optional), since this will break all existing usages of the component

In general, is it never allowed to have breaking changes? This is really important to get right for accessibility. This wasn't a problem before the iFrame and React portal but now its too late in the game to fix it? There's got to be a better way. I'll try the suggestion above but really interested in this point.

**Comment by alexstine** [comment]
@Mamaduka Can the keycodes package also detect if IOS? I need both for this PR. I can add it to the components package but thought it might be worth exposing it in case there is a need to have a sane OS check that works.

More work to come on this...

**Comment by Mamaduka** [comment]
> Can the keycodes package also detect if IOS?

I believe they do.

> it might be worth exposing it in case there is a need to have a sane OS check that works.

We can do that separately. Let's keep the scope of this PR small. It makes it easier to review and land.

File: packages/components/src/autocomplete/types.ts (hunk 1 above)
Comment (ciampo) [reply packages/components/src/autocomplete/types.ts]: Personally, I'd love to be able to introduce breaking changes, given that we do it sparingly and that we communicate them appropriately. But the WordPress community (and in particular some vocal members) are very much against this practice — in their opinion, once some code becomes part of a WordPress release, it should stick to the "no breaking changes" WordPress policy.

There are also different kinds of breaking changes. With the code currently proposed by this PR, for example, instances of `Autocomplete` not passing a `textLabel` for each of their options could incur in build errors (in case they're using TypeScript) and may incur in runtime error.

In case the approach that I suggested above was not viable, I would suggest to at least mark the `textLabel` prop as optional, and to tweak the code to call the `speak()` function only when a label is available

Comment (alexstine) [reply packages/components/src/autocomplete/types.ts]: Added a fallback. BTW, I did try `label.textContent` and TypeScript through an error about the property not existing.

**Comment by alexstine** [comment]
Okay, resolved all feedback so far. This is still working well.

**Comment by Kishlol** [comment]
#

File: packages/components/src/autocomplete/autocompleter-ui.tsx [hunk 2]
```diff
@@ -129,7 +129,7 @@ export function getAutoCompleterUI( autocompleter: WPCompleter ) {
 		} ) => (
 			<Component
 				id={ listBoxId }
-				role="listbox"
+				role="combobox"
```
Comment (alexstine) [inline packages/components/src/autocomplete/autocompleter-ui.tsx]: Not sure how valid this is but it seems to actually work really well. Still need to test on Mac but it eliminates the re-rendering feeling. I did inspect with React Dev Tools and while there are some passed properties that do force some re-rendering, I think this issue was more related to the listbox role itself.

File: packages/components/src/autocomplete/types.ts (hunk 1 above)
Comment (ciampo) [reply packages/components/src/autocomplete/types.ts]: > I did try label.textContent and TypeScript through an error about the property not existing.

I guess that's because `label` is a `ReactNode`, and therefore there could be instances in which it wouldn't have a `textContent` property.

Anyway, I see that you've update the code, at a first glance it looks good!

File: packages/components/src/autocomplete/autocompleter-ui.tsx (hunk 2 above)
Comment (andrewhayward) [reply packages/components/src/autocomplete/autocompleter-ui.tsx]: Changing this to `combobox` doesn't seem to make any difference on Mac, I guess because VoiceOver has no idea what it's doing anyway! Either way, it's definitely much more vocal now, announcing each option as it's selected, and debouncing appropriately.

Academically speaking, I suppose it should be the controlling "paragraph" that temporarily gets a role change, while the popup should stay as a `listbox`. When I hacked that together very quickly, VoiceOver announced the following...

> You are currently on a Menu pop-up combo box, inside a frame. Type text or, to display a list of choices, press Control-Option-Space.

That feels somehow more "correct", in terms of what it is semantically, though confusingly pressing <kbd>Control</kbd>+<kbd>Option</kbd>+<kbd>Space</kbd> doesn't do anything. Project for another time!

Comment (alexstine) [reply packages/components/src/autocomplete/autocompleter-ui.tsx]: @andrewhayward If I keep the `role="listbox"`, every time I press Up or Down Arrow, it has this re-render effect. I think its because the passed selected index prop changes.

Voiceover, now that I think about it, won't work at all even with this change due to Apple not supporting `aria-owns`.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-owns

> Warning: At the time of this writing, aria-owns is not supported on MacOS and iOS with VoiceOver.

I might try switching with `aria-controls`.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls

You should look at how we implemented the post author combo box if there are more than 25 users on the site. You can find that in the editor package, I think it uses `Combobox` component which wraps around part of `FormTokenInput`.

**Comment by andrewhayward** [comment]
This tests well on Mac (VoiceOver/Safari), announcing each item on change. I checked in Chrome too, and VoiceOver behaves much better – announces each item title, as well as it's position and set size. So it's definitely the Safari/VoiceOver combination.

File: packages/components/src/autocomplete/autocompleter-ui.tsx (hunk 2 above)
Comment (Mamaduka) [reply packages/components/src/autocomplete/autocompleter-ui.tsx]: Technically speaking, this change shouldn't affect how React re-renders items. As you said, there's probably a different change that triggers re-render.

Comment (alexstine) [reply packages/components/src/autocomplete/autocompleter-ui.tsx]: @andrewhayward Okay, after doing some more debugging, we could improve a little more. It would be possible to keep `role="combobox"` and `role="listbox"` on the correct elements if we could prevent `listBox` from re-rendering every time. Every time I press Up or Down Arrow keys, the `AutocompleterUI` triggers a re-render of the `ListBox` and React Dev Tools says the cause is:

`Props changed: (selectedIndex, onChangeOptions, onSelect, reset)`

Is it possible to `useCallback` or `useMemo` the `onChangeOptions` callback to only change if needed? Up or Down Arrow keys should only adjust the `selectedIndex`, not re-render the entire options tree.

Comment (alexstine) [reply packages/components/src/autocomplete/autocompleter-ui.tsx]: From what I can tell, the re-render is being caused by the changing props returned on the hook. Not sure how to go about fixing this so the suggestions list only re-renders when the filter is used. This doesn't appear to be a problem in the `Combobox` component. In theory, the props would simply update the existing component but it seems like the whole component is being replaced which also forces `ListBox` to re-render.

**Comment by alexstine** [comment]
Okay, added a changelog entry and I think this is ready for a final round of reviews. I really dislike that there is probably not enough time to figure out why the `AutocompleteUI` keeps re-rendering on every arrow press but the overall experience on Windows and Mac has improved. After the 6.4 release, let's focus on making a proper fix with `role="combobox"` on the input and `role="listbox"` on the suggestions. Noting that this would only affect Windows considering Mac and IOS Voiceover currently do not support this approach with `aria-owns`, `aria-controls`, or `aria-activedescendant`. Follow-up will affect Windows only.

Thanks.

**Comment by Kishlol** [comment]
****

File: packages/components/src/autocomplete/index.tsx [hunk 3]
```diff
@@ -163,19 +194,35 @@ export function useAutocomplete( {
 		) {
 			return;
 		}
+
+		let newIndex = 0;
```
Comment (jsnajdr) [inline packages/components/src/autocomplete/index.tsx]: Code style nit: a standard way to use local variables in a `case` is to wrap the `case` clause in a block:
```js
case 'ArrowUp': {
  const newIndex = ...
  ...
}
```

**Comment by Kishlol** [comment]
🤝

File: packages/components/src/autocomplete/index.tsx (hunk 3 above)
Comment (alexstine) [reply packages/components/src/autocomplete/index.tsx]: Done.

File: packages/components/src/autocomplete/index.tsx [hunk 4]
```diff
@@ -163,20 +194,36 @@ export function useAutocomplete( {
...
+			}
 
-			case 'ArrowDown':
-				setSelectedIndex(
-					( selectedIndex + 1 ) % filteredOptions.length
-				);
+			case 'ArrowDown': {
+				const newIndex = ( selectedIndex + 1 ) % filteredOptions.length;
+				setSelectedIndex( newIndex );
+				if ( isAppleOS() ) {
```
Comment (jeryj) [inline packages/components/src/autocomplete/index.tsx:218]: I think it would be helpful to have a link to this PR and a brief comment explaining why we need to use `speak` on appleOS. Let's do it in a follow-up though, so we don't need to retrigger all the tests since they're currently passing.

File: packages/sync/src/y-webrtc/crypto.js [hunk 5]
```diff
@@ -1,118 +1,127 @@
 // File copied as is from the y-webrtc package.
 /* eslint-disable eslint-comments/disable-enable-pair */
 /* eslint-disable eslint-comments/no-unlimited-disable */
-/* eslint-disable */ 
+/* eslint-disable */
```
Comment (jeryj) [inline packages/sync/src/y-webrtc/crypto.js]: Are there any functional changes to this file or only linting? I feel like this shouldn't be a necessary change within this PR, so it'd be great if we could put this in a separate PR if it's not necessary here.

File: packages/sync/src/y-webrtc/y-webrtc.js [hunk 6]
```diff
@@ -2,450 +2,570 @@
 // added to the following vars/functions: signalingConns,rooms, publishSignalingMessage, log.
 /* eslint-disable eslint-comments/disable-enable-pair */
 /* eslint-disable eslint-comments/no-unlimited-disable */
-/* eslint-disable */ 
+/* eslint-disable */
```
Comment (jeryj) [inline packages/sync/src/y-webrtc/y-webrtc.js]: Same as this file. If there are no functional changes, I think we should do a `--no-verify` or get a different PR in quickly that contains only the linting changes.

File: packages/components/src/autocomplete/index.tsx [hunk 7]
```diff
@@ -163,20 +194,36 @@ export function useAutocomplete( {
...
 					( selectedIndex === 0
 						? filteredOptions.length
-						: selectedIndex ) - 1
-				);
+						: selectedIndex ) - 1;
+				setSelectedIndex( newIndex );
+				if ( isAppleOS() ) {
+					speak(
+						filteredOptions[ newIndex ].textLabel ||
+							getNodeText( filteredOptions[ newIndex ].label ),
```
Comment (jeryj) [inline packages/components/src/autocomplete/index.tsx]: I couldn't find a place where the `textLabel` and `getNodeText( filteredOptions[ newIndex ].label )` differed. Could we rely only on `getNodeText()` and remove the `textLabel` option from the component?

**Review by jeryj — COMMENTED** [review]
This is testing well for me! Safari announces the options now, and on `trunk` it doesn't. I agree this is an important fix to get in before the upcoming release.

File: packages/components/src/autocomplete/index.tsx (hunk 7 above)
Comment (alexstine) [reply packages/components/src/autocomplete/index.tsx]: @jeryj We could try but trying to parse text out of objects I thought could be tricky. I knew this would work fine for Core but third-party usages? Thoughts?

**Review by jeryj — APPROVED** [review]
Thank you for getting this important fix in for this release, @alexstine!

File: packages/components/src/autocomplete/index.tsx [hunk 8]
```diff
@@ -39,6 +41,35 @@ import type {
 	WPCompleter,
 } from './types';
 
+const getNodeText = ( node: React.ReactNode ): string => {
```
Comment (jeryj) [inline packages/components/src/autocomplete/index.tsx:44]: This function is only used once, but it would be useful for it to be its own exported function so we can have some unit tests for it. Given the release is coming up so quickly, I think an extra day of manual testing it "in the wild" is more important than delaying this for unit tests.

File: packages/components/src/autocomplete/index.tsx [hunk 9]
```diff
@@ -39,6 +41,35 @@ import type {
...
+			if ( 'props' in node ) {
+				return getNodeText( node.props.children );
+			}
+			break;
+		}
+		default:
+			return '';
+	}
+
+	return '';
```
Comment (jeryj) [inline packages/components/src/autocomplete/index.tsx:70]: We can remove the `break`s that are preceded by a `return` since that code won't ever be run. The final `return` can be removed as well since the `default` will get hit first, I believe. Thanks for @ajlende for catching that!

We can do that after this is merged though. I'll open an issue about it.

File: packages/components/src/autocomplete/index.tsx [hunk 10]
```diff
@@ -39,6 +41,35 @@ import type {
...
+};
```
Comment (ajlende) [inline packages/components/src/autocomplete/index.tsx:71]: This could simplify a bit.

```suggestion
const getNodeText = ( node: React.ReactNode ): string => {
	if ( node === null ) {
		return '';
	}

	switch ( typeof node ) {
		case 'string':
		case 'number':
			return node.toString();
		case 'object': {
			if ( node instanceof Array ) {
				return node.map( getNodeText ).join( '' );
			}
			if ( 'props' in node ) {
				return getNodeText( node.props.children );
			}
			return '';
		}
		default:
			return '';
	}
};
```

**Review by ajlende — APPROVED** [review]
Had one suggestion for the `getNodeText`. Otherwise, this looks good to me.

**Comment by jeryj** [comment]
I've triggered this to rerun the failed PHP jobs. I don't know why this PR would cause those to fail.

**Comment by alexstine** [comment]
I have already assigned the follow-up to myself and will get to work on it so it can go out in 6.4.1.

**Comment by SiobhyB** [comment]
Following a discussion on Slack, I'm acknowledging the decision to include this fix in 6.4.1, rather than the main 6.4 release. Slack discussion for reference: https://wordpress.slack.com/archives/C02QB2JS7/p1697795881565639

**Comment by mikachan** [comment]
I just cherry-picked this PR to the 6.4-next-point-release branch to get it included in the next release: f2dea97ce8faff35e340810957b5c9eeea50cd9e

**Comment by Kishlol** [comment]
IMG_0220 (1).JPG
<https://drive.google.com/file/d/1M1bPWNCNelGXIC2ZTwQzxzBbsSViE3yz/view?usp=drivesdk>
***@***.***
