### PR TITLE
`Modal`: fix closing when contained iframe is focused

### LINKED ISSUE #40912: Components: Clicking on iframe in the content close the modal
### Description

I'm trying to load a tinymce editor in a gutenberg modal. I'm using the oficial component: https://github.com/tinymce/tinymce-react#readme

The component load correctly the editor, however clicking or typing something will close the modal.

### Step-by-step reproduction instructions

1. Create a custom component as the one presented here: https://www.tiny.cloud/docs/integrations/react/
2. Create a simple basic modal and put the component there
3. Try to type some texts

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by stokesman**
## What?
Fix for a bug in `Modal` it closes when a contained iframe is focused.

## Why?
It seems like iframes in modals should be supported.
to fix: #40912

## How?
Uses an event handler on the Modal’s overlay element to trigger the closing instead of the `useFocusOutside` hook.

## Testing Instructions
1. Visit the Modal story in Storybook.
2. Open the modal.
3. Verify that clicking/focusing the contained iframe does not close the modal.
4. Verify that clicking outside the modal closes the modal.

### CODE REVIEW

**Review by chad1008 — COMMENTED** [review]
This looks good and tests well for me. I'll let @ciampo/@mirka take a look and provide an approval though, to get more eyeballs.

**Review by ciampo — COMMENTED** [review]
This is testing well for me, although I'd like to also hear @alexstine and @t-hamano 's opinion.

I wish we could find a solution that involves improving the `useFocusOutside` hook, since it's used in a few places across Gutenberg that will likely face the same issue as the `Modal` component when an `iframe` is rendered.

Also noting that, while focus is inside the iframe, pressing the Escape key won't close the Modal (although I guess that is expected and would kind of fall on the consumer of `Modal` to decide what to do with keyboard events and `iframe`s)


> I'll let @ ciampo/ @ lena

I guess you meant @mirka  😄

**Comment by alexstine** [comment]
It's in my queue. Waiting for green tests first.

**Comment by chad1008** [comment]
> I guess you meant @mirka

Yep. Edited... sorry for the mis-ping 🤦

**Comment by stokesman** [comment]
Thanks for testing this out Chad and Marco. 🙇 

> I wish we could find a solution that involves improving the `useFocusOutside` hook

Agreed. My efforts in that direction haven’t come to fruition and I figured this should be simple enough that it's worth doing for the time being. 

> Waiting for green tests first.

👍 😁. There’s some e2e tests that are consistently failing here and so far it’s a head-scratcher. I’d just started to manually run those tests when I noticed the focus return behavior of the modal wasn’t working. I found a fix and pushed bf431ed hoping that would be it but no luck. That’s apparently an existing bug in trunk so I just made #51722 for it. I'll keep looking into these tests and meanwhile kick this back into draft mode.

**Comment by t-hamano** [comment]
Thanks for the PR, @stokesman!

This PR looks good to me, including the test, but I still don't know what caused #51722 😅

Furthermore, and this may be a future improvement, if it were possible to close the modal by clicking on the overlay, it would mean that it would be possible to determine which key on the mouse was pressed. In other words, it is possible to prevent the modal from closing when it is not the primary key.

There is no correct answer for this, but the behavior of other libraries seems to be as follows:

- [react-modal](https://codesandbox.io/s/vigorous-carson-6grq7f?file=/src/index.js:606-620) (This is a sample of my code sandbox): Modal will not close if it is not the primary key
- [micromodal](https://micromodal.vercel.app/): Modal will not close if it is not the primary key
- [Ariakit Dialog](https://ariakit.org/components/dialog): Modal close when auxiliary key is pressed

https://github.com/WordPress/gutenberg/assets/54422211/db64a5c0-665c-4b21-9790-3046bc866646

**Comment by stokesman** [comment]
Thanks for taking a look @t-hamano. I appreciate the suggestion to consider the behavior for a non-primary key too. I'd be in favor of not closing the modal then.

Back to the tests that are failing here. They are all related to #51737 which this branch happens to escalate. On this branch, the Command Center modal stays open. On trunk, it only flickers open for an instant before closing. In such a situation one might think `Modal` with `useFocusOutside` has an advantage but this case is a poor example because the situation isn't intentional (and is still a UX issue). It does raise the question of whether there could be a use case for programmatically moving the focus outside of a modal and expecting that to dismiss it but I'd call YAGNI.

So I think the only two options that would unblock this are:
- Change the global shortcut for the Command Center to something that doesn't conflict with the one for adding links.
- Pull in [these changes](https://github.com/WordPress/gutenberg/compare/try/terminate-event-at-link-shortcuts) to avoid triggering the Command Center when the shortcut for links is used.

**Comment by ciampo** [comment]
Testing an alternative solution that only applies changes to `useFocusOutside` in https://github.com/WordPress/gutenberg/pull/52040 — let's see how it goes.

**Comment by stokesman** [comment]
This is unblocked since #53001. I've rebased this and changes are reduced because #52653 incorporated some of what was originally done here.

What is most novel in these changes now is df1e700. The only case `useFocusOutside` was actually supporting since #52653 was the closing of one modal when another opened. So with the hook removed these changes maintain that behavior. I had missed this previously and we don’t have a test for it.

**Comment by afercia** [comment]
@ciampo @stokesman I do remember there were good reasons why a 'focus outside' approach was used instead of a simpler click handler on the overlay. Right now I can't recall what the specific reason for that approach was, but I'm pretty sure there was one :)

@aduth or @youknowriad may know more, otherwise I'd suggest a little research in the history of this project to better understand why a 'on focus outside' approach is preferred.

**Comment by ciampo** [comment]
> otherwise I'd suggest a little research in the history of this project to better understand why a 'on focus outside' approach is preferred.

Found https://github.com/WordPress/gutenberg/pull/16878 where the switch happened from click-based to focus-based checks.

File: packages/components/src/modal/index.tsx [hunk 1]
```diff
@@ -106,7 +105,10 @@ function UnforwardedModal(
 		if ( openModalCount === 1 ) {
 			ariaHelper.hideApp( ref.current );
 			document.body.classList.add( bodyOpenClassName );
+		} else if ( openModalCount > 1 ) {
+			dismissOpenModal();
```
Comment (ciampo) [inline packages/components/src/modal/index.tsx]: > The only case useFocusOutside was actually supporting since https://github.com/WordPress/gutenberg/pull/52653 was the closing of one modal when another opened. So with the hook removed these changes maintain that behavior. I had missed this previously and we don’t have a test for it.

I tried to add code to test opening a modal inside a modal, and this PR instantly closes the new modal as described in the quoted text.

<details>
<summary>See code diff</summary>

```diff
diff --git a/packages/components/src/modal/stories/index.story.tsx b/packages/components/src/modal/stories/index.story.tsx
index 6963026963..6697d65346 100644
--- a/packages/components/src/modal/stories/index.story.tsx
+++ b/packages/components/src/modal/stories/index.story.tsx
@@ -48,11 +48,17 @@ export default meta;
 
 const Template: StoryFn< typeof Modal > = ( { onRequestClose, ...args } ) => {
 	const [ isOpen, setOpen ] = useState( false );
+	const [ isOpenTwo, setOpenTwo ] = useState( false );
 	const openModal = () => setOpen( true );
+	const openModalTwo = () => setOpenTwo( true );
 	const closeModal: ModalProps[ 'onRequestClose' ] = ( event ) => {
 		setOpen( false );
 		onRequestClose( event );
 	};
+	const closeModalTwo: ModalProps[ 'onRequestClose' ] = ( event ) => {
+		setOpenTwo( false );
+		onRequestClose( event );
+	};
 
 	return (
 		<>
@@ -86,9 +92,29 @@ const Template: StoryFn< typeof Modal > = ( { onRequestClose, ...args } ) => {
 						src="https://www.openstreetmap.org/export/embed.html?bbox=-0.004017949104309083%2C51.47612752641776%2C0.00030577182769775396%2C51.478569861898606&layer=mapnik"
 					/>
 
+					<Button variant="secondary" onClick={ openModalTwo }>
+						Open Modal two
+					</Button>
+
 					<Button variant="secondary" onClick={ closeModal }>
 						Close Modal
 					</Button>
+
+					{ isOpenTwo && (
+						<Modal
+							onRequestClose={ closeModalTwo }
+							style={ { maxWidth: '600px' } }
+							{ ...args }
+						>
+							Two!
+							<Button
+								variant="secondary"
+								onClick={ closeModalTwo }
+							>
+								Close Modal
+							</Button>
+						</Modal>
+					) }
 				</Modal>
 			) }
 		</>

```

</details>

But then I tried the same code diff on `trunk`, and I was able to open a nested modal (ie. neither the "old" modal, nor the new modal closed).

What is the correct expected behaviour? Is trunk currently experiencing a regression?

File: packages/components/src/modal/index.tsx [hunk 2]
```diff
@@ -177,12 +179,9 @@ function UnforwardedModal(
 		onPointerUp: React.PointerEventHandler< HTMLDivElement >;
 	} = {
 		onPointerDown: ( event ) => {
-			if ( event.isPrimary && event.target === event.currentTarget ) {
+			if ( event.target === event.currentTarget ) {
```
Comment (ciampo) [inline packages/components/src/modal/index.tsx:239]: Why is the `isPrimary` check being removed, after it was added recently in #52994?

**Comment by stokesman** [comment]
I’ve looked into it before https://github.com/WordPress/gutenberg/pull/52653#issuecomment-1646362071. At first, both Modals and Popovers used a click-based approach. As evidenced by #14851, this was problematic for Popovers (which lack an overlay element). I think the decision to also change the approach for Modals was mostly for the opportunity to eliminate an external dependency (per the description of #16878) and not because of any actual issue.

File: packages/components/src/modal/index.tsx (hunk 1 above)
Comment (stokesman) [reply packages/components/src/modal/index.tsx]: The expected behavior is that only a single modal can be open at any time. I don't think trunk is experiencing a regression as I've not been able to reproduce it (testing in WP, by launching other modals with command palette). Perhaps there was a build hiccup when you were testing? I can test more soon though.

File: packages/components/src/modal/index.tsx (hunk 2 above)
Comment (stokesman) [reply packages/components/src/modal/index.tsx:239]: Oh I meant to remove that in dbed083 from that PR but goofed and only removed it from the `pointerup`. More context https://github.com/WordPress/gutenberg/pull/52994#issuecomment-1675241542
>I'd been supposing it might be a good to cover a case on multi input devices (think touch screen laptop with mouse) but I think that’s over doing it and I don’t have a device like that for testing anyway.

File: packages/components/src/modal/index.tsx (hunk 1 above)
Comment (stokesman) [reply packages/components/src/modal/index.tsx]: I've tested more and trunk seems fine. I get one modal open at a time. Granted I don't see evidence that the behavior was by design it's just how it is (probably since #16878).

Comment (t-hamano) [reply packages/components/src/modal/index.tsx]: As far as I've tested, only one modal is always displayed, both in trunk and in this PR. Probably there is a difference between trunk and this PR when Modal components are nested?

https://github.com/WordPress/gutenberg/assets/54422211/ec05dc2d-bd79-406c-ab22-a46d1be9e688

Comment (ciampo) [reply packages/components/src/modal/index.tsx]: That's weird — there must be something unusual going on.

I pulled latest `trunk`, re-installed dependencies, ran `npm run storybook:dev` and made changes to the `Modal` story as follows:

<details>

<summary>Click to expand</summary>

```diff
diff --git a/packages/components/src/modal/stories/index.story.tsx b/packages/components/src/modal/stories/index.story.tsx
index 8405a6eb01..62aedfee8f 100644
--- a/packages/components/src/modal/stories/index.story.tsx
+++ b/packages/components/src/modal/stories/index.story.tsx
@@ -47,21 +47,28 @@ const meta: Meta< typeof Modal > = {
 export default meta;
 
 const Template: StoryFn< typeof Modal > = ( { onRequestClose, ...args } ) => {
-	const [ isOpen, setOpen ] = useState( false );
-	const openModal = () => setOpen( true );
-	const closeModal: ModalProps[ 'onRequestClose' ] = ( event ) => {
-		setOpen( false );
+	const [ isOuterOpen, setOuterOpen ] = useState( false );
+	const openOuterModal = () => setOuterOpen( true );
+	const closeOuterModal: ModalProps[ 'onRequestClose' ] = ( event ) => {
+		setOuterOpen( false );
+		onRequestClose( event );
+	};
+
+	const [ isInnerOpen, setInnerOpen ] = useState( false );
+	const openInnerModal = () => setInnerOpen( true );
+	const closeInnerModal: ModalProps[ 'onRequestClose' ] = ( event ) => {
+		setInnerOpen( false );
 		onRequestClose( event );
 	};
 
 	return (
 		<>
-			<Button variant="secondary" onClick={ openModal }>
-				Open Modal
+			<Button variant="secondary" onClick={ openOuterModal }>
+				Open Outer Modal
 			</Button>
-			{ isOpen && (
+			{ isOuterOpen && (
 				<Modal
-					onRequestClose={ closeModal }
+					onRequestClose={ closeOuterModal }
 					style={ { maxWidth: '600px' } }
 					{ ...args }
 				>
@@ -79,9 +86,32 @@ const Template: StoryFn< typeof Modal > = ( { onRequestClose, ...args } ) => {
 
 					<InputControl style={ { marginBottom: '20px' } } />
 
-					<Button variant="secondary" onClick={ closeModal }>
+					<Button variant="secondary" onClick={ openInnerModal }>
+						Open Inner Modal
+					</Button>
+
+					<Button variant="secondary" onClick={ closeOuterModal }>
 						Close Modal
 					</Button>
+
+					{ isInnerOpen && (
+						<Modal
+							onRequestClose={ closeInnerModal }
+							style={ { maxWidth: '600px' } }
+							{ ...args }
+						>
+							<p>Inner</p>
+
+							<InputControl style={ { marginBottom: '20px' } } />
+
+							<Button
+								variant="secondary"
+								onClick={ closeInnerModal }
+							>
+								Close Modal
+							</Button>
+						</Modal>
+					) }
 				</Modal>
 			) }
 		</>

```
</details>

This is what I see on my local machine:

https://github.com/WordPress/gutenberg/assets/1083581/3f91b8a4-9060-4687-a90f-87d6da6fc9e3


This behaviour would make sense to me considering that the nested modal is still within the outer modal, which means that technically the focus doesn't move outside and doesn't trigger the `onFocusOutside` callback

Comment (stokesman) [reply packages/components/src/modal/index.tsx]: My bad. I missed that your example was nested (the first diff wasn't applying for me). I've tested with your latest diff applied and see the same thing as you. I think the behavior makes sense yet I wondered since when has it been like that. ~~I had my suspicions it's since #52653 and that seems to be the case. So I think the behavior would be worth preserving but it does appear to be a recent incidental "enhancement".~~ Oops, I somehow got focused on how it behaves when clicking outside 🤦‍♂️ and that's a minor point compared to the fact that at least the nesting is possible.

<details><summary>A diff reverting Modal to before #52653</summary>

```diff
diff --git a/packages/components/src/modal/index.tsx b/packages/components/src/modal/index.tsx
index d21a3f9ae3..3a630eed11 100644
--- a/packages/components/src/modal/index.tsx
+++ b/packages/components/src/modal/index.tsx
@@ -171,34 +171,6 @@ function UnforwardedModal(
 		[ hasScrolledContent ]
 	);
 
-	let pressTarget: EventTarget | null = null;
-	const overlayPressHandlers: {
-		onPointerDown: React.PointerEventHandler< HTMLDivElement >;
-		onPointerUp: React.PointerEventHandler< HTMLDivElement >;
-	} = {
-		onPointerDown: ( event ) => {
-			if ( event.isPrimary && event.target === event.currentTarget ) {
-				pressTarget = event.target;
-				// Avoids loss of focus yet also leaves `useFocusOutside`
-				// practically useless with its only potential trigger being
-				// programmatic focus movement. TODO opt for either removing
-				// the hook or enhancing it such that this isn't needed.
-				event.preventDefault();
-			}
-		},
-		// Closes the modal with two exceptions. 1. Opening the context menu on
-		// the overlay. 2. Pressing on the overlay then dragging the pointer
-		// over the modal and releasing. Due to the modal being a child of the
-		// overlay, such a gesture is a `click` on the overlay and cannot be
-		// excepted by a `click` handler. Thus the tactic of handling
-		// `pointerup` and comparing its target to that of the `pointerdown`.
-		onPointerUp: ( { target, button } ) => {
-			const isSameTarget = target === pressTarget;
-			pressTarget = null;
-			if ( button === 0 && isSameTarget ) onRequestClose();
-		},
-	};
-
 	return createPortal(
 		// eslint-disable-next-line jsx-a11y/no-static-element-interactions
 		<div
@@ -208,7 +180,6 @@ function UnforwardedModal(
 				overlayClassName
 			) }
 			onKeyDown={ handleEscapeKeyDown }
-			{ ...( shouldCloseOnClickOutside ? overlayPressHandlers : {} ) }
 		>
 			<StyleProvider document={ document }>
 				<div

```
</details>

I've yet to determine how hard it would be to support this use case with the approach in this PR.

Comment (ciampo) [reply packages/components/src/modal/index.tsx]: Yeah, I guess that the key aspect of this is to understand the desired behaviour, and if indeed the recent changes introduced a regression around it. I will also try to look into it a bit better in the upcoming days

Comment (stokesman) [reply packages/components/src/modal/index.tsx]: I think it probably is the desired behavior regardless of whether there are existing use cases. Also, my comment above was a bit misleading as I now think Modal probably has supported nesting since its inception.

Comment (ciampo) [reply packages/components/src/modal/index.tsx]: I came to the same conclusion, ie. that **we should support nested modals**

> I've yet to determine how hard it would be to support this use case with the approach in this PR.

Let me know how that goes, hopefully it's not too complicated 🤞

Comment (t-hamano) [reply packages/components/src/modal/index.tsx]: Does supporting nested modals mean closing the outer modal when the inner modal is opened?

I'm wondering if that's possible. This is because the inner modal is rendered within the outer modal, so if the outer modal disappears (is unmounted), the inner modal must also disappear as a result 🤔

Comment (stokesman) [reply packages/components/src/modal/index.tsx]: Yes, Aki, I believe you're right. There might be some way to visually hide the outer one but it certainly couldn't unmount or else the inner one goes too.

I did find a way to support the nesting that doesn't seem too complicated but I have to focus on some other stuff for a bit and I'll push it later.

Comment (ciampo) [reply packages/components/src/modal/index.tsx]: My expectation would be that, when the inner modal is opened, the outer modal stays open in the background.

Clicking on the backdrop / pressing ESC at this point would close the inner modal, but leave the outer modal visible.

> Does supporting nested modals mean closing the outer modal when the inner modal is opened?

Doing so would mean that two modals can't be open at a time, which basically would mean that nested modals are not really supported?

Comment (stokesman) [reply packages/components/src/modal/index.tsx]: I pushed some changes and now this supports nested modals more completely than trunk. I say more completely because while working on this I realized a nested modal doesn't accessibly hide the outer modal that launched it. Probably not a big deal because who is actually using nested modals? Still, technically I think it's the right thing to do.

Here’s a demo:

https://github.com/WordPress/gutenberg/assets/9000376/892b2398-c0de-436f-8476-4d60eb0e5c55

And of course…

<details><summary>A diff to add the story I tested with</summary>

```diff
diff --git a/packages/components/src/modal/stories/index.story.tsx b/packages/components/src/modal/stories/index.story.tsx
index 6963026963..be36e1fb6f 100644
--- a/packages/components/src/modal/stories/index.story.tsx
+++ b/packages/components/src/modal/stories/index.story.tsx
@@ -6,7 +6,7 @@ import type { StoryFn, Meta } from '@storybook/react';
 /**
  * WordPress dependencies
  */
-import { useState } from '@wordpress/element';
+import { createContext, useContext, useState } from '@wordpress/element';
 import { starEmpty, starFilled } from '@wordpress/icons';
 
 /**
@@ -127,3 +127,117 @@ WithHeaderActions.args = {
 WithHeaderActions.parameters = {
 	...Default.parameters,
 };
+
+const Cue: React.FC< {
+	children: React.ReactNode;
+	not?: boolean;
+	of: React.Dispatch< React.SetStateAction< boolean > >;
+} > = ( { children, not, of } ) => (
+	<Button variant="secondary" onClick={ () => of( ! not ) }>
+		{ children }
+	</Button>
+);
+
+const depth = createContext( 0 );
+
+const ModalWithDepth: React.FC< Parameters< typeof Template >[ 0 ] > = ( {
+	children,
+	...args
+} ) => {
+	const localDepth = useContext( depth );
+	return (
+		<depth.Provider value={ localDepth + 1 }>
+			<Modal
+				style={ { maxWidth: '600px' } }
+				{ ...args }
+				title={ `Depth ${ localDepth }: ${ args.title }` }
+			>
+				{ children }
+			</Modal>
+		</depth.Provider>
+	);
+};
+
+const Recursive: React.FC< Parameters< typeof Template >[ 0 ] > = ( args ) => {
+	const [ isOuterOpen, setOuterOpen ] = useState( false );
+	const [ isInnerOpen, setInnerOpen ] = useState( false );
+	const [ isAdjacentOpen, setAdjacentOpen ] = useState( false );
+
+	const localDepth = useContext( depth );
+
+	return (
+		<>
+			<Cue of={ setOuterOpen }>
+				{ localDepth === 0 ? 'Inception' : `🪆 ${ localDepth }` }
+			</Cue>
+			{ isOuterOpen && (
+				<ModalWithDepth
+					style={ { maxWidth: '600px' } }
+					{ ...args }
+					onRequestClose={ ( event ) => {
+						setInnerOpen( false );
+						setOuterOpen( false );
+						args.onRequestClose( event );
+					} }
+				>
+					<p>
+						Lorem ipsum dolor sit amet, consectetur adipiscing elit,
+						sed do eiusmod tempor incididunt ut labore et magna
+						aliqua. Ut enim ad minim veniam, quis nostrud
+						exercitation ullamco laboris nisi ut aliquip ex ea ea
+						commodo consequat. Duis aute irure dolor in
+						reprehenderit in voluptate velit esse cillum dolore eu
+						fugiat nulla pariatur. Excepteur sint occaecat cupidatat
+						non proident, sunt in culpa qui noticia deserunt mollit
+						anim id est laborum.
+					</p>
+
+					<InputControl style={ { marginBottom: '20px' } } />
+
+					<Cue of={ setInnerOpen }>🪆 { localDepth + 1 }</Cue>
+
+					<Cue of={ setAdjacentOpen }>➡️ Adjacent</Cue>
+
+					{ isInnerOpen && (
+						<ModalWithDepth
+							{ ...args }
+							onRequestClose={ () => {
+								setInnerOpen( false );
+								args.onRequestClose();
+							} }
+						>
+							<Recursive { ...args } />
+
+							<Cue of={ setAdjacentOpen }>
+								↖️ Adjacent to outer
+							</Cue>
+						</ModalWithDepth>
+					) }
+				</ModalWithDepth>
+			) }
+			{ isAdjacentOpen && (
+				<Modal
+					style={ { maxWidth: '500px' } }
+					{ ...args }
+					onRequestClose={ ( event ) => {
+						setAdjacentOpen( false );
+						args.onRequestClose( event );
+					} }
+					title={ `Depth ${ localDepth } adjacent: ${ args.title }` }
+				>
+					<p>
+						Lorem ipsum dolor sit amet, consectetur adipiscing elit,
+						sed do eiusmod tempor incididunt ut labore et magna
+						aliqua. Ut enim ad minim veniam, quis nostrud.
+					</p>
+				</Modal>
+			) }
+		</>
+	);
+};
+
+export const Recursion: StoryFn< typeof Modal > = ( args ) => (
+	<Recursive { ...args } />
+);
+Recursion.args = Default.args;
+Recursion.parameters = Default.parameters;

```
</details>

**Comment by stokesman** [comment]
To recap, in exploring this PR we've uncovered three behaviors we don't currently test for that we might want to:
1. Opening a modal causes other (non-nested) modals to close
2. Modals can nest
3. Nested modals accessibly hide their parent modal

Trunk would pass the first two but not the third and this PR should pass all three. I'd guess these can all be covered with unit tests but I'm not sure. Because the issue this PR sought to resolve has a workaround I suppose creating such tests could take priority over getting a fix merged. What do you think @ciampo?

File: packages/components/src/modal/aria-helper.ts
Comment (stokesman) [inline packages/components/src/modal/aria-helper.ts:1]: It’s not important to rename  `hideApp` and `showApp` but those names didn’t seem to fit well when it comes to nested modals which aren't hiding/showing the whole set of siblings.

**Comment by ciampo** [comment]
Gave a quick try in Storybook and so far it tests well as per the latest specs.

<details>

<summary>storybook diff</summary>

```diff
diff --git a/packages/components/src/modal/stories/index.story.tsx b/packages/components/src/modal/stories/index.story.tsx
index 8405a6eb01..e6fc36c64d 100644
--- a/packages/components/src/modal/stories/index.story.tsx
+++ b/packages/components/src/modal/stories/index.story.tsx
@@ -47,21 +47,35 @@ const meta: Meta< typeof Modal > = {
 export default meta;
 
 const Template: StoryFn< typeof Modal > = ( { onRequestClose, ...args } ) => {
-	const [ isOpen, setOpen ] = useState( false );
-	const openModal = () => setOpen( true );
-	const closeModal: ModalProps[ 'onRequestClose' ] = ( event ) => {
-		setOpen( false );
+	const [ isOuterOpen, setOuterOpen ] = useState( false );
+	const openOuterModal = () => setOuterOpen( true );
+	const closeOuterModal: ModalProps[ 'onRequestClose' ] = ( event ) => {
+		setOuterOpen( false );
+		onRequestClose( event );
+	};
+
+	const [ isInnerOpen, setInnerOpen ] = useState( false );
+	const openInnerModal = () => setInnerOpen( true );
+	const closeInnerModal: ModalProps[ 'onRequestClose' ] = ( event ) => {
+		setInnerOpen( false );
+		onRequestClose( event );
+	};
+
+	const [ isOtherOpen, setOtherOpen ] = useState( false );
+	const openOtherModal = () => setOtherOpen( true );
+	const closeOtherModal: ModalProps[ 'onRequestClose' ] = ( event ) => {
+		setOtherOpen( false );
 		onRequestClose( event );
 	};
 
 	return (
 		<>
-			<Button variant="secondary" onClick={ openModal }>
-				Open Modal
+			<Button variant="secondary" onClick={ openOuterModal }>
+				Open Outer Modal
 			</Button>
-			{ isOpen && (
+			{ isOuterOpen && (
 				<Modal
-					onRequestClose={ closeModal }
+					onRequestClose={ closeOuterModal }
 					style={ { maxWidth: '600px' } }
 					{ ...args }
 				>
@@ -79,7 +93,49 @@ const Template: StoryFn< typeof Modal > = ( { onRequestClose, ...args } ) => {
 
 					<InputControl style={ { marginBottom: '20px' } } />
 
-					<Button variant="secondary" onClick={ closeModal }>
+					<Button variant="secondary" onClick={ openOtherModal }>
+						Open Other Modal
+					</Button>
+
+					<Button variant="secondary" onClick={ openInnerModal }>
+						Open Inner Modal
+					</Button>
+
+					<Button variant="secondary" onClick={ closeOuterModal }>
+						Close Modal
+					</Button>
+
+					{ isInnerOpen && (
+						<Modal
+							onRequestClose={ closeInnerModal }
+							style={ { maxWidth: '600px' } }
+							{ ...args }
+						>
+							<p>Inner</p>
+
+							<InputControl style={ { marginBottom: '20px' } } />
+
+							<Button
+								variant="secondary"
+								onClick={ closeInnerModal }
+							>
+								Close Modal
+							</Button>
+						</Modal>
+					) }
+				</Modal>
+			) }
+			{ isOtherOpen && (
+				<Modal
+					onRequestClose={ closeOtherModal }
+					style={ { maxWidth: '600px' } }
+					{ ...args }
+				>
+					<p>Other</p>
+
+					<InputControl style={ { marginBottom: '20px' } } />
+
+					<Button variant="secondary" onClick={ closeOtherModal }>
 						Close Modal
 					</Button>
 				</Modal>


```

</details>

> Trunk would pass the first two but not the third and this PR should pass all three. I'd guess these can all be covered with unit tests but I'm not sure. Because the issue this PR sought to resolve has a workaround I suppose creating such tests could take priority over getting a fix merged. What do you think @ciampo?

Sounds like a good plan:

1. Open a new PR that adds unit tests for all 3 usecases. We make sure that the last test fails on trunk (nested modals hiding accessibly their parent), and we disable it for the sake of that PR.
2. Once that PR is merged, we rebase this PR and make sure that all tests pass

Sounds like a plan? @stokesman can you also work on the separate PR adding unit tests? I guess it could also embed the refactor to user-event that is currently part of this PR.

**Comment by stokesman** [comment]
> can you also work on the separate PR adding unit tests? I guess it could also embed the refactor to user-event that is currently part of this PR.

See #54569

**Comment by stokesman** [comment]
To keep this PR focused, I extracted the changes for improving a11y isolation into #54743. I haven't pushed to this PR again yet. I'd prefer to land that one first because I think the other way around would make both a little less clean. There'd be little conditions introduced here to maintain current behavior that then could be removed in the other.

I've also discovered `Modal` has yet more poorly specified behavior. This time in regards to `bodyOpenClassName` but addressing it can probably be done after the fate of this PR is decided.

**Comment by afercia** [comment]
Late to teh party. I quickly scenned the discussion and I'm not sure I'm fully understandint the nested modal dialogs issue. IN any case, a modal dialog should never be rendered inside another modal dialog in the DOM. They elements with role=dialog must be separated and _not nsted_.

The ARIA Authoring Practices Guide design patterns show an example of multiple modal dialogs:
https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/

The behavior is different depending on the user flow:
- Click Add Delivery Address > Add
  - The first dialog closes.
  - Makes sense because the intereaction flow is complete.
- Click Add Delivery Address > Verify Address > accepting an alternative form
  - The first and second dialogs stay open.
  - Makes sense because the intereaction flow is not complete yet: the two additional dialogs are intermediary steps users can take to complete the main task.

I'd recommend to follow that pattern and provide the option to close or keep the 'opener' modal dialog open.

**Comment by afercia** [comment]
@priethor as an example related to our conversation about labels: I added the accessibility label to this PR and now the related check is failing. This is less than ideal.

This PR *must* ba marked with the accessibility lable to let the accessibility team and any otehr accessiblity specialist be able to follow, contriute, review. Also for history, to make easier retrieve this PR in the future.
Thanks.

**Comment by stokesman** [comment]
> IN any case, a modal dialog should never be rendered inside another modal dialog in the DOM.

The nesting mentioned here is in the context of the React tree. In the DOM they are siblings.

> I'd recommend to follow that pattern and provide the option to close or keep the 'opener' modal dialog open

Thanks for the example. The "opener" modal dialog will remain open.

> This PR _must_ ba marked with the accessibility lable

I am not sure it _must_ be. I extracted those a11y changes into #54743. They won't be included here and the single thing this PR will do is ensure that focus moving within an iframe inside the dialog will not cause the dialog to close. Does that still merit the label? Anyway, as an example for the "type" labeling discussion, your comment is valid and could apply to #54743, I didn't label that a bug because I didn't want the check to fail.

**Comment by afercia** [comment]
> I am not sure it _must_ be. I extracted those a11y changes into #54743. They won't be included here and the single thing this PR will do is ensure that focus moving within an iframe inside the dialog will not cause the dialog to close. Does that still merit the label?

Yes it does:
1. We want to easily retrieve and follow all accessibility related issues and PRs, and this PR touches important accessibility features.
2. For history and statistics: in the future we may want to retrieve how many accessibility focus related issues occurred and how many have been fixed.

File: packages/components/src/modal/index.tsx (hunk 1 above)
Comment (stokesman) [reply packages/components/src/modal/index.tsx]: Since #54569 and #54743 we have unit tests covering this so I'll mark this as resolved.

**Comment by priethor** [comment]
> PR touches important accessibility features.

The way it's framed sounds like a11y should be treated as a Focus, not a Type of label. I've opened [a PR to address this](https://github.com/WordPress/gutenberg/pull/54941).

File: packages/components/src/modal/index.tsx [hunk 3]
```diff
@@ -36,8 +42,13 @@ import Button from '../button';
 import StyleProvider from '../style-provider';
 import type { ModalProps } from './types';
 
-// Used to count the number of open modals.
-let openModalCount = 0;
+// Used to track and dismiss the prior modal when another opens unless nested.
+const level0Dismissers: MutableRefObject<
+	ModalProps[ 'onRequestClose' ] | undefined
+>[] = [];
+const context = createContext( level0Dismissers );
```
Comment (ciampo) [inline packages/components/src/modal/index.tsx]: Nit: let's capitalize the variable, and give it a more meaningful name (this better aligns with naming conventions and can help while debugging code in React Dev Tools)

File: packages/components/src/modal/stories/index.story.tsx
Comment (ciampo) [inline packages/components/src/modal/stories/index.story.tsx:1]: Let's remove the `iframe` from the Storybook example before merging.

**Review by ciampo — APPROVED** [review]
Overall the changes test well - unit tests are passing, the storybook iframe example is working well!

One thing that could be done, though, is to add some extra inline comments explaining the logic behind `dismissers`, `level0Dismissers`, `nestedDismissers` and the recursion via the context. To a developer with no context on these changes, it may take a while to understand what it going on.

Finally, we'll also need to add a CHANGELOG entry (I guess under the "Big Fix" section, since this is a fix for #40912 ?

I'm going to preemptively approve this PR, we can merge once all feedback is addressed

File: packages/components/src/modal/stories/index.story.tsx
Comment (stokesman) [reply packages/components/src/modal/stories/index.story.tsx:1]: It'd be nice to have an automated test for this but I think it'd likely have to be e2e. Seems like I tried a unit test for this at some point and couldn't pull it off.

File: packages/components/src/modal/index.tsx (hunk 3 above)
Comment (stokesman) [reply packages/components/src/modal/index.tsx]: This and the inline comments are addressed in 145dc0e.

**Comment by afercia** [comment]
> I wish we could find a solution that involves improving the useFocusOutside hook, since it's used in a few places across Gutenberg that will likely face the same issue as the Modal component when an iframe is rendered.

Came here after some investigation for https://github.com/WordPress/gutenberg/pull/61313 where there's an ongoing discussion oh whether to implement some _modal_ behaviors to the Popover component. I share the same concern @ciampo expressed above. A popover could contain an iframe. If we implement the current hooks from `useDialog`, the issue addressed here will occur for the Popover as we. 
Architecturall, the editor has a `useDialog` component that encompasses some expected behaviors for a modal dialog. But, the Modal component now uses only _part_ of `useDialog`.
I turn, the Popover, the Inserter sidebar, and the entities save panel do use `useDialog` but they do not use the modal [aria-helper](https://github.com/WordPress/gutenberg/blob/bf3720532a6d0d4759d474faf8ff8e3eda11b305/packages/components/src/modal/aria-helper.ts) responsible to make the modal _behavior_ actually work.

Overall, the current state of these features seems a little confusing to me and uses ad-hoc implementations that should be better abstracted to be reusable. I'll try to create a new issue soon.
