### PR TITLE
List View: Recalculate window list when expanded state changes (fix logic for long nested lists)

### LINKED ISSUE #41613: Gutenberg List View has limits on the length it can display
### Description

It seems there are annoying limits on how may items the Gutenberg "List View" can display (using WordPress 6.0 on Win 10 system, latest version of Chrome browser). On long complicated pages, that contain many blocks, if I scroll far down my page, past many many blocks, and click on a block, that block often won't get highlighted in List View.  Lets refer to such a block as a "far down block". In fact, it won't even be visible in List View, because the List View is cut off, and not showing blocks beyond some fairly small limit of items.  If I go into List View, and close most of the nested items, to shrink what's shown, then I can have better luck for it letting me access a "far down block".  This is a tremendous hassle.
     I imagine this bug has been reported dozens of times, but I've not used GetHub before to search for existing bug reports. I see something like 12K bugs when doing a "Gutenberg List View" search, so not sure how I'm supposed to verify if this particular bug has already been reported. If there are work arounds to this bug reported, can someone send me a link to where this bug is being discussed?

### Step-by-step reproduction instructions

See my Description

### Screenshots, screen recording, code snippet

_No response_

### Environment info

See my description

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #42031: Column blocks (e.g. 30) are not displayed correctly in a group block
### Description

If I insert many column blocks in a group block (in the mentioned example these are 30 column blocks - I copied the columns blocks and the last column block I labeled "the last one" in the movie), then the list is not shown completely. 
As a workaround I have found the following solution: Delete a column block and undo the deletion afterwards. After that the list is shown correctly.
However, if I then leave the page and then edit this page again, then I have the same problem, which I then have to solve again via the mentioned workaround.

When I activate Gutenberg 13.5.1 the error is still present and after performing the workaround the error is fixed, but when I then exit the page and edit again the list is displayed correctly

### Step-by-step reproduction instructions

1. Create group block
2. Column block with a column containing an image, heading and paragraph.
3. I have copied this column block

### Screenshots, screen recording, code snippet

issue_columns_in_group

### Environment info

WordPress 6.0
Chrome
Gutenberg 13.5.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by andrewserong**
## What?

Fixes #41613, fixes #42031

Fix an issue with the windowing logic in the list view, where a short post containing a nested block with _heaps_ of inner blocks (e.g. a Gallery with > 40 images) results in the windowing logic getting stuck and not updating when a user scrolls up and down the list.

## Why?

When the list view is initially opened, if there are not many blocks at the root level, then no scrollbar will be present, so the fixed window list logic will not find the list view's scroll container in order to set up the windowing logic when a user scrolls up and down the list.

In normal circumstances (at the root level) this is fine — if you add or remove blocks, then `totalItems` within `useFixedWindowList` will change, causing the windowing logic to be recalculated. However, if you have a container block with heaps of children (i.e. 40 or more), then expanding and collapsing the container block does not cause the recalculation to happen. In these cases (short root list, but a container block with heaps of children), then prior to this PR, the windowing logic can fail to update.

## How?

The fix is to ensure the fixed window list is recalculated whenever a block is expanded or collapsed. We can do this by passing the `expandedState` to `useFixedWindowList` and then place the `expandedState` in the hook's `useLayoutEffect` dependency arrays. This causes the windowing to be recalculated whenever the expanded state is changed, anywhere in the tree.

## Testing Instructions

1. Create a post or page with only a few blocks at the root level.
2. Add a container block (e.g. Group or Gallery).
3. Within this container block, add lots of blocks (e.g. greater than 40-50 — I find it easier to test with a very large number like 100 or so).
4. Save your post or page and reload the editor.
5. Open the list view.
6. Expand the container block and scroll up and down the list view. Prior to this PR notice that the windowing logic is stuck and there'll be a big expanse of whitespace. With this PR applied, scrolling up and down the list view should update the list view.

### Testing Instructions for Keyboard

1. Reload the post or page created in the previous steps.
2. Navigate to the list view via keyboard (tab your way there).
3. With focus on the container block, press the Right arrow key to expand the item in the list.
4. Use Page Up / Page Down or Home and End keys to navigate up and down the list view. With this PR applied, the windowing logic should be correct, and behave in the same way as scrolling with the mouse.

## Screenshots or screencast 

Note in the before screengrab below, when expanding the collapsed block and then scrolling down the list, that the window list is not updated, resulting in an expanse of white further down the list. In the After screengrab, the list is updated as the user scrolls up and down the list.

| Before | After |
| --- | --- |
|  |  |

### CODE REVIEW

File: packages/compose/src/hooks/use-fixed-window-list/index.js [hunk 1]
```diff
@@ -59,7 +59,10 @@ export default function useFixedWindowList(
 		if ( ! useWindowing ) {
 			return;
 		}
-		const scrollContainer = getScrollContainer( elementRef.current );
+		const scrollContainer = elementRef.current?.closest(
+			'.edit-post-editor__list-view-panel-content'
+		);
+
```
Comment (andrewserong) [inline packages/compose/src/hooks/use-fixed-window-list/index.js]: This won't stay — it's just hacked in there for testing for now

**Comment by andrewserong** [comment]
Update: getting closer. I think I've figured out a reliable way to do it by recalculating the windowing logic whenever the expanded state changes (in https://github.com/WordPress/gutenberg/pull/53716/commits/04dc42e931c0e87f09825228488c055880646986). I'll do some more testing tomorrow, but if this works, I think the next step will be to decide on a good prop name for it.

**Comment by andrewserong** [comment]
> I think the next step will be to decide on a good prop name for it.

I've gone with `expandedState` to keep it explicit, and I think it's pretty consistent with the existing `totalItems` value that's used in a similar way (just that `expandedState` is optional, as not all lists will have such a thing)

**Review by t-hamano — APPROVED** [review]
LGTM! I think it works as expected, both with mouse and keyboard.

https://github.com/WordPress/gutenberg/assets/54422211/5f7ff956-b94d-489b-b561-dcc21664668c

**Comment by andrewserong** [comment]
Thanks for reviewing @t-hamano! I think this change is fairly safe (as the main change is that recalculation happens more frequently, and only on expanded state change), so I'll merge this in now. Happy to follow up if anyone runs into any issues!
