### PR TITLE
[Writing Flow]: Fix browser formatting with shortcuts on multiple selection

### LINKED ISSUE #41164: Text formatting for selected text across blocks reverts when block is clicked (6.0 RC3)
### Description

I just installed 6.0 RC3 on a dev site, and tested out the new feature that allows us to select text across multiple blocks at once.
When I select text, and then press CTRL-b to bold it, it all looks bold while it's selected. Once I then click back into either block, the bold disappears in that block.

I also see similar behavior with CTRL-i for italic.

(This behavior is on Chrome. On Firefox, Ctrl-b opens bookmarks and ctrl-i opens Page Info and does not change the formatting at all.)

### Step-by-step reproduction instructions

1. Create two paragraph blocks with text, in the Chrome browser.
2. Using the mouse, click+drag to select text across both paragraphs.
3. Press `ctrl-b` or `ctrl-i` to change the text formatting.
4. Click in either text block, outside the selected area. That will undo the formatting; click in the other text block and it will undo the formatting in that block.

### Screenshots, screen recording, code snippet

Here's a video that I hope is helpful: https://share.nrdp.rs/ApuXBrEq

### Environment info

Tested on 6.0 RC3 with the Twenty Twenty-Two Theme, and no active plugins. Chrome browser Windows 10.

I do not have the Gutenberg plugin installed; this is just 6.0 RC3.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/41164

Some common shortcuts for formatting like `cmd + b (bold), cmd + i(italic), etc...` are implemented by browsers. In GB we handle such events in RichText for multiple reasons(example would be different markup applied per browser). With the current multiple selection implementation we make conditionally the content being `contentEditable` which in turn enabled the browsers to add markup with such shortcuts.

At first this seemed to work well, but we keep all formatting internally in RichText, and that's why when you would select a single block afterwards, the formatting was 'gone'.

So, until we implement this([issue](https://github.com/WordPress/gutenberg/issues/40907)) we need to disable these formatting from browsers.

## Testing Instructions
1. Multiple select blocks and try the formatting shortcuts for bold, italic, underline, etc..
2. Observe that nothing happens
3. Ensure that shortcuts work as expected in single blocks(with RichText) like paragraphs, etc..
4. Test that no regression has been introduced.

#### Before

https://user-images.githubusercontent.com/16275880/169566284-be1fe13d-0492-4c32-9dc7-ed1094d5c910.mov

#### After

https://user-images.githubusercontent.com/16275880/169566310-4392fa12-3278-4493-8f04-6666f658eb5d.mov

### CODE REVIEW

File: packages/block-editor/src/components/writing-flow/use-input.js [hunk 1]
```diff
@@ -30,6 +30,16 @@ export default function useInput() {
 	} = useDispatch( blockEditorStore );
 
 	return useRefEffect( ( node ) => {
+		function onBeforeInput( event ) {
+			if ( ! hasMultiSelection() ) {
+				return;
+			}
+			// Prevent the browser to format something when we have multiselection.
+			if ( event?.inputType?.startsWith( 'format' ) ) {
```
Comment (mcsf) [inline packages/block-editor/src/components/writing-flow/use-input.js]:
```js
event?.inputType?.
//   ^
```

Can `event` ever be falsy?

**Review by jorgefilipecosta — APPROVED** [review]
LGTM 👍

File: packages/block-editor/src/components/writing-flow/use-input.js (hunk 1 above)
Comment (mcsf) [reply packages/block-editor/src/components/writing-flow/use-input.js]: Do we need to clarify where these `format*` input events come from? Or is this easy enough to understand?

**Review by mcsf — APPROVED** [review]
Clear diff, and good choice with `beforeinput`. LGTM!

File: packages/block-editor/src/components/writing-flow/use-input.js (hunk 1 above)
Comment (ntsekouras) [reply packages/block-editor/src/components/writing-flow/use-input.js]: >Can event ever be falsy?

I guess not :). I made some more tests and I don't think it's possible to get here without an event.

>Do we need to clarify where these format* input events come from? Or is this easy enough to understand?

I think the `Prevent the browser` is enough.
