### PR TITLE
Pasting: Convert unknown shortcodes to Shortcode block

### LINKED ISSUE #3062: Shortcodes don't work in a new Gutenberg post
## Issue Overview

Shortcodes don't work / render on the front-end (shows nothing for the shortcode) when adding a new shortcodes in a new Gutenberg post via visual editor (plugin version: 1.4.0) however, it works if you add it via HTML editor.

## Steps to Reproduce
1) Add a new post via Gutenberg editor
2) Add a shortcode via visual editor (in a paragraph block for instance) - I've tested with one of the Tickera shortcodes [tc_ticket id="19"]
3) Save post
4) View the post on front-end

## Expected Behavior
To render shortcode added via visual or HTML view in a same way

## Current Behavior
You'll notice that after saving a post, in the HTML view, Gutenberg formats the shortcode added to something like this <p>[tc_ticket id=&quot;19&quot;]</p>

This happens when:
1) Create a new post via Gutenberg (visual view)
2) Create a new post or page without a content (in a standard WordPress editor) then edit it via Gutenberg visual view.

It doesn't happen when you add a new post / page via standard WordPress editor WITH SOME CONTENT and then edit it via Gutenberg and add a shortcode. 

In the other words: if you add a new post with some content (with or without a shortcode) via standard WordPress editor, edit it via Gutenber after and add some shortcode(s) in the visual or HTML view, everything works like a charm.

### PR DESCRIPTION
**Pull request by mcsf**
Fixes #3062. Builds on top of #3609 (`fix/shortcode-pasting-plain-text`).

## Description
Blocks can specify shortcodes from which blocks should be automatically created when pasting. For any other shortcode, the core Shortcode block will now act as a fallback.

The main benefit of this is that, within the Shortcode block, the code will be properly handled and never mishandled. Notably, this fixes the case where a shortcode sitting in a Paragraph block will be picked up with its double quotes rendered as `&quot;`, thus breaking parsing of a shortcode's attributes.

## Screenshots (jpeg or gifs if applicable):
gutenberg-shortcode-paste-fallback

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style.
- [ ] My code follows has proper inline documentation.

### CODE REVIEW

File: blocks/api/raw-handling/shortcode-converter.js [hunk 1]
```diff
@@ -33,7 +33,7 @@ export default function( HTML ) {
 
 			const attributes = mapValues(
 				pickBy( transform.attributes, ( schema ) => schema.shortcode ),
-				( schema ) => schema.shortcode( match.shortcode.attrs ),
+				( schema ) => schema.shortcode( match.shortcode.attrs, match ),
```
Comment (mcsf) [inline blocks/api/raw-handling/shortcode-converter.js]: Passing all of `match` is intentionally broad for the sake of the discussion here. For this PR, only `match.content` is needed. Using `content` seems better than attempting to reconstruct the code from the shortcode parser's output (for which we'd still need more than just `match.shortcode.attrs`).

**Comment by ephox-mogran** [comment]
Works well

File: blocks/library/shortcode/index.js [hunk 2]
```diff
@@ -31,6 +31,27 @@ registerBlockType( 'core/shortcode', {
...
 
+	transforms: {
+		from: [
+			{
+				type: 'shortcode',
+				// Per "Shortcode names should be all lowercase and use all
+				// letters, but numbers and underscores should work fine too.
+				// Be wary of using hyphens (dashes), you'll be better off not
+				// using them." in https://codex.wordpress.org/Shortcode_API
+				tag: '[A-z0-9_-]+',
```
Comment (aduth) [inline blocks/library/shortcode/index.js]: Per above comment, should we not be matching capital letters as the regular expression here currently allows? Wondering if there's a more canonical regular expression from core code we should be leveraging, or if we should bother being strict at all.

File: blocks/library/index.js [hunk 3]
```diff
@@ -1,3 +1,4 @@
+import './shortcode';
```
Comment (aduth) [inline blocks/library/index.js]: Can you explain this change? It makes me nervous that we depend on load order of blocks.

Comment (mcsf) [reply blocks/library/index.js]: Yes, I agree. See https://github.com/WordPress/gutenberg/pull/3326#issuecomment-343150527. My thinking is that we can get away with it for now in `library`, and we could soon start to think of a mechanism based on explicit priority.

File: blocks/library/shortcode/index.js (hunk 2 above)
Comment (mcsf) [reply blocks/library/shortcode/index.js]: Yes, I'm fine with keeping it lowercase.
