### PR TITLE
Fixing broken layout styles for themes using theme.json settings on blocks that require layout styles

### LINKED ISSUE #43924: core/post-content settings in the theme.json is causing broken layout styles and invalid CSS
### Description

Using `core/post-content` settings in the `theme.json` file of a theme, [as in TT3](https://github.com/WordPress/twentytwentythree/blob/29150922040eb2b7e6aed00e3d1bb14459e41997/theme.json#L322-L330), in theme.json breaks the layout styles rendered.

### Step-by-step reproduction instructions

1. Activate any theme using settings for `core/post-content` in `theme.json` as [TT3](https://github.com/WordPress/twentytwentythree/blob/29150922040eb2b7e6aed00e3d1bb14459e41997/theme.json#L322-L330).
2. Add a few elements to a post, for example, a few paragraphs.
3. Save the post and navigate the frontend
4. Check that there is invalid CSS rendered and no block gap between post elements.

### Screenshots, screen recording, code snippet
**Using TT3**
layout

**Using Emptytheme**
To test using empty theme:
- Add this snippet to theme's `theme.json` file:
```
"styles": {
        "blocks": {
	        "core/post-content": {
		        "color": {
			        "text": "gray"
		        }
	        }
        }
}
```
- Activate emptytheme

image

### Environment info

- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
The function `get_property_value`  from `WP_Theme_JSON_6_1` class returns an empty string instead of `NULL`  when a property is not set. So when we call this function to get the styles, of a block that needs layout settings, the block gap value is an empty string instead of null and that prevents that the value is fallback to the correct value.

Let's see a example:
When Gutenberg calls `get_property_value` to get the layout styles of the `core/post-content` block, with [`$block_gap_value = static::get_property_value( $node, array( 'spacing', 'blockGap' ) )`](https://github.com/WordPress/gutenberg/blob/a6548830648dd26f96871898e31a9d1040abcb50/lib/compat/wordpress-6.1/class-wp-theme-json-6-1.php#L1333), `$block_gap_value` value is an empty string instead of NULL.This is causing that, for example, the default layout block gap value is not properly set for `core/post-content` block, ending in invalid CSS being rendered. 

## Why?

Because returning an empty string is causing problems while rendering layout styles resulting in the rendering of invalid CSS. This problem is described in https://github.com/WordPress/gutenberg/issues/43924.

## How?

This PR makes `NULL` the default result of `get_property_value()`.

If this looks like an acceptable solution for the problem probably I should add some PHP unit tests. 

## Testing Instructions
1. Activate any theme using settings for `core/post-content` in `theme.json` as [TT3](https://github.com/WordPress/twentytwentythree/blob/29150922040eb2b7e6aed00e3d1bb14459e41997/theme.json#L322-L330).
2. Add a few elements to a post, for example, a few paragraphs.
3. Save the post and navigate the frontend
4. Check that there is no invalid CSS rendered and that the block gap between post elements is there.

## Screenshots or screencast 
| Before | After  |
| --- | --- |
| layout | layout after |

Fixes: https://github.com/WordPress/gutenberg/issues/43924

### CODE REVIEW

**Comment by andrewserong** [comment]
Oh, thanks for looking into a fix for this! (And apologies, I believe the issue was likely introduced in https://github.com/WordPress/gutenberg/pull/43757 when I attempted to get the layout output to handle `0` string values).

As a potential alternative, we could always update the check in `get_layout_styles` to be a bit more specific about the value it's looking for. At the moment the check is a not null check on this line: https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.1/class-wp-theme-json-6-1.php#L1348

Would it work to use a check like `'0' === $block_gap_value || ! empty( $block_gap_value )` like we have in the style engine in this function: https://github.com/WordPress/gutenberg/blob/trunk/packages/style-engine/class-wp-style-engine.php#L263?

**Review by tellthemachines — COMMENTED** [review]
Thanks for fixing this! Tested with a few blocks with custom theme.json settings and everything seems to be working fine. Might be good to add some tests to make sure the function still behaves as expected though.

**Comment by draganescu** [comment]
It feels like the system should be less easy to break, getting an empty string instead of null in PHP is something to guard against - so this fix should fix the fact that invalid styles are output when the value to generate from is empty string.

We should strive to return consistent types as well, but if `get_property_value` always returns empty string and it did so before the block gap problem was introduced, then it should not be fixed.

**Comment by scruffian** [comment]
> As a potential alternative, we could always update the check in get_layout_styles to be a bit more specific about the value it's looking for.

I think it makes sense to do both things.

**Comment by matiasbenedetto** [comment]
Hi thanks for your feedback!


> Would it work to use a check like '0' === $block_gap_value || ! empty( $block_gap_value )

This check doesn't cover the case when $block_gap_value is `0`, so if I set this in my `theme.json`, the value is ignored and no gap styles are rendered for the block. 
```
"core/post-content": {
        "spacing": {
	        "blockGap": 0
        }
}
```
There are some themes using `0` as value: 
image



On the other hand this check `null !== $block_gap_value && false !== $block_gap_value && '' !== $block_gap_value` seems to be covering correctly all the cases:

Using `0`, `'0'` in 'theme.json' render the block gap styles.
Using `false`, `null`, or `""` doesn't render the block gap styles.

image



I added 4 tests:

- Without this PR the first and the fourth would fail this way:
image

- The second and third ones are to avoid future errors that could ignore the '0' or 0.

File: phpunit/class-wp-theme-json-test.php [hunk 1]
```diff
@@ -40,6 +40,163 @@ public function test_get_stylesheet_generates_layout_styles( $layout_definitions
...
+			'body { margin: 0;}.wp-site-blocks > .alignleft { float: left; margin-right: 2em; }.wp-site-blocks > .alignright { float: right; margin-left: 2em; }.wp-site-blocks > .aligncenter { justify-content: center; margin-left: auto; margin-right: auto; }.wp-site-blocks > * { margin-block-start: 0; margin-block-end: 0; }.wp-site-blocks > * + * { margin-block-start: 1rem; }body { --wp--style--block-gap: 1rem; }body .is-layout-flow > *{margin-block-start: 0;margin-block-end: 0;}body .is-layout-flow > * + *{margin-block-start: 1rem;margin-block-end: 0;}body .is-layout-flex{gap: 1rem;}body .is-layout-flow > .alignleft{float: left;margin-inline-start: 0;margin-inline-end: 2em;}body .is-layout-flow > .alignright{float: right;margin-inline-start: 2em;margin-inline-end: 0;}body .is-layout-flow > .aligncenter{margin-left: auto !important;margin-right: auto !important;}body .is-layout-flex{display: flex;}body .is-layout-flex{flex-wrap: wrap;align-items: center;}.wp-block-post-content.is-layout-flow > *{margin-block-start: 0;margin-block-end: 0;}.wp-block-post-content.is-layout-flow > * + *{margin-block-start: 0;margin-block-end: 0;}.wp-block-post-content.is-layout-flex{gap: 0;}',
```
Comment (andrewserong) [inline phpunit/class-wp-theme-json-test.php]: This test is failing, as the expected result is that there will be no gap output for `post-content`, but it looks like the string here was copied from the previous test. This is the error from PHPUnit:

```
There was 1 failure:

1) WP_Theme_JSON_Gutenberg_Test::test_get_stylesheet_generates_layout_styles_with_block_accepting_layout_settings_false with data set "layout definitions" (array(array('default', 'flow', 'is-layout-flow', array(array(' > .alignleft', array('left', '0', '2em')), array(' > .alignright', array('right', '2em', '0')), array(' > .aligncenter', array('auto !important', 'auto !important'))), array(array(' > *', array('0', '0')), array(' > * + *', array(null, '0')))), array('flex', 'flex', 'is-layout-flex', 'flex', array(array('', array('wrap', 'center'))), array(array('', array(null))))))
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'body { margin: 0;}.wp-site-blocks > .alignleft { float: left; margin-right: 2em; }.wp-site-blocks > .alignright { float: right; margin-left: 2em; }.wp-site-blocks > .aligncenter { justify-content: center; margin-left: auto; margin-right: auto; }.wp-site-blocks > * { margin-block-start: 0; margin-block-end: 0; }.wp-site-blocks > * + * { margin-block-start: 1rem; }body { --wp--style--block-gap: 1rem; }body .is-layout-flow > *{margin-block-start: 0;margin-block-end: 0;}body .is-layout-flow > * + *{margin-block-start: 1rem;margin-block-end: 0;}body .is-layout-flex{gap: 1rem;}body .is-layout-flow > .alignleft{float: left;margin-inline-start: 0;margin-inline-end: 2em;}body .is-layout-flow > .alignright{float: right;margin-inline-start: 2em;margin-inline-end: 0;}body .is-layout-flow > .aligncenter{margin-left: auto !important;margin-right: auto !important;}body .is-layout-flex{display: flex;}body .is-layout-flex{flex-wrap: wrap;align-items: center;}.wp-block-post-content.is-layout-flow > *{margin-block-start: 0;margin-block-end: 0;}.wp-block-post-content.is-layout-flow > * + *{margin-block-start: 0;margin-block-end: 0;}.wp-block-post-content.is-layout-flex{gap: 0;}'
+'body { margin: 0;}.wp-site-blocks > .alignleft { float: left; margin-right: 2em; }.wp-site-blocks > .alignright { float: right; margin-left: 2em; }.wp-site-blocks > .aligncenter { justify-content: center; margin-left: auto; margin-right: auto; }.wp-site-blocks > * { margin-block-start: 0; margin-block-end: 0; }.wp-site-blocks > * + * { margin-block-start: 1rem; }body { --wp--style--block-gap: 1rem; }body .is-layout-flow > *{margin-block-start: 0;margin-block-end: 0;}body .is-layout-flow > * + *{margin-block-start: 1rem;margin-block-end: 0;}body .is-layout-flex{gap: 1rem;}body .is-layout-flow > .alignleft{float: left;margin-inline-start: 0;margin-inline-end: 2em;}body .is-layout-flow > .alignright{float: right;margin-inline-start: 2em;margin-inline-end: 0;}body .is-layout-flow > .aligncenter{margin-left: auto !important;margin-right: auto !important;}body .is-layout-flex{display: flex;}body .is-layout-flex{flex-wrap: wrap;align-items: center;}'
```

File: phpunit/class-wp-theme-json-test.php [hunk 2]
```diff
@@ -40,6 +40,163 @@ public function test_get_stylesheet_generates_layout_styles( $layout_definitions
...
+					),
+				),
+				'styles'   => array(
+					'spacing' => array(
+						'blockGap' => '1rem',
+					),
+					'blocks'=> array(
+						'core/post-content' => array(
+							'spacing' => array(
+								'blockGap' => false, // '0' should be ignored and defaulted to the global gap ('1rem').
```
Comment (andrewserong) [inline phpunit/class-wp-theme-json-test.php]:
```suggestion
								'blockGap' => false, // false should be ignored and the block will default to using the global gap.
```

File: phpunit/class-wp-theme-json-test.php [hunk 3]
```diff
@@ -40,6 +40,163 @@ public function test_get_stylesheet_generates_layout_styles( $layout_definitions
...
+					),
+					'spacing' => array(
+						'blockGap' => true,
+					),
+				),
+				'styles'   => array(
+					'spacing' => array(
+						'blockGap' => '1rem',
+					),
+					'blocks'=> array(
```
Comment (andrewserong) [inline phpunit/class-wp-theme-json-test.php]: This is a small nit (and not at all a blocker, since the existing tests are nice and explicit), but instead of four separate tests, we could potentially combine the tests into one if we used different blocks with separate values, in the one `blocks` array.

E.g. something like:

```
					'blocks'=> array(
						'core/post-content' => array(
							'color' => array(
								'text' => 'gray',
							),
						),
						'core/social-links' => array(
							'spacing' => array(
								'blockGap' => '0',
							),
						),
						'core/buttons' => array(
							'spacing' => array(
								'blockGap' => 0,
							),
						),
						'core/columns' => array(
							'spacing' => array(
								'blockGap' => false,
							),
						),
					),
```

The name of the test could then be something like `test_get_stylesheet_generates_valid_block_gap_values_and_skips_null_or_false_values`?

**Review by andrewserong — APPROVED** [review]
Thanks for the follow-ups @matiasbenedetto, this is testing nicely for me! Also, adjusting the return type to `null` looks reasonably safe to me, since the function is protected and is only used in the layout output and in `compute_style_properties` where the null case is handled 👍

I tested that it resolves the issue with post content, and also tested with a variety of different values for simple and split (axial) block gap, and all appears to be working well for me.

Thanks for catching the `0` non-string value issue, too — since the UI will always save the `0` value as a string, I hadn't thought of hand-written themes using an integer value, so good to ensure that we don't accidentally cause issues for themes that explicitly set `0`.

I just left a totally optional comment about potentially grouping together the test cases into one,  but feel free to ignore it, it's not at all a blocker. (Also, it looks like you've already fixed up that final test while I was typing out this comment 😀)

File: phpunit/class-wp-theme-json-test.php (hunk 1 above)
Comment (andrewserong) [reply phpunit/class-wp-theme-json-test.php]: Just resolving this one, you'd already fixed this before I hit submit 😄

File: phpunit/class-wp-theme-json-test.php (hunk 3 above)
Comment (matiasbenedetto) [reply phpunit/class-wp-theme-json-test.php]: Yep, good idea :+1:
