### PR TITLE
Writing Flow: Fix vertical arrow navigation skips

### LINKED ISSUE #6524: Blocks: Arrow up from quote citation empty newline skips to quoted text
## Issue Overview

When a quote block citation includes line breaks, attempting to press Arrow Up from any of a blank new line of the citation will result in the caret being moved to the quoted text, rather than the line preceding it.

## Steps to Reproduce (for bugs)

1. Insert quote block
2. Enter some text
3. Arrow Down into citation field
4. Insert a line of text
5. Press Enter
6. Press Arrow Up

## Expected Behavior

Caret is moved to moved to the first line of the citation.

## Current Behavior

Caret jumps to quoted text.

## Possible Solution

Likely something going on with edge detection in `WritingFlow`.

## Video

caret-quote

### LINKED ISSUE #7838: Up and down keys skip several lines
**Describe the bug**

Sometimes, when using the `up` and `down` keys to navigate through text within a block, and across blocks, some lines will be skipped over.

**To Reproduce**

1. Paste the following into the code editor, then switch to the visual editor:

```
<!-- wp:preformatted -->
<pre class="wp-block-preformatted">function mark_as_encoded( $post_ID, $post ) {<br/>  if ( false == $this->encoded || 'revision' == $post->post_type ) {<br/>   return;<br/>  }<br/><br/>  delete_post_meta( $post_ID, 'syntaxhighlighter_encoded' );<em><br/></em>  add_post_meta( $post_ID, '_syntaxhighlighter_encoded', true, true );<br/>}</pre>
<!-- /wp:preformatted -->

<!-- wp:paragraph -->
<p>lorum ipsum blah blah blah here's a long url http://wp-develop.test/wp-admin/edit.php?s=foo&amp;post_status=all&amp;post_type=post&amp;action=-1&amp;m=0&amp;cat=0&amp;paged=1&amp;action2=-1<br/></p>
<!-- /wp:paragraph -->

<!-- wp:preformatted -->
<pre class="wp-block-preformatted"><em>/**<br/></em><em> * @param array $assoc_args Output format arguments.<br/></em><em> * @param array $fields Fields to display of each item.<br/></em><em> * @param string $prefix Check if fields have a standard prefix.<br/></em><em> */<br/></em>public function __construct( &amp;$assoc_args, $fields = null, $prefix = false ) {<br/>$format_args = array(<br/>'format' => 'table',<br/>'fields' => $fields,<br/>'field' => null,<br/>);<br/><br/>foreach ( array( 'format', 'fields', 'field' ) as $key ) {<br/>if ( isset( $assoc_args[ $key ] ) ) {<br/>$format_args[ $key ] = $assoc_args[ $key ];<br/>unset( $assoc_args[ $key ] );<br/>}<br/>}<br/><br/>if ( ! is_array( $format_args['fields'] ) ) {<br/>$format_args['fields'] = explode( ',', $format_args['fields'] );<br/>}<br/><br/>$format_args['fields'] = array_map( 'trim', $format_args['fields'] );<br/><br/>$this->args = $format_args;<br/>$this->prefix = $prefix;<br/>}</pre>
<!-- /wp:preformatted -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->
```

2. Click in the title to move the cursor there
3. Press the `down` key and watch where the cursor moves to. Repeat until you reach the end of the document. You'll notice that several of the lines have been skipped.

**Expected behavior**

Hitting the `up` or `down` key once should only move 1 line, and no lines should be skipped.

**Screen capture**

https://cloudup.com/cWtcPA1LbI2

**Desktop:**
- OS X 10.13.5
- Firefox Developer Edition 62.0b6
- Gutenberg `master` @ e697f72

### PR DESCRIPTION
**Pull request by aduth**
Fixes #7838
Fixes #6524
Salvaged from #6467

This pull request seeks to pull in improvements to the `isHorizontalEdge` and `isVerticalEdge` proposed in #6467 to resolve multiple issues around navigating multi-line content within contenteditables.

**Testing instructions:**

Repeat testing instructions from #7838 and #6524, observing expected results.

### CODE REVIEW

**Comment by iandunn** [comment]
This tested well for me, thanks!

**Comment by aduth** [comment]
This was a bit of a challenge to author end-to-end tests for, due to some unrelated bugginess (https://github.com/WordPress/gutenberg/issues/6524#issuecomment-404627323) and the fact that the arrow skipping wasn't always predictable for me. It seems to be relatively predictable with the implemented test (a preformatted block with at least one blank line).

File: packages/dom/src/dom.js [hunk 1]
```diff
@@ -1,25 +1,58 @@
...
+		anchorOffset,
+		focusOffset,
+	} = selection;
+
+	const position = anchorNode.compareDocumentPosition( focusNode );
+
+	return (
+		// Compare whether anchor node precedes focus node.
+		position !== DOCUMENT_POSITION_PRECEDING &&
+
```
Comment (tofumatt) [inline packages/dom/src/dom.js]: This empty newline strikes me as a bit odd. 🤷‍♂️

File: packages/dom/src/dom.js [hunk 2]
```diff
@@ -1,25 +1,58 @@
...
+		// which case compare offsets.
+		! ( position === 0 && anchorOffset > focusOffset )
+	);
+}
+
+/**
+ * Check whether the selection is horizontally at the edge of the container.
+ *
+ * @param {Element} container Focusable element.
+ * @param {boolean} isReverse Set to true to check left, false for right.
```
Comment (tofumatt) [inline packages/dom/src/dom.js]: This seems like an odd variable name–we aren't setting if something `isReverse`, we're checking for it. Would we want `checkForReverse` or maybe to specify the direction? eg. `isHorizontalEdge( container, direction='left' )`? I know it's a more verbose API but it's also easier to grok. Supplying a binary to this function doesn't provide much context in isolation. (`isHorizontalEdge( container, false )`–what is `false` in that bit?)

File: packages/dom/src/dom.js [hunk 3]
```diff
@@ -36,61 +69,34 @@ export function isHorizontalEdge( container, isReverse, collapseRanges = false )
...
-		}
-
-		node = parentNode;
-	}
+	const { endContainer, endOffset } = range;
+	range.selectNodeContents( container );
+	range.setEnd( endContainer, endOffset );
 
-	return true;
+	// Edge reached if effective caret position is at expected extreme.
```
Comment (tofumatt) [inline packages/dom/src/dom.js]: "extreme" is maybe an odd word to use here–I guess it's alright but maybe rephrasing this to something like:

```js
// Check if the caret position is at the expected start/end position (depending on the
// value of `isReverse`). If so we consider the horizontal edge to be reached.
```

🤷‍♂️

File: packages/dom/src/dom.js [hunk 4]
```diff
@@ -36,61 +69,34 @@ export function isHorizontalEdge( container, isReverse, collapseRanges = false )
...
 
 /**
- * Check whether the caret is vertically at the edge of the container.
+ * Check whether the selection is vertically at the edge of the container.
  *
- * @param {Element} container      Focusable element.
- * @param {boolean} isReverse      Set to true to check top, false for bottom.
- * @param {boolean} collapseRanges Whether or not to collapse the selection range before the check.
+ * @param {Element} container Focusable element.
+ * @param {boolean} isReverse Set to true to check top, false for bottom.
```
Comment (tofumatt) [inline packages/dom/src/dom.js]: Same here, I just find this API a bit odd. If we have to do deprecations to change it we could file an issue, but I just find it hard to understand in isolation.

File: packages/dom/src/dom.js [hunk 5]
```diff
@@ -150,21 +148,19 @@ export function getRectangleFromRange( range ) {
...
-		const { x, y, height } = range.startContainer.getBoundingClientRect();
+	let rect = range.getClientRects()[ 0 ];
 
-		// Create a new DOMRect with zero width.
-		return new DOMRect( x, y, 0, height );
+	// If the collapsed range starts (and therefore ends) at an element node,
+	// `getClientRects` can be empty in some browsers. This can be resolved
+	// by adding a temporary text node to the range.
+	if ( ! rect ) {
+		const padNode = document.createTextNode( '\u200b' );
```
Comment (tofumatt) [inline packages/dom/src/dom.js]: What is that character and why is it used? It's probably just worth documenting whether it matters for future devs.

**Review by tofumatt — APPROVED** [review]
I have some thoughts about comments and API stuff, but nothing that blocks merging, so address what you think needs to be addressed but overall looks good.

I tested locally and both issues were fixed by this branch 👍

File: packages/dom/src/dom.js (hunk 2 above)
Comment (aduth) [reply packages/dom/src/dom.js]: I'd probably tend to agree, but it's not within scope of the pull request, and since this is a [published module](https://www.npmjs.com/package/@wordpress/dom), such a change would qualify as breaking. Since I'm already touching the documentation, I'll at least try to make the boolean-ness more clear.

File: packages/dom/src/dom.js (hunk 5 above)
Comment (aduth) [reply packages/dom/src/dom.js]: Good call. I'll add some clarification with a link to the resource where I'd found the tip (StackOverflow).

File: packages/dom/src/dom.js (hunk 2 above)
Comment (tofumatt) [reply packages/dom/src/dom.js]: Yeah, that's fair. I just figured I'd point it out either way. If I still feel strongly about it I'll file a code quality issue later 😉

File: packages/dom/src/dom.js (hunk 1 above)
Comment (aduth) [reply packages/dom/src/dom.js]: >This empty newline strikes me as a bit odd. 🤷‍♂️

It's probably more symptomatic of it being an issue to need such descriptions in a multi-line return value, which could be achieved in a more verbose / easy-to-understand format by simply splitting out the `return` statements. I've done so in the rebased 52b8f97.

File: packages/dom/src/dom.js (hunk 2 above)
Comment (aduth) [reply packages/dom/src/dom.js]: Yes, it's good to point out. I think it's easy to fall into the trap of accepting "simple" values as arguments when authoring the function originally, and not considering that it would be difficult to interpret the intent of the statement `isHorizontalEdge( container, false )`.

File: packages/dom/src/dom.js [hunk 6]
```diff
@@ -36,61 +84,36 @@ export function isHorizontalEdge( container, isReverse, collapseRanges = false )
...
-	}
+	const { endContainer, endOffset } = range;
+	range.selectNodeContents( container );
+	range.setEnd( endContainer, endOffset );
 
-	return true;
+	// Check if the caret position is at the expected start/end position based
+	// on the value of `isReverse`. If so, consider the horizontal edge to be
+	// reached.
+	const caretOffset = range.toString().length;
```
Comment (youknowriad) [inline packages/dom/src/dom.js]: This doesn't work properly when the paragraph block starts with `<br />`

Related #8388

Comment (aduth) [reply packages/dom/src/dom.js]: Would appreciate your review at #8461

Comment (youknowriad) [reply packages/dom/src/dom.js]: Cool missed that PR :)
