### PR TITLE
Make link UI rich previews target agnostic and fix unwanted preview for internal URLs

### LINKED ISSUE #32657: Link UI briefly shows unwanted rich preview for internal URLs
## Description
Due to the introduction of loading placeholders towards the end of #31464, internal URLs will now briefly showing a "loading" state. This is not desirable.

This PR fixes this by testing against a base URL which is used to test if the URL being previewed is an internal URL. If it is then we bail out.

This baseURL has been added to the @wordpress/editor block editor settings as we cannot apply the test directly in <LInkControl> as this must remain WordPress agnostic. Note however, that the concept of a internal URL applies to all types of application.

## Step-by-step reproduction instructions
1. Create link to internal URL (ie: a Page or Post).
2. Click on link again to see preview.
3. See brief loading UI flash up.

## Expected behaviour
Should not show any rich preview loading state (or otherwise) for internal URLs.

## Actual behaviour

Shows a briefly "loading" UI for rich previews even if the URL is internal.

## Screenshots or screen recording (optional)
Screen Capture on 2021-06-11 at 09-30-22

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

### PR DESCRIPTION
**Pull request by getdave**
## Description
This PR has two purposes:

1. To fix [this bug where the rich preview shows in the Link UI for internal URLs ](https://github.com/WordPress/gutenberg/issues/32657)
2. As a consequence of `#1`, slightly refactor the rich data APIs to make them less _external_ URL specific. This has the advantage of fixing `#1` and also preparing the link UI for showing rich previews of _internal_ URLs in the future.

**Note**: changes to test solely down to renaming of the main fetch function.

Closes https://github.com/WordPress/gutenberg/issues/32657

## Questions

~@youknowriad Where do you think the new `fetchRichUrlData` function should reside? I was thinking `@wordpress/core-data`?~

Suggest we ship "as is" and revisit where to move the function in a followup.

#### Automated Testing

I will add unit tests for the `fetchRichUrlData` once we have found a suitable home for it.

#### Manual testing instructions

* Create post with text in it.
* Add x4 links 
    - one to an internal page/post
    - one to a remote URL (eg: `www.wordpress.org`).
    - one to a remote URL which includes the internal (URL of the site) as a query string (eg: `www.wordpress.org?qs=http://localhost:8888`).
    - one to a URL which uses a non-http protocol (eg: `tel:123456`).
* Click on all the links to preview them one by one.
* _Both_ the external links should show the rich preview.
* _Both_ the external links should show a loading state whilst fetching (trying throttling your network connection).
* The _internal_ URL should not show a loading state or any form of "rich" preview.
* The non-http URL should not show a loading state or any form of "rich" preview.
## Screenshots 

https://user-images.githubusercontent.com/444434/121881455-386c0300-cd07-11eb-8ff0-74d119963b33.mp4

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by getdave** [comment]
I am aware that all the unit tests are broken. I can fix these as soon as I get a 👍 on the overall direction here.

File: packages/editor/src/components/provider/use-block-editor-settings.js [hunk 1]
```diff
@@ -51,11 +53,41 @@ function useBlockEditorSettings( settings, hasTemplate ) {
...
+	function fetchRichUrlData( url, fetchOptions = {} ) {
+		const emptyDataSet = {};
+
+		const fetchingBaseUrl = '' === baseUrl;
+
+		// If the baseUrl is still resolving then return
+		// empty data for this request.
+		if ( fetchingBaseUrl ) {
+			return Promise.resolve( emptyDataSet );
+		}
```
Comment (kevin940726) [inline packages/editor/src/components/provider/use-block-editor-settings.js]: When will this happen? Should we instead wait for it to be resolved? So instead of using `useSelect`, we could probably just use `subscribe` and wrap it inside a promise.

File: packages/editor/src/components/provider/use-block-editor-settings.js [hunk 2]
```diff
@@ -51,11 +53,41 @@ function useBlockEditorSettings( settings, hasTemplate ) {
...
+
+		// More accurate test for internal URLs to avoid edge cases
+		// such as baseURL being included as part of a query string
+		// on the target url.
+		const baseUrlAuthority = getAuthority( baseUrl );
+		const urlAuthority = getAuthority( url );
+
+		const isInternal = urlAuthority === baseUrlAuthority;
```
Comment (kevin940726) [inline packages/editor/src/components/provider/use-block-editor-settings.js]: Should we guard when `url` is not a valid url? Or is it being handled elsewhere?

`getAuthority` also returns undefined if there's no _authority_. TBH, maybe we should just use the native `URL` constructor to parse the urls? Maybe in another PR though.

File: packages/editor/src/components/provider/use-block-editor-settings.js [hunk 3]
```diff
@@ -51,11 +53,41 @@ function useBlockEditorSettings( settings, hasTemplate ) {
...
 			),
+			baseUrl: getUnstableBase()?.url || '',
 		};
 	}, [] );
 
 	const { undo } = useDispatch( editorStore );
 
+	// Temporary home - should this live in `core-data`?
+	function fetchRichUrlData( url, fetchOptions = {} ) {
+		const emptyDataSet = {};
```
Comment (kevin940726) [inline packages/editor/src/components/provider/use-block-editor-settings.js]: If we want to create a constant empty object, then we should probably declare it outside the render function, like in the top level, so that the instance never changes.

**Review by kevin940726 — COMMENTED** [review]
Mostly looks good! I'm okay as long as it unblocks things and fixes the bug. We can create follow-up PRs if necessary 👍 .

File: packages/editor/src/components/provider/use-block-editor-settings.js (hunk 2 above)
Comment (getdave) [reply packages/editor/src/components/provider/use-block-editor-settings.js]: Great point. Lets follow up with guards.

File: packages/editor/src/components/provider/use-block-editor-settings.js (hunk 1 above)
Comment (getdave) [reply packages/editor/src/components/provider/use-block-editor-settings.js]: The state isn't populated until the selector resolves. Therefore there is the possibility that we're comparing against nothing.

Therefore I thought I'd set the default to an empty string so that we can tell the difference between:

1. This selector isn't yet populated (empty string `''`).
2. This selector will never be populated (`undefined`)- which would presumably be the case if you're in a non-WP env.

How would the subscribe look? Not sure I've seen this pattern.

Comment (kevin940726) [reply packages/editor/src/components/provider/use-block-editor-settings.js]: `useSelect` is actually just a wrapper of `subscribe` (well, not actually, but a wrapper of a more advanced version of subscribe). So it would look something like this.

```js
import { subscribe, select } from '@wordpress/data';

const baseUrlPromise = new Promise( ( resolve ) => {
	const unsubscribe = subscribe( () => {
		const baseUrl = select( coreStore ).getUnstableBase()?.url;
		if ( baseUrl ) {
			resolve( baseUrl );
			unsubscribe();
		}
	} );
} );
```

I understand if it's too much work though. Where does this `getUnstableBase()` come from? Why isn't it populated with initial data? I can't seem to find the definition of this method 🤔.

Comment (getdave) [reply packages/editor/src/components/provider/use-block-editor-settings.js]: > Where does this getUnstableBase() come from? Why isn't it populated with initial data? I can't seem to find the definition of this method 🤔.

Same! I just tried searching for it and it's nowhere in the source. Does it come from WP Core?

Comment (getdave) [reply packages/editor/src/components/provider/use-block-editor-settings.js]: @gwwar used it in the `Home` block code which is where I found it. Do you know where this is from Kerry?

Comment (getdave) [reply packages/editor/src/components/provider/use-block-editor-settings.js]: Ok I found some info here https://github.com/WordPress/gutenberg/pull/30812#issuecomment-819748485.

Looks like the getters and resolvers are dynamically generated here

https://github.com/WordPress/gutenberg/blob/eaa1be08e278a76774c040414c1691058caaa653/packages/core-data/src/index.js#L20-L49

File: packages/editor/src/components/provider/use-block-editor-settings.js (hunk 2 above)
Comment (getdave) [reply packages/editor/src/components/provider/use-block-editor-settings.js]: I added the `isUrl` guard because this package has been designed to  cater for URLs. I remember @aduth spending a long time on getting it to conform to the spec.

We may still need something like `isValidHref` to check whether a URL is suitable to be fetched (eg: it isn't a tel or a hash or anything like that):

https://github.com/WordPress/gutenberg/blob/eaa1be08e278a76774c040414c1691058caaa653/packages/format-library/src/link/utils.js#L29

File: packages/editor/src/components/provider/use-block-editor-settings.js (hunk 1 above)
Comment (getdave) [reply packages/editor/src/components/provider/use-block-editor-settings.js]: I've now used the resolver to determine whether the baseUrl is available.

File: packages/editor/src/components/provider/use-block-editor-settings.js [hunk 4]
```diff
@@ -51,11 +69,61 @@ function useBlockEditorSettings( settings, hasTemplate ) {
...
+			}
+
+			// Test for "http" based URL as it is possible for valid
+			// yet unusable URLs such as `tel:123456` to be passed.
+			const protocol = getProtocol( url );
+
+			if (
+				! isValidProtocol( protocol ) ||
+				! protocol.startsWith( 'http' ) ||
+				! /^https?:\/\/[^\/\s]/i.test( url )
```
Comment (kevin940726) [inline packages/editor/src/components/provider/use-block-editor-settings.js:95]: Why do we need this?

**Review by kevin940726 — APPROVED** [review]
LGTM 👍 Just a small question.

File: packages/editor/src/components/provider/use-block-editor-settings.js (hunk 4 above)
Comment (getdave) [reply packages/editor/src/components/provider/use-block-editor-settings.js:95]: Cos otherwise things like tel: protocol become valid and we try to fetch them.

Comment (getdave) [reply packages/editor/src/components/provider/use-block-editor-settings.js:95]: I think i mention in the code comment above that line.

**Comment by getdave** [comment]
**Note**: ~I will create~ [I have created a followup](https://github.com/WordPress/gutenberg/issues/32725) to discuss where would be the best place for the `fetchRichPreviews` function to reside. Currently it's in `packages/editor/src/components/provider/use-block-editor-settings.js` which I don't feel is well suited.

File: packages/editor/src/components/provider/use-block-editor-settings.js (hunk 4 above)
Comment (kevin940726) [reply packages/editor/src/components/provider/use-block-editor-settings.js:95]: Oh I mean why we need the last line. Isn't `protocol.startsWith( 'http' )` enough?

Comment (getdave) [reply packages/editor/src/components/provider/use-block-editor-settings.js:95]: I'm actually copying if from @talldan's implementation in https://github.com/WordPress/gutenberg/pull/32663

Comment (kevin940726) [reply packages/editor/src/components/provider/use-block-editor-settings.js:95]: Wrong PR? I think it's #11835?

Oh this is interesting. I guess the reason is to ensure there are two `//` after the `http` protocol. So that these will fail:

- `http:example.com`
- `https:/example.com`

However, seems like most major browsers support both above and will interpret them as valid urls.

In the [spec](https://url.spec.whatwg.org/#scheme-relative-special-url-string) though, it's required to have the `//`. Hence, I guess this change is actually preferred. TIL!
