### PR TITLE
Replace locate_template method

### LINKED ISSUE #26359: Use of undefined constants STYLESHEETPATH and TEMPLATEPATH PHP warning
**Describe the bug**
The Gutenberg's Global Styles feature is throwing following PHP warnings in curtomizer context on some requests:

```
Warning: Use of undefined constant STYLESHEETPATH - assumed 'STYLESHEETPATH' (this will throw an Error in a future version of PHP) in /srv/www/wordpress-default/public_html/wp-includes/template.php on line 663
Warning: Use of undefined constant TEMPLATEPATH - assumed 'TEMPLATEPATH' (this will throw an Error in a future version of PHP) in /srv/www/wordpress-default/public_html/wp-includes/template.php on line 666
```

This is caused by the call of the `locate_template` in

https://github.com/WordPress/gutenberg/blob/9ce9380681c5c02caed074fbe1539b2174b18319/lib/global-styles.php#L14

which is being hooked to the `wp_enqueue_scripts` action via some function chain in

https://github.com/WordPress/gutenberg/blob/9ce9380681c5c02caed074fbe1539b2174b18319/lib/global-styles.php#L979

However, the WordPress customizer may call the `wp_enqueue_scripts` prior setting up a theme and defining the templating constants ( `STYLESHEETPATH`, `TEMPLATEPATH` ) in case a user w/o necessary capabilities for switching theme is attempting to review a customizer changeset. Customizer is hooking the `setup_theme` action and eventually dying. See:

https://github.com/WordPress/WordPress/blob/a7d6e929c96f2d1e6e0307e781d36c338b8bf877/wp-includes/class-wp-customize-manager.php#L366 and https://github.com/WordPress/WordPress/blob/a7d6e929c96f2d1e6e0307e781d36c338b8bf877/wp-includes/class-wp-customize-manager.php#L505

**To reproduce**
1. Go to a customizer screen of your site under a user account with all appropriate caps needed for making changes in customizer
2. Make any changes ( does not really matter which ones ), but don't publish those
3. Copy the customizer preview iframe URL ( should be something like: `?customize_changeset_uuid=c0af4551-5b8c-4260-ad4e-368af589c737&customize_theme=twentyseventeen&customize_messenger_channel=preview-0` )
4. Open the copied URL while logged in as a subscriber (or any other user w/o switch_themes capability)
5. Notice the PHP warning

**Expected behavior**
No PHP warning

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "gutenberg plugin"
- If the Gutenberg plugin is installed, which version is it? 920

### PR DESCRIPTION
**Pull request by oandregal**
Fixes https://github.com/WordPress/gutenberg/issues/26359
Related https://github.com/WordPress/gutenberg/pull/28410#discussion_r572847813

This PR replaces `locate_method` by building the file path ourselves by means of `get_stylesheet_directory`. It also minimizes the number of times we check the file exists and is readable.

This stems from this conversation and a bug report (while I couldn't reproduce, I understand that validates the idea that `locate_template` is unsafe in certain scenarios).

## Test

- Activate TT1-blocks.
- Load front-end and check that it works as expected (also no errors in the log).
- Load editors (site & post) and verify that they work as expected (also no errors in the log).

### CODE REVIEW

File: lib/class-wp-theme-json-resolver.php [hunk 1]
```diff
@@ -482,10 +482,37 @@ public static function get_user_custom_post_type_id() {
 	 */
 	public static function theme_has_support() {
 		if ( ! isset( self::$theme_has_support ) ) {
-			self::$theme_has_support = is_readable( locate_template( 'experimental-theme.json' ) );
+			self::$theme_has_support = !! self::get_file_path_from_theme( 'experimental-theme.json' );
```
Comment (Soean) [inline lib/class-wp-theme-json-resolver.php]: Maybe we can cast the type to make it more readable.

```suggestion
			self::$theme_has_support = (bool) self::get_file_path_from_theme( 'experimental-theme.json' );
```

Comment (nosolosw) [reply lib/class-wp-theme-json-resolver.php]: I like that: https://github.com/WordPress/gutenberg/pull/28942/commits/23e0a78c8c7d5049db3d9b166fba94bf620d9896

**Comment by aristath** [comment]
Just curious, is there a reason we don't use [`get_theme_file_path()`](https://developer.wordpress.org/reference/functions/get_theme_file_path/)?

**Comment by nosolosw** [comment]
> Just curious, is there a reason we don't use get_theme_file_path()?

I think the API in this PR is simpler to operate with: for example, if the file doesn't exist or is an empty string, it always returns an empty string, hence consumers don't need to check anything else than whether the result is an empty string (quick check). 

With `get_theme_file_path`, consumers always have to check whether the file effectively exists, because it can be a variety of: the path to the stylesheet directory, the path to the file, the path to a file in the template directory that nobody has checked it existed or not.

**Comment by aristath** [comment]
Gotcha. Thanks for the explanation @nosolosw :+1:

**Comment by nosolosw** [comment]
Some other things landed, so had to rebase. Welcome a :+1: !

**Comment by nosolosw** [comment]
I've rebased this from master, there were some conflicts and also unrelated mobile test failures. Anyone can give this a :+1: if it looks good?

File: lib/class-wp-theme-json-resolver.php [hunk 2]
```diff
@@ -483,10 +483,37 @@ public static function get_user_custom_post_type_id() {
...
+		// that threw errors in some scenarios.
+		//
+		// When the theme.json merge algorithm properly supports
+		// child themes, this should also fallback
+		// to the template path, as locate_template did.
+		$located   = '';
+		$candidate = get_stylesheet_directory() . '/' . $file_name;
+		if ( is_readable( $candidate ) ) {
+			$located = $candidate;
+		}
```
Comment (aristath) [inline lib/class-wp-theme-json-resolver.php:515]: Shouldn't we also add a check for `get_template_directory` as well?
If the user has a child-theme activated and the file doesn't exist in the child theme but exists in the parent theme then the file from the parent theme should be used.

Comment (nosolosw) [reply lib/class-wp-theme-json-resolver.php:515]: I don't think we're ready for that (see comment above this code).

Comment (nosolosw) [reply lib/class-wp-theme-json-resolver.php:515]: It wasn't something we supported, although we probably should at some point https://github.com/WordPress/gutenberg/issues/25612

File: lib/class-wp-theme-json-resolver.php [hunk 3]
```diff
@@ -287,8 +287,8 @@ public static function get_core_data() {
 	 */
 	public static function get_theme_data( $theme_support_data = array() ) {
 		if ( null === self::$theme ) {
-			$theme_json_data = self::get_from_file( locate_template( 'experimental-theme.json' ) );
-			self::translate( $theme_json_data, wp_get_theme()->get( 'TextDomain' ) );
+			$theme_json_data = self::read_json_file( self::get_file_path_from_theme( 'experimental-theme.json' ) );
+			self::translate_presets( $theme_json_data, wp_get_theme()->get( 'TextDomain' ) );
```
Comment (aristath) [inline lib/class-wp-theme-json-resolver.php:291]: Getting PHP fatal errors because of the calls to `translate_presets()` which no longer exists

File: lib/class-wp-theme-json-resolver.php [hunk 4]
```diff
@@ -207,8 +207,8 @@ public static function get_core_data() {
 		}
 
 		$all_blocks = WP_Theme_JSON::ALL_BLOCKS_NAME;
-		$config     = self::get_from_file( __DIR__ . '/experimental-default-theme.json' );
-		self::translate( $config );
+		$config     = self::read_json_file( __DIR__ . '/experimental-default-theme.json' );
+		self::translate_presets( $config );
```
Comment (aristath) [inline lib/class-wp-theme-json-resolver.php:211]: Same here, getting PHP fatal errors because of the calls to `translate_presets()` which no longer exists

**Review by aristath — CHANGES_REQUESTED** [review]

File: lib/class-wp-theme-json-resolver.php (hunk 4 above)
Comment (nosolosw) [reply lib/class-wp-theme-json-resolver.php]: Thanks!

Too many rebases :sweat_smile:

**Review by aristath — APPROVED** [review]
LGTM :+1: 
Tested and confirmed

**Review by Soean — APPROVED** [review]
