### PR TITLE
Preserve the wp_theme_preview query arg when navigating in Site Editor

### LINKED ISSUE #61239: Theme preview activation does not work after navigating in the previewing site editor
### Description

Live preview should allow users to customise a theme before activation. This feature is lost now as any navigation in the site editor that previews a theme removes the save button.

### Step-by-step reproduction instructions

1. Go to Appearance > Themes
2. On any of the installed and inactive block themes hover and click "Live preview"
3. On the Site editor that opens, click on _any_ of the sidebar items
4. **Notice bug**: the activate button disappears replaced w/ a "Saved" disabled button

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/107534/084a921f-bc07-4bf5-8058-d17e915806ae

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by jsnajdr**
Fixes #61239, a bug where the `wp_theme_preview` query param is not preserved when navigating around Site Editor in "Activate theme" mode.

It's a regression I commited in #60466, stopping to preserve query params automatically.

This fix is a not very good "temporary" hotfix. It's not a good solution to patch the router package, but I haven't found any other so far and I want to make the feature work again quickly.

**How to test:**
- open Site Editor with a `wp_theme_preview=theme-slug` query param.
- verify that the UI is modified accordingly: shows the "Previewing: Theme" label in the sidebar, and all save UI actions are "Activate Theme" instead of "Save".

### CODE REVIEW

File: packages/edit-site/src/components/sidebar-navigation-screen-navigation-menus/leaf-more-menu.js [hunk 1]
```diff
@@ -82,9 +75,6 @@ export default function LeafMoreMenu( props ) {
 					{
 						postType: 'page',
 						postId: attributes.id,
-						...( isPreviewingTheme() && {
-							wp_theme_preview: currentlyPreviewingTheme(),
-						} ),
```
Comment (jsnajdr) [inline packages/edit-site/src/components/sidebar-navigation-screen-navigation-menus/leaf-more-menu.js:87]: Preserving `wp_theme_preview` no longer needs to be done explicitly like this. It is now, and should continue to be, abstracted and automated.

Comment (draganescu) [reply packages/edit-site/src/components/sidebar-navigation-screen-navigation-menus/leaf-more-menu.js:87]: Does [this place](https://github.com/WordPress/gutenberg/blob/07ea95344c5343d8f8f8c8f3ce71de9a66174df8/packages/edit-site/src/components/routes/link.js#L36) need to remove the param management?

Comment (draganescu) [reply packages/edit-site/src/components/sidebar-navigation-screen-navigation-menus/leaf-more-menu.js:87]: Does [this place](https://github.com/WordPress/gutenberg/blob/07ea95344c5343d8f8f8c8f3ce71de9a66174df8/packages/edit-site/src/components/routes/link.js#L36) need to remove the param management?

**Review by draganescu — COMMENTED** [review]
Tested and it works for restoring the theme preview functionality. Left one  comment, not sure if it causes any issue.

So the router should maybe get a setting that contains what params need to be sticky, or are externally "managed"?

File: packages/edit-site/src/components/sidebar-navigation-screen-navigation-menus/leaf-more-menu.js (hunk 1 above)
Comment (jsnajdr) [reply packages/edit-site/src/components/sidebar-navigation-screen-navigation-menus/leaf-more-menu.js:87]: That `useLink` function is also creating a URL link that can be used as an `<a href>` attribute. Therefore the `wp_theme_preview` arg needs to be added explicitly, there is no router magic that would add it automatically. That's why I'm keeping it here.

**Comment by jsnajdr** [comment]
> So the router should maybe get a setting that contains what params need to be sticky, or are externally "managed"?

We'll need to think more deeply about what is the best long term solution for this. If the router has a "sticky params" setting, they need to somehow find their way also to the URLs that are not processed by the router. See the `useLink` comment. One way to do this is that the `useLink` hook uses the [`history.createHref`](https://github.com/remix-run/history/blob/dev/docs/api-reference.md#historycreatehrefto-to) function to create the links -- then they are also processed by the router and can honor the "sticky params" setting.

I plan to continue working on this, this PR is just a good-enough hotfix so that the Theme Preview feature is not broken for too long.

**Comment by jsnajdr** [comment]
Apparently I broke e2e tests, like this one:
```
Site editor browser history › Back button works properly 
```
There are links that have an empty `&wp_theme_preview=` query arg, which shouldn't be there at all. Will need to fix that before merging.

**Comment by jsnajdr** [comment]
@draganescu I fixed the e2e failures (caused by bad `undefined` vs `null` comparison) and I believe the PR is ready to ship. Would you mind doing a final review?

**Review by draganescu — APPROVED** [review]
Let's get this in as it fixes the big problem. 

Stumbled upon another smaller problem, which may have been in before any change:

- when previewing
- after activating a theme
- clicking browser back
- brings the activate button back, which is wrong b/c the theme is already active

⬆️ this needs to be a separate issue, not blocking here.

Thank you for the quick help @jsnajdr

**Comment by jsnajdr** [comment]
> brings the activate button back, which is wrong b/c the theme is already active

Nice find, though in this case it's not a regression caused by #60466, it existed before. If you click browser back button after theme activation, the URL changes from one that doesn't have `wp_theme_preview` to one that does. Therefore you're in a Theme Preview mode, it's hard to avoid.

A possible fix is to detect the case where we're previewing the currently active theme. In that case all the "Activate ..." buttons have no function and we should be redirected to plain Site Editor, without `wp_theme_preview`.
