### PR TITLE
Fix: Custom font size taking over fit text.

### LINKED ISSUE #73211: Fit Text Block Variation doesn't work if underlying block has explicit font size
### Description

This is a bug report about the current Block Variation implementation of Fit Text. The issues is that while the variation removes the font-size setting UI, it does not strip any previously-set font size. Because `theme.json` font-size classes use `!important`, this overrides the fit text behavior, leading to broken user expectations.

### Step-by-step reproduction instructions

1. Insert Paragraph block
2. Type some text in it
3. Set a non-default font size for the Paragraph block
4. Switch the Paragraph to the fit text Paragraph variation

The front-end of the site uses the font size setting selected in Step 3.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WP 6.9-RC1
- No Gutenberg plugin
- Hybrid custom theme

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [x] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Fixes: https://github.com/WordPress/gutenberg/issues/73211

Fixes an issue where if a paragraph/heading had a custom font size and then was conververted to the stretchy variation. The custom font size on the front end was applied instead of fit text.

cc: @mrwweb

## How?
Insert Paragraph block
Type some text in it
Set a non-default font size for the Paragraph block
Switch the Paragraph to the fit text Paragraph variation
The front-end of the site should not use the font size setting selected in Step 3 and should instead show fit text working normally as in the editor.

### CODE REVIEW

File: lib/block-supports/typography.php [hunk 1]
```diff
@@ -260,6 +260,7 @@ function gutenberg_render_typography_support( $block_content, $block ) {
 				$block_content = $processor->get_updated_html();
 			}
 		}
+		return $block_content;
```
Comment (jorgefilipecosta) [inline lib/block-supports/typography.php:264]: The rest of the code returns $block_content anyway which on this case we want to ignore so we should return here.

Comment (mcsf) [reply lib/block-supports/typography.php:264]: Let's make this early return clear for other devs and mitigate the risk that future changes break anything:

```suggestion
		// fitText supersedes any other typography features
		return $block_content;
```

* * *

Also, shouldn't the condition at the top be improved (regardless of this PR)? Currently it works on the assumption that the default will always be false (and thus if the attribute has a value it must be true), but that sounds just a little fragile to me.

```diff
-if ( ! empty( $block['attrs']['fitText'] ) && ! is_admin() ) {
+if ( ! empty( $block['attrs']['fitText'] ) && $block['attrs']['fitText'] && ! is_admin() ) {
```

Comment (jorgefilipecosta) [reply lib/block-supports/typography.php:264]: Feedback applied 👍

**Review by mcsf — APPROVED** [review]
LGTM, assuming the [missing](https://github.com/WordPress/gutenberg/actions/runs/19338641747/job/55320696194?pr=73241) core backport is attached

File: lib/block-supports/typography.php (hunk 1 above)
Comment (mcsf) [reply lib/block-supports/typography.php:264]: I don't know where my mind was last week, but my advice about `! empty( … )` was totally idiotic. Your code was fine for the purpose, @jorgefilipecosta. Sorry about that. :)

> A variable is considered empty if it does not exist [or if its value equals false](https://www.php.net/manual/en/function.empty.php#:~:text=A%20variable%20is%20considered%20empty%20if%20it%20does%20not%20exist%20or%20if%20its%20value%20equals%20false.%20empty()%20does%20not%20generate%20a%20warning%20if%20the%20variable%20does%20not%20exist.). empty() does not generate a warning if the variable does not exist.
