### PR TITLE
Try to fix auto resizing in template part focus mode

### LINKED ISSUE #36141: Isolated template part editor: Height doesn't always wrap correctly
I noticed when testing with the [Quadrat](https://wordpress.org/themes/quadrat/) theme that the height of the header in the isolated template part editing view is not correct. For some reason it is way too tall:

https://user-images.githubusercontent.com/846565/139853072-7ab7bb6c-4ec3-400b-8ffd-ad851234b45b.mp4

cc @kevin940726

### PR DESCRIPTION
**Pull request by kevin940726**
## Description

Close https://github.com/WordPress/gutenberg/issues/36141.

Try to fix auto resizing in Template Part focus mode with two changes:

- Force `height: fit-content` for `<body>` and `<html>`.
- Force `min-height: 0` for the root containers.

## How has this been tested?

1. Activate block-based theme like `tt1-blocks` or `Quadrat`.
2. Go to Appearance -> Editor (beta)
3. Click on navigation toggle button and select "Template Part"
4. Select any template part to enter the focus mode
5. Observe that the canvas should have height fit to its content

## Screenshots 

**`tt1-blocks`**

Before | After
--- | ---
image | image

**Quadrat**

Before | After
--- | ---
image | image

## Types of changes

Bug fix

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/edit-site/src/components/block-editor/resizable-editor.js [hunk 1]
```diff
@@ -133,8 +155,15 @@ function ResizableEditor( { enableResizing, settings, ...props } ) {
...
 							// Forming a "block formatting context" to prevent margin collapsing.
 							// @see https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context
-							`.edit-site-block-editor__block-list { display: flow-root; }`
+							`.is-root-container { display: flow-root; }`
 						}</style>
+						{ enableResizing && (
+							// Some themes will have `min-height: 100vh` for the root container,
+							// which isn't a requirement in auto resize mode.
+							<style>
+								{ `.is-root-container { min-height: 0 !important; }` }
```
Comment (kevin940726) [inline packages/edit-site/src/components/block-editor/resizable-editor.js]: Not entirely sure if this makes sense in all cases though 🤔 .

**Comment by jameskoster** [comment]
I'm still seeing the scrolling issue when the theme applies a border to the body:


https://user-images.githubusercontent.com/846565/146166476-0d5f8e23-4048-43a7-bc6a-b2ddb5bac523.mp4

Quadrat is working much better though :)

Screenshot 2021-12-15 at 10 07 29

**Comment by kevin940726** [comment]
@jameskoster Just being curious, why would anyone wants to add border the the `<body>` element 😅 ? It feels like an anti-pattern to me.

**Comment by jameskoster** [comment]
I used a border to add the blue/green gradient outline around the page in my theme:

Screenshot 2021-12-16 at 10 06 24

Is it an anti-pattern? Maybe... but this was the only way I could think to achieve the desired effect and maintain predictable behaviour of the background color option in global styles.

**Comment by kevin940726** [comment]
> I used a border to add the blue/green gradient outline around the page in my theme:
> 
> Screenshot 2021-12-16 at 10 06 24
> 
> Is it an anti-pattern? Maybe... but this was the only way I could think to achieve the desired effect and maintain predictable behaviour of the background color option in global styles.

Interesting 🤔 !

I just pushed https://github.com/WordPress/gutenberg/pull/37394/commits/bc1a27b955edf229b64fc66388c45b34aeb5c49f trying to fix this issue using a different approach (accessing `documentElement.scrollHeight` instead). In the meantime I also found a bug (not resizing on change) only in Firefox and fixed it as well.

**Comment by jameskoster** [comment]
Bingo :D 

Screenshot 2021-12-17 at 11 31 38

I tried a bunch of block themes for the directory and didn't see any issues except for one: [Bai theme](https://wordpress.org/themes/bai/).

Screenshot 2021-12-17 at 11 33 40

I couldn't see anything in the markup that would cause this, so maybe worth a check?

**Comment by kevin940726** [comment]
@jameskoster Nice catch! I pushed some changes to address that as well. I also removed `MutationObserver` because it seems like we don't need it after all.

**Review by jameskoster — APPROVED** [review]
Much better :) 

Screenshot 2021-12-20 at 11 35 36

**Review by Mamaduka — APPROVED** [review]
Thanks, @kevin940726. The changes look good to me.
