### PR TITLE
Packages: only add polyfills where needed

### LINKED ISSUE #65216: Improve dependency extraction to only include `wp-polyfill` when needed
## What problem does this address?

Currently, simple scripts like `wp-hooks` depend on `wp-polyfill`, even when they don't seem to make use of any of the features that are currently present in `wp-polyfill`:

<details>
<summary>The list of polyfilled features in `wp-polyfill` as of issue creation</summary>

```
es.array.push
es.array.to-reversed
es.array.to-sorted
es.array.to-spliced
es.array.with
es.map.group-by
es.object.group-by
es.promise.with-resolvers
es.regexp.flags
es.string.is-well-formed
es.string.to-well-formed
es.typed-array.to-reversed
es.typed-array.to-sorted for
es.typed-array.with
web.dom-exception.stack
web.structured-clone
web.url.can-parse
web.url-search-params.delete
web.url-search-params.has
web.url-search-params.size
```

</details>

As far as I can tell, the dependency on `wp-polyfill` comes from [a hardcoded boolean in `tools/webpack/packages.js`](https://github.com/WordPress/gutenberg/blob/trunk/tools/webpack/packages.js#L148):

```js
new DependencyExtractionWebpackPlugin( { injectPolyfill: true } ),
```

This approach is problematic, since it can lead to the fairly large `wp-polyfill` being loaded in the `head` to support simple scripts like `wp-hooks` and `wp-i18n`.

## What is your proposed solution?

At a high level, it seems that `DependencyExtractionWebpackPlugin` should be able to determine on its own whether polyfills are needed, and the `injectPolyfill` configuration option should be dropped (or perhaps turned into an optional override).

Perhaps the plugin could look for `core-js` imports, as it currently does for WordPress ones? Though I'm not sure if it runs before or after Babel.

Alternatively, we could hardcode a list of excluded packages, but that would involve some amount of error-prone maintenance.

CC @gziolo @jsnajdr @tyxla for some ideas! 🙏

### PR DESCRIPTION
**Pull request by sgomes**
## What?
Currently, all packages depend on `wp-polyfill`, even when it's not really needed.

This PR changes that, and automatically determines at build time whether a dependency on `wp-polyfill` is needed, taking usage and browser support into account.

This PR fixes #65216.

## Why?
Packages like `wp-hooks` and `wp-i18n` are often enqueued in the head, which means that their dependencies are placed there as well. `wp-polyfill` is rather large, and so we want to avoid loading it in the critical path whenever possible.

## How?
A new option was added to `packages/babel-preset-default`, that enables adding magic comments.

Enabling this option turns on the babel `useBuiltIns: 'usage'` option, which adds `core-js` imports to the output. These are then transformed by a small plugin into a `/* wp:polyfill */` magic comment instead.

The webpack build then looks for the magic comments, and enables the polyfill dependency if it finds them.

In order to make this PR minimally effective, a new polyfill exclusion was also added, to avoid pedantically polyfilling `Array.prototype.push` due to an obscure bug on some older browsers.

## Testing Instructions
Since this is a build-level change, the best approach is probably to build and smoke-test all of Gutenberg.

In particular, ensure that:
- Packages like `wp-i18n` and `wp-hooks` do not end up depending on `wp-polyfill`
- Packages like `wp-url` and `wp-block-library` *do* end up depending on `wp-polyfill`
- Modules like `interactivity` and `interactivity-router` do not break
- Well, nothing breaks, really! 😄

### Testing Instructions for Keyboard
N/A

### CODE REVIEW

**Comment by sgomes** [comment]
CC @sirreal, who will know how to check that I haven't broken the interactivity packages 🙂

**Comment by sgomes** [comment]
Looking at the Playwright tests, it seems I may have broken the interactivity API after all. Will investigate tomorrow.

File: packages/dependency-extraction-webpack-plugin/lib/util.js [hunk 1]
```diff
@@ -93,6 +93,7 @@ function defaultRequestToExternalModule( request ) {
 	switch ( request ) {
 		case '@wordpress/interactivity-router':
 		case '@wordpress/a11y':
+		case '@wordpress/polyfill':
```
Comment (sirreal) [inline packages/dependency-extraction-webpack-plugin/lib/util.js]: This should probably be in the condition above. `import …` would make it async. `module …` makes it a static import. With a polyfill, it would needs to be evaluated.

But if we don't have a module for this… I'm not sure what to do 😕

File: packages/dependency-extraction-webpack-plugin/lib/index.js [hunk 2]
```diff
@@ -97,6 +97,16 @@ class DependencyExtractionWebpackPlugin {
...
 
 		if ( externalRequest ) {
+			// Special case for modules.
+			// Since `@wordpress/polyfill` is a script and not a module, we need
+			// to exclude it from the list of externalised deps.
+			if (
+				this.useModules &&
+				externalRequest.includes( '@wordpress/polyfill' )
+			) {
+				return callback( null, '' );
```
Comment (sirreal) [inline packages/dependency-extraction-webpack-plugin/lib/index.js]: Is this attempting to ignore the module during when externalizing?

Comment (sgomes) [reply packages/dependency-extraction-webpack-plugin/lib/index.js]: Yes, that's correct! I sneaked this change in today to see if it fixed the tests. If it works, I'll see if I can simplify it later 🙂

**Comment by sirreal** [comment]
I've got a local setup and can help test and debug this. I'm not sure what the quickest way is. It's doable via the playground but the way I'm familiar with requires several setup steps each time.

File: packages/dependency-extraction-webpack-plugin/lib/util.js (hunk 1 above)
Comment (gziolo) [reply packages/dependency-extraction-webpack-plugin/lib/util.js]: One note. As far as I’m aware Interactivity API doesn’t use any polyfills for runtime and router on production. I doubt it ever had it integrated.

**Comment by cbravobernal** [comment]
> CC @sirreal, who will know how to check that I haven't broken the interactivity packages 🙂

Lightbox and router region navigation should work. There are also Interactivity API unit tests.

**Comment by sgomes** [comment]
> Lightbox and router region navigation should work. There are also Interactivity API unit tests.

Thank you @cbravobernal!

**Comment by sgomes** [comment]
Please hold off on reviewing while I investigate the interactivity router breakage. Thank you!

File: packages/dependency-extraction-webpack-plugin/lib/index.js (hunk 2 above)
Comment (gziolo) [reply packages/dependency-extraction-webpack-plugin/lib/index.js]: It looks like it would be necessary to be included somehow for `@wordpress/interactivity-router`.

File: tools/webpack/shared.js [hunk 3]
```diff
@@ -25,7 +25,7 @@ const baseConfig = {
 				parallel: true,
 				terserOptions: {
 					output: {
-						comments: /translators:/i,
+						comments: /(translators|wp):/i,
```
Comment (gziolo) [inline tools/webpack/shared.js]: That's cool how it can get preserved with little effort.

**Comment by gziolo** [comment]
Screenshot 2024-09-13 at 14 21 28

Intriguing, so that needs to be investigated.

**Comment by sgomes** [comment]
> Screenshot 2024-09-13 at 14 21 28
> Intriguing, so that needs to be investigated.

I think we may be preserving some undesired comments:

```
/**
 * Parser function, that converts input HTML into a block based structure.
 *
 * @param {string} doc The HTML document to parse.
 *
 * @example
 * Input post:
 * ```html
 * <!-- wp:columns {"columns":3} -->
 * <div class="wp-block-columns has-3-columns"><!-- wp:column -->
 * <div class="wp-block-column"><!-- wp:paragraph -->
 * <p>Left</p>
 * <!-- /wp:paragraph --></div>
 * <!-- /wp:column -->
 *
 * <!-- wp:column -->
 * <div class="wp-block-column"><!-- wp:paragraph -->
 * <p><strong>Middle</strong></p>
 * <!-- /wp:paragraph --></div>
 * <!-- /wp:column -->
 *
 * <!-- wp:column -->
 * <div class="wp-block-column"></div>
 * <!-- /wp:column --></div>
 * <!-- /wp:columns -->
```

I'll see if I can touch up that comment preservation regex.

File: tools/webpack/shared.js (hunk 3 above)
Comment (sgomes) [reply tools/webpack/shared.js]: Apparently a little more effort is needed, as discussed below 😄

I'll look for `wp:polyfill` explicitly, instead of just `wp:`

Comment (sgomes) [reply tools/webpack/shared.js]: Done.

**Comment by sgomes** [comment]
Everything should be working correctly now, after switching the strategy to magic comments instead of real imports, and rebasing on trunk!

Please take a look when you have a chance!

File: tools/webpack/shared.js [hunk 4]
```diff
@@ -25,7 +25,7 @@ const baseConfig = {
 				parallel: true,
 				terserOptions: {
 					output: {
-						comments: /translators:/i,
+						comments: /(translators:|wp:polyfill)/i,
```
Comment (swissspidy) [inline tools/webpack/shared.js:28]: Does this need to be changed in `packages/scripts/config/webpack.config.js` as well?

Comment (sgomes) [reply tools/webpack/shared.js:28]: I don't think it's necessary unless we want to provide this functionality (automatically marking which files need `wp-polyfill`) to consumers of `@wordpress/scripts`. We would need further changes in order to make that work, though.

File: packages/dependency-extraction-webpack-plugin/lib/util.js (hunk 1 above)
Comment (sgomes) [reply packages/dependency-extraction-webpack-plugin/lib/util.js]: Changing this code shouldn't be necessary anymore. Thanks for the help!

File: packages/dependency-extraction-webpack-plugin/lib/index.js (hunk 2 above)
Comment (sgomes) [reply packages/dependency-extraction-webpack-plugin/lib/index.js]: Right, I think this exposed the fact that while `@wordpress/interactivity-router` doesn't currently depend on the polyfills, it probably should, if we want it to work correctly in older browsers like Chrome 109. Although there isn't really a good mechanism to make that happen, as far as I know 🤔

File: packages/dependency-extraction-webpack-plugin/lib/index.js [hunk 5]
```diff
@@ -278,12 +278,32 @@ class DependencyExtractionWebpackPlugin {
...
+			const hashBuilder = createHash( hashFunction );
+
+			const processContentsForHash = ( content ) => {
+				hashBuilder.update( content );
+			};
+
+			// Prepare to look for magic comments, in order to decide whether
+			// `wp-polyfill` is needed.
+			const processContentsForMagicComments = ( content ) => {
+				if ( content.toString().includes( '/* wp:polyfill */' ) ) {
```
Comment (sirreal) [inline packages/dependency-extraction-webpack-plugin/lib/index.js]: It looks like content is a `Buffer` and [`Buffer` has an `includes` method](https://nodejs.org/api/buffer.html#bufincludesvalue-byteoffset-encoding). Do we need to call `toString`?

```suggestion
				if ( content.includes( '/* wp:polyfill */' ) ) {
```

File: tools/webpack/packages.js [hunk 6]
```diff
@@ -146,7 +146,7 @@ module.exports = {
 	},
 	plugins: [
 		...plugins,
-		new DependencyExtractionWebpackPlugin( { injectPolyfill: true } ),
+		new DependencyExtractionWebpackPlugin( { injectPolyfill: false } ),
```
Comment (sirreal) [inline tools/webpack/packages.js:149]: What do you think of making this configurable?

I understand this would require more setup to work correctly for third parties. 

This would behave like `false` and apply the new behavior of searching for the comment string.

```suggestion
		new DependencyExtractionWebpackPlugin( { injectPolyfill: 'auto' } ),
```

Maybe this isn't necessary, but it would also avoid applying this for third parties when it's not desired or add a path to expose it to third parties in the future.

**Review by sirreal — COMMENTED** [review]
I've looked at this mostly around DEWP, it looks good in general 👍 

I left a few notes I'd like to know your thoughts on.

DEWP also has some decent tests, would you add a test for this behavior?

File: packages/dependency-extraction-webpack-plugin/lib/index.js (hunk 5 above)
Comment (sgomes) [reply packages/dependency-extraction-webpack-plugin/lib/index.js]: That does seem to work! Thanks 🙂

File: tools/webpack/packages.js (hunk 6 above)
Comment (sgomes) [reply tools/webpack/packages.js:149]: I'm happy to make changes, but I think we need to clarify the semantics here. As far as I can tell, what you're looking for is:

- `false`: Don't add polyfills, regardless of the presence of magic comments.
- `true`: Add polyfills, regardless of the presence of magic comments.
- `'auto'`: Add polyfills only when magic comments are present.

Does that sounds about right?

To clarify, note that this is a separate build step to the one that actually adds the magic comments.
`node ./bin/packages/build.js` builds the packages in situ, and `wp-scripts build` is the one that takes each built package from its src directory, extracts the dependencies, and places the results in the top-level `build` dir.

My reasoning for not adding a separate option was that if we didn't want auto polyfilling we probably wouldn't add magic comments in the first build step anyway (the `addPolyfillComments` option), but I'm happy to make changes if we feel it's still best to make this behaviour explicitly opt-in in DEWP as well.

Comment (sirreal) [reply tools/webpack/packages.js:149]: I'm not 100% decided on this… let's leave it as-is.

File: bin/packages/get-babel-config.js [hunk 7]
```diff
@@ -11,6 +11,8 @@ module.exports = ( environment = '', file ) => {
 			name: `WP_BUILD_${ environment.toUpperCase() }`,
 		},
 	};
+	// Add `@wordpress/polyfill` import where needed.
```
Comment (sirreal) [inline bin/packages/get-babel-config.js]: This comment is out of date, the magic comments are added by babel, not the import.

File: packages/babel-preset-default/CHANGELOG.md [hunk 8]
```diff
@@ -2,6 +2,8 @@
 
 ## Unreleased
 
+- Added `addPolyfillComments` option. When used, it will automatically add magic comments to mark files that need `wp-polyfill`.
```
Comment (sirreal) [inline packages/babel-preset-default/CHANGELOG.md:5]: This needs a change type header like `### Internal`.

Does this change the package's behavior in any significant ways for 3rd parties?

File: bin/packages/get-babel-config.js (hunk 7 above)
Comment (sgomes) [reply bin/packages/get-babel-config.js]: Well spotted! Fixed.

File: packages/babel-preset-default/CHANGELOG.md (hunk 8 above)
Comment (sgomes) [reply packages/babel-preset-default/CHANGELOG.md:5]: It changes behaviour in the sense that, when the `addPolyfillComments` option is enabled, any code that goes through this babel config will end up with magic comments. So in that sense it becomes part of the public API for `babel-preset-default`, even though its intended use is only internal.

Do you think the option's name itself should reflect its internal-ness?

Comment (sirreal) [reply packages/babel-preset-default/CHANGELOG.md:5]: `### Internal` was only intended as an example, not a suggestion. We don't need to change the option name, but since this really isn't intended for third parties at the moment, it can go under an `Internal` header.

Comment (sgomes) [reply packages/babel-preset-default/CHANGELOG.md:5]: Done!

**Review by gziolo — COMMENTED** [review]
This is looking close to ready. How much work would it be to add unit tests? For dependency extraction webpack plugin that’s probably easy to copy and adjust an existing test. For Babel, would it be possible and reliable as we would have to use a feature that needs a polyfill but it’s a moving target as the browser support changes.

**Comment by sgomes** [comment]
Thank you for taking a look, @sirreal and @gziolo! I'll see what I can do about those unit tests you both asked for 👍

File: tools/webpack/packages.js (hunk 6 above)
Comment (gziolo) [reply tools/webpack/packages.js:149]: The strategy outlined seems good overall. The question is whether we really want to keep the differences between false and auto? The magic comment gets injected only with custom Babe code. In effect, in WP ecosystem there should never be a case where polyfill gets listed as a dependency outside of Gutenberg and Core. The only exception would be a project that bundles in a custom  way WP packages but it's unlikely they would use the webpack plugin to generate asset files.

Comment (gziolo) [reply tools/webpack/packages.js:149]: That said, should we ever enable magic comments by default in the default Babel preset that WordPress maintains?

**Comment by sgomes** [comment]
@sirreal @gziolo: I added DEWP and babel plugin tests. Please take another look!

**Comment by sgomes** [comment]
Rebased on trunk.

File: packages/dependency-extraction-webpack-plugin/test/fixtures/polyfill-magic-comment/webpack.config.js [hunk 9]
```diff
@@ -0,0 +1,14 @@
...
+ */
+const DependencyExtractionWebpackPlugin = require( '../../..' );
+
+module.exports = {
+	plugins: [
+		new DependencyExtractionWebpackPlugin( {
+			requestToExternalModule( request ) {
+				return request.startsWith( '@wordpress/' );
+			},
+		} ),
```
Comment (sirreal) [inline packages/dependency-extraction-webpack-plugin/test/fixtures/polyfill-magic-comment/webpack.config.js]: I think the plugin with defaults should work fine:

```suggestion
new DependencyExtractionWebpackPlugin(),
```

**Review by sirreal — APPROVED** [review]
:shipit:

**Comment by gziolo** [comment]
This is awesome. Tests look great. Simple yet powerful. Such a pleasure to collaborate on iterations to the build optimizations 😀

**Review by gziolo — APPROVED** [review]

**Comment by sgomes** [comment]
Thank you @sirreal and @gziolo for the review and all the great suggestions! I'll merge once everything goes green 🙂

**Comment by tnke** [comment]
This latest update seems to have broken our block plugins that used the babel preset. The two files being required are nowhere to be found in node_modules, throwing an error:

```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL]: Cannot find module './polyfill-exclusions'
```

Confirmed it by going to `node_modules/@wordpress/babel-preset-default/index.js` and commenting out the two local `require`'s that were recently included and things started building again.

**Comment by gziolo** [comment]
`files` entry needs an update:
https://github.com/WordPress/gutenberg/blob/610aabe26fe113603fece27db5cd2a90a3fe62b4/packages/babel-preset-default/package.json#L27-L30

**Comment by sirreal** [comment]
Thanks for the report @tnke, I'll work on getting a patch release out shortly.

**Comment by sgomes** [comment]
Thank you, everyone, and sorry for missing this 😕

**Comment by sirreal** [comment]
Fix in https://github.com/WordPress/gutenberg/pull/65481.

**Comment by sirreal** [comment]
[8.8.2 is published with the fix](https://www.npmjs.com/package/@wordpress/babel-preset-default/v/8.8.2)

File: tools/webpack/shared.js (hunk 4 above)
Comment (anomiex) [inline tools/webpack/shared.js:28]: I think you could avoid having to preserve the comment through Terser by checking for the "wp:polyfill" comments in the `PROCESS_ASSETS_STAGE_OPTIMIZE_COMPATIBILITY` stage (rather than `PROCESS_ASSETS_STAGE_ANALYSE` as now).

You could pass the "needs polyfill" flag between the two hooks with a map of some sort or by doing something like `compilation.updateAsset( filename, v => v, { wpPolyfill: flag } );` to set it and then `asset.info.wpPolyfill` to check it.

File: tools/webpack/packages.js (hunk 6 above)
Comment (anomiex) [reply tools/webpack/packages.js:149]: > In effect, in WP ecosystem there should never be a case where polyfill gets listed as a dependency outside of Gutenberg and Core

Someone already filed https://github.com/Automattic/jetpack/issues/39452 asking us to do it in Jetpack. 😀

I can't see any reason anyone would have the magic comment and not want the plugin to add the dependency.

File: tools/webpack/shared.js (hunk 4 above)
Comment (gziolo) [reply tools/webpack/shared.js:28]: That would work. It would be a bit more complex, as it would require scanning all the chunks twice. We decided to keep the comment so we don't have to recalculate the hash generated for chunks. It sounds like a good follow up task.

File: tools/webpack/packages.js (hunk 6 above)
Comment (gziolo) [reply tools/webpack/packages.js:149]: It looks like a follow-up is very welcomed 👌

File: tools/webpack/shared.js (hunk 4 above)
Comment (anomiex) [reply tools/webpack/shared.js:28]: > It sounds like a good follow up task.

I'll take that as an invitation. 🙂

https://github.com/WordPress/gutenberg/pull/65582

Comment (gziolo) [reply tools/webpack/shared.js:28]: Awesome, I will have a look when I find some time in the next few days.
