### PR TITLE
Accordion: Add BlockGap support to content & panel

### LINKED ISSUE #71433: Accordion Content, Accordion Panel: blockGap support doesn't work
### Description

The Accordion Content and Accordion Panel blocks have the `spacing.blockGap` field defined, but it doesn't work because the `layout` field is not defined.

### Step-by-step reproduction instructions

- Inset an Accordion block.
- Click the Accordion Content or Accordion Panel block.
- Change the Block Spacing setting.
- The gap style doesn't work.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by yashjawale**
## What?

Closes #71433 

This PR fixes issue of block spacing setting not working for accordion content

## Why?
Currently, changing the value of Block spacing from Inspector doesn't have any effect. Ideally it should add block spacing styles to accordion content

## How?
This PR adds `layout` field to `block.json` for Accordion content & panel so that block spacing setting works
For `accordion-content` block, addtional handling via use of `useSpacingProps` was needed for blockGap changes to reflect
Styling specificity is modified so that the margin applied by blockSpacing settings of AccordionContent block don't affect the spacing when accordions are closed (this one is handled by spacing set by main parent Accordion block) & instead is only utilized for separation between Accordion header & panel.

## Testing Instructions
1. Enable experimental blocks
2. Create a new post or page
3. Insert Accordion block
4. Click the Accordion Content or Accordion Panel block.
5. Change the Block Spacing setting.
6. Observe the changes

### Before

https://github.com/user-attachments/assets/88f8c4bf-d254-4066-927c-bbd2ba1b899f

### After

https://github.com/user-attachments/assets/ca34ee6f-8ea5-4832-afed-7bdb8227ca74

### CODE REVIEW

**Comment by t-hamano** [comment]
Thanks for working on this PR.

In #71454, the extra wrapper div has been removed from the Accordion Panel, so can you rebase this PR on top of trunk and confirm the blockGap support works?

**Comment by yashjawale** [comment]
@t-hamano thanks for notifying about the change 🙌

I've merged the updates & the blockGap support works as expected

https://github.com/user-attachments/assets/2de9bb2f-8ae9-4b13-b08b-55201c08f1f0

File: packages/block-library/src/accordion-content/edit.js [hunk 1]
```diff
@@ -74,6 +73,10 @@ export default function Edit( {
 			className: clsx( blockProps.className, {
 				'is-open': openByDefault || isSelected,
 			} ),
+			style: {
+				...blockProps.style,
+				...spacingProps.style,
+			},
```
Comment (t-hamano) [inline packages/block-library/src/accordion-content/edit.js]: This approach is only necessary if we want to skip serialization of block support or apply styles to elements within a block.

We might take this opportunity to simplify it to:

```javascript
const blockProps = useBlockProps( {
	className: clsx( {
		'is-open': openByDefault || isSelected,
	} ),
} );
const innerBlocksProps = useInnerBlocksProps( blockProps, {
	template: [
		[ 'core/accordion-header', {} ],
		[
			'core/accordion-panel',
			{
				openByDefault,
			},
		],
	],
	templateLock: 'all',
	directInsert: true,
	templateInsertUpdatesSelection: true,
} );
```

File: packages/block-library/src/accordion/style.scss [hunk 2]
```diff
@@ -13,7 +13,7 @@
 	}
 }
 
-.accordion-content__heading {
+:where(.accordion-content__heading) {
```
Comment (t-hamano) [inline packages/block-library/src/accordion/style.scss]: Why is this style necessary in the first place?

File: packages/block-library/src/accordion/style.scss [hunk 3]
```diff
@@ -45,12 +45,17 @@
 	width: 100%;
 }
 
-.is-layout-flow > .wp-block-accordion-panel,
-.wp-block-accordion-panel {
+:where(.is-layout-flow > .wp-block-accordion-panel, .wp-block-accordion-panel) {
```
Comment (t-hamano) [inline packages/block-library/src/accordion/style.scss]: What is the reason for this change?

File: packages/block-library/src/accordion/style.scss [hunk 4]
```diff
@@ -45,12 +45,17 @@
...
 	overflow: hidden;
 	margin: 0;
 }
 
+// Override block spacing for closed accordion panels specifically.
+// Higher specificity to ensure it overrides block spacing margins.
+.wp-block-accordion-content:not(.is-open) > * + .wp-block-accordion-panel {
+	margin-block-start: 0 !important;
+}
```
Comment (t-hamano) [inline packages/block-library/src/accordion/style.scss]: As far as I've tested, I don't understand what this style is trying to fix - what specific problem does it cause?

File: packages/block-library/src/accordion/style.scss (hunk 2 above)
Comment (yashjawale) [reply packages/block-library/src/accordion/style.scss]: This was already present before the change...
I'll check if removing that style causes any visible effect
If that doesn't change anything then the workarounds below won't be needed

File: packages/block-library/src/accordion/style.scss (hunk 3 above)
Comment (yashjawale) [reply packages/block-library/src/accordion/style.scss]: For accordion content block, this rule was preventing the margin from being applied for blockGap to work
This change lowers the specificity so that margin applied by blockGap could work

File: packages/block-library/src/accordion/style.scss (hunk 4 above)
Comment (yashjawale) [reply packages/block-library/src/accordion/style.scss]: When we set blockGap on Accordion content, the margin still remains when the accordion is collapsed
This rule overrides it to zero so that additional margin isn't applied for collapsed accordions (user would use block gap of parent accordion block to set that spacing), so the content block's gap would just affect the spacing between header & panel

File: packages/block-library/src/accordion/style.scss (hunk 3 above)
Comment (t-hamano) [reply packages/block-library/src/accordion/style.scss]: How about just removing `margin: 0` here?

`.wp-block-accordion-panel` is just a div element, so I'm not sure why `margin:0` is necessary in the first place.

Comment (yashjawale) [reply packages/block-library/src/accordion/style.scss]: Yes I'll try finding why was that added
ig removing `margin: 0` shouldn't cause any problems & then the workarounds won't be needed too

File: packages/block-library/src/accordion/style.scss (hunk 4 above)
Comment (t-hamano) [reply packages/block-library/src/accordion/style.scss]: I see, then, how about a selector like this? I'm not sure why aria-hidden is used in the editor and inert on the front end, but maybe we can unify this in a follow-up.

```scss
.wp-block-accordion-panel[inert],
.wp-block-accordion-panel[aria-hidden="true"] {
}
```

**Comment by yashjawale** [comment]
Updated ✅
Removing `margin: 0` did the trick, Thanks!
The rule was added in #64119 itself but couldn't find any clues as to why it was added
Removed the other workarounds revolving around it too

**Review by t-hamano — APPROVED** [review]
LGTM! Everything works as expected 👍
