### PR TITLE
Block Patterns: Override patterns that were registered by Core

### LINKED ISSUE #23996: E2E Tests: Admin - 4 Test Suite fails
**Describe the bug**
On all PRs filed for branches that have been branched off `master` recently, the Admin - 4 Test Suite fails because of a snapshot test ([e.g.](https://github.com/WordPress/gutenberg/runs/877897932)).

**To reproduce**
See above

**Expected behavior**
The test should pass

**Additional context**
The reason for this is probably #23848, which updated button labels in the 'Two Buttons' block pattern (`Button One` became `Get started`, `Button Two` became `Learn more`.). While it did update the snapshot also, pattern registration [doesn't actually register Gutenberg's own 'Two Buttons' block pattern](https://github.com/WordPress/gutenberg/blob/40c6c8f7d1b88ca79f19cadd0c75b34b33803aa8/lib/client-assets.php#L707-L715), as its already present in Core -- [with the 'old' strings](https://github.com/WordPress/wordpress-develop/blob/5b9b012e5304bc4934d9439b4b7337d37f704029/src/wp-includes/block-patterns/two-buttons.php#L10).

I've set priority to High, as this is causing part of the e2e tests to fail for everyone.

cc/ @enriquesanchez @kjellr @mapk @youknowriad

### PR DESCRIPTION
**Pull request by ockham**
## Description

Unconditionally register Gutenberg's block patterns, potentially overriding ones that were registered by Core.

This is to make sure that Gutenberg is using its own block patterns (rather than Core's), since they might have changes that haven't been synced to Core yet.

Specifically, this fixes #23996.

## How has this been tested?

Easiest way: Verify that the "Admin - 4" GH Action goes green.

More difficult: Test locally by using a `.wp-env.override.json` that links to a current WP snapshot (rather than a released version), and run `npm run test-e2e -- packages/e2e-tests/specs/editor/various/adding-patterns.test.js`. Or insert the "Two Buttons" block pattern in the editor, and verify that the default button labels are `Get started` and `Learn more`, rather than `Button One` and `Button Two`.

## Types of changes
Bug fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: lib/client-assets.php [hunk 1]
```diff
@@ -704,13 +704,13 @@ function gutenberg_extend_settings_link_color( $settings ) {
...
+ * Register default patterns, potentially overriding ones that were already registered in Core.
  *
- * This can be removed when plugin support requires WordPress 5.5.0+.
+ * This can be removed when plugin support requires WordPress 5.5.0+, and patterns have been synced back to Core.
  *
  * @see https://core.trac.wordpress.org/ticket/50550
  */
-if ( class_exists( 'WP_Block_Patterns_Registry' ) && ! WP_Block_Patterns_Registry::get_instance()->is_registered( 'text-two-columns' ) ) {
+if ( class_exists( 'WP_Block_Patterns_Registry' ) ) {
 	register_block_pattern( 'core/text-two-columns', gutenberg_load_block_pattern( 'text-two-columns' ) );
```
Comment (ockham) [inline lib/client-assets.php:714]: Implementation note: We don't have to unregister explicitly before re-registering, since the block pattern registry [simply overrides the entry for the pattern with the same name](https://github.com/WordPress/gutenberg/blob/0ac90749e99efe1871dd017fadad25e0ef80cd02/lib/class-wp-block-patterns-registry.php#L31-L63) (it's basically an assoc array).

**Comment by ockham** [comment]
Tests are still failing :confused:  Investigating...

File: lib/client-assets.php (hunk 1 above)
Comment (youknowriad) [reply lib/client-assets.php:714]: That should probably be fixed IMO. I think we should throw an error. (better as a trac ticket now though)

Comment (youknowriad) [reply lib/client-assets.php:714]: It's separate from this PR though

Comment (youknowriad) [reply lib/client-assets.php:714]: The issue in the tests is probably a "timing" issue. This may need to be run on "init".

Comment (ockham) [reply lib/client-assets.php]: d638aef

**Review by youknowriad — APPROVED** [review]
Thanks for the fix
