### PR TITLE
Fix insertion point displaying when there are no inserter items

### LINKED ISSUE #28123: In-between Inserter is Unreliable
Inbetween Inserter

I can get the in-between inserter to appear between _widget areas_, which seems like a mistake.

Also, unless there are multiple widgets in a sidebar area, I'm unable to get the in-between inserter to appear.

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #28123

In locked template areas (and other between blocks places where blocks can't be inserted), the insertion point indicator was still being displayed, though just the blue line without an inserter button.

To solve this, the `isInsertionPointVisible` selector now checks whether the insertion point's root client id has a template lock.

<strike>To solve this, the `InsertionPointPopover` component needs to do its own check for `hasInserterItems` to get around this issue. This matches what the inserter button does:
- https://github.com/WordPress/gutenberg/blob/3c722bf9ab1266a7e29d0aa4e28c21283e7220b9/packages/block-editor/src/components/inserter/index.js#L225
- https://github.com/WordPress/gutenberg/blob/3c722bf9ab1266a7e29d0aa4e28c21283e7220b9/packages/block-editor/src/components/inserter/index.js#L296-L299</strike>

## How has this been tested?
1. In the widget editor, hover between widget areas
2. The insertion point should not be shown

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by talldan** [comment]
Looks like I'll need to revisit this once #31896 is merged, as that removes the isHidden variable this uses.

**Comment by ellatrix** [comment]
> In locked template areas

Could we check the setting directly, instead of inserter items? This component is also being used for drag and drop and could in the future be used for more things like the "Move to" feature.

**Comment by talldan** [comment]
@ellatrix I've reworked this and added a template lock check to the selector.

File: packages/block-editor/src/store/selectors.js [hunk 1]
```diff
@@ -1215,7 +1215,17 @@ export function getBlockInsertionPoint( state ) {
...
+
+	if ( ! state.insertionPoint ) {
+		return false;
+	}
+
+	if ( getTemplateLock( state, insertionPoint.rootClientId ) ) {
+		return false;
+	}
+
+	return true;
```
Comment (ellatrix) [inline packages/block-editor/src/store/selectors.js:1228]: I never know what's the best layer to adjust here. Should we (also or instead) prevent insertion points to be set if the template is locked? And if so, in the component or reducer? I know that in a lot of other places we're doing a lot to prevent actions from even dispatching to the store if we know it won't change anything.

The question is a bit more general, but I think it would be good to see more consistency across the code base.

Comment (ellatrix) [reply packages/block-editor/src/store/selectors.js:1228]: For example, for the block drop zone, we are completely disabling it when the template is locked:

https://github.com/WordPress/gutenberg/blob/05ed04a83eba9aee6e68bb3cdd99bd3a788b6311/packages/block-editor/src/components/use-block-drop-zone/index.js#L125

Comment (ellatrix) [reply packages/block-editor/src/store/selectors.js:1228]: So maybe we should disable the in-between inserter if the template is locked?

**Review by draganescu — APPROVED** [review]
In my testing this fixes all previous issues I noticed in the Widgets editor.
