### PR TITLE
Comment Template: Fix comment pagination with nested replies.

### LINKED ISSUE #37153: Comment Template: Optimize the way pagination is handled for comments with replies
## What problem does this address?

Originally raised by @michalczaplinski in https://github.com/WordPress/gutenberg/pull/36065#issuecomment-955097061 while working on the support for comments with replies:

> I wonder what the best UX here should be. Like I mention in the video, if this setting is set:
> 
> Screen Shot 2021-10-29 at 18 16 04
> 
> we cannot easily fetch the X top level comments AND it's replies.

The extended version of the issue is explained in the video included:

https://user-images.githubusercontent.com/5417266/139510408-bb141fdc-9716-4bc6-9e04-73a64e9b0686.mov

The initial approach taken in #36065 looks like the following:

https://github.com/WordPress/gutenberg/blob/93393d09e89ba9cc13bcce7b83cc4c85620ace5b/packages/block-library/src/comment-template/edit.js#L141-L148

This fetches all comments (unless there is a limit enforced on the endpoint that would be another issue) and then constructs a tree structure representing top-level comments and their replies. The drawback is that we fetch comments that we might never use if the number of the top-level comments is higher than the number of comments per page. Another concern would be that we might want to be able to use different sorting or offset and it all should play along nicely. 

## What is your proposed solution?

Now the question is whether there is a way to use `per_page`, `offset`, and `hierarchical` params to have better control over the data fetched from the server in a way that we don't have to recreate the tree structure modeled on the server.

### PR DESCRIPTION
**Pull request by DAreRodz**
## Description

Closes #37153

Improve the Comment Template block to simplify pagination handling when nested comments are active. It uses both the WordPress discussion settings and the block props.

The implementation extends the REST API to mark comment children as 'embeddable', and only shows two levels of nested comments. Showing more than two levels will be addressed in another PR.

There are some bugs that should be addressed as well (I'll open issues for them):

- `Comments-Pagination-Next` and  `Comments-Pagination-Previous` blocks are using WP functions that use the WP Discussion Settings under the hood, rendering a wrong link when the default page attribute of the Comment Loop block doesn’t coincide with the corresponding WP setting.
- When nested comments are disabled, replies are rendered in the root of the comment tree and again as children of their respective parent.

## How has this been tested?

**Editor, with context**

https://user-images.githubusercontent.com/6917969/153957102-fa9ab21e-7264-47ed-b2e0-cc3c184332bf.mov

**Editor, without context**

https://user-images.githubusercontent.com/6917969/153957145-83c6a6df-dd23-42fe-8855-7f7fd481426e.mov

## Types of changes
- Enhancement

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by DAreRodz** [comment]
Hey, just a quick update here. Things are not properly working yet --there are some discrepancies between the editor and the frontend versions--, but these are some things I've done so far:

- When comments are fetched from the REST API, they come with children embedded. The code responsible for that is included in the `/lib/compat/experimental/blocks.php` file. BTW, I have a gut feeling that this code can be improved.
   https://github.com/WordPress/gutenberg/blob/510eea6f34c82441c382c104c3935898d5998944/lib/compat/experimental/blocks.php#L120-L139
 
- I've created a hook called [`useCommentsQueryArgs`](https://github.com/WordPress/gutenberg/blob/aa4cd79a8dc773b1aa3aa01c5930b72ed552d0cc/packages/block-library/src/comment-template/hooks.js#L10-L59), which is kind of the same function as [`build_comment_query_vars_from_block`](https://github.com/WordPress/gutenberg/blob/510eea6f34c82441c382c104c3935898d5998944/lib/compat/experimental/blocks.php#L8-L97), but in React. It generates the new query vars for the REST API depending on the different attributes of the block. There is a tricky thing with the `default_comments_page` option, though. Depending on the value of this option, the block needs to request either the first (newest) or the last (oldest) page of comments. In the second case, the only way to know the index of the last page is to make a previous request and read the `X-WP-TotalPages` header of the response. For this purpose, I created a hook called [`useDefaultPage`](https://github.com/WordPress/gutenberg/blob/aa4cd79a8dc773b1aa3aa01c5930b72ed552d0cc/packages/block-library/src/comment-template/hooks.js#L61-L107) that returns the correct index once it is fetched.

- I've also added a new attribute to the Comments Query Loop block to manually set the `default_comments_page` setting. To handle that setting in the Comment Template when it is rendered in the editor.

Again, this is not working yet, I messed up something with the comments order, but it's not far from working. 😄 

And I still have to add a "show more" button if users want to show more than 2 levels of nested comments, still figuring out a proper way of doing so.

**Comment by michalczaplinski** [comment]
I ll have a deeper look tomorrow, but awesome work so far! 🚀

**Comment by DAreRodz** [comment]
Oh, after some investigation, I think we are not using the `comment_order` option correctly. 🕵️ 

That option does not define the order in which the comments should be *queried*, but *shown* in the comment list. Looking at what the PHP template does, inside the `wp_list_comments` function, `comment_order` is assigned to a property named `reverse_top_level`, which is passed to the "walker" that generates the comment tree.

[/wp-includes/comment-template.php#L2238-L2240](https://github.com/WordPress/WordPress/blob/a3a61c5a3e564656dcebb9691f5a9857a63ca24a/wp-includes/comment-template.php#L2238-L2240)

```php
	if ( null === $parsed_args['reverse_top_level'] ) {
		$parsed_args['reverse_top_level'] = ( 'desc' === get_option( 'comment_order' ) );
	}
```

The `reverse_top_level` property (if defined) is used later to just reverse the top level comments.

[/wp-includes/class-wp-walker.php#L361-L362](https://github.com/WordPress/wordpress/blob/a3a61c5a3e564656dcebb9691f5a9857a63ca24a/wp-includes/class-wp-walker.php#L361-L362)

```php
		if ( ! empty( $args[0]['reverse_top_level'] ) ) {
			$top_level_elements = array_reverse( $top_level_elements );
```

Using `comment_order` as the `order` argument of `WP_Comments_Query`(what we are doing) don't reverse the top comments, reverses all the comments before pagination, so it reverses the pages as well.

**Comment by gziolo** [comment]
> Oh, after some investigation, I think we are not using the comment_order option correctly. 

Yes, you might be correct. There was always something off when I was testing it in the past 🙈 

Screenshot 2022-02-02 at 12 42 31

Does it mean that `last` vs `first` setting is what translates to `asc` vs `desc`. `older` vs `newer` would change the sorting on the individual page. Super complicated. How we didn't get it earlier together with @c4rl0sbr4v0 😅

**Comment by cbravobernal** [comment]
> Does it mean that last vs first setting is what translates to asc vs desc. older vs newer would change the sorting on the individual page. Super complicated. How we didn't get it earlier together with @c4rl0sbr4v0 😅

Maybe one reason could be this:
In `wp-includes/comment-template.php` last/first is only used to set the query page. Not related with `asc` or `desc`

`$parsed_args['page'] = ( 'newest' === get_option( 'default_comments_page' ) ) ? get_comment_pages_count( $_comments, $parsed_args['per_page'], $threaded ) : 1;`

Anyway, I completely missed the `reverse_top_level` attribute. This comments settings are crazy 😆

File: packages/block-library/src/comment-template/edit.js [hunk 1]
```diff
@@ -114,68 +114,73 @@ const CommentsList = ( {
...
+	order = order || commentOrder;
+
+	// Reverse the order of top comments if needed, as specified in the
+	// Discussion settings. NOTE that this only changes the order of comments in
+	// the given page, not the order of pages.
+
+	// Generate a tree structure of comment IDs.
+	const { commentTree } = useCommentTree(
+		order === 'desc'
+			? topLevelComments?.slice().reverse()
```
Comment (ockham) [inline packages/block-library/src/comment-template/edit.js]: Minor note, I think we typically prefer array spread over `.slice()` for copying:

```suggestion
			? [ ...topLevelComments ].reverse()
```

(Not that it's a hard-and-fast rule 😅 )

It would look a bit less nice if we have to take care of the `null` case, but maybe we can move the `commentTree` definition below the [early return](https://github.com/WordPress/gutenberg/pull/38187/files?diff=split&w=0#diff-885985bee90d7d51f079b99d59d8562cba40b4a6f64258e86fc81b0dc0f11b87R169-R175)?

Comment (DAreRodz) [reply packages/block-library/src/comment-template/edit.js]: Yeah, sure! The only reason I opted for that syntax was that `topLevelComments` could not exist, but I can refactor the code to avoid that case. I prefer array spread as well. 😆

File: packages/block-library/src/comment-template/hooks.js [hunk 2]
```diff
@@ -0,0 +1,142 @@
...
+ * @return {Object} TODO Write JSDOC.
+ */
+export const useCommentTree = ( topLevelComments ) => {
+	const commentTree = useMemo(
+		() =>
+			topLevelComments?.map( ( { id, _embedded } ) => {
+				const [ children ] = _embedded?.children || [];
+				return {
+					commentId: id,
+					children: children?.map( ( child ) => ( {
```
Comment (michalczaplinski) [inline packages/block-library/src/comment-template/hooks.js]: Nitpick: no need for the `?.` - `children` is never falsy because of the `_embedded?.children || [];` above.

**Review by michalczaplinski — COMMENTED** [review]
Awesome work @DAreRodz ! 👏

Just tested it and it works well! Do you have an idea on how you want to handle comments more than 2 levels deep?

**Comment by DAreRodz** [comment]
> Do you have an idea on how you want to handle comments more than 2 levels deep?

Not yet, I haven't figured out a good way to solve that. Any idea is more than welcome. 😄

**Comment by DAreRodz** [comment]
### Status update

- In the editor, the comments are requested with `_embed: true`. That makes the children of top-level comments to be included in the response, using a single REST API call.

- In the frontend, I fixed some inconsistencies while showing paginated comments using either the block attributes or the WP options (through the `comments/inherit` attribute). Those issues were not only in the Comment Query Loop block, but in the Comment Pagination Numbers and Comment Pagination Next blocks as well, and [one of the issues](https://github.com/WordPress/gutenberg/pull/38187#issuecomment-1027367501) was a bit sneaky.

- I still have to make all the tests pass, ensure that everything works as expected, and come up with an idea to show more than 2 levels of nested comments in the editor.

**Comment by cbravobernal** [comment]
> * and come up with an idea to show more than 2 levels of nested comments in the editor

Maybe you prefer to open a new issue just for that improvement. That way we can land the comment pagination improvement.

**Comment by DAreRodz** [comment]
> Maybe you prefer to open a new issue just for that improvement. That way we can land the comment pagination improvement.

Oh yes, that would be better than waiting for that _idea_ to be implemented and tested before merging these changes. 💯

File: packages/block-library/src/comments-query-loop/edit/comments-inspector-controls.js [hunk 3]
```diff
@@ -21,10 +21,20 @@ const orderOptions = [
...
+	{
+		label: __( 'Newest' ),
+		value: 'newest',
+	},
+	{
+		label: __( 'Oldest' ),
+		value: 'oldest',
+	},
+];
+
```
Comment (cbravobernal) [inline packages/block-library/src/comments-query-loop/edit/comments-inspector-controls.js:34]: Right now on Discussion Settings say:
Last or First page to display by default.

This could make confusion to the user, although, to be honest, Discussion settings are also confusing 😓 

How could we improve the naming?

cc: @jasmussen @jameskoster

Comment (DAreRodz) [reply packages/block-library/src/comments-query-loop/edit/comments-inspector-controls.js:34]: I have the same feeling. I ended using `oldest` and `newset` because those are the values used internally, but I'm not sure which option is clearer from the user's perspective. For me, it's like using `first` or `last` instead would be equivalent, although it doesn't give you information about what comments are going to be shown (`oldest` comments are in the `first` or the `last` page? 🤷 ).

Comment (jasmussen) [reply packages/block-library/src/comments-query-loop/edit/comments-inspector-controls.js:34]: Took it for a spin:
comments

I don't see any "Last or First page to display by default" on this page:

Screenshot 2022-02-16 at 09 04 03

Am I looking in the wrong place?

Right now it says "Default page", that seems okay to me. It's not super clear, but it's also a rare change to tweak. I'd be happy to start simple and then we can rephrase if it becomes necessary, for example to add help text.

Comment (gziolo) [reply packages/block-library/src/comments-query-loop/edit/comments-inspector-controls.js:34]: It's all very confusing because and I'm still not sure how it exactly works 🤣 

I think it's the following:
1. When you select the `last` page displayed by default then you sort all top-level comments by date where the newest comments are on the first page.
2. When you select the `older` comments at the top of each page, then it reverses the order of comments but only on individual pages.

So maybe we should have:
1. Order pages by...
2. Order items on the page by...

Comment (jameskoster) [reply packages/block-library/src/comments-query-loop/edit/comments-inspector-controls.js:34]: Is it definitely necessary that a single comment loop can override the global discussion settings? 🤔  Comments are a fairly universal concept – doesn't it seem unlikely that a site would want a different treatment between post and page comments? 

I worry that this could encourage folks to customise all comment loops, at which point the global settings don't actually do anything. That could lead to some confusing UX. 

If we're committed to this change, should we update the language on the global discussion settings to clarify that the ordering and default page options are _defaults_, and might be overwritten by the theme / template?

Comment (DAreRodz) [reply packages/block-library/src/comments-query-loop/edit/comments-inspector-controls.js:34]: > I don't see any "Last or First page to display by default" on this page:

@jasmussen it's kind of hidden. 😅 🙈 

Screenshot 2022-02-16 at 11 28 38

> So maybe we should have:
> 
> 1. Order pages by...
> 2. Order items on the page by...

Yup @gziolo, that would be more clear than we have now, it would be nice to have an option to change the order of pages as well. 🙂

AFAIK, WP settings don't allow you to change the _pages_ order, just the _items_ order on each page, which is what you select when you choose between _newer_ or _older_ comments at the top of each page. For that reason, the _first_ page was always the _oldest_ comments and the _last_ page the _newest_ ones.

I think it is clearer with this diagram:

image

BTW, the option that is set internally when you choose between _newer_ or _older_ comments at the top of each page is [`comment_order`](https://codex.wordpress.org/Option_Reference), but the possible values for that option are `asc` or `desc` 😅, and can be confused with the `order` param you can pass to [`WP_Comment_Query`](https://developer.wordpress.org/reference/classes/wp_comment_query/__construct/), which also changes the pages order, so `comment_order` and `order` are not equivalent (I know, it's really confusing 😓).

Comment (DAreRodz) [reply packages/block-library/src/comments-query-loop/edit/comments-inspector-controls.js:34]: > Comments are a fairly universal concept – doesn't it seem unlikely that a site would want a different treatment between post and page comments?

You're right, although it would be great to also consider other cases, like adding a list of “latest comments” somewhere in your page, or “top comments”, or whatever…

Well, now I'm not sure if it would be better to create custom blocks for those specific cases. 🤔 

> If we're committed to this change, should we update the language on the global discussion settings to clarify that the ordering and default page options are _defaults_, and might be overwritten by the theme / template?

Wouldn't it be simpler if we warn in the block settings that you're overwriting the global discussion settings? Just asking, I don't have any strong opinion here. 😄

Comment (jasmussen) [reply packages/block-library/src/comments-query-loop/edit/comments-inspector-controls.js:34]: > You're right, although it would be great to also consider other cases, like adding a list of “latest comments” somewhere in your page, or “top comments”, or whatever…

That's a good point, even held up against Jay's also excellent point. A few thoughts:

* Perhaps the toggle should be renamed "Inherit discussion settings", and we add help-text below that says something like "Use globally defined sort order and comment settings. You can configure these in [link]Discussion Settings[/link]".
* We start with less: perhaps we start with just "Items per page", and then instead of _two_ options for oldest vs. newest, we make a single toggle: "Show newest comments first", untoggled by default. We'd then use this setting for both "Order by" and "Default page". 

Keeping in mind we can always make it more granular as we go, it seems like this might also be an opportunity to simplify.

File: packages/block-library/src/comments-pagination-next/block.json [hunk 4]
```diff
@@ -12,7 +12,13 @@
...
 		}
 	},
-	"usesContext": [ "postId", "comments/perPage", "comments/paginationArrow" ],
+	"usesContext": [
+		"postId",
+		"comments/perPage",
+		"comments/order",
+		"comments/inherit",
+		"comments/defaultPage"
+	],
```
Comment (cbravobernal) [inline packages/block-library/src/comments-pagination-next/block.json:22]: "comments/paginationArrow" is missing 😅

Comment (DAreRodz) [reply packages/block-library/src/comments-pagination-next/block.json:22]: Nice catch @c4rl0sbr4v0, it's fixed now. ✅

**Review by cbravobernal — APPROVED** [review]
It looks good to me. There is some discussion to approach, but I think the PR is improving the behaviour of comments, and we could address the conversation of settings in smaller PRs.

File: packages/block-library/src/comments-query-loop/edit/comments-inspector-controls.js (hunk 3 above)
Comment (DAreRodz) [reply packages/block-library/src/comments-query-loop/edit/comments-inspector-controls.js:34]: > * [...] and we add help-text below that says something like "Use globally defined sort order and comment settings. You can configure these in [link]Discussion Settings[/link]".

That's great, I really like that suggestion. 😊 

> * [...] we make a single toggle: "Show newest comments first", untoggled by default. We'd then use this setting for both "Order by" and "Default page".

Yup, that would be simpler from the user perspective, and we can always add more features/complexity in the future.

I don't mind creating new PRs to address these changes, if we all agree on that. 👀

cc @gziolo @jameskoster @c4rl0sbr4v0 @michalczaplinski

Comment (jameskoster) [reply packages/block-library/src/comments-query-loop/edit/comments-inspector-controls.js:34]: > Well, now I'm not sure if it would be better to create custom blocks for those specific cases.

Yes I considered things like Reviews in WooCommerce as well (which are just WP comments). They feel like variations of the comment query block to me. Similar to how the "Posts List" block is a variation of the Query block.

> Wouldn't it be simpler if we warn in the block settings that you're overwriting the global discussion settings?

I don't think so, from the UX perspective. To be clear I'm thinking of the other side of this flow. Consider an end user who installs a theme that elects not to inherit the global settings in each instance of the comment query loop block. When that user customises options in the global discussion settings, their changes will not be reflected on the frontend, and they will have no feedback explaining why.

Comment (DAreRodz) [reply packages/block-library/src/comments-query-loop/edit/comments-inspector-controls.js:34]: > Consider an end user who installs a theme that elects not to inherit the global settings in each instance of the comment query loop block. When that user customises options in the global discussion settings, their changes will not be reflected on the frontend, and they will have no feedback explaining why.

That's a good point, I haven't thought of that. 🤔 

I think it's better to continue this conversation in a different issue, I've created one: https://github.com/WordPress/gutenberg/issues/38864
