### PR TITLE
Fix Template Part renaming error.

### LINKED ISSUE #24000: Attempting to rename Template Part deletes Template Part
**Describe the bug**

When trying to edit the template part name, the entire template section is removed. cc @epiqueras since this _might_ be resolved with your PR https://github.com/WordPress/gutenberg/pull/23661

**To reproduce**
1. Enable Full Site Editing and the demo content.
2. Head to Site Editor (beta) tab.
3. Try to edit the template part name
4. The entire template part will be removed.

**Expected behavior**

I expected the template part to be renamed.

**Screenshots**

Here's a video of me walking through this (44 seconds): https://cloudup.com/cc_RpdQWy8F

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 8.5.1

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 83.0.4103.116

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

Fixes #24000 by using ensuring the `postId` attribute is set on the block when we update the `slug`.

## How has this been tested?

Load a fresh template part supplied by the theme and attempt to rename it.  
Verify it does not disappear from the screen.
Verify saving works as expected.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-library/src/template-part/edit/index.js [hunk 1]
```diff
@@ -23,7 +23,11 @@ export default function TemplatePartEdit( {
 	const initialTheme = useRef( theme );
 
 	// Resolve the post ID if not set, and load its post.
-	const postId = useTemplatePartPost( _postId, slug, theme );
+	const postId = useTemplatePartPost(
+		_postId,
+		initialSlug.current,
+		initialTheme.current
+	);
```
Comment (Addison-Stavlo) [inline packages/block-library/src/template-part/edit/index.js:30]: In `useTemplatePartPost` the slug and theme are only used where no ID is available.  It only makes sense to use the initialSlug and initialTheme values for this hook, as using the current `slug` attribute was causing the template part to disappear when renamed before saving and having an Id.

**Comment by noahtallen** [comment]
> Saving can replace with a different auto-drafted template part by the same slug when:
> - The template has never been saved.
> - Or the template and unsaved template part are saved at the same time.

 I'm a little confused by this. Is this the scenario?
- there is an existing template part with a specific slug (say, `header`) that is in autodraft
- you try to rename this other template part to `header` (?)
- it starts using that first template part instead of the one you want

**Comment by noahtallen** [comment]
Ah I think I understand more testing it out. Now, when you rename it to anything and then save changes, it seems to switch the template part back to whatever it was looking at previously, which causes some UI jankiness, and then it references the old name. But after refreshing, the new name shows up correctly.

File: packages/block-library/src/template-part/edit/index.js (hunk 1 above)
Comment (Addison-Stavlo) [reply packages/block-library/src/template-part/edit/index.js]: Reverted this as part of the new changes.

File: packages/block-library/src/template-part/edit/index.js [hunk 2]
```diff
@@ -24,6 +24,9 @@ export default function TemplatePartEdit( {
 
 	// Resolve the post ID if not set, and load its post.
 	const postId = useTemplatePartPost( _postId, slug, theme );
+	useEffect( () => {
+		setAttributes( { postId } );
+	}, [ postId ] );
```
Comment (Addison-Stavlo) [inline packages/block-library/src/template-part/edit/index.js:29]: This seems to fix it.  However, it means that when we first load a template supplied by a theme, the template and all of its template parts will be marked as 'dirty' immediately since they have all been given explicit `postId`s.  I dont think this is necessarily bad behavior, just different than before. 🤔

Comment (noahtallen) [reply packages/block-library/src/template-part/edit/index.js:29]: interesting. I think this behavior also existed at some point in the past (I think @epiqueras changed that somehow)

Comment (epiqueras) [reply packages/block-library/src/template-part/edit/index.js:29]: I don't think this behavior is acceptable. We made an effort to remove it because it's confusing.

Comment (Addison-Stavlo) [reply packages/block-library/src/template-part/edit/index.js:29]: > We made an effort to remove it because it's confusing.

True, definitely confusing if we are prompting the user to save changes to something they haven't made changes to.  🤔

Comment (Addison-Stavlo) [reply packages/block-library/src/template-part/edit/index.js]: Alternative idea - 61fa1bf - also set the `postId` attribute in the name-panel when the slug is changed.  This will prevent it from disappearing when renamed, allow the template to dirty to save the proper id for its child, and not give us any issues with dirty loading. 🤔

Comment (ZebulanStanphill) [reply packages/block-library/src/template-part/edit/index.js]: I think there needs to be a clear distinction between Template Parts that are being referenced from the theme, and those that are customized by the user. Because once you start editing a Template Part, you're actually editing a newly-created duplicate, not the one from the theme. If your theme updates, the Template Part won't change with it, because you're no longer using the theme's version of the Template Part. But this is never conveyed clearly to the user.

I think theme-provided Template Parts should be in a sort of "read-only" mode by default, with an explicit "Customize/Edit" button that, when pressed, will copy it and create the editable version. Right now it's not clear at all whether a Template Part is still being referenced from a theme or not, and I think this is the source of a lot of the confusing behavior/logic.

Comment (noahtallen) [reply packages/block-library/src/template-part/edit/index.js]: That makes sense to me for sure. Imo, we can move forward with the fixes here, and then come up with a design for that interaction as well.

**Review by noahtallen — APPROVED** [review]
Nice! This works perfectly to fix the issue in my testing without causing other side effects.

I think we should totally follow up to address @ZebulanStanphill's concerns about template parts coming from themes.

File: packages/block-library/src/template-part/edit/index.js (hunk 2 above)
Comment (Addison-Stavlo) [reply packages/block-library/src/template-part/edit/index.js]: > If your theme updates, the Template Part won't change with it

I could be wrong, but now that you mention this I think this may still be the case even if the user has not edited the template part?  On first use an auto-draft is created from the theme's .html files with the slug name, that is what is being used by the editor.  If the auto-draft with that slug/theme already exists, I don't think we create a new one and overwrite it.  So if the themes template part .html is updated, the editor would still be looking for the auto-draft by slug which was created with the outdated version. 🤔

Comment (ZebulanStanphill) [reply packages/block-library/src/template-part/edit/index.js]: > I think if we handle it this way for template parts we should probably do the same for templates as well?

Yes, that sounds like the right behavior to me.
