### PR TITLE
Adapt the height of the block preview container to its content

### LINKED ISSUE #20692: Patterns: The pattern preview should adjust height depending on actual height of pattern
**Describe the bug**
The Pattern Previews cut off some of the patterns making it difficult to determine if that pattern is what the user wants.

**To reproduce**
1. Click the Pattern sidebar icon.
2. Observe the "Natural Columns" preview.
3. Notice that it is cut off.

**Expected behavior**
The preview height should adjust to show the whole pattern.

**Screenshots**

**The Natural Columns pattern is cut off**

Screen Shot 2020-03-06 at 12 35 41 PM

cc @youknowriad @enriquesanchez

### PR DESCRIPTION
**Pull request by youknowriad**
closes #20692

This PR adds a new mode to the BlockPreview component called "auto-height" where instead of relying on a fixed height, the height is computed based on the content of the preview.

This preview mode is used in the patterns preview and I'll explore using for the inserter separately.

Capture d’écran 2020-03-09 à 11 09 50 AM

### CODE REVIEW

**Comment by mtias** [comment]
This is working a lot better:

image

**Comment by mtias** [comment]
The "List" one looks a bit rough:

image

File: packages/block-editor/src/components/block-preview/index.js [hunk 1]
```diff
@@ -2,209 +2,70 @@
...
-			<ScaledBlockPreview
-				key={ recompute }
-				blocks={ renderedBlocks }
-				viewportWidth={ viewportWidth }
-				padding={ padding }
-				onReady={ __experimentalOnReady }
-				scalingDelay={ __experimentalScalingDelay }
-			/>
+			{ autoHeight ? (
+				<AutoHeightBlockPreview viewportWidth={ viewportWidth } />
```
Comment (retrofox) [inline packages/block-editor/src/components/block-preview/index.js]: does not autoHeight mode depend on the content?

Comment (youknowriad) [reply packages/block-editor/src/components/block-preview/index.js]: yes but that's provided by the BlockEditorProvider store.

**Comment by youknowriad** [comment]
@mtias that list issue should be in master too right?

File: packages/block-editor/src/components/block-preview/auto.js [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+/**
+ * Internal dependencies
+ */
+import BlockList from '../block-list';
+
+function AutoBlockPreview( { viewportWidth } ) {
+	const [
+		containerResizeListener,
+		{ width: containerWidth },
+	] = useResizeAware();
```
Comment (retrofox) [inline packages/block-editor/src/components/block-preview/auto.js]: Nice hook. Maybe `ScaledBlockPreview` should be aware or resizing, too.

File: packages/block-editor/src/components/block-preview/index.js (hunk 1 above)
Comment (retrofox) [reply packages/block-editor/src/components/block-preview/index.js]: yes, but wondering if it should add the recompute key also to the  `< AutoHeightBlockPreview />` in order to force the rendering when it triggers a recomputation.

Comment (youknowriad) [reply packages/block-editor/src/components/block-preview/index.js]: Makes sense

File: packages/block-editor/src/components/block-preview/auto.js (hunk 2 above)
Comment (youknowriad) [reply packages/block-editor/src/components/block-preview/auto.js]: Yeah potentially. Thought, I would like to see if we could use the new preview everywhere. Maybe there are better ways to center vertically...

**Review by mtias — APPROVED** [review]

**Comment by aduth** [comment]
#19918 was in development at the same time as this and since merged. I updated the component here in #20889 to use it.
