### PR TITLE
Global Styles: Fix palette color popovers

### LINKED ISSUE #41894: Unable to select colors on small screens
### Description

On small screens, the color palette popover is hidden.

### Step-by-step reproduction instructions

On a small screen:

1. Select a block that can have colors applied, like Paragraph
2. Open the Inspector (⇧⌘,)
3. In the Color panel, click one of the buttons
4. Observe that no color palette is revealed

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/846565/175257052-55c1faa6-b450-4e2a-9a9b-428f61441822.mp4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #49040: PaletteEdit: ColorPicker popover position can't be changed
## What problem does this address?

When clicking on a color swatch, the ColorPicker popover opens to the left side of the component with a 20px offset. This positioning is coupled to the block editor sidebar and cannot be changed.

https://user-images.githubusercontent.com/555336/224762107-41e59d71-4f62-4c7a-92fb-5b2be0ec292c.mp4

https://github.com/WordPress/gutenberg/blob/a2e91a4ebe3c1b80f32f75b76c688d8e0f1532d5/packages/components/src/palette-edit/index.js#L99-L101

In Storybook, the result looks glitchy:

https://user-images.githubusercontent.com/555336/224762257-1402808a-0ab3-4455-b533-7fddad5f920c.mp4

## What is your proposed solution?

The popover positioning should not be coupled to the block editor.

Related: All the components with the `__experimentalIsRenderedInSidebar` prop.

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Fixes: https://github.com/WordPress/gutenberg/issues/41894
Fixes: https://github.com/WordPress/gutenberg/issues/49040

## What?

- Adds the ability to pass Popover props through to the palette color pickers
- Updates the color palette panel to pass through alternative popover props when on small viewports

## Why?

- Without at least the `shift` prop on the palette color pickers they are rendered outside the viewport on smaller screens
- If only `shift` is added to the palette color pickers they overlay the individual color elements that triggered them, adding the ability to pass through popover props will allow for fine-tuning the positioning of the popovers in a follow up.

## How?

- Adds popover props to the `ColorPickerPopover`
- Plumbs through popover props for the `PaletteEdit` component
- Leverages `useViewportMatch` and  the new `popoverProps` to tweak the palette popovers when on small viewports

## Next Steps

In a follow-up, we can refine the popover placement, including which elements they may be anchored to.

## Testing Instructions

1. In the Site Editor, navigate to Global Styles > Colors > Palette
2. Confirm the placement of popovers for theme, default, and custom palettes
3. Resize to a small viewport and confirm the palette popovers all appear within the viewport

## Screenshots or screencast 

| Before | After |
|---|---|
| <video src="https://user-images.githubusercontent.com/60436221/233541102-55c67b1b-15bc-4668-9972-5cb6344d3c97.mp4" /> | <video src="https://user-images.githubusercontent.com/60436221/233541121-b39e4aa3-9736-471a-b4d8-7efaf020ca91.mp4" /> |

### CODE REVIEW

**Comment by aaronrobertshaw** [comment]
@ciampo or @mirka if you have time, could you please sanity-check the approach here? I'm sure the typing can be improved but I was mostly interested in getting something that worked together first.

**Review by mirka — COMMENTED** [review]
Nice! I'm assuming this will also close #49040?

The approach looks good to me, and perhaps would be the same approach to take to remove all the `__experimentalIsRenderedInSidebar` props in the codebase.

**Comment by aaronrobertshaw** [comment]
Thanks for the sanity check and the related issue link @mirka 👍 

This PR should address https://github.com/WordPress/gutenberg/issues/49040. I've tweaked the `PaletteEdit` story's default args so the popover will be displayed ok in Storybook.


https://user-images.githubusercontent.com/60436221/233879628-6025dea6-92d1-4b1f-9b20-6bc7cf8a7b4a.mp4

> The approach looks good to me, and perhaps would be the same approach to take to remove all the __experimentalIsRenderedInSidebar props in the codebase.

This might be something I could help chip away at in follow-ups.

File: packages/components/src/palette-edit/index.tsx [hunk 1]
```diff
@@ -106,13 +112,20 @@ function ColorPickerPopover< T extends Color | Gradient >( {
...
+		placement: 'left-start',
+		...receivedPopoverProps,
+	};
+
 	return (
 		<Popover
-			placement="left-start"
-			offset={ 20 }
 			className="components-palette-edit__popover"
+			{ ...popoverProps }
```
Comment (mirka) [inline packages/components/src/palette-edit/index.tsx]: Should we merge the `className` with the one that could be in `receivedPopoverProps`?

File: packages/components/src/palette-edit/index.tsx [hunk 2]
```diff
@@ -154,17 +167,31 @@ function Option< T extends Color | Gradient >( {
...
+	// re-renders when the popover's anchor updates.
+	const [ popoverAnchor, setPopoverAnchor ] = useState( null );
+	const popoverProps = useMemo(
+		() => ( {
+			...receivedPopoverProps,
+			// Use the custom palette color item as the popover anchor.
+			anchor: popoverAnchor,
+		} ),
+		[ popoverAnchor, receivedPopoverProps ]
+	);
```
Comment (mirka) [inline packages/components/src/palette-edit/index.tsx:192]: Is it worth the memoizing overhead when we don't even pass a stable props object in our own app? (in `color-palette-panel.js`)

File: packages/components/src/palette-edit/types.ts [hunk 3]
```diff
@@ -85,7 +86,9 @@ type PaletteEditGradients = {
 };
 
 export type PaletteEditProps = BasePaletteEdit &
-	( PaletteEditColors | PaletteEditGradients );
+	( PaletteEditColors | PaletteEditGradients ) & {
+		popoverProps?: Omit< PopoverProps, 'children' >;
```
Comment (mirka) [inline packages/components/src/palette-edit/types.ts]: I feel like `popoverProps` should be part of the `BasePaletteEdit` type object, no?

Also, let's add a description for the docs, for example:

```ts
	/**
	 * Props to pass through to the underlying Popover component.
	 */
	popoverProps?: Omit< PopoverProps, 'children' >;
```

File: packages/components/src/palette-edit/types.ts [hunk 4]
```diff
@@ -94,6 +97,7 @@ export type ColorPickerPopoverProps< T extends Color | Gradient > = {
 	onChange: ( newElement: T ) => void;
 	isGradient?: T extends Gradient ? true : false;
 	onClose?: () => void;
+	popoverProps?: Omit< PopoverProps, 'children' >;
```
Comment (mirka) [inline packages/components/src/palette-edit/types.ts]: Maybe worth DRYing these a little — so `popoverProps?: PaletteEditProps[ 'popoverProps' ]`

**Review by mirka — APPROVED** [review]
I had some minor comments, but overall looks great 🚀 Thanks for fixing up the Storybook example as well.

I guess it's worth explicitly mentioning that the positioning of the Gradient popovers haven't been fully resolved. Not a blocker for this PR merging though, since it's already incrementally better.

File: packages/components/src/palette-edit/types.ts (hunk 4 above)
Comment (aaronrobertshaw) [reply packages/components/src/palette-edit/types.ts]: ✅ Done (https://github.com/WordPress/gutenberg/pull/49975/commits/7430b2d411c7f2a85a091f1d707e1d43b1b2b242)

File: packages/components/src/palette-edit/types.ts (hunk 3 above)
Comment (aaronrobertshaw) [reply packages/components/src/palette-edit/types.ts]: ✅ Done (https://github.com/WordPress/gutenberg/commit/7430b2d411c7f2a85a091f1d707e1d43b1b2b242)

File: packages/components/src/palette-edit/index.tsx (hunk 1 above)
Comment (aaronrobertshaw) [reply packages/components/src/palette-edit/index.tsx]: This one required adding `className` to the `popoverProps` type for the ColorPickerPopover. I wasn't sure if this is something that we should be adding closer to the source e.g. in the Popover components props.

I'll hold off on merging this until I get confirmation on the latest changes to the types.

See: https://github.com/WordPress/gutenberg/pull/49975/commits/1efa1533a529516e917abd31e7ccfcf24fabc4eb

File: packages/components/src/palette-edit/index.tsx (hunk 2 above)
Comment (aaronrobertshaw) [reply packages/components/src/palette-edit/index.tsx:192]: I'm not sure if this is a bit of premature optimization as well. Looking through the rest of the codebase it appears that the majority of use cases memoize the popover props.

I've updated `color-palette-panel.js` to avoid recreating the popover props object and made the ColorPickerPopover memoize its popover props as well for consistency. I can of course remove the useMemo instances if you feel this was the wrong direction.

What do you think?

**Comment by aaronrobertshaw** [comment]
Thank you for reviewing this one again @mirka 🙇 

I think most of the feedback has been addressed. I did have a couple of follow-up questions/comments though that I left in reply to your review comments. 

I'll hold off on merging this for the moment to make sure that my latest changes are still in the right direction.

**Comment by aaronrobertshaw** [comment]
> I guess it's worth explicitly mentioning that the positioning of the Gradient popovers haven't been fully resolved. Not a blocker for this PR merging though, since it's already incrementally better.

I've put up a PR to reposition the gradient palette popovers based on this PR: https://github.com/WordPress/gutenberg/pull/50233.

I don't know what should happen with the duotone palette there. On trunk, no popover is displayed even at larger viewports. It's possible it isn't supposed to be there at all 🤷.

I'll look into the code and any existing issues for that separately.

File: packages/components/src/palette-edit/index.tsx (hunk 1 above)
Comment (mirka) [reply packages/components/src/palette-edit/index.tsx]: > I wasn't sure if this is something that we should be adding closer to the source e.g. in the Popover components props.

How about this?

```ts
	popoverProps?: Omit<
		React.ComponentPropsWithoutRef< typeof Popover >,
		'children'
	>;
```

File: packages/components/src/palette-edit/index.tsx (hunk 2 above)
Comment (mirka) [reply packages/components/src/palette-edit/index.tsx:192]: Looks good, let's go with this then 👍

**Comment by aaronrobertshaw** [comment]
> On trunk, no popover is displayed even at larger viewports. It's possible it isn't supposed to be there at all 🤷.

To close the loop on this, the duotone palette was intentionally uneditable (see https://github.com/WordPress/gutenberg/pull/36920). There are some ongoing explorations to make duotone filters editable via Global Styles (e.g. https://github.com/WordPress/gutenberg/pull/49265).
