### PR TITLE
Fix: Drop Cap + alignment produces a gap between paragraphs

### LINKED ISSUE #18409: Drop Cap + alignment produces a gap between paragraphs
A combination of a paragraph, a drop cap, and a right/left-aligned image produces a gap between the paragraph with the drop cap _and_ the next paragraph. 

**To reproduce**

Add an Image block, and resize the image so it’s about half the width or less of a normal block. For best results, make the image slightly less wide than the screen of your mobile device (or one you'll check in inspect element). I made this image 344x281 px and viewed it via inspect element with the Pixel 2 profile, 411x&731.
Right-align the Image block.
Click below the Image block, in an attempt to add a new block.
See a new Paragraph block appear to the left of the small Image block. Add some text, and use a Drop Cap.
1. Create a new post using Gutenberg, or use an existing post.
2. Add a paragraph with a right or left-aligned image that's taller than the paragraph
3. Choose to use the drop cap option

**Expected behavior**

To see the text in a good flow. Example:

Captura de Tela 2019-11-08 às 12 06 47

**What happened instead**

It produces a gap between the first paragraph (with the drop cap) and the second one:

Captura de Tela 2019-11-08 às 12 07 11

This is coming from:

```
.has-drop-cap:not(:focus):after {
    content: "";
    display: table;
    clear: both;
    padding-top: 14px;
}
```
Reproduced on both WordPress.com and Jurassic Ninja.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome, Safari, and FF

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
Fix: https://github.com/WordPress/gutenberg/issues/18409

These group fo styles were added in https://github.com/WordPress/gutenberg/pull/12177 to fix an issue with one-line paragraphs and drop cap. It seems removing clear: both; fixes https://github.com/WordPress/gutenberg/issues/18409
 bug and keeps the fix added in https://github.com/WordPress/gutenberg/pull/12177.

## How has this been tested?
I verified bug https://github.com/WordPress/gutenberg/issues/18409 was fixed and verified we did not regress on the problem https://github.com/WordPress/gutenberg/pull/12177 addresses.

### CODE REVIEW

**Review by epiqueras — CHANGES_REQUESTED** [review]
This does regress #12177. The drop cap now overflows the hover area again.

**Comment by jorgefilipecosta** [comment]
Hi @epiqueras, it seems I missed something in my tests. It turns out that addressing this problem is more complex, I proposed a new solution.

File: packages/block-library/src/paragraph/edit.js [hunk 1]
```diff
@@ -48,6 +56,27 @@ function ParagraphRTLToolbar( { direction, setDirection } ) {
 	) );
 }
 
+function useDropCapMinimumHeight( isDropCap ) {
+	const [ minimumHeight, setMinimumHeight ] = useState();
+	useEffect(
+		() => {
+			const element = querySelector && querySelector( PARAGRAPH_DROP_CAP_SELECTOR );
```
Comment (epiqueras) [inline packages/block-library/src/paragraph/edit.js]: `querySelector` shouldn't ever be `undefined` since you are binding it in the top scope.

File: packages/block-library/src/paragraph/edit.js [hunk 2]
```diff
@@ -48,6 +56,27 @@ function ParagraphRTLToolbar( { direction, setDirection } ) {
...
+			if ( isDropCap && element ) {
+				setMinimumHeight(
+					getComputedStyle(
+						element,
+						'first-letter'
+					).height
+				);
+			} else if ( minimumHeight ) {
```
Comment (epiqueras) [inline packages/block-library/src/paragraph/edit.js]: The closure over `minimumHeight` could be stale, because it's not a dep, leading to the minimum height not being cleared in some cases where it should.

File: packages/block-library/src/paragraph/edit.js [hunk 3]
```diff
@@ -48,6 +56,27 @@ function ParagraphRTLToolbar( { direction, setDirection } ) {
...
+				setMinimumHeight( undefined );
+			}
+		},
+		[ isDropCap ]
```
Comment (epiqueras) [inline packages/block-library/src/paragraph/edit.js]: The minimum height should also change when we change the font size.

File: packages/block-library/src/paragraph/edit.js [hunk 4]
```diff
@@ -64,7 +93,8 @@ function ParagraphBlock( {
 		placeholder,
 		direction,
 	} = attributes;
-
+	const paragraphRef = useRef();
+	const minimumDropCapHeight = useDropCapMinimumHeight( dropCap );
```
Comment (epiqueras) [inline packages/block-library/src/paragraph/edit.js]: `const dropCapMinimumHeight =` might read better.

File: packages/block-library/src/paragraph/edit.js [hunk 5]
```diff
@@ -64,7 +93,8 @@ function ParagraphBlock( {
 		placeholder,
 		direction,
 	} = attributes;
-
+	const paragraphRef = useRef();
```
Comment (epiqueras) [inline packages/block-library/src/paragraph/edit.js]: I don't think this is used.

File: packages/block-library/src/paragraph/editor.scss [hunk 6]
```diff
@@ -15,3 +15,8 @@
 	min-height: $empty-paragraph-height / 2;
 	line-height: $editor-line-height;
 }
+
+// Overwrite the inline style to make the height collapse when the paragraph editable gets focus.
+.block-editor-block-list__block[data-type="core/paragraph"] .has-drop-cap:focus {
+	min-height: $empty-paragraph-height / 2 !important;
```
Comment (epiqueras) [inline packages/block-library/src/paragraph/editor.scss]: It would be clearer to just not apply the inline style when focused, using the selection props/selectors.

**Review by epiqueras — CHANGES_REQUESTED** [review]
I think we could do this with pure CSS.

Some ideas:

https://stackoverflow.com/a/17761830
https://stackoverflow.com/questions/7166716/unexplained-white-space-when-using-clearboth
https://stackoverflow.com/questions/5684951/the-css-property-clear-leaves-a-huge-empty-space?noredirect=1&lq=1

**Comment by jorgefilipecosta** [comment]
Hi @epiqueras,
> I think we could do this with pure CSS.

Some ideas:
stackoverflow.com/a/17761830
stackoverflow.com/questions/7166716/unexplained-white-space-when-using-clearboth
stackoverflow.com/questions/5684951/the-css-property-clear-leaves-a-huge-empty-space?noredirect=1&lq=1


I tried lots of things with pure CSS and I was not able to find a solution that works on all case.
The problem with setting a clear right or left is that the previous image may be on the right or left so setting a clear breaks the things and creates white space.

File: packages/block-library/src/paragraph/editor.scss (hunk 6 above)
Comment (jorgefilipecosta) [reply packages/block-library/src/paragraph/editor.scss]: The isSelected prop gives an indication if the block is selected or not but the block can be selected and we may not have the rich text-focused e.g: we are typing on a block inspector field. As far as I know, there is no prop that tells us if the rich text is focused or not.

**Comment by epiqueras** [comment]
Did you try this one: https://stackoverflow.com/a/5685062?

**Comment by jorgefilipecosta** [comment]
Hi @epiqueras,
Yes, I tried to use something like:
```
.has-drop-cap:not(:focus)::after {
        clear: both;
        height: 0px;
        overflow: hidden;
    }
```

And unfortunately, it did not work.

**Review by epiqueras — APPROVED** [review]

**Comment by ellatrix** [comment]
@jorgefilipecosta This doesn't work in Firefox, probably because the selector isn't working:

Screenshot 2020-01-23 at 11 16 31

**Comment by ellatrix** [comment]
Additionally, it seems like this is only applied in the editor? Previously this worked on the front-end too.

**Comment by jorgefilipecosta** [comment]
I'm sorry for the delay @ellatrix, I lost this mention. Thank you for fixing this issue 👍
