### PR TITLE
TokenInput field: try alternative approach to fix screen reader focus issue

### LINKED ISSUE #42285: Post author combo box receives focus on page load
### Description

When editing an existing post and you have at least 25 users to select from the post author combo box, focus is automatically placed on the combo box after page load is complete. I expect this to not happen.

### Step-by-step reproduction instructions

1. Ensure you have 25+ users on your site.
2. Open an existing post or page.
3. Notice how focus is moved to the post author combo box just after the page finishes loading.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ciampo**
## What?

This PR tries an alternative approach to the changes suggested in #44347 — see https://github.com/WordPress/gutenberg/pull/44347#issuecomment-1260698575 for more context

## Why?

This is an attempt to fix #42285

## How?

The idea behind the fix is to only add the `aria-activedescendant` attribute when needed — i.e. when the input has focus and there is a valid suggestion being rendered and selected.

## Testing Instructions

- Follow instructions in #42285 and #44347 to make sure that the original issue is fixed (requires Windows)
  - Relevant comments:
    - https://github.com/WordPress/gutenberg/issues/42285#issuecomment-1254177634
    - https://github.com/WordPress/gutenberg/issues/42285#issuecomment-1254468323
- Make sure that there aren't regressions for screenreader users on Mac
- Make sure that components based on `TokenInput` (like `ComboboxControl` and `FormTokenField`) work as expected

### CODE REVIEW

File: packages/editor/src/components/post-author/index.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ import PostAuthorCombobox from './combobox';
 import PostAuthorSelect from './select';
 import { AUTHORS_QUERY } from './constants';
 
-const minimumUsersForCombobox = 25;
```
Comment (ciampo) [inline packages/editor/src/components/post-author/index.js]: This is only to make it easier to test for this fix. I will undo this change before merging, if this PR will get approved.

File: packages/components/src/combobox-control/index.js [hunk 2]
```diff
@@ -247,11 +247,6 @@ function ComboboxControl( {
 								instanceId={ instanceId }
 								ref={ inputContainer }
 								value={ isExpanded ? inputValue : currentLabel }
-								aria-label={
-									currentLabel
-										? `${ currentLabel }, ${ label }`
-										: null
-								}
```
Comment (ciampo) [inline packages/components/src/combobox-control/index.js:254]: For now, I decided to delete those lines like in the original PR. See https://github.com/WordPress/gutenberg/pull/44347#discussion_r978615389 and https://github.com/WordPress/gutenberg/pull/44347#discussion_r981917387 for additional context and motivations for this change

(cc @tellthemachines )

**Comment by ciampo** [comment]
(cc @costdev @joedolson @alexstine  )

**Review by alexstine — APPROVED** [review]
Thanks for the work on this @ciampo !

I had no idea how to get access to `onFocus` and `onBlur` at this stage. That is cool how you can just pass these consumers around like this.

**Review by andrewserong — APPROVED** [review]
Thanks for working on this one! Unfortunately my Windows test environment isn't working properly at the moment, so I haven't been able to reproduce the original issue to confirm the fix, but good that Alex has confirmed that that side of things is working correctly 👍

The code change looks good to me, and using state for keeping track of focus seems consistent with the `ComboboxControl`.

I smoke tested use of the `ComboboxControl` in the editor and it still appears to otherwise be working the same as on trunk for me. At first I though that I'd encountered a performance bug when hovering between items in the suggestions list with my mouse, but it turns out that's to do with a [`window.setTimeout` in the `SuggestionsList` set to `100ms`](https://github.com/WordPress/gutenberg/blob/ef8264a33dfb4efb35f471a8db893ddc0c1ebb7e/packages/components/src/form-token-field/suggestions-list.tsx#L57) which creates a delay when rapidly hovering between items in the list. Separately to this PR, it might be worth exploring reducing that timeout interval down to something lower (or even use `requestAnimationFrame` if it isn't too expensive to do on every frame).

Here's a GIF of that UI performance issue:



This LGTM! ✨

**Comment by ciampo** [comment]
Thank you both, @alexstine and @andrewserong !

I'll go ahead and merge this PR as soon as CI is ✅ 

>  Separately to this PR, it might be worth exploring reducing that timeout interval down to something lower (or even use requestAnimationFrame if it isn't too expensive to do on every frame).

Well spotted! I've opened #44573 to fix it

More in general, select-like and combobox-like control components (`SelectControl`, `ComboboxControl` and `FormTokenField`) are all in need of a refactor, which is on our radar for the upcoming months.

**Comment by michalczaplinski** [comment]
Cherry-picked for the 6.1 release in https://github.com/WordPress/gutenberg/pull/44656

**Comment by alexstine** [comment]
@michalczaplinski Thanks. This was an important one to get in.
