### PR TITLE
Modules API: Fix Interactivity not working on Classic Themes.

### LINKED ISSUE #57370: Image Lightbox not working on Classic Themes with Gutenberg versions higher than 17.1.x
### Description

The Image Lightbox is not working on Classic Themes when using Gutenberg versions higher than 17.1.x. In the backend, the Image Block will present the "Expand on click" option, but in the frontend clicking on the image or in the icon to expand it will do nothing. No error is tracked in the browser console.

Switching to a block theme like TT4 or deactivating Gutenberg fixes the issue.

### Step-by-step reproduction instructions

1. Install a Classic Theme
2. Install Gutenberg with a version higher than 17.1.x (I tested 17.2, 17.2.3 and 17.3)
3. Add an image to a page/post
4. Select the option to "Expand on click"
5. The image lightbox will not open on click

### Screenshots, screen recording, code snippet

Video: https://cldup.com/qvnfo5aGOa.mp4 (bigger than 10MB)

### Environment info

- WordPress 6.4
- GB 17.1, 17.2, 17.2.3, 17.3
- Twenty Sixteen and TT4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by cbravobernal**
## What?

Fixes #57370 and https://github.com/Automattic/wp-calypso/issues/85638

## Why?

As @t-hamano spotted in https://github.com/WordPress/gutenberg/pull/56143#issuecomment-1870135214. In classic themes, blocks are rendered on `the_content`. 

If we move the import map and the enqueued modules to the footer. Lightbox is working again.
This can be a temporary workaround before moving to WordPress Core.

## Testing Instructions

- Add Lightbox to any image.
- Check that the Lightbox is working on both Classic (Twenty Sixteen i.e.) and Block Themes (Twenty Twenty Four).

### CODE REVIEW

**Review by sirreal — APPROVED** [review]
I installed twentyseventeen and was able to reproduce the issue with Gutenberg 17.3. With this PR, the lightbox works again with twentyseventeen.

File: lib/experimental/modules/class-gutenberg-modules.php [hunk 1]
```diff
@@ -262,13 +262,14 @@ function gutenberg_dequeue_module( $module_identifier ) {
...
+add_action( $modules_position, array( 'Gutenberg_Modules', 'print_import_map' ) );
 
-// Prints the enqueued modules in the head tag.
-add_action( 'wp_head', array( 'Gutenberg_Modules', 'print_enqueued_modules' ) );
+// Prints the enqueued modules in the head tag in block themes. Otherwise in the footer.
+add_action( $modules_position, array( 'Gutenberg_Modules', 'print_enqueued_modules' ) );
 
-// Prints the preloaded modules in the head tag.
+// Prints the preloaded modules in the head tag in block themes.
 add_action( 'wp_head', array( 'Gutenberg_Modules', 'print_module_preloads' ) );
```
Comment (sirreal) [inline lib/experimental/modules/class-gutenberg-modules.php]: I'm not well versed in the modules code now, but it seems like this may be an issue. Won't all the module loading rely on import maps? In that case, wouldn't we need to move all the module loading (including the "preload" modules) to the footer?

Comment (cbravobernal) [reply lib/experimental/modules/class-gutenberg-modules.php]: Let's prevent it by moving all scripts to the footer.

**Review by sirreal — APPROVED** [review]
It seems safer to move all the modules to the footer 👍 

I'm doing some testing locally to better understand the issue and the implications, but I think this is OK to merge now.

**Comment by t-hamano** [comment]
Does `modulepreload` have any effect even if it is loaded ~~with a footer~~ inside the body tag? I'm not familiar with module imports, but in the case of classic themes, is it better not to do the enqueue itself?

**Comment by sirreal** [comment]
I was able to confirm that before moving preloads to the footer, this would cause an issue with preloaded modules. If I check out f13a53a6f908bc64d32dbf824b107107375819fc and add module preloads, I get the following errors in my browser console and interactivity is broken:

```
An import map is added after module script load was triggered.
Uncaught TypeError: Failed to resolve module specifier "@wordpress/interactivity". Relative references must start with either "/", "./", or "../".
Uncaught TypeError: Failed to resolve module specifier "@wordpress/interactivity". Relative references must start with either "/", "./", or "../".
```

**Comment by sirreal** [comment]
> Does `modulepreload` have any effect even if it is loaded ~with a footer~ inside the body tag? I'm not familiar with module imports…

That's a good question… I suspect it depends on a lot of different things and I don't have the expertise to explore them all. This is only a hint to help performance. I would be surprised if this were _harmful_, at worst I think we're providing a performance hint that's irrelevant. Maybe we could skip printing preload modules altogether if they're in the footer, but that can be revisited.

@sgomes [wrote the post on this](https://web.dev/articles/modulepreload), so maybe has more insight to share 🙂 

> but in the case of classic themes, is it better not to do the enqueue itself?

Modules still have to be enqueued, so nothing changes there regarding preload. The preload is only a hint to the browser saying "we'll need this, so fetch it so we've got it cached."

**Comment by cbravobernal** [comment]
>  Maybe we could skip printing preload modules

I added a conditional to make the preload only in block themes, where the modules are in the head. Classic themes will have worse performance, but is still a fix for an experimental feature that we can improve in future Gutenberg versions / WordPress Core implementation.

**Review by t-hamano — APPROVED** [review]
I confirmed that it works correctly with TwentyTwenty-One.

This theme injects a few scripts with the wp_footer hook, but the scripts related to the interactivity API are output in the expected order.

```html
<!doctype html>
<html lang="en-US" >
<head><head>
<body>
	<!-- ... -->
	<script type="importmap">{"imports":{"@wordpress\/interactivity":"http:\/\/localhost:8888\/wp-content\/plugins\/gutenberg\/build\/interactivity\/index.min.js?ver=6.4.2"}}</script>
	<script type="module" src="http://localhost:8888/wp-content/plugins/gutenberg/build/interactivity/image.min.js?ver=6.4.2" id="@wordpress/block-library/image"></script>
	<script>document.body.classList.remove("no-js");</script>
	<script>
	if ( -1 !== navigator.userAgent.indexOf( 'MSIE' ) || -1 !== navigator.appVersion.indexOf( 'Trident/' ) ) {
		document.body.classList.add( 'is-IE' );
	}
	</script>
	<script src="http://localhost:8888/wp-content/plugins/gutenberg/build/modules/importmap-polyfill.min.js" defer></script>

	<!-- ... -->
</body>
</html>
```

I think we can ship this approach for now and explore better approaches in the future.

**Comment by cbravobernal** [comment]
Sorry for all the changes, but, let's the browser fetch the module earlier, it doesn't need to parse the other script to find the dependency, so should give some perf improvement at best, and not really hurt at worst.

Again, it fixes the issue on the next Gutenberg release, and can be iterated in next releases.

**Comment by t-hamano** [comment]
> let's the browser fetch the module earlier

I see. I confirmed that it continues to work with the classic theme 👍
