### PR TITLE
Core Data: Don't return partial data when selecting a complete item

### LINKED ISSUE #71375: Bug: Post Featured Image sometimes retrieves incomplete media data if getMedia with _fields parameter is used earlier
### Description

This is a very hard to reproduce bug, and for whatever reason it only seems to be occurring on one client's website with only the most recent half-dozen images. 

Essentially, we have a custom Image Block in the editor, and it has this code:
```
	const imageData = useSelect(
		( select ) =>
			imageUrl ? { source_url: imageUrl } : select( coreStore ).getMedia( imageId, {
				context: 'view',
				_fields: [ 'source_url', 'alt_text' ],
			} ),
		[ imageId, imageUrl, imageAlt ],
	);
```
The idea being if it has an image url, just provide that as an object, otherwise use `getMedia` but only return those two fields.

Now, when one of our Image Blocks was present in the editor, had one of the problematic images set, and the user went to change the Post Featured Image via the sidebar, if they picked one of those same problematic images that were already in the editor, they'd get an error:
```
TypeError: can't access property "width", e.media_details is undefined
@https://www.animatematerials.org/wp-includes/js/dist/editor.min.js?ver=e143f7bc0f4773342f31:14:124889
Pp<@https://www.animatematerials.org/wp-includes/js/dist/editor.min.js?ver=e143f7bc0f4773342f31:14:124986
ht@https://www.animatematerials.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1.1:10:45677
vr@https://www.animatematerials.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1.1:10:56342
Qs@https://www.animatematerials.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1.1:10:121002
wl@https://www.animatematerials.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1.1:10:88343
bl@https://www.animatematerials.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1.1:10:88271
yl@https://www.animatematerials.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1.1:10:88132
il@https://www.animatematerials.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1.1:10:84984
fl@https://www.animatematerials.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1.1:10:85364
Nn@https://www.animatematerials.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1.1:10:32442
n/ul/<@https://www.animatematerials.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1.1:10:82952
```

It seems to fall apart here: https://github.com/WordPress/gutenberg/blob/06ce64d529ba10548945984989dc7125a9a939ea/packages/editor/src/components/post-featured-image/index.js#L88

To try and diagnose it, I created a PostFeaturedImage filter:
```
wp.hooks.addFilter( 'editor.PostFeaturedImage', 'test', ( PostFeaturedImage ) => {
	const withFeat = wp.compose.createHigherOrderComponent( ( PostFeaturedImage ) => ( props ) => {
		console.log( props );
		return (
			<>hlelo

				<PostFeaturedImage { ...props } />
			</>
		);
	} );

	return withFeat( PostFeaturedImage );
} );
```

Just to see what was happening.

I redid the error steps, and just before the error occurred, I got this props object from my HOC Post Featured Image:
```
{
  "media": {
    "alt_text": "",
    "source_url": "[REDACTED]",
  },
  "currentPostId": 3510,
  "featuredImageId": 3487,
  "isRequestingFeaturedImageMedia": false,
   // ... yadda yadda other unrelated stuff
}
```

And the only connection I can make is getMedia with the fields parameter cached the media object for when it was eventually retrieved by PostFeaturedImage.

I don't know why this only occurs with the most recent images, and I feel like I would have to really dive into Gutenberg with a dev build to understand the exact process taking place here.

TLDR: I can sort of replicate what is happening in the console:

Image

Using `getEntityRecord` with the _fields parameter appears to be a little sticky - once we get a response, and I use it again without the fields parameter, I get the entity ID as well as the fields that were already present in the previous response.

This issue appears to be related to https://github.com/WordPress/gutenberg/issues/56355 but because its dealing with a specific core component resulting in a critical error, felt the need to still make this issue.

### Step-by-step reproduction instructions

See above for the very convoluted process.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes #71375.

PR fixes a bug in the data store that would return subset record properties (as an intermediate response) when the consumer was requesting and expecting the whole record.

**Note:** This regressed sometime after initial `_fields` support was implemented. The lack of integration tests made it harder to catch similar regressions.

I've added coverage for the current case, plus some basic uses as integration tests. Hopefully, we can expand on those in the future.

## Why?
When a component requests a full entity record, it expects to receive `undefined` or the whole record. Returning partial data can lead to unexpected failures as described in the issue.

```js
// Resolved somewhere in the app.
wp.data.select( 'core' ).getEntityRecord( 'postType', 'attachment', 23, { _fields: [ 'id', 'source_url', 'alt_text' ], context: 'view' } ))

// A new request returns the previous resolution subset until the selector resolves, instead of `undefined`.
wp.data.select( 'core' ).getEntityRecord( 'postType', 'attachment', 23, { context: 'view' } )
```

## How?
Fixes the complete item check for the `getEntityRecord` selector to match a similar condition in the resolver.

### Integration tests

1. Create a new branch on top of the trunk.
2. Cherry-pick the 0e2eb9f commit.
3. `npm run test:unit -- packages/core-data/src/test/store.js`

### Manual
1. Open a post.
4. Select a featured image, close the sidebar and save.
5. Reload the editor.
6. Request partial data for the featured image. See snippet below.
7. Opening the sidebar shouldn't crash the editor.

```js
wp.data.select( 'core' ).getEntityRecord( 'postType', 'attachment', wp.data.select( 'core/editor' ).getEditedPostAttribute( 'featured_media' ), { _fields: [ 'source_url', 'alt_text' ], context: 'view' } )
```

### Testing Instructions for Keyboard
Same.

### CODE REVIEW

File: packages/core-data/src/selectors.ts [hunk 1]
```diff
@@ -365,7 +365,7 @@ export const getEntityRecord = createSelector(
 		}
 		const context = query?.context ?? 'default';
 
-		if ( query === undefined ) {
+		if ( ! query || ! query._fields ) {
```
Comment (Mamaduka) [inline packages/core-data/src/selectors.ts:368]: The new condition is the same as that used in the reducer.

https://github.com/WordPress/gutenberg/blob/2e69c4a1f175269004327759448097ef3a2336c8/packages/core-data/src/queried-data/reducer.js#L153-L161

File: packages/core-data/src/test/store.js
Comment (Mamaduka) [inline packages/core-data/src/test/store.js:1]: The filename is just a placeholder, unless we have better ideas 😅

File: packages/core-data/src/selectors.ts (hunk 1 above)
Comment (aduth) [inline packages/core-data/src/selectors.ts:368]: Does this now make the `&& query._fields` on the condition below redundant? 

https://github.com/WordPress/gutenberg/blob/0e2eb9fd046f516f978f7cae36889ddd94838982/packages/core-data/src/selectors.ts#L378

File: packages/core-data/src/test/store.js
Comment (aduth) [reply packages/core-data/src/test/store.js:1]: Curious why we wouldn't want this in `packages/core-data/src/test/selectors.js` ?

**Review by aduth — COMMENTED** [review]
My memory is a bit fuzzy on the details of the original implementation in #19498, but this change seems sensible to me 👍

File: packages/core-data/src/selectors.ts (hunk 1 above)
Comment (Mamaduka) [reply packages/core-data/src/selectors.ts:368]: ~~Why would it?~~

It's good practice to check argument existence before iterating on them. I think we should leave the linked condition.

File: packages/core-data/src/test/store.js
Comment (Mamaduka) [reply packages/core-data/src/test/store.js:1]: These are more like integration tests. I guess we can also convert those tests to be integration, but that's outside of the scope for this PR, IMO.

File: packages/core-data/src/selectors.ts (hunk 1 above)
Comment (aduth) [reply packages/core-data/src/selectors.ts:368]: What I mean is that line 378 can now never be reached if `query._fields` is falsey, so there's no need in checking that it's truthy.

Comment (Mamaduka) [reply packages/core-data/src/selectors.ts:368]: You're right. I don't have a strong opinion here, but it seems like a good check to keep in place "just in case" 😄

Updated in [d1b7dca](https://github.com/WordPress/gutenberg/pull/71474/commits/d1b7dcaf8829c397e50ad74da8277cabb7e9b47e).

File: packages/core-data/src/selectors.ts [hunk 2]
```diff
@@ -375,30 +375,29 @@ export const getEntityRecord = createSelector(
...
+				value = value?.[ fieldName ];
+			} );
+			setNestedValue( filteredItem, field, value );
+		}
+		return filteredItem as EntityRecord;
 	} ) as GetEntityRecord,
 	( state: State, kind, name, recordId, query ) => {
 		const context = query?.context ?? 'default';
+		const queriedState =
+			state.entities.records?.[ kind ]?.[ name ]?.queriedData;
```
Comment (Mamaduka) [inline packages/core-data/src/selectors.ts:397]: I just extracted it into a reusable variable.

File: packages/core-data/src/test/store.js
Comment (Mamaduka) [reply packages/core-data/src/test/store.js:1]: Turns out we already had unfinished unit tests for precisely this case. I've added the missing unit tests and removed the integration one.

P.S. I think I was too eager to introduce integration tests; we've been discussing them for a while. But I'm working on a different bug, where I think they'll be more suitable.

https://github.com/WordPress/gutenberg/blob/089ea38ae42d959e56ea1dad5ecea5b73f28424b/packages/core-data/src/test/selectors.js#L128

File: packages/core-data/src/test/selectors.js [hunk 3]
```diff
@@ -25,11 +24,7 @@ import {
 	getRevision,
 } from '../selectors';
 
-// getEntityRecord and __experimentalGetEntityRecordNoResolver selectors share the same tests.
-describe.each( [
-	[ getEntityRecord ],
-	[ __experimentalGetEntityRecordNoResolver ],
-] )( '%p', ( selector ) => {
```
Comment (Mamaduka) [inline packages/core-data/src/test/selectors.js:32]: I've removed coverage for `__experimentalGetEntityRecordNoResolver`. It's a leftover from when the data package was introduced and hasn't been used in the core.

I think we should just remove or deprecate it.

File: packages/core-data/src/selectors.ts [hunk 4]
```diff
@@ -375,30 +375,29 @@ export const getEntityRecord = createSelector(
...
-			for ( let f = 0; f < fields.length; f++ ) {
-				const field = fields[ f ].split( '.' );
-				let value = item;
-				field.forEach( ( fieldName ) => {
-					value = value?.[ fieldName ];
-				} );
-				setNestedValue( filteredItem, field, value );
-			}
-			return filteredItem as EntityRecord;
+		if ( ! item ) {
```
Comment (aduth) [inline packages/core-data/src/selectors.ts:378]: I like the flattening with early return 👍

**Review by aduth — APPROVED** [review]
Makes sense and LGTM 👍

**Comment by Mamaduka** [comment]
Thanks for the review, @aduth 🙇
