### PR TITLE
Fix: Ensure consistency in editor tools for navigation buttons and delete options

### LINKED ISSUE #63991: Inconsistent UI in editor settings
Editor tools aren't consistent creating this to track the following inconsistencies.

### 1. Having Chevron vs not having for the same menu type.

Shadow and Typography/font sizes, both are NavigationButtonItems, both takes to edit screen on click. But one comes with arrows and other is not.

| Shadows | Typography/font sizes |
| --- | --- |
| image | image |

Also

image

### 2. Delete all items or not

Delete options between the above two are different. Custom font sizes has delete all but not shadows 

| Custom Shadows | Custom font sizes | Colors |
| --- | --- | -- |
| image | image | image |
| image | image |

### PR DESCRIPTION
**Pull request by sarthaknagoshe2002**
Fixes: #63991

## What?
This PR addresses inconsistencies in the editor tools UI, focusing on:

Navigation Button Design: Ensures consistent use of chevrons for menu items like Shadows and Typography/Font Sizes, which navigate to edit screens.
Delete All Options: Adds or aligns "Delete All" functionality for custom settings like Shadows, Custom Font Sizes, and Colors.

## Why?
Inconsistent UI elements create confusion for users and hinder the overall experience. Aligning the design and functionality of editor tools improves usability, accessibility, and coherence across the interface.

## How?
Updated navigation button components to uniformly display chevrons for items that navigate to sub-settings (e.g., Shadows, Typography/Font Sizes).
Implemented consistent "Delete All" options for applicable settings, ensuring uniform behavior across Shadows, Custom Font Sizes, and Colors.
Adjusted CSS and component logic for styling and interactions to reflect these changes.

## Testing Instructions

1. Navigation Buttons

    - Check that Shadows and Typography/Font Sizes now show chevrons consistently.

2. Delete All Options

    - Verify the "Delete All" option exists and works for Shadows, Custom Font Sizes, and Colors.

## Screenshots or screencast 

https://github.com/user-attachments/assets/dfb019df-d454-4ba4-abb1-7d0456af6d85

### CODE REVIEW

**Comment by sarthaknagoshe2002** [comment]
@mikachan Could you kindly review this PR?

File: packages/edit-site/src/components/global-styles/shadows-panel.js [hunk 1]
```diff
@@ -21,6 +27,10 @@ import Subtitle from './subtitle';
 import { NavigationButtonAsItem } from './navigation-button';
 import ScreenHeader from './header';
 import { getNewIndexFromPresets } from './utils';
+import { IconWithCurrentColor } from './icon-with-current-color';
+const { Menu } = unlock( componentsPrivateApis );
```
Comment (mikachan) [inline packages/edit-site/src/components/global-styles/shadows-panel.js]: I'd suggest moving `Menu` further down to around line 36, after where `useGlobalSetting` is defined. We don't have a lint rule for it, but it's strange to me seeing a `const` in between the imports.

File: packages/edit-site/src/components/global-styles/shadows-panel.js [hunk 2]
```diff
@@ -115,6 +152,23 @@ function ShadowList( { label, shadows, category, canCreate, onCreate } ) {
...
+							<Button
+								size="small"
+								icon={ moreVertical }
+								label={ __( 'shadow options' ) }
+							/>
+						}
+					>
+						<Menu.Item onClick={ onReset }>
+							<Menu.ItemLabel>
+								{ __( 'Remove all shadows' ) }
```
Comment (mikachan) [inline packages/edit-site/src/components/global-styles/shadows-panel.js]:
```suggestion
								{ __( 'Remove all custom shadows' ) }
```

I think we should be more specific that this will remove just the custom shadows.

File: packages/edit-site/src/components/global-styles/shadows-panel.js [hunk 3]
```diff
@@ -115,6 +152,23 @@ function ShadowList( { label, shadows, category, canCreate, onCreate } ) {
 						/>
 					</FlexItem>
 				) }
+				{ !! shadows?.length && category === 'custom' && (
+					<Menu
+						trigger={
+							<Button
+								size="small"
+								icon={ moreVertical }
+								label={ __( 'shadow options' ) }
```
Comment (mikachan) [inline packages/edit-site/src/components/global-styles/shadows-panel.js]:
```suggestion
								label={ __( 'Shadow options' ) }
```

File: packages/edit-site/src/components/global-styles/shadows-panel.js [hunk 4]
```diff
@@ -135,9 +189,14 @@ function ShadowItem( { shadow, category } ) {
...
 			path={ `/shadows/edit/${ category }/${ shadow.slug }` }
-			icon={ shadowIcon }
 		>
-			{ shadow.name }
+			<HStack justify="space-between">
+				<HStack justify="flex-start">
+					<IconWithCurrentColor icon={ shadowIcon } />
+					<FlexItem> { shadow.name } </FlexItem>
+				</HStack>
+				<IconWithCurrentColor icon={ chevronRight } />
```
Comment (mikachan) [inline packages/edit-site/src/components/global-styles/shadows-panel.js]: It looks like the chevrons were added in https://github.com/WordPress/gutenberg/pull/67720. We should merge trunk into this PR and resolve any conflicts.

**Review by mikachan — COMMENTED** [review]
Nice work! I can see the shadow options are now more in line with the typography options, with the additional options menu and the confirm modal.

| trunk | Typography | This PR |
| ---- | ---- | ---- |
| image | image | image |

I've left a couple of inline comments. I think we should resolve the conflicts with trunk and then I'll give this another review 🙌

File: packages/edit-site/src/components/global-styles/shadows-panel.js (hunk 4 above)
Comment (sarthaknagoshe2002) [reply packages/edit-site/src/components/global-styles/shadows-panel.js]: I believe the approach I used to add the chevrons is better suited to accommodate the changes proposed in this PR. I’d like to continue with the same method, but please let me know if you have suggestions for a better approach.

**Comment by sarthaknagoshe2002** [comment]
@mikachan I’ve resolved the merge conflicts and addressed the feedback.  

I also noticed that a `tsconfig.json` file added yesterday to the latest trunk has some linting issues, which were automatically rectified by the pre-commit git hooks. Unfortunately, I’m unable to undo those changes, as the linting check requires proper formatting before committing.  

Could you please share any insights or suggestions on how to handle this?

**Comment by sarthaknagoshe2002** [comment]
> @mikachan I’ve resolved the merge conflicts and addressed the feedback.
> 
> I also noticed that a `tsconfig.json` file added yesterday to the latest trunk has some linting issues, which were automatically rectified by the pre-commit git hooks. Unfortunately, I’m unable to undo those changes, as the linting check requires proper formatting before committing.
> 
> Could you please share any insights or suggestions on how to handle this?

This is now resolved.

File: packages/upload-media/tsconfig.json [hunk 5]
```diff
@@ -8,13 +8,13 @@
...
-	  { "path": "../private-apis" },
-	  { "path": "../url" }
+		{ "path": "../api-fetch" },
+		{ "path": "../blob" },
+		{ "path": "../compose" },
+		{ "path": "../data" },
+		{ "path": "../element" },
+		{ "path": "../i18n" },
+		{ "path": "../private-apis" },
+		{ "path": "../url" }
```
Comment (mikachan) [inline packages/upload-media/tsconfig.json]: It looks like this has been resolved on trunk so we should be able to discard the changes to this file.

File: packages/edit-site/src/components/global-styles/shadows-panel.js [hunk 6]
```diff
@@ -136,11 +195,12 @@ function ShadowItem( { shadow, category } ) {
...
 			path={ `/shadows/edit/${ category }/${ shadow.slug }` }
 		>
-			<HStack>
-				<FlexItem>{ shadow.name }</FlexItem>
-				<FlexItem display="flex">
-					<Icon icon={ isRTL() ? chevronLeft : chevronRight } />
-				</FlexItem>
+			<HStack justify="space-between">
+				<HStack justify="flex-start">
+					<IconWithCurrentColor icon={ shadowIcon } />
```
Comment (mikachan) [inline packages/edit-site/src/components/global-styles/shadows-panel.js]: The `shadowIcon` was removed in https://github.com/WordPress/gutenberg/pull/67720 as per [this comment](https://github.com/WordPress/gutenberg/issues/67696#issuecomment-2525550554), so I don't think we should introduce it again here.

If we remove the `shadowIcon`, then I think we can also simplify the markup in line with [the changes](https://github.com/WordPress/gutenberg/pull/67720/files#diff-d76fe0b9848e786a8cc26155bd54635fb31ed7bb5ba193af1e702fe7c1cbeaaeR139) in the above PR (removing the additional `HStack`).

File: packages/edit-site/src/components/global-styles/shadows-panel.js (hunk 4 above)
Comment (mikachan) [reply packages/edit-site/src/components/global-styles/shadows-panel.js]: Could you explain the approach you're referring to here? At the moment it looks like this PR is using the same method to add the chevrons:

`<Icon icon={ isRTL() ? chevronLeft : chevronRight } />`

Comment (sarthaknagoshe2002) [reply packages/edit-site/src/components/global-styles/shadows-panel.js]: I was referring to the extra `Hstack`, however now as we have decided to remove it lets ignore that 😇

File: packages/edit-site/src/components/global-styles/shadows-panel.js (hunk 6 above)
Comment (sarthaknagoshe2002) [reply packages/edit-site/src/components/global-styles/shadows-panel.js]: This is now fixed.

File: packages/edit-site/src/components/global-styles/shadows-panel.js [hunk 7]
```diff
@@ -136,11 +193,9 @@ function ShadowItem( { shadow, category } ) {
 		<NavigationButtonAsItem
 			path={ `/shadows/edit/${ category }/${ shadow.slug }` }
 		>
-			<HStack>
+			<HStack justify="space-between">
```
Comment (mikachan) [inline packages/edit-site/src/components/global-styles/shadows-panel.js]: I don't think `justify="space-between"` is required, as it's the default alignment for this component.

File: packages/edit-site/src/components/global-styles/shadows-panel.js [hunk 8]
```diff
@@ -40,8 +50,27 @@ export default function ShadowsPanel() {
...
+	const [ isResetDialogOpen, setIsResetDialogOpen ] = useState( false );
+
+	const toggleResetDialog = () => setIsResetDialogOpen( ! isResetDialogOpen );
+
 	return (
 		<>
+			{ isResetDialogOpen && (
+				<ConfirmResetShadowDialog
+					text={ __(
+						'Are you sure you want to remove all custom Shadows?'
```
Comment (mikachan) [inline packages/edit-site/src/components/global-styles/shadows-panel.js]:
```suggestion
						'Are you sure you want to remove all custom shadows?'
```

Small nitpick for consistency, as I don't think we capitalise this anywhere else.

**Review by mikachan — APPROVED** [review]
Thanks for your work here, @sarthaknagoshe2002! I think this is ready to merge when the tests pass 🎉
