### PR TITLE
Fix custom template creation regression

### LINKED ISSUE #50793: Creating custom template fails
Creating a custom template doesn't proceed correctly to the next step:

https://github.com/WordPress/gutenberg/assets/846565/1f897743-3dea-4be6-8a13-da5814d4f6ea

@ntsekouras I wonder if this regression was caused by combining the modals in https://github.com/WordPress/gutenberg/pull/50595?

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Resolves: https://github.com/WordPress/gutenberg/issues/50793

I introduce a regression in https://github.com/WordPress/gutenberg/pull/50595 where the creation of a custom template is not possible right now. This PR fixes that.

Since it seems we focuses on the other flows mostly, this might need some css tweaks or design feedback

Screenshot 2023-05-22 at 11 48 27 AM

### CODE REVIEW

**Comment by jasmussen** [comment]
Here's a GIF showing the behavior:

custom

One thing we know we'll want in the future is to animate these modals when they change size. And size is the main problem with the second step, the custom template. If it was just sized appropriately it'd be fine.

File: packages/edit-site/src/components/add-new-template/add-custom-generic-template-modal-content.js [hunk 1]
```diff
@@ -50,7 +50,7 @@ function AddCustomGenericTemplateModalContent( { onClose, createTemplate } ) {
 					placeholder={ defaultTitle }
 					disabled={ isBusy }
 					help={ __(
-						'Describe the template, e.g. "Post with sidebar".'
+						'Describe the template, e.g. "Post with sidebar". A custom template can be manually applied to any post or page.'
```
Comment (ntsekouras) [inline packages/edit-site/src/components/add-new-template/add-custom-generic-template-modal-content.js:53]: This is just to match the post editor's modal.

**Comment by ntsekouras** [comment]
>One thing we know we'll want in the future is to animate these modals when they change size. And size is the main problem with the second step, the custom template. If it was just sized appropriately it'd be fine.

@jasmussen I have made the input in the modal to be full width for now. We should probably land this regression and have a follow up for design improvements, as it's not working right now on trunk. What do you think?

File: test/e2e/specs/site-editor/templates.spec.js [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+	test.beforeAll( async ( { requestUtils } ) => {
+		await requestUtils.activateTheme( 'emptytheme' );
+	} );
+	test.afterEach( async ( { requestUtils } ) => {
+		await requestUtils.deleteAllTemplates( 'wp_template' );
+	} );
+	test( 'Create a custom template', async ( { admin, page } ) => {
+		const templateName = 'demo';
+		await admin.visitSiteEditor();
+		await page.click( 'role=button[name="Templates"]' );
```
Comment (kevin940726) [inline test/e2e/specs/site-editor/templates.spec.js]: Nit: This is fine but we now recommend `getByRole` syntax because that's the officially documented one from Playwright. I think either is fine though so feel free to ignore :)!

Comment (ntsekouras) [reply test/e2e/specs/site-editor/templates.spec.js]: Updated [here](https://github.com/WordPress/gutenberg/pull/50797/commits/aa0aa39cb64c6853d9f65448d0e1487155e48267).

**Review by jameskoster — APPROVED** [review]
I think we should merge this as it fixes an important bug. 

There are other design details to polish in this flow, and we can probably include the custom-template-naming step therein.

**Comment by jasmussen** [comment]
The input becomes a bit wide, so it'd be good to follow up.

**Comment by jameskoster** [comment]
I'll make an issue for the UX / Polish board when I get a moment 👍 

Edit: No need, already tracked in https://github.com/WordPress/gutenberg/issues/50395.
