### PR TITLE
Block Hooks: Fix truncation of post content

### LINKED ISSUE #68605: Filtered post content is truncated in post-content block
When the content is filtered with `the_content` filter, the replaced content is truncated because it's not wrapped in the `post-content` block.

**Screenshots of the issue**

On Five for the Future we inject the company description:

Image

In "notice" blocks, we run `the_content` to parse markup:

Image

## To reproduce

- Add the following to your site, which will replace all content with `123456789`
	```
	add_filter(
		'the_content',
		function() {
			return '123456789';
		},
		1
	);
	```
- View any page, and you'll only see `456`.

## More details

This is due to #67272 adding `add_filter( 'the_content', 'remove_serialized_parent_block', 8 );`, and [remove_serialized_parent_block](https://developer.wordpress.org/reference/functions/remove_serialized_parent_block/) does not check for serialized blocks before running `substr`. This results in it trimming from 3, -3 if there is no wrapper.

Additionally, any blocks that run `the_content` on attributes are also truncated, as this filter runs in the course of rendering the block.

I'm not sure if the better solution is to add a check in `remove_serialized_parent_block`, or to change how the filter is applied in `core/post-content`, but I'm happy to draft a core patch if needed.

### LINKED ISSUE #68614: Query loop excerpt begins with ">"
### Description

I created a list of my latest blog posts using the Query Loop block. In the block editor, everything looks normal, but on the published page, the excerpt begins with ">". 

Rather than "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed..."
It shows "> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed..."

This symbol (>) obviously should not be present.

### Step-by-step reproduction instructions

1. Create a WordPress site on the Twenty Twenty Four theme
2. Create a query loop block ("image at left")
3. Ensure there's an excerpt
4. Publish
5. Visit published page

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 6.7.1, Twenty Twenty Four Theme
- Safari on macOS
- Gutenberg 20.0.0
- PHP 8.4

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by ockham**
## What?
Fix https://github.com/WordPress/gutenberg/issues/68605. To understand the underlying problem, see https://github.com/WordPress/gutenberg/issues/68605#issuecomment-2618970655.

## How?

By introducing a new function, `apply_block_hooks_to_content_from_post_object`, to colocate the logic used to temporarily wrap content in a parent block (with `ignoredHookedBlocks` information fetched from post meta) alongside the call to `apply_block_hooks_to_content`.

This centralizes logic added to the Post Content (https://github.com/WordPress/gutenberg/pull/67272), Synced Pattern (https://github.com/WordPress/gutenberg/pull/68058), and Navigation (https://github.com/WordPress/gutenberg/pull/57754) blocks.

See [`#62716`](https://core.trac.wordpress.org/ticket/62716).

## Testing Instructions

First, verify that this PR indeed fixes #68605. To do so, add the following filter:

```php
add_filter(
	'the_content',
	function() {
		return '123456789';
	},
	1
);
```

Then, verify that content on the frontend is indeed replaced by `123456789` (and not by just `456`). 

Additionally, it would be good to verify that this PR also fixes https://github.com/WordPress/gutenberg/issues/68614.

Finally, testing needs to cover that insertion of hooked blocks into **Post Content**, **Synced Pattern**, and **Navigation** blocks still works as before -- with a special focus on insertion as first or last child of those blocks.

To that end, please refer to the testing instructions of #67272, #68058, and #57754, respectively.

### CODE REVIEW

File: packages/block-library/src/block/index.php [hunk 1]
```diff
@@ -87,25 +87,8 @@ function render_block_core_block( $attributes ) {
...
-	$content = get_comment_delimited_block_content(
-		'core/block',
-		$attributes,
-		$content
-	);
 	// Apply Block Hooks.
-	$content = apply_block_hooks_to_content( $content, $reusable_block );
-	// Remove block wrapper.
-	$content = remove_serialized_parent_block( $content );
+	$content = apply_block_hooks_to_content_from_post_object( $content, $reusable_block );
```
Comment (ockham) [inline packages/block-library/src/block/index.php:91]: Note that each block that fetches content from a post object in the DB does so in a different way. Specifically, the Synced Pattern block (`core/block`) does not invoke the `the_content` filter, so we need to run `apply_block_hooks_to_content_from_post_object` manually.

File: packages/block-library/src/post-content/index.php [hunk 2]
```diff
@@ -46,33 +46,10 @@ function render_block_core_post_content( $attributes, $content, $block ) {
...
-		$content
-	);
-
-	// We need to remove the `core/post-content` block wrapper after the Block Hooks algorithm,
-	// but before `do_blocks` runs, as it would otherwise attempt to render the same block again --
-	// thus recursing infinitely.
-	add_filter( 'the_content', 'remove_serialized_parent_block', 8 );
-
 	/** This filter is documented in wp-includes/post-template.php */
 	$content = apply_filters( 'the_content', str_replace( ']]>', ']]&gt;', $content ) );
```
Comment (ockham) [inline packages/block-library/src/post-content/index.php:50]: The Post Content block runs the `the_content` filter, [to which we've hooked](https://github.com/WordPress/gutenberg/pull/68926/files#diff-76236aad75203b8bb9c5c1bb8c6c6bdd9751d9226f624c4e89327af5c11cb0b4R77) `apply_block_hooks_to_content_from_post_object`, which is why we don't have to run it manually here.

**Comment by ockham** [comment]
This should be ready for review. Since it's a pretty nasty bug, it'd be great if we could get it merged and synced over to Core before WP 6.8 Beta 1 (next Tuesday). I'm not sure if another npm package release and sync is planned prior to that; otherwise, Beta 1 will have the bug, and the fix will only go into Beta 2. Anyway, pinging Release Tech Leads @joemcgill @desrosj @mamaduka for advice.

Testing this PR is no small feat; not only do we need to test that it fixes the [original issue](https://github.com/WordPress/gutenberg/issues/68605), but also to make sure that hooked block insertion into the affected blocks (Post Content, Synced Pattern, Navigation) still works (especially first child/last child insertion). For the latter, we can peruse the testing instructions from the respective PRs that added Block Hooks to those blocks:

- [ ] #67272 for Post Content
- [ ] #68058 for Synced Patterns
- [ ] #57754 for Navigation

and

- [ ] #68605 for the original issue

It'd be great if we could divvy up testing to speed it up! (Ideally, we can land it on Thursday or Friday, so it can be part of another npm package release and sync prior to WP 6.8 Beta 1). If you'd like to help, edit this comment to add yourself to the above list, next to whichever block you're going to test, and leave a comment with your findings once you're done 😊 

Tentatively pinging @ryelle @richtabor @gziolo @tjcafferkey to ask for help with testing, if you have a bit of time available 🙌 

---

Finally, I've already started working on the [Core port](https://github.com/WordPress/wordpress-develop/pull/8212). I'll add some test coverage there and see to landing it before Beta 1.

**Comment by Mamaduka** [comment]
Thanks for working on this, @ockham!

Does core have PHPUnit test coverage for these methods? Can we add additional unit tests?

The release date of the WP 6.8 Beta 1 is March 4, 2025, so there will be at least one more Gutenberg release.

**Comment by ockham** [comment]
> Thanks for working on this, @ockham!
> 
> Does core have PHPUnit test coverage for these methods?

Not yet. `apply_block_hooks_to_content_from_post_object` is used either as a filter (for `the_content`), or from within blocks code. Due to the nature of those callsites, I don't think any of the containing methods have unit test coverage themselves. (It'd be pretty complex to set up test fixtures for those; arguably, they'd be integration tests rather than unit tests.)

> Can we add additional unit tests?

Yes! I'm planning to add unit test coverage for `apply_block_hooks_to_content_from_post_object` to the [Core port](https://github.com/WordPress/wordpress-develop/pull/8212) tomorrow.

> The release date of the WP 6.8 Beta 1 is March 4, 2025, so there will be at least one more Gutenberg release.

Oh, for what date is that GB release scheduled? (Also, we used to have a GB cut-off release some 2-3 weeks prior to WP Beta 1, after which any changes in GB had to be manually cherry-picked (to GB's `wp/x.y` branch) in order to have them synced over to Core. Did we change that policy?)

**Comment by Mamaduka** [comment]
Thanks again, @ockham!

> Oh, for what date is that GB release scheduled? (Also, we used to have a GB cut-off release some 2-3 weeks prior to WP Beta 1, after which any changes in GB had to be manually cherry-picked (to GB's wp/x.y branch) in order to have them synced over to Core. Did we change that policy?)

The plugin cut-off happens a week before Beta 1 - https://make.wordpress.org/core/handbook/about/release-cycle/block-editor-release-process-for-major-releases/#scheduling-the-last-editor-release-and-communicating-deadlines.

**Comment by ockham** [comment]
> The plugin cut-off happens a week before Beta 1 - https://make.wordpress.org/core/handbook/about/release-cycle/block-editor-release-process-for-major-releases/#scheduling-the-last-editor-release-and-communicating-deadlines.

🤦‍♂️ For whatever reason, I had _February_ 4 as the date for Beta 1 in my mind -- i.e. in less than a week from now -- even though you wrote March. Apologies -- took me a moment to realize!

Anyway, that gives us plenty more time to work on this 😅

**Review by gziolo — APPROVED** [review]
Code changes look good. It's definitely much anticipated refactoring that helps to remove some code duplication. In my testing, everything works as expected for the edge cases covered that regressed. I also repeated the testing steps outline in #67272. It would be nice to add some e2e testing coverage as this started to be very complex process to find and repeat all these steps.

One thing that might need closer look is when using the Classic block in the post content. I couldn't make it work with inserting the hooked block as the last or first child in the `core/post-content` block.

Screenshot 2025-01-30 at 14 33 13
Screenshot 2025-01-30 at 14 33 43

**Comment by Mamaduka** [comment]
Thank you, @ockham and @gziolo!

Are there any other blockers, or can we merge this?

**Comment by ockham** [comment]
No blockers from my side!

I'll file issues for the e2e tests, and for the problem with the classic block that @gziolo found.

**Comment by ockham** [comment]
Thank you for merging this, @Mamaduka!

I've filed
- https://github.com/WordPress/gutenberg/issues/68986
- https://github.com/WordPress/gutenberg/issues/68988

**Comment by XiaoWXZ** [comment]
As someone still relatively new to software development in the real world, It was very fascinating to see this progress from a GitHub Issue I opened, to pushing to solve the root problem, not just a symptom (https://github.com/WordPress/gutenberg/pull/68619#issuecomment-2586161334), to a merged pull request!

**Comment by ockham** [comment]
I've cherry-picked https://github.com/WordPress/gutenberg/commit/abd963b479b8b10e733ac5c63d69b64211b36cce to the `release/20.0` branch.
