### PR TITLE
wp-env: Set core source to latest when null

### LINKED ISSUE #43222: Env: Error in `readWordPressVersion`
### Description

It looks like either #41780 or #42826 broke wp-env usage for the Preferred Languages feature plugin.

Trying to update to `@wordpress/env` 5.1.0 (which includes this change) breaks `wp-env start` with this error:

```

✖ Cannot read property 'path' of null
TypeError: Cannot read property 'path' of null
    at readWordPressVersion (/home/runner/work/preferred-languages/preferred-languages/node_modules/@wordpress/env/lib/wordpress.js:251:14)
    at start (/home/runner/work/preferred-languages/preferred-languages/node_modules/@wordpress/env/lib/commands/start.js:138:4)
```

### Step-by-step reproduction instructions

Using a wp-env config file like this:

```json
{
	"core": null,
	"plugins": [ "." ]
}
```

Try to run `wp-env start`

### Screenshots, screen recording, code snippet

_No response_

### Environment info

`@wordpress/env` 5.1.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by noahtallen**
## What?
On trunk, there is a bug where if `.wp-env.json` sets `"core": null`, wp-env will crash. This PR handles that case.

Fixes #43222

## Why?
The object spread operators which merge all of the configurations together override the default "latest version" string with this null value.

## How?
In the overrides section of the config, we check if any of the core source values are still null, and then manually set the versions if needed. This means the core source should never be null.

## Testing Instructions
1. Use the trunk branch to start
2. In Gutenberg's wp-env.json file, change "core" to be `null`
3. Run `npx wp-env start --debug`. Observe that the core source in the printed config file is null and that wp-env crashes.
4. Checkout this branch.
5. Keep the wp-env.json change from step 2.
6. Run `npx wp-env start --debug`. It should start successfully, and you should see a git core source printed in the config file.

### CODE REVIEW

File: packages/env/lib/config/config.js [hunk 1]
```diff
@@ -273,15 +276,31 @@ function withOverrides( config ) {
...
 		);
 		config.env.development.coreSource = coreSource;
 		config.env.tests.coreSource = coreSource;
 	}
 
+	// If one of the sources is STILL null after parsing every config and CLI option,
+	// set it to the latest WordPress version. This also allows one to use
+	// .wp-env.override.json to reset the coreSource to the latest version.
+	if (
+		config.env.development.coreSource === null ||
```
Comment (ObliviousHarmony) [inline packages/env/lib/config/config.js]: After thinking about this some more, I don't actually think we need this fallback. `WP_ENV_CORE` _can_ be set to `"null"` but that will be parsed as a download source instead of being recognized as `null`.

Running `WP_ENV_CORE=null npm run wp-env start` will throw an error.

**Review by ObliviousHarmony — COMMENTED** [review]
How would you feel about moving the version default to `parseConfig()`? The conversion from `null` to `"latest"` might make the most sense there since we're really just parsing the `null`. Given that we won't need the fallback in `withOverrides()` and that we're already caching `getLatestWordPressVersion()`, that might be the most semantically correct.

File: packages/env/lib/config/config.js (hunk 1 above)
Comment (noahtallen) [reply packages/env/lib/config/config.js]: To clarify, do you mean that we need to also fix that case above or somehow integrate it with this fallback?

Comment (ObliviousHarmony) [reply packages/env/lib/config/config.js]: No, I don't think handling that case is necessary. I more mean that it removes the need for the fallback altogether. The `WP_ENV_CORE` _requires_ a valid `core` configuration that _isn't_ `null` since that would be a string `"null"` instead of an actual `null`.

I propose the following changes to this PR:

* Remove `coreRef` lookup from `readConfig()` and use the default of `null` as it was before. Also remove `getCoreRef()`.
* Remove fallback from `withOverrides()` and return to previous state since `WP_ENV_CORE` can't be anything other than a valid ref.
* In `parseConfig()` add handling to replace a `null` `core` with the latest version. This feels like it makes the most sense because it's "parsing" the `null` into the appropriate version.

Comment (noahtallen) [reply packages/env/lib/config/config.js]: That makes sense to me 👍 

I do wonder if it makes sense to allow some `WP_ENV_CORE` value which "unsets" whatever version would otherwise be used -- but also seems unimportant now.

File: packages/env/CHANGELOG.md [hunk 2]
```diff
@@ -2,11 +2,16 @@
...
+
+## 5.1.0 (2022-08-10)
+
 ### Enhancement
-- Previously, wp-env used the WordPress version provided by Docker in the WordPress image for installations which don't specify a WordPress version. Now, wp-env will find the latest stable version on WordPress.org and check out the https://github.com/WordPress/WordPress repository at the tag matching that version. In most cases, this will match what Docker provides. The benefit is that wp-env (and WordPress.org) now controls the default WordPress version rather than Docker.
+-   Previously, wp-env used the WordPress version provided by Docker in the WordPress image for installations which don't specify a WordPress version. Now, wp-env will find the latest stable version on WordPress.org and check out the https://github.com/WordPress/WordPress repository at the tag matching that version. In most cases, this will match what Docker provides. The benefit is that wp-env (and WordPress.org) now controls the default WordPress version rather than Docker.
```
Comment (noahtallen) [inline packages/env/CHANGELOG.md:11]: My guess is that the missing whitespace messed things up.

File: packages/env/lib/config/config.js [hunk 3]
```diff
@@ -155,23 +142,21 @@ module.exports = async function readConfig( configPath ) {
 
 	// Merge each of the specified environment-level overrides.
 	const allPorts = new Set(); // Keep track of unique ports for validation.
-	const env = allEnvs.reduce( ( result, environment ) => {
-		result[ environment ] = parseConfig(
+	const env = {};
+	for ( const envName in allEnvs ) {
```
Comment (noahtallen) [inline packages/env/lib/config/config.js]: Moved away from `reduce` because it's a lot easier to do async/await in a plain for loop

File: packages/env/lib/config/parse-config.js [hunk 4]
```diff
@@ -58,6 +62,19 @@ module.exports = function parseConfig( config, options ) {
...
+	}
+	const wpVersion = await getLatestWordPressVersion();
+	if ( ! wpVersion ) {
+		throw new ValidationError(
+			'Could not find the latest WordPress version. There may be a network issue.'
+		);
+	}
+	return `WordPress/WordPress#${ wpVersion }`;
+}
+
```
Comment (ObliviousHarmony) [inline packages/env/lib/config/parse-config.js]:
```suggestion
async function parseCoreSource( coreSource, options ) {
	// An empty source means we should use the latest version of WordPress.
	if ( ! coreSource ) {
		const wpVersion = await getLatestWordPressVersion();
		if ( ! wpVersion ) {
			throw new ValidationError(
				'Could not find the latest WordPress version. There may be a network issue.'
			);
		}
		
		coreSource = `WordPress/WordPress#${ wpVersion }`;
	}

	return parseSourceString( coreSource, options );
}

```

File: packages/env/lib/config/parse-config.js [hunk 5]
```diff
@@ -32,12 +33,15 @@ const HOME_PATH_PREFIX = `~${ path.sep }`;
...
+module.exports = async function parseConfig( config, options ) {
 	return {
 		port: config.port,
 		phpVersion: config.phpVersion,
 		coreSource: includeTestsPath(
-			parseSourceString( config.core, options ),
+			parseSourceString(
+				await getCoreSourceString( config.core ),
+				options
+			),
```
Comment (ObliviousHarmony) [inline packages/env/lib/config/parse-config.js]:
```suggestion
			await parseCoreSource( config.core, options ),
```

**Review by ObliviousHarmony — COMMENTED** [review]
Thanks @noahtallen, I appreciate the changes you made, this approach looks cleaner. I'm unable to test it right now because of the way I've set up Docker (Something is going wrong with argument passing to `docker-compose`). I've added two suggestions that I think might be aligned with the current "parsing of `null`" idea, but, it's probably not a big deal.

**Comment by noahtallen** [comment]
Nice, I like that idea! Added.

**Review by fullofcaffeine — APPROVED** [review]
LGTM and tests well!
