### PR TITLE
Lib: Show error when resolved block template is empty.

### LINKED ISSUE #20201: Empty templates in Block Based Themes result in "No matching template found" message.
I've gone back and forth on whether to report this as a bug or not, but I found it confusing enough that I think it is a bug. 

**Describe the bug**
A block template with no content in it results in an error message stating "No matching template found", even though a template was found, it was just empty.

**To reproduce**
1. Under "Appearance" > "Templates", create a template with the slug "single-post", but put no content in it.
2. Create and view a blog post.
3. Notice you see the error `"No matching template found"`.
4. Now, add a file called "single.html" to your Block Based Theme, fill it with block content, and save it.
5. View the blog post again, and notice you still see `"No matching template found".`

Seeing the message `"No matching template found".` was pretty confusing because I had multiple templates that existed, both of which would normally have worked in the old-style themes.

From a user perspective, I was just clicking around to try and learn this new system, and came to the conclusion that my theme was broken. But in reality, I had just added a user-created Block Template (in wp-admin) but put nothing in it yet. 

I'm guessing there are still more plans for that error message, but just wanted to make a note that this type of thing will likely confuse both users and theme authors alike.

**Expected behavior**
There are a few possibilities for my expectations of the behavior:

If a template exists, but is simply empty, then do one of these:
- Output `Template code was empty` 
- Output an actual empty page, matching the empty template.
- Fall-back to the next-in-line template and use it (like `single-post` to `single`)

If a template truly does not exist at all (not just empty), and there's no fallback available either, then it might make sense to output `"No matching template found"`, though any theme with an index.html file should be able to completely avoid this.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser Chrome
 - Version  79.0.3945.130 (Official Build) (64-bit)

**Additional context**
This discrepancy is caused by the falsey check done here:
https://github.com/WordPress/gutenberg/blob/master/lib/template-loader.php#L230

I don't feel a falsey check on the value of post_content is really enough to determine whether a template exists or not, at least not enough to provide valuable/actionable feedback to the user. 

To re-iterate my thoughts. I feel that either that should be changed to allow an empty template, use the next-in-line template available, or the error message should be adjusted based on whether a template exists, but is simply empty.

### PR DESCRIPTION
**Pull request by epiqueras**
Closes #20201

## Description

When a resolved block template was empty, the "No matching template found." error message was displayed. This was confusing to users because a template was found; it was just empty.

This PR handles these cases with an "Empty template." error message instead.

## How to test this?

- Enable The Gutenberg FSE and Demo Templates Experiments.
- Visit your home page and verify the demo `front-page` template is rendering.
- Delete the contents of `lib/demo-block-templates/front-page.html`.
- Refresh your home page and verify that the "Empty template." message is displayed.

## Types of Changes

*New Feature:* There is now a more granular error message to differentiate between when a block template is not found and when a block template is found, but it is empty.

## Checklist:

- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by epiqueras** [comment]
@WordPress/gutenberg-core Can we get this merged? It's a solid change regardless of how design decides to handle this later on.

**Review by mtias — APPROVED** [review]

File: lib/template-loader.php [hunk 1]
```diff
@@ -199,7 +199,7 @@ function gutenberg_find_template( $template_file ) {
 			}
 		}
 		$_wp_current_template_id      = $current_template_post->ID;
-		$_wp_current_template_content = $current_template_post->post_content;
+		$_wp_current_template_content = empty( $current_template_post->post_content ) ? 'Empty template.' : $current_template_post->post_content;
```
Comment (johnstonphilip) [inline lib/template-loader.php]: @epiqueras This string should likely be wrapped in a translation function like `__(`.

Comment (epiqueras) [reply lib/template-loader.php]: #20277
