### PR TITLE
Audio: Add uploading state

### LINKED ISSUE #29991: Audio block's "Upload" button doesn't show progress and fails silently.
## Description

When using the Audio block, if you click the "Upload" button and choose a file, it immediately places an audio player in the post, and it doesn't indicate whether the file has completed uploading. You can then publish the post and leave the page, all without being notified that your audio has not uploaded.

## Step-by-step reproduction instructions
1. Begin a new post.
2. Insert a new Audio block. 
3. Click the "Upload" button.
4. Choose an audio file that will take a few minutes to upload.
5. Immediately click the "Publish" button (and the subsequent confirmation Publish button).
6. You'll now see a link like "(no title) is now live." Click on it.

Notice that you leave the post editing page and it loads the published post with an audio player that doesn't work.

## Expected behaviour

Either the audio player UI shouldn't be added until the file has finished uploading, or some additional progress indicator should be added. Publishing should also be prohibited until the file finishes uploading.

## Actual behaviour

No consideration is given to whether the audio file has finished uploading.

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.2.0 (and whatever shipped with WordPress 5.7)
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Macbook Pro
- Operating system: Mac OS 10.15.7
- Browser: Firefox 85.0 (64 bit): Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:85.0) Gecko/20100101 Firefox/85.0

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
PR adds uploading state to the Audio block.

Resolves #29991.

## How has this been tested?
1. Throttle network to 3G via DevTools.
2. Add a new audio block.
3. Upload audio (you can use file from block example).
4. The uploading state should be visible.

## Screenshots 
https://user-images.githubusercontent.com/240569/148345602-f6b8baaa-f67f-4c72-9b58-f408f9100084.mp4

## Types of changes
Enhancement

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-library/src/audio/edit.js [hunk 1]
```diff
@@ -101,7 +108,6 @@ function AudioEdit( {
 			: null;
 	}
 
-	// const { setAttributes, isSelected, noticeUI } = this.props;
```
Comment (Mamaduka) [inline packages/block-library/src/audio/edit.js:104]: I think this was leftover code from refactoring.

File: packages/block-library/src/audio/editor.scss [hunk 2]
```diff
@@ -2,4 +2,18 @@
 	// Remove the left and right margin the figure is born with.
 	margin-left: 0;
 	margin-right: 0;
+	position: relative;
+
+	&.is-transient video {
```
Comment (Soean) [inline packages/block-library/src/audio/editor.scss]: Why do we style a Video element in the Audio player?

Comment (Mamaduka) [reply packages/block-library/src/audio/editor.scss]: Oh, it's copy-pasta 😅  I will push the fix shortly.

Comment (Mamaduka) [reply packages/block-library/src/audio/editor.scss]: Fixed in 4eba194.

**Review by jameskoster — APPROVED** [review]
Seems to be working:

Screenshot 2022-01-07 at 12 28 12

When I upload audio on trunk the player immediately appears with no loading indicator.

It would be nice to align the spinner centrally with the player if possible.

**Comment by Mamaduka** [comment]
Thanks, @jameskoster.

I think the spinner position should be better now.

https://user-images.githubusercontent.com/240569/148545572-39394c98-3cbe-4edc-b08f-eedd8e19cf93.mp4

**Comment by jameskoster** [comment]
Hmm the original CSS looked fine. I suppose it's the caption that's upsetting the position. It would be nice to implement something that will work long term if the player or caption height ever changes. 

Could the `audio` and the `Spinner` be wrapped in a div while it loads?

**Comment by Mamaduka** [comment]
You're right. Spinner is centered for the whole block, so caption is taken into account.

> Hmm the original CSS looked fine.

I can revert to the original position if you want.

> Could the audio and the Spinner be wrapped in a div while it loads?

Technically, yes. But I want to keep logic simple here.

**Comment by jameskoster** [comment]
If there's no simple way to align the spinner to the player then yes, it's probably best to have it aligned to the whole block rather than use magic numbers like the `35%`.

Edit: That said, perhaps we could use `transform: translate(-50%, -50%);` instead of the negative margin values? That would future-proof in case the spinner changes size.

**Comment by Mamaduka** [comment]
Restored. I tried `transform: translate(-50%, -50%);` but it didn't worked as I expected.

All other blocks use the same styles, so we can update them in one go if Snipper changes.
