### PR TITLE
Fix table block cell selection

### LINKED ISSUE #14904: Unexpected cell selection behavior in tables
**Describe the bug**
Cells in the table block seem to only accept selection when clicking in a specific area of the cell. Especially when writing longer texts, the issue becomes particularly apparent. The area seems to align with the part of the cell where the cursor appears when correctly selecting the cell.

**To reproduce**
1. Create a table block with at least two cells.
2. Add an example text to one of the cells. Especially when writing longer texts, the issue becomes particularly apparent (e.g., "Short example text to demonstrate unexpected behavior when selecting other cells in the created table. Short example text to demonstrate unexpected behavior when selecting other cells in the created table. Short example text to demonstrate unexpected behavior when selecting other cells in the created table.").
3. Optionally activate the "Fixed width table cells" option. However, this option does not change the unexpected behavior.
4. Select any of the other cells. Hovering with the mouse cursor over / clicking in different parts of the cell demonstrates that only a small area is actually accepting clicks to select the cell for editing. Compare with the areas highlighted in green and red in the attached _Screenshot 1_.

**Expected behavior**
As long as the user clicks somewhere in the rectangular area of a cell, it should not matter where the user clicks to select the cell for editing.

**Screenshots**
_Screenshot 1:_ The _green area_ seems to accept clicks by the user. The _red area_ does not accept clicks by the user.
table_edit

**Desktop**
 - OS: Windows 10
 - Browser: Firefox 66.0.2 (64-bit)
 - Gutenberg 5.4

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #14904

Fixes an issue where table block cells are difficult to select in some situations.

This issue particularly occurs when a cell is alongside another that has a lot of text content, and also particularly noticable when Fixed Width Cells is enabled.

## How has this been tested?
Added an e2e test

Manual testing
1. Create a table block with 1 row, 2 columns
2. Toggle on Fixed Width Cells
3. Type a lot of text into the first cell so that it wraps onto multiple lines
4. Try clicking at the very top or bottom of the second cell

Expected Result (in this branch)
The cell is selected

Actual Result (in current master)
The cell is not selected

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/block-library/src/table/edit.js [hunk 1]
```diff
@@ -377,15 +377,24 @@ export class TableEdit extends Component {
 							};
 
 							const cellClasses = classnames( { 'is-selected': isSelected } );
+							const richTextClassName = 'wp-block-table__cell-content';
```
Comment (ellatrix) [inline packages/block-library/src/table/edit.js]: Could this just be `rich-text`?

File: packages/block-library/src/table/edit.js [hunk 2]
```diff
@@ -377,15 +377,24 @@ export class TableEdit extends Component {
...
 								<CellTag
 									key={ columnIndex }
 									className={ cellClasses }
 									scope={ CellTag === 'th' ? scope : undefined }
+									onClick={ ( event ) => {
+										// When a cell is selected, forward focus to the child RichText. This solves an issue where the
+										// user may click inside a cell, but outside of the RichText, resulting in nothing happening.
+										const richTextElement = event && event.target && event.target.querySelector( `.${ richTextClassName }` );
+										if ( richTextElement ) {
+											richTextElement.focus();
```
Comment (ellatrix) [inline packages/block-library/src/table/edit.js]: I removed this line, and the e2e test still passes.

**Review by ellatrix — CHANGES_REQUESTED** [review]

File: packages/block-library/src/table/edit.js (hunk 1 above)
Comment (talldan) [reply packages/block-library/src/table/edit.js]: It could be, it's an existing class name though, not something new, so I don't see a big reason to change it.

File: packages/block-library/src/table/edit.js (hunk 2 above)
Comment (talldan) [reply packages/block-library/src/table/edit.js]: Thanks for spotting that, the selector used in the test was wrong, now fixed.

**Comment by talldan** [comment]
This one should be good for re-review.

File: packages/e2e-tests/specs/blocks/table.test.js [hunk 3]
```diff
@@ -154,4 +154,40 @@ describe( 'Table', () => {
 		// Expect the table to have 2 columns across the header, body and footer.
 		expect( await getEditedPostContent() ).toMatchSnapshot();
 	} );
+
+	// Testing for regressions of https://github.com/WordPress/gutenberg/issues/14904.
+	it( 'allows cells to be selected when the cell area outside of the RichText is clicked', async () => {
+		await insertBlock( 'Table' );
+
+		// Create the table.
+		const createButton = await page.$x( createButtonSelector );
```
Comment (ellatrix) [inline packages/e2e-tests/specs/blocks/table.test.js]: Also here, could the utility function `clickButton` be used?

File: packages/e2e-tests/specs/blocks/table.test.js [hunk 4]
```diff
@@ -154,4 +154,40 @@ describe( 'Table', () => {
...
+		await createButton[ 0 ].click();
+
+		// Enable fixed width as it exascerbates the amount of empty space around the RichText.
+		const fixedWidthSwitch = await page.$x( "//label[text()='Fixed width table cells']" );
+		await fixedWidthSwitch[ 0 ].click();
+
+		// Add lots of text to the first cell.
+		await page.click( '.wp-block-table__cell-content' );
+		await page.keyboard.type(
+			`Some long text that will wrap onto multiple lines.`
```
Comment (ellatrix) [inline packages/e2e-tests/specs/blocks/table.test.js]: You could also use line breaks here. Press `Enter` or type `\n`.

File: packages/e2e-tests/specs/blocks/table.test.js [hunk 5]
```diff
@@ -154,4 +154,40 @@ describe( 'Table', () => {
...
+			// Page.evaluate can only return a non-serializable value to the
+			// parent process, so destructure and restructure the result
+			// into an object.
+			const { x, y } = secondCell.getBoundingClientRect();
+			return { x, y };
+		} );
+
+		// Click in the top left corner of the second cell and type some text.
+		await page.mouse.click( secondCellX, secondCellY );
+		await page.keyboard.type( 'This content is in the second cell.' );
```
Comment (ellatrix) [inline packages/e2e-tests/specs/blocks/table.test.js]: I usually try to avoid long strings of text where one single character may be enough to test. Not sure if that actually makes much difference though. :)

**Review by ellatrix — APPROVED** [review]
