### PR TITLE
Post content: show placeholder if trying to render itself

### LINKED ISSUE #22080: FSE: Adding a post content block to a post causes a WSOD
**Describe the bug**
With full site editing enabled, it is possible to add a post content block to a post.
This causes a WSOD on the front.

In the console of the editor I see the following error:
```
react-dom.js?ver=16.9.0:539 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in r (created by Context.Consumer)
    in v (created by C)
    in C (created by BlockSettingsMenuControlsSlot)
    in BlockSettingsMenuControlsSlot
    in Unknown (created by r)
    in div (created by r)
    in r (created by ForwardRef(NavigableContainer))
    in ForwardRef(NavigableContainer) (created by ForwardRef)
    in ForwardRef (created by r)
    in div
    in div (created by ForwardRef)
    in ForwardRef
    in Unknown (created by W)
    in r (created by WithFocusOutside(r))
    in div (created by WithFocusOutside(r))
    in WithFocusOutside(r) (created by W)
    in Unknown (created by f)
    in div (created by f)
    in f (created by Context.Consumer)
    in WithFocusReturn(Component) (created by WithConstrainedTabbing(WithFocusReturn(Component)))
    in div (created by WithConstrainedTabbing(WithFocusReturn(Component)))
    in WithConstrainedTabbing(WithFocusReturn(Component)) (created by W)
    in S (created by M)
    in M (created by W)
    in span (created by W)
    in W (created by r)
    in div (created by r)
    in r (created by Kr)
    in Kr
    in div (created by Va)
    in Va (created by Ba)
    in Ba (created by ps)
    in ps
    in Unknown (created by WithDispatch(Component))
    in WithDispatch(Component)
    in Unknown (created by WithSelect(WithDispatch(Component)))
    in WithSelect(WithDispatch(Component)) (created by Su)
    in Su (created by Mu)
    in div (created by Mu)
    in Mu (created by uc)
    in div (created by r)
    in r (created by ForwardRef(NavigableContainer))
    in ForwardRef(NavigableContainer) (created by ForwardRef)
    in ForwardRef (created by sc)
    in sc (created by uc)
    in div (created by uc)
    in uc (created by fc)
    in div
    in div (created by ForwardRef)
    in ForwardRef
    in Unknown (created by W)
    in r (created by WithFocusOutside(r))
    in div (created by WithFocusOutside(r))
    in WithFocusOutside(r) (created by W)
    in S (created by M)
    in M (created by W)
    in W (created by fc)
    in fc (created by pc)
warningWithoutStack @ react-dom.js?ver=16.9.0:539
warnAboutUpdateOnUnmountedFiberInDEV @ react-dom.js?ver=16.9.0:23315
scheduleUpdateOnFiber @ react-dom.js?ver=16.9.0:21532
enqueueForceUpdate @ react-dom.js?ver=16.9.0:13283
Component.forceUpdate @ react.js?ver=16.9.0:431
(anonymous) @ index.js?ver=e11eeaeb4a7db2fe31218b09cb0efae2:6
commitHookEffectList @ react-dom.js?ver=16.9.0:20124
commitLifeCycles @ react-dom.js?ver=16.9.0:20169
commitLayoutEffects @ react-dom.js?ver=16.9.0:22951
callCallback @ react-dom.js?ver=16.9.0:341
invokeGuardedCallbackDev @ react-dom.js?ver=16.9.0:391
invokeGuardedCallback @ react-dom.js?ver=16.9.0:448
commitRootImpl @ react-dom.js?ver=16.9.0:22723
unstable_runWithPriority @ react.js?ver=16.9.0:2820
runWithPriority$2 @ react-dom.js?ver=16.9.0:11443
commitRoot @ react-dom.js?ver=16.9.0:22552
runRootCallback @ react-dom.js?ver=16.9.0:21692
(anonymous) @ react-dom.js?ver=16.9.0:11491
unstable_runWithPriority @ react.js?ver=16.9.0:2820
runWithPriority$2 @ react-dom.js?ver=16.9.0:11443
flushSyncCallbackQueueImpl @ react-dom.js?ver=16.9.0:11487
flushSyncCallbackQueue @ react-dom.js?ver=16.9.0:11476
discreteUpdates$1 @ react-dom.js?ver=16.9.0:21815
discreteUpdates @ react-dom.js?ver=16.9.0:2357
dispatchDiscreteEvent @ react-dom.js?ver=16.9.0:6104
```

Chrome:
In the console of the front I see the following error:
`Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING`

Firefox:
Refuses to load the post at all.

**To reproduce**
1.Enable full site editing
2. Create a new post in the regular block editor
3. Add a post content block and save
4. View the post on the front

**Expected behavior**
Posts should not be able to include _themselves_, I would assume it causes a infinite loop.

I am not sure what the solution would be:
Either disable the block in the post editor,
Or displaying a placeholder explaining that en error occurred (only visible to user with the correct privileges).

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Gutenberg 8.0.0

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome version:  81.0.4044.129
- Firefox version 75.0

### LINKED ISSUE #23762: browser becomes unresponsive when inserting post content block within a template
**Describe the bug**
Very similar to what @carolinan and @johnstonphilip reported in https://github.com/WordPress/gutenberg/issues/22080  

My browser becomes unresponsive when I attempt to add a post content block;

in my case, it occurs even when I try to add it to a post type of `template ` within the editor. 

**To reproduce**
1. create new site; 
2. build gutenberg from source
3. enable plugin
4. sitename.test/wp-admin/admin.php?page=gutenberg-experiments - enable full site editing
5. create new template at http://sitename.test/wp-admin/post-new.php?post_type=wp_template
6. open block directory, type in post content, click on its icon so it can be insert.

**Expected behavior**
the block would appear in the template even a square with a placeholder value so I know that the post content will appear when I use this template. 

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version:  5.4.2
- Does the website has Gutenberg plugin installe - yes, 
- uses gutenberg that was built from master branch, earlier today (2020-07-07) its most recent commit was 51256763abb2f54fa66ebfa7b6e1e5efb6eb5210

**Desktop (please complete the following information):**
- ubuntu 18.04 
chrome and firefox

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
Fixes #22080, fixes #23762 (by stopping those crashes from occurring when a post content block exists.)

Related to #24006.

## Description

* Adds Placeholder content for Post Title block which displays when editing wp_template.
* Adds placeholder for post content block, which displays when the root post is different from the post content (to avoid a crash. This works because there is no root post in FSE, but there is in all the other editors.)
* Restructuring of how we pull props in the Query Loop component.  This would break with a block error when loaded in the old editor due to lack of expected props being supplied through context.  Now it just finds the posts without a supplied query.

Although it will show all posts retrieved from the entity records as there is no query to control or limit them. 🤔 

## How has this been tested?
locally in edit site, edit post (while editing posts and templates)

## Screenshots 

For the Singular template, instead of looking totally broken we get:

Screen Shot 2020-07-16 at 7 18 04 PM

(note that the post content placeholder has since been updated to look like this:)
Screen Shot 2020-07-20 at 3 02 53 PM

And for the Index template the broken query loop block:
Screen Shot 2020-07-16 at 5 57 49 PM

Shows posts:
Screen Shot 2020-07-16 at 5 57 05 PM

## Types of changes
Bug fix, enhancement

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by noahtallen** [comment]
updated the placeholder style:

Screen Shot 2020-07-20 at 3 02 53 PM

**Comment by noahtallen** [comment]
> updated the placeholder style:

note that I'd love to get designs for these, but I feel like we can merge this "rough" one and it will be an improvement until we do have placeholder designs

File: packages/block-library/src/post-content/edit.js [hunk 1]
```diff
@@ -2,17 +2,28 @@
...
 
 export default function PostContentEdit( { context: { postId, postType } } ) {
-	if ( postId && postType ) {
+	const { id, type } = useSelect( ( select ) => {
+		return select( 'core/editor' ).getCurrentPost() ?? {};
+	} );
+
+	// Only render InnerBlocks if the context is different from the active post
+	// to avoid infinite recursion of post content.
+	if ( postId && postType && postId !== id && postType !== type ) {
```
Comment (ockham) [inline packages/block-library/src/post-content/edit.js:19]: I'm wondering if it would make sense to move this kind of check into the logic that provdes block context, in order to avoid any other blocks end up with the same infinite recursion issue. The context logic could e.g. set `context` to `{}` in those cases. The individual blocks would then still have to add UI for that case (placeholders, most likely), but they'd be prevented from causing infinite loops.

Comment (ockham) [reply packages/block-library/src/post-content/edit.js:19]: (Not a blocker, we can go ahead with this approach for now.)

However, let's maybe rename the var names in this component, since they're quite confusing right now (`postId` :left_right_arrow: `id`, `postType` :left_right_arrow: `type`)

Comment (noahtallen) [reply packages/block-library/src/post-content/edit.js:19]: > The context logic could e.g. set context to {} in those cases

The challenging thing here is that the context is always set to the root post. For example, in the post/page/template editors, it will be set with the postId of the loaded post, and the postType as well. We still need that context to be set at a root level in those editors :/

So obviously in the above editors, postId and postType in the post content block will always match the root context and therefore the block will render a placeholder.

In the site editor, though, there is no root post set at all. when you change pages in the nav menu, we just update the root context with that new postId and postType. These values are always different from `undefined`, so it renders the correct thing.

I'm not sure the infinite recursion is related to context, IMO. As far as I can tell, it is only related to a block which could possibly also show up again in the innerblocks of itself, but happens to pull that innerblock list from the same source. At the moment, that's only the post content block.

Do we need more robust checks in `BlockList` to avoid this recursive situation? e.g. an inner block controller attached to a specific entity happens to render the same inner block controller inside of itself, also attached to the same entity.

Comment (ockham) [reply packages/block-library/src/post-content/edit.js:19]: Maybe. Inner blocks and `BlockList` sound like a good lead.

Let's maybe defer the more general solution to later though, and go ahead with this one. (Can we do the [rename](https://github.com/WordPress/gutenberg/pull/24010#discussion_r458068789) though? :pray: :grimacing: )

Comment (noahtallen) [reply packages/block-library/src/post-content/edit.js:19]: yep, adding that real quick

File: packages/block-library/src/query-loop/edit.js [hunk 2]
```diff
@@ -17,12 +17,12 @@ import { useQueryContext } from '../query';
 const TEMPLATE = [ [ 'core/post-title' ], [ 'core/post-content' ] ];
 export default function QueryLoopEdit( {
 	clientId,
-	context: {
-		query: { perPage, offset, categoryIds },
-		queryContext,
-	},
+	context: { query: _query, queryContext },
```
Comment (epiqueras) [inline packages/block-library/src/query-loop/edit.js:20]: Won't query default to an empty object?

Comment (Addison-Stavlo) [reply packages/block-library/src/query-loop/edit.js:20]: It seems to be undefined when loading in the post editor ( Appearance -> Templates -> some template with a query loop ).  So being de-structured at that previous level was crashing with a `cannot find perPage of undefined` type error.

Comment (epiqueras) [reply packages/block-library/src/query-loop/edit.js:20]: Can we add a default value to the attribute? It would be simpler.

Comment (Addison-Stavlo) [reply packages/block-library/src/query-loop/edit.js:20]: Im familiar with how to do this for attributes in the block.json, but how do we do it for items in the `usesContext` array? 🤔

Comment (epiqueras) [reply packages/block-library/src/query-loop/edit.js:20]: In the parameter destructuring.

Comment (Addison-Stavlo) [reply packages/block-library/src/query-loop/edit.js:20]: Ohhh... gotcha.  So more like:
```
( {  context: { query = {}, queryContext } } )
const { perPage, offset, catergoryIds } = query;
```
^^ this?

Or are you mentioning there is a way to apply a default and continue to destructure from it in that perPage, offset, categoryIds would still be defined in that destructuring as well?  LOL, it would be nice but im not sure how that would look but a not-working example being:
```
( {  context: { query = {}: { perPage, offset, categoryIds }, queryContext } } )
```

Comment (Addison-Stavlo) [reply packages/block-library/src/query-loop/edit.js]: Updated for the first, but it would be neat if there was a way to do the second. 😆

Comment (epiqueras) [reply packages/block-library/src/query-loop/edit.js]: `( {
	context: { query: { perPage, offset, categoryIds } = {}, queryContext },
} )`

Comment (Addison-Stavlo) [reply packages/block-library/src/query-loop/edit.js]: Oo yes, that does it.  Thank you!

**Comment by noahtallen** [comment]
cc @youknowriad this could use a review!

File: packages/block-library/src/post-title/edit.js [hunk 3]
```diff
@@ -73,3 +69,20 @@ export default function PostTitleEdit( {
 		</>
 	);
 }
+
+export default function PostTitleEdit( {
+	attributes,
+	setAttributes,
+	context,
+} ) {
+	if ( ! context.postType || context.postType === 'wp_template' ) {
```
Comment (noahtallen) [inline packages/block-library/src/post-title/edit.js:78]: I wonder if we should switch this to the approach used for the post content block to make it more flexible in other post context :thinking:

File: packages/block-library/src/post-content/edit.js [hunk 4]
```diff
@@ -2,17 +2,38 @@
...
  */
 import PostContentInnerBlocks from './inner-blocks';
 
-export default function PostContentEdit( { context: { postId, postType } } ) {
-	if ( postId && postType ) {
+export default function PostContentEdit( {
+	context: { postId: contextPostId, postType: contextPostType },
+} ) {
+	const { id: currentPostId, type: currentPostType } = useSelect(
+		( select ) => select( 'core/editor' ).getCurrentPost() ?? {}
```
Comment (youknowriad) [inline packages/block-library/src/post-content/edit.js:16]: Ideally, block-library shouldn't rely on `core/editor` store as a block can be used in several contexts. Is there a way to infer this from the block context API?

File: packages/block-library/src/post-title/edit.js (hunk 3 above)
Comment (youknowriad) [reply packages/block-library/src/post-title/edit.js:78]: I actually think using PostTitle inside PostContent of the same context is fine. Why shouldn't it be possible?

Comment (Addison-Stavlo) [reply packages/block-library/src/post-title/edit.js:78]: Ah yes, looking back this is the 'weird spot' i wasn't sure about.  Honestly we should probably just remove the changes here as they don't induce any crashing.

> I actually think using PostTitle inside PostContent of the same context is fine. Why shouldn't it be possible?

It should be possible!  However, there are some oddities.

Say we are using the template post type editor to create a template that uses the post title block.  The intention would be that it displays the post title for whatever context is given to that page in the site editor, but editing that in the template post type editor it would be showing the name of the template instead.

File: packages/block-library/src/post-content/edit.js (hunk 4 above)
Comment (Addison-Stavlo) [reply packages/block-library/src/post-content/edit.js:16]: Id argue this doesn't rely on `core/editor`, it just checks for it.  We are only concerned with applying this fix when the context Post and the current Post are the same, as that is what was creating the loop and crashing the editor.  So in the case that `core/editor` is not available, this continues to work as intended as this fix is not necessary in that circumstance.

Comment (youknowriad) [reply packages/block-library/src/post-content/edit.js:16]: I can see that but do you think we can leverage the context API instead? It seems like a natural fit for this kind of checks?

Comment (Addison-Stavlo) [reply packages/block-library/src/post-content/edit.js:16]: Oh, sure!  Im drawing a blank at the moment, do you have an example of where else this is used?

Comment (Addison-Stavlo) [reply packages/block-library/src/post-content/edit.js:16]: Is that `useContext` from `@wordpress/element` ?

Comment (noahtallen) [reply packages/block-library/src/post-content/edit.js:16]: I think this block context API: https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-context

That said, we can't use any existing data which exists in context for this, but mabye we can add some extra data?

So we consume the context `postType` and `postId` here. So we use that to determine which post to render. The problem is that in the normal post editor, these values are set to the root post. If there exists a post content block in the root post, it will try to render itself recursively until it crashes the editor.

This is basically getting around that in the case that the post specified via context is the same as the root one in the editor store.

On any page with the core/editor store:
- The context postId and postType equal the one in the post/editor store (so we show the placeholder)

On the site editor:
- The context postId and postType are set, but the post/editor store does not specify anything at all since it isn't a post page. So we know it's ok to use them.

Instead of this, what if we instead add a bit of context to the root block context specifying the editor type? Then, if it is `post-editor`, we can show a placeholder, but if it is `site-editor`, we can safely render actual post content.

File: packages/block-library/src/post-title/edit.js (hunk 3 above)
Comment (noahtallen) [reply packages/block-library/src/post-title/edit.js:78]: I agree that the placeholder would be useful here, but yeah, maybe there is a better approach for accomplishing that.

File: packages/block-library/src/post-content/edit.js (hunk 4 above)
Comment (Addison-Stavlo) [reply packages/block-library/src/post-content/edit.js:16]: > Instead of this, what if we instead add a bit of context to the root block context specifying the editor type? Then, if it is post-editor, we can show a placeholder, but if it is site-editor, we can safely render actual post content.

This seems like a good approach, curious if @youknowriad has any other thoughts.

File: packages/block-library/src/post-title/edit.js (hunk 3 above)
Comment (Addison-Stavlo) [reply packages/block-library/src/post-title/edit.js]: I removed the changes to Post Title.  We can revisit this later if it is an issue, but for this PR we should concentrate on fixing the editor crashing via the post content block.

Comment (noahtallen) [reply packages/block-library/src/post-title/edit.js]: sounds good!

File: packages/block-library/src/post-content/edit.js (hunk 4 above)
Comment (youknowriad) [reply packages/block-library/src/post-content/edit.js:16]: Mmm right! I guess I'd avoid a new context value, I thought the existing one was already sufficient but apparently not, so I'm fine with the current "hack" for the moment.

**Review by noahtallen — APPROVED** [review]
Let's do it!
