### PR TITLE
Post editor: fix meta boxes accessibility

### LINKED ISSUE #65406: Don't use a details element for the metaboxes area
### Description

Follow-up to https://github.com/WordPress/gutenberg/pull/64351

Under a viewport height of 550 pixels, the metaboxes area container now turns into a `<details>` element. See 

https://github.com/WordPress/gutenberg/blob/6b7345fbaaedac8952274d821b23033b14e55a86/packages/edit-post/src/components/layout/index.js#L209-L226

As reported on https://github.com/WordPress/gutenberg/pull/64351#issuecomment-2355960496 by @joedolson a `<details>` element isn't ideal in this case. Basically it should not be used for sections of content that need a heading to identify the section. Also, it should not be used for accordion-like UIs. Rather, an expandable section with a heading 'Meta Boxe' should be used instead.

### Step-by-step reproduction instructions

- Activate a plugin that adds a metabox e.g. Yoast SEO.
- Edit a post.
- Emulate a viewport height that is smaller than 550 pixels.
- Observe the metaboxes area turns into a `<details>` element.

### Screenshots, screen recording, code snippet

metaboxes details

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by stokesman**
## What?
A fix for meta box headings being absent from accessibility tree when their container is collapsed.

## Why?
Meta boxes are expected to be accessible even if their container is collapsed.

To fix #65406.

## How?
1. Replaces the `details` element with a custom expandable (using `aria-expanded`).
2. Makes the meta boxes container a region and includes it in the navigable regions.

### Testing Instructions for Keyboard
Have a plugin activated that creates meta boxes or have the custom fields preference on and open a post or page in the Post editor.
#### Toggle (short viewport)
1. Make sure your window is short enough (less than 550 pixels tall)
3. Verify the meta box headings are in the document hierarchy whether or not they are visually hidden.

### CODE REVIEW

**Comment by t-hamano** [comment]
Thanks for the PR!

I'd like to test this PR in detail later, but one thing I noticed is that when the resize handle is focused, pressing the up and down keys may lose focus.

I checked out #65325 (07c6a1f), which implemented a custom resize handle, and tested this problem, and I was able to reproduce the problem in my environment. And, although the behavior is slightly different, this problem also occurs in this PR. We might have to investigate and fix this issue first.

Below is a video that reproduces the problem in trunk:

https://github.com/user-attachments/assets/053bc308-10c0-4cf8-b684-b74f3623aadc


By the way, I submitted a PR to the `re-resizable` library itself to match the focus order and visual order: https://github.com/bokuweb/re-resizable/pull/827 (cc @WordPress/gutenberg-components)

Even if that PR is merged, backporting it to WP 6.7 may have a big impact. Therefore, we might consider shipping this PR at the time of WP 6.7 and updating the library in WP 6.8.

**Comment by t-hamano** [comment]
> one thing I noticed is that when the resize handle is focused, pressing the up and down keys may lose focus.

It looks like this problem can be solved just by adding `event.preventDefault()` here:

https://github.com/WordPress/gutenberg/blob/e691b04fff49023687919e31184f20f8862fa13c/packages/edit-post/src/components/layout/index.js#L280-L281

**Update:** 

> one thing I noticed is that when the resize handle is focused, pressing the up and down keys may lose focus.

It turns out that this issue is specific to the Windows OS and Chrome browser. When [text cursor mode](https://support.google.com/accessibility/answer/10129654?hl=en-GB) is enabled, pressing the up and down keys takes focus away from the drag handle. In any case, it seems that `event.preventDefault()` is able to work around the effects of this mode.

**Comment by t-hamano** [comment]
https://github.com/bokuweb/re-resizable/pull/827 has been merged and released as version 6.10.0. Another way to solve this issue is to update `re-resizable`.

**Comment by tyxla** [comment]
> [bokuweb/re-resizable#827](https://github.com/bokuweb/re-resizable/pull/827) has been merged and released as version 6.10.0. Another way to solve this issue is to update `re-resizable`.

@t-hamano I see you're already working on it in [this branch](https://github.com/WordPress/gutenberg/tree/update-re-resizable), but if you need any help, let us know.

**Comment by stokesman** [comment]
> It turns out that this issue is specific to the Windows OS and Chrome browser.

I was able to reproduce on Mac OS with Firefox or Chrome as they both support caret browsing. I added the `preventDefault` call as suggested and all seems well now. Really nice you caught that Aki!

File: packages/edit-post/src/components/layout/index.js [hunk 1]
```diff
@@ -220,13 +222,47 @@ function MetaBoxesMain( { isLegacy } ) {
 	const separatorRef = useRef();
 	const separatorHelpId = useId();
 
-	const [ isUntouched, setIsUntouched ] = useState( true );
+	const heightRef = useRef();
+	const actualizeHeight = ( candidateHeight, isPersistent ) => {
```
Comment (DaniGuardiola) [inline packages/edit-post/src/components/layout/index.js]: I think you mean "update" ("make (something) more modern or up to date") instead of "actualize" ("make a reality of").

Comment (DaniGuardiola) [reply packages/edit-post/src/components/layout/index.js]: I guess "actualize" was already used in the code before this PR. Still, might be a good chance to fix it as the name does not match what it actually does, afaik.

**Comment by t-hamano** [comment]
I think we have two paths to take. Which one is better?

1. Backport this PR to WP 6.6 >  Update `re-resizable` library > Replace the custom code implemented in this PR with the ResizableBox component
2. Update `re-resizable` library and backport it to WP6.6 (This will solve the tab order issue) > Revert the custom code implemented in this PR (just replace the details element) and backport it to WP 6.6

File: packages/edit-post/src/components/layout/index.js [hunk 2]
```diff
@@ -248,141 +284,89 @@ function MetaBoxesMain( { isLegacy } ) {
...
-			boundsByDirection
+	const className = 'edit-post-meta-boxes-main';
+	const paneLabel = __( 'Meta Boxes' );
+	let paneProps, paneButtonProps;
+	if ( isShort ) {
+		paneProps = {
+			className: clsx( className, 'is-toggle-only', isOpen && 'is-open' ),
+		};
+		paneButtonProps = {
+			'aria-label': __( 'Expand or collapse meta boxes pane' ),
```
Comment (joedolson) [inline packages/edit-post/src/components/layout/index.js]: This button should have a managed `aria-expanded` attribute, which allows the text to be shortened to just 'Meta boxes pane'. The behavior will be conveyed by the value of the `aria-expanded` attribute, and the extra terms are unnecessary.

File: packages/edit-post/src/components/layout/style.scss [hunk 3]
```diff
@@ -1,69 +1,83 @@
...
-	// The position is absolute by default inline style of ResizableBox.
-	inset: 0 0 auto 0;
-	height: $resize-handle-height;
-	box-shadow: 0 $border-width $gray-300;
+	.is-resizable > & {
+		cursor: row-resize;
+		height: $grid-unit-30;
+		@media (pointer: coarse) {
+			height: $button-size-compact;
+		}
```
Comment (t-hamano) [inline packages/edit-post/src/components/layout/style.scss]: This is the first I've heard of this, but it's a great improvement.

File: packages/edit-post/src/components/layout/index.js [hunk 4]
```diff
@@ -248,141 +284,89 @@ function MetaBoxesMain( { isLegacy } ) {
...
-		>
-			<meta ref={ effectSizeConstraints } />
+					</div>
+				</Tooltip>
+			),
+		};
+	}
+
+	return (
+		<aside aria-label={ paneLabel } { ...paneProps }>
```
Comment (t-hamano) [inline packages/edit-post/src/components/layout/index.js]: Is the `aside` element appropriate here? I'd like to hear from people with more knowledge.

**Review by t-hamano — COMMENTED** [review]
Regarding the tab order issue, I thought it might be solved by updating the `re-resizable` library (#65637). However, some behaviors have changed in the latest version, so I couldn't simply update it. Considering the impact on developers, it might be better to proceed with this PR after all.

After testing this PR, I noticed two things so far:

---

1. In Windows high contrast mode, I can't see the resize handles and the chevron icon:

high-contrast-mode

details

The following style should help:

<details>
<summary>Diff</summary>

```diff
diff --git a/packages/edit-post/src/components/layout/style.scss b/packages/edit-post/src/components/layout/style.scss
index 4e2e72b721..3d4d9af30f 100644
--- a/packages/edit-post/src/components/layout/style.scss
+++ b/packages/edit-post/src/components/layout/style.scss
@@ -5,6 +5,8 @@
        display: flex;
        flex-direction: column;
        overflow: hidden;
+       // Windows High Contrast mode will show this outline, but not the box-shadow.
+       outline: 2px solid transparent;
 }
 
 .edit-post-meta-boxes-main__presenter {
@@ -35,6 +37,10 @@
                        inset: var(--wp-admin-border-width-focus);
                        @include button-style__focus();
                }
+
+               svg {
+                       fill: currentColor;
+               }
        }
 
        .is-resizable > & {
@@ -60,6 +66,8 @@
                                border-radius: $radius-small;
                                transition: width 0.3s ease-out;
                                @include reduce-motion("transition");
+                               // Windows High Contrast mode will show this outline, but not the box-shadow.
+                               outline: 2px solid transparent;
                        }
                }
```

</details>

---

2. I can't resize it on touch devices. My guess is that this is because [`useDragging` only targets mouse events](https://github.com/WordPress/gutenberg/blob/e39c22ac1fa556d982630684b7e577ae1fc156f7/packages/compose/src/hooks/use-dragging/index.js#L54-L55). I haven't found a good solution to this yet...

**Comment by t-hamano** [comment]
I'm not sure if this is possible, but I wanted to share one idea I had.

- Use a `ResizableBox` component as before, and render a top resize handle via the `handleComponent` prop. But the resize handle is NOT focusble.
- Users with a mouse or touch device can use this resize handle to resize.
- Overlay a focusable button on the non-focusable resize handle. Attach a key down event to this button. Keyboard users can use this button to resize.

File: packages/edit-post/src/components/layout/index.js (hunk 2 above)
Comment (stokesman) [reply packages/edit-post/src/components/layout/index.js]: Thanks for reviewing! b7f087ecb19759e681a5f7400b8edb0164bcb03d adds `aria-expanded` but since the button itself already had "Meta boxes" as its text I just removed `aria-label`. Does that seem good?

**Comment by stokesman** [comment]
> 1. In Windows high contrast mode, I can't see the resize handles and the chevron icon:

I’ve updated with a slightly tweaked version of the styles you suggested. Thanks for catching that!

> 2\. I can't resize it on touch devices. My guess is that this is because [`useDragging` only targets mouse events](https://github.com/WordPress/gutenberg/blob/e39c22ac1fa556d982630684b7e577ae1fc156f7/packages/compose/src/hooks/use-dragging/index.js#L54-L55). I haven't found a good solution to this yet...

Yes this is unfortunate. I’ve opted use `ResizableBox` again for this PR so we can just focus this on removing the `details` element. The solutions for the tab order issue all seem to have enough obstacles that they’d be better explored separately.

> * Overlay a focusable button on the non-focusable resize handle. Attach a key down event to this button. Keyboard users can use this button to resize.

I do think I briefly considered this, if I understand what you are suggesting. The focusable button would be rendered before the meta boxes container and have its positioning dynamically kept in sync with the drag handle. It could be worth a try, though it seems likely it may be about as complicated as not using `ResizableBox` and fixing `useDragging`. The latter would have performance benefits that I was going discuss here but I’ll save that for elsewhere.

File: packages/edit-post/src/components/layout/index.js (hunk 1 above)
Comment (stokesman) [reply packages/edit-post/src/components/layout/index.js]: I’m okay with "update". I bet no one would have given it second glance so perhaps that alone makes it better.

I’m always interested in words and using them better so I’ll take the opportunity to ask your thoughts on why what this function does is not an actualization.

My own convention with  "update" is to use it for functions that modify the value relatively or take a callback which receives the current value and uses the returned value to set the new one.

As for "actualize", to me it signifies effects. In this case the function may apply two DOM properties. Which after having another look at the other "actualize" in the file, I want to say that was mistaken (and my doing). It only sets state so I should have named it something else 😆.

Maybe instead of "actualize" there is a better word—"affect" or "apply"? Just wondering and not specifically for this case. "updateHeight" is fine by me.

File: packages/edit-post/src/components/layout/style.scss [hunk 5]
```diff
@@ -1,69 +1,107 @@
-$resize-handle-height: $grid-unit-30;
-
 .edit-post-meta-boxes-main {
 	filter: drop-shadow(0 -1px rgba($color: #000, $alpha: 0.133)); // 0.133 = $gray-200 but with alpha.
+	// Windows High Contrast mode will show this outline, but not the shadow.
+	outline: 1px solid transparent;
 	background-color: $white;
 	clear: both; // This is seemingly only needed in case the canvas is not iframe’d.
```
Comment (t-hamano) [inline packages/edit-post/src/components/layout/style.scss]: Although not directly related to the purpose of this PR, if the editor is not an iframe (`isLegacy` is `true`), the `.edit-post-meta-boxes-main` class does not exist, so it seems this CSS (`clear: both`) can be removed.

File: packages/edit-post/src/components/layout/style.scss [hunk 6]
```diff
@@ -1,69 +1,107 @@
...
-			z-index: 1;
-		}
+	&.is-resizable {
+		padding-block-start: $grid-unit-30;
 	}
 }
 
-.edit-post-meta-boxes-main__resize-handle {
+.edit-post-meta-boxes-main__presenter {
+	flex-shrink: 0;
```
Comment (t-hamano) [inline packages/edit-post/src/components/layout/style.scss]: I don't think it's necessary since the parent element is not flex.

**Review by t-hamano — COMMENTED** [review]
Everything seems to work fine. Let's address the tab order problem in a follow-up.

I just found that I need one more outline for Windows high contrast mode.

```diff
diff --git a/packages/edit-post/src/components/layout/style.scss b/packages/edit-post/src/components/layout/style.scss
index 7c97cfe4e5..a8c39f265c 100644
--- a/packages/edit-post/src/components/layout/style.scss
+++ b/packages/edit-post/src/components/layout/style.scss
@@ -19,6 +19,8 @@
        box-shadow: 0 $border-width $gray-300;
        position: relative;
        z-index: 1;
+       // Windows High Contrast mode will show this outline, but not the shadow.
+       outline: 1px solid transparent;
 
        // Button style reset for both toggle or resizable.
        .is-toggle-only > &,
```

### Before

before-resizable

before-details

### After

after_resizable

after-details

My only concern is whether the `aside` element is appropriate. @joedolson @afercia

**Comment by t-hamano** [comment]
By the way, as another approach to solving the tab order, I submitted #65637 to update the `re-resizable` library itself. However, I found that some default behaviors have changed and it is not possible to simply update it. Considering the impact on developers, I think it would be better to update the `re-resizable` library after WP6.7 is released.

**Comment by afercia** [comment]
> My only concern is whether the aside element is appropriate

@t-hamano thanks for your ping. 
Semantically, an `aside` element looks appropriate at first but I see a couple concerns:
- Ideally, an `aside` should be placed outside of the `<main>` element which is the `<div id="wpbody" role="main">`.
- An `aside` element is natively mapped to an ARIA landmark. Screen readers provide built-in tools to navigate through ARIA landmarks and in the editor we're coupling this screen-reader-only feature with the `NavigateRegions` component to provide an equivalent navigation mechanism to all keyboard users. For clarity: it's about the Ctrl + backtick shortcut to navigate the editor regions. As such, this would be the only ARIA landmark that is not coupled with `NavigateRegions`. 

I'm a little thorn on this but I would say that either the aside should be replaced with a generic div or it should be a `role="region"` that works with `NavigateRegions`.

File: packages/edit-post/src/components/layout/style.scss (hunk 5 above)
Comment (stokesman) [reply packages/edit-post/src/components/layout/style.scss]: Thanks for noticing this! This rule seems like it should be preserved but it was in the wrong place. 89fdd4edb12e8949086297582844deb7e6f2281b moves it so it will actually apply. I just realized, I could have specified it to not apply when the iframe is present, but the rule isn’t harmful and it costs more bytes write the longer selector.

File: packages/edit-post/src/components/layout/style.scss (hunk 6 above)
Comment (stokesman) [reply packages/edit-post/src/components/layout/style.scss]: Good spot! It’s still useful for the toggle button so I moved the style there 3f7553bb508168120a4116d07b93e7cf108ea0e8. It was in play for the separator button when `ResizableBox` wasn’t being used.

**Comment by stokesman** [comment]
@afercia thanks for weighing in. I’d wanted to try a labeled section for the meta boxes for a couple of reasons. 

@joedolson’s https://github.com/WordPress/gutenberg/issues/65406#issuecomment-2358686167 got me thinking that maybe it improves a11y for the section itself to be locatable so I wanted to apply a label. Using `aria-label` on an element without a `role` doesn’t seem recommended so I tried the `aside`. Now if we switch to a `div` without a `role`, would `aria-label` actually be meaningful? Is the label helpful in the first place?

That same comment also had me wondering if perhaps with a labeled landmark as the container then it would actually be okay to accessibly hide the meta boxes. That would remove my current concern that the container can be collapsed but there’s still a bunch of tab stops within. It seems like we have to uncollapse the section in case focus enters it. I don’t think that’s too challenging but hadn’t done it yet in case the simpler option could be considered.

**Comment by afercia** [comment]
> Now if we switch to a div without a role, would aria-label actually be meaningful? Is the label helpful in the first place?

~~@t-hamano~~ @stokesman  What I meant with my previous comment was to try to make the aside a div with role=region and keep the label. I'd try to render the meta boxes container with a `NavigableRegion`, that should automatically add `role="region" tabindex="-1"`. That way, the container would be an ARIA landmark _and_ a navigable region. In my quick testing, Ctrl + backtick would work and allow to navigate to the meta boxes region.

Here's what I tried: 
```
-const { Editor, FullscreenMode } = unlock( editorPrivateApis );
+const { Editor, FullscreenMode, NavigableRegion } = unlock( editorPrivateApis );
 const { BlockKeyboardShortcuts } = unlock( blockLibraryPrivateApis );
 const DESIGN_POST_TYPES = [
 	'wp_template',
@@ -298,14 +298,14 @@ function MetaBoxesMain( { isLegacy } ) {
 	const paneLabel = __( 'Meta Boxes' );
 	let Pane, paneProps;
 	if ( isShort ) {
-		Pane = 'aside';
+		Pane = NavigableRegion;
 		paneProps = {
 			className: clsx( className, 'is-toggle-only', isOpen && 'is-open' ),
 		};
 	} else {
 		Pane = ResizableBox;
 		paneProps = /** @type {Parameters<typeof ResizableBox>[0]} */ ( {
-			as: 'aside',
+			as: NavigableRegion,
 			ref: metaBoxesMainRef,
 			className: clsx( className, 'is-resizable' ),
 			defaultSize: { height: openHeight },

```

Navigale regions in action:

navregion

Edit:
hm, I suspect using the `NavigableRegion` component would break the `Resizablebox` functionality. Worth double checking. Otherwise, `role="region" tabindex="-1"` could be added manually.

**Comment by stokesman** [comment]
@afercia, thanks for clarifying! I like the idea of using `NavigableRegion`. The only caveat I can think of is that it is possible to have the region go from present to absent if all the meta boxes are set to not show in the preferences. I remember your comment elsewhere that a region should not be conditionally rendered. However, that’s already an issue for other regions in the interface so this seems acceptable. It also seems less bad than the other regions which are more frequently/easily toggled in or out of existence.

> I suspect using the `NavigableRegion` component would break the `Resizablebox` functionality.

If so, I would guess it’s because `NavigableRegion` doesn’t accept a `ref` prop and that’d be a simple thing to fix. I’ll test it out.

**Comment by joedolson** [comment]
> I remember your comment elsewhere that a region should not be conditionally rendered. 

I don't think that applies in this case. A region shouldn't be conditionally rendered on the fly, but whether or not to show metaboxes is a persistent conditional. Once set, the region is always present. This is different from examples like the Document overview, which is only present when toggled, and persistent across different editor views.

**Comment by stokesman** [comment]
> I don't think that applies in this case

Thanks for elaborating. I thought the same and you explained the reasoning more clearly.

I’ve pushed a couple commits. The first one to create the navigable region and the second to (fully) hide the contents if collapsed. I did so to force the question of whether with a labeled navigable region if that makes it acceptable to hide its contents when not expanded. If not, then don’t we need to add logic to expand the area when focus enters its contents so to avoid invisible tab stops?

**Comment by t-hamano** [comment]
Test results using NVDA:


https://github.com/user-attachments/assets/17fc0c0c-7942-424e-8c17-af9cceece31e

File: packages/edit-post/src/components/layout/index.js (hunk 1 above)
Comment (DaniGuardiola) [reply packages/edit-post/src/components/layout/index.js]: I'm missing the context here, but my 2cents are that 1. "actualize" just sounds odd to me in this context and 2. "update" instantly hints to something being up-to-date (in this case it seems to imply "keeping DOM properties up-to-date" from what I understood of your response) so it seems okay. FWIW, "apply" also sounds okay to me - and if more accurate, then that'd be my preference over "update". "affect" feels weird to me.

Also, this immediately stood out to me because many native spanish speakers tend to use that word when they really mean "update", because update is "actualizar" in Spanish so it's a very common ["false friend"](https://en.wikipedia.org/wiki/False_friend).

In any case, I don't have the context, so this is a very optional nit based on a very quick and shallow look at the code, and I'm personally okay with any choice you make here :)

Comment (DaniGuardiola) [reply packages/edit-post/src/components/layout/index.js]: Btw, I don't disagree "actualize" is a technically correct description of what the function does. It's just not a very accessible word, especially to non-native speakers, and it's not that commonly used. I think it's the first time I've personally seen it outside of a philosophy or psychology context (or a fellow native Spanish speaker wrongly using it in place of "update"). So that's what I mean by odd, no more no less.

I don't know if you chose the original naming - FWIW I think if intentional, it's an interesting choice that can lead to some interesting linguistic conversations, however my points here are purely rooted in practicality :P

**Comment by t-hamano** [comment]
I think we're ready to ship this PR, but what do you think? I'd be grateful for additional accessibility feedback.

**Comment by afercia** [comment]
> If so, I would guess it’s because NavigableRegion doesn’t accept a ref prop and that’d be a simple thing to fix. I’ll test it out.

I see `NavigableRegion` is now wrapped within a `forwardRef` and to my understanding that solves the issue, correct? 

> to (fully) hide the contents if collapsed. I did so to force the question of whether with a labeled navigable region if that makes it acceptable to hide its contents when not expanded. If not, then don’t we need to add logic to expand the area when focus enters its contents so to avoid invisible tab stops?

An entirely empty navigable region (which is an ARIA landmark) wouldn't be ideal. This is a problem for other regions in teh editor. However, to my understanding, the `hidden` attribute is set on the meta boxes _content_. If that's correct, the landmark isn't entirely empty. It does contain the heading the move buttons (conditionally shown) and more importantly the toggle button to expand the _content_. If that's correct I think it's perfectly OK and it functionally follows the pattern used for example for the Publish region, which contains the toggle button (only revealed on focus) when ht epanel is collapsed. Screenshot:

Screenshot 2024-10-07 at 12 27 38

**Comment by stokesman** [comment]
> I see `NavigableRegion` is now wrapped within a `forwardRef` and to my understanding that solves the issue, correct?

Yes, that makes sure resizing added by `ResizableBox` works.

> If that's correct, the landmark isn't entirely empty.

When collapsed it contains only the button to expand its contents. It is like the Publish region except it’s visible even when not focused.

File: packages/edit-post/src/components/layout/index.js (hunk 1 above)
Comment (stokesman) [reply packages/edit-post/src/components/layout/index.js]: Thanks for elaborating. I concur "actualize" is uncommon enough that it may fail to add any clarity. So I’ve renamed the functions that were using it b1b0ad2ec75640ae9c2b244724ea08fc7addd8cf. It is interesting about the false friend status of actualize and actualizar. I would have to admit my willingness to use "actualize" is influenced by Spanish as a second language though not in place of "update". Merely that I think the word might be underused in English.

**Review by t-hamano — APPROVED** [review]
All accessibility concerns appear to be resolved, so it looks like it's ready to ship.

Let's merge this PR so it gets backported into WP 6.7 Beta 3.
