### PR TITLE
ESLint Plugin: Fix Babel config resolution when a custom ESLint config present

### LINKED ISSUE #37096: Babel related issue when custom .eslintrc is available in project
### Description

I use @wordpress/scripts for most themes / plugins that needs some sort of compiling, and other than the prettier paren-spacing issue it has been working great.

Now I set up a repo for a new theme, just the theme, and it seems like the combination of the file structure and a .eslint beeing present in root of project generates the following error when linting:

```
Parsing error: No Babel config file detected for ..../src/index.js. Either disable config file checking with requireConfigFile: false, or configure Babel so that it can find the config files.
```

### Step-by-step reproduction instructions

I have made a repo for reproducing this issue: https://github.com/kimmenbert/wordpress-scripts-babel-issue

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by gziolo**
## Description

Fixes #37096.

> Now I set up a repo for a new theme, just the theme, and it seems like the combination of the file structure and a .eslint beeing present in root of project generates the following error when linting:
>
> ```
> Parsing error: No Babel config file detected for ..../src/index.js. Either disable config file checking with requireConfigFile: false, or configure Babel so that it can find the config files.
> ```

## How has this been tested?

You can use the reproduction repo https://github.com/kimmenbert/wordpress-scripts-babel-issue shared by @kimmenbert.

I also created a new project with:

```
npx @wordpress/create-block my-block
cd my-block
```

I created `.eslintrc` file with:

```json
{
  "extends":  [ "plugin:@wordpress/eslint-plugin/recommended" ]
}
```

The last step is the most tricky as you need to patch the `node_modules/@wordpress/eslint-plgin` with the changes applied in this branch in this file:

https://github.com/WordPress/gutenberg/blob/f457352eda91ea733a0eed8e1f2b8910b494650f/packages/eslint-plugin/configs/esnext.js

Linting should work correctly when running:

`npx wp-scripts lint-js`

## Types of changes

Bug fix (non-breaking change which fixes an issue).

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [-] My code follows the accessibility standards. 
- [-] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/eslint-plugin/configs/esnext.js [hunk 1]
```diff
@@ -45,3 +51,16 @@ module.exports = {
 		'template-curly-spacing': [ 'error', 'always' ],
 	},
 };
+
+const result = cosmiconfigSync( 'babel' ).search();
```
Comment (gziolo) [inline packages/eslint-plugin/configs/esnext.js:57]: There is a known limitation in `cosmiconfig`: https://github.com/davidtheclark/cosmiconfig/issues/24. Support for `babel.config.json` is missing, so when you want to test with a custom config you need to use a different name like `babel.config.js`.

Comment (ryelle) [reply packages/eslint-plugin/configs/esnext.js:57]: I think you meant to link to this issue: https://github.com/davidtheclark/cosmiconfig/issues/246

This means if someone is using `babel.config.json`, eslint won't recognize it, and will use the default parser to run? Is that something common enough that it should get documented?

**Review by ryelle — APPROVED** [review]
I swapped out the `eslint-plugin` package in my project, removed my local `parserOptions` fix, and it succeeded without error 👍🏻

File: packages/eslint-plugin/configs/esnext.js (hunk 1 above)
Comment (gziolo) [reply packages/eslint-plugin/configs/esnext.js:57]: > I think you meant to link to this issue: [davidtheclark/cosmiconfig#246](https://github.com/davidtheclark/cosmiconfig/issues/246)

Ooops, thanks for correcting it.
 
> This means if someone is using `babel.config.json`, eslint won't recognize it, and will use the default parser to run? Is that something common enough that it should get documented?

I will add a note in the codebase and the changelog so we can revisit that in the future but I would expect that it gets resolved in the `comsiconfig` package because there is an open PR https://github.com/davidtheclark/cosmiconfig/pull/255 that addresses it. It's also there sitting for a few months so I hope to learn what needs to happen to get in included.

Comment (gziolo) [reply packages/eslint-plugin/configs/esnext.js:57]: Done with https://github.com/WordPress/gutenberg/pull/37406/commits/804eee012835478e6da8f6b43ae4b947e4ea9ab4.

**Comment by gziolo** [comment]
@anton-vlasenko, I cherry-picked this PR to the upcoming Gutenberg plugin 12.2 (branch `release/12.2`). I don't think there is anything you need to do with it. I want to publish WordPress packages to npm with the `next` dist-tag (development version) and the release script uses the most recent Gutenberg release branch as a source.

**Comment by anton-vlasenko** [comment]
> I cherry-picked this PR to the upcoming Gutenberg plugin 12.2 (branch release/12.2). 

@gziolo Awesome. Thank you for cherry-picking it.

**Comment by gziolo** [comment]
It's now available for testing on npm with:
```
npm install --save-dev @wordpress/eslint-plugin@next
```

The stable version should be available in the second half of January.
