### PR TITLE
Fix Color Picker Angle Reset on Gradient Type Change

### LINKED ISSUE #72433: Add a default linear gradient degree setting in the GradientPicker
## What problem does this address?
At the moment, if you set a default linear gradient in the gradient picker with a 180deg angle, or you setup a gradient with anything other than a 90 degree angle, when a user switches between Radial and Linear in the select dropdown, the angle always resets to 90deg as a default. 

## What is your proposed solution?
Could we add a block setting attribute to set the default linear angle?

### PR DESCRIPTION
**Pull request by Vedant-Gandhi**
## What?
Closes https://github.com/WordPress/gutenberg/issues/72433

## Why?
When we switch the gradient type in color picket from linear to radial and then back to linear the selected angle in linear resets.

## How?
Add logic to memoize the last angle selected.

## Demo

https://github.com/user-attachments/assets/b3cd818c-80e5-4052-afc8-b52509f899d1

### CODE REVIEW

File: packages/components/src/custom-gradient-picker/index.tsx [hunk 1]
```diff
@@ -70,14 +67,27 @@ const GradientTypePicker = ( {
 	onChange,
 }: GradientTypePickerProps ) => {
 	const { type } = gradientAST;
+	const lastLinearOrientation = useRef< AngularNode >(
```
Comment (mirka) [inline packages/components/src/custom-gradient-picker/index.tsx]:
```diff
diff --git a/packages/components/src/custom-gradient-picker/index.tsx b/packages/components/src/custom-gradient-picker/index.tsx
index 164562c23c9..0d951e8a66b 100644
--- a/packages/components/src/custom-gradient-picker/index.tsx
+++ b/packages/components/src/custom-gradient-picker/index.tsx
@@ -1,7 +1,7 @@
 /**
  * External dependencies
  */
-import { type AngularNode, type LinearGradientNode } from 'gradient-parser';
+import { type LinearGradientNode } from 'gradient-parser';
 
 /**
  * WordPress dependencies
@@ -67,27 +67,23 @@ const GradientTypePicker = ( {
 	onChange,
 }: GradientTypePickerProps ) => {
 	const { type } = gradientAST;
-	const lastLinearOrientation = useRef< AngularNode >(
-		( gradientAST.orientation as AngularNode ) ?? {
-			type: 'angular',
-			value: `${ DEFAULT_LINEAR_GRADIENT_ANGLE }`,
-		}
-	);
+	const lastLinearAngle = useRef( DEFAULT_LINEAR_GRADIENT_ANGLE );
 
-	if ( type === 'linear-gradient' && gradientAST.orientation ) {
-		lastLinearOrientation.current = gradientAST.orientation as AngularNode;
+	if (
+		type === 'linear-gradient' &&
+		gradientAST.orientation?.type === 'angular'
+	) {
+		lastLinearAngle.current = Number( gradientAST.orientation.value );
 	}
 
 	const onSetLinearGradient = () => {
 		onChange(
 			serializeGradient( {
 				...gradientAST,
-				orientation:
-					lastLinearOrientation.current ??
-					( {
-						type: 'angular',
-						value: `${ DEFAULT_LINEAR_GRADIENT_ANGLE }`,
-					} as const ),
+				orientation: {
+					type: 'angular',
+					value: `${ lastLinearAngle.current }`,
+				},
 				type: 'linear-gradient',
 			} satisfies LinearGradientNode )
 		);
```

Comment (mirka) [reply packages/components/src/custom-gradient-picker/index.tsx]: Something like this may be simpler, safer, and avoid all the `as` casting.

**Review by mirka — COMMENTED** [review]
Approach looks good overall 👍  Can we also add tests to cover this new behavior?

The native counterpart (`index.native.js`) has the same pattern of stripping orientation when switching to radial, so it likely has the same issue. Out of scope for this PR, but worth noting here. Maybe it's fine to leave it that way, since we're migrating away from the React Native implementation.

File: packages/components/src/custom-gradient-picker/index.tsx (hunk 1 above)
Comment (Vedant-Gandhi) [reply packages/components/src/custom-gradient-picker/index.tsx]: Yes, this works like a charm and reduces the unnecessary complexity.

Comment (Vedant-Gandhi) [reply packages/components/src/custom-gradient-picker/index.tsx]: Hi @mirka, Thanks for the detailed feedback and suggestions. I have added the test cases and implemented the suggested approach for type hinting. Let me know if any further improvements are needed.

File: packages/components/CHANGELOG.md [hunk 2]
```diff
@@ -7,6 +7,7 @@
 -   Revert `word-break: break-word` addition ([#76230](https://github.com/WordPress/gutenberg/pull/76230)).
 -   `VisuallyHidden`: Add `word-break: normal` to prevent text wrapping issues in screen reader content ([#75539](https://github.com/WordPress/gutenberg/pull/75539)).
 -   `DateTimePicker`: Fix error that occurs when selecting a day outside the valid days for a month (e.g. February 30) ([#76400](https://github.com/WordPress/gutenberg/pull/76400)).
+- `GradientAnglePicker`: Add state persistence when switching between Linear and Radial Gradient.([#76595](https://github.com/WordPress/gutenberg/pull/76595))
```
Comment (ciampo) [inline packages/components/CHANGELOG.md]: Spacing + mentioning the correct public-facing component:

```suggestion
-   `CustomGradientPicker `: Add state persistence when switching between Linear and Radial Gradient.([#76595](https://github.com/WordPress/gutenberg/pull/76595))
```

File: packages/components/src/custom-gradient-picker/index.tsx [hunk 3]
```diff
@@ -70,14 +67,22 @@ const GradientTypePicker = ( {
...
+		);
+	}
 
 	const onSetLinearGradient = () => {
 		onChange(
 			serializeGradient( {
 				...gradientAST,
-				orientation: gradientAST.orientation
-					? undefined
-					: HORIZONTAL_GRADIENT_ORIENTATION,
```
Comment (ciampo) [inline packages/components/src/custom-gradient-picker/index.tsx:80]: This PR introduces a subtle behaviour change: before this PR, switching from radial → linear for the first time used `HORIZONTAL_GRADIENT_ORIENTATION` (90°, i.e. left-to-right). With the new code, the fallback is `DEFAULT_LINEAR_GRADIENT_ANGLE` (180°, i.e. top-to-bottom).

I don't think this is a breaking change, but we should either:

- change the code to restore the original behaviour;
- document it explicitly in the changelog

File: packages/components/src/custom-gradient-picker/index.tsx [hunk 4]
```diff
@@ -70,14 +67,22 @@ const GradientTypePicker = ( {
...
+				orientation: {
+					type: 'angular',
+					value: `${ lastLinearOrientationAngle.current }`,
+				} as const,
```
Comment (ciampo) [inline packages/components/src/custom-gradient-picker/index.tsx]: Can we restrict the type narrowing to the `angular` string?

```suggestion
				orientation: {
					type: 'angular' as const,
					value: `${ lastLinearOrientationAngle.current }`,
				},
```

File: packages/components/CHANGELOG.md [hunk 5]
```diff
@@ -7,6 +7,7 @@
 -   Revert `word-break: break-word` addition ([#76230](https://github.com/WordPress/gutenberg/pull/76230)).
 -   `VisuallyHidden`: Add `word-break: normal` to prevent text wrapping issues in screen reader content ([#75539](https://github.com/WordPress/gutenberg/pull/75539)).
 -   `DateTimePicker`: Fix error that occurs when selecting a day outside the valid days for a month (e.g. February 30) ([#76400](https://github.com/WordPress/gutenberg/pull/76400)).
+-   `CustomGradientPicker`: Add state persistence when switching between Linear and Radial Gradient.([#76595](https://github.com/WordPress/gutenberg/pull/76595))
```
Comment (ciampo) [inline packages/components/CHANGELOG.md]: Super nit

```suggestion
-   `CustomGradientPicker`: Add state persistence when switching between Linear and Radial Gradient.([#76595](https://github.com/WordPress/gutenberg/pull/76595)).
```

File: packages/components/src/custom-gradient-picker/test/index.tsx [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+
+			// Verify the angle from before the radial switch is restored, not the default
+			const lastCall =
+				onChange.mock.calls[ onChange.mock.calls.length - 1 ][ 0 ];
+			expect( lastCall ).toContain(
+				'linear-gradient(90deg,rgb(0,0,0) 0%,rgb(255,255,255) 100%)'
+			);
+		} );
+
+		it( 'should use DEFAULT_LINEAR_GRADIENT_ANGLE when no prior linear angle exists', async () => {
```
Comment (ciampo) [inline packages/components/src/custom-gradient-picker/test/index.tsx]: Test name out of date?

```suggestion
		it( 'should use HORIZONTAL_GRADIENT_ORIENTATION when no prior linear angle exists', async () => {
```

File: packages/components/src/custom-gradient-picker/test/index.tsx [hunk 7]
```diff
@@ -0,0 +1,85 @@
...
+			} );
+			await user.selectOptions( typeSelect, 'radial-gradient' );
+			await user.selectOptions( typeSelect, 'linear-gradient' );
+
+			// Verify the angle from before the radial switch is restored, not the default
+			const lastCall =
+				onChange.mock.calls[ onChange.mock.calls.length - 1 ][ 0 ];
+			expect( lastCall ).toContain(
+				'linear-gradient(90deg,rgb(0,0,0) 0%,rgb(255,255,255) 100%)'
+			);
```
Comment (ciampo) [inline packages/components/src/custom-gradient-picker/test/index.tsx]: This assertion may be overly specific to how the streing is formatted, potentially we could do something like

```js
expect( lastCall ).toContain( '90deg' );
```

File: packages/components/src/custom-gradient-picker/test/index.tsx [hunk 8]
```diff
@@ -0,0 +1,85 @@
...
+			const typeSelect = screen.getByRole( 'combobox', {
+				name: /type/i,
+			} );
+			await user.selectOptions( typeSelect, 'linear-gradient' );
+
+			const lastCall =
+				onChange.mock.calls[ onChange.mock.calls.length - 1 ][ 0 ];
+			expect( lastCall ).toContain(
+				'linear-gradient(90deg,rgb(0,0,0) 0%,rgb(255,255,255) 100%)'
+			);
```
Comment (ciampo) [inline packages/components/src/custom-gradient-picker/test/index.tsx]: Same here re. `expect( lastCall ).toContain( '90deg' );`

File: packages/components/CHANGELOG.md [hunk 9]
```diff
@@ -7,6 +7,7 @@
 -   Revert `word-break: break-word` addition ([#76230](https://github.com/WordPress/gutenberg/pull/76230)).
 -   `VisuallyHidden`: Add `word-break: normal` to prevent text wrapping issues in screen reader content ([#75539](https://github.com/WordPress/gutenberg/pull/75539)).
 -   `DateTimePicker`: Fix error that occurs when selecting a day outside the valid days for a month (e.g. February 30) ([#76400](https://github.com/WordPress/gutenberg/pull/76400)).
+-   `CustomGradientPicker`: Add state persistence when switching between Linear and Radial Gradient.([#76595](https://github.com/WordPress/gutenberg/pull/76595)).
```
Comment (ciampo) [inline packages/components/CHANGELOG.md]: We may need to rebase and move the CHANGELOG entry to the latest "unreleased" section, since new versions of the packages have just been released

Comment (ciampo) [inline packages/components/CHANGELOG.md]: Nit: not `.` before the parenthesis

```suggestion
-   `CustomGradientPicker`: Add state persistence when switching between Linear and Radial Gradient ([#76595](https://github.com/WordPress/gutenberg/pull/76595)).
```

**Review by ciampo — APPROVED** [review]
LGTM 🚀  Thank you for working on this!

We can merge after last CHANGELOG feedback is addressed

**Comment by ciampo** [comment]
E2E failures don't seem related, merging anyway when all remaining tests have passed.
