### PR TITLE
[ Latest Posts ] Fix link for read more markup

### LINKED ISSUE #20783: [ Latest Posts ] Markup issue for Read more link inside the editor
Inside the editor, the markup for the Read more link (href attribute) is missing double-quotes. As a result, the target attribute is concatenated to the URL (e.g. `http://localhost/gutenberg/2020/03/11/hello-world/target=_blank`) which creates wrong links.
[L336-L338](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/latest-posts/edit.js#L336-L338):
```
' ... <a href=' +
	post.link +
	'target="_blank" rel="noopener noreferrer">' +
```

### PR DESCRIPTION
**Pull request by draganescu**
## Description
Fixes #20783

## How has this been tested?
1. Make sure you have some posts
2. Add a page or post
3. Add a LatestPosts block
4. Set the block to show post content > excerpt
5. Check that the URL of the read more link is correct

## Screenshots 

Screenshot 2020-03-16 at 10 48 45

### CODE REVIEW

**Review by adamziel — APPROVED** [review]
Works perfectly!

**Review by adamziel — APPROVED** [review]

File: packages/block-library/src/latest-posts/edit.js [hunk 1]
```diff
@@ -360,9 +360,9 @@ class LatestPostsEdit extends Component {
 										.trim()
 										.split( ' ', excerptLength )
 										.join( ' ' ) +
-								  ' ... <a href=' +
+								  ' ... <a href="' +
 								  post.link +
-								  'target="_blank" rel="noopener noreferrer">' +
+								  '" target="_blank" rel="noopener noreferrer">' +
 								  __( 'Read more' ) +
 								  '</a>'
```
Comment (youknowriad) [inline packages/block-library/src/latest-posts/edit.js]: Any reason why we're concatening HTML and using `RawHTML`. security-wise, it seems better to just use JSX.

Comment (draganescu) [reply packages/block-library/src/latest-posts/edit.js]: i don't think there is a reason :)

**Comment by jorgefilipecosta** [comment]
Merging this PR as it was approved and seems to fix the problem.
I think as a follow up we should refactor to avoid RawHTML and rely on jsx.

File: packages/block-library/src/latest-posts/edit.js (hunk 1 above)
Comment (mcsf) [reply packages/block-library/src/latest-posts/edit.js]: @draganescu, can you prioritise a fix?

Comment (draganescu) [reply packages/block-library/src/latest-posts/edit.js]: Howdy @youknowriad and @mcsf a fix is ready in #21170
