### PR TITLE
Query Loop: Don't show publicly non-queryable taxonomies

### LINKED ISSUE #59257: Query block taxonomy filter does not work on frontend if taxonomy is not set to publicly_queryable
### Description

When `publicly_queryable` is set to `false` for a custom taxonomy, it can still be selected in the query block filter criteria (and filters properly in the editor) but does not properly filter on the frontend.

Ideally, filtering would remain working even when a taxonomy is set to not be `publicly_queryable`.

### Step-by-step reproduction instructions

1. Register a custom taxonomy with `publicly_queryable` set to `false`, and apply it to a post type.
2. Add some terms to the taxonomy.
3. Create some sample posts with a variety of terms selected.
4. Add a query block to a test page and filter for one of the terms used in your sample posts.

You should notice the list of posts properly filtered in the editor, but once you save the page and view it on the frontend, all posts will appear.

This issue is also described in this comment from over a year ago: https://github.com/WordPress/gutenberg/issues/41067#issuecomment-1404849467

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WP version 6.4.3
- Twenty Twenty-Four theme
- Gutenberg plugin 17.7.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #59257

## What?

This PR excludes taxonomies with `publicly_queryable` set to `false` from the Filter panel in the Query Loop block.

## Why?

The behavior of the Query Loop block must be consistent in the editor and front end. My understanding is that `publicly_queryable` defines whether it is queryable on the front end, and if the value is `false`, the query results will not be displayed. Therefore, I don't think the editor should display taxonomies where `publicly_queryable` is `false` in the first place.

## How?

Display only taxonomies for which `publicly_queryable` is `true` in the Filters panel. This approach is consistent elsewhere, as noted in [this comment](https://github.com/WordPress/gutenberg/issues/59257#issuecomment-1958671953).

## Testing Instructions

- Add the following code to the `gutenberg.php` file. This code adds queryable and non-queryable taxonomies to Post and Page, respectively.
  ```php
  function add_taxonomies() {
  	register_taxonomy( 'queryable_post_taxonomy', array( 'post' ), array(
  		'public'             => true,
  		'publicly_queryable' => true,
  		'show_in_rest' 		   => true,
  		'label'              => 'Queryable Post Taxonomy',
  	) );
  	register_taxonomy( 'non_queryable_post_taxonomy', array( 'post' ), array(
  		'public'             => true,
  		'publicly_queryable' => false,
  		'show_in_rest' 		   => true,
  		'label'              => 'Non Queryable Post Taxonomy',
  	) );
  	register_taxonomy( 'queryable_page_taxonomy', array( 'page' ), array(
  		'public'             => true,
  		'publicly_queryable' => true,
  		'show_in_rest' 		   => true,
  		'label'              => 'Queryable Page Taxonomy',
  	) );
  	register_taxonomy( 'non_queryable_page_taxonomy', array( 'page' ), array(
  		'public'             => true,
  		'publicly_queryable' => false,
  		'show_in_rest' 		   => true,
  		'label'              => 'Non Queryable Page Taxonomy',
  	) );
  }
  add_action( 'init', 'add_taxonomies' );
  ```
- Insert a Query Loop block in the Post Editor.
- Open the Filters panel. Taxonomies where `publicly_queryable` is `false` should not be displayed.

## Screenshots or screencast 

| Before | After |
|--------|--------|
| image| image |

### CODE REVIEW

File: packages/block-library/src/query/utils.js [hunk 1]
```diff
@@ -131,16 +131,16 @@ export const useTaxonomies = ( postType ) => {
...
 				type: postType,
 				per_page: -1,
-				context: 'view',
 			} );
-			return filteredTaxonomies;
 		},
 		[ postType ]
 	);
-	return taxonomies;
+	return taxonomies?.filter(
```
Comment (ntsekouras) [inline packages/block-library/src/query/utils.js]: Probably it's better to `useMemo` here to avoid extra rerenders.

**Review by ntsekouras — APPROVED** [review]
Thanks for the fix! I've left a small comment to address and after that, it would be good to land.

**Comment by t-hamano** [comment]
@ntsekouras Thanks for the review!

I added `useMemo` exactly like [this implementation](https://github.com/WordPress/gutenberg/blob/184e4ad4f7cb063fd628b20024a621221d3edb5c/packages/edit-site/src/components/add-new-template/utils.js#L94-L98). I would like to merge it as soon as it passes the tests, as it works correctly as before.

**Comment by eric-michel** [comment]
I'd like to make one more pitch to revert this change and instead fully allow for filtering based on taxonomies with `publicly_queryable` set to `false`. I agree with the idea that `publicly_queryable` being set to `false` should prevent the editor from displaying terms in that taxonomy. But the Query Loop isn't displaying terms, it's displaying _posts_. And just as a `tax_query` can still be run against a taxonomy with `publicly_queryable` set to `false`, so should the Query Loop block.

There are many applications in which I would like to have a taxonomy that does not generate archive pages but does allow me to filter posts by that taxonomy in the Query Loop. Unfortunately, unlike custom post types, the `register_taxonomy` function does not include a `has_archive` argument that lets me turn off term archives, which means `publicly_queryable` is my only option.

As this functions now, accomplishing what should be a relatively mundane task is onerous. In order to filter the Query Loop by a taxonomy that does not create archives for its terms, I have to:

- write a function to return a 404 when a term archive is accessed
- rewrite the site search query so site search results do not return term archives
- write a function to filter our SEO plugin's sitemap so that it does not include the term archives in the sitemap

All of this instead of simply setting `publicly_queryable` to `false` and allowing me to still filter by it in the Query Loop block, as I can do in a `tax_query`.

**Comment by t-hamano** [comment]
@eric-michel Thanks for the reply.

This PR just doesn't display taxonomies where `publicly_queryable` is `false` as UI. Internally, you should be able to set any taxonomy to the query. In other words, rewrite the following parts in the code editor. Is this helpful to you?

taxonomy

**Comment by eric-michel** [comment]
@t-hamano I was not aware that was possible; that is definitely helpful! Thank you!

I would still love for the taxonomy to be visible in the UI for ease of use, if there's any chance for a change there. More options are always better, as far as I'm concerned.

**Comment by eric-michel** [comment]
@t-hamano I reviewed a site I have in development. Since it does not use the Gutenberg plugin, the Query block still allows me to select a taxonomy that is set to `publicly_queryable: false`. When I do that, it appears to add the `taxQuery` property in the code editor, as in your example of adding this manually, but it does not properly filter for that `taxQuery` on the frontend. Won't this still be the case in the future if I add this manually via the code editor?

Here's what I'm seeing generated from the UI:
```
<!-- wp:query {"queryId":10,"query":{"perPage":6,"pages":0,"offset":0,"postType":"map-point","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"exclude","inherit":false,"taxQuery":{"map-point-category":[9]}},"align":"wide","layout":{"type":"default"}} -->
```

**Comment by t-hamano** [comment]
> but it does not properly filter for that `taxQuery` on the frontend. 

This is expected behavior and is not due to the influence of this PR. The front end builds the query via the `build_query_vars_from_query_block` function, but only if its taxonomy is "viewable" it will be added to the query.

https://github.com/WordPress/wordpress-develop/blob/45ec568f0ce905b9aabfb469b613e39d042ad3b7/src/wp-includes/blocks.php#L1989-L1995

My guess is that you can use [query_loop_block_query_vars](https://developer.wordpress.org/reference/hooks/query_loop_block_query_vars/) filter hook to manually add taxonomies to the query.
