### PR TITLE
Fixes the checkbox appearance

### LINKED ISSUE #17564: Sidebar - Checkbox: Background color AND icon is blue
Noticed that the background + icon for the category checkbox was blue (when checked)

**To reproduce**
1. Create a new post
2. Scroll down to "Categories" (right sidebar)
3. Expand
4. See the checkbox

**Expected behavior**
For the checkbox' background to be transparent (or white)

**Screenshots**
Screen Shot 2019-09-24 at 9 49 17 PM

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave
 - Browser: Chrome 77.0.3865.90
 - Version WP 5.3-beta1-46288

### PR DESCRIPTION
**Pull request by draganescu**
## Description
Fixes #17564 

## How has this been tested?
Tested locally.

## Screenshots 

Screenshot 2019-09-25 at 12 17 11

## Types of changes
Used a `CheckboxControl` component for the taxonomy list.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js [hunk 1]
```diff
@@ -319,15 +318,16 @@ class HierarchicalTermSelector extends Component {
 			const id = `editor-post-taxonomies-hierarchical-term-${ term.id }`;
 			return (
 				<div key={ term.id } className="editor-post-taxonomies__hierarchical-terms-choice">
-					<input
+					<CheckboxControl
 						id={ id }
```
Comment (epiqueras) [inline packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js]: This doesn't need an `id`.

File: packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js [hunk 2]
```diff
@@ -319,15 +318,16 @@ class HierarchicalTermSelector extends Component {
...
-						className="editor-post-taxonomies__hierarchical-terms-input"
-						type="checkbox"
 						checked={ terms.indexOf( term.id ) !== -1 }
 						value={ term.id }
```
Comment (epiqueras) [inline packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js]: This doesn't take a `value`.

File: packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js [hunk 3]
```diff
@@ -319,15 +318,16 @@ class HierarchicalTermSelector extends Component {
...
-						onChange={ this.onChange }
+						onChange={ () => {
```
Comment (epiqueras) [inline packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js]: The previous approach was better, because it didn't create a new function on every render, and hence break equality checks.

File: packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js [hunk 4]
```diff
@@ -319,15 +318,16 @@ class HierarchicalTermSelector extends Component {
 			const id = `editor-post-taxonomies-hierarchical-term-${ term.id }`;
 			return (
 				<div key={ term.id } className="editor-post-taxonomies__hierarchical-terms-choice">
-					<input
+					<CheckboxControl
 						id={ id }
-						className="editor-post-taxonomies__hierarchical-terms-input"
```
Comment (epiqueras) [inline packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js]: We need to remove all the CSS and change all the e2e tests that used this `className` as a selector.

**Review by epiqueras — CHANGES_REQUESTED** [review]

File: packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js (hunk 4 above)
Comment (draganescu) [reply packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js]: 🤪

File: packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js (hunk 1 above)
Comment (draganescu) [reply packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js]: it does for the label for attribute :)

File: packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js (hunk 3 above)
Comment (draganescu) [reply packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js]: yes. but. the CheckboxControl hijacks the event of the click and returns only true or false and I need to get that id.

File: packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js (hunk 1 above)
Comment (epiqueras) [reply packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js]: Look at the implementation of the component. It uses `withInstanceId`.

File: packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js (hunk 3 above)
Comment (epiqueras) [reply packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js]: Maybe we should change `CheckboxControl` to add the full event as the second parameter to `onChange`.

Comment (youknowriad) [reply packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js]: Mind the mobile :) (events).

I think inline function are fine. We should optimize if we measure performance issues in that case. we can use things like `useCallback` if needed

Comment (epiqueras) [reply packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js]: >Mind the mobile :) (events).

Good point.

>`useCallback`

Yes.

File: packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js (hunk 4 above)
Comment (draganescu) [reply packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js]: attempt one

File: packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js (hunk 1 above)
Comment (draganescu) [reply packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js]: yes I noticed and removed my initial comment :D

Comment (epiqueras) [reply packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js]: :smile:

File: packages/e2e-tests/specs/taxonomies.test.js [hunk 5]
```diff
@@ -31,7 +31,7 @@ describe( 'Taxonomies', () => {
 		return page.evaluate(
 			() => {
 				return Array.from( document.querySelectorAll(
-					'.editor-post-taxonomies__hierarchical-terms-input:checked'
+					'.editor-post-taxonomies__hierarchical-terms-choice .components-checkbox-control__input:checked'
```
Comment (talldan) [inline packages/e2e-tests/specs/taxonomies.test.js]: The structure of the html is different now, there's an extra wrapper around the `input`, so on line 36 where there's a call to `node.parentElement.querySelector( 'label' )`, there's no label within the parentElement.

Could try using `node.closest` instead of `node.parentElement` to select the parent of the label (https://developer.mozilla.org/en-US/docs/Web/API/Element/closest).

**Review by talldan — COMMENTED** [review]
This would be a good fix to get in soon, I left some hints on how to fix the e2e tests.

**Comment by talldan** [comment]
I've added this to the WP 5.3 Must Have's project, but feel free to remove it if you disagree.

**Comment by draganescu** [comment]
Tests pass, review observations implemented.

**Review by epiqueras — APPROVED** [review]
