### PR TITLE
Global Styles: fix overflow caused by RangeControl tooltip

### LINKED ISSUE #65825: Global Styles: Unnecessary vertical scrollbar appears
### Description

**Note: This issue cannot be reproduced in WP6.7 Beta 1. It can be reproduced in the latest Gutenberg.**

A vertical scrollbar may appear in global styles even when the content does not need to scroll vertically.

This issue seems to occur when there is a `RangeControl` at the end of the content. You can see that the tooltip that appears when operating the slider overflows:

image

The tooltip is there even though it is not visually visible, which is why the overflow appears to occur.

### Step-by-step reproduction instructions

The easiest steps to reproduce this issue are:

- Activate any block theme.
- Go to the site editor.
- Open the Global Styles > Typography > Font size presets > Click "Add font size" button
- Click "New Font Size 1" item > Enable both "Fluid typography" and "Custom fluid values".

The steps above will render a RangeControl component at the end of your content, which should allow you to reproduce the issue.

You may also need to change your scrollbar display settings to reproduce this issue on a Mac.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/fd5aac13-bef7-402f-be9d-bf3654209f45

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by ciampo**
## What?

Fixes #65825

This PR fixes an involuntary overflow in the font size screen, in the Global Styles sidebar

## Why?

Fixing a visual glitch

## How?

As @ciampo and @t-hamano debugged in #65825, the cause for the overflow is the `RangeControl`'s tooltip.

The tooltip is a custom implementation (context for this decision can be found in https://github.com/WordPress/gutenberg/pull/19916 and https://github.com/WordPress/gutenberg/pull/23006).

This PR applies two separate fixes:

- it sets the tooltip to `display: none` when hidden. This seems safe because the tooltip already has a `aria-hidden` attribute set, and because it only replicates the same information that assistive technology can parse from the native `input` element. We can still animate the tooltip thanks to the recent [`@starting-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/@starting-style) and [`allow-discrete`](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-behavior) CSS apis, which should work in most browsers (and can be considered as progressive enhancement);
- It uses padding instead of margin for the bottom part of the screen, which removes the overflow when the tooltip is shown

> [!NOTE]
> `RangeControl` can clearly benefit from some love. We should see if we can use the `Tooltip` component, instead of a custom implementation. And potentially remove a lot of code, given the advancements in CSS styling of native inputs. Obviously not in scope for this PR. And potentially, we could just look at overhauling the whole set of slider-related components (see https://github.com/WordPress/gutenberg/issues/40507)

## Testing Instructions

Follow instructions in #65825 — the overflow bug should be gone.

## Screenshots or screencast 

https://github.com/user-attachments/assets/d2cd33c0-c839-4b6b-a732-753c89d4d0fe

### CODE REVIEW

File: packages/components/src/range-control/styles/range-control-styles.ts [hunk 1]
```diff
@@ -57,7 +57,10 @@ const wrapperMargin = ( { marks, __nextHasNoMarginBottom }: WrapperProps ) => {
 	return '';
 };
 
-export const Wrapper = styled.div< WrapperProps >`
+export const Wrapper = styled( 'div', {
+	shouldForwardProp: ( prop: string ) =>
+		! [ 'color', '__nextHasNoMarginBottom', 'marks' ].includes( prop ),
+} )< WrapperProps >`
```
Comment (ciampo) [inline packages/components/src/range-control/styles/range-control-styles.ts:63]: This change is not related to the fix, but rather an improvement that I applied while debugging the DOM rendered by `RangeControl`. I noticed that the value of the `color` prop was being applied as an attribute, which is not expected.

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

In my testing, the tooltip disappearance animation doesn't seem to work in Firefox. How about in your environment?

### Chrome 

https://github.com/user-attachments/assets/da14c1cf-9cd0-4eee-a76e-ba387b3f662b

### Firefox

https://github.com/user-attachments/assets/38ad5b20-c51e-4b89-ad96-55b6fbc35f1d


Maybe it's because Firefox only partially supports the `@starting-style` rule?

https://developer.mozilla.org/en-US/docs/Web/CSS/@starting-style#browser_compatibility

image

**Comment by ciampo** [comment]
> In my testing, the tooltip disappearance animation doesn't seem to work in Firefox. How about in your environment?
>
> Maybe it's because Firefox only partially supports the `@starting-style` rule?

Werid — I'd expect the "entry" animation not to work and the exit to work. I get the same behaviour on MacOS firefox. 

Although I wouldn't consider it blocking, since the animation is pure cosmetic here, and it should work when Firefox will add support for these APIs.

On the other hand, though, [`js-dom` doesn't seem to support `@starting-style`](https://github.com/jsdom/jsdom/issues/3236#issuecomment-2029781526), which is causing all of the unit test failures.

**Comment by ciampo** [comment]
I'm testing updating `jsdom` to latest stable version (`25.0.1`), since [version `24.1.0` has some changes](https://github.com/jsdom/jsdom/releases/tag/24.1.0) that could fix our test failures ("parse additional CSS constructs"). Let's see if that helps

**Comment by ciampo** [comment]
Extracted the update to jsdom here: https://github.com/WordPress/gutenberg/pull/65879

~If we're in a rush to merge this fix, I can remove changes to `RangeControl` and only keep the bottom padding changes.~

Rebased on top of `trunk` to include the `jsdom` update from #65879

**Review by tyxla — APPROVED** [review]
I confirm this fixes the bug 👍

**Comment by tyxla** [comment]
> In my testing, the tooltip disappearance animation doesn't seem to work in Firefox. How about in your environment?

Confirmed I see that in Firefox, although I think this isn't related to this PR, is it?

**Comment by t-hamano** [comment]
> > In my testing, the tooltip disappearance animation doesn't seem to work in Firefox. How about in your environment?
> 
> Confirmed I see that in Firefox, although I think this isn't related to this PR, is it?

I think it's related to this PR.

It might be that `allow-discrete` is not fully supported in Firefox. For example, if you make the following changes to this PR and do not apply `transition` to the `dispay` property, you should be able to confirm that both fade-in/fade-out work correctly in Firefox:

```diff
diff --git a/packages/components/src/range-control/styles/range-control-styles.ts b/packages/components/src/range-control/styles/range-control-styles.ts
index 6e9c68ace9..10175f57c6 100644
--- a/packages/components/src/range-control/styles/range-control-styles.ts
+++ b/packages/components/src/range-control/styles/range-control-styles.ts
@@ -265,13 +265,11 @@ export const InputRange = styled.input`
 
 const tooltipShow = ( { show }: TooltipProps ) => {
        return css`
-               display: ${ show ? 'inline-block' : 'none' };
+               display: inline-block;
                opacity: ${ show ? 1 : 0 };
 
                @media not ( prefers-reduced-motion ) {
-                       transition:
-                               opacity 120ms ease,
-                               display 120ms ease allow-discrete;
+                       transition: opacity 120ms ease;
                }
 
                @starting-style {
```

However, I think it's okay to proceed with this PR in the hope that Firefox will fully support it in the future.
