### PR TITLE
Fix: Cover block does not contain a class for predefined gradients

### LINKED ISSUE #20825: Block Patterns: Coverblock is missing a CSS class
When adding the gradient coverblock via the Block Patterns in 7.7.0
the `has-background-gradient` CSS class is missing from the wrapping div on the front.

The class is added correctly in the editor.

This means that the block does not look the same on the front and in the editor and that the default `opacity: 0.5;` of the dim is much more difficult to remove.

**To reproduce**
1. Add the coverblock from the Block Patterns.
2. Save
3. View the front
4. See the default 0.5 opacity dim cover the block.

-If I manually add a new cover block with the same gradient, or if I change the gradient of the existing block, then the class is added on the front.

**Expected behavior**
I expect the class to be added, so that block on the front looks identical to the block in the editor.

**Desktop (please complete the following information):**
 - OS:  Win10
 - Browser: Chrome Version 80.0.3987.132

**Additional context**
- Please add the version of Gutenberg you are using in the description.
Version 7.7.0

WordPress Version 5.3.2

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Fixes: https://github.com/WordPress/gutenberg/issues/20825

The class has-background-gradient was not present for predefined gradients on the frontend (it was present on the editor as expected). This caused a visual difference between the editor and the frontend.
This PR fixes the issue and adds the required class to the frontend.

## How has this been tested?
I added a cover image with a background image and a predefined gradient.
I verified the class has-background-gradient was part of the produced markup.
I created a cover block in the WordPress 5.4 RC with a background image and a predefined background. I pasted the markup produced and saved a post with it. I opened the post with Gutenberg on this branch and verified the block was not considered invalid and the class was automatically added to the markup.

### CODE REVIEW

**Comment by aduth** [comment]
In reviewing the discussion from #20825, it's not clear to me whether the class name is expected to be applied, or if it's a problem of the _styles_ of `has-background-gradient` needing to be applied when those `gradientClass` is also applied. Or was it considered practically infeasible, or better that the cover block styles not be "aware" of the full set of possible gradient variation classnames?

File: packages/block-library/src/cover/save.js [hunk 1]
```diff
@@ -64,7 +64,7 @@ export default function save( { attributes } ) {
 		{
 			'has-background-dim': dimRatio !== 0,
 			'has-parallax': hasParallax,
-			'has-background-gradient': customGradient,
+			'has-background-gradient': gradient || customGradient,
 			[ gradientClass ]: ! url && gradientClass,
```
Comment (aduth) [inline packages/block-library/src/cover/save.js]: There is at least one condition here `! url` (not sure if `gradientClass` can be falsey) in determining whether a gradient class is applied. Should that also be taken into consideration above when considering to apply `has-background-gradient`?

Comment (jorgefilipecosta) [reply packages/block-library/src/cover/save.js]: Hi @aduth when we have a gradient background, and a URL background we need to make the gradient background part of another element (we use a span just for that) and we apply the class to the other element that's why we use "! url && gradientClass". The idea of "has-background-gradient" is to allow targeting cover blocks that use a gradient background no matter if they also use an image background or not. I guess it would be possible to target the gradients using their gradients classes but themes can defined their own so one would need to use something like class attribute contains but that sounds hacky, also one would need to target the application of the class to this element or the span used when we don't have an image background. This class seems to make things easier.
The changes to the save make the save match what happens in the editor where we add the class provided that a gradient exists (custom or predefined). gradientClass will always be defined provided gradient attribute exists so "gradient || customGradient" or using "gradientClass || customGradient" is exactly the same.

Comment (aduth) [reply packages/block-library/src/cover/save.js]: So in the serialized output:

https://github.com/WordPress/gutenberg/blob/52417c6b13143bef1105952ce404ac6683a978ab/packages/e2e-tests/fixtures/blocks/core__cover__deprecated-5.serialized.html#L2

It's expected that the `has-background-gradient` class is on a different element (`div`) than the `has-midnight-gradient-background` element (`span`), when a `url` is assigned?

**Review by aduth — APPROVED** [review]

File: packages/block-library/src/cover/save.js (hunk 1 above)
Comment (jorgefilipecosta) [reply packages/block-library/src/cover/save.js]: Yes it is expected our selectors already rely on this e.g:"&.has-background-dim:not(.has-background-gradient)::before,".
