### PR TITLE
Fix: Hide  input popover when editing Math block as HTML

### LINKED ISSUE #72899: Math: When you select "Edit as HTML," the text area moves to the upper left corner of the editor.
### Description

When you select "Edit as HTML," the text area moves to the upper left corner of the editor.

### Step-by-step reproduction instructions

1. Open a post or page.
2. Insert a Math block. 
3. Enter the formula and select "Edit as HTML" from the options.
4. The text area will move to the upper left corner.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/d223c1ae-f48e-4881-b53d-30c442c06725

### Environment info

- WordPress 6.8
- Gutenberg  22.0.0-rc.1

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by sidharthpandita1**
## What?
Closes #72899

Fixes the issue where the LaTeX input textarea appears in the upper left corner when switching to 'Edit as HTML' mode in the Math block.

## Why?
When a user selects "Edit as HTML" from the Math block options, the LaTeX input popover (TextareaControl) continues to display because it only checks if the block is selected (`isSelected`), not whether it's in HTML editing mode. This causes the textarea to appear in an incorrect position (upper left corner) instead of being hidden during HTML editing.

## How?
- Added `useSelect` hook to check the block's editing mode using `getBlockMode` selector from `blockEditorStore`
- Added `clientId` prop to the component to identify the current block
- Updated the conditional rendering logic to hide the Popover when `isEditingAsHTML` is `true`
- The popover now only displays when the block is selected AND not in HTML editing mode

## Testing Instructions
1. Open a post or page in the block editor
2. Insert a Math block
3. Enter a LaTeX formula (e.g., `x^2` or `\frac{a}{b}`)
4. Click the three-dot menu (⋮) on the block toolbar
5. Select "Edit as HTML" from the options
6. ✅ Verify that the LaTeX input popover is hidden
7. The HTML textarea should display the block markup without the LaTeX input appearing in the corner
8. Click "Edit visually" to switch back
9. ✅ Verify that the LaTeX input popover appears again when the block is selected

### Testing Instructions for Keyboard
1. Open a post or page in the block editor
2. Insert a Math block using `/math` or the inserter
3. Type a LaTeX formula (e.g., `x^2`)
4. Press `Shift + Alt + Z` (Windows/Linux) or `Ctrl + Option + Z` (Mac) to open the block toolbar
5. Use arrow keys to navigate to the options menu (⋮) and press `Enter`
6. Use arrow keys to navigate to "Edit as HTML" and press `Enter`
7. ✅ Verify that the LaTeX input popover is hidden and focus moves to the HTML textarea
8. Press `Shift + Alt + Z` / `Ctrl + Option + Z` again and select "Edit visually"
9. ✅ Verify that the LaTeX input popover appears again and is accessible via keyboard

## Screenshots or screencast

https://github.com/user-attachments/assets/3a22b296-e353-45ba-a052-08fec8111461

The LaTeX input popover is properly hidden when editing the block as HTML.|

### CODE REVIEW

File: packages/block-library/src/math/edit.js [hunk 1]
```diff
@@ -31,6 +36,17 @@ export default function MathEdit( { attributes, setAttributes, isSelected } ) {
 	const { __unstableMarkNextChangeAsNotPersistent } =
 		useDispatch( blockEditorStore );
 
+	// Check if block is in HTML editing mode
+	const { isEditingAsHTML } = useSelect(
```
Comment (ntsekouras) [inline packages/block-library/src/math/edit.js:40]: Nit: we could return the boolean primitive and not an object.

**Review by ntsekouras — APPROVED** [review]
LGTM, thanks!
