### PR TITLE
Hide insertion point if a template lock exists.

### LINKED ISSUE #5531: In-between inserter ignores locking via template_lock
## Issue Overview
If you lock a template [as explained in the docs](https://wordpress.org/gutenberg/handbook/templates/#locking) you can afterwards still add new paragraph blocks by using the "in-between inserter".

## Steps to Reproduce (for bugs)

1. Define a template and set `template_lock` to `all` or `insert`
2. Edit a post
3. Click between the blocks defined by the template

## Expected Behavior

I'd expect the "in-between inserter" to be disabled as well by setting `template_lock` to `all` or `insert`

## Current Behavior

You can still insert paragraph blocks. Even if the   `core/paragraph` block type is disabled via `allowed_block_types`

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
The insertion point allows inserting a new block by clicking on it, when a template lock exists, insertion should not be possible.

Fixes: https://github.com/WordPress/gutenberg/issues/5531

## How Has This Been Tested?
Define a CPT with a template lock, verify it is not possible to insert block using the insertion point inserter if a template lock exists.

### CODE REVIEW

File: editor/components/block-list/block.js [hunk 1]
```diff
@@ -439,7 +439,7 @@ export class BlockListBlock extends Component {
 		// Insertion point can only be made visible when the side inserter is
 		// not present, and either the block is at the extent of a selection or
 		// is the last block in the top-level list rendering.
-		const shouldShowInsertionPoint = (
+		const shouldShowInsertionPoint = ! isLocked && (
```
Comment (aduth) [inline editor/components/block-list/block.js]: For the block movers, we assign `shouldShowMovers` without consideration of `isLocked`, and this consideration is managed by the `BlockMover` component itself. Should we do that here? Or at least align the two approaches one way or the other?

Comment (jorgefilipecosta) [reply editor/components/block-list/block.js]: Yes, we should be consistent, I updated the code to follow the same logic we now do the check for template locking inside BlockInsertionPointm, like we do for BlockMover.

**Comment by janeschindler** [comment]
I made a column layout today, locked the template, and still see an inserter point. Perhaps columns can't be locked from the page template?
Bildschirmfoto 2019-04-24 um 16 02 06

This is the code I'm using to make the template (part of it). I made a block called 'coltext' that only allows a limited number of options. Ideally the user shouldn't be able to add any blocks, except within the coltext block where they can only add the few I've specifically allowed there. 

`        'template_lock' 	 => 'all',
        'template' => array(
            array('core/paragraph', array('placeholder' => 'Text', 'className' => 'intro') ),	
            array('neuthalblocks/gmap', array() ),

			array( 'core/columns', array(), array(
				array( 'core/column', array(), array(
					array( 'core/columns', array(), array(
						array( 'core/column', array(), array(
							array( 'neuthalblocks/coltext', array() ),
						) ),
						array( 'core/column', array(), array(
							array( 'neuthalblocks/coltext', array() ),
						) ),
					) )
				) ),
				array( 'core/column', array(), array(
					array( 'core/columns', array(), array(
						array( 'core/column', array(), array(
							array( 'neuthalblocks/coltext', array() ),
						) ),
						array( 'core/column', array(), array(
							array( 'neuthalblocks/coltext', array() ),
						) ),
					) )
				) ),
			) ),
`

**Comment by aduth** [comment]
@janeschindler This was merged five days ago and hasn't yet landed in a Gutenberg plugin release, so I wouldn't expect you should see any difference yet. Gutenberg 5.6.0 will be released on Wednesday. If you are still having problems after the testing again the latest version, I'd recommend you open a new issue, as it will be the easiest way to track further improvements.
