### PR TITLE
Editor: Fix resetting the drop-zone states after dropping a file

### LINKED ISSUE #2597: Block tools not responding
Using Gutenberg 1.0, I was inserting an image into a post and wanted to adjust the layout. I dragged and dropped the image into Gutenberg image block (awesome), but when I tried to edit the layout using the toolbar, it wasn't responding.

image-layout

This seems to be happening for all blocks.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #2597

The dropzone classes were not being cleaned on drop which causes the dropzone to appear over the controls.

**Testings instructions**

 - Follow instructions ins #2597

### CODE REVIEW

File: components/drop-zone/provider.js [hunk 1]
```diff
@@ -68,7 +68,7 @@ class DropZoneProvider extends Component {
 		} );
 
 		this.dropzones.forEach( ( { updateState } ) => {
-			updateState( { isDraggingOverDocument, isDraggingOverElement: false, position: null } );
+			updateState( { isDraggingOverDocument: false, isDraggingOverElement: false, position: null } );
```
Comment (aduth) [inline components/drop-zone/provider.js]: Should consider splitting long line across multiple.

**Review by aduth — APPROVED** [review]

File: components/drop-zone/provider.js (hunk 1 above)
Comment (youknowriad) [reply components/drop-zone/provider.js]: we definitely need prettier 👍 one hour dev time gained per day :)

Comment (aduth) [reply components/drop-zone/provider.js]: [`object-curly-newline`](https://eslint.org/docs/rules/object-curly-newline) has options for configuring number of properties before newlines are required, **and** includes a fixer!

Comment (youknowriad) [reply components/drop-zone/provider.js]: Do you use the auto-fixer on IDE save? I never saw ESlint used for this, but yeah could be a good alternative for now 👍.

I'm using prettier "auto-save format" in other projects and it's really a huge gain.

Comment (youknowriad) [reply components/drop-zone/provider.js]: I found a similar config in VS Core, I'll be trying it for some days. I'm not adding the rule right now, but we should consider it in a separate PR.
