### PR TITLE
Fix: the description text of block movers for horizontal movement

### LINKED ISSUE #25158: Movers: description text for horizontal movement is incorrect with multiple selection
**Describe the bug**
Noticed while working on https://github.com/WordPress/gutenberg/pull/24894

Some blocks can be moved horizontally, for example the buttons in the "Buttons" block and the Social icons.

In this case, the mover buttons aria-label (and tooltip) correctly says "Move right" or "Move left" instead of down and up.

However, there's also some descriptive text used for the `aria-describedby` attribute that provides more info on the position etc. This descriptive text is correct when there's only one block selected. See in the screenshot below, with just one button selected the text is: "Move Button block from position 1 right to position 2":

Screenshot 2020-09-08 at 17 12 15

Instead, the text is _not_ correct when there's more than one block selected. See in the screenshot below, with two buttons selected the text is: "Move 2 blocks from position 1 down by one place":

Screenshot 2020-09-08 at 17 10 47

Where "down" is wrong and it should be "right".

Similarly, when moving to left. There's some logic in place to build these strings and it should be reviewed. Also, checking what happens with RTL languages is important.

**Editor version (please complete the following information):**
- WordPress version: 5.6 trunk
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? both
- If the Gutenberg plugin is installed, which version is it? 8.9.2

### PR DESCRIPTION
**Pull request by t-hamano**
Clone of #32337
Fix: #25158

This PR is newly created to reflect the latest trunk in #32337 sent from `thisissandip:fix/block-mover-description-text`.

## Description
The button to move the block has the following two accessibility attributes:

- `aria-label`: indicates the direction to move
- `aria-describedby`: Indicates where to move to or whether to move

This PR fixes a problem where the text indicated by `aria-describedby` does not consider the orientation if the layout orientation is horizontal.

## How has this been tested?
1. Select a block that can be moved horizontally (eg. Buttons Block)
2. Add 2 to 3 blocks to move them around
3. Select multiple blocks
4. Inspect the block mover buttons
5. The correct descriptive text should be displayed according to the orientation of the blocks

#### Select the first two blocks

horizontal_1

#### Select the two blocks in between

horizontal_2

#### Select the last two blocks

horizontal_3

#### Select the first two blocks

vertical_1

#### Select the two blocks in between

vertical_2

#### Select the last two blocks

vertical_3

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/block-editor/src/components/block-mover/mover-description.js [hunk 1]
```diff
@@ -65,13 +66,13 @@ export function getBlockMoverDescription(
...
 		// Moving down.
-		const movementDirection = getMovementDirection( 'down' );
+		const movementDirection = getMovementDirection( 'down', orientation );
 
 		if ( movementDirection === 'down' ) {
 			return sprintf(
 				// translators: 1: Type of block (i.e. Text, Image etc), 2: Position of selected block, 3: New position
 				__(
-					'Move %1$s block from position %2$d down to position %3$d'
+					`Move %1$s block from position %2$d down to position %3$d`
```
Comment (talldan) [inline packages/block-editor/src/components/block-mover/mover-description.js]: Was the change here needed?

File: packages/block-editor/src/components/block-mover/mover-description.js [hunk 2]
```diff
@@ -231,43 +234,88 @@ export function getMultiBlockMoverDescription(
...
+	orientation
 ) {
 	const position = firstIndex + 1;
 
-	if ( dir < 0 && isFirst ) {
-		return __( 'Blocks cannot be moved up as they are already at the top' );
-	}
+	if ( dir < 0 && ! isFirst ) {
+		// moving up
+		const movementDirection = getMovementDirection( 'up', orientation );
```
Comment (talldan) [inline packages/block-editor/src/components/block-mover/mover-description.js]: I think this function can also return 'right' if `isRTL()` is `true`, but there isn't an `if` statement below for 'right'. I think there's the same issue with most of the code below too.

It's probably easiest to replicate the logic from the `getBlockMoverDescription`. It could use the same ordering of `if` statements.

I also wonder whether `getMultiBlockMoverDescription` should have a description for when all blocks are selected and can't be moved in any direction. A bit like how `getBlockMoverDescription` has a case for when the only block is selected.

File: packages/block-editor/src/components/block-mover/mover-description.js [hunk 3]
```diff
@@ -65,13 +66,13 @@ export function getBlockMoverDescription(
 
 	if ( dir > 0 && ! isLast ) {
 		// Moving down.
-		const movementDirection = getMovementDirection( 'down' );
+		const movementDirection = getMovementDirection( 'down', orientation );
 
 		if ( movementDirection === 'down' ) {
 			return sprintf(
 				// translators: 1: Type of block (i.e. Text, Image etc), 2: Position of selected block, 3: New position
 				__(
```
Comment (talldan) [inline packages/block-editor/src/components/block-mover/mover-description.js]: I'm not an expert in i18n, but could an alternative option (instead of having separate `getBlockMoverDescription` and `getMultiBlockMoverDescription` functions that repeat the same logic) be to use the `_n` i18n function? (https://developer.wordpress.org/reference/functions/_n/)?

cc @tobifjellner I was wondering if you could advise on whether this fits the best practice for `_n`? 

Maybe it isn't possible to use `_n` with `sprintf` 🤔

**Review by talldan — COMMENTED** [review]
Thanks for addressing this and adding tests!

File: packages/block-editor/src/components/block-mover/mover-description.js (hunk 1 above)
Comment (t-hamano) [reply packages/block-editor/src/components/block-mover/mover-description.js]: Oh, that's my mistake 😢
I have fixed it.

**Comment by t-hamano** [comment]
Added condition when all blocks are selected:

select-all-blocks

File: packages/block-editor/src/components/block-mover/mover-description.js (hunk 2 above)
Comment (t-hamano) [reply packages/block-editor/src/components/block-mover/mover-description.js]: Thanks for pointing out the missing condition! I updated `getMultiBlockMoverDescription` with reference to `getBlockMoverDescription`.

File: packages/block-editor/src/components/block-mover/mover-description.js (hunk 3 above)
Comment (t-hamano) [reply packages/block-editor/src/components/block-mover/mover-description.js]: We might not be able to use `_n` because the number of  placeholders depends on whether you have multiple blocks selected.

However, we may be able to integrate the logic of `getBlockMoverDescription` and `getMultiBlockMoverDescription` by using a condition such as `isMultiSelected`:

```javascript
const isMultiSelected = selectedCount > 1;

if ( dir > 0 && ! isLast ) {
	// Moving down.
	const movementDirection = getMovementDirection( 'down', orientation );

	if ( movementDirection === 'down' ) {
		return isMultiSelected
			? sprintf(
					// translators: 1: Number of selected blocks, 2: Position of selected blocks
					__(
						'Move %1$d blocks from position %2$d down by one place'
					),
					selectedCount,
					position
				)
			: sprintf(
					// translators: 1: Type of block (i.e. Text, Image etc), 2: Position of selected block, 3: New position
					__(
						'Move %1$s block from position %2$d down to position %3$d'
					),
					type,
					position,
					position + 1
				);
	}
}
```

File: packages/block-editor/src/components/block-mover/mover-description.js [hunk 4]
```diff
@@ -231,43 +234,123 @@ export function getMultiBlockMoverDescription(
...
+
+		if ( movementDirection === 'left' ) {
+			return __(
+				'Blocks cannot be moved left as they are already are at the leftmost position'
+			);
+		}
+
+		if ( movementDirection === 'right' ) {
+			return __(
+				'Blocks cannot be moved right as they are already are at the leftmost position'
```
Comment (talldan) [inline packages/block-editor/src/components/block-mover/mover-description.js]: Small error here:
```suggestion
				'Blocks cannot be moved right as they are already are at the rightmost position'
```

File: packages/block-editor/src/components/block-mover/mover-description.js (hunk 2 above)
Comment (talldan) [reply packages/block-editor/src/components/block-mover/mover-description.js]: That's great, thanks!

File: packages/block-editor/src/components/block-mover/mover-description.js (hunk 3 above)
Comment (talldan) [reply packages/block-editor/src/components/block-mover/mover-description.js]: Ah, yes, thought so. I'm not sure the ternary improves readability that much, so lets' not worry about it for now.

**Comment by t-hamano** [comment]
It looks like there is no problem with what we have done so far, but I can't test it in RTL language.
Is there anyone who can test this in the RTL language?

**Review by talldan — APPROVED** [review]
Thanks for fixing this!

I tested in an RTL language and could reproduce the issue in `trunk` and also confirm that this solves the problem.

I tested quite a few different combinations (single block selections, multi-block selections and horizontal block selections) and couldn't see any further issues, so really nice work.
