### PR TITLE
Post Settings: Refactor revisions handling to avoid performance issues

### LINKED ISSUE #3167: Post edit script takes way much longer to generate for Gutenberg editor
## Issue Overview

I encountered this issue for the first time when opening the post that has **75 revisions**. It took almost **30 seconds** to generate HTML document with PHP when trying to edit the post using **Gutenberg**. It was working normally for the **Classic** editor - **1.42 s**. When I copied the content of this post to the newly created post with Gutenberg it got back to normal - about the same as with classic. As soon as I added over 20 revisions, processing time has increased to 6 seconds for Gutenberg.

## Steps to Reproduce (for bugs)

1. Create a new post with Gutenberg.
2. Paste the content of the post: https://pastebin.com/R8Zue5kQ.
3. Save draft.
4. Open with the Classic editor and check how long does it take to generate PHP document.
5. Repeat (4) for Gutenberg editor.
6. Add as many revisions as possible, 20 should be enough to notice the difference.
7. Repeat steps (4) and (5) and compare times.

## Expected Behavior

It always takes about the same to generate HTML document with PHP when selecting Classic or Gutenberg editor. The number of revisions shouldn't have any impact.

## Current Behavior

It takes way much longer to generate HTML document with PHP when selecting Gutenberg editor than the Classic editor. The number of revisions seems to have a big impact.

##### Gutenberg

gutenberg-editor

##### Classic

classic-editor

## Related Issues and/or PRs

#2822

### PR DESCRIPTION
**Pull request by gziolo**
## Description

Fixes #3167 - Post edit script takes way much longer to generate for Gutenberg editor. With the help of @pento we were able to identify the root cause:

> Performance improves significantly when I comment out this block:
> 
> https://github.com/WordPress/gutenberg/blob/master/lib/client-assets.php#L706-L708

This code preloads API response for revisions endpoint, which fetches all existing post revisions and exposes them in the `<script />` tag. When you have let's say 50 revisions, all of them are loaded from the database and exposed in the HTML code leading to the big size of the HTML and processing time to create all objects.

I refactored the handling of revisions to extend REST API endpoint for post types to include information about the number of revisions and the last revision id.

It solves a few issues I noticed:
- performance of the post edit page
- number of revisions updates whenever new revision gets created together with the link
- the link to the revision was pointing to the wrong revision

## How Has This Been Tested?

Manually:
- Create new post or page
- Make sure they are no errors
- Save draft
- Make sure that link to the revision shows up and you can navigate to this page
- Load existing post or page
- Make sure that link to the revisions shows up and you can navigate to this page
- Save another revision
- Make sure that link to the revisions updates properly

## Screenshots (jpeg or gifs if applicable):

screen shot 2017-10-30 at 11 47 09

## Types of changes
Bug fix (non-breaking change which fixes an issue). Code was refactored.

## Checklist:
- [x] My code is tested.
- [ ] My code follows the WordPress code style.
- [ ] My code follows has proper inline documentation.

### CODE REVIEW

File: lib/client-assets.php [hunk 1]
```diff
@@ -462,12 +462,12 @@ function gutenberg_extend_wp_api_backbone_client() {
 				return model.prototype.route && route === model.prototype.route.index;
 			} );
 		};
-		wp.api.getPostTypeRevisionsCollection = function( postType ) {
+		/*wp.api.getPostTypeRevisionsCollection = function( postType ) {
```
Comment (gziolo) [inline lib/client-assets.php]: We no longer need this handler, should we remove it?

File: lib/client-assets.php [hunk 2]
```diff
@@ -703,10 +703,6 @@ function gutenberg_editor_scripts_and_styles( $hook ) {
 		gutenberg_get_rest_link( $post_to_edit, 'about', 'edit' ),
 	);
 
-	if ( ! $is_new_post ) {
```
Comment (gziolo) [inline lib/client-assets.php]: Preloading all revisions and exposing them in the Script tag was the main root cause of performance issues reported in #3167. Kudos to @pento for finding out 👍

File: lib/register.php [hunk 3]
```diff
@@ -360,6 +360,32 @@ function gutenberg_register_rest_routes() {
...
+
+function gutenberg_register_post_revisions() {
+	register_rest_field( get_post_types( '', 'names' ),
+		'revisions',
+		array(
+			'get_callback'  => 'gutenberg_get_post_revisions',
+		)
+	);
+}
+add_action( 'rest_api_init', 'gutenberg_register_post_revisions' );
```
Comment (youknowriad) [inline lib/register.php]: Just wondering if it's a good idea to add extra fields to this endpoint. This won't be specific to Gutenberg.

File: lib/register.php [hunk 4]
```diff
@@ -360,6 +360,32 @@ function gutenberg_register_rest_routes() {
...
+
+	$last_revision = array_shift( $revisions );
+
+	return array(
+		'count' => $revisions_count,
+		'last_id' => $last_revision->ID
+	);
+}
+
+function gutenberg_register_post_revisions() {
```
Comment (gziolo) [inline lib/register.php]: Docs are missing. I will add later.

File: lib/register.php (hunk 3 above)
Comment (gziolo) [reply lib/register.php]: I'm learning WP hooks and APIs. I'm open to suggestions how to implement it better. This change makes loading Gutenberg with tons of revisions comparable to the Classic editor.

Comment (youknowriad) [reply lib/register.php]: I still think a separate endpoint is better, do you know why the previously used endpoint was slow? Maybe we should create a custom endpoint? Also, I'm not 100% confident when it comes to the REST API, others might have a better input.

Comment (pento) [reply lib/register.php]: @youknowriad: Loading all the revisions was running pretty much all of the code that would be run if the posts were being loaded to display on the front end. `the_content` was the biggest problem, but everything added up.

Comment (pento) [reply lib/register.php]: I'm okay with the field being here for now. I was unfortunately waylaid for the past week or so, so I haven't managed to focus on the REST API problem, but I'm hoping to get back to it later this week. I imagine there'll be a lot of re-shuffling, so I wouldn't get too hung up on where this is for now.

Comment (youknowriad) [reply lib/register.php]: Yes, I'm aware of that, I'm just saying we may want to load the "last_revision_id" and "revision_count" in a separate endpoint instead of adding these as extra fields to the default POST endpoint. Because this change will change the result for everything and not only Gutenberg.

File: lib/client-assets.php (hunk 1 above)
Comment (aduth) [reply lib/client-assets.php]: If it's dead code, I'm in favor of removing it.

File: lib/client-assets.php (hunk 2 above)
Comment (aduth) [reply lib/client-assets.php]: But why?

Comment (gziolo) [reply lib/client-assets.php]: See my description:

> This code preloads API response for revisions endpoint, which fetches all existing post revisions and exposes them in the <script /> tag. When you have let's say 50 revisions, all of them are loaded from the database and exposed in the HTML code leading to the big size of the HTML and increases processing time to process all objects.

And more technical comment from @pento:

> Loading all the revisions was running pretty much all of the code that would be run if the posts were being loaded to display on the front end. ‘the_content’ was the biggest problem, but everything added up.

Comment (aduth) [reply lib/client-assets.php]: Sorry, definitely overlooked this 👍

**Comment by aduth** [comment]
While it doesn't appear that it will prevent content filtering from being run, an alternative solution to limiting the size of the version history payload in the upcoming 4.9 release is to specify only the necessary fields on the API request:

e.g. `/wp/v2/posts/4462/revisions?_fields=id`

See: https://core.trac.wordpress.org/ticket/38131

**Comment by gziolo** [comment]
It seems like this solution makes sense as a temporary workaround. I will clean up this branch and add proper documentation to the `rest_api_init` hook.

> While it doesn't appear that it will prevent content filtering from being run, an alternative solution to limiting the size of the version history payload in the upcoming 4.9 release is to specify only the necessary fields on the API request:

Yes, that would be one of the possible ways of improving performance here. I think it would still need more work to make sure that REST API call is triggered every time new post's content is saved. At the moment information about revisions doesn't get updated whenever a post is saved. This PR addresses it, too.

**Review by youknowriad — APPROVED** [review]
Let's get this in (for the release) and make sure we revisit the endpoint later

**Comment by gziolo** [comment]
Thanks for all your feedback and reviews 🙇 

I'll open a follow-up issue. Let's discuss further steps there.
