### PR TITLE
Use clientWidth when no width is available for cropper

### LINKED ISSUE #27145: Image disappears when trying to crop
**Describe the bug**
While testing #27105 I found that when trying to crop an aligned image the image would disappear.

**To reproduce**
- in a new post
- add an image
- set its alignment to right
- select the image
- press crop in the toolbar
- notice the bug

**Expected behavior**
The image should not disappear.

**Screenshots**

align-crop

### PR DESCRIPTION
**Pull request by draganescu**
Fixes #27145

When the image has an align property the crop container's width becomes zero. When the image is having a set width the crop container inherits it, but when it has no width, the crop container is 100% of zero, because of the float, so it results in a zero width.

With this small change, we make the crop container always have at least the clientWidth value.

### CODE REVIEW

File: packages/block-library/src/image/image-editing/cropper.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ export default function ImageCropper( {
 				'is-applying': isInProgress,
 			} ) }
 			style={ {
-				width,
+				width: width || clientWidth,
```
Comment (stokesman) [inline packages/block-library/src/image/image-editing/cropper.js:51]: I notice this is the only place `width` is even referenced. Only `clientWidth` is used elsewhere (lines 39 and 42) which makes it look like only using it here would be fine too, ie:
```suggestion
				width: clientWidth,
```

**Review by stokesman — APPROVED** [review]
I've tested this. Works to resolve the issue where I've encountered it. I didn't test my suggestion and don't see that omitting it would cause issues. 

Aside: In part this review is for me to try out the github workflow. Thanks!

File: packages/block-library/src/image/image-editing/cropper.js (hunk 1 above)
Comment (draganescu) [reply packages/block-library/src/image/image-editing/cropper.js:51]: This should be set to `width` when that is available, which is by default available.

**Review by getdave — APPROVED** [review]
I tested this as per instructions to replicate in https://github.com/WordPress/gutenberg/issues/27145.

I found on `master` the bug was still in evidence (except the image didn't disappear it was just very very small).

On this branch however the image remains as the correct size based on it's alignment.

I tested on Twenty Twenty One.

👍 Nice fix.

Screen Capture on 2021-01-11 at 14-05-28
