### PR TITLE
Add an overlay to the html block preview to fix block selection in Firefox

### LINKED ISSUE #12577: Can't reliably select and edit HTML Blocks
**Describe the bug**
After adding code to an HTML Block, and then deselecting that block, it's incredibly difficult to reselect it again, and therefore hard to edit.

Vid: https://cl.ly/d411723691e7

This is another issue related to one that I raised almost a month ago, in regards to not being able to select blocks, and the Block toolbar not displaying. This issue is effecting numerous blocks in the editor and making them become uneditable.

**To Reproduce**
1. Add HTML Block
2. Add some example HTML to the block
3. Preview the Block and then click outside the block to deselect it
4. Try to reselect the block and edit your html

**Expected behavior**
I should be able to click on the Block to select it and edit it.

**Desktop (please complete the following information):**
 - macOS Sierra
 - Firefox Quantum 63.0.3
 - WP 5.0-RC3-43966

See Also: #11906

### PR DESCRIPTION
**Pull request by glendaviesnz**
In Firefox, if an html block is left in preview mode, it is very difficult to reselect the block except by clicking on the very bottom edge of the block - https://share.getcloudapp.com/9ZuArmrd. 

It appears that the click events are not bubbling up from the sandboxed iframe, and the selection works on the bottom edge due to some padding/margin which is outside the extents of the iframe.

Fixes #12577

## Description
This PR adds an overlay which covers the html preview area in order to prevent clicks being trapped in the sandboxed iframe

Before:
before

After:
after

## How has this been tested?
Tested manually in Firefox and Chrome.

## Types of changes
Adds additional HTML and CSS to html block

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.

### CODE REVIEW

File: packages/block-library/src/html/edit.js [hunk 1]
```diff
@@ -76,10 +76,13 @@ class HTMLEdit extends Component {
...
-							<SandBox
-								html={ attributes.content }
-								styles={ styles }
-							/>
+							<>
+								<SandBox
+									html={ attributes.content }
+									styles={ styles }
+								/>
+								<div className="wp-block-html__preview-overlay"></div>
```
Comment (youknowriad) [inline packages/block-library/src/html/edit.js]: Since this is an internal/editor div, it should follow our CSS class guidelines, it should be something like

`block-library-html__preview-overlay`

**Review by youknowriad — COMMENTED** [review]
Thanks for the fix, it makes sense to me but I was wondering if we ever want people to access the HTML (click on links, ...)

File: packages/block-library/src/html/edit.js (hunk 1 above)
Comment (glendaviesnz) [reply packages/block-library/src/html/edit.js]: fixed

**Comment by glendaviesnz** [comment]
> Thanks for the fix, it makes sense to me but I was wondering if we ever want people to access the HTML (click on links, ...)

Good question, hadn't thought about that, will have another look at it with that in mind.

**Comment by glendaviesnz** [comment]
@youknowriad I modified it so the overlay is only in place if the block is not selected, once selected it is removed so that any click actions within the html block will still work.

File: packages/block-library/src/html/edit.js [hunk 2]
```diff
@@ -76,10 +76,15 @@ class HTMLEdit extends Component {
...
-							<SandBox
-								html={ attributes.content }
-								styles={ styles }
-							/>
+							<>
+								<SandBox
+									html={ attributes.content }
+									styles={ styles }
+								/>
+								{ ! this.props.isSelected && (
```
Comment (youknowriad) [inline packages/block-library/src/html/edit.js]: Can we maybe add a comment explaining why the overlay is needed (browser issue)

**Review by youknowriad — APPROVED** [review]
