### PR TITLE
Guard block component against zombie state bug

### LINKED ISSUE #17013: Cannot insert Heading component into Cover
**Describe the bug**
when inserting a new Cover, changing the paragraph to heading using "/" break it
related: https://github.com/WordPress/gutenberg/issues/16959
possibly related: https://github.com/WordPress/gutenberg/issues/16851
**To reproduce**
1. create a new cover block
2. set a background
3. in the paragraph field, write / to insert a heading
4. it breaks

**Expected behavior**
Paragraph should turn into Heading block

**Screenshots**
ezgif com-optimize (1)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: Latest

**Additional context**
- Gutenberg on master

### PR DESCRIPTION
**Pull request by senadir**
fixes #17013
implements this fix by @nerrad 
https://github.com/WordPress/gutenberg/issues/17013#issuecomment-521237613
gif that shows a paragraph being transformed to a heading in the cover component

### CODE REVIEW

File: packages/block-editor/src/components/block-list/block.js [hunk 1]
```diff
@@ -775,5 +775,6 @@ export default compose(
 	withViewportMatch( { isLargeViewport: 'medium' } ),
 	applyWithSelect,
 	applyWithDispatch,
+	ifCondition( ( { block } ) => !! block ),
```
Comment (nerrad) [inline packages/block-editor/src/components/block-list/block.js]: I think we want a comment block here explaining why this was added.

**Review by nerrad — CHANGES_REQUESTED** [review]

File: packages/block-editor/src/components/block-list/block.js (hunk 1 above)
Comment (senadir) [reply packages/block-editor/src/components/block-list/block.js]: indeed, I referenced the issue and briefly explained why the block might not be defined

**Review by nerrad — APPROVED** [review]
👍

**Comment by youknowriad** [comment]
An e2e test for this one would be good.

**Comment by senadir** [comment]
should we build it against the Cover block or some other block that implements innerBlocks

**Comment by youknowriad** [comment]
It doesn't really matter @senadir we can just use the Cover block.
