### PR TITLE
Block Editor: Avoid block removal when calling 'moveBlockToPosition'

### LINKED ISSUE #75720: moveBlockToPosition can cause deletion of the last top-level block in Editor
### Description

If you call `moveBlockToPosition()` with the clientId of a nested block and the incorrect `fromRootClientId` of `''`, it will **delete** the last top-level block in the document instead of moving the target block.

We were a bit surprised when we hit this on a client site, when code that was intended to "pin" a block to the top after insertion repeatedly triggered and ended up deleting the entire post's content.

### Step-by-step reproduction instructions

In a blank block editor post, run the following snippet in console to create a hierarchy of groups with paragraph blocks inside them:

```js
const groups = [
    wp.blocks.createBlock( 'core/group', {}, [
        wp.blocks.createBlock( 'core/paragraph', { content: 'Par 1' } ),
    ] ),
    wp.blocks.createBlock( 'core/group', {}, [
        wp.blocks.createBlock( 'core/paragraph', { content: 'Par 2' } ),
    ] ),
    wp.blocks.createBlock( 'core/group', {}, [
        wp.blocks.createBlock( 'core/paragraph', { content: 'Par 3' } ),
    ] ),
];

wp.data.dispatch( 'core/block-editor' ).insertBlocks( groups );
```

Then, run this snippet to try to move the paragraph out from the last group and into the first position in the editor:

```js
wp.data.dispatch('core/block-editor').moveBlockToPosition(
    groups[2].innerBlocks[0].clientId,
    '', // fromRootClientId
    '', // toRootClientId -- want to move to top-level
    0 // targetPosition -- can be any index
);
```

**Expected**
- _either_ nothing would happen since the `fromRootClientId` is incorrect,
- _or_ the block moves to the start as intended
- and at minimum no unrelated blocks would be deleted either way

**Actual**
- The last group in the post is **_deleted_**
- If the dispatch is repeated two more times, the other groups are deleted, even though our target block (Par 3) isn't even in the editor's hierarchy anymore
- If you run this code snippet on a post which already has content, you can repeat the dispatch until the post is entirely empty

### Screenshots, screen recording, code snippet

Image

### Environment info

- WordPress 6.9.1, stock Gutenberg
- Tested in Chrome and Firefox on macOS 15.7.3, but observed on Windows as well
- Also replicated in the Playground

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes #75720.

PR updates `MOVE_BLOCKS_TO_POSITION` reducer to bail out early if it's moving blocks within the same root, but the `clientId` doesn't exist in that root.

## Why?
When `fromRootClientId === toRootClientId`, the reducer looks up the block's position with `indexOf`. If the block isn't actually in that parent, `indexOf` returns `-1`. The `splice(-1, 1)` interprets `-1` as "last element" and removes it.

## Testing Instructions
I've added unit tests; manual testing instructions are in #75720.

### Testing Instructions for Keyboard
Same.

### CODE REVIEW

**Review by kadamwhite — APPROVED** [review]
🙌 Thank you, @Mamaduka !

File: packages/block-editor/src/store/reducer.js [hunk 1]
```diff
@@ -1083,6 +1083,9 @@ export const blocks = pipe(
 				if ( fromRootClientId === toRootClientId ) {
 					const subState = state.get( toRootClientId );
 					const fromIndex = subState.indexOf( clientIds[ 0 ] );
+					if ( fromIndex === -1 ) {
```
Comment (ntsekouras) [inline packages/block-editor/src/store/reducer.js:1086]: Should we be selectively defensive against wrong API usage? I mean, it's fine to add this but there are so many more paths that things can break with wrong usage.

Comment (Mamaduka) [reply packages/block-editor/src/store/reducer.js:1086]: What do you have in mind? There are many ways similar actions can be misused; I think guarding against content loss is a good start.

IMO, the `fromRootClientId` argument isn't really required here; we can derive that value from `clientIds`, but now that would be hard to migrate without breaking something.

We could silently patch the wrong `fromRootClientId`, but consumers might still use the action incorrectly without even knowing it.

Comment (ntsekouras) [reply packages/block-editor/src/store/reducer.js:1086]: I told you I'm fine with this small change, but I find it weird to be defensive like that and I'll share my thinking.

If I was the one that tried to use that (or any other API) and noticed the issue. I'd see the docs/code and just call the API with the proper argument, that I had missed.. Or I'd suggest in an issue to have a `you're doing it wrong` message etc..

>We could silently patch the wrong fromRootClientId, but consumers might still use the action incorrectly without even knowing it.

That's still the case now.. They don't really know it's wrong, and even though they don't have content loss, they still don't know it's a no-op.

Anyway, that was a harmless change and shared my thoughts candidly. No reason to spent more time on this philosophical discussion I think 😄

Comment (Mamaduka) [reply packages/block-editor/src/store/reducer.js:1086]: Thanks for great feedback, Nik!
