### PR TITLE
Don't add Post Content layout styles to title in the post editor.

### LINKED ISSUE #48579: Post Title receiving Post Content layout styles in the post editor.
### Description

If the Post Content block in a post template has custom layout settings, they will also be applied to the title in the post editor. This seems to be a result of #46698 which adds the post content classes to the title area.

### Step-by-step reproduction instructions

1. Edit the Post Content block in the post template to e.g. justify content right, and give it a narrow content width;
2. Save and reload the post page;
3. Verify that the post title is now also aligned to the right and correspondingly narrow.

### Screenshots, screen recording, code snippet

Screenshot 2023-02-28 at 5 02 12 pm

### Environment info

Gutenberg latest trunk and also WP 6.2 Beta 3. Not reproducible on WP 6.1.1, so looks like a regression from the latest release.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

Fixes #48579.

If Post Content block has custom layout settings (e.g. if it's justified right and/or has a narrow content width) the post title in the post editor shouldn't get those styles, as they don't necessarily reflect the layout of the Post Title block in the template.

## Testing Instructions

1. Edit the post template and set a custom layout on the Post Content block; save and go back to the post editor.
2. Post title should't reflect the post content styles; they should be applied to the post content only.

## Screenshots or screencast 

Screenshot 2023-03-02 at 4 10 42 pm

### CODE REVIEW

File: packages/edit-post/src/components/visual-editor/index.js [hunk 1]
```diff
@@ -376,15 +376,11 @@ export default function VisualEditor( { styles } ) {
 						{ ! isTemplateMode && (
 							<div
 								className={ classnames(
-									// This wrapper div should have the same
-									// classes as the block list beneath.
-									'is-root-container',
-									'block-editor-block-list__layout',
```
Comment (andrewserong) [inline packages/edit-post/src/components/visual-editor/index.js:382]: Just double-checking, these two lines aren't required because we already have layout styles output that target `edit-post-visual-editor__post-title-wrapper` directly?

File: packages/edit-post/src/components/visual-editor/index.js [hunk 2]
```diff
@@ -376,15 +376,11 @@ export default function VisualEditor( { styles } ) {
...
 									'edit-post-visual-editor__post-title-wrapper',
 									{
 										'is-focus-mode': isFocusMode,
 									},
-									blockListLayoutClass
+									'is-layout-flow'
```
Comment (andrewserong) [inline packages/edit-post/src/components/visual-editor/index.js:383]: Since the layout rules affecting the post title block are already targeting `edit-post-visual-editor__post-title-wrapper`, we might not even need `'is-layout-flow'` added? It doesn't hurt to add it, though, and if it helps readability to make it explicit here, the inclusion sounds fine to me!

**Review by andrewserong — APPROVED** [review]
Nice work @tellthemachines, glad to see it was a simple fix to ensure that the post content block layout rules don't affect the post title block in the post editor 👍

This is testing well for me across a variety of blocks and classic themes.

One thing I noticed in testing that isn't related to this PR, is that while running `emptytheme` there's no spacing between the post title block and the first block of the post content.

image

I believe this is because we don't have layout running on the parent of both areas of the document (since the parent is `body` currently). I wonder if it'd be worth at some point seeing if we can add layout one level up, so that we can apply default spacing between the title and the post content area? (I see themes like TT3 deal with this by including margin rules for the post content block as part of the theme). Definitely not a blocker for this PR, though!

LGTM! ✨

File: packages/edit-post/src/components/visual-editor/index.js (hunk 1 above)
Comment (tellthemachines) [reply packages/edit-post/src/components/visual-editor/index.js:382]: The post content styles are targeted at those classes [here](https://github.com/WordPress/gutenberg/blob/fix/post-title/packages/edit-post/src/components/visual-editor/index.js#L257), so if we don't remove them they'll still apply to the title. It's also semantically incorrect to use them here, because the title wrapper isn't a block container.

File: packages/edit-post/src/components/visual-editor/index.js (hunk 2 above)
Comment (tellthemachines) [reply packages/edit-post/src/components/visual-editor/index.js:383]: Yeah, I thought it was best to have a fallback class to be on the safe side 😅

**Comment by tellthemachines** [comment]
Thanks for reviewing @andrewserong!

File: packages/edit-post/src/components/visual-editor/index.js (hunk 1 above)
Comment (andrewserong) [reply packages/edit-post/src/components/visual-editor/index.js:382]: Excellent, that all makes sense, thanks for confirming!

**Comment by ntsekouras** [comment]
I just cherry-picked this PR to the wp/6.2 branch to get it included in the next release: 83ddde76b4
