### PR TITLE
[Real-time Collaboration] Fix sync issue on refresh

### LINKED ISSUE #75976: RTC: [Engine] Refreshing can cause a user to no longer update the document
### Description

Refreshing an open post can cause a user to become invisibly disconnected from a collaborative session:

https://github.com/user-attachments/assets/4813f7ca-441f-4391-a3e5-52c321780559

### Step-by-step reproduction instructions

1. Enable real-time collaboration via WordPress Admin -> Settings -> Writing, and check the "Enable real-time collaboration" checkbox. Click the "Save Changes" button.
1. Open a post in tab A, then add a title and content and click "Save Draft".
2. In tab B, also open the post and add content. Both users should see the content synced.
3. Go back to tab A and refresh the page. 
4. After refreshing, add more content in tab A. New content in tab A is no longer synced to other peers.

Note that the network panel still shows consistent REST calls to the `/updates` endpoint in tab A after it is invisibly disconnected from syncing.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by maxschmeling**
## What?

Fixes #75976

Improves Yjs initialization to prevent issues when a collaborator refreshes their page

## Why?

When a collaborator refreshed, they could get into a state where their changes weren't being properly synced.

## How?
Instead of adding updates in `createYjsDoc`, delay those updates instead until `initializeYjsDoc` when observers have already been attached.

## Testing Instructions
1. Enable real-time collaboration via WordPress Admin -> Settings -> Writing, and check the "Enable real-time collaboration" checkbox. Click the "Save Changes" button.
2. Open a post in tab A, then add a title and content and click "Save Draft".
3. In tab B, also open the post and add content. Both users should see the content synced.
4. Go back to tab A and refresh the page.
5. After refreshing, add more content in tab A. Verify the new content in tab A is synced to other peers.

### CODE REVIEW

File: packages/sync/src/providers/http-polling/polling-manager.ts [hunk 1]
```diff
@@ -462,6 +462,12 @@ function registerRoom( {
 	}
 
 	// Note: Queue is initially paused. Call .resume() to unpause.
+	// Include the current doc state as an UPDATE alongside the SYNC_STEP_1 to
```
Comment (alecgeatches) [inline packages/sync/src/providers/http-polling/polling-manager.ts]: I think this comment can be removed now

**Review by alecgeatches — APPROVED** [review]

File: packages/sync/src/providers/http-polling/polling-manager.ts [hunk 2]
```diff
@@ -462,6 +462,12 @@ function registerRoom( {
...
+	// ensure any operations created before the onDocUpdate handler is attached
+	// (e.g. the VERSION_KEY set in createYjsDoc) are sent to peers. Without
+	// this, peers may receive subsequent operations that depend on these
+	// earlier operations but never receive the operations themselves, causing
+	// all updates to be stuck in Yjs's pendingStructs buffer.
```
Comment (chriszarate) [inline packages/sync/src/providers/http-polling/polling-manager.ts]:
```suggestion
```

**Review by chriszarate — APPROVED** [review]
