### PR TITLE
a11y: Add aria-label attributes and custom override control to core/social-link block

### LINKED ISSUE #18620: core/social-link component doesn't render accessible markup
**Describe the bug**
The anchor markup rendered by `core/social-link` isn't accessible. Anchors need [text to describe the links](https://dequeuniversity.com/rules/axe/3.1/link-name?application=lighthouse) to a screen reader.

[Render method](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/social-link/index.php#L25)

**To reproduce**
1. Go to Block Editor
2. Insert the **Social Links** block
3. Click **Preview** to see rendered block markup
4. Inspect Anchors or run Google Lighthouse, which will flag the issue as `Links do not have a discernible name`, multiplied by the number of inserted anchors.

**Expected behavior**
In the current implementation, anchor elements simply wrap SVGs of each social brand. The name of each site is already available and used to add a unique CSS class, so the fix should be to a fairly light lift to add a default, descriptive `aria-label="{BRAND} logo"` to the `<a>`.

However, we might also consider adding a custom override for the AIRA label in `core/social-link`. If a blog post was created identifying social profiles for **_10 Fast-Food Brands That Have Fire Social Accounts_**, it's possible there could be many instances of the Social Links block. Having a screen reader read "Twitter logo" 10+ times throughout the document isn't nearly as useful as... 

- "Twitter list for 10 Fast-Food Brands That Have Fire Social Accounts"
- "Twitter profile for Shake Shack", 
- "Twitter profile for Popeyes" 
- and "Twitter profile for AwesomeFastFoodReviews.com" [the current site].

### PR DESCRIPTION
**Pull request by 0aveRyan**
## Description
Fixes #18620.

Per #18620, I've modified the core/social-link block to contain an `aria-label` attribute for the anchor elements wrapping the social icon SVGs. 

Deque classifies missing descriptive text for links as a serious user impact and Google Lighthouse accessibility scores are negatively impacted without an `aria-label` if the anchor doesn't contain text or an image with an `alt` description.

By default, if the user doesn't customize the label in the provided TextControl in the Inspector, the block will render `Link to {BRAND}`. However, if the block is used 10 times in a document, hearing the same label 10 times isn't very useful if each social icon links to a different profile/type of page, hence the custom attribute to enable clearer descriptions.

At this point, there is a fair amount of duplication between the PHP and JS file containing data about the brands. These are unlikely to change greatly, but I'm happy to address with a different approach if desired.

## How has this been tested?
I've run the lint command, inserted each social icon and validated the display and markup for the Editor and Frontend render.

## Types of changes
* Introduces `label` attribute for the core/social-link block (only stores customizations, default is handled in render method)
* Introduces no breaking changes and progressively enhances any existing social blocks in-use.

# Screenshot
Screenshot of editor displaying new TextControl component for setting aria-label in core/social-block

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Review by mkaz — CHANGES_REQUESTED** [review]
This is a nice addition, thanks. 
I added a couple minor suggestions.

**Comment by mkaz** [comment]
Unrelated to your changes, I'm still not thrilled with the implementation. I agree there is too much duplication between PHP and JS. The core issue at hand is wrangling the SVG, I have one unsuccessful attempt here to solve: https://github.com/WordPress/gutenberg/pull/18243 

Additionally, I think we can simplify the list if we can solve the above, and then implement the ability to extend or modify, related issue https://github.com/WordPress/gutenberg/issues/17277

**Comment by 0aveRyan** [comment]
@mkaz Thanks for the review! I'll push a commit to address the description & LinkedIn.

I'm also a fan of svgr, but from the chatter on #18243 sounds like that may require some creative solutions for the Gutenberg codebase.

I agree the implementation is fairly easy to understand, but perhaps leaves something to be desired from a developer experience and maintenance standpoint. Unfortunately, most other approaches I can think of would either transfer that burden to visitors or obfuscate to developers what's happening.

**On my brain apart from svgr...**
- Leave implementation as-is, add filter hooks in JS & PHP for extension and enhance with clearer inline documentation that any changes must happen to both objects -- _still duplicated but extensible and clearer_.
- Add a `socialData.json` file with icons base64 encoded and filter hooks in JS & PHP to allow extension -- _adds filesystem read in PHP and base64 strings would be about 1/3 larger_.
- Use a `socialData.json` file to inject the objects into JS & PHP during webpack build, base64 decode icons and add filter hooks -- _obfuscates what's happening and some complexity, but reduces client burden_.
- Separate icons into a SVG sprite approach or one-off SVG files, use a `socialData.json` to point to the proper icon and add filter hooks -- _makes a larger payload to transmit to client/increases client requests, but makes using a data file easier._

**Comment by mkaz** [comment]
One more, Github --> GitHub, see https://github.com/WordPress/gutenberg/pull/18714

With regards to SVG, thanks for the suggestions, I'll need to noodle on them a bit more, I like how you draw out the pros and cons to the various solutions. We discuss further in a separate PR, I have on my list to move them out of PHP into single SVG files this would improve one aspect, but need to consider how it might change after this PR, it may not make it easier overall

**Comment by 0aveRyan** [comment]
@mkaz I've addressed the branding issues and helper text. Should we start a new issue to discuss and address the social SVG storage and label data?

**Review by mkaz — APPROVED** [review]
Updates looks good, thanks! :+1:

Yes, I think a new issue to discuss the alternate storage would be best.

File: packages/block-library/src/social-link/edit.js [hunk 1]
```diff
@@ -30,35 +33,50 @@ const SocialLinkEdit = ( { attributes, setAttributes, isSelected } ) => {
...
-							/>
-						</div>
-						<IconButton icon="editor-break" label={ __( 'Apply' ) } type="submit" />
-					</form>
-				</URLPopover>
-			) }
-		</Button>
+		<Fragment>
+			<InspectorControls>
+				<PanelBody title={ `${ SocialLinkName }` + __( ' Label' ) } initialOpen={ false }>
```
Comment (youknowriad) [inline packages/block-library/src/social-link/edit.js]: isn't this better with `sprintf( __( '%s Label' ), SocialLinkName )`  ?

File: packages/block-library/src/social-link/edit.js [hunk 2]
```diff
@@ -30,35 +33,50 @@ const SocialLinkEdit = ( { attributes, setAttributes, isSelected } ) => {
 
 	// Import icon.
 	const IconComponent = getIconBySite( site );
+	const SocialLinkName = getNameBySite( site );
```
Comment (youknowriad) [inline packages/block-library/src/social-link/edit.js]: Why is this variable uppercased? It doesn't look like a component to me.

File: packages/block-library/src/social-link/index.php [hunk 3]
```diff
@@ -100,128 +104,223 @@ function register_block_core_social_link() {
...
+			'name' => 'RSS Feed',
+			'icon' => '<svg width="24" height="24" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg"><path d="M2,8.667V12c5.515,0,10,4.485,10,10h3.333C15.333,14.637,9.363,8.667,2,8.667z M2,2v3.333 c9.19,0,16.667,7.477,16.667,16.667H22C22,10.955,13.045,2,2,2z M4.5,17C3.118,17,2,18.12,2,19.5S3.118,22,4.5,22S7,20.88,7,19.5 S5.882,17,4.5,17z"></path></svg>',
+		),
+		'flickr'        => array(
+			'name' => 'Flickr',
+			'icon' => '<svg width="24" height="24" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg"><path d="M6.5,7c-2.75,0-5,2.25-5,5s2.25,5,5,5s5-2.25,5-5S9.25,7,6.5,7z M17.5,7c-2.75,0-5,2.25-5,5s2.25,5,5,5s5-2.25,5-5 S20.25,7,17.5,7z"></path></svg>',
+		),
+		'foursquare'    => array(
+			'name' => 'Foursquare',
+			'icon' =>
```
Comment (youknowriad) [inline packages/block-library/src/social-link/index.php]: Looks like there's some unresolved conflicts

File: packages/block-library/src/social-link/social-list.js [hunk 4]
```diff
@@ -207,3 +207,7 @@ export default socialList;
 export const getIconBySite = ( site ) => {
 	return socialList[ site ].icon;
 };
+
+export const getNameBySite = ( site ) => {
+	return socialList[ site ].name;
+};
```
Comment (youknowriad) [inline packages/block-library/src/social-link/social-list.js]: These functions could use some JSDocs

**Comment by 0aveRyan** [comment]
@youknowriad I've addressed your feedback, this should be good to go.

File: packages/block-library/src/social-link/edit.js [hunk 5]
```diff
@@ -6,18 +6,23 @@ import classNames from 'classnames';
 /**
```
Comment (youknowriad) [inline packages/block-library/src/social-link/edit.js]: I see a few strings here where we use Title Case. I think we've been recently moving to always using "Sentence case" in all of our strings. @karmatosed do you confirm?

Comment (0aveRyan) [reply packages/block-library/src/social-link/edit.js]: Screen Shot 2019-12-26 at 10 03 00 AM

@youknowriad that doesn't appear to be the standard used for Panel Titles and that doesn't seem to be the standard [outlined in the docs](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/copy-guide.md#five-pay-attention-to-capitalization). Was there a discussion about that I missed? If that's changed, the docs need to be updated and issues opened to address the many instances of title case throughout the application.

Comment (0aveRyan) [reply packages/block-library/src/social-link/edit.js]: I've since dug and found the PRs and issue discussion around sentence case. A major departure like that should be memorialized in docs well before it's put into practice, to avoid confusing situations like this.

Comment (youknowriad) [reply packages/block-library/src/social-link/edit.js]: I don't know to be honest, I'll let @karmatosed chime in when she comes back. I think we can land this as is for now.

File: packages/block-library/src/social-link/edit.js [hunk 6]
```diff
@@ -27,34 +32,51 @@ const SocialLinkEdit = ( { attributes, setAttributes, isSelected } ) => {
...
+					<URLPopover
+						onClose={ () => setPopover( false ) }
+					>
+						<form
+							className="block-editor-url-popover__link-editor"
+							onSubmit={ ( event ) => {
+								event.preventDefault();
+								setPopover( false );
+							} } >
+							<div className="editor-url-input block-editor-url-input">
```
Comment (aduth) [inline packages/block-library/src/social-link/edit.js]: This is not a valid class name for this component:

https://github.com/WordPress/gutenberg/blob/master/docs/contributors/coding-guidelines.md#naming

It violates the guideline to not inherit styles from other compoennts:

>A component's class name should never be used outside its own folder (with rare exceptions such as _z-index.scss). If you need to inherit styles of another component in your own components, you should render an instance of that other component. At worst, you should duplicate the styles within your own component's stylesheet. This is intended to improve maintainability by isolating shared components as a reusable interface, reducing the surface area of similar UI elements by adapting a limited set of common components to support a varied set of use-cases.

It also introduces additional legacy compatibility class names intended to have been removed as part of #19050 (though I also note that this is problematic in the `format-library` from which this code was presumably copied).

Comment (0aveRyan) [reply packages/block-library/src/social-link/edit.js]: @aduth This was moved in this PR, but originated in #16897 four months ago. I can see you've opened a PR addressing this so I'm going to close this as resolved.

File: packages/block-library/src/social-link/index.php [hunk 7]
```diff
@@ -13,16 +13,17 @@
  * @return string Rendered HTML of the referenced block.
  */
 function render_core_social_link( $attributes ) {
-	$site = ( isset( $attributes['site'] ) ) ? $attributes['site'] : 'Icon';
-	$url  = ( isset( $attributes['url'] ) ) ? $attributes['url'] : false;
+	$site  = ( isset( $attributes['site'] ) ) ? $attributes['site'] : 'Icon';
+	$url   = ( isset( $attributes['url'] ) ) ? $attributes['url'] : false;
+	$label = ( isset( $attributes['label'] ) ) ? $attributes['label'] : __( 'Link to ' ) . core_social_link_get_name( $site );
```
Comment (aduth) [inline packages/block-library/src/social-link/index.php]: I believe that this should be using a placeholder:

https://codex.wordpress.org/I18n_for_WordPress_Developers#Placeholders

Otherwise, translators will only be provided the string "Link to " without contextual clues to know that it is being used in a concatenation. Furthermore, some translations may require that the position of the placeholder be changed relative to the rest of the sentence. 

Even with a placeholder, this sort of string can still be problematic where the translation may vary depending on e.g. the gender of the noun of the placeholder value. In this case, I don't believe that should be a problem, given that the values to be substituted are proper names of companies / services.

That said, it would be good to:

- Confirm whether this is a correct assumption.
- Update to use a placeholder.
- Consider including a [translator comment](https://codex.wordpress.org/I18n_for_WordPress_Developers#Descriptions) to explain this.

Comment (aduth) [reply packages/block-library/src/social-link/index.php]: Issue for tracking purposes: #20152

**Comment by afercia** [comment]
The aria-label doesn't seem to work for me: whatever I enter in the field, the aria-label rendered on the front end has always the default value "Link to {something}".

@youknowriad @aduth do you see any potential regression since this was merged?

**Comment by aduth** [comment]
@afercia I'm not personally familiar enough with these changes to know if it had ever been working as expected, but I can also reproduce the issue you're seeing.

**Comment by aduth** [comment]
On further investigation, it appears to have regressed as a result of #19887, where the `label` attribute `type` was [incorrectly assigned as `'number'`](https://github.com/WordPress/gutenberg/pull/19887/files#diff-3b8f7987eeab3be14d42acf339a3cb30R11-R13), which would invalidate the custom string value. This [was correctly assigned as `'string'` previously](https://github.com/0aveRyan/gutenberg/blob/cf861db5ae47b98ad6f83c1c2e2133933c6e2cf3/packages/block-library/src/social-link/index.php#L87-L89).

https://github.com/WordPress/gutenberg/blob/fcbc6cac8821ad9ea2160d7c23d17d2f6ff00320/packages/block-library/src/social-link/block.json#L12-L14

cc @mcsf

**Comment by aduth** [comment]
Fix at #20468

**Comment by afercia** [comment]
@aduth thanks so much for the quick investigation and fix!
