### PR TITLE
Site editor: fix image upload bug

### LINKED ISSUE #57037: Image uploads broken in site editor
### Description

In  17.1+ and trunk image uploads are broken via blocks in the site editor. The work as expected in post editor, and via the media library in the site editor, but using the `Upload` button in Image block etc. causes a `Invalid paramater: post` error.

It looks like this bug was introduced by https://github.com/WordPress/gutenberg/pull/55970 - commits prior to this work as expected.

### Step-by-step reproduction instructions

- Go to site editor and edit a page or template
- Add an Image block and try using the `Upload` option

### Screenshots, screen recording, code snippet

Screenshot 2023-12-14 at 3 11 35 PM

### Environment info

17.1+

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by glendaviesnz**
## What?
Fixes a bug with images not uploading in the site editor.
Fixes: https://github.com/WordPress/gutenberg/issues/57037

## Why?
In https://github.com/WordPress/gutenberg/pull/55970 the settings were shared between site editor and post editor, but the site editor image upload did not previously include a post id as the post id in site editor is a template string slug. This string slug is now being passed as a post id to the image upload endpoint which causes a bad request error.

## How?
Checks for a numeric post id before appending to upload media data.

## Testing Instructions

- Go to site editor and add edit a template and add an image block
- Selection the `Upload` option and make sure it succeeds
- Do the same in the post editor and make sure that the call to the media endpoint still includes a post id

## Screenshots or screencast 

Before:

https://github.com/WordPress/gutenberg/assets/3629020/ced80914-11e6-44ee-aab4-ab32236c1872

After:

https://github.com/WordPress/gutenberg/assets/3629020/e51c70c1-cd58-4410-ba5c-621cf0827f00

### CODE REVIEW

**Comment by glendaviesnz** [comment]
I did initially try to find a way to inject a different mediaUpload method into the site editor settings as [used to happen](https://github.com/WordPress/gutenberg/pull/55970/files#diff-94ccd649d2e3a0efc85ceb76fc0ebf13e6b721cedec21edc917064fe4cb2c79bL140), but I think this simple fix achieves the same thing.

**Comment by glendaviesnz** [comment]
I think we should add an additional e2e test for image load in site editor. This can be done in a separate PR though.

File: packages/editor/src/utils/media-upload/index.js [hunk 1]
```diff
@@ -35,13 +35,13 @@ export default function mediaUpload( {
...
 		maxUploadFileSize || getEditorSettings().maxUploadFileSize;
-
+	const currentPostId = getCurrentPostId();
 	uploadMedia( {
 		allowedTypes,
 		filesList,
 		onFileChange,
 		additionalData: {
-			post: getCurrentPostId(),
+			...( ! isNaN( currentPostId ) ? { post: currentPostId } : {} ),
```
Comment (talldan) [inline packages/editor/src/utils/media-upload/index.js:44]: Nitpick, but I'd find it more readable if it were something along the lines of:
```js
const postData = isNaN( currentPostId ) ? {} : { post: currentPostId };
// ...
additionalData: {
    ...postData,
    ...additionalData
};
```

File: packages/editor/src/utils/media-upload/index.js [hunk 2]
```diff
@@ -35,13 +35,13 @@ export default function mediaUpload( {
 	const wpAllowedMimeTypes = getEditorSettings().allowedMimeTypes;
 	maxUploadFileSize =
 		maxUploadFileSize || getEditorSettings().maxUploadFileSize;
-
+	const currentPostId = getCurrentPostId();
```
Comment (talldan) [inline packages/editor/src/utils/media-upload/index.js:38]: I wonder what the post id is used for? Attachments?

It seems like the way this function works might lead to some issues. In the site editor an image could be uploaded in the context of a post if you were editing post content, but I'm not sure `getCurrentPostId` is guaranteed to return the right thing ... maybe there are some contexts where it returns the template id instead of the content post id (as per this bug).

I wonder if the post id should really be passed into `mediaUpload` in the majority of cases, and maybe determined using `useEntityProp` within the block.

**Review by aaronrobertshaw — APPROVED** [review]
LGTM 👍 

✅ Could replicate image upload issue in the site editor
✅ Applying the changes in this PR fix the issue
✅ Post editor image uploads still work

As [noted](https://github.com/WordPress/gutenberg/pull/57040#issuecomment-1855113803), we need an e2e to cover image uploading in the site editor. No objections here though for that to be done in a follow-up.

**Review by talldan — APPROVED** [review]
I think this is good as an interim fix, but there might need to be some thought about whether the way `mediaUpload` works is right in the context of the site editor.

Seems like we might not be able to rely on `getCurrentPostId`.

Would appreciate thoughts from @youknowriad, as it seems related to some changes he's been making.

File: packages/editor/src/utils/media-upload/index.js (hunk 2 above)
Comment (glendaviesnz) [reply packages/editor/src/utils/media-upload/index.js:38]: When I edited a page in the context of the site editor with this patch the post id was set correctly in this method. But previously with the site editor specific method no post id was being set for the media upload even when editing in the context of the post/page, so it seems like moving to this shared method might have resolved an existing potential issue as well as causing the bug. As you note though, there may be some contexts in the site editor where it isn't returned correctly so could be worth some further investigation.

I don't know what the impact might be of all the images previously uploaded in pages in the site editor not having the post id set might be - so it could be worth looking further into why it is set. I will look at that tomorrow if @youknowriad doesn't know.

Comment (youknowriad) [reply packages/editor/src/utils/media-upload/index.js:38]: > maybe there are some contexts where it returns the template id instead of the content post id (as per this bug).

No, it always returns the postId no matter the context.

Comment (youknowriad) [reply packages/editor/src/utils/media-upload/index.js:38]: That said, when you open a template directly in the site editor, it contains the template id, when you open the navigation block, it contains its id, when you open a pattern or template part, same...

Comment (talldan) [reply packages/editor/src/utils/media-upload/index.js:38]: I guess I was thinking of whether it's possible to open a template (where it's set to the template slug) and the edit an image inside the `Content` block of a nested post, but that doesn't seem possible in my testing.

File: packages/editor/src/utils/media-upload/index.js (hunk 1 above)
Comment (ramonjd) [reply packages/editor/src/utils/media-upload/index.js:44]: In the case of templates, the `isNan` test will return `false`. Is that a problem?

`! isNaN('twentytwentyfour//home') === false // true`

File: packages/editor/src/utils/media-upload/index.js (hunk 2 above)
Comment (ramonjd) [reply packages/editor/src/utils/media-upload/index.js:38]: >  so it could be worth looking further into why it is se

Original PR here:

- https://github.com/WordPress/gutenberg/pull/6231

Since that PR, `editorMediaUpload` has been renamed to `mediaUpload` and refactored a bit.

Here's the reason it seems:

> Once the image was uploaded, it was correctly assigned to its parent post

Comment (ramonjd) [reply packages/editor/src/utils/media-upload/index.js:38]: Having said that, I'm not entirely sure sending the post id is required at all 🤷🏻 

But it's been there so long it's expected, at least by Jetpack. See: https://github.com/Automattic/wp-calypso/issues/85373#issuecomment-1869907797

Here's a PR that forces the numerical ID: 

- https://github.com/WordPress/gutenberg/pull/57388

Comment (ramonjd) [reply packages/editor/src/utils/media-upload/index.js:38]: Yes, here we go. Right in front my eyes. The `post` arg is an integer according to the `WP_REST_Attachments_Controller`

https://github.com/WordPress/wordpress-develop/blob/d1faee936de9f08b0e496c86f7cd24dfda6739f6/src/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php#L946-L946
