### PR TITLE
Fix: Pagination arrows are pointing in the wrong direction in RTL languages

### LINKED ISSUE #64929: Pagination arrows are pointing in the wrong direction in RTL languages
### Description

For example, the DataViews pagination is displayed as follows in LTR language:

image

On the other hand, in RTL languages ​​it looks like this:

image

This should be displayed as:

image

You can also see that the text "PAGE 1 OF N" is not displayed correctly in RTL languages, but I'm not sure if this is an implementation issue or if it's not yet translated.

At the very least, the direction of the arrow should be fixed.

As far as I can tell, we need to fix the pagination below:

- DataViews
- Revision
- Font Library Modal

### Step-by-step reproduction instructions

- Enable RTL languages.
- Access any of the pagination methods mentioned above.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #64929

## What?

This PR fixes the incorrect chevron icon direction in RTL languages.

## Why?

In RTL languages, the horizontal document flow is reversed, so the chevron icon must also be displayed in reverse.

## How?

- Search the whole project for the keyword `chevronLeft` and `chevronRight`. This keyword will find the following icons: `chevronLeft`, `chevronLeftSmall`, `chevronRight`, `chevrontRightSmall`.
- In an RTL language, evaluate whether the direction of the icon is appropriate. If not, use the `isRTL()` function to reverse the direction.

## Testing Instructions

- Enable RTL languages.
- Verify that the chevron icon direction is correct in the following locations.

### Grid Block Mover

- First, enable the Grid interactivity experiment setting.
- Insert a block using the HTML below.

<details><summary>Details</summary>

```html
<!-- wp:group {"layout":{"type":"grid","columnCount":3,"rowCount":3,"isManualPlacement":true,"minimumColumnWidth":null}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"layout":{"columnStart":1,"rowStart":1}},"backgroundColor":"accent-4"} -->
<p class="has-accent-4-background-color has-background">Paragraph 1</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"layout":{"columnStart":2,"rowStart":1}},"backgroundColor":"accent-4"} -->
<p class="has-accent-4-background-color has-background">Paragraph 2</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"layout":{"columnStart":3,"rowStart":1}},"backgroundColor":"accent-4"} -->
<p class="has-accent-4-background-color has-background">Paragraph 3</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"layout":{"columnStart":1,"rowStart":2}},"backgroundColor":"accent-4"} -->
<p class="has-accent-4-background-color has-background">Paragraph 4</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"layout":{"columnStart":2,"rowStart":2}},"backgroundColor":"accent-4"} -->
<p class="has-accent-4-background-color has-background">Paragraph 5</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"layout":{"columnStart":3,"rowStart":2}},"backgroundColor":"accent-4"} -->
<p class="has-accent-4-background-color has-background">Paragraph 6</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"layout":{"columnStart":1,"rowStart":3}},"backgroundColor":"accent-4"} -->
<p class="has-accent-4-background-color has-background">Paragraph 7</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"layout":{"columnStart":1,"rowStart":3}},"backgroundColor":"accent-4"} -->
<p class="has-accent-4-background-color has-background">Paragraph 7</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"layout":{"columnStart":2,"rowStart":3,"columnSpan":1}},"backgroundColor":"accent-4"} -->
<p class="has-accent-4-background-color has-background">Paragraph 8</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"layout":{"columnStart":3,"rowStart":3,"columnSpan":1}},"backgroundColor":"accent-4"} -->
<p class="has-accent-4-background-color has-background">Paragraph 9</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```

</details> 

| Before | After |
|--------|--------|
| image| image| 

### Navigation Block

- Access the Site Editor > select any template
- Select a Navigation block
- Click the quick inserter
- Click the Add Block button
- Check the back button icon direction

| Before | After |
|--------|--------|
| image| image| 

### DataViews Pagination

- Check the direction of the previous button and next button icons

Note: You can also see that the text "PAGE 1 OF N" is not displayed correctly in RTL languages, but I'm not sure if this is an implementation issue or if it's not yet translated.

| Before | After |
|--------|--------|
| image| image| 

### Font Library Modal

- Access the Site Editor > Select any template
- Access the global styles > typography > Manage Fonts button
- Install Fonts Tab:
  - Check the direction of the icon displayed to the left of the font item
  - Click on any font
  - Check the back button icon direction
- Library Tab:
  - Check the direction of the icon displayed to the left of the font item
  - Click on any font
  - Check the back button icon direction

| Before | After |
|--------|--------|
| image| image|
| image| image| 
| image| image |
| image| image| 

### Edit Site Pagination Component (Revisions Pagination)

- Access the Site Editor > Select any template
- Continue modifying and saving the template to create sufficient revisions
- Access the global styles > revisions
- Check the direction of the Last page, Next page, Previous page, and First page button icons
 
Note: You can also see that the text "1 OF N" is not displayed correctly in RTL languages, but I'm not sure if this is an implementation issue or if it's not yet translated.

| Before | After |
|--------|--------|
| image| image |

### CODE REVIEW

File: packages/block-editor/src/components/block-pattern-setup/setup-toolbar.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 /**
  * WordPress dependencies
  */
-import { __ } from '@wordpress/i18n';
+import { __, isRTL } from '@wordpress/i18n';
```
Comment (t-hamano) [inline packages/block-editor/src/components/block-pattern-setup/setup-toolbar.js:4]: The `SetupToolbar` component is imported by [the `BlockPatternSetup` component](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-pattern-setup/index.js). However, the `BlockPatternSetup` component itself does not seem to be used anywhere.

**Review by cbravobernal — APPROVED** [review]
LGTM,is  kind of mindblowing following all arrows 😅

**Comment by t-hamano** [comment]
@cbravobernal Thanks for the review!
