### PR TITLE
Fix a Text Selection Exception in Safari

### LINKED ISSUE #8254: Non-text inputs can trigger exception inside isTextField in Safari
**Describe the bug**
When a block exists with a non-text `<input>` (e.g. `<input type="submit">` it can cause an issue inside [`isTextField`](https://github.com/WordPress/gutenberg/blob/caaf20474e7e45a6e6669f3fafb3d57edf61662e/packages/dom/src/dom.js#L381-L399).

This seems to be specific to Safari, which throws an exception when trying to get `selectionStart` from a non-text `<input`>. Other browsers return `undefined` (such as Chrome) but Safari throws a `TypeError` exception for whatever reason.

```
isTextField@http://redacted/content/plugins/gutenberg/build/dom/index.js?ver=1532620128:2539:31
filter@[native code]
focusTabbable@http://redacted/content/plugins/gutenberg/build/editor/index.js?ver=1532620128:2230:109
componentDidMount@http://redacted/content/plugins/gutenberg/build/editor/index.js?ver=1532620128:2178:27
commitLifeCycles@http://redacted/content/plugins/gutenberg/vendor/react-dom.24169eaf.js:14939:39
commitAllLifeCycles@http://redacted/content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16040:23
callCallback@http://redacted/content/plugins/gutenberg/vendor/react-dom.24169eaf.js:140:19
dispatchEvent@[native code]
invokeGuardedCallbackDev@http://redacted/content/plugins/gutenberg/vendor/react-dom.24169eaf.js:178:29
invokeGuardedCallback@http://redacted/content/plugins/gutenberg/vendor/react-dom.24169eaf.js:227:34
commitRoot@http://redacted/content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16181:30
completeRoot@http://redacted/content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17196:44
performWorkOnRoot@http://redacted/content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17141:21
performWork@http://redacted/content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17060:24
performSyncWork@http://redacted/content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17032:14
interactiveUpdates$1@http://redacted/content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17297:22
dispatchInteractiveEvent@http://redacted/content/plugins/gutenberg/vendor/react-dom.24169eaf.js:4882:21
dispatchInteractiveEvent@[native code]
```

**To Reproduce**
1. Register a block type with an `<input type="submit">` inside the Edit representation
2. Insert the block
3. Get the above error

**Expected behavior**
No error should be displayed.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari 11.1.1
 - Gutenberg Version: `master`

### PR DESCRIPTION
**Pull request by chrisvanpatten**
## Description
Wraps the `isTextField` logic inside a try/catch block to handle an exception when trying to get `selectionStart` on a non-text input in Safari.

Also adds an inline comment to explain the reasoning for the try/catch block, for future devs.

Fixes #8254.

(Text Selection Exception is also my new band name.)

## How has this been tested?
Manually in Safari

## Types of changes
Bug fix

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: packages/dom/src/dom.js [hunk 1]
```diff
@@ -389,13 +389,21 @@ export function placeCaretAtVerticalEdge( container, isReverse, rect, mayUseScro
...
-	);
+	try {
+		const { nodeName, selectionStart, contentEditable } = element;
+
+		return (
+			( nodeName === 'INPUT' && selectionStart !== null ) ||
+			( nodeName === 'TEXTAREA' ) ||
+			contentEditable === 'true'
+		);
+	} catch ( error ) {
```
Comment (jorgefilipecosta) [inline packages/dom/src/dom.js]: Hi @chrisvanpatten thank you for catching and addressing this issue.
It seems the isTextField can be called on safari many times and on safari calling it on non-text inputs and having to catch this exception may be expected/part of the normal flow. Ideally, exceptions should not be used for expected flows.
Do you think checking for a list of input types (text, email etc...) when the node name is equal to input can be a valid solution?

Comment (chrisvanpatten) [reply packages/dom/src/dom.js]: @jorgefilipecosta I had thought about that but was concerned the list of valid input types could change from browser-to-browser and be harder to maintain. That said, I'm totally fine with that too.

Might need help with structuring the function… here's what I'd do if it were just for personal code. Does this look okay?

```
if ( element.nodeName === 'TEXTAREA' || element.contentEditable === true ) {
	return true;
}

// List of valid input types for selectionStart via WHATWG spec.
// https://html.spec.whatwg.org/multipage/input.html#concept-input-apply
const validInputTypes = [
	'password',
	'search',
	'tel',
	'text',
	'url',
];

if ( element.nodeName === 'INPUT' && ! includes( validInputTypes, element.type ) ) {
	return false;
}

if ( element.selectionStart !== null ) {
	return true;
}

return false;
```

Comment (jorgefilipecosta) [reply packages/dom/src/dom.js]: Sorry @chrisvanpatten I missed your ping.  In my option, the logic you propose seems nice and is preferable over using a try catch. Maybe we can make validInputTypes a constant VALID_INPUT_TYPES_SELECTION_START or something similar.

Comment (aduth) [reply packages/dom/src/dom.js]: I'm fine with either the revised approach or the original proposal. The `try` / `catch` is agreeable only because it seems in this case Safari is not following the standard by throwing, where the standard dictates:

>If this element is an `input` element, and `selectionStart` [does not apply](https://html.spec.whatwg.org/multipage/input.html#do-not-apply) to this element, return `null`.

https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#dom-textarea/input-selectionstart

...in which case we're capturing an unpredictable (non-standard) behavior.

The revised approach recreates the intent of the standard above, though in which case I'd find the condition of `if ( element.selectionStart !== null ) {` to be redundant and unnecessary.

**Review by aduth — APPROVED** [review]

**Comment by chrisvanpatten** [comment]
Okay, I've rebased this, expanded my code comment, and pending Travis success I think we're ready for merge. @aduth do you want to re-review?
