### PR TITLE
Image: Fix design of close button for the lightbox (correct PR)

### LINKED ISSUE #51125: Image: Vertical image from URL cut when displayed in the lightbox
### Description

When using the lightbox behavior for the Image block that contains a vertical image inserted from URL, it displays correctly on the front end. However, when the lightbox gets opened, if the image is tall, then it gets cut on both the top and bottom of the image.

### Step-by-step reproduction instructions

1. Activate the experiment that enables Interactivity API and Behaviors.
2. Go to the post editor.
3. Insert an image with a much bigger height than width using `Insert from URL` option, for example: 
https://pd.w.org/2023/05/7866470b6f485ce37.96403804.jpg.
4. In the advanced settings for the Image block, activate the lightbox behavior.
5. Publish the post.
6. Navigate to the post on the front end.
7. Open the lightbox and check whether the image is correctly displayed.

### Screenshots, screen recording, code snippet

Vertical image in the block editor:

Screenshot 2023-05-30 at 14 50 27

Vertical image in the lightbox on the frontend:
Screenshot 2023-05-30 at 14 50 40

### Environment info

- WordPress 6.2, Gutenberg latest (`trunk`)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #51126: Image: Close button in the lightbox hard to see with dark images
### Description

When using the lightbox behavior for the Image block that contains a dark image, it displays the `Close` button in a way that is hard to see it.

### Step-by-step reproduction instructions

1. Activate the experiment that enables Interactivity API and Behaviors.
2. Go to the post editor.
3. Upload an image with a dark area around borders, for example: 
Screenshot-2023-05-30-at-10 06 09

4. Set the `Resolution` to `Full Size`. Alternatively, it might work with different settings depending on the screen-size used.
5. In the advanced settings for the Image block, activate the lightbox behavior.
6. Publish the post.
7. Navigate to the post on the front end.
8. Open the lightbox and check whether the `Close` button is correctly displayed.

### Screenshots, screen recording, code snippet

**Editor view:**

Screenshot 2023-05-31 at 12 40 12

---

**Frontend view:**

Screenshot 2023-05-31 at 12 39 59

Screenshot 2023-05-30 at 14 50 27

---

**Lightbox view:**

Screenshot 2023-05-31 at 12 39 39

Screenshot 2023-05-30 at 14 50 40

### Environment info

- WordPress 6.2, Gutenberg latest (`trunk`)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by artemiomorales**
## What?
This PR changes the design of the close button in the lightbox so that it is easily visible at all times.
Additionally, it ensures the image is contained within the lightbox so that the [close button design](https://github.com/WordPress/gutenberg/issues/51126#issuecomment-1573835454 ) is implemented as closely as possible.

## Why?
Fixes https://github.com/WordPress/gutenberg/issues/51126, wherein the close button was appearing on top of images and was hard to see in cases where the image was dark, and also fixes https://github.com/WordPress/gutenberg/issues/51125, https://github.com/WordPress/gutenberg/issues/51170, and https://github.com/WordPress/gutenberg/issues/51171 as a part of those changes.

## How?
It rebases on top of and replaces https://github.com/WordPress/gutenberg/pull/51164 to make use of those fixes, then uses and sets the close button color to be the theme contrast color, adds padding, and makes the close button smaller.

## Testing Instructions
1. Ensure the Interactivity API and Behaviors UI setting is enabled in Gutenberg > Experiments in the admin.
2. Create a new post and insert a vertically oriented image as well as a horizontally oriented one.
3. Activate the image lightboxes via Advanced > Behaviors > Lightbox in block settings.
4. Publish and view the post.
5. Click on the images; in the lightbox, the close button should be clearly visible and unobscured by the image.
6. Change the theme background color and contrast color. (Note: Manually setting these colors individually will not work, I believe due to https://github.com/WordPress/gutenberg/issues/49712, but you can experiment with changing theme styles.)
7. Test again to ensure that the colors are applied as expected.

## Testing Instructions for Keyboard
- When viewing the post, tab to the image instead and press Enter or Space to open the lightbox.
- See that the close button and focus are visible.

### CODE REVIEW

File: packages/block-library/src/image/interactivity.js [hunk 1]
```diff
@@ -89,13 +89,19 @@ store( {
...
+						: '';
+				},
 			},
 		},
 	},
 	effects: {
 		core: {
 			image: {
 				initLightbox: async ( { context, ref } ) => {
+					context.core.image.imageRef = ref.querySelector( 'img' );
```
Comment (SantosGuillamot) [inline packages/block-library/src/image/interactivity.js]: Why is this needed? It doesn't seem to be used anywhere else.

File: packages/block-library/src/image/style.scss [hunk 2]
```diff
@@ -186,23 +186,36 @@
...
+		z-index: 3000000;
+		box-sizing: border-box;
+		display: flex;
+		justify-content: center;
+		align-items: center;
 		flex-direction: column;
+		padding: 30px;
+
+		figcaption {
+			margin: 10px 0 0 0;
```
Comment (SantosGuillamot) [inline packages/block-library/src/image/style.scss]: I guess that, if we are using `display: none`, we don't need this margin, right?

**Review by SantosGuillamot — APPROVED** [review]
It looks good to me 🙂 It seems to solve the mentioned issues, and it matches the design shared [here](https://github.com/WordPress/gutenberg/issues/51126#issuecomment-1573835454).

I just left a couple of minor comments.

**Comment by artemiomorales** [comment]
@SantosGuillamot Thanks for the review! I removed the obsolete code 👍
