### PR TITLE
 Remove default value for allowedTypes property

### LINKED ISSUE #24315: File block - Can't upload pdf file using Upload button but can using Media Library link
**Describe the bug**
The file block does not allow PDF uploads through the upload button but does through media library. 

**To reproduce**
1. create new post or page
1. add file block
1. Click upload 
1. select a pdf file 
1. See error - "Sorry, this file type is not supported here."  this error message is sourced at https://github.com/WordPress/gutenberg/blob/8afed75c6f2daa2624b0f91781aa4bee163d4e93/packages/media-utils/src/utils/upload-media.js#L143

**Expected behavior**
If repeat steps 1-2, but then upload through the media library, the file is successfully uploaded. 

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.4, 
- using gutenberg plugin; from master branch, most recent commit 456e1c4e13d38ca0b4365a8399c5678442d2bee0 from 2020-07-30

note, slightly different than #23510 (that error message is "the file type is not allowed for security reasons"

in my case, when I issue `wp.data.select('core/editor').getEditorSettings().allowedMimeTypes;` in the console, 
pdf is listed.

### PR DESCRIPTION
**Pull request by javidalkaruzi**
## Description
This pull request resolves #24315. While investigating, a similar behaviour was observed for images. 

## How has this been tested?
I observed that all existing unit tests passed.
I observed behaviour in the block editor by first replicating the issue then checking that my change gave the desired result.

### CODE REVIEW

File: packages/block-editor/src/components/media-placeholder/index.js [hunk 1]
```diff
@@ -157,7 +157,7 @@ export function MediaPlaceholder( {
 			setMedia = ( [ media ] ) => onSelect( media );
 		}
 		mediaUpload( {
-			allowedTypes,
+			allowedTypes: allowedTypes.length > 0 ? allowedTypes : undefined,
```
Comment (youknowriad) [inline packages/block-editor/src/components/media-placeholder/index.js:160]: Maybe we can just remove the default value for the prop?

Comment (javidalkaruzi) [reply packages/block-editor/src/components/media-placeholder/index.js:160]: That is an alternative. However, it means doing checks at several places that use this variable. I do prefer that method instead of specifying an explicit undefined value. Is this the preference at WordPress?

Comment (javidalkaruzi) [reply packages/block-editor/src/components/media-placeholder/index.js:160]: > Maybe we can just remove the default value for the prop?

That is an alternative. However, it means doing checks at several places that use this variable. I do prefer that method instead of specifying an explicit undefined value. Is this the preference at WordPress?

Comment (youknowriad) [reply packages/block-editor/src/components/media-placeholder/index.js:160]: I personally prefer removing the default value because what you're doing here is changing the meaning of the prop.

When I pass`allowedTypes = []`, I personally expect that upload is not allowed. Not that all files are allowed.

File: packages/block-editor/src/components/media-placeholder/index.js [hunk 2]
```diff
@@ -87,7 +87,7 @@ export function MediaPlaceholder( {
 	}, [ value ] );
 
 	const onlyAllowsImages = () =>
-		allowedTypes.every(
+		( allowedTypes ?? [] ).every(
```
Comment (youknowriad) [inline packages/block-editor/src/components/media-placeholder/index.js:90]: Judging from the name, this function should return false if everything is allowed and not true, right?

Comment (javidalkaruzi) [reply packages/block-editor/src/components/media-placeholder/index.js]: Yes, it should. Thanks for the catch.

**Review by youknowriad — APPROVED** [review]
Thanks, this is looking good.
