### PR TITLE
Fix copy paste and delete error core paragraph with locking

### LINKED ISSUE #12774: Copy / Paste error core/paragraph using InnerBlocks
**Describe the bug**
Using `InnerBlocks` with a nested block template, you can not copy / paste inside of the `core/paragraph` block. It results in a console error and the text is not copied into the block 
```shell
Uncaught TypeError: r is not a function
    at t.value (index.js?ver=1542840426:formatted:830)
    at t.value (index.js?ver=1542840430:formatted:11004)
    at Object.Fg (react-dom.min.713f0afa.js:formatted:4357)
    at Eg (react-dom.min.713f0afa.js:formatted:42)
    at Hg (react-dom.min.713f0afa.js:formatted:45)
    at ae (react-dom.min.713f0afa.js:formatted:96)
    at Ig (react-dom.min.713f0afa.js:formatted:4390)
    at Hc (react-dom.min.713f0afa.js:formatted:113)
    at Jc (react-dom.min.713f0afa.js:formatted:150)
    at gh (react-dom.min.713f0afa.js:formatted:872)
```
`core/heading` works fine. If I begin typing in the `core/paragraph` and then copy / paste, the new text is added without the console error.

**To Reproduce**
Add a custom block that uses `InnerBlocks` with a template that includes `core/pargraph`. Something like 
```javascript
[core/column, {}, [
  [core/paragraph, {}]
]]
```

**Expected behavior**
`core/paragraph` should not have issues with copy / paste when used inside of a nested block

**Desktop (please complete the following information):**
 - OS: OsMojave
 - Browser chrom

**Additional context**
Gutenberg version 4.5.0

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/12774

Rich text is able to handle the situation of onReplace and onRemove not existing.
When locking exist onReplace prop is not passed to blocks.
Previously onReplace prop was passed directly passed from paragraph to rich text. Now that's not the case and we have a middle function that may call the onReplace prop. If the onReplace property is not set (e.g we have locking) we should not pass the onReplace to rich text.

## How has this been tested?
I added the following CPT with locking:
```
function gutenberg_test_cpt_locking() {
	register_post_type(
		'locked-all-post',
		array(
			'public'        => true,
			'label'         => 'Locked All Post',
			'show_in_rest'  => true,
			'template'      => $template,
			'template_lock' => 'all',
		)
	);
	register_post_type(
		'locked-insert-post',
		array(
			'public'        => true,
			'label'         => 'Locked Insert Post',
			'show_in_rest'  => true,
			'template'      => $template,
			'template_lock' => 'insert',
		)
	);
}

add_action( 'init', 'gutenberg_test_cpt_locking' );
```
I verified I can paste in the paragraph.
I verified I can type something and delete all the contents again, and when I press backspace when the paragraph is empty no errors happen.
I repeated the same tests for the paragraph inside the following block:
( function() {
	const { registerBlockType } = wp.blocks;
	const { createElement: el } = wp.element;
	const { InnerBlocks } = wp.editor;

	registerBlockType( 'acme/product', {
		title: 'Product',
		icon: 'carrot',
		category: 'common',

		edit() {
			return el( 'div', { className: 'product', style: { outline: '1px solid gray', padding: 5 } },
				// Only paragraphs, images, and products:
				el(
                    InnerBlocks,
                    { template: [
                        [ 'core/heading', { placeholder: 'Slide heading...', level: 2 } ],
                        [ 'core/paragraph', { placeholder: 'Slide content...' } ],
                        [ 'core/button', { text: 'Read More', className: 'btn-lg' } ],
                    ],
                    templateLock: 'all'
                    }
                )
				// Everything and products:
				//el( InnerBlocks )
			);
		},

		save() {
			return el( 'div', { className: 'product', style: { outline: '1px solid gray', padding: 5 } },
				el( InnerBlocks.Content )
			);
		},
	} );
} )();

I verified that If I revert the fix in the paragraph block the tests start failing.

### CODE REVIEW

**Comment by aduth** [comment]
>When locking exist onReplace prop is not passed to blocks.

Could we address this by tackling #6587 as the same time?

**Comment by jorgefilipecosta** [comment]
Hi @aduth following https://github.com/WordPress/gutenberg/issues/6587 would not solve this bug.
RichText would assume onReplace is available when it is not and the copy paste on empty locked paragraphs would not work.
It is possible to simulate that by changing the paragraph code to:
```
onReplace={ this.props.onReplace ? this.onReplace : () => {} }
onRemove={ this.props.onReplace ? ( () => onReplace( [] ) ) : () => {} }
```

That said one option I see to go with https://github.com/WordPress/gutenberg/issues/6587 while solving this bug without big changes to rich text would be to have a BLOCK_EDITOR_NOOP variable referencing a function that is passed when the operation is not available. RichText would then be able to easily check if the action is not possible by comparing against BLOCK_EDITOR_NOOP.

**Comment by aduth** [comment]
>I added the following CPT with locking:

There's an unset variable `$template` in this snippet.

File: packages/block-library/src/paragraph/edit.js [hunk 1]
```diff
@@ -244,8 +244,8 @@ class ParagraphBlock extends Component {
 					} }
 					unstableOnSplit={ this.splitBlock }
 					onMerge={ mergeBlocks }
-					onReplace={ this.onReplace }
-					onRemove={ () => onReplace( [] ) }
+					onReplace={ this.props.onReplace && this.onReplace }
+					onRemove={ this.props.onReplace && ( () => onReplace( [] ) ) }
```
Comment (aduth) [inline packages/block-library/src/paragraph/edit.js]: We have the prop destructured already (it's referenced on this same line).

```suggestion
					onRemove={ onReplace && ( () => onReplace( [] ) ) }
```

**Review by aduth — APPROVED** [review]
>copy paste on empty locked paragraphs would not work.

This wasn't clear, but I tested and I see what you mean now: RichText changes its behavior based on whether it receives an `onReplace`, so it could handle internally to substitute the text when it's not available.

https://github.com/WordPress/gutenberg/blob/5b3b3aba47049e025464d4942a3e3d742c7513cf/packages/block-editor/src/components/rich-text/index.js#L286

Alternatively, we could revise the implementation so that we always pass an `onReplace` function which is _not quite_ a `noop`: For a locked template, it would allow a replacement for when the substituted value would still satisfy the template (i.e. replacing one paragraph with another).

That being said, this is still an improvement, and allows us some time to consider whether we want to guarantee a function to be passed always (#6587) separately.
