### PR TITLE
Query Loop: Fix isControlAllowed and isTemplate combined logic

### LINKED ISSUE #65902: Since Gutenberg v19.3, `allowedControls` in `core/query` block variation are ignored in Site Editor's singular template editor and post editor
### Description

Referring to the [Extending the Query Loop Block](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/extending-the-query-loop-block/) documentation, we can use the `allowedControls` property in the `core/query` block variation definition to include only some of the controls in the editor.

For example, if a block variation defines: `allowedControls: []`, the block variation will not display any controls.

However, since Gutenberg v19.3, I have found that some controls are always displayed even if they are not defined in the `allowedControls` array when in the Site Editor's singular template editor and post editor. This issue doesn't occur in the Site Editor's index template editor.

Some of the affected controls are: `postType`, `order`, and `sticky`.

I tried to roll back to previous Gutenberg versions and discovered this issue doesn't happen in v19.2.

Changes in v19.3:
https://github.com/WordPress/gutenberg/blob/v19.3.0/packages/block-library/src/query/edit/inspector-controls/index.js#L125

Compared to v19.2:
https://github.com/WordPress/gutenberg/blob/v19.2.0/packages/block-library/src/query/edit/inspector-controls/index.js#L109

There's the additional logic of `! isTemplate` that caused the issue.

### Step-by-step reproduction instructions

Create a new block variation using this snippet:

```
registerBlockVariation(
	'core/query',
	{
		name: 'testing-allowed-controls',
		title: __( 'Testing Allowed Controls' ),
		category: 'theme',
		keywords: [],
		scope: [ 'inserter' ],
		attributes: {
			namespace: 'testing-allowed-controls',
		},
		allowedControls: [],
		innerBlocks: [],
		isActive: [ 'namespace' ],
	}
);
```

Go to 3 block editors:

- Site Editor > Templates > Index
- Site Editor > Templates > Single Posts
- Posts > Add New, or edit an existing post (e.g. "Sample Page")

Add the `Testing Allowed Controls` query block variation into the block editor content via the inserter. Choose any inner blocks template.

Check the available controls in the block options panel (right sidebar).

### Screenshots, screen recording, code snippet

Using the snippet above, these are 3 different screenshots:

| Site Editor > Templates > Index | Site Editor > Templates > Single Posts | Post Editor (e.g. Sample Page)  |
| ------------------------------- | -------------------------------------- | ------------------------------- |
| Image | Image | Image |

### Environment info

WordPress 6.7 beta1

OR

WordPress 6.6.2
Gutenberg 19.3

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### PR DESCRIPTION
**Pull request by mikachan**
## What?

This fixes the logic for showing the `allowedControls` for the Query Loop block in combination with the new `isTemplate` check from https://github.com/WordPress/gutenberg/pull/65067.

## Why?

Fixes https://github.com/WordPress/gutenberg/issues/65902.

## How?

Previously, the `isTemplate` check was considered separately from the `isControlAllowed` check, and now with this PR, the logic is combined. This wasn't an intentional change to the logic, so this is a pure bug fix.

## Testing Instructions

These are taken from the testing instructions in https://github.com/WordPress/gutenberg/issues/65902:

Create a new block variation using this snippet:

```
registerBlockVariation(
	'core/query',
	{
		name: 'testing-allowed-controls',
		title: __( 'Testing Allowed Controls' ),
		category: 'theme',
		keywords: [],
		scope: [ 'inserter' ],
		attributes: {
			namespace: 'testing-allowed-controls',
		},
		allowedControls: [],
		innerBlocks: [],
		isActive: [ 'namespace' ],
	}
);
```

Go to 3 block editors:

- Site Editor > Templates > Index
- Site Editor > Templates > Single Posts
- Posts > Add New, or edit an existing post (e.g. "Sample Page")

Add the `Testing Allowed Controls` query block variation into the block editor content via the inserter. Choose any inner blocks template.

Check the available controls in the block options panel (right sidebar), and ensure that no controls are available on single posts or pages.

## Screenshots or screencast 

| Site Editor > Sample Page on trunk | Site Editor > Sample Page on this PR |
| ------ | ------- |
| image | image |

### CODE REVIEW

File: packages/block-library/src/query/edit/inspector-controls/index.js [hunk 1]
```diff
@@ -123,21 +123,18 @@ export default function QueryInspectorControls( props ) {
 	const showInheritControl =
 		isTemplate && isControlAllowed( allowedControls, 'inherit' );
 	const showPostTypeControl =
-		( ! inherit && isControlAllowed( allowedControls, 'postType' ) ) ||
-		! isTemplate;
+		! inherit && isControlAllowed( allowedControls, 'postType' );
```
Comment (mikachan) [inline packages/block-library/src/query/edit/inspector-controls/index.js:126]: `inherit` is already being set to false if on singular content in [query-conent.js](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/query/edit/query-content.js#L111), so we can remove the `isTemplate` check from these lines.

The only `isTemplate` check we need here is the one on line 124, as this decides whether to show the inherit control or not, and the intended behaviour is for this control to only show when on non-singular content (and if the control is allowed).

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

I tried enabling only some controls as shown below, and it seems to work properly:

```javascript
wp.blocks.registerBlockVariation(
	'core/query',
	{
		name: 'testing-allowed-controls',
		title: 'Testing Allowed Controls',
		category: 'theme',
		keywords: [],
		scope: [ 'inserter' ],
		attributes: {
			namespace: 'testing-allowed-controls',
		},
		allowedControls: ['author', 'search'],
		innerBlocks: [],
		isActive: [ 'namespace' ],
	}
);
```

However, I'm not familiar with the recent changes to the Query Loop block. I'd be grateful if @fabiankaegy could help me 🙏

**Review by fabiankaegy — APPROVED** [review]
In my quick testing this fixes the issue :) Thank you for the quick fix ❤️
