### PR TITLE
Fix: More block to handle Enter

### LINKED ISSUE #7324: [3.0.1] The "read more" block does not respond to "enter" despite being a single line block
**Describe the bug**
The "read more" block is a single line, so pressing "enter" does not create a second line within that block.

However, the current behavior is that when "read more" block is in focus, the "enter" key doesn't do anything.

**Expected behavior**
Pressing "enter" while within a "read more" block should open a new paragraph block.

### PR DESCRIPTION
**Pull request by mkaz**
## Description

Pressing enter in the Read More should behave like other blocks and simply create a new block and make all keyboard access a bit smoother.

Fixes #7324

## How has this been tested?

Tested adding a Read More block and pressing enter.

## Screenshots 

read-more-results

## Types of changes

Adds a `onKeyDown` listener to the More block which when checks for ENTER, when pressed will insert a new block below.

Updates unittest with new snapshot.

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style. 
- [X] My code follows the accessibility standards. 
- [X] My code has proper inline documentation.

### CODE REVIEW

**Comment by GlennMartin1** [comment]
I'd love this to be in 4.0. 👍

File: packages/block-library/src/more/edit.js [hunk 1]
```diff
@@ -26,6 +29,14 @@ export default class MoreEdit extends Component {
 		this.props.setAttributes( { customText: value } );
 	}
 
+	onKeyDown( event ) {
+		const { keyCode } = event;
+		const { insertBlocksAfter } = this.props;
+		if ( keyCode === ENTER ) {
+			insertBlocksAfter( [ createBlock( 'core/paragraph' ) ] );
```
Comment (iseulde) [inline packages/block-library/src/more/edit.js]: Maybe this should be the default block?

Comment (mkaz) [reply packages/block-library/src/more/edit.js]: @iseulde TIL. :+1:

**Review by mkaz — COMMENTED** [review]
Updated to use getDefaultBlockName() instead of core/paragraph.

**Review by swissspidy — APPROVED** [review]
