### PR TITLE
Check for match in stylesheet host and protocol

### LINKED ISSUE #20632: Lastest Version: Cant create/edit post with Block editor, Chrome
Since last gutenberg update we can not create new port, edit existing posts in Chrome.

Error: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at https://www.ksstradio.com/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=241345a79547bcd17b5c2c78b839ed72:36:273329
    at Array.forEach (<anonymous>)
    at https://www.ksstradio.com/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=241345a79547bcd17b5c2c78b839ed72:36:273285
    at Vb (https://www.ksstradio.com/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js?ver=16.9.0:4:1470)
    at Xi (https://www.ksstradio.com/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js?ver=16.9.0:5:12306)
    at unstable_runWithPriority (https://www.ksstradio.com/wp-content/plugins/gutenberg/vendor/react.min.0212dc62.js?ver=16.9.0:2:4923)
    at Ma (https://www.ksstradio.com/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js?ver=16.9.0:3:1824)
    at Yb (https://www.ksstradio.com/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js?ver=16.9.0:5:12083)
    at O (https://www.ksstradio.com/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js?ver=16.9.0:4:9409)
    at ze (https://www.ksstradio.com/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js?ver=16.9.0:4:8159)

Latest version of Chrome, WP, and Gutenberg.  System works with Firefox

### PR DESCRIPTION
**Pull request by tellthemachines**
## Description

Addresses #20632.

## How has this been tested?

Tested in several browsers (including IE) and ran automated tests.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-editor/src/components/use-simulated-media-query/index.js [hunk 1]
```diff
@@ -22,9 +23,15 @@ function getStyleSheetsThatMatchHostname() {
...
+			if ( ! styleSheet.href ) {
+				return false;
+			}
+			const matcheableUrl = styleSheet.href.match( URL_REGEX );
 			return (
-				styleSheet.href &&
-				styleSheet.href.includes( window.location.hostname )
+				matcheableUrl &&
+				matcheableUrl.length > 2 &&
+				matcheableUrl[ 1 ] === window.location.protocol &&
```
Comment (talldan) [inline packages/block-editor/src/components/use-simulated-media-query/index.js]: The url package has a `getProtocol` function that might be useful as this could be simplified to `getProtocol( styleSheet.href ) === window.location.protocol`.

File: packages/block-editor/src/components/use-simulated-media-query/index.js [hunk 2]
```diff
@@ -22,9 +23,15 @@ function getStyleSheetsThatMatchHostname() {
...
+				matcheableUrl[ 2 ] === window.location.host
```
Comment (talldan) [inline packages/block-editor/src/components/use-simulated-media-query/index.js]: The url package also has `getAuthority` function, which seems like it returns the same url part as the window.location.host (`subdomain.domain:port`).

**Review by talldan — APPROVED** [review]
Looks good. I think it might be nice to use the url package functions as they're unit tested. Having said that, i threw a few things at the regex in this PR and didn't spot any issues.

File: packages/block-editor/src/components/use-simulated-media-query/index.js (hunk 1 above)
Comment (tellthemachines) [reply packages/block-editor/src/components/use-simulated-media-query/index.js]: Oooh great tip, thanks! Updated.
