### PR TITLE
Rich text: fix internal paste across multiline and single line instances

### LINKED ISSUE #33078: Can't copy text from paragraph into the list block
## Description

Can't copy text from paragraph into the list block. This might be a symptom of a lower-level problem, but that's how it manifested so far.

## Step-by-step reproduction instructions
1. Start a new page or post and press enter to create a new `Paragraph` block;
2. Press enter again to break into a new line, then insert a `List` block;
3. Use your mouse to select the text from the `Paragraph` block, then copy it;
4. Now give focus to the `List` block again, create a new bullet point if you hadn't already. Try to paste the text you copied. You won't be able to;
5. Create a new `Paragraph` and paste the text. This time the text will be pasted as expected.

#### Other aspects to keep in mind:
* Copying text from within the `List` block and pasting into it again works;
* Copying another block and pasting from within the `List` block context works, though the new block is not inserted as an inner block (this is expected, just to note that the actual paste is done)
* Copying text from a context outside the editor canvas and pasting into the list block works (i.e try copying from the browser's address bar and pasting into the list block
* Copying from the page/post heading field into the `List` block, works.
* This might not be something specific to the `List` block but more general, but that's the scenario that can be used to easily reproduce the issue.

## Expected behaviour

I expect to be able to paste from a `Paragraph` block (or any source) into the `List` block without problems.

## Actual behaviour

Copying text from a `Paragraph`  block and pasting into the `List` block doesn't work. It just fails silently. It does work if you paste somewhere else (i.e another `Paragraph`), so it suggests that it's a problem in the logic that handles pasting for `List`.

## Additional information

I bisected and it led me to this PR: https://github.com/WordPress/gutenberg/pull/27967. If you check out its merge commit (`06f741e`), you'll see the issue still happens at its point. If you then revert it, you'll see it doesn't happen anymore.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/1451471/123830975-204dd380-d904-11eb-95d8-cd9c55e5b519.mov

## WordPress information
- WordPress version: 5.8-beta4-51261
- Gutenberg version: `trunk`
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: Ubuntu Linux 18.04
- Browser: Firefox 90.0b12 64bit and Chrome 91.0.4472.101 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #33078.

Problem: the multilineTag context is lost when pasting across rich text instances. This causes the HTML to be parsed wrongly.
Solution: pass the multilineTag through the transferData, so we can recreate the rich text value from the HTML correctly.

I also added a function to replace line separators with line breaks when pasting a multiline value into a single line instance and to replace line breaks with line separators when pasting a single line value into a multiline instance. The latter is already used for external paste.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-editor/src/components/rich-text/use-paste-handler.js [hunk 1]
```diff
@@ -21,6 +21,25 @@ import { filePasteHandler } from './file-paste-handler';
...
 import { splitValue } from './split-value';
 
+/** @typedef {import('@wordpress/rich-text').RichTextValue} RichTextValue */
+
+/**
+ * Replaces line separators with line breaks if not multiline.
+ * Replaces line breaks with line separators if multiline.
+ *
+ * @param {RichTextValue} value       Value to adjust.
+ * @param {boolean}       isMultiline Wether to adjust to multiline or not.
```
Comment (mcsf) [inline packages/block-editor/src/components/rich-text/use-paste-handler.js]:
```suggestion
 * @param {boolean}       isMultiline Whether to adjust to multiline or not.
```

**Review by mcsf — APPROVED** [review]
Thanks for the quick fix, this makes more sense to me!

Related to this, I noticed in `createFromMultilineElement` that `currentWrapperTags` is [documented](https://github.com/WordPress/gutenberg/blob/34f08ab091e8f0575cb9730c528e5f5dbccb0e0e/packages/rich-text/src/create.js#L514) as a boolean (in the `@param` type and in the English description), but used as an array. Could you patch it before merging this?
