### PR TITLE
Synced Pattern: Guard against redeclaration of `WP_Block_Cloner`

### LINKED ISSUE #71170: Fatal error when adding a synced pattern to a template at root level
### Description

When a synced pattern is added to the root level of a template, there's a fatal error on the front end of any pages using that template:

`Fatal error: Cannot declare class WP_Block_Cloner, because the name is already in use in /var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/block.php on line 92`

Looks like `class WP_Block_Cloner` was introduced in #70943. @ockham any idea why this might be happening?

### Step-by-step reproduction instructions

1. Open up the homepage template;
2. Add a synced pattern to it at root level (it helps to check list view to make sure it's not going into any group block or anything - see attached screenshot)
3. Save and check the front end.

### Screenshots, screen recording, code snippet

Image

### Environment info

Latest WP, Gutenberg trunk.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by ockham**
## What?
Closes #71170

In the Synced Pattern block, there's code that's conditionally code when run on a WordPress version < 6.8. That code includes a helper class declaration, `WP_Block_Cloner`.

## Why?
It's a 🐛 

## How?
By adding a simple `if class_exists()` guard.

## Testing Instructions
Make sure you're running GB on a WP version < 6.8 (e.g. 6.7.3). Then, follow the instructions in #71170 and verify that the bug is fixed by this PR.

### CODE REVIEW

**Comment by ockham** [comment]
Maybe I'll change the helper class prefix to `Gutenberg_` while I'm here 🤔

**Comment by ockham** [comment]
> Maybe I'll change the helper class prefix to `Gutenberg_` while I'm here 🤔

Ah, nevermind, we have a WPCS rule against that -- in order to avoid block code with `Gutenberg_` ending up in Core. Fair enough, I'll leave it at `WP_Block_Cloner`. The fallback code should never run in Core anyway, as `WP_Block::refresh_context_dependents` exists there.

**Comment by ockham** [comment]
👋 @priethor Once merged, this should be cherry-picked to the 21.4 branch, prior to release of the stable version.

File: packages/block-library/src/block/index.php [hunk 1]
```diff
@@ -88,20 +88,22 @@ function render_block_core_block( $attributes, $content, $block_instance ) {
...
-			 * In this case, this gives us access to `available_context` and `registry`.
-			 */
-			// phpcs:ignore Gutenberg.Commenting.SinceTag.MissingMethodSinceTag
-			public static function clone_instance( $instance ) {
-				return new WP_Block(
-					$instance->parsed_block,
-					$instance->available_context,
-					$instance->registry
-				);
+		if ( ! class_exists( 'WP_Block_Cloner' ) ) {
```
Comment (gziolo) [inline packages/block-library/src/block/index.php:91]: If this is code should run only in the Gutenberg plugin then an alternative check would work, too:

```php
defined( 'IS_GUTENBERG_PLUGIN' ) && IS_GUTENBERG_PLUGIN
```

**Review by gziolo — APPROVED** [review]

File: packages/block-library/src/block/index.php (hunk 1 above)
Comment (ockham) [reply packages/block-library/src/block/index.php:91]: Based on the bug report, it seems like the issue wasn't due to a collision between GB and Core, but rather the GB block code being loaded twice (and the class thus being redeclared).

**Comment by tellthemachines** [comment]
Thanks for the quick fix Bernie!

**Comment by priethor** [comment]
I just cherry-picked this PR to the release/21.4 branch to get it included in the next release: 9b6697ab5b
