### PR TITLE
 Theme JSON: Clarify status of fixed position opt-in in appearance tools

### LINKED ISSUE #48635: `WP_Theme_JSON` classes: clarify status of `position.fixed`
## What problem does this address?

In comparing Gutenberg and WordPress core versions of the `WP_Theme_JSON` class, I realized the `position.sticked` setting/style was backported but the `postition.fixed` is in a mixed position.

## What I know

This core ticket https://core.trac.wordpress.org/ticket/57618 and corresponding PR https://github.com/WordPress/wordpress-develop/pull/3973 backported to core support for `position.sticky`, where it's mentioned that:

> The backport deviates from Gutenberg trunk in one way: fixed position type is excluded from the appearance tools opt-in: this is because fixed positioning isn't being opted-in for the Group block and isn't ready to be used as a default opt-in. The code paths exist for fixed positioning as it will be supported in the future, but for now, sticky is the only one exposed by default. (The overall block support should still support it as a valid value, though)

However, WordPress core still considers `position.fixed` a valid setting, as per https://github.com/WordPress/wordpress-develop/pull/3973/files#diff-e12c3008d747d1bec5be9927c5e7b1ced0a88641abe52c278d495da936714817R343

## Next steps

I don't know.

Without having the full context, I presume we may need to:

- WordPress core: do not have `postition.fixed` as a valid setting?

- Gutenberg: if making Gutenberg work like core is not feasible, at least we need to document the situation. In other cases where we don't want to backport some code we add a comment, like we do for [fonts](https://github.com/WordPress/gutenberg/blob/trunk/lib/class-wp-theme-json-resolver-gutenberg.php#L277) and [appearance tools](https://github.com/WordPress/gutenberg/blob/trunk/lib/class-wp-theme-json-resolver-gutenberg.php#L322).

### PR DESCRIPTION
**Pull request by andrewserong**
## What?

Fixes: #48635

Add a comment to the Theme JSON class clarifying the current status of the `position.fixed` opt-in within appearance tools.

## Why?

As raised in #48635, without a comment, it isn't clear why there's a discrepancy between the core code and the Gutenberg code for this particular opt-in.

As discussed in https://github.com/WordPress/gutenberg/issues/48635#issuecomment-1450970783 and https://github.com/WordPress/wordpress-develop/pull/3973#discussion_r1097984933, Gutenberg should be slightly more permissive than core here, so that it's easier to test subsequent explorations in adding `fixed` to the Group block, but this wasn't desired in core. In core, `fixed` is a valid setting, but it needs to be opted-in intentionally so that it isn't accidentally exposed anywhere.

## How?

Add a comment to the Theme JSON class explaining the current status of the `position.fixed` opt-in. This uses the same `// BEGIN EXPERIMENTAL` and `// END EXPERIMENTAL` comments I've seen used elsewhere.

## Testing Instructions

1. Proofread the comments.
2. (Optional) Load up the site editor or post editor with TT3 theme, and check that you can still access the Position panel and set Sticky (this just checks that I didn't add a typo or anything to break the PHP file)

### CODE REVIEW

File: lib/class-wp-theme-json-gutenberg.php [hunk 1]
```diff
@@ -555,7 +555,12 @@ public static function get_element_class_name( $element ) {
 		array( 'border', 'width' ),
 		array( 'color', 'link' ),
 		array( 'dimensions', 'minHeight' ),
+		// BEGIN EXPERIMENTAL.
+		// Allow `position.fixed` to be opted-in by default.
+		// Sticky position support was backported to WordPress 6.2 in https://core.trac.wordpress.org/ticket/57618.
+		// While `fixed` was included as a valid setting, exposing it by default it still experimental.
```
Comment (aaronrobertshaw) [inline lib/class-wp-theme-json-gutenberg.php]:
```suggestion
		// While `fixed` was included as a valid setting, exposing it by default is still experimental.
```

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for adding the detailed comment @andrewserong 👍 

I think it helps explain why `position.fixed` is being added to the appearance tools opt-in within Gutenberg only and clearly marks its inclusion as experimental. There's one small typo in it though.

The sticky position support continues to function for me as well.

Screenshot 2023-03-02 at 11 18 04 am

**Comment by andrewserong** [comment]
Thanks for the review and for spotting the typo @aaronrobertshaw!

**Review by oandregal — APPROVED** [review]

**Comment by andrewserong** [comment]
Thanks for the reviews!
