### PR TITLE
`Spacer`: Fix changes being marked as persistent to `undo`

### LINKED ISSUE #68863: Undo breakage with Spacer block and Row/Stack
### Description

Inserting or moving a Spacer block into a Row/Stack block stops undo from working. Moving a Spacer block out of a Row/Stack has the same effect. I expect undo to keep working.

### Step-by-step reproduction instructions

1. Insert a Row or Stack block.
2. Insert a Spacer into the previously inserted Row or Stack.
3. Try to undo.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/4f0a61b7-9552-4272-885b-e963401d31a5

### Environment info

WP 6.7.1 / Gutenberg plugin trunk
Chrome 130
macOS 13.7.1

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by yogeshbhutkar**
## What, Why and How?

Fixes: #68863 

Currently, inserting or moving a `Spacer block` into a Row or Stack block disrupts the `undo` functionality. Similarly, moving a `Spacer block` out of a Row or Stack block also breaks the `undo` behavior. 

Also, Converting a `Row block` containing a `Spacer block` into a `Group block` caused undo to fail.

## Testing Instructions

Step 1: Navigate to the `post edit` page.
Step 2: Verify the undo functionality with `Spacer` works for the following cases:

- Case 1: Using `Flex Containers`. ( i.e. `Row` & `Stack` without setting `selfStretch` to `fit` or `fill` ).
- Case 2: Using `Flex Containers` with `selfStretch` to be either `fit` or `fill`.
- Case 3: `Non-Flex Container` with `selfStretch` to be either `fit` or `fill`.
- Case 4: Move `Spacer` into `Row/Stack`.
- Case 5: Move `Spacer` out of `Row/Stack`.
- Case 6: With `Spacer` inserted into a `Row/Stack`, convert it to `Group` and verify undo.

## Screencast

https://github.com/user-attachments/assets/3f53a999-b70b-4f07-871a-fc67df9ac4c3

### CODE REVIEW

**Comment by yogeshbhutkar** [comment]
Hi, @stokesman, can you please review the PR when you get a moment?

File: packages/block-library/src/spacer/edit.js [hunk 1]
```diff
@@ -320,6 +326,10 @@ const SpacerEdit = ( {
 					height: flexSize,
 				} );
 			}
+
+			// This ensures that the next change is not marked as persistent
+			// when the user changes the container layout.
```
Comment (stokesman) [inline packages/block-library/src/spacer/edit.js]: Given there are multiple places in the effect this comment is applicable I think it’d be better to remove this and instead put a more generalized version at the start of the effect. Something like:
```js
// To avoid interfering with undo/redo operations any changes in this
// effect must not make history and should be preceded by
// `__unstableMarkNextChangeAsNotPersistent()`
```

**Review by stokesman — COMMENTED** [review]
Thanks for tackling this one! The changes make sense. I’ve tested and can no longer reproduce the issue.

I have one specific suggestion I’d like to see done and I’ll leave a separate comment fort that. Alternatively, I’ll include here a larger suggested diff that incorporates it but also changes the code style to be less verbose. Please apply it only if you’d agree it’s a clear improvement. I’m fine with keeping the changes more minimal.

<details><summary>Reduce some verbosity and add a general comment about making changes non-persistent</summary>

```diff
diff --git a/packages/block-library/src/spacer/edit.js b/packages/block-library/src/spacer/edit.js
index cd21870f0c..c11201861a 100644
--- a/packages/block-library/src/spacer/edit.js
+++ b/packages/block-library/src/spacer/edit.js
@@ -259,13 +259,18 @@ const SpacerEdit = ( {
 	};
 
 	useEffect( () => {
+		// To avoid interfering with undo/redo operations any changes in this
+		// effect must not make history.
+		const setAttributesCovertly = ( nextAttributes ) => {
+			__unstableMarkNextChangeAsNotPersistent();
+			setAttributes( nextAttributes );
+		};
 		if (
 			isFlexLayout &&
 			selfStretch !== 'fill' &&
 			selfStretch !== 'fit' &&
 			flexSize === undefined
 		) {
-			__unstableMarkNextChangeAsNotPersistent();
 			if ( inheritedOrientation === 'horizontal' ) {
 				// If spacer is moving from a vertical container to a horizontal container,
 				// it might not have width but have height instead.
@@ -273,7 +278,7 @@ const SpacerEdit = ( {
 					getCustomValueFromPreset( width, spacingSizes ) ||
 					getCustomValueFromPreset( height, spacingSizes ) ||
 					'100px';
-				setAttributes( {
+				setAttributesCovertly( {
 					width: '0px',
 					style: {
 						...blockStyle,
@@ -289,7 +294,7 @@ const SpacerEdit = ( {
 					getCustomValueFromPreset( height, spacingSizes ) ||
 					getCustomValueFromPreset( width, spacingSizes ) ||
 					'100px';
-				setAttributes( {
+				setAttributesCovertly( {
 					height: '0px',
 					style: {
 						...blockStyle,
@@ -305,32 +310,16 @@ const SpacerEdit = ( {
 			isFlexLayout &&
 			( selfStretch === 'fill' || selfStretch === 'fit' )
 		) {
-			__unstableMarkNextChangeAsNotPersistent();
-			if ( inheritedOrientation === 'horizontal' ) {
-				setAttributes( {
-					width: undefined,
-				} );
-			} else {
-				setAttributes( {
-					height: undefined,
-				} );
-			}
+			setAttributesCovertly(
+				inheritedOrientation === 'horizontal'
+					? { width: undefined }
+					: { height: undefined }
+			);
 		} else if ( ! isFlexLayout && ( selfStretch || flexSize ) ) {
-			__unstableMarkNextChangeAsNotPersistent();
-			if ( inheritedOrientation === 'horizontal' ) {
-				setAttributes( {
-					width: flexSize,
-				} );
-			} else {
-				setAttributes( {
-					height: flexSize,
-				} );
-			}
-
-			// This ensures that the next change is not marked as persistent
-			// when the user changes the container layout.
-			__unstableMarkNextChangeAsNotPersistent();
-			setAttributes( {
+			setAttributesCovertly( {
+				...( inheritedOrientation === 'horizontal'
+					? { width: flexSize }
+					: { height: flexSize } ),
 				style: {
 					...blockStyle,
 					layout: {

```

File: packages/block-library/src/spacer/edit.js (hunk 1 above)
Comment (yogeshbhutkar) [reply packages/block-library/src/spacer/edit.js]: Thanks for the review, @stokesman, I've incorporated the suggested changes in the latest commit.

**Comment by yogeshbhutkar** [comment]
While testing this PR, I discovered a bug in the Spacer block. When a flex container's orientation is vertical and the Spacer block's `selfStretch` is set to Grow, the `resizable` div lacks height, causing the draggable indicator to align at the top instead of the bottom. Additionally, the gray highlight on selecting the Spacer block is missing.

https://github.com/user-attachments/assets/13fa6ec2-4239-48c7-8084-1a287d498e3d

**Expected:**
Screenshot 2025-01-27 at 10 39 43 AM

It's best to tackle this issue separately.

**Review by stokesman — APPROVED** [review]
I’ve tested again and undo is working for all scenarios. Thank you for tackling this.
