### PR TITLE
Fix Inconsistent Labels for Lightbox Feature

### LINKED ISSUE #55617: Image block: Lightbox setting name and labels are inconsistent
### Description

Splitting this out from https://github.com/WordPress/gutenberg/pull/54509#issuecomment-1751322560

The LIghtbox setting in the UI is named `Expand on Click`.
However, the visually hidden labels used in the front end use the verb 'Enlarge`:
- aria-label for the trigger button: Enlarge image
- aria-label for the modal dialog: Enlarged image

Whatever the decision about the term to use is, the terminology should be the same in the admin and in the front end. Users of assistive technology who perceive the aria-labels will hear the verb 'Enlarge'. When they will search for the related I control in the admin they will find an UI. control that says 'Expand' instead. This seems not ideal and potentially confusing. A goo dUI should take care also of visually hidden names and descriptions.

Personally I don't have a strong preference. Also, I'm not a native English speaker but, to me, 'Exoand` doesn't sound entirely appropriate. 'Enlarge' seems more correct to me. Regardless, These strings should be consistend and use the same term.

Prioir discussion on the setting name occurred on https://github.com/WordPress/gutenberg/issues/53403

Cc @artemiomorales  @Poliuk @jameskoster @jasmussen 

**Additional issue:**

- I'm not sure why the word 'Click' is title case. 'Click' is not a name of a WordPress feature, it should be lowercase. Also, in the description of the toggle when disabled, it is lowercase and as such it's inconsistent with the toggle name:

Screenshot 2023-10-25 at 09 23 28

### Step-by-step reproduction instructions

- Edit a post, add an image with lightbox enabled.
- Observe the setting name is 'Expand on Click` and the C of the word Click is uppercase.
- Save and view the front end.
- Inspect the source and observe the aria-label of the button to open the lightbox is 'Enlarge image'. Expected: to use a coonsistent terminology with the editor.
- Open the lightbox modal dialog.
- Inspect the source and observe the aria-label of the modal dialog is 'Enlarge image {alt attribute text here if any}'. Expected: to use a coonsistent terminology with the editor.
- In the editor, add an image with a link.
- Observe the lightbox setting in the settings panel is disabled.
- Observe the disabled setting shows a description where the word 'click' is all lowercase. Expected: to have consistent casing.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by karthick-murugan**
## What?
Fixes https://github.com/WordPress/gutenberg/issues/55617 

This PR ensures consistent terminology between the editor (backend) and frontend for the lightbox feature. The label "Expand on click" in the editor has been updated to "Enlarge image" for alignment with the frontend aria-labels.

## Why?
Consistency in terminology is vital for accessibility and usability. Users of assistive technology will now encounter the same terms ("Enlarge image") in both the editor and frontend, reducing potential confusion. 

## How?

- Updated the editor UI setting label from "Expand on click" to "Enlarge image."
- Verified that the aria-label for the trigger button and modal dialog in the frontend is "Enlarge image," ensuring consistency across the interface.

## Testing Instructions

1. Open a post or page.
2. Insert an image block with the lightbox feature enabled.
3. Observe that the lightbox setting in the editor now reads "Enlarge image."

## After making changes 

enlarge_1

enalrge_2

enlarge_3

### CODE REVIEW

**Comment by karthick-murugan** [comment]
@afercia - Please have a look at this PR and let me know if you have any suggestions.

File: packages/block-library/src/image/index.php [hunk 1]
```diff
@@ -234,6 +229,7 @@ class="lightbox-trigger"
 			type="button"
 			aria-haspopup="dialog"
 			aria-label="' . esc_attr( $aria_label ) . '"
+			aria-describedby="' . esc_attr( $alt ) . '"
```
Comment (afercia) [inline packages/block-library/src/image/index.php]: The `aria-describedby` attribute should point to the ID of a hidden element that contains the description. If it turns to be too complicated, we could consider to not use a description at all.

**Review by afercia — CHANGES_REQUESTED** [review]
I left a comment about aria-describedby that should be addressed.
Also, some tests are failing because they still expect a button with name 'Expand on click'', they should be updated/
A quick note; I think the preferred way to sync with trunk is to rebase insteaf of merging trunk.

File: packages/block-library/src/image/index.php (hunk 1 above)
Comment (karthick-murugan) [reply packages/block-library/src/image/index.php]: @afercia - Considering the complexity of this implementation, I have removed the aria-describedby attribute as per your suggestion. We can address it in a separate PR to ensure it is handled comprehensively.

**Comment by afercia** [comment]
@karthick-murugan thanks for working on this. 
The aria-label of the modal dialog should be adjusted to be more meaningful. Currently, it uses the same text used for hte button: `Enlarge`. However, the modal dialog should be labeled to communicate this is the _enlarged_ image. Something simple like `Enlarged image` would work, I think.

I think that the button label should stay `__( 'Enlarge' )` and a new `$dialog_aria_label` variable should be added with value `__( 'Enlarged image' )`  and then be used [here](https://github.com/WordPress/gutenberg/blob/54f59fece2d9abd28fea97f3c2273dd9fc6e0eb8/packages/block-library/src/image/index.php#L193).

**Review by afercia — CHANGES_REQUESTED** [review]
Looks good to me but a new variable should be adder to be used for the modal dialog label.

**Comment by karthick-murugan** [comment]
> Looks good to me but a new variable should be adder to be used for the modal dialog label.

@afercia - Thanks for your time on reviewing this PR. Updated the changes that you have requested.

**Review by afercia — APPROVED** [review]
Looks good to me.
This improves naming consistency, simplifies labeling and makes the UI more predictable.
