### PR TITLE
Fix core-block-patterns support on GB

### LINKED ISSUE #31510: remove_theme_support('core-block-patterns') ignored
I have the following in my theme functions file: 

```
add_action( 'after_setup_theme', 'my_theme_setup' );
function my_theme_setup(){
	remove_theme_support( 'core-block-patterns' );
}
```

And all of the Patterns still appear. 

WP: 5.7.1
Gutenberg: 10.5.4
Macbook Pro 
Chrome 90.0.4430.93

Cheers,
Brad

### PR DESCRIPTION
**Pull request by MaggieCabrera**
## Description

After adding the new default block patterns to the plugin, the `core-block-patterns` support stopped working. This PR restores its functionality. This fix won't be needed in core.

Fixes https://github.com/WordPress/gutenberg/issues/31510

## How has this been tested?

Add this to your current theme:

```
add_action( 'after_setup_theme', 'my_theme_setup' );
function my_theme_setup(){
	remove_theme_support( 'core-block-patterns' );
}
```

Check that the new default patterns don't show up on the inserter (this PR doesn't consider the new Query patterns and the Social Links pattern as "core" patterns, I can change accordingly if they should apply too)

## Types of changes

Bug fix (non-breaking change which fixes an issue) 

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: lib/block-patterns.php [hunk 1]
```diff
@@ -185,6 +185,8 @@
 	'init',
 	function() {
 
+		$should_register_core_patterns = get_theme_support( 'core-block-patterns' );
```
Comment (ntsekouras) [inline lib/block-patterns.php]: I think it's fine to just have this check at the top of the function:
```
if ( ! get_theme_support( 'core-block-patterns' ) || ! function_exists( 'unregister_block_pattern' ) ) {
	return;
}
```

Unregistering will have be handled already.

**Review by ntsekouras — COMMENTED** [review]
Thanks for working on this @MaggieCabrera !

>this PR doesn't consider the new Query patterns and the Social Links pattern as "core" patterns

IMO I think it's fine to leave them as are, especially the `Query` ones that make the insertion/setup way friendlier.

**Comment by youknowriad** [comment]
> this PR doesn't consider the new Query patterns and the Social Links pattern as "core" patterns, I can change accordingly if they should apply too

I think that's a good question, folks that use this filter do expect all patterns to go away at least in the inserter.

**Comment by MaggieCabrera** [comment]
> > this PR doesn't consider the new Query patterns and the Social Links pattern as "core" patterns, I can change accordingly if they should apply too
> 
> I think that's a good question, folks that use this filter do expect all patterns to go away at least in the inserter.

Yeah, but they expect the core patterns to go away, and these are still not on core, they are part of the plugin. That's why I hesitated.

**Comment by youknowriad** [comment]
> Yeah, but they expect the core patterns to go away, and these are still not on core, they are part of the plugin. That's why I hesitated.

**Comment by youknowriad** [comment]
> Yeah, but they expect the core patterns to go away, and these are still not on core, they are part of the plugin. That's why I hesitated.

They are not in Core because Query block was not in Core yet, it will be with 10.6

**Comment by MaggieCabrera** [comment]
What about the social links one? I think @ntsekouras you added that one.

**Comment by vdwijngaert** [comment]
I'm inclined to omit the Query and Social Links blocks as well, in this case.

**Comment by ntsekouras** [comment]
>They are not in Core because Query block was not in Core yet, it will be with 10.6

I pushed a change to hide all of them. Check the diff without whitespace changes [here](https://github.com/WordPress/gutenberg/pull/31546/files?diff=split&w=1).

>What about the social links one

I think this can land in core and if not we will register only that after 10.6. --cc @kjellr

**Comment by kjellr** [comment]
Eventually, most or all of these will move over to the pattern directory, and _not_ be bundled with Gutenberg or Core. 

But in the meantime, using `remove_theme_support( 'core-block-patterns' );` to hide all core/gutenberg-provided all makes sense. 👍

**Review by vdwijngaert — APPROVED** [review]
Works as expected :)

One side-effect, however, is that when a theme does not add patterns of itself, the pattern tab in the inserter is empty. But that could be addressed in a follow-up issue. 

image

**Comment by ntsekouras** [comment]
>One side-effect, however, is that when a theme does not add patterns of itself, the pattern tab in the inserter is empty. But that could be addressed in a follow-up issue.

Yeah, this is a separate issue. I created a PR for this: https://github.com/WordPress/gutenberg/pull/31687
