### PR TITLE
useEntityRecord: Fix destructure error when `enabled` option is `false`

### LINKED ISSUE #51466: The enabled option triggers an error on useEntityRecord if set to false.
### Description

Setting the enabled: false option when using useEntityRecord triggers a destructuring error instead of deactivating the query : 
Uncaught TypeError: Cannot destructure property 'data' of 'useQuerySelect(...)' as it is null.
    at useEntityRecord (core-data.js?ver=60feb4306fe9534bc937:6862:11)

### Step-by-step reproduction instructions

1. Create any kind of block
2. Try to use getEntityRecord with valid info, for example `const {record, isResolving} = useEntityRecord('postType','post',1);`
3. Assert it works
4. Add, the {enabled: false} option as a fourth parameter
5. It should trigger the error

### Screenshots, screen recording, code snippet

When looking at the current useEntityRecord source code, I can see why we have this error.

Here, if options.enabled is false, we return null : https://github.com/WordPress/gutenberg/blob/trunk/packages/core-data/src/hooks/use-entity-record.ts#L184-L185

Then, if I understand correctly the function tries to extrapolate data: record, ...querySelectRest from null (https://github.com/WordPress/gutenberg/blob/trunk/packages/core-data/src/hooks/use-entity-record.ts#L182), resulting in the given error.

### Environment info

- WP 6.2.2
- MacOs BigSur 
- Chrome 114.0.5735.106

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes: #51466
Related to #39288

## What?
This PR fixes an error that occurs when `{ enabled: false }` is specified in the fourth argument of `useEntityRecord`.

For example, when you write code like this:

```javascript
const { record, isResolving } = useEntityRecord( 'postType', 'page', 1, {
	enabled: false,
} );
```

The following error is logged in the browser console:

```
use-entity-record.ts:182 Uncaught TypeError: Cannot destructure property 'data' of '(0 , _use_query_select__WEBPACK_IMPORTED_MODULE_4__.default)(...)' as it is null.
```

## Why?
This is because if `enabed` is `false`, the internal `useQuerySelect` returns `null` and the `data` property cannot be destructured.

## How?
I referred to [getEntityRecords implementation](https://github.com/WordPress/gutenberg/blob/14dc7d2ad9151470431d584615aadddcb6e736ef/packages/core-data/src/hooks/use-entity-records.ts#L89-L94), but I think it should be the value of the `data` property that is null, not the entire object.

## Testing Instructions
Confirm that the following code does not cause an error.

The `record` variable should be the post object if the post exists, or `undefined` if it does not:

```javascript
const { record } = useEntityRecord( 'postType', 'page', 2 );
```

```javascript
const { record } = useEntityRecord( 'postType', 'page', 2, {
	enabled: true,
} );
```

The `record` variable should always be `null`:

```javascript
const { record } = useEntityRecord( 'postType', 'page', 2, {
	enabled: false,
} );
```

### CODE REVIEW

File: packages/core-data/src/hooks/use-entity-record.ts [hunk 1]
```diff
@@ -182,7 +182,10 @@ export default function useEntityRecord< RecordType >(
 	const { data: record, ...querySelectRest } = useQuerySelect(
 		( query ) => {
 			if ( ! options.enabled ) {
-				return null;
+				return {
+					// Avoiding returning a new reference on every execution.
```
Comment (Mamaduka) [inline packages/core-data/src/hooks/use-entity-record.ts]: There's no need for this comment; The `null` value, like other primitive values, always has a stable reference.

**Review by Mamaduka — APPROVED** [review]
Thanks, @t-hamano!

File: packages/core-data/src/hooks/use-entity-record.ts (hunk 1 above)
Comment (t-hamano) [reply packages/core-data/src/hooks/use-entity-record.ts]: @Mamaduka 

Thanks for the review! Now I would like to delete this comment before merging.

Comment (Mamaduka) [reply packages/core-data/src/hooks/use-entity-record.ts]: Thanks, @t-hamano!
