### PR TITLE
RTL fix for inlined block-styles

### LINKED ISSUE #41649: When Gutenberg is active, RTL styles are not loading correctly on the front.
### Description

Different RTL files and styles are loaded on the front of the website depending on if Gutenberg is active or not.
This breaks some RTL styles, for example for the query pagination and comment query pagination blocks.

The example page I am using to reproduce this is the front page of Twenty Twenty-Two, with enough posts to show the query pagination in the query loop.

WordPress trunk, without Gutenberg, loads the following rtl files:
```
<link rel='stylesheet' id='wp-block-navigation-rtl-css'  href='http://localhost:8889/wp-includes/blocks/navigation/style-rtl.css?ver=6.1-alpha-53344-src' media='all' />
<link rel='stylesheet' id='wp-block-image-rtl-css'  href='http://localhost:8889/wp-includes/blocks/image/style-rtl.css?ver=6.1-alpha-53344-src' media='all' />
<link rel='stylesheet' id='wp-block-columns-rtl-css'  href='http://localhost:8889/wp-includes/blocks/columns/style-rtl.css?ver=6.1-alpha-53344-src' media='all' />
<link rel='stylesheet' id='wp-block-library-rtl-css'  href='http://localhost:8889/wp-includes/css/dist/block-library/common-rtl.css?ver=6.1-alpha-53344-src' media='all' />
```
Inline styles are replaced with their rtl versions. - For example to rotate the query pagination arrows.

With Gutenberg 13.4.0 active, the following rtl file is loaded, but it is the only one:
`<link rel='stylesheet' id='wp-block-navigation-rtl-css'  href='http://localhost:8889/wp-content/plugins/gutenberg/build/block-library/blocks/navigation/style-rtl.css?ver=1654842440' media='all' />`
Inline styles are not replaced with their rtl versions, and the query pagination arrows are not rotated.

See https://github.com/WordPress/gutenberg/pull/40684#issuecomment-1151373296

### Step-by-step reproduction instructions

1. Activate Gutenberg trunk or 13.4.0.
2. Activate an RTL language. I tested with Arabic.
3. Add or select a query pagination block and enable the arrow option. Save,
4. Compare the position and direction of the arrows in the editor and the front, confirm that the views do not match.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WordPress trunk
Gutenberg trunk or 13.4-0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by aristath**
## What?

Fixes #41649 

## Why?

When replacing block styles in Gutenberg, we don't account for RTL styles.

## How?
Adds an extra condition to change the path for inline styles to their RTL counterpart.

## Testing Instructions
Switch to an RTL language and ensure that the RTL styles get loaded.
To make testing easier, you can also add `var_dump( $style_path );` below the line that changed to see more clearly that the RTL styles are the ones that get loaded.

### CODE REVIEW

File: lib/blocks.php [hunk 1]
```diff
@@ -193,19 +193,22 @@ function gutenberg_register_core_block_assets( $block_name ) {
 
 	$style_path        = "build/block-library/blocks/$block_name/style.css";
```
Comment (jorgefilipecosta) [inline lib/blocks.php]: Instead of calling a str_replace could we define $style_path as $style_path        = "build/block-library/blocks/$block_name/" . ( is_rtl() ? 'style-rtl.css' : 'style.css' );

Comment (aristath) [reply lib/blocks.php]: Hmmm we also do `wp_style_add_data( "wp-block-{$block_name}", 'rtl', 'replace' );`, and if we change the `$style_path` there, then the RTL stylesheet would end up being `style-rtl-rtl.css` because `-rtl` would get appended twice.
That is the main reason I chose to do it this way... We needed to change the _absolute path_ but not the _url_.

**Review by carolinan — COMMENTED** [review]
_Not a code review._

With the PR applied, on RTL, using Twenty Twenty-Two.
Navigation block:
Blocks/navigation/style-rtl.css is loading.
The margin on the submenu button is correctly moved to the right of the button.

- During testing I noticed that this margin was incorrect in WordPress 6.0 without Gutenberg installed. Perhaps this can be backported to a minor release.

Query pagination block:
The arrows are pointing in the correct direction. The spacing is also correct.
This is an improvement over Gutenberg 13.4.0.

Comment pagination block:
The arrows are pointing in the correct direction. The spacing is also correct.
This is an improvement over Gutenberg 13.4.0.

I think it would be good if an RTL user could test and confirm, since there are probably more areas to test than the 3 above.

File: lib/blocks.php (hunk 1 above)
Comment (aristath) [reply lib/blocks.php]: Updated the implementation and it no longer uses str_replace 👍

**Comment by aristath** [comment]
Updated the PR and rebased, this is now ready for another review 👍

File: lib/blocks.php (hunk 1 above)
Comment (jorgefilipecosta) [reply lib/blocks.php]: Thank you for the change, the code looks good 👍

**Review by jorgefilipecosta — APPROVED** [review]
The change looks good to me 👍

**Comment by jorgefilipecosta** [comment]
Does this change need backporting as it seems we have the same problem in core now https://core.trac.wordpress.org/ticket/56325?

**Comment by scruffian** [comment]
I rebased this.

**Review by scruffian — APPROVED** [review]
LGTM

**Comment by aristath** [comment]
Thank you @jorgefilipecosta and @scruffian!

> Does this change need backporting as it seems we have the same problem in core now https://core.trac.wordpress.org/ticket/56325?

Yes, it should be backported 👍
