### PR TITLE
Fix: Add cursor pointer to the ariakit menu item component - Issue - #70411

### LINKED ISSUE #70411: Update Menu component base item to have cursor pointer style for UX
### Description

- Since we are in progress of updating the `DropDownMenu` to `Ariakit Menu` a newer version, on checking the menu's in dataview or post actions, it seems that it is missing the basic `cursor: pointer`, style for the mouse interaction which can be an issue in terms of UX, as current implementation of `DropDownMenu` component adds this UX experience, so we should consider it for the `Menu` specifically to `Menu.Item` component.

See below recording,

https://github.com/user-attachments/assets/4cfdacc5-4c0b-41e4-a096-de09805a90ff

Since, all this actions are something which needs to be clicked, so we should be adding some UX experience instead of a normal cursor and update it to pointer.

### Step-by-step reproduction instructions

1. Go to any post/page edit screen.
2. Check for the posts actions Menu item and hover to each menu item.
3. You will notice it does not indicates that Menu Item is clickable and should improve UX.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- Gutenberg: Trunk.
- WP: 6.8.1
- MAC M1 AIR, Sonoma 14.5

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by hbhalodia**
## What?

Closes #70411 70411

- PR updates the style for `baseItem` component to use cursor pointer to enhance the UX.

## Why?

- It resolves #70411

## How?

- Update `baseItem` styled component to use the `cursor: pointer` style.

## Testing Instructions

1. Open any post/page in editor.
2. Check for post actions, you would notice the cursor is pointer for the menu items.

### Testing Instructions for Keyboard

- NIL

## Screenshots or screencast 

https://github.com/user-attachments/assets/796f40c1-9893-46ee-8f45-acab27018b13

### CODE REVIEW

**Comment by mirka** [comment]
I think we can move forward with this as long as we use the design token (#76221).

**Comment by hbhalodia** [comment]
Thanks @mirka, I would update the PR to use `--wpds-cursor-control`.

**Comment by hbhalodia** [comment]
> I think we can move forward with this as long as we use the design token (#76221).

@mirka, We have a rule applied here, `@wordpress/no-ds-tokens` as stated here - `/packages/eslint-plugin/docs/rules/no-ds-tokens.md` https://github.com/WordPress/gutenberg/blob/e374659fe59f4ceaa7f2031d8f78fb76d6ae7397/eslint.config.mjs#L622-L629

I do not think, that simply adding a token would work here, as it would fail linting. 

I am not sure how to move forward, do we need to set anything before or any other way to apply design token on such places?

Thanks

File: packages/components/src/menu/styles.ts [hunk 1]
```diff
@@ -114,6 +114,7 @@ export const Menu = styled( Ariakit.Menu )< Pick< ContextProps, 'variant' > >`
 
 const baseItem = css`
 	all: unset;
+	cursor: pointer;
```
Comment (mirka) [inline packages/components/src/menu/styles.ts:117]: Can we also remove the `cursor: not-allowed;` on L161 please.

**Review by mirka — COMMENTED** [review]
> I do not think, that simply adding a token would work here, as it would fail linting.

Oh right sorry, this needs to be migrated from Emotion to CSS modules first before using the tokens.

Let's move forward as is then. I'll tokenize it when doing the migration and re-theming.

This should be ready to merge once `cursor: not-allowed` is removed and a changelog is added 👍

File: packages/components/src/menu/styles.ts (hunk 1 above)
Comment (hbhalodia) [reply packages/components/src/menu/styles.ts:117]: This is done.

**Review by mirka — APPROVED** [review]
Looks good, thanks 🚀
