### PR TITLE
Social Links: Set the default protocol to 'https' if not specified

### LINKED ISSUE #21699: Social Icon URLs default with incorrect protocol
**Describe the bug**
If you simply enter a social icon url without a protocol, such as `twitter.com`, the buttons default to using HTTP. All social media platforms use HTTPS so it should default the URLs to HTTPS.

Editing the block in the Dashboard
screenshot_75

Viewing the page in the browser
screenshot_76

**To reproduce**
1. Insert Social Icons Block
2. Click on Twitter Icon and enter the url as `twitter.com`
3. Save the page and view in browser
4. Use the Browser dev tools to view that the url in the link is using the incorrect protocol.

**Expected behavior**
It should default all URLs to HTTPS if it's not specified

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: mascOS 10.15.4
 - Browser: Firefox 75.0

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Resolves #21699.
Alternative to #30100.

PR tries to use `https` as the default protocol if the URL doesn't appear to contain schema and it's not a relative link starting with //.

## Why?
If URL has no schema `esc_url`, prepend it with `http://`. All social media platforms use `https://`, so it makes sense to be the default fallback.

## How?
I've used slightly modified logic from `esc_url`. Schema is checked using `parse_url` and code only checks for relative links with `//` prefix.

## Testing Instructions
1. Open a Post or Page
2. Insert the example block (snippet below).
3. Save and view the post.
4. On the front-end inspect block elements and confirm that only WordPress social link has a default protocol.

## Snippet

```html
<!-- wp:social-links -->
<ul class="wp-block-social-links"><!-- wp:social-link {"url":"//twitter.com/WordPress","service":"twitter"} /-->

<!-- wp:social-link {"url":"profiles.wordpress.org/wordpress/","service":"wordpress"} /-->

<!-- wp:social-link {"url":"http://github.com/WordPress","service":"github"} /--></ul>
<!-- /wp:social-links -->
```

### CODE REVIEW

File: packages/block-library/src/social-link/index.php [hunk 1]
```diff
@@ -27,6 +27,14 @@ function render_block_core_social_link( $attributes, $content, $block ) {
 		return '';
 	}
 
+	/**
+	 * Prepend URL with https:// if it doesn't appear to contain a scheme
+	 * and it's not a relative link starting with //.
+	 */
+	if ( ! parse_url( $url, PHP_URL_SCHEME ) && ! str_starts_with( $url, '//' ) ) {
```
Comment (aristath) [inline packages/block-library/src/social-link/index.php:34]: Could this not be expressed as `if ( false === strpos( $url, '//' ) ) {` ? 🤔 
It would seem a bit simpler (and possibly even faster) that way...
If the string contains `//` we don't want to do anything because it either has the protocol defined, _or_ starts with `//`. So we basically only want to prepend `https://` if `//` is not contained in the string.

Comment (Mamaduka) [reply packages/block-library/src/social-link/index.php:34]: Sure, but not all schemas contain `//`. So I would rather trust PHP on schema validity.

**Review by aristath — APPROVED** [review]
LGTM 👍

**Comment by Mamaduka** [comment]
Thanks for the review, Ari ❤️
