### PR TITLE
Fix: ISO 8601 compliant year formatting in TimePicker

### LINKED ISSUE #75254: Post scheduling fails with 'Invalid Date' error
When attempting to schedule a post for a future date, the editor displays "Invalid Date" in the scheduling UI fields and scheduling fails with the error "Scheduling failed. Invalid parameter(s): date". This appears to consistently affect Block themes and intermittently affect Classic themes.

**Expected behavior**: User should be able to select a future date and successfully schedule the post.

**Current behavior**:

-   UI shows "Invalid Date" text in date/time input fields
-   Attempting to publish results in error: "Scheduling failed. Invalid parameter(s): date"
-   Browser console shows errors: `The specified value "Invalid date" cannot be parsed, or is out of range.` and `The specified value "NaN" cannot be parsed, or is out of range.`

## Step-by-step reproduction instructions

1. Create a new post or edit an existing draft
2. Open the sidebar settings panel
3. Under "Status & visibility", click on "Immediately" next to "Publish"
4. Select "Schedule"
5. In the date picker, **delete the values in both the Day and Year fields** (leave them empty)
6. Navigate to a future month using the month dropdown (e.g., change from February to March)
7. Observe: The date/time input fields now show "Invalid Date" and "NaN"
8. Attempt to publish the post
9. Observe: Error message appears: "Scheduling failed. Invalid parameter(s): date"

## Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/2b4dccaa-4540-47c3-8114-bc7e828da731

### Error in Browser Console

```
The specified value "Invalid date" cannot be parsed, or is out of range.
The specified value "NaN" cannot be parsed, or is out of range.
The specified value "Invalid date" cannot be parsed, or is out of range.
```

### Error when attempting to publish

```
Scheduling failed. Invalid parameter(s): date
```

### Root Cause

The issue occurs when date/time picker fields emit incomplete or invalid values (empty Day/Year fields) during user interaction. When the month dropdown is changed while other fields are empty, the TimePicker component immediately calls `onChange` with the partially complete date, which creates an Invalid Date object. This Invalid Date then propagates through the scheduling flow, resulting in:

1. Invalid Date objects being passed to `.toISOString()` calls, causing errors
2. Malformed date strings being sent to the REST API, resulting in "Invalid parameter(s): date" errors

The TimePicker component in `packages/components/src/date-time/` emits `onChange` immediately when any field changes, without validating that all required date components are present first.

## Environment info

**Affected environments**:

-   Block themes (consistently affected)
-   Classic themes (intermittently affected)

**Technical details**:

-   Browser: Multiple browsers affected (Chrome, Firefox, Safari)
-   WordPress version: Latest
-   Gutenberg version: Current trunk/latest plugin version
-   Device: All devices (desktop, mobile)

## Suggested Fix Approach

Two areas need attention:

1. **Date validation in post-schedule component**: The `post-schedule/index.js` component should validate that `postDate` is valid before creating Date objects and calling `.toISOString()`. Use `isNaN(date.getTime())` to check for Invalid Date objects (truthy checks are insufficient as Invalid Date objects are truthy).

2. **TimePicker validation**: The TimePicker component should either:
    - Defer calling `onChange` until all required date fields are complete and valid
    - Or validate that the constructed date is valid before emitting it
    - Consider adding validation to ensure impossible dates (like Feb 31) are handled gracefully when users change individual fields

## Checklist

-   [x] I have searched existing issues in the repo
-   [x] I have tested with all plugins deactivated except Gutenberg
-   [x] Theme type tested: Block - consistently reproduces
-   [x] Theme type tested: Classic - intermittently reproduces

### PR DESCRIPTION
**Pull request by getdave**
## What?

Fixes date parsing for years below 1000 by implementing ISO 8601 compliant year formatting with zero-padding.

**This is a sub-PR extracted from #75285** to allow the core fix to be merged independently before the broader enhancements.

## Why?

Fixes #75254

`setInConfiguredTimezone()` was creating non-ISO-8601-compliant date strings for years below 1000:
- Year 999 → `"999-10-18T11:00:00"` (only 3 digits)
- Year 1 → `"1-10-18T11:00:00"` (only 1 digit)

ISO 8601 requires a minimum of 4 digits for the year. When `getDate()` calls `momentLib.tz()` without an explicit format, it fails to parse these strings, resulting in `Invalid Date` errors.

## How?

**Single line fix in `packages/components/src/date-time/utils.ts`:**

```typescript
const year = String(values.year).padStart(4, '0');
```

This ensures all date strings are ISO 8601 compliant:
- `"0999-10-18T11:00:00"` → Valid, year 999
- `"0001-10-18T11:00:00"` → Valid, year 1

## Testing Instructions

```bash
# Run all date-time tests
npm run test:unit -- packages/components/src/date-time/

# Should pass 114 tests
```

All tests pass including the new test for zero-padded output.

## Notes

- This is a minimal, focused fix - only changes internal date string formatting
- No API changes
- No changes to UI behavior or validation
- Once merged, PR #75285 will rebase on this and add:
  - Removal of MIN_SUPPORTED_YEAR guards
  - Change minYear defaults from 1000 to 1
  - Comprehensive test suite
  - Documentation updates

### CODE REVIEW

File: packages/components/src/date-time/time/test/index.tsx [hunk 1]
```diff
@@ -591,4 +591,35 @@ describe( 'TimePicker', () => {
...
+	describe( 'ISO 8601 compliance', () => {
+		it( 'should handle years below 1000 with zero-padded output', async () => {
+			const user = userEvent.setup();
+			const onChangeSpy = jest.fn();
+
+			render(
+				<TimePicker
+					currentTime="0999-10-18T11:00:00"
+					onChange={ onChangeSpy }
+					minYear={ 1 }
```
Comment (tyxla) [inline packages/components/src/date-time/time/test/index.tsx]: Unnecessary artifact of #75285
```suggestion
```

**Review by tyxla — COMMENTED** [review]
One thing I'm noticing while testing is that this works well with 3-digit years:

Image

but not with 1-digit or 2-digit ones:

Image

Image

(see how the year is respectively 1950 or 1905 instead of 0050 / 0005)

File: packages/components/src/date-time/time/test/index.tsx [hunk 2]
```diff
@@ -591,4 +591,35 @@ describe( 'TimePicker', () => {
...
+			// Verify onChange emits zero-padded ISO 8601 format
+			await user.clear( yearInput );
+			await user.type( yearInput, '500' );
+			await user.keyboard( '{Tab}' );
+
+			// With zero-padding, this should work without errors
+			if ( onChangeSpy.mock.calls.length > 0 ) {
+				const lastCall = onChangeSpy.mock.calls[ onChangeSpy.mock.calls.length - 1 ];
+				expect( lastCall[ 0 ] ).toMatch( /^0500-/ );
+				expect( lastCall[ 0 ] ).not.toContain( 'NaN' );
```
Comment (tyxla) [inline packages/components/src/date-time/time/test/index.tsx]: Sorry for being a nuisance, but please consider [this comment](https://github.com/WordPress/gutenberg/pull/75285#discussion_r2774301290):

> In each of the new tests, can we also include an assertion that checks the value of the input we're testing?

Comment (getdave) [reply packages/components/src/date-time/time/test/index.tsx]: No it's fine. It's just AI refactoring. I need to fix all this before marking ready for review. Thanks for flagging early though!

**Review by tyxla — APPROVED** [review]
This is looking good as a fix of the original issue 👍 

Let's land it.

And [this one](https://github.com/WordPress/gutenberg/pull/75343#pullrequestreview-3772867877) is yet another follow-up to fix afterwards.

Thanks a bunch @getdave 🙌
