### PR TITLE
Fix responsive embeds on widget screen

### LINKED ISSUE #26104: Can't preview video embeds in the editor
In the new widgets editor one cannot add embed blocks and then preview them.

Steps to reproduce:

1 have the Gutenberg plugin installed
2 go to the new widgets editor
3 add an YouTube block
4 paste an YouTube URL
5 preview the embed using the preview button in the block's toolbar
6 notice bug: nothings shows up except a caption placeholder
7 notice bug: the embed does not render on the front end either, for YouTube all I got was the link.

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #26104

WordPress keeps some internal state to determine whether the current screen is a block editor. Setting this to true has the side effect of enabling responsive embeds in the editor, solving the issues seen in #26104:
https://github.com/WordPress/wordpress-develop/blob/master/src/wp-admin/admin-header.php#L192-L199

## How has this been tested?
1. Paste a youtube link into a widget area on the widget screen
2. The video should eventually appear and be playable within the editor

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by talldan** [comment]
I've left a note on https://github.com/WordPress/wordpress-develop/pull/603 that this will have to be implemented in core too.

File: lib/widgets-page.php [hunk 1]
```diff
@@ -41,6 +41,16 @@ function gutenberg_widgets_init( $hook ) {
...
 
+	$current_screen = get_current_screen();
+	/**
+	 * Make the WP Screen object aware that this is a block editor page.
+	 * Since custom blocks check whether the screen is_block_editor,
+	 * this is required for custom blocks to be loaded and for responsive embeds
+	 * to work.
+	 * See wp_enqueue_registered_block_scripts_and_styles in wp-includes/script-loader.php
+	 */
+	$current_screen->is_block_editor( true );
```
Comment (talldan) [inline lib/widgets-page.php:52]: I copied most of the comment from the site editor:
https://github.com/WordPress/gutenberg/blob/277506eadc6ef77354c90f7984d65b243cb7c7ca/lib/edit-site-page.php#L90-L102

Two questions:
1. Is there a reason the site editor uses `global $current_screen` instead of `get_current_screen()`?
2. The comment implies this duplicates what we've implemented here, can this code now be removed? - https://github.com/WordPress/gutenberg/blob/277506eadc6ef77354c90f7984d65b243cb7c7ca/lib/widgets-page.php#L135-L143

**Comment by talldan** [comment]
Just noting that https://core.trac.wordpress.org/ticket/51566 and https://github.com/WordPress/gutenberg/issues/26180 are tracking the issue of actually displaying the embed in the frontend.

**Review by draganescu — DISMISSED** [review]
Tested this and works as described. It's not clear to me if we need to act on this [comment](https://github.com/WordPress/gutenberg/pull/26263/files#r507633766).

**Review by kevin940726 — DISMISSED** [review]
Tested and LGTM 👍

File: lib/widgets-page.php (hunk 1 above)
Comment (noisysocks) [reply lib/widgets-page.php:52]: 1. The only difference between `get_current_screen()` and `global $current_screen` is that the former will instantiate `WP_Screen` if it hasn't already been instantiated. What you did here looks good to me.

2. Yes, we should be able to remove all of that. It worked when I tried it in https://github.com/WordPress/wordpress-develop/pull/603 🙂

**Review by noisysocks — DISMISSED** [review]
Remove the now redundant `should_load_block_editor_scripts_and_styles` filter that we're adding in `lib/widegts-page.php` and then we'll be cooking with gas 😎

**Comment by talldan** [comment]
I've changed this PR to use the `admin_body_class` filter for now as per the discussion here - https://github.com/WordPress/wordpress-develop/pull/603#issuecomment-716872165 (cc @noisysocks)

**Review by draganescu — APPROVED** [review]
Tested again and it works!
