### PR TITLE
Avoid errors when a fontSize preset is not available

### LINKED ISSUE #65774: Javascript error when resetting Font Size Presets
### Description

Hello all!

I've got a javascript error and the editor crashed when doing the following:

### Step-by-step reproduction instructions

1. opening global styles
2. typography
3. font size presets
4. add a new individual font size preset
5. click on the new individual preset
6. next to the revisions button click on the 3 dots
7. click reset styles

### Screenshots, screen recording, code snippet

TypeError: f is undefined
    Kh https://hostingtools.at/wordpress/wp-includes/js/dist/edit-site.min.js?ver=5a21c7ca87b2d5588902:11
    ht https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
    vr https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
    Qs https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
    wl https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
    bl https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
    yl https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
    il https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
    fl https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
    Nn https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
    ul https://hostingtools.at/wordpress/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:10
[react-dom.min.js:10:53523]

https://github.com/user-attachments/assets/47ed221e-c606-4f2e-b1d9-c7a13e36ddf0

### Environment info

Firefox,
completely fresh and unmodified WordPress 6.7-beta1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
Avoid errors when a fontSize preset is not available

## Why?
Fixes: https://github.com/WordPress/gutenberg/issues/65774

## How?
- use ? optional chain operator when a property may be undefined.
- Navigate to typograpjy

## Testing Instructions
1. Activate TT4
2. Create a custom preset.
3. Reset global styles
Expected result: you should be directed to the typography -> font size presets screen.

### CODE REVIEW

**Comment by t-hamano** [comment]
@ciampo @tyxla The issue this PR is trying to fix is ​​caused by the font size preset logic itself, and is also present in the WP 6.7 branch. Therefore, I would like to review and merge this PR before #65765 and #65790.

**Review by t-hamano — APPROVED** [review]
LGTM!


https://github.com/user-attachments/assets/9444c7e5-45c1-4039-a415-7461f0c808ef

The E2E test failure should be resolved once #65793 is merged.

File: packages/edit-site/src/components/global-styles/font-sizes/font-size.js [hunk 1]
```diff
@@ -125,6 +121,18 @@ function FontSize() {
 		setIsRenameDialogOpen( ! isRenameDialogOpen );
 	};
 
+	// Navigate to the font sizes list if the font size is not available.
+	useEffect( () => {
+		if ( ! fontSize ) {
+			goTo( '/typography/font-sizes/' );
```
Comment (ciampo) [inline packages/edit-site/src/components/global-styles/font-sizes/font-size.js]: could this be `goBack()` instead?

Comment (matiasbenedetto) [reply packages/edit-site/src/components/global-styles/font-sizes/font-size.js]: goBack doesn't work as expected here because this runs more than once, and it ends up going back more than one screen

Comment (ciampo) [reply packages/edit-site/src/components/global-styles/font-sizes/font-size.js]: Got it. Ideally we'd fix it so that it runs only once (since calling `goTo` many times is also not great), but I understand the urgency of the fix.

Could we at least specify the `isBack` option?

```suggestion
			goTo( '/typography/font-sizes/', { isBack: true } );
```

Comment (ramonjd) [reply packages/edit-site/src/components/global-styles/font-sizes/font-size.js]: Sorry I just saw this before getting another PR up. I can close mine, but do we need a useEffect here?

What about just returning early if the navigator params are not available?

https://github.com/WordPress/gutenberg/pull/65811/files#diff-88536b41b2c498208a524ef21e82ff4796a9bd768fafa50c82ef0bbe79d67f21R49


```diff
diff --git a/packages/edit-site/src/components/global-styles/font-sizes/font-size.js b/packages/edit-site/src/components/global-styles/font-sizes/font-size.js
index 80b1ea55c405b..1ce4c97b91d98 100644
--- a/packages/edit-site/src/components/global-styles/font-sizes/font-size.js
+++ b/packages/edit-site/src/components/global-styles/font-sizes/font-size.js
@@ -46,6 +46,10 @@ function FontSize() {
 
 	const [ globalFluid ] = useGlobalSetting( 'typography.fluid' );
 
+	if ( ! origin || ! slug ) {
+		return;
+	}
+
 	// Get the font sizes from the origin, default to empty array.
 	const sizes = fontSizes[ origin ] ?? [];
 ```

Comment (matiasbenedetto) [reply packages/edit-site/src/components/global-styles/font-sizes/font-size.js]: Yes it's needed because the useEffect handles the navigation when the global styles are reset. In that case returning null will results in a blank screen in that sidebar.

Comment (t-hamano) [reply packages/edit-site/src/components/global-styles/font-sizes/font-size.js]: @matiasbenedetto is right. However, the code @ramonjd proposed is necessary to solve a different problem, and that problem also occurs in the shadow panel.

I plan to merge #65765 after this PR is shipped.

Comment (ramonjd) [reply packages/edit-site/src/components/global-styles/font-sizes/font-size.js]: Thanks for clarifying folks.
