### PR TITLE
fix issue 24539, show external icon on help button

### LINKED ISSUE #24539: Help link in the editor 'more' menu doesn't indicate that it opens in a new tab
**Describe the bug**
The Help link in the editor more menu doesn't indicate that it opens in a new tab.

Links in the editor that open in a new tab usually have some visually hidden text for screen readers that says '(opens in a new tab)' so this one is inconsistent.

E.g.
- The preview button
- The Embed block's placeholder
- The View Post in the permalink panel

They either use the `ExternalLink` component for this or the `VisuallyHidden` component.

A second inconsistency is that the 'Manage all reusable blocks' link in the same menu doesn't open in a new tab.

**To reproduce**
1. Open the editor more menu (either with a screenreader, or use dev tools to inspect the markup)
2. Notice the help link doesn't indicate it opens in a new tab, but selecting it opens a new tab
3. Notice the Manage Reusable Blocks link doesn't open in a new tab

**Expected behavior**
- Links in the same dropdown menu should probably have the same behaviour in regards to opening a new tab.
- The links should indicate whether they open in a new tab or not.

**Screenshots**
Screenshot 2020-08-13 at 4 43 33 pm

**Editor version (please complete the following information):**
- 8.7

### PR DESCRIPTION
**Pull request by leutrimhusaj**
## Description
I have added the external icon (`icon={ external }`) to the Help MenuItem for edit-post and edit-site plugin. Adding as an svg was important because when i referenced it only as a string (`icon="external"`) it creates a Dashicon, which is 20x20 pixel big, it would break the padding of the text. The default icon size is 24x24 pixel and fits perfect into the more option menu.

## How has this been tested?
Open gutenberg editor for a page.
Open the "more option" menu and check/click the help button.

## Screenshots
help-with-external-icon

## Types of changes
Bug fix for #24539 with non-breaking change

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows the accessibility standards.
- [x] My code has proper inline documentation.
- [x] I've included developer documentation if appropriate.
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jasmussen** [comment]
Thank you for the PR! This tests nicely, the code is clean and simple, and it solves the issue. The placement on the left feels a little off to me, though, and it might feel better if the icon immediately followed the link, inline in the text. We might even discuss making `external` a prop on menu items, so this gets simplified. 

However because of the simplicity of this PR, and the issue it solves, I'm not opposed to approving this as an interim solution. I also still have a PR in progress (#23552#issuecomment-656049689) which would refactor some of this stuff, so it _will_ be revisited. 

I'd love a quick sanity check, @shaunandrews or @MichaelArestad in case you have them?

Thanks again!

**Comment by MichaelArestad** [comment]
@jasmussen It works well enough until it gets revisited. I believe I share your concern over the location of the icon. Right now it draws extra intention due to the way it aligns with other items on the list. If there's anything I can do to help your PR along, let me know.

File: packages/edit-post/src/plugins/index.js [hunk 1]
```diff
@@ -38,6 +39,7 @@ registerPlugin( 'edit-post', {
 							<CopyContentMenuItem />
 							<MenuItem
 								role="menuitem"
+								icon={ external }
```
Comment (talldan) [inline packages/edit-post/src/plugins/index.js:42]: Thanks so much for picking this up 👍 

In addition to the icon, the other thing that's usually present on these external links is some visually hidden text for screenreader users.

I think you should be able to follow how the External Link component does that for implementing it on these two MenuItems:
https://github.com/WordPress/gutenberg/blob/master/packages/components/src/external-link/index.js#L38-L43

Alternatively, as @jasmussen proposes a prop for the MenuItem component could be an option so that it adds the icon and the visually hidden text implicitly.

Comment (leutrimhusaj) [reply packages/edit-post/src/plugins/index.js:42]: Thanks for the hint, i didn't knew about that. I have added the visually hidden text like in the example, works well.

Comment (jasmussen) [reply packages/edit-post/src/plugins/index.js:42]: I'll refresh my PRs and rebase them off whatever lands here. In the mean time, this PR should not be held up. 

This is what the preview dropdown looks like:

Screenshot 2020-08-24 at 09 50 02

The same feedback applies to that, it looks a little weird on the left. But because this PR looks the same, I say let's move this forward. 👍 👍 from a design POV and thank you for the PR! If this gets a quick sanity check, we should land it.

**Comment by shaunandrews** [comment]
I find it a little weird, both visually (it feels unbalanced) and conceptually (the left-side space is usually reserved for the checkmark). I think it'd be better placed inline, to the right of the text, but I don't have a strong preference.

I think an ideal solution is to _not_ open an external link directly from the menu. Instead, I'd expect a help modal to appear within the editor — and from that modal, I'd find general guidance along with links to external resources.

**Comment by jasmussen** [comment]
I have refreshed #23552, which now shows at least the preview icon on the right:

Screenshot 2020-08-28 at 11 33 51

If that PR lands first, rebasing this one should address the most pressing feedback about the icon positioning. That does not preclude a further PR that changes that link to open a modal dialog instead — totally fair feedback — but until that, this one would be a nice little improvement.

**Comment by shaunandrews** [comment]
👍

**Comment by leutrimhusaj** [comment]
I have rebased the PR and fixed the conflicts. This PR looks like this now.

help-with-external-icon-right

@jasmussen @talldan Is there anything else to do for this minimal PR?

The other feature should be done in other PR in my opinion.

**Review by jasmussen — APPROVED** [review]
This seems like a good small win. Thanks for the PR!

Before:

Screenshot 2020-09-08 at 11 11 08

After:

Screenshot 2020-09-08 at 11 15 23

Markup:

Screenshot 2020-09-08 at 11 15 33
