### PR TITLE
Section Styles: Resolve ref values in variations data

### LINKED ISSUE #63159: The `ref` values doesn't work on `theme.json` block style variations since Gutenberg 18.7.0
### Description

After updating to Gutenberg 18.7.0 or Gutenberg 18.7.1, the `ref` values feature doesn't work on block style variations on `theme.json`.  This works on the previous version Gutenberg 18.6.1.

** This issue also happens on WordPress 6.6 RC versions (without Gutenberg installed)

### Step-by-step reproduction instructions

Copy this snippet to the `theme.json`.
We define the button element styling.
The normal `core/button` styling is inherited from the button element using `ref` values.
And then we want to change the outline button text color to use the button element's background color.

```
{
    "styles": {
        "elements": {
            "button": {
                "border": {
                    "color": "transparent",
                    "radius": "0.25em",
                    "style": "solid",
                    "width": "1px"
                },
                "color": {
                    "background": "var(--wp--preset--color--accent)",
                    "text": "var(--wp--preset--color--base)"
                },
                "spacing": {
                    "padding": {
                        "bottom": "0.5em",
                        "left": "1.25em",
                        "right": "1.25em",
                        "top": "0.5em"
                    }
                }
            }
        },
        "blocks": {
            "core/button": {
                "border": {
                    "color": { "ref": "styles.elements.button.border.color" },
                    "radius": { "ref": "styles.elements.button.border.radius" },
                    "style": { "ref": "styles.elements.button.border.style" },
                    "width": { "ref": "styles.elements.button.border.width" }
                },
                "color": {
                    "background": { "ref": "styles.elements.button.color.background" },
                    "text": { "ref": "styles.elements.button.color.text" }
                },
                "spacing": {
                    "padding": {
                        "bottom": { "ref": "styles.elements.button.spacing.padding.bottom" },
                        "left": { "ref": "styles.elements.button.spacing.padding.left" },
                        "right": { "ref": "styles.elements.button.spacing.padding.right" },
                        "top": { "ref": "styles.elements.button.spacing.padding.top" }
                    }
                },
                "variations": {
                    "outline": {
                        "border": {
                            "color": "currentColor",
                            "width": { "ref": "styles.elements.button.border.width" }
                        },
                        "color": {
                            "text": { "ref": "styles.elements.button.color.background" }
                        },
                        "spacing": {
                            "padding": {
                                "bottom": { "ref": "styles.elements.button.spacing.padding.bottom" },
                                "left": { "ref": "styles.elements.button.spacing.padding.left" },
                                "right": { "ref": "styles.elements.button.spacing.padding.right" },
                                "top": { "ref": "styles.elements.button.spacing.padding.top" },
                            }
                        }
                    }
                }
            }
        }
    }
}
```

### Screenshots, screen recording, code snippet

Expected result:

image

Result of Gutenberg 18.7, the outline button has the same text color as the normal button. This means, the `ref` value on the `outline` style variation doesn't work.

image

### Environment info

WordPress 6.5.5 + Gutenberg 18.7.1
or
WordPress 6.6 RC

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Fixes: https://github.com/WordPress/gutenberg/issues/63159

## What?

Retrieve reference values when generating styles for block style variations.

## Why?

Without resolving `ref` values some styles may not be generated.

## How?

When retrieving variation data, to generate styles from, also retrieve any referenced values.

## Testing Instructions

1. Add some ref values for block style variations to your theme.json e.g. update TT4 with the sections from the theme.json snippet below
2. Load the site editor and edit the default home page
3. Confirm that outline buttons are displayed and have the correct referenced style values
4. Save and ensure the same on the frontend

<details>
<summary>Example theme.json snippet</summary>

```json
{
    "styles": {
        "elements": {
            "button": {
                "border": {
                    "color": "transparent",
                    "radius": "0.25em",
                    "style": "solid",
                    "width": "1px"
                },
                "color": {
                    "background": "var(--wp--preset--color--accent)",
                    "text": "var(--wp--preset--color--base)"
                },
                "spacing": {
                    "padding": {
                        "bottom": "0.5em",
                        "left": "1.25em",
                        "right": "1.25em",
                        "top": "0.5em"
                    }
                }
            }
        },
        "blocks": {
            "core/button": {
                "border": {
                    "color": { "ref": "styles.elements.button.border.color" },
                    "radius": { "ref": "styles.elements.button.border.radius" },
                    "style": { "ref": "styles.elements.button.border.style" },
                    "width": { "ref": "styles.elements.button.border.width" }
                },
                "color": {
                    "background": { "ref": "styles.elements.button.color.background" },
                    "text": { "ref": "styles.elements.button.color.text" }
                },
                "spacing": {
                    "padding": {
                        "bottom": { "ref": "styles.elements.button.spacing.padding.bottom" },
                        "left": { "ref": "styles.elements.button.spacing.padding.left" },
                        "right": { "ref": "styles.elements.button.spacing.padding.right" },
                        "top": { "ref": "styles.elements.button.spacing.padding.top" }
                    }
                },
                "variations": {
                    "outline": {
                        "border": {
                            "color": "currentColor",
                            "width": { "ref": "styles.elements.button.border.width" }
                        },
                        "color": {
                            "text": { "ref": "styles.elements.button.color.background" }
                        },
                        "spacing": {
                            "padding": {
                                "bottom": { "ref": "styles.elements.button.spacing.padding.bottom" },
                                "left": { "ref": "styles.elements.button.spacing.padding.left" },
                                "right": { "ref": "styles.elements.button.spacing.padding.right" },
                                "top": { "ref": "styles.elements.button.spacing.padding.top" },
                            }
                        }
                    }
                }
            }
        }
    }
}
```

</details>

## Screenshots or screencast 

| Before | After |
|---|---|
| Screenshot 2024-07-05 at 6 21 01 PM | Screenshot 2024-07-05 at 6 20 41 PM |

### CODE REVIEW

File: lib/block-supports/block-style-variations.php [hunk 1]
```diff
@@ -79,6 +79,38 @@ function gutenberg_render_block_style_variation_support_styles( $parsed_block )
 		return $parsed_block;
 	}
 
+	// Recursively resolve any ref values with the appropriate value within the
+	// theme_json data.
+	$replace_refs = function ( &$variation_data ) use( &$replace_refs, $theme_json ) {
```
Comment (aaronrobertshaw) [inline lib/block-supports/block-style-variations.php]: After WP6.6 I'd like to try and clean up some of this block support's code. To that end, I've tried to avoid introducing another global function that would then need to be deprecated.

File: packages/block-editor/src/hooks/block-style-variation.js [hunk 2]
```diff
@@ -194,9 +256,14 @@ function useBlockStyleVariation( name, variation, clientId ) {
...
 
 	return useMemo( () => {
-		const styles = mergedConfig?.styles ?? globalStyles;
-		const variationStyles =
-			styles?.blocks?.[ name ]?.variations?.[ variation ];
+		const variationStyles = getVariationStylesWithRefValues(
+			{
+				settings: mergedConfig?.settings ?? globalSettings,
+				styles: mergedConfig?.styles ?? globalStyles,
+			},
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/hooks/block-style-variation.js:273]: Creating a "complete" theme.json object seemed the easiest approach to reason about when `ref` values could target any value within `settings` or `styles` etc.

File: lib/block-supports/block-style-variations.php [hunk 3]
```diff
@@ -79,6 +115,10 @@ function gutenberg_render_block_style_variation_support_styles( $parsed_block )
 		return $parsed_block;
 	}
 
+	// Recursively resolve any ref values with the appropriate value within the
+	// theme_json data.
+	gutenberg_resolve_block_style_variation_ref_values( $variation_data, $theme_json );
```
Comment (ramonjd) [inline lib/block-supports/block-style-variations.php:120]: Just checking so I understand the approach: the refs in `$theme_json` have already been resolved via [get_property_value](https://github.com/WordPress/gutenberg/blob/ba1c881a9615a9e6fdfad6b52c761c59a0a77733/lib/class-wp-theme-json-gutenberg.php#L2439-L2439), and you're using the "ref" values in the variation to fetch the resolved values from `$theme_json`?

**Review by andrewserong — APPROVED** [review]
This is testing nicely for me in the post and site editors, and on the site frontend. When I update the element's background color to another explicit color, e.g. `red`, the referenced values are also updated for variations, and the output is correct:

image

Thanks for all the inline comments and clear tests!

LGTM

**Review by ramonjd — APPROVED** [review]
This is working as advertised for me. I can't seem to break it and the refs are resolved in theme.json and the variations as I'd expect.

Before, the variation refs were not being output at all in the styles, after they're resolved correctly

Here is my test JSON for the record

<details>

<summary>theme.json</summary>

```json

{
	"$schema": "../../schemas/json/theme.json",
	"version": 3,
	"settings": {
		"appearanceTools": true,
		"layout": {
			"contentSize": "840px",
			"wideSize": "1100px"
		},
		"color": {
			"palette": [
				{
					"name": "Accent",
					"slug": "accent",
					"color": "#0073aa"
				},
				{
					"name": "Base",
					"slug": "base",
					"color": "#32373c"
				}
			]
		}
	},
	"styles": {
		"color": {
			"background": "var(--wp--preset--color--accent)"
		},
		"elements": {
			"button": {
				"border": {
					"color": "transparent",
					"radius": "0.25em",
					"style": "solid",
					"width": "1px"
				},
				"color": {
					"background": { "ref": "styles.color.background" },
					"text": "var(--wp--preset--color--base)"
				},
				"spacing": {
					"padding": {
						"bottom": "0.1111em",
						"left": "1.25em",
						"right": "1.25em",
						"top": "0.32em"
					}
				}
			}
		},
		"blocks": {
			"core/button": {
				"border": {
					"color": { "ref": "styles.elements.button.border.color" },
					"radius": { "ref": "styles.elements.button.border.radius" },
					"style": { "ref": "styles.elements.button.border.style" },
					"width": { "ref": "styles.elements.button.border.width" }
				},
				"color": {
					"background": { "ref": "styles.elements.button.color.background" },
					"text": { "ref": "styles.elements.button.color.text" }
				},
				"spacing": {
					"padding": {
						"bottom": { "ref": "styles.elements.button.spacing.padding.bottom" },
						"left": { "ref": "styles.elements.button.spacing.padding.left" },
						"right": { "ref": "styles.elements.button.spacing.padding.right" },
						"top": { "ref": "styles.elements.button.spacing.padding.top" }
					}
				},
				"variations": {
					"outline": {
						"border": {
							"color": "currentColor",
							"width": { "ref": "styles.elements.button.border.width" }
						},
						"color": {
							"background": { "ref": "styles.elements.button.color.text" },
							"text": { "ref": "styles.color.background" }
						},
						"spacing": {
							"padding": {
								"bottom": { "ref": "styles.elements.button.spacing.padding.bottom" },
								"left": { "ref": "styles.elements.button.spacing.padding.left" },
								"right": { "ref": "styles.elements.button.spacing.padding.right" },
								"top": { "ref": "styles.elements.button.spacing.padding.top" }
							}
						}
					}
				}
			}
		}
	}
}


```

</details>

File: lib/block-supports/block-style-variations.php (hunk 3 above)
Comment (aaronrobertshaw) [reply lib/block-supports/block-style-variations.php:120]: > the refs in $theme_json have already been resolved via [get_property_value](https://github.com/WordPress/gutenberg/blob/ba1c881a9615a9e6fdfad6b52c761c59a0a77733/lib/class-wp-theme-json-gutenberg.php#L2439-L2439)

This works a little differently as `get_property_value` is called when computing theme.json styles. When processing a block style variation, it's a partial set of the overall theme.json data that doesn't always contain the values that might have been referenced. 

So the solution here resolves those values before generating the variation's styles.

Comment (ramonjd) [reply lib/block-supports/block-style-variations.php:120]: Thanks, it's been a while since I touched refs. All good 🚀
