### PR TITLE
DataForm: fix issue with array fields in layout panel

### LINKED ISSUE #73342: [DataForm] - Layout panel `tags` field (token field) misbehave when rendered in the modal
### Description

1. DataForm Layout Panel (Modal), Tags (token form field) misbehave and is not working as expected.

### Step-by-step reproduction instructions

1. Go to - https://wordpress.github.io/gutenberg/?path=/story/dataviews-dataform--layout-panel&args=openAs:modal
2. Click on Tags to change.
3. Try to remove the tag, You will see it is not being removed.
4. Now add more tag, the count of how many time you tried to remove tag will be added.
5. This misbehave does not occur in `dropdown` open as option.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/1cd4d271-796d-4385-b08b-55a2c14bfe21

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by hbhalodia**
## What?

Closes https://github.com/WordPress/gutenberg/issues/73342

## Why?

- https://github.com/WordPress/gutenberg/issues/73342

## How?

- Update to use spread operator instead of deepMerge to fix the issue.

## Testing Instructions

1. Go to - https://wordpress.github.io/gutenberg/?path=/story/dataviews-dataform--layout-panel&args=openAs:modal
2. Click on Tags to change.
3. Try to remove/add the tags, it is working as expected.
4. Check other fields as well and check if we have updated data.

### Testing Instructions for Keyboard

- Nil

## Before
https://github.com/user-attachments/assets/1cd4d271-796d-4385-b08b-55a2c14bfe21

## After 
https://github.com/user-attachments/assets/76aa6d47-a8bd-4faf-b28d-67a33ebed36a

### CODE REVIEW

File: packages/dataviews/src/dataform-layouts/panel/modal.tsx [hunk 1]
```diff
@@ -72,7 +67,7 @@ function ModalContent< Item >( {
 	};
 
 	const handleOnChange = ( newValue: Partial< Item > ) => {
-		setChanges( ( prev ) => deepMerge( prev, newValue ) );
+		setChanges( ( prev ) => ( { ...prev, ...newValue } ) );
```
Comment (ntsekouras) [inline packages/dataviews/src/dataform-layouts/panel/modal.tsx]: I'm not sure why we were using `deepMerge` in the first place but I might be missing context. @oandregal, @straku any insights?

Comment (oandregal) [reply packages/dataviews/src/dataform-layouts/panel/modal.tsx]: That's there for nested data. Here's a use case that breaks with these changes:

Before ([current storybook](https://wordpress.github.io/gutenberg/?path=/story/dataviews-dataform--data-adapter)):

https://github.com/user-attachments/assets/dcccb7b6-3c72-40d7-a7a0-969a5022f16a

After (with these changes): note how all other fields are cleared

https://github.com/user-attachments/assets/94b4f926-b7ac-4864-918c-f0394a24ac67

Comment (ntsekouras) [reply packages/dataviews/src/dataform-layouts/panel/modal.tsx]: Does this mean though that the `deepMerge` usage is correct? Shouldn't a nested field handle that on `setValue` or something (have a way to control how the changes merge in parent props)? Current implementation is buggy (the issue for tokens) and feels like opinionated handling of changes.

Comment (oandregal) [reply packages/dataviews/src/dataform-layouts/panel/modal.tsx]: Take the following example, add a new value to a field type array:

https://github.com/user-attachments/assets/43cfb57e-04d3-4248-8bdc-05b1f70620a9

What do you expect to receive as values in the `onChange` callback of DataForm?

For any other control (single items, not arrays) it streams the _changed_ value, so I expected `Book reviews`, but the array control streams all (existing and new). That's the core issue we need to figure out. I see two ways to go about this:

1. make the array field type only stream the changes ("[ 'book reviews' ] ")
2. make the array field type stream the whole list of values ("[ 'photography' , 'book reviews']")

Whatever we do here, we should do for objects as well (when we support them).

If we go with 1, for nested scenarios, `deepMerge` would work as it is (for both arrays and objects).  If we go with 2 (current behavior), we need to tweak the merging algorithm to do the following: for arrays (and objects), do not merge, just take the incoming data.

Comment (ntsekouras) [reply packages/dataviews/src/dataform-layouts/panel/modal.tsx]: In general your `option 1` can't work seamlessly because we can remove existing values, so we'd need to indicate that somehow without passing the whole new value.

Not sure how we can  solve this (I'll have to familiarize myself more with the code), but it seems we can't have opinionated merging. I've mentioned a few times if `setValue` can help here, but in general for me it feels it should be the `field` that handles the merging somehow.

Comment (hbhalodia) [reply packages/dataviews/src/dataform-layouts/panel/modal.tsx]: Hi @ntsekouras @oandregal, We can do something like this?

```diff
- setChanges( ( prev ) => ( { ...prev, ...newValue } ) );
+ setChanges( ( prev ) => deepMerge( prev, newValue, {
+     arrayMerge: ( target, source ) => source,
+ } ) );
```
This is resolving both the cases, token field as well as the data adapter nested issue. So bascially instead of merging we are replacing the same.

Just tweak merging algortihm to use the incoming one as mentioned here - https://github.com/WordPress/gutenberg/pull/73344#discussion_r2534178933

## After the above change

https://github.com/user-attachments/assets/0a9708d3-0d7b-4f51-9490-b824132449d0

Ps: Used the help of `copilot` 😝 🙈

Comment (oandregal) [reply packages/dataviews/src/dataform-layouts/panel/modal.tsx]: @hbhalodia could you also update the existing story ([see](https://github.com/WordPress/gutenberg/blob/265a1597ed779e99055ac273e3a4b9c8ed3c6271/packages/dataviews/src/stories/dataform.story.tsx#L2203)) to 1) use the same and 2) add an example of a `array` field type that is also nested.

@straku would you have thoughts on this one?

Comment (hbhalodia) [reply packages/dataviews/src/dataform-layouts/panel/modal.tsx]: Hi @oandregal, If I am correct, are you saying need to update something like below?

```diff
diff --git a/packages/dataviews/src/stories/dataform.story.tsx b/packages/dataviews/src/stories/dataform.story.tsx
index 58b7226abc..ebafae27ed 100644
--- a/packages/dataviews/src/stories/dataform.story.tsx
+++ b/packages/dataviews/src/stories/dataform.story.tsx
@@ -2144,6 +2144,20 @@ const DataAdapterComponent = () => {
 			label: 'User Email',
 			type: 'email',
 		},
+		{
+			id: 'user.profile.tags',
+			label: 'User Tags',
+			type: 'array',
+			placeholder: 'Enter comma-separated tags',
+			description: 'Add tags separated by commas (e.g., "tag1, tag2, tag3")',
+			elements: [
+				{ value: 'astronomy', label: 'Astronomy' },
+				{ value: 'book-review', label: 'Book review' },
+				{ value: 'event', label: 'Event' },
+				{ value: 'photography', label: 'Photography' },
+				{ value: 'travel', label: 'Travel' },
+			],
+		},
 		// Example of adapting a data value to a control value
 		// by providing getValue/setValue methods.
 		{
@@ -2200,7 +2214,11 @@ const DataAdapterComponent = () => {
 		// Edits will respect the shape of the data
 		// because fields provide the proper information
 		// (via field.id or via field.setValue).
-		setData( ( prev ) => deepMerge( prev, edits ) );
+		setData( ( prev ) =>
+			deepMerge( prev, edits, {
+				arrayMerge: ( target, source ) => source,
+			} )
+		);
 	}, [] );
 
 	return (
@@ -2241,6 +2259,7 @@ const DataAdapterComponent = () => {
 							children: [
 								'user.profile.name',
 								'user.profile.email',
+								'user.profile.tags',
 							],
 						},
 					],

```

If not, Can you provide a example with type array which is nested type, that we can use here?

Comment (straku) [reply packages/dataviews/src/dataform-layouts/panel/modal.tsx]: First, sorry for missing this scenario in the original PR 🙇

@hbhalodia @oandregal I like the idea of overwriting the original array with the new update. I don't see any obvious red flags for this approach.

Comment (oandregal) [reply packages/dataviews/src/dataform-layouts/panel/modal.tsx]: Okay, so let's go with 2 (the current approach in the PR). While simple cases may work well for the 1 option (adding a single values), covering all the use cases will require a lot of complexity (think of: how do we rely that some values were _removed_?).

@hbhalodia yeah, thanks. An important note is to make sure that additional test would fail _before_ this PR and that the changes her would fix it.

Comment (hbhalodia) [reply packages/dataviews/src/dataform-layouts/panel/modal.tsx]: Yep, will update the PR soon with the above changes. 

>  An important note is to make sure that additional test would fail before this PR and that the changes her would fix it.

Not able to collect this? Can you please explain what needs to be done related to test.

Note: Updated the changes.

Thanks,

Comment (hbhalodia) [reply packages/dataviews/src/dataform-layouts/panel/modal.tsx]: Hi @oandregal @ntsekouras @straku, The PR is also updated with latest changes. Can you please take a look on it?

Thanks,

**Review by oandregal — APPROVED** [review]
Thanks for raising this bug and providing a fix, @hbhalodia

**Comment by oandregal** [comment]
@hbhalodia the changelog needs to be updated, I can merge the PR when that's done.

**Comment by hbhalodia** [comment]
Hi @oandregal, The changelog is now updated. Let me know if the sentence needs to be tweaked?

Thank You,
