### PR TITLE
Site Editor: Use server definition for the Template Areas

### LINKED ISSUE #36955: Template Areas UI: Add support for other area types
I was testing some FSE themes from the directory last week and spotted what I suspect is a bug:

Screenshot 2021-11-29 at 12 36 52

The areas UI currently only seems to support Template Parts that are assigned to either the `header` or `footer` area. Other Template Parts (IE those assigned to the `navigation` or `sidebar` area) appear to be broken in the areas UI.

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
Closes #36955.

Updates template details components to use server-side definitions for the Template Areas. In addition, it will allow correctly displaying custom areas registered by themes. If the custom area isn't registered, it will fall back to the "General" area.

## How has this been tested?
1. Create a new template part and add it to the [template parts](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#templateparts) in theme.json.
2. Use `nav` in the area field.
3. Use the snippet below to register the new default template part area.
4. In the site editor, add the new template part we just defined.
5. Template details should correctly display labels for this new area (as seen on screenshot).

```php
add_filter( 'default_wp_template_part_areas', function( $areas ) {
	$areas[] = array(
		'area'        => 'nav',
		'label'       => __( 'Navigation', 'gutenberg' ),
		'description' => '',
		'icon'        => 'layout',
		'area_tag'    => 'div',
	);

	return $areas;
} );
```

For testing, you can also use the [Wowmall](https://wordpress.org/themes/wowmall/) theme.

## Screenshots 
CleanShot 2021-12-08 at 12 43 49

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/edit-site/src/components/sidebar/template-card/template-areas.js [hunk 1]
```diff
@@ -6,27 +6,39 @@ import {
...
 	);
+	const templatePartArea = useSelect(
+		( select ) => {
+			const defaultAreas = select(
+				editorStore
+			).__experimentalGetDefaultTemplatePartAreas();
+
+			return defaultAreas.find(
+				( defaultArea ) => defaultArea.area === area
+			);
```
Comment (Mamaduka) [inline packages/edit-site/src/components/sidebar/template-card/template-areas.js:30]: I doubt myself this morning, but this will correctly pass `isShallowEqual` check if the returned item is the same, right? 😄

**Comment by Mamaduka** [comment]
@jameskoster, I think we should include the "Navigation" icon in the `getTemplatePartIcon`.

File: packages/edit-site/src/components/sidebar/template-card/template-areas.js (hunk 1 above)
Comment (kevin940726) [reply packages/edit-site/src/components/sidebar/template-card/template-areas.js:30]: Yes, I think so 😆 .

**Review by kevin940726 — APPROVED** [review]
Didn't know that it's a thing 😆 .

Code looks good to me, haven't tested it though, but I'll just trust you on that 😛 .

**Review by jameskoster — APPROVED** [review]
It works :)

**Comment by jameskoster** [comment]
> I think we should include the "Navigation" icon in the getTemplatePartIcon.

Agreed. We also need to make it possible to edit the template part properties whilst editing it in focus mode.

**Comment by Mamaduka** [comment]
Thanks for testing, @kevin940726, and @jameskoster.

I can do a quick follow-up for the Navigation icon; it should be a small PR.


> We also need to make it possible to edit the template part properties whilst editing it in focus mode.

Do we have an issue for this?

**Comment by jameskoster** [comment]
No, I'll make one :) 

Edit: https://github.com/WordPress/gutenberg/issues/37220

**Comment by Mamaduka** [comment]
I'm going to merge this. Failing e2e tests is caused by a known issue - a bad request when fetching nonces.

**Comment by noisysocks** [comment]
Thanks @Mamaduka!
