### PR TITLE
Editor: Fix block context defined for template parts

### LINKED ISSUE #58215: Template Part: using name "content" conflicts with the post content block
### Description

I created a pattern called "Content". I added the post content block inside of it. This results in the pattern being inserted inside itself. 

### Step-by-step reproduction instructions

Make new template part in the general area. 
Name it Content
add the "Content" block inside of it. 
You should get a "this block cannot be rendered inside itself" error. 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/5473066/84879259-db79-4c56-90e8-542e38319fab

### Environment info

Wp 6.4 
Gutenberg 17.5.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

### PR DESCRIPTION
**Pull request by youknowriad**
closes #58215 
Regression introduced in #56000 

## What?

Using Post Content blocks was causing an error within the template part editor because we were considering that the "postId" defined in the context corresponded to the same template part being rendered and obviously we can't render a template part within itself.

The problem is that we shouldn't be defining the template part's postId as the "post" context being rendered. In fact there are multiple post types who's editor shouldn't define any context: navigation, template part, reusable block and templates These are global entities that are only there to split blocks into logical units but they don't provide a "context" for the current post/page being rendered. 

## How?

So this PR solve the issue by not providing any "post" context when editing these entities.

## Testing instructions

 - Open the site editor
 - Create a template part or a pattern
 - Insert "Post Content" block
 - No error is triggered.

### CODE REVIEW

**Review by gziolo — APPROVED** [review]
That makes perfect sense 👍🏻

File: packages/editor/src/components/provider/index.js [hunk 1]
```diff
@@ -28,6 +28,12 @@ const { ExperimentalBlockEditorProvider } = unlock( blockEditorPrivateApis );
 const { PatternsMenuItems } = unlock( editPatternsPrivateApis );
 
 const noop = () => {};
+const NON_CONTEXTUALU_POST_TYPES = [
```
Comment (Mamaduka) [inline packages/editor/src/components/provider/index.js]:
```suggestion
const NON_CONTEXTUAL_POST_TYPES = [
```

File: packages/editor/src/components/provider/index.js [hunk 2]
```diff
@@ -113,7 +119,8 @@ export const ExperimentalEditorProvider = withRegistryProvider(
 		const rootLevelPost = shouldRenderTemplate ? template : post;
 		const defaultBlockContext = useMemo( () => {
 			const postContext =
-				rootLevelPost.type !== 'wp_template' || shouldRenderTemplate
+				! NON_CONTEXTUALU_POST_TYPES.includes( rootLevelPost.type ) ||
```
Comment (Mamaduka) [inline packages/editor/src/components/provider/index.js]:
```suggestion
				! NON_CONTEXTUAL_POST_TYPES.includes( rootLevelPost.type ) ||
```

Small typo.

File: packages/editor/src/components/provider/index.js [hunk 3]
```diff
@@ -28,6 +28,12 @@ const { ExperimentalBlockEditorProvider } = unlock( blockEditorPrivateApis );
 const { PatternsMenuItems } = unlock( editPatternsPrivateApis );
 
 const noop = () => {};
+const NON_CONTEXTUAL_POST_TYPES = [
```
Comment (mtias) [inline packages/editor/src/components/provider/index.js:31]: Would be helpful to explain further what these are or why they are distinct

Comment (youknowriad) [reply packages/editor/src/components/provider/index.js:31]: Follow-up here https://github.com/WordPress/gutenberg/pull/58836
