### PR TITLE
'Move to widget area' iterations and fixes

### LINKED ISSUE #31129: Move to widget area available for innerBlocks
In @talldan 's #30826 a button was added that allows moving a between widget areas. The problem is that we should not be able to move inner blocks only root blocks.

## To reproduce

1. Have latest Gutenberg `trunk`
2. Go to Appearance > Widgets
3. Add a buttons block
4. Add a second button
5. Notice that  in the second buttons toolbar there is a "Move to widget area button"
6. Click the "Move to widget area button" and select a widget area
7. Nothing happens

The problem is at (6), as the button should only appear for root blocks.

## Screenshots:

Screen Shot 2021-04-23 at 14 21 06

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #31129, which points out that some blocks can't be moved to a widget area (e.g. button, which can only be added in the buttons block).

This adds a `canInsertBlockType` check to the customize and standalone widgets editors to determine if the Move to Widget Area dropdown should be shown.

Also fixes another issue where a theme might only have a single widget area, but the useless dropdown is still displayed.

#### Move To Widget Area dropdown shows correctly for blocks that can be moved
1. Use a theme that has multiple widget areas (e.g. Twenty Twenty)
2. Add a buttons block to a widget area
3. Select the buttons block, and notice the move to widget area dropdown shows.
4. Select the inner button block, and notice the move to widget area dropdown isn't visible on the toolbar

#### Move To Widget Area dropdown isn't visible for themes with a single widget area
1. Use a theme that has a single widget area (e.g. Twenty Twenty One)
2. In the customizer editor, select a block
3. Notice the move to widget area dropdown isn't visible.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/edit-widgets/src/filters/move-to-widget-area.js [hunk 1]
```diff
@@ -26,17 +36,25 @@ const withMoveToWidgetAreaToolbarItem = createHigherOrderComponent(
...
+						props.name
+					),
 				};
 			},
-			[ __internalWidgetId ]
+			[ __internalWidgetId, blockName ]
 		);
 
 		const { moveBlockToWidgetArea } = useDispatch( editWidgetsStore );
+		const hasMultipleWidgetAreas = widgetAreas?.length > 1;
```
Comment (talldan) [inline packages/edit-widgets/src/filters/move-to-widget-area.js:46]: The standalone editor usually has at least two widget areas (a proper widget area and inactive widgets)

Not sure if there are themes that won't have a widget area for this to become `false`, but I figured it can't hurt to add this for absolute correctness.

**Comment by kevin940726** [comment]
This needs a rebase now that #31308 is merged 😅.

**Comment by talldan** [comment]
rebased 👍

File: packages/edit-widgets/src/filters/move-to-widget-area.js (hunk 1 above)
Comment (draganescu) [reply packages/edit-widgets/src/filters/move-to-widget-area.js:46]: There are themes who don't have any widget areas, but in that case we should display a large message that widgets areas are unsupported by the theme. This is what the classic widgets editor does. See #26153

**Review by draganescu — APPROVED** [review]
This PR is a joy to read and the testing was perfectly smooth.
