### PR TITLE
Fix escape key events in customizer closing the editor

### LINKED ISSUE #31730: Esc and Enter keys: Modify behavior in Customizer > Widgets
This issue is for taking a look at the keyboard behavior for `Esc` and `Enter` keys within the Customizer Widgets screen.

Since the editor and Customizer have different behaviors for these keys, I wonder if we could try a hybrid approach:

- If you have a block selected, `Esc` and `Enter` toggles between Select and Edit mode (default editor behavior)
- If you don’t have a block selected, `Esc` and `Enter` takes you back a screen (default Customizer behavior)

These tweaks would be especially helpful re: the editing flow for legacy widgets that was merged in #30889.

### PR DESCRIPTION
**Pull request by kevin940726**
## Description

Fix #31730.

The issue is that there are 2 different ways to bind <kbd>esc</kbd> key events in Widgets Customizer. One is binding it to close the section/control/panel in the customizer, which is registered in core. The other one is binding it to close the popup or entering the navigation mode in the block editor, which is registered in Gutenberg. Ideally, we should favor the events in Gutenberg first and stop the propagation there, so that the customizer won't trigger the handler and close the current section. However, since that the events in Gutenberg are registered via React's (v16) [event delegation](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation), they are bound to the `document` element. On the other hand, events in core are bound to [`$(body)`](https://github.com/WordPress/WordPress/blob/270f2011f8ec7265c3f4ddce39c77ef5b496ed1c/wp-admin/js/customize-controls.js#L8440-L8495) instead. Which means that when the handlers in React are getting the events, it's already too late to stop the propagation, events in core will always fire first.

The solution I take in this PR is to rewrite those events to bind to the nearest elements which make sense. Instead of implicitly binding to `document` via `onKeyDown`, I'm binding the events to the container element using `addEventListener` directly in `<Popover>`. This might have some undesired side effects though, the <kbd>esc</kbd> won't work now if the focus is not within the container element anymore. We can solve that by binding the events to the React root element instead (the same as in React 17 #26847), but let's see if we actually need to do this.

For navigation mode events, they're already binding themself via `useRefEffect`, we only need to add the missing `event.stopPropagation` to make it work.

These two are the events mentioned in the issue, I'm not sure if there're other ones I'm missing?

## How has this been tested?

**Navigation mode**
1. Go to Appearance -> Customizer -> Widgets
2. Select any block in the editor
3. Press <kbd>esc</kbd>
4. It should enter navigation mode without closing the editor.

**Popover**
1. Go to Appearance -> Customizer -> Widgets
2. Open any popover (block settings dropdown, editor settings dropdown, etc)
3. Press <kbd>esc</kbd>
4. It should close the popover without closing the editor.

Also added e2e tests.

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-editor/src/components/writing-flow/use-tab-nav.js [hunk 1]
```diff
@@ -91,6 +91,7 @@ export default function useTabNav() {
 	const ref = useRefEffect( ( node ) => {
 		function onKeyDown( event ) {
 			if ( event.keyCode === ESCAPE && ! hasMultiSelection() ) {
+				event.stopPropagation();
```
Comment (ellatrix) [inline packages/block-editor/src/components/writing-flow/use-tab-nav.js:94]: How do we handle this in the post editor? We should really avoid `stopPropagation`.

File: packages/components/src/popover/index.js [hunk 2]
```diff
@@ -490,18 +491,25 @@ const Popover = (
 	] );
 
 	// Event handlers
-	const maybeClose = ( event ) => {
-		// Close on escape
-		if ( event.keyCode === ESCAPE && onClose ) {
-			event.stopPropagation();
-			onClose();
-		}
+	useEffect( () => {
```
Comment (ellatrix) [inline packages/components/src/popover/index.js]: For event handlers, we should use `useRefEffect` to guarantee event handlers get reattached when the ref changes.

File: packages/block-editor/src/components/writing-flow/use-tab-nav.js (hunk 1 above)
Comment (kevin940726) [reply packages/block-editor/src/components/writing-flow/use-tab-nav.js:94]: I think it has a valid use case for Escape key, but I see your point!

> How do we handle this in the post editor?

I think this hook is used in the post editor?

File: packages/components/src/popover/index.js (hunk 2 above)
Comment (kevin940726) [reply packages/components/src/popover/index.js]: Makes sense!

File: packages/block-editor/src/components/writing-flow/use-tab-nav.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-editor/src/components/writing-flow/use-tab-nav.js:94]: Right, it is used in the post editor, so I wonder how it worked fine there before?

Comment (ellatrix) [reply packages/block-editor/src/components/writing-flow/use-tab-nav.js:94]: Ah, I see now:

> It should enter navigation mode without closing the editor.

I usually use `event.preventDefault()` and then check down the line if it's been default prevented already. Anyway this seems fine since we're already doing it in other places.

File: packages/components/src/popover/index.js [hunk 3]
```diff
@@ -477,32 +478,39 @@ const Popover = (
...
+	);
+
 	const constrainedTabbingRef = useConstrainedTabbing();
 	const focusReturnRef = useFocusReturn();
 	const focusOnMountRef = useFocusOnMount( focusOnMount );
 	const focusOutsideProps = useFocusOutside( handleOnFocusOutside );
 	const mergedRefs = useMergeRefs( [
 		ref,
 		containerRef,
+		closeEventRef,
```
Comment (ellatrix) [inline packages/components/src/popover/index.js]: Nit pick: you could check `onClose ? closeEventRef : null` like below to avoid adding the behaviour entirely and you'd no longer have to check for `onClose` in the callback.

File: packages/components/src/popover/index.js [hunk 4]
```diff
@@ -587,7 +595,7 @@ const Popover = (
 				}
 			) }
 			{ ...contentProps }
-			onKeyDown={ maybeClose }
+			onKeyDown={ onKeyDown }
```
Comment (ellatrix) [inline packages/components/src/popover/index.js]: Nit pick: you could remove `onKeyDown` from the props and then allow it to be spread through `...contentProps` in the line above.

File: packages/components/src/popover/index.js [hunk 5]
```diff
@@ -477,32 +478,39 @@ const Popover = (
...
+				}
+			}
+
+			node.addEventListener( 'keydown', maybeClose );
+
+			return () => {
+				node.removeEventListener( 'keydown', maybeClose );
+			};
+		},
+		[ onClose ]
```
Comment (ellatrix) [inline packages/components/src/popover/index.js:497]: Nit pick: when we attach event handlers in a ref callback, we usually try to avoid reattaching them when the callback function changes and instead store the callback in a ref and keep it fresh (à la `useLatestRef`) 🙂

**Review by ellatrix — APPROVED** [review]
Left some nit picks but looks good otherwise.

File: packages/components/src/popover/index.js (hunk 5 above)
Comment (kevin940726) [reply packages/components/src/popover/index.js:497]: Yep, but I don't think `onClose` would change often? In addition, I believe we already handle that in `useMergeRefs` to make sure the ref callback will never change.

Comment (ellatrix) [reply packages/components/src/popover/index.js:497]: The main ref callback never changes, but the callback passed to `useRefEffect` will be called every time `onClose` changes.

> Yep, but I don't think `onClose` would change often?

It depends. It's generally a nicer API if you can pass a new function on every render, just as React allows for event handlers. This is also what people are used to. It's easy to forget wrapping a callback in `useCallback`. I believe it's more dev friendly to allow callbacks to change on every render and handle that well.

Comment (kevin940726) [reply packages/components/src/popover/index.js:497]: > but the callback passed to useRefEffect will be called every time onClose changes.

Will it? I believe it will just create a new callback function every time `onClose` changes, but the actual ref callback will only be called if the merged ref callback changes (which it won't, `useMergeRefs` makes sure of that). Not tested though, I might have missed something.

Wrapping every callback into `useCallback` is not always a good practice though, memoization also has a cost. Sure, it could be a good default, but I doubt it without further audits. I like to think that React already provides the most general defaults to us, and we shouldn't try to prematurely optimize things. Especially as we already handled it once in `useMergeRefs`.

(I know it's a nit pick, but I also find it interesting 😆)

Comment (ellatrix) [reply packages/components/src/popover/index.js:497]: Yes, the callback and cleanup functions supplied to `useRefEffect` that add and remove the event listeners will be called when `onClose` changes. `useMergeRefs` uses `useLayoutEffect` internally to do so. I created `useMergeRefs` 🙂

> Wrapping every callback into useCallback is not always a good practice though, memoization also has a cost. 

I'm arguing against the use of `useCallback`. 🙂 What I'm saying is that it could be good to store `onClose` in a ref to be accessed in the callback instead of removing and re-adding event listeners on every render, though `addEventListener` should be performant enough for the impact to be negligible.

**Comment by critterverse** [comment]
Working great for me, thanks @kevin940726! 🎉

File: packages/components/src/popover/index.js (hunk 5 above)
Comment (kevin940726) [reply packages/components/src/popover/index.js:497]: Oh, you're right! I missed that part! Thanks!

I agree. Let's monitor the performance impact (if there's any) before we optimize it. 👍
