### PR TITLE
DataForm: Fix focus loss and refactor Card layout

### LINKED ISSUE #73242: DataForm: Focus loss when collapsing in Card view
### Description

When toggling the expand/collapse button in Card view, keyboard focus is lost. The focus needs to stay on the button.

### Step-by-step reproduction instructions

1. Toggle the collapse button by keyboard.
2. Focus is lost.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/59cda097-ff2c-46da-a5b9-6a5a4a80e10f

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by ntsekouras**
Closes #73242

## What?

Part of this PR is extracted from https://github.com/WordPress/gutenberg/pull/73723 in case we can add it just in time for 7.0 today. If we'll merge on time [props will be given](https://github.com/WordPress/gutenberg/pull/73723) to everyone worked in the linked PR.

It also refactors the component a bit because it seems quite hard to follow IMO.

## Testing Instructions
1. DataForm panel should look and work exactly as before, with the focus loss issue fixed though.

### CODE REVIEW

File: packages/dataviews/src/components/dataform-layouts/card/index.tsx [hunk 1]
```diff
@@ -228,24 +162,55 @@ export default function FormCardField< Item >( {
...
+					className="dataforms-layouts-card__field-header"
+					onClick={ isCollapsible ? toggle : undefined }
+					style={ {
+						cursor: isCollapsible ? 'pointer' : undefined,
+					} }
+					isBorderless
+				>
+					<div
+						style={ {
+							height: isCollapsible ? undefined : '40px',
```
Comment (ciampo) [inline packages/dataviews/src/components/dataform-layouts/card/index.tsx:236]: Let's preserve the comment

```suggestion
							// This is to match the chevron's __next40pxDefaultSize
							height: isCollapsible ? undefined : '40px',
```

File: packages/dataviews/src/components/dataform-layouts/card/index.tsx [hunk 2]
```diff
@@ -262,95 +227,59 @@ export default function FormCardField< Item >( {
...
+							) }
+							<DataFormLayout
+								data={ data }
+								form={ form }
+								onChange={ onChange }
+								validity={ validity?.children }
+							/>
+						</>
+					) : (
+						SingleFieldLayout && (
```
Comment (ciampo) [inline packages/dataviews/src/components/dataform-layouts/card/index.tsx]: This check should be redundant because of the `if (! SingleFieldLayout)` check a few lines above, we can probably remove it?

**Review by ciampo — APPROVED** [review]
Left a couple of comments, but in general code changes LGTM and the focus bug is fixed 🚀

File: packages/dataviews/src/components/dataform-layouts/card/index.tsx (hunk 2 above)
Comment (ntsekouras) [reply packages/dataviews/src/components/dataform-layouts/card/index.tsx]: I had tried that but TS is not happy (can't narrow down the `let` across the ternary boundary). So even if it's guaranteed to be defined here, we can't avoid this check or a similar TS workaround.

**Comment by ciampo** [comment]
@ntsekouras should we backport this fix even if it didn't make the latest release before 7.0?

**Comment by ntsekouras** [comment]
>@ntsekouras should we backport this fix even if it didn't make the latest release before 7.0?

I believe we should, yes. I've asked @ellatrix about the proper label  (either backport to GB RC or WP core) and will add it when I have the answer.

**Comment by ellatrix** [comment]
Reapplied the label because the `wp/7.0` was not created yet and the cherry pick failed.
