### PR TITLE
Global styles: check for recursive dynamic reference in the site editor

### LINKED ISSUE #43154: Theme.json: dynamic references, avoid recursive references
### Description

[Pointed out](https://github.com/WordPress/gutenberg/pull/42976#issuecomment-1209582853) in #42976, the editor crashes when there's a recursive reference in place.

### Step-by-step reproduction instructions

In theme.json add:

```
"color": {
    "background": { "ref": "styles.color.text" },
    "text": {"ref": "styles.color.background" }
},
```

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ramonjd**
Fixes https://github.com/WordPress/gutenberg/issues/43154

## What?

This PR checks for a recursive dynamic reference in `getValueFromVariable()` and bails if found. 

## Why?

When clicking on "Styles", the site editor crashes where a dynamic references points to another dynamic reference.

https://user-images.githubusercontent.com/6458278/184270114-79643a1f-0a9a-4717-9738-0833be4efa3e.mp4

```
utils.js:240 Uncaught TypeError: variable.startsWith is not a function
    at getValueFromVariable (utils.js:240:16)
    at useStyle (hooks.js:130:33)
    at StylesPreview (preview.js:58:42)
    at renderWithHooks (react-dom.js?ver=6.1-alpha-53868:15015:20)
    at mountIndeterminateComponent (react-dom.js?ver=6.1-alpha-53868:17841:15)
    at beginWork (react-dom.js?ver=6.1-alpha-53868:19079:18)
    at HTMLUnknownElement.callCallback (react-dom.js?ver=6.1-alpha-53868:3942:16)
    at Object.invokeGuardedCallbackDev (react-dom.js?ver=6.1-alpha-53868:3991:18)
    at invokeGuardedCallback (react-dom.js?ver=6.1-alpha-53868:4053:33)
    at beginWork$1 (react-dom.js?ver=6.1-alpha-53868:23994:9)

```

## Testing Instructions

Add a recursive reference to your theme.json, e.g., 

```json
{
	"version": 2,
	"settings": {
		"appearanceTools": true
	},
	"styles": {
		"color": {
			"background": {
				"ref": "styles.color.text"
			},
			"text": {
				"ref": "styles.color.background"
			}
		}
	}
}
```

Open up the site editor. You should see the https://github.com/WordPress/gutenberg/blob/34932d72320da970a7d7db39c2ca02d1c27b2bf4/lib/compat/wordpress-6.1/class-wp-theme-json-6-1.php#L969 still. 

Click on the "Styles" button.

Screen Shot 2022-08-12 at 11 00 54 am

The editor shouldn't crash.

### CODE REVIEW

File: packages/edit-site/src/components/global-styles/test/utils.js [hunk 1]
```diff
@@ -134,13 +134,73 @@ describe( 'editor utils', () => {
...
+					},
+				};
+				const actual = getValueFromVariable( stylesWithRefs, 'root', {
+					ref: 'styles.color.text',
+				} );
+
+				expect( actual ).toBe( stylesWithRefs.styles.color.text );
+			} );
+
+			it( 'returns where value is dynamic reference and reference does not exist', () => {
```
Comment (glendaviesnz) [inline packages/edit-site/src/components/global-styles/test/utils.js]: should this be 'returns the originally provided value where value is ....?

File: packages/edit-site/src/components/global-styles/utils.js [hunk 2]
```diff
@@ -222,11 +222,24 @@ function getValueFromCustomVariable( features, blockName, variable, path ) {
...
+ * @return {string|*|{ref}} The value of the CSS var, if found. If not found, the passed variable argument.
+ */
 export function getValueFromVariable( features, blockName, variable ) {
 	if ( ! variable || typeof variable !== 'string' ) {
 		if ( variable?.ref && typeof variable?.ref === 'string' ) {
 			const refPath = variable.ref.split( '.' );
 			variable = get( features, refPath );
+			// Presence of another ref indicates a reference to another dynamic value.
+			// Pointing to another dynamic value is not supported.
+			if ( ! variable || !! variable?.ref ) {
```
Comment (glendaviesnz) [inline packages/edit-site/src/components/global-styles/utils.js:240]: do we need `.?` here since we have already checked that `variable` is defined?

Comment (ramonjd) [reply packages/edit-site/src/components/global-styles/utils.js:240]: I left it in there since variable is reassigned above: `variable = get( features, refPath );`

File: packages/edit-site/src/components/global-styles/test/utils.js (hunk 1 above)
Comment (ramonjd) [reply packages/edit-site/src/components/global-styles/test/utils.js]: yes it should. Thanks!

File: packages/edit-site/src/components/global-styles/use-global-styles-output.js [hunk 3]
```diff
@@ -277,6 +277,11 @@ export function getStylesDeclarations(
 		if ( typeof ruleValue !== 'string' && ruleValue?.ref ) {
 			const refPath = ruleValue.ref.split( '.' );
 			ruleValue = get( tree, refPath );
+			// Presence of another ref indicates a reference to another dynamic value.
+			// Pointing to another dynamic value is not supported.
+			if ( ! ruleValue || !! ruleValue?.ref ) {
```
Comment (ramonjd) [inline packages/edit-site/src/components/global-styles/use-global-styles-output.js:282]: I ran out of time to [add tests](https://github.com/WordPress/gutenberg/blob/22fec1abe5bb61935f40db1aaed3e8b80d097d40/packages/edit-site/src/components/global-styles/test/use-global-styles-output.js) for this today. Will do later or in a follow up

File: packages/edit-site/src/components/global-styles/utils.js (hunk 2 above)
Comment (glendaviesnz) [reply packages/edit-site/src/components/global-styles/utils.js:240]: sorry, wasn't 100% clear, and just a nit really. On line 240 we check again if it is defined with ` if ( ! variable ...`. I thought we would only need `.?` if we were only checking for `.ref`, eg. `if ( !! variable?.ref )` ?  ... it is Friday afternoon though, so I may be missing something 😄

**Comment by MaggieCabrera** [comment]
I was thinking about this yesterday and wasn't sure where it was best to catch this issue, if it's best to handle this when we are resolving what ref is pointing to or right at the start when we are sanitizing the theme.json. The syntax is valid, but not the value being referenced. I don't have an answer to that! In any case, this is working for me and it looks good, thanks for the follow up!

**Review by MaggieCabrera — APPROVED** [review]

**Comment by ramonjd** [comment]
> I was thinking about this yesterday and wasn't sure where it was best to catch this issue, if it's best to handle this when we are resolving what ref is pointing to or right at the start when we are sanitizing the theme.json.


This is an excellent point, thanks for raising.

I naively didn't probe much further than the JS error stack. 😀 

Fetching and sanity checking refs during resolution sounds like it might be more bug-proof.

I'm happy to go further on this as as a follow up next week or help test PRs.

File: packages/edit-site/src/components/global-styles/utils.js (hunk 2 above)
Comment (ramonjd) [reply packages/edit-site/src/components/global-styles/utils.js:240]: Ah sorry 🤦 was my Friday bad. 

Good question. I wanted to check for both just in case the ref pointed to a dead end, not just another ref.

I'll update the comment.

**Comment by ramonjd** [comment]
>  if it's best to handle this when we are resolving what ref is pointing to or right at the start when we are sanitizing the theme.json

I've spent some time testing a couple of backend alternative approaches.

The assumption I made was to move the work of `ref` resolution to the backend: rather than resolve the refs when asking for styles, incoming theme.json styles could be parsed whenever, and as soon as, `WP_Theme_JSON` in instantiated. 

So 

```json
{
	"version": 2,
	"styles": {
		"color": {
			"background": {
				"ref": "styles.color.text"
			},
			"text": "green"
		}
	}
}
```

Would become

```json
{
	"version": 2,
	"styles": {
		"color": {
			"background": "green",
			"text": "green"
		}
	}
}
```

This could happen in the constructor, or indirectly via `sanitize` or another method like `merge`.

The challenge is that it would involve the duplication of a bunch of existing processes, e.g., `get_style_nodes`, `compute_style_properties` and, I guess, not very efficient. 

Furthermore, we need to watch out for `remove_insecure_styles`, which strips refs.

The catch is that we'd want to make sure all theme data are merged first, so perhaps there's a case for `resolve_dynamic_references( $theme_json) // returns $theme_json with style refs resolved`, which can be called at any time. 

I've created a test PR of this idea:

- https://github.com/WordPress/gutenberg/pull/43217

I did also test updating the methods in [Gutenberg_REST_Global_Styles_Controller](https://github.com/WordPress/gutenberg/blob/e238e6588be4ac339bb5e0205b29871514c04bc4/lib/compat/wordpress-6.0/class-gutenberg-rest-global-styles-controller.php#L190) that retrieve theme and theme variations.

This is how the frontend gets the theme.json (and its variations), and here we could parse the style nodes and ensure that any ref values are resolved. 

I thought it might be an alternative, and save a whole bunch of refactoring of `WP_Theme_JSON`, but I rejected that idea pretty quickly, since it doubled up on what's happening in [get_property_value ](https://github.com/WordPress/gutenberg/blob/4a05778b9850c8a6230620959cf6f1ce44941e6c/lib/compat/wordpress-6.1/class-wp-theme-json-6-1.php#L948) anyway 🤷

**Comment by ramonjd** [comment]
I've also created a follow up to remove the duplicated code:

- https://github.com/WordPress/gutenberg/pull/43249

**Comment by MaggieCabrera** [comment]
> 
> I've spent some time testing a couple of backend alternative approaches.
> 
> The assumption I made was to move the work of `ref` resolution to the backend: rather than resolve the refs when asking for styles, incoming theme.json styles could be parsed whenever, and as soon as, `WP_Theme_JSON` in instantiated.
> 

I thought about this too! The problem with that is that then the editor loses the information that that value is a ref to another value, [we should aim to expose this to the user](https://github.com/WordPress/gutenberg/issues/42890#issuecomment-1202318335) at some point so they can decide if they want to replace a value that was initially referencing another one.

**Comment by ramonjd** [comment]
> The problem with that is that then the editor loses the information that that value is a ref to another value, https://github.com/WordPress/gutenberg/issues/42890#issuecomment-1202318335 at some point so they can decide if they want to replace a value that was initially referencing another one.

Oh! That's a tricky one. I wonder how we'd translate it to the UI... 🤔 If Gutenberg did perform resolution on the backend, maybe it could replace the circular ref value with some other error identifier that the UI knows how to handle? Might be too tightly coupled.

**Comment by MaggieCabrera** [comment]
> Oh! That's a tricky one. I wonder how we'd translate it to the UI... 🤔 If Gutenberg did perform resolution on the backend, maybe it could replace the circular ref value with some other error identifier that the UI knows how to handle? Might be too tightly coupled.

I think the backend should provide the frontend with valid values and let the frontend resolve what the ref is. If it's a recursive reference, then it's not a valid value, so we are not letting that reach the frontend. If it's a valid ref, then we let the frontend handle getting the content of that. Right now, resolving it to what the final value is, in the future, we can think how to expose that the value is actually a reference (though I don't know how that would look like technically or UI wise!)
