### PR TITLE
Block editor: create useBlockRef and useBlockElement for better access

### LINKED ISSUE #29457: Site editor: show color warning if poor contrast colors are picked
## Description

If you select a color for the site title that results in poor contrast, no notice is given. This is feedback from the[ FSE Outreach Program's second call for testing](https://make.wordpress.org/test/2021/02/18/fse-program-testing-call-2-build-a-homepage-with-site-editing-blocks/). 

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Use a block based theme and the latest version of Gutenberg to setup the FSE experience.
2. Go to "Site Editor (beta)"
3. Select the Site Title block and change the block settings so that the color contrast is poor for the text (or vice versa for the background).
4. See no notice. 

## Expected behaviour

I expect a notice about poor contrast similar to what happens when you do so in the post/page editor:

Screen Shot 2021-03-01 at 3 53 24 PM

## Actual behaviour

No warning given. 

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/109569843-50947b00-7aa6-11eb-8847-9d65a160b5ec.mov

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 10.0.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

### LINKED ISSUE #29475: Block API: useBlockRef( clientId, ref )
Would replace the `BlockNodes` context and `getBlockDOMNode`.

We have some components that need access to the block node, for example the block toolbar, inserter, writing flow...

The idea is to have a `useBlockRef( clientId, ref )` hook that would add the given ref to the block props in `useBlockProps` for a given client ID. The ref can be either a ref object or callback, that doesn't matter.

Internally, we'd need some kind of store to keep track of all the refs that need to be added. Maybe we kan use `addFilters`? In `useBlockProps`, we'd can use `applyFilters` to get all the refs by client ID. `applyFilters` would need to be reactive though, meaning if a new filter is added, the hook is called again and the block is re-rendered.

Cc @youknowriad @gziolo

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #29475.
Fixes #29457.

This is sorely needed to be able to access the a block node by client ID that doesn't rely on querying the document and doesn't need `ownerDocument`. Currently, the skip to selected block button and colour panels are broken for the iframed site editor.

`useBlockRef` gets a ref that points to the current block node and `useBlockElement` return the element directly and updates whenever the element changes.

We do currently provide block nodes, but it's limited to the selected block nodes and only works within the `BlockList`. This PR also moved the context to the `BlockEditorProvider` so it can be accessed by all components.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-editor/src/components/block-list/block-popover.js [hunk 1]
```diff
@@ -121,6 +113,14 @@ function BlockPopover( {
 		initialToolbarItemIndexRef.current = undefined;
 	}, [ clientId ] );
 
+	const [ selectedElement, setSelectedElement ] = useState();
+	const [ lastSelectedElement, setLastSelectedElement ] = useState();
+	const [ capturingElement, setCapturingElement ] = useState();
+
+	useBlockRef( clientId, setSelectedElement );
+	useBlockRef( lastClientId, setLastSelectedElement );
+	useBlockRef( capturingClientId, setCapturingElement );
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-list/block-popover.js]: In most cases, refs are used without "state" to avoid rerendering when they change. This hook forces the opposite, is this what we we want? rerender this when the ref changes?

File: packages/block-editor/src/components/block-list/use-block-props/use-block-refs.js [hunk 2]
```diff
@@ -0,0 +1,54 @@
+/**
+ * WordPress dependencies
+ */
+import { useEffect, useReducer } from '@wordpress/element';
+
+const store = {
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-list/use-block-props/use-block-refs.js]: This is a global store that's not going to work well in a multi  block editor instances. a Provider would be better here IMO.

File: packages/compose/src/hooks/use-merge-refs/index.js [hunk 3]
```diff
@@ -36,19 +36,24 @@ export default function useMergeRefs( refs ) {
...
+				}
+
 				ref( element.current );
 			}
 		} );
 
 		previousRefs.current = refs;
 		didElementChange.current = false;
-	}, refs );
+	}, [ refs.length, ...refs ] );
```
Comment (youknowriad) [inline packages/compose/src/hooks/use-merge-refs/index.js]: Curious why this hook needed to be changed? was it a bug, should we add a unit test for it?

Comment (ellatrix) [reply packages/compose/src/hooks/use-merge-refs/index.js]: It's only relevant if extra dependencies are added. Strangely, React doesn't trigger and update if you go from e.g. `[]` to `[ value ]`. It assumes the amount of dependencies is constant.

File: packages/block-editor/src/components/block-list/use-block-props/use-block-refs.js (hunk 2 above)
Comment (ellatrix) [reply packages/block-editor/src/components/block-list/use-block-props/use-block-refs.js]: Hm, I'm not following. Client IDs are unique in the whole application?

File: packages/block-editor/src/components/block-list/block-popover.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-editor/src/components/block-list/block-popover.js]: Yes, previously it did the same. We can only render the popover once we know the block element.

File: packages/compose/src/hooks/use-merge-refs/index.js (hunk 3 above)
Comment (ellatrix) [reply packages/compose/src/hooks/use-merge-refs/index.js]: Can add a test case though.

File: packages/block-editor/src/components/block-list/use-block-props/use-block-refs.js (hunk 2 above)
Comment (youknowriad) [reply packages/block-editor/src/components/block-list/use-block-props/use-block-refs.js]: they are indeed but I personally think we should avoid global style in singletons like that as much as we can, this is the exact use case for context providers. 

I think this kind of thing create issues for npm consumption (deduplication of modules...)

Comment (ellatrix) [reply packages/block-editor/src/components/block-list/use-block-props/use-block-refs.js]: Ok, I'll look into it

Comment (ellatrix) [reply packages/block-editor/src/components/block-list/use-block-props/use-block-refs.js]: @youknowriad How would you solve the "skip to selected block" component, which would be rendered outside of the context tree? Somehow it needs access to the right store. Should we use `useSelect` for these refs and store them in the some store as the blocks?

Comment (youknowriad) [reply packages/block-editor/src/components/block-list/use-block-props/use-block-refs.js]: > How would you solve the "skip to selected block" component, which would be rendered outside of the context tree?

What is this component? 

> Somehow it needs access to the right store. Should we use useSelect for these refs and store them in the some store as the blocks?

This is a solution but if we do this, this hook is useless, we can just keep the block node in the store and use useEffect if we need to react to changes

Comment (ellatrix) [reply packages/block-editor/src/components/block-list/use-block-props/use-block-refs.js]: This one: https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/skip-to-selected-block/index.js

File: packages/block-editor/src/components/block-list/block-popover.js [hunk 4]
```diff
@@ -235,6 +222,9 @@ function BlockPopover( {
 					__experimentalOnIndexChange={ ( index ) => {
 						initialToolbarItemIndexRef.current = index;
 					} }
+					// Resets the index whenever the active block changes so
+					// this is not persisted. See https://github.com/WordPress/gutenberg/pull/25760#issuecomment-717906169
+					key={ clientId }
```
Comment (ellatrix) [inline packages/block-editor/src/components/block-list/block-popover.js:227]: Remounting the component is better because the block element may change immediately from one to the other. Previously the block node would be undefined between client ID changes.

File: packages/block-editor/src/components/block-list/insertion-point.js [hunk 5]
```diff
@@ -100,8 +96,7 @@ function InsertionPointPopover( {
 				'vertical';
 
 			return {
-				previousElement: getBlockDOMNode( previous, ownerDocument ),
-				nextElement: getBlockDOMNode( next, ownerDocument ),
+				previousClientId: previous,
```
Comment (ellatrix) [inline packages/block-editor/src/components/block-list/insertion-point.js:99]: Note that previously the element wouldn't update if it changed because it's memoized by client ID.

File: packages/block-editor/src/utils/dom.js [hunk 6]
```diff
@@ -1,36 +1,3 @@
...
-/**
- * Returns the preview container DOM node for a given block client ID, or
- * undefined if the container cannot be determined.
- *
- * @param {string}   clientId Block client ID.
- * @param {Document} doc      Document to search.
- *
- * @return {Node|undefined} Preview container DOM node.
- */
-export function getBlockPreviewContainerDOMNode( clientId, doc ) {
```
Comment (ellatrix) [inline packages/block-editor/src/utils/dom.js:24]: This function is not used anywhere.

File: packages/block-editor/src/components/block-list/use-block-props/use-block-refs.js (hunk 2 above)
Comment (ellatrix) [reply packages/block-editor/src/components/block-list/use-block-props/use-block-refs.js]: Rewrote the PR to use context.

File: packages/block-editor/src/components/block-list/index.js [hunk 7]
```diff
@@ -53,7 +49,7 @@ export default function BlockList( { className, __experimentalLayout } ) {
 	}, [] );
 
 	return (
-		<BlockNodes.Provider value={ blockNodes }>
+		<>
 			{ insertionPoint }
 			<BlockPopover />
```
Comment (ellatrix) [inline packages/block-editor/src/components/block-list/index.js:54]: After this and #31134, we can move the popover and insertion point out of the BlockList component.

File: packages/block-editor/src/components/block-list/use-block-props/use-block-refs.js [hunk 8]
```diff
@@ -0,0 +1,101 @@
...
+	const ref = useRef();
+	useLayoutEffect( () => {
+		refs.set( clientId, ref );
+		return () => {
+			refs.delete( clientId );
+		};
+	}, [] );
+	return useCallback( ( element ) => {
+		// Update the ref in the provider.
+		ref.current = element;
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-list/use-block-props/use-block-refs.js:39]: I wonder if we could just set the element in the context here instead of using an intermediary "ref". I thought the "ref" was useful for useBlockRef, but it doesn't seem to be the case anyway.

**Review by youknowriad — APPROVED** [review]
I like this PR a lot, I like how it simplifies all these places where we rely on block elements. There are probably more.

File: packages/block-editor/src/components/block-list/use-block-props/use-block-refs.js (hunk 8 above)
Comment (ellatrix) [reply packages/block-editor/src/components/block-list/use-block-props/use-block-refs.js:39]: We could through `useMergeRefs`, but we'd need to callback anyway as well, so this seems a bit simpler.

**Review by aristath — APPROVED** [review]

File: packages/block-editor/src/components/provider/index.js [hunk 9]
```diff
@@ -24,7 +25,7 @@ function BlockEditorProvider( props ) {
 	// Syncs the entity provider with changes in the block-editor store.
 	useBlockSync( props );
 
-	return children;
+	return <BlockRefsProvider>{ children }</BlockRefsProvider>;
```
Comment (youknowriad) [inline packages/block-editor/src/components/provider/index.js:28]: Since this is now a Provider inside the state provider, it makes me wonder whether we really need this new provider and whether we can just use the store to keep track of these refs.

Comment (ellatrix) [reply packages/block-editor/src/components/provider/index.js:28]: Hm, I'm not sure. Then we'd have refs and elements in the redux state?

Comment (youknowriad) [reply packages/block-editor/src/components/provider/index.js:28]: Is that an issue? 🤷‍♂️That doesn't bother me personally,  it's not a part of the state that is meant to be serializable

Comment (youknowriad) [reply packages/block-editor/src/components/provider/index.js:28]: To clarify, it doesn't bother me as right now, I'm just wondering whether it's just the same thing and we could avoid the extra state/provider

Comment (ellatrix) [reply packages/block-editor/src/components/provider/index.js:28]: I can try, but we'd still keep the mutable maps because otherwise we're rerendering the editor too much on load
