### PR TITLE
Navigation Block: Fix issue with double-clicking "Create a new menu" causing duplicate menus.

### LINKED ISSUE #56248: Navigation: Possible to create two navigations by mistake
### Description

The "Create a new menu" option in an empty block is possible to double click:
Screenshot 2023-11-17 at 10 59 31

If you do that you accidentally create two navigations by mistake

### Step-by-step reproduction instructions

1. Add a navigation block
2. Delete the navigation CPT that the block is using
3. You should now see a prompt that says "Create a new menu".
4. Double click
5. Notice that two navigations are created.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

All

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by creador-dev**
Fixes #56248

## What?

This PR addresses an issue where users could accidentally create two navigation menus by double-clicking the "Create a new menu" button in an empty block.

## Why?

[#56248](https://github.com/WordPress/gutenberg/issues/56248)

## How?

The DeletedNavigationWarning component has been updated:
- Added a useState hook to manage the disabled state of the button.
- Updated the button to disable immediately after the first click.
- Included the accessibleWhenDisabled prop to ensure the button remains accessible when disabled.

## Testing Instructions

1. Open the **Editor** (Post/Page editor or Site Editor) in WordPress.
2. Insert a **Navigation Block** into your content.
3. Delete the Navigation **Custom Post Type (CPT)** that the block is using.  
   - This can typically be done by navigating to the **Appearance > Navigation** section and deleting the menu associated with the block.
4. Return to the editor, and observe that the **"Create a new menu"** prompt appears within the Navigation block.
5. Quickly double-click the **"Create a new menu"** button.
6. Verify that:
   - The button becomes disabled after the first click.
   - Only one navigation menu is created in the **Appearance > Navigation** section.
   - No duplicate menus are created, even with rapid double-clicking.

### Testing Instructions for Keyboard

1. Follow the steps above using only the keyboard:
   - Navigate to the **"Create a new menu"** button using the **Tab** key.
   - Press **Enter** or **Space** to activate the button.
2. Confirm that the button disables after the first activation.
3. Verify that no duplicate menus are created when the button is activated repeatedly using the keyboard.

### Interacted Accounts

The following accounts have interacted with this PR and/or linked issues:
- @creador-dev

### CODE REVIEW

File: packages/block-library/src/navigation/edit/deleted-navigation-warning.js [hunk 1]
```diff
@@ -4,9 +4,16 @@
...
-import { createInterpolateElement } from '@wordpress/element';
+import { useState, createInterpolateElement } from '@wordpress/element';
 
 function DeletedNavigationWarning( { onCreateNew, isNotice = false } ) {
+	const [ isButtonDisabled, setIsButtonDisabled ] = useState( false );
+
+	const handleButtonClick = () => {
+		setIsButtonDisabled( true );
+		onCreateNew();
+	};
```
Comment (talldan) [inline packages/block-library/src/navigation/edit/deleted-navigation-warning.js:15]: I think I would personally choose to inline this function and as a nicety also pass the arguments through to `onCreateNew`, as this changes the type/signature of the prop.

It still works fine though, so these changes aren't strictly needed, I leave it as some thoughtful feedback. 😄

**Review by talldan — APPROVED** [review]
This works well for me, thanks for contributing, and congrats on your first Gutenberg code contribution 🎉

File: packages/block-library/src/navigation/edit/deleted-navigation-warning.js (hunk 1 above)
Comment (creador-dev) [reply packages/block-library/src/navigation/edit/deleted-navigation-warning.js:15]: @talldan  Thank you so much for your feedback! I really appreciate your insight and will definitely keep this in mind for the future.
