### PR TITLE
Data: Schedule render by store update via setState

### LINKED ISSUE #7722: Regression: Weird behavior with default appender, appears to create two blocks
There are a couple of issues present in `master` that were not in 3.1. 

1. Click the default appender ("write your story") in Chrome, notice how there's a weird flickering
2. Try in Firefox, note how an empty block is created. 
3. Try clicking below the appender, which should rediret the click to the appender — it appears two .blocks are created _until you move the mouse_.

[See videos of issues 1 and 2 here](https://cloudup.com/i7eBVeZShD0).

GIF of issue 3:

3 2beta

Compare with the behavior in 3.1:

### PR DESCRIPTION
**Pull request by aduth**
Fixes #7722

This pull request seeks to resolve an issue with `withSelect` state derivations where a subscribe update could be called with old versions of `this.props` during a scheduled update. Its subsequent `forceUpdate` would thereby prevent the default `shouldComponentUpdate` from taking place, where new props would be expected to be accounted for. The revised implementation here uses `setState` with awareness of the state change by referential equality condition to allow a props change to be accounted for after the subscribe.

**Implementation notes:**

I have thus far been unsuccessful in recreating this via a failing unit test. It's unclear if the render reconciliation flow is different in Enzyme / `react-test-renderer`. Neither have shown promise. The general idea would be that a prop update from a parent would be applied _after_ a child had already triggered `forceUpdate`, and this prop update should but does not have an impact on the `getDerivedStateFromProps`. In the case of #7722, this prop is `lastBlockUID`, where the presence of a previous default block should be preventing the appender from being shown.

The specific handling in React where `shouldComponentUpdate` is being skipped occurs here:

https://github.com/facebook/react/blob/4fe6eec15bc69737910e5c6c749ebc6187d67be0/packages/react-reconciler/src/ReactFiberClassComponent.js#L816-L825

I had explored a number of alternative approaches here, none of which proved to provide stability in ensuring (a) synchronous application of state changes (otherwise resulting in strange behaviors like caret positioning shifting) or (b) major performance regressions.

See: https://gist.github.com/aduth/0b5b6ed26acbbf2f6387cb46d42059fe

**Testing instructions:**

Repeat Steps to Reproduce from #7722, verifying that no ghost appender appears.

Ensure unit tests pass:

```
npm run test-unit
```

Verify there are no performance regressions by typing within the Demo post.

### CODE REVIEW

File: packages/data/src/index.js [hunk 1]
```diff
@@ -307,25 +307,26 @@ export const withSelect = ( mapStateToProps ) => createHigherOrderComponent( ( W
...
 
-		shouldComponentUpdate( nextProps ) {
-			// This implementation of shouldComponentUpdate is only intended
-			// to handle incoming props changes. Changes effected via state
-			// changes are reflected by the subscribe handler's forceUpdate.
-			if ( isShallowEqual( this.props, nextProps ) ) {
+		shouldComponentUpdate( nextProps, nextState ) {
+			const hasPropsChanged = ! isShallowEqual( this.props, nextProps );
+
+			// Only render if result of props change or merge props update
```
Comment (tofumatt) [inline packages/data/src/index.js]: I think this comment is worded a bit strangely so I'm going to tweak it.

File: packages/data/src/index.js [hunk 2]
```diff
@@ -307,25 +307,26 @@ export const withSelect = ( mapStateToProps ) => createHigherOrderComponent( ( W
...
-				// that it is very much a hot code path, and will employ any
-				// and all gymnastics necessary for optimal performance.
-				this.mergeProps = nextMergeProps;
+			// If merge props change as a result of the incoming props, they
+			// should be reflected as such in the upcoming render.
+			if ( hasPropsChanged ) {
+				const nextMergeProps = getNextMergeProps( nextProps );
+				if ( ! isShallowEqual( this.mergeProps, nextMergeProps ) ) {
+					// While side effects are typically discouraged in this
+					// lifecycle methods, this component is very much on a hot
```
Comment (tofumatt) [inline packages/data/src/index.js]: "hot code path" is a great turn of phrase but it might confuse ESL readers (or just folks unfamiliar with that colloquium). I'm just gonna tweak this comment.

**Review by tofumatt — APPROVED** [review]
Tested locally, including the demo post. Perf seems good and the code makes sense.

I think the comments were a bit unclear ("exasperation comments" 😉), so I pushed a tweak to tidy them up.

If you're alright with them: 🚢

**Comment by tofumatt** [comment]
My tabs are set to 2-width in JS because *everyone else in the universe* uses 2-spaces for JS.

If it should be four then we should set it in the `.editorconfig` 😉

**Comment by aduth** [comment]
Oh come now, it's a pretty well-accepted objective truth that tabs are _far_ superior than spaces.

**Comment by jasmussen** [comment]
💥
