### PR TITLE
Framework: Use babel-polyfill in place of runtime builtins

### LINKED ISSUE #9640: Editor: Editor won't load in Internet Explorer
Regression of #9171

Editor won't load when using Internet Explorer.

**Steps to reproduce:**

1. In IE11, navigate to Posts > Add New
2. Observe blank screen

**Expected result:**

Editor.

### PR DESCRIPTION
**Pull request by aduth**
Fixes #9640 
Related: #9275
Alternative to: #9641

This pull request seeks to disable our use of the `@babel/runtime` `useBuiltIns` option, replaced instead by `@babel/polyfill` as a dependency of every script registered by Gutenberg. This could be further enhanced to conditionally load the script only for browsers where expected features are not supported, but at this time it is not evident how such a condition would be formed.

While this technically adds a new script to be loaded, there is a net _decrease_ in bundle size, from 2011.96kb total to 1803.72kb (+89.6kb polyfill) (minified, pre-gzip), for an overall savings of 118.64kb. Full build comparison below:

<details><summary>Before</summary><pre>                         ./build/blocks/index.js    219 KiB      23  [emitted]         blocks
                      ./build/wordcount/index.js     10 KiB       0  [emitted]         wordcount
                            ./build/url/index.js    8.9 KiB       2  [emitted]         url
                     ./build/token-list/index.js     13 KiB       3  [emitted]         tokenList
                      ./build/shortcode/index.js   16.2 KiB       4  [emitted]         shortcode
                  ./build/redux-routine/index.js   18.6 KiB       5  [emitted]         reduxRoutine
                        ./build/plugins/index.js   13.3 KiB       6  [emitted]         plugins
                            ./build/nux/index.js   16.6 KiB       7  [emitted]         nux
                       ./build/keycodes/index.js   3.64 KiB       8  [emitted]         keycodes
               ./build/is-shallow-equal/index.js   1.15 KiB       9  [emitted]         isShallowEqual
                           ./build/i18n/index.js   27.7 KiB      10  [emitted]         i18n
                  ./build/html-entities/index.js  986 bytes      11  [emitted]         htmlEntities
                          ./build/hooks/index.js   19.3 KiB      12  [emitted]         hooks
                        ./build/element/index.js   34.3 KiB      13  [emitted]         element
                         ./build/editor/index.js    371 KiB      14  [emitted]  [big]  editor
                      ./build/dom-ready/index.js  778 bytes      15  [emitted]         domReady
                            ./build/dom/index.js   15.4 KiB      16  [emitted]         dom
                     ./build/deprecated/index.js   10.9 KiB      17  [emitted]         deprecated
                           ./build/date/index.js    196 KiB      18  [emitted]         date
                           ./build/data/index.js   52.1 KiB      19  [emitted]         data
                      ./build/core-data/index.js   57.8 KiB      20  [emitted]         coreData
                        ./build/compose/index.js     18 KiB      21  [emitted]         compose
./build/block-serialization-spec-parser/index.js   9.48 KiB      22  [emitted]         blockSerializationSpecParser
                       ./build/viewport/index.js   13.3 KiB       1  [emitted]         viewport
                           ./build/blob/index.js  909 bytes      24  [emitted]         blob
                          ./build/autop/index.js   24.7 KiB      25  [emitted]         autop
                      ./build/api-fetch/index.js   35.2 KiB      26  [emitted]         apiFetch
                           ./build/a11y/index.js   5.32 KiB      27  [emitted]         a11y
                  ./build/block-library/index.js    217 KiB      28  [emitted]         blockLibrary
                      ./build/edit-post/index.js   87.4 KiB      29  [emitted]         editPost
                     ./build/components/index.js    494 KiB      30  [emitted]  [big]  components</pre></details>

<details><summary>After</summary><pre>                         ./build/blocks/index.js    191 KiB      23  [emitted]         blocks
                      ./build/wordcount/index.js   2.53 KiB       0  [emitted]         wordcount
                            ./build/url/index.js    8.9 KiB       2  [emitted]         url
                     ./build/token-list/index.js   2.39 KiB       3  [emitted]         tokenList
                      ./build/shortcode/index.js   8.89 KiB       4  [emitted]         shortcode
                  ./build/redux-routine/index.js   18.6 KiB       5  [emitted]         reduxRoutine
                        ./build/plugins/index.js   11.7 KiB       6  [emitted]         plugins
                            ./build/nux/index.js   16.6 KiB       7  [emitted]         nux
                       ./build/keycodes/index.js   3.64 KiB       8  [emitted]         keycodes
               ./build/is-shallow-equal/index.js   1.15 KiB       9  [emitted]         isShallowEqual
                           ./build/i18n/index.js   24.6 KiB      10  [emitted]         i18n
                  ./build/html-entities/index.js  986 bytes      11  [emitted]         htmlEntities
                          ./build/hooks/index.js   10.2 KiB      12  [emitted]         hooks
                        ./build/element/index.js   24.3 KiB      13  [emitted]         element
                         ./build/editor/index.js    354 KiB      14  [emitted]  [big]  editor
                      ./build/dom-ready/index.js  778 bytes      15  [emitted]         domReady
                            ./build/dom/index.js   11.4 KiB      16  [emitted]         dom
                     ./build/deprecated/index.js   7.02 KiB      17  [emitted]         deprecated
                           ./build/date/index.js    191 KiB      18  [emitted]         date
                           ./build/data/index.js   43.3 KiB      19  [emitted]         data
                      ./build/core-data/index.js   48.9 KiB      20  [emitted]         coreData
                        ./build/compose/index.js   8.28 KiB      21  [emitted]         compose
./build/block-serialization-spec-parser/index.js   9.48 KiB      22  [emitted]         blockSerializationSpecParser
                       ./build/viewport/index.js   2.77 KiB       1  [emitted]         viewport
                           ./build/blob/index.js  909 bytes      24  [emitted]         blob
                          ./build/autop/index.js   11.8 KiB      25  [emitted]         autop
                      ./build/api-fetch/index.js   28.9 KiB      26  [emitted]         apiFetch
                           ./build/a11y/index.js    1.8 KiB      27  [emitted]         a11y
                  ./build/block-library/index.js    202 KiB      28  [emitted]         blockLibrary
                      ./build/edit-post/index.js   77.9 KiB      29  [emitted]         editPost
                     ./build/components/index.js    478 KiB      30  [emitted]  [big]  components</pre></details>

**Testing instructions:**

Repeat Steps to Reproduce from #9640, verifying both in Internet Explorer and in your preferred browser that there are no issues loading or using the editor.

### CODE REVIEW

File: packages/babel-preset-default/index.js [hunk 1]
```diff
@@ -8,11 +8,8 @@ module.exports = function( api ) {
 				targets: {
 					browsers: [ 'extends @wordpress/browserslist-config' ],
 				},
-				useBuiltIns: 'usage',
-			} ],
-			isTestEnv && [ '@babel/preset-env', {
-				useBuiltIns: 'usage',
 			} ],
+			isTestEnv && [ '@babel/preset-env' ],
```
Comment (youknowriad) [inline packages/babel-preset-default/index.js]: This is a breaking change for this package, should we update the changelog accordingly?

Comment (aduth) [reply packages/babel-preset-default/index.js]: Yes.

Comment (youknowriad) [reply packages/babel-preset-default/index.js]: We can do some cleanup to the `get-babel-config.js` file and remove the override of `useBuiltIns: false,`

**Comment by youknowriad** [comment]
Nice work, I can't test and approve at the moment. It will be the first thing I'll do in the morning unless someone beats me to it.

**Comment by gziolo** [comment]
5 unit tests fail, investigating.

**Comment by gziolo** [comment]
This is very similar but simpler approach taken to what I was trying to do in #9275. I really like where it is going. Let's close #9275 and #9641 and focus to get this one in 💯

**Comment by youknowriad** [comment]
I included a small CSS tweak to fix the block toolbars in 43cde18 (display flex elements in IE need flex-shrink: 0) if they are inside other flex elements :)

I didn't do a separate PR because people won't be able to test otherwise.

File: lib/client-assets.php [hunk 2]
```diff
@@ -830,11 +823,21 @@ function gutenberg_register_vendor_scripts() {
 	wp_add_inline_script( 'lodash', 'window.lodash = _.noConflict();' );
 	gutenberg_register_vendor_script(
 		'wp-polyfill-fetch',
-		'https://unpkg.com/whatwg-fetch/fetch.js'
+		'https://unpkg.com/whatwg-fetch/fetch.js',
+		array( 'wp-deprecated' )
+	);
+	wp_add_inline_script(
+		'wp-polyfill-fetch',
+		'wp.deprecated( "wp-polyfill-fetch script handle", { plugin: "Gutenberg", version: "4.0" } );'
```
Comment (gziolo) [inline lib/client-assets.php]: Does it mean that `wp-polyfill-ecmascript` contains also polyfill for fetch?

I can see some code for `Promise` in https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.0.0/polyfill.js, but can't see anything related to `fetch`.

File: packages/babel-preset-default/index.js [hunk 3]
```diff
@@ -8,7 +8,6 @@ module.exports = function( api ) {
 				targets: {
 					browsers: [ 'extends @wordpress/browserslist-config' ],
 				},
-				useBuiltIns: 'usage',
 			} ],
 			isTestEnv && [ '@babel/preset-env', {
 				useBuiltIns: 'usage',
```
Comment (gziolo) [inline packages/babel-preset-default/index.js]: I had to revert the change which removes:
`useBuiltIns: 'usage',`
from test environment because some tests were failing. Those which use `Array.values` method which isn't supported by Node.

@youknowriad suggested using `babel-polyfill` instead to have the setup closer to the browser but I found out that it can cause memory issues with Jest. See https://github.com/facebook/jest/pull/2755 and the line in the changelog:
> Breaking Change: Replaced auto-loading of babel-polyfill with only regenerator-runtime, fixes a major memory leak.

File: packages/babel-preset-default/test/index.js [hunk 4]
```diff
@@ -16,6 +16,7 @@ describe( 'Babel preset default', () => {
 
 		const output = transform( input, {
 			configFile: false,
+			envName: 'production',
```
Comment (gziolo) [inline packages/babel-preset-default/test/index.js]: With this change, we test again production configuration rather than test env ... It is more helpful now :)

**Comment by youknowriad** [comment]
Hey hey looks like the tests pass now 🎉

**Comment by gziolo** [comment]
We still need to test it against IE11, @jorgefilipecosta or @tofumatt can you help to ensure it works consistently?

File: lib/client-assets.php (hunk 2 above)
Comment (youknowriad) [reply lib/client-assets.php]: Since it relies on `core-js` I don't think it's included https://github.com/zloirock/core-js#missing-polyfills

**Review by tofumatt — CHANGES_REQUESTED** [review]
This isn't working for me in IE11, it seems there is no `fetch` polypill. When the editor goes to autosave it gets stuck on "Autosaving…" with this error:

```
TypeError: Object doesn't support property or method 'fetch'
```

**Review by youknowriad — APPROVED** [review]
LGTM 👍 Tested in IE and chrome. Works great.

**Review by tofumatt — APPROVED** [review]

**Comment by tofumatt** [comment]
I didn't re-test in IE but if @youknowriad says it works in IE11 that's good enough for me; dismissing my review 😄
