### PR TITLE
Fix nav editor links to correctly persist new tab target attribute

### LINKED ISSUE #30323: Navigation screen: The 'Open in new tab' setting is not saved
## Description
In the navigation screen, using the 'Open in new tab' option on a link has no effect.

## Step-by-step reproduction instructions
1. Add a menu item with a link and enable the open in new tab option
2. Save and reload
3. View the link for menu item just added
4. Observe the option is disabled again
5. View the menu on the front end of the site
6. Click the link—it doesn't open in a new menu.

## Expected behaviour
The option should be retained when saving. The link in the frontend should open in a new tab.

The old menu screen had this option (under advanced screen options), so it should be possible to save the setting.

### PR DESCRIPTION
**Pull request by getdave**
## Description

Fixes https://github.com/WordPress/gutenberg/issues/30323.

Currently within the Navigation Editor the feature to cause a nav link to _"Open in new tab"_ does not work. 

Whilst it is possible to toggle the control and have the state persist within the _editor_, if you reload the editor the setting state is not persisted (ie: it is always "off").

The reason for this is that that the `settings` property on the underlying `<LinkControl>` component is called `opensInNewTab` whereas the menuItem data (when stored in the database) expects a `target` property with a string value of `_blank`. This mismatch has not been accounted for when translating `core/navigation-link` blocks into the equivalent menu item to be persisted into the database. 

This PR updates things so that 

* when the block is translated into the database format it sets the `target` attribute to `_blank` if the block has `opensInNewTab` set to `true`.
* when the menu item from the database is converted into a block the `opensInNewTab` property is set based on the presence of the string `_blank` as the value of the menu item's `target` property.

🙏 Note: I'd appreciate a confidence check that the value `_blank` is the correct string value as used on the old WordPress menu page.

## How has this been tested?

1. Manually.
2. Automated tests.

### Manual Testing

In the Navigation Editor (experimental):

* Create a new menu and add a single nav item with a link.
* Toggle the `Opens in new tab` to "on".
* Save the menu.
* Reload the editor.
* Click on the menu item you added and check the `Opens in new tab` setting is still set to "on".
* Now, toggle the `Opens in new tab` setting to "off".
* Save the menu.
* Reload the editor.
* Click on the menu item you added and check the `Opens in new tab` setting is still set to "off".

Note is is important to check that you can toggle this setting on and off. Also repeat for multiple nav items within a menu and using different link types.

### Automated Tests

Run `npm run test-unit packages/edit-navigation/src/store/test/`. See all ✅ .

## Screenshots 

https://user-images.githubusercontent.com/444434/115224742-26098a80-a105-11eb-8c25-53989dfc2dcd.mov

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by getdave** [comment]
There may be a wider follow-up to this required where we methodically go through all the possible nav menu item fields and ensure they are correctly mapped to block attributes (and the inverse!). We'll need some unit tests for this to avoid future regressions.

**Comment by gwwar** [comment]
> Note: I'd appreciate a confidence check that the value _blank is the correct string value as used on the old WordPress menu page.

Yes, `_blank` is the correct value. I tested this with the following:

With Gutenberg plugin disabled > wp-admin/nav-menus.php > Screen Options (then select Link Target) 

Screen Shot 2021-04-21 at 10 48 02 AM

Screen Shot 2021-04-21 at 10 49 05 AM

**Review by gwwar — APPROVED** [review]
Thanks @getdave this manually tests well for me and code looks reasonable . I'm not as familiar with the serialization here, so a +1 from other folks working on the navigation editor wouldn't hurt.

I tested this against the old menu editor, navigation editor, and populating a navigation block from a menu.

https://user-images.githubusercontent.com/1270189/115605135-00ac8600-a297-11eb-899c-d938225ece1a.mp4

File: packages/edit-navigation/src/store/resolvers.js [hunk 1]
```diff
@@ -147,6 +152,9 @@ function convertMenuItemToBlock( menuItem, innerBlocks = [] ) {
 		className: menuItem.classes.join( ' ' ),
 		description: menuItem.description,
 		rel: menuItem.xfn.join( ' ' ),
+		...( menuItem.target === NEW_TAB_TARGET_ATTRIBUTE && {
+			opensInNewTab: true,
+		} ),
```
Comment (talldan) [inline packages/edit-navigation/src/store/resolvers.js:157]: fancy!

**Review by talldan — APPROVED** [review]
Looks good 👍
