### PR TITLE
Fix layout for non viewable post types

### LINKED ISSUE #58956: Site Editor: Unintended title display and content width
Most canvases in the site editor seem to be experiencing the following issue.

- The entity title is displayed
- The content width is narrow

When I searched for the problematic commit using `git bisect`, #58935 seems to be affected. #58935 has a backport label, so it may need to be fixed soon.

### Actual

image

### Expected

image

### PR DESCRIPTION
**Pull request by youknowriad**
closes #58956

## What?

Post Types that are not "viewable", which basically means post types that don't get rendered within a template in the frontend shouldn't get the post content or global layout applied when rendered in the editor. This fixes a regression introduced in #58935 where this was taking into consideration by using the "all" rendering mode.

## Testing Instructions

1- Open the site editor
2- Ensure that the layout is correct (no extra title is added and the content is not narrow)

### CODE REVIEW

**Comment by youknowriad** [comment]
Mmm, so it turns out that testing viewable is not strictly equivalent to what we want (e2e failure), we want to be able to fill the "title" for some non public post types as well excluding (wp_block, wp_navigation, wp_template_part and wp_template). So I'm going to use a fix list for these.

File: packages/editor/src/components/editor-canvas/index.js [hunk 1]
```diff
@@ -40,6 +40,17 @@ const {
...
+/**
+ * These post types have a special editor where they don't allow you to fill the title
+ * and they don't apply the layout styles.
+ */
+const DESIGN_POST_TYPES = [
+	'wp_block',
+	'wp_template',
+	'wp_navigation',
+	'wp_template_part',
+];
```
Comment (mcsf) [inline packages/editor/src/components/editor-canvas/index.js:52]: I'm fine with this fix, but of course I wonder if there's a systematic way to do it instead of using constants.

Comment (youknowriad) [reply packages/editor/src/components/editor-canvas/index.js:52]: I think there are multiple things at play here and we need a way for post styles to say:

 - I'm rendered within a template (isViewable), so this should probably control the layout
 - Users can edit the title in the canvas: We don't have anything for that, thus the need for this custom array for now.

I'm not sure what the right fix would be for the last part yet, so I kept it like 6.4 for now but indeed, it seems there's some rule missing/flag/support missing here.

**Comment by youknowriad** [comment]
Backported

**Comment by creativecoder** [comment]
Note that as part of curating the Gutenberg 17.8 changelog, I added the label [[Package] Editor](https://github.com/WordPress/gutenberg/labels/%5BPackage%5D%20Editor) to this PR to better categorize it.

Please let me know if there is a different label that would be a better fit.
