### PR TITLE
Avoid copying global style presets via the styles compatibility hook

### LINKED ISSUE #52155: If there is a block with apiVersion of 2 in block.json, the content width is applied to the pattern preview
### Description

For example, activate a plugin with apiVersion 2 blocks such as CoBlocks. The content width would then be applied to the content in the pattern preview.

Specifically, the following styles will be added in the pattern preview.

```
.editor-styles-wrapper .block-editor-block-list__layout.is-root-container > :where(:not(.alignleft):not(.alignright):not(.alignfull)) {
    max-width: 650px;
    margin-left: auto !important;
    margin-right: auto !important;
}
```

If the apiVersion is only a block of 3, this style will not be loaded.

Even without the block plugin installed, I was able to reproduce the problem by changing `wp-includes/blocks/blocks-json.php` as follows.

```
<?php return array(
  'archives' => array(
    '$schema' => 'https://schemas.wp.org/trunk/block.json',
    'apiVersion' => 2, // 3 to 2
```

### Step-by-step reproduction instructions

1. Activate the appropriate block plugins. For example, CoBlocks
2. Open the Submission Editor
3. Open the Pattern Inserter
4. Check the preview
-----
1. Modify `wp-includes/blocks/blocks-json.php`.
2. Open the Submission Editor
3. Open the Pattern Inserter
4. Check the preview

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1094306/a34f622f-5cd6-43fd-b41c-d74b28d1b384

### Environment info

- WordPress 6.3 beta2
- TwentyTwentyThree v1.1

This problem does not occur when the Gutenberg (v16.1.0) plugin is activated.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #52648: Blockeditor iFraming problems when switching Preview
### Description

There seem to be some problems when switching the Blockeditor Preview which result from the new iFraming functions introduced in https://github.com/WordPress/gutenberg/pull/50091 and https://github.com/WordPress/gutenberg/pull/48286 .

When using WP 6.2.2 with Gutenberg 16.1.1 and original Twenty Twenty-Three Theme, everything works as expected. The Blockeditor is fully iFramed and no console warnings are shown.

According to https://github.com/WordPress/gutenberg/pull/48286 the fully iFramed Editor is used when "all blocks are v3". However, by adding a single `add_meta_boxes` action (see snippet), the Editor is back its old behaviour with Tablet and Mobile previews in iFrames and Desktop without. From that point on, switching the preview to Tablet or Mobile shows console warnings from https://github.com/WordPress/gutenberg/pull/50091- even with the Twenty Twenty-Three Theme (see gutenberg-16-bugreport-03.jpg). The actual problem occurs when switching back to Desktop while a block is selected. In that case, a fatal javascript error is thrown and the block is broken with the message "This block has encountered an error and cannot be previewed." (see gutenberg-16-bugreport-04.jpg).

Firefox prints a bit more info in the console:
`e.ownerDocument.defaultView is null` in `wp/packages/block-editor/build-module/hooks/@wordpress/block-editor/src/hooks/padding.js:14`.
As far a I understand, this happens because while switching the preview, the iFrame is destroyed to be replaced by the non-iFramed Desktop preview.

A secondary bug I noticed when making the screenshots:
In Tablet and Mobile preview, the Toolbar is missing.

### Step-by-step reproduction instructions

- Add snippet to theme or custom plugin functions.php
- Open example page (gutenberg-16-bugreport-01.jpg)
- Select a paragraph block (gutenberg-16-bugreport-02.jpg)
- Switch to "Tablet" preview (gutenberg-16-bugreport-03.jpg)
  - _Notice console warnings_
  - _Toolbar is missing_
- Switch back to "Desktop" preview (gutenberg-16-bugreport-04.jpg)
  - _console error_ `e.ownerDocument.defaultView is null`
  - Selected block is broken

### Screenshots, screen recording, code snippet

snippet
```
add_action( 'add_meta_boxes', function() {
	add_meta_box(
		'custom_meta_box',
		__('Test', 'core'),
		function() { /* empty */ },
		null,
		'side'
	);
} );
```

gutenberg-16-bugreport-01.jpg
gutenberg-16-bugreport-01

gutenberg-16-bugreport-02.jpg
gutenberg-16-bugreport-02

gutenberg-16-bugreport-03.jpg
gutenberg-16-bugreport-03

gutenberg-16-bugreport-04.jpg
gutenberg-16-bugreport-04

### Environment info

- WP 6.2.2
- Gutenberg 16.1.1
- Twenty Twenty-Three
- Chrome, Firefox Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes #52155.

This is just a PoC PR. It updates the `useCompatibilityStyles` hook to avoid copying styles directly rendered in the editors.

## Why?
* When the non-iframed editor is rendered, global style presets are injected into a `body`.
* The `useCompatibilityStyles` parses and memoized document stylesheet on initial load. So these styles are added to the compat styles array.
* The presets are copied as part of the compatibility layer when the iframed editor is rendered via pattern preview or switching device type. This results in "broken" previews and unnecessary warnings in the console.

## How?
~~I added a custom data attribute to the `style` tags generated by the `EditorStyles` and `LayoutStyle` components. This "marked" is used to skip collecting preset styles in the `compatStyles` list.~~

Skip the styles without IDs. Styles enqueued via the WP dependency system will always have IDs.

## Testing Instructions
1. Open a Post or Page.
2. Enable "Custom fields" from Preferences.
3. Switch to device preview 'Tablet' and confirm no warnings in the console.
4. Open the pattern inserter and switch to the "Featured" category.
5. Confirm pattern previews are rendered without extra spacing.

## Screenshots or screencast 
CleanShot 2023-07-14 at 17 15 56

### CODE REVIEW

**Comment by ellatrix** [comment]
Interesting. Why weren't these styles being added previously for previews, when the editor was not iframed? Or was this always an issue?

File: packages/block-editor/src/components/iframe/use-compatibility-styles.js [hunk 1]
```diff
@@ -45,6 +45,11 @@ export function useCompatibilityStyles() {
 					return accumulator;
 				}
 
+				// Don't try to add global style presets; they're directly rendered in iframe.
+				if ( ownerNode.dataset.globalStyle === 'preset' ) {
```
Comment (ellatrix) [inline packages/block-editor/src/components/iframe/use-compatibility-styles.js]: Alternatively we could only accept stylesheets with an ID, which is any stylesheet added through the WP dependency system. What do you think?

**Review by ellatrix — APPROVED** [review]

File: packages/block-editor/src/components/iframe/use-compatibility-styles.js (hunk 1 above)
Comment (Mamaduka) [reply packages/block-editor/src/components/iframe/use-compatibility-styles.js]: That should work as well, and no need to maintain the "markers" concept. I'll update the code.

**Comment by Mamaduka** [comment]
> Why weren't these styles being added previously for previews, when the editor was not iframed? Or was this always an issue?

Hard to say for sure. The styles that affect the preview layout could be new, and we only recently returned the compat error log.

We would have caught this earlier if it was for this [special treatment of the Gutenberg plugin](https://github.com/WordPress/gutenberg/blob/5e44d3db252ba483dc8e88b1e337fbe0613544be/packages/edit-post/src/components/visual-editor/index.js#L364).

File: packages/block-editor/src/components/iframe/use-compatibility-styles.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-editor/src/components/iframe/use-compatibility-styles.js]: Great. This compat layer was anyway only intended to be for styles added through the WP dependency system.

**Comment by bph** [comment]
@ellatrix 
>Why weren't these styles being added previously for previews, when the editor was not iframed? Or was this always an issue?

Not sure this answers your question. I mention this to close the circle, [there was an earlier remark on an PR after merge](https://github.com/WordPress/gutenberg/pull/50091#issuecomment-1592582675), that didn't bubble up. Only when they contacted me, wondering why this wasn't worked on, I suggested [filing a separate bug report fast](https://github.com/WordPress/gutenberg/issues/52648#top).

**Comment by ramonjd** [comment]
I just cherry-picked this PR to the update/second-round-RC1 branch to get it included in the next release: c13d613e00
