### PR TITLE
Fix updateSlot missing from default SlotFillContext

### LINKED ISSUE #23014: Slot/Fill - `updateSlot` is missing from Slot Fill Context.
**Describe the bug**
I'm trying to use [@wordpress/block-editor](https://www.npmjs.com/package/@wordpress/block-editor) as a standalone library and copied the [example](https://www.npmjs.com/package/@wordpress/block-editor#usage).

I am unable to get it running because, it appears like this call: 

https://github.com/WordPress/gutenberg/blob/8ac282605512cb4ee0c90973b60e1d01596df018/packages/components/src/slot-fill/bubbles-virtually/slot.js#L34

is failing because `updateSlot` is undefined as it's not part of the `slot-fill-context`.

https://github.com/WordPress/gutenberg/blob/8ac282605512cb4ee0c90973b60e1d01596df018/packages/components/src/slot-fill/bubbles-virtually/slot-fill-context.js#L6

Instead, it appears to have moved to the `useSlot` hook:
https://github.com/WordPress/gutenberg/blob/8ac282605512cb4ee0c90973b60e1d01596df018/packages/components/src/slot-fill/bubbles-virtually/use-slot.js#L18

In this PR:
https://github.com/WordPress/gutenberg/pull/19242

**To reproduce**
I used Create React App to get started.

1. Create React app.
2. Install everything listed in the `@wordpress/block-editor` example https://www.npmjs.com/package/@wordpress/block-editor#usage
3. Try to run app.
4. Expect to see this:
Error Notice

**Editor version (please complete the following information):**
Pulled from `package.json`:
```
 {
    "@wordpress/block-editor": "^4.0.0",
    "@wordpress/block-library": "^2.19.0",
    "@wordpress/components": "^9.7.0",
    "@wordpress/element": "^2.14.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"
}
```

**Desktop (please complete the following information):**
 - OS: macOs (Catalina)
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by diegohaz**
Closes #23014

Due to the convention that this module adopts, I think the preferred fix is to simply add `updateSlot` as a noop function to the default object that is returned by the context (when `SlotFillProvider` isn't present).

But I also wonder when using `Slot`/`Fill` without `SlotFillProvider` would make sense.

Failing test: https://travis-ci.com/github/WordPress/gutenberg/jobs/347817325#L3248

### CODE REVIEW

File: packages/components/src/slot-fill/bubbles-virtually/slot-fill-provider.js [hunk 1]
```diff
@@ -93,6 +93,7 @@ function useSlotRegistry() {
 			slots,
 			fills,
 			registerSlot,
+			updateSlot,
```
Comment (diegohaz) [inline packages/components/src/slot-fill/bubbles-virtually/slot-fill-provider.js:96]: This was also missing from the React memo deps, although it wasn't making any difference.

**Review by gziolo — APPROVED** [review]
Thanks for a quick fix 💯 

As noted in the parent issue: https://github.com/WordPress/gutenberg/issues/23014#issuecomment-643065493, we should consider adding warnings when the provider is missing.

**Comment by sirreal** [comment]
> But I also wonder when using Slot/Fill without SlotFillProvider would make sense.

Does this component work in expected ways without the provider? When reviewing the code, I got the impression that the Provider was absolutely necessary to get coherent behavior, and it would be preferable to throw an informative error early in the Consumer when it's not mounted under a Provider.

**Comment by gziolo** [comment]
@sirreal, see https://github.com/WordPress/gutenberg/pull/23108#pullrequestreview-429477187:

> we should consider adding warnings when the provider is missing
