### PR TITLE
Try fixing post editor layout for wide/full Post Content blocks

### LINKED ISSUE #49546: Layout / Post Editor: A post content block set to "wide" is not rendered as wide within the post editor
### Description

In WordPress 6.2, the post editor was updated to more closely reflect visually the block attributes set on the post content block in the template currently in use. This works well for constrained layouts with site-level `contentSize` or `wideSize` set, however for themes that use a post content block that is nested within a Group block and set to `wide` alignment, this wide alignment is not reflected in the post editor.

### What's expected

For templates that set the Post Content block to `wide` alignment within the template, that when a user opens up the post editor, the wide alignment will be respected and rendered correctly.

### What happens instead

When opening up the post editor, the blocks are displayed as if constrained to `contentSize` instead of `wideSize`

### A caveat about this issue

This would be a good issue to resolve (ensuring rendering of `wide` post content blocks is accurate within the post editor), but also reveals an interesting case for themes. My suspicion is that in many cases when a template is set up in this way, it isn't _quite_ what the theme or user desires.

For example, if a template is set up as a `wide` template, with the expectation that content within the template will be displayed at a wider size than other templates, in many cases it is likely preferable to set the post content block to a constrained layout with custom values for `contentSize` and `wideSize` that are wider than the global values used by the theme, _or_ to use block patterns where a wrapping group block is set to `wide`, and that pattern is inserted within a post or page by the user. This is because:

* If a template sets the post content block to `wide` and with layout _not_ constrained (that is, no options for content/wide size), then it isn't possible for users to set content within the post to other alignments (e.g. the options for content/wide/full that are commonly expected)

### Step-by-step reproduction instructions

* In a blocks theme (to make testing more clear, I used `emptytheme`), add the following markup to a post or page template:

```
<!-- wp:group {"align":"wide","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide"><!-- wp:post-content {"align":"wide"} /--></div>
<!-- /wp:group -->
```

* Save the template
* Create a post or page using that template
* Notice that while it's expected that the post will be displayed within the editor using `wide` width, instead the regular `contentSize` is applied to blocks within the post or page
* The site frontend is unaffected

### Screenshots, screen recording, code snippet

View while editing the template:

image

View while editing a post or page using that template:

image

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

Thanks @annezazu and @richtabor for raising the issue, and CC: @tellthemachines

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

Fixes #49546.

This is not a perfect fix, because it assumes that Post Content is inside a constrained layout block with the default wide content value. If the parent block has custom content/wide width values set, it won't really work. 

Currently the only way to make sure the post editor layout conforms exactly to the appearance of the Post Content block would be to look at the attributes of all its parent blocks, which would require a lot of complicated logic 😅 and, given the direction #41717 sets for the future of post editing, it is likely not worth the effort. (Once the editors are unified as per #41717, the problem will be solved because the post editing interface will reproduce its template structure exactly.)

The fix in this PR should cover a bunch of common cases though, so I think it can still be useful.

## Testing Instructions

1. In a block theme, edit the Single template so that Post Content is nested in a Group with "Inner blocks use content width" turned on, and is set to "wide" alignment. Post Content itself should have "Inner blocks use content width" turned off.
2. Save changes and go to the post editor. Add a few blocks to the post and check that their maximum width is the theme wide alignment width.
3. Back in the template view, try switching the Post Content alignment to "full" and save changes.
4. Reload the post editor and check that the content now stretches to full width of the editor.

## Screenshots or screencast 

Editor with full width layout:

Screenshot 2023-04-04 at 1 55 25 pm

### CODE REVIEW

File: packages/edit-post/src/components/visual-editor/index.js [hunk 1]
```diff
@@ -272,7 +272,8 @@ export default function VisualEditor( { styles } ) {
 		{
 			'is-layout-flow': ! themeSupportsLayout,
 		},
-		themeSupportsLayout && postContentLayoutClasses
+		themeSupportsLayout && postContentLayoutClasses,
+		align && `align${ align }`
```
Comment (andrewserong) [inline packages/edit-post/src/components/visual-editor/index.js:276]: I know this is likely pretty edge-casey, but what about the case where the wide post content block has the constrained layout type (or `inherit: true`)? In that case, in the site editor, the preview of the post content block will visually look like the content is constrained to the contentSize, but when opening up the page editor, the `alignwide` rules take precedence.

To avoid that, I was wondering if we could add a variable to use before outputting the classname and styles. E.g. something along the lines of:

```
const { layout = {}, align = '' } = newestPostContentAttributes || {};
const outputAlignmentStyles = !! ( align && ( ! layout.type || layout.type === 'default' ) );
```

And then use that in this line and before outputting `<LayoutStyle...` below?

**Review by andrewserong — COMMENTED** [review]
Thanks for putting together a fix so quickly! I think the direction here is a good pragmatic fix for the reported issue, and helps get the UI closer to what's expected. As you mention, so long as the post editor is separate from the template, it'll always be a little different to how the content will appear on the site frontend, but this gets it much closer for this case 👍

Just left a comment about post content blocks that have `wide` alignment as well as using constrained layout, and whether we should check that we're using the `default` layout type before outputting the align class and styles.

Another subtle issue, that could very well not be worth attempting to fix in this PR, is that the blocks within the editor canvas report the `None` alignment as `Max 840x wide`. However in this context, everything will be at either wide width or full width.

image

Aside from those two issues, this is otherwise testing great for me!

**Comment by ramonjd** [comment]
Testing this, it looks to me to address the issue of ensuring that the post content in the post editor reflects post content block alignment.

I've given then post content block in the singular post template an alignment value of "full". Here's what I see in the post editor:

### Before
Screenshot 2023-04-05 at 11 52 29 am


### After
Screenshot 2023-04-05 at 11 52 20 am


I have a question, and I'm not sure if this is a valid one.

I was fiddling with alignments on the post content block in the template editor. E.g., I gave the block a right alignment:

Screenshot 2023-04-05 at 12 02 13 pm


In trunk I'm seeing this in the post editor, which matches what I see on the frontend:

Screenshot 2023-04-05 at 12 02 19 pm


On this branch however, the alignment is being overridden, I think by this [line of CSS](https://github.com/WordPress/gutenberg/pull/49565/files#diff-175b6822ebac715bc984ae982f1d9230b5d1e441c98138d8a1fc7ccf275c19bcR335)

Screenshot 2023-04-05 at 12 02 29 pm

And the post editor no longer appears as it does on the frontend, that is, right-aligned.

File: packages/edit-post/src/components/visual-editor/index.js (hunk 1 above)
Comment (tellthemachines) [reply packages/edit-post/src/components/visual-editor/index.js:276]: Well spotted! I think we should still output the alignment styles though, because if the Post Content is alignwide none of its children will ever be wider than that, so it helps to have the content max width set. 

Instead, I'm going to try scoping the rules affecting Post Content children to when Post Content itself is `is-layout-flow`.

Comment (andrewserong) [reply packages/edit-post/src/components/visual-editor/index.js:276]: > Instead, I'm going to try scoping the rules affecting Post Content children to when Post Content itself is is-layout-flow.

Nice, that helps keep the code simpler, too 👍

**Comment by tellthemachines** [comment]
Thanks for the feedback folks!

> On this branch however, the alignment is being overridden, I think by this [line of CSS](https://github.com/WordPress/gutenberg/pull/49565/files#diff-175b6822ebac715bc984ae982f1d9230b5d1e441c98138d8a1fc7ccf275c19bcR335)

Ah yes, that should now be fixed too! It was a consequence of the issue Andy pointed out [here](https://github.com/WordPress/gutenberg/pull/49565#discussion_r1156707168).

> Another subtle issue, that could very well not be worth attempting to fix in this PR, is that the blocks within the editor canvas report the None alignment as Max 840x wide. However in this context, everything will be at either wide width or full width.

I think that might be good to address separately because it's really an existing issue: children of blocks with flow layout still get that `max [content width] wide` label even though their width with no alignment will be the same as that of their parent, which could be anything. We should probably only output the label for children of constrained layouts, or when we know for sure what the width will be.

**Review by andrewserong — APPROVED** [review]
Thanks for the updates, this is testing well for me now! Nice work coming up with an elegant CSS fix 👍

✅ The original issue of displaying flow layouts for a post content block set to `wide` is still working well
✅ When the post content block is set to a constrained layout type, the alignments are working now
✅ The `alignwide` and `alignfull` rules are being correctly applied, as you mention, this ensures that if a post content block is set to `wide` that the full size cannot be larger than the wide size:

image

> I think that might be good to address separately because it's really an existing issue: children of blocks with flow layout still get that max [content width] wide label even though their width with no alignment will be the same as that of their parent, which could be anything. 

I agree, a separate PR sounds good — it sounds like hiding the description of "none" for children of flow layouts is a good way to go 👍

LGTM! ✨

**Comment by Mamaduka** [comment]
@tellthemachines, @andrewserong, I'm working on backports for WP 6.2.1, but can't cleanly cherry-pick this change. I believe the fix here depends on changes from #45299, which is still experimental.

How crucial is it that we ship this fix in the minor release? Can a similar fix be applied on the `wp/6.2` branch?

The WP 6.2.1-RC is [scheduled for tomorrow](https://make.wordpress.org/core/2023/05/03/wordpress-6-2-1-planning/).

**Comment by tellthemachines** [comment]
@Mamaduka that's right, this change was made on top of #45299 which is mostly a performance enhancement so it's not appropriate for a minor release. I think it's fine to leave this out of 6.2.1 though!

**Comment by Mamaduka** [comment]
Thanks for the feedback, @tellthemachines! I will remove the backport label.

File: packages/edit-post/src/components/visual-editor/index.js [hunk 2]
```diff
@@ -327,6 +328,12 @@ export default function VisualEditor( { styles } ) {
 		[ styles ]
 	);
 
+	// Add some styles for alignwide/alignfull Post Content and its children.
+	const alignCSS = `.is-root-container.alignwide { max-width: var(--wp--style--global--wide-size); margin-left: auto; margin-right: auto;}
```
Comment (youknowriad) [inline packages/edit-post/src/components/visual-editor/index.js:332]: This is so weird, I don't really understand why we need this code, any explanations?

Comment (tellthemachines) [reply packages/edit-post/src/components/visual-editor/index.js:332]: That was added to address [this comment](https://github.com/WordPress/gutenberg/pull/49565/files#r1156707168). Post Content layout in the front end is influenced by both its layout and alignment; this was an attempt make the post editor accurately reflect them.

Comment (youknowriad) [reply packages/edit-post/src/components/visual-editor/index.js:332]: So are you saying that we try to apply the "alignment" of the post content block in the post editor? For me that seems a bit random because we don't really know the layout of its parent block, maybe it's within a small sidebar, and wide there means something else. Anyway, I'm not touching that at the moment but I feel like it's just complexity for nothing.

Comment (tellthemachines) [reply packages/edit-post/src/components/visual-editor/index.js:332]: True, we're not looking at the complete nesting tree. It would be possible to grab any custom wide align value from the parent (which we're not doing) and that might make things a bit more accurate, but in terms of effort vs effect the current solution will work for the majority of cases. Many themes nest Post Content inside one or more Group blocks; even those that nest it inside Columns will most likely have it in a responsive column that takes up most of the page. Having Post Content display in a narrow column on the single post template is a very unlikely scenario.

With these layout problems there are always many variables at play: nesting structure, parent block styles, theme styles, root padding, alignments... and often no approach works for all cases; I think if there's no universal solution it's best to try for a solution that works for _most_ cases 😅
