### PR TITLE
[RNMobile] Gallery block: Fix crash when adding images and selecting a gallery item

### LINKED ISSUE #38217: Gallery block: Crash when adding images and selecting a gallery item
## Description

**Sentry ticket:** https://sentry.io/share/issue/e9deb70195184b10bf08a31afb2bce7b/

Adding images to the Gallery block and selecting an item of the gallery, produces the following error and crashes the app:
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```

**NOTE:** I spotted this issue while testing the beta version of WordPress-iOS 19.1 (19.1.0.0).

## Step-by-step reproduction instructions

1. Add a Gallery block.
2. Add images to the gallery.
3. Observe that an error is displayed.

**NOTE:** I experienced that if the editor is re-opened after getting this error, the images might have been added. However, in this case, the issue can be also reproduced by selecting any of the gallery items.

## Expected behaviour

Either adding images or selecting gallery items of the Gallery block shouldn't display errors or make the app crash.

## Actual behaviour

Either adding images or selecting gallery items of the Gallery block display an error and make the app crash.

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: Simulator - iPhone 12 Pro Max
- Operating system: iOS 15.0
- WordPress app version: `19.1` (WordPress-iOS `19.1.0.0`) and `develop` branch.

### PR DESCRIPTION
**Pull request by fluiddot**
**Gutenberg Mobile PR:** https://github.com/wordpress-mobile/gutenberg-mobile/pull/4515

## Description

Fixes https://github.com/WordPress/gutenberg/issues/38217.

After the changes introduced in https://github.com/WordPress/gutenberg/pull/38036, we spotted in the native version that the Gallery block is trying to render the component `MediaReplaceFlow` which is neither defined nor exported in native hence, this produces a crash in the editor.

For this reason, this PR introduces the following two changes:
1. **Create the native variant of the component `MediaReplaceFlow`:**
As this component is not required yet by the native version, an empty component is provided for now.

2. **Create a platform-specific set of props to be included when rendering the `MediaPlaceholder` component:**
This is required in order to keep the same behavior for the native version of the gallery block, after the changes introduced in https://github.com/WordPress/gutenberg/pull/38036.

## Testing Instructions

1. Open a post/page.
1. Add a Gallery block.
1. Add images to the gallery.
1. Observe that no error is displayed.
1. Select one of the gallery items.
1. Observe that no error is displayed. 

## Screenshots 
N/A

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [x] I've updated related schemas if appropriate.

### CODE REVIEW

File: packages/block-library/src/gallery/edit.js [hunk 1]
```diff
@@ -429,24 +429,44 @@ function GalleryEdit( props ) {
 		( img ) => ! img.id && img.url?.indexOf( 'blob:' ) === 0
 	);
 
+	// MediaPlaceholder props are different between web and native hence, we provide a platform-specific set.
+	const mediaPlaceholderProps = Platform.select( {
+		web: {
+			addToGallery: false,
+			disableMediaButtons: imagesUploading,
+			icon: sharedIcon,
+			labels: {
```
Comment (geriux) [inline packages/block-library/src/gallery/edit.js]: I think we could share for both web and native the following: `icon`, `labels` and `notices` using the `web` props values. This way we reduce some lines.

```javascript
const mediaPlaceholderProps = Platform.select( {
    web: {
        addToGallery: false,
        disableMediaButtons: imagesUploading,
        value: {},
    },
    native: {
        addToGallery: hasImageIds,
        isAppender: hasImages,
        disableMediaButtons:
            ( hasImages && ! isSelected ) || imagesUploading,
        value: hasImageIds ? images : {},
        autoOpenMediaUpload:
            ! hasImages && isSelected && wasBlockJustInserted,
    },
} );
```

File: packages/block-library/src/gallery/test/index.native.js [hunk 2]
```diff
@@ -0,0 +1,128 @@
...
+		fireEvent( innerBlockListWrapper, 'layout', {
+			nativeEvent: {
+				layout: {
+					width: 100,
+				},
+			},
+		} );
+
+		const appenderButton = await waitFor( () =>
+			within( galleryBlock ).getByA11yLabel( /false block\. Empty/ )
```
Comment (geriux) [inline packages/block-library/src/gallery/test/index.native.js]: If we update the props as I mentioned above, we'll need to update this label to: `/Gallery block\. Empty/`. It looks like it's getting `false` from the `placeholderTitle`.

**Review by geriux — COMMENTED** [review]
Hey @fluiddot 👋 thank you for working on fixing this crash. I left two comments, let me know what you think. Also thanks for introducing some tests to catch these type of issues from now on 👏 .

File: packages/block-library/src/gallery/edit.js (hunk 1 above)
Comment (fluiddot) [reply packages/block-library/src/gallery/edit.js]: Good catch! I've just checked that those props can be shared:

- `icon`, `labels`: These props are only rendered when `isAppender` is `false` or not defined (i.e. when `hasImages` is `false`), so should be safe to use the same code on both platforms.
https://github.com/WordPress/gutenberg/blob/00aea001988f2a8cbd70eeff975d0efebacf1019/packages/block-editor/src/components/media-placeholder/index.native.js#L118-L128

- `notices`: Looks like this prop is not used in the native version of the `MediaPlaceholder` component ([reference](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/media-placeholder/index.native.js)) only on the web, so it should be safe to do the same here.
https://github.com/WordPress/gutenberg/blob/00aea001988f2a8cbd70eeff975d0efebacf1019/packages/block-editor/src/components/media-placeholder/index.native.js#L35-L54
https://github.com/WordPress/gutenberg/blob/00aea001988f2a8cbd70eeff975d0efebacf1019/packages/block-editor/src/components/media-placeholder/index.js#L62

File: packages/block-library/src/gallery/test/index.native.js (hunk 2 above)
Comment (fluiddot) [reply packages/block-library/src/gallery/test/index.native.js]: Right, in fact, updating the props will make the label to be more descriptive than the text `false block` 😅 .

File: packages/block-library/src/gallery/edit.js (hunk 1 above)
Comment (fluiddot) [reply packages/block-library/src/gallery/edit.js]: I applied the suggestion in https://github.com/WordPress/gutenberg/pull/38238/commits/589d5d8fe8e9192a49bf3a64e192e52294df3e43.

File: packages/block-library/src/gallery/test/index.native.js (hunk 2 above)
Comment (fluiddot) [reply packages/block-library/src/gallery/test/index.native.js]: I updated the label query in https://github.com/WordPress/gutenberg/pull/38238/commits/589d5d8fe8e9192a49bf3a64e192e52294df3e43 due to the changes in the props.

**Comment by fluiddot** [comment]
> Hey @fluiddot 👋 thank you for working on fixing this crash. I left two comments, let me know what you think. Also thanks for introducing some tests to catch these type of issues from now on 👏 .

Thank you @geriux for reviewing the PR ❤️ !

I've just reviewed and applied the suggestions you mentioned, let me know if you could take another review, thanks 🙇.

**Review by geriux — APPROVED** [review]
LGTM! I tested this on both iOS/Android and in a local instance of Gutenberg.

**Comment by glendaviesnz** [comment]
This tested well for me on the web side and the code LGTM. What is the best way for us to minimise the chance of this sort of surprise on the mobile side in the future - should we ping some mobile team members whenever we change the gallery?

**Comment by fluiddot** [comment]
> This tested well for me on the web side and the code LGTM.

Thanks for taking a look @glendaviesnz, I really appreciate it 🙇.

> What is the best way for us to minimise the chance of this sort of surprise on the mobile side in the future - should we ping some mobile team members whenever we change the gallery?

Ideally, these issues should be identified by automatic tests (integration + e2e tests). In this case, as there was none for the Gallery block, we spotted it probably too late during the manual testing. Nevertheless, currently, we're focused on increasing the coverage of blocks, especially for preventing cases like this, so hopefully, that should help us in the future.

Regarding pinging, I see that for the Gallery block @mkevins is assigned as a code owner ([reference](https://github.com/WordPress/gutenberg/blob/71635329224c3dcc148258b7b0e855acf3b5d733/.github/CODEOWNERS#L17)), but not sure if Matthew was able to take a look. It would be great to figure out better ways to sync changes between both platforms, but in the meantime, I think pinging someone from the mobile team is a good workaround 👍 .

**Comment by mkevins** [comment]
> not sure if Matthew was able to take a look

I did get a notification for this, but I think I overlooked it as it was purple by the time I saw it :disappointed: .

> Ideally, these issues should be identified by automatic tests (integration + e2e tests).

This is definitely the way to go, imo. Also, as we continue to improve the [developer experience of building and running the mobile app](https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/react-native/getting-started-react-native.md), direct manual testing of the areas related to a PR's changes can be a great holistic way to cover these kinds of issues, and will likely help to foster the "mobile caution/awareness" upstream. I.e. the tighter that loop is, the better.

**Comment by mkevins** [comment]
> In this case, as there was none for the Gallery block

It looks like the [gallery block on-device test](https://github.com/WordPress/gutenberg/blob/1194689cc91fdcb84dabcd89d90107151f4607b6/packages/react-native-editor/__device-tests__/gutenberg-editor-gallery.test.js) is still present, but it merely adds an empty gallery block, which will only catch a limited subset of potential issues. That suite could certainly use some expansion :smile:

**Comment by fluiddot** [comment]
> It looks like the gallery block on-device test is still present, but it merely adds an empty gallery block, which will only catch a limited subset of potential issues. That suite could certainly use some expansion 😄

Certainly, we could also add integration tests to cover the block's logic and user flows.

**Comment by mkevins** [comment]
> Certainly, we could also add integration tests to cover the block's logic and user flows.

This would be fantastic! Especially now that the gallery block is in a more "stable" state from a UI perspective (i.e. using inner blocks). One of the blockers to adding such tests earlier was that the block was undergoing big changes to the UI with the format refactoring, and now that this phase is complete (more or less), integration / UI tests will help catch (and prevent) a whole class of issues before they even land.

**Comment by fluiddot** [comment]
> > Certainly, we could also add integration tests to cover the block's logic and user flows.
> 
> This would be fantastic! Especially now that the gallery block is in a more "stable" state from a UI perspective (i.e. using inner blocks). One of the blockers to adding such tests earlier was that the block was undergoing big changes to the UI with the format refactoring, and now that this phase is complete (more or less), integration / UI tests will help catch (and prevent) a whole class of issues before they even land.

@mkevins Great, thanks for sharing the context 🙇 . FYI I planned to tackle integration tests for this block, I'll let you know once I finish the PRs in case you could take a look at the user flows covered, thanks.
