### PR TITLE
Scripts: Use default value for process.env.WP_SRC_DIRECTORY

### LINKED ISSUE #44309: Scripts: regression - webpack config cannot be extended anymore
### Description

Until [this commit](https://github.com/WordPress/gutenberg/commit/f20c355c3f8667264b84e13b19d20d708bd624e2#diff-cba9f881720fd03020570ce36ae5b8dde43c14d4a1d79fa857155beb6ef578d1R41) It was possible to extend the wordpress-scripts webpack config.

This change breaks it. I was using it to compile es6 files using WordPress libraries (eg. @wordpress/api-fetch). This way I am able to control the input and output directories and filenames. It will then give me a bundle and a PHP files with scripts dependencies.

Here is a simplified example that works with version 24.0.0 and not 24.1.0: https://github.com/loxK/wordpress-scripts-test

### Step-by-step reproduction instructions

1. create a webpack config
2. extend it and export
3. use it
4. see the error:

```bash
» npm run build                               

> build
> webpack

[webpack-cli] Failed to load '/home/www/test/webpack.config.js' config
[webpack-cli] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:121:11)
    at Object.join (node:path:1172:7)
    at fromProjectRoot (/home/www/test/node_modules/@wordpress/scripts/utils/file.js:13:7)
    at hasProjectFile (/home/www/test/node_modules/@wordpress/scripts/utils/file.js:16:14)
    at getRenderPropPaths (/home/www/test/node_modules/@wordpress/scripts/utils/config.js:312:9)
    at Object.<anonymous> (/home/www/test/node_modules/@wordpress/scripts/config/webpack.config.js:41:21)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32) {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by loxK**
## What?
Fixes this regression: WordPress/gutenberg#44309

## Why?
See discussion here: https://github.com/WordPress/gutenberg/pull/43917#pullrequestreview-1113911446

## How?
Using wp-scripts command, if is not specified, `process.env.WP_SRC_DIRECTORY` defaults to string 'src'. When extending the webpack.config.js directly, it should behave the same.

### CODE REVIEW

**Review by luisherranz — COMMENTED** [review]
This looks about right to me. Thanks for the PR, Laurent 🙂

@gziolo, what do you think? Should we also centralize the default value defined on `build.js` and `start.js` so there's only a single place where the `'src'` string is defined?

File: packages/scripts/utils/config.js [hunk 1]
```diff
@@ -168,6 +168,15 @@ const getWebpackArgs = () => {
 	return webpackArgs;
 };
 
+/**
+ * Returns the webpack src directory. Will default to 'src' if not set.
+ *
+ * @return {string} the webpack src directory.
```
Comment (luisherranz) [inline packages/scripts/utils/config.js]:
```suggestion
 * Returns the WordPress source directory. It defaults to 'src' if the `process.env.WP_SRC_DIRECTORY` variable is not set.
 *
 * @return {string} The WordPress source directory.
```

```suggestion
 * Returns the WordPress source directory. It defaults to 'src' if the `process.env.WP_SRC_DIRECTORY` variable is not set.
```

**Review by luisherranz — CHANGES_REQUESTED** [review]
Oh, would you please rename the function from `getWebpackSrcDirectory` to `getWordPressSrcDirectory`? Thanks!

**Comment by loxK** [comment]
> @gziolo, what do you think? Should we also centralize the default value defined on `build.js` and `start.js` so there's only a single place where the `'src'` string is defined?

I thought about it too, but decided it was up to you.

File: packages/scripts/utils/config.js (hunk 1 above)
Comment (loxK) [reply packages/scripts/utils/config.js]: Done.

**Review by gziolo — COMMENTED** [review]
This looks good to go, @luisherranz is there anything I missed?

**Comment by luisherranz** [comment]
> @luisherranz is there anything I missed?

If you think it's good, let's merge it 🙂

**Review by luisherranz — APPROVED** [review]

**Comment by luisherranz** [comment]
Thanks for your contribution, @loxK!

**Comment by loxK** [comment]
> Thanks for your contribution, @loxK!

I appreciate but it is nothing compared to how useful is WordPress to me. Thank YOU guys.

**Comment by annezazu** [comment]
@loxK wanted to follow up - did you make a WordPress.org profile? If so, can you share the link here? For example, here's mine: https://profiles.wordpress.org/annezazu/ We'd love to gives you props in the next WordPress release but need your WordPress.org username to do so. 

You can follow the steps above to set it up correctly: https://github.com/WordPress/gutenberg/pull/44367#issuecomment-1257979289

Thank you!

**Comment by loxK** [comment]
@annezazu Here you go, thanks

https://profiles.wordpress.org/dreadlox/
