### PR TITLE
Image: Fix Lightbox display bug in Classic Themes.

### LINKED ISSUE #54682: New Lightbox with display bug in Classic Themes
### Description

Image Lightbox (expand on click) in Gutenberg 16.7.0 RC1 works as expected with Theme Twenty Twenty-Two

After changing to classic Theme Twenty Sixteen (or GeneratePress) an error occurs:
Warning: Array to string conversion in ...\wp-includes\formatting.php on line 1104

Checked:
grafik

Visual bug:
1. Image looks regular
2. on mouseover: image disappears and is replaced with a monochrome coloured area of same size
3. click on image opens lightbox as expected
4. click again closes lightbox as expected
5. image was again replaced with coloured area (even without mouseover!)
6. clicking elsewhere make image reappear like regular

### Step-by-step reproduction instructions

1. Install Gutenberg 16.7.0 RC1
2. change to theme Twenty Sixteen
3. add page/post
4. add image
5. activate "expand on click"
6. view page
7. try lightbox-efect

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WP 6.3.1
Gutenberg 16.7.0 RC1
Themes: Twenty Sixteen, GeneratePress

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by michalczaplinski**
Co-authored with @SantosGuillamot 

## What?
Fixes #54682. 

## Why?
1. In Classic Themes, the [`wp_get_global_styles()`](https://developer.wordpress.org/reference/functions/wp_get_global_styles/) call returns the whole array of all styles, instead of an individual string value. An array cannot be interpolated into HTML (on this line):

   https://github.com/WordPress/gutenberg/blob/d3986f0766e37f6cb985806f33d8e68d0e658642/packages/block-library/src/image/index.php#L286

   so it throws a warning.

2. The CSS of a theme can include styles for `button:hover` and `button:focus`. Since the Lightbox contains a `<button>` element, we want to reset those styles to avoid the ugly unwanted flashes of content. 

## How?
- Adding a `wp_is_block_theme()` check before getting the value from `wp_get_global_styles()`.
- Resetting the Image block's CSS on `button:hover` & `button:focus`.

### Before

https://github.com/WordPress/gutenberg/assets/5417266/dbd723a6-1e22-46fa-9b26-451cd9351ab5

### After 

https://github.com/WordPress/gutenberg/assets/5417266/6731f0e1-2b01-4a49-8473-6932cc46e4d8

### CODE REVIEW

**Comment by michalczaplinski** [comment]
@alexstine I'd appreciate your opinion on the accessibility implications here. It should be fine to override the theme's CSS to avoid the ugly (and presumably unwanted) highlights on hover/focus, but if you know of a better way, let me know!

**Comment by alexstine** [comment]
CC: @joedolson

**Review by t-hamano — COMMENTED** [review]
I think it's unstable to rely solely on whether it's a block theme or not. Block themes don't necessarily have background and text colors defined in `theme.json`. For example, if you enable an Emptytheme (with no colors defined in `theme.json`), the error message persists.

I think the `wp_get_global_styles()` function returns an array not depending on whether the theme is a block theme or not, but when the key does not exist in the global style.

I think we should check the return value of the `wp_get_global_styles()` function or use some other function that is more reasonable, but as far as I know of no implementation that references global styles in a core block callback function, so I would like to ping @aaronrobertshaw and @ramonjd for help 🙇

**Comment by t-hamano** [comment]
After doing some research, I think the following code might be better. `wp_get_global_styles()` is guaranteed to return an array, so the color is determined by the presence or absence of that key. There should be no errors in all themes.

```php
$global_styles        = wp_get_global_styles( array( 'color' ) );
$has_background_color = ! empty( $global_styles['background'] );
$has_text_color       = ! empty( $global_styles['text'] );
$background_color     = esc_attr( $has_background_color ? $global_styles['background'] : '#fff' );
$close_button_color   = esc_attr( $has_text_color ? $global_styles['text'] : '#000' );
```

**Review by aaronrobertshaw — COMMENTED** [review]
@t-hamano makes a [good point](https://github.com/WordPress/gutenberg/pull/54837#pullrequestreview-1653130560). Not only can block themes not have background and text colors, but we could also have a hybrid theme that uses theme.json.

Would using [`wp_theme_has_theme_json`](https://developer.wordpress.org/reference/functions/wp_theme_has_theme_json/) assist here?

Once we're checking global styles for all themes that might use theme.json, we still need to handle the edge case where background/text colors aren't set as Aki mentioned.

P.S. Could we get some test instructions on the PR description? It might help others jump into reviews here, especially for a11y feedback and people that don't have the luxury of discerning info from videos.

**Comment by SantosGuillamot** [comment]
Thanks a lot for the feedback. It totally makes sense to me. I just pushed a commit with your suggestions. I hope that's why you had in mind. Feel free to correct me I am wrong 🙂 

> P.S. Could we get some test instructions on the PR description? It might help others jump into reviews here, especially for a11y feedback and people that don't have the luxury of discerning info from videos.

Regarding this, we should always include proper testing instructions. Thanks for flagging it. I'll leave that to @michalczaplinski as he opened the pull request, but the way I was testing it was:

1. Include an Image in a page.
2. Enable the "Expand on click" functionality.

**Before this change**

* Using a classic theme, like Twenty Sixteen, the page with the image returns a warning.
* Using a block theme WITHOUT the background color and text color defined in the `theme.json`, the page returns the same warning. For that, I installed a block theme and removed the `styles.color` object manually from the `theme.json`.

**After this change**

* Using a classic theme doesn't return the error, and when expanding the image, it shows default colors (white background and black text).
* Using a block theme WITHOUT the colors defined doesn't return the error, and when expanding the image, it shows default colors (white background and black text).
* Using a block theme WITH colors defined shows the colors defined in the `theme.json` when expanding the image.
* If I change the colors through the Global Styles, those changes are applied when expanding the image.

File: packages/block-library/src/image/index.php [hunk 1]
```diff
@@ -252,10 +252,16 @@ function block_core_image_render_lightbox( $block_content, $block ) {
...
 
-	$background_color = esc_attr( wp_get_global_styles( array( 'color', 'background' ) ) );
+	// If the current theme does NOT have a `theme.json`, or the colors are not defined,
+	// we need to set the background color & close button color to some default values
+	// because we can't get them from the Global Styles.
+	$global_styles_color  = wp_get_global_styles( array( 'color' ) );
+	$has_background_color = ! empty( $global_styles_color['background'] );
+	$has_text_color       = ! empty( $global_styles_color['text'] );
+	$background_color     = esc_attr( ( wp_theme_has_theme_json() && $has_background_color ) ? $global_styles_color['background'] : '#fff' );
+	$close_button_color   = esc_attr( ( wp_theme_has_theme_json() && $has_text_color ) ? $global_styles_color['text'] : '#000' );
```
Comment (swissspidy) [inline packages/block-library/src/image/index.php]: Just call `wp_theme_has_theme_json()` once above to avoid duplicate calls

Comment (t-hamano) [reply packages/block-library/src/image/index.php]: If you don't have a `theme.json`, I think you shouldn't need to call `wp_get_global_styles()`. Furthermore, how about an approach like below to run the `wp_theme_has_theme_json()` function only once?

```php
$background_color   = '#fff';
$close_button_color = '#000';

if ( wp_theme_has_theme_json() ) {
	$global_styles_color = wp_get_global_styles( array( 'color' ) );
	if ( ! empty( $global_styles_color['background'] ) ) {
		$background_color = esc_attr( $global_styles_color['background'] );
	}
	if ( ! empty( $global_styles_color['text'] ) ) {
		$close_button_color = esc_attr( $global_styles_color['text'] );
	}
}
```

Comment (SantosGuillamot) [reply packages/block-library/src/image/index.php]: It makes sense to me! Thank you 🙂 I just updated the code with your suggestion.

Comment (t-hamano) [reply packages/block-library/src/image/index.php]: Thanks for the update, @SantosGuillamot!

If the diff I'm checking is the latest, then the five lines [here](https://github.com/WordPress/gutenberg/pull/54837/files#diff-1e4aa29ea183efda9c795271dc1acf6e8049355db104d0dca5b0ea5caf7f619cR269-R273) shouldn't be necessary 😄

**Comment by artemiomorales** [comment]
I've added a couple of style fixes that address issues in a couple of other classic themes as documented in https://github.com/WordPress/gutenberg/issues/54940

Note: While the focus ring on the close button should always appear when using a keyboard, we want to omit that style when opening the lightbox with a mouse click.

This generally works as expected, but the focus ring is erroneously showing up in Twenty Twenty One and Twenty Nineteen when using the mouse.

I mention this so we can have it on our radar, but we can likely fix that as part of a separate PR.

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for the continued iterations here 👍 

As [noted earlier](https://github.com/WordPress/gutenberg/pull/54837#discussion_r1344307720) there's some [unnecessary code](https://github.com/WordPress/gutenberg/pull/54837/files#diff-1e4aa29ea183efda9c795271dc1acf6e8049355db104d0dca5b0ea5caf7f619cR269-R273) we can remove.

With that code removed, I only encountered one issue while testing.

The recent [change](https://github.com/WordPress/gutenberg/pull/54837/commits/a544d106905a8495249ada49ca433f620b2b0779) to the button's inline styles also appears to prevent the `$close_button_color` from being applied correctly. Reverting the inline style back to `fill` applies the color on the button's inner SVG. cc/ @artemiomorales 

To replicate:
1. Activate TT4 theme
2. Appearance > Editor > Styles and select Onyx variant
3. Save changes
4. Visit page with image and lightbox and expand
5. Note the incorrect dark color for the `X`

https://github.com/WordPress/gutenberg/assets/60436221/8e71a0f7-a93c-4fcc-972c-8e0d2dac7410


Tested with the following themes:
- TT1
- TT3
- TT4
- emptytheme
- emptyhybrid

**Comment by afercia** [comment]
Just noting that in https://github.com/WordPress/gutenberg/pull/55010 I'm going to add a minimum width and height to the Close button, as the target size is really too small. I guess CSS from themes may impact also the size of the button, which should be at least around 40 by 40 pixels.

**Comment by SantosGuillamot** [comment]
I totally missed those lines 😅 Thanks for noticing! I just removed them.

> The recent [change](https://github.com/WordPress/gutenberg/pull/54837/commits/a544d106905a8495249ada49ca433f620b2b0779) to the button's inline styles also appears to prevent the $close_button_color from being applied correctly.

I confirm I can reproduce it as well. I reverted it back to use `fill` because it seems to work in both cases: It applies the text color when defined in a block theme, and it works fine in classic themes like Twenty Twenty One.

Let me know if that's correct.

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for the continued iterations here @SantosGuillamot 👍 

LGTM! Tests as advertised as well.

For posterity, it might be good to tweak the PR description so the "How" section matches the latest approach i.e. checking if the theme has a theme.json file rather than only being a block theme.

**Comment by SantosGuillamot** [comment]
Thanks for the review!

> For posterity, it might be good to tweak the PR description so the "How" section matches the latest approach i.e. checking if the theme has a theme.json file rather than only being a block theme.

That makes sense 🙂 @michalczaplinski as you opened the PR, could you handle that?

**Comment by mikachan** [comment]
I just cherry-picked this PR to the 6.4-beta3 branch to get it included in the next release: ae40d77ce0

**Comment by t-hamano** [comment]
Thanks for the great work, @SantosGuillamot!

I don't know much about the Lightbox implementation itself, but I believe it used to be called "Behaviours". And similar code that this PR fixes exists [here](https://github.com/WordPress/gutenberg/blob/8b09de4ff256f9d7ed455a66646767fe32711094/lib/block-supports/behaviors.php#L218-L223) as well.

Is this code also used in Lightbox? If so, you might want to make similar changes in your follow-up PR.

**Comment by SantosGuillamot** [comment]
> Is this code also used in Lightbox? If so, you might want to make similar changes in your follow-up PR.

If I am correct, that file is there for backward-compatibility in the Gutenberg plugin. This functionality was previously included as a "behavior" in Gutenberg, so people could have activated that. I believe the plan is to maintain it for 2 releases. Although @michalczaplinski and @artemiomorales will know better than me.

Having said that, it makes sense to me to replicate the logic there as well. Although I believe it is unlikely that there are already users with the functionality enabled and using a classic theme because this wasn't reported before.

~~I will work on a new pull request for that.~~ Thanks for noticing it 🙂 

EDIT: I looked at this I am not sure if `behaviors.php` file is called at all. It's probably better if @artemiomorales or @michalczaplinski look at it.
