### PR TITLE
Performance suite: track Time To First Byte in the front-end

### LINKED ISSUE #33645: Add frontend rendering metrics in the performance tests.
Our performance test currently tracks editor-centric metrics such as: editor loading time, editor typing time, time to select a block, time to open the inserter, time to hover an element on the inserter. While we did a number of iterations and improvements to the frontend rendering of Gutenberg, we don't have a metric to track. It would be a great addition to our performance numbers. 

## Tasks

_V1: the MVP is having visibility in what happens in the server and the browser._

While tracking the time spent in the server is useful, it doesn't directly correlate to user-perceived performance. We need to track client metrics as well. For example, WordPress processes the post to render, so it can identify the blocks in use. With that information, it enqueues only the CSS of those blocks instead of the CSS of the whole block library. This certainly takes more time in the server, though we expect it to improve the perceived performance by the user. If we only tracked server metrics, they'd report this behavior as a regression, and we'd lack tools to understand how it impacted the actual user-perceived performance.

- [x] [#47442](https://github.com/WordPress/gutenberg/pull/47442) Log front-end metrics in codehealth.
- [x] [#47037](https://github.com/WordPress/gutenberg/pull/47037) Add support for [Time To First Byte](https://web.dev/ttfb/). Tells us the time it takes the server to render something.
- [x] [#47938](https://github.com/WordPress/gutenberg/pull/47938) Add support for [Largest Contentful Paint](https://web.dev/lcp/). Tell us the time it takes to render a meaningful part of the page in the client.
- [x] [#48288](https://github.com/WordPress/gutenberg/pull/48288/files) Add support for a new metric, LCP-TTFB, so we have a better sense of how certain changes impact the rendering in the browser.

Later:

- [ ] Content: add images and other meaningful elements to the homepage template, so LCP metric can catch regressions on those areas. For awareness, core is in the process of tracking this front-end metrics as well. See https://core.trac.wordpress.org/ticket/57687 They plan to use the theme test data https://github.com/WPTT/theme-test-data
- [ ] Content: in addition to track the homepage, track a single large post template as well.
- [ ] Metrics: use the [server-timing API](https://w3c.github.io/server-timing/) to measure WordPress specific metrics. [See example](https://gist.github.com/felixarntz/de5c697a1a16c2b892634b70216eb6c7).
- [ ] Metrics: add support for [First Contentful Paint](https://web.dev/fcp/). Tells us the time it takes to render some part of the page in the client.
- [ ] Runtime: consider using the latest WordPress (nightly?) so we report the latest. The runtime is now the older WordPress that Gutenberg supports, so it lacks many improvements.
- [ ] Runtime: consider improving how some Gutenberg code is hooked into core, so it's faster. For example, add short-circuit hooks to certain global styles code (e.g.: `wp_get_global_settings`) so it's "hookable" by Gutenberg. By doing this sort of changes, the logic will run only once.

### PR DESCRIPTION
**Pull request by oandregal**
closes https://github.com/WordPress/gutenberg/issues/33645

## What?

This PR aims to add the basic structure to have performance tests executed for the front-end, in addition to the existing test for post & site editor.

## Why?

By defining some measures and track them over time, regressions will be caught up earlier in the cycle and there will be clarity about the impact of any given PR.

## How?

The test measures two themes: TwentyTwentyOne as a classic theme and TwentyTwentyThree as a block theme. It loads the homepage of each with no posts. These gives use a baseline. In follow-ups, we can add more tests (load a specific post, etc.).

It reports the [Time To First Byte](https://web.dev/ttfb/), defined as the time it took since the browser requested the resource until the response started. It's reported as a median and as the 75th percentile.

## Testing Instructions

Verify that the results for front-end test suite are reported in the Performance Test job:

image

## TODO

- [x] Define the test to run. Load the homepage for pinned versions of 2021 (classic theme) and 2023 (block theme).
- [x] Verify config values for env: WP_DEBUG, SCRIPT_DEBUG, etc.
- [x] Create the JSON file with the results.
- [x] Show those results in the existing reporting mechanism.

## Follow ups

- Test a post page with dedicated content.
- Make it visible in [codehealth](https://codehealth.vercel.app/).
- While tracking TTFB is useful, we need more granularity to know how the WordPress request lifecycle is affected by code changes. We can leverage the [Server-Timing API](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing) to expose some server-side statistics in the client and track them via the existing tooling. For inspiration, we can look at incorporating something like [this script](https://gist.github.com/felixarntz/de5c697a1a16c2b892634b70216eb6c7).

### CODE REVIEW

**Comment by oandregal** [comment]
> Define the test to run.

**What page to load?** I don't have a strong opinion. How a given template is set up or what template do we load would affect the test, though. In my PRs, I've been testing by loading a "Hello World" post using TwentyTwentyThree (block theme with `theme.json`) and TwentyTwenty (classic theme without `theme.json`). Any other ideas?

**Who visits the page?** I think we should test a logged-out user, as that's the real use case we want to improve (most of the visits to a given site are by logged-out users).

File: bin/plugin/commands/performance.js [hunk 1]
```diff
@@ -118,11 +120,18 @@ function formatTime( number ) {
...
  * Curate the raw performance results.
  *
+ * @param {string} testSuite
  * @param {WPRawPerformanceResults} results
  *
  * @return {WPPerformanceResults} Curated Performance results.
  */
-function curateResults( results ) {
+function curateResults( testSuite, results ) {
+	if ( testSuite === 'front-end' ) {
```
Comment (oandregal) [inline bin/plugin/commands/performance.js]: The `WPPerformanceResults` and `WPRawPerformanceResults` data structures expect the results to be the same shape. The front-end metrics will be different from the editor ones, so this will no longer be true. I'm not very keen of stretching it this way, though it's simple and works. See https://github.com/WordPress/gutenberg/pull/47037/commits/c647035739fdc51cf1d8559ebc98f1a9a5fd49d9

An alternative I considered was to make the tests themselves return a single value. The test would be responsible for curating the value it wants to report, not the performance command. I'm tempted to do it. The only benefit of having an array of values here would be to aggregate them all across the different runs, which is something we don't do at the moment anyway. FWIW, we only do 1 run at the moment (though we did 3 in the past).

File: bin/plugin/commands/performance.js [hunk 2]
```diff
@@ -379,78 +388,25 @@ async function runPerformanceTests( branches, options ) {
...
-					minListViewOpen: rawResults.map(
-						( r ) => r[ branch ].minListViewOpen
-					),
-					maxListViewOpen: rawResults.map(
-						( r ) => r[ branch ].maxListViewOpen
-					),
-				},
-				median
-			);
+			/**
```
Comment (oandregal) [inline bin/plugin/commands/performance.js:414]: This change is just a way of making the command independent from the test suite data points. https://github.com/WordPress/gutenberg/pull/47037/commits/859e45394ba2f283fc61877816b8ab87a52b3651

File: bin/plugin/commands/performance.js (hunk 1 above)
Comment (oandregal) [reply bin/plugin/commands/performance.js]: Another advantage of asking the test to curate the results themselves is that adding a new metric doesn't involve modifying the performance command, only the test itself.

File: packages/e2e-tests/specs/performance/front-end-twentytwentythree.test.js [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+ */
+import { basename, join } from 'path';
+import { writeFileSync } from 'fs';
+
+/**
+ * WordPress dependencies
+ */
+import { activateTheme, createURL, logout } from '@wordpress/e2e-test-utils';
+
+describe( 'Front End Performance', () => {
```
Comment (oandregal) [inline packages/e2e-tests/specs/performance/front-end-twentytwentythree.test.js]: Adding separate files per theme makes it simple with the way the performance report is set up.

I considered an alternative: having a single test for all themes and keys such as `timeToFirstByteTT1`, `timeToFirstByteTT3`, etc. That could also work. The performance command could even have some code to extract those keys into separate tables. However, at that point, the performance command is not independent from the actual tests and data. I thought the current approach was simpler to understand and navigate.

File: packages/e2e-tests/specs/performance/front-end-twentytwentythree.test.js [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+	it( 'Time To First Byte (TTFB)', async () => {
+		let i = 10;
+		while ( i-- ) {
+			await page.goto( createURL( '/' ) );
+			const navigationTimingJson = await page.evaluate( () =>
+				JSON.stringify( performance.getEntriesByType( 'navigation' ) )
+			);
+			const [ navigationTiming ] = JSON.parse( navigationTimingJson );
+			results.timeToFirstByte.push(
+				navigationTiming.responseStart - navigationTiming.requestStart
```
Comment (kevin940726) [inline packages/e2e-tests/specs/performance/front-end-twentytwentythree.test.js]: TTFB, by [definition](https://web.dev/ttfb/), is the time from `startTime` to `responseStart`. I guess we can just do `responseStart` here? Or should we use a different metric or a different name?

Comment (kevin940726) [reply packages/e2e-tests/specs/performance/front-end-twentytwentythree.test.js:40]: Update: We should change the name to something like `requestTime`. And maybe also include TTFB additionally if needed.

Comment (kevin940726) [reply packages/e2e-tests/specs/performance/front-end-twentytwentythree.test.js]: Update: We should change the name to something like `requestTime`. And maybe also include TTFB additionally if needed.

**Comment by kevin940726** [comment]
Some updates on what we could do next:

1. We should rename the currently incorrectly named TTFB to something like `serverResponse` or `requestTime`. We can also still collect TTFB additionally though.
2. We should also test the post page. We might want to create a dedicated post for this test in the future. How long or complicated the post should be is still undecided yet though.
3. We would want to pin the theme to a specific version so that future releases won't affect the data we collect. One idea is to fetch the themes on CI with a certain version hash.

File: packages/e2e-tests/specs/performance/front-end-twentytwentythree.test.js [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+		await activateTheme( 'twentytwentyone' );
+		const resultsFilename = basename( __filename, '.js' ) + '.results.json';
+		writeFileSync(
+			join( __dirname, resultsFilename ),
+			JSON.stringify( results, null, 2 )
+		);
+	} );
+
+	it( 'Time To First Byte (TTFB)', async () => {
+		let i = 10;
```
Comment (kevin940726) [inline packages/e2e-tests/specs/performance/front-end-twentytwentythree.test.js]: Any reason why we're testing it 10 times here but only 5 times in TT1?

File: bin/plugin/commands/performance.js [hunk 6]
```diff
@@ -344,7 +356,12 @@ async function runPerformanceTests( branches, options ) {
 	// 4- Running the tests.
 	log( '\n>> Running the tests' );
 
-	const testSuites = [ 'post-editor', 'site-editor' ];
+	const testSuites = [
+		'post-editor',
+		'site-editor',
+		'front-end-twentytwentyone',
+		'front-end-twentytwentythree',
```
Comment (kevin940726) [inline bin/plugin/commands/performance.js]: I wonder if it makes sense to change these names into more semantic ones. Like `front-end-classic-theme` and `front-end-block-theme`?

**Comment by mikachan** [comment]
> We would want to pin the theme to a specific version so that future releases won't affect the data we collect. One idea is to fetch the themes on CI with a certain version hash.

I've attempted this in https://github.com/WordPress/gutenberg/pull/47037/commits/dfbff0290d5fe183cf595a50613763e31f3a98ee, waiting for the tests to run to see if this works...

**Comment by oandregal** [comment]
> We should rename the currently incorrectly named TTFB to something like serverResponse or requestTime. We can also still collect TTFB additionally though.

Pushed changes to clarify this: it reports the TTFB as median and as 75th percentile.

I'd be interested in adding specific timings for the server, that's why I thought of using responseStart-requestStart. However, it sounds like using an approach [like this](https://gist.github.com/felixarntz/de5c697a1a16c2b892634b70216eb6c7) could be more interesting, and it'll help us to add more WordPress specific hooks as desired. So thought we should stick to TTFB for the moment.

File: packages/e2e-tests/specs/performance/front-end-twentytwentythree.test.js (hunk 5 above)
Comment (oandregal) [reply packages/e2e-tests/specs/performance/front-end-twentytwentythree.test.js]: Thanks for the catch! Modified both to use 16 runs. The reason for choosing 16 is that calculating the 75th percentile means that we discard the 4 worse results, which gives us some room for avoiding out of the ordinary platform-specific numbers. 12 could also do: 9 is the 75th percentile, so we'd discard the worse 3 results.

File: packages/e2e-tests/specs/performance/front-end-twentytwentythree.test.js (hunk 4 above)
Comment (oandregal) [reply packages/e2e-tests/specs/performance/front-end-twentytwentythree.test.js]: https://github.com/WordPress/gutenberg/pull/47037#issuecomment-1404101794

**Comment by oandregal** [comment]
>  Verify config values for env: WP_DEBUG, SCRIPT_DEBUG, etc.

Where can I find the wp-env configuration for CI? I want to make sure the values we use for those variables in this test and production like (false, essentially).

**Comment by oandregal** [comment]
> We should also test the post page. We might want to create a dedicated post for this test in the future. How long or complicated the post should be is still undecided yet though.

I'm interested in shipping a first version of this test. We can do this in a follow-up.

File: .github/workflows/performance.yml [hunk 7]
```diff
@@ -33,6 +33,13 @@ jobs:
               run: |
                   npm ci
 
+            - name: Install specific versions of the themes used in tests
+              run: |
+                  npm run wp-env start
+                  npm run wp-env -- run tests-cli "wp theme update twentytwentyone --version=1.7"
+                  npm run wp-env -- run tests-cli "wp theme update twentytwentythree --version=1.0"
```
Comment (youknowriad) [inline .github/workflows/performance.yml:40]: Will these downgrade the theme if it has a more recent version?

**Review by youknowriad — APPROVED** [review]

File: .github/workflows/performance.yml (hunk 7 above)
Comment (mikachan) [reply .github/workflows/performance.yml:40]: Yes, the idea was to keep the theme version consistent across the tests so the themes couldn't influence the results. It's unlikely, but I think it's still good to keep things as consistent as possible.

Comment (oandregal) [reply .github/workflows/performance.yml:40]: Yeah. The rationale for this is to be able to control the environment so that only the Gutenberg PR affects the metrics. At some point, we should manually update the themes, but at least this will be an intentional change and won't affect any unrelated PR.

**Comment by mikachan** [comment]
> Where can I find the wp-env configuration for CI?

If they're not being modified anywhere, I assume we're using the default values, which are described [here in the docs](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/#default-wp-config-values). It looks like they're set to true on the development instance, and false on the test instance.

**Review by mikachan — APPROVED** [review]

File: packages/e2e-tests/specs/performance/front-end-block-theme.test.js [hunk 8]
```diff
@@ -0,0 +1,47 @@
...
+		// We derive the 75th percentile of the TTFB based on these results.
+		// By running it 16 times, the percentile value would be (75/100)*16=12,
+		// meaning that we discard the worst 4 values.
+		let i = 16;
+		while ( i-- ) {
+			await page.goto( createURL( '/' ) );
+			const navigationTimingJson = await page.evaluate( () =>
+				JSON.stringify( performance.getEntriesByType( 'navigation' ) )
+			);
+			const [ navigationTiming ] = JSON.parse( navigationTimingJson );
```
Comment (kevin940726) [inline packages/e2e-tests/specs/performance/front-end-block-theme.test.js:41]: Nit:

`evaluate` should automatically serialize/deserialize JSON data, so we should be able to just do:

```js
const [ navigationTimeing ] = await page.evaluate( () =>
  performance.getEntriesByType( 'navigation' )
);
```

In addition, we already have some performance utils available, and this probably belongs in the `getLoadingDurations` util. WDYT?

Comment (oandregal) [reply packages/e2e-tests/specs/performance/front-end-block-theme.test.js:41]: :+1:

Comment (oandregal) [reply packages/e2e-tests/specs/performance/front-end-block-theme.test.js:41]: https://github.com/WordPress/gutenberg/pull/47541

**Comment by oandregal** [comment]
Follow-up for LCP at https://github.com/WordPress/gutenberg/pull/47938
