### PR TITLE
Fix metabox reordering

### LINKED ISSUE #30071: Meta box reordering does not save in user preferences
## Description
Originally reported as [WP#52818](https://core.trac.wordpress.org/ticket/52818) by wordpress.org user [terraling](https://profiles.wordpress.org/terraling/)

> Post edit screens with metaboxes allow for drag and drop re-ordering.
> 
> This worked up to WordPress 5.6.2, but stopped working in WP 5.7, though it continues to work if you use the Classic Editor to edit posts rather than the block editor.
> 
> When re-ordering the metaboxes, an ajax update with the action 'meta-box-order' occurs, and this reports a succesful response both in the working and non-working cases, so it appears as if updating the metabox order works.
> 
> But, when the page is reloaded, the metaboxes are displayed in an unchanged order.

At the moment this is on the WP 5.7.1 milestone but please let me know if this isn't possible.

## Step-by-step reproduction instructions
1. Create a legacy meta box with this code in a plugin https://gist.github.com/peterwilsoncc/65e80a277a1ac1d1d700502638d80fb3
2. Create a new post
3. Enable the custom fields panel
3. You should see two meta boxes at the bottom of the screen
4. Reordeer the two meta boxes, either by dragging and dropping or clicking the buttons
5. Refresh the editor
6. Observe the two meta boxes are not showing in the user's selected order.

## Expected behaviour

At the final step the order should reflect the user's preferences.

## Actual behaviour

The order of meta boxes is reset to the default WP order each time the editor is loaded.

@desrosj has determined that the `page` parameter is been left off the AJAX request to the admin-ajax action `meta-box-order`. 

A git bisect shows it was apparently introduced in this package update during the WP 5.7 cycle https://github.com/WordPress/wordpress-develop/commit/bc405697b025841c0b897f4248ee78ae9f9baf5c.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/519727/111938237-a85e5900-8b1d-11eb-8419-763af20c28e0.mov

## WordPress information
- WordPress version: 5.7.0
- Gutenberg version: latest (built from 49c6fb99edd685db0cc63bafb5a884c87a0ef141 )
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, TT1

## Device information
- Device: Desktop
- Operating system: macOS 11.2.1
- Browser: Firefox Developer Edition 87

### PR DESCRIPTION
**Pull request by ribaricplusplus**
## Description
Fixes #30071

**Important**: This PR also includes changes to WordPress core. I will submit those here: https://core.trac.wordpress.org/ticket/52818

Cause of issue:

postboxes.js wp-admin script [(this one)](https://github.com/WordPress/WordPress/blob/master/wp-admin/js/postbox.js), which is responsible for saving meta box order, is initialized by `setAvailableMetaBoxesPerLocation` here:

https://github.com/WordPress/gutenberg/blob/8aa446b4e6845c91c10e1fb35a23ee44c257200b/packages/edit-post/src/store/actions.js#L279-L281

However, that function is called from `post.php`, here:

https://github.com/WordPress/WordPress/blob/57da3e781320dd62e3016624b310c23447d9e6d1/wp-admin/includes/post.php#L2379-L2381

But at that point the editor is not yet fully initialized because `setupEditor` action didn't run yet. So `postType` is still null, postboxes becomes initialized incorrectly (with null instead of proper post type), and then when reordering happens the reordered metaboxes are saved incorrectly.

## How has this been tested?
Manually. Try changing metabox order. Steps to reproduce are given in the linked issue.

## Types of changes
Bug fix

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 

I'm not sure if anything needs to be changed for React Native:

- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by peterwilsoncc — COMMENTED** [review]
Confirmed this fixes the bug with some manual testing. Also checked the `postType` is passed as a string on `trunk` with some well placed `console.log`s and that is the case too.

File: packages/edit-post/src/editor.js [hunk 1]
```diff
@@ -102,6 +106,7 @@ function Editor( {
 					? getEditedPostTemplate()
 					: null,
 			post: postObject,
+			isEditorReady: __unstableIsEditorReady(),
```
Comment (peterwilsoncc) [inline packages/edit-post/src/editor.js]: Reading the coding standards and wondering if this should be returned with the `__unstable` prefix too. 

What am I missing? This is mainly for my own education rather than an opinion either way :)

Comment (ribaricplusplus) [reply packages/edit-post/src/editor.js]: I was following the style established elsewhere in the code where `__unstable` and `__experimental` is often removed, for example here:

https://github.com/WordPress/gutenberg/blob/04c7c760dc480ae2d2eae295ca5bab6c766d31a9/packages/edit-post/src/components/layout/index.js#L17-L25

Also, if I'm not mistaken, it seems that the `__unstable` and `__experimental` prefix is there for people using Gutenberg packages in their projects, so it's important not to document these functions and tell people to use them and so forth. Here it's just used locally and not exported anywhere.

That's just my reasoning for renaming it, but I'll put the `__unstable` prefix back if you think that would be better.

**Comment by paaljoachim** [comment]
I believe this PR could use some additional eyes...
@mcsf @ockham @youknowriad

**Comment by youknowriad** [comment]
Hi there! thanks for the fix here, it seems to me that the current way this call is handled could be improved, and this is highlighted by the issue being fixed here.

In other words and to avoid any timing issues in the future, what about a solution like this:

 1- Remove the promise from here https://github.com/WordPress/WordPress/blob/57da3e781320dd62e3016624b310c23447d9e6d1/wp-admin/includes/post.php#L2379-L2381 and just call `setAvailableMetaBoxesPerLocation` action synchronously.

 2- Split the `setAvailableMetaBoxesPerLocation` action creator to two separate action steps:
   a- one that sets the state in the store (saves the active meta boxes)
   b- one that triggers the post box script and also enables the meta boxes saving: all this code https://github.com/WordPress/gutenberg/blob/8aa446b4e6845c91c10e1fb35a23ee44c257200b/packages/edit-post/src/store/actions.js#L275-L322
   c- when setting the metaboxes, only call the second part if the editor is ready 

 3- Add an effect somewhere in the `MetaBoxes` component that monitors `__unstableIsEditorReady` and calls the action defined in **b** above when the flag is set to true.

The main reason I'm suggesting this is to make the code less dependent on the timing of the actions being called. Does that sound like a better solution?

**Comment by paaljoachim** [comment]
Associated PR:
Allow moving metaboxes to previously empty area
https://github.com/WordPress/gutenberg/pull/25187

**Comment by ribaricplusplus** [comment]
Thank you for the review @youknowriad.

Your suggestions sound good. However, I realized that I will not be able to invest time into this PR for at least a month. Just wanted to let you know. If it's still relevant when I can invest time in it, I'll do it.

**Comment by desrosj** [comment]
Hey @ribaricplusplus, just wanted to see if you had some time that freed up to revise this PR. I'd love to wrap this one up and get it shipped in a 5.8.x release of WordPress.

**Comment by rodrigo-arias** [comment]
Hi, I'm having a similar issue with ACF that I think has the same origin. After inserting a taxonomy I cannot open the meta boxes. The error doesn't happen in WP 5.6.x

CleanShot 2021-07-28 at 16 53 17

I've seen a similar report here: https://core.trac.wordpress.org/ticket/52818

CleanShot 2021-07-28 at 16 34 56@2x

It would be great if you could have this fix for the next minor version as right now it is hard to use the block editor since WP 5.7 with this bug.

Thank you

**Comment by ribaricplusplus** [comment]
I haven't forgotten about this, but finding time is a struggle!

I'll update you in the next few days about when I'll be able to work on this.

**Comment by ribaricplusplus** [comment]
I'll try to do it mid September.

**Comment by ribaricplusplus** [comment]
@youknowriad Hey. I've made the changes as you proposed, the patch to WordPress core is here: https://core.trac.wordpress.org/ticket/52818

Please review this again and let me know if something still needs to be changed.

File: packages/edit-post/src/components/meta-boxes/index.js [hunk 2]
```diff
@@ -15,7 +17,70 @@ import MetaBoxesArea from './meta-boxes-area';
...
+				isReady: __unstableIsEditorReady(),
+				metaBoxes: getMetaBoxesPerLocation( location ),
+				isVisible: isMetaBoxLocationVisible( location ),
+				postType: getCurrentPostType(),
+			};
+		}
+	);
+	const { isSavingPost, isAutosavingPost } = useSelect( editorStore );
+	const { hasMetaBoxes } = useSelect( editPostStore );
+	const [ initialized, setInitialized ] = useState( false );
```
Comment (youknowriad) [inline packages/edit-post/src/components/meta-boxes/index.js]: Potentially this could be just a `useRef` to avoid rerendering the component when it changes value (since it's only important for effects)

File: packages/edit-post/src/components/meta-boxes/index.js [hunk 3]
```diff
@@ -6,7 +6,9 @@ import { map } from 'lodash';
 /**
  * WordPress dependencies
  */
-import { withSelect } from '@wordpress/data';
+import { useSelect, subscribe, dispatch } from '@wordpress/data';
```
Comment (youknowriad) [inline packages/edit-post/src/components/meta-boxes/index.js]: Instead of using the global `subscribe` and `dispatch` here, can we do a small refactoring and use `useRegistry` instead to retrieve the current registry and use `registry.subscribe` and `registry.dispatch`?

File: packages/edit-post/src/components/meta-boxes/index.js [hunk 4]
```diff
@@ -15,7 +17,70 @@ import MetaBoxesArea from './meta-boxes-area';
...
+				getMetaBoxesPerLocation,
+			} = select( editPostStore );
+			return {
+				isReady: __unstableIsEditorReady(),
+				metaBoxes: getMetaBoxesPerLocation( location ),
+				isVisible: isMetaBoxLocationVisible( location ),
+				postType: getCurrentPostType(),
+			};
+		}
+	);
```
Comment (youknowriad) [inline packages/edit-post/src/components/meta-boxes/index.js:43]: You should add an array of dependencies to useSelect `[ location ]` to only recompute if location changes (instead of each render)

**Review by youknowriad — COMMENTED** [review]
This is looking very good to me, I'd appreciate some testing from folks relying on meta boxes a bit. 

I assume this works even without the Core patch right (as we're supposed to support existing and previous WP versions in the Gutenberg plugin)

File: packages/edit-post/src/components/meta-boxes/index.js (hunk 2 above)
Comment (ribaricplusplus) [reply packages/edit-post/src/components/meta-boxes/index.js]: Great suggestion, thanks.

**Comment by ribaricplusplus** [comment]
> I assume this works even without the Core patch right

@youknowriad  Yes.

>  I'd appreciate some testing from folks relying on meta boxes a bit.

@desrosj Can you mention anyone who could potentially do some testing?

**Comment by ribaricplusplus** [comment]
@youknowriad I just realized that my previous solution was actually not good because the `MetaBoxes` component is created multiple times for different values of the `location` parameter. So the effect that initializes meta boxes would also run multiple times.

Now I extracted the meta box initializing logic into a separate action on the `edit-post` store.

File: packages/edit-post/src/store/selectors.js [hunk 5]
```diff
@@ -367,6 +367,17 @@ export function isEditingTemplate( state ) {
...
 }
 
+/**
+ * Returns true if meta boxes are initialized.
+ *
+ * @param {Object} state Global application state.
+ *
+ * @return {boolean} Whether meta boxes are initialized.
+ */
+export function metaBoxesInitialized( state ) {
```
Comment (youknowriad) [inline packages/edit-post/src/store/selectors.js]: Can we maybe rename this one  `areMetaBoxesInitialized`, `hasInitializedMetaboxes` or something like that to match the naming scheme of the other selectors?

**Review by youknowriad — COMMENTED** [review]
Still looking good. Good point on the extraction to an action + isInitialized check.

File: packages/edit-post/src/store/selectors.js (hunk 5 above)
Comment (ribaricplusplus) [reply packages/edit-post/src/store/selectors.js]: Done

**Review by youknowriad — APPROVED** [review]

**Comment by youknowriad** [comment]
Thanks for your work and persistence here :)

**Comment by dariaknl** [comment]
Tested on a last [checkout from trunk](https://github.com/WordPress/gutenberg/commit/796d25c34cdf26d1dd788eb174b18a1b282770d2): the re-ordering bug from the original issue is not reproduced. Re-ordering is kept after updating the post.
