### PR TITLE
Editor: Save post after deletion so that its status is refreshed and redirection happens.

### LINKED ISSUE #17426: "Move to Trash" fails to redirect to posts page
**Describe the bug**
"Move to Trash" trashes a post but doesn't redirect to the posts page.

**To reproduce**
- tested on latest WP trunk 5.3 alpha
- activate Gutenberg plugin, current version: 6.4.0 9a1e33e823295c694d20ca3cbe0953ae3695c59f
- create a new post
- enter a title and add a paragraph just to have some content
- either save as draft or publish
- click "Move to Trash" in the Document sidebar
- nothing happens (visually)
- click again "Move to Trash"
- see the error notice informing you the post is already trashed

Screenshot 2019-09-13 at 14 33 42

Git bisect tells me 4944315cac156c78313121657dff9d58ce8f4d3f is the first bad commit, see #16932 (huge PR to update the store to use Core Data entities) /Cc @epiqueras @youknowriad

### PR DESCRIPTION
**Pull request by epiqueras**
Fixes #17426

## Description

This PR fixes the issue described in #17426.

## How has this been tested?

It was verified that moving a post to the trash works as expected.

## Types of Changes

*Bug Fix:* Redirect users after moving a post to the trash.

## Checklist:

- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/editor/src/store/actions.js [hunk 1]
```diff
@@ -493,12 +493,9 @@ export function* trashPost() {
 			}
 		);
 
-		// TODO: This should be an updatePost action (updating subsets of post
-		// properties), but right now editPost is tied with change detection.
 		yield dispatch(
 			STORE_KEY,
-			'resetPost',
-			{ ...post, status: 'trash' }
+			'savePost'
```
Comment (mcsf) [inline packages/editor/src/store/actions.js]: What does it mean to save a deleted post? My first impression is that we're abusing action creators a little in order to get a result not intended from them.

My second note is that the outbound comment mentions that `editPost` isn't used because of its ties to change detection, while `savePost` itself dispatches `editPost`.

Comment (epiqueras) [reply packages/editor/src/store/actions.js]: >What does it mean to save a deleted post? My first impression is that we're abusing action creators a little in order to get a result not intended from them.

It saves and refetches the post, getting the new status.

>My second note is that the outbound comment mentions that editPost isn't used because of its ties to change detection, while savePost itself dispatches editPost.

I can't think of any issues it could cause.

**Review by mcsf — APPROVED** [review]

**Comment by aduth** [comment]
In my testing, "Move to Trash" still doesn't complete a redirect, at least not without first prompting the user there are unsaved changes. #18269 is partly related here, though it applies to non-metabox scenarios. I worry also that we try to save all changes, when it's the case that the REST API may reject some of those pending changes (evidenced by the error message in #18269 about editing trashed posts).

When I run `wp.data.select( 'core/editor' ).getPostEdits()` after seeing the prompt for redirecting, it always seems to return an object with the `blocks` value, regardless of whether I've made any changes to the post or its content.

**Comment by epiqueras** [comment]
>In my testing, "Move to Trash" still doesn't complete a redirect, at least not without first prompting the user there are unsaved changes. #18269 is partly related here, though it applies to non-metabox scenarios. I worry also that we try to save all changes, when it's the case that the REST API may reject some of those pending changes (evidenced by the error message in #18269 about editing trashed posts).

It was a nasty race condition. Fixed and explained here: #18275.

>When I run wp.data.select( 'core/editor' ).getPostEdits() after seeing the prompt for redirecting, it always seems to return an object with the blocks value, regardless of whether I've made any changes to the post or its content. Could this stem from some of the recent refactoring? (#16932)

That's expected, `blocks` are a transient edit and are not part of change detection.
