### PR TITLE
Avatar: Fix application of borders

### LINKED ISSUE #47408: Avatar border has stopped working on the front
### Description

In WordPress 6.2 alpha, with or without Gutenberg 15.0 or Gutenberg trunk active, the avatar border works in the block editor but not on the front.
This is a regression from WordPress 6.0 and 6.1.

Note that the border still works well with 6.1.1 and Gutenberg trunk, so maybe it is only an incomplete backport somewhere.

On the front, only the border radius is applied. The border style, color and width are also not in the style attribute. The wrapper is missing `has-border-color`  and `has-color-name-border-color` CSS classes.

### Step-by-step reproduction instructions

Using WordPress 6.2 alpha,
Create a new post and add an avatar block.
Adjust the border settings.
Save and view the post on the front.
Compare the results and confirm that the border works in the editor but not the front.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Fixes: https://github.com/WordPress/gutenberg/issues/47408

## What?

Ensures border classes and styles are correctly applied to the avatar block's markup.

_Note: The original issue notes this as an issue for classic themes however it should be a problem for block themes as well._ 

## Why?

The avatar block adopts border supports and skips the serialization of the support classes and styles so they can be applied to an inner image element. Given the block skips serialization it must handle the application of all border configurations and it is currently missing the handling of split or "individual" borders.

## How?
- Replaces the ad-hoc class and style generation with an approach leveraging the style engine
- Creates a helper function for the Avatar block to generate the classes and styles for border support, then leverages that.
- Adds a `box-sizing: border-box` reset to the block's `img` element so borders don't break out of the avatar's sizing.

## Testing Instructions

1. Edit a post, adding an avatar block
2. Selec the block and configure a flat border (i.e. uniform width, color, and style) for all sides
3. Save the post and confirm the correct styles on the frontend
4. Back in the editor, tweak the border styles so they are different per side.
5. Save and verify the individual split borders are reflected correctly on the frontend.
6. Switch back to the editor and toggle on the block's "Link to user profile" option
7. Save and confirm borders are applied correctly still. Repeat for the flat borders.

## Screenshots or screencast 

| Classic Theme (TwentyTwenty) | Block Theme (TwentyTwentyThree) |
|---|---|
| <video src="https://user-images.githubusercontent.com/60436221/215984731-2043d13f-e584-4494-bc23-d3db40dfbd1f.mp4" /> | <video src="https://user-images.githubusercontent.com/60436221/215986192-76ef7e6c-8895-47a3-8e08-4e2df4120d59.mp4" /> |

### CODE REVIEW

**Review by carolinan — APPROVED** [review]
Thank you for taking the time to test this so thoroughly and submitting the fix 🦸 

It works well for me.
For anyone testing Twenty Twenty, you must set a border style, but it is a theme issue.

File: packages/block-library/src/avatar/index.php [hunk 1]
```diff
@@ -16,67 +16,14 @@
...
-		$image_classes .= 'has-border-color';
-	}
-	if ( isset( $attributes['borderColor'] ) ) {
-		$image_classes .= ' has-' . $attributes['borderColor'] . '-border-color';
-	}
+	$image_classes = ! empty( $border_attributes['class'] )
+		? "wp-block-avatar__image {$border_attributes['class']}"
+		: 'wp-block-avatar__image';
+	$image_styles  = ! empty( $border_attributes['style'] )
+		? sprintf( ' style="%s"', safecss_filter_attr( $border_attributes['style'] ) )
```
Comment (andrewserong) [inline packages/block-library/src/avatar/index.php]: The style engine already filters attributes, so I don't think we need the `safecss_filter_attr` call here?

To dig in, `wp_style_engine_get_styles` calls compile_css [here](https://github.com/WordPress/gutenberg/blob/8c79d908ac4ea5775a9f3c34e67442215a69b630/packages/style-engine/style-engine.php#L57), which [then calls](https://github.com/WordPress/gutenberg/blob/758372afab62b8665277776d860f5acf5da3c41b/packages/style-engine/class-wp-style-engine.php#L538) [`get_declarations_string`](https://github.com/WordPress/gutenberg/blob/388e5d23e327e13b7e88f60268b99d89e761bf79/packages/style-engine/class-wp-style-engine-css-declarations.php#L174) which calls [`filter_declaration`](https://github.com/WordPress/gutenberg/blob/388e5d23e327e13b7e88f60268b99d89e761bf79/packages/style-engine/class-wp-style-engine-css-declarations.php#L141), so it should already be filtered.

**Review by andrewserong — APPROVED** [review]
Nice one, logic looks good and this is testing well for me:

✅ Avatar block with uniform sides is output correctly in post editor and on site frontend
✅ Avatar block with non-uniform sides is output correctly in post editor and on site frontend
✅ Tested in a blocks-theme and with TwentyTwenty theme with appearance tools enabled

Only issue I noticed is that I think there's a no-longer-needed call to safecss_filter_attr, but other than that this LGTM ✨  — good idea splitting the logic into a separate utility function, it helps the readability 👍

File: packages/block-library/src/avatar/index.php (hunk 1 above)
Comment (aaronrobertshaw) [reply packages/block-library/src/avatar/index.php]: Thanks for flagging this. 

On closer inspection the `get_avatar` function doesn't escape the attributes passed via the `extra_attr` arg so I've replaced the superfluous call to `safecss_filter_attr` with one to `esc_attr`. 

In addition, a couple of inline comments have been added explaining the escaping. Hopefully that is sufficient for anyone else in future adding something here to know how and what they'll need to escape.

Comment (andrewserong) [reply packages/block-library/src/avatar/index.php]: Thanks for the update! Looks good 👍
