### PR TITLE
Avoid navigating outside the editor using the arrow keys

### LINKED ISSUE #1997: It's possible to lose the cursor in a paragraph block
Tested in Version 0.5
## Issue Overview
In a paragraph block, if you are on the bottom line and press the bottom arrow on the keyboard, the cursor disappears

## Steps to Reproduce (for bugs)
0. Use Chrome (may affect other browsers as well)
1. Add a paragraph block
2. Write content.
3. Press the down arrow on your keyboard
4. Wonder where your cursor is and how you got to the point in your life that you are forced to wonder where your cursor is.

## Expected Behavior
There should be a clear visual indicator of where my cursor is at all times

### PR DESCRIPTION
**Pull request by youknowriad**
closes #1997 

In this PR, I'm limiting the scope of the arrow navigation to the editor area only.

### CODE REVIEW

File: editor/modes/visual-editor/block.js [hunk 1]
```diff
@@ -262,7 +262,7 @@ class VisualEditorBlock extends Component {
 			'*[tabindex]',
 			'textarea',
 			'input',
-		].join( ',' );
+		].map( ( selector ) => `.editor-visual-editor ${ selector }` ).join( ',' );
```
Comment (iseulde) [inline editor/modes/visual-editor/block.js]: Should we make that a constant?

**Review by ellatrix — APPROVED** [review]
