### PR TITLE
17642 adds edit state to frames to fix new tab issue

### LINKED ISSUE #17642: Media Library 'featured image' dialogue missing link text that describes 'opens in new tab'.
**Describe the bug**
This was originally reported in https://core.trac.wordpress.org/ticket/48028

This github issue is being created because the bug was introduced via Gutenberg and will need to happen here to resolve the overall Accessibility bug. 

Description from Trac Report: 

> The "Media Library" panel of the "Featured Image" modal dialog contains a link labelled with "Edit image". This link takes users to a new window/tab, but that link does not inform users that it opens a new window or tab.
> A link does not naturally convey itself to assistive technology that it opens in a new tab without link text that describes it.
> It is important to convey that a link opens in a new tab because of the change of context may not be clear to everyone.
> Suggested solution
> Write more descriptive link text that describes the link opening in a new tab;
> Utilise the class of 'screen-reader-text' in CSS to hide that text (you can wrap the text in <span class="screen-reader-text">).
> Example of solution
> <a class="edit-attachment" href="..." target="_blank">
>   Edit Image
>   <span class="screen-reader-text">(Opens in a new window)</span>
> </a>
> 

This problem was originally raised on ticket [#47137](https://core.trac.wordpress.org/ticket/47137) and has been separated out here to reduce complexity.

**To reproduce**
1. Add an image block
2. Click on 'media library'
3. Select image
4. Click "Edit Image" in the sidebar
After 4 you will see this opens in a new tab. This is due to the fact that the required edit state logic is not currently in the MediaUpload component. 

**Expected behavior**
Instead of opening in a new tab, the link should just open the Edit Image state _within_ the same modal.

**Screenshots**
Screen Shot 2019-09-29 at 4 35 55 PM

### PR DESCRIPTION
**Pull request by anthonyburchell**
## Description
https://core.trac.wordpress.org/ticket/48028
Excerpt from the ticket above: 

Fixes: #17642.

> The "Media Library" panel of the "Featured Image" modal dialog contains a link labelled with "Edit image". This link takes users to a new window/tab, but that link does not inform users that it opens a new window or tab.
A link does not naturally convey itself to assistive technology that it opens in a new tab without link text that describes it.
It is important to convey that a link opens in a new tab because of the change of context may not be clear to everyone.

Screen Shot 2019-09-29 at 4 35 55 PM

## ## Types of changes/ How has this been tested?

This PR adds a new editState function to initialize the available edit frames. This function also respects the `allowedTypes` prop and has been tested with the video, gallery, and featured image media flows. Additional testing there would be appreciated. 

~~PENDING BUG: edit image state for gallery seems to be messing up because of the multiple nature of this screen. Leaving this draft until I have a fix.~~

### CODE REVIEW

File: packages/media-utils/src/components/media-upload/index.js [hunk 1]
```diff
@@ -86,6 +165,43 @@ const getGalleryDetailsMediaFrame = () => {
 	} );
 };
 
+/**
+ * Prepares the edit state and sets the listener for "Edit Image" button click.
+ *
+ * @param {Object} types passes the allowedTypes object to the media library.
+ * @return {wp.media.view.MediaFrame.Select} The default media workflow.
+ */
+const addEditState = ( types ) => {
```
Comment (joemcgill) [inline packages/media-utils/src/components/media-upload/index.js]: Curious if we could move this into core directly, rather than extending the Select frame only for Gutenberg to include the edit state?

Comment (anthonyburchell) [reply packages/media-utils/src/components/media-upload/index.js]: Thanks for looking at this! I explored doing it globally in the select frame but found it difficult to set the context of `allowedTypes` and selections from this component. The way that we are using frames in Gutenberg is a bit different than we do with core because we base everything off of one default frame. If we set it globally in the select frame, we would have conflict with the Video block because we use the default frame with mime types passed from the props. In this function, we need to pass the allowed mimetypes to the `createStates` function as `types` and as such, each frame (featured, gallery, default) has a specific state to get the selection from. (library, gallery, featured-image) I think where I found the hangup is passing `allowedTypes` from Gutenberg to the Core code. I could be missing something so please let me know if you have any ideas how :) I also want to be cautious about changing Core code and breaking the Classic Editor plugin's flow

Comment (anthonyburchell) [reply packages/media-utils/src/components/media-upload/index.js]: Have it working in the Core `Select` ! I need to explore one last bug where the select button is blank when clicking "back" from the edit screen. This addEditState function can now be removed from this PR. The featured image and gallery states will still need this PR to fix it in Gutenberg. Thanks for calling this out @joemcgill !

Comment (gziolo) [reply packages/media-utils/src/components/media-upload/index.js]: > Have it working in the Core `Select` !

This is great news! Did you manage to resolve it in Core fully?

Comment (anthonyburchell) [reply packages/media-utils/src/components/media-upload/index.js]: @gziolo Yeah! I think we are good now. I've updated this PR to remove the default edit state handling. Now the edit state is added to select using the latest patch in https://core.trac.wordpress.org/ticket/48028

With the core patch above **and** this PR applied to a local Gutenberg, the issue is fixed in gallery, featured image, image block, and inline image block. (may npm have mercy on your computer while testing)

I also removed a declaration in the `frameConfig` to not define a button text for the default state. It is redundant with the core default select button text. Also it caused conflict when hitting the back button once in the `Edit Image` frame.

Comment (anthonyburchell) [reply packages/media-utils/src/components/media-upload/index.js]: and to be clear. The Core side is resolved fully once the patch is committed, however, this PR is needed in order for folks using the new editor to reap the benefits. :) 

New commit incoming to resolve Travis errors.

**Comment by anthonyburchell** [comment]
The Core side changes have been merged in https://core.trac.wordpress.org/changeset/46461

No need to apply the Core patch now. Just test this PR and all should be working again.

**Comment by gziolo** [comment]
I tested it with the latest WordPress core changes in `trunk`. There is some edge case where you see only a blank page in the modal after clicking on the `Edit Image` link. I'm not 100% sure how to reproduce it, but it feels like it happens after you close the modal on the `Edit Image` page and you try to edit the same image from another part of the UI:

edit-image

I also can observe that there is some unexpected behavior with the focus when navigating back from editing the image when you want to select the featured image:

Screen Shot 2019-10-14 at 13 23 31

Somehow, the visual focus stays on the `Back` button which is no longer there.

File: packages/media-utils/src/components/media-upload/index.js [hunk 2]
```diff
@@ -49,14 +75,66 @@ const getGalleryDetailsMediaFrame = () => {
...
+			} ) );
+		},
+
+		/**
+		 * Handle the edit state requirements of selected media item.
+		 *
+		 * @return {void}
+		 */
+		editState( ) {
+			const selection = this.state( 'gallery' ).get( 'selection' ),
```
Comment (joemcgill) [inline packages/media-utils/src/components/media-upload/index.js]: Same style suggestions from above.

File: packages/media-utils/src/components/media-upload/index.js [hunk 3]
```diff
@@ -26,21 +31,42 @@ const getFeaturedImageMediaFrame = () => {
 			} );
 		},
 
+		/**
+		 * Handle the edit state requirements of selected media item.
+		 *
+		 * @return {void}
+		 */
+		editState( ) {
+			const selection = this.state( 'featured-image' ).get( 'selection' ),
```
Comment (joemcgill) [inline packages/media-utils/src/components/media-upload/index.js]: Nitpick, but I'd prefer separate `const` declarations for each variable rather than the shorthand because it makes it easier to read at a glance. I'd also move `this.content.set(view);` to a new line to separate functional code from the variable declarations and add an inline comment.

File: packages/media-utils/src/components/media-upload/index.js [hunk 4]
```diff
@@ -26,21 +31,42 @@ const getFeaturedImageMediaFrame = () => {
...
+				view = new wp.media.view.EditImage( { model: selection.single(), controller: this } ).render();
+			this.content.set( view );
+
+			// after bringing in the frame, load the actual editor via an ajax call
```
Comment (joemcgill) [inline packages/media-utils/src/components/media-upload/index.js]: Capitalize "After" and end the sentence with a period.

**Review by joemcgill — APPROVED** [review]
A few small stylistic comments, but the code overall looks good to me.

File: packages/media-utils/src/components/media-upload/index.js (hunk 3 above)
Comment (gziolo) [reply packages/media-utils/src/components/media-upload/index.js]: Yes, variable declarations are usually in their own statements in Gutenberg. I'm familiar with both approaches because of previous experience, but I agree that we could align.

**Comment by gziolo** [comment]
@anthonyburchell - we should figure out why you see this white screen inside the modal from time to time before we proceed.

There is also this question, whether we should remove `target="_blank"` from `Edit Image` link as it seems to be no longer necessary.

**Comment by afercia** [comment]
The related Trac ticket is milestoned for WordPress 5.4. See https://core.trac.wordpress.org/ticket/48028

Any change to get this rebased, reviewed, and if everything goes well, merged? /Cc @youknowriad @anthonyburchell  @joemcgill

**Comment by anthonyburchell** [comment]
Thanks for the ping @afercia! I rebased and fixed some linting issues. Looks like that is passing now. 

The feedback provided in [this comment](https://github.com/WordPress/gutenberg/pull/17641#issuecomment-541630454) is still valid. It is possible to get a blank white screen after clicking edit in one frame (gallery) and opening edit in another (maybe featured). I still have some investigation to get that solved. It's a pretty edge case instance so I leave it to y'all to thumbs up moving forward and making a separate issue to solve that.

**Comment by anthonyburchell** [comment]
Also, it may be worth mentioning that I don't think this _needs_ to be included in Beta 1. This is a bug fix to a broken part of the edit image functionality so maybe we can land this for Beta 2?

**Comment by anthonyburchell** [comment]
An update here, I found that the edit image bug has existed since before this PR. I think that calls for a trac side change to fix the close action. To reproduce, click edit image on a selected image in the gallery library modal, close window. open another frame (featured image maybe), attempt to edit same image, see white screen. It's possible to do this in older versions. 

With that in mind, I dont see any blockers to merging this PR before 5.4 Beta 2. Please let me know if theres anything I can do to bring it to 100%. :)

**Review by gziolo — APPROVED** [review]
I tested it again and I couldn't reproduce issues listed a few months back. Nice work. Let's get it in 🎉

**Comment by gziolo** [comment]
> With that in mind, I dont see any blockers to merging this PR before 5.4 Beta 2. Please let me know if theres anything I can do to bring it to 100%. :)

@jorgefilipecosta - I added this PR to the list of PRs to include in WP 5.4 release.

**Comment by mcsf** [comment]
@anthonyburchell @gziolo @jorgefilipecosta:
There are two bugs introduced in the Gallery block by this PR:

## Gallery: can't insert select items from media library

gallery-media-insert

Also notice that, when an image is selected in the media modal, the action button at the bottom-right corner reads **"Insert gallery"** instead of "Create a new gallery".

## Gallery: can't edit collection of images

1. Open a post that has a Gallery block with images.
2. Select the block.
3. Click on "Media Library" underneath the images.
**Expected:** The media modal opens up.
**Observed:** Nothing happens in the UI, and a TypeError is raised:

```
TypeError: t is null                      media-views.min.js:2:7343
```

**Comment by anthonyburchell** [comment]
@mcsf you rock. Thank you for finding this. Here is the fix for the issue you identified: https://github.com/WordPress/gutenberg/pull/20287

Would greatly appreciate some testing on this to verify gallery works as intended. 🙏🏼
