### PR TITLE
Composite: make items tabbable if active element gets removed

### LINKED ISSUE #65283: Options in the CircularOptionPicker may be not operable with the keyboard
### Description

Working on https://github.com/WordPress/gutenberg/pull/65124/ surfaced an edge case where the buttons in the color picker may end up in a state where they're not focusable because they all have a `tabindex="-1"` attribute.

I'm not sure what is the root cause but I see some recent work on the `CircularOptionPicker` and the underlying `Composite` components in https://github.com/WordPress/gutenberg/pull/64833

It appears to me the UI may end up in a state where the value of the circular option picker _option_ `activeId` value doesn't match any HTML id attribute in the UI. As such, none of the color buttons is considered 'active'. Worth reminding the 'actice' button is expected to be the only button that is focusable with the Tab key, while navigation to the other buttons works via arrow keys.

Cc @WordPress/gutenberg-components 

Three prerequisites to reproduce the bug:
- Seems the bug can be reproduced only with themes that display more than one color palette in the panel:
  - Twenty Twenty-Three: Theme and Default palettes - can reproduce
  - Twenty Twenty-Four: Theme palette - cannot reproduce
  - Twenty Twenty-Five: Theme and Default palettes - can reproduce
- Switch to the branch from https://github.com/WordPress/gutenberg/pull/65124/ to reproduce.
- Go to the WP admin > Gutenberg > Experiments and enable the 'Color randomizer' experiment.

Aniamted GIF to illustrate; Notice that after randomizing the colors, tabbing through the UI entirely skipcs the color picker buttons:

circular color picker options not focusable

### Step-by-step reproduction instructions

- Set the prerequisites as described above.
- Test with Twenty Twenty-Four.
- Go to Site Editor > Styles > Colors > Edit palette.
- Tab through the UI and observe the color picker buttons are operable with the keyboard.
- Move focus to the Randomize colors button and press Enter.
- At this point, the color buttons in the picker re-render. They get new IDs.
- Tab backwards and forwards through the UI and observe that the color picker buttons are still operable with the keyboard.
- Test with Twenty Twenty-Three or Twenty Twenty-Five.
- Repeat the steps above.
- On the last step, observe that now none of the color picker buttons is operable with the keyboard.

Inspecting the source:
- All the buttons have a `tabindex="-1"` attribute.
- Expected: the 'active' button to be focusable (not sure whether tabindex should be removed or be `tabindex="0"`).
- In my testing, dumping the value of `activeId` may return a value that doesn't match any ID attribute in the DOM. for example:
  - The `activeId` value is `components-circular-option-picker-3-75`.
  - None of the IDs of the 8 buttons in the screenshot below matches `activeId` e.g.:

```
components-circular-option-picker-3-43
components-circular-option-picker-3-45
components-circular-option-picker-3-83
components-circular-option-picker-3-85
components-circular-option-picker-3-87
components-circular-option-picker-3-53
components-circular-option-picker-3-89
components-circular-option-picker-3-57
```

Screenshot 2024-09-12 at 14 44 41

Worth also noting that the ID values in the HTML are not consecutive. I would expect to be numbers progressively incremented by 1. Instead, they appear to be pretty inconsistent, which makes me think to some _timing_ issue and the ID being genereated randomly across the multiple instances of the color picker.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by ciampo**
## What?

May fix https://github.com/WordPress/gutenberg/issues/65283

This PR tweaks the behavior of the `Composite` component so that the composite widget can continue to receive keyboard focus even when its active ID doesn't correspond to an element rendered in the DOM.

## Why?

The fact that `Composite` can end up in a situation where the whole widget is not focusable is bad for assistive technology, and we should try to fix it.

## How?

Following [a suggestion](https://github.com/ariakit/ariakit/issues/4129) from the Ariakit maintainers, this PR makes all composite items tabbable if the element associated with the active ID is not connected to the store.

In this case, when the focus is moved back to the composite widget, the items will be able to receive focus. As soon as one item receives focus, all composite items will stop being tabbable and revert back to the standard behavior of a composite widget.

## Review suggestions

Review commit-by-commit. The actual fix is applied in the first commit. The rest of the commits are accessories to the main fix.

## Testing Instructions

In Storybook:
- Load the "Remove active item" example
- Focus the composite widget, and with the arrow keys move focus on the third item
- Tab to the "Toggle third item button" and click it
- Tab back to the composite widget: the second item should receive focus and become active
- Moving arrow keys should work as expected in the composite widget

<details>

<summary>Edit: it looks like the UI has changed and it's impossible to reproduce the bug in the editor as of now</summary>

In the editor:
- Follow the testing instructions indicated in https://github.com/WordPress/gutenberg/issues/65283
- When clicking the "randomize colors" button, tab back to the color palette.
- The last item in the palette should receive keyboard focus
- Moving arrow keys should work as expected in the composite widget

</details>

## Screenshots or screencast 

| Before (trunk) | After (this PR) |
|---|---|
| <video src="https://github.com/user-attachments/assets/d7535e1c-d70e-4ee2-a7e3-bbdadeec1e32" /> | <video src="https://github.com/user-attachments/assets/d91a8172-e2d8-460f-967d-cc9b65bff417" /> |

### CODE REVIEW

File: packages/components/src/composite/item.tsx [hunk 1]
```diff
@@ -20,9 +20,24 @@ export const CompositeItem = forwardRef<
...
+	const store = storeViaProps ?? ( context.store as Ariakit.CompositeStore );
+
+	// If the active item is not connected, Composite may end up in a state
+	// where none of the items are tabbable. In this case, we force all items to
+	// be tabbable, so that as soon as an item received focus, it becomes active
+	// and Composite goes back to working as expected.
+	const tabbable = Ariakit.useStoreState( store, ( state ) => {
+		return ! store?.item( state?.activeId )?.element?.isConnected;
+	} );
+
```
Comment (ciampo) [inline packages/components/src/composite/item.tsx]: This is the actual fix

File: packages/components/src/composite/stories/index.story.tsx
Comment (ciampo) [inline packages/components/src/composite/stories/index.story.tsx:1]: I'll remove this story before merging

File: packages/components/src/composite/legacy/test/index.tsx
Comment (ciampo) [inline packages/components/src/composite/legacy/test/index.tsx:1]: While reviewing some unit test failures, I realised that `renderAndValidate` is an async function but is never `await`ed. If folks think this change is worth applying, I'll do so in a separate PR.

File: packages/components/src/composite/group.tsx [hunk 2]
```diff
@@ -20,11 +20,11 @@ export const CompositeGroup = forwardRef<
...
-			store={ context.store as Ariakit.CompositeStore }
-			{ ...props }
-			ref={ ref }
-		/>
-	);
+
+	// @ts-expect-error The store prop in undocumented and only used by the
+	// legacy compat layer.
+	const storeViaProps = props.store as Ariakit.CompositeStore;
+	const store = storeViaProps ?? ( context.store as Ariakit.CompositeStore );
```
Comment (ciampo) [inline packages/components/src/composite/group.tsx]: Reading the store passed via `props` is a fix to how the legacy compat layer works. I believe that this is a bug that's been around since we wrote the legacy compat layer, but it was surfaced by the changes in this PR. If folks agree with it, I'll apply it in a separate PR.

File: packages/components/src/composite/test/index.tsx
Comment (ciampo) [inline packages/components/src/composite/test/index.tsx:1]: We should probably add a suite of tests similar to the legacy version. I can do that in a follow-up PR

File: packages/components/src/composite/item.tsx (hunk 1 above)
Comment (diegohaz) [reply packages/components/src/composite/item.tsx]: Just a heads up: it's probably better to check if `activeId` is not `null` beforehand. See https://github.com/ariakit/ariakit/issues/4129#issuecomment-2367928139

Comment (ciampo) [reply packages/components/src/composite/item.tsx]: Thank you, updated!

File: packages/components/src/composite/group.tsx (hunk 2 above)
Comment (ciampo) [reply packages/components/src/composite/group.tsx]: https://github.com/WordPress/gutenberg/pull/65821

File: packages/components/src/composite/legacy/test/index.tsx
Comment (ciampo) [reply packages/components/src/composite/legacy/test/index.tsx:1]: https://github.com/WordPress/gutenberg/pull/65823

File: packages/components/src/composite/item.tsx [hunk 3]
```diff
@@ -20,9 +20,27 @@ export const CompositeItem = forwardRef<
...
+	// If the active item is not connected, Composite may end up in a state
+	// where none of the items are tabbable. In this case, we force all items to
+	// be tabbable, so that as soon as an item received focus, it becomes active
+	// and Composite goes back to working as expected.
+	const tabbable = Ariakit.useStoreState( store, ( state ) => {
+		return (
+			state?.activeId !== null &&
+			! store?.item( state?.activeId )?.element?.isConnected
+		);
+	} );
```
Comment (tyxla) [inline packages/components/src/composite/item.tsx:38]: Good catch 👍 

I wonder if this is something that Ariakit should resolve internally?

File: packages/components/src/composite/stories/index.story.tsx [hunk 4]
```diff
@@ -353,3 +353,28 @@ const Fill = ( { children } ) => {
 		},
 	},
 };
+
+export const RemoveActiveItem: StoryObj< typeof Composite > = {
```
Comment (tyxla) [inline packages/components/src/composite/stories/index.story.tsx]: Was going to say this story doesn't make much sense to keep, but I see you created it solely for testing and plan to remove it - thanks!

File: packages/components/src/composite/test/index.tsx [hunk 5]
```diff
@@ -0,0 +1,123 @@
...
+import { useState } from '@wordpress/element';
+
+/**
+ * Internal dependencies
+ */
+import { Composite } from '..';
+
+// This is necessary because of how Ariakit calculates page up and
+// page down. Without this, nothing has a height, and so paging up
+// and down doesn't behave as expected in tests.
```
Comment (tyxla) [inline packages/components/src/composite/test/index.tsx:20]: Ah, jsdom strikes again. Makes you wonder if this kind of tests isn't better suited for e2e. I guess not, because we're not really testing anything related to calculating the height.

File: packages/components/src/composite/test/index.tsx [hunk 6]
```diff
@@ -0,0 +1,123 @@
...
+			</Composite>
+			<button onClick={ () => setShowThirdItem( ( value ) => ! value ) }>
+				Toggle third item
+			</button>
+		</>
+	);
+}
+
+describe( 'Composite', () => {
+	it( 'should remain focussable even when there is no elements in the DOM associated with the currently active ID', async () => {
```
Comment (tyxla) [inline packages/components/src/composite/test/index.tsx]: Nit: let's use the US English version like for anything else we do in code:

```suggestion
	it( 'should remain focusable even when there is no elements in the DOM associated with the currently active ID', async () => {
```

File: packages/components/src/composite/test/index.tsx [hunk 7]
```diff
@@ -0,0 +1,123 @@
...
+				{ showThirdItem && <Composite.Item>Item 3</Composite.Item> }
+			</Composite>
+			<button onClick={ () => setShowThirdItem( ( value ) => ! value ) }>
+				Toggle third item
+			</button>
+		</>
+	);
+}
+
+describe( 'Composite', () => {
```
Comment (tyxla) [inline packages/components/src/composite/test/index.tsx:71]: Thanks for adding a comprehensive test 👍

**Review by tyxla — COMMENTED** [review]
Looks good, works well 👍 

Thanks for adding tests and a special storybook story to manually test it in 🙇‍♂️ 

Not approving just yet since we'll need to clean up after merging #65823 and #65821.

File: packages/components/src/composite/item.tsx (hunk 3 above)
Comment (ciampo) [reply packages/components/src/composite/item.tsx:38]: I already discussed it in https://github.com/ariakit/ariakit/issues/4129. I think Ariakit maintainers are cautious about implementing such a fix directly in the library, and instead asked if we wanted to try the fix out in userland first

File: packages/components/src/composite/test/index.tsx (hunk 5 above)
Comment (ciampo) [reply packages/components/src/composite/test/index.tsx:20]: Not singularly for this test, but in general we way need to consider this. The closer our environment is to the real browser, the more confidence we get from the tests

File: packages/components/src/composite/test/index.tsx (hunk 6 above)
Comment (ciampo) [reply packages/components/src/composite/test/index.tsx]: There's also a grammar error that I'll fix ("there IS no elements" -> "there ARE no elements")

**Comment by ciampo** [comment]
Rebased to include changes from https://github.com/WordPress/gutenberg/pull/65823 and https://github.com/WordPress/gutenberg/pull/65821 (which were merged in the meantime), and addressed other pending feedback

@tyxla this is ready for another round of review

File: packages/components/src/composite/test/index.tsx
Comment (tyxla) [reply packages/components/src/composite/test/index.tsx:1]: Sounds like a plan

**Review by tyxla — APPROVED** [review]
LGTM 🚀

**Comment by ciampo** [comment]
I'll enable backporting once https://github.com/WordPress/gutenberg/pull/65853 gets merged

**Comment by diegohaz** [comment]
@ciampo Thanks for trying this. Is there anything noteworthy about this change that we should know before implementing it on Ariakit? Have you encountered any issues?

**Comment by ciampo** [comment]
I haven't encountered issues myself, not have received any reports — @afercia , do you have any feedback?

**Comment by afercia** [comment]
@ciampo @diegohaz I haven't tested the progress on this fix since I reported it iin https://github.com/WordPress/gutenberg/issues/65283

Do I get it correctly that the fix is:
- When there's no element referenced by the activeId, all the items become focusable.
- As soon as one of the items receives focus, the original behavior is restored with only one item tabbable (tabindex=0) and the other ones not tabbable (tabindex=-1). Arrows navigation will work as expected.

If that's correct, it seems to me it's a reasonable and effective fix.

File: packages/components/src/composite/test/index.tsx
Comment (ciampo) [reply packages/components/src/composite/test/index.tsx:1]: https://github.com/WordPress/gutenberg/pull/65952
