### PR TITLE
Make sure comments keep their location when inside paragraph

### LINKED ISSUE #18079: Convert to Blocks moves the more tag
**Describe the bug**
When I chose Convert to blocks to convert a Classic block the more block was moved to after the content. It should have respected the original order of the content.

**To reproduce**
1. Create a post containing 
```
<!--more-->Seen before as shallow and bugs.
```
2. In the block editor it gets shown in the Classic Block
3. Click on More options > Convert to Blocks
4. The More block is created after the Paragraph block
```
<!-- wp:paragraph -->
<p>Seen before as shallow and bugs.</p>
<!-- /wp:paragraph -->

<!-- wp:more -->
<!--more-->
<!-- /wp:more -->
```

**Expected behavior**
The More block should not be moved after the paragraph block. The More block should remain first. Even though there's nothing before it.

**Screenshots**

I'd love to add a sreenshot but GitHub's saying "Something went really wrong, and we can't process that file."

**Desktop (please complete the following information):**
 - OS:  Windows
 - Browser: Chrome
 - Version: Version 77.0.3865.120 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
I was using WordPress core when I found the problem. 
It's still present in Gutenberg 6.7.0

The irony is, of course, the content. I was going to write that well known quote from Linus's law
https://en.wikipedia.org/wiki/Linus%27s_Law

### PR DESCRIPTION
**Pull request by vdwijngaert**
## Description
Fixes an issue where  `<!--more-->` comments did not keep their location when inside a paragraph, after being converted to blocks. This mostly affects those cases where a classic editor block gets converted. See the linked issue for details.

My code addresses the special case where the `<!--more-->` was placed inside of a paragraph. In order to obtain the expected behavior, we split the paragraph in two and insert the block in the middle instead.

Closes #18079 

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style. 
- [X] My code follows the accessibility standards. 
- [X] I've tested my changes with keyboard and screen readers. 
- [X] My code has proper inline documentation. 
- [X] I've included developer documentation if appropriate. 
- [X] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). (not applicable)

### CODE REVIEW

**Comment by paaljoachim** [comment]
@gwwar Kerry can you take a look?
Thanks!

File: packages/blocks/src/api/raw-handling/special-comment-converter.js [hunk 1]
```diff
@@ -30,28 +29,79 @@ export default function specialCommentConverter( node, doc ) {
...
-				break;
-			}
+/**
+ * Convert `<!--more-->` as well as the `<!--more Some text-->` variant
+ * and its `<!--noteaser-->` companion into the custom element
+ * described in `specialCommentConverter()`.
+ *
+ * @param {Node}     node The node to be processed.
+ * @param {Document} doc  The document of the node.
+ * @return {void}
```
Comment (gwwar) [inline packages/blocks/src/api/raw-handling/special-comment-converter.js:43]: Optional: Note that if we return {void} it's fine to leave the return off [JSDoc](https://developer.wordpress.org/block-editor/contributors/code/coding-guidelines/#nullable-undefined-and-void-types).

File: packages/blocks/src/api/raw-handling/test/special-comment-converter.js [hunk 2]
```diff
@@ -49,6 +49,44 @@ describe( 'specialCommentConverter', () => {
 			<p>Third paragraph</p>`
 		);
 	} );
+	describe( 'when more comment is inside paragraph', () => {
```
Comment (gwwar) [inline packages/blocks/src/api/raw-handling/test/special-comment-converter.js:52]: 👏 Thanks for adding useful test cases!

File: packages/blocks/src/api/raw-handling/special-comment-converter.js [hunk 3]
```diff
@@ -30,28 +29,79 @@ export default function specialCommentConverter( node, doc ) {
...
+
+			return acc;
+		};
+
+		// Split the original parent node and insert our more block
+		[
+			childNodes.slice( 0, nodeIndex ).reduce( paragraphBuilder, null ),
+			moreBlock,
+			childNodes.slice( nodeIndex + 1 ).reduce( paragraphBuilder, null ),
+		].forEach(
```
Comment (gwwar) [inline packages/blocks/src/api/raw-handling/special-comment-converter.js:98]: Do folks know if we've polyfilled https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/replaceWith ? It's 💯 optional, but might be nice here.

eg
```js
paragraphWithMore.replaceWith( firstParagraph, moreBlock, secondParagraph );
```

File: packages/blocks/src/api/raw-handling/special-comment-converter.js [hunk 4]
```diff
@@ -30,28 +29,79 @@ export default function specialCommentConverter( node, doc ) {
...
+		node.parentNode.nodeName !== 'P' ||
+		node.parentNode.childNodes.length === 1
+	) {
+		replace( node, moreBlock );
+	} else {
+		const childNodes = Array.from( node.parentNode.childNodes );
+		const nodeIndex = childNodes.indexOf( node );
+		const wrapperNode = node.parentNode.parentNode || doc.body;
+
+		const paragraphBuilder = ( acc, child ) => {
```
Comment (gwwar) [inline packages/blocks/src/api/raw-handling/special-comment-converter.js:83]: I can read this okay, but do other reviewers prefer something more declarative? The reducer here did stick out a little bit.

**Review by gwwar — COMMENTED** [review]
This one manually tests well for me @vdwijngaert ! Let's get another +1 from folks a little more familiar with this package. From recent history, perhaps @ellatrix or @mcsf could 👀 on code changes here.

File: packages/blocks/src/api/raw-handling/test/special-comment-converter.js [hunk 5]
```diff
@@ -49,6 +49,44 @@ describe( 'specialCommentConverter', () => {
...
+		it( 'should split the paragraph', () => {
+			const output = deepFilterHTML(
+				`<p>First part<!--more-->second part</p>`,
+				[ specialCommentConverter ]
+			);
+			expect( output ).toEqual(
+				`<p>First part</p><wp-block data-block=\"core/more\"></wp-block><p>second part</p>`
+			);
+		} );
+		it( 'should handle complex cases', () => {
```
Comment (mcsf) [inline packages/blocks/src/api/raw-handling/test/special-comment-converter.js]: Minor suggestion for a more descriptive name:

```suggestion
		it( 'should preserve inline formatting', () => {
```

File: packages/blocks/src/api/raw-handling/special-comment-converter.js (hunk 4 above)
Comment (mcsf) [reply packages/blocks/src/api/raw-handling/special-comment-converter.js:83]: Yeah, it's not a big deal, but the reducer feels unnecessarily abstract. I don't mind the use of `reduce` itself, but it might be clearer to use its `initialValue` argument and inline the reducer, e.g.

```js
childNodes.slice( 0, nodeIndex ).reduce(
  ( acc, child ) => { acc.appendChild( child ); return acc; },
  doc.createElement( 'p' )
);
```

> prefer something more declarative?

The other option, in my head, kind of goes in the opposite direction: making this clearer by following local conventions. In `raw-handling`, a lot of DOM manipulations are done very imperatively, mostly because performance is paramount but also because it's also syntactically convenient, especially iterating through or _unwrapping_ child nodes. So paradoxically, _in this module_, it might be more readable to write something like:

```js
for ( let i = 0; i < nodeIndex; i++ ) insert( childNodes[i], node.parentNode );
insert( moreBlock, node.parentNode );
for ( let i = nodeIndex; i < l; i++ ) insert( childNodes[i], node.parentNode );
```

I have no idea if modern JIT compilers can optimise `[ e0, e1, ... ].forEach( fn )` into something that doesn't require allocating memory for that temporary array (e.g. optimise it as a loop). So I can't comment on the performance impact of what we're doing with `Array.from`+`Array#reduce` in this PR, and whether it matters at all. :)

**Review by mcsf — APPROVED** [review]
This looks really good to me — the added tests are most welcome!

**Comment by gwwar** [comment]
Whoops, I think we lost track of this one. Sorry about that! Pretty sure this is still an issue in trunk, @vdwijngaert if you're still interested let's rebase the PR to fix the conflict and we can try landing this one.

If you're busy, I can also rebase and land for you.

**Comment by t-hamano** [comment]
As a result of [the bug scrub](https://wordpress.slack.com/archives/C02QB2JS7/p1657030369881049) in the editor chat, I will continue to test.
I will rebase and try to test the issue 👍

**Comment by t-hamano** [comment]
- [x]  Merge `trunk`
- [x] Fix unit test
- [x] Passes all tests

Everything looks good to me 👍
