### PR TITLE
RichText: remove selection change listener during composition

### LINKED ISSUE #14434: Duplicated first Chinese word when typing
**Describe the bug**
Duplicated first Chinese word

**To Reproduce**
1. New  post
2. New phrase
3. Input Chinese, the first word will be duplicated.

It looks like this

case 1. 好好的 .... 
In this case "好" is duplicated automatically.

case 2.機基本上 ....
In this case "機" is the same sound with "基", and auto-input by gutenberg.

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

This should be included in WP 5.2. It worked fine in WP 5.1.

Fixes #14434.

This bug can also be reproduced with other keyboards, including an American keyboard.

1. Create a new post and paragraph.
2. Press `` option+` ``. You started composing a character.
3. Press any vowel, e.g. `a`.

Expected: `à`. Actual: `` `à ``. 

Cause: the selection change event listener is called after input, which overwrites the DOM if the selection state is different (and it is different, but shouldn't be recorded). The overwrite happens for the format boundaries.

Solution: remove the selection change listener during composition.

Includes a minor clean up, as I was experimenting with different events bound to `Editable`.

## How has this been tested?

See above.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/block-editor/src/components/rich-text/index.js [hunk 1]
```diff
@@ -373,6 +373,8 @@ export class RichText extends Component {
 		// Browsers setting `isComposing` to `true` will usually emit a final
 		// `input` event when the characters are composed.
 		if ( event && event.nativeEvent.isComposing ) {
+			// Also don't update any selection.
+			document.removeEventListener( 'selectionchange', this.onSelectionChange );
```
Comment (youknowriad) [inline packages/block-editor/src/components/rich-text/index.js]: Do you think there's a simpler way togo instead of this selection enabling/disabling? maybe a flag?

File: packages/block-editor/src/components/rich-text/editable.js [hunk 2]
```diff
@@ -154,44 +151,29 @@ export default class Editable extends Component {
...
 			dangerouslySetInnerHTML: { __html: valueToEditableHTML( record ) },
-			onPaste,
-			onInput,
-			onFocus,
-			onBlur,
-			onKeyDown,
-			onCompositionEnd,
-			onMouseDown,
-			onTouchStart,
+			...remainingProps,
```
Comment (youknowriad) [inline packages/block-editor/src/components/rich-text/editable.js]: Can you expand a little bit on the refactoring here?

Comment (youknowriad) [reply packages/block-editor/src/components/rich-text/editable.js]: Actually, I got it :)

**Review by youknowriad — APPROVED** [review]
This fixes the issue for me. I'm wondering, is it possible that the event is not rebound properly in a scenario like this:

 - Trigger a composition `^` for instance
 - Leave the RichText by clicking outside or something else?

File: packages/block-editor/src/components/rich-text/index.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-editor/src/components/rich-text/index.js]: I see this as the simplest way. There's no need to run a listener if it's not needed?

**Comment by ellatrix** [comment]
@youknowriad Thanks for the review! To answer your question: the browser always triggers a `compositionend` event, also when a composition is cancelled. When you leave the field, composition ends and the final character is just `^`.

File: packages/block-editor/src/components/rich-text/index.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-editor/src/components/rich-text/index.js]: I mean, I think it's "cleanliest" if you remove listeners if you don't need them, add them back if you do need them again. I made the mistake before not to do that, and it had a negative performance impact (#12480), so I make a habit of taking this "cleaner" approach.
