### PR TITLE
[Widgets editor] Disallow multiple instances of reference widgets

### LINKED ISSUE #25494: Widgets editor - prevent creation of multiple reference widgets
**Describe the bug**
As discussed in https://github.com/WordPress/gutenberg/pull/24905, it is possible to create multiple reference widgets by leveraging multiple legacy widget blocks. There should only ever be at most one instance of any reference widget. Unfortunately `supports.multiple=false` only works for the block, not for it's variations.

### PR DESCRIPTION
**Pull request by adamziel**
## Description

This PR fixes #25494 by:

* Showing an error message if such reference widget already exists in another widget area
* Removing duplicates from submitted API requests

This PR only affects the frontend and does **not** change the actual API handlers.

## How has this been tested?

1. Add the following code to gutenberg.php: https://gist.github.com/adamziel/526436b4cc9bc82a7221c77e00137ae1
1. Go to widgets editor
1. Add a marquee widget
1. Add another marquee widget
1. Confirm you see the same message as on the screenshots below
1. Add another legacy widget, could be by just copying&pasting the marquee and renaming it to e.g. "Calendar"
1. Repeat steps 3-5, confirm the error allows you to switch to a Calendar widget
1. Click save while the duplicates are still in the editor, confirm only one instance of each reference widget got saved

## Screenshots 

Zrzut ekranu 2020-10-15 o 13 02 03
Zrzut ekranu 2020-10-15 o 13 02 14

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/edit-widgets/src/blocks/legacy-widget/edit/widget-select-control.js [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+			.map( ( { attributes } ) => attributes?.referenceWidgetName )
+	);
+	const choosableLegacyWidgets = useMemo( () => {
+		const visible = pickBy(
+			availableLegacyWidgets,
+			( { isHidden } ) => ! isHidden
+		);
+
+		// Filter out used reference widgets
+		return filter( visible, ( widget, referenceWidgetName ) => {
```
Comment (talldan) [inline packages/edit-widgets/src/blocks/legacy-widget/edit/widget-select-control.js]: Using filter here was converting the value from an object to an array, which caused an issue when mapping the options for the select control, as `key` is supposed to be the widget name instead of a number.

I've changed it to use the `pickBy` above. 

However, I don't think an object should be used for SelectControl values, as it'll give unpredictable results in terms of ordering.

File: packages/edit-widgets/src/blocks/legacy-widget/edit/index.js [hunk 2]
```diff
@@ -34,71 +39,76 @@ function LegacyWidgetEdit( {
...
-			/>
-		</InspectorControls>
-	) : null;
+	if ( isDuplicateReferenceWidget ) {
+		return (
+			<Placeholder
+				icon={ <BlockIcon icon={ brush } /> }
+				label={ __( 'Duplicate Widget' ) }
+			>
+				<p className="components-placeholder__error">
```
Comment (talldan) [inline packages/edit-widgets/src/blocks/legacy-widget/edit/index.js]: Hmm, this classname doesn't really seem to do much. I see the styles are defined in the placeholder styles, but I think it must be legacy given the lack of any notable styling. I'd expect some red text or something.

Ideally there would be a `PlaceholderError` component or an `error` prop on the placeholder that renders this. The pattern of using another component's classname like this is discouraged. Some more info:
https://github.com/WordPress/gutenberg/blob/master/docs/contributors/coding-guidelines.md#naming

I've switched this to use the `instructions` prop, which makes it look pretty much the same, but without the code quality issues.

**Review by talldan — APPROVED** [review]
I rebased, resolved merge conflicts, and push three fairly basic commits that are either bug fixes or code quality.

This looks good to me. There might be more we can do in the future like removing the 'duplicate' option for reference widgets, but I think we can push those things out to separate PRs as they're more debatable.
