### PR TITLE
`ColorPalette`: Use computed color when css variable is passed to `ColorPicker`

### LINKED ISSUE #46492: `ColorPalette`: Color picker doesn't work correctly with variable colors
Hello everyone 👋

If I set the value of a color in `theme.json` file to be a CSS custom property - the color picker is not showing the color correctly inside the color picker popover when you select a color from the theme color presets - it returns to `#000000`.

I am setting the theme palette colors in `theme.json` file like this because the theme has multiple color palettes and the user [could change](https://d.pr/v/5GKRhq) the palette from customizer. 

```
"color": {
	"palette": [
		{
			"name": "Palette Color 1",
			"slug": "palette-color-1",
			"color": "var(--paletteColor1)"
		},

		{
			"name": "Palette Color 2",
			"slug": "palette-color-2",
			"color": "var(--paletteColor2)"
		}
	]
}
```

Here is a quick video that better explains the problem - https://d.pr/v/8tSl5E

The question is, if it is not possible to use variable colors inside color picker, could you please add support for this?

Thank you very much for your time!

### PR DESCRIPTION
**Pull request by t-hamano**
Closes #46492

## What?
This PR passes the computed color to the `ColorPicker` component if the value of the `ColorPalette` component is a CSS variable. This will ensure that the correct color value is set in the input field when the custom color picker is opened.

## Why?
The `ColorPicker` component doesn't know what actual color the CSS variable points to. Therefore, the color input field of the `ColorPicker` component displays `#000000` as a fallback.

## How?
I used the following approach to pass the computed value to the `ColorPicker` component:

- Set a `ref` in the custom color picker area and reference its DOM node.
- Use the new `getComputedBackgroundColorValueFromRef()` function to read the background-color from that DOM node. Therefore, `ColorPalette` itself doesn't directly reference CSS variables; it expects CSS variables to be correctly defined by the consumer or theme. I also created this function because it may help resolve the following issue:
  - #41459
  - #44904 

### In the block editor

Enable Empty Theme and update theme.json as follows:

<details>
<summary>/test/emptytheme/theme.json</summary>

```json
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"settings": {
		"appearanceTools": true,
		"layout": {
			"contentSize": "840px",
			"wideSize": "1100px"
		},
		"color": {
			"palette": [
				{
					"name": "Normal Color",
					"slug": "normal",
					"color": "#378C60"
				},
				{
					"name": "Variable Color (Hex)",
					"slug": "hex",
					"color": "var(--wp--custom--hex)"
				},
				{
					"name": "Variable Color (RGB)",
					"slug": "rgb",
					"color": "var(--wp--custom--rgb)"
				},
				{
					"name": "Variable Color (RGBA)",
					"slug": "rgba",
					"color": "var(--wp--custom--rgba)"
				}
			]
		},
		"custom": {
			"hex": "#e42c64",
			"rgb": "rgb(45,36,138)",
			"rgba": "rgba(45,36,138, 0.5)"
		}
	}
}
```
</details>

The definition of the `settings.custom` property creates the following CSS variable, which is referenced as the value of the `settings.color.palette`:

```
--wp--custom--hex: #e42c64;
--wp--custom--rgb: rgb(45,36,138);
--wp--custom--rgba: rgba(45,36,138, 0.5);
```

- Inserts a block that supports the color.
- Open the Text Color or Background Color menu and click on one of the palettes in the THEME area.
- When you open the custom color palette, confirm that the input field is set to the value calculated from the CSS variable.

### In the storybook

- Build Storybook and access "ColorPalette" > "CSS Variables".
- Select one of the palettes, open the color picker, and verify that the input field is set to the calculated value.

## Screenshots or screencast 

https://user-images.githubusercontent.com/54422211/212678589-cbfb74da-dc29-433f-924f-c524b784929b.mp4

### CODE REVIEW

File: packages/components/src/color-palette/index.tsx [hunk 1]
```diff
@@ -214,10 +214,32 @@ const areColorsMultiplePalette = (
 	);
 };
 
+const getComputedBackgroundColorValueFromRef = (
+	value: string | undefined,
+	ref: RefObject< HTMLElement > | null
+) => {
+	let computedValue = value;
```
Comment (mirka) [inline packages/components/src/color-palette/index.tsx]: Nit: The naming is kind of misleading to me. It only returns a "computed value from ref" when the value is a CSS var. Maybe something like `normalizeColorValue()` or `getValueForColord()`? And we can probably remove the `let computedValue` if we do an early return like:

```jsx
if ( ! currentValueIsCssVariable ) {
  return value;
}
```

**Review by mirka — COMMENTED** [review]
Ooh, thank you for the fix!

I confirmed this is working in Chrome/Firefox/Safari, and it _should_ stay that way given that [the spec says it returns "resolved values"](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle#notes) 🤞

Can we also fix the other issue (#41459) in this PR or are you planning to do it separately?

https://github.com/WordPress/gutenberg/blob/8e299b5e8e50e1669cef37bf598bc1e0f339e065/packages/components/src/color-palette/index.tsx#L313-L324

File: packages/components/src/color-palette/index.tsx (hunk 1 above)
Comment (t-hamano) [reply packages/components/src/color-palette/index.tsx]: I have changed the function name.
Also, I think I could have simplified the function content without using `let` 👍

**Comment by t-hamano** [comment]
> Can we also fix the other issue (https://github.com/WordPress/gutenberg/issues/41459) in this PR or are you planning to do it separately?

Yes, I would like to try to see if #41459, #44904, can also be solved separately using this function or ref.

File: packages/components/src/color-palette/index.tsx (hunk 1 above)
Comment (mirka) [reply packages/components/src/color-palette/index.tsx]: Awesome, I like how these small changes improve readability 😊

**Review by mirka — APPROVED** [review]
🚢

**Comment by ciampo** [comment]
Thank you @t-hamano for working on this 🙏  it looks like a little improvement but it fixes a really annoying bug!
