### PR TITLE
Cover: Avoid content loss when the templateLock value is all or contentOnly

### LINKED ISSUE #45625: Cover: Applying lock and templateLock attributes occasionally strips content
### Description

When locking a Cover block or when using the `templateLock` functionality, the Cover block's inner blocks can occasionally be stripped unexpectedly. It's a bit hard to explain, but the video below includes a complete walkthrough. Given that this issue results in a loss of content and is related to a new feature in 6.1, I believe a fix would be a good candidate for a minor release. 

### Step-by-step reproduction instructions

1. On a new page or post insert the sample block code noted below.
2. Click on the Cover block and use the locking functionality to apply locking to the Cover and all internal blocks. Be sure to use the "Apply to all blocks inside" toggle.
3. You should see that the blocks inside of the Cover disappear when locking is applied. 
4. Click Undo, and the content should reappear.
5. Remove the locking attributes and refresh the page. 
6. Now open the Code Editor and manually apply the `"templateLock":"contentOnly"` attribute to the Cover block.
7. Exit the Core Editor and see that the content in the Cover block has disappeared again. 
8. Click Undo, and the content should reappear and the Cover should remain content-only locked.

See the video for a complete walkthrough.

Sample Code:
```
<!-- wp:cover {"overlayColor":"contrast","minHeight":450,"minHeightUnit":"px","contentPosition":"center center","align":"full","style":{"spacing":{"padding":{"top":"0","right":"0","bottom":"0","left":"0"}},"color":{}}} -->
<div class="wp-block-cover alignfull" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0;min-height:450px"><span aria-hidden="true" class="wp-block-cover__background has-contrast-background-color has-background-dim-100 has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:group {"templateLock":false,"lock":{"move":false,"remove":false},"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","right":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50"}}},"textColor":"base","layout":{"type":"constrained","justifyContent":"center"}} -->
<div class="wp-block-group alignfull has-base-color has-text-color" style="padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--50)"><!-- wp:group {"align":"wide","layout":{"type":"constrained","justifyContent":"left"}} -->
<div class="wp-block-group alignwide"><!-- wp:heading {"style":{"typography":{"textTransform":"none"}}} -->
<h2 style="text-transform:none">Write a Call to Action Here!</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"style":{"spacing":{"margin":{"bottom":"var:preset|spacing|30"}}},"fontSize":"medium"} -->
<p class="has-medium-font-size" style="margin-bottom:var(--wp--preset--spacing--30)">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"style":{"spacing":{"margin":{"bottom":"10px"}},"typography":{"textTransform":"uppercase","letterSpacing":"0.5px"}},"fontSize":"medium"} -->
<div class="wp-block-buttons has-custom-font-size has-medium-font-size" style="margin-bottom:10px;letter-spacing:0.5px;text-transform:uppercase"><!-- wp:button {"backgroundColor":"base","textColor":"contrast"} -->
<div class="wp-block-button"><a class="wp-block-button__link has-contrast-color has-base-background-color has-text-color has-background wp-element-button" href="#">Button One</a></div>
<!-- /wp:button -->

<!-- wp:button {"textColor":"base","className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-base-color has-text-color wp-element-button" href="#">Button Two</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover -->
```

### Screenshots, screen recording, code snippet

**Walkthrough**
https://user-images.githubusercontent.com/4832319/200827957-df2b3a3f-f508-4556-b5fd-81ac3a68699f.mp4

### Environment info

- WordPress 6.1
- Gutenberg 14.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Resolves #45625.

PR fixes the content loss bug when a Cover block has the `templateLock` attribute set to `all` or `contentOnly`.

## Why?
The `useInnerBlockTemplateSync` hook will try to replace inner blocks with the default template when the template is meant to be locked.

It ensures templates are always in sync, which is handy for post-type templates in the editor. But it can cause content loss when a block has a default template, and `templateLock` can be defined directly on it.

## How?
We can skip synchronizing by omitting the default template when a Cover already has inner blocks.

Ideally, we might want to adjust `shouldApplyTemplate` inside the `useInnerBlockTemplateSync`, but that's a significant change for a minor release patch.

## Testing Instructions
See the original issue for reproduction steps - #45625.

Also, confirm that the default template is correctly inserted for a new Cover block.

### CODE REVIEW

File: packages/block-library/src/cover/edit/index.js [hunk 1]
```diff
@@ -188,7 +188,7 @@ function CoverEdit( {
 			className: 'wp-block-cover__inner-container',
 		},
 		{
-			template: innerBlocksTemplate,
+			template: ! hasInnerBlocks ? innerBlocksTemplate : undefined,
```
Comment (Mamaduka) [inline packages/block-library/src/cover/edit/index.js:193]: If we decide to go with this fix, I will add an inline comment.

**Comment by ndiego** [comment]
Just tested and this is working perfectly now, no loss of content. Here is a quick screencap showing that applying the `templateLock` no longer strips inner content. 

cover-templatelock

**Review by ndiego — APPROVED** [review]

**Comment by youknowriad** [comment]
The fix is correct but there's indeed a reflexion to be had for the future on these props. It seems we might need two kind of templates: initialTemplate and a regular template prop.

**Review by youknowriad — APPROVED** [review]

**Comment by Mamaduka** [comment]
Thanks for the reviews, @ndiego, and @youknowriad!
