### PR TITLE
Remove the lightbox filter and view file when the lightbox setting is disabled.

### LINKED ISSUE #55119: Image block lightbox: setting lightbox on an image makes all following images open in the lightbox
### Description

This can be reproduced also in WordPress core with Gutenberg disabled so is needs to be fixed before the 6.4 release.
Cc @annezazu @bph @mikachan @SiobhyB @karmatosed @hellofromtonya 

When a post has more than one Image block, setting one of the image to open in the lightbox makes all following imges open in the lightbox, even if their lightbox setting is disabled.

This is clearly not the expected beheavior.

This filter rund at priority 15:

https://github.com/WordPress/gutenberg/blob/f04f5c5ee7875bd858d35891565f1b7f736c772f/packages/block-library/src/image/index.php#L72

The filter is never removed. That means the lightbox markup and view file are added to all the blocks after the first block that has the lightbox enabled.

That also highlights that the lighbox feature has never been tested with more than one image, which is  a little surprising.

### Step-by-step reproduction instructions

- Create a post.
- Add four image blocks.
- Set only the second image block to open the image in the lightbox.
- Publish annd view the front end.
- Obzerv the first image has no lightbox enabled.
- Observe the second image has the lightbox enabled, as expected.
- Observe the third image  has the lightbox enabled: wrong.
- Observe the fourth image  has the lightbox enabled: wrong.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by afercia**
Fixes https://github.com/WordPress/gutenberg/issues/55119

## What?

With multiple image block on a page, setting one image to open in the lightbox makes all following images open in the lightbox, even if the related setting is disabled.

## Why?

Clearly not the expected behavior.

## How?

- Makes sure the filter that adds the lightbox markup and the view JavaScript file are removed when not needed.
- Simplifies the code as there is really no need to set a `$lightbox_enabled` flag that stays true for all the following blocks.

## Testing Instructions

- Create a post.
- Add four image blocks.
- Set only the second image block to open the image in the lightbox.
- Publish and view the front end.
- Observe the first image has no lightbox enabled.
- Observe the second image does have the lightbox enabled, as expected.
- Check the lightbox works as expected.
- Observe the third image has no lightbox enabled, as expected.
- Observe the fourth image has no lightbox enabled, as expevted.

Additionally:
- Set only the first image to open in the lightbox.
- Save and view the front end.
- Observe that only the first image opens in the lightbox.
- Check the lightbox works as expected.

### CODE REVIEW

File: packages/block-library/src/image/index.php [hunk 1]
```diff
@@ -32,44 +32,46 @@ function render_block_core_image( $attributes, $content, $block ) {
...
-
-	// Determine whether the view script should be enqueued or not.
-	$view_js_file = 'wp-block-image-view';
-	if ( ! wp_script_is( $view_js_file ) ) {
-		$script_handles = $block->block_type->view_script_handles;
 
-		// If the script is not needed, and it is still in the `view_script_handles`, remove it.
-		if ( ! $lightbox_enabled && in_array( $view_js_file, $script_handles, true ) ) {
-			$block->block_type->view_script_handles = array_diff( $script_handles, array( $view_js_file ) );
+		if ( ! in_array( $view_js_file_handle, $script_handles, true ) ) {
```
Comment (artemiomorales) [inline packages/block-library/src/image/index.php:53]: It appears that when running this code when the lightbox is enabled for just the first image block, `$script_handles` contains the `'wp-block-image-view'` handle, so this conditional erroneously evaluates to `false` and the view script is not loaded, resulting in the following error:

Screenshot 2023-10-06 at 4 36 22 PM

**Review by artemiomorales — CHANGES_REQUESTED** [review]
Thanks for opening this PR! I tested and while the code works when the lightbox is enabled for the second or subsequent images, it does _not_ work when the lightbox is enabled on the first image, resulting in an error (see comment below).

I think this requires a little reworking of the logic. Here's a suggested revision that will only remove the view script if the lightbox settings are absent or the lightbox is disabled, which seems to work, though there are lots of ways of doing this and you may have ideas on how else we can clearly express the intent:

```
/*
* Remove the filter and the JavaScript view file if previously added by
* other Image blocks.
*/
remove_filter( 'render_block_core/image', 'block_core_image_render_lightbox', 15 );

/*
* If the lightbox is enabled and the image is not linked, add the filter
* and the JavaScript view file.
*/
if ( isset( $lightbox_settings ) && 'none' === $link_destination ) {

	if( isset( $lightbox_settings['enabled'] ) && true === $lightbox_settings['enabled'] ) {
		$block->block_type->supports['interactivity'] = true;

		if ( ! in_array( $view_js_file_handle, $block->block_type->view_script_handles, true ) ) {
			$block->block_type->view_script_handles = array_merge( $script_handles, array( $view_js_file_handle ) );
		}

		/*
		* This render needs to happen in a filter with priority 15 to ensure
		* that it runs after the duotone filter and that duotone styles are
		* applied to the image in the lightbox. We also need to ensure that the
		* lightbox works with any plugins that might use filters as well. We
		* can consider removing this in the future if the way the blocks are
		* rendered changes, or if a new kind of filter is introduced.
		*/
		add_filter( 'render_block_core/image', 'block_core_image_render_lightbox', 15, 2 );
	} else {
		// If the script is not needed, and it is still in the `view_script_handles`, remove it.
		if ( in_array( $view_js_file_handle, $script_handles, true ) ) {
			$block->block_type->view_script_handles = array_diff( $script_handles, array( $view_js_file_handle ) );
		}
	}

}

return $processor->get_updated_html();
```

**Comment by afercia** [comment]
@artemiomorales thanks. Right, I think one of my last changes aimed to avoid the if / else but I see it is necessary instead.

**Comment by afercia** [comment]
An E2E test related to the cover image keeps failing.

```
editor/blocks/cover.spec.js:74:2 › Cover › dims background image down by 50% with the average image color when an image is uploaded 
```

It passes locally for me. It seems completely unrelated to the changes in this PR. I'll try to rebase onto latest trunk but if it keeps failing I't need some help to understand why.

**Comment by tellthemachines** [comment]
> An E2E test related to the cover image keeps failing.

This was just fixed in #55168 so another rebase should get it to pass!

**Comment by afercia** [comment]
Rebased on top of latest trunk. Hopefully the failing test should now pass.

**Comment by afercia** [comment]
Qustion: should this:

`$block->block_type->supports['interactivity'] = true;`

be reverted to `false` in the `else`?
I have no idea what that code line actually does. Any feedback would be appreciated.

**Review by artemiomorales — APPROVED** [review]
This works as expected now 🙌

File: packages/block-library/src/image/index.php [hunk 2]
```diff
@@ -32,45 +32,47 @@ function render_block_core_image( $attributes, $content, $block ) {
...
+	 * If the lightbox is enabled and the image is not linked, add the filter
+	 * and the JavaScript view file.
+	 */
+	if (
+		isset( $lightbox_settings ) &&
+		'none' === $link_destination &&
+		isset( $lightbox_settings['enabled'] ) &&
+		true === $lightbox_settings['enabled']
+	) {
 		$block->block_type->supports['interactivity'] = true;
```
Comment (afercia) [inline packages/block-library/src/image/index.php:51]: @artemiomorales @SantosGuillamot when you have a chance, I'd appreciate your feedback on this line of code:
- I have no idea what it does.
- Is it really necessary?
- If it is, should it be changed back to `false` in the `else` statement?

Comment (artemiomorales) [reply packages/block-library/src/image/index.php:51]: From what I understand, that line moves the interactivity scripts to the footer, which is a helpful optimization.
It shouldn't be changed to `false`, because it should be `true` so long as any image has the lightbox enabled.

Pinging @luisherranz to see if he'd like to detail better! In any case, I don't believe a change here is a blocker for this PR.

Comment (luisherranz) [reply packages/block-library/src/image/index.php:51]: We're actually thinking about removing the conditionality and use `supports.interactivity: true` for any block that _might_ be interactive at some point. 

But we also need to figure out how those conditional interactive blocks can declare that conditionality, or even be able to combine different interactive behaviors depending on their configuration.

Related conversation here: 
- https://github.com/WordPress/gutenberg/discussions/54194

**Comment by mikachan** [comment]
I just cherry-picked this PR to the 6.4-rc1 branch to get it included in the next release: 63bba04357
