### PR TITLE
Post Excerpt Block: Fix length limits for both Editor and Front and fix ellipsis consistency.

### LINKED ISSUE #74133: Post Excerpt: Missing ellipsis on the front of the site when the read more link is added
### Description

The ellipsis is missing on the front of the site when the read more link is added. It looks strange without it.

Image

The ellipsis is there in the editor, which makes sense. 

Image

### Step-by-step reproduction instructions

* Use TT4 or a theme that uses the post excerpt block.
* Make sure you have a long enough content, more than the length of the excerpt.
* Add read more link in the template
* See the discrepancy in the ellipsis between the editor and the front of the site.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WP 6.9
Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by ItsYash1421**
Fixes #74133

## What?
Closes #74133

Adds the missing ellipsis (…) to the Post Excerpt block on the frontend when the excerpt is trimmed and a read more link is present.

## Why?
The ellipsis was correctly displayed in the editor but missing on the frontend, creating an inconsistent user experience. When users add a "read more" link to a trimmed excerpt, the ellipsis should appear to indicate the content continues, matching the editor preview.

## How?
- Track whether the excerpt was actually trimmed by storing the original excerpt and comparing it with the trimmed version
- Pass an empty string as the third parameter to `wp_trim_words()` to prevent it from automatically adding its own ellipsis
- Manually add `&hellip;` when the excerpt is trimmed and displayed inline with the read more link

## Testing Instructions
1. Use TT4 or any block theme
2. Create a new post with long content (more than 55 words in the excerpt or content)
3. Go to the Site Editor and edit a template that displays posts (e.g., Home or Archive template)
4. Add or locate the Post Excerpt block
5. In the block settings, add "Read more" text (e.g., "Continue reading")
6. Test with "Show link on new line" disabled (inline mode)
7. Save the template and view the frontend
8. Verify the ellipsis (…) now appears before the "Read more" link
9. Also test with "Show link on new line" enabled to ensure no regression

### Testing Instructions for Keyboard
1. Navigate to the Post Excerpt block using Tab key
2. Press Enter to select the block
3. Use Tab to navigate to the block settings sidebar
4. Use arrow keys to navigate to "Read more" text field
5. Type "Read more" text
6. Tab to "Show link on new line" toggle and test both states with Space key
7. Save and verify on frontend using keyboard navigation

### CODE REVIEW

**Review by SirLouen — CHANGES_REQUESTED** [review]
## Test Report
### Description
❌ This report can't validate that the indicated patch works as expected.

### Environment
- WordPress: 7.0-alpha-61215-src
- PHP: 8.2.29
- Server: nginx/1.29.3
- Database: mysqli (Server: 8.4.7 / Client: mysqlnd 8.2.29)
- Browser: Chrome 143.0.0.0
- OS: Windows 10/11
- Theme: Twenty Twenty-Three 1.6
- MU Plugins: None activated
- Plugins:
  * Gutenberg 22.3.0
  * Test Reports 1.2.1

### Testing Instructions
1. Using TT3 theme
2. Added the Read more
3. 🐞 The ellipsis only appears on the editor, not in the frontend

### Actual Results
1.  ❌ Issue resolved with patch.

### Supplemental Artifacts
Editor:
Image


Frontend:
Image

**Review by SirLouen — CHANGES_REQUESTED** [review]
@ItsYash1421 you have not changed anything in the last 3 commits, only added and removed package.json, and changed the unit tests.

**Comment by ItsYash1421** [comment]
> @ItsYash1421 you have not changed anything in the last 3 commits, only added and removed package.json, and changed the unit tests.

The changes are working fine here is screenshots after applying changes.

In editor:
Screenshot 2025-12-21 at 8 16 23 PM

In Frontend:
Screenshot 2025-12-21 at 8 17 54 PM

**Comment by SirLouen** [comment]
@ItsYash1421 please use this playground instance to test:

https://playground.wordpress.net/?gutenberg-pr=74140&theme=twentytwentythree&blueprint-url=https%3A%2F%2Fgist.githubusercontent.com%2FSirLouen%2Fc007290ea9fb989c949156b2a32b6e41%2Fraw%2F47bca479ed85265f9b356e75058e1cc87d5716ad%2Fblueprint.json

Blueprint: https://gist.githubusercontent.com/SirLouen/c007290ea9fb989c949156b2a32b6e41/raw/47bca479ed85265f9b356e75058e1cc87d5716ad/blueprint.json

https://github.com/user-attachments/assets/585d8cbe-62f5-44b9-8334-8e74743483fe

**Comment by ItsYash1421** [comment]
> @ItsYash1421 please use this playground instance to test:
> 
> https://playground.wordpress.net/?gutenberg-pr=74140&theme=twentytwentythree&blueprint-url=https%3A%2F%2Fgist.githubusercontent.com%2FSirLouen%2Fc007290ea9fb989c949156b2a32b6e41%2Fraw%2F47bca479ed85265f9b356e75058e1cc87d5716ad%2Fblueprint.json
> 
> Blueprint: https://gist.githubusercontent.com/SirLouen/c007290ea9fb989c949156b2a32b6e41/raw/47bca479ed85265f9b356e75058e1cc87d5716ad/blueprint.json
> 

its working their too.

image

**Comment by SirLouen** [comment]
@ItsYash1421 we are doing something differently for sure. Can you share a screencast of the whole process?

**Comment by ItsYash1421** [comment]
> @ItsYash1421 we are doing something differently for sure. Can you share a screencast of the whole process?


https://github.com/user-attachments/assets/90f253af-64c4-4c27-b4bb-18b12d5bce65

**Comment by ItsYash1421** [comment]
I think it was not working with Number of words more than 55

**Comment by SirLouen** [comment]
> I think it was not working with Number of words more than 55

I was not touching the number of words, so yes, probably. This must work for all numbers.

**Comment by ItsYash1421** [comment]
> > I think it was not working with Number of words more than 55
> 
> I was not touching the number of words, so yes, probably. This must work for all numbers.

i fixed it in latest commit please check

File: packages/block-library/src/post-excerpt/index.php [hunk 1]
```diff
@@ -37,6 +37,10 @@ function render_block_core_post_excerpt( $attributes, $content, $block ) {
 	 * Otherwise, the read more link filter from the theme is not removed.
 	 */
 	add_filter( 'excerpt_more', $filter_excerpt_more );
+	$filter_excerpt_length = static function () {
```
Comment (SirLouen) [inline packages/block-library/src/post-excerpt/index.php]: Not sure if this is the best fix. I have a hunch that there is probably something intrinsecal, maybe in Core. More research is required here.

**Review by SirLouen — CHANGES_REQUESTED** [review]

File: packages/block-library/src/post-excerpt/index.php (hunk 1 above)
Comment (ItsYash1421) [reply packages/block-library/src/post-excerpt/index.php]: The issue is that WordPress Core's get_the_excerpt() applies the excerpt_length filter (default 55 words) during frontend rendering. The editor avoids this by getting the raw excerpt via REST API (which already has the filter override).

My fix extends this same pattern to frontend rendering, ensuring consistency between editor and frontend for excerpt lengths 56-100 words. This mirrors the existing approach rather than introducing a new pattern.

Comment (SirLouen) [reply packages/block-library/src/post-excerpt/index.php]: I've tried over 55 and its not showing in the ellipsis frontend. 
Anyway I don't like the filter solution. I will give it a thought on how to improve it

Comment (ItsYash1421) [reply packages/block-library/src/post-excerpt/index.php]: ok

**Review by SirLouen — APPROVED** [review]
I've reviewed this, and now it looks legit.

Here are the changes (this is easily visible in Twenty Twenty Three theme)
Currently the excerpts display can only handle correctly the manual excerpts. But if we are using the automatic excerpts, there are inconsistencies between the editor and the front end.

The solution is to extend a little the current flow to have a unified mechanism to display for both the automatic and manual excerpt the limit of the RangeControl (100 words).

Using this url for testing (with 2023 theme):
`/wp-admin/site-editor.php?p=%2Fwp_template%2Ftwentytwentythree%2F%2Findex&canvas=edit`

Adding or not adding `Read More` as pointed out in #74133 should be irrelevant; in any case, with and without `Read More` and for automatic and manual excerpts, it should behave identically: if there are more words available than the maximum selected in the `RangeControl` the ellipsis should appear for both editor and frontend.

### Editor:

Image

### Frontend

Image

cc @ntsekouras I noticed you worked in the render excerpt part, could you do a final second review to double check everything is in order now?

File: packages/block-library/src/post-excerpt/index.php [hunk 2]
```diff
@@ -86,18 +96,31 @@ function register_block_core_post_excerpt() {
...
-		PHP_INT_MAX
-	);
+function block_core_post_excerpt_excerpt_length() {
+	return 101;
 }
+
+if ( is_admin() ) {
+	add_filter( 'excerpt_length', 'block_core_post_excerpt_excerpt_length', PHP_INT_MAX );
+}
+add_action(
```
Comment (ntsekouras) [inline packages/block-library/src/post-excerpt/index.php:121]: I'm wondering if this change affects anything. Do you know why we had `defined( 'REST_REQUEST' ) && REST_REQUEST )` (essentially [wp_is_serving_rest_request](https://developer.wordpress.org/reference/functions/wp_is_serving_rest_request/))?

It seems this change to have the same effect, but I might be missing something.

File: packages/block-library/src/post-excerpt/index.php [hunk 3]
```diff
@@ -86,18 +96,31 @@ function register_block_core_post_excerpt() {
...
-	defined( 'REST_REQUEST' ) && REST_REQUEST ) {
-	add_filter(
-		'excerpt_length',
-		static function () {
-			return 100;
-		},
-		PHP_INT_MAX
-	);
+function block_core_post_excerpt_excerpt_length() {
+	return 101;
```
Comment (ntsekouras) [inline packages/block-library/src/post-excerpt/index.php:115]: There are so many nuances with excerpt and all the different filters.. Why `101` is the magic number? 

Why it works when we don't add a `read more` label and fails when we do (in trunk).

Said that, in general the `Read More` standalone block is more flexible and should be preferred over this label from excerpt block. I should probably revive [this old PR](https://github.com/WordPress/gutenberg/pull/38662) that hides it by default..

Comment (SirLouen) [reply packages/block-library/src/post-excerpt/index.php:115]: Basically the limit in the `RangeControl` is 100. So if you return 100, you will not see the ellipsis (100+1).

File: packages/block-library/src/post-excerpt/index.php (hunk 2 above)
Comment (SirLouen) [reply packages/block-library/src/post-excerpt/index.php:121]: This was proposed for #48654 and @mcsf got some concerns that were not addressed in #44964. The problem is that he is not addressing either the problem of the frontend, the ellipsis variations (difference between `...` and `[...]`  and the scenario of the automatic excerpts). 

The problem is that there was no unified logic. 

Now the logic is unified for all 3 cases
-  For admin, it will called inmediately during `init`
- For REST API Requests (in this case in for the editor) its called  via `rest_api_init`. 
- Frontend, on ìnit`

Before it was calling during `init` but `REST_REQUEST` was not defined yet. So for the manual excerpts it worked well, but for the automatic excerpts that were built through the API, it was not building the right excerpt. In fact by default in Core, manual excerpts should be shown completely, and what it's handled is the lenght of the automatic excerpts (not the other way around as it's being done here).

File: packages/block-library/src/post-excerpt/index.php [hunk 4]
```diff
@@ -39,13 +39,23 @@ function render_block_core_post_excerpt( $attributes, $content, $block ) {
...
-	* Because the excerpt_length filter only applies to auto generated excerpts,
-	* wp_trim_words is used instead.
-	*/
+	 * The purpose of the excerpt length setting is to limit the length of both
+	 * automatically generated and user-created excerpts.
+	 * Because the excerpt_length filter only applies to auto generated excerpts,
+	 * wp_trim_words is used instead.
+	 *
+	 * To ensure the block's excerptLength setting works correctly for auto-generated
+	 * excerpts, we temporarily override excerpt_length to 100 (the max block setting)
```
Comment (ntsekouras) [inline packages/block-library/src/post-excerpt/index.php]: This should be `to 101`, no? A small rewording here to either mention 101 and that 100 is the max setting or something like override to `x + 1` of the maximum setting.

File: packages/block-library/src/post-excerpt/index.php (hunk 3 above)
Comment (ntsekouras) [reply packages/block-library/src/post-excerpt/index.php:115]: Ok, got it.

**Review by ntsekouras — APPROVED** [review]
Left a small docs comment but this seems to be fine. Something related that could be handled either here or separately, is a small inconsistency between editor and front-end for custom excerpts. 

I tested a post with a big custom excerpt (more than 100 words) and in the editor we show one more word than the front-end.

**Comment by SirLouen** [comment]
> I tested a post with a big custom excerpt (more than 100 words) and in the editor we show one more word than the front-end.

@ntsekouras I cannot reproduce this for automatic excerpts (this is what we are targeting in this PR)

Although its true that in manual, in the editor there are even 3 words more

### 100 words set in the slider

Before

|*|Front|Editor|
|-|-|-|
|Manual|100|103|
|Automatic|55|55|

After

|*|Front|Editor|
|-|-|-|
|Manual|100|103|
|Automatic|100|100|

So this is ready to be merged now

I've been reviewing the code, and it appears that the word splitter was doing the thing wrong. 
Although, I've opened a new PR to handle this independently, as this is not related to this ticket #74925

File: packages/block-library/src/post-excerpt/index.php [hunk 5]
```diff
@@ -86,18 +96,31 @@ function register_block_core_post_excerpt() {
...
+
+if ( is_admin() ) {
+	add_filter( 'excerpt_length', 'block_core_post_excerpt_excerpt_length', PHP_INT_MAX );
+}
+add_action(
+	'rest_api_init',
+	static function () {
+		add_filter( 'excerpt_length', 'block_core_post_excerpt_excerpt_length', PHP_INT_MAX );
+	}
+);
```
Comment (xavier-lc) [inline packages/block-library/src/post-excerpt/index.php:126]: I've noticed that this change breaks the utility of the `exceprt_length` param on API requests.

#### Before:

The word count on the output matches the `excerpt_length` param.

> curl -H "Authorization: Basic ***"    "http://localhost:8888/wp-json/wp/v2/posts/35?context=edit&_fields=excerpt&excerpt_length=4"
>
> {"excerpt":{"raw":"","rendered":"<p>What is Lorem Ipsum? [&hellip;]<\/p>\n","protected":false}}


> curl -H "Authorization: Basic ***"    "http://localhost:8888/wp-json/wp/v2/posts/35?context=edit&_fields=excerpt&excerpt_length=20"
> 
> {"excerpt":{"raw":"","rendered":"<p>What is Lorem Ipsum? Lorem Ipsum\u00a0is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the [&hellip;]<\/p>\n","protected":false}}

#### After:

The word count on the output is always 101

> curl -H "Authorization: Basic ***"    "http://localhost:8888/wp-json/wp/v2/posts/35?context=edit&_fields=excerpt&excerpt_length=20"
> 
> {"excerpt":{"raw":"","rendered":"<p>What is Lorem Ipsum? Lorem Ipsum\u00a0is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#8217;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Why do we use it? It is [&hellip;]<\/p>\n","protected":false}}

@ItsYash1421 @SirLouen @ntsekouras

Comment (SirLouen) [reply packages/block-library/src/post-excerpt/index.php:126]: Thanks for reporting, I'm looking into it

File: packages/block-library/src/post-excerpt/index.php [hunk 6]
```diff
@@ -39,13 +39,23 @@ function render_block_core_post_excerpt( $attributes, $content, $block ) {
...
+	 * so that wp_trim_excerpt doesn't pre-trim the content before wp_trim_words can
+	 * apply the user's desired length.
+	 */
 	$excerpt_length = $attributes['excerptLength'];
-	$excerpt        = get_the_excerpt( $block->context['postId'] );
+	add_filter( 'excerpt_length', 'block_core_post_excerpt_excerpt_length', PHP_INT_MAX );
+
+	$excerpt = get_the_excerpt( $block->context['postId'] );
+
+	remove_filter( 'excerpt_length', 'block_core_post_excerpt_excerpt_length', PHP_INT_MAX );
```
Comment (ellatrix) [inline packages/block-library/src/post-excerpt/index.php:57]: Note that this requires us to update a core rest controller: https://github.com/WordPress/wordpress-develop/pull/10865/changes#diff-48cfdad3b747164ac4b6857186399519dabf913026235575b00ebe5b0dc7169bL1991
