### PR TITLE
Image: Reflect media deletion in the editor

### LINKED ISSUE #23262: Deleting an image via the media library is not reflected.
Deleting an image permanently on the media library is not reflected to the related image block.

**Step to reproduce**
1. Click the "Replace" menu item to open the media library.
2. Delete the image permanently.
3. Click the X button to close the media libarary.
4. The image is still displayed in the image block.
5. Actually the image is not deleted and the frontend still has it.

**Expected behavior**
The image should be removed from the image block in sync with the media library, and the image itself is to be deleted from the server.

**Screenshots**
Animation

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Both.
- If the Gutenberg plugin is installed, which version is it?  v8.3.0 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 83.0.4103.106

### LINKED ISSUE #28914: Deleted media in Media Library still seen in the post or page.
## Description

I tested this issue. https://github.com/WordPress/gutenberg/issues/11501
The issue itself is not valid any longer, but the point came up that deleting an image from the media library will still show the image in the post or page if it has been used.

When deleting an image (or perhaps audio file) from the Media library it should not still be visible in a post or page, but instead show the Image block placeholder.

## Step-by-step reproduction instructions

1. Add an image to the Media Library.
2. Go to a post. Add the Image block. Add an image. Publish the post.
3. Go to the Media Library and delete the image used in the post.
4. Go back to the post and notice the image is still seen as if it was not deleted.

## Expected behaviour

After having deleted the image from the media library
Going back to the post or page the image should not be visible. 
There should be a placeholder mentioning that the image has been deleted and that one now needs to replace it with another image.

Actually using the standard placeholder can work:

Screen Shot 2021-02-10 at 12 27 10

## Actual behaviour
Deleting the image in the Media Library still shows the image in the post or page.

### PR DESCRIPTION
**Pull request by ramonjd**
## Description

Looking at fixes for https://github.com/WordPress/gutenberg/issues/23262

It should close https://github.com/WordPress/gutenberg/issues/28914 as well.

Very rough start.

So far we're:

1. Listening out for when the Media Modal closes and checking the media collection for destroyed entries.
2. Checking the "loadability"&copy; of every Image's url via `new Image()`

## How to test

1. Insert a single Image Block and select an image from your media library. Or upload a new image. All good. Add a caption as well.
2. Open the Media Modal by clicking **Replace**
3. Delete the image you inserted.
4. Close the modal
5. The Image Block placeholder should show.
6. Now refresh the page. Don't save. Just refresh.
7. The Image Block placeholder should still show.

Repeat steps 1-7 but add multiple images, including the new Gallery block (with Image InnerBlocks), ensuring that the same image appears multiple times in your post.

To test that image embed replacement still works, insert a new Image Block and use an url from an image service, e.g., https://www.flickr.com/photos/normanwest4tography/51737773160/in/explore-2021-12-11/ 

See [Embeds](https://wordpress.org/support/article/embeds/) for a list of embeddable image sources.

Repeat steps 1-7, but at step 3, after you've deleted the image, select another image to replace the deleted one. If you've added a caption, the caption should persist.

## Screenshots 

https://user-images.githubusercontent.com/6458278/141960844-f38a4fcb-8963-4d02-a759-7570d10efe95.mp4

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/media-utils/src/components/media-upload/index.js [hunk 1]
```diff
@@ -270,6 +273,11 @@ class MediaUpload extends Component {
 		this.frame.on( 'update', this.onUpdate );
 		this.frame.on( 'open', this.onOpen );
 		this.frame.on( 'close', this.onClose );
+		this.frame.listenTo(
+			wp.media.model.Attachments.all,
+			'remove',
+			this.onRemoveSelectedAttachment
```
Comment (ramonjd) [inline packages/media-utils/src/components/media-upload/index.js]: I'm thinking we need to set up a store for `media-utils` to track deleted attachments so other blocks can use a selector to check if specific image ids are deleted.

Then we could dispatch the action here with the deleted attachment.

To use `useDispatch` we first might need to turn `MediaUpload` into a function component.

Comment (ramonjd) [reply packages/media-utils/src/components/media-upload/index.js]: > To use useDispatch we first might need to turn MediaUpload into a function component.

WIP

https://github.com/WordPress/gutenberg/pull/36131

File: packages/block-library/src/image/edit.js [hunk 2]
```diff
@@ -87,6 +87,20 @@ function hasDefaultSize( image, defaultSize ) {
 	);
 }
 
+/**
+ * Checks if a media attachment object has been "destroyed",
+ * that is, removed from the media library. The core Media Library
+ * add a `destroyed` property to a deleted attachment object in the media collection.
```
Comment (glendaviesnz) [inline packages/block-library/src/image/edit.js]: a tiny typo  - `adds`

File: packages/block-library/src/image/edit.js [hunk 3]
```diff
@@ -87,6 +87,20 @@ function hasDefaultSize( image, defaultSize ) {
...
+ * Checks if a media attachment object has been "destroyed",
+ * that is, removed from the media library. The core Media Library
+ * adds a `destroyed` property to a deleted attachment object in the media collection.
+ *
+ * @param {number} id The attachment id.
+ *
+ * @return {boolean} Whether the image has been destroyed.
+ */
+function isMediaDestroyed( id ) {
+	const attachment = wp?.media?.attachment( id ) || {};
```
Comment (glendaviesnz) [inline packages/block-library/src/image/edit.js:100]: Not sure what the 'standard' approach is as this file already used `/* global wp */` but the other [use of this in media related file ](https://github.com/WordPress/gutenberg/blob/trunk/packages/media-utils/src/components/media-upload/index.js#L12)uses `const { wp } = window;`

Comment (ramonjd) [reply packages/block-library/src/image/edit.js:100]: I followed the existing examples in `image/edit.js` but now I look, `const { wp } = window;` seems to be used more often. I'm also not sure about this one either.

**Comment by glendaviesnz** [comment]
This tested well for me, the only thing that doesn't work, and this is probably an edge case we don't need to worry about, is deleting multiple images while in a gallery context:
image-delete

The same thing happens if you have multiple images on the page, and delete them all in the media library - only the one he fired the media library open call reflects the deletion. I don't know that this has to hold up this PR, but just mentioning it in case you can see any wider implications of this or can see an easy fix for it.

**Comment by ramonjd** [comment]
> The same thing happens if you have multiple images on the page, and delete them all in the media library - only the one he fired the media library open call reflects the deletion. I don't know that this has to hold up this PR, but just mentioning it in case you can see any wider implications of this or can see an easy fix for it.

Thanks for raising this. I also came across this phenomenon, but couldn't find a neat way way to trigger a rerender for the entire post. 

There's probably a way. I was thinking along the following lines:

```
If one or more images have been deleted:
    check the post for image blocks
        check whether each image has been destroyed
           if there are destroyed images in the block list:
              rerender block list
```
In a [previous commit on this PR](https://github.com/WordPress/gutenberg/pull/35973/commits/6c2e8736cfb777696193453f6bb6fd5c1fc39899#diff-1ee0f3c9ecb27cc1599a5d4a4020ff32f4e3ad111953a4c0310e35df1ece8854R165), I added a `useEffect` that triggered a isDestroyed check when `isSelected === true`. So the placeholder would show on a destroyed image when you selected it.

I decided to hold off on that until a later iteration, as I wanted to validate the basic approach before adding more fluff.

**Comment by glendaviesnz** [comment]
> I decided to hold off on that until a later iteration, as I wanted to validate the basic approach before adding more fluff.

I think the basic approach here is looking pretty good, and probably for the edge case where multiple images are deleted updating the related images when `isSelected` is probably enough of a fix - trying to check the whole document and reload the whole block tree might add a lot of complexity and overhead than is warranted. I would be tempted to put that bit back into this PR and see how it looks/works in combination with the rest of it.

**Comment by ramonjd** [comment]
> I would be tempted to put that bit back into this PR and see how it looks/works in combination with the rest of it.

Will do! It would be great to get it tested by someone who is not me too. 🍺

**Comment by ramonjd** [comment]
> I would be tempted to put that bit back into this PR and see how it looks/works in combination with the rest of it.

Thanks for the nudge on this one @glendaviesnz 

Seems actually to be a nice little upgrade 

https://user-images.githubusercontent.com/6458278/145923343-ed88993b-b46a-40c4-bc99-e3328cab1fe8.mp4

**Comment by glendaviesnz** [comment]
This tests well for me - this seems like a pretty robust fix for the single image deletion, and a `good enough` fix for the multiple deletion edge case.

One last question at this point - should we be assuming that on deleting the image the user also expects the `alt`, `title`, `caption` fields to also be wiped? Currently, if you replace an image the caption you have added to the block remains, so I wonder if we should do the same even though there is a deletion in the middle?

**Comment by ramonjd** [comment]
> One last question at this point - should we be assuming that on deleting the image the user also expects the alt, title, caption fields to also be wiped?

Good question. I didn't consider that angle 🤔, and assumed that metadata should also be deleted with the image.

I was taking the lead from the way [we already clear the attributes if we can't find the media properties](https://github.com/WordPress/gutenberg/blob/6859bd6d4144ac505f8d2b60c71cd43ec115a069/packages/block-library/src/image/edit.js#L182).

I can imagine that one might delete the image and select another one at the same time. Looking at it that way, it could be annoying to have the data wiped.

What do you reckon?

**Comment by glendaviesnz** [comment]
> I can imagine that one might delete the image and select another one at the same time. Looking at it that way, it could be annoying to have the data wiped.
> What do you reckon?

I imagine that 50% of users will want the data to stay and 50% for it to be cleared 😄 Maybe, given that it is easier to highlight and overwrite text you thought should have been wiped than to remember and rewrite the text you had hoped would stay, we start with keeping it?

**Comment by ramonjd** [comment]
> I imagine that 50% of users will want the data to stay and 50% for it to be cleared 😄 Maybe, given that it is easier to highlight and overwrite text you thought should have been wiped than to remember and rewrite the text you had hoped would stay, we start with keeping it?

Ha! Too easy. I've also updated the test description.

**Review by glendaviesnz — APPROVED** [review]
Tests well for me 🎉

**Comment by paaljoachim** [comment]
I added the Backport label as I assume this will be backported to WP 5.9.

**Comment by tellthemachines** [comment]
@paaljoachim could you clarify why this needs to be backported to 5.9? At this stage in the release process, we should only backport regressions and fixes to the new features going into this release e.g. site editor, global styles and navigation block.

**Comment by paaljoachim** [comment]
Hi @tellthemachines I removed the Backport label.
