### PR TITLE
Debounce the ServerSideRender component's fetch

### LINKED ISSUE #7320: ServerSideRender component should debounce the request
**Describe the bug**
When using the new ServerSideRender component if you have a text control in the Inspector on each change event it sends a request to the Block API Endpoint without debouncing it. Also if one of your attributes is an array or an array of arrays or an array of objects it is not getting sent correctly to the REST API.

**To Reproduce**
1. Use the component that is found at this gist: https://gist.github.com/ivanlopez/3f415d805704e950a94ad62a4dd75981
2. After you install and add the component to the editor open your dev tools to the network tab in your browser.
3. Start typing in the text field in the inspector and you'll see that every change event fires a request to the Block API endpoint without debouncing or canceling the previous request.
4. Click on the buttons in the Inspector and you'll see that the response you get is not what you would expect. For a simple array you'll get the an array with a single value of all the items you sent. For nested array you will get all the items in one nested array. Finally for an array of objects the data is getting sent as [object Object]so the API can't process that request.

**Expected behavior**
I would expect that when using ServerSideRender request would get debounced. I would also expect that if you have an attribute with an array or an array of arrays or an array of objects that the ServerSideRender component would send the data correctly to the block API endpoint.

**Screenshots**
serversiderenderingtextcontrol

screen shot 2018-06-15 at 10 38 05 am

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser Chrome
 - Version 66.0.3359.181

**Additional context**
- Gutenberg 3.0.1

### PR DESCRIPTION
**Pull request by notnownikki**
## Description

Fixes: #7320 

Debounce fetch so that sliders and typing do not fire off a mini-DDOS.

## How has this been tested?

Create the block from https://gist.github.com/ivanlopez/3f415d805704e950a94ad62a4dd75981

Type in the text input in the inspector and check the number of HTTP requests. Hold down a key and check there aren't a stream of requests.

## Types of changes
Bug fix

### CODE REVIEW

File: packages/components/src/server-side-render/index.js [hunk 1]
```diff
@@ -34,6 +34,7 @@ export class ServerSideRender extends Component {
 		this.state = {
 			response: null,
 		};
+		this.fetch = debounce( this.fetch, 500 );
```
Comment (aduth) [inline packages/components/src/server-side-render/index.js]: The assignment of `this.isStillMounted` in `componentWillUnmount` is not enough for this, since there are logic paths of `fetch` which call `this.setState` directly without consideration of the instance value, thus resulting in errors / warnings.

We should do one of:

- Always consider `this.isStillMounted` at the beginning of `fetch` and in its callback handlers.
- Call `this.fetch.cancel()` in `componentWillUnmount`

**Review by aduth — CHANGES_REQUESTED** [review]
Any rhyme or reason to the choice of a half second? It's pretty short, but I'm not too concerned about it.

**Comment by notnownikki** [comment]
500 seemed to be a nice balance between keeping it responding in a way that doesn't look like it's been delayed, and not getting hammered by fast typers and sliders. I'm happy to increase it though, it was something I figured people would have opinions on :)

File: packages/components/src/server-side-render/index.js (hunk 1 above)
Comment (notnownikki) [reply packages/components/src/server-side-render/index.js]: The `setState` calls have a check for `this.isStillMounted` in the callbacks already, https://github.com/WordPress/gutenberg/blob/1084fe302b83affb547d22f193591eb1e2fa258a/packages/components/src/server-side-render/index.js#L65

Is there something I've missed there?

**Review by aduth — COMMENTED** [review]
Last question: Should we provide the `leading: true` option to allow the first fetch to occur undelayed?

https://lodash.com/docs/4.17.11#debounce

Otherwise LGTM

**Comment by notnownikki** [comment]
Looking at this a bit more, and although debouncing fixes #7320, we have the same race condition here as the autocompleters used to have. On an unreliable, slow, or high latency network, there could be multiple fetches happening at the same time and resolving in an unpredictable sequence. If we're ok merging this as-is, I can fix the race condition in a follow up PR.

**Comment by notnownikki** [comment]
@aduth would you be able to approve this?

**Comment by aduth** [comment]
Do you have thoughts on https://github.com/WordPress/gutenberg/pull/11300#issuecomment-435914900 ?

>Maybe the debounce could be applied in componentDidMount?

**Comment by notnownikki** [comment]
> Maybe the debounce could be applied in componentDidMount?

This works well. Having the very first fetch happen immediately, and all further fetches debounced makes the component feel nice and fast when the editor first renders, and still achieves what we need from this PR. I've pushed up a new commit with this behaviour.

I was also thinking, after this lands I could work on a `derace` util that wraps `apiRequest` to make sure that the code is only run if the request is the latest one, but that's a bit of a tangent for this one :)

**Comment by aduth** [comment]
>after this lands I could work on a derace util that wraps apiRequest to make sure that the code is only run if the request is the latest one, but that's a bit of a tangent for this one :)

I'd much prefer we opt to stop using `apiFetch` in components altogether in lieu of providing by `data` module, which was designed to handle these conditions much more cleanly.

File: packages/components/src/server-side-render/index.js [hunk 2]
```diff
@@ -39,6 +39,7 @@ export class ServerSideRender extends Component {
 	componentDidMount() {
 		this.isStillMounted = true;
 		this.fetch( this.props );
+		this.fetch = debounce( this.fetch, 500 );
```
Comment (aduth) [inline packages/components/src/server-side-render/index.js]: Could we maybe leave a comment explaining why this occurs here vs. in the constructor? It won't necessarily be obvious to the next maintainer.

```suggestion
		// Only debounce once the initial fetch occurs to ensure that the first
		// renders show data as soon as possible.
		this.fetch = debounce( this.fetch, 500 );
```

**Review by aduth — APPROVED** [review]
