### PR TITLE
Fix Link UI popover anchor in rich text

### LINKED ISSUE #58280: Link UI incorrectly anchored to "last" link within rich text contenteditable
If you have multiple links within a block of rich text then the Link UI will be "anchor" to ~the final~ first link you clicked in the block.

So if you click the first link in the block and then click on other links, the popover will continue to anchor to the first link. Similarly if you clicked the last link first, it would continue to anchor to that link.

It should be anchored to the link that triggers it. I suspect this is due to the way in which we recently changed the usage of `useAnchor` to cache the first position. 

https://github.com/WordPress/gutenberg/blob/ecda32e0911ee7e04e044b8a7351ee4841e94a19/packages/format-library/src/link/inline.js#L208-L215

https://github.com/WordPress/gutenberg/assets/444434/4d0d88d1-2800-4e45-9876-2ba955b22950

### PR DESCRIPTION
**Pull request by getdave**
## What?

Fixes bug where Link UI Popover anchor becomes divorced from the link that "owns" it (see Issue).

Closes https://github.com/WordPress/gutenberg/issues/58280

## Why?

The Link UI should always be anchored to the link that was clicked/activated.

## How?

Ensures that the anchor position is allowed to be dynamically calculated for existing links where there is a `<a>` tag in the contenteditable element.

## Testing Instructions

- New Post
- Type a line of text 
- Link several individual pieces of text along the line
- Click on each link in turn checking that the popover is anchored to the link in question
- Try starting and ending on different links when clicking to stress test

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/444434/776813ca-632d-4d60-8eb6-9e04b5591058

### CODE REVIEW

File: packages/format-library/src/link/inline.js [hunk 1]
```diff
@@ -212,7 +212,17 @@ function InlineLinkUI( {
...
+	// If the link is not active (i.e. it is a new link) then we need to
+	// override the getBoundingClientRect method on the anchor element
+	// to return the cached value of the selection represented by the text
+	// that the user selected to be linked.
+	// If the link is active (i.e. it is an existing link) then we allow
+	// the default behaviour of the popover anchor to be used. This will get
+	// the anchor based on the `<a>` element in the rich text.
+	if ( ! isActive ) {
+		popoverAnchor.getBoundingClientRect = () => cachedRect;
+	}
```
Comment (getdave) [inline packages/format-library/src/link/inline.js:225]: If `isActive` is true then there is an existing link and thus we should allow `popoverAnchor ` (derived from `useAnchor`) to use the default implementation which will seek the `<a>` in the DOM and anchor to that.

Otherwise if we're creating a link then there is no `<a>` until the link is submitted. Therefore we need to cache the anchor value of the original text selection that the user selected to be linked.

Previously we just cached the selection value always, which wasn't correct.

**Review by scruffian — APPROVED** [review]
I can confirm that this fixes the problem. Thanks for the fix.

File: packages/format-library/src/link/inline.js (hunk 1 above)
Comment (jeryj) [reply packages/format-library/src/link/inline.js:225]: This fixes it for existing links, but for new links, the popover will have the same scroll issue since its position is cached.
