### PR TITLE
Fix: Prevent empty renders in ServerSideRender component caused by changing props while already fetching markup

### LINKED ISSUE #35406: Bug in ServerSideRender where the block disappears during render.
If you change a prop (block option) during the loading stage (while the spinner is showing), the entire content of the block disappears.

## Before

https://user-images.githubusercontent.com/134939/135711766-d85154f5-c9a2-4447-aabf-70fadc8235b4.mp4

## After

https://user-images.githubusercontent.com/134939/135711774-c450a095-bacb-44ea-91b5-9f37dbf609fd.mp4

_Originally posted by @pryley in https://github.com/WordPress/gutenberg/issues/28297#issuecomment-932723947_

### PR DESCRIPTION
**Pull request by fabiankaegy**
## Description

Change the way the `ServerSideRender` components stores the markup from previous renders and keeps track of loading state to fix #35406 

## How has this been tested?

Using `wp-env` locally with the "Latest Comments" Block

## Types of changes

Bug Fix
## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 

Closing: #35406

### CODE REVIEW

File: packages/server-side-render/src/server-side-render.js [hunk 1]
```diff
@@ -162,30 +169,31 @@ export default function ServerSideRender( props ) {
...
+	const hasEmptyResponse = response === '';
+	const hasError = response?.error;
 
-	if ( response === '' ) {
+	if ( hasEmptyResponse || ! hasResponse ) {
 		return <EmptyResponsePlaceholder { ...props } />;
-	} else if ( ! response ) {
+	} else if ( hasError ) {
+		return <ErrorResponsePlaceholder response={ response } { ...props } />;
+	} else if ( isLoading ) {
```
Comment (Mamaduka) [inline packages/server-side-render/src/server-side-render.js]: Maybe we should refactor these `else if` statements into early returns?

Comment (fabiankaegy) [reply packages/server-side-render/src/server-side-render.js]: @Mamaduka made that change in c546927

**Review by ZebulanStanphill — APPROVED** [review]
Code looks good and appears to fix the issue.
