### PR TITLE
Converts paragraphs to headings with keyboard shortcuts

### LINKED ISSUE #11173: Paragraphs should be converted to headings using existing keyboard shortcuts
**Describe the bug**
Keyboard and formatting shortcuts that exist in the "classic" editor that convert paragraphs to headings should also apply to the paragraph block.

**To Reproduce**
1. Create a paragraph block
2. Press `ALT` + `SHIFT` + a number 1-6

or

1. Create a paragraph block
2. Start typing a number of hashes before the paragraph content
3. Press enter/return

**Expected behavior**
The paragraph block should be converted to a heading block with the heading level matching the number of the key pressed or the number of hashes that preface the paragraph

**Additional context**
- Gutenberg 4.1.1
- Keyboard and formatting shortcuts: https://codex.wordpress.org/Keyboard_Shortcuts

### PR DESCRIPTION
**Pull request by draganescu**
## What?

Closes #11173

## Why?

For feature parity with the classic editor in WordPress but also because they're a great set of shortcuts to have.

## How?

Not sure I am doing it right, because:

- This PR adds a new dependency to the block library package for this implementation. 
- Should the block handle this sort of shortcut or should the editor, or the editor implementation (post/site)?
- Is this repetitive way enough? Should we update how transforms work (in particular make `switchToBlockType` receive some 
attributes ...)?

## Testing Instructions

1. Create a post
2. Write a paragraph
3. Press Ctrl + Alt (Option) + [1-6]
4. Observe magic transform to heading that is the level of [1-6]

## Screenshots

https://user-images.githubusercontent.com/107534/194541040-052f0bd2-f586-4908-afa9-ebeb14407257.mp4

## To do

- [x] Fix some typos in the code
- [x] Make sure only the selected block is transformed
- [x] Add a combo+0 to go back to paragraph
- [x] Register the shortcuts for the heading block as well to switch between levels
The mechanism in the heading block would be different as it's only a "level" change. So maybe a separate PR?
- [x] Refactor the registration/handler into a hook
- [x] Make sure the shortcuts appear in the Keyboard shortcuts help modal
- [x] Figure out what to use for Windows browsers as `access+[1-6]` is for pinned items
- [x] Refactor to remove the changes to RichText

### CODE REVIEW

File: packages/block-library/src/paragraph/edit.js [hunk 1]
```diff
@@ -52,6 +58,115 @@ function hasDropCapDisabled( align ) {
 	return align === ( isRTL() ? 'left' : 'right' ) || align === 'center';
 }
 
+function ParagrapgShortcuts( { attributes, clientId } ) {
```
Comment (getdave) [inline packages/block-library/src/paragraph/edit.js]:
```suggestion
function ParagraphShortcuts( { attributes, clientId } ) {
```

File: packages/block-library/src/paragraph/edit.js [hunk 2]
```diff
@@ -86,6 +201,10 @@ function ParagraphBlock( {
 
 	return (
 		<>
+			<ParagrapgShortcuts
```
Comment (getdave) [inline packages/block-library/src/paragraph/edit.js]:
```suggestion
			<ParagraphShortcuts
```

**Review by getdave — COMMENTED** [review]
If these shortcuts are specific to the block then it seems reasonable to register them on the block itself.

I wonder:

- will this register the shortcuts repeatedly for each instance of the block?
- do you need to have a method of _de_registering the shortcuts if the block is not in use (see [this example](https://github.com/WordPress/gutenberg/blob/260bcb583652ee60c181073dec62f8163a386b74/packages/block-editor/src/components/keyboard-shortcuts/index.js#L13))?

File: packages/block-library/src/paragraph/edit.js [hunk 3]
```diff
@@ -52,6 +58,115 @@ function hasDropCapDisabled( align ) {
...
+			modifier: 'access',
+			character: '1',
+		},
+	} );
+	useShortcut( 'core/blocks/paragraph/transform-to-heading-1', ( event ) => {
+		event.preventDefault();
+		replaceBlocks(
+			clientId,
+			createBlock( 'core/heading', { level: 1, content, align } )
+		);
```
Comment (talldan) [inline packages/block-library/src/paragraph/edit.js]: At the moment if you have multiple paragraphs in a post, this will transform every paragraph, and it should only work for the selected block. 😄

File: packages/block-library/src/paragraph/edit.js [hunk 4]
```diff
@@ -52,6 +58,115 @@ function hasDropCapDisabled( align ) {
...
 }
 
+function ParagrapgShortcuts( { attributes, clientId } ) {
+	const { align, content } = attributes;
+	const { replaceBlocks } = useDispatch( blockEditorStore );
+	const { registerShortcut } = useDispatch( keyboardShortcutsStore );
+	registerShortcut( {
+		name: 'core/blocks/paragraph/transform-to-heading-1',
+		category: 'block-library',
+		description: __( 'Transform to heading.' ),
```
Comment (talldan) [inline packages/block-library/src/paragraph/edit.js]:
```suggestion
		description: __( 'Transform a paragraph to heading level 1.' ),
```
I think this should be a user facing description. Ideally it shows in the Keyboard shortcuts modal, but that's not happening for some reason. Possibly because the `category` isn't one that exists.

File: packages/block-library/src/paragraph/edit.js (hunk 1 above)
Comment (talldan) [inline packages/block-library/src/paragraph/edit.js]: It'd be good to move this component into a separate file. It could also just be a hook.

File: packages/block-library/src/paragraph/edit.js [hunk 5]
```diff
@@ -52,6 +58,115 @@ function hasDropCapDisabled( align ) {
...
+		keyCombination: {
+			modifier: 'access',
+			character: '1',
+		},
```
Comment (talldan) [inline packages/block-library/src/paragraph/edit.js]: On Windows, Ctrl+Alt+{number} keys are used to open the pinned apps in the corresponding position one the taskbar, so I don't think this is a good shortcut combination.

**Review by talldan — COMMENTED** [review]
It's a nice convenience feature. 👍 

The thing that stood out in testing is there's no easy way to reverse the action (other than undo). Maybe a modifier+`0` could be an option for transforming back to a paragraph.

Also, once you've converted to a heading it should be possible to continue using the shortcut to switch between other heading levels, so I think the same shortcuts could be added to the heading block.

Adding this code directly to the blocks is a reasonable first iteration. I think there might be other options that are worth exploring. 


<details>
<summary>
The shortcuts are really just block transforms, so perhaps it should be possible to specify a keyboard shortcut for a transform and have the shortcut display in the transform menu:
</summary>

Screen Shot 2022-10-05 at 11 57 10 am

</details>

I feel like that would be an interesting solution, but not without problems - at the moment the only transform between a paragraph and heading is for the default Heading block which is always a `<h2>` level. There's some overlap here with #32472 and #33811, which suggests showing each heading level in the quick inserter and there was a previous attempt to add the levels as variations, but seems it was abandoned. There's lots of opportunities here, but it's just a matter of finding the right solution.

**Comment by draganescu** [comment]
> * will this register the shortcuts repeatedly for each instance of the block?

Yes. This is one reason why letting the block handle this doesn't look like the best option possible. It's possible to avoid registering every time sure! But the naive implementation shows some potential bad architecture.

Also, I don't understand the example link in relation to deregistering. As an aside it's unlikely the paragraph block could be unused.

**Comment by getdave** [comment]
> Also, I don't understand the example link in relation to deregistering. As an aside it's unlikely the paragraph block could be unused.

There's a `useEffect` which returns a callback "cleanup" function which de-registers the shortcut.

Could we register the shortcut at an editor level conditionally based on whether paragraph and heading blocks are available?

File: packages/block-library/src/paragraph/edit.js (hunk 3 above)
Comment (draganescu) [reply packages/block-library/src/paragraph/edit.js]: Hahah, great.

File: packages/block-library/src/paragraph/edit.js (hunk 5 above)
Comment (draganescu) [reply packages/block-library/src/paragraph/edit.js]: That is what @ellatrix suggested. On OSX this works swell. @t-hamano you've done some windows compat fixes, do you have any suggestion as to what could work without conflicts on Wirdows?

Comment (t-hamano) [reply packages/block-library/src/paragraph/edit.js]: In Windows, I think the shortcut to open a pinned app is "Windows logo key + number" (Please see "Windows logo key keyboard shortcuts" section).
https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec

Also, this is very complicated, but when the modifier is `access`, it means `CTRL + ALT` on Mac and `SHIFT + ALT` on Windows.
https://github.com/WordPress/gutenberg/blob/b66257558a7c7d3bffd88c5c9d3e4e75a0c7e828/packages/keycodes/src/index.js#L164

I report that the current implementation works as expected on Windows 🙂

<details>
<summary>Screencast on Windows</summary>

https://user-images.githubusercontent.com/54422211/194326122-d5571f80-7867-487a-9c2a-c816f2adecde.mp4

</details>

**Comment by t-hamano** [comment]
My idea is to implement it in the `block-editor` package itself.
It would solve the problem of multiple shortcut registrations and additional dependencies.

Register shortcuts here:
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/keyboard-shortcuts/index.js

Like this:

```javascript
[ 1, 2, 3, 4, 5, 6 ].forEach( ( level ) => {
	registerShortcut( {
		name: `core/block-editor/transform-paragraph-to-heading-${ level }`,
		category: 'block',
		keyCombination: {
			modifier: 'access',
			character: level.toString(),
		},
	} );
} );
```

And catch the shortcuts here:
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-tools/index.js

Like this:

```javascript
[ 1, 2, 3, 4, 5, 6 ].forEach( ( level ) => {
	if (
		isMatch(
			`core/block-editor/transform-paragraph-to-heading-${ level }`,
			event
		)
	) {
		console.log( `transform paragraph to heading H${ level }` );
		// Do transform...
	}
} );
```

File: packages/block-library/src/paragraph/edit.js (hunk 5 above)
Comment (talldan) [reply packages/block-library/src/paragraph/edit.js]: > In Windows, I think the shortcut to open a pinned app is "Windows logo key + number" (Please see "Windows logo key keyboard shortcuts" section).

You're right, I forgot that my keyboard has alt and windows keys swapped over because I usually work on a mac 😆

File: packages/block-library/src/paragraph/edit.js [hunk 6]
```diff
@@ -172,6 +174,7 @@ function ParagraphBlock( {
 								'Empty block; start writing or type forward slash to choose a block'
 						  )
 				}
+				onKeyDown={ semanticShorcutsHandler }
```
Comment (draganescu) [inline packages/block-library/src/paragraph/edit.js]: I think this messes up other rich text shortcuts.

**Comment by draganescu** [comment]
Converted this to draft as it is currently breaking other rich text keyboard interactions.

**Comment by draganescu** [comment]
I think this should be refactored in a way in which it is the post editor's job to handle these shortcuts. I'll refactor to try and replicate in the post editor how the block editor handles block level shortcuts.

File: packages/edit-post/src/hooks/useTextLevelShortcuts.js [hunk 7]
```diff
@@ -0,0 +1,73 @@
...
+			} );
+			registerShortcut( {
+				name: `core/block-editor/transform-heading-to-paragraph`,
+				category: 'block-library',
+				description: __( 'Transform heading to paragraph.' ),
+				keyCombination: {
+					modifier: 'access',
+					character: `0`,
+				},
+			} );
```
Comment (talldan) [inline packages/edit-post/src/hooks/useTextLevelShortcuts.js]: I think it'd be ok to inline this next to where all the other `registerShortcut` calls are. It's not a lot of code and very easy to understand.

File: packages/edit-post/src/hooks/useTextLevelShortcuts.js [hunk 8]
```diff
@@ -0,0 +1,73 @@
...
+		( event, level ) => {
+			event.preventDefault();
+			const destinationBlockName =
+				level === 0 ? 'core/paragraph' : 'core/heading';
+			const {
+				getBlockName,
+				getSelectedBlockClientId,
+				getBlockAttributes,
+			} = select( blockEditorStore );
+			const currentClientId = getSelectedBlockClientId();
```
Comment (talldan) [inline packages/edit-post/src/hooks/useTextLevelShortcuts.js]: This returns `null` in case of a multiselection, so I think it'd be good to return early when `currentClientId === null`.

File: packages/edit-post/src/hooks/useTextLevelShortcuts.js [hunk 9]
```diff
@@ -0,0 +1,73 @@
+/**
```
Comment (talldan) [inline packages/edit-post/src/hooks/useTextLevelShortcuts.js]: The file name should be kebab case instead of camel case 😄 

(if you decide to keep it)

File: packages/edit-post/src/components/keyboard-shortcuts/index.js [hunk 10]
```diff
@@ -200,6 +205,35 @@ function KeyboardShortcuts() {
...
+		( event ) => handleTextLevelShortcut( event, 4 )
+	);
+	useShortcut(
+		'core/block-editor/transform-paragraph-to-heading-5',
+		( event ) => handleTextLevelShortcut( event, 5 )
+	);
+	useShortcut(
+		'core/block-editor/transform-paragraph-to-heading-6',
+		( event ) => handleTextLevelShortcut( event, 6 )
+	);
```
Comment (talldan) [inline packages/edit-post/src/components/keyboard-shortcuts/index.js]: I think this could technically put this into a loop as well without breaking the rule of hooks (because the loop is based on a constant, it will always execute the same way every time).

You could then avoid having to export `handleTextLevelShortcut` from a hook, and have it work the same way as the other `useShortcut` calls where all the logic is inline.

File: packages/edit-post/src/hooks/useTextLevelShortcuts.js [hunk 11]
```diff
@@ -0,0 +1,73 @@
...
+		},
+		( event, level ) => {
+			event.preventDefault();
+			const destinationBlockName =
+				level === 0 ? 'core/paragraph' : 'core/heading';
+			const {
+				getBlockName,
+				getSelectedBlockClientId,
+				getBlockAttributes,
+			} = select( blockEditorStore );
```
Comment (talldan) [inline packages/edit-post/src/hooks/useTextLevelShortcuts.js]: Interesting that you use `select` here instead of `useSelect`.

File: packages/edit-post/src/hooks/useTextLevelShortcuts.js [hunk 12]
```diff
@@ -0,0 +1,73 @@
...
+			const currentClientId = getSelectedBlockClientId();
+			if (
+				getBlockName( currentClientId ) !== 'core/paragraph' &&
+				getBlockName( currentClientId ) !== 'core/heading'
```
Comment (talldan) [inline packages/edit-post/src/hooks/useTextLevelShortcuts.js]: You could assign `getBlockName( currentClientId )` to a variable here to avoid the repeated call.

File: packages/edit-post/src/components/keyboard-shortcut-help-modal/config.js [hunk 13]
```diff
@@ -36,4 +36,14 @@ export const textFormattingShortcuts = [
 		keyCombination: { modifier: 'access', character: 'x' },
 		description: __( 'Make the selected text inline code.' ),
 	},
+	{
+		keyCombination: { modifier: 'access', character: 'Level' },
```
Comment (talldan) [inline packages/edit-post/src/components/keyboard-shortcut-help-modal/config.js]: I wonder if instead of `'Level'` it could be `'1-6'`

File: packages/edit-post/src/components/keyboard-shortcut-help-modal/config.js [hunk 14]
```diff
@@ -36,4 +36,14 @@ export const textFormattingShortcuts = [
...
+		description: __(
+			'Convert the current paragraph to a heading of level 1-6.'
```
Comment (talldan) [inline packages/edit-post/src/components/keyboard-shortcut-help-modal/config.js]: It also converts headings so it could say 'paragraph or heading'

File: packages/edit-post/src/components/keyboard-shortcut-help-modal/config.js [hunk 15]
```diff
@@ -36,4 +36,14 @@ export const textFormattingShortcuts = [
...
+		),
+	},
+	{
+		keyCombination: { modifier: 'access', character: '0' },
```
Comment (talldan) [inline packages/edit-post/src/components/keyboard-shortcut-help-modal/config.js:40]: Nitpick, I think this could be put above the other shortcut, so that it's in numerical order (0 and then 1-6)

**Review by talldan — COMMENTED** [review]
Works really well now. I think a few aspects of the code could be tidied up, but it's not far off being ready. Nice work!

File: packages/edit-post/src/components/keyboard-shortcut-help-modal/config.js (hunk 13 above)
Comment (draganescu) [reply packages/edit-post/src/components/keyboard-shortcut-help-modal/config.js]: For some reason it can't

File: packages/edit-post/src/hooks/useTextLevelShortcuts.js (hunk 7 above)
Comment (draganescu) [reply packages/edit-post/src/hooks/useTextLevelShortcuts.js]: I thought that file is long enough :D

File: packages/edit-post/src/components/keyboard-shortcut-help-modal/config.js (hunk 13 above)
Comment (draganescu) [reply packages/edit-post/src/components/keyboard-shortcut-help-modal/config.js]: Oh the thing again, in the function that displays shortcut, I hit that strip regexp back when added `[[` :)

File: packages/edit-post/src/components/keyboard-shortcuts/index.js (hunk 10 above)
Comment (draganescu) [reply packages/edit-post/src/components/keyboard-shortcuts/index.js]: I felt I needed permission to ~~break~~ bend the holy react rules

**Comment by draganescu** [comment]
Cool review @talldan 👏🏻  Applied all feedback, ready for a new check.

**Comment by bph** [comment]
So I tested this as fan of keyboard shortcut so yah for @draganescu to tackle. 
I use to use the ### method on paragraphs that I wanted to be come H3 so at first I was kind of, do we really need this. 
After testing it, we definitely need this. I like that is quite simple to use, it supposed to work on paragraphs, but in actually also works on heading blocks, too. 

Nice, it already listed in the Keyboard shortcuts page! Love it. :-)

File: packages/edit-post/src/components/keyboard-shortcut-help-modal/test/__snapshots__/index.js.snap [hunk 16]
```diff
@@ -821,6 +821,76 @@ exports[`KeyboardShortcutHelpModal should match snapshot when the modal is activ
...
+          <div
+            class="edit-post-keyboard-shortcut-help-modal__shortcut-description"
+          >
+            Convert the current heading to a paragraph.
+          </div>
+          <div
+            class="edit-post-keyboard-shortcut-help-modal__shortcut-term"
+          >
+            <kbd
+              aria-label="Shift + Alt + 0"
```
Comment (scruffian) [inline packages/edit-post/src/components/keyboard-shortcut-help-modal/test/__snapshots__/index.js.snap:836]: Isn't it Ctrl + Alt + 0?

File: packages/edit-post/src/components/keyboard-shortcut-help-modal/test/__snapshots__/index.js.snap [hunk 17]
```diff
@@ -821,6 +821,76 @@ exports[`KeyboardShortcutHelpModal should match snapshot when the modal is activ
...
+              class="edit-post-keyboard-shortcut-help-modal__shortcut-key-combination"
+            >
+              <kbd
+                class="edit-post-keyboard-shortcut-help-modal__shortcut-key"
+              >
+                Shift
```
Comment (scruffian) [inline packages/edit-post/src/components/keyboard-shortcut-help-modal/test/__snapshots__/index.js.snap:842]: Ctrl?

File: packages/edit-post/src/components/keyboard-shortcut-help-modal/test/__snapshots__/index.js.snap [hunk 18]
```diff
@@ -821,6 +821,76 @@ exports[`KeyboardShortcutHelpModal should match snapshot when the modal is activ
...
+          <div
+            class="edit-post-keyboard-shortcut-help-modal__shortcut-description"
+          >
+            Convert the current paragraph or heading to a heading of level 1 to 6.
+          </div>
+          <div
+            class="edit-post-keyboard-shortcut-help-modal__shortcut-term"
+          >
+            <kbd
+              aria-label="Shift + Alt + 1 6"
```
Comment (scruffian) [inline packages/edit-post/src/components/keyboard-shortcut-help-modal/test/__snapshots__/index.js.snap:871]: Ctrl?

File: packages/edit-post/src/components/keyboard-shortcut-help-modal/test/__snapshots__/index.js.snap [hunk 19]
```diff
@@ -821,6 +821,76 @@ exports[`KeyboardShortcutHelpModal should match snapshot when the modal is activ
...
+              class="edit-post-keyboard-shortcut-help-modal__shortcut-key-combination"
+            >
+              <kbd
+                class="edit-post-keyboard-shortcut-help-modal__shortcut-key"
+              >
+                Shift
```
Comment (scruffian) [inline packages/edit-post/src/components/keyboard-shortcut-help-modal/test/__snapshots__/index.js.snap:877]: Ctrl?

**Review by scruffian — APPROVED** [review]
LGTM.

✅ tested converting paragraphs to heading 1, 2, 3, 4, 5, 6
✅ tested converting headings to a paragraph

File: packages/edit-post/src/components/keyboard-shortcut-help-modal/test/__snapshots__/index.js.snap (hunk 16 above)
Comment (draganescu) [reply packages/edit-post/src/components/keyboard-shortcut-help-modal/test/__snapshots__/index.js.snap:836]: Hmm maybe that is not access?

File: packages/edit-post/src/components/keyboard-shortcut-help-modal/test/__snapshots__/index.js.snap (hunk 19 above)
Comment (draganescu) [reply packages/edit-post/src/components/keyboard-shortcut-help-modal/test/__snapshots__/index.js.snap:877]: `access: ( _isApple ) => ( _isApple() ? [ CTRL, ALT ] : [ SHIFT, ALT ] ),`

The tests run on a linux env so the snapshots match :)

**Comment by t-hamano** [comment]
@draganescu 
What do you think about adding this feature to other editors (edit-site/edit-widget)? If it seems reasonable, I'd like to work on it, including E2E testing.

**Comment by draganescu** [comment]
@t-hamano  sure thing, I think it's a cool addition from a consistency point of view. The intended goal here is to improve the writing experience via easier formatting - in the widget and site editors we expect more of a structural approach and less focus on flow, but sure, even cycling through heading sizes with a KBD shortcut is awesome.

Add me to review! 🙇🏻
