### PR TITLE
Navigator: restore focus only once per location

### LINKED ISSUE #44834: Global Styles: color picker closes unexpectedly while editing color palette
Steps to reproduce:

1. Go to site editor
2. Open global styles sidebar
3. Edit the color palette
4. When editing a single color in the palette, click in the color's HEX value input field and start typing a new value
5. The color picker closes prematurely, which also causes the wrong color to be applied

https://user-images.githubusercontent.com/1083581/194912939-04cdfa92-c685-4d9e-b1ac-f604b71dfc59.mp4

### PR DESCRIPTION
**Pull request by ciampo**
## What?

Requires changes from #44970

Fixes #44834

Fix a bug which caused `Navigator` to attempt to move focus in a screen more than once while the same screen is being re-rendered.

This focus shifting can impact the user experience, especially in cases there the user is interacting with an input, and changes to the input cause the screen to re-render.

## Why?

These changes fix an unintended behaviour of the component.

We were already trying to solve this issue with the changes from #44239, but #44834 highlights an edge case that wasn't covered yet: the input that the user is interacting with is not rendered inside of `Navigator`.

## How?

A new `hasRestoredFocus` flag has been added to `location` objects, and is used to avoid that a screen tries to move focus more than once for the same location.

## Testing Instructions

Follow instructions from https://github.com/WordPress/gutenberg/issues/44834 , the bug should be fixed

I've also added a new unit test to cover this edge case.

## Screenshots or screencast 

Before:

https://user-images.githubusercontent.com/1083581/194912939-04cdfa92-c685-4d9e-b1ac-f604b71dfc59.mp4

After:

https://user-images.githubusercontent.com/1083581/195831503-e0a7877f-f92b-4a64-b925-59914eb3d6a7.mp4

### CODE REVIEW

File: packages/components/src/navigator/test/index.tsx [hunk 1]
```diff
@@ -445,26 +433,77 @@ describe( 'Navigator', () => {
 		).toHaveFocus();
 	} );
 
-	it( 'should keep focus on the element that is being interacted with, while re-rendering', async () => {
-		const user = userEvent.setup( {
-			advanceTimers: jest.advanceTimersByTime,
+	describe( 'focus management', () => {
```
Comment (ciampo) [inline packages/components/src/navigator/test/index.tsx:436]: The changes in this file are:
 - moving tests around (into the new `describe` for focus management)
 - removing unnecessary assertions (those assertions are already made in other tests in the same file)
 - adding a new test specifically for the bug that this PR is fixing

Reviewing the PR commit-by-commit should make it easier to review them

File: packages/components/src/navigator/test/index.tsx [hunk 2]
```diff
@@ -445,26 +433,77 @@ describe( 'Navigator', () => {
...
+
+			// Navigate back to home screen, check that focus was correctly restored.
+			await user.click( getNavigationButton( 'back' ) );
+
+			// The first tabbable element receives focus.
+			expect( getNavigationButton( 'toChildScreen' ) ).toHaveFocus();
 		} );
 
-		render( <MyNavigation /> );
+		it( 'should keep on an active element inside navigator, while re-rendering', async () => {
```
Comment (aaronrobertshaw) [inline packages/components/src/navigator/test/index.tsx]:
```suggestion
		it( 'should keep focus on an active element inside navigator, while re-rendering', async () => {
```

Typo.

**Review by aaronrobertshaw — APPROVED** [review]
Nice fix @ciampo!

✅ Code changes look good
✅ Unit tests are green
✅ Can replicate original issue
✅ This PR resolves issue

There was one minor nit/typo but other than that this looks good to me. 🚢

**Review by tyxla — APPROVED** [review]
Looks great 👍

**Comment by michalczaplinski** [comment]
I just cherry-picked this PR to the wp/6.1-rc-2 branch to get it included in the next release: https://github.com/WordPress/gutenberg/commit/a68fa587057b06ae68f279bf1f78f212a33b1207
