### PR TITLE
Fix isRTL check by loading the ltr string explilcitely

### LINKED ISSUE #28221: RTL/LTR button missing from Paragraph block
## Description

The LTR button has gone missing from paragraph blocks in sites with RTL locales.

This button was added in https://github.com/WordPress/gutenberg/pull/10663
This seems to be a regression from https://github.com/WordPress/gutenberg/pull/27838

The `isRTL` check returns false, causing the LTR button not to render:
https://github.com/WordPress/gutenberg/blob/8b30eda7b12f881eb0befaed7ed44fedf0414207/packages/block-library/src/paragraph/edit.js#L33

The following can also be observed in the JavaScript console, which suggests the issue is related to the locale:

```js
wp.i18n.isRTL()
// false
// isRTL checks this under the hood
wp.i18n._x( 'ltr', 'text direction' )
// "ltr"
```

Yet, the locales I've tested appear to have the correct "ltr" setting, for [`ar`](https://translate.wordpress.org/projects/wp/dev/ar/default/?filters%5Bterm%5D=ltr&filters%5Bterm_scope%5D=scope_originals&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) and [`he`](https://translate.wordpress.org/projects/wp/dev/he/default/?filters%5Bterm%5D=ltr&filters%5Bterm_scope%5D=scope_originals&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc).

## Step-by-step reproduction instructions
1. Create a site with Gutenberg 9.7 installed
1. Set the site language to an RTL language, e.g. `ar` or `he`.
1. Ensure translations are updated from the site dashboard
1. Open the post editor
1. Add a paragraph block
1. The LTR button is missing

no-ltr

There should be an LTR button like this (installed Gutenberg 9.6 on the same site):

ltr with 9 6

## Expected behaviour
LTR button should be present

## Actual behaviour
LTR button is missing

## WordPress information
- WordPress version: 5.6
- Gutenberg version: 9.7.1 (latest)
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

### LINKED ISSUE #28252: RangeControl problem is RTL
Hi, there is a problem with RangeControl in RTL it is obvious (ThumbWrapper goes reverse):

Gutenberg range control for rtl

### PR DESCRIPTION
**Pull request by youknowriad**
closes #28221 
closes #28252 

Due to potential infinite loop, translations for i18n script are not being loaded. This PR  makes sure we load the "ltr" string as an inline script.

The root issue is being tackled in https://core.trac.wordpress.org/ticket/46089

**Testing instructions**

 - Use an RTL language
 - Insert a paragraph
 - the ltr/rtl direction button should be visible.

### CODE REVIEW

File: lib/client-assets.php [hunk 1]
```diff
@@ -95,6 +95,11 @@ function gutenberg_override_script( $scripts, $handle, $src, $deps = array(), $v
 	if ( 'wp-i18n' !== $handle && 'wp-polyfill' !== $handle ) {
 		$scripts->set_translations( $handle, 'default' );
 	}
+	if ( 'wp-i18n' === $handle ) {
+		$ltr    = _x( 'ltr', 'text direction', 'default' );
```
Comment (sirreal) [inline lib/client-assets.php:99]: Are translations considered safe? This is outputting unescaped text from translations into JavaScript quite directly. 

Is there some escaping or cleaning we can do? Maybe something like this is good, since our expected strings are well known:

```suggestion
		$ltr    = 'rtl' === _x( 'ltr', 'text direction', 'default' ) ? 'rtl' : 'ltr';
```

Alternatively, this seems idiomatic via [`is_rtl()`](https://developer.wordpress.org/reference/functions/is_rtl/).

```suggestion
		$ltr    = is_rtl() ? 'rtl' : 'ltr';
```

**Review by sirreal — COMMENTED** [review]
This tests well, fixes https://github.com/WordPress/gutenberg/issues/28221 in my testing.

I've left a suggestion.

File: lib/client-assets.php (hunk 1 above)
Comment (youknowriad) [reply lib/client-assets.php:99]: I'd prefer to keep the current behavior personally because it matches the expectation that  the translators in glotpress can decide what to do here. And about the safety, I'm not sure. I noticed that core uses `load_script_textdomain` which loads the translations from a json file and just paste the JSON as is to this function.

**Review by sirreal — APPROVED** [review]
This fixes the issue in my testing.

**Comment by ockham** [comment]
Cherry-picked to both `release/9.7` and `release/9.8`.

**Comment by noisysocks** [comment]
Hey @youknowriad, do you know if this change needs to be made in `trunk` for WordPress 5.7?

**Comment by youknowriad** [comment]
@noisysocks I think it's one of :

 - landing  https://core.trac.wordpress.org/ticket/46089
 - or bring this change as is to Core.

I added the label here so we don't forget.

It's easy to test though: just run `wp.i18n._x( 'ltr', 'text direction' )` in the console while in an RTL local. It should say 'rtl'

**Comment by noisysocks** [comment]
I dug into this some more. Even if the infinite recursion bug is fixed, we can still not use `wp-i18n` translations to implement `isRTL()` because WordPress will prints a script’s translations **before** it prints the script. This means that `wp-i18n`’s translations will try to call `wp.i18n.setLocaleData()` before `wp.i18n` is defined.

Our options are to keep the fix in this PR even after https://core.trac.wordpress.org/ticket/46089 is fixed or to move `isRTL()` out of `@wordpress/i18n`.

**Comment by noisysocks** [comment]
Removing the label here as we have https://core.trac.wordpress.org/ticket/52441
