### PR TITLE
Fix: apply by slug on all origins

### LINKED ISSUE #36770: Preset colors from the default palette are serialized as inline styles
In testing the new color UI component that shows up to 3 different palettes (default, theme, custom), I've noticed that preset colors from the default palette are serialized as inline colors, instead of having their class applied, like the theme colors.

## How to reproduce

- Use a theme with `theme.json` support, for example TwentyTwentyTwo.
- Add a paragraph block with a link.
- Select a preset color from the theme palette for text, a preset color from the theme palette for background, and a preset color from the theme palette for link.

Notice that the color is serialized in the inline `style` attribute of the block instead of being serialized as a class.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Fix: https://github.com/WordPress/gutenberg/issues/36770

Currently, at the block level, when we select a color/gradient from the default palette or the theme palette, if there is a custom palette, the color is applied as an inline style instead of being applied as a class or variable as it should.

These PR makes sure independently of the color palette chosen, the editor always colors and gradients with a class or CSS variable.

## How has this been tested?
I went to the paragraph block and applied a background, text, and link color from the default palette. I verified background and text colors are applied using classes, and link color references a CSS variable.
I went to the group block and applied a gradient background from the default palette. I verified the background was applied using a class.
I went to the color block (a block with a specific color implementation) and applied a background color from the default palette. I verified the color was applied using a class.
I went to the color block and applied a background gradient from the default palette. I verified the gradient was applied using a class.

### CODE REVIEW

**Comment by oandregal** [comment]
Rebased to fix some PHP tests that were removed from this repo and ported to WordPress core.

Also pushed a fix for the inline styles that are serialized to the block to cover themes that don't enqueue styles for the editor. Without https://github.com/WordPress/gutenberg/pull/36841/commits/c00b485dfae82768425552d32391deb006f108d0 How to test: upon selecting a preset background color for the paragraph block, in addition to the classes the block should have the inline styles as well.

**Comment by oandregal** [comment]
Pushed https://github.com/WordPress/gutenberg/pull/36841/commits/acf458ca9158ab6b0d354b3142b8a1cb6274ae40 to fix the utils some blocks use (button, table, search) to serialize classes & inline styles. The inline styles we generate to cover for blocks not enqueuing their own styles were missing.

**Comment by oandregal** [comment]
Testing this and looking for more code changes run into another place we need to update https://github.com/WordPress/gutenberg/issues/36886

**Comment by jorgefilipecosta** [comment]
The test failures are also happening on master and don't seem related to this PR. So I'm merging it. https://github.com/WordPress/gutenberg/issues/36886 should be addressed in a different PR.

File: packages/block-editor/src/components/gradients/use-gradient.js [hunk 1]
```diff
@@ -67,7 +65,15 @@ export function __experimentalUseGradient( {
 } = {} ) {
 	const { clientId } = useBlockEditContext();
 
-	const gradients = useSetting( 'color.gradients' ) || EMPTY_ARRAY;
+	const { gradients: gradientsPerOrigin } = useSetting( 'color' ) || {};
```
Comment (oandregal) [inline packages/block-editor/src/components/gradients/use-gradient.js:68]: Some of the properties, such as `useSetting( 'color.custom' )` have a special handling only takes effect when accessing them directly, and doing `useSetting( 'color' )` introduces some bugs. See https://github.com/WordPress/gutenberg/issues/37094

Until that's addressed we're reverting some of these changes at https://github.com/WordPress/gutenberg/pull/36900

**Comment by oandregal** [comment]
@jorgefilipecosta I've reopened https://github.com/WordPress/gutenberg/issues/36770 as I still can reproduce it.
