### PR TITLE
Fix: Button highlight popover overflow conflict with link popover

### LINKED ISSUE #38339: Buttons: Highlight Color View and Link Control are overlapping
### Description

After a link is added to a Buttons block, the Highlight Color View popover is shown below the Link Control popover and, as such, it's impossible to use.

This issue was originally reported by @ iStag in [WordPress Trac ticket #54974](https://core.trac.wordpress.org/ticket/54974), and I was able to reproduce it.

### Step-by-step reproduction instructions

1. Create a new post
2. Add a new Buttons block
3. Add some text to the button
4. Add a link
5. Select a part of the button text
6. Select "Display more block tools" and select "Highlight"

### Screenshots, screen recording, code snippet

A screenshot is available in the original Trac ticket.
https://core.trac.wordpress.org/attachment/ticket/54974/button-highlight-bug.png

### Possible solution
As suggested by the original reporter, changing the `z-index` of one of the popovers, so that the color picker is above the link control, will solve this bug.

### Environment info

- WordPress version: 6.0-alpha-52646. Gutenberg version: 12.4.1. Active theme: Twenty Twenty-Two.
- Chrome 97.0.4692.99
- Desktop with Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by delowardev**
Fixes: #38339 

Rendering button link popover in the global slot causing z-index conflict/overlapping issue with text highlight popover; Using `block-toolbar` slot solves the overlapping issue here.

## Screenshots 
|Before|After|
|:---:|:---:|
|Screen Shot 2022-02-13 at 10 28 13 AM|Screen Shot 2022-02-13 at 10 28 00 AM|

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [x] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by ndiego** [comment]
Just tested and works as expected, thanks for the PR @delowardev! 

@Mamaduka and @ntsekouras, whenever you have a second, can I get a sanity check on this? Just want to make sure the use of `__unstableSlotName` is the direction we want to go here.

**Comment by delowardev** [comment]
(Just for the context) This bug appeared after https://github.com/WordPress/gutenberg/pull/34956. Here the block tools popover slot had changed, but the button link popover was left in the previous slot position which created z-index conflict.

File: packages/block-library/src/button/edit.js [hunk 1]
```diff
@@ -224,6 +224,7 @@ function ButtonEdit( props ) {
 					} }
 					anchorRef={ ref?.current }
 					focusOnMount={ isEditingURL ? 'firstElement' : false }
+					__unstableSlotName={ 'block-toolbar' }
```
Comment (ntsekouras) [inline packages/block-library/src/button/edit.js]: >(Just for the context) This bug appeared after https://github.com/WordPress/gutenberg/pull/34956.

Based on the shared PR, it seems to me that setting the slot name to `__unstable-block-tools-after` would be better. -cc @ellatrix 

>These popovers need to use a slot in the block tools component instead, so it's the next tabbable element after the content.

**Review by ntsekouras — COMMENTED** [review]
Thanks for the PR and the context about the issue @delowardev!

File: packages/block-library/src/button/edit.js (hunk 1 above)
Comment (delowardev) [reply packages/block-library/src/button/edit.js]: @ntsekouras Thanks for the suggestion, slot name has been updated.

**Review by ellatrix — APPROVED** [review]
Makes sense to me!
