### PR TITLE
Handle edge cases in with-constrained-tabbing.

### LINKED ISSUE #10165: Improve withConstrainedTabbing to take into account click on the content
Splitting this out from https://github.com/WordPress/gutenberg/pull/9973

While testing the Modal component, an edge case surfaced which should be taken into account by `withConstrainedTabbing`. To reproduce:
- test with Safari, Edge, or IE 11 where this edge case is more evident
- open the Help modal (on a mac, press Control-Option-H, on Windows: Shift-Alt-H)
- press Tab and verify focus stays on the Close button
- click in the middle of the content
- press Tab
- instead of staying within the modal, focus is now on the document root

Testing the modal, it was pointed out that adding a `tabIndex="-1"` to the modal wrapper could help. It does help but if still fails on Safari, Edge, and IE11. Instead of relying on browsers implementation of focus and tab starting point, a better option would trying to address this issue programmatically.

Proposed solution
- add a `tabIndex="-1"` to the `withConstrainedTabbing` wrapper instead of to the single component wrapped in `withConstrainedTabbing`
- account for the case when the `keydown` event target is the wrapper itself, which happens when clicking in the content and then pressing the Tab key
- in this case, move focus to the first tabbable element

### PR DESCRIPTION
**Pull request by afercia**
## Description
Handle edge cases to keep tabbing constrained in `withConstrainedTabbing`, for example when clicking in the content and then pressing Tab. See conversation on #9973

To test:
- use Safari or Edge / IE11 where the edge case is more evident
- edit a post and open the Help modal (on a mac, press Control-Option-H, on Windows: Shift-Alt-H)
- press Tab and verify focus stays on the Close button
- click in the middle of the content
- press Tab and verify focus is moved to the Close button

Previously, focus went to the document root.

By adding `tabIndex="-1"` to the `withConstrainedTabbing` it is possible to detect when the `event.target` is _not_ the firstTabbable or `lastTabbable`. This happens, for example when the content is clicked and then Tab is pressed again. In this edge case, focus is moved to the first tabbable.

Fixes #10165

### CODE REVIEW

File: packages/components/src/higher-order/with-constrained-tabbing/index.js [hunk 1]
```diff
@@ -33,6 +33,13 @@ const withConstrainedTabbing = createHigherOrderComponent(
 			} else if ( ! event.shiftKey && event.target === lastTabbable ) {
 				event.preventDefault();
 				firstTabbable.focus();
+			/*
+			 * When pressing Tab and none of the tabbables has focus, the keydown
+			 * event happens on the wrapper div: move focus on the first tabbable.
+			 */
+			} else if ( ! tabbables.includes( event.target ) ) {
```
Comment (aduth) [inline packages/components/src/higher-order/with-constrained-tabbing/index.js]: Would it be enough to test `event.target === this.focusContainRef.current` ? More optimized, more explicit to what we are testing.

Or are there other cases where the target of the tab press would itself not be tabbable? I guess might account for elements with tabIndex=-1 within the content? If so, should be update the comment to reflect this?

**Review by aduth — APPROVED** [review]
This component could use some tests.

File: packages/components/src/higher-order/with-constrained-tabbing/index.js (hunk 1 above)
Comment (afercia) [reply packages/components/src/higher-order/with-constrained-tabbing/index.js]: Yep it would be nicer and simpler. Unfortunately, it doesn't work on IE11 where the `event.target` seems to be the clicked children element in the content. See below, in order:
- event.target
- event.currentTarget
- this.focusContainRef.current

screenshot 94

**Comment by mcsf** [comment]
Added tests co-authored with @talldan. Should be ready to merge.

File: packages/components/src/higher-order/with-constrained-tabbing/index.js (hunk 1 above)
Comment (aduth) [reply packages/components/src/higher-order/with-constrained-tabbing/index.js]: Ah! This is fine then.
