### PR TITLE
Footnotes/RichText: fix getRichTextValues for deeply nested blocks

### LINKED ISSUE #53009: Footnotes: footnotes within nested blocks are sometimes counted twice
Following on from https://github.com/WordPress/gutenberg/pull/52682, it looks like there's still an issue with footnotes sometimes being counted multiple times. It's a bit edge-casey, but I believe a reliable way to reproduce the issue is:

1. Add a Group block to a post
2. Add a Quote block within the Group block
3. Add a footnote to the paragraph within the Quote block as well as to the Citation of the Quote block
4. Notice that the footnote item is duplicated and synced twice:

https://github.com/WordPress/gutenberg/assets/14988353/b28b03d2-d1f6-4755-bba3-6ad3a98adc31

From looking at #52682, I think this might be a result of iterating over inner blocks as well `addValuesForBlocks` being called a second time for blocks with `InnerBlocks.Content`? CC: @ellatrix, @mcsf, @ramonjd, @tellthemachines

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Fixes #53009. The problem is that when there's a quote nested in a group, when we encounter the group's `InnerBlocks.Content`, we are using the group's inner blocks instead of the quotes.

I changed things to enforce using `InnerBlock.Content` for all blocks, so inner block handling goes through a single code path.

I'd love to add some good tests to this come, either in this PR or a follow-up if we run out of time.

## How?

We should link save elements to a block so we can change the innerBlocks when looping over the save elements.

## Testing Instructions

Add a quote in a group and add a footnote to the citation. There's shouldn't be a double entry in the footnotes block.

### CODE REVIEW

**Review by andrewserong — COMMENTED** [review]
Thanks for looking into this! Unfortunately, it looks like the e2e failures are legitimate. I looked into the failing `inserts patterns by dragging and dropping from the global inserter` test and attempted to reproduce manually, and there's some odd behaviour surrounding adding and editing nested blocks, particularly with the Social Icons block and with Code editor view.

To reproduce:

* Add a Social Icons block to a post
* Attempt to add child blocks to it, note that the blocks are added very slowly
* Attempt to edit the URL for one of the social icons blocks, note that typing in the field is very slow to respond
* View the code editor view, note that the inner blocks markup for the Social Icons block is empty

Here's a video:

https://github.com/WordPress/gutenberg/assets/14988353/de8ac46c-23eb-482f-b56c-149f2d173a9a

File: packages/block-editor/src/components/rich-text/get-rich-text-values.js [hunk 1]
```diff
@@ -13,18 +13,20 @@ import {
 import InnerBlocks from '../inner-blocks';
 import { Content } from './content';
 
+const elementToInnerBlocksMap = new WeakMap();
```
Comment (andrewserong) [inline packages/block-editor/src/components/rich-text/get-rich-text-values.js]: Will this be an issue in subsequent calls? I.e. should the weak map only exist for the lifecycle of a call to `getRichTextValues`? I'm not too familiar with how `WeakMap` works, so just thought I'd mention it in case it's related to the odd behaviour with the social icons blocks 🤔

Comment (ellatrix) [reply packages/block-editor/src/components/rich-text/get-rich-text-values.js]: The problem there is just that we're `saveElement` may be null, which I didn't take into account. Should be fixed now.

File: packages/blocks/src/api/serializer.js [hunk 2]
```diff
@@ -98,12 +98,9 @@ export function getBlockProps( props = {} ) {
  */
 export function getInnerBlocksProps( props = {} ) {
 	const { innerBlocks } = innerBlocksPropsProvider;
-	const [ firstBlock ] = innerBlocks ?? [];
-	if ( ! firstBlock ) return props;
-	// If the innerBlocks passed to `getSaveElement` are not blocks but already
-	// components, return the props as is. This is the case for
-	// `getRichTextValues`.
-	if ( ! firstBlock.clientId ) return { ...props, children: innerBlocks };
```
Comment (ellatrix) [inline packages/blocks/src/api/serializer.js:106]: Note that this reverts https://github.com/WordPress/gutenberg/pull/51201/files#diff-9740c1068259d4fb58036de0b2fa8a58ba9bb83f0c4b7c85aee6c0835698accaR101-R106.

**Comment by ellatrix** [comment]
This turned out to be a simplification too, so that's good.

**Review by andrewserong — APPROVED** [review]
Nice fix @ellatrix!

> This turned out to be a simplification too, so that's good.

Agreed, I like how this means there's only a single entry point for recursing into subsequent `addValuesForBlocks` calls by consolidating around the `InnerBlocks.Content` component.

This is testing well for me:

✅ Tested a bunch of permutations of different blocks inside blocks, including Quote inside a Group, and numbering is working correctly, with no duplication.
✅ Adding and editing other container blocks (e.g. social icons) works as on trunk with no perceivable difference.
✅ Gallery blocks (whose `edit` component expects `innerBlocks` to be an array [here](https://github.com/WordPress/gutenberg/blob/4404be955e3daf2ac87b1cdd3d211f9a16868ddf/packages/block-library/src/gallery/edit.js#L370)) works as on trunk, and isn't affected by this particular usage of `innerBlocks` being a component. As far as I can tell, the change in this PR appears to be pretty safe, and any blocks' `save` functions should ideally check that `innerBlocks` is not empty before attempting to call array methods like `forEach` (AFAICT no core blocks' save functions grab `innerBlocks` in a way that would be of concern).

Quick screengrab of the numbering working nicely for Quote nested in a Group:



LGTM! ✨

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the update/second-round-6-3-rc3 branch to get it included in the next release: 9a04e31fe8
