### PR TITLE
Mobile - Fix Buttons block text input

### LINKED ISSUE #25623: Button block not accepting text entry on iOS
**Describe the bug**
I can't add text to the button block, typing text does not appear inside the block. Only affects iOS, not Android.

**To reproduce**
1. Open the Gutenberg demo app
2. Add a Button block
3. Type text and observe that the text doesn't appear in the block

**Expected behavior**
The Button block should accept text and typed text should be visible in the button block.

**Screenshots**

| Screen recording showing inability to add text to a button block |
| - |

**Smartphone (please complete the following information):**
 - Device: iPhone (bug not present on Android)
 - OS: iOS 14
 - Demo App Version https://github.com/WordPress/gutenberg/commit/777a100772bb84d76b809a8ec4553cb9046eecdf

### PR DESCRIPTION
**Pull request by geriux**
`Gutenberg Mobile PR` -> https://github.com/wordpress-mobile/gutenberg-mobile/pull/2665

Fixes https://github.com/WordPress/gutenberg/issues/25623

## Description
This PR fixes and regression introduced by [this PR](https://github.com/WordPress/gutenberg/pull/23034) where some props were missing in the `RichText` component for the `Buttons` block causing it impossible to type any text in it.

## How has this been tested?
- Open the app with metro running
- Add a Buttons block
- **Expect** to be able to type in texts inside the buttons

## Screenshots 
Before | After
-|-
<kbd></kbd> | <kbd></kbd> 

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by guarani** [comment]
Thanks for the fix, @geriux! It's working well, although I noticed a difference between Gutenberg on the the current App Store 15.7 version and this.

If you add two Buttons, one after the other — should the first button which loses focus should shown a placeholder of "Add text..." when the second button is added. Do you think this could be related to the same breakage?

| This branch | WPiOS 15.7 |
| - | - |
|  |  |

**Comment by geriux** [comment]
> Thanks for the fix, @geriux! It's working well, although I noticed a difference between Gutenberg on the the current App Store 15.7 version and this.
> 
> On WPiOS 15.7, when you add two Buttons, one after the other — the first button which loses focus shows a placeholder of "Add text..." when the second button is added. On this branch I don't see the placeholder. Do you think this could be related to the same breakage?

Nice catch @guarani! I've missed some props 😅 I've just updated the PR. Thanks!

**Review by guarani — APPROVED** [review]
Thanks @geriux! Tested on iOS and it's working great.

**Comment by geriux** [comment]
> Thanks @geriux! Tested on iOS and it's working great.

Thanks for testing! Unfortunately with the latest changes it breaks the web editor, looks like passing the `id` prop breaks it. @lukewalczak Since you worked on the Buttons block, do you have any idea why this could be happening?

File: packages/block-editor/src/components/rich-text/index.js [hunk 1]
```diff
@@ -603,6 +607,11 @@ function RichTextWrapper(
 			fontFamily={ fontFamily }
 			fontWeight={ fontWeight }
 			fontStyle={ fontStyle }
+			minWidth={ minWidth }
+			maxWidth={ maxWidth }
+			onBlur={ onBlur }
+			setRef={ setRef }
+			id={ props.id }
```
Comment (geriux) [inline packages/block-editor/src/components/rich-text/index.js:614]: Hey @ellatrix 👋 I was wondering if you would have any idea about an issue I had, I added some more missing props for native, more specifically for the `Button` component that the `Buttons` block uses. If I destructure the `id` prop it breaks the web editor. Do you know by any chance why does it break?

If I pass the prop as `props.id` it works correctly. Any help would be appreciated, thanks!

**Comment by lukewalczak** [comment]
Some time ago I had a similar issue, where `style` prop has to be [destructured](https://github.com/WordPress/gutenberg/pull/23616) separately. I was testing it in multiple different ways, comparing them by reference and at the end values and objects were always the same. Unfortunately, I have no clue what is wrong :(

File: packages/block-editor/src/components/rich-text/index.js (hunk 1 above)
Comment (lukewalczak) [inline packages/block-editor/src/components/rich-text/index.js:614]: @geriux could you please add there a comment? It can be something similar to the [one](https://github.com/WordPress/gutenberg/blob/master/packages/react-native-aztec/src/AztecView.js#L214) related to `styles`

**Review by lukewalczak — APPROVED** [review]

**Comment by ceyhun** [comment]
Merging before this week's 1.38 release cut per @geriux's request.

File: packages/block-editor/src/components/rich-text/index.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-editor/src/components/rich-text/index.js:616]: Hi! That's probably because, for web, props need to be spread on the container component itself (further down in this file) rather than passed through rich text.
