### PR TITLE
Components: Add onFocusOutside replacement to Popover onClickOutside

### LINKED ISSUE #14754: "More options" dropdown menu stuck after removing block
**Describe the bug**
The "More options" menu (three dot button) in the Top Toolbar is stuck when a block is removed using the arrow keys.

Using Gutenberg 5.4.0-rc.1.

**To Reproduce**
1. Add new post
2. Select the first block (*"Start writing or type / choose a block"*)
3. Press `ALT + F10`, `Arrow Left`, `ENTER` to open the "More options" dropdown.
4. Select "Remove Block" with the arrow keys
5. Observe that the dropdown menu stays open.

To confirm the issue, add any number of blocks and try these steps on a random block.

**Expected behavior**
The dropdown menu should close after the block is removed.

(Note: the menu also stays open when performing these steps with the mouse, but can be closed by clicking anywhere on the screen. This is *only* possible using the keyboard by selecting the post title, because it does not have a more options menu.)

**Desktop (please complete the following information):**
 - OS: Windows 10 (build 1809)
 - Browser Firefox Developer Edition 
 - Version 67.0b6

### LINKED ISSUE #14849: Edit Post: More Options menu toggle buttons cause focus loss when toggled
Previously: https://github.com/WordPress/gutenberg/pull/14456#issuecomment-473403200

**Describe the bug**

When activating the toggleable menu items from the post editor's More Options menu, a focus loss occurs. Proceeding to press Tab will restore focus to the expected position (in Chrome at least); however, the focus loss should not occur.

**To reproduce**

1. Navigate to Posts > Add New
2. Click or otherwise activate the "More Options" menu in the top-right
3. Press <kbd>Spacebar</kbd> (assumes first menu item focused)
4. Note focus loss

**Expected behavior**

Focus should remain on the activated toggle button ("Top Toolbar"), indicated by the focus outline on the button.

**Desktop:**

 - OS: macOS Mojave 10.14.4
 - Browser: Chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Additional context**

As noted at https://github.com/WordPress/gutenberg/pull/14456#issuecomment-473403200, this has to do with how the menu item elements become unmounted and remounted.

### PR DESCRIPTION
**Pull request by aduth**
Fixes #14754, fixes #14849.

This pull request seeks to refactor popovers to avoid relying on "click outside" behaviors in popovers, deprecating the `Popover` component's `onClickOutside` prop in favor of a substitute `onFocusOutside`. This accounts for more reasons for focus transitions not previously reflected in `onClickOutside`, such as that described by the bug of #14754.

**Status:** While functionally complete, I'm considering this to be blocked by an apparent incompatibility with a tangentially-related bug described at #14849 . Notably, when toggling an option in the More Options menu, the menu will no longer become closed again from clicks elsewhere in the page.

**Testing instructions:**

Repeat Steps to Reproduce from #14754 , verifying that the menu is closed as expected.

Verify there are no changes in behavior from other Popover usage, particularly specialized cases such as:

- Clicking a DropdownMenu toggle button should toggle itself closed when currently opened
- Clicking a result in the link suggestions autocomplete does not dismiss the URL popover

### CODE REVIEW

**Comment by gziolo** [comment]
> Clicking a result in the link suggestions autocomplete does not dismiss the URL popover

There seems to be a different behavior when using mouse and keyboard. Well, there might be something wrong with the URL popover and autocomplete:
- when I use an arrow key, select one of the results and press `space` it doesn't get selected
- when I use an arrow key, select one of the results and press `enter` it gets selected and focus goes back to RichText field

File: packages/components/src/popover/detect-outside.js [hunk 1]
```diff
@@ -1,24 +1,21 @@
 /**
- * External dependencies
+ * WordPress dependencies
  */
-import clickOutside from 'react-click-outside';
```
Comment (gziolo) [inline packages/components/src/popover/detect-outside.js]: Unrelated question to this PR. Can we also refactor `Modal` component to stop using `react-click-outside`? :)

File: packages/components/src/popover/index.js [hunk 2]
```diff
@@ -94,6 +96,47 @@ class Popover extends Component {
 		this.toggleAutoRefresh( false );
 	}
 
+	/**
+	 * Shims an onFocusOutside callback to be compatible with a deprecated
+	 * onClickOutside prop function, if provided.
+	 *
+	 * @param {FocusEvent} event Focus event from onFocusOutside.
+	 */
+	onFocusOutside( event ) {
```
Comment (gziolo) [inline packages/components/src/popover/index.js]: How can I test this shim? By updating one of the places with usage?

**Review by gziolo — COMMENTED** [review]
I will finish this review tomorrow. It's looking great so far. I left some questions.

File: packages/components/src/popover/index.js (hunk 2 above)
Comment (aduth) [reply packages/components/src/popover/index.js]: You could locally revert one or both of 55ca76a5427876ab91e6966272e973fe295e0275 or 3e8ffc4673db9f9527173d03b5018b53d7c78a9d to restore those components' use of `onClickOutside`.

File: packages/components/src/popover/detect-outside.js (hunk 1 above)
Comment (aduth) [reply packages/components/src/popover/detect-outside.js]: > Unrelated question to this PR. Can we also refactor `Modal` component to stop using `react-click-outside`? :)

I would like to, yes.

( https://github.com/WordPress/gutenberg/pull/6261#discussion_r191758392 😞 )

Comment (gziolo) [reply packages/components/src/popover/detect-outside.js]: There is still hope then :)

Comment (gziolo) [reply packages/components/src/popover/detect-outside.js]: https://unpkg.com/react-click-outside@3.0.1/index.js

Well, it looks like `react-click-outside` is a simplified version of our own HOC :)

**Comment by aduth** [comment]
This one was a pain to rebase, in good part because of #15053 (cc @youknowriad). 

Worth noting that this will resolve some lingering errors after #11360 logged frequently in StrictMode concerning `findDOMNode` from `react-click-outside` (related: https://github.com/kentor/react-click-outside/issues/45). Also related to prior conversation https://github.com/WordPress/gutenberg/pull/14851#discussion_r273979181.

File: packages/components/src/popover/detect-outside.js [hunk 3]
```diff
@@ -1,24 +1,21 @@
...
+		this.props.onFocusOutside( event );
 	}
 
 	render() {
 		return this.props.children;
 	}
 }
 
-export default clickOutside( PopoverDetectOutside );
+export default withFocusOutside( PopoverDetectOutside );
```
Comment (youknowriad) [inline packages/components/src/popover/detect-outside.js]: This could be a nice hook const `useOnFocusOutside( ref, handler )`

**Review by noisysocks — APPROVED** [review]
I rebased this PR to fix some conflicts that existed in the `CHANGELOG.md` files. You may want to double check that the changes to `CHANGELOG.md` make sense.

I followed the testing steps in the description and everything seems okay. I also played with some `Popover` and `DropdownMenu` components and couldn't see anything off. I was not able to follow the original steps in the linked issue as that issue was fixed via a different approach.

Would love to get this in as it fixes a bug that's blocking #16582.

**Comment by aduth** [comment]
Thanks @noisysocks for the assist here. Looking again over the code and with some final testing, I think this is in good shape for merge.

However, I might like to solicit some accessibility feedback here. The changes seem like a reasonable improvement to avoid assumptions of pointer devices, but I'm curious if there are edge cases I've overlooked. Since the associated issue #14754 has been addressed in a separate pull request, I think it should be safe to spare some additional time before we commit to modifying the API.

**Comment by aduth** [comment]
Thanks @noisysocks for the assist here. Looking again over the code and with some final testing, I think this is in good shape for merge. 👍

**Comment by aduth** [comment]
Hmm, the end-to-end test failures may be legitimate.

**Comment by aduth** [comment]
The end-to-end tests seem to be getting stuck when trying to switch from "Code" editor back to "Visual" in the [container blocks test cases](https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/specs/plugins/container-blocks.test.js). I can't see any reason why it would be such a specific issue here.

My hunches are:

- Something specific with the [plugin under test](https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/plugins/inner-blocks-templates/index.js) and its template locking which is causing trouble?
- The implementation of [`withFocusOutside` using timeouts](https://github.com/WordPress/gutenberg/blob/d45c8ea9f3adafba76676a29f07f28dfd0f2d444/packages/components/src/higher-order/with-focus-outside/index.js#L81-L85) could be flawed and allow for race conditions

Separately, I stumbled upon this code, which seems like something we might want to update:

https://github.com/WordPress/gutenberg/blob/d45c8ea9f3adafba76676a29f07f28dfd0f2d444/packages/block-library/src/image/edit.js#L208

**Comment by noisysocks** [comment]
I figured out how to recreate the bug with some simple steps, but I'm no closer to figuring out what's causing it:

1. Create a new post
2. Open the _More tools & options_ menu
3. Click any menu item, e.g. enable _Spotlight mode_
4. Click outside of the menu to dismiss it. The menu does not close

**Comment by noisysocks** [comment]
Figured it out! It's because clicking on the menu item causes a focus loss. This was reported in https://github.com/WordPress/gutenberg/issues/14849. I'll include a fix here.

**Comment by noisysocks** [comment]
I pushed up 738d987 which fixes the E2E test failures and fixes #14849. 

Would you mind giving this a quick test, @gziolo?

---

**Testing instructions:**

Verify that #14849 is fixed:

1. Navigate to Posts > Add New
2. Click or otherwise activate the "More Options" menu in the top-right
3. Press <kbd>Spacebar</kbd> (assumes first menu item focused)
4. Note focus loss

Verify there are no changes in behavior from other Popover usage, particularly specialized cases such as:

- Clicking a DropdownMenu toggle button should toggle itself closed when currently opened
- Clicking a result in the link suggestions autocomplete does not dismiss the URL popover

File: packages/components/src/menu-item/index.js [hunk 4]
```diff
@@ -47,32 +46,26 @@ export function MenuItem( {
...
+			height: 20,
+			width: 20,
+		} );
 	}
 
-	return createElement(
-		tagName,
-		{
+	return (
+		<IconButton
```
Comment (gziolo) [inline packages/components/src/menu-item/index.js]: It's a bit stretched use of IconButton in the case when there is no icon 😅 

However, I can't think of another simple way of handling it where this doesn't trigger re-render of the button. I noticed that this behavior is broken only because we swap `IconButton` with `Button` for no reason when only the icon gets removed/added.

**Review by gziolo — APPROVED** [review]

**Comment by gziolo** [comment]
@afercia, would you mind running some sanity check for the `Manage All Reusable Blocks` link in the menu. I have issues confirming that it gets announced as link as expected. I outputted its HTML content and it is still an anchor with role `menuitem` as expected but I can't confirm it with VoiceOVer.

Aside: yes, I still keep it in mind that we should have no links in the dropdown menu :) I need to find a related issue where @mapk proposes we move it to the Manage Blocks modal and tackle it at last.

**Comment by gziolo** [comment]
This PR will also partially resolve https://github.com/WordPress/gutenberg/issues/15501. There is a remaining issue with focus loss when switching between Code and Visual editor when the post is empty.

**Comment by afercia** [comment]
Thanks for working on this! @gziolo I tested a bit and seems to me everything works as expected. Just one small thing: should the small horizontal "jump" of menuitems with the check icon be fixed in this PR? See animated GIF:

jump

Regarding the way screen readers announce `Manage All Reusable Blocks`: it has a `menuitem` role so it's announced as a "menu button" (or similar, depending on the browser / screen reader). ARIA roles override the native role.

However, it still creates some issues. For example: in VoiceOver, this menuitem is not listed in the "Form Controls" list while the other ones are:

Screenshot 2019-08-01 at 13 40 40

- open the More menu
- press Command Option U to open the VoiceOver "rotor"
- right / left arrows to go to the "Form Controls" panel
- down / up arrows to browse the list of form controls
- see that `Manage All Reusable Blocks` is missing

For clarity, menuitems can be links. However, an ARIA menu is supposed to be _either_ a menu of actions _or_ a navigation menu. When it's a navigation menu, it should be wrapped in a `<nav>` element, see the W3C example:

Menu or Menu bar design pattern:
https://www.w3.org/TR/wai-aria-practices-1.1/#menu

Navigation Menubar Example: 
https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html

> Since the menubar presents a site navigation system, it is wrapped in a navigation region implemented with a `nav` element that has an `aria-label` that matches the label on the menubar.

The point is that an ARIA menu _can't be_ a mix of the two things. In this case, all the menuitems perform an action in the current page except `Manage All Reusable Blocks`, which triggers navigation to another page. This is unexpected for users and there's no way to communicate it properly. See #13390

**Comment by gziolo** [comment]
> Thanks for working on this! @gziolo I tested a bit and seems to me everything works as expected. Just one small thing: should the small horizontal "jump" of menuitems with the check icon be fixed in this PR?

Good catch, it needs to be fixed, it would be a regression.

File: packages/components/src/menu-item/index.js (hunk 4 above)
Comment (noisysocks) [reply packages/components/src/menu-item/index.js]: Yep, exactly! Switching between the two components causes React to remount the component and lose focus. Looking at `IconButton`, it seemed to me that `icon={}` is an optional prop so I felt comfortable doing it this way.

**Comment by noisysocks** [comment]
Thanks for testing all!

> The point is that an ARIA menu can't be a mix of the two things. In this case, all the menuitems perform an action in the current page except Manage All Reusable Blocks, which triggers navigation to another page. This is unexpected for users and there's no way to communicate it properly. See #13390

Thanks for going into this. Let's address the issues with _Manage All Reusable Blocks_ as part of #13390. I agree we should remove the menu item altogether.

> Just one small thing: should the small horizontal "jump" of menuitems with the check icon be fixed in this PR?

This bug exists in `master`, so I'll create a separate PR to fix it. I'm keen to get this PR merged as it is blocking some other work.

File: packages/components/src/menu-item/index.js (hunk 4 above)
Comment (youknowriad) [reply packages/components/src/menu-item/index.js]: One thing we keep discussing here and there is why not just add an `icon` prop to the `Button` block and deprecate the `IconButton` (or make it just a shortcut)

File: packages/components/src/popover/detect-outside.js (hunk 1 above)
Comment (gziolo) [reply packages/components/src/popover/detect-outside.js]: I opened a follow-up to address it – #16878.

File: packages/components/src/menu-item/index.js (hunk 4 above)
Comment (gziolo) [reply packages/components/src/menu-item/index.js]: I'm sure @drw158 @cburton4 have some good ideas on how to approach it :)

I'm fine with anything which makes it less confusing. I guess having more flexible `Button` and `IconButton` as a backward-compatible alias makes a lot of sense.

Comment (drw158) [reply packages/components/src/menu-item/index.js]: We have an issue open to discuss combining IconButton and Button in #16541 

We are leaning towards keeping them separate, but I'll look at this closer to understand the disadvantage.

Comment (drw158) [reply packages/components/src/menu-item/index.js]: I'm assuming from the code that this is an issue because Button does not have an icon option. Switching between icon and non-icon buttons for Menu Items is causing technical problems.

Could this be solved by adding an icon option to the Button component, but still keep IconButton a separate component?

Comment (youknowriad) [reply packages/components/src/menu-item/index.js]: To be fair, we already do the opposite here. Not pass the "icon" prop to the IconButton (so it behaves like a Button).  If it doesn't make sense to merge the two components into one, I feel we shouldn't do anything specific about it.
