### PR TITLE
Scripts: Update webpack to v5 (try 2)

### LINKED ISSUE #30289: @wordpress/scripts 14.0.1 incorrect creation of css source maps
After updating to 14.0.1 version of @wordpress/scripts, css source maps are incorrectly generated for setup of multiple blocks in one plugin (tested on two machines, both in firefox and chrome browsers)

Source map for style-index, blocks front-end is generated only for last compiled block (I am using setup with more blocks in separate directories, all imported from common index.js in the root. Each block has its own style.css file for each block). In previous versions, source maps were generated correctly.

### LINKED ISSUE #32203: @wordpress/scripts: loading async chunks using import fails when they import styles and webpackChunkName is used (FixStyleWebpackPlugin?)
## Description
When building my project with @wordpress/scripts i encounter the following problem:
loading async chunks using import() fails when they import styles and webpackChunkName is used to give the chunk a proper name.

## Step-by-step reproduction instructions
Here i have created a minimal project to reproduce the issue: <https://github.com/tw-360vier/wp-scripts-FixStyleWebpackPlugin-chunk-load-error>

## Expected behaviour
I expect the chunk to be loaded without error.

## Actual behaviour
i encounter the following error:
```
index.js:1 Uncaught (in promise) ChunkLoadError: Loading chunk 2 failed.
(error: http://127.0.0.1:8080/style-my-chunk.js)
    at Function.u.e (http://127.0.0.1:8080/index.js:1:1662)
    at Object.<anonymous> (http://127.0.0.1:8080/index.js:1:3148)
    at u (http://127.0.0.1:8080/index.js:1:369)
    at http://127.0.0.1:8080/index.js:1:3106
    at http://127.0.0.1:8080/index.js:1:3115
u.e @ index.js:1
(anonymous) @ index.js:1
u @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
Promise.then (async)
(anonymous) @ index.js:1
u @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
```

Removing ["FixStyleWebpackPlugin"](https://github.com/WordPress/gutenberg/blob/59a3b775646f02ac610d6d74424cac36ebbd7cb5/packages/scripts/config/fix-style-webpack-plugin/index.js) from the webpack config fixes the issue, so it seems like it is related to that.

### LINKED ISSUE #33768: @wordpress/scripts vulnerable via webpack thru glob-parent
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried deactivating all plugins except Gutenberg?

- [X] I have tested with all plugins deactivated.

### Have you tried replicating the bug using a default theme e.g. Twenty Twenty?

- [X] I have tested with a default theme.

### Description

the `@wordpress/scripts` NPM package depends on a version of `webpack` which ultimately depends on a vulnerable version of `glob-parent`:

```plain
@wordpress/scripts > webpack > watchpack > watchpack-chokidar2 > chokidar > glob-parent
```

`npm audit` shows this as a "moderate" security vulnerability.

### Step-by-step reproduction instructions

1. `npm init`
2. `npm install @wordpress/scripts`
3. `npm audit`
4. read the audit report indicating vulnerabilities.

### Expected Behavior

`npm audit` gives the project a clean bill of health.

### Current Behavior

Has a security hole indicated by `npm audit`

### Screenshots or screen recording (optional)

_No response_

### Code snippet (optional)

_No response_

### WordPress Information

_No response_

### Gutenberg Information

_No response_

### What browsers are you seeing the problem on?

_No response_

### Device Information

_No response_

### Operating System Information

_No response_

### PR DESCRIPTION
**Pull request by gziolo**
## Description

Follow-up for #26382. 
Fixes #33768, fixes #32203, fixes #30289.

It's a second attempt to upgrade webpack to v5.

## Known Issues

- [x] `wp-scripts build` generates styles with a wrong name
  Screen Shot 2021-08-02 at 15 15 49
 it should be `index-style.css` in the context of a block
- [x] `npm run build` errors because of API changes in webpack plugins
  Screen Shot 2021-08-02 at 15 23 15
- [x] `npm run storybook:build` – Storybook has to be updated to work with webpack v5, more details at https://storybook.js.org/blog/storybook-for-webpack-5/

### Build for Gutenberg

- `npm run dev`
- `npm run build`

### Build for Storybook

- `npm run storybook:dev`
- `npm run storybook:build`

### Build for `@wordpress/scripts`

```bash
npx wp-create-block example --no-wp-scripts
cd example
../node_modules/.bin/wp-script build
```

## Types of changes
Breaking change for `@wordpress/scripts` users that provide their own config files for build tools.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by jsnajdr** [comment]
I fixed the `copy-webpack-plugin` issue by removing the `flatten: true` option from its config. As we are always copying from a single directory, `build-style/*.css`, not from a tree, it should not be needed.

Another issue will be solved by merging #33785 and rebasing.

**Comment by jsnajdr** [comment]
> `wp-scripts` build generates styles with a wrong name

@gziolo What's the fastest way to reproduce this?

**Comment by gziolo** [comment]
> `wp-scripts build` generates styles with a wrong name

@gziolo What's the fastest way to reproduce this?

The steps I use to create a custom block:

```bash
npx wp-create-block example --no-wp-scripts
cd example
../node_modules/.bin/wp-script build
```

**Comment by jsnajdr** [comment]
> The steps I use to create a custom block:

Thanks, now I have the `647.css` file, too 🙂

**Comment by walbo** [comment]
I looked into updating to v5 when working on #33785. I belive `@wordpress/custom-templated-path-webpack-plugin` and `@wordpress/library-export-default-webpack-plugin` that has a few issues in v5 can be removed. You now have the option to set `library` in the entry config that will fix what those packages do. If you want I can create a PR that targets this branch.

**Comment by gziolo** [comment]
> I looked into updating to v5 when working on #33785. I belive @wordpress/custom-templated-path-webpack-plugin and @wordpress/library-export-default-webpack-plugin that has a few issues in v5 can be removed. You now have the option to set library in the entry config that will fix what those packages do.

If it is possible then it would be great and we could stop maintaining those two custom plugins. They were introduced only to deal with webpack's limitations.

**Comment by walbo** [comment]
> If it is possible then it would be great and we could stop maintaining those two custom plugins. They were introduced only to deal with webpack's limitations.

Created #33826 based on this branch that removed those plugins. Runs `npm run build` without errors (as long as you rebase on trunk so #33785 is included)

**Comment by jsnajdr** [comment]
The `647.css` issue is solved. I had to provide a custom `name` function for the `splitChunks.cacheGroup` config that produced the desired name for the asset: cache group name (`style`) + original chunk name (`index`). Webpack 5 algorithm for splitting chunks and naming them is more complicated than it was in version 4.

**Comment by jsnajdr** [comment]
@walbo The changes in #33826 look good and are very helpful, so I cherry-picked the commit to this branch. That makes things simpler to administer.

File: tools/webpack/packages.js [hunk 1]
```diff
@@ -31,44 +29,47 @@ const gutenbergPackages = Object.keys( dependencies )
...
+const exportDefaultPackages = [
+	'api-fetch',
+	'deprecated',
+	'dom-ready',
+	'redux-routine',
+	'token-list',
+	'server-side-render',
+	'shortcode',
+	'warning',
+];
```
Comment (jsnajdr) [inline tools/webpack/packages.js:41]: It would be really nice if this information was part of the individual packages, like a flag in `packages/api-fetch/package.json`. The list shoudn't be maintained in a build script.

It's certainly a task for another PR, it just caught my attention here and I wanted to make a note.

Comment (gziolo) [reply tools/webpack/packages.js:41]: I agree that it's a bit unfortunate that we have to list all of them. The benefit would be that we wouldn't have to maintain the same list in WordPress core. Still, it's a manual task that we will have to remember about.

**Comment by gziolo** [comment]
All unit tests should be fixed with https://github.com/WordPress/gutenberg/pull/33818/commits/abbc15ff58a21e0e4d41fcdb8f4841ea541eeef5. I marked `@wordpress/library-export-default-webpack-plugin` as deprecated in the context of webpack 5 and removed unit tests that were erroring. Unless you feel we should try to fix them and keep the plugin compatible with webpack 5. As discussed, it's obsolete now so better to ignore it.

In https://github.com/WordPress/gutenberg/pull/33818/commits/b257e9e3f871274ec0bcb564d876f9c83b74a22e, I added some tweaks to the default webpack config shipped with `@wordpress/scripts`. The biggest change is that `file-loader` is no longer necessary because webpack 5 has native assets handling. I tested fonts handling, I still need to verify images, including SVG.

File: packages/readable-js-assets-webpack-plugin/test/fixtures/webpack.config.js [hunk 2]
```diff
@@ -17,9 +17,7 @@ module.exports = {
 		concatenateModules: true,
 		minimizer: [
 			new TerserPlugin( {
-				cache: true,
```
Comment (gziolo) [inline packages/readable-js-assets-webpack-plugin/test/fixtures/webpack.config.js:20]: @jsnajdr, is it correct? I had to remove both flags because they were removed in webpack 5. The output generated in the tests needs to be verified, too.

File: packages/scripts/config/webpack.config.js [hunk 3]
```diff
@@ -135,16 +104,16 @@ const config = {
...
+					},
 				},
 				default: false,
 			},
 		},
 		minimizer: [
 			new TerserPlugin( {
-				cache: true,
 				parallel: true,
-				sourceMap: ! isProduction,
```
Comment (gziolo) [inline packages/scripts/config/webpack.config.js:147]: A similar concern as earlier, both flags were removed from the plugin to use settings from webpack. It would be great to verify if we need to add more changes.

File: packages/readable-js-assets-webpack-plugin/test/fixtures/webpack.config.js [hunk 4]
```diff
@@ -17,9 +17,7 @@ module.exports = {
...
 				parallel: true,
-				sourceMap: true,
```
Comment (gziolo) [inline packages/readable-js-assets-webpack-plugin/test/fixtures/webpack.config.js:22]: @jsnajdr, is it correct? I had to remove both flags because they were removed in webpack 5. The output generated in the tests needs to be verified, too.

File: tools/webpack/shared.js [hunk 5]
```diff
@@ -19,15 +19,14 @@ const {
...
+	target: 'browserslist',
 	optimization: {
 		// Only concatenate modules in production, when not analyzing bundles.
 		concatenateModules:
 			mode === 'production' && ! process.env.WP_BUNDLE_ANALYZER,
 		minimizer: [
 			new TerserPlugin( {
-				cache: true,
 				parallel: true,
-				sourceMap: mode !== 'production',
```
Comment (gziolo) [inline tools/webpack/shared.js:30]: Another place where `TerserPlugin` had changes in config enforced by the API changes.

File: packages/readable-js-assets-webpack-plugin/test/fixtures/webpack.config.js (hunk 4 above)
Comment (jsnajdr) [reply packages/readable-js-assets-webpack-plugin/test/fixtures/webpack.config.js:22]: Yes, removing both flags is correct IMO. According to the `terser-webpack-plugin` [5.0.0 release notes](https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v5.0.0), these options are now inherited from the parent webpack config.

**Comment by jsnajdr** [comment]
> I marked `@wordpress/library-export-default-webpack-plugin` as deprecated in the context of webpack 5 and removed unit tests that were erroring.

Are we going to remove the legacy plugins from the repo? We won't do any further releases of them, will we? If we did, it would be preferrable to keep the unit tests working.

**Comment by jsnajdr** [comment]
@gziolo There are also unit tests failing in the `readable-js-assets-webpack-plugin`. I'm working on fixing them.

**Comment by gziolo** [comment]
> > I marked @wordpress/library-export-default-webpack-plugin as deprecated in the context of webpack 5 and removed unit tests that were erroring.
> 
> Are we going to remove the legacy plugins from the repo? We won't do any further releases of them, will we? If we did, it would be preferrable to keep the unit tests working.

I was thinking about publishing a new version with updates in the readme and the changelog. The next step could be deprecating on npm the package and removing the source folder. However, if you know how to fix the tests then we can keep the sources.

**Comment by jsnajdr** [comment]
> However, if you know how to fix the tests then we can keep the sources.

I'll see what I can do.

**Comment by gziolo** [comment]
`npm run storybook:build` works with webpack 5. I still need to update some less important config entries that I temporarily commented out and verify everything with `npm run storybook:dev`.

File: storybook/webpack.config.js [hunk 6]
```diff
@@ -10,11 +10,11 @@ const postcssPlugins = require( '@wordpress/postcss-plugins-preset' );
 
 module.exports = ( { config } ) => {
 	config.module.rules.push(
-		{
+		/*{
```
Comment (gziolo) [inline storybook/webpack.config.js]: Details on how it should be configured in https://www.npmjs.com/package/@storybook/source-loader.

**Comment by gziolo** [comment]
Story source code view works again:

Screen Shot 2021-08-03 at 16 08 30

I tested both `npm run storybook:dev` and `npm run storybook:build`.

**Comment by walbo** [comment]
Nice work!

`engines` in package.json should be updated to `>=12.13`. Some of the updated packages require node v12.13.0. (ex [mini-css-extract-plugin v2.0.0](https://github.com/webpack-contrib/mini-css-extract-plugin/releases/tag/v2.0.0), [css-loader v6.0.0)](https://github.com/webpack-contrib/css-loader/releases/tag/v6.0.0)

**Comment by gziolo** [comment]
> `engines` in package.json should be updated to `>=12.13`. Some of the updated packages require node v12.13.0. (ex [mini-css-extract-plugin v2.0.0](https://github.com/webpack-contrib/mini-css-extract-plugin/releases/tag/v2.0.0), [css-loader v6.0.0)](https://github.com/webpack-contrib/css-loader/releases/tag/v6.0.0)

Good catch, let's align 👍🏻 Done in https://github.com/WordPress/gutenberg/pull/33818/commits/032456862578b797a1f431237f3b0cf2c0e54a88.

**Comment by jsnajdr** [comment]
> However, if you know how to fix the tests then we can keep the sources.

@gziolo The `library-export-default-webpack-plugin` is not going to work with webpack 5 without major changes. Currently, it works by appending a string suffix `["default"]` to the module source string, assuming that the module source has certain layout: that it is an expression that's indexable with the `[]` operator. But in webpack 5, the source layout is different.

Simply removing the tests is the best way to proceed, I'm now confirming that.

**Review by jsnajdr — APPROVED** [review]
Everything I tested works well and I don't see any further obstacles. Looks good to go :+1:

**Comment by gziolo** [comment]
I'm working on a test block template that we can use with `@wordpress/create-block` to compare the build output generated with webpack 4 and webpack 5. We will have to confirm that:

- [x] file names generated are the same
- [x] CSS integration works correctly
- [x] SVG integration still works
- [x] image integration still works
- [x] font integration still works

I need to finish updating [wp-block-directory-template](https://www.npmjs.com/package/wp-block-directory-template) package so we can scaffold a block and compare it as follows:

## webpack 4 (`@wordpress/scripts` v17.1.0)

```bash
npx @wordpress/create-block example --template wp-block-directory-template
cd example
# npm run build is executed as part of the scaffolding process
npm start
```

## webpack 5 (this branch)

```bash
npx wp-create-block example --no-wp-scripts --template wp-block-directory-template
cd example
../node_modules/.bin/wp-script build
../node_modules/.bin/wp-script start
```

**Comment by jsnajdr** [comment]
OK, please ping me whenever I can contribute some debugging 🙂

**Comment by gziolo** [comment]
I tested again both `npm run build` and `npm run dev` and everything works perfectly fine. I can also confirm that updates to CSS and JS source files in the watch mode trigger updates to all build folders as before.

**Comment by gziolo** [comment]
I discovered an issue in webpack v5 with how it handles `wp-script start` in comparison with webpack v4.

webpack 4:
Screen Shot 2021-08-04 at 14 29 27

webpack 5 - additional `style-index.js` file that breaks the block:
Screen Shot 2021-08-04 at 14 29 38
 
`wp-scripts build` works the same way with webpack v4 and v5.

We had a custom plugin that was removing `style-index.js` in webpack v4, so we need to investigate how it can be handled natively in v5 since it isn't an issue for `wp-scripts build`.

**Comment by gziolo** [comment]
b102916 fixes the issue with obsolete `style-index.js` generated with `wp-scripts start`. The solution I used is now included in the official docs and I found it in the following comment: https://github.com/webpack/webpack/issues/7300#issuecomment-702840962. The related issue was https://github.com/webpack-contrib/mini-css-extract-plugin/issues/85 - we had it referenced in the config file.

**Comment by gziolo** [comment]
I can also confirm that SVG and images integration works as expected:
- SVG files are inlined a

Source code used for testing:

Screen Shot 2021-08-04 at 15 50 13
Screen Shot 2021-08-04 at 15 57 05

Project structure:

Screen Shot 2021-08-04 at 15 57 44

SVG file was inlined in HTML output:

Screen Shot 2021-08-04 at 16 00 40


Inserted block:

Screen Shot 2021-08-04 at 15 57 13

**Comment by Mamaduka** [comment]
It would be interesting to see how this affects plugins that use `@wordpress/scripts` but also extend default webpack config.

**Comment by gziolo** [comment]
> It would be interesting to see how this affects plugins that use @wordpress/scripts but also extend default webpack config.

I'm sure it won't be simple to upgrade for them. We made it clear in the documentation that using own webpack config is discouraged. See https://github.com/WordPress/gutenberg/tree/trunk/packages/scripts#extending-the-webpack-config:

> If you follow this approach, please, be aware that future versions of this package may change what webpack and Babel plugins we bundle, default configs, etc. Should those changes be necessary, they will be registered in the package’s CHANGELOG, so make sure to read it before upgrading.

**Comment by gziolo** [comment]
I published a new version of `@wordpress/scripts` to npm to make it possible to test the upcoming changes. It is hidden behind the `next` dist tag:

```bash
npm i --save-dev @wordpress/scripts@next
```

**Comment by gziolo** [comment]
I see an error that needs to be resolved before the final release:

```
[webpack-cli] Error: No browserslist config found to handle the 'browserslist' target.
See https://github.com/browserslist/browserslist#queries for possible ways to provide a config.
The recommended way is to add a 'browserslist' key to your package.json and list supported browsers (resp. node.js versions).
You can also more options via the 'target' option: 'browserslist' / 'browserslist:env' / 'browserslist:query' / 'browserslist:path-to-config' / 'browserslist:path-to-config:env'
```

It looks like we need to provide the fallback path to the browserlist config with `browserslist:/path/to/config` when a project doesn't provide its own config.

**Comment by gziolo** [comment]
Fix is ready: #34112.

**Comment by gziolo** [comment]
Follow-up issues reported:
- #34236
- #34239
