### PR TITLE
Fixed a bug that List block attributes were reset in 6.1.1

### LINKED ISSUE #45987: List block styles will be reset in 6.1.1.
### Description

When I edit an article written before 6.1 in 6.1.1, the list block settings disappear.

I have not tried all the settings, but "ADDITIONAL CSS CLASS", "Color" settings, etc. will be reset.
At least, the `attributes.className` data seems to disappear.

This bug occurs when updating from 6.0.3 to 6.1.1, for example, and does not occur when updating from 6.0.3 to 6.1.

Therefore, it is believed to be a bug in 6.1.1.

### Step-by-step reproduction instructions

1. Prepare an environment with a version of 6.1 or earlier and use the list. (e.g., 6.0.3)
2. Place the listing block and change the background color.
3. Save the article.
4. Update to 6.1.1 and open the edit window for that article again.
5. You will see that the background color has disappeared.

### Screenshots, screen recording, code snippet

List block in 6.0.3

ss-wp603

Updating to 6.1.1 will result in the following.

ss-wp611

### Environment info

- WordPress: 6.1.1
- Twenty Twenty-Three: 1.0
- No Plugins.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ddryo**
## What?
This is a PR that fixes #45987.

## How?
Inherited data such as className, fontSize, textColor, etc. that were not inherited in 6.1.1.

## Testing Instructions
1. Prepare an environment with a version of 6.1 or earlier and use the list. (e.g., 6.0.3)
2. Change the background color and font size of the list block.
3. Save the article.
4. Update to 6.1.1 and open the edit window for that article again.

### CODE REVIEW

File: packages/block-library/src/list/utils.js [hunk 1]
```diff
@@ -56,7 +56,8 @@ export function createListBlockFromDOMElement( listElement ) {
 }
 
 export function migrateToListV2( attributes ) {
-	const { values, start, reversed, ordered, type } = attributes;
+	const { values, start, reversed, ordered, type, ...othorAttrs } =
```
Comment (talldan) [inline packages/block-library/src/list/utils.js]: Typo here - `othorAttrs` should be `otherAttributes`.

**Comment by ddryo** [comment]
@talldan Fixed!

**Review by ellatrix — APPROVED** [review]
Fine with me
