### PR TITLE
Don't offer Classic block as a recovery action when not registered

### LINKED ISSUE #48991: Site Editor: remove Convert to Classic Block recovery option since it produces an error
### Description

In the Site Editor I loaded a template that contained a block which contained unexpected or invalid content, therefore displayed the Attempt Block Recovery button and more options menu with Resolve, Convert to HTML and Convert to Classic Block.

Choosing **Convert to Classic Block** causes Uncaught Errors in the console.

Uncaught Error: Block type 'core/freeform' is not registered.

Proposed fix: The **Convert to Classic Block** menu item should not be offered in the Site Editor as the block is no longer available.

### Step-by-step reproduction instructions

1. Edit a template to introduce a block that will fail block validation in the Site Editor
2. Open the Site Editor for this template
3. See the Attempt Block Recovery message instead of the block
4. Choose the More options menu ( ... )
5. Choose the Convert to Classic Block item
6. See the Uncaught Error message(s) in the console.

### Screenshots, screen recording, code snippet

image

### Environment info

- WordPress 6.5-beta2
- Gutenberg 15.3.1

In my scenario I was also using the the oik-blocks plugin to provide the Block info block that failed.
The block fails validation since it contains an `<svg>` tag with a `viewbox` attribute that Gutenberg wants to convert to `viewBox`.

I didn't spend much time looking for an existing bug since it's only recently that the code was implemented to disable the Classic Block in the Site Editor.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Fixes #48991.

PR fixes an error when converting a block with invalid markup to a Classic block in the site editor.

## Why?
The Classic block is no longer registered for the Site Editor (#48129), so this option should be provided.

## Testing Instructions
1. Edit a template to introduce a block that will fail block validation in the Site Editor
2. Open the Site Editor for this template
3. See the Attempt Block Recovery message instead of the block
4. Confirm "Convert to Classic Block" isn't available in the "More" options dropdown.

**Example invalid block**

```
<!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group" data-invalid="example"></div>
<!-- /wp:group -->
```

## Screenshots or screencast 

CleanShot 2023-03-14 at 10 25 00

### CODE REVIEW

**Review by kevin940726 — APPROVED** [review]
Code looks good to me 👍

**Review by carolinan — APPROVED** [review]
The PR solves the issue for me, thank you.

File: packages/block-editor/src/components/block-list/block-invalid-warning.js [hunk 1]
```diff
@@ -23,6 +23,7 @@ export function BlockInvalidWarning( {
 	block,
 } ) {
 	const hasHTMLBlock = !! getBlockType( 'core/html' );
+	const hasClassicBlock = !! getBlockType( 'core/freeform' );
```
Comment (talldan) [inline packages/block-editor/src/components/block-list/block-invalid-warning.js:26]: I think this component should really use `canInsertBlockType`.

Comment (talldan) [reply packages/block-editor/src/components/block-list/block-invalid-warning.js:26]: Just to add, I can push a PR that does this as a follow up, as this solves the immediate issue in the UI for the user.

(I accidentally started looking at the same issue in parallel, and already started writing the code, also refactoring it to hooks).

Comment (Mamaduka) [reply packages/block-editor/src/components/block-list/block-invalid-warning.js:26]: Yes, that would be ideal for both `core/html` and `core/freeform` checks. However, I only decided to reuse the method since this is targeted for WP 6.2 RC.

We should also refactor away from `withDispatch|Select` hooks in the future.

Comment (talldan) [reply packages/block-editor/src/components/block-list/block-invalid-warning.js:26]: PR here - https://github.com/WordPress/gutenberg/pull/49052
