### PR TITLE
[Gradient Tool]: Fix closing of popover when the angle control is clicked

### LINKED ISSUE #40661: Gradient Tool: Clicking the angle control closes the popover
The gradient tool comes with an input field for angle, and a separate angel control. When clicking the angle control in the flyout, the entire flyout closes, as shown here:

gradient

Steps to reproduce:

* Insert a cover block
* Add a background gradient
* Turn the angle control knob

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/40661

From the issue:
>The gradient tool comes with an input field for angle, and a separate angel control. When clicking the angle control in the flyout, the entire flyout closes, as shown here:

## How?
In [this PR](https://github.com/WordPress/gutenberg/pull/25609) there were changes that affected InputControl and how it updates/syncs values. That PR added a line of code in angle circle control to programmatically `blur` the active element.

I couldn't find the reason for making the popover close and my guess is that there is someone else listening to that event and/or a rerender somewhere is triggered. I'd love to learn why it was happening if anyone knows or debugs a bit 😄 --cc @ciampo @aaronrobertshaw 

What I did here was explicitly focus the current node(angle circle) if clicked, to contain the triggered event with the same effect.

## Testing Instructions
* Insert a cover block
* Add a background gradient
* Turn the angle control knob

#### Before
gradient

#### After

https://user-images.githubusercontent.com/16275880/165960755-7a58a8e9-5552-47d8-b77d-35519e3a8296.mov

### CODE REVIEW

**Review by stokesman — APPROVED** [review]
I tested this with Gutenberg.run and the issue is fixed. The changes make sense.

Coincidentally, were #40518 merged it would allow fixing this by removing any focus handling here but so far we're not to looking to backport that one so this is a great fix in the meantime.

File: packages/components/src/angle-picker-control/angle-circle.js [hunk 1]
```diff
@@ -28,12 +28,11 @@ function AngleCircle( { value, onChange, ...props } ) {
 
 	const changeAngleToPosition = ( event ) => {
```
Comment (stokesman) [inline packages/components/src/angle-picker-control/angle-circle.js:29]: I just noticed this is the handler for `onDragMove` and `onDragEnd` (in addition to being called by `onDragStart`) so it's executing `event.target.focus()` way more than necessary. Perhaps even the old `blur()` would work if it were only called from `onDragStart`. Not that I'm suggesting that `blur()` should be used.

**Review by andrewserong — APPROVED** [review]
Thanks for fixing this up @ntsekouras!

> I couldn't find the reason for making the popover close and my guess is that there is someone else listening to that event

I was curious so did a little bit of digging into the Popover component:

In the Popover, the dialog props are expanded to the wrapper element of the Popover [here](https://github.com/wordpress/gutenberg/blob/b99e6688fba7037ccee46cb6b7d70917a5f2c418/packages/components/src/popover/index.js#L490), and the props are retrieved from useDialog [here](https://github.com/wordpress/gutenberg/blob/b99e6688fba7037ccee46cb6b7d70917a5f2c418/packages/components/src/popover/index.js#L455). Within useDialog, the props that contain the blur handlers are retrieved via a call to useFocusOutside [here](https://github.com/wordpress/gutenberg/blob/d5915916abc45e6682f4bdb70888aa41e98aa395/packages/compose/src/hooks/use-dialog/index.js#L44), and in useFocusOutside [this is where](https://github.com/wordpress/gutenberg/blob/d5915916abc45e6682f4bdb70888aa41e98aa395/packages/compose/src/hooks/use-focus-outside/index.js#L189) `onBlur` is set.

So, that appears to be how the Popover is set up to watch for blur events within its container. There's [a bunch of other handlers](https://github.com/wordpress/gutenberg/blob/d5915916abc45e6682f4bdb70888aa41e98aa395/packages/compose/src/hooks/use-focus-outside/index.js#L184) in useFocusOutside to cancel the call to the onFocusOutside callback for `onFocus`, `onMouseDown`, `onMouseUp`, etc. The `onBlur` callback queues the check via a `setTimeout` to give the other handlers a chance to cancel / prevent the blur callback from firing, which appears to be how we get the "focus outside" behaviour.

The approach here to skip blurring the element and instead call `.focus()` to intentionally focus the desired element makes sense to me as a way to fix the underlying issue by avoiding blurring from within the Popover.

Perhaps, separately, we might need to add additional logic to the `useFocusOutside` hook to also take into account the drag event handlers (e.g. `onDragMove`, `onDragEnd`, etc) so that they're recognised as valid reasons not to call the focus outside callback.

At any rate, this change tests well, and LGTM!

File: packages/components/src/angle-picker-control/angle-circle.js (hunk 1 above)
Comment (andrewserong) [reply packages/components/src/angle-picker-control/angle-circle.js:29]: Good point! I didn't notice any performance penalty in my testing, but I suppose we could add a check before calling `.focus()` to only do that if the element isn't already focused?

**Comment by ntsekouras** [comment]
Thanks for the reviews and also for digging @andrewserong!

>Perhaps, separately, we might need to add additional logic to the useFocusOutside hook to also take into account the drag event handlers (e.g. onDragMove, onDragEnd, etc) so that they're recognised as valid reasons not to call the focus outside callback.

That sounds like a plan.

File: packages/components/src/angle-picker-control/angle-circle.js (hunk 1 above)
Comment (ntsekouras) [reply packages/components/src/angle-picker-control/angle-circle.js:29]: Definitely agree here. I noticed this as well that these events are tied together in a bit weird fashion. I'll land this as is to fix the issue for now, and we need to check how to separate/handle the drag events better.

**Comment by adamziel** [comment]
I cherry picked this change into `wp/6.0` branch to be included in WordPress 6.0 RC1: ee9bd24e22

**Comment by ciampo** [comment]
Thank you folks for collaborating on this PR! I didn't get to leave a review, but changes LGTM 🚀 

Could we just add a CHANGELOG entry for this bug fix in a follow-up ?

**Comment by ntsekouras** [comment]
>Could we just add a CHANGELOG entry for this bug fix in a follow-up ?

Sorry about that @ciampo . I often forget the changelog entry in components package, but here it is: https://github.com/WordPress/gutenberg/pull/40797
