### PR TITLE
Fix: Embed blocks: adding captions via toolbar - #64385

### LINKED ISSUE #64385: Embed blocks: adding captions via toolbar
Some blocks, like audio and image, allow toggling captions on/off via the block toolbar:

Screenshot 2024-08-09 at 09 46 46
Screenshot 2024-08-09 at 09 47 02

Meanwhile, embed blocks always have a caption visible with a placeholder nudge to "add caption" when selected:

Screenshot 2024-08-09 at 09 46 17

https://github.com/user-attachments/assets/3b539780-2947-4bae-87b9-1d210f477ae0

I'd expect all the media blocks to support captions via the toolbar only, leaving the canvas clean when switching between blocks, less content-jumping when selecting blocks, and better overall consistency.

### PR DESCRIPTION
**Pull request by hbhalodia**
## What?

- Issue - https://github.com/WordPress/gutenberg/issues/64385

## Why?

- For consistency, embed block was adding the caption option normally and was visible when we add it, instead we converted to what used in audio, image block. To add the caption via toolbar, making the backend editor consistent across blocks.

## How?

- This PR updates the embed block to use the caption via block toolbar.

## Testing Instructions

1. Open any page/post in editor.
2. Add the embed block.
3. You can see now, toolbar has option to add the caption, if you click that you would be able to add the caption making it consistent.

### Testing Instructions for Keyboard

- NIL

## Screenshots or screencast 

Screenshot 2024-08-09 at 3 53 44 PM

### CODE REVIEW

File: packages/block-library/src/embed/edit.js [hunk 1]
```diff
@@ -277,6 +278,14 @@ const EmbedEdit = ( props ) => {
 					label={ label }
 					insertBlocksAfter={ insertBlocksAfter }
 				/>
+				<Caption
```
Comment (Rishit30G) [inline packages/block-library/src/embed/edit.js:281]: Just a small suggestion 🙇 
As per the other caption text labels, the below label makes much more sense 
`label={ __( 'Embed caption text' ) }`

Comment (hbhalodia) [reply packages/block-library/src/embed/edit.js:281]: Thanks For that @Rishit30G 🚀, I missed it.

**Review by t-hamano — APPROVED** [review]
LGTM!

- The caption still works as before
- If blocks are multi-selected, the caption toolbar button is not visible
- Changing the label makes sense to me
