### PR TITLE
Fix YouTube Embed block from flickering and crashing in Safari

### LINKED ISSUE #20614: Embeds flicker in editor in Safari as of 7.6
**Describe the bug**
As of Gutenberg 7.6, the YouTube embed block will flicker in Safari in the editor. Downgrading to 7.5 seems to fix the issue. 

**To reproduce**
1. Start with a non-localhost site (for whatever reason, I could not recreate that there), and Safari on Mac OSX.
2. Embed a YouTube video block.
3. Add a YouTube video.
4. The video(s) will flicker 'on' and 'off', between visible and hidden, while previewing in the editor.

**Expected behavior**
That the video previews as usual.

**Screenshots**
Video of flickering: https://cloudup.com/cGtCQRz8i8s

The editor contains a three column block with a YouTube video in each column, and a single YouTube video below that.

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6
 - Browser: Safari
 - Version: 13.0.5

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

### PR DESCRIPTION
**Pull request by ItsJonQ**
## Description

This update fixes the issue where a YouTube video embed in Safari would flicker (and crash).

This issue is due to the inner `Sandbox` component forcefully re-rendering itself in an loop. This is why there's flickering. This is also why your computer fans may be spinning up (due to requests and stack overflow + memory leaks).

Digging deeper, it appears it has to do with the `onLoad` callback from the `iFrame` component.
The `onLoad` callback provided an `event` argument, which triggered a force rerender... resulting in a render loop.

## How has this been tested?

Tested in local Gutenberg with a YouTube video embed. Both in Chrome and in Safari.

## Types of changes

* Add an additional guard for `forceRerender` checking to ensure it does not get accidentally triggered by the `onLoad` callback.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. 

Resolves: https://github.com/WordPress/gutenberg/issues/20614

### CODE REVIEW

**Comment by ItsJonQ** [comment]
Shout out to @mcsf for debugging and collab'ing on this one!

**Review by mcsf — APPROVED** [review]
Thanks for the fix!

While I'm fine with this approach and have approved the PR, I'm wondering (nitpicking?) about the type juggling that happens due to `trySandbox` being called either with a boolean or with an event as a handler of `onLoad`.

(It's the kind of thing we would have caught with type checking, which is always a little frustrating.)

In my mind, the event should not be passed to the function in the first place, so the alternative fix would be to have `onLoad={ () => this.trySandbox() }` — or the equivalent using components methods, e.g. `onLoad={ this.onLoad }` and `this.onLoad = this.trySandbox.bind( this, false )`.

**Comment by ItsJonQ** [comment]
> In my mind, the event should not be passed to the function in the first place, so the alternative fix would be to have onLoad={ () => this.trySandbox() } — or the equivalent using components methods, e.g. onLoad={ this.onLoad } and this.onLoad = this.trySandbox.bind( this, false ).

@mcsf I agree! I'll make that update :)

File: packages/components/src/sandbox/index.js [hunk 1]
```diff
@@ -232,7 +233,7 @@ class Sandbox extends Component {
 				title={ title }
 				className="components-sandbox"
 				sandbox="allow-scripts allow-same-origin allow-presentation"
-				onLoad={ this.trySandbox }
+				onLoad={ () => this.trySandbox() }
```
Comment (mcsf) [inline packages/components/src/sandbox/index.js]: Could you test this to make sure it's not causing unnecessary re-renders down the tree? Since this component is already a class, then to avoid re-renders we might as well add:

```js
constructor() {
  …
  this.onLoad = this.trySandbox.bind( this, false );
}

…
<FocusableIframe
  onLoad={ this.onLoad }
```

Comment (ItsJonQ) [reply packages/components/src/sandbox/index.js]: @mcsf I just tested! Both solutions (the one I pushed) and the one you proposed, have the same amount of renders for both `Sandbox` and `FocusableIframe` (4 for me).

As far as implementation, I'm happy to go with either 👍 .

Just lemme know :)

Comment (mcsf) [reply packages/components/src/sandbox/index.js]: Thanks for checking — merge away :)

Comment (mcsf) [reply packages/components/src/sandbox/index.js]: Oh, actually, make it an explicit `=> this.trySandbox( false )`!

**Comment by ItsJonQ** [comment]
Thank you so much @mcsf !!

I'll merge as soon as Travis is green and happy
