### PR TITLE
Fix UnitControl select disabled state colors

### LINKED ISSUE #62969: UnitControl component keeps accent color when is disabled
### Description

UnitControl component keeps accent color when is disabled

### Step-by-step reproduction instructions

1. Add a UnitControl component to the editor and pass `disabled` prop as true.
2. Look at the rendered styles (the unit select component still renders the accent color instead of the greyed disabled one).

### Screenshots, screen recording, code snippet

[Screencast from 28-06-24 14:41:30.webm](https://github.com/WordPress/gutenberg/assets/1310626/27eaba66-3a5e-4566-b102-70c333760c0f)

### Environment info

- WordPress 6.5.4
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
Fix UnitControl select disabled state colors

## Why?
Fixes: https://github.com/WordPress/gutenberg/issues/62969

## How?
Render the accent colors when the component is not disabled.

## Testing Instructions
See https://github.com/WordPress/gutenberg/issues/62969

### Before
[Screencast from 28-06-24 14:41:30.webm](https://github.com/WordPress/gutenberg/assets/1310626/52bae4ca-4e9a-450d-816f-0b5f8f141ac6)

### After
[Screencast from 28-06-24 14:38:27.webm](https://github.com/WordPress/gutenberg/assets/1310626/0568089b-2910-4ae0-bc4f-dac28ef3b692)

### CODE REVIEW

File: packages/components/src/unit-control/styles/unit-control-styles.ts [hunk 1]
```diff
@@ -106,7 +113,7 @@ const unitSelectSizes = ( { selectSize = 'default' }: SelectProps ) => {
 			justify-content: center;
 			align-items: center;
 
-			&:hover {
+			&:not( :disabled ):hover {
 				color: ${ COLORS.ui.borderFocus };
```
Comment (mirka) [inline packages/components/src/unit-control/styles/unit-control-styles.ts]: Looks like this line is redundant? Because we already get the `color` from `baseUnitLabelStyles`.

File: packages/components/src/unit-control/styles/unit-control-styles.ts [hunk 2]
```diff
@@ -106,7 +113,7 @@ const unitSelectSizes = ( { selectSize = 'default' }: SelectProps ) => {
 			justify-content: center;
 			align-items: center;
 
-			&:hover {
+			&:not( :disabled ):hover {
```
Comment (mirka) [inline packages/components/src/unit-control/styles/unit-control-styles.ts]:
```suggestion
			&:where( :not( :disabled ) ):hover {
```

I think we need to reduce the specificity here, to prevent the hover style from overriding the focus style when the select is already focused when hovered. (By the way I confirmed that the difference between the hover and focus style is [intentional](https://github.com/WordPress/gutenberg/pull/42000#issuecomment-1168598352).)

File: packages/components/CHANGELOG.md [hunk 3]
```diff
@@ -2,6 +2,8 @@
 
 ## Unreleased
 
+- `UnitControl`: Fix colors when disabled. ([#62970](https://github.com/WordPress/gutenberg/pull/62970))
```
Comment (mirka) [inline packages/components/CHANGELOG.md]: Can we put this under a "Bug Fixes" heading please?
```suggestion
### Bug Fixes

-   `UnitControl`: Fix colors when disabled. ([#62970](https://github.com/WordPress/gutenberg/pull/62970))
```

**Review by mirka — APPROVED** [review]
Great catch, thank you!

File: packages/components/src/unit-control/styles/unit-control-styles.ts (hunk 1 above)
Comment (matiasbenedetto) [reply packages/components/src/unit-control/styles/unit-control-styles.ts]: thanks for the review. I didn't get what you mean in this comment.

Comment (mirka) [reply packages/components/src/unit-control/styles/unit-control-styles.ts]: It looks like `color: ${ COLORS.ui.borderFocus }` is unnecessary, because the correct color is already set here:

https://github.com/WordPress/gutenberg/blob/f9d406c5e98b4b4164418a4d19f6905a821c658e/packages/components/src/unit-control/styles/unit-control-styles.ts#L68-L70

It should be ok to remove, unless I'm missing something.

Comment (matiasbenedetto) [reply packages/components/src/unit-control/styles/unit-control-styles.ts]: Ohh I see. Yes, removed: [`9cd4cec` (#62970)](https://github.com/WordPress/gutenberg/pull/62970/commits/9cd4cecc7df454f18e01b33686d06c67dfff8c13)
