### PR TITLE
Writing flow: allow select all from empty selection

### LINKED ISSUE #33358: Block editor: "Select all" keyboard shortcut doesn't work anymore in WP 5.8
## Description

It looks like there is a regression in the block editor. The `cmd + A` / `ctrl + A` keyboard shortcut doesn't work anymore.

- In 5.7.2 and before, one could use this shortcut to select all the blocks available in the current post.
- In 5.8 RC 2, using this shortcut results in selecting the whole HTML content of the editor screen (see screenshot below).

## Screenshots or screen recording (optional)
0ef437364445b2d958a40f53ed158c42

## WordPress information
- WordPress version: 5.8 RC 2
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes (Twenty Twenty)

## Device information
- Device: Desktop
- Operating system: OSX
- Browser: Chrome last version

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #33358. "Select all" was made only for when a block selection already exists, but it seems unexpected to people to not be able to select all blocks from an empty selection (e.g. after clicking in the canvas to clear block selection).

This PR should enable "select all" when no blocks are selected but the canvas is focussed.

## How has this been tested?

Try this both in the normal post editor and the page template editor (iframed).

* Click on the content canvas' side (don't select any blocks).
* Press `cmd+a`.
* All blocks in the canvas should be selected.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/edit-post/src/components/visual-editor/index.js [hunk 1]
```diff
@@ -75,7 +76,7 @@ function MaybeIframe( {
 			contentRef={ contentRef }
 			style={ { width: '100%', height: '100%', display: 'block' } }
 		>
-			{ children }
+			<WritingFlow>{ children }</WritingFlow>
```
Comment (ellatrix) [inline packages/edit-post/src/components/visual-editor/index.js:79]: In the future, writing flow behaviour will be set on the iframe body element.

**Comment by Mamaduka** [comment]
I'm seeing the following warning in the editor when building on this branch:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `MaybeIframe`.
    at WritingFlow (https://gutenberg.test/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=f17c9180bd30995f41a47363057d4fd3:35120:3)
    at MaybeIframe (https://gutenberg.test/wp-content/plugins/gutenberg/build/edit-post/index.min.js?ver=e4f01b20f194bf28a576d78f2c634b77:7616:3)
    at div
    at MotionComponent (https://gutenberg.test/wp-content/plugins/gutenberg/build/edit-post/index.min.js?ver=e4f01b20f194bf28a576d78f2c634b77:15128:80)
```

File: packages/block-editor/src/components/writing-flow/index.js [hunk 2]
```diff
@@ -13,6 +13,10 @@ import useTabNav from './use-tab-nav';
 import useArrowNav from './use-arrow-nav';
 import useSelectAll from './use-select-all';
 import { store as blockEditorStore } from '../../store';
+/**
+ * External dependencies
+ */
+import classNames from 'classnames';
```
Comment (Mamaduka) [inline packages/block-editor/src/components/writing-flow/index.js]: Just nitpicking, but this should probably go to the top of the file, per coding guidlines.

**Comment by gziolo** [comment]
> Click on the content canvas' side (don't select any blocks).

It's still different from what you can observe in WP 5.7, you can click anywhere on the page and `cmd` + `a` would select all blocks.

**Comment by ellatrix** [comment]
> It's still different from what you can observe in WP 5.7, you can click anywhere on the page and cmd + a would select all blocks.

That doesn't make any sense. We shouldn't add globals shortcuts like that. What if you have multiple editors on a page? Or a different app or editor?

**Comment by Mamaduka** [comment]
> That doesn't make any sense. We shouldn't add globals shortcuts like that. What if you have multiple editors on a page? Or a different app or editor?

I agree. I think we had incorrect behavior pre 5.8, and now this feels like a regression.

Personally, I like this logic more.

**Comment by ellatrix** [comment]
I don't mind re-adding the behaviour when we catch focus within the canvas, but outside of it, it feels wrong. We even may have other components that do custom things for cmd-a. I could very well imagine a code editor in the inspector for example. Shortcuts should generally be local behaviours.

File: packages/block-editor/src/components/writing-flow/index.js (hunk 2 above)
Comment (ellatrix) [reply packages/block-editor/src/components/writing-flow/index.js]: Yeah, fixed it in https://github.com/WordPress/gutenberg/pull/33446/commits/894848db647c888340bc6607b554b5e4cf8443cd.
The code autocomplete doesn't know where to put it 😄

**Comment by gziolo** [comment]
@audrasjb reported the issue so it looks like the old behavior has some usage on the post editor page. I guess it's fine to change it to the writing canvas because of the reasons @ellatrix mentioned because we won't be able to replicate it on the widgets editor page where several instances of the block editor can be present.

File: packages/block-editor/src/components/writing-flow/use-tab-nav.js [hunk 3]
```diff
@@ -102,6 +102,7 @@ export default function useTabNav() {
 			const direction = isShift ? 'findPrevious' : 'findNext';
 
 			if ( ! hasMultiSelection() && ! getSelectedBlockClientId() ) {
+				setNavigationMode( true );
```
Comment (youknowriad) [inline packages/block-editor/src/components/writing-flow/use-tab-nav.js:106]: How is this related to this PR? What's the purpose of this change?

Comment (ellatrix) [reply packages/block-editor/src/components/writing-flow/use-tab-nav.js:106]: It is needed to make e2e tests pass. We enable navigation mode when the user tabs into the writing flow focus capture, but with tab index set to `-1` and when clearing block selection, focus will no longer move to the interface content element, but rather to the editor styles wrapper. When tabbing, it will not go through to focus capture to enable navigation mode, so we have to enable navigation mode when the user tabs in the content and there is no block selection.

Comment (youknowriad) [reply packages/block-editor/src/components/writing-flow/use-tab-nav.js:106]: I don't think I follow here, why do we need to auto-enable navigation mode implicitly (not hitting "Escape"). 

If there's no block selected and we tab into the content, can't we just select the first one?

Comment (ellatrix) [reply packages/block-editor/src/components/writing-flow/use-tab-nav.js:106]: We could, but that's not how the behaviour was. I want to preserve the current behaviour. This was discussed once with the some people from the accessibility team that if no block is selected, and you tab into the content, the editor should be in navigation mode to select a block. Supposedly it wouldn't make sense to decide for the user and pick the first one from which they then have to press Esc to pick another one. But all of this is a bit more opinionated, so for this PR I just want to make the tests pass and not change the current behaviour. :)

Comment (youknowriad) [reply packages/block-editor/src/components/writing-flow/use-tab-nav.js:106]: 👍 I didn't know this was the current behavior, that's fine by me.

**Review by youknowriad — APPROVED** [review]
LGTM 👍

**Comment by ellatrix** [comment]
Re-running some intermittent failures

**Comment by youknowriad** [comment]
@ellatrix that widget test is one of the latest intermittent failing tests with reusable blocks, we should probably skip both.

**Comment by audrasjb** [comment]
Thanks all for working on this issue 👍

**Comment by audrasjb** [comment]
Hi, while testing WP 5.8 RC4 package, I noticed it didn't fix the issue.

**Comment by audrasjb** [comment]
Ok so if you first put the focus on the editor area then it works fine. I think it’s not as good as the previous behavior, but it’s not a blocker anymore for 5.8 in my opinion.

**Comment by youknowriad** [comment]
@audrasjb The previous behavior has actually been considered wrong. See https://github.com/WordPress/gutenberg/pull/33446#issuecomment-880527700
