### PR TITLE
Extend Moment.js localization

### LINKED ISSUE #16727: Moment.js localization strings are ignored.
**Describe the bug**
`setSettings()` of `date` ignores the localization strings for `relativeTime` of moment.js. Also the two existing `relativeTime` values are incorrect.

There is an existing [trac ticket](https://core.trac.wordpress.org/ticket/47373) for it.

### PR DESCRIPTION
**Pull request by manzoorwanijk**
## Description
Fixes #16727.  The incorrect format specifiers for existing values of `relativeTime` are fixed. Also the other strings were hard-coded and thus ignored by `setSettings` when passed in `dateSettings `.
Related [Trac Ticket](https://core.trac.wordpress.org/ticket/47373).

## How has this been tested?
Yes, the changes were tested in the Console with different locales and it works perfectly.

## Types of changes
Bug 

## Checklist:
- [x] My code is tested.
- [x] My code follows the accessibility standards. 
- [x] My code follows the WordPress code style. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by ntwb** [comment]
It would be good to have the tests updated for this change please @manzoorwanijk

**Comment by manzoorwanijk** [comment]
@ntwb I tried to write a mock but it seems that the test environment doesn't set the things correctly. I tried the above code in browser console after `npm run dev`, it works perfectly. Here is the mock I tried:

```js
...
import { fromNow } from '../';
...
describe( 'Moment.js Localization', () => {
	it( 'should change the relative time strings', () => {
		const settings = __experimentalGetSettings();

		// Change the locale strings for tests.
		setSettings( {
			...settings,
			l10n: {
				...settings.l10n,
				relative: {
					...settings.l10n.relative,
					mm: '%d localized minutes',
					hh: '%d localized hours',
				}
			}
		} );
		
		// Create a Date object 5 minutes in the past.
		let date = new Date( Number( getDate() ) - ( 1000 * 60 * 5 ) );
		expect( fromNow( date ) ).toBe( '5 localized minutes ago' );
		// Test withoutSuffix
		expect( fromNow( date, true ) ).toBe( '5 localized minutes' );

		// Create a Date object 10 hours in the future.
		date = new Date( Number( getDate() ) + ( 1000 * 60 * 60 * 10 ) );
		expect( fromNow( date ) ).toBe( '10 localized hours from now' );
		// Test withoutSuffix
		expect( fromNow( date, true ) ).toBe( '10 localized hours' );

		// Test the unchanged locale strings.
		// Create a Date object 8 days in the past.
		date = new Date( Number( getDate() ) + ( 1000 * 60 * 60 * 24 * 8 ) );
		expect( fromNow( date ) ).toBe( '8 days ago' );
		// Test withoutSuffix
		expect( fromNow( date, true ) ).toBe( '8 days' );

		// Restore default settings
		setSettings( settings );
	} );
} );
```

Here is `fromNow()`:

```js
/**
 * Get the timeago or relative time according to the WordPress settings.
 *
 * @param {string}  dateValue     Date String or Date object in the Defined WP Timezone.
 * @param {boolean} withoutSuffix Whether to remove suffix e.g "ago".
 *
 * @return {string} The duration from now.
 */
export function fromNow( dateValue, withoutSuffix ) {
	const momentObject = momentLib.tz( dateValue, WP_ZONE );

	return momentObject.fromNow( withoutSuffix );
}
```

**Comment by manzoorwanijk** [comment]
The code I used in console after `npm run dev`

```js
var settings = wp.date.__experimentalGetSettings();

wp.date.setSettings( {
	...settings,
	l10n: {
		...settings.l10n,
		relative: {
			...settings.l10n.relative,
			mm: '%d localized minutes',
			hh: '%d localized hours',
		}
	}
} );

// Create a Date object 5 minutes in the past.
var date = new Date( Number( wp.date.getDate() ) - ( 1000 * 60 * 5 ) );

console.log(wp.date.fromNow(date)); // 5 localized minutes

// Create a Date object 10 hours in the future.
var date = new Date( Number( wp.date.getDate() ) + ( 1000 * 60 * 60 * 10 ) );

console.log(wp.date.fromNow(date)); // 10 localized hours from now
```

**Comment by manzoorwanijk** [comment]
Finally figured out the issue! Moment.js uses `en` as the default locale instead of `en_US`. So when using `setSettings` during tests, it updates the `en_US` data, the `localeData` of `en` remains unchanged.

I am going to push the tests now.

File: packages/date/src/index.js [hunk 1]
```diff
@@ -379,6 +380,17 @@ export function isInTheFuture( dateValue ) {
...
 }
 
+/**
+ * Get the moment object from date.
+ *
+ * @param {string} dateValue Date String or Date object in the Defined WP Timezone.
+ *
+ * @return {Moment} The Moment object.
+ */
+export function getMomemt( dateValue ) {
```
Comment (talldan) [inline packages/date/src/index.js]: There's a typo here, I'm guessing it should be `getMoment`.

Comment (talldan) [reply packages/date/src/index.js]: Also, just wanted to check one other thing. Is the intended use of this function only as a helper in the test?

Comment (manzoorwanijk) [reply packages/date/src/index.js]: > There's a typo here, I'm guessing it should be `getMoment`.

Oh yes! It should be `getMoment`, will fix that.

> Is the intended use of this function only as a helper in the test?

No, the intention is to expose moment API for other uses.

File: packages/date/src/index.js [hunk 2]
```diff
@@ -379,6 +380,17 @@ export function isInTheFuture( dateValue ) {
...
 }
 
+/**
+ * Get the moment object from date.
+ *
+ * @param {string} dateValue Date String or Date object in the Defined WP Timezone.
+ *
+ * @return {Moment} The Moment object.
+ */
+export function getMoment( dateValue ) {
```
Comment (youknowriad) [inline packages/date/src/index.js]: We had that in the past but we decided against exposing "moment" as an official API. The idea being at some point, we could get rid of moment as it's a very heavy module (and not so well maintained anymore).

Comment (manzoorwanijk) [reply packages/date/src/index.js]: > We had that in the past but we decided against exposing "moment" as an official API. The idea being at some point, we could get rid of moment as it's a very heavy module (and not so well maintained anymore).

In that case we can create specific functions for tests like this one for relative time.

```js
/**
 * Get the timeago or relative time according to the WordPress settings.
 *
 * @param {string}  dateValue     Date String or Date object in the Defined WP Timezone.
 * @param {boolean} withoutSuffix Whether to remove suffix e.g "ago".
 *
 * @return {string} The duration from now.
 */
export function fromNow( dateValue, withoutSuffix ) {
	const momentObject = momentLib.tz( dateValue, WP_ZONE );

	return momentObject.fromNow( withoutSuffix );
}
```

Comment (youknowriad) [reply packages/date/src/index.js]: Is this only for test ? Is it possible to use `__experimentalGetSettings`  to test this ?

Comment (manzoorwanijk) [reply packages/date/src/index.js]: It will be same as `isInTheFuture()` which is used for tests. Using `__experimentalGetSettings` may not server the purpose.

Comment (youknowriad) [reply packages/date/src/index.js]: `isInTheFuture` is not exposed only for tests, it's also used in other packages though.

Comment (manzoorwanijk) [reply packages/date/src/index.js]: Since the settings mapping is available via `__experimentalGetSettings`, can we rely on it for tests?

Comment (youknowriad) [reply packages/date/src/index.js]: yes, I think so.

Comment (manzoorwanijk) [reply packages/date/src/index.js]: I have removed the exposed moment API and updated the tests to use `__experimentalGetSettings`.

**Comment by manzoorwanijk** [comment]
Any update on this?

**Comment by youknowriad** [comment]
@talldan Mind giving this a second review when you have time?

**Review by talldan — COMMENTED** [review]
Sorry for the delay in reviewing @manzoorwanijk, and thanks for working on this change.

I'm struggling a bit to understand exactly what it does. Would I be right in saying that this allows these `relativeTime` i10n strings to be updated, but doesn't have any impact because there are no functions in the date package using them currently?

**Comment by manzoorwanijk** [comment]
> Would I be right in saying that this allows these `relativeTime` i10n strings to be updated...

Yes, you are right.

It just changes those strings just to make them changeable when/if the moment or an alternate API is exposed.

**Review by talldan — APPROVED** [review]
Thanks for the explanation. Lets get this merged then, it seems to do what's required.
