### PR TITLE
[Widgets Editor] Fix insertion point in widget areas

### LINKED ISSUE #25708: Widget Editor: Drop placeholder should appear below any existing blocks/widgets
Current in https://github.com/WordPress/gutenberg/pull/25681, when hovering over a block in the Inserter, the drop placeholder (blue line) appears at the top of the first widget area when nothing is selected. It appears at the top even when there are existing blocks/widgets already in that area. 

Screen Shot 2020-09-29 at 8 05 08 AM

I'd like this to mimic the behavior in the post editor. This means that the blue line should appear below any existing blocks/widgets. 

If the area has so many blocks in it that it extends below the screen, it should follow the pattern found in the post editor which is to not scroll to show the placeholder, but instead drop the block in the area and then move that area into view with the block selected.

cc @adamziel @draganescu

### LINKED ISSUE #25764: Widget screen: Adding widgets/blocks to widget area 2 adds them to widget area 1
**Describe the bug**
I noticed that when Widget area 2 (Footer 2) is open that adding a block through the inserter panel adds it automatically to widget area 1.

**To reproduce**
1. Open widget area 2 (Footer 2) (Footer widget area one is closed)
2. Open the Inserter Panel. Click to add a block/widget.
3. Notice it is not added to Footer 2, but to Footer 1.

**Expected behavior**
I expected to add widgets/blocks to the widget area that is open. As Footer widget area 1 was closed.

Widget-screen-Open-widget-area-2-adds-widgets-to-1

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin: 9.1

**Desktop (please complete the following information):**
 - Mac
 - Chrome
 - Desktop Server local site.

Bottom line is that I am only able to add widgets/blocks to Footer 1. I am not able to add widgets to any other widget area.

### PR DESCRIPTION
**Pull request by kevin940726**
## Description

Fix #25708.
Fixes https://github.com/WordPress/gutenberg/issues/25764.

Insert blocks at the bottom of the widget area via the inserter.

Also fixes a regression in #25708 where the inserter would insert blocks to the first widget area no matter which widget area is selected.

## How has this been tested?

1. Go to Widgets Editor
2. Select the second widget area
3. Insert a block via the inserter
4. The block should appear at the bottom of the second widget area, and scroll down to it.

## Screenshots 
Kapture 2020-09-30 at 13 56 38

## Types of changes

Bug fix

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by noisysocks** [comment]
Looks good! The block is inserted into the right place when I click on it in the inserter.

This isn't addressing the first part of https://github.com/WordPress/gutenberg/issues/25708, though. When I hover over the block in the inserter, I should see a blue line appear at the bottom of the widget area where the block will be inserted.

File: packages/block-editor/src/components/inserter/hooks/use-insertion-point.js [hunk 1]
```diff
@@ -81,9 +81,9 @@ function useInsertionPoint( {
 			return getBlockIndex( clientId, destinationRootClientId );
 		}
 
-		// If there a selected block, we insert after the selected block.
+		// If there's a selected block, and the selected block is not the destination root block, we insert after the selected block.
 		const end = getBlockSelectionEnd();
-		if ( ! isAppender && end ) {
+		if ( ! isAppender && end && end !== destinationRootClientId ) {
```
Comment (talldan) [inline packages/block-editor/src/components/inserter/hooks/use-insertion-point.js:86]: I'm not sure I understand the situation where `end` would be equal to `destinationRootClientId`, since `end` is usually representative of the last selected block and `destinationRootClientId` would be representative of that block's parent.

Comment (talldan) [reply packages/block-editor/src/components/inserter/hooks/use-insertion-point.js:86]: I think it possibly indicates that something has gone wrong up here if the two could ever have the same value:
https://github.com/WordPress/gutenberg/blob/a58272e2ee19358321c01dbce7263fa5e27ad6a0/packages/block-editor/src/components/inserter/hooks/use-insertion-point.js#L50-L56

Comment (kevin940726) [reply packages/block-editor/src/components/inserter/hooks/use-insertion-point.js:86]: Hmmm interesting...

The code above only happens when there's no `rootClientId` present. However, in the widgets screen, there's a `rootClientId` provided.

In the widget screen case, `rootClientId` is the last selected `widget-area` block, which is also the _selection end_ block. Since the `widget-area` block is a root block, there's no parent block for it.

I'm also hesitate that this fix could potentially break other usages in the post editor or other editor, but I couldn't find any other elegant solution. Suggestions welcome 🙇‍♂️!

**Comment by kevin940726** [comment]
> When I hover over the block in the inserter, I should see a blue line appear at the bottom of the widget area where the block will be inserted.

@noisysocks Good point, I missed it! However, there's no blue line when inserting to post editor via the inserter either though. I wonder if we should follow the current behavior in post editor? 🤔

**Comment by noisysocks** [comment]
> > When I hover over the block in the inserter, I should see a blue line appear at the bottom of the widget area where the block will be inserted.
> 
> @noisysocks Good point, I missed it! However, there's no blue line when inserting to post editor via the inserter either though. I wonder if we should follow the current behavior in post editor? 🤔

Oh, huh. That might be a bug unless it was intentionally removed and @mapk and I have missed it.

File: packages/block-editor/src/components/inserter/hooks/use-insertion-point.js (hunk 1 above)
Comment (talldan) [reply packages/block-editor/src/components/inserter/hooks/use-insertion-point.js:86]: > In the widget screen case, rootClientId is the last selected widget-area block, which is also the selection end block

I don't think that can be the case, as it'd make the next line invalid:
```js
getBlockIndex( end, destinationRootClientId );
```

The arguments are `clientId` and `rootClientId`. Since `rootClientId` represents the parent of the `clientId`, if they're the same it'd mean the block is a child of itself.

I think there must be something else happening here causing the wrong clientId and rootClientId to be set within this function. Let me see if I can find some clues.

Comment (talldan) [reply packages/block-editor/src/components/inserter/hooks/use-insertion-point.js:86]: I think it's this bit here @kevin940726:
https://github.com/WordPress/gutenberg/blob/643007e68633388280c9fc4456081fa5774cc45a/packages/edit-widgets/src/hooks/use-last-selected-root-id.js#L30

The rootClientId returned should ideally stay `null`.

Comment (talldan) [reply packages/block-editor/src/components/inserter/hooks/use-insertion-point.js:86]: This is a bit more complex than I initially thought. I think the main issue is that the `Library` component doesn't really support the use case of widget areas.

A `widget-area` is really a special kind of block where when it's selected we don't want to insert after it, we want to insert inside of it.

The `useInsertionPoint` hook instead tries to insert after any selected block.

We can pass both a `rootClientId` and a `clientId` to `Library` to circumvent inserting after, but this always inserts before the given `clientId`, and doesn't cover the use case where the widget area has no inner blocks (and therefore no `clientId` can be passed).

Some options:
- Add an `insertionIndex` prop to `Library` so that we can override `useInsertionPoint`'s derived index and support inserting within widget areas when they're selected.
- Add some kind of support for container blocks where the default is to insert within them. I'm not sure if there are any other use cases for this kind of block.

Any other ideas?

Comment (talldan) [reply packages/block-editor/src/components/inserter/hooks/use-insertion-point.js:86]: @kevin940726 I tired the `insertionIndex` idea in #25763

**Comment by talldan** [comment]
It seems like in both the post editor and widgets editor the blue line doesn't show if you're trying to insert at the end of a block list.

I think it's only implemented to show before a block that exists:
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/block-list/insertion-point.js#L110

**Comment by adamziel** [comment]
If I select a block, click on the empty space (grey area), and open the inserter after that - the insertion point resets to the end of the widget area.

Also, there is no margin between the legacy widget and the insertion point. We could fix it in a follow-up PR as it seems to be more related to the way legacy-widget block is styled, but we should keep track of it:

Zrzut ekranu 2020-10-5 o 11 49 42

**Comment by mapk** [comment]
I encouraged the same interaction as in the post editor here. If there is an area selected, or a block selected that has no blocks below it, the blue line doesn't appear. I could be convinced that it needs to show all the time.

**Comment by kevin940726** [comment]
> If I select a block, click on the empty space (grey area), and open the inserter after that - the insertion point resets to the end of the widget area.

@adamziel This seems expected to me? Since the user explicitly "un-focus" the selected block. I think it could be pretty frustrating if the user can't do that. It's just my opinion though, and I would love to be proven wrong!

> There is no margin between the legacy widget and the insertion point. We could fix it in a follow-up PR as it seems to be more related to the way legacy-widget block is styled, but we should keep track of it:

Nice catch! Open another issue?

**Comment by mapk** [comment]
@kevin940726 yes, can you open another issue for that lack of margin?

**Comment by adamziel** [comment]
> @adamziel This seems expected to me? Since the user explicitly "un-focus" the selected block. I think it could be pretty frustrating if the user can't do that. It's just my opinion though, and I would love to be proven wrong!

I checked what happens in the post editor. If you click on the top bar, it still remembers the last focused block.

**Comment by kevin940726** [comment]
> I checked what happens in the post editor. If you click on the top bar, it still remembers the last focused block.

Hmmm, interesting, could you share a gif just to be sure that I understand it correctly?

It's similar in the Widgets Editor, it will remember the last focused block if you click on the top bar. In the post editor, the inserter will append to the end when you click on an empty area in the post too. I think they are behaving similarly? Maybe I'm missing some edge cases though 🤔 .

**Comment by adamziel** [comment]
@kevin940726 oh that's right! It seems like it's a mental model thing - in the post editor, the entire page _is_ the editor and so whenever I want to remove the blue focus I feel it's "safe" to click on the blank area of top bar without really affecting the editor area (as if the top bar) was outside of the editor. I applied the same mental model to the grey area in the widgets editor, even though if you inspect it with dev tools, it is part of the editor. I somehow instinctively click there every now and then :-)

Sounds like it's something that we should consider separately (if at all). Let me CC @mapk on this note and approve this PR!

**Review by adamziel — APPROVED** [review]
