### PR TITLE
Restore correct additional CSS screen layout

### LINKED ISSUE #73128: Additional CSS: Input misplaced and not full-height
Go to site editor > global styles, and click the new ellipsis button to surface Additional CSS, and observe:

Image

A few things are off about this:

* The "learn more about CSS" link is flush against the input
* The input is not full-height
* The input is resizable

My expectation would be that the input was full height, not resizable, and that the "Learn more about CSS" was below the input field, _or_ at least had bottom margin so the spacing was balanced.

Not sure if this is a bug or a regression. The issue is reproducible inside the editor.

### PR DESCRIPTION
**Pull request by t-hamano**
- Related to #72599
- Fixes https://github.com/WordPress/gutenberg/issues/73128

## What?

This PR adds the following changes to restore the correct additional CSS screen layout:

- Remove the "Additional CSS" navigation button. This was an intentional decision made in #71550.
- Restore the correct label and description.
- Make the textarea full-height.

## Why?

In my research, this is a regression that occurred in #72599. 

## Testing Instructions

- Access the site editor > Styles
- Make sure there is no "Additional CSS" navigation button
- Access the "Additional CSS" screen from the drop-down button in the top right.
- Confirm the layout.

|Before|After|
|-|-|
| image | image |
| image | image |

### CODE REVIEW

**Comment by youknowriad** [comment]
Thanks for the fix, I appreciate it.

File: packages/global-styles-ui/src/global-styles-ui.tsx [hunk 1]
```diff
@@ -81,7 +86,10 @@ function ContextScreens( { name, parentMenu = '' }: ContextScreensProps ) {
 
 	return (
 		<>
-			<Navigator.Screen path={ parentMenu + '/colors/palette' }>
+			<Navigator.Screen
```
Comment (youknowriad) [inline packages/global-styles-ui/src/global-styles-ui.tsx]: Should this be using `GlobalStylesNavigationScreen` ?

**Review by youknowriad — APPROVED** [review]
I tested both global styles top level and within the editor, both work. Thanks :)

File: packages/global-styles-ui/src/global-styles-ui.tsx (hunk 1 above)
Comment (t-hamano) [reply packages/global-styles-ui/src/global-styles-ui.tsx]: Good catch, fixed.

File: packages/global-styles-ui/src/screen-root.tsx [hunk 2]
```diff
@@ -27,26 +26,10 @@ import RootMenu from './root-menu';
...
-			? getEntityRecord( 'root', 'globalStyles', globalStylesId )
-			: undefined;
-
-		return {
-			hasVariations:
-				!! __experimentalGetCurrentThemeGlobalStylesVariations()
-					?.length,
-			canEditCSS: !! ( globalStyles as GlobalStylesConfig )?._links?.[
-				'wp:action-edit-css'
-			],
```
Comment (Mamaduka) [inline packages/global-styles-ui/src/screen-root.tsx:48]: Were are we doing this check now?

Comment (t-hamano) [reply packages/global-styles-ui/src/screen-root.tsx:48]: In the site editor, you can access it through this button:

image


There's a check here to determine whether or not to display this button:

https://github.com/WordPress/gutenberg/blob/3e6b3d4e3610445bb38e324dc44d2917b61f2528/packages/editor/src/components/global-styles/menu.js#L66-L71

Comment (Mamaduka) [reply packages/global-styles-ui/src/screen-root.tsx:48]: Thanks for clarification, @t-hamano!

**Comment by Mamaduka** [comment]
Noticed the following warning when opening the Styles panel, not 100% sure if it's related to this PR.

## Screenshot
CleanShot 2025-12-03 at 21 07 58
