### PR TITLE
Use best fitting embed aspect ratio if exact match doesn't exist

### LINKED ISSUE #8383: Can't style embedded videos properly due to inline width & height
**Describe the bug**
There's numerous issues open that discuss the inability to style various blocks so I'm not going to repeat all that again here. The only thing I will say is that we need the ability to specify the content width, and Wide width, at the very minimum.

When you insert a YouTube or Vimeo embed Block, it adds inline width and height to the iframe:

screenshot_763

This causes the content to end up looking something like this (when you have Wide and Full videos):

gutenberg_videoembeds

Whilst its possible to override the width settings by doing something like `.wp-block-embed.is-type-video iframe {width: 100%;}`, this just makes it look even worse as we can't control the height and the vid just ends up looking squished.

There needs to be a better way to style these video embeds on the front-end.

**To Reproduce**
1. Add YouTube or Vimeo Embed
2. View inline iframe styles on front-end

**Desktop (please complete the following information):**
 - macOS 10.12.6
 - Firefox Quantum 61.0.1 (64-bit)
 - Gutenberg 3.4.0

Some related issues:
#5650
#6131

### PR DESCRIPTION
**Pull request by notnownikki**
## Description

This picks the best fit of the common aspect ratios if an exact fit does not appear in our list, for responsive content.

Fixes: https://github.com/WordPress/gutenberg/issues/8383#issuecomment-424998603

## How has this been tested?

Embed https://www.youtube.com/watch?v=XT13ijUfSts and check it has the 16-9 style.

Embed https://www.youtube.com/watch?v=uAE6Il6OTcs and check it has the 4-3 style.

Embed https://vimeo.com/139290912 and check it has the 21-9 style.

Embed https://vimeo.com/139290912 again in the same post, and check the new embed has the 21-9 style.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by jasmussen** [comment]
This is great! It works well. Twenty Seventeen front:

screen shot 2018-09-28 at 09 44 30

Backend:

screen shot 2018-09-28 at 09 44 37

However that above is after a reload. There seems to be an issue with the Vimeo video where the 2nd and 3rd time you embed it, it's not properly sized:

repeat embed

I did a little inspecting, and as it turns out, the 2nd and 3rd vimeo embed is correctly identified same as the first one. However the right classes are not applied. Compare, this is the `body` tag of the sandbox iframe for the first vimeo embed:

screen shot 2018-09-28 at 09 53 20

Now compare with the `body` tag of the same sandbox iframe for the 2nd and 3rd video embeds:

screen shot 2018-09-28 at 09 53 03

Note how the first one has all these CSS classes:

`video wp-block-embed-vimeo wp-embed-aspect-21-9 wp-has-aspect-ratio`

the 2nd and 3rd one only has this one:

`wp-block-embed-vimeo`

Note that if you save the post, then reload, evertything is fine, as you can see in the first screenshot. The missing classes happen only on the first edit. The important CSS class we need to have is `wp-has-aspect-ratio`.

Any idea why the classes go missing the first time but appear after a reload?

**Comment by notnownikki** [comment]
> Any idea why the classes go missing the first time but appear after a reload?

That's really strange because this contains a fix specifically for that. I'll take a look again.

**Comment by jasmussen** [comment]
Uhm, let me also clear cache and try again.

**Comment by notnownikki** [comment]
Ugh, ok, so this does set the classes correctly, but it doesn't make it through to the edit's render. The front end published post is fine, but the edit has problems.

**Comment by jasmussen** [comment]
Okay I'm not insane. 

It feels like we're 99% there, though ❤️

**Comment by notnownikki** [comment]
Yeah, it's just that there are a number of issues with React components and the type of data updating we do here. I'm considering a refactor to make the edit component very simple, and move most of the logic into the part where we select the data from the store. But, looking at this now.

**Comment by notnownikki** [comment]
Fix for the issue is in another PR, which currently has a conflict with master and so can't be reviewed and merged. I'll fix that PR, but there's nothing we can do in this one to fix the issue, it's to do with passing around attributes when the embed block changes type (which happens when you paste a URL) and there's a refactor in https://github.com/WordPress/gutenberg/pull/10035 to fix that.

**Comment by notnownikki** [comment]
The other PR will be fixed today and opened up for core review.

File: packages/block-library/src/embed/index.js [hunk 1]
```diff
@@ -163,39 +166,26 @@ export function getEmbedEdit( title, icon ) {
...
-					return {
-						[ aspectRatioClassName ]: allowResponsive,
-						'wp-has-aspect-ratio': allowResponsive,
-					};
+					{ ratio: '1.00', className: 'wp-embed-aspect-1-1' },
+					{ ratio: '0.56', className: 'wp-embed-aspect-9-16' },
+					{ ratio: '0.50', className: 'wp-embed-aspect-1-2' },
+				];
+				// Given the actual aspect ratio, find the widest ratio to support it.
+				for ( let idx = 0; idx < aspectRatios.length; idx++ ) {
```
Comment (tofumatt) [inline packages/block-library/src/embed/index.js]: What's the `idx` stand for?

Also, any reason not to use `for... in/of`?

File: packages/block-library/src/embed/index.js [hunk 2]
```diff
@@ -55,18 +55,21 @@ export function getEmbedEdit( title, icon ) {
...
-			this.maybeSwitchBlock();
+			if ( this.props.preview ) {
+				this.receivePreview();
+			}
 		}
 
-		componentWillUnmount() {
-			// can't abort the fetch promise, so let it know we will unmount
-			this.unmounting = true;
+		receivePreview() {
```
Comment (tofumatt) [inline packages/block-library/src/embed/index.js]: `receivePreview` seems a bit of an odd name for what it arguably *rendering* or *changing attributes of* the preview. I don't know what `this.maybeSwitchBlock` does because it's another weird *maybe* function name, but would this be better-named as `this.updatePreview`? 🤷‍♂️

That or maybe just use `this.setAttributesFromPreview()` in place of calling `this.receivePreview()` and add `this. .maybeSwitchBlock()` to the end of `setAttributesFromPreview`. Hope that makes sense!

**Review by tofumatt — APPROVED** [review]
Code seems fine, just comments about the loop used and function names, but just ping me if my comments are unclear. If they make sense feel free to modify+merge 😄 

more-red-than-green

There's talk of issues here but they're resolved in other PRs so if the UX here is better by @jasmussen I'm cool with the code.

File: packages/block-library/src/embed/index.js (hunk 1 above)
Comment (aduth) [reply packages/block-library/src/embed/index.js]: >Also, any reason not to use `for... in/of`?

Related: https://stackoverflow.com/questions/500504/why-is-using-for-in-with-array-iteration-a-bad-idea

In this case, guaranteed iteration order seems important.

**Comment by jasmussen** [comment]
It's a good step forward and since the final step is in progress separately, 👍👍

File: packages/block-library/src/embed/index.js (hunk 1 above)
Comment (tofumatt) [reply packages/block-library/src/embed/index.js]: Heh, good point 👍

File: packages/block-library/src/embed/index.js [hunk 3]
```diff
@@ -163,39 +166,26 @@ export function getEmbedEdit( title, icon ) {
 
 			if ( iframe && iframe.height && iframe.width ) {
 				const aspectRatio = ( iframe.width / iframe.height ).toFixed( 2 );
-				let aspectRatioClassName;
-
-				switch ( aspectRatio ) {
+				const aspectRatios = [
```
Comment (aduth) [inline packages/block-library/src/embed/index.js]: This seems like it fits criteria of being a constant:

https://github.com/WordPress/gutenberg/blob/master/docs/reference/coding-guidelines.md#constants

**Comment by aduth** [comment]
I'll defer to others more knowledgeable than I, but I don't necessarily agree with the premise of this pull request in assigning an aspect ratio to an element which is not in-fact of that ratio.

**Comment by jasmussen** [comment]
> I'll defer to others more knowledgeable than I, but I don't necessarily agree with the premise of this pull request in assigning an aspect ratio to an element which is not in-fact of that ratio.

If we know for sure it's a video, then it needs SOME aspect ratio, all videos have them. If the video element behaved like an img, the height would be intrinsically applied. 

We use this detected aspect ratio to apply a padding that's relatively easily calculated from the dimensions. So as an alternative to css classes we could apply this padding inline. But in the past, inline styles have caused headaches with themes, which is why we went this route.

File: packages/block-library/src/embed/index.js (hunk 2 above)
Comment (notnownikki) [reply packages/block-library/src/embed/index.js]: It's code we need to run whenever we receive a preview, and to keep things small and the functions easy to read, `setAttributesFromPreview` and `maybeSwitchBlock` are split. `handleIncomingPreview` perhaps?

`maybe` means that calling that method might do what it says, but the conditions are complex and there's no guarantee. The method is short and documented. You can find the `maybe` prefix in the parser, in the popover component, in the async-generator middleware, in the block list, and in the format toolbar. And in WordPress core PHP code.

File: packages/block-library/src/embed/index.js (hunk 1 above)
Comment (notnownikki) [reply packages/block-library/src/embed/index.js]: idx was short for index, I thought it was one of the commonly used index var names (i, and x being others) and I hope the usage is obvious from the code.  We use this in other places too, but I'll change it to `ratioIndex`

File: packages/block-library/src/embed/index.js (hunk 3 above)
Comment (notnownikki) [reply packages/block-library/src/embed/index.js]: Screaming snake case is my favourite case name. Changed :)

File: packages/block-library/src/embed/index.js (hunk 1 above)
Comment (tofumatt) [reply packages/block-library/src/embed/index.js]: The usage is pretty obvious, but I think I have a pet peeve regarding brief variable names. Sorry for the nitpicking!

File: packages/block-library/src/embed/index.js (hunk 2 above)
Comment (tofumatt) [reply packages/block-library/src/embed/index.js]: I know it's elsewhere, but it breaks my brain. I think I want to launch a campaign to improve it. As @aduth has said elsewhere (I'm paraphrasing): "Just because we do it less optimally elsewhere doesn't mean we should here." 😏

But yes, it's not isolated to this patch. I like `handleIncomingPreview`, that makes more sense to me. 🤷‍♂️

**Review by tofumatt — APPROVED** [review]
Additional changes are good to me, thanks!

File: packages/block-library/src/embed/index.js (hunk 2 above)
Comment (notnownikki) [reply packages/block-library/src/embed/index.js]: I was under the (possibly wrong) impression that it was an established pattern, as it's in both WP core and G, with some of the usage in G being added as recently as last week.

I'll change `receivePreview` to `handleIncomingPreview`, that does make it clearer :)
