### PR TITLE
Try fixing combobox a11y issues 

### LINKED ISSUE #27385: Parent page dropdown: screen reader issues
**Describe the bug**

When navigating to the parent page dropdown under "Page Attributes" in the sidebar, VoiceOver on Safari does not announce the input label, but goes straight to announcing number of options. 

Additionally, if a selection already exists, it is not announced either with VoiceOver/Safari or with NVDA/Firefox, so the user has no way of knowing if an option is currently selected. 

**To reproduce**
1. Go to any page (there must be multiple pages on the website);
2. Using VoiceOver, navigate to Page Attributes in the sidebar, then tab once to land in the parent page dropdown;
3. Verify that VoiceOver doesn't announce the component name (which is "Parent page);
4. Select an option from the dropdown;
5. Tab away from the dropdown, and then tab back into it;
6. Verify that the previously selected option is not announced.

**Expected behavior**

Expected both component label, and existing selection (if there is one), to be read out by screen reader when focusing on the input.

**Editor version (please complete the following information):**
- WordPress version: 5.6 RC1
- If the Gutenberg plugin is installed, which version is it? 9.4.1

### PR DESCRIPTION
**Pull request by tellthemachines**
## Description

Fixes #27385.

The issue with VoiceOver not announcing the input label is straightforward: changing the `aria-live` setting to `polite` fixes it. (Thanks for the suggestion, @talldan 😄 )

The selection not being announced is trickier as different screen readers announce input selection in different order. What I tried here was adding an `aria-label` with the selection value as well as the original label value (because the aria-label will override the label) and that reads out in VoiceOver in the same order as a native `select` would, but in NVDA it doesn't quite match. 

Would be good to have some a11y input into this.

## How has this been tested?

Tested with VoiceOver/Safari on macOS and NVDA/Firefox on Windows 10.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/components/src/combobox-control/index.js [hunk 1]
```diff
@@ -135,7 +135,7 @@ function ComboboxControl( {
 	const onFocus = () => {
 		setIsExpanded( true );
 		onFilterValueChange( '' );
-		setInputValue( '' );
+		// setInputValue( '' );
```
Comment (sarahricker) [inline packages/components/src/combobox-control/index.js:138]:
```suggestion

```

Comment (sarahricker) [reply packages/components/src/combobox-control/index.js:138]: Might as well just remove it instead of commenting out :) We've got git!

File: packages/components/src/combobox-control/index.js [hunk 2]
```diff
@@ -203,6 +203,11 @@ function ComboboxControl( {
 								instanceId={ instanceId }
 								ref={ inputContainer }
 								value={ isExpanded ? inputValue : currentLabel }
+								aria-label={
+									currentLabel
+										? `${ currentLabel }, ${ label }`
+										: null
```
Comment (sarahricker) [inline packages/components/src/combobox-control/index.js:209]: Is there any other default value that would be good here rather than null?

**Review by sarahricker — CHANGES_REQUESTED** [review]
Looks pretty good - but haven't tested locally yet. Left a question and a note inline.

File: packages/components/src/combobox-control/index.js (hunk 1 above)
Comment (tellthemachines) [reply packages/components/src/combobox-control/index.js:138]: Whoops, that was unintended! I don't think removing it changes anything, but it's not needed for the fix so I'll revert the change.

File: packages/components/src/combobox-control/index.js (hunk 2 above)
Comment (tellthemachines) [reply packages/components/src/combobox-control/index.js:209]: The purpose of `null` here is to not render the `aria-label` if there's no currently selected value, because in that case, its contents are identical to the already existing label, so we don't need to override it with `aria-label`.

**Review by kevin940726 — APPROVED** [review]
LGTM, I don't have any knowledge of the `aria-label` change though.

**Review by talldan — APPROVED** [review]
Looks good and works well in testing 👍

**Comment by alexstine** [comment]
I can confirm that this fix is perfect for Mac Voiceover.

NVDA doesn't seem to handle this well as it reads the description first, the current selected item, Parent Page, and then something else after. I guess it is the current cursor position in the list. It's very odd, but I think it will just have to suffice until something better can be done.

In general this searchable combo box is not the most accessible thing in the world, but I support this PR as it fixes a major issue on Mac.

Thanks.
