### PR TITLE
Fix duotone rendering in site editor

### LINKED ISSUE #35331: Duotone filter not rendering in some places
## Description

When applying duotone as a block style in theme.json, there are still a couple places the duotone filter doesn't get applied.

See https://github.com/WordPress/gutenberg/pull/34667#issuecomment-930287643

The thumbnail for block patterns that use duotone won't show the filter applied:
Screenshot 2021-09-29 at 17 22 27

The site editor shows the image without a filter but the frontend works fine. The post editor when I insert an image does work fine:
Screenshot 2021-09-29 at 17 22 51

## To reproduce

You can test on Skatepark applying https://github.com/Automattic/themes/pull/4740

Or by adding the following to your theme.json for testing the image and cover blocks.

```json
{
	"styles": {
		"blocks": {
			"core/cover": {
				"filter": {
					"duotone": "var(--wp--preset--duotone--blue-red)"
				}
			},
			"core/image": {
				"filter": {
					"duotone": "var(--wp--preset--duotone--blue-red)"
				}
			}
		}
	}
}
```

### PR DESCRIPTION
**Pull request by ajlende**
## Description

Fix the site editor part of #35331

For duotone to work on the site editor we need to port the same changes introduced in the server at #34667.

## How has this been tested?

1. Set duotone styles in theme.json under `styles.blocks['core/image'].filter.duotone` as `var(--wp--preset--duotone--blue-red)` or a theme's duotone preset variable.
2. Open the site editor and add an image. 
3. The image should have duotone styles. 

## Screenshots 

Using TwentyTwentyTwo with the following added to theme.json:

```json
{
	"styles": {
		"blocks": {
			"core/image": {
				"filter": {
					"duotone": "var(--wp--preset--duotone--foreground-and-secondary)"
				}
			}
		}
	}
}
```

Before:

site editor with image without the filter applied

After:

site editor with image with the filter applied

## Types of changes

Bug fix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/edit-site/src/components/global-styles/utils.js [hunk 1]
```diff
@@ -49,6 +49,12 @@ export const PRESET_METADATA = [
 			},
 		],
 	},
+	{
+		path: [ 'color', 'duotone' ],
+		cssVarInfix: 'duotone',
+		valueFunc: ( { slug } ) => `url( '#wp-duotone-${ slug }' )`,
```
Comment (ajlende) [inline packages/edit-site/src/components/global-styles/utils.js:55]: I'm a bit unsure about this. It would be nice to specify it in duotone.js, but adding a hook for it seems a bit like overkill.

File: packages/edit-site/src/components/global-styles/utils.js [hunk 2]
```diff
@@ -49,6 +49,12 @@ export const PRESET_METADATA = [
...
+		svgFilter: 'duotone',
```
Comment (ajlende) [inline packages/edit-site/src/components/global-styles/utils.js]: Adding `svgFilter` to the `PRESET_METADATA` is how I'm limiting the duotone `editor.PresetSvgFilter` hook to only apply for duotone SVG filters. I'm curious if folks think this is the best way to go about that or if there's a better solution.

File: packages/block-editor/src/hooks/duotone.js [hunk 3]
```diff
@@ -326,3 +372,8 @@ addFilter(
 	'core/editor/duotone/with-styles',
 	withDuotoneStyles
 );
+addFilter(
+	'editor.PresetSvgFilter',
```
Comment (ajlende) [inline packages/block-editor/src/hooks/duotone.js]: Should this filter be `__unstable`?

File: packages/edit-site/src/components/block-editor/resizable-editor.js [hunk 4]
```diff
@@ -182,7 +182,10 @@ function ResizableEditor( { enableResizing, settings, ...props } ) {
 				name="editor-canvas"
 				className="edit-site-visual-editor__editor-canvas"
 				{ ...props }
-			/>
+			>
+				{ settings.svgFilters }
```
Comment (ajlende) [inline packages/edit-site/src/components/block-editor/resizable-editor.js:187]: Filters need to be rendered before children to avoid Safari rendering issues.

**Comment by ajlende** [comment]
@oandregal sorry it took me a while to get this up—it took me some time to understand how everything is wired up in the site editor. Because I don't feel hugely confident in how it all works, please read through it all thoroughly. Adding `?w=1` to the files url to hide whitespace changes can be helpful for duotone.js since a lot of indenting changed there with the refactoring that I did. Thanks!

File: packages/edit-site/src/components/block-editor/resizable-editor.js (hunk 4 above)
Comment (oandregal) [reply packages/edit-site/src/components/block-editor/resizable-editor.js:187]: Can we enqueue the default and theme SVGs from the server instead? The only change in the client would be to create the selectors using the duotone selector.

File: packages/edit-site/src/components/block-editor/resizable-editor.js [hunk 5]
```diff
@@ -182,7 +182,14 @@ function ResizableEditor( { enableResizing, settings, ...props } ) {
 				name="editor-canvas"
 				className="edit-site-visual-editor__editor-canvas"
 				{ ...props }
-			/>
+			>
+				<span
+					dangerouslySetInnerHTML={ {
+						__html: window._wpSvgFilters,
+					} }
+				/>
```
Comment (ajlende) [inline packages/edit-site/src/components/block-editor/resizable-editor.js]: @oandregal (re: https://github.com/WordPress/gutenberg/pull/37727#discussion_r789516704)

> Can we enqueue the default and theme SVGs from the server instead? The only change in the client would be to create the selectors using the duotone selector.

The filters still have to make their way into the iframe in the body before the content, but I was able to make it happen by throwing them into a variable and injecting them here. It feels a little awkward, but it avoids the JS `addFilter`.

I'm still not very excited about all of the changes needed for adding the styles, especially the `valueFunc` function that is going to be easy to forget if it ever changes in the PHP. Maybe we could do something similar for the styles by rendering them all on the server and injecting them like this.

Comment (oandregal) [reply packages/edit-site/src/components/block-editor/resizable-editor.js]: I'm not sure there's a better way to load the SVGs, I'm going to ping @ellatrix for thoughts.

Ella, for context: the duotone feature needs to enqueue a bunch of `SVG` HTML elements in the scope of the content, as they're used as filter styles. This PR explores make them available via the `_wpSvgFilters` global. We use `wp_body_open` for the frontend. Is there a better alternative?

File: packages/edit-site/src/components/global-styles/utils.js (hunk 1 above)
Comment (oandregal) [reply packages/edit-site/src/components/global-styles/utils.js:55]: Thinking of what happens when we allow users to be able to change the duotone assigned to a block via the global styles sidebar: at that point, we'd need the ability to regenerate the styles in the client, hence, we need this code. I think this should be fine, it works the same as any other existing preset (server & client implementation).

File: packages/edit-site/src/components/block-editor/resizable-editor.js (hunk 5 above)
Comment (ellatrix) [reply packages/edit-site/src/components/block-editor/resizable-editor.js]: Didn't we solve this previously with a portal? 

https://github.com/WordPress/gutenberg/blob/d06ee3a4c5d18e336e2a7f3e78dcf6a7f9a6e397/packages/block-editor/src/hooks/duotone.js#L294-L309

Comment (ajlende) [reply packages/edit-site/src/components/block-editor/resizable-editor.js]: @ellatrix That loads the inline per-block overrides, not the global styles SVG filters. For global styles, the SVG filters get rendered in the `wp_body_open` action here https://github.com/WordPress/gutenberg/blob/42cd5bbded43f84224c6d18e1c8f5aacae8e1268/lib/compat/wordpress-5.9/render-svg-filters.php#L16-L26

File: packages/edit-site/src/components/global-styles/utils.js (hunk 1 above)
Comment (ajlende) [reply packages/edit-site/src/components/global-styles/utils.js:55]: > Thinking of what happens when we allow users to be able to change the duotone assigned to a block via the global styles sidebar: at that point, we'd need the ability to regenerate the styles in the client, hence, we need this code.

Wouldn't that mean we'll need the ability to regenerate the SVGs too on the frontend then?

**Comment by kspilarski** [comment]
I have a user case using Twenty Twenty-two Swiss theme, where the images appeared colored in the site editor, but black and white on the live page.

File: packages/edit-site/src/components/block-editor/resizable-editor.js (hunk 5 above)
Comment (ellatrix) [reply packages/edit-site/src/components/block-editor/resizable-editor.js]: And we can't do the same thing with `useContext( BlockList.__unstableElementContext )`?

Comment (ajlende) [reply packages/edit-site/src/components/block-editor/resizable-editor.js]: No, because that is for the per-block overrides, not the global styles.

Take a look at the branch [one commit before the last](https://github.com/WordPress/gutenberg/compare/trunk...59b4151e55f5ee2972b87e06cffd4cf5546ba649) where I previously added a place for rendering the SVGs in JS to get an idea as to what this current approach is an alternative to.

File: packages/edit-site/src/components/block-editor/resizable-editor.js (hunk 4 above)
Comment (ajlende) [reply packages/edit-site/src/components/block-editor/resizable-editor.js:187]: I reverted this change because I expect we'll need this for updating the duotone filters in the site editor eventually

**Comment by gwwar** [comment]
I verified the issue in trunk, where filters are not seen in the site-editor, but are visible in post-editor and on the published page. 

When testing this branch I'm seeing a WSOD when loading the site editor, with "Objects are not valid as a React child" thrown when fetching global styles.

CleanShot 2022-02-15 at 15 50 49@2x

**Comment by ajlende** [comment]
@gwwar I'm not seeing any WSOD in my testing. I'm running wordpress-develop trunk and this branch after rebasing with gutenberg trunk. Maybe give it another try now?

**Comment by gwwar** [comment]
As a quick follow up note for other reviewers, the WSOD is visible when testing in Chrome but not FF.

**Comment by scruffian** [comment]
I rebased with trunk and see the WSOD still. I'll try to debug it...

**Comment by scruffian** [comment]
I did some more testing and now I can't reproduce it. I think it might be coming from a cached value - the error said something about cache but I am unable to see it again. Is there anything else preventing this from merging?

**Comment by ajlende** [comment]
Thanks for rebasing and testing @scruffian! I got distracted with some other things and haven't made my way back to this yet.

🤞 Hopefully the issue was something that was fixed with the rebase. I'll bring this back to the top of my priority list and give it another test tomorrow. 

> Is there anything else preventing this from merging?

If the problem is resolved from the rebase, I'd still want to hear from @ellatrix and @oandregal or have someone else who is familiar with global styles look over the code once more.

**Comment by ajlende** [comment]
Tested Firefox and Chromium on Linux and Firefox, Google Chrome, and Safari on MacOS and I wasn't getting the WSOD anymore either. Must have been some unrelated issue.

**Comment by jasmussen** [comment]
Thanks for this one, it's a really important one to land for 6.0!

**Comment by oandregal** [comment]
I've tested this and it works for me (both Chrome & Firefox in Ubuntu OS). Though I've noticed that the placeholder state of the image also gets the duotone styles applied:

Captura de ecrã de 2022-04-01 10-34-41

I'm going to do a code review now.

**Comment by jasmussen** [comment]
> Though I've noticed that the placeholder state of the image also gets the duotone styles applied:

Yes, this is an existing issue: https://github.com/WordPress/gutenberg/issues/31373

**Comment by oandregal** [comment]
When I have a duotone for the image block type via theme.json, I can still apply a duotone for a specific block instance in the post editor (and is properly rendered in the frontend):

https://user-images.githubusercontent.com/583546/161242774-3e3f9ee1-92c1-4aaf-9d26-7d364dc9969d.mp4

In the site editor, this is what happens when I apply a block instance duotone (if I publish, in the frontend it works fine: only the block instance duotone is applied):

https://user-images.githubusercontent.com/583546/161243151-6800b6f6-bd1a-4a3f-b306-77695ba9fc7f.mp4

File: packages/edit-site/src/components/block-editor/resizable-editor.js (hunk 4 above)
Comment (oandregal) [reply packages/edit-site/src/components/block-editor/resizable-editor.js:187]: > Filters need to be rendered before children to avoid Safari rendering issues.

Can we add this as a comment in the code to document why is was done this way?

File: packages/edit-site/src/components/global-styles/use-global-styles-output.js [hunk 6]
```diff
@@ -123,6 +135,27 @@ function getPresetsClasses( blockSelector, blockPresets = {} ) {
 	);
 }
 
+const PresetSvgFilter = withFilters( 'editor.PresetSvgFilter' )( () => null );
```
Comment (oandregal) [inline packages/edit-site/src/components/global-styles/use-global-styles-output.js]: What's the value of creating a specific filter for rendering duotone in the site editor? This is the reasons I see:

- We plan that third-parties will can hook into it. I don't understand how/why this would be the case?
- It's a way to share behaviour between the block-editor and the edit-site packages. If this is the primary reason, can't we just export the function we need (`DuotoneFilter`) from the block-editor package and import it here, as we do with the rest of the hook utilities?

File: packages/block-editor/src/hooks/duotone.js [hunk 7]
```diff
@@ -60,82 +60,109 @@ export function getValuesFromColors( colors = [] ) {
...
+ * @param {string} props.selector Selector to apply the filter to.
+ * @param {string} props.id       Unique id for this duotone filter.
+ * @param {Values} props.values   R, G, B, and A values to filter with.
+ *
+ * @return {WPElement} Duotone element.
+ */
+function InlineDuotone( { selector, id, values } ) {
+	return (
+		<>
+			<DuotoneFilter id={ id } values={ values } />
```
Comment (oandregal) [inline packages/block-editor/src/hooks/duotone.js:164]: I understand we need this for the block-instance duotone. Though, in the site editor, we'll be adding the SVG when we already have it, don't we? This is all the ways we add SVGs in the site editor:

- We load them all via the `in_admin_header` hook ([see](https://github.com/WordPress/gutenberg/blob/39333d427000e3b7dcff16da842a14c109abc844/lib/compat/wordpress-5.9/render-svg-filters.php#L38)). These aren't in the scope of the iframed editor. So perhaps we can add there a check for not loading them if we're in the site editor?
- We load them all dynamically via the regular preset mechanism introduced in this PR (`svgFilters`).
- We load the specific filter when the user attaches it to a block instance.

I don't think this is a blocker given the time-sensitive situation we're in. Thought I'd think it merits a follow-up PR to organize it a bit.

File: packages/edit-site/src/components/global-styles/utils.js (hunk 2 above)
Comment (oandregal) [reply packages/edit-site/src/components/global-styles/utils.js]: Do we still need this if we don't use a filter? [related convo](https://github.com/WordPress/gutenberg/pull/37727/files#r840444001).

File: packages/blocks/src/api/constants.js [hunk 8]
```diff
@@ -56,6 +56,10 @@ export const __EXPERIMENTAL_STYLE_PROPERTY = {
 		support: [ 'color', 'text' ],
 		requiresOptOut: true,
 	},
+	filter: {
+		value: [ 'filter', 'duotone' ],
+		support: [ 'color', '__experimentalDuotone' ],
```
Comment (oandregal) [inline packages/blocks/src/api/constants.js:109]: We don't really need declare `support`, do we? I mean, it's fine and even nice because it's whole. For a moment I thought whether this would make any block panel in the GS sidebar to show (despite not having any other support), but it seems we're fine there. Nothing to do here, just documenting my thought process and worries.

**Review by oandregal — COMMENTED** [review]
I've finished reviewing this PR and:

- We need to make the duotone at the block instance work (it works in `trunk`) ([thread](https://github.com/WordPress/gutenberg/pull/37727#issuecomment-1085713264))
- I'd like to see if we can not introduce a specific filter for duotone and use export/import instead ([thread](https://github.com/WordPress/gutenberg/pull/37727/files#r840444001))

Other than that, this would be ready to land in my view.

File: packages/edit-site/src/components/global-styles/use-global-styles-output.js (hunk 6 above)
Comment (ajlende) [reply packages/edit-site/src/components/global-styles/use-global-styles-output.js]: > We plan that third-parties will can hook into it.

This is the long-term vision of it—plugin authors being able to create their own complex filters that don't make sense for core. But maybe I'm getting ahead of myself and should wait until the other pieces of that are more complete. 😅

File: packages/blocks/src/api/constants.js (hunk 8 above)
Comment (ajlende) [reply packages/blocks/src/api/constants.js:109]: This is actually the cause of the block instance issue https://github.com/WordPress/gutenberg/pull/37727#issuecomment-1085713264. It's adding the filter to the block container which we don't want.

File: packages/edit-site/src/components/global-styles/use-global-styles-output.js (hunk 6 above)
Comment (oandregal) [reply packages/edit-site/src/components/global-styles/use-global-styles-output.js]: Ah, I see. Yeah, I think we can go with the import solution and leave the filter out for when we cross that bridge.

File: packages/blocks/src/api/constants.js (hunk 8 above)
Comment (oandregal) [reply packages/blocks/src/api/constants.js:109]: If we remove the `filter` constant, the duotone ruleset (`editor-styles-wrapper .wp-block-image img { filter: <value>; }`) is not rendered client-side in the site editor as the other block styles (we could also remove the `filter` in `pickStyleKeys`).

I've checked the plugin with the following versions:

- WordPress latest: this works fine.
- WordPress 5.9: this works fine.
- WordPress 5.8: this does not work.

Why does it work in 5.9 and onwards?

It seems we enqueue some extra stylesheet starting in 5.9. I don't know why or when we've introduced this, but we shouldn't rely on it in the site editor, as it's redundant and it should be removed. Can we make the duotone rendering in the site editor work?

Comment (oandregal) [reply packages/blocks/src/api/constants.js:109]: https://github.com/WordPress/gutenberg/pull/40185 is related although probably don't fully solve the issue (need to test more)

**Comment by scruffian** [comment]
> We need to make the duotone at the block instance work (it works in trunk)

I tested this with Skatepark and TT2 (there's a variation with duotone) and I could set duotone filters in the Site Editor even when the theme applies a different one (I think it's fixed!)

**Comment by scruffian** [comment]
> I'd like to see if we can not introduce a specific filter for duotone and use export/import instead ([thread](https://github.com/WordPress/gutenberg/pull/37727/files#r840444001))

I pushed a commit to achieve this. Feel free to revert it if it's not the right approach!

**Comment by jasmussen** [comment]
Let's gooo! ❤️ 😄

File: packages/blocks/src/api/constants.js (hunk 8 above)
Comment (oandregal) [reply packages/blocks/src/api/constants.js:109]: 40185 has landed and fixes this for 5.9. In 6.0 we need to get https://github.com/WordPress/wordpress-develop/pull/2542 in for the extra global stylesheet not being enqueued.

**Comment by oandregal** [comment]
> We need to make the duotone at the block instance work (it works in trunk) (https://github.com/WordPress/gutenberg/pull/37727#issuecomment-1085713264)

I've pushed a fix for this and block-level and global-level duotone work now in 5.9 and 6.0 <sup>[1]</sup>.

In addition to add the SVG to the site editor (`settings.svgFilters`), we also need to create the `duotone_selector { filter: url }` ruleset dynamically in the site editor (https://github.com/WordPress/gutenberg/pull/37727/commits/6d85792257e7fb540a2f1729f762a87d1d4865d8). I've taken a look at [how this works in the server](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.0/class-wp-theme-json-gutenberg.php#L333) and ported the necessary changes: we need to take the duotone selector (different from the block selector) from the block metadata if it exists (https://github.com/WordPress/gutenberg/pull/37727/commits/4de57374e44ebf085d0c9f99bd234984c26e4f74) and then use it to render the ruleset (https://github.com/WordPress/gutenberg/pull/37727/commits/edc11fb62d523ae22955a73f30b62c3aa3e80eaf).

---

<sup>[1]</sup> For testing 6.0, I've used this PR https://github.com/WordPress/wordpress-develop/pull/2542 to make sure the bug reported https://github.com/WordPress/gutenberg/pull/37727#discussion_r840467523 is not present, which hides this PR behavior due to the fact that global styles are loaded from the server instead.

**Review by oandregal — APPROVED** [review]

**Comment by oandregal** [comment]
There's a failing e2e test that is unrelated to this that it's failed in `trunk` at https://github.com/WordPress/gutenberg/runs/6061924208?check_suite_focus=true

**Comment by jasmussen** [comment]
🔥 👏

**Comment by adamziel** [comment]
This was backported to wp/6.0 branch to be included in WordPress 6.0 Beta 3 tomorrow: 
fbe64ec8d3
