### PR TITLE
Accessibility: Make text alignment items radio menu items.

### LINKED ISSUE #18721: Text alignment controls lack semantic indication of the active state
In WordPress 5.2, the text alignment buttons of the block toolbar were rendered as a group of buttons. The active state was communicated with an `aria-pressed` attribute. This made the visual feedback match the semantic feedback and assistive technology users were able to understand which alignment was set:

Screenshot 2019-11-25 at 16 51 39

In WordPress 5.3 (not sure since which Gutenberg version) the text alignment setting in the block toolbar was refactored to use a drop down menu. The buttons within the drop down don't have any kind of semantic indication of the active state. Assistive technology users (and any other software as well) now don't have any clue of what alignment is set. There's only a visual indication, no semantics at all:

Screenshot 2019-11-25 at 16 49 07

This is an accessibility regression, as the previous implementation had the proper semantics.

Worth also reminding that this drop down component renders an ARIA `menu` which can contain only three kind of elements:
- a generic `menuitem`
- a `menuitemcheckbox` for multiple choices
- a `menuitemradio` for single choices

In this case, since the text alignment can be set only to one value at a time, the menu items should use a `menuitemradio` role instead of a generic `menuitem`.

Seems to me the drop down menu items should use the `MenuItem` component instead of `IconButton` because `MenuItem` already has all that's needed and it's already used for this purpose, for example in the "More" menu in the Editor main toolbar.

Please consider to:
- use `MenuItem` for the items
- pass a `role="menuitemradio"` prop
- pass a `isSelected={ control.isActive }` prop which will render an `aria-checked` attribute with a true/false value depending on the item state

### PR DESCRIPTION
**Pull request by MarcoZehe**
## Description

Pass a role from the alignment toolbar to the dropdown menu. Make the dropdown menu aware of this role on each control and set it if present. Also set aria-checked on the active control if the role calls for it. Fixes #18721.

## Types of changes

Bug fix.
## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Review by gziolo — COMMENTED** [review]
It all makes sense. I guess I missed it completely when converting the alignment options to the dropdown. I think we have the same logic covered already in the `MenuItem` component, so it would be a good idea to use this component rather than the `IconButton`. The challenge here is that those block alignment toolbar (groups) support `isCollapsed` flag. When they aren't collapsed, they should be regular `IconButton` without the role applied. The easiest way to move forward would be to apply  `menuitemradio` role conditionally and move forward with your proposal. What do you think?

**Comment by MarcoZehe** [comment]
> 
> 
> It all makes sense. I guess I missed it completely when converting the alignment options to the dropdown. I think we have the same logic covered already in the `MenuItem` component, so it would be a good idea to use this component rather than the `IconButton`. The challenge here is that those block alignment toolbar (groups) support `isCollapsed` flag. When they aren't collapsed, they should be regular `IconButton` without the role applied. The easiest way to move forward would be to apply `menuitemradio` role conditionally and move forward with your proposal. What do you think?

Yes, that makes sense. I will add that bit, hoping it will pass. :-) However, I have a problem currently that the conditional role is not yet being applied to those icon buttons. So when I try this PR on gutenberg.run, it is still a normal menu item, and aria-checked is not set at all. So I am not sure why.

File: packages/components/src/dropdown-menu/index.js [hunk 1]
```diff
@@ -153,7 +153,8 @@ function DropdownMenu( {
 										},
 									) }
 									icon={ control.icon }
-									role="menuitem"
+									aria-checked={ ( control.role === 'menuitemcheckbox' || control.role === 'menuitemradio' ) ? control.isActive : undefined }
```
Comment (ellatrix) [inline packages/components/src/dropdown-menu/index.js]: Is there no active state for other roles?

Comment (MarcoZehe) [reply packages/components/src/dropdown-menu/index.js]: No, for the normal menuitem, there is no aria-checked or the like, that is only supported for menuitemcheckbox and menuitemradio. And those are the only roles allowed here.

File: packages/block-editor/src/components/alignment-toolbar/index.js [hunk 2]
```diff
@@ -54,6 +54,7 @@ export function AlignmentToolbar( props ) {
 				return {
 					...control,
 					isActive,
+					role: 'menuitemradio',
```
Comment (ellatrix) [inline packages/block-editor/src/components/alignment-toolbar/index.js]: This works great. I wonder if we could have a `Toolbar` props called `type`, which could be either `radio`, `checkbox`, or nothing, and pass that down to `DropdownMenu` to handle the roles etc.

Comment (ellatrix) [reply packages/block-editor/src/components/alignment-toolbar/index.js]: And when a `Toolbar` is not collapsed, the `type` wouldn't do anything.

Comment (gziolo) [reply packages/block-editor/src/components/alignment-toolbar/index.js]: @diegohaz is working on some improvements around that in https://github.com/WordPress/gutenberg/pull/18931. One thing we discussed is to have `ToolbarGroup` which can be collapsible, and one way would be to have this type `radio` or `checkbox` as proposed. We might also try a more declarative way with JSX rather than using `controls` props. It needs to be further investigated.

Aside: I probably used my limit of pings for Diego for this year :)

**Review by ellatrix — APPROVED** [review]

**Comment by gziolo** [comment]
Awesome work, congrats on your first code contribution to Gutenberg 🎉
