### PR TITLE
Avoid rendering fills if empty elements inside

### LINKED ISSUE #20480: Block Editor: Ungroupable, non-reusable blocks show redundant block settings popover section
Possible regression of #19344 (cc @youknowriad, @jasmussen )

image

**Steps to Reproduce:**

1. Navigate to Posts > Add New
2. Insert Social Icons block
3. Click block settings
4. Observe undesirable blank section between "Duplicate" and "Remove block"

**Suspected cause:**

This section of the block settings normally contains "Add to Reusable blocks" and "Group" options, which leads me to think that we are not correctly omitting the section when a block is neither reusable nor groupable.

Example for paragraph block:

image

I note that this is a "possible regression of #19344", because I am not able to reproduce this in WordPress 5.4 Beta 3, but I can reproduce it in the latest `master`.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #20480 

> Possible regression of #19344
> 
> image
> 
> **Steps to Reproduce:**
> 
> 1. Navigate to Posts > Add New
> 2. Insert Social Icons block
> 3. Click block settings
> 4. Observe undesirable blank section between "Duplicate" and "Remove block"

The diff looks big but in the end, it's just moving things around to avoid rendering the Fills if their content is empty. This ensures that if there are no fills, the slot is empty too.

I tried a CSS fix but it's not that easy.

### CODE REVIEW

**Comment by youknowriad** [comment]
I don't really understand where the failing 404 is being triggered.

File: packages/editor/src/components/reusable-blocks-buttons/test/reusable-block-convert-button.js [hunk 1]
```diff
@@ -1,56 +0,0 @@
-/**
```
Comment (youknowriad) [inline packages/editor/src/components/reusable-blocks-buttons/test/reusable-block-convert-button.js]: With the new implementation, it's hard to unit test these components with snapshots. I removed the tests because these are already covered in e2e tests.

**Review by gziolo — APPROVED** [review]
I tested all the updated menu items and they still work as expected. I can also confirm that there is no empty section when there are no menu items in the plugins group.

Code wise I will leave the final call to you, @nosolosw and @getdave.
