### PR TITLE
Hide disabled blocks from shortcut inserter

### LINKED ISSUE #3968: Blocks can still be inserted from the list next to the inserter even if useOnce is true
## Issue Overview
I've created a block and set useOnce to true, however I'm still able to insert it when it shows up in the quick links next to the inserter. Notice in the screenshot below how my Test Block is greyed out in the actual inserter but can still be highlighted and clicked in the quick links.

screenshot 2017-12-12 21 50 18_preview

## Steps to Reproduce (for bugs)

1. Create a block with useOnce set to true.
2. Use the block enough times that it shows up in the quick links.
3. You can insert it more than once using the quick links even though useOnce is true.

## Expected Behavior

You should be able to only insert the block once. 

## Current Behavior

You can insert the block more than once.

### PR DESCRIPTION
**Pull request by Soean**
## Description
This PR hides blocks with `isDisabled` attribute from the shortcut inserter. For example if blocks with `multiple: false` are already inserted. There are only 3 Items so it does't make sense to just disable the button.
Fixes #3968

## Screenshots 
juni-17-2018 13-33-01

### CODE REVIEW

**Review by danielbachhuber — APPROVED** [review]

File: editor/components/inserter-with-shortcuts/index.js [hunk 1]
```diff
@@ -23,9 +23,12 @@ function InserterWithShortcuts( { items, isLocked, onInsert } ) {
 		return null;
 	}
 
-	const itemsWithoutDefaultBlock = filter( items, ( item ) =>
-		item.name !== getDefaultBlockName() || ! isEmpty( item.initialAttributes )
-	).slice( 0, 3 );
+	const itemsWithoutDefaultBlock = filter( items, ( item ) => {
```
Comment (aduth) [inline editor/components/inserter-with-shortcuts/index.js]: Is this function name still accurate? It's now doing more than just checking whether the block is the default block. To be fair, it wasn't even very accurate previously, because it was referring to the "unchanged default block", which is logic duplicated with [`wp.blocks.isUnmodifiedDefaultBlock`](https://github.com/WordPress/gutenberg/blob/a292eb514c7eb21c27323d7b1314df0cb5ca940f/blocks/api/utils.js#L27-L52).
