### PR TITLE
Show Classic block contents on load

### LINKED ISSUE #24696: Unable to edit Classic Block on regular (web) editor
**Describe the bug**

This seems related to https://github.com/WordPress/gutenberg/issues/24563, however I didn't see an issue or patch for the regular web editor. After saving a post with a Classic Block, the contents of the Classic Block are not visible and the block encounters a JS error when used.

**To reproduce**
1. Create a new post with a Classic Block. Save the post.

Screen Shot 2020-08-20 at 11 38 52 AM

2. Refresh the page. Observe the block content is missing from the Classic Block:

Screen Shot 2020-08-20 at 11 39 26 AM

3. With the JS console open, click on the block toolbar for the Classic Block (the gray bar that says "Classic"). Observe block encounters a fatal error and the JS console logs `Cannot read property 'getContent' of null`:

Screen Shot 2020-08-20 at 11 39 39 AM

4. Go to code view. Observe content is still there:

Screen Shot 2020-08-20 at 11 39 52 AM

5. Go back to visual view. Observe block preview works correctly after coming from code view:

Screen Shot 2020-08-20 at 11 40 00 AM

**Expected behavior**
I expected the block content of Classic Block to render correctly when editing a saved post.

**Screenshots**
See steps to reproduce above.

**Editor version (please complete the following information):**
- WordPress version: 5.5.0
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? I reproduced the error on a clean site using only WP 5.5.0 and Gutenberg 8.8.0
- If the Gutenberg plugin is installed, which version is it? 8.8.0. This bug seems to have been introduced in 8.8.0, as rolling back to 8.7.1 solves the issue.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 84.0.4147.125

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/24696

With the update of React there seems to be some `async` changes that made the initialization of `Classic` block not to be triggered. This changes the event to hook on to `load`.

### CODE REVIEW

File: packages/block-library/src/classic/edit.js [hunk 1]
```diff
@@ -54,7 +54,7 @@ export default class ClassicEdit extends Component {
 		if ( document.readyState === 'complete' ) {
```
Comment (youknowriad) [inline packages/block-library/src/classic/edit.js:54]: It seems this condition is meant to handle the case where the block is rendered after the "load" happens. So I believe right now, we might be loading the block between the `DOMContentLoaded` event and the moment the `readyState` is set to "complete".

I don't know if `load` used for the event handler is the right event to use here but we should probably be using the event that happens at the moment `document.readyState` is set to "complete" to ensure the block works properly no matter when it's rendered.

Comment (ntsekouras) [reply packages/block-library/src/classic/edit.js]: Hm.. okay.. Thanks Riad!

**Comment by sirreal** [comment]
This does appear to fix the issue in question in my testing.

**Comment by youknowriad** [comment]
If someone has time later, this is a good opportunity for an e2e test

 - add classic block
 - add content
 - save
 - reload
 - check rendered content
 - switch to code editor and back
 - check rendered content

**Review by ockham — APPROVED** [review]
Thanks! Confirming that this is fixing #24696, per the latest commit (f4fadf47700e1d3f8c7843ed54874c071d5f7d1a)

:shipit:

**Comment by fullofcaffeine** [comment]
> If someone has time later, this is a good opportunity for an e2e test
> 
> * add classic block
> * add content
> * save
> * reload
> * check rendered content
> * switch to code editor and back
> * check rendered content

I will take this one for a spin.
