### PR TITLE
Safari: fix Shift+Click multi select

### LINKED ISSUE #44755: Safari: Shift+click can't select across text blocks
### Description

Clicking while pressing the Shift key is a convenient way to create a selection between two points. Since the introduction of partial multi-selection in #38892, users can expect to use this method of selection across blocks, just as they would in a word processor. It doesn't work in Safari, though.

### Step-by-step reproduction instructions

1. **In Safari,** in a post with multiple paragraphs, place the caret inside one.
2. While holding the Shift key, click in the middle of an adjacent paragraph.

Expected: a partial selection across the two paragraphs
Observed: a collapsed selection in the second paragraph

### Screenshots, screen recording, code snippet

A comparison between Firefox (expected behaviour) and Safari (unexpected). In both browsers, shift-clicking _inside the same paragraph_ works (unsurprisingly), but shift-clicking across blocks just moves the collapsed selection when using Safari.

https://user-images.githubusercontent.com/150562/194375803-0b7bfc91-7da5-418d-a3ff-90c9bfe8d32d.mov

### Environment info

Gutenberg trunk, etc.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Fixes #44755.

Safari doesn't allow Shift+Click selection inside content editable _into_ an element with a tab index. Instead it focusses that element. Except for removing the tab index, there's no way to otherwise prevent a focusable element from gaining focus as far as I know. Normally, contentEditable should be disabling all interactivity.

## How?

Thought a while about it, and then realised we don't actually need the tab index is the element is content editable, because these elements are already focusable.

### CODE REVIEW

File: packages/block-editor/src/components/copy-handler/index.js [hunk 1]
```diff
@@ -198,6 +198,7 @@ export function useClipboardHandler() {
 				if ( shouldHandleWholeBlocks && ! expandSelectionIsNeeded ) {
 					removeBlocks( selectedBlockClientIds );
 				} else {
+					event.target.ownerDocument.activeElement.contentEditable = false;
```
Comment (ellatrix) [inline packages/block-editor/src/components/copy-handler/index.js:201]: This is actually a bug introduced in #40098. When using `__unstableDeleteSelection`, contenteditable needs to be turned off first (see other instances). Ideally we should move this logic to writing flow and build in clipboard handling there.

**Review by richtabor — APPROVED** [review]
Works! 

Before (unable to multi-select): 

https://github.com/WordPress/gutenberg/assets/1813435/8e97d7a2-0d07-4806-b1fa-6c598dc9724a

After (able to multi-select): 

https://github.com/WordPress/gutenberg/assets/1813435/5d072014-83f3-4416-80c3-1cf92be0f872

**Comment by ellatrix** [comment]
Added the existing e2e test to be run on WebKit.
