### PR TITLE
Editor: Trigger reusable blocks autocomplete when options generated

### LINKED ISSUE #14766: Merely selecting a block after load creates undo level
**To Reproduce**

1. Create a new post.
2. Create a new paragraph with some text.
3. Save the post.
4. Reload the page.
5. Select the paragraph block.
6. Observe that the undo button is not disabled any longer.

**Expected behavior**

I don't expect block selection to create undo levels.

**Additional context**

I see the following actions when I select a block:

```js
{type: "FETCH_REUSABLE_BLOCKS", id: undefined}
{type: "SELECT_BLOCK", initialPosition: null, clientId: "adb9ef30-61f7-45c3-b785-01fc5ca630e3"}
{type: "RECEIVE_REUSABLE_BLOCKS", results: Array(1)}
{type: "UPDATE_SETTINGS", settings: {…}}
{type: "RECEIVE_BLOCKS", blocks: Array(1)}
{type: "RESET_EDITOR_BLOCKS", blocks: Array(1), shouldCreateUndoLevel: false}
{type: "FETCH_REUSABLE_BLOCKS_SUCCESS", id: undefined}
```

So it looks like it has something to do with reusable blocks fetching? Cc @noisysocks @aduth.

### PR DESCRIPTION
**Pull request by aduth**
Fixes #14766 

This pull request changes the behavior of the default block autocompleter to avoid triggering a fetch of reusable blocks until the time at which the user begins entering a search query which would prompt the block autocompleter to generate its own options set. Prior to this change, a fetch would occur immediately upon selecting a paragraph block. While this had the benefit of preloading data for improved likelihood could be reflected in the search query, it had the downsides of (a) not guaranteeing this likelihood, (b) incurring the overhead of a network request, and (c) causing changes in state. The last of these manifests itself in the bug report described in #14766.

For transparency's sake, I should be clear that the implementation here does not solve the underlying issue that receiving reusable blocks into editor state has the dual effect of creating an undo level and marking the post as having unsaved changes. This is tracked more thoroughly at #14910, with a separate improvement planned. Thus, it is still expected that unexpected undo history will accumulate in response to reusable blocks fetching (e.g. clicking the Inserter when on a new post will add an Undo level). Technically speaking, the full fix considered for #14910 at https://github.com/WordPress/gutenberg/issues/14910#issuecomment-481808021 would resolve both #14910 and #14766, at which point this pull request could be considered an optional enhancement / change in behavior to defer fetching of reusable blocks.

Separately, I anticipate that we should explore further refactoring of autocompleters to avoid "fetches" as explicit actions, and consider what solutions might exist for being able to express autocompleter options via subscribed selectors (or `withSelect`-bound components) and complementing resolvers.

**Testing Instructions:**

Repeat Steps to Reproduce from #14766, observing that no undo level is created.

### CODE REVIEW

File: packages/editor/src/components/autocompleters/block.js [hunk 1]
```diff
@@ -41,6 +46,25 @@ function defaultGetSelectedBlockName() {
...
+ * Triggers a fetch of reusable blocks, once.
+ *
+ * TODO: Reusable blocks fetching should be reimplemented as a core-data entity
+ * resolver, not relying on `core/editor` (see #7119). The implementation here
+ * is imperfect in that the options result will not await the completion of the
+ * fetch request and thus will not include any reusable blocks. This has always
+ * been true, but relied upon the fact the user would be delayed in typing an
+ * autocompleter search query. Once implemented using resolvers, the status of
+ * this request could be subscribed to as part of a promised return value using
+ * the result of `hasFinishedResolution`. There is currently reliable way to
```
Comment (jorgefilipecosta) [inline packages/editor/src/components/autocompleters/block.js]: There is currently (no) reliable way to

**Review by jorgefilipecosta — APPROVED** [review]
LGTM 👍 I verified that before as soon as I focused paragraph a blocks request was immediately made, now the request is only made when the inserter or the autocomplete opens.

**Comment by aduth** [comment]
Thanks for the review @jorgefilipecosta !

While this does serve as a fix for #14766, that issue was also separately fixed by #14916 . I still think this pull request can be considered an improvement to avoid the fetch until necessary, but not as urgent as it once was. I think I may wait until after the next plugin release to consider merging it. Either that, or give some more time to consider what might be necessary to support autocompleters which update options asynchronously.

**Comment by youknowriad** [comment]
Going to merge this as it brings more stability to e2e tests.
