### PR TITLE
Fix Fatal for unregistered taxonomy (#26851)

### LINKED ISSUE #26851: Fatal error in post-hierarchical-terms.php for unregistered taxonomy name
**Describe the bug**
When the `core/post-hierarchical-terms` block is invoked with a taxonomy name that's not registered a Fatal error is issued.
This is due to the logic trying to process a WP_error.

**To reproduce**
1. Create a template containing the `core/post-hierarchical-terms` block with an unknown taxonomy name.
```
 <!-- wp:post-hierarchical-terms {"term":"26851"} /-->
```
2. Attempt to view content using this template.
3. See two Notices and a Fatal error

Notice: Trying to get property 'term_id' of non-object in C:\apache\htdocs\wp55\wp-content\plugins\gutenberg\build\block-library\blocks\post-hierarchical-terms.php on line 32

Notice: Trying to get property 'name' of non-object in C:\apache\htdocs\wp55\wp-content\plugins\gutenberg\build\block-library\blocks\post-hierarchical-terms.php on line 33

Fatal error: Uncaught Error: Object of class WP_Error could not be converted to string.

**Expected behavior**
Fail gracefully by returning '' when a WP_Error has been detected.

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] 5.6-beta3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] 9.3.0
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 86.0.4240.183 (Official Build) (64-bit)

**Additional context**
- Originally raised as https://github.com/bobbingwide/fizzie/issues/29
- In my opinion the attribute should not be called `term`; it is the taxonomy name.

- It is possible to create this problem using the Code editor in a post.
- If you do so, and you quit the editor in Visual editor mode, then you may find it difficult to fix the error.
- The problem occurs in the editor as  well as the front-end.
- You may have to resort to the classic editor.
image

### PR DESCRIPTION
**Pull request by bobbingwide**
## Description
When the `core/post-hierarchical-terms` block has been passed an invalid taxonomy name for the `term` attribute it produced a Fatal error due to not detecting a WordPress error (  `WP_error` object )  returned from `get_the_terms()`.

This fix adds an `is_wp_error()` test, returning an empty string when detected. 

## How has this been tested?
Tested with Twenty Twenty-One Blocks in WordPress 5.6-beta3

I manually created a post using the code editor containing.
```
<!-- wp:post-hierarchical-terms {"term":"26851"} /-->

<!-- wp:post-hierarchical-terms {"term":"category"} /-->
```
Prior to applying the fix I got the Fatal error.
After applying the fix the output showed the taxonomy terms associated with Categories.
There was no visible output for the unknown taxonomy.
With the fix applied the post could be viewed and edited, using both the Code and Visual editor.

## Screenshots 
image

## Types of changes
Fixes #26851 

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-library/src/post-hierarchical-terms/index.php [hunk 1]
```diff
@@ -19,6 +19,9 @@ function render_block_core_post_hierarchical_terms( $attributes, $content, $bloc
 	}
 
 	$post_hierarchical_terms = get_the_terms( $block->context['postId'], $attributes['term'] );
+	if ( is_wp_error( $post_hierarchical_terms ) ) {
+		return '';
+	}
 	if ( empty( $post_hierarchical_terms ) ) {
```
Comment (gziolo) [inline packages/block-library/src/post-hierarchical-terms/index.php:25]: This new condition could be combined with `empty` check.

**Review by gziolo — APPROVED** [review]
Thanks for catching this one. I see that you are right about [`get_the_terms `](https://developer.wordpress.org/reference/functions/get_the_terms/) and its return value.

Should we add this check to the existing condition?

File: packages/block-library/src/post-hierarchical-terms/index.php (hunk 1 above)
Comment (bobbingwide) [reply packages/block-library/src/post-hierarchical-terms/index.php:25]: Agreed. What do the coding guidelines say?

Comment (gziolo) [reply packages/block-library/src/post-hierarchical-terms/index.php:25]: I'm not aware of coding styles that cover it. I can merge as is if you prefer.

Comment (bobbingwide) [reply packages/block-library/src/post-hierarchical-terms/index.php:25]: Yes please. Then I can continue working on PRs for other issues.
