### PR TITLE
Edit Post: Reset active sidebar tab on initial load

### LINKED ISSUE #6377: Restore Document Tab when creating a new post/page
Recently a change was made to automatically select the "Block" tab of the sidebar whenever a block is selected, and then select the document tab when you deselect a block. However if the block tab is selected when you press "Add New", the Document tab isn't restored.

Steps to reproduce:

- Create a new post
- Insert a block, select it, verify the block tab is active
- Click "Add New" in the navigation sidebar to create a new post

Result: the block tab is still selected, but empty. It should show the document tab, since you don't have a block selected.

### PR DESCRIPTION
**Pull request by aduth**
Fixes #6377 
Related: #6382

This pull request seeks to resolve a regression which was recently introduced in recent refactoring of state persistence. The `SERIALIZE` action type is no longer used to limit or modify the persisted result.

The changes here, rather than imitate the equivalent, instead change active general sidebar to be a non-persisted state value. However, in implementing this it was discovered that we may want to at least persist whether or not the user chooses to dismiss the sidebar altogether. Thus, there are now two state values: `state.activeGeneralSidebar` (string, not persisted) and `state.preferences.isGeneralSidebarDismissed` (boolean, persisted).

It is not quite the same behavior in that if a plugin sidebar is activated, the sidebar will still be reset to `edit-post/document` on the next session. This is an intentional change.

**Testing instructions:**

Repeat steps to reproduce from #6377, ensuring that sidebar resets between editor sessions.

Ensure unit tests pass:

```
npm run test-unit
```

### CODE REVIEW

**Comment by jasmussen** [comment]
Can confim that this fixes the issue, thanks for looking at this.

`npm run test-unit` also pass the tests for me. 

screen shot 2018-08-15 at 09 40 13

File: edit-post/store/selectors.js [hunk 1]
```diff
@@ -40,14 +40,34 @@ export function isPluginSidebarOpened( state ) {
...
+	}
+
+	// If not dismissed and an active sidebar is assigned, used.
+	const { activeGeneralSidebar } = state;
+	if ( activeGeneralSidebar !== null ) {
+		return activeGeneralSidebar;
+	}
+
+	// Default to Document tab.
+	return 'edit-post/document';
```
Comment (youknowriad) [inline edit-post/store/selectors.js]: Is this necessary here? can't we assign it as a default value in the reducer?

**Review by youknowriad — APPROVED** [review]
LGTM 👍

File: edit-post/store/selectors.js (hunk 1 above)
Comment (aduth) [reply edit-post/store/selectors.js]: >Is this necessary here? can't we assign it as a default value in the reducer?

We can, and we should. Also as a top-level documented constant.

**Comment by aduth** [comment]
Given this was a regression, I might look to add a new E2E test case.
