### PR TITLE
Switch back to getAuthors

### LINKED ISSUE #26476: New authors dropdown breaks author selection for editors
**Describe the bug**
#23237 stopped using `getAuthors` and instead uses `getUsers`. `getUsers` automatically applies a `context=edit` which requires that the current user have the `list_users` capability. This capability only exists for administrators.

**To reproduce**
1. Create a new user with the "Editor" role.
2. Create a new post.
3. Observe the authors dropdown is missing.

**Expected behavior**
To be able to see the list of users.

**Screenshots**
image

**Editor version (please complete the following information):**
- WordPress version: trunk
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? plugin
- If the Gutenberg plugin is installed, which version is it? 9.2.1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 14

---

This dropdown really should only be loading users in the `embed` context if all it needs are their names and IDs.

Cc: @adamsilverstein, @youknowriad.

### PR DESCRIPTION
**Pull request by adamsilverstein**
## Description
Fixes https://github.com/WordPress/gutenberg/issues/26476

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/core-data/src/resolvers.js [hunk 1]
```diff
@@ -29,14 +29,29 @@ import { ifNotResolved, getNormalizedCommaSeparable } from './utils';
...
+/**
+ * Temporary approach to resolving editor access to author queries.
+ *
+ * @param {number} id The author id.
+ */
+export function* __unstableGetAuthor( id ) {
+	const users = yield apiFetch( {
+		path: `/wp/v2/users?who=authors&include=${ id }`,
+	} );
+	yield receiveUserQuery( 'author', users );
```
Comment (youknowriad) [inline packages/core-data/src/resolvers.js:52]: should the first argument here be "authors" to match the same entity as "getAuthors"?

Comment (adamsilverstein) [reply packages/core-data/src/resolvers.js:52]: Maybe? I think that results in the fetched author overwriting the authors? I can test.

Comment (adamsilverstein) [reply packages/core-data/src/resolvers.js:52]: Tested changing this and confirmed using the same key results in the query interfering with the `getAuthors` query, causing errors or unexpected results as the results from the two queries overwrite each other.

**Review by youknowriad — APPROVED** [review]

File: packages/editor/src/components/post-author/index.js [hunk 2]
```diff
@@ -21,17 +21,23 @@ function PostAuthor() {
...
 		( select ) => {
-			const { getUser, getUsers, isResolving } = select( 'core' );
+			const { __unstableGetAuthor, getAuthors, isResolving } = select(
+				'core'
+			);
 			const { getEditedPostAttribute } = select( 'core/editor' );
-			const author = getUser( getEditedPostAttribute( 'author' ) );
+			const author =
+				postAuthor ||
+				__unstableGetAuthor( getEditedPostAttribute( 'author' ) )[ 0 ];
```
Comment (youknowriad) [inline packages/editor/src/components/post-author/index.js:30]: Actually, why do we need `[ 0 ]` here. getAuthor only returns one author right?

**Comment by youknowriad** [comment]
Seems like there's some valid test failures.

File: packages/editor/src/components/post-author/index.js (hunk 2 above)
Comment (adamsilverstein) [reply packages/editor/src/components/post-author/index.js:30]: Yes, but it is returned as an array with a single element. I can change this so `__unstableGetAuthor` returns a single element which makes more sense based on the naming, does that sound good?

**Comment by adamsilverstein** [comment]
> Seems like there's some valid test failures.

I'll take a look.

**Comment by adamsilverstein** [comment]
> Seems like there's some valid test failures.

@youknowriad One issue was the selector was showing even when the site only had one author. 

I had removed the check for `authors.length <= 1` when switching to `getAuthors` because the `authors` in `check.js` uses the same data store as the selector itself, so when you started searching and got zero results, the `authors` in the check would also be empty and the selector would disappear! 

To alleviate this I added `originalAuthors` behind a memo call so it is only set once. What do you think?

File: packages/core-data/src/selectors.js [hunk 3]
```diff
@@ -56,12 +56,21 @@ export const isRequestingEmbedPreview = createRegistrySelector(
...
+/**
+ * Returns all available authors.
+ *
+ * @param {Object} state Data state.
+ *
+ * @return {Array} Authors list.
+ */
+export function __unstableGetAuthor( state ) {
+	const authors = getUserQueryResults( state, 'author' );
+	return authors ? authors[ 0 ] : [];
```
Comment (youknowriad) [inline packages/core-data/src/selectors.js:71]: It should probably return `null`  if the author was not found.

**Comment by youknowriad** [comment]
> the same data store as the selector itself, so when you started searching and got zero results, the authors in the check would also be empty and the selector would disappear!

I think that's the issue, both selectors use different queries, so they shouldn't share the same "query key".

File: packages/core-data/src/resolvers.js (hunk 1 above)
Comment (youknowriad) [reply packages/core-data/src/resolvers.js:52]: Mmm, so if I'm reading  this right `getAuthor(1)` and  `getAuthor(2)` are using the same query key which means if I trigger both concurrently, they'll mess with each other's result.

File: packages/core-data/src/selectors.js (hunk 3 above)
Comment (adamsilverstein) [reply packages/core-data/src/selectors.js:71]: Good point, will change.

**Comment by adamsilverstein** [comment]
> I think that's the issue, both selectors use different queries, so they shouldn't share the same "query key".

Right - that is why I changed the single author query key to 'author' vs 'authors'

File: packages/core-data/src/resolvers.js (hunk 1 above)
Comment (youknowriad) [reply packages/core-data/src/resolvers.js:53]: Yes, I did add dynamic query keys  for both getAuthor and getAuthors, I think it will solve both issues so I reverted the change you did with useMemo

**Comment by youknowriad** [comment]
This is looking good for me, but it could use some testing @adamsilverstein

**Comment by skorasaurus** [comment]
Hi, 

I tested this out (last commit - https://github.com/WordPress/gutenberg/pull/26554/commits/f507edbf8e7975a6c38a69d928048c987835213d  ) and the select author dropdown does not appear, even as an admin user. I created another user with the 'editor' role. 

I tried on a test site [wordpress 5.5.3], no other plugins installed except this one.

**Comment by tellthemachines** [comment]
Tested this branch on top of WP 5.6-beta4 and can confirm the post author dropdown isn't showing for either editor or admin users. The `PostAuthor` component doesn't seem to be rendering at all now 😕

**Comment by youknowriad** [comment]
Yep, i just realized I forgot to fix the query key in the selector.😅

**Comment by skorasaurus** [comment]
Thanks for the additional fix; with that last commit, I now confirm that the postauthor component now displays as intended and is keyboard accessible as well.

**Comment by adamsilverstein** [comment]
@youknowriad - Great! Works well in my testing.

**Review by adamsilverstein — COMMENTED** [review]
👍 Looks good!
