### PR TITLE
Patterns: edit source pattern in focus mode in post and site editors

### LINKED ISSUE #32353: Make Synced Patterns lockable so content cannot be edited inline
## What problem does this address?
The seamless experience of editing reusable blocks (in core since 5.7) causes a lot of trouble for my clients. They are struggling to know when they are editing a reusable block and when the normal content. 

For example, you have a reusable block in a column and you want to add another content to the column, no to the RB. What do you do? Users do click on the existing content and click on the + icon.

I've been explaining it since the 5.7 is out and it doesn't help at all. They don't want to pay that much attention to the editing and "locked" reusable block content would be the best.

## What is your proposed solution?
Option to disable direct editing for reusable blocks - either allow to return to the state before 5.7 was released or just lock it (and users would go to revealed wp_blocks post archive or something).

I would love to select a reusable block just as a parent to move it around, but not the child (I think that's the part when it causes a lot of trouble).

If I miss a filter or something I'll be really glad if you point me in the right direction. I've tried to disable it via CSS and pointer events and it's just super tricky and kind of mission impossible when I want to move the blocks but not to edit them (eg you need to select them via list view and then move them around):

```scss
.is-reusable {
    opacity: 0.5;
    cursor: not-allowed;
	.block-editor-block-list__layout > * {
		pointer-events: none;
	}
	.block-list-appender {
		display: none;
	}
}
```

### LINKED ISSUE #54442: Editing a Synced Pattern that you don't have permission to edit is a poor user experience
### Description

Take an Author who inserts a Sync'd Pattern into a new Post. The editor lets them edit it. There's no clear indication that I shouldn't be allowed to.

Once I go to Publish my post, things get ugly and could end up in a really bad state.  I'm presented with a series of checkboxes about what I want to Save. Again, the UI gives me the option to save updates to the Pattern (and it's checked by default), so I'd imagine that I can. However, I can't.  And the only reason given for this is a big red generic error that says "Saving failed." At this point, I'd imagine my entire attempt to publish failed, but that's not the case.

My post has actually been published in a state that looks **different** from what it is in the editor, because the Pattern wasn't updated.  This feels really wrong.

The best solution, in my opinion, is to not let me edit the Synced Pattern to begin with. If I can't save the changes, why let me edit it in the editor?  I think that any attempts to edit the Pattern should prompt me with a message saying I can't edit it - perhaps I want to detach it (and what that means).

### Step-by-step reproduction instructions

1. Have User 1 create a sync'd pattern.
2. Have Author 2 insert it into a new Post.
3. Have author 3 edit the pattern and try to publish the post.
4. Confirm that the post was published with the OLD content of the pattern, and that the only error message I'm shown is a generic "Saving failed."

### Screenshots, screen recording, code snippet

_No response_

### Environment info

6.3.1. No Gutenberg plugin.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by glendaviesnz**
## What?
In the `Synced patterns partial syncing` experiment locks pattern editing in the post editor to only child blocks that have had content connections set.

**N.B.** This PR changes the paradigm for editing synced patterns in the editor and moves the editing of a pattern's content that causes global changes to a focus mode view, similar to template editing.

## Why?
As part of the work on allowing [partial editing of synced patterns](https://github.com/WordPress/gutenberg/issues/53705) we want to disable full editing of the synced pattern entities within the block editor.

This will make it easier to indicate to users when they are editing just a section of the pattern for that instance of the pattern only, versus editing the global source pattern instance.

This would also fix https://github.com/WordPress/gutenberg/issues/54442 as the edit button only shows if the user has permission to update the pattern. It also fixes #32353

## How?

- Sets each of the patterns innerBlocks edit mode to `disabled` using `setBlockEditingMode` unless the block connected attributes are set in which case the block is set to `contentOnly`. 
- Adds an `Edit` button to pattern block toolbar to edit source pattern.

**Important note** - limiting editing to `contentOnly` in the post editor is 🤞 just the starting point. We are keeping it restricted to contentOnly to keep things simple while we set up the initial APIs for implementing partial syncing. The hope is that we can later extend it out to things like innerBlocks, limited block style attributes, etc. when/if the complexities around doing so are resolved.

## Testing Instructions
- Make sure the synced pattern experiment is enabled
- Add a synced pattern 
- Insert the pattern into the block editor and check that the child blocks can't be edited, and don't appear in the list view
- Check that the `Edit original` button in the block toolbar redirects to focus mode canvas. Make sure pattern can be edited and that back button on top menu bar works as expected. 
- Check that changes to pattern show in post editor once when you go back and that the pattern shows as needing to be saved when you click  the post save button
- Check that the `Edit original` button does not display if the user does not have edit permission for the given pattern
- Also add the synced pattern in the site editor in a template and make sure `Edit original` and back buttons works as expected
- Add a new synced pattern using the following block markup, add the block to a post and make sure the Heading can't be edited but the paragraphs can be edited as `contentOnly`. Also check that the `Content` panel appears in right inspector panel when block or nested content selected.
- Turn of the synced pattern experiment and check that the synced patterns still behave the same as they do in trunk

```
<!-- wp:heading -->
<h2 class="wp-block-heading">This heading must stay the same</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"metadata":{"id":"tbm3po"},"connections":{"attributes":{"content":{"source":"pattern_attributes"}}}} -->
<p>You can change this</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"metadata":{"id":"Gt1Y1m"},"connections":{"attributes":{"content":{"source":"pattern_attributes"}}}} -->
<p>And you really should change this</p>
<!-- /wp:paragraph -->
```

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/3629020/a5ac3082-da0f-4377-bd56-4ba8c97ec768

### CODE REVIEW

**Comment by glendaviesnz** [comment]
There is a console error thrown when switching to focus mode:
Screenshot 2023-12-14 at 2 40 43 PM
This is an existing issue in trunk and also happens when switching to template edit mode. I will look at this in a separate follow up PR

File: packages/block-library/src/block/edit.js [hunk 1]
```diff
@@ -132,12 +135,56 @@ function getOverridesFromBlocks( blocks, defaultValues ) {
...
+) {
+	const currentArgs = getQueryArgs( window.location.href );
+	const currentUrlWithoutArgs = removeQueryArgs(
+		window.location.href,
+		...Object.keys( currentArgs )
+	);
+	const newUrl = addQueryArgs( currentUrlWithoutArgs, {
+		...currentArgs,
+		patternId,
+	} );
```
Comment (glendaviesnz) [inline packages/block-library/src/block/edit.js]: It didn't seem worth adding in `@wordpress/router` dependency and the router context provider just for this one small push to the query params. I thought adding the pattern id to url would make the browser back button work, but it doesn't so I am wondering if we should add the pattern id to the store somehow instead, eg. `setEditedPattern` to track this between modes instead of appending to url - what do you think?

File: packages/block-library/src/block/edit.js [hunk 2]
```diff
@@ -8,26 +8,29 @@ import classnames from 'classnames';
...
 	__experimentalUseHasRecursion as useHasRecursion,
 	InnerBlocks,
-	InspectorControls,
 	useBlockProps,
 	Warning,
 	privateApis as blockEditorPrivateApis,
 	store as blockEditorStore,
+	BlockControls,
 } from '@wordpress/block-editor';
 import { getBlockSupport, parse } from '@wordpress/blocks';
```
Comment (glendaviesnz) [inline packages/block-library/src/block/edit.js:30]: not sure if adding the `editor` package as a dependency of blocks is a good thing or not, but couldn't see another way of setting the rendering mode from within a block.

Comment (talldan) [reply packages/block-library/src/block/edit.js:30]: Yep, blocks shouldn't really depend on `@wordpress/editor`.

One option that comes to mind, you could use a `BlockEdit` filter in the `edit-post` package to augment the block.

For example, you could pass in an additional prop to the block edit function, something like `editPatternInFocusMode`. The block could check for the existence of that prop, and when it exists we show the button for editing and make the `onClick` trigger the function.

The functionality in the site editor could potentially be built the same way.

Comment (glendaviesnz) [reply packages/block-library/src/block/edit.js:30]: ah, nice, will make that change tomorrow. I wonder if I can add the filter to the `editor` package as now that is also being shared by the site editor it would then work across both editors 🤔

**Comment by paaljoachim** [comment]
Looking at the video I expected to see the lock icon in the toolbar of the block that could not be edited. So that one would have to click the lock icon and directly unlock it to gain access to editing the specific block.

**Comment by glendaviesnz** [comment]
> Looking at the video I expected to see the lock icon in the toolbar of the block that could not be edited. So that one would have to click the lock icon and directly unlock it to gain access to editing the specific block.

I did discuss the lock icon with @SaxonF but we decided that this was a slightly different paradigm to the other locking options so we wanted to avoid using it, ie. this is about different editing contexts, instance versus global, more than locking. It is something that can be discussed further though for sure once we get this merged and people test it. @SaxonF do you have anything to add about this?

**Comment by annezazu** [comment]
I know this touches on a wider problem with the snackbar notices but this is rough:
- First notice is far too long
- There are too many back to back notices
- Says "post updated" when you're editing a pattern

Screenshot 2023-12-14 at 12 45 24 PM

Since we're reusing much of the template vs content editing experience right now, I'm curious how we're going to handle folks clicking on the parts of a pattern that can't be edited. Will we show a notice for folks to explain how they can edit that section? I worry it'll be wildly frustrating otherwise and we need a way to guide people seamlessly.

**Comment by glendaviesnz** [comment]
Thanks @annezazu those mulitplying snackbars were on my list to sort - any ideas on some nice short wording to convey the ideas in the first one?

> Since we're reusing much of the template vs content editing experience right now, I'm curious how we're going to handle folks clicking on the parts of a pattern that can't be edited. Will we show a notice for folks to explain how they can edit that section

@SaxonF any thoughts on UX for indicating to the user why they can't edit all of a synced pattern inline in the post?

File: packages/block-library/src/block/edit.js (hunk 2 above)
Comment (glendaviesnz) [reply packages/block-library/src/block/edit.js:30]: Moving this to the editor package worked for both post and site editor

File: packages/editor/src/components/provider/index.js [hunk 3]
```diff
@@ -154,8 +158,14 @@ export const ExperimentalEditorProvider = withRegistryProvider(
 			type,
 			id
 		);
+
```
Comment (glendaviesnz) [inline packages/editor/src/components/provider/index.js:161]: I was playing with passing the pattern id via  the query param as the hope that the browser back button would work with this pushed to the history, but it doesn't for some reason, so we are probably better off passing this via the store somehow 🤔

File: packages/editor/src/components/document-bar/index.js [hunk 4]
```diff
@@ -48,39 +50,75 @@ const icons = {
...
+
+	function handleOnBack() {
+		if (
+			patternId &&
+			dirtyEntityRecords.length > 0 &&
+			dirtyEntityRecords.find( ( record ) => record.key === patternId )
+		) {
+			createWarningNotice(
+				__(
+					'Your pattern changes will not show in the post until they are saved'
```
Comment (talldan) [inline packages/editor/src/components/document-bar/index.js]: We should be able to fix this. I imagine it's because since #56235, the experimental version of the pattern block no longer uses `useEntityBlockEditor`, the inner blocks are static when the block is first created and only use the pattern data as a sort of 'starter content'.

That's an unanticipated problem (cc @kevin940726).

File: packages/editor/src/components/provider/index.js [hunk 5]
```diff
@@ -109,7 +112,8 @@ export const ExperimentalEditorProvider = withRegistryProvider(
 			( select ) => select( editorStore ).getRenderingMode(),
 			[]
 		);
-		const shouldRenderTemplate = !! template && mode !== 'post-only';
+		const shouldRenderTemplate =
+			!! template && mode !== 'post-only' && mode !== 'pattern-only';
```
Comment (talldan) [inline packages/editor/src/components/provider/index.js]: Agree with [Riad's point](https://github.com/WordPress/gutenberg/pull/56827#issuecomment-1856529519) that this kind of thing isn't really scalable.

It seems like `post-only` mode is already mostly appropriate for patterns, but needs a few adjustments for the desired user experience.

For the back button, Riad suggests a rudimentary stack of post types as a history, which sounds reasonable.

Some other aspects, like the dark grey surround around the content can be derived from the post type.

File: packages/edit-post/src/components/visual-editor/style.scss [hunk 6]
```diff
@@ -36,6 +36,10 @@
 	// as align-items: stretch is inherited by default.Additionally due to older browser's flex height
 	// interpretation, any percentage value is likely going to cause issues, such as metaboxes overlapping.
 	// See also https://www.w3.org/TR/CSS22/visudet.html#the-height-property.
+
+	&.is-pattern-mode {
+		padding: 48px 48px 0;
+	}
```
Comment (talldan) [inline packages/edit-post/src/components/visual-editor/style.scss]: It'd be good to use a more semantic name rather than `is-pattern-mode`.

Maybe `has-surround` or something. (though it feels like a bad name. I also thought `has-frame`, but it reads too much like 'iframe').

(edit: also instead of `48px` try to use the spacing variable from `_variables.scss`.)

File: packages/edit-post/src/components/sidebar/settings-header/index.js [hunk 7]
```diff
@@ -15,20 +15,27 @@ import { sidebars } from '../settings-sidebar';
...
+		[]
+	);
 
 	return (
 		<Tabs.TabList>
 			<Tabs.Tab tabId={ sidebars.document }>
-				{ isTemplateMode ? __( 'Template' ) : documentLabel }
+				{ isTemplateMode && __( 'Template' ) }
+				{ isPatternMode && __( 'Pattern' ) }
+				{ ! isTemplateMode && ! isPatternMode && documentLabel }
```
Comment (talldan) [inline packages/edit-post/src/components/sidebar/settings-header/index.js]: I think the issue here is that `postType` is still 'post' when editing a pattern, and I think we need to try ensuring it's `wp_block` in the editor store. If the post type is set to the correct thing, `documentLabel` will have the right value.

File: packages/edit-post/src/components/header/mode-switcher/index.js [hunk 8]
```diff
@@ -46,13 +47,15 @@ function ModeSwitcher() {
...
+			isEditingPattern:
+				select( editorStore ).getRenderingMode() === 'pattern-only',
 			mode: select( editPostStore ).getEditorMode(),
 		} ),
 		[]
 	);
 	const { switchEditorMode } = useDispatch( editPostStore );
 
-	if ( isEditingTemplate ) {
+	if ( isEditingTemplate || isEditingPattern ) {
```
Comment (talldan) [inline packages/edit-post/src/components/header/mode-switcher/index.js]: I think it's ok to allow the pattern to be edited in text mode, so can probably drop this addition.

File: packages/edit-post/src/components/header/index.js [hunk 9]
```diff
@@ -136,35 +138,40 @@ function Header( {
...
 							hasBlockSelected &&
 							! isBlockToolsCollapsed &&
 							hasFixedToolbar &&
 							isLargeViewport,
 					} ) }
 				>
-					{ isEditingTemplate && <DocumentBar /> }
+					{ ( isEditingTemplate || isEditingPattern ) && (
+						<DocumentBar />
+					) }
```
Comment (talldan) [inline packages/edit-post/src/components/header/index.js]: I think this is one area where `post-only` mode won't work for patterns. I guess it should be dependent on post type for now.

Not sure if we want to keep some config like this to drive all these aspects of the editor:
```js
const DEFAULT_EDITOR_INTERFACE = {
  hasDocumentBar: false,
  hasSurround: false,
};
const POST_TYPE_EDITOR_INTERFACE = {
  wp_block: {
    hasDocumentBar: true,
    hasSurround: true,
  }
};
```

File: packages/block-library/src/block/edit.js [hunk 10]
```diff
@@ -132,11 +133,36 @@ function getOverridesFromBlocks( blocks, defaultValues ) {
...
+	const currentArgs = getQueryArgs( window.location.href );
+	const currentUrlWithoutArgs = removeQueryArgs(
+		window.location.href,
+		...Object.keys( currentArgs )
+	);
+	const newUrl = addQueryArgs( currentUrlWithoutArgs, {
+		...currentArgs,
+		patternId,
+	} );
+	window.history.pushState( null, '', newUrl );
```
Comment (talldan) [inline packages/block-library/src/block/edit.js]: I think you could move all of this into the `editInPatternOnlyMode` function, that way you don't need the `editSourcePattern` function.

By doing that the editor is responsible for its own routing rather than the block.

File: packages/block-editor/src/components/block-inspector/index.js [hunk 11]
```diff
@@ -92,7 +92,9 @@ const BlockInspector = ( { showNoBlockSelectedMessage = true } ) => {
 			blockType: _blockType,
 			topLevelLockedBlock:
 				__unstableGetContentLockingParent( _selectedBlockClientId ) ||
-				( getTemplateLock( _selectedBlockClientId ) === 'contentOnly'
+				( getTemplateLock( _selectedBlockClientId ) === 'contentOnly' ||
+				( _selectedBlockName === 'core/block' &&
+					window.__experimentalPatternPartialSyncing )
```
Comment (talldan) [inline packages/block-editor/src/components/block-inspector/index.js:97]: I think we should make sure we consider reviewing this and the similar code (in `use-in-between-inserter.js` and `selectors.js` code down the road, as there's a lot of hard coding of values to bend things into a working state. Feels like there should be a better way.

The gist of the problem seems to be that none of the block editing modes seem to be suitable for patterns.

**Comment by glendaviesnz** [comment]
FYI - this is still a bit of a PoC - we need to do some more work on naming, working out where is best to update post id and type from url and how best to indicate to use header doc bar and add padding around edited document - these things are all working, but may not be set up in the optimum way yet.

File: packages/edit-post/src/components/header/index.js [hunk 12]
```diff
@@ -87,6 +90,9 @@ function Header( {
 		};
 	}, [] );
```
Comment (glendaviesnz) [inline packages/edit-post/src/components/header/index.js]: `POST_TYPE_EDITOR_INTERFACE` is not structured quite right as we don't want the header bar and surround in all cases, currently only if linking from within a full post, but not if linking from pattern list in wp_admin. maybe it needs to be something like:
```
export const POST_TYPE_EDITOR_INTERFACE = {
    wp_block {	
         focusedMode: {
		hasDocumentBar: true,
		hasBackLink: true,
		hasSurround: true,
	},
    }
};
```
the check can then be `POST_TYPE_EDITOR_INTERFAC[postType][ editMode ]?.hasDocumentBar. That is pretty messy though, we probably need to abstract this to a method or selector if adding that extra layer.

**Comment by SaxonF** [comment]
> Since we're reusing much of the template vs content editing experience right now, I'm curious how we're going to handle folks clicking on the parts of a pattern that can't be edited. Will we show a notice for folks to explain how they can edit that section

I added an idea [here](https://github.com/WordPress/gutenberg/issues/55025) but will add here as well for visibility.

Here's a concept that highlights editable parts of a synced pattern or template on hover. You can also see when editing a page we can highlight and select the surrounding template much like a pattern.

https://github.com/WordPress/gutenberg/assets/1072756/8aac2ba3-8225-4226-ad92-289712c5db72


https://github.com/WordPress/gutenberg/assets/1072756/e69d8c43-02b6-4855-95ed-e1c282f305c5

File: packages/editor/src/hooks/pattern-partial-syncing.js [hunk 13]
```diff
@@ -64,10 +65,45 @@ const withPartialSyncingControls = createHigherOrderComponent(
...
+	( BlockEdit ) => ( props ) => {
+		if ( props.name !== 'core/block' ) {
+			return <BlockEdit { ...props } />;
+		}
+
+		const { onClick } = useLink( {
+			postId: props.attributes?.ref,
+			postType: 'wp_block',
+			canvas: 'edit',
+			editMode: 'focused',
```
Comment (talldan) [inline packages/editor/src/hooks/pattern-partial-syncing.js]: Isn't this just adding another render mode, but instead of adding it the store it's a query param?

File: packages/edit-post/src/components/header/index.js (hunk 12 above)
Comment (talldan) [reply packages/edit-post/src/components/header/index.js]: I wasn't aware of that.

An alternative is that it works on the basis of whether there's any router history and then get rid of the `POST_TYPE_EDITOR_INTERFACE` constant. 

So:
- Editing post and no history - `documentBar: false`, `hasBackLink: false`, `hasSurround: false`
- Editing pattern and no history - `documentBar: false`, `hasBackLink: false`, `hasSurround: false`
- Editing anything else when there's history - `documentBar: true`, `hasBackLink: true`, `hasSurround: true`

It certainly seems like that's how the back link should work, though I'm not as certain about what the rules are supposed to be for the other parts of the UI.

Had a quick look at `@wordpress/router` and it seems like it should be possible, but it isn't something that the history package supports out of the box. I think `history.listen` would need to be exposed and then the post editor can keep track of the entity history.

File: packages/editor/src/components/routes/link.js
Comment (talldan) [inline packages/editor/src/components/routes/link.js:1]: If this file is the same as the component in the `edit-site` package, the best thing would be to replace usage in the site editor with this version.

**Review by talldan — COMMENTED** [review]
Feels like quite a big step to add the `router` package in this PR. 😅 

It seems to be working pretty well for patterns, but if you go to edit the post template the back button doesn't quite work and that feels like an inconsistency.

Maybe the right first step would be a separate PR to make the router work for templates. Templates also seem a bit unusual in the post editor in that the post type/id isn't changed to a `wp_template` and the relevant slug, though I imagine it's like this because there was previously no history, so the template has to be derived from the post id.

Or alternatively not introduce the `@wordpress/router` and use an array that records a history in a stack, as Riad suggested.

File: packages/editor/src/hooks/pattern-partial-syncing.js (hunk 13 above)
Comment (glendaviesnz) [reply packages/editor/src/hooks/pattern-partial-syncing.js]: Yeh, but it is not tied to a particular post type so doesn't need a new mode for each post type which was the issue with the previous approach of having `template-mode`, `pattern-mode`, etc, however, it was really just added there in this initial step of this new approach in order to differentiate between the edit original link from post editor and  editing a pattern from pattern list from wp-admin, but your suggestion below of using router history might be a better alternative so we can probably get rid of it.

File: packages/editor/src/components/routes/link.js
Comment (glendaviesnz) [reply packages/editor/src/components/routes/link.js:1]: yeh, we will want to do that for sure if we proceed with this approach.

File: packages/edit-post/src/components/header/index.js (hunk 12 above)
Comment (glendaviesnz) [reply packages/edit-post/src/components/header/index.js]: Yeh, that could be worth exploring, will have a play around with that idea.

File: packages/editor/src/components/document-bar/index.js (hunk 4 above)
Comment (kevin940726) [reply packages/editor/src/components/document-bar/index.js]: Nice catch! I opened a PR here: https://github.com/WordPress/gutenberg/pull/57148.

**Comment by glendaviesnz** [comment]
> Feels like quite a big step to add the router package in this PR. 😅

Yeh, I was hoping to be able to just use `useLocation` and `useHistory` from the router package, but they don't work unless you also have the `RouterProvider` to provide the routing context. We could just manipulate the urls manually, but with the two editors merging over time it seems to make sense to use the same methods for this sort of url manipulation.

> It seems to be working pretty well for patterns, but if you go to edit the post template the back button doesn't quite work and that feels like an inconsistency.

The back button is broken for templates already on trunk, so I guess it depends what our priorities are, introducing the router and getting templates working properly or getting the pattern editing working, and then circle back with a separate PR to migrate templates to the routing approach. I would go with getting patterns working and then migrate templates, but let me know if you think we should do the reverse.

We could also just create a small separate PR that does nothing but introduce the router package with a minimal amount of plumbing?

> Or alternatively not introduce the @wordpress/router and use an array that records a history in a stack, as Riad suggested.

With the two editors merging over time it doesn't seem to make sense to go with a completely different approach in the post editor to site editor. The router does not seem to add a lot of overhead at this point in terms of complexity, etc. but let me  know if you would prefer to ditch it for now and try managing all of this with that history array idea instead of url manipulation ( which will have the side effect  of the browser back button not working, that is why it is broken in templates currently I think  🤔  - unless we are keeping an array of history and manually manipulating the location/history with the raw browser history calls - which is sort of building a router 😃 )

**Comment by talldan** [comment]
> The back button is broken for templates already on trunk, so I guess it depends what our priorities are, introducing the router and getting templates working properly or getting the pattern editing working, and then circle back with a separate PR to migrate templates to the routing approach. I would go with getting patterns working and then migrate templates, but let me know if you think we should do the reverse.

Yep, I don't mind too much which order, but I think it's important that the inconsistency is solved one way or another.

> With the two editors merging over time it doesn't seem to make sense to go with a completely different approach in the post editor to site editor. The router does not seem to add a lot of overhead at this point in terms of complexity, etc. but let me know if you would prefer to ditch it for now and try managing all of this with that history array idea instead of url manipulation

I don't know too much about the editors merging or what strategy is being taken to do that, so not sure I can provide much insight about that. I'm happy for you to make a call, but maybe it's worth checking in with some other folks.

cc @youknowriad - just wondering if you have any feedback about the possibility of `@wordpress/router` being introduced in the post editor?

File: packages/edit-post/src/components/header/index.js (hunk 12 above)
Comment (youknowriad) [reply packages/edit-post/src/components/header/index.js]: Can't we just simplify, if there's history show the document bar, otherwise don't? Alternatively we could also do like the site editor (which we should probably align anyway) and always show the document bar.

File: packages/edit-post/src/components/sync-state-with-url/use-init-edited-entity-from-url.js [hunk 14]
```diff
@@ -0,0 +1,17 @@
...
+
+/**
+ * Internal dependencies
+ */
+import { unlock } from '../../lock-unlock';
+
+const { useLocation } = unlock( routerPrivateApis );
+
+export default function useInitEditedEntityFromURL() {
+	const { params = {} } = useLocation();
```
Comment (youknowriad) [inline packages/edit-post/src/components/sync-state-with-url/use-init-edited-entity-from-url.js]: Do we want to introduce the routing into the post editor? This is a new public API btw. (the URLs)
I initially though, we could just keep some internal state with a list of edited entities.

File: packages/edit-post/src/components/visual-editor/style.scss [hunk 15]
```diff
@@ -36,6 +36,9 @@
 	// as align-items: stretch is inherited by default.Additionally due to older browser's flex height
 	// interpretation, any percentage value is likely going to cause issues, such as metaboxes overlapping.
 	// See also https://www.w3.org/TR/CSS22/visudet.html#the-height-property.
+	&.has-surround {
```
Comment (youknowriad) [inline packages/edit-post/src/components/visual-editor/style.scss]: I think this should move the `EditorCanvas` component within the "editor" package and should be based on whether there's a "goBack" setting or something, that way we unify between post and site editors.

File: packages/editor/src/components/routes/link.js [hunk 16]
```diff
@@ -0,0 +1,55 @@
+/**
+ * WordPress dependencies
+ */
+import { addQueryArgs, getQueryArgs, removeQueryArgs } from '@wordpress/url';
+import { privateApis as routerPrivateApis } from '@wordpress/router';
```
Comment (youknowriad) [inline packages/editor/src/components/routes/link.js]: I don't think the "editor" package should depend on the "router". We should consider the "editor" package as a generic package to render `<Editor postType={ postType } postId={ postId } />` for instance we could have multiple on the same page. Based on that I think we need two optional settings to the "EditorProvider" to address the use-case of this PR:

 - onSelectPost( postType, postId ): a setting to call to navigate to a new postType/postId.
 - goBack (or something like that): to go back to the previous edited entity.

Worth noting that the document bar is not the only place where we'd want to use these settings, I can think of the "template panel" as another place to use onSelectPost for instance.

File: packages/editor/src/hooks/pattern-partial-syncing.js [hunk 17]
```diff
@@ -64,10 +65,45 @@ const withPartialSyncingControls = createHigherOrderComponent(
...
 	addFilter(
 		'editor.BlockEdit',
 		'core/editor/with-partial-syncing-controls',
 		withPartialSyncingControls
 	);
+	addFilter(
+		'editor.BlockEdit',
+		'core/editor/with-pattern-edit-original-mode',
+		withPatternOnlyRenderMode
+	);
```
Comment (youknowriad) [inline packages/editor/src/hooks/pattern-partial-syncing.js]: Aside: this pattern of adding filters to blocks like that, is probably something we should avoid as much as we can if possible. It's probably something that creates performance issues.

**Review by youknowriad — COMMENTED** [review]
Good start, can we also unify with the "template-only mode" as well? I thought we'd start with that one because it's already in place.

File: packages/edit-post/src/components/sync-state-with-url/use-init-edited-entity-from-url.js (hunk 14 above)
Comment (glendaviesnz) [reply packages/edit-post/src/components/sync-state-with-url/use-init-edited-entity-from-url.js]: I was trying to set it up in a way that the browser back button worked as expected. If just managing with internal state that won't be the case, unless I am missing something. Happy to set it up without routing if the browser back button experience is not an issue.

File: packages/edit-post/src/components/header/index.js (hunk 12 above)
Comment (glendaviesnz) [reply packages/edit-post/src/components/header/index.js]: @SaxonF do you have any views on always showing the document bar in the post editor?

**Comment by glendaviesnz** [comment]
> can we also unify with the "template-only mode" as well? I thought we'd start with that one because it's already in place.

We will definitely be looking for a solution that can cover off template mode as well, patterns was just a priority due to 6.5 deadlines.

File: packages/edit-post/src/editor.js [hunk 18]
```diff
@@ -26,8 +26,38 @@ import { unlock } from './lock-unlock';
...
+const postHistory = [];
+
+function Editor( {
+	postId: initialPostId,
+	postType: initialPostType,
+	settings,
+	initialEdits,
+	...props
+} ) {
 	const isLargeViewport = useViewportMatch( 'medium' );
```
Comment (glendaviesnz) [inline packages/edit-post/src/editor.js:37]: The following should probably be pulled out into a hook if we finalise on this approach as we will need to do the same in the site editor

File: packages/edit-post/src/editor.js [hunk 19]
```diff
@@ -26,8 +26,38 @@ import { unlock } from './lock-unlock';
...
+	const onSelectPost = useCallback(
+		( postId, postType ) => {
+			postHistory.unshift( currentPost );
+			setCurrentPost( { postId, postType } );
+		},
+		[ currentPost ]
+	);
+
+	const goBack = () => {
+		const previousPost = postHistory.shift();
```
Comment (talldan) [inline packages/edit-post/src/editor.js]: This is a nitpick, but it might be a small improvement to use `push` and `pop` to implement the stack instead of `unshift` and `shift`, as that would align more closely to how browser history works:
https://developer.mozilla.org/en-US/docs/Web/API/History/pushState

File: packages/edit-post/src/editor.js [hunk 20]
```diff
@@ -26,8 +26,38 @@ import { unlock } from './lock-unlock';
...
 	const isLargeViewport = useViewportMatch( 'medium' );
+	const [ currentPost, setCurrentPost ] = useState( {
+		postId: initialPostId,
+		postType: initialPostType,
+	} );
+
+	const onSelectPost = useCallback(
+		( postId, postType ) => {
+			postHistory.unshift( currentPost );
+			setCurrentPost( { postId, postType } );
```
Comment (talldan) [inline packages/edit-post/src/editor.js]: Similar to the other comment, to save on future refactoring efforts, it might be good to stick closer to the [browser history API](https://developer.mozilla.org/en-US/docs/Web/API/History_API).

One difference is the browser history usually includes the most recent item on the top of the stack.

So you'd start with the `postHistory` stack being `[ { postId: initialPostId, postType: initialPostType } ]`, then if you go to edit a pattern it becomes:
```js
[ 
  { postId: initialPostId, postType: initialPostType }, // first item in history
  { postId: patternPostId, postType: patternPostType }, // second item in history
]
```

I think the browser API does use a pointer system, which allows you to go back and forward without removing an item from the history, but it's probably not needed here as I don't think there's ever a way to go forward, so to get the current post could be `const [ ..., currentPost ] = postHistory` (meaning the `currentPost` state wouldn't be needed).

If I had to implement it, I'd probably use `useReducer`, but it's entirely up to you.

File: packages/edit-post/src/editor.js [hunk 21]
```diff
@@ -102,6 +141,9 @@ function Editor( { postId, postType, settings, initialEdits, ...props } ) {
 	const editorSettings = useMemo( () => {
 		const result = {
 			...settings,
+			onSelectPost,
+			goBack,
+			postHistory,
```
Comment (talldan) [inline packages/edit-post/src/editor.js]: Making this an editor setting means `onSelectPost`, `goBack` and `postHistory` become an API for developers, which I think becomes a problem. 

Two options that I can think of:
- It's implemented as a React Context Provider that's entirely private.
- It's store state with private actions/selectors.

File: packages/editor/src/components/document-bar/index.js [hunk 22]
```diff
@@ -48,39 +48,56 @@ const icons = {
...
+			getEditorSettings,
+		} = select( editorStore );
+		const _templateId = getCurrentTemplateId();
+		const back = getEditorSettings().goBack;
+		return {
+			isEditingTemplate:
+				!! _templateId && getRenderingMode() === 'template-only',
+			templateId: _templateId,
+			postType: getCurrentPostType(),
+			postId: getCurrentPostId(),
```
Comment (talldan) [inline packages/editor/src/components/document-bar/index.js:73]: I wonder if we need to consider how these APIs work with the history, as there's a lot of overlap. 🤔 

If we do, then that might mean needing to use a store for the history state.

File: packages/editor/src/hooks/pattern-partial-syncing.js [hunk 23]
```diff
@@ -64,10 +64,44 @@ const withPartialSyncingControls = createHigherOrderComponent(
...
+
+		const newProps = {
+			...props,
+			editOriginalPattern:
+				typeof onSelectPost === 'function' ? onSelectPost : undefined,
+		};
+
+		return <BlockEdit { ...newProps } />;
+	}
+);
```
Comment (talldan) [inline packages/editor/src/hooks/pattern-partial-syncing.js]: Both the site editor and post editor use the `editor` package, so I'm not sure that this code is in the right place given how it's post editor specific.

**Review by talldan — COMMENTED** [review]
This looks like it's getting a lot closer.

File: packages/editor/src/hooks/pattern-partial-syncing.js (hunk 23 above)
Comment (glendaviesnz) [reply packages/editor/src/hooks/pattern-partial-syncing.js]: We still want the `Edit original` button to appear in the site editor though don't we?

**Comment by glendaviesnz** [comment]
Thanks for all the feedback Dan. I have pulled things out into a hook, and have stopped passing `postHistory` into settings, and just leaving goBack as undefined if no history instead, so now just `onSelectPost` and `goBack` being passed into settings. Will take a look at the other changes you suggested in terms of tidying up the stack tomorrow.

File: packages/edit-post/src/editor.js (hunk 19 above)
Comment (glendaviesnz) [reply packages/edit-post/src/editor.js]: done.

File: packages/edit-post/src/hooks/use-post-history.js [hunk 24]
```diff
@@ -0,0 +1,37 @@
...
+	} );
+
+	const onSelectPost = useCallback(
+		( postId, postType ) => {
+			postHistory.current.unshift( currentPost );
+			setCurrentPost( { postId, postType } );
+		},
+		[ currentPost ]
+	);
+
```
Comment (glendaviesnz) [inline packages/edit-post/src/hooks/use-post-history.js:20]: this can be simplified greatly, will sort out tomorrow

File: packages/edit-post/src/editor.js (hunk 21 above)
Comment (talldan) [reply packages/edit-post/src/editor.js]: Ah, I missed that it was suggested here - https://github.com/WordPress/gutenberg/pull/57036#discussion_r1429758624.

Happy to defer to Riad's suggestion.

Comment (youknowriad) [reply packages/edit-post/src/editor.js]: In my mind `postHistory` is not needed, I'm curious how it's used?

File: packages/editor/src/components/document-bar/index.js [hunk 25]
```diff
@@ -48,40 +48,46 @@ const icons = {
...
 			};
-		},
-		[]
-	);
+		}, [] );
 	const { getEditorSettings } = useSelect( editorStore );
 	const { setRenderingMode } = useDispatch( editorStore );
 
+	const handleOnBack = () => {
+		if ( isEditingTemplate ) {
```
Comment (youknowriad) [inline packages/editor/src/components/document-bar/index.js:82]: I was talking about "template-only" mode because in my mind, this would just be `goBack` like the other one. There would be no special case for templates.

File: packages/editor/src/components/document-bar/index.js [hunk 26]
```diff
@@ -48,40 +48,46 @@ const icons = {
...
+			setRenderingMode( getEditorSettings().defaultRenderingMode );
+			return;
+		}
+		if ( goBack ) {
+			goBack();
+			return;
+		}
+		window.history.back();
```
Comment (youknowriad) [inline packages/editor/src/components/document-bar/index.js]: We should remove this fallback IMO

File: packages/editor/src/components/document-bar/index.js [hunk 27]
```diff
@@ -48,40 +48,46 @@ const icons = {
...
+	};
+
 	return (
 		<BaseDocumentActions
```
Comment (youknowriad) [inline packages/editor/src/components/document-bar/index.js:87]: I think this component shouldn't be rendered if there's no "goBack" (and for now no "template mode" )

File: packages/editor/src/components/editor-canvas/index.js [hunk 28]
```diff
@@ -299,6 +301,7 @@ function EditorCanvas( {
 			styles={ styles }
 			height="100%"
 			iframeProps={ {
+				className: classnames( { 'has-history': hasHistory } ),
```
Comment (youknowriad) [inline packages/editor/src/components/editor-canvas/index.js]: Shouldn't we apply the same classname in template mode?

File: packages/editor/src/components/editor-canvas/style.scss [hunk 29]
```diff
@@ -0,0 +1,5 @@
+.edit-post-visual-editor {
```
Comment (youknowriad) [inline packages/editor/src/components/editor-canvas/style.scss]: This class is edit-post specific, we should not use it here

File: packages/editor/src/hooks/pattern-partial-syncing.js [hunk 30]
```diff
@@ -64,10 +64,44 @@ const withPartialSyncingControls = createHigherOrderComponent(
...
 
+/**
+ * Adds an editOriginalPattern prop which allows the block to switch between post and pattern
+ * editing modes.
+ *
+ * @param {Component} BlockEdit Original component.
+ *
+ * @return {Component} Wrapped component.
+ */
+const withPatternOnlyRenderMode = createHigherOrderComponent(
```
Comment (youknowriad) [inline packages/editor/src/hooks/pattern-partial-syncing.js]: What is this filter and why we need it?

File: packages/block-editor/src/components/block-inspector/index.js (hunk 11 above)
Comment (youknowriad) [reply packages/block-editor/src/components/block-inspector/index.js:97]: I'd love to understand the problem more here.

File: packages/edit-post/src/editor.js (hunk 21 above)
Comment (youknowriad) [reply packages/edit-post/src/editor.js]: If I'm not wrong, it's not used, we should remove it.

File: packages/editor/src/components/document-bar/index.js (hunk 22 above)
Comment (youknowriad) [reply packages/editor/src/components/document-bar/index.js:73]: I don't think we should but in the site editor for instance, calling `onSelectPost` should actually do nothing more than just `history.navigate` and potentially, it should store the entity somewhere to be able to do `goBack` (actually not even sure it should store the entity as it can check from the "history" object maybe).

In other words, it's the "history" that will control these props as they get passed to `EditorProvider`. In the post editor it might not be needed unless we decide to add "url changes" there.

File: packages/editor/src/components/document-bar/index.js (hunk 25 above)
Comment (glendaviesnz) [reply packages/editor/src/components/document-bar/index.js:82]: We were planning to follow up with an additional PR straight after this one to bring the template mode into line with this new approach otherwise this PR gets a bit polluted with changes not related to the pattern implementation.

File: packages/editor/src/components/editor-canvas/style.scss (hunk 29 above)
Comment (glendaviesnz) [reply packages/editor/src/components/editor-canvas/style.scss]: 🤦

File: packages/edit-post/src/editor.js (hunk 21 above)
Comment (glendaviesnz) [reply packages/edit-post/src/editor.js]: That is an outdated snippet - it was removed earlier.

File: packages/editor/src/hooks/pattern-partial-syncing.js (hunk 30 above)
Comment (glendaviesnz) [reply packages/editor/src/hooks/pattern-partial-syncing.js]: This was just a temporary way of getting the `editor` specific rendering mode dispatcher into the `core/block` block without making `editor` a dependency of `block-library` for the purposes of quickly trying a PoC. Now we are moving to using the `onSelectPost` setting instead we will be deleting this temporary filter.

File: packages/editor/src/components/editor-canvas/style.scss (hunk 29 above)
Comment (glendaviesnz) [reply packages/editor/src/components/editor-canvas/style.scss]: Updated.

File: packages/editor/src/components/editor-canvas/index.js (hunk 28 above)
Comment (glendaviesnz) [reply packages/editor/src/components/editor-canvas/index.js]: As mentioned above we will have a follow-up PR that will handle all of the template mode migration to this new approach.

**Comment by paaljoachim** [comment]
Touching upon @SaxonF comment here:
https://github.com/WordPress/gutenberg/pull/57036#issuecomment-1859520585

Some brainstorming...

I remember earlier we had a click through. Initial click selected the Reusable block. Telling the user that now we are inside the special kind of block. The toolbar would change to reflect the selection. What I miss with the video I see is that the first click does not make it obvious that one is now inside a special kind of "Group" block. I believe at the time there was also a kind of overlay color (I might be remembering wrong). 

Clicking a pattern containing locked blocks need as you Saxon suggested show the editable blocks within the pattern. That might work as you show it. Showing a kind of border and pencil with the editable blocks. What I miss is having a border around the full pattern showing the Pattern group. Perhaps even having a lock icon instead of the pencil icon on the blocks that are locked. This would show editable and locked blocks inside the pattern making it clear which blocks are inside the pattern and what can be done with these.

File: packages/editor/src/components/editor-canvas/style.scss [hunk 31]
```diff
@@ -0,0 +1,5 @@
+.block-editor__container {
```
Comment (youknowriad) [inline packages/editor/src/components/editor-canvas/style.scss]: I'm not certain where this class come from, can't we just use a dedicated class that we pass in `editor-canvas` instead like `editor-canvas__iframe` for something?

File: packages/edit-site/src/components/block-editor/back-button.js [hunk 32]
```diff
@@ -22,11 +23,12 @@ function BackButton() {
 	const history = useHistory();
 	const isTemplatePart = location.params.postType === TEMPLATE_PART_POST_TYPE;
 	const isNavigationMenu = location.params.postType === NAVIGATION_POST_TYPE;
+	const isPattern = location.params.postType === PATTERN_TYPES.user;
 	const previousTemplateId = location.state?.fromTemplateId;
```
Comment (glendaviesnz) [inline packages/edit-site/src/components/block-editor/back-button.js:28]: it would be nice to have some sort of `hasHistory` check in the site editor to decided if back button shown instead of these multiplying post type checks but I think we should do that as a follow-up PR.

File: packages/block-editor/src/components/block-inspector/index.js (hunk 11 above)
Comment (talldan) [reply packages/block-editor/src/components/block-inspector/index.js:97]: At the moment the PR uses `useBlockEditingMode` to prevent editing inside the pattern block, but it doesn't support exactly what's needed for the pattern block. 'disabled' locks down too much. 'contentOnly' also isn't right. At the moment the PR sets the inner blocks of the pattern to 'disabled' or 'contentOnly' as needed, but that still results in things like the sibling inserter showing.

This part still needs some investigation.

File: packages/block-library/src/block/edit.js [hunk 33]
```diff
@@ -153,7 +163,42 @@ export default function ReusableBlockEdit( {
...
+				postId: ref,
+				postType: 'wp_block',
+				canvas: 'edit',
+		  } )
+		: {};
+
+	useEffect(
+		() => setBlockEditMode( setBlockEditingMode, innerBlocks ),
+		[ innerBlocks, setBlockEditingMode ]
+	);
```
Comment (talldan) [inline packages/block-library/src/block/edit.js:204]: May need to consider using `registry.batch` here to batch all the action dispatches.

File: packages/editor/src/components/document-bar/index.js [hunk 34]
```diff
@@ -48,40 +48,44 @@ const icons = {
...
+		useSelect( ( select ) => {
 			const {
 				getRenderingMode,
 				getCurrentTemplateId,
 				getCurrentPostId,
 				getCurrentPostType,
+				getEditorSettings,
 			} = select( editorStore );
 			const _templateId = getCurrentTemplateId();
+			const back = getEditorSettings().goBack;
```
Comment (talldan) [inline packages/editor/src/components/document-bar/index.js]: I notice there's also a `useSelect` call for `getEditorSettings` on line 71, so maybe there's some deduplication that can happen.

File: packages/editor/src/components/editor-canvas/index.js [hunk 35]
```diff
@@ -135,6 +136,7 @@ function EditorCanvas( {
 			wrapperBlockName: _wrapperBlockName,
 			wrapperUniqueId: getCurrentPostId(),
 			deviceType: getDeviceType(),
+			hasHistory: !! getEditorSettings().goBack,
```
Comment (talldan) [inline packages/editor/src/components/editor-canvas/index.js]: There's already an `editorSettings` variable on line 114, so it could be changed to:
```suggestion
			hasHistory: !! editorSettings.goBack,
```

A similar improvement could happen on line 129.

**Review by kevin940726 — COMMENTED** [review]
I started testing it and discovered some issues. I'll do more testing later. Good work so far! 👍

1. After editing the source pattern and saving it once, the users can no longer edit it.

https://github.com/WordPress/gutenberg/assets/7753001/7caca9d7-a3a0-4757-acaf-0c5d53bd8c91

2. Reloading the page inside the source pattern editor goes to the `wp_block` post editor. I guess whether we should stay in the original post is TBD, but I'd expect us to at least go to the site editor if landing in the pattern editor is expected.

https://github.com/WordPress/gutenberg/assets/7753001/d940c910-2884-47db-999e-4097a06a84fc

3. You can delete a synced paragraph in the post editor but at most we should only hide it. I think this might be out of scope of this PR though, just something we should note for.

File: packages/edit-site/src/components/block-editor/use-site-editor-settings.js [hunk 36]
```diff
@@ -157,7 +158,7 @@ export function useSpecificEditorSettings() {
 			hasFixedToolbar,
 			keepCaretInsideBlock,
 			defaultRenderingMode,
-
+			onSelectPost: useLink,
```
Comment (talldan) [inline packages/edit-site/src/components/block-editor/use-site-editor-settings.js]: I think there are a number of issues with this approach:
- `onSelectPost` doesn't sound like a react hook, which I think is a little dangerous. It means people might be encouraged to use it in a way that breaks the rule of hooks, or to use it outside of react components.
- The `onSelectPost` implementation in the post editor isn't a hook, so that inconsistency might be confusing to other devs.
- It adds a lot of overhead to the implementation in `usePostHistory`, which wasn't necessary before.
- The name `onSelectPost` is also misleading as it isn't used as an `onClick` handler, instead it's called to return an object with the `href` and the `onClick` handler.

So this needs some work. 🤔 

The way to solve this is going to be interesting. Some I can think of:

We could just pass a react hook in to the settings called something like `usePostLink`, and make the post editor work the same way. Not sure how @youknowriad feels about that 😄 .

Or you could do some refactoring in the site editor `useLink` hook so that the same can be achieved without using a hook, which doesn't seem to complicated.

In the long run, it seems it's not as simple as a single `onSelectPost` function if we need both the `href` and the `onClick` handler, it also probably needs to be renamed to `getPostLinkProps` or something.

**Review by talldan — COMMENTED** [review]
It looks very close! Unfortunately I think the way `useLink` is used is a problem and needs some work.

File: packages/edit-site/src/components/block-editor/use-site-editor-settings.js (hunk 36 above)
Comment (glendaviesnz) [reply packages/edit-site/src/components/block-editor/use-site-editor-settings.js]: Thanks @talldan. Yeh, I had doubts about the approach also, but it at least proved it is possible to get things working in the site editor using the existing routing one way or another.

I have pushed [a very quick modification](https://github.com/WordPress/gutenberg/pull/57036/commits/ff77bebd69331d6d8643873f19c39943431c5af6) using your idea of switching to `getPostLinkProps` which makes more sense than `onSelect` with href added. I have also added a custom hook in the site editor to retrieve a version of `getPostLinkProps` that uses the routing.

I have only given it a quick test and it seems to work, but will need some tidy up/refining if we want to go this way instead - I thought it was worth pushing it anyway so we can see how it looks taking this approach approaches.

File: packages/editor/src/components/document-bar/index.js (hunk 34 above)
Comment (glendaviesnz) [reply packages/editor/src/components/document-bar/index.js]: Thanks. Fixed.

File: packages/editor/src/components/editor-canvas/index.js (hunk 35 above)
Comment (glendaviesnz) [reply packages/editor/src/components/editor-canvas/index.js]: Thanks. Fixed.

**Comment by glendaviesnz** [comment]
> Reloading the page inside the source pattern editor goes to the wp_block post editor. I guess whether we should stay in the original post is TBD, but I'd expect us to at least go to the site editor if landing in the pattern editor is expected.

@kevin940726 this is a problem with not using proper routing, but a history array in the component state, so if you refresh the browser that history is lost, so there is no way to know you were supposed to be in focused mode. Do you have any thoughts about how to get around this? We may just have to live with it for now if not adding routing to the post editor.

**Comment by glendaviesnz** [comment]
> After editing the source pattern and saving it once, the users can no longer edit it.

@kevin940726 For some reason when editing in the focused mode the connections metadata gets messed up, will try and work out why tomorrow.

File: packages/edit-site/src/components/block-editor/use-site-editor-settings.js (hunk 36 above)
Comment (youknowriad) [reply packages/edit-site/src/components/block-editor/use-site-editor-settings.js]: I'm not sure that I'm a big fan of passing a setting as a hook. I wonder why not just pass a regular callback that does "history.goTo" or something like that?

Comment (glendaviesnz) [reply packages/edit-site/src/components/block-editor/use-site-editor-settings.js]: Yeh, I refactored it with [this commit](https://github.com/WordPress/gutenberg/pull/57036/commits/ff77bebd69331d6d8643873f19c39943431c5af6) to pass a callback in both the site and post editor. In the site editor it is using the existing routing history mechanism and in the post editor the history array we implemented yesterday. As mentioned above this was a very quick last-minute refactor at end of day, it needs some refining - I will take a better look at the implementation details tomorrow.

Comment (glendaviesnz) [reply packages/edit-site/src/components/block-editor/use-site-editor-settings.js]: FYI - the reason for adding the `href` as well as the `onClick` was to match the `Edit` buttons in the post editor to those in the site editor which allow for a right click and open in new tab due to the presence of the href on the button, which we didn't have with the previous simple onSelectPost handler.

File: packages/block-library/src/block/edit.js [hunk 37]
```diff
@@ -272,17 +306,15 @@ export default function ReusableBlockEdit( {
...
-						onChange={ setTitle }
-						__nextHasNoMarginBottom
-						__next40pxDefaultSize
-					/>
-				</PanelBody>
-			</InspectorControls>
+			{ userCanEdit && editOriginalProps && (
+				<BlockControls>
+					<ToolbarGroup>
+						<ToolbarButton { ...editOriginalProps }>
```
Comment (kevin940726) [inline packages/block-library/src/block/edit.js]: I wonder if it makes sense to just register this on each editor. For `edit-post` it's a button that will toggle the focus mode, for `edit-site` it's a link that calls `router.navigate()`. This way we avoid introducing the `getPostLinkProps` setting, it's not really related to the `block-library` package anyway. I still have mixed feelings about this though 😅 .

**Comment by kevin940726** [comment]
> this is a problem with not using proper routing, but a history array in the component state, so if you refresh the browser that history is lost, so there is no way to know you were supposed to be in focused mode. Do you have any thoughts about how to get around this? We may just have to live with it for now if not adding routing to the post editor.

I think the main issue here is that the URL is updated to the pattern's URL when entering the focus mode. Maybe we need an `isFocusMode` flag and bail out the updates in `<BrowserURL>` so that it won't update the URL for now. 🤔

File: packages/block-library/src/block/edit.js (hunk 37 above)
Comment (glendaviesnz) [reply packages/block-library/src/block/edit.js]: The [plan is to get rid of focus mode](https://github.com/WordPress/gutenberg/pull/56827#issuecomment-1856529519). The preference is to move to this approach of passing the new post id and post type to the entity provider.

**Comment by glendaviesnz** [comment]
> After editing the source pattern and saving it once, the users can no longer edit it.

@kevin940726 I think this should be [fixed now](https://github.com/WordPress/gutenberg/pull/57036/commits/779bb38c33dae6b1136b879e6b5d04a7a2922d8b) if you want to retest. The block editing modes were staying set when redirecting to the edit original page - not sure why this only happened after saving the pattern 🤔

**Comment by glendaviesnz** [comment]
>  Maybe we need an isFocusMode flag and bail out the updates in <BrowserURL> so that it won't update the URL for now. 

[That seems to work](https://github.com/WordPress/gutenberg/pull/57036/commits/7378942648ae3ecd7787d5e6ac45d4b57ef95706) - see what you think of the flow now when reloading @kevin940726

**Review by kevin940726 — APPROVED** [review]
Works well for me! It behaves the same if the experimental flag is disabled too. Given that this feature is still behind an experimental flag, I think we can merge and iterate 👍.

File: packages/edit-post/src/components/browser-url/index.js [hunk 38]
```diff
@@ -56,7 +57,8 @@ export class BrowserURL extends Component {
 		if (
 			( postId !== prevProps.postId || postId !== historyId ) &&
```
Comment (talldan) [inline packages/edit-post/src/components/browser-url/index.js:58]: `historyId` seems to do something similar to `usePostHistory`, so there might be an opportunity to remove it from this component, replacing it with `usePostHistory`.

File: packages/edit-post/src/components/browser-url/index.js [hunk 39]
```diff
@@ -56,7 +57,8 @@ export class BrowserURL extends Component {
...
 			postStatus !== 'auto-draft' &&
-			postId
+			postId &&
+			! hasHistory
```
Comment (talldan) [inline packages/edit-post/src/components/browser-url/index.js:61]: This line feels mysterious, it'd be good to add a comment about why it was added.

File: packages/edit-post/src/hooks/use-post-history.js [hunk 40]
```diff
@@ -0,0 +1,73 @@
...
+				if ( historyState.length > 1 ) {
+					return historyState.slice( 0, -1 );
+				}
+			}
+			return historyState;
+		},
+		[ { postId: initialPostId, postType: initialPostType } ]
+	);
+
+	const getPostLinkProps = useCallback( ( params ) => {
```
Comment (talldan) [inline packages/edit-post/src/hooks/use-post-history.js:38]: Minor - the separation of concerns here could match what the site editor has, where `history` is one thing, and then `getPostLinkProps` is a seperate function, but they get plumbed together.

On the other hand, `usePostHistory` is already quite specific and not really a generic history API, so it's probably fine as it is.

**Review by talldan — COMMENTED** [review]
This is working well for me, so I'll rebase and merge it.

I left a few comments, but they're all minor/optional, any further feedback seems like it could be addressed in a follow-up.

**Comment by talldan** [comment]
I noticed one thing that has changed since rebasing. The background area when editing the original pattern is now white instead of black:
Screenshot 2024-01-03 at 11 36 20 am

The way it was styled in this PR didn't take into account the bug that #57330 fixed. A follow-up can address styling the area around the editor canvas in a different way.

**Comment by talldan** [comment]
Rebased again now that e2e tests should be fixed in trunk (and there were new conflicts)

File: packages/editor/src/components/provider/use-block-editor-settings.js [hunk 41]
```diff
@@ -76,6 +76,7 @@ const BLOCK_EDITOR_SETTINGS = [
 	'__unstableIsBlockBasedTheme',
 	'__experimentalArchiveTitleTypeLabel',
 	'__experimentalArchiveTitleNameLabel',
+	'__experimentalGetPostLinkProps',
```
Comment (youknowriad) [inline packages/editor/src/components/provider/use-block-editor-settings.js:79]: Why is this "__experimental" ? It should be either "private" or stable.

Comment (talldan) [reply packages/editor/src/components/provider/use-block-editor-settings.js:79]: @youknowriad Do you know if there's prior art for making these private?

I saw in the block editor package there are some private settings, but not so much in the editor package.

Comment (youknowriad) [reply packages/editor/src/components/provider/use-block-editor-settings.js:79]: I'm not sure there's for the EditorProvider yet.

Comment (talldan) [reply packages/editor/src/components/provider/use-block-editor-settings.js:79]: I think there's something unusual going on here anyway, as it looks like `getPostLinkProps` is already passed in as an editor setting, so I'm not sure if `__experimentalGetPostLinkProps` is also needed.

Comment (talldan) [reply packages/editor/src/components/provider/use-block-editor-settings.js:79]: PR here - https://github.com/WordPress/gutenberg/pull/57535

(I'll continue looking into whether it can be made private)

**Comment by getdave** [comment]
@glendaviesnz Can I confirm whether you think any of the files here will need a backport to Core? Experiments page doesn't need to be brought over and the rest looks like JS changes only.

**Comment by glendaviesnz** [comment]
@getdave the experiments file is the only php change so no backporting for this one.

File: packages/block-library/src/block/edit.js (hunk 33 above)
Comment (ellatrix) [reply packages/block-library/src/block/edit.js:204]: I don't understand this code. Why are we recursively changing blocks on every change?
