### PR TITLE
Fix exception when editing non-public CPTs

### LINKED ISSUE #12129: Editing a reusable block results in "The editor has encountered an unexpected error"
**Describe the bug**

Attempting to edit a reusable block fails and results in the error message `The editor has encountered an unexpected error`.

Full error message:

```
TypeError: Cannot read property 'split' of undefined
    at $n (https://fresh.test/branches/5.0/build/wp-includes/js/dist/editor.min.js?ver=5.0-beta5-20181120.201135:55:45572)
    at https://fresh.test/branches/5.0/build/wp-includes/js/dist/data.min.js?ver=5.0-beta5-20181120.201135:1:6353
    at https://fresh.test/branches/5.0/build/wp-includes/js/dist/edit-post.min.js?ver=5.0-beta5-20181120.201135:12:54732
    at n (https://fresh.test/branches/5.0/build/wp-includes/js/dist/data.min.js?ver=5.0-beta5-20181120.201135:1:13032)
    at new r (https://fresh.test/branches/5.0/build/wp-includes/js/dist/data.min.js?ver=5.0-beta5-20181120.201135:1:13283)
    at zf (https://fresh.test/branches/5.0/build/wp-includes/js/dist/vendor/react-dom.min.js?ver=5.0-beta5-20181120.201135:69:258)
    at Mf (https://fresh.test/branches/5.0/build/wp-includes/js/dist/vendor/react-dom.min.js?ver=5.0-beta5-20181120.201135:87:4)
    at ph (https://fresh.test/branches/5.0/build/wp-includes/js/dist/vendor/react-dom.min.js?ver=5.0-beta5-20181120.201135:98:474)
    at eg (https://fresh.test/branches/5.0/build/wp-includes/js/dist/vendor/react-dom.min.js?ver=5.0-beta5-20181120.201135:125:307)
    at fg (https://fresh.test/branches/5.0/build/wp-includes/js/dist/vendor/react-dom.min.js?ver=5.0-beta5-20181120.201135:126:168)
```

**To Reproduce**

1. Create a post
2. Create a reusable block within the post
3. Click `Manage All Reusable Blocks` in the tools and options menu
4. Click the `Edit` link next to your new reusable block
5. Observe the error message
6. Observe that clicking `Attempt recovery` has no effect and re-triggers the same error

**Expected behavior**

The block should be editable.

Note that with the Gutenberg plugin (version 4.4.0) on WordPress 4.9, this functionality works as expected.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 70

**Additional context**

* Gutenberg version: WordPress 5.0 beta 5

### PR DESCRIPTION
**Pull request by noisysocks**
Fixes #12129.

- Changes the posts API endpoint to only set `permalink_template` and `generated_slug` when the post is public and queryable. This matches the behaviour in Core.
- Changes the `getPermalink()` and `getPermalinkParts()` selectors to return null when there is no `permalink_template`. This fixes an exception on non-public CPTs caused by attempting to parse an undefined `permalink_template`.

#### Testing

1. Edit a non-public post using the block editor (e.g. a reusable block by going to _Manage All Reusable Blocks_ and then clicking _Edit_)
2. Publish a post and change its permalink using the sidebar
3. Publish a post and change its permalink using the permalink editor in the post title

### CODE REVIEW

File: lib/rest-api.php [hunk 1]
```diff
@@ -206,6 +206,11 @@ function gutenberg_add_permalink_template_to_posts( $response, $post, $request )
 		return $response;
 	}
 
+	$post_type_obj = get_post_type_object( $post->post_type );
+	if ( ! is_post_type_viewable( $post_type_obj ) || ! $post_type_obj->public ) {
+		return $response;
+	}
```
Comment (noisysocks) [inline lib/rest-api.php]: I pulled this logic [over from the 5.0 branch](https://github.com/WordPress/wordpress-develop/blob/edbb865da0410182a36695160abecb35885a4f4c/src/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L1602).

**Review by pento — APPROVED** [review]
🕺
