### PR TITLE
Inserter: Fix handling of child blocks

### LINKED ISSUE #23227: Block API: Can't restrict where a block may be inserted using `parent`
**Describe the bug**

Third parties are no longer able to make it so that a child block C can only be added to specific parent block P _while also allowing P to have non-C blocks added to it_.

**To reproduce**
<ol>
<li>
<p>Paste the following snippet into the DevTools console:</p>
<details>
<summary>Snippet</summary>

```js
( function() {
	const { registerBlockType } = wp.blocks;
	const { createElement: el } = wp.element;
	const { InnerBlocks } = wp.blockEditor;

	registerBlockType( 'acme/product', {
		title: 'Product',
		icon: 'carrot',
		category: 'common',

		edit() {
			return el( 'div', { className: 'product', style: { outline: '1px solid gray', padding: 5 } },
				// Only paragraphs, images, and Add to Cart blocks:
				el( InnerBlocks, { allowedBlocks: [ 'core/paragraph', 'core/image' ] } )
				// Everything and Add to Cart blocks:
				//el( InnerBlocks )
			);
		},

		save() {
			return el( 'div', { className: 'product', style: { outline: '1px solid gray', padding: 5 } },
				el( InnerBlocks.Content )
			);
		},
	} );

	registerBlockType( 'acme/buy-button', {
		title: 'Buy Button',
		icon: 'cart',
		category: 'common',

		// Only allow in products:
		parent: [ 'acme/product' ],

		edit() {
			return el(
				'button',
				{
					className: 'buy-button',
					style: { display: 'block', margin: '0 auto', padding: '10px 30px' },
				},
				'Buy Now'
			);
		},

		save() {
			return el(
				'button',
				{
					className: 'buy-button',
					style: { display: 'block', margin: '0 auto', padding: '10px 30px' },
				},
				'Buy Now'
			);
		},
	} );
} )();
```
</details>
</li>
<li>Add a <I>Product</I> block to the post.</li>
<li>Select the <I>Product</I> block and open the Inserter.</li>
</ol>

**Expected result**

The _Paragraph_, _Image_ and _Add to Cart_ blocks should appear in the Inserter.

**Actual result**

Only the _Add to Cart_ block appears in the Inserter.

**Additional context**

This functionality was introduced in https://github.com/WordPress/gutenberg/pull/6753.

### PR DESCRIPTION
**Pull request by noisysocks**
Fixes https://github.com/WordPress/gutenberg/issues/23227. Necessary for https://github.com/WordPress/gutenberg/pull/22656.

When a block C specifies `parent: [ P ]`, it means that C may only be added to P. It does NOT mean that P may *only* contain C. (Which is what `<InnerBlocks allowedBlocks={ [ C ] }>` means.)

This fixes the Inserter so that the correct blocks are shown when inserting into a block that is referenced by `parent`. It does so by leaning on `getInserterItems()` which already does the right thing.

**To test**
<ol>
<li>
<p>Paste the following snippet into the DevTools console:</p>
<details>
<summary>Snippet</summary>

```js
( function() {
	const { registerBlockType } = wp.blocks;
	const { createElement: el } = wp.element;
	const { InnerBlocks } = wp.blockEditor;

	registerBlockType( 'acme/product', {
		title: 'Product',
		icon: 'carrot',
		category: 'common',

		edit() {
			return el( 'div', { className: 'product', style: { outline: '1px solid gray', padding: 5 } },
				// Only paragraphs, images, and Add to Cart blocks:
				el( InnerBlocks, { allowedBlocks: [ 'core/paragraph', 'core/image' ] } )
				// Everything and Add to Cart blocks:
				//el( InnerBlocks )
			);
		},

		save() {
			return el( 'div', { className: 'product', style: { outline: '1px solid gray', padding: 5 } },
				el( InnerBlocks.Content )
			);
		},
	} );

	registerBlockType( 'acme/buy-button', {
		title: 'Buy Button',
		icon: 'cart',
		category: 'common',

		// Only allow in products:
		parent: [ 'acme/product' ],

		edit() {
			return el(
				'button',
				{
					className: 'buy-button',
					style: { display: 'block', margin: '0 auto', padding: '10px 30px' },
				},
				'Buy Now'
			);
		},

		save() {
			return el(
				'button',
				{
					className: 'buy-button',
					style: { display: 'block', margin: '0 auto', padding: '10px 30px' },
				},
				'Buy Now'
			);
		},
	} );
} )();
```
</details>
</li>
<li>Add a <I>Product</I> block to the post.</li>
<li>Select the <I>Product</I> block and open the Inserter.</li>
</ol>

The _Paragraph_, _Image_ and _Add to Cart_ blocks should appear in the Inserter.

### CODE REVIEW

File: packages/block-editor/src/components/inserter/block-list.js [hunk 1]
```diff
@@ -127,16 +114,19 @@ export function InserterBlockList( {
...
-				rootClientId={ rootClientId }
-				items={ childItems }
-				onSelect={ onSelectItem }
-				onHover={ onHover }
-			/>
+			{ hasChildItems && (
+				<ChildBlocks
+					rootClientId={ rootClientId }
+					// Pass along every block, as getInserterItems() will have
+					// already filtered out non-child blocks.
```
Comment (youknowriad) [inline packages/block-editor/src/components/inserter/block-list.js:124]: This comment makes me wonder what's special about `ChildBlocks` component. Why not just render `BlockTypesList` directly?

Comment (noisysocks) [reply packages/block-editor/src/components/inserter/block-list.js]: They receive different visual treatments.

Here's `ChildBlocks`:

Screen Shot 2020-06-18 at 10 35 22

Here's `InserterPanel`:

Screen Shot 2020-06-18 at 10 41 11

Perhaps we should unify the two? I'd rather address this as a separate issue, though.

In the meantime I agree that `ChildBlocks` should at least work the same as `InserterPanel` where the parent is responsible for passing through `BlockTypes`. I've changed that in 866b98e2f4.

File: packages/block-editor/src/components/inserter/block-list.js [hunk 2]
```diff
@@ -127,16 +114,20 @@ export function InserterBlockList( {
...
-			<ChildBlocks
-				rootClientId={ rootClientId }
-				items={ childItems }
-				onSelect={ onSelectItem }
-				onHover={ onHover }
-			/>
+			{ hasChildItems && (
+				<ChildBlocks rootClientId={ rootClientId }>
+					<BlockTypesList
+						// Pass along every block, as getInserterItems() will have
```
Comment (talldan) [inline packages/block-editor/src/components/inserter/block-list.js:123]: Nitpick, I found the mention of `getInserterItems` confusing at first because it's not used at all in this file. Maybe this should mention `useBlockTypesState` instead

**Review by talldan — APPROVED** [review]
Looks like a good solution.

I'm surprised this problem hasn't had more consequences, it'd be interesting to know the history and whether this was a recently introduced bug.

**Comment by noisysocks** [comment]
> I'm surprised this problem hasn't had more consequences, it'd be interesting to know the history and whether this was a recently introduced bug.

It was probably introduced in #20880, but I haven't confirmed that. I'd not be surprised if no third parties are using this functionality since it's not very well documented and we don't (yet) use it ourselves!

File: packages/block-editor/src/components/inserter/block-list.js (hunk 2 above)
Comment (noisysocks) [reply packages/block-editor/src/components/inserter/block-list.js]: 👍 0cad806

File: packages/block-editor/src/components/inserter/block-list.js (hunk 1 above)
Comment (youknowriad) [reply packages/block-editor/src/components/inserter/block-list.js]: Yes, seems like unnecessary complexity for now. I believe the visual difference is from the old design.
