### PR TITLE
Handle no variation case in the block transform menu

### LINKED ISSUE #41321: Inserting a Classic block with the slash inserter crashes the editor if the sidebar is open
### Description

When adding a Classic block in an empty post, the editor crashes.

### Step-by-step reproduction instructions

1. Create a new post
2. Open the sidebar
3. Add a Classic block through the slash inserter

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/27339341/170268220-2fa79da4-4e4d-4218-9fc7-ea898916bf22.mov

### Environment info

- WordPress 6.0, or WordPress < 6.0 + Gutenberg version >= 13.0
- Firefox & Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by youknowriad**
closes #41321 

## What?

If you insert the classic block while the sidebar is open, you'll see the editor break.

## Testing Instructions

1- Open the editor sidebar
2- Insert a classic block
3- The editor shouldn't break.

### CODE REVIEW

**Comment by youknowriad** [comment]
I'll see if I can add an e2e test that would catch this in the future.

File: packages/block-editor/src/components/block-variation-transforms/index.js [hunk 1]
```diff
@@ -121,6 +121,9 @@ function __experimentalBlockVariationTransforms( { blockClientId } ) {
 	// Check if each variation has a unique icon.
 	const hasUniqueIcons = useMemo( () => {
 		const variationIcons = new Set();
+		if ( ! variations ) {
+			return true;
+		}
```
Comment (Mamaduka) [inline packages/block-editor/src/components/block-variation-transforms/index.js:126]: Let's return `false` so that the default variation dropdown is displayed.

https://github.com/WordPress/gutenberg/blob/9c1c67bba4ba0dc7b241639719c567a364a8ea05/packages/block-editor/src/components/block-variation-transforms/index.js#L144

P.S. Super small nitpick. I would also make this check first thing in the callback 😅

**Review by Mamaduka — APPROVED** [review]
I'm still not able to reproduce the issue. But based on the code and the fact that `variations` can be undefined, this guard clause makes sense.

**Comment by youknowriad** [comment]
I'm failing to put the right conditions in the e2e test to make it fail :)

File: packages/block-editor/src/components/block-variation-transforms/index.js [hunk 2]
```diff
@@ -121,6 +121,9 @@ function __experimentalBlockVariationTransforms( { blockClientId } ) {
 	// Check if each variation has a unique icon.
 	const hasUniqueIcons = useMemo( () => {
 		const variationIcons = new Set();
+		if ( ! variations ) {
```
Comment (mcsf) [inline packages/block-editor/src/components/block-variation-transforms/index.js:124]: The expected behaviour when there are no variations is to fall back to `VariationsDropdown`, correct? In that case, we should make the logic more robust, because the patch currently only covers falsy values for `variations`, but not empty values like `variations: []`.

```suggestion
		if ( ! variations?.length ) {
```

Comment (Mamaduka) [reply packages/block-editor/src/components/block-variation-transforms/index.js:124]: @mcsf, if there's no variations component rendering is skipped.

https://github.com/WordPress/gutenberg/blob/38aeca81a6338a17d503e0b97926a33aaf4ce63d/packages/block-editor/src/components/block-variation-transforms/index.js#L144-L145

**Review by priethor — COMMENTED** [review]
The bug described in #41321 doesn't reproduce to me with this branch. 🙌

**Review by andrewserong — APPROVED** [review]
This change LGTM, but like some of the others, I wasn't able to reproduce the error.

It looks like a good defensive conditional to add, though, as I missed that in the `useSelect` call `variations` can be returned as a falsy value.

Thanks for putting up the fix!

**Comment by adamziel** [comment]
I just cherry-picked this PR to the wp/6.0 branch to get it included in the next release: 0eaf63d595
