### PR TITLE
Properly convert successive shortcodes

### LINKED ISSUE #7030: [2.9.2] Convert to Blocks not properly converting successive Shortcodes
**Describe the bug**
On a Classic block with multiple successive Shortcodes, choose the option "Convert to Blocks." Not all the Shortcodes will convert.

**To Reproduce**
1. create a new page/post
2. add this content in a Classic block
[shortcodetest]
[shortcodetest]
[shortcodetest]
3. choose "Convert to Blocks"
4. BUG: It will not create all the Shortcode blocks

Different combinations of text with successive Shortcodes result in different behavior, but in most/all scenarios, at least one of multiple successive Shortcodes does not convert.

**Expected behavior**
Any combination of Shortcodes, even in succession, should convert to Shortcode blocks.

### PR DESCRIPTION
**Pull request by danielbachhuber**
## Description

Removes `memize()` call around `wp.shortcode.regexp()` to avoid buggy behavior when converting successive shortcodes.

Fixes #7030

## How has this been tested?

1. Add the following code to a Classic Editor post:

```
[foo one]

[foo two]

[foo three]
```

2. Open the post in Gutenberg.
3. Hit 'Convert to Blocks' and see that all shortcode instances have been converted to blocks.

multipleshortcodes

## Types of changes

Bug fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by aduth** [comment]
Chatted about this with @danielbachhuber , seems to stem from this related Core issue:

https://core.trac.wordpress.org/ticket/35545

Which is that we're using shortcode regular expressions as stateful (`RegExp#exec`) while also memoizing their creation, thus causing unpredictable results like the one surfaced here.

There's not much to go by so far as the context for memoizing in [the initial introduction of the `shortcodes` utility](https://core.trac.wordpress.org/ticket/21996). Typically it'd be for performance, though in this case we're simply concatenating a string into a new regular expression, so doubtful we're really saving much (the overhead of memoization is likely more costly). Given that we _are_ using the regular expressions as stateful, it may have been intentional to return a cached copy, but again the context is unclear.

My intuition is: Remove `memize` wrapper from `wp.shortcode.regexp`. This fixes #7030.

cc @iseulde @azaozz @koop

File: packages/shortcode/src/index.js [hunk 1]
```diff
@@ -143,9 +143,9 @@ export function string( options ) {
  *
  * @return {RegExp} Shortcode RegExp.
  */
-export const regexp = memize( ( tag ) => {
+export const regexp = ( tag ) => {
```
Comment (aduth) [inline packages/shortcode/src/index.js]: Minor: Simply for consistency, we could format this as the other plain functions in this file now:

```js
export function regexp( tag ) {
	 // ...
}
```

**Review by aduth — APPROVED** [review]
Looks good 👍

File: packages/shortcode/src/index.js (hunk 1 above)
Comment (danielbachhuber) [reply packages/shortcode/src/index.js]: > Simply for consistency, we could format this as the other plain functions in this file now:

Good point, 1bf5ba0b7

File: packages/shortcode/src/index.js [hunk 2]
```diff
@@ -143,9 +143,9 @@ export function string( options ) {
  *
  * @return {RegExp} Shortcode RegExp.
  */
-export const regexp = memize( ( tag ) => {
+export function regexp( tag ) {
 	return new RegExp( '\\[(\\[?)(' + tag + ')(?![\\w-])([^\\]\\/]*(?:\\/(?!\\])[^\\]\\/]*)*?)(?:(\\/)\\]|\\](?:([^\\[]*(?:\\[(?!\\/\\2\\])[^\\[]*)*)(\\[\\/\\2\\]))?)(\\]?)', 'g' );
-} );
+};
```
Comment (aduth) [inline packages/shortcode/src/index.js]: Semi-colon should be removed.

Comment (danielbachhuber) [reply packages/shortcode/src/index.js]: I wouldn't hate you if you just removed it yourself :) a712bf7eb439f3f398dcfb7e6f850222c1e7cb8c

**Comment by danielbachhuber** [comment]
Merging to incorporate into #7892. The failure is a codecov false positive.

**Comment by ktmn** [comment]
Does it also handle nesting?

```
[foo]
  [bar]
    [asd /]
  [/bar]
[/foo]
[foo]
  [bar][/bar]
[/foo]
```

Would it create 2 blocks?

**Comment by wpexplorer** [comment]
There seems to be issues still with converting blocks that are next to each other. I recorded a quick video to show you: https://a.cl.ly/jkuOjvOQ

There are many page builders out there that are shortcode based and basically everything added to the page are shortcodes and there isn't any space between them. So there is no way currently to convert these page builders to Blocks without having to first manually space out the shortcodes.

Thanks for all the great works you guys do over there!
