### PR TITLE
Data: Fix persistence initial state merging behavior

### LINKED ISSUE #9994: Persistence data plugin should take into account the object shape
The persistence data plugin helps to persist parts of the state in between sessions. When the data persisted is an object (e.g. the `preferences` key in the [editor](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/store/index.js#L26), [nux](https://github.com/WordPress/gutenberg/blob/c1c4c7ed80f0f29f60adb44f2fd0cb2f8660045d/packages/nux/src/store/index.js), or [edit-post](https://github.com/WordPress/gutenberg/blob/c1c4c7ed80f0f29f60adb44f2fd0cb2f8660045d/edit-post/store/index.js) stores) new keys added to that object will be invalidated once the persistence mechanism retrieves old data from cache.

### How to test

- Clean browser application cache, check out `master` branch, and run Gutenberg.
- Create a new branch and add some code that adds a new key to the `preferences` object whose value is `true` by default.
- Execute that new branch.

Expected result is that the `preferences` object will have the new truthy value but instead it has the state retrieved from local storage (which doesn't have the new added key).

### PR DESCRIPTION
**Pull request by aduth**
Fixes #9994 
Addresses https://github.com/WordPress/gutenberg/pull/13088#issuecomment-463276248

This pull request seeks to improve the behavior of the persistence plugin with respect to restoring a persisted value. Specifically, a persisted value would previously have been used verbatim, without any consideration of whether only a subset of store keys were persisted, and without any consideration of additional new keys which could have been added to the default value (used often in our case for adding additional preferences).

There are a few tangential improvements which have been included here:

- A couple corrections / improvements to the persistence plugin README
- Implement support for `initialState` in the `registerStore` interface, which simplifies the persistence plugin slightly.

**Testing instructions:**

Repeat steps to reproduce from #9994, verifying the observed issue has been resolved.

Ensure unit tests pass:

```
npm run test-unit packages/data
```

### CODE REVIEW

File: packages/data/src/plugins/persistence/index.js [hunk 1]
```diff
@@ -178,12 +164,25 @@ export default function( registry, pluginOptions ) {
...
+			let initialState = persistence.get()[ reducerKey ];
+			if ( initialState !== undefined ) {
+				// For object-like persistence, ensure that:
+				// - Other keys are left intact when persisting only a subset
+				//   of keys.
+				// - New keys in what would otherwise be provided as a default
+				//   state are deeply merged as a base for the persisted value.
+				if ( isPlainObject( initialState ) ) {
+					initialState = merge(
+						options.reducer( undefined, {
```
Comment (youknowriad) [inline packages/data/src/plugins/persistence/index.js]: I wonder if we should ensure that this also returns a plain object or undefined to avoid a corrupted persisted state from being loaded.

**Review by youknowriad — APPROVED** [review]

File: packages/data/src/plugins/persistence/index.js (hunk 1 above)
Comment (aduth) [reply packages/data/src/plugins/persistence/index.js]: What would be the expected behavior if we had a plain-object persisted state and a non-plain-object default initial state?

Comment (aduth) [reply packages/data/src/plugins/persistence/index.js]: In a1469ff302c696321bd36787beacc2cac84a89b2, I went with: If there's a mismatch of object-likeness between initial and persisted states, it defers always to the value produced by the original reducer.

But immediately upon pushing the change, I'm second-guessing myself, particularly for the following scenarios:

- Why defer to the default implementation for only the mismatch on this type, when if they were both non-objects we'd be fine to use the persisted value, regardless whether they're different types (array vs. string vs. number vs. etc)
- Are there cases where we'd want to allow some "empty" initial state, but still prefer the persisted value? Take, for example, the changed test case "should load a persisted value as initialState" in a1469ff302c696321bd36787beacc2cac84a89b2 where the reducer returns `null` as the default initial state

With consideration of these points, maybe it should be that the persisted value always  "wins", and merges with the default implementation value if and only if both it and the persisted value are objects.

The merging behavior in general feels a bit odd to me, though I understand the need for it in introducing new keys to something like a preferences object over time. The only other ideas that came to mind to support this were things more explicitly defined as "upgrading" behaviors†. There's some overhead in trying to manage this, which I think the auto-merging handles reasonably well on its own. 

† Things like: Handling the "persistence restore" action type from the reducer, checking the value and adding missing keys. Or defining a validation function which returns whether a persisted value should be considered valid for use.

Comment (youknowriad) [reply packages/data/src/plugins/persistence/index.js]: Yes, I also was thinking to defer to the reducer value and consider the persisted one as broken but on a second though reducers can return different shapes so I guess it's fine to override the state entirely with the persisted value.

Comment (aduth) [reply packages/data/src/plugins/persistence/index.js]: > Yes, I also was thinking to defer to the reducer value and consider the persisted one as broken but on a second though reducers can return different shapes so I guess it's fine to override the state entirely with the persisted value.

And should a need arise that we need to explicitly forget some persisted state, I think at that point we could consider introducing one of the other options I mentioned in my previous comment about validating or overriding the persisted input.
