### PR TITLE
Fix button block focus trap after a URL has been added

### LINKED ISSUE #34307: Button Block: Adding close button on the link control toggle or allow to close it using Esc key
### Description

While I was testing for the [FSE Program testing,](https://make.wordpress.org/test/2021/08/11/fse-program-testing-call-9-handling-highered-headers/)  I noticed there was no way to close the Button link toggle using Keyboard. 

### Step-by-step reproduction instructions

1. Create a button and enter text link
2. Open the link control toggle by using Ctrl+K or ⌘+K 
3. Once the toggle opens, search a post or page in the search bar
4. Select a post or page using down arrow key
5. Click Tab, and Enter to submit

Once submitted, the link control toggle stays open, and keyboard focus loops within the toggle. 

I tried using the Esc key and the arrow keys but could not figure out a way to close the toggle. 

### Screenshots, screen recording, code snippet

screenshot1

### Environment info

_No response_

### Pre-checks

- [x] I have searched the existing issues.
- [x] I have tested with all plugins deactivated except Gutenberg.

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #34307

The button block unfortunately has a focus trap. I've reworked it to be more like the link format. Unfortunately it's quite a sizeable change. It might be worth looking at refactoring the delicate way focus and visibility for LinkControl works into a React hook if that's possible, so that the implementation can be shared across the codebase.

This is a bad enough bug that I'm suggesting it should be included in WordPress 5.8.1.

## How has this been tested?
1. Create a button block and enter text link
2. Open the link control toggle by using Ctrl+K or ⌘+K
3. Once the toggle opens, search a post or page in the search bar
4. Select a post or page using down arrow key
5. Use Enter to submit
6. Press escape, focus should move back to the RichText. The link control remains visible so that users can see what the URL is.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-library/src/button/edit.js [hunk 1]
```diff
@@ -73,27 +73,42 @@ function URLPicker( {
...
+
+	const isLinkControlVisible = isSelected && ( isEditingURL || isURLSet );
+
+	const linkControl = isLinkControlVisible && (
 		<Popover
 			position="bottom center"
-			onClose={ () => setIsURLPickerOpen( false ) }
+			onClose={ () => {
+				setIsEditingURL( false );
+				richTextRef.current?.focus();
```
Comment (talldan) [inline packages/block-library/src/button/edit.js:108]: Ideally the original caret selection in the rich text would be restored rather than just a focus.

@ellatrix would you know the best way to do that?

**Review by draganescu — APPROVED** [review]
I tested this and it works as described. The code looks OK to me.

Unrelated problem, in Firefox pressing enter in the LinkControl opened the link in a tab.

**Comment by talldan** [comment]
Thanks—I think the link should open if it's focused. If it's not focused then that's a problem.

I'll go ahead and merge, happy to address any other feedback in a separate PR.
