### PR TITLE
Image: Fix resizer controls being hidden in Safari when switching between alignments

### LINKED ISSUE #24587: Image block resizer controls hidden in Safari after setting block alignment
With the recent image editing added in 5.5, there's an issue with Safari where the resizing option disappears after setting the alignment of an image until the page is refreshed.

I've tested on both Firefox and Chrome on Mac, and everything worked as expected.

### PR DESCRIPTION
**Pull request by andrewserong**
## Description

Fixes #24587 

In Safari, when switching the Image block between not aligned and an alignment, the component appears to re-render however the `img` element's `onload` callback is never fired, resulting in `naturalWidth` and `naturalHeight` being `undefined`. This means that the conditional [on this line](https://github.com/wordpress/gutenberg/blob/fffa06392bb584c1190948525a8767b78d9d9369/packages/block-library/src/image/image.js#L447) is reached, which means that the resizer isn't rendered.

The fix is to update `naturalWidth` and `naturalHeight` to pull from an image ref (so that the values are always available) and fall back to local component state when not available. This should 🤞 give us the best of both worlds — the real current value is available for Safari, and the fallback local component state value is available when cropping and editing images so that the saving state doesn't unexpectedly fail due to `undefined` natural width/height.

## How has this been tested?

1. In Safari, before applying this PR, insert an image block.
2. Switch the image block from no alignment to any alignment (e.g. Left alignment)
3. Observe that the resizer controls are no longer visible.
4. Apply this PR.
5. Repeat the above steps, and the resizer should always be available.

Test in other browsers, and also test cropping / image editing to be sure this doesn't introduce any regressions.

## Screenshots 

| Before | After |
| --- | --- |
| Kapture 2021-12-08 at 12 31 31 | Kapture 2021-12-08 at 12 29 20 |

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by andrewserong** [comment]
Update: this fix will need some adjustment, I just noticed it introduces a regression when dealing with external images when the external image is initially added to the block (the resizer is not visible).

We might wind up needing to retain the `onload` and use the imageRef as a fallback if available. I'll have a play around.

**Comment by andrewserong** [comment]
> I just noticed it introduces a regression when dealing with external images when the external image is initially added to the block (the resizer is not visible).

Another update: I _think_ I've fixed up the issue by preserving the local component state for the loaded image's natural width / height. We then use that as a fallback value, and prioritise the real `img` element's natural width/height when available, so that the fix for Safari still works.

**Comment by paaljoachim** [comment]
Hey @andrewserong 
I assume we also need the backtrack label here as well?
As the various fixes can easier be picked up to be added to the next beta.

**Comment by andrewserong** [comment]
> I assume we also need the backtrack label here as well?

@paaljoachim yes, we sure do! I've added the label. 👍

**Comment by glendaviesnz** [comment]
This tests well for me. An alternative, rather than using image onload method at all for this, would be to use `ref.current.complete`. A quick test of just adding the following to the existing image.js code seems to work for chrome and safari:

```javascript
	const imgRef = useRef();
	const imageOnload = () => {
		setNaturalSize(
			pick( imgRef.current, [ 'naturalWidth', 'naturalHeight' ] )
		);
	};

	useEffect( () => {
		if ( imgRef.current?.complete ) {
			imageOnload();
		}
	}, [ imgRef.current?.complete ] );

	let img = (
		// Disable reason: Image itself is not meant to be interactive, but
		// should direct focus to block.
		/* eslint-disable jsx-a11y/no-noninteractive-element-interactions, jsx-a11y/click-events-have-key-events */
		<>
			<img
				ref={ imgRef }
				src={ temporaryURL || url }
				alt={ defaultedAlt }
				onError={ () => onImageError() }
			/>
			{ temporaryURL && <Spinner /> }
		</>
		/* eslint-enable jsx-a11y/no-noninteractive-element-interactions, jsx-a11y/click-events-have-key-events */
	);

```

**Comment by glendaviesnz** [comment]
> A quick test of just adding the following to the existing image.js code seems to work for chrome and safari:

Actually it only works for existing images - `ref.current.complete` stays as false for new images for some reason.

**Comment by glendaviesnz** [comment]
> Actually it only works for existing images - `ref.current.complete` stays as false for new images for some reason.

My bad, the useEffect in above should be:

```javascript
	useEffect( () => {
		if ( imgRef.current?.complete ) {
			imageOnload();
		}
	}, [ imgRef.current?.complete ] );
```
have updated the full example above, and now seems to test well for me for existing images on page load and new images added.

**Comment by andrewserong** [comment]
Thanks for reviewing @glendaviesnz! Nice, I hadn't thought of using `imgRef?.current?.complete`. With the other approaches I tried for removing the `onload` handler, I wound up introducing bugs when using the cropping tool, or with external images that don't have CORS access. I'll give `imgRef?.current?.complete` a try! 🤞

File: packages/block-library/src/image/image.js [hunk 1]
```diff
@@ -179,6 +183,23 @@ export default function Image( {
...
+			naturalWidth:
+				imageRef.current?.naturalWidth ||
+				loadedNaturalWidth ||
+				undefined,
+			naturalHeight:
+				imageRef.current?.naturalHeight ||
+				loadedNaturalHeight ||
+				undefined,
+		};
+	}, [ loadedNaturalWidth, loadedNaturalHeight, imageRef.current ] );
```
Comment (Mamaduka) [inline packages/block-library/src/image/image.js]: I don't think we need to include `imageRef.current` in the dependency, at least based on `exhaustive-deps` 😄

Comment (andrewserong) [reply packages/block-library/src/image/image.js]: Thanks! I've removed the `useMemo` call, since I _think_ setting the `naturalWidth` and `naturalHeight` isn't quite worth it (because there's no real calculation going on). Let me know if you think it's better to leave it in, and I can add it back 🙂

Comment (andrewserong) [reply packages/block-library/src/image/image.js]: Update: I actually just added it back in, as removing it caused the resizer to intermittently fail to display in Safari. I've included `imageRef.current?.complete` in the dependency array — here I _think_ we want the `useMemo` to recalculate _slightly_ more frequently than with just the `loadedNaturalWidth` and `loadedNaturalHeight` values, but happy to remove it if it winds up not being needed.

I've found the behaviour in Safari to be a bit unreliable in testing, so working out what is and isn't needed has been a bit more challenging than usual 😅

**Comment by andrewserong** [comment]
Thanks for the suggestion to move away from the `onLoad` callback and to use `imageRef.current?.complete` in a `useEffect` instead, @glendaviesnz! Unfortunately doing that introduced a regression:

Kapture 2021-12-10 at 17 09 47

In this screengrab, I've added an external image, and once it's loaded, the resizer controls aren't available. I _think_ this is due to:

When inserting an image from an external URL, the `useEffect` [at this line](https://github.com/wordpress/gutenberg/blob/832d1c53e9bca886851050f26907a9a2e6c55339/packages/block-library/src/image/image.js#L169) attempts to async fetch the image so that it can be uploaded if need be. When the fetch fails for images without an appropriate CORS policy, the `imageRef.current?.complete` value is set to `false`, even though the image itself has loaded within the editor. This appears to be because fetching the asset resets `.complete`? And then the CORS failure means that it remains `false`. I found a tiny bit more context [in this MDN article](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/complete), but I wasn't _too_ sure of what I was observing. It looks like the cases where the value changes are a fair bit more broad than the `onLoad` handler.

To resolve that issue, adding an `onLoad` handler back in on the `img` element worked, however we then have multiple state updates and additional renders occurring from having both the `useEffect` and `onLoad` methods updating the natural width/height. So, if we need to have the `onLoad` handler there, I think I prefer the idea of reducing the number of state updates and avoiding the `useEffect`? The `imageRef.current?.complete` is still a good idea, though, so I've added it to the `useMemo` dependency array. I've also moved things around a little bit to reduce the diff.

Let me know if you can think of a better way to handle all this, though, or if I missed something in your approach. Very happy to try alternatives!

**Comment by glendaviesnz** [comment]
@andrewserong I didn't try the remote url scenario - I can't see a way around the CORs failure with my approach.  The current change of your's seems to work well in both cases - although I did have one failure still in Safari, so just trying to see if I can replicate that

**Comment by glendaviesnz** [comment]
I couldn't replicate the issue with Safari not showing the resize handles with this patch applied, so not sure what caused that.

The only other thought I had was that maybe this extra code isn't needed if the `allowResize` context is set to false by a parent gallery, but I can't see an easy way of making it dependent on `allowResize=true` as hooks can't be used conditionally - but it doesn't seem like it would cause any performance issues on a large gallery, what do you think?

**Comment by andrewserong** [comment]
Thanks for re-testing @glendaviesnz!

> The only other thought I had was that maybe this extra code isn't needed if the allowResize context is set to false by a parent gallery, but I can't see an easy way of making it dependent on allowResize=true as hooks can't be used conditionally - but it doesn't seem like it would cause any performance issues on a large gallery, what do you think?

That's a good point. I can't think of a clean way to exclude it, either, but 🤞 the `useMemo` means that the logic only fires when an image is loaded or changes are made to it, so I don't think it should have much of an effect on larger galleries. I just had a go at inserting a gallery with 50 images and performance switching between image blocks appears to be unaffected in my manual testing:

Kapture 2021-12-13 at 10 46 24

Let me know if you can think of any other edges cases I should test, though!

**Comment by glendaviesnz** [comment]
> Let me know if you can think of any other edges cases I should test, though!

I can't think of any additional edge cases that we would need to check.

**Review by glendaviesnz — APPROVED** [review]
This tested well for me on chrome, firefox and safari.

**Comment by ramonjd** [comment]
Also LGTM! 🙇
