### PR TITLE
Made each taxonomy appear on its own panel.

### LINKED ISSUE #4599: Title of panel Categories & Tags is wrong when only one taxonomy is used
## Issue Overview
When a custom post type uses either Categories **or** Tags, the title of the panel is _Categories & Tags_.

## Expected Behavior
The title of a panel should reflect its content.

## Possible Solution
Use separated panels for each taxonomy or a neutral term like _Taxonomies_ (or easier to understand ; maybe _Classification_).

---

Tested with Gutenberg 2.0
Related to #2450.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
This PR promotes each taxonomy to be a top-level panel (equal to the classic editor).

Closes: https://github.com/WordPress/gutenberg/issues/4599

## How Has This Been Tested?
Open post editor, verify now we don't have panel named "Categories & Tags" but a panel for categories and another one for tabs. Open and close the panels and verify things work as expected.
Change the categories & tags and check the functionality was not affected.
Add a custom taxonomy e.g: Type of Project, verify the taxonomy is rendered with the correct labels and works as expected.

## Screenshots (jpeg or gifs if applicable):
screen shot 2018-02-21 at 18 48 34

### CODE REVIEW

File: edit-post/components/sidebar/post-taxonomies/taxonomy-panel.js [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+/**
+ * Internal dependencies
+ */
+import { isEditorSidebarPanelOpened } from '../../../store/selectors';
+import { toggleGeneralSidebarEditorPanel } from '../../../store/actions';
+
+function TaxonomyPanel( { taxonomy, isOpened, onTogglePanel, panelName, children } ) {
+	const taxonomyMenuName = get( taxonomy, [ 'labels', 'menu_name' ] );
+	if ( ! taxonomyMenuName ) {
+		return;
```
Comment (aduth) [inline edit-post/components/sidebar/post-taxonomies/taxonomy-panel.js]: A component cannot return `undefined` from its render. It should return `null`.

File: edit-post/components/sidebar/post-taxonomies/taxonomy-panel.js [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+	}
+	return (
+		<PanelBody
+			key={ panelName }
```
Comment (aduth) [inline edit-post/components/sidebar/post-taxonomies/taxonomy-panel.js]: I don't think `key` is effective in this context?

File: edit-post/components/sidebar/post-taxonomies/taxonomy-panel.js [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+			panelName,
+			isOpened: slug ? isEditorSidebarPanelOpened( state, panelName ) : false,
+		};
+	},
+	{
+		onTogglePanel( panelName ) {
+			return toggleGeneralSidebarEditorPanel( panelName );
+		},
+	},
+	( stateProps, dispatchProps, ownProps ) => {
```
Comment (aduth) [inline edit-post/components/sidebar/post-taxonomies/taxonomy-panel.js]: See #5090 and https://github.com/WordPress/gutenberg/pull/5098#discussion_r168808765 for more on my distaste for the `mergeProps` function. Specifically that returning a function here will cause the component to _always_ re-render. Via `withDispatch` of #5137, we can probably avoid this now.

File: edit-post/components/sidebar/post-taxonomies/taxonomy-panel.js [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+	( state, ownProps ) => {
+		const slug = get( ownProps.taxonomy, [ 'slug' ] );
+		const panelName = slug ? `taxonomy-panel-${ slug }` : '';
+		return {
+			panelName,
+			isOpened: slug ? isEditorSidebarPanelOpened( state, panelName ) : false,
+		};
+	},
+	{
+		onTogglePanel( panelName ) {
```
Comment (aduth) [inline edit-post/components/sidebar/post-taxonomies/taxonomy-panel.js]: Minor: This could be simplified to:

```js
{
	onTogglePanel: toggleGeneralSidebarEditorPanel,
},
```

File: editor/components/post-taxonomies/flat-term-selector.js [hunk 5]
```diff
@@ -171,7 +171,6 @@ class FlatTermSelector extends Component {
 
 		return (
 			<div className="editor-post-taxonomies__flat-terms-selector">
```
Comment (aduth) [inline editor/components/post-taxonomies/flat-term-selector.js]: Do we need the wrapper anymore?

I see there's a lingering style for it, but I'm wondering if we need that either:

https://github.com/WordPress/gutenberg/blob/adb821746d9803ae304c57a750b824e08cdcacef/editor/components/post-taxonomies/style.scss#L1-L4

Why doesn't `.components-panel__body-title` add its own bottom margin rather than rely on children to add this themselves?

File: editor/components/post-taxonomies/index.js [hunk 6]
```diff
@@ -18,23 +18,26 @@ import HierarchicalTermSelector from './hierarchical-term-selector';
...
+			<TaxonomyComponent
+				key={ taxonomy.slug }
+				restBase={ taxonomy.rest_base }
+				slug={ taxonomy.slug }
+			/>,
+			taxonomy
+		);
+	} );
+
+	// Fragment is used because enzyme shallow does not seems to handle correctly components returning just arrays.
```
Comment (aduth) [inline editor/components/post-taxonomies/index.js]: Are you sure it's not just that `shallow` won't traverse into the `children` ? Have you tried with `mount` instead?

**Review by aduth — COMMENTED** [review]
Seeing key warning:

>react.0406e355.js:336 Warning: Each child in an array or iterator should have a unique "key" prop.
>
>Check the render method of `PostTaxonomies`. See https://fb.me/react-warning-keys for more information.

File: editor/components/post-taxonomies/index.js (hunk 6 above)
Comment (jorgefilipecosta) [reply editor/components/post-taxonomies/index.js]: Not sure of the reason but all my tries to test returning array failed and I observed in that debug method returned totally invalid data. At the time I found a recent PR on enzyme repository, related to this https://github.com/airbnb/enzyme/pull/1498, maybe these changes are not yet available in our version.

I also tried to use mount instead, but unfortunately, it was not possible because of errors related with our withAPIData HOC I think we would need to mock it to use mount here, which was something unnecessary for testing purposes of this component.

File: edit-post/components/sidebar/post-taxonomies/taxonomy-panel.js [hunk 7]
```diff
@@ -0,0 +1,48 @@
...
+			panelName,
+			isOpened: slug ?
+				select( 'core/edit-post' ).isEditorSidebarPanelOpened( panelName ) :
+				false,
+		};
+	} ),
+	withDispatch( ( dispatch, ownProps ) => ( {
+		onTogglePanel: () => {
+			if ( ownProps.panelName ) {
+				return dispatch( 'core/edit-post' ).
```
Comment (aduth) [inline edit-post/components/sidebar/post-taxonomies/taxonomy-panel.js]: This doesn't need to return a value.

File: edit-post/components/sidebar/post-taxonomies/taxonomy-panel.js [hunk 8]
```diff
@@ -0,0 +1,48 @@
...
+					toggleGeneralSidebarEditorPanel( ownProps.panelName );
```
Comment (aduth) [inline edit-post/components/sidebar/post-taxonomies/taxonomy-panel.js]: Minor: If we're concerned about line length, we could invert the condition to an early return to avoid the tab.

```js
if ( ! ownProps.panelName ) {
	return;
}

dispatch( 'core/edit-post' ).toggleGeneralSidebarEditorPanel( ownProps.panelName );
```

File: edit-post/components/sidebar/post-taxonomies/taxonomy-panel.js [hunk 9]
```diff
@@ -0,0 +1,48 @@
...
+		return {
+			panelName,
+			isOpened: slug ?
+				select( 'core/edit-post' ).isEditorSidebarPanelOpened( panelName ) :
+				false,
+		};
+	} ),
+	withDispatch( ( dispatch, ownProps ) => ( {
+		onTogglePanel: () => {
+			if ( ownProps.panelName ) {
```
Comment (aduth) [inline edit-post/components/sidebar/post-taxonomies/taxonomy-panel.js]: Under what real-world conditions will `panelName` be falsey? And in those cases, is it acceptable that toggling the panel then does nothing?

File: editor/components/post-taxonomies/index.js (hunk 6 above)
Comment (aduth) [reply editor/components/post-taxonomies/index.js]: It's very unintuitive, but this seemed to work okay for me:

```diff
diff --git a/editor/components/post-taxonomies/index.js b/editor/components/post-taxonomies/index.js
index d7f28db94..200d61f06 100644
--- a/editor/components/post-taxonomies/index.js
+++ b/editor/components/post-taxonomies/index.js
@@ -8,7 +8,7 @@ import { filter, identity, includes } from 'lodash';
  * WordPress dependencies
  */
 import { withAPIData } from '@wordpress/components';
-import { compose, Fragment } from '@wordpress/element';
+import { compose } from '@wordpress/element';
 
 /**
  * Internal dependencies
@@ -20,7 +20,8 @@ import { getCurrentPostType } from '../../store/selectors';
 
 export function PostTaxonomies( { postType, taxonomies, taxonomyWrapper = identity } ) {
 	const availableTaxonomies = filter( taxonomies.data, ( taxonomy ) => includes( taxonomy.types, postType ) );
-	const taxonomyComponents = availableTaxonomies.map( ( taxonomy ) => {
+
+	return availableTaxonomies.map( ( taxonomy ) => {
 		const TaxonomyComponent = taxonomy.hierarchical ? HierarchicalTermSelector : FlatTermSelector;
 		return taxonomyWrapper(
 			<TaxonomyComponent
@@ -31,14 +32,6 @@ export function PostTaxonomies( { postType, taxonomies, taxonomyWrapper = identi
 			taxonomy
 		);
 	} );
-
-	// Fragment is used because enzyme shallow does not seems to handle correctly components returning just arrays.
-	// Using debug method it was possible to verify shallow always output <undefined /> when arrays are used.
-	return (
-		<Fragment>
-			{ taxonomyComponents }
-		</Fragment>
-	);
 }
 
 const applyConnect = connect(
diff --git a/editor/components/post-taxonomies/test/index.js b/editor/components/post-taxonomies/test/index.js
index 42cfed70f..1f21845a1 100644
--- a/editor/components/post-taxonomies/test/index.js
+++ b/editor/components/post-taxonomies/test/index.js
@@ -16,7 +16,7 @@ describe( 'PostTaxonomies', () => {
 			<PostTaxonomies postType="page" taxonomies={ taxonomies } />
 		);
 
-		expect( wrapper.children() ).toHaveLength( 0 );
+		expect( wrapper.at( 0 ) ).toHaveLength( 0 );
 	} );
 
 	it( 'should render taxonomy components for taxonomies assigned to post type', () => {
@@ -43,8 +43,8 @@ describe( 'PostTaxonomies', () => {
 			<PostTaxonomies postType="page" taxonomies={ taxonomies } />
 		);
 
-		expect( wrapper.children() ).toHaveLength( 1 );
-		expect( wrapper.childAt( 0 ).props() ).toEqual( {
+		expect( wrapper.at( 0 ) ).toHaveLength( 1 );
+		expect( wrapper.at( 0 ).at( 0 ).props() ).toEqual( {
 			slug: 'category',
 			restBase: 'categories',
 		} );
```

https://github.com/airbnb/enzyme/issues/1149 is the (open) parent issue for array-returning components in Enzyme.

File: edit-post/components/sidebar/post-taxonomies/taxonomy-panel.js (hunk 9 above)
Comment (jorgefilipecosta) [reply edit-post/components/sidebar/post-taxonomies/taxonomy-panel.js]: I expected when loading, but on a second thought when loading the array is empty and we don't render taxonomy-panel at all, so this logic was not needed.

**Comment by jorgefilipecosta** [comment]
Hi @aduth thank you for providing a possible approach to handle enzyme array limitation 👍, all the feedback was applied.

**Comment by aduth** [comment]
I'd like for this to make it into the 2.3 release, but am also wary about the small design change here in that there's marginally more margin added to the bottom of sidebar panel titles. The removed styles applied only to block inspector panels, not those in the document inspector

Before (Focused)|After (Focused)
---|---
Before Focused|After Focused

Before (Unfocused)|After (Unfocused)
---|---
Before Unfocused|After Unfocused

cc @jasmussen

File: editor/components/post-taxonomies/index.js [hunk 10]
```diff
@@ -18,24 +18,19 @@ import HierarchicalTermSelector from './hierarchical-term-selector';
...
-					/>
-				);
-			} ) }
-		</div>
-	);
+	return availableTaxonomies.map( ( taxonomy ) => {
+		const TaxonomyComponent = taxonomy.hierarchical ? HierarchicalTermSelector : FlatTermSelector;
+		return taxonomyWrapper(
+			<TaxonomyComponent
+				key={ taxonomy.slug }
```
Comment (aduth) [inline editor/components/post-taxonomies/index.js]: I think there's some redundancy in `key` application. Technically this prop is not needed (nor used), *but* I do think it should be the responsibility of this component, not the callback for `taxonomyWrapper`, to apply the `key`. This could be done in one of two ways:

- Add a wrapper element to the return value of this `map` callback with the `key`
- Use `cloneElement` to assign `key` as a prop into the return value of `taxonomyWrapper`

File: editor/components/post-taxonomies/hierarchical-term-selector.js [hunk 11]
```diff
@@ -248,54 +248,52 @@ class HierarchicalTermSelector extends Component {
...
-		return (
-			<div className="editor-post-taxonomies__hierarchical-terms-selector">
-				<h3 className="editor-post-taxonomies__hierarchical-terms-selector-title">{ label }</h3>
-				{ this.renderTerms( availableTermsTree ) }
-				{ ! loading &&
+		return [
+			...this.renderTerms( availableTermsTree ),
+			! loading && (
+				<button
+					key="term-add-btn"
```
Comment (aduth) [inline editor/components/post-taxonomies/hierarchical-term-selector.js]: Minor: Abbreviating seems to serve only to introduce some ambiguity here.

File: editor/components/post-taxonomies/hierarchical-term-selector.js [hunk 12]
```diff
@@ -248,54 +248,52 @@ class HierarchicalTermSelector extends Component {
...
+					<input
+						type="text"
+						id={ inputId }
+						className="editor-post-taxonomies__hierarchical-terms-input"
+						value={ formName }
+						onChange={ this.onChangeFormName }
+						required
+					/>
+					{ !! availableTerms.length &&
+					<TreeSelect
```
Comment (aduth) [inline editor/components/post-taxonomies/hierarchical-term-selector.js]: Should be indented one more (how it was previously)

**Comment by jasmussen** [comment]
> I'd like for this to make it into the 2.3 release, but am also wary about the small design change here in that there's marginally more margin added to the bottom of sidebar panel titles. The removed styles applied only to block inspector panels, not those in the document inspector

Took a look. Here's the whole panel:

screen shot 2018-03-01 at 18 22 38

Here's the extra margin the change makes:

screen shot 2018-03-01 at 18 23 59

I think this is fine. 👍 👍 for the change and shipping, we can always revisit later.

---

Now that you made me look, however, and *this is unrelated to _this_ PR*, I did notice that there's too much padding in the Status and Comments panels:

screen shot 2018-03-01 at 18 24 04

screen shot 2018-03-01 at 18 25 45

This seems to be from the `.components-panel__row` top-margin not collapsing:

screen shot 2018-03-01 at 18 24 17

We can either convert that margin to a bottom margin instead, or do something like this:

```
.components-panel__row:first-of-type {
    margin-top: 0;
}
```

That would address it:

screen shot 2018-03-01 at 18 28 31

screen shot 2018-03-01 at 18 28 34

But this can be done separately.

File: editor/components/post-taxonomies/index.js (hunk 10 above)
Comment (jorgefilipecosta) [reply editor/components/post-taxonomies/index.js]: Yes, it makes sense to define the key here, I used a wrapper as it looks like the simplest approach.

File: editor/components/post-taxonomies/hierarchical-term-selector.js (hunk 11 above)
Comment (jorgefilipecosta) [reply editor/components/post-taxonomies/hierarchical-term-selector.js]: The abbreviation was removed.

File: editor/components/post-taxonomies/hierarchical-term-selector.js (hunk 12 above)
Comment (jorgefilipecosta) [reply editor/components/post-taxonomies/hierarchical-term-selector.js]: Corrected.

**Comment by jorgefilipecosta** [comment]
Hi @aduth and @jasmussen thank you for your feedback. I end up adding the CSS rule referred by @jasmussen, I think it improves the design compared to what we had, thank you @jasmussen 👍 I think the rule may be fragile e.g: if panel title was a div it would not work, but right now it seems like our best bet and it solves the problem.  Maybe the panel body should have title and content in separate dom containers and the :first-child selector could be used for rows, it is something to check and discuss after, but from the design point of view as things are right now the result would be the same.

The design now looks like this:
image

**Comment by jorgefilipecosta** [comment]
Test cases were updated, the addition of the fragment made the props test case even less intuitive, that test case was removed and another test case that tests the rendering of multiple taxonomies was added. I think this made tests cases simpler to understand and still relevant.

**Comment by jorgefilipecosta** [comment]
Hi @karmatosed, can you please have a final look regarding the user experience perspective?

File: components/panel/style.scss [hunk 13]
```diff
@@ -134,6 +134,10 @@
 	&:empty {
 		margin-top: 0;
 	}
+
+	&:first-of-type {
+		margin-top: 0px;
```
Comment (aduth) [inline components/panel/style.scss]: Minor: `0` doesn't need a unit. Further, this could be merged into the selector above:

```scss
&:empty,
&:first-of-type {
	margin-top: 0;
}
```

**Review by aduth — APPROVED** [review]
Code-wise, looks good 👍

**Review by karmatosed — APPROVED** [review]
Looks good to me, thanks for iterating on this.
