### PR TITLE
Button: Add prefix to the description ID

### LINKED ISSUE #34879: Button has incorrect
### Description

The `Button` component uses `uniqueId()` for the `aria-describedby` attribute to point to a `VisuallyHidden` element with that ID.

`uniqueId()` produces numeric IDs, however, IDs in HTML must not start with a number.

`uniqueId()` should be used with a prefix (or perhaps replaced by `uuid`) and ideally be memoized so it doesn't change on every render.

https://github.com/WordPress/gutenberg/blob/5cca2e1a8021679aaf2fc713c1a2c1cce168c374/packages/components/src/button/index.js#L142-L145

https://github.com/WordPress/gutenberg/blob/69e348ec80dc2cb9d537a8ba3cf6774b48636461/packages/block-editor/src/components/block-switcher/index.js#L167

### Step-by-step reproduction instructions

Render the `Button` component yourself or observe the wrong ID in the block switcher.

### Screenshots, screen recording, code snippet

Screenshot 2021-09-16 at 15 13 40

### Environment info

WordPress 5.8.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
Adds a prefix to the `descriptionId` since HTML IDs must start with this string.

Replaces `uniqueId()` with `useInstanceId()` so values are memoized.

Fixes #34879.

## How has this been tested?
1. Inspect the Block Switcher element.
2. The `aria-describedby` value should follow this pattern:

```js
`components-button__description-${ instanceId }`
```

## Screenshots 
CleanShot 2021-09-17 at 11 53 37

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/components/src/button/index.js [hunk 1]
```diff
@@ -86,6 +87,7 @@ export function Button( props, ref ) {
 		describedBy,
 		...additionalProps
 	} = useDeprecatedProps( props );
+	const instanceId = useInstanceId( Button );
```
Comment (ntsekouras) [inline packages/components/src/button/index.js]: Nit: you can pass the `prefix` in [useInstanceId](https://github.com/WordPress/gutenberg/blob/trunk/packages/compose/src/hooks/use-instance-id/index.js#L34).

**Review by ntsekouras — APPROVED** [review]
Looks good! Thanks George!

File: packages/components/src/button/index.js (hunk 1 above)
Comment (Mamaduka) [reply packages/components/src/button/index.js]: Thanks and done ✅
