### PR TITLE
RTC: Fix list sidebar reset during real-time collaboration

### LINKED ISSUE #75647: RTC: [Interface] List updates clear out the list items in the block inspector sidebar
Editing a list in a collaborative session causes the list items to be cleared from the block inspector sidebar for other connected clients. See the video for an example.

https://github.com/user-attachments/assets/b3eba253-52cd-424f-ab0a-7a351c063a6f

### PR DESCRIPTION
**Pull request by alecgeatches**
## What?

Closes https://github.com/WordPress/gutenberg/issues/75647.

## Why?

When real-time collaboration is enabled and two users are editing the same post, selecting a List block and viewing its items in the sidebar's "List View" tab clears out when the other user adds a list item:

https://github.com/user-attachments/assets/6bd3d960-e47d-4be2-ac02-ce3a8e5a5e2b

*Reproducing the bug by editing a selected list*

The root cause is that `resetBlocks()` is called whenever there's a real-time collaboration update, which dispatches `RESET_BLOCKS`. The `openedListViewPanels` reducer unconditionally clears all panel state on `RESET_BLOCKS`, collapsing the sidebar panel. Currently, there's no way to distinguish an RTC sync from a local reset, so the panel state gets wiped every time.

## How?

This PR adds an `isExternal` flag to the `resetBlocks` action, set to `true` when the reset originates from an external data source (RTC sync, undo/redo via `useBlockSync`) rather than a local user action. When `openedListViewPanels` reducer receives `isExternal` as true, the reducer returns the existing state unchanged, preserving whatever panel state the user had open. Local resets still clear panel state as before. This allows the same local logic to work, but not interrupt RTC collaborators:

https://github.com/user-attachments/assets/f53c3c7b-5b62-4a5f-aaeb-0cc809819dbe

*Fixed reproduction, selected list stays selected during edit*

The flag is set in `useBlockSync`'s `setControlledBlocks()`, which is always triggered by an external data source.

## Testing Instructions

1. Enable real-time collaboration and open a post in two separate browser tabs.
2. In Tab 1, insert a List block with a couple of list items.
3. In Tab 1, open the "Document Overview" panel and click on the List block. Switch to the "List View" tab in the right sidebar and see the list items.
4. In Tab 2, add a new list item to the same List block.
5. Go back to Tab 1. The sidebar should still show all list items (including the new one from Tab 2), and the panel should remain open.

## Test Coverage

Tests were added for the `openedListViewPanels` reducer covering:
- External `RESET_BLOCKS` (with `isExternal: true`) preserves all panel state
- Local `RESET_BLOCKS` (without the flag) still clears the `allOpen` flag and individual panel entries as before

### CODE REVIEW

File: packages/block-editor/src/components/provider/use-block-sync.js [hunk 1]
```diff
@@ -270,8 +270,12 @@ export default function useBlockSync( {
 			if ( subscribedRef.current ) {
 				pendingChangesRef.current.incoming = controlledBlocks;
 			}
+			// This reset is always from an external data source (real-time
+			// collaboration, undo/redo) pushing blocks into the editor,
+			// so mark it isExternal. The current user's edits are filtered out
+			// by the isOutgoing check above.
 			__unstableMarkNextChangeAsNotPersistent();
-			resetBlocks( controlledBlocks );
+			resetBlocks( controlledBlocks, { isExternal: true } );
```
Comment (alecgeatches) [inline packages/block-editor/src/components/provider/use-block-sync.js]: @ellatrix Do you think this `isExternal` flag for `resetBlocks()` is a reasonable idea?

Comment (alecgeatches) [reply packages/block-editor/src/components/provider/use-block-sync.js]: The main point is when an RTC change comes through `useBlockSync()` we can use the flag to ignore local behavior that clears out the sidebar. There may be some other places we want to ignore the side effects of `RESET_BLOCKS` when the change is coming remotely, so this gives us an easy path to do so.

**Comment by ingeniumed** [comment]
I have been encountering an intermittent bug with the way posts are rendered in the block editor for admin users with this fix. Note that this is with RTC off.

The rough steps are:

- Open up a post
- Edit the `single post` template from the post sidebar. Remove the featured image and make some other changes.
- Hit save.
- Go back to the `wp-admin` dashboard and load up a post.
- You'll see that the post is rendered as if its being published.
- Editing via the site editor also triggers the same issue

https://github.com/user-attachments/assets/d4d13283-7c53-4ca9-aa59-2d737250c385

I removed this fix, ran `npm run distclean` and then was finally able to load the post properly.

The reason why I said its intermittent is because I couldn't consistently replicate it with the above steps. I tried this 5 times, and could replicate it two times. The other times it just loaded as it should.

Note that it only happens with admins. Anyone lower than an admin doesn't see this behaviour.

**Comment by alecgeatches** [comment]
@ingeniumed I took a look at [your report above](https://github.com/WordPress/gutenberg/pull/76025#issuecomment-3988415895). I was unable to reproduce and I don't think it's related to this PR.

The only functional change affects `openedListViewPanels()`, which changes the behavior of the editor sidebar. Especially with RTC off and your reproduction, this seems to be unrelated. It almost looks like in your reproduction video that the left user has "Show Template" enabled through some means. `npm run distclean` fixing it makes me think it was some unusual build leftover, but I don't think it was this PR.

Feel free to try another reproduction!

**Comment by alecgeatches** [comment]
@youknowriad @ellatrix, could you have a quick look at this PR and [the comment above](https://github.com/WordPress/gutenberg/pull/76025#discussion_r2873742071)?

In short, we had added a `isExternal` flag to `resetBlocks()`, and then we use that to ignore the normal behavior to reset the sidebar if another user caused the `resetBlocks()` via RTC. I'm not very familiar with this part of the code and want to ensure it makes sense. Thanks!

File: packages/block-editor/src/components/provider/use-block-sync.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-editor/src/components/provider/use-block-sync.js]: Sorry for not replying to you before.

> The openedListViewPanels reducer unconditionally clears all panel state on RESET_BLOCKS, collapsing the sidebar panel.

Why does that happen in the first place? At first glance, that seems wrong to me. Maybe we should track down where that was introduced to understand the full picture better. Maybe we can remove this side effect and check for things other than RESET_BLOCKS

**Comment by jsnajdr** [comment]
> The root cause is that `resetBlocks()` is called whenever there's a real-time collaboration update, which dispatches `RESET_BLOCKS`. The openedListViewPanels reducer unconditionally clears all panel state on `RESET_BLOCKS`, collapsing the sidebar panel.

Recently we're starting to see more and more instances of a very similar problem: when calling `RESET_BLOCKS`, do we want to completely reset the editor state and start from scratch, or do we want to just "edit the blocks by replacing" and preserve as much editor state as possible? It's increasingly clear that we want to do the latter.

Since #75458 we started preserving "controlled inner blocks" on reset. When the block IDs are mostly the same after reset, try to find the controlled subtrees and copy them over.

In #76529 and #76310 we identified that there is a lot of trouble when `RESET_BLOCKS` removes the `blockEditingModes` flags. In the end we'll probably start preserving them.

And now we see that also `openedListViewPanels` state ought to be preserved on `RESET_BLOCKS` instead of cleared.

It's always the same story: don't clear state on reset, preserve as much as possible. Instead of the `isExternal` flag, could we just preserve the `openedListViewPanels` state on reset, unconditionally? If any panels need to be closed, let's implement that some other way, triggered by a different condition.

**Comment by alecgeatches** [comment]
> Instead of the `isExternal` flag, could we just preserve the `openedListViewPanels` state on reset, unconditionally?

@jsnajdr Great idea! This PR has now been simplified to a `-3` change and works the same.

**Review by chriszarate — APPROVED** [review]

**Review by ingeniumed — APPROVED** [review]
