### PR TITLE
Fix locked template not updating when inner blocks template prop changes

### LINKED ISSUE #27897: Issue with InnerBlock's template prop in version > 5.4.4
**Describe the bug**
I am running into an issue with InnerBlock's template prop. When I increase or decrease count, it doesn't change. Only when I refresh the editor the change maybe apply. This happens in the version > 5.4.4. Version 5.4.4 was fine without this issue.

**Screen Recorded**
innerblock bug

**Below is a simple reproduction of code.**

```
   // Import WP Gutenberg Components
   const { InnerBlocks, InspectorControls } = wp.blockEditor
   const { Component } = wp.element
   const { 
      PanelBody, RangeControl
   } = wp.components


   const { __ } = wp.i18n;


   const getTemplates = (items, block) => {
      // Tempporary store
      const store = [];
      // Slot each template into the store 
      for(let i=0; i<items; i++) store[i] = [block];

      return store;
   };


   const IB_OPTIONS = {
      templateLock: 'all'
   };


   class PanelColumns extends Component {
      
      constructor() {
         super(...arguments);
      }

      render() {
         const {
            PanelBody, RangeControl,
            attributes, setAttributes,
         } = this.props;

         const { items } = attributes;

         const Items = <RangeControl
            label={ __('Number of items in the section') }
            value={ items }
            onChange={ items => setAttributes( { items } ) }
            min={ 1 }
            max={ 12 }
         />

         // Debug Logger
         // console.log(attributes);
         
         return (
            <PanelBody title={ __('Columns') } initialOpen={ true }>
               
               { Items }
            </PanelBody>
         );
      }
   };


   export default function ({ clientId, attributes, className, setAttributes }) {
      
      const {
         items
      } = attributes

      // Common options needed for each Panel Control on right side of the editor
      const PanelCommonOptions = { attributes, setAttributes, PanelBody }

      // Save the InnerBlocks in a new variable
      const innerBlockContent = <InnerBlocks { ...IB_OPTIONS } template={ getTemplates(items, 'core/image') } />
      console.log(innerBlockContent)
      return (
         <>
            <InspectorControls>
               
               <PanelColumns {...{ RangeControl, ...PanelCommonOptions }} />

            </InspectorControls>

            <div className={ className } >
               { innerBlockContent }
            </div>
         </>
      )
   }
```

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #27897

Adds a missing dependency to ensure template sync update works correctly.

It looks like when this was refactored to a hook the dependency was missed.

## How has this been tested?
Added an e2e test.

To manually test:
1. Paste the code in this file in your browser console: https://raw.githubusercontent.com/WordPress/gutenberg/3e66b4c52a23a2317b3e090193b294d811bd8b6b/packages/e2e-tests/plugins/inner-blocks-templates/index.js
2. Add the 'Test Inner Blocks update locked template' block
3. Click the 'update template' button
4. You should see a second block added.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/e2e-tests/plugins/inner-blocks-templates/index.js [hunk 1]
```diff
@@ -24,55 +24,106 @@
...
+		],
+	];
+
 	var save = function () {
-		return el( InnerBlocks.Content );
+		return el(InnerBlocks.Content);
 	};
 
-	registerBlockType( 'test/test-inner-blocks-no-locking', {
+	registerBlockType('test/test-inner-blocks-no-locking', {
```
Comment (talldan) [inline packages/e2e-tests/plugins/inner-blocks-templates/index.js:48]: For some reason prettier isn't working on these files. I tried the `npm run format-js` command as well.

Comment (talldan) [reply packages/e2e-tests/plugins/inner-blocks-templates/index.js:48]: I don't think this is a major blocker for the PR.

I had a brief look and couldn't see why this is happening.

**Review by diegohaz — APPROVED** [review]
Tested the "Test Inner Blocks update locked template" and it works as described. Thanks!

**Comment by talldan** [comment]
Thanks for the review!

File: packages/e2e-tests/plugins/inner-blocks-templates/index.js (hunk 1 above)
Comment (talldan) [reply packages/e2e-tests/plugins/inner-blocks-templates/index.js:48]: #28033 has background and restores formatting and linting.

**Comment by WYKDev** [comment]
Thank you talldan for taking the time to resolve my concern.

I look forward to the fix in the version hopefully in the 5.6.1 minor release.

Thank you again.

Kind regards,
Wenyu
