### PR TITLE
Post Template: fix incorrect offset query

### LINKED ISSUE #56439: Query Loop Block: Can't find post in the editor
### Description

When I insert a Query Loop block in the editor, there should be posts that matche the query, but no post is found. On the frontend, the posts are displayed correctly.

This problem seems to occur when the Gutenberg plugin is enabled.

### Step-by-step reproduction instructions

N/A

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/bac0bcfe-3dbc-4931-9c00-f665c21fae2a

### Environment info

WordPress Version: WordPress 6.5-alpha-57120
Gutenberg Version: 17.1.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #56439
Related to: #56034

## What?
This PR fixes an issue where the Post Template block's offset query would have an incorrect value when using the Query Loop block in the editor.

## Why?

This offset value was originally calculated using the following formula.

```javascript
const query = {
	offset: perPage ? perPage * ( page - 1 ) + offset : 0,
	// ...
};
```

In a post template block, my understanding is that the `page` variable should always be `1`. In other words, the original `offset` value should have been calculated as follows.

```javascript
const query = {
	offset: perPage ? perPage * 0 + offset : 0,
	// ...
};

to...

const query = {
	offset: perPage ? offset : 0,
	// ...
};
```

Later, in #56034, this calculation formula was changed as follows.
```javascript
const query = {
	offset: perPage ? perPage + offset : 0,
	order,
	orderby: orderBy,
};
```

As a result, the `perPage` value is always added to the offset value, and I suspect that it will deviate from the front end query offset.

## How?
Maintain the original calculation formula.

## Testing Instructions

- Create multiple posts.
- Insert a Query Loop block into the page.
- From the block toolbar, change the "Items Per Page" and "Offset" parameters.
- Query results in the editor and frontend should always match.

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/54422211/a0c8ebe6-cc5b-4179-b24f-d54e1c41ef00

### CODE REVIEW

File: packages/block-library/src/post-template/edit.js [hunk 1]
```diff
@@ -123,7 +123,7 @@ export default function PostTemplateEdit( {
 					slug: templateSlug.replace( 'category-', '' ),
 				} );
 			const query = {
-				offset: perPage ? perPage + offset : 0,
+				offset: perPage ? offset || 0 : 0,
```
Comment (t-hamano) [inline packages/block-library/src/post-template/edit.js]: `|| 0` ensures that the value of the `offset` property is always a number. Without this code, when you empty the offset field, the value of the offset property will be an empty string and the spinner will remain visible.

https://github.com/WordPress/gutenberg/assets/54422211/318626f5-517f-4d45-8a0b-3935b1027d6a

Comment (ntsekouras) [reply packages/block-library/src/post-template/edit.js]: Per page doesn't affect the calculation, so `offset: offset || 0` would be enough.

**Review by ntsekouras — APPROVED** [review]
Thanks for catching this and the fix! 🚀 
I've left a small comment and will pre approve.

File: packages/block-library/src/post-template/edit.js (hunk 1 above)
Comment (t-hamano) [reply packages/block-library/src/post-template/edit.js]: Good point, I updated 👍
