### PR TITLE
Fix: Duotone unset button

### LINKED ISSUE #69980: Duotone: Improve the unset button
## What problem does this address?

Currently, the Duotone “Unset” button displays the admin theme color (blue) on hover and does not show a checkmark when selected, which may lead to some confusion for users.

## What is your proposed solution?
This can be improved by removing the blue color on hover and adding a checkmark for the unset duotone just how it's present in other duotone options 

## Screencast 

https://github.com/user-attachments/assets/66621eb8-8982-4d93-adb7-47e5e7bd9fda

### Enviornment Info 

- WordPress: 6.8 
- Gutenberg: 20.7.0
- Theme: TT4 ( In TT5 we will have to add dutone in theme.json )
- MacOS
- Chrome

### PR DESCRIPTION
**Pull request by Rishit30G**
## What?
Closes #69980

## Why?
This PR is necessary to improve the behaviour of the default duotone unset button

## How?
This PR targets the class which sets the blue color to the unset button and sets the color to transparent 
It also adds the condition of `value === undefined` to `isUnset` to get the checked icon on the unset button 

## Testing Instructions
- Create a new post 
- Add an Image Block or any block that has 'Duotone' present 
- Open the Duotone from the right panel ( Styles > Filters > Duotone ) 
- Notice that now when we select a duotone option we get a checkmark and on hovering or selecting there is no blue color

## Screenshots or screencast 

https://github.com/user-attachments/assets/de5d86d2-0b5f-4dd1-86cf-749422a589a6

### CODE REVIEW

File: packages/components/src/duotone-picker/duotone-picker.tsx [hunk 1]
```diff
@@ -76,7 +76,7 @@ function DuotonePicker( {
 		[ colorPalette ]
 	);
 
-	const isUnset = value === 'unset';
+	const isUnset = value === 'unset' || value === undefined;
```
Comment (Mamaduka) [inline packages/components/src/duotone-picker/duotone-picker.tsx]: I'm unsure about this change. The "Unset" is similar to the clear button; I don't think it should be selected when no Duotone value is set.

Comment (Rishit30G) [reply packages/components/src/duotone-picker/duotone-picker.tsx]: Makes sense, but the current implementation is also not working, that's the reason why I have introduced `undefined`
Apart from `undefined` nothing seems to be working here to get the check option for unset button

Comment (Mamaduka) [reply packages/components/src/duotone-picker/duotone-picker.tsx]: It then seems we're trying to solve the wrong problem in the wrong place. Why?

* The `unset` is a valid filter and can remove the globally set Duotone filter. It shouldn't be treated as `undefined`.
* When this filter is selected, selection should be visible, and it should also be clearable.

The following changes fix these issues in my tests:

```diff
diff --git packages/block-editor/src/hooks/duotone.js packages/block-editor/src/hooks/duotone.js
index 246e4fde7d8..b6a1989870d 100644
--- packages/block-editor/src/hooks/duotone.js
+++ packages/block-editor/src/hooks/duotone.js
@@ -124,9 +124,10 @@ function DuotonePanelPure( { style, setAttributes, name } ) {
 		return null;
 	}
 
-	const duotonePresetOrColors = ! Array.isArray( duotoneStyle )
-		? getColorsFromDuotonePreset( duotoneStyle, duotonePalette )
-		: duotoneStyle;
+	const duotonePresetOrColors =
+		duotoneStyle === 'unset' || Array.isArray( duotoneStyle )
+			? duotoneStyle
+			: getColorsFromDuotonePreset( duotoneStyle, duotonePalette );
 
 	return (
 		<>
```

Comment (Rishit30G) [reply packages/components/src/duotone-picker/duotone-picker.tsx]: > It then seems we're trying to solve the wrong problem in the wrong place. Why?

My apologies, I wasn't aware of this file, I was trying to fix the component itself 🙇🏻 


> When this filter is selected, selection should be visible, and it should also be clearable.

Yes, I have updated the file with the shared diff, thanks!

**Review by Mamaduka — APPROVED** [review]
The fix works as expected. Thanks, @Rishit30G!

**Comment by Rishit30G** [comment]
Thanks @Mamaduka for approving the PR, if we are all set then we consider merging this! 💯
