### PR TITLE
Flex Layout: Fix incorrect default alignment values for `Vertical Alignment Control` component

### LINKED ISSUE #68864: `Flex Layout`:  `Incorrect` default alignment value used in `Vertical Alignment Control` Component
### Description

Originally discovered by @luisherranz while testing here https://github.com/WordPress/gutenberg/pull/68112#pullrequestreview-2569737517 and splitting it from the `enhancement` as this is an existing bug.

https://github.com/WordPress/gutenberg/blob/f14a977248dfabbb15460ffab7b03d64e528a682/packages/block-editor/src/layouts/flex.js#L202-L205

Here, the default value of vertical alignment when the orientation is set to `vertical` is essentially `verticalAlignmentMap.top` which resolves to `flex-start`, which is not acceptable for the `Toolbar`. This causes the default value to remain unselected within the `Vertical Alignment Toolbar`.

Acceptable values:
https://github.com/WordPress/gutenberg/blob/f14a977248dfabbb15460ffab7b03d64e528a682/packages/block-editor/src/layouts/flex.js#L222

https://github.com/WordPress/gutenberg/blob/f14a977248dfabbb15460ffab7b03d64e528a682/packages/block-editor/src/layouts/flex.js#L146-L147

It's expected that `layout.verticalAlignment` holds the **_key_** instead of the **_value_**, failing to do so causes the bug mentioned above (No default alignment value being rendered on the toolbar when the orientation is set to columns).

I searched the issue repository but couldn’t find a similar report. Please feel free to close this if it’s a duplicate.

### Step-by-step reproduction instructions

1. Create a `Row` block.
2. Verify that the default value of `Alignment` in the `Toolbar` is set as `Align middle`.
3. Convert the `Row` to a `Column` block.
4. Notice, that the `Alignment` value within the `Toolbar` is missing, whereas, it should have been selected as `Top`.

### Screenshots, screen recording, code snippet

Image

### Environment info

- WordPress Version: 6.8-alpha-59361
- Gutenberg Version: Trunk (654bace6e3c7269dfdf99d78b0e08ea8e63376f8)
- OS: macOS Sequoia

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by yogeshbhutkar**
## What, Why and How?

Fixes: #68864 

This PR addresses a bug in which the default `vertical alignment` value does not render as selected in the Vertical Alignment Toolbar when the orientation is set to vertical. The issue arises because the `layout.verticalAlignment` property is expected to store the alignment key (e.g., `top`, `center`, `bottom`, `stretch`, etc.) but instead holds the resolved CSS value (e.g., `flex-start`).

## Testing Instructions
1. Create a `Row Block`.
2. Verify from the `Block Toolbar` that the default alignment value is `Align middle`.
3. Convert the same `Block` to a `Column` block.
4. Confirm that the default alignment value for is now appropriately set to `Top`.

## Screencast

https://github.com/user-attachments/assets/db451918-0c26-4317-8adc-a811d056d2ea

## Screenshots

|Before|After|
|-|-|
|before|after|

### CODE REVIEW

**Comment by yogeshbhutkar** [comment]
Hi, can this PR get a review?

CC: @WordPress/gutenberg-core @t-hamano @Mamaduka

**Comment by yogeshbhutkar** [comment]
I noticed that this bug is still unresolved on trunk. Here's more context on the proposed changes to help this PR move forward.

Within `flex.js`, we're trying to pass the value of `verticalAlignment` to `BlockVerticalAlignmentControl`.
https://github.com/WordPress/gutenberg/blob/a5d288757fed0b0eb2f1a542bcf6203f7aae2d4d/packages/block-editor/src/layouts/flex.js#L219

The value of `verticalAlignment` is determined here:
https://github.com/WordPress/gutenberg/blob/a5d288757fed0b0eb2f1a542bcf6203f7aae2d4d/packages/block-editor/src/layouts/flex.js#L202-L205

When the orientation is `vertical` (i.e., Stack), `verticalAlignmentMap.top` becomes `flex-start`.
https://github.com/WordPress/gutenberg/blob/a5d288757fed0b0eb2f1a542bcf6203f7aae2d4d/packages/block-editor/src/layouts/flex.js#L52

However, `BlockVerticalAlignmentUI` does not expect to receive `flex-start`, there's no corresponding value for `flex-start`, instead it expects the value `top`.
https://github.com/WordPress/gutenberg/blob/a5d288757fed0b0eb2f1a542bcf6203f7aae2d4d/packages/block-editor/src/components/block-vertical-alignment-control/ui.js#L15

This can be seen in the UI as well, when a row block is transformed to stack, the default value is not shown as selected in the UI.

|Actual|Expected|
|-|-|
|bug|expected|

We cannot update `verticalAlignmentMap.top` as it's also being used elsewhere to add the corresponding `justify-content` rule, therefore, this PR creates a new constant for the default values.

Hi @t-hamano,
If you have some time, could you please review this PR?

**Review by t-hamano — COMMENTED** [review]
@yogeshbhutkar Thanks for the PR!

To understand the problem exactly, let me confirm one thing.

This problem does not occur in horizontal layout, i.e. Row block, and "Align middle" is selected as the default value correctly. The reason for this is that the default vertical alignment in the horizontal layout is "center", and the key name and value in the `verticalAlignmentMap` object were the same, so fortunately, no problems occurred.

I my understanding correct?

File: packages/block-editor/src/layouts/flex.js [hunk 1]
```diff
@@ -56,6 +56,11 @@ const verticalAlignmentMap = {
 	'space-between': 'space-between',
 };
 
+const DEFAULT_ALIGNMENT = {
+	horizontal: 'center',
+	vertical: 'top',
+};
```
Comment (t-hamano) [inline packages/block-editor/src/layouts/flex.js]:
```suggestion
const defaultAlignments = {
	horizontal: 'center',
	vertical: 'top',
};
```

For constants, UPPER_SNAKE_CASE is indeed recommended, but in this file, it might be better to use the same format as the other constants.

**Comment by yogeshbhutkar** [comment]
> This problem does not occur in horizontal layout, i.e. Row block, and "Align middle" is selected as the default value correctly. The reason for this is that the default vertical alignment in the horizontal layout is "center", and the key name and value in the verticalAlignmentMap object were the same, so fortunately, no problems occurred.
> 
> I my understanding correct?

Yes, exactly.

**Review by t-hamano — APPROVED** [review]
The changes make sense to me 👍
