### PR TITLE
Footnotes: save numbering through the entity provider

### LINKED ISSUE #52239: Footnotes: anchors wrongly positioned (Firefox)
### Description

In Firefox, both in the editor and in the front end, footnote anchors are rendered as follows:

footnotes-firefox-rendering

### Step-by-step reproduction instructions

1. Using Firefox, start a new post
2. Add some footnotes
3. Observe their rendering

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

⚠️ Depends on [RichText/Footnotes: make getRichTextValues work with InnerBlocks.Content](https://github.com/WordPress/gutenberg/pull/52241), which should be merged first.

This PR adjusts the numbering of the footnote anchors in the entity provider, so the numbering is saved to the db, instead of having an asterisk placeholder and using a CSS counter. It also adds a `sup` tag so we don't need any CSS at all.

Also fixes #52239.

## Why?

* We no longer need a CSS hack to hide the asterisk fallback.
* Numbering is done without CSS, no need for a counter and counter reset etc.
* Footnotes are visible and pretty for email, Reader, RSS...
* The anchor now has an underline as links should.

## How?

It's easier than I though because, since footnote IDs are unique, we don't actually need the block clientID and attribute key to update the numbering.

### CODE REVIEW

File: packages/rich-text/src/to-dom.js [hunk 1]
```diff
@@ -61,6 +61,10 @@ function append( element, child ) {
 		child = element.ownerDocument.createTextNode( child );
 	}
 
+	if ( child.html !== undefined ) {
+		return ( element.innerHTML += child.html );
+	}
+
```
Comment (mcsf) [inline packages/rich-text/src/to-dom.js:63]: Does this need to be documented and perhaps mentioned in the change log?

**Review by mcsf — COMMENTED** [review]
This is clever and works pretty well for me!

As discussed in private, it would be great to have a compatibility plan to automatically migrate from the previous format. Even though we are still in the Beta cycle for WP 6.3, we owe it to ourselves to see what we can do to minimise breakage for early testers of footnotes.

File: packages/rich-text/src/to-dom.js (hunk 1 above)
Comment (ellatrix) [reply packages/rich-text/src/to-dom.js:63]: It's not an external API

**Review by ellatrix — COMMENTED** [review]
Before merging, make sure [RichText/Footnotes: make getRichTextValues work with InnerBlocks.Content](https://github.com/WordPress/gutenberg/pull/52241) is merged first.

File: packages/rich-text/src/component/use-select-object.js [hunk 2]
```diff
@@ -25,8 +25,13 @@ export function useSelectObject() {
 			if ( selection.containsNode( target ) ) return;
 
 			const range = ownerDocument.createRange();
+			// If the target in within a non editable element, select the non
+			// editable element.
```
Comment (mcsf) [inline packages/rich-text/src/component/use-select-object.js]:
```suggestion
			// If the target is within a non editable element, select the non
			// editable element.
```

**Review by mcsf — APPROVED** [review]

**Comment by mcsf** [comment]
Rebased against trunk after merging #52241 and dropped the commits that had been cherry-picked from that branch.

**Comment by ockham** [comment]
Cherry-picked to the `release/16.2` branch in 7ab272b5da.
