### PR TITLE
[Type] Enhancement - Adds max limit to row span and column span in grid.

### LINKED ISSUE #63967: Grid: Add `max` to 'Row span' and 'Column span' controls
Feedback from @jameskoster:

> It feels a bit unexpected that I can set row span to a greater number than the actual number of rows in the grid, especially in auto mode. In manual mode should it increase the row value on the parent?

We have a `max` on the `<input>` for the _Row_ and _Column_ controls so I think a sensible fix here would be to similarly set a `max` on the _Row span_ and _Column span_ controls.

The `max` needs to take into account the position of the grid item. For example if a grid item is in the second last column then its max column span should be 2.

It might be nice to have these controls automatically increase the parent grid's size one day but for now I think the important thing is that we're consistent across all of the grid controls. Right now the placement controls have a max but the span controls don't—weird!

### PR DESCRIPTION
**Pull request by vipul0425**
## What?
Fixes: #63967 

## Why?
There was no maximum limit set for row span and column span, allowing users to set values larger than the actual number of rows or columns.

## How?
It calculates the max column and row span based on the columns/row count and current position.

## Testing Instructions
1. Adds the grid block.
2. Insert any block into it example image block.
3. Try to increase/decrease the row/column span in the style tab of the block. It should not exceed the max columns/rows.

## Screenshots or screencast 

https://github.com/user-attachments/assets/96e49da5-52d3-47f7-b20b-7e6e01379f47

### CODE REVIEW

**Comment by jameskoster** [comment]
Makes sense to me :)

File: packages/block-editor/src/components/child-layout-control/index.js [hunk 1]
```diff
@@ -220,53 +219,75 @@ function GridControls( {
...
-							rowStart,
-							columnSpan,
-							rowSpan: newRowSpan,
-						} );
-					} }
-					value={ rowSpan ?? 1 }
-					min={ 1 }
-				/>
-			</HStack>
+				<FlexItem style={ { width: '50%' } }>
```
Comment (tellthemachines) [inline packages/block-editor/src/components/child-layout-control/index.js:258]: Why change from `HStack` to `Flex` and `FlexItem`? `HStack` uses less markup to the same effect.

File: packages/block-editor/src/components/child-layout-control/index.js [hunk 2]
```diff
@@ -220,53 +219,75 @@ function GridControls( {
...
+						type="number"
+						onChange={ ( value ) => {
+							// Don't allow unsetting.
+							const newColumnSpan =
+								value === ''
+									? 1
+									: Math.min(
+											parseInt( value, 10 ),
+											maxColumnSpan
+									  );
```
Comment (tellthemachines) [inline packages/block-editor/src/components/child-layout-control/index.js]: We should only set a `maxColumnSpan` if the `columnCount` exists. Otherwise, when the grid is in auto mode and can have as many columns as fit on the screen, it won't be possible to increase the column count beyond 3.

File: packages/block-editor/src/components/child-layout-control/index.js [hunk 3]
```diff
@@ -220,53 +219,75 @@ function GridControls( {
...
+						size="__unstable-large"
+						label={ __( 'Row span' ) }
+						type="number"
+						onChange={ ( value ) => {
+							// Don't allow unsetting.
+							const newRowSpan =
+								value === ''
+									? 1
+									: Math.min(
+											parseInt( value, 10 ),
```
Comment (tellthemachines) [inline packages/block-editor/src/components/child-layout-control/index.js]: I don't believe we should set a maxRowSpan unless it's for manual mode under the experimental flag, because in the current stable grid it's not possible to set a row count. This effectively means that items will never be able to span more than one row.

**Review by tellthemachines — COMMENTED** [review]
Thanks for the PR! 

Unfortunately, #63967 is lacking some context in its description 😬  This issue mostly applies to the experimental grid functionality behind the experiment flag.
To enable it, go to "Experiments" under the "Gutenberg" wp-admin menu item.
To see it in the code, look at where we're checking for `window.__experimentalEnableGridInteractivity` being enabled.

As mentioned in the comments below, I think we could use the column span constraint in stable grid _when a columnCount exists_, but not otherwise.

The row span constraint doesn't make sense outside of the experiment flag, as we can't currently set row count in stable.

A general purpose tip for submitting PRs in Gutenberg:

Make sure you manually test your changes in your local development environment before submitting the PR. Some of the issues I'm seeing in this PR could have easily been detected by testing the changes in a block with grid layout against its current state in trunk.
If you're implementing something as described in an issue (as I'm guessing was the case here!) and in testing it doesn't seem to work that well, feel free to start a discussion about it on the issue. Sometimes things we think might work don't in practice! And that's OK. It just means we need to think about it some more.

And a small workflow tip 🙂 

"Feat" isn't used as a PR descriptor in this repo. We use GitHub labels instead: "[Type] Feature" labels for major features only, "[Type] Enhancement" for small improvements such as this one, or "[Type] Bug" for stuff that's broken.

File: packages/block-editor/src/components/child-layout-control/index.js (hunk 1 above)
Comment (vipul0425) [reply packages/block-editor/src/components/child-layout-control/index.js:258]: I tried, but by using the `max` attribute it wasn’t applying the size as expected. So, I followed a similar approach to the one Robert used in the Grid Placement section below.

image

**Comment by vipul0425** [comment]
Hi @tellthemachines, Thank you so much for the review. 🙇 

I’ve updated the PR. I also noticed that when we set the `maxColumnSpan` based on the `columnCount`, it restricts the span to 3—since the default `columnCount` is set to 3 initially and the parent layout doesn’t define this property. However, it works as expected once we switch to manual mode, as shown in the video.

Should we check against the `parentLayout'`s `columnCount` directly instead? I couldn’t find any other property related to the layout mode. Alternatively, should we consider combining it with `rowCount` to handle edge cases more accurately?



https://github.com/user-attachments/assets/ee70abfb-3426-4303-b1a3-a4ebaeee44ba

File: packages/block-editor/src/components/child-layout-control/index.js [hunk 4]
```diff
@@ -235,53 +234,78 @@ function GridControls( {
 		} );
 	};
 
+	// Calculate max column span based on current position and grid width
+	const maxColumnSpan = columnCount
+		? columnCount - ( columnStart ?? 1 ) + 1
```
Comment (tellthemachines) [inline packages/block-editor/src/components/child-layout-control/index.js:239]: `columnCount` is always going to exist here because we're setting a default value of 3 when we get it from `parentLayout` above. The problem with that is in auto layouts with no columnCount defined, we're now unable to set a columnCount above 3 on child blocks.

I think we'll have to remove that default value in order to fix this, and maybe pass it instead to `useGetNumberOfBlocksBeforeCell` if `columnCount` is undefined.
We should also remove `columnCount` from the condition that allows the grid placement controls to display below (that shouldn't make a difference because `columnCount` is always true currently). 

(Later we might want to consider not displaying the grid placement controls for children of auto grids, but that can be done in another PR)

**Review by tellthemachines — COMMENTED** [review]
Thanks for persisting with this! It looks pretty close, but I found a small bug. Details in the comment below.

File: packages/block-editor/src/components/child-layout-control/index.js (hunk 4 above)
Comment (vipul0425) [reply packages/block-editor/src/components/child-layout-control/index.js:239]: Since we've now removed the default `columnCount`, the grid placement controls in Auto mode are no longer visible, after removing the `columnCount` check for their visibility. So, this change has been included in the same PR.

**Review by tellthemachines — APPROVED** [review]
Thanks for the update, changes LGTM!

CI failures seem unrelated to the PR so they should go away if you rebase this branch. Are you able to do that?

**Comment by vipul0425** [comment]
Sure @tellthemachines
