### PR TITLE
Block Editor: Fix block color contrast checker

### LINKED ISSUE #67035: The contrast checker should be triggered when colors are changed.
## What problem does this address?

While working on TT5, I noticed that the contrast checker only runs when you change the block focus. This means if you’re adjusting colors for a block, the contrast issue message only appears after you switch to another element and then come back to the block controls. As a result, many users might miss the contrast warning entirely, defeating its purpose.

At the same time, the notice is still there when you update colors that would pass the contrast checker (for the same reason).

https://github.com/user-attachments/assets/2c3b31d3-ef52-438c-bae6-f02744b2bd87

## What is your proposed solution?

It would be ideal if the notice updated in real-time with color changes, providing a clear message for the current color selection.

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Fixes #67035.
Alternative to #67036.

Combine `useLayoutEffect` and two rAF calls to ensure that values are read after the current paint but before the next paint.

## Why?
The solution is similar to #59227, which also needs to read computed styles from the block element.

Quoting from: #59227.
> React does not guarantee that useEffect will be called after the browser paints and, in fact, useEffect can be called before a paint when React is handling a user event (e.g. a click) or if a useLayoutEffect in the component tree updates state (e.g. calls setState). See https://github.com/facebook/react/issues/20863#issuecomment-976582680.

This is probably a better summary for React 18 - https://github.com/facebook/react/issues/24409#issuecomment-1103917606.

## Testing Instructions
1. Open a post.
2. Add paragraph block.
3. Change block colors.
4. Confirm that the contrast checker is displayed when selecting problematic color combinations.

### Testing Instructions for Keyboard
Same.

### CODE REVIEW

**Review by juanfra — APPROVED** [review]
Thanks so much for working on this, George!

Everything is testing great on my end, and the code looks solid. 


https://github.com/user-attachments/assets/5abb91ea-8121-4561-aadc-3cec2e512824

File: packages/block-editor/src/hooks/contrast-checker.js [hunk 1]
```diff
@@ -1,60 +1,94 @@
...
+			setColors( getBlockElementColors( blockEl ) );
 		}
 
-		setDetectedBackgroundColor( backgroundColor );
-	}, [ blockEl ] );
+		// Combine `useLayoutEffect` and two rAF calls to ensure that values are read
+		// after the current paint but before the next paint.
+		window.requestAnimationFrame( () =>
+			window.requestAnimationFrame( updateColors )
+		);
```
Comment (Mamaduka) [inline packages/block-editor/src/hooks/contrast-checker.js:83]: This is the actual fix. The rest is just moving code around for readability.

Comment (jsnajdr) [reply packages/block-editor/src/hooks/contrast-checker.js:83]: It seems to me that the actual fix is removing the `[ blockEl ]` dependency array from the effect. Then it runs on every render, not only on `blockEl` change (the block's DOM element hardly ever changes), and catches all the color updates.

Running after the current paint but before the next paint is exactly what `useEffect` does. It runs when the rendered DOM is already painted. You shouldn't need to simulate it with layout effect + rAF.

Comment (Mamaduka) [reply packages/block-editor/src/hooks/contrast-checker.js:83]: @jsnajdr, the component had an issue before adding `blockEl` as a dependency. It didn't always work, and the computed properties from `blockEl` were stale.

>  You shouldn't need to simulate it with layout effect + rAF.

I would like to avoid it as well, but this the only solution that works.

Quoting from: #59227.
> React does not guarantee that useEffect will be called after the browser paints and, in fact, useEffect can be called before a paint when React is handling a user event (e.g. a click) or if a useLayoutEffect in the component tree updates state (e.g. calls setState). See https://github.com/facebook/react/issues/20863#issuecomment-976582680.

This is probably a better summary for React 18 - https://github.com/facebook/react/issues/24409#issuecomment-1103917606.

**Comment by Mamaduka** [comment]
Note: Removing dependency regression introduced in #63799, doesn't resolve the issue the component had issues before. See #60825.

**Comment by afercia** [comment]
Thanks a lot for working on this, I get a chance to test it only now and it's great ot see this fix ❤️ 
Question:
Should some simple e2e test be added (e.g. the simplest case for a Paragraph) to make sure this never regress? I can create a new issue, if no objections.

**Comment by Mamaduka** [comment]
> Should some simple e2e test be added (e.g. the simplest case for a Paragraph) to make sure this never regress? I can create a new issue, if no objections.

Yes, that would be helpful. Thank you, @afercia!

**Comment by afercia** [comment]
Sure, I created https://github.com/WordPress/gutenberg/issues/68853 and will see if I can reserve some time to it in the next days. Anyone please do feel free to beat me to it.
