### PR TITLE
Navigation block: Fix submenu colors for imported classic menus

### LINKED ISSUE #44235: Navigation color settings not working for submenus using classic menus
### Description

Navigation color settings not working for submenus using classic menus

### Step-by-step reproduction instructions

- Import the content from [theamdemo](https://theamdemo.wordpress.com/)
- Activate TT2 or any other block theme
- Select a background and text color for the navigation overlay and submenu items
- Check that the overlay is working as expected but the submenus don't have the colors selected applied.

In the video recording you will be able to see this behavior:

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1310626/190712386-92b9262e-7354-47bf-aa2c-f67333d6ad31.mp4

### Environment info

- WordPress 6.0.2
-  Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by talldan**
## What?
Fixes #44235

## Why?
The `isTopLevelLink` / `isTopLevelItem` attribute is important for rendering colors correctly in the navigation block.

The values weren't being set correctly when importing classic menus which resulted in the colors being wrong.

## How?
Ensure those values are set correctly when importing classic menus

## Testing Instructions
Prerequsites: 
- At least one classic menu that has nested items
- A block theme currently active

1. Open the site editor and select the navigation block 
2. Set some background and text colors for the submenu
3. Import a classic menu
4. Save
5. View the frontend

Expected: The submenu colors should be shown correctly.

### Before

Screen Shot 2022-09-20 at 1 02 23 pm

### After

Screen Shot 2022-09-20 at 1 01 46 pm

### CODE REVIEW

File: packages/block-library/src/navigation/menu-items-to-blocks.js [hunk 1]
```diff
@@ -166,6 +177,12 @@ function menuItemToBlockAttributes( {
 		...( target === '_blank' && {
 			opensInNewTab: true,
 		} ),
+		...( blockType === 'core/navigation-submenu' && {
+			isTopLevelItem: level === 0,
+		} ),
+		...( blockType === 'core/navigation-link' && {
+			isTopLevelLink: level === 0,
+		} ),
```
Comment (talldan) [inline packages/block-library/src/navigation/menu-items-to-blocks.js:185]: I can't believe it's named differently 😭

**Review by draganescu — APPROVED** [review]
Works great code LGTM 👏🏻

**Comment by matiasbenedetto** [comment]
:wave: Thanks for working on this.

The change is working only if I use the import menu function but I just select my existing Classic menu following the instructions of the issue https://github.com/WordPress/gutenberg/issues/44235 the colors for submenus are not applied. Is this expected?


image


image

**Comment by talldan** [comment]
> The change is working only if I use the import menu function but I just select my existing Classic menu following the instructions of the issue https://github.com/WordPress/gutenberg/issues/44235 the colors for submenus are not applied. Is this expected?

@matiasbenedetto That's a good point. I'm unsure why it doesn't work. There's an effect that sets the `isTopLevelLink` value, and I can see that it's triggered, but it doesn't show up in the editor as an unsaved change:
https://github.com/WordPress/gutenberg/blob/a41947b217a83bb3506b9605d624cc9ca888e2de/packages/block-library/src/navigation-link/edit.js#L513-L520

I'll investigate some more and make a separate issue for it, but will merge this in the meantime as it does move things in the right direction.

A workaround for users is to make a change to a menu item (add a character and then delete the character) and then save and the colours will show up.

**Comment by ockham** [comment]
I just cherry-picked this PR to the wp/6.1 branch to get it included in the next release: 3101140890
