### PR TITLE
Fix issue where the toolbar can be hidden for the block after a wide aligned image

### LINKED ISSUE #16519: Gutenberg - Transition [Transform] Bug on Reordering
I open now a Issue Ticket because more in some Themes the new transition animation it doesn't work fine in the latest version of Gutenberg. 

You have to change the Transform CSS. More details here: 
https://github.com/WordPress/gutenberg/pull/16065#issuecomment-510158699 

For example the new Twenty Nineteen Theme: https://github.com/WordPress/gutenberg/pull/16065#issuecomment-509231071

### PR DESCRIPTION
**Pull request by youknowriad**
closes #16519

**Testing instructions**

 - Insert a full aligned image
 - Insert a paragraph after the image
 - The paragraph's toolbar should not be cropped.

### CODE REVIEW

File: packages/block-editor/src/components/block-list/moving-animation.js [hunk 1]
```diff
@@ -43,7 +43,9 @@ function useMovingAnimation( ref, isSelected, enableAnimation, triggerAnimationO
 			x: previous ? previous.left - destination.left : 0,
 			y: previous ? previous.top - destination.top : 0,
 		};
-		ref.current.style.transform = `translate3d(${ newTransform.x }px,${ newTransform.y }px,0)`;
+		ref.current.style.transform = newTransform.x === 0 && newTransform.y === 0 ?
+			undefined :
+			`translate3d(${ newTransform.x }px,${ newTransform.y }px,0)`;
```
Comment (jorgefilipecosta) [inline packages/block-editor/src/components/block-list/moving-animation.js]: I wonder why applying a translate3d with all coordinates as 0 causes this problem, it seems unexpected. Supposedly translate3d(0,0,0) is a common "hack" to force hardware acceleration and makes CSS transitions smoother, but I did not expect a visual impact.

**Review by jorgefilipecosta — APPROVED** [review]
I was able to replicate the problem in master and it is solved on this branch.

File: packages/block-editor/src/components/block-list/moving-animation.js (hunk 1 above)
Comment (youknowriad) [reply packages/block-editor/src/components/block-list/moving-animation.js]: Yes, I don't know it seems to mess up with z-index somehow.
