### PR TITLE
Preview menu: Remove redundant "opens in a new tab" hidden text

### LINKED ISSUE #24386: Preview menu: the link text "Preview in new tab (opens in a new tab)" is redundant
**Describe the bug**

In WordPress 5.5, on large screens the Preview is now a menu with options for desktop, tablet, mobile, and traditional preview in a new browser tab.

The link for the preview in a new browser tab has this text:

"Preview in new tab (opens in a new tab)"

where the portion `(opens in a new tab)` is visually hidden. While it's a recommended practice to add this information to link that open in a new tab and don't inform users about the potentially unexpected new tab opening, in this specific case the link text _already inform users_ as it literally says: "Preview in new tab":

Screenshot 2020-08-05 at 17 16 57

Worth also reminding that modern browsers provide tools to check what the computed _accessible name_ (in this case: the link text) is, which makes checking this kind of things very easy:

Screenshot 2020-08-05 at 17 18 23

Above: Chrome dev tools: accessibility tab displaying the computed accessible name of the link.

In this case, the visually hidden text is unnecessary and redundant for screen reader users. It should be removed.

Looking at the implementation, not sure what is the preferred approach. `PostPreviewButton` accepts a `textContent` prop and fallbacks to a link text `Preview` if none is passed. So the default text does need the visually hidden text, while a more meaningful text passed via `textContent` _may_ not need it. Since this depends on the actual text passed via the prop, I'd tend to think the behavior can't be automated and maybe an additional, explicit, prop to render the visually hidden text would be the best option.

**Editor version (please complete the following information):**
- WordPress version: 5.5 RC 2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default.

### PR DESCRIPTION
**Pull request by kellychoffman**
Fixes: https://github.com/WordPress/gutenberg/issues/24386 

Text link already states that the link will open in a new tab, so this PR removes the visually hidden "(opens in a new tab)" text. (And yes, I realize this very description is redundant if you've read the title)

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
Before:

Screenshot 2020-08-07 at 09 21 17

After:

Screenshot 2020-08-07 at 09 20 40

Congrats on your first PR!

The test failure looks legitimate, I'll take a look and see if I can fix it.

**Comment by jasmussen** [comment]
It looks like the snapshots just needed updating. Usually whenever the markup of the UI changes, these need updating. I do it on the commandline using `npm run test-unit -- --updateSnapshot`, but I'm always happy to take a look.

File: packages/editor/src/components/post-preview-button/index.js [hunk 1]
```diff
@@ -207,12 +207,6 @@ export class PostPreviewButton extends Component {
 				{ this.props.textContent
 					? this.props.textContent
 					: _x( 'Preview', 'imperative verb' ) }
-				<VisuallyHidden as="span">
```
Comment (talldan) [inline packages/editor/src/components/post-preview-button/index.js:210]: It looks like there are a couple of other uses of `PostPreviewButton`, like in the `PostLockedModal`, and I think that only says 'Preview'.

An option could be to change the text everywhere to 'Preview in new tab', or make the VisuallyHidden text something that can be enabled/disabled through a prop..

Comment (jasmussen) [reply packages/editor/src/components/post-preview-button/index.js:210]: Great catch, Probably risky to change that phrasing because it will likely not scale to mobile interfaces with the length of the phrase. 

So we should probably restore the hint for that use case.

**Comment by kellychoffman** [comment]
> It looks like the snapshots just needed updating

Thanks! TIL.

File: packages/editor/src/components/post-preview-button/index.js (hunk 1 above)
Comment (afercia) [reply packages/editor/src/components/post-preview-button/index.js:210]: Yep, this was, in a way, mentioned on the issue:
> Looking at the implementation, not sure what is the preferred approach. PostPreviewButton accepts a textContent prop and fallbacks to a link text Preview if none is passed. So the default text does need the visually hidden text, while a more meaningful text passed via textContent may not need it. Since this depends on the actual text passed via the prop, I'd tend to think the behavior can't be automated and maybe an additional, explicit, prop to render the visually hidden text would be the best option.

**Comment by jasmussen** [comment]
I tried a thing in https://github.com/WordPress/gutenberg/pull/24427/commits/34a2d98587db84ac874ccb1d4041ef50deeaf0d1, to simply make the `VisuallyHidden` component part of the same condition that outputs the short verb. @talldan can you sanity check it?

**Comment by talldan** [comment]
@jasmussen Looks good! I'm not sure what that change in the unrelated snapshot file is though:
packages/dependency-extraction-webpack-plugin/test/__snapshots__/build.js.snap

**Comment by jasmussen** [comment]
Thanks for looking. That's curious indeed, I didn't even notice it. I'll try a good rebase and regenerate the snaps afterwards. Happy to know the fix is okay though 👍

**Comment by jasmussen** [comment]
I rebased, which removed the snapshots discrepancy.

I am however seeing a test failure locally, both on this branch and in master, that seems unrelated to this PR but might nonetheless cause tests to fail here:

```
Summary of all failing tests
 FAIL  packages/components/src/tooltip/test/index.js
  ● Tooltip › #render() › should ignore mouseenter on disabled elements

    expect(jest.fn()).not.toHaveBeenCalled()

    Expected number of calls: 0
```

**Comment by jasmussen** [comment]
Hooray, tests are passing!

**Comment by jasmussen** [comment]
Congrats on your first PR here, Kelly, and thank you!
