### PR TITLE
Fix RichText rerendering when it shouldn't

### LINKED ISSUE #12150: Browser gets frozen after pressing ENTER button
**Describe the bug**
I updated the last version of Gutenberg (4.5.0) this morning (10:00 am GMT +7). After updating, I try to write a post, it **gets frozen** when I press ENTER button **to create next paragraph**. Moreover, when I open the posted article and click to a paragraph to edit, then I **can't click to another** or the title again. Please check it and let me know if it not a bug (First, I think it's my computer problem but it was normal if I use Classic Editor or the old version of Gutenberg).

**To Reproduce**
1. Click 'Add new' to create a post
2. Write something in paragraph
3. Press 'Enter'
4. The browser's tab is frozen after 2 secs.

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser: Coc coc (Vietnamese's browser which is built on Chrome platform)
 - Version: 75.4.124 (32 bit)

### PR DESCRIPTION
**Pull request by atimmer**
closes #12150

## Description

The prepareEditableTree and onChangeEditableValue function stacks would have a new reference on every render. This prevents that by memoized the stack based on the previous stack and the newly added function.

## How has this been tested?

Tested using Yoast SEO. I am working on e2e tests to test that RichText's doesn't rerender too often.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
I confirm that this does fix the Yoast incompatibility issue.

File: packages/annotations/src/store/selectors.js [hunk 1]
```diff
@@ -4,6 +4,8 @@
 import createSelector from 'rememo';
 import { get, flatMap } from 'lodash';
 
+const emptyArray = [];
```
Comment (iseulde) [inline packages/annotations/src/store/selectors.js]: Minor: I think in other places we called this `EMPTY_ARRAY`.

File: packages/annotations/src/format/annotation.js [hunk 2]
```diff
@@ -115,6 +120,40 @@ function updateAnnotationsWithPositions( annotations, positions, { removeAnnotat
...
+} );
+
+/**
+ * Returns the annotations as a props object. Memoized to prevent re-renders.
+ *
+ * @param {Array} The annotations to put in the object.
+ *
+ * @return {Object} The annotations props object.
+ */
+const getAnnotationObject = memize( ( annotations ) => {
```
[the remark this answers is not in the document]
Comment (iseulde) [reply packages/annotations/src/format/annotation.js]: Agreed, this sounds better.

File: packages/annotations/src/store/selectors.js (hunk 1 above)
Comment (iseulde) [reply packages/annotations/src/store/selectors.js]: Wouldn't be bad to have the same comment: https://github.com/WordPress/gutenberg/blob/563ef41c663f163a725c2ef7e961b11ea6981f6e/packages/editor/src/store/selectors.js#L57-L66

File: packages/rich-text/src/register-format-type.js [hunk 3]
```diff
@@ -119,6 +120,14 @@ export function registerFormatType( name, settings ) {
 
 	dispatch( 'core/rich-text' ).addFormatTypes( settings );
 
+	const emptyArray = [];
+	const getFunctionStackMemoized = memize( ( previousStack = emptyArray, newFunction ) => {
```
Comment (iseulde) [inline packages/rich-text/src/register-format-type.js]: Would it work to keep the cache size to one?

Comment (iseulde) [reply packages/rich-text/src/register-format-type.js]: Also, why do both this and `prepareEditableTree` need to be memoized? Could use some more clarification.

Comment (youknowriad) [reply packages/rich-text/src/register-format-type.js]: Probably not as we need one per RichText I think.

File: packages/rich-text/src/register-format-type.js [hunk 4]
```diff
@@ -119,6 +120,14 @@ export function registerFormatType( name, settings ) {
 
 	dispatch( 'core/rich-text' ).addFormatTypes( settings );
 
+	const emptyArray = [];
```
Comment (iseulde) [inline packages/rich-text/src/register-format-type.js]: Same here.

File: packages/rich-text/src/register-format-type.js (hunk 3 above)
Comment (atimmer) [reply packages/rich-text/src/register-format-type.js]: I don't think so, because a different function could be returned based on `richTextIdentifier`/`blockClientId`.

**Comment by iseulde** [comment]
Just wondering, does this also fix https://github.com/WordPress/gutenberg/pull/11595#discussion_r231969644?

**Comment by youknowriad** [comment]
@iseulde In my testing it doesn't fix it completely

File: packages/rich-text/src/register-format-type.js (hunk 3 above)
Comment (iseulde) [reply packages/rich-text/src/register-format-type.js]: Just wondering because it's probably best to keep cache size as small as possible. I'm guessing the issue is just consecutive calls and nothing else.

**Comment by atimmer** [comment]
That is what I concluded too. It's probably not far away. I will dive into that further to completely fix it. But I thought that doesn't have to be in 4.5.1.

File: packages/rich-text/src/register-format-type.js (hunk 3 above)
Comment (iseulde) [reply packages/rich-text/src/register-format-type.js]: So how big is this cache going to grow?

Comment (iseulde) [reply packages/rich-text/src/register-format-type.js]: No way to cache per instance?

**Review by ellatrix — APPROVED** [review]

File: packages/rich-text/src/register-format-type.js (hunk 3 above)
Comment (youknowriad) [reply packages/rich-text/src/register-format-type.js]: That's a good question though

File: packages/annotations/src/format/annotation.js [hunk 5]
```diff
@@ -1,3 +1,8 @@
+/**
+ * External dependencies
+ */
+import memize from 'memize';
```
Comment (iseulde) [inline packages/annotations/src/format/annotation.js]: I don't see this added as a dependency.

**Review by ellatrix — DISMISSED** [review]

File: packages/annotations/package.json [hunk 6]
```diff
@@ -26,6 +26,7 @@
 		"@wordpress/i18n": "file:../i18n",
 		"@wordpress/rich-text": "file:../rich-text",
 		"lodash": "^4.17.10",
+		"memize": "^1.0.5",
```
Comment (iseulde) [inline packages/annotations/package.json]: I think we also need it on the server side.

Comment (youknowriad) [reply packages/annotations/package.json]: No we don't, there's no script for memize

Comment (iseulde) [reply packages/annotations/package.json]: Oh, cool then :)

File: packages/annotations/package.json [hunk 7]
```diff
@@ -26,6 +26,7 @@
...
 		"rememo": "^3.0.0",
 		"uuid": "^3.3.2"
```
Comment (gziolo) [inline packages/annotations/package.json]: PHP file needs to get updated, too :(

Comment (gziolo) [reply packages/annotations/package.json]: Nope, I'm wrong. :)

File: packages/annotations/src/store/selectors.js (hunk 1 above)
Comment (aduth) [reply packages/annotations/src/store/selectors.js]: > Minor: I think in other places we called this `EMPTY_ARRAY`.

Related guideline: https://github.com/WordPress/gutenberg/blob/master/docs/contributors/coding-guidelines.md#constants
