### PR TITLE
Inserter: Expand matching categories when searching

### LINKED ISSUE #7046: Inserter search should remove the accordions and show all the results
**Describe the bug**

The inserter search results should display all the available results without requiring users further actions. Instead, since the inserter now uses accordion, some results are hidden meaning they're within the collapsed accordions.

- click the main Add Block button to invoke the Inserter
- search, for example, for "embed"
- this is what you will see:

screen shot 2018-05-31 at 11 31 02

The Custom HTML block has a keyword "embed" (aside: why?) and will be displayed in the accordion expanded by default.

The real embed you were looking for is hidden within the collapsed accordion.

Depending on the search term, there may be various collapsed accordions:

screen shot 2018-05-31 at 11 50 04

Regardless of potential inconsistencies with search keywords, I'd say a better used experience would be showing all the results by default without requiring users further actions.

In the previous version, the inserter did so (of course, there were no accordions):

screen shot 2018-05-31 at 11 35 31

Not saying Gutenberg should necessarily follow what others do, but other platforms completely remove any division in groups or category titles and the like, and just show the search results.

### PR DESCRIPTION
**Pull request by mcsf**
## Description
Fixes #7046 by expanding accordions containing blocks matching a search term.

## How has this been tested?

Per the parent issue:

1. Click the main Add Block button to invoke the Inserter
1. Search, for example, for "embed"
1. Expect to see results akin to:

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by aduth** [comment]
>Fixes #7046 by expanding accordions containing blocks matching a search term.

Based on the implementation, I think it'd be more accurate to say that it expands all accordions when filtering, regardless of whether it contains a matching block?

File: editor/components/inserter/menu.js [hunk 1]
```diff
@@ -207,7 +208,7 @@ export class InserterMenu extends Component {
 							<PanelBody
 								key={ category.slug }
 								title={ category.title }
-								opened={ isPanelOpen( category.slug ) }
+								opened={ isSearching || isPanelOpen( category.slug ) }
```
Comment (aduth) [inline editor/components/inserter/menu.js]: I guess we could want this to be considered as part of the implementation of `isPanelOpen`. Small thing.

**Review by aduth — APPROVED** [review]
Looks good 👍

File: editor/components/inserter/menu.js (hunk 1 above)
Comment (mcsf) [reply editor/components/inserter/menu.js]: Since `isPanelOpen` is used elsewhere, it seemed a bit cleaner to keep it separate.

**Comment by aduth** [comment]
Observed odd behavior [noted in Slack today](https://wordpress.slack.com/archives/C02QB2JS7/p1528732368000611): The accordions are still shown as collapsible controls, but do not do anything when a search is made and the user interacts with the collapse panels.
