### PR TITLE
Fix content loss when ungrouping template parts or reusable blocks

### LINKED ISSUE #36788: Grouping and ungrouping the Header block results in loss of data
### Description

When you group the `Header` block and then ungroup it, all content inside the `Header` is lost and only the `Header` block itself remains on the page.

Apparently, the contents of the template part are lost. There is no way to re-select a template.

Adding another `Header` immediately below the affected header does not open the template part selector, resulting in another empty header. I'm not sure if this is related to the same problem or another issue.

### Step-by-step reproduction instructions

1. Open the block editor;
2. Insert the `Header` block;
3. Create a new group with the `Header` inside;
4. Click on the `...` on the newly created group;
5. Click "Ungroup".

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26530524/143089756-27a84918-0a2b-493f-9660-4dd4af13fcb6.mov

### Environment info

- WordPress 5.8.2;
- Gutenberg 11.9.1.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by youknowriad**
Closes #36788 
Alternative to #37274 

There are two low level bugs that create this issue:

 - When the template part or reusable block remounts, the `onChange` handler from `useBlockSync` is called. Ideally it shouldn't be because that component will be unmounted a few milliseconds later. This is hard to solve because the store subscriptions run from the deepest component to the top level ones. Basically, it's another kind of redux zombie bug. I'm not sure we can solve that part of the bug.
 - The other part is that `blocks` shouldn't be emptied in the first place when "moving" the block to another position, this happens because controlled blocks are supposed to retrieve their block again from the "core" store when they remount again but since onChange is called (first bug above) the value in "core" store is wrong (empty blocks). I'm fixing this part of the bug in this PR: I'm making sure if a controlled block moves to a new position, it retains its inner blocks from the previous position.

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]
Thank you, Riad. It works like a charm.

https://user-images.githubusercontent.com/240569/145569789-2866f5fa-205f-4fdf-a848-648e2eea803c.mp4

**Comment by Mamaduka** [comment]
> When the template part or reusable block remounts, the onChange handler from useBlockSync is called. Ideally it shouldn't be because that component will be unmounted a few milliseconds later. This is hard to solve because the store subscriptions run from the deepest component to the top level ones. Basically, it's another kind of redux zombie bug. I'm not sure we can solve that part of the bug.

Is this a reason why my example fix was failing?

We also have another issue with controlled inner blocks and now I'm curious if this might be related - #36937.

File: packages/block-editor/src/store/reducer.js [hunk 1]
```diff
@@ -369,9 +369,14 @@ const withBlockTree = ( reducer ) => ( state = {}, action ) => {
 					...omit(
 						newState.tree,
 						action.replacedClientIds.concat(
-							action.replacedClientIds.map(
-								( clientId ) => 'controlled||' + clientId
-							)
+							// controlled inner blocks are only removed
+							// if the block don't move to another position
```
Comment (Mamaduka) [inline packages/block-editor/src/store/reducer.js]:
```suggestion
							// Controlled inner blocks are only removed
							// if the block doesn't move to another position
```

Nit

**Comment by ntsekouras** [comment]
It's interesting that with this PR, if we group and then ungroup, we don't have the disappearing issue(#36937)

**Comment by Mamaduka** [comment]
@ntsekouras Do you mean if we group/ungroup before accessing focus mode or inside the focus mode?

**Comment by ntsekouras** [comment]
>@ntsekouras Do you mean if we group/ungroup before accessing focus mode or inside the focus mode?

Before the isolated editing view

**Comment by youknowriad** [comment]
@ntsekouras potential fix for the related issue here https://github.com/WordPress/gutenberg/pull/37283

**Review by ntsekouras — APPROVED** [review]
🚀

**Comment by Mamaduka** [comment]
Maybe we should add e2e tests that cover the grouping/ungrouping of inner block controllers. I've to call it a day soon, but happy to create a new test on Monday. What do you think?

**Comment by youknowriad** [comment]
> Maybe we should add e2e tests that cover the grouping/ungrouping of inner block controllers. I've to call it a day soon, but happy to create a new test on Monday. What do you think?

Works for me. Thanks @Mamaduka
