### PR TITLE
Fix: Crash after undo with top toolbar on

### LINKED ISSUE #24515: Ghost undo entry and top toolbar crash
When you first click into the editor it seems to create a 'ghost' undo item:

image

If you undo this item, and have 'top toolbar' enabled, the toolbar displays a mystery ellipsis where the format toolbar should go:

image

If you click this ellipsis the editor crashes:

`An error occurred while running 'mapSelect': Cannot read property 'name' of null`

This occurs in `BlockSettingsMenuControlsSlot`

There's a secondary error:

`onCopy is not a function` in ClipboardButton

Tested on plugin 8.7.1 and the version in WP 5.5.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Fixes: https://github.com/WordPress/gutenberg/issues/24515

## How has this been tested?
I repeated the steps described in https://github.com/WordPress/gutenberg/issues/24515 and verified there was no crash anymore.

### CODE REVIEW

File: packages/block-editor/src/components/block-settings-menu-controls/index.js [hunk 1]
```diff
@@ -21,7 +21,10 @@ const BlockSettingsMenuControlsSlot = ( { fillProps, clientIds = null } ) => {
 			);
 			const ids =
 				clientIds !== null ? clientIds : getSelectedBlockClientIds();
-			return map( getBlocksByClientId( ids ), ( block ) => block.name );
+			return map(
+				compact( getBlocksByClientId( ids ) ),
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-settings-menu-controls/index.js:25]: I wonder if the selector itself should clear the empty blocks. Not sure though.
