### PR TITLE
Fix renaming in Site View sidebar rename saves all edits for Template Parts and Navigation Menus

### LINKED ISSUE #52294: Site View > Navigation: renaming menu saves all menu changes
### Description

While testing 6.3 Beta 3, I noticed that when using the Site View > Navigation section, if I rename the menu, all menu changes are saved, even if I didn't confirm that change. 

### Step-by-step reproduction instructions

1. Open the Site Editor
2. Head to Navigation
3. Make changes to the menu, like rearranging items or deleting.
4. Using the three dot menu, rename the menu and notice that all of the changes are saved.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/26996883/ba4fd202-5d0d-4138-8ef7-ec6a9fc06104

### Environment info

- 6.3 Beta 3
- No GB
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by getdave**
## What?

Only persists the title field of Template Parts and Navigation Menus being edited when they are renamed in the Site View sidebar.

Fixes https://github.com/WordPress/gutenberg/issues/52294

## Why?

Currently the entire record is saved being that if you make some edits to the entity and then rename, _all_ of your changes are saved despite you not confirming.

This PR changes this so that only the new title is changed and other edits are left for the user to confirm.

## How?

Only saves the `title` field of the entity. This necessitates using the `__experimentalSaveSpecifiedEntityEdits` action to allow us to pass a subset of fields to be saved.

Its also necessary to update the action to ensure the `recordKey` is _always_ passed. This is because `saveEntityRecord` will attempt to save a _new_ record rather than update the existing one unless the `recordKey` is passed as part of the 3rd `record` argument.

https://github.com/WordPress/gutenberg/blob/bc663f6418c2775b24b3e62a7c639f2d72eb1b51/packages/core-data/src/actions.js#L637-L641

This is because `saveEntityRecord` interrogates the passed `record` for an `id` property

https://github.com/WordPress/gutenberg/blob/bc663f6418c2775b24b3e62a7c639f2d72eb1b51/packages/core-data/src/actions.js#L481-L482

...and `__experimentalSaveSpecifiedEntityEdits` only passes a subset of the record:

https://github.com/WordPress/gutenberg/blob/bc663f6418c2775b24b3e62a7c639f2d72eb1b51/packages/core-data/src/actions.js#L786-L797

This PR updates `__experimentalSaveSpecifiedEntityEdits` to also pass the `recordKey`.

## Testing Instructions

- Create x2 Navigation Menus with some items in each. You should be easily able to identify the order of the menu items so name them `First` and `Second` ...etc.
- Click through to one of your Navigation Menus.
- Order the items in the menu so that `Second` is _before_ `First` but do _not_ save.
- Verify the "Save" button at the bottom of the sidebar is active.
- Now rename your Navigation Menu.
- You should still see the "Save" button at the bottom of the sidebar is active indicating the menu _item_ edits have not been saved.
- Refresh/reload the page.
- See that your menu has been renamed but that the menu edits were _not_ persisted and the _original_ menu item order is still in evidence.

----

- Do the same for Template Parts
- Create Custom Template Part
- Add content inside where you can tell the order of items such as two paragraphs with `first` and `second` as the content.
- Do NOT save.
- Go back to `Patterns` library and click on `Manage all Template Parts`
- Use options menu to `Rename`.
- Rename to whatever and confirm.
- Return to editing the Template Part
- See the entity save flow is still prompting you to Save.
- Reload - see that the edits you made to the Template Part are lost (i.e. were not persisted) but the renaming of the title is still present.

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/444434/85217d8b-ff8e-42bb-9010-75f4d785b445

### CODE REVIEW

File: packages/core-data/src/actions.js [hunk 1]
```diff
@@ -789,6 +789,11 @@ export const __experimentalSaveSpecifiedEntityEdits =
 				editsToSave[ edit ] = edits[ edit ];
 			}
 		}
+
+		// Provide recordKey to saveEntityRecord to avoid creating a new record
+		// and instead update the existing record.
+		editsToSave.id = recordId;
```
Comment (getdave) [inline packages/core-data/src/actions.js]: Another option is we revert this change and instead pass the `id` in the call to `saveSpecifiedEntityEdits` from the Navigation sidebar hooks.

I noticed that `__experimentalSaveSpecifiedEntityEdits` is used elsewhere and I'm nervous about modifying it this close to a release.

File: packages/edit-site/src/components/sidebar-navigation-screen-navigation-menu/use-navigation-menu-handlers.js [hunk 2]
```diff
@@ -65,8 +65,10 @@ function useSaveNavigationMenu() {
 		};
 	}, [] );
 
-	const { editEntityRecord, saveEditedEntityRecord } =
```
Comment (getdave) [inline packages/edit-site/src/components/sidebar-navigation-screen-navigation-menu/use-navigation-menu-handlers.js:68]: Question: should we rename `useSaveNavigationMenu` to `useUpdateNavigationMenu`? Really we should have 

`create` and `update` actions which both defer to a low level `save` action under the hood. This usage of `save` in actions which have varying behaviour is quite confusing.

**Comment by draganescu** [comment]
Can we not save anything until the button in the sidebar is clicked?

**Comment by getdave** [comment]
> Can we not save anything until the button in the sidebar is clicked?

We can but that did seem right to me. I've said "Rename" and I've clicked "Ok". Then I leave the Site Editor and come back and my Navigation renaming didn't happen.

**Comment by draganescu** [comment]
I think it's a break of expectations that other things are added to the queue of things to be saved and this one is not. It does feel a bit weird that you get a dialog, but think about this: there are changes where you enter the frame, open up the inspector, update stuff, exit the inspector and they're not saved, but added to the queue.

The more I think about it the more I am convinced we should not save directly anything in this case, just put it in the queue of updates.

**Comment by getdave** [comment]
I'm not saying you're necessarily wrong but worth considering the options menu behavioural consistency (or lack of!):

- `Duplicate` - happens immediately
- `Delete` - happens immediately
- `Rename` - we're suggesting would have only once you click the "Save" button.

What do @WordPress/gutenberg-design think about the two proposals for renaming flow:

1. Retain existing flow where re-naming results in the menu being renamed and immediately saved without need for further interaction with saving flow.
2. [Andre's proposal](https://github.com/WordPress/gutenberg/pull/52373#issuecomment-1623599323), whereby renaming simply pushes the rename as one more edit into the entity saving flow and you are required to manually hit the `Save` button in the sidebar to persist.

**Comment by jameskoster** [comment]
Renaming occurs instantly for templates and patterns/template parts. I'd be inclined to aim for consistency with those experiences.

**Comment by draganescu** [comment]
Cool @jameskoster :) in that case this solves the problem correctly, my only remaining gripe is that we need to update that low level action for this .. how do patterns and template parts do it?

File: packages/edit-site/src/components/sidebar-navigation-screen-navigation-menu/use-navigation-menu-handlers.js (hunk 2 above)
Comment (draganescu) [reply packages/edit-site/src/components/sidebar-navigation-screen-navigation-menu/use-navigation-menu-handlers.js:68]: I think doing create and update inside save is a common DX pattern, and also a matter of personal taste? Ideally we'd have all three available 🤷🏻

**Comment by getdave** [comment]
> how do patterns and template parts do it?

They don't. They display same bug 😆

**Comment by getdave** [comment]
Ok @scruffian @draganescu please can you review for both TPs and Navigations 🙏

File: packages/edit-site/src/components/template-actions/rename-menu-item.js [hunk 3]
```diff
@@ -42,11 +44,14 @@ export default function RenameMenuItem( { template, onClose } ) {
 			onClose();
 
 			// Persist edited entity.
-			await saveEditedEntityRecord(
+			await saveSpecifiedEntityEdits(
 				'postType',
 				template.type,
 				template.id,
-				{ throwOnError: true }
+				[ 'title' ], // only save title to avoid persisting other edits.
```
Comment (scruffian) [inline packages/edit-site/src/components/template-actions/rename-menu-item.js]:
```suggestion
				[ 'title' ], // Only save title to avoid persisting other edits.
```

**Review by scruffian — APPROVED** [review]
This works as advertised and the code looks good to me.

**Comment by Mamaduka** [comment]
I was reading the recent conversation in https://github.com/WordPress/gutenberg/pull/51477#pullrequestreview-1491279875, and it reminded me of this PR/issue.

Maybe we should only persist changes via the main save button.

## Why

* This is how we already do it when a user renames Navigation or Template Part in the editors.
* No other edit action is immediately persisted.

> We can but that did seem right to me. I've said "Rename" and I've clicked "Ok". Then I leave the Site Editor and come back and my Navigation renaming didn't happen.

@getdave, the same would happen when the user re-arranges navigation in the sidebar, then leaves the editor and ignores the unsaved changes dialog.

**Comment by draganescu** [comment]
Given I merged this and _after that_ I saw @Mamaduka 's comment - @jameskoster your argument was about consistency, would you be in favor to change them all to save using the main save button? Is there anythingin the UI that should also be updated to reflect this? (I am thinking that the way the modal presents the actions it's expetced to do a "destructive" action).

**Comment by scruffian** [comment]
The other factor for persisting the change immediately is that duplicate and delete happen immediately. To my mind when I open a modal, I am entering a new context and so I expect the changes to be saved immediately.

**Comment by getdave** [comment]
Just a quick note to say we did [discuss this above](https://github.com/WordPress/gutenberg/pull/52373#issuecomment-1624940985).

**Comment by jameskoster** [comment]
> To my mind when I open a modal, I am entering a new context and so I expect the changes to be saved immediately.

I think that's a reasonable heuristic and I know @SaxonF has expressed a similar sentiment. 

I also think there's a nuance to consider in terms of 'site view' (the dark material) versus 'edit view' (the fullscreen editor). The former generally feels like a file explorer where you'd expect renaming to be an instantaneous action. The latter is like opening a file where it's more likely you'd expect changes to be held until you save.

There's also a question about the type of change and specifically whether it will effect what visitors see on the frontend. For instance renaming a pattern or a navigation menu has no impact on the frontend, so feels like a low risk change that is safe to save straight away. Whereas editing the menu itself _will_ effect the frontend (if the menu it in use), so the change probably shouldn't be instantaneous.  

Of course none of this is set in stone, but what we have currently feels satisfactory to me until we nail down these concepts more broadly.
