### PR TITLE
CustomGradientPicker: improve initial state UI

### LINKED ISSUE #42994: GradientPicker: improvements wishlist
This is a wish list of improvements for the `GradientPicker` component (& related components) that I came up with while fixing popover regressions:

### Slow rendering performance

This can be observed especially when dragging a control point in the editor:

https://user-images.githubusercontent.com/1083581/182951729-34eba57c-0c46-4a11-bffd-5354fb4bb718.mp4

### ~Improve the initial state when there's no gradient set~

- ~The semi-transparency given to the whole gradient bar is weird, especially when clicking on an insertion point: in that case, the popover is also semi transparent, and is rendered below the rest of the controls (this is a side-effect caused by the opacity rule, which creates a new stacking context for the gradient bar)~
- ~I also find it weird that the "no gradient set" state is represented by the value of the gradient being set to the default one — in my mind, that value should be `undefined` (or `null`), but definitely not a gradient. The visual state of the component should be also adjusted to clearly show that there's no gradient being set~

https://user-images.githubusercontent.com/1083581/182949019-584c1ad3-717b-41bd-a383-5b354c1e6642.mp4

Done as part of https://github.com/WordPress/gutenberg/pull/49146

### ~Get rid of `__experimentalHasMultipleOrigins` prop~

~We should agree on the best way to implement this feature, and remove the experimental prop. I'm personally not a fan of props like `__experimentalHasMultipleOrigins` that change the meaning of other props (in this case, `gradients`). Maybe we don't need `__experimentalHasMultipleOrigins` at all, and we can just infer the information from the shape of the gradients prop~

Done in https://github.com/WordPress/gutenberg/pull/46315

### Get rid of the `__experimentalIsRenderedInSidebar` prop

We should avoid props that introduce a tight coupling with the editor. First we should understand exactly what changes when this prop is specified, and then find alternatives to get to the same results

### Component structure is messy

We should tidy up components and folder structures for the GradientPicker-related components (GradientPicker, CustomGradientPicker, ColorPalette, ColorListPicker, CircularOptionPicker, ColorIndicator....). These components feel very intertwined / tightly coupled and partially overlapping. (related to https://github.com/WordPress/gutenberg/issues/35093 )

### ~Sometimes clicking on the GradientPicker in the editor doesn't result in a new control point being added~

~I can't reproduce this unexpected behavior consistently, but it's definetly something that we should investigate (it could be related to the low rendering performance listed above)~

Done as part of https://github.com/WordPress/gutenberg/pull/49146

### PR DESCRIPTION
**Pull request by ciampo**
## What?

Requires #48929 to be merged first
Part of #42994

Improve `CustomGradientPicker`'s initial UI state and interaction:

- preserve the 0.4 opacity of the gradient bar when no gradient is set, but make the control points and the related color pickers always at full opacity
- add checkered background to better show semi-transparent gradients
- improve the code around how the component checks if it has a gradient

## Why?

Improve the component's UX

## How?

- Opacity improvements have been applied by creating a new `div` element dedicated to display the `background-color`, and applying some CSS changes to force the controls on the bottom row to render with a lower stacking index than the gradient bar
- Code changes around the default gradient value:- This also improved the `hasGradient` logic: previously the component would think that it didn't a gradient set if, as a coincidence, the user chose a gradient value that was the same as the default gradient

## Testing Instructions

Interact with the component on Storybook and in the editor (for example, in the Site Editor > Global Styles Sidebar > Colors  > Palette > "Gradient" tab > Create a new custom gradient)
- Make sure that, when clicking an insertion point, the related color picker is 100% opaque and is displayed on top of the rest of the UI
- Make at least one of the color stops partially transparent, make sure that the checkered background shows in the gradient bar
- Make sure that the component otherwise behaves like on `trunk`

## Screenshots or screencast 

| | trunk (before) | This PR (after) |
|---|---|---|
| z-index and opacity of insertion points and color picker popover | Screenshot 2023-03-16 at 19 36 46 | Screenshot 2023-03-16 at 19 56 43 |
| transparent color points (notice the chequered gradient bar) | Screenshot 2023-03-16 at 19 37 01 | Screenshot 2023-03-16 at 19 57 07 |

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
Seems good to me. The main visible change is the transparency one. I think we might separately want to revisit that texture, there were some contexts in which it didn't work too well. But seems fine to go with for now as it's at least the same texture.

File: packages/components/src/custom-gradient-picker/utils.ts
Comment (chad1008) [inline packages/components/src/custom-gradient-picker/utils.ts:1]: Nice, I like this change a lot. Really simplifies parsing what the utility is actually accomplishing.

File: packages/components/src/custom-gradient-picker/index.tsx [hunk 1]
```diff
@@ -148,19 +147,19 @@ export function CustomGradientPicker( {
...
 	const background = getLinearGradientRepresentation( gradientAST );
-	const hasGradient = gradientAstValue !== DEFAULT_GRADIENT;
+
 	// Control points color option may be hex from presets, custom colors will be rgb.
 	// The position should always be a percentage.
 	const controlPoints = gradientAST.colorStops.map( ( colorStop ) => {
 		return {
 			color: getStopCssColor( colorStop ),
-			// Although it's already been checked by `hasUnsupportedLength` in `getGradientAstWithDefault`,
+			// Although it's already been checked by `hasUnsupportedLength` in `getGradientAst`,
```
Comment (chad1008) [inline packages/components/src/custom-gradient-picker/index.tsx]: I notice you've changed this comment, but the function returning `gradientAST` is still named `getGradientAstWithDefault`. Did you mean to rename the function now that it's handling default gradients differently?

**Review by chad1008 — COMMENTED** [review]
This looks good and tests well to me. I did leave one question in the inline comments.

File: packages/components/src/custom-gradient-picker/index.tsx (hunk 1 above)
Comment (ciampo) [reply packages/components/src/custom-gradient-picker/index.tsx]: I did rename the function at some point, but then I changed my mind and restored the original name. Although I forgot to update the comment — thank you for catching it!
