### PR TITLE
Hide the hidden navigation block

### LINKED ISSUE #50639: Keyboard Navigation Broken on List View Sidebar
### Description

The keyboard navigation for the list view sidebar only works with Tab presses, but skips to[ the hidden navigation block](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/sidebar-navigation-screen-navigation-menus/navigation-menu-content.js#L194-L198) that is currently required for the navigation.

### Step-by-step reproduction instructions

1. Go to the Site Editor
2. Click Navigation from the left sidebar
3. Try to navigate the menu using your keyboard

### Screenshots, screen recording, code snippet

Sidebar List View Navigation Keyboard Broken

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by draganescu**
## What?

Fixes #50639

## Why?

We use a hidden navigation block to allow the edits to the navigation entity to be caught by the entity system and also to allow the effects of the block to run. This block was hidden using `VisuallyHidden` which is the wrong component for this case.

Here we want to really hide the block, not hide it visually.

## How?

Instead of using `VisuallyHidden` I just use a `div` that is set to `display:none`.

## Testing Instructions

1. Go to the side editor
2. Open the navigation sidebar screen
3. Tab around
4. You should not be able to tab into a navigation block

## Screenshots or screencast 

N/A

### CODE REVIEW

**Comment by jeryj** [comment]
Unfortunately, using `display: none;` causes an issue with [the Link Control popover on submenus](https://github.com/WordPress/gutenberg/issues/50536). Maybe that could be solved in a different way alongside `display: none;`?

**Comment by draganescu** [comment]
Either that or we stop using LinkUI in that sidebar :)

**Comment by draganescu** [comment]
Now that we don't use LinkControl anymore we could apply this fix, as the hidden block shows a horizontal scrollbar when the user has the top toolbar setting toggled on.

**Review by scruffian — APPROVED** [review]
This looks like a good way forward now.

File: packages/edit-site/src/components/sidebar-navigation-screen-navigation-menus/navigation-menu-content.js [hunk 1]
```diff
@@ -106,11 +105,11 @@ export default function NavigationMenuContent( { rootClientId } ) {
 					showAppender={ false }
 				/>
 			) }
-			<VisuallyHidden aria-hidden="true">
+			<div className="edit-site-sidebar-navigation-screen-navigation-menus__helper-block-editor">
```
Comment (getdave) [inline packages/edit-site/src/components/sidebar-navigation-screen-navigation-menus/navigation-menu-content.js:108]: I wonder whether this code should have included a comment to explain _why_ we did this?

I know we have Git history but is this covered by any tests to avoid regressions?

Comment (MaggieCabrera) [reply packages/edit-site/src/components/sidebar-navigation-screen-navigation-menus/navigation-menu-content.js:108]: maybe we should keep the aria-hidden=true too?
