### PR TITLE
Replace, on editing a navigation link, the current label with the title of page or post

### LINKED ISSUE #18695: Changing navigation link doesn't update the label
**Describe the bug**
When changing the link of a navigation menu item to a post or page the label of the link does not update to the one of the selected post or page.

**To reproduce**
1. Make a post
2. Add an empty navigation menu
3. Add a navigation item by searching for a page
4. Observe the label
5. Click on edit link button and then on change
6. Search for a different page
7. Select it
8. Observe the label: bug.

**Expected behavior**
The new selected page or post should be reflected by a new label.

**Screenshots**
menu-label-not-updating

### PR DESCRIPTION
**Pull request by draganescu**
## Description
Closes #18695

## How has this been tested?
Tested locally.

## Screenshots 

navigation-link-update

## Types of changes
Small non-breaking update of the navigation link component that sets the label on link change depending on whether the link is a page or post, or just a link.

### CODE REVIEW

File: packages/block-library/src/navigation-link/edit.js [hunk 1]
```diff
@@ -167,7 +167,10 @@ function NavigationLinkEdit( {
 							} = {} ) => setAttributes( {
 								title: escape( newTitle ),
 								url: newURL,
-								label: label || escape( newTitle ),
+								label: (
+									( newTitle !== '' && newTitle !== newURL && label !== newTitle ) ?
```
Comment (tellthemachines) [inline packages/block-library/src/navigation-link/edit.js]: If I try replacing the link with a url without explicitly typing the protocol, it will replace the label. This seems to be because the protocol gets added automatically to the url, but not to the title, so url `!==` title. So say I have a nav item with the manually added label `Personal website`. If I edit the link to `https://tellthemachines.com`, the label doesn't change. BUT if I edit the link to `tellthemachines.com`, the label then changes to `tellthemachines.com`. 

Perhaps we could remove the protocol from newUrl before making the comparison with newTitle?

Comment (draganescu) [reply packages/block-library/src/navigation-link/edit.js]: wow good catch :) I'll see to it asap!

Comment (draganescu) [reply packages/block-library/src/navigation-link/edit.js]: fixed!

File: packages/block-library/src/navigation-link/edit.js [hunk 2]
```diff
@@ -177,7 +177,17 @@ function NavigationLinkEdit( {
 								} = {} ) => setAttributes( {
 									title: escape( newTitle ),
 									url: newURL,
-									label: label || escape( newTitle ),
+									label: ( () => {
+										const normalizedTitle = newTitle.replace( /http(s?):\/\//gi, '' );
+										const normalizedURL = newURL.replace( /http(s?):\/\//gi, '' );
+										if (
+											newTitle !== '' &&
+											normalizedTitle !== normalizedURL &&
```
Comment (tellthemachines) [inline packages/block-library/src/navigation-link/edit.js]: Hmmm, this might need a bit more tweaking. Now, adding a new nav item with just a url doesn't automatically fill in the label field. Or is that expected behaviour?

Comment (draganescu) [reply packages/block-library/src/navigation-link/edit.js]: It is expected because there is no label and we assume the label already there is better than replacing it with a raw link.

**Review by tellthemachines — APPROVED** [review]
All good then! Approving.
