### PR TITLE
Revert: Rich text: copy tag name on internal paste

### LINKED ISSUE #53422: Copy/paste handler not working in RichText component in block
### Description

If there is a RichText component in a block, such as caption text, the copy/paste handler does not seem to work on that RichText.

- This problem is not reproduced when the block itself is a RichText component, such as a paragraph block.
- I have tested on Windows OS and this problem occurs in Chrome and not in Firefox.
- This problem occurs when the latest Gutenberg is enabled.

It would be great if you could test this issue, especially on MacOS, as the results may vary depending on the OS and browser.

### Step-by-step reproduction instructions

- Insert a block that contains a RichText component.
- Enter text in the RichText component. For example, the caption in the Image block, cells, and caption in the Table blocks, etc.
- Press the `Ctrl + C` key. Here, the text should be saved to the clipboard.
- Press the `Ctrl + V` key elsewhere. In certain browsers, the text should not be pasted.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/5da0b42c-02f3-4ed1-8465-d1f76dde3e14

### Environment info

- Gutenberg version: 16.4.0-rc.1
- Browser:
  - Chrome 115.0.5790.171: This problem occurs
  - Firefox 115.0.3: This problem does not occur

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

This reverts #48254.
Fixes #53422
See https://github.com/WordPress/gutenberg/pull/53453#issuecomment-1706687896

Sorry for the problems this introduced. And sorry to remove the new behaviour, I'll try to find a different way to do it at some point.

## Why?

#48254 introduced new copying behaviour, copying the rich text wrapper tag for context when pasting. For example it allow us to retain the heading tag when pasting into an empty paragraph. But a fundamental problem is that the rich text tags could really be anything: e.g. quote has a cite rich text area, so copying the cite wrapper doesn't make sense.

Also think about instances where the structure matters: details block with rich text summary, you can't just copy the wrapper tag (summary) on its own.

It seems like we need to somehow check wether the rich text element is a full block or not. Only then it makes sense because the HTML can always be parsed as a block. Let's try that in a follow up.

### CODE REVIEW

**Review by t-hamano — APPROVED** [review]
LGTM !

- Pasting heading text into an empty paragraph will not convert it into a heading (which is what is expected in this PR)
- Formatting is preserved when paragraph text containing inline formatting is pasted into inline rich text.
- Formatting is preserved when pasting inline rich text containing inline formatting into an empty paragraph.
- Tested with Chrome and Firefox on Windows OS.

File: packages/block-editor/src/components/rich-text/use-paste-handler.js [hunk 1]
```diff
@@ -104,6 +104,20 @@ export function usePasteHandler( props ) {
...
+			// pasted content and remove inline styles.
+			if ( isInternal ) {
+				const pastedValue = create( {
+					html,
+					preserveWhiteSpace,
+				} );
+				addActiveFormats( pastedValue, value.activeFormats );
+				onChange( insert( value, pastedValue ) );
+				return;
+			}
```
Comment (youknowriad) [inline packages/block-editor/src/components/rich-text/use-paste-handler.js:120]: This change here introduced a regression. Basically if you have a plain link in your paragraph for instance, and you cut the link and paste it over some text to create a real link, the link won't be created.

Comment (ellatrix) [reply packages/block-editor/src/components/rich-text/use-paste-handler.js:120]: This is just reverting https://github.com/WordPress/gutenberg/pull/48254/files#diff-11720f5193f80b98003f574708df7d6107ff4f286b6a5c31f66dce1ef73b5123L154, but rebased with the multi line stuff removed 🤔

Comment (ellatrix) [reply packages/block-editor/src/components/rich-text/use-paste-handler.js:120]: I think the regression is caused by the change in order here #55195
