### PR TITLE
Block registration: Fix shared defaults between different blocks

### LINKED ISSUE #20524: Block Types registered with no attributes end up "sharing" attributes list.
**Describe the bug**
If you register block types with no attributes (not an empty list; if you leave out the attributes key entirely), they will "share" an attributes list should any of them be modified by filters.

**To reproduce**
1. Register a block type, leave out the attributes entry.
2. Register a second block type, same way, but with a support like `align` specified.
3. Check the resulting WPBlock objects, the first one now has the `align` attribute, and an equality check confirms that the attributes list is the same object on both.

**Expected behavior**
The first block should not have the `align` attribute registered.

**Additional context**
Tested on WordPress 5.3.2 with and without the Gutenberg plugin.

-----

A use case would be if you're registering multiple simpler block types that legitimately doesn't need unique attributes (such as a custom grouping/wrapping block), but supports features that add attributes to that block type during registration (such as align or a custom feature).

I'm currently getting around this by adding an explicit empty attributes list to all my block definitions. The other option is to have my filters that add attributes simply assign to a new object every time, but that wouldn't prevent issues caused by the hooks in the block-editor package.

This issue could also apply to the keywords list, since any blocks that don't register one end up "sharing" the same array, but filters adding keywords to blocks is a pretty niche sitation.

The issue is due to `DEFAULT_BLOCK_TYPE_SETTINGS` being defined with the empty attributes object and keywords array, rather than the defaults being delared on each call of registerBlockType (though doing it that way probably causes it's own hiccups/annoyances).

### PR DESCRIPTION
**Pull request by marekhrabe**
## Description

I've added a failing test for the issue described. The severity of this bug shows as it also breaks 4 other unrelated tests, despite the filter being auto-removed and limited to a specific block. 

I have addressed it by calling `cloneDeep` on the object `DEFAULT_BLOCK_TYPE_SETTINGS` before it is applied as a default in `registerBlockType`. 

Tests are all green now, including the new one testing mutations of default attributes.

Fixes #20524

## How has this been tested?
- added a new unit test `npm run test-unit -- packages/blocks/src/api/test/registration.js`

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.

### CODE REVIEW

File: packages/blocks/src/api/test/registration.js [hunk 1]
```diff
@@ -632,6 +632,31 @@ describe( 'blocks', () => {
...
 				} );
 			} );
+
+			it( 'should update block attributes separately for each block when they use a default set', () => {
+				addFilter(
+					'blocks.registerBlockType',
+					'core/blocks/shared-defaults',
+					( settings, name ) => {
+						if ( name === 'my-plugin/test-block-1' ) {
+							settings.attributes.newlyAddedAttribute = {
```
Comment (youknowriad) [inline packages/blocks/src/api/test/registration.js]: What happens if you avoid mutations?

Comment (marekhrabe) [reply packages/blocks/src/api/test/registration.js]: Things will work well, as described in the linked issue. I have written all my filters avoiding mutation just from a habit so I have never discovered this situation but I think we should just play it safe and prevent the possibility. 

This would be ok:

```
settings.attributes = {
  ...settings.attributes,
  newlyAddedAttribute: {},
};
```

What do you think? I'm thinking about removing the declaration of `DEFAULT_BLOCK_TYPE_SETTINGS` and moving the default attributes directly inside `registerBlockType` so each block gets their own instance. Or keep the constant and do a deep copy before using it which I probably like better

Comment (youknowriad) [reply packages/blocks/src/api/test/registration.js]: Agreed, we should still recommend immutability but we should clone the defaults

Comment (marekhrabe) [reply packages/blocks/src/api/test/registration.js]: I think this is ready now

File: packages/blocks/src/api/registration.js [hunk 2]
```diff
@@ -154,7 +162,7 @@ export function unstable__bootstrapServerSideBlockDefinitions( definitions ) {
 export function registerBlockType( name, settings ) {
 	settings = {
 		name,
-		...DEFAULT_BLOCK_TYPE_SETTINGS,
+		...cloneDeep( DEFAULT_BLOCK_TYPE_SETTINGS ),
```
Comment (youknowriad) [inline packages/blocks/src/api/registration.js]: I'm not sure clone deep is the best solution here, especially for the icon. Could shallow cloning the settings and attributes work? I'm also not against moving it to the function.

Comment (marekhrabe) [reply packages/blocks/src/api/registration.js]: I've tried moving it directly to the function. Otherwise, we would need to clone deeply some keys of the defaults object and I think that might get unnecessary complex for relatively simple operation.

**Review by youknowriad — APPROVED** [review]
LGTM

@gziolo any opinion here?

**Comment by gziolo** [comment]
Looks good 👍
