### PR TITLE
Video Block: Use existing video poster image on insert.

### LINKED ISSUE #21553: Video poster image is ignored when inserted into editor
**Describe the bug**

When a video attachment already has a poster image, it is ignored when the video gets inserted into the editor.

**To reproduce**

1. Go to Media -> Add New and upload a video
2. Click 'Edit' and on the attachment editing screen, select a poster image for the video in the Featured Image meta box
3. Save the video attachment
4. Create a new post and insert the video using the Video block type

Observe that the video's poster image does not get used, and the user has to choose the poster image again using the Select Poster Image button in the block controls

**Expected behavior**

When a video has an existing poster image (featured image) it should be used when that video is inserted into the editor using the video block type.

**Screenshots**

### PR DESCRIPTION
**Pull request by getsource**
## Description

When selecting a video in the video block, automatically use the poster image (from a video's featured image) when it is assigned.

Side note for testing:
While working on this, I found #34411. Removing the poster does not currently work (with or without this PR), but should after #34411 is merged.

Fixes: #21553

## How has this been tested?

Tested on `wp-env`.

From the #21553 description:
- Go to Media -> Add New and upload a video
- Click 'Edit' and on the attachment editing screen, select a poster image for the video in the Featured Image meta box
- Save the video attachment

Then:
- Create a new post
- Insert a video block
- Select previously created video
- Notice that poster image is set

## Screenshots 
Before:

https://user-images.githubusercontent.com/1034160/131494074-749f9c27-9002-4a01-83d6-441f5c230203.mov

After:

https://user-images.githubusercontent.com/1034160/131494116-4447f712-1b63-4c26-bab2-9be1af5683d6.mov

## Types of changes

Enhancement

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-library/src/video/edit.js [hunk 1]
```diff
@@ -99,7 +99,11 @@ function VideoEdit( {
 		}
 		// sets the block's attribute and updates the edit component from the
 		// selected media
-		setAttributes( { src: media.url, id: media.id } );
+		setAttributes( {
+			src: media.url,
+			id: media.id,
+			poster: media?.image?.src,
```
Comment (ntsekouras) [inline packages/block-library/src/video/edit.js]: Here `media` is an object, so no need to use `media?.`.

**Review by ntsekouras — COMMENTED** [review]
Thanks for working on this!

This change makes the video block, without a poster added by the user, show the default image, which IMO is not so good compared to the video preview that is being shown right now..

I haven't checked how and if we can obtain the `default` poster value and I'm not sure how we should handle it either 😄 . More opinions here would be good.

File: packages/block-library/src/video/edit.js (hunk 1 above)
Comment (getsource) [reply packages/block-library/src/video/edit.js]: Thank you! Rebased and updated this.

**Comment by getsource** [comment]
Oh! I'm not sure how I missed this, but I can reproduce it now, thanks.
Going to see if I can restore the previous behavior for videos that don't have a user-selected one.

File: packages/block-library/src/video/edit.js [hunk 2]
```diff
@@ -97,9 +97,15 @@ function VideoEdit( {
...
 		}
+
 		// sets the block's attribute and updates the edit component from the
 		// selected media
-		setAttributes( { src: media.url, id: media.id } );
+		setAttributes( {
+			src: media.url,
+			id: media.id,
+			poster:
+				media.image?.src !== media.icon ? media.image?.src : undefined,
```
Comment (getsource) [inline packages/block-library/src/video/edit.js:111]: This emulates what seems to be used in core in a couple of places:
https://github.com/WordPress/wordpress-develop/blob/b83b01e1b01429dc4a6da49ec23e1f7dfc4ae446/src/wp-includes/media-template.php#L386

File: packages/block-library/src/video/edit.js [hunk 3]
```diff
@@ -97,9 +97,15 @@ function VideoEdit( {
 			setAttributes( { src: undefined, id: undefined } );
```
Comment (getsource) [inline packages/block-library/src/video/edit.js]: Does `poster` need to be cleared here as well?

File: packages/block-library/src/video/edit.js [hunk 4]
```diff
@@ -97,9 +97,15 @@ function VideoEdit( {
...
+
 		// sets the block's attribute and updates the edit component from the
 		// selected media
-		setAttributes( { src: media.url, id: media.id } );
+		setAttributes( {
+			src: media.url,
+			id: media.id,
+			poster:
+				media.image?.src !== media.icon ? media.image?.src : undefined,
+		} );
```
Comment (getsource) [inline packages/block-library/src/video/edit.js:112]: It looks like `poster` defaults to `undefined`, which is why I picked that -- this avoids having an empty `poster` attribute.

However, when `poster` is "Removed", it's set to empty string: https://github.com/WordPress/gutenberg/blob/009717a3d88fa26cb8613cd64fd987cc8607a210/packages/block-library/src/video/edit.js#L160

This results in an empty `poster` attribute. I'm not sure anything should change about it in this PR, but figured I'd document the finding.

**Comment by getsource** [comment]
Okay, I think this is working better now.
I left a couple comments / questions on the most recent commit.

File: packages/block-library/src/video/edit.js (hunk 4 above)
Comment (getsource) [reply packages/block-library/src/video/edit.js:112]: Okay, I set this to `undefined` instead in the most recent pass to avoid an empty `poster` attribute on the front-end.

File: packages/block-library/src/video/edit.js (hunk 3 above)
Comment (getsource) [reply packages/block-library/src/video/edit.js]: Decided that since it's getting set here, makes sense to clear it. Less likely to end up with an error condition where there's still a poster set, but the other information is missing.

File: packages/block-library/src/video/edit.js [hunk 5]
```diff
@@ -112,7 +122,7 @@ function VideoEdit( {
 				onReplace( embedBlock );
 				return;
 			}
-			setAttributes( { src: newSrc, id: undefined } );
+			setAttributes( { src: newSrc, id: undefined, poster: undefined } );
```
Comment (getsource) [inline packages/block-library/src/video/edit.js:125]: This is a new behavior, but I think it makes the most sense for the poster to get reset / removed if a user has selected a new URL / video in the general sense.

This way, also, the poster image doesn't hide the preview of the new URL that was selected, which keeps the user from having to "play" the video to see if it worked.

**Comment by getsource** [comment]
After chatting with @Mamaduka, made a few additional changes in response to my questions, reflected in the most recent commit.

**Review by ntsekouras — APPROVED** [review]
Nice work here @getsource, thanks! 👍
