### PR TITLE
Fix: Image resizer does not work if only one dimension is changed

### LINKED ISSUE #12278: Pixel-sizing only works after setting image size percentage
**Describe the bug**
This is related to #12276, #12277, and #12168 in various ways.

When inserting an image in 5.0-RC1, the pixel sizer doesn't work unless a percentage is set first.

The pixel sizer jumps from it's initial value to 1 the when hitting up (i.e. it's as if the value is 0 and 1 is added) and the size in pixels is not set either.

It appears that the sizing kicks in once _both_ dimensions are set. As I tested this, I think I realized that the pixel dimension fields aren't actually set with values but instead have placeholders. I suspect that's the root cause of the issue. (Placeholders are always confusing!)

**To Reproduce**
1. Insert an image
2. Hit the "Up" control on the number field of either the width or height pixel size settings fields

**Expected behavior**
Image is proportionally scaled by 1px in that dimension. If the image is 300px wide, the image is now 301px wide.

**Screenshots**
image-pixel-sizing-bug

**Desktop (please complete the following information):**
Win 10, Firefox 63.0.3, WP 5.0-RC1, no plugins, Twenty Nineteen

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/12278

Image sizes were only applied to the editor if both width and height were set. This PR applies the sizes even if just one of the dimensions is set.

## How has this been tested?
I added an image, I went to the image dimensions setting, I changed the width by writing a new number. I verified the new dimension was applied. On master, nothing happens until the height is also set, but the attribute is changed anyway and when we view the post on the frontend the dimension is applied.

### CODE REVIEW

File: packages/block-library/src/image/edit.js [hunk 1]
```diff
@@ -675,12 +675,10 @@ class ImageEdit extends Component {
 								<>
 									{ getInspectorControls( imageWidth, imageHeight ) }
 									<ResizableBox
-										size={
-											width && height ? {
```
Comment (youknowriad) [inline packages/block-library/src/image/edit.js]: Do you know why the check was there?

**Review by youknowriad — APPROVED** [review]
Works well 👍

File: packages/block-library/src/image/edit.js (hunk 1 above)
Comment (jorgefilipecosta) [reply packages/block-library/src/image/edit.js]: The logic of just applying sizes when both dimension change was applied in this PR https://github.com/WordPress/gutenberg/pull/6205. I did not notice regressions on the behavior that PR was intended to solve when comparing this PR to master (before the merge).
