### PR TITLE
Fix: Patterns & template parts: remove "apply globally" option from block settings

### LINKED ISSUE #52139: Patterns: remove "apply globally" option from block settings
### Description

When creating a new pattern using 16.1 and syncing it, an option to "apply globally" popped up in the block settings. This doesn't make sense in this context and should be removed.

### Step-by-step reproduction instructions

1. Create a new pattern from three dot menu.
2. Ensure focus remains on the pattern (it should).
3. Open sidebar and notice under advanced an option to apply globally greyed out. 

### Screenshots, screen recording, code snippet

Screen Shot 2023-06-29 at 11 15 29 AM

### Environment info

- WP 6.2.2
- GB 16.1
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by carolinan**
## What?

Synced patterns and template parts have a Styles option in the Advanced panel of the block settings sidebar (inspector), for applying styles globally.

This PR removes this option by adding an early return to the "push changes to global styles" hook, if the block is a template part or pattern.

Closes https://github.com/WordPress/gutenberg/issues/52139

## Why?

These blocks have no styling options, so the option to apply the styles is not needed.

## Testing Instructions
1. Activate a block theme
2. Open the site editor. 
3. Select or create a synced pattern and a template part.
4. Select them and open the Advanced panel in the inspector.
5. Confirm that there is no styles and "apply globally" option.
6. Select a different block that has style options. Open the advanced panel and confirm that the block still has the styles option. Optionally, make some style changes, use the option, and confirm that the option still works for the valid block types.

## Screenshots or screencast 
Before:
The block settings sidebar with the unused styles option.

After:
The block settings sidebar without the styles 'apply globally' option.

### CODE REVIEW

**Review by Mamaduka — COMMENTED** [review]
I like @richtabor's [suggestion](https://github.com/WordPress/gutenberg/issues/52139#issuecomment-1613635325) to use block support flags and avoid hardcoding block name checks.

Any reason for not going in that direction?

**Comment by carolinan** [comment]
> I like @richtabor's [suggestion](https://github.com/WordPress/gutenberg/issues/52139#issuecomment-1613635325) to use block support flags and avoid hardcoding block name checks.
> 
> Any reason for not going in that direction?

Updated, I was just trying to avoid the extra import.

File: packages/edit-site/src/hooks/push-changes-to-global-styles/index.js [hunk 1]
```diff
@@ -212,6 +214,19 @@ function PushChangesToGlobalStylesControl( {
...
 	( BlockEdit ) => ( props ) => {
 		const blockEditingMode = useBlockEditingMode();
+
+		/**
+		 * Do not show the panel if the block does not have style support.
+		 *
+		 * @see https://github.com/WordPress/gutenberg/issues/52139
+		 */
+		if (
+			! hasBlockSupport( props.name, 'color' ) ||
```
Comment (carolinan) [inline packages/edit-site/src/hooks/push-changes-to-global-styles/index.js]:
```suggestion
			! hasBlockSupport( props.name, 'color' ) &&
```

@Mamaduka  @richtabor What condition should we use here though?

**Comment by Mamaduka** [comment]
@carolinan, I pushed some minor changes; I hope you are okay with it.

* Since the control already had a condition for rendering, I combined both conditions instead of returning early.
* I removed the comment. This isn't a temporary hack we might change in the future, so there's no need to leave a comment with an issue reference.

File: packages/edit-site/src/hooks/push-changes-to-global-styles/index.js [hunk 2]
```diff
@@ -212,10 +213,14 @@ function PushChangesToGlobalStylesControl( {
 const withPushChangesToGlobalStyles = createHigherOrderComponent(
 	( BlockEdit ) => ( props ) => {
 		const blockEditingMode = useBlockEditingMode();
+		const supportsStyles =
+			hasBlockSupport( props.name, 'color' ) ||
+			hasBlockSupport( props.name, 'typography' );
+
```
Comment (carolinan) [inline packages/edit-site/src/hooks/push-changes-to-global-styles/index.js:221]: Are we absolutely 100% sure we only want to check for these two, not border and spacing?
Related: https://github.com/WordPress/gutenberg/pull/51621

Comment (Mamaduka) [reply packages/edit-site/src/hooks/push-changes-to-global-styles/index.js:221]: We can start with these two and widen the check as needed in the future.

**Review by Mamaduka — APPROVED** [review]

File: packages/edit-site/src/hooks/push-changes-to-global-styles/index.js (hunk 2 above)
Comment (aaronrobertshaw) [reply packages/edit-site/src/hooks/push-changes-to-global-styles/index.js:221]: I'm a bit late to this party, sorry, but border etc should really be checked.

I was looking into this feature in https://github.com/WordPress/gutenberg/pull/51621 before being pulled onto higher priority tasks. Perhaps that could be of some help, or we roll whatever is need here into that PR?

Comment (Mamaduka) [reply packages/edit-site/src/hooks/push-changes-to-global-styles/index.js:221]: Thanks for the additional context, @aaronrobertshaw.

As I can see, the border will only be supported after #51621. I think it makes sense to adjust the checks there.

Comment (carolinan) [reply packages/edit-site/src/hooks/push-changes-to-global-styles/index.js:221]: Perhaps we need to wait with the border, until the border is fixed.
But it means the image blocks that currently have this "apply globally" option, won't,  until maybe 6.4.

Comment (Mamaduka) [reply packages/edit-site/src/hooks/push-changes-to-global-styles/index.js:221]: > But it means the image blocks that currently have this "apply globally" option, won't, until maybe 6.4.

It doesn't do anything for the Image block since the border still needs to be supported. Having an option that does nothing is more confusing.

Comment (aaronrobertshaw) [reply packages/edit-site/src/hooks/push-changes-to-global-styles/index.js:221]: Thanks for taking a look.

I guess I wasn't comfortable half-fixing the feature. Particularly, when for spacing at least it's only a minor tweak to include it now, reducing the scope of what still remains broken. Combining the two fixes it all.

Comment (Mamaduka) [reply packages/edit-site/src/hooks/push-changes-to-global-styles/index.js:221]: > Apply this block’s typography, spacing, dimensions, and color styles to all Post Featured Image blocks.

This paragraph is misleading. If you check, the "style paths" feature only supports `color` and `typography`.

Unless I'm misunderstanding something, this PR can ship separately, and future PRs can adjust checks. We can also use a constant to keep track of `SUPPORTED_STYLES`.

Comment (aaronrobertshaw) [reply packages/edit-site/src/hooks/push-changes-to-global-styles/index.js:221]: The comments above those style path constants note they are supposed to be duplicates from the block-editor and they are out of sync and incorrect. Hence missing things like spacing etc.

Comment (Mamaduka) [reply packages/edit-site/src/hooks/push-changes-to-global-styles/index.js:221]: Would something like this work - [512aeb4](https://github.com/WordPress/gutenberg/pull/52160/commits/512aeb4dcadac87d75008abff8846238536eabf3)?

Comment (Mamaduka) [reply packages/edit-site/src/hooks/push-changes-to-global-styles/index.js:221]: @aaronrobertshaw, any blockers to merge this PR?

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for the patience here 🙇 

This solves the immediate need relating to https://github.com/WordPress/gutenberg/issues/52139.

Let's go with this, it tests as advertised for me.

| Before | After |
|---|---|
| Screenshot 2023-07-07 at 5 48 54 pm | Screenshot 2023-07-07 at 5 50 33 pm |

File: packages/edit-site/src/hooks/push-changes-to-global-styles/index.js (hunk 2 above)
Comment (aaronrobertshaw) [reply packages/edit-site/src/hooks/push-changes-to-global-styles/index.js:221]: No, let's go with this. I've been caught up today on last-minute patterns updates and haven't had the time to revisit the other PR.

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the update/beta-4-second-round branch to get it included in the next release: eb8ef9f17d
