### PR TITLE
Inspector Fields: Show DataForm driven Content tab for all blocks that support content fields (+ support block bindings)

### LINKED ISSUE #73423: Block Fields: Add support for Pattern Overrides and Block Bindings
## What problem does this address?
The inspector fields currently doesn't support Pattern Overrides or any other attributes that have block bindings.

To reproduce this:
1. Insert a synced pattern that has overrides
2. Note that the inspector fields _are_ displayed and can be edited, however any changes aren't persisted.

https://github.com/user-attachments/assets/f30f7684-deb1-493a-8008-6adff4788eb3

## What is your proposed solution?
The reason behind the issue is that block bindings hooks into (or monkey patches) a block's `setAttributes` calls.

The inspector fields instead dispatch the `updateBlockAttributes` action, which doesn't have any handling of block bindings.

### PR DESCRIPTION
**Pull request by talldan**
Addresses part of [Block Attribute Groups](https://github.com/WordPress/gutenberg/issues/73845#top)
Fixes #73423

## What?
This PR updates what we previously called 'ContentOnlyControls' to work more as described in [Block Attribute Groups](https://github.com/WordPress/gutenberg/issues/73845#top).
- Individually selected blocks (paragraph, image etc) now have dataform driven fields in the inspector content tab
- Patterns and other sections when selected still show an accumulated version of all fields for all inner blocks (so that the pattern feels like a single block).

These changes still require the `contentOnly` experiments to be active, but we might now want to entirely decouple the 'contentOnly: Enable editable inspector fields' experiment.

As part of this refactor, #73423 is also fixed, block bindings and pattern overrides are now supported by the fields.

## Why?
Quoting the salient part of the #73845
> Notably, these attribute groups are agnostic about editing modes like "contentOnly". Which, by the way, is likely a misnomer, it should be treated as simpler editing or pattern editing, a subset of all attributes and block types. This means the block inspector should be able to render these four tabs as necessary depending on what a given block supports.

## How?
The main change is to re-work the way the component previously known as `ContentOnlyControls` renders.

Before, the component rendered in a very custom way that was built into the block inspector itself. There was a process of mapping over the inner blocks of the selected section to render the dataforms.

With this PR, the rendering is now block-centric. Each block now renders its own dataform though the `<InspectorControls group="content">`  slot, which is a much more typical way for blocks to render controls.

This change makes it possible to render the controls for individually selected blocks outside of patterns.

It also makes support for block bindings trivial, as the fields can now use `setAttributes` directly instead of `updateBlockAttributes`.

With this PR, `ContentOnlyControls` is now renamed to `BlockFields`.

## Trade-offs
The previous implementation had a 'drilldown' feature for Lists, Buttons, Navigation. In this PR it's removed and the implementation will need to be revised. I think it's worth reconsidering how this can work in a way that's in keeping with the recently added List View tab ([Add list view tab to the buttons, list and social icons blocks](https://github.com/WordPress/gutenberg/pull/74120#top)). This needs some design consideration as well

For now it means that the dataforms can be quite big, but I think this should only be a temporary issue:
| Before | After |
|--------|--------|
| Screenshot 2026-01-06 at 1 38 04 pm | Screenshot 2026-01-06 at 1 43 42 pm |

## Testing Instructions
Prerequisite - Enable the contentOnly experiments

### Individual blocks
1. Insert an individual block like Paragraph, Image, Media Text
2. Observe these blocks now have a Content tab that allows modifying content

### Pattern editing
1. Edit a pattern (synced or unsynced), or template part.
2. Observe the Content tab appears almost as before, but without the drilldown feature (all fields are shown at the root level).
3. For synced patterns, inner blocks with overrides should now be editable in a pattern instance—the changes can be saved and persist to the frontend.

## Screenshots or screencast 
Screenshot 2026-01-06 at 1 56 33 pm

### CODE REVIEW

**Comment by talldan** [comment]
I think this should work as expected now, I've updated the AsyncModeProvider logic so that blocks within a section receive synchronous updates, and looks like that fixes the field order.

I'm not sure it's the best solution though, feels like I've tarnished the AsyncModeProvider.

File: packages/block-editor/src/components/block-list/index.js [hunk 1]
```diff
@@ -260,7 +273,8 @@ function Items( {
 						// Only provide data asynchronously if the block is
 						// not visible and not selected.
 						! visibleBlocks.has( clientId ) &&
-						! selectedBlocks.includes( clientId )
+						! selectedBlocks.includes( clientId ) &&
+						! isSelectionWithinCurrentSection
 					}
 				>
```
Comment (talldan) [inline packages/block-editor/src/components/block-list/index.js:265]: This change to the `AsyncModeProvider` is not something I like, it might cause performance issues, but without it the fields don't always display in the correct order for Pattern Editing.

I think we could remove the change from this PR and explore a fix separately. Maybe it's possible to fix it in a different way.

File: packages/block-editor/src/components/inspector-controls/fill.js [hunk 2]
```diff
@@ -42,7 +43,7 @@ export default function InspectorControlsFill( {
 		warning( `Unknown InspectorControls group "${ group }" provided.` );
 		return null;
 	}
-	if ( ! context[ mayDisplayControlsKey ] ) {
+	if ( ! forceDisplayControls && ! context[ mayDisplayControlsKey ] ) {
```
Comment (talldan) [inline packages/block-editor/src/components/inspector-controls/fill.js:46]: `mayDisplayControls` usually limits InspectorControls to only display fills for the selected block.

For Pattern Editing, we need to show fills for all the inner blocks of the pattern (and for the pattern itself). I've added this extra prop to a private version of the component to override the normal behavior.

File: packages/block-editor/src/hooks/block-fields/index.js
Comment (talldan) [inline packages/block-editor/src/hooks/block-fields/index.js:1]: I've moved this code to the 'hooks' folder and renamed it to 'block-fields'.

It's in 'hooks' as the code now uses the `BlockEdit` filter, so it has side-effects and this generally where code with side-effects lives.

We may also want to make this into a BlockSupports feature in the future, but I'll leave that question for the future.

File: packages/block-library/src/image/image.js [hunk 3]
```diff
@@ -774,81 +778,84 @@ export default function Image( {
...
-						<ToolsPanelItem
-							label={ __( 'Alternative text' ) }
-							isShownByDefault
-							hasValue={ () => !! alt }
-							onDeselect={ () =>
-								setAttributes( { alt: undefined } )
-							}
-						>
-							<TextareaControl
+			{ ! hasDataFormBlockFields && (
```
Comment (talldan) [inline packages/block-library/src/image/image.js:781]: Prevents the UI added in #74201 from displaying when the experiment is active, as that results in duplicate UI for the same thing.

**Comment by talldan** [comment]
There are some failing e2e tests, but they look to be unrelated and are also failing in trunk.

File: packages/block-editor/src/hooks/block-fields/media/styles.scss
Comment (ramonjd) [inline packages/block-editor/src/hooks/block-fields/media/styles.scss:1]: Just noticed that the `block-editor-content-only-controls__media-thumbnail` selector doesn't have a `.` - not from this PR, but I thought while you're relocating it might be a chance to fix.

File: packages/block-editor/src/hooks/block-fields/index.js [hunk 4]
```diff
@@ -351,192 +331,62 @@ function BlockFields( { clientId } ) {
...
-					nestedContentClientIds: _nestedContentClientIds,
-					contentClientIds: _contentClientIds,
-				};
-			},
-			[ rootClientId ]
+				{ ! isSelectionWithinCurrentSection && isSelected && (
+					<PrivateInspectorControlsFill group="content">
+						<BlockFields { ...props } blockType={ blockType } />
+					</PrivateInspectorControlsFill>
+				) }
```
Comment (andrewserong) [inline packages/block-editor/src/hooks/block-fields/index.js:382]: Not a blocker for this PR, but for this case where we're rendering the block fields for a single selected block, I wonder if it'd be worth forcing all the controls to be visible by default? For the Image block, for example, it winds up being quite short and a little fiddly to expand the different properties:

Image

Whereas when we're in a pattern, it's quite useful having some of these controls hidden 🤔. Again not a blocker, just wanted to capture the thought.

File: packages/block-editor/src/hooks/block-fields/media/styles.scss
Comment (ramonjd) [reply packages/block-editor/src/hooks/block-fields/media/styles.scss:1]: Optional too, or for later: should CSS classes be renamed to match new hooks/block-fields location?

File: packages/block-library/src/image/image.js (hunk 3 above)
Comment (andrewserong) [reply packages/block-library/src/image/image.js:781]: Would it be worth adding a comment to capture this? Mostly to flag that this is sort of in an "in progress" state as we'll want to eventually remove the ad hoc code here and depend on the hook instead?

File: packages/block-editor/src/hooks/block-fields/styles.scss [hunk 5]
```diff
@@ -0,0 +1,33 @@
+@use "@wordpress/base-styles/colors" as *;
+@use "@wordpress/base-styles/variables" as *;
+@use "./link/styles.scss" as *;
+@use "./media/styles.scss" as *;
+@use "./rich-text/styles.scss" as *;
+
+.block-editor-content-only-controls__fields-container {
```
Comment (andrewserong) [inline packages/block-editor/src/hooks/block-fields/styles.scss]: Not necessarily something that needs to be done in this PR, but we could also rename the CSS classes?

File: packages/block-editor/src/components/block-list/index.js (hunk 1 above)
Comment (andrewserong) [reply packages/block-editor/src/components/block-list/index.js:265]: Is the concern about performance due to needing to use a deep check with `hasSelectedInnerBlock` or the potential for a very long section that has hundreds of blocks that are no longer being dealt with asynchronously?

My hunch is that we should be treating the behaviour when working within a section similarly to if we'd selected a big list of blocks, so IMO this change seems reasonable. But I guess we might not know until we use it in practice?

Comment (ramonjd) [reply packages/block-editor/src/components/block-list/index.js:265]: Ah, so if blocks render asynchronously, they might not be mounted when BlockFields tries to collect their fields?

What's the performance concern? Is it checking innerblocks in large patterns?

I have some pretty gnarly patterns (100+ blocks) and didn't perceive any performance issues, but I guess there'd be bigger ones out there 😄 

I don't know if it would make things worse, it very well could 😄 but would it improve things to only force sync for blocks with fields?

`isSelectionWithinCurrentSection && blocksWithFields.has( clientId )`

**Review by andrewserong — APPROVED** [review]
Lots of good improvements in this PR — I like the refactor, the use of the hook to inject the controls, and the `forceDisplayControls` in `PrivateInspectorControlsFill` 👍

All testing well for me, and looks safely tucked away behind the experiment. I agree it looks like we can tweak the scope of the experiments in follow-ups as there's now behaviour that isn't part of patterns that's part of the experiment.

Overall, I like the Content Tab idea. Another non-blocking comment is that I think the content tab is overkill for the Paragraph block, as the tabbed interface is IMO worse than the single tab for such a commonly used block. I.e.

With the experiment enabled, the content and settings tabs have very little in them:

Image

But with the experiment switched off, we have everything in a single tab which feels nicer to me:

Image

So, an idea for a follow-up: can we determine when to force a single tab for the Content as well? For the Paragraph block, I reckon we could comfortable have a Content _panel_ sit above those controls, rather than needing separate tabs.

I've left a couple of comments (possibly doubling up with @ramonjd), but nothing major. IMO I think this is looking pretty good to merge and iterate. What do folks think?

**Review by ramonjd — APPROVED** [review]
This is working well for me. I tested the following:

- patterns
- synced patters
- paragraph/buttons/list/media + text blocks

Screenshot 2026-01-07 at 2 26 26 pm


Synced patterns with overrides and overrides with the same names work as expected:


https://github.com/user-attachments/assets/c70ef6dd-b806-4275-a029-72df6477e584



Checked with experiment on an off and couldn't spot any regressions.

I agree with @andrewserong - this is behind the experiment and is looking good. 


-------

Not for this PR, but I'm just noting that I missed being taken to the block when clicking on an editable field. 

As mentioned, I have some pretty gnarly patterns with lots of blocks in the tree, so the visual connect between canvas and field would be nice to have later.

**Comment by andrewserong** [comment]
> So, an idea for a follow-up: can we determine when to force a single tab for the Content as well? For the Paragraph block, I reckon we could comfortable have a Content panel sit above those controls, rather than needing separate tabs.

Just to capture the thought while it's in my brain: I think we might be able to add a bit more logic before calling `tabs.push( TAB_CONTENT )`, a bit like how we've got some conditions before adding the settings tab:

https://github.com/WordPress/gutenberg/blob/1d916a08f9d8e429a76da9a56f590e910a2fcfa3/packages/block-editor/src/components/inspector-controls-tabs/use-inspector-controls-tabs.js#L103-L110

In any case, that's for another PR!

File: packages/block-editor/src/components/block-list/index.js (hunk 1 above)
Comment (talldan) [reply packages/block-editor/src/components/block-list/index.js:265]: Yeah, pretty much, if component updates are deferred, the fields aren't render into the slots in the correct order. Any off-screen blocks will be last even if they're visually first. 😬  

My main performance concern is that `AsyncModeProvider` is itself a performance improving measure, so adding more conditions (and more expensive ones) is naturally going to make it worse.

Performance tests don't look great (even though they're not always reliable):
```
┌──────────────────────┬──────────────────────────────────────────┬─────────────────────────────┬────────────┐
│ (index)              │ 3df02b87f0fae4a4515f5a0baa5528309233c393 │ trunk                       │ % Change   │
├──────────────────────┼──────────────────────────────────────────┼─────────────────────────────┼────────────┤
│ type                 │ '12.71 ms +13.3% -7.63%'                 │ '11.7 ms +8.63% -6.75%'     │ '8.63%'    │
│ typeWithoutInspector │ '12.79 ms +5.94% -5.08%'                 │ '11.85 ms +6.67% -7.68%'    │ '7.93%'    │
│ typeWithTopToolbar   │ '15.68 ms +9.44% -1.21%'                 │ '14.27 ms +7.99% -1.47%'    │ '9.88%'    │
│ typeContainer        │ '6.58 ms +3.95% -10.03%'                 │ '5.83 ms +17.67% -3.43%'    │ '12.86%'   │
└──────────────────────┴──────────────────────────────────────────┴─────────────────────────────┴────────────┘
```

File: packages/block-editor/src/hooks/block-fields/index.js (hunk 4 above)
Comment (talldan) [reply packages/block-editor/src/hooks/block-fields/index.js:382]: Yeah, agree. I think it'd be good to look at as a follow-up. The block icon and name is also duplicative in this situation, so we can probably simplify some bits.

File: packages/block-editor/src/hooks/block-fields/media/styles.scss
Comment (talldan) [reply packages/block-editor/src/hooks/block-fields/media/styles.scss:1]: Wow, good catch. Fixed the thumbnail styles. I've also updated the class names for the main block fields code.

The fields themselves will be moved/replaced by the fields package, so I've skipped that.

File: packages/block-editor/src/components/block-list/index.js (hunk 1 above)
Comment (talldan) [reply packages/block-editor/src/components/block-list/index.js:265]: I've reverted this for now and will move the change to a separate PR to encourage more focused dialog about it.

**Comment by youknowriad** [comment]
I think there's work to be done to make this and the php only controls that we added recently the same thing. 
I also think that we should make this work in a generic way (and not just for the "content" attributes).
In other words, my idea is something like this:

 - You add "group" prop (or something like that) to the attribute definition, when doing so, the inspector control automatically shows up in the block (regardless of block, regardless of attribute and regardless of whether it's php only block or not). Maybe that property could be "role" but I'm not sure entirely yet because it would mean new "style" role for instance.

This behavior shouldn't be tied to "content-only" work directly but "content-only" behavior might decide to only keep the "content" group visible in the inspector or something like that.

cc @mcsf 

We need to really nail this behavior properly before 7.0 because php only attribute are already merged "stable" AFAIK, so we might need to course correct there to make these non specific to php-only blocks.

**Comment by ramonjd** [comment]
> I think there's work to be done to make this and the php only controls that we added recently the same thing.

To help folks with context, do you have a link to a PR or issue? Are you referring to this line of work?

- https://github.com/WordPress/gutenberg/pull/71794

**Comment by talldan** [comment]
Yep, that's the one @ramonjd 👍 

Agree with your points, @youknowriad. I'll make some issues for the things you've mentioned.

**Comment by youknowriad** [comment]
Yes and more specifically this PR https://github.com/WordPress/gutenberg/pull/74102

**Comment by talldan** [comment]
I've made two issues here:
- [Block Fields: Support attribute groups](https://github.com/WordPress/gutenberg/issues/74437#top)
- [Block Fields: Align implementation with PHP-only block dataform](https://github.com/WordPress/gutenberg/issues/74438#top)

There are some other things I want to start working on:
- Currently the experiment is "contentOnly: Enable editable inspector fields". I want to remove the reference to contentOnly and make sure it doesn't depend on the other contentOnly experiment at all.
- Adjust the block form configuration so that it properly lists all the available fields, at the moment it's optimized for pattern editing, but that should no longer be the case: https://github.com/WordPress/gutenberg/blob/3cd52a40505eef031cba9d522ef8d94096f08281/packages/block-library/src/image/index.js#L108-L110

I'll make some PRs tomorrow for these.

Also need to consider how `form.fields` works with the concept of attribute groups. Maybe that's where the groups are defined?

**Comment by youknowriad** [comment]
> Also need to consider how form.fields works with the concept of attribute groups. Maybe that's where the groups are defined?

I was going back and forth with this in my head. Are the "groups" just a smart (tabs) DataForm layout that we can introspect within the block editor or are these something else, something you define within the attributes definition.  My ideal scenario is that "form" is not necessarily for most folks to define and just inferred from the attributes (all the fields), which means I have a preference for the "group" (or is that the same as role) to in the attribute definition and the "form" might be either three different forms or maybe better a single form like now where we filter out the top level "fields" by group or something depending on the tab.

**Comment by mcsf** [comment]
Sorry for the late reply, I lost this ping in a see of notifications. 🫠 

> I was going back and forth with this in my head. Are the "groups" just a smart (tabs) DataForm layout that we can introspect within the block editor or are these something else, something you define within the attributes definition. My ideal scenario is that "form" is not necessarily for most folks to define and just inferred from the attributes (all the fields), which means I have a preference for the "group" (or is that the same as role) to in the attribute definition and the "form" might be either three different forms or maybe better a single form like now where we filter out the top level "fields" by group or something depending on the tab.

Something like this makes sense to me.

* * *

Forgive me for asking without the necessary context — or revisiting closed questions — but what are the current contenders for how to address the mismatch between complex fields like Media and the several block attributes that make it up? I see @oandregal's new PR, #74575, going in the direction of preserving a structure at `blockType[ fieldsKey ]` distinct from `blockType.attributes`, but normalising the former by defining `getValue` and `setValue`.

But what about efforts to consolidate (almost) everything into `.attributes`? For completeness's sake, I'll also note @ntsekouras's exploration #72792, but I'm wondering about something more drastic. Attribute types can be objects; is that something to take further (e.g. `image.json > attributes > image > { type: object, default: ..., id: { ... }, url: { ... } }`)? Or what if we avoided premature generalisations and explored complex types like `media` (e.g. `image.json > attributes > image > { type: media }` assumes certain attribute names automatically, e.g. `attributes.image.id`), `link`, etc.?

**Edit:** I should also mention @oandregal's #74409, which concerns fields and not attributes, but which could be a point in favour of object-like attributes.

**Comment by talldan** [comment]
@mcsf I'd like to migrate the `blockType[ fieldsKey ]` to attributes as much as possible.

I think `type: object` (https://github.com/WordPress/gutenberg/pull/74409) seems like a worthy thing to add to DataForm anyway, so that could mark a path forwards.

I'm personally not sure how feasible it is to refactor existing flat block attributes to something like `type: object`, but I'm happy to try it (we can pick a block to test and build on top of #74409). My main concern would be features like block bindings that rely on attribute keys. Those would need to be migrated. It might also break a lot of plugins. Dynamic blocks too, I'm not sure they have an obvious way to be migrated.

A separate task is to move properties like `label` and `Edit` to block attributes. That's easier to achieve 🤞 .

**Comment by oandregal** [comment]
I'm catching up on this, but it seems in line with what was done at https://github.com/WordPress/gutenberg/pull/74575 The follow-ups listed in that issue description can help to tie together stuff that has been discussed in multiple places:


- Field API: add support for declaring fields that update multiple datums (each property of the data) at once with its Edit control. As demonstrated by [#74575](https://github.com/WordPress/gutenberg/pull/74575) updating multiple datum at once is feasible with the current Field API — it's just not serializable, you need to use `setValue`/`getValue` for the mapping, so we can't have it in block.json. A path forward for this would be introducing the `object` and/or `group` types, etc. discussed at [#74409](https://github.com/WordPress/gutenberg/pull/74409). I'll post an update shortly there following-up the work from [#74575](https://github.com/WordPress/gutenberg/pull/74575). I'm working on this.

- Field API: how to represent, declaratively, a rich-text field. [#73180](https://github.com/WordPress/gutenberg/issues/73180). The field declares that it uses rich-text (either `type: rich-text` or `Edit: rich-text`), but there's also the question about how do we pass it data that is not available at field-registration time such as the `clientId` of the block, etc. I suppose the `clientId` is used to read/write data from the block, but we need to remove that in favor of other mechanics. My suggestion here would be to create a `rich-text` field type bundled by DataForm ([examples](https://github.com/WordPress/gutenberg/blob/9dc20abe8736070c26338db4b30bd80d2d7517f5/packages/dataviews/src/field-types/index.tsx#L1)). That'd help untangle the current situation. Who can work on this? I can help with reviews, etc. 

- Field API: for the `media` and `link` examples in [#74575](https://github.com/WordPress/gutenberg/pull/74575), we have a few ways forward to make them declarative. One would be asking consumers to register field types (e.g., `type: wpMedia`, `type: wpLink`), and so we'd need to finish [#73548](https://github.com/WordPress/gutenberg/issues/73548). Though, custom types feel a bit heavy-handed, and we could instead allow consumers to register different _Edit_ controls for an existing field. This begs the question: how do we scope this? Do we allow replacing the Edit for any field of `type: url`? Do we allow replacing the Edit for any field of `type: url` that is part of a given entity? Do we do it per field id? etc. This is captured on the very broad [#61084](https://github.com/WordPress/gutenberg/issues/61084), and needs to be made more specific. I can also take this one.

> I was going back and forth with this in my head. Are the "groups" just a smart (tabs) DataForm layout that we can introspect within the block editor or are these something else, something you define within the attributes definition.

I read through the comments, but it's not clear to me what this is for. I'd benefit from some context to provide better suggestions. What's the UI impact? How do I see what we're trying to implement?

**Comment by youknowriad** [comment]
> I read through the comments, but it's not clear to me what this is for. I'd benefit from some context to provide better suggestions. What's the UI impact? How do I see what we're trying to implement?

The groups represent the "tabs" in the inspector sidebar, so basically, when you pick the "content" group, you'd end up in the DataForm rendered in the content tab, if you pick "style" the control end-up in styles tab and so on.

**Comment by talldan** [comment]
The part that doesn't connect for me is that if the mapping is in `form`, it means the `fields` don't represent an accurate schema of the data. It would represent the internal runtime state of the data, but not the external state. Maybe that's ok, I think I'm still not operating with a full understanding of all the design choices.

All the feedback still seems to suggests there's still no blocker for `type: 'object'`, so I think it would be good to reduce the scope of #74409 to just `object` and explore the other suggestions for mapping properties in separate PRs.

**Comment by youknowriad** [comment]
> it means the fields don't represent an accurate schema of the data. 

How so? they represent the shape of the block.attributes object exactly no?

**Comment by ellatrix** [comment]
Regarding the `clientId`, I commented here: https://github.com/WordPress/gutenberg/issues/73180#issuecomment-3777174845

The only thing that needs it is the annotation format that Yoast uses (it's not loaded by default). We should keep supporting that though. What that means specifically is that the block client ID + block attribute key needs to be passed to rich text when rich text is controlling a block attribute, but if not, it can be omitted.

**Comment by talldan** [comment]
> How so? they represent the shape of the block.attributes object exactly no?

@youknowriad Maybe it depends on the API being proposed, but I think a `media` field would be needed for the UI, but the block doesn't have any appropriate `media` attribute. A block has separate attributes like `id` (a number), `url` (a url), `caption` (a string), etc.

**Comment by ockham** [comment]
> I'm personally not sure how feasible it is to refactor existing flat block attributes to something like `type: object`, but I'm happy to try it (we can pick a block to test and build on top of #74409). My main concern would be features like block bindings that rely on attribute keys.

FWIW, block bindings do have a need for something like a "composite" (object) type; we'd probably need to align them with block attributes as closely as possible. This is one of the problems we're currently working on solving. In #74610, I'm exploring binding the Cover block image to a source, using a post's featured image (exposed by the `core/post-data` source) as an example. For now, I'm using dot notation expose the featured image's individual attributes. Bindings then look as follows:

```json
{
	"id":{"src":"core/post-data","args":{"key":"featured_media.id"}},
	"url":{"src":"core/post-data","args":{"key":"featured_media.url"}}
}
```

(Note that the source doesn't currently even define `featured_media` but only `featured_media.id` and `featured_media.url`.)

The more attributes need to be bound to what represents one "datum", the more redundant this gets. It'd be nice to do

```json
{
	"image":{"src":"core/post-data","args":{"key":"featured_media"}}
}
```

instead. (This would of course require an image type with standardized field names, unless we want to bring custom mappings back into the mix.)

> Those would need to be migrated. It might also break a lot of plugins. Dynamic blocks too, I'm not sure they have an obvious way to be migrated.

I don't think a migration would cut it; there's always the problem of pre-existing markup that's loaded on the frontend (and never goes through an editor-side block migration), so we'd have to support the old ("flat") format indefinitely. This can be done in dynamic blocks; purely static blocks would need to add a dynamic part to do that. 

(The same problem applies to block bindings, i.e. their previous syntax as found in persisted content; but I think the solution isn't substantially different from what we'd need for block attributes.)

---

What I'm more concerned about are union types. I believe we have a few instances of these that aren't currently obvious. For example, some blocks accept external images, which are only represented by a `url`; since they're not part of the media library, they don't have an `id`. How do we represent these cases?


We also need to be granular enough to specify that we either allow both internal and external images, or only an internal image. @cbravobernal came across an example of the latter while working on https://github.com/WordPress/gutenberg/pull/74109: The Cover block only allows internal images (AFAIK). (The reason is that it fetches some information about the image (such as color distribution etc) to compute the default opacity and the color of the Cover text.)

**Comment by oandregal** [comment]
> Field API: add support for declaring fields that update multiple datums (each property of the data) at once with its Edit control. (...) I'm working on this.

https://github.com/WordPress/gutenberg/pull/74900 addresses this.

> Field API: for the media and link examples in https://github.com/WordPress/gutenberg/pull/74575, we have a few ways forward to make them declarative. (...) I can also take this one

https://github.com/WordPress/gutenberg/pull/74942 addresses this.
