### PR TITLE
Components: Fix Post Publishing Popover moving when certain dates are clicked

### LINKED ISSUE #29899: Post Publishing Popover: Popover moves when certain dates are clicked
## Description

We recently made a change ( #29738 ) to keep the post publish popover open when a date is clicked. When the date is clicked, however, and the date length changes, the popover changes position. 

## Step-by-step reproduction instructions

    1. Create a new post
    2. Open the schedule popover by clicking on the publish date
    3. Click on a date in the picker that has a different day length than the current date (e.g. two digits instead of one or vice versa).

## Expected behaviour

The popover position doesn't change.

## Actual behaviour

The popover position changes.

## Screenshots or screen recording (optional)

Gif of the popover moving when some dates are clicked:
datetimepickerstaysopen

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

### PR DESCRIPTION
**Pull request by allilevine**
## Description
Fix Post Publishing popover glitch by changing the popover anchor ref to the containing div (`PanelRow`). Requires changing `PanelRow` to accept a forwarding ref.

Alternatively, we can change `PanelRow` to accept a ref as a prop and include the [`forwardRef()` wrapper](https://reactjs.org/docs/forwarding-refs.html) in `PostSchedule` instead.

Fixes #29899

## How has this been tested?

- Add or edit a post.
- Open the Post Publishing popover by clicking on the publish date or "Immediately."
- Click on various dates in the picker and confirm that the popover does not move or change position.
- Regression: check that other instances of the `PanelRow` component function correctly and don't require a ref.

## Screenshots 

popovernotmoving

## Types of changes

Bug fix:
- Changes the `PanelRow` component to accept a forwarding ref
- Creates a ref in `PostSchedule` and assigns it to `PanelRow`
- Passes the ref to `Dropdown` as an anchor ref and popover prop

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by retrofox — APPROVED** [review]
LGTM. Although I guess it's possible to deal with this visual issue via CSS keeping the popover stuck to a position, this solution looks good to me. 
I'd like to know the opinion of core folks, though.
@ellatrix @youknowriad could you chime on this, please?

File: packages/edit-post/src/components/sidebar/post-schedule/index.js [hunk 1]
```diff
@@ -3,18 +3,22 @@
...
 export function PostSchedule() {
+	const anchorRef = useRef();
+
 	return (
 		<PostScheduleCheck>
-			<PanelRow className="edit-post-post-schedule">
+			<PanelRow className="edit-post-post-schedule" ref={ anchorRef }>
 				<span>{ __( 'Publish' ) }</span>
 				<Dropdown
+					popoverProps={ { anchorRef: anchorRef.current } }
```
Comment (youknowriad) [inline packages/edit-post/src/components/sidebar/post-schedule/index.js:21]: Can you explain more why the default behavior of the Dropdown was not working as intended. (The toggle button being the anchorRef)?

File: packages/components/src/panel/row.js [hunk 2]
```diff
@@ -3,10 +3,18 @@
...
-function PanelRow( { className, children } ) {
-	const classes = classnames( 'components-panel__row', className );
+/**
+ * WordPress dependencies
+ */
+import { forwardRef } from '@wordpress/element';
 
-	return <div className={ classes }>{ children }</div>;
-}
+const PanelRow = forwardRef( ( { className, children }, ref ) => (
```
Comment (youknowriad) [inline packages/components/src/panel/row.js:11]: I'm ok with this change 👍

File: packages/edit-post/src/components/sidebar/post-schedule/index.js (hunk 1 above)
Comment (youknowriad) [reply packages/edit-post/src/components/sidebar/post-schedule/index.js:21]: Ok I see, it's the width of the button. An alternative and maybe smaller solution would have been to right (or left never know) position the dropdown.

File: packages/components/src/panel/row.js (hunk 2 above)
Comment (retrofox) [reply packages/components/src/panel/row.js:11]: that's great :+1:

File: packages/edit-post/src/components/sidebar/post-schedule/index.js (hunk 1 above)
Comment (allilevine) [reply packages/edit-post/src/components/sidebar/post-schedule/index.js:21]: The default `anchorRef` [is the button wrapper](https://github.com/WordPress/gutenberg/blob/c761c4c8bc70c29f55b781fa6c9d82e893dd6586/packages/components/src/dropdown/index.js#L87), `components-dropdown`. It's in a flex layout.

> An alternative and maybe smaller solution would have been to right (or left never know) position the dropdown.

I've tried passing different `position` props to `Dropdown` but that didn't seem to change the behavior. 😞 Or do you mean with CSS?

Comment (retrofox) [reply packages/edit-post/src/components/sidebar/post-schedule/index.js:21]: yeah, well... setting the position at `left` or `right` doesn't work. First of all, I'm not sure whether it's possible to anchor the popover at the right because it's too close to the client border, so I guess it's going to apply for another `x` position automatically. 
I think we could set a fixed width at the button, maybe play a little bit with the text and element alignment, but it will change the button size which isn't something that we'd like to get either.

Comment (youknowriad) [reply packages/edit-post/src/components/sidebar/post-schedule/index.js:21]: Ok, than the solution in the PR looks good to me.

**Comment by retrofox** [comment]
Thanks, Allison for dealing with this uncomfortably annoying visual issue 😅. Considering that the approach doesn't have any objection and it works well, I'm going to merge it.
