### PR TITLE
Fix: Safari "Edit as HTML" for Fit Text  deletes content

### LINKED ISSUE #73768: "Edit as HTML" for Stretchy Text block variations deletes content
### Description

When using the "Edit as HTML" option for a Heading or Paragraph block using the Stretchy Text block variation, the block content is removed.

### Step-by-step reproduction instructions

1. Make a paragraph or heading block
2. Write anything in it such as "Content"
3. Apply the Stretchy Text block variation for that block
4. In the block toolbar kebab menu, select "Edit as HTML"

Observe: the text written in Step 2 is gone. Expected outcome: Content of block is retained.

### Screenshots, screen recording, code snippet

Paragraph stretchy text block with content that says Stretchy Text

Block being editing as html is an empty paragraph element with the class has-fit-text

### Environment info

- WordPress 6.9 on https://playground.wordpress.net/
- No plugins
- Core theme

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Fixes: https://github.com/WordPress/gutenberg/issues/73768

cc: @mrwweb, @t-hamano 

On safari we had a bug when "Edit as HTML" was pressed and the block had "Fit Text" enabled, the content of the block disappear. This PR fixes the issue by making sure useFitText doesn't run when we are on HTML block mode. It is a good change and saves some CPU cycles in all browsers as when in HTML mode running the hook has no value because the block is hidden and the dimensions are irrelevant (and change while switching modes).

## Testing

On safari:
Paste this on the code editor:
```
<!-- wp:paragraph {"fitText":true} -->
<p class="has-fit-text">Content</p>
<!-- /wp:paragraph -->
```
Switch to visual mode and then at the block level press: "Edit as HTML".
Verify the content is kept on trunk it is lost.

### CODE REVIEW

File: packages/block-editor/src/hooks/fit-text.js [hunk 1]
```diff
@@ -68,9 +68,10 @@ function useFitText( { fitText, name, clientId } ) {
 	const hasFitTextSupport = hasBlockSupport( name, FIT_TEXT_SUPPORT_KEY );
 	const blockElement = useBlockElement( clientId );
 
-	// Monitor block attribute changes, and parent changes.
+	// Monitor block attribute changes, parent changes, and block mode.
 	// Any attribute or parent change may change the available space.
-	const { blockAttributes, parentId } = useSelect(
+	// Block mode is needed to disable fit text when in HTML editing mode.
+	const { blockAttributes, parentId, blockMode } = useSelect(
```
Comment (t-hamano) [inline packages/block-editor/src/hooks/fit-text.js:74]: Can we use an early return for further performance improvements?

```javascript
const { blockAttributes, parentId, blockMode } = useSelect(
	( select ) => {
		if ( ! clientId || ! hasFitTextSupport || ! fitText ) {
			return EMPTY_OBJECT;
		}
		const _blockMode =
			select( blockEditorStore ).getBlockMode( clientId );
		if ( _blockMode === 'html' ) {
			return { mode: _blockMode };
		}
		return {
			blockAttributes:
				select( blockEditorStore ).getBlockAttributes( clientId ),
			parentId:
				select( blockEditorStore ).getBlockRootClientId( clientId ),
			blockMode: _blockMode,
		};
	},
	[ clientId, hasFitTextSupport, fitText ]
);
```

**Comment by t-hamano** [comment]
I think it’s worth backporting this PR to 6.9.1.

File: packages/block-editor/src/hooks/fit-text.js (hunk 1 above)
Comment (jorgefilipecosta) [reply packages/block-editor/src/hooks/fit-text.js:74]: Yes, good suggestion I will apply it 👍

**Review by t-hamano — APPROVED** [review]
LGTM!

**Comment by jorgefilipecosta** [comment]
> LGTM!

Thank you for the review ☺️

**Comment by t-hamano** [comment]
This PR has been backported to the `wp/6.9` branch. #74806
