### PR TITLE
Fix some issues on the color picker component; Remove tinycolor2;

### LINKED ISSUE #34286: Components: use `colord` instead of `tinycolor2` in `ColorPicker`
Part of #34284

## Why

The [`colord` library](https://github.com/omgovich/colord) may be a better replacement for [`tinycolor2`](https://github.com/bgrins/TinyColor), which is currently used by the `ColorPicker` component:

- it has a smaller size
- it comes with first-party TS types

## What

The maintainer of `colord` [reached out to us in a previous PR](https://github.com/WordPress/gutenberg/pull/33714#issuecomment-897157426) and suggested we take a look at the `colord` library.

We should first assess the feasibility of this refactor (partially started in https://github.com/WordPress/gutenberg/pull/34014#discussion_r687904062)

## A/C

- [x] Assess if `colord` provides all needed functionality
- [x] Assess if any breaking changes are introduced
- [ ] Swap the libraries, update imports

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Closes #34286

We had some issues with the API of the color picker component on the readme we said it received a string color property representing the color but in fact, it received a hsla color object, the onChange was documented as receiving a string when in fact it also received a hsla color object.
I think we should follow the readme and make the component receive a string and pass a string to onChange. This way it becomes consistent with the other components like the color palette and custom gradient picker.
During these changes, we also remove the tinycolor2 package.

## How has this been tested?
I verified the color picker still works as expected on the color palette and the gradient picker.

### CODE REVIEW

File: packages/components/src/color-picker/color-display.tsx [hunk 1]
```diff
@@ -81,13 +81,7 @@ const RgbDisplay = ( { color, enableAlpha }: DisplayProps ) => {
...
 
 const HexDisplay = ( { color, enableAlpha }: DisplayProps ) => {
-	const colorized = colorize( color );
-	const colorWithoutHash = ( enableAlpha
-		? colorized.toHex8String()
-		: colorized.toHexString()
-	)
-		.slice( 1 )
-		.toUpperCase();
+	const colorWithoutHash = color.toHex().slice( 1 ).toUpperCase();
```
Comment (ciampo) [inline packages/components/src/color-picker/color-display.tsx]: Since `toHex` _"Returns the hexadecimal representation of a color. When the alpha channel value of the color is less than 1, it outputs #rrggbbaa format instead of #rrggbb."_ (from the docs),  i guess the `enableAlpha` property is not necessary anymore? Or should we add some explicit logic back in?

File: packages/components/src/color-picker/hsl-input.tsx [hunk 2]
```diff
@@ -1,53 +1,67 @@
...
-	const { h, s, l, a } = color;
+	const { h, s, l, a } = color.toHsl();
 
 	return (
 		<>
 			<InputWithSlider
-				min={ 1 }
-				max={ 360 }
+				min={ 0 }
+				max={ 359 }
```
Comment (ciampo) [inline packages/components/src/color-picker/hsl-input.tsx:24]: What's the reason for changing from `360` to `359`?

File: packages/components/src/color-picker/hsl-input.tsx [hunk 3]
```diff
@@ -1,53 +1,67 @@
...
 				label="Hue"
 				abbreviation="H"
-				value={ Math.trunc( h ) }
-				onChange={ ( nextH: number ) =>
-					onChange( { h: nextH, s, l, a } )
-				}
+				value={ h }
```
Comment (ciampo) [inline packages/components/src/color-picker/hsl-input.tsx:27]: What's the reason for removing the `Math.trunc` call?

File: packages/components/src/color-picker/use-deprecated-props.ts [hunk 4]
```diff
@@ -43,7 +51,7 @@ type LegacyColor =
  * @deprecated
  */
 export interface LegacyProps {
-	color: LegacyColor | undefined;
+	color: LegacyColor;
```
Comment (ciampo) [inline packages/components/src/color-picker/use-deprecated-props.ts]: I think the previous notation `LegacyColor | undefined` was more correct.

The `LegacyColor` type should not be intrinsically `undefined` — but it _can_ be undefined when passed to the component's props.

We should probably remove `undefined` from `LegacyColor` and update the `color` prop to be optional: `color?: LegacyColor;`

File: packages/components/src/color-picker/use-deprecated-props.ts [hunk 5]
```diff
@@ -62,51 +70,32 @@ export interface LegacyProps {
 function isLegacyProps( props: any ): props is LegacyProps {
 	return (
 		typeof props.onChangeComplete !== 'undefined' ||
-		typeof props.color === 'string' ||
+		typeof props.disableAlpha !== 'undefined' ||
```
Comment (ciampo) [inline packages/components/src/color-picker/use-deprecated-props.ts:72]: We could revert this change in case we decided to change the type of the `color` prop for the new `ColorPicker` back to `HSL | HSLA`

File: packages/components/src/color-picker/use-deprecated-props.ts [hunk 6]
```diff
@@ -62,51 +70,32 @@ export interface LegacyProps {
...
 		typeof props.color?.hex === 'string'
 	);
 }
 
-function getColorFromLegacyProps(
-	props: LegacyProps
-): ColorFormats.HSL | ColorFormats.HSLA | undefined {
-	if ( ! props.color ) {
+function getColorFromLegacyProps( props: LegacyProps ): string | undefined {
+	if ( props.color === undefined ) {
```
Comment (ciampo) [inline packages/components/src/color-picker/use-deprecated-props.ts]: Nit, but this way of checkin may be slightly more robust:

```suggestion
	if ( typeof props?.color === 'undefined' ) {
```

File: packages/components/src/color-picker/use-deprecated-props.ts [hunk 7]
```diff
@@ -22,13 +30,13 @@ type ColorPickerProps = ComponentProps< typeof ColorPicker >;
  * @deprecated
  */
 type LegacyColor =
+	| undefined
 	| string
 	| {
-			color: colorize.Instance;
```
Comment (ciampo) [inline packages/components/src/color-picker/use-deprecated-props.ts:27]: The removal of the `color` property from the `LegacyColor` type (and from the return value of `transformColorStringToLegacyColor`) was discussed and agreed on in https://github.com/WordPress/gutenberg/pull/34014#discussion_r705432911.

This this is a breaking change, we should add a [CHANGELOG](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md) entry

**Review by ciampo — COMMENTED** [review]
Thank you @jorgefilipecosta for working on this! The new `ColorPicker` component is getting more polished every week!

> I think we should follow the readme and make the component receive a string and pass a string to onChange. This way it becomes consistent with the other components like the color palette and custom gradient picker.
During these changes, we also remove the tinycolor2 package.

This is going to be the main point of conversation for this PR. I seem to remember that using the `HSL | HSLA` format for interfacing with the component was a specific choice — I'm going to cc @sarayourfriend who should have more context about this.

> on the readme we said it received a string color property representing the color

If what I just said above holds true, then this must have been overlooked in previous reviews. Thank you for spotting it!

Finally, we should add a changelog entry (the contents of which are still TBD based on the outcome of the previous conversation)

File: packages/components/src/color-picker/color-display.tsx (hunk 1 above)
Comment (jorgefilipecosta) [reply packages/components/src/color-picker/color-display.tsx]: Exactly given that colord outputs already in #rrggbbaa or #rrggbb we don't need this logic anymore.

File: packages/components/src/color-picker/hsl-input.tsx (hunk 2 above)
Comment (jorgefilipecosta) [reply packages/components/src/color-picker/hsl-input.tsx:24]: 360 is the same as 0. Colord automatically transforms 360 to 0 so we want to avoid a strange UI jump.

File: packages/components/src/color-picker/hsl-input.tsx (hunk 3 above)
Comment (jorgefilipecosta) [reply packages/components/src/color-picker/hsl-input.tsx:27]: tinycolor was strange some times integer values become decimal, on colord it seems that issue does not happen.

**Comment by jorgefilipecosta** [comment]
Hi @ciampo thank you for reviewing this PR.

> This is going to be the main point of conversation for this PR. I seem to remember that using the HSL | HSLA format for interfacing with the component was a specific choice — I'm going to cc @sarayourfriend who should have more context about this.

The color palette component that uses the color picker inside (but also includes the presets) has an API where value is string and onChange passes a string. That API is public for a long time and there was never feedback to change it. I think this component should just replicate that.
The most common usage of this component is to choose a color that is applied as CSS style so it is more useful if it passes and receives a string that can be directly used. If we pass objects the users of the component will have to convert the object back to a string to use it on CSS styles so the component will be harder to use by the WordPress community.

File: packages/components/src/color-picker/color-display.tsx (hunk 1 above)
Comment (ciampo) [reply packages/components/src/color-picker/color-display.tsx]: Got it! We should probably then remove the `enableAlpha` from the props destructuring, since it became an unused variable?

File: packages/components/src/color-picker/hsl-input.tsx (hunk 2 above)
Comment (ciampo) [reply packages/components/src/color-picker/hsl-input.tsx:24]: Got it, thank you! I has missed the change in the line above from `0` to `1`

**Comment by jorgefilipecosta** [comment]
Hi @ciampo, your feedback was applied let me know if there are other changes we should do.

**Comment by ciampo** [comment]
> Hi @ciampo, your feedback was applied let me know if there are other changes we should do.

Thank you for letting me know. I'm going to take a look at this soon — in the future, could you add the code changes to new commits, instead of amending and force pushing the same commit? It would make your changes much more explicit to identify and the review process easier

File: packages/components/CHANGELOG.md [hunk 8]
```diff
@@ -9,7 +9,12 @@
 ### Enhancements
 
 -   Removed the separator shown between `ToggleGroupControl` items ([#35497](https://github.com/WordPress/gutenberg/pull/35497)).
+-   The `ColorPicker` component property `onChangeComplete`, a function accepting a color object, was replaced with the property `onChange`, a function accepting a  string on  ([#35220](https://github.com/WordPress/gutenberg/pull/35220)).
+-  The property `disableAlpha`, was removed from the `ColorPicker` component. Use the new opposite property `enableAlpha` instead ([#35220](https://github.com/WordPress/gutenberg/pull/35220)).
 
+### Breaking Changes
+
+-   The `color` property a `tinycolor2` color object passed on `onChangeComplete` property of the `ColorPicker` component was removed. Please use the new `onChange` property that accepts a string color representation ([#35562](https://github.com/WordPress/gutenberg/pull/35562)).
```
Comment (ciampo) [inline packages/components/CHANGELOG.md:22]: Nit: adding an empty line before next section

```suggestion
-   The `color` property a `tinycolor2` color object passed on `onChangeComplete` property of the `ColorPicker` component was removed. Please use the new `onChange` property that accepts a string color representation ([#35562](https://github.com/WordPress/gutenberg/pull/35562)).

```

File: packages/components/src/color-picker/hsl-input.tsx (hunk 3 above)
Comment (ciampo) [reply packages/components/src/color-picker/hsl-input.tsx:27]: Alright, it looks like [`toHsl()` rounds the `h`, `s`, and `l` values](https://github.com/omgovich/colord/blob/c3402bc5f36de19e7defe3e4e45df5f7a2d940f8/src/colord.ts#L89), so there's no need to `Math.trunc` anymore here

File: packages/components/src/color-picker/component.tsx [hunk 9]
```diff
@@ -75,17 +72,24 @@ const ColorPicker = (
...
-		debouncedSetColor( nextValue );
-	};
-
-	// Use a safe default value for the color and remove the possibility of `undefined`.
-	const safeColor = getSafeColor( color );
+	const handleChange = useCallback(
+		( nextValue: Colord ) => {
+			debouncedSetColor(
+				nextValue.alpha() < 1
+					? nextValue.toRgbString()
```
Comment (ciampo) [inline packages/components/src/color-picker/component.tsx]: In the [README](https://github.com/WordPress/gutenberg/blob/a969d2840c634e1cdc11650c214760a33bed3230/packages/components/src/color-picker/README.md?plain=1#L35) we mention that the argument of the `onChange` callback is always a hex8 string, but from this line it looks like it could also be in the [`rgb()` string format](https://github.com/omgovich/colord/blob/master/README.md?plain=1#L167-L175).

We should probably change this to always use [`toHex`](https://github.com/omgovich/colord/blob/master/README.md?plain=1#L152) which returns a `hex` or `hex8` string (depending on the alpha value) ?

File: packages/components/src/color-picker/hex-input.tsx [hunk 10]
```diff
@@ -17,22 +17,19 @@ import { space } from '../ui/utils/space';
...
+		if ( ! colord( '#' + value ).isValid() ) {
 			throw new Error( 'Invalid hex color input' );
 		}
 	};
 
-	const colorized = colorize( color );
-	const value = enableAlpha
-		? colorized.toHex8String()
-		: colorized.toHexString();
+	const value = color.toHex();
```
Comment (ciampo) [inline packages/components/src/color-picker/hex-input.tsx]: Since `value` already appears as a local variable in other places inside this component, a small code readability improvement could be to

```diff
diff --git a/packages/components/src/color-picker/hex-input.tsx b/packages/components/src/color-picker/hex-input.tsx
index d2160f96d1..c17d8866fc 100644
--- a/packages/components/src/color-picker/hex-input.tsx
+++ b/packages/components/src/color-picker/hex-input.tsx
@@ -29,8 +29,6 @@ export const HexInput = ( { color, onChange, enableAlpha }: HexInputProps ) => {
 		}
 	};
 
-	const value = color.toHex();
-
 	return (
 		<ColorHexInputControl
 			prefix={
@@ -43,7 +41,7 @@ export const HexInput = ( { color, onChange, enableAlpha }: HexInputProps ) => {
 					#
 				</Spacer>
 			}
-			value={ value.slice( 1 ).toUpperCase() }
+			value={ color.toHex().slice( 1 ).toUpperCase() }
 			onChange={ ( nextValue ) => {
 				onChange( colord( '#' + nextValue ) );
 			} }
```

File: packages/components/src/color-picker/stories/index.js [hunk 11]
```diff
@@ -49,7 +49,7 @@ const Example = () => {
 		>
 			<ColorPicker { ...props } color={ color } onChange={ setColor } />
 			<div style={ { width: 200, textAlign: 'center' } }>
-				{ colorize( color ).toHslString() }
+				{ colord( color ).toHslString() }
```
Comment (ciampo) [inline packages/components/src/color-picker/stories/index.js]: For the purpose of showing the actual value of the `color` returned in the `onChange` callback, should we change this to just be

```suggestion
				{ color }
```

?

File: packages/components/src/color-picker/use-deprecated-props.ts [hunk 12]
```diff
@@ -62,51 +69,32 @@ export interface LegacyProps {
...
-	( hsla: ColorFormats.HSL | ColorFormats.HSLA ): LegacyColor => {
-		const color = colorize( hsla );
-		const rawHex = color.toHex();
-		const rgb = color.toRgb();
-		const hsv = toHsv( color );
-		const hsl = hsla;
-
-		const isTransparent = rawHex === '000000' && rgb.a === 0;
-
-		const hex = isTransparent ? 'transparent' : `#${ rawHex }`;
```
Comment (ciampo) [inline packages/components/src/color-picker/use-deprecated-props.ts:106]: Since this is a legacy adapter, we should not delete this logic (even if I agree that it doesn't make much sense) (see [the legacy component's implementation](https://github.com/WordPress/gutenberg/blob/8d8e07699df7c31fd89c07406356fb779de90b33/packages/components/src/color-picker/utils.js#L57-L61))

**Review by ciampo — COMMENTED** [review]
Thank you for giving a more detailed explanation about the change to use a `string` format instead of `HSL | HSLA` — **I actually agree that it could be a good solution here**, but I was slightly confused by the mismatch between the internal implementation and the README docs. We will also need to make sure that [the issue that caused the switch to the `HSL` format](https://github.com/WordPress/gutenberg/pull/33714#issuecomment-895234590) can't be replicated with this refactor either.

I had a deeper look and left a few more comments. I also checked the component in Storybook and I couldn't find any issues with it!

Having this component written in TypeScript definitely made this review much easier — it's a pity that we can't (yet) type the `hex` and `hex8` types more strictly than a `string`, but hopefully we'll get there!

File: packages/components/src/color-picker/use-deprecated-props.ts (hunk 12 above)
Comment (jorgefilipecosta) [reply packages/components/src/color-picker/use-deprecated-props.ts:106]: Hi @ciampo, I don't think we must keep this logic. It was never documented that for a transparent color we need to pass the string transparent as the hex value. In fact, I think passing transparent as the hex value goes against the expectation that a hex color is passed ( we are passing a named color instead) so I guess we can apply this change and remove this logic from our codebase.

**Comment by jorgefilipecosta** [comment]
Hi @ciampo thank you for another pass on this PR most of the suggestions were incorporated. I think this PR should be ready to merge.
Regarding the HSL to string I think even with HSL we still have the issue of flunky UI on the HSL picker because colors ended up serialized as strings if not inside the component at the block attributes level so the way to solve the issue seems to be a follow-up PR that adds some local state in the HSL picker keeping the API of the component the same receives strings and passes strings. I guess this PR is ready to merge.

File: packages/components/src/color-picker/use-deprecated-props.ts (hunk 12 above)
Comment (ciampo) [reply packages/components/src/color-picker/use-deprecated-props.ts:106]: I absolutely agree that this code doesn't make much sense — I'm just trying to be very careful about introducing unnecessary breaking changes.

Having said that, since `colordColor.toHex()` will output a hex8 string including the alpha channel when needed, I feel quite confident that this won't cause any issues (especially when used as a CSS value).

But let's keep an eye on potential breakages around the `transparent` keyword and let's be ready to revert the removal of this logic

**Review by ciampo — APPROVED** [review]
Thank you for working on this, @jorgefilipecosta !

> I think even with HSL we still have the issue of flunky UI on the HSL picker because colors ended up serialized as strings if not inside the component at the block attributes level

I'm not sure I follow entirely, but I think that, at this point, we should keep your current solution (i.e using hex strings) since it uses the same conventions as the previous `ColorPicker` and as the other color-related components.

We can always make changes at a later stage if we think that the component's UX needs improving

> so the way to solve the issue seems to be a follow-up PR that adds some local state in the HSL picker keeping the API of the component the same receives strings and passes strings.

That's an interesting approach that we should definitely investigate. The ideal solution would keep the public APIs unchanged, and would avoid exposing internal dependencies (e.g. `colord`).

Finally, I noticed that [this conversation](https://github.com/WordPress/gutenberg/pull/35562/commits/5240a49567758a22b2e2109d70fce978f2e5c419#r728014913) was marked as solved without being addressed — would you mind taking a quick look before merging?
