### PR TITLE
[Block Editor]: Fix selection by holding shift key for nested blocks

### LINKED ISSUE #33665: Shift-select in a group block doesn't select anything
## Description
Impossible to edit text after selecting several words with SHIFT key.

## Step-by-step reproduction instructions
1. Make a "group" with a text block;
2. Try to select several words using SHIF key

## Expected behaviour
Be able to do something, delete selected text, edit text block, etc.

## Actual behaviour
It's freezing the block and all blocks around. Impossible to edit nothing.

## Screenshots or screen recording (optional)
ezgif com-video-to-gif

## WordPress information
- WordPress version: 5.8
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes 2021

## Device information
- Device: Desktop
- Operating system: Mac OS Big Surr 11.2.2
- Browser: FireFox 90.0.2

### PR DESCRIPTION
**Pull request by ntsekouras**
Part of: https://github.com/WordPress/gutenberg/issues/35662
Fixes: https://github.com/WordPress/gutenberg/issues/33665

There are currently two bugs in selection when holding `shift` key that result in locking the user out of editing.

1. Pressing shift + click within a rich-text block nested inside a nested block like `Group`
2. Having a nested block selected and holding shift + click to another nested block with a different parent block - example two different `Group` blocks.

## Before
https://user-images.githubusercontent.com/548849/137452873-c8291abf-9919-4401-be67-741f2d071233.mov

and

https://user-images.githubusercontent.com/16275880/137484644-b09f0a3e-9dd1-45be-abfb-1ad26f2ec738.mov

## After

https://user-images.githubusercontent.com/16275880/137484658-e57d5a72-ff0f-4759-973c-158a5f5d2918.mov

In my videos the different `Group` blocks have different background colors.

### CODE REVIEW

File: packages/block-editor/src/components/block-list/use-block-props/use-multi-selection.js [hunk 1]
```diff
@@ -165,15 +165,29 @@ export function useMultiSelection( clientId ) {
...
+					// case where we select a single block. We also have to check
+					// the selectionEnd (clientId) not to be included in the
+					// `blockSelectionStart`'s parents because the click event is
+					// propagated.
+					const startParents = getBlockParents( blockSelectionStart );
 					if (
 						blockSelectionStart &&
-						blockSelectionStart !== clientId
+						blockSelectionStart !== clientId &&
+						! startParents?.includes( clientId )
```
Comment (ntsekouras) [inline packages/block-editor/src/components/block-list/use-block-props/use-multi-selection.js:177]: @ellatrix I'm not sure if there is a more elegant way to handle this or in another place..

File: packages/block-editor/src/components/block-list/use-block-props/use-multi-selection.js [hunk 2]
```diff
@@ -165,15 +165,29 @@ export function useMultiSelection( clientId ) {
...
+							...startParents,
+							blockSelectionStart,
+						];
+						const endPath = [
+							...getBlockParents( clientId ),
+							clientId,
+						];
+						const depth =
+							Math.min( startPath.length, endPath.length ) - 1;
+						multiSelect( startPath[ depth ], endPath[ depth ] );
```
Comment (ockham) [inline packages/block-editor/src/components/block-list/use-block-props/use-multi-selection.js:190]: It seems like this is pretty much the same logic as https://github.com/WordPress/gutenberg/blob/b29c09d63588c16f2d22cd7e8d994e02272e4a5f/packages/block-editor/src/components/block-list/use-block-props/use-multi-selection.js#L93-L104

Should we extract it into a small helper method, or share it otherwise?

**Review by ockham — APPROVED** [review]
Thanks Nik! Confirming that this fixes the issue. Code LGTM, too!

Awesome videos and e2e coverage! 👏

File: packages/block-editor/src/components/block-list/use-block-props/use-multi-selection.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-editor/src/components/block-list/use-block-props/use-multi-selection.js:177]: This is for when we shift+click in a parent of the selected block, right? What should the outcome be for that case? Do we need a test here too?

Comment (ockham) [reply packages/block-editor/src/components/block-list/use-block-props/use-multi-selection.js:177]: AFAIU, it's for this case:

> 1. Pressing shift + click within a rich-text block nested inside a nested block like `Group`

Currently, when you do that, you can't really edit the block anymore, see https://github.com/WordPress/gutenberg/issues/33665. So this line is supposed to fix that behavior. In practice, for what I see, it highlights the text between the cursor location, and the location that's being shift-clicked.

Comment (ockham) [reply packages/block-editor/src/components/block-list/use-block-props/use-multi-selection.js:177]: > Do we need a test here too?

I think it's covered by [this e2e test](https://github.com/WordPress/gutenberg/pull/35668/files#diff-fd2caeee0cb92da62fd4cdaca1b0888d65721b1a03df98ac142e0e3b9ef639c0R345-R366), isn't it?

**Review by ellatrix — APPROVED** [review]

File: packages/block-editor/src/components/block-list/use-block-props/use-multi-selection.js (hunk 1 above)
Comment (ntsekouras) [reply packages/block-editor/src/components/block-list/use-block-props/use-multi-selection.js:177]: >I think it's covered by this e2e test, isn't it?

Yes

File: packages/block-editor/src/components/block-list/use-block-props/use-multi-selection.js (hunk 2 above)
Comment (ntsekouras) [reply packages/block-editor/src/components/block-list/use-block-props/use-multi-selection.js:190]: I thought about it but in the second case we use the parents for another check before, so a shared util for our 2 cases would end up passing the start/end paths and just having the `Math.min` in there, so I'm not really sure it's worth it.. 

I'm going to merge and happy to follow up on this if it needs to 😄

**Comment by jasmussen** [comment]
I'm not sure if this PR is related, but I get the sense that it may have tried to fix an issue that is similar to what I'm seeing at the moment, which is that after having edited content for a bit, the title block becomes inert:

inert

I don't have specific steps to reproduce, other than to start editing some content, waiting for a bit, saving, then trying to edit the title. Sometimes it continues to work, sometimes it breaks.

**Comment by ntsekouras** [comment]
@jasmussen this PR had to do specifically with holding `shift` cases. I think @ellatrix had worked recently on some `title` selection issues.
