### PR TITLE
Fix controlled inner blocks parent block attributes updates

### LINKED ISSUE #35664: Changes not saving in FSE
### Description

When you change something in FSE e.g. add custom class, toggle layout settings etc. and click save, it does not save the changes. I'm facing the issue after updating to 11.5.0. The issue still exists in 11.7.0. If you switch back to 11.4.1 it works as expected.

### Step-by-step reproduction instructions

1. Open a template in FSE
2. Select Header/Footer
3. Add any custom class or toggle layout settings.
4. Save the changes and refresh the page.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/7956101/137462136-2e6cf24c-0e7d-45a0-b678-0934cc467a54.mp4

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #35664

I bisected and found that the problem was introduced in #34241. I scanned the code and I think I spotted the issue:
```jsx
	for ( const clientId of updatedClientIds ) {
		let current = clientId;
		do {
			if ( state.controlledInnerBlocks[ current ] ) {
				controlledParents.add( current );
				// If we reach a controlled parent, break out of the loop.
				break;
			} else {
				clientIds.add( current );
			}
			// Should stop on controlled blocks.
			current = state.parents[ current ];
		} while ( current !== undefined );
	}
```
	
It looks like the intent here was to traverse up and stop when reaching a block that has controlled inner blocks.

It has an unwanted side effect that if it's only the parent block (and not the controlled inner blocks) that changed the parent is also skipped from being added to the clientIds list.

Instead I think it needs to check the parent on each loop, and only traverse up if the parent isn't a controlled inne rblock

## How has this been tested?
1. Open the site editor
2. Select the Header from List View
3. Change colors from the sidebar
4. Click save. Observe that the sidebar only shows changes to the Header template part
5. Save those changes
6. Reload, observe changes are now retained.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by youknowriad** [comment]
Looking at the diff here, there are some changes that make me worry. Let me dig deeper into the issue.

**Comment by talldan** [comment]
It should be almost exactly the same, the only difference is that if only the block wrapper had updates, that gets added to clientIds list now. My thinking is that this needs to bubble up to the parent entity (e.g. if the only the template part block wrapper is edited, that should still save to the template).

File: packages/block-editor/src/store/reducer.js [hunk 1]
```diff
@@ -246,15 +246,18 @@ function updateParentInnerBlocksInTree( state, tree, updatedClientIds ) {
...
 		do {
-			if ( state.controlledInnerBlocks[ current ] ) {
-				controlledParents.add( current );
+			clientIds.add( current );
+
+			const parent = state.parents[ current ];
+			if ( state.controlledInnerBlocks[ parent ] ) {
+				// Should stop on controlled blocks.
 				// If we reach a controlled parent, break out of the loop.
+				controlledParents.add( current );
```
Comment (youknowriad) [inline packages/block-editor/src/store/reducer.js:259]: Should this be `controlledParents.add( parent );` ?

Comment (talldan) [reply packages/block-editor/src/store/reducer.js:259]: Oh yes, it should be 😄

File: packages/block-editor/src/store/reducer.js [hunk 2]
```diff
@@ -246,15 +246,18 @@ function updateParentInnerBlocksInTree( state, tree, updatedClientIds ) {
 	for ( const clientId of updatedClientIds ) {
 		let current = clientId;
 		do {
-			if ( state.controlledInnerBlocks[ current ] ) {
-				controlledParents.add( current );
+			clientIds.add( current );
```
Comment (youknowriad) [inline packages/block-editor/src/store/reducer.js]: If I'm not wrong, I think the "innerBlocks" of the "controlled blocks" is supposed to be empty, while the "inner blocks" of the `controlled||{clientId}` is supposed to be "full". 

So in the case of an "updatedClientId" that is also a "controlled parent", we should not add it to `clientIds` (to avoid having its inner blocks filled) but we should continue looping

Comment (talldan) [reply packages/block-editor/src/store/reducer.js]: Ok, I think I see. So down on line 268 the inner blocks for a controlled parent shouldn't be expanded?

But I guess that parent should still be present, just with empty inner blocks?

Comment (youknowriad) [reply packages/block-editor/src/store/reducer.js]: > But I guess that parent should still be present

Not sure what you mean by "present" here but yeah, the idea is that the parent of that block should still update its inner blocks but not the block itself since its inner blocks are always an empty thing.

Comment (talldan) [reply packages/block-editor/src/store/reducer.js]: Yes, I get it now. Ok, will find another way!

**Comment by talldan** [comment]
So I think what I've unearthed is that there are two separate bugs.

1. When updating a template part's attributes only (not the inner blocks), the changes cannot be saved. This is the original bug that I've tried to fix and it's now working in this PR. The issue was that the parent of the template part in the tree wasn't being updated, it still had stale attributes. The reason is that the code that I indicated in the description wasn't traversing up from a modified controlled parent, and so wasn't updating the controlled parent's parent.
2. When updating a template part's attributes only (not the inner blocks), the template part will still display as an entity needing to be saved. I think this is because the item in the tree with the `controlled||` prefix is always updated and so the object reference changes, causing it to be considered dirty. I haven't been able to come up with a way to fix this.

**Comment by talldan** [comment]
The failing tests indicate there are more issues with this fix too.

@youknowriad any other ideas how to solve the problems?

File: packages/block-editor/src/store/reducer.js [hunk 3]
```diff
@@ -246,15 +246,20 @@ function updateParentInnerBlocksInTree( state, tree, updatedClientIds ) {
 	for ( const clientId of updatedClientIds ) {
 		let current = clientId;
 		do {
+			clientIds.add( current );
+
 			if ( state.controlledInnerBlocks[ current ] ) {
 				controlledParents.add( current );
```
Comment (youknowriad) [inline packages/block-editor/src/store/reducer.js]: I guess if we avoid this on the first level of the loop (when clientId is part of `updatedClientIds`) to avoid marking its innerBlocks as dirty. which should resolve your second point maybe ?

Comment (youknowriad) [reply packages/block-editor/src/store/reducer.js]: Maybe just moving this line to the check line 256?

**Comment by youknowriad** [comment]
Both of your points 1 and 2 are logical to me. That said, I feel the implementation we have is probably too complex for nothing. I'll see if there's a way to make it a bit more simple.

**Comment by youknowriad** [comment]
Ok, I think what's confusing is that sometimes the function is called with the actual blocks that were modified (attributes), but sometimes it's called with their parents, so it's hard to reason about, I'm thinking we should add another argument to separate these two use-cases.

**Comment by youknowriad** [comment]
I think I remove the ambiguity with the last update, let's see.

**Comment by talldan** [comment]
Thanks for iterating on this.

Still some failing tests I see. I'll try to give this a bit more testing on Monday to see what the issue is there.

File: packages/block-editor/src/store/selectors.js [hunk 4]
```diff
@@ -1980,7 +1980,7 @@ export const __experimentalGetPatternTransformItems = createSelector(
 		if (
 			blocks.some(
 				( { clientId, innerBlocks } ) =>
-					innerBlocks.length ||
+					innerBlocks?.length ||
```
Comment (talldan) [inline packages/block-editor/src/store/selectors.js]: @youknowriad This should hopefully resolve the failing tests. 🤞 

It looks like with the recent change, some blocks in state now won't have the `innerBlocks` property. I think the reason is that if a block only ever gets updated using the `false` option it won't ever reach this line of code that adds the property (only the parents will):
https://github.com/WordPress/gutenberg/pull/35827/files#diff-3c4b969f7547d02bc04a2c554e0f7d21da07c3f779714acf02800ee0341b50d9R276-R280

The alternative fix would be to ensure the innerBlocks property is present, but that might involve changing the `updateParentInnerBlocksInTree` again. Let me know what you think.

edit: also updated the failing unit test in 14bcacf, that had the same issue.

Comment (talldan) [reply packages/block-editor/src/store/selectors.js]: Seems like there's also this code that expects `innerBlocks` to be defined, which is causing the remaining failing test:
https://github.com/WordPress/gutenberg/blob/d209b27a85d2d89cecc53853c5683f4a067da971/packages/blocks/src/api/serializer.js#L265-L283

Perhaps it's better to look at fixing the root cause.

Comment (youknowriad) [reply packages/block-editor/src/store/selectors.js]: yes, It seems we should consider adding an empty inner blocks in some init code somewhere to avoid that. Some third-party code could also rely on it.

Comment (talldan) [reply packages/block-editor/src/store/selectors.js]: @youknowriad Did some more staring at this problem, and I think the cause is the `UPDATE_BLOCK` case, which isn't passing in a valid tree to `updateParentInnerBlocksInTree`. Hopefully the change in 04d1853 is ok.

We could also add some initialization code, but I don't think it's necessary right now.

**Review by youknowriad — APPROVED** [review]
This makes sense. Thanks Dan :)

**Comment by talldan** [comment]
Thanks for your help with this one, glad we could get it sorted!

**Comment by mtias** [comment]
Thanks for catching and looking into this
