### PR TITLE
Server side renderer: Fix errors in template part editor context

### LINKED ISSUE #29236: Navigation Block: cannot "Add all pages" when directly editing a Template Part
## Description
Upon adding a Navigation Block while directly editing a Template Part (eg Appearance → Template Parts), clicking "Add all pages" will produce the error `Error loading block: Invalid parameter(s): post_id`

Note that the error does not appear directly in the full Site Editor, even when the Navigation Block is added to a Template Part within that context.

## Step-by-step reproduction instructions
1. Go to Appearance → Template Parts with a FSE-enabled theme active
2. Create a new Template Part (or edit existing)
3. Add a Navigation block (either horizontal or vertical)
4. Click "Add all pages" 
5. Note the error `Error loading block: Invalid parameter(s): post_id`

## Expected behaviour
All pages added

## Actual behaviour
Error

## Screenshots or screen recording (optional)
image

## Code snippet (optional)
The error happens in this REST API request:

```
/wp-json/wp/v2/block-renderer/core/page-list?context=edit&post_id=q%2F%2Ftemplate-part-5&_locale=user
```

That `post_id` looks fishy indeed. It's omitted in the Site Editor context.

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 10.0.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Desktop
- Operating system: macOS 11.2.1
- Browser: Chrome 88

### LINKED ISSUE #29237: Navigation block: Trying to add link results in block error when editing in Template Parts
## Description

In trying to use the navigation block, I'm unable to add Page links and encounter an error message: "This block has encountered an error and cannot be previewed." This ONLY happens when in the Template Parts editing section. It works just fine in the Site Editor. 

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Go to Site Editor 
2. Use the W Menu to browse to the Header Template Part (Template Parts > Header)
3. Add a navigation block
4. Use the "start empty" option
5. Try to add a link and see error. 

## Expected behaviour

I expected to be able to edit the navigation block within the template parts screen. This works just fine when in the site editor experience but breaks when viewing the template part specifically. 

## Actual behaviour

Run into a block error. 

## Screenshots or screen recording (optional)

Video:

https://user-images.githubusercontent.com/26996883/108778544-bf138f00-7522-11eb-94ff-6f084be85b54.mov

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 10.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, TT1 Blocks

### PR DESCRIPTION
**Pull request by david-szabo97**
## Description
Fixes https://github.com/WordPress/gutenberg/issues/29237 
Fixes https://github.com/WordPress/gutenberg/issues/29236
In https://github.com/WordPress/gutenberg/pull/27910 we introduced a custom ID for template and template parts. Server side renderer tried to use these IDs but failed since they aren't real post IDs. To fix this, this PR tries to use `wp_id` if possible, otherwise fallback to `id`.

## How has this been tested?
1. Open wp-admin
2. Go to Themes -> Template Parts
3. Edit a template part
4. Insert any of these blocks:
    - Page List
    - RSS
    - Archives
    - Calendar
    - Latest Comments 
    - Post Comments Count
5. See error: "Error loading block: Invalid parameter(s): post_id"

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by david-szabo97** [comment]
@youknowriad Do you think there is a better way to handle this? 🤔

**Comment by youknowriad** [comment]
Do you know how this post id is used server side by the server side render endpoint? It seems the best solution here is to update that endpoint instead?

**Comment by youknowriad** [comment]
Or may just don't pass the "id" in these situations because a "template" or "template part" is not really a post.

**Comment by david-szabo97** [comment]
It uses the `post_id` to setup the postdata context for the rendered blocks.
https://developer.wordpress.org/reference/classes/wp_rest_block_renderer_controller/

I think it's safe to omit the `currentPostId` if the `entity.id` is not an integer. But I'm 100% sure about the consequences. Other blocks might read the current post's data (which would be the `template_part` in this case). Those blocks will fail if we don't provide the correct ID.

I don't like that we need to add this `currentPost.wp_id || currentPost.id`, but this seems the best solution that won't cause any troubles in the future.

**Comment by jeyip** [comment]
@david-szabo97 

Are we still trying to push this ticket forward? I'm testing per the instructions in #29237 and #29236 and can't seem to replicate the described issues.

**Comment by david-szabo97** [comment]
@jeyip You need to directly edit a template part. Appearance -> Template Parts -> Edit a template part

**Comment by jeyip** [comment]
> You need to directly edit a template part. Appearance -> Template Parts -> Edit a template part

Yeah I had tried that previously as well without luck. My mistake for not posting a GIF of it. I'll try again and capture a video of the results.

**Comment by jeyip** [comment]
Still no luck reproducing it 😞

**Comment by david-szabo97** [comment]
Looks like "Navigation block > Page Link" doesn't use ServerSideRender anymore. Other blocks are still failing like RSS and "Navigation block > Page List". Any block will fail that use ServerSideRender:
- Page List
- RSS
- Archives
- Calendar
- Latest Comments 

(Updated PR description)

File: packages/server-side-render/src/index.js [hunk 1]
```diff
@@ -18,10 +18,10 @@ const EMPTY_OBJECT = {};
 const ExportedServerSideRender = withSelect( ( select ) => {
 	const coreEditorSelect = select( 'core/editor' );
 	if ( coreEditorSelect ) {
-		const currentPostId = coreEditorSelect.getCurrentPostId();
-		if ( currentPostId ) {
+		const currentPost = coreEditorSelect.getCurrentPost();
+		if ( currentPost ) {
 			return {
-				currentPostId,
+				currentPostId: currentPost.wp_id || currentPost.id,
```
Comment (Addison-Stavlo) [inline packages/server-side-render/src/index.js]: It would probably be good to add a comment here to clarify why we are favoring `wp_id`.

**Review by Addison-Stavlo — COMMENTED** [review]
Tested, and all works as expected!

I was able to repro the current issue with RSS blocks in the stand alone template and template part post editors.  This PR fixes the issues.

I think this fix is simple enough and a fair solution, but I think we should at least comment as to why we are doing this as it is a bit unexpected for those unfamiliar to FSE templates/parts entities.

**Comment by jeyip** [comment]
## Testing
Like Addie, I found that everything worked as expected once I reproduced the issue 🙂

### Behavior
- [x] Latest comments block renders without error
- [x] Page list block renders without error
- [x] Calendar block renders without error

### Requirements
- [x] Edge
- [x] Firefox
- [x] Safari
- [x] Chrome

**Comment by jeyip** [comment]
> Other blocks might read the current post's data (which would be the template_part in this case). Those blocks will fail if we don't provide the correct ID.

Do you happen to know examples of blocks that would fail today? Not saying this has to be done immediately, but I'm wondering if there's some sort of design we could implement to handle this situation gracefully, similar to how templates selected from the FSE navigation menu will render content placeholders. I might be off-base with this though, so would love to hear everyone's thoughts.

**Comment by jeyip** [comment]
> I don't like that we need to add this currentPost.wp_id || currentPost.id, but this seems the best solution that won't cause any troubles in the future.

I'm not a big fan of this solution either. Using two separate ids is quite confusing, but with that being said, I think that the inline comment helps.

> Other blocks might read the current post's data (which would be the template_part in this case). Those blocks will fail if we don't provide the correct ID.

There were some alternative approaches mentioned by @youknowriad. 
1. Update the server side render endpoint instead of the Gutenberg client. 
    - It seems like this issue would be equally confusing for core WordPress developers if we moved the logic in this PR into the server side render endpoint.
    - Not really convinced by this approach.
2. Or maybe just don't pass the "id" in these situations
    - I think this is worth exploring more. I left a comment above regarding this approach.
    
 +1 from me whenever we resolve the discussions around approach # 2

**Comment by david-szabo97** [comment]
> Other blocks might read the current post's data (which would be the template_part in this case). Those blocks will fail if we don't provide the correct ID.

"Might" 😄 So far every server side rendered block seem to work fine.

**Comment by jeyip** [comment]
@david-szabo97 Nice! I'll re-test this in a bit.

**Comment by jeyip** [comment]
Re-tested functionality of the calendar, latest comments, and page list blocks from Appearance -> Template Parts -> Edit a template part.

Everything works as expected 🎉

**Review by jeyip — APPROVED** [review]
+1 from me! I'd wait for one more set of 👀 since I don't have a lot of experience with SSR blocks, and to make sure we're not missing anything.

**Review by Addison-Stavlo — APPROVED** [review]
Approving per my previous testing and comments.
