### PR TITLE
Block Editor: Fix stale dependencies of selectors depending on editorTool preference

### LINKED ISSUE #66463: Template part selecting and editing unavailable in “Write” mode
When the editor is set to “Design” mode, users can select template parts, which renders an “Edit” button allowing isolated editing of the template part. However, this functionality is unavailable in “Write” mode.

But if you enter the editor, turn on write mode, and open list view, template parts aren't visible in the list view nor can you edit them. I can replicate this with Twenty Twenty-Five, as well as other block themes with both 6.7 trunk & Gutenberg trunk on:

https://github.com/user-attachments/assets/50bfdd22-c85d-4138-be23-81ed0e307b33

### PR DESCRIPTION
**Pull request by mcsf**
Fixes #66463

## What?
This fixes a bug wherein changes to the Write/Design mode selection don't trigger a re-render of the block list view.

## How?
The `state.editorMode` reducer was removed in #65945 in favour of persisted user preference `core.editorTool`. Selector `__unstableGetEditorMode` should be used instead. This fix correctly adopts the latter as a dependency of selectors `getEnabledClientIdsTree` and `getInsertBlockTypeDependants`.

## Testing Instructions
See parent issue. In short: in the site editor, keep the list view open, then switch between Write and Design modes, and confirm that the list view updates to show/hide certain blocks, such as template parts.

### CODE REVIEW

**Comment by annezazu** [comment]
You are magic 🧙🏼 Works great for me, both when switching in the editor and in leaving/returning:

https://github.com/user-attachments/assets/48761ac6-781f-4f3b-a029-ddac0eaed4a3

**Review by annezazu — APPROVED** [review]
Can't speak to the code but can speak to the outcome. Works great!

**Review by xavier-lc — APPROVED** [review]
I had the same changes, thanks for the PR!

**Review by youknowriad — APPROVED** [review]

**Comment by talldan** [comment]
Pushed a commit to fix the failing tests. It looks like because `__unstableGetEditorMode` is a registry selector, all the other selectors that now use it as a dependency have to be registry selectors too.

File: packages/block-editor/src/store/private-selectors.js [hunk 1]
```diff
@@ -116,7 +117,7 @@ export const getEnabledClientIdsTree = createSelector(
 		state.blockEditingModes,
 		state.settings.templateLock,
 		state.blockListSettings,
-		state.editorMode,
+		__unstableGetEditorMode( state ),
```
Comment (ellatrix) [inline packages/block-editor/src/store/private-selectors.js]: This seems wrong still, shouldn't it use `select( store )`?

Comment (talldan) [reply packages/block-editor/src/store/private-selectors.js]: Pushed a commit, does that look better?

Comment (talldan) [reply packages/block-editor/src/store/private-selectors.js]: Looks like some tests need to be updated now.

Comment (talldan) [reply packages/block-editor/src/store/private-selectors.js]: Should now be fixed too.

Comment (mcsf) [reply packages/block-editor/src/store/private-selectors.js]: Thanks for the fixes, @talldan! This was an end-of-day PR for me, and I didn't wait for the tests...

Comment (talldan) [reply packages/block-editor/src/store/private-selectors.js]: No worries, thought I'd help out on the night shift, as it looked fairly urgent 😄

**Comment by mcsf** [comment]
Cherry-picked for 19.6.1.
