### PR TITLE
Editor: Avoid scheduling autosave if same edit reference as last completion

### LINKED ISSUE #12318: Autosave continues to trigger for published posts when no changes applied
**Describe the bug**

I discovered that autosave triggers even when there were no changes applied only for the published post. It works perfectly fine for drafts.

**To Reproduce**
1. Create a post (it isn't related to demo post only), write some content and publish it.
2. Reopen your published post.
3. Open network tab in your browser's developer tools.
3. Change something in one of the blocks.
4. Observer autosave being triggered after your changes were autosaved.

**Expected behavior**
Autosave is triggered only once after content in the published post has changed.

**Screenshots**
autosave-published-post

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 70

### PR DESCRIPTION
**Pull request by aduth**
Fixes #12318 

This pull request seeks to resolve an issue where autosaves will repeatedly occur when an edit is made to a published post. As explained in https://github.com/WordPress/gutenberg/issues/12318#issuecomment-441671741 , this is a consequence of a published post's autosave occurring as a revision, not a proper save. The post is still in an "unsaved" state, in the sense that the user has not yet Updated the post.

With these changes, an autosave will not be scheduled after a prior autosave had completed until an explicit edit occurs, even if the post is dirty or autosaveable. 

**Implementation notes:**

For posterity's sake, there are some specific intricacies of the autosave flow which may appear to be redundant with the logic included here, but which still serve an independent role. Namely, the re-dirtying of an autosaved published post performed as a consequence of:

https://github.com/WordPress/gutenberg/blob/874321773aff9be87b591e63c5fc606ede9872ac/packages/editor/src/store/effects/posts.js#L143-L150

https://github.com/WordPress/gutenberg/blob/874321773aff9be87b591e63c5fc606ede9872ac/packages/editor/src/store/selectors.js#L124-L150

To reiterate, it is _correct_ that a post is considered dirty after a published post is autosaved. The user should be prompted when attempting to navigate away. It's because of this distinction that an additional "has autosaved for edits reference" is included here.

It may, however, be worth considering for future refactoring to remove [the `isEditedPostAutosaveable` selector](https://github.com/WordPress/gutenberg/blob/874321773aff9be87b591e63c5fc606ede9872ac/packages/editor/src/store/selectors.js#L484-L515) in favor of dirtiness conditions, or reflecting the last autosave which had occurred. Currently, the recurring autosave occurs because `hasChangedContent` will return `true` due to the re-dirtying behavior described above.

**Testing instructions:**

Repeat steps to reproduce from #12318, verifying by Network DevTools activity that only a single autosave occurs for a single edit to a published post.

Verify that after an autosave occurs, continued edits will still autosave.

**Pending:**

This is worth testing via an end-to-end test.

### CODE REVIEW

File: packages/editor/src/components/autosave-monitor/index.js [hunk 1]
```diff
@@ -7,14 +7,26 @@ import { withSelect, withDispatch } from '@wordpress/data';
...
-		const { isDirty, editsReference, isAutosaveable } = this.props;
+		const { isDirty, editsReference, isAutosaveable, isAutosaving } = this.props;
+
+		if ( editsReference !== prevProps.editsReference ) {
+			this.didAutosaveForEditsReference = false;
+		}
+
+		if ( ! isAutosaving && prevProps.isAutosaving ) {
+			this.didAutosaveForEditsReference = true;
+		}
```
Comment (danielbachhuber) [inline packages/editor/src/components/autosave-monitor/index.js]: It'd probably useful at this point to include inline comments throughout this entire function that explain the idiosyncrasies of these variables.

Comment (aduth) [reply packages/editor/src/components/autosave-monitor/index.js]: Yep, that would be sensible.

Comment (aduth) [reply packages/editor/src/components/autosave-monitor/index.js]: Added in rebased fdd44b2.

File: packages/editor/src/components/autosave-monitor/test/index.js [hunk 2]
```diff
@@ -82,6 +82,28 @@ describe( 'AutosaveMonitor', () => {
...
+			wrapper.setProps( { isDirty: false, isAutosaving: true, isAutosaveable: true, editsReference: beforeReference } );
+			toggleTimer.mockClear();
+			wrapper.setProps( { isDirty: true, isAutosaving: false, isAutosaveable: true, editsReference: beforeReference } );
+
+			expect( toggleTimer ).toHaveBeenCalledWith( false );
+
+			// Once edit occurs after autosave, resume scheduling.
+			wrapper.setProps( { isDirty: true, isAutosaving: false, isAutosaveable: true, editsReference: afterReference } );
+
+			expect( toggleTimer ).toHaveBeenCalledWith( false );
```
Comment (tofumatt) [inline packages/editor/src/components/autosave-monitor/test/index.js]: Maybe I'm mis-reading the test, but I would expect this to test for something different. Now the post is dirty, isn't autosaving, is autosavable, and has a different `editsReference`, but the expectation is the same.

I don't quite follow 🤷‍♂️

**Review by tofumatt — COMMENTED** [review]
This is kinda confusing logic to follow and I don't quite understand the test, but maybe if explained a bit more I would. The code seems fine but I don't grok the test.

File: packages/editor/src/components/autosave-monitor/test/index.js (hunk 2 above)
Comment (aduth) [reply packages/editor/src/components/autosave-monitor/test/index.js]: > Maybe I'm mis-reading the test, but I would expect this to test for something different.

You're totally right. We expect `toggleTimer` to have been called with `true`, which it _is_, but as written `toHaveBeenCalledWith` would consider both this and the prior invocation (since we didn't clear mock calls between). So while it's true that it had been called with `false`, this was not what we're testing.

I've updated the test so that it explicitly checks that the second time around, it's called with `true`.

**Comment by aduth** [comment]
In case it has an impact on how people prioritize reviewing this: Without this change, published posts will currently autosave infinitely after an initial change is made to a block.

File: packages/editor/src/components/autosave-monitor/index.js [hunk 3]
```diff
@@ -53,6 +73,7 @@ export default compose( [
 			isDirty: isEditedPostDirty(),
 			isAutosaveable: isEditedPostAutosaveable(),
```
Comment (youknowriad) [inline packages/editor/src/components/autosave-monitor/index.js]: It definitely does feel like this selector is useless or doesn't have the same meaning as its name.

**Review by youknowriad — APPROVED** [review]
Thanks for the fix.
