### PR TITLE
Template Part: Fix 'isMissing' condition check

### LINKED ISSUE #36510: Template part block doesn't handle a missing template part entity
### Description

When a template part block's associated template part entity/post is missing, the block is designed to show a warning to the user:
https://github.com/WordPress/gutenberg/blob/39f883e503f05aac223fe9d9d03a49d6279192a4/packages/block-library/src/template-part/edit/index.js#L120-L139

Unfortunately this is never shown since the code that determines `isMissing` doesn't work. It uses the value from `getEditedEntityRecord` which always returns a (truthy) object when resolved.

I'm also unsure about this comment next to that code
> A new template part is automatically created if we have any inner blocks but no entity.

This might be outdated as I can't see any evidence that this happens.

To solve this, some design guidance will probably be needed to determine the right behavior.

<strike>Related is #36507, which fixes the same issue in the navigation block. In that change we make the nav block go back to its placeholder when the associated menu id deleted or non-existent.</strike> That regressed and the message is back again 😞 .

### Step-by-step reproduction instructions

1. Add a paragraph with some text in the site editor
2. Make it a template part using the 'Make template part' option in the block settings menu, give it a name, and create it.
3. Save all the changes
4. In wp-admin, navigate to Appearance > Template Parts and delete the template part you just created
5. Go back to the site editor
6. Observe that the template part made in step 2 is now empty. Blocks can be added to it, but they can't be saved.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WordPress trunk
Gutenberg trunk
Brave on Mac OS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
PR fixes incorrect `isMissing` condition check. The `getEditedEntityRecord` will return an empty object when the entity isn't available.

Fixes #36510.

## How has this been tested?

1. Add a paragraph with some text in the site editor
2. Make a template part using the 'Make template part' option in the block settings menu, give it a name, and create it.
3. Save all the changes
4. Navigate to Site Editor > Template Parts (using navigation sidebar) and delete the template part you just created
5. Go back to the site editor
6. Observe that the template part made in step 2 is now empty. Blocks can be added to it, but they can't be saved.

_Adapted from #36510._

## Screenshots 
CleanShot 2021-12-14 at 17 24 28

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-library/src/template-part/edit/index.js [hunk 1]
```diff
@@ -99,7 +104,7 @@ export default function TemplatePartEdit( {
 			return {
 				innerBlocks: getBlocks( clientId ),
 				isResolved: hasResolvedEntity,
-				isMissing: hasResolvedEntity && ! entityRecord,
+				isMissing: hasResolvedEntity && isEmpty( entityRecord ),
```
Comment (ntsekouras) [inline packages/block-library/src/template-part/edit/index.js:107]: Does this always return an empty object? In general could we adjust the check without adding the lodash dependency?

Comment (Mamaduka) [reply packages/block-library/src/template-part/edit/index.js:107]: The `getEditedEntityRecord` will return an object. Empty if no edited entity was found.

https://github.com/WordPress/gutenberg/blob/22814c75b0c0041493f791399c70299a037bf3f3/packages/core-data/src/selectors.js#L491-L495

I thought about using `Object.entries(entityRecord).length === 0`, but `isEmpty` is more clear IMO, and we're already using lodash in other blocks.

**Review by talldan — APPROVED** [review]
Looks good, thanks @Mamaduka!

File: packages/block-library/src/template-part/edit/index.js (hunk 1 above)
Comment (ntsekouras) [reply packages/block-library/src/template-part/edit/index.js:107]: In general there were discussion and and an effort to loose lodash dependencies. It's not a big deal for sure, but one could argue that since we know that it returns an `object`, a specific js check like `Object.keys` makes it also clear about what  type we are expecting.

Comment (Mamaduka) [reply packages/block-library/src/template-part/edit/index.js:107]: Thanks, Nik, and it makes sense if we're trying to lose `lodash` dep. I will keep it in mind for the future.
