### PR TITLE
Drag and drop: enable for multi selection

### LINKED ISSUE #7283: Can't Drag 'n Drop Multiple blocks at once
After selecting multiple blocks, you can't then drag 'n drop them. You can only Drag 'n Drop a single block at a time. Since every single paragraph is forced into it's own block, it's going to be very frustrating and slow if we can only move one block at a time.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select multiple blocks
2. Try to drag and drop those blocks to another position

_mac osSierra 10.12.1
Firefox Quantum 60.0.2 (64-bit)
Gutenberg 3.0.1_

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #7283.

There's nothing to stop us from allowing multiple blocks to be dragged and dropped since #23024. We don't have put them in a clone, and it won't be a huge thing you'll have to move around.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-editor/src/components/block-draggable/draggable-chip.js [hunk 1]
```diff
@@ -43,6 +43,7 @@ export default function BlockDraggableChip( { clientIds } ) {
 					<FlexItem>
 						<BlockIcon icon={ icon } />
 					</FlexItem>
+					<FlexItem>{ `(${ clientIds.length })` }</FlexItem>
```
Comment (talldan) [inline packages/block-editor/src/components/block-draggable/draggable-chip.js:46]: This might need some design adjustments, but not a blocker right now.

**Review by talldan — APPROVED** [review]
This looks good to me and will be a really valuable feature for many users.

The only thing I noticed in testing is that multi-selected blocks aren't removed when a user starts to drag, which is different to the way singularly selected blocks behave.

**Comment by ellatrix** [comment]
> The only thing I noticed in testing is that multi-selected blocks aren't removed when a user starts to drag, which is different to the way singularly selected blocks behave.

Fixed in 0969d4a.
