### PR TITLE
Focus block selection button only in navigation mode

### LINKED ISSUE #59741: Keep the inserter open when a pattern is inserted from zoom out mode
To allow for a full composition view, the Inserter should remain open when I pick a pattern to add to my site. This way I can pick as many patterns as I want, without getting "interrupted" with the Inserter closing unexpectedly.

Also, the Inserter already remains open when _not_ in zoom-out; it would be consistent to have it remain open when zoom-out is engaged. 

### Current

https://github.com/WordPress/gutenberg/assets/1813435/e3683ff8-bae5-406b-b7ce-c543b661297f

### PR DESCRIPTION
**Pull request by draganescu**
## What?

Closes #59741

## Why?

To avoid flickering UI while assembling a page from multiple patterns.
To keep the UI behaviour consistent between editor modes.

## How?

Manually place focus on the block selection button component only in navigation mode.

## Testing Instructions

1. In the site editor
2. Open a template
3. Open the inserter
4. Switch to the patterns tab
5. Open a category
6. Insert a few patterns
7. _Notice the inserter does not close_

### Testing Instructions for Keyboard

N/A

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/107534/fc4cf1ce-4319-4673-811d-7d911d97117e

### CODE REVIEW

File: packages/block-editor/src/components/block-tools/block-selection-button.js [hunk 1]
```diff
@@ -123,10 +123,11 @@ function BlockSelectionButton( { clientId, rootClientId } ) {
...
 	useEffect( () => {
-		ref.current.focus();
-
-		speak( label );
-	}, [ label ] );
+		if ( editorMode === 'navigation' ) {
+			ref.current.focus();
+			speak( label );
+		}
+	}, [ label, editorMode ] );
```
Comment (jeryj) [inline packages/block-editor/src/components/block-tools/block-selection-button.js:130]: I'm unsure about this. It seems the core issue is that focusing this shouldn't automatically close the inserter. We're going to need to be able to have focus on the zoom-out mode toolbar and also stay in zoom-out mode. For example: 
- Insert a new pattern
- Click on the revealed pattern toolbar to move the pattern up/down.
- Pattern inserter is closed

**Review by jeryj — APPROVED** [review]
Can we add a comment/TODO to remove this check once we're able to have focus on the zoom out view toolbar and the inserter stays open?

**Comment by draganescu** [comment]
I'll add the comment in a PR that removes the block name and brings over the drag button.
