### PR TITLE
Notes: Fix new note creation from the List View

### LINKED ISSUE #75451: Notes: Adding a note via List View can result in the note being added to the wrong block
### Description

Notes always seem to be added to the selected block.

In List View a user is able to add a note to an unselected block, but when doing so the note ends up on the selected block.

### Step-by-step reproduction instructions

1. Add two blocks, say a heading and a paragraph
2. Open list view
3. Click on the paragraph block to select it
4. Try adding a note to the heading block via the settings menu in List View, but do so without selecting the block
5. Observe that the note is still incorrectly added to the paragraph block.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/90fb302f-943f-4ab5-be7b-f5988b78c73a

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes #75451.

PR adds special handling when the "Add Note" action is triggered from the List View, where block selection isn't required to open the Options dropdown for a block.

## Testing Instructions
1. Open a post or page. 
2. Add a couple of blocks.
3. Try adding a new note for a block via List View, without selecting a block.
4. Selection should move to the block, and a new note form should be displayed.

### Testing Instructions for Keyboard
Same.

## Screenshots or screencast 

https://github.com/user-attachments/assets/d77e38ce-440f-49fa-bd1c-e937939eb494

### CODE REVIEW

File: packages/editor/src/components/collab-sidebar/index.js [hunk 1]
```diff
@@ -160,11 +161,18 @@ function NotesSidebar( { postId } ) {
...
+	async function openTheSidebar( selectedClientId ) {
 		const prevArea = await getActiveComplementaryArea( 'core' );
 		const activeNotesArea = SIDEBARS.find( ( name ) => name === prevArea );
+		const targetClientId =
+			selectedClientId && selectedClientId !== clientId
+				? selectedClientId
+				: clientId;
+		const targetNote = resultComments.find(
+			( note ) => note.blockClientId === targetClientId
+		);
```
Comment (Mamaduka) [inline packages/editor/src/components/collab-sidebar/index.js:173]: This needs to be derived here; we'll get stale value based on block selection.

File: packages/editor/src/components/collab-sidebar/index.js [hunk 2]
```diff
@@ -179,14 +187,11 @@ function NotesSidebar( { postId } ) {
...
-			commentSidebarRef.current,
-			// Focus the textarea when creating a new note.
-			! currentThread ? 'textarea' : undefined
-		);
-		toggleBlockSpotlight( clientId, true );
+		// A special case for the List View, where block selection isn't required to trigger an action.
+		// The action won't do anything if the block is already selected.
+		selectBlock( targetClientId, null );
+		toggleBlockSpotlight( targetClientId, true );
+		selectNote( targetNote ? targetNote.id : 'new', { focus: true } );
```
Comment (Mamaduka) [inline packages/editor/src/components/collab-sidebar/index.js:194]: Letting note selection handle focus fixes a minor race condition.

**Review by t-hamano — APPROVED** [review]
LGTM!

I think whenever a note is selected, the associated block should be selected, otherwise things would get complicated.

**Comment by Mamaduka** [comment]
Thanks for the review, @t-hamano!

I'm going to merge this. I think this is the most straightforward solution and aligns with the general Notes behavior: selecting a note (or a new note form) selects the associated block.

**Comment by talldan** [comment]
Thanks for fixing!
