### PR TITLE
Fix unable to publish edited legacy widgets in the customizer

### LINKED ISSUE #31177: Customizer widget editor does not publish changes
## Description
When having a legacy widget added in the standalone editor saving works. However, when moving to the Customizer and editing the legacy widget, publishing changes fails with the error `Unable to save due to 1 invalid setting.`

## Step-by-step reproduction instructions
0. Have Gutenberg `trunk` and TT1 theme active
1. Install and activate the Site Origin widgets bundle.
2. Go to Appearance > Widgets
3. Add a heading block.
4. Add a legacy widget, pick Site Origin Button Widget
5. Edit the legacy widget - set button label - and save the changes
6. Go to Appearance > Customize > Footer
7. Edit the legacy widget - change the button label
8. Publish
9. Notice the error on top of the sidebar `Unable to save due to 1 invalid setting.`

## Expected behaviour
Changes are published.

## Actual behaviour
Changes are not published.

## Screenshots or screen recording (optional)
invalid-setting

### PR DESCRIPTION
**Pull request by kevin940726**
## Description

Fix #31177.

Add missing `is_widget_customizer_js_value` value so that it can be saved and published. Apparently it's [required](https://github.com/WordPress/WordPress/blob/270f2011f8ec7265c3f4ddce39c77ef5b496ed1c/wp-includes/class-wp-customize-widgets.php#L1324).

Currently editing a legacy widget will trigger the whole preview iframe to reload. Not sure why yet.

## How has this been tested?

Follow the reproducing steps in #31177.

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by noisysocks** [comment]
Why does `$value` not already contain this though? It should be set in `sanitize_js_callback`, sent to the client, and then sent back as-is to the server.

**Comment by noisysocks** [comment]
Here's where it's set. Are we accidentally removing it in the frontend somewhere?

https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/class-wp-customize-widgets.php#L1362

**Comment by noisysocks** [comment]
Yes, it looks like `widgetToBlock` removes `instance.is_widget_customizer_js_value`. We should maybe make it and `blocktoWidget` use spread operators (`...`) to keep `instance` mostly intact.

https://github.com/WordPress/gutenberg/blob/trunk/packages/customize-widgets/src/components/sidebar-block-editor/use-sidebar-block-editor.js#L58

File: lib/class-wp-rest-widget-types-controller.php [hunk 1]
```diff
@@ -472,8 +472,10 @@ public function encode_form_data( $request ) {
 				)
 			),
 			'instance' => array(
-				'encoded' => base64_encode( $serialized_instance ),
-				'hash'    => wp_hash( $serialized_instance ),
+				'encoded'                       => base64_encode( $serialized_instance ),
+				'hash'                          => wp_hash( $serialized_instance ),
+				'title'                         => $request['instance']['title'],
+				'is_widget_customizer_js_value' => $request['instance']['is_widget_customizer_js_value'],
```
Comment (noisysocks) [inline lib/class-wp-rest-widget-types-controller.php]: Hm, I don't think these REST API endpoints should know anything about Customizer stuff (including `is_widget_customizer_js_value`). Is it to fix the issue if you add a new Legacy Widget?

**Review by noisysocks — APPROVED** [review]
LGTM 👍

File: packages/customize-widgets/src/components/sidebar-block-editor/use-sidebar-block-editor.js [hunk 2]
```diff
@@ -25,14 +25,17 @@ function blockToWidget( block, existingWidget = null ) {
...
+
 			// Widget that extends WP_Widget.
 			widget = {
 				idBase: block.attributes.idBase,
 				instance: {
-					encoded_serialized_instance:
-						block.attributes.instance.encoded,
-					instance_hash_key: block.attributes.instance.hash,
-					raw_instance: block.attributes.instance.raw,
+					...existingWidget.instance,
```
Comment (talldan) [inline packages/customize-widgets/src/components/sidebar-block-editor/use-sidebar-block-editor.js:34]: This seems to be throwing an error for new widgets.

I tried adding a SiteOrigin Button, and this line throws because `existingWidget` is `null`.

Comment (kevin940726) [reply packages/customize-widgets/src/components/sidebar-block-editor/use-sidebar-block-editor.js:34]: Oh shoot, forgot about that.

Comment (talldan) [reply packages/customize-widgets/src/components/sidebar-block-editor/use-sidebar-block-editor.js:34]: Lets make a note to add some tests for adding/updating/removing legacy widgets 👍

**Comment by talldan** [comment]
I think this one might have regressed. At least I can no longer save SiteOrigin legacy widgets in `trunk`.

**Comment by kevin940726** [comment]
> I think this one might have regressed. At least I can no longer save SiteOrigin legacy widgets in `trunk`.

I can't reproduce it though 🤔.
