### PR TITLE
Style Book: Fix missing styles for classic themes in stylebook route

### LINKED ISSUE #76826: StyleBook: Styles are not applied to classic themes
### Description

Originally reported at  https://wordpress.org/support/topic/wordpress-7-0-rc1-classic-theme-stylebook-broken/

props to @cabrailsford @fierevere

My investigation revealed that this issue was caused by https://github.com/WordPress/gutenberg/pull/72681.

### WP 6.9

Image

### WP 7.0 or Gutenberg

Image

### Step-by-step reproduction instructions

- Activate Twenty Twenty-One
- Access Appearance > Design > Styles

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [x] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #76826

## What?

Fix the Style Book not applying any styles when opened via the stylebook route with a classic theme

## Why?

When `StyleBookPreview` was moved from `edit-site` to `editor` package in #72681, [the settings source changed from `siteEditorStore.getSettings()` to `editorStore.getEditorSettings()`](https://github.com/WordPress/gutenberg/pull/72681/changes#diff-183511823cbdb27735b9754cbc1f56d137e587bb7e741b7041792bb0cd7814a9R386-R389). For the classic theme stylebook route, no post is being edited, so `EditorProvider` is not rendered and `editorStore.editorSettings` is never initialized with the theme's styles — resulting in a completely unstyled Style Book.

## How?

- Add an optional `settings` prop to `StyleBookPreview` that takes precedence over `editorStore.getEditorSettings()` when provided.
- In the stylebook route, pass `siteData.editorSettings` (from `editSiteStore.getSettings()`, which contains the theme styles) to `StyleBookPreview`.

## Testing Instructions

1. Activate a classic theme (e.g., Twenty Twenty-One)
2. Navigate to Appearance > Design > Styles.
3. Verify that the Style Book displays with styles properly applied.

### Before

image

### After

image

## Use of AI Tools

Claude Code was used to investigate the regression and implement the fix.

### CODE REVIEW

File: packages/edit-site/src/components/site-editor-routes/stylebook.js [hunk 1]
```diff
@@ -33,12 +33,18 @@ export const stylebookRoute = {
 		},
 		preview( { siteData } ) {
 			return isClassicThemeWithStyleBookSupport( siteData ) ? (
-				<StyleBookPreview isStatic />
+				<StyleBookPreview
+					isStatic
+					settings={ siteData.editorSettings }
```
Comment (ntsekouras) [inline packages/edit-site/src/components/site-editor-routes/stylebook.js:38]: I'm wondering if it would be better to update editor settings (`dispatch( editorStore ).updateEditorSettings( settings );`) below the edit site [settings](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/index.js#L87) update. 🤔

Comment (t-hamano) [reply packages/edit-site/src/components/site-editor-routes/stylebook.js:38]: That approach might also be possible, but it could have a significant impact and be risky to implement during the RC phase 🤔

File: packages/editor/src/components/style-book/index.js [hunk 2]
```diff
@@ -375,17 +375,19 @@ function StyleBook(
...
 	userConfig = {},
 	isStatic = false,
 	path,
 	onPathChange,
+	settings: settingsProp,
 } ) => {
 	const editorSettings = useSelect(
-		( select ) => select( editorStore ).getEditorSettings(),
-		[]
+		( select ) => settingsProp ?? select( editorStore ).getEditorSettings(),
```
Comment (ntsekouras) [inline packages/editor/src/components/style-book/index.js:389]: Do we gain anything by doing the check inside the `useSelect` and not outside? 🤔

**Review by ntsekouras — APPROVED** [review]
I think this approach is fine too and we already have `siteData` available to pass. Thanks!

File: packages/editor/src/components/style-book/index.js (hunk 2 above)
Comment (t-hamano) [reply packages/editor/src/components/style-book/index.js:389]: This is to avoid unnecessary subscriptions to the `editorStore` when `settingsProp` exists.
