### PR TITLE
Fix: Editing "Page" is broken for low capability users.

### LINKED ISSUE #68053: Editing "Page" is broken for low capability users
Nothing is rendered in the editor canvas when editing pages using a non-administrator user (Editor). The bug doesn't affect WP 6.7. I think this is a regression since #62304.

## Testing Instructions

1. Create a test user with an Editor role.
2. Switch to this user. You can use the [User Switching](https://wordpress.org/plugins/user-switching/) plugin.
3. Open a page.
4. Confirm that the editor canvas is blank.

## Screenshot
Image

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Fixes: https://github.com/WordPress/gutenberg/issues/68053

The issue arises because, despite checking that the user does not have permission to read templates and passing an undefined template, we were still passing the template-lock mode. Without a valid template, this mode does not function correctly. So to fix the problem when there is no template we use the post only mode.

This change addresses the issue and is necessary; however, the pull request is still in progress. There is a minor bug where the page start pattern modal briefly closes and reopens during loading. I am currently looking for a suitable solution that is not a hacky fix, for the close and reopen.

## Testing Instructions
With the 2024 theme and an editor user verify you can create and edit pages and they load in the normal post view.
Verify that the template view is loaded for admins.

### CODE REVIEW

**Comment by vipul0425** [comment]
Hey @jorgefilipecosta,
The undefined check for the template property seems reasonable. However, I’m curious why the template is not accessible for non-admin roles anymore. I tested this with `v19.6.1`, and it was available, as shown below:

image

But in latest versions, the value is now undefined. Have you encountered any PR or change implemented that might have affected template access for non-admin roles? I have not seen it in changelog.

**Comment by Mamaduka** [comment]
@jorgefilipecosta, users who can edit posts/pages can also read the templates. I think there might be another issue hiding here. When testing with the Editor role, I can also see a failed request for the `/settings` endpoint.

**Comment by jorgefilipecosta** [comment]
> @jorgefilipecosta, users who can edit posts/pages can also read the templates. I think there might be another issue hiding here. When testing with the Editor role, I can also see a failed request for the `/settings` endpoint.

Good point, I will check the settings part, but this code is still needed access to templates may still be removed for some roles, while they could still access pages.

File: packages/editor/src/components/provider/index.js [hunk 1]
```diff
@@ -193,17 +193,19 @@ export const ExperimentalEditorProvider = withRegistryProvider(
...
+							: 'post-only',
 					selection: getEditorSelection(),
 					postTypeEntities:
 						post.type === 'wp_template'
 							? getEntitiesConfig( 'postType' )
 							: null,
 				};
 			},
-			[ post.type ]
+			[ template, post.type ]
```
Comment (Mamaduka) [inline packages/editor/src/components/provider/index.js]: Can we pass `hasTemplate` or a similar boolean value? There is no need to re-run `mapSelect` after every template change.

It's also odd that this line resolves true when `template` isn't available. Let's check if the template is passed as an empty object when missing.

https://github.com/WordPress/gutenberg/blob/79200bfea601b51b7cfc5414a62e56aca63509be/packages/editor/src/components/provider/index.js#L209

**Comment by jorgefilipecosta** [comment]
> @jorgefilipecosta, users who can edit posts/pages can also read the templates. I think there might be another issue hiding here. When testing with the Editor role, I can also see a failed request for the `/settings` endpoint.

Yes, editors can normally read templates. The issue is that they cannot find the template associated with a page, such as a homepage and special pages, because these are located in the root site entity (they can not know if a page is homepage so they can not know the template used in it). I added a check for canUser read root site. The other 403 errors are unrelated, and I'm fixing them https://github.com/WordPress/gutenberg/pull/68146.

File: packages/editor/src/components/provider/index.js (hunk 1 above)
Comment (jorgefilipecosta) [reply packages/editor/src/components/provider/index.js]: Feedback applied 👍

**Comment by Mamaduka** [comment]
Thanks, @jorgefilipecosta! I'll try to do another review tomorrow.

I think we need to improve `getTemplateId` and other related private selectors. Otherwise, we'll be treating the symptoms instead of the root cause. Which I think are these selectors.

The `getTemplateId` bails early when `getHomePage` doesn't return values but only returns values for Administrator users.

https://github.com/WordPress/gutenberg/blob/c01cb99445c2261d2af1238b59104334fae91714/packages/core-data/src/private-selectors.ts#L178-L182

File: packages/editor/src/components/provider/index.js [hunk 2]
```diff
@@ -194,8 +195,7 @@ export const ExperimentalEditorProvider = withRegistryProvider(
 					editorSettings: getEditorSettings(),
 					isReady: __unstableIsEditorReady(),
 					mode: getRenderingMode(),
-					defaultMode:
-						postTypeObject?.default_rendering_mode ?? 'post-only',
+					defaultMode: postTypeObject?.default_rendering_mode,
```
Comment (Mamaduka) [inline packages/editor/src/components/provider/index.js]: We need a fallback here in case the server provides a false value. Consumers can unset `default_rendering_mode` using PHP filters.

File: packages/editor/src/components/provider/index.js [hunk 3]
```diff
@@ -327,14 +327,19 @@ export const ExperimentalEditorProvider = withRegistryProvider(
...
 
 		useHideBlocksFromInserter( post.type, mode );
 
 		// Register the editor commands.
 		useCommands();
 
+		console.log( {
+			notRender: ! isReady || ! mode || ! hasLoadedPostObject,
+			settings: ! settings.isPreviewMode,
+		} );
```
Comment (Mamaduka) [inline packages/editor/src/components/provider/index.js]: Leftovers 🥪

File: packages/editor/src/components/provider/index.js (hunk 2 above)
Comment (jorgefilipecosta) [reply packages/editor/src/components/provider/index.js]: Yes it was part of a debug change I included the missing commit

**Comment by jorgefilipecosta** [comment]
> I think we need to improve getTemplateId and other related private selectors. Otherwise, we'll be treating the symptoms instead of the root cause. Which I think are these selectors.

> The getTemplateId bails early when getHomePage doesn't return values but only returns values for Administrator users.

I believe that currently, only administrators can determine whether a page is a homepage or a blog page. As a result, it is expected that the selector should only return a value for administrators. For other users, returning a value could lead to a wrong value; for example, if the page were the homepage, the value would differ from what the selector would return.

I wonder why "The /lookup endpoint cannot currently handle a lookup when a page is set as the front page". It means the endpoint returns a wrong value for the homepage. Ideally, we fix the endpoint and simplify the selector (it could simply return the endpoint value). But I guess if the endpoint is not already doing this and the logic is on the frontend it may mean there is a reason and it may have wider implications. I will try to look into this. I guess this may be a short-term fix if changing the endpoint becomes a bigger effort or infeasible.

Regarding the issue faced of the patterns modal appearing closing and appearing, I think the ideal non-hacky fix, is to preload the template it like we do for the post. It would also noticeably improve the experience and loading performance of the page editor. I will also look into this.

File: packages/edit-post/src/components/layout/index.js [hunk 4]
```diff
@@ -400,6 +400,10 @@ function Layout( {
 				kind: 'postType',
 				name: 'wp_template',
 			} );
+			const canDiscoverTemplate = canUser( 'read', {
+				kind: 'root',
+				name: 'site',
+			} );
```
Comment (Mamaduka) [inline packages/edit-post/src/components/layout/index.js]: Maybe we should move this check into the `getHomePage` selector so we don't have to remember this implementation detail.

**Comment by Mamaduka** [comment]
I don't know; it seems too defensive. Non-Administrators can edit pages and view their templates. I would expect `getTemlateId` to return value, especially when a currently edited page has nothing to do with "homepage displays" settings.

It would be nice to resolve https://core.trac.wordpress.org/ticket/48885 and allow more granular controls over settings read/update permissions.

File: packages/edit-post/src/components/layout/index.js (hunk 4 above)
Comment (jorgefilipecosta) [reply packages/edit-post/src/components/layout/index.js]: Good point I added the check inside the selector.

**Comment by jorgefilipecosta** [comment]
Hi @Mamaduka, 

I agree that it would be ideal for editors to have access the pages templates. This could be achieved either by making the settings on https://core.trac.wordpress.org/ticket/48885 available as read-only or by modifying the lookup endpoint to consider special pages. However, for now, I believe our current solution is adequate.

I think we still need all of this code. In cases where there is no template—potentially due to custom permissions on the site from a plugin filter—we should default to post-only. And we also should check for user permissions before making the request. Thus, even with the upcoming long-term API fixes, this code remains valuable and addresses the issue in the short term.

**Comment by youknowriad** [comment]
I don't think we can use the "lookup" here because there might be "local edits" in the frontend that alter which template to return. This is the reason the algorithm of the "lookup" is recreated in the client kind of.

Now, yeah I agree with @jorgefilipecosta that if we want to allow these users to see the templates, we need to ensure they can retrieve which page is the home page and posts page... So alter the settings endpoint to access readonly values.

That seems like a big change, so I think being defensive is probably the quickest path for now (fallback to post-only)

File: packages/core-data/src/private-selectors.ts [hunk 5]
```diff
@@ -134,6 +139,13 @@ interface SiteData {
 export const getHomePage = createRegistrySelector( ( select ) =>
 	createSelector(
 		() => {
+			const canReadSiteData = select( STORE_NAME ).canUser( 'read', {
```
Comment (youknowriad) [inline packages/core-data/src/private-selectors.ts:142]: Should we do something similar for `getPostsPageId` and `getTemplateId`

**Comment by Mamaduka** [comment]
It seems we have different ideas on how `getTemplateId` should work 😄

However, I understand the current REST API limitations, and there's no need to delay @jorgefilipecosta's work further. Jorge, if you don't mind, I'll do another round of tests tomorrow morning and approve the fix.

**Comment by youknowriad** [comment]
> It seems we have different ideas on how getTemplateId should work 😄

Curious about your thoughts here?

**Comment by Mamaduka** [comment]
Ideally, I would expect it to continue with the regular template lookup, considering that custom page templates are more widely used than "home page" and "page for posts".

File: packages/core-data/src/private-selectors.ts (hunk 5 above)
Comment (jorgefilipecosta) [reply packages/core-data/src/private-selectors.ts:142]: Yes for getPostsPageId we should and I included the check. For getTemplateId I think it is not needed as that selector never reads settings directly.

**Comment by jorgefilipecosta** [comment]
> Ideally, I would expect it to continue with the regular template lookup, considering that custom page templates are more widely used than "home page" and "page for posts".

I'm not sure, even though the homepage and blog pages are only two pages they are impactful showing the wrong template on them may not be ideal.
I guess that is a discussion for later, I think we can go on and merge this PR it just adds checks which I believe are needed even if in the future we improve things on the lookup and the editor can use the template mode.

**Review by Mamaduka — APPROVED** [review]

**Comment by jorgefilipecosta** [comment]
@Mamaduka thank you a lot for all the reviews and insights 😊

File: packages/core-data/src/private-selectors.ts (hunk 5 above)
Comment (fabiankaegy) [reply packages/core-data/src/private-selectors.ts:142]: This check here only returns `undefined` for me for a user with the `editor` role. Something must not be working correctly here
