### PR TITLE
Retain the same specificity for non iframed selectors

### LINKED ISSUE #63925: Differing CSS specificity between Non-Iframed Editor and Front end
### Description

With non-iframed block editor, specificity of top-level element selectors are different relative to other selectors. I believe this is due to the `.editor-style-wrapper` prefix.

### Step-by-step reproduction instructions

1. Create theme using code snippets below.
2. Activate the created theme.
3. Edit a page or post.
4. Add a Heading block, with default attributes and any text content.
5. Save.
6. Observe the font size.
7. Top right 3-dots menu → Preferences → Enable "Custom Fields".
8. Hit *Show and Reload Page* button (to enable the non-iframe editor).
9. Observe the heading block size is different to step 5.
10. On the front end, observe the heading block size is the same as 5.

##### `theme.json`
```json
{
  "$schema": "https://schemas.wp.org/wp/6.6/theme.json",
  "version": 3,
  "styles": {
    "blocks": {
      "core/heading": {
        "typography": {
          "fontSize": "var(--wp--preset--font-size--large)"
        }
      }
    },
    "elements": {
      "heading": {
        "typography": {
          "fontSize": "inherit"
        }
      }
    }
  }
}
```

##### `style.css`
```css
/*
Theme Name: Test
*/
```

##### `templates/index.html`

```html
<!-- wp:post-content /-->
```

#### Observed behavior

<table>
<thead>
<tr>
<th>&nbsp;</th>
<th>Front end</th>
<th>Iframe editor</th>
<th>Non-iframe editor</th>
</tr>
</thead>
<tbody>
<tr>
<th scope="row">Screenshot</th>
<td>

image

</td>
<td>

image

</td>
<td>

image

</td>
</tr>
<tr>
<th scope="row">CSS</th>

<td>

```css
:root :where(.wp-block-heading) {
  font-size: var(--wp--preset--font-size--large);
}
h1, h2, h3, h4, h5, h6 {
  font-size: inherit;
}
```

</td>
<td>

```css
:root :where(.wp-block-heading) {
  font-size: var(--wp--preset--font-size--large);
}
h1, h2, h3, h4, h5, h6 {
  font-size: inherit;
}
```

</td>
<td>

```css
.editor-styles-wrapper h1,
.editor-styles-wrapper h2,
.editor-styles-wrapper h3
.editor-styles-wrapper h4,
.editor-styles-wrapper h5,
.editor-styles-wrapper h6 {
  font-size: inherit;
}
.editor-styles-wrapper :where(.wp-block-heading) {
  font-size: var(--wp--preset--font-size--large);
}
```

</td>
</tr>
<th scope="row">Analysis</th>
<td>

✅ `core/heading` block styles override top-level element `heading` styles.

</td>
<td>

✅ `core/heading` block styles override top-level element `heading` styles.

</td>
<td>

❌ Top-level element `heading` styles override `core/heading` block styles. Element `heading` styles have specificity (0, 1, 1) whereas `core/heading` block styles have (0, 1, 0).

</td>
</tbody>
</table>

### Environment info

- WordPress 6.6.1
- Custom theme (see code snippets)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by talldan**
## What?
Alternative to #56649
Fixes #63925

Tries to maintain specificity across styles between the iframed and non-iframed canvas. This PR is slightly different to https://github.com/WordPress/gutenberg/pull/56649 in that it also seeks to maintain specificity for root selectors.

For a quick recap, in a a non-iframed canvas `.editor-styles-wrapper` is prefixed onto the majority of selectors to scope the styles. This results in a bump in specificity. For root selectors (any that begin with `body`, `html` or `:root`) prefixing the classname would create an invalid selector, so the root part of the classname is replaced instead. This results in some of these selectors maintaining specificity, while others change ever so slightly.

This inconsistency creates a situation where the specificity of some styles is bumped, others aren't, and so in a non-iframed editor styles often don't apply in the same way and can look completely different to the front end or iframed editor.

## How?
For most selectors, the prefix is changed from `.editor-styles-wrapper` to `:where(.editor-styles-wrapper)`.

For root selectors, a selector like `body .some-selector` changes to `body :where(.editor-styles-wrapper) .some-selector`. 

Both are maintaining the same specificity.

The tool of choice for prefixing is `postcss` and in particular a `postcss` plugin called `postcss-prefixwrap` is used in trunk. In this PR I've replaced it with the `postcss-prefix-selector` plugin. This one has a callback that allows us to change how scoping works on a per selector basis, which is how the root selector behavior has been changed.

One drawback of the new library is that it's `exclude` option doesn't work the same way as the `ignoredSelectors` option of the old library. Fortunately the callback means it's possible to replicate that behavior.

## Testing Instructions
This needs a lot of general smoke testing. Below are instructions to check whether #63925 was fixed:

[Test using WordPress playground](https://playground.wordpress.net/#%7B%22landingPage%22:%22/wp-admin/%22,%22steps%22:%5B%7B%22step%22:%22login%22,%22username%22:%22admin%22,%22password%22:%22password%22%7D,%7B%22step%22:%22mkdir%22,%22path%22:%22/wordpress/pr%22%7D,%7B%22step%22:%22writeFile%22,%22path%22:%22/wordpress/pr/pr.zip%22,%22data%22:%7B%22resource%22:%22url%22,%22url%22:%22/plugin-proxy.php?org=WordPress&repo=gutenberg&workflow=Build%2520Gutenberg%2520Plugin%2520Zip&artifact=gutenberg-plugin&pr=64534%22,%22caption%22:%22Downloading%20Gutenberg%20PR%2064534%22%7D,%22progress%22:%7B%22weight%22:2,%22caption%22:%22Applying%20Gutenberg%20PR%2064534%22%7D%7D,%7B%22step%22:%22unzip%22,%22zipPath%22:%22/wordpress/pr/pr.zip%22,%22extractToPath%22:%22/wordpress/pr%22%7D,%7B%22step%22:%22installPlugin%22,%22pluginZipFile%22:%7B%22resource%22:%22vfs%22,%22path%22:%22/wordpress/pr/gutenberg.zip%22%7D%7D%5D%7D)

1. Go to Tools > Theme File Editor > theme.json
2. Add the following snippet to the theme.json under `styles.blocks`:
```json
"core/heading": {
    "typography": {
        "fontSize": "var(--wp--preset--font-size--small)"
    }
},
```
3. Create a post and insert a heading block - observe it should have a small font size
4. Save the post and in the editor preferences, enable Custom fields to un-iframe the editor
5. When the editor reloads, observe that the heading block still has a small font size

Here are some diffs that show the styles before and after transformation:
- [Twenty Seventeen Diff](https://gist.github.com/talldan/81ec7b125adc394bf5d86db93ca02447)
- [Twenty Twenty One Diff](https://gist.github.com/talldan/26b4739cceb1cedc9f2091357c3e37c1)
- [Twenty Twenty Four Diff](https://gist.github.com/talldan/806258c68ed0763cb22a3ea5cd155e25)

### CODE REVIEW

File: packages/block-editor/src/utils/test/transform-styles.js [hunk 1]
```diff
@@ -212,7 +212,7 @@ describe( 'transformStyles', () => {
 		} );
 
 		it( 'should not double wrap selectors', () => {
-			const input = ` .my-namespace h1, .red { color: red; }`;
+			const input = ` .my-namespace h1, .my-namespace .red { color: red; }`;
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/utils/test/transform-styles.js]: Would it be better to leave this as it is, covering different specificities in the selector list, and just update the output? 

To me, the original input covered the scenario when the plugin detects that it does need to prefix something and then ensures it doesn't go overboard resulting in a double prefix.

File: packages/block-editor/src/utils/transform-styles/index.js [hunk 2]
```diff
@@ -2,38 +2,76 @@
...
+								return replaceDoublePrefix(
+									updatedRootSelector,
+									prefix
+								);
+							}
+
+							return replaceDoublePrefix(
+								prefixedSelector,
+								prefix
+							);
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/utils/transform-styles/index.js]: Would it be worth a comment here explaining why this is needed? 

My understanding of the old plugin was that it ignored all selectors already starting with the prefix. This one seems to only do a simple comparison between the selectors in `exclude` and so requires this double handling. Is that correct?

File: packages/block-editor/src/utils/test/transform-styles.js [hunk 3]
```diff
@@ -111,7 +111,7 @@ describe( 'transformStyles', () => {
 			expect( output ).toMatchSnapshot();
 		} );
 
-		it( 'should replace root tags', () => {
+		it( 'should replace body selectors', () => {
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/utils/test/transform-styles.js]: We have tests for `body` and `:root`, should we have cover for all the [`ROOT_SELECTORS`](https://github.com/WordPress/gutenberg/pull/64534/files#diff-1a1112576a3a01919381e2096bad6958636e1dc429328754cb607ce37b22d565R10-R16)?

**Review by aaronrobertshaw — COMMENTED** [review]
Nice work wrangling this one @talldan 👍 

It's looking like a promising direction to me! 

I still need to do some broader testing, mainly around layout and global styles, but it fixes the issue in https://github.com/WordPress/gutenberg/issues/63925/.

Screenshot 2024-08-16 at 4 21 49 PM

✅ Heading block global styles remain higher specificity than prefixed element styles
✅ Prefixed selectors match those promised in PR description
✅ Couldn't find any remaining places where `.editor-styles-wrapper` was programmatically added as scoping selector
✅ Element styles on block instances continue to work

Screenshot 2024-08-16 at 4 32 25 PM

On a side note, the use of snapshots for simple CSS assertions is a bit of a pain when trying to see what the expected outcome is. I like the switch away from snapshots for the new tests. If we proceed with this PR, is it then the best opportunity to get rid of the snapshots entirely?

They also caught me out checking the diff as it looked like a test had been removed.

I'll give this a further test on Monday. If there are any specific areas you'd like focus on, add them to the test instructions and I'll cast an eye over them.

**Comment by aaronrobertshaw** [comment]
If we proceed with the new scoping selector for the non-iframed editor, we might also need to revisit quite a few `editor.scss` files in the block library as they often use `.editor-styles-wrapper` in their selectors.

**Comment by talldan** [comment]
> On a side note, the use of snapshots for simple CSS assertions is a bit of a pain when trying to see what the expected outcome is. I like the switch away from snapshots for the new tests. If we proceed with this PR, is it then the best opportunity to get rid of the snapshots entirely?

Agree, I also didn't like the use of snapshots.

> If we proceed with the new scoping selector for the non-iframed editor, we might also need to revisit quite a few editor.scss files in the block library as they often use .editor-styles-wrapper in their selectors.

This is also a concern for any themes that might have (e.g. `.editor-styles-wrapper .my-class` already in a selector. Prefixing it would produce a non-matching selector now `:where(.editor-styles-wrapper) .editor-styles-wrapper .my-class`.

I'm thinking the best option would be to ignore those selectors and not try prefixing them. Alternatively, we could try replacing `.editor-styles-wrapper` with `:where(.editor-styles-wrapper)`, but I fear that might lead to frustration from theme developers if they want to purposely keep specificity.

I can go through and manually update the block library selectors though.

**Comment by aaronrobertshaw** [comment]
> I'm thinking the best option would be to ignore those selectors and not try prefixing them. Alternatively, we could try replacing .editor-styles-wrapper with :where(.editor-styles-wrapper), but I fear that might lead to frustration from theme developers if they want to purposely keep specificity.

Honestly, I'm not sure either.

Part of the fix/goal here is to ensure consistent specificity. Styles with selectors prefixed with `.editor-styles-wrapper` would have the intent to override bleed-in from other sources or styles. If this PR ultimately makes the selectors match those from global styles, wrapping `.editor-styles-wrapper` in `:where()` might not be such an issue. It could even prevent requiring some updates from block/plugin authors.

Perhaps we could try out that approach here and see how it plays with the block library editor styles before we go changing them?

**Comment by talldan** [comment]
I've pushed a commit that ignores selectors that already contain `.editor-styles-wrapper` so that they stay valid. To test, I did this:
1. Enabled Twenty Seventeen (it helps to use an older theme, since block themes tend to enqueue specific editor styles that aren't passed through `transformStyles`)
2. Add CSS like this to the editor-styles.scss file:
```css
.editor-styles-wrapper h2 {
	color: orange !important;
}
```
3. Load the gutenberg demo post
4. Check that with the latest commit ([25bfa9d](https://github.com/WordPress/gutenberg/pull/64534/commits/25bfa9dbbbc9b17c6f4ec10a22f898fa8ab48788)), the orange style is applied.
5. If you check out the commit before that (https://github.com/WordPress/gutenberg/pull/64534/commits/93455f86ac43aec17707c5f12a9cc215087ba2e7), the orange style isn't applied (the selector ends up being `:where(.editor-styles-wrapper) .editor-styles-wrapper h2`, which won't work).

I think this is a good thing to do, even if using `.editor-styles-wrapper` in CSS that will be prefixeed is probably not something that themes do a lot.

File: packages/block-editor/src/utils/transform-styles/index.js (hunk 2 above)
Comment (talldan) [reply packages/block-editor/src/utils/transform-styles/index.js]: The 'should not double wrap selectors' was failing when I switched to the new library. You're right that the `ignoredSelectors` seems to be where the old library works differently to the new one. We've been using the string `'.editor-styles-wrapper'` as an ignored selector. With the old library it uses something akin to `selector.includes( ignoredSelector )` to check if it should be ignored, whereas the new library is more like `selector === ignoredSelector`. Both also support regular expressions, but we weren't using that.

I think this will be an issue as `transformStyles` is a public API, so `ignoredSelectors` should work the same as before. 🤔 

Probably the best bet would be to replicate how the old library works in the callback rather than the way I've done it using `replaceDoublePrefix` 😄

Comment (talldan) [reply packages/block-editor/src/utils/transform-styles/index.js]: Done in [6b43b57](https://github.com/WordPress/gutenberg/pull/64534/commits/6b43b57d5c8c7cba546ba276e95ed5485c0dbcd3)

File: packages/block-editor/src/utils/test/transform-styles.js (hunk 1 above)
Comment (talldan) [reply packages/block-editor/src/utils/test/transform-styles.js]: I liked being able to make the test `expect( output ).toEqual( [ input ] )`, but I've updated it in [6b43b57](https://github.com/WordPress/gutenberg/pull/64534/commits/6b43b57d5c8c7cba546ba276e95ed5485c0dbcd3) to be as it was before (though without snapshots)

File: packages/block-editor/src/utils/test/transform-styles.js (hunk 3 above)
Comment (talldan) [reply packages/block-editor/src/utils/test/transform-styles.js]: Done 👍

**Comment by talldan** [comment]
I think there are a couple of things remaining here:
- [ ] Check few block library styles to see if any of them need specificity adjustments after this change.
- [x] Do an audit of the styles generated before and after transformation to see if I can spot any issues. Check a few themes.
    - [Twenty Seventeen Diff](https://gist.github.com/talldan/81ec7b125adc394bf5d86db93ca02447)
    - [Twenty Twenty One Diff](https://gist.github.com/talldan/26b4739cceb1cedc9f2091357c3e37c1)
    - [Twenty Twenty Four Diff](https://gist.github.com/talldan/806258c68ed0763cb22a3ea5cd155e25)

File: packages/block-editor/src/utils/transform-styles/index.js (hunk 2 above)
Comment (aaronrobertshaw) [reply packages/block-editor/src/utils/transform-styles/index.js]: I haven't had a chance to look deeply at the code after the latest updates but did you account for the fact the old plugin allows regex in those ignored selectors?

Here's a snippet from the [plugin's readme](https://github.com/dbtedman/postcss-prefixwrap).
```
    // You may want to exclude some selectors from being prefixed, this is
    // enabled using the `ignoredSelectors` option.
    ignoredSelectors: [":root", "#my-id", /^\.some-(.+)$/],
```

As noted in my earlier comment, this new plugin appears to do a direct comparison of selectors. Take that with a grain of salt but something to double all the same.

Comment (talldan) [reply packages/block-editor/src/utils/transform-styles/index.js]: Yep, the pseudocode is `selector.match( ignoredSelector )`, and `match` which will work for both plain strings and regexes.

edit: pushed a commit to make sure there's test coverage for regex ignored selectors.

Comment (aaronrobertshaw) [reply packages/block-editor/src/utils/transform-styles/index.js]: Nice. Appreciate the extra test coverage there 👌

**Comment by talldan** [comment]
From looking through the transformed styles, I see a small number of invalid selectors being produced.

Iframed:
```css
html[lang="th"] body,
```

Non-iframed:
```css
html :where(.editor-styles-wrapper) [lang="th"] body,
```

It should be 
```css
html[lang="th"] body :where(.editor-styles-wrapper),
```

Root selector handling needs a bit more care. That said, it's also broken in trunk:
```css
 .editor-styles-wrapper[lang="th"] body,
 ```

**Comment by talldan** [comment]
Pushed a fix for that. Tomorrow I'll do another audit on the transformed selectors to see if there's anything else looking dodgy.

File: packages/block-editor/src/utils/transform-styles/index.js [hunk 4]
```diff
@@ -53,21 +53,37 @@ function transformStyle(
...
-								const updatedRootSelector =
-									`${ rootSelector } ${ prefix } ${ selectorWithoutRootPart }`.trim();
-
-								return updatedRootSelector;
+							if ( hasRootSelector ) {
+								// Split the selector into its parts.
+								// Take into account combinators, which don't need a space around them to form a valid selector.
+								const selectorParts = selector
+									.split( /(\s|>|\+|~)/g )
+									.filter( ( part ) => part.trim() !== '' );
```
Comment (talldan) [inline packages/block-editor/src/utils/transform-styles/index.js]: I don't like having to make assumptions about css selector syntax, as I imagine it's quite a deep topic.

There are a couple of small libraries for parsing selectors that could be used to make this more robust:
- https://github.com/mdevils/css-selector-parser
- https://parsel.verou.me/

That said, I think it'd make the code a lot more involved.

Comment (talldan) [reply packages/block-editor/src/utils/transform-styles/index.js]: I've added quite a few tests, let me know if you can think of any more, or anything I've missed!

Comment (talldan) [reply packages/block-editor/src/utils/transform-styles/index.js]: I decided to switch to a tokenizer ([parsel.verou.me](https://parsel.verou.me/)) as I found another case that wouldn't work with the previous approach (some themes had selectors like `html [data-type="core/html"] .test` which are very difficult to get right with regular string or regex matching).

Added a test case for this to show it solves that particular issue.

File: test/unit/jest.config.js [hunk 5]
```diff
@@ -40,7 +40,7 @@ module.exports = {
 		'^.+\\.[jt]sx?$': '<rootDir>/test/unit/scripts/babel-transformer.js',
 	},
 	transformIgnorePatterns: [
-		'/node_modules/(?!(docker-compose|yaml|preact|@preact)/)',
+		'/node_modules/(?!(docker-compose|yaml|preact|@preact|parsel-js)/)',
```
Comment (talldan) [inline test/unit/jest.config.js:43]: Parsel is an es module, so needs to be transformed.

File: packages/block-editor/src/utils/transform-styles/index.js (hunk 4 above)
Comment (aaronrobertshaw) [reply packages/block-editor/src/utils/transform-styles/index.js]: Given how much work `transformStyles` might have to do prefixing selectors, do we know much about the performance implications of using the tokenizer vs a simplistic (and limited/brittle) regex?

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for the persistence in wrangling all these edge cases @talldan 👍 

I've given this another test after the recent change in direction and it looks to be testing well in the editor. I couldn't replicate the issue in https://github.com/WordPress/gutenberg/issues/63925 on this branch.

The linked gists detailing all the updated selectors for a few themes was a nice touch 🥇 

I think my eyes were playing tricks on me by the time I got to the end of them but from what I could tell there didn't seem to be any surprises.

The latest tests are also looking pretty good. I hacked around with them a little bit to test some hunches e.g. multi attribute selectors `html[lang="en"][dir="rtl"]`. Most things I tried were covered although I did find one minor issue.

If the wrapper selector is set to `:where(.my-namespace)` and a selector has that wrapper selector already in it, it still gets prefixed. This is avoided for our `EditorStyles` component due to the regex used to ignore anything with `.editor-styles-wrapper` in it.

The wrapper selector is supposed to be added to the ignored selectors. Which doesn't appear to work correctly once it contains `:where()`. Do we need to escape the selector for use as a regex? 

Here's a quick diff tweaking one of the tests to see what I mean. The test fails even though the output should match the input if it isn't erroneously being prefixed.

```diff
diff --git a/packages/block-editor/src/utils/test/transform-styles.js b/packages/block-editor/src/utils/test/transform-styles.js
index 8e365e9e18..e1d2c21634 100644
--- a/packages/block-editor/src/utils/test/transform-styles.js
+++ b/packages/block-editor/src/utils/test/transform-styles.js
@@ -214,14 +214,15 @@ describe( 'transformStyles', () => {
 		} );
 
 		it( 'should not double prefix a root selector', () => {
-			const input = 'body .my-namespace h1  { color: goldenrod; }';
+			const input =
+				'body :where(.my-namespace) h1  { color: goldenrod; }';
 			const output = transformStyles(
 				[
 					{
 						css: input,
 					},
 				],
-				'.my-namespace'
+				':where(.my-namespace)'
 			);
 
 			expect( output ).toEqual( [ input ] );

```

File: packages/block-editor/src/utils/transform-styles/index.js [hunk 6]
```diff
@@ -1,39 +1,132 @@
...
 	}
-	const postcssFriendlyCSS = css
-		.replace( /:root :where\(body\)/g, 'body' )
-		.replace( /:where\(body\)/g, 'body' );
+
 	try {
+		const excludedSelectors = [
+			...ignoredSelectors,
+			...( transformOptions?.ignoredSelectors ?? [] ),
+			wrapperSelector,
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/utils/transform-styles/index.js:100]: Do we need to escape normal CSS selectors here e.g. `:where(...)` for use as a regex?

Comment (talldan) [reply packages/block-editor/src/utils/transform-styles/index.js:100]: The `match` method works for strings as well as regexes, so I think it should be ok.

File: packages/block-library/src/button/editor.scss [hunk 7]
```diff
@@ -32,8 +32,3 @@
 div[data-type="core/button"] {
 	display: table;
 }
-
-.editor-styles-wrapper .wp-block-button[style*="text-decoration"] .wp-block-button__link {
-	text-decoration: inherit;
-}
```
Comment (talldan) [inline packages/block-library/src/button/editor.scss:38]: Removed because there's a rule in the style.scss that does the same thing.

There's also a related conversation here - https://github.com/WordPress/gutenberg/pull/43934#discussion_r1408015884

File: packages/block-library/src/buttons/editor.scss [hunk 8]
```diff
@@ -52,12 +52,6 @@ $blocks-block__margin: 0.5em;
 			margin-bottom: 0;
 		}
 	}
-
-	.editor-styles-wrapper &.has-custom-font-size {
-		.wp-block-button__link {
-			font-size: inherit;
-		}
-	}
```
Comment (talldan) [inline packages/block-library/src/buttons/editor.scss:60]: Removed because there's a rule in the style.scss that does the same thing.

File: packages/block-library/src/cover/editor.scss [hunk 9]
```diff
@@ -1,9 +1,4 @@
 .wp-block-cover {
-	/* Extra specificity needed because the reset.css applied in the editor context is overriding this rule. */
-	.editor-styles-wrapper & {
-		box-sizing: border-box;
-	}
```
Comment (talldan) [inline packages/block-library/src/cover/editor.scss:5]: Removed because there's a rule in the style.scss that does the same thing.

It also doesn't seem to override anything in the reset.css, maybe that was refactored after this was introduced.

File: packages/block-library/src/site-title/editor.scss [hunk 10]
```diff
@@ -2,7 +2,3 @@
 	padding: 1em 0;
 	border: 1px dashed;
 }
-
-.editor-styles-wrapper :where(.wp-block-site-title a) {
-	color: inherit;
-}
```
Comment (talldan) [inline packages/block-library/src/site-title/editor.scss:8]: Removed because there's a rule in the style.scss that does the same thing (and has the same specificity, so exactly the same).

File: packages/block-library/src/comments-pagination/editor.scss [hunk 11]
```diff
@@ -5,7 +5,7 @@ $pagination-margin: 0.5em;
 	justify-content: center;
 }
 
-.editor-styles-wrapper {
+:where(.editor-styles-wrapper) {
```
Comment (talldan) [inline packages/block-library/src/comments-pagination/editor.scss:8]: I decided to lower the specificity here, though I can't see that these styles are doing anything. 🤔 

Same applies for query pagination.

edit: looking a bit more, I can see that the `margin: 0` wipes out the block gap on classic themes. I don't know if that was the intention. I wish there were some inline comments. The `max-width` also overrides a max-width set by some themes, but it also doesn't seem to have any visible effect.

The change here doesn't affect any of that.

File: packages/block-library/src/navigation/editor.scss [hunk 12]
```diff
@@ -3,7 +3,9 @@
  */
 
 // Undo default editor styles.
-// These need extra specificity.
+// These need extra specificity to do two things in classic themes
+// 1. Override the auto margin left from alignment styles.
+// 2. Override list style indentation.
 .editor-styles-wrapper .wp-block-navigation {
```
Comment (talldan) [inline packages/block-library/src/navigation/editor.scss:7]: If anything this needs to be a higher specificity, as the padding-left rule is not overriding the list styling applied by some older themes (e.g. Twenty Twenty). 😬

File: packages/block-editor/src/hooks/duotone.js [hunk 13]
```diff
@@ -251,10 +251,6 @@ function useDuotoneStyles( {
 	const selectors = duotoneSelector.split( ',' );
 
 	const selectorsScoped = selectors.map( ( selectorPart ) => {
-		// Extra .editor-styles-wrapper specificity is needed in the editor
-		// since we're not using inline styles to apply the filter. We need to
-		// override duotone applied by global styles and theme.json.
-
```
Comment (talldan) [inline packages/block-editor/src/hooks/duotone.js:257]: The selector no longer has `.editor-styles-wrapper` added, though it looks like the comment wasn't removed.

File: packages/block-editor/src/utils/transform-styles/index.js (hunk 6 above)
Comment (aaronrobertshaw) [reply packages/block-editor/src/utils/transform-styles/index.js:100]: Did you apply the diff in my review? 

That shows that if the `wrapperSelector` is `:where(.my-namespace)` and the selector to be prefixed contains `:where(.my-namespace)` it still prefixes when it shouldn't.

Screenshot 2024-08-26 at 6 51 16 PM

File: packages/block-library/src/comments-pagination/editor.scss (hunk 11 above)
Comment (aaronrobertshaw) [reply packages/block-library/src/comments-pagination/editor.scss:8]: > I don't know if that was the intention

Sounds like it was unintentional. The original PR for the block doesn't give any clues either.

File: packages/block-library/src/navigation/editor.scss (hunk 12 above)
Comment (aaronrobertshaw) [reply packages/block-library/src/navigation/editor.scss:7]: Is this supposed to be overriding classic theme styles? How do these margin styles interact with the current block gap support for the Navigation block?

File: packages/block-editor/src/utils/transform-styles/index.js (hunk 6 above)
Comment (talldan) [reply packages/block-editor/src/utils/transform-styles/index.js:100]: I'll take a look and make sure there's a unit test 👍

File: packages/block-library/src/navigation/editor.scss (hunk 12 above)
Comment (talldan) [reply packages/block-library/src/navigation/editor.scss:7]: The selectors target an inner element of the block, so block styles work ok. Block gap works ok from my testing, it's using `column-gap`.

[There's a separate bug in the nav block that the `ul` inner element has a `wp-block` classname](https://github.com/WordPress/gutenberg/pull/63801), so that's why the alignment styles need to be overridden.

I'll add some extra detail to the comment to make it clearer. 

edit: On further testing I'm seeing some stuff broken in the nav block in Twenty Twenty - a page list in the nav block looks completely different to a normal menu, but that's mostly coming from the theme.

File: packages/block-editor/src/utils/transform-styles/index.js (hunk 6 above)
Comment (talldan) [reply packages/block-editor/src/utils/transform-styles/index.js:100]: That should be fixed now in the latest commit, thanks for catching it 👍

Comment (aaronrobertshaw) [reply packages/block-editor/src/utils/transform-styles/index.js:100]: Works well now 🚀 

I like the simple check for whether the excluded selector is a RegExp instance. Means all kinds of funky CSS selectors are covered.

File: packages/block-editor/src/utils/transform-styles/index.js [hunk 14]
```diff
@@ -1,39 +1,138 @@
...
+/**
+ * Prefixes root selectors in a way that ensures consistent specificity.
+ * This requires special handling, since prefixing a classname before
+ * html, body, or :root will generally result in an invalid selector.
+ *
+ * Some libraries will simply replace the root selector with the prefix
+ * instead, but this results in inconsistent specificity.
+ *
+ * This function instead inserts the prefix after the root tags but before
+ * any other part of the selector.
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/utils/transform-styles/index.js]: Is it worth clarifying here that the specificity is made consistent by the prefix being wrapped in `:where()`?

File: packages/block-library/src/navigation/editor.scss (hunk 12 above)
Comment (aaronrobertshaw) [reply packages/block-library/src/navigation/editor.scss:7]: In most cases I tested it was ok to wrap the `.editor-styles-wrapper` class in `:where()`. Unfortunately there were still some like TwentyTwentyOne which had selectors like `.wp-block-navigation [data-block]`. 

Keeping this selector's specificity as is, makes sense to me. Thanks for the clarifying comments.

**Review by aaronrobertshaw — APPROVED** [review]
Thank you for all the hard work wrangling edges on this front 💪 

✅  After the latest round of tweaks, the tests are looking good and I couldn't find any plausible ways of breaking the prefixing.
✅  I've searched through the code for remaining uses of `.editor-styles-wrapper` and they all seem to check out. 
✅  The culling of outdated comments look good
✅  Each of the touched editor block styles make sense and I didn't spot any issues there

This is looking good to me @talldan and I'm happy to give it a tentative approval. I think it would be prudent though to get some extra eyes on it given the scope of the changes.

**Review by kevin940726 — APPROVED** [review]
Tested on playground and it worked as expected for me too! 💯

File: packages/block-editor/src/utils/transform-styles/index.js (hunk 14 above)
Comment (talldan) [reply packages/block-editor/src/utils/transform-styles/index.js]: Good idea, I've pushed a commit that adds some extra context.

**Comment by talldan** [comment]
Thanks for the testing and reviews! I'll go ahead and merge this, but further testing feedback or code review feedback is still welcome, I'll address anything in follow-up PRs.

@vcanales I've labelled this for backport to 6.6.2, though it might be worth having a conversation about the size and scope of this PR. I think it'd fix a lot of issues for users though, so hopefully it's ok.

**Comment by mrleemon** [comment]
Thanks for your work, @talldan! I hope your fix makes it into 6.6.2.

**Comment by hellofromtonya** [comment]
Will discuss in today's bug scrub (starting in about 10 minutes). I'm thinking this PR is not well suited for a minor release. Why?

* It's marked as an enhancement.
* It's an alternative to #56649, which is from last year.
* Due to its size and scope, it's a good candidate for first releasing in Gutenberg for broader testing, validation, and possibly further iteration.

So I'm thinking it's an enhancement that subsequently also fixes a regression bug that (may have) happened in 6.6.0 (or earlier). As an enhancement, it's better suited for 6.7.0.

**Comment by aaronjorbin** [comment]
Some additional info to consider: It is fixing an issue (#63925) that is labeled as a regression.  If it's a regression from 6.5 to 6.6, that seems to me like this should be considered.

That said, this is not a small PR and based on the other tickets connected, I'm not sure it is a regression from 6.5 or from much earlier (making it a long standing bug that is better fixed in a major version)

**Comment by hellofromtonya** [comment]
Summary of [discussion during today's Core bug scrub](https://wordpress.slack.com/archives/C02RQBWTW/p1724857471611359):

- It's not ready for 6.6.2.
- It needs to be released first in the plugin to gain confidence and, if needed, iteration.
- Then it could be reconsidered for a future 6.6.x minor release.

Also noting, an enhancement can be considered for a minor release [per Core's handbook](https://make.wordpress.org/core/handbook/about/release-cycle/releasing-minor-versions/):
>A minor release is intended for bugfixes and enhancements that do not add new deployed files and are at the discretion of the release lead with suggestions/input from component maintainers and committers.

TIL

**Comment by talldan** [comment]
Thanks for discussing it. I've removed the Backport label, so it isn't accidentally included 😄 

> It's marked as an enhancement.

Mislabelled, it's a shame that wasn't questioned a bit more, it's definitely a bug fix 🤦 

Agree with the other points discussed though, this is mostly why I raised the question. 👍

**Comment by hellofromtonya** [comment]
~I think there may be a misunderstanding. [Last week's bug scrub, consensus  was reached](https://github.com/WordPress/gutenberg/pull/64534#issuecomment-2315863032) that this fix could potentially be included in a 6.6.x minor release, but first needs to be released in the plugin.~

To keep it on the radar for tracking, I'm adding it to the  6.6.x project board. It's already being tracked in the 6.6 Specificity/Style tracking issue #64243.

**Comment by talldan** [comment]
What's the misunderstanding?

**Comment by hellofromtonya** [comment]
Me not reading it correctly 🤦‍♀️ 🤣 

Sorry about that @talldan. I re-read and now understand what you're saying here:
>I've removed the Backport label, so it isn't accidentally included 😄

Deserves another 🤦‍♀️ from me.

**Comment by talldan** [comment]
No worries, thanks for handling all the release coordination!

**Comment by jeffpaul** [comment]
@ktmn mind sharing your WordPress.org username so I can ensure its included in the 6.7 credits listing?
