### PR TITLE
Fix: pattern rendering issue

### LINKED ISSUE #66009: Patterns fail to load after switching from all patterns (page 2) to template parts tab
### Description

When navigating between the "All Patterns" tab (specifically on page 2) and the "Template Parts" tab, the patterns fail to load correctly, and a "No Results" message is displayed. This issue occurs only when switching between the second page of patterns and the template parts tab. The patterns should render properly, but instead, users encounter the "No Results" message until the page is refreshed or navigated again.

This issue was originally posted in WordPress Core Ticket [#62089](https://core.trac.wordpress.org/ticket/62089).

### Step-by-step reproduction instructions

1.  Log into your test site.
2. Go to Appearance > Editor
3. In the Design menu, select Patterns. By default, the template parts have 5 templates showing
4. In the "View options", set the Layout to Grid. 
5. Go into all patterns.
6. Navigate the next page using the pagination at the bottom of the editor.
7. Select the all template parts tab

🐞 Bug occurs. As no patterns display.

Expected Results :-
Step 7: Patterns should render after switching to All template parts tab.
When reproducing a bug:
✅ Step 7: patterns list is shown empty, no patterns are rendered

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/02298849-927f-4897-9a66-51f3b38b6b6a

### Environment info

OS: unbuntu
Web Server: Apache
PHP: 8.1.2
WordPress: 6.7 latest
Browser: Chrome
Theme: Twenty Twenty-Five
Active Plugins: None

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### PR DESCRIPTION
**Pull request by dhruvang21**
## What?
part of https://github.com/WordPress/gutenberg/issues/66009

## Why?
Fixes:-  https://github.com/WordPress/gutenberg/issues/66009

## How?
I’ve tracked down the issue and identified that it occurs because the page is not reset to page 1 when switching tabs. This happens due to the condition failure in the file [index.js#L124](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/page-patterns/index.js#L124). When switching tabs between wp_block post type and wp_template_part, neither has a category, so the categoryId defaults to PATTERN_DEFAULT_CATEGORY. As a result, both the previous and current categories are the same, causing the condition to fail.  I have added a condition using the same logic for the post type, which resolves the issue

## Testing Instructions
1.  Log into your test site.
2. Go to Appearance > Editor
3. In the Design menu, select Patterns. By default, the template parts have 5 templates showing
4. In the "View options", set the Layout to Grid. 
5. Go into all patterns.
6. Navigate the next page using the pagination at the bottom of the editor.
7. Select the all template parts tab
8. Patterns should render after switching to All template parts tab.

## Screenshots or screencast 
https://github.com/user-attachments/assets/5e94bd7d-dc45-4aed-b317-3434a22c6034

### CODE REVIEW

File: packages/edit-site/src/components/page-patterns/index.js [hunk 1]
```diff
@@ -78,6 +78,7 @@ export default function DataviewsPatterns() {
 	const categoryId = categoryIdFromURL || PATTERN_DEFAULT_CATEGORY;
 	const [ view, setView ] = useState( DEFAULT_VIEW );
 	const previousCategoryId = usePrevious( categoryId );
+	const previouspostType = usePrevious( type );
```
Comment (talldan) [inline packages/edit-site/src/components/page-patterns/index.js]: It'd be good to fix the capitalization of the variable - `previousPostType`

Comment (ramonjd) [inline packages/edit-site/src/components/page-patterns/index.js]:
```suggestion
	const previousPostType = usePrevious( type );
```

File: packages/edit-site/src/components/page-patterns/index.js [hunk 2]
```diff
@@ -121,10 +122,10 @@ export default function DataviewsPatterns() {
 
 	// Reset the page number when the category changes.
 	useEffect( () => {
-		if ( previousCategoryId !== categoryId ) {
+		if ( previousCategoryId !== categoryId || previouspostType !== type ) {
```
Comment (ramonjd) [inline packages/edit-site/src/components/page-patterns/index.js]:
```suggestion
		if ( previousCategoryId !== categoryId || previousPostType !== type ) {
```

File: packages/edit-site/src/components/page-patterns/index.js [hunk 3]
```diff
@@ -121,10 +122,10 @@ export default function DataviewsPatterns() {
...
 			setView( ( prevView ) => ( { ...prevView, page: 1 } ) );
 		}
-	}, [ categoryId, previousCategoryId ] );
+	}, [ categoryId, previousCategoryId, previouspostType, type ] );
```
Comment (ramonjd) [inline packages/edit-site/src/components/page-patterns/index.js]:
```suggestion
	}, [ categoryId, previousCategoryId, previousPostType, type ] );
```

**Review by ramonjd — APPROVED** [review]
I noticed the bug occurs regardless of view type (grid, table). So long as you paginate from all patterns and then switch to the templates view, it'll be empty. 

This PR fixes all that. Thank you very much, @dhruvang21!

## Before

https://github.com/user-attachments/assets/c2d7ab30-c53c-4a19-b84d-53ac10fd1416



## After

https://github.com/user-attachments/assets/3dfc102c-2c9e-4074-b442-837b5fdf56c3

**Comment by ramonjd** [comment]
I updated the variable name to camelCase and marked this PR to auto-merge.

Great work @dhruvang21 !

File: packages/edit-site/src/components/page-patterns/index.js (hunk 1 above)
Comment (dhruvang21) [reply packages/edit-site/src/components/page-patterns/index.js]: Thanks @ramonjd for fixing variable name.
