### PR TITLE
Cover block: fix flickering when inserted in templates and also fix isDark calculation bugs

### LINKED ISSUE #53211: Cover Block: flickering in site editor page view when used within a synced pattern
### Description

While reviewing #53169 an issue with the Cover block was encountered, where sometimes it will repeatedly flicker when displayed within the site editor's view of an individual page, when the Cover block is contained within a synced pattern that forms part of the template.

The flickering appears to be to do with logic in `useCoverIsDark` within the Cover block. Specifically, the async state update in:

https://github.com/WordPress/gutenberg/blob/ba31d2db18057faaada6a7394bcdf96d1e44aeda/packages/block-library/src/cover/edit/use-cover-is-dark.js#L43-L53

Kudos @aaronrobertshaw for finding the bug and the lines of code relevant for it!

### Step-by-step reproduction instructions

1. Create a synced pattern that contains a Cover block with a background image set
2. In a theme like TT3, add a new template (e.g. my-template.html in the `templates` directory).
3. Within `my-template.html`, add the synced block pattern. To get the markup to add to the template, you can add the synced pattern to a post or page, then view the code editor view and copy + paste to your `my-template.html` file
4. Create a page and set its template to `my-template.html`.
5. Open the site editor, and navigate to Pages > your newly created page. Click the preview of the page to switch to the edit mode, and notice that the Cover block flickers.

Example markup from my `my-template.html` file:

```
<!-- wp:template-part {"slug":"header","tagName":"header"} /-->

<!-- wp:pattern {"slug":"core/query-standard-posts"} /-->

<!-- wp:post-content /-->

<!-- wp:post-featured-image /-->

<!-- wp:template-part {"slug":"footer","tagName":"footer"} /-->

<!-- wp:block {"ref":65} /-->
```

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/14988353/482541e7-839c-4c9d-8cfa-d26afb86ec3f

### Environment info

- GB trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by glendaviesnz**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/53211
Also fixes bugs with the calculation if `isDark` that were identified while working on the above fix:

- When overly color is removed the color defaults to black but `isDark` is set to false
- Changing the dimRatio of the overlay color has no impact on the `isDark` setting so a black overlay dimRatio of 0 is still considered dark

## Why?
The `useEffects` used in the calculation of `isDark` are the cause for both the jitter and the above bugs, so easier to fix both at the same time.

## How?
Replace the `useEffects` with setting of `isDark` in the relevant event handlers.

### Flickering bug

1. Create a synced pattern that contains a Cover block with a background image set
2. In a theme like TT3, add a new template (e.g. my-template.html in the `templates` directory).
3. Within `my-template.html`, add the synced block pattern. To get the markup to add to the template, you can add the synced pattern to a post or page, then view the code editor view and copy + paste to your `my-template.html` file
4. Create a page and set its template to `my-template.html`.
5. Open the site editor, and navigate to Pages > your newly created page. Click the preview of the page to switch to the edit mode, and check that the Cover block does not flicker.

Example markup from my `my-template.html` file:

```
<!-- wp:template-part {"slug":"header","tagName":"header"} /-->

<!-- wp:pattern {"slug":"core/query-standard-posts"} /-->

<!-- wp:post-content /-->

<!-- wp:post-featured-image /-->

<!-- wp:template-part {"slug":"footer","tagName":"footer"} /-->

<!-- wp:block {"ref":65} /-->
```

### isDark bug and verifying all isDark workflows

- Add a Cover block and set a black overlay color, then add text and ensure the text is white
- Reduce the dimRatio below 50 and check that the text turns black
- Increase the dimRatio above 50 again and check that the text turns white again
- Change the overlay color to a light color and check that the text turns black
- Change the dimRatio above and below 50 and check that the text remains black
- Make sure dimRatio is above 50 with the light background and then add a very dark overlay image and check that the text remains black
- Reduce the dimRatio below 50 and check that the text turns white
- Replace the image with a very light one and check that the text turns black
- Remove both the image and the overlay color and check that the text turns white
- Add a new cover block with black overlay color and dimRation < 50
- Add light featured image to the post and toggle it on as the overlay image in the Cover block toolbar and check that the text color is black
- Toggle the feature image back off and check that the text is white again
- Repeat the above two steps with a dark feature image

In summary, my thinking is that whenever the image/featured image/overlay color/dim ratio is changed the isDark value should be updated in order to prevent text disappearing. **N.B.** - the only flow that will not reset the isDark setting is if a featured image is removed from the post via the post settings tab. The only way I can see to fix this is by adding a useEffect, but it is a very edge case and I don't think it is worth adding extra complexity to handle this.

## Screenshots or screencast 

Flicker before:

https://github.com/WordPress/gutenberg/assets/14988353/482541e7-839c-4c9d-8cfa-d26afb86ec3f

Flicker after:

https://github.com/WordPress/gutenberg/assets/3629020/def2a950-d89f-4917-8d4b-b21e0ea1617b

Is dark before:

https://github.com/WordPress/gutenberg/assets/3629020/81ac7268-cd41-4580-bf52-79ef7031f52d

Is dark after:

https://github.com/WordPress/gutenberg/assets/3629020/4789dc64-a6aa-40cc-8004-b3c1b88bc088

### CODE REVIEW

File: packages/block-library/src/cover/edit/use-cover-is-dark.js [hunk 1]
```diff
@@ -18,58 +20,68 @@ function retrieveFastAverageColor() {
...
-		// so use that color for the dark mode computation.
-		if ( dimRatio > 50 || ! url ) {
-			if ( ! overlayColor ) {
-				// If no overlay color exists the overlay color is black (isDark )
-				setIsDark( true );
+export default function useCoverIsDark( setAttributes ) {
+	const { __unstableMarkNextChangeAsNotPersistent } =
+		useDispatch( blockEditorStore );
+
+	const getCoverIsDark = useCallback(
```
Comment (andrewserong) [inline packages/block-library/src/cover/edit/use-cover-is-dark.js]: In `edit.js` this is used as `setCoverIsDark`. Should we call it that here, too?

File: packages/block-library/src/cover/edit/index.js [hunk 2]
```diff
@@ -112,6 +112,10 @@ function CoverEdit( {
 	);
 	const mediaUrl = media?.source_url;
 
+	if ( mediaUrl && useFeaturedImage ) {
+		setCoverIsDark( mediaUrl, dimRatio, overlayColor.color );
+	}
```
Comment (andrewserong) [inline packages/block-library/src/cover/edit/index.js]: Will this be called on every render? Would it be worth only calling if `mediaUrl`, `dimRatio`, or `overlayColor.color` changes?

That might wind up re-introducing some form of `useEffect`, though, which might not be the goal here 🤔

Comment (Mamaduka) [inline packages/block-library/src/cover/edit/index.js]: Can this logic also be moved inside the event handler? This will cause attribute updates on every render when a condition is true and trigger another re-render.

While it's okay to call `setState` during the render, I'm not sure if the same applies to the `setAttributes`.

File: packages/block-library/src/cover/edit/index.js [hunk 3]
```diff
@@ -103,7 +103,7 @@ function CoverEdit( {
 		'featured_media',
 		postId
 	);
-
+	const setCoverIsDark = useCoverIsDark( setAttributes );
```
Comment (Mamaduka) [inline packages/block-library/src/cover/edit/index.js]: This could become `getCoverIsDark` and let the components update the attribute. What do you think?

**Review by andrewserong — COMMENTED** [review]
This feels like a promising direction @glendaviesnz! It's fixed the flickering issue for me in templates that contain a pattern that has a cover block within it 👍

One subtle issue that I noticed while playing around with this is that if I adjust the overlay opacity very quickly, with this PR applied it's possible for it to not update when expected.

In the following screengrabs, on `trunk` the `is-light` class is correctly present when quickly dragging to the right. With this PR applied, it only appears to update when dragging slowly (or at least not quickly):

| Trunk | This PR |
| --- | --- |
|  |  |

Also a couple of the Color panel tests are currently failing — could that be related?

image

**Comment by Mamaduka** [comment]
I think this showcases how fragile attribute updates via effects can be in blocks. We should probably try and move similar logic into event handlers for other blocks as well.

File: packages/block-library/src/cover/edit/index.js (hunk 3 above)
Comment (glendaviesnz) [reply packages/block-library/src/cover/edit/index.js]: I was initially doing that and it just seemed like a lot of replicated:

```
__unstableMarkNextChangeAsNotPersistent();
setAttributes( { isDark: color.isDark } );
```
in each of the event handlers so moving to the hook removed the duplication, but I don't have a strong opinion on this. If you think this is better handled in the edit component I can move it back?

File: packages/block-library/src/cover/edit/use-cover-is-dark.js (hunk 1 above)
Comment (glendaviesnz) [reply packages/block-library/src/cover/edit/use-cover-is-dark.js]: Depends on the [answer to this question](https://github.com/WordPress/gutenberg/pull/53253#discussion_r1282625647) - what do you think?

File: packages/block-library/src/cover/edit/index.js (hunk 2 above)
Comment (glendaviesnz) [reply packages/block-library/src/cover/edit/index.js]: yeh, this is the one bit I wasn't sure on. Because the setting of featured image is outside the component we don't have access to the event handle, so maybe this is one case when an effect is better - will have a play.

Comment (glendaviesnz) [reply packages/block-library/src/cover/edit/index.js]: Yeh, this[ may be one place we need an effect still.](https://github.com/WordPress/gutenberg/pull/53253#discussion_r1282628098)

File: packages/block-library/src/cover/edit/index.js (hunk 3 above)
Comment (Mamaduka) [reply packages/block-library/src/cover/edit/index.js]: If we can "batch" the attribute updates, I think it's okay to include this in the `undo` history and drop the "non-persistent" action call. But I see that most attribute updaters have wrappers like `setMedia`; that would mean unwrapping them as well, probably not worth it at the moment.

File: packages/block-library/src/cover/edit/use-cover-is-dark.js (hunk 1 above)
Comment (andrewserong) [reply packages/block-library/src/cover/edit/use-cover-is-dark.js]: George does make a good point! I don't feel too strongly about it, though. Using `getCoverIsDark` might help neaten things a bit potentially as the `isDark` value could be updated in the same `setAttributes` call as other attributes (e.g. in `onClearMedia`, `onUpdateDimRatio`, etc)... but I suppose one challenge is that for images the update needs to happen asynchronously via the `.then()` since we won't immediately know the dark value?

**Comment by glendaviesnz** [comment]
Thanks for the great feedback @Mamaduka and @andrewserong, I have made your suggested changes and I think this makes things much more robust - have pushed the changes but have run out of time to fully test. I will give it a better test in the morning, but feel free to give it a quick once over and see if I have missed anything obvious.

**Comment by glendaviesnz** [comment]
> One subtle issue that I noticed while playing around with this is that if I adjust the overlay opacity very quickly, with this PR applied it's possible for it to not update when expected.

This seems to have been resolved by batching the update with the dimRatio attribute update.

File: packages/block-library/src/cover/edit/index.js (hunk 3 above)
Comment (glendaviesnz) [reply packages/block-library/src/cover/edit/index.js]: batching the updates where possible was a much better approach!

**Comment by glendaviesnz** [comment]
I will sort out the unit tests tomorrow.

**Comment by glendaviesnz** [comment]
I also need to add some awaits onto the getCoverIsDark calls I think as this can now  return a promise.

**Comment by andrewserong** [comment]
Thanks for the updates!

> This seems to have been resolved by batching the update with the dimRatio attribute update.

That does appear to resolve the issue of dragging quickly not updating correctly. One issue I'm seeing now is that for an image that in its `0` opacity (and that doesn't have an overlay color set) results in dark text on `trunk`, now dragging the opacity slider never results in dark text. If I set the Overlay to a hard color (e.g. white) then scrolling the slider does update correctly (even very quickly), so it looks like the issue has been resolved in terms of rapidly sliding the control. I'm not _too_ sure why the `0` opacity state isn't updating it to dark, though — but happy to give it a more detailed review again tomorrow!

Here's a quick screengrab demoing the above (note that the text is only dark in this screengrab when the Overlay color is set):

https://github.com/WordPress/gutenberg/assets/14988353/4017f041-cb0c-43da-a662-2126eac348df

File: packages/block-library/src/cover/edit/use-cover-is-dark.js [hunk 4]
```diff
@@ -18,58 +18,66 @@ function retrieveFastAverageColor() {
...
-	}, [ url, url && dimRatio <= 50, setIsDark ] );
-	useEffect( () => {
-		// If opacity is greater than 50 the dominant color is the overlay color,
-		// so use that color for the dark mode computation.
-		if ( dimRatio > 50 || ! url ) {
-			if ( ! overlayColor ) {
-				// If no overlay color exists the overlay color is black (isDark )
-				setIsDark( true );
-				return;
+export default function useCoverIsDark() {
```
Comment (Mamaduka) [inline packages/block-library/src/cover/edit/use-cover-is-dark.js]: I think now this could be just a callback `getCoverIsDark`, and there's no need for `useCallback` memoization.

File: packages/block-library/src/cover/edit/use-cover-is-dark.js [hunk 5]
```diff
@@ -18,58 +18,66 @@ function retrieveFastAverageColor() {
...
+	const getCoverIsDark = useCallback(
+		( url, dimRatio = 50, overlayColor ) => {
+			// If the dimRatio is less than 50, the image will have the most impact on darkness.
+			if ( url && dimRatio <= 50 ) {
```
Comment (stokesman) [inline packages/block-library/src/cover/edit/use-cover-is-dark.js]: Before, when wrapped in an effect, this branch didn’t execute unless `url` had changed. Now, it may execute needlessly for changes to `overlayColor` or `dimRatio` (given `dimRatio` is less than `50`). Since the `url` hasn't changed the color average and resulting `isDark` determination will end up the same. Not sure it’s objectionable or worth optimizing but thought it should be noted.

File: packages/block-library/src/cover/edit/use-cover-is-dark.js (hunk 4 above)
Comment (glendaviesnz) [reply packages/block-library/src/cover/edit/use-cover-is-dark.js]: yeh, now we are not saving state or setting attributes there isn't any point in it being a hook, have moved it to a standard method in the shared methods folder.

**Comment by glendaviesnz** [comment]
> One issue I'm seeing now is that for an image that in its 0 opacity (and that doesn't have an overlay color set) results in dark text on trunk

@andrewserong I think this was due to the missing awaits, which I have now added and it seems to work as expected now.

File: packages/e2e-tests/specs/editor/various/__snapshots__/inserting-blocks.test.js.snap [hunk 6]
```diff
@@ -88,8 +88,8 @@ exports[`Inserting blocks inserts a block in proper place after having clicked \
 <p>First paragraph</p>
 <!-- /wp:paragraph -->
```
Comment (glendaviesnz) [inline packages/e2e-tests/specs/editor/various/__snapshots__/inserting-blocks.test.js.snap:90]: I think it was a bug in the hook that caused `isDark` attrib to be set to false when a Cover block was first inserted. 

I don't think there are any backwards compat issues to it now behaving correctly and not setting this unless a light image or background is selected after the block is inserted, but let me know if you can see any issues.

I added a Cover block placeholder to a post on trunk and saved, checked out this PR and reloaded the post and there were no errors, and selecting color or image on the placeholder worked as expected.

**Comment by glendaviesnz** [comment]
Switching from hook to a standard method is a reasonably big change so probably needs another thorough review sorry.

**Comment by glendaviesnz** [comment]
I seem to have broken a couple of things with the latest changes so don't bother testing again yet

File: packages/block-library/src/cover/shared.js [hunk 7]
```diff
@@ -109,3 +117,62 @@ export function getPositionClassName( contentPosition ) {
...
+function retrieveFastAverageColor() {
+	if ( ! retrieveFastAverageColor.fastAverageColor ) {
+		retrieveFastAverageColor.fastAverageColor = new FastAverageColor();
+	}
+	return retrieveFastAverageColor.fastAverageColor;
+}
+
+/**
+ * getCoverIsDark is a method that specifyies if the cover background is dark or not and
+ * applies the relevant attribute to help ensure that text is visible by default.
```
Comment (andrewserong) [inline packages/block-library/src/cover/shared.js]: Nit: `getCoverIsDark` no longer applied the attribute, rather it's handled in the block's code. Shall we update this comment?

File: packages/block-library/src/cover/shared.js [hunk 8]
```diff
@@ -109,3 +117,62 @@ export function getPositionClassName( contentPosition ) {
...
+ * - When the overlay color is removed
+ * - When the dimRatio is changed
+ *
+ * See the comments below for more details about which aspects take priority when
+ * calculating the relative darkness of the Cover.
+ *
+ * @param {string} url
+ * @param {number} dimRatio
+ * @param {string} overlayColor
+ * @return {boolean|Promise} True if cover should be considered to be dark.
```
Comment (andrewserong) [inline packages/block-library/src/cover/shared.js]: Does this ever return a promise? Now that there's an `await` on `retrieveFastAverageColor()` it looks like it always returns a boolean.

If that's the case, then I _think_ the code in `edit/index.js` might not need to be async functions, since the await is handled internally by `getCoverIsDark`? I could be wrong, though, so apologies if that's a red herring!

**Review by andrewserong — COMMENTED** [review]
Nice one @glendaviesnz! This is looking really good, each of the event handlers appears to be updating the `isDark` value as expected and I haven't run into any issues across all actions (uploading media, using featured images, clearing media, changing overlay colors and dimRatio, etc), and it still fixes the flickering issue 👍

Just left a couple of comments — ~now that there's an `await` in `getColorIsDark`, I was wondering if the other handlers need to be "async" if `getColorIsDark` never returns a promise?~ Edit: nevermind, I was misunderstanding how async functions work in this way.

File: packages/block-library/src/cover/shared.js (hunk 8 above)
Comment (andrewserong) [reply packages/block-library/src/cover/shared.js]: Nevermind, thanks for explaining how `async` works in this case @glendaviesnz! For reference in case anyone else looking at this made the same mistake as me here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function#description

**Review by andrewserong — APPROVED** [review]
This is testing great for me! Might be worth waiting for another review before merging, too, just to make sure we're covered since changing this part of the Cover block can be pretty tricky.

Great work here, though, the approach feels like a big improvement for the block, while resolving the tricky flickering issue! ✨

File: packages/block-library/src/cover/shared.js (hunk 7 above)
Comment (glendaviesnz) [reply packages/block-library/src/cover/shared.js]: Thanks, fixed.

File: packages/block-library/src/cover/edit/use-cover-is-dark.js (hunk 5 above)
Comment (glendaviesnz) [reply packages/block-library/src/cover/edit/use-cover-is-dark.js]: Thanks for pointing that out. I have done some testing and this doesn't seem to introduce any performance issues, even in the places where this might get called a lot, like dragging the mouse around the custom color picker, so given the extra complexity it would add in order to better track when and when not to run this, and the fact that is now only explicitly run in event handlers, I don't think it is worth trying to optimise it at this stage.

**Comment by stokesman** [comment]
👋 Hey folks. I've been following along here (and on the issue before this PR). I'm pleased to see how this progressed. The approach matches where my mind first went on thinking of a solution, i.e. "Try not to derive the attribute in an effect when it could be done with event handlers". Still, out of curiosity, I tried an alternate approach in revamping the hook #53317. It solves the issue in my testing and due to its fewer changes might be more compelling from a maintenance perspective. If there’s time available, I'd like it if it could be considered. Much respect to all the great work and collaboration that's gone into this and I'm offering it up in the same spirit.

**Comment by glendaviesnz** [comment]
> I tried an alternate approach in revamping the hook #53317

Thanks for this @stokesman, I ran out of time today to get to this, and it is my end of week here, so will try and take a closer look on Monday if someone else doesn't get to it.

**Comment by ajlende** [comment]
It seems my old unmerged PR https://github.com/WordPress/gutenberg/pull/45076 that improves the heuristic also seems to fix it. The PR already has one approval, but if you'd like to take a look, it might be another alternative. I explained what I think is going on and how it fixes it in the [original issue](https://github.com/WordPress/gutenberg/issues/53211#issuecomment-1665756058).

**Comment by stokesman** [comment]
> I ran out of time today to get to this, and it is my end of week here, so will try and take a closer look on Monday

Thanks Glen! Now that Alex has brought up his PR, I'm very much in favor of it. So please disregard the PR I made as an alternate to this and instead have a look at Alex’s to see if you agree we should incorporate it first.

**Comment by glendaviesnz** [comment]
@ajlende, @stokesman, the heuristic used in #45076 does seem to provide a better outcome in terms of the dark/light setting, but for me it does not fix the flickering issue.

I have [copied the updated heuristic to this PR](https://github.com/WordPress/gutenberg/pull/53253/commits/da469fe0c89f285297afa4484b35754915243b47), and this gives the same improved results while still also fixing the flickering.

@stokesman, I understand your preference for a small change over a major refactor, especially in a block as commonly used as the Cover. If this was going into 6.3.1 I would also be very onboard with that. If we are thinking 6.4 for this change,  given we have a couple of months until the next release I wonder if we should take the opportunity to make a bigger improvement in the structure of this block. This is not really a good use of an effect, and across the project we should be looking to move from the use of effects to update internal state in preference for using event handlers where possible, and this is a good opportunity to do this.

I don't have a strong opinion on this though, so happy to hear what others think. @andrewserong, @Mamaduka what are your thoughts?

**Comment by andrewserong** [comment]
> does seem to provide a better outcome in terms of the dark/light setting, but for me it does not fix the flickering issue.

Yes, I saw the same.

> I don't have a strong opinion on this though, so happy to hear what others think

I usually like the idea of trying out smaller changes, and doing things iteratively where we can. In this case, from my perspective, each of the changes are fairly significant in the sense that we'll need to thoroughly test every permutation of changes to the cover block to make sure that the `isDark` value and block attributes updates are correct, even if the code change itself is fairly small. For example, in #53375, although it's a smaller change, due to the updates to the `useEffect` and the dependency array, I think we'd still need to be careful that all the changes are behaving as we'd expect.

So in that respect, I'm currently leaning toward the idea of seeing if we can land an approach that we think is what we'd like in the longer term for the block.

I don't feel very strongly about it, though, so happy to hear what everyone else thinks, too!

**Comment by stokesman** [comment]
My first instinct is to go for an overhaul like this PR because it should be more efficient. On the other hand, I’d like to avoid introducing complexity to an already complex block while possible. I'm glad it’s being considered and don't mind much what decision is reached.

> we should be looking to move from the use of effects to update internal state in preference for using event handlers where possible

I agree, though not without exceptions. Strictly speaking, it has not proven possible for this PR. As is, we have to lean on it for the one case anyway so if we reduce complexity by employing it for all cases it seems justifiable.

> For example, in https://github.com/WordPress/gutenberg/pull/53375, although it's a smaller change, due to the updates to the useEffect and the dependency array, I think we'd still need to be careful that all the changes are behaving as we'd expect.

I'm glad you saw that PR. I just want to point out the change to the dependency array is only the addition of two dependencies that are stable. They could be left out, just as they are in trunk and as they are in the similar effect in this PR. Anyway, I agree no matter what we do care must be taken!

**Comment by glendaviesnz** [comment]
> Strictly speaking, it has not proven possible for this PR. 

Even though one case does still use an effect, in 4 out of the 6 use cases we are now bundling the attribute update with the source event which I think is enough of a potential efficiency gain to still warrant the change. 

Good discussion @stokesman, thanks for raising it. 

@Mamaduka did you have any additional thoughts to add before we try and make a decision on this?

**Comment by Mamaduka** [comment]
I like the direction of this PR. The only time the effect is used is with the featured image.

Every time we refactor away from using effects, it would require a lot of changes, but that's good, IMO.

**Review by Mamaduka — APPROVED** [review]

File: packages/block-library/src/cover/shared.js [hunk 9]
```diff
@@ -109,3 +117,81 @@ export function getPositionClassName( contentPosition ) {
...
+ */
+export async function getCoverIsDark( url, dimRatio = 50, overlayColor ) {
+	const overlay = colord( overlayColor )
+		.alpha( dimRatio / 100 )
+		.toRgb();
+	// If the dimRatio is less than 50, the image will have the most impact on darkness.
+	if ( url && dimRatio <= 50 ) {
```
Comment (ajlende) [inline packages/block-library/src/cover/shared.js]:
```suggestion
	if ( url ) {
```

The new heuristic works on all dim ratios.

**Review by ajlende — APPROVED** [review]
I've tested all the listed scenarios:

- When an overlay image is added, changed or removed
- When the featured image is selected as the overlay image, or removed from the overlay
- When the overlay color is changed
- When the overlay color is removed
- When the dimRatio is changed

They all seem to be working for me. I was never able to reproduce the original flickering issue, but things do still work as I expect here.
