### PR TITLE
Site Editor: Append template type and name to the site editor page title

### LINKED ISSUE #47730: Site Editor: routing should update the document title
### Description

From a user experience perspective, navigation in Single Page Applications (SPA) should emulate as much as possible the 'traditional' navigation mechanism (page load).

The Site Editor is basically a SPA that implements a routing mechanism. So far so good, the routing mechanism works well.

However, the document title is not updated. It's always the same. This has a few consequences that aren't limited to accessibility. It's a known usability and accessibility issue with SPAs, at the point that Dan Abramov himself built a little tool to solve it, a few years ago. See https://github.com/gaearon/react-document-title

1
The entries in the browser history have all the same name. This makes impossible for users to efficiently use a native browser feature. When trying to navigate through the browser fully history, users can;t distinguish the history entries. To reproduce:
- Go to the Site Editor.
- Navigate multiple times through the Templates and Template parts, just to fill the browser history.
- Click _and hold_ the browser Back button.
- Observe the history entries have all the same name, which makes the browser history arguably usable.

Screenshot:

history entries

- Same happens when opening the browser fully history page, typically under the browser 'History' menu >  'Show full history' or something along that line. In Chrome, it will open the full history at: chrome://history/
- Since the Site Editor history entries have all the same name, this native browser feature is basically unusable.

2
Minor: Bookmarking a page is a native browsers feature. When bookmarking multiple Site Editor pages, by default they will all have the same name. Distinguishing the bookmarks would be impossible. Users would be forced to edit the bookmark title each time they bookmark a Site Editor page.

3
Important for a11y: Navigation through the Site Editor pages is announced with a `speak` message via `useTitle`. The message text appends `document.title` to the text `Now displaying: `. Unfortunately, since the document title never updates, the `speak` message is always the same and it's basically useless.
When navigating, screen reader users will always get the same audible message, e.g.:

`Now displaying: Editor (beta) ‹ {site title} — WordPress`

Screenshots:

Screenshot 2023-02-03 at 09 11 14

Screenshot 2023-02-03 at 09 11 20

Screenshot 2023-02-03 at 09 11 52

Screenshot 2023-02-03 at 09 11 08

Note: one more issue with SPAs navigation is about where initial focus should land after navigation. I will reate a separate issue for that.

### Step-by-step reproduction instructions

- Go to the site editor
- Navigate through the Templates and Template parts.
- Observe the document title doesn't updated.
- Click _and hold_ your Browser Back button.
- Observe the History entries have all the same name.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by glendaviesnz**
## What?
Adds the template name and type to the page title

## Why?
Currently every page in the editor has the same tile, which makes navigating the history impossible.

Fixes: #47730

## How?
Passes the page template name and type into the `useTitle` hook.

## Testing Instructions
Open the site editor
Navigate to different templates and template parts
Check that the page title updates with the template type and name as you navigate, and that the browser history shows the full page titles

## Screenshots or screencast 

Before:

https://user-images.githubusercontent.com/3629020/217401640-da2d8728-9630-4409-a336-bd3d7a81900e.mp4

After:

https://user-images.githubusercontent.com/3629020/217401666-0755bf2e-6e33-486a-afc5-534ebd47bd11.mp4

### CODE REVIEW

File: packages/edit-site/src/components/editor/index.js [hunk 1]
```diff
@@ -138,9 +138,18 @@ export default function Editor() {
...
 	const isReady = editedPostType !== undefined && editedPostId !== undefined;
 
+	let titleBreadcrumb;
+	if ( isReady && editedPost ) {
+		const type =
+			editedPostType === 'wp_template'
+				? __( 'Template' )
+				: __( 'Template Part' );
+		titleBreadcrumb = `${ editedPost.title?.rendered } ‹ ${ type } ‹ `;
+	}
```
Comment (kevin940726) [inline packages/edit-site/src/components/editor/index.js]: Nit: I think can just construct the `title` string here for simplicity (`useMemo` is probably not needed):

```suggestion
	const title = useMemo( () => {
		const type =
			editedPostType === 'wp_template'
				? __( 'Template' )
				: __( 'Template Part' );
		return `${ editedPost.title?.rendered } ‹ ${ type } ‹ ${ __( 'Editor (beta)' ) }`
	}, [ editedPost.title, editedPostType ] );
```

Then later we can just do:

```js
useTitle( isReady && title );
```

**Review by kevin940726 — APPROVED** [review]
It tested well for me! Not sure if it satisfies the accessibility checklist though.

File: packages/edit-site/src/components/editor/index.js (hunk 1 above)
Comment (glendaviesnz) [reply packages/edit-site/src/components/editor/index.js]: I was thinking that there might be instances where `editedPost` was not set so title would then just need to be `Editor (beta)` but I did some more testing and this doesn't seem to ever be the case, so have simplified as you suggested, but without the useMemo  - this isn't a calculation heavy bit of logic so I agree that this probably isn't needed.

**Review by apeatling — APPROVED** [review]
Tested and confirmed the page title updates, this is a nice change. 👍

**Comment by ntsekouras** [comment]
Cherry-picked this PR to the wp/6.2 branch.

**Comment by afercia** [comment]
Nice! Thanks everyone ❤️ 
The history entries are pretty clear now. Maybe not that concise but clear :) 
The audible message may be a bit too long sometimes but I'd suggest to wait for feedback from screen reader users.

File: packages/edit-site/src/components/editor/index.js [hunk 2]
```diff
@@ -138,9 +138,20 @@ export default function Editor() {
...
 	const isReady = editedPostType !== undefined && editedPostId !== undefined;
 
+	let title;
+	if ( isReady && editedPost ) {
+		const type =
+			editedPostType === 'wp_template'
+				? __( 'Template' )
+				: __( 'Template Part' );
+		title = `${ editedPost.title?.rendered } ‹ ${ type } ‹ ${ __(
+			'Editor (beta)'
```
Comment (youknowriad) [inline packages/edit-site/src/components/editor/index.js:148]: I think we should remove "beta" now.

Comment (youknowriad) [reply packages/edit-site/src/components/editor/index.js:148]: Also, I'm not entirely certain that we should concat translated items like that, we should probably be using `sprintf` here.

Comment (youknowriad) [reply packages/edit-site/src/components/editor/index.js:148]: There's also a hook `useEditedEntityRecord` that would save a few lines of code here (allows to call `getTitle` directly and also provide access to the `record` if needed.

Comment (glendaviesnz) [reply packages/edit-site/src/components/editor/index.js:148]: I have added a [follow up PR here](https://github.com/WordPress/gutenberg/pull/48053) to cover off these suggestions.
