### PR TITLE
Fix: Move the "View Posts..." anchor out of the role=toolbar section in the header

### LINKED ISSUE #15331: Toolbar elements are tabbable
Toolbar elements are tabbable

-   **Severity:** Medium
-   **Affected Populations:**
    -   Blind
    -   Motor Impaired
    -   Cognitively Impaired
-   **Platform(s):**
    -   All / Universal
-   **Components affected:**
    -   Editor Top Bar

#### Issue description

Keyboard-only users who enter the Editor Top Bar must Tab from button to
button. Although this is manageable when there's a small number of
buttons, the group of buttons is given the role of `toolbar`, whose
purpose (besides grouping related controls) is to lessen the number of
Tab stops keyboard users must make to navigate past widgets.

Screen reader users may be told they are entering a toolbar and expect
to be able to Tab past everything in it. Their experience does not match
the promise of the role.

Screen reader users may also miss the toolbar role when meeting the
first item (an anchor), because roles such as toolbar are sometimes only
announced when users meet items which can trigger their forms/focus
mode. Since the anchor's behaviour is semantically different from the
buttons' (the buttons deal with the editable content, the anchor simply
takes users back), it may make more sense to keep the anchor out of the
toolbar group.

##### Issue Code

```
    <div role="region" aria-label="Editor top bar" class="edit-post-header" tabindex="-1">


        <div role="toolbar" aria-orientation="horizontal" class="edit-post-header-toolbar" aria-label="Document tools">


            <div class="components-toolbar components-toolbar edit-post-fullscreen-mode-close__toolbar">


                <a href="edit.php?post_type=post" aria-label="View Posts" class="..."><svg aria-hidden="true"...>...</svg></a>


            </div>


        <div>


            <div class="editor-inserter">


                <button type="button" aria-label="Add block" aria-haspopup="true" aria-expanded="false" class="...">...</button>


            </div>


        </div>


        <button type="button" aria-label="Undo" aria-disabled="false" class="...">...</button>


        <button type="button" aria-label="Redo" aria-disabled="true" class="...">...</button>


        <div class="table-of-contents">


            <button type="button" aria-label="Content structure" aria-expanded="false" aria-disabled="false" class="...">...</button>


        </div>


        ...


    </div>

```

#### Remediation Guidance

Move the "View Posts..." anchor out of the `role=toolbar` section,
so the toolbar only has `<button>` children.

Although ideally it would be a better use of the `toolbar` pattern to
implement Arrow-keys only, and not support Tab navigation between items,
this pattern may not be familiar to all users. Adding support for the
Home and End keys (for jumping to the first and last item in the
toolbar) will help here: this will allows users who know the keyboard
pattern for ARIA toolbars to efficiently get past the toolbar, while
leaving the Tab pattern for users who do not.

##### Recommended Code

```
    <div role="region" aria-label="Editor top bar" class="edit-post-header" tabindex="-1">


        <div class="...">


            <a href="edit.php?post_type=post" aria-label="View Posts" class="..."><svg aria-hidden="true"...>...</svg></a>


        </div>


        <div role="toolbar" aria-orientation="horizontal" class="edit-post-header-toolbar" aria-label="Document tools">


            <div>


                <div class="editor-inserter">


                    <button type="button" aria-label="Add block" aria-haspopup="true" aria-expanded="false" class="...">...</button>


                </div>


            </div>


            <button type="button" aria-label="Undo" aria-disabled="false" class="...">...</button>


            <button type="button" aria-label="Redo" aria-disabled="true" class="...">...</button>


            <div class="table-of-contents">


                <button type="button" aria-label="Content structure" aria-expanded="false" aria-disabled="false" class="...">...</button>


            </div>


        </div>


        ...


    </div>

```

#### References

<https://www.w3.org/TR/wai-aria-practices-1.1/#toolbar>

#### Relevant standards

-   [2.1.1 Keyboard
    (Level A)](https://www.w3.org/TR/WCAG20/#keyboard-operation-keyboard-operable)

**Note:** This issue may be a duplicate with other existing accessibility-related bugs in this project. This issue comes from the Gutenberg accessibility audit, performed by [Tenon](https://www.tenon.io) and funded by [WP Campus](https://wpcampus.org/). This issue is GUT-8 in Tenon's report

### PR DESCRIPTION
**Pull request by gziolo**
## Description
Partially fixes #15331.

> Screenshot from full report:
> 
> image

> Keyboard-only users who enter the Editor Top Bar must Tab from button to
button. Although this is manageable when there's a small number of
buttons, the group of buttons is given the role of toolbar, whose
purpose (besides grouping related controls) is to lessen the number of
Tab stops keyboard users must make to navigate past widgets.

This PR follows the recommendation:

> Move the "View Posts..." anchor out of the `role=toolbar` section,
> so the toolbar only has `<button>` children.

## Testing

Enabled Fullscreen Mode through More Menu item. Ensure that the header looks like before and `View Posts` anchor is outside of the toolbar.

## Screenshots 

Screen Shot 2019-05-17 at 09 56 37
Screen Shot 2019-05-17 at 09 57 03

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/edit-post/src/components/header/index.js [hunk 1]
```diff
@@ -38,7 +39,10 @@ function Header( {
 			className="edit-post-header"
 			tabIndex="-1"
 		>
-			<HeaderToolbar />
+			<div>
```
Comment (gziolo) [inline packages/edit-post/src/components/header/index.js]: @kjellr or @jasmussen - I don't know if this is the best idea to wrap them with div but I took as little steps as possible to make it look close to what we had before. I would love to hear your recommendations because I also noticed that the border is slightly broken now:

Screen Shot 2019-05-17 at 10 02 08

Comment (jasmussen) [reply packages/edit-post/src/components/header/index.js]: Yep was about to note the same. There's a height difference to the toolbar. Even outside of fullscreen. This branch:

Screenshot 2019-05-17 at 10 58 51

Master:

Screenshot 2019-05-17 at 10 59 47

Let me take a look.

Comment (jasmussen) [reply packages/edit-post/src/components/header/index.js]: It looks like if this particular div is assigned `display: flex;`, and `.edit-post-fullscreen-mode-close__toolbar` is also assigned `display: flex;` (instead of `inline-block` as it is now), both issues are fixed:

Screenshot 2019-05-17 at 11 03 19

Screenshot 2019-05-17 at 11 03 38

I could use a sanity check by Kjell though.

Comment (kjellr) [reply packages/edit-post/src/components/header/index.js]: > It looks like if this particular div is assigned display: flex;, and .edit-post-fullscreen-mode-close__toolbar is also assigned display: flex; (instead of inline-block as it is now), both issues are fixed:

Yep, that fixes it for me too. 👍

**Comment by gziolo** [comment]
I applied changes as recommended by @jasmussen and @kjellr, many thanks for your help 🙇 

It seems like UI wise everything looks exactly the same now:

Branch:

Screen Shot 2019-05-17 at 16 55 23
Screen Shot 2019-05-17 at 16 55 38

Master:

Screen Shot 2019-05-17 at 16 59 53
Screen Shot 2019-05-17 at 17 00 04

**Comment by jasmussen** [comment]
Nice work. Be sure to test all mobile breakpoints, and Firefox and Safari. Otherwise, 👍👍

**Comment by gziolo** [comment]
It seems to work the same on Firefox, Safar. At mobile breakpoints, there is no Fullscreen Mode so nothing to test there, well I did it, it just works :)

One more check and I think it confirms it works the same as in `master`.

Branch:

Screen Shot 2019-05-17 at 17 32 18

Master:

Screen Shot 2019-05-17 at 17 45 01

**Review by kjellr — APPROVED** [review]
Tested in Safari, Chrome, + FF, across a wide range of screen widths. Looks great to me!
