### PR TITLE
Edit Site: Integrate quick inserter.

### LINKED ISSUE #23492: Site editor: Inserter missing functionality
**Describe the bug**
The Inserter in the post editor was recently updated and some of the functionality is missing in the site editor's version of the Inserter.

1. The "Browse all" button is missing.

**Current:**
image

**Expected:**
image

2. Patterns are not showing when initiating a search.

**Current:**
image

**Expected:**
image

### PR DESCRIPTION
**Pull request by epiqueras**
Closes #23492.

### CODE REVIEW

**Comment by MichaelArestad** [comment]
This looks like it resolves the issues. Thanks! (I can't speak to the code, unfortunately, or I would approve it.)

File: packages/edit-site/src/store/selectors.js [hunk 1]
```diff
@@ -47,29 +47,33 @@ export const getCanUserCreateMedia = createRegistrySelector( ( select ) => () =>
...
  *
- * @param {Object} state Global application state.
+ * @param {Object}   state             Global application state.
+ * @param {Function} setIsInserterOpen Setter for the open state of the global inserter.
  *
  * @return {Object} Settings.
  */
 export const getSettings = createSelector(
-	( state ) => {
+	( state, setIsInserterOpen ) => {
```
Comment (ItsJonQ) [inline packages/edit-site/src/store/selectors.js:56]: One thought! For the second arg, would it be helpful if it were an object? Like:

`createSelector( state, options = {})`

My thinking is that it would more gracefully handle additional enhancements to `getSettings` as Edit Site evolves.

(Totally not a blocker though!)

**Review by ItsJonQ — APPROVED** [review]
🚀 Looks good to me! Tested locally and working. I left a small comment re: the update `getSettings()` function. Not a blocker though! Just a thought :)

File: packages/edit-site/src/store/selectors.js (hunk 1 above)
Comment (epiqueras) [reply packages/edit-site/src/store/selectors.js:56]: Yes!, but since it's not public yet, let's just change it when the need arises.
