### PR TITLE
DataViews: Fix focus transfer while searching in `list` layout

### LINKED ISSUE #67758: DataViews List View: Search input loses focus
When you search when in the List view the focus sometimes shifts to the list, away from the input. I would expect the focus to stay in the search field.

Image

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/67758

Alternative of: https://github.com/WordPress/gutenberg/pull/71810

In `list` layout of DataViews sometimes there is a focus transfer while searching. The issue cannot be reproduced consistently in 'real' usage because of racing conditions between Ariakit's removal/set of active composite item and our own updating of that. I've added an e2e test for that.

The main issue was setting focus to the active list item unconditionally when selecting a new active composite item. That was problematic because while it's fine to keep setting the active item id to a new item if the previous active item was removed from the list, but focus should only update if our above programmatic selection came from within the composite itself (keyboard navigation, etc..).

## Testing Instructions

Results might be inconsistent, but I could reproduce 'reliably' if I typed fast :)
1. In site editor go to `pages` page in list layout
2. wait a bit for Ariakit to set the active item (first of the list)
3. type 'fast' something that would exclude the first item of the list (previous active item)
4. focus should be preserved in search input.

### Before

https://github.com/user-attachments/assets/d0ebc6e4-c7d8-4d50-9356-b963abde8e78

### After

https://github.com/user-attachments/assets/1fd59330-d5d5-4fe9-898f-506323b76aa8

### CODE REVIEW

File: packages/dataviews/src/components/dataviews-layouts/list/index.tsx [hunk 1]
```diff
@@ -465,7 +467,13 @@ export default function ViewList< Item >( props: ViewListProps< Item > ) {
...
 
 			setActiveCompositeId( targetCompositeItemId );
-			document.getElementById( targetCompositeItemId )?.focus();
+			if (
+				compositeRef.current?.contains(
+					compositeRef.current.ownerDocument.activeElement
+				)
+			) {
+				document.getElementById( targetCompositeItemId )?.focus();
+			}
```
Comment (Mamaduka) [inline packages/dataviews/src/components/dataviews-layouts/list/index.tsx:480]: Do you think we should add an inline comment for this condition for future reference?

**Review by Mamaduka — APPROVED** [review]
Thanks, Nik!

The fix to avoid focus shift makes sense. I was able to reproduce the bug and confirm it's fixed now.

File: packages/dataviews/src/components/dataviews-layouts/list/index.tsx (hunk 1 above)
Comment (ntsekouras) [reply packages/dataviews/src/components/dataviews-layouts/list/index.tsx:480]: Sure!
