### PR TITLE
Separator: Surfacing the HTML markup control

### LINKED ISSUE #70441: Find alternative solutions for surfacing the HTML markup control in the Separator block
In https://github.com/WordPress/gutenberg/pull/70185 the HTML Select control of the Separator block was moved from the advanced inspector (where it lives for every single other block that has this control) so the top level inspector area. 

This change was done to improve the accessibility of the separator block because in most instances the separator should not be a literal `hr` element but rather a `span`/`div` without semantic meaning...

I can totally understand the need to surface the control more in the UI.

What I am concerned about, is that the way this was done caused a large regression in the usability for all the other controls of the block.

All the design tools of the separator block were accessible without needing to click on anything in the sidebar. Now with this change the sidebar is split into the settings and the design tabs which means all the controls that were previously directly accessible without needing to click anywhere are now hidden behind a tab. And instead we just have a whole bunch of whitespace in the sidebar creating a really subpar experience.

CC: @amberhinds @t-hamano

### PR DESCRIPTION
**Pull request by Infinite-Null**
## What?
Closes #70441

Reverts the HTML element control in the Separator block back to the Advanced Inspector panel to restore consistent UI patterns and improve overall usability.

## Why?

In PR #70185, the HTML element control was moved from the Advanced Inspector to the top-level Settings panel to improve accessibility. However, this change created a significant usability regression.

## How?

This PR reverts the UI changes from #70185 by:
- Moving the `HtmlElementControl` back to `InspectorAdvancedControls` 
- Keeping the helpful control itself (just moving its location)

## Testing Instructions

1. Open the WordPress block editor (post or page)
2. Insert a Separator block
3. Open the block settings in the sidebar
5. Click on the "Advanced" section at the bottom of the inspector
6. Verify that the "HTML element" control is present and functional
7. Test changing between `<hr>` and `<div>` options
8. Confirm the separator renders with the correct HTML element in both editor and frontend

## Screenshots or screencast

|Before (Current)|After (This PR)|
|-|-|
|image|image|

### CODE REVIEW

**Comment by Infinite-Null** [comment]
Hi @t-hamano, I have reverted the changes and moved `HTML element control` to the Inspector advanced section. Please review it at your convenience.

File: packages/block-library/src/separator/edit.js [hunk 1]
```diff
@@ -84,37 +75,11 @@ export default function SeparatorEdit( { attributes, setAttributes } ) {
...
-							isShownByDefault
-						>
-							<HtmlElementControl
-								tagName={ tagName }
-								setAttributes={ setAttributes }
-							/>
-						</ToolsPanelItem>
-					</ToolsPanel>
-				) }
+			<InspectorControls group="advanced">
```
Comment (Infinite-Null) [inline packages/block-library/src/separator/edit.js:78]: While we could also use `InspectorAdvancedControls` to achieve the same result, I followed the approach used in the previous PR and implemented it using `InspectorControls` for consistency.  Happy to adjust if there’s a preference for a different approach.

Comment (t-hamano) [reply packages/block-library/src/separator/edit.js:78]: Either way is fine since they have the same meaning, but it appears that [InspectorAdvancedControls exists for backward compatibility](https://github.com/WordPress/gutenberg/blob/de918f7042142dff69b99998bc02749f135e26cd/packages/block-editor/src/components/inspector-controls/index.js#L11). Therefore, the current approach of using InspectorControls seems to be fine.

**Review by t-hamano — APPROVED** [review]
Thanks for the PR!

I support this PR, but I want to avoid moving the UI multiple times due to disagreements, as this creates cognitive load for users. Let's take a moment and wait for the additional feedback.

**Review by t-hamano — DISMISSED** [review]
As discussion is still ongoing on #70441, let's pause moving forward with this PR.

**Comment by t-hamano** [comment]
After much thought, let's merge this PR for now. See https://github.com/WordPress/gutenberg/issues/70441#issuecomment-3061628521

**Review by t-hamano — APPROVED** [review]
