### PR TITLE
CustomSelectControl: Refactor to use Ariakit store state for current value

### LINKED ISSUE #67759: CustomSelectControl: Button description doesn't update correctly when uncontrolled
When in uncontrolled mode, the trigger button of the `CustomSelectControl` doesn't get its ARIA description updated properly after a selection change.

## Steps to reproduce

In the Storybook for CustomSelectControl, add a temporary story to test uncontrolled mode.

```js
export const Uncontrolled = {
	args: {
		...Default.args,
	},
};
```

In DevTools, see the the accessibility panel for the main combobox button. The button description will not update after changing the selected options.

## Proposed solution

In uncontrolled mode, the outer component (`CustomSelectControl`) doesn't get re-rendered on selection change, so the `currentValue` is not updated accordingly:

https://github.com/WordPress/gutenberg/blob/f430cd73ff8eaf58aa9782d50891e8eb50a9ee54/packages/components/src/custom-select-control/index.tsx#L208

We might want to subscribe to `_CustomSelect` store updates via `onChange` so this part can be re-rendered on store state changes.

### PR DESCRIPTION
**Pull request by yogeshbhutkar**
Fixes: #67759 

## What?  
This PR fixes a bug where the Button component's description fails to update correctly when uncontrolled.

## How?  
The implementation replaces `store.getState()` with `Ariakit.useStoreState(store)` to accurately retrieve the current value, ensuring the description updates as expected.

## Testing Instructions
1. Add the below code snippet to the storybook.
```js
export const Uncontrolled = {
	args: {
		...Default.args,
	},
};
```
2. In DevTools, checkout out the accessibility panel for the main combobox button. The button description will now update after changing the selected options.

### Before:

https://github.com/user-attachments/assets/89980a97-6762-4efd-bb74-22d46fd1dcf4

### After:

Custom Select Control After

### CODE REVIEW

**Comment by yogeshbhutkar** [comment]
This PR also works well with the previously raised issue #67721 and takes a different approach as mentioned in #67733.


https://github.com/user-attachments/assets/172fe0a0-a140-4ce0-81cc-2c79fd3b0f7d

File: packages/components/src/custom-select-control/index.tsx [hunk 1]
```diff
@@ -149,16 +151,14 @@ function CustomSelectControl< T extends CustomSelectOption >(
 			);
 		} );
 
-	const { value: currentValue } = store.getState();
-
 	const renderSelectedValueHint = () => {
 		const selectedOptionHint = options
 			?.map( applyOptionDeprecations )
 			?.find( ( { name } ) => store.getState().value === name )?.hint;
```
Comment (Mamaduka) [inline packages/components/src/custom-select-control/index.tsx]: I think changes on this line from #67733 also need to be reverted.

Comment (yogeshbhutkar) [reply packages/components/src/custom-select-control/index.tsx]: @Mamaduka, in the new PR, these have already been reverted to use currentValue instead of getState().value again. Of course, the way currentValue is determined is slightly different. Does this align with what we were aiming for?

Comment (Mamaduka) [reply packages/components/src/custom-select-control/index.tsx]: Which new PR? Here, I only see the current value reverted on line 161.

Comment (yogeshbhutkar) [reply packages/components/src/custom-select-control/index.tsx]: Got it, I think you're referring to the change that happened on line 157. I'll add a commit to fix it. It would just become:

```js
const renderSelectedValueHint = () => {
		const selectedOptionHint = options
			?.map( applyOptionDeprecations )
			?.find( ( { name } ) => currentValue === name )?.hint;
```

Apologies for missing it 🙇‍♂️

Comment (Mamaduka) [reply packages/components/src/custom-select-control/index.tsx]: Corret! Thanks, @yogeshbhutkar!

File: packages/components/src/custom-select-control/index.tsx [hunk 2]
```diff
@@ -149,16 +149,16 @@ function CustomSelectControl< T extends CustomSelectOption >(
 			);
 		} );
 
-	const { value: currentValue } = store.getState();
+	const { value: currentValue } = Ariakit.useStoreState( store );
```
Comment (Mamaduka) [inline packages/components/src/custom-select-control/index.tsx]: You can also access a specific value from the state by passing a second argument. However, I'm not sure if it makes any difference performance-wise.

```js
const currentValue = Ariakit.useStoreState( store, 'value' );
```

Comment (yogeshbhutkar) [reply packages/components/src/custom-select-control/index.tsx]: Thanks for the suggestion @Mamaduka. It looks more readable for sure. I've incorporated it in the latest commit 🙌.

**Review by Mamaduka — APPROVED** [review]
Thanks, @yogeshbhutkar! I can confirm that this fixes the issue.

Let's add a changelog entry. I think this is a good merge.

**Review by tyxla — APPROVED** [review]
Confirming this looks good and works well. Happy to ship once we have a CHANGELOG entry as @Mamaduka suggested.

**Review by mirka — APPROVED** [review]
Oh great, nice clean fix! Thank you 🙌

**Comment by yogeshbhutkar** [comment]
Added changelog entry.

CC: @Mamaduka

File: packages/components/CHANGELOG.md [hunk 3]
```diff
@@ -46,6 +46,7 @@
 
 -   `ResizableBox`: Make drag handles focusable ([#67305](https://github.com/WordPress/gutenberg/pull/67305)).
 -   `CustomSelectControl`: Update correctly when `showSelectedHint` is enabled ([#67733](https://github.com/WordPress/gutenberg/pull/67733)).
+-   `CustomSelectControl`: use `useStoreState` to get `currentValue` for optimistic updates ([#67815](https://github.com/WordPress/gutenberg/pull/67815))
```
Comment (Mamaduka) [inline packages/components/CHANGELOG.md]:
```suggestion
-   `CustomSelectControl`: Use `useStoreState` to get `currentValue` and avoid stale values ([#67815](https://github.com/WordPress/gutenberg/pull/67815)).
```

A minor suggestion. The optimistic updates refer to a different pattern, especially after the React 19 release.

Comment (yogeshbhutkar) [reply packages/components/CHANGELOG.md]: Thanks for the suggestion @Mamaduka. Fixed in the latest commit 🚀.
