### PR TITLE
Show proper message on trash of an entity

### LINKED ISSUE #19144: Wrong notification message shown when an entity is moved to trash
**Describe the bug**

When moving a post to trash from the Document settings pane in Gutenberg:

Screen Shot 2019-12-13 at 18 36 15

(Image above is a screen shot of the Gutenberg editor with focus set to the "Move to trash button")

VoiceOver announces after successful completion of operation that the post has been reverted to draft:

Screen Shot 2019-12-13 at 18 37 16

(Image above is a screenshot of the Posts section in wp-admin, where the recently deleted post appears to have been moved to trash but the VoiceOver caption is announcing that the post has been reverted to draft)

I expect the announcement to be "Post moved to trash" instead. Also, the just-deleted post does not appear as a draft, as announced, but instead appears in the Trash, as expected.

**To reproduce**
1. Open a published post.
2. On the Document settings pane, click on "Move to trash"
3. Post is correctly moved to trash, but VoiceOver announces that it has been reverted to draft instead.

**Desktop**
 - OS: macOS 10.15.1
 - Browser: Safari 13.0.3

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/19144

When moving a post to `trash` from the Document settings pane in Gutenberg, shows a wrong message (`reverted to draft`).
This is because we don't handle the `trash` case. 

Since there is not a label for a post_type `trash` action, I have added that manually with a message: `{Singular name of entity's labels} trashed`.
The singular name is dynamic per post type.

Reference: https://developer.wordpress.org/reference/functions/get_post_type_labels/

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by enriquesanchez — APPROVED** [review]
This works as expected, thanks @ntsekouras!



Seeing the discussion happening on #19144, I agree that perhaps the best solution is to have the notice on the posts page announce the trash action, but I think this is a welcoming change while that gets sorted out.

File: packages/editor/src/store/utils/notice-builder.js [hunk 1]
```diff
@@ -31,11 +31,18 @@ export function getNotificationArgumentsForSaveSuccess( data ) {
...
 
 	let noticeMessage;
 	let shouldShowLink = get( postType, [ 'viewable' ], false );
 
-	if ( ! isPublished && ! willPublish ) {
+	// Since there is not a label for a post_type `trash` action,
+	// we add the message manually.
+	// Reference: https://developer.wordpress.org/reference/functions/get_post_type_labels/
+	if ( isTrashed ) {
+		noticeMessage = `${ postType.labels.singular_name } trashed.`;
```
Comment (afercia) [inline packages/editor/src/store/utils/notice-builder.js:43]: The `trashed` part of this string is not translatable.
Also, we should avoid translatable strings made by concatenating a variable part with other text as this is not well translatbale in some languages. This should use a _new_ post label to be introduced in core. Thus, it requires a patch for core. Note that in WordPress 5.0 new post labels were introduced for use in Gutenberg so this wouldn't be unprecedented.

**Comment by afercia** [comment]
I think this has been merged a bit too quickly 🙂 
The message string is not translatable, see comment https://github.com/WordPress/gutenberg/pull/25563/files#r494082027

File: packages/editor/src/store/utils/notice-builder.js (hunk 1 above)
Comment (ntsekouras) [reply packages/editor/src/store/utils/notice-builder.js:43]: I opened a ticket for this: https://core.trac.wordpress.org/ticket/51387

**Comment by ntsekouras** [comment]
@afercia you're right about the translation. I opened a ticket in core as commented above(https://core.trac.wordpress.org/ticket/51387) and created a revert PR here: https://github.com/WordPress/gutenberg/pull/25604

File: packages/editor/src/store/utils/notice-builder.js (hunk 1 above)
Comment (swissspidy) [reply packages/editor/src/store/utils/notice-builder.js:43]: @ntsekouras a core ticket should not be a blocker for this.

Compat shims can be added to Gutenberg.

And even when that's not possible, we should not push strings that are not translatable.
