### PR TITLE
fix/[#21440] Copy/cut input values copying entire block

### LINKED ISSUE #21440: Copy/cut input values copying entire block/removing block
I'm getting some weirdness in WP 5.4 with and without the Gutenberg plugin when it comes to copying/pasting/cutting values.

The following video shows the process/how to reproduce. It was taken using Chrome on Windows.

https://www.screencast.com/t/5I006Nyxhd

I used Twenty-Twenty with no plugins other than Gutenberg activated and used the paragraph block as an example. I originally noticed the problem in my own blocks that I'm building, but it seems to happen with core blocks as well.

It seems to only affect number inputs.

- Copying the value copies the entire block
- Pasting doesn't seem to work (obviously), as it's trying to paste the entire block into the value
- Cutting the value seems to delete the block entirely

It seems like Gutenberg is mistaking the selection for the block itself, even though the input is selected.

### PR DESCRIPTION
**Pull request by kirilzh**
## Description
In `block-editor/src/components/copy-handler/index.js` this check does not pass 
```js
// Let native copy behaviour take over in input fields.
if ( ! hasMultiSelection() && documentHasSelection() ) {
	return;
}
```
because `documentHasSelection()` returns false. Going deeper we see there’s a check if a text fields has a selection 
```js
function documentHasSelection() {
	if ( isTextField( document.activeElement ) ) {
		return true;
	}

	const selection = window.getSelection();
	const range = selection.rangeCount ? selection.getRangeAt( 0 ) : null;

	return range && ! range.collapsed;
}
```
I then stumbled upon [this](https://stackoverflow.com/questions/21177489/selectionstart-selectionend-on-input-type-number-no-longer-allowed-in-chrome). Hence I added a function checking only `<input type="number" />`.

## How has this been tested?
In both Chrome and FF on MacOS. 

## Types of changes
Bug fix (non-breaking change) which fixes #21440 .

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.

### CODE REVIEW

File: packages/dom/src/dom.js [hunk 1]
```diff
@@ -480,6 +494,10 @@ export function documentHasSelection() {
 		return true;
 	}
 
+	if ( isNumberInput( document.activeElement ) ) {
```
Comment (youknowriad) [inline packages/dom/src/dom.js:497]: Should we add this inside isTextField or should it be a separate function? Or more precisely, do we consider a "number" input as a text field? I might think yes but curious what others think?

**Review by youknowriad — COMMENTED** [review]
Code looks good to me, I'll do some testing

File: packages/dom/src/dom.js (hunk 1 above)
Comment (kirilzh) [reply packages/dom/src/dom.js:497]: Initially I extended `isTextField` but later I asked myself the same question and to me it makes more sense to have them separated. I don't consider numbers as text per se. Also curious what others think : )

**Review by youknowriad — APPROVED** [review]
This seems to work very well :) Thanks for the fix.

**Comment by tomusborne** [comment]
This has fixed the copying part of the issue, but I'm still seeing an issue once the value is pasted back into the field. The pasted value replaces the block itself, instead of being added to the field.
