### PR TITLE
Navigation Editor: show a warning when trying to save unsupported blocks

### LINKED ISSUE #35045: Navigation editor: Fail loudly when attempting to save unsupported blocks
Navigation editor only processes a subset of blocks in the editor, silently omitting anything that's not supported:

https://github.com/WordPress/gutenberg/blob/fa5728771df7cdc86369f7157d6aa763649937a7/packages/edit-navigation/src/store/actions.js#L207-L209

It would be useful to log a warning and make any problems there apparent.

### PR DESCRIPTION
**Pull request by anton-vlasenko**
## Description
Navigation editor only processes a subset of blocks in the editor, silently omitting anything that's not supported.
It would be useful to log a warning and make any problems there apparent.
Fixes https://github.com/WordPress/gutenberg/issues/35045.

## How has this been tested?

1. Create or edit an existing menu in the Navigation Editor (you have to enable it in the settings).
2. Make sure that the menu contains some unsupported blocks.
I had trouble reproducing this, so I've just replaced
https://github.com/WordPress/gutenberg/blob/92bf5e63a7a008fd4088f310a30691f4d990de85/packages/edit-navigation/src/store/utils.js#L80
with
```javascript
[  ].includes(
```
to emulate unsupported blocks.
3. Open the menu in the Navigation editor. Try to save it.
4. You should see a similar message in your browser console:
Screenshot 2021-10-27 at 18 45 01

## Types of changes

New feature

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/edit-navigation/src/store/actions.js [hunk 1]
```diff
@@ -204,7 +205,22 @@ const batchInsertPlaceholderMenuItems = ( navigationBlock ) => async ( {
 const batchUpdateMenuItems = ( navigationBlock, menuId ) => async ( {
 	registry,
 } ) => {
-	const updatedMenuItems = blocksTreeToAnnotatedList( navigationBlock )
+	const allMenuItems = blocksTreeToAnnotatedList( navigationBlock );
+	const unsupportedMenuItems = allMenuItems
+		.filter( ( { block } ) => ! isBlockSupportedInNav( block ) )
+		.map( ( { block } ) => block.name );
+	if ( unsupportedMenuItems.length ) {
+		logWarning(
```
Comment (gziolo) [inline packages/edit-navigation/src/store/actions.js]: This function exists for development purposes, to show warnings in the development mode related to code.

Comment (anton-vlasenko) [reply packages/edit-navigation/src/store/actions.js]: @gziolo Ah, I see. It's not going to work in the browser because `process.env.NODE_ENV` won't be defined.
Should we simply use `console.warn` instead?
Do you have a better alternative?

Comment (gziolo) [reply packages/edit-navigation/src/store/actions.js]: Yes, `console.warn` should work. We might have usage of it also in other places.

Comment (anton-vlasenko) [reply packages/edit-navigation/src/store/actions.js]: @gziolo  Fixed in https://github.com/WordPress/gutenberg/pull/35993/commits/70ed0edb3f43c2bb1a57e884ddc33b0b128e8132
Could you please approve this PR if you think it's OK?

**Review by draganescu — APPROVED** [review]
LGTM 👏🏻

**Comment by anton-vlasenko** [comment]
Thank you for the review, @draganescu !
