### PR TITLE
Editor: Fix custom sources backwards compatibility for the pages post type.

### LINKED ISSUE #17767: Blocks with post meta attributes stopped working after update 6.6.0
**Describe the bug**
The 6.6.0 update seems to cause an issue where the editor breaks when I add blocks that use post meta as source for one of their attributes.

I've created a small [plugin to test this](https://github.com/razwan/gutenberg-test-meta-attributes) and got the same result:
```
Cannot read property 'my_block_meta' of undefined
```
The error comes from the **withMetaAttributeSource** filter [here](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/hooks/custom-sources-backwards-compatibility.js#L26)

**To reproduce**
1. Register a block type that has an attribute with post meta as source
2. Try to add that block type to the content
3. The editor encounters an unexpected error.

**Trace**
```
index.js?ver=2e2b78de4a8a9e8f1ec023c58f617ba6:17 Uncaught TypeError: Cannot read property 'my_block_meta' of undefined
    at index.js?ver=2e2b78de4a8a9e8f1ec023c58f617ba6:17
    at Array.reduce (<anonymous>)
    at index.js?ver=2e2b78de4a8a9e8f1ec023c58f617ba6:17
    at mountMemo (react-dom.8b3dda97.js:15807)
    at Object.useMemo (react-dom.8b3dda97.js:16029)
    at useMemo (react.eef5f5a3.js:1680)
    at index.js?ver=2e2b78de4a8a9e8f1ec023c58f617ba6:17
    at WithMetaAttributeSource((Component)) (index.js?ver=2e2b78de4a8a9e8f1ec023c58f617ba6:17)
    at renderWithHooks (react-dom.8b3dda97.js:15246)
    at mountIndeterminateComponent (react-dom.8b3dda97.js:17480)
(anonymous) @ index.js?ver=2e2b78de4a8a9e8f1ec023c58f617ba6:17
(anonymous) @ index.js?ver=2e2b78de4a8a9e8f1ec023c58f617ba6:17
mountMemo @ react-dom.8b3dda97.js:15807
useMemo @ react-dom.8b3dda97.js:16029
useMemo @ react.eef5f5a3.js:1680
(anonymous) @ index.js?ver=2e2b78de4a8a9e8f1ec023c58f617ba6:17
WithMetaAttributeSource((Component)) @ index.js?ver=2e2b78de4a8a9e8f1ec023c58f617ba6:17
renderWithHooks @ react-dom.8b3dda97.js:15246
mountIndeterminateComponent @ react-dom.8b3dda97.js:17480
beginWork$1 @ react-dom.8b3dda97.js:18624
callCallback @ react-dom.8b3dda97.js:341
invokeGuardedCallbackDev @ react-dom.8b3dda97.js:391
invokeGuardedCallback @ react-dom.8b3dda97.js:448
beginWork$$1 @ react-dom.8b3dda97.js:23355
performUnitOfWork @ react-dom.8b3dda97.js:22349
workLoopSync @ react-dom.8b3dda97.js:22323
renderRoot @ react-dom.8b3dda97.js:22016
runRootCallback @ react-dom.8b3dda97.js:21692
(anonymous) @ react-dom.8b3dda97.js:11491
unstable_runWithPriority @ react.eef5f5a3.js:2820
runWithPriority$2 @ react-dom.8b3dda97.js:11443
flushSyncCallbackQueueImpl @ react-dom.8b3dda97.js:11487
flushSyncCallbackQueue @ react-dom.8b3dda97.js:11476
discreteUpdates$1 @ react-dom.8b3dda97.js:21815
discreteUpdates @ react-dom.8b3dda97.js:2357
dispatchDiscreteEvent @ react-dom.8b3dda97.js:6104
react-dom.8b3dda97.js:19952 The above error occurred in the <WithMetaAttributeSource((Component))> component:
    in WithMetaAttributeSource((Component)) (created by WithFilters(Component))
    in WithFilters(Component) (created by IfCondition(WithFilters(Component)))
    in IfCondition(WithFilters(Component)) (created by WithDispatch(IfCondition(WithFilters(Component))))
    in WithDispatch(IfCondition(WithFilters(Component)))
    in Unknown (created by WithSelect(WithDispatch(IfCondition(WithFilters(Component)))))
    in WithSelect(WithDispatch(IfCondition(WithFilters(Component))))
    in Unknown (created by Pure(WithViewportMatch(WithSelect(WithDispatch(IfCondition(WithFilters(Component)))))))
    in Pure(WithViewportMatch(WithSelect(WithDispatch(IfCondition(WithFilters(Component)))))) (created by t)
    in Br (created by t)
    in div (created by t)
    in t (created by WithDispatch(t))
    in WithDispatch(t)
    in Unknown (created by WithSelect(WithDispatch(t)))
    in WithSelect(WithDispatch(t))
    in Unknown (created by yt)
    in div
    in Unknown (created by WithDispatch(Component))
    in WithDispatch(Component) (created by yt)
    in div (created by t)
    in t (created by WithSafeTimeout(t))
    in WithSafeTimeout(t) (created by WithDispatch(WithSafeTimeout(t)))
    in WithDispatch(WithSafeTimeout(t))
    in Unknown (created by WithSelect(WithDispatch(WithSafeTimeout(t))))
    in WithSelect(WithDispatch(WithSafeTimeout(t))) (created by yt)
    in div (created by t)
    in div (created by t)
    in t (created by WithDispatch(t))
    in WithDispatch(t)
    in Unknown (created by WithSelect(WithDispatch(t)))
    in WithSelect(WithDispatch(t)) (created by yt)
    in div (created by t)
    in t
    in Unknown (created by WithSelect(t))
    in WithSelect(t) (created by yt)
    in div (created by t)
    in t (created by WithDispatch(t))
    in WithDispatch(t)
    in Unknown (created by WithSelect(WithDispatch(t)))
    in WithSelect(WithDispatch(t)) (created by yt)
    in yt
    in div
    in div (created by t)
    in t
    in Unknown
    in Unknown (created by WithViewportMatch(Component))
    in WithViewportMatch(Component) (created by NavigateRegions(WithViewportMatch(Component)))
    in div (created by NavigateRegions(WithViewportMatch(Component)))
    in NavigateRegions(WithViewportMatch(Component)) (created by WithDispatch(NavigateRegions(WithViewportMatch(Component))))
    in WithDispatch(NavigateRegions(WithViewportMatch(Component)))
    in Unknown (created by WithSelect(WithDispatch(NavigateRegions(WithViewportMatch(Component)))))
    in WithSelect(WithDispatch(NavigateRegions(WithViewportMatch(Component)))) (created by t)
    in t (created by t)
    in t (created by WithDispatch(t))
    in WithDispatch(t)
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(WithDispatch(t)) (created by t)
    in ht (created by t)
    in t (created by WithDispatch(t))
    in WithDispatch(t)
    in Unknown (created by WithSelect(WithDispatch(t)))
    in WithSelect(WithDispatch(t))
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(WithSelect(WithDispatch(t))) (created by t)
    in div (created by t)
    in t (created by t)
    in t (created by t)
    in StrictMode (created by t)
    in t (created by WithDispatch(t))
    in WithDispatch(t)
    in Unknown (created by WithSelect(WithDispatch(t)))
    in WithSelect(WithDispatch(t))

React will try to recreate this component tree from scratch using the error boundary you provided, t.
```

**Additional context**
Gutenberg 6.6.0

### PR DESCRIPTION
**Pull request by epiqueras**
Fixes #17767

## Description

This PR fixes the custom sources backwards compatibility filter's hook to take into account post types other than `post`.

## How has this been tested?

It was verified that adding blocks with meta sources to pages no longer crashes the editor and an e2e test was added to avoid regressions.

## Types of Changes

*Bug Fix:* Meta sources no longer crash the editor if the edited post is not of post type `post`.

## Checklist:

- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/editor/src/hooks/custom-sources-backwards-compatibility.js [hunk 1]
```diff
@@ -15,7 +16,9 @@ function useMetaAttributeSource( name, _attributes, _setAttributes ) {
 
 	if ( Object.values( attributeTypes ).some( ( type ) => type.source === 'meta' ) ) {
 		// eslint-disable-next-line react-hooks/rules-of-hooks
-		const [ meta, setMeta ] = useEntityProp( 'postType', 'post', 'meta' );
+		const { type } = useSelect( ( select ) => select( 'core/editor' ).getCurrentPost(), [] );
```
Comment (youknowriad) [inline packages/editor/src/hooks/custom-sources-backwards-compatibility.js]: `getCurrentPostType` selector maybe?

Comment (epiqueras) [reply packages/editor/src/hooks/custom-sources-backwards-compatibility.js]: Sure, we'll need to change it later, but it's better for performance now.

**Review by youknowriad — APPROVED** [review]
This makes sense to me. I didn't test but I trust the e2e test here.

**Comment by luuptekman** [comment]
Came into this issue via https://github.com/WordPress/gutenberg/issues/17767.

I'm still experiencing this issue with custom post type (in my case I have created a new post type `experiences`). When adding a block in custom post edit screen this happens `Cannot read property '_my_meta_id' of undefined`.

When adding the block in posts/pages, everything is ok. This is the block plugin I'm using to reproduce the issue with WP 5.3.2. https://github.com/luuptek/bokun-wp

**Comment by epiqueras** [comment]
>When adding a block in custom post edit screen this happens Cannot read property '_my_meta_id' of undefined.
>When adding the block in posts/pages, everything is ok.

Sounds like the core-data store is not bootstrapped correctly. Is `getEntityRecord` being called for the relevant post before loading the editor?

**Comment by luuptekman** [comment]
How can I check that?

**Comment by epiqueras** [comment]
Where is the code for the custom post edit screen?

**Comment by luuptekman** [comment]
> Where is the code for the custom post edit screen?

Gutenberg related stuff in here: https://github.com/luuptek/bokun-wp/blob/master/src/bokun-product/bokun-product.js ==> `_bokun_wp_bokun_id ` is what it's complaining about...

Meta data is registered via `register_post_meta` in main plugin file: https://github.com/luuptek/bokun-wp/blob/master/bokun-wp.php

Custom post is added in theme , example via this:
```
function book_setup_post_type() {
	$args = array(
		'public'    => true,
		'label'     => __( 'Books', 'textdomain' ),
		'menu_icon' => 'dashicons-book',
		'show_in_rest' => true,
	);
	register_post_type( 'book', $args );
}
add_action( 'init', 'book_setup_post_type' );
```

**Comment by epiqueras** [comment]
>When adding a block in custom post edit screen this happens Cannot read property '_my_meta_id' of undefined.

Where is that custom post edit screen?

**Comment by luuptekman** [comment]
> > When adding a block in custom post edit screen this happens Cannot read property '_my_meta_id' of undefined.
> 
> Where is that custom post edit screen?

Depends on custom post definition...in example above it would be in `Books => Add new`

**Comment by epiqueras** [comment]
Sounds like your post type is missing `custom-fields` support.

https://developer.wordpress.org/reference/functions/register_post_type/

https://developer.wordpress.org/reference/functions/add_post_type_support/

**Comment by luuptekman** [comment]
Big thanks for pointing that! So custom post need to support `custom-fields` ==> will work then 👍

**Comment by epiqueras** [comment]
I'm glad I could help! 😄
