### PR TITLE
Block Comment: make blockCommentId as part of the metadata

### LINKED ISSUE #71784: Block Commenting: Move `blockCommentId` attribute into `metadata`
## What problem does this address?

If you add a block comment to the blocks that have `ServerSideRender` component to render block contents, a 400 error occurs:

Image

The API request returns the following error:

```
{
  "code": "rest_invalid_param",
  "message": "Invalid parameter(s): attributes",
  "data": {
    "status": 400,
    "params": {
      "attributes": "blockCommentId is not a valid property of Object."
    },
    "details": {
      "attributes": {
        "code": "rest_additional_properties_forbidden",
        "message": "blockCommentId is not a valid property of Object.",
        "data": null
      }
    }
  }
}
```
 
This happens because the `blockCommentId` attribute is not defined server-side. The `metadata` and `lock` attributes, on the other hand, are defined as global attributes, so there's no problem.

https://github.com/t-hamano/wordpress-develop/blob/7289643a4d6a901a04f13b0359c95a1df5af63d3/src/wp-includes/class-wp-block-type.php#L282-L285

## What is your proposed solution?

~To solve this problem, I can think of two approaches.~

**Update:** Moving `blockCommentId` inside `metadata` seems like the best approach. See: https://github.com/WordPress/gutenberg/pull/71847#issuecomment-3326379875

### Add `blockCommentId` as Global Attributes

Along with the core patch that extends the global attributes, we will need to use the following filter in the Gutenberg project:

```php
function gutenberg_add_block_comments_support( $args ) {
	if ( empty( $args['attributes'] ) ) {
		$args['attributes'] = array();
	}
	$args['attributes']['blockCommentId'] = array(
		'type' => 'number',
	);
	return $args;
}
add_filter( 'register_block_type_args', 'gutenberg_add_block_comments_support' );
```

## Add `blockComment` block support

I think this is a more ideal approach: define the attribute schema server-side, based on this block support.

### PR DESCRIPTION
**Pull request by t-hamano**
Closes #71784

## What?

Moves `attributes.blockCommentId` into `attributes.metadata,blockCommentId`

## Why?

The `blockCommentId` attribute is not registered on the server-side. As a result, when commenting on the Block that uses the `ServerSideRender` component, the API request returns a 400 error.

We need to make the Block Commenting feature work on dynamic blocks.

## How?

- First, I suggested adding support for the `blockComment` block and registering attributes server-side, but [since `metadata` attribute is allowed globally](https://github.com/t-hamano/wordpress-develop/blob/7289643a4d6a901a04f13b0359c95a1df5af63d3/src/wp-includes/class-wp-block-type.php#L282-L285), using the existing `metadata` is a more ideal approach.
- Rename `blockCommentId` to `commentId`. See [this discussion](https://github.com/WordPress/gutenberg/issues/71784#issuecomment-3333780085) for more details.

## Testing Instructions

- Confirm that you can comment on dynamic blocks.
- Add both a custom name and a comment to a block. Ensure that when you delete one, the other doesn't get deleted.
- Ensure custom names and comments are preserved when transforming blocks.

> [!NOTE]
> I have encountered cases where metadata is lost during block conversion, which needs to be addressed separately. See https://github.com/WordPress/gutenberg/issues/71922

> [!NOTE]
> I plan to update my [Block Commenting Data Generator plugin](https://github.com/t-hamano/block-commenting-data-generator) to work with the new definition after this PR has been merged.

### CODE REVIEW

File: packages/editor/src/components/collab-sidebar/index.js [hunk 1]
```diff
@@ -86,8 +78,11 @@ function CollabSidebarContent( {
 
 			// If it's a main comment, update the block attributes with the comment id.
 			if ( ! parent && savedRecord?.id ) {
-				updateBlockAttributes( getSelectedBlockClientId(), {
-					blockCommentId: savedRecord.id,
+				updateBlockAttributes( selectedBlockClientId, {
+					metadata: {
+						...metadata,
+						commentId: savedRecord.id,
+					},
```
Comment (Mamaduka) [inline packages/editor/src/components/collab-sidebar/index.js]: We can access all the required data within the callback, rather than using the store sub.

File: packages/editor/src/components/collab-sidebar/index.js [hunk 2]
```diff
@@ -173,7 +171,7 @@ function CollabSidebarContent( {
 				setShowCommentBoard={ setShowCommentBoard }
 			/>
 			<Comments
-				key={ getSelectedBlockClientId() }
+				key={ selectedBlockClientId }
```
Comment (Mamaduka) [inline packages/editor/src/components/collab-sidebar/index.js]: This is a temporary hack; we should remove it. I think we can do it after refactoring to [the new state logic](https://github.com/WordPress/gutenberg/pull/71898#pullrequestreview-3268062319).

File: packages/editor/src/components/collab-sidebar/comments.js [hunk 3]
```diff
@@ -51,17 +51,15 @@ export function Comments( {
...
-	const { blockCommentId } = useSelect( ( select ) => {
+	const commentId = useSelect( ( select ) => {
 		const { getBlockAttributes, getSelectedBlockClientId } =
 			select( blockEditorStore );
 		const clientId = getSelectedBlockClientId();
-		return {
-			blockCommentId: clientId
-				? getBlockAttributes( clientId )?.blockCommentId
-				: null,
-		};
```
Comment (Mamaduka) [inline packages/editor/src/components/collab-sidebar/comments.js:62]: Perhaps in this case and the updates below, we should continue to refer to the value as `blockCommentId`. Just to differentiate that the value is coming from the block and not the `threads` themselves. What do you think?

File: packages/editor/src/components/collab-sidebar/index.js (hunk 2 above)
Comment (Mamaduka) [reply packages/editor/src/components/collab-sidebar/index.js]: Actually, let’s just remove this hack. It creates false sense that selection/focus is working as expected.

It better to document and fix it separately. We might have to skip a e2e test.

File: packages/editor/src/components/collab-sidebar/comments.js (hunk 3 above)
Comment (t-hamano) [reply packages/editor/src/components/collab-sidebar/comments.js:62]: That's certainly true. updated in 5d27902107ee5c6568e431a05cc2722d64fc7355

File: packages/editor/src/components/collab-sidebar/index.js (hunk 2 above)
Comment (t-hamano) [reply packages/editor/src/components/collab-sidebar/index.js]: Should we remove it in this PR?

File: packages/editor/src/components/collab-sidebar/index.js (hunk 1 above)
Comment (t-hamano) [reply packages/editor/src/components/collab-sidebar/index.js]: Can you explain in more detail?

File: packages/editor/src/components/collab-sidebar/index.js (hunk 2 above)
Comment (Mamaduka) [reply packages/editor/src/components/collab-sidebar/index.js]: I’ll trust your judgment here.

File: packages/editor/src/components/collab-sidebar/index.js (hunk 1 above)
Comment (Mamaduka) [reply packages/editor/src/components/collab-sidebar/index.js]: We can use a static selector getter and then call `getSelectedBlockClientId()` and `getBlockAttributes()` inside the callback. The values are only used during the event.

See: https://developer.wordpress.org/news/2024/03/how-to-work-effectively-with-the-useselect-hook/#but-call-them-outside-when-you-re-in-an-event-handler

Comment (Mamaduka) [reply packages/editor/src/components/collab-sidebar/index.js]: It’s not a blocker, we can refactor later.

**Review by Mamaduka — APPROVED** [review]

**Comment by adamsilverstein** [comment]
Nice work, I will give this a test to confirm.

**Comment by adamsilverstein** [comment]
This works well in my testing 🚀 !

File: packages/editor/src/components/collab-sidebar/index.js (hunk 2 above)
Comment (t-hamano) [reply packages/editor/src/components/collab-sidebar/index.js]: Removed in 90f58bd4bbb12b8bedba349226b07aa81c7398a5

As far as I've tested, all E2E tests pass and there should be no regressions.

Comment (t-hamano) [reply packages/editor/src/components/collab-sidebar/index.js]: Update: Removing the key prop seems to cause our E2E tests to fail, so let's restore it for now.

File: packages/editor/src/components/collab-sidebar/index.js (hunk 1 above)
Comment (t-hamano) [reply packages/editor/src/components/collab-sidebar/index.js]: Updated in 73d58d480cb806952b9f8f92a231e6e486417a2f

I hope I understand your intentions 😅

Comment (Mamaduka) [reply packages/editor/src/components/collab-sidebar/index.js]: It’s not a blocker. Let’s merge this and we can refactor later, while working to fix the states.

**Review by adamsilverstein — APPROVED** [review]
Neat!

**Comment by t-hamano** [comment]
Thanks for the review! Let's merge this PR for now.

**Comment by t-hamano** [comment]
P.S. I have updated my https://github.com/t-hamano/block-commenting-data-generator plugin so that handle new `metadata.commentId` correctly.
