### PR TITLE
Editor: Fix issue where createBlock in block template caused list view collapse

### LINKED ISSUE #56662: List View: Navigation list view unexpectedly collapses when rearranging items
### Description

Originally raised in `#core-editor` channel in the WordPress Slack: https://wordpress.slack.com/archives/C02QB2JS7/p1701292630488409

When rearranging blocks within the Navigation list views (either in the main list view, or in the block inspector right-hand list view), the list view will collapse after dropping the block into a new position.

### Step-by-step reproduction instructions

1. In the site editor, open up a navigation item to edit it directly
2. With the List View open in the left hand sidebar, go to rearrange items
3. Notice that the list view collapses unexpectedly
4. With the Navigation block selected, use the list view in the block inspector (right hand side)
5. Do the same, and notice that the list view collapses unexpectedly

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/14988353/18bef316-916c-41d2-ab0f-8b81043070c7

### Environment info

- WP 6.4.1
- Gutenberg `trunk`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by andrewserong**
## What?

Fixes https://github.com/WordPress/gutenberg/issues/56662, related to https://github.com/WordPress/gutenberg/issues/56000

This fixes an issue when editing Navigation entities in the site editor, or when editing content within the post-only mode — in both cases, rearranging blocks will cause the list view to collapse on `trunk`.

## Why?

Within `useBlockEditorProps`, `createBlock` was called too frequently (every time a change was made in `postBlocks`), resulting in a new `clientId` for the wrapping Navigation block, or the wrapping Post Content block in the Navigation editor or the post-only mode, respectively.

## How?

By updating the `useMemo` to remove `postBlocks` from the dependency array, and moving the fallback to `postBlocks` to outside of the `useMemo`, we ensure that `createBlock` is only called when switching a mode, template, or post. This means that the `clientId` of the Navigation or Post Content blocks should now be stable when editing within the Navigation editor in the site editor, or in post only mode.

## Testing Instructions

1. On trunk, go to edit a Navigation entity in the Site Editor (Select a menu from the Navigation menu on the left hand side in browse mode).
2. Within the Navigation editor, with the list view open, go to rearrange items within the Navigation menu. On trunk, the list view will immediately collapse when finishing dragging. The same will happen if you use the list view in the right-hand block inspector.
3. With this PR applied, the list views should not collapse when rearranging items.
4. Similarly, test editing a page within the site editor, using the post only mode (by toggling off the template preview for an individual page). On trunk, if you rearrange blocks within the page, the list view will collapse. With this PR applied, they should not collapse.
5. Double-check that otherwise editing templates and post content is otherwise unaffected.

### Before (Navigation)

https://github.com/WordPress/gutenberg/assets/14988353/18bef316-916c-41d2-ab0f-8b81043070c7

### After (Navigation)

https://github.com/WordPress/gutenberg/assets/14988353/0eab713a-92bd-4610-8f7d-62e47a4a2c95

### Before (editing Page content)

Notice how rearranging paragraph blocks within Content unexpectedly collapses the Content block:

https://github.com/WordPress/gutenberg/assets/14988353/bfc3a3d4-f29f-4d70-9e7e-e960afc574f8

### After (editing Page content)

https://github.com/WordPress/gutenberg/assets/14988353/f6eb0989-9fc6-419a-b53c-757f8ad816da

### CODE REVIEW

File: packages/editor/src/components/provider/index.js [hunk 1]
```diff
@@ -156,15 +156,13 @@ function useBlockEditorProps( post, template, mode ) {
...
-	}, [
-		templateBlocks,
-		postBlocks,
-		rootLevelPost,
-		post.type,
-		post.id,
-		mode,
-	] );
+		return null;
+	}, [ templateBlocks, rootLevelPost, post.type, post.id, mode ] );
```
Comment (ramonjd) [inline packages/editor/src/components/provider/index.js]: Just checking, `postBlocks` was kind of redundant anyway given that `post.type` and `post.id` were used to fetch it?

**Review by ramonjd — APPROVED** [review]
This is working well for me.

### Before



https://github.com/WordPress/gutenberg/assets/6458278/16ac9f86-ba44-42df-933a-297589d8c85c

### After

https://github.com/WordPress/gutenberg/assets/6458278/7ec3644d-e85b-4b7f-b187-638d4cbf478d



Also, page editing, template preview toggling and template editing work for pages in the Site Editor as I'd expect 👍🏻

File: packages/editor/src/components/provider/index.js (hunk 1 above)
Comment (andrewserong) [reply packages/editor/src/components/provider/index.js]: Pretty much — `postBlocks` was only in the dependency array because it was returned as a fallback value, so it wasn't being used for anything. By moving it out of the dependency array, it shouldn't really change anything other than reducing the number of times that the `useMemo` gets called unnecessarily.

**Comment by andrewserong** [comment]
Thanks for the quick review @ramonjd! I'll leave this PR open overnight in case @youknowriad had other ideas or concerns about this fix, but if not, I'll merge this in tomorrow 🙂

**Comment by youknowriad** [comment]
Yes, I noticed this, I had included a fix in my post editor refactor PR that is slightly different than this one. Mind if I push it here?

**Comment by youknowriad** [comment]
It's a little bit different to account for more overrides in the future potentially and adds a comment.

I'd love an approval for this #56542 too, it included this fix

**Comment by youknowriad** [comment]
Feel free to revert my commit if you don't like it :)

**Comment by youknowriad** [comment]
Merging this PR, as I'm opening a follow-up based on it.

**Comment by andrewserong** [comment]
Nice, that's a bit clearer @youknowriad, and helps ensure each template is isolated to only those changes that mean it should be regenerated. Thanks for landing this! 👍

I think we now have an unnecessary comment below the `useMemo`, but that'll be easy to tidy up in a follow-up 🙂

**Comment by vcanales** [comment]
Backported to 17.2 RC
