### PR TITLE
Core Data: Fix incorrect pagination for non-paginated entities

### LINKED ISSUE #15413: getPostTypes() limited to 10
**Describe the bug**

I am developing Gutenberg Plugins I found a problem.  if there are more than 10 post types, it only shows me the first 10.

It's not related with "show_in_rest"

Probably it's related with: _context.abrupt but i'm not sure

**To reproduce**
Use this
`edit: withSelect((select) => {
        const {getPostTypes} = select('core');
	return {
		types: getPostTypes()
	};
}`

**Expected behavior**
Return all post types

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes #15413.

PR fixes a bug where records returned by the REST API for entities that don't support pagination are limited to the default `per_page: 10`. Consumers and Core code had to use `per_page: -1` "hack" to fix this behavior.

## Why?
Non-paginated entities like `postType` and `taxonomy` return all records in a single response, but `getEntityRecords` was slicing results to the default page size. This normalizes the query to `per_page: -1` for non-paginated entities in both the resolver and selectors, ensuring all records are returned.

## Todo

- [ ] Update selector calls in code base as needed and remove `per_page: -1` "hack". 

## Testing Instructions
1. Open a post or page.
2. Try selecting records for a non-paginated entity that has more than 10 entries.
3. The Icons entity is probably a good choice here.
4. It should return all the records.

```js
wp.data.select( 'core' ).getEntityRecords( 'root', 'icon' );
```

### Testing Instructions for Keyboard
Same.

## AI usage

I had the idea, used Claude for validation, improving comments and rubber ducking (is this still a thing?).

### CODE REVIEW

File: packages/core-data/src/resolvers.js [hunk 1]
```diff
@@ -467,6 +467,16 @@ export const getEntityRecords =
...
+
+				// Non-paginated entities return all data. Normalize the
+				// query so the reducer and selectors treat it correctly.
+				// Skip if consumer explicitly set per_page (backward compat).
+				if (
+					! entityConfig.supportsPagination &&
+					query.per_page === undefined
+				) {
+					query = { ...query, per_page: -1 };
+				}
```
Comment (youknowriad) [inline packages/core-data/src/resolvers.js]: We should have done this a long time ago that said, it can be seen as a breaking change.

I know at some point @ellatrix wanted to use this loophole/bug to "auto-migrate" templates to the new "activate template" mode. I wonder if it's still the case or not.

Comment (Mamaduka) [reply packages/core-data/src/resolvers.js]: I tried to limit the breaking change effects. If perPage is defined it will be respected when slicing the records.

I don’t have info about auto-migration plan, but using similar bugs as loopholes doesn’t seem reliable.

Comment (ellatrix) [reply packages/core-data/src/resolvers.js]: Why don't we check `supportsPagination` before slicing? Tbh, I've always thought `per_page: -1` is wrong and we should use that property to define "unbound" requests. Even if you use `per_page: -1` on pages that support pagination, it can be valuable to be able to set by how many pages it batches requests. `per_page: -1` suggests it grabs all items in a single request, and that's simply not true.

Comment (Mamaduka) [reply packages/core-data/src/resolvers.js]: I think this is the closest we can do before slicing, right before action is dispatched to the reducer.

> Tbh, I've always thought per_page: -1 is wrong and we should use that property to define "unbound" requests.

I think this was just copied from `WP_Query`, but I agree that, depending on the data, it might take more than a couple of requests. We could try to improve this, but I don't think it's in the scope of this PR.

**Comment by Mamaduka** [comment]
I've rebased and updated the Icons block query; if anyone wants to do manual testing. We can handle the remaining cases before merging.

File: packages/core-data/src/resolvers.js (hunk 1 above)
Comment (jsnajdr) [reply packages/core-data/src/resolvers.js]: This is how I understand the problem, correct me if I'm wrong:
- the `/wp/v2/icons` endpoint returns an array of 80+ icons, with no pagination: ignores the `per_page` and `page` query args, there are no `x-wp-total` and `x-wp-totalpages` headers in the response.
- the `getEntityRecords( 'root', 'icon' )` selector will, however, return only first 10 items, because `getQueriedItems` and `getQueryParts` assigns default values to `page` and `per_page`. Although the REST endpoint doesn't support pagination, it's implemented client-side, inside the `getEntityRecords` selector.
- this PR partially disables this "client-side pagination" for entities that don't have `config.supportsPagination === true`. It will work only when you specify `page` and `per_page` explicitly. If you don't specify them, `getEntityRecords( 'root', 'icon' )` will return the full list by default.

> it can be seen as a breaking change.

The breaking change is that the client-side pagination is no longer the default? I.e., that the `getEntityRecords( 'root', 'icon' )` doesn't return just the first 10 items, but all 80+? Or is there also something else?

Implementation-wise, I don't like the fact that `getQueriedItems` _always_ looks at `page` and `per_page` and respects them, and that we need `getNonPaginatedQuery` to create a "fake" paginated query, adding an artificial `per_page=-1` query arg. I would prefer the following, if possible:
- `getQueryParts` doesn't add any default values for `page` and `per_page`. They are relevant only when `supportsPagination` is true.
- it's the `getQueriedItems` selector that reads the `supportsPagination` flag and does the pagination accordingly, not `getNonPaginatedQuery`.

Comment (Mamaduka) [reply packages/core-data/src/resolvers.js]: > The breaking change is that the client-side pagination is no longer the default? I.e., that the getEntityRecords( 'root', 'icon' ) doesn't return just the first 10 items, but all 80+? Or is there also something else?

That could be considered a breaking change, but consumers were relying on the existing bug. The whole data set was received but then discarded.

@jsnajdr, I've pushed changes based on your feedback, plus rebased the branch after the `offset` fixes.

File: packages/core-data/src/queried-data/selectors.js [hunk 2]
```diff
@@ -26,12 +26,15 @@ const queriedItemsCacheByState = new WeakMap();
...
+ * @param {Object}  state                      State object.
+ * @param {?Object} query                      Optional query.
+ * @param {?Object} options                    Optional pagination options.
+ * @param {boolean} options.supportsPagination Whether the entity supports pagination. Default false.
  *
  * @return {?Array} Query items.
  */
-function getQueriedItemsUncached( state, query ) {
+function getQueriedItemsUncached( state, query, options = {} ) {
+	const { supportsPagination = false } = options;
```
Comment (Mamaduka) [inline packages/core-data/src/queried-data/selectors.js]: Based on 849901f49b1f1e9152e11cc107ac378a7a2e38fe and to limit breaking changes, we might want to configure entities `supportsPagination` explicitly. Currently, entities don't support pagination by default.

Plan:
1. Update core entity configs and explicitly define `supportsPagination`.
2. If `supportsPagination` is undefined, selectors should work as before - slice the data on the client.

**Update:** This seems like the right direction. Pushed changes with the last commit.

File: packages/core-data/src/queried-data/selectors.js [hunk 3]
```diff
@@ -118,27 +120,31 @@ function getQueriedItemsUncached( state, query ) {
...
  *
  * @return {?Array} Query items.
  */
-export const getQueriedItems = createSelector( ( state, query = {} ) => {
-	let queriedItemsCache = queriedItemsCacheByState.get( state );
-	if ( queriedItemsCache ) {
-		const queriedItems = queriedItemsCache.get( query );
-		if ( queriedItems !== undefined ) {
-			return queriedItems;
+export const getQueriedItems = createSelector(
```
Comment (jsnajdr) [inline packages/core-data/src/queried-data/selectors.js:130]: Any idea why we have `createSelector` here when there is no dependents array to memoize by? The caching is implemented manually inside the selector.

File: packages/core-data/src/queried-data/selectors.js [hunk 4]
```diff
@@ -118,27 +120,31 @@ function getQueriedItemsUncached( state, query ) {
...
-	} else {
-		queriedItemsCache = new EquivalentKeyMap();
-		queriedItemsCacheByState.set( state, queriedItemsCache );
-	}
 
-	const items = getQueriedItemsUncached( state, query );
-	queriedItemsCache.set( query, items );
-	return items;
-} );
+		const items = getQueriedItemsUncached( state, query, options );
```
Comment (jsnajdr) [inline packages/core-data/src/queried-data/selectors.js:143]: The `options` object doesn't need to be part of the cache key, is that right? It's always a constant for a given `kind`/`name` entity type combination.

Comment (Mamaduka) [reply packages/core-data/src/queried-data/selectors.js:143]: That's correct.

File: packages/core-data/src/queried-data/selectors.js (hunk 3 above)
Comment (Mamaduka) [reply packages/core-data/src/queried-data/selectors.js:130]: This is all I can find https://github.com/WordPress/gutenberg/pull/6395#discussion_r185322524.

Comment (jsnajdr) [reply packages/core-data/src/queried-data/selectors.js:130]: Interesting, it's @aduth's work 😄 @aduth do you happen to remember why you used `createSelector` without any dependency array 8 years ago, back in May 2018? 😉 

I believe that all the memoization is done already by the two level cache, first level for `state`, second level for `query`.

Comment (aduth) [reply packages/core-data/src/queried-data/selectors.js:130]: Hm, I don't remember exactly. It does seem intentional and was documented in the function's DocBlock ("caches result by both per state (by reference) and per query (by deep equality)". It does practically have dependents on the _whole_ state object. But in practice you're right that the inner caching logic is pretty effective on its own. I think the one key difference is that `createSelector` memoization is going to be a lot faster than `EquivalentKeyMap` lookup if the `query` object is a stable reference between calls.

Comment (Mamaduka) [reply packages/core-data/src/queried-data/selectors.js:130]: > I think the one key difference is that createSelector memoization is going to be a lot faster than EquivalentKeyMap lookup if the query object is a stable reference between calls.

I think most consumers pass inline query objects into `useSelect`, which makes it harder to ensure stable references when you're dealing with dynamic query values (`search`, `order`, `include`, etc.). So actual benefit of this would be hard to measure.

**Review by jsnajdr — APPROVED** [review]
I have some doubts about the `createSelector` call, but it's preexisting and not a blocker. I'd like to have a closer look sometime later. Let's ship this 🚢

**Comment by Mamaduka** [comment]
Thanks for the feedback and reviews, everyone! I added the "Needs Dev Note" label. Let's mention this behavior change in Misc dev notes.

**Comment by t-hamano** [comment]
The Icon block seems to show only 10 icons. Is there anything we need to address regarding this?

image

**Comment by Mamaduka** [comment]
> The Icon block seems to show only 10 icons. Is there anything we need to address regarding this?

Hm, that's odd. I remember testing this with the Icons block. I'll try to have a proper look later today or tomorrow morning.

**Update:** I think regression is an accidental combo of this PR and #76808. Luckily, none of this code has shipped.

Thanks for catching the bug, @t-hamano!

**Comment by jsnajdr** [comment]
> The Icon block seems to show only 10 icons.

I can reproduce, working on a fix.

**Comment by jsnajdr** [comment]
Fixing in #77262.

File: packages/core-data/src/queried-data/selectors.js (hunk 3 above)
Comment (Mamaduka) [reply packages/core-data/src/queried-data/selectors.js:130]: Here's a follow-up #77483.
