### PR TITLE
Bug/24286 create block error

### LINKED ISSUE #24286: createBlock fires error if name doesn't match a registered block type.
**Describe the bug**
When calling `createBlock()` with a block name that is not registered, a console error is fired due to  `blockType` being undefined when accessing the `.attributes` property [here](https://github.com/WordPress/gutenberg/blob/89e34315314d7800c988301f06ae3d226f31bf44/packages/blocks/src/api/factory.js#L52)

**To reproduce**
1. Create a new Post or Page
2. In the console panel call `wp.blocks.createBlock('not/registered)`
4. See error in console.

**Expected behavior**
I would expect this function to fail with a console warning of `Block type {name} is not registered.`

**Screenshots**
create-block-error

**Editor version (please complete the following information):**
- WordPress version: 5.4.2
- No plugin installed.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.6
 - Browser Chrome
 - Version 84.0.4147.105

### PR DESCRIPTION
**Pull request by ryanwelcher**
closes #24286

## Description
This PR implements the proposed solution indicated in #24286 

## How has this been tested?
Running `wp.blocks.createBlock('not/registered') in the console.

## Screenshots 
create-block-warning

## Types of changes
This introduces a warning() call and an early return if the blockType is not registered

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/blocks/src/api/factory.js [hunk 1]
```diff
@@ -40,12 +41,17 @@ import { normalizeBlockType } from './utils';
...
- * @return {Object} Block object.
+ * @return {(Object|boolean)} Block object or false if the block name is not a registered block.
  */
 export function createBlock( name, attributes = {}, innerBlocks = [] ) {
 	// Get the type definition associated with a registered block.
 	const blockType = getBlockType( name );
 
+	if ( undefined === blockType ) {
+		warning( `Block type '${ name }' is not registered.` );
+		return false;
```
Comment (youknowriad) [inline packages/blocks/src/api/factory.js:52]: Making this non-blocking changes the expectation from someone calling this function. 

We do things like that in general in Gutenberg `compact( configs.map( config => createBlock( config.name, config.attributes, config.innerBlocks ) )`

With the current implementation, this will hide bugs and just move them down the road. IMO, we should throw an example here instead of calling `warning`.

Comment (ryanwelcher) [reply packages/blocks/src/api/factory.js]: @youknowriad thanks for the review here! I have updated the PR to throw an exception.

File: packages/blocks/src/api/factory.js [hunk 2]
```diff
@@ -46,6 +46,10 @@ export function createBlock( name, attributes = {}, innerBlocks = [] ) {
 	// Get the type definition associated with a registered block.
 	const blockType = getBlockType( name );
 
+	if ( undefined === blockType ) {
```
Comment (youknowriad) [inline packages/blocks/src/api/factory.js:49]: Not important but yoda conditions are not a guideline in JavaScript because we enforce strict equality.

**Review by youknowriad — APPROVED** [review]
Thanks for your PR. The error message is way clearer this way.
