### PR TITLE
Real-time collaboration: Improve collaboration within the same rich text

### LINKED ISSUE #74563: Real-time collaboration: Multiple users cannot input within the same Y.Text
### Description

When two users have selections with the same `Y.Text` (e.g. `core/paragraph` text), other users' editors do not update selection position when it has changed.

Here are some examples of that behavior:

### 1. Stationary cursor "moves backward"

Image

Above, my user has a cursor set at the beginning of "second". When another user types earlier in the paragraph, my selection stays in the same location. Because the text is being added before my selection position, my cursor "travels backwards" within the paragraph.

### 2. Selection range moves

Similarly, if a range is selected, this also stays stationary during text changes:

Image

This is the same problem as above. Because the `selectionStart`/`selectionEnd` properties don't adjust to the changes in the underlying text, the selection can move backwords within the logical text.

### 3. Unexpected selection changes in rich text with line breaks

This problem persists when there are line breaks in a shared rich text object:

Image

This could definitely be a problem when a text section looks separated in a layout and appears to be a different text area but is actually only composed of line breaks.

### Step-by-step reproduction instructions

1. Open a real-time collaboration post.
2. Write a line of text and leave your selection at the end of it.
3. Have another user join the post and start typing before your cursor position.
4. See your cursor position stay in the same place, but the logical position of the cursor changes.

## How do we fix it?

We currently store user positions as [`Y.RelativePosition`](https://docs.yjs.dev/api/relative-positions)s, which gives us the flexibility to recalculate and correctly draw cursor positions when the underlying content changes. However, in order for the local Gutenberg editor to know about those, we need to dispatch selection change events and actually move the user's cursor to a new place.

We tried a basic prototype within the RTC plugin here: https://github.com/Automattic/vip-real-time-collaboration/commit/fec829deb55b32bdab7e3f29ed2b1e43ed70306e. In short, when a user focuses a rich text field we start observing changes on the underlying `Y.Text`. When these changes result in [absolute position changes](https://github.com/Automattic/vip-real-time-collaboration/blob/fec829deb55b32bdab7e3f29ed2b1e43ed70306e/src/hooks/use-reposition-cursor.ts#L95-L110), we [dispatch a `selectionChange` to the new location](https://github.com/Automattic/vip-real-time-collaboration/blob/fec829deb55b32bdab7e3f29ed2b1e43ed70306e/src/hooks/use-reposition-cursor.ts#L122-L127).

This should work in theory, but two users quickly typing within the same text area still caused occasional positional slippage. This is likely due to a race condition from incoming CRDT events and selection change events. In order to fix this I think we'll need a similar solution with guard rails to ensure that we're timing things correctly. It might be easier to manage this lifecycle directly within Gutenberg instead of relying on store signals like above.

### PR DESCRIPTION
**Pull request by alecgeatches**
## What?

Allow two users to type at the same time within a block.

simultaneous-typing

Fixes https://github.com/WordPress/gutenberg/issues/74563, which demonstrates the behavior before this PR:

> When two users have selections with the same `Y.Text` (e.g. `core/paragraph` text), other users' editors do not update selection position when it has changed.
> 
> Here are some examples of that behavior:
> 
> ### 1. Stationary cursor "moves backward"
> 
> 
> Image
>
> Above, my user has a cursor set at the beginning of "second". When another user types earlierin the paragraph, my selection stays in the same location. Because the text is being added before my selection position, my cursor "travels backwards" within the paragraph.
> 
> ### 2. Selection range moves
> 
> Similarly, if a range is selected, this also stays stationary during text changes:
> 
> Image
>
> This is the same problem as above. Because the `selectionStart`/`selectionEnd` properties don't adjust to the changes in the underlying text, the selection can move backwords within the logical text.
> 
> ### 3. Unexpected selection changes in rich text with line breaks
> 
> This problem persists when there are line breaks in a shared rich text object:
> 
> Image

This PR addresses these issues and allows fluid selection updates with CRDT changes.

## Why?

Users expect editing within the same block to work, and cursors to adjust to real-time changes in the same text.

## How?

The cursor drift issue happens because the editor stores cursor positions as absolute offsets (e.g. "index `5` in the paragraph"), but when a remote peer inserts or deletes text before that position, the offset becomes stale. The cursor stays at index 5 even though the text it was anchored to has shifted.

The fix utilizes existing stored relative position data and updates selection to match when text changes occur.

When a user interacts with the editor, their cursor position is saved to a selection history as a `Y.RelativePosition`. These relative positions automatically account for text mutations and the relative position converted back to absolute will return the corrected offset. The main change is in `getPostChangesFromCRDTDoc()`, which extracts changes from the CRDT document when remote updates arrive. After extracting content changes, it now also recalculates the local user's cursor by converting their stored relative position back to an absolute offset, and includes this recalculated selection in the returned changes.

Because the recalculated selection is bundled into the same `EDIT_ENTITY_RECORD` dispatch as the content changes, both arrive in the store atomically.

## Limitations

This strategy of recalculating absolute position doesn't work in two scenarios:

### Limitation 1: Current block is split before the cursor

https://github.com/user-attachments/assets/8acf11d9-2ebf-47a6-b95c-20159ecbc8e1

User 1 has their cursor near the front of the block, and user 2 is typing later in the block. When user 1 hits enter and the block breaks into two, user 2's cursor stays within the same block. Ideally, the cursor should stay with the same logical text and move into the second paragraph.

This is tricky to solve. When the block is broken, a new `Y.Text` object is created for the new block's content which is now a separate data structure from the block the user was typing in. The anchor text is gone, so the absolute position just resolves to the end of the first block.

### Limitation 2: Current block is merged into another block

https://github.com/user-attachments/assets/3ca6fba1-74fc-4183-a45f-d50140925137

User 1 has their cursor at the beginning of the block and user 2 is typing later in the block. When user 1 hits backspace and the block is merged into the previous block, user 2's cursor disappears. Ideally, the cursor should stay in the same logical text and move into the previous block with the rest of the content.

Similar to above, this is difficult because the second block's structure is destroyed when the block is merged and the Y.Text in the prior block is changed. Making this work would require understanding where text content has been merged into other blocks and recalculating position.

---

Both of these are real issues, but will require more intensive tree-watching, changing our `mergeCrdtBlocks` logic to be more intelligent about block additions/deletions, or listening for specific Gutenberg signals that a block split or merge has occurred. In any case, I think this PR represents a huge improvement over [current behavior](https://github.com/WordPress/gutenberg/issues/74563) and can be merged without addressing these cases yet.

## Testing Instructions

1. Check out this PR. Ensure real-time collaboration is enabled via: WordPress Admin -> Settings -> Writing, and check the "Enable real-time collaboration" checkbox. Click the "Save Changes" button.
2. Open a post in two separate tabs. Ideally, this can be done on a shared site so that another real human can test at the same time.
3. Within the same block, have one user at the beginning of the block start typing.
4. Have a second user start typing later in the block.
5. Verify that both user's text appears in the block, and that the cursor position moves intuitively with the content.

### CODE REVIEW

File: packages/core-data/src/utils/crdt-selection.ts [hunk 1]
```diff
@@ -205,3 +218,48 @@ export function restoreSelection(
...
+
+	const { start, end } = selectionHistory[ 0 ];
+
+	// Block-level selections have no offset that can shift.
+	if (
+		start.type === YSelectionType.BlockSelection ||
+		end.type === YSelectionType.BlockSelection
+	) {
+		return null;
+	}
```
Comment (maxschmeling) [inline packages/core-data/src/utils/crdt-selection.ts:247]: I thought this might be an issue, but you can't select half of a paragraph and then a block after that. Extending you selection down to a block at the end causes the entire paragraph to be selected. So it seems you can't half `end.type` be `BlockSelection` and `start.type` not be `BlockSelection`

**Review by maxschmeling — APPROVED** [review]

File: packages/core-data/src/utils/crdt-selection.ts (hunk 1 above)
Comment (alecgeatches) [reply packages/core-data/src/utils/crdt-selection.ts:247]: Block-level selections overall are funky, so thank you for checking.

**Review by chriszarate — APPROVED** [review]
