### PR TITLE
Only load Gutenberg Polyfill in Gutenberg pages

### LINKED ISSUE #6847: Classic Editor Visual Mode Broken by Gutenberg
**Describe the bug**
WordPress 4.9.6
Gutenberg 2.9.1

The Classic Visual Editor is broken ; displays only a white screen. Text view okay.

**To Reproduce**
1. Disable all plugins except Gutenberg.
2. Activate a Twenty-Something theme (I used Twenty Sixteen).
3. Open Dashboard : Pages, Select some page, and click Classic Editor
4. The Visual Editor show a white screen. Nothing editable.
5. Strange side effect: If you switch to Text View, content there. Switch back to Visual, see blank screen. Now switch BACK to Text View, and all the line breaks are gone - just run together HTML.

**Expected behavior**
Duh - the classic editor needs to work. Note that WP 4.9.6 updated TinyMCE.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome, Firefox
 - Version: latest

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

### PR DESCRIPTION
**Pull request by youknowriad**
This PR fixes #6847 by avoiding to load the Gutenberg scripts in the classic editor. 
This avoids any TinyMCE conflict.

I also added an e2e test to avoid this kind of regressions in the future.

### CODE REVIEW

**Comment by gziolo** [comment]
It seems like a legit fix, however, I'd prefer to have someone else double check PHP logic.

File: lib/client-assets.php [hunk 1]
```diff
@@ -1093,9 +1093,25 @@ function gutenberg_editor_scripts_and_styles( $hook ) {
...
+		return;
+	}
+
+	if ( isset( $_GET['classic-editor'] ) ) {
+		return;
+	}
+
+	if ( ! gutenberg_can_edit_post( $post ) ) {
+		return;
+	}
```
Comment (youknowriad) [inline lib/client-assets.php]: It might be handy to define a `is_editor_page` function to check whether we're loading a Gutenberg page or not

**Review by ellatrix — APPROVED** [review]
Fixes the issue for me. Would be nice to either share the logic with `gutenberg_init` or explain why different checks are needed. Would also be nice to explain why this is needed: "Ensure the editor module is loaded before third party plugins."

**Comment by youknowriad** [comment]
> "Ensure the editor module is loaded before third party plugins."

This is needed before the previous APIs defined in `wp-blocks` are loaded in `wp-editor` and `wp-editor` is not added as a dependency to these third party plugins. We have a warning showing on the console to help plugin authors migrate but during that period we need to load `wp-editor` before everything else to avoid breakage.

**Comment by youknowriad** [comment]
>  `gutenberg_init` or explain why different checks are needed

The checks are not different. This has an extra check to ensure we're on the editor page `get_current_screen`. The `gutenberg_init` is only run in the `replace_editor` hook or in `post.php`

**Comment by youknowriad** [comment]
Merging as this fixed the issue and it's a temporary polyfill anyway.
