### PR TITLE
Block Editor: fix duplicate clientIds when dragging patterns

### LINKED ISSUE #35120: Dragging the same pattern twice will assign the same clientId
### Description

I noticed that dragging patterns multiple times will insert blocks with duplicate clientIds. 

It looks like the transfer data is set with these blocks, and clientIds are never updated even when a drop is successful.

https://github.com/WordPress/gutenberg/blob/efaa86b900f8707a1ae8c11ebf591fde808f24aa/packages/block-editor/src/components/block-patterns-list/index.js#L23-L26

https://user-images.githubusercontent.com/1270189/134714213-9e7a6271-e6f7-4968-81b7-db0e68da347f.mp4

### Step-by-step reproduction instructions

1. In the post-editor try adding a pattern via drag
2. Add the same pattern again
3. Check the clientIds assigned using `wp.data.select('core/block-editor').getBlocks()`
Expected: Each block has a new clientId
Actual: Dropped items have the same clientId

### Environment info

Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by gwwar**
Fixes https://github.com/WordPress/gutenberg/issues/35120 where dragging patterns multiple times will insert blocks with duplicate clientIds. This isn't a problem for onClick since we explicitly clone the blocks in that case.

If we don't like the code approach here, one alternative is always cloning for the 'inserter' case since we never intend to add duplicate clientIds. (It happens to work for the inserter drag currently since it re-renders that often).

### Step-by-step reproduction instructions

1. In the post-editor try adding a pattern via drag
2. Add the same pattern again
3. Check the clientIds assigned using `wp.data.select('core/block-editor').getBlocks()`

Before:

https://user-images.githubusercontent.com/1270189/134714213-9e7a6271-e6f7-4968-81b7-db0e68da347f.mp4

After:

https://user-images.githubusercontent.com/1270189/134714213-9e7a6271-e6f7-4968-81b7-db0e68da347f.mp4

### CODE REVIEW

**Review by fabiankaegy — COMMENTED** [review]
I checked this out locally and confirmed the issue and the fix. Dragging patterns into the editor now works as expected giving each inserted block a unique clientId. 

The code also looks good to me but I will leave the approval to a code owner more familiar with the functionality :)

File: packages/block-editor/src/components/inserter-draggable-blocks/index.js [hunk 1]
```diff
@@ -2,15 +2,23 @@
...
  */
 import BlockDraggableChip from '../block-draggable/draggable-chip';
 
-const InserterDraggableBlocks = ( { isEnabled, blocks, icon, children } ) => {
+const InserterDraggableBlocks = ( {
+	isEnabled,
+	blocks,
+	icon,
+	children,
+	clone = false,
```
Comment (youknowriad) [inline packages/block-editor/src/components/inserter-draggable-blocks/index.js]: Do we really need the flag? Should we just always clone?

Comment (gwwar) [reply packages/block-editor/src/components/inserter-draggable-blocks/index.js]: Updated in db8cfe0 👍  we don't need a flag if we didn't have a use case for it.

**Review by youknowriad — APPROVED** [review]
That makes sense to me, Thanks for the fix. 👍

**Comment by gwwar** [comment]
Thanks for the reviews @youknowriad @fabiankaegy !
