### PR TITLE
Embed: Restore paragraph with URL when undoing paste-to-embed transform

### LINKED ISSUE #11245: Pasting links creates empty embed block when embed blocks is not allowed
**Describe the bug**
I'm using 'allowed_block_types' to remove all embed blocks. When I paste a link from for example vimeo an empty embed block is still created

**To Reproduce**
1. don't allow any embed blocks
2. paste vimeo link in empty paragraph block

**Expected behavior**
I expect a text link to be pasted.

**Screenshots**
embedissue

**Desktop (please complete the following information):**
 - chrome

**Additional context**
GB 4.1

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes https://github.com/WordPress/gutenberg/issues/11245.
Requires #77546. Rebased, all tests are passing now.
Somewhat related #21789.

PR makes it easier to paste and retain links into empty paragraph blocks. See: https://github.com/WordPress/gutenberg/issues/15102.

Pasting a plain URL into an empty paragraph auto-replaces it with an embed block in a single `REPLACE_BLOCKS`, so `⌘Z` jumped straight back to the empty paragraph and the pasted URL was lost.

Before calling `onReplace` in the BLOCKS-mode paste path, insert the URL into the paragraph and mark that change as persistent. One undo now lands on "paragraph containing URL"; a second undo removes it.

## Testing Instructions
1. Open a post or page. 
2. Paste a YouTube (or any other embeddable) into a paragraph block.
3. Undo the change.
4. Confirm that it reverts to a paragraph with a URL in it.

### Testing Instructions for Keyboard
Same.

## Screenshots or screencast 

https://github.com/user-attachments/assets/6586a80b-c86b-436a-a070-98e0d4ff6a38

## Use of AI Tools

Claude as an assistant, for running the ideas.

### CODE REVIEW

**Comment by Mamaduka** [comment]
As a nice side-effect, this also fixes #11245. Now that paragraph with URL is persisted and then `onReplace` will bailout, since it can't insert an embed block.

cc @talldan

File: packages/block-editor/src/components/rich-text/event-listeners/paste-handler.js [hunk 1]
```diff
@@ -116,11 +118,23 @@ export default ( props ) => ( element ) => {
...
+		}
+
+		if ( ! content.length || ! onReplace || ! isEmpty( value ) ) {
+			return;
+		}
+
+		// Record an intermediate paragraph-with-URL state so a single undo
+		// after the URL → block transformation restores the pasted text.
+		if ( mode === 'BLOCKS' ) {
+			onChange( insert( value, create( { text: trimmedPlainText } ) ) );
```
Comment (tyxla) [inline packages/block-editor/src/components/rich-text/event-listeners/paste-handler.js]: In this scenario, if the restored text is a URL, should it be a linked URL? Right now it seems like it's just plain text.

Comment (tyxla) [inline packages/block-editor/src/components/rich-text/event-listeners/paste-handler.js]: The other thing that comes to mind is that we're losing the trimmed leading/trailing space. Should we keep it if we're reverting back to the original text?

Comment (Mamaduka) [reply packages/block-editor/src/components/rich-text/event-listeners/paste-handler.js]: Good question. I thought about this as just plain-text pasting, and let the user undo to that state. Behavior also differs when pasting URLs:

* When RichText contains a value, and a URL is pasted, it converts to a link.
* If you paste a paragraph containing a URL, it doesn't convert to a link.

We can easily swap behavior by using `pasteInline( html )` instead of a direct `onChange` call. @ellatrix, what do you think?

Comment (Mamaduka) [reply packages/block-editor/src/components/rich-text/event-listeners/paste-handler.js]: Good point. I'll handle this based outcome of https://github.com/WordPress/gutenberg/pull/77551#discussion_r3126612040

Comment (ellatrix) [reply packages/block-editor/src/components/rich-text/event-listeners/paste-handler.js]: Fine by me :)

Comment (Mamaduka) [reply packages/block-editor/src/components/rich-text/event-listeners/paste-handler.js]: Updated in [52e533f](https://github.com/WordPress/gutenberg/pull/77551/commits/52e533ff1a4fbbb9cbe0ede8e4267e46b2658193).

File: packages/block-editor/src/components/rich-text/event-listeners/paste-handler.js [hunk 2]
```diff
@@ -116,11 +118,23 @@ export default ( props ) => ( element ) => {
...
+		}
+
+		if ( ! content.length || ! onReplace || ! isEmpty( value ) ) {
+			return;
 		}
+
+		// Record an intermediate paragraph-with-URL state so a single undo
+		// after the URL → block transformation restores the pasted link.
+		if ( mode === 'BLOCKS' ) {
+			pasteInline( html );
```
Comment (tyxla) [inline packages/block-editor/src/components/rich-text/event-listeners/paste-handler.js:131]: Nice, that feels more intuitive and readable too 👍

**Review by tyxla — APPROVED** [review]
Tests well and code looks good. Thanks @Mamaduka!
