### PR TITLE
JS Error Tracking: Allow custom error reporting logic to be called in Error Boundaries via a WP action hook

### LINKED ISSUE #41094: API proposal: allow setting an Error Reporting callback function for Error Boundaries using an action
## What problem does this address?

Gutenberg provides one React Error Boundary that wraps block components (that I know of, there might be more). Some WordPress' apps that have Gutenberg activated might want to log these errors to some third-party Error Reporter like Sentry or Rollbar. Currently, there's no easy way to do that without modifying the Gutenberg source code.

## What is your proposed solution?

I was thinking we could leverage the WP's hooks extension system (the frontend JS version) and provide an action API that would be called from the error boundary (i.e from [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/editor/src/components/error-boundary/index.js#L38)). Something akin to what I did here, though using actions instead of filters. So somewhere in another plugin specific to the WordPress app that needs error reporting, we'd have a snippet like:

```
addAction(
	'gb.errorReporter',
	( e ) => { sentry.captureException( e )
	}
);
```

And in the Error Boundary component(s):

```
componentDidCatch(error, errorInfo) {
 doAction('gb.errorReporter', error); // I don't know if the name of the function is doAction, though, I'm not 100% sure about the hooks API in the frontend
}
```

What do you think?

### PR DESCRIPTION
**Pull request by fullofcaffeine**
## What?

Create an extension point in Gutenberg Error Boundaries that allows any client code (**browser** JS code running in the same context as the GB editor) to call custom logic as part of the boundaries' `componentDidCatch` methods, via a WP action hook. This logic can be set by any JS code running in the same context as the Gutenberg plugin that has access to import and use `addAction` from the `@wordpress/hooks` package.

## Why?

Error Boundaries provide a great way to customize the way rendering errors are caught and presented to the user, however, they end up swallowing the errors. This means that if you want to report it somewhere else, you're out of luck (as in, you need to modify the actual GB source code).

A typical real-world scenario is the use of tools like Sentry or Rollbar. By default, these tools setup a global error handler that will track and capture any uncaught error that ends up bubbling up to it. This is not the case for errors handled by React Error Boundaries, so they end up not being captured at all.

These tools usually provide their own Error Boundaries that will take care of capturing the errors, but Gutenberg already has many Error Boundaries with their custom logic, and we're not looking to replace them. We also don't want to couple the custom error reporting logic to the Error Boundary classes, either. We want them to be optional and set by any other JS code running in the same context (any other plugin/mu-plugin or enqueued js file).

## How?

For each React Error Boundary in Gutenberg, as part of the `componentDidCall` callback, we introduce a new `gb.reportErrorBoundaryException` action hook call (the name is provisory and up for discussion) and pass the `error` as its payload:

```js
class ErrorBoundary extends Component {
	componentDidCatch( error ) {
		this.setState( { error } );

		doAction( 'gb.reportErrorBoundaryException', error );
	}
}
```

Then, in any client JS code - which could be, say, the logic that sets up a tool like Sentry or Rollbar - we can then do something like:

```js
Sentry.init( {
	dsn: 'https://<dsn>',
} );

addAction( 'gb.reportErrorBoundaryException', 'mu-plugin/sentry-setup', ( error ) => {
	Sentry.reportError( error );
} );
```

## TODO
* [x] Discuss the approach :)
* [x] Add unit-tests
* [x] Add manual testing instructions
* [x] Should we worry about multiple `addAction` calls setting multiple callbacks? (I think not)
* [ ] Any security concerns?

#### 1) In your WP test instance, add a `wp-content/mu-plugins/test.php` file with the following contents:

```php
<?php
function testit() {
    wp_register_script('test', '');
    wp_enqueue_script('test' );
    wp_add_inline_script('test', "wp.hooks.addAction('gb.reportErrorBoundaryException', 'testing', (error) => {
       console.error('Opsie!', error);
    });");
}

add_action( 'admin_enqueue_scripts', 'testit', 99 );
```

#### 2) Force an error in a component that's wrapped by one of the available React Error Boundaries. Here's a diff for the `PostTitle` component, which will test the Error Boundary in `packages/editor/src/components/error-boundary`:

```diff
diff --git i/packages/editor/src/components/post-title/index.js w/packages/editor/src/components/post-title/index.js
index 6930819700..19bb9b9a72 100644
--- i/packages/editor/src/components/post-title/index.js
+++ w/packages/editor/src/components/post-title/index.js
@@ -208,6 +208,7 @@ function PostTitle( _, forwardedRef ) {
                                ref={ useMergeRefs( [ richTextRef, ref ] ) }
                                contentEditable
                                className={ className }
+                               foo={ bar }
                                aria-label={ decodedPlaceholder }
                                role="textbox"
                                aria-multiline="true"
```

**Apply this diff to your custom build of GB based on this branch. Make sure it's installed and active in your WP test instance.**

#### 3) Start a new post. You'll see the `The editor has encountered an unexpected error.` warning message, and if you open the console, you should see the `error` log prefixed with `Opsie`, meaning the custom action callback you setup in step 1) ran successfully.

Resolves: https://github.com/WordPress/gutenberg/issues/41094

### CODE REVIEW

File: packages/customize-widgets/src/components/error-boundary/index.js [hunk 1]
```diff
@@ -26,6 +27,8 @@ export default class ErrorBoundary extends Component {
 
 	componentDidCatch( error ) {
 		this.setState( { error } );
+
+		doAction( 'gb.reportErrorBoundaryException', error );
```
Comment (fullofcaffeine) [inline packages/customize-widgets/src/components/error-boundary/index.js]: To avoid repeating the identifier string everytime, we might abstract this into a function and extract it in a module somewhere. Something like:

```js
export function extendErrorBoundaryDidCatch( error ) {
    doAction( 'gb.extendErrorBoundaryDidCatch', error );
}
```

You may see I also renamed it to `extendErrorBoundaryDidCatch` in the snippet above. The reason is that the action callback is not limited to only reporting the error to an external target source _(though I assume this will be one of the main use cases)_, so semantically `extendErrorBoundaryDidCatch` is more accurate, I think.

Comment (fullofcaffeine) [reply packages/customize-widgets/src/components/error-boundary/index.js]: Another thing that we should discuss is whether this action will apply to all Error Boundaries, or if we need more granularity. I'd say it should apply to all boundaries, at least to begin with, and we can see if there's an actual need to provide finer control.

File: packages/edit-site/src/components/error-boundary/index.js [hunk 2]
```diff
@@ -20,6 +21,10 @@ export default class ErrorBoundary extends Component {
 		};
 	}
 
+	componentDidCatch( error ) {
```
Comment (gziolo) [inline packages/edit-site/src/components/error-boundary/index.js:24]: Did it work before? 😅 

Should it call `this.setState( { error } );` as all other error boundaries?

Actually, it looks like this is the now only component that doing it correctly by updating the state with `getDerivedStateFromError` and logging the error with `componentDidCatch` 🙃

https://reactjs.org/docs/error-boundaries.html#introducing-error-boundaries

> A class component becomes an error boundary if it defines either (or both) of the lifecycle methods [static getDerivedStateFromError()](https://reactjs.org/docs/react-component.html#static-getderivedstatefromerror) or [componentDidCatch()](https://reactjs.org/docs/react-component.html#componentdidcatch). Use static getDerivedStateFromError() to render a fallback UI after an error has been thrown. Use componentDidCatch() to log error information.

File: packages/customize-widgets/src/components/error-boundary/index.js (hunk 1 above)
Comment (gziolo) [reply packages/customize-widgets/src/components/error-boundary/index.js]: It looks like all error boundaries do the same thing in all places and save the error in the state so we could as well extract a general React component that implements `getDerivedStateFromError` and `componentDidCatch`. 

`componentDidCatch` can also show additional details:

> `info` - An object with a componentStack key containing [information about which component threw the error](https://reactjs.org/docs/error-boundaries.html#component-stack-traces).

This way we would have one place to rule them all. The only question would be where to put this component. It could be `@wordpress/compose` or `@wordpress/block-editor`. If we follow the pattern used with other hooks, the name of the action could be `compose.ErrorBoundary.error` or `compose.reportErrorBoundaryException`.

**Review by gziolo — COMMENTED** [review]
Nice start, I think we only need to figure out how to address the concern you raised in https://github.com/WordPress/gutenberg/pull/42024/files#r909107114. Otherwise, it's all about documenting this new functionality so people can learn about it. 

>  Any security concerns?

Great question. We will have to examine what exactly `componenDidCatch` exposes in `error` and `info` params.

> Should we worry about multiple `addAction` calls setting multiple callbacks? (I think not)

Do you mean that the same callback can be registered multiple times if the app doesn't guard it? Can you explain what case are you worried about?

Totally optional for the first version. The fun part is that `ErrorBoundry` is the only React component that isn't using the functional form which became unusual in the world of hooks. I would be curious to check if we could abstract it also in a way so we don't have to use the `extends` syntax. There is a good article that covers it:
https://blog.logrocket.com/react-error-handling-react-error-boundary/. I'm definitely NOT advocating for using a library presented in the article, but maybe we can borrow some pattern that abstracts all that in a nice fashion.

File: packages/edit-navigation/src/components/error-boundary/index.js [hunk 3]
```diff
@@ -19,6 +20,8 @@ class ErrorBoundary extends Component {
 
 	componentDidCatch( error ) {
 		this.setState( { error } );
+
+		doAction( 'gb.reportErrorBoundaryException', error );
```
Comment (Mamaduka) [inline packages/edit-navigation/src/components/error-boundary/index.js]: I think we can skip this one for now. Separate navigation editor screen development is on hold.

Comment (gziolo) [reply packages/edit-navigation/src/components/error-boundary/index.js]: If we have a general solution for all error boundaries then it should follow the same approach, but otherwise, we can skip as @Mamaduka correctly pointed out 👍🏻

File: packages/customize-widgets/src/components/error-boundary/index.js (hunk 1 above)
Comment (fullofcaffeine) [reply packages/customize-widgets/src/components/error-boundary/index.js]: > It looks like all error boundaries do the same thing in all places and save the error in the state so we could as well extract a general React component that implements getDerivedStateFromError and componentDidCatch.

That's a good idea! I also briefly thought about that, but didn't want to deviate too much from the main goal. Would it be better to do that as a follow-up (I can track it and make sure we don't forget)?

Comment (fullofcaffeine) [reply packages/customize-widgets/src/components/error-boundary/index.js]: What do you think if we start with abstracting in a function, like I suggested [here](https://github.com/WordPress/gutenberg/pull/42024/files#r909107114)? This would also make it easier to document it in a single place. I'm just not sure what would be a good place for such a helper function, I'll poke around, but I'm open to suggestions! After that, we can then follow up with your suggestion about DRYing the boundaries.

File: packages/edit-navigation/src/components/error-boundary/index.js (hunk 3 above)
Comment (fullofcaffeine) [reply packages/edit-navigation/src/components/error-boundary/index.js]: Cool, I'll revert the changes here then :)

File: packages/edit-site/src/components/error-boundary/index.js (hunk 2 above)
Comment (fullofcaffeine) [reply packages/edit-site/src/components/error-boundary/index.js:24]: > Did it work before? 

I actually don't know, but I can test it out!

**Comment by fullofcaffeine** [comment]
> Totally optional for the first version. The fun part is that ErrorBoundry is the only React component that isn't using the functional form which became unusual in the world of hooks. I would be curious to check if we could abstract it also in a way so we don't have to use the extends syntax. There is a good article that covers it:
https://blog.logrocket.com/react-error-handling-react-error-boundary/. I'm definitely NOT advocating for using a library presented in the article, but maybe we can borrow some pattern that abstracts all that in a nice fashion.

Ah, just saw this after I replied here. Thanks for the pointer. I'm definitely interested in working on that as a follow-up!

**Comment by fullofcaffeine** [comment]
> Do you mean that the same callback can be registered multiple times if the app doesn't guard it? Can you explain what case are you worried about?

Actually scratch that concern. It's just that I'm not too versed in the WP hooks engine, and thought we might not want to have multiple callbacks for the same action, but thinking again, that's actually a feature and a legit use-case.

**Comment by fullofcaffeine** [comment]
> Great question. We will have to examine what exactly componenDidCatch exposes in error and info params.

Any group of people in the community that could help us audit this?

File: packages/customize-widgets/src/components/error-boundary/index.js (hunk 1 above)
Comment (fullofcaffeine) [reply packages/customize-widgets/src/components/error-boundary/index.js]: Would `@wordpress/compose` be a good package to host this function for now? We could name it `compose.ErrorBoundary.error`, as you suggested.

File: packages/edit-site/src/components/error-boundary/index.js (hunk 2 above)
Comment (fullofcaffeine) [reply packages/edit-site/src/components/error-boundary/index.js:24]: > Did it work before?

Yep, just checked and it did work fine. 

> Actually, it looks like this is the now only component that doing it correctly by updating the state with getDerivedStateFromError and logging the error with componentDidCatch upside_down_face

Ah, nice. I think this could be a neat little improvement to work as a follow-up :)

File: packages/customize-widgets/src/components/error-boundary/index.js (hunk 1 above)
Comment (gziolo) [reply packages/customize-widgets/src/components/error-boundary/index.js]: I did some code checking. `@wordpress/compose` doesn't depend on `@wordpress/hooks` package and I think we should keep it general enough. I see that `@wordpress/block-editor` uses WP filters already so it's probably better to put this functionality there. We can take care of it later though. For now, we only need to settle on the name of the hook.

File: packages/edit-site/src/components/error-boundary/index.js (hunk 2 above)
Comment (gziolo) [reply packages/edit-site/src/components/error-boundary/index.js:24]: 👍🏻

**Comment by gziolo** [comment]
For the first iteration, we can proceed with the unified way of calling the action that has usage documented in the reference guide. The closest page to what we need here would be Editor Filters:

https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/filters/editor-filters.md

The name is a bit confusing when I think about it, because we are dealing with the action here. However, it's a structural mistake of calling hooks - filters in the Gutenberg documentation 😞 

As for the filter name, it looks like we aren't consistent with using the name of the package as the prefix so we can go with the general `editor.` one. How about the following:

```js
doAction( 'editor.ErrorBoundary.errorLogged', error, errorInfo );
```

File: packages/customize-widgets/src/components/test/error-boundary.js [hunk 4]
```diff
@@ -0,0 +1,38 @@
+/**
```
Comment (fullofcaffeine) [inline packages/customize-widgets/src/components/test/error-boundary.js:1]: The unit-tests are identical but simple enough, but there's one for each error boundary, which is a symptom of the existing unDRYness for Error Boundaries. We can turn them into a single test once we work on https://github.com/WordPress/gutenberg/pull/42024#discussion_r909341655.

Comment (fullofcaffeine) [reply packages/customize-widgets/src/components/test/error-boundary.js:1]: Since we plan to work on https://github.com/WordPress/gutenberg/pull/42024#discussion_r909341655 soon, I'll abstain from trying to DRY the unit-tests (by extracting the common logic into a shared function or something along those lines, for example).

**Review by gziolo — APPROVED** [review]
This is a great start. Thank you @fullofcaffeine for bringing this task to the finish line.

The new documentation page is disconnected from the Block Editor Handbook. I will take care of changes to the Reference Guides separately as it requires some discussion how to rephrase all sections for filters to cover also actions similar to what you can see in WordPress core.

**Comment by gziolo** [comment]
I opened a follow-up that tries to re-structure documentation to better surface the new error logging capability for extenders.

I also marked this PR with the `Needs Dev Note` label as we definitely want to bring more attention once it lands in WordPress core. It's going to be a game changer for people willing to debug why the editor crashes on production.

**Comment by bph** [comment]
I added `Developer Documentation` as reminder to double-check on this in time of 6.1
