### PR TITLE
FIX: Saving in Classic Editor shouldn't redirect to Gutenberg

### LINKED ISSUE #2707: Saving Gutenberg post in Classic Editor redirects to Gutenberg
Regression introduced in #1797

## Issue Overview

When saving a post in the current editor ("Classic Editor") which contains Gutenberg blocks, the user is unexpectedly redirected to the Gutenberg editor.

## Steps to Reproduce

1. (Prerequisite) Create and save a post in Gutenberg
2. Navigate to Posts
3. Hover the post created in Step 1, then click Classic Editor
4. Save the post

## Expected Behavior

The post is saved, and you are returned to the classic editor.

## Current Behavior

The post is saved, and you are redirected to the Gutenberg editor.

## Possible Solution

Expected that this is related to the `get_edit_post_link` added in #1797.

### PR DESCRIPTION
**Pull request by aaronjorbin**
`get_edit_post_link` is used in `post.php` to redirect when saving. See https://core.trac.wordpress.org/browser/trunk/src/wp-admin/post.php#L190

By checking to see if the referer is the classic editor, modification to the edit post link is preserved.

Introduced in #1797
Fixes #2707

### CODE REVIEW

File: lib/register.php [hunk 1]
```diff
@@ -221,6 +221,13 @@ function gutenberg_get_edit_post_url( $post_id ) {
  * @return string Edit post link.
  */
 function gutenberg_filter_edit_post_link( $url, $post_id, $context ) {
+	$sendback = wp_get_referer();
+	if ( $sendback && (
+		 strpos( $sendback, 'post.php' ) !== false ||
```
Comment (aduth) [inline lib/register.php]: Should we be more specific about these referrers, in case `post.php` occurs as a suffix for a file, or query parameter, or otherwise? Maybe:

```php
0 === strpos( parse_url( admin_url( 'post.php' ), PHP_URL_PATH ), $sendback )
```

File: lib/register.php [hunk 2]
```diff
@@ -221,6 +221,13 @@ function gutenberg_get_edit_post_url( $post_id ) {
...
+		 strpos( $sendback, 'post-new.php' ) !== false ) ) {
```
Comment (aduth) [inline lib/register.php]: Should the space indenting here be a tab? It's not clear by the PHP standards, but the JavaScript standards are more specific about this case:

>When a conditional is too long to fit on one line, successive lines must be indented one extra level to distinguish them from the body.

https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/#multi-line-statements

i.e.

```php
if ( $sendback && (
		strpos( $sendback, 'post.php' ) !== false ||
		strpos( $sendback, 'post-new.php' ) !== false ) ) {
	return $url;
}
```
