### PR TITLE
Fix editor colors for themes not loading color palettes

### LINKED ISSUE #21931: Color settings not styling block in editor
**Describe the bug**
In the editor, the color settings are not styling the selected block with colors from editor-color-palette. Choosing a custom color does work. 

Colors display as expected on frontend. 

Also not displaying here: https://wordpress.org/gutenberg/

**To reproduce**
1. create text block. type text
2. in block controls, go to "color settings"
3. choose swatch for text color.
4. text does not change color.
5. choose swatch for background color
6. background does not change color though padding is added

**Expected behavior**
Selected block should change color.

**Editor version (please complete the following information):**
- Fresh WordPress 5.4
- gutenberg plugin 7.9.1
- twenty nineteen theme

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.4
 - Browser: Safari 13.1

### PR DESCRIPTION
**Pull request by youknowriad**
closes #21931 

While ideally themes should load their palette styles in the editor to match the frontend, this PR restores the inline styles that were previously applied on the editor to avoid regressions.

The downside here is that there's a hook that has a very small but non-negligible impact on performance. 

**Testing instructions**

 - Use a theme that doesn't load its palette on the editor (2019)
 - Make sure that when you use palette colors, the colors apply properly.

### CODE REVIEW

File: packages/block-editor/src/hooks/color.js [hunk 1]
```diff
@@ -276,6 +277,47 @@ export function ColorEdit( props ) {
...
+						?.color
+				: undefined,
+		};
+
+		let wrapperProps = props.wrapperProps;
+		wrapperProps = {
+			...props.wrapperProps,
+			style: {
+				...extraStyles,
+				...props.wrapperProps?.style,
```
Comment (jorgefilipecosta) [inline packages/block-editor/src/hooks/color.js:313]: Here we assume props.wrapperProps may be undefined (props.wrapperProps?) but previously we spread it without any verification (...props.wrapperProps). Should we add a verification?

File: packages/block-editor/src/hooks/color.js [hunk 2]
```diff
@@ -276,6 +277,47 @@ export function ColorEdit( props ) {
...
+ */
+export const withColorPaletteStyles = createHigherOrderComponent(
+	( BlockListBlock ) => ( props ) => {
+		const { name, attributes } = props;
+		const { backgroundColor, textColor } = attributes;
+		const { colors } = useSelect( ( select ) => {
+			return select( 'core/block-editor' ).getSettings();
+		}, [] );
+
+		if ( ! hasColorSupport( name ) || ! backgroundColor || ! textColor ) {
```
Comment (jorgefilipecosta) [inline packages/block-editor/src/hooks/color.js:295]: This condition may be wrong. If text color is set but a background color is not set we may not be applying the text color style. I'm able to reproduce this issue while testing with the paragraph block and 2019 theme.

File: packages/block-editor/src/hooks/color.js (hunk 1 above)
Comment (youknowriad) [reply packages/block-editor/src/hooks/color.js:313]: spreading doesn't cause errors when the value is undefined.

File: packages/block-editor/src/hooks/color.js (hunk 2 above)
Comment (youknowriad) [reply packages/block-editor/src/hooks/color.js:295]: Good catch

**Review by jorgefilipecosta — APPROVED** [review]
LGTM 👍 We have a failing test on travis but does not looks related.

File: packages/block-editor/src/hooks/color.js [hunk 3]
```diff
@@ -276,6 +277,47 @@ export function ColorEdit( props ) {
...
+ * Ideally, this is not needed and themes should load their palettes on the editor.
+ *
+ * @param  {Function} BlockListBlock Original component
+ * @return {Function}                Wrapped component
+ */
+export const withColorPaletteStyles = createHigherOrderComponent(
+	( BlockListBlock ) => ( props ) => {
+		const { name, attributes } = props;
+		const { backgroundColor, textColor } = attributes;
+		const { colors } = useSelect( ( select ) => {
```
Comment (youknowriad) [inline packages/block-editor/src/hooks/color.js:291]: I tracked the test failure locally. I don't understand why it happens yet but it seems that commenting/removing the useSelect solves the issue. That's very weird. Any ideas why a useSelect call without impact on the rendered component would break tests here cc @aduth @epiqueras @jorgefilipecosta

Comment (aduth) [reply packages/block-editor/src/hooks/color.js:291]: What are the symptoms of the issue? (What do you see?)

Based on what I see here, it's not really clear what issue there should be. Is it fair to say "without impact on the rendered component" if `colors` is used below in determining which props to assign?

I doubt it has any impact on fixing the issue, but a suggestion I might have here is it could be good to avoid the subscription incurred by `useSelect` until after the point where it's known whether the early `return` is reached, by creating a separate component which handles the logic after the early return and contains the hook.

I guess unless we figure that most common blocks will support colors, in which case it's probably not much an optimization.

Comment (youknowriad) [reply packages/block-editor/src/hooks/color.js:291]: I agree with the proposal, it will fix the test but potentially hide an issue because the test fails even if we don't apply any style (the early return)

And I don't the symptoms are basically the test failure: it seems like something related to focus  maybe cause the "Third paragraph" is not written.

Comment (epiqueras) [reply packages/block-editor/src/hooks/color.js:291]: It sounds like a race condition with the subscriptions.

Comment (youknowriad) [reply packages/block-editor/src/hooks/color.js:291]: This PR is an important fix, I'm tempted to apply @aduth's fix in order to land it even if it hides the failure.

Comment (epiqueras) [reply packages/block-editor/src/hooks/color.js:291]: It's not a bad idea. That's the recommended way to deal with conditional hooks, regardless of tests.

**Comment by nosolosw** [comment]
Hey, this is a difficult situation 😞

Trying to recap what has happened here, for the record:

- At some point in the past, the Block Editor makes custom presets (color, font-size, gradient) work by adding a class and inline styles to the block, while in the front the inline styles aren't present.
- Themes declare custom presets. However, some of them don't enqueue the corresponding classes for those presets in the editor.
- Luckily, presets in the editor still work because Gutenberg added inline styles in addition to the classes.
- We removed the inline styles to make the editor as much similar to the front-end as possible, so themes can do fewer things.
- Themes that don't enqueue the styles for their custom presets realize that the styles for their presets in the editor aren't present (so some things aren't working now).

Would this be a faithful representation of what happened here?

If it is, I wouldn't consider this a Block Editor regression, but a theme bug that was only uncovered recently. Note that this fix is also incomplete: for example, it won't fix the situations where themes want to be smart about things (like setting both the text and background color at the same time) and can introduce subtle errors in that case. TwentyTwenty does this.

I reckon we under-communicated the removal of inline styles. Do you think is still there a chance we can handle this by publishing a dev note?

I understand this is a nuanced situation and why we feel like we need to cover for themes here. So, _if_ we do this, I'd say that:

- We should do the same for the font-size presets.

- By coincidence, this PR would also fix https://github.com/WordPress/gutenberg/issues/22482 although the root cause is different. I have a PR at https://github.com/WordPress/gutenberg/pull/22526 that addresses that different issue and I think it should land anyway (just in case, in the future, we may be able to revert this change).

File: packages/block-editor/src/hooks/color.js (hunk 3 above)
Comment (youknowriad) [reply packages/block-editor/src/hooks/color.js:291]: Actually, no ideally we don't remount the block when applying a color so we shouldn't bail early here (maybe just for the support check)

**Comment by youknowriad** [comment]
> I reckon we under-communicated the removal of inline styles. Do you think is still there a chance we can handle this by publishing a dev note?

Judging by the number  of impacted themes,  I don't think so. That said, this becomes useless when we provide presets styles... (experimentl-theme.json)

**Comment by youknowriad** [comment]
Did we use inline styles for font sizes as well in the past? If so I agree we should do the same but I'm not sure it was the case.

**Comment by nosolosw** [comment]
> Judging by the number of impacted themes, I don't think so.

:+1: 

> That said, this becomes useless when we provide presets styles... (experimental-theme.json)

Agreed. One of the advantages of a "managed CSS" approach.

> Did we use inline styles for font sizes as well in the past? If so I agree we should do the same but I'm not sure it was the case.

I was under the impression we did, but I'll check tomorrow morning.

**Comment by nosolosw** [comment]
Yeah, font-sizes [did the same](https://github.com/WordPress/gutenberg/pull/21153/files#diff-7b64e61cdb441265be8d707b44abad80L90). Haven't looked at the code for this PR, but, if this is ready, perhaps it can land and we do font-sizes separately. You want to do that or should I help? I guess that's one that needs to land in the next release for coherence.

File: packages/block-editor/src/components/block-list/block.js [hunk 4]
```diff
@@ -38,6 +38,30 @@ import { Block } from './block-wrapper';
...
+ *
+ * @return {Object} Merged props.
+ */
+function mergeWrapperProps( propsA, propsB ) {
+	const newProps = {
+		...propsA,
+		...propsB,
+	};
+
+	if ( propsA && propsB && propsA.className && propsB.className ) {
```
Comment (nosolosw) [inline packages/block-editor/src/components/block-list/block.js:55]: optional?.chaining?.here?

**Comment by youknowriad** [comment]
@nosolosw I'd appreciate some help if possible for the font sizes.

I'm not going to merge yet though because it's quite clear that this PR makes the e2e tests more unstable than master for the moment.

File: packages/block-editor/src/hooks/color.js [hunk 5]
```diff
@@ -276,6 +277,48 @@ export function ColorEdit( props ) {
...
+		wrapperProps = {
+			...props.wrapperProps,
+			style: {
+				...extraStyles,
+				...props.wrapperProps?.style,
+			},
+		};
+
+		return <BlockListBlock { ...props } wrapperProps={ wrapperProps } />;
+	}
```
Comment (nosolosw) [inline packages/block-editor/src/hooks/color.js:319]:
```suggestion
	},
	'withColorPaletteStyles'
```

**Comment by nosolosw** [comment]
@youknowriad I've created the equivalent PR for font sizes at https://github.com/WordPress/gutenberg/pull/22668

**Comment by ellatrix** [comment]
What's the status of this PR?

**Comment by youknowriad** [comment]
The status is that it's ready but I haven't been able to find a way to make the e2e failure go. I'm having hard time understanding the reason for this failure.

File: packages/block-editor/src/hooks/color.js [hunk 6]
```diff
@@ -334,6 +335,48 @@ export function ColorEdit( props ) {
...
+ *
+ * @param  {Function} BlockListBlock Original component
+ * @return {Function}                Wrapped component
+ */
+export const withColorPaletteStyles = createHigherOrderComponent(
+	( BlockListBlock ) => ( props ) => {
+		const { name, attributes } = props;
+		const { backgroundColor, textColor } = attributes;
+		const { colors } = useSelect( ( select ) => {
+			return select( 'core/block-editor' ).getSettings();
```
Comment (ellatrix) [inline packages/block-editor/src/hooks/color.js:350]: Why are we returning all settings here? Shouldn't we only subscribe to `colors` changes?

Comment (youknowriad) [reply packages/block-editor/src/hooks/color.js:350]: Good remark, not sure it has any impact though.

File: packages/block-editor/src/hooks/color.js (hunk 3 above)
Comment (ellatrix) [reply packages/block-editor/src/hooks/color.js:349]: Aren't we already rerendering? For each path, a different instance of `BlockListBlock` is returned. It should still work otherwise though. Maybe worth looking at after beta 1?

File: packages/block-editor/src/hooks/color.js [hunk 7]
```diff
@@ -334,6 +335,48 @@ export function ColorEdit( props ) {
...
+			color: textColor
+				? getColorObjectByAttributeValues( colors, textColor )?.color
+				: undefined,
+			backgroundColor: backgroundColor
+				? getColorObjectByAttributeValues( colors, backgroundColor )
+						?.color
+				: undefined,
+		};
+
+		let wrapperProps = props.wrapperProps;
```
Comment (ellatrix) [inline packages/block-editor/src/hooks/color.js:367]: This can be a constant?

File: packages/block-editor/src/components/block-list/block.js (hunk 4 above)
Comment (ellatrix) [reply packages/block-editor/src/components/block-list/block.js:55]: How can `propsA` be spread above if it can me nullish?
