### PR TITLE
Rich text: fix link paste for internal paste

### LINKED ISSUE #57487: Copy/pasting a link from plain text causes autolinking to not work
### Description

If you paste some text and a link from plain text into Gutenberg and then try to apply the link with a copy/paste onto the text itself, it fails and instead just replaces the text. 

### Step-by-step reproduction instructions

1. Write some text with a link in plain text.
2. Copy and paste it into a new post. 
3. Copy the link you added and paste it over the text.
4. Notice it doesn't link and instead overwrites the text. 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/26996883/678a3f87-9c61-4b1b-aa47-bff3ba9e6151

### Environment info

- WP 6.4.2
- GB 17.3
- TT4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Fixes https://github.com/WordPress/gutenberg/issues/57487
Alternative to #58786

## Why?

Added an e2e test that fails in trunk:

```
  1) [chromium] › editor/various/copy-cut-paste.spec.js:541:2 › Copy/cut/paste › should link selection on internal paste 

    Error: expect(received).toMatchObject(expected)

    - Expected  - 1
    + Received  + 1

      Array [
        Object {
          "attributes": Object {
    -       "content": "<a href=\"https://w.org\">a</a>",
    +       "content": "https://w.org",
          },
          "name": "core/paragraph",
        },
      ]

      553 | 		await pageUtils.pressKeys( 'shift+ArrowLeft' );
      554 | 		await pageUtils.pressKeys( 'primary+v' );
    > 555 | 		expect( await editor.getBlocks() ).toMatchObject( [
```

## How?

The transforms must be run for external as well as internal paste.

## Testing Instructions

See test and issue linked: type out a link, copy it, then paste it over a word.

### CODE REVIEW

File: packages/block-editor/src/components/rich-text/use-paste-handler.js [hunk 1]
```diff
@@ -58,13 +58,35 @@ export function usePasteHandler( props ) {
 			const isInternal =
 				event.clipboardData.getData( 'rich-text' ) === 'true';
 
+			function pasteInline( content ) {
+				const transformed = formatTypes.reduce(
+					( accumlator, { __unstablePasteRule } ) => {
```
Comment (mcsf) [inline packages/block-editor/src/components/rich-text/use-paste-handler.js]: While we're here, we can fix the typo:

```suggestion
					( accumulator, { __unstablePasteRule } ) => {
```

**Review by mcsf — APPROVED** [review]
Oh, I see what you mean. Thanks, LGTM :)

File: packages/block-editor/src/components/rich-text/use-paste-handler.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-editor/src/components/rich-text/use-paste-handler.js]: What do you mean, you didn't know about the abbreviation accum'lator? 😄

**Comment by youknowriad** [comment]
I just cherry-picked this PR to the more/backports-for-beta3 branch to get it included in the next release: 295804391b4
