### PR TITLE
Cover: Video - Add position controls

### LINKED ISSUE #22509: Cover: Video - Add position controls
At the moment, the horizontal and vertical background positioning controls only work for Cover images. **Cover videos lack this feature**.

Screen Capture on 2020-05-20 at 17-33-12

I think it would be helpful to add feature parity with video backgrounds.

To achieve the same positioning MATH, `<video />` styles can use [object-position](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position).

This will also give as an opportunity to improve the `FocalPointPicker` component a bit.

I've done some explorations! I've added couple of enhancements, including adding our new `UnitControl` components as well as a Grid overlay. It feels really nice!

Screen Capture on 2020-05-20 at 17-19-09

Note: This does not work on IE 11. However, `video` backgrounds **already use** `object-fit: cover`. So this update should not introduce a regression on IE 11.

### PR DESCRIPTION
**Pull request by ItsJonQ**
focal-demo

This update adds positioning controls for video backgrounds within the **Cover block**. Previous to this image, the positioning controls (powered by the `FocalPointPicker` component) were available only to image backgrounds.

##### Click to reposition

The position values can be updated by clicking anywhere in the preview area.

##### Keyboard arrow key support

Screen Capture on 2020-05-21 at 14-53-25

Up, Down, Left, Right keyboard keys will adjust the position values.

##### Hold Shift to jump by 10

Holding <kbd>Shift</kbd> will jump the values, rounded to the nearest `10`. This works for boht dragging and keyboard arrow inputs.

##### New InputControls

The `top` and `left` values use a new `NumberControl` component. This component includes many features, such as dragging to update, jumping values by holding <kbd>Shift</kbd>, and automatic number rounding.

##### Grid

A 9x9 grid appears anytime a value is updated by **any** interaction (drag, click, etc...)

## 🛠 Fixes

* Enable `<FocalPointPicker />` to reset values based on undo actions in the editor.

## How has this been tested?

This has been tested locally in Storybook and local Gutenberg.

To test...

* Pull down the branch
* Run `npm install`
* Run `npm run dev` to fire up local Gutenberg
* Add a Cover block
* Add a video background (Here's a [sample video to download](https://www.w3schools.com/html/mov_bbb.mp4))
* Adjust the position
* Ensure it works in the editor and on the front-end of the site

## Types of changes

* Add video preview support to `FocalPointPicker`
* Substantial refactors to `FocalPointPicker`
* Adds `Flex` component to `@wordpress/components` as a layout-based primitive
* Update Cover video position rendering in `edit.js` and `save.js`

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. 

Resolves: https://github.com/WordPress/gutenberg/issues/22509

### CODE REVIEW

File: packages/components/src/focal-point-picker/styles/focal-point-style.js [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+/**
+ * WordPress dependencies
+ */
+import { Path, SVG } from '@wordpress/primitives';
+
+/**
+ * Internal dependencies
+ */
+import { color } from '../../utils/style-mixins';
+
```
Comment (ItsJonQ) [inline packages/components/src/focal-point-picker/styles/focal-point-style.js:15]: Migrated and improved styles from the previous `styles.scss` file.

**Comment by ItsJonQ** [comment]
@jasmussen Provided a design suggestion in the issue. Will attempt it now 🙌

**Comment by ItsJonQ** [comment]
@jasmussen We have "side" label alignments for Inputs :D

Screen Shot 2020-05-22 at 1 35 08 PM

Note! This is done at the `InputControl` component level. That means that we can more easily side-align labels in the future in a consistent manner (if we choose to)

**Comment by ItsJonQ** [comment]
@jasmussen Based on your mockup, do you think we should remove the extra padding around the media (when possible)?

Screen Shot 2020-05-22 at 1 38 00 PM

Doing so would change the height of the preview. We could set min/max values to ensure it doesn't get too wonky.

It comes down to... do we want the preview to have a consistent height (currently `200px`) or not 😊 

Would love your thoughts!

**Comment by jasmussen** [comment]
> @jasmussen Based on your mockup, do you think we should remove the extra padding around the media (when possible)?

OMG @ItsJonQ I'm so sorry I missed this ping! I don't know hos that got lost. Sorry about that.

Yes, I think we should remove both the border, and the inner padding — I can't quite figure out what that padding is for, if it serves a purpose then I can add a new design.

Border too, yes, I know that we might end up with a situation where a white background bleeds in. If it turns out to be a problem, we can fo a subtler shadow border that should only be visible in those cases, such as `box-shadow: inset 0 0 0 $border-width rgba($black, 0.4)`; or something like that.

**Comment by ItsJonQ** [comment]
@jasmussen No worries! Thanks for the followup :)

I've updated the UI to remove the excess padding, and added a subtle border (via box-shadow):

Screen Shot 2020-06-08 at 3 48 08 PM

Lemme know how it feels!

P.S. Excuse ma spooky 👻 cover image, haha

**Comment by jasmussen** [comment]
This is way better.

All this needs is a code review 👍 👍

**Comment by ItsJonQ** [comment]
@jasmussen Amazing! Thank you <3

File: packages/components/src/focal-point-picker/styles/focal-point-picker-style.js [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+	box-sizing: border-box;
+	height: 170px;
+	max-width: 280px;
+	min-width: 200px;
+	width: 100%;
+`;
+
+export const UnitControl = styled( BaseUnitControl )`
+	width: 100px;
+`;
```
Comment (youknowriad) [inline packages/components/src/focal-point-picker/styles/focal-point-picker-style.js:56]: So for my own knowledge, this means the sub-styles are passed as a `style` prop right? Are there any other magic-tricks done here? 

Also, this seems to force us to add  a `style` prop for most of our components. How do you see React native support fitting here. One principle we had for some time in `@wordpress/components` is that the public API for our components should  be as DOM agnostic as possible.

File: packages/components/src/focal-point-picker/focal-point.js [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+	PointerIconSVG,
+	PointerIconPathFill,
+	PointerIconPathOutline,
+	FocalPointWrapper,
+} from './styles/focal-point-style';
+
+export default function FocalPoint( {
+	coordinates = { left: '50%', top: '50%' },
+	isDragging = false,
+	...props
```
Comment (youknowriad) [inline packages/components/src/focal-point-picker/focal-point.js:19]: I noticed you do that often (spread extra props) and I'm having trouble figuring out why or whether I consider this a good or bad practice. Are these needed? I know I personally try to avoid them if possible as they can lead to react warnings and can be hard to follow.

File: packages/components/src/focal-point-picker/grid.js [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+ * Internal dependencies
+ */
+import {
+	GridView,
+	GridLineX,
+	GridLineY,
+} from './styles/focal-point-picker-style';
+
+export default function FocalPointPickerGrid( {
+	bounds = {},
```
Comment (youknowriad) [inline packages/components/src/focal-point-picker/grid.js:16]: Do you think bounds is better than height/width? I'm mainly thinking in terms of consistency or should it be `dimensions` like the prop for `FocalPointPicker`?

File: packages/components/src/focal-point-picker/grid.js [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+	percentages = {
```
Comment (youknowriad) [inline packages/components/src/focal-point-picker/grid.js:17]: Seems like the only thing we need here is a new instance of the value when it changed. Do you think we should just name this `value` and avoid any computation/destructuring? As written it gives the impression that we do need each value separately but by looking at the code it's not really the case, we just need a new instance.

File: packages/components/src/focal-point-picker/grid.js [hunk 6]
```diff
@@ -0,0 +1,79 @@
...
+
+			clearTimer();
+
+			timeoutRef.current = setTimeout( () => {
+				setIsActive( false );
+			}, 600 );
+		}
+
+		return () => clearTimer();
+	}, [ value ] );
```
Comment (youknowriad) [inline packages/components/src/focal-point-picker/grid.js:74]: Seems like this could be simplied to just:

```
useEffect( () => {
 	setIsActive( true );
 	const timeout = setTimeout( () => {
 		setIsActive( false );
 	}, 600 );

 	return () => window.clearTimeout( timeout );
 }, [ value ] );
```

and avoid all refs. Am I missing anything?

File: packages/components/src/focal-point-picker/index.js [hunk 7]
```diff
@@ -9,62 +10,86 @@ import classnames from 'classnames';
...
+} from './styles/focal-point-picker-style';
+import { roundClamp } from '../utils/math';
+import { INITIAL_BOUNDS } from './utils';
 
 export class FocalPointPicker extends Component {
-	constructor( props ) {
-		super( props );
-		this.onMouseMove = this.onMouseMove.bind( this );
+	constructor( props, context ) {
+		super( props, context );
```
Comment (youknowriad) [inline packages/components/src/focal-point-picker/index.js:33]: in general we used to use this pattern `super( ...arguments )` but it's the same thing.

File: packages/components/src/input-control/index.js [hunk 8]
```diff
@@ -37,6 +37,7 @@ export function InputControl(
 		isPressEnterToChange = false,
 		isFloatingLabel = false,
 		label,
+		labelPosition = 'top',
```
Comment (youknowriad) [inline packages/components/src/input-control/index.js:40]: Do you see this as something available in all *Control components?

File: packages/e2e-tests/fixtures/blocks/core__cover__deprecated-4.serialized.html [hunk 9]
```diff
@@ -1,5 +1,5 @@
 <!-- wp:cover {"url":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==","id":35,"focalPoint":{"x":"0.07","y":"0.07"}} -->
-<div class="wp-block-cover has-background-dim" style="background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==);background-position:7% 7%"><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","fontSize":"large"} -->
+<div class="wp-block-cover has-background-dim" style="background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==);background-position:7.000000000000001% 7.000000000000001%"><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","fontSize":"large"} -->
```
Comment (youknowriad) [inline packages/e2e-tests/fixtures/blocks/core__cover__deprecated-4.serialized.html:2]: Seems like this change is an indication that something is wrong with the "rounding" of the focal point value.

**Review by youknowriad — COMMENTED** [review]
That component is still a monster :) but It's a nicer monster with these focused subcomponents.

File: packages/e2e-tests/fixtures/blocks/core__cover__deprecated-4.serialized.html (hunk 9 above)
Comment (ItsJonQ) [reply packages/e2e-tests/fixtures/blocks/core__cover__deprecated-4.serialized.html:2]: This is really odd... looking into this now!

File: packages/components/src/input-control/index.js (hunk 8 above)
Comment (ItsJonQ) [reply packages/components/src/input-control/index.js:40]: Unsure yet! However, I know there are certain UIs where a top vs bottom label position would be beneficial. ColorPicker is a good example. Also BoxControl. I guess we'll see :)

File: packages/components/src/focal-point-picker/styles/focal-point-picker-style.js (hunk 2 above)
Comment (ItsJonQ) [reply packages/components/src/focal-point-picker/styles/focal-point-picker-style.js:56]: `styled()` generated CSS are passed as classNames ✌️ .

```
styled.div`...`

// or

styled(SomeComponent)`...`
```

Creates...

```
<div className="css-12xjx1" />
```

With the generated CSS injected (and managed) as:

```
<style>
    ...
    .css-12xjx1 {...}
    ...
</style>
```

Hope this helps!

Comment (youknowriad) [reply packages/components/src/focal-point-picker/styles/focal-point-picker-style.js:56]: Oh cool! How does this translate in react native?

File: packages/components/src/focal-point-picker/focal-point.js (hunk 3 above)
Comment (ItsJonQ) [reply packages/components/src/focal-point-picker/focal-point.js:19]: For component libraries, prop spreading is common and often the default. The reason is because the consumer should be able to use HTML approved properties (like `aria-*` or `data-*`) just like they would on any HTML element. Not only that, but `on*` event callbacks should be available as well.

A (mostly) reliable solution for handling React warnings is that inner components often have prop filtering built in. In the case of components created with `@emotion/styled`, they filter out non React/HTML props before passing it down to elements like `<div />`, `<input />`, etc...

File: packages/components/src/focal-point-picker/controls.js [hunk 10]
```diff
@@ -0,0 +1,70 @@
...
+				dragDirection="s"
+			/>
+		</ControlWrapper>
+	);
+}
+
+function UnitControl( props ) {
+	return (
+		<BaseUnitControl
+			className="focal-point-picker__controls-position-unit-control"
```
[the remark this answers is not in the document]
Comment (ItsJonQ) [reply packages/components/src/focal-point-picker/controls.js:61]: `className` is not required for styling ✌️. However, I kept them to maintain current style workflows + expectations within the project.

File: packages/block-library/src/cover/save.js [hunk 11]
```diff
@@ -104,6 +115,7 @@ export default function save( { attributes } ) {
 					loop
 					playsInline
 					src={ url }
+					style={ { objectPosition: positionValue } }
```
[the remark this answers is not in the document]
Comment (ItsJonQ) [reply packages/block-library/src/cover/save.js:118]: Ah, good catch. I'll make that update 👍

File: packages/components/src/focal-point-picker/styles/focal-point-picker-style.js (hunk 2 above)
Comment (ItsJonQ) [reply packages/components/src/focal-point-picker/styles/focal-point-picker-style.js:56]: I believe it generates a React Native `Stylesheet` under the hood:

https://emotion.sh/docs/@emotion/native

https://github.com/emotion-js/emotion/blob/master/packages/native/src/styled.js#L7

I've used `styled` from `@emotion/native` in a pure React Native project. It worked great! However, I've personally not worked on project that required the exact same (styled) component to be compatible for both Web and Native.

That would be an interesting challenge!

Comment (youknowriad) [reply packages/components/src/focal-point-picker/styles/focal-point-picker-style.js:56]: Would be cool to see if these new components work well for the mobile team.

File: packages/components/src/focal-point-picker/focal-point.js (hunk 3 above)
Comment (youknowriad) [reply packages/components/src/focal-point-picker/focal-point.js:19]: > For component libraries, prop spreading is common and often the default. The reason is because the consumer should be able to use HTML approved properties (like aria-* or data-*) just like they would on any HTML element. Not only that, but on* event callbacks should be available as well.

When I use `FocalPointPicker` as a user, I don't know its internals whether it's a div, a button, or just a string... which makes me think, I don't know what HTML  prop are approved. This also makes it harder to be compatible with mobile. A block doing `< FocalPointPicker some-dom-specific-prop="something" />` won't translate properly to mobile. 

It makes me wonder if we should try to move away from these iteratively.

File: packages/components/src/focal-point-picker/controls.js (hunk 10 above)
[the remark this answers is not in the document]
Comment (ItsJonQ) [reply packages/components/src/focal-point-picker/controls.js:61]: Oh? That works for me 👍 . It would encourage a more component (API) driven approach for adjustments.

I know that ad-hoc className targeting has proved to be a bit problematic in the block/editor part of the stylesheets. I also understand that those were the most practical solutions at the time.

File: packages/components/src/focal-point-picker/index.js (hunk 7 above)
Comment (ItsJonQ) [reply packages/components/src/focal-point-picker/index.js:33]: That makes sense to me 👍

File: packages/components/src/focal-point-picker/grid.js (hunk 5 above)
Comment (ItsJonQ) [reply packages/components/src/focal-point-picker/grid.js:17]: Works for me

File: packages/components/src/focal-point-picker/grid.js (hunk 6 above)
Comment (ItsJonQ) [reply packages/components/src/focal-point-picker/grid.js:59]: That works. I initially created refs so that the animation would not flash on first render. I was able to combine your solution with the `useUpdateEffect` hook from another PR:

https://github.com/WordPress/gutenberg/blob/8a35791d60f8a69e2d155990e9c7e564248a4713/packages/components/src/utils/use-update-effect.js

File: packages/block-library/src/cover/edit.js [hunk 12]
```diff
@@ -327,28 +331,36 @@ function CoverEdit( {
...
-									onChange={ ( newFocalPoint ) =>
-										setAttributes( {
-											focalPoint: newFocalPoint,
-										} )
-									}
-								/>
-							) }
-						{ VIDEO_BACKGROUND_TYPE === backgroundType && (
-							<video autoPlay muted loop src={ url } />
+						{ isImageBackground && ! hasParallax && (
```
[the remark this answers is not in the document]
Comment (ItsJonQ) [reply packages/block-library/src/cover/edit.js:341]: Oh, that works 👍 .  I'll created another `const` above. Something like `const showFocalPointPicker` so that it's easier to follow.

File: packages/e2e-tests/fixtures/blocks/core__cover__deprecated-4.serialized.html (hunk 9 above)
Comment (ItsJonQ) [reply packages/e2e-tests/fixtures/blocks/core__cover__deprecated-4.serialized.html]: Fixed! I needed to wrap the values with `Math.round` in `block/save.js`

**Review by youknowriad — APPROVED** [review]
This is looking very good 👍

**Comment by ItsJonQ** [comment]
@youknowriad Thank you for reviewing this @youknowriad + @jasmussen  ! I'll merge it up 🙌

**Comment by youknowriad** [comment]
Looks like this PR might have introduced a JavaScript unit test error on master 😬

**Comment by ItsJonQ** [comment]
@youknowriad Uh oh!! Will look into that now

**Comment by ItsJonQ** [comment]
@youknowriad PR incoming with fix~!
