### PR TITLE
[Block Library - Post Excerpt]: Fix `excerpt_more` filter conflict and remove `wordCount` attribute

### LINKED ISSUE #32473: Query block: Conflict with excerpt_more filter
## Description
It looks like the Query block outputs multiple More links when the Post Excerpt block is used within the Query block , and `excerpt_more` filter is used in the theme functions.

## Step-by-step reproduction instructions

1. Create new page.
2. Add the **Query** block to the content area (Grid View, and 3 columns layout to display 3 latest posts).
3. Select the **Post Excerpt** block.
4. In the **Post Excerpt** settings, set "Max words" to 25 and check option "Show link on new line".
5. Add "read more" link text.
6. Publish page.

## Expected behaviour
Only one More link should be shown in the excerpt section.

## Actual behaviour
The excerpt section displays two More links: one from the theme, added via `excerpt_more` filter, and another from the Query block, with a custom text added using the Editor.

Multiple more links in the excerpt section

## WordPress information
- WordPress version: "5.8-alpha-51064"
- Gutenberg version: Not installed
- Twenty Twenty-One: "1.3"
- Are all plugins deactivated? "Yes"

### LINKED ISSUE #33306: Post Excerpt Block: Max words control is not available when an excerpt is present
The post excerpt block includes a slider to control the length of the excerpt: 

Screen Shot 2021-07-08 at 2 00 39 PM

This works infrequently in my testing. Part of the reason is that the control seems to totally disappear sometimes. In my testing, it shows up when there's no excerpt, but disappears when there is an auto-generated excerpt present:

post-excerpt

## To reproduce: 

1. Start a new, empty post.
2. Add a paragraph, do not hit save yet. 
3. Add a post excerpt block, and notice that it has a "max words" slider in the sidebar. 
4. Now save the post. 
5. Select the post excerpt block (which now has an excerpt in it), and notice that there is no longer a "max words" slider in the sidebar. 

## GIF:

post-excerpt

### LINKED ISSUE #33309: Post Excerpt Block: Remove ability to load a post within the template editor to prevent inception/crashing
## Description

If you click "continue reading" in the Post Excerpt Block within the Query Loop block, the post itself is loaded in the editor. This eventually causes the editor to crash. This issue is similar to this previously reported bug: https://github.com/WordPress/gutenberg/issues/30647  and might be related to this: https://github.com/WordPress/gutenberg/issues/33269 

## Step-by-step reproduction instructions

1. Enable template editing mode in the twenty twenty-one theme. 
2. Add new page. 
3. Create a new template from the sidebar and give it a name.
4. Add the Query Loop block and select whatever configuration you desire.
5. Add the Post Excerpt block into the loop. 
6. Click on "Continue reading" and find it opens up the post within the template editor. 

## Expected behaviour

Unable to click on the post link and have it load. 

## Actual behaviour

Able to click on the read more and see the site load within the editor.

## Screenshots or screen recording (optional)

During this recording, the editor didn't crash but for most of the tests it does after the post is loaded and I try to click edit:

https://user-images.githubusercontent.com/26996883/124978326-db562b00-dfee-11eb-8de0-f37722325ab8.mov

## WordPress information
- WordPress version: 5.8RC2
- Gutenberg version: 11.0
- Are all plugins except Gutenberg deactivated? No, WP Beta Tester plugin.
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes.

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Chrome Version 89.0.4389.128 (Official Build) (x86_64)

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/33309
Fixes: https://github.com/WordPress/gutenberg/issues/32473
Fixes: https://github.com/WordPress/gutenberg/issues/33306

There are a couple of issues in `Post Excerpt` block that involve the `excerpt_length` and  [`excerpt_more` filter](https://developer.wordpress.org/reference/hooks/excerpt_more/). With `excerpt_more` filter someone (usually a theme) can filter the string in the “more” link displayed after a trimmed excerpt. Both filters are called if a post has no explicit excerpt set in [`wp_trim_excerpt` function](https://developer.wordpress.org/reference/functions/wp_trim_excerpt/).

## Problems
The problems are:
1. `Post Excerpt` block when is not editable, uses the `rendered excerpt` from REST API which makes it impossible to know what and if something has been added. This makes the `wordCount` in editor and the displayed excerpt in editor inconsistent.
2.  If the `Post Excerpt` is editable we create a preview excerpt from the `rendered content`, which isn't the same as the `rendered excerpt`. 
3. `word count` control is currently displayed only if the excerpt has been produced from content and its value is used properly in the front-end but is inconsistent in the editor because of the above problem depending on whether the block is editable or not.
4. We don't know what the filter returns in javascript. If it returns a link it can create `inception` problems which might cause the editor to crash (#33309).
 
## What I've done so far
1. In front-end if we have set a `moreText` in the block, show block's `moreText` and override theme's `excerpt_length` filter  to return nothing. If we have not set `moreText` apply the filters if provided (conflicting filter issue).
2. In the editor if the block is readonly which uses the `rendered excerpt`, I've wrapped it in a `Disabled` component in case `excerpt_more` filter is used and applies a link  (editor crash/inception issue).
3. Remove `wordCount` attribute altogether. This means that if a theme uses `excerpt_length` filter for posts with no excerpt, it will be used but you can't update it in javascript. This solves other inconsistencies described in above `Problems` section in `1 and 2`.

## Testing instructions
1. In order to reproduce the issues you have to enable a theme that has such a filter like `twenty twenty one`.
2. Please read the testing instructions from the issues: [editor crash/inception](https://github.com/WordPress/gutenberg/issues/33309), [conflict with `excerpt_more` filter](Conflict with excerpt_more filter).

### CODE REVIEW

File: packages/block-library/src/post-excerpt/edit.js [hunk 1]
```diff
@@ -69,6 +69,34 @@ export default function PostExcerptEditor( {
...
+		);
+		const links = document.getElementsByTagName( 'a' );
+		if ( ! links?.length ) {
+			return renderedExcerpt;
+		}
+		for ( const link of links ) {
+			link.setAttribute( 'href', '#excerpt_more-pseudo-link' );
+		}
+		return document.body.innerHTML || '';
+	}, [ renderedExcerpt ] );
```
Comment (youknowriad) [inline packages/block-library/src/post-excerpt/edit.js:58]: What about just wrapping the content with `Disabled` component like we do in several other blocks? Is that enough?

File: packages/block-library/src/post-excerpt/index.php [hunk 2]
```diff
@@ -18,15 +18,16 @@ function render_block_core_post_excerpt( $attributes, $content, $block ) {
 		return '';
 	}
 
-	$more_text = isset( $attributes['moreText'] ) ? '<a class="wp-block-post-excerpt__more-link" href="' . esc_url( get_the_permalink( $block->context['postId'] ) ) . '">' . $attributes['moreText'] . '</a>' : '';
+	$more_text           = ! empty( $attributes['moreText'] ) ? '<a class="wp-block-post-excerpt__more-link" href="' . esc_url( get_the_permalink( $block->context['postId'] ) ) . '">' . $attributes['moreText'] . '</a>' : '';
+	$filter_excerpt_more = function( $more ) use ( $more_text ) {
+		return empty( $more_text ) ? $more : ' [&hellip;]';
```
Comment (youknowriad) [inline packages/block-library/src/post-excerpt/index.php]: Having a bit of trouble to understand the logic here, why are we using `[&hellip;]` here?

File: packages/block-library/src/post-excerpt/edit.js (hunk 1 above)
Comment (ntsekouras) [reply packages/block-library/src/post-excerpt/edit.js:58]: Oh.., I guess this could do the trick for the `click link` problem in a more elegant way. I'll try it out.

File: packages/block-library/src/post-excerpt/index.php (hunk 2 above)
Comment (ntsekouras) [reply packages/block-library/src/post-excerpt/index.php]: That's just the default value for this filter in core. We could remove this default `hellip` altogether.

Comment (youknowriad) [reply packages/block-library/src/post-excerpt/index.php]: ok, so basically what you're doing this is:

If the block has a "more text" attribute, reset the filter. I think it makes sense but why not just return `$more_text` there?

Comment (youknowriad) [reply packages/block-library/src/post-excerpt/index.php]: Also maybe add some comments to explain the logic of why we're using filters here.

Comment (ntsekouras) [reply packages/block-library/src/post-excerpt/index.php]: >I think it makes sense but why not just return $more_text there?

We wrap this block in a `paragraph` and  have `showMoreOnNewLine` that also uses `paragraph`, so we can't have these two nested. We don't always want `more text` just appended to the excerpt.

**Comment by draganescu** [comment]
I remember this was a problem with the latest posts block as well. How did that one sort it out in the end I wonder? Ideally this should be a layered approach:

- there is a default where WordPress creates a $word_count length excerpt with a $default_read_more text link resulting in an $excerpt.
- all three are filtereable and the result of defaults + filters is what the API serves
- in the editor the user can override any of these via UI controls, and these settings have the final say, so they should be known in the end by the server.

To enable this flow it may be that we need to change more than the behavior of the editor.

**Comment by youknowriad** [comment]
I'd appreciate some testing on thoughts for this one to make the right call for 5.8. cc @carolinan @aristath @scruffian @kjellr 

Removing the `word count` does seem logical to avoid conflicts with the backend filter. I wonder if the other alternative for the block is to say: both `excerpt_length` and `excerpt_more` should not apply to the block and the block should have its own logic/attributes and reset these filters.

**Comment by draganescu** [comment]
Will the theme be able to set these via theme.json? If yes, we can just forego the filters and allow themes to set excerpt length and read more in the theme.json and users to change it via UI. No need to respect the filter if the themes don't need it. This block afaik is for block themes, not for classic themes, right?

**Comment by mcsf** [comment]
Just to add some background info regarding:

> there is a default where WordPress creates a $word_count length excerpt with a $default_read_more text link resulting in an $excerpt.

There is a [convention in core](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/formatting.php?rev=51113#L3812) for this in `wp-includes/formatting.php`:

```php
/* translators: Maximum number of words used in a post excerpt. */
$excerpt_length = (int) _x( '55', 'excerpt_length' );
```

It's intended for locales, but I wonder if any themes out there intercept this string. Anyway, if we build something for theme.json, let's keep this convention in mind.

**Comment by mcsf** [comment]
I'm convinced this is the right direction: removing the word-count attribute and sandboxing any server-rendered content.

This block obviously has more rough edges, generally stemming from the frictions between the old and the new, but let's start by fixing proper failures (like the "inception" per #33309) and reduce the client-side feature set; that way, users of traditional themes can keep relying on excerpt hooks.

There's also a bug in which the `showMoreOnNewLine` attribute has no effect when `moreText` is empty. It doesn't break anything, it's just a jarring user experience; so it might be good enough to hide the attribute when `moreText` is empty.

**Comment by mcsf** [comment]
> There's also a bug in which the `showMoreOnNewLine` attribute has no effect when `moreText` is empty. It doesn't break anything, it's just a jarring user experience; so it might be good enough to hide the attribute when `moreText` is empty.

Thinking some more, the fix may end up being more confusing than the original issue. So I decided not to touch this for now.

On the other hand, I pushed 52aa854345d3498ef37d24740c7d83dd023e447a to address a specific remark in https://github.com/WordPress/gutenberg/issues/32473#issuecomment-858828122:

> I've noticed that if the Read More link is wrapped within `p` tag and added using the `excerpt_more` filter, the block creates additional empty `p` tag

I think this is good to go. It definitely closes #33309 (by sandboxing RichText) and #33306 (by removing `wordCount`). As for #32473, I think this solves _most_ of the conflicts. Any leftover issues should be brought up in specific issues, so that we can backport the present fix to WP5.8.

**Review by mcsf — APPROVED** [review]

**Comment by mcsf** [comment]
The failing E2E test stems from a recent merge to trunk and isn't related to this PR. Merging.
