### PR TITLE
Avoid lossy html entities encoding by setting charset

### LINKED ISSUE #24445: Wide-aligned blocks: Non latin text characters are rendered as gibberish inside the block if set to Wide or Full Width
**Describe the bug**

First reported by @zdenys at https://github.com/Automattic/wp-calypso/issues/44759. The following is a copy of that issue, since it applies to Gutenberg.

**To reproduce**
1. Add a Cover block with paragraph of text with some or all non-Latin characters (I tried Norwegian, Japanese and Chinese)
2. Set Cover Block to Wide or Full Width
3. View Preview or Published site

**Expected behavior**
See all characters rendered normally on the front end just like on the backend. 

**Screenshots**

_Link: https://d.pr/i/5gdq1V_

_Link: https://d.pr/i/gFwXfS_

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 8.7

**Additional context**
Encoding issue. PR coming right up.

cc/ @sirreal @akirk @simison @yansern

### PR DESCRIPTION
**Pull request by lsl**
## Description
This change specifies the content type and charset of the html passed into `DomDocument` as `utf-8`.

Replaces the `mb_convert_encoding` call which encodes `UTF-8` as `HTML-ENTITIES` before handing off to `DomDocument`.

This change avoids the need to later revert the encoding back to `UTF-8` afterwards using `mb_convert_encoding`. This secondary `mb_convert_encoding` call was converting not only the `UTF-8` characters that were converted earlier but also any pre-existing entity encoded html stored inside block content.

This issue was originally raised here: https://github.com/Automattic/wp-calypso/issues/44897 as I wasn't sure of the root cause at the time, originally thinking it may be because of the way [Jetpack is injecting](https://github.com/Automattic/jetpack/blob/dcfa5ca8bdfc31aacec107aec27bb24357d6cdac/modules/carousel/jetpack-carousel.php#L434) html into the [`data-image-description` attributes](https://github.com/Automattic/jetpack/blob/dcfa5ca8bdfc31aacec107aec27bb24357d6cdac/modules/carousel/jetpack-carousel.php#L485). 

There are more situations where this can be a problem such as encoded html entities existing inside block content then being decoded breaking html validation.

## How has this been tested?
- The `npm run test-php` unittests cover this somewhat, will add more soon.
- https://3v4l.org/EaZv9 contains illustrates a comparison of the different approaches available

## Screenshots 
Before

After

## Types of changes
- Bug fix

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. 

(re)Fixes https://github.com/WordPress/gutenberg/issues/24445 (Mostly maintaining the same behavior introduced in https://github.com/WordPress/gutenberg/pull/24447)

### CODE REVIEW

**Comment by ockham** [comment]
Looking good so far. We should just add some unit test coverage for the cases this fixes :+1: 

@mcsf @youknowriad Can we get this into 8.8? The [fix](https://github.com/WordPress/gutenberg/pull/24447) we got into 8.7.1 broke cases where server-side rendered blocks inject HTML (e.g. https://github.com/Automattic/wp-calypso/issues/44897) :confused: 

cc/ @sirreal @WunderBart @fullofcaffeine

**Comment by lsl** [comment]
> We should just add some unit test coverage for the cases this fixes +1 

Will do - got sidetracked today. Just added some screenshots that might help explain things a bit better to anyone stopping by.

**Comment by ockham** [comment]
Added unit tests (based on https://3v4l.org/EaZv9) so we can get this merged in time for the 8.8 release.

**Review by ockham — APPROVED** [review]
Approving. I've touched this, but the unit tests give us a pretty good guarantee that this covers a very broad class of content that was previously causing encoding issues.

File: lib/block-supports/index.php [hunk 1]
```diff
@@ -52,17 +52,21 @@ function gutenberg_apply_block_supports( $block_content, $block ) {
 		return $block_content;
 	}
 
+	// We need to wrap the block in order to handle UTF-8 properly.
+	$wrapper_left  = '<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head><body>';
+	$wrapper_right = '</body></html>';
```
Comment (lsl) [inline lib/block-supports/index.php:57]: Much cleaner! :+1:

**Comment by sirreal** [comment]
Thanks for this!
