### PR TITLE
Query: Fix add new post link position via private SlotFill

### LINKED ISSUE #49327: When a block style is registered for the query, the "Create a new post for this feed." link is in the Style section
### Description

When you register a custom block style for the query (with register_block_style or the JavaScript equivalent) the link to where you add a new post to the query is in Styles section.

This is a bit difficult to explain without the screenshot:
When you open the block settings sidebar, 
The link to add new posts is below the title "Styles" and below the buttons that you use to select the style variation.

### Step-by-step reproduction instructions

Register any block style for the query loop.
My example looks like this:

```
<?php
/**
 * Register block styles.
 */
function blue_note_register_block_styles() {
	register_block_style(
		'core/query',
		array(
			'name'  => 'blue-note-query-slant',
			'label' => __( 'Slanted images', 'blue-note' ),
			'inline_style' => '.is-style-blue-note-query-slant .wp-block-post-featured-image {transform: rotate(-1deg);}',
		)
	);
}
add_action( 'init', 'blue_note_register_block_styles' );
```

Open the block editor.
Add a query block.
View the Styles section in the block settings sidebar.

### Screenshots, screen recording, code snippet

Missplaced link in the styles section

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Fixes: https://github.com/WordPress/gutenberg/issues/49327

## What?

- Updates the `SlotFill` component to allow `Symbol` keys instead of string names only.
- Creates a small util function to generate a SlotFill using a Symbol key
- Creates a "private" SlotFill for rendering additional block information (`BlockInfo`).
- Exports the `BlockInfo` component as a private API in the block-editor package
- Renders the `BlockInfo` slot in the block inspector
- Updates the Query block to import and unlock the the new `BlockInfo` fill.
- Renames the "Create new post" link to "Add new post" and renders it as a `BlockInfo` fill.

### <samp>🤖 Generated by Copilot at e46f7af</samp>

This pull request adds a new `BlockInfo` component that can show information about the selected block in the block toolbar. It uses a private slot-fill pair to render the component in different parts of the block editor UI. It also updates the query block UI to use the new component and improves the slot-fill module to support symbols as keys.

## Why?

When plugins register Block Styles for the Query block the Block Styles UI is rendered above the "Add new post" link which should sit immediately below the Block Card or the block's variation transforms if it has them.

We can't use a normal `SlotFill` as anyone with that name could abuse the slot to render anything above the tabs undermining the proper prominence for controls.

The proposed "private" `SlotFill` is only private as far as our Private/Experimental API can make it. A determined individual can still unlock experimental or private APIs even though they shouldn't. It has been generally accepted that we can still consider anything locked via the private API, to in fact be private for our purposes.

The ability to use a private `SlotFill` allows us to avoid introducing block-specific code into the block-editor package simply to restore the position of the Query block's link.

## How?

- Created a new private SlotFill for block information
- Exported private SlotFill as a private API
- Updated the Block Inspector to render the new slot
- Updated the Query block to unlock the new SlotFill and render its "Add new post" link as a fill for it

**It might be easiest to review the PR commit-by-commit as they are all pretty small and self-contained.** 

## Next Steps

- [ ] Write some tests for SlotFills using Symbols as keys

## Testing Instructions

1. Add some block styles to the Query block (example in the snippet below)
2. Edit a post, add a query block, select it and confirm the incorrect create new post link position
3. Checkout this PR branch, rebuild, and reload the post
4. The create new post link position should now be below the block card but above the block styles

```php
<?php
/**
 * Register block styles.
 */
function blue_note_register_block_styles() {
	register_block_style(
		'core/query',
		array(
			'name'  => 'blue-note-query-slant',
			'label' => __( 'Slanted images', 'blue-note' ),
			'inline_style' => '.is-style-blue-note-query-slant .wp-block-post-featured-image {transform: rotate(-1deg);}',
		)
	);
}
add_action( 'init', 'blue_note_register_block_styles' );
```

## Screenshots or screencast 

| Before | After |
|---|---|
| Screenshot 2023-04-04 at 3 53 24 pm | Screenshot 2023-04-14 at 3 42 10 pm |

### CODE REVIEW

File: packages/block-editor/src/components/block-info-slot-fill/index.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+ * WordPress dependencies
+ */
+import { createSlotFill } from '@wordpress/components';
+
+export const createPrivateSlotFill = ( name ) => {
+	const privateKey = Symbol( name );
+	const privateSlotFill = createSlotFill( privateKey );
+
+	return { privateKey, ...privateSlotFill };
+};
```
Comment (talldan) [inline packages/block-editor/src/components/block-info-slot-fill/index.js]: I wonder if this could be moved into the `packages/components/src/slot-fill/index.js` file, and exported from there as a private api?

That way implementers generally don't have to be concerned about the detail of using a Symbol.

It'd be similar to the private `registerPrivateActions` and `registerPrivateSelectors` APIs that exist for stores.

File: packages/components/src/slot-fill/index.js [hunk 2]
```diff
@@ -44,13 +44,14 @@ export function Provider( { children, ...props } ) {
 	);
 }
 
-export function createSlotFill( name ) {
-	const FillComponent = ( props ) => <Fill name={ name } { ...props } />;
-	FillComponent.displayName = name + 'Fill';
+export function createSlotFill( key ) {
+	const baseName = typeof key === 'string' ? key : key.description;
```
Comment (talldan) [inline packages/components/src/slot-fill/index.js]: I think it might be good to flip this.

It would provide better back-compat in case anyone is doing anything weird and already using non-string keys/names (e.g. implementing `toString`):

```suggestion
	const baseName = typeof key === 'symbol' ? key.description : key;
```

File: packages/block-library/src/query/index.js [hunk 3]
```diff
@@ -27,7 +27,7 @@ export const settings = {
 };
 
 export const init = () => {
-	addFilter( 'editor.BlockEdit', 'core/query', queryInspectorControls );
+	addFilter( 'editor.BlockEdit', 'core/query', queryBlockInfo );
```
Comment (talldan) [inline packages/block-library/src/query/index.js]: I wonder why a filter is used for this, vs. adding it to the block directly.

**Review by talldan — COMMENTED** [review]
It's nice that this didn't require too many modifications. I think being able to create private slots will be really useful.

I checked out the branch and tried a few things to see if there were any ways to render in the slot without unlocking the private API:
- `<Fill name="BlockInformation">TEST</Fill>` - didn't work as expected.
- `<Fill name={ Symbol.for( 'BlockInformation' ) }>Test</BlockInformation>` - didn't work as expected, since the symbols created for the slot fill aren't in the symbol registry.

It'd be good to get thoughts from @youknowriad and @adamziel on this approach.

**Comment by aaronrobertshaw** [comment]
Thanks for the early review @talldan 🚀 

A lot of the feedback is on my radar for further polishing before making this ready for final review. The plan is to address it all first thing next week.

That said, getting some early feedback, sanity checking just how "private" the SlotFill would be sounds wise. Thanks for sending out the pings 🙇

File: packages/block-library/src/query/index.js (hunk 3 above)
Comment (aaronrobertshaw) [reply packages/block-library/src/query/index.js]: I have a suspicion it was a means of ensuring the new post link was the first inspector control fill to be rendered. In the earlier PRs addressing this (https://github.com/WordPress/gutenberg/pull/45437/ & https://github.com/WordPress/gutenberg/pull/49566) I removed the filter but I haven't got to it here yet.

File: packages/components/src/slot-fill/index.js (hunk 2 above)
Comment (aaronrobertshaw) [reply packages/components/src/slot-fill/index.js]: Good idea, I'll make that improvement. Thanks.

File: packages/block-editor/src/components/block-info-slot-fill/index.js (hunk 1 above)
Comment (aaronrobertshaw) [reply packages/block-editor/src/components/block-info-slot-fill/index.js]: I wasn't sure if it would be something we necessarily wanted in the components package and previously we've begun by having experimental components in the block-editor package before migrating them to components. That was undermined though once I needed to update the components package's SlotFill to accept a symbol.

I don't have any strong opinions on where is the best home for it. I wrapped it all up here in the block-editor for the initial proof of concept more out of convenience than anything.

**Comment by youknowriad** [comment]
Since this is all private, I don't mind it too much but it seems to me that if `BlockStyles` were also rendered using the `BlockInspector` slot/fills (which we already have there). One could still use `BlockInspector` (and hook priorities) to inject UI where this PR is proposing `BlockInfo` no?

File: packages/block-editor/src/components/block-info-slot-fill/index.js (hunk 1 above)
Comment (aaronrobertshaw) [reply packages/block-editor/src/components/block-info-slot-fill/index.js]: ✅ eb85f63ad6

File: packages/block-library/src/query/index.js (hunk 3 above)
Comment (aaronrobertshaw) [reply packages/block-library/src/query/index.js]: ✅ af0ee962a2

File: packages/components/src/slot-fill/index.js (hunk 2 above)
Comment (aaronrobertshaw) [reply packages/components/src/slot-fill/index.js]: ✅ https://github.com/WordPress/gutenberg/commit/a40673fac1671cbc293b46ef30eb828a220f1e97

**Comment by aaronrobertshaw** [comment]
Thanks for weighing in @youknowriad 👍 

> seems to me that if BlockStyles were also rendered using the BlockInspector slot/fills (which we already have there). One could still use BlockInspector (and hook priorities) to inject UI where this PR is proposing BlockInfo no?

Unfortunately, no, unless I'm missing something. 

If we rely on rendering the Block Styles into existing InspectorControls slots, we can't guarantee order and end up with 3rd parties easily being able to push their controls to a higher prominence than warranted and above the Block Styles.

If we were to add a new InspectorControls group slot for the block styles and explicitly position that slot above the default InspectorControls slot, we end up back where we started needing the means to allow the Query block to position its additional block info (i.e. the new post link) above the Block Styles. 

The current approach in this PR only adds a single new SlotFill. I don't think having an additional private slot dedicated to the Block Styles only provides much value.

**Comment by youknowriad** [comment]
If I'm not mistake @mtias had some resistance in the past to adding such a slot or URLs to blocks there. So, I'm just looping him in just in case.

**Comment by aaronrobertshaw** [comment]
> If I'm not mistake @mtias had some resistance in the past to adding such a slot or URLs to blocks there. So, I'm just looping him in just in case.

I'm happy to wait for @mtias to weigh in, if needed.

For historical context, Matías was involved in https://github.com/WordPress/gutenberg/pull/45437 where we explored a new slot when first rolling out the Block Inspector tabs. The [concerns](https://github.com/WordPress/gutenberg/pull/45437/#pullrequestreview-1187816687) there were the slot being abused by 3rd parties. It was this concern that the private SlotFill aims to mitigate.

It's my understanding we can accept that the private APIs lock/unlock feature is sufficient to consider the new SlotFill private and secure enough.

File: packages/block-editor/src/components/block-inspector/index.js [hunk 4]
```diff
@@ -115,6 +116,7 @@ function BlockInspectorLockedBlocks( { topLevelLockedBlock } ) {
 				className={ blockInformation.isSynced && 'is-synced' }
 			/>
 			<BlockVariationTransforms blockClientId={ topLevelLockedBlock } />
+			<BlockInfo.Slot />
```
Comment (ntsekouras) [inline packages/block-editor/src/components/block-inspector/index.js:119]: Shouldn't  this be above `BlockVariationTransforms`? Also related [issue](https://github.com/WordPress/gutenberg/issues/49887) about slot in BlockCard.

Comment (aaronrobertshaw) [reply packages/block-editor/src/components/block-inspector/index.js:119]: When the block inspector tabs were being introduced, we explored adding a new slot above the tabs for items that related to the block as a whole but weren't really a setting or style. At that time the direction was that it should occur the block transforms as those should still have a higher prominence.

In the Query block's use case with the "add new post" link, it doesn't particularly matter. 

It's worth noting that the earlier exploration into adding a slot above the block inspector tabs was blocked due to concerns about the slot being abused by 3rd parties that might promote their controls in ways detrimental to the end-user experience. The potential "resistance" to a new slot fill here was questioned again in earlier comments on this PR. It was these concerns that drove the approach in this PR to make this proposed slot "private". 

A "private" slot as proposed here wouldn't solve the need expressed in https://github.com/WordPress/gutenberg/issues/49887 as the use case there requires it to be available for public consumption.

So that leaves me a little unsure of how best to proceed here. Some options are:

1. Proceed with this private slot approach to solve the Query block's immediate need.
    - Buys time to get consensus on if we are in fact happy to add a public slot
    - Allows time for exploration to see if we might mitigate misuse of the public slot by filtering allowed fills or something
    - It can easily be changed or removed should we land a new public slot and the private slot fills might be beneficial elsewhere.
2. Shelve this fix until we get consensus on a new public slot, including what is acceptable to be added above the block transforms
3. Bite the bullet and add a public slot to the BlockCard now
4. Rework this PR to only add the private SlotFill feature omitting its use in the block inspector and query block for now

While I don't feel strongly, I'm leaning more towards option 1, landing this PR and iterating from there. That leaning was reinforced further after some internal discussions with @talldan.

What do you think? Are there any better options I haven't considered?

**Review by talldan — APPROVED** [review]
I think it's worth landing this. There's been so much back and forth on this tiny piece of UI, it's been a lot of effort for little reward. I don't think it's worth stretching it out even further.

The implementation here looks good, it avoids introducing code that has tech debt and it can all be removed in the future if a better solution comes along, I personally see no issues.

File: packages/block-editor/src/components/block-inspector/index.js (hunk 4 above)
Comment (ntsekouras) [reply packages/block-editor/src/components/block-inspector/index.js:119]: Sounds good, thank you Aaron!

**Comment by adamziel** [comment]
Late to the party but I like this implementation and I'm glad to see that `lock()` is flexible enough to support all sorts of use-cases. Great use of symbols, too.

**Comment by ciampo** [comment]
Out of curiosity, is creating a  "private slotfill" API necessary? Could we just rely on having the locked `BlockInfo` slot and using symbols directly in the `BlockInfo` implementation?

**Comment by aaronrobertshaw** [comment]
> is creating a "private slotfill" API necessary?

I’d say it would be possible to avoid the private SlotFill API. The `BlockInfo` implementation would then need to import the `Fill` and `Slot` directly and reimplement the `createSlotFill` util to handle symbols. If we keep the updates to `createSlotFill` in the components package, then `createPrivateSlotFill` is a minor addition.

Private SlotFills have already been added in a few more places within Gutenberg, I think providing the API will help reduce code duplication and increase consistency & convenience.

If the API isn’t something that you think fits alongside the component package’s SlotFill API, we could look at relocating it.

**Comment by ciampo** [comment]
> Private SlotFills have already been added in a few more places within Gutenberg

Thank you for the extra context, I was not aware of this.

> If the API isn’t something that you think fits alongside the component package’s SlotFill API, we could look at relocating it.

My comment above was mostly trying to gather more context and understand if we were talking about a single exception, or if the "private slot fill" is a repeated pattern that is worth addressing at the components' package level. I'm happy to keep it as is if we feel that's a correct decision.

@youknowriad , what's your stance, as someone with tons of experience on slot fill ?

**Comment by gziolo** [comment]
> We can't use a normal SlotFill as anyone with that name could abuse the slot to render anything above the tabs undermining the proper prominence for controls.

I agree with the sentiment, but at the same time, it was previously possible to hack the `description` field and include additional DOM nodes, as explained in https://github.com/WordPress/gutenberg/issues/49887. It is also doable to use `InspectorControls` in combination with `editor.blockEdit` filter to render anything the plugin author wants very close to the top of the sidebar – it was implemented this way before. 

I would be in favor of opening this new slot for every plugin author. If necessary, it can be wrapped into an HTML element like `<p>` with opinionated styling that makes it harder to put any type of content inside.

**Comment by mtias** [comment]
One thing to consider is that block info / description can be used in multiple places where you wouldn't expect to be extended — for example, on block previews that include the block description the link for the query block would never be accessible. It seems the semantics should be closely tied to the inspector rendering of this unit.
