### PR TITLE
Packages: Replace the apiRequest module with api-fetch module

### LINKED ISSUE #7488: Gutenberg 3.1 breaks Real Media Library (on Wordpress Media Library screen)
**Describe the bug**
With the latest Gutenberg update (3.1) the Wordpress Media Library does not load and shows an blank screen. I narrowed this down to an plugin I use which is no longer working after the update. The plugin in question is Real Media Library (RML). It fails with the following errors in the console:

ReferenceError: wpApiSettings is not defined: rml.js:1:47210
TypeError: window.rml is undefined: script.js:10:5
TypeError: e is undefined: load-scripts.php:277:1538

On the previous Gutenberg 3.0.1 (?) there was no issue. Also when I disable RML and use only Gutenberg 3.1 all works as intended.

**To Reproduce**
1. Install Gutenberg 3.1
2. Install Real Media Libary
3. Open Wordpress Media Library

**Expected behavior**
Expected behavior is to not interfere with other plugins.

**Screenshots**
I can upload the error or blank screen if requested.

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Firefox 

**Additional context**
I am not sure if this bug report belongs here or at Real Media Library. At the moment the issue report has been posted both to RML and Gutenberg.

### PR DESCRIPTION
**Pull request by youknowriad**
This PR follows the core-js meeting and replaces the wp.apiRequest with a new wp.fetch module not relying on jQuery APIs but using `window.fetch`

**Differences**:

 - Returning regular promises
 - If you want to receive the entire response you need to pass `parse: false`
 - To avoid data processing, you can pass `body` directly

**Remaining tasks**

 - Deprecate wp.apiRequest (I'm leaving it for later, we need to settle on the deprecation strategy first)

closes #7488 #7455 #7515

### CODE REVIEW

File: packages/fetch/src/index.js [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+import namespaceEndpointMiddleware from './middlewares/namespace-endpoint';
+import httpV1Middleware from './middlewares/http-v1';
+
+const middlewares = [];
+
+function registerMiddleware( middleware ) {
+	middlewares.push( middleware );
+}
+
+function request( options ) {
```
Comment (joyously) [inline packages/fetch/src/index.js]: Why is it called `request`? Does this map to `fetch` somewhere?

Comment (youknowriad) [reply packages/fetch/src/index.js]: It's just an internal name to avoid confusion with `window.fetch` (which can also be accessed by `fetch` since it's a global) used on the same file.

Comment (joyously) [reply packages/fetch/src/index.js]: Maybe it should have been called `apifetch` then. Or `wpfetch`.

File: editor/store/effects.js [hunk 2]
```diff
@@ -302,7 +302,7 @@ export default {
 		const { postId } = action;
 		const basePath = wp.api.getPostTypeRoute( getCurrentPostType( getState() ) );
 		dispatch( removeNotice( TRASH_POST_NOTICE_ID ) );
-		apiRequest( { path: `/wp/v2/${ basePath }/${ postId }`, method: 'DELETE' } ).then(
+		fetch( { path: `/wp/v2/${ basePath }/${ postId }`, method: 'DELETE' } ).then(
```
Comment (noisysocks) [inline editor/store/effects.js]: In the error handler for this request (line 317) we reference `err.responseJSON` which will now be undefined. We do this in most places that used `apiRequest`.

**Review by noisysocks — DISMISSED** [review]
Really supportive of this change—moving away from jQuery is 💯.

There's a few places where we're treating `response.json()` as a promise which will cause errors. For example, the latest posts block doesn't load when I check out this branch. We're also referencing `responseJSON` in quite a few error handlers which isn't right. (I haven't tested this, though.)

As a developer that's familiar with `fetch`, I find it a little confusing that `@wordpress/fetch` doesn't behave exactly the same as `window.fetch` unless you pass it `parse: false`. Maybe renaming it to `apiFetch` would help with this? Alternatively, we could move the "magic" that we do (JSON parsing and response status error handling) into a function that works on regular [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) objects.

**Comment by youknowriad** [comment]
> As a developer that's familiar with fetch, I find it a little confusing that @wordpress/fetch doesn't behave exactly the same as window.fetch unless you pass it parse: false. Maybe renaming it to apiFetch would help with this? Alternatively, we could move the "magic" that we do (JSON parsing and response status error handling) into a function that works on regular Response objects.

I guess I like the auto parsing to avoid repeating the same thing over and over again in all of our implementations. I think parsing is the default in 99% of use-cases, isn't it?

**Comment by tofumatt** [comment]
If it won't behave like fetch I think putting `fetch` in the name at all might be best avoided, but `apiFetch` is fine. Re-using `apiRequest` is better I think.

I definitely think we should be parsing by default; it's totally the standard use-case and it's handy to not have to worry about it! 👍

**Comment by youknowriad** [comment]
We can't reuse `apiRequest` for backwards compatibility. We can do `apiFetch` but I personally prefer just `fetch` and even without parsing the API is different. `window.fetch` expects two arguments while `wp.fetch` expects the `path` as part of the `options`, do you think we should change this?

**Comment by tofumatt** [comment]
The API is fine to me, but I think using `fetch` is confusing. It's for API requests and calling it `fetch` just invites confusion to me. I think avoiding confusion with `fetch` is worth it (yes, I know the API is different but for newer JS developers this could be confusing, and it's also just a bit strange to scan–also folks might assume our `fetch` is a shim rather than a different API). Also calling it `apiFetch` makes the purpose of the package clearer.

File: editor/store/effects.js [hunk 3]
```diff
@@ -94,6 +94,25 @@ export function removeProvisionalBlock( action, store ) {
...
+export const getErrorFromResponse = ( response ) => {
+	const getErrorFromBody = ( body ) => {
+		return body || {
+			code: 'unknown_error',
+			message: __( 'An unknown error occurred.' ),
+		};
+	};
+	return response.json()
+		.then( getErrorFromBody )
+		.catch( () => getErrorFromBody() );
```
Comment (nerrad) [inline editor/store/effects.js]: I wonder if it would be more useful to have this utility function within the apiFetch package itself?

File: packages/api-fetch/README.md [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+	const start = Date.now();
+	const result = next( options );
+	result.then( () => {
+		console.log( 'The request took ' + Date.now() - start );
+	} );
+	return result;
+} );
+```
+
+The `api-fetch` package provides built-in middlewares you can use to provide a `nonce` and a custom `rootURL`.
```
Comment (nerrad) [inline packages/api-fetch/README.md]: Should the `preloading` and `namespace-endpoint` middlewares be mentioned here too?

File: components/higher-order/with-api-data/request.js [hunk 5]
```diff
@@ -80,12 +60,12 @@ export function getCachedResponse( request ) {
...
-		.then( ( body, status, xhr ) => {
-			return {
-				body,
-				headers: getResponseHeaders( xhr ),
-			};
+	const promise = apiFetch( { ...request, parse: false } )
+		.then( ( response ) => {
+			return response.json().then( ( body ) => ( {
+				body: body,
+				headers: response.headers,
```
Comment (aduth) [inline components/higher-order/with-api-data/request.js]: What is the shape of `response.headers` here ? Is it an object implementing the [`Headers` interface](https://developer.mozilla.org/en-US/docs/Web/API/Headers) ? That doesn't seem compatible with how this was previously shaped as a set of tuples.

File: editor/components/post-taxonomies/flat-term-selector.js [hunk 6]
```diff
@@ -104,27 +104,27 @@ class FlatTermSelector extends Component {
...
-			} ).then( resolve, ( xhr ) => {
-				const errorCode = xhr.responseJSON && xhr.responseJSON.code;
+		const basePath = wp.api.getTaxonomyRoute( this.props.slug );
+		// Tries to create a term or fetch it if it already exists
+		return apiFetch( {
+			path: `/wp/v2/${ basePath }`,
+			method: 'POST',
+			data: { name: termName },
+		} ).catch( ( response ) =>
+			response.json().then( ( body ) => {
```
Comment (aduth) [inline editor/components/post-taxonomies/flat-term-selector.js]: So in `.then` we receive a JSON payload by default ? But `.catch` we receive `response` always ? And in `.then` we have the option to receive `response` by passing `parse: false` ? Feels like an inconsistent developer experience.

File: packages/api-fetch/README.md (hunk 4 above)
Comment (aduth) [reply packages/api-fetch/README.md]: Also, how does one leverage said nonce and rootURL middlewares ?

File: packages/api-fetch/src/index.js [hunk 7]
```diff
@@ -0,0 +1,69 @@
...
+		return responsePromise
+			.then( checkStatus )
+			.then( parseResponse );
+	};
+	const steps = [
+		...middlewares,
+		namespaceEndpointMiddleware,
+		httpV1Middleware,
+		raw,
+	].reverse();
```
Comment (aduth) [inline packages/api-fetch/src/index.js]: I guess this is inherited, but why do we go through the effort to `Array#reverse` if we could already know what the result will be in assigning this array? i.e.

```js
const steps = [
	raw,
	httpV1Middleware,
	namespaceEndpointMiddleware,
	...middlewares,
];
```

**Review by aduth — COMMENTED** [review]
What do we do about https://www.npmjs.com/package/@wordpress/api-request ?

File: editor/components/post-taxonomies/flat-term-selector.js (hunk 6 above)
Comment (youknowriad) [reply editor/components/post-taxonomies/flat-term-selector.js]: Yes, what's the alternative you suggest? Try to parse the response in errors as well?

Comment (aduth) [reply editor/components/post-taxonomies/flat-term-selector.js]: That, or just abandon the auto-parse convenience. Consistency could have the bigger benefit.

Comment (youknowriad) [reply editor/components/post-taxonomies/flat-term-selector.js]: I personally prefer to keep the auto-parsing because of the duplication it can create. I'm fine with consistency between `then/catch`

Comment (noisysocks) [reply editor/components/post-taxonomies/flat-term-selector.js]: I think parsing error response bodies makes sense since this package is specifically designed to work with the WP REST API, which we know returns nicely formatted error responses:

```json
{
    "code": "rest_forbidden",
    "data": {
        "status": 401
    },
    "message": "Sorry, you are not allowed to do that."
}
```

Most error handling can then be as simple as:

```js
apiFetch( ... ).catch( ( { message } ) => {
	console.error( message );
} );
```

If we cannot parse the error response body (e.g. because of a connection issue), then we should throw a similarly shaped object, e.g.:

```js
{
    code: "unknown_error",
    message: "An unknown error occurred.",
}
```

File: components/higher-order/with-api-data/request.js (hunk 5 above)
Comment (youknowriad) [reply components/higher-order/with-api-data/request.js]: unless I'm missing something, I don't see it being used or exposed anywhere. I think it should be fine to remove entirely.

File: packages/api-fetch/src/index.js [hunk 8]
```diff
@@ -0,0 +1,95 @@
...
+		const parseResponse = ( response ) => {
+			return parse ? response.json() : response;
+		};
+
+		return responsePromise
+			.then( checkStatus )
+			.then( parseResponse )
+			.catch( ( response ) => {
+				if ( ! parse ) {
+					Promise.reject( response );
```
Comment (noisysocks) [inline packages/api-fetch/src/index.js]: We're missing a `return` here.

**Comment by youknowriad** [comment]
This should be ready to land if I can get another review :)

**Review by tofumatt — CHANGES_REQUESTED** [review]
I think the helper functions used in the `apiFetch` promise chain should be defined outside the function and I think there are some little cleanup things that need to happen here.

File: packages/api-fetch/src/middlewares/preloading.js [hunk 9]
```diff
@@ -32,15 +27,12 @@ const createPreloadingMiddleware = ( preloadedData ) => ( options, next ) => {
 			.join( '&' );
 	}
 
-	if ( typeof options.path === 'string' ) {
+	if ( typeof options.path === 'string' && options.parse !== false ) {
```
[the remark this answers is not in the document]
Comment (youknowriad) [reply packages/api-fetch/src/middlewares/preloading.js]: The idea is that it's clearer this way that it's opt-out and not opt-in. The default value allows us to change the condition but I think it's a little bit safer to check against false values on "opt-out" flags.

File: editor/store/test/effects.js [hunk 10]
```diff
@@ -755,10 +761,13 @@ describe( 'effects', () => {
...
-					expect( dispatch ).toHaveBeenCalledWith( {
-						type: 'SAVE_SHARED_BLOCK_FAILURE',
-						id: 123,
+				promise.catch( () => {
+					process.nextTick( () => {
+						expect( dispatch ).toHaveBeenCalledWith( {
+							type: 'SAVE_SHARED_BLOCK_FAILURE',
+							id: 123,
+						} );
+						done();
```
[the remark this answers is not in the document]
Comment (youknowriad) [reply editor/store/test/effects.js]: It was not possible on the initial implementation (I guess because of jQuery), I'll see if it's better now.

File: editor/components/post-taxonomies/flat-term-selector.js [hunk 11]
```diff
@@ -105,26 +105,24 @@ class FlatTermSelector extends Component {
...
+			method: 'POST',
+			data: { name: termName },
+		} ).catch( ( error ) => {
+			const errorCode = error.code;
+			if ( errorCode === 'term_exists' ) {
+				// search the new category created since last fetch
+				this.addRequest = apiFetch( {
+					path: `/wp/v2/${ basePath }?${ stringify( { ...DEFAULT_QUERY, search: termName } ) }`,
+				} );
+				return this.addRequest.then( ( searchResult ) => {
```
[the remark this answers is not in the document]
Comment (youknowriad) [reply editor/components/post-taxonomies/flat-term-selector.js]: I find that using `async/await` is not necessarily better when we use `.catch` because you end up with `await` inside try/catch and you also have to embed `try/catch` inside `try/catch` sometimes.

File: packages/api-fetch/src/index.js [hunk 12]
```diff
@@ -0,0 +1,95 @@
...
+		const responsePromise = window.fetch(
+			url || path,
+			{
+				...remainingOptions,
+				credentials: 'include',
+				body: body || JSON.stringify( data ),
+				headers,
+			}
+		);
+		const checkStatus = ( response ) => {
```
[the remark this answers is not in the document]
Comment (youknowriad) [reply packages/api-fetch/src/index.js]: parseResponse is not stateless, and I think creating inline function is not bad in terms of performance so I preferred consistency.

[the remark this answers is not in the document]
Comment (tofumatt) [reply packages/api-fetch/src/index.js]: Oh shoot, I missed that.

That makes sense; I find inline functions make a function a lot tougher to understand right away, but that's cool.

File: packages/api-fetch/src/middlewares/preloading.js (hunk 9 above)
[the remark this answers is not in the document]
Comment (tofumatt) [reply packages/api-fetch/src/middlewares/preloading.js]: Right, you need to pass `parse: false` to opt-out, that makes sense. But why not make the condition check `if ( typeof options.path === 'string' && options.parse ) {`?

I just find it easier to read that we're checking for true rather than for "not false".

**Review by tofumatt — APPROVED** [review]
Makes sense! I left a note about `options.parse` just because I think the conditional is weird and I'm still not huge on inline functions for readability. I'd be curious about the performance difference for such a frequently-used function. 🤔

Anyway, looks good!

File: packages/api-fetch/src/middlewares/preloading.js (hunk 9 above)
[the remark this answers is not in the document]
Comment (youknowriad) [reply packages/api-fetch/src/middlewares/preloading.js]: 👍 updating

[the remark this answers is not in the document]
Comment (youknowriad) [reply packages/api-fetch/src/middlewares/preloading.js]: Noting that if `options.parse` is undefined `options.parse` returns false but in the current condition it returns `true` so we have to assign a default value before simplifying the check.

[the remark this answers is not in the document]
Comment (tofumatt) [reply packages/api-fetch/src/middlewares/preloading.js]: Oh yeah, sorry, I should have said that; it was implied but I should've mentioned it explicitly. My bad 😞

I think that'll make the code easier to follow and the intent clearer as well. 👍

**Comment by youknowriad** [comment]
Thanks all for the reviews.

**Comment by youknowriad** [comment]
> What do we do about https://www.npmjs.com/package/@wordpress/api-request ?

We should probably just add a "deprecated" notice manually to the npm README

**Comment by gziolo** [comment]
@ntwb any hints, how we should proceed?

**Comment by aduth** [comment]
Running `npm run docs:build` on master after this merge produces some local changes:

```diff
diff --git a/docs/manifest.json b/docs/manifest.json
index 3efafeb88..66ae6255e 100644
--- a/docs/manifest.json
+++ b/docs/manifest.json
@@ -222,9 +222,9 @@
 		"parent": "packages"
 	},
 	{
-		"title": "@wordpress/api-request",
-		"slug": "packages-api-request",
-		"markdown_source": "https://raw.githubusercontent.com/WordPress/gutenberg/master/packages/api-request/README.md",
+		"title": "@wordpress/api-fetch",
+		"slug": "packages-api-fetch",
+		"markdown_source": "https://raw.githubusercontent.com/WordPress/gutenberg/master/packages/api-fetch/README.md",
 		"parent": "packages"
 	},
 	{
```

**Comment by youknowriad** [comment]
good catch @aduth forgot this one :)

**Comment by ntwb** [comment]
> What do we do about npmjs.com/package/@wordpress/api-request ?

> We should probably just add a "deprecated" notice manually to the npm README

> @ntwb any hints, how we should proceed?

I've just deprecated `@wordpress/api-request` on `npmjs.com`

If someone installs it they will see a notice:
> _"This package is deprecated, use @wordpress/api-fetch instead."_

**Comment by ntwb** [comment]
cc @gziolo @youknowriad ☝️

**Comment by gziolo** [comment]
Awesome, thanks!

File: packages/api-fetch/README.md [hunk 13]
```diff
@@ -0,0 +1,64 @@
+# @wordpress/api-fetch
+
+Wrapper around `window.fetch` to call WordPress REST APIs.
```
Comment (aduth) [inline packages/api-fetch/README.md]: Minor: Should we maybe be more explicit for general use that this _requires_ `Fetch` (and thus, a polyfill maybe required for older browsers?)

Comment (youknowriad) [reply packages/api-fetch/README.md]: yes, definitely, this makes me think we may need a consistent way to gather the required polyfills for each package. Better automated but It's probably not easy to automate.

Comment (aduth) [reply packages/api-fetch/README.md]: Related: #7159
