### PR TITLE
FIX: Use a `role="textbox"` for all the Editable elements 

### LINKED ISSUE #3412: Use a `role="textbox"` for all the Editable elements
The "editable" blocks use an element with `contenteditable`. Depending on the cases, this element can be a paragraph, a heading, a div, a figcaption...

Screen readers need to understand an element is an "editable text" element to correctly interact with it. Not surprisingly, browsers expose different information to assistive technologies and in turn assistive technologies have their own quirks.

TL:DR some browser / screen readers combinations don't work well without an explicitly set ARIA role. For example, JAWS 17 with Firefox on Windows doesn't understand a Gutenberg paragraph block is editable and doesn't automatically switch to "forms mode". Users can manually switch to forms mode when they need, and that can be done pressing Enter. However, pressing Enter in Gutenberg creates a new block so this won't work.

The result is the *complete inability to switch to forms mode, so it's impossible to enter content*.

A standard way to let screen readers understand an element has a semantics of editable text is using a `role="textbox"`.

Inputs and textareas don't need any role, since they already have the required semantics.

Multi-line elements should use `role="textbox"` and `aria-multiline="true`.
Single-line elements should use just `role="textbox"`.

To illustrate how browsers differ in exposing information through the accessibility API, see the screenshot below (using the Accessibility Viewer, a tool to explore a11y infos):

## Without role

Firefox exposes a Gutenberg editable paragraph like a paragraph (also notice the weird ARIA role img)

screenshot 114

IE 11 exposes it as "editable text", this explains why JAWS works nicely with IE and switches to forms mode:

screenshot 115

## With role=textbox

Firefox:

screenshot 116

IE 11:

screenshot 117

both browsers expose now a correct, consistent, information.

### PR DESCRIPTION
**Pull request by tg-ephox**
## Description

fixes https://github.com/WordPress/gutenberg/issues/3412

Whichever node TinyMCE wraps now has `role="textbox"`.

`aria-multiline="true"` is set for these node types `'p', 'ol', 'ul', 'table', 'pre', 'cite'`

I'm not 100% sure this is correct for the Paragraph block as Enter or Return will add a new Paragraph, as described [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_textbox_role).

## How Has This Been Tested?

Visually, inspecting elements for different Blocks

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: blocks/editable/index.js [hunk 1]
```diff
@@ -825,7 +827,7 @@ export default class Editable extends Component {
 			formatters,
 		} = this.props;
 
-		const ariaProps = pickAriaProps( this.props );
+		const ariaProps = { ...pickAriaProps( this.props ), 'aria-multiline': MULTI_LINE_TAGS.indexOf( Tagname ) > -1 };
```
Comment (aduth) [inline blocks/editable/index.js]: Should `aria-multiline` be dictated by `this.props.multiline` ?

**Review by aduth — COMMENTED** [review]
What do you think about my comment at https://github.com/WordPress/gutenberg/issues/3412#issuecomment-352557002 where I suggested maybe TinyMCE ought to be applying these attribute(s) automatically?

**Comment by tg-ephox** [comment]
@aduth we had some discussion internally believe that it is the responsibility of the tag author to supply its attributes.

File: blocks/editable/index.js (hunk 1 above)
Comment (tg-ephox) [reply blocks/editable/index.js]: `this.props.multiline` is undefined for a ParagraphBlock and is set to `li` for a ListBlock.  I looked at this prop first but it wasn't suitable for this purpose...

Comment (aduth) [reply blocks/editable/index.js]: Okay. I suspect future maintainers may have a similar reaction to mine in not understanding the difference between how `this.props.multiline` and `aria-multiline` are handled. Perhaps we could do for a code comment or documentation clarifying this.

**Review by aduth — COMMENTED** [review]
The `aria-multiline` attribute is a bit confusing to me. Based on the implementation here, it would make me question why it's not up to the browser or accessible device to infer multiline from a tag name. But then, for how we treat a paragraph block, is it indeed "multiline" ? It can have multiple lines via Shift-Enter, but based on my reading of [the `aria-multiline` specification](https://www.w3.org/TR/wai-aria/states_and_properties#aria-multiline), it would seem to be most relevant for describing the plain "Enter" behavior, in which case it's not accurate to say that the paragraph block is multiline, since pressing Enter creates a new separate `role="textbox"` element.

**Comment by tg-ephox** [comment]
>But then, for how we treat a paragraph block, is it indeed "multiline" ? It can have multiple lines via Shift-Enter, but based on my reading of the aria-multiline specification, it would seem to be most relevant for describing the plain "Enter" behavior, in which case it's not accurate to say that the paragraph block is multiline, since pressing Enter creates a new separate role="textbox" element.
@aduth that was my concern after reading the spec.  
@afercia should the Paragraph block have the `aria-multiline` attribute given that pressing Enter will add a new block?

File: blocks/editable/index.js (hunk 1 above)
Comment (tg-ephox) [reply blocks/editable/index.js]: I think the best approach would to re-name the multiline prop to something more appropriate, maybe `multilineTag` as this is how its used...

**Comment by afercia** [comment]
@tg-ephox to me `aria-multiline` is meant to distinguish an element that emulates an input field from an element that emulates a textarea:
`<div contenteditable role="textbox" ...` --> input field
`<div contenteditable role="textbox" aria-multiline-"true" ...` --> textarea

VoiceOver, for example, announces:
`edif text (pause) you are currently on a text field`
`edif text (pause) you are currently on a text area`

Test: https://codepen.io/afercia/full/goGPPN/

As per the Enter behavior, that's not standard in a textarea and is a bit controversial... since default behaviors should not be altered, ever.

**Comment by afercia** [comment]
Any news on this? 🙂

**Comment by afercia** [comment]
Worth noting since https://github.com/WordPress/gutenberg/commit/8ae2e8026afae63e725d7b6fd2191e801f67f336 the paragraph blocks have `aria-*` attributes typically used for autocompleters and thus they really need a `role` attribute too.

Even the W3C validator throws an error because of the missing role:
> Error: Element p is missing required attribute role.

**Comment by youknowriad** [comment]
This issues is required for the merge proposal, thus, I went ahead and updated the PR. Let me know how it looks now @afercia Thanks

**Comment by afercia** [comment]
@youknowriad thanks. I've tested extensively, also merging this with the navigation/edit mode #5709  and the role application #5807 to get an idea of how this change improves the screen readers behavior. 

It's definitely an improvement for all the blocks that can be considered similar to input fields or textareas, e.g.:
- heading
- paragraph 
- preformatted
- pullquote 
- quote
- verse

because they're really similar to inputs. It is also useful for blocks that are input sunder the hood, for example:
- button 
- text columns 

But, we should _not_ set the `role="textbox"` on blocks that are completely different from inputs or textareas:
- list: loses it snative semantics: number of items etc. are no longer announced
- table: same, the number of rows and columns are no longer announced, as well as the current position in the table

We should definitely exclude the list and table blocks, wondering if there's an elegant way to do that. Also wondering about blocks added b plugins, how would they declare if the block editable part needs a `role="textbox"` or not?

**Comment by youknowriad** [comment]
> We should definitely exclude the list and table blocks, wondering if there's an elegant way to do that. Also wondering about blocks added b plugins, how would they declare if the block editable part needs a role="textbox" or not?

If it's dependent on the TagName, I can add a rule saying that if the tagName is table, ul, ol, don't add the role, does that work?

**Comment by afercia** [comment]
Yes I've seen the tagName thing :) was just wondering if there's a more solid way. Alternatively, this should really be well documented for plugin authors. I'd say the tagName is OK for now? and maybe we can iterate later, if need be.

For completeness, also the various captions are OK (cover image, image, gallery, embed, etc.)

**Review by afercia — APPROVED** [review]

**Comment by afercia** [comment]
🎉
