### PR TITLE
Template editor: only disable the save button if no changes rather than hiding it 

### LINKED ISSUE #47882: Site Editor: global Save button shows up when not needed
### Description

It appears the 'global' Save button added to the Site editor sidebar in https://github.com/WordPress/gutenberg/pull/47142 shows up unexpectedly in some flows where it's not actually needed.

In the 'browse mode' templates list, users can take some actions. For example they can:
- Rename a custom template.
- Clear customizations made to a template.

When taking these actions, the 'Save' button appears in the 'saving' state at the bottom of the sidebar. Screenshot:

Screenshot 2023-02-08 at 14 18 41

For better clarity, here's an animated GIF:

save-button-sidebar

The global Save button makes perfectly sense for the scenarios illustrated in https://github.com/WordPress/gutenberg/pull/47142 and https://github.com/WordPress/gutenberg/issues/46985

I'm not sure it should show up at all when saving changes from the templates list. That's totally unexpected and confusing for users. I'm guessing this potentially happens for all the flows where there's a similar saving process.

Cc @youknowriad 

### Step-by-step reproduction instructions

- Go to the Site Editor.
- Create a custom template.
- Switch back to 'browse' more and click Templates > Manage all templates.
- From the templates list, click the 'Actions' button related to the custom template you created.
- Choose 'Rename', set a new name for the template and save.
- Observe that while saving, the global 'Save' button unexpectedly shows up in the Sidebar and the button is in the 'saving' state.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by glendaviesnz**
## What?
Makes the save button always visible, but disabled if no changes, rather than hiding it.

## Why?
There are accessibility issues with adding and removing the save button from the DOM, and this change makes it behave the same as the Save buttons in the Site and Post editor.

Also, currently the buttons saving state suddenly shows when saves have been initiated from other places, eg. the template rename dialog - this change avoids this confusion. 

Fixes: #47882

## How?
Always shows the button rather than only for an isDirty state.

## Testing Instructions

- In the Template Editor/Browse pages check that the 'Save' button is visible but disabled if no changes
- In the site editor make some changes to global style settings, eg. background color
- Return to the site editor browse mode without saving and make sure the save button is now enabled and works as expected

## Screenshots or screencast 

Before:

https://user-images.githubusercontent.com/3629020/217946606-7156e058-9031-4fbc-8c42-6df6cb1dc0da.mov

After:

https://user-images.githubusercontent.com/3629020/217946676-ba953520-8915-40fa-a69e-9cbfd896b8e7.mov

After with template change save:

https://user-images.githubusercontent.com/3629020/217949940-404f4965-f485-43bf-833d-c658c6e5d718.mov

### CODE REVIEW

File: packages/edit-site/src/components/save-button/index.js [hunk 1]
```diff
@@ -32,29 +37,43 @@ export default function SaveButton() {
...
-			isBusy={ isSaving }
-			onClick={ disabled ? undefined : () => setIsSaveViewOpened( true ) }
-			label={ label }
-			/*
-			 * We want the tooltip to show the keyboard shortcut only when the
-			 * button does something, i.e. when it's not disabled.
-			 */
-			shortcut={ disabled ? undefined : displayShortcut.primary( 's' ) }
-			/*
+		showButton && (
```
Comment (kevin940726) [inline packages/edit-site/src/components/save-button/index.js]: Let's short-circuit it so that it's easier to follow?

```js
if ( ! showButton ) {
  return null;
}
```

File: packages/edit-site/src/components/save-button/index.js [hunk 2]
```diff
@@ -6,13 +6,18 @@ import { Button } from '@wordpress/components';
...
 
 /**
  * Internal dependencies
  */
 import { store as editSiteStore } from '../../store';
 
 export default function SaveButton() {
+	// We only want to show the saving state of the button if the button itself initiated the save,
+	// otherwise, the button will show in the side bar when saving is initiated from template save models, etc.
+	const [ selfInitiatedSave, setSelfInitiatedSave ] = useState( false );
```
Comment (kevin940726) [inline packages/edit-site/src/components/save-button/index.js]: I'm not sure if this is the _right_ approach, as we're relying on the parent component to "remount" the save button to reset the state. At the time, it seems to be the case in the sidebar, as we'll not mount the button if `isDirty` is false. However, this breaks the editor that it'll not show the save button when first entering the editor 🤔 .

Comment (kevin940726) [reply packages/edit-site/src/components/save-button/index.js]: Seems like a lot of the `template-revert` e2e tests are failing randomly because the save button is sometimes not present 😅 .

**Comment by alexstine** [comment]
You cannot hide the save button from the DOM completely. I can already hear the accessibility issues without even testing the PR. Consider disabling the button instead but not removing it from the DOM.

Thanks.

File: packages/edit-site/src/components/save-button/index.js (hunk 2 above)
Comment (glendaviesnz) [reply packages/edit-site/src/components/save-button/index.js]: Yeh, I thought this was a flakey fix, so I am glad it made the tests flakey to prove that 😆 I will take another look at some different approaches, let me know if you have any ideas.

**Comment by glendaviesnz** [comment]
> Consider disabling the button instead but not removing it from the DOM.

@alexstine  I have redone the PR so that the button is always visible but disabled, so now behaves the same way as the Save buttons in the Post and Site editor. I thinks this also fixes the issue noted in https://github.com/WordPress/gutenberg/issues/47882 as the button isn't now suddenly appearing for no reason.

I have asked for some design feedback though as it feels like the placement isn't quite right if the button is permanently there.

**Review by alexstine — APPROVED** [review]
@glendaviesnz Code and accessibility look good. This is good to go pending design feedback.

**Review by kevin940726 — APPROVED** [review]
Same as @alexstine, code looks good, let's see if the design is ok too. 👍

**Comment by youknowriad** [comment]
I think this needs some design review as well. cc @jasmussen @jameskoster

**Comment by youknowriad** [comment]
I'd like to ask to be added as a reviewer to all the PRs that target the site editor on going work. That would be appreciated. Thank you.

**Comment by jameskoster** [comment]
When there are unsaved changes could we keep the disabled button in the DOM but visually hide it?

**Comment by alexstine** [comment]
@jameskoster This would be difficult considering the button would need to appear visually on focus. Generally disabled buttons cannot gain focus but we have made a work-around for our disabled buttons in Gutenberg. Just do not want it to be confusing if a user tabs to a disabled button and it suddenly appears visually.

I am also still confused why the big thing in this project is hiding/showing things all the time. That would drive me nuts as a sighted person always looking for something that is not there because I did not complete some pre-condition.

Just my take, thanks.

**Comment by jameskoster** [comment]
> That would drive me nuts as a sighted person always looking for something that is not there because I did not complete some pre-condition.

It's definitely a fine balance... the site editor is fairly advanced and exposing all the tools all the time can be overwhelming. I don't think it's unhealthy to consider disclosing certain parts of the UI contextually.

That said, saving is a very established and familiar concept, so it's probably okay to display it permanently, even when disabled. This would open the door for us to include related affordances here (e.g. access to revisions) in the future as well.

**Comment by glendaviesnz** [comment]
> That said, saving is a very established and familiar concept, so it's probably okay to display it permanently, even when disabled

@jameskoster should we go ahead and merge this then?

**Review by aristath — APPROVED** [review]

**Review by jameskoster — APPROVED** [review]
Yes I think so.

**Comment by DaisyOlsen** [comment]
@glendaviesnz would you this more bug or more enhancement? I'm working on prepping labels for the changelog before tomorrow's RC. Both labels are applied at present.

**Comment by ntsekouras** [comment]
@DaisyOlsen I took the liberty to classify it as a11y bug fix 😄

**Comment by ntsekouras** [comment]
I just cherry-picked this PR to the wp/6.2 branch to get it included in the next release: 36dcb00e72

**Comment by mtias** [comment]
I don't think this is a great solution. The save button (at this higher level of the interface) is an affordance only relevant for when a user is making changes across templates, styles, navigation, and so forth. Displaying it so prominently all the time is a considerable distraction and potentially misleading (a single disabled big blue button can be mistaken as active, and draw attention to it). This item is meant to contextually explain what is going on, and it's failing to do that at the moment. If we need to define a permanent area to contain it we should explore other alternatives, like a collapsed panel when there is nothing to be saved, auto-expanded when there is, and always focusable. Alternatively, the disabled state should not be that of a primary button in this context, it could instead read when the last saved happened, with access to revisions, etc.
