### PR TITLE
Edit Post: Make sidebar header focusable for button focus normalization

### LINKED ISSUE #20759: (Firefox) "Open Document Settings" region visible after closing sidebar
## Steps to reproduce

1. Open the sidebar with either Document or Block settings selected.
1. Close it using the X sign to the right from the _Document_ and _Block_ tabs.
**Observed:** the little _Open document settings_ region is visible.

Note that the same doesn’t happen when closing the sidebar by clicking on the cog icon

## Screencast

firefox-toggle-sidebar

## Environment

Firefox 74 (stable), macOS Catalina.

### PR DESCRIPTION
**Pull request by aduth**
Fixes #20759

This pull request seeks to resolve an issue where clicking the "Close Sidebar" in Firefox for macOS has two problems:

- Focus will not be returned to the corresponding header toolbar toggle button
- The "Open document settings" panel at the bottom of the sidebar remains visible

There are a number of contributing factors here, all of which ultimately stem from a [particular browser quirk](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus) in how Firefox for macOS treats clicks on button elements. Essentially, the problem is that clicking the sidebar dismiss button never registers as the sidebar ever having received focus, so it does not know to either return focus to the header, nor to dismiss the bottom panel of the sidebar.

In other browsers, the normal expected behavior is:

1. A click on the button bubbles as a focus event captured on `withFocusReturn` state:

https://github.com/WordPress/gutenberg/blob/d4f159a3da0738aa045e9969dba2c6c13a7f6a8d/packages/components/src/higher-order/with-focus-return/index.js#L105-L108

2. When the (inner) sidebar component is unmounted, it runs the focus return logic if focus was within. This is where Firefox fails, because at this point it does not consider focus as being within the element.

https://github.com/WordPress/gutenberg/blob/d4f159a3da0738aa045e9969dba2c6c13a7f6a8d/packages/components/src/higher-order/with-focus-return/index.js#L73-L84

3. The implementation of the sidebar explicitly shifts focus to the header toolbar toggle button, having the dual effect of shifting focus to a meaningful fallback, and hiding the sidebar panel.

https://github.com/WordPress/gutenberg/blob/d4f159a3da0738aa045e9969dba2c6c13a7f6a8d/packages/edit-post/src/components/sidebar/index.js#L33-L41

There is some prior art to this proposed solution, specifically in how the sibling inserter captures focus via click on the inserter button:

https://github.com/WordPress/gutenberg/blob/d4f159a3da0738aa045e9969dba2c6c13a7f6a8d/packages/block-editor/src/components/block-list/insertion-point.js#L166-L172

**Testing Instructions:**

Repeat Steps to Reproduce from #20759, verifying that the panel at the bottom of the sidebar no longer remains visible, and that focus is shifted to the sidebar toggle button in the header toolbar.

### CODE REVIEW

File: packages/edit-post/src/components/sidebar/sidebar-header/index.js [hunk 1]
```diff
@@ -23,6 +23,14 @@ const SidebarHeader = ( { children, className, closeLabel } ) => {
 	);
 	const { closeGeneralSidebar } = useDispatch( 'core/edit-post' );
 
+	// The `tabIndex` serves the purpose of normalizing browser behavior of
+	// button clicks and focus. Notably, without making the header focusable, a
+	// Button click would not trigger a focus event in macOS Firefox. Thus, when
+	// the sidebar is unmounted, the corresponding "focus return" behavior to
+	// shift focus back to the heading toolbar would not be run.
+	//
+	// See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus
```
Comment (youknowriad) [inline packages/edit-post/src/components/sidebar/sidebar-header/index.js]: I know we tried this before but forgot the conclusion, why don't we try to normalize it on the Button click handler (or related events).

Comment (youknowriad) [reply packages/edit-post/src/components/sidebar/sidebar-header/index.js]: Asking cause it's not the first time we have the button click focus issues and certainly not the last time.

**Review by youknowriad — APPROVED** [review]

File: packages/edit-post/src/components/sidebar/sidebar-header/index.js (hunk 1 above)
Comment (aduth) [reply packages/edit-post/src/components/sidebar/sidebar-header/index.js]: I've been thinking about this as well.

I think one of the main reluctances I'd have is in _breaking expectations_ about how elements are expected to work, but I'm not sure how well this holds up:

- The abstraction of a button shouldn't necessarily be known to be tied to expectations around a particular HTML element.
- The "expected" behavior is clearly not very _expected_, or at least it's highly inconsistent between browsers and consequently prone to error.

On the technical front, I've been wondering as well just how this would work:

- If we dispatch a `new window.Event`, how well does would it interoperate with React's event system, and in particular with [portaled](https://reactjs.org/docs/portals.html) rendering which can't rely on DOM event bubbling.

I've also been thinking about a few other options:

- Is `<input type="button">` susceptible to this as well? And if not, could we implement `<Button>` this way? I expect by virtue of the differences between the two (largely ability to use non-text HTML content in `<button>`), it may be infeasible.
- What about something like `<span role="button">` ? As I understand it, there are a lot of accessibility challenges in using `role="button"` effectively, but if it were technically possible, we could absorb that complexity into the implementation of the core component.

Comment (youknowriad) [reply packages/edit-post/src/components/sidebar/sidebar-header/index.js]: I think @diegohaz might have good thoughts on this problem as something he probably already faced with reakit

Comment (diegohaz) [reply packages/edit-post/src/components/sidebar/sidebar-header/index.js]: On Reakit we opted to ensure consistency across browsers on a `Tabbable` component (which is used by `Button`): https://github.com/reakit/reakit/blob/c9f55d7d87f12b58ee409e8a392a9c36c2aadf52/packages/reakit/src/Tabbable/Tabbable.ts#L141-L148

It's important to note that, on Firefox/macOS, calling `preventDefault()` there also prevents it to get the `:active` state when clicked (https://github.com/reakit/reakit/issues/432). Something like `data-active` could be used instead. That's the only bad side-effect people noticed so far.

Comment (aduth) [reply packages/edit-post/src/components/sidebar/sidebar-header/index.js]: @diegohaz Thanks for sharing! It hadn't occurred to me as potentially being as simple as calling `.focus()` on the button node. About the implementation and your point about `preventDefault`: Can you explain why `preventDefault` is necessary at all?

Comment (diegohaz) [reply packages/edit-post/src/components/sidebar/sidebar-header/index.js]: That's because Safari/Firefox on macOS will blur the button if it has focus on mouse down. `preventDefault` prevents that from happening. But there may be another way to work around that.
