### PR TITLE
Fix reusable block cancelling

### LINKED ISSUE #5719: Pressing Cancel while editing a reusable block does not reset the block preview
## Issue Overview
Pressing _Cancel_ while editing a reusable block should discard any unsaved changes that have been made to that block.

## Steps to Reproduce (for bugs)
1. Insert a reusable block
2. Select it and click _Edit_
3. Make some changes to the block
4. Click _Cancel_

## Expected Behavior
The block should return to how it looked before _Edit_ was clicked.

## Current Behavior
The block retains the changes made in step 3, which does not reflect how the post will look once published or previewed.

## Possible Solution
The changes to the referenced block's attributes should be kept in local state until _Save_ is clicked, i.e. [revert this recent change.](https://github.com/WordPress/gutenberg/pull/5228/files#diff-73aa07c726a1d65d06d6a64039e659ecL62)

## Screenshots / Video

regression

## Related Issues and/or PRs
This regression was introduced by https://github.com/WordPress/gutenberg/pull/5228.

### PR DESCRIPTION
**Pull request by noisysocks**
dog

Makes it so that pressing Cancel while editing a reusable block discards any unsaved changes that have been made to that block.

This fixes #5719, which is a regression introduced by https://github.com/WordPress/gutenberg/pull/5228.

### To test:

1. Insert a reusable block
2. Select it and click Edit
3. Make some changes to the block
4. Click Cancel
5. The block should appear how it did before you edited it

### CODE REVIEW

File: blocks/library/block/index.js [hunk 1]
```diff
@@ -30,6 +30,7 @@ class ReusableBlockEdit extends Component {
 		this.state = {
 			isEditing: !! ( reusableBlock && reusableBlock.isTemporary ),
 			title: null,
+			attributes: null,
```
Comment (aduth) [inline blocks/library/block/index.js]: I think the name of the state property could be improved to better indicate that it's the _transient_ updates which have yet to be saved. Otherwise it's a bit difficult to discern the difference between `this.state.attributes` and `this.props.block.attributes`.

File: blocks/library/block/index.js [hunk 2]
```diff
@@ -40,46 +41,53 @@ class ReusableBlockEdit extends Component {
...
 	}
 
 	setAttributes( attributes ) {
-		const { updateAttributes, block } = this.props;
-		updateAttributes( block.uid, attributes );
+		this.setState( ( prevState ) => {
+			if ( prevState.attributes !== null ) {
+				return { attributes: { ...prevState.attributes, ...attributes } };
+			}
+			return null;
```
Comment (aduth) [inline blocks/library/block/index.js]: Is an explicit return value necessary here? Or could we drop this line altogether?

File: blocks/library/block/index.js [hunk 3]
```diff
@@ -40,46 +41,53 @@ class ReusableBlockEdit extends Component {
 	}
 
 	startEditing() {
-		const { reusableBlock } = this.props;
+		const { reusableBlock, block } = this.props;
 
 		this.setState( {
 			isEditing: true,
 			title: reusableBlock.title,
+			attributes: block.attributes,
```
Comment (aduth) [inline blocks/library/block/index.js]: Do we need to track all of the block's original attributes in state? Or could we simply track the state as the object which assigns into `block.attributes` as the base?

```js
this.setState( {
	attributes: {},
} );

// ... 

const attributes = { ...block.attributes, ...this.state.attributes };
```

Also has the added advantage that when we call `updateAttributes` in `save`, we're only applying the patch changes to state (likely to save a couple iterations when [aggregating into state value](https://github.com/WordPress/gutenberg/blob/030b562ed81b567806975a43900b18064ba12a8a/editor/store/reducer.js#L292) and maybe avoiding some false positives when [overriding state value for undo](https://github.com/WordPress/gutenberg/blob/030b562ed81b567806975a43900b18064ba12a8a/editor/store/reducer.js#L165)).

File: blocks/library/block/index.js (hunk 1 above)
Comment (noisysocks) [reply blocks/library/block/index.js]: 👌 fixed in 5a36e93ce.

File: blocks/library/block/index.js (hunk 2 above)
Comment (noisysocks) [reply blocks/library/block/index.js]: 👌 fixed in 5a36e93ce.

File: blocks/library/block/index.js (hunk 3 above)
Comment (noisysocks) [reply blocks/library/block/index.js]: 👌 fixed in 5a36e93ce.
