### PR TITLE
Fix the dataviews experiment locked fields position on toggle.

### LINKED ISSUE #74153: DataViews: lockedFields don't retain their position when toggling visibility
### Description

While working on #74147, @talldan noticed that if you toggle the Title field while the Media field is visible, then it jumps from its controlled position within the list, which looks a bit awkward, but also results in a focus loss when interacting via keyboard. I believe the cause is that we only lock the position of the fields when they're visible, but not when they're hidden:

https://github.com/WordPress/gutenberg/blob/804e44bc4a37b71e6b9901b9ae70b2976187803a/packages/dataviews/src/components/dataviews-view-config/properties-section.tsx#L69-L95

I can see the reasoning as it looks good when the locked visible fields are all at the top together. On balance, though, I think if we're forcing this order, then it might be better to retain that order irrespective of the status of the `isVisibleFlag`.

Also, previously the locked fields that didn't allow `enableHiding` had a lock icon, which is no longer present. I think that was an intentional removal by @youknowriad to simplify things, but I may be misremembering. Just mentioning it here in case it wasn't intentional. 

### Step-by-step reproduction instructions

To see it in practice, you can test with the media modal experiment:

Image

With this enabled, go to add a featured image to a post, then switch to the table view. Play around with toggling field visibility for the title field. 

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/98262602-768a-48d2-992e-d729e1206f2b

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by rutviksavsani**
## What?

Closes #74153 

## Why?
In this PR change, we are updating the logic where the locked fields will retain their position when toggling visibility and will be in consistent positions.

## How?
- Treat title, media, and description as a single ordered `lockedFields` list in `PropertiesSection`.
- Compute which of those locked fields are visible, then render them in a single `map` pass so their relative order never changes.

## Testing Instructions
1. Enable the Media Modal experiment (as in the issue description).
2. Open the post editor and add or edit a post.
3. Open the Featured Image (media modal) and switch to the table view.
4. Open the “Properties” panel.
5. Toggle the visibility of Title, Media, and Description:
   - Verify their order in the Properties list remains consistent (Title → Media → Description), regardless of visibility.
   - Verify the last remaining visible field cannot be hidden (either locked or regular).
6. Confirm that non-locked/regular fields still appear after the locked fields and can be shown/hidden as before.

### Testing Instructions for Keyboard
 Using the above instructions for the keyboard method should work fine as well.

### Before
https://github.com/user-attachments/assets/90cc0596-56ce-44eb-916b-025605a746fc

### After 
https://github.com/user-attachments/assets/aba4a49e-8a51-4e00-a5d6-fe543c706385

### CODE REVIEW

**Review by ntsekouras — COMMENTED** [review]
This LGTM, thanks! We need to add a changelog entry though :)

File: packages/dataviews/src/components/dataviews-view-config/properties-section.tsx [hunk 1]
```diff
@@ -126,32 +111,28 @@ export function PropertiesSection( {
...
-									onChangeView( {
-										...view,
-										[ isVisibleFlag ]: false,
-									} );
-								} }
-							/>
-						);
-					} ) }
+					{ lockedFields.map( ( { field, isVisibleFlag } ) => {
+						if ( ! isDefined( field ) ) {
```
Comment (ntsekouras) [inline packages/dataviews/src/components/dataviews-view-config/properties-section.tsx]: `lockedFields` are already being checked for a defined field, so we could remove this here, no?

Comment (rutviksavsani) [reply packages/dataviews/src/components/dataviews-view-config/properties-section.tsx]: Thanks for pointing that out,  I have removed the check and also added the change log entry.

Comment (ntsekouras) [reply packages/dataviews/src/components/dataviews-view-config/properties-section.tsx]: Thanks! Though you removed only the one extra check. In this loop the `field` should be defined and we should remove this one too.

File: packages/dataviews/src/components/dataviews-view-config/properties-section.tsx [hunk 2]
```diff
@@ -78,13 +78,16 @@ export function PropertiesSection( {
...
 	const visibleFieldIds = view.fields ?? [];
 	const visibleRegularFieldsCount = regularFields.filter( ( f ) =>
 		visibleFieldIds.includes( f.id )
 	).length;
 
-	let visibleLockedFields = lockedFields.filter(
+	const visibleLockedFields = lockedFields.filter(
 		( { field, isVisibleFlag } ) =>
 			// @ts-expect-error
 			isDefined( field ) && ( view[ isVisibleFlag ] ?? true )
```
Comment (ntsekouras) [inline packages/dataviews/src/components/dataviews-view-config/properties-section.tsx]: We don't need this `isDefined( field )` check here, right?

File: packages/dataviews/src/components/dataviews-view-config/properties-section.tsx [hunk 3]
```diff
@@ -78,13 +78,16 @@ export function PropertiesSection( {
 			field: descriptionField,
 			isVisibleFlag: 'showDescription',
 		},
-	].filter( ( { field } ) => isDefined( field ) );
+	].filter( ( { field } ) => isDefined( field ) ) as Array< {
```
Comment (ntsekouras) [inline packages/dataviews/src/components/dataviews-view-config/properties-section.tsx:81]: If we add the type here, can we remove it from `visibleLockedFields` below?

File: packages/dataviews/src/components/dataviews-view-config/properties-section.tsx (hunk 2 above)
Comment (rutviksavsani) [reply packages/dataviews/src/components/dataviews-view-config/properties-section.tsx]: Now, I caught it. Sorry for missing this earlier. Fixed this now.

File: packages/dataviews/CHANGELOG.md [hunk 4]
```diff
@@ -19,6 +19,7 @@
 - DataViews: Combined field alignment in table layout. [#73908](https://github.com/WordPress/gutenberg/pull/73908)
 - DataViews: Fix table row multiselection in Firefox [#73945](https://github.com/WordPress/gutenberg/pull/73945)
 - DataViews: `filterSortAndPaginate()` will ignore sorting on non-sortable fields [#73950](https://github.com/WordPress/gutenberg/pull/73950)
+ - DataViews: Fix locked fields order when toggling visibility in properties section. [#74326](https://github.com/WordPress/gutenberg/pull/74326)
```
Comment (ntsekouras) [inline packages/dataviews/CHANGELOG.md]: It seems there is an extra space at the begining of the line.

File: packages/dataviews/src/components/dataviews-view-config/properties-section.tsx [hunk 5]
```diff
@@ -126,32 +111,24 @@ export function PropertiesSection( {
...
-										[ isVisibleFlag ]: false,
-									} );
-								} }
-							/>
-						);
-					} ) }
+					{ lockedFields.map( ( { field, isVisibleFlag } ) => {
+						// @ts-expect-error
+						const isVisible = view[ isVisibleFlag ] ?? true;
+						const isLastVisibleLocked =
```
Comment (ntsekouras) [inline packages/dataviews/src/components/dataviews-view-config/properties-section.tsx]: We could avoid this `const` altogether. If we keep it, we should rename to something more descriptive, like `shouldDisableHiding`.

**Comment by ntsekouras** [comment]
Besides the last 2 small comments, this is ready to land. Thanks!

**Comment by rutviksavsani** [comment]
@ntsekouras Thanks for the patience, the final changes have been done.

**Review by ntsekouras — APPROVED** [review]
LGTM, thank you!
