### PR TITLE
RangeControl: Fix initialPosition to accept 0

### LINKED ISSUE #18610: Components: RangeControl: initialPosition 0 does not work
**Describe the bug**
Screen Shot 2019-11-19 at 9 06 11 AM

Setting the `initialPosition` of `0` does not work with `RangeControl`. When it is set to `0`, it is set to the middle instead.

**To reproduce**

Try the following code:
```jsx
<RangeControl
  initialPosition={ 0 }
  value={ null }
  label={ label }
/>
```

**Expected behavior**
Initial value to the `0`, if set to `0`.

**Additional context**

The reason for this issue is the ternary used to determine the `initialSliderValue`, specifically this part:

```
initialPosition || ''
```

Zero should be a valid value, but it is not when piped. I feel like the solution should be checking to see if the `initialPosition` is defined, rather than truthiness.

Example:

```js
const initialFallbackValue = ! isUndefined( initialPosition ) ?
  initialPosition : '';

const initialSliderValue = isFinite( currentInputValue ) ?
  currentInputValue : initialFallbackValue;
```

### PR DESCRIPTION
**Pull request by ItsJonQ**
## Description

Screen Shot 2019-11-19 at 9 13 12 AM

This update fixes the `initialPosition` prop for `RangeControl` to properly handle a value of `0`. Previously, the fallback value was checking for truthiness, which does not allow for `0` to work.

Being able to set the value to `0` is important with something like a range slider, as you may not have
an initial value, but you would like the slider to start from the very beginning (with an example range of 0-20).

## How has this been tested?

Tested in Storybook. Added new story specifically for this use case.

## Types of changes

This update changes how `RangeControl` handles `initialPosition` of `0`, if there are no values defined. This fix will impact all of the places where this scenario exists with `RangeControl`.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 

Resolves https://github.com/WordPress/gutenberg/issues/18610

### CODE REVIEW

File: packages/components/src/range-control/index.js [hunk 1]
```diff
@@ -64,9 +64,12 @@ function RangeControl( {
 			parseFloat( newValue )
 		);
 	};
+
+	const initialFallbackValue = ! isUndefined( initialPosition ) ?
```
Comment (jorgefilipecosta) [inline packages/components/src/range-control/index.js]: We are using isFinite for checking currentInputValue, would it make sense to use isFinite to check initialPosition too?

File: packages/components/src/range-control/stories/index.js [hunk 2]
```diff
@@ -37,6 +38,20 @@ export const _default = () => {
 	);
 };
 
+export const WithoutInitialValue = () => {
```
Comment (jorgefilipecosta) [inline packages/components/src/range-control/stories/index.js]: Should we can this InitialValueZero?

File: packages/components/src/range-control/index.js (hunk 1 above)
Comment (ItsJonQ) [reply packages/components/src/range-control/index.js]: Ah yes! That works. Thank you!

File: packages/components/src/range-control/stories/index.js (hunk 2 above)
Comment (ItsJonQ) [reply packages/components/src/range-control/stories/index.js]: Sure thing!

**Review by jorgefilipecosta — APPROVED** [review]
LGTM 👍
