### PR TITLE
Block Commenting: Add block-comments as a new post type support

### LINKED ISSUE #71642: Block Comenting: Add `block-comment` as a new post type support
## What problem does this address?

In #71643, we disabled the block commenting when postId is not a number, because the block commenting functionality doesn't work in the template or template part, which has a string value post id, such as `'twentytwentyfive//home'`.

That said, ideally, enabling block commenting should depend on whether the post type supports it, rather than on whether the post ID is an integer.

## What is your proposed solution?

Add `block-comment` as a new post type support. The block commenting should be enabled by default for built-in post types Post and Page.

### PR DESCRIPTION
**Pull request by t-hamano**
- Closes #71642
- Follow-up: #71643

## What?

This PR adds a new `'block-comments'` post type support to Page and Post.

## Why?

In #71643, we disabled the block commenting when postId is not a number, because the block commenting functionality doesn't work in the template or template part, which has a string value post id, such as 'twentytwentyfive//home'.
 That said, ideally, enabling block commenting should depend on whether the post type supports it, rather than on whether the post ID is an integer.

## How?

Adds a new `'block-comments'` post type support. I'm not sure which is better, `block-comments` or `block-comment`..

P.S. If the Block Commenting is stabilized and shipped into core, I plan to add new block support here directly.

https://github.com/WordPress/wordpress-develop/blob/da61a89ddebabc030db6a218ccac6d6a85f91fc3/src/wp-includes/post.php#L40

## Testing Instructions

Confirm that you can comment on a block in the post or page editor.
Confirm that you can NOT comment on a block in the template or template part, or pattern editor.

### CODE REVIEW

File: packages/editor/src/components/collab-sidebar/index.js [hunk 1]
```diff
@@ -339,11 +339,6 @@ export default function CollabSidebar() {
 		? AddCommentToolbarButton
 		: AddCommentButton;
 
-	// If postId is not a valid number, do not render the comment sidebar.
-	if ( ! ( !! postId && typeof postId === 'number' ) ) {
-		return null;
-	}
```
Comment (t-hamano) [inline packages/editor/src/components/collab-sidebar/index.js]: I'm wondering whether we should keep this code just to be safe.

File: lib/experimental/block-comments.php [hunk 2]
```diff
@@ -1,4 +1,18 @@
 <?php
+
+/**
+ * Adds support for block comments to the built-in post types.
+ *
+ * @return void
+ */
+if ( ! function_exists( 'gutenberg_block_comment_add_post_type_support' ) ) {
```
Comment (Mamaduka) [inline lib/experimental/block-comments.php]: There's no need for a `function_exists` check for the functions with `gutenberg_`.

File: packages/editor/src/components/collab-sidebar/index.js (hunk 1 above)
Comment (Mamaduka) [reply packages/editor/src/components/collab-sidebar/index.js]: I'm guessing eventually, the editor will support Block Comments for templates. It could be handy when collaborating on design.

That would mean selectors need to adapt to them, rather than just using early return.

**Review by Mamaduka — APPROVED** [review]
Thanks, @t-hamano!

I like the opt-in nature of this new support feature, and `block-comments` seems to be a good name.

Cc @swissspidy, you've worked on some recent post-type supports. Did we miss anything?

File: lib/experimental/block-comments.php (hunk 2 above)
Comment (t-hamano) [reply lib/experimental/block-comments.php]: Updated in 9d07a6b22828570ae4a64a8c44d0659e727e59d9

File: packages/editor/src/components/collab-sidebar/index.js (hunk 1 above)
Comment (t-hamano) [reply packages/editor/src/components/collab-sidebar/index.js]: I agree. Templates and template parts are also a type of post type and have a post ID, so technically, Block Comments should be able to support them.

**Comment by swissspidy** [comment]
Why is this a top level support and not a property of the editor support? That would make way more sense to me at first glance. Can't have block-comments without editor support.

**Comment by Mamaduka** [comment]
That's a good point, @swissspidy! The block comments don't work without the block editor.

@t-hamano, I think we also will need to update `Gutenberg_REST_Comment_Controller`, so that it accounts for disabled post type support.

File: packages/editor/src/components/header/index.js [hunk 3]
```diff
@@ -80,14 +83,23 @@ function Header( {
...
 			showIconLabels: getPreference( 'core', 'showIconLabels' ),
 			hasFixedToolbar: getPreference( 'core', 'fixedToolbar' ),
 			hasBlockSelection: !! getBlockSelectionStart(),
 			hasSectionRootClientId: !! getSectionRootClientId(),
+			supportsBlockComments:
+				_postType?.supports?.editor &&
+				Array.isArray( _postType.supports.editor ) &&
+				!! _postType.supports.editor.find(
+					( item ) => item?.[ 'block-comments' ] === true
+				),
```
Comment (Mamaduka) [inline packages/editor/src/components/header/index.js]: Not a blocker: We should consider updating the `PostTypeSupportCheck` to support nested keys.

Comment (t-hamano) [reply packages/editor/src/components/header/index.js]: Yes, I realized that checking the nested support key is complicated 😅

**Comment by t-hamano** [comment]
- In 543ab9708ab8bb7f5be4b85cb8550e3337bfa63e: Make block-comments part of editor support.
- In : f64cfefe5933b666b222f763c74fe79de99a9bf9: Update `Gutenberg_REST_Comment_Controller` to check whether the post type supports `block-comments`.

I would like to confirm under what conditions the block comment support is considered enabled. My understanding is as follows, but is it correct?

 ✅Block Comment is enabled:

```php
register_post_type(
	'post',
	array(
		// ...
		'supports' => array(
			'title',
			'editor' => array(
				'block-comments' => true,
			),
		),
	)
);
```

❌ Block Comment is disabled:

```php
register_post_type(
	'post',
	array(
		// ...
		'supports' => array( 'title', 'editor' ),
	)
);

register_post_type(
	'post',
	array(
		// ...
		'supports' => array( 'title' ),
	)
);

register_post_type(
	'post',
	array(
		// ...
		'supports' => array(
			'title',
			'editor' => array(
				'block-comments' => false,
			),
		),
	)
);
```

**Comment by swissspidy** [comment]
We could also say it's implicitly enabled unless explicitly disabled.

So `'supports' => array( 'title', 'editor' ),` would mean it's enabled

**Comment by Mamaduka** [comment]
@swissspidy, I think we want to make this feature opt-in and enable it only for Posts and Pages by default. The `'supports' => array( 'title', 'editor' )` would mean enabling it for any post type that supports the editor.

File: lib/experimental/class-gutenberg-rest-comment-controller.php [hunk 4]
```diff
@@ -110,6 +110,36 @@ public function create_item_permissions_check( $request ) {
...
+			return false;
+		}
+		if ( ! is_array( $supports['editor'] ) ) {
+			return false;
+		}
+		foreach ( $supports['editor'] as $item ) {
+			if ( is_array( $item ) && isset( $item['block-comments'] ) && true === $item['block-comments'] ) {
+				return true;
+			}
+		}
```
Comment (t-hamano) [inline lib/experimental/class-gutenberg-rest-comment-controller.php:142]: I have never used or tested nested support keys, but I didn't realize it would be so complicated to check for support.

Comment (Mamaduka) [reply lib/experimental/class-gutenberg-rest-comment-controller.php:142]: You can also use something like this: `isset` supports multi-dimensional arrays.

```php
isset( $supports['editor']['block-comments'] ) && true === $supports['editor']['block-comments']
```

P.S. Now that we've started using more nested support keys, maybe it's time to update the `post_type_supports` function to make checks easier.

Comment (t-hamano) [reply lib/experimental/class-gutenberg-rest-comment-controller.php:142]: Curiously, get_all_post_type_supports returns the following data:

```
array(11) {
  ["title"]=> bool(true)
  ["editor"]=> array(1) {
    [0]=> array(1) {
      ["block-comments"]=> bool(true)
    }
  }
  ["author"]=> bool(true)
  // ...
}
```

I was expecting data like this, but for some reason, I can't get the data in this format 🤔

```
array(11) {
  ["title"]=> bool(true)
  ["editor"]=> array(1) {
    ["block-comments"]=>  bool(true)
  }
  ["author"]=> bool(true)
  // ...
}
```

Comment (Mamaduka) [reply lib/experimental/class-gutenberg-rest-comment-controller.php:142]: Oh, you're right. That's an annoying data format.

**Comment by Mamaduka** [comment]
I just realized that `add_post_type_support` doesn't merge support sub-properties. The last call will override previous ones.

This could be problematic for our use cases, as the editor is beginning to manage some of its features through sub-property flags.

```php
add_action( 'init', function() {
	add_post_type_support( 'page', 'editor', array(
		'default-mode' => 'template-locked',
	) );

	// This second call will overwrite the first sub-support property instead of merging.
	add_post_type_support( 'page', 'editor', array(
		'block-comments' => true,
	) );
} );
```

**Review by adamsilverstein — APPROVED** [review]
Nice!

**Comment by t-hamano** [comment]
> I just realized that `add_post_type_support` doesn't merge support sub-properties. The last call will override previous ones.
> 
> This could be problematic for our use cases, as the editor is beginning to manage some of its features through sub-property flags.

Ideally, we may need to update the add_post_type_support() function so that the third argument (sub-properties) is automatically merged. However, for now, we may need to incorporate the subproperty merging logic ourselves into this PR, and I plan to work on that before merging this PR.

**Comment by t-hamano** [comment]
In 42025a0fbc01d98c9b7bf134e852ca62fac1a185, I made sure to explicitly merge the subproperties so that even if the consumer had predefined editor support subproperties, they wouldn't be overwritten.

File: packages/editor/src/components/header/index.js [hunk 5]
```diff
@@ -80,14 +83,22 @@ function Header( {
...
 			isPublishSidebarOpened: _isPublishSidebarOpened(),
 			showIconLabels: getPreference( 'core', 'showIconLabels' ),
 			hasFixedToolbar: getPreference( 'core', 'fixedToolbar' ),
 			hasBlockSelection: !! getBlockSelectionStart(),
 			hasSectionRootClientId: !! getSectionRootClientId(),
+			supportsBlockComments: Array.isArray( _postType?.supports?.editor )
+				? _postType.supports.editor.find(
+						( features ) => 'block-comments' in features
+				  )?.[ 'block-comments' ] === true
+				: false,
```
Comment (t-hamano) [inline packages/editor/src/components/header/index.js]: The logic remains the same, but the way it's written has been changed to fit this code style:

https://github.com/WordPress/gutenberg/blob/42025a0fbc01d98c9b7bf134e852ca62fac1a185/packages/editor/src/store/private-selectors.js#L255-L261

Comment (Mamaduka) [reply packages/editor/src/components/header/index.js]: Just merged the #71723, so we should be able to use `PostTypeSupportCheck` as initially proposed.

Comment (t-hamano) [reply packages/editor/src/components/header/index.js]: Updated in 0bbfecdbe34e334c8d07e033c2c8b1299c46def0

File: packages/editor/src/components/collab-sidebar/index.js (hunk 1 above)
Comment (Mamaduka) [reply packages/editor/src/components/collab-sidebar/index.js]: Should we keep this for now?

Comment (t-hamano) [reply packages/editor/src/components/collab-sidebar/index.js]: Yes, let's keep this just in case. Updated in ee85fcdab2fb14b8a7d6918db6cfae26a850c8a2

File: packages/editor/src/components/collab-sidebar/index.js [hunk 6]
```diff
@@ -361,7 +361,7 @@ export default function CollabSidebar() {
 		? resultComments.find( ( thread ) => thread.id === blockCommentId )
 		: null;
 
-	// If postId is not a valid number, do not render the comment sidebar.
+	// If postId is not a valid number, do not render the comment sidebar. 1Code has comments. Press enter to view.
```
Comment (Mamaduka) [inline packages/editor/src/components/collab-sidebar/index.js]:
```suggestion
	// If postId is not a valid number, do not render the comment sidebar.
```

This seems to be leftover.

**Comment by Mamaduka** [comment]
@t-hamano, are there any blockers here?

**Comment by t-hamano** [comment]
@Mamaduka I think there are no blockers. Are we good to merge this PR?

**Comment by Mamaduka** [comment]
@t-hamano, yes. Let's merge this.
