### PR TITLE
Raw Handling: Fix grok markdown pasting issues

### LINKED ISSUE #72468: Copying and pasting markdown from Grok fails to convert
Using WordPress 6.8.3 and Gutenberg 21.8.2, I tried to select "copy markdown" in Grok and paste it into the editor, only to have it fail in pasting:

https://github.com/user-attachments/assets/5939b336-0c19-4ad5-a28c-d4ee8fbcfade

### PR DESCRIPTION
**Pull request by annezazu**
## What?
Fixes markdown paste from Grok by expanding the `isPlain()` function to detect single non-semantic wrapper elements. I worked with @youknowriad and Claude on this :) 

 ## Why?
Closes #72468

When copying markdown from Grok using "copy markdown", the clipboard contains both plain text (with markdown syntax like `**bold**`, `### headers`) and HTML (a `<span>` wrapper with the same markdown text). Gutenberg was detecting the HTML wrapper and skipping markdown conversion, pasting the literal markdown syntax instead of converting it to blocks.

## How?
Expanded `isPlain()` in `packages/blocks/src/api/raw-handling/utils.js` to return `true` when:
- HTML contains only a single wrapper element (`span`)
- The wrapper has no semantic child elements (only text nodes and `<br>` tags)

This allows the markdown converter to run on the plain text content instead of using the HTML wrapper.

## Testing Instructions
  1. Go to Grok and generate some content with markdown formatting (headers, bold, lists, etc.)
  2. Click "copy markdown"
  3. Paste into the Gutenberg editor
  4. Verify that markdown converts to proper blocks (headings, paragraphs with bold text, lists)

### Before
Markdown syntax appears literally in paragraph blocks

### After
Markdown converts to proper block structure

### CODE REVIEW

File: packages/blocks/src/api/raw-handling/test/utils.js [hunk 1]
```diff
@@ -30,6 +30,41 @@ describe( 'isPlain', () => {
...
+		expect( isPlain( '<span>test</span>' ) ).toBe( true );
+		expect( isPlain( '<div>test</div>' ) ).toBe( true );
+		expect( isPlain( '<p>test</p>' ) ).toBe( true );
+	} );
+
+	it( 'should return true for single wrapper with styled content but no semantic tags', () => {
+		expect( isPlain( '<span style="color: red;">test</span>' ) ).toBe(
+			true
+		);
+		expect( isPlain( '<div class="wrapper">test</div>' ) ).toBe( true );
```
Comment (ellatrix) [inline packages/blocks/src/api/raw-handling/test/utils.js]: I think we should start with just checking spans. Plugins might create custom raw transforms that check class names on divs. For example they might transform `class="box"` to a box block.

Could you share an example of a piece of content that was pasted? It would be nice to create an integration test with that.

Comment (annezazu) [reply packages/blocks/src/api/raw-handling/test/utils.js]: Of course! Here's an example:

```
<meta charset='utf-8'><span style="color: rgb(255, 255, 255); font-family: Times; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: pre-wrap; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">WordPress is an **open-source content management system (CMS)** that powers over **43% of all websites on the internet** (as of 2025). It started in 2003 as a simple blogging tool and has evolved into a full-featured platform for building everything from personal blogs to enterprise-level e-commerce sites.

---

### **Two Flavors of WordPress**

| Feature | **WordPress.com** (Hosted) | **WordPress.org** (Self-Hosted) |
|--------|----------------------------|---------------------------------|
| **Hosting** | Managed by Automattic (no setup needed) | You host it on your own server (e.g., Bluehost, SiteGround) |
| **Cost** | Free tier + paid plans ($4–$45/month) | Free software + hosting costs (~$3–$10/month) |
| **Customization** | Limited (plugins/themes restricted on lower plans) | **Unlimited** (full PHP/code access) |
| **Best For** | Beginners, small blogs, quick setup | Developers, businesses, full control |

---

### **Key Features**

1. **Themes**  
   - 10,000+ free themes in the repository  
   - Premium themes (e.g., Astra, Divi, GeneratePress)  
   - Full-site editing (FSE) with **block themes** (Gutenberg)

2. **Plugins** (60,000+ free)  
   - **WooCommerce** → Turns WP into an online store  
   - **Yoast/Rank Math** → SEO  
   - **Elementor/Beaver Builder** → Drag-and-drop page builders  
   - **WP Rocket** → Caching/speed optimization

3. **Gutenberg Block Editor** (since 2018)  
   - Visual, block-based content creation  
   - Reusable blocks, patterns, full-site editing

4. **Multisite**  
   - Run multiple sites from one WP install (e.g., `blog.example.com`, `shop.example.com`)

---

### **Who Uses WordPress?**

- **Small sites**: Personal blogs, portfolios  
- **Big brands**: Microsoft News, BBC America, Sony Music, The White House  
- **E-commerce**: 40% of online stores (via WooCommerce)

---

### **Pros &amp; Cons**

| Pros | Cons |
|------|------|
| Free &amp; open-source | Requires maintenance (updates, backups) |
| Huge ecosystem (themes/plugins) | Can be slow without optimization |
| SEO-friendly out of the box | Security vulnerabilities if neglected |
| Beginner-friendly | Over-reliance on plugins can bloat sites |

---

### **Getting Started (Self-Hosted)**

1. Buy hosting + domain (e.g., **SiteGround** → $2.99/month)  
2. Install WordPress (1-click via cPanel)  
3. Pick a theme (e.g., **Astra**)  
4. Install essential plugins:  
   - Yoast SEO  
   - UpdraftPlus (backups)  
   - LiteSpeed Cache  

---

### **Fun Facts**
- The **WordPress REST API** powers headless CMS setups (React, Next.js frontends)  
- **Automattic** (company behind WP.com) is valued at **$7.5B**  
- WordPress releases are named after **jazz musicians** (e.g., "Gershwin" in 2025)

---

**TL;DR**: WordPress is the **world’s most popular website builder**—flexible, free, and powerful, but requires some TLC for security and speed.

Need help choosing between WordPress.com vs .org, or setting up a specific type of site (blog, store, portfolio)? Let me know!</span>
```

Comment (annezazu) [reply packages/blocks/src/api/raw-handling/test/utils.js]: Updated the test to address the feedback!

**Comment by ellatrix** [comment]
Looks like the added test is failing. Could you tell Claude to run the unit test and fix?

File: packages/blocks/src/api/raw-handling/test/paste-handler.js [hunk 2]
```diff
@@ -287,4 +287,33 @@ describe( 'pasteHandler', () => {
 		expect( result.name ).toEqual( 'core/video' );
 		expect( result.isValid ).toBeTruthy();
 	} );
+
+	it( 'can handle Grok markdown wrapped in a styled span', () => {
+		// Simulates pasting markdown from Grok, which wraps content in a styled span
+		const grokMarkdownHTML =
```
Comment (ellatrix) [inline packages/blocks/src/api/raw-handling/test/paste-handler.js]: This is not quite what I had in mind. There's a folder with HTML input and output that we use as integration tests. What I had in mind is just adding the the input and expected output to this folder. It can be found at `test/integration/fixtures/documents`.

Comment (annezazu) [reply packages/blocks/src/api/raw-handling/test/paste-handler.js]: Updated to include.

**Comment by annezazu** [comment]
Updated some of the tests.

File: packages/blocks/src/api/raw-handling/utils.js [hunk 3]
```diff
@@ -113,14 +113,49 @@ export function getBlockContentSchema( context ) {
...
+ * any elements that are not line breaks, or it only contains a single non-semantic
+ * wrapper element (span) with no semantic child elements.
  *
  * @param {string} HTML The HTML to check.
  *
  * @return {boolean} Whether the HTML can be considered plain text.
  */
 export function isPlain( HTML ) {
-	return ! /<(?!br[ />])/i.test( HTML );
+	// Existing check: no tags except <br>
```
Comment (ebinnion) [inline packages/blocks/src/api/raw-handling/utils.js]: I'd probably remove this and the new check comment below.

File: packages/blocks/src/api/raw-handling/utils.js [hunk 4]
```diff
@@ -113,14 +113,49 @@ export function getBlockContentSchema( context ) {
...
+		const childElements = Array.from( doc.body.children );
+		if ( childElements.length !== 1 ) {
+			return false;
+		}
+
+		const wrapper = childElements[ 0 ];
+		const tagName = wrapper.tagName.toLowerCase();
+
+		// Only consider non-semantic wrapper tags
+		if ( ! [ 'span' ].includes( tagName ) ) {
```
Comment (ebinnion) [inline packages/blocks/src/api/raw-handling/utils.js]: Since we removed the check for div and p, we can simplify here.

```suggestion
		if ( tagName !== 'span' ) {
```

File: packages/blocks/src/api/raw-handling/utils.js [hunk 5]
```diff
@@ -113,14 +113,49 @@ export function getBlockContentSchema( context ) {
...
+		const doc = document.implementation.createHTMLDocument( '' );
+		doc.body.innerHTML = HTML;
+
+		// Check if there's exactly one top-level element
+		const childElements = Array.from( doc.body.children );
+		if ( childElements.length !== 1 ) {
+			return false;
+		}
+
+		const wrapper = childElements[ 0 ];
```
Comment (tyxla) [inline packages/blocks/src/api/raw-handling/utils.js]: Since we don't do any advanced array manipulation, we could actually use `document.body.children` collection and avoid an extra variable + `Array.from()`:

```suggestion
		if ( doc.body.children.length !== 1 ) {
			return false;
		}

		const wrapper = doc.body.children.item(0);
```

**Comment by annezazu** [comment]
Alright. Updated this PR in light of the feedback on the tests:

- Removed unnecessary inline comments from isPlain function
- Added grok-markdown-in.txt fixture (plain text version for clipboard simulation)
- Updated grok-markdown-out.html fixture (corrected heading levels)
- Added grok-markdown to the integration test array
- Updated test snapshots

File: packages/blocks/src/api/raw-handling/utils.js [hunk 6]
```diff
@@ -113,14 +113,46 @@ export function getBlockContentSchema( context ) {
...
  *
  * @return {boolean} Whether the HTML can be considered plain text.
  */
 export function isPlain( HTML ) {
-	return ! /<(?!br[ />])/i.test( HTML );
+	if ( ! /<(?!br[ />])/i.test( HTML ) ) {
+		return true;
+	}
+
+	try {
```
Comment (ellatrix) [inline packages/blocks/src/api/raw-handling/utils.js]: I don't think there's anything that will throw an error in this block, so we should remove the try/catch. Even if something unexpectedly throws an error, I think it would be better to not suppress it so that it's clear to the user that something didn't work correctly and an error is logged in the console. I'm curious why it added a try/catch here though.

File: packages/blocks/src/api/raw-handling/utils.js (hunk 3 above)
Comment (ellatrix) [reply packages/blocks/src/api/raw-handling/utils.js]: Yes, this can be removed now.

Comment (ellatrix) [reply packages/blocks/src/api/raw-handling/utils.js]: The new check will also have to run for non-span wrapped content though, `hasSemanticChildren` can be moved to the start.

File: packages/blocks/src/api/raw-handling/utils.js (hunk 6 above)
Comment (annezazu) [reply packages/blocks/src/api/raw-handling/utils.js]: When asked, it said it was unnecessary defensive programming :)

File: packages/blocks/src/api/raw-handling/utils.js [hunk 7]
```diff
@@ -113,14 +113,41 @@ export function getBlockContentSchema( context ) {
...
+		return false;
+	}
+
+	// Check if the wrapper contains only text nodes and <br> tags
+	// (no other semantic elements)
+	const hasSemanticChildren = Array.from(
+		wrapper.getElementsByTagName( '*' )
+	).some( ( el ) => el.tagName.toLowerCase() !== 'br' );
+
+	return ! hasSemanticChildren;
```
Comment (mcsf) [inline packages/blocks/src/api/raw-handling/utils.js]: At the risk of overthinking, we could:

* avoid the copy (`Array.from`) for a test where we want to fail early
* avoid lower-casing the tag name, in comformity with other parts of `raw-handling` (same goes for `const tagName` a few lines above)


```suggestion
	// Check if the wrapper contains only text nodes and <br> tags
	// (no other semantic elements)
	const descendants = element.getElementsByTagName( '*' );
	for ( let i = 0; i < descendants.length; i++ ) {
		if ( descendants.item( i ).tagName !== 'BR' ) {
			return false;
		}
	}
	
	return true;
```

File: packages/blocks/src/api/raw-handling/utils.js (hunk 6 above)
Comment (mcsf) [reply packages/blocks/src/api/raw-handling/utils.js]: > When asked, it said it was unnecessary defensive programming :)

classic :)

File: packages/blocks/src/api/raw-handling/utils.js (hunk 7 above)
Comment (aduth) [reply packages/blocks/src/api/raw-handling/utils.js]: In the spirit of overthinking, you could probably go further and just look at `children`? Since you wouldn't have any nested children if you're only allowing `<br />` in the first place.


```suggestion
	// Check if the wrapper contains only text nodes and <br> tags
	// (no other semantic elements)
	for ( let i = 0; i < wrapper.children.length; i++ ) {
		if ( wrapper.children[ i ].tagName !== 'BR' ) {
			return false;
		}
	}

	return true;
```

Or let the browser do the work of filtering out text nodes and just look at the element children:


```suggestion
	let child = wrapper.firstElementChild;
	while ( child ) {
		if ( child.tagName !== 'BR' ) {
			return false;
		}

		child = child.nextElementSibling;
	}

	return true;
```

Comment (annezazu) [reply packages/blocks/src/api/raw-handling/utils.js]: Thank you for reviewing! Seems like there aren't any downsides so I committed your suggestion.

**Review by youknowriad — APPROVED** [review]
Let's land this.

**Comment by annezazu** [comment]
Thanks for all the help here, all.
