### PR TITLE
Fix block-based widget customizer initializing too soon

### LINKED ISSUE #30726: Blocks in Widget Customizer: Block editor doesn't load for some themes
## Description
When testing out some themes (Twenty Nineteen, Twenty Seventeen), the block based widget customizer isn't loading for me.

In the console, there's an error:
```
Uncaught TypeError: Cannot read property 'Section' of undefined
    at Module../packages/customize-widgets/build-module/controls/inspector-section.js
```

It seems that `wp.customize` (the object that has the `Section` property) is `undefined` causing initialization to fail.

## Step-by-step reproduction instructions
1. Enable the blocks in widget customizer experiment
2. Switch to one of the themes mentioned above
3. Try accessing the customize > widgets screen

## Expected behaviour
I can edit blocks

## Actual behaviour
The sidebar area is empty, the block editor doesn't load

## Screenshots or screen recording (optional)
Screenshot 2021-04-12 at 4 38 05 pm

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #30726

This fixes the issue, but there may be other, better options for fixing this. This was just a quick hack around at the end of a day, but will help demonstrate the issue.

### The bug
The customize-widgets 'app' uses `wp.domReady` to defer intialization:
https://github.com/WordPress/gutenberg/blob/82ddc9e405d91066eba6d08fb716ef8feea922ab/packages/customize-widgets/src/index.js#L37

However, there are still some imported files before that point that are executed immediately:
https://github.com/WordPress/gutenberg/blob/82ddc9e405d91066eba6d08fb716ef8feea922ab/packages/customize-widgets/src/index.js#L13-L14

Those files use `wp.customize`, which doesn't seem to be available at this point.

The fix I've made here is to move everything in those files to 'getter' functions so that they're also deferred.

## How has this been tested?
1. Enable the block widget customizer experiment
2. Set Twenty Seventeen as your theme
3. Open the customize > widgets screen

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by draganescu — APPROVED** [review]
This works and does not look like a hack but makes sense to not be so sure of globals being available.

**Comment by noisysocks** [comment]
This seems fine to me. Ideally `customize` would be something that we can `import` but it's not clear how we would do that short of moving the Customiser into the Gutenberg repo.

File: packages/customize-widgets/src/controls/inserter-outer-section.js [hunk 1]
```diff
@@ -4,117 +4,118 @@
 import { ESCAPE } from '@wordpress/keycodes';
 import { focus } from '@wordpress/dom';
 
-const {
-	wp: { customize },
-} = window;
+export default function getInserterOuterSection() {
```
Comment (noisysocks) [inline packages/customize-widgets/src/controls/inserter-outer-section.js:7]: Should we use `build` instead of `get`? `get` to me implies that it's a simple property access. I suppose it doesn't matter 😀
