### PR TITLE
Remove Text Columns block from insertion menus

### LINKED ISSUE #6506: Remove Text Columns block and convert existing ones to Columns + nested Paragraph blocks
## Issue Overview
The Text Columns blocks is pretty much useless. With the Columns block having been added, there is no reason for it to exist. It is not even responsive, so it does not work well at all on mobile. <del>On top of that, the block is currently full of bugs.</del>

When WordPress 5.0 is released, I do not think it makes sense to ship this block, since the Columns block does everything it does and more. Actually, I would not ship WordPress 5.0 with the Columns block as it is right now since it also lacks responsive columns. (See #6048.) If the Columns block does not have responsive columns by the merge proposal, then it may make more sense to just leave it out of WordPress 5.0 rather than ship a pretty much useless block, but in that case, it makes no sense to ship the Text Columns block either since it is even worse.

Is there any reason to keep this block anymore?

To test backwards compatibility with completely-removed blocks and also if backwards compatibility with older Gutenberg versions is desired at this point in development, Text Columns blocks could be converted to Columns blocks with nested Paragraph blocks.

## Related Issues and/or PRs
- #2651
- #4962

### PR DESCRIPTION
**Pull request by brandonpayton**
## Description
This is a simple PR to remove the Text Columns block from the block library and other insertion menus. It also prints a deprecation warning when loading a Text Columns block in the editor.

Closes #6506.
NOTE: It doesn't do everything called for in #6506 but follows Matías' direction on the issue and addresses the concern for the Try Gutenberg callout.

## How has this been tested?
* Ran unit and e2e tests.
* Loaded the editor and verified that the `core/text-columns` block is not present in the block library or the block autocompletion menu.
* Loaded a post with a pre-existing Text Columns block and observed that the block was loaded as a Text Columns block and editable.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: core-blocks/text-columns/index.js [hunk 1]
```diff
@@ -25,6 +26,9 @@ import './editor.scss';
 export const name = 'core/text-columns';
 
 export const settings = {
+	// Use an empty parent array to indicate this block should no longer be available for insertion.
+	parent: [],
```
Comment (noisysocks) [inline core-blocks/text-columns/index.js]: A more "official" way of doing this is to use `supports.inserter: false`. Up to you which way you go—they should be functionally equivalent 🙂

https://github.com/WordPress/gutenberg/blob/7ab5a9e8a6d07bb2d16e21fe2841e4619e64f0c1/core-blocks/block/index.js#L23-L27

File: core-blocks/text-columns/index.js [hunk 2]
```diff
@@ -64,6 +68,12 @@ export const settings = {
 	edit: ( ( { attributes, setAttributes, className } ) => {
 		const { width, content, columns } = attributes;
 
+		deprecated( 'The Text Columns block', {
+			version: 'a future version',
```
Comment (noisysocks) [inline core-blocks/text-columns/index.js]: `version` is an optional param, so we could just omit it entirely instead of being vague here.

**Review by noisysocks — APPROVED** [review]
It works! 🐩 

Should we remove the _(beta)_ from _Columns (beta)_?

File: core-blocks/text-columns/index.js (hunk 2 above)
Comment (noisysocks) [reply core-blocks/text-columns/index.js]: Oh—we should update `deprecated.md`.

File: core-blocks/text-columns/index.js (hunk 1 above)
Comment (gziolo) [reply core-blocks/text-columns/index.js]: Let's follow what we have for Shared block 👍

**Comment by SuperGeniusZeb** [comment]
@noisysocks I would wait until a basic solution for #6048 is implemented before removing the beta label from the Columns block.

File: core-blocks/text-columns/index.js (hunk 1 above)
Comment (brandonpayton) [reply core-blocks/text-columns/index.js]: That's much more explicit. I'll switch to that. Thanks for letting me know.
