### PR TITLE
[Widgets editor] Load custom block assets

### LINKED ISSUE #15644: Custom Blocks don't show up in Widgets
**Describe the bug**

Custom-created Blocks can't be accessed in the widget-editor (e.g. in the Footer)

**To reproduce**
1. Register custom block
2. Click on 'Gutenberg' --> 'Widgets'
3. Try to add a new block to any selection
4. Custom blocks don't show up

**Expected behavior**
Custom created blocks should be displayed and accessible.

**Screenshots**
Block selection of regular posts:
Bildschirmfoto 2019-05-15 um 12 04 37

Block selection of widgets:
Bildschirmfoto 2019-05-15 um 12 05 17

**Desktop**
 - OS: macOS10.14.4
 - Browser: all browsers

**Additional context**
- Gutenberg version: 5.7.0
- Wordpress version: 5.2

### PR DESCRIPTION
**Pull request by adamziel**
## Description
Fixes https://github.com/WordPress/gutenberg/issues/15644 by plugging into `should_load_block_editor_scripts_and_styles` filter and returning `true` on widgets editor screen.

Note that this PR will only fix the problem on latest WP trunk, but it won't break anything on older WP versions.

## How has this been tested?
1. Use latest WP trun
1. Apply this PR
1. Install and activate, let's say, the CoBlocks plugin
1. Go to the widgets editor, add a "map" block to any widget area
1. Confirm it worked

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: lib/widgets-page.php [hunk 1]
```diff
@@ -125,3 +125,21 @@ function gutenberg_widgets_init( $hook ) {
...
+
+/**
+ * Tells the script loader to load the scripts and styles of custom block on widgets editor screen.
+ *
+ * @param bool $is_block_editor_screen Current decision about loading block assets.
+ * @return bool Filtered decision about loading block assets.
+ */
+function widgets_editor_load_block_editor_scripts_and_styles( $is_block_editor_screen ) {
+	global $current_screen;
+	if ( 'appearance_page_gutenberg-widgets' === $current_screen->base ) {
```
Comment (TimothyBJacobs) [inline lib/widgets-page.php:137]:
```suggestion
	if ( 'appearance_page_gutenberg-widgets' === get_current_screen()->base ) {
```

File: lib/widgets-page.php [hunk 2]
```diff
@@ -125,3 +125,21 @@ function gutenberg_widgets_init( $hook ) {
...
 }
 add_action( 'admin_enqueue_scripts', 'gutenberg_widgets_init' );
+
+/**
+ * Tells the script loader to load the scripts and styles of custom block on widgets editor screen.
+ *
+ * @param bool $is_block_editor_screen Current decision about loading block assets.
+ * @return bool Filtered decision about loading block assets.
+ */
+function widgets_editor_load_block_editor_scripts_and_styles( $is_block_editor_screen ) {
```
Comment (noisysocks) [inline lib/widgets-page.php:135]: Convention says this should start with `gutenberg_` (e.g. `gutenberg_should_load_block_editor_scripts_and_styles`) because it's a function added by the Gutenberg plugin.

**Review by noisysocks — APPROVED** [review]
Looks good! Giving you the ✅ so you can merge after addressing mine and Timothy's small comments.

Are we able to use this new filter to simplify any of `gutenberg_widgets_init`? Or would we have to wait until Gutenberg requires WordPress 5.6?

**Comment by adamziel** [comment]
> Are we able to use this new filter to simplify any of gutenberg_widgets_init? Or would we have to wait until Gutenberg requires WordPress 5.6?

I don't think so, I believe the filter and `gutenberg_widgets_init` cover two disjoint sets of scripts and styles.

**Comment by adamziel** [comment]
Test failures seem to be caused by flakiness - they vary from run to run and seem to be unrelated to this PR. I'm merging.

**Comment by noahtallen** [comment]
I'm almost positive this PR introduced the test failure related to `entry-content` because:

- no commits on master in the past 5 days have failed for that reason
- every commit on master after this was merged has failed for that reason (until a different PR introduced a new e2e issue, at which point every commit was failing for _that_ reason.)

Also, locally, I get the error related to `entry-content` in my e2e test runner. But when I revert the merge commit from this PR, the error goes away.

So I did try including a revert of this PR in #25923, and while it made the `.entry-content` issue go away, I started getting other failures. 🤷 So I haven't done anything about it yet. So I thought I'd comment with my findings so far

**Comment by noahtallen** [comment]
I think this fixes it: #25935

**Comment by adamziel** [comment]
I believe what happened is that some of the failures I've seen were random and varied from rerun to rerun, while others were constant and caused by this PR - I totally missed the latter. When restarting selenium multiple time is the norm, I find it too easy to dismiss these failures. Thank you so much for fixing it @noahtallen ! 🙇

**Comment by noahtallen** [comment]
Totally! It also looks like the root issue was in WordPress core, so it was easy to miss locally unless the local environment was completely up to date.
