### PR TITLE
Extract theme json processor 

### LINKED ISSUE #26804: Protect against bad data in processing theme.json
Steps to reproduce the bug:

- edit `lib/global-styles.php` and add a new context that doesn't represent any block's selector. For example, by including a typo such as:

```js
"core/paragrah": { // Note the missing 'p'.
    "settings": {
        "color": {
            "custom": false
        }
    }
}
```

- load the front-end of the site and see the error message (you may have to activate WP_DEBUG).

### PR DESCRIPTION
**Pull request by oandregal**
This PR does a few things:

- Fixes https://github.com/WordPress/gutenberg/issues/26804

- Fixes block.json key retrieval: it's called `link` and not linkColor.

- Fixes one of the issues noted at https://github.com/WordPress/gutenberg/issues/26802 by sending through `__experimentalFeatures` and `__experimentalGlobalStylesBaseStyles` only the relevant data to the client. It fixes the root cause: how we normalize the schema.

- Extracts the first piece out of `global-styles.php`, so that it has a structure that helps us maintain, grow, test, and merge it into WP core. More to come in subsequent PRs. It was increasingly difficult to land a big PR with so many features and people working in parallel, so I think it's best to go step by step.

## How to test

- Activate an FSE-enabled theme. Example: [demo theme](https://github.com/nosolosw/global-styles-theme/).

**Test that the link color works as expected:**

- Go to the edit site and make some changes. For example to the link color.
- Edit some values and verify that they are updated in the editor. Save and go the front-end, verify that the styles reflect the changes.

**Test that it only passes the necessary data:** https://github.com/WordPress/gutenberg/issues/26802 for details

- Go to the site editor and verify that the `core/edit-site` store only holds the necessary data within `settings.__experimentalData`. Example:

Captura de ecrã de 2020-11-09 17-59-01

**Test that an invalid context doesn't break the site**  https://github.com/WordPress/gutenberg/issues/26804

- Edit `lib/global-styles.php` and add a new context that doesn't represent any block's selector:

```
"core/para": {
    "settings": {
        "color": {
            "custom": false
        }
    }
}
```

- Verify that the site still works as expected (no PHP errors reported).

### CODE REVIEW

**Comment by nosolosw** [comment]
I still need to fix some PHP linting issues, but it's now ready for review!

File: lib/class-wp-theme-json.php [hunk 1]
```diff
@@ -0,0 +1,953 @@
...
+	 *     'styles': {
+	 *       'color': {
+	 *         'link': 'color'
+	 *       }
+	 *     }
+	 *   }
+	 * }
+	 */
+	const SCHEMA = array(
+		'selector' => null,
```
Comment (jorgefilipecosta) [inline lib/class-wp-theme-json.php:58]: Specifying the schema pointing things can contain strings like selector to null seems strange.
What if specify in the same format to specify inputs for the rest API:
Example:
```
/**
 * Get our sample schema for comments.
 */
function prefix_get_comment_schema() {
    $schema = array(
        // This tells the spec of JSON Schema we are using which is draft 4.
        '$schema'              => 'http://json-schema.org/draft-04/schema#',
        // The title property marks the identity of the resource.
        'title'                => 'comment',
        'type'                 => 'object',
        // In JSON Schema you can specify object properties in the properties attribute.
        'properties'           => array(
            'id' => array(
                'description'  => esc_html__( 'Unique identifier for the object.', 'my-textdomain' ),
                'type'         => 'integer',
                'context'      => array( 'view', 'edit', 'embed' ),
                'readonly'     => true,
            ),
            'author' => array(
                'description'  => esc_html__( 'The id of the user object, if author was a user.', 'my-textdomain' ),
                'type'         => 'integer',
            ),
            'content' => array(
                'description'  => esc_html__( 'The content for the object.', 'my-textdomain' ),
                'type'         => 'string',
            ),
        ),
    );
 
    return $schema;
}
```

File: lib/class-wp-theme-json.php [hunk 2]
```diff
@@ -0,0 +1,953 @@
...
+	 *                   generate for the presets. Each class should have
+	 *                   the class suffix and the property name. Example:
+	 *
+	 *                   .has-<slug>-<class_suffix> {
+	 *                       <property_name>: <preset_value>
+	 *                   }
+	 */
+	const PRESETS_METADATA = array(
+		array(
+			'path'          => array( 'settings', 'color', 'palette' ),
```
Comment (jorgefilipecosta) [inline lib/class-wp-theme-json.php:139]: I guess the presets are for sure always inside settings. Could we assume that and not include settings as part of the path?

File: lib/class-wp-theme-json.php [hunk 3]
```diff
@@ -0,0 +1,953 @@
...
+					'class_suffix'  => 'font-size',
+					'property_name' => 'font-size',
+				),
+			),
+		),
+		array(
+			'path'          => array( 'settings', 'typography', 'fontFamilies' ),
+			'value_key'     => 'fontFamily',
+			'css_var_infix' => 'font-family',
+			'classes'       => array(
```
Comment (jorgefilipecosta) [inline lib/class-wp-theme-json.php:179]: All the presets after this line and including it. Should not include classes. Only colors, gradients, and font sizes have classes.

File: lib/class-wp-theme-json.php [hunk 4]
```diff
@@ -0,0 +1,953 @@
...
+			return self::$blocks_metadata;
+		}
+
+		self::$blocks_metadata = array();
+
+		$registry = WP_Block_Type_Registry::get_instance();
+		$blocks   = array_merge(
+			$registry->get_all_registered(),
+			array(
+				'global' => new WP_Block_Type(
```
Comment (jorgefilipecosta) [inline lib/class-wp-theme-json.php:372]: Would it make sense to move the global support definitions to constant, instead of having them in the constructor?

File: lib/class-wp-theme-json.php [hunk 5]
```diff
@@ -0,0 +1,953 @@
...
+	/**
+	 * Utility to extract a path from an array.
+	 *
+	 * @param array $array    Array we want to retrieve data from.
+	 * @param array $path     Array containing the path to retrieve.
+	 * @param array $default  Value to return if $array doesn't contain the $path.
+	 *
+	 * @return array Data at the given $path or $default.
+	 */
+	private function get_from_path( $array, $path, $default = array() ) {
```
Comment (jorgefilipecosta) [inline lib/class-wp-theme-json.php:582]: This function is the dash get equivalent? I guess we can use the existing one and avoid duplication? The function is also used by the server-side supports mechanism and will be part of the core even if internal for now.

File: lib/class-wp-theme-json.php [hunk 6]
```diff
@@ -0,0 +1,953 @@
...
+	/**
+	 * Normalize the subtree according to the given schema.
+	 * This function modifies the given input by removing
+	 * the nodes that aren't valid per the schema.
+	 *
+	 * @param string $key Key of the subtree to normalize.
+	 * @param array  $input Whole tree to normalize.
+	 * @param array  $schema Schema to use for normalization.
+	 */
+	private function process_key( $key, &$input, $schema ) {
```
Comment (jorgefilipecosta) [inline lib/class-wp-theme-json.php:472]: Why do we need to remove the nodes that aren't valid per the schema? When outputting CSS could we simply ignore these nodes?

File: lib/class-wp-theme-json.php [hunk 7]
```diff
@@ -0,0 +1,967 @@
...
+	 *   'value' => 'property_value,
+	 * )
+	 * ```
+	 *
+	 * Note that this modifies the $declarations in place.
+	 *
+	 * @param array $declarations Holds the existing declarations.
+	 * @param array $context Input context to process.
+	 */
+	private function compute_style_properties( &$declarations, $context ) {
```
Comment (jorgefilipecosta) [inline lib/class-wp-theme-json.php:655]: Should this function be static?

File: lib/class-wp-theme-json.php [hunk 8]
```diff
@@ -0,0 +1,967 @@
...
+	/**
+	 * Utility to extract a path from an array.
+	 *
+	 * @param array $array    Array we want to retrieve data from.
+	 * @param array $path     Array containing the path to retrieve.
+	 * @param array $default  Value to return if $array doesn't contain the $path.
+	 *
+	 * @return array Data at the given $path or $default.
+	 */
+	private function get_from_path( $array, $path, $default = array() ) {
```
Comment (jorgefilipecosta) [inline lib/class-wp-theme-json.php:589]: Should this function be static?

File: lib/class-wp-theme-json.php [hunk 9]
```diff
@@ -0,0 +1,967 @@
...
+	 * It also converts CSS Custom Property stored as
+	 * "var:preset|color|secondary" to the form
+	 * "--wp--preset--color--secondary".
+	 *
+	 * @param array $styles Styles subtree.
+	 * @param array $path Which property to process.
+	 *
+	 * @return string Style property value.
+	 */
+	private function get_property_value( $styles, $path ) {
```
Comment (jorgefilipecosta) [inline lib/class-wp-theme-json.php:616]: Should this function be static?

File: lib/class-wp-theme-json.php [hunk 10]
```diff
@@ -0,0 +1,967 @@
...
+	/**
+	 * Given a context, it extracts its presets
+	 * and adds them to the given input $stylesheet.
+	 *
+	 * Note this function modifies $stylesheet in place.
+	 *
+	 * @param string $stylesheet Input stylesheet to add the presets to.
+	 * @param array  $context Context to process.
+	 */
+	private function compute_preset_classes( &$stylesheet, $context ) {
```
Comment (jorgefilipecosta) [inline lib/class-wp-theme-json.php:690]: Should this function be static?

File: lib/class-wp-theme-json.php [hunk 11]
```diff
@@ -0,0 +1,967 @@
...
+	 *   'value' => 'property_value,
+	 * )
+	 * ```
+	 *
+	 * Note that this modifies the $declarations in place.
+	 *
+	 * @param array $declarations Holds the existing declarations.
+	 * @param array $context Input context to process.
+	 */
+	private function compute_preset_vars( &$declarations, $context ) {
```
Comment (jorgefilipecosta) [inline lib/class-wp-theme-json.php:733]: Should this function be static?

File: lib/class-wp-theme-json.php [hunk 12]
```diff
@@ -0,0 +1,967 @@
...
+	 *   'value' => 'property_value,
+	 * )
+	 * ```
+	 *
+	 * Note that this modifies the $declarations in place.
+	 *
+	 * @param array $declarations Holds the existing declarations.
+	 * @param array $context Input context to process.
+	 */
+	private function compute_theme_vars( &$declarations, $context ) {
```
Comment (jorgefilipecosta) [inline lib/class-wp-theme-json.php:762]: Should this function be static?

File: lib/class-wp-theme-json.php [hunk 13]
```diff
@@ -0,0 +1,967 @@
...
+	 *
+	 * To help debugging, will add some space
+	 * if SCRIPT_DEBUG is defined and true.
+	 *
+	 * @param string $selector CSS selector.
+	 * @param array  $declarations List of declarations.
+	 *
+	 * @return string CSS ruleset.
+	 */
+	private function to_ruleset( $selector, $declarations ) {
```
Comment (jorgefilipecosta) [inline lib/class-wp-theme-json.php:785]: Should this function be static?

File: lib/class-wp-theme-json.php [hunk 14]
```diff
@@ -0,0 +1,967 @@
...
+	 *   .has-value-gradient-background {
+	 *     background: value;
+	 *   }
+	 *
+	 * @param string $stylesheet Stylesheet to append new rules to.
+	 * @param array  $context Context to be processed.
+	 *
+	 * @return string The new stylesheet.
+	 */
+	private function to_stylesheet( $stylesheet, $context ) {
```
Comment (jorgefilipecosta) [inline lib/class-wp-theme-json.php:847]: Should this function be static?

File: lib/class-wp-theme-json.php (hunk 3 above)
Comment (nosolosw) [reply lib/class-wp-theme-json.php]: Ah, I missed font families don't generate classes. However, all the others do, as per what's in master https://github.com/WordPress/gutenberg/blob/master/lib/global-styles.php#L687 Updated (and added test!) at https://github.com/WordPress/gutenberg/pull/26803/commits/c0a958d20ea549016ff8758385f5a4dd87fba5fc

File: lib/class-wp-theme-json.php (hunk 6 above)
Comment (nosolosw) [reply lib/class-wp-theme-json.php:474]: Right, we can do validation at entering-time or at outputting-time. I chose to do it on entering because that simplifies all the internal code for processing the tree (stylesheet processing but also settings, etc). It's also safer, as we are strict on which things we allow and which things we don't, which is important in case attackers are able to hook into the theme.json in the server.

File: lib/class-wp-theme-json.php (hunk 2 above)
Comment (nosolosw) [reply lib/class-wp-theme-json.php:146]: I prefer to be explicit so all data is together. Removing settings from here means that all pieces of code that process the presets need to have that piece of info.

File: lib/class-wp-theme-json.php (hunk 7 above)
Comment (nosolosw) [reply lib/class-wp-theme-json.php:650]: I don't have a strong opinion on this, I'm fine marking them as static. I'm curious why it'd be preferred, though!

Comment (nosolosw) [reply lib/class-wp-theme-json.php]: https://github.com/WordPress/gutenberg/pull/26803/commits/718e367302cbb4d2c4b39eb7afb7b53e3c076a22

File: lib/class-wp-theme-json.php (hunk 5 above)
Comment (nosolosw) [reply lib/class-wp-theme-json.php]: It is! I wasn't sure what was its status given that you mentioned that it was marked as internal for the block supports, so I wasn't sure it was available any longer. Happy to do what you think is best.

File: lib/class-wp-theme-json.php (hunk 4 above)
Comment (nosolosw) [reply lib/class-wp-theme-json.php]: We can do so, yup https://github.com/WordPress/gutenberg/pull/26803/commits/d82db958e03204a7c381d0b3e1dbea2e086575a1

File: lib/class-wp-theme-json.php (hunk 1 above)
Comment (nosolosw) [reply lib/class-wp-theme-json.php:93]: You mean, adding type validation at the leaf node level?

It crossed my mind, and I think it'd be potentially helpful if connected with the logging mechanism for theme authors to see, which is something they have suggested they'd want. It can be useful, yes, but perhaps can be added in a subsequent PR? Would love to land this one quickly to unblock some work, let other people use this, and avoid many rebases (which are going to be / already were quite painful and time-consuming).

File: lib/class-wp-theme-json.php (hunk 5 above)
Comment (jorgefilipecosta) [reply lib/class-wp-theme-json.php]: It is marked as internal in the core. But I guess we can still use it in Gutenberg. And even in core, it will be public as I think it is a useful function (we just need more code showing its usefulness). I think for now in this PR we should just use the function we already have on Gutenberg and avoid duplicating it.

File: lib/class-wp-theme-json.php (hunk 7 above)
Comment (jorgefilipecosta) [reply lib/class-wp-theme-json.php]: I think it is a good practice to have all the functions that don't depend on the instance of a class marked as static.

File: lib/class-wp-theme-json.php (hunk 1 above)
Comment (jorgefilipecosta) [reply lib/class-wp-theme-json.php:93]: Yah having a schema would allow validation at the node level, and I guess developers could even use validation tools to make sure their theme.json is correct.
I guess the first version of a schema could just validate what we have currently but specifying things in schema.json would be better than "'selector' => null," as the current syntax is a little confusing, selector is not null it is a string. It seems we are inventing our own schema.
I agree it can be done as a follow up 👍

File: lib/class-wp-theme-json.php (hunk 3 above)
Comment (jorgefilipecosta) [reply lib/class-wp-theme-json.php]: Well nice catch, the others should also not generate classes as we decided not to use classes anymore besides for things that already had them. But that should be fixed in a different PR.

**Review by jorgefilipecosta — APPROVED** [review]
LGTM 👍 


I think as follow-ups we should improve our schema. We should also think about the public API we expose we are exposing a set of getters that to me don't seem very useful right now.

File: lib/class-wp-theme-json.php (hunk 5 above)
Comment (nosolosw) [reply lib/class-wp-theme-json.php]: https://github.com/WordPress/gutenberg/pull/26803/commits/aee8a216fd4fdf017d50089b1b96a9c4b32aca78

File: lib/class-wp-theme-json.php (hunk 1 above)
Comment (nosolosw) [reply lib/class-wp-theme-json.php:93]: Created https://github.com/WordPress/gutenberg/issues/26955 to track this.
