### PR TITLE
Edit Post: Automatically connect a menu item with the pinnable sidebar plugin

### LINKED ISSUE #14457: After unpinning a PluginSidebar, there's no way to get it back
If a user accidentally or deliberately unpins a plugin sidebar (`PluginSidebar` component) that doesn't also add a "More menu item" (`PluginSidebarMoreMenuItem` component), that sidebar appears to be lost for that user. In addition, there doesn't appear to be a way to disable the ability to unpin a sidebar.

**To Reproduce**

1. Create a plugin with a `PluginSidebar` component
2. Display that plugin sidebar and then unpin it
3. You can no longer get back to that sidebar

**Expected behavior**

Either,
1. Gutenberg provides a separate UI to view/open unpinned sidebars, e.g. in the "Options" modal
2. "Unpinning" is an opt-in feature for `PluginSidebar`, so developers can opt to allow that if they're also adding another way to get to that sidebar, e.g. via `PluginSidebarMoreMenuItem`

Duplicates #14211, but I have no way to reopen that so I'm submitting it anew.

### PR DESCRIPTION
**Pull request by gziolo**
## Description

Fixes #14457.
Fixes partially #28546.

> If a user accidentally or deliberately unpins a plugin sidebar (`PluginSidebar` component) that doesn't also add a "More menu item" (`PluginSidebarMoreMenuItem` component), that sidebar appears to be lost for that user. In addition, there doesn't appear to be a way to disable the ability to unpin a sidebar.
>
> **To Reproduce**
>
> 1. Create a plugin with a `PluginSidebar` component
> 2. Display that plugin sidebar and then unpin it
> 3. You can no longer get back to that sidebar

When the plugin renders a pinnable `PluginSidebar` component, then by default it also automatically renders a corresponding `PluginSidebarMenuItem`. It's respecting matching `PluginSidebarMenuItem` components registered by plugins and therefore is fully backward compatible

## Technical implementation

This PR adds Special handling for backward compatibility. It ensures that menu items created by plugin authors aren't duplicated with automatically injected menu items coming from pinnable plugin sidebars. In practice, we create two fills, one indirectly from `PluginSidebar` and another that the plugin's author defines with `PluginSidebarMoreMenuItem`. At the time of rendering the Plugins section in MoreMenu, code iterates over all fills and detects possible duplications. When it happens then the fill rendered by `PluginSidebar` gets removed. `__unstableInitSource` prop was added to make it possible to decide which duplicated fill should be ignored.

### Case 1

Register a plugin with a sidebar only:

```js

wp.plugins.registerPlugin( 'my-default-plugin', {
	render: function() {
		const el = wp.element.createElement;
 	
		function MyPluginSidebar() {
 			return el(
				wp.editPost.PluginSidebar,
				{
					name: 'my-sidebar',
					title: 'My default title',
					icon: 'smiley',
				},
				el(
					wp.components.PanelBody,
					{},
					'My default content'
				)
			);
		}

 		return el( MyPluginSidebar );
	}
} );
```

### Case 2

The menu link for the sidebar should be added automatically in More Menu.

Register a plugin with a sidebar and a menu link:
```js
wp.plugins.registerPlugin( 'my-custom-plugin', {
	render: function() {
		const el = wp.element.createElement;
 	
		function MyPluginSidebar() {
 			return el(
				wp.editPost.PluginSidebar,
				{
					name: 'my-custom-sidebar',
					title: 'My sidebar title',
					icon: 'palmtree',
				},
				el(
					wp.components.PanelBody,
					{},
					'My custom content'
				)
			);
		}

		function MyPluginSidebarMoreMenuItem() {
 			return el(
				wp.editPost.PluginSidebarMoreMenuItem,
				{
					target: 'my-custom-sidebar',
					icon: 'menu'
				},
				'My custom title'
			);
		}

 		return el( wp.element.Fragment, {}, el( MyPluginSidebar ), el( MyPluginSidebarMoreMenuItem ) );
	}
} );
```

The menu link from the plugin should be rendered in More Menu, but the link from the sidebar should be removed.

## Screenshots

Screen Shot 2021-02-18 at 08 29 42

## Types of changes

New feature and a bug fix at once? It's hard to tell really 😄 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by gziolo** [comment]
@jasmussen, it's nearly ready but I struggle with finding a good testing examples. I might also miss some use cases 😃

I will let you know again once I sort everything out.

**Comment by gziolo** [comment]
It looks better with the latest changes applied:

Screen Shot 2021-02-17 at 20 38 09

So the original issues seem to be resolved, but there are other issues more visible now:
- the order of pinned items and menu items seems to be random
- Settings is now also added as a menu item - it shouldn't be there, we need a flag that disables this default behavior that isn't tied to pinning
- Pinned items should remember their place, at least the Settings sidebar should (#28546) - it becomes supper annoying now :)

File: packages/e2e-tests/plugins/plugins-api/sidebar.js [hunk 1]
```diff
@@ -86,25 +85,22 @@
...
+				el( SidebarContentsWithDataHandling, {} )
 			),
 			el(
 				PluginSidebarMoreMenuItem,
 				{
-					target: 'title-sidebar'
+					target: 'title-sidebar',
 				},
-				__( 'Sidebar title plugin' )
+				__( 'Plugin sidebar more menu title' )
```
Comment (gziolo) [inline packages/e2e-tests/plugins/plugins-api/sidebar.js:97]: I changed the name to ensure that we use the version explicitly registered by the plugin, rather than the one automatically injected.

**Comment by gziolo** [comment]
> Settings is now also added as a menu item - it shouldn't be there, we need a flag that disables this default behavior that isn't tied to pinning

I think I found a way to fix the issue by using `__unstableInitSource` prop introduced to exist only for backward compatibility. When the vale `core` is passed then the menu item is never rendered.

I think I have some ideas on how to fix the issue with the order of pinned items. It is less of an issue in the More Menu for the Plugins section and I believe it has the same root. My guess is that all pinned items get unmounted but the one that has currently opened sidebar. I will investigate separately as it isn't related to this PR at all. #28546 was created for a reason 😄

**Comment by youknowriad** [comment]
This is very cool :) 

Is `__unstableInitSource` necessary do you think?

**Comment by youknowriad** [comment]
Oh actually, that prop is useful, I misunderstood its purpose originally :)

File: packages/edit-post/src/components/sidebar/settings-sidebar/index.js [hunk 2]
```diff
@@ -59,6 +59,7 @@ const SettingsSidebar = () => {
 
 	return (
 		<PluginSidebarEditPost
+			__unstableInitSource="core"
```
Comment (youknowriad) [inline packages/edit-post/src/components/sidebar/settings-sidebar/index.js:62]: What does "core" mean? I thought `__unstableInitSource` was just a prop for the menu item fill to be able to prioritize which menu item to show?

File: packages/interface/src/components/action-item/index.js [hunk 3]
```diff
@@ -22,11 +23,44 @@ function ActionItemSlot( {
...
+							__unstableTarget &&
+							__unstableInitSource === 'plugin'
+						) {
+							initializedByPlugins.push( __unstableTarget );
+						}
+					}
+				);
+				const children = Children.map( fills, ( child ) => {
+					if (
+						child.props.__unstableInitSource === 'sidebar' &&
```
Comment (youknowriad) [inline packages/interface/src/components/action-item/index.js:52]: It seems there's no need to check "sidebar" here right? Can't we just check !== "plugin"

File: packages/interface/src/components/complementary-area/index.js [hunk 4]
```diff
@@ -150,6 +153,16 @@ function ComplementaryArea( {
 					/>
 				</PinnedItems>
 			) }
+			{ __unstableInitSource !== 'core' && isPinnable && (
```
Comment (youknowriad) [inline packages/interface/src/components/complementary-area/index.js:156]: mmm,  so "core" is a way to opt-out of the menu item?

**Comment by gziolo** [comment]
> Is `__unstableInitSource` necessary do you think?

There needs to be a way to detect which fill should be preferred in More Menu when it gets duplicated. I didn't come up with anything nicer but if you can think of something more elegant I will willingly update the code :) I explained the reasons for the current implementation in the description this way:

> This PR adds Special handling for backward compatibility. It ensures that menu items created by plugin authors aren't duplicated with automatically injected menu items coming from pinnable plugin sidebars. In practice, we create two fills, one indirectly from `PluginSidebar` and another that the plugin's author defines with `PluginSidebarMoreMenuItem`. At the time of rendering the Plugins section in MoreMenu, code iterates over all fills and detects possible duplications. When it happens then the fill rendered by `PluginSidebar` gets removed. `__unstableInitSource` prop was added to make it possible to decide which duplicated fill should be ignored.

File: packages/interface/src/components/complementary-area/index.js (hunk 4 above)
Comment (youknowriad) [reply packages/interface/src/components/complementary-area/index.js:156]: Do you think plugins could benefit this (regardless of whether they provide  their  own menu item). Meaning, do you think it should be an explicit `noMenuItem` prop?

Comment (gziolo) [reply packages/interface/src/components/complementary-area/index.js:156]: Yes 🙈

File: packages/interface/src/components/complementary-area/index.js [hunk 5]
```diff
@@ -150,6 +153,16 @@ function ComplementaryArea( {
...
+				<ComplementaryAreaMoreMenuItem
+					__unstableInitSource={ __unstableInitSource }
```
Comment (youknowriad) [inline packages/interface/src/components/complementary-area/index.js:158]: Feels like we could just drop the `__unstableInitSource` from here.

File: packages/interface/src/components/action-item/index.js (hunk 3 above)
Comment (gziolo) [reply packages/interface/src/components/action-item/index.js:52]: That would work as well, but the values can be either `sidebar` and `plugin` so both ways work.

Comment (youknowriad) [reply packages/interface/src/components/action-item/index.js:52]: I was actually thinking we could probably make it a boolean: `__unstableExplicitMenuItem` or something

File: packages/interface/src/components/complementary-area/index.js (hunk 5 above)
Comment (gziolo) [reply packages/interface/src/components/complementary-area/index.js:158]: I now connected this comment with https://github.com/WordPress/gutenberg/pull/29081#discussion_r578203796. Yes, that would work 👍🏻

File: packages/edit-post/src/components/sidebar/settings-sidebar/index.js (hunk 2 above)
Comment (gziolo) [reply packages/edit-post/src/components/sidebar/settings-sidebar/index.js:62]: We can always add a new prop that allows disabling auto-injecting the menu item by the sidebar. What do you think?

File: packages/interface/src/components/action-item/index.js (hunk 3 above)
Comment (gziolo) [reply packages/interface/src/components/action-item/index.js:52]: I'll give it a try. Thank you for the good pointers 💯

**Comment by gziolo** [comment]
> > Settings is now also added as a menu item - it shouldn't be there, we need a flag that disables this default behavior that isn't tied to pinning
> 
> I think I found a way to fix the issue by using `__unstableInitSource` prop introduced to exist only for backward compatibility. When the vale `core` is passed then the menu item is never rendered.
> 
> I think I have some ideas on how to fix the issue with the order of pinned items. It is less of an issue in the More Menu for the Plugins section and I believe it has the same root. My guess is that all pinned items get unmounted but the one that has currently opened sidebar. I will investigate separately as it isn't related to this PR at all. #28546 was created for a reason 😄

I found what the issue is. It's a subtle difference in the implementation that regressed here:
https://github.com/WordPress/gutenberg/pull/20698/files#r578252851

It's so simple that I will include it here.

File: packages/interface/src/components/complementary-area/index.js [hunk 6]
```diff
@@ -134,22 +136,33 @@ function ComplementaryArea( {
...
+							aria-expanded={ isActive }
+							label={ title }
+							icon={ showIconLabels ? check : icon }
+							showTooltip={ ! showIconLabels }
+							isTertiary={ showIconLabels }
+						/>
+					) }
 				</PinnedItems>
 			) }
+			{ name && isPinnable && (
```
Comment (gziolo) [inline packages/interface/src/components/complementary-area/index.js:157]: I found a prop that is mandatory and unique for the `PluginSidebar` implementation. Would it work?

File: packages/edit-post/src/components/header/plugin-sidebar-more-menu-item/index.js [hunk 7]
```diff
@@ -53,6 +53,12 @@ import { ComplementaryAreaMoreMenuItem } from '@wordpress/interface';
 
 export default function PluginSidebarMoreMenuItem( props ) {
 	return (
-		<ComplementaryAreaMoreMenuItem scope="core/edit-post" { ...props } />
+		<ComplementaryAreaMoreMenuItem
+			// Menu item is marked with unstable prop for backward compatibility.
+			// @see https://github.com/WordPress/gutenberg/issues/14457
+			__unstableExplicitMenuItem
```
Comment (gziolo) [inline packages/edit-post/src/components/header/plugin-sidebar-more-menu-item/index.js:59]: I think it works well. Good idea @youknowriad 👏🏻

**Comment by gziolo** [comment]
@youknowriad I think I was able to address your feedback:

Last remaining thing I discovered now are two warnings that need to be fixed:
> Warning: React does not recognize the `__unstableExplicitMenuItem` prop on a DOM element.
> Warning: React does not recognize the `__unstableTarget` prop on a DOM element.

File: packages/interface/src/components/complementary-area/index.js (hunk 6 above)
Comment (youknowriad) [reply packages/interface/src/components/complementary-area/index.js:157]: is the name the prop?

**Review by youknowriad — APPROVED** [review]
This is looking good

File: packages/interface/src/components/complementary-area/index.js (hunk 6 above)
Comment (gziolo) [reply packages/interface/src/components/complementary-area/index.js:157]: Yes, it's part of the `PluginSidebar` API. In other places `identifier` is used for some reasons.

**Comment by jasmussen** [comment]
Thank you so much for doing this!

sidebar

This is exactly how I was hoping it'd work. 

Note: the bigger button that's toggled, I will look at that separately. 

Another question: will #28546 be easier to address once this lands or is that entirely separate?

**Comment by gziolo** [comment]
> Another question: will #28546 be easier to address once this lands or is that entirely separate?

This PR improves the order of pinned items - they don't change after unpinning/pinning anymore. I will look separately how to ensure that core features are always first on the list.

**Comment by gziolo** [comment]
I will work on further improvements in the follow-up PR.
