### PR TITLE
Fix WordPress block resolution and embeds as reusable blocks

### LINKED ISSUE #9938: Weird behavior trying to save a WordPress embed as reusable block
**Describe the bug**
I added a WordPress embed block to my post. It worked. Then I used "add as reusable block", it bypassed the save screen and added it as an "untitled"  to the list. Then I tried to add it to a post.  The "An error happened screen" appeared. (nice!!) 
And I was able to "copy the error" see below. 

_NOTE: The error message indicates 3.9 RC, I tested it in 3.8 as well, with the same outcome._

**To Reproduce**
1. Add a new post
2. in new line, [copy/page URL](https://make.wordpress.org/core/2018/09/12/whats-new-in-gutenberg-12th-september/) 
3. save post
4. Edit Post
5. Select block
6. Use: Add to reusable block. 
7.  Remove block from post
8. Try to add from reusable blocks the "Untitled" block

**Expected behavior**
- A save screen to give the reusable block a name
- when selected add just saved block again into the post. 

**Video**
http://recordit.co/cHJ3ygmpqZ

**Desktop (please complete the following information):**
 - OS: Mac 10.13.6
 - Browser Chrome
 - Version 68

**Error Message**
TypeError: this.props.onReplace is not a function
at r.value (http://rctesting.local/wp-content/plugins/gutenberg-3.9-RC/build/block-library/index.js?ver=1537102276:12:86194)
at new r (http://rctesting.local/wp-content/plugins/gutenberg-3.9-RC/build/block-library/index.js?ver=1537102276:12:84960)
at yh (http://rctesting.local/wp-content/plugins/gutenberg-3.9-RC/vendor/react-dom.min.82e21c65.js:97:111)
at lg (http://rctesting.local/wp-content/plugins/gutenberg-3.9-RC/vendor/react-dom.min.82e21c65.js:120:88)
at mg (http://rctesting.local/wp-content/plugins/gutenberg-3.9-RC/vendor/react-dom.min.82e21c65.js:120:386)
at gc (http://rctesting.local/wp-content/plugins/gutenberg-3.9-RC/vendor/react-dom.min.82e21c65.js:127:202)
at vb (http://rctesting.local/wp-content/plugins/gutenberg-3.9-RC/vendor/react-dom.min.82e21c65.js:126:230)
at ub (http://rctesting.local/wp-content/plugins/gutenberg-3.9-RC/vendor/react-dom.min.82e21c65.js:126:65)
at ug (http://rctesting.local/wp-content/plugins/gutenberg-3.9-RC/vendor/react-dom.min.82e21c65.js:136:380)
at ue (http://rctesting.local/wp-content/plugins/gutenberg-3.9-RC/vendor/react-dom.min.82e21c65.js:25:80)

### PR DESCRIPTION
**Pull request by notnownikki**
## Description

There were a couple of problems using Embed blocks as Reusable blocks.

1) Pasting a WordPress URL created an embed block, but did not resolve the block to a WordPress block. This meant that if you tried to edit a post with the resulting block in it, and converted it to a Reusable block, it would crash. The crash was caused because the new block had the preview data already available, and so the block resolution would kick in and try to replace it with a WordPress block, but `this.props.onReplace` was not available, so, we got the crash seen in https://github.com/WordPress/gutenberg/issues/9938 . This is fixed in this PR by making sure that the block resolution works and carries across all attributes set on the Embed block when we're embedding WordPress content. It's more complex for WordPress embeds because we need to get back the embed preview to detect it's WordPress and switch to the correct block. We can't go by the URL as we can for the other blocks because there is no regex that can determine a URL is WordPress.

2) The `do_blocks` filter ran before `do_shortcode` but after `oembed`, so reusable embed blocks did not get their URL processed. This PR changes the priority to fix this.

Fixes: https://github.com/WordPress/gutenberg/issues/9938

## How has this been tested?

Run through the steps in https://github.com/WordPress/gutenberg/issues/9938

The embed block should become reusable, and render correctly on the published post.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: lib/blocks.php [hunk 1]
```diff
@@ -249,7 +249,7 @@ function do_blocks( $content ) {
 
 	return $rendered_content;
 }
-add_filter( 'the_content', 'do_blocks', 9 ); // BEFORE do_shortcode().
+add_filter( 'the_content', 'do_blocks', 7 ); // BEFORE do_shortcode() and oembed.
```
Comment (notnownikki) [inline lib/blocks.php]: Allows embed blocks to be used as reusable blocks

File: packages/block-library/src/embed/index.js [hunk 2]
```diff
@@ -65,7 +69,7 @@ export function getEmbedEdit( title, icon ) {
 			const switchedPreview = this.props.preview && this.props.attributes.url !== prevProps.attributes.url;
 			const switchedURL = this.props.attributes.url !== prevProps.attributes.url;
 
-			if ( switchedURL && this.maybeSwitchBlock() ) {
+			if ( ( switchedURL || ( hasPreview && ! hadPreview ) ) && this.maybeSwitchBlock() ) {
```
Comment (notnownikki) [inline packages/block-library/src/embed/index.js]: Try switching the block if the URL changes, or we get a preview. To switch to a WordPress block, we need the preview.

File: packages/block-library/src/embed/index.js [hunk 3]
```diff
@@ -142,14 +161,15 @@ export function getEmbedEdit( title, icon ) {
...
 		 */
-		maybeSetAspectRatioClassName( html ) {
+		getClassNamesWithAspectRatio( html ) {
 			const previewDocument = document.implementation.createHTMLDocument( '' );
 			previewDocument.body.innerHTML = html;
 			const iframe = previewDocument.body.querySelector( 'iframe' );
 
 			if ( ! iframe ) {
-				return;
+				return this.props.attributes.className;
```
Comment (talldan) [inline packages/block-library/src/embed/index.js]: This function could be refactored a bit to avoid so many returns. Could remove this if statement, change the one below to `if( iframe && iframe.height && iframe.width )`, and then move the remaining `return this.props.attributes.className;` to the very last line of the function.

File: packages/block-library/src/embed/index.js [hunk 4]
```diff
@@ -128,7 +132,22 @@ export function getEmbedEdit( title, icon ) {
 				if ( includes( html, 'class="wp-embedded-content" data-secret' ) ) {
 					// If this is not the WordPress embed block, transform it into one.
 					if ( this.props.name !== 'core-embed/wordpress' ) {
-						this.props.onReplace( createBlock( 'core-embed/wordpress', { url } ) );
+						this.props.onReplace(
+							createBlock(
```
Comment (talldan) [inline packages/block-library/src/embed/index.js]: Not really a thing to fix in this PR, but I thought i'd mention that it'd be tidier if `maybeSwitchBlock` returned the value of createBlock so that it becomes purer and somewhat side-effect free (depending on what createBlock does).

**Review by talldan — COMMENTED** [review]
I'm not all that familiar with some of the code being changed, so I think it'd worth getting someone with more familiarity to review as well. 

I tested though and the fix works well. Also seems like it'd be a good fix to get in, as the editor crashes whenever hovering over the reusable block in the block switcher (I imagine that's the preview), so it's quite a nasty bug!

File: packages/block-library/src/embed/index.js (hunk 3 above)
Comment (notnownikki) [reply packages/block-library/src/embed/index.js]: Gah yes, I missed a refactor pass!

**Comment by notnownikki** [comment]
@talldan thanks :) I've added it to the 4.0 milestone so it should get into the review queue for other peeps. There will be some happy people on my twitter timeline once 4.0 gets out!!

File: packages/block-library/src/embed/index.js (hunk 4 above)
Comment (notnownikki) [reply packages/block-library/src/embed/index.js]: Yes, too many side effects caused this problem. Separating the preview->attribute generation from the code that set the attributes let us fix this, same should be done here. Once this is in I'll do it as a `chore` PR.

**Comment by gziolo** [comment]
@talldan can you do another round of testing and merge it if everything goes well?

**Review by talldan — APPROVED** [review]
I gave it a good test and no issues, and the explanations make sense.

A few things in the embed block could do with a bit of a tidy up, but that's not really the fault of this PR - so lets get it in!

**Comment by notnownikki** [comment]
@talldan an embed block refactor and tidy and unit test is on my list of stuff to do. It's kinda of grown organically... like a mold.

**Comment by gziolo** [comment]
Kudos @talldan for doing another review so quickly, much appreciated 💯

File: lib/blocks.php (hunk 1 above)
Comment (youknowriad) [reply lib/blocks.php]: I think this change broke the dynamic blocks in the frontend if you have any meta box in the editor.

Comment (lkraav) [reply lib/blocks.php]: @youknowriad this change has even more consequences. For one, it completely invalidates `gutenberg_wpautop()` who will have `has_blocks()` always fail (because `do_blocks()` already killed markup), rendering `gutenberg_wpautop()` useless.

Comment (youknowriad) [reply lib/blocks.php]: yes, I noticed too. We're working on fixes in #11050
