### PR TITLE
Switch the custom color control to a text link, fix padding for color picker.

### LINKED ISSUE #5258: Improve Custom Color Button
From a recent meetup there was feedback that the color picker wasn't that obvious for everyone. Right now we just show the rainbow circle:

color-picker

A suggestion was to add the 'droplet picker' icon, props to @rickybanister, but we could also add a droplet itself. I have done 2 versions and I think the droplet works well as a suggestion but visually easy to work out.

color-picker-obvious

What do people think? Does this make it more obvious? Is this enough or should we do more? What else could we do?

### PR DESCRIPTION
**Pull request by kjellr**
Fixes #5258.

This PR changes the custom color control from a multi-color palette icon to a text link, lined up next to the "Clear" button. It also adds proper top + bottom padding to the color picker's controls area (This appears to have been a regression at some point). 

**Before**

original-02

---

original-01

---

**After**

new-02

---

new-01

---

### CODE REVIEW

**Review by mapk — APPROVED** [review]
Looks and works great! Tested on smaller and larger screens without any issues. I do feel a little awkward with a link opening up a popover, which feels more like a button interaction. But we can always iterate if needed. 🚢

**Comment by gziolo** [comment]
There are 4 failing unit tests which fail because HTML markup has changed. Related docs on how to update snapshots:
https://github.com/WordPress/gutenberg/blob/master/docs/contributors/testing-overview.md#snapshot-testing

**Comment by kjellr** [comment]
> There are 4 failing unit tests which fail because HTML markup has changed. Related docs on how to update snapshots:

Thanks, @gziolo! Should be all set now. 

---

> I do feel a little awkward with a link opening up a popover, which feels more like a button interaction. But we can always iterate if needed. 🚢

Yep. For now, this actually follows the behavior for the "Visibility" and "Publish" state popovers: 

screen shot 2019-02-07 at 10 55 54 am

---

I'll hold off for some a11y 👀 before merging. Thanks, all!

**Comment by mapk** [comment]
@LukePettway Can we get some a11y eyes on this before merging?

**Comment by LukePettway** [comment]
@mapk I can take a look today 🌝

**Comment by LukePettway** [comment]
Initial keyboard testing seems fine so far. I'm having issues with my VM so I can't test NVDA until I get home later today.

**Comment by kjellr** [comment]
Hey @LukePettway — just wanted to see if you'd had a moment to review this with NVDA? I really appreciate the help. 🙂

**Comment by afercia** [comment]
I'd suggest to remove the tooltip, as it's now pointless :)

screenshot 2019-02-18 at 22 33 44

@mapk @LukePettway this change shouldn't impact a11y in any way as it touches only the button and CSS.

**Comment by LukePettway** [comment]
Thanks @afercia I did retest this again in Voice Over (since I can't seem to get Gutenberg running on Windows) and it worked. I think I wasn't using Safari 🤣. Everything worked fine. I agree that it shouldn't mess with anything AT related. Everything looks good to me.

**Comment by kjellr** [comment]
Thanks, @afercia and @LukePettway. I've removed the tooltip, and I'll get this in as soon as those tests pass. 👍

File: packages/components/src/color-palette/test/index.js [hunk 1]
```diff
@@ -71,7 +71,7 @@ describe( 'ColorPalette', () => {
 			const isOpen = true;
 			const onToggle = jest.fn();
 
-			const renderedToggleButton = shallow( dropdown.props().renderToggle( { isOpen, onToggle } ).props.children );
+			const renderedToggleButton = shallow( dropdown.props().renderToggle( { isOpen, onToggle } ) );
```
Comment (kjellr) [inline packages/components/src/color-palette/test/index.js]: @gziolo would you mind taking a quick look at this change? I just want to make sure I fixed those tests correctly. 

After removing the tooltip wrapper in f493620, I was getting a failed test that said `ShallowWrapper can only wrap valid elements` on this line. I tried removing the `.props.children` bit at the end here (since the wrapper was removed, there are no child elements in this dropdown anymore), and that got the tests to pass. Is that the right move here? 

Thanks!

Comment (gziolo) [reply packages/components/src/color-palette/test/index.js]: Before it was a Tooltip component with a button and span. Now it's simply `Button` component so you no longer need to access `button` through children. Nicely done 👍

File: packages/components/src/color-palette/index.js [hunk 2]
```diff
@@ -55,42 +55,42 @@ export default function ColorPalette( { colors, disableCustomColors = false, val
...
-						<Tooltip text={ customColorPickerLabel }>
-							<button
+			<div className="components-color-palette__custom-clear-wrapper">
+				{ ! disableCustomColors &&
+					<Dropdown
+						className="components-color-palette__custom-color"
+						contentClassName="components-color-palette__picker"
+						renderToggle={ ( { isOpen, onToggle } ) => (
+							<Button
 								type="button"
```
Comment (gziolo) [inline packages/components/src/color-palette/index.js]: `type` `button` is applied inside `Button` component. It should be removed here.

See: https://github.com/WordPress/gutenberg/blob/master/packages/components/src/button/index.js#L42

File: packages/components/src/color-palette/test/index.js (hunk 1 above)
Comment (kjellr) [reply packages/components/src/color-palette/test/index.js]: ⭐️ Thank you!

File: packages/components/src/color-palette/index.js (hunk 2 above)
Comment (kjellr) [reply packages/components/src/color-palette/index.js]: Good call! Removed that in 62087ba. Should be all set. 👍

**Review by gziolo — APPROVED** [review]
Code changes look good as commented earlier 👍

**Comment by kjellr** [comment]
Thanks, everyone!
