### PR TITLE
wp-env: Add better default PHPunit settings, fix Xdebug, and update docs

### LINKED ISSUE #28703: Edit php configuration wp-env
## What problem does this address?

I need to increase the `max_upload_filesize` and I can't find how to edit the php.ini. I've tried to edit the `~/.wp-env/{HASH_OF_MY_PROJECT}/Dockerfile` by adding `RUN echo 'upload_max_filesize="512M"' >> /usr/local/etc/php/php.ini` but when I do a `wp-env start --upgrade`, it replace the entire `Dockerfile`.

## What is your proposed solution?
I think the best solution should be to add php configuration params in the `.wp-env.json`. Something like : 
```JSON
{
    "phpConfig": {
        "post_max_size": "512M",
        "upload_max_filesize": "512M",
        "memory_limit": "512M",
    }
}
```

An other idea should be to Specified a customer `Dockerfile` to use. The only downside of this one is auto configuration like wordpress version, core version or xDebug configuration won't work.

### LINKED ISSUE #46635: wp-env with xdebug fails due to mismatching PHP version
### Description

[Xdebug recently released version 3.2.0, which drops support for PHP 7.2, 7.3 and 7.4.](https://pecl.php.net/package/xdebug/3.2.0) `wp-env start` seems to take the latest stable version of xdebug from pecl, which causes problems when using PHP <8. Wordpress only has beta support for PHP 8.x, so I don't want to update my plugin to use that yet. 

```
$ wp-env start --xdebug
✖ Error while running docker-compose command.
Sending build context to Docker daemon  421.5MB
Step 1/7 : FROM wordpress:php7.4
 ---> 1730fea0ae8e
Step 2/7 : RUN apt-get -qy install $PHPIZE_DEPS && touch /usr/local/etc/php/php.ini
 ---> Using cache
 ---> ee0742886da6
Step 3/7 : RUN if [ -z "$(pecl list | grep xdebug)" ] ; then pecl install xdebug ; fi
 ---> Running in abab7ff4328a
pecl/xdebug requires PHP (version >= 8.0.0, version <= 8.2.99), installed version is 7.4.33
No valid packages found
install failed
Building wordpress
The command '/bin/sh -c if [ -z "$(pecl list | grep xdebug)" ] ; then pecl install xdebug ; fi' returned a non-zero code: 1
Service 'wordpress' failed to build : Build failed
```

### Step-by-step reproduction instructions

1. In .wp-env.json, set `"phpVersion": "7.4"`
2. Run `wp-env start --xdebug`

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- `@wordpress/env` v5.8.0
- Linux (KDE Neon 5.26) 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by noahtallen**
## What?
1. Resolves #28703 by documenting `.htaccess` mapping and increasing default upload size to 1GB. 
2. Resolves #46635 by using the previous Xdebug version when using PHP 7.x
3. Fixes Xdebug, which I found was broken while testing this
4. Adds more documentation about stuff in this PR, and for #50408 

### Before:
SCR-20230509-ilv

### After:
SCR-20230509-iu0

## How?
Adjusts the dockerfiles we generate! This also changes Xdebug such that it's not installed in the CLI environments.

### PHP settings
1. Verify that larger files can be uploaded
2. Check the media upload settings here: http://localhost:8888/wp-admin/site-health.php?tab=debug
3. Map a `.htaccess` file (following the documentation), and verify those upload sizes override the default values

### Xdebug
1. Setup Xdebug in VS Code following the instructions in the readme
2. Run `npx wp-env start --xdebug`
3. Add a breakpoint to `gutenberg.php`
5. Access the site via URL, and verify a breakpoint is triggered.

### CODE REVIEW

File: packages/env/lib/init-config.js [hunk 1]
```diff
@@ -235,33 +236,32 @@ RUN apt-get -qy install $PHPIZE_DEPS && touch /usr/local/etc/php/php.ini
 # Set up sudo so they can have root access.
 RUN apt-get -qy install sudo
 RUN echo "$HOST_USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers`;
-	} else {
-		dockerFileContent += `
+			if ( shouldEnableXdebug( config ) ) {
+				// Xdebug is only needed for WordPress environments.
+				dockerFileContent += getXdebugSetup( config.xdebug );
+			}
```
Comment (ObliviousHarmony) [inline packages/env/lib/init-config.js]: How would you feel about merging `shouldEnableXdebug()` and `getXdebugSetup()` in favor of just having a `getXdebugConfiguration()` and inject that into `dockerFileContent` with `${ getXdebugConfiguration() }`? We can have the new function return an empty string if it's disabled and then return the configuration if it's enabled?

File: packages/env/lib/init-config.js [hunk 2]
```diff
@@ -235,33 +236,32 @@ RUN apt-get -qy install $PHPIZE_DEPS && touch /usr/local/etc/php/php.ini
...
+			break;
+		}
+		case 'cli': {
```
Comment (ObliviousHarmony) [inline packages/env/lib/init-config.js:208]: We should keep Xdebug support in the CLI container

Comment (noahtallen) [reply packages/env/lib/init-config.js:208]: added 👍

File: packages/env/lib/init-config.js (hunk 1 above)
Comment (noahtallen) [reply packages/env/lib/init-config.js]: yep, that sounds good!

File: packages/env/lib/build-docker-compose-config.js [hunk 3]
```diff
@@ -241,6 +243,7 @@ module.exports = function buildDockerComposeConfig( config ) {
 					...dbEnv.development,
 					WP_TESTS_DIR: '/wordpress-phpunit',
 				},
+				extra_hosts: [ 'host.docker.internal:host-gateway' ],
```
Comment (noahtallen) [inline packages/env/lib/build-docker-compose-config.js:246]: This ultimately becomes

```
    extra_hosts:
      - 'host.docker.internal:host-gateway'
```

in the yml file. Not sure if the extra quotations marks will matter

Comment (ObliviousHarmony) [reply packages/env/lib/build-docker-compose-config.js:246]: Looking at the YAML spec it seems that using single-quotes like this just clarifies that the type is a string. It's useful in cases where they may be ambiguity, so once parsed, `docker-compose` won't see any quotes.

Comment (ObliviousHarmony) [reply packages/env/lib/build-docker-compose-config.js:246]: For what it's worth too, I'm sure Docker would give an error otherwise because `'` isn't valid in a hostname!

File: packages/env/README.md [hunk 4]
```diff
@@ -183,6 +183,26 @@ Out of the box `wp-env` includes the [WordPress' PHPUnit test files](https://dev
 
 While we do provide a default `wp-tests-config.php` file within the environment, there may be cases where you want to use your own. WordPress provides a `WP_TESTS_CONFIG_FILE_PATH` constant that you can use to change the `wp-config.php` file used for testing. Set this to a desired path in your `bootstrap.php` file and the file you've chosen will be used instead of the one included in the environment.
 
+## Using `composer`, `phpunit`, and `wp-cli` tools.
+
+For ease of use, Composer, PHPUnit, and wp-cli are available for in the environment. To run these executables, use `wp-env run <env> <tool> <command>`. For example, `wp-env run cli composer install`, or `wp-env run tests-cli phpunit`. You can also access various shells like `wp-env run cli bash` or `wp-env run cli wp shell`.
```
Comment (ObliviousHarmony) [inline packages/env/README.md:188]: I worry that including `wp-cli` here makes it ambiguous. It feels like this is saying you should use `wp-env run cli wp-cli <command>`.

File: packages/env/lib/init-config.js [hunk 5]
```diff
@@ -280,19 +276,17 @@ USER root`;
...
-	const phpCompatibility = true;
+function getXdebugConfig( config ) {
+	if ( config.xdebug === 'off' ) {
+		return '';
+	}
 
-	// If PHP version is defined
-	// ensure it meets the Xdebug minimum compatibility requirment.
+	// Throw an error if someone tries to use Xdebug with an unsupported PHP version.
 	if ( config.env.development.phpVersion ) {
```
Comment (ObliviousHarmony) [inline packages/env/lib/init-config.js]: Technically this would break if `development` and `tests` had a different PHP version and one was incompatible.

**Review by ObliviousHarmony — APPROVED** [review]
Thanks @noahtallen, this tests really well. I tried it out both with the web server and CLI, and in both cases, the debugger worked perfectly. I _really_ like how easy it was to set this up. Once I had the VS Code plugin installed it worked completely out of the box.

File: packages/env/README.md (hunk 4 above)
Comment (noahtallen) [reply packages/env/README.md:188]: That's a good point. I was trying to provide a search result if someone is looking to use `wp-cli`. And to actually use it, you have to do `run cli wp`... how do you think we should phrase it?

File: packages/env/lib/init-config.js (hunk 5 above)
Comment (noahtallen) [reply packages/env/lib/init-config.js]: true, I'll update this

File: packages/env/README.md (hunk 4 above)
Comment (ObliviousHarmony) [reply packages/env/README.md:188]: Actually, I think this is fine. If you look at https://wp-cli.org, the official documentation has you using `wp` as the command. Anyone looking to use `wp-cli` will have that as the expectation I bet.

**Review by ObliviousHarmony — APPROVED** [review]

File: packages/env/lib/init-config.js [hunk 6]
```diff
@@ -6,14 +6,13 @@ const path = require( 'path' );
...
 const yaml = require( 'js-yaml' );
-const os = require( 'os' );
 
 /**
  * Internal dependencies
  */
 const { loadConfig } = require( './config' );
 const buildDockerComposeConfig = require( './build-docker-compose-config' );
-
+const { ValidationError } = require( './config' );
```
Comment (ObliviousHarmony) [inline packages/env/lib/init-config.js]: This can be combined with the above `require()` (shouldn't the linter have caught this?)

File: packages/env/lib/init-config.js [hunk 7]
```diff
@@ -280,36 +247,50 @@ USER root`;
...
+			throw new ValidationError(
+				`Cannot use XDebug 3 with PHP < 7.2. Your PHP version is ${ phpVersion }.`
+			);
+		}
+
+		// For now, we support PHP 7 by installing the final version of Xdebug to
+		// support PHP 7 when the environment uses that version. By default, use the
+		// latest version.
+		if ( majorVer === 7 ) {
+			xdebugVersion = 'xdebug-3.1.6';
```
Comment (ObliviousHarmony) [inline packages/env/lib/init-config.js:286]: What do you think about using the [support version table from Xdebug's website](https://xdebug.org/docs/compat)? We can pair each PHP minor release with a compatible version of Xdebug and then fall back to plain `xdebug` to grab the latest.

Comment (ObliviousHarmony) [reply packages/env/lib/init-config.js:286]: Something like:

```
// Map the PHP version to a compatible Xdebug version.
const versionMap = {
	'7.2': 'xdebug-3.1.6',
	'7.3': 'xdebug-3.1.6',
	'7.4': 'xdebug-3.1.6',
	'8.0': 'xdebug-3.2.1',
};
const xdebugVersion = versionMap[ `${ majorVer }.${ minorVer }` ] ?? 'xdebug';
```

Comment (noahtallen) [reply packages/env/lib/init-config.js:286]: I think it might be useful in the future, but I don't know if it provides any value right now -- we either use current (3.2), or previous (3.1). Outside of that, we'd be on 2.x, which would require config changes that would be hard to maintain

**Review by ObliviousHarmony — APPROVED** [review]
Looks good, sorry for the back and forth @noahtallen!

**Comment by noahtallen** [comment]
np, glad we got it in a good spot!

**Comment by ienzam** [comment]
The documentation says to run :

```
wp-env run cli --env-cwd=wp-content/plugins/gutenberg composer
```

But it fails because the container user does not write permission:
```
  /var/www/html/wp-content/plugins/bazar-mama-plugin/vendor does not exist and could not be created.  
```

Full output:
```
$ npx pnpm run composer install

> bazar-mama-plugin@0.1.0 composer /home/enzam/bazarmama/monorepo/wordpress/bazar-mama-plugin
> wp-env run cli --env-cwd=wp-content/plugins/bazar-mama-plugin composer "install"

ℹ Starting 'composer install' on the cli container. 

Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 26 installs, 0 updates, 0 removals

In Filesystem.php line 254:
                                                                                                      
  /var/www/html/wp-content/plugins/bazar-mama-plugin/vendor does not exist and could not be created.  
                                                                                                      

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--download-only] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]

✖ Command failed with exit code 1
Command failed with exit code 1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by noahtallen** [comment]
What does `npx wp-env --version` say?

**Comment by ObliviousHarmony** [comment]
It might also be the case that the environment hasn't been updated since the permission changes! One caveat that just occurred to me is that, technically, changes to `docker-compose.yml` and `Dockerfile` aren't seen as cache-busting. If we update these files but don't change anything else about the `WPConfig` object, `wp-env start` won't update without the option. It might be good to include a hash of these files in the cache object too!

**Comment by noahtallen** [comment]
> It might be good to include a hash of these files in the cache object too

True... I guess the assumption was that those files won't change unless the config changes!
