### PR TITLE
[Block Editor]: Restrict delete multi selected blocks shortcut

### LINKED ISSUE #36513: Selected blocks get deleted when creating a reusable block and pressing backspace key
### Description

When creating a reusable block via selecting multiple blocks, pressing the backspace key when typing a name in the "Create Reusable block" dialog leads to deleting the selected blocks and therefore the dialog to disappear. This behavior makes it very difficult to create a reusable block as removing characters when setting a name is very common.

### Step-by-step reproduction instructions

1. Add multiple blocks to a post.
2. Select multiple blocks.
3. Click on the options button located in the toolbar (the three dots icon).
4. Click on "Add to Reusable blocks" option.
5. Select the Name input field.
6. Type a name and press the backspace key.
7. Observe that the selected blocks are deleted and the "Create Reusable block" dialog is closed.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/14905380/141965638-b75f064e-35fb-4e94-951d-43958b0f0e0e.mp4

### Environment info

- Gutenberg: v11.8.3
- Editing Toolkit: 3.19495
- WP AMP: 2.0.5
- CoBlocks: 2.10.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #37316: Shortcuts: Delete multi selection shortcut triggered when clearing sidebar controls
#### Current Behaviour:

While multiple blocks are selected, clearing values from inputs in the `BlockInspector` using `del` or `backspace`, will trigger the keyboard shortcut to delete blocks, unexpectedly removing them.

#### Expected Behaviour: 

Using delete or backspace to clear values in a control such as the `UnitControl` would only clear that input's value not trigger removal of multiple blocks.

### Step-by-step reproduction instructions

1. On trunk, create a Post and add multiple paragraph blocks with text to it
2. Select those multiple paragraphs together
3. In the block inspector expand the color panel, click the color swatch, then toggle the edit button for the color value
4. In the color value field, press either the `del` or `backspace` keys
5. Notice the blocks were deleted.

**Note: Typgraphy panel will not be visible for multiple selections until https://github.com/WordPress/gutenberg/pull/37216 lands. This issue can also be replicated using line-height or letter-spacing if testing with that PR branch.**

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/60436221/145759649-bdae255c-150e-4c02-891b-c18ec9310b5b.mp4

### Environment info

- WordPress 5.8
- Gutenberg: Latest

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ntsekouras**
Fixes: https://github.com/WordPress/gutenberg/issues/36513
Fixes: https://github.com/WordPress/gutenberg/issues/37316

Currently if the writing flow keyboard shortcuts ([BlockEditorKeyboardShortcuts](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/keyboard-shortcuts/index.js)) are registered, they can be also processed in the Inspector controls or in any modals created in a block because they're all nested in the same BlockTools tree.

This results to the above two issues where if we have multi selected blocks and press `escape` or `delete` on a modal's or Inspector controls inputs, the blocks are deleted and we're not just removing a character as expected.

@ellatrix explained the issue very well [here](https://github.com/WordPress/gutenberg/issues/36513#issuecomment-999576385) and I'm quoting part of it.

>I think this boils down to the question: do we want shortcuts to work when the options popover in the block toolbar is toggled (which shows some shortcuts). I think yes. In that case this popover is no different from any other thing that uses a portal (iframe, inspector...). There's no way to know where exactly ⇧⌘D (for example) should work. If we want it to work in the block toolbar popover, then it will also work in the inspector and modals created in a block because they're all nested in the same BlockTools tree.

This PR implements the first solution with some tweaks.
>Solution 1: check if the target element is a text area, input, content editable, or event.defaultPrevented is true and return early. In all these cases backspace could be handled elsewhere.

From the above solution I added this check only in the specific shortcut for deleting multi selected blocks, as IMO this is the only one that disrupts the expected flow.
In addition I'm checking only for `input and text area` because we can be in content editable(example paragraph) but we still want the other shortcuts to work like `duplicate`, etc...

## Testing instructions
1. In `post editor` or `site editor` multi select some blocks
1.1 observe that by pressing `escape` or `delete` even with the block setting open will still work.
1.2 either in `Add to Reusable blocks` input or in an input in Inspector controls like `color, line height, etc..` press `escape` or `delete` and observe that the blocks are not deleted.

## Before

https://user-images.githubusercontent.com/16275880/147129511-2d7cb4b6-6ecc-44ee-a39e-d992619d257b.mov

## After

https://user-images.githubusercontent.com/16275880/147129324-5f1cc797-3cd9-4a64-9a33-fd192b2fc04d.mov

--------
Noting that the block editor shortcuts were [just merged for site editor](https://github.com/WordPress/gutenberg/pull/37577) and that's why in previous testing from others the above issues couldn't be reproduced consistently between the two editors (post/site).

### CODE REVIEW

File: packages/block-editor/src/components/block-tools/index.js [hunk 1]
```diff
@@ -95,6 +95,17 @@ export default function BlockTools( {
...
 			isMatch( 'core/block-editor/delete-multi-selection', event )
 		) {
+			/**
+			 * Check if the target element is a text area, input or
+			 * event.defaultPrevented and return early. In all these
+			 * cases backspace could be handled elsewhere.
+			 */
+			if (
+				[ 'INPUT', 'TEXTAREA' ].includes( event.target.nodeName ) ||
+				event.isDefaultPrevented()
```
Comment (Mamaduka) [inline packages/block-editor/src/components/block-tools/index.js]: I think this should be `event.defaultPrevented`.

Comment (ntsekouras) [reply packages/block-editor/src/components/block-tools/index.js]: Thanks 😄

**Review by Mamaduka — APPROVED** [review]
The fix works great in my tests. Tested in both Post and Site Editors.

File: packages/block-editor/src/components/block-tools/index.js (hunk 1 above)
Comment (ntsekouras) [reply packages/block-editor/src/components/block-tools/index.js]: I had tried it in debugger and saw the function and used it. I didn't know `jQuery` enhances the event object with that function. That was interesting 😄

**Review by stacimc — APPROVED** [review]
This tested great for me.

✅  Reproduced the bug on trunk in both the site and post editor
✅  Tested `Delete` and `Esc` from within the `Add to Reusable blocks` menu
✅  Tested `Delete` and `Esc` from within Inspector Controls, including nested controls (for example, opening up several layers of modals in the Color controls and using Esc to close each in order)
✅  Tested in both post editor and site editor

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for the fix @ntsekouras 👍 

This works great for me.

✅ Can replicate the original issue
✅ Normal deletion of multiple blocks still works as expected
✅ Prevents unintentional deletion of blocks when in inspector controls or modals etc
✅ Solution works in both Site and Post editors.

**Review by andrewserong — APPROVED** [review]
Just another +1 that this is testing well for me, too in the post and site editors. Thanks for the clean fix @ntsekouras! I'll close out a couple of other WIP PRs that sought to fix this issue, too.

File: packages/block-editor/src/components/block-tools/index.js [hunk 2]
```diff
@@ -95,6 +95,17 @@ export default function BlockTools( {
 		} else if (
 			isMatch( 'core/block-editor/delete-multi-selection', event )
 		) {
+			/**
+			 * Check if the target element is a text area, input or
+			 * event.defaultPrevented and return early. In all these
+			 * cases backspace could be handled elsewhere.
+			 */
+			if (
+				[ 'INPUT', 'TEXTAREA' ].includes( event.target.nodeName ) ||
```
Comment (ellatrix) [inline packages/block-editor/src/components/block-tools/index.js:104]: Should we add a check for content editable? Less common I guess.
Should we add an e2e test?

Comment (ntsekouras) [reply packages/block-editor/src/components/block-tools/index.js:104]: Yeah I think it's quite uncommon. If the `content editable` thing is raised let's add it then.

Regarding the tests you're 100% right and I should have written them in this PR, but [this follow up](https://github.com/WordPress/gutenberg/pull/37624) will do I guess 😄

**Comment by ramonjd** [comment]
Bit late to the party, but thanks for this fix @ntsekouras  🙇
