### PR TITLE
Fixed bad grammar in featured image upload.

### LINKED ISSUE #3394: Bad Grammar in Featured Image Upload
## Issue Overview
Featured image says "Select or Upload a media"

## Steps to Reproduce (for bugs)
1. Add a featured image
2. see bad grammar
3. cry

## Possible Solution
This should say "Select a Featured Image" since that's literally what you're doing here.

## Screenshots / Video
screen shot 2017-11-08 at 11 05 21 am

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
This PR aims to fix https://github.com/WordPress/gutenberg/issues/3394. An optional title parameter was added to the media upload button so we can easily change the title of the modal area in similar situations.

## Testing

1. Add a featured image.
2. Verify that the title of the image selection area is "Select a Featured Image"
3. Add the featured image.
4. Add an image or gallery block verify their titles stay the same as before.

## Screenshots (jpeg or gifs if applicable):
screen shot 2017-11-08 at 21 22 46

### CODE REVIEW

File: blocks/media-upload-button/index.js [hunk 1]
```diff
@@ -59,14 +59,14 @@ const slimImageObject = ( img ) => {
 };
 
 class MediaUploadButton extends Component {
-	constructor( { multiple = false, type, gallery = false } ) {
+	constructor( { multiple = false, type, gallery = false, title = __( 'Select or Upload a media' ) } ) {
```
Comment (aduth) [inline blocks/media-upload-button/index.js]: This is still poor grammar, even if not used in the specific case of featured image assignment. Maybe "Select or Upload Media".

**Review by aduth — COMMENTED** [review]
Ideally we'd be using strings from the post type definition, which can be customized for CPTs and filtered:

https://github.com/WordPress/WordPress/blob/0a81bcf4fffef460f22fda3fe5ccdf0376d1e3d9/wp-includes/post.php#L1403

**Comment by aduth** [comment]
>Ideally we'd be using strings from the post type definition, which can be customized for CPTs and filtered:

Noting that these are made available on a `labels` property from the `/wp/v2/types/<type>` endpoint when `?context=edit` is passed.

**Comment by jorgefilipecosta** [comment]
Hi @aduth, thank you for your suggestions. I end up using labels form the rest API. And I corrected the grammar of the default title in the image choosing modal.

File: editor/components/post-featured-image/index.js [hunk 2]
```diff
@@ -84,6 +90,7 @@ const applyWithAPIData = withAPIData( ( { featuredImageId } ) => {
 
 	return {
 		media: `/wp/v2/media/${ featuredImageId }`,
+		postType: '/wp/v2/types/post?context=edit',
```
Comment (aduth) [inline editor/components/post-featured-image/index.js]: We shouldn't assume the "post" type, since the editor can be used for custom post types.

`withAPIData` passes as a second argument an object containing a helper you can use here: `type`

See: https://github.com/WordPress/gutenberg/tree/master/components/higher-order/with-api-data

**Review by aduth — CHANGES_REQUESTED** [review]

File: editor/components/post-featured-image/index.js (hunk 2 above)
Comment (jorgefilipecosta) [reply editor/components/post-featured-image/index.js]: > We shouldn't assume the "post" type, since the editor can be used for custom post types.

Nice point, an improvement was made so we take into consideration the post type.

> .withAPIData passes as a second argument an object containing a helper you can use here: type
See: https://github.com/WordPress/gutenberg/tree/master/components/higher-order/with-api-data

This helper receives that the type and helps us create URLs for requests related to that type e.g: post -> posts, page -> pages. In this case, we need to use directly the post type name so I’m using the result of selector getCurrentPostType.

File: editor/components/post-featured-image/index.js [hunk 3]
```diff
@@ -77,13 +84,10 @@ const applyConnect = connect(
...
-const applyWithAPIData = withAPIData( ( { featuredImageId } ) => {
-	if ( ! featuredImageId ) {
-		return {};
-	}
-
+const applyWithAPIData = withAPIData( ( { featuredImageId, postTypeName } ) => {
 	return {
-		media: `/wp/v2/media/${ featuredImageId }`,
+		media: featuredImageId ? `/wp/v2/media/${ featuredImageId }` : undefined,
+		postType: postTypeName ? `/wp/v2/types/${ postTypeName }?context=edit` : undefined,
```
Comment (aduth) [inline editor/components/post-featured-image/index.js]: Unfortunately you cannot rely on the post type slug, since a plugin author can define a different `rest_base` for their custom post types:

https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-rest-api-support-for-custom-content-types/

You can see this in core behavior, where `/wp/v2/types/attachment` is incorrect, since the `rest_base` for the `attachment` post type has been assigned as `media`.

This is why the `type` helper from `withAPIData` second argument should be used.

**Review by aduth — CHANGES_REQUESTED** [review]

File: editor/components/post-featured-image/index.js (hunk 3 above)
Comment (jorgefilipecosta) [reply editor/components/post-featured-image/index.js]: Hi @aduth, thank you for having a look into this. I used the post type slug because it looks like this specific endpoint relies on it instead of the type.
E.g .../wp-json/wp/v2/types/attachment is a valid request, while .../wp-json/wp/v2/types/media is not a valid request.
The some for posts the type is 'posts' and if we use it we create an invalid request, while we use the slug the request is valid.

Comment (aduth) [reply editor/components/post-featured-image/index.js]: Aha! That makes sense, sorry for the quick instinctual reaction 😄

File: editor/components/post-featured-image/index.js [hunk 4]
```diff
@@ -15,14 +15,19 @@ import { MediaUploadButton } from '@wordpress/blocks';
  * Internal dependencies
  */
 import './style.scss';
-import { getEditedPostAttribute } from '../../selectors';
+import { getCurrentPostType, getEditedPostAttribute } from '../../selectors';
 import { editPost } from '../../actions';
 
-function PostFeaturedImage( { featuredImageId, onUpdateImage, onRemoveImage, media } ) {
+function PostFeaturedImage( { featuredImageId, onUpdateImage, onRemoveImage, media, postType } ) {
+	if ( ! postType || ! postType.data ) {
```
Comment (aduth) [inline editor/components/post-featured-image/index.js]: Do we really need to be so extreme as to hide the entire component when waiting for the label to become known? Can we show a temporary one, or is the text changing considered more jarring than the element suddenly becoming visible on the page?

File: editor/components/post-featured-image/index.js (hunk 3 above)
Comment (jorgefilipecosta) [reply editor/components/post-featured-image/index.js]: No problem at all, at the first I also tried to use post type and then I found it really really strange when it was not working as I expected :D

File: editor/components/post-featured-image/index.js [hunk 5]
```diff
@@ -15,14 +15,20 @@ import { MediaUploadButton } from '@wordpress/blocks';
  * Internal dependencies
  */
 import './style.scss';
-import { getEditedPostAttribute } from '../../selectors';
+import { getCurrentPostType, getEditedPostAttribute } from '../../selectors';
 import { editPost } from '../../actions';
 
-function PostFeaturedImage( { featuredImageId, onUpdateImage, onRemoveImage, media } ) {
+//used when labels from post tyoe were not yet loaded or when they are not present.
+const DEFAULT_SET_FEATURE_IMAGE_LABEL = __( 'Set featured image' );
```
Comment (aduth) [inline editor/components/post-featured-image/index.js]: Minor: We may not want to assume that `__` is a trivial operation, if we could avoid calling it as a side-effect of the module being imported (i.e. before we even know that we'll render it). Further, if we ever wanted to support changing locale in the current page session, these would always show the original value (vs. a forceful re-render of the whole app calling to get the latest value).

On second thought, if we _do_ consider `__` as non-trivial, we also have a similar problem that re-renders may occur frequently. Maybe we want to optimize it to be as trivial as possible, in which case it's not as big an issue to assign here.

**Review by aduth — APPROVED** [review]
👍

File: editor/components/post-featured-image/index.js (hunk 5 above)
Comment (jorgefilipecosta) [reply editor/components/post-featured-image/index.js]: I opted for this version because I saw other similar usages e.g: TABLE_CONTROLS in table-block.js, or ALIGNMENT_CONTROLS in alignment-toolbar. But your point: "Further, if we ever wanted to support changing locale in the current page session", is really important not necessarily in this case (because we will get the labels from the API), but in other cases, it may be problematic. I think in the interest of allowing local changes without full refresh we may move __ calls into the render. But even that would be problematic, because there is no guarantee the refresh would happen (unless another prop changes).
