### PR TITLE
More Block: Fix undo/redo history for custom text

### LINKED ISSUE #58875: More block: Undo does not work reliably for the custom text
### Description

In the more block, the capitalised READ MORE text in between the dashed lines can be edited.
If you edit the text and use the undo command or button, the text change is not undone.

### Step-by-step reproduction instructions

Add a more block to a post or page.
Place the cursor anywhere inside the READ MORE default text, and enter a new text.
Save.
Try to use the undo button. The text change is not undone.

Test two:
Add a more block.
Customize the text.
Add two new paragraphs.
Use the undo button 4 times:
1) The most recent paragraph is undone, which is correct
2) The first paragraph is undone, which is correct
3) There is a small shift in the layout of the read more block. This is not correct. The text change is meant to be undone.
4) The more block is removed. This undo step happens without the text in the block being undone.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WordPress 6.4.3 without Gutenberg active

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes #58875.
Based on the original proposal in #61131 by @carolinan.

PR updates the More block to use `PlainText` for rendering editable custom text. This allows proper integration in edit history, fixing the undo/redo bug.

I tried to keep the current (trunk) styling as much as possible.

## Testing Instructions
1. Create a post.
3. Add some content.
4. Split it using the More block.
5. Confirm that the default is displayed as a placeholder.
6. Slowly type the custom text. Take a couple of seconds break between each word.
7. Now undo/redo changes.
8. Confirm that history works similarly to a paragraph block.

### Testing Instructions for Keyboard
Same.

## Screenshots or screencast 

|Before|After|
|-|-|
|CleanShot 2025-08-06 at 13 42 58|CleanShot 2025-08-06 at 13 47 42|

https://github.com/user-attachments/assets/592534dc-5457-44ae-977f-8f193ed4d76d

### CODE REVIEW

File: packages/block-library/src/more/edit.js [hunk 1]
```diff
@@ -73,21 +54,34 @@ export default function MoreEdit( {
...
 			</InspectorControls>
 			<div { ...useBlockProps() }>
-				<input
-					aria-label={ __( '“Read more” link text' ) }
-					type="text"
+				<PlainText
+					__experimentalVersion={ 2 }
+					tagName="span"
+					aria-label={ __( '"Read more" text' ) }
 					value={ customText }
```
Comment (Mamaduka) [inline packages/block-library/src/more/edit.js:74]: Using `DEFAULT_TEXT` text as fallback values leaves an impression that you can't entirely delete the text.

There are workarounds if we decide to display default text as a fallback.

**Review by t-hamano — APPROVED** [review]
LGTM!

> I tried to keep the current (trunk) styling as much as possible.

In the future, we may be able to remove the current styling and add typography supports, like the Read More block.

**Comment by jasmussen** [comment]
I love the amount of red in this one. Nice.

**Comment by Mamaduka** [comment]
Thank you, folks, for the review!

**Comment by carolinan** [comment]
Thank you
