### PR TITLE
Latest Posts: Bring back classname on post list

### LINKED ISSUE #26445: Styles for the latest posts blocks are not loaded in the editor
**Describe the bug**
The CSS for the latest posts blocks, including the grid style, is not loaded in the editor, only on the front.

**To reproduce**
1. Go to the editor.
2. Add a latest posts block.
3. Select the grid style. confirm that the block does not change.
4. Save and view the front.
5. See that the editor and front does not match.

**Expected behavior**
The editor and front needs to match.

**Screenshots**
grid-56

**Editor version (please complete the following information):**
- WordPress version: 5.6-beta1-49308

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome version 86.0.4240.111

### PR DESCRIPTION
**Pull request by ryelle**
## Description
Fixes #26445. In https://github.com/WordPress/gutenberg/pull/26122 the Latest Posts edit component was refactored away from a class, which meant that the `this.props.className` was removed. This breaks latest posts styling, since themes rely on the `.wp-block-latest-posts` class to style. This is most obvious when you try to switch to grid style.

This PR simply adds the class back to the `ul`. I tried passing a props arg to `useBlockProps`, but since the classname needs to be on the `ul` (not the `div`, where `useBlockProps` is), this simple change works better.

## How has this been tested?

I tested with Twenty Twenty-One and Twenty Nineteen, both were broken (not showing posts in a grid, had bullet points) before this change.

Test by adding a Latest Posts block to your site, and making sure it looks the same on the frontend and editor.

## Screenshots

These are both in the editor. Everything's fine on the frontend.

Before:
Screen Shot 2020-10-26 at 5 09 12 PM

After:
Screen Shot 2020-10-26 at 5 02 34 PM

## Types of changes

Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/block-library/src/latest-posts/edit.js [hunk 1]
```diff
@@ -52,7 +52,11 @@ const USERS_LIST_QUERY = {
 	per_page: -1,
 };
 
-export default function LatestPostsEdit( { attributes, setAttributes } ) {
+export default function LatestPostsEdit( {
+	attributes,
+	setAttributes,
+	className,
```
Comment (youknowriad) [inline packages/block-library/src/latest-posts/edit.js:58]: `useBlockProps` is supposed to apply automatically these custom and generated classNames, so I wonder if the issue here is more than the wrapping "div" should be removed and instead the block props applied to the ul

Comment (ryelle) [reply packages/block-library/src/latest-posts/edit.js]: Yeah, like I mentioned, I tried passing the className to `useBlockProps` so that it would work correctly, but the class belongs on the `ul`. I didn't think of _removing_ the div, so I've tried that… it also didn't work initially, but clued me in to looking at other blocks, and finally it looks like the `apiVersion` was not updated in #26122, so the className is not being set correctly by `useBlockProps`.

With the fix for `"apiVersion": 2` in the block.json, and moving `blockProps` to the `<ul>` , this seems to be working correctly now.

**Review by youknowriad — APPROVED** [review]
This looks good to me and it matches the frontend.
Thanks for the fix.
