### PR TITLE
[Mobile] - Fix Voice Over and assistive keyboards

### LINKED ISSUE #21399: VoiceOver: Text input blocks no longer recognized as editing fields
A [user report from Elena B.](https://wordpress.slack.com/archives/C02RP4X03/p1692747057094999) in .org Slack:

> Since 23.0 of iOS/iPadOS JetPack app released August 21st, the editor does not work as expected with VoiceOver; in few words, the fields in post creation are no longer recognized as editing fields. Post title, paragraph blocks, HTML code editor...
Consequences: no possibility for Input Braille Screen; no way to select, cut, paste, copy text or move insertion point (cursor) to desired position. Consequently no ability to paste from a MarkDown editor to JetPack's editor.
Bluetooth keyboard? Yeah, tried, but while editing works with standard non-voiceover select commands, when I press Enter key to add a new block, focus jumps backwards in a random block making me lose the point. Instead of quickening my job, hardware keyboard ends up slowing it down.

| 22.9 | 23.0 |
| - | - |
| <video src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/b9d71f81-188f-480c-b112-69d420f3b7c3" alt="Screen recording of Braille input working correctly in 22.9" /> | <video src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/a4860e23-5406-48bb-b578-d15d20786c47" alt="Screen recording of Braille input not working correctly in 23.0" /> |

### PR DESCRIPTION
**Pull request by geriux**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/21399

**Related PRs:**
- https://github.com/wordpress-mobile/gutenberg-mobile/pull/6102
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21401

## What?
This PR addresses a regression after the React Native `0.71` upgrade, affecting how VoiceOver works with assistive input like Braille Screen Input, as well as using a Bluetooth keyboard and VoiceOver enabled.

There's an existing [GitHub ticket](https://github.com/facebook/react-native/issues/36465) in the React Native repo about this problem, it seems it only affects the legacy renderer.

## Why?
React Native `0.71` includes [several accessibility changes](https://github.com/facebook/react-native/commit/98d84e571df64b00e1ed3484923a1d8169dcfda1#diff-712da1fe12a3b8c4a5e7ff3d72135cc81c382e9cec7175d4eb34d5edbd040ff6) and these introduced this regression of the mobile editor.

## How?
First, it replaces the `TouchableWithoutFeedback` component in `AztecView` with `Pressable` as it restores the expected behavior when using VoiceOver and an assistive keyboard. It adds the `accessible` prop to `false` so the children components get accessed directly.

Due to updating the component that wraps `RCTAztecView` some snapshots needed to be updated.

Another important change is the new `patches/react-native+0.71.11.patch` patch, This was needed due to standard TextInputs being broken as well, so it applies a change that reverts the changes introduced in [React Native](https://github.com/facebook/react-native/commit/98d84e571df64b00e1ed3484923a1d8169dcfda1#diff-846840f37831efe100d9ef18d888a2ef838ad986a8c0e3107bf8029b1401d0bf).

## Testing Instructions

**Note:** This only affects the iOS platform and the VoiceOver functionality.

**Preconditions**: 
- Use the build [from this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/21401#issuecomment-1690382674).
- Make sure you have `Braille Screen Input` [enabled in the VoiceOver Rotor](https://support.apple.com/en-us/101637).
- All tests need VoiceOver to be enabled.

**Tip**: You can enable/disable VoiceOver with Siri.

### Adding content to the title and a Paragraph block

- Open the app
- Open the editor
- Focus on the title
- Type in some text with the Braille screen input
- **Expect** to see the text in the title field
- Add a Paragraph block
- Focus on the Paragraph block
- Type in some text with the Braille screen input
- **Expect** to see the text added in the Paragraph block

### Adding content to the HTML editor

- Open the app
- Open the editor
- Toggle to the HTML mode
- Type in some text with the Braille screen input
- **Expect** to see the text added in the HTML editor TextInput

### Using the Search block in the inserter

- Open the app
- Open the editor
- Open the Inserter
- Using the Search input, type in some content with the Braille screen input
- **Expect** to see the search text added

### Updating an Image caption
- Open the app
- Open the editor
- Add an Image block
- Add an image
- Focus on the caption field
- Type in a caption with the Braille screen input
- **Expect** to see the caption added to the Image block

## Bluetooth keyboard input with **VoiceOver enabled**

- Open the app
- Open the editor
- Connect a Bluetooth keyboard to your device
- Add a Paragraph block
- Type in some content
- On your keyboard hit the return key
- Type in new text in the new Paragraph block
- Make sure that the VoiceOver focus is on the newly added block
- Repeat these steps a few times
- **Expect** to see the VoiceOver focus to be in the block you last added and that is currently focused.

## VoiceOver with an assistive input (Braille Screen Input)

Before|After
-|-
<video src="https://github.com/WordPress/gutenberg/assets/4885740/e0adb925-af61-46e8-bdae-732447351000" />|<video src="https://github.com/WordPress/gutenberg/assets/4885740/dabef83c-a9d6-4b3c-9cfd-035a34a69893" />

## Bluetooth keyboard input with **VoiceOver enabled**

Before|After
-|-
<video src="https://github.com/WordPress/gutenberg/assets/4885740/dbbe870c-db79-4a03-9602-6682b4f11d7d" />|<video src="https://github.com/WordPress/gutenberg/assets/4885740/ef5fb19e-e1c0-4806-bdb6-b271054d3c4b" />

### CODE REVIEW

File: packages/react-native-aztec/src/AztecView.js [hunk 1]
```diff
@@ -305,7 +305,7 @@ class AztecView extends Component {
 		}
 
 		return (
-			<TouchableWithoutFeedback onPress={ this._onPress }>
+			<Pressable accessible={ false } onPress={ this._onPress }>
```
Comment (dcalhoun) [inline packages/react-native-aztec/src/AztecView.js:308]: Disabling `accessible` is interesting. What was the catalyst for this change? Have we tested its impact on Android?

**Comment by twstokes** [comment]
- VoiceOver with an assistive input (Braille Screen Input)
  - ✅ Adding content to the title and a Paragraph block
  - ✅ Adding content to the HTML editor
  - ✅ Using the Search block in the inserter
  - ✅ Updating an Image caption
- ✅ Bluetooth keyboard input with VoiceOver enabled

All tests passed for me @geriux! Thank you! 🚀

**Review by dcalhoun — COMMENTED** [review]
Thank you! The test plan succeed for me. 🎉 From my testing the experience mirrored that found in the 22.9 release.

File: packages/react-native-aztec/src/AztecView.js (hunk 1 above)
Comment (geriux) [reply packages/react-native-aztec/src/AztecView.js:308]: Great question, sorry I didn't include it in the PR description or as an inline comment in the PR changes 😅 

So I realized we needed to disable the `accessibility` for the `Pressable` component when the E2E tests started to fail, by inspecting using Appium Inspector I saw the TextInput within the Paragraph block couldn't be found, instead a `XCUIElementTypeOther` element was showing up.

By checking React Native's [accessibility documentation](https://reactnative.dev/docs/accessibility#accessible) I saw this:

> When `true`, indicates that the view is an accessibility element. When a view is an accessibility element, it groups its children into a single selectable component. By default, all touchable elements are accessible.

So the expected `XCUIElementTypeStaticText` wasn't there. By disabling the parent's `accessible` prop it allows children's components to show up in the tree. We have other places in the app where we do this too so it shouldn't cause any unexpected behaviors 🤞 

I've double-checked on Android and TalkBack works as expected.

**Review by dcalhoun — APPROVED** [review]

**Comment by dcalhoun** [comment]
This is definitely worth adding a release note IMO.

**Comment by geriux** [comment]
> This is definitely worth adding a release note IMO.

Yup! But I was wondering if it'd make things easier if we add it when we cherry-pick it, what do you think? To prevent possible conflicts 😅

**Comment by dcalhoun** [comment]
> > This is definitely worth adding a release note IMO.
> 
> Yup! But I was wondering if it'd make things easier if we add it when we cherry-pick it, what do you think? To prevent possible conflicts 😅

Ah, that makes and works for me. 

For another time: we should automate this. 😄
