### PR TITLE
Fix multi-entity multi-property undo redo

### LINKED ISSUE #12075: Undo / Redo unreliable with the post title
Splitting this out from https://github.com/WordPress/gutenberg/issues/5685#issuecomment-439831378 / #10650

#10650 improved a lot the Undo / Redo behavior with regards to RichText.

However, seems the post title is not always included in the undo / redo history. Following the steps listed on https://github.com/WordPress/gutenberg/issues/5685#issue-306271173 there are still cases where the post title is not restored or not removed when undoing / redoing.

Quoting @iseulde:
> I think only blocks are included in the history reducers.

I haven't followed this part of the development but seems to me it's something worth investigating.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #12075

It's been sometime I didn't dig into the undo/redo reducer and while taking a deep look into it, I noticed a fundamental issue in how the stack is recorded and applied when undoing/redoing.

### How Undo works ?

To understand the issue and the need for this PR to solve it, we first need to understand how the undo/redo works in Gutenberg. 

In trunk, for any change done in the editor, a "set of edits" is added to a list of undos. Each edit, contain the following information: The identifier of the modified entity/record + the set of edits to apply when going (either back or forth) to that state. So the list resembles something like this:

 - entity1, { property1: value1, property2: value2 }
 - entityX { propertyX: valueX, propertyY: valueY }
 - ...

We also keep track of a "pointer" to a particular "step" in this list. By default the pointer is always pointing at the last step (current step) and when calling "undo" it goes back by 1 step (and opposite for redo). 

Each time this step is modified (undo or redo called), we retrieve the set of "edits" corresponding to that step and apply it.

### How do these steps gets recorded

This is a bit complex (as there are edge cases) but for the regular case, the behavior is the following: Let's stay initially the "undo list" contained the following content:

- entity1, { property1: value1 }

The user in the UI edits property1 with value12, the list becomes:

- entity1, { property1: value1 }
- entity1, { property1: value12 }

The user in the UI edits property2 with value22 (let's also assume that the previous value of value2 was value21 but this was not in the undo list, it's just the saved value), the list becomes

- entity1, { property1: value1 }
- entity1, { property2: value21 }
- entity1, { property2: value22 }

Notice that for the second item (penultimate item) of the list, we actually updated the edits to store the previous value of  property2. The reason we do this is because when "undoing" to that step, we need to restore the previous value, so we need to "edit" value2 to set the previous value.

And here's the bug, now let's say with used undo twice, we went to the initial step (property 1 is value1), and now we "redo" to move to the pointer to step2. What will happen now is that the edits of step2 will be applied, so `property2 set to value21` but if you remember properly, in step2, property1 need to be set to value12 and it didn't happen. (This is the bug recorded in #12075)

So what this tells us is that for each "step" in the undo list, we need to record both:

 - The edits to apply when we go up the list (redo)
 - The edits to apply when we go down the list (undo)

### Multi-entity bug

Worth nothing that in trunk, the undo/redo suffer also from the "multi-entity" diff problem. Each diff can contain multiple properties (especially when using transient edits) but in theory "multi-entity" diffs are possible. So each "diff" should be a list of diffs instead.

### Solution

One solution to this is to update the "diff" format to use a (from, to) tupples instead, so for the example above, we should have the following undo stack:

- [ { entity1,  property1, from: value1, to: value12 } ]
- [ { entity2,  property2, from: value21, to: value22 } ]

And when undoing, we use the pointer to retrieve the current diff and edit the entities using the "from" values. (Restore the from values), while for redos, we'd use the "to" values.

Now, this solves navigating up and down the list and we'll get the expected result (and works both for multi property and multi entities).

**This is the main change in this PR** 

 - It changes the format of the undo list in the reducer
 - It allows "multiple edits from multiple entities" to be applied at the same time (using UNDO, REDO actions for now)
 - It also contains secondary changes to simplify the reducer: more specifically "flattenedUndo" is replaced with "cache" which represents a list of multi entity edits that have been performed but no "undo" step has been created for them, they are just waiting for the "next" undo step to be created. This is needed to support "transient entity changes" and "stacked undo steps in RichText".
 - Unfortunately, since the format of the list change and the format is currently exposed in `getUndoEdit`/`getRedoEdit`, this PR contains a breaking change right now. Ideally these selectors should have been private, I'll find a way to solve this by using new private selectors and trying to return something similar in format for these two selectors and probably deprecate them.

There are some extra simplifications that are possible to our undo/redo APIs but are not included in this PR.

**Todo**

 - [x] Ensure all existing unit/e2e tests pass.
 - [x] Add a unit test and/or e2e test for the specific issue being fixed.
 - [x] Backward compatibility for getUndoEdit / getRedoEdit

**Testing instructions**

 - Create a new post
 - Type a character in the post title
 - Remove that character from the post title
 - Type something in the post content
 - Undo until the post title is filled back with the initial character
 - Redo ==> the character should get removed again.

### CODE REVIEW

File: packages/core-data/src/test/reducer.js [hunk 1]
```diff
@@ -305,18 +302,17 @@ describe( 'undo', () => {
...
-			expectedUndoState.length - 1
-		].edits.transientValue = 2;
+		expectedUndoState.list[
+			expectedUndoState.list.length - 1
+		][ 0 ].edits.transientValue = 2;
 		expect( undoState ).toEqual( expectedUndoState );
 
-		// Check that undo levels are created with the latest action,
-		// even if undone.
+		// Check that create after undo does nothing.
```
Comment (youknowriad) [inline packages/core-data/src/test/reducer.js:348]: This is the only place where I disagree with the previous expectations/behavior.

File: packages/core-data/src/actions.js [hunk 2]
```diff
@@ -406,14 +407,14 @@ export const editEntityRecord =
 export const undo =
 	() =>
 	( { select, dispatch } ) => {
-		const undoEdit = select.getUndoEdit();
+		// Todo: we shouldn't have to pass "root" here.
+		const undoEdit = select( ( state ) => getUndoEdits( state.root ) );
```
Comment (youknowriad) [inline packages/core-data/src/actions.js:411]: @adamziel @jsnajdr I've learned today that:

 - you can call private selectors like that in "thunks"
 - you can't (or at least I didn't see any way to do it) call `unlock( select ).somePrivateSelector()` in "thunks".
 - The first approach is buggy because I had to pass `state.root` instead of just `state` (`state.root` should be just an internal thing, the store author shouldn't even know it exists).

Fixing that bug is going to be a breaking change. Maybe we can still "proxy" .root and deprecate it somehow though. I'm not fixing this in this unrelated PR but just wanted to let you know about this.

File: package-lock.json [hunk 3]
```diff
@@ -29227,7 +29227,7 @@
 		"co": {
 			"version": "4.6.0",
 			"resolved": "https://registry.npmjs.org/co/-/co-4.6.0.tgz",
-			"integrity": "sha1-bqa989hTrlTMuOR7+gvz+QMfsYQ=",
```
Comment (ntsekouras) [inline package-lock.json:29230]: Do we need these changes?

**Comment by jsnajdr** [comment]
Reading your description of the undo stack data structure, I'm wondering if we shouldn't be storing diffs? Like:
```
entity1: { property2: { from: value21, to: value22 } }
```
Then each edit creates one undo stack record, and doesn't need to amend the penultimate one. Going through the stack backward or forward would be applying the diffs in the desired direction. It's like having a classic diff:
```diff
@@ property2
- value21
+ value22
```
and then applying it either with `patch` or `patch -R`. To be able to apply the patch in both directions, we need both the `-` and `+` values. In one-directional diff, only one value would be needed, the other is just for integrity checking.

The currently implemented format -- and this PR is only bugfixing it, not fundamentally changing it -- basically stores _snapshots_ at each step. Only the snapshots are not complete, but compressed: they store only the modified properties. After modifying `property2` or `entity2`, the older snapshots become incomplete and must be completed.

**Comment by youknowriad** [comment]
@jsnajdr It is possible indeed. But I think it's probably a change that is too big IMO. Worth noting that editing the penultimate edit was being done before too but in a buggy way.

**Comment by youknowriad** [comment]
@jsnajdr I'll probably explore it separately to see what we get.

File: packages/core-data/src/reducer.js [hunk 4]
```diff
@@ -183,6 +183,26 @@ export function themeGlobalStyleVariations( state = {}, action ) {
 	return state;
 }
 
+const withMultiEntityRecordEdits = ( reducer ) => ( state, action ) => {
+	if ( action.type === 'UNDO' || action.type === 'REDO' ) {
+		const { stackedEdits } = action;
+
+		let newState = state;
```
Comment (ntsekouras) [inline packages/core-data/src/reducer.js:190]: Should we shallow copy the state here?

File: packages/core-data/src/reducer.js [hunk 5]
```diff
@@ -436,107 +456,110 @@ let lastEditAction;
...
-					( key ) => ! action.transientEdits[ key ]
-				)
-			) {
-				// @ts-ignore we might consider using Object.assign({}, state)
-				nextState = [ ...state ];
-				nextState.flattenedUndo = {
-					...state.flattenedUndo,
-					...action.edits,
+			const isCachedChange = Object.keys( action.edits ).every(
+				( key ) => action.transientEdits[ key ]
```
Comment (ntsekouras) [inline packages/core-data/src/reducer.js:547]: Could the usage of `every` affect the logic here, taking into account that an empty array will return `true`?

**Review by ntsekouras — COMMENTED** [review]
Thanks Riad! Took a first pass here and tests well. I'll have to take a better look though because of the high complexity.

File: packages/core-data/src/actions.js (hunk 2 above)
Comment (jsnajdr) [reply packages/core-data/src/actions.js:411]: Thunks themselves are a private implementation detail of the store. The user of the store doesn't see how a particular action is implemented.

Therefore, the thunk should be able to see the private selectors and actions without having to unlock anything. The `select` object passed into a thunk should be already "unlocked", it should expose all the private selectors and let you call `select.getUndoEdits()` directly.

The same applies to private actions and the `dispatch` object.

Note that the ability to pass functions to `select` and `dispatch`, i.e., calling them as `select( state => state.foo )` or `dispatch( { type: 'BAR' } )`, is also unique to thunks -- see how the `thunkArgs` properties are constructed with `Object.assign` [here](https://github.com/WordPress/gutenberg/blob/2b687d03ecdfb52229c25d5d455038b14fc8fa89/packages/data/src/redux-store/index.js#L148-L166). This allows the thunk to access the `state` directly and dispatch actions to the reducer directly.

If `select` doesn't expose private selectors, we need to fix the `thunkArgs` construction: instead of `getSelectors()` we need to get the "unlocked" selectors.

> The first approach is buggy because I had to pass `state.root` instead of just `state`

It seems like this was intentional because we're passing `store.__unstableOriginalGetState()` to `select()` [here](https://github.com/WordPress/gutenberg/blob/2b687d03ecdfb52229c25d5d455038b14fc8fa89/packages/data/src/redux-store/index.js#L159). If we didn't want that, we could very easily pass `store.getState()`. Or was this an oversight that I and @adamziel didn't catch 2 years ago?

File: package-lock.json (hunk 3 above)
Comment (youknowriad) [reply package-lock.json:29230]: Probably not, these are auto-generated by npm install. I'll revert them.

File: packages/core-data/src/private-selectors.ts [hunk 6]
```diff
@@ -0,0 +1,30 @@
...
+
+/**
+ * Returns the previous edit from the current undo offset
+ * for the entity records edits history, if any.
+ *
+ * @param state State tree.
+ *
+ * @return The edit.
+ */
+export function getUndoEdits( state: State ): Optional< any > {
```
Comment (jsnajdr) [inline packages/core-data/src/private-selectors.ts]: We know the return value is an array so `Optional< unknown[] >` should be better.

File: packages/core-data/src/reducer.js (hunk 5 above)
Comment (youknowriad) [reply packages/core-data/src/reducer.js:547]: No, it's fine to consider "no edits" as "cached change".

File: packages/core-data/src/reducer.js (hunk 4 above)
Comment (youknowriad) [reply packages/core-data/src/reducer.js:190]: No, it's fine, this is a Higher order reducer that doesn't perform changes on its own, the lower level reducers will copy the state if needed.

File: test/e2e/specs/editor/various/undo.spec.js [hunk 7]
```diff
@@ -455,6 +455,35 @@ test.describe( 'undo', () => {
...
 		] );
 	} );
+
+	// @see https://github.com/WordPress/gutenberg/issues/12075
+	test( 'should be able to undo and redo property cross property changes', async ( {
+		page,
+		pageUtils,
+	} ) => {
+		await page.getByRole( 'textbox', { name: 'Add title' } ).type( 'a' ); // First step.
+		await page.keyboard.press( 'Backspace' ); // Second step.
```
Comment (ellatrix) [inline test/e2e/specs/editor/various/undo.spec.js:465]: Could we also add a test for this for blocks? The title case is a bit different? Maybe we need some logic in RichText that treats Backspace changes differently from input, which normally only marks changes as persistent after 1s.

https://github.com/WordPress/gutenberg/blob/2b687d03ecdfb52229c25d5d455038b14fc8fa89/packages/block-editor/src/components/rich-text/use-mark-persistent.js#L12

File: packages/core-data/src/reducer.js [hunk 8]
```diff
@@ -436,107 +456,110 @@ let lastEditAction;
  * @return {UndoState} Updated state.
  */
 export function undo( state = UNDO_INITIAL_STATE, action ) {
+	const omitPendingRedos = ( currentState ) => {
```
Comment (ellatrix) [inline packages/core-data/src/reducer.js:463]: Nit: why not use named functions for easier debugging?

File: packages/core-data/src/reducer.js [hunk 9]
```diff
@@ -411,8 +433,9 @@ export const entities = ( state = {}, action ) => {
 /**
  * @typedef {Object} UndoStateMeta
  *
- * @property {number} offset          Where in the undo stack we are.
- * @property {Object} [flattenedUndo] Flattened form of undo stack.
+ * @property {number} list   The undo stack.
+ * @property {number} offset Where in the undo stack we are.
+ * @property {Object} cache  Cache of unpersisted transient edits.
```
Comment (ellatrix) [inline packages/core-data/src/reducer.js:442]: What exactly is this cache?

Comment (ellatrix) [reply packages/core-data/src/reducer.js:442]: Sounds like that's just unpersisted edits, not really cache?

File: packages/core-data/src/reducer.js [hunk 10]
```diff
@@ -436,107 +456,110 @@ let lastEditAction;
...
-						};
-					}
-					action = lastEditAction;
-				} else {
-					return nextState;
-				}
-			}
+		case 'UNDO':
+		case 'REDO': {
+			const nextState = appendCachedEditsToLastUndo( state );
```
Comment (ellatrix) [inline packages/core-data/src/reducer.js:534]: Why do we persist unpersisted changes on redo? Normally it should no longer be possible to redo once there are more changes made?

File: packages/core-data/src/reducer.js (hunk 9 above)
Comment (youknowriad) [reply packages/core-data/src/reducer.js:442]: It's a cache of "edits" that were not added to the "undo" stack yet.

File: packages/core-data/src/reducer.js (hunk 10 above)
Comment (youknowriad) [reply packages/core-data/src/reducer.js:534]: In theory it's not going to do anything at all because when you call "undo", the "unpersisted changes" are persisted. 
So whenever you have a "redo", there's probably no cached changes. The code is here for the "undo" case. (to share the same code) but I can add a check if needed.

File: packages/core-data/src/actions.js (hunk 2 above)
Comment (youknowriad) [reply packages/core-data/src/actions.js:411]: > If select doesn't expose private selectors, we need to fix the thunkArgs construction: instead of getSelectors() we need to get the "unlocked" selectors.

Yes, I tried without unlocking and it doesn't work, these things are not available.

> It seems like this was intentional because we're passing store.__unstableOriginalGetState() to select() [here](https://github.com/WordPress/gutenberg/blob/2b687d03ecdfb52229c25d5d455038b14fc8fa89/packages/data/src/redux-store/index.js#L159). If we didn't want that, we could very easily pass store.getState(). Or was this an oversight that I and @adamziel didn't catch 2 years ago?

I'd argue that it's oversight because all selectors receive the "state" and not the "original state" with metadata (which is an internal thing added by the data module).

File: packages/core-data/src/reducer.js (hunk 8 above)
Comment (mcsf) [reply packages/core-data/src/reducer.js:463]: Function declarations in `const f = (...) =>` syntax are equivalent to named functions. I don't remember when this started, but it's been some years. See for yourself, even in Safari:

```js
(() => {
    const foo = () => 42
    const bar = foo

    function logFunctionName(fn) {
        console.log(fn.name)
    }

    logFunctionName(bar);
})() // logs 'foo'
```

(But I agree that we should name our callbacks when possible.)

Comment (ellatrix) [reply packages/core-data/src/reducer.js:463]: Ah cool! So all these anon functions are anon because they're not assigned to a var?

**Comment by youknowriad** [comment]
@jsnajdr Here's the alternative exploration (on top of this branch) https://github.com/WordPress/gutenberg/pull/51002
As you can see in the code, I don't think there's a very big difference between both but I prefer this new alternative as it's conceptually slightly better and easier to understand. It does store a bit more "bits" in the state but I think it's fine.

I'll be waiting for the tests to pass on that PR to merge into the current one.

**Comment by youknowriad** [comment]
I've merged the other PR into this one and updated the PR description accordingly. We're now using the alternative "diff" format as suggested by @jsnajdr

File: test/e2e/specs/editor/various/undo.spec.js (hunk 7 above)
Comment (youknowriad) [reply test/e2e/specs/editor/various/undo.spec.js:465]: Can you give me an example of test you have in mind. The issue fixed by this PR is hardly reproducible with blocks in trunk.

**Comment by youknowriad** [comment]
This is ready to ship. Any approvals/reviews?

File: packages/core-data/src/reducer.js [hunk 11]
```diff
@@ -489,30 +493,31 @@ export function undo( state = UNDO_INITIAL_STATE, action ) {
...
-				...( existingEditIndex !== -1
-					? stack[ existingEditIndex ].edits
-					: {} ),
-				...edits,
-			},
-		} );
+		const nextStack = [ ...stack ];
+		if ( existingEditIndex !== -1 ) {
+			// If the edit is already in the stack leave the initial "from" value.
+			nextStack[ existingEditIndex ].to = to;
```
Comment (jsnajdr) [inline packages/core-data/src/reducer.js]: This is modifying also the _previous_ stack, which should remain immutable. The `[...stack]` statement does only a shadow one-level copy, but we're doing a modification at the second level, where both stack share the data.

Comment (jsnajdr) [reply packages/core-data/src/reducer.js]: There is a change in how `appendEditsToStack` merges new edits into existing ones. The old version pushed the merged edit at the end, and removed the existing one. The new version modifies the existing one, leaving it at the original position. Is that intentional or is it a mistake?

File: packages/core-data/src/reducer.js [hunk 12]
```diff
@@ -529,37 +534,41 @@ export function undo( state = UNDO_INITIAL_STATE, action ) {
...
+					to: action.edits[ key ],
+				};
+			} );
+
 			if ( isCachedChange ) {
+				let newCache = state.cache;
+				edits.forEach(
+					( edit ) =>
+						( newCache = appendEditToStack( newCache, edit ) )
+				);
```
Comment (jsnajdr) [inline packages/core-data/src/reducer.js]: Use a reducer pattern here:
```js
const newCache = edits.reduce( appendEditToStack, state.cache );
```
There are multiple opportunities to this, e.g., the `stackedEdits.forEach` loop could be turned into `stackedEdits.reduce`.

File: packages/core-data/src/reducer.js (hunk 11 above)
Comment (youknowriad) [reply packages/core-data/src/reducer.js]: > The new version modifies the existing one, leaving it at the original position. Is that intentional or is it a mistake?

It doesn't matter, I just went for the simplest here. I'll fix the mutation though. Good catch.

File: packages/core-data/src/reducer.js (hunk 12 above)
Comment (youknowriad) [reply packages/core-data/src/reducer.js]: I like less and less reduce to generate objects based on arrays personally, I find that code less readable.

Comment (youknowriad) [reply packages/core-data/src/reducer.js]: You're right that it's a great fit for this one though :)

Comment (jsnajdr) [reply packages/core-data/src/reducer.js]: If you mean the popular pattern where we do:
```js
items.reduce( ( acc, [ key, value ] ) => {
  acc[ key ] = value;
  return acc;
}, {} );
```
then I totally agree with you, doing a for loop or using `Object.fromEntries` is much better.

But our case is different, `appendEditsToStack` _is_ a reducer function, and applying it with `.reduce` makes perfect sense, that's _exactly_ what `.reduce` is for.

File: packages/core-data/src/reducer.js [hunk 13]
```diff
@@ -436,107 +460,113 @@ let lastEditAction;
...
+
+		let nextState = {
+			...currentState,
+			list: [ ...currentState.list ],
+		};
+		nextState = omitPendingRedos( nextState );
+		let previousUndoState = nextState.list.pop();
+		currentState.cache.forEach( ( edit ) => {
+			previousUndoState = appendEditToStack( previousUndoState, edit );
+		} );
```
Comment (jsnajdr) [inline packages/core-data/src/reducer.js]: Could also be `reduce` 🙂

**Review by jsnajdr — APPROVED** [review]
Looks good 👍
