### PR TITLE
Fix slashing when creating or updating a menu item

### LINKED ISSUE #25094: REST API: Audit menus endpoint slashing
Data in the `WP_REST_Request` object is unslashed. We need to make sure that whenever we are calling WordPress APIs that expect slashed data ( most of them ) we are slashing our data before hand.

On a first pass, it looks like the data passed to `wp_update_nav_menu_item` is not being slashed.

### PR DESCRIPTION
**Pull request by anton-vlasenko**
## Description
The data passed to `wp_update_nav_menu_item` function is not being slashed when using `WP_REST_Menu_Items_Controller` controller.
The goal of this PR is to slash data before calling the `wp_update_nav_menu_item` function.
Other experimental endpoints have been audited and it seems that the issue only affects this (`__experimental/menu-items`) endpoint.
Fixes https://github.com/WordPress/gutenberg/issues/25094

## How has this been tested?
1. Go to the Gutenberg -> Experiments page and enable `Navigation screen` feature.
2. Save the changes.
3. Go back to your browser, and open the Gutenberg  -> Navigation page.
4.  Run the following JavaScript code in your browser's console:
```javascript
wp.apiFetch( {
    path: '/__experimental/menu-items',
    method: 'POST',
    data: { title: "Some \\\'title", url: 'https://my.test.url' },
} ).then( ( res ) => {
    console.log( res );
} );
```
5. Connect to the database, check the contents of the `wp_posts` table.
**Expected result**:
You should see `Some \'title` in the `post_title` column (not `Some 'title`).

## Screenshots 
No screenshots are needed to test this issue.

## Types of changes
Bug fix.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by adamziel** [comment]
Would you please add a test case for that? It would prevent regressions and make the issue apparent.

File: lib/class-wp-rest-menu-items-controller.php [hunk 1]
```diff
@@ -181,7 +181,7 @@ public function create_item( $request ) {
 		}
 		$prepared_nav_item = (array) $prepared_nav_item;
 
-		$nav_menu_item_id = wp_update_nav_menu_item( $prepared_nav_item['menu-id'], $prepared_nav_item['menu-item-db-id'], $prepared_nav_item );
+		$nav_menu_item_id = wp_update_nav_menu_item( wp_slash( $prepared_nav_item['menu-id'] ), wp_slash( $prepared_nav_item['menu-item-db-id'] ), wp_slash( $prepared_nav_item ) );
```
Comment (spacedmonkey) [inline lib/class-wp-rest-menu-items-controller.php]: Why do we need to slash menu id and db id here? Feels like overkill.

**Comment by anton-vlasenko** [comment]
@adamziel 
> Would you please add a test case for that? It would prevent regressions and make the issue apparent.

Thank you for the review.
I absolutely agree. I think we should encourage writing unit tests for the new code/ bug fixes.
Fixed in 2dcf97b255b399bd8086a27397cea9e9de9f9c64.

File: lib/class-wp-rest-menu-items-controller.php (hunk 1 above)
Comment (anton-vlasenko) [reply lib/class-wp-rest-menu-items-controller.php]: Good catch! Fixed in 3c36175618efccbcafb9dab6d4d9bfc54c741fb5

**Review by TimothyBJacobs — APPROVED** [review]
Looks great, nice catch!

**Review by spacedmonkey — APPROVED** [review]
Looks good to me

**Review by adamziel — APPROVED** [review]

**Comment by adamziel** [comment]
This PR looks good, but I have a bigger question.

This slashing problem confuses me. What is the role of `wp_slash` here? Is it to defend against SQL inject? This sounds like a model concern. Is it to defend XSS? This sounds like a rendering concern. Why do we have to call `wp_slash` it in the API endpoint @TimothyBJacobs ?

**Comment by TimothyBJacobs** [comment]
> This slashing problem confuses me. What is the role of `wp_slash` here? Is it to defend against SQL inject? This sounds like a model concern. Is it to defend XSS? This sounds like a rendering concern. Why do we have to call `wp_slash` it in the API endpoint @TimothyBJacobs ?

The vast majority of WP APIs expect slashed data, and call `wp_unslash` on the input. While WordPress slashes inputs via `wp_magic_quotes`, the `WP_REST_Request` objects intentionally contain unlashed data. So we need to slash the data when we pass it to the WP APIs.

**Comment by Mamaduka** [comment]
Thanks for working on this, @anton-vlasenko.

I'm going to merge the PR since we already have three approvals.
