### PR TITLE
RichText: collapse toolbar

### LINKED ISSUE #13762: Searching for inline image suggests no blocks found even though they are
Steps to reproduce:

- Set cursor in text
- Open block library in the top-bar
- Search for "inline"

You'll see this:

screenshot 2019-02-08 at 09 36 56

This is misleading because there _is_ actually an inline block present:

screenshot 2019-02-08 at 09 37 01

Suggested fix is to not show the "no blocks found" message when an inline block is found, and to open the collapsed panel.

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

This PR solves two problems:

* Currently, all rich text controls that are added by plugins are added to the block toolbar. This can get quickly out of hand, breaking the block toolbar. The solution would be to put overflowing buttons in a dropdown. I decided to cut this after Bold, Italic and Link, which are by far the most used buttons.
* Moves the inline image button from the block inserter to the rich text drop down. The block inserter doesn't seem to be a good place for the inline image button. Lots of people have reported that they cannot find the button, and this makes sense as it doesn't really belong in the block inserter, but better with inline tools.

Fixes #13762.

Block toolbar:

screenshot 2019-03-05 at 10 29 17

The arrow down is the same as the one in the block switcher and alignment switcher, so it doesn't feel too much.

Rich text dropdown:

screenshot 2019-03-05 at 10 51 56

This is the same kind of menu as the alignment dropdown:

screenshot 2019-03-05 at 10 29 36

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by jasmussen** [comment]
Wow, this is really nice! GIF:

dropdown

It's not the magical wonderous responsiveness that we've been dreaming of, where you scale the block toolbar by width and stuff happens magically inside. But it's a *solid* step in the right direction. Your argument about making the cutoff at the "strikethrough" is solid to me as well — and honestly I feel this paves the way for us to add text color and inline text highlight tools to core as well. And finally it doesn't block even better responsiveness tools to land in the future.

I pushed a small fix to balance the margins so the dropdown is centered when hovered:

screenshot 2019-03-05 at 11 16 36

Can we add a tooltip as well? Accessibility wise it seems good to me, but it might be nice to get a sanity check here as well.

Nice work!

**Comment by ellatrix** [comment]
@jasmussen Thanks for the polish! I added a tooltip. :)

File: packages/editor/src/components/rich-text/format-toolbar/index.js [hunk 1]
```diff
@@ -11,7 +18,16 @@ const FormatToolbar = ( { controls } ) => {
 				{ controls.map( ( format ) =>
 					<Slot name={ `RichText.ToolbarControls.${ format }` } key={ format } />
 				) }
-				<Slot name="RichText.ToolbarControls" />
+				<Slot name="RichText.ToolbarControls">
+					{ ( fills ) =>
```
Comment (gziolo) [inline packages/editor/src/components/rich-text/format-toolbar/index.js]: Should `DropdownMenu` be conditionally included only when there are fills to render?

File: packages/format-library/src/image/index.js [hunk 2]
```diff
@@ -87,11 +87,11 @@ export const image = {
 
 			return (
 				<MediaUploadCheck>
-					<RichTextInserterItem
-						name={ name }
+					<RichTextToolbarButton
```
Comment (gziolo) [inline packages/format-library/src/image/index.js]: Does it mean we no longer want to keep `RichTextInserterItem` component?

**Comment by gziolo** [comment]
There are tests failing:

```
FAIL packages/e2e-tests/specs/plugins/format-api.test.js (10.174s)
```

It seems like they need to be updated to work with this newly introduced dropdown menu.

File: packages/format-library/src/image/index.js (hunk 2 above)
Comment (ellatrix) [reply packages/format-library/src/image/index.js]: Yes, let's remove it. It hasn't been documented.

File: packages/editor/src/components/rich-text/format-toolbar/index.js [hunk 3]
```diff
@@ -11,7 +18,16 @@ const FormatToolbar = ( { controls } ) => {
 				{ controls.map( ( format ) =>
 					<Slot name={ `RichText.ToolbarControls.${ format }` } key={ format } />
 				) }
-				<Slot name="RichText.ToolbarControls" />
+				<Slot name="RichText.ToolbarControls">
+					{ ( fills ) => fills.length &&
+						<DropdownMenu
```
Comment (youknowriad) [inline packages/editor/src/components/rich-text/format-toolbar/index.js]: In terms of design, any button added to the block toolbar should ideally be wrapped in `<Toolbar>`. There are many examples of this in the code base and it gives the right aria-roles, design...

**Comment by ellatrix** [comment]
@youknowriad Could you point me to such an example? The ones I see have the menu role, and the items are menu items. This dropdown is just like the alignment dropdown.

**Comment by youknowriad** [comment]
The block alignment and the alignment toolbars both use the `Toolbar` component, The block switcher also uses a `Toolbar` component with a button inside it. 

IIRC just wrapping any button in a `Toolbar` component gives it the right design for the block toolbar. The `Toolbar` component also has an `isCollapsed` flag, you could force to true. Is this not enough for the use-case here?

**Comment by ellatrix** [comment]
@youknowriad I still don't understand. It has the right design? I've attached some screenshots above. The button is also wrapped in a toolbar:

screenshot 2019-03-05 at 17 07 51

**Comment by ellatrix** [comment]
https://github.com/WordPress/gutenberg/blob/4bcd44cbb4a311f808f19bcce91314c775e94264/packages/editor/src/components/rich-text/format-toolbar/index.js#L17-L23

**Comment by youknowriad** [comment]
mmm Right, I missed that it was already inside the formatting toolbar. I guess what bothers me is the width of the button as it's not similar to the other ones.

**Comment by ellatrix** [comment]
I like that it's smaller. It's also in line with the icons for the block switcher and alignment switcher.

**Comment by iamthomasbishop** [comment]
Thanks for the work on this thus far! I love that we're thinking about how we can accommodate smaller screens, and I like the ideas y'all are exploring. I have a one tiny bit of drive-by feedback with regards to mobile.

Beyond the personal/visual preference of the dropdown icon feeling too small (which I agree with @youknowriad on), it appears that the button doesn't provide adequate tap area. Unless my eyes are playing tricks on me, it looks like the current buttons are 36x36, so for now I'd at least match that. Then in the future I would consider going with ≥44pt (via iOS HIG) or better yet ≥48dp (via Google Material).

Obviously that concern isn't limited to this specific button, and it's another separate project, but maybe something to consider/keep in mind moving forward. :)

**Comment by ellatrix** [comment]
Okay, sounds good, I can make the button bigger.

**Comment by ellatrix** [comment]
@iamthomasbishop @youknowriad @jasmussen I made is so that the button is the same size as other buttons in the toolbar.

screenshot 2019-03-07 at 12 58 29

**Comment by jasmussen** [comment]
Nice, can you then remove the right margin I added to the drop-down icon, or is that still necessary to balance things?

**Comment by ellatrix** [comment]
@jasmussen I replaced it in 88bfc3ef7fde5247851b8f1d223078ec2f74b5ea.

**Comment by jasmussen** [comment]
🤘

**Comment by iamthomasbishop** [comment]
Looks great, thanks @ellatrix!

**Review by youknowriad — APPROVED** [review]
I like this, I like that we remove the inline items from the inserter, it was confusing for a lot of people there (based on feedback), that said, it's not a trivial change in terms of UI. So I'd appreciate an approval from designers @jasmussen @mapk

**Review by jasmussen — APPROVED** [review]
Yep, this is solid. Couldn't break it on any breakpoint, or with fullscreen or top toolbar or anything. It solves a problem and takes steps in the right direction. It's also a good place for the Inline Image button. 

It's entirely possible additional enhancements can be made in the future, but this is a solid PR.

**Comment by ellatrix** [comment]
Thanks for the reviews!

File: packages/editor/src/components/rich-text/format-toolbar/index.js (hunk 3 above)
Comment (gziolo) [reply packages/editor/src/components/rich-text/format-toolbar/index.js]: I think we are using:
```js
{ ( fills ) => ! isEmpty( fills ) && (
```
in other places. I don't remember why. Ideally, we should be using `fills.length`.

File: packages/editor/src/components/index.js [hunk 4]
```diff
@@ -22,7 +22,6 @@ export {
 	default as RichText,
 	RichTextShortcut,
 	RichTextToolbarButton,
-	RichTextInserterItem,
```
Comment (youknowriad) [inline packages/editor/src/components/index.js]: Is this a breaking change? Should we stub it at least to avoid breakage or find a way to move it automatically to the toolbar?

File: packages/editor/src/components/rich-text/format-toolbar/index.js (hunk 3 above)
Comment (gziolo) [reply packages/editor/src/components/rich-text/format-toolbar/index.js]: Okey, I double checked our code and it's safe to use `fills.length`. We should default to it moving on 👍 

Intrernally we use `map` from lodash which ensures it returns an array:
https://github.com/WordPress/gutenberg/blob/master/packages/components/src/slot-fill/slot.js#L66

screen shot 2019-03-08 at 11 14 51

File: packages/editor/src/components/index.js (hunk 4 above)
Comment (gziolo) [reply packages/editor/src/components/index.js]: Yeah, mapping to `RichTextToolbarButton` should do the trick.

**Comment by azaozz** [comment]
I'm not sure this is a good thing to do. It closely resembles the "Toolbar Toggle" button in the classic editor which was one of the most "questionable" functionality there. My (unofficial) stats were that about 90% of the people would open the second toolbar row there and leave it open ...forever (guessing the other 10% didn't know what that button does, and were afraid to test it) :)

> ...decided to cut this after Bold, Italic and Link, which are by far the most used buttons

Shouldn't the toolbar be roughly the same width as the block? Both visually and functionality wise that seems best. It would "fit" quite nicely visually, and at the same time won't obscure some of the (more useful) buttons. 

Then, what about the alignment buttons. They are pretty much useless in "all text" blocks/areas like the paragraph block. I see in the screenshots that they are in another drop-down/popup. If that is implemented would we still need to hide the arguably more useful toolbar buttons added by plugins?

File: packages/editor/src/components/rich-text/format-toolbar/index.js [hunk 5]
```diff
@@ -11,7 +18,16 @@ const FormatToolbar = ( { controls } ) => {
 				{ controls.map( ( format ) =>
 					<Slot name={ `RichText.ToolbarControls.${ format }` } key={ format } />
 				) }
-				<Slot name="RichText.ToolbarControls" />
```
Comment (technote-space) [inline packages/editor/src/components/rich-text/format-toolbar/index.js]: I used this slot to add some toolbar controls.
There is no longer a way to add any controls at this position, isn't it?

Comment (ellatrix) [reply packages/editor/src/components/rich-text/format-toolbar/index.js]: You should use the RichText API to add controls, not the slot id directly.

Comment (technote-space) [reply packages/editor/src/components/rich-text/format-toolbar/index.js]: Noted with thanks.
