### PR TITLE
RichText: warn when using inline container

### LINKED ISSUE #11839: RichText: warn when using inline tagName
**Describe the bug**
Create a RichText node in edit function. Fill with text content. Remove text with backspace key (selecting the text and deleting it all together does not cause this issue).  

**To Reproduce**
0. Create Richtext, e.g.
```
<RichText
	tagName={ 'span' }
	value={ citation }
	placeholder={ __( 'Write citation…' ) }
	onChange={
		( nextCitation ) => setAttributes( {
			citation: nextCitation,
		} )
	}
/>
```
1. Enter content into rich text field
2. Safe Document
3. Reload
4. Click into text
5. Delete text by hitting backspace multiple times
6. Last digit can not be removed

Error occurs:
`index.js?ver=1542114671:1 The given range isn't in document.`

**Expected behavior**
Text should be cleared if user tries to delete content letter by letter with backspace.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.14.1
 - Browser: all

**Additional context**
- Gutenberg Version 4.3.0
- Wordpress Version 4.9.8

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #11839. `RichText` (read: the browser) will not behave correctly when using an inline container. We should warn implementors about this. Not sure if I should wrap this in a script debug condition.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/editor/src/components/rich-text/index.js [hunk 1]
```diff
@@ -136,7 +136,17 @@ export class RichText extends Component {
 	}
 
 	setRef( node ) {
-		this.editableRef = node;
+		if ( node ) {
+			const computedStyle = getComputedStyle( node );
+
+			if ( computedStyle.display === 'inline' ) {
+				window.console.warn( 'RichText cannot be used with an inline container. Please use a different tagName.' );
```
Comment (talldan) [inline packages/editor/src/components/rich-text/index.js]: Is the use of `window.console.warn` is to get around the lint rule? In other places I noticed the rule is specifically disabled:
```
// eslint-disable-next-line no-console
console.warn( // ... );
```
I think it'd be better to follow that convention—if the eslint rule is updated in the future to cover `window.console` there would lint failures that need to be fixed.

File: packages/editor/src/components/rich-text/index.js [hunk 2]
```diff
@@ -136,7 +136,17 @@ export class RichText extends Component {
 	}
 
 	setRef( node ) {
-		this.editableRef = node;
+		if ( node ) {
+			const computedStyle = getComputedStyle( node );
```
Comment (talldan) [inline packages/editor/src/components/rich-text/index.js]: An option could be to only run this in dev environments and potentially throw an error, similar to the way the tooltip component does it:
https://github.com/WordPress/gutenberg/blob/f43572c8e55e692f45062ffaab0bdf8c8040b41b/packages/components/src/tooltip/index.js#L94-L97

That would avoid the need to run these extra checks in production.

Comment (iseulde) [reply packages/editor/src/components/rich-text/index.js]: Updated, thanks!

File: packages/editor/src/components/rich-text/index.js (hunk 1 above)
Comment (aduth) [reply packages/editor/src/components/rich-text/index.js]: > if the eslint rule is updated in the future to cover `window.console` there would lint failures that need to be fixed.

This conversation makes me want to update that rule now 😅

Comment (iseulde) [reply packages/editor/src/components/rich-text/index.js]: I wonder, now that we add the environment check, if we cannot just stop `RichText` from doing anything further. It will still work in production, but if you're trying to develop with RichText and inline elements, it just won't work. I think a lot of people will just ignore or be blind to the warning.

**Review by talldan — APPROVED** [review]
LGTM 👍
