### PR TITLE
Utils: Default to empty object for previous defined utils

### LINKED ISSUE #6063: wp-utils console error in version 2.6
## Issue Overview

Since version 2.6 there is a console log error as follows: `ReferenceError: Can't find variable: wp`. This is related to a line injected as follows: `var originalUtils = wp.utils;` from the ./lib/client-assets.php file.

This is because, I think, that line added the code 'before' wp-utils exists. Amended line 100 of ./lib/client-assets.php to include and 'after' argument, instead of 'before' fixes this error.

## Steps to Reproduce (for bugs)

1. Install and activate Gutenberg 2.6
2. Open a page where Gutenberg is active
3. View the console log in your browser

## Expected Behavior

There should be no console error.

## Current Behavior

There is a console error.

## Possible Solution

Current line 100 of the ./lib/client-assets.php file is as follows:
`wp_add_inline_script( 'wp-utils', 'var originalUtils = wp.utils;', 'before' );`

Change is to the following fixes the error:
`wp_add_inline_script( 'wp-utils', 'var originalUtils = wp.utils;', 'after' );`
## Todos
- [ ] Tests
I have tested on my local install and the error resolves.
- [ ] Documentation

### PR DESCRIPTION
**Pull request by youknowriad**
closes #6063

Depending on the order of the loaded scripts (which can change depending on the plugins used), we can see an error like this `ReferenceError: Can't find variable: wp` while depending on the `wp-utils` script because the global `wp` and `wp.utils` are not defined if this is the first script to be loaded.

This PR default to an empty object if one of these variables are not defined.

### CODE REVIEW

File: lib/client-assets.php [hunk 1]
```diff
@@ -97,7 +97,7 @@ function gutenberg_register_scripts_and_styles() {
 		filemtime( gutenberg_dir_path() . 'utils/build/index.js' ),
 		true
 	);
-	wp_add_inline_script( 'wp-utils', 'var originalUtils = wp.utils;', 'before' );
+	wp_add_inline_script( 'wp-utils', 'window.wp = window.wp || {}; var originalUtils = wp && wp.utils ? wp.utils : {};', 'before' );
```
Comment (aduth) [inline lib/client-assets.php]: Do we need the first part of this line? `window.wp = window.wp || {}; `

Comment (youknowriad) [reply lib/client-assets.php]: Well since the error is `ReferenceError: Can't find variable: wp` I believe so. If the `wp-utils` is the first script to be loaded, there will be no `wp` global defined at all before the script.

Comment (aduth) [reply lib/client-assets.php]: Oh, right. Though then it begs the question do we need the second part, `wp &&`, since we know it'll be defined since we just defined it if it wasn't.

Maybe we just test against the property on `window`:

```js
var originalUtils = window.wp && window.wp.utils ? window.wp.utils : {};
```
