### PR TITLE
Meta Boxes: Fix metaboxes using file inputs

### LINKED ISSUE #5341: Input[type="file"] is not handled when saving meta box
## Issue Overview

I'm the author of [Meta Box](https://metabox.io) plugin that helps developers to create custom fields. We have a field type of HTML `<input type="file">` that allows users to upload files. And after testing, the field doesn't work at all (other normal fields work as expected).

Regarding [the Gutenberg guide for meta box](https://github.com/WordPress/gutenberg/blob/master/docs/meta-box.md), the code that handles meta box saving is in [`editor-post/store/effects.js`](https://github.com/WordPress/gutenberg/blob/master/edit-post/store/effects.js#L71), which tries to gather all the inputs and submit via ajax like this:

```js
const formData = values( dataPerLocation )
	.concat( jQuery( '.metabox-base-form' ).serialize() )
	.concat( additionalData )
	.join( '&' );

// Save the metaboxes
wp.apiRequest( {
	url: window._wpMetaBoxUrl,
	method: 'POST',
	contentType: 'application/x-www-form-urlencoded',
	data: formData,
} )
.then( () => store.dispatch( metaBoxUpdatesSuccess() ) );
```

The problem is that the `values( dataPerLocation )` function ignores the inputs with `type=file`. While it works nicely for most of input types (`text`, `select`, etc.), somehow it doesn't handle the `file` type. And thus any custom fields that use a custom upload won't work.

## Steps to Reproduce (for bugs)

I guess it doesn't work for normal `input[type="file"]` in all cases, not just in Meta Box. But you can test with Meta Box at first.

To reproduce the bug, please install the [Meta Box](https://wordpress.org/plugins/meta-box/) plugin. Then put the following code into `functions.php` of the active theme:

```php
add_filter( 'rwmb_meta_boxes', function( $meta_boxes ) {
    $meta_boxes[] = [
        'title' => 'Test file upload',
        'fields' => [
            [
                'id' => 'file_upload',
                'type' => 'file',
                'name' => 'Test file',
            ]
        ],
    ];

    return $meta_boxes;
} );
```

Then go to add a new post and see how it works.

Any solution is appreciated! Thanks for your time and hard work!

### PR DESCRIPTION
**Pull request by youknowriad**
closes #5341

This PR fixes MetaBoxes using file inputs by replacing the `jQuery.serialize` calls with `FormData` usage. I needed to include a FormData polyfill though because `.append` is not supported properly in all browsers.

**Testing instructions**

Repeat testing instructions in #5341

### CODE REVIEW

File: edit-post/store/effects.js [hunk 1]
```diff
@@ -1,7 +1,8 @@
 /**
  * External dependencies
  */
-import { reduce, values, some } from 'lodash';
+import { reduce, some } from 'lodash';
+import 'formdata-polyfill';
```
Comment (aduth) [inline edit-post/store/effects.js]: Could we polyfill this as we do other features already in `client-assets.php` via `gutenberg_get_script_polyfill` for (a) consistency and (b) not loading / including the resource for browsers which _do_ support the feature?

File: edit-post/store/effects.js [hunk 2]
```diff
@@ -65,23 +66,33 @@ const effects = {
...
-			.concat( additionalData )
-			.join( '&' );
+		// We gather all the metaboxes locations data and the base form data
+		const baseFormData = new window.FormData( document.querySelector( '.metabox-base-form' ) );
+		const formDataToMerge = reduce( getMetaBoxes( state ), ( memo, metabox, location ) => {
+			if ( metabox.isActive ) {
+				memo.push( new window.FormData( getMetaBoxContainer( location ) ) );
+			}
+			return memo;
+		}, [] ).concat( baseFormData );
```
Comment (aduth) [inline edit-post/store/effects.js]: Minor: Why not use `[ baseFormData ]` as `reduce`'s `initialValue` ? Does it need to be concatenated to be last?

File: edit-post/store/effects.js [hunk 3]
```diff
@@ -65,23 +66,33 @@ const effects = {
...
+		const formData = reduce( formDataToMerge, ( memo, current ) => {
+			for ( const [ key, value ] of current ) {
```
Comment (aduth) [inline edit-post/store/effects.js]: What is `current` ? I'd _guess_ an instance of `FormData` ? Not easy to follow.

File: edit-post/store/effects.js (hunk 1 above)
Comment (youknowriad) [reply edit-post/store/effects.js]: Are you certain this technique (`gutenberg_get_script_polyfill`) is working properly, I just tried it for formdata but it didn't work. Also I'm wondering if it works for the other polyfills since I don't see any request for the said scripts (promises and fetch).

We do use another polyfill using the import technique `element-closest`. I'm thinking we should consolidate these separately, and my idea, for now, is to register a `wp-polyfills` script depending on all polyfills and add it as a dependency to all our other scripts.

Comment (gziolo) [reply edit-post/store/effects.js]: I think the issue is that `FormData` is there, but has a very limited implementation. See: https://developer.mozilla.org/en-US/docs/Web/API/FormData#Browser_compatibility. I guess it would need to have a more complex detection strategy,

File: edit-post/store/effects.js [hunk 4]
```diff
@@ -65,23 +66,35 @@ const effects = {
...
 		].filter( Boolean );
 
-		// To save the metaboxes, we serialize each one of the location forms and combine them
-		// We also add the "common" hidden fields from the base .metabox-base-form
-		const formData = values( dataPerLocation )
-			.concat( jQuery( '.metabox-base-form' ).serialize() )
-			.concat( additionalData )
-			.join( '&' );
+		// We gather all the metaboxes locations data and the base form data
+		const baseFormData = new window.FormData( document.querySelector( '.metabox-base-form' ) );
```
Comment (gziolo) [inline edit-post/store/effects.js]: Nice, we have a few places where we use `jQuery( selector ).serialize()`. It would be awesome if we could get rid of it completely.

File: edit-post/store/effects.js (hunk 1 above)
Comment (youknowriad) [reply edit-post/store/effects.js]: @gziolo I don't think so because I've use `true` to always load it.

Comment (youknowriad) [reply edit-post/store/effects.js]: Stupid me :) I'll try again

File: edit-post/store/effects.js (hunk 4 above)
Comment (youknowriad) [reply edit-post/store/effects.js]: Yep but not possible at the moment because we need a serialized version of the content to check for changes.

**Comment by youknowriad** [comment]
Updated with the polyfill moved to a separate backend script.

File: lib/client-assets.php [hunk 5]
```diff
@@ -269,6 +269,11 @@ function gutenberg_register_scripts_and_styles() {
 		filemtime( gutenberg_dir_path() . 'edit-post/build/index.js' ),
 		true
 	);
+	wp_add_inline_script(
+		'wp-edit-post',
+		gutenberg_get_script_polyfill( array( 'false' => 'formdata' ) ),
```
Comment (aduth) [inline lib/client-assets.php]: I may have been confused previously. I assumed "`false` for forced" was just for debugging purposes. Can't we have a real condition to check here for whether FormData is supported? As-is, this isn't really any different than the original implementation, just loaded as a separate resource.

Comment (youknowriad) [reply lib/client-assets.php]: If I understand correctly we can't, because the check is more complex, depending on the browser somethings could be supported and others not.

Comment (youknowriad) [reply lib/client-assets.php]: looking at the code of the polyfill for confirmation.

Comment (aduth) [reply lib/client-assets.php]: I know there are some odd quirks with FormData and Safari (something about `entries`), so you may be right, but if we can, it would be good to identify.

Comment (youknowriad) [reply lib/client-assets.php]: Oh it looks like they are doing this check `!window.FormData || !window.FormData.prototype.keys` We can probably do it here as well. Trying.

**Comment by rilwis** [comment]
Thanks for the fix!
