### PR TITLE
REST API: Avoid resetting parent field in draft update

### LINKED ISSUE #10753: Draft child pages: parent is removed when an autosave is performed
**Describe the bug**
When publishing a page, that was a draft and also was assigned to have a parent page, the parent is removed when the child page is published.

**To Reproduce**
1. Create a page in Gutenberg, publish it
2. Create another page in Gutenberg, set it as child page of the page created above, save but do not publish
3. Check on pages overview that the child page is correctly added below the parent page
4. Add contents to child page
5. Publish child page, it becomes a first level page, the parent page connection is removed

**Expected behavior**
When publishing a page that already has a parent page assigned, keep that structure.

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser: Firefox
 - Version: 62

**Smartphone (please complete the following information):**
not tested

**Additional context**
- WordPress 4.9.8
- Gutenberg 3.9.0

### PR DESCRIPTION
**Pull request by aduth**
Related: #10753 

This pull request seeks to resolve an issue where if a draft page is assigned a parent, the parent will become unset the next time an autosave occurs. This occurs because while the revision's parent is typically assigned to the post for which the revision is to be created, in this flow a revision is not created and instead the post itself is updated.

**Testing instructions:**

Verify that an autosave for a page assigned a parent does not ~reset the parent value~ _send the `parent` value in its save request_.

1. Navigate to Pages > Add New
2. Set a Parent page
3. Add a title
4. Save the page
5. Reload
6. Change the title
7. Wait for autosave
8. Once autosave occurs, ~reload~ _observe in the Developer Tools Network tab that a `parent` value was not sent with the request_.

~Note that the parent field is still assigned to the value chosen in Step 2.~

Verify there are no other regressions in the behavior of autosave.

Ensure tests pass:

```
npm run test-unit
```

```
npm run test-unit-php
```

```
npm run test-e2e
```

**Follow-up Task:**

Needs Trac ticket / patch for core 5.0 branch if deemed an appropriate solution.

Related:
* https://core.trac.wordpress.org/ticket/43316
* #6257

### CODE REVIEW

File: lib/class-wp-rest-autosaves-controller.php [hunk 1]
```diff
@@ -188,6 +188,10 @@ public function create_item( $request ) {
 		$user_id           = get_current_user_id();
 
 		if ( ( 'draft' === $post->post_status || 'auto-draft' === $post->post_status ) && $post->post_author == $user_id ) {
+			// To avoid resetting the draft's parent, clear the parent of the
+			// prepared revision which is assigned the draft's own ID.
+			unset( $prepared_post->post_parent );
```
Comment (danielbachhuber) [inline lib/class-wp-rest-autosaves-controller.php]: Is this truly necessary, or are you simply adding it to guard against a client causing a similar bug in the future?

The reason I ask is more from the perspective of: why is `post_parent` a special case? Is it a special case simply because Gutenberg sent it, or is there some additional functional value?

If the former, then we'd need to guard against _all_ extraneous post fields. Which means it probably only makes sense to whitelist the fields we do allow: `title`, `excerpt`, `content`.

Let me know if this doesn't make sense or I missed something.

Comment (aduth) [reply lib/class-wp-rest-autosaves-controller.php]: I don't see it as something specific to Gutenberg: In sending a payload to the autosave endpoint, I consider that the `parent_id` value I send should correspond to the post for which we're creating an autodraft revision. That the REST API interprets the fact that it's a draft and thus doesn't need to operate on a revision should change its treatment of the parent field. It's a bit of an overloaded use of the parent field.

>we'd need to guard against all extraneous post fields. Which means it probably only makes sense to whitelist the fields we do allow: title, excerpt, content.

I agree. This would also help avoid setting misleading expectations about the ability to send other fields for this specific draft condition, which won't work for when creating/updating a revision†.

It still needs to accept `parent_id`, but it only becomes relevant when creating a revision in knowing where to attach the revision, not for the update flow here.

† _I've not actually confirmed whether this behavior takes place_

Comment (danielbachhuber) [reply lib/class-wp-rest-autosaves-controller.php]: @aduth As it turns out, it looks like you flagged this issue 5 months ago: https://core.trac.wordpress.org/ticket/43316#comment:89

---

@adamsilverstein Do you recall why you introduced this conditional logic?

```php
if ( ( 'draft' === $post->post_status || 'auto-draft' === $post->post_status ) && $post->post_author == $user_id ) {
	// Draft posts for the same author: autosaving updates the post and does not create a revision.
	// Convert the post object to an array and add slashes, wp_update_post expects escaped array.
	$autosave_id = wp_update_post( wp_slash( (array) $prepared_post ), true );
} else {
	// Non-draft posts: create or update the post autosave.
	$autosave_id = $this->create_post_autosave( (array) $prepared_post );
}
```

Ideally, we'd prefer to use `$this->create_post_autosave()` for both instances. Barring that, we'll need to replicate the behavior of `_wp_post_revision_data()` prior to calling `wp_update_post()`.

**Comment by danielbachhuber** [comment]
@aduth What do you think about:

1. Backing out of the PHP changes on this pull request.
2. Keeping this pull request exclusively JavaScript changes.
3. Solving the PHP issues with https://core.trac.wordpress.org/ticket/43316.

I'd be fine to only fix the PHP issues in trunk, and have that conversation on the Trac ticket.

**Comment by aduth** [comment]
@danielbachhuber Works for me. I'll push up a revised branch shortly.

**Comment by aduth** [comment]
With foresight of this moment, it was just a revert of one of two commits, done in e7a2360f2373edfd52e61c30ca2c89325bbd299c . I'll keep it in the branch's history for posterity's sake. It'll be squashed into master as a single commit.

**Review by danielbachhuber — APPROVED** [review]

**Comment by aduth** [comment]
Removing the "Fixes" signal, since the issue described in #10753 will still persist until the backend stops considering the `parent` argument from the registered path.

Related: https://core.trac.wordpress.org/ticket/43316#comment:128
