### PR TITLE
Navigation Link: Fix URL deletion in Inspector Controls

### LINKED ISSUE #60758: Navigation Link URL setting in Inspector Controls does not allow you to delete last character
### Description

The URL setting in the naviation link blocks settings sidebar does not allow you to remove the final character. So if you for example have an anchor link in there you are not able to delete the `#` from the URL. 

### Step-by-step reproduction instructions

1. Go to the site editor
2. Select a navigation menu
3. Add a new custom link menu item
4. Open the settings sidebar
5. Try to remove the URL via the text field in the sidebar

You should be able to remove everything including the last character 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/20684594/629453a1-7cee-4e72-bdb6-1123dfde88b8

### Environment info

- WordPress 6.5.2
- TT4 Theme

Also:
 - WordPress 6.5.2
 - Gutenberg Trunk
 - TT4 Theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes #60758.

PR  fixes a bug for the Navigation Link control and allows deleting the last character in the URL control.

## Why?
The user should be able to modify the URL entirely via the inspector controls.

## How?
Reuse workaround for `label` controls.

## Testing Instructions
1. Open a post or page.
2. Insert a Navigation block.
3. Add a new custom link menu item.
4. Open the settings sidebar.
5. Try to remove the URL via the text field in the sidebar.

### Testing Instructions for Keyboard
Same.

## Screenshots or screencast 

https://github.com/user-attachments/assets/e839f9ea-830c-4841-b68f-b51d03c601f5

### CODE REVIEW

**Review by fabiankaegy — APPROVED** [review]
This works as advertised and is a great improvement :) 

The code also looks good to me  👍 Thanks for working on this :)

**Comment by Mamaduka** [comment]
Thanks for testing, @fabiankaegy!

It appears that unit tests have started failing (#68143). I need to investigate this issue, and then I will merge the changes.

File: packages/block-library/src/navigation-link/edit.js [hunk 1]
```diff
@@ -224,14 +225,25 @@ function Controls( { attributes, setAttributes, setIsLabelFieldFocused } ) {
...
+					onBlur={ () => {
+						// Defer the updateAttributes call to ensure entity connection isn't severed by accident.
 						updateAttributes(
-							{ url: urlValue },
+							{ url: ! url ? lastURLRef.current : url },
 							setAttributes,
-							attributes
+							{ ...attributes, url: lastURLRef.current }
 						);
+						setIsEditingControl( false );
```
Comment (Mamaduka) [inline packages/block-library/src/navigation-link/edit.js:245]: @getdave, what do you think about this?

The connection is severed after the first change on the trunk. This delays actual processing logic until the user is "done" editing, or if they have changed their mind.

Comment (getdave) [reply packages/block-library/src/navigation-link/edit.js:245]: Good spot and I think we don't have much choice on this one. 

I'm surprised we don't already just use internal state (`useState`) to manage the value and then only "submit" it on blur.

Comment (Mamaduka) [reply packages/block-library/src/navigation-link/edit.js:245]: This also works, so decided to go without separate internal state.

**Comment by Mamaduka** [comment]
@fabiankaegy, @getdave, can I get a final approval?

**Review by fabiankaegy — APPROVED** [review]
Still works as advertised:)
