### PR TITLE
Editor: Reshape editor state for optimized and accurate dirtiness detection

### LINKED ISSUE #7409: State: Refactor isEditedPostDirty to consider presence of edited properties
Related: #7130

Currently, the post editor prompts when unsaved changes exist based on the `withChangeDetection` higher-order reducer operating on `state.editor`, which includes both edits (fields like title, etc) and block manipulations. This has the downsides of: (a) needing to reset change detection when it's inferred to have been persisted (on save) and (b) manually considering the presence of edited fields after a save to re-trigger dirtiness (https://github.com/WordPress/gutenberg/pull/7130#issuecomment-398726307).

Instead, change detection is only needed on block details. The `isEditedPostDirty` should consider any fields in `edits` as being unsaved. This requires that "initial edits" (described in https://github.com/WordPress/gutenberg/pull/7130#issuecomment-398726307) be refactored as a separate state value, and that blocks state be reshaped to allow `withChangeDetection` to be applied to it specifically (via `blocks.byUID` and `blocks.order` by `combineReducers`). This itself has proven challenging to implement since `combineReducers` is not directly compatible with `withChangeDetection`, since the latter adds a property `isDirty` that causes warnings to occur by `combineReducers` expected shape.

### LINKED ISSUE #10427: Performance: save components are called for *every* block on *every* keystroke
**Describe the bug**

This happens *after* the initial autosave, from then on every keystroke (or any attribute change) will trigger serialisation of the whole post content. I would expect (partial) serialisation of the content to only happen once the post has to be saved, ideally only for the parts that have changed.

The issue seems to happen where we try to determine whether the post is auto saveable?

https://github.com/WordPress/gutenberg/blob/cc5bf5c150268b4a48ff9f68a41be5280a894253/packages/editor/src/store/selectors.js#L390-L406

Looking further into this, but reporting now because it seems high priority.

### PR DESCRIPTION
**Pull request by aduth**
Closes #10427
Closes #7409

This pull request seeks to refactor editor state to to enable a more sensible, accurate, and performant dirty detection routine. Rather than representing `isDirty` as a reflection of the entirety of the `state.editor` state object, it's now been moved to only handle the new `state.editor.blocks`, which contains `byClientId` and `order` (previously `state.editor.blocksByClientId` and `state.editor.blockOrder`). Dirty detection for fields other than content are reflected by the presence of any keys in `state.editor.edits`.

This helps to support:

- Removal of an undesirable artificial dirtying, which was intended as a temporary solution
- Avoid expensive calls to content serialization, notably in `isEditedPostAutosaveable` (which, as noted in #10427, became very negatively impactful)

Previous attempts to implement this had been unsuccessful in that `withChangeDetection` adds a property to the combined reducer which was incompatible with Redux's `combineReducers` (logging an error to the console). To work around this, the `combineReducers` exported from `@wordpress/data` was swapped with an in-place-compatible, more-performant variation [`turbo-combine-reducers`](https://github.com/aduth/turbo-combine-reducers) (authored by yours truly).

**Testing Instructions:**

Verify that there is no regressions in the behavior of autosave, namely that it occurs after delay if and only if one of content, title, or excerpt is updated. 

Conversely, verify that if a field other than the three aforementioned is updated (e.g. categories added or removed), it is reflected by the UI as needing save ("Save Draft" becomes active). An autosave should not occur, but you should be prompted about unsaved changes if you attempt to leave the page before pressing "Save Draft".

Finally, verify that if changing _both_ one of content, title, excerpt _and_ another field, that the autosave does occur, and once completed, the editor is still in a "dirty" state ("Save Changes" present, after brief delay once save finishes). This is because autosaves do not include other fields.

### CODE REVIEW

File: packages/editor/src/store/selectors.js [hunk 1]
```diff
@@ -99,6 +99,20 @@ export function isEditedPostNew( state ) {
...
+ * Returns true if content includes unsaved changes, or false otherwise.
+ *
+ * @param {Object} state Editor state.
+ *
+ * @return {boolean} Whether content includes unsaved changes.
+ */
+export function hasChangedContent( state ) {
+	return (
+		state.editor.present.blocks.isDirty ||
+		'content' in state.editor.present.edits
```
Comment (iseulde) [inline packages/editor/src/store/selectors.js]: I don't really get what this second condition is checking for.

Comment (iseulde) [inline packages/editor/src/store/selectors.js]: I don't really get what this second condition is checking for.

Comment (iseulde) [inline packages/editor/src/store/selectors.js]: I don't really get what this second condition is checking for.

Comment (iseulde) [inline packages/editor/src/store/selectors.js]: I don't really get what this second condition is checking for.

File: packages/editor/src/store/reducer.js [hunk 2]
```diff
@@ -279,259 +267,270 @@ export const editor = flow( [
...
+	blocks: flow( [
+		combineReducers,
+
+		// Track whether changes exist, resetting at each post save. Relies on
+		// editor initialization firing post reset as an effect.
+		withChangeDetection( {
+			resetTypes: [ 'SETUP_EDITOR_STATE', 'REQUEST_POST_UPDATE_START' ],
+			ignoreTypes: [ 'RECEIVE_BLOCKS', 'RESET_POST', 'UPDATE_POST' ],
+		} ),
+	] )( {
```
Comment (iseulde) [inline packages/editor/src/store/reducer.js]: Is everything below here just indented? It's a bit hard to see the code changes, if there are any.

**Comment by iseulde** [comment]
> To work around this, the `combineReducers` exported from `@wordpress/data` was swapped with an in-place-compatible, more-performant variation [`turbo-combine-reducers`](https://github.com/aduth/turbo-combine-reducers) (authored by yours truly).

If we're swapping something from `@wordpress/data` because it is not performant enough, might it not be better to adjust `combineReducers` in `@wordpress/data`?

File: packages/editor/src/store/reducer.js (hunk 2 above)
Comment (aduth) [reply packages/editor/src/store/reducer.js]: >Is everything below here just indented? It's a bit hard to see the code changes, if there are any.

Yes, no changes aside from indentation. 

GitHub has an option to hide whitespace-only changes, which should help make things a bit clearer.

image

**Comment by aduth** [comment]
>If we're swapping something from `@wordpress/data` because it is not performant enough, might it not be better to adjust `combineReducers` in `@wordpress/data`?

To be clear, we're not swapping it because of performance, we're swapping it to work around the errors which are logged by the shape validation in the Redux implementation. Performance is a "plus".

To your question, is the point that we should bring it in rather than rely on it as a third-party dependency? I don't really feel strongly one way or the other. I implemented it as a separate project largely to disable the availability of transpilation, for performances' sake (it's a weekend side hack project, something I felt fine to "waste" time over-optimizing).

File: packages/editor/src/store/selectors.js (hunk 1 above)
Comment (aduth) [reply packages/editor/src/store/selectors.js]: I'll add a comment to clarify, but it's a combination of two things which require this consideration:

- While content in Visual mode is represented by the blocks state, in Text mode it is tracked by `edits.content`.
- `edits` is intended to contain only the different property values, so it is expected that the _mere presence_ of any property is an indicator that the value is different than what is known to be saved.

**Comment by aduth** [comment]
I've rebased and pushed a number of revisions, including updated unit tests.

There's failing end-to-end tests which are legitimate, and which highlight an issue I've dealt with previously: We can't naively consider emptiness of `state.editor.edits` object for considering dirtiness currently, because we have this concept of "initial edits" to e.g. set the 'Auto-Draft' default title to an empty string. This isn't initiated by the user, but is a field we need to send in the save, but should _not_ trigger a dirty prompt for the user in a new post (as it does in the branch currently).

I'll need to think on this some more.

Related: #9403

**Comment by aduth** [comment]
Extracted substitution of `combineReducers` implementation separately to #11255

**Comment by aduth** [comment]
This has been rebased and is now passing. The changes are still substantial, and I've extracted at least one more commit out (the initial edits refactoring, to #11267). It was originally developed separately, but cherry-picked into this branch to verify its viability for addressing the remaining E2E test failures.

**Comment by aduth** [comment]
Extracted `blocksByClientId`, `blockOrder` -> `blocks.byClientId`, `blocks.order` state shape refactoring to #11315.

**Comment by aduth** [comment]
#11267 has been separately merged and this one rebased in response, reducing from +660 -243 changes to +261 -111. 

I'm not planning on extracting any other separate pull requests. This one should be considered ready for final review as-is.

File: packages/editor/src/store/reducer.js (hunk 2 above)
Comment (youknowriad) [reply packages/editor/src/store/reducer.js]: Funny that this Higher order reducer moved from "edits" to just "blocks". It almost feels like we need an `editBlocks` :)

File: packages/editor/src/store/selectors.js [hunk 3]
```diff
@@ -111,7 +131,15 @@ export function isEditedPostNew( state ) {
...
-	return state.editor.isDirty || inSomeHistory( state, isEditedPostDirty );
+	if ( hasChangedContent( state ) ) {
+		return true;
+	}
+
+	if ( Object.keys( state.editor.present.edits ).length > 0 ) {
+		return true;
+	}
+
+	return inSomeHistory( state, isEditedPostDirty );
```
Comment (youknowriad) [inline packages/editor/src/store/selectors.js]: So if I understand properly. We conder a post dirty until it's completely saved (successful response)? right? any particular reason? should we clarify why in a comment?

File: packages/editor/src/store/selectors.js [hunk 4]
```diff
@@ -451,9 +479,17 @@ export function isEditedPostAutosaveable( state ) {
 		return true;
 	}
 
+	// To avoid an expensive content serialization, use the content dirtiness
+	// flag in place of content field comparison against the known autosave.
+	// This is not strictly accurate, and relies on a tolerance toward autosave
+	// request failures for unnecessary saves.
+	if ( hasChangedContent( state ) ) {
```
Comment (youknowriad) [inline packages/editor/src/store/selectors.js]: I guess this is the fix for the performance issue. 

It might not be easy but I wonder if we can add an e2e test checking that we don't run `save` functions as we type :)

**Review by youknowriad — APPROVED** [review]
LGTM 👍

File: packages/editor/src/store/selectors.js (hunk 3 above)
Comment (aduth) [reply packages/editor/src/store/selectors.js]: > So if I understand properly. We conder a post dirty until it's completely saved (successful response)? right? any particular reason? should we clarify why in a comment? (I know it's not new in this PR though)

It's because change detection (now only for blocks) is reset at _the start_ of the save, but we still want to avoid allowing a user to reload while that request is still pending.

It's covered in this test:

https://github.com/WordPress/gutenberg/blob/26ccc159f373e5412d4fabf20fa00431d8fce7b6/test/e2e/specs/change-detection.test.js#L216-L230

I'll see if I can form a useful comment here.

File: packages/editor/src/store/selectors.js (hunk 4 above)
Comment (aduth) [reply packages/editor/src/store/selectors.js]: > It might not be easy but I wonder if we can add an e2e test checking that we don't run `save` functions as we type :)

Hmm, might not be too hard! I'll give it a shot.

File: packages/editor/src/store/selectors.js (hunk 3 above)
Comment (aduth) [reply packages/editor/src/store/selectors.js]: >I'll see if I can form a useful comment here.

Added in rebased fd7a8ec.

**Comment by aduth** [comment]
Consolidated list of composing pull requests:

- #10844 
- #11255
- #11267
- #11315
