### PR TITLE
Data Module: Fix multi-store persistence

### LINKED ISSUE #4695: Bug with Fix Toolbar to Top
## Issue Overview

There appears to be a bug with the latest master branch. Setting the option to "Fix Toolbar to Top" in the editor settings (accessed via the ellipsis icon in the top right), will render the editor broken/unusable. The console output points to an uncaught type error, specifically:

```
Uncaught TypeError: Cannot convert undefined or null to object
    at from (native)
    at wp.editor.exports.default (http://vagrant.local/content/plugins/gutenbergx/editor/build/index.js?ver=1516985614:2888:31)
    at preferences (http://vagrant.local/content/plugins/gutenbergx/editor/build/index.js?ver=1516985614:34147:142)
    at combination (http://vagrant.local/content/plugins/gutenbergx/editor/build/index.js?ver=1516985614:15016:29)
    at baseReducer (http://vagrant.local/content/plugins/gutenbergx/editor/build/index.js?ver=1516985614:34656:18)
    at http://vagrant.local/content/plugins/gutenbergx/editor/build/index.js?ver=1516985614:34672:12
    at enhancedReducer (http://vagrant.local/content/plugins/gutenbergx/data/build/index.js?ver=1516985614:378:19)
    at combination (http://vagrant.local/content/plugins/gutenbergx/data/build/index.js?ver=1516985614:5381:29)
    at dispatch (http://vagrant.local/content/plugins/gutenbergx/data/build/index.js?ver=1516985614:3003:22)
    at http://vagrant.local/content/plugins/gutenbergx/editor/build/index.js?ver=1516985614:34991:77
```
The specifics of this bug were spotted by Jason Caldwell (@jaswrks) on his quest to break his version of master and sync with the rest of us on Slack 😁 

## Steps to Reproduce (for bugs)

1. Pull and build the latest master.
2. Open a post in the Gutenberg editor.
3. If page loads fine, then select "Fix Toolbar to Top" from the menu accessible via the ellipsis in the top right (see image below).
4. Refreshing the page will render a blank editor with errors printed in the console.

Tested in Mac/Chrome and Mac/Safari.

## Possible Solution

- Calling `localStorage.clear()` in the console will unset the setting and allow the editor to function as normal - also spotted by @jaswrks as a short term solution to carry on working/developing.
- Gary Thayer in #core-editor found that last working commit is `cd2ce06256e9cb1f1e022ae0991b110eb5822d60`. 

## Screenshots / Video

"Fix Toolbar to Top" setting:
screen shot 2018-01-26 at 19 04 05

### PR DESCRIPTION
**Pull request by youknowriad**
closes #4695

This PR fixes the persist middleware for multiple-stores. 
The issue was that we were rehydrating both states at the same time with the same value because the reducer was not able to differentiate the actions. The fix adds the storageKey as a parameter to the rehydrate action.

**Testing instructions**

 - Clear localstorage
 - Open the editor
 - It should load

### CODE REVIEW

File: data/persist.js [hunk 1]
```diff
@@ -51,6 +52,7 @@ export function loadAndPersist( store, reducer, reducerKey, storageKey ) {
 		store.dispatch( {
 			type: 'REDUX_REHYDRATE',
 			payload: persistedState,
+			storageKey,
```
Comment (aduth) [inline data/persist.js]: Necessary? Would we want a test to confirm it's included in the dispatched action for rehydration?
