### PR TITLE
Make Archives Block display correct empty message

### LINKED ISSUE #9418: No published Posts result in Ghost Archives Block
**Describe the bug**
When creating an Archives Block while having no posts published, the Archives Block is empty and overlaps with the subsequent Blocks

**To Reproduce**
1. Go to Posts
2. Make sure you have no Published Posts
3. Create New Post
4. Add 2 Paragraph Blocks with dummy text
5. Create an Archives Block between those 2
6. Notice how the Archives Block is empty and overlaps with its next Block

**Screenshots**
emptyarchives

**Expected behavior**
Show a message explaining there are no Archives, like the Latest Comments Block
emptycomments

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome Version 68.0.3440.106 (Official Build) (64-bit)
 - Gutenberg Version 3.6.2

### PR DESCRIPTION
**Pull request by caxco93**
## Description
When creating an Archives Block while having no posts published, the
Archives Block is empty and overlaps with the subsequent Blocks.

This addresses that by setting the correct Block content when there
are no Archives to show.

## How has this been tested?
Built in tests and manually

## Screenshots
*Before:*
emptyarchives

*After:*
emptyarchives2

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 

Fixes #9418

### CODE REVIEW

File: packages/block-library/src/archives/index.php [hunk 1]
```diff
@@ -79,12 +79,16 @@ function render_block_core_archives( $attributes ) {
...
 
-		$block_content = sprintf(
+		$block_content = ! empty( $archives ) ? sprintf(
 			'<ul class="%1$s">%2$s</ul>',
 			esc_attr( $class ),
-			$block_content
+			$archives
+		) : sprintf(
+			'<div class="%1$s">%2$s</div>',
+			$classnames,
```
Comment (jorgefilipecosta) [inline packages/block-library/src/archives/index.php]: We are outputting an empty class on the frontend `<div class="">No archives to show.</div>`. Should we use `esc_attr( $class )` here instead of `$classnames` ?

Comment (caxco93) [reply packages/block-library/src/archives/index.php]: Thanks for noticing!

**Comment by pento** [comment]
@caxco93: Thanks for the PR!

It seems like this could be simplified further: rather than duplicating the `sprintf()` call, it could be something like:

```php
		$block_content = sprintf(
			'<ul class="%1$s">%2$s</ul>',
			esc_attr( $class ),
			$archives ? $archives : __( 'No archives to show.', 'gutenberg' )
		);
```

**Comment by pento** [comment]
Oh, I totally missed the `<ul>` / `<div>` difference. 🙂

This looks good to me, thanks @caxco93!

**Review by pento — APPROVED** [review]

**Comment by karmatosed** [comment]
Just a little note, we probably should have had a design check on this but we can retro do. In future as this is a state lets get insight here.
