### PR TITLE
Register webfonts defined in styles variations

### LINKED ISSUE #39702: [Styles] Webfonts enqueued using styles JSON files are not loaded
Webfonts declared in custom styles json files are not enqueued. No error is thrown, but the fonts are not loaded in. 

---

To reproduce: 

1. Add a style variation to emptytheme.
2. Add font file(s)
3. Declare the font using fontFace under `settings.typography.fontFamilies`.
4. Open the Site Editor.
5. Select the variation, notice that the correct font is not loaded.

Example PR here: https://github.com/WordPress/theme-experiments/pull/304

In the PR example, the same code works properly when pasted into `theme.json` instead of `styles/variation.json`. 

--- 

Screenshots:

styles

The correct font for the variation should be DM Sans. Instead, the default `sans-serif` fallback is being used, and no network call to the DM Sans font files is being made.  

Screen Shot 2022-03-23 at 1 36 47 PM

### PR DESCRIPTION
**Pull request by aristath**
## What?

Fixes https://github.com/WordPress/gutenberg/issues/39702
Registers webfonts defined in variations, as described in the issue.

## Why?
This will allow defining webfonts in styles variations.

## How?
* In the editor, all webfonts registered in variations get added
* On the frontend, we use the merged data, so if the user has selected to use a webfont from a variation, then (and only then) the webfont gets added.

## Testing Instructions
Testing instructions available in #39702

### CODE REVIEW

File: lib/blocks.php [hunk 1]
```diff
@@ -592,3 +592,31 @@ function gutenberg_multiple_block_styles( $metadata ) {
 	return $metadata;
 }
 add_filter( 'block_type_metadata', 'gutenberg_multiple_block_styles' );
+
+/**
+ * Get theme styles variations.
+ *
+ * @return array
+ */
+function gutenberg_get_theme_styles_variations() {
```
Comment (youknowriad) [inline lib/blocks.php]: Can we move this to a lib/wordpress-6.0/blocks.php or something like that. (See https://github.com/WordPress/gutenberg/blob/trunk/lib/README.md)

Comment (youknowriad) [reply lib/blocks.php]: Also I feel blocks.php might not be the right place for this, maybe this could be a `WP_theme` method when it lands in Core?

File: lib/compat/wordpress-6.0/register-webfonts-from-theme-json.php [hunk 2]
```diff
@@ -12,15 +12,35 @@ function gutenberg_register_webfonts_from_theme_json() {
...
+			empty( $variation['settings'] ) ||
+			empty( $variation['settings']['typography'] ) ||
+			empty( $variation['settings']['typography']['fontFamilies'] )
+		) {
+			continue;
+		}
+		$settings['typography']                 = empty( $settings['typography'] ) ? array() : $settings['typography'];
+		$settings['typography']['fontFamilies'] = empty( $settings['typography']['fontFamilies'] ) ? array() : $settings['typography']['fontFamilies'];
+		$settings['typography']['fontFamilies'] = array_merge( $settings['typography']['fontFamilies'], $variation['settings']['typography']['fontFamilies'] );
+	}
```
Comment (youknowriad) [inline lib/compat/wordpress-6.0/register-webfonts-from-theme-json.php]: If I'm following this properly, this basically just merges the font families from the variations into the main theme.json output. 

While this may work for now, this might not be the best approach I think. Our goal is to be able to load variations from potentially the directory (theme or dedicated directory) and feel it would be better if instead of doing this, we provide a way for the site editor to lazy-load fonts for dedicated variations.

File: lib/blocks.php (hunk 1 above)
Comment (youknowriad) [reply lib/blocks.php]: I guess these comments might not be relevant depending on whether we address https://github.com/WordPress/gutenberg/pull/39886#discussion_r838491541

File: lib/compat/wordpress-6.0/register-webfonts-from-theme-json.php (hunk 2 above)
Comment (aristath) [reply lib/compat/wordpress-6.0/register-webfonts-from-theme-json.php]: I'm trying to think of a way to "lazy-load" these on the frontend, but I can't think of something... From what I can tell, we don't add a body-class or something that would help us identify whether a variation is used or not, correct?

Comment (youknowriad) [reply lib/compat/wordpress-6.0/register-webfonts-from-theme-json.php]: Yeah! there's no concept of "active variation", but maybe that's an advantage instead of being a problem. Basically 

We have this in the site editor:

```js
<GlobalStylesProvider config={ config }>
   <Iframe>
      <SiteEditor />
    </Iframe>
</GlobaStylesProvider />
```

and for each style variation on the style variation picker we do something like this as well:

```
<GlobalStylesProvider config={ config }>
  <IFrame> 
   <VariationPreview />
   </IFrame>
</GlobaStylesProvider />
```

So both places have the same structure, so we can use the global styles provider config to get the font family and call a URL to load these fonts in the iframe or something like that.

Would something like that work?

Comment (aristath) [reply lib/compat/wordpress-6.0/register-webfonts-from-theme-json.php]: tbh, I'm more concerned with the frontend and not the editor...We can probably find a way to handle it on the editor, but on the frontend we'll still need a way to figure out what the "active variation" is in order to load the appropriate variation JSON files and then parse the webfonts from that.
That's what troubles me right now... 
If variation JSON files simply pick things that are defined in the main JSON file like colors, font-sizes and whatnot, we don't need to know what the active variation is. But if in that file we're actually defining new things (like webfonts), then we'll need to know which one is active :hurtrealbad:

Comment (youknowriad) [reply lib/compat/wordpress-6.0/register-webfonts-from-theme-json.php]: > We can probably find a way to handle it on the editor, but on the frontend we'll still need a way to figure out what the "active variation" is in order to load the appropriate variation JSON files and then parse the webfonts from that.

No, in the frontend there's no problem because the variation will be saved as a "user theme.json" so I think there won't be any issue, it should already be working.

Comment (aristath) [reply lib/compat/wordpress-6.0/register-webfonts-from-theme-json.php]: Yep, that worked! 👍 I just needed to change `get_theme_data()` to `get_merged_data()`.

As for lazy-loading assets in the editor, I got the impression from https://github.com/WordPress/gutenberg/issues/39332#issuecomment-1085157058 that we don't want to do that at this stage, and it's something we'll want to do later-on?

Comment (youknowriad) [reply lib/compat/wordpress-6.0/register-webfonts-from-theme-json.php]: No I think that comment is talking about something else: Basically there's a difference between all registered fonts and all fonts that a theme use (theme.json or variations). For the former we don't want to enqueue them anywhere, for the latter, we want to enqueue them for both frontend and editor.

The variation is special in the sense that in the editor, we only want to load them in the iframe showing the preview of the variation unless the variation is applied as "user theme.json" in which case it should be loaded in the main iframe too.

Comment (Addison-Stavlo) [reply lib/compat/wordpress-6.0/register-webfonts-from-theme-json.php]: >  Basically there's a difference between all registered fonts and all fonts that a theme use (theme.json or variations). For the former we don't want to enqueue them anywhere, for the latter, we want to enqueue them for both frontend and editor.

RE: what is vs. isnt enqueued in the editor - It [sounds like ](https://github.com/WordPress/gutenberg/issues/39332#issuecomment-1085157058)we may be conflicting on this: "The main goal is to avoid loading every registered font on the front-end while still loading them in the site editor (back-end) so people can choose and manage them."

Comment (aristath) [reply lib/compat/wordpress-6.0/register-webfonts-from-theme-json.php]: @Addison-Stavlo that's why I converted this PR to a draft... I'm still a bit unclear on what it is we want to achieve.
The frontend now works as expected in this PR, but on the editor things got complicated and I don't know how to address it 😞 
If we want to **always** load the webfonts, it's relatively easy to do. If we want to "lazy-load" them, then I don't know how to properly address it.

Comment (youknowriad) [reply lib/compat/wordpress-6.0/register-webfonts-from-theme-json.php]: > If we want to always load the webfonts, it's relatively easy to do

Maybe we can start with that first but I imagine it's not sustainable for the future if we want to load all "registered" fonts (not particularly variations ones but all the ones that are in google fonts for instance).

Comment (aristath) [reply lib/compat/wordpress-6.0/register-webfonts-from-theme-json.php]: OK. For now I suppose it's a reasonable compromise. Visitors will only get the font if they're using it, while editors will get more fonts enqueued.

I think that we'll need a more generic mechanism to lazy-load stuff in the editor anyway, so this could probably be a part of a more generalized approach 👍

**Comment by youknowriad** [comment]
It took me some time to be able to test this :). Should we include a variation with a font file in the "emptytheme" embedded in the Gutenberg plugin to make testing this easier in the future?

Regardless, I'm noticing two bugs:

I have a default theme.json without font family (default) and one variation with a font applied to the whole body.

 - If apply the variation on the editor and save, then reload the frontend, the frontend is still displaying the default font family.
 - In the editor, if I have the variation applied and I save and reload. I'm not able to "reset" the styles to the default theme.json. Basically when I click "reset styles", the variation's font family is still applied somehow.

(Testing in safari)

**Comment by kjellr** [comment]
This `emptytheme` PR works for testing: https://github.com/WordPress/theme-experiments/pull/304

I'm also testing alongside the Twenty Twenty-Two style variations here: https://github.com/WordPress/wordpress-develop/pull/2440

The former works just fine aside from the issues that @youknowriad [noted above](https://github.com/WordPress/gutenberg/pull/39886#issuecomment-1088636359) — I am able to reproduce those. But the Twenty Twenty-Two PR doesn't seem to load any fonts at all. 🤔 

If someone could help gut check that for me, I'd appreciate it — I'm unclear if the problem is over on the Twenty Twenty-Two end or in this PR.

**Comment by aristath** [comment]
> If apply the variation on the editor and save, then reload the frontend, the frontend is still displaying the default font family.

Apparently I didn't test after rebasing the PR, and some things have changed 😅 
Fixed. It appears that after some recent changes in the webfonts API, now an extra call is required to enqueue the webfont, registering them is not enough.

> In the editor, if I have the variation applied and I save and reload. I'm not able to "reset" the styles to the default theme.json. Basically when I click "reset styles", the variation's font family is still applied somehow.

After some debugging, I don't think this is a bug in this PR...
The problem here  is that the `theme.json` file in the emptytheme doesn't have a default typography defined, while the variation does.
If in `theme.json` I add this (see snippet below) then everything works:
```json
	"styles": {
		"typography": {
			"fontFamily": "sans-serif"
		}
	}
```

If we want to change that behavior, it will need to be done in a separate PR since it's more generic and not related to the webfonts... it's an overrides/resets issue when a variation has something defined that doesn't exist in the main file.

**Review by youknowriad — APPROVED** [review]
This is looking good to me. (I agree the reset bug is separate, I'll look into it). 

Also cc @oandregal in case you want to take a look here.

**Review by scruffian — APPROVED** [review]
I tested with @kjellr's TT2 variations PR and it works for me

File: lib/experimental/register-webfonts-from-theme-json.php [hunk 3]
```diff
@@ -64,6 +89,7 @@ function gutenberg_register_webfonts_from_theme_json() {
 	}
 	foreach ( $webfonts as $webfont ) {
 		wp_webfonts()->register_webfont( $webfont );
+		wp_webfonts()->enqueue_webfont( $webfont['font-family'] );
```
Comment (Addison-Stavlo) [inline lib/experimental/register-webfonts-from-theme-json.php:92]: Does this now enqueue all variation webfonts (including unused) on the frontend for folks visiting the site?

Comment (aristath) [reply lib/experimental/register-webfonts-from-theme-json.php:92]: Only when the variation is actually active - so the webfonts are used. It doesn't enqueue webfonts from unused/inactive variations.

Comment (Addison-Stavlo) [reply lib/experimental/register-webfonts-from-theme-json.php:92]: awesome! thanks for the quick response! 😁
