### PR TITLE
Inserter: Fix Block visibility manager

### LINKED ISSUE #65687: Child blocks are displayed in the block inserter and block visibility doesn't work
## What problem does this address?

I found two issues in the trunk:

- Child blocks that have a specific parent, such as the List Item, are displayed. When you click on the block, it will say "Block "{blockName}" can't be inserted.". (This may be a new specification)
- "Manage block visibility" doesn't work.

I used `git bisect` and it looks like this issue occurred in #65490.

https://github.com/user-attachments/assets/e9b761f6-79a2-4ab9-bde3-86b031d5e755

cc @youknowriad @andrewserong @jorgefilipecosta

### PR DESCRIPTION
**Pull request by youknowriad**
Closes #65687 

## What?

In #65490 we changed a bit how the inserter works by avoiding any initial block type filtering and only upon insertion figuring out what things can or can't be allowed in a given position and also try to guess a more suitable position.

The problem is that in some situations (block visibility managed, allowed blocks settings), it doesn't really make sense to show the blocks at all. So this PR separate the `canInsertBlock` selector into two:

 - One about visibility of the block
 - One about the possibility to insert the block in a given position.

**Note**

- For child blocks, I elected for now to keep them in the inserter. The reason is that there's value in that, for instance, if you're within a nested block within a column, it's handy to be able to click "column" block to insert a new column in the parent's columns block. We can revise/tweak that behavior if it's deemed too problematic.

- Note that the PR applies the fix to the pattern inserter too.

## Testing Instructions

1- Open the post inserter
2- Go to preferences > blocks and remove the "heading" block
3- Open the inserter and notice the block is not visible anymore and any block that uses the block is not either.

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
For example, even if I hide all blocks in the Text category via "Manage block visibility", only the List item block will be displayed in The text category in the inserter. This happens with other categories as well. I think this is because the Block Manager [filters out blocks that have parents](https://github.com/WordPress/gutenberg/blob/deb6a90a349b0801c5e2148d719f56685acf29c4/packages/editor/src/components/block-manager/index.js#L65).

This behavior seems a bit strange, but what do you think?

list-item

**Comment by youknowriad** [comment]
> This behavior seems a bit strange, but what do you think?

I agree, It seems if the blocks that have a "parent" block are not allowed, their children shouldn't be allowed either.

**Comment by youknowriad** [comment]
It should be fixed now.

**Comment by t-hamano** [comment]
It seems like e2e tests and unit tests are failing. Maybe it has to do with the logic in `canInsertBlockType`.

**Comment by youknowriad** [comment]
This should be ready now.

File: packages/block-editor/src/store/selectors.js [hunk 1]
```diff
@@ -1540,6 +1540,59 @@ export function getTemplateLock( state, rootClientId ) {
 	return getBlockListSettings( state, rootClientId )?.templateLock ?? false;
 }
 
+/**
+ * Determines if the given block type is visible in the inserter.
+ * Note that this is different than whenter a block is allowed to be inserted.
+ * In some case, the block is not allowed in a given position but
+ * it should still be visible in the inserter to be able to add it
+ * to a different position.
```
Comment (t-hamano) [inline packages/block-editor/src/store/selectors.js]:
```suggestion
 * Determines if the given block type is visible in the inserter.
 * Note that this is different than whether a block is allowed to be inserted.
 * In some cases, the block is not allowed in a given position but
 * it should still be visible in the inserter to be able to add it
 * to a different position.
```

**Review by t-hamano — APPROVED** [review]
Looks good to me 👍

File: packages/block-editor/src/store/selectors.js [hunk 2]
```diff
@@ -1540,6 +1540,59 @@ export function getTemplateLock( state, rootClientId ) {
...
+		blockName,
+		true
+	);
+	if ( ! isBlockAllowedInEditor ) {
+		return false;
+	}
+
+	// If parent blocks are not visible, child blocks should be hidden too.
+	if ( !! blockType.parent?.length ) {
+		return blockType.parent.some(
```
Comment (oandregal) [inline packages/block-editor/src/store/selectors.js:1584]: At this point, how do we know `blockType.parent` is an array? Can't it be a string, for example, that also has a `length` property?

For context, I'm looking at [an issue in the support forum](https://wordpress.org/support/topic/error-after-update-228/) that I believe to be related to this check: the report is recent, the users report issues when inserting blocks, and there's no other place in the codebase that uses `parent.some`.

Comment (oandregal) [reply packages/block-editor/src/store/selectors.js:1584]: Looking at the block registration, it seems `parent` should be null or an array, but we don't enforce that.

Even the [recently added logic](https://github.com/WordPress/gutenberg/pull/66121/files#diff-30ce126b90014d659302087765876898f16562219f796796ed407fdb346c8e4dR235) to block registration doesn't check that parent is an array. This:

```js
if (
  1 === settings?.parent?.length &&
  name === settings.parent[ 0 ]
) { /**/ }
```

would still be fine for blocks that register `parent` as a string.

Comment (oandregal) [reply packages/block-editor/src/store/selectors.js:1584]: One thing we can do to fix this is to make the if check above explicit for what we want to do: verify that it is an array and that it has elements.

The more general question is: how `parent` can become an array? Are block authors mis-registering this property? Can we now enforce it being an array?

Comment (oandregal) [reply packages/block-editor/src/store/selectors.js:1584]: PR at https://github.com/WordPress/gutenberg/pull/66234

Comment (t-hamano) [reply packages/block-editor/src/store/selectors.js:1584]: > Even the [recently added logic](https://github.com/WordPress/gutenberg/pull/66121/files#diff-30ce126b90014d659302087765876898f16562219f796796ed407fdb346c8e4dR235) to block registration doesn't check that parent is an array.

Regarding this conditional statement, I suggested a change in [this comment](https://github.com/WordPress/gutenberg/pull/66121#discussion_r1802296536). However, I noticed that, unlike my comment, the order of each conditional was reversed when it was merged, which is certainly not what was intended.

Comment (oandregal) [reply packages/block-editor/src/store/selectors.js:1584]: cc @gziolo for thoughts about enforcing the `blockType.parent` being an array at registration. Would that be feasible?

Comment (gziolo) [reply packages/block-editor/src/store/selectors.js:1584]: We are discussing it in this thread: https://github.com/WordPress/gutenberg/pull/66234#discussion_r1806378362. The short answer is if we know that block types were registered with the `parent` set to a string, the best way would be to respect that and provide a fallback handling.
