### PR TITLE
Fix theme supports for themes without theme.json

### LINKED ISSUE #34931: add_theme_support() disabled for some editor options on without theme.json or `experimental-link-color` support
### Description

Introduced in #34334.

After the above change was merged ([specific commit](https://github.com/WordPress/gutenberg/commit/482650ac91cc7b6ad5b595d563b081c389124759)), themes that do not have a theme.json file _or_ declare support for `experimental-link-color` will fail to load some plugin-based `add_theme_support()` calls. Calls from within the theme's `functions.php` file will still work as expected.

This applies specifically to `custom-line-height`, but may also be true for other options.

### Step-by-step reproduction instructions

1. Install and activate a theme that does not provide a theme.json file, nor declare support for `experimental-link-color`. I recommend Twenty Twenty for this test.
2. Create a new post with at least one paragraph block. Select that block and note that the `Line height` option is _not_ provided in the editor sidebar... this is expected, as the option is disabled by default.
3. Install a plugin to add support for custom line height. The following bare-bones snippet should suffice as a basic plugin `.php` file:
```
<?php
/**
 * Plugin Name: Line Height Test
*/

function test_modify_theme_support() {
	add_theme_support( 'custom-line-height' );
}
add_action( 'after_setup_theme', 'test_modify_theme_support', 11 );

```
(note the priority of `11`. It ensures your plugin is firing _after_ the theme's declarations, which will be important in a minute...)

4. Activate your plugin and refresh the editor. Note that the `Line height` option is still not provided.

Confirm your plugin is working:
1. To confirm your plugin is working, add an image block. Note that option for `wide width` and `full width` are included under alignment. This is expected, as support for these options is declared by the theme.
2. Edit your plugin to also declare ```remove_theme_support( 'align-wide' );```
3. Make sure you have the priority of your `add_action` set to `11` as shown above
4. Reload the editor and confirm that you can no longer apply `wide` or `full width` alignments to image blocks.

You now have a plugin that can modify some `theme_support` parameters like `align-wide` but fails to modify specific ones like `custom-line-height`. Note this is theme specific, as described above, and only applies to themes that lack a `theme.json` file _and_ do not declare support for `experimental-link-color`.

**Expected outcome**
Different options should be respected equally. In the above example, `line height` would activate alongside the removal of `align-wide` on TwentyTwenty.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WP 5.8.1, Gutenberg 11.5.0, with Twenty Twenty active.

2019 MacBook Pro, MacOS 11.5.2, Chrome 93.0.4577.63

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by oandregal**
Fixes https://github.com/WordPress/gutenberg/issues/34931
Fixes https://wordpress.org/support/topic/gutenberg-plugin-over-rides-custom-editor-color-palette/

https://github.com/WordPress/gutenberg/pull/34334 introduced a bug by which settings provided via theme supports were not passed to the editor for themes without `theme.json` supports. This resulted in bugs like the palette of the theme not showing in the editor (it was shown the core palette instead) or that a plugin could not enable the `custom-line-height` support.

## Tests

Activate **TT1-blocks**: a theme with `theme.json` support.

- Visit the front end. Check the content of `global-styles-inline-css` is: both core & theme presets (classes and variables), the block gap styles ([see](https://github.com/WordPress/gutenberg/pull/34334#issuecomment-906498931)), the theme styles.
- Visit the editor and verify that the editor palette is the theme palette.

Activate the **TwentyTwentyOne** theme: a theme without theme.json but with `experimental-link-color` support.

- Visit the front end. Check the content of `global-styles-inline-css` is both core & theme presets (classes and variables).
- Visit the editor and verify that the editor palette is the theme palette.

Activate the **TwentyTwenty** theme: a theme without theme.json and no `experimental-link-color` support.

- Visit the front end. Check the content of `global-styles-inline-css` is the core presets (classes & variables).
- Visit the editor and verify that the editor palette is the theme palette.
- Enable the `custom-line-height` and verify the control is shown in the editor. See [full instructions](https://github.com/WordPress/gutenberg/issues/34931) or paste the following code in the `global-styles.php` file:

```php

function test_modify_theme_support() {
	add_theme_support( 'custom-line-height' );
}
add_action( 'after_setup_theme', 'test_modify_theme_support', 11 );
```

### CODE REVIEW

**Comment by oandregal** [comment]
With this PR the stylesheet would contain the theme presets as well, which is not the expected behavior https://github.com/WordPress/gutenberg/pull/34334

> Themes without theme.json and no experimental-link-color support either: the stylesheet contains the core presets.

I'm looking at alternatives.

**Comment by oandregal** [comment]
Pushed the necessary changes to make it work in all scenarios.

File: lib/class-wp-theme-json-gutenberg.php [hunk 1]
```diff
@@ -1072,27 +1077,29 @@ private static function get_setting_nodes( $theme_json, $selectors = array() ) {
...
+	 *                         'all': css variables, block classes, preset classes. The default.
+	 *                         'block_styles': only block & preset classes.
+	 *                         'css_variables': only css variables.
+	 *                         'presets': only css variables and preset classes.
+	 * @param array  $origins A list of origins to include. By default it includes 'core', 'theme', and 'user'.
+	 *
 	 * @return string Stylesheet.
 	 */
-	public function get_stylesheet( $type = 'all' ) {
+	public function get_stylesheet( $type = 'all', $origins = self::VALID_ORIGINS ) {
```
Comment (youknowriad) [inline lib/class-wp-theme-json-gutenberg.php:1089]: Are we adding more complexity to the caller by adding new options here instead of absorbing the logic inside the class? Maybe this is not the right level of abstraction I'm looking for. When I want the stylesheet of a theme, why should I need to specify a "type" (meaning do we have dedicated use case to retrieve two different stylesheets for the same theme) or "origins"

**Review by youknowriad — COMMENTED** [review]
How can we test this to avoid regressions?

**Comment by youknowriad** [comment]
>  the block gap styles (see)

The block gap styles are not there but I think it's the right thing since now they are opt-in.

**Review by youknowriad — APPROVED** [review]
This is working as advertised (testing instructions).

A think some documentation or effort to clarify the backend APIs for themes would be great. #34843 is a good start in that aspect.

**Comment by chad1008** [comment]
Being newer to the code base, I won't speak to the specifics of how the change is implemented, but it does test well, and fixes the issue raised with `theme_support` declarations on themes without a theme.json. 👍 

Thanks @oandregal!

**Comment by oandregal** [comment]
This has been cherry-picked to the `release/11.5` branch.

**Comment by dennisheiden** [comment]
Thanks folks, this really saved us hours of overtime and helps planning for theme.json implementation in our theme.

**Comment by oandregal** [comment]
> How can we test this to avoid regressions?

I'm adding tests for this at https://github.com/WordPress/gutenberg/pull/34998

File: lib/class-wp-theme-json-gutenberg.php (hunk 1 above)
Comment (oandregal) [reply lib/class-wp-theme-json-gutenberg.php:1089]: > meaning do we have a dedicated use case to retrieve two different stylesheets for the same theme

Yeah, we have. The front enqueues a single stylesheet with all styles but the block editor needs two different stylesheets: one with the block styles that will be wrapped by `.editor-styes-wrapper` and the other with the CSS Custom Properties that won't be wrapped so they're available to the UI controls in the sidebar.

Comment (oandregal) [reply lib/class-wp-theme-json-gutenberg.php:1089]: I'm troubled about the `origins` as well. However, this is the result of having added them to the existing format for each preset. We still have use cases when we only want one preset (stylesheet for themes without theme.json support, settings from the theme, etc).

I'll continue with the explorations at https://github.com/WordPress/gutenberg/pull/34843 to create a higher-level API for consumers.
