### PR TITLE
Command Palette: Fix crash on block-related commands

### LINKED ISSUE #53863: Crash when trying to type something in commands after editing blocks
### Description

The Site Editor crashes when trying to type something in commands after editing blocks. You'll see the black screen. See the instructions below.

### Step-by-step reproduction instructions

1. Go to the Site Editor
2. Edit some blocks, such as changing the text, adding a block, and moving a block
3. Open commands 
Screen Shot 2023-08-22 at 13 46 49

4. Start tying and see the crash
[Image from Gyazo](https://gyazo.com/65223a0e3459e61f6a38cde170840387)

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/5287479/3826ae6e-2d16-40bd-9dbb-62bd4ad37cc9

### Environment info

- Gutenberg v16.5.0-rc.1
- WordPress 6.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### Related 

- https://github.com/WordPress/gutenberg/issues/53633

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #53863
Related to #52509

## What?

This PR fixes a problem in the command palette where the editor crashes due to block-related commands.

## Why?
This problem occurs when **building** a Gutenberg project, as mentioned in [this comment](https://github.com/WordPress/gutenberg/issues/53863#issuecomment-1691961566). Also, when built, the callback function name is also compressed, so the replace method does not produce the intended string. There is also a problem in terms of localization

## How?

I changed the command item to an object and specified the label, icon, callback function, etc. as individual properties.

## Testing Instructions

- Build this PR.
- Add a block.
- Launch the command palette.
- Confirm that the editor does not crash when typing `add`, `move`, etc. and that the commands are displayed.

Note: While I was investigating this issue, I discovered several problems in block related actions. These are not addressed in this PR as they also occur in trunk.

- #53921
- #53920

### CODE REVIEW

File: packages/block-editor/src/components/use-block-commands/index.js [hunk 1]
```diff
@@ -229,39 +229,54 @@ const useActionsCommands = () => {
...
+		},
+		{
+			name: 'duplicate',
+			label: __( 'Duplicate' ),
+			callback: onDuplicate,
+			icon: copy,
+		},
+	].map( ( { name, label, callback, icon } ) => {
 		return {
-			name: 'core/block-editor/action-' + callback.name,
```
Comment (youknowriad) [inline packages/block-editor/src/components/use-block-commands/index.js:255]: yes, it makes sense, we shouldn't be relying on callback.name here.

**Review by youknowriad — APPROVED** [review]

File: packages/block-editor/src/components/use-block-commands/index.js (hunk 1 above)
Comment (draganescu) [reply packages/block-editor/src/components/use-block-commands/index.js:255]: Yea what an oversight on my side - particularly around localization! 🤦🏻

**Comment by draganescu** [comment]
Thank you @t-hamano 🙇🏻

**Comment by t-hamano** [comment]
@youknowriad @draganescu Thanks for the review!
