### PR TITLE
Fix bug in the receiveBlocks action resulting in a broken block list

### LINKED ISSUE #35066: Block Editor State: Calls to receiveBlocks insert undefined values into block tree
### Description

Calling `receiveBlocks` inserts `undefined` innerBlocks into the root node of `block-editor` block tree state.

### Step-by-step reproduction instructions

1. Checkout this PR https://github.com/WordPress/gutenberg/pull/35067
2. Open the post editor
3. Verify that, for the information logged into the dev console, that `undefined` values are introduced into `block-editor` block tree state.

### Screenshots, screen recording, code snippet

Screen Shot 2021-09-22 at 9 50 27 PM

### Environment info

- WordPress dev (5.9-alpha-51739)
- Gutenberg dev

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by youknowriad**
closes #35066 

After the refactoring in #34241 an issue has been introduced in the `receiveBlocks` action that would result in a broken block list (and potentially JS errors in the editor).

Since this action is deprecated and was not used in Gutenberg (potentially used in some third-party plugins), we didn't notice the issue.

**Testing instructions**

 - Open the editor
 - Paste this in the console `wp.data.dispatch('core/block-editor').receiveBlocks( [ wp.blocks.createBlock( 'core/image' ) ] );`
 - A new image block should be added properly to your post.

### CODE REVIEW

File: packages/block-editor/src/store/test/reducer.js [hunk 1]
```diff
@@ -1696,60 +1696,6 @@ describe( 'state', () => {
 		} );
 
 		describe( 'blocks', () => {
-			it( 'should not reset any blocks that are not in the post', () => {
```
Comment (youknowriad) [inline packages/block-editor/src/store/test/reducer.js:1699]: The presence of the bug above was making this test pass but in reality, this behavior is something we removed a long time ago (we used to keep reusable blocks here even if they're not on the post)

**Review by Addison-Stavlo — APPROVED** [review]
Changes look reasonable and fix the bug in my testing as well!

Thanks for getting at this so promptly @youknowriad !

**Comment by youknowriad** [comment]
Let's try to get this at least in 11.6 cc @ntsekouras

**Comment by ntsekouras** [comment]
Cherry picked to 11.6 😄
