### PR TITLE
Fix pattern preview expanding height and scrollbar issues

### LINKED ISSUE #34729: Patterns using VH units or fixed background vertically expanding their previews endlessly
### Description

This is a replica of this issue: https://github.com/Automattic/wp-calypso/issues/56077

### Steps to Reproduce

1. Start by opening a page to edit
2. Click the blue plus sign to open the blocks & pattern search sidebar
3. Go to Patterns → Headers (in the Patterns drop down)
4. Start scrolling. The second pattern, "Large header with text and a button" does not load correctly and breaks the entire pattern selection box. 

I tested this on Chrome and did not see the same error/issue. 

In Safari, I also got an error that "This webpage is using significant memory. Closing it may improve the responsiveness of your Mac." 

I'm currently running Safari Version 14.1.2 (16611.3.10.1.6) on macOS Big Sur, version 11.5.2. 16" 2019 MacBook Pro. 

Video of the error: 

https://user-images.githubusercontent.com/30205248/132394213-f4588668-003c-4fea-9aec-0a6e2806f971.mov

### Screenshots, screen recording, code snippet

_No response_

### Operating System

macOS

### OS Version

11.5.2

### Browser

Safari

### Browser Version(s)

14.1.2

### Is this specific to applied theme? If so, what is the theme name?

I tested using Blank Canvas and also Bradford. Issue happened on both themes. 

### Console and/or error logs

_No response_

### Available Workarounds

You can use a different web browser - I was able to select a header pattern in Chrome. 

### Reproducibility

_No response_

### Other information

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #37573: Individual Patterns have scrollbars in Inserter making it difficult to scroll through
### Description

With WordPress beta 4, after opening the Inserter, I found that the various patterns show a scroll bar and are randomly very condensed. This makes it hard to quickly navigate between patterns while scrolling as sometimes the focus gets lost in scrolling in the pattern itself.

### Step-by-step reproduction instructions

1. Open Inserter.
2. Switch to patterns tab.
3. Try scrolling down through the patterns.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/147023921-676f4c23-ed30-494f-bf33-3d6e1cb955b7.mov

### Environment info

- WordPress 5.9 Beta 4
- TT2
- Chrome
- No Gutenberg

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
Resolves #34729
Resolves #37573.

Description by @jasmussen

This PR fixes the scrollbar shown inside thumbnails and applies a bandaid to stop `vh` based patterns from endlessly expanding.
In testing, it became clear that 100vh equals the height of your browser. Inside an iframe, things are different. This [StackOverflow question](https://stackoverflow.com/questions/34057239/css-vh-units-inside-an-iframe) led me to [this spec note](https://www.w3.org/TR/css-values/#viewport-relative-lengths):

>The viewport-percentage lengths are relative to the size of the initial containing block. When the height or width of the initial containing block is changed, they are scaled accordingly.

That seems to suggest it’s very easy to create a race condition, as “initial containing block” can’t be properly sized until content inside is loaded.
Because of that, this PR applies a pixel based max-height. A tall one, and one that will let the VH based pattern scale until it reaches that max-limit, but nevertheless it should mitigate the issue.
As noted in comments in the code, a better fix might be apply a max-height based on the initial-content height. But due to the iframe scaling behavior, this seems nontrivial

## How has this been tested?
I tested with TT2, Blockbase, and Blank Canvas themes. The "vertically expanding" issue was most visible with Blank Canvas.

## Screenshots 
1. Using "Blank Canvas" open the Inserter > Patterns tab.
2. Try switching between categories "Featured," "Blank Canvas" and "Links in Bio".
3. Confirm that pattern previews don't expect vertically and that they don't have visible scrollbars.

Try similar testing method with different Classic and Block themes.

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [x] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by Mamaduka** [comment]
Note: As a future follow-up, we might want to review `useResizeObserver` and the library it uses under the hood. Check if we can avoid similar race conditions when viewport units are used.

**Comment by cbravobernal** [comment]
WP Version: 5.9-beta3-52380
Gutenberg: trunk with branch `fix/expanding-thumbnails`
Steps done:
 - Install Blank Canvas theme
 - Go to post editor
 - Go to patterns
 - Used selector to switch between categories.
 - Screen height used for testing: 1380px
 
 Conclusions:
It seems that enters into a height styles adjustment loop.

https://user-images.githubusercontent.com/37012961/150763204-3a652677-4714-4d66-bc5a-e3e40d87d195.mov

File: packages/block-editor/src/components/block-preview/auto.js [hunk 1]
```diff
@@ -33,6 +34,18 @@ function AutoBlockPreview( { viewportWidth, __experimentalPadding } ) {
 		};
 	}, [] );
 
+	// Avoid scrollbars for pattern previews.
+	const editorStyles = useMemo( () => {
+		if ( styles ) {
+			return [
+				...styles,
+				{ css: 'body{overflow:hidden;}', __unstableType: 'presets' },
```
Comment (talldan) [inline packages/block-editor/src/components/block-preview/auto.js]: I left a comment over here, but just wanted to make sure you see it: https://github.com/WordPress/gutenberg/issues/37573#issuecomment-1019923503

I think if we need to override a style in the iframe, it'd be good to also do something like `height: unset`, the reason being that `height: 100%` is what's causing the scrollbar for patterns.

I'm not sure if you also need `overflow:hidden` to fix the other issue. It seems ok in conjunction with overriding the height, but just `overflow:hidden` on its own causes patterns to be cropped unnecessarily.

Comment (talldan) [reply packages/block-editor/src/components/block-preview/auto.js]: Here's a comparison to show what I mean:

**Just `overflow: hidden` on the preview body:**
Screen Shot 2022-01-24 at 6 13 00 pm

**`height: unset` and optionally `overflow: hidden` on the preview body:**
Screen Shot 2022-01-24 at 6 11 40 pm

It's subtle, but you can see for the second one there's the correct spacing at the bottom of the preview when unsetting the height. My concern is that some patterns may be more affected than others by this effect.

Comment (Mamaduka) [reply packages/block-editor/src/components/block-preview/auto.js]: Thanks, @talldan.

Added the rule to unset height.

**Comment by jasmussen** [comment]
> It seems that enters into a height styles adjustment loop.

Thanks for the video, that's helpful. I want to note I've seen that issue separately from the patterns panel, occasionally in the block inspector as well, so although a frustrating issue, I believe it's a separate one. Can you reproduce that one on trunk as well? In my past experience, the issue "goes away" by simply making the browser taller or shorter.

**Comment by Mamaduka** [comment]
Thanks for testing, @c4rl0sbr4v0.

That might not be related to this fix. I've seen a similar issue before. Unfortunately, we can fix everything an hour before RC4.

Can you confirm that PR fixes the original issues?

**Comment by jasmussen** [comment]
Thanks for working on this, thanks for pushing the fix. This is working well for me, and substantially better than trunk:

- I see no scrollbars
- I see no ever-expanding VH based patterns

I tested with a number of themes. TT2:
tt2

TT1 Blocks:

tt1blocks

TT1 (classic theme):
tt1

My own theme which has very crazy no-good margin rules:

own theme

One thing to keep in mind is that these thumbnails are subject to the editor styles that the theme loads into them. Which means if the theme (like my own) loads some crazy styles into the editor, they will affect thumbnails as well, and they might not look like "thumbnails". 

The addition of overflow and max-height rules feel completely sensible to me, and act as guard-rails. For example this prank pattern could wreak havoc without any guard-rails:

```
<!-- wp:group {"style":{"color":{"background":"#ff0000"},"spacing":{"padding":{"top":"20px","right":"20px","bottom":"200vh","left":"20px"}}}} -->
<div class="wp-block-group has-background" style="background-color:#ff0000;padding-top:20px;padding-right:20px;padding-bottom:200vh;padding-left:20px"><!-- wp:paragraph -->
<p>Buy Acme™ Brand Space Suits!</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```

A 200vh bottom padding would take up all the space of the pattern browser if we don't cap it. 1800px as a value was chosen because in my testing, it was sufficient for every pattern I could see. In the case of the above april fools pattern, the max-height would benefit from the overflow rule, ensuring no scrollbar appeared.

Because of the simplicity of the height, overflow and max-height rules added, and because it tests well for me, this feels like a good fix.

It could always use a ton of additional testing, looking specifically for patterns that have scrollbars or scale infinitely. In my testing, I couldn't find any.

**Comment by carolinan** [comment]
Windows 10, Chrome Version 97.0.4692.99, WordPress 5.9-RC3-52619 and Gutenberg with the PR applied.

[Theme: Frost. Pattern: "Sample home page."](https://github.com/wpengine/themes/blob/trunk/frost/inc/patterns/page/page-home.php)
This pattern is exceptionally long because it is meant to display an entire page.
In the preview, the content in the pattern is cut off but the box that contains the pattern continues to expand down.

Pattern content is cut off but the container is not.

**Comment by cbravobernal** [comment]
> Thanks for the video, that's helpful. I want to note I've seen that issue separately from the patterns panel, occasionally in the block inspector as well, so although a frustrating issue, I believe it's a separate one. Can you reproduce that one on trunk as well? In my past experience, the issue "goes away" by simply making the browser taller or shorter.

It is indeed. It happens in `trunk`, and "goes away" by resizing.

**Comment by jasmussen** [comment]
Thanks for the steps to reproduce Carolina.

> In the preview, the content in the pattern is cut off but the box that contains the pattern continues to expand down.

The max-height applies to the iframe, but the container doesn't collapse down to that content. I'm investigating.

**Comment by cbravobernal** [comment]
Tested with themes:
 - Tove
 - Livro
 - Mebae
 - Videomaker
 
 All of them are working as expected after the PR 🎉

**Comment by jasmussen** [comment]
I've taken this PR through additional testing now, and wanted to leave a few general notes.

- The expansion of VH patterns is classic themes only, and does appear to be “fixed” by removing default margins from `packages/edit-post/src/classic.scss`. However, margins on their own should not cause this such an expansion, removing those default margins would be unlikely to would fix every case of this.
  - Props @ixkaito for [discovering this margin issue](https://github.com/WordPress/gutenberg/issues/34729#issuecomment-1019943997).
- It seems like `100vh` when applied inside an iframe is the same height as the height of the container (i.e. min-content). That means the ever-expanding issue is not about how tall 100vh is, but rather seems like a race condition that occurs somewhere between the resizing code and the combination of those margins and VH units.
- It makes sense to have a max-height as a guard-rail, and an overflow-rule for the scrollbars. The rules as they are in this PR serve as a good small bandaid. They are also rules that we can keep around in the long term, even for when we find a way to fix the race condition in a future PR; they set boundaries on [the crazy example code I suggested here](https://github.com/WordPress/gutenberg/pull/38175#issuecomment-1019981194).
- However when we _do_ fix the the race condition, the change we should make to today's bandaid is to _increase_ the max-height to a taller value to better [handle full-page patterns](https://github.com/WordPress/gutenberg/pull/38175#issuecomment-1019983575). 

All that is to say: I think we should land the PR as a big improvement over what's shipping in trunk, and as a first step on the journey. Thanks for the work!

**Comment by ndiego** [comment]
Yes this is an improvement. The pattern still "grows", but stops when it hits the max-height. 

vh-issue
 
While this issue does need an eventual fix, I wonder if adding a `viewportHeight` attribute to pattern registration would be helpful to theme developers. It looks like we will always need a max-height to avoid this race condition and this would allow theme devs to set that manually if they need to for specific patterns.

**Comment by Mamaduka** [comment]
It looks like we're good to land this in the plugin and WP 5.9, see [Slack thread](https://wordpress.slack.com/archives/C02QB2JS7/p1643016553443600) for more details.

**Comment by hellofromtonya** [comment]
Hello all 👋 I concur with @jasmussen @Mamaduka and @ndiego that this PR is an improvement though not a full fix for the root cause. [In talking with Joen in slack](https://wordpress.slack.com/archives/C02QB2JS7/p1643030917446500?thread_ts=1643016553.443600&cid=C02QB2JS7) about if the root cause is known and if this PR is a partial fix:

>we have an idea of the root cause but it's non trivial, and even with the root cause fixed, what's added in this PR should be complementary.

As this fix is complementary and an improvement, I agree that it can be merged and backported to include in 5.9 RC4 👍

**Review by jasmussen — APPROVED** [review]
This tests well for me. It's a vast improvement over what's shipping in trunk, it serves as an initial guardrail against infinitely tall patterns, and it's a fix that can be built upon further with a subsequent fix of the root race condition. In that light, shipping this max-height is a necessary step on the road.

**Comment by ixkaito** [comment]
Hello all! I'm doing an improvement PR. Please wait a second for me.

**Review by hellofromtonya — APPROVED** [review]

**Comment by ixkaito** [comment]
I sent a PR to this branch. https://github.com/WordPress/gutenberg/pull/38180 I think this should be the permanent fix. And I think the `transform` property was in the wrong place.

**Comment by Mamaduka** [comment]
Thank you, @ixkaito.

Do you mind opening a new PR against trunk? We won't be able to ship it with WP 5.9, but if it works, it would significantly improve the plugin

**Comment by ixkaito** [comment]
Thank you @Mamaduka ! Of course. I'll do it.

**Comment by ixkaito** [comment]
I re-sent the PR to trunk. Please check it. https://github.com/WordPress/gutenberg/pull/38181

**Comment by ndiego** [comment]
Just testing in RC4, still a lot of issues 😢  This PR was definitely an improvement though, most noticeably in Gutenberg itself, but there seems to be a larger issue with regards to the way WordPress handles stylesheet concatenations. I am also still seeing some scrollbars so maybe we should keep #37573 open 🤔

**Comment by ellenbauer** [comment]
Like @ndiego I've just tested with RC4 without the Gutenberg plugin active and the issues are still present. I used our Aino theme but the 2022 gives a similar experience. 

The scrollbars are gone, but the height of the patterns is not displayed correctly (some are too short, some stretch longer than the actual height. So now for the short ones no preview is possible at all, see:

Screen Shot 2022-01-25 at 1 25 35 PM

**Comment by Mamaduka** [comment]
Thanks for testing, @ellenbauer.

@ndiego or @ellenbauer, do you mind creating a new issue? I will add to the 5.9.1 milestone and re-post the technical findings of the problem so far.

As Nick mentioned, the way WP handles stylesheet concatenations can cause different results. Currently, we can't reproduce the same environment via the plugin.

**Comment by richtabor** [comment]
> Like @ndiego I've just tested with RC4 without the Gutenberg plugin active and the issues are still present. I used our Aino theme but the 2022 gives a similar experience.

@ellenbauer Do they still get cut off if you're not loading extra styling from your plugin?

**Comment by richtabor** [comment]
I'm seeing the same experience with utility styles that are added with Extendify. If I don't have those loaded, then the scaled previews are generated in time for the height to not be cut off.
