### PR TITLE
Fix gradient RGBA/HSLA inputs' width

### LINKED ISSUE #24201: Gradient RGBA/HSLA inputs are not wide enough in WordPress 5.5
**Description**
When adding a gradient with RGBA or HSLA color values to a block, the increment buttons of number inputs cover up the inputs' values. The design worked well enough with 3 inputs (RGB/HSL) in WordPress 5.4, but there is a fourth input now in 5.5.

Originally reported by MarkS99 on Trac: https://core.trac.wordpress.org/ticket/50689

**Steps to reproduce**
1. Create a Group block (or another block that supports gradient backgrounds).
2. Expand Color Settings and choose Gradient.
3. Click an existing gradient control point or create a new one (circles along the pill-shaped bar).
4. Click the chevron icon next to the hexadecimal input to see the RGBA or HSLA inputs.
5. Type any value in each input. If your browser/user agent has increment buttons, those likely will overlap the value.

**Screenshots**
1. Visible increment buttons overlap HSLA inputs in Windows Firefox
HSLA inputs in Firefox

2. RGBA inputs in Windows Chrome (hidden increment buttons show on hover/focus)
RGBA inputs in Chrome

**Versions:**
- MarkS99 found the problem using WordPress 5.5-beta-2 on Mac OSX in Chrome, Safari & Firefox.
- My screenshots are from a more recent trunk version (still 5.5) on Windows 10, without the plugin, but I still see it with Gutenberg 8.6.0 activated.

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description

Fixes: https://github.com/WordPress/gutenberg/issues/24201

When adding a gradient with RGBA or HSLA color values to a block, the increment buttons of number inputs cover up the inputs' values.

Steps to reproduce and screenshots in the issue.

### CODE REVIEW

File: packages/components/src/color-picker/inputs.js [hunk 1]
```diff
@@ -178,7 +178,7 @@ export class Inputs extends Component {
 			return (
 				<fieldset>
 					<VisuallyHidden as="legend">
-						{ __( 'Color value in RGB' ) }
+						{ __( 'Color value in RGBA' ) }
```
Comment (youknowriad) [inline packages/components/src/color-picker/inputs.js:181]: Do you think this should stay "RGB" unless `disableAlpha` is false?

File: packages/components/src/color-picker/inputs.js [hunk 2]
```diff
@@ -231,7 +231,7 @@ export class Inputs extends Component {
 			return (
 				<fieldset>
 					<VisuallyHidden as="legend">
-						{ __( 'Color value in HSL' ) }
+						{ __( 'Color value in HSLA' ) }
```
Comment (youknowriad) [inline packages/components/src/color-picker/inputs.js:234]: Same here

File: packages/components/src/color-picker/inputs.js (hunk 1 above)
Comment (ntsekouras) [reply packages/components/src/color-picker/inputs.js]: You're right. I missed that. Thanks!

File: packages/components/src/color-picker/style.scss [hunk 3]
```diff
@@ -227,6 +227,11 @@
 	padding-top: 16px;
 	display: flex;
 	align-items: flex-end;
+	min-width: 22em;
```
Comment (youknowriad) [inline packages/components/src/color-picker/style.scss:230]: Why do we use "em"s here?  It seems like we prefer pixels in general in Gutenberg?

Comment (youknowriad) [reply packages/components/src/color-picker/style.scss:230]: It is still possible to have the issuue on mobile 
Capture d’écran 2020-07-27 à 11 21 09 AM 

I  wonder if a better fix is to wrap inputs (return to the line) when they reach a certain size instead of increasing the popover size.

Comment (ntsekouras) [reply packages/components/src/color-picker/style.scss:230]: > I wonder if a better fix is to wrap inputs (return to the line)

What do you mean by that?

> It seems like we prefer pixels in general in Gutenberg

Okay, I'll use pixels.

>Issue on mobile

Is this the min width we should make sure it's shown properly? `$break-mobile: 480px;`

Comment (ntsekouras) [reply packages/components/src/color-picker/style.scss]: I've made the changes to be visible in mobile too with the minimum `min-width` required. 

> I wonder if a better fix is to wrap inputs (return to the line) when they reach a certain size instead of increasing the popover size.

@youknowriad just let me know what did you mean, so I can maybe explore a different approach.

If you meant though to listen to input changes and change layout or resize, I believe it would cause an unpleasant/confusing user experience.

**Review by youknowriad — APPROVED** [review]
I think this is a good fix for the moment.
I was thinking maybe if the width is not enough to show 4 inputs, move one to the row (flex-wrap) but it could be explored later.
