### PR TITLE
Spacing visualizer: Fix display of unexpected visualizer for certain mouse actions

### LINKED ISSUE #45738: SpacingInputControl: Certain mouse movements leave the visualizer visible
### Description

Related to: #45054, #44955

In the `SpacingInputContorl`, the visualizer remains after mousing out of the control when certain mouse actions are performed.

### Step-by-step reproduction instructions

- Mouse over the slide for padding or margin control. Here you'll see the visualizer.
- Drag the dots to change the value.
- Mouse out from the control.
- After a short time the visualizer will disappear, but mouse in on the control again before the visualizer disappears.
- Repeat mouse in and mouse out to make sure the visualizer does not disappear unless you select another block.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/54422211/201503423-815fd204-0bf1-443a-af78-fabeff2cb3b7.mp4

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fix #45738

## What?
This PR fixes display of unexpected visualizer for certain mouse actions

## Why?

In the `SpacingInputControl` component, if you drag the slider handle to change the value and then mouse out, the visualizer disappears after 400 milliseconds via `setTimeout`.

https://github.com/WordPress/gutenberg/blob/92d28ca4096457135dc7f213a900ec19ced1c8b6/packages/block-editor/src/hooks/margin.js#L215-L227

However, if you mouse in again before 400 milliseconds have passed, the timer is cleared in the cleanup function and the process to set the `isActive` state to false is not executed.

## How?
I have added a process to change the `isActive` state to false in the cleanup function. My understanding is that each time a component is rendered, cleanup function is performed before the effect is executed. This means that isActive is false once before the effect is processed. The effect of turning off the visualizer after 400 milliseconds is performed after the cleanup function, so it should not affect the previous behaviour.

## Testing Instructions

- Use the mouse to control the sliders for margins and padding.
- Mouse out, then mouse in immediately.
- When you mouse out again, make sure the visualizer disappears.

### Before

https://user-images.githubusercontent.com/54422211/201506483-3ab2be7d-f943-4674-aef4-f3e4fcca4069.mp4

### After

https://user-images.githubusercontent.com/54422211/201506484-db32d8ed-a611-420b-acf3-674e4eb5369e.mp4

### CODE REVIEW

File: packages/block-editor/src/hooks/margin.js [hunk 1]
```diff
@@ -217,14 +217,15 @@ export function MarginVisualizer( { clientId, attributes, forceShow } ) {
 			setIsActive( true );
 			valueRef.current = margin;
 
-			clearTimer();
```
Comment (t-hamano) [inline packages/block-editor/src/hooks/margin.js:220]: Since clearing the timer is always performed by the cleanup function, I think it isn't necessary to do it again here.

**Review by youknowriad — APPROVED** [review]
This fixes the issue for me. Thanks
