### PR TITLE
Firefox: fix issue where it selects a nearby contentEditable

### LINKED ISSUE #42535: Selecting Parent Block Selects Child Block in Firefox
### Description

In WordPress 6.0 when using Firefox, there is a bug that makes it very difficult to select parent blocks.

When clicking the parent block (and explicitly outside a child block) the parent block is briefly selected and then the nearest child block is selected.

I have observed this behavior in the Group block, Columns block, and Media & Text block content container (clicking the image works to select the block).

### Step-by-step reproduction instructions

1. Insert a Group block
2. Give it a background color so it has some padding (in most themes, like Twenty Twenty Two)
3. Add a paragraph inside the group block with a few words
4. Click inside the group block but outside the paragraph (in the padding added by the background color)

Expected result: Group block is selected

Actual result: Group block is _briefly_ selected and then the paragraph block is selected instead

### Screenshots, screen recording, code snippet

The basic bug described in the step-by-step instructions:

https://user-images.githubusercontent.com/1238696/179756355-a1574f7d-ef53-4d5f-9d84-bd4c4458660d.mp4

Note the nearest child block selection behavior (selecting even the nearest list-item, not just the nearest list block):

nearest-child-block-selection-bug

### Environment info

- Windows 10 / Firefox 103
- WordPress 6.0 (and 6.0.1)
- Twenty Twenty Two
- No plugins
- No Gutenberg

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Fixes #42535.

## Why?
Bug fix.

## How?

See code comment.

## Testing Instructions
See issue.

### CODE REVIEW

File: packages/rich-text/src/component/use-input-and-selection.js [hunk 1]
```diff
@@ -140,6 +140,15 @@ export function useInputAndSelection( props ) {
 			// for the rich text instance that contains the start or end of the
 			// selection.
 			if ( ownerDocument.activeElement !== element ) {
+				// Only process if the active elment is contentEditable, either
+				// this rich text instance or the writing flow parent. Fixes a
+				// bug in Firefox where it strangely selects the closest
+				// contentEditable element, even though the click was outside
+				// any contentEditable element.
+				if ( ownerDocument.activeElement.contentEditable !== 'true' ) {
```
Comment (mtias) [inline packages/rich-text/src/component/use-input-and-selection.js:148]: Do we know if this popped recently as a bug in FF itself?

Comment (ellatrix) [reply packages/rich-text/src/component/use-input-and-selection.js:148]: No idea. Could have been there all along. This code was introduced relatively recently for partial multi selection.

**Review by mtias — APPROVED** [review]
