### PR TITLE
Move the directives and markup needed for the lightbox to block supports

### LINKED ISSUE #50973: Experiment: Duotone filter in Image block lightbox not working
## Description

Duotone filters are not applied when using the experimental Lightbox behavior.

Follow-up to https://github.com/WordPress/gutenberg/pull/50373

### Step-by-step reproduction instructions

1. Enable Core blocks in the Gutenberg Experiments settings page
2. Add an image to a post
3. Go to the image block styles, and select a filter under Filters > Duotone
4. Enable the lightbox by selecting the image block setting Advanced > Behaviors > Lightbox
5. Save and view the post
6. Notice that the duotone filter is not applied

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/5360536/098fe909-e3a8-4215-bae4-bcf7ed7a0b10

### Environment info

WordPress 6.2.2, Gutenberg 15.9.0-rc.1 
Chrome 113.0.5672.92
MacOS 12.5

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by SantosGuillamot**
_Marking this as a draft because the code will need to be updated with the changes made in [this other pull request](https://github.com/WordPress/gutenberg/pull/51206)._

## What?
Instead of having the directives and the markup needed to make the lightbox behavior work in the Image block `render_callback`, this pull request moves them to a `render_block` filter called in the block supports.

## Why?
There are mainly two reasons for this pull request:
* Right now, if there are changes applied to the Image markup through a `render_block` filter (like [the duotone](https://github.com/WordPress/gutenberg/issues/50973) is doing adding a class), those changes are not applied to the markup. It would solve [this bug](https://github.com/WordPress/gutenberg/issues/50973).
* It would be a first step of abstracting the lightbox behavior so it is not completely coupled to the Image block and can be easily reused.
 
Note that this pull request doesn't aim to completely abstract the lightbox behavior, it would be just a good first step. There are some things missing in that regard that I believe could be handled in a subsequent pull request:
* Move the styles and the scripts outside of the Image block.
* Modify the markup, directives, and styles to make it work properly for other blocks apart from the core/image.

## How?
* Remove the directives and markup from the `render_callback` of the image block.
* Register a new "block supports" for `supports.behaviors.lightbox` using `WP_Block_Supports::get_instance()->register`.
* When the behaviors support is registered, if the block has the lightbox support set to true, add a `render_block_{$this->name}` filter to add the directives and the markup.
* Update the editor hook to read the block supports.

## Testing Instructions
* Enable the "Interactivity API and Behaviors UI" in Gutenberg->Experiments.
* Check that the lightbox keeps working as expected.
* Add a duotone filter to some of your images and check that it works.

## Video explanation

https://www.loom.com/share/09ffb096070943d7b73ed0d885c40fd4

### CODE REVIEW

**Review by artemiomorales — APPROVED** [review]
Looks good to me!

EDIT: Realized I shouldn't have approved these changes yet, as we need to make sure it's synced with the latest code from https://github.com/WordPress/gutenberg/pull/51206

**Review by cbravobernal — APPROVED** [review]
Looks good to me.

I would move in a near future each behavior php code (the one that updates the markup to enhance the experience) to its own file.

File: lib/block-supports/behaviors.php [hunk 1]
```diff
@@ -0,0 +1,136 @@
...
+
+/**
+ * Add the directives and layout needed for the lightbox behavior.
+ * This functions shouldn't be in this file. It should be moved to a package (or somewhere else), where all the behaviors logic is defined.
+ *
+ * @param  string $block_content Rendered block content.
+ * @param  array  $block         Block object.
+ * @return string                Filtered block content.
+ */
+function gutenberg_blocks_supports_add_lightbox( $block_content, $block ) {
```
Comment (ajlende) [inline lib/block-supports/behaviors.php]: Small nit. All of the other block supports that update rendering follow the same naming pattern which makes it a little easier to search through.

`gutenberg_render_behaviors_support` would match the pattern here.

File: lib/block-supports/behaviors.php [hunk 2]
```diff
@@ -0,0 +1,136 @@
...
+
+	$block_type->attributes['behaviors'] = array(
+		'type' => 'object',
+	);
+
+	// If it supports the lightbox behavior, add the hook to that block.
+	// In the future, this should be a loop with all the behaviors.
+	$has_lightbox_support = block_has_support( $block_type, array( 'behaviors', 'lightbox' ), false );
+	if ( $has_lightbox_support ) {
+		add_filter( 'render_block_' . $block_type->name, 'gutenberg_blocks_supports_add_lightbox', 15, 2 );
```
Comment (ajlende) [inline lib/block-supports/behaviors.php]: Why are we using priority 15 instead of 10? We probably want to add a comment explaining that.

I can see that we'd want it to run later than the other block supports, but I figured that's why you were using the `render_block_{block_name}` instead of `render_block` filter.

**Review by ajlende — COMMENTED** [review]
A couple small nits, but otherwise this is looking good. I'm happy the duotone support works for it without much hassle this way.

Also, I found another issue (https://github.com/WordPress/gutenberg/issues/51276) while testing, but I think it's unrelated to this change.

File: lib/block-supports/behaviors.php (hunk 2 above)
Comment (SantosGuillamot) [reply lib/block-supports/behaviors.php]: I thought that there could be external plugins using the `render_block_{block_name}` filter to modify the image as the duotone is doing, and I believe this hook should run after the default ones.

I'll add a comment for that. Thank you! 🙂

File: lib/block-supports/behaviors.php (hunk 1 above)
Comment (SantosGuillamot) [reply lib/block-supports/behaviors.php]: Oh, great! I will make that change as well 🙂

**Comment by SantosGuillamot** [comment]
Merging this pull request. As the functionality is still experimental, we can still change it in the future.

File: lib/block-supports/behaviors.php [hunk 3]
```diff
@@ -0,0 +1,138 @@
...
+		'type' => 'object',
+	);
+
+	// If it supports the lightbox behavior, add the hook to that block.
+	// In the future, this should be a loop with all the behaviors.
+	$has_lightbox_support = block_has_support( $block_type, array( 'behaviors', 'lightbox' ), false );
+	if ( $has_lightbox_support ) {
+		// Use priority 15 to run this hook after other hooks/plugins.
+		// They could use the `render_block_{$this->name}` filter to modify the markup.
+		add_filter( 'render_block_' . $block_type->name, 'gutenberg_render_behaviors_support_lightbox', 15, 2 );
```
Comment (ockham) [inline lib/block-supports/behaviors.php:34]: Bit late to this, but I think there's a dedicated `apply` argument to `WP_Block_Supports::get_instance()->register()` that's typically used to render the block-supports on the frontend based on the attribute(s) registered (see e.g. [how the`align` block-support does it](https://github.com/WordPress/wordpress-develop/blob/9fe8cdf1264c1ab87ef234219aa3633cd5e7d3b2/src/wp-includes/block-supports/align.php#L63)). 

Maybe that would be a better fit here rather than using the (more generic) `render_block_{$type}` filter?

Comment (cbravobernal) [reply lib/block-supports/behaviors.php:34]: We won't be landing this into 6.3, so I guess is not to late to update it (or make another PR to update it).

Comment (SantosGuillamot) [reply lib/block-supports/behaviors.php:34]: We can definitely explore that option deeper. I think we tried, but we didn't fully understand how that worked, so we ended up using a filter like [the duotone](https://github.com/WordPress/wordpress-develop/blob/9fe8cdf1264c1ab87ef234219aa3633cd5e7d3b2/src/wp-includes/block-supports/duotone.php#L590-L597). We need to run this code after other filters, like the duotone, run, so we thought using another filter with lower priority was the proper way. But I'm happy to explore other possibilities if you think that's possible.
