### PR TITLE
Navigation Screen: Indicate when a menu is deleted and show the menu switcher afterwards

### LINKED ISSUE #25435: Delete menu option shows no visible indication that deletion is in progress on navigation screen
**Describe the bug**
Clicking 'Delete Menu' doesn't result in any visual indication that the deletion is in progress. In my case the delete request took a few seconds to complete (I was on a slow internet connection when testing this). During that time it feels like the page has frozen and something has gone wrong momentarily until eventually the deletion happens.

**To reproduce**
1. If you're on a fast internet connection, use browser dev tools to throttle the connection.
2. Open the navigation screen
3. Selected a menu you wish to delete
4. Using the block settings (cog) menu click the delete menu option
5. Observe that nothing happens until the menu is deleted

**Expected behavior**
There are a few options:
- The delete button shows a progress indication
- A loading spinner or snackbar is shown
- The menu is deleted optimistically by the client while the request to the server is still in progress.

### PR DESCRIPTION
**Pull request by grzim**
## Description

Closes https://github.com/WordPress/gutenberg/issues/25435

According to [comment](https://github.com/WordPress/gutenberg/issues/25435#issuecomment-776993797) the following steps have been added:
- When a menu is being deleted (call to the API is being made) a `delete` button has a `busy` status.
- All elements are dimmed when a call is being made
- A snack bar is shown, informing a user that a menu has been deleted
- When the API call is finished, a panel to choose another menu is displayed

## How has this been tested?

Tested manually.

I order to test:
1. Navigate to Gutenberg > Navigation (beta)
2. Select the menu area, and the navbar will appear
3. Click the `delete menu` button in the navbar
4. When a prompt asking, if a menu should be deleted, appears then click on the `OK` button

## Types of changes

New feature

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/edit-navigation/src/components/inspector-additions/delete-menu-panel.js [hunk 1]
```diff
@@ -4,12 +4,16 @@
...
+export default function DeleteMenuPanel( {
+	onDeleteMenu,
+	isMenuBeingDeleted,
+} ) {
 	return (
 		<PanelBody className="edit-navigation-inspector-additions__delete-menu-panel">
 			<Button
 				isLink
 				isDestructive
+				className={ isMenuBeingDeleted && 'is-busy' }
```
Comment (talldan) [inline packages/edit-navigation/src/components/inspector-additions/delete-menu-panel.js]: There's an `isBusy` prop.

File: packages/edit-navigation/src/components/menu-selector/index.js [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+/**
+ * Internal dependencies
+ */
+import AddMenu from '../add-menu';
+
+export default function MenuSelector( { onSelectMenu, menus } ) {
+	return (
+		<div className="edit-navigation-menu-selector-wrapper">
+			<div className="edit-navigation-menu-selector-header">
+				{ __( 'Chose a menu to edit: ' ) }
```
Comment (talldan) [inline packages/edit-navigation/src/components/menu-selector/index.js]: Typo here:
```suggestion
				{ __( 'Choose a menu to edit: ' ) }
```

I think it should be an `h3` instead of a `div`.

File: packages/edit-navigation/src/components/menu-selector/index.js [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+import { __ } from '@wordpress/i18n';
+/**
+ * Internal dependencies
+ */
+import AddMenu from '../add-menu';
+
+export default function MenuSelector( { onSelectMenu, menus } ) {
+	return (
+		<div className="edit-navigation-menu-selector-wrapper">
+			<div className="edit-navigation-menu-selector-header">
```
Comment (talldan) [inline packages/edit-navigation/src/components/menu-selector/index.js]: The classnames should be `edit-navigation-menu-selector` and `edit-navigation-menu-selector__header` (https://github.com/WordPress/gutenberg/blob/master/docs/contributors/coding-guidelines.md#naming)

File: packages/edit-navigation/src/components/menu-selector/index.js [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+				{ __( 'Chose a menu to edit: ' ) }
+			</div>
+			<div className="edit-navigation-menu-selector">
+				<div className="editor-styles-wrapper">
```
Comment (talldan) [inline packages/edit-navigation/src/components/menu-selector/index.js]: Is this div needed?

File: packages/edit-navigation/src/components/menu-selector/index.js [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+							</Button>
+						) }
+						renderContent={ () => (
+							<AddMenu
+								className="edit-navigation-header__add-menu"
+								menus={ menus }
+								onCreate={ onSelectMenu }
+							/>
+						) }
+					/>
```
Comment (talldan) [inline packages/edit-navigation/src/components/menu-selector/index.js]: There's a lot of overlap with this change and the changes in https://github.com/WordPress/gutenberg/pull/29202. (specifically https://github.com/WordPress/gutenberg/pull/29202/files#diff-0910df9c480702dee864c775800b2fef76963c014cce2224ffd4236ef59bd0aaR108-R140).

For now I think it's best to avoid adding the Create New Menu button until that PR is merged.

File: packages/edit-navigation/src/components/menu-selector/index.js [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+ */
+import AddMenu from '../add-menu';
+
+export default function MenuSelector( { onSelectMenu, menus } ) {
+	return (
+		<div className="edit-navigation-menu-selector-wrapper">
+			<div className="edit-navigation-menu-selector-header">
+				{ __( 'Chose a menu to edit: ' ) }
+			</div>
+			<div className="edit-navigation-menu-selector">
```
Comment (talldan) [inline packages/edit-navigation/src/components/menu-selector/index.js]: The outermost element should have this classname, as mentioned in a previous comment. This should be something like `edit-navigation-menu-selector__menu`

File: packages/edit-navigation/src/components/menu-selector/index.js [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+				<div className="editor-styles-wrapper">
+					<MenuGroup>
+						<MenuItemsChoice
+							onSelect={ onSelectMenu }
+							choices={ menus.map( ( menu ) => ( {
+								value: menu.id,
+								label: menu.name,
+							} ) ) }
+						/>
+					</MenuGroup>
```
Comment (talldan) [inline packages/edit-navigation/src/components/menu-selector/index.js]: A MenuGroup should generally be in a `NavigableMenu`. `NavigableMenu` provides arrow key navigation between menu items and has the correct `role` of `menu`.

File: packages/edit-navigation/src/components/menu-selector/style.scss [hunk 8]
```diff
@@ -0,0 +1,16 @@
+.edit-navigation__menu-selector__select-menu-button {
+	width: 100%;
+}
+
+.edit-navigation-menu-selector {
+	padding: $grid-unit-15;
+	@extend .edit-navigation-editor;
+	&-header {
```
Comment (talldan) [inline packages/edit-navigation/src/components/menu-selector/style.scss]: This concatenation style is generally avoided on the project because it makes it harder to search the codebase.

File: packages/edit-navigation/src/components/layout/index.js [hunk 9]
```diff
@@ -105,18 +114,26 @@ export default function Layout( { blockEditorSettings } ) {
...
-									className="edit-navigation-layout__canvas"
-									ref={ canvasRef }
-								>
-									<Editor
-										isPending={ ! hasLoadedMenus }
-										blocks={ blocks }
+								{ isMenuDeleted ? (
+									<MenuSelector
+										onSelectMenu={ selectMenu }
+										menus={ menus }
```
Comment (talldan) [inline packages/edit-navigation/src/components/layout/index.js]: I think it'd be better to render this in the `EmptyState` component. Maybe we can rename `EmptyState` to `UnselectedMenuState`.

That should already have a lot of the necessary styles (though it will probably need a modifier for the narrower width) and it ensures the options that aren't needed (Select Menu, Add New, Manage Locations, Save) won't be visible:
Screenshot 2021-02-23 at 1 16 33 pm

File: packages/edit-navigation/src/components/layout/use-navigation-editor.js [hunk 10]
```diff
@@ -8,11 +8,17 @@ import { useState, useEffect } from '@wordpress/element';
...
+import { store as noticesStore } from '@wordpress/notices';
+import { __ } from '@wordpress/i18n';
 
 export default function useNavigationEditor() {
 	const [ hasFinishedInitialLoad, setHasFinishedInitialLoad ] = useState(
 		false
 	);
+	const [ selectedMenuId, setSelectedMenuId ] = useState( null );
+	const [ isMenuDeleted, setIsMenuDeleted ] = useState( false );
+	const [ isMenuBeingDeleted, setIsMenuBeingDeleted ] = useState( false );
```
Comment (talldan) [inline packages/edit-navigation/src/components/layout/use-navigation-editor.js]: There is a `isDeletingEntityRecord` selector that should be able to serve the same purpose.

File: packages/edit-navigation/src/components/menu-selector/style.scss [hunk 11]
```diff
@@ -0,0 +1,16 @@
+.edit-navigation__menu-selector__select-menu-button {
+	width: 100%;
+}
+
+.edit-navigation-menu-selector {
+	padding: $grid-unit-15;
+	@extend .edit-navigation-editor;
```
Comment (talldan) [inline packages/edit-navigation/src/components/menu-selector/style.scss]: I'm not a sass expert, but I know `@extend` isn't commonly used. 

I think it's better to provide consistent styles through reusable components rather than mixing together css.

This shouldn't be an issue if we repurpose `EmptyState` as mentioned in an earlier comment. That uses a `Card` component to provide the right border style.

File: packages/edit-navigation/src/components/layout/index.js [hunk 12]
```diff
@@ -87,7 +94,9 @@ export default function Layout( { blockEditorSettings } ) {
 						{ ! hasFinishedInitialLoad && <Spinner /> }
 
 						{ hasFinishedInitialLoad && ! hasMenus && (
-							<EmptyState />
+							<EmptyState
+								onCreate={ () => setIsMenuDeleted( false ) }
```
Comment (talldan) [inline packages/edit-navigation/src/components/layout/index.js]: Seems unusual that this is needed. What does it do?

File: packages/edit-navigation/src/components/layout/index.js (hunk 9 above)
Comment (grzim) [reply packages/edit-navigation/src/components/layout/index.js]: Using EmptyState for those two could be a little bit of overkill. Instead, I have updated MenuSelector to use the `<Card>` component so it shares the common styling. It is a bit different than in a mockup but is consistent with `<EmptyState>`

File: packages/edit-navigation/src/components/layout/index.js (hunk 12 above)
Comment (grzim) [reply packages/edit-navigation/src/components/layout/index.js]: after deleting a menu an app is in a new state where a `MenuSelector` is being displayed and the `header` is hidden. When a new menu is added a `MenuSelector` is hidden and `header` is displayed.  isMenuDeleted is an indicator informing which state should be presented

Comment (talldan) [reply packages/edit-navigation/src/components/layout/index.js]: The entire header shouldn't be hidden. In the mockup the 'Navigation' title is still visible. As is the 'Save' button, but lets ignore that for now.

`<Header>` already has some logic internally for hiding the necessary parts (currently using the `hasMenu` variable).

This is why I think consolidating with `EmptyState` is a better solution. `EmptyState` instead would be renamed to `UnselectedMenuState`.

Instead of using `hasMenu` to hide parts of the header, a variable called `hasUnselectedMenu` is used instead.

The logic becomes nicely consolidated and `EmptyState` doesn't need this extra prop.

File: packages/edit-navigation/src/components/layout/index.js (hunk 9 above)
Comment (talldan) [reply packages/edit-navigation/src/components/layout/index.js]: I've added some more detail on why I think using `EmptyState` is the right solution in a comment below:
https://github.com/WordPress/gutenberg/pull/29201#discussion_r586209001

**Comment by draganescu** [comment]
Tested this and works pretty good.

**Comment by talldan** [comment]
Nice work here. The end to end tests caught a small bug. When creating a new menu for the first time the menu switcher is displayed. The menu just created should be shown instead.

It looks like the `onCreate` prop for `UnselectedMenuState` isn't implemented.

**Comment by draganescu** [comment]
This seems to work well, but the new "Select menu" screen seems to conflict with #22623 which says that the default behavior in the navigation editor is to edit the last opened menu. Also I should be able to create a new menu right from that screen if we create a new one.

Is this select menu screen needed for this PR?

**Comment by grzim** [comment]
The last step of menu deletion is to show a menu selection window so a user can choose another menu to edit ( the last part of https://github.com/WordPress/gutenberg/issues/25435#issuecomment-776993797 ). It is a good catch though, that it should be possible to easily add a new menu, so I suggest adding an `add new` menu button to the menu selection screen.

**Comment by talldan** [comment]
> This seems to work well, but the new "Select menu" screen seems to conflict with #22623 which says that the default behavior in the navigation editor is to edit the last opened menu.

@draganescu That's how the current editor works, but it's not a cast iron rule. It's really up to a designer like @shaunandrews to define how this works. I think showing the menu switcher initially is a fine option, and if we decide to go with that we can close #22623 once this is merged. The existing end to end tests will need to be updated to cover this change in behaviour.

> The last step of menu deletion is to show a menu selection window so a user can choose another menu to edit ( the last part of #25435 (comment) ). It is a good catch though, that it should be possible to easily add a new menu, so I suggest adding an add new menu button to the menu selection screen.

@grzim This was discussed already in a resolved comment - https://github.com/WordPress/gutenberg/pull/29201#discussion_r580767510

We were both basically working on the same feature at the same time, which wasn't really optimal. Now that #29202 is merged the `MenuSwitcher` component developed there can be used in this PR.

**Comment by draganescu** [comment]
> the MenuSwitcher component developed there can be used in this PR.

Let's do that.

**Comment by shaunandrews** [comment]
> We were both basically working on the same feature at the same time, which wasn't really optimal.

Sorry if I contributed to this confusion; I always expected the menu switcher to be the same when accessed from the top area, or when shown after deleting. I literally copy/pasted the elements in Figma for the design.

> This seems to work well, but the new "Select menu" screen seems to conflict with #22623 which says that the default behavior in the navigation editor is to edit the last opened menu.

I don't see these as conflicting statements:
- If I have no menus, when visiting the screen I should see a create menu wizard.
- If I have one or more menu(s), when visiting the screen I should see the last menu I edited.
- If I delete a menu I should see the menu switcher.

> Also I should be able to create a new menu right from that screen if we create a new one.

This was already in the design:

image

**Comment by grzim** [comment]
I have updated the behavior to work as it used to - when a user navigates to navigator editor, the first menu is selected. This behavior should be changed to selecting the last edited menu, but this is out of the scope of this PR.

File: packages/edit-navigation/src/components/name-editor/index.js [hunk 13]
```diff
@@ -34,7 +34,7 @@ export function NameEditor() {
 				label={ __( 'Name' ) }
 				onBlur={ () => setIsMenuNameEditFocused( false ) }
 				className="edit-navigation-name-editor__text-control"
-				value={ editedMenuName }
+				value={ editedMenuName || '' }
```
Comment (draganescu) [inline packages/edit-navigation/src/components/name-editor/index.js]: What is this change about? Can we not have a menu name?

Comment (grzim) [reply packages/edit-navigation/src/components/name-editor/index.js]: nice catch, it is not needed anymore. I have changed it back.

File: packages/edit-navigation/src/components/layout/unselected-menu-state.js [hunk 14]
```diff
@@ -0,0 +1,43 @@
...
+	menus,
+} ) {
+	const showMenuSwitcher = menus?.length > 0;
+	return (
+		<div className="edit-navigation-empty-state">
+			{ showMenuSwitcher && <h4>{ __( 'Choose a menu to edit:' ) }</h4> }
+			<Card>
+				<CardBody>
+					{ showMenuSwitcher ? (
+						<MenuSwitcher
```
Comment (talldan) [inline packages/edit-navigation/src/components/layout/unselected-menu-state.js]: I think `MenuSwitcher` does still need to be wrapped with a `NavigableMenu` here. That will ensure arrow keys work for navigation when a menu item has focus.

It can't be added inside the `MenuSwitcher` component. `MenuSwitcher` is also used in `DropdownMenu` which adds `NavigableMenu` itself.

File: packages/edit-navigation/src/components/inspector-additions/index.js [hunk 15]
```diff
@@ -49,6 +49,12 @@ export default function InspectorAdditions( {
 					openModal={ openManageLocationsModal }
 				/>
 			</PanelBody>
+			<PanelBody>
+				<DeleteMenuPanel
```
Comment (talldan) [inline packages/edit-navigation/src/components/inspector-additions/index.js]: I see this button has moved to match the design in the issue.

I think the design below is ever so slightly more recent though, which shows it in the Menu settings 😄 

See https://github.com/WordPress/gutenberg/issues/28864#issuecomment-780083954

image

File: packages/edit-navigation/src/components/inspector-additions/delete-menu-panel.js [hunk 16]
```diff
@@ -4,12 +4,16 @@
 import { Button } from '@wordpress/components';
 import { __ } from '@wordpress/i18n';
 
-export default function DeleteMenu( { onDeleteMenu } ) {
+export default function DeleteMenuPanel( {
```
Comment (talldan) [inline packages/edit-navigation/src/components/inspector-additions/delete-menu-panel.js]: I think this should keep the name `DeleteMenu` as it doesn't have a Panel component within it any longer.

**Review by talldan — APPROVED** [review]
This is working well. Thanks for updating it @grzim.

There were a few very small things I noticed in testing, which seem to mostly be because of other changes since this was previously worked on.

Those can be tackled in this PR before merging , or in a separate PR.

edit: I also noticed some of the spacing is slightly wrong when testing:
Screenshot 2021-03-26 at 4 43 48 pm

Design:
Screenshot 2021-03-26 at 4 42 35 pm

In particular there's no spacing above the 'Create new menu' button. Not sure why it looks correct in the dropdown, but not here, but maybe some extra styles can be added to solve it.

**Comment by grzim** [comment]
Thanks, @talldan for testing.

When it comes to padding here:
image
it is a default padding for `<Card>` element. I can change it to match padding from `<MenuSwitcher>` in Header but then it should be also consistent with create the first element: 
image


which with smaller padding, in my opinion, does not look good:
image

**Comment by talldan** [comment]
@grzim There's that padding, but that wasn't the main part I was thinking of:
> In particular there's no spacing above the 'Create new menu' button. Not sure why it looks correct in the dropdown, but not here, but maybe some extra styles can be added to solve it.

**Comment by talldan** [comment]
Lets merge this and we can follow up with any styling adjustments.
