### PR TITLE
Fix timezone conflicts when setting global moment default timezone

### LINKED ISSUE #5179: Time zone issues by setting global moment time zone
## Issue Overview

I'm seeing issues with setting the global moment time zone to what amounts to be the time zone of the server. This overrides the moment time zone that might be used in themes or other plugins. In my case, the front-end theme for P2 which I'm also loading Gutenberg.

## Steps to Reproduce (for bugs)
1. Use moment library elsewhere after Gutenberg loads
2. Use moment to display a user's local timezone where user not in UTC/server zone 
3. Time zone is set globally to server zone, wrong time shows

## Possible Solution

My thought is to not set the global time zone on moment library but to create an instance of the moment library which is cloned and the timezone set on that which then gets used. 
Something like:

```
const now = moment();
const gutentime = now.clone();
gutentime.tz.setDefault( 'WP' );
```

For reference the timezone is set in `edit-post/index.js` which is configured from dateSettings in `lib/client-assets.php`

### PR DESCRIPTION
**Pull request by mkaz**
## Description

Creates a new WP timezone object which should be used across Gutenberg instead of relying on the global default timezone being set. 

Updates `isEditedPostBeingScheduled()` to use the new timezone when setting the Publish button to Schedule/Publish

Fixes #5179 

## How Has This Been Tested?

Verify the post publish button is correct per post date in future or not, should be Publish or Scheduled.

## Types of changes
The change should be non-breaking and fixing the issue when setting the default timezone. However, the code does remove the setDefault timezone, which looked like the Publish button was the only component that was using it.

Potential issue with any other code that is using moment and relying on the default timezone being set to the site's timezone.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by mkaz** [comment]
sigh, my branch was off another branch and not master. (Fixing)

File: edit-post/index.js [hunk 1]
```diff
@@ -23,19 +23,17 @@ export * from './api';
...
+// create WP timezone based off dateSettings
+const offsets = ( dateSettings.timezone.string ) ?  moment.tz.zone( dateSettings.timezone.string ).offsets : [ -dateSettings.timezone.offset * 60 ];
+const momentTimezone = {
+	name: 'WP',
+	abbrs: [ 'WP' ],
+	untils: [ null ],
+	offsets: [ offsets ],
+};
+const unpackedTimezone = moment.tz.pack( momentTimezone );
+moment.tz.add( unpackedTimezone );
```
Comment (youknowriad) [inline edit-post/index.js]: Do you think we should move this to `date/index.js` instead, since we're already using moment?

File: editor/store/selectors.js [hunk 2]
```diff
@@ -275,7 +276,7 @@ export function isCurrentPostPublished( state ) {
 	const post = getCurrentPost( state );
 
 	return [ 'publish', 'private' ].indexOf( post.status ) !== -1 ||
-		( post.status === 'future' && moment( post.date ).isBefore( moment() ) );
+		( post.status === 'future' && moment.tz( post.date, 'WP' ).isBefore( moment.tz( 'WP' ) ) );
```
Comment (youknowriad) [inline editor/store/selectors.js]: instead of repeating the same timezone initalization everywhere, is it possible to provide a specific moment constructor in `data/index.js` and always to `import { moment } from '@wordpress/date'` ?

Comment (mkaz) [reply editor/store/selectors.js]: yeh, I was thinking the some thing when I was finishing up this change.
It'd be much easier to do it all in one spot.

**Comment by mkaz** [comment]
@youknowriad let me know what you think of this approach 

Moment is a bit weird, it changes and handles things globally which can be dangerous. Also, it gets treated as a date/time object when used as just `moment()` but then used to create and convert dates when used as `moment( date )` and results can be different depending if date has timezone info or not.

The latest attempt is to create a time zoned moment object called `wpmoment` in `@wordpress/date`. This can be used in all places that `moment()` would've been used, which assumed the default timezone was set. 

This is slightly confusing since functions like `moment( postdate)` are still used to create a moment object from a date. 

I'm still testing this approach, particularly with user and server set in different time zones.

**Comment by mkaz** [comment]
This approach still does not work because the postdate does not have timezone information attached so calling `moment( postdate)` will not create it with the expected timezone if it differs from local timezone. For example database in UTC and user in PST.

File: date/index.js [hunk 3]
```diff
@@ -1,4 +1,22 @@
...
+	name: 'WP',
+	abbrs: [ 'WP' ],
+	untils: [ null ],
+	offsets: [ offsets ],
+};
+moment.tz.add( moment.tz.pack( momentTimezone ) );
+
+// Create a new wpmoment object attaching the timezone and cloning
+// so it does not change the global moment timezone.
+export const wpmoment = moment.tz( 'WP' ).clone();
```
Comment (youknowriad) [inline date/index.js]: Instead of exporting this, maybe we could proxify the calls to moment instead.

```js
import momentLibrary from 'moment';

export const moment = (...args) => {
  return momentLibrary.tz(...args, 'WP');
};
```
not certain it works with all the different ways to instanciate moment though

Comment (mkaz) [reply date/index.js]: Also, I forgot I did attempt something similar but ran into issues because the moment timezone library attaches itself to the moment namespace, so renaming the library on import doesn't work. 

It is why I ended up with wpmoment name, though I think I prefer wpdate.

File: components/date-time/date.js [hunk 4]
```diff
@@ -3,14 +3,15 @@
...
+import { wpmoment } from '@wordpress/date';
 
 /**
  * Module Constants
  */
 const TIMEZONELESS_FORMAT = 'YYYY-MM-DDTHH:mm:ss';
 
 function DatePicker( { currentDate, onChange, ...args } ) {
-	const momentDate = currentDate ? moment( currentDate ) : moment();
+	const momentDate = currentDate ? moment( currentDate ) : wpmoment;
```
Comment (youknowriad) [inline components/date-time/date.js]: Should this be `wpmoment()`?

Also why we're using `moment` sometimes and sometimes `wpmoment`  can we use `wpmoment` consistently.

File: date/index.js [hunk 5]
```diff
@@ -171,37 +192,37 @@ const formatMap = {
 /**
  * Adds a locale to moment, using the format supplied by `wp_localize_script()`.
  *
- * @param {Object} settings Settings, including locale data.
+ * @param {Object} s Settings, including locale data.
  */
-function setupLocale( settings ) {
+function setupLocale( s ) {
```
Comment (youknowriad) [inline date/index.js]: I believe this because of the ESlint rule we have, can't we find a name that's not a single letter? `localeSettings` or something.

**Review by youknowriad — COMMENTED** [review]
Thinking we should update all the instances of `moment`in the code base with `wpmoment` what do you think?

File: components/date-time/date.js (hunk 4 above)
Comment (mkaz) [reply components/date-time/date.js]: I think this was just an oversight, we should be able to use wpmoment everywhere. Also, that probably should be wpmoment() - I'll search and double check them all again and any other instances.

File: date/index.js (hunk 5 above)
Comment (mkaz) [reply date/index.js]: I love single letter variables, <a href="https://github.com/golang/go/wiki/CodeReviewComments#variable-names">blame Golang</a>. I'll switch it out

**Comment by mkaz** [comment]
The only spot that still uses moment() is the `blocks/library/latest-posts/block.js` which specifies the utc() and local() timezones, so we don't need to call them with the WP timezone attached.

**Comment by youknowriad** [comment]
This is looking great, the last thing that bothers me is the `wpmoment` name, it would be great if we could keep the `moment` name and fix the `moment-timezone` issue. I'm not certain how is `moment-timezone` accessing and enhancing `moment`, is it using the global moment variable? I don't understand exactly how this breaks `import momentLib from 'moment'`

File: editor/store/selectors.js [hunk 6]
```diff
@@ -24,6 +23,7 @@ import createSelector from 'rememo';
 import { serialize, getBlockType, getBlockTypes } from '@wordpress/blocks';
 import { __ } from '@wordpress/i18n';
 import { addQueryArgs } from '@wordpress/url';
+import { moment } from '@wordpress/date';
```
Comment (youknowriad) [inline editor/store/selectors.js]: So after digging more, I found that these are the only places where we really need this timezone. After some thoughts, I pushed a small commit keeping the usage of this special moment version in this module only to avoid creating too much dependency to WordPress server side. (For instance using `wpmoment` in the components module means the components module have to be updated to depend on the `date` module).

**Review by youknowriad — APPROVED** [review]
This is looking good for me. Let me know what are your thoughts on the last commit.

**Comment by mkaz** [comment]
> I'm not certain how is moment-timezone accessing and enhancing moment, is it using the global moment variable? 

Yep, from what I can tell it is hard coded to use the global moment name.

Also, this change unfortunately, did not working for me. My test is, with my server set to UTC +0 and my local timezone UTC -7, when going to edit a draft if I set the time an hour ahead, it shows as publish instead of schedule (works for time up to 7 hours due to timezone shift). 

It is comparing what I see as my local time, but the library considers it UTC time due to `wpmoment(date)`

**Comment by youknowriad** [comment]
@mkaz Tried different configs, and it seems to work as intended for me. Let me know how it goes for you.

**Comment by mkaz** [comment]
I'm still seeing timezone mismatch errors. When I go to create a post it shows the time on the right as UTC time and not Pacific. Any comparisons for the time I set are compared against the UTC time, so even if display was wrong setting a local time still compares it to a UTC.

My system, database, and browser are all set to Pacific (UTC -7)
WordPress install is set to UTC +0 in settings screen.

**Comment by mkaz** [comment]
If I change my WordPress install setting to Pacific (UTC -7) then the date displayed creating a Draft Post sidebar shows as expected but the comparison is still incorrect. Setting the time to one hour ahead still shows as "Publish..." and not "Scheduled..."

**Comment by brandonpayton** [comment]
@mkaz, I tested with UTC+0 and UTC-7, and setting an hour ahead of the current time for either results in seeing the "Schedule" button.

I did encounter a time where tabbing away from the hour field, reset it to the current hour. I wonder if that may have happened in your case.

**Comment by narendraie** [comment]
The issue still exists https://core.trac.wordpress.org/ticket/61223
