### PR TITLE
Navigation: add unit tests for onChange handler and fix cases around custom links tags and post-format

### LINKED ISSUE #31254: Navigation Link stores url as id
After adding a custom link, the block id attribute is set to the url value. In this case we'd expect no id attribute to be set for a custom link.

With work in https://github.com/WordPress/gutenberg/pull/31004 we may also want to add the a `kind` value of `custom`

https://user-images.githubusercontent.com/1270189/116308559-7b284a80-a75c-11eb-98fd-0c8b462cba3b.mp4

### PR DESCRIPTION
**Pull request by gwwar**
Fixes https://github.com/WordPress/gutenberg/issues/31254 https://github.com/WordPress/gutenberg/issues/31379

https://user-images.githubusercontent.com/1270189/116925012-802e4380-ac0d-11eb-84d1-58d4b9e8f0d5.mp4

### Changes of interest:

* **Pulls out the LinkControl onChange function** in Navigation Link so we can add **unit test cases**
* **Custom links are now persisted with "kind:custom"** instead of serializing misc link control specific items, like (tel, URL, internal mailto).
* **Consistently save as type:tag**. We were inconsistently saving "type:tag" as a tag variation placeholder and "type:post_tag" when a full tag link was inserted. I'm not sure of the original reasons for favoring "tag" versus the actual "post_tag" name.
* **Toggling opensInNewTab on an existing link no longer wipes out other block attributes**
* **Updates fetchLinkSuggestions to return a type:post-format and kind:taxonomy**

~~Main feedback questions~~:
* ~~Did we intend to persist "internal/tel/URL/mailto" or is it okay to map these to a plain custom type?~~ A: good to map to custom
* ~~Are post-formats and post type archives similar or different use cases?~~ post-format is a `taxonomy` with a name of `post_format`
* ~~If folks prefer, instead of adding a `getNavigationLinkType` helper I can create a function for the LinkControl onChange function. It'd be a little bit of a refactor, but nice for unit testing, as we can isolate the data transform cases.~~ I think it's worth the unit tests at this point, so I'll isolate and refactor this.

### Testing Instructions

Unit Tests:
- Verify that the new test cases make sense. Run them locally with `npm run test-unit packages/block-library/src/navigation-link/test/edit.js`

Custom Links:
- Visit the post or site editor
- Add a navigation block 
- Add a custom link variation
- Type email link like "mailto:foo@example.com", Type a custom url like "wordpress.org", Type a telephone link like: "tel:1234567", Type an internal link like "#foo"
- Save, and check in code view that the type value for the navigation link is "custom"

Tag:
- Visit the post or site editor
- Add a navigation block 
- Add an item, select tag variation
- Do not click on a tag suggestion. Click out then inspect code view.
- Verify that type = tag
- Select a tag suggestion
- Verify that type = tag in code view

Opens In New Tab
- Visit the post or site editor
- Add a navigation block 
- Add a post link
- Click on the link symbol, then toggle opensInNewTab.
- Verify that id is still set in code view

Post Formats
- A post format link looks like http://wordpress.local/type/quote/. This points at the archive of a post type format like quote or image.
- Install a theme that supports post-formats like Twenty Thirteen
- Create a post using one of the post-format types like "Quote"
- Add a navigation block
- Add a navigation link using the general link variation
- Search for the post-format and individual quote
- Verify that the link to the post-format has a type of "post_format" and a kind of "taxonomy"

### CODE REVIEW

File: packages/block-library/src/navigation-link/edit.js [hunk 1]
```diff
@@ -133,6 +133,31 @@ function getSuggestionsQuery( type, kind ) {
...
+	}
+	switch ( type ) {
+		// Different types of custom links should be saved as a "custom" type
+		// this is originally defined in packages/block-editor/src/components/link-control/settings-drawer.js
+		case 'URL':
+		case 'mailto':
+		case 'tel':
+		case 'internal':
+			return { type: 'custom' };
+		case 'post-format': //TODO is this a post_archive?
```
Comment (getdave) [inline packages/block-library/src/navigation-link/edit.js]: I looked into this and and when I save a Post Format menu item in the current menus screen I see this in the DB:
 
Screen Shot 2021-04-30 at 15 51 17

You are going to set the block's `type` atrribute which maps to `object` on the nav_menu_item. Therefore the value should be `post_format`.

If you were setting the `kind` attribute then it would be `taxonomy` (as shown in the screenshot).

File: packages/block-library/src/navigation-link/edit.js [hunk 2]
```diff
@@ -133,6 +133,31 @@ function getSuggestionsQuery( type, kind ) {
...
+		return {};
+	}
+	switch ( type ) {
+		// Different types of custom links should be saved as a "custom" type
+		// this is originally defined in packages/block-editor/src/components/link-control/settings-drawer.js
+		case 'URL':
+		case 'mailto':
+		case 'tel':
+		case 'internal':
+			return { type: 'custom' };
```
Comment (getdave) [inline packages/block-library/src/navigation-link/edit.js]: As the person who wrote the original LinkControl code I can say that this is entirely correct. These are intended to map to `custom` link types. Basically anything that doesn't map to an entity should be `custom`.

File: packages/block-library/src/navigation-link/edit.js [hunk 3]
```diff
@@ -552,15 +577,11 @@ export default function NavigationLinkEdit( {
 											return escape( normalizedURL );
 										} )(),
 										opensInNewTab: newOpensInNewTab,
-										id,
+										...( Number.isInteger( id ) && { id } ),
```
Comment (getdave) [inline packages/block-library/src/navigation-link/edit.js]: We have another bug where sometimes `id` isn't defined at all and we're overriding it. What you have here should also fix this, although I have an alternative implementation in https://github.com/WordPress/gutenberg/pull/31004

File: packages/block-library/src/navigation-link/edit.js [hunk 4]
```diff
@@ -133,6 +133,31 @@ function getSuggestionsQuery( type, kind ) {
 	}
 }
 
+/**
+ * Link control may sometimes return a type which we do not want to persist in block attributes.
+ *
+ * @param {string} type The type returned by the link control suggestion.
+ * @return {{}|{type: string}} empty object or object with type of string
```
Comment (getdave) [inline packages/block-library/src/navigation-link/edit.js]:
```suggestion
 * @return {{}|{type: string}} object with the correctly mapped `type` property to be set on the `block.attribute.type` based. 
```

It feels like we're currently describing what is already documented in the JSDoc `@param` syntax.

I wonder whether we should amend this to be more descriptive of what we are getting back.

File: packages/block-library/src/navigation-link/edit.js [hunk 5]
```diff
@@ -133,6 +133,31 @@ function getSuggestionsQuery( type, kind ) {
 	}
 }
 
+/**
+ * Link control may sometimes return a type which we do not want to persist in block attributes.
```
Comment (getdave) [inline packages/block-library/src/navigation-link/edit.js]:
```suggestion
 * Determines the correct block.attribute.type to which to map the "type" returned by `<LinkControl>` which may sometimes return a type which doesn't have an exact equivalent. Note this `type` attribute will be mapped to [`object` on the nav_menu_item](https://core.trac.wordpress.org/browser/tags/5.7.1/src/wp-includes/nav-menu.php#L796). It is different to `kind`.
```

**Review by getdave — CHANGES_REQUESTED** [review]
This looks like a good improvement and is a good spot. 

Didn't get a chance to take this for a spin, but I did a quick code review and noticed some things.

The key is to be mindful of the mapping because the attributes and nav_menu_item fields are confusingly similar yet different.

`block.attributes.type` = `nav_menu_item.object`.
`block.attributes.kind` = `nav_menu_item.type`.

Also I'm thinking that perhaps there is a lot of this "mapping" code going to land up in the nav block/editor. Once https://github.com/WordPress/gutenberg/pull/31004 has landed we should look to try and standardize it. Perhaps a first step is solid documentation and then perhaps some kind of schema validation?

File: packages/block-library/src/navigation-link/edit.js (hunk 1 above)
Comment (gwwar) [reply packages/block-library/src/navigation-link/edit.js]: Thanks, that does make sense 👍

File: packages/block-library/src/navigation-link/edit.js (hunk 2 above)
Comment (gwwar) [reply packages/block-library/src/navigation-link/edit.js]: Excellent ✨ thanks for verifying!

**Comment by gwwar** [comment]
> The key is to be mindful of the mapping because the attributes and nav_menu_item fields are confusingly similar yet different.

It's not only the block attributes, and menu items, but each search result might also have a different value. 🤔

I'll go ahead and stub out some units for the search suggestion -> blockAttribute in this PR

**Comment by gwwar** [comment]
The unit tests were a good exercise, I found a number of other cases to sort out (for example tags uses 'tag' if inserted as a placeholder, but if a search item is actually set it persists type as 'post_tag'. Putting this back into draft until I cover/fix the rest.

**Comment by gwwar** [comment]
🤔 looks like E2Es have been a bit flakey in trunk

File: packages/block-library/src/navigation-link/edit.js [hunk 6]
```diff
@@ -133,6 +133,53 @@ function getSuggestionsQuery( type, kind ) {
...
+
+	const isCustomLink =
+		( ! newKind && ! isBuiltInType ) || newKind === 'custom';
+	const kind = isCustomLink ? 'custom' : newKind;
+
+	return setAttributes( {
+		url: encodeURI( url ),
+		label,
+		opensInNewTab,
+		...( Number.isInteger( id ) && { id } ),
```
Comment (gwwar) [inline packages/block-library/src/navigation-link/edit.js]: For reviewers, the block mostly uses the id value to check whether or not a post-type instance is a draft or not to control the visibility of the link in the published vew.

I double checked what gets returned for a `post-format` type, from `/wp/v2/search` and it's a string value vs int, so this won't get saved in that case.

Screen Shot 2021-05-03 at 12 56 19 PM

File: packages/block-library/src/navigation-link/edit.js (hunk 3 above)
Comment (gwwar) [reply packages/block-library/src/navigation-link/edit.js]: This one is fixed in this PR, and now backed by unit cases

File: packages/block-library/src/navigation-link/edit.js (hunk 6 above)
Comment (getdave) [reply packages/block-library/src/navigation-link/edit.js]: Yep. I have a dedicated issue open for this.

**Comment by gwwar** [comment]
To make things easier to reason about I also added some guards in https://github.com/WordPress/gutenberg/pull/31259/commits/407b236cb64b9f964995a6f6411776870696a4eb to only setAttributes when new values are provided.

This one is ready for a review 👀

File: packages/block-library/src/navigation-link/edit.js (hunk 6 above)
Comment (gwwar) [reply packages/block-library/src/navigation-link/edit.js]: > Yep. I have a dedicated issue open for this.

Excellent, thanks @getdave

Comment (getdave) [reply packages/block-library/src/navigation-link/edit.js]: Here is the Issue https://github.com/WordPress/gutenberg/issues/31380

File: packages/block-library/src/navigation-link/edit.js [hunk 7]
```diff
@@ -133,6 +133,82 @@ function getSuggestionsQuery( type, kind ) {
 	}
 }
 
+/**
+ * @typedef {'post-type'|'custom'|'taxonomy'} WPNavigationLinkKind
```
Comment (getdave) [inline packages/block-library/src/navigation-link/edit.js]: FYI that for nav_menu_item [`type` can also be `post-type-archive`](https://core.trac.wordpress.org/browser/tags/5.7.1/src/wp-includes/nav-menu.php#L862). As `block.attributes.kind` maps to `menuItem.type` we should probably include that here.

File: packages/block-library/src/navigation-link/edit.js [hunk 8]
```diff
@@ -133,6 +133,82 @@ function getSuggestionsQuery( type, kind ) {
...
+ * @property {string}                [rel]            The relationship of the linked URL.
+ * @property {number}                [id]             A post or term id.
+ * @property {boolean}               [opensInNewTab]  Sets link target to _blank when true.
+ * @property {string}                [url]            Link href.
+ * @property {string}                [title]          Link title attribute.
+ */
+
+/**
+ * OnChange handler that updates block attributes when a link suggestion is chosen, a url is updated, or
+ * opensInNewTab is toggled
```
Comment (getdave) [inline packages/block-library/src/navigation-link/edit.js]: > or opensInNewTab is toggled

Should we simply say "when a setting is changed (eg: opensInNewTab)?

File: packages/block-library/src/navigation-link/edit.js [hunk 9]
```diff
@@ -133,6 +133,82 @@ function getSuggestionsQuery( type, kind ) {
...
+	const {
+		title = '',
+		url = '',
+		opensInNewTab,
+		id,
+		kind: newKind = originalKind,
+		type: newType = originalType,
+	} = updatedValue;
+
+	const normalizedTitle = title.replace( /http(s?):\/\//gi, '' );
```
Comment (getdave) [inline packages/block-library/src/navigation-link/edit.js:182]: I wish I didn't have to read the regex to understand what this is doing. A question for me was why are we removing the link protocol from a `title`? We could comment here to explain that (as I understand it) sometimes the `title` is actually the URL and so for visual presentation purposes we are stripping the protocol.

File: packages/block-library/src/navigation-link/edit.js [hunk 10]
```diff
@@ -133,6 +133,82 @@ function getSuggestionsQuery( type, kind ) {
...
+	const normalizedURL = url.replace( /http(s?):\/\//gi, '' );
```
Comment (getdave) [inline packages/block-library/src/navigation-link/edit.js:183]: `normalizedURL` and `normalizedTitle` could both be the result of passing `url` / `title` into a function called `removeURLProtocol` which would self document the `.replace()`. Just a thought...

File: packages/block-library/src/navigation-link/edit.js [hunk 11]
```diff
@@ -133,6 +133,82 @@ function getSuggestionsQuery( type, kind ) {
...
+	const escapeTitle =
+		title !== '' &&
+		normalizedTitle !== normalizedURL &&
+		originalLabel !== title;
+	const label = escapeTitle
+		? escape( title )
+		: originalLabel || escape( normalizedURL );
+
+	const type = newType === 'post_tag' ? 'tag' : newType.replace( '-', '_' );
```
Comment (getdave) [inline packages/block-library/src/navigation-link/edit.js:193]: I feel we really need document what is happening here with `tag` and `post_tag`. It's happening all over the codebase now and it's a source of potential confusion.

Would an inline code comment here help?

I will look into writing a README around these things.

Comment (getdave) [reply packages/block-library/src/navigation-link/edit.js:193]: Also let's document why we are swapping `-` with `_` with [references to trac](https://core.trac.wordpress.org/browser/tags/5.7.1/src/wp-includes/nav-menu.php#L862)...etc.

File: packages/block-library/src/navigation-link/edit.js [hunk 12]
```diff
@@ -133,6 +133,82 @@ function getSuggestionsQuery( type, kind ) {
...
+
+	const isBuiltInType =
```
Comment (getdave) [inline packages/block-library/src/navigation-link/edit.js:195]: 👍 Nicely self documenting!

File: packages/block-library/src/navigation-link/edit.js [hunk 13]
```diff
@@ -133,6 +133,82 @@ function getSuggestionsQuery( type, kind ) {
...
+		[ 'post', 'page', 'tag', 'category' ].indexOf( type ) > -1;
+
+	const isCustomLink =
+		( ! newKind && ! isBuiltInType ) || newKind === 'custom';
+	const kind = isCustomLink ? 'custom' : newKind;
+
+	setAttributes( {
+		...( url && { url: encodeURI( url ) } ),
+		...( label && { label } ),
+		...( undefined !== opensInNewTab && { opensInNewTab } ),
```
Comment (getdave) [inline packages/block-library/src/navigation-link/edit.js:205]: Nice explicit check here for `undefined`. 

Nit: I wonder whether we might like to include a comment here to illustrate that as `opensInNewTab` can be `false` and that is a valid value then we have to have an explicit check for `undefined`?

File: packages/block-library/src/navigation-link/test/edit.js [hunk 14]
```diff
@@ -0,0 +1,506 @@
+/**
+ * Internal dependencies
+ */
+import { updateNavigationLinkBlockAttributes } from '../edit';
+
+describe( 'edit', () => {
+	describe( 'updateNavigationLinkBlockAttributes', () => {
+		// data shapes are linked to fetchLinkSuggestions from
```
Comment (getdave) [inline packages/block-library/src/navigation-link/test/edit.js:8]: We need to document these data shapes with typedefs. Can we import typedefs from another package to use in another package?

PS: when can we have TypeScript support! 🙏

File: packages/block-library/src/navigation-link/test/edit.js [hunk 15]
```diff
@@ -0,0 +1,506 @@
...
+			} );
+		} );
+
+		it( 'can update a custom category link', () => {
+			const setAttributes = jest.fn();
+			const linkSuggestion = {
+				id: 2,
+				kind: 'taxonomy',
+				opensInNewTab: false,
+				title: 'Portfolioz Category',
```
Comment (getdave) [inline packages/block-library/src/navigation-link/test/edit.js]:
```suggestion
				title: 'Portfolios Category',
```

File: packages/block-library/src/navigation-link/test/edit.js [hunk 16]
```diff
@@ -0,0 +1,506 @@
...
+			} );
+		} );
+
+		it( 'can update a custom tag link', () => {
+			const setAttributes = jest.fn();
+			const linkSuggestion = {
+				id: 4,
+				kind: 'taxonomy',
+				opensInNewTab: false,
+				title: 'PortfolioTag',
```
Comment (getdave) [inline packages/block-library/src/navigation-link/test/edit.js]:
```suggestion
				title: 'Portfolio Tag',
```

File: packages/block-library/src/navigation-link/test/edit.js [hunk 17]
```diff
@@ -0,0 +1,506 @@
...
+			};
+			updateNavigationLinkBlockAttributes(
+				linkSuggestion,
+				setAttributes
+			);
+			expect( setAttributes ).toHaveBeenCalledWith( {
+				id: 4,
+				kind: 'taxonomy',
+				opensInNewTab: false,
+				label: 'PortfolioTag',
```
Comment (getdave) [inline packages/block-library/src/navigation-link/test/edit.js]:
```suggestion
				label: 'Portfolio Tag',
```

File: packages/block-library/src/navigation-link/test/edit.js [hunk 18]
```diff
@@ -0,0 +1,506 @@
...
+			};
+			updateNavigationLinkBlockAttributes(
+				linkSuggestion,
+				setAttributes
+			);
+			expect( setAttributes ).toHaveBeenCalledWith( {
+				id: 2,
+				kind: 'taxonomy',
+				opensInNewTab: false,
+				label: 'Portfolioz Category',
```
Comment (getdave) [inline packages/block-library/src/navigation-link/test/edit.js]:
```suggestion
				label: 'Portfolios Category',
```

File: packages/block-library/src/navigation-link/test/edit.js [hunk 19]
```diff
@@ -0,0 +1,506 @@
...
+				linkSuggestion,
+				setAttributes
+			);
+			expect( setAttributes ).toHaveBeenCalledWith( {
+				kind: 'taxonomy',
+				opensInNewTab: false,
+				label: 'Video',
+				type: 'post_format',
+				url: 'http://wordpress.local/type/video/',
+			} );
```
Comment (getdave) [inline packages/block-library/src/navigation-link/test/edit.js:203]: I wonder whether we should have an explicit assertion around `id` _not_ being set when the linkSuggestion `id` is not an int (as in this case).

File: packages/block-library/src/navigation-link/test/edit.js [hunk 20]
```diff
@@ -0,0 +1,506 @@
...
+				opensInNewTab: false,
+				title: 'Video',
+				type: 'post-format',
+				url: 'http://wordpress.local/type/video/',
+			};
+			updateNavigationLinkBlockAttributes(
+				linkSuggestion,
+				setAttributes
+			);
+			expect( setAttributes ).toHaveBeenCalledWith( {
```
Comment (getdave) [inline packages/block-library/src/navigation-link/test/edit.js:197]: We should probably document in these tests that we expect `id` to be missing for `post-formats` and reference the issue with the Post Formats API endpoint returning strings and not term ids. Otherwise as someone without that context I'd be puzzling over why post format is an exception.

File: packages/block-library/src/navigation-link/test/edit.js [hunk 21]
```diff
@@ -0,0 +1,506 @@
...
+					url: 'http://www.wordpress.org',
+				};
+				updateNavigationLinkBlockAttributes(
+					linkSuggestion,
+					setAttributes
+				);
+				expect( setAttributes ).toHaveBeenCalledWith( {
+					opensInNewTab: false,
+					label: 'www.wordpress.org',
+					kind: 'custom',
```
Comment (getdave) [inline packages/block-library/src/navigation-link/test/edit.js:241]: I've just thought, by stripping out the data about whether this is a `tel`, `URL`, `#anchor`...etc are we going to cause problems if we ever want to render the "type" in the `LinkPreview` so the user knows this is a `telephone` link...etc?

We currently visually distinguish `tel`, `hash`...etc from each other in the search suggestions and we are going to lose this data as soon as the suggestion is selected.

Is there anywhere else we could store it?

I know I said it was ok to transform them to `custom` but thinking about it we might need to discuss options for being more nuanced. Apologies!

File: packages/block-library/src/navigation-link/test/edit.js [hunk 22]
```diff
@@ -0,0 +1,506 @@
...
+					label: 'tel:5555555',
+					kind: 'custom',
+					url: 'tel:5555555',
+				} );
+			} );
+		} );
+
+		describe( 'link label', () => {
+			// https://github.com/WordPress/gutenberg/pull/19461
+			it( 'sets the url as a label if title is not provided', () => {
```
Comment (getdave) [inline packages/block-library/src/navigation-link/test/edit.js:315]:
```suggestion
			it( 'sets the protocol-less version of the url as a label if title is not provided', () => {
```

File: packages/block-library/src/navigation-link/test/edit.js [hunk 23]
```diff
@@ -0,0 +1,506 @@
...
+				);
+				expect( setAttributes ).toHaveBeenCalledWith( {
+					opensInNewTab: false,
+					label: 'Custom Title',
+					kind: 'custom',
+					url: 'https://wordpress.org',
+				} );
+			} );
+			// https://github.com/WordPress/gutenberg/pull/18617
+			it( 'label is javascript escaped', () => {
```
Comment (getdave) [inline packages/block-library/src/navigation-link/test/edit.js:376]: 👍👍👍👍👍

👏 👏 👏 👏 👏

File: packages/block-library/src/navigation-link/test/edit.js [hunk 24]
```diff
@@ -0,0 +1,506 @@
...
+					opensInNewTab: false,
+					label: 'Custom Title',
+					kind: 'custom',
+					url: 'http://wordpress.org/?s=%3C%3E',
+				} );
+			} );
+		} );
+
+		describe( 'does not overwrite props when only some props are passed', () => {
+			it( 'id is retained after toggling opensInNewTab', () => {
```
Comment (getdave) [inline packages/block-library/src/navigation-link/test/edit.js:419]: Super important 🏅

File: packages/block-library/src/navigation-link/test/edit.js (hunk 21 above)
Comment (getdave) [reply packages/block-library/src/navigation-link/test/edit.js:241]: I wonder if the `type` attribute could store this info? Should be safe as the nav_menu_item ignores `type` if `kind` is `custom`.

**Review by getdave — APPROVED** [review]
I tested all scenarios and they worked as described. Also the unit tests add a good level of coverage to this which is really really great. Thank you for all the work 🥇 

I have approved this on it's current basis. However there are a few questions I raised so feel free to move those to a follow up or resolve them prior to merging. Happy to re-review as required.


### Custom Links:

✅ Works as described

Screen Shot 2021-05-05 at 12 46 05

### Tag

✅ Works as described

Screen Shot 2021-05-05 at 12 47 25
Screen Shot 2021-05-05 at 12 47 49

### Post Formats

✅ Works as described


Screen Shot 2021-05-05 at 12 51 07

File: packages/block-library/src/navigation-link/edit.js (hunk 11 above)
Comment (gwwar) [reply packages/block-library/src/navigation-link/edit.js:193]: There's inconsistent usage of kebab case with the search rest API vs other server code, I'm not sure why hardcoded variations decided to pick "tag" over "post_tag", but possibly it was because the first pass may have tried to use it as a label display? https://github.com/WordPress/gutenberg/pull/24670/files#diff-7e333e3cb4e3e25a9d7349bcb6144c5af837ff2284bd98ceec2a616e40dd6213R66

One thing we could do is favor the actual entity name "post_tag", but also support the custom alias "tag" since persisted data is now mixed, depending on which WP version folks are using and if people left a tag link placeholder or not.

File: packages/block-library/src/navigation-link/edit.js (hunk 9 above)
Comment (gwwar) [reply packages/block-library/src/navigation-link/edit.js:182]: > A question for me was why are we removing the link protocol from a title?

Protocol stripping here is to determine whether or not we should use the url as a label. 

https://github.com/WordPress/gutenberg/pull/19461#discussion_r366627977

File: packages/block-library/src/navigation-link/test/edit.js (hunk 21 above)
Comment (gwwar) [reply packages/block-library/src/navigation-link/test/edit.js:241]: It doesn't hurt to persist extra data here. I tried this in 5d19a86 for everything but "URL" since that felt redundant, and link control would inconsistently set this.

One downside is that it ties together LinkControl typing that doesn't necessarily match our menu data models, but with the extra information here, we can choose to transform it later.

File: packages/block-library/src/navigation-link/edit.js (hunk 11 above)
Comment (gwwar) [reply packages/block-library/src/navigation-link/edit.js:193]: I left a short comment in https://github.com/WordPress/gutenberg/pull/31259/commits/c6a8a5984af5ec1f26af1fe61b9d7ebd698eacb3

I do think we can revisit the choice later.

File: packages/block-library/src/navigation-link/edit.js (hunk 8 above)
Comment (gwwar) [reply packages/block-library/src/navigation-link/edit.js]: Updated in https://github.com/WordPress/gutenberg/pull/31259/commits/c6a8a5984af5ec1f26af1fe61b9d7ebd698eacb3

File: packages/block-library/src/navigation-link/edit.js (hunk 7 above)
Comment (gwwar) [reply packages/block-library/src/navigation-link/edit.js]: Good catch updated in https://github.com/WordPress/gutenberg/pull/31259/commits/c6a8a5984af5ec1f26af1fe61b9d7ebd698eacb3

File: packages/block-library/src/navigation-link/edit.js (hunk 10 above)
Comment (gwwar) [reply packages/block-library/src/navigation-link/edit.js:183]: I think this would be good in a follow up PR. I was trying to retain most of the original logic here while pulling out the function.

File: packages/block-library/src/navigation-link/test/edit.js (hunk 20 above)
Comment (gwwar) [reply packages/block-library/src/navigation-link/test/edit.js:197]: Good idea, I added some context in https://github.com/WordPress/gutenberg/pull/31259/commits/3d94e8115e442d51783e781b6a4b48cdbc666edd

File: packages/block-library/src/navigation-link/edit.js (hunk 13 above)
Comment (gwwar) [reply packages/block-library/src/navigation-link/edit.js:205]: I think we should be okay here, I verified that unit tests will break if the undefined check is removed.

**Comment by gwwar** [comment]
Thanks for the review @getdave!
