### PR TITLE
Site Editor - prevent loading state from showing the admin menu.

### LINKED ISSUE #36445: (Site) "Editor (beta)" loads with wp-admin navigation in the background.
There is a recent regression in the 11.9.0 releases that has caused the site editor to load with the wp-admin nav bar in the background instead of the blank editor canvas.

Current behavior with the regression:

site-editor-wp-admin-background-loading

Notice that when the editor starts loading, the wp-admin nav bar remains on the left while the rest of the screen turns white.  This remains in place until all editor content is loaded and dropped into place at once.

This may be related to https://github.com/WordPress/gutenberg/pull/36044 (cc @youknowriad ) as doing a local revert seems to resolve the issue and the behavior goes back to its previous and expected state:

site-editor-proper-loading

Notice how the blank editor canvas is shown while the editor content finishes loading, instead of awkward wp-admin nav menu with blank white screen.

This regression seems especially concerning in environments with longer load times.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

Resolves https://github.com/WordPress/gutenberg/issues/36445 by ensuring the site editor is in fullscreen mode while loading.

## How has this been tested?

Load the site editor and verify you do not see the wp-admin menu while it loads, as is described in the linked issue.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: lib/full-site-editing/edit-site-page.php [hunk 1]
```diff
@@ -31,6 +31,15 @@ function gutenberg_is_edit_site_page( $page ) {
 	return 'appearance_page_gutenberg-edit-site' === $page;
 }
 
+// Default to is-fullscreen-mode to avoid rendering wp-admin navigation menu while loading and
+// having jumps in the UI.
+add_filter(
```
Comment (youknowriad) [inline lib/full-site-editing/edit-site-page.php]: This is going to be executed for all pages, not just the site editor (because the php file is always loaded), should we instead move this into `gutenberg_edit_site_init` ?

Comment (Addison-Stavlo) [reply lib/full-site-editing/edit-site-page.php]: Ohh, that makes sense.  I moved it into that function here c434238

Comment (Addison-Stavlo) [reply lib/full-site-editing/edit-site-page.php]: Do we need to also remove the filter as part of the `! gutenberg_is_edit_site_page( $hook )` conditional return?

Comment (Addison-Stavlo) [reply lib/full-site-editing/edit-site-page.php]: Also curious, does the function need to be `static` here?  I didn't think so, but then I noticed your example in wordpress-develop was also static but didn't seem to be part of a class?

Comment (youknowriad) [reply lib/full-site-editing/edit-site-page.php]: they started using "static" for closures like that recently something about PHP 8 support, but I didn't fully follow the explanations tbh :) So I might think it's better if it's static here as well.

It doesn't seem like we need to remove the filter though as it's only applied if we're on this page so, so it looks good to me.

**Review by youknowriad — APPROVED** [review]

File: lib/full-site-editing/edit-site-page.php [hunk 2]
```diff
@@ -81,6 +81,15 @@ function gutenberg_edit_site_init( $hook ) {
 		return;
 	}
 
+	// Default to is-fullscreen-mode to avoid rendering wp-admin navigation menu while loading and
+	// having jumps in the UI.
+	add_filter(
+		'admin_body_class',
+		function( $classes ) {
```
Comment (Addison-Stavlo) [inline lib/full-site-editing/edit-site-page.php]:
```suggestion
		static function( $classes ) {
```

**Review by Mamaduka — APPROVED** [review]
Changes look good. Thanks, @Addison-Stavlo.

**Comment by Addison-Stavlo** [comment]
Would we be able to get this into a point release for 11.9 if one ends up happening?  cc @noisysocks

**Comment by andrewserong** [comment]
@Addison-Stavlo I'm not sure if there are plans for a point release, but I've cherry picked this PR into the [`release/11.9`](https://github.com/WordPress/gutenberg/commits/release/11.9) branch in https://github.com/WordPress/gutenberg/commit/6229382be28d30e5939d33c3155e377037f36595, so if anyone does do a point release, it'll be included.

**Comment by Addison-Stavlo** [comment]
Thanks @andrewserong !
