### PR TITLE
Prevent prependHttp from failing if url is not defined

### LINKED ISSUE #17657: Block disapear when clicking on a link (anchor, <a>) with no href
**Describe the bug**
In Gutenberg 6.5.
Shows this error in the console :
react-dom.min.b694e242.js:103 TypeError: Cannot read property 'trim' of undefined

**To reproduce**
1. Copy text from a source where there is a <a> tag with no href
or
create a link with no href when editing a block in HTML mode
2. In visual mode, click on the link or drag over it (like when you want to select text containing a anchor with no href). 
3. Oups, block is gone!

**Expected behavior**
The pop-up to enter the adress should show up empty

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 77

Thank you!

### PR DESCRIPTION
**Pull request by glendaviesnz**
## Description

The url package methods don't defend against undefined values being passed in, so this PR adds a check at the caller end in the inline link component which fixes #17657.

It might be better to defend against this at the prependHttp end, but maybe it is a deliberate decision that all the methods in this package leave checking to the caller. Also, changing the prependHttp method would require updating the related index.d.ts to allow undefined or false as an optional return type - but happy to look at doing that if it is a preferred approach

## How has this been tested?

- Copy text from a source where there is a tag with no href or create a link with no href when editing a block in HTML mode
- In visual mode, click on the link or drag over it (like when you want to select text containing a anchor with no href).
- You should see a broken block error
- Apply this patch and repeat the above steps
 - Block should not break this time

## Screenshots 

Before:

before

After: 

after

## Types of changes
Adds a simple check to see if value defined before passing in to  prependHttp

## Checklist:
- [ X ] My code is tested - juts manually, couldn't see an easy/obvious way to unit test this.
- [ X ] My code follows the WordPress code style. 
- [  NA ] My code follows the accessibility standards. 
- [  NA ] My code has proper inline documentation. 
- [ NA ] I've included developer documentation if appropriate.

### CODE REVIEW

**Review by senadir — DISMISSED** [review]
I tested this and it works great,some notes:

it might to add a placeholder or something when no value is set since it's confusing like this.
image
something like this:
image

the url will receive `has-invalid-link` class even if there is no link, we might want to not add that and simply add a new class `is-empty-link`

```js
<URLPopover.LinkViewer
	linkClassName={ classnames(
		{ 'has-invalid-link': url && ! isValidHref( prependHTTP( url ) ) },
		{ 'is-empty-link': ! url }
	) }
/>
```

File: packages/format-library/src/link/inline.js [hunk 1]
```diff
@@ -227,7 +227,7 @@ class InlineLinkUI extends Component {
 						onKeyPress={ stopKeyPropagation }
 						url={ url }
 						onEditLinkClick={ this.editLink }
-						linkClassName={ isValidHref( prependHTTP( url ) ) ? undefined : 'has-invalid-link' }
```
Comment (gziolo) [inline packages/format-library/src/link/inline.js]: I think we should fix `prependHTTP` instead. 

```js
* @param {string} url The URL to test.
```

In its definition, it's expected to pass `string` so it should return the original value otherwise. It'd be similar to what `addQueryArgs` does.

Comment (glendaviesnz) [reply packages/format-library/src/link/inline.js]: Would you prefer the fix to prependHTTP as a separate PR to the UI enhancements that @senadir has suggested?

Comment (gziolo) [reply packages/format-library/src/link/inline.js]: UI enhancement can be filed as a separate issue. We should fix the bug in the first place to make it usable :)

Comment (gziolo) [reply packages/format-library/src/link/inline.js]: I tested it with the Class block and it looks like the way it's handled there is, it gets never converted into a link if you leave the input field empty.

Comment (glendaviesnz) [reply packages/format-library/src/link/inline.js]: I have updated the PR to just return the original value in prependHTTP instead. This fixes the bug - not sure if we want to do a proper check for a string value rather than a simple truthy check. 

With removing the link if url is not set, this is slightly complicated by the fact that we need to account for existing named anchor tags that will have no url attribute. The Classic block does account for these, and it has a different UI treatment for anchors. Do we want to combine looking at this in a separate PR along with the UI enhancements mentioned above?

Comment (talldan) [reply packages/format-library/src/link/inline.js]: My feeling is that it's probably best to get this fix in as is, and then look to do other improvements separately. The current fix improves things quite a bit, and leaves only a couple of rough edges (which is way better than a crashing block).

Bearing in mind there's some work (https://github.com/WordPress/gutenberg/pull/17846) to revamp the link interface going on separately, it might be best to create a separate issue and seek some design feedback on how to handle this use case. It can then be factored in to the new design.

What do think @gziolo?

**Review by gziolo — APPROVED** [review]
There is a failing e2e test for the font size picker. It's unrelated to this PR and I see it in other open PRs as well.

Thanks for the bug fix. Let's file a separate issue for UI improvements as discussed.

**Comment by gziolo** [comment]
@youknowriad – if we do another patch release for 5.3 - this bug fix could be included.

File: packages/format-library/src/link/inline.js (hunk 1 above)
Comment (gziolo) [reply packages/format-library/src/link/inline.js]: Filed a follow-up: https://github.com/WordPress/gutenberg/issues/17972
