### PR TITLE
Validated form controls: Suppress native popover

### LINKED ISSUE #73015: Components: Validated form components should cancel browser invalid handling
## What problem does this address?

Validated form components use [browser-native form validation](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#constraints) behavior to control and intercept form validation to show visible error messages.

However, they don't currently work very well when external application logic programatically invokes validation, such as through [`HTMLFormElement#reportValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reportValidity). Use-cases include external revisions to a form field's value such as asynchronous validation or mirrored input values.

**Steps to reproduce:**

1. Go to https://wordpress.github.io/gutenberg/?path=/docs/components-validatedtextcontrol--docs
2. Enter "error" into the field
3. Right-click the field and "Inspect element" to inspect the input in your browser DevTools
4. In your DevTools console, enter `$0.reportValidity()`

The above steps result in both the custom visual error label and the browser-native error popup appearing:

Image

## What is your proposed solution?

It may be as simple as calling `event.preventDefault()` on [the handled '`invalid'` event](https://github.com/WordPress/gutenberg/blob/03e3101bd7e1a06067c5275ad5a4cf3873603c54/packages/components/src/validated-form-controls/control-with-error.tsx#L109-L112).

Via [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reportValidity) (emphasis mine):

>The reportValidity() method of the [HTMLFormElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement) interface performs the same validity checking steps as the [checkValidity()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/checkValidity) method. In addition, for each [invalid](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/invalid_event) event that was fired **and not canceled**, the browser displays the problem to the user.

cc @WordPress/gutenberg-components

### PR DESCRIPTION
**Pull request by mirka**
## What?

Closes #73015

Try suppressing the native error popover that appears when a form is validated, while keeping the focus behavior as is.

## Why?

The popover can obscure our custom error messages, and are redundant.

## How?

`preventDefault()` on `invalid` events on the validity target, and then add back the focus logic.

The concern here is whether we're overlooking any other "default behavior" that would be bad to prevent.

One that I noticed so far is, at least in VoiceOver on Chrome and Safari, hitting the submit button on an invalid form _plays a special sound effect_ in addition to announcing the first error again. This behavior is lost by doing `preventDefault()`. We can mimic the announcement programmatically, but not the sound effect.

## Testing Instructions

Try the Validated Form Control stories in the three major browsers.

### Before

https://github.com/user-attachments/assets/529119c9-2e37-45b5-a5e5-9ade4ee17c96

### After

https://github.com/user-attachments/assets/f178c8bb-c8a7-4fe2-b0cb-d1ad11c18440

### CODE REVIEW

File: packages/components/src/validated-form-controls/control-with-error.tsx [hunk 1]
```diff
@@ -101,17 +101,65 @@ function UnforwardedControlWithError< C extends React.ReactElement >(
...
+			);
+
+			if ( firstErrorInForm === target ) {
+				target.focus();
+			}
+		};
+
+		// Radio inputs need special handling because all radio inputs with the
+		// same `name` will be marked as invalid.
+		const radioSibilings =
```
Comment (mirka) [inline packages/components/src/validated-form-controls/control-with-error.tsx:134]: One of the topics discussed in the original issue was whether this would be "worth the extra trouble".

So far, from the set of use cases that we currently have, radio inputs were the only thing that needed special handling like this. There may be more, and I have some qualms about the screen reader behavior, but perhaps not too bad to count as hard blockers.

**Comment by mirka** [comment]
Not sure if we'll merge, but I'll open this up to feedback.

**Comment by jasmussen** [comment]
At a very high level glance at just the before and after, purely conceptually the path forward is clear: it should be one or the other, not both.

**Comment by mirka** [comment]
I think we're all aligned that suppressing the native popovers is better for general UX. Since this is trivial to revert if it causes complications down the line, I would be comfortable trying it out to see how it goes.

I've rebased this with the latest validation logic, so the PR is ready for review (with the assumption that it will actually be merged) 🙂

File: packages/components/src/validated-form-controls/test/control-with-error.tsx [hunk 2]
```diff
@@ -282,4 +282,57 @@ describe( 'ControlWithError', () => {
...
+					<button type="submit">Submit</button>
+				</form>
+			);
+
+			await user.click(
+				screen.getByRole( 'button', { name: 'Submit' } )
+			);
+
+			expect(
+				screen.getByRole( 'textbox', { name: /^Text1/ } )
```
Comment (aduth) [inline packages/components/src/validated-form-controls/test/control-with-error.tsx:302]: Nit: Should we expect that the name would be _exactly_ `Text1` ?

```suggestion
				screen.getByRole( 'textbox', { name: 'Text1' } )
```

File: packages/components/src/validated-form-controls/control-with-error.tsx [hunk 3]
```diff
@@ -109,6 +111,58 @@ function UnforwardedControlWithError< C extends React.ReactElement >(
 		return () => validityTarget?.removeEventListener( 'invalid', handler );
 	}, [ getValidityTarget ] );
 
+	// Suppress the native error popover, while keeping the focus behavior intact.
+	useEffect( () => {
+		const validityTarget = getValidityTarget();
+
+		const supressNativePopover = ( event: Event ) => {
```
Comment (aduth) [inline packages/components/src/validated-form-controls/control-with-error.tsx]: Nit: Typo


```suggestion
		const suppressNativePopover = ( event: Event ) => {
```

File: packages/components/src/validated-form-controls/control-with-error.tsx [hunk 4]
```diff
@@ -109,6 +111,58 @@ function UnforwardedControlWithError< C extends React.ReactElement >(
...
+				return;
+			}
+
+			const firstErrorInForm = Array.from( target.form.elements ).find(
+				( el ) => ! ( el as ValidityTarget ).validity.valid
+			);
+
+			if ( firstErrorInForm === target ) {
+				target.focus();
+			}
```
Comment (aduth) [inline packages/components/src/validated-form-controls/control-with-error.tsx]: Could we use `:invalid` query selector to simplify this?


```suggestion
			if ( ! target.form || target.form.querySelector( ':invalid' ) === target ) {
				target.focus();
			}
```

File: packages/components/src/validated-form-controls/control-with-error.tsx (hunk 1 above)
Comment (aduth) [reply packages/components/src/validated-form-controls/control-with-error.tsx:134]: I'm having a hard time understanding what happens if we just... didn't have this code for radio inputs.

File: packages/components/src/validated-form-controls/control-with-error.tsx (hunk 3 above)
Comment (mirka) [reply packages/components/src/validated-form-controls/control-with-error.tsx]: 297b474

File: packages/components/src/validated-form-controls/test/control-with-error.tsx (hunk 2 above)
Comment (mirka) [reply packages/components/src/validated-form-controls/test/control-with-error.tsx:302]: This is just side-stepping the detail that the `required` prop adds a `(Required)` suffix to the labels. Kind of wanted to exclude that detail from these tests.

File: packages/components/src/validated-form-controls/control-with-error.tsx (hunk 4 above)
Comment (mirka) [reply packages/components/src/validated-form-controls/control-with-error.tsx]: Ugh, this is a great idea I didn't think of, but unfortunately this `querySelector( ':invalid' )` seems to trigger a recursive validation check in jsdom and makes every test hang 😭 I reshuffled the original code to make it a bit simpler though (41d019f).

File: packages/components/src/validated-form-controls/control-with-error.tsx (hunk 1 above)
Comment (mirka) [reply packages/components/src/validated-form-controls/control-with-error.tsx:134]: My bad. Here's what happens when you click the submit button on an untouched radio group. The "Before" version has the radio handling in this hook commented out.

| Before | After |
|--------|-------|
|Radio group, before|Radio group, after|


I expanded on the code comment a bit (793ace03a6d7625649297f5880fa3045870f389d). Ideally we have a unit test, but unfortunately this is not accurately testable in jsdom.

Comment (aduth) [reply packages/components/src/validated-form-controls/control-with-error.tsx:134]: Gotcha 👍 

Thinking out loud a bit: Rather than dealing with `getValidityTarget` as assuming there's some "one element" to be validated (which your comment seems to suggest is not actually the case), could we bind to the wrapper and watch for the event in capture phase?

Something like...

```tsx
wrapperRef.current?.addEventListener( 'invalid', suppressNativePopover, true );
```

Or maybe it should be `getValidityTargets`, which is usually an array of one, but could be multiple?

Definitely not a blocker.

**Review by aduth — APPROVED** [review]

File: packages/components/src/validated-form-controls/control-with-error.tsx (hunk 1 above)
Comment (mirka) [reply packages/components/src/validated-form-controls/control-with-error.tsx:134]: At the moment I'm not considering supporting multiple validity targets for a control, because there's only one slot to show an error message.

But listening to _all_ invalid events within a control wrapper might work… 🤔 That might be preferable if we encounter additional cases that need a similar workaround.

**Comment by joedolson** [comment]
I'm trying to assess this as I review accessibility related changes in 7.0, but I'm not sure where I can test this within core. Can you point me to some examples of inputs in core using this validation? I'm aware of the stories, but I want to be testing this in a use case.

**Comment by mirka** [comment]
@joedolson Thanks for looking at this. I believe the only use case in 7.0 is the `LinkControl` when you try to submit an invalid URL:

https://github.com/user-attachments/assets/7b165eb1-d8c5-427d-bf3a-81cf5907ec5a

**Comment by joedolson** [comment]
And it seems like there was no validation on that in 6.9, so it's actually a completely new addition, from the user perspective. Checking on it!

**Comment by joedolson** [comment]
No problems with suppressing the native error, but there is an issue with the error message - it's not explicitly connected to the input field; I'm going to open a new issue.
