### PR TITLE
Font Library: install fonts in sequence to work around race condition

### LINKED ISSUE #59023: Font Library: first time install fails if fonts upload directory isn't created.
## Reproduction Report
First attempt i got this error but second attempt installed successfully.

trac ticket: https://core.trac.wordpress.org/ticket/60528

### Environment
- WordPress: 6.5-beta1-57631
- PHP: 8.3.2
- Server: nginx/1.25.3
- Database: mysqli (Server: 11.2.2-MariaDB / Client: mysqlnd 8.3.2)
- Browser: Chrome 121.0.0.0
- OS: macOS
- Theme: Twenty Twenty-Four 1.0
- MU Plugins: None activated
- Plugins:
  * Test Reports 
  
Screenshot 2024-02-14 at 12 46 32 PM

_Originally posted by @huzaifaalmesbah in https://github.com/WordPress/gutenberg/issues/58997#issuecomment-1943178496_

### PR DESCRIPTION
**Pull request by creativecoder**
## What?

Install new font faces sequentially, rather than in parallel, to prevent a race condition where font installation errors because two requests try to create the font directory at the same time.

Closes https://github.com/WordPress/gutenberg/issues/59023

## Why?

Prevents font installation from partially erroring when the fonts directory doesn't exist yet (such as on new installs of WordPress or those updating to WP 6.5).

## How?

Run the font-face creation requests in sequence using a for loop rather than `Promise.allSettled`.

## Testing Instructions

- Delete the fonts directory, if it already exists.
- Install multiple fonts
- See that they install successfully

Note that the race condition error can be difficult to replicate. There are specific instructions for that here: https://github.com/WordPress/gutenberg/issues/59023#issuecomment-2018324697

### CODE REVIEW

**Review by mcsf — APPROVED** [review]
LGTM, but let's get some additional testing, and I want @matiasbenedetto's opinion too.

**Comment by huzaifaalmesbah** [comment]
Great! This seems to have resolved the issue with the PR.

Huzaifa-20240326011032
Huzaifa-20240326011050

File: packages/edit-site/src/components/global-styles/font-library-modal/utils/index.js [hunk 1]
```diff
@@ -234,10 +234,21 @@ export function makeFontFacesFormData( font ) {
...
 
 export async function batchInstallFontFaces( fontFamilyId, fontFacesData ) {
-	const promises = fontFacesData.map( ( faceData ) =>
-		fetchInstallFontFace( fontFamilyId, faceData )
-	);
-	const responses = await Promise.allSettled( promises );
+	const responses = [];
+
+	// Uses the same response format as Promise.allSettled, but executes requests in sequence to work around a race condition
+	// that can cause an error when the fonts directory doesn't exist yet.
```
Comment (peterwilsoncc) [inline packages/edit-site/src/components/global-styles/font-library-modal/utils/index.js]: Multi-line comment format per coding standards. Made the lines the same length because it looks nicer. 

```suggestion
	/*
	 * Uses the same response format as Promise.allSettled, but executes requests in sequence to work 
	 * around a race condition that can cause an error when the fonts directory doesn't exist yet.
	 */
```

**Review by peterwilsoncc — APPROVED** [review]
This looks good and tests well. The timeline in the browser tools' network tab confirms the uploads are sequential.

I was able to consistently reproduce the race condition with a version of the code in https://github.com/WordPress/gutenberg/issues/59023#issuecomment-2018324697

**Comment by getdave** [comment]
@bph we'll need to bring this into Gutenberg 18.0.0.

**Comment by getdave** [comment]
This PR was triaged by Editor release leads and contributors in WP Slack as part of the final WordPress 6.5 process.

See https://wordpress.slack.com/archives/C02QB2JS7/p1711371934226359 (requires registration).

The criteria used was:

- Was this bug identified during the RC cycle for WP 6.5?
- Is this bug directly related to one of the blessed features in this release?
- Would this bug cause existing website’s to break/fail upon upgrade to WP 6.5?
- What is the approximate scope of the impact? Scale: (Minimal) 1 - 5 (Severe).
- Is the fix introducing any new features or changes?

**Conclusion**: we propose that this fix _is_ included in WP 6.5.

**Reason**: bug affects the (blessed) Font Library feature in a severe way and this PR resolves it in a simple fashion.

We now await a final decision from the full release team.

**Review by getdave — APPROVED** [review]
I was able to replicate the error on `trunk` and then reset everything and applied this PR and re-tested.


The fix works correctly and the code looks good. Great work 👏 

Screen Shot 2024-03-26 at 09 37 42

**Review by mikachan — APPROVED** [review]
Nice! Thanks for working on this 👏 It tests well for me.

(I have a feeling this will fix/improve the issue I've seen with request times when working on the [e2e tests](https://github.com/WordPress/gutenberg/pull/59316).)

**Comment by getdave** [comment]
There have now been multiple reviews and tested by contributors. As a result I went ahead and merged this.

**Comment by bph** [comment]
I just cherry-picked this PR to the release/18.0 branch to get it included in the next release: 671b80a648

File: packages/edit-site/src/components/global-styles/font-library-modal/utils/index.js (hunk 1 above)
Comment (creativecoder) [reply packages/edit-site/src/components/global-styles/font-library-modal/utils/index.js]: Thank you! I will try to remember this one for next time.

**Comment by getdave** [comment]
@creativecoder Please could we look into adding some test coverage for the changes in this PR. This will increase confidence of release team in including this in WP 6.5. See [related Slack discussion](https://wordpress.slack.com/archives/C065MBW03EH/p1711471479786339).

**Comment by getdave** [comment]
e2e test coverage is being worked on in https://github.com/WordPress/gutenberg/pull/60221/.

**Comment by getdave** [comment]
I just cherry picked this into WP 6.5 RC 4 branch https://github.com/WordPress/gutenberg/pull/60241/commits/a5ab3c568f66a4099e85f94b1cef17ae59a5e631
