### PR TITLE
Fix wp-env start for non-english core sources

### LINKED ISSUE #22938: If a non-English package is specified with `wp-env` , an error occurs at `wp-env start` .
**Describe the bug**

Run `wp-env start` with a non-English package in the `core` field of `wp-env` , as shown below.

```json:.wp-env.json
{
    "core": "https://ja.wordpress.org/latest-ja.zip"
}
```

Then, the following error occurs.

```bash
>wp-env start
× Error while running docker-compose command.
Starting XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_mysql_1 ... done
Starting XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_tests-wordpress_1 ... done
Error: Could not process the 'wp-config.php' transformation.
Reason: Unable to locate placement anchor.
```

*Notice*

Although the error ends, the container is still running and can be accessed with `localhost:8888` .

**To reproduce**

1. Prepare a `.wp-env.json` file for a non-English package as described above.
    - I experimented with Japanese ( `https://ja.wordpress.org/latest-ja.zip` ) as well as French ( `https://fr.wordpress.org/latest-fr_FR.zip` ) and confirmed that the same error is displayed.
2. Run `npm i @wordpress/env --save-dev`
3. Run `wp-env start`

**Expected behavior**

`wp-env` executes correctly.

**Screenshots**

N/A

**Editor version (please complete the following information):**

- WordPress version: `latest-ja`, `latest-fr_FR`
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? N/A
- If the Gutenberg plugin is installed, which version is it? N/A

**Desktop**

- OS: `Windows 10 Pro 1909`
- Docker Engine: `v19.03.8`
- `wp-env` Version: `1.3.0`, `1.4.0`
- Browser: N/A

**Smartphone**

N/A

**Additional context (My expectation)**

First, a Google search for the error `Could not process the 'wp-config.php' transformation.` resulted in the WP-CLI file.

- [config\-command/Config\_Command\.php at v2\.0\.5 ・ wp\-cli/config\-command](https://github.com/wp-cli/config-command/blob/v2.0.5/src/Config_Command.php#L507)

Here's a quote from the code.

```php:config-command/Config_Command.php
        } catch ( Exception $exception ) {
            WP_CLI::error( "Could not process the 'wp-config.php' transformation.\nReason: {$exception->getMessage()}" );
        }
```

Next, I searched for `Unable to locate placement anchor.` after `Reason:`.

- [wp\-config\-transformer/WPConfigTransformer\.php at v1\.2\.6 ・ wp\-cli/wp\-config\-transformer](https://github.com/wp-cli/wp-config-transformer/blob/v1.2.6/src/WPConfigTransformer.php#L151)

```php:wp-config-transformer/WPConfigTransformer.php
            if ( false === strpos( $this->wp_config_src, $anchor ) ) {
                throw new Exception( 'Unable to locate placement anchor.' );
            }
```

At a cursory reading of the code, it seems to be looking for the string `/* That's all, stop editing!` in the file `wp-config.php`.

Probably, the `add` method of the `WPConfigTransformer` class searches for the default (English) string when it runs.

However, since this time I'm specifying a non-English package, it is assumed that an exception was thrown and an error was made because there is no matching string.

Is it possible to add the `lang` field to `.wp-env.json` and use `@wordpress/env/lib/wordpress.js` in order to refer to the `lang` field when we install WordPress with WP-CLI?

### PR DESCRIPTION
**Pull request by ixkaito**
## Description

To specify the `anchor` parameter of `wp config set` to `define( 'WP_DEBUG',` in `configureWordPress()` instead of using the default `/* That’s all, stop editing!`, because non-English WordPress core doesn't have that line in `wp-config-sample.php` and will return errors. This will fix #22938.

By the way, I also tested `--anchor="define( 'WP_DEBUG', true );" --placement=after`, `--anchor="define( 'WP_DEBUG', false );" --placement=after`, etc. It inserts values properly to the `wp-config.php`, but the CLI still returns `Error: Could not process the 'wp-config.php' transformation. Reason: Unable to locate placement anchor.`.

I know this might not be the best solution, but it's better to make wp-env work in all environments first.

## How has this been tested?

- `npx wp-env start` with the default `.wp-env.json`
- `npx wp-env start` with `"core": "https://ja.wordpress.org/latest-ja.zip"` in `.wp-env.json`
- `npm run test`

All of these returned no warnings and errors, and the front page of WordPress was displayed at http://localhost:8888.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/env/lib/wordpress.js [hunk 1]
```diff
@@ -83,7 +83,7 @@ async function configureWordPress( environment, config, spinner ) {
 		// Add quotes around string values to work with multi-word strings better.
 		value = typeof value === 'string' ? `"${ value }"` : value;
 		setupCommands.push(
-			`wp config set ${ key } ${ value }${
+			`wp config set ${ key } ${ value } --anchor="define( 'WP_DEBUG',"${
```
Comment (noahtallen) [inline packages/env/lib/wordpress.js:86]: This works for me assuming that WP_DEBUG is always defined :p

**Review by noahtallen — APPROVED** [review]
image

:heavy_check_mark: Firstly, this does successfully install the correct WordPress image for me

image

:heavy_check_mark: Secondly, this continues correctly adding the config values.

:heavy_check_mark: Finally, this continues working for a default install with no modifications.

Also, the test failures are unrelated, since the RN tests do not rely on wp-env.
