### PR TITLE
Embed Block: Fix Aspect Ratio Classes #29641

### LINKED ISSUE #29641: Yotube videos cannot be changed aspect
## Description

Youtube aspect ratio is defined on the classes of the embed block, such as: wp-embed-aspect-4-3 wp-has-aspect-ratio

But when changing the classes to change to 16-9, it does not save the change.
## Expected behaviour

The video should change aspect ratio LIVE

## Actual behaviour

The video kept its ratio.

## Screenshots or screen recording (optional)

https://video.drift.com/v/abfFJ0Jwp5q/

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: Not Installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
- Device: Chromebook
- Operating system: Chrome OS
- Browser: Chrome v88

### LINKED ISSUE #41813: Additional CSS class(es) not loading properly for Embed-block in wp-admin
### Description

The value in the "Additional CSS class(es)"-field on Embed-blocks is not loaded correctly in wp-admin. If you add a value to the field, publish the page (or save it as draft), and then refresh, the custom class will be missing. The value is stored in the database, and is shown when visiting the frontend, but as soon as you do some changes to the page and update it, the custom class will be overwritten. The additional CSS classes will then be gone.

### Step-by-step reproduction instructions

1. Create a new post in wp-admin
2. Add the Vimeo- or YouTube-block to the page, and put in a valid URL (e.g. `https://vimeo.com/253989945`)
3. Select the block, go to the options panel, and open up "Advanced"
4. Add a random class to "Additional CSS class(es)", e.g. `test-class-123`
5. Publish the page
6. Refresh the edit-page in wp-admin
7. Find the "Additional CSS class(es)"-field - the class you added should now be missing
8. If you try to leave the page, it will tell you that you have unsaved changes

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress version: 6.0
- Gutenberg plugin version: 13.4.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #45540: Embed Blocks: Additional CSS classes are not saved
### Description

Additional CSS classes are not preserved in embed blocks.
At least, it was reproduced in the following blocks

- Twitter
- YouTube
- Flickr

In addition, Twitter will no longer preview correctly when additional CSS classes are entered.

https://user-images.githubusercontent.com/54422211/199924820-eb48bc65-645c-4937-b6d7-b09517d0a925.mp4

### Step-by-step reproduction instructions

N/A

### Screenshots, screen recording, code snippet

N/A

### Environment info

Gutenberg Version: 14.5.0-rc.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #46627: Youtube block - pasting link clearing existing classes
### Description

When you add any class to the Youtube block that has already embedded url the class is not save after page refresh.

### Step-by-step reproduction instructions

1. Add Youtube block
2. Add any class and save page - the class is now saved.
3. Open page click the block and paste any YT url -> https://www.youtube.com/watch?v=MFj_S0Nof90&list=RDCMUCFbNIlppjAuEX4znoulh0Cw&start_radio=1
4. Now your class is overwritten by "wp-embed-aspect-16-9 wp-has-aspect-ratio"

### Screenshots, screen recording, code snippet

https://www.loom.com/share/f03c97bb875342caa3019dbd83709a8b

### Environment info

newest version of Wordpress

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by TylerB24890**
## What?

This Pull Request ensures the aspect ratio classes remain the same across Block Editor reloads. If an editor adds a custom Aspect Ratio class to a YouTube video, it should retain that class until the embed is changed.

## Why?

Aspect Ratio classes (i.e. `wp-embed-aspect-16-9`) are added automatically to YouTube Videos (and potentially other embeds.) When this aspect ratio class is manually changed (to, for example, `wp-embed-aspect-4-3`) the video aspect ratio would change as expected and save to the block, but when the block editor reloads the classes are reverted to the original aspect ratio despite what is saved in the Block Attributes.

Resolves #29641.
Resolves #41813.
Resolves #45540.
Resolves #46627.

## How?

When the Embed URL is added or changed the Aspect Ratio classes are reset using the existing `removeAspectRatioClasses()` method. This action fires in the `onSubmit` action of the URL input field.

When the **Preview** view is activated, we check if the Block already has a valid Aspect Ratio class applied. If it does, do not regenerate the classes and retain the classes that have already been set. If it **does not** have an Aspect Ratio class this can be considered a new embed, so the ratio classes are regenerated.

A new utility method `hasAspectRatioClass( existingClassNames )` has been added to determine if a block already has an Aspect Ratio class.

## Testing Instructions

1. Open the Block Editor in any post type
2. Add the **Embed Block**
3. Add a valid YouTube Embed Link
    - Confirm the Aspect Ratio classes are generated and added to the "Classes" input under the "Advanced" panel.
4. Change the Aspect Ratio class to another valid Aspect Ratio class
    - If the aspect ratio class is `wp-embed-aspect-16-9` change it to `wp-embed-aspect-4-3` (and vice-versa)
    - Verify the video Aspect Ratio has changed in the editor.
5. Update the page.
    - **Do not** refresh the block editor page yet.
6. View the frontend of the page **in a new tab** and confirm the new aspect ratio is applied to the block.
7. Revisit the Block Editor tab and refresh the page.
8. Confirm the Embed Block retains the custom applied Aspect Ratio.
9. Click the Edit icon to replace the Embed URL.
10. Either replace the Embed URL with a new video **or** simply click "Embed" again.
11. Confirm the Aspect Ratio classes were reset (or changed to the correct/original)

### CODE REVIEW

**Comment by Mamaduka** [comment]
Sorry for the ping, @fluiddot. Since you recently worked on Embed block fixes, maybe you can have a look at this PR 🙇

**Comment by fluiddot** [comment]
> Sorry for the ping, @fluiddot. Since you recently worked on Embed block fixes, maybe you can have a look at this PR 🙇

Hey @Mamaduka, thanks for the ping 😊. I'll be happy to check these changes but I'd like to note that although I worked on fixes related to the Embed block, they were mainly related to the native version which is the platform I focus on as part of the Gutenberg Mobile project. Being this said, we might eventually ping someone else with higher context on the web version of the Embed block.

**Comment by Mamaduka** [comment]
That sounds good, @fluiddot.

P.S. I think I could also use a refresher on the Embed block 😄

File: packages/block-library/src/embed/util.js [hunk 1]
```diff
@@ -152,6 +152,21 @@ export const createUpgradedEmbedBlock = (
...
+ * @return {boolean} True or false if the classnames contain an aspect ratio class.
+ */
+export const hasAspectRatioClass = ( existingClassNames ) => {
+	if ( ! existingClassNames ) {
+		return false;
+	}
+	return ASPECT_RATIOS.some( ( { className } ) =>
+		existingClassNames.includes( className )
+	);
+};
```
Comment (fluiddot) [inline packages/block-library/src/embed/util.js:168]: It would be great if you could add a unit test for covering this logic, wdyt?

File: packages/block-library/src/embed/util.js [hunk 2]
```diff
@@ -311,6 +326,14 @@ export const getMergedAttributesWithPreview = (
 	ignorePreviousClassName = false
 ) => {
 	const { allowResponsive, className } = currentAttributes;
+
+	// Aspect ratio classes are removed when the embed URL is updated.
+	// If the embed already has an aspect ratio class, that means the URL has not changed.
+	// Which also means no need to regenerate it.
+	if ( hasAspectRatioClass( className ) ) {
+		return currentAttributes;
+	}
```
Comment (fluiddot) [inline packages/block-library/src/embed/util.js]: @TylerB24890 I'm wondering if we could rely upon determining if the attributes should be updated from the preview data just by the presence of aspect ratio classnames 🤔 . From the testing I've done so far, looks like the attributes remain the same, but I'm not sure if this might lead to side effects in the future.

I'm thinking that this check might be done in `getAttributesFromPreview` function instead, specifically in the part we're getting the classnames, so we would only modify the `classname` attribute with this logic:
https://github.com/WordPress/gutenberg/blob/5695f47ac1bf5c4df5bef1338b4e25cb3772a3a6/packages/block-library/src/embed/util.js#L301-L305

So, in case the block already has aspect ratio classes, we would keep them instead of calculating new ones, wdyt?

Following this approach, we would need also to stop setting the `ignorePreviousClassName` argument to `true` when receiving the preview, so we don't ignore the current class names:
https://github.com/WordPress/gutenberg/blob/5695f47ac1bf5c4df5bef1338b4e25cb3772a3a6/packages/block-library/src/embed/edit.js#L147-L151

In fact, I introduced the `ignorePreviousClassName` parameter for addressing [this issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/4059) in https://github.com/WordPress/gutenberg/pull/35326. However, I checked that with the changes you made in relation to removing the aspect ratio classes when the embed URL changes, we no longer require it.

**Review by fluiddot — COMMENTED** [review]
@TylerB24890 I've tested the changes and work as expected 🎊 . However, I added a couple of comments that would be great if you could take a look at them, before proceeding to approve the PR, thanks 🙇 .

File: packages/block-library/src/embed/util.js (hunk 1 above)
Comment (TylerB24890) [reply packages/block-library/src/embed/util.js:168]: Done! https://github.com/WordPress/gutenberg/pull/41141/commits/80fac253e0e8af7c18d53e96a57a4c9b03abd8d3

File: packages/block-library/src/embed/util.js (hunk 2 above)
Comment (TylerB24890) [reply packages/block-library/src/embed/util.js]: @fluiddot Apologies for the delayed response & update here. Things kind of got crazy for a while and I wasn't able to circle back around to this.

I've updated this as you've suggested;
1. Moved the `hasAspectRatioClass()` check to the `getAttributesFromPreview` method
   - If `hasAspectRatioClass` returns `true` we skip regenerating the classes.
2. Removed the `ignorePreviousClassName` parameter (and all referencing methods).
    - As you mentioned, this is no longer needed when we reset the classnames when the URL changes.
3. Added a unit test to cover the `hasAspectRatioClass`.

Comment (fluiddot) [reply packages/block-library/src/embed/util.js]: No worries at all @TylerB24890 , thank you very much for making the updates 🙇. Sorry I couldn't review this earlier, I'm planning to take a look today 👀 .

**Review by fluiddot — COMMENTED** [review]
I tested the last changes using the Testing Instructions outlined in the PR and confirmed that work as expected 🎊.

I also tried the mobile native version and looks like we should apply the same changes to match the same behavior between platforms. @TylerB24890 I created the following patch file in case you'd like to apply it to this PR, otherwise, I'll be happy to push a commit with the changes. I tested those changes in the mobile native version and confirmed they also work as expected (including the issue solved in https://github.com/WordPress/gutenberg/pull/35326).

<details><summary><strong>Patch file</strong></summary>

```
diff --git forkSrcPrefix/packages/block-library/src/embed/edit.native.js forkDstPrefix/packages/block-library/src/embed/edit.native.js
index 109478461c0b3e14975e4f3df2a17523774bf7ea..eec991c7b2037b46e5d0e40c3ab006fbcfb35b5f 100644
--- forkSrcPrefix/packages/block-library/src/embed/edit.native.js
+++ forkDstPrefix/packages/block-library/src/embed/edit.native.js
@@ -4,6 +4,7 @@
 import {
 	createUpgradedEmbedBlock,
 	getClassNames,
+	removeAspectRatioClasses,
 	fallback,
 	getEmbedInfoByProvider,
 	getMergedAttributesWithPreview,
@@ -123,16 +124,14 @@ const EmbedEdit = ( props ) => {
 	/**
 	 * Returns the attributes derived from the preview, merged with the current attributes.
 	 *
-	 * @param {boolean} ignorePreviousClassName Determines if the previous className attribute should be ignored when merging.
 	 * @return {Object} Merged attributes.
 	 */
-	const getMergedAttributes = ( ignorePreviousClassName = false ) =>
+	const getMergedAttributes = () =>
 		getMergedAttributesWithPreview(
 			attributes,
 			preview,
 			title,
-			responsive,
-			ignorePreviousClassName
+			responsive
 		);
 
 	const toggleResponsive = () => {
@@ -159,21 +158,20 @@ const EmbedEdit = ( props ) => {
 		const newURL = url.replace( /\/$/, '' );
 		setIsEditingURL( false );
 		setAttributes( { url: newURL } );
-	}, [ preview?.html, url ] );
+	}, [ preview?.html, url, cannotEmbed, fetching ] );
 
 	// Handle incoming preview.
 	useEffect( () => {
 		if ( preview && ! isEditingURL ) {
-			// When obtaining an incoming preview, we set the attributes derived from
-			// the preview data. In this case when getting the merged attributes,
-			// we ignore the previous classname because it might not match the expected
-			// classes by the new preview.
-			setAttributes( getMergedAttributes( true ) );
+			// When obtaining an incoming preview,
+			// we set the attributes derived from the preview data.
+			const mergedAttributes = getMergedAttributes();
+			setAttributes( mergedAttributes );
 
 			if ( onReplace ) {
 				const upgradedBlock = createUpgradedEmbedBlock(
 					props,
-					getMergedAttributes()
+					mergedAttributes
 				);
 
 				if ( upgradedBlock ) {
@@ -188,13 +186,25 @@ const EmbedEdit = ( props ) => {
 		[ isEditingURL ]
 	);
 
-	const onEditURL = useCallback( ( value ) => {
-		// The order of the following calls is important, we need to update the URL attribute before changing `isEditingURL`,
-		// otherwise the side-effect that potentially replaces the block when updating the local state won't use the new URL
-		// for creating the new block.
-		setAttributes( { url: value } );
-		setIsEditingURL( false );
-	}, [] );
+	const onEditURL = useCallback(
+		( value ) => {
+			// If the embed URL was changed, we need to reset the aspect ratio class.
+			// To do this we have to remove the existing ratio class so it can be recalculated.
+			if ( attributes.url !== value ) {
+				const blockClass = removeAspectRatioClasses(
+					attributes.className
+				);
+				setAttributes( { className: blockClass } );
+			}
+
+			// The order of the following calls is important, we need to update the URL attribute before changing `isEditingURL`,
+			// otherwise the side-effect that potentially replaces the block when updating the local state won't use the new URL
+			// for creating the new block.
+			setAttributes( { url: value } );
+			setIsEditingURL( false );
+		},
+		[ attributes, setAttributes ]
+	);
 
 	const blockProps = useBlockProps();
 

```
</details>

Thanks!

**Comment by fluiddot** [comment]
As I mentioned [here](https://github.com/WordPress/gutenberg/issues/41813#issuecomment-1453937076), this PR will also fix the issue https://github.com/WordPress/gutenberg/issues/41813 🎊 .

**Comment by TylerB24890** [comment]
> I tested the last changes using the Testing Instructions outlined in the PR and confirmed that work as expected 🎊.
> 
> I also tried the mobile native version and looks like we should apply the same changes to match the same behavior between platforms. @TylerB24890 I created the following patch file in case you'd like to apply it to this PR, otherwise, I'll be happy to push a commit with the changes. I tested those changes in the mobile native version and confirmed they also work as expected (including the issue solved in #35326).
> 
> **Patch file**
> Thanks!

This is great! Thank you, @fluiddot ! 

I've applied the patch file in this PR and have re-submitted. Please take a look and let me know if you have any further suggestions or changes!

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

I confirm the following test cases work as expected:
- Change the Aspect Ratio class to another valid Aspect Ratio class is preserved (https://github.com/WordPress/gutenberg/issues/29641) ✅ .
- Additional CSS class(es) are preserved when changing the aspect ratio or Embed URL (https://github.com/WordPress/gutenberg/issues/41813) ✅ .
- No regression introduced related to cut-off in preview when editing URL on mobile (https://github.com/wordpress-mobile/gutenberg-mobile/issues/4059) ✅.

Thank you very much @TylerB24890 for working on this fix 🙇 !

From my side, the PR is ready to be merged. @Mamaduka since you pinged me originally in the PR, let me know if you'd like to take a look or we can go ahead and merge it, I'll be happy to do it. Thanks!

**Review by Mamaduka — APPROVED** [review]
Thank you, @TylerB24890! The changes look good to me!

@t-hamano, if you have time, do you mind checking if this also fixes the issue reported by you - #45540?

**Review by t-hamano — APPROVED** [review]
Thank you for the great work, @TylerB24890!

This PR would also fix the two problems of #45540 and #46627. In particular, I have tested whether custom classes not related to aspect-ratio are retained, and have confirmed that they are retained no matter what operation is performed.
