### PR TITLE
Fix navigation link block dragging error

### LINKED ISSUE #30177: Error when dragging and dropping inner blocks of the navigation block
## Description
Block drag and drop seems to be buggy in the navigation block.

When dropping a block, often the block disappears, and an error is thrown in the console:
Screenshot 2021-03-24 at 6 18 28 pm

The stack trace seems to indicate an error with one of the rich text formats.

Originally reproduce in the navigation editor, but also happens in the post editor.

## Step-by-step reproduction instructions
1. Add some inner blocks to a nav block
2. Try re-ordering them using drag and drop

## Expected behaviour
It works

## Actual behaviour
The dragged block disappears on drop

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #30177.

The thing that triggers the error is the call to the `isDraggingBlocks` selector. I'm not sure why yet. I'll do some more digging to try to fix the root cause.

But this can serve as an intermediate fix.

To resolve the issue I removed a bunch of code related to that selector, and I don't really know what some of it does. It looks like one use of `isDraggingBlocks` was to hide the appenders in the nav block when dragging. I don't think it's a big issue if these are visible again.

The other cases modify the `is-selected` and `is-editing` classnames. It's unclear to me what that might do, but it might be that there was a need for this originally, but now there isn't (the feature still seems to work ok without this).

## How has this been tested?
Try dragging a navigation link (including into a nested submenu)
Expected result: The block should be drag and droppable.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-library/src/navigation-link/edit.js [hunk 1]
```diff
@@ -297,12 +294,8 @@ export default function NavigationLinkEdit( {
...
 		ref: listItemRef,
 		className: classnames( {
-			'is-editing':
-				( isSelected || isParentOfSelectedBlock ) &&
-				// Don't show the element as editing while dragging.
-				! isDraggingBlocks,
-			// Don't select the element while dragging.
-			'is-selected': isSelected && ! isDraggingBlocks,
+			'is-editing': isSelected || isParentOfSelectedBlock,
+			'is-selected': isSelected,
```
Comment (ellatrix) [inline packages/block-library/src/navigation-link/edit.js]: Why do we assign the `is-selected` class when `useBlockProps` is responsible for this?

And could we also revert the change here: https://github.com/WordPress/gutenberg/commit/748c632feccbffb51a6e3c79972a447b71211a0c#diff-4501da117949f251043d70ffccf02c54af2a99fb80ccd33eb2d40175acdfc833L153?

Comment (talldan) [reply packages/block-library/src/navigation-link/edit.js]: I don't know to be honest. Might just have been a visual thing.

It was originally added in this PR - https://github.com/WordPress/gutenberg/pull/17832 - which has a lot of comments, it might have been discussed in there at some point.

I'll remove that line.

Comment (ellatrix) [reply packages/block-library/src/navigation-link/edit.js]: Ah, sorry, should have linked this one too: https://github.com/WordPress/gutenberg/commit/748c632feccbffb51a6e3c79972a447b71211a0c#diff-4501da117949f251043d70ffccf02c54af2a99fb80ccd33eb2d40175acdfc833R165

**Review by ellatrix — APPROVED** [review]

**Comment by ellatrix** [comment]
Would be good to also remove this change https://github.com/WordPress/gutenberg/commit/748c632feccbffb51a6e3c79972a447b71211a0c#diff-4501da117949f251043d70ffccf02c54af2a99fb80ccd33eb2d40175acdfc833R165
Otherwise sounds good.

**Comment by ellatrix** [comment]
If we do want to make style changes based on a block being dragged, we should use a dragging class in combination with e.g.`is-selected` (and others) instead of removing that class on dragging.

File: packages/block-library/src/navigation-link/edit.js (hunk 1 above)
Comment (talldan) [reply packages/block-library/src/navigation-link/edit.js]: Have removed both of the modified lines, and it still seems to work, so hopefully there's no drama from that change (cd3aa0c).

Comment (ellatrix) [reply packages/block-library/src/navigation-link/edit.js]: If there's a problem we look for a pure CSS solution. :)
