### PR TITLE
Ensure layout classnames are applied to the inner blocks wrapper and not to its siblings

### LINKED ISSUE #57242: `wp_render_layout_support_flag` renders classes on wrong element
### Description

Like the [comment here](https://github.com/WordPress/gutenberg/blob/6bbf33c1eeb634ed404ef8505318852308f0a627/lib/block-supports/layout.php#L746-L803) says (in @TODO as well), the wrong element is used when there is no inner block wrapper. This happens for example with a block that uses a `<details>` element and a `<summary class="anything">` inside, and then renders the inner blocks directly after the `</summary>` like the HTML spec allows/recommends:

```html
<details>
  <summary class="anything">Summary title</summary>
  <p>Inner blocks</p>
  <p>Other blocks</p>
</details>
```

The `core/details` block is not affected because it just happens to not apply any classes to the `summary` element. But for custom blocks that do (ie: `supports.color.__experimentalSkipSerialization` that apply to `summary` instead of the root `details` element), this becomes a problem.

A workaround is to obviously wrap the inner blocks in a `div` or similar, but this may cause other style issues and is not in line with HTML spec again. And a Make WordPress Core article about inner blocks recommends this approach of adding [HTML inline with inner blocks](https://make.wordpress.org/core/2021/12/28/take-more-control-over-inner-block-areas-as-a-block-developer/).

### Step-by-step reproduction instructions

1. Create a custom block that supports layout, and renders an element with a non-empty class attribute and then renders inner blocks directly after: `<details { ...innerBlocksProps }><summary className="anything">Summary</summary>{ innerBlocksProps.children }</details>`
2. Insert this block in the editor and save post
3. View post. See how the `is-layout-flow` (or `flex`, etc) class is applied to the `summary` element instead of the `details` element.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WordPress 6.4.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

Fixes #57242.

When there's an element inside a block container which is a sibling to its inner blocks, and that element has a classname, and the block has layout support, we need to ensure that the layout classnames are applied to the container and not to the inner block sibling. The logic in trunk finds the last element with a classname in the first chunk of `innerContent`, which is the element right before the inner blocks start. But if this element has a closing tag in that first chunk, it's likely to be a sibling and not the container (it can still be the container if there are no inner blocks, in which case there should only be one chunk of `innerContent`, but in that case we have no way of distinguishing it from a sibling element so it's safer to keep the layout classes in the outer wrapper. I was also looking for a solution to #76235 but can't think of a reliable one that doesn't mess with dynamic content).

This PR tries to check for a closing tag in the first chunk of `innerContent` and not apply the layout classnames if it exists.

## Testing Instructions

This may be easier to test by checking out the branch locally and making changes to the Details block so that its `summary` element has a classname.

Check that when `summary` has a classname, the layout classes don't get attached to it but stay on the outer wrapper.

## Use of AI Tools

Code generated with copilot; reviewed and tested by myself.

### CODE REVIEW

**Comment by andrewserong** [comment]
Oh, hey, this is clever! Good find. Just to make sure I'm following correctly, this accumulates a stack of _unclosed_ elements that should help us more reliably identify the inner blocks wrapper by attempting to grab the very last unclosed tag and walk our way back up.

Is it possible to add some simple PHP tests to cover the cases that were breaking? I think it might be simply adding other cases to `data_layout_support_flag_renders_classnames_on_wrapper`?

**Comment by tellthemachines** [comment]
> Oh, hey, this is clever! Good find. Just to make sure I'm following correctly, this accumulates a stack of _unclosed_ elements that should help us more reliably identify the inner blocks wrapper by attempting to grab the very last unclosed tag and walk our way back up.

Yes, we want to ensure the classnames are added to the last unclosed tag because that points to it being the actual inner block wrapper.

> Is it possible to add some simple PHP tests to cover the cases that were breaking? I think it might be simply adding other cases to `data_layout_support_flag_renders_classnames_on_wrapper`?

Good idea!

File: lib/block-supports/layout.php [hunk 1]
```diff
@@ -1050,10 +1050,30 @@ function gutenberg_render_layout_support_flag( $block_content, $block ) {
...
-			$class_attribute = $first_chunk_processor->get_attribute( 'class' );
+		/*
+		 * Use a stack to track open elements as tags are visited. Void elements
+		 * (those without a matching closing tag) are excluded so they don't
+		 * accumulate on the stack. At the end of the chunk, every element still
+		 * on the stack is unclosed — meaning its closing tag lives in a later
+		 * innerContent entry alongside the inner blocks, which makes it the
+		 * inner-block container. Elements that open and close within this chunk
+		 * are siblings that precede the inner blocks and should be ignored.
+		 * The last unclosed element with a class attribute is the best candidate
```
Comment (ramonjd) [inline lib/block-supports/layout.php:1061]: Is this is the "last" as in last in a list, or "Innermost"? Just getting my head around things 😄

File: lib/block-supports/layout.php [hunk 2]
```diff
@@ -1050,10 +1050,30 @@ function gutenberg_render_layout_support_flag( $block_content, $block ) {
...
+		 * for the inner-block wrapper.
+		 */
+		$tag_stack          = array();
+		$html_void_elements = array( 'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'param', 'source', 'track', 'wbr' );
```
Comment (ramonjd) [inline lib/block-supports/layout.php]: Anyway to use `WP_HTML_Processor::is_void` here? Or is it not the right use case?

https://github.com/WordPress/wordpress-develop/blob/bf4c17409433cc14a37aa0ad7bf10982a4b8ebe6/src/wp-includes/html-api/class-wp-html-processor.php#L6611

**Review by ramonjd — COMMENTED** [review]
This is working well for me - thanks for tackling it. At first sight the changes look good. I'll defer to @dmsnell when he gets time to run an eye over the HTML tag processor usage. 

| Before  | After |
| ------------- | ------------- |
| Image  | Image |

File: lib/block-supports/layout.php (hunk 1 above)
Comment (tellthemachines) [reply lib/block-supports/layout.php:1061]: It's the last open tag in the string of markup that is `$block['innerContent'][0]`.

File: lib/block-supports/layout.php (hunk 2 above)
Comment (tellthemachines) [reply lib/block-supports/layout.php]: Oh I didn't know about that one! It should work.

Comment (tellthemachines) [reply lib/block-supports/layout.php]: Updated! Much better.

**Review by andrewserong — APPROVED** [review]
Looking good! Thanks for adding the test, and this is smoke testing well with the Details block hacked in to add a class name to the `summary` element:

Image

Tested with a bunch of different configurations of layouts including accordions, cover block, etc, and all working fine.

LGTM 🚀

File: lib/block-supports/layout.php [hunk 3]
```diff
@@ -1050,10 +1050,29 @@ function gutenberg_render_layout_support_flag( $block_content, $block ) {
...
+		 * inner-block container. Elements that open and close within this chunk
+		 * are siblings that precede the inner blocks and should be ignored.
+		 * The last unclosed element with a class attribute is the best candidate
+		 * for the inner-block wrapper.
+		 */
+		$tag_stack = array();
+		while ( $first_chunk_processor->next_tag( array( 'tag_closers' => 'visit' ) ) ) {
+			if ( $first_chunk_processor->is_tag_closer() ) {
+				array_pop( $tag_stack );
+			} elseif ( ! WP_HTML_Processor::is_void( $first_chunk_processor->get_tag() ) ) {
```
Comment (dmsnell) [inline lib/block-supports/layout.php:1068]: we also have “special atomic elements” like `SCRIPT` and `STYLE` and others which have no closing tag. they wouldn’t be likely, but some could show up, such as `TEXTAREA`.

a more proper solution would use the `WP_HTML_Processor->expects_closer()` method to see if a closing tag is meant to appear. that will handle all of the wild edge cases, including knowing that `IMG` is a void element in HTML, but not if it appears within an `SVG` or `MATH` element.

we can use depth to track which elements are open and closed and limit that to elements with a class because the depth increases before visiting and opening tag and decreases before visiting a closing tag.

```php
$first_chunk_processor = WP_HTML_Processor::create_fragment( $first_chunk );
$open_classes = array();
$open_depths  = array();
while ( $first_chunk_processor->next_token() ) {
	if ( '#tag' !== $first_chunk_processor->get_token_type() ) {
		continue;
	}

	$depth = $first_chunk_processor->get_current_depth();

	if ( $first_chunk_processor->is_tag_closer() ) {
		if ( $depth < ( end( $open_depths ) ?? 0 ) ) {
			array_pop( $open_depths );
		}
		continue;
	}

	if ( null === ( $classes = $first_chunk_processor->class_list() ) ) {
		continue;
	}

	$open_classes[] = iterator_to_array( $classes );
	$open_depths[]  = $depth;
}

$inner_block_wrapper_classes = end( $open_classes );
```

this highlights another existing issue, which is that we’re looking for exact string matches of the `class` attribute. in this snippet I’ve tossed in a change which gives us the ability to match any element containing all of the class names in the `class` attribute, not just exact matches.

this could be further refined by limiting these to names that start with some prefix, like `wp-`
