### PR TITLE
Fix for drop-down "New Post" button to remove hacky code - Fixes #4682

### LINKED ISSUE #4682: "Classic editor" option in "New post" drop down launches Gutenberg
## Issue Overview

I saw this in v2.0 and thought it MUST have been reported and fixed in GB 2.1, but it's not.

On the "All Posts" screen is a "New post" button which, with the GB plugin installed has a dropdown with two items:

* Gutenberg; and 
* Classic editor

screen shot 2018-01-25 at 21 11 24

Both of these seem to link to /wp-admin/post-new.php

The "Classic editor" link therefore launches Gutenberg.

## Steps to Reproduce (for bugs)
1. Install and activate Gutenberg plugin
2. Go to "All posts" screen
3. Select "Classic Editor" from the dropdown

I'm using Chrome 63 on a MacBook Pro running High Sierra

## Expected Behavior

The Classic Editor should open

## Current Behavior

The Gutenberg editor opens

## Possible Solution

Make the "Classic Editor" link have the `classic-editor` parameter in the URL

### PR DESCRIPTION
**Pull request by rosswintle**
This makes the button work in environments that run WordPress in non-global scope, such as Laravel Valet. It's an alternative solution to #4683 that attempts to fix #4682

## Description
Removed hacky code that sets default URL for New Post button.
Modify JS that "fixed" this URL for the classic editor.

## How Has This Been Tested?

Manually on my local Laravel Valet environment. You may want to test it in other environments.

## Types of changes
Breaking change (fix or feature that would cause existing functionality to not work as expected):

Arguably if you have JS turned off then then New Post button no longer works. But then, none of the other new post links around the place work either, so this seems OK.

## Checklist:
- [X] My code is tested.
- [?] My code follows the WordPress code style.
- [X] My code has proper inline documentation.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Related #4704

**Review by danielbachhuber — APPROVED** [review]
I've verified this works as expected locally:

addnew

**Review by aduth — APPROVED** [review]
I'm a bit puzzled by the original implementation, as the one offered here seems far simpler and equally valid. cc @pento (#3070) for additional context if needed, though I understand you're AFK for a while longer.

Works well in my testing 👍

File: gutenberg.php [hunk 1]
```diff
@@ -517,13 +485,14 @@ function gutenberg_replace_default_add_new_button() {
 			}
 
 			var url = button.href;
-			var newUrl = url.replace( /[&\?]?classic-editor/, '' );
+			var urlHasParams = ( -1 !== url.indexOf( '?' ) );
```
Comment (aduth) [inline gutenberg.php]: There was a single trailing whitespace here, which is apparently not captured by PHPCS (likely because it's in a JS code block?). I'd encourage you to install an EditorConfig integration for your preferred editor, which will automatically strip this on a per-project basis (configured already for Gutenberg):

http://editorconfig.org/#download

Fixed in 3e18927a64cec0027a8ee7f25aec2cbf804c2b8d
