### PR TITLE
Fix the headings hierarchy in the styles sidebar

### LINKED ISSUE #42496: Fix the headings hierarchy in the Styles sidebar
### Description

Follow-up to https://github.com/WordPress/gutenberg/issues/42373

The headings hierarchy in the Styles sidebar is less than ideal. It skips levels, doesn't follow a logical structure and it appears it was implemented more for visual purposes rather than for good semantics.

Suffice to say the first heading within the Styles sidebar is a H5, which doesn't make sense and it's totally disconnected from the overall headings hierarchy.

A good headings structure is not just about good semantics. Headings are also a navigational tool for screen reader users, as they can use dedicated commands to jump through headings, get a sense of the overall content, and navigate a page. This principle applies also to administration user interfaces, where headings can be used to identify the main parts of the interface.

### Step-by-step reproduction instructions

- Go to the Site editor.
- Open the Styles sidebar.
- Click 'Colors'.
- Check the 'Colors' text to the right of the back button is a H5 heading. This is incorrect.
- Check that 'Palette' and 'Elements' are H2 headings. This doesn't communicate a proper hierarchy.
- Click 'Buttons'.
- Check the 'Buttons' text to the right of the back button is a H5 heading. This is incorrect.
- Check the 'Text color' heading underneath 'Buttons' is a H4 heading. This is incorrect because 'Text color' should be a sub-heading of 'Buttons'.
- Check the all-caps text 'THEME' is a H2 heading. It should be a sub-heading of 'Text color'.
- Check the all-caps text 'DEFAULT' is a H2 heading. It should be a sub-heading of 'Text color'.
- Check 'Background color' is a H2 heading. It skips a heading level but it should probably be a H2 in the first place.
- Check the all-caps text 'THEME' is a H2 heading. It should be a sub-heading of 'Background color'.
- Check the all-caps text 'DEFAULT' is a H2 heading. It should be a sub-heading of 'Background color'.

Hint; Use the HeadingsMap browser extension to check the headings hierarchy. 

### Screenshots, screen recording, code snippet

Worth mentioning the HeadingsMap browser extension only highlights skipped heading levels, and in the screenshot below there are a few headings highlighted as errors. It doesn't evaluate whether a heading level is logically correct or not, which requires evaluation by a human.

Screenshot 2022-07-18 at 12 07 53

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by afercia**
Fixes #42496 

## What?

Changes the heading levels in the styles sidebar so that the headings hierarchy is correct.

## Why?

The heading hierarchy must reflect the logical structure of the content.

Previously, the first heading in the styles sidebar was a H5, which skipped many levels and didn't make sense.

Also, sections of content that belong to a main 'topic' need a heading level to indicate they're 'sub-headings'.

## How?

- Changes the level of some `Heading` components.
- Chances the heading level of some other components that use a `Heading` component, adds new props where necessary.

Regarding `ToolsPanel`, I'm not that familiar with TypeScript types, please do let me know if the way I imported and used types is correct.

## Testing Instructions

The best way to test this PR is by installing the [HeadingsMap](https://chrome.google.com/webstore/detail/headingsmap/flbjommegcjonpdmenkdiocclhjacmbi) browser extension (available also for Firefox).
- Go to the site editor.
- Open the Styles sidebar.
- Launch HeadingsMap: it will open a sidebar that shows the headings hierarchy.
- Navigate through **all the panels and sub-panels** of the Styles sidebar: the HeadingsMap will update on the fly and show the headings hierarchy of the current panel.
- Check that the headings hierarchy within the Styles sidebar:
  - starts with a H2
  - all the headings below the H2 are sub-headings (H3 and H4, depending on the panel)

## Screenshots or screencast 

A few screenshots:

Typography panel:

typography

Colors panel:

colors

Colors > Palette panel:

color palette

Layout panel:

layout

### CODE REVIEW

**Comment by carolinan** [comment]
I have fixed the two small merge conflicts.
I made one update to the new Custom CSS screen to make the subtitle a level 3 heading.
The same type of update needs to be made when the per-block custom CSS is merged.

I have browsed through all the screens / panels and the levels look correct to me.

I found an exception that can be solved in a separate PR, and that is a missing H1 when the style book is opened:

The headingsmap browser addon is showing that the Style book page is missing an H1

**Review by carolinan — APPROVED** [review]

**Comment by aristath** [comment]
@afercia can you please rebase this PR to resolve the conflicts? Once it gets rebased, we can continue with the review 👍

**Comment by afercia** [comment]
Rebased on top of latest trunk.

**Review by aristath — APPROVED** [review]
* Code looks good
* Automated tests pass
* Manually testing and inspecting the headings hierarchy this is a great improvement

This PR looks good to me 👍

File: packages/components/src/palette-edit/index.js [hunk 1]
```diff
@@ -313,6 +313,7 @@ export default function PaletteEdit( {
 	colors = EMPTY_ARRAY,
 	onChange,
 	paletteLabel,
+	paletteLabelLevel = 2,
```
Comment (ciampo) [inline packages/components/src/palette-edit/index.js:316]: I don't think that this prop name conveys its meaning, since "level" only makes sense in the context of a "heading".

I suggest that we rename this prop to a more clear name, maybe `paletteLabelHeadingLevel`?

File: packages/components/src/tools-panel/types.ts [hunk 2]
```diff
@@ -47,6 +52,10 @@ export type ToolsPanelProps = {
 	 * last visible `ToolsPanelItem` within the `ToolsPanel`.
 	 */
 	__experimentalLastVisibleItemClass?: string;
+	/**
+	 * The heading level of the panel's header.
+	 */
+	headingLevel: HeadingSize;
```
Comment (ciampo) [inline packages/components/src/tools-panel/types.ts:58]: I believe this prop should be marked as optional as assigned a default value, both for `ToolsPanel` and `ToolsPanelHeader`. Any reason why it was marked as required instead?

**Review by ciampo — COMMENTED** [review]
Thank you for working on this, @afercia — this is definitely a great improvement!

For future work involving the `@wordpress/components` package, it would be great if you could ping @mirka and/or myself so that we can help and advise.

Especially when working on API design, and ever more so for low-level packages like components/data/etc.., we need to think carefully about the choices we make given the strict back-compat policy.

Finally, when making changes in the components package, we usually add an item to the package's [CHANGELOG](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md).

Furthermore, tomorrow marks the feature freeze deadline for the WordPress 6.2 release — @afercia would be able to follow-up and apply any agreed changes to the components before tomorrow ?

Edit: I went ahead and opened #47788

**Comment by carolinan** [comment]
> For future work involving the `@wordpress/components` package, it would be great if you could ping @mirka and/or myself so that we can help and advise.

Have you considered adding yourself as code owners? It is great to know who to ping, but not so easy to remember when you work on so many different parts of the project.

**Comment by afercia** [comment]
Sorry for late response, pretty busy days and I missed to reply.

Tanks for your feedback @ciampo and for the polishing in #47788. Much appreciated.

All your points make totally sense. Just a few considerations.

I'd second @carolinan's comment, as it is important to make contributors live easier.

> Especially when working on API design, and ever more so for low-level packages like components/data/etc.., we need to think carefully about the choices we make given the strict back-compat policy.

Is this policy documented anywhere? Not arguing, but I think for the greater good of any open source software project it's very, very important to make all contributors well aware of the best practices they should follow. I'm all for a wise back-compat policy but it should be documented and shared. Any contributor deserves to be placed in the best possible conditions for a valuable contribution. Also, that would help to make the best use of their time and of the reviewers' time. 

> when making changes in the components package, we usually add an item to the package's CHANGELOG

I'm not arguing on this point as well 🙏 Is this documented anywhere, though? Maybe I'm missing something because of my low vision but I can't see anything related to changelog entries in the components package CONTRIBUTING.md or README.md. I just see generic recommendations to 'ensure documentation'.
If a changelog entry is a required step for API changes, then this requirement should be well documented. Contributors are not required to know internal best practices, even if they're very good practices. I'd suggest to add some good documentation and illustrate the rationale for this policy in the CONTRIBUTING.md.
