### PR TITLE
Components: Update ExternalLink to support onClick handler

### LINKED ISSUE #45212: Components: ExternalLink onClick event handler is not working
### Description

We are using ExternalLink on multiple instances in Jetpack monorepo, using the onClick event handler to track clicks. After a recent change implemented, any code passed to onClick prop is being ignored by this component.

This is related to a [recent change implemented](https://github.com/WordPress/gutenberg/pull/42259/files#diff-d9253c06cfb3ec985751228ee0c3b07c4029a0a54aa9684a55c8be53de5858e7R52) for validating anchor links in #42259.

### Step-by-step reproduction instructions

You can reproduce the bug by adding an `onClick` event handler to `ExternalLink`. After clicking the link, you will notice it is not calling `doSomething` function.

```
import { ExternalLink } from '@wordpress/components';
import { useCallback } from '@wordpress/element';

const MyExternalLink = () => {
	const doSomething = useCallback( () => {
		console.log( 'ExternalLink clicked!' );
	}, [] );

	return (
		<ExternalLink href="https://wordpress.org" onClick={ doSomething }>
			WordPress.org
		</ExternalLink>
	);
);
```

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Initsogar**
## What?

Fixes #45212

The idea is to make `<ExternalLink>` component to handle onClick events again, based on the issue #45212. Also it includes some unit testing for this component.

## Why?

`onClick` handler on `<ExternalLink>` component is currently being used in [multiple instances in Jetpack monorepo](https://github.com/Automattic/jetpack/search?q=ExternalLink+onClick) to record tracking events, and we consider it is necessary to include custom logic on that handler.

This stopped working after a change implemented for validating anchor links in https://github.com/WordPress/gutenberg/pull/42259.

## How?

We are creating a new function for the `onClick` handler to:
* Validate and execute `onClick` whether it is passed as a prop.
* Validate if the link is an internal anchor, so we can prevent default action to not impact what was implemented on [#42259](https://github.com/WordPress/gutenberg/pull/42259)

## Testing Instructions
You can run unit tests for this:
```npm run test:unit -- external-link/test/index.tsx```

### CODE REVIEW

**Review by alexstine — COMMENTED** [review]
@Initsogar Thanks for your PR. I do like how the code is a little cleaner now and makes more sense.

One thing that will be needed, the changelog will need updating at packages/components/changelog.md. Probably call this a bug fix if it is currently not working.

**Comment by ciampo** [comment]
@chad1008 , would you be able to review this PR ?

File: packages/components/src/external-link/test/index.tsx [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+			<ExternalLink
+				href="https://wordpress.org"
+				onClick={ doSomething }
+				data-testid="external-link"
+			>
+				WordPress.org
+			</ExternalLink>
+		);
+
+		fireEvent.click( screen.getByTestId( 'external-link' ) );
```
Comment (chad1008) [inline packages/components/src/external-link/test/index.tsx]: [Looking for the element's accessible role and name](https://testing-library.com/docs/queries/byrole/) will better simulate how a user would interact with the component. Perhaps something like:

```
const component = screen.getByRole( 'link', {
			name: "I'm an anchor link! (opens in a new tab)",
		} );
```


Also along the same lines of[ testing user interaction, `userEvent` would be preferable to `fireEvent`](https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/testing-overview.md#user-interactions). (examples: [ComboboxControl](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/combobox-control/test/index.js) or [ColorPalette](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/color-palette/test/index.js) tests)

File: packages/components/src/external-link/test/index.tsx [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+		render(
+			<ExternalLink href="#test" data-testid="external-link">
+				I&apos;m an anchor link!
+			</ExternalLink>
+		);
+
+		const component = screen.getByTestId( 'external-link' );
+		const clickEvent = createEvent.click( component );
+
+		fireEvent( component, clickEvent );
```
Comment (chad1008) [inline packages/components/src/external-link/test/index.tsx]: same as above re: `userEvent` vs `fireEvent`

File: packages/components/src/external-link/test/index.tsx [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+				data-testid="external-link"
+			>
+				I&apos;m an anchor link!
+			</ExternalLink>
+		);
+
+		const component = screen.getByTestId( 'external-link' );
+		const clickEvent = createEvent.click( component );
+
+		fireEvent( component, clickEvent );
```
Comment (chad1008) [inline packages/components/src/external-link/test/index.tsx]: same as above re: `userEvent` vs `fireEvent`

File: packages/components/src/external-link/test/index.tsx [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+				data-testid="external-link"
+			>
+				I&apos;m not an anchor link!
+			</ExternalLink>
+		);
+
+		const component = screen.getByTestId( 'external-link' );
+		const clickEvent = createEvent.click( component );
+
+		fireEvent( component, clickEvent );
```
Comment (chad1008) [inline packages/components/src/external-link/test/index.tsx]: same as above re: `userEvent` vs `fireEvent`

File: packages/components/src/external-link/test/index.tsx [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+				onClick={ doSomething }
+				data-testid="external-link"
+			>
+				WordPress.org
+			</ExternalLink>
+		);
+
+		fireEvent.click( screen.getByTestId( 'external-link' ) );
+
+		expect( doSomething ).toHaveBeenCalled();
```
Comment (chad1008) [inline packages/components/src/external-link/test/index.tsx]: I'd recommend `toHaveBeenCalledTimes(1)`. The more specific check can avoid some subtle bugs from creeping in.

File: packages/components/src/external-link/test/index.tsx [hunk 6]
```diff
@@ -0,0 +1,84 @@
...
+				I&apos;m an anchor link!
+			</ExternalLink>
+		);
+
+		const component = screen.getByTestId( 'external-link' );
+		const clickEvent = createEvent.click( component );
+
+		fireEvent( component, clickEvent );
+
+		expect( doSomething ).toHaveBeenCalled();
```
Comment (chad1008) [inline packages/components/src/external-link/test/index.tsx]: same as above re `toHaveBeenCalledTimes()` vs `toHaveBeenCalled()`

File: packages/components/src/external-link/test/index.tsx [hunk 7]
```diff
@@ -0,0 +1,84 @@
...
+	} );
+
+	test( 'should prevent default action when clicking an internal anchor link', () => {
+		render(
+			<ExternalLink href="#test" data-testid="external-link">
+				I&apos;m an anchor link!
+			</ExternalLink>
+		);
+
+		const component = screen.getByTestId( 'external-link' );
```
Comment (chad1008) [inline packages/components/src/external-link/test/index.tsx]: same as above re: roles vs `getByTestId()`

File: packages/components/src/external-link/test/index.tsx [hunk 8]
```diff
@@ -0,0 +1,84 @@
...
+			<ExternalLink
+				href="#test"
+				onClick={ doSomething }
+				data-testid="external-link"
+			>
+				I&apos;m an anchor link!
+			</ExternalLink>
+		);
+
+		const component = screen.getByTestId( 'external-link' );
```
Comment (chad1008) [inline packages/components/src/external-link/test/index.tsx]: same as above re: roles vs `getByTestId()`

File: packages/components/src/external-link/test/index.tsx [hunk 9]
```diff
@@ -0,0 +1,84 @@
...
+		render(
+			<ExternalLink
+				href="https://wordpress.org"
+				data-testid="external-link"
+			>
+				I&apos;m not an anchor link!
+			</ExternalLink>
+		);
+
+		const component = screen.getByTestId( 'external-link' );
```
Comment (chad1008) [inline packages/components/src/external-link/test/index.tsx]: same as above re: roles vs `getByTestId()`

File: packages/components/src/external-link/test/index.tsx [hunk 10]
```diff
@@ -0,0 +1,84 @@
...
+				I&apos;m an anchor link!
+			</ExternalLink>
+		);
+
+		const component = screen.getByTestId( 'external-link' );
+		const clickEvent = createEvent.click( component );
+
+		fireEvent( component, clickEvent );
+
+		expect( clickEvent.defaultPrevented ).toBe( true );
```
Comment (chad1008) [inline packages/components/src/external-link/test/index.tsx]: With the suggested change to userEvent, you'll need a different test of the `defaultPrevented` property. Maybe something like: 

```
const onClickMock = jest.fn();

// ...

expect( onClickMock ).toHaveBeenCalledTimes( 1 );
expect( onClickMock ).toHaveBeenLastCalledWith(
  expect.objectContaining( {
    defaultPrevented: true
  } )
);
```

File: packages/components/src/external-link/test/index.tsx [hunk 11]
```diff
@@ -0,0 +1,84 @@
...
+			</ExternalLink>
+		);
+
+		const component = screen.getByTestId( 'external-link' );
+		const clickEvent = createEvent.click( component );
+
+		fireEvent( component, clickEvent );
+
+		expect( doSomething ).toHaveBeenCalled();
+		expect( clickEvent.defaultPrevented ).toBe( true );
```
Comment (chad1008) [inline packages/components/src/external-link/test/index.tsx]: same as above re: `clickEvent.defaultPrevented` after implementing `userEffect`

File: packages/components/src/external-link/test/index.tsx [hunk 12]
```diff
@@ -0,0 +1,84 @@
...
+				I&apos;m not an anchor link!
+			</ExternalLink>
+		);
+
+		const component = screen.getByTestId( 'external-link' );
+		const clickEvent = createEvent.click( component );
+
+		fireEvent( component, clickEvent );
+
+		expect( clickEvent.defaultPrevented ).toBe( false );
```
Comment (chad1008) [inline packages/components/src/external-link/test/index.tsx]: same as above re: `clickEvent.defaultPrevented` after implementing `userEffect`

**Review by chad1008 — CHANGES_REQUESTED** [review]
Changes to the component look good to me 🙂. I've included some inline comments on the new unit tests.

Other than that I think all this will need is a CHANGELOG entry!

**Comment by Initsogar** [comment]
Thanks @alexstine and @chad1008, I will be working on the suggested changes!

File: packages/components/src/external-link/test/index.tsx (hunk 10 above)
Comment (Initsogar) [reply packages/components/src/external-link/test/index.tsx]: @chad1008 The idea of this specific test case is to validate it is properly preventing default action if it is an anchor link, without passing onClick prop to our component (I will update the test case name). I'm trying to find a way to accomplish this using userEvent, but don't find any yet. Do you have any idea how we could handle it?

Comment (Initsogar) [reply packages/components/src/external-link/test/index.tsx]: I think we can mock the `onClick` after rendering the link from the component and validate we are receiving the `defaultPrevented: true`. Something like:

```
const user = setupUser();

render(
	<ExternalLink href="#test">I&apos;m an anchor link!</ExternalLink>
);

const link = screen.getByRole( 'link', {
	name: "I'm an anchor link! (opens in a new tab)",
} );

const onClickMock = jest.fn();
link.onclick = onClickMock;

await user.click( link );
expect( onClickMock ).toHaveBeenCalledTimes( 1 );
expect( onClickMock ).toHaveBeenLastCalledWith(
	expect.objectContaining( { defaultPrevented: true } )
);
```

What do you think?

Comment (Initsogar) [reply packages/components/src/external-link/test/index.tsx]: I tested this approach, and it is working as expected. I will push new changes so you can review it properly :)

**Comment by Initsogar** [comment]
Hmm, I clicked to ask for re-review from @chad1008 and @alexstine and somehow it messed up and removed the other ones that were on the list. Sorry 😅

I just added the changelog entry and made changes on the unit test related to use getByRole and userEvent instead of getByTestId and fireEvent/createEvent. I would appreciate your review :)

File: packages/components/src/external-link/test/index.tsx (hunk 10 above)
Comment (chad1008) [reply packages/components/src/external-link/test/index.tsx]: Ah, yes I see your point... hard to test the behavior when no `onClick` is passed by ...passing a mock to `onClick` 😆

Your proposed solution looks like works, although modifying the event listener imperatively is an unusual pattern. Maybe we just add a brief comment to those two tests explaining that we're using that approach specifically so we can test the `defaultPrevented` without passing an `onClick` prop? It's described in the test title, but a comment closer to the actual `link.onclick` modification might help make it crystal clear for future maintainers.

Comment (Initsogar) [reply packages/components/src/external-link/test/index.tsx]: Correct! 🥲 I just added the comments!

**Comment by Initsogar** [comment]
@chad1008 I just added some comments for clarification purposes on the approach used for unit testing `defaultPrevented` on this component while no passing `onClick` prop. Also resolved the conflict with components `CHANGELOG.md`.

File: packages/components/src/external-link/test/index.tsx [hunk 13]
```diff
@@ -0,0 +1,113 @@
...
+
+	test( 'should call function passed in onClick handler and prevent default action when clicking an internal anchor link', async () => {
+		const user = setupUser();
+		const onClickMock = jest.fn();
+
+		render(
+			<ExternalLink
+				href="#test"
+				onClick={ onClickMock }
+				data-testid="external-link"
```
Comment (chad1008) [inline packages/components/src/external-link/test/index.tsx]: Just noticed this `data-testid` is still here, but no longer needed. Looks like there's another lingering in the next test as well. We can remove both before merging 🙂

**Review by chad1008 — APPROVED** [review]
Looks great @Initsogar, thank you! I left one last inline comment (sorry for not spotting that last time), but after that I think we're good to go 🚀 🚢 

Congrats on your first core contribution, btw! 🎉

File: packages/components/src/external-link/test/index.tsx (hunk 13 above)
Comment (Initsogar) [reply packages/components/src/external-link/test/index.tsx]: You are right! Thank you for that!
Just [fixed](https://github.com/WordPress/gutenberg/pull/45214/commits/0f48906784b35bce8d4ab9197ce487f97436dcb3) it :)

**Comment by Initsogar** [comment]
@chad1008 @ciampo @mirka Hey there! I pushed the latest suggestion and I think we are ready. Could you confirm and let me know what would be the next step? :) Thanks for all your support!

**Comment by ciampo** [comment]
Hey @Initsogar , I re-ran the failing tests (it looks like they're being a flakey lately) and they passed!

I'll go ahead and merge your changes — thank you for helping the project, and congrats on your first contribution 🎉  Happy to collaborate more in the future in case you felt like opening more PRs like this one
