### PR TITLE
Add: action to set category icon; Fix: Managing block categories documentation

### LINKED ISSUE #11594: Adding SVG icon to block category in GB 4.2.0 doesn't work
**Describe the bug**
Adding an SVG icon to block category as described in https://github.com/WordPress/gutenberg/blob/062089236b9ab32994af2595e44ee9791bcb5570/docs/extensibility/extending-blocks.md#managing-block-categories doesn't seem to work in GB 4.2.0.

**To Reproduce**
0. register a block
```
registerBlockType( 'my-plugin/test', {
    title: 'Test Category Icon',
    category: 'my-category',
    icon: 'wordpress',
    ...
);
```
1. Follow the example at https://github.com/WordPress/gutenberg/blob/062089236b9ab32994af2595e44ee9791bcb5570/docs/extensibility/extending-blocks.md#managing-block-categories

[Edit: since the proposed fix involves changing the example, I'm adding the current state of the example when this issue was opened, for posterity]
```
<?php
// my-plugin.php

function my_plugin_block_categories( $categories, $post ) {
	if ( $post->post_type !== 'post' ) {
		return $categories;
	}
	return array_merge(
		$categories,
		array(
			array(
				'slug' => 'my-category',
				'title' => __( 'My category', 'my-plugin' ),
				'icon'  => '<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path fill="none" d="M0 0h24v24H0V0z" /><path d="M19 13H5v-2h14v2z" /></svg>',
			),
		)
	);
}
add_filter( 'block_categories', 'my_plugin_block_categories', 10, 2 );
```

**Expected behavior**
I expect to the see the icon to the right of the category name in the block chooser

**Screenshot**

gb-no-icon

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Chrome  70.0.3538.77

**Additional context**
Gutenberg 4.2.0 and WP 4.9.8

Note: setting a dashicon works, just SVG that doesn't.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Closes: https://github.com/WordPress/gutenberg/issues/11594

The documentation of "Managing block categories" was wrong as on the server we can not set SVG icons. The server would not be able to use our SVG component.
This PR fixes the documentation and adds a new action that allows updating the icon on the front end in a simple way.

## How has this been tested?
```
Add the following code to functions.php:
function my_plugin_block_categories( $categories, $post ) {
	if ( $post->post_type !== 'post' ) {
		return $categories;
	}
	return array_merge(
		$categories,
		array(
			array(
				'slug' => 'my-category',
				'title' => __( 'My category', 'my-plugin' ),
			),
		)
	);
}
add_filter( 'block_categories', 'my_plugin_block_categories', 10, 2 );
```
Execute the following code block on the browser console:
```
(function() {
	var el = wp.element.createElement;
	var SVG = wp.components.SVG;
	var circle = el( 'circle', { cx: 10, cy: 10, r: 10, fill: 'red', stroke:	'blue', strokeWidth: '10' } );
	var svgIcon = el( SVG, { width: 20, height: 20, viewBox: '0 0 20 20'},	circle);
	wp.blocks.updateCategory( 'my-category', { icon: svgIcon } );
} )();
( function() {
	const { registerBlockType } = wp.blocks;
	const { createElement: el } = wp.element;
	const { InnerBlocks } = wp.editor;

	registerBlockType( 'block/simple-block', {
		title: 'Test Simple Block',
		icon: 'carrot',
		category: 'my-category',

		edit() {
			return el( 'div', { style: { outline: '1px solid gray', padding: 5 } },
				el( 'p', {}, 'ok' )
			);
		},

		save() {
			return el( 'div', { style: { outline: '1px solid gray', padding: 5 } },
				el( 'p', {}, 'ok' )
			);
		},
	} );
} )();
```
Verify a circle is the icon of "My category"

### CODE REVIEW

File: packages/blocks/src/api/categories.js [hunk 1]
```diff
@@ -20,3 +20,13 @@ export function getCategories() {
...
 	dispatch( 'core/blocks' ).setCategories( categories );
 }
+
+/**
+ * Sets the category icon.
+ *
+ * @param {string}       slug Block category slug.
+ * @param {string|Array} icon Block category icon.
+ */
+export function setCategoryIcon( slug, icon ) {
```
Comment (youknowriad) [inline packages/blocks/src/api/categories.js]: I'd personally prefer a `addCategory` action instead of this. This actions is targetting the issue directly but I think the issue is not about allowing to edit the icon but more about allowing to set the icon as SVG from the server. I expect some work around this in phase2 (because it's the same issue for blocks).

So instead of offering a way to edit the icon, I'd prefer if we offer a way to add a category without requiring any filter on the backend.

Is this not a viable option?

Comment (jorgefilipecosta) [reply packages/blocks/src/api/categories.js]: Hi @youknowriad,
I think we made the categories changeable on the server because the blocks may be registered on the server.
I thought we may have timing issues if a block registered on the server, used a category added on the client (the add code may not yet have been executed when the block is registered). So I end up in this approach where the category is still managed on the server but we allow updating the icon with client code so SVG's may be open.
Also, the category seems important data that the server should be aware of, so I was not totally comfortable documenting a method that allows categories being added to the client only. Technically this is already possible using the setCategories action but it is not something we recommend anywhere in our docs.
This approaches documents a way to add categories on the server, and then just the icon is updated on the client. I think updating the icon on the client is fine and could be seen as applying a skin and allows a plugin for example change all the default icons. The icon is not information important to the server while the category may end up being important.

That said I can give a try to an add action make some tests and if things seem fine to update this PR, let me know if you think applying this change is worth it.

Comment (gziolo) [reply packages/blocks/src/api/categories.js]: What if we limit this PR to offering a store action which updates a category on the client instead? What if someone would want to update the name of the category?

```js
const icon = <SVG ....</SVG>;
dispatch( 'core/blocks' ).updateCategory( slug, { icon } );
```

I personally don't see any value in offering all those action wrappers which don't have any additional logic but forces us to have the same functionality documented twice. At the same time, it introduces the confusion for plugin developers because there are 2 ways to perform the same task. I think we had `getCategories` in the past which wasn't using store at all. When we refactored code we didn't remove it which in retrospect should happen in my opinion.

Comment (jorgefilipecosta) [reply packages/blocks/src/api/categories.js]: Hi @gziolo, I updated this PR to follow your suggestion.

File: docs/data/data-core-blocks.md [hunk 2]
```diff
@@ -224,4 +224,13 @@ Returns an action object used to set block categories.
...
+ * categories: Block categories.
+
+### updateCategory
+
+Returns an action object used to update a category.
+
+*Parameters*
+
+ * slug: Block category slug.
+ * newProperties: Object containing the category properties that should be updated.
```
Comment (gziolo) [inline docs/data/data-core-blocks.md]: Should it be called `category` for consistency with `setCategories` action?

File: docs/extensibility/extending-blocks.md [hunk 3]
```diff
@@ -333,13 +333,25 @@ function my_plugin_block_categories( $categories, $post ) {
...
 	);
 }
 add_filter( 'block_categories', 'my_plugin_block_categories', 10, 2 );
 ```
 
-You can also display an icon with your block category by setting an `icon` attribute. The value can be the slug of a [WordPress Dashicon](https://developer.wordpress.org/resource/dashicons/), or a custom `svg` element.
+You can also display an icon with your block category by setting an `icon` attribute. The value can be the slug of a [WordPress Dashicon](https://developer.wordpress.org/resource/dashicons/).
+It is possible to set an SVG as the icon of the category if a custom icon is needed.
+To do so, the icon should be rendered and set on the frontend, so it can make use of WordPress SVG, allowing mobile compatibility and making the icon more accessible.
+To use an SVG icon add a category as shown in the previous example, and add javascript code to the editor calling wp.blocks.updateCategory e.g:
```
Comment (gziolo) [inline docs/extensibility/extending-blocks.md]: It might need to be tweaked as follows:

> To use the SVG icon with the category ...

@tofumatt can you help? :)

File: docs/extensibility/extending-blocks.md [hunk 4]
```diff
@@ -333,13 +333,25 @@ function my_plugin_block_categories( $categories, $post ) {
...
+```js
+(function() {
```
Comment (gziolo) [inline docs/extensibility/extending-blocks.md]: Space is missing after opening parenthesis.

File: docs/extensibility/extending-blocks.md [hunk 5]
```diff
@@ -333,13 +333,25 @@ function my_plugin_block_categories( $categories, $post ) {
...
+	var el = wp.element.createElement;
+	var SVG = wp.components.SVG;
+	var circle = el( 'circle', { cx: 10, cy: 10, r: 10, fill: 'red', stroke:	'blue', strokeWidth: '10' } );
```
Comment (gziolo) [inline docs/extensibility/extending-blocks.md]: There is some whitespace issues after `stroke:`.

File: docs/extensibility/extending-blocks.md (hunk 3 above)
Comment (gziolo) [inline docs/extensibility/extending-blocks.md]: `wp.blocks.updateCategory` should be wrapped in backticks so it stands out.

File: packages/blocks/src/store/reducer.js [hunk 6]
```diff
@@ -124,10 +134,27 @@ export const unregisteredFallbackBlockName = createBlockNameSetterReducer( 'SET_
  * @return {Object} Updated state.
  */
 export function categories( state = DEFAULT_CATEGORIES, action ) {
-	if ( action.type === 'SET_CATEGORIES' ) {
-		return action.categories || [];
+	switch ( action.type ) {
+		case 'SET_CATEGORIES':
```
Comment (gziolo) [inline packages/blocks/src/store/reducer.js]: Should categories be stored in an object keyed by the slug? It would simplify update operations. It might negatively influence selectors though.

**Comment by gziolo** [comment]
@jorgefilipecosta thanks for updating this PR. It looks like it needs to be rebases now because docs structure got an update.

I think it all looks good. I would double check whether we can simplify the reducer after changes introduced. See my comment https://github.com/WordPress/gutenberg/pull/11640#discussion_r235694688.

**Comment by jorgefilipecosta** [comment]
Hi @gziolo I applied most of your feedback, the missing change was the refactor to the state structure. I'm not sure if it is something, it seems linke a bigger change (involves updating selectors and most of existing category test cases) and if doing it I would prefer to do it in a separate PR to make sure this PR does not becomes unnecessarly huge.

**Review by gziolo — APPROVED** [review]
I tested it and it works great.  I tested the following:
- update the existing category with the snippet provided in the PR
- update the existing category again
- update non-existing category - it gets ignored

There is a slight delay until this change will be reflected in the UI when the inserter is opened. It might be nice to open a follow-up PR where we include `categories` in one of the memoized selectors which controls re-renders for the inserter. I assume it is the reason why it doesn't get updated immediately.

**Comment by gziolo** [comment]
> I'm not sure if it is something, it seems linke a bigger change (involves updating selectors and most of existing category test cases) and if doing it I would prefer to do it in a separate PR to make sure this PR does not becomes unnecessarly huge.

I anticipated it, fine to look at it later if it makes code easier to read for other observers, too.

**Comment by youknowriad** [comment]
> There is a slight delay until this change will be reflected in the UI when the inserter is opened. It might be nice to open a follow-up PR where we include categories in one of the memoized selectors which controls re-renders for the inserter. I assume it is the reason why it doesn't get updated immediately.

This is probably related to the fact that we don't use the selectors to retrieve the categories but use the `getCategories` global function instead. We should change that when possible, it could be a follow-up.

I think we should hold on merging this PR for the moment until we get some clarity on the need or not of an RC2

**Comment by gziolo** [comment]
> This is probably related to the fact that we don't use the selectors to retrieve the categories but use the `getCategories` global function instead. We should change that when possible, it could be a follow-up.

Yeah, we should kill that usage for `wp.blocks.getCategories` sooner than later. The same applies for `wp.blocks.getBlockTypes` :)

File: docs/designers-developers/developers/filters/block-filters.md [hunk 7]
```diff
@@ -329,12 +329,25 @@ function my_plugin_block_categories( $categories, $post ) {
...
 	);
 }
 add_filter( 'block_categories', 'my_plugin_block_categories', 10, 2 );
 ```
 
-You can also display an icon with your block category by setting an `icon` attribute. The value can be the slug of a [WordPress Dashicon](https://developer.wordpress.org/resource/dashicons/), or a custom `svg` element.
+You can also display an icon with your block category by setting an `icon` attribute. The value can be the slug of a [WordPress Dashicon](https://developer.wordpress.org/resource/dashicons/).
+It is possible to set an SVG as the icon of the category if a custom icon is needed.
+To do so, the icon should be rendered and set on the frontend, so it can make use of WordPress SVG, allowing mobile compatibility and making the icon more accessible.
+To use the SVG icon with the category as shown in the previous example, add the following example JavaScript code to the editor calling `wp.blocks.updateCategory` e.g:
```
Comment (chrisvanpatten) [inline docs/designers-developers/developers/filters/block-filters.md]: Would be good to have line breaks between paragraphs, or put them all as one line if they should be the same paragraph.

Comment (jorgefilipecosta) [reply docs/designers-developers/developers/filters/block-filters.md]: Thank you @chrisvanpatten the comments were updated 👍
