### PR TITLE
API: Replace all withAPIData usage and deprecate the HoC

### LINKED ISSUE #6277: Latest Posts Blocks don't retrieve content reliably
## Issue Overview
The Latest Posts block don't always retrieve the Latest Posts.

I had a page with 2 Latest Posts blocks (image below), and when I tried to edit the page, none of them showed any content.

I also had a page with 6 Latest Posts blocks (showing the different options such as Grid, List, Wide etc). Out of 6 Blocks, 3 showed content and 3 didn't.

gutenberg-latestposts

## Steps to Reproduce (for bugs)
1. Insert multiple Latest Posts blocks into content and save
2. Close page
3. Edit page with Latest Posts Blocks

## Expected Behavior
Latest Posts Block should always show content when editing the page

## Current Behavior
Latest Posts Block don't reliably retrieve content

_Gutenberg 2.7.0
Firefox Quantum 59.0.2 (64-bit)
WP 4.9.5_

### LINKED ISSUE #6379: Block displaying data with withAPIData only if window width below 782px
## Issue Overview

You can follow this [example](https://wordpress.org/gutenberg/handbook/blocks/creating-dynamic-blocks/) from Gutenberg handbook.
After post edit page reload,  block not displaying fetched data from API if window width bigger than 782px and get stuck in loading state. In safari if i go back to pages and open this page again data is appeared. I noticed that if window width > 782px edit method of wp.blocks.registerBlockType is called twice.

## Steps to Reproduce (for bugs)

1. Create block with HOC withAPIData ([example](https://wordpress.org/gutenberg/handbook/blocks/creating-dynamic-blocks/))
2. Add this block in editor
3. Save post
4. Reload page

Chrome, Firefox, Safari

### LINKED ISSUE #6537: withAPIData doesn't fetch after page reload
Hey guys, thanks for the awesome work around Gutenberg. I want to report the following issue that [another guy reproduced already](https://stackoverflow.com/questions/49995422/gutenberg-withapidata-hoc-not-fetching-on-page-reload).

## Issue Overview
When withAPIData is used, the data is loaded only when the block is added freshly to Gutenberg. If the block was already added and someone reloads the whole page, there is no data.

```
export default registerBlockType(
	'whatever/categories',
	{
		title:      'Whatever',
		category:   'widgets',
		icon:       'list-view',
		keywords:   [],
		supports:   {
			html: false,
		},
		attributes: {
			headline:       {
				type:    'string',
				default: 'Whatever',
			},
			
		},
		edit:       withAPIData( function () {
			return {
				categoriesList: '/wp/v2/categories?per_page=100&_fields=id,name,parent',
			}
		} )( ( props ) => {
			console.log(props.categoriesList); // no data once the page reloads

			return <div>whatever</div>;
		} ),
		save:       props => {
			return null;
		},
	},
);
```

## Steps to Reproduce (for bugs)
1. Add the block to Gutenberg. `props.categoriesList.data` exists and has data.
2. Reload the page (by pressing the browsers reload-button).
3. REST-Request finishes with code 200, however `props.categoriesList.data` is `undefined`.

I used Firefox developer edition 60.0b16 (64-Bit). But could reproduce it with Chrome 66.0.3359.139 as well.

## Expected Behavior
In the example above, `props.categoriesList` should return `{get: ƒ, isLoading: false, path: "/wp/v2/posts?per_page=4", create: ƒ, isCreating: false, data: [array data]}`

## Current Behavior
In the example above, `props.categoriesList` returns `{get: ƒ, isLoading: true, path: "/wp/v2/posts?per_page=4", create: ƒ, isCreating: false]}` (no data)

## Possible Solution
That's the question.

### LINKED ISSUE #7397: Core blocks: Stop using `withAPIData` for Latest Posts block in code and docs
Raised by @mrleemon in #7390:

> It might be a good idea to update the handbook section dedicated to building dynamic blocks cause it still makes reference to `withAPIData`:
>
> https://wordpress.org/gutenberg/handbook/blocks/creating-dynamic-blocks/

We should refactor Latest Posts block to use `withSelect` instead of `withAPIData` and update all docs to follow the same pattern. We are planning to deprecate `withAPIData`, so let's make sure it is no longer exposed in Gutenberg handbook.

More details on how to perform migration is shared in #7390.

There is also a known bug with a race condition inside `withAPIData` that has been around for quite some time. This is another reason why we should migrate our codebase sooner than later.

### PR DESCRIPTION
**Pull request by youknowriad**
This PR removes the remaining usage of withAPIData from Gutenberg and officially deprecate its usage.

**Testing instructions**

 - Check that The lastest posts block is working properly
 - Check that you can set a parent page when creating pages.

closes #7397
closes #6277
closes #6379
closes #6537

### CODE REVIEW

File: core-blocks/latest-posts/edit.js [hunk 1]
```diff
@@ -158,21 +156,20 @@ class LatestPostsEdit extends Component {
...
-export default withAPIData( ( props ) => {
+export default withSelect( ( select, props ) => {
 	const { postsToShow, order, orderBy, categories } = props.attributes;
+	const { getEntityRecords } = select( 'core' );
 	const latestPostsQuery = pickBy( {
 		categories,
 		order,
 		orderby: orderBy,
 		per_page: postsToShow,
-		_fields: [ 'date_gmt', 'link', 'title' ],
```
Comment (gziolo) [inline core-blocks/latest-posts/edit.js]: We are going to fetch more data, is that expected?

**Comment by gziolo** [comment]
Eslint complains

> /Users/gziolo/PhpstormProjects/gutenberg/core-blocks/latest-posts/edit.js
>  4:10  error  'get' is defined but never used  no-unused-vars

Unit test fails:

>  ● withAPIData() › should initialize fetchables on mount
> 
>     expect(jest.fn()).not.toHaveWarned(expected)
> 
>     Expected mock function not to be called but it was called with:
>     ["wp.components.withAPIData is deprecated and will be removed from Gutenberg in 3.7. Please use the Core Data Module or wp.apiFetch directly instead."]
> 
>       26 |      afterEach( () => {
>       27 |              if ( spy.assertionsNumber === 0 && spy.mock.calls.length > 0 ) {
>     > 28 |                      expect( console ).not[ matcherName ]();
>          |                      ^
>       29 |              }
>       30 |      } );
>       31 | };
> 
>       at Object.<anonymous> (packages/jest-console/src/index.js:28:4)

Otherwise everything works perfectly fine.

File: core-blocks/latest-posts/edit.js (hunk 1 above)
Comment (gziolo) [reply core-blocks/latest-posts/edit.js]: We could, but it is super complex :)

**Review by gziolo — APPROVED** [review]
Awesome 🎉 

great one 💯 

:shipit:

File: packages/core-data/src/entities.js [hunk 2]
```diff
@@ -40,6 +41,22 @@ async function loadPostTypeEntities() {
 	} );
 }
 
+/**
+ * Returns the list of the taxonomies entities.
```
Comment (aduth) [inline packages/core-data/src/entities.js]: Nit: The function returns a promise. The promise resolves to a list of the taxonomies entities.

Aside: This is probably one of the only things I dislike about `async` / `await`, that it becomes very non-obvious that it will always return a Promise (I think even if the function has no `return` statement? My uncertainty reenforces my point 😄 ).
