### PR TITLE
Rich Text: Add missing keep placeholder on focus prop.

### LINKED ISSUE #17405: RichText changes and custom blocks backwards compatibility for WP 5.3
**Describe the bug**
Recent changes related to the `RichText` component (tested in Gutenberg 6.4.0) seem to break backwards compatibility with custom blocks that work on WordPress 5.2 (not sure what the Gutenberg version is there).

**To reproduce**
- on WordPress trunk 5.3 alpha
- install latest [Yoast SEO](https://wordpress.org/plugins/wordpress-seo/) 12.0
- create a post and add a "How-to" block
- see the block UI works as expected:
  - clicking the 3 editable fields (actually they're 3 RichText) sets focus on the fields
  - the placeholder stays visible because the block uses `keepPlaceholderOnFocus={ true }`
  - when clicking the "step title" or the "step description", additional buttons appear within the UI
  - screenshot:

Screenshot 2019-09-11 at 15 18 48

- activate the Gutenberg plugin: I tested latest master 6.4.0 https://github.com/WordPress/gutenberg/commit/50fb29bb2181e56a4a2d4c5407ba23c8bba2c4da
- click multiple times on the editable fields and see the fields area is only partially clickable, and sometimes clicking doesn't set focus on the fields
- click the "step title" or the "step description": the additional buttons UI doesn't appear

**Expected behavior**
The custom blocks to work in the same way they work with the previous Gutenberg version.

**Additional context**

To my understanding, there are a few potential breaking changes in Gutenberg 6.4.0. Briefly:

The `RichText` is now split in two components:
https://github.com/WordPress/gutenberg/pull/15212

> There will be two RichText components in each package, where the one in the block-editor package wraps the one in the rich-text package and adds block context.

Also, there are several renamed props marked as “unstable”, for example `isSelected` is now `__unstableIsSelected` (besides `unstableOnFocus`).

> There's a few temporary unstable props added that aid this wrapping, but in the future these props should be stabilised. Some props might disappears, some need to be renamed for the "bare" RichText component.

Looks like there's no backwards compatibility with custom blocks that make use of the `RichText` component out of the way Gutenberg uses it. I do realise Yoast SEO implementation is "custom" but that usage of `RichText` used to be legitimate and now it breaks on Gutenberg 6.4.0. There may be other potential breakages with other plugins as well.

The Yoast SEO blocks can be explored at https://github.com/Yoast/wordpress-seo/tree/trunk/js/src/structured-data-blocks

Also, the `keepPlaceholderOnFocus` prop was removed. This removal is _undocumented_ so far. See https://github.com/WordPress/gutenberg/pull/16733

Worth also reminding that `wp.editor.RichText` is now deprecated and `wp.blockEditor.RichText` should be used instead. When developers switch to `wp.blockEditor.RichText` they will get the new `RichText` which brings in props with different names. The old props names should be translated to the new names in some way: this specific point was mentioned by @gziolo 

This issue was discussed during today's weekly editor meeting on Slack, see https://wordpress.slack.com/archives/C02QB2JS7/p1568208422122500

Agreed with the Gutenberg team to create a new issue to ensure backwards compatibility.

### PR DESCRIPTION
**Pull request by epiqueras**
Closes #17405

## Description

This PR fixes backwards compatibility issues that came with the unintentional removal of the `keepPlaceholderOnFocus` prop in `RichText`.

It does this by adding the prop back in.

## How has this been tested?

It was verified that setting the `keepPlaceholderOnFocus` prop to true makes the placeholder still show when selected/focused without content.

## Types of Changes

*Bug Fix:* Fix backwards compatibility issues arising from accidentally removing the `keepPlaceholderOnFocus` prop from `RichText`.

## Checklist:

- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/block-editor/src/components/rich-text/index.js [hunk 1]
```diff
@@ -336,6 +336,7 @@ class RichTextWrapper extends Component {
 			didAutomaticChange,
 			undo,
 			placeholder,
+			keepPlaceholderOnFocus,
```
Comment (gziolo) [inline packages/block-editor/src/components/rich-text/index.js]: Should we include the deprecation message?

File: packages/block-editor/src/components/rich-text/style.scss [hunk 2]
```diff
@@ -43,8 +43,14 @@
 	}
 
 	// Could be unset for individual rich text instances.
-	&.is-selected [data-rich-text-placeholder]::after {
-		display: none;
+	&.is-selected {
+		&.keep-placeholder-on-focus [data-rich-text-placeholder] {
+			pointer-events: none;
```
Comment (gziolo) [inline packages/block-editor/src/components/rich-text/style.scss]: Will it display a different cursor icon? I guess, it still needs to be overridden.

Comment (epiqueras) [reply packages/block-editor/src/components/rich-text/style.scss]: It shows the same one for me.

File: packages/block-editor/src/components/rich-text/index.js (hunk 1 above)
Comment (epiqueras) [reply packages/block-editor/src/components/rich-text/index.js]: We are not actually deprecating this one.

File: packages/block-editor/src/components/rich-text/style.scss (hunk 2 above)
Comment (ellatrix) [reply packages/block-editor/src/components/rich-text/style.scss]: Why does this rule need to be added? Is the one above not enough on `:after`?

**Comment by ellatrix** [comment]
Fixed https://github.com/WordPress/gutenberg/pull/16733#issuecomment-530337711 in 
37e6fab.

**Review by ellatrix — APPROVED** [review]

**Comment by ellatrix** [comment]
I see one small issue: when the placeholder is kept on focus and you click on it, there is no caret visible. You can still type though. I see that the browser selection is somewhere after the placeholder, so we could enforce selection to be in the placeholder text element. Let's look at this separately.

File: packages/block-editor/src/components/rich-text/style.scss (hunk 2 above)
Comment (epiqueras) [reply packages/block-editor/src/components/rich-text/style.scss]: It's needed so that you can select/see the caret through the placeholder.

**Comment by epiqueras** [comment]
Sounds good, thanks for taking a look at this!

File: packages/block-editor/src/components/rich-text/index.js (hunk 1 above)
Comment (gziolo) [reply packages/block-editor/src/components/rich-text/index.js]: We need to restore documentation then.

Comment (epiqueras) [reply packages/block-editor/src/components/rich-text/index.js]: #17445

**Comment by afercia** [comment]
> I see one small issue: when the placeholder is kept on focus and you click on it, there is no caret visible. You can still type though. I see that the browser selection is somewhere after the placeholder, so we could enforce selection to be in the placeholder text element. Let's look at this separately.

This was also noted on https://github.com/WordPress/gutenberg/pull/16733#issuecomment-530325186

When `keepPlaceholderOnFocus` is true, the editable is partially non-clickable, because the click actually happens on the new `<span>` .

**Comment by ellatrix** [comment]
> When `keepPlaceholderOnFocus` is true, the editable is partially non-clickable, because the click actually happens on the new `<span>` .

I'm a bit confused. If the placeholder (the span element) is not clickable, how can the click happen on the span element?

I think the placeholder should be ignored/"invisible" for clicks, and instead fall in the parent element. I'll have a look to fix this. In the meantime it might be worth creating a separate tracking issue for it.

**Comment by afercia** [comment]
> I'm a bit confused. If the placeholder (the span element) is not clickable, how can the click happen on the span element?

Language barriers 🙂 I mean it's not possible to click the field because the `<span>` sit on top of the field. I _think_ this was fixed in #17439 by using `pointer-events: none` ?

**Comment by ellatrix** [comment]
Yes, it should be fixed by this PR right?

**Comment by ellatrix** [comment]
The only remaining issue I see is that the caret is hidden after the placeholder is clicked. It seems to be positioned after the placeholder instead of the text node before.

**Comment by ellatrix** [comment]
Btw, this seems to work fine in Safari. In Chrome the caret becomes invisible.
