### PR TITLE
Backup and restore global `$post` when preloading API data

### LINKED ISSUE #7468: Editor screen is showing content from a different post.
**Describe the bug**
My Gutenberg Editor is constantly showing POST ID 9 of my posts table, rather than the `post` in the uri query string. 

This means I can't actually edit any page with Gutenberg?

**To Reproduce**
WP 4.9.6. Gutenberg 3.1.0
the primary site of a Multisite, with Custom Post types. (Worth saying that ID 9 is a custom post type, rather than just a post, and not the post type I'm intending to view!) 

Click to edit any post of _*any*_ post type. 

**Expected behavior**
The edit screen of the item you clicked on (and of the item that URI Query string suggests)

**Screenshots**
Not applicable/private information

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser CHROME
 - Version, latest

**Additional context**
- Gutenberg 3.1.0

### PR DESCRIPTION
**Pull request by danielbachhuber**
## Description

Backs up the global `$post` prior to calling `gutenberg_preload_api_request()`, and then restores the global `$post` afterwards. Doing so helps mitigate, but doesn't fix entirely, the impact of shortcode callbacks modifying the global `$post`.

If there's ever a better solution to this, the abstraction will likely be implemented in https://core.trac.wordpress.org/ticket/18408. However, a broader solution has the potential for lots of nasty side effects, so this localized solution seems most appropriate.

Fixes #7468

## How has this been tested?

0. Install and activate the [Display Posts Shortcode](https://wordpress.org/plugins/display-posts-shortcode/) plugin.
1. Make sure you have a few published posts.
2. Create a new draft post in the Classic Editor with the `[display-posts]` shortcode:

image

3. Open the draft post in Gutenberg.

Without this pull request, Gutenberg should open a seemingly random post. With this pull request, Gutenberg should open the correct post.

## Types of changes

Bug fix.

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: lib/client-assets.php [hunk 1]
```diff
@@ -1068,12 +1068,22 @@ function gutenberg_editor_scripts_and_styles( $hook ) {
 		sprintf( '/wp/v2/users/me?post_type=%s&context=edit', $post_type ),
 	);
 
+	// Ensure the global $post remains the same after
+	// API data is preloaded. Because API preloading
+	// can call the_content and other filters, callbacks
+	// can unexpectedly modify $post and cause the sky
```
Comment (tofumatt) [inline lib/client-assets.php]: "The sky to fall on Gutenberg's head" is definitely a cute turn-of-phrase, but it might confuse ESL folks or someone not familiar with what that means–and itself doesn't really add any info. I will push a comment tweak, but if you can add any additional context feel free 😄

Comment (danielbachhuber) [reply lib/client-assets.php]: Works for me!

**Comment by danielbachhuber** [comment]
@tofumatt Was that an approving review or do I need to re-request?

**Review by tofumatt — APPROVED** [review]
Ah, shoot, sorry, I meant to approve it. 😓

**Comment by tofumatt** [comment]
A note here: I'm not super-familiar with how the server-side of WordPress works, admittedly, but if plugins are getting data they don't expect after Gutenberg modifies things then this makes sense.

But I wonder if we just shouldn't be modifying this data in the first place in our hooks? Or is that impossible?

**Comment by danielbachhuber** [comment]
> But I wonder if we just shouldn't be modifying this data in the first place in our hooks? Or is that impossible?

The problem is that _plugins_ are modifying the data. This problem would exist in classic WordPress too, but classic WordPress doesn't execute this code path (rendering shortcodes in the editor context). If it did execute the code path, it could have the same problem.

**Comment by tofumatt** [comment]
Ah, gotcha! Thanks for the explanation, that's great. 👍
