### PR TITLE
Blocks: Introduce registerBlockTypeFromMetadata API

### LINKED ISSUE #23636: Block API: Add i18n support to `block.json` metadata file
Part of #16209.

There are some issues related to internationalization (i18n) support in newly introduced `block.json` metadata files that still need to be resolved.

There is a proposal in block registration metadata document that we still need to implement:
https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/block-api/block-metadata.md#internationalization

The good news is that WP-CLI has implemented (https://github.com/wp-cli/i18n-command/pull/210) native support for translatable strings extraction from `block.json` file in `i18n` command. It was based on the aforementioned RFC. It still needs to be released though.

## JavaScript

1. JSON imports work only in Node.js or with webpack tool. In Gutenberg, we use a custom plugin that inlines JSON in JavaScript as a plain object. We should decide whether we add the same plugin to the shared Babel preset (`@wordpress/babel-preset-default`) distributed as part of WordPress packages.
2. We miss the logic that wraps translatable fields with i18n functions, it still needs to be added. In the past, there was a failed attempt to build a Babel macro that would address both points but it wasn’t as straightforward as expected. We were afraid it could be a point of bugs when not configured properly. Related PR: #16088.

## PHP (Implemented)

The same issue applies to i18n handling on the PHP side of things. There was a new `register_block_type_from_metadata` utility function added in https://github.com/WordPress/gutenberg/pull/20794 to make it possible to register a new block type using `block.json` metadata file. It's still missing i18n support. 

### Temporary support

The temporary approach for 3rd party blocks that want to use `register_block_type_from_metadata` would be to keep everything that doesn't need to be translated in `block.json` and put the rest as additional params passed with 2nd argument, e.g.:

```php
register_block_type_from_metadata( __DIR__, array(
	'title'       => _x( 'My block', 'block title', 'my-plugin-domain' ),
	'description' => _x( 'My block is fantastic!', 'block description', 'my-plugin-domain' ),
	'keywords'    => array( _x( 'fantastic', 'block keywords', 'my-plugin-domain' ) ),
) );
```

### PR DESCRIPTION
**Pull request by gziolo**
## Description

Fixes #23636.

> 1. JSON imports work only in Node.js or with webpack tool. In Gutenberg, we use a custom plugin that inlines JSON in JavaScript as a plain object. We should decide whether we add the same plugin to the shared Babel preset (`@wordpress/babel-preset-default`) distributed as part of WordPress packages.
> 2. We miss the logic that wraps translatable fields with i18n functions, it still needs to be added. In the past, there was a failed attempt to build a Babel macro that would address both points but it wasn’t as straightforward as expected. We were afraid it could be a point of bugs when not configured properly. Related PR: #16088.

This PR proposes we introduce a new API method `registerBlockTypeFromMetadata` that processes metadata loaded from `block.json` and applies translations on the fly to the corresponding fields. 

## Dev Note

In JavaScript, you can use now `registerBlockTypeFromMetadata` method from `@wordpress/blocks` package to register a  block type using the metadata loaded from `block.json` file. All localized properties get automatically wrapped in `_x` (from `@wordpress/i18n` package) function calls similar to how it works in PHP with `register_block_type_from_metadata`. The only requirement is to set the `textdomain` property in the `block.json` file.

 **Example:**

`block.json`
```json
{
	"name": "my-plugin/translatable-block",
	"title": "My translatable block",
	"description": "My block with translatable metadata",
	"keywords": [ "translatable" ],
	"textdomain": "my-plugin"
}
```

`index.js`
```js
import { registerBlockTypeFromMetadata } from '@wordpress/blocks';
import Edit from './edit';
import metadata from './block.json';

registerBlockTypeFromMetadata( metadata, {
	edit: Edit,
	// ...other client-side settings
} );
```

## How has this been tested?

`npm run test-unit`

## Types of changes

New API.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by gziolo** [comment]
It's nearly ready. I still have to find out how to dynamically translate the value read from the `block.json`. Covering it with unit tests might be yet another challenge as it needs some mocking.

File: packages/blocks/src/api/registration.js [hunk 1]
```diff
@@ -310,6 +316,114 @@ export function registerBlockType( name, settings ) {
...
+ *
+ * @return {string|string[]|Object[]} Translated setting.
+ */
+function translateBlockSettingUsingI18nSchema(
+	i18nSchema,
+	settingValue,
+	textdomain
+) {
+	if ( isString( i18nSchema ) && isString( settingValue ) ) {
+		// eslint-disable-next-line @wordpress/i18n-no-variables, @wordpress/i18n-text-domain
```
Comment (gziolo) [inline packages/blocks/src/api/registration.js:334]: @swissspidy, do we need to do something special to ensure this particular translation call is ignored during WP-CLI processing?

File: packages/blocks/src/api/i18n-block.json [hunk 2]
```diff
@@ -0,0 +1,12 @@
+{
```
Comment (gziolo) [inline packages/blocks/src/api/i18n-block.json:1]: @gwwar, should we put here `variations` as well which we plan to integrate with `block.json` soon?

There is one more place where we would need to put it on the allow list.

Comment (gwwar) [reply packages/blocks/src/api/i18n-block.json:1]: I think it'd be worth a try, will it affect the needed PR order?

Comment (gziolo) [reply packages/blocks/src/api/i18n-block.json:1]: Let me think about what we need to change to enable `variations` in `block.json` on the PHP side. As far as I can tell, it's mostly the same set of changes like here now that `WP_Block_Type` and the REST API endpoint support block variations. Given that you won't be able to register block variations on the server until WP 5.8 is out the order shouldn't matter at all. We also have a mechanism in place that favors definitions from the server but fallback to the client when not set there. I think it's safe to change here at the same time 👍🏻

Comment (gziolo) [reply packages/blocks/src/api/i18n-block.json:1]: Added in https://github.com/WordPress/gutenberg/pull/30293/commits/b851c2f3e3e91e8d200ba1036e3d7c6f17539d3a. Every change to docs get synced with https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/ so I will open another PR that covers the part that describes `variations` in the `block.json` file. We should plan to merge it around WordPress 5.8 RC.1 when all Dev Notes get published.

File: packages/blocks/src/api/i18n-block.json [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+	"title": "block title",
+	"description": "block description",
+	"keywords": [ "block keyword" ],
+	"styles": [
+		{
+			"label": "block style label"
+		}
+	],
+	"variations": [
```
Comment (gziolo) [inline packages/blocks/src/api/i18n-block.json:10]: @nosolosw and @jorgefilipecosta – this i18n schema format is very flexible, it works with quite complex structures like the one for block variations.

**Comment by gziolo** [comment]
I opened https://github.com/WordPress/gutenberg/pull/31120 that is based on this branch and it presents how it will simplify handling blocks:

```diff
diff --git a/packages/block-library/src/archives/block.json b/packages/block-library/src/archives/block.json
index d35f8b05001c..0c94c4b44b35 100644
--- a/packages/block-library/src/archives/block.json
+++ b/packages/block-library/src/archives/block.json
@@ -1,7 +1,10 @@
 {
 	"apiVersion": 2,
 	"name": "core/archives",
+	"title": "Archives",
+	"description": "Display a monthly archive of your posts.",
 	"category": "widgets",
+	"textdomain": "default",
 	"attributes": {
 		"displayAsDropdown": {
 			"type": "boolean",
diff --git a/packages/block-library/src/archives/index.js b/packages/block-library/src/archives/index.js
index 6bfdbef7abce..e1f01f30a718 100644
--- a/packages/block-library/src/archives/index.js
+++ b/packages/block-library/src/archives/index.js
@@ -2,7 +2,6 @@
  * WordPress dependencies
  */
 import { archive as icon } from '@wordpress/icons';
-import { __, _x } from '@wordpress/i18n';
 
 /**
  * Internal dependencies
@@ -15,8 +14,6 @@ const { name } = metadata;
 export { metadata, name };
 
 export const settings = {
-	title: _x( 'Archives', 'block title' ),
-	description: __( 'Display a monthly archive of your posts.' ),
 	icon,
 	example: {},
 	edit,
```

File: packages/blocks/src/api/registration.js (hunk 1 above)
Comment (swissspidy) [reply packages/blocks/src/api/registration.js:334]: String extraction will skip anything that‘s not a string literal, so no.

File: packages/blocks/src/api/i18n-block.json (hunk 3 above)
Comment (jorgefilipecosta) [reply packages/blocks/src/api/i18n-block.json:10]: That's good news :)

File: packages/blocks/src/api/registration.js (hunk 1 above)
Comment (gziolo) [reply packages/blocks/src/api/registration.js:334]: Thanks!

File: packages/blocks/src/api/registration.js [hunk 4]
```diff
@@ -310,6 +316,115 @@ export function registerBlockType( name, settings ) {
...
+		return _x( settingValue, i18nSchema, textdomain );
```
Comment (jorgefilipecosta) [inline packages/blocks/src/api/registration.js:335]: Aren't we going to cause a string extraction because of the usage of _x function? Maybe because we are using variables the extraction does not happen? On the PHP side, we use an internal function to avoid this issue.

Comment (jorgefilipecosta) [inline packages/blocks/src/api/registration.js:335]: Things like the block description currently don't have a context and now are going to have one. I guess their current translation will be invalidated, should we make some dev note or something equivalent to dev note for translators?

File: packages/blocks/src/api/registration.js [hunk 5]
```diff
@@ -310,6 +316,115 @@ export function registerBlockType( name, settings ) {
...
+) {
+	const allowedFields = [
+		'apiVersion',
+		'title',
+		'category',
+		'parent',
+		'icon',
+		'description',
+		'keywords',
+		'attributes',
```
Comment (gwwar) [inline packages/blocks/src/api/registration.js:397]: Does i18n support get added for string default values? For example let's say we have
```
"attributes": {
		"label": {
			"type": "string",
                         "default": "Home",
		},
		"opensInNewTab": {
			"type": "boolean",
                         "default": false,
		},
}
```

**Comment by gwwar** [comment]
Let us know what type of feedback/testng you'd like on this one @gziolo to help move this forward.

File: packages/blocks/src/api/registration.js (hunk 4 above)
Comment (jorgefilipecosta) [inline packages/blocks/src/api/registration.js:335]: In the branch of PR https://github.com/WordPress/gutenberg/pull/31120, I made a simple test and replaced "return _x( settingValue, i18nSchema, textdomain );" with "return 'ok';". Nothing changed. With this change shouldn't all the block titles and descriptions appear as "ok"?

File: packages/blocks/src/api/registration.js (hunk 5 above)
Comment (gziolo) [reply packages/blocks/src/api/registration.js:397]: No, we should rather avoid it because it won't produce predictable content. Depending on the language picked in the admin UI, you could get a different output for the same block. We need to remember also that, the value of an attribute when strictly equal to the default value it doesn't get stored in HTML comment of the block definition. The other challenge is, how would you decide which `default` values need to be translated and for which blocks?

File: packages/blocks/src/api/registration.js (hunk 4 above)
Comment (gziolo) [reply packages/blocks/src/api/registration.js:335]: See comment from @swissspidy in https://github.com/WordPress/gutenberg/pull/30293#discussion_r618471970:

> String extraction will skip anything that‘s not a string literal

Comment (gziolo) [reply packages/blocks/src/api/registration.js:335]: As far as I understand it will be automatically handled during the WordPress release cycle, and it's the same process that happens for every newly added or updated translation. We did a batch updated of UI labels in the block editor in the past, and I don't remember any dev notes related to that.

Comment (gziolo) [reply packages/blocks/src/api/registration.js:335]: It might require adding a fallback to read the value from the client when it isn't provided from the server. It would be useful for WordPress 5.7 when using with the Gutenberg plugin.

Comment (gziolo) [reply packages/blocks/src/api/registration.js:335]: I investigate it further and it's a different use case than `apiVersion` setting that I was referring to:

https://github.com/WordPress/gutenberg/blob/c047e2716149c794eebff3c2c002f66a6f546f59/packages/blocks/src/api/registration.js#L167-L181

We register all blocks on the server and we set now all translatable fields there and they are exposed to the client. The values from the server take precedence to respect all PHP filters that could get applied to the metadata. It's the same data after all, so there is no reason to override it with the same metadata read on the client. 

To test it, you could change the method I embedded above and enforce that those fields get overridden with the values loaded on the client. Maybe you could also tweak `register_block_type_from_metadata` calls on the server to somehow ignore translatable fields using [`block_type_metadata_settings`](https://developer.wordpress.org/reference/hooks/block_type_metadata_settings/) filter, but you rather would need to prevent registration of the block you want to test with on the server.

**Comment by gziolo** [comment]
> Let us know what type of feedback/testng you'd like on this one @gziolo to help move this forward.

I opened https://github.com/WordPress/gutenberg/pull/31120 which is based on this branch that moves all translatable fields to `block.json`. The challenge with testing is that it's going to use all metadata from the server and happy all translations there for the WordPress scenario. To test how it works on the client you can check with the React Native mobile app or with Storybook (`npm run storybook:build`). Storybook doesn't apply translations but it could be tested with i18n hooks like in unit tests or with the changes that @jorgefilipecosta mentioned in https://github.com/WordPress/gutenberg/pull/30293#discussion_r619454350.

File: packages/blocks/src/api/registration.js (hunk 4 above)
Comment (jorgefilipecosta) [reply packages/blocks/src/api/registration.js:335]: Thank you for the clarification 👍

**Review by jorgefilipecosta — APPROVED** [review]
LGTM 👍

File: packages/blocks/src/api/registration.js (hunk 5 above)
Comment (gwwar) [reply packages/blocks/src/api/registration.js:397]: > We need to remember also that, the value of an attribute when strictly equal to the default value it doesn't get stored in HTML comment of the block definition.

🤔 good to highlight this case.

>  The other challenge is, how would you decide which default values need to be translated and for which blocks?

If we wanted to support it, we could add an additional attribute. I found that I did need it in one of the blocks, but the behavior can also be simulated with a `useEffect` hook in the block.

Comment (gziolo) [reply packages/blocks/src/api/registration.js:397]: > If we wanted to support it, we could add an additional attribute. I found that I did need it in one of the blocks, but the behavior can also be simulated with a `useEffect` hook in the block.

When using a side effect as part of the React component lifecycle, you are updating an attribute that might create an undo level so you need to use a special version of the store action that mitigates that. Another approach is to use a block variation that gets applied as the default one in the inserter. The benefit of that is that it sets attributes dynamically when inserting the block.

**Review by gwwar — APPROVED** [review]
Stepping through the code I think this looks correct ✅

File: packages/blocks/src/api/registration.js [hunk 6]
```diff
@@ -310,6 +316,115 @@ export function registerBlockType( name, settings ) {
...
+		'usesContext',
+		'supports',
+		'styles',
+		'example',
+		'variations',
+	];
+
+	const settings = pick( metadata, allowedFields );
+
+	if ( textdomain ) {
```
Comment (fluiddot) [inline packages/blocks/src/api/registration.js:408]: As far as I checked, in the native version [we set the locale data without defining a text domain](https://github.com/WordPress/gutenberg/blob/329fe98df660b0da9b3f149ce34fce2bda1b805d/packages/react-native-editor/src/index.js#L143), not sure if this could be a problem if in the future we move some of the fields to the `block.json` file to do the on fly translation.

Comment (gziolo) [reply packages/blocks/src/api/registration.js:408]: `default` is the default text domain, so this is what I'm using in https://github.com/WordPress/gutenberg/pull/31120. I think it should be fine.

File: packages/blocks/src/api/registration.js (hunk 1 above)
Comment (ocean90) [reply packages/blocks/src/api/registration.js:334]: @gziolo How are the translations supposed to be in `wp.i18n` without a specific `wp.i18n.setLocaleData()` call? The strings from the block.json aren't assigned to a JavaScript file thus not automatically part of a JSON translation file. But I might be missing something here? Or are we fully relying on server-side registration for the strings?

Comment (gziolo) [reply packages/blocks/src/api/registration.js:334]: In the context of WordPress core, they are always registered on the server and translated there before passed to the client. At the moment, there is a temporary JS method `unstable__bootstrapServerSideBlockDefinitions` that takes care of setting data generated with PHP. In the future, we are going to use the REST API endpoint for blocks, but the general idea is going to be the same - translations get applied when registering a block on the server.

In practice, this implementation is a fallback for everything else that depends only on JavaScript:
- standalone block editor like Storybook integration (although this is a bad example as it is never translated)
- native mobile apps still consume only JavaScript codebase so they have to collect all translations themselves (it might change when we start using the REST API endpoint for blocks)
