### PR TITLE
Packages[core-data]: Change "include" type in getQueryParts

### LINKED ISSUE #27771: getEntityRecords() for 'attachment' post type no longer works with Wordpress 5.6
**Describe the bug**
I have been making use of getEntityRecords() to fetch image data to display in some custom Gutenberg blocks. They worked fine until I upgraded to Wordpress 5.6. Now when I make calls with getEntityRecords() I get the following errors:
"Uncaught TypeError: fe(...) is null"
"Uncaught (in promise) TypeError: fe(...) is null"

However, I can successfully fetch image data by using getMedia(). This was the behavior I experienced on my live and staging sites. I deactivated all plugins and changed to Twentytwentyone theme and still had the issue. So I installed a fresh copy of Wordpress locally and went through the following steps, which produced the error as well.

**To reproduce**
1. Make a clean Wordpress installation
2. Upload an image to the media library and take note of it's post_id (let's say it's `6`)
3. Open the page editor and the Javascript console then type in `wp.data.select('core').getEntityRecords('postType', 'attachment', { include: 6 })`
5. Instead type in `wp.data.select('core').getMedia(6)` (you'll likely get 'undefined' the first time while it's fetching the media item, but if you re-enter you should be able to see the details for that image)

**Expected behavior**
I expected to be able to continue using getEntityRecords() within my custom blocks like I did before. I noticed that a similar error would occur fetching pages (e.g. `wp.data.select('core').getEntityRecords('postType', 'page', { include: 3912 } )`) but if I passed the post_id as a string in the query parameter it works (e.g. `wp.data.select('core').getEntityRecords('postType', 'page', { include: '3912' } )`. However, passing the attachment ID as a string always returns `null`

**Screenshots**
Firefox console error:
Screen Shot 2020-12-16 at 13 31 47

Chrome console error, slightly different message:
Screen Shot 2020-12-16 at 13 54 12

This screenshot shows the successful getMedia() call for the same image id:
Screen Shot 2020-12-16 at 13 54 43

**Editor version (please complete the following information):**
- WordPress version: 5.6
- Default block editor
- OSX 10.15.7
- Firefox 83 and Chrome 83

### PR DESCRIPTION
**Pull request by mauriac**
## What?
Convert the value of the parameter include into a string when it's
a number.

## Why?
fixes: #27771

This bug is backwards compatibility issue

## Testing Instructions
1. Make a clean Wordpress installation
2. Upload an image to the media library and take note of it's post_id (let's say it's 6)
3. Open the page editor and the Javascript console then type in wp.data.select('core').getEntityRecords('postType', 'attachment', { include: 6 })
4. wp.data.select('core').getEntityRecords('postType', 'attachment', { include: '6' })
5. steps 3 and 4 should return the same result : the attachment data

**Head's up:** steps 3 or 4 could return null first, and then the second time the attachment data after the request had resolved.

### CODE REVIEW

**Comment by getdave** [comment]
@adamziel might be a good person to take a look at this one if he has time alongside his duties as Editor release lead.

File: packages/core-data/src/queried-data/get-query-parts.js [hunk 1]
```diff
@@ -80,6 +80,9 @@ export function getQueryParts( query ) {
 
 				// Two requests with different include values cannot have same results.
 				if ( key === 'include' ) {
+					if ( typeof value === 'number' ) {
+						value = value.toString();
+					}
```
Comment (adamziel) [inline packages/core-data/src/queried-data/get-query-parts.js:85]: This would work! Although I'd prefer to have this in `getNormalizedCommaSeparable` which already handles types conversion.

Comment (adamziel) [reply packages/core-data/src/queried-data/get-query-parts.js:85]: Actually, thinking about this more, `getNormalizedCommaSeparable` is also used in a few different places where such behavior could be unexpected. Let's move forward with this version then. Thank you for contributing!

**Review by adamziel — APPROVED** [review]

**Comment by adamziel** [comment]
I cherry picked this change into `wp/6.0` branch to be included in WordPress 6.0 Beta 4 on Monday: 0bfa48c7e9
