### PR TITLE
Fix: DataViews: Layout resets for patterns each time a new pattern category is selected.

### LINKED ISSUE #63393: DataViews: Layout resets for patterns each time a new pattern category is selected
### Description

Each time a pattern category is selected, the layout resets from 'Table' to 'Grid'.

This behaves differently compared to Templates or Pages, where selecting different categories on the left retains the chosen layout.

### Step-by-step reproduction instructions

1. Open the site editor
2. Go to the patterns screen
3. Change the layout to Table
4. Choose a different pattern category

Expected: The layout stays as 'Table'
Actual: The layout changes back to 'Grid'

### Screenshots, screen recording, code snippet

_No response_

### Environment info

trunk
Brave / Mac OS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Fixes: https://github.com/WordPress/gutenberg/issues/63393

We were forcing the grid layout each time a pattern category was changed, and all the other defaults. This PR fixes the issue by keeping the previous view, and just resetting the page to 1 as the comment there indicated.

## Testing Instructions
Go to the patterns page.
Switch to the table layout, change the pattern category, and verify that the table layout is active.

### CODE REVIEW

**Review by jameskoster — APPROVED** [review]
Confirming this is working.

File: packages/edit-site/src/components/page-patterns/index.js [hunk 1]
```diff
@@ -351,9 +351,12 @@ export default function DataviewsPatterns() {
...
 	useEffect( () => {
 		if ( previousCategoryId !== categoryId ) {
-			setView( DEFAULT_VIEW );
+			setView( {
+				...view,
+				page: 1,
+			} );
 		}
-	}, [ categoryId, previousCategoryId ] );
+	}, [ categoryId, previousCategoryId, view ] );
```
Comment (Mamaduka) [inline packages/edit-site/src/components/page-patterns/index.js]: Passing the same state as a dependency as the effect updates could easily lead to infinite loops, especially when this state is an object. Only having a category check prevents that here.

Let's use the [state updater function](https://react.dev/reference/react/useState#updating-state-based-on-the-previous-state) instead - `setView( ( prevView ) => ( { ...prevView, page: 1 } ) );`.

Comment (Mamaduka) [reply packages/edit-site/src/components/page-patterns/index.js]: Updated in [0383686](https://github.com/WordPress/gutenberg/pull/63711/commits/03836866a900df683edb5cb5c04e0b27e315dd44).

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for the fix 👍 

LGTM!

| Before | After |
|---|---|
| <video src="https://github.com/user-attachments/assets/1af57ebd-dc1d-41b4-b6fb-d5fd8a17e64a" /> | <video src="https://github.com/user-attachments/assets/dccf78e3-6457-48aa-a3dd-55c372c5c004" /> |

**Comment by jorgefilipecosta** [comment]
Thank you for helping this PR get merged @Mamaduka, @aaronrobertshaw, and @jameskoster !

**Comment by ellatrix** [comment]
Does this need to be backported?
