### PR TITLE
Enforce @since tags in block-library/src/*/*.php files

### LINKED ISSUE #55777: Tagging all functions in the wp-includes/blocks/ directory with @since tags
### Description

While preparing for WP 6.4 RC3 a discussion was brought up about filters and functions missing a `@since` tag in the directory `wp-includes/blocks`. This ticket is for a general discussion on the topic.

Highlights from the slack-discussion 
`I think they should still have an @since when the come over to WordPress but I don't think this needs to interrupt or stop RC prep` by @aaronjorbin 

`Following up on the discussion: Very few of the functions in that directory have @since annotations. Thinking if they should be there, then would be worth adding them to all of the functions for consistency.` @hellofromtonya 

Pinging @mukeshpanchal27 who also expressed opinions.

For me as a novice developer I think the `@since` tags are helpful for tracking origins and how long things have been in core. And I think missing since-tags are breaking the docblock standard in core. But thats maybe an incorrect asumption of me.

### Step-by-step reproduction instructions

.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by anton-vlasenko**
## What?
This PR introduces a new sniff called `FunctionCommentSinceTagSniff` to ensure that PHP functions have a valid `@since` tag in the docblock.

The sniff skips checking files in `__experimental` block-library packages.

Fixes https://github.com/WordPress/gutenberg/issues/55777.

## Why?
`@since` tags are helpful for tracking origins and how long things have been in Core.

## How?
- [x] Defines a new sniff class `FunctionCommentSinceTagSniff` within the `GutenbergCS\Gutenberg\Sniffs\Commenting` namespace.
- [x] Adds unit tests for the `FunctionCommentSinceTagSniff` sniff.
- [x] Updates existing `block-library` functions so that they have valid `@since` tags.

## Testing Instructions
1. Try to define a PHP function somewhere in the `block-library/src/*/*.php` without a `@since` tag.
2. Make sure that CI checks fail.

## Screenshots or Screencast

### CODE REVIEW

**Comment by anton-vlasenko** [comment]
@kebbet @gziolo I would appreciate your feedback and thoughts.
Thank you.

File: packages/block-library/src/media-text/index.php [hunk 1]
```diff
@@ -8,6 +8,8 @@
 /**
  * Renders the `core/media-text` block on server.
  *
+ * @since 6.6.0
```
Comment (anton-vlasenko) [inline packages/block-library/src/media-text/index.php:11]: This is the only place I'm not sure about. These functions haven't been included in WordPress Core yet.

File: packages/block-library/src/media-text/index.php [hunk 2]
```diff
@@ -54,6 +56,8 @@ function render_block_core_media_text( $attributes, $content ) {
 
 /**
  * Registers the `core/media-text` block renderer on server.
+ *
+ * @since 6.6.0
```
Comment (anton-vlasenko) [inline packages/block-library/src/media-text/index.php:60]: This is the only place I'm not sure about. These functions haven't been included in WordPress Core yet.

Comment (gziolo) [reply packages/block-library/src/media-text/index.php:60]: I don't see it in WordPress core, so that would be correct. The PHP file was added 5 days ago 👍🏻

File: phpcs.xml.dist [hunk 3]
```diff
@@ -172,4 +172,8 @@
 			</property>
 		</properties>
 	</rule>
+	<rule ref="Gutenberg.Commenting.FunctionCommentSinceTag">
+		<!-- The sniff ensures that functions have a valid @since tag but skips checking experimental packages. -->
```
Comment (gziolo) [inline phpcs.xml.dist]: Nice!

In another PR, we should also include `/pacakages/block-serialization-default-parser/.+/*\.php$`.

https://github.com/WordPress/wordpress-develop/blob/b1b97f96727f137210b942f00f85fc6449033d1d/tools/webpack/packages.js#L128-L135

There are two more special core blocks:
- `widgets/src/blocks/legacy-widget/index.php`
- `widgets/src/blocks/widget-group/index.php`

https://github.com/WordPress/wordpress-develop/blob/b1b97f96727f137210b942f00f85fc6449033d1d/tools/webpack/blocks.js#L38-L48

@youknowriad, what do we miss here? Should we discuss in a separate issue what else we could copy from Gutenberg to the core and put under more pressure to follow WP coding standards? 😄

File: test/php/gutenberg-coding-standards/Gutenberg/Tests/Commenting/FunctionCommentSinceTagUnitTest.php [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+final class FunctionCommentSinceTagUnitTest extends AbstractSniffUnitTest {
+
+	/**
+	 * Returns the lines where errors should occur.
+	 *
+	 * @return array <int line number> => <int number of errors>
+	 */
+	public function getErrorList() {
+		return array(
+			9  => 1,
```
Comment (gziolo) [inline test/php/gutenberg-coding-standards/Gutenberg/Tests/Commenting/FunctionCommentSinceTagUnitTest.php:28]: Maybe it would be good to document that only functions are covered at the moment.

It's annotated in the sniff, but it might not be immediately obvious when looking at the test in isolation.

File: test/php/gutenberg-coding-standards/Gutenberg/Sniffs/Commenting/FunctionCommentSinceTagSniff.php [hunk 5]
```diff
@@ -0,0 +1,162 @@
...
+		);
+	}
+
+	/**
+	 * Checks if the current package is experimental.
+	 *
+	 * @param File $phpcsFile The file being scanned.
+	 * @return bool Returns true if the current package is experimental.
+	 */
+	private static function is_experimental_package( File $phpcsFile ) {
```
Comment (gziolo) [inline test/php/gutenberg-coding-standards/Gutenberg/Sniffs/Commenting/FunctionCommentSinceTagSniff.php]: I think the name should get updated to:
```suggestion
	private static function is_experimental_block( File $phpcsFile ) {
```

Individual blocks only can be experimental, the block library package is stable.

**Review by gziolo — APPROVED** [review]
Impressive detective work adding all missing `@since` annotations. It must have taken some time to track down the proper versions. I'm not going to validate these numbers and will put trust in you and the collective knowledge of the community that can always follow-up to correct them 😄 

The code looks good. I'm starting to get more familiar with PHP sniffs and more open to approve 😄 

I left a comment with a suggestion to cover more files that I know we sync with WP core, but it isn't a blocker. In practice, it would require some changes to when to run `is_experimantal_package`, as it only applies to the `packages/block-library`. So maybe, another PR.

**Comment by kebbet** [comment]
What a detectives work! Great with progress on the @since-tag, and creating a sniff for it! Wow! 👏🏼

File: phpcs.xml.dist (hunk 3 above)
Comment (youknowriad) [reply phpcs.xml.dist]: It is interesting that @getdave opened a discussion about this PR yesterday https://github.com/WordPress/gutenberg/discussions/59786

--- 

Yeah, so these files would be good to address next but I wonder if all the php files in Gutenberg should have these rules applied (Manual backports include a lot of copy/pasting of php files)

**Comment by youknowriad** [comment]
Awesome work here.

File: test/php/gutenberg-coding-standards/Gutenberg/Sniffs/Commenting/FunctionCommentSinceTagSniff.php (hunk 5 above)
Comment (anton-vlasenko) [reply test/php/gutenberg-coding-standards/Gutenberg/Sniffs/Commenting/FunctionCommentSinceTagSniff.php]: I agree, I've used some vague terminology here. Fixed in 0a615920215e8a4fc71a734992afa59406920def.

File: test/php/gutenberg-coding-standards/Gutenberg/Tests/Commenting/FunctionCommentSinceTagUnitTest.php (hunk 4 above)
Comment (anton-vlasenko) [reply test/php/gutenberg-coding-standards/Gutenberg/Tests/Commenting/FunctionCommentSinceTagUnitTest.php:28]: Fixed in 9bf6c1868644024f75f08d5b5a3da7ffbf614f4a.

File: phpcs.xml.dist (hunk 3 above)
Comment (anton-vlasenko) [reply phpcs.xml.dist]: Thank you for your feedback, @gziolo. Your review is greatly appreciated.
I'd prefer to implement checking files in `/pacakages/block-serialization-default-parser` and other folders in a follow-up issue as this would allow for incremental improvements while ensuring that the enforcement of `@since` tags in the Block Library is already in place.

Follow-up issue: https://github.com/WordPress/gutenberg/issues/59826

Comment (gziolo) [reply phpcs.xml.dist]: Yes, it is definitely another issue/PR. We better introduce these improvements gradually so we can start catching issues for covered files.

**Comment by anton-vlasenko** [comment]
> . I'm not going to validate these numbers and will put trust in you and the collective knowledge of the community that can always follow-up to correct them 😄

I think/hope these numbers should be pretty accurate.
I've downloaded all major releases and verified the presence of these functions in the respective releases.
I didn't find it necessary to check point releases, as they are primarily focused on bug fixes rather than introducing new functionality.

**Review by getdave — COMMENTED** [review]
Great work. I can't believe you found all the `@since` releases for al those 🤯 

I'm of the opinion we should ship and if we find any that are inaccurate we can modify them as needed. 

I would encourage you to leave your opinion on [the discussion I raised](https://github.com/WordPress/gutenberg/discussions/59786) about the need to implement these exact types of automated linting in the project. It would be hugely valuable if you were able to continue down this route.

Thanks again

**Comment by swissspidy** [comment]
A custom sniff for enforcing `@since` tags sounds really useful!

I definitely encourage you to contribute this to [WPCS](https://github.com/WordPress/WordPress-Coding-Standards), as this is important for WordPress core as well and even plugins and themes. It's the right thing to do.

See https://github.com/WordPress/WordPress-Coding-Standards/issues/1994

**Review by swissspidy — COMMENTED** [review]
A custom sniff for enforcing `@since` tags sounds really useful!

I definitely encourage you to contribute this to [WPCS](https://github.com/WordPress/WordPress-Coding-Standards), as this is important for WordPress core as well and even plugins and themes. It's the right thing to do.

See https://github.com/WordPress/WordPress-Coding-Standards/issues/1994

**Comment by anton-vlasenko** [comment]
> Great work. I can't believe you found all the `@since` releases for al those 🤯
> 
> I'm of the opinion we should ship and if we find any that are inaccurate we can modify them as needed.
> 
> I would encourage you to leave your opinion on [the discussion I raised](https://github.com/WordPress/gutenberg/discussions/59786) about the need to implement these exact types of automated linting in the project. It would be hugely valuable if you were able to continue down this route.
> 
> Thanks again

Thank you, @getdave!
I'm glad you think we should proceed with this PR.
I will look into the issue you mentioned.

> A custom sniff for enforcing `@since` tags sounds really useful!
> 
> I definitely encourage you to contribute this to [WPCS](https://github.com/WordPress/WordPress-Coding-Standards), as this is important for WordPress core as well and even plugins and themes. It's the right thing to do.
> 
> See [WordPress/WordPress-Coding-Standards#1994](https://github.com/WordPress/WordPress-Coding-Standards/issues/1994)


Thank you for your suggestion, @swissspidy.
I've already attempted to submit some of my other sniffs to WPCS.
However, the sniff I tried to submit was Gutenberg-specific, and I received feedback from the WPCS maintainers stating that it doesn't belong in the WPCS package (meaning it won't be useful for other WordPress plugins/sites).
I agree with that assessment.
This particular sniff is also Gutenberg-specific, as it checks whether the current block is experimental.
However, if I ever work on a sniff that is more universally applicable, I will consider submitting it to WPCS.
I think that's great idea.

**Comment by swissspidy** [comment]
@anton-vlasenko Yes obviously the sniffs would need to be made generic. In this instance for example there is no reason to include GB-specific stuff in it. I would just make the sniff enforce `@since` annotations for all functions. You can then either a) create a custom sniff in GB that extends the generic one or b) just exclude experimental block files in the config file. That seems pretty straightforward.

Agan, especially core itself would be really benefit from this and expanding the scope of the contribution would demonstrate the unity of the project instead of working in isolation. Just figured I'd chime in to share a core perspective here.

If you don't have the capacity for this I totally understand of course, so maybe we can start with leaving a comment on that issue.

**Comment by getdave** [comment]
> Agan, especially core itself would be really benefit from this and expanding the scope of the contribution would demonstrate the unity of the project instead of working in isolation. Just figured I'd chime in to share a core perspective here.

Yes please 👍  The more we can unify the standards then the easier it will make syncing code from Gutenberg repo to the WP Core repo. 

Personally I feel like exploring these opportunities would be a great use of contributor time as - based on my experience in this cycle - I see we all spend too much time on resolving coding standards issues which should be automated.

It's my opinion that we should consider them _the same_ codebase in many ways. Therefore the more alignment we can bring the better. The more of this that is automated the better.

Again I'd love to hear from folks on https://github.com/WordPress/gutenberg/discussions/59786.

**Comment by anton-vlasenko** [comment]
> Agan, especially core itself would be really benefit from this and expanding the scope of the contribution would demonstrate the unity of the project instead of working in isolation. Just figured I'd chime in to share a core perspective here.

@swissspidy I will think about submitting this sniff to WPCS when it becomes more stable. You've made me reconsider my viewpoint on the matter, and I agree that Core could benefit from it. Thank you for sharing your thoughts.

**Comment by anton-vlasenko** [comment]
> > Agan, especially core itself would be really benefit from this and expanding the scope of the contribution would demonstrate the unity of the project instead of working in isolation. Just figured I'd chime in to share a core perspective here.

Thank you for sharing your thoughts, @getdave. I appreciate it. I will consider submitting this sniff to WPCS after https://github.com/WordPress/gutenberg/issues/59826 is done.
