### PR TITLE
`ColorPalette`: Display checkered preview background when `value` is transparent

### LINKED ISSUE #42230: ColorPalette: Using 'transparent' as color value produces unexpected preview background
### Description

When I pass 'transparent' as a potential color to `ColorPalette`, it unexpectedly shows a white background:

image

I would expect the background to be representative of the color, similar to other colors:

image

Related #42170

### Step-by-step reproduction instructions

```js
<PanelColorSettings
	title={ __( 'Color Settings' ) }
	colorSettings={ [
		{
			label: __( 'Background Color' ),
			colors: [
				{
					name: __( 'Dark Gray' ),
					slug: 'dark-gray',
					color: '#111',
				}
				{
					name: __( 'Transparent' ),
					slug: 'transparent',
					color: 'transparent',
				}
			],
		},
	] }
/>
```

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by danielbachhuber**
## What?

Avoids styling `background` when the provided `value` is transparent (either `transparent`, or a RGBA/HEX value with transparent alpha channel).

### After

image

### Before

image

## Why?

Fixes #42230

### CODE REVIEW

**Comment by annezazu** [comment]
@WordPress/gutenberg-design for thoughts here :)

**Comment by jameskoster** [comment]
Makes sense to me 👍 

It would be good to fix this holistically to account for alpha channels:

Screenshot 2022-07-12 at 10 37 52

**Comment by danielbachhuber** [comment]
> It would be good to fix this holistically to account for alpha channels:

@jameskoster What's the best way to detect the alpha channel?

**Comment by jameskoster** [comment]
Sorry, I'm not sure 🙈

**Comment by danielbachhuber** [comment]
> > It would be good to fix this holistically to account for alpha channels:
> 
> What's the best way to detect the alpha channel?

@jameskoster It turned out to be pretty simple! `colord( currentValue ).alpha()`

Updated in bcfb85ab5b

**Review by mtias — APPROVED** [review]
Looks good to me. @jameskoster we should probably update the transparent circle in the palette to match the newer transparent grid design

File: packages/components/src/color-palette/test/utils.ts [hunk 1]
```diff
@@ -21,4 +24,16 @@ describe( 'ColorPalette: Utils', () => {
 			expect( result ).toBe( 'Blue' );
 		} );
 	} );
+	describe( 'showTransparentBackground', () => {
+		test( 'should return true for transparent colors', () => {
+			expect( showTransparentBackground( 'transparent' ) ).toBe( true );
+			expect( showTransparentBackground( '#75757500' ) ).toBe( true );
+		} );
+
+		test( 'should return true for transparent colors', () => {
```
Comment (mirka) [inline packages/components/src/color-palette/test/utils.ts]:
```suggestion
		test( 'should return false for non-transparent colors', () => {
```

File: packages/components/src/color-palette/index.js [hunk 2]
```diff
@@ -162,6 +162,10 @@ export const extractColorNameFromCurrentValue = (
 	return __( 'Custom' );
 };
 
+export const showTransparentBackground = ( currentValue ) => {
+	return colord( currentValue ).alpha() === 0;
+};
```
Comment (mirka) [inline packages/components/src/color-palette/index.js]: Can we add handling (and a test case) for an `undefined` color value? It will be undefined when the "Clear" button is clicked.

**Review by mirka — COMMENTED** [review]
Thanks for the fix! If you could add a quick [changelog entry](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md) before merging, that would be great.

---

In a follow-up, we may want to look into tweaking the background implementation so the checkered background can be seen through a semi-transparent color. This is already the case with the circular swatch:

The checkered transparent background cannot be seen through a translucent red color

File: packages/components/src/color-palette/index.js (hunk 2 above)
Comment (danielbachhuber) [reply packages/components/src/color-palette/index.js]: > Can we add handling (and a test case) for an `undefined` color value? It will be undefined when the "Clear" button is clicked.

@mirka Yep, did with d482da9668142d7b8fefb39ec2f59487c9d11b10

**Comment by danielbachhuber** [comment]
> Thanks for the fix! If you could add a quick [changelog entry](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md) before merging, that would be great.

@mirka You're welcome 😄 Did with 23f9b5188933363d350d1dee408a71119fed3869

> In a follow-up, we may want to look into tweaking the background implementation so the checkered background can be seen through a semi-transparent color. This is already the case with the circular swatch:

I actually looked into this. I think it will involve a bit of CSS retooling, though. I didn't feel comfortable contributing the change because I felt like it might delay the review process (and solving 'transparent' is my immediate need).

File: packages/components/src/color-palette/test/utils.ts [hunk 3]
```diff
@@ -21,4 +24,19 @@ describe( 'ColorPalette: Utils', () => {
 			expect( result ).toBe( 'Blue' );
 		} );
 	} );
+	describe( 'showTransparentBackground', () => {
+		test( 'should return undefined for transparent colors', () => {
+			expect( undefined ).toBe( undefined );
+		} );
```
Comment (mirka) [inline packages/components/src/color-palette/test/utils.ts]: Ah sorry this was unclear, I think the behavior we want is for it to return true:

```suggestion
		test( 'should return true for undefined color values', () => {
			expect( undefined ).toBe( true );
		} );
```

The fact that it "works" as expected with the current `background` implementation is only coincidental. It will be misleading to return a falsy value from `showTransparentBackground( undefined )`.

Comment (danielbachhuber) [reply packages/components/src/color-palette/test/utils.ts]: > The fact that it "works" as expected with the current `background` implementation is only coincidental.

@mirka It's actually because the test is missing the call to `showTransparentBackground()` 🙈 

Fixed with 43afb0cdc47f06010449984cf644548b4fbe42fc

Comment (mirka) [reply packages/components/src/color-palette/test/utils.ts]: LOL

**Review by mirka — APPROVED** [review]
I think we're good to go then! 🚀 

> I actually looked into this. I think it will involve a bit of CSS retooling, though. I didn't feel comfortable contributing the change because I felt like it might delay the review process (and solving 'transparent' is my immediate need).

Agreed, this is the right call 👍 Split into a separate issue at #42715.

**Comment by danielbachhuber** [comment]
> I think we're good to go then! 🚀

Awesome, thanks!
