### PR TITLE
Inserter: Hide child blocks from the inserter when needed

### LINKED ISSUE #65687: Child blocks are displayed in the block inserter and block visibility doesn't work
## What problem does this address?

I found two issues in the trunk:

- Child blocks that have a specific parent, such as the List Item, are displayed. When you click on the block, it will say "Block "{blockName}" can't be inserted.". (This may be a new specification)
- "Manage block visibility" doesn't work.

I used `git bisect` and it looks like this issue occurred in #65490.

https://github.com/user-attachments/assets/e9b761f6-79a2-4ab9-bde3-86b031d5e755

cc @youknowriad @andrewserong @jorgefilipecosta

### PR DESCRIPTION
**Pull request by youknowriad**
closes #65687 

## What?

In a previous iteration, we allowed all blocks to be visible in the inserter at any time. This has proven a bit confusing for blocks that require a parent block. These blocks should only be visible within their parent blocks. This PR solves that.

## Testing Instructions

1- The "column" block shouldn't be visible when you're at the root level in the inserter
2- The "column" block should be visible when you're within a columns block.

### CODE REVIEW

File: packages/block-editor/src/store/selectors.js [hunk 1]
```diff
@@ -1621,29 +1621,25 @@ const isBlockVisibleInTheInserter = (
...
-						name,
-						checkedBlocks
-					) ) ||
-				// Exception for blocks with post-content parent,
-				// the root level is often consider as "core/post-content".
-				// This exception should only apply to the post editor ideally though.
-				name === 'core/post-content'
+	const parents = (
+		Array.isArray( blockType.parent ) ? blockType.parent : []
+	).concat( blockType.ancestor ? blockType.ancestor : [] );
```
Comment (Mamaduka) [inline packages/block-editor/src/store/selectors.js]: The  `ancestor` is also an array; we should do a check similar to the parent.

Comment (youknowriad) [reply packages/block-editor/src/store/selectors.js]: I think the check for parent is only done because historically we kind of supported string if I'm not wrong. I can add a check though, I don't mind.

**Review by juanfra — COMMENTED** [review]
This is testing well for me, thank you! I noticed that it caused confusion during the speed build challenge last Friday and came to see if there was an issue for it.

https://github.com/user-attachments/assets/ebb446fd-eab0-4ff9-a493-bea95d7f68c7

**Comment by Mamaduka** [comment]
Thanks, Riad!

This almost works, but some bugs remain for the primary root (`' '`) and container blocks that allow all items.

1. Some blocks that require parent/ancestor are still listed.
2. When switching from primary root (`' '`) to group root, inserter remounts, even though the allowed items should be the same.

## Screenshot,  group block example
CleanShot 2024-12-10 at 15 49 48

**Comment by Mamaduka** [comment]
It looks like the `ancestor` property is missing from `buildBlockTypeItem`. The patch below partially fixes the issue.

```diff
diff --git packages/block-editor/src/store/selectors.js packages/block-editor/src/store/selectors.js
index 8e2ce92eede..7ee0efd5f41 100644
--- packages/block-editor/src/store/selectors.js
+++ packages/block-editor/src/store/selectors.js
@@ -2061,6 +2061,7 @@ const buildBlockTypeItem =
 		return {
 			...blockItemBase,
 			initialAttributes: {},
+			ancestor: blockType.ancestor,
 			description: blockType.description,
 			category: blockType.category,
 			keywords: blockType.keywords,
```

**Comment by youknowriad** [comment]
I think the "template parts" and "post content" blocks showing there are issues unrelated with the current PR. I'm not entirely sure how to solve this yet.

**Review by Mamaduka — APPROVED** [review]
> I think the "template parts" and "post content" blocks showing there are issues unrelated with the current PR. I'm not entirely sure how to solve this yet.

We can tackle that separately. Can you create an issue so we don't forget?

**Comment by youknowriad** [comment]
I created an issue here #67797

File: packages/block-editor/src/store/selectors.js [hunk 2]
```diff
@@ -1621,26 +1621,19 @@ const isBlockVisibleInTheInserter = (
...
-						name,
-						checkedBlocks
-					) ) ||
-				// Exception for blocks with post-content parent,
-				// the root level is often consider as "core/post-content".
-				// This exception should only apply to the post editor ideally though.
-				name === 'core/post-content'
+	const parents = (
+		Array.isArray( blockType.parent ) ? blockType.parent : []
+	).concat( Array.isArray( blockType.ancestor ) ? blockType.ancestor : [] );
```
Comment (ockham) [inline packages/block-editor/src/store/selectors.js:1627]: 👋 This seems to be treating `parent` and `ancestor` as synonymous. However, their semantics are meant to be different: For `parent`, only the _immediate_ ancestor should be considered.

Comment (youknowriad) [reply packages/block-editor/src/store/selectors.js:1627]: But they are indeed the same when you want to insert a block directly within a parent block (rootClientId) so this is correct AFAIK. Do you see any errors here?

Comment (ockham) [reply packages/block-editor/src/store/selectors.js:1627]: Yeah, you're right. I think I read the code wrong! Apologies 😊
