### PR TITLE
Components: Fix Toolbar arrow key navigation in RTL contexts

### LINKED ISSUE #23265: Block toolbar misaligned in RTL contexts
It appears that the block toolbar is misaligned in RTL environments. 

1. Set the site language to an RTL language, for example arabic.
2. Go to the block editor and add content. 
3. Make sure the viewport is not too wide, less than 1280px or thereabouts.

Observe that the block toolbar is mis-aligned. It should be flush with the right margin of blocks, but it is indented a little bit. 

GIF of small viewport:

rtl

Note that on a very wide viewport the issue only appears once one or two sidebars appear:

rtl widescreen

Mac/Chrome/Nightly.

### PR DESCRIPTION
**Pull request by diegohaz**
This PR fixes https://github.com/WordPress/gutenberg/issues/23265#issuecomment-659410357.

**Before**:

GIF showing the interaction on the block toolbar. Pressing arrow right moves focus to the toolbar item on the left, and pressing arrow left moves focus to the toolbar item on the right.

**After:**

GIF showing the interaction on the block toolbar. Pressing arrow right moves focus to the toolbar item on the right, and pressing arrow left moves focus to the toolbar item on the left.

## How to test

1. Set the site language to an RTL langauge, such as Arabic, in the settings.
2. Go to the block editor and interact with the block toolbar using arrow keys.
3. Make sure <kbd>ArrowLeft</kbd> moves focus to the left, and <kbd>ArrowRight</kbd> moves focus to the right.

### CODE REVIEW

File: packages/components/src/toolbar/toolbar-container.js [hunk 1]
```diff
@@ -12,12 +12,17 @@ import { forwardRef } from '@wordpress/element';
  * Internal dependencies
  */
 import ToolbarContext from '../toolbar-context';
+import { getRTL } from '../utils/rtl';
```
Comment (youknowriad) [inline packages/components/src/toolbar/toolbar-container.js:15]: Ideally, we'd drop this in favor of `{ isRTL } from '@wordpress/i18n'` but this could be separate as this is already used.

**Review by youknowriad — APPROVED** [review]
Works well, thanks for the fix.
