### PR TITLE
Widget Editor: Fix allow adding same image twice

### LINKED ISSUE #32901: Widget editor: Adding same image twice only saves one block
## Description
Inserting the same image twice in the same area only saves one of the blocks. This is also true if you use the image in a cover block and the same image in a image block.

Note: This only happens on `wp-admin/widgets.php` and not in the customizer.

## Step-by-step reproduction instructions
1. Go to widget editor.
2. Insert a image block with a image.
3. Insert a new image block with the same image.
4. Click save
5. Reload the page and only one of the blocks is saved.

## Expected behaviour
Both blocks is saved.

## Actual behaviour
Only one of the image blocks is saved.

## WordPress information
- WordPress version: 5.8-beta2-51203
- Gutenberg version: trunk (10.9.0-rc.1)
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Macbook
- Operating system: macOS Big Sur
- Browser: Chrome 91.0

### PR DESCRIPTION
**Pull request by thisissandip**
## Description
Fixes https://github.com/WordPress/gutenberg/issues/32901

Adding same image twice in the widgets editor only saves one block. This PR fixes that.

This was happening because while saving/updating the blocks in the widget editor, duplicate widget instances were filtered. Whereas when multiple blocks (cover block/image block) use the same image, the `id` attribute of the blocks becomes identical and only the first block was saved.

## How has this been tested?
1. Go to widget editor.
2. Insert an image block with an image.
3. Insert a new image block with the same image.
4. Click save
5. Reload the page and both the blocks should be saved.

## Types of changes
bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by adamziel** [comment]
@thisissandip I understand that removing filtering solves the "duplicate" block problem, but won't it break the duplicate widget case it was originally meant to address?

**Comment by thisissandip** [comment]
@adamziel No, it will not. The filtering was blocking the blocks in the widget area with the same `id` attribute but most of the blocks don't have the `id` attribute. 

Also, while working on this PR I noticed that the filtering was blocking the gallery block too since the gallery block has the `id` attribute as an array.

Issue:

https://user-images.githubusercontent.com/69596988/123272414-57e10800-d51f-11eb-9d93-3056e74d1e0e.mov

Gallery block `id` attribute:
Screenshot 2021-06-24 at 7 04 39 PM

**Comment by adamziel** [comment]
I wanted to test this patch with function-based widgets and then I ran into an even larger issue: https://github.com/WordPress/gutenberg/issues/32960

**Comment by thisissandip** [comment]
@adamziel Thank you for taking a look! 😄 
> but won't it break the duplicate widget case it was originally meant to address?

No, it won't. The filtering was blocking the blocks in the widget area with the same `id` but most of the blocks don't have the `id` attribute. Moreover, having 2 similar blocks within a widget area should be allowed.

**Comment by adamziel** [comment]
> most of the blocks don't have the id attribute

IIRC the function-based blocks do and this code is there to prevent adding more than one instance of these (because WordPress doesn't support that).

> Moreover, having 2 similar blocks within a widget area should be allowed.

Fully agreed! I'm only saying that this check is there for a reason and removing it will break something else. It would be cool to rethink it somehow to both prevent adding multiple instances of the same function-based widgets AND support multiple similar images at the same time. I'm not sure how to approach that off the top of my head though

**Comment by thisissandip** [comment]
> IIRC the function-based blocks do and this code is there to prevent adding more than one instance of these (because WordPress doesn't support that).

@adamziel Okay! I'll try some other approach then!

File: packages/edit-widgets/src/store/actions.js [hunk 1]
```diff
@@ -108,17 +108,7 @@ export function* saveWidgetArea( widgetAreaId ) {
...
-	const widgetsBlocks = post.blocks.filter( ( { attributes: { id } } ) => {
-		if ( id ) {
-			if ( usedReferenceWidgets.includes( id ) ) {
-				return false;
-			}
-			usedReferenceWidgets.push( id );
-		}
-		return true;
-	} );
+	const widgetsBlocks = post.blocks;
```
Comment (getdave) [inline packages/edit-widgets/src/store/actions.js]:
```js
const widgetsBlocks = post.blocks.filter( ( { clientId } ) => {
		if ( clientId ) {
			if ( usedReferenceWidgets.includes( clientId ) ) {
				return false;
			}
			usedReferenceWidgets.push( clientId );
		}
		return true;
	} );
```

Could we use `clientId` here as the identifier?

**Review by getdave — COMMENTED** [review]
TBH I'm not clear from the code what the purpose of this removing widgets which have duplicate ID attribute. There's not a lot of context in the code and the comments don't illuminate much beyond the fact that we're doing filtering.

Given that not all blocks have an `id` attribute I wonder what we're trying to achieve here?

Perhaps @noisysocks or @talldan can advise?

File: packages/edit-widgets/src/store/actions.js (hunk 1 above)
Comment (thisissandip) [reply packages/edit-widgets/src/store/actions.js]: I guess all the blocks have different `clientId` by default.  I don't think it will make any difference rather than just removing the filter itself. As it is blocking the blocks with a similar `id` to be saved. That's why I decided to remove it. 😅 

Thank you for taking a look! 😄

**Comment by adamziel** [comment]
@getdave IIRC we filter out the widgets with duplicate IDs to prevent adding more than one instance of a widget implemented using a function (e.g. [marquee_greetings](https://gist.github.com/adamziel/526436b4cc9bc82a7221c77e00137ae1)). WordPress doesn't support having more than one instance of these, if you try to save multiple `marquee_greetings` in different sidebars you will run into undefined behaviors. It isn't easy to prevent Gutenberg from adding one more instance of a block, hence the next best thing: this custom filtering logic.

File: packages/edit-widgets/src/store/actions.js (hunk 1 above)
Comment (getdave) [reply packages/edit-widgets/src/store/actions.js]: Yeh you're absolutely right. Needed to fully understand the problem.

**Comment by thisissandip** [comment]
@adamziel I have a question. If I am not wrong the function-based widgets can be added with legacy widget block right? So wrapping the filter with a block type check can solve the issue.

**Comment by getdave** [comment]
> @adamziel I have a question. If I am not wrong the function-based widgets can be added with legacy widget block right? So wrapping the filter with a block type check can solve the issue.

How about https://github.com/WordPress/gutenberg/pull/32951#pullrequestreview-691958646 ?

File: packages/edit-widgets/src/store/actions.js (hunk 1 above)
Comment (getdave) [inline packages/edit-widgets/src/store/actions.js]:
```js
// Remove all duplicate reference widget instances for legacy widgets.
// Why? We filter out the widgets with duplicate IDs to prevent adding more than one instance of a widget
// implemented using a function. WordPress doesn't support having more than one instance of these, if you try to
// save multiple instances of these in different sidebars you will run into undefined behaviors.
const usedReferenceWidgets = [];
const widgetsBlocks = post.blocks.filter( ( block ) => {

    const { id } = block.attributes;

    if ( block.name === 'core/legacy-widget' && block.attributes?.id ) {
        if ( usedReferenceWidgets.includes( id ) ) {
            return false;
        }
        usedReferenceWidgets.push( id );
    }
    return true;
} );
```

**Comment by thisissandip** [comment]
@getdave Yes! This is exactly what I was thinking!

File: packages/edit-widgets/src/store/actions.js (hunk 1 above)
Comment (getdave) [reply packages/edit-widgets/src/store/actions.js]: I gave this a spin and it seemed to work.

I'd say we'd need some confirmation that the widget `id` guard is still correct as even with Adam's comment I (personally) don't have the full context/confidence that I've done this correctly.

Comment (getdave) [reply packages/edit-widgets/src/store/actions.js]: https://user-images.githubusercontent.com/444434/123297534-8e168b80-d50f-11eb-86f0-5946d162e442.mov

**Comment by thisissandip** [comment]
@getdave I have updated the code! Thanks for the snippet!

File: packages/edit-widgets/src/store/actions.js (hunk 1 above)
Comment (thisissandip) [reply packages/edit-widgets/src/store/actions.js]: Yes, it works! I tested with file and cover block too! 🎉

File: packages/edit-widgets/src/store/actions.js [hunk 2]
```diff
@@ -108,10 +108,15 @@ export function* saveWidgetArea( widgetAreaId ) {
...
+	// Why? We filter out the widgets with duplicate IDs to prevent adding more than one instance of a widget
+	// implemented using a function. WordPress doesn't support having more than one instance of these, if you try to
+	// save multiple instances of these in different sidebars you will run into undefined behaviors.
 	const usedReferenceWidgets = [];
-	const widgetsBlocks = post.blocks.filter( ( { attributes: { id } } ) => {
-		if ( id ) {
+	const widgetsBlocks = post.blocks.filter( ( block ) => {
+		const { id } = block.attributes;
+
+		if ( block.name === 'core/legacy-widget' && block.attributes?.id ) {
```
Comment (kevin940726) [inline packages/edit-widgets/src/store/actions.js]: This seems like a typo :)?

```suggestion
		if ( block.name === 'core/legacy-widget' && id ) {
```

Comment (thisissandip) [reply packages/edit-widgets/src/store/actions.js]: yeah, thanks! 😄

**Review by talldan — APPROVED** [review]
This makes sense to me, the `id` attribute of the legacy widget is fundamentally different from other block's `id` attributes, so shouldn't be confused.

Thanks so much for your contribution @thisissandip!

**Comment by adamziel** [comment]
This looks great, thank you @thisissandip and @getdave !
