### PR TITLE
fix: Show permalink editor in editor

### LINKED ISSUE #7467: Permalinks editing has vanished
Right now on master the permalink editing has gone:

2018-06-22 at 11 26

### PR DESCRIPTION
**Pull request by tofumatt**
## Description
Fixed the permalink editor not appearing. Fix #7467.

## How has this been tested?
Tested locally and saw the permalink editor appear as it used to in `v3.0.1`.

## Types of changes
Bug fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: editor/components/post-permalink/index.js [hunk 1]
```diff
@@ -123,7 +123,13 @@ class PostPermalink extends Component {
 
 export default compose( [
 	withSelect( ( select ) => {
-		const { isEditedPostNew, isPermalinkEditable, getEditedPostPreviewLink, getPermalink, isCurrentPostPublished } = select( 'core/editor' );
+		const {
+			isEditedPostNew,
```
Comment (tofumatt) [inline editor/components/post-permalink/index.js]: I was messing about with possibly improving how the logic to display the permalink editor worked and it meant editing the selectors used… I didn't end up doing it, but I found this a bit easier to read so left it in 😄

File: editor/components/post-permalink/index.js [hunk 2]
```diff
@@ -60,7 +60,7 @@ class PostPermalink extends Component {
 		const { isCopied, isEditingPermalink } = this.state;
 		const ariaLabel = isCopied ? __( 'Permalink copied' ) : __( 'Copy the permalink' );
 
-		if ( isNew || ! previewLink ) {
+		if ( isNew ) {
```
Comment (mcsf) [inline editor/components/post-permalink/index.js]: Can you provide context on why the necessary condition has changed? Put differently: what changed in the breaking PR (#7130) that requires adapting this line?

Comment (tofumatt) [reply editor/components/post-permalink/index.js]: So I'm a bit confused as to how it worked before and why this condition is here at all. The only time we shouldn't render the permalink editor is when the post is entirely new and hasn't been sent to the server (eg `isNew === true`).

Changing this check makes the Permalink editor behave as it did in `3.0.1`… though I'll admit the lack of tests on this had me confused as to exactly what that was, so I just manually tested it 😄

To be honest it's just an educated guess but I'd think https://github.com/WordPress/gutenberg/pull/7130/files#diff-36dbe9dade73983f5ea95f585450ff2cR1091 is the breaking change. Not sure why it's there… @aduth?

Comment (aduth) [reply editor/components/post-permalink/index.js]: #7130 moved the `preview_link` out of the posts endpoint into the autosaves endpoint. The `autosave` state had never previously tracked `preview_link`, so the referenced line from the pull request is related -- though not directly. Omitting the field is not the breakage; it's the fact that we no longer track `preview_link` in the objects accessed by `getEditedPostPreviewLink`. This is intentional, though apparently I did not audit the existing code to update all places where we relied on it.

In fact, the selector `getEditedPostPreviewLink` should either be removed or updated to `getAutosaveAttribute( 'preview_link' )` (as was done for `PostPreviewButton`).

That said, there's a few issues:

- We don't populate `autosave` when the post loads, so we can't rely on it existing to retrieve a preview link. Related: #7416.
- The behavior in #7130 was changed to be such that the preview button redirects its popup when a preview link becomes available, so there is a short time between an autosave starting and its completion that the preview link is unset. What are we to be rendering as a link here in the meantime?
- More generally, what is the behavior of the link when there are unsaved changes? It's odd we apply the preview link, but not the mechanics of autosaving in order to show the latest preview of the post.

So I'm inclined to wonder: Should we just set this to be the `post.link` from whatever is the most recent saved version of the post (`currentPost`)? 

There may be some additional context buried in #5756 which could shed light on why we might want a preview link here.

File: editor/components/post-permalink/index.js [hunk 3]
```diff
@@ -123,7 +123,13 @@ class PostPermalink extends Component {
 
 export default compose( [
 	withSelect( ( select ) => {
-		const { isEditedPostNew, isPermalinkEditable, getEditedPostPreviewLink, getPermalink, isCurrentPostPublished } = select( 'core/editor' );
+		const {
+			isEditedPostNew,
+			isPermalinkEditable,
+			getEditedPostPreviewLink,
```
Comment (aduth) [inline editor/components/post-permalink/index.js]: Noted above: `getEditedPostPreviewLink` is a useless selector, should be removed here (and altogether, since this is its only remaining usage).

**Comment by tofumatt** [comment]
Thanks for all the context here @aduth; I'll have another look soon and see about using `post.link` as mentioned.

File: editor/components/post-permalink/index.js (hunk 2 above)
Comment (tofumatt) [reply editor/components/post-permalink/index.js]: Using `getCurrentPost()` means we can otherwise preserve the logic here. Thanks! 👍

**Comment by tofumatt** [comment]
Cool, used `getCurrentPost()`, tested it locally, and it all worked. r?

File: editor/store/selectors.js [hunk 4]
```diff
@@ -444,17 +444,6 @@ export function getDocumentTitle( state ) {
...
 }
 
-/**
- * Returns a URL to preview the post being edited.
- *
- * @param {Object} state Global application state.
- *
- * @return {string} Preview URL.
- */
-export function getEditedPostPreviewLink( state ) {
```
Comment (noisysocks) [inline editor/store/selectors.js]: Should we deprecate this? On the one hand, it's a public 'method'. On the other, it's undocumented.

**Review by noisysocks — APPROVED** [review]
Tested this locally and it smells nice 👍

File: editor/store/selectors.js (hunk 4 above)
Comment (tofumatt) [reply editor/store/selectors.js]: It's not documented, nothing else uses it, and @aduth mentioned it just missed the cutting block during another commit. I think technically maybe we should but I feel like we're in the clear.

I will add it back, deprecate it, and wear the dunce hat if it affects anyone in the next release 😉

Comment (aduth) [reply editor/store/selectors.js]: Worth noting: It doesn't work as-is anyways, hence the original issue. Probably better to not work than to throw errors though. If we wanted full compatibility, we might redirect the result to `getAutosaveAttribute( 'preview_link' )`

Comment (tofumatt) [reply editor/store/selectors.js]: But `getAutosaveAttribute( 'preview_link' )` won't work on page load, right? I tested this with new page loads of existing posts and "Add New" posts and it never broke the page 🤷‍♂️
