### PR TITLE
FormTokenField: Fix duplicate input in IME composition

### LINKED ISSUE #45599: FormTokenField: ADD NEW TAG is entered twice in Japanese
### Description

In WordPress 6.1, when I type Japanese in ADD NEW TAG on the editor screen and press Enter, Japanese is typed twice.

In WordPress 6.0, Japanese is entered only once and works correctly.

When entering characters in Japanese language ( including Kanji), after entering "Hiragana", select which character to convert to and press Enter to confirm.

I would expect the same problem in other languages that perform the same operation.

### Step-by-step reproduction instructions

I expect users to use a Japanese keyboard.

1.On the editor screen. type `あああ` in the ADD NEW TAG input.

2.Confirm that a character is unintentionally typed twice when the enter key is pressed.

#### WordPress 6.1

・Type in Japanese and press Enter key unintentionally types the word twice.

スクリーンショット 2022-11-08 190328

#### WordPress 6.0

・Type in Japanese and press Enter Key for correct operation.

スクリーンショット 2022-11-08 190620

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
- Fix #45599 
- Part of #45605 

## What?
This PR fixes a problem where duplicate values are set when characters are entered into `FormTokenField` in languages that use IME composition.

## Why?
This is because the `enter` key, which is used to confirm the entry of a character, is considered a token decision.
For more context, see [here](https://github.com/WordPress/gutenberg/issues/45605#issue-1440281357).

## How?
Replaced `event.code` with `event.key`.

## Testing Instructions

1. Create some post tags.
2. Open the post Editor.
3. Enter text in IME composition mode in the "ADD TAG" sidebar.
4. Confrim that the Enter key to decide your input does NOT insert a token.
5. Confirm that pressing the Enter key again sets the token.

## Screenshots or screencast 

https://user-images.githubusercontent.com/54422211/200599026-be0f0c44-6126-4322-9d54-5fc4c029bc19.mp4

### CODE REVIEW

File: packages/components/src/form-token-field/index.tsx [hunk 1]
```diff
@@ -213,9 +213,9 @@ export function FormTokenField( props: FormTokenFieldProps ) {
 
 	function onKeyPress( event: KeyboardEvent ) {
 		let preventDefault = false;
-		// TODO: replace to event.code;
-		switch ( event.charCode ) {
-			case 44: // Comma.
+
+		switch ( event.key ) {
+			case 'Comma':
```
Comment (t-hamano) [inline packages/components/src/form-token-field/index.tsx]: Since there was a TODO for key events here, this was also addressed.
If it is unnecessary, I would like to revert it.

Comment (Mamaduka) [reply packages/components/src/form-token-field/index.tsx]: I think the `event.key` for the comma is `,`. See: https://www.toptal.com/developers/keycode

File: packages/components/src/form-token-field/index.tsx [hunk 2]
```diff
@@ -172,7 +172,7 @@ export function FormTokenField( props: FormTokenFieldProps ) {
 		if ( event.defaultPrevented ) {
```
Comment (mirka) [inline packages/components/src/form-token-field/index.tsx]: Unfortunately I've noticed some cross-browser differences — in Mac Chrome, the `event.key` fix is insufficient when <kbd>Enter</kbd> is involved (the other keys, and other Mac browsers, seem to be fine).

https://user-images.githubusercontent.com/555336/200654761-fc674d04-fab9-4a7c-aa50-6037dd0bdd94.mp4

☝️ Mac Chrome

I think we'll need to add a `isComposing` check:

```suggestion
		if ( event.defaultPrevented || event.nativeEvent.isComposing ) {
```

I guess technically we could just add the check in the `case 'Enter'` branch, but I think it would be safer to check it for all cases. In my experience there are some weird IME-related differences between OSes and browsers 😅 (Linux too!)

File: packages/components/src/form-token-field/index.tsx (hunk 1 above)
Comment (t-hamano) [reply packages/components/src/form-token-field/index.tsx]: Thanks for noticing.
You are correct, I have fixed it in 16190d6.

But it is strange that all tests have passed even though the value was wrong. Perhaps we should check for any missing tests as a follow-up to this PR.

File: packages/components/src/form-token-field/index.tsx (hunk 2 above)
Comment (t-hamano) [reply packages/components/src/form-token-field/index.tsx]: Thanks for the test!
I think adding `isComposing` makes sense.

I am concerned that the same follow-up needs to be added for the corrections made in [AutocompleteUI](https://github.com/WordPress/gutenberg/issues/45496).

**Comment by t-hamano** [comment]
I accessed the local site where I built this PR from my iPhone and it seems to work as expected in Chrome on my iPhone.


https://user-images.githubusercontent.com/54422211/200821257-72aa2508-0c24-4811-a41e-b387773b3f76.mp4

**Review by Mamaduka — COMMENTED** [review]
Tested on macOS using Chrome, Safari, and Firefox with English/Georgian keyboards. I couldn't spot any regressions, `FormTokenField` works as before.

It would be great to get confirmations from folks using other OS to backport this into a minor release.

**Comment by benridane** [comment]
Tested on Windows 10 using Chrome and Firefox with Japanese. It looks like work fine.

File: packages/components/src/form-token-field/index.tsx [hunk 3]
```diff
@@ -169,10 +169,10 @@ export function FormTokenField( props: FormTokenFieldProps ) {
 	function onKeyDown( event: KeyboardEvent ) {
 		let preventDefault = false;
 
-		if ( event.defaultPrevented ) {
+		if ( event.defaultPrevented || event.nativeEvent.isComposing ) {
```
Comment (mirka) [inline packages/components/src/form-token-field/index.tsx]: Ok, we have another complication, sorry I didn't notice it the first time.

On Mac Safari, the <kbd>Enter</kbd> or <kbd>Backspace</kbd> that ends IME composition is `isComposing=false` 🙃 This causes these keydowns to immediately commit the token or erase the previous token, when that is not the user intent.


https://user-images.githubusercontent.com/555336/200918022-4eaa0342-ef5e-4f70-82d2-a9139cb0a8d4.mp4

event output of the video

☝️ `console.log( event.key, event.keyCode, event.nativeEvent.isComposing )`

At this point I'd consider reverting to the `event.keyCode` method, but maybe we can try a hybrid approach, given that `event.keyCode` could theoretically be removed from browsers at any time.

How about we add a `event.keyCode === 229` check in the guard? This way, even if `event.keyCode` is removed from browsers at some point, the damage will be limited to Safari.

```suggestion
		if (
			event.defaultPrevented ||
			// Ignore keydowns from IMEs
			event.nativeEvent.isComposing ||
			// Workaround for Mac Safari where the final Enter/Backspace of an IME composition
			// is `isComposing=false`, even though it's technically still part of the composition.
			// These can only be detected by keyCode.
			event.keyCode === 229
		) {
```

File: packages/components/src/form-token-field/index.tsx (hunk 1 above)
Comment (ciampo) [reply packages/components/src/form-token-field/index.tsx]: The ["should add a token with the input's value when pressing the comma key" test](https://github.com/WordPress/gutenberg/blob/519f0e7077e6aca363793cc02b7618211de8565c/packages/components/src/form-token-field/test/index.tsx#L136) should check for comma keypresses, maybe you could look a bit more into it and why it didn't flag a regression?

File: packages/components/src/form-token-field/index.tsx (hunk 3 above)
Comment (ciampo) [reply packages/components/src/form-token-field/index.tsx]: TIL about IME composition 🤯 

Just skimming through the spec, is there any chance we could leverage `compositionstart` and `compositionend` events?

Comment (mirka) [reply packages/components/src/form-token-field/index.tsx]: Oh hi, welcome to cross-browser IME event handling hell!

> Just skimming through the spec, is there any chance we could leverage `compositionstart` and `compositionend` events?

Unfortunately that is a whole other can of worms I'd prefer we keep shut 😂 Japanese article, but [look at this table](https://qiita.com/pochman/items/b99c835bf598810d3c18#ime%E5%85%A5%E5%8A%9B%E3%81%AE%E7%B5%82%E4%BA%86enter%E3%81%AB%E3%82%88%E3%82%8B%E6%B1%BA%E5%AE%9A) of how random the event firing is across browsers. And yeah, the `Enter` keydown that we want to ignore in this case fires after `compositionend` in Safari, so it wouldn't help 🙃

Comment (t-hamano) [reply packages/components/src/form-token-field/index.tsx]: Thanks for the suggestion and the detailed research, @mirka !

I found [another article](https://developer.squareup.com/blog/understanding-composition-browser-events/) that corroborates the issue of the strange sequence of events in Safari.

> This is what the user should expect; only after finishing the composition should subsequent enter presses open their search query in a new tab. However, in my testing, Safari appears to fire the keyDown and compositionEnd events in the opposite order. Here’s the logic path:

**Comment by Mamaduka** [comment]
@t-hamano, @mirka, do we have a solution that we can ship with WP 6.1.1?

The RC is scheduled for tomorrow, and I plan to release packages later today.

**Comment by mirka** [comment]
To play it safe, I'm wondering if we should ship the hotfix simply as a revert to the `event.keyCode` way. I'm worried about the lack of testing on this new implementation, namely on Android and Linux. This is one of the most unpredictable parts of the browser, and it could potentially cause even more problems.

Unfortunately I don't have a Virtualbox setup anymore and can't easily test for those environments. We might not be able to get testers before the deadline.

File: packages/components/src/form-token-field/index.tsx (hunk 1 above)
Comment (t-hamano) [reply packages/components/src/form-token-field/index.tsx]: @ciampo 

I have tried various inputs to clarify this issue and have been unable to find a case where `onKeyPress` occurs.
Also, the determination of the token by comma key appears to be controlled by [this other event](https://github.com/WordPress/gutenberg/blob/8c9af511be57af4364db63eb47dc175712b4177d/packages/components/src/form-token-field/index.tsx#L256-L267).
Is there any way to clarify what this event is provided for?

**Comment by t-hamano** [comment]
I committed this suggestion because I thought the method suggested in [this comment](https://github.com/WordPress/gutenberg/pull/45607#discussion_r1018323807) was the best so far.
But it may indeed not be well tested.

Considering that there is not much time left before the RC release, it may be safe to revert to the previous implementation.

This is also true for #45626 regarding `AutoComplete` component.

**Comment by mirka** [comment]
Cool, let's keep this PR to merge into trunk, and open a separate `event.keyCode` PR for cherry-picking into 6.1.1. @t-hamano Are you still available today to do this? If not, I'd be happy to do it 🙂

**Comment by Mamaduka** [comment]
Thank you both for the feedback! I agree; that's probably the safest fix we can ship with the minor release.

@t-hamano, do you have time to create a revert to the `keyCode` hotfix for both components?

**Comment by t-hamano** [comment]
Yes, I'll work on them 👍

**Comment by t-hamano** [comment]
I had something to check.
Should PR for WP6.1.1 be checked out from the `wp/6.1` branch? (or `trunk` ?)

File: packages/components/src/form-token-field/index.tsx (hunk 1 above)
Comment (mirka) [reply packages/components/src/form-token-field/index.tsx]: Agreed, tokenization is also done with regex so the comma handling seems redundant.

https://github.com/WordPress/gutenberg/blob/8c9af511be57af4364db63eb47dc175712b4177d/packages/components/src/form-token-field/index.tsx#L258

So it turns out the test is correct and it isn't a regression! We could bypass this entire onKeyPress handler and it wouldn't matter 😇

https://github.com/WordPress/gutenberg/blob/8c9af511be57af4364db63eb47dc175712b4177d/packages/components/src/form-token-field/index.tsx#L214-L223

Digging into the history, apparently the original code was [copied](https://github.com/WordPress/gutenberg/pull/924) from wp-calypso, and we can see that the [regex was added](https://github.com/Automattic/wp-calypso/pull/8457/files#diff-2ea7a1abaac30ad7200f831bceecf1a1876603dd17a2283b24d0cf751fc29a7cR232) after the keyPress comma handling was already in place, in the context of supporting copy-pasted strings. From that, I would guess that the redundancy is just an oversight. If anything, relying on the regex for commas is probably more reliable given that there was some [weirdness with keyCode/charCode differences](https://github.com/Automattic/wp-calypso/pull/2511).

**Comment by Mamaduka** [comment]
6.1 will work as well. Thanks!

**Comment by t-hamano** [comment]
`FormTokenField` PR for WP6.1.1 is here: #45703

**Comment by t-hamano** [comment]
`AutoComplete` PR for WP6.1.1 is here: #45704

As for the FormTokenField, I will continue to look into this as the unit test is failing.

**Comment by ciampo** [comment]
Thank you all for working on a solution for this, really appreciate the collaboration. Excuses also for not having tested my `keyCode` to `code` PRs properly, I was definitely not considering IME composition.

**Review by mirka — APPROVED** [review]
Retested on Mac Chrome/Firefox/Safari, and it works as expected.

I'm ok to merge this into trunk so we can get more field testing in the plugin track 👍
