### PR TITLE
Deprecate and make Fonts API non-functional.

### LINKED ISSUE #51819: [Fonts API] Deprecate and remove all functionality (in favor of Font Face)
Related to https://github.com/WordPress/gutenberg/issues/51769.

Part of https://github.com/WordPress/gutenberg/issues/41479.

## What problem does this address?

- Avoid fatal errors on sites using the Fonts API once the [Fonts Library](https://github.com/WordPress/gutenberg/pull/50927) is merged.

The Fonts API will be replaced by the Font Face https://github.com/WordPress/gutenberg/issues/51769. But its classes, functions, and public and protected methods must be loaded into memory and be non-functional (no code except deprecations).

Once the Fonts Library is merged, sites currently using the Fonts API will break with fatal errors. Why? The Font Face files get loaded instead of the Fonts API (its replacing it).

## What is your proposed solution?

To avoid breaking sites using the Fonts API, all of the classes, public methods, and functions need to be loaded into memory. To avoid font workflow conflicts, the code within these methods and functions will be removed and not work (non-functional), and deprecations added to alert folks to not use the Fonts API.

Once [Font Face](https://github.com/WordPress/gutenberg/pull/51770) is merged into `trunk, then:

1. Copy all of the files from '/lib/experimental/fonts-api/` into `/lib/experimental/fonts/bc-layer/`.
2. Remove all `private` methods.
3. Remove all of code from functions and methods, except for deprecation notices and `wp_fonts()`.
4. Ensure each function and method has a deprecation notice that alerts to stop using the Fonts API.
5. Remove all hooks, such as the hooks that call `wp_print_fonts()`.
6. Load each of the files in `/lib/experimental/fonts/bc-layer/` in `lib/load.php`, adding them after the Font Face files. 

IMPORTANT:
In `lib/load.php`, files in `lib/experimental/fonts/` (i.e. Font Face and its BC Layer) will only load into memory when the Font Library is merged into `trunk` or when loaded in tests.

Else, the Fonts API (in `lib/experimental/fonts-api`) is loaded into memory.

It's important to keep these separate and only load either the Fonts API (all files in `lib/experimental/fonts-api/`) OR Font Face (all files in `lib/experimental/fonts/`). Do not load both `lib/experimental/fonts-api/` and `lib/experimental/fonts/`.

### PR DESCRIPTION
**Pull request by hellofromtonya**
Closes [51819](https://github.com/WordPress/gutenberg/issues/51819).

## What?

Creates a BC Layer in the new Font Face.

Deprecates all of the Fonts API's public-facing files, functions, classes, and methods.

Makes the Fonts API non-functional, i.e. as Font Face replaces it.

## Why?

Font Face replaces Fonts API.

For sites using the Fonts API, this PR:

1. Avoids those sites experiencing a fatal parsing error.
2. Makes the Fonts API non-functional to avoid conflicts with the [new font management approach](https://github.com/WordPress/gutenberg/issues/45271).

## How?

1. Copies all of the Fonts API's files into a new `fonts/bc-layer` directory.
2. Removes all `private` methods.
3. Removes all functionality from remaining functions and methods.
4. Deprecates all of the files, classes, functions, and methods.
5. Loads the files into memory (to avoid fatal parsing errors on sites using it).

### Set up
1. Enable the loading of the Font Face files:
    a. Open `lib/load.php`.
    b. Scroll down to where the Font Face files are loaded.
    c. Add `true || ` in the `if`:

```php
if ( true || class_exists( 'WP_Fonts_Library' ) || class_exists( 'WP_Fonts_Library_Controller' ) ) {
```

2. Plugin using the Fonts API:
* Install and activate [this test plugin](https://github.com/ironprogrammer/webfonts-jetpack-test).
* Comment out these [3 lines of code](https://github.com/ironprogrammer/webfonts-jetpack-test/blob/master/webfonts.php#L75-L77) in the `webfonts.php` file:

```php
                 if ( ! function_exists( 'wp_register_font_provider' ) || ! function_exists( 'wp_register_fonts' ) ) {
                        return;
                }
```

#### Reproduce the fatal error

Before applying the changes from this PR (or comment out the BC Layer files loading in `lib/load.php`, refresh the admin page on your test site.

Expected: Fatal error such as:

```
Fatal error: Uncaught Error: Call to undefined function wp_register_font_provider() in ../wp-content/plugins/webfonts-jetpack-test/webfonts.php:79
```

the path to the `webfonts.php` will be different in your test site.

This fatal error happens because the tester plugin is using the Fonts API but it is not loaded into memory.

#### Test this PR

1. Apply the changes from this PR to your local testing site.
2. Refresh the admin page.
Expected: No fatal error. There will be deprecation notices as the tester plugin is using the Fonts API (which is now deprecated).
3. Check that none of the Google Fonts from the tester plugin are in the font pickers:
   a. Go to Site Editor > Styles > Typography > Headings.
   b. Select "FONT".
Expected: Google Fonts such as Arvo, Merriweather, Open Sans, etc. are not in the list. Rather, only the theme's fonts in the list.

Using TT3, the FONT picker should contain:
- Default
- DM Sans
- IBM Plex Mono
- Inter
- System Font
- Source Serif Pro
Screen Shot 2023-07-11 at 3 48 19 PM

Note: To see all of the Google Fonts the tester plugin registers, remove the `true` so that the Font Face libs are not loaded.

### CODE REVIEW

**Comment by anton-vlasenko** [comment]
## Test Report
PR tested: https://github.com/WordPress/gutenberg/pull/52485

### Environment
- WordPress: 6.3-beta3-56130-src
- PHP: 8.0.27
- Server: Apache/2.4.55 (Unix) PHP/8.0.27
- Database: mysqli (Server: 5.7.38 / Client: mysqlnd 8.0.27)
- Browser: Safari 16.5 (macOS)
- Theme: Twenty Twenty-Three 1.1
- MU-Plugins: None activated
- Plugins: 
  * Fonts API Test Plugin 1.0.0-ironprogrammer
  * Gutenberg 16.2.0-rc.1

### Steps to Test
Follow the steps listed in the PR's description above.

### Expected Results
1. Fatal error
```
Uncaught Error: Class 'WP_Fonts_Resolver' not found
```
occurs before applying the changes from this PR.
2. The font picker should contain the expected fonts.

### Actual Results
1. ❌ Fatal error `Uncaught Error: Class 'WP_Fonts_Resolver' not found` doesn't occur whether using the trunk branch or commenting out the BC layer files loading in `load.php`.
2. ✅ The font picker contains the expected fonts.

### Supplemental Artifacts

Screenshot 2023-07-14 at 01 07 30

**Review by anton-vlasenko — COMMENTED** [review]
The code LGTM.
However, I'm not sure why the fatal error doesn't occur when the BC layer files are not loaded. Please see my test report here: https://github.com/WordPress/gutenberg/pull/52485#issuecomment-1635050688.

File: lib/experimental/fonts/bc-layer/class-gutenberg-fonts-api-bc-layer.php [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+
+/**
+ * Class Gutenberg_Fonts_API_BC_Layer
+ *
+ * BACKPORT NOTE: Do not backport this file to Core.
+ *
+ * @since X.X.X
+ * @deprecated 16.3.0 Fonts API is not supported.
+ */
+class Gutenberg_Fonts_API_BC_Layer {
```
Comment (aristath) [inline lib/experimental/fonts/bc-layer/class-gutenberg-fonts-api-bc-layer.php:21]: Personal preference and definitely not a blocker, but couldn't we be more verbose?
`BC` can mean a lot of things, and `Backwards_Compatibility` may be a bit longer but is definitely easier to understand

**Review by aristath — APPROVED** [review]
Code LGTM 👍

File: lib/experimental/fonts/bc-layer/class-gutenberg-fonts-api-bc-layer.php (hunk 1 above)
Comment (hellofromtonya) [reply lib/experimental/fonts/bc-layer/class-gutenberg-fonts-api-bc-layer.php:21]: You're right @aristath that spelling out `Backwards_Compatibility` is more understandable. But it's too late to make that change.

Why is it too late to change?
This class already shipped in Gutenberg as part of the Fonts API. In this PR, the class name is copied here just in case an extender is using it.

**Comment by hellofromtonya** [comment]
>The code LGTM.
>However, I'm not sure why the fatal error doesn't occur when the BC layer files are not loaded. Please see my test report here: https://github.com/WordPress/gutenberg/pull/52485#issuecomment-1635050688.

Oh silly me 🤦‍♀️ Thanks @anton-vlasenko for flagging this. I missed a step in the Set up process and the fatal error is a different one.

I've updated the testing instructions. The tester plugin already guards against the functions not existing. By commenting out those lines of code, a fatal error will happen when it attempts to invoke `wp_register_font_provider()` when it does not exist in memory.

**Comment by anton-vlasenko** [comment]
> I've updated the testing instructions. The tester plugin already guards against the functions not existing. By commenting out those lines of code, a fatal error will happen when it attempts to invoke `wp_register_font_provider()` when it does not exist in memory.

Thank you, @hellofromtonya. I'm able to reproduce the fatal error now.

**Review by anton-vlasenko — APPROVED** [review]
LGTM ✅.

**Comment by hellofromtonya** [comment]
Thank you @aristath and @anton-vlasenko 🎉 Merging now.

**Comment by hellofromtonya** [comment]
Removed `Needs PHP backport` label as this PR will not be backported to Core. The Fonts API is deprecated within the plugin.
