### PR TITLE
[Components - ToggleGroupControl]: Fix visual state when no option is selected

### LINKED ISSUE #35383: ToggleGroupControl: Visual state of an undefined value is inconsistent
### Description

The visual state of an initial undefined `value` is different from when the value is set _back_ to undefined after being set to a defined value.

### Step-by-step reproduction instructions

1. Render a `ToggleGroupControl` with `value` initially undefined.
2. Render a `button` with an `onClick` to set the `value` to undefined.
3. Click on one of the toggle group options, then click the reset button.

https://codesandbox.io/s/togglegroupcontrol-undefined-state-h8z9q?file=/src/App.js

### Screenshots, screen recording, code snippet

An initial undefined value looks different from when the value is set from a truthy value back to undefined

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ntsekouras**
Fixes: https://github.com/WordPress/gutenberg/issues/35383

When we pass a value to `ToggleGroupControl` that doesn't exist in the available options the backdrop should not be visible.

## Testing instructions
1. Run storybook
2. Check the `With Reset` story
3. Observe that the backdrop is not visible when we reset.

The case is being discussed here: https://github.com/WordPress/gutenberg/pull/35395/files#r726460400 and previous mention to the existing code about `targetNode` is [here](https://github.com/WordPress/gutenberg/pull/31937#discussion_r666004949).

>The thing is that this is probably related to Reakit and was related to the fix here: #35409 (that got removed now). The problem is probably that if we have a value in Reakit state that doesn't exist in our options, the currentId is filled with the first available option, which is not what we want. Reakit docs state that if we pass null the currentId will not be set, but with some tests of mine, it still had the first option as value.

--cc @sRahul-00

### CODE REVIEW

**Review by ciampo — COMMENTED** [review]
Testing the Storybook example, the problem seems to be solved.

I have a question though: with this fix, we're rendering `BackdropView` with a width of `0`. Should we instead look into _not rendering_ that component at all?

**Comment by ntsekouras** [comment]
> I have a question though: with this fix, we're rendering BackdropView with a width of 0. Should we instead look into not rendering that component at all, instead?

I updated the code 😄

File: packages/components/src/toggle-group-control/toggle-group-control-backdrop.tsx [hunk 1]
```diff
@@ -18,6 +18,7 @@ function ToggleGroupControlBackdrop( {
 	const [ left, setLeft ] = useState( 0 );
 	const [ width, setWidth ] = useState( 0 );
 	const [ canAnimate, setCanAnimate ] = useState( false );
+	const [ renderBackdrop, setRenderBackdrop ] = useState( true );
```
Comment (ciampo) [inline packages/components/src/toggle-group-control/toggle-group-control-backdrop.tsx]: Would `false` be a better initial value here? I like the idea of rendering `BackdropView` lazily and only when necessary.

**Review by ciampo — APPROVED** [review]
Thank you for Changes LGTM!

I left a small comment, feel free to address it and merge after that.

File: packages/components/src/toggle-group-control/toggle-group-control-backdrop.tsx (hunk 1 above)
Comment (ntsekouras) [reply packages/components/src/toggle-group-control/toggle-group-control-backdrop.tsx]: I changed it. Thanks for the review!
