### PR TITLE
RichText: fix tree output after applying format

### LINKED ISSUE #12314: Applied formats should produce optimized HTML
**Describe the behavior**
When you apply multiple formats to the text when using `RichText`. It doesn't always produce optimal HTML code. In many cases the order of application matters producing different HTML. In the case I recorded, it produces two links instead of one.

**To Reproduce**
1. Create a new post.
2. Type a few words in a paragraph.
3. Apply `bold` to one of the words.
4. Apply `italics` to the part of the bolded word.
5. Apply `link` to the full bolded word.
6. You should see something like the following when checking HTML source:
```html
<p>My <strong><a href="http://localhost:8888/?page_id=2">te</a><em><a href="http://localhost:8888/?page_id=2">xt</a></em></strong> to test</p>
```

**Expected behavior**
Wrap text with only one link in all cases, no matter in what order formats get applied. The HTML should look like:

```html
<p>My <a href="http://localhost:8888/?page_id=2"><strong>te<em>xt</em></strong></a> to test</p>
```

**Screenshots**
rich text formats

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 70

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #12314. Still needs some additional tests.

Problem: Applying a format around an existing format (greater selection), will chop the applied format into 2-3 pieces. Why? Because the format is just added at the end of each format array at every index:

```
     1111
111110000
link bold
     link
```

Instead, this should be:

```
     0000
111111111
link bold
     link
```

Solution: check the position at which to insert first. This should be the lowest value between the start and end indices.

## How has this been tested?

Make something bold. Select the bolded text, including something more. Now link it. The link should not be split into two elements.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/rich-text/src/apply-format.js [hunk 1]
```diff
@@ -60,19 +70,23 @@ export function applyFormat(
...
+					.filter( ( { type } ) => type !== format.type );
+			} else {
+				newFormats[ index ] = [];
+			}
 		}
-	}
 
-	return normaliseFormats( { ...value, formats: newFormats } );
-}
+		const position = Math.min(
```
Comment (aduth) [inline packages/rich-text/src/apply-format.js]: I've been staring at this for a while trying to understand, and am having trouble grasping why it matters the number of formats at the start or end of the fragment of text. Should it not instead be some result of whichever format is applied to the broadest selection? Or is that an indirect result of this logic?

Comment (ellatrix) [reply packages/rich-text/src/apply-format.js]: Yes, you're right, it doesn't account for the following case:

```
22  33
111111
```

where you'd expect the format to be applied as follows:

```
22  33
444444
111111
```

Comment (ellatrix) [reply packages/rich-text/src/apply-format.js]: Fixed in a55ce96. Thanks!

**Review by draganescu — APPROVED** [review]
I tested locally and it solves the problem as described. Reading the code I don't spot any problem.
Minor thing @ellatrix while the solution here solves the problem there is another inconsistent behavior:

- in a selection containing `test text <b>bold item</b><em>italic!</em>` applying a link results in `<a href='#'>test text <b>bold item</b><em>italic!</em></a>`
- YET in a selection containing only`<b>bold item</b>` applying a link results in `<b><a href='#'>bold item</a></b>`

However I am unsure if this is in the scope of this fix, so I say we merge this as it is.

**Comment by ellatrix** [comment]
@draganescu Thanks for reviewing! I don't see a problem there, what's wrong with the second case?

**Comment by draganescu** [comment]
@ellatrix it might not be a problem, the difference is that in the first case the link tags wrap the content and any tags, and in the second case the link tag is placed inside the outer tag. It just doesn't work the same, maybe it doesn't have to, I just noticed :) otherwise no issue.

**Comment by ellatrix** [comment]
Thanks @draganescu. I didn't really think much of it, but you have a point. Maybe the rule for applying tags should be: wrap as much content as possible. Currently it seems to be: wrap as little content as possible.
