### PR TITLE
Fix the navigate regions focus style

### LINKED ISSUE #21717: Regression: the navigate region focus style is broken
**Describe the bug**
When jumping through the main ARIA landmarks in the editor (also known as "navigate-region" component) via the dedicated keyboard shortcuts, the focus style of the regions is broken, in slightly different ways on different browsers.

**To reproduce**
- Test in different browsers, also on Windows.
- Use the keyboard shortcuts to navigate through the landmarks.
- on macOS:
  - Ctrl+backtick
  - Shift+Ctrl+backtick
- on Windows (if I'm not mistaken):
  - Shift+Alt+N
  - Shift+Alt+P
- see the focus style is broken on some of the regions

**Expected behavior**
The focus style to always be clearly visible.

**Note**
This style broke a few times during the project history. Maybe worth considering a different, more solid, _testable_, implementation.

**Screenshots**

With Gutenberg plugin activated.

Chrome Windows: content region focused: the style is visible only in the part of the UI close to the browser scrollbar:

Screenshot (95) content

Chrome Windows: sidebar region focused: the style is barely visible:

Screenshot (96) sidebar

Chrome macOS content region: no style visible:

chrome content

Chrome macOS sidebar region: style barely visible:

chrome sidebar

Chrome macOS publish region: no style visible:

chrome publish

Firefox macOS sidebar region: style breaks but in a different way:

firefox sidebar

**Editor version (please complete the following information):**
- can reproduce with slightly different results on both:
  - default editor shipped with WP 5.4
  - plugin version 7.9.1

### PR DESCRIPTION
**Pull request by afercia**
Fixes https://github.com/WordPress/gutenberg/issues/21717

## What?

When navigating through the editor regions via the dedicated keyboard shortcuts, the focused region should show a blue outline as focus indicator. This used to work well in https://github.com/WordPress/gutenberg/pull/8554 but it's broken since at least 2 years and a half, see https://github.com/WordPress/gutenberg/issues/21717

It appears that new layouts and features introduced over time didn't take into consideration the navigable regions need to have a focus style. There are two main issues that make the focus style not visible:
1. Sometimes, the region contains elements with a higher z-index which partially or completely covers the focus outline.
2. Sometimes, the region doesn't have a computed size because its content is absolutely positioned (or it's fixed) so the outline isn't visible because it's set on an element that has a 0px by 0px size.

Screenshot to illustrate the z-index issue:

Screenshot 2022-10-28 at 09 47 48

Screenshot to illustrate the 0 size issue (this is the Publish panel toggle button, see there's no focus style on its wrapper region):

Screenshot 2022-10-28 at 09 49 35

The original purpose of these regions is to allow keyboard navigation through the main parts of the editor and show a focus style. They're now also used for layout purposes, as parts of the 'interface skeleton', which is fine. However, it's very important  to keep in mind that:
- The regions must have a computed size.
- The regions focus style needs to be 'on top' of any other content within the region.

## Why?
A clear focus indicator is a basic accessibility requirement for all sighted keyboard users, as they need to see where focus is.

## How?

- Simplified the `navigateRegions` CSS as we don't need a fix for IE11 any longer. Note: we can't use a CSS pseudo element as suggested in https://github.com/WordPress/gutenberg/issues/21717 because the pseudo element would scroll together wit the content.
- Added a new `NavigableRegion` component to abstract the markup and features of the ARIA regions.
- `NavigableRegion` renders the focusable ARIA landmark region and a child container.
- The child container is responsible to set a negative `z-index: -1` so that any content within the region is positioned in the Z-axis at a lower level than the wrapper.
- This way, the focus indicator on the wrapper is always visible.
- The child container also establishes a new stacking context so that any layering within it should still work as expected.
- This solves the first issue related to z-indexes.
- Instead, the size issue can't be solved with a generic fix.
- Therefore, this PR adds some exceptions to cover these edge cases.
- I opted to add these exceptions in the `navigateRegions` stylesheet.
- Ideally, these exceptions should be removed in the future and we should make sure the layout always makes the regions have a size.

## Testing Instructions

- Go to the Post editor.
- Click on any empty part of the UI.
- Navigate through the editor regions by pressing Cmd + backtick (on macOS)
- Note: for keyboard layouts other than English and for Windows, see alternative keyboard shortcuts at: Options > Keyboard shortcuts > Global shortcuts > Navigate to the next part of the editor.
- Check that when focus lands on an editor region there's a clearly visible blue outline around the region.
- Test with the Setting sidebar closed ad opened.
- Test with the Publish sidebar opened.
- Test with the List View sidebar opened.
- Test with the 'Distraction free' mode enabled.
- Go to the Site Editor.
- Navigate through the editor regions.
- Check that blue outline on the focused region is clearly visible.
- Test with the sidebars closed and opened, especially the Navigation sidebar.
- Activate the Twenty Twenty-One theme to make the Widgets page available in the WP admin.
- Go to the Widgets page.
- Click on any empty part of the Widgets page.
- Navigate through the regions.
- Check that blue outline on the focused region is clearly visible.

## Screenshots or screencast 

Animated GIF to illustrates the navigate regions focus style in action in the Post editor.

navigateregion

### CODE REVIEW

**Comment by afercia** [comment]
Rebased on latest trunk after changes for the new theming accent color, see https://github.com/WordPress/gutenberg/pull/45289

**Review by aristath — APPROVED** [review]
Code looks good to me, and it fixes the focus issue 👍

File: packages/interface/src/components/navigable-region/index.js [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+
+	return (
+		<Tag
+			className={ classnames( 'interface-navigable-region', className ) }
+			aria-label={ ariaLabel }
+			role="region"
+			tabIndex="-1"
+			{ ...motionProps }
+		>
+			<div className="interface-navigable-region__stacker">
```
Comment (jffng) [inline packages/interface/src/components/navigable-region/index.js:27]: Noting that this may have caused a regression: https://github.com/WordPress/gutenberg/issues/45778

A fix could be to set the display + flex direction on this `__stacker` class, but I'm not familiar enough with the change to be sure.

Comment (Mamaduka) [reply packages/interface/src/components/navigable-region/index.js:27]: I can confirm this. The same is visible in the post editor if a theme has a non-white background.

Comment (afercia) [reply packages/interface/src/components/navigable-region/index.js:27]: Looking into this!

File: packages/interface/src/components/navigable-region/README.md [hunk 2]
```diff
@@ -0,0 +1,38 @@
+# NavigableRegion
```
Comment (youknowriad) [inline packages/interface/src/components/navigable-region/README.md:1]: I wonder if this should be moved to the components package insect it's meant to be used in conjunction with useNavigateRegions from that package.

File: packages/interface/complementary-area-context/index.js [hunk 3]
```diff
@@ -0,0 +1,12 @@
+/**
+ * WordPress dependencies
+ */
+import { withPluginContext } from '@wordpress/plugins';
+
+export default withPluginContext( ( context, ownProps ) => {
```
Comment (talldan) [inline packages/interface/complementary-area-context/index.js:6]: @afercia @aristath Just wondering if this file should be in the `src` folder of the package?

I'm not familiar with the PR, but just spotted this file when browsing the codebase, so I may be wrong.
