### PR TITLE
Block Editor: Fix Columns block horizontal spacing when setting vertical gap

### LINKED ISSUE #45277: Columns block: changing the vertical block spacing also wrongly changes the horizontal block spacing
### Description

Changing the vertical block spacing of the columns block also changes the horizontal block spacing, which isn't the expected behavior. The horizontal block spacing should keep its default value.

### Step-by-step reproduction instructions

1. Using the Twenty Twenty-Three theme, insert two columns by pasting the following code.

```
<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"style":{"spacing":{"padding":{"top":"var:preset|spacing|30","right":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30"}}},"backgroundColor":"primary"} -->
<div class="wp-block-column has-primary-background-color has-background" style="padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30)"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut leo nibh, placerat eget nisi non, sagittis convallis purus.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"spacing":{"padding":{"top":"var:preset|spacing|30","right":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30"}}},"backgroundColor":"primary"} -->
<div class="wp-block-column has-primary-background-color has-background" style="padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30)"><!-- wp:paragraph -->
<p>Morbi in iaculis ligula. Mauris in libero suscipit, pulvinar erat a, rutrum purus.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

By default, the horizontal spacing is set by the theme.json file with a value of 1.5rem.

2. Select the columns block. In the settings sidebar, change only the vertical block spacing. 
Inside the editor, observe that the horizontal spacing has changed to 0.5em.

```
.editor-styles-wrapper .wp-block-columns.wp-container-1 {
    gap: var(--wp--preset--spacing--60) 0.5em;
}
```

3. On the front end, the horizontal spacing has changed to 2em.

```
.wp-block-columns.wp-container-1 {
    flex-wrap: nowrap;
    gap: var(--wp--preset--spacing--60) 2em;
}
```

I expect the horizontal spacing to keep the default value (1.5rem for Twenty Twenty-Three).

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 6.1 RC2 with/without Gutenberg 14.3.1
- Twenty Twenty-Three theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mustafabharmal**
## What?
Closes #45277

Fixes an issue where changing only the vertical block spacing in the Columns block incorrectly changes the horizontal spacing to hardcoded values instead of maintaining the theme.json default.

## Why?

The Columns block uses a flex layout, and when users set only vertical spacing, the horizontal spacing should maintain its default value from theme.json (e.g., 1.5rem in Twenty Twenty-Three). Instead, it was falling back to hardcoded values:
- `0.5em` in the editor
- `2em` on the frontend

## How?

Updated the `getLayoutStyle` function in both `flex.js` and `grid.js` to:
1. Accept the `globalBlockGapValue` parameter (already passed from the layout hook)
2. Calculate a proper `fallbackGapValue` from `globalBlockGapValue` before processing user-defined spacing
3. Use this theme-aware fallback instead of the hardcoded `0.5em` default

This ensures that when users set only one axis of spacing (vertical or horizontal), the other axis uses the theme's default blockGap value instead of an arbitrary hardcoded value.

### Setup
1. Use the any theme with a custom blockGap in theme.json
2. Add a Columns block with two columns for ref use below code. 

```
<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"style":{"spacing":{"padding":{"top":"var:preset|spacing|30","right":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30"}}},"backgroundColor":"primary"} -->
<div class="wp-block-column has-primary-background-color has-background" style="padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30)"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut leo nibh, placerat eget nisi non, sagittis convallis purus.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"spacing":{"padding":{"top":"var:preset|spacing|30","right":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30"}}},"backgroundColor":"primary"} -->
<div class="wp-block-column has-primary-background-color has-background" style="padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30)"><!-- wp:paragraph -->
<p>Morbi in iaculis ligula. Mauris in libero suscipit, pulvinar erat a, rutrum purus.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```
### Before the fix
1. In the block settings sidebar, change only the **vertical** block spacing
2. Inspect the generated CSS
3. The horizontal gap incorrectly changes to `0.5em` in editor, `2em` on frontend

### After the fix
1. In the block settings sidebar, change only the **vertical** block spacing 
2. Inspect the generated CSS
3. The horizontal gap maintains the theme default 

## Screenshots or screencast 

Before:

https://github.com/user-attachments/assets/d8f056e0-0e96-4515-b00b-90a4501f49c9

After:

https://github.com/user-attachments/assets/d9d8da39-6bab-4d24-96e9-e81302cd2c3a

### CODE REVIEW

File: packages/block-editor/src/layouts/grid.js [hunk 1]
```diff
@@ -139,24 +139,24 @@ export default {
...
-
-		// Use the global blockGap value for grid column calculations when available
-		// If the gap value has both top and left (separated by space), use the left value for horizontal calculations
+		// Use the global blockGap value as fallback when available.
+		// If the gap value has both top and left (separated by space), use the left value for horizontal calculations.
 		let fallbackGapValue = '1.2rem';
 		if ( globalBlockGapValue ) {
 			const processedGap = getGapCSSValue( globalBlockGapValue, '0.5em' );
-			const gapParts = processedGap.split( ' ' );
+			const gapParts = processedGap?.split( ' ' ) || [];
```
Comment (tellthemachines) [inline packages/block-editor/src/layouts/grid.js]: We don't need to safeguard against a null `globalBlockGapValue` because if that's the case this whole code block won't run.

**Review by tellthemachines — APPROVED** [review]
Thanks for fixing this! LGTM and works as expected. Just one very minor comment below.

Fortunately this doesn't require equivalent changes to the PHP because it's already working well on that side 🙂
