### PR TITLE
Change resource URL in source map for @wordpress packages.

### LINKED ISSUE #55068: Plugin source maps contain incorrect source paths
### Description

When sourcemaps are generated for the Gutenberg plugin, a final source map includes a "sources" section pointing back to the original source files. This can be useful for tools which might map a stack trace to a source file in GitHub.

An example source path for the plugin looks like this: `webpack://wp/./packages/annotations/build-module/format/@wordpress/annotations/src/format/annotation.js`.

With the duplicate path in the string, it's not immediately correct. (Though you could manually edit it with a script pretty easily.)

After digging into the webpack config, I believe this happens because our babel transform step happens outside of webpack. Webpack ultimately imports the `build-module` code already generated by `bin/packages/build.js` (which runs babel transform), and this code already includes source maps. In _those_ files, the source file points to `@wordpress/annotations/src/format/annotation.js`, for example.

I think when webpack transforms those sources, it sees the original directory of the file it imports as `packages/annotations/build-module/format`, but when it tries to look up the file name, it gets `@wordpress/annotations/src/format/annotation.js` and combines the two strings.

I'm not yet sure the best approach for fixing this, as this `@wordpress/` source map is technically correct if you were consuming the source map as a 3rd party package from npm.

### Step-by-step reproduction instructions

Inspect the source maps included in the plugin release.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by torounit**
## What?

Change the URL of `@wordpress` packages referenced in the source map. Specifically, the following will be used.

before: `webpack://wp/packages/a11y/build-module/@wordpress/a11y/src/index.js`
after: `../../packages/a11y/src/index.js`

## Why?

When VS Code and a browser are linked, the actual file can be referenced from the debug console. Also, operations such as breakpoints can be performed from VS Code.

The lanch.json configuration is as follows

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch localhost",
			"type": "chrome",
			"request": "launch",
			"url": "http://localhost:8888/",
			"sourceMaps":true, 
			"trace": true
		},
	]
}
```

## How?

Set [`devtoolModuleFilenameTemplate`](https://webpack.js.org/configuration/output/#outputdevtoolmodulefilenametemplate) 

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/1908815/e050a1e2-b836-4c33-a582-7d368c785b30

### CODE REVIEW

**Comment by torounit** [comment]
@gziolo Could you review this PR?

**Comment by gziolo** [comment]
Hello, I don't have much experience configuring source maps with webpack. I landed 4 years ago PR https://github.com/WordPress/gutenberg/pull/17024 that set a constant namespace with `devtoolNamespace` to make source maps work correctly with Firefox. I can help land this change, but we need to get some testing from other folks to ensure it works with devtools from Chrome, Safari and Firefox.

**Comment by torounit** [comment]
#### screenshot of chrome.




#### screenshot of firefox.



#### screenshot of safari


firefox and chome will jump to the original source code.

File: tools/webpack/packages.js [hunk 1]
```diff
@@ -142,6 +142,14 @@ module.exports = {
...
 		filename: './build/[name]/index.min.js',
 		path: join( __dirname, '..', '..' ),
+		devtoolModuleFilenameTemplate: ( info ) => {
+			if ( info.resourcePath.includes( '@wordpress' ) ) {
+				const resourcePath =
+					info.resourcePath.split( '@wordpress' )[ 1 ];
+				return `../../packages/${ resourcePath }`;
+			}
+			return `webpack://${ info.namespace }/${ info.resourcePath }`;
+		},
```
Comment (t-hamano) [inline tools/webpack/packages.js]: I noticed that I have a duplicate slash.

double-border

Additionally, to check namespaces more strictly, how about the following change? Even on Windows, `info.resourcePath` had a forward slash instead of a backslash as the path separator, so I think this style is fine.

```suggestion
		devtoolModuleFilenameTemplate: ( info ) => {
			if ( info.resourcePath.includes( '/@wordpress/' ) ) {
				const resourcePath =
					info.resourcePath.split( '/@wordpress/' )[ 1 ];
				return `../../packages/${ resourcePath }`;
			}
			return `webpack://${ info.namespace }/${ info.resourcePath }`;
		},
```

**Review by t-hamano — COMMENTED** [review]
It seems to work as expected on Windows OS 👍

### Chrome

chrome

### Firefox

firefox

File: tools/webpack/packages.js (hunk 1 above)
Comment (torounit) [reply tools/webpack/packages.js]: @t-hamano I missed it. Thank you !

**Comment by youknowriad** [comment]
As long as it's about the source map generated by the plugin and not by the packages, it's good to go (since it has been tested). I wonder if a similar change is needed on Core.

**Comment by torounit** [comment]
@youknowriad 
In the case of core, there are no packages under the document root, so this is probably unnecessary.

**Review by noahtallen — APPROVED** [review]
I confirmed the sourcemaps for packages are the same (which makes sense, since those aren't generated by webpack). Looking at the sourcemaps for `@wordpress/annotations` (under `build/annotations`):

before:
```json
	"sources": [
		"webpack://wp/webpack/bootstrap",
		"webpack://wp/webpack/runtime/define property getters",
		"webpack://wp/webpack/runtime/hasOwnProperty shorthand",
		"webpack://wp/webpack/runtime/make namespace object",
		"webpack://wp/external window [\"wp\",\"richText\"]",
		"webpack://wp/external window [\"wp\",\"i18n\"]",
		"webpack://wp/./packages/annotations/build-module/store/@wordpress/annotations/src/store/constants.js",
		"webpack://wp/./packages/annotations/build-module/format/@wordpress/annotations/src/format/annotation.js",
		"webpack://wp/./packages/annotations/build-module/format/@wordpress/annotations/src/format/index.js",
		"webpack://wp/external window [\"wp\",\"hooks\"]",
		"webpack://wp/external window [\"wp\",\"data\"]",
		"webpack://wp/./packages/annotations/build-module/store/@wordpress/annotations/src/store/reducer.js",
		"webpack://wp/./packages/annotations/build-module/block/@wordpress/annotations/src/block/index.js",
		"webpack://wp/./node_modules/rememo/rememo.js",
		"webpack://wp/./packages/annotations/build-module/store/@wordpress/annotations/src/store/selectors.js",
		"webpack://wp/./packages/annotations/node_modules/uuid/dist/esm-browser/rng.js",
		"webpack://wp/./packages/annotations/node_modules/uuid/dist/esm-browser/stringify.js",
		"webpack://wp/./packages/annotations/node_modules/uuid/dist/esm-browser/regex.js",
		"webpack://wp/./packages/annotations/node_modules/uuid/dist/esm-browser/validate.js",
		"webpack://wp/./packages/annotations/node_modules/uuid/dist/esm-browser/v4.js",
		"webpack://wp/./packages/annotations/build-module/store/@wordpress/annotations/src/store/actions.js",
		"webpack://wp/./packages/annotations/build-module/store/@wordpress/annotations/src/store/index.js"
	],
```

after:

```json
	"sources": [
		"webpack://wp/webpack/bootstrap",
		"webpack://wp/webpack/runtime/define property getters",
		"webpack://wp/webpack/runtime/hasOwnProperty shorthand",
		"webpack://wp/webpack/runtime/make namespace object",
		"webpack://wp/external window [\"wp\",\"richText\"]",
		"webpack://wp/external window [\"wp\",\"i18n\"]",
		"../../packages/annotations/src/store/constants.js",
		"../../packages/annotations/src/format/annotation.js",
		"../../packages/annotations/src/format/index.js",
		"webpack://wp/external window [\"wp\",\"hooks\"]",
		"webpack://wp/external window [\"wp\",\"data\"]",
		"../../packages/annotations/src/store/reducer.js",
		"../../packages/annotations/src/block/index.js",
		"webpack://wp/./node_modules/rememo/rememo.js",
		"../../packages/annotations/src/store/selectors.js",
		"webpack://wp/./packages/annotations/node_modules/uuid/dist/esm-browser/rng.js",
		"webpack://wp/./packages/annotations/node_modules/uuid/dist/esm-browser/stringify.js",
		"webpack://wp/./packages/annotations/node_modules/uuid/dist/esm-browser/regex.js",
		"webpack://wp/./packages/annotations/node_modules/uuid/dist/esm-browser/validate.js",
		"webpack://wp/./packages/annotations/node_modules/uuid/dist/esm-browser/v4.js",
		"../../packages/annotations/src/store/actions.js",
		"../../packages/annotations/src/store/index.js"
	],
```

This makes sense to me 👍

**Comment by noahtallen** [comment]
I will go ahead and merge it, since @youknowriad said it is good to go.
