### PR TITLE
fix: [#21810] Allow default pasting behaviour in FontSizePicker

### LINKED ISSUE #21810: Pasting in FontSizePicker replaces the block itself
**Describe the bug**
Pasting a custom value in "Custom" size block replaces the block itself.
image

**To reproduce**
Steps to reproduce the behaviour:
1. Go to Pages and try to edit a page.
2. Click on text block and empty the custom field.
3. Paste a number in custom field.
4. See that your text block is replaced.

**Expected behaviour**
The size should be pasted in the field

**Screenshots**

**Editor version:**
- WordPress version: (5.5-alpha-47610)
- Gutenberg version: Version 7.9.1 default setting

**Desktop:**
 - OS: Mac OS
 - Browser Chrome 81

### PR DESCRIPTION
**Pull request by kirilzh**
## Description
Fixes: #21810
Default paste behavior is not allowed for input fields. 

## Types of changes
Bug fix, non-breaking change.
Handling the case when you want to paste in an input field. 

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/block-editor/src/components/copy-handler/index.js [hunk 1]
```diff
@@ -11,6 +11,10 @@ import { compose } from '@wordpress/compose';
  */
 import { getPasteEventData } from '../../utils/get-paste-event-data';
 
+function isNativePasteEvent( event ) {
+	return event.type === 'paste' && event.target.tagName === 'INPUT';
```
Comment (youknowriad) [inline packages/block-editor/src/components/copy-handler/index.js:15]: Is this the right check here, won't we have the same issues for contenteditables, textareas....
I feel the intent here is more: 

 - trigger the native paste behavior if the target is inside the editor canvas 

I believe the main issue here is that there's React event bubbling happening instead of native DOM event bubbling triggering the onPaste handler when it shouldn't. 

One option to solve this is to avoid the React handlers or to check the `event.target` inside the handlers.

Comment (kirilzh) [reply packages/block-editor/src/components/copy-handler/index.js:15]: I was thinking it was more of an isolated case hence treating the symptoms rather than the cause. Will look into your suggestions.

Comment (kirilzh) [reply packages/block-editor/src/components/copy-handler/index.js]: Updated the PR.

File: packages/block-editor/src/components/copy-handler/index.js [hunk 2]
```diff
@@ -1,77 +1,84 @@
...
+		getSettings,
+	} = useSelect( ( select ) => select( 'core/block-editor' ), [] );
+
+	const { removeBlocks, replaceBlocks } = useDispatch( 'core/block-editor' );
+
+	const {
+		__experimentalCanUserUseUnfilteredHTML: canUserUseUnfilteredHTML,
+	} = getSettings();
+
+	const handler = ( event ) => {
```
Comment (youknowriad) [inline packages/block-editor/src/components/copy-handler/index.js:31]: There's one small difference that potentially can have performance impact. Since this is an inline function, potentially, this could rerender children often. I think it's good to start like you did (without any memoization) but we just need to check that the component is not being rerendered on each "store change".

For instance you can add a "console log" inside the component and type on a paragraph and see if the logging is repeated or not as you type.

File: packages/block-editor/src/components/copy-handler/index.js [hunk 3]
```diff
@@ -1,77 +1,84 @@
 /**
  * WordPress dependencies
  */
+
```
Comment (youknowriad) [inline packages/block-editor/src/components/copy-handler/index.js:4]: Seems like a useless new line

File: packages/block-editor/src/components/copy-handler/index.js [hunk 4]
```diff
@@ -1,77 +1,84 @@
...
 import { documentHasSelection } from '@wordpress/dom';
-import { withDispatch } from '@wordpress/data';
-import { compose } from '@wordpress/compose';
+import { useDispatch, useSelect } from '@wordpress/data';
 
 /**
  * Internal dependencies
  */
 import { getPasteEventData } from '../../utils/get-paste-event-data';
+import { useRef } from '@wordpress/element';
```
Comment (youknowriad) [inline packages/block-editor/src/components/copy-handler/index.js:13]: This should be moved to the WP dependencies section

File: packages/block-editor/src/components/copy-handler/index.js (hunk 2 above)
Comment (kirilzh) [reply packages/block-editor/src/components/copy-handler/index.js:30]: While typing console.log is not executed. When copying/pasting there are two statements in console.

Comment (youknowriad) [reply packages/block-editor/src/components/copy-handler/index.js:30]: That's fine :) Thanks for the tests

**Review by youknowriad — APPROVED** [review]
