### PR TITLE
Fix CSS Custom Properties for presets in the site editor

### LINKED ISSUE #30642: [FSE] Gradient color options greyed out
## Description

When trying to set certain Global Styles, the gradient color options are greyed out making it impossible to see what colors you're selecting from. 

This seems to have perhaps recently broken since I can see previous issues like https://github.com/WordPress/gutenberg/issues/28781 where this was working. 

## Step-by-step reproduction instructions
1. Create/use a site with FSE capabilities.
2. Open the site editor and open global styles
3. Select the Root options or specific By Block options that have the option for gradients.
4. View gradients and see the options are greyed out making it impossible to see what colors you're picking. 

## Expected behaviour

I expect to be able to see the gradients.

## Actual behaviour

The gradient colors are greyed out. 

## Screenshots or screen recording (optional)

Screen Shot 2021-04-08 at 4 41 42 PM

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.3.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Chrome v 89

### PR DESCRIPTION
**Pull request by oandregal**
Fixes https://github.com/WordPress/gutenberg/issues/30642

This PR enqueues the CSS Custom Properties coming from the `theme.json` in a different way.

**Before**

We enqueued them via the `styles` key in the block editor settings. By doing this the styles are wrapped with the `.editor-styles-wrapper` class, for them to be scoped to the content canvas. This was problematic for the CSS Custom Properties, as they wouldn't be available in the sidebar, hence, we added `__experimentalNoWrapper` to the styles transformation, a scape hatch for certain styles not to be wrapped via `.editor-styles-wrapper`.

**After**

We enqueue the vars via the `enqueue_block_editor_assets` that is unaffected by the `.editor-styles-wrapper` mechanism.

## How to test

See testing instructions in the issue.

In addition to testing that the gradients are visible, I've also tested that, in the site editor, modifications to the solid colors are reflected in the own component  (sidebar) and in the content canvas. I've also applied this PR on top of https://github.com/WordPress/gutenberg/pull/36820 to make sure gradients work as expected as well.

### CODE REVIEW

File: lib/global-styles.php [hunk 1]
```diff
@@ -71,34 +71,22 @@ function_exists( 'gutenberg_is_edit_site_page' ) &&
 		}
 
 		$new_global_styles = array();
-		$new_presets       = array(
-			array(
-				'css'                     => 'variables',
```
Comment (oandregal) [inline lib/global-styles.php:76]: We no longer pass the CSS variables via the block editor settings and tell the editor not to wrap them. Instead, we enqueue them via the `enqueue_block_editor_assets` filter.

File: packages/block-editor/src/utils/transform-styles/index.js [hunk 2]
```diff
@@ -23,23 +23,20 @@ import wrap from './transforms/wrap';
  * @return {Array} converted rules.
  */
 const transformStyles = ( styles, wrapperClassName = '' ) => {
-	return map(
-		styles,
-		( { css, baseURL, __experimentalNoWrapper = false } ) => {
```
Comment (oandregal) [inline packages/block-editor/src/utils/transform-styles/index.js:28]: We no longer need the `__experimentalNoWrapper` so this is an extra win.

File: lib/global-styles.php [hunk 3]
```diff
@@ -304,3 +302,5 @@ function gutenberg_global_styles_include_support_for_wp_variables( $allow_css, $
 add_filter( 'force_filtered_html_on_import', 'gutenberg_global_styles_force_filtered_html_on_import_filter', 999 );
 add_filter( 'safecss_filter_attr_allow_css', 'gutenberg_global_styles_include_support_for_wp_variables', 10, 2 );
 // This filter needs to be executed last.
+
+add_filter( 'enqueue_block_editor_assets', 'gutenberg_load_css_custom_properties' );
```
Comment (youknowriad) [inline lib/global-styles.php:306]: I think this was of loading styles is kind of deprecated to the iframing. cc @ellatrix

**Comment by youknowriad** [comment]
For me this issue is larger than just "loading styles". 

Basically we render these "previews" (the small circles) for gradients/colors in a lot of places, and we always relied on the fact that the previous use the actual value and are not dependent of a global CSS variable. 

So while the current PR solves the issue for the case where the custom CSS variable originates from theme.json, it doesn't solve if if the value of the gradient relied on a variable that is loaded in an editor styles for instance.

So this makes me wonder whether a potential fix could be to actually consider these small circles as "block previews". Meaning render a circle inside an iframe and use the same mechanism used for the block canvas. 

Also, it's not just about the circles, there's a lot of places where we want a "preview": the global styles preview on the global styles sidebar, the typography previews as well.

**Comment by youknowriad** [comment]
A similar but maybe simpler workaround to the proposed solution on this PR could be to "flag" (add some flag to the style object) the style and enqueue it outside the iframe as well. This would also only solve the issue if the custom CSS variable comes from theme.json.

**Comment by oandregal** [comment]
Oh, interesting. I'm not super familiar with how other parts of the editor interface work (previews, etc), although I see this approach is working and seems natural (3rd parties can use it as well). But I'll let others comment on the best direction to fix this.

File: lib/global-styles.php (hunk 3 above)
Comment (ellatrix) [reply lib/global-styles.php:306]: For them to load in the iframe, the styles need to be enqueued here:

https://github.com/WordPress/gutenberg/blob/e5234418780871ccf848bdbf21d8dd9a67b6963b/lib/client-assets.php#L710-L780

Comment (oandregal) [reply lib/global-styles.php:306]: Hey @ellatrix I've pushed the changes to use the function you mention, but it looks like it enqueues the given styles within the iframe. Or perhaps I need to do more things?

In this PR I'm actually trying to do the opposite: enqueue the styles outside the iframe, so they're available for the global styles sidebar.

This is the setup:

- Styles for the content, within the iframe: CSS vars + block styles. This is working fine and it's done at `gutenberg_experimental_global_styles_settings` (adds them to editor settings' styles key).
- Styles for the sidebar: only the CSS vars. So far, we've been using the same method than the content's styles but with an additional flag (`__experimentalNoWrapper`) so they weren't wrapped by `.editor-styles-wrapper` and so targeted the sidebar. This is what I'm struggling to see how to do in an iframed editor.

Comment (oandregal) [reply lib/global-styles.php:306]: Talked with ella in private and can confirm that using `enqueue_block_editor_assets` is fine. So, switching this back to the original direction.

**Comment by oandregal** [comment]
This is ready for another review and/or :+1:

**Comment by oandregal** [comment]
For the record, I see `Block_Fixture_Test::test_kses_doesnt_change_fixtures` is failing, but it's also failing in `trunk` and it's unrelated to this PR.

File: lib/global-styles.php (hunk 3 above)
Comment (ellatrix) [reply lib/global-styles.php:306]: `enqueue_block_editor_assets` is for the editor UI only, not the iframe. If you need it to load in both, you'll need to use both.

**Comment by oandregal** [comment]
@youknowriad @ellatrix is there anything left here that I should implement? It's working as expected for me:

- CSS vars are in the scope of the sidebar for post & site editor (`enqueue_block_editor_assets` filter)
- CSS vars are in the scope of the post content via `styles` key in the settings (server code)
- CSS vars are in the scope of the site editor content via `styles` key in the settings (client code)

**Review by youknowriad — APPROVED** [review]
I think this is a decent fix but I think longer term it's probably better to consider these small "preview" as actual BlockPreviews and just render the whole styles like in any preview.

**Comment by oandregal** [comment]
It appears this PR introduced a regression https://github.com/WordPress/gutenberg/issues/37292
