### PR TITLE
Classic Block: Always use modal and display block placeholder

### LINKED ISSUE #73891: InnerBlocks template={[['core/freeform']]} work incorrect in repeater system WP 6.9
### Description

I use the `<InnerBlocks template={[['core/freeform']]} />` field in my plugins to create a classic editor for my clients.

In my plugin template I initially have several elements in Gutenberg Block. The visualization worked correctly in WP 6.8.

Image

I see that in the current WordPress core 6.9 ``<InnerBlocks template={[['core/freeform']]} />` was opening in a **popup window** and this was breaking all my elements because it was showing a popup every time I opened the page in the editor and I **only saw the first element** of the Сlassic editor in the popup with my fields.

Image

-> IF you have several components `<InnerBlocks template={[['core/freeform']]} />` in one block it works incorrect.

Image

*In this video, I tried to show that if the component initially has two fields, then they work incorrectly

### Step-by-step reproduction instructions

You just need to add 3-4 `<InnerBlocks template={[['core/freeform']]} />` in one component

I tested it on [my plugin](https://github.com/BlackStar1991/timeline-full-widget)  in file -> [edit.js](https://github.com/BlackStar1991/timeline-full-widget/blob/main/src/item/edit.js)

### Screenshots, screen recording, code snippet

Please add some attribute that would return the component to its previous state, without popup.

### Environment info

WordPress v.6.8

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by t-hamano**
## What?

We plan to force the post editor to work as an iframe in WordPress 7.0. So I think it's time to retire the old inline editor.

## How?

In addition to removing code that is no longer necessary, this PR also displays a block placeholder when there is no content, which is consistent with the latest HTML block:

image

Accordingly, two changes will also be made:

- Stops modals from automatically opening when there is no content, because it could potentially insert multiple empty classic blocks at once.
- Prevent blocks from being deleted when a modal editor with no content is closed.

## Testing Instructions

Smoke test the block. The block should continue to work as before.

### CODE REVIEW

**Review by SirLouen — APPROVED** [review]
@t-hamano 
Won't this PR close #73891 ?
I have been unable to use the Timeline block from the reporter's repository:
https://gist.githubusercontent.com/SirLouen/c98765a7d5405301264037e17a2c49c2/raw/de4c480baeaae33fb8f239b5fff8d56cfbd5b205/blueprint.json
https://playground.wordpress.net/?blueprint-url=https%3A%2F%2Fgist.githubusercontent.com%2FSirLouen%2Fc98765a7d5405301264037e17a2c49c2%2Fraw%2Fde4c480baeaae33fb8f239b5fff8d56cfbd5b205%2Fblueprint.json&gutenberg-pr=74162&gutenberg-branch=trunk

I have not reviewed the code https://github.com/BlackStar1991/timeline-full-widget
But I simply registered the block via console for testing with the original conditions of #73891

Looks way more refined and better UX, and cleaner by avoiding the duplication of `ClassicEdit` component.

**Comment by t-hamano** [comment]
> Won't this PR close https://github.com/WordPress/gutenberg/issues/73891 ?

Yes. See https://github.com/WordPress/gutenberg/issues/73891#issuecomment-3681727065

**Comment by SirLouen** [comment]
> > Won't this PR close #73891 ?
> 
> Yes. See [#73891 (comment)](https://github.com/WordPress/gutenberg/issues/73891#issuecomment-3681727065)

Oh, for some reason I don't have the capability of linking PR to their respective Issues.

File: packages/block-library/src/freeform/edit.js [hunk 1]
```diff
@@ -57,227 +46,44 @@ export default function FreeformEdit( props ) {
...
-						if ( scrollContainer.scrollTop !== scrollPosition ) {
-							scrollContainer.scrollTop = scrollPosition;
+				{ isOpen && (
+					<ModalEdit
+						clientId={ clientId }
+						content={ content }
+						onClose={ () => setOpen( false ) }
+						onChange={ ( newContent ) =>
+							setAttributes( { content: newContent } )
 						}
```
Comment (talldan) [inline packages/block-library/src/freeform/edit.js:92]: I notice there's a focus loss issue when following these steps:
1. Add classic block
2. When the 'Edit contents' button is focused hit enter or space to edit
3. When the modal appears, tab to the text area and enter some text
4. Tab to the Save button and hit enter to save
5. Observe that with the 'Edit contents' button removed from the DOM, there's nowhere to transfer focus back to, so focus is lost

Perhaps a way around that is to focus the 'Edit' toolbar button in the `onChange` callback here.

**Comment by talldan** [comment]
I've tested a bit, and I think this works much better than the auto-opening modal—thanks for going that extra step, nice work!

I mentioned one focus loss issue that would be good to solve, hopefully that's easy enough.

File: packages/block-library/src/freeform/edit.js (hunk 1 above)
Comment (t-hamano) [reply packages/block-library/src/freeform/edit.js:92]: Nice catch! Fixed in c33e8a8bec759cab2462eca24913d0cb9d2879ba

**Review by talldan — APPROVED** [review]
Looks like a nice improvement 🎉

**Comment by BlackStar1991** [comment]
Can someone explain if the `<InnerBlocks template={[['core/freeform']]} />` template will work correctly for multiple elements with a placeholder string (if it is NOT EMPTY)? *with placeholder text
How can I test this for my plugin? Can someone provide a link to a new version of the WP?

*I really need a wysiwyg editor element for my plugins.

**Comment by talldan** [comment]
I believe the fix solves that use case. It'll be released in the next gutenberg release (22.4), so that's one way to test it.
