### PR TITLE
Block API: Fallback to all attributes when checking for unmodified block

### LINKED ISSUE #73851: isUnmodifiedDefaultBlock returns true if block is missing specified role from attributes
### Description

Relates to https://github.com/WordPress/gutenberg/pull/70897 I believe.

I dig this a lot, but it does fail to gracefully handle a default block without a content role assigned anywhere, instead reporting true regardless of any changes. 

IMO It should instead fall back to generic isUnmodifiedBlock behaviour if the specified role is not present on the block in question.

Obv simple fix is to just use the content role going forward, but this change definitely caught me flat footed and it took me a while to figure out why the block toolbar was missing from our custom paragraph blocks.

### Step-by-step reproduction instructions

1. create a new dummy block to use as a default without a "role": "content" prop set on any attributes, or just remove the role prop from paragraph block;
2. inserter always shows, toolbar is missing unless in top toolbar mode

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes #73851
This is a follow-up to #70764 and #70897.

PR adds fallback logic to `isUnmodifiedBlock` helper to maintainn original behavior for blocks that haven't yet started using attribute roles.

## Why?
Attribute roles are relatively new, and not all blocks have adopted them. The editor should maintain the previous behavior for them - check for any attribute modification as a fallback.

## Testing Instructions
1. Remove attribute roles for Paragraph block definition.
2. Open a post.
3. Type into the first empty paragraph.
4. Confirm that the empty block inserter isn't rendered after the content update.

### Testing Instructions for Keyboard
Same.

## Screencast

CleanShot 2025-12-10 at 08 22 18

### CODE REVIEW

File: packages/blocks/src/api/utils.js [hunk 1]
```diff
@@ -43,20 +43,27 @@ export function isUnmodifiedBlock( block, role ) {
...
 		? Object.entries( blockAttributes ).filter( ( [ key, definition ] ) => {
 				// A special case for the metadata attribute.
 				// It can include block bindings that serve as a source of content,
 				// without directly modifying content attributes.
 				if ( role === 'content' && key === 'metadata' ) {
-					return true;
+					return (
+						Object.keys( block.attributes[ key ]?.bindings ?? {} )
+							.length > 0
+					);
```
Comment (Mamaduka) [inline packages/blocks/src/api/utils.js:55]: I skipped on this idea [originally](https://github.com/WordPress/gutenberg/pull/70903#discussion_r2230198553), but it became an obvious choice when working on this fix. Otherwise, the fallback doesn't work.

File: packages/blocks/src/api/utils.js [hunk 2]
```diff
@@ -43,20 +43,27 @@ export function isUnmodifiedBlock( block, role ) {
...
-	const attributesToCheck = role
+	const attributesByRole = role
 		? Object.entries( blockAttributes ).filter( ( [ key, definition ] ) => {
 				// A special case for the metadata attribute.
 				// It can include block bindings that serve as a source of content,
 				// without directly modifying content attributes.
 				if ( role === 'content' && key === 'metadata' ) {
-					return true;
+					return (
+						Object.keys( block.attributes[ key ]?.bindings ?? {} )
```
Comment (andrewserong) [inline packages/blocks/src/api/utils.js:53]: Totally optional, but could this be checking `definition?.bindings ?? {}` since we already grab the value in this loop?

**Review by andrewserong — APPROVED** [review]
Thanks for the testing instructions, I could reproduce the issue in trunk by removing the content role from the content attribute in the paragraph block, and this PR fixes it up nicely 👍 

Left a drive-by comment but it's not in any way significant so feel free to ignore.

LGTM!

File: packages/blocks/src/api/utils.js (hunk 2 above)
Comment (Mamaduka) [reply packages/blocks/src/api/utils.js:53]: The definition refers to a block-type attribute definition. In this case, we want to check whether the block in the canvas has bindings.

Comment (andrewserong) [reply packages/blocks/src/api/utils.js:53]: Ah, of course, thanks! My drive-by comment was too quick and I hadn't double-checked the logic.

Sounds good!

**Comment by t-hamano** [comment]
This PR has been backported to the `wp/6.9` branch. #74806
