### PR TITLE
Fix: Improve the DocumentBar post type label for the Homepage and Posts Page cases

### LINKED ISSUE #66320: Improve the DocumentBar post type label for the Homepage and Posts Page cases
### Description

https://github.com/WordPress/gutenberg/pull/65170 added a 'post type label' to the DocumentBar and removed the type icon to provide a clearer information about the object being edited. So far so good. Screenshot:

Image

There are at least two edge cases though where other parts of the UI use a special label for the object being edited: The 'Homepage' and 'Posts Page' pages. 

In this cases, while the DocumentBar still says just 'Page', the `PostCardPanel` in the Settings panel adds a more specific label to these special pages. 

As such, users see two inconsistent pieces of information, which is confusing, and may think something is going wrong. 

Screenshots:

Image

Image

I'd suggest to provide a consistent information and make the Document Bar handle these special cases by providing a consistent label:
- Homepage 
- Posts Page

### Step-by-step reproduction instructions

- Go to the wp-admin Reading Settings.
- Set your homepage to display a static page.
- Set a Posts page.
- Go to the Site editor > Pages.
- Select either the page used tor the homepage or the one used tor the posts page.
- Observe the Document Bar label is 'Page'.
- Observe the Post card in the settings panel uses a more specific label: 'Homepage' or 'Posts page'.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### PR DESCRIPTION
**Pull request by hbhalodia**
Fixes https://github.com/WordPress/gutenberg/issues/66320

## What?

- This PR adds the utility custom hook to add the badge to the editor view in post panel and docuemnt bar.

## Why?

- Issue - https://github.com/WordPress/gutenberg/issues/66320

## How?

- PR adds the utility custom hook to get the details and add the badge based on the details.

## Testing Instructions

- See `Testing Instructions on` - https://github.com/WordPress/gutenberg/issues/66320

### Testing Instructions for Keyboard

- None.

## Screenshots or screencast 
Screenshot 2024-10-23 at 12 34 35 PM

### CODE REVIEW

File: packages/editor/src/components/document-bar/index.js [hunk 1]
```diff
@@ -184,11 +187,19 @@ export default function DocumentBar( props ) {
...
+							{ pageTypeBadge && ! props.title && (
 								<span className="editor-document-bar__post-type-label">
-									{ '· ' + decodeEntities( postTypeLabel ) }
+									{ '. ' + pageTypeBadge }
 								</span>
 							) }
+							{ postTypeLabel &&
+								! props.title &&
+								! pageTypeBadge && (
+									<span className="editor-document-bar__post-type-label">
```
Comment (Vrishabhsk) [inline packages/editor/src/components/document-bar/index.js:194]: Would it be more readable to move the conditional inside the `<span>` tag since it's the same for both `conditions`?

```suggestion
<span className="editor-document-bar__post-type-label">
    { '. ' + ( postTypeLabel && ! props.title && ! pageTypeBadge ) ? decodeEntities( postTypeLabel ) : pageTypeBadge }
</span>
```

Comment (hbhalodia) [reply packages/editor/src/components/document-bar/index.js:194]: Thanks @Vrishabhsk, Updated the PR with the same.

File: packages/editor/src/components/document-bar/index.js [hunk 2]
```diff
@@ -184,11 +187,15 @@ export default function DocumentBar( props ) {
 									? decodeEntities( title )
 									: __( 'No title' ) }
 							</span>
-							{ postTypeLabel && ! props.title && (
-								<span className="editor-document-bar__post-type-label">
-									{ '· ' + decodeEntities( postTypeLabel ) }
-								</span>
-							) }
+							<span className="editor-document-bar__post-type-label">
+								{ `. ${
```
Comment (afercia) [inline packages/editor/src/components/document-bar/index.js]: Please do not change this to a normal dot. It should be a 'middle dot' character `·`

File: packages/editor/src/components/document-bar/index.js [hunk 3]
```diff
@@ -184,11 +187,15 @@ export default function DocumentBar( props ) {
 									? decodeEntities( title )
 									: __( 'No title' ) }
 							</span>
-							{ postTypeLabel && ! props.title && (
-								<span className="editor-document-bar__post-type-label">
-									{ '· ' + decodeEntities( postTypeLabel ) }
-								</span>
-							) }
+							<span className="editor-document-bar__post-type-label">
```
Comment (afercia) [inline packages/editor/src/components/document-bar/index.js]: I'd suggest to avoid to render a potentially emptuy `<span>`. See in the previous implementaiton the condition wraps the entire span.

File: packages/editor/src/utils/pageTypeBadge.js [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+import { store as editorStore } from '../store';
+
+/**
+ * Custom hook to get the page type badge for the current post on edit site view.
+ */
+export default function usePageTypeBadge() {
+	const { isFrontPage, isPostsPage } = useSelect( ( select ) => {
+		const { getCurrentPostId } = select( editorStore );
+		const { canUser, getEditedEntityRecord } = select( coreStore );
+		const _postId = getCurrentPostId();
```
Comment (afercia) [inline packages/editor/src/utils/pageTypeBadge.js]: Not sure this variable name needs an underscore.

File: packages/editor/src/components/document-bar/index.js (hunk 1 above)
Comment (afercia) [reply packages/editor/src/components/document-bar/index.js:194]: I would recommend to avoid to potentially render an empty span element so I'd keep the condition wrapping the span.

**Review by afercia — CHANGES_REQUESTED** [review]
Tests well for me, thanks @hbhalodia.
I left a few minor comments to address.

**Comment by hbhalodia** [comment]
> Tests well for me, thanks @hbhalodia. I left a few minor comments to address.

Thanks @afercia, I would look on those and address the same.

File: packages/editor/src/components/document-bar/index.js (hunk 3 above)
Comment (hbhalodia) [reply packages/editor/src/components/document-bar/index.js]: Sure, I would revert that change.

File: packages/editor/src/components/document-bar/index.js (hunk 2 above)
Comment (hbhalodia) [reply packages/editor/src/components/document-bar/index.js]: This is now revert to use `·` character.

**Comment by afercia** [comment]
@hbhalodia looks good to me, thanks. Can you please solve the merge conflict, when you have a chance?

**Comment by hbhalodia** [comment]
> @hbhalodia looks good to me, thanks. Can you please solve the merge conflict, when you have a chance?

Sure, @afercia, I would fix those.

**Comment by hbhalodia** [comment]
Hi @afercia, I have resolved the conflicts and do checked from my end all looks good, Can you please have a final look as well, if anything missed while resolving conflicts 🙇.

Thank You,

**Review by afercia — APPROVED** [review]
Thanks @hbhalodia, looks good to me
