### PR TITLE
Fix blockGap styles not working in block style variations

### LINKED ISSUE #72318: Global blockGap property is not overridable in style variations
### Description

1. Define global blockGap property in theme.json:
```
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 3,	
	"settings": {
		"spacing": {
			"blockGap": true
		}
	},
	"styles": {
		"spacing": {
			"blockGap": "10px"
		}
	}
}
```

2. Create style variation for any block that override blockGap:
```
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 3,
	"title": "No Block Gap",
	"slug": "no-block-gap",
	"blockTypes": ["core/group"],
	"styles": {	
		"spacing": {
			"blockGap": "0"
		}
	}
}
```

Override doesn't work. Workaround:
```
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 3,
	"title": "No Block Gap",
	"slug": "no-block-gap",
	"blockTypes": ["core/group"],
	"styles": {	
		"css": "&.is-layout-constrained > *:not(:first-child) { margin-block-start: 0; }"		
	}
}
```

UPD. [Same issue](https://github.com/WordPress/gutenberg/issues/63273)

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

Fixes #72318.

<details>
<summary>previous description</summary>

Essentially, block gap styles get left out of block style variation stylesheets because block gap isn't included in `PROPERTIES_METADATA` that gets iterated through when generating the stylesheet. Instead, block gap exists by itself in a `PROTECTED_PROPERTIES` array.

(I'm not sure what the history behind `PROTECTED_PROPERTIES` is; gap is unique in its dependency on layout styles, that are output separately from other block supports, but `PROTECTED_PROPERTIES` doesn't seem to be doing much at present.)

This PR fixes the issue by adding an optional `$include_protected_properties` flag to `compute_style_properties` which, if set, includes those properties in with the regular properties to be computed.

It also adds the block gap setting to the block style variations config, without which block gap styles aren't output (this might be related to the reason block gap is a protected property)

For styles to be generated in the editor as well as on the front end, I also had to add gap to `__EXPERIMENTAL_STYLE_PROPERTY`. If we think it makes sense to keep the PHP `PROTECTED_PROPERTIES` around, it might be worth reflecting this construction on the JS side too.

I'm not too certain about this solution, so feedback and ideas very welcome!

</details>

I've iterated a bit and finally arrived at a solution that seems satisfactory 😅 

It ended up not being necessary to add gap to `PROPERTIES_METADATA` but I'm removing `PROTECTED_PROPERTIES` all the same because it's not needed anymore.

What this PR now does is generate layout styles for block style variations and section styles that have a blockGap defined. In order for this to work correctly, I had to fiddle a bit with the selectors, because the order they're output in (for valid reasons, namely the Paragraph block has an element selector instead of a classname) is `.block-selector.variation-selector`, but for layout style generation we need block selector to come last, so we can append the layout type classname extension to it. So I added another block selector to the end: `.block-selector.variation-selector.block-selector`, which after the layouts are processed becomes something like `.block-selector.variation-selector.block-selector-is-layout-flex`. This shouldn't cause any problems in the scenario that the classnames were originally ordered for, because Paragraph blocks don't support layout.

I also had to switch the output order of theme style variations and section styles in the editor code, because it was different from the front end and resulted in higher-level theme styles overriding section styles. The editor order now matches the front end.

## Testing Instructions

1. in your block theme folder, under styles > blocks, add a file with something like:

```
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 3,
	"title": "Gaplesss",
	"slug": "gapless",
	"blockTypes": ["core/group"],
	"styles": {
		"spacing": {
			"blockGap": "1px"
		}
	}
}
```

2. if your theme has any section styles, you can also try adding the following in one of the section style files, under styles > blocks:

```
"core/group": {
				"spacing": {
					"blockGap": "3px"
				}
			}
```

3. If your theme has theme style variations, try adding the following to an inactive variation:

```
"core/group": {
				"spacing": {
					"blockGap": "5px"
				}
			}
```
and then activate it.

Then, add some Group blocks using these section styles and variations to a post, nest a few of them, make use of all the different layout types (gap should apply to flex and grid as `gap` on the container, and to flow/constrained layouts as `margin-block-start` on the children)  and check that they render correctly in the editor. Save, and check the front end. 

(Be mindful that for the section styles, the above style snippet will apply only to a group _within_ the section, not to the section wrapper)

In the screenshot, the Paragraph margin is determined by a section style, which overrides a theme style variation:

Screenshot 2026-01-15 at 6 11 07 pm

### CODE REVIEW

File: lib/class-wp-theme-json-gutenberg.php [hunk 1]
```diff
@@ -358,7 +358,7 @@ class WP_Theme_JSON_Gutenberg {
 	 * @since 5.9.0
 	 */
 	const PROTECTED_PROPERTIES = array(
-		'spacing.blockGap' => array( 'spacing', 'blockGap' ),
+		'gap' => array( 'spacing', 'blockGap' ),
```
Comment (andrewserong) [inline lib/class-wp-theme-json-gutenberg.php]: I think `PROTECTED_PROPERTIES` is meant to use a path as a key, rather than map CSS properties? From looking at this bit of code:

https://github.com/WordPress/gutenberg/blob/4203f6ed5064c368ca9b9034ccb3aa600c526ec3/lib/class-wp-theme-json-gutenberg.php#L2473

**Review by andrewserong — COMMENTED** [review]
Thanks for looking into this! I haven't tested it yet, but I'm not quite sure it's the right path for `blockGap` as the value doesn't necessarily map to the `gap` CSS property. I.e. for the default and constrained layouts, the spacing styles value that gets set for blockGap is actually `margin-block-start`.

It's pretty hard to read, but for global styles, here's where the block gap values are generated (in `get_layout_styles`):

https://github.com/WordPress/gutenberg/blob/4203f6ed5064c368ca9b9034ccb3aa600c526ec3/lib/class-wp-theme-json-gutenberg.php#L1757

In that code, the layout definitions are iterated over, and spacing rules are generated for each layout type.

Is there a way to implement this so that each layout type is factored in? This area of layout/blockGap gets a bit 🍝 -ey quite quickly, so I'm not opposed to pragmatic fixes if there's a way to handle it gracefully. And the instincts in this PR (let's just output `gap` where we need to) is possibly simpler than alternatives 🤔

What do you think?

File: lib/class-wp-theme-json-gutenberg.php (hunk 1 above)
Comment (tellthemachines) [reply lib/class-wp-theme-json-gutenberg.php]: Hmm yeah, that's the only place we seem to be using `PROTECTED_PROPERTIES` though, and afaict before this PR it would never run, because we're looping through `PROPERTIES_METADATA` at that point, and there are no common properties between the two. I'm probably missing something here, but I don't get what `PROTECTED_PROPERTIES` is actually meant to be doing 😅

Comment (andrewserong) [reply lib/class-wp-theme-json-gutenberg.php]: Ah, here we go, I had to dust off my memory with this one, but it turns out I added it way back in: https://github.com/wordpress/gutenberg/pull/35209 — it was to prevent causing regressions in Classic themes. (blockGap set to `null` will prevent base blockGap values from being output including the `--wp--style-block-gap` CSS variable).

As it turns out, this made more sense when `--wp--style--block-gap` lived in `PROPERTIES_METADATA`. It was mapped to `array( 'spacing', 'blockGap] )` and should have been skipped in `compute_style_properties` if set to `null` in `$settings`.

As things have evolved in `theme.json` we no longer output the CSS variable in that way, so I _think_ we can probably ditch `PROTECTED_PROPERTIES` (and the logic that filters it) altogether now, as the only place we're outputting `--wp-style--block-gap` is here now:

https://github.com/WordPress/gutenberg/blob/4203f6ed5064c368ca9b9034ccb3aa600c526ec3/lib/class-wp-theme-json-gutenberg.php#L3246

And that output is guarded by the simpler `if ( isset( $this->theme_json['settings']['spacing']['blockGap'] ) ) {` check.

TL;DR: `--wp--style--block-gap` was added in WP 5.9 as a property and was removed in WP 6.1. This logic appears to be a bit of a relic from the 5.9-6.0 period.

Comment (tellthemachines) [reply lib/class-wp-theme-json-gutenberg.php]: Ah, thanks for diving in there Andy! So to confirm, if we remove `PROTECTED_PROPERTIES`, it would be safe to add gap to `PROPERTIES_METADATA`?

Comment (andrewserong) [reply lib/class-wp-theme-json-gutenberg.php]: I _think_ so. The main gap (pardon the pun) is that depending on the layout type, `gap` might not be appropriate (the default/constrained layout type issue). And if folks are using `blockGap` in `theme.json` there could be duplicate output of rules (i.e. those generated by `get_layout_styles`).

So, my hunch is that if we add `gap` to `PROPERTIES_METADATA`, there might be a bit of tidying / plumbing to do in `get_layout_styles` to make sure everything's working correctly, no duplicate rules, etc.

Comment (tellthemachines) [reply lib/class-wp-theme-json-gutenberg.php]: Hmm, that part should just work - it seems to be working fine in this PR at least! - because we're already mapping the gap value to margin in flow/constrained layouts.

Ok, I'll give it a go, it should simplify things a bit. Thanks for the discussion!

Comment (tellthemachines) [reply lib/class-wp-theme-json-gutenberg.php]: OK I've now updated to remove `PROTECTED_PROPERTIES` altogether and added gap to `PROPERTIES_METADATA`. Everything seems to be working well and I'm not seeing any additional or unexpected output of gap-related styles.

**Comment by tellthemachines** [comment]
In testing, the one thing that still _isn't_ working is setting blockGap on a block anywhere inside a theme style variation. So for instance, in TT5, going into the "noon" variation json file and adding 
```
"core/group": {
				"spacing": {
					"blockGap": "4px"
				}
}
```
under styles > blocks doesn't do anything. But I haven't been able to make changes to other properties in style variations either, so it might be a different issue. 

Does anyone know offhand whereabouts theme style variations are processed?

I also need to fix the failing tests, and once that's done I'll mark this ready for review.

File: lib/class-wp-theme-json-gutenberg.php (hunk 1 above)
Comment (aaronrobertshaw) [reply lib/class-wp-theme-json-gutenberg.php]: Have we considered that we support nested application of block style variations, where the styles for block gap would need to understand the context they are in regarding parent layout?

I'm still trying to dust off my memory of all this myself but figure its worth asking the question early.

**Comment by aaronrobertshaw** [comment]
> Does anyone know offhand whereabouts theme style variations are processed?

If I understand the question, I think the start of the thread you might be looking for could be the Theme JSON resolver class and [`get_theme_data`](https://github.com/WordPress/gutenberg/blob/trunk/lib/class-wp-theme-json-resolver-gutenberg.php#L234).

File: lib/class-wp-theme-json-gutenberg.php (hunk 1 above)
Comment (tellthemachines) [reply lib/class-wp-theme-json-gutenberg.php]: Yes, I _think_ I've tested with all nesting combinations. Further testing always welcome though!

**Comment by tellthemachines** [comment]
Thanks everyone for the feedback so far! I'm marking this ready for review in hopes we can validate the approach, and then I'll deal with the core sync work.

**Review by aaronrobertshaw — COMMENTED** [review]
Nice work on this @tellthemachines 👍 

The approach seems solid to me and so far is working as advertised on all the current core blocks I've tested. I still need to do some further testing around nesting and some edge cases though.

In the meantime, I was wondering if there's a latent bug here around how we generate selectors. As you noted, this assumes simple class based selectors. I verified that no core blocks with layout support use HTML elements in their selectors, but I do wonder what the potential is for third party blocks to do so. Maybe something using an `aside` or `section` element?

More simply put, do we have the potential to create malformed CSS selectors as it currently stands? 

Maybe I've misread the code as I'm pretty rusty here but:

1. **Pure element selectors** (e.g., `p`, `table`) - would create `p.is-style-customp-is-layout-flex` (malformed class)
2. **Combinators** (e.g., `.wp-block-list > li`) - would create invalid nested selectors

Could it be possible that List Item blocks actually get blockGap support in the future given they can contain nested lists?

This is by no means blocking but would it be worth trying to fix or mitigate this so it doesn't become a more serious bug in the future?

**Comment by tellthemachines** [comment]
> More simply put, do we have the potential to create malformed CSS selectors as it currently stands?

Yeah that's an interesting question. There is the potential for malformed selectors, but that potential already exists with the layout support due to how we concatenate the layout classnames. In this case, rather than overly complicating the code to try and protect from arbitrary selectors, it might be better to clarify in the docs that block support for layout and block spacing requires a classname selector. 

I kinda wish that was a requirement for all blocks tbh, the Paragraph thing has given us more than enough grief already 😅

**Comment by aaronrobertshaw** [comment]
> There is the potential for malformed selectors, but that potential already exists with the layout support due to how we concatenate the layout classnames

My memory is probably rusty or out of date but I think this is why layout and blockGap styles were initially left unsupported for block style variations.

> In this case, rather than overly complicating the code to try and protect from arbitrary selectors, it might be better to clarify in the docs that block support for layout and block spacing requires a classname selector.

If everyone thinks that is sufficient, you wont get any arguments for me. Would it potentially still be worth a sanity "doing it wrong" check in the code?

None of this is blocking for this fix. It can be a follow-up

**Comment by tellthemachines** [comment]
> Would it potentially still be worth a sanity "doing it wrong" check in the code?

I guess we could check whether the block selector starts with a `.`?

**Comment by aaronrobertshaw** [comment]
> I guess we could check whether the block selector starts with a .?

Maybe also contains any combinators e.g. `>` etc

**Comment by tellthemachines** [comment]
> Maybe also contains any combinators e.g. `>` etc

This is the kind of complexity I'd rather avoid 😅 

We can leave it as it is for now, because there haven't been any issues so far with how the layout classnames are composed, and this just uses the same mechanism. I might add a note to the layout support docs to the effect that it won't work if the block selector isn't a classname, and we can always revisit doing checks if any complications arise.

**Comment by tellthemachines** [comment]
OK I've added the backport changelog and a note in the docs about layout compatible selectors. This should be ready for a final review now!

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for all the work on this 👍 

This tests as advertised for me.

✅ Top level block gap styles apply for block style variations
✅ Nested block gap styles apply for block style variations
✅ Block gap styles function work in variation definition within theme.json
✅ Block gap styles function correctly in standalone section style theme.json partial
✅ Both margin and gap based styles work for the different layouts

| Editor | Frontend |
|---|---|
| Screenshot 2026-01-21 at 7 27 46 pm | Screenshot 2026-01-21 at 7 27 54 pm |
