### PR TITLE
Fix character newlines in pre

### LINKED ISSUE #12109: Converting a <pre> to blocks drops new lines
If you open an old post in Gutenberg it will put the contents in a classic block. If this classic block contains a `<pre>` section and you then convert that to blocks it removes the new lines in the editor.

edit_post_ _wordpress_latest_ _wordpress

HTML is:

```html
<pre>line1
line2
line3
</pre>
```

From the block options pick 'convert to blocks' and get:

edit_post_ _wordpress_latest_ _wordpress

Note that this is only in the Gutenberg editor, where the code is:

edit_post_ _wordpress_latest_ _wordpress

When viewed in the post the `<pre>` is correct:

test_pre_ _wordpress_latest

### Expected behavior

Either the `<pre>` conversion should add the `<br/>` tags that occur when created in Gutenberg, or the preformatted block should insert breaks in the display when a new line is encountered.

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #12109. Alternative of #13606. See https://github.com/WordPress/gutenberg/pull/13606#issuecomment-460950301.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/block-library/src/preformatted/index.js [hunk 1]
```diff
@@ -68,7 +68,7 @@ export const settings = {
 		return (
 			<RichText
 				tagName="pre"
-				value={ content }
+				value={ content.replace( /\n/g, '<br>' ) }
```
Comment (youknowriad) [inline packages/block-library/src/preformatted/index.js]: Does this mean we should do the opposite once `onChange` is called?
Are there other tags that needs to behave this way? Should this be a config of `RichText`?

Comment (iseulde) [reply packages/block-library/src/preformatted/index.js]: No, we don't need modify `onChange`. There are two possibilities: `<br>` and `\n`. In `RichText` `\n` is collapsed as it is normally in HTML, so it cannot handle it. I went for using `<br>` by default, but we could go for `\n` too, in which case we would need to `onChange`. RichText always outputs `<br>` for line breaks.

Yes, it could also be part of the `RichText` config. Something like `collapseLineBreaks: false`. Not sure if that's needed as it will be more of an exception and it can be resolved outside of `RichText`, keeping `RichText` free of more parameters.

**Review by jorgefilipecosta — APPROVED** [review]
Works great in my tests and the approach is simple, I think we can use it 👍 I don't expect other blocks to need this kind of replacement so I think it is fine to leave this logic in the block.

Maybe we can add simple memoization to the replacement to avoid executing it on each block rerender even if nothing changed? A function wrapped around memize configured to one in the constructor would probably work great, but the replacement should also be a fast operation so in this case, memoization is not a must.

**Comment by iseulde** [comment]
@aduth What do you think about the memoization? I'm not sure if a simple replace needs it, but maybe it's slightly faster and worth it.

**Comment by aduth** [comment]
> @aduth What do you think about the memoization? I'm not sure if a simple replace needs it, but maybe it's slightly faster and worth it.

Are you asking if it should be introduced? I see none currently.

I'd probably avoid it, or limit it to a `maxSize` of `1` to just avoid repeatedly calling it when the value doesn't change.

But I also think ideally the value sits at rest in the format we want it to be in, so that we don't need to apply formatting when rendering the value. I see @youknowriad mentioned `onChange` earlier, but it's not clear by that conversation that we shouldn't just be replacing newlines from content there and not at all as part of the `value` assignment.

Similar to what we do for the PostTitle component:

https://github.com/WordPress/gutenberg/blob/858719bf3e5c7cd37c14824f5f3d4b8db49cc8f2/packages/editor/src/components/post-title/index.js#L58-L61

**Comment by iseulde** [comment]
We don't want to change anything in the RichText output. Only to the input. Ideally, the replacing happens on attribute parsing, but there's no way for the block to interfere with it?

And yes, @jorgefilipecosta was thinking it would be good to introduce it. I'm not sure. I'd avoid it as well.

File: packages/block-library/src/preformatted/index.js (hunk 1 above)
Comment (aduth) [reply packages/block-library/src/preformatted/index.js]: > Yes, it could also be part of the `RichText` config. Something like `collapseLineBreaks: false`.

Does it need to be configured? Or is it enough to infer by `tagName === 'pre'` ?

Comment (aduth) [reply packages/block-library/src/preformatted/index.js]: Why does RichText collapse HTML anyways? From the comment in `filterString`, it reads as though it's not strictly necessary, but more to the point of normalizing on an assumption it'd be treated as equivalent by the browser anyways. If so, wouldn't this pull request and corresponding issue contradict that assumption?

https://github.com/WordPress/gutenberg/blob/910b655018037167c2dcee38095905003f632b51/packages/rich-text/src/create.js#L235-L239

Comment (iseulde) [reply packages/block-library/src/preformatted/index.js]: * Without removing line breaks, the line breaks will be visible in `RichText`, just like `<br>`. So if you add a line break in the HTML editor, then switch back, the line break will remain visible. 
* If we were to keep textual line breaks, they'd interfere with the rich text value line breaks:
  * In HTML, `\n` means nothing, it's just for the formatting of HTML, `<br>` means line break.
  * In a rich text value, `\n` means line break.

So if we just leave `\n`, they'll all be serialised as line breaks.

**Comment by iseulde** [comment]
Merging as it fixes the issue and adds a test. We can iterate on implementation if needed.

**Comment by gziolo** [comment]
The test added in this PR is very unstable on Travis. See #14014.

**Comment by EricForgy** [comment]
Out of curiosity, I'm a little lost, but did this change break multiline LaTeX equations? Ref #14564

**Comment by fransflippo** [comment]
Would this be included in WordPress 5.4.1? I'm experiencing this exact issue with preformatted blocks in WordPress 5.4.1, but I don't know how to tell which Gutenberg version it includes.

**Comment by fransflippo** [comment]
Scratch that, it's not the exact same issue. 

My issue is that adding a Gutenberg preformatted block with newlines cause those newlines to be converted into spaces when rendered to HTML.

Editor:
```<pre class="wp-block-preformatted">Line 1
Line 2

Line 4 (previous line was empty)</pre>```

HTML:
```<pre class="wp-block-preformatted">Line 1 Line 2  Line 4 (previous line was empty)</pre>```

Before I log a new issue, is anybody aware of this and can you reproduce it? Thanks.

**Comment by fransflippo** [comment]
If anybody runs into the same problem: newlines in the Tabbed Content block from the Ultimate Blocks plugin will be replaced by whitespace. So don't put preformatted or code blocks inside Tabbed Content blocks. (I'm using Tabby now for tabs which just doesn't have Gutenberg support atm, but the shortcodes work fine and it doesn't screw up my code blocks.)
