### PR TITLE
fix: a11y/HTML validation issues

### LINKED ISSUE #2375: HTML validation errors
On current master demo content (0.8  just released):

1
Error: Attribute label not allowed on element button at this point.
`<button type="button" aria-expanded="true" label="Open section: Status &amp; Visibility" ...`

this is because the panel body Button receives a `label` prop that should be `aria-label`

2
Error: Element figcaption not allowed as child of element div in this context. 
```
<div class="blocks-editable"><figcaption contenteditable="true" class="blocks-editable__tinymce mce-content-body" aria-label="Write caption…" id="mce_7" data-is-placeholder-visible="false">
```

3
Error: Element div not allowed as child of element span in this context.
`<div class="editor-visual-editor__block-edit"><span class="wp-block-button"><div class="blocks-editable">`

4
Error: The scrolling attribute on the iframe element is obsolete. Use CSS instead.

### PR DESCRIPTION
**Pull request by tofumatt**
Fixes #2375

## Description
Fix HTML validation issues mentioned in #2375.

## How has this been tested?
Snapshots updated after expected failures.

Tested locally and button (the main HTML change) appears fine in the editor.

### CODE REVIEW

File: packages/components/src/panel/body.js [hunk 1]
```diff
@@ -50,6 +50,7 @@ class PanelBody extends Component {
 							className="components-panel__body-toggle"
 							onClick={ this.toggle }
 							aria-expanded={ isOpened }
+							aria-label={ title }
```
Comment (afercia) [inline packages/components/src/panel/body.js]: #2375 is from August 2017 🙂and many things have changed since then. Specifically, this Button used to have a `label` prop that was rendered as a `label=""` HTML attribute. It was removed in https://github.com/WordPress/gutenberg/pull/2591/files#diff-db33f7945064a86aa02f468ca5cb4184L54

I'd say this `aria-label` shouldn't be added as it just duplicates the button text.

Comment (tofumatt) [reply packages/components/src/panel/body.js]: 😄

Ah, I wasn't sure if it was useful to add here so I erred on the side of caution. Thanks, I'll remove it! 👍

File: packages/components/src/sandbox/index.js [hunk 2]
```diff
@@ -193,7 +193,7 @@ class Sandbox extends Component {
 			<FocusableIframe
 				iframeRef={ this.iframe }
 				title={ title }
-				scrolling="no"
+				scrolling="no" /* TODO: Remove */
```
Comment (aduth) [inline packages/components/src/sandbox/index.js]: Context?

Comment (tofumatt) [reply packages/components/src/sandbox/index.js]: I left it in because I was worried I'd forget to remove it and if I pushed this it would alert me to do it, haha. So I have to do that 😆

**Comment by tofumatt** [comment]
Okay, fixed that `scrolling` attribute TODO I forgot about. Ready for review now 😄

**Review by youknowriad — APPROVED** [review]
LGTM 👍

File: packages/components/src/sandbox/index.js [hunk 3]
```diff
@@ -193,7 +193,7 @@ class Sandbox extends Component {
 			<FocusableIframe
 				iframeRef={ this.iframe }
 				title={ title }
-				scrolling="no"
```
Comment (aduth) [inline packages/components/src/sandbox/index.js]: Regression: #9920
