### PR TITLE
Featured Image: Allow authors to select images uploaded by other users

### LINKED ISSUE #18510: Bug: Author role can't add a featured image uploaded by someone else
In the block editor screen, on the right-side where we have the featured image panel, if a user is an author and can 'upload_files', the featured image that is not their own image will not load up when selected. This bug is only present when user selects an image uploaded by someone else.

**Reproduce:**

1. As an author user, on the post editing screen, click the Set Featured Image button.
2. Select an image that is **NOT** uploaded by this user. So an image uploaded by a different user.
3. Now, you will see a never-ending loading icon:

Screenshot 2019-11-13 at 14 38 39

Works fine with images uploaded by the user themselves.

Tested on WP 5.3 and several environments.

**Probable cause of this bug:**

The Block Editor uses RESTful API to facilitate its functionality and the endpoint that is responsible for media attachments, for some unthoughtful reasons, checks if the current author is allowed to **update** the image that is about to be used as Features Image.

Maybe this part is the gremlin:

```
if ( $post && ! $this->check_update_permission( $post ) ) {
    return new WP_Error( 'rest_cannot_edit', __( 'Sorry, you are not allowed to edit this post.' ), array( 'status' => rest_authorization_required_code() ) );
}
```

Not sure. 

An obvious fix would be to add `edit_others_posts` to author roles, but that defeats the main idea of the author role.

This is clearly a severe bug. Please let me know if you have questions to reproduce this bug.

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
PR fixes the issue when users with the Author role couldn't select images uploaded by other users.

The media entity is only requested for display. Therefore, I think it makes sense to change the request `context` to the `view` argument.

Fixes #18510.

## How has this been tested?
1. Upload an image using an Administrator user account.
2. Switch to a user with an Author role.
3. Create a post.
4. Select the uploaded image using the "Post Featured Image" block or "Feature image" panel in the sidebar.
5. See that feature image is displayed.
6. DevTools has no 403 requests in the Networks panel.

## Types of changes
Bugfix 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by ntsekouras — COMMENTED** [review]
Thanks for your work @Mamaduka !

**Review by ntsekouras — APPROVED** [review]

**Comment by christincooper** [comment]
Two years of [campaigning](https://github.com/WordPress/gutenberg/issues/18510) has finally concluded. If WordPress does not give me credit for the time I've spent to push this up...

@Mamaduka Endless high-fives for resolving this issue.

File: packages/block-library/src/post-featured-image/edit.js [hunk 1]
```diff
@@ -44,7 +44,13 @@ function PostFeaturedImageDisplay( {
 	);
 	const media = useSelect(
 		( select ) =>
-			featuredImage && select( coreStore ).getMedia( featuredImage ),
+			featuredImage &&
+			select( coreStore ).getEntityRecord(
```
Comment (gziolo) [inline packages/block-library/src/post-featured-image/edit.js:48]: @youknowriad, is it possible to pass additional params to `getMedia` and other methods automatically generated from entities? One thing that surprises me is that I see `getEntityRecord` used so often despite all these shorthand methods available:

Screen Shot 2021-08-06 at 08 16 11

Comment (Mamaduka) [reply packages/block-library/src/post-featured-image/edit.js:48]: @gziolo, It wasn't possible when I created this PR. But it is fixed now - #33689.

I can create PR to switch back to `getMedia`.

Comment (gziolo) [reply packages/block-library/src/post-featured-image/edit.js:48]: @Mamaduka, it's optional. I was rather sharing a general thought about the surprising popularity of more verbose `getEntityRecord`.

Comment (Mamaduka) [reply packages/block-library/src/post-featured-image/edit.js:48]: @gziolo, I also kinda like `getMedia( mediaId, { context: 'view' } )` more 😄  So follow-up PR won't be a problem.
