### PR TITLE
Block templates: Recognize and convert old or derivative block types to their canonical form

### LINKED ISSUE #26137: Derivative embed blocks in post type templates should be recognized and converted on the fly when creating a new post
**Describe the bug**

If a post type template contains an old embed block for a specific platform (e.g. WordPress TV), the editor will crash with a WSOD when trying to create a new post, essentially as described in #21718.

**To reproduce**
1. Register a new post type and give it a template like:
    ```
    'template' => [
        [ 'core-embed/wordpress-tv' ],
    ]
    ```
1. Navigate to the Add New screen for that post type.
1. You should get a White Screen Of Death. If you view the browser console, you'll see an error:
    ```
    Uncaught (in promise) Error: Block type ‘core-embed/wordpress-tv’ is not registered.
    ```

**Expected behavior**

I would expect the editor to be able to recognize and convert the old WordPress TV embed block into the new Embed block with the WordPress TV block variation, as happens [here](https://github.com/WordPress/gutenberg/blob/02590029e7464efafee46141b3549763dbf22cd4/packages/blocks/src/api/parser.js#L438-L458).

**Editor version:**
- WordPress version: 5.6-alpha-49153
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? `default`

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: Firefox
 - Version: 81.0.1

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/26137

If a post type template contains a legacy block, like an `embed` for a specific platform (e.g. `core-embed/wordpress-tv`), the editor will crash with a WSOD when trying to create a new post.

Steps to reproduce exist in issue.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/blocks/src/api/parser.js [hunk 1]
```diff
@@ -456,6 +441,34 @@ export function createBlockWithFallback( blockNode ) {
...
+	attributes = attributes || {};
+
+	// Trim content to avoid creation of intermediary freeform segments.
+	innerHTML = innerHTML.trim();
+
+	// Use type from block content if available. Otherwise, default to the
+	// freeform content fallback.
+	let name = originalName || freeformContentFallbackBlock;
+
+	name = convertDerivativeBlocks( name, attributes ).name;
```
Comment (mcsf) [inline packages/blocks/src/api/parser.js:471]: Looking at this line, one would expect no side effects to happen. However, `attributes` is being mutated behind the scenes. We should fix this by either:

* Eliminating side effects and making `convertDerivativeBlocks` return `{ name, attributes }`
* Making it very clear that there are side effects and eliminating return values: `(void) convertDerivativeBlocks( blockNode )`

The former would be the least surprising approach.

File: lib/blocks.php [hunk 2]
```diff
@@ -45,6 +45,7 @@ function gutenberg_reregister_core_block_types() {
 				'text-columns',
 				'verse',
 				'video',
+				'embed',
```
Comment (mcsf) [inline lib/blocks.php:48]: Is this needed?

**Review by mcsf — COMMENTED** [review]
Thanks for looking at this. The general approach seems right.

**Comment by mcsf** [comment]
I wonder if we could tweak one of the E2E tests that we have, e.g. `cpt-locking.php`, to include deprecated block types.

Now, this only fixes the issue of templates not having their blocks converted from deprecated types (e.g. `core/text`, `core/embed-wordpress`). It does not fix the issue of the white screen of death (WSOD) triggered whenever a block in a template is not known. This is something to track in an issue, if there isn't one already.

File: packages/blocks/src/api/parser.js [hunk 3]
```diff
@@ -395,29 +395,14 @@ export function getMigratedBlock( block, parsedAttributes ) {
...
-	attributes = attributes || {};
-
-	// Trim content to avoid creation of intermediary freeform segments.
-	innerHTML = innerHTML.trim();
-
-	// Use type from block content if available. Otherwise, default to the
-	// freeform content fallback.
-	let name = originalName || freeformContentFallbackBlock;
-
+export function convertDerivativeBlocks( name, attributes ) {
```
Comment (mcsf) [inline packages/blocks/src/api/parser.js:405]: It's not a very important detail, but I wonder if `convertOldBlocks` — or something along those lines — might be a better name for this. I consider that only a few cases, like Embeds, are about converting derivatives. The other ones, like Text, are about converting old forms of these blocks.

File: lib/blocks.php (hunk 2 above)
Comment (mcsf) [reply lib/blocks.php:48]: Ah, I suppose this is addressing this other piece of feedback? https://github.com/WordPress/gutenberg/pull/24090#issuecomment-708950360

Comment (ntsekouras) [reply lib/blocks.php:48]: Actually is not related and is about the above feedback. If this PR will not land, I'll create a separate one to address that.

File: packages/blocks/src/api/parser.js (hunk 1 above)
Comment (ntsekouras) [reply packages/blocks/src/api/parser.js:471]: Yes I thought about making this one pure, but didn't believe it was so much needed as it actually conditionally adds some attributes that wouldn't exist in the first place. In other cases both name and attributes are returned as are.

I can make it pure of course :)

File: packages/blocks/src/api/parser.js (hunk 3 above)
Comment (ntsekouras) [reply packages/blocks/src/api/parser.js:405]: Yeah, the name didn't seem right to me, but wanted to get first feedback about the approach. I'll change it.

**Comment by ntsekouras** [comment]
Thanks for reviewing @mcsf - very valuable feedback as always 💯 

>I wonder if we could tweak one of the E2E tests that we have, e.g. cpt-locking.php, to include deprecated block types.

>The general approach seems right.

Since I wanted to get feedback about the approach I'll improve the implementation and add tests for sure and address the other feedback as well.

>Now, this only fixes the issue of templates not having their blocks converted from deprecated types (e.g. core/text, core/embed-wordpress). It does not fix the issue of the white screen of death (WSOD) triggered whenever a block in a template is not known. This is something to track in an issue, if there isn't one already.

There was a relevant issue about handling the error better here: https://github.com/WordPress/gutenberg/issues/21718, which I closed as there was a better error msg and handled earlier. This still results in WSOD though.

I think it's a separate issue and I'm not really sure what the best approach of this would be to be honest.

**Comment by mcsf** [comment]
> There was a relevant issue about handling the error better here: #21718, which I closed as there was a better error msg and handled earlier. This still results in WSOD though.
> 
> I think it's a separate issue and I'm not really sure what the best approach of this would be to be honest.

Either reopen that issue or make a more specific one — both are fine.

> I'm not really sure what the best approach [is]

The editor is already equipped to handle unknown blocks if they are loaded from `post_content`. We just need to make sure this is also somehow applied to CPT templates. See `getUnregisteredTypeHandlerName`, `setUnregisteredTypeHandlerName` and `core/missing`.

**Comment by ntsekouras** [comment]
>Either reopen that issue or make a more specific one — both are fine.

I'll open a new one. Thanks for the context too!

**Comment by mcsf** [comment]
The other thing is looking at how we're using `ErrorBoundary` and figuring out why we got a full WSOD instead of a _The editor has encountered an unexpected error._ message.

File: packages/blocks/src/api/parser.js (hunk 3 above)
Comment (ntsekouras) [reply packages/blocks/src/api/parser.js:405]: Does `convertLegacyBlocks` sound alright?

Comment (mcsf) [reply packages/blocks/src/api/parser.js]: Yep!

File: packages/blocks/src/api/parser.js [hunk 4]
```diff
@@ -395,14 +395,15 @@ export function getMigratedBlock( block, parsedAttributes ) {
...
 
 /**
- * Convert derivative blocks to their canonical form. This function is used
+ * Convert legacy blocks to their canonical form. This function is used
  * both in the parser level for previous content and to convert such blocks
  * used in Custom Post Types templates.
  *
- * @param {string} name
- * @param {Object} attributes
+ * @param {string} name The block's name
```
Comment (mcsf) [inline packages/blocks/src/api/parser.js:402]: Needs `returns` annotation too.

File: packages/e2e-tests/specs/editor/plugins/custom-post-types.test.js [hunk 5]
```diff
@@ -64,4 +64,10 @@ describe( 'Test Custom Post Types', () => {
 		);
 		expect( selectedValue ).toEqual( valueToSelect );
 	} );
+	it( 'should create a cpt with a legacy block in its template without WSOD', async () => {
+		await createNewPost( { postType: 'leg_block_in_tpl' } );
+		await page.click( '.block-editor-writing-flow' );
+		await page.keyboard.type( 'Hello there' );
+		await publishPost();
```
Comment (gziolo) [inline packages/e2e-tests/specs/editor/plugins/custom-post-types.test.js:71]: It would be great to verify whether the converted block type is part of the content, too.

**Review by gziolo — COMMENTED** [review]
Nice one, I only skimmed but it's definitely a good direction 👍

**Review by mcsf — APPROVED** [review]
