### PR TITLE
[Block Editor]: Fix displaying only the `none` alignment option

### LINKED ISSUE #35341: Align "None" is available for blocks when they have no other alignment options
### Description

It might be an edge case, so feel free to ignore this 😄 .

Align option "None" is available for a group block while other options are missing. I think if the only alignment option is "None," we shouldn't display alignment controls.

 I discovered it while trying to debug #34010.

cc @ntsekouras

### Step-by-step reproduction instructions

1. Install and activate the "Blockbase" theme.
2. Go to Site Editor > Template Parts > Footer.
3. Select wrapper Group block.
4. See that only align "None" option is available.

### Screenshots, screen recording, code snippet

CleanShot 2021-10-05 at 12 54 41

### Environment info

- WordPress 5.8.1, Gutenberg 11.6

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #35814: Button block: two "Change alignment" icons in toolbar
### Description

Two "Change alignment" icons are displayed in the Button block toolbar.

They offer different options:

- None, Wide width, and Full width
- None

### Step-by-step reproduction instructions

1. Add a Buttons block.
2. Select the default button to reveal the Button toolbar.
3. Observe two "Change alignment" icons are displayed.

### Screenshots, screen recording, code snippet

buttons-duplicate-alignment-toggles

### Environment info

- WordPress 5.8.1, Gutenberg 11.7.0, tested with Empty and TT1 Blocks themes
- Chrome 94.0.4606.81
- Desktop with Windows 10

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ntsekouras**
Fixes: https://github.com/WordPress/gutenberg/issues/35341
Fixes: https://github.com/WordPress/gutenberg/issues/35814

Recently a `none` alignment option was added along with some contextual info(when available) for the widths. There are use cases though in site editor where we would end up with the `AlignmentControl` containing only the `none` option.

Such use cases came from [this PR](https://github.com/WordPress/gutenberg/pull/30079) that removed the alignments from the top level of the site editor because at that point there's no defined layout, as they won't do anything. 

In my PR I also bring back the check in `align` hook not to render the toolbar item if there are no alignments available, which was added in above Riad's PR and then [removed here](https://github.com/WordPress/gutenberg/pull/34593)  ( I also had approved the PR and didn't get the reason for that being there).

## Testing instructions
1. In site editor the top level blocks and other blocks where no alignments are available shouldn't render the control with only the `none` option.
2. In post editor everything should work properly as before, both in block themes or not
3. If there is any available alignment, the `none` option should be there as well.

### CODE REVIEW

File: packages/block-editor/src/hooks/align.js [hunk 1]
```diff
@@ -117,15 +117,19 @@ export function addAttribute( settings ) {
...
+		// Slot.
 		const blockAllowedAlignments = getValidAlignments(
 			getBlockSupport( blockName, 'align' ),
 			hasBlockSupport( blockName, 'alignWide', true )
 		);
 
+		const validAlignments = useAvailableAlignments(
+			blockAllowedAlignments
+		).map( ( { name } ) => name );
+
```
Comment (Mamaduka) [inline packages/block-editor/src/hooks/align.js:132]: The `BlockAlignmentControl` also does similar validation. Is there are a reason we want to do it twice?

https://github.com/WordPress/gutenberg/blob/a0c59f2ae2caeac94adcc1dbbe965d9851dcf907/packages/block-editor/src/components/block-alignment-control/ui.js#L71-L76

Comment (Mamaduka) [reply packages/block-editor/src/hooks/align.js:132]: Ignore this, re-read PR, and now it's clear. It makes sense not to render whole BlockControls.

**Comment by jasmussen** [comment]
Nice work. Before I see alignments with just "none":
before

After this PR, they are gone:

aligns

Cool beans, this seems to just need a code review.

On a separate note, and not something to fix here, I noticed text aligns have this "hint" coloration:

Screenshot 2021-10-21 at 10 02 34

It shouldn't, that's toggle/inversion style is only for the inline formatting menu. For these alignments, the icon itself changes, which is sufficient. These alignments do it right:

Screenshot 2021-10-21 at 10 02 50

Not the biggest issue in the world, just wanted to record it as I saw it. 

Thanks for the PR!

**Comment by Mamaduka** [comment]
It works as expected.

I can also confirm that this fixed the #35814 as well.

| Before | After |
| --- | --- |
| CleanShot 2021-10-21 at 12 16 25 | CleanShot 2021-10-21 at 12 14 25 |

**Review by Mamaduka — APPROVED** [review]

**Review by youknowriad — APPROVED** [review]
LGTM 👍

**Comment by jasmussen** [comment]
🚀

**Comment by ntsekouras** [comment]
@vcanales this should be cherry picked for the stable 11.8. Thanks!
