### PR TITLE
Editor: Fix 'slug' editing in 'template-locked' mode

### LINKED ISSUE #69509: Block editor: Can not edit slug with "Show template" enabled
### Description

When editing a page or post in the block editor, and "Show template" is enabled, 
I can not edit the slug correctly due to a bug.

A soon as I enter a character into the slug input field in the popover, the change is saved and the page "refreshes":
The page content becomes blank for a moment until the blocks shows again, and the popover is closed.
So, I can only enter one character at the time.

This happens with Gutenberg trunk enabled. 
In 6.8 beta, without Gutenberg active, the canvas blinks and refreshes when I enter each character into the slug field. But the popover does not close, so I can continue entering my updated slug into the field.

### Step-by-step reproduction instructions

Activate a block theme.
Create or edit a page or post in the block editor.

Enable "show template".
Open the document panel.
Open the slug popover by clicking on the link next to the text "Slug"
Try entering a long slug.

### Screenshots, screen recording, code snippet

With Gutenberg active:

https://github.com/user-attachments/assets/e34faaa3-761d-4db2-9f0b-2d3e3970492c

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Fixes #69509.

PR fixes a regression in which editing a page slug causes the editor canvas to fully re-render, disrupting field editing.

## Why?
The editor provider only starts rendering its contents based on two conditions: `isReady` and `mode`; both need to be `truthy` for the contents to render.

Previously, I made `isReady` dependent on the `hasTemplate` condition to avoid rendering mode flash and wait until the editor resolved the template. This introduced the problem - changing the slug also recalculates the template ID for the current page, toggling `isReady` from true to false and back.

## How?
Rearrange conditions so that `isReady` and `mode` are not recalculated when the `hasTemplate` value changes.

P.S. I think the content "flash" became less noticeable after https://github.com/WordPress/gutenberg/pull/69454.

## Testing Instructions

1. Using a block theme.
2. Open a page.
3. Confirm that canvas loading hasn't regressed and that there's no post content flash.
4. Confirm you can edit the page slug and the editor doesn't remount.
5. Confirm no regression when loading content in `post-only` mode. Posts use this mode by default.

_Note:_ I tested with CPU throttling, and content loading differences are more noticeable.

### Testing Instructions for Keyboard
Same.

## Screenshots or screencast 

_The loading screencasts are taken with CPU throttling - 4x slowdown._

**Before**

https://github.com/user-attachments/assets/5ab8303d-e091-4be3-a64a-88ca38f2b79b

**After**

https://github.com/user-attachments/assets/8f3b3ee1-fc84-4500-a004-f0a73102d7d7

### CODE REVIEW

File: packages/editor/src/components/provider/index.js [hunk 1]
```diff
@@ -190,16 +191,20 @@ export const ExperimentalEditorProvider = withRegistryProvider(
 				 * - Wait for template to be resolved if the default mode is 'template-locked'.
 				 * - Wait for default mode to be resolved otherwise.
 				 */
-				const hasResolvedMode =
+				const hasResolvedDefaultMode =
 					_defaultMode === 'template-locked'
 						? hasTemplate
 						: _defaultMode !== undefined;
+				// Wait until the default more is retrieved and start rendering canvas.
```
Comment (t-hamano) [inline packages/editor/src/components/provider/index.js]:
```suggestion
				// Wait until the default mode is retrieved and start rendering canvas.
```

**Review by t-hamano — COMMENTED** [review]
When changing the slug, it seems that the editor is re-rendered because the `defaultMode` toggles between `undefined` and `template-locked`. Is there a way to fix this behavior?


https://github.com/user-attachments/assets/38d03ffb-960f-404e-8a03-4a179c09dfab

**Comment by Mamaduka** [comment]
> When changing the slug, it seems that the editor is re-rendered because the defaultMode toggles between undefined and template-locked. Is there a way to fix this behavior?

Yes, I'm aware of that, but I haven't found the right solution yet. Conditionally using the `hasTemplate` value in `hasResolvedDefaultMode` prevents rendering mode flash.

The `undefinfed` is returned because the editor has to resolve the template based on the new slug, and `hasTemplate` becomes false while the resolution is in progress. This also affects the `hasResolvedDefaultMode` condition and `defaultMode`

P.S. The template flash you see when changing the slug is technically the same as trying to swap the template, but it's not apparent. I'm not sure if we can communicate this from the slug popover.

**Comment by carolinan** [comment]
Maybe the default template needs to be stored somewhere the same way as a custom template is, if that means it does not have to resolve the template based on the slug.

**Comment by Mamaduka** [comment]
> Maybe the default template needs to be stored somewhere the same way as a custom template is, if that means it does not have to resolve the template based on the slug.

I think it still has to react to the slug change. Example: You start working on a draft page and then decide that it should use the `page-heros` template file you've in the hierarchy, so you change the slug to be `heros`.

Generally speaking, template lookup/resolution needs some improvements (related https://github.com/WordPress/gutenberg/issues/64341#issuecomment-2667560930), but it's out of the scope of this PR.

**Review by t-hamano — APPROVED** [review]
For now, it seems best to ship this PR and address the other improvements in a follow-up.

**Review by fabiankaegy — APPROVED** [review]
Agree with @t-hamano here. This PR does not produce any regressions in my testing and helps to move things in the right direction :) 

Thank you @Mamaduka 🚀

**Comment by Mamaduka** [comment]
Thanks for the feedback, everyone!
