### PR TITLE
Code block: paste plain text

### LINKED ISSUE #26689: Pasted HTML code inside the core code block is formatted/parsed
**Describe the bug**

Pasted HTML code inside the core code block is formatted/parsed.

**To reproduce**

1. Open the default WordPress homepage
2. Open the HTML source code of the page using the browser's view page source option
3. Copy the HTML code
4. Go to the editor and insert a code block
5. Paste previously copied HTML code

**Expected behavior**

The code that I paste inside the core code block remains unaltered.

**Screenshots**

Result with Gutenberg 9.3.0-rc.1:

![Screenshot from 2020-11-04 12-15-35](https://user-images.githubusercontent.com/6097856/98098827-84b0b400-1e97-11eb-8e3d-d66c6a15bc84.png)

Result with the core editor:

![Screenshot from 2020-11-04 12-18-40](https://user-images.githubusercontent.com/6097856/98099186-ecff9580-1e97-11eb-8275-8a10998af30b.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5.3
- Gutenberg plugin: 9.3.0-rc.1

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Browser: Firefox
 - Version: 81

**Additional context**

Discussion about this: https://wordpress.slack.com/archives/C02QB2JS7/p1604424472345400 it also contains screen recordings.

This also happens in Gutenberg 9.1, 9.2, but works okay with the WordPress editor or Gutenberg 9.0

From the console...

<details>
  <summary>Received HTML:</summary>
  
```
<pre id="line1"><span></span><span class="doctype">&lt;!DOCTYPE html&gt;</span><span>
<span id="line2"></span>
<span id="line3"></span></span><span>&lt;<span class="start-tag">html</span> <span class="attribute-name">class</span>="<a class="attribute-value">no-js</a>" <span class="attribute-name">lang</span>="<a class="attribute-value">en-US</a>"&gt;</span><span>
<span id="line4"></span>
<span id="line5"></span>	</span><span>&lt;<span class="start-tag">head</span>&gt;</span><span>
<span id="line6"></span>
<span id="line7"></span>		</span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">charset</span>="<a class="attribute-value">UTF-8</a>"&gt;</span><span>
<span id="line8"></span>		</span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">name</span>="<a class="attribute-value">viewport</a>" <span class="attribute-name">content</span>="<a class="attribute-value">width=device-width, initial-scale=1.0</a>" &gt;</span><span>
<span id="line9"></span>
<span id="line10"></span>		</span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">profile</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:https://gmpg.org/xfn/11">https://gmpg.org/xfn/11</a>"&gt;</span><span>
<span id="line11"></span>
<span id="line12"></span>		</span><span>&lt;<span class="start-tag">title</span>&gt;</span><span>Plugin Test <span class="entity"><span>&amp;</span>#8211;</span> Just another WordPress site</span><span>&lt;/<span class="end-tag">title</span>&gt;</span><span>
<span id="line13"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>='<a class="attribute-value">dns-prefetch</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://s.w.org/">//s.w.org</a>' <span>/</span>&gt;</span><span>
<span id="line14"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">alternate</a>" <span class="attribute-name">type</span>="<a class="attribute-value">application/rss+xml</a>" <span class="attribute-name">title</span>="<a class="attribute-value">Plugin Test <span class="entity"><span>&amp;</span>raquo;</span> Feed</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/feed/">http://plugin-test.localhost/feed/</a>" <span>/</span>&gt;</span><span>
<span id="line15"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">alternate</a>" <span class="attribute-name">type</span>="<a class="attribute-value">application/rss+xml</a>" <span class="attribute-name">title</span>="<a class="attribute-value">Plugin Test <span class="entity"><span>&amp;</span>raquo;</span> Comments Feed</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/comments/feed/">http://plugin-test.localhost/comments/feed/</a>" <span>/</span>&gt;</span><span>
<span id="line16"></span>		</span><span>&lt;<span class="start-tag">script</span>&gt;</span><span>
<span id="line17"></span>			window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/13.0.0\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/13.0.0\/svg\/","svgExt":".svg","source":{"concatemoji":"http:\/\/plugin-test.localhost\/wp-includes\/js\/wp-emoji-release.min.js?ver=5.5.3"}};
<span id="line18"></span>			!function(e,a,t){var r,n,o,i,p=a.createElement("canvas"),s=p.getContext&amp;&amp;p.getContext("2d");function c(e,t){var a=String.fromCharCode;s.clearRect(0,0,p.width,p.height),s.fillText(a.apply(this,e),0,0);var r=p.toDataURL();return s.clearRect(0,0,p.width,p.height),s.fillText(a.apply(this,t),0,0),r===p.toDataURL()}function l(e){if(!s||!s.fillText)return!1;switch(s.textBaseline="top",s.font="600 32px Arial",e){case"flag":return!c([127987,65039,8205,9895,65039],[127987,65039,8203,9895,65039])&amp;&amp;(!c([55356,56826,55356,56819],[55356,56826,8203,55356,56819])&amp;&amp;!c([55356,57332,56128,56423,56128,56418,56128,56421,56128,56430,56128,56423,56128,56447],[55356,57332,8203,56128,56423,8203,56128,56418,8203,56128,56421,8203,56128,56430,8203,56128,56423,8203,56128,56447]));case"emoji":return!c([55357,56424,8205,55356,57212],[55357,56424,8203,55356,57212])}return!1}function d(e){var t=a.createElement("script");t.src=e,t.defer=t.type="text/javascript",a.getElementsByTagName("head")[0].appendChild(t)}for(i=Array("flag","emoji"),t.supports={everything:!0,everythingExceptFlag:!0},o=0;o</span><span>&lt;i</span><span>.length;o++)t.supports[i[o]]=l(i[o]),t.supports.everything=t.supports.everything&amp;&amp;t.supports[i[o]],"flag"!==i[o]&amp;&amp;(t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&amp;&amp;t.supports[i[o]]);t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&amp;&amp;!t.supports.flag,t.DOMReady=!1,t.readyCallback=function(){t.DOMReady=!0},t.supports.everything||(n=function(){t.readyCallback()},a.addEventListener?(a.addEventListener("DOMContentLoaded",n,!1),e.addEventListener("load",n,!1)):(e.attachEvent("onload",n),a.attachEvent("onreadystatechange",function(){"complete"===a.readyState&amp;&amp;t.readyCallback()})),(r=t.source||{}).concatemoji?d(r.concatemoji):r.wpemoji&amp;&amp;r.twemoji&amp;&amp;(d(r.twemoji),d(r.wpemoji)))}(window,document,window._wpemojiSettings);
<span id="line19"></span>		</span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line20"></span>		</span><span>&lt;<span class="start-tag">style</span>&gt;</span><span>
<span id="line21"></span>img.wp-smiley,
<span id="line22"></span>img.emoji {
<span id="line23"></span>	display: inline !important;
<span id="line24"></span>	border: none !important;
<span id="line25"></span>	box-shadow: none !important;
<span id="line26"></span>	height: 1em !important;
<span id="line27"></span>	width: 1em !important;
<span id="line28"></span>	margin: 0 .07em !important;
<span id="line29"></span>	vertical-align: -0.1em !important;
<span id="line30"></span>	background: none !important;
<span id="line31"></span>	padding: 0 !important;
<span id="line32"></span>}
<span id="line33"></span></span><span>&lt;/<span class="end-tag">style</span>&gt;</span><span>
<span id="line34"></span>	</span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>='<a class="attribute-value">stylesheet</a>' <span class="attribute-name">id</span>='<a class="attribute-value">dashicons-css</a>'  <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-includes/css/dashicons.min.css?ver=5.5.3">http://plugin-test.localhost/wp-includes/css/dashicons.min.css?ver=5.5.3</a>' <span class="attribute-name">media</span>='<a class="attribute-value">all</a>' <span>/</span>&gt;</span><span>
<span id="line35"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>='<a class="attribute-value">stylesheet</a>' <span class="attribute-name">id</span>='<a class="attribute-value">admin-bar-css</a>'  <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-includes/css/admin-bar.min.css?ver=5.5.3">http://plugin-test.localhost/wp-includes/css/admin-bar.min.css?ver=5.5.3</a>' <span class="attribute-name">media</span>='<a class="attribute-value">all</a>' <span>/</span>&gt;</span><span>
<span id="line36"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>='<a class="attribute-value">stylesheet</a>' <span class="attribute-name">id</span>='<a class="attribute-value">wp-block-library-css</a>'  <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-content/plugins/gutenberg/build/block-library/style.css?ver=1604325854">http://plugin-test.localhost/wp-content/plugins/gutenberg/build/block-library/style.css?ver=1604325854</a>' <span class="attribute-name">media</span>='<a class="attribute-value">all</a>' <span>/</span>&gt;</span><span>
<span id="line37"></span></span><span>&lt;<span class="start-tag">style</span> <span class="attribute-name">id</span>='<a class="attribute-value">global-styles-inline-css</a>'&gt;</span><span>
<span id="line38"></span>:root{--wp--preset--color--accent:#cd2653;--wp--preset--color--primary:#000000;--wp--preset--color--secondary:#6d6d6d;--wp--preset--color--subtle-background:#dcd7ca;--wp--preset--color--background:#f5efe0;--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple:linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%);--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan:linear-gradient(135deg,rgb(122,220,180) 0%,rgb(0,208,130) 100%);--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange:linear-gradient(135deg,rgba(252,185,0,1) 0%,rgba(255,105,0,1) 100%);--wp--preset--gradient--luminous-vivid-orange-to-vivid-red:linear-gradient(135deg,rgba(255,105,0,1) 0%,rgb(207,46,46) 100%);--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray:linear-gradient(135deg,rgb(238,238,238) 0%,rgb(169,184,195) 100%);--wp--preset--gradient--cool-to-warm-spectrum:linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%);--wp--preset--gradient--blush-light-purple:linear-gradient(135deg,rgb(255,206,236) 0%,rgb(152,150,240) 100%);--wp--preset--gradient--blush-bordeaux:linear-gradient(135deg,rgb(254,205,165) 0%,rgb(254,45,45) 50%,rgb(107,0,62) 100%);--wp--preset--gradient--luminous-dusk:linear-gradient(135deg,rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);--wp--preset--gradient--pale-ocean:linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);--wp--preset--gradient--electric-grass:linear-gradient(135deg,rgb(202,248,128) 0%,rgb(113,206,126) 100%);--wp--preset--gradient--midnight:linear-gradient(135deg,rgb(2,3,129) 0%,rgb(40,116,252) 100%);--wp--preset--font-size--small:18px;--wp--preset--font-size--normal:21px;--wp--preset--font-size--large:26.25px;--wp--preset--font-size--larger:32px;}.has-accent-color{color:#cd2653;}
<span id="line39"></span>.has-primary-color{color:#000000;}
<span id="line40"></span>.has-secondary-color{color:#6d6d6d;}
<span id="line41"></span>.has-subtle-background-color{color:#dcd7ca;}
<span id="line42"></span>.has-background-color{color:#f5efe0;}
<span id="line43"></span>.has-accent-background-color{background-color:#cd2653;}
<span id="line44"></span>.has-primary-background-color{background-color:#000000;}
<span id="line45"></span>.has-secondary-background-color{background-color:#6d6d6d;}
<span id="line46"></span>.has-subtle-background-background-color{background-color:#dcd7ca;}
<span id="line47"></span>.has-background-background-color{background-color:#f5efe0;}
<span id="line48"></span>.has-vivid-cyan-blue-to-vivid-purple-gradient-background{background:linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%);}
<span id="line49"></span>.has-light-green-cyan-to-vivid-green-cyan-gradient-background{background:linear-gradient(135deg,rgb(122,220,180) 0%,rgb(0,208,130) 100%);}
<span id="line50"></span>.has-luminous-vivid-amber-to-luminous-vivid-orange-gradient-background{background:linear-gradient(135deg,rgba(252,185,0,1) 0%,rgba(255,105,0,1) 100%);}
<span id="line51"></span>.has-luminous-vivid-orange-to-vivid-red-gradient-background{background:linear-gradient(135deg,rgba(255,105,0,1) 0%,rgb(207,46,46) 100%);}
<span id="line52"></span>.has-very-light-gray-to-cyan-bluish-gray-gradient-background{background:linear-gradient(135deg,rgb(238,238,238) 0%,rgb(169,184,195) 100%);}
<span id="line53"></span>.has-cool-to-warm-spectrum-gradient-background{background:linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%);}
<span id="line54"></span>.has-blush-light-purple-gradient-background{background:linear-gradient(135deg,rgb(255,206,236) 0%,rgb(152,150,240) 100%);}
<span id="line55"></span>.has-blush-bordeaux-gradient-background{background:linear-gradient(135deg,rgb(254,205,165) 0%,rgb(254,45,45) 50%,rgb(107,0,62) 100%);}
<span id="line56"></span>.has-luminous-dusk-gradient-background{background:linear-gradient(135deg,rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);}
<span id="line57"></span>.has-pale-ocean-gradient-background{background:linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);}
<span id="line58"></span>.has-electric-grass-gradient-background{background:linear-gradient(135deg,rgb(202,248,128) 0%,rgb(113,206,126) 100%);}
<span id="line59"></span>.has-midnight-gradient-background{background:linear-gradient(135deg,rgb(2,3,129) 0%,rgb(40,116,252) 100%);}
<span id="line60"></span>.has-small-font-size{font-size:18px;}
<span id="line61"></span>.has-normal-font-size{font-size:21px;}
<span id="line62"></span>.has-large-font-size{font-size:26.25px;}
<span id="line63"></span>.has-larger-font-size{font-size:32px;}
<span id="line64"></span>
<span id="line65"></span></span><span>&lt;/<span class="end-tag">style</span>&gt;</span><span>
<span id="line66"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>='<a class="attribute-value">stylesheet</a>' <span class="attribute-name">id</span>='<a class="attribute-value">twentytwenty-style-css</a>'  <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-content/themes/twentytwenty/style.css?ver=1.5">http://plugin-test.localhost/wp-content/themes/twentytwenty/style.css?ver=1.5</a>' <span class="attribute-name">media</span>='<a class="attribute-value">all</a>' <span>/</span>&gt;</span><span>
<span id="line67"></span></span><span>&lt;<span class="start-tag">style</span> <span class="attribute-name">id</span>='<a class="attribute-value">twentytwenty-style-inline-css</a>'&gt;</span><span>
<span id="line68"></span>.color-accent,.color-accent-hover:hover,.color-accent-hover:focus,:root .has-accent-color,.has-drop-cap:not(:focus):first-letter,.wp-block-button.is-style-outline,a { color: #cd2653; }blockquote,.border-color-accent,.border-color-accent-hover:hover,.border-color-accent-hover:focus { border-color: #cd2653; }button,.button,.faux-button,.wp-block-button__link,.wp-block-file .wp-block-file__button,input[type="button"],input[type="reset"],input[type="submit"],.bg-accent,.bg-accent-hover:hover,.bg-accent-hover:focus,:root .has-accent-background-color,.comment-reply-link { background-color: #cd2653; }.fill-children-accent,.fill-children-accent * { fill: #cd2653; }body,.entry-title a,:root .has-primary-color { color: #000000; }:root .has-primary-background-color { background-color: #000000; }cite,figcaption,.wp-caption-text,.post-meta,.entry-content .wp-block-archives li,.entry-content .wp-block-categories li,.entry-content .wp-block-latest-posts li,.wp-block-latest-comments__comment-date,.wp-block-latest-posts__post-date,.wp-block-embed figcaption,.wp-block-image figcaption,.wp-block-pullquote cite,.comment-metadata,.comment-respond .comment-notes,.comment-respond .logged-in-as,.pagination .dots,.entry-content hr:not(.has-background),hr.styled-separator,:root .has-secondary-color { color: #6d6d6d; }:root .has-secondary-background-color { background-color: #6d6d6d; }pre,fieldset,input,textarea,table,table *,hr { border-color: #dcd7ca; }caption,code,code,kbd,samp,.wp-block-table.is-style-stripes tbody tr:nth-child(odd),:root .has-subtle-background-background-color { background-color: #dcd7ca; }.wp-block-table.is-style-stripes { border-bottom-color: #dcd7ca; }.wp-block-latest-posts.is-grid li { border-top-color: #dcd7ca; }:root .has-subtle-background-color { color: #dcd7ca; }body:not(.overlay-header) .primary-menu &gt; li &gt; a,body:not(.overlay-header) .primary-menu &gt; li &gt; .icon,.modal-menu a,.footer-menu a, .footer-widgets a,#site-footer .wp-block-button.is-style-outline,.wp-block-pullquote:before,.singular:not(.overlay-header) .entry-header a,.archive-header a,.header-footer-group .color-accent,.header-footer-group .color-accent-hover:hover { color: #cd2653; }.social-icons a,#site-footer button:not(.toggle),#site-footer .button,#site-footer .faux-button,#site-footer .wp-block-button__link,#site-footer .wp-block-file__button,#site-footer input[type="button"],#site-footer input[type="reset"],#site-footer input[type="submit"] { background-color: #cd2653; }.header-footer-group,body:not(.overlay-header) #site-header .toggle,.menu-modal .toggle { color: #000000; }body:not(.overlay-header) .primary-menu ul { background-color: #000000; }body:not(.overlay-header) .primary-menu &gt; li &gt; ul:after { border-bottom-color: #000000; }body:not(.overlay-header) .primary-menu ul ul:after { border-left-color: #000000; }.site-description,body:not(.overlay-header) .toggle-inner .toggle-text,.widget .post-date,.widget .rss-date,.widget_archive li,.widget_categories li,.widget cite,.widget_pages li,.widget_meta li,.widget_nav_menu li,.powered-by-wordpress,.to-the-top,.singular .entry-header .post-meta,.singular:not(.overlay-header) .entry-header .post-meta a { color: #6d6d6d; }.header-footer-group pre,.header-footer-group fieldset,.header-footer-group input,.header-footer-group textarea,.header-footer-group table,.header-footer-group table *,.footer-nav-widgets-wrapper,#site-footer,.menu-modal nav *,.footer-widgets-outer-wrapper,.footer-top { border-color: #dcd7ca; }.header-footer-group table caption,body:not(.overlay-header) .header-inner .toggle-wrapper::before { background-color: #dcd7ca; }
<span id="line69"></span></span><span>&lt;/<span class="end-tag">style</span>&gt;</span><span>
<span id="line70"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>='<a class="attribute-value">stylesheet</a>' <span class="attribute-name">id</span>='<a class="attribute-value">twentytwenty-print-style-css</a>'  <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-content/themes/twentytwenty/print.css?ver=1.5">http://plugin-test.localhost/wp-content/themes/twentytwenty/print.css?ver=1.5</a>' <span class="attribute-name">media</span>='<a class="attribute-value">print</a>' <span>/</span>&gt;</span><span>
<span id="line71"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">src</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-content/themes/twentytwenty/assets/js/index.js?ver=1.5">http://plugin-test.localhost/wp-content/themes/twentytwenty/assets/js/index.js?ver=1.5</a>' <span class="attribute-name">id</span>='<a class="attribute-value">twentytwenty-js-js</a>' <span class="attribute-name">async</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line72"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">https://api.w.org/</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-json/">http://plugin-test.localhost/wp-json/</a>" <span>/</span>&gt;</span><span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">EditURI</a>" <span class="attribute-name">type</span>="<a class="attribute-value">application/rsd+xml</a>" <span class="attribute-name">title</span>="<a class="attribute-value">RSD</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/xmlrpc.php?rsd">http://plugin-test.localhost/xmlrpc.php?rsd</a>" <span>/</span>&gt;</span><span>
<span id="line73"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">wlwmanifest</a>" <span class="attribute-name">type</span>="<a class="attribute-value">application/wlwmanifest+xml</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-includes/wlwmanifest.xml">http://plugin-test.localhost/wp-includes/wlwmanifest.xml</a>" <span>/</span>&gt;</span><span> 
<span id="line74"></span></span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">name</span>="<a class="attribute-value">generator</a>" <span class="attribute-name">content</span>="<a class="attribute-value">WordPress 5.5.3</a>" <span>/</span>&gt;</span><span>
<span id="line75"></span>	</span><span>&lt;<span class="start-tag">script</span>&gt;</span><span>document.documentElement.className = document.documentElement.className.replace( 'no-js', 'js' );</span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line76"></span>	</span><span>&lt;<span class="start-tag">style</span>&gt;</span><span>.recentcomments a{display:inline !important;padding:0 !important;margin:0 !important;}</span><span>&lt;/<span class="end-tag">style</span>&gt;</span><span></span><span>&lt;<span class="start-tag">style</span> <span class="attribute-name">media</span>="<a class="attribute-value">print</a>"&gt;</span><span>#wpadminbar { display:none; }</span><span>&lt;/<span class="end-tag">style</span>&gt;</span><span>
<span id="line77"></span>	</span><span>&lt;<span class="start-tag">style</span> <span class="attribute-name">media</span>="<a class="attribute-value">screen</a>"&gt;</span><span>
<span id="line78"></span>	html { margin-top: 32px !important; }
<span id="line79"></span>	* html body { margin-top: 32px !important; }
<span id="line80"></span>	@media screen and ( max-width: 782px ) {
<span id="line81"></span>		html { margin-top: 46px !important; }
<span id="line82"></span>		* html body { margin-top: 46px !important; }
<span id="line83"></span>	}
<span id="line84"></span></span><span>&lt;/<span class="end-tag">style</span>&gt;</span><span>
<span id="line85"></span>	
<span id="line86"></span>	</span><span>&lt;/<span class="end-tag">head</span>&gt;</span><span>
<span id="line87"></span>
<span id="line88"></span>	</span><span>&lt;<span class="start-tag">body</span> <span class="attribute-name">class</span>="<a class="attribute-value">home blog logged-in admin-bar no-customize-support wp-embed-responsive enable-search-modal has-no-pagination showing-comments show-avatars footer-top-visible</a>"&gt;</span><span>
<span id="line89"></span>
<span id="line90"></span>			</span><span>&lt;<span class="start-tag">script</span>&gt;</span><span>
<span id="line91"></span>		(function() {
<span id="line92"></span>			var request, b = document.body, c = 'className', cs = 'customize-support', rcs = new RegExp('(^|\\s+)(no-)?'+cs+'(\\s+|$)');
<span id="line93"></span>
<span id="line94"></span>				request = true;
<span id="line95"></span>	
<span id="line96"></span>			b[c] = b[c].replace( rcs, ' ' );
<span id="line97"></span>			// The customizer requires postMessage and CORS (if the site is cross domain).
<span id="line98"></span>			b[c] += ( window.postMessage &amp;&amp; request ? ' ' : ' no-' ) + cs;
<span id="line99"></span>		}());
<span id="line100"></span>	</span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line101"></span>			</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">id</span>="<a class="attribute-value">wpadminbar</a>" <span class="attribute-name">class</span>="<a class="attribute-value">nojq nojs</a>"&gt;</span><span>
<span id="line102"></span>							</span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>="<a class="attribute-value">screen-reader-shortcut</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/#wp-toolbar">#wp-toolbar</a>" <span class="attribute-name">tabindex</span>="<a class="attribute-value">1</a>"&gt;</span><span>Skip to toolbar</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>
<span id="line103"></span>						</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">quicklinks</a>" <span class="attribute-name">id</span>="<a class="attribute-value">wp-toolbar</a>" <span class="attribute-name">role</span>="<a class="attribute-value">navigation</a>" <span class="attribute-name">aria-label</span>="<a class="attribute-value">Toolbar</a>"&gt;</span><span>
<span id="line104"></span>				</span><span>&lt;<span class="start-tag">ul</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-root-default</a>' <span class="attribute-name">class</span>="<a class="attribute-value">ab-top-menu</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-wp-logo</a>' <span class="attribute-name">class</span>="<a class="attribute-value">menupop</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">aria-haspopup</span>="<a class="attribute-value">true</a>" <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/about.php">http://plugin-test.localhost/wp-admin/about.php</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">ab-icon</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">screen-reader-text</a>"&gt;</span><span>About WordPress</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">ab-sub-wrapper</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">ul</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-wp-logo-default</a>' <span class="attribute-name">class</span>="<a class="attribute-value">ab-submenu</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-about</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/about.php">http://plugin-test.localhost/wp-admin/about.php</a>'&gt;</span><span>About WordPress</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span></span><span>&lt;<span class="start-tag">ul</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-wp-logo-external</a>' <span class="attribute-name">class</span>="<a class="attribute-value">ab-sub-secondary ab-submenu</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-wporg</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:https://wordpress.org/">https://wordpress.org/</a>'&gt;</span><span>WordPress.org</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-documentation</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:https://codex.wordpress.org/">https://codex.wordpress.org/</a>'&gt;</span><span>Documentation</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-support-forums</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:https://wordpress.org/support/">https://wordpress.org/support/</a>'&gt;</span><span>Support</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-feedback</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:https://wordpress.org/support/forum/requests-and-feedback">https://wordpress.org/support/forum/requests-and-feedback</a>'&gt;</span><span>Feedback</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-site-name</a>' <span class="attribute-name">class</span>="<a class="attribute-value">menupop</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">aria-haspopup</span>="<a class="attribute-value">true</a>" <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/">http://plugin-test.localhost/wp-admin/</a>'&gt;</span><span>Plugin Test</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">ab-sub-wrapper</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">ul</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-site-name-default</a>' <span class="attribute-name">class</span>="<a class="attribute-value">ab-submenu</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-dashboard</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/">http://plugin-test.localhost/wp-admin/</a>'&gt;</span><span>Dashboard</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span></span><span>&lt;<span class="start-tag">ul</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-appearance</a>' <span class="attribute-name">class</span>="<a class="attribute-value">ab-submenu</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-themes</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/themes.php">http://plugin-test.localhost/wp-admin/themes.php</a>'&gt;</span><span>Themes</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-widgets</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/themes.php?page=gutenberg-widgets">http://plugin-test.localhost/wp-admin/themes.php?page=gutenberg-widgets</a>'&gt;</span><span>Widgets</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-menus</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/nav-menus.php">http://plugin-test.localhost/wp-admin/nav-menus.php</a>'&gt;</span><span>Menus</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-background</a>' <span class="attribute-name">class</span>="<a class="attribute-value">hide-if-customize</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/themes.php?page=custom-background">http://plugin-test.localhost/wp-admin/themes.php?page=custom-background</a>'&gt;</span><span>Background</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-customize</a>' <span class="attribute-name">class</span>="<a class="attribute-value">hide-if-no-customize</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/customize.php?url=http%3A%2F%2Fplugin-test.localhost%2F">http://plugin-test.localhost/wp-admin/customize.php?url=http%3A%2F%2Fplugin-test.localhost%2F</a>'&gt;</span><span>Customize</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-comments</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/edit-comments.php">http://plugin-test.localhost/wp-admin/edit-comments.php</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">ab-icon</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">ab-label awaiting-mod pending-count count-0</a>" <span class="attribute-name">aria-hidden</span>="<a class="attribute-value">true</a>"&gt;</span><span>0</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">screen-reader-text comments-in-moderation-text</a>"&gt;</span><span>0 Comments in moderation</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-new-content</a>' <span class="attribute-name">class</span>="<a class="attribute-value">menupop</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">aria-haspopup</span>="<a class="attribute-value">true</a>" <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/post-new.php">http://plugin-test.localhost/wp-admin/post-new.php</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">ab-icon</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">ab-label</a>"&gt;</span><span>New</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">ab-sub-wrapper</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">ul</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-new-content-default</a>' <span class="attribute-name">class</span>="<a class="attribute-value">ab-submenu</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-new-post</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/post-new.php">http://plugin-test.localhost/wp-admin/post-new.php</a>'&gt;</span><span>Post</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-new-media</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/media-new.php">http://plugin-test.localhost/wp-admin/media-new.php</a>'&gt;</span><span>Media</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-new-page</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/post-new.php?post_type=page">http://plugin-test.localhost/wp-admin/post-new.php?post_type=page</a>'&gt;</span><span>Page</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-new-user</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/user-new.php">http://plugin-test.localhost/wp-admin/user-new.php</a>'&gt;</span><span>User</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span></span><span>&lt;<span class="start-tag">ul</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-top-secondary</a>' <span class="attribute-name">class</span>="<a class="attribute-value">ab-top-secondary ab-top-menu</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-search</a>' <span class="attribute-name">class</span>="<a class="attribute-value">admin-bar-search</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">ab-item ab-empty-item</a>" <span class="attribute-name">tabindex</span>="<a class="attribute-value">-1</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">form</span> <span class="attribute-name">action</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/">http://plugin-test.localhost/</a>" <span class="attribute-name">method</span>="<a class="attribute-value">get</a>" <span class="attribute-name">id</span>="<a class="attribute-value">adminbarsearch</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">input</span> <span class="attribute-name">class</span>="<a class="attribute-value">adminbar-input</a>" <span class="attribute-name">name</span>="<a class="attribute-value">s</a>" <span class="attribute-name">id</span>="<a class="attribute-value">adminbar-search</a>" <span class="attribute-name">type</span>="<a class="attribute-value">text</a>" <span class="attribute-name">value</span>="<a class="attribute-value"></a>" <span class="attribute-name">maxlength</span>="<a class="attribute-value">150</a>" <span>/</span>&gt;</span><span></span><span>&lt;<span class="start-tag">label</span> <span class="attribute-name">for</span>="<a class="attribute-value">adminbar-search</a>" <span class="attribute-name">class</span>="<a class="attribute-value">screen-reader-text</a>"&gt;</span><span>Search</span><span>&lt;/<span class="end-tag">label</span>&gt;</span><span></span><span>&lt;<span class="start-tag">input</span> <span class="attribute-name">type</span>="<a class="attribute-value">submit</a>" <span class="attribute-name">class</span>="<a class="attribute-value">adminbar-button</a>" <span class="attribute-name">value</span>="<a class="attribute-value">Search</a>"<span>/</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">form</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-my-account</a>' <span class="attribute-name">class</span>="<a class="attribute-value">menupop with-avatar</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">aria-haspopup</span>="<a class="attribute-value">true</a>" <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/profile.php">http://plugin-test.localhost/wp-admin/profile.php</a>'&gt;</span><span>Howdy, </span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">display-name</a>"&gt;</span><span>admin</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">alt</span>='<a class="attribute-value"></a>' <span class="attribute-name">src</span>='<a class="attribute-value" href="view-source:http://1.gravatar.com/avatar/77a591799c03c21b44b472e151bc8374?s=26&amp;d=mm&amp;r=g">http://1.gravatar.com/avatar/77a591799c03c21b44b472e151bc8374?s=26<span class="entity"><span>&amp;</span>#038;</span>d=mm<span class="entity"><span>&amp;</span>#038;</span>r=g</a>' <span class="attribute-name">srcset</span>='<a class="attribute-value">http://1.gravatar.com/avatar/77a591799c03c21b44b472e151bc8374?s=52<span class="entity"><span>&amp;</span>#038;</span>d=mm<span class="entity"><span>&amp;</span>#038;</span>r=g 2x</a>' <span class="attribute-name">class</span>='<a class="attribute-value">avatar avatar-26 photo</a>' <span class="attribute-name">height</span>='<a class="attribute-value">26</a>' <span class="attribute-name">width</span>='<a class="attribute-value">26</a>' <span class="attribute-name">loading</span>='<a class="attribute-value">lazy</a>'<span>/</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">ab-sub-wrapper</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">ul</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-user-actions</a>' <span class="attribute-name">class</span>="<a class="attribute-value">ab-submenu</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-user-info</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">tabindex</span>="<a class="attribute-value">-1</a>" <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/profile.php">http://plugin-test.localhost/wp-admin/profile.php</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">img</span> <span class="attribute-name">alt</span>='<a class="attribute-value"></a>' <span class="attribute-name">src</span>='<a class="attribute-value" href="view-source:http://1.gravatar.com/avatar/77a591799c03c21b44b472e151bc8374?s=64&amp;d=mm&amp;r=g">http://1.gravatar.com/avatar/77a591799c03c21b44b472e151bc8374?s=64<span class="entity"><span>&amp;</span>#038;</span>d=mm<span class="entity"><span>&amp;</span>#038;</span>r=g</a>' <span class="attribute-name">srcset</span>='<a class="attribute-value">http://1.gravatar.com/avatar/77a591799c03c21b44b472e151bc8374?s=128<span class="entity"><span>&amp;</span>#038;</span>d=mm<span class="entity"><span>&amp;</span>#038;</span>r=g 2x</a>' <span class="attribute-name">class</span>='<a class="attribute-value">avatar avatar-64 photo</a>' <span class="attribute-name">height</span>='<a class="attribute-value">64</a>' <span class="attribute-name">width</span>='<a class="attribute-value">64</a>' <span class="attribute-name">loading</span>='<a class="attribute-value">lazy</a>'<span>/</span>&gt;</span><span></span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>='<a class="attribute-value">display-name</a>'&gt;</span><span>admin</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-edit-profile</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/profile.php">http://plugin-test.localhost/wp-admin/profile.php</a>'&gt;</span><span>Edit Profile</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">id</span>='<a class="attribute-value">wp-admin-bar-logout</a>'&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>='<a class="attribute-value">ab-item</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-login.php?action=logout&amp;_wpnonce=2c655d3f1a">http://plugin-test.localhost/wp-login.php?action=logout<span class="entity"><span>&amp;</span>#038;</span>_wpnonce=2c655d3f1a</a>'&gt;</span><span>Log Out</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span>			</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line105"></span>						</span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>="<a class="attribute-value">screen-reader-shortcut</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-login.php?action=logout&amp;_wpnonce=2c655d3f1a">http://plugin-test.localhost/wp-login.php?action=logout<span class="entity"><span>&amp;</span>#038;</span>_wpnonce=2c655d3f1a</a>"&gt;</span><span>Log Out</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>
<span id="line106"></span>					</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line107"></span>
<span id="line108"></span>		</span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>="<a class="attribute-value">skip-link screen-reader-text</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/#site-content">#site-content</a>"&gt;</span><span>Skip to the content</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>
<span id="line109"></span>		</span><span>&lt;<span class="start-tag">header</span> <span class="attribute-name">id</span>="<a class="attribute-value">site-header</a>" <span class="attribute-name">class</span>="<a class="attribute-value">header-footer-group</a>" <span class="attribute-name">role</span>="<a class="attribute-value">banner</a>"&gt;</span><span>
<span id="line110"></span>
<span id="line111"></span>			</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">header-inner section-inner</a>"&gt;</span><span>
<span id="line112"></span>
<span id="line113"></span>				</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">header-titles-wrapper</a>"&gt;</span><span>
<span id="line114"></span>
<span id="line115"></span>					
<span id="line116"></span>						</span><span>&lt;<span class="start-tag">button</span> <span class="attribute-name">class</span>="<a class="attribute-value">toggle search-toggle mobile-search-toggle</a>" <span class="attribute-name">data-toggle-target</span>="<a class="attribute-value">.search-modal</a>" <span class="attribute-name">data-toggle-body-class</span>="<a class="attribute-value">showing-search-modal</a>" <span class="attribute-name">data-set-focus</span>="<a class="attribute-value">.search-modal .search-field</a>" <span class="attribute-name">aria-expanded</span>="<a class="attribute-value">false</a>"&gt;</span><span>
<span id="line117"></span>							</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">toggle-inner</a>"&gt;</span><span>
<span id="line118"></span>								</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">toggle-icon</a>"&gt;</span><span>
<span id="line119"></span>									</span><span>&lt;<span class="start-tag">svg</span> <span class="attribute-name">class</span>="<a class="attribute-value">svg-icon</a>" <span class="attribute-name">aria-hidden</span>="<a class="attribute-value">true</a>" <span class="attribute-name">role</span>="<a class="attribute-value">img</a>" <span class="attribute-name">focusable</span>="<a class="attribute-value">false</a>" <span class="attribute-name">xmlns</span>="<a class="attribute-value">http://www.w3.org/2000/svg</a>" <span class="attribute-name">width</span>="<a class="attribute-value">23</a>" <span class="attribute-name">height</span>="<a class="attribute-value">23</a>" <span class="attribute-name">viewBox</span>="<a class="attribute-value">0 0 23 23</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">path</span> <span class="attribute-name">d</span>="<a class="attribute-value">M38.710696,48.0601792 L43,52.3494831 L41.3494831,54 L37.0601792,49.710696 C35.2632422,51.1481185 32.9839107,52.0076499 30.5038249,52.0076499 C24.7027226,52.0076499 20,47.3049272 20,41.5038249 C20,35.7027226 24.7027226,31 30.5038249,31 C36.3049272,31 41.0076499,35.7027226 41.0076499,41.5038249 C41.0076499,43.9839107 40.1481185,46.2632422 38.710696,48.0601792 Z M36.3875844,47.1716785 C37.8030221,45.7026647 38.6734666,43.7048964 38.6734666,41.5038249 C38.6734666,36.9918565 35.0157934,33.3341833 30.5038249,33.3341833 C25.9918565,33.3341833 22.3341833,36.9918565 22.3341833,41.5038249 C22.3341833,46.0157934 25.9918565,49.6734666 30.5038249,49.6734666 C32.7048964,49.6734666 34.7026647,48.8030221 36.1716785,47.3875844 C36.2023931,47.347638 36.2360451,47.3092237 36.2726343,47.2726343 C36.3092237,47.2360451 36.347638,47.2023931 36.3875844,47.1716785 Z</a>" <span class="attribute-name">transform</span>="<a class="attribute-value">translate(-20 -31)</a>" <span>/</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">svg</span>&gt;</span><span>								</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line120"></span>								</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">toggle-text</a>"&gt;</span><span>Search</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line121"></span>							</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line122"></span>						</span><span>&lt;/<span class="end-tag">button</span>&gt;</span><span></span><span class="comment">&lt;!-- .search-toggle --&gt;</span><span>
<span id="line123"></span>
<span id="line124"></span>					
<span id="line125"></span>					</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">header-titles</a>"&gt;</span><span>
<span id="line126"></span>
<span id="line127"></span>						</span><span>&lt;<span class="start-tag">h1</span> <span class="attribute-name">class</span>="<a class="attribute-value">site-title</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/">http://plugin-test.localhost/</a>"&gt;</span><span>Plugin Test</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">h1</span>&gt;</span><span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">site-description</a>"&gt;</span><span>Just another WordPress site</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .site-description --&gt;</span><span>
<span id="line128"></span>					</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .header-titles --&gt;</span><span>
<span id="line129"></span>
<span id="line130"></span>					</span><span>&lt;<span class="start-tag">button</span> <span class="attribute-name">class</span>="<a class="attribute-value">toggle nav-toggle mobile-nav-toggle</a>" <span class="attribute-name">data-toggle-target</span>="<a class="attribute-value">.menu-modal</a>"  <span class="attribute-name">data-toggle-body-class</span>="<a class="attribute-value">showing-menu-modal</a>" <span class="attribute-name">aria-expanded</span>="<a class="attribute-value">false</a>" <span class="attribute-name">data-set-focus</span>="<a class="attribute-value">.close-nav-toggle</a>"&gt;</span><span>
<span id="line131"></span>						</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">toggle-inner</a>"&gt;</span><span>
<span id="line132"></span>							</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">toggle-icon</a>"&gt;</span><span>
<span id="line133"></span>								</span><span>&lt;<span class="start-tag">svg</span> <span class="attribute-name">class</span>="<a class="attribute-value">svg-icon</a>" <span class="attribute-name">aria-hidden</span>="<a class="attribute-value">true</a>" <span class="attribute-name">role</span>="<a class="attribute-value">img</a>" <span class="attribute-name">focusable</span>="<a class="attribute-value">false</a>" <span class="attribute-name">xmlns</span>="<a class="attribute-value">http://www.w3.org/2000/svg</a>" <span class="attribute-name">width</span>="<a class="attribute-value">26</a>" <span class="attribute-name">height</span>="<a class="attribute-value">7</a>" <span class="attribute-name">viewBox</span>="<a class="attribute-value">0 0 26 7</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">path</span> <span class="attribute-name">fill-rule</span>="<a class="attribute-value">evenodd</a>" <span class="attribute-name">d</span>="<a class="attribute-value">M332.5,45 C330.567003,45 329,43.4329966 329,41.5 C329,39.5670034 330.567003,38 332.5,38 C334.432997,38 336,39.5670034 336,41.5 C336,43.4329966 334.432997,45 332.5,45 Z M342,45 C340.067003,45 338.5,43.4329966 338.5,41.5 C338.5,39.5670034 340.067003,38 342,38 C343.932997,38 345.5,39.5670034 345.5,41.5 C345.5,43.4329966 343.932997,45 342,45 Z M351.5,45 C349.567003,45 348,43.4329966 348,41.5 C348,39.5670034 349.567003,38 351.5,38 C353.432997,38 355,39.5670034 355,41.5 C355,43.4329966 353.432997,45 351.5,45 Z</a>" <span class="attribute-name">transform</span>="<a class="attribute-value">translate(-329 -38)</a>" <span>/</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">svg</span>&gt;</span><span>							</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line134"></span>							</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">toggle-text</a>"&gt;</span><span>Menu</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line135"></span>						</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line136"></span>					</span><span>&lt;/<span class="end-tag">button</span>&gt;</span><span></span><span class="comment">&lt;!-- .nav-toggle --&gt;</span><span>
<span id="line137"></span>
<span id="line138"></span>				</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .header-titles-wrapper --&gt;</span><span>
<span id="line139"></span>
<span id="line140"></span>				</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">header-navigation-wrapper</a>"&gt;</span><span>
<span id="line141"></span>
<span id="line142"></span>					
<span id="line143"></span>							</span><span>&lt;<span class="start-tag">nav</span> <span class="attribute-name">class</span>="<a class="attribute-value">primary-menu-wrapper</a>" <span class="attribute-name">aria-label</span>="<a class="attribute-value">Horizontal</a>" <span class="attribute-name">role</span>="<a class="attribute-value">navigation</a>"&gt;</span><span>
<span id="line144"></span>
<span id="line145"></span>								</span><span>&lt;<span class="start-tag">ul</span> <span class="attribute-name">class</span>="<a class="attribute-value">primary-menu reset-list-style</a>"&gt;</span><span>
<span id="line146"></span>
<span id="line147"></span>								</span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">class</span>="<a class="attribute-value">page_item page-item-2</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/sample-page/">http://plugin-test.localhost/sample-page/</a>"&gt;</span><span>Sample Page</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line148"></span>
<span id="line149"></span>								</span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span>
<span id="line150"></span>
<span id="line151"></span>							</span><span>&lt;/<span class="end-tag">nav</span>&gt;</span><span></span><span class="comment">&lt;!-- .primary-menu-wrapper --&gt;</span><span>
<span id="line152"></span>
<span id="line153"></span>						
<span id="line154"></span>						</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">header-toggles hide-no-js</a>"&gt;</span><span>
<span id="line155"></span>
<span id="line156"></span>						
<span id="line157"></span>							</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">toggle-wrapper search-toggle-wrapper</a>"&gt;</span><span>
<span id="line158"></span>
<span id="line159"></span>								</span><span>&lt;<span class="start-tag">button</span> <span class="attribute-name">class</span>="<a class="attribute-value">toggle search-toggle desktop-search-toggle</a>" <span class="attribute-name">data-toggle-target</span>="<a class="attribute-value">.search-modal</a>" <span class="attribute-name">data-toggle-body-class</span>="<a class="attribute-value">showing-search-modal</a>" <span class="attribute-name">data-set-focus</span>="<a class="attribute-value">.search-modal .search-field</a>" <span class="attribute-name">aria-expanded</span>="<a class="attribute-value">false</a>"&gt;</span><span>
<span id="line160"></span>									</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">toggle-inner</a>"&gt;</span><span>
<span id="line161"></span>										</span><span>&lt;<span class="start-tag">svg</span> <span class="attribute-name">class</span>="<a class="attribute-value">svg-icon</a>" <span class="attribute-name">aria-hidden</span>="<a class="attribute-value">true</a>" <span class="attribute-name">role</span>="<a class="attribute-value">img</a>" <span class="attribute-name">focusable</span>="<a class="attribute-value">false</a>" <span class="attribute-name">xmlns</span>="<a class="attribute-value">http://www.w3.org/2000/svg</a>" <span class="attribute-name">width</span>="<a class="attribute-value">23</a>" <span class="attribute-name">height</span>="<a class="attribute-value">23</a>" <span class="attribute-name">viewBox</span>="<a class="attribute-value">0 0 23 23</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">path</span> <span class="attribute-name">d</span>="<a class="attribute-value">M38.710696,48.0601792 L43,52.3494831 L41.3494831,54 L37.0601792,49.710696 C35.2632422,51.1481185 32.9839107,52.0076499 30.5038249,52.0076499 C24.7027226,52.0076499 20,47.3049272 20,41.5038249 C20,35.7027226 24.7027226,31 30.5038249,31 C36.3049272,31 41.0076499,35.7027226 41.0076499,41.5038249 C41.0076499,43.9839107 40.1481185,46.2632422 38.710696,48.0601792 Z M36.3875844,47.1716785 C37.8030221,45.7026647 38.6734666,43.7048964 38.6734666,41.5038249 C38.6734666,36.9918565 35.0157934,33.3341833 30.5038249,33.3341833 C25.9918565,33.3341833 22.3341833,36.9918565 22.3341833,41.5038249 C22.3341833,46.0157934 25.9918565,49.6734666 30.5038249,49.6734666 C32.7048964,49.6734666 34.7026647,48.8030221 36.1716785,47.3875844 C36.2023931,47.347638 36.2360451,47.3092237 36.2726343,47.2726343 C36.3092237,47.2360451 36.347638,47.2023931 36.3875844,47.1716785 Z</a>" <span class="attribute-name">transform</span>="<a class="attribute-value">translate(-20 -31)</a>" <span>/</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">svg</span>&gt;</span><span>										</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">toggle-text</a>"&gt;</span><span>Search</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line162"></span>									</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line163"></span>								</span><span>&lt;/<span class="end-tag">button</span>&gt;</span><span></span><span class="comment">&lt;!-- .search-toggle --&gt;</span><span>
<span id="line164"></span>
<span id="line165"></span>							</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line166"></span>
<span id="line167"></span>							
<span id="line168"></span>						</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .header-toggles --&gt;</span><span>
<span id="line169"></span>						
<span id="line170"></span>				</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .header-navigation-wrapper --&gt;</span><span>
<span id="line171"></span>
<span id="line172"></span>			</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .header-inner --&gt;</span><span>
<span id="line173"></span>
<span id="line174"></span>			</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">search-modal cover-modal header-footer-group</a>" <span class="attribute-name">data-modal-target-string</span>="<a class="attribute-value">.search-modal</a>"&gt;</span><span>
<span id="line175"></span>
<span id="line176"></span>	</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">search-modal-inner modal-inner</a>"&gt;</span><span>
<span id="line177"></span>
<span id="line178"></span>		</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">section-inner</a>"&gt;</span><span>
<span id="line179"></span>
<span id="line180"></span>			</span><span>&lt;<span class="start-tag">form</span> <span class="attribute-name">role</span>="<a class="attribute-value">search</a>" <span class="attribute-name">aria-label</span>="<a class="attribute-value">Search for:</a>" <span class="attribute-name">method</span>="<a class="attribute-value">get</a>" <span class="attribute-name">class</span>="<a class="attribute-value">search-form</a>" <span class="attribute-name">action</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/">http://plugin-test.localhost/</a>"&gt;</span><span>
<span id="line181"></span>	</span><span>&lt;<span class="start-tag">label</span> <span class="attribute-name">for</span>="<a class="attribute-value">search-form-1</a>"&gt;</span><span>
<span id="line182"></span>		</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">screen-reader-text</a>"&gt;</span><span>Search for:</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line183"></span>		</span><span>&lt;<span class="start-tag">input</span> <span class="attribute-name">type</span>="<a class="attribute-value">search</a>" <span class="attribute-name">id</span>="<a class="attribute-value">search-form-1</a>" <span class="attribute-name">class</span>="<a class="attribute-value">search-field</a>" <span class="attribute-name">placeholder</span>="<a class="attribute-value">Search <span class="entity"><span>&amp;</span>hellip;</span></a>" <span class="attribute-name">value</span>="<a class="attribute-value"></a>" <span class="attribute-name">name</span>="<a class="attribute-value">s</a>" <span>/</span>&gt;</span><span>
<span id="line184"></span>	</span><span>&lt;/<span class="end-tag">label</span>&gt;</span><span>
<span id="line185"></span>	</span><span>&lt;<span class="start-tag">input</span> <span class="attribute-name">type</span>="<a class="attribute-value">submit</a>" <span class="attribute-name">class</span>="<a class="attribute-value">search-submit</a>" <span class="attribute-name">value</span>="<a class="attribute-value">Search</a>" <span>/</span>&gt;</span><span>
<span id="line186"></span></span><span>&lt;/<span class="end-tag">form</span>&gt;</span><span>
<span id="line187"></span>
<span id="line188"></span>			</span><span>&lt;<span class="start-tag">button</span> <span class="attribute-name">class</span>="<a class="attribute-value">toggle search-untoggle close-search-toggle fill-children-current-color</a>" <span class="attribute-name">data-toggle-target</span>="<a class="attribute-value">.search-modal</a>" <span class="attribute-name">data-toggle-body-class</span>="<a class="attribute-value">showing-search-modal</a>" <span class="attribute-name">data-set-focus</span>="<a class="attribute-value">.search-modal .search-field</a>" <span class="attribute-name">aria-expanded</span>="<a class="attribute-value">false</a>"&gt;</span><span>
<span id="line189"></span>				</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">screen-reader-text</a>"&gt;</span><span>Close search</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line190"></span>				</span><span>&lt;<span class="start-tag">svg</span> <span class="attribute-name">class</span>="<a class="attribute-value">svg-icon</a>" <span class="attribute-name">aria-hidden</span>="<a class="attribute-value">true</a>" <span class="attribute-name">role</span>="<a class="attribute-value">img</a>" <span class="attribute-name">focusable</span>="<a class="attribute-value">false</a>" <span class="attribute-name">xmlns</span>="<a class="attribute-value">http://www.w3.org/2000/svg</a>" <span class="attribute-name">width</span>="<a class="attribute-value">16</a>" <span class="attribute-name">height</span>="<a class="attribute-value">16</a>" <span class="attribute-name">viewBox</span>="<a class="attribute-value">0 0 16 16</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">polygon</span> <span class="attribute-name">fill</span>="<a class="attribute-value"></a>" <span class="attribute-name">fill-rule</span>="<a class="attribute-value">evenodd</a>" <span class="attribute-name">points</span>="<a class="attribute-value">6.852 7.649 .399 1.195 1.445 .149 7.899 6.602 14.352 .149 15.399 1.195 8.945 7.649 15.399 14.102 14.352 15.149 7.899 8.695 1.445 15.149 .399 14.102</a>" <span>/</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">svg</span>&gt;</span><span>			</span><span>&lt;/<span class="end-tag">button</span>&gt;</span><span></span><span class="comment">&lt;!-- .search-toggle --&gt;</span><span>
<span id="line191"></span>
<span id="line192"></span>		</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .section-inner --&gt;</span><span>
<span id="line193"></span>
<span id="line194"></span>	</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .search-modal-inner --&gt;</span><span>
<span id="line195"></span>
<span id="line196"></span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .menu-modal --&gt;</span><span>
<span id="line197"></span>
<span id="line198"></span>		</span><span>&lt;/<span class="end-tag">header</span>&gt;</span><span></span><span class="comment">&lt;!-- #site-header --&gt;</span><span>
<span id="line199"></span>
<span id="line200"></span>		
<span id="line201"></span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">menu-modal cover-modal header-footer-group</a>" <span class="attribute-name">data-modal-target-string</span>="<a class="attribute-value">.menu-modal</a>"&gt;</span><span>
<span id="line202"></span>
<span id="line203"></span>	</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">menu-modal-inner modal-inner</a>"&gt;</span><span>
<span id="line204"></span>
<span id="line205"></span>		</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">menu-wrapper section-inner</a>"&gt;</span><span>
<span id="line206"></span>
<span id="line207"></span>			</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">menu-top</a>"&gt;</span><span>
<span id="line208"></span>
<span id="line209"></span>				</span><span>&lt;<span class="start-tag">button</span> <span class="attribute-name">class</span>="<a class="attribute-value">toggle close-nav-toggle fill-children-current-color</a>" <span class="attribute-name">data-toggle-target</span>="<a class="attribute-value">.menu-modal</a>" <span class="attribute-name">data-toggle-body-class</span>="<a class="attribute-value">showing-menu-modal</a>" <span class="attribute-name">aria-expanded</span>="<a class="attribute-value">false</a>" <span class="attribute-name">data-set-focus</span>="<a class="attribute-value">.menu-modal</a>"&gt;</span><span>
<span id="line210"></span>					</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">toggle-text</a>"&gt;</span><span>Close Menu</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line211"></span>					</span><span>&lt;<span class="start-tag">svg</span> <span class="attribute-name">class</span>="<a class="attribute-value">svg-icon</a>" <span class="attribute-name">aria-hidden</span>="<a class="attribute-value">true</a>" <span class="attribute-name">role</span>="<a class="attribute-value">img</a>" <span class="attribute-name">focusable</span>="<a class="attribute-value">false</a>" <span class="attribute-name">xmlns</span>="<a class="attribute-value">http://www.w3.org/2000/svg</a>" <span class="attribute-name">width</span>="<a class="attribute-value">16</a>" <span class="attribute-name">height</span>="<a class="attribute-value">16</a>" <span class="attribute-name">viewBox</span>="<a class="attribute-value">0 0 16 16</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">polygon</span> <span class="attribute-name">fill</span>="<a class="attribute-value"></a>" <span class="attribute-name">fill-rule</span>="<a class="attribute-value">evenodd</a>" <span class="attribute-name">points</span>="<a class="attribute-value">6.852 7.649 .399 1.195 1.445 .149 7.899 6.602 14.352 .149 15.399 1.195 8.945 7.649 15.399 14.102 14.352 15.149 7.899 8.695 1.445 15.149 .399 14.102</a>" <span>/</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">svg</span>&gt;</span><span>				</span><span>&lt;/<span class="end-tag">button</span>&gt;</span><span></span><span class="comment">&lt;!-- .nav-toggle --&gt;</span><span>
<span id="line212"></span>
<span id="line213"></span>				
<span id="line214"></span>					</span><span>&lt;<span class="start-tag">nav</span> <span class="attribute-name">class</span>="<a class="attribute-value">mobile-menu</a>" <span class="attribute-name">aria-label</span>="<a class="attribute-value">Mobile</a>" <span class="attribute-name">role</span>="<a class="attribute-value">navigation</a>"&gt;</span><span>
<span id="line215"></span>
<span id="line216"></span>						</span><span>&lt;<span class="start-tag">ul</span> <span class="attribute-name">class</span>="<a class="attribute-value">modal-menu reset-list-style</a>"&gt;</span><span>
<span id="line217"></span>
<span id="line218"></span>						</span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">class</span>="<a class="attribute-value">page_item page-item-2</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">ancestor-wrapper</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/sample-page/">http://plugin-test.localhost/sample-page/</a>"&gt;</span><span>Sample Page</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .ancestor-wrapper --&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line219"></span>
<span id="line220"></span>						</span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span>
<span id="line221"></span>
<span id="line222"></span>					</span><span>&lt;/<span class="end-tag">nav</span>&gt;</span><span>
<span id="line223"></span>
<span id="line224"></span>					
<span id="line225"></span>			</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .menu-top --&gt;</span><span>
<span id="line226"></span>
<span id="line227"></span>			</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">menu-bottom</a>"&gt;</span><span>
<span id="line228"></span>
<span id="line229"></span>				
<span id="line230"></span>			</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .menu-bottom --&gt;</span><span>
<span id="line231"></span>
<span id="line232"></span>		</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .menu-wrapper --&gt;</span><span>
<span id="line233"></span>
<span id="line234"></span>	</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .menu-modal-inner --&gt;</span><span>
<span id="line235"></span>
<span id="line236"></span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .menu-modal --&gt;</span><span>
<span id="line237"></span>
<span id="line238"></span></span><span>&lt;<span class="start-tag">main</span> <span class="attribute-name">id</span>="<a class="attribute-value">site-content</a>" <span class="attribute-name">role</span>="<a class="attribute-value">main</a>"&gt;</span><span>
<span id="line239"></span>
<span id="line240"></span>	
<span id="line241"></span></span><span>&lt;<span class="start-tag">article</span> <span class="attribute-name">class</span>="<a class="attribute-value">post-1 post type-post status-publish format-standard hentry category-uncategorized</a>" <span class="attribute-name">id</span>="<a class="attribute-value">post-1</a>"&gt;</span><span>
<span id="line242"></span>
<span id="line243"></span>	
<span id="line244"></span></span><span>&lt;<span class="start-tag">header</span> <span class="attribute-name">class</span>="<a class="attribute-value">entry-header has-text-align-center</a>"&gt;</span><span>
<span id="line245"></span>
<span id="line246"></span>	</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">entry-header-inner section-inner medium</a>"&gt;</span><span>
<span id="line247"></span>
<span id="line248"></span>		
<span id="line249"></span>			</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">entry-categories</a>"&gt;</span><span>
<span id="line250"></span>				</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">screen-reader-text</a>"&gt;</span><span>Categories</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line251"></span>				</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">entry-categories-inner</a>"&gt;</span><span>
<span id="line252"></span>					</span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/category/uncategorized/">http://plugin-test.localhost/category/uncategorized/</a>" <span class="attribute-name">rel</span>="<a class="attribute-value">category tag</a>"&gt;</span><span>Uncategorized</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>				</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .entry-categories-inner --&gt;</span><span>
<span id="line253"></span>			</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .entry-categories --&gt;</span><span>
<span id="line254"></span>
<span id="line255"></span>			</span><span>&lt;<span class="start-tag">h2</span> <span class="attribute-name">class</span>="<a class="attribute-value">entry-title heading-size-1</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/2020/10/27/hello-world/">http://plugin-test.localhost/2020/10/27/hello-world/</a>"&gt;</span><span>Hello world!</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">h2</span>&gt;</span><span>
<span id="line256"></span>		</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">post-meta-wrapper post-meta-single post-meta-single-top</a>"&gt;</span><span>
<span id="line257"></span>
<span id="line258"></span>			</span><span>&lt;<span class="start-tag">ul</span> <span class="attribute-name">class</span>="<a class="attribute-value">post-meta</a>"&gt;</span><span>
<span id="line259"></span>
<span id="line260"></span>									</span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">class</span>="<a class="attribute-value">post-author meta-wrapper</a>"&gt;</span><span>
<span id="line261"></span>						</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">meta-icon</a>"&gt;</span><span>
<span id="line262"></span>							</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">screen-reader-text</a>"&gt;</span><span>Post author</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line263"></span>							</span><span>&lt;<span class="start-tag">svg</span> <span class="attribute-name">class</span>="<a class="attribute-value">svg-icon</a>" <span class="attribute-name">aria-hidden</span>="<a class="attribute-value">true</a>" <span class="attribute-name">role</span>="<a class="attribute-value">img</a>" <span class="attribute-name">focusable</span>="<a class="attribute-value">false</a>" <span class="attribute-name">xmlns</span>="<a class="attribute-value">http://www.w3.org/2000/svg</a>" <span class="attribute-name">width</span>="<a class="attribute-value">18</a>" <span class="attribute-name">height</span>="<a class="attribute-value">20</a>" <span class="attribute-name">viewBox</span>="<a class="attribute-value">0 0 18 20</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">path</span> <span class="attribute-name">fill</span>="<a class="attribute-value"></a>" <span class="attribute-name">d</span>="<a class="attribute-value">M18,19 C18,19.5522847 17.5522847,20 17,20 C16.4477153,20 16,19.5522847 16,19 L16,17 C16,15.3431458 14.6568542,14 13,14 L5,14 C3.34314575,14 2,15.3431458 2,17 L2,19 C2,19.5522847 1.55228475,20 1,20 C0.44771525,20 0,19.5522847 0,19 L0,17 C0,14.2385763 2.23857625,12 5,12 L13,12 C15.7614237,12 18,14.2385763 18,17 L18,19 Z M9,10 C6.23857625,10 4,7.76142375 4,5 C4,2.23857625 6.23857625,0 9,0 C11.7614237,0 14,2.23857625 14,5 C14,7.76142375 11.7614237,10 9,10 Z M9,8 C10.6568542,8 12,6.65685425 12,5 C12,3.34314575 10.6568542,2 9,2 C7.34314575,2 6,3.34314575 6,5 C6,6.65685425 7.34314575,8 9,8 Z</a>" <span>/</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">svg</span>&gt;</span><span>						</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line264"></span>						</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">meta-text</a>"&gt;</span><span>
<span id="line265"></span>							By </span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/author/admin/">http://plugin-test.localhost/author/admin/</a>"&gt;</span><span>admin</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>						</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line266"></span>					</span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line267"></span>										</span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">class</span>="<a class="attribute-value">post-date meta-wrapper</a>"&gt;</span><span>
<span id="line268"></span>						</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">meta-icon</a>"&gt;</span><span>
<span id="line269"></span>							</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">screen-reader-text</a>"&gt;</span><span>Post date</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line270"></span>							</span><span>&lt;<span class="start-tag">svg</span> <span class="attribute-name">class</span>="<a class="attribute-value">svg-icon</a>" <span class="attribute-name">aria-hidden</span>="<a class="attribute-value">true</a>" <span class="attribute-name">role</span>="<a class="attribute-value">img</a>" <span class="attribute-name">focusable</span>="<a class="attribute-value">false</a>" <span class="attribute-name">xmlns</span>="<a class="attribute-value">http://www.w3.org/2000/svg</a>" <span class="attribute-name">width</span>="<a class="attribute-value">18</a>" <span class="attribute-name">height</span>="<a class="attribute-value">19</a>" <span class="attribute-name">viewBox</span>="<a class="attribute-value">0 0 18 19</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">path</span> <span class="attribute-name">fill</span>="<a class="attribute-value"></a>" <span class="attribute-name">d</span>="<a class="attribute-value">M4.60069444,4.09375 L3.25,4.09375 C2.47334957,4.09375 1.84375,4.72334957 1.84375,5.5 L1.84375,7.26736111 L16.15625,7.26736111 L16.15625,5.5 C16.15625,4.72334957 15.5266504,4.09375 14.75,4.09375 L13.3993056,4.09375 L13.3993056,4.55555556 C13.3993056,5.02154581 13.0215458,5.39930556 12.5555556,5.39930556 C12.0895653,5.39930556 11.7118056,5.02154581 11.7118056,4.55555556 L11.7118056,4.09375 L6.28819444,4.09375 L6.28819444,4.55555556 C6.28819444,5.02154581 5.9104347,5.39930556 5.44444444,5.39930556 C4.97845419,5.39930556 4.60069444,5.02154581 4.60069444,4.55555556 L4.60069444,4.09375 Z M6.28819444,2.40625 L11.7118056,2.40625 L11.7118056,1 C11.7118056,0.534009742 12.0895653,0.15625 12.5555556,0.15625 C13.0215458,0.15625 13.3993056,0.534009742 13.3993056,1 L13.3993056,2.40625 L14.75,2.40625 C16.4586309,2.40625 17.84375,3.79136906 17.84375,5.5 L17.84375,15.875 C17.84375,17.5836309 16.4586309,18.96875 14.75,18.96875 L3.25,18.96875 C1.54136906,18.96875 0.15625,17.5836309 0.15625,15.875 L0.15625,5.5 C0.15625,3.79136906 1.54136906,2.40625 3.25,2.40625 L4.60069444,2.40625 L4.60069444,1 C4.60069444,0.534009742 4.97845419,0.15625 5.44444444,0.15625 C5.9104347,0.15625 6.28819444,0.534009742 6.28819444,1 L6.28819444,2.40625 Z M1.84375,8.95486111 L1.84375,15.875 C1.84375,16.6516504 2.47334957,17.28125 3.25,17.28125 L14.75,17.28125 C15.5266504,17.28125 16.15625,16.6516504 16.15625,15.875 L16.15625,8.95486111 L1.84375,8.95486111 Z</a>" <span>/</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">svg</span>&gt;</span><span>						</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line271"></span>						</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">meta-text</a>"&gt;</span><span>
<span id="line272"></span>							</span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/2020/10/27/hello-world/">http://plugin-test.localhost/2020/10/27/hello-world/</a>"&gt;</span><span>October 27, 2020</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>
<span id="line273"></span>						</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line274"></span>					</span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line275"></span>										</span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">class</span>="<a class="attribute-value">post-comment-link meta-wrapper</a>"&gt;</span><span>
<span id="line276"></span>						</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">meta-icon</a>"&gt;</span><span>
<span id="line277"></span>							</span><span>&lt;<span class="start-tag">svg</span> <span class="attribute-name">class</span>="<a class="attribute-value">svg-icon</a>" <span class="attribute-name">aria-hidden</span>="<a class="attribute-value">true</a>" <span class="attribute-name">role</span>="<a class="attribute-value">img</a>" <span class="attribute-name">focusable</span>="<a class="attribute-value">false</a>" <span class="attribute-name">xmlns</span>="<a class="attribute-value">http://www.w3.org/2000/svg</a>" <span class="attribute-name">width</span>="<a class="attribute-value">19</a>" <span class="attribute-name">height</span>="<a class="attribute-value">19</a>" <span class="attribute-name">viewBox</span>="<a class="attribute-value">0 0 19 19</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">path</span> <span class="attribute-name">d</span>="<a class="attribute-value">M9.43016863,13.2235931 C9.58624731,13.094699 9.7823475,13.0241935 9.98476849,13.0241935 L15.0564516,13.0241935 C15.8581553,13.0241935 16.5080645,12.3742843 16.5080645,11.5725806 L16.5080645,3.44354839 C16.5080645,2.64184472 15.8581553,1.99193548 15.0564516,1.99193548 L3.44354839,1.99193548 C2.64184472,1.99193548 1.99193548,2.64184472 1.99193548,3.44354839 L1.99193548,11.5725806 C1.99193548,12.3742843 2.64184472,13.0241935 3.44354839,13.0241935 L5.76612903,13.0241935 C6.24715123,13.0241935 6.63709677,13.4141391 6.63709677,13.8951613 L6.63709677,15.5301903 L9.43016863,13.2235931 Z M3.44354839,14.766129 C1.67980032,14.766129 0.25,13.3363287 0.25,11.5725806 L0.25,3.44354839 C0.25,1.67980032 1.67980032,0.25 3.44354839,0.25 L15.0564516,0.25 C16.8201997,0.25 18.25,1.67980032 18.25,3.44354839 L18.25,11.5725806 C18.25,13.3363287 16.8201997,14.766129 15.0564516,14.766129 L10.2979143,14.766129 L6.32072889,18.0506004 C5.75274472,18.5196577 4.89516129,18.1156602 4.89516129,17.3790323 L4.89516129,14.766129 L3.44354839,14.766129 Z</a>" <span>/</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">svg</span>&gt;</span><span>						</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line278"></span>						</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">meta-text</a>"&gt;</span><span>
<span id="line279"></span>							</span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/2020/10/27/hello-world/#comments">http://plugin-test.localhost/2020/10/27/hello-world/#comments</a>"&gt;</span><span>1 Comment</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">screen-reader-text</a>"&gt;</span><span> on Hello world!</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>						</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line280"></span>					</span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line281"></span>					
<span id="line282"></span>			</span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span></span><span class="comment">&lt;!-- .post-meta --&gt;</span><span>
<span id="line283"></span>
<span id="line284"></span>		</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .post-meta-wrapper --&gt;</span><span>
<span id="line285"></span>
<span id="line286"></span>		
<span id="line287"></span>	</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .entry-header-inner --&gt;</span><span>
<span id="line288"></span>
<span id="line289"></span></span><span>&lt;/<span class="end-tag">header</span>&gt;</span><span></span><span class="comment">&lt;!-- .entry-header --&gt;</span><span>
<span id="line290"></span>
<span id="line291"></span>	</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">post-inner thin </a>"&gt;</span><span>
<span id="line292"></span>
<span id="line293"></span>		</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">entry-content</a>"&gt;</span><span>
<span id="line294"></span>
<span id="line295"></span>			
<span id="line296"></span></span><span>&lt;<span class="start-tag">p</span>&gt;</span><span>Welcome to WordPress. This is your first post. Edit or delete it, then start writing!</span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span>
<span id="line297"></span>
<span id="line298"></span>		</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .entry-content --&gt;</span><span>
<span id="line299"></span>
<span id="line300"></span>	</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .post-inner --&gt;</span><span>
<span id="line301"></span>
<span id="line302"></span>	</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">section-inner</a>"&gt;</span><span>
<span id="line303"></span>		</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">post-meta-wrapper post-meta-edit-link-wrapper</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">ul</span> <span class="attribute-name">class</span>="<a class="attribute-value">post-meta</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">class</span>="<a class="attribute-value">post-edit meta-wrapper</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">meta-icon</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">svg</span> <span class="attribute-name">class</span>="<a class="attribute-value">svg-icon</a>" <span class="attribute-name">aria-hidden</span>="<a class="attribute-value">true</a>" <span class="attribute-name">role</span>="<a class="attribute-value">img</a>" <span class="attribute-name">focusable</span>="<a class="attribute-value">false</a>" <span class="attribute-name">xmlns</span>="<a class="attribute-value">http://www.w3.org/2000/svg</a>" <span class="attribute-name">width</span>="<a class="attribute-value">18</a>" <span class="attribute-name">height</span>="<a class="attribute-value">18</a>" <span class="attribute-name">viewBox</span>="<a class="attribute-value">0 0 18 18</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">path</span> <span class="attribute-name">fill</span>="<a class="attribute-value"></a>" <span class="attribute-name">d</span>="<a class="attribute-value">M14.7272727,11.1763636 C14.7272727,10.7244943 15.0935852,10.3581818 15.5454545,10.3581818 C15.9973239,10.3581818 16.3636364,10.7244943 16.3636364,11.1763636 L16.3636364,15.5454545 C16.3636364,16.9010626 15.2646989,18 13.9090909,18 L2.45454545,18 C1.09893743,18 0,16.9010626 0,15.5454545 L0,4.09090909 C0,2.73530107 1.09893743,1.63636364 2.45454545,1.63636364 L6.82363636,1.63636364 C7.2755057,1.63636364 7.64181818,2.00267611 7.64181818,2.45454545 C7.64181818,2.9064148 7.2755057,3.27272727 6.82363636,3.27272727 L2.45454545,3.27272727 C2.00267611,3.27272727 1.63636364,3.63903975 1.63636364,4.09090909 L1.63636364,15.5454545 C1.63636364,15.9973239 2.00267611,16.3636364 2.45454545,16.3636364 L13.9090909,16.3636364 C14.3609602,16.3636364 14.7272727,15.9973239 14.7272727,15.5454545 L14.7272727,11.1763636 Z M6.54545455,9.33890201 L6.54545455,11.4545455 L8.66109799,11.4545455 L16.0247344,4.09090909 L13.9090909,1.97526564 L6.54545455,9.33890201 Z M14.4876328,0.239639906 L17.7603601,3.51236718 C18.07988,3.83188705 18.07988,4.34993113 17.7603601,4.669451 L9.57854191,12.8512692 C9.42510306,13.004708 9.21699531,13.0909091 9,13.0909091 L5.72727273,13.0909091 C5.27540339,13.0909091 4.90909091,12.7245966 4.90909091,12.2727273 L4.90909091,9 C4.90909091,8.78300469 4.99529196,8.57489694 5.14873082,8.42145809 L13.330549,0.239639906 C13.6500689,-0.0798799688 14.1681129,-0.0798799688 14.4876328,0.239639906 Z</a>" <span>/</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">svg</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">meta-text</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/post.php?post=1&amp;action=edit">http://plugin-test.localhost/wp-admin/post.php?post=1<span class="entity"><span>&amp;</span>#038;</span>action=edit</a>"&gt;</span><span>Edit </span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">screen-reader-text</a>"&gt;</span><span>Hello world!</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span></span><span class="comment">&lt;!-- .post-meta --&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .post-meta-wrapper --&gt;</span><span>
<span id="line304"></span>	</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .section-inner --&gt;</span><span>
<span id="line305"></span>
<span id="line306"></span>	
<span id="line307"></span></span><span>&lt;/<span class="end-tag">article</span>&gt;</span><span></span><span class="comment">&lt;!-- .post --&gt;</span><span>
<span id="line308"></span>
<span id="line309"></span>	
<span id="line310"></span></span><span>&lt;/<span class="end-tag">main</span>&gt;</span><span></span><span class="comment">&lt;!-- #site-content --&gt;</span><span>
<span id="line311"></span>
<span id="line312"></span>
<span id="line313"></span>	</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">footer-nav-widgets-wrapper header-footer-group</a>"&gt;</span><span>
<span id="line314"></span>
<span id="line315"></span>		</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">footer-inner section-inner</a>"&gt;</span><span>
<span id="line316"></span>
<span id="line317"></span>			
<span id="line318"></span>			
<span id="line319"></span>				</span><span>&lt;<span class="start-tag">aside</span> <span class="attribute-name">class</span>="<a class="attribute-value">footer-widgets-outer-wrapper</a>" <span class="attribute-name">role</span>="<a class="attribute-value">complementary</a>"&gt;</span><span>
<span id="line320"></span>
<span id="line321"></span>					</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">footer-widgets-wrapper</a>"&gt;</span><span>
<span id="line322"></span>
<span id="line323"></span>						
<span id="line324"></span>							</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">footer-widgets column-one grid-item</a>"&gt;</span><span>
<span id="line325"></span>								</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">widget widget_search</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">widget-content</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">form</span> <span class="attribute-name">role</span>="<a class="attribute-value">search</a>"  <span class="attribute-name">method</span>="<a class="attribute-value">get</a>" <span class="attribute-name">class</span>="<a class="attribute-value">search-form</a>" <span class="attribute-name">action</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/">http://plugin-test.localhost/</a>"&gt;</span><span>
<span id="line326"></span>	</span><span>&lt;<span class="start-tag">label</span> <span class="attribute-name">for</span>="<a class="attribute-value">search-form-2</a>"&gt;</span><span>
<span id="line327"></span>		</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">screen-reader-text</a>"&gt;</span><span>Search for:</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line328"></span>		</span><span>&lt;<span class="start-tag">input</span> <span class="attribute-name">type</span>="<a class="attribute-value">search</a>" <span class="attribute-name">id</span>="<a class="attribute-value">search-form-2</a>" <span class="attribute-name">class</span>="<a class="attribute-value">search-field</a>" <span class="attribute-name">placeholder</span>="<a class="attribute-value">Search <span class="entity"><span>&amp;</span>hellip;</span></a>" <span class="attribute-name">value</span>="<a class="attribute-value"></a>" <span class="attribute-name">name</span>="<a class="attribute-value">s</a>" <span>/</span>&gt;</span><span>
<span id="line329"></span>	</span><span>&lt;/<span class="end-tag">label</span>&gt;</span><span>
<span id="line330"></span>	</span><span>&lt;<span class="start-tag">input</span> <span class="attribute-name">type</span>="<a class="attribute-value">submit</a>" <span class="attribute-name">class</span>="<a class="attribute-value">search-submit</a>" <span class="attribute-name">value</span>="<a class="attribute-value">Search</a>" <span>/</span>&gt;</span><span>
<span id="line331"></span></span><span>&lt;/<span class="end-tag">form</span>&gt;</span><span>
<span id="line332"></span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line333"></span>		</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">widget widget_recent_entries</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">widget-content</a>"&gt;</span><span>
<span id="line334"></span>		</span><span>&lt;<span class="start-tag">h2</span> <span class="attribute-name">class</span>="<a class="attribute-value">widget-title subheading heading-size-3</a>"&gt;</span><span>Recent Posts</span><span>&lt;/<span class="end-tag">h2</span>&gt;</span><span>
<span id="line335"></span>		</span><span>&lt;<span class="start-tag">ul</span>&gt;</span><span>
<span id="line336"></span>											</span><span>&lt;<span class="start-tag">li</span>&gt;</span><span>
<span id="line337"></span>					</span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/2020/10/27/hello-world/">http://plugin-test.localhost/2020/10/27/hello-world/</a>"&gt;</span><span>Hello world!</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>
<span id="line338"></span>									</span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line339"></span>					</span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span>
<span id="line340"></span>
<span id="line341"></span>		</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">widget widget_recent_comments</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">widget-content</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">h2</span> <span class="attribute-name">class</span>="<a class="attribute-value">widget-title subheading heading-size-3</a>"&gt;</span><span>Recent Comments</span><span>&lt;/<span class="end-tag">h2</span>&gt;</span><span></span><span>&lt;<span class="start-tag">ul</span> <span class="attribute-name">id</span>="<a class="attribute-value">recentcomments</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">class</span>="<a class="attribute-value">recentcomments</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">comment-author-link</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:https://wordpress.org/">https://wordpress.org/</a>' <span class="attribute-name">rel</span>='<a class="attribute-value">external nofollow ugc</a>' <span class="attribute-name">class</span>='<a class="attribute-value">url</a>'&gt;</span><span>A WordPress Commenter</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span> on </span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/2020/10/27/hello-world/#comment-1">http://plugin-test.localhost/2020/10/27/hello-world/#comment-1</a>"&gt;</span><span>Hello world!</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>							</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line342"></span>
<span id="line343"></span>						
<span id="line344"></span>						
<span id="line345"></span>							</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">footer-widgets column-two grid-item</a>"&gt;</span><span>
<span id="line346"></span>								</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">widget widget_archive</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">widget-content</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">h2</span> <span class="attribute-name">class</span>="<a class="attribute-value">widget-title subheading heading-size-3</a>"&gt;</span><span>Archives</span><span>&lt;/<span class="end-tag">h2</span>&gt;</span><span>
<span id="line347"></span>			</span><span>&lt;<span class="start-tag">ul</span>&gt;</span><span>
<span id="line348"></span>					</span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/2020/10/">http://plugin-test.localhost/2020/10/</a>'&gt;</span><span>October 2020</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line349"></span>			</span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span>
<span id="line350"></span>
<span id="line351"></span>			</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">widget widget_categories</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">widget-content</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">h2</span> <span class="attribute-name">class</span>="<a class="attribute-value">widget-title subheading heading-size-3</a>"&gt;</span><span>Categories</span><span>&lt;/<span class="end-tag">h2</span>&gt;</span><span>
<span id="line352"></span>			</span><span>&lt;<span class="start-tag">ul</span>&gt;</span><span>
<span id="line353"></span>					</span><span>&lt;<span class="start-tag">li</span> <span class="attribute-name">class</span>="<a class="attribute-value">cat-item cat-item-1</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/category/uncategorized/">http://plugin-test.localhost/category/uncategorized/</a>"&gt;</span><span>Uncategorized</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>
<span id="line354"></span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line355"></span>			</span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span>
<span id="line356"></span>
<span id="line357"></span>			</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">widget widget_meta</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">widget-content</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">h2</span> <span class="attribute-name">class</span>="<a class="attribute-value">widget-title subheading heading-size-3</a>"&gt;</span><span>Meta</span><span>&lt;/<span class="end-tag">h2</span>&gt;</span><span>
<span id="line358"></span>		</span><span>&lt;<span class="start-tag">ul</span>&gt;</span><span>
<span id="line359"></span>			</span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-admin/">http://plugin-test.localhost/wp-admin/</a>"&gt;</span><span>Site Admin</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>			</span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-login.php?action=logout&amp;_wpnonce=2c655d3f1a">http://plugin-test.localhost/wp-login.php?action=logout<span class="entity"><span>&amp;</span>#038;</span>_wpnonce=2c655d3f1a</a>"&gt;</span><span>Log out</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line360"></span>			</span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/feed/">http://plugin-test.localhost/feed/</a>"&gt;</span><span>Entries feed</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line361"></span>			</span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/comments/feed/">http://plugin-test.localhost/comments/feed/</a>"&gt;</span><span>Comments feed</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line362"></span>
<span id="line363"></span>			</span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:https://wordpress.org/">https://wordpress.org/</a>"&gt;</span><span>WordPress.org</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line364"></span>		</span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span>
<span id="line365"></span>
<span id="line366"></span>		</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>							</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line367"></span>
<span id="line368"></span>						
<span id="line369"></span>					</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .footer-widgets-wrapper --&gt;</span><span>
<span id="line370"></span>
<span id="line371"></span>				</span><span>&lt;/<span class="end-tag">aside</span>&gt;</span><span></span><span class="comment">&lt;!-- .footer-widgets-outer-wrapper --&gt;</span><span>
<span id="line372"></span>
<span id="line373"></span>			
<span id="line374"></span>		</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .footer-inner --&gt;</span><span>
<span id="line375"></span>
<span id="line376"></span>	</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .footer-nav-widgets-wrapper --&gt;</span><span>
<span id="line377"></span>
<span id="line378"></span>
<span id="line379"></span>			</span><span>&lt;<span class="start-tag">footer</span> <span class="attribute-name">id</span>="<a class="attribute-value">site-footer</a>" <span class="attribute-name">role</span>="<a class="attribute-value">contentinfo</a>" <span class="attribute-name">class</span>="<a class="attribute-value">header-footer-group</a>"&gt;</span><span>
<span id="line380"></span>
<span id="line381"></span>				</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">section-inner</a>"&gt;</span><span>
<span id="line382"></span>
<span id="line383"></span>					</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">footer-credits</a>"&gt;</span><span>
<span id="line384"></span>
<span id="line385"></span>						</span><span>&lt;<span class="start-tag">p</span> <span class="attribute-name">class</span>="<a class="attribute-value">footer-copyright</a>"&gt;</span><span><span class="entity"><span>&amp;</span>copy;</span>
<span id="line386"></span>							2020							</span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/">http://plugin-test.localhost/</a>"&gt;</span><span>Plugin Test</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>
<span id="line387"></span>						</span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span></span><span class="comment">&lt;!-- .footer-copyright --&gt;</span><span>
<span id="line388"></span>
<span id="line389"></span>						</span><span>&lt;<span class="start-tag">p</span> <span class="attribute-name">class</span>="<a class="attribute-value">powered-by-wordpress</a>"&gt;</span><span>
<span id="line390"></span>							</span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:https://wordpress.org/">https://wordpress.org/</a>"&gt;</span><span>
<span id="line391"></span>								Powered by WordPress							</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>
<span id="line392"></span>						</span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span></span><span class="comment">&lt;!-- .powered-by-wordpress --&gt;</span><span>
<span id="line393"></span>
<span id="line394"></span>					</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .footer-credits --&gt;</span><span>
<span id="line395"></span>
<span id="line396"></span>					</span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>="<a class="attribute-value">to-the-top</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://plugin-test.localhost/#site-header">#site-header</a>"&gt;</span><span>
<span id="line397"></span>						</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">to-the-top-long</a>"&gt;</span><span>
<span id="line398"></span>							To the top </span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">arrow</a>" <span class="attribute-name">aria-hidden</span>="<a class="attribute-value">true</a>"&gt;</span><span><span class="entity"><span>&amp;</span>uarr;</span></span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>						</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span class="comment">&lt;!-- .to-the-top-long --&gt;</span><span>
<span id="line399"></span>						</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">to-the-top-short</a>"&gt;</span><span>
<span id="line400"></span>							Up </span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">arrow</a>" <span class="attribute-name">aria-hidden</span>="<a class="attribute-value">true</a>"&gt;</span><span><span class="entity"><span>&amp;</span>uarr;</span></span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>						</span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span></span><span class="comment">&lt;!-- .to-the-top-short --&gt;</span><span>
<span id="line401"></span>					</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span class="comment">&lt;!-- .to-the-top --&gt;</span><span>
<span id="line402"></span>
<span id="line403"></span>				</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span class="comment">&lt;!-- .section-inner --&gt;</span><span>
<span id="line404"></span>
<span id="line405"></span>			</span><span>&lt;/<span class="end-tag">footer</span>&gt;</span><span></span><span class="comment">&lt;!-- #site-footer --&gt;</span><span>
<span id="line406"></span>
<span id="line407"></span>		</span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">src</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-includes/js/hoverintent-js.min.js?ver=2.2.1">http://plugin-test.localhost/wp-includes/js/hoverintent-js.min.js?ver=2.2.1</a>' <span class="attribute-name">id</span>='<a class="attribute-value">hoverintent-js-js</a>'&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line408"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">src</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-includes/js/admin-bar.min.js?ver=5.5.3">http://plugin-test.localhost/wp-includes/js/admin-bar.min.js?ver=5.5.3</a>' <span class="attribute-name">id</span>='<a class="attribute-value">admin-bar-js</a>'&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line409"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">src</span>='<a class="attribute-value" href="view-source:http://plugin-test.localhost/wp-includes/js/wp-embed.min.js?ver=5.5.3">http://plugin-test.localhost/wp-includes/js/wp-embed.min.js?ver=5.5.3</a>' <span class="attribute-name">id</span>='<a class="attribute-value">wp-embed-js</a>'&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line410"></span>	</span><span>&lt;<span class="start-tag">script</span>&gt;</span><span>
<span id="line411"></span>	/(trident|msie)/i.test(navigator.userAgent)&amp;&amp;document.getElementById&amp;&amp;window.addEventListener&amp;&amp;window.addEventListener("hashchange",function(){var t,e=location.hash.substring(1);/^[A-z0-9_-]+$/.test(e)&amp;&amp;(t=document.getElementById(e))&amp;&amp;(/^(?:a|select|input|button|textarea)$/i.test(t.tagName)||(t.tabIndex=-1),t.focus())},!1);
<span id="line412"></span>	</span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line413"></span>	
<span id="line414"></span>	</span><span>&lt;/<span class="end-tag">body</span>&gt;</span><span>
<span id="line415"></span></span><span>&lt;/<span class="end-tag">html</span>&gt;</span><span>
<span id="line416"></span></span></pre>
```
</details>

<details>
  <summary>Received plain text:</summary>
  
```
<!DOCTYPE html>

<html class="no-js" lang="en-US">

	<head>

		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0" >

		<link rel="profile" href="https://gmpg.org/xfn/11">

		<title>Plugin Test &#8211; Just another WordPress site</title>
<link rel='dns-prefetch' href='//s.w.org' />
<link rel="alternate" type="application/rss+xml" title="Plugin Test &raquo; Feed" href="http://plugin-test.localhost/feed/" />
<link rel="alternate" type="application/rss+xml" title="Plugin Test &raquo; Comments Feed" href="http://plugin-test.localhost/comments/feed/" />
		<script>
			window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/13.0.0\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/13.0.0\/svg\/","svgExt":".svg","source":{"concatemoji":"http:\/\/plugin-test.localhost\/wp-includes\/js\/wp-emoji-release.min.js?ver=5.5.3"}};
			!function(e,a,t){var r,n,o,i,p=a.createElement("canvas"),s=p.getContext&&p.getContext("2d");function c(e,t){var a=String.fromCharCode;s.clearRect(0,0,p.width,p.height),s.fillText(a.apply(this,e),0,0);var r=p.toDataURL();return s.clearRect(0,0,p.width,p.height),s.fillText(a.apply(this,t),0,0),r===p.toDataURL()}function l(e){if(!s||!s.fillText)return!1;switch(s.textBaseline="top",s.font="600 32px Arial",e){case"flag":return!c([127987,65039,8205,9895,65039],[127987,65039,8203,9895,65039])&&(!c([55356,56826,55356,56819],[55356,56826,8203,55356,56819])&&!c([55356,57332,56128,56423,56128,56418,56128,56421,56128,56430,56128,56423,56128,56447],[55356,57332,8203,56128,56423,8203,56128,56418,8203,56128,56421,8203,56128,56430,8203,56128,56423,8203,56128,56447]));case"emoji":return!c([55357,56424,8205,55356,57212],[55357,56424,8203,55356,57212])}return!1}function d(e){var t=a.createElement("script");t.src=e,t.defer=t.type="text/javascript",a.getElementsByTagName("head")[0].appendChild(t)}for(i=Array("flag","emoji"),t.supports={everything:!0,everythingExceptFlag:!0},o=0;o<i.length;o++)t.supports[i[o]]=l(i[o]),t.supports.everything=t.supports.everything&&t.supports[i[o]],"flag"!==i[o]&&(t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&t.supports[i[o]]);t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&!t.supports.flag,t.DOMReady=!1,t.readyCallback=function(){t.DOMReady=!0},t.supports.everything||(n=function(){t.readyCallback()},a.addEventListener?(a.addEventListener("DOMContentLoaded",n,!1),e.addEventListener("load",n,!1)):(e.attachEvent("onload",n),a.attachEvent("onreadystatechange",function(){"complete"===a.readyState&&t.readyCallback()})),(r=t.source||{}).concatemoji?d(r.concatemoji):r.wpemoji&&r.twemoji&&(d(r.twemoji),d(r.wpemoji)))}(window,document,window._wpemojiSettings);
		</script>
		<style>
img.wp-smiley,
img.emoji {
	display: inline !important;
	border: none !important;
	box-shadow: none !important;
	height: 1em !important;
	width: 1em !important;
	margin: 0 .07em !important;
	vertical-align: -0.1em !important;
	background: none !important;
	padding: 0 !important;
}
</style>
	<link rel='stylesheet' id='dashicons-css'  href='http://plugin-test.localhost/wp-includes/css/dashicons.min.css?ver=5.5.3' media='all' />
<link rel='stylesheet' id='admin-bar-css'  href='http://plugin-test.localhost/wp-includes/css/admin-bar.min.css?ver=5.5.3' media='all' />
<link rel='stylesheet' id='wp-block-library-css'  href='http://plugin-test.localhost/wp-content/plugins/gutenberg/build/block-library/style.css?ver=1604325854' media='all' />
<style id='global-styles-inline-css'>
:root{--wp--preset--color--accent:#cd2653;--wp--preset--color--primary:#000000;--wp--preset--color--secondary:#6d6d6d;--wp--preset--color--subtle-background:#dcd7ca;--wp--preset--color--background:#f5efe0;--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple:linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%);--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan:linear-gradient(135deg,rgb(122,220,180) 0%,rgb(0,208,130) 100%);--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange:linear-gradient(135deg,rgba(252,185,0,1) 0%,rgba(255,105,0,1) 100%);--wp--preset--gradient--luminous-vivid-orange-to-vivid-red:linear-gradient(135deg,rgba(255,105,0,1) 0%,rgb(207,46,46) 100%);--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray:linear-gradient(135deg,rgb(238,238,238) 0%,rgb(169,184,195) 100%);--wp--preset--gradient--cool-to-warm-spectrum:linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%);--wp--preset--gradient--blush-light-purple:linear-gradient(135deg,rgb(255,206,236) 0%,rgb(152,150,240) 100%);--wp--preset--gradient--blush-bordeaux:linear-gradient(135deg,rgb(254,205,165) 0%,rgb(254,45,45) 50%,rgb(107,0,62) 100%);--wp--preset--gradient--luminous-dusk:linear-gradient(135deg,rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);--wp--preset--gradient--pale-ocean:linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);--wp--preset--gradient--electric-grass:linear-gradient(135deg,rgb(202,248,128) 0%,rgb(113,206,126) 100%);--wp--preset--gradient--midnight:linear-gradient(135deg,rgb(2,3,129) 0%,rgb(40,116,252) 100%);--wp--preset--font-size--small:18px;--wp--preset--font-size--normal:21px;--wp--preset--font-size--large:26.25px;--wp--preset--font-size--larger:32px;}.has-accent-color{color:#cd2653;}
.has-primary-color{color:#000000;}
.has-secondary-color{color:#6d6d6d;}
.has-subtle-background-color{color:#dcd7ca;}
.has-background-color{color:#f5efe0;}
.has-accent-background-color{background-color:#cd2653;}
.has-primary-background-color{background-color:#000000;}
.has-secondary-background-color{background-color:#6d6d6d;}
.has-subtle-background-background-color{background-color:#dcd7ca;}
.has-background-background-color{background-color:#f5efe0;}
.has-vivid-cyan-blue-to-vivid-purple-gradient-background{background:linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%);}
.has-light-green-cyan-to-vivid-green-cyan-gradient-background{background:linear-gradient(135deg,rgb(122,220,180) 0%,rgb(0,208,130) 100%);}
.has-luminous-vivid-amber-to-luminous-vivid-orange-gradient-background{background:linear-gradient(135deg,rgba(252,185,0,1) 0%,rgba(255,105,0,1) 100%);}
.has-luminous-vivid-orange-to-vivid-red-gradient-background{background:linear-gradient(135deg,rgba(255,105,0,1) 0%,rgb(207,46,46) 100%);}
.has-very-light-gray-to-cyan-bluish-gray-gradient-background{background:linear-gradient(135deg,rgb(238,238,238) 0%,rgb(169,184,195) 100%);}
.has-cool-to-warm-spectrum-gradient-background{background:linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%);}
.has-blush-light-purple-gradient-background{background:linear-gradient(135deg,rgb(255,206,236) 0%,rgb(152,150,240) 100%);}
.has-blush-bordeaux-gradient-background{background:linear-gradient(135deg,rgb(254,205,165) 0%,rgb(254,45,45) 50%,rgb(107,0,62) 100%);}
.has-luminous-dusk-gradient-background{background:linear-gradient(135deg,rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);}
.has-pale-ocean-gradient-background{background:linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);}
.has-electric-grass-gradient-background{background:linear-gradient(135deg,rgb(202,248,128) 0%,rgb(113,206,126) 100%);}
.has-midnight-gradient-background{background:linear-gradient(135deg,rgb(2,3,129) 0%,rgb(40,116,252) 100%);}
.has-small-font-size{font-size:18px;}
.has-normal-font-size{font-size:21px;}
.has-large-font-size{font-size:26.25px;}
.has-larger-font-size{font-size:32px;}

</style>
<link rel='stylesheet' id='twentytwenty-style-css'  href='http://plugin-test.localhost/wp-content/themes/twentytwenty/style.css?ver=1.5' media='all' />
<style id='twentytwenty-style-inline-css'>
.color-accent,.color-accent-hover:hover,.color-accent-hover:focus,:root .has-accent-color,.has-drop-cap:not(:focus):first-letter,.wp-block-button.is-style-outline,a { color: #cd2653; }blockquote,.border-color-accent,.border-color-accent-hover:hover,.border-color-accent-hover:focus { border-color: #cd2653; }button,.button,.faux-button,.wp-block-button__link,.wp-block-file .wp-block-file__button,input[type="button"],input[type="reset"],input[type="submit"],.bg-accent,.bg-accent-hover:hover,.bg-accent-hover:focus,:root .has-accent-background-color,.comment-reply-link { background-color: #cd2653; }.fill-children-accent,.fill-children-accent * { fill: #cd2653; }body,.entry-title a,:root .has-primary-color { color: #000000; }:root .has-primary-background-color { background-color: #000000; }cite,figcaption,.wp-caption-text,.post-meta,.entry-content .wp-block-archives li,.entry-content .wp-block-categories li,.entry-content .wp-block-latest-posts li,.wp-block-latest-comments__comment-date,.wp-block-latest-posts__post-date,.wp-block-embed figcaption,.wp-block-image figcaption,.wp-block-pullquote cite,.comment-metadata,.comment-respond .comment-notes,.comment-respond .logged-in-as,.pagination .dots,.entry-content hr:not(.has-background),hr.styled-separator,:root .has-secondary-color { color: #6d6d6d; }:root .has-secondary-background-color { background-color: #6d6d6d; }pre,fieldset,input,textarea,table,table *,hr { border-color: #dcd7ca; }caption,code,code,kbd,samp,.wp-block-table.is-style-stripes tbody tr:nth-child(odd),:root .has-subtle-background-background-color { background-color: #dcd7ca; }.wp-block-table.is-style-stripes { border-bottom-color: #dcd7ca; }.wp-block-latest-posts.is-grid li { border-top-color: #dcd7ca; }:root .has-subtle-background-color { color: #dcd7ca; }body:not(.overlay-header) .primary-menu > li > a,body:not(.overlay-header) .primary-menu > li > .icon,.modal-menu a,.footer-menu a, .footer-widgets a,#site-footer .wp-block-button.is-style-outline,.wp-block-pullquote:before,.singular:not(.overlay-header) .entry-header a,.archive-header a,.header-footer-group .color-accent,.header-footer-group .color-accent-hover:hover { color: #cd2653; }.social-icons a,#site-footer button:not(.toggle),#site-footer .button,#site-footer .faux-button,#site-footer .wp-block-button__link,#site-footer .wp-block-file__button,#site-footer input[type="button"],#site-footer input[type="reset"],#site-footer input[type="submit"] { background-color: #cd2653; }.header-footer-group,body:not(.overlay-header) #site-header .toggle,.menu-modal .toggle { color: #000000; }body:not(.overlay-header) .primary-menu ul { background-color: #000000; }body:not(.overlay-header) .primary-menu > li > ul:after { border-bottom-color: #000000; }body:not(.overlay-header) .primary-menu ul ul:after { border-left-color: #000000; }.site-description,body:not(.overlay-header) .toggle-inner .toggle-text,.widget .post-date,.widget .rss-date,.widget_archive li,.widget_categories li,.widget cite,.widget_pages li,.widget_meta li,.widget_nav_menu li,.powered-by-wordpress,.to-the-top,.singular .entry-header .post-meta,.singular:not(.overlay-header) .entry-header .post-meta a { color: #6d6d6d; }.header-footer-group pre,.header-footer-group fieldset,.header-footer-group input,.header-footer-group textarea,.header-footer-group table,.header-footer-group table *,.footer-nav-widgets-wrapper,#site-footer,.menu-modal nav *,.footer-widgets-outer-wrapper,.footer-top { border-color: #dcd7ca; }.header-footer-group table caption,body:not(.overlay-header) .header-inner .toggle-wrapper::before { background-color: #dcd7ca; }
</style>
<link rel='stylesheet' id='twentytwenty-print-style-css'  href='http://plugin-test.localhost/wp-content/themes/twentytwenty/print.css?ver=1.5' media='print' />
<script src='http://plugin-test.localhost/wp-content/themes/twentytwenty/assets/js/index.js?ver=1.5' id='twentytwenty-js-js' async></script>
<link rel="https://api.w.org/" href="http://plugin-test.localhost/wp-json/" /><link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://plugin-test.localhost/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://plugin-test.localhost/wp-includes/wlwmanifest.xml" /> 
<meta name="generator" content="WordPress 5.5.3" />
	<script>document.documentElement.className = document.documentElement.className.replace( 'no-js', 'js' );</script>
	<style>.recentcomments a{display:inline !important;padding:0 !important;margin:0 !important;}</style><style media="print">#wpadminbar { display:none; }</style>
	<style media="screen">
	html { margin-top: 32px !important; }
	* html body { margin-top: 32px !important; }
	@media screen and ( max-width: 782px ) {
		html { margin-top: 46px !important; }
		* html body { margin-top: 46px !important; }
	}
</style>
	
	</head>

	<body class="home blog logged-in admin-bar no-customize-support wp-embed-responsive enable-search-modal has-no-pagination showing-comments show-avatars footer-top-visible">

			<script>
		(function() {
			var request, b = document.body, c = 'className', cs = 'customize-support', rcs = new RegExp('(^|\\s+)(no-)?'+cs+'(\\s+|$)');

				request = true;
	
			b[c] = b[c].replace( rcs, ' ' );
			// The customizer requires postMessage and CORS (if the site is cross domain).
			b[c] += ( window.postMessage && request ? ' ' : ' no-' ) + cs;
		}());
	</script>
			<div id="wpadminbar" class="nojq nojs">
							<a class="screen-reader-shortcut" href="#wp-toolbar" tabindex="1">Skip to toolbar</a>
						<div class="quicklinks" id="wp-toolbar" role="navigation" aria-label="Toolbar">
				<ul id='wp-admin-bar-root-default' class="ab-top-menu"><li id='wp-admin-bar-wp-logo' class="menupop"><a class='ab-item' aria-haspopup="true" href='http://plugin-test.localhost/wp-admin/about.php'><span class="ab-icon"></span><span class="screen-reader-text">About WordPress</span></a><div class="ab-sub-wrapper"><ul id='wp-admin-bar-wp-logo-default' class="ab-submenu"><li id='wp-admin-bar-about'><a class='ab-item' href='http://plugin-test.localhost/wp-admin/about.php'>About WordPress</a></li></ul><ul id='wp-admin-bar-wp-logo-external' class="ab-sub-secondary ab-submenu"><li id='wp-admin-bar-wporg'><a class='ab-item' href='https://wordpress.org/'>WordPress.org</a></li><li id='wp-admin-bar-documentation'><a class='ab-item' href='https://codex.wordpress.org/'>Documentation</a></li><li id='wp-admin-bar-support-forums'><a class='ab-item' href='https://wordpress.org/support/'>Support</a></li><li id='wp-admin-bar-feedback'><a class='ab-item' href='https://wordpress.org/support/forum/requests-and-feedback'>Feedback</a></li></ul></div></li><li id='wp-admin-bar-site-name' class="menupop"><a class='ab-item' aria-haspopup="true" href='http://plugin-test.localhost/wp-admin/'>Plugin Test</a><div class="ab-sub-wrapper"><ul id='wp-admin-bar-site-name-default' class="ab-submenu"><li id='wp-admin-bar-dashboard'><a class='ab-item' href='http://plugin-test.localhost/wp-admin/'>Dashboard</a></li></ul><ul id='wp-admin-bar-appearance' class="ab-submenu"><li id='wp-admin-bar-themes'><a class='ab-item' href='http://plugin-test.localhost/wp-admin/themes.php'>Themes</a></li><li id='wp-admin-bar-widgets'><a class='ab-item' href='http://plugin-test.localhost/wp-admin/themes.php?page=gutenberg-widgets'>Widgets</a></li><li id='wp-admin-bar-menus'><a class='ab-item' href='http://plugin-test.localhost/wp-admin/nav-menus.php'>Menus</a></li><li id='wp-admin-bar-background' class="hide-if-customize"><a class='ab-item' href='http://plugin-test.localhost/wp-admin/themes.php?page=custom-background'>Background</a></li></ul></div></li><li id='wp-admin-bar-customize' class="hide-if-no-customize"><a class='ab-item' href='http://plugin-test.localhost/wp-admin/customize.php?url=http%3A%2F%2Fplugin-test.localhost%2F'>Customize</a></li><li id='wp-admin-bar-comments'><a class='ab-item' href='http://plugin-test.localhost/wp-admin/edit-comments.php'><span class="ab-icon"></span><span class="ab-label awaiting-mod pending-count count-0" aria-hidden="true">0</span><span class="screen-reader-text comments-in-moderation-text">0 Comments in moderation</span></a></li><li id='wp-admin-bar-new-content' class="menupop"><a class='ab-item' aria-haspopup="true" href='http://plugin-test.localhost/wp-admin/post-new.php'><span class="ab-icon"></span><span class="ab-label">New</span></a><div class="ab-sub-wrapper"><ul id='wp-admin-bar-new-content-default' class="ab-submenu"><li id='wp-admin-bar-new-post'><a class='ab-item' href='http://plugin-test.localhost/wp-admin/post-new.php'>Post</a></li><li id='wp-admin-bar-new-media'><a class='ab-item' href='http://plugin-test.localhost/wp-admin/media-new.php'>Media</a></li><li id='wp-admin-bar-new-page'><a class='ab-item' href='http://plugin-test.localhost/wp-admin/post-new.php?post_type=page'>Page</a></li><li id='wp-admin-bar-new-user'><a class='ab-item' href='http://plugin-test.localhost/wp-admin/user-new.php'>User</a></li></ul></div></li></ul><ul id='wp-admin-bar-top-secondary' class="ab-top-secondary ab-top-menu"><li id='wp-admin-bar-search' class="admin-bar-search"><div class="ab-item ab-empty-item" tabindex="-1"><form action="http://plugin-test.localhost/" method="get" id="adminbarsearch"><input class="adminbar-input" name="s" id="adminbar-search" type="text" value="" maxlength="150" /><label for="adminbar-search" class="screen-reader-text">Search</label><input type="submit" class="adminbar-button" value="Search"/></form></div></li><li id='wp-admin-bar-my-account' class="menupop with-avatar"><a class='ab-item' aria-haspopup="true" href='http://plugin-test.localhost/wp-admin/profile.php'>Howdy, <span class="display-name">admin</span><img alt='' src='http://1.gravatar.com/avatar/77a591799c03c21b44b472e151bc8374?s=26&#038;d=mm&#038;r=g' srcset='http://1.gravatar.com/avatar/77a591799c03c21b44b472e151bc8374?s=52&#038;d=mm&#038;r=g 2x' class='avatar avatar-26 photo' height='26' width='26' loading='lazy'/></a><div class="ab-sub-wrapper"><ul id='wp-admin-bar-user-actions' class="ab-submenu"><li id='wp-admin-bar-user-info'><a class='ab-item' tabindex="-1" href='http://plugin-test.localhost/wp-admin/profile.php'><img alt='' src='http://1.gravatar.com/avatar/77a591799c03c21b44b472e151bc8374?s=64&#038;d=mm&#038;r=g' srcset='http://1.gravatar.com/avatar/77a591799c03c21b44b472e151bc8374?s=128&#038;d=mm&#038;r=g 2x' class='avatar avatar-64 photo' height='64' width='64' loading='lazy'/><span class='display-name'>admin</span></a></li><li id='wp-admin-bar-edit-profile'><a class='ab-item' href='http://plugin-test.localhost/wp-admin/profile.php'>Edit Profile</a></li><li id='wp-admin-bar-logout'><a class='ab-item' href='http://plugin-test.localhost/wp-login.php?action=logout&#038;_wpnonce=2c655d3f1a'>Log Out</a></li></ul></div></li></ul>			</div>
						<a class="screen-reader-shortcut" href="http://plugin-test.localhost/wp-login.php?action=logout&#038;_wpnonce=2c655d3f1a">Log Out</a>
					</div>

		<a class="skip-link screen-reader-text" href="#site-content">Skip to the content</a>
		<header id="site-header" class="header-footer-group" role="banner">

			<div class="header-inner section-inner">

				<div class="header-titles-wrapper">

					
						<button class="toggle search-toggle mobile-search-toggle" data-toggle-target=".search-modal" data-toggle-body-class="showing-search-modal" data-set-focus=".search-modal .search-field" aria-expanded="false">
							<span class="toggle-inner">
								<span class="toggle-icon">
									<svg class="svg-icon" aria-hidden="true" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg" width="23" height="23" viewBox="0 0 23 23"><path d="M38.710696,48.0601792 L43,52.3494831 L41.3494831,54 L37.0601792,49.710696 C35.2632422,51.1481185 32.9839107,52.0076499 30.5038249,52.0076499 C24.7027226,52.0076499 20,47.3049272 20,41.5038249 C20,35.7027226 24.7027226,31 30.5038249,31 C36.3049272,31 41.0076499,35.7027226 41.0076499,41.5038249 C41.0076499,43.9839107 40.1481185,46.2632422 38.710696,48.0601792 Z M36.3875844,47.1716785 C37.8030221,45.7026647 38.6734666,43.7048964 38.6734666,41.5038249 C38.6734666,36.9918565 35.0157934,33.3341833 30.5038249,33.3341833 C25.9918565,33.3341833 22.3341833,36.9918565 22.3341833,41.5038249 C22.3341833,46.0157934 25.9918565,49.6734666 30.5038249,49.6734666 C32.7048964,49.6734666 34.7026647,48.8030221 36.1716785,47.3875844 C36.2023931,47.347638 36.2360451,47.3092237 36.2726343,47.2726343 C36.3092237,47.2360451 36.347638,47.2023931 36.3875844,47.1716785 Z" transform="translate(-20 -31)" /></svg>								</span>
								<span class="toggle-text">Search</span>
							</span>
						</button><!-- .search-toggle -->

					
					<div class="header-titles">

						<h1 class="site-title"><a href="http://plugin-test.localhost/">Plugin Test</a></h1><div class="site-description">Just another WordPress site</div><!-- .site-description -->
					</div><!-- .header-titles -->

					<button class="toggle nav-toggle mobile-nav-toggle" data-toggle-target=".menu-modal"  data-toggle-body-class="showing-menu-modal" aria-expanded="false" data-set-focus=".close-nav-toggle">
						<span class="toggle-inner">
							<span class="toggle-icon">
								<svg class="svg-icon" aria-hidden="true" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg" width="26" height="7" viewBox="0 0 26 7"><path fill-rule="evenodd" d="M332.5,45 C330.567003,45 329,43.4329966 329,41.5 C329,39.5670034 330.567003,38 332.5,38 C334.432997,38 336,39.5670034 336,41.5 C336,43.4329966 334.432997,45 332.5,45 Z M342,45 C340.067003,45 338.5,43.4329966 338.5,41.5 C338.5,39.5670034 340.067003,38 342,38 C343.932997,38 345.5,39.5670034 345.5,41.5 C345.5,43.4329966 343.932997,45 342,45 Z M351.5,45 C349.567003,45 348,43.4329966 348,41.5 C348,39.5670034 349.567003,38 351.5,38 C353.432997,38 355,39.5670034 355,41.5 C355,43.4329966 353.432997,45 351.5,45 Z" transform="translate(-329 -38)" /></svg>							</span>
							<span class="toggle-text">Menu</span>
						</span>
					</button><!-- .nav-toggle -->

				</div><!-- .header-titles-wrapper -->

				<div class="header-navigation-wrapper">

					
							<nav class="primary-menu-wrapper" aria-label="Horizontal" role="navigation">

								<ul class="primary-menu reset-list-style">

								<li class="page_item page-item-2"><a href="http://plugin-test.localhost/sample-page/">Sample Page</a></li>

								</ul>

							</nav><!-- .primary-menu-wrapper -->

						
						<div class="header-toggles hide-no-js">

						
							<div class="toggle-wrapper search-toggle-wrapper">

								<button class="toggle search-toggle desktop-search-toggle" data-toggle-target=".search-modal" data-toggle-body-class="showing-search-modal" data-set-focus=".search-modal .search-field" aria-expanded="false">
									<span class="toggle-inner">
										<svg class="svg-icon" aria-hidden="true" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg" width="23" height="23" viewBox="0 0 23 23"><path d="M38.710696,48.0601792 L43,52.3494831 L41.3494831,54 L37.0601792,49.710696 C35.2632422,51.1481185 32.9839107,52.0076499 30.5038249,52.0076499 C24.7027226,52.0076499 20,47.3049272 20,41.5038249 C20,35.7027226 24.7027226,31 30.5038249,31 C36.3049272,31 41.0076499,35.7027226 41.0076499,41.5038249 C41.0076499,43.9839107 40.1481185,46.2632422 38.710696,48.0601792 Z M36.3875844,47.1716785 C37.8030221,45.7026647 38.6734666,43.7048964 38.6734666,41.5038249 C38.6734666,36.9918565 35.0157934,33.3341833 30.5038249,33.3341833 C25.9918565,33.3341833 22.3341833,36.9918565 22.3341833,41.5038249 C22.3341833,46.0157934 25.9918565,49.6734666 30.5038249,49.6734666 C32.7048964,49.6734666 34.7026647,48.8030221 36.1716785,47.3875844 C36.2023931,47.347638 36.2360451,47.3092237 36.2726343,47.2726343 C36.3092237,47.2360451 36.347638,47.2023931 36.3875844,47.1716785 Z" transform="translate(-20 -31)" /></svg>										<span class="toggle-text">Search</span>
									</span>
								</button><!-- .search-toggle -->

							</div>

							
						</div><!-- .header-toggles -->
						
				</div><!-- .header-navigation-wrapper -->

			</div><!-- .header-inner -->

			<div class="search-modal cover-modal header-footer-group" data-modal-target-string=".search-modal">

	<div class="search-modal-inner modal-inner">

		<div class="section-inner">

			<form role="search" aria-label="Search for:" method="get" class="search-form" action="http://plugin-test.localhost/">
	<label for="search-form-1">
		<span class="screen-reader-text">Search for:</span>
		<input type="search" id="search-form-1" class="search-field" placeholder="Search &hellip;" value="" name="s" />
	</label>
	<input type="submit" class="search-submit" value="Search" />
</form>

			<button class="toggle search-untoggle close-search-toggle fill-children-current-color" data-toggle-target=".search-modal" data-toggle-body-class="showing-search-modal" data-set-focus=".search-modal .search-field" aria-expanded="false">
				<span class="screen-reader-text">Close search</span>
				<svg class="svg-icon" aria-hidden="true" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><polygon fill="" fill-rule="evenodd" points="6.852 7.649 .399 1.195 1.445 .149 7.899 6.602 14.352 .149 15.399 1.195 8.945 7.649 15.399 14.102 14.352 15.149 7.899 8.695 1.445 15.149 .399 14.102" /></svg>			</button><!-- .search-toggle -->

		</div><!-- .section-inner -->

	</div><!-- .search-modal-inner -->

</div><!-- .menu-modal -->

		</header><!-- #site-header -->

		
<div class="menu-modal cover-modal header-footer-group" data-modal-target-string=".menu-modal">

	<div class="menu-modal-inner modal-inner">

		<div class="menu-wrapper section-inner">

			<div class="menu-top">

				<button class="toggle close-nav-toggle fill-children-current-color" data-toggle-target=".menu-modal" data-toggle-body-class="showing-menu-modal" aria-expanded="false" data-set-focus=".menu-modal">
					<span class="toggle-text">Close Menu</span>
					<svg class="svg-icon" aria-hidden="true" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><polygon fill="" fill-rule="evenodd" points="6.852 7.649 .399 1.195 1.445 .149 7.899 6.602 14.352 .149 15.399 1.195 8.945 7.649 15.399 14.102 14.352 15.149 7.899 8.695 1.445 15.149 .399 14.102" /></svg>				</button><!-- .nav-toggle -->

				
					<nav class="mobile-menu" aria-label="Mobile" role="navigation">

						<ul class="modal-menu reset-list-style">

						<li class="page_item page-item-2"><div class="ancestor-wrapper"><a href="http://plugin-test.localhost/sample-page/">Sample Page</a></div><!-- .ancestor-wrapper --></li>

						</ul>

					</nav>

					
			</div><!-- .menu-top -->

			<div class="menu-bottom">

				
			</div><!-- .menu-bottom -->

		</div><!-- .menu-wrapper -->

	</div><!-- .menu-modal-inner -->

</div><!-- .menu-modal -->

<main id="site-content" role="main">

	
<article class="post-1 post type-post status-publish format-standard hentry category-uncategorized" id="post-1">

	
<header class="entry-header has-text-align-center">

	<div class="entry-header-inner section-inner medium">

		
			<div class="entry-categories">
				<span class="screen-reader-text">Categories</span>
				<div class="entry-categories-inner">
					<a href="http://plugin-test.localhost/category/uncategorized/" rel="category tag">Uncategorized</a>				</div><!-- .entry-categories-inner -->
			</div><!-- .entry-categories -->

			<h2 class="entry-title heading-size-1"><a href="http://plugin-test.localhost/2020/10/27/hello-world/">Hello world!</a></h2>
		<div class="post-meta-wrapper post-meta-single post-meta-single-top">

			<ul class="post-meta">

									<li class="post-author meta-wrapper">
						<span class="meta-icon">
							<span class="screen-reader-text">Post author</span>
							<svg class="svg-icon" aria-hidden="true" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg" width="18" height="20" viewBox="0 0 18 20"><path fill="" d="M18,19 C18,19.5522847 17.5522847,20 17,20 C16.4477153,20 16,19.5522847 16,19 L16,17 C16,15.3431458 14.6568542,14 13,14 L5,14 C3.34314575,14 2,15.3431458 2,17 L2,19 C2,19.5522847 1.55228475,20 1,20 C0.44771525,20 0,19.5522847 0,19 L0,17 C0,14.2385763 2.23857625,12 5,12 L13,12 C15.7614237,12 18,14.2385763 18,17 L18,19 Z M9,10 C6.23857625,10 4,7.76142375 4,5 C4,2.23857625 6.23857625,0 9,0 C11.7614237,0 14,2.23857625 14,5 C14,7.76142375 11.7614237,10 9,10 Z M9,8 C10.6568542,8 12,6.65685425 12,5 C12,3.34314575 10.6568542,2 9,2 C7.34314575,2 6,3.34314575 6,5 C6,6.65685425 7.34314575,8 9,8 Z" /></svg>						</span>
						<span class="meta-text">
							By <a href="http://plugin-test.localhost/author/admin/">admin</a>						</span>
					</li>
										<li class="post-date meta-wrapper">
						<span class="meta-icon">
							<span class="screen-reader-text">Post date</span>
							<svg class="svg-icon" aria-hidden="true" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg" width="18" height="19" viewBox="0 0 18 19"><path fill="" d="M4.60069444,4.09375 L3.25,4.09375 C2.47334957,4.09375 1.84375,4.72334957 1.84375,5.5 L1.84375,7.26736111 L16.15625,7.26736111 L16.15625,5.5 C16.15625,4.72334957 15.5266504,4.09375 14.75,4.09375 L13.3993056,4.09375 L13.3993056,4.55555556 C13.3993056,5.02154581 13.0215458,5.39930556 12.5555556,5.39930556 C12.0895653,5.39930556 11.7118056,5.02154581 11.7118056,4.55555556 L11.7118056,4.09375 L6.28819444,4.09375 L6.28819444,4.55555556 C6.28819444,5.02154581 5.9104347,5.39930556 5.44444444,5.39930556 C4.97845419,5.39930556 4.60069444,5.02154581 4.60069444,4.55555556 L4.60069444,4.09375 Z M6.28819444,2.40625 L11.7118056,2.40625 L11.7118056,1 C11.7118056,0.534009742 12.0895653,0.15625 12.5555556,0.15625 C13.0215458,0.15625 13.3993056,0.534009742 13.3993056,1 L13.3993056,2.40625 L14.75,2.40625 C16.4586309,2.40625 17.84375,3.79136906 17.84375,5.5 L17.84375,15.875 C17.84375,17.5836309 16.4586309,18.96875 14.75,18.96875 L3.25,18.96875 C1.54136906,18.96875 0.15625,17.5836309 0.15625,15.875 L0.15625,5.5 C0.15625,3.79136906 1.54136906,2.40625 3.25,2.40625 L4.60069444,2.40625 L4.60069444,1 C4.60069444,0.534009742 4.97845419,0.15625 5.44444444,0.15625 C5.9104347,0.15625 6.28819444,0.534009742 6.28819444,1 L6.28819444,2.40625 Z M1.84375,8.95486111 L1.84375,15.875 C1.84375,16.6516504 2.47334957,17.28125 3.25,17.28125 L14.75,17.28125 C15.5266504,17.28125 16.15625,16.6516504 16.15625,15.875 L16.15625,8.95486111 L1.84375,8.95486111 Z" /></svg>						</span>
						<span class="meta-text">
							<a href="http://plugin-test.localhost/2020/10/27/hello-world/">October 27, 2020</a>
						</span>
					</li>
										<li class="post-comment-link meta-wrapper">
						<span class="meta-icon">
							<svg class="svg-icon" aria-hidden="true" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg" width="19" height="19" viewBox="0 0 19 19"><path d="M9.43016863,13.2235931 C9.58624731,13.094699 9.7823475,13.0241935 9.98476849,13.0241935 L15.0564516,13.0241935 C15.8581553,13.0241935 16.5080645,12.3742843 16.5080645,11.5725806 L16.5080645,3.44354839 C16.5080645,2.64184472 15.8581553,1.99193548 15.0564516,1.99193548 L3.44354839,1.99193548 C2.64184472,1.99193548 1.99193548,2.64184472 1.99193548,3.44354839 L1.99193548,11.5725806 C1.99193548,12.3742843 2.64184472,13.0241935 3.44354839,13.0241935 L5.76612903,13.0241935 C6.24715123,13.0241935 6.63709677,13.4141391 6.63709677,13.8951613 L6.63709677,15.5301903 L9.43016863,13.2235931 Z M3.44354839,14.766129 C1.67980032,14.766129 0.25,13.3363287 0.25,11.5725806 L0.25,3.44354839 C0.25,1.67980032 1.67980032,0.25 3.44354839,0.25 L15.0564516,0.25 C16.8201997,0.25 18.25,1.67980032 18.25,3.44354839 L18.25,11.5725806 C18.25,13.3363287 16.8201997,14.766129 15.0564516,14.766129 L10.2979143,14.766129 L6.32072889,18.0506004 C5.75274472,18.5196577 4.89516129,18.1156602 4.89516129,17.3790323 L4.89516129,14.766129 L3.44354839,14.766129 Z" /></svg>						</span>
						<span class="meta-text">
							<a href="http://plugin-test.localhost/2020/10/27/hello-world/#comments">1 Comment<span class="screen-reader-text"> on Hello world!</span></a>						</span>
					</li>
					
			</ul><!-- .post-meta -->

		</div><!-- .post-meta-wrapper -->

		
	</div><!-- .entry-header-inner -->

</header><!-- .entry-header -->

	<div class="post-inner thin ">

		<div class="entry-content">

			
<p>Welcome to WordPress. This is your first post. Edit or delete it, then start writing!</p>

		</div><!-- .entry-content -->

	</div><!-- .post-inner -->

	<div class="section-inner">
		<div class="post-meta-wrapper post-meta-edit-link-wrapper"><ul class="post-meta"><li class="post-edit meta-wrapper"><span class="meta-icon"><svg class="svg-icon" aria-hidden="true" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18"><path fill="" d="M14.7272727,11.1763636 C14.7272727,10.7244943 15.0935852,10.3581818 15.5454545,10.3581818 C15.9973239,10.3581818 16.3636364,10.7244943 16.3636364,11.1763636 L16.3636364,15.5454545 C16.3636364,16.9010626 15.2646989,18 13.9090909,18 L2.45454545,18 C1.09893743,18 0,16.9010626 0,15.5454545 L0,4.09090909 C0,2.73530107 1.09893743,1.63636364 2.45454545,1.63636364 L6.82363636,1.63636364 C7.2755057,1.63636364 7.64181818,2.00267611 7.64181818,2.45454545 C7.64181818,2.9064148 7.2755057,3.27272727 6.82363636,3.27272727 L2.45454545,3.27272727 C2.00267611,3.27272727 1.63636364,3.63903975 1.63636364,4.09090909 L1.63636364,15.5454545 C1.63636364,15.9973239 2.00267611,16.3636364 2.45454545,16.3636364 L13.9090909,16.3636364 C14.3609602,16.3636364 14.7272727,15.9973239 14.7272727,15.5454545 L14.7272727,11.1763636 Z M6.54545455,9.33890201 L6.54545455,11.4545455 L8.66109799,11.4545455 L16.0247344,4.09090909 L13.9090909,1.97526564 L6.54545455,9.33890201 Z M14.4876328,0.239639906 L17.7603601,3.51236718 C18.07988,3.83188705 18.07988,4.34993113 17.7603601,4.669451 L9.57854191,12.8512692 C9.42510306,13.004708 9.21699531,13.0909091 9,13.0909091 L5.72727273,13.0909091 C5.27540339,13.0909091 4.90909091,12.7245966 4.90909091,12.2727273 L4.90909091,9 C4.90909091,8.78300469 4.99529196,8.57489694 5.14873082,8.42145809 L13.330549,0.239639906 C13.6500689,-0.0798799688 14.1681129,-0.0798799688 14.4876328,0.239639906 Z" /></svg></span><span class="meta-text"><a href="http://plugin-test.localhost/wp-admin/post.php?post=1&#038;action=edit">Edit <span class="screen-reader-text">Hello world!</span></a></span></li></ul><!-- .post-meta --></div><!-- .post-meta-wrapper -->
	</div><!-- .section-inner -->

	
</article><!-- .post -->

	
</main><!-- #site-content -->


	<div class="footer-nav-widgets-wrapper header-footer-group">

		<div class="footer-inner section-inner">

			
			
				<aside class="footer-widgets-outer-wrapper" role="complementary">

					<div class="footer-widgets-wrapper">

						
							<div class="footer-widgets column-one grid-item">
								<div class="widget widget_search"><div class="widget-content"><form role="search"  method="get" class="search-form" action="http://plugin-test.localhost/">
	<label for="search-form-2">
		<span class="screen-reader-text">Search for:</span>
		<input type="search" id="search-form-2" class="search-field" placeholder="Search &hellip;" value="" name="s" />
	</label>
	<input type="submit" class="search-submit" value="Search" />
</form>
</div></div>
		<div class="widget widget_recent_entries"><div class="widget-content">
		<h2 class="widget-title subheading heading-size-3">Recent Posts</h2>
		<ul>
											<li>
					<a href="http://plugin-test.localhost/2020/10/27/hello-world/">Hello world!</a>
									</li>
					</ul>

		</div></div><div class="widget widget_recent_comments"><div class="widget-content"><h2 class="widget-title subheading heading-size-3">Recent Comments</h2><ul id="recentcomments"><li class="recentcomments"><span class="comment-author-link"><a href='https://wordpress.org/' rel='external nofollow ugc' class='url'>A WordPress Commenter</a></span> on <a href="http://plugin-test.localhost/2020/10/27/hello-world/#comment-1">Hello world!</a></li></ul></div></div>							</div>

						
						
							<div class="footer-widgets column-two grid-item">
								<div class="widget widget_archive"><div class="widget-content"><h2 class="widget-title subheading heading-size-3">Archives</h2>
			<ul>
					<li><a href='http://plugin-test.localhost/2020/10/'>October 2020</a></li>
			</ul>

			</div></div><div class="widget widget_categories"><div class="widget-content"><h2 class="widget-title subheading heading-size-3">Categories</h2>
			<ul>
					<li class="cat-item cat-item-1"><a href="http://plugin-test.localhost/category/uncategorized/">Uncategorized</a>
</li>
			</ul>

			</div></div><div class="widget widget_meta"><div class="widget-content"><h2 class="widget-title subheading heading-size-3">Meta</h2>
		<ul>
			<li><a href="http://plugin-test.localhost/wp-admin/">Site Admin</a></li>			<li><a href="http://plugin-test.localhost/wp-login.php?action=logout&#038;_wpnonce=2c655d3f1a">Log out</a></li>
			<li><a href="http://plugin-test.localhost/feed/">Entries feed</a></li>
			<li><a href="http://plugin-test.localhost/comments/feed/">Comments feed</a></li>

			<li><a href="https://wordpress.org/">WordPress.org</a></li>
		</ul>

		</div></div>							</div>

						
					</div><!-- .footer-widgets-wrapper -->

				</aside><!-- .footer-widgets-outer-wrapper -->

			
		</div><!-- .footer-inner -->

	</div><!-- .footer-nav-widgets-wrapper -->


			<footer id="site-footer" role="contentinfo" class="header-footer-group">

				<div class="section-inner">

					<div class="footer-credits">

						<p class="footer-copyright">&copy;
							2020							<a href="http://plugin-test.localhost/">Plugin Test</a>
						</p><!-- .footer-copyright -->

						<p class="powered-by-wordpress">
							<a href="https://wordpress.org/">
								Powered by WordPress							</a>
						</p><!-- .powered-by-wordpress -->

					</div><!-- .footer-credits -->

					<a class="to-the-top" href="#site-header">
						<span class="to-the-top-long">
							To the top <span class="arrow" aria-hidden="true">&uarr;</span>						</span><!-- .to-the-top-long -->
						<span class="to-the-top-short">
							Up <span class="arrow" aria-hidden="true">&uarr;</span>						</span><!-- .to-the-top-short -->
					</a><!-- .to-the-top -->

				</div><!-- .section-inner -->

			</footer><!-- #site-footer -->

		<script src='http://plugin-test.localhost/wp-includes/js/hoverintent-js.min.js?ver=2.2.1' id='hoverintent-js-js'></script>
<script src='http://plugin-test.localhost/wp-includes/js/admin-bar.min.js?ver=5.5.3' id='admin-bar-js'></script>
<script src='http://plugin-test.localhost/wp-includes/js/wp-embed.min.js?ver=5.5.3' id='wp-embed-js'></script>
	<script>
	/(trident|msie)/i.test(navigator.userAgent)&&document.getElementById&&window.addEventListener&&window.addEventListener("hashchange",function(){var t,e=location.hash.substring(1);/^[A-z0-9_-]+$/.test(e)&&(t=document.getElementById(e))&&(/^(?:a|select|input|button|textarea)$/i.test(t.tagName)||(t.tabIndex=-1),t.focus())},!1);
	</script>
	
	</body>
</html>
```
</details>

<details>
  <summary>Processed inline HTML:</summary>
  
```
&lt;!DOCTYPE html&gt;

&lt;html class="<a>no-js</a>" lang="<a>en-US</a>"&gt;

	&lt;head&gt;

		&lt;meta charset="<a>UTF-8</a>"&gt;
		&lt;meta name="<a>viewport</a>" content="<a>width=device-width, initial-scale=1.0</a>" &gt;

		&lt;link rel="<a>profile</a>" href="<a href="view-source:https://gmpg.org/xfn/11">https://gmpg.org/xfn/11</a>"&gt;

		&lt;title&gt;Plugin Test &amp;#8211; Just another WordPress site&lt;/title&gt;
&lt;link rel='<a>dns-prefetch</a>' href='<a href="view-source:http://s.w.org/">//s.w.org</a>' /&gt;
&lt;link rel="<a>alternate</a>" type="<a>application/rss+xml</a>" title="<a>Plugin Test &amp;raquo; Feed</a>" href="<a href="view-source:http://plugin-test.localhost/feed/">http://plugin-test.localhost/feed/</a>" /&gt;
&lt;link rel="<a>alternate</a>" type="<a>application/rss+xml</a>" title="<a>Plugin Test &amp;raquo; Comments Feed</a>" href="<a href="view-source:http://plugin-test.localhost/comments/feed/">http://plugin-test.localhost/comments/feed/</a>" /&gt;
		&lt;script&gt;
			window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/13.0.0\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/13.0.0\/svg\/","svgExt":".svg","source":{"concatemoji":"http:\/\/plugin-test.localhost\/wp-includes\/js\/wp-emoji-release.min.js?ver=5.5.3"}};
			!function(e,a,t){var r,n,o,i,p=a.createElement("canvas"),s=p.getContext&amp;&amp;p.getContext("2d");function c(e,t){var a=String.fromCharCode;s.clearRect(0,0,p.width,p.height),s.fillText(a.apply(this,e),0,0);var r=p.toDataURL();return s.clearRect(0,0,p.width,p.height),s.fillText(a.apply(this,t),0,0),r===p.toDataURL()}function l(e){if(!s||!s.fillText)return!1;switch(s.textBaseline="top",s.font="600 32px Arial",e){case"flag":return!c([127987,65039,8205,9895,65039],[127987,65039,8203,9895,65039])&amp;&amp;(!c([55356,56826,55356,56819],[55356,56826,8203,55356,56819])&amp;&amp;!c([55356,57332,56128,56423,56128,56418,56128,56421,56128,56430,56128,56423,56128,56447],[55356,57332,8203,56128,56423,8203,56128,56418,8203,56128,56421,8203,56128,56430,8203,56128,56423,8203,56128,56447]));case"emoji":return!c([55357,56424,8205,55356,57212],[55357,56424,8203,55356,57212])}return!1}function d(e){var t=a.createElement("script");t.src=e,t.defer=t.type="text/javascript",a.getElementsByTagName("head")[0].appendChild(t)}for(i=Array("flag","emoji"),t.supports={everything:!0,everythingExceptFlag:!0},o=0;o&lt;i.length;o++)t.supports[i[o]]=l(i[o]),t.supports.everything=t.supports.everything&amp;&amp;t.supports[i[o]],"flag"!==i[o]&amp;&amp;(t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&amp;&amp;t.supports[i[o]]);t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&amp;&amp;!t.supports.flag,t.DOMReady=!1,t.readyCallback=function(){t.DOMReady=!0},t.supports.everything||(n=function(){t.readyCallback()},a.addEventListener?(a.addEventListener("DOMContentLoaded",n,!1),e.addEventListener("load",n,!1)):(e.attachEvent("onload",n),a.attachEvent("onreadystatechange",function(){"complete"===a.readyState&amp;&amp;t.readyCallback()})),(r=t.source||{}).concatemoji?d(r.concatemoji):r.wpemoji&amp;&amp;r.twemoji&amp;&amp;(d(r.twemoji),d(r.wpemoji)))}(window,document,window._wpemojiSettings);
		&lt;/script&gt;
		&lt;style&gt;
img.wp-smiley,
img.emoji {
	display: inline !important;
	border: none !important;
	box-shadow: none !important;
	height: 1em !important;
	width: 1em !important;
	margin: 0 .07em !important;
	vertical-align: -0.1em !important;
	background: none !important;
	padding: 0 !important;
}
&lt;/style&gt;
	&lt;link rel='<a>stylesheet</a>' id='<a>dashicons-css</a>'  href='<a href="view-source:http://plugin-test.localhost/wp-includes/css/dashicons.min.css?ver=5.5.3">http://plugin-test.localhost/wp-includes/css/dashicons.min.css?ver=5.5.3</a>' media='<a>all</a>' /&gt;
&lt;link rel='<a>stylesheet</a>' id='<a>admin-bar-css</a>'  href='<a href="view-source:http://plugin-test.localhost/wp-includes/css/admin-bar.min.css?ver=5.5.3">http://plugin-test.localhost/wp-includes/css/admin-bar.min.css?ver=5.5.3</a>' media='<a>all</a>' /&gt;
&lt;link rel='<a>stylesheet</a>' id='<a>wp-block-library-css</a>'  href='<a href="view-source:http://plugin-test.localhost/wp-content/plugins/gutenberg/build/block-library/style.css?ver=1604325854">http://plugin-test.localhost/wp-content/plugins/gutenberg/build/block-library/style.css?ver=1604325854</a>' media='<a>all</a>' /&gt;
&lt;style id='<a>global-styles-inline-css</a>'&gt;
:root{--wp--preset--color--accent:#cd2653;--wp--preset--color--primary:#000000;--wp--preset--color--secondary:#6d6d6d;--wp--preset--color--subtle-background:#dcd7ca;--wp--preset--color--background:#f5efe0;--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple:linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%);--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan:linear-gradient(135deg,rgb(122,220,180) 0%,rgb(0,208,130) 100%);--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange:linear-gradient(135deg,rgba(252,185,0,1) 0%,rgba(255,105,0,1) 100%);--wp--preset--gradient--luminous-vivid-orange-to-vivid-red:linear-gradient(135deg,rgba(255,105,0,1) 0%,rgb(207,46,46) 100%);--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray:linear-gradient(135deg,rgb(238,238,238) 0%,rgb(169,184,195) 100%);--wp--preset--gradient--cool-to-warm-spectrum:linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%);--wp--preset--gradient--blush-light-purple:linear-gradient(135deg,rgb(255,206,236) 0%,rgb(152,150,240) 100%);--wp--preset--gradient--blush-bordeaux:linear-gradient(135deg,rgb(254,205,165) 0%,rgb(254,45,45) 50%,rgb(107,0,62) 100%);--wp--preset--gradient--luminous-dusk:linear-gradient(135deg,rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);--wp--preset--gradient--pale-ocean:linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);--wp--preset--gradient--electric-grass:linear-gradient(135deg,rgb(202,248,128) 0%,rgb(113,206,126) 100%);--wp--preset--gradient--midnight:linear-gradient(135deg,rgb(2,3,129) 0%,rgb(40,116,252) 100%);--wp--preset--font-size--small:18px;--wp--preset--font-size--normal:21px;--wp--preset--font-size--large:26.25px;--wp--preset--font-size--larger:32px;}.has-accent-color{color:#cd2653;}
.has-primary-color{color:#000000;}
.has-secondary-color{color:#6d6d6d;}
.has-subtle-background-color{color:#dcd7ca;}
.has-background-color{color:#f5efe0;}
.has-accent-background-color{background-color:#cd2653;}
.has-primary-background-color{background-color:#000000;}
.has-secondary-background-color{background-color:#6d6d6d;}
.has-subtle-background-background-color{background-color:#dcd7ca;}
.has-background-background-color{background-color:#f5efe0;}
.has-vivid-cyan-blue-to-vivid-purple-gradient-background{background:linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%);}
.has-light-green-cyan-to-vivid-green-cyan-gradient-background{background:linear-gradient(135deg,rgb(122,220,180) 0%,rgb(0,208,130) 100%);}
.has-luminous-vivid-amber-to-luminous-vivid-orange-gradient-background{background:linear-gradient(135deg,rgba(252,185,0,1) 0%,rgba(255,105,0,1) 100%);}
.has-luminous-vivid-orange-to-vivid-red-gradient-background{background:linear-gradient(135deg,rgba(255,105,0,1) 0%,rgb(207,46,46) 100%);}
.has-very-light-gray-to-cyan-bluish-gray-gradient-background{background:linear-gradient(135deg,rgb(238,238,238) 0%,rgb(169,184,195) 100%);}
.has-cool-to-warm-spectrum-gradient-background{background:linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%);}
.has-blush-light-purple-gradient-background{background:linear-gradient(135deg,rgb(255,206,236) 0%,rgb(152,150,240) 100%);}
.has-blush-bordeaux-gradient-background{background:linear-gradient(135deg,rgb(254,205,165) 0%,rgb(254,45,45) 50%,rgb(107,0,62) 100%);}
.has-luminous-dusk-gradient-background{background:linear-gradient(135deg,rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);}
.has-pale-ocean-gradient-background{background:linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);}
.has-electric-grass-gradient-background{background:linear-gradient(135deg,rgb(202,248,128) 0%,rgb(113,206,126) 100%);}
.has-midnight-gradient-background{background:linear-gradient(135deg,rgb(2,3,129) 0%,rgb(40,116,252) 100%);}
.has-small-font-size{font-size:18px;}
.has-normal-font-size{font-size:21px;}
.has-large-font-size{font-size:26.25px;}
.has-larger-font-size{font-size:32px;}

&lt;/style&gt;
&lt;link rel='<a>stylesheet</a>' id='<a>twentytwenty-style-css</a>'  href='<a href="view-source:http://plugin-test.localhost/wp-content/themes/twentytwenty/style.css?ver=1.5">http://plugin-test.localhost/wp-content/themes/twentytwenty/style.css?ver=1.5</a>' media='<a>all</a>' /&gt;
&lt;style id='<a>twentytwenty-style-inline-css</a>'&gt;
.color-accent,.color-accent-hover:hover,.color-accent-hover:focus,:root .has-accent-color,.has-drop-cap:not(:focus):first-letter,.wp-block-button.is-style-outline,a { color: #cd2653; }blockquote,.border-color-accent,.border-color-accent-hover:hover,.border-color-accent-hover:focus { border-color: #cd2653; }button,.button,.faux-button,.wp-block-button__link,.wp-block-file .wp-block-file__button,input[type="button"],input[type="reset"],input[type="submit"],.bg-accent,.bg-accent-hover:hover,.bg-accent-hover:focus,:root .has-accent-background-color,.comment-reply-link { background-color: #cd2653; }.fill-children-accent,.fill-children-accent * { fill: #cd2653; }body,.entry-title a,:root .has-primary-color { color: #000000; }:root .has-primary-background-color { background-color: #000000; }cite,figcaption,.wp-caption-text,.post-meta,.entry-content .wp-block-archives li,.entry-content .wp-block-categories li,.entry-content .wp-block-latest-posts li,.wp-block-latest-comments__comment-date,.wp-block-latest-posts__post-date,.wp-block-embed figcaption,.wp-block-image figcaption,.wp-block-pullquote cite,.comment-metadata,.comment-respond .comment-notes,.comment-respond .logged-in-as,.pagination .dots,.entry-content hr:not(.has-background),hr.styled-separator,:root .has-secondary-color { color: #6d6d6d; }:root .has-secondary-background-color { background-color: #6d6d6d; }pre,fieldset,input,textarea,table,table *,hr { border-color: #dcd7ca; }caption,code,code,kbd,samp,.wp-block-table.is-style-stripes tbody tr:nth-child(odd),:root .has-subtle-background-background-color { background-color: #dcd7ca; }.wp-block-table.is-style-stripes { border-bottom-color: #dcd7ca; }.wp-block-latest-posts.is-grid li { border-top-color: #dcd7ca; }:root .has-subtle-background-color { color: #dcd7ca; }body:not(.overlay-header) .primary-menu &gt; li &gt; a,body:not(.overlay-header) .primary-menu &gt; li &gt; .icon,.modal-menu a,.footer-menu a, .footer-widgets a,#site-footer .wp-block-button.is-style-outline,.wp-block-pullquote:before,.singular:not(.overlay-header) .entry-header a,.archive-header a,.header-footer-group .color-accent,.header-footer-group .color-accent-hover:hover { color: #cd2653; }.social-icons a,#site-footer button:not(.toggle),#site-footer .button,#site-footer .faux-button,#site-footer .wp-block-button__link,#site-footer .wp-block-file__button,#site-footer input[type="button"],#site-footer input[type="reset"],#site-footer input[type="submit"] { background-color: #cd2653; }.header-footer-group,body:not(.overlay-header) #site-header .toggle,.menu-modal .toggle { color: #000000; }body:not(.overlay-header) .primary-menu ul { background-color: #000000; }body:not(.overlay-header) .primary-menu &gt; li &gt; ul:after { border-bottom-color: #000000; }body:not(.overlay-header) .primary-menu ul ul:after { border-left-color: #000000; }.site-description,body:not(.overlay-header) .toggle-inner .toggle-text,.widget .post-date,.widget .rss-date,.widget_archive li,.widget_categories li,.widget cite,.widget_pages li,.widget_meta li,.widget_nav_menu li,.powered-by-wordpress,.to-the-top,.singular .entry-header .post-meta,.singular:not(.overlay-header) .entry-header .post-meta a { color: #6d6d6d; }.header-footer-group pre,.header-footer-group fieldset,.header-footer-group input,.header-footer-group textarea,.header-footer-group table,.header-footer-group table *,.footer-nav-widgets-wrapper,#site-footer,.menu-modal nav *,.footer-widgets-outer-wrapper,.footer-top { border-color: #dcd7ca; }.header-footer-group table caption,body:not(.overlay-header) .header-inner .toggle-wrapper::before { background-color: #dcd7ca; }
&lt;/style&gt;
&lt;link rel='<a>stylesheet</a>' id='<a>twentytwenty-print-style-css</a>'  href='<a href="view-source:http://plugin-test.localhost/wp-content/themes/twentytwenty/print.css?ver=1.5">http://plugin-test.localhost/wp-content/themes/twentytwenty/print.css?ver=1.5</a>' media='<a>print</a>' /&gt;
&lt;script src='<a href="view-source:http://plugin-test.localhost/wp-content/themes/twentytwenty/assets/js/index.js?ver=1.5">http://plugin-test.localhost/wp-content/themes/twentytwenty/assets/js/index.js?ver=1.5</a>' id='<a>twentytwenty-js-js</a>' async&gt;&lt;/script&gt;
&lt;link rel="<a>https://api.w.org/</a>" href="<a href="view-source:http://plugin-test.localhost/wp-json/">http://plugin-test.localhost/wp-json/</a>" /&gt;&lt;link rel="<a>EditURI</a>" type="<a>application/rsd+xml</a>" title="<a>RSD</a>" href="<a href="view-source:http://plugin-test.localhost/xmlrpc.php?rsd">http://plugin-test.localhost/xmlrpc.php?rsd</a>" /&gt;
&lt;link rel="<a>wlwmanifest</a>" type="<a>application/wlwmanifest+xml</a>" href="<a href="view-source:http://plugin-test.localhost/wp-includes/wlwmanifest.xml">http://plugin-test.localhost/wp-includes/wlwmanifest.xml</a>" /&gt; 
&lt;meta name="<a>generator</a>" content="<a>WordPress 5.5.3</a>" /&gt;
	&lt;script&gt;document.documentElement.className = document.documentElement.className.replace( 'no-js', 'js' );&lt;/script&gt;
	&lt;style&gt;.recentcomments a{display:inline !important;padding:0 !important;margin:0 !important;}&lt;/style&gt;&lt;style media="<a>print</a>"&gt;#wpadminbar { display:none; }&lt;/style&gt;
	&lt;style media="<a>screen</a>"&gt;
	html { margin-top: 32px !important; }
	* html body { margin-top: 32px !important; }
	@media screen and ( max-width: 782px ) {
		html { margin-top: 46px !important; }
		* html body { margin-top: 46px !important; }
	}
&lt;/style&gt;
	
	&lt;/head&gt;

	&lt;body class="<a>home blog logged-in admin-bar no-customize-support wp-embed-responsive enable-search-modal has-no-pagination showing-comments show-avatars footer-top-visible</a>"&gt;

			&lt;script&gt;
		(function() {
			var request, b = document.body, c = 'className', cs = 'customize-support', rcs = new RegExp('(^|\\s+)(no-)?'+cs+'(\\s+|$)');

				request = true;
	
			b[c] = b[c].replace( rcs, ' ' );
			// The customizer requires postMessage and CORS (if the site is cross domain).
			b[c] += ( window.postMessage &amp;&amp; request ? ' ' : ' no-' ) + cs;
		}());
	&lt;/script&gt;
			&lt;div id="<a>wpadminbar</a>" class="<a>nojq nojs</a>"&gt;
							&lt;a class="<a>screen-reader-shortcut</a>" href="<a href="view-source:http://plugin-test.localhost/#wp-toolbar">#wp-toolbar</a>" tabindex="<a>1</a>"&gt;Skip to toolbar&lt;/a&gt;
						&lt;div class="<a>quicklinks</a>" id="<a>wp-toolbar</a>" role="<a>navigation</a>" aria-label="<a>Toolbar</a>"&gt;
				&lt;ul id='<a>wp-admin-bar-root-default</a>' class="<a>ab-top-menu</a>"&gt;&lt;li id='<a>wp-admin-bar-wp-logo</a>' class="<a>menupop</a>"&gt;&lt;a class='<a>ab-item</a>' aria-haspopup="<a>true</a>" href='<a href="view-source:http://plugin-test.localhost/wp-admin/about.php">http://plugin-test.localhost/wp-admin/about.php</a>'&gt;&lt;span class="<a>ab-icon</a>"&gt;&lt;/span&gt;&lt;span class="<a>screen-reader-text</a>"&gt;About WordPress&lt;/span&gt;&lt;/a&gt;&lt;div class="<a>ab-sub-wrapper</a>"&gt;&lt;ul id='<a>wp-admin-bar-wp-logo-default</a>' class="<a>ab-submenu</a>"&gt;&lt;li id='<a>wp-admin-bar-about</a>'&gt;&lt;a class='<a>ab-item</a>' href='<a href="view-source:http://plugin-test.localhost/wp-admin/about.php">http://plugin-test.localhost/wp-admin/about.php</a>'&gt;About WordPress&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;ul id='<a>wp-admin-bar-wp-logo-external</a>' class="<a>ab-sub-secondary ab-submenu</a>"&gt;&lt;li id='<a>wp-admin-bar-wporg</a>'&gt;&lt;a class='<a>ab-item</a>' href='<a href="view-source:https://wordpress.org/">https://wordpress.org/</a>'&gt;WordPress.org&lt;/a&gt;&lt;/li&gt;&lt;li id='<a>wp-admin-bar-documentation</a>'&gt;&lt;a class='<a>ab-item</a>' href='<a href="view-source:https://codex.wordpress.org/">https://codex.wordpress.org/</a>'&gt;Documentation&lt;/a&gt;&lt;/li&gt;&lt;li id='<a>wp-admin-bar-support-forums</a>'&gt;&lt;a class='<a>ab-item</a>' href='<a href="view-source:https://wordpress.org/support/">https://wordpress.org/support/</a>'&gt;Support&lt;/a&gt;&lt;/li&gt;&lt;li id='<a>wp-admin-bar-feedback</a>'&gt;&lt;a class='<a>ab-item</a>' href='<a href="view-source:https://wordpress.org/support/forum/requests-and-feedback">https://wordpress.org/support/forum/requests-and-feedback</a>'&gt;Feedback&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;&lt;/li&gt;&lt;li id='<a>wp-admin-bar-site-name</a>' class="<a>menupop</a>"&gt;&lt;a class='<a>ab-item</a>' aria-haspopup="<a>true</a>" href='<a href="view-source:http://plugin-test.localhost/wp-admin/">http://plugin-test.localhost/wp-admin/</a>'&gt;Plugin Test&lt;/a&gt;&lt;div class="<a>ab-sub-wrapper</a>"&gt;&lt;ul id='<a>wp-admin-bar-site-name-default</a>' class="<a>ab-submenu</a>"&gt;&lt;li id='<a>wp-admin-bar-dashboard</a>'&gt;&lt;a class='<a>ab-item</a>' href='<a href="view-source:http://plugin-test.localhost/wp-admin/">http://plugin-test.localhost/wp-admin/</a>'&gt;Dashboard&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;ul id='<a>wp-admin-bar-appearance</a>' class="<a>ab-submenu</a>"&gt;&lt;li id='<a>wp-admin-bar-themes</a>'&gt;&lt;a class='<a>ab-item</a>' href='<a href="view-source:http://plugin-test.localhost/wp-admin/themes.php">http://plugin-test.localhost/wp-admin/themes.php</a>'&gt;Themes&lt;/a&gt;&lt;/li&gt;&lt;li id='<a>wp-admin-bar-widgets</a>'&gt;&lt;a class='<a>ab-item</a>' href='<a href="view-source:http://plugin-test.localhost/wp-admin/themes.php?page=gutenberg-widgets">http://plugin-test.localhost/wp-admin/themes.php?page=gutenberg-widgets</a>'&gt;Widgets&lt;/a&gt;&lt;/li&gt;&lt;li id='<a>wp-admin-bar-menus</a>'&gt;&lt;a class='<a>ab-item</a>' href='<a href="view-source:http://plugin-test.localhost/wp-admin/nav-menus.php">http://plugin-test.localhost/wp-admin/nav-menus.php</a>'&gt;Menus&lt;/a&gt;&lt;/li&gt;&lt;li id='<a>wp-admin-bar-background</a>' class="<a>hide-if-customize</a>"&gt;&lt;a class='<a>ab-item</a>' href='<a href="view-source:http://plugin-test.localhost/wp-admin/themes.php?page=custom-background">http://plugin-test.localhost/wp-admin/themes.php?page=custom-background</a>'&gt;Background&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;&lt;/li&gt;&lt;li id='<a>wp-admin-bar-customize</a>' class="<a>hide-if-no-customize</a>"&gt;&lt;a class='<a>ab-item</a>' href='<a href="view-source:http://plugin-test.localhost/wp-admin/customize.php?url=http%3A%2F%2Fplugin-test.localhost%2F">http://plugin-test.localhost/wp-admin/customize.php?url=http%3A%2F%2Fplugin-test.localhost%2F</a>'&gt;Customize&lt;/a&gt;&lt;/li&gt;&lt;li id='<a>wp-admin-bar-comments</a>'&gt;&lt;a class='<a>ab-item</a>' href='<a href="view-source:http://plugin-test.localhost/wp-admin/edit-comments.php">http://plugin-test.localhost/wp-admin/edit-comments.php</a>'&gt;&lt;span class="<a>ab-icon</a>"&gt;&lt;/span&gt;&lt;span class="<a>ab-label awaiting-mod pending-count count-0</a>" aria-hidden="<a>true</a>"&gt;0&lt;/span&gt;&lt;span class="<a>screen-reader-text comments-in-moderation-text</a>"&gt;0 Comments in moderation&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;&lt;li id='<a>wp-admin-bar-new-content</a>' class="<a>menupop</a>"&gt;&lt;a class='<a>ab-item</a>' aria-haspopup="<a>true</a>" href='<a href="view-source:http://plugin-test.localhost/wp-admin/post-new.php">http://plugin-test.localhost/wp-admin/post-new.php</a>'&gt;&lt;span class="<a>ab-icon</a>"&gt;&lt;/span&gt;&lt;span class="<a>ab-label</a>"&gt;New&lt;/span&gt;&lt;/a&gt;&lt;div class="<a>ab-sub-wrapper</a>"&gt;&lt;ul id='<a>wp-admin-bar-new-content-default</a>' class="<a>ab-submenu</a>"&gt;&lt;li id='<a>wp-admin-bar-new-post</a>'&gt;&lt;a class='<a>ab-item</a>' href='<a href="view-source:http://plugin-test.localhost/wp-admin/post-new.php">http://plugin-test.localhost/wp-admin/post-new.php</a>'&gt;Post&lt;/a&gt;&lt;/li&gt;&lt;li id='<a>wp-admin-bar-new-media</a>'&gt;&lt;a class='<a>ab-item</a>' href='<a href="view-source:http://plugin-test.localhost/wp-admin/media-new.php">http://plugin-test.localhost/wp-admin/media-new.php</a>'&gt;Media&lt;/a&gt;&lt;/li&gt;&lt;li id='<a>wp-admin-bar-new-page</a>'&gt;&lt;a class='<a>ab-item</a>' href='<a href="view-source:http://plugin-test.localhost/wp-admin/post-new.php?post_type=page">http://plugin-test.localhost/wp-admin/post-new.php?post_type=page</a>'&gt;Page&lt;/a&gt;&lt;/li&gt;&lt;li id='<a>wp-admin-bar-new-user</a>'&gt;&lt;a class='<a>ab-item</a>' href='<a href="view-source:http://plugin-test.localhost/wp-admin/user-new.php">http://plugin-test.localhost/wp-admin/user-new.php</a>'&gt;User&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;&lt;/li&gt;&lt;/ul&gt;&lt;ul id='<a>wp-admin-bar-top-secondary</a>' class="<a>ab-top-secondary ab-top-menu</a>"&gt;&lt;li id='<a>wp-admin-bar-search</a>' class="<a>admin-bar-search</a>"&gt;&lt;div class="<a>ab-item ab-empty-item</a>" tabindex="<a>-1</a>"&gt;&lt;form action="<a href="view-source:http://plugin-test.localhost/">http://plugin-test.localhost/</a>" method="<a>get</a>" id="<a>adminbarsearch</a>"&gt;&lt;input class="<a>adminbar-input</a>" name="<a>s</a>" id="<a>adminbar-search</a>" type="<a>text</a>" value="" maxlength="<a>150</a>" /&gt;&lt;label for="<a>adminbar-search</a>" class="<a>screen-reader-text</a>"&gt;Search&lt;/label&gt;&lt;input type="<a>submit</a>" class="<a>adminbar-button</a>" value="<a>Search</a>"/&gt;&lt;/form&gt;&lt;/div&gt;&lt;/li&gt;&lt;li id='<a>wp-admin-bar-my-account</a>' class="<a>menupop with-avatar</a>"&gt;&lt;a class='<a>ab-item</a>' aria-haspopup="<a>true</a>" href='<a href="view-source:http://plugin-test.localhost/wp-admin/profile.php">http://plugin-test.localhost/wp-admin/profile.php</a>'&gt;Howdy, &lt;span class="<a>display-name</a>"&gt;admin&lt;/span&gt;&lt;img alt='' src='<a href="view-source:http://1.gravatar.com/avatar/77a591799c03c21b44b472e151bc8374?s=26&amp;d=mm&amp;r=g">http://1.gravatar.com/avatar/77a591799c03c21b44b472e151bc8374?s=26&amp;#038;d=mm&amp;#038;r=g</a>' srcset='<a>http://1.gravatar.com/avatar/77a591799c03c21b44b472e151bc8374?s=52&amp;#038;d=mm&amp;#038;r=g 2x</a>' class='<a>avatar avatar-26 photo</a>' height='<a>26</a>' width='<a>26</a>' loading='<a>lazy</a>'/&gt;&lt;/a&gt;&lt;div class="<a>ab-sub-wrapper</a>"&gt;&lt;ul id='<a>wp-admin-bar-user-actions</a>' class="<a>ab-submenu</a>"&gt;&lt;li id='<a>wp-admin-bar-user-info</a>'&gt;&lt;a class='<a>ab-item</a>' tabindex="<a>-1</a>" href='<a href="view-source:http://plugin-test.localhost/wp-admin/profile.php">http://plugin-test.localhost/wp-admin/profile.php</a>'&gt;&lt;img alt='' src='<a href="view-source:http://1.gravatar.com/avatar/77a591799c03c21b44b472e151bc8374?s=64&amp;d=mm&amp;r=g">http://1.gravatar.com/avatar/77a591799c03c21b44b472e151bc8374?s=64&amp;#038;d=mm&amp;#038;r=g</a>' srcset='<a>http://1.gravatar.com/avatar/77a591799c03c21b44b472e151bc8374?s=128&amp;#038;d=mm&amp;#038;r=g 2x</a>' class='<a>avatar avatar-64 photo</a>' height='<a>64</a>' width='<a>64</a>' loading='<a>lazy</a>'/&gt;&lt;span class='<a>display-name</a>'&gt;admin&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;&lt;li id='<a>wp-admin-bar-edit-profile</a>'&gt;&lt;a class='<a>ab-item</a>' href='<a href="view-source:http://plugin-test.localhost/wp-admin/profile.php">http://plugin-test.localhost/wp-admin/profile.php</a>'&gt;Edit Profile&lt;/a&gt;&lt;/li&gt;&lt;li id='<a>wp-admin-bar-logout</a>'&gt;&lt;a class='<a>ab-item</a>' href='<a href="view-source:http://plugin-test.localhost/wp-login.php?action=logout&amp;_wpnonce=2c655d3f1a">http://plugin-test.localhost/wp-login.php?action=logout&amp;#038;_wpnonce=2c655d3f1a</a>'&gt;Log Out&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;&lt;/li&gt;&lt;/ul&gt;			&lt;/div&gt;
						&lt;a class="<a>screen-reader-shortcut</a>" href="<a href="view-source:http://plugin-test.localhost/wp-login.php?action=logout&amp;_wpnonce=2c655d3f1a">http://plugin-test.localhost/wp-login.php?action=logout&amp;#038;_wpnonce=2c655d3f1a</a>"&gt;Log Out&lt;/a&gt;
					&lt;/div&gt;

		&lt;a class="<a>skip-link screen-reader-text</a>" href="<a href="view-source:http://plugin-test.localhost/#site-content">#site-content</a>"&gt;Skip to the content&lt;/a&gt;
		&lt;header id="<a>site-header</a>" class="<a>header-footer-group</a>" role="<a>banner</a>"&gt;

			&lt;div class="<a>header-inner section-inner</a>"&gt;

				&lt;div class="<a>header-titles-wrapper</a>"&gt;

					
						&lt;button class="<a>toggle search-toggle mobile-search-toggle</a>" data-toggle-target="<a>.search-modal</a>" data-toggle-body-class="<a>showing-search-modal</a>" data-set-focus="<a>.search-modal .search-field</a>" aria-expanded="<a>false</a>"&gt;
							&lt;span class="<a>toggle-inner</a>"&gt;
								&lt;span class="<a>toggle-icon</a>"&gt;
									&lt;svg class="<a>svg-icon</a>" aria-hidden="<a>true</a>" role="<a>img</a>" focusable="<a>false</a>" xmlns="<a>http://www.w3.org/2000/svg</a>" width="<a>23</a>" height="<a>23</a>" viewBox="<a>0 0 23 23</a>"&gt;&lt;path d="<a>M38.710696,48.0601792 L43,52.3494831 L41.3494831,54 L37.0601792,49.710696 C35.2632422,51.1481185 32.9839107,52.0076499 30.5038249,52.0076499 C24.7027226,52.0076499 20,47.3049272 20,41.5038249 C20,35.7027226 24.7027226,31 30.5038249,31 C36.3049272,31 41.0076499,35.7027226 41.0076499,41.5038249 C41.0076499,43.9839107 40.1481185,46.2632422 38.710696,48.0601792 Z M36.3875844,47.1716785 C37.8030221,45.7026647 38.6734666,43.7048964 38.6734666,41.5038249 C38.6734666,36.9918565 35.0157934,33.3341833 30.5038249,33.3341833 C25.9918565,33.3341833 22.3341833,36.9918565 22.3341833,41.5038249 C22.3341833,46.0157934 25.9918565,49.6734666 30.5038249,49.6734666 C32.7048964,49.6734666 34.7026647,48.8030221 36.1716785,47.3875844 C36.2023931,47.347638 36.2360451,47.3092237 36.2726343,47.2726343 C36.3092237,47.2360451 36.347638,47.2023931 36.3875844,47.1716785 Z</a>" transform="<a>translate(-20 -31)</a>" /&gt;&lt;/svg&gt;								&lt;/span&gt;
								&lt;span class="<a>toggle-text</a>"&gt;Search&lt;/span&gt;
							&lt;/span&gt;
						&lt;/button&gt;&lt;!-- .search-toggle --&gt;

					
					&lt;div class="<a>header-titles</a>"&gt;

						&lt;h1 class="<a>site-title</a>"&gt;&lt;a href="<a href="view-source:http://plugin-test.localhost/">http://plugin-test.localhost/</a>"&gt;Plugin Test&lt;/a&gt;&lt;/h1&gt;&lt;div class="<a>site-description</a>"&gt;Just another WordPress site&lt;/div&gt;&lt;!-- .site-description --&gt;
					&lt;/div&gt;&lt;!-- .header-titles --&gt;

					&lt;button class="<a>toggle nav-toggle mobile-nav-toggle</a>" data-toggle-target="<a>.menu-modal</a>"  data-toggle-body-class="<a>showing-menu-modal</a>" aria-expanded="<a>false</a>" data-set-focus="<a>.close-nav-toggle</a>"&gt;
						&lt;span class="<a>toggle-inner</a>"&gt;
							&lt;span class="<a>toggle-icon</a>"&gt;
								&lt;svg class="<a>svg-icon</a>" aria-hidden="<a>true</a>" role="<a>img</a>" focusable="<a>false</a>" xmlns="<a>http://www.w3.org/2000/svg</a>" width="<a>26</a>" height="<a>7</a>" viewBox="<a>0 0 26 7</a>"&gt;&lt;path fill-rule="<a>evenodd</a>" d="<a>M332.5,45 C330.567003,45 329,43.4329966 329,41.5 C329,39.5670034 330.567003,38 332.5,38 C334.432997,38 336,39.5670034 336,41.5 C336,43.4329966 334.432997,45 332.5,45 Z M342,45 C340.067003,45 338.5,43.4329966 338.5,41.5 C338.5,39.5670034 340.067003,38 342,38 C343.932997,38 345.5,39.5670034 345.5,41.5 C345.5,43.4329966 343.932997,45 342,45 Z M351.5,45 C349.567003,45 348,43.4329966 348,41.5 C348,39.5670034 349.567003,38 351.5,38 C353.432997,38 355,39.5670034 355,41.5 C355,43.4329966 353.432997,45 351.5,45 Z</a>" transform="<a>translate(-329 -38)</a>" /&gt;&lt;/svg&gt;							&lt;/span&gt;
							&lt;span class="<a>toggle-text</a>"&gt;Menu&lt;/span&gt;
						&lt;/span&gt;
					&lt;/button&gt;&lt;!-- .nav-toggle --&gt;

				&lt;/div&gt;&lt;!-- .header-titles-wrapper --&gt;

				&lt;div class="<a>header-navigation-wrapper</a>"&gt;

					
							&lt;nav class="<a>primary-menu-wrapper</a>" aria-label="<a>Horizontal</a>" role="<a>navigation</a>"&gt;

								&lt;ul class="<a>primary-menu reset-list-style</a>"&gt;

								&lt;li class="<a>page_item page-item-2</a>"&gt;&lt;a href="<a href="view-source:http://plugin-test.localhost/sample-page/">http://plugin-test.localhost/sample-page/</a>"&gt;Sample Page&lt;/a&gt;&lt;/li&gt;

								&lt;/ul&gt;

							&lt;/nav&gt;&lt;!-- .primary-menu-wrapper --&gt;

						
						&lt;div class="<a>header-toggles hide-no-js</a>"&gt;

						
							&lt;div class="<a>toggle-wrapper search-toggle-wrapper</a>"&gt;

								&lt;button class="<a>toggle search-toggle desktop-search-toggle</a>" data-toggle-target="<a>.search-modal</a>" data-toggle-body-class="<a>showing-search-modal</a>" data-set-focus="<a>.search-modal .search-field</a>" aria-expanded="<a>false</a>"&gt;
									&lt;span class="<a>toggle-inner</a>"&gt;
										&lt;svg class="<a>svg-icon</a>" aria-hidden="<a>true</a>" role="<a>img</a>" focusable="<a>false</a>" xmlns="<a>http://www.w3.org/2000/svg</a>" width="<a>23</a>" height="<a>23</a>" viewBox="<a>0 0 23 23</a>"&gt;&lt;path d="<a>M38.710696,48.0601792 L43,52.3494831 L41.3494831,54 L37.0601792,49.710696 C35.2632422,51.1481185 32.9839107,52.0076499 30.5038249,52.0076499 C24.7027226,52.0076499 20,47.3049272 20,41.5038249 C20,35.7027226 24.7027226,31 30.5038249,31 C36.3049272,31 41.0076499,35.7027226 41.0076499,41.5038249 C41.0076499,43.9839107 40.1481185,46.2632422 38.710696,48.0601792 Z M36.3875844,47.1716785 C37.8030221,45.7026647 38.6734666,43.7048964 38.6734666,41.5038249 C38.6734666,36.9918565 35.0157934,33.3341833 30.5038249,33.3341833 C25.9918565,33.3341833 22.3341833,36.9918565 22.3341833,41.5038249 C22.3341833,46.0157934 25.9918565,49.6734666 30.5038249,49.6734666 C32.7048964,49.6734666 34.7026647,48.8030221 36.1716785,47.3875844 C36.2023931,47.347638 36.2360451,47.3092237 36.2726343,47.2726343 C36.3092237,47.2360451 36.347638,47.2023931 36.3875844,47.1716785 Z</a>" transform="<a>translate(-20 -31)</a>" /&gt;&lt;/svg&gt;										&lt;span class="<a>toggle-text</a>"&gt;Search&lt;/span&gt;
									&lt;/span&gt;
								&lt;/button&gt;&lt;!-- .search-toggle --&gt;

							&lt;/div&gt;

							
						&lt;/div&gt;&lt;!-- .header-toggles --&gt;
						
				&lt;/div&gt;&lt;!-- .header-navigation-wrapper --&gt;

			&lt;/div&gt;&lt;!-- .header-inner --&gt;

			&lt;div class="<a>search-modal cover-modal header-footer-group</a>" data-modal-target-string="<a>.search-modal</a>"&gt;

	&lt;div class="<a>search-modal-inner modal-inner</a>"&gt;

		&lt;div class="<a>section-inner</a>"&gt;

			&lt;form role="<a>search</a>" aria-label="<a>Search for:</a>" method="<a>get</a>" class="<a>search-form</a>" action="<a href="view-source:http://plugin-test.localhost/">http://plugin-test.localhost/</a>"&gt;
	&lt;label for="<a>search-form-1</a>"&gt;
		&lt;span class="<a>screen-reader-text</a>"&gt;Search for:&lt;/span&gt;
		&lt;input type="<a>search</a>" id="<a>search-form-1</a>" class="<a>search-field</a>" placeholder="<a>Search &amp;hellip;</a>" value="" name="<a>s</a>" /&gt;
	&lt;/label&gt;
	&lt;input type="<a>submit</a>" class="<a>search-submit</a>" value="<a>Search</a>" /&gt;
&lt;/form&gt;

			&lt;button class="<a>toggle search-untoggle close-search-toggle fill-children-current-color</a>" data-toggle-target="<a>.search-modal</a>" data-toggle-body-class="<a>showing-search-modal</a>" data-set-focus="<a>.search-modal .search-field</a>" aria-expanded="<a>false</a>"&gt;
				&lt;span class="<a>screen-reader-text</a>"&gt;Close search&lt;/span&gt;
				&lt;svg class="<a>svg-icon</a>" aria-hidden="<a>true</a>" role="<a>img</a>" focusable="<a>false</a>" xmlns="<a>http://www.w3.org/2000/svg</a>" width="<a>16</a>" height="<a>16</a>" viewBox="<a>0 0 16 16</a>"&gt;&lt;polygon fill="" fill-rule="<a>evenodd</a>" points="<a>6.852 7.649 .399 1.195 1.445 .149 7.899 6.602 14.352 .149 15.399 1.195 8.945 7.649 15.399 14.102 14.352 15.149 7.899 8.695 1.445 15.149 .399 14.102</a>" /&gt;&lt;/svg&gt;			&lt;/button&gt;&lt;!-- .search-toggle --&gt;

		&lt;/div&gt;&lt;!-- .section-inner --&gt;

	&lt;/div&gt;&lt;!-- .search-modal-inner --&gt;

&lt;/div&gt;&lt;!-- .menu-modal --&gt;

		&lt;/header&gt;&lt;!-- #site-header --&gt;

		
&lt;div class="<a>menu-modal cover-modal header-footer-group</a>" data-modal-target-string="<a>.menu-modal</a>"&gt;

	&lt;div class="<a>menu-modal-inner modal-inner</a>"&gt;

		&lt;div class="<a>menu-wrapper section-inner</a>"&gt;

			&lt;div class="<a>menu-top</a>"&gt;

				&lt;button class="<a>toggle close-nav-toggle fill-children-current-color</a>" data-toggle-target="<a>.menu-modal</a>" data-toggle-body-class="<a>showing-menu-modal</a>" aria-expanded="<a>false</a>" data-set-focus="<a>.menu-modal</a>"&gt;
					&lt;span class="<a>toggle-text</a>"&gt;Close Menu&lt;/span&gt;
					&lt;svg class="<a>svg-icon</a>" aria-hidden="<a>true</a>" role="<a>img</a>" focusable="<a>false</a>" xmlns="<a>http://www.w3.org/2000/svg</a>" width="<a>16</a>" height="<a>16</a>" viewBox="<a>0 0 16 16</a>"&gt;&lt;polygon fill="" fill-rule="<a>evenodd</a>" points="<a>6.852 7.649 .399 1.195 1.445 .149 7.899 6.602 14.352 .149 15.399 1.195 8.945 7.649 15.399 14.102 14.352 15.149 7.899 8.695 1.445 15.149 .399 14.102</a>" /&gt;&lt;/svg&gt;				&lt;/button&gt;&lt;!-- .nav-toggle --&gt;

				
					&lt;nav class="<a>mobile-menu</a>" aria-label="<a>Mobile</a>" role="<a>navigation</a>"&gt;

						&lt;ul class="<a>modal-menu reset-list-style</a>"&gt;

						&lt;li class="<a>page_item page-item-2</a>"&gt;&lt;div class="<a>ancestor-wrapper</a>"&gt;&lt;a href="<a href="view-source:http://plugin-test.localhost/sample-page/">http://plugin-test.localhost/sample-page/</a>"&gt;Sample Page&lt;/a&gt;&lt;/div&gt;&lt;!-- .ancestor-wrapper --&gt;&lt;/li&gt;

						&lt;/ul&gt;

					&lt;/nav&gt;

					
			&lt;/div&gt;&lt;!-- .menu-top --&gt;

			&lt;div class="<a>menu-bottom</a>"&gt;

				
			&lt;/div&gt;&lt;!-- .menu-bottom --&gt;

		&lt;/div&gt;&lt;!-- .menu-wrapper --&gt;

	&lt;/div&gt;&lt;!-- .menu-modal-inner --&gt;

&lt;/div&gt;&lt;!-- .menu-modal --&gt;

&lt;main id="<a>site-content</a>" role="<a>main</a>"&gt;

	
&lt;article class="<a>post-1 post type-post status-publish format-standard hentry category-uncategorized</a>" id="<a>post-1</a>"&gt;

	
&lt;header class="<a>entry-header has-text-align-center</a>"&gt;

	&lt;div class="<a>entry-header-inner section-inner medium</a>"&gt;

		
			&lt;div class="<a>entry-categories</a>"&gt;
				&lt;span class="<a>screen-reader-text</a>"&gt;Categories&lt;/span&gt;
				&lt;div class="<a>entry-categories-inner</a>"&gt;
					&lt;a href="<a href="view-source:http://plugin-test.localhost/category/uncategorized/">http://plugin-test.localhost/category/uncategorized/</a>" rel="<a>category tag</a>"&gt;Uncategorized&lt;/a&gt;				&lt;/div&gt;&lt;!-- .entry-categories-inner --&gt;
			&lt;/div&gt;&lt;!-- .entry-categories --&gt;

			&lt;h2 class="<a>entry-title heading-size-1</a>"&gt;&lt;a href="<a href="view-source:http://plugin-test.localhost/2020/10/27/hello-world/">http://plugin-test.localhost/2020/10/27/hello-world/</a>"&gt;Hello world!&lt;/a&gt;&lt;/h2&gt;
		&lt;div class="<a>post-meta-wrapper post-meta-single post-meta-single-top</a>"&gt;

			&lt;ul class="<a>post-meta</a>"&gt;

									&lt;li class="<a>post-author meta-wrapper</a>"&gt;
						&lt;span class="<a>meta-icon</a>"&gt;
							&lt;span class="<a>screen-reader-text</a>"&gt;Post author&lt;/span&gt;
							&lt;svg class="<a>svg-icon</a>" aria-hidden="<a>true</a>" role="<a>img</a>" focusable="<a>false</a>" xmlns="<a>http://www.w3.org/2000/svg</a>" width="<a>18</a>" height="<a>20</a>" viewBox="<a>0 0 18 20</a>"&gt;&lt;path fill="" d="<a>M18,19 C18,19.5522847 17.5522847,20 17,20 C16.4477153,20 16,19.5522847 16,19 L16,17 C16,15.3431458 14.6568542,14 13,14 L5,14 C3.34314575,14 2,15.3431458 2,17 L2,19 C2,19.5522847 1.55228475,20 1,20 C0.44771525,20 0,19.5522847 0,19 L0,17 C0,14.2385763 2.23857625,12 5,12 L13,12 C15.7614237,12 18,14.2385763 18,17 L18,19 Z M9,10 C6.23857625,10 4,7.76142375 4,5 C4,2.23857625 6.23857625,0 9,0 C11.7614237,0 14,2.23857625 14,5 C14,7.76142375 11.7614237,10 9,10 Z M9,8 C10.6568542,8 12,6.65685425 12,5 C12,3.34314575 10.6568542,2 9,2 C7.34314575,2 6,3.34314575 6,5 C6,6.65685425 7.34314575,8 9,8 Z</a>" /&gt;&lt;/svg&gt;						&lt;/span&gt;
						&lt;span class="<a>meta-text</a>"&gt;
							By &lt;a href="<a href="view-source:http://plugin-test.localhost/author/admin/">http://plugin-test.localhost/author/admin/</a>"&gt;admin&lt;/a&gt;						&lt;/span&gt;
					&lt;/li&gt;
										&lt;li class="<a>post-date meta-wrapper</a>"&gt;
						&lt;span class="<a>meta-icon</a>"&gt;
							&lt;span class="<a>screen-reader-text</a>"&gt;Post date&lt;/span&gt;
							&lt;svg class="<a>svg-icon</a>" aria-hidden="<a>true</a>" role="<a>img</a>" focusable="<a>false</a>" xmlns="<a>http://www.w3.org/2000/svg</a>" width="<a>18</a>" height="<a>19</a>" viewBox="<a>0 0 18 19</a>"&gt;&lt;path fill="" d="<a>M4.60069444,4.09375 L3.25,4.09375 C2.47334957,4.09375 1.84375,4.72334957 1.84375,5.5 L1.84375,7.26736111 L16.15625,7.26736111 L16.15625,5.5 C16.15625,4.72334957 15.5266504,4.09375 14.75,4.09375 L13.3993056,4.09375 L13.3993056,4.55555556 C13.3993056,5.02154581 13.0215458,5.39930556 12.5555556,5.39930556 C12.0895653,5.39930556 11.7118056,5.02154581 11.7118056,4.55555556 L11.7118056,4.09375 L6.28819444,4.09375 L6.28819444,4.55555556 C6.28819444,5.02154581 5.9104347,5.39930556 5.44444444,5.39930556 C4.97845419,5.39930556 4.60069444,5.02154581 4.60069444,4.55555556 L4.60069444,4.09375 Z M6.28819444,2.40625 L11.7118056,2.40625 L11.7118056,1 C11.7118056,0.534009742 12.0895653,0.15625 12.5555556,0.15625 C13.0215458,0.15625 13.3993056,0.534009742 13.3993056,1 L13.3993056,2.40625 L14.75,2.40625 C16.4586309,2.40625 17.84375,3.79136906 17.84375,5.5 L17.84375,15.875 C17.84375,17.5836309 16.4586309,18.96875 14.75,18.96875 L3.25,18.96875 C1.54136906,18.96875 0.15625,17.5836309 0.15625,15.875 L0.15625,5.5 C0.15625,3.79136906 1.54136906,2.40625 3.25,2.40625 L4.60069444,2.40625 L4.60069444,1 C4.60069444,0.534009742 4.97845419,0.15625 5.44444444,0.15625 C5.9104347,0.15625 6.28819444,0.534009742 6.28819444,1 L6.28819444,2.40625 Z M1.84375,8.95486111 L1.84375,15.875 C1.84375,16.6516504 2.47334957,17.28125 3.25,17.28125 L14.75,17.28125 C15.5266504,17.28125 16.15625,16.6516504 16.15625,15.875 L16.15625,8.95486111 L1.84375,8.95486111 Z</a>" /&gt;&lt;/svg&gt;						&lt;/span&gt;
						&lt;span class="<a>meta-text</a>"&gt;
							&lt;a href="<a href="view-source:http://plugin-test.localhost/2020/10/27/hello-world/">http://plugin-test.localhost/2020/10/27/hello-world/</a>"&gt;October 27, 2020&lt;/a&gt;
						&lt;/span&gt;
					&lt;/li&gt;
										&lt;li class="<a>post-comment-link meta-wrapper</a>"&gt;
						&lt;span class="<a>meta-icon</a>"&gt;
							&lt;svg class="<a>svg-icon</a>" aria-hidden="<a>true</a>" role="<a>img</a>" focusable="<a>false</a>" xmlns="<a>http://www.w3.org/2000/svg</a>" width="<a>19</a>" height="<a>19</a>" viewBox="<a>0 0 19 19</a>"&gt;&lt;path d="<a>M9.43016863,13.2235931 C9.58624731,13.094699 9.7823475,13.0241935 9.98476849,13.0241935 L15.0564516,13.0241935 C15.8581553,13.0241935 16.5080645,12.3742843 16.5080645,11.5725806 L16.5080645,3.44354839 C16.5080645,2.64184472 15.8581553,1.99193548 15.0564516,1.99193548 L3.44354839,1.99193548 C2.64184472,1.99193548 1.99193548,2.64184472 1.99193548,3.44354839 L1.99193548,11.5725806 C1.99193548,12.3742843 2.64184472,13.0241935 3.44354839,13.0241935 L5.76612903,13.0241935 C6.24715123,13.0241935 6.63709677,13.4141391 6.63709677,13.8951613 L6.63709677,15.5301903 L9.43016863,13.2235931 Z M3.44354839,14.766129 C1.67980032,14.766129 0.25,13.3363287 0.25,11.5725806 L0.25,3.44354839 C0.25,1.67980032 1.67980032,0.25 3.44354839,0.25 L15.0564516,0.25 C16.8201997,0.25 18.25,1.67980032 18.25,3.44354839 L18.25,11.5725806 C18.25,13.3363287 16.8201997,14.766129 15.0564516,14.766129 L10.2979143,14.766129 L6.32072889,18.0506004 C5.75274472,18.5196577 4.89516129,18.1156602 4.89516129,17.3790323 L4.89516129,14.766129 L3.44354839,14.766129 Z</a>" /&gt;&lt;/svg&gt;						&lt;/span&gt;
						&lt;span class="<a>meta-text</a>"&gt;
							&lt;a href="<a href="view-source:http://plugin-test.localhost/2020/10/27/hello-world/#comments">http://plugin-test.localhost/2020/10/27/hello-world/#comments</a>"&gt;1 Comment&lt;span class="<a>screen-reader-text</a>"&gt; on Hello world!&lt;/span&gt;&lt;/a&gt;						&lt;/span&gt;
					&lt;/li&gt;
					
			&lt;/ul&gt;&lt;!-- .post-meta --&gt;

		&lt;/div&gt;&lt;!-- .post-meta-wrapper --&gt;

		
	&lt;/div&gt;&lt;!-- .entry-header-inner --&gt;

&lt;/header&gt;&lt;!-- .entry-header --&gt;

	&lt;div class="<a>post-inner thin </a>"&gt;

		&lt;div class="<a>entry-content</a>"&gt;

			
&lt;p&gt;Welcome to WordPress. This is your first post. Edit or delete it, then start writing!&lt;/p&gt;

		&lt;/div&gt;&lt;!-- .entry-content --&gt;

	&lt;/div&gt;&lt;!-- .post-inner --&gt;

	&lt;div class="<a>section-inner</a>"&gt;
		&lt;div class="<a>post-meta-wrapper post-meta-edit-link-wrapper</a>"&gt;&lt;ul class="<a>post-meta</a>"&gt;&lt;li class="<a>post-edit meta-wrapper</a>"&gt;&lt;span class="<a>meta-icon</a>"&gt;&lt;svg class="<a>svg-icon</a>" aria-hidden="<a>true</a>" role="<a>img</a>" focusable="<a>false</a>" xmlns="<a>http://www.w3.org/2000/svg</a>" width="<a>18</a>" height="<a>18</a>" viewBox="<a>0 0 18 18</a>"&gt;&lt;path fill="" d="<a>M14.7272727,11.1763636 C14.7272727,10.7244943 15.0935852,10.3581818 15.5454545,10.3581818 C15.9973239,10.3581818 16.3636364,10.7244943 16.3636364,11.1763636 L16.3636364,15.5454545 C16.3636364,16.9010626 15.2646989,18 13.9090909,18 L2.45454545,18 C1.09893743,18 0,16.9010626 0,15.5454545 L0,4.09090909 C0,2.73530107 1.09893743,1.63636364 2.45454545,1.63636364 L6.82363636,1.63636364 C7.2755057,1.63636364 7.64181818,2.00267611 7.64181818,2.45454545 C7.64181818,2.9064148 7.2755057,3.27272727 6.82363636,3.27272727 L2.45454545,3.27272727 C2.00267611,3.27272727 1.63636364,3.63903975 1.63636364,4.09090909 L1.63636364,15.5454545 C1.63636364,15.9973239 2.00267611,16.3636364 2.45454545,16.3636364 L13.9090909,16.3636364 C14.3609602,16.3636364 14.7272727,15.9973239 14.7272727,15.5454545 L14.7272727,11.1763636 Z M6.54545455,9.33890201 L6.54545455,11.4545455 L8.66109799,11.4545455 L16.0247344,4.09090909 L13.9090909,1.97526564 L6.54545455,9.33890201 Z M14.4876328,0.239639906 L17.7603601,3.51236718 C18.07988,3.83188705 18.07988,4.34993113 17.7603601,4.669451 L9.57854191,12.8512692 C9.42510306,13.004708 9.21699531,13.0909091 9,13.0909091 L5.72727273,13.0909091 C5.27540339,13.0909091 4.90909091,12.7245966 4.90909091,12.2727273 L4.90909091,9 C4.90909091,8.78300469 4.99529196,8.57489694 5.14873082,8.42145809 L13.330549,0.239639906 C13.6500689,-0.0798799688 14.1681129,-0.0798799688 14.4876328,0.239639906 Z</a>" /&gt;&lt;/svg&gt;&lt;/span&gt;&lt;span class="<a>meta-text</a>"&gt;&lt;a href="<a href="view-source:http://plugin-test.localhost/wp-admin/post.php?post=1&amp;action=edit">http://plugin-test.localhost/wp-admin/post.php?post=1&amp;#038;action=edit</a>"&gt;Edit &lt;span class="<a>screen-reader-text</a>"&gt;Hello world!&lt;/span&gt;&lt;/a&gt;&lt;/span&gt;&lt;/li&gt;&lt;/ul&gt;&lt;!-- .post-meta --&gt;&lt;/div&gt;&lt;!-- .post-meta-wrapper --&gt;
	&lt;/div&gt;&lt;!-- .section-inner --&gt;

	
&lt;/article&gt;&lt;!-- .post --&gt;

	
&lt;/main&gt;&lt;!-- #site-content --&gt;


	&lt;div class="<a>footer-nav-widgets-wrapper header-footer-group</a>"&gt;

		&lt;div class="<a>footer-inner section-inner</a>"&gt;

			
			
				&lt;aside class="<a>footer-widgets-outer-wrapper</a>" role="<a>complementary</a>"&gt;

					&lt;div class="<a>footer-widgets-wrapper</a>"&gt;

						
							&lt;div class="<a>footer-widgets column-one grid-item</a>"&gt;
								&lt;div class="<a>widget widget_search</a>"&gt;&lt;div class="<a>widget-content</a>"&gt;&lt;form role="<a>search</a>"  method="<a>get</a>" class="<a>search-form</a>" action="<a href="view-source:http://plugin-test.localhost/">http://plugin-test.localhost/</a>"&gt;
	&lt;label for="<a>search-form-2</a>"&gt;
		&lt;span class="<a>screen-reader-text</a>"&gt;Search for:&lt;/span&gt;
		&lt;input type="<a>search</a>" id="<a>search-form-2</a>" class="<a>search-field</a>" placeholder="<a>Search &amp;hellip;</a>" value="" name="<a>s</a>" /&gt;
	&lt;/label&gt;
	&lt;input type="<a>submit</a>" class="<a>search-submit</a>" value="<a>Search</a>" /&gt;
&lt;/form&gt;
&lt;/div&gt;&lt;/div&gt;
		&lt;div class="<a>widget widget_recent_entries</a>"&gt;&lt;div class="<a>widget-content</a>"&gt;
		&lt;h2 class="<a>widget-title subheading heading-size-3</a>"&gt;Recent Posts&lt;/h2&gt;
		&lt;ul&gt;
											&lt;li&gt;
					&lt;a href="<a href="view-source:http://plugin-test.localhost/2020/10/27/hello-world/">http://plugin-test.localhost/2020/10/27/hello-world/</a>"&gt;Hello world!&lt;/a&gt;
									&lt;/li&gt;
					&lt;/ul&gt;

		&lt;/div&gt;&lt;/div&gt;&lt;div class="<a>widget widget_recent_comments</a>"&gt;&lt;div class="<a>widget-content</a>"&gt;&lt;h2 class="<a>widget-title subheading heading-size-3</a>"&gt;Recent Comments&lt;/h2&gt;&lt;ul id="<a>recentcomments</a>"&gt;&lt;li class="<a>recentcomments</a>"&gt;&lt;span class="<a>comment-author-link</a>"&gt;&lt;a href='<a href="view-source:https://wordpress.org/">https://wordpress.org/</a>' rel='<a>external nofollow ugc</a>' class='<a>url</a>'&gt;A WordPress Commenter&lt;/a&gt;&lt;/span&gt; on &lt;a href="<a href="view-source:http://plugin-test.localhost/2020/10/27/hello-world/#comment-1">http://plugin-test.localhost/2020/10/27/hello-world/#comment-1</a>"&gt;Hello world!&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;&lt;/div&gt;							&lt;/div&gt;

						
						
							&lt;div class="<a>footer-widgets column-two grid-item</a>"&gt;
								&lt;div class="<a>widget widget_archive</a>"&gt;&lt;div class="<a>widget-content</a>"&gt;&lt;h2 class="<a>widget-title subheading heading-size-3</a>"&gt;Archives&lt;/h2&gt;
			&lt;ul&gt;
					&lt;li&gt;&lt;a href='<a href="view-source:http://plugin-test.localhost/2020/10/">http://plugin-test.localhost/2020/10/</a>'&gt;October 2020&lt;/a&gt;&lt;/li&gt;
			&lt;/ul&gt;

			&lt;/div&gt;&lt;/div&gt;&lt;div class="<a>widget widget_categories</a>"&gt;&lt;div class="<a>widget-content</a>"&gt;&lt;h2 class="<a>widget-title subheading heading-size-3</a>"&gt;Categories&lt;/h2&gt;
			&lt;ul&gt;
					&lt;li class="<a>cat-item cat-item-1</a>"&gt;&lt;a href="<a href="view-source:http://plugin-test.localhost/category/uncategorized/">http://plugin-test.localhost/category/uncategorized/</a>"&gt;Uncategorized&lt;/a&gt;
&lt;/li&gt;
			&lt;/ul&gt;

			&lt;/div&gt;&lt;/div&gt;&lt;div class="<a>widget widget_meta</a>"&gt;&lt;div class="<a>widget-content</a>"&gt;&lt;h2 class="<a>widget-title subheading heading-size-3</a>"&gt;Meta&lt;/h2&gt;
		&lt;ul&gt;
			&lt;li&gt;&lt;a href="<a href="view-source:http://plugin-test.localhost/wp-admin/">http://plugin-test.localhost/wp-admin/</a>"&gt;Site Admin&lt;/a&gt;&lt;/li&gt;			&lt;li&gt;&lt;a href="<a href="view-source:http://plugin-test.localhost/wp-login.php?action=logout&amp;_wpnonce=2c655d3f1a">http://plugin-test.localhost/wp-login.php?action=logout&amp;#038;_wpnonce=2c655d3f1a</a>"&gt;Log out&lt;/a&gt;&lt;/li&gt;
			&lt;li&gt;&lt;a href="<a href="view-source:http://plugin-test.localhost/feed/">http://plugin-test.localhost/feed/</a>"&gt;Entries feed&lt;/a&gt;&lt;/li&gt;
			&lt;li&gt;&lt;a href="<a href="view-source:http://plugin-test.localhost/comments/feed/">http://plugin-test.localhost/comments/feed/</a>"&gt;Comments feed&lt;/a&gt;&lt;/li&gt;

			&lt;li&gt;&lt;a href="<a href="view-source:https://wordpress.org/">https://wordpress.org/</a>"&gt;WordPress.org&lt;/a&gt;&lt;/li&gt;
		&lt;/ul&gt;

		&lt;/div&gt;&lt;/div&gt;							&lt;/div&gt;

						
					&lt;/div&gt;&lt;!-- .footer-widgets-wrapper --&gt;

				&lt;/aside&gt;&lt;!-- .footer-widgets-outer-wrapper --&gt;

			
		&lt;/div&gt;&lt;!-- .footer-inner --&gt;

	&lt;/div&gt;&lt;!-- .footer-nav-widgets-wrapper --&gt;


			&lt;footer id="<a>site-footer</a>" role="<a>contentinfo</a>" class="<a>header-footer-group</a>"&gt;

				&lt;div class="<a>section-inner</a>"&gt;

					&lt;div class="<a>footer-credits</a>"&gt;

						&lt;p class="<a>footer-copyright</a>"&gt;&amp;copy;
							2020							&lt;a href="<a href="view-source:http://plugin-test.localhost/">http://plugin-test.localhost/</a>"&gt;Plugin Test&lt;/a&gt;
						&lt;/p&gt;&lt;!-- .footer-copyright --&gt;

						&lt;p class="<a>powered-by-wordpress</a>"&gt;
							&lt;a href="<a href="view-source:https://wordpress.org/">https://wordpress.org/</a>"&gt;
								Powered by WordPress							&lt;/a&gt;
						&lt;/p&gt;&lt;!-- .powered-by-wordpress --&gt;

					&lt;/div&gt;&lt;!-- .footer-credits --&gt;

					&lt;a class="<a>to-the-top</a>" href="<a href="view-source:http://plugin-test.localhost/#site-header">#site-header</a>"&gt;
						&lt;span class="<a>to-the-top-long</a>"&gt;
							To the top &lt;span class="<a>arrow</a>" aria-hidden="<a>true</a>"&gt;&amp;uarr;&lt;/span&gt;						&lt;/span&gt;&lt;!-- .to-the-top-long --&gt;
						&lt;span class="<a>to-the-top-short</a>"&gt;
							Up &lt;span class="<a>arrow</a>" aria-hidden="<a>true</a>"&gt;&amp;uarr;&lt;/span&gt;						&lt;/span&gt;&lt;!-- .to-the-top-short --&gt;
					&lt;/a&gt;&lt;!-- .to-the-top --&gt;

				&lt;/div&gt;&lt;!-- .section-inner --&gt;

			&lt;/footer&gt;&lt;!-- #site-footer --&gt;

		&lt;script src='<a href="view-source:http://plugin-test.localhost/wp-includes/js/hoverintent-js.min.js?ver=2.2.1">http://plugin-test.localhost/wp-includes/js/hoverintent-js.min.js?ver=2.2.1</a>' id='<a>hoverintent-js-js</a>'&gt;&lt;/script&gt;
&lt;script src='<a href="view-source:http://plugin-test.localhost/wp-includes/js/admin-bar.min.js?ver=5.5.3">http://plugin-test.localhost/wp-includes/js/admin-bar.min.js?ver=5.5.3</a>' id='<a>admin-bar-js</a>'&gt;&lt;/script&gt;
&lt;script src='<a href="view-source:http://plugin-test.localhost/wp-includes/js/wp-embed.min.js?ver=5.5.3">http://plugin-test.localhost/wp-includes/js/wp-embed.min.js?ver=5.5.3</a>' id='<a>wp-embed-js</a>'&gt;&lt;/script&gt;
	&lt;script&gt;
	/(trident|msie)/i.test(navigator.userAgent)&amp;&amp;document.getElementById&amp;&amp;window.addEventListener&amp;&amp;window.addEventListener("hashchange",function(){var t,e=location.hash.substring(1);/^[A-z0-9_-]+$/.test(e)&amp;&amp;(t=document.getElementById(e))&amp;&amp;(/^(?:a|select|input|button|textarea)$/i.test(t.tagName)||(t.tabIndex=-1),t.focus())},!1);
	&lt;/script&gt;
	
	&lt;/body&gt;
&lt;/html&gt;
```
</details>

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #26689.

The problem: when plain text is pasted into the code block, the text is parsed as markdown. We need a way to return plain text early if desired.

The issue can only be reproduced if you copy the text as plain text like from a code editor. Copying code from an HTML page works because it's already encoded.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/blocks/src/api/raw-handling/paste-handler.js [hunk 1]
```diff
@@ -180,10 +183,16 @@ export function pasteHandler( {
 		HTML = HTML.normalize();
 	}
 
+	const isPlainText = ! HTML || isPlain( HTML );
+
+	if ( preservePlainText && isPlainText ) {
```
Comment (tellthemachines) [inline packages/blocks/src/api/raw-handling/paste-handler.js:188]: Would there be any problem with removing the `isPlainText` check here, so that HTML is also returned as plain text in the code block?

**Review by tellthemachines — COMMENTED** [review]
Following the steps in #27236, I can still reproduce the issue in this branch. The problem is text copied from browser view source is HTML, and OP expects it to be rendered as plain text in the code block. I think it's reasonable to expect anything inside the code block should be plain text, so shall we `preservePlainText` whatever the content is? (And should it then be called something like`convertToPlainText` instead?)

File: packages/blocks/src/api/raw-handling/paste-handler.js (hunk 1 above)
Comment (ellatrix) [reply packages/blocks/src/api/raw-handling/paste-handler.js:188]: Pasted HTML should not be pasted as plaintext. You might for example paste some code from an HTML page, which would already be encoded and formatted correctly.

**Comment by ellatrix** [comment]
> The problem is text copied from browser view source is HTML, and OP expects it to be rendered as plain text in the code block.

In that case the HTML data will be empty and the plain text will contain the HTML. Only if the content pasted is plain text should we "preserve plain text", meaning we should skip the markdown converting which is normally done and the cause of the problem.

I just retested and it works correctly. I'll test in other browsers. What browser are you testing in?

**Comment by ellatrix** [comment]
You're right, it does seem to be give some strange results in some browsers, which are setting the HTML data in addition to plain text. It seems the safest option is to always rely on plain text data indeed.

**Review by getdave — APPROVED** [review]
I tested this by pasting `view-source:https://wordpress.org/` into an empty Code block in the Editor.

I found that on this branch the formatting was correctly preserved whereas on `master` it was not (as reported in https://github.com/WordPress/gutenberg/issues/26689).

Therefore I'd say this works.

| This Branch       | Master | 
| :------------- | :----------: | 
| Screen Shot 2020-11-25 at 11 17 39 (1) | Screen Shot 2020-11-25 at 11 21 06  |

**Comment by getdave** [comment]
I'm going to test https://github.com/WordPress/gutenberg/issues/24282 now as I think it could be related.

**Comment by ellatrix** [comment]
I'll wait for a second approval from @tellthemachines, since this has to go in WP5.6.

**Comment by ellatrix** [comment]
#24282 is unrelated and has been an issue since the beginning of Gutenberg I think. I fixed in anyway in #27268, but it's not a regression that should go in RC.

**Comment by tellthemachines** [comment]
> What browser are you testing in?

I tested in Chrome, and could also reproduce in Firefox. In Chrome only the contents of `href` attributes were being presented as links, but in Firefox other attributes were too. I _couldn't_ reproduce it on 5.5.3 in any of the browsers.

Anyway, it's working fine now, thanks for the fix!

**Review by tellthemachines — APPROVED** [review]
