### PR TITLE
Tag Processor: Fix a problem backing up too far after updating HTML

### LINKED ISSUE #46588: One of the recent updates broke `WP_HTML_Tag_Processor`'s PHPUnit tests
### Description

I've noticed that these changes break PHPUnit tests on PHP 5.6:
https://github.com/WordPress/gutenberg/pull/46018/files#diff-93724b2f6e5dbf16c2b3c0efea57fa442b572f75f325d1cb185cf614b692cf9f
If I revert the changes made to the `WP_HTML_Tag_Processor` class in that PR, then PHPUnit tests pass.

### Step-by-step reproduction instructions

1. Install docker.
2. Checkout Gutenberg; navigate to its directory.
3. Add this line to the `.wp-env.json` file:
```json
"phpVersion": "5.6",
```
4. `npm ci`
5. `npm run build`
6. `composer config platform.php 5.6`
7. `composer remove spatie/phpunit-watcher --dev --no-update`
8. `composer update`
9. `npm run wp-env start`
10. `npm run test:unit:php`
11. Observe failed tests in the console.

### Screenshots, screen recording, code snippet

```
npm run wp-env run "tests-wordpress /var/www/html/wp-content/plugins/gutenberg/vendor/bin/phpunit -c /var/www/html/wp-content/plugins/gutenberg/phpunit.xml.dist --verbose"

> gutenberg@14.7.1 wp-env /src/wp-content/plugins/gutenberg
> wp-env "run" "tests-wordpress /var/www/html/wp-content/plugins/gutenberg/vendor/bin/phpunit -c /var/www/html/wp-content/plugins/gutenberg/phpunit.xml.dist --verbose"

[+] Running 1/0
 ⠿ Container f3a4f83488076060de4206c19ed1d495-tests-mysql-1  Running                                                                                                                                                                                                                                                                                                                                                     0.0s
⠋ Installing...
⠸ Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
⠼ Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
⠋ PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 5.6.39
Configuration: /var/www/html/wp-content/plugins/gutenberg/phpunit.xml.dist

⠧ .  63 / 743 (  8%)
⠸ .. 126 / 743 ( 16%)
⠼ ... 189 / 743 ( 25%)
............................................................... 252 / 743 ( 33%)
⠴ .......................................... 315 / 743 ( 42%)
............................................................... 378 / 743 ( 50%)
⠦ ...........................
Notice: Function wpdb::prepare was called <strong>incorrectly</strong>. Unsupported value type (object). Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 4.8.2.) in /var/www/html/wp-includes/functions.php on line 5836

Notice: Function wpdb::prepare was called <strong>incorrectly</strong>. Unsupported value type (object). Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 4.8.2.) in /var/www/html/wp-includes/functions.php on line 5836

Notice: Function wpdb::prepare was called <strong>incorrectly</strong>. Unsupported value type (object). Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 4.8.2.) in /var/www/html/wp-includes/functions.php on line 5836

Notice: Function wpdb::prepare was called <strong>incorrectly</strong>. Unsupported value type (object). Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 4.8.2.) in /var/www/html/wp-includes/functions.php on line 5836
⠴ II... 441 / 743 ( 59%)
⠴ ... 504 / 743 ( 67%)
⠇ .........................EEEE....... 567 / 743 ( 76%)
⠏ EEEE...................... 630 / 743 ( 84%)
⠙ ................... 693 / 743 ( 93%)
⠦ ..              743 / 743 (100%)

Time: 11.86 seconds, Memory: 37.25MB

There were 41 errors:

1) Render_Block_Heading_Test::test_block_core_heading_render_appends_css_class_to_a_vanilla_element with data set "should add a class name to a vanilla h2 element" ('<h2>Hello World</h2>', '<h2 class="wp-block-heading">...d</h2>')
⠧ strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/heading.php:37
/var/www/html/wp-content/plugins/gutenberg/phpunit/blocks/render-block-heading-test.php:22
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

2) Render_Block_Heading_Test::test_block_core_heading_render_appends_css_class_to_a_vanilla_element with data set "should add a class name even when the class attribute is already defined" ('<h2 class="is-align-right">He...d</h2>', '<h2 class="is-align-right wp-...d</h2>')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/heading.php:37
/var/www/html/wp-content/plugins/gutenberg/phpunit/blocks/render-block-heading-test.php:22
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

3) Render_Block_Heading_Test::test_block_core_heading_render_appends_css_class_to_a_vanilla_element with data set "should handle single quotes" ('<h2 class='is-align-right'>He...d</h2>', '<h2 class="is-align-right wp-...d</h2>')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/heading.php:37
/var/www/html/wp-content/plugins/gutenberg/phpunit/blocks/render-block-heading-test.php:22
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

4) Render_Block_Heading_Test::test_block_core_heading_render_appends_css_class_to_a_vanilla_element with data set "should handle single quotes with double quotes inside" ('<h2 class='" is-align-right'>...d</h2>', '<h2 class="&quot; is-align-ri...d</h2>')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/heading.php:37
/var/www/html/wp-content/plugins/gutenberg/phpunit/blocks/render-block-heading-test.php:22
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

5) Render_Block_Heading_Test::test_block_core_heading_render_appends_css_class_to_a_vanilla_element with data set "should not add a class name even when it is already defined" ('<h2 class="is-align-right wp-...d</h2>', '<h2 class="is-align-right wp-...d</h2>')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/heading.php:37
/var/www/html/wp-content/plugins/gutenberg/phpunit/blocks/render-block-heading-test.php:22
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

6) Render_Block_Heading_Test::test_block_core_heading_render_appends_css_class_to_a_vanilla_element with data set "should add a class name even when there are other HTML attributes present" ('<h2 style="display: block">He...d</h2>', '<h2 class="wp-block-heading" ...d</h2>')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/heading.php:37
/var/www/html/wp-content/plugins/gutenberg/phpunit/blocks/render-block-heading-test.php:22
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

7) Render_Block_Heading_Test::test_block_core_heading_render_appends_css_class_to_a_vanilla_element with data set "should add a class name even when the class attribute is already defined and has many entries" ('<h2 class="is-align-right cus...d</h2>', '<h2 class="is-align-right cus...d</h2>')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/heading.php:37
/var/www/html/wp-content/plugins/gutenberg/phpunit/blocks/render-block-heading-test.php:22
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

8) Render_Block_Heading_Test::test_block_core_heading_render_appends_css_class_to_a_vanilla_element with data set "should not add a class name to a nested h2" ('<h2 class="is-align-right cus...></h2>', '<h2 class="is-align-right cus...></h2>')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/heading.php:37
/var/www/html/wp-content/plugins/gutenberg/phpunit/blocks/render-block-heading-test.php:22
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

9) Render_Block_Heading_Test::test_block_core_heading_render_appends_css_class_to_a_vanilla_element with data set "should not add a class name to a nested h2 when the parent has another attribute" ('<h2 style="display: block" cl...></h2>', '<h2 style="display: block" cl...></h2>')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/heading.php:37
/var/www/html/wp-content/plugins/gutenberg/phpunit/blocks/render-block-heading-test.php:22
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

10) Render_Block_Heading_Test::test_block_core_heading_render_appends_css_class_to_a_vanilla_element with data set "should add a class name even when the class attribute is surrounded by other attributes" ('<h2 style="display: block" cl...></h2>', '<h2 style="display: block" cl...></h2>')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/heading.php:37
/var/www/html/wp-content/plugins/gutenberg/phpunit/blocks/render-block-heading-test.php:22
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

11) Render_Block_Heading_Test::test_block_core_heading_render_appends_css_class_to_a_vanilla_element with data set "should add a class name without getting confused when there is a tricky data-class attribute present" ('<h2 data-class="corner case!"...></h2>', '<h2 data-class="corner case!"...></h2>')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/heading.php:37
/var/www/html/wp-content/plugins/gutenberg/phpunit/blocks/render-block-heading-test.php:22
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

12) WP_HTML_Tag_Processor_Bookmark_Test::test_updates_bookmark_for_additions_after_both_sides
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-bookmark-test.php:257
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

13) WP_HTML_Tag_Processor_Bookmark_Test::test_updates_bookmark_for_additions_before_both_sides
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1324
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-bookmark-test.php:277
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

14) WP_HTML_Tag_Processor_Bookmark_Test::test_updates_bookmark_for_deletions_after_both_sides
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-bookmark-test.php:305
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

15) WP_HTML_Tag_Processor_Bookmark_Test::test_updates_bookmark_for_deletions_before_both_sides
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1324
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-bookmark-test.php:325
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

16) WP_HTML_Tag_Processor_Test::test_set_attribute_prevents_xss with data set #0 ('"')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:353
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

17) WP_HTML_Tag_Processor_Test::test_set_attribute_prevents_xss with data set #1 ('&quot;')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:353
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

18) WP_HTML_Tag_Processor_Test::test_set_attribute_prevents_xss with data set #2 ('&')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:353
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

19) WP_HTML_Tag_Processor_Test::test_set_attribute_prevents_xss with data set #3 ('&amp;')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:353
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

20) WP_HTML_Tag_Processor_Test::test_set_attribute_prevents_xss with data set #4 ('&euro;')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:353
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

21) WP_HTML_Tag_Processor_Test::test_set_attribute_prevents_xss with data set #5 (''')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:353
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

22) WP_HTML_Tag_Processor_Test::test_set_attribute_prevents_xss with data set #6 ('<>')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:353
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

23) WP_HTML_Tag_Processor_Test::test_set_attribute_prevents_xss with data set #7 ('&quot";')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:353
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

24) WP_HTML_Tag_Processor_Test::test_set_attribute_prevents_xss with data set #8 ('" onclick="alert('1');"><span...cript>')
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:353
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

25) WP_HTML_Tag_Processor_Test::test_set_attribute_with_a_non_existing_attribute_adds_a_new_attribute_to_the_markup
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:386
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

26) WP_HTML_Tag_Processor_Test::test_update_first_when_duplicated_attribute
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:402
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

27) WP_HTML_Tag_Processor_Test::test_set_attribute_with_an_existing_attribute_name_updates_its_value_in_the_markup
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:415
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

28) WP_HTML_Tag_Processor_Test::test_remove_first_when_duplicated_attribute
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:452
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

29) WP_HTML_Tag_Processor_Test::test_remove_attribute_with_an_existing_attribute_name_removes_it_from_the_markup
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:465
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

30) WP_HTML_Tag_Processor_Test::test_add_class_creates_a_class_attribute_when_there_is_none
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:491
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

31) WP_HTML_Tag_Processor_Test::test_calling_add_class_twice_creates_a_class_attribute_with_both_class_names_when_there_is_no_class_attribute
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:505
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

32) WP_HTML_Tag_Processor_Test::test_remove_class_does_not_change_the_markup_when_there_is_no_class_attribute
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:518
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

33) WP_HTML_Tag_Processor_Test::test_add_class_appends_class_names_to_the_existing_class_attribute_when_one_already_exists
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:534
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

34) WP_HTML_Tag_Processor_Test::test_remove_class_removes_a_single_class_from_the_class_attribute_when_one_exists
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:550
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

35) WP_HTML_Tag_Processor_Test::test_calling_remove_class_with_all_listed_class_names_removes_the_existing_class_attribute_from_the_markup
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:567
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

36) WP_HTML_Tag_Processor_Test::test_add_class_does_not_add_duplicate_class_names
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:583
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

37) WP_HTML_Tag_Processor_Test::test_add_class_preserves_class_name_order_when_a_duplicate_class_name_is_added
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:599
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

38) WP_HTML_Tag_Processor_Test::test_add_class_when_there_is_a_class_attribute_with_excessive_whitespaces
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:617
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

39) WP_HTML_Tag_Processor_Test::test_remove_class_preserves_whitespaces_when_there_is_a_class_attribute_with_excessive_whitespaces
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:635
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

40) WP_HTML_Tag_Processor_Test::test_removing_all_classes_removes_the_existing_class_attribute_from_the_markup_even_when_excessive_whitespaces_are_present
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:654
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

41) WP_HTML_Tag_Processor_Test::test_set_attribute_takes_priority_over_add_class
strpos(): Offset not contained in string

/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:853
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:478
/var/www/html/wp-content/plugins/gutenberg/lib/experimental/html/class-wp-html-tag-processor.php:1661
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:677
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

--

There were 34 failures:

1) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set "Invalid entity inside attribute value" ('<img src="https://s0.wp.com/i.../span>', '<img foo="bar" class="firstTa.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<img foo="bar" class="firstTag" src="https://s0.wp.com/i/atat.png" title="&; First &lt;title&gt; is &notit;" TITLE="second title" title="An Imperial &imperial; AT-AT"><span class="secondTag">test</span>
+<img class="firstTag" foo="bar" src="https://s0.wp.com/i/atat.png" title="&; First &lt;title&gt; is &notit;" TITLE="second title" title="An Imperial &imperial; AT-AT"><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

2) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set "Single and double quotes in attribute value" ('<p title="Demonstrating how t.../span>', '<p foo="bar" class="firstTag".../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<p foo="bar" class="firstTag" title="Demonstrating how to use single quote (') and double quote (&quot;)"><span class="secondTag">test</span>
+<p class="firstTag" foo="bar" title="Demonstrating how to use single quote (') and double quote (&quot;)"><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

3) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set "Unquoted attribute values" ('<hr a=1 a=2 a=3 a=5 /><span>t.../span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" a=1 a=2 a=3 a=5 /><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" a=1 a=2 a=3 a=5 /><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

4) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set "Double-quotes escaped in double-quote attribute value" ('<hr title="This is a &quot;do.../span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" title="This is a &quot;double-quote&quot;"><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" title="This is a &quot;double-quote&quot;"><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

5) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set "Unquoted attribute value" ('<hr id=code><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" id=code><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" id=code><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

6) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set "Unquoted attribute value with tag-like value" ('<hr id=   <code> ><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" id=     <code> ><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" id=     <code> ><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

7) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set "Unquoted attribute value with tag-like value followed by tag-like data" ('<hr id=code>><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" id=code>><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" id=code>><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

8) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #0 ('<hr id=&quo;code><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" id=&quo;code><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" id=&quo;code><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

9) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #1 ('<hr id/test=5><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" id/test=5><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" id/test=5><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

10) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #2 ('<hr title="<hr>"><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" title="<hr>"><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" title="<hr>"><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

11) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #3 ('<hr id=>code><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" id=>code><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" id=>code><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

12) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #4 ('<hr id"quo="test"><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" id"quo="test"><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" id"quo="test"><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

13) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #5 (Binary String: 0x3c68722069640...0616e3e, Binary String: 0x3c687220666f6...0616e3e)
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" idzero="test"><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" idzero="test"><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

14) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #6 ('<hr >id="test"><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" >id="test"><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" >id="test"><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

15) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #7 ('<hr =id="test"><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" =id="test"><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" =id="test"><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

16) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #8 ('</><span>test</span>', '</><span foo="bar" class="fir.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-</><span foo="bar" class="firstTag">test</span>
+</><span class="firstTag" foo="bar">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

17) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #9 ('The applicative operator <* w.../span>', 'The applicative operator <* w.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-The applicative operator <* works well in Haskell; <data-tag foo="bar" class="firstTag"> is what?<span class="secondTag">test</span>
+The applicative operator <* works well in Haskell; <data-tag class="firstTag" foo="bar"> is what?<span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

18) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #10 ('<3 is a heart but <t3> is a t.../span>', '<3 is a heart but <t3 foo="ba.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<3 is a heart but <t3 foo="bar" class="firstTag"> is a tag.<span class="secondTag">test</span>
+<3 is a heart but <t3 class="firstTag" foo="bar"> is a tag.<span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

19) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #11 ('<?comment --><span>test</span>', '<?comment --><span foo="bar" .../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<?comment --><span foo="bar" class="firstTag">test</span>
+<?comment --><span class="firstTag" foo="bar">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

20) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #12 ('<!-- this is a comment. no <s.../span>', '<!-- this is a comment. no <s.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<!-- this is a comment. no <strong>tags</strong> allowed --><span foo="bar" class="firstTag">test</span>
+<!-- this is a comment. no <strong>tags</strong> allowed --><span class="firstTag" foo="bar">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

21) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #13 ('<![CDATA[This <is> a <strong .../span>', '<![CDATA[This <is> a <strong .../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<![CDATA[This <is> a <strong id="yes">HTML Tag</strong>]]><span foo="bar" class="firstTag">test</span>
+<![CDATA[This <is> a <strong id="yes">HTML Tag</strong>]]><span class="firstTag" foo="bar">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

22) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #14 ('<hr ===name="value"><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" ===name="value"><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" ===name="value"><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

23) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #15 ('<hr asdf="test"><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" asdf="test"><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" asdf="test"><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

24) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #16 ('<hr =asdf="tes"><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" =asdf="tes"><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" =asdf="tes"><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

25) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #17 ('<hr ==="test"><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" ==="test"><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" ==="test"><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

26) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #18 ('<hr =><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" =><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" =><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

27) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #19 ('<hr =5><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" =5><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" =5><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

28) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #20 ('<hr ==><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" ==><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" ==><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

29) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #21 ('<hr ===><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" ===><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" ===><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

30) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #22 ('<hr disabled><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" disabled><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" disabled><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

31) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #23 ('<hr a"sdf="test"><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" a"sdf="test"><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" a"sdf="test"><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

32) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set "Multiple unclosed tags treated as a single tag" ('                       <hr id=">"code\n                        <hr id=".../span>', '                   <hr foo="bar" class="first.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-                       <hr foo="bar" class="firstTag" id=">"code
+                       <hr class="firstTag" foo="bar" id=">"code
                        <hr id="value>"code
                        <hr id="/>"code
                        <hr id="value/>"code
                        />
                        <span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

33) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #24 ('<hr id   =5><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" id   =5><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" id   =5><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51

34) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set #25 ('<hr id a  =5><span>test</span>', '<hr foo="bar" class="firstTag.../span>')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<hr foo="bar" class="firstTag" id a  =5><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" id a  =5><span class="secondTag">test</span>

/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51
```

### Environment info

macOs 12.6

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by dmsnell**
## What

Fixes a bug in the HTML Tag Processor when updating a document when the internal pointer is at the first tag in the document.

## Why?

The Tag Processor shouldn't break code relying on it.

## How?

A defect introduced in #46018 led to the tag processor backing up one index too far after flushing its queued changes on a document.

For most operations this didn't cause any harm because when immediately moving forward after an update, the `next_tag()` returned to the same spot: it was backing up to one position before the current tag instead of at the start of the current tag.

Unfortunately, when the current tag was the first in the document this would lead the processor to rewind to position `-1`, right before the start of the document, and lead to errors with `strpos()` when it received out-of-bounds indices.

In this fix we're correcting the adjustment for the HTML tag's `<` and documenting the math in the file so that it's clearer why it's there and providing guidance should another fix be necessary.

Props to @anton-vlasenko for finding this bug.

## Testing Instructions

Run the PHP unit test suite with PHP <= 7.0.
Tests should start failing in `trunk` but should pass in this branch.

Temporarily merging in `fix/parity-with-cores-php-ci-jobs` in this PR to run such tests in CI.

### CODE REVIEW

**Review by anton-vlasenko — CHANGES_REQUESTED** [review]
Thanks for the PR, @dmsnell!
It fixes lots of the tests.
But some PHP 5.6 [tests still don't pass](https://github.com/WordPress/gutenberg/actions/runs/3711263900/jobs/6291503554).
E.g.: 
```
WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set "Invalid entity inside attribute value" ('<img src="https://s0.wp.com/i.../span>', '<img foo="bar" class="firstTa.../span>')
[66](https://github.com/WordPress/gutenberg/actions/runs/3711263900/jobs/6291503554#step:14:67)
Failed asserting that two strings are identical.
[67](https://github.com/WordPress/gutenberg/actions/runs/3711263900/jobs/6291503554#step:14:68)
--- Expected
[68](https://github.com/WordPress/gutenberg/actions/runs/3711263900/jobs/6291503554#step:14:69)
+++ Actual
[69](https://github.com/WordPress/gutenberg/actions/runs/3711263900/jobs/6291503554#step:14:70)
@@ @@
[70](https://github.com/WordPress/gutenberg/actions/runs/3711263900/jobs/6291503554#step:14:71)
-<img foo="bar" class="firstTag" src="https://s0.wp.com/i/atat.png" title="&; First &lt;title&gt; is &notit;" TITLE="second title" title="An Imperial &imperial; AT-AT"><span class="secondTag">test</span>
[71](https://github.com/WordPress/gutenberg/actions/runs/3711263900/jobs/6291503554#step:14:72)
+<img class="firstTag" foo="bar" src="https://s0.wp.com/i/atat.png" title="&; First &lt;title&gt; is &notit;" TITLE="second title" title="An Imperial &imperial; AT-AT"><span class="secondTag">test</span>
[72](https://github.com/WordPress/gutenberg/actions/runs/3711263900/jobs/6291503554#step:14:73)

[73](https://github.com/WordPress/gutenberg/actions/runs/3711263900/jobs/6291503554#step:14:74)
/var/www/html/wp-content/plugins/gutenberg/phpunit/html/wp-html-tag-processor-test.php:1117
[74](https://github.com/WordPress/gutenberg/actions/runs/3711263900/jobs/6291503554#step:14:75)
phpvfscomposer:///var/www/html/wp-content/plugins/gutenberg/vendor/phpunit/phpunit/phpunit:51
[75](https://github.com/WordPress/gutenberg/actions/runs/3711263900/jobs/6291503554#step:14:76)

[76](https://github.com/WordPress/gutenberg/actions/runs/3711263900/jobs/6291503554#step:14:77)
2) WP_HTML_Tag_Processor_Test::test_updating_attributes_works_even_in_malformed_html_2 with data set "Single and double quotes in attribute value" ('<p title="Demonstrating how t.../span>', '<p foo="bar" class="firstTag".../span>')
[77](https://github.com/WordPress/gutenberg/actions/runs/3711263900/jobs/6291503554#step:14:78)
Failed asserting that two strings are identical.
[78](https://github.com/WordPress/gutenberg/actions/runs/3711263900/jobs/6291503554#step:14:79)
--- Expected
[79](https://github.com/WordPress/gutenberg/actions/runs/3711263900/jobs/6291503554#step:14:80)
+++ Actual
[80](https://github.com/WordPress/gutenberg/actions/runs/3711263900/jobs/6291503554#step:14:81)
@@ @@
[81](https://github.com/WordPress/gutenberg/actions/runs/3711263900/jobs/6291503554#step:14:82)
-<p foo="bar" class="firstTag" title="Demonstrating how to use single quote (') and double quote (&quot;)"><span class="secondTag">test</span>
[82](https://github.com/WordPress/gutenberg/actions/runs/3711263900/jobs/6291503554#step:14:83)
+<p class="firstTag" foo="bar" title="Demonstrating how to use single quote (') and double quote (&quot;)"><span class="secondTag">test</span>
```

**Comment by anton-vlasenko** [comment]
I had to rebase this PR, because Github started to display incorrect "changed files" when I rebased https://github.com/WordPress/gutenberg/tree/fix/parity-with-cores-php-ci-jobs to the latest trunk.
Should this PR be converted to a draft to not accidentally merge it to trunk?

**Comment by adamziel** [comment]
PHP 5.6 tests do not indicate a real problem – they just complain about the order of the generated attributes:

```
-<hr foo="bar" class="firstTag" id a  =5><span class="secondTag">test</span>
+<hr class="firstTag" foo="bar" id a  =5><span class="secondTag">test</span>
```

These updates are sorted as follows:

```php
	private function apply_attributes_updates() {
		// ...
		usort( $this->attribute_updates, array( self::class, 'sort_start_ascending' ) );

		foreach ( $this->attribute_updates as $diff ) {
			// ...
		}
		// ...
	}

	private static function sort_start_ascending( $a, $b ) {
		return $a->start - $b->start;
	}

```

In the failed tests `$a->start === $b->start` – PHP 5.6 just has a different opinion on what to do with that than PHP 7+.

Ideally the tests wouldn't fail in this scenario. How about we provide an alternative acceptable output string where these attributes are listed in PHP 5.6 order @dmsnell ?

**Comment by anton-vlasenko** [comment]
> In the failed tests `$a->start === $b->start` – PHP 5.6 just has a different opinion on what to do with that than PHP 7+.
> 
> Ideally the tests wouldn't fail in this scenario. How about we provide an alternative acceptable output string where these attributes are listed in PHP 5.6 order @dmsnell ?

@adamziel 
If you run the PHP 5.6 tests using [the version of `WP_HTML_Tag_Processor`](https://raw.githubusercontent.com/WordPress/gutenberg/7df3687192ad50f76fbd194682239b9c75f51fb0/lib/experimental/html/class-wp-html-tag-processor.php) that was in use before https://github.com/WordPress/gutenberg/pull/46018, the tests will pass.

I wonder why [it](https://raw.githubusercontent.com/WordPress/gutenberg/7df3687192ad50f76fbd194682239b9c75f51fb0/lib/experimental/html/class-wp-html-tag-processor.php) passes the tests then?

The code responsible for attributes' sorting hasn't changed since then.

> How about we provide an alternative acceptable output string where these attributes are listed in PHP 5.6 order @dmsnell ?

Doing so would make the tests pass, but it doesn't explain why the sorting doesn't work as it used to.
@dmsnell @adamziel

**Comment by anton-vlasenko** [comment]
>Doing so would make the tests pass, but it doesn't explain why the sorting doesn't work as it used to.

Ah, I get it. We didn't compare similar values in the callback function before https://github.com/WordPress/gutenberg/pull/46018.
That's why the comparison logic didn't change, but we started to get failing tests.
This snippet illustrates the issue: https://3v4l.org/JO7urg
You were right about the root cause of the issue, @adamziel.

> How about we provide an alternative acceptable output string where these attributes are listed in PHP 5.6 order

Yes. We also have to ensure that these alternative strings are only used when running the tests on PHP 5.x.

**Comment by dmsnell** [comment]
Thanks for working on this, both of you.

> Should this PR be converted to a draft to not accidentally merge it to trunk?

This PR won't merge to `trunk` because it's based off of `fix/parity-with-cores-php-ci-jobs`. If the button is pressed then it will merge into that branch, and that's not much of a problem because we could undo it.

> alternative strings

If I'm reading this right we're talking about providing alternative strings against which to compare the results based on differences in the sort algorithm across PHP versions. That's something that would quiet the tests but definitely increase the maintenance burden and confuse the people who come after us, so I'd rather we either fix the tests so that they aren't clamping down on behaviors we don't care to assert (for example, we don't care where the attributes appear) or we take the same "avoid the problem" approach but do it inside the tag processor.

I'll propose an update soon which does one of these.

It's noteworthy that PHP 8.0 changes the default behavior of the sort functions by making them stable, whereas in previous versions the sort is unstable. Simply changing the comparison string is not only risky, but it's only going to move us a couple steps forward before we would run into this same problem.

I'm thinking we could sort the updates by start and then by alphabetical order of the replacement. That shouldn't product a conflict because we shouldn't have multiple copies of the same attribute. This is all adjusting runtime behavior in order to appease deficient tests, and while I hate doing that, as a practical thing we discussed using `DOMDocument` in the tests and had a set of issues with doing that as well.

**Comment by dmsnell** [comment]
Everything was [passing](https://github.com/WordPress/gutenberg/actions/runs/3716249813) in the tests in fix/parity-with-cores-php-ci-jobs, @anton-vlasenko, so I've rebased against `trunk` and I think this is ready to go.

It's a good update for `trunk` too so as soon as we're happy with it I'd like to merge it in.

File: lib/experimental/html/class-wp-html-tag-processor.php [hunk 1]
```diff
@@ -1331,16 +1331,33 @@ public function seek( $bookmark_name ) {
...
-	 * @param object $a First attribute update.
-	 * @param object $b Second attribute update.
+	 * @param WP_HTML_Text_Replacement $a First attribute update.
+	 * @param WP_HTML_Text_Replacement $b Second attribute update.
 	 * @return integer
 	 */
 	private static function sort_start_ascending( $a, $b ) {
-		return $a->start - $b->start;
+		$by_start = $a->start - $b->start;
+		if ( $by_start !== 0 ) {
```
Comment (anton-vlasenko) [inline lib/experimental/html/class-wp-html-tag-processor.php]:
```suggestion
		if ( 0 !== $by_start ) {
```
https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#yoda-conditions

File: lib/experimental/html/class-wp-html-tag-processor.php [hunk 2]
```diff
@@ -1331,16 +1331,33 @@ public function seek( $bookmark_name ) {
...
+			return $by_start;
+		}
+
+		$by_text = isset( $a->text, $b->text ) ? strcmp( $a->text, $b->text ) : 0;
+		if ( $by_text !== 0 ) {
```
Comment (anton-vlasenko) [inline lib/experimental/html/class-wp-html-tag-processor.php]:
```suggestion
		if ( 0 !== $by_text ) {
```
https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#yoda-conditions

**Review by anton-vlasenko — CHANGES_REQUESTED** [review]
@dmsnell 
~~When I run the tests locally (PHP 8.1), I get these errors (please see below).
Maybe it makes sense to add alternative strings, just as [@adamziel](https://github.com/adamziel) proposed.
I'm not sure why Github's CI jobs don't fail. I'm investigating it.
P.S. I'm going to reinstall my local WP copy to see if it's somehow related.~~

I've asked around and it seems that this issue sometimes happens: sort works differently on different PHP installations.
So if the tests pass here, I guess that is fine.
Please disregard this message, @dmsnell 
```
1) Block_Fixture_Test::test_kses_doesnt_change_fixtures with data set #69 ('<!-- wp:file {"href":"http://... -->\n', 'core__file__pdf-preview.seria...d.html')
Failed to match core__file__pdf-preview.serialized.html
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
 '<!-- wp:file {"href":"http://localhost:8889/wp-content/uploads/2021/04/yolo.pdf","displayPreview":true,"previewHeight":370} -->
-<div class="wp-block-file"><object class="wp-block-file__embed" data="http://localhost:8889/wp-content/uploads/2021/04/yolo.pdf" type="application/pdf" style="width:100%;height:370px" aria-label="yolo"></object><a id="wp-block-file--media-_clientId_0" href="http://localhost:8889/wp-content/uploads/2021/04/yolo.pdf">yolo</a><a href="http://localhost:8889/wp-content/uploads/2021/04/yolo.pdf" class="wp-block-file__button wp-element-button" download aria-describedby="wp-block-file--media-_clientId_0">Download</a></div>
+<div class="wp-block-file"><object></object><a id="wp-block-file--media-_clientId_0" href="http://localhost:8889/wp-content/uploads/2021/04/yolo.pdf">yolo</a><a href="http://localhost:8889/wp-content/uploads/2021/04/yolo.pdf" class="wp-block-file__button wp-element-button" download aria-describedby="wp-block-file--media-_clientId_0">Download</a></div>
 <!-- /wp:file -->
 '

/Users/anton/html/wordpress.test/src/wp-content/plugins/gutenberg/phpunit/class-block-fixture-test.php:31

2) Block_Fixture_Test::test_kses_doesnt_change_fixtures with data set #70 ('<!-- wp:file {"href":"http://... -->\n', 'core__file__pdf-preview__depr...d.html')
Failed to match core__file__pdf-preview__deprecated-1.serialized.html
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
 '<!-- wp:file {"href":"http://localhost:8889/wp-content/uploads/2021/04/yolo.pdf","displayPreview":true,"previewHeight":370} -->
-<div class="wp-block-file"><object class="wp-block-file__embed" data="http://localhost:8889/wp-content/uploads/2021/04/yolo.pdf" type="application/pdf" style="width:100%;height:370px" aria-label="yolo"></object><a href="http://localhost:8889/wp-content/uploads/2021/04/yolo.pdf">yolo</a><a href="http://localhost:8889/wp-content/uploads/2021/04/yolo.pdf" class="wp-block-file__button wp-element-button" download>Download</a></div>
+<div class="wp-block-file"><object></object><a href="http://localhost:8889/wp-content/uploads/2021/04/yolo.pdf">yolo</a><a href="http://localhost:8889/wp-content/uploads/2021/04/yolo.pdf" class="wp-block-file__button wp-element-button" download>Download</a></div>
 <!-- /wp:file -->
 '

/Users/anton/html/wordpress.test/src/wp-content/plugins/gutenberg/phpunit/class-block-fixture-test.php:31

3) Gutenberg_REST_Global_Styles_Controller_Test::test_get_theme_items
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
-Array &0 ()
+Array &0 (
+    0 => Array &1 (
+        'version' => 2
+        'settings' => Array &2 (
+            'color' => Array &3 (
+                'palette' => Array &4 (
+                    'theme' => Array &5 (
+                        0 => Array &6 (
+                            'slug' => 'foreground'
+                            'color' => '#3F67C6'
+                            'name' => 'Foreground'
+                        )
+                    )
+                )
+            )
+        )
+        'styles' => Array &7 (
+            'blocks' => Array &8 (
+                'core/post-title' => Array &9 (
+                    'typography' => Array &10 (
+                        'fontWeight' => '700'
+                    )
+                )
+            )
+        )
+        'title' => 'variation'
+    )
+)

/Users/anton/html/wordpress.test/tests/phpunit/includes/abstract-testcase.php:987
/Users/anton/html/wordpress.test/src/wp-content/plugins/gutenberg/phpunit/class-gutenberg-rest-global-styles-controller-test.php:116

4) WP_Webfonts_Provider_Local_Test::test_get_css with data set "truetype format" (array(array('local', 'Open Sans', 'italic', 'bold', 'http://example.org/assets/fon...ht.ttf')), '@font-face{font-family:"Open ...pe');}')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'@font-face{font-family:"Open Sans";font-style:italic;font-weight:bold;src:local("Open Sans"), url('http://example.org/assets/fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf') format('truetype');}'
+'@font-face{font-family:"Open Sans";font-style:italic;font-weight:bold;src:local("Open Sans"), url('/assets/fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf') format('truetype');}'

/Users/anton/html/wordpress.test/src/wp-content/plugins/gutenberg/phpunit/class-wp-webfonts-local-provider-test.php:91

5) WP_Webfonts_Provider_Local_Test::test_get_css with data set "woff2 format" (array(array('local', 'Source Serif Pro', 'normal', '200 900', 'normal', 'http://example.org/assets/fon....woff2'), array('local', 'Source Serif Pro', 'italic', '200 900', 'normal', 'http://example.org/assets/fon....woff2')), '@font-face{font-family:"Sourc...f2');}')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'@font-face{font-family:"Source Serif Pro";font-style:normal;font-weight:200 900;font-stretch:normal;src:local("Source Serif Pro"), url('http://example.org/assets/fonts/source-serif-pro/SourceSerif4Variable-Roman.ttf.woff2') format('woff2');}@font-face{font-family:"Source Serif Pro";font-style:italic;font-weight:200 900;font-stretch:normal;src:local("Source Serif Pro"), url('http://example.org/assets/fonts/source-serif-pro/SourceSerif4Variable-Italic.ttf.woff2') format('woff2');}'
+'@font-face{font-family:"Source Serif Pro";font-style:normal;font-weight:200 900;font-stretch:normal;src:local("Source Serif Pro"), url('/assets/fonts/source-serif-pro/SourceSerif4Variable-Roman.ttf.woff2') format('woff2');}@font-face{font-family:"Source Serif Pro";font-style:italic;font-weight:200 900;font-stretch:normal;src:local("Source Serif Pro"), url('/assets/fonts/source-serif-pro/SourceSerif4Variable-Italic.ttf.woff2') format('woff2');}'

/Users/anton/html/wordpress.test/src/wp-content/plugins/gutenberg/phpunit/class-wp-webfonts-local-provider-test.php:91

6) WP_Style_Engine_Test::test_wp_style_engine_get_styles with data set "inline_valid_typography_style" (array(array('clamp(2em, 2vw, 4em)', 'Roboto,Oxygen-Sans,Ubuntu,sans-serif', 'italic', '800', '1.3', '2', 'underline', 'uppercase', '2')), null, array('font-size:clamp(2em, 2vw, 4em...ing:2;', array('clamp(2em, 2vw, 4em)', 'Roboto,Oxygen-Sans,Ubuntu,sans-serif', 'italic', '800', '1.3', '2', 'underline', 'uppercase', '2')))
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
 Array &0 (
-    'css' => 'font-size:clamp(2em, 2vw, 4em);font-family:Roboto,Oxygen-Sans,Ubuntu,sans-serif;font-style:italic;font-weight:800;line-height:1.3;column-count:2;text-decoration:underline;text-transform:uppercase;letter-spacing:2;'
+    'css' => 'font-size:clamp(2em, 2vw, 4em);font-family:Roboto,Oxygen-Sans,Ubuntu,sans-serif;font-style:italic;font-weight:800;line-height:1.3;text-decoration:underline;text-transform:uppercase;letter-spacing:2;'
     'declarations' => Array &1 (
         'font-size' => 'clamp(2em, 2vw, 4em)'
         'font-family' => 'Roboto,Oxygen-Sans,Ubuntu,sans-serif'
@@ @@
         'font-style' => 'italic'
         'font-weight' => '800'
         'line-height' => '1.3'
-        'column-count' => '2'
         'text-decoration' => 'underline'
         'text-transform' => 'uppercase'
         'letter-spacing' => '2'
     )
 )

/Users/anton/html/wordpress.test/src/wp-content/plugins/gutenberg/phpunit/style-engine/style-engine-test.php:47
```

**Review by anton-vlasenko — APPROVED** [review]

**Comment by dmsnell** [comment]
Rebasing this against `trunk@{9.hours.ago}` to start investigating performance test suite failures. Will likely rewrite the branch a few times.

**Review by anton-vlasenko — APPROVED** [review]
I confirm this PR passes PHPUnit tests on all Core-supported PHP versions (5.6 - 8.2). So I approve that PR.
But I'd prefer someone else to also approve this PR as I'm not very familiar with the `WP_HTML_Tag_Processor' class. This PR changes the order in which element attributes are sorted.

**Review by adamziel — APPROVED** [review]

**Comment by ockham** [comment]
👋 Coming here from #46680, which seems to be fixed by this PR. Thank you for that! 🎉 

Can we maybe add the test coverage from that PR here? I.e. 

```diff
diff --git a/phpunit/html/wp-html-tag-processor-test.php b/phpunit/html/wp-html-tag-processor-test.php
index cab1496249..fbf629088c 100644
--- a/phpunit/html/wp-html-tag-processor-test.php
+++ b/phpunit/html/wp-html-tag-processor-test.php
@@ -378,12 +378,14 @@ class WP_HTML_Tag_Processor_Test extends WP_UnitTestCase {
         *
         * @covers set_attribute
         * @covers get_updated_html
+        * @covers get_attribute
         */
        public function test_set_attribute_with_a_non_existing_attribute_adds_a_new_attribute_to_the_markup() {
                $p = new WP_HTML_Tag_Processor( self::HTML_SIMPLE );
                $p->next_tag();
                $p->set_attribute( 'test-attribute', 'test-value' );
                $this->assertSame( '<div test-attribute="test-value" id="first"><span id="second">Text</span></div>', $p->get_updated_html() );
+               $this->assertSame( 'test-value', $p->get_attribute( 'test-attribute' ) );
        }
 
        /**
```

(And maybe add an assertion like that to other `set_attribute()` tests as well; or add a separate test case.)

**Comment by anton-vlasenko** [comment]
> 👋 Coming here from #46680, which seems to be fixed by this PR. Thank you for that! 🎉
> 
> Can we maybe add the test coverage from that PR here? I.e.

I'd appreciate it if these tests could be added later.
I need to get this PR merged to unblock https://github.com/WordPress/gutenberg/pull/46510.
Thanks.
