### PR TITLE
Page details: Fix displaying slugs with non-latin characters

### LINKED ISSUE #51676: Browse mode/ navigation sidebar page details shows incorrect slug and link with non-latin characters
### Description

If a page has a slug that contains non-latin characters, the slug and page link is incorrect  under Appearance > Editor > Pages > Chosen page.

The Slug `/επίπεδο-2/` shows as `%ce%b5%cf%80%ce%af%cf%80%ce%b5%ce%b4%ce%bf-2`

### Step-by-step reproduction instructions

1. Activate a block theme
2. Import the [theme test data](https://github.com/WPTT/theme-test-data) that has some content in greek, or create a new page with this Russian title: `Привет, мир`
3. Navigate to Appearance > Editor > Pages.
4. Select the page you created, or for example the page with the title "Επίπεδο 2 -Second Greek level"
5. See that the slug shows the wrong characters.
6.  Optionally confirm that clicking the link below the page title in the sidebar still works. It only displays incorrectly.

### Screenshots, screen recording, code snippet

slug

### Environment info

WordPress 6.2.2.
Gutenberg current trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by carolinan**
## What?

If a page has a title and slug with non-latin characters, the page details show them as encoded:
The Slug /επίπεδο-2/ shows as %ce%b5%cf%80%ce%af%cf%80%ce%b5%ce%b4%ce%bf-2.
This PR decodes the visual presentation of the slug in two places in the page details:
The page link at the top below the page title,  and the page slug item that is further down the list.

Closes https://github.com/WordPress/gutenberg/issues/51676

## Why?

The text was not displayed correctly.

## How?

Decodes the URI and slug.

## Testing Instructions
1. Activate a block theme
2. Import the [theme test data](https://github.com/WPTT/theme-test-data) that has some content in greek, or create a new page with this Russian title: `Привет, мир`
3. Navigate to Appearance > Editor > Pages.
4. Select the page you created, or for example the page with the title "Επίπεδο 2 -Second Greek level"
5. See that the slug shows the correct characters.
6.  Optionally confirm that clicking the link below the page title in the sidebar still works. It only displays incorrectly.

### Testing Instructions for Keyboard

1. Activate a block theme
2. Import the [theme test data](https://github.com/WPTT/theme-test-data) that has some content in greek, or create a new page with this Russian title: `Привет, мир`
3. Navigate from the WordPress admin to the Site Editor via the menu items Appearance, Editor.
4. In the navigation Sidebar, navigate past the links (go back to dashboard, view site etc) until you reach the navigation with buttons. Skip past the first two buttons, "Navigation" and "Styles", and activate the button with the label "Pages".
5. Skip past the back button and the "draft new page" button, and activate the button with the title of the page you want to test.
6. There are two items to test here:
1. A link that is immediately after the "Edit" button. Confirm that the slug with the non-latin characters is announced and not something like "0%/d".
2. A non-focusable text item inside a list. To test this, read the full content of the page and pay attention to "Slug" followed by the page slug. Confirm that it does not read out something like "0%/d".

## Screenshots or screencast 
After:
Page details view with decoded slugs

### CODE REVIEW

File: packages/edit-site/src/components/sidebar-navigation-screen-page/index.js [hunk 1]
```diff
@@ -90,7 +90,9 @@ export default function SidebarNavigationScreenPage() {
 					className="edit-site-sidebar-navigation-screen__page-link"
 					href={ record.link }
 				>
-					{ record.link.replace( /^(https?:\/\/)?/, '' ) }
+					{ decodeURI(
+						record.link.replace( /^(https?:\/\/)?/, '' )
+					) }
```
Comment (Mamaduka) [inline packages/edit-site/src/components/sidebar-navigation-screen-page/index.js]: I believe the core uses the `safeDecodeURIComponent` from the `url` [package](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-url/#safedecodeuricomponent), in other places for similar fixes. We can also replace the regex here with `filterURLForDisplay`.

```js
{ filterURLForDisplay( safeDecodeURIComponent( record.link ) ) }
 ```

Edit: I found my PR that fixes a similar bug in post editor - #42930.

File: packages/edit-site/src/components/sidebar-navigation-screen-page/page-details.js [hunk 2]
```diff
@@ -42,7 +42,11 @@ function getPageDetails( page ) {
 		},
 		{
 			label: __( 'Slug' ),
-			value: <Truncate numberOfLines={ 1 }>{ page.slug }</Truncate>,
+			value: (
+				<Truncate numberOfLines={ 1 }>
+					{ decodeURI( page.slug ) }
```
Comment (Mamaduka) [inline packages/edit-site/src/components/sidebar-navigation-screen-page/page-details.js]: Same here, but just `safeDecodeURIComponent`.

File: packages/edit-site/src/components/sidebar-navigation-screen-page/index.js (hunk 1 above)
Comment (carolinan) [reply packages/edit-site/src/components/sidebar-navigation-screen-page/index.js]: Thank you, I did not know these existed.

**Review by Mamaduka — APPROVED** [review]
Works as expected. Tested with Georgian language.

**Review by t-hamano — APPROVED** [review]
It also worked correctly in Japanese. Thank you!

| Before| After |
|--------|--------|
| before | after |
