### PR TITLE
Bundle the block autocompleter in the block-editor package

### LINKED ISSUE #20619: Slash inserter not working in Storybook playground
**Describe the bug**

In the [Storybook Gutenberg playground](https://wordpress.github.io/gutenberg/?path=/story/playground-block-editor--default), typing `/` in the editor does not cause the block autocomplete dropdown to appear as expected. Placeholder text still reads "Start writing or type / to choose a block" so this functionality should work.

**To reproduce**
1. Go to [Storybook Gutenberg playground](https://wordpress.github.io/gutenberg/?path=/story/playground-block-editor--default)
2. Click on the placeholder that says "Start writing or type / to choose a block"
3. Type "/"
4. Observe nothing happens.

**Expected behavior**

Expected block dropdown to appear.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #20619

This PR bundles the block autocompleter by default in all block editor instances. This makes the slash inserter work on the widget screen, edit site screen and the playground.

There's still another WordPress autocompleter that is not enabled on these pages (user) but this one can't be enabled by default as it's WordPress specific, so we need to find another home for it (today it's inside the editor package).

### CODE REVIEW

File: packages/block-editor/src/components/autocomplete/index.js [hunk 1]
```diff
@@ -26,7 +29,13 @@ import { withBlockEditContext } from '../block-edit/context';
  */
 export function withFilteredAutocompleters( Autocomplete ) {
 	return ( props ) => {
-		let { completers = [] } = props;
+		let { completers = [], blockName } = props;
```
Comment (jorgefilipecosta) [inline packages/block-editor/src/components/autocomplete/index.js:32]: Each time we arrive to this function with undefined completers, completers will be set to a new array reference and useMemo will execute again. Should we have an empty array constant and set the completers default value to it?

**Review by jorgefilipecosta — APPROVED** [review]
Everything worked well on my tests 👍
