### PR TITLE
FontSizePicker: Use number values when the initial value is a number

### LINKED ISSUE #33651: FontSizePicker is not working with value type "number"
## Description
After update to WordPress 5.8 version FontSizePicker doesn't support value with type of number.

## Step-by-step reproduction instructions
https://github.com/NasKadir123/textBlock here is example of a custom block. This block is working in previous versions, but not in the new one. When you change Font Size in FontSizePicker for example to "large" it works, but if you insert number inside Custom input, for example "24" then update and refresh the page it will throw the error. It has the same effect even if you don't want to use HOCs and will just have a value attribute with type number.

## Expected behaviour
It should work correctly.

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/49153601/126791873-f861438c-a5b2-469b-92f6-1cf8936a7c8b.mov
Sorry for the long pause after updating the page, my internet connection is slow.
## Code snippet (optional)
https://github.com/NasKadir123/textBlock @getdave Can you recheck it, please? Now publish and refresh the page. Thanks in advance!

## WordPress information
- WordPress version: 5.8
- Gutenberg version: 10.7
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Desktop
- Operating system: OS 10.15
- Browser: Firefox 89.0.1

### LINKED ISSUE #33653: withFontSizes bug in WordPress 5.8 release
With the release of WordPress 5.8 the `withFontSizes` HOC within '@wordpress/block-editor' has bugged behavior. The CoBlocks implementation of `withFontSizes` has remained unchanged for over two years yet is non-functional in 5.8.

https://github.com/godaddy-wordpress/coblocks/blob/4b6a23ebbca9a9702acf88316cf35aeedad8a5da/src/blocks/highlight/edit.js#L136

https://github.com/godaddy-wordpress/coblocks/blob/4b6a23ebbca9a9702acf88316cf35aeedad8a5da/src/blocks/highlight/inspector.js#L36-L40

fontSizesBug

## Description

It seems that while migrating to the new global settings schema that some items may have been left out.

## Step-by-step reproduction instructions

1. Add Highlight block. (Happens on any blocks using `withFontSizes` HOC)
2. Modify block font size and save changes.
3. Reload the editor to see an invalid block state.

## Expected behaviour

Expect API changes to `withFontSizes` to allow deprecation.

## WordPress information
- WordPress version:  5.8
- Gutenberg version:  11.1.0
- Are all plugins except Gutenberg deactivated?  (Except CoBlocks where we implement the HOC)
- Are you using a default theme (e.g. Twenty Twenty-One)?  Yes

This does not occur using the same steps on 5.7.2

## Device information
- Device:  Desktop
- Operating system:  IOS
- Browser:  Chrome/Firefox

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
Updates `onChange` logic in FontSizePicker component. When the component detects that value or first object in `fonSizes` doesn't use units, it will pass the number value to the onChange callback.

Fixes #33651.
Fixes #33653.

## How has this been tested?
Tested with plugin provided in original issue report - https://github.com/NasKadir123/textBlock

## Types of changes
Bugfix 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by olafleur** [comment]
Thanks! :)

**Comment by youknowriad** [comment]
Is it possible to fix the issue in `FontSizePicker` instead?

**Comment by youknowriad** [comment]
Asking because this will fix `withFontSizes` but `FontSizePicker` direct usage still remains broken right?

**Comment by Mamaduka** [comment]
> Asking because this will fix withFontSizes but FontSizePicker direct usage still remains broken right?

The `FontSizePicker` now will return units and blocks can use those directly in attributes - #31314.

If we have to parse units into numbers there as well, then using `UnitControl` doesn't really make sense.

**Comment by youknowriad** [comment]
I was thinking something like: if the passed (previous) value passed to `FontSizePicker` is a number and the selected unit is "px", call onChange with just the number (and not the full string).

That said, I still prefer this PR because the proposal is a hack but the hack might be necessary depending on the scale of the breaking change.

**Review by youknowriad — APPROVED** [review]
Maybe this is good enough as both reported issues are specifically about withFontSizes

**Comment by Mamaduka** [comment]
So far, I've only seen reports about `withFontSizes`. It might be better to add a proposed hack if we see reports for the `FontSizePicker` component.

Side note: The problem can also be fixed by changing attribute type from "number" to "string."

**Comment by youknowriad** [comment]
One question though about the fix here. It seems that the proposed fix assumes that only `number` attributes are supported with `withFontSize`. Won't that break if we use that with the default `FontSizePicker`. Meaning someone could select "2em" but it would get applied as "2px" ?

**Comment by Mamaduka** [comment]
The `withFontSize` was only using numbers before, so users/devs expect numbers in their attributes.

But yeah, sadly, unit control values will have no effect.

**Comment by youknowriad** [comment]
What was the behavior in WP 5.7?

**Comment by Mamaduka** [comment]
The `FontSizePicker` was using `NumberControl`, so onChange was returning numbers.

What do you think about this idea?
* Use `parseCSSUnitValue` to parse values.
* If the unit is `px`, return parsed number, otherwise return the whole unit.

**Comment by Mamaduka** [comment]
Currently, I can think of the one issue with my proposed solution: if the user changes unit and attribute type is a number, it will trigger block validation.

**Comment by youknowriad** [comment]
> The FontSizePicker was using NumberControl, so onChange was returning numbers.

So we introduced units only in 5.7? In my mind, we did introduce that before but maybe I'm wrong?

**Comment by Mamaduka** [comment]
I think we introduced the units before, but we update NumberControl to UnitControl in FontSizePicker in 5.8. This is the PR - #31314.

**Comment by youknowriad** [comment]
Ok, so it seems the best approach would be to revert the FontSizePicker to `pixel` only (to avoid any breaking changes) and have a way to trigger multi-units by padding a `units` array or something like that (or potentially a boolean) which we should enable for core blocks all hooks. Is something like that possible?

Also curious about @aristath's opinion here.

**Comment by aristath** [comment]
Making the `FontSizePicker` use `UnitControl` instead of `NumberControl` was a significant improvement... Reverting that would be a big regression for designers.
What if, instead of reverting an improvement, we introduced a package/method to automatically convert all units to pixel values when needed? It should be possible to convert `2em` to `32px` and get `32` as a number...

**Comment by Mamaduka** [comment]
It looks like we already have `hasUnits` check for values:

https://github.com/WordPress/gutenberg/blob/ed8a7ad7ab127d59a1407941c2ec1e639bb440e6/packages/components/src/font-size-picker/index.js#L66-L68

I think we can use that check and do following:
```js
onChange( hasUnits ? nextSize : parseInt( nextSize, 10 ) );
```

This way, we'll consider the block's current attribute value and pre-defined sizes, allowing us to use units or numbers.

I will update PR shortly to test this case.

**Comment by youknowriad** [comment]
@aristath I'm not suggesting to revert but to make it optional (and enabled for all Core things) because switching the value from number to attribute is breaking all plugins that rely on the "value" of FontSizePicker being a number.

**Comment by Mamaduka** [comment]
@youknowriad, @aristath

Removed original fix and updated `onChange` logic in FontSizePicker component. When the component detects that `value` or first object in `fonSizes` doesn't use units, it will pass the number to the onChange callback.

It should fix the BC issue and allow developers to use units with FontSizePicker.

**Comment by youknowriad** [comment]
@Mamaduka maybe I'm asking too much but I feel like we should have an e2e test with the provided plugin to avoid future regressions. WDYT?

**Comment by Mamaduka** [comment]
I think this case is more suited for unit tests - `it should return number if value|sizes are numbers`.

Or do you want to test that it doesn't trigger block validation and attributes are correctly defined?.

**Comment by youknowriad** [comment]
Whatever works best for you :)

**Comment by Mamaduka** [comment]
@aristath, @youknowriad

Added unit tests.

File: packages/components/src/font-size-picker/test/index.js [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+import { render, fireEvent, screen } from '@testing-library/react';
+
+/**
+ * Internal dependencies
+ */
+import FontSizePicker from '../';
+
+describe( 'FontSizePicker', () => {
+	describe( 'onChange values', () => {
+		it( 'should not use units when the initial value is a number', () => {
```
Comment (youknowriad) [inline packages/components/src/font-size-picker/test/index.js:18]: Should we check that the units input is not render or do you think it should be rendered in this case?

Comment (Mamaduka) [reply packages/components/src/font-size-picker/test/index.js:18]: Do you mean units "switcher"? It's is still rendered but has no effect since we only use number values.

I think toggling between `NumberControl` and `UnitControl` based on has units value will introduce more complexity to the component.

CleanShot 2021-07-30 at 13 37 06

Comment (youknowriad) [reply packages/components/src/font-size-picker/test/index.js:18]: > I think toggling between NumberControl and UnitControl based on has units value will introduce more complexity to the component.

Can't we just pass an empty array of units or something like that in that case? It feels weird for a user to select "em" but have pixels applied.

Comment (Mamaduka) [reply packages/components/src/font-size-picker/test/index.js:18]: Done. It will now only display the "PX" unit label when there are no units.

**Comment by youknowriad** [comment]
This is great for me, thanks for all the iterations.

**Comment by Mamaduka** [comment]
Not a problem. I'm just happy we were able to find the right way to fix this issue.
