### PR TITLE
Image block: Fix responsive sizing in lightbox

### LINKED ISSUE #51556: Image block: Lightbox zoom animation cuts off image in Android landscape mode
### Description

When using the zoom animation for the image lightbox, the image is cut off in Android landscape mode.

### Step-by-step reproduction instructions

1. Ensure the Gutenberg Interactivity API experiments are enabled.
2. Add an image to a post.
3. Enable the lightbox for the images in Advanced > Behaviors under the block settings.
4. Publish the post and click on the image.
5. Make sure your Android device is in landscape mode and click on the image.
6. See that the image is cut off.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/5360536/7de47f54-03d3-46a9-93c3-3a2dbd799a77

### Environment info

- Gutenberg 16.0.0, WP 6.2.2
- Samsung Galaxy S8, Android v7.0
- Default Samsung browser

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by artemiomorales**
## What?

This revises the logic for calculating image dimensions in the lightbox, as well as adds some styles, because the images were getting stretched in some cases.

This was most pronounced on mobile, but it was visible on desktop as well.

## Why?

Addresses #51556 
The lightbox images should be scaled properly at all resolutions.

## How?

It calculates the inner width of the parent container based on the padding, then compares the aspect ratio of the image to the inner container to determine on which axis to resize the image.

## Testing Instructions

1. Ensure Interactivity API experiments are enabled
2. Add an image block to a post
3. Make sure the lightbox zoom animation is enabled under Advanced > Behaviors
4. View the post and click on the image
5. Test at different responsive sizes
6. See that the image is scaled and centered appropriately

Please test a horizontal image, a vertical image, and a square image, at various resolutions, on mobile as well as desktop, and in different browsers.

### Testing Instructions for Keyboard

N/A

#### Before

https://github.com/WordPress/gutenberg/assets/5360536/63e2623a-43cb-4c50-9d65-a64ad7583964

#### After

https://github.com/WordPress/gutenberg/assets/5360536/cab70934-b93e-44c7-a2f1-815f3e74ca5f

### CODE REVIEW

**Comment by artemiomorales** [comment]
Note: This PR is currently rebased on #51721 to avoid conflicts and make use of improvements in that branch.

Update: Since #51721 was merged, this branch has now been rebased on trunk.

**Comment by artemiomorales** [comment]
It appears the close button is not always visible on Android, or sometimes it appears too closely to the top corner of the screen. Likely this can be resolved by using the `safe-area-inset` properties (more info [here](https://developer.mozilla.org/en-US/docs/Web/CSS/env)). I'm currently looking into that. 

Other than that, I believe this PR is ready for feedback on the approach and any suggestions.

**Comment by artemiomorales** [comment]
> It appears the close button is not always visible on Android, or sometimes it appears too closely to the top corner of the screen. Likely this can be resolved by using the safe-area-inset properties (more info [here](https://developer.mozilla.org/en-US/docs/Web/CSS/env)). I'm currently looking into that.

After more testing, it turns out this was an issue related to the WP Twenty Twenty Two theme, which has horizontal overflow on some mobile Android devices. After switching to Twenty Twenty Three, the issue with the close button disappeared.

Even so, I added the `safe-area-inset` to the positioning of the close button to be safe.

I also added a couple of other miscellaneous fixes to improve the lightbox code, namely:
1.) Changing the moment when the responsive image `src` attribute is removed, as I was seeing a flash when swapping the images on on mobile
~~2.) Revising to use the the Interactivity API's built-in `mouseover` directive rather than defining my own callback in `data-wp-effect`~~ (Decided to do this one in a [separate PR](https://github.com/WordPress/gutenberg/pull/52067))

With that, I believe this PR is good to go 👍

File: packages/block-library/src/image/view-interactivity.js [hunk 1]
```diff
@@ -206,48 +207,48 @@ function setZoomStyles( imgDom, context, event ) {
...
+			targetWidth = containerInnerWidth;
 			targetHeight =
-				imgDom.naturalHeight * ( targetWidth / imgDom.naturalWidth );
+				( targetWidth * imgDom.naturalHeight ) / imgDom.naturalWidth;
 		} else {
-			targetHeight = containerHeight;
+			targetHeight = containerInnerHeight;
 			targetWidth =
-				imgDom.naturalWidth * ( targetHeight / imgDom.naturalHeight );
+				( targetHeight * imgDom.naturalWidth ) / imgDom.naturalHeight;
```
Comment (cbravobernal) [inline packages/block-library/src/image/view-interactivity.js:251]: Could have `imgDom.naturalWidth`, `imgDom.naturalHeight`, `containerInnerHeight` or `targetHeight` 0 as value?

If they are 0 or NaN in any moment, they will cause a warning/error.

**Review by cbravobernal — APPROVED** [review]
It works as described, feel free to take a look at the comment regarding unexpected warnings and should be good to go!

File: packages/block-library/src/image/view-interactivity.js (hunk 1 above)
Comment (artemiomorales) [reply packages/block-library/src/image/view-interactivity.js:251]: > If they are 0 or NaN in any moment, they will cause a warning/error.

Thanks for bringing this up! The only way I could see this happening is if a user inserts a broken external image with an incorrect URL, in which case other parts of WordPress also break. If an image is not fully loaded, it will return 0 for the `naturalWidth` and `naturalHeight`, but since we wait until the image is fully loaded to activate this part of the code, I don't believe that's currently an issue.

We can revisit this if any issues do arise in the future or if we revise the functionality, but for the moment I don't think handling this should be a blocker for this PR 👍

Comment (cbravobernal) [reply packages/block-library/src/image/view-interactivity.js:251]: What happens then if the user inserts a working external image, and then, suppose in couple of months, the external site closes and all the images are gone?

Comment (artemiomorales) [reply packages/block-library/src/image/view-interactivity.js:251]: Double checked this and we get some PHP errors due to `getimagesize()` that can actually likely be circumvented. I've captured the `getimagesize()` [in an issue](https://github.com/WordPress/gutenberg/issues/52172) and the implementation is going to change soon, so I can handle this issue then.

Comment (artemiomorales) [reply packages/block-library/src/image/view-interactivity.js:251]: Ok I [opened a pull request](https://github.com/WordPress/gutenberg/pull/52178) that fixes this 👍
