### PR TITLE
Colors: Fix color button border radii

### LINKED ISSUE #55051: Incorrect border radius when only one color panel item
The border radius is incorrect if there is only one color panel item. It should be `$radius-block-ui` on all corners. 

We currently add `.first` and `.last` classes to the `.block-editor-tools-panel-color-gradient-settings__item`, but they don't account for when there is only one item. 

You can see this example within the Featured Image block. 

| Current  | Expected |
| ------------- | ------------- |
|CleanShot 2023-10-04 at 12 18 28|CleanShot 2023-10-04 at 12 19 19|

### PR DESCRIPTION
**Pull request by ciampo**
Fixes #55051
Alternative approach to #55071

## What?

Applies the intended border radii to the last color item regardless of whether additional controls have been injected into the colors panel.

## Why?

The details matter.

## How?

There are 2 main aspects to this solution:
- The `ToolsPanelItem` component has been slightly tweaked, and it now applies the given `classname` only when the item is not being rendered as a placeholder
- Instead of using `first` and `last` classnames, this PR leverages a combination of the subsequent sibling selector (`~`), `:has()` and `:not()` to limit the first/last item logic to only the items that need to receive the border radius tweaks.

*NOTE: The `has()` selector [has decent support](https://caniuse.com/css-has), but at the time of writing it's not yet supported by all evergreen browsers (I'm looking at you, Firefox). While Firefox should include support in the next release, i decided to maintain the older (suboptimal) solution as a fallback for when `:has()` is not supported.*

## Testing Instructions

1. Edit a post and add a feature image and group block
2. Select the feature image block, open the style tab in the block inspector and confirm the overlay option there has border radii for all corners
3. Select the group block and, open the styles tab
4. Confirm the first color option has top left/right border radii
5. Confirm the last color option has bottom left/right border radii
6. Toggle on additional color controls from the color panel's menu
7. Ensure that hidden placeholder items do not interfere with the correct application of border radii
8. Test across browsers
9. When testing in Firefox, the issue described in #55051 should still be present, but everything else around the border radii should continue to work as expected.

### Testing Instructions for Keyboard

Changes are visual only. 

## Screenshots or screencast 

Screenshot 2023-10-05 at 2 37 10 pm

### CODE REVIEW

File: packages/components/src/tools-panel/tools-panel-item/hook.ts [hunk 1]
```diff
@@ -176,18 +176,16 @@ export function useToolsPanelItem(
...
 		const firstItemStyle =
 			firstDisplayedItem === label && __experimentalFirstVisibleItemClass;
 		const lastItemStyle =
 			lastDisplayedItem === label && __experimentalLastVisibleItemClass;
 		return cx(
 			styles.ToolsPanelItem,
-			placeholderStyle,
-			className,
+			shouldApplyPlaceholderStyles && styles.ToolsPanelItemPlaceholder,
+			! shouldApplyPlaceholderStyles && className,
```
Comment (aaronrobertshaw) [inline packages/components/src/tools-panel/tools-panel-item/hook.ts:188]: Nice solution! 👍 

This was the key I was missing in https://github.com/WordPress/gutenberg/pull/55071 to avoid the internal class name.

File: packages/block-editor/src/components/colors-gradients/style.scss [hunk 2]
```diff
@@ -77,18 +77,33 @@ $swatch-gap: 12px;
 	border-right: 1px solid $gray-300;
 	border-bottom: 1px solid $gray-300;
 
-	&.first {
+	// Identify the first instance as the item that is not a subsequent item to an
+	// item with the same class. The `~` selector is used instead of `+` to take
+	// into account any potential `ToolsPanelItem` placeholder item.
+	&:not(& ~ &) {
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/components/colors-gradients/style.scss]:
```suggestion
	// Identify the first visible instance as placeholder items will not have this class.
	&:nth-child(1 of &) {
```

With the change below avoiding the need for `:has`, and fixing Firefox, perhaps this selector is clearer and doesn't require the lengthy explanation. (See [coverage](https://caniuse.com/css-nth-child-of) for selector list in nth-child)

File: packages/block-editor/src/components/colors-gradients/style.scss [hunk 3]
```diff
@@ -77,18 +77,33 @@ $swatch-gap: 12px;
...
 		border-top-left-radius: $radius-block-ui;
 		border-top-right-radius: $radius-block-ui;
 		border-top: 1px solid $gray-300;
 	}
 
-	&.last {
+	// Identify the last instance as an item without any subsequent siblings
+	// with the same class. The `~` selector is used instead of `+` to take
+	// into account any potential `ToolsPanelItem` placeholder item.
+	&:not(:has(~ &)) {
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/components/colors-gradients/style.scss]:
```suggestion
	// Identify the last visible instance as placeholder items will not have this class.
	&:nth-last-child(1 of &) {
```

Unfortunately, in Firefox (without flags enabled) neither the current selector or the proposed fallback match. 

Selector lists for the `nth-child` pseudo-classes appear to have better [coverage](https://caniuse.com/css-nth-child-of) and work well for me testing across browsers.

It also has the added benefit of avoiding `:has` entirely for now and being much easier to grok.

File: packages/block-editor/src/components/colors-gradients/style.scss [hunk 4]
```diff
@@ -77,18 +77,33 @@ $swatch-gap: 12px;
...
 
+	// Less accurate fallback to detect the last instance of this item
+	// for older browsers not yet supporting the `:has()` selector.
+	@supports not selector(:has(*)) {
+		&.last {
+			border-bottom-left-radius: $radius-block-ui;
+			border-bottom-right-radius: $radius-block-ui;
+		}
+	}
+
```
Comment (aaronrobertshaw) [inline packages/block-editor/src/components/colors-gradients/style.scss]:
```suggestion
```

If we remove the use of `:has` in the selectors above we should also be able to get rid of this fallback CSS.

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for the alternative approach here @ciampo 👍 

It tests pretty well in general but fails to address the issue for me in Firefox, unless you toggle on the `layout.css.has-selector` flag via `about:config`. 

✅ Chrome
✅ Safari
✅ Edge
✅ Opera
🔴 Firefox

Screenshot 2023-10-11 at 10 13 58 am

I've proposed some tweaks that have the solution working across all browsers for me and are arguably easier to grok for newcomers to the code.

Let me know what you think

File: packages/block-editor/src/components/colors-gradients/style.scss (hunk 2 above)
Comment (andrewserong) [reply packages/block-editor/src/components/colors-gradients/style.scss]: TIL about `of` selector list argument 👍

**Review by andrewserong — COMMENTED** [review]
Nice attention to detail here, and good discussion, folks!

I quite like Aaron's suggestion of `&:nth-last-child(1 of &) {` and avoiding `:has()` where possible, and this PR is testing nicely for me with that change added in locally. Though it's probably not too big an issue if there are gentle / not particularly obvious fallbacks for FF, if we can avoid introducing `:has()` then hopefully we can help avoid folks accidentally using it in situations where the fallback wouldn't be quite so subtle.

Separately, I can't wait until FF supports it properly! 😄

**Comment by ciampo** [comment]
Thank you both for your suggestions! I've replaced the CSS selectors with the ones suggested by @aaronrobertshaw . Things are looking good on my end, so hopefully we should be able to merge this one soon!

> Separately, I can't wait until FF supports it properly! 😄

That should be very soon (in the next release, I think!) So only a matter of time until we can start using it in the project 🤞

**Review by aaronrobertshaw — APPROVED** [review]
> Things are looking good on my end, so hopefully we should be able to merge this one soon!

LGTM as well. 

The border radii are applied correctly in Chrome, Safari, Firefox, Edge, and Opera for me. 

Thanks for iterating here @ciampo 👍

**Comment by aaronrobertshaw** [comment]
While working with the design tools today, I spotted a weird layout issue with the color panel that appears to have been introduced through this PR. 

https://github.com/WordPress/gutenberg/assets/60436221/005b6043-e362-4d51-956b-1a9e239dacd2

Unfortunately, I ran out of time to find a proper solution to this, so I've created an issue: https://github.com/WordPress/gutenberg/issues/56470
