### PR TITLE
fix: update the logic of fetching current url in loginout block

### LINKED ISSUE #70024: Enhancement: core/loginout block
## What problem does this address?

Our current method for retrieving the current URL is as follows:

```php
$current_url = ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
```

- https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/loginout/index.php#L20C2-L20C105

This approach relies on `is_ssl()` and `$_SERVER['HTTP_HOST']`, and it accesses `$_SERVER['HTTP_HOST']` without checking if it is set. It also lacks proper usage of `wp_unslash()` and sanitization.

## What is your proposed solution?

Why rely on `$_SERVER['HTTP_HOST']` and `is_ssl()` when we can construct the URL directly using:

```php
home_url( wp_unslash( sanitize_url( $_SERVER['REQUEST_URI'] ) ) )
```

This provides a more secure and WordPress-native approach.

### PR DESCRIPTION
**Pull request by SH4LIN**
## What?

Closes: https://github.com/WordPress/gutenberg/issues/70024

## Why?

Our current method for retrieving the current URL is as follows:

```php
$current_url = ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
```

- https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/loginout/index.php#L20C2-L20C105

This approach relies on `is_ssl()` and `$_SERVER['HTTP_HOST']`, and it accesses `$_SERVER['HTTP_HOST']` without checking if it is set. It also lacks proper usage of `wp_unslash()` and sanitization.

## What is your proposed solution?

Why rely on `$_SERVER['HTTP_HOST']` and `is_ssl()` when we can construct the URL directly using:

```php
home_url( wp_unslash( sanitize_url( $_SERVER['REQUEST_URI'] ) ) )
```

This provides a more secure and WordPress-native approach.

## How?

- We are checking whether REQUEST_URI is set or not if it is not set then use home_url() if it is set then use home_url() with REQUEST_URI as it's path

## Testing Instructions

1. Add loginout block in your page or post.
2. After login or logout it should redirect to the page from where the request initiated

### CODE REVIEW

File: packages/block-library/src/loginout/index.php [hunk 1]
```diff
@@ -16,6 +16,7 @@
  */
 function render_block_core_loginout( $attributes ) {
 
+	// This current url fetching logic matches with the core: https://github.com/WordPress/WordPress/blob/6612d90f6c8ee9e917dc2dfcbcc24e120a5746ea/wp-includes/general-template.php#L528
 	// Build the redirect URL.
 	$current_url = ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
```
Comment (t-hamano) [inline packages/block-library/src/loginout/index.php]:
```suggestion
	/*
	 * Build the redirect URL. This current url fetching logic matches with the core.
	 *
	 * @see https://github.com/WordPress/wordpress-develop/blob/6bf62e58d21739938f3bb3f9e16ba702baf9c2cc/src/wp-includes/general-template.php#L528.
	 */
	$current_url = ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
```

- Let's use the PHPDoc format.
- It would be good to reference the development repo (`WordPress/wordpress-develop`), not the mirror repo (`WordPress/WordPress`),

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR! Could you update each section of the description according to the actual changes?

**Review by t-hamano — APPROVED** [review]
LGTM 👍
