### PR TITLE
Fix previews for blocks using InnerBlocks

### LINKED ISSUE #9897: Styles variations don't work for blocks using `InnerBlocks`
**Describe the bug**
I'd like to create a custom section block with additional style variants. The section is going to be a wrapper for multiple blocks - so parent block with some inner blocks.
Unfortunately, an attempt of choosing styles triggers an error _Cannot read property 'innerBlocks' of null_
Maybe there's a bug or maybe I'm doing wrong.

**To Reproduce**
Create the block:
```const { __ } = wp.i18n;
const { registerBlockType } = wp.blocks;
const { InnerBlocks } = wp.editor;

export default registerBlockType(
	'my-blocks/section',
	{
		title: __( 'My Section', 'my-blocks' ),
		description: __( 'A section of blocks.', 'my-blocks' ),
		category: 'layout',
		icon: 'index-card',
		keywords: [
			__( 'Text', 'my-blocks' ),
			__( 'Content', 'my-blocks' ),
			__( 'Paragraphs', 'my-blocks' ),
		],
		styles: [
			{ name: 'default', label: __( 'Regular', 'my-blocks' ), isDefault: true },
			{ name: 'intro', label: __( 'Intro', 'my-blocks' ) },
		],
		edit: () => {
			return (
				<InnerBlocks />
			);
		},
		save: () => {
			return (
				<div>
					<InnerBlocks.Content />
				</div>
			);
		},
	},
);
```

1. Insert the block "My Section" into the editor.
2. Click block switcher to choose between style variants.
3. The popup appears: "The editor has encountered an unexpected error.  Attempt Recovery  Copy Post Text  Copy Error"

The copied error is like below:
``` 
TypeError: Cannot read property 'innerBlocks' of null
    at t.value (http://mysite.local/wp-content/plugins/gutenberg/build/editor/index.js?ver=1536831520:12:157572)
    at t.value (http://mysite.local/wp-content/plugins/gutenberg/build/editor/index.js?ver=1536831520:12:157246)
    at commitLifeCycles (http://mysite.local/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:14939:22)
    at commitAllLifeCycles (http://mysite.local/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16040:7)
    at HTMLUnknownElement.callCallback (http://mysite.local/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:140:14)
    at Object.invokeGuardedCallbackDev (http://mysite.local/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:178:16)
    at invokeGuardedCallback (http://mysite.local/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:227:29)
    at commitRoot (http://mysite.local/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:16181:7)
    at completeRoot (http://mysite.local/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17196:34)
    at performWorkOnRoot (http://mysite.local/wp-content/plugins/gutenberg/vendor/react-dom.24169eaf.js:17141:9)
```

**Expected behavior**
Style variants to choose should appear without an error.

**Additional context**
- Gutenberg 3.8.0
- WordPress 4.9.8

### PR DESCRIPTION
**Pull request by youknowriad**
closes #9897 Alternative to #14767

This PR uses an inner block editor component to render the preview. 

**Testing instructions**

 - Add a style variations for the columns block, group block

```js
styles: [
		{ name: 'default', label: _x( 'Default', 'block style' ), isDefault: true },
		{ name: 'outline', label: __( 'Outline' ) },
		{ name: 'squared', label: _x( 'Squared', 'block style' ) },
	],
```

 - Check that you can switch style variations.

### CODE REVIEW

File: packages/block-editor/src/components/block-vertical-alignment-toolbar/index.js [hunk 1]
```diff
@@ -68,10 +68,10 @@ export default compose(
 	} ),
 	withViewportMatch( { isLargeViewport: 'medium' } ),
 	withSelect( ( select, { clientId, isLargeViewport, isCollapsed } ) => {
-		const { getBlockRootClientId, getEditorSettings } = select( 'core/editor' );
+		const { getBlockRootClientId, getSettings } = select( 'core/block-editor' );
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-vertical-alignment-toolbar/index.js]: This fix is unrelated but I thought I'd include here as a small fix (the block editor module should not rely on the editor data module) cc @getdave

File: packages/block-editor/src/components/block-preview/index.js [hunk 2]
```diff
@@ -31,18 +28,22 @@ function BlockPreview( props ) {
...
+	const block = createBlock( name, attributes, innerBlocks );
 	return (
 		<Disabled className="editor-block-preview__content block-editor-block-preview__content editor-styles-wrapper" aria-hidden>
-			<BlockEdit
-				name={ name }
-				focus={ false }
-				attributes={ block.attributes }
-				setAttributes={ noop }
-			/>
+			<BlockEditorProvider
```
Comment (gziolo) [inline packages/block-editor/src/components/block-preview/index.js]: That's neat ❤️

File: packages/block-editor/src/components/block-vertical-alignment-toolbar/index.js (hunk 1 above)
Comment (getdave) [reply packages/block-editor/src/components/block-vertical-alignment-toolbar/index.js]: Thanks

**Review by gziolo — COMMENTED** [review]
Code looks good but the visual part has some flaws:

Screen Shot 2019-05-15 at 16 57 50

File: packages/block-editor/src/components/block-preview/style.scss [hunk 3]
```diff
@@ -29,6 +29,17 @@
 	}
 }
 
+.block-editor-block-preview__content {
+	// Resetting the block editor paddings and margins
```
Comment (youknowriad) [inline packages/block-editor/src/components/block-preview/style.scss]: I think that's not the ideal fix as I think by default the block editor shouldn't have paddings and margins but It's not easy to reset without big implications. I'm fixing it for the preview right now.

**Comment by youknowriad** [comment]
@gziolo Good catch, It should be better now.

**Review by gziolo — APPROVED** [review]
It looks much better, but generally speaking, this preview could get some improvements as it doesn't look optimal for more complex blocks:

Screen Shot 2019-05-16 at 11 05 32
Screen Shot 2019-05-16 at 11 05 40

**Comment by youknowriad** [comment]
@gziolo I agree that sometimes a preview in such a small area is not the best solution. That said I'm happy this PR fixes the style variation issues for nested blocks.

**Comment by gziolo** [comment]
> @gziolo I agree that sometimes a preview in such a small area is not the best solution. That said I'm happy this PR fixes the style variation issues for nested blocks.

Yep, we should definitely land it. I wanted to make sure it gets noted by designers as well so they could include it in their future plans :D
