### PR TITLE
Editor: Resolve Publish button busy state styling regression

### LINKED ISSUE #15029: Publish button styling issue
**Describe the bug**
When you click on Publish button, it looks like this while it's in `isBusy` state. It appears `is-default` class is being added to the button even when it's set to primary.

Screen Shot 2019-04-18 at 3 16 42 AM

**To reproduce**
1. Open Gutenberg and click on Publish.
2. Or you can manually add `is-busy` class to the button.

**Expected behavior**
Color to be blue.

**Desktop (please complete the following information):**
 - OS:MacOS
 - Browser Firefox latest

### PR DESCRIPTION
**Pull request by aduth**
Fixes #15029

This pull request seeks to resolve an issue where the Publish button (or any busy, disabled button) would display with incorrect styling.

Before|After
---|---
Before|After

**Implementation Notes:**

There are two separate changes which independently resolve the issue, but which together help reduce redundancy and assure broader applicability:

- A button should not be assigned `is-default` styling if it is is a primary button, since the "default" styling is the gray background (which primary styling is intended to supersede)
- The publish button does not need large styling (which is how `is-default` was applied) because all style properties of `is-large` ([source](https://github.com/WordPress/gutenberg/blob/f4d5d500630e44e4f2b0cb160fed7c0ca2ee353a/packages/components/src/button/style.scss#L191-L195)) are substituted in post editor header styles ([[1]](https://github.com/WordPress/gutenberg/blob/f4d5d500630e44e4f2b0cb160fed7c0ca2ee353a/packages/edit-post/src/components/header/style.scss#L95-L96), [[2]](https://github.com/WordPress/gutenberg/blob/f4d5d500630e44e4f2b0cb160fed7c0ca2ee353a/packages/edit-post/src/components/header/style.scss#L112-L116)). This also ensures consistency with the "Toggle" variant of the same button, which already doesn't apply `isLarge` and, aside from text of the button is intended to appear visually identical.

**Testing Instructions:**

Verify that upon Publishing a post, the intermediate state of the save request displays as shown in the "After" screenshot above.

### CODE REVIEW

File: packages/components/src/button/index.js [hunk 1]
```diff
@@ -28,7 +28,7 @@ export function Button( props, ref ) {
 
 	const classes = classnames( 'components-button', className, {
 		'is-button': isDefault || isPrimary || isLarge || isSmall,
-		'is-default': isDefault || isLarge || isSmall,
+		'is-default': ! isPrimary && ( isDefault || isLarge || isSmall ),
```
Comment (jorgefilipecosta) [inline packages/components/src/button/index.js]: Would the condition `isDefault || ! isPrimary && ( isLarge || isSmall )`also work? I guess when someone passes `isDefault` there is an expectation the is-default class is added for sure. Otherwise, maybe we can add a small note on  https://github.com/WordPress/gutenberg//blob/dd9bf47ff07680d672efc5b31abac268e2cb69c0/packages/components/src/button/README.md#L128 saying the prop is ignored if isPrimary prop is also passed.

Comment (aduth) [reply packages/components/src/button/index.js]: Hm, well, the root of the problem is that nobody should ever apply _both_ `isPrimary` and `isDefault`, so your expectation may be valid in considering `isDefault` alone, but not in combination with `isPrimary`.

That being said, your suggestion still seems like a slight improvement in sensibly mapping `isDefault` and `isPrimary` to their respective classes, irrespective the styling conflict which would likely ensue from this choice.

Comment (aduth) [reply packages/components/src/button/index.js]: Updated in cc9a75540.

**Comment by youknowriad** [comment]
I think the button is supposed to be animated. I'm not seeing the animation?

**Comment by youknowriad** [comment]
nevermind, I had the "disable animations" plugin enabled :)

**Comment by youknowriad** [comment]
nevermind, I had the "disable animations" plugin enabled :)

**Review by youknowriad — APPROVED** [review]
