### PR TITLE
Run registerBlockType hook over deprecated settings

### LINKED ISSUE #16328: Group blocks won't validate after update to 6.0
**Describe the bug**
After updating to 6.0, every group blocks show the validation error "This block contains unexpected or invalid content.". The "Resolve" function won't work. It converts the block to a Custom HTML. The console shows this :
Block validation: Block validation failed for `core/group` ({name: "core/group", save: ƒ, category: "layout", attributes: {…}, title: "Group", …}).
Content generated by `save` function:
```
<div class="wp-block-group strate accent" id="group-125"><div class="wp-block-group__inner-container"></div></div>
```
Content retrieved from post body:
```
<div class="wp-block-group strate accent" id="group-125">
</div>
```

**Desktop:**
 - OS: Windows 10, version 1703
 - Browser : Chrome
 - Version : 75.0.3770.100

**Additional context**
As you can see in the HTML outputed by the console, i have a custom function that adds an id to every group blocks. They also have custom classes added in the advanced tab ("strate" and "accent").

If someone have an idea on how i could fix this via the database it would be appreciated. All my site content is wrapped in a group. As for now, i can't do any modification to my site without loosing a page content...

Thanks, and sorry for the bad english...

### PR DESCRIPTION
**Pull request by talldan**
## Description
Alternative attempt to fix #16328. Unfinished and unlikely to be the right fix, but this PR should hopefully generate some discussion about the right way to fix the issue.

**Background**
After some digging into the above issue, I discovered that the `supports` settings for blocks relies on the `registerBlockType` filter. This filter adds an extra `anchor` attribute to blocks that support anchors.

Unfortunately the `registerBlockType` filter only runs on the main block settings, not deprecated block settings. When falling back to an older deprecation the attribute is not present and is never sourced from the HTML. In the case reported in the related issue, this caused a validation issue.

Other `supports` settings (e.g. align) also don't work with deprecations, but don't cause validation issues since `data-` attributes are ignored by the validator.

The fix here is to also run the `registerBlockType` filter over each object in the deprecation array.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by talldan** [comment]
Not sure this is the right thing to do as it might have undesired consequences for other implementors of this filter (e.g. for plugins).

File: packages/blocks/src/api/test/registration.js [hunk 1]
```diff
@@ -337,6 +337,42 @@ describe( 'blocks', () => {
...
+						},
+						{
+							save() {
+								return 2;
+							},
+						},
+					],
+				};
+
+				addFilter( 'blocks.registerBlockType', 'core/blocks/without-title', ( settings ) => {
```
Comment (youknowriad) [inline packages/blocks/src/api/test/registration.js]: Should we remove the filter after the test to ensure it doesn't mess with other tests?

**Review by youknowriad — APPROVED** [review]

File: packages/blocks/src/api/test/registration.js (hunk 1 above)
Comment (talldan) [reply packages/blocks/src/api/test/registration.js]: It's already handled in an `afterEach` on line 317.

**Comment by aduth** [comment]
> Not sure this is the right thing to do as it might have undesired consequences for other implementors of this filter (e.g. for plugins).

Might be worth doing a look over keyword matches from the plugin repository using [wpdirectory.net](https://wpdirectory.net/).

Example: https://wpdirectory.net/search/01DESKYX62AMYKSZE8KJ5FBQKF

**Comment by talldan** [comment]
> Might be worth doing a look over keyword matches from the plugin repository using wpdirectory.net.

> Example: https://wpdirectory.net/search/01DESKYX62AMYKSZE8KJ5FBQKF

Thanks for the link @aduth. It mostly looks ok, there's quite a bit of minified code, though.

There were a couple of plugins that use the filter to completely replace/enhance a block. For example, Jetpack:
https://github.com/Automattic/jetpack/blob/4c63a49fc0139c3296248e09ee69dedb537e024f/extensions/blocks/videopress/editor.js

This change would result in a bunch of properties being added to the deprecated settings that would go unused (`deprecated`, `edit`, `transform`). Probably not harmful, but perhaps it'd be better for the code in this PR to pick just `supports`, `save` and `attributes` from the filter return value?

Will also add an issue for Jetpack on how they're setting that deprecated value. If the video block is deprecated in core, that could cause some issues!

**Comment by youknowriad** [comment]
Let's ship this. The plugin releases will allow us to detect any potential issue with it we might have missed.

**Comment by talldan** [comment]
👍
