### PR TITLE
Try: Restore block mover for floats.

### LINKED ISSUE #12736: Block mover hidden when left or right aligned
**Describe the bug**
Left or right aligned blocks may have hidden move controls if it floated. This looks intentionally added in https://github.com/WordPress/gutenberg/pull/10085.

Could be related to https://github.com/WordPress/gutenberg/issues/12290

pull quote test

**To Reproduce**
1. Create a pull quote block.
2. Left or right align the pull quote block.
3. Attempt to drag or move the pull quote block.

**Expected behavior**
Expected the mover controls to be visible when hovering over the pull quote block.

**Screenshots**

screen shot 2018-12-09 at 2 45 30 pm

# Initial Investigation

* While a non floated block pull-quote has a class="editor-block-mover is-visible" the block controls display as expected.
* While a pull quote block is floated left or right and has class="editor-block-mover is-visible" the block move controls are hidden. This is caused by an overflow on the parent container.

```scss
//editor/style.css line 349
.editor-block-list__layout .editor-block-list__block[data-align="left"] .editor-block-mover, .editor-block-list__layout .editor-block-list__block[data-align="left"] .editor-block-list__block-mobile-toolbar, .editor-block-list__layout .editor-block-list__block[data-align="right"] .editor-block-mover, .editor-block-list__layout .editor-block-list__block[data-align="right"] .editor-block-list__block-mobile-toolbar {
    display: none;
}
```

Turning off display none will display the block menu controls. However, the controls disappear while visible for the paragraph block that the pull quote is floated around.

You can get the block working properly again by changing `left: -30px` to `left: 0;'. However, the movement controls will display in an awkward place.

screen shot 2018-12-09 at 3 03 29 pm

```scss
.editor-block-list__block > .editor-block-mover {
    padding-right: 2px;
    // left: -30px;
    left: 0; // moves the block back in the container.
    display: none;
}
```

### PR DESCRIPTION
**Pull request by jasmussen**
This PR hopes to fix #12736, #11424, #10300.

Currently we hide the block mover for any floated block. We do this because if you have a left floated image followed by a paragraph, the block mover for the image would overlap exactly with the block mover for the subsequent paragraph block. This would cause moving a float to be fiddly and virtually impossible as the hover states for the two conflicted.

This PR is an experiment to mitigate, or possibly fix that. It's a try branch because it is not necessarily a solid fix. What this PR does:

- It makes it so the block mover cannot be invoked when only hovering a float, but when the float is selected they are permanently visible.
- It changes some z-indexes so floats always have a higher z-index than not a float.
- It changes the footprint of the side-UI container to "cover up" the underlying paragraph block, so it won't invoke unlesss you move the mouse below the footprint.

This is best explained in some GIFs. Here's one where the block mover footprint is coral colored to help explain what's going on:

float movers

Here's without that coral debug color:

without debug

The reason this is a "Try" branch is that when you move the mouse over the adjacent paragraph, the block mover is show as overlapping the selected floats block mover. But due to the rearranging of z-indexes, at least this is only a visual issue. A click on the floats block mover will still work as intended.

Why can't the float have on-hover block movers like every other block, you ask? Picture again the test-case of a left floated image followed by a paragraph of text. In this case, hovering over the image would show a block mover that would visually appear to be that of the paragraph block. By showing it when the float is selected, the context is clear.

We could experiment with not showing the hover block mover for float-adjacent blocks when hovered, but this isn't feasible because you might have a float, and then a block that clears this float, in which case the rule would break down.

Lay your thoughts on me.

### CODE REVIEW

File: packages/editor/src/components/block-list/block.js [hunk 1]
```diff
@@ -553,25 +553,25 @@ export class BlockListBlock extends Component {
...
-									}
-									onDragStart={ this.onDragStart }
-									onDragEnd={ this.onDragEnd }
-								/>
-							) }
 							{ isFirstMultiSelected && (
 								<BlockMultiControls rootClientId={ rootClientId } />
 							) }
 							<div className="editor-block-list__block-edit">
+								{ shouldRenderMovers && (
```
Comment (jasmussen) [inline packages/editor/src/components/block-list/block.js]: For the block mover to be able to work for a right-floated block, it has to be inside `.editor-block-list__block-edit`, or the control will show up way on the left of the main column. Same case as when we refactored the floats, essentially.

File: packages/editor/src/components/block-list/style.scss [hunk 2]
```diff
@@ -1,8 +1,8 @@
 .editor-block-list__layout .components-draggable__clone {
-	// Hide the Block UI when dragging the block
-	// This ensures the page scroll properly (no sticky elements)
+	// Hide the Block UI when dragging the block.
```
Comment (jasmussen) [inline packages/editor/src/components/block-list/style.scss]: Just a few comment cleanups while I'm in here.

**Comment by chrisvanpatten** [comment]
I think the iteration could happen in a separate PR but I think this is another case where some version of #7211 would help with the mover overlap issues.

**Comment by jasmussen** [comment]
> I think the iteration could happen in a separate PR but I think this is another case where some version of #7211 would help with the mover overlap issues.

I know I've been skeptical in the past, but I'm starting to agree especially for nested blocks and now floats. I still don't really see the value it brings to top level blocks, except perhaps the consistency it would bring, but for those blocks which for now are still the most common, the extra chrome behind the controls just seems heavier.

**Comment by chrisvanpatten** [comment]
@jasmussen Yeah it's primarily a consistency thing, although I do think it will be more practically valuable as the editor starts to reflect the front-end more and more and the "base level" editor canvas isn't so bare. But that could be a future iteration; it could definitely focus just on InnerBlocks for the moment.

**Comment by jasmussen** [comment]
@youknowriad For now I've set this in "future/phase 2". But I would appreciate a pair of eyes if you have time — could we get this into a plugin release like 4.9? I'd love for it to land early between major releases.

**Comment by youknowriad** [comment]
I've put this PR in 4.9 to get some review 👀 It doesn't mean it's going to ship there though. Depends on the reviews.

**Comment by jasmussen** [comment]
I'm not necessarily super antsy that it land in 4.9 or even 5.0, but I appreciate it being on the radar! Thanks Riad! 💕

File: packages/editor/src/components/block-list/style.scss [hunk 3]
```diff
@@ -1,8 +1,8 @@
...
+	// This ensures the page scroll properly (no sticky elements).
 	.editor-block-contextual-toolbar {
-		// I think important is fine here to avoid over complexing the selector
+		// I think important is fine here to avoid over complexing the selector.
```
Comment (ZebulanStanphill) [inline packages/editor/src/components/block-list/style.scss]:
```suggestion
		// I think important is fine here to avoid over-complicating the selector.
```

File: packages/editor/src/components/block-list/style.scss [hunk 4]
```diff
@@ -168,7 +168,7 @@
 		background-color: $blue-medium-highlight;
 	}
 
-	// selection style for multiple blocks
+	// Selection style for multiple blocks.
 	&.is-multi-selected *::selection {
```
Comment (ZebulanStanphill) [inline packages/editor/src/components/block-list/style.scss]:
```suggestion
	&.is-multi-selected ::selection {
```
I think that asterisk is redundant.

Comment (jasmussen) [reply packages/editor/src/components/block-list/style.scss]: Good thought, but I'd prefer not actually making this change in this PR. It is already sort of big surgery and I'd like to minimize the changes as much as possible. Given that code did not change in this PR, only the comment, I'd prefer to look at this separately.

**Comment by jasmussen** [comment]
Rebased, and addressed feedback. Tested again. I think this is good to go, it seems to work well for me. It would be good to get in _after 5.1_, but before 5.2, so I think now might be a good time to merge this.

One thing I fixed was hiding the block mover from the gray ghost when dragging:

dragging

**Comment by gziolo** [comment]
I only noticed one inconsistency with other blocks. Movers show up even when I move mouse close to the right edge of the block. It behaves differently with blocks that span the width of the editor:

screen shot 2019-02-04 at 16 10 17

**Review by gziolo — APPROVED** [review]
Nice improvement 👍

**Comment by jasmussen** [comment]
> I only noticed one inconsistency with other blocks. Movers show up even when I move mouse close to the right edge of the block. It behaves differently with blocks that span the width of the editor:

Yes, this is intentional. The hover effect is gone from floats, and the movers are now permanently visible when the block is selected.

When I worked on this, I recall it feeling best this way, notably in situations where you have a right floated image, then a text block that wraps around that, and then have the text block seleted. I can take another glance and see if it's possible to keep the old behavior and have a good experience, but I recall this change being very intentional and part of enabling it for floats in the first place (even if the exact reason now escapes me).

**Comment by ZebulanStanphill** [comment]
@kjellr In that second GIF, it seems like those movement control buttons should always have a solid background.

**Comment by jasmussen** [comment]
Rebased, to keep this fresh. 

It seems like this is mostly ready to go, the remaining sticking point being what Kjell and ZebulanStanphill brought up, about overlap.

Is the following the solution?

bgs

If yes, let me know and I can push that as a fix and then merge.

**Comment by kjellr** [comment]
> Is the following the solution?

Sure, that works for me. We can push that in and keep iterating. 👍

**Comment by ZebulanStanphill** [comment]
@jasmussen That change looks good to me.

**Comment by mapk** [comment]
The improvements are great, but the border on each of the positioning elements does leave a desire for iteration. 😉 

I tried to see if we can just add the bordered state to the arrows only (not sure if it helps).

screen shot 2019-02-05 at 5 00 39 pm

Let's not let this hold up the PR though. Thanks for the work, Joen!

**Comment by jasmussen** [comment]
Added the borders around the movers for floats, as proposed. 

> I tried to see if we can just add the bordered state to the arrows only (not sure if it helps).

I do agree that the movers could be visually enhanced a fair bit — perhaps just making it feel like a "pill button with separators" instead of 3 stacked rounded buttons might help? The background is important even for the drag handle when it overlaps colored backgrounds or images. 

But right now this uses the same CSS as any nested blocks, which also have the bordered movers. Let's explore improving those styles separately. I know @chrisvanpatten has ideas around that also.

**Comment by jasmussen** [comment]
@gziolo Unless you object, I think we should land this once the checks pass!

**Comment by gziolo** [comment]
Merged 🎉

**Comment by jasmussen** [comment]
`itshappening.rmvb`!

**Comment by senadir** [comment]
Hi, this fix seems to cause a new bug #15923, #15930
setting the image block z-index to 81 overrides the block toolbar 
this pull request should fix it #15966 while keeping everything right
