### PR TITLE
Image: Display errors after failed upload

### LINKED ISSUE #39116: Image Block should display error message after failed upload
### Description

Using WordPress’ `wp_handle_upload_prefilter` filter, I limited the max size of the images I can upload to my media library (I changed the value to `10kb` for demo purposes):

```php
function nelio_max_image_size( $file ) {
  $size     = $file['size'] / 1024;
  $is_image = strpos( $file['type'], 'image' ) !== false;
  $limit    = 10;
  if ( $is_image && $size > $limit ) {
    $file['error'] = "Image files must be smaller than {$limit}kb";
  }
  return $file;
}
add_filter( 'wp_handle_upload_prefilter', 'nelio_max_image_size' );
```

If I upload the image to the media library directly, I get the expected error message:

image

However, when uploading the image from Gutenberg’s image block directly, it gets stuck and never reports the issue to the end user:

image

Even though the REST API returned an error:

image

### Step-by-step reproduction instructions

1. Add the aforementioned PHP filter
2. Try to upload an image bigger than 10kb via Gutenberg
3. Get stuck

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 5.9.1
- Both with and without Gutenberg 12.6.1
- Linux Mint 19.1
- Firefox 89.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
Resolves #39116

PR ixes the issue when the upload error message wasn't displayed. Also re-uses `onUploadError` callback for error messages.

## Testing Instructions
1. Open a Post or Page
2. Insert an Image Block.
3. Fake upload error (see code below).
4. Confirm that the upload error message is displayed and the image isn't stuck in the upload state.

### Example

```php
add_filter( 'wp_handle_upload_prefilter', function( $file ) {
	$file['error'] = 'Image files must be smaller than 10kb';
	return $file;
} );
```

## Screenshots 
**Before**

https://user-images.githubusercontent.com/240569/156501201-c88eb097-55c7-4500-9148-4660217d14a5.mp4

**After**

https://user-images.githubusercontent.com/240569/156501218-d3daf46b-52be-4c8f-bc76-291698071ec2.mp4

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [x] I've updated related schemas if appropriate.

### CODE REVIEW

File: packages/block-library/src/image/edit.js [hunk 1]
```diff
@@ -304,15 +310,7 @@ export function ImageEdit( {
 					onSelectImage( img );
 				},
 				allowedTypes: ALLOWED_MEDIA_TYPES,
-				onError: ( message ) => {
-					isTemp = false;
```
Comment (Mamaduka) [inline packages/block-library/src/image/edit.js:308]: @glendaviesnz I reverted the change from #34371. Settings `temporaryURL` to undefined also fixed the issue.

**Comment by glendaviesnz** [comment]
I tested this and it works if just setting the default error message so every image fails, but in the gallery if an image really fails due to exceeding the php.ini limit then it goes back to the endless spinner:

With every image getting fake error:
image-all-fake-error

With php.ini upload_max_filesize set to 1MB, so one image getting a `real` upload error:
image-error-with-ini-failure

**Comment by glendaviesnz** [comment]
Adding back the `isTemp = false;` seems to make it work in both instances:
image-error-fix

**Comment by Mamaduka** [comment]
Thanks for testing, @glendaviesnz.

It's interesting that we get different behavior for emulated and actual errors. I reverted the `isTemp` change, but I think we should revisit these two side-effects in the future.

File: packages/block-library/src/image/edit.js [hunk 2]
```diff
@@ -171,6 +171,7 @@ export function ImageEdit( {
 	function onUploadError( message ) {
 		noticeOperations.removeAllNotices();
 		noticeOperations.createErrorNotice( message );
+		setTemporaryURL( undefined );
```
Comment (Mamaduka) [inline packages/block-library/src/image/edit.js:179]: I realized that we only need to reset the state. The `onSelectImage` will remove attributes for us. It's called during the error but with an undefined `media` argument.

Comment (glendaviesnz) [reply packages/block-library/src/image/edit.js:179]: This is a weird one 🤔  - for me this change causes the php.ini upload limit error to be ignored, but only in the gallery:

https://user-images.githubusercontent.com/3629020/156953603-0c8ec8ea-1c8a-4829-8eef-afcb3c039832.mp4

Seems like there are a couple of `gotchas` with how gallery versus individual images blocks are behaving with these errors, which would be good to work out why and resolve, or at least document. I will try and get a closer look at it later today.

Comment (glendaviesnz) [reply packages/block-library/src/image/edit.js:179]: I had another look at it, and for some reason it seems like the standalone Image block goes through an extra render cycle which causes image to be removed and error to display, but this doesn't happen if the Image block is in a Gallery, but I can't work out why, as the Gallery essentially just delegates the upload process to the Image block. I will take another look at it tomorrow if you don't have any ideas. 

We could just put the [setAttributes](https://github.com/WordPress/gutenberg/pull/39178/commits/de17283b98005198a3337423196f133ed4237b25) back, but it would be nice to know why this is happening.

**Comment by glendaviesnz** [comment]
> but I think we should revisit these two side-effects in the future.

I would love to refactor the whole Image block at some point - the `<Image>` component, in particular, has ended up quite large and hard to reason about.

File: packages/block-library/src/image/edit.js (hunk 2 above)
Comment (Mamaduka) [reply packages/block-library/src/image/edit.js:179]: Thanks for testing, @glendaviesnz. I will revert `setAttributes` removal.

**Review by glendaviesnz — APPROVED** [review]
Tested again and this now works for me in all the following instances:

- Single image with mocked error and genuine error from exceeding ini max file setting
- Gallery images with mocked error and genuine error from exceeding ini max file setting

**Comment by Mamaduka** [comment]
Thanks for the reviews, @glendaviesnz 🙇
