### PR TITLE
Sort spacing sizes when all slugs begin numerically

### LINKED ISSUE #62520: theme.json schema change for spacingSizes pattern incorrect
With this change to `spacingSizes` and `theme.json` v3, the schema was changed to specifically add a numeric string pattern instead of any string for the `slug` property: https://github.com/WordPress/gutenberg/pull/61842

If I use a non-numeric string for `slug`, this gave no warning in the past:

```json
"settings": {
	"spacing": {
		"spacingSizes": [
			{
				"name": "Base",
				"size": "clamp(1.06rem, 0.37cqi + 0.95rem, 1.19rem)",
				"slug": "base"
			}
		]
	}
}
```

Now, VS Code or other schema checkers will show a warning that the `slug` doesn't match the pattern.

I am concerned that theme authors who were previously using non-numeric strings in the past will think they must migrate/upgrade their spacing sizes in some way, which would not be something we'd want to ask theme authors to do.

Not to mention that the Theme Handbook has shown non-numeric slugs as valid examples since last year: https://developer.wordpress.org/themes/global-settings-and-styles/settings/spacing/

I think the new `description` is fine:

> Unique identifier for the space size preset. Will be sorted numerically. For best cross theme compatibility these should be in the form '10','20','30','40','50','60', etc. with '50' representing the 'Medium' size step.

However, I would remove the `pattern` from the schema because non-numeric strings can and still do work in v3.

CC: @ajlende

### PR DESCRIPTION
**Pull request by ajlende**
## What?

Changes the sorting heuristic for `spacingSizes` from having more than one origin to all slugs from all origins beginning numerically.

Removes the numeric requirement for slugs in the schema.

## Why?

Fixes #62520

## How?

> The heuristics for sorting that I added in https://github.com/WordPress/gutenberg/pull/62199 were focused on figuring out v2 vs v3 schemas. If we do away with heuristics and simply sort when all slugs start with a number, the sorting becomes an opt-in feature by the theme using numeric slugs. The numeric slugs become a bonus feature rather than a requirement for correct operation.
>
> We'll still want to update the UI to have sections, but I don't think that's critical to fix until we have UI for adding user origin spacing presets. At that point, if a user adds a new preset that isn't numeric, then that will effectively opt-out of the merging and sorting of presets even if the theme is using numeric slugs.

https://github.com/WordPress/gutenberg/issues/62520#issuecomment-2167205559

## Testing Instructions

Try numeric and non-numeric slugs with and without defaults enabled to see if sorting happens when you would expect.

### CODE REVIEW

File: packages/block-editor/src/components/spacing-sizes-control/hooks/use-spacing-sizes.js [hunk 1]
```diff
@@ -44,15 +44,8 @@ export default function useSpacingSizes() {
...
-		// preserve order for themes that don't include default presets and
-		// want a custom order.
-		if (
-			( customSizes.length && 1 ) +
-				( themeSizes.length && 1 ) +
-				( defaultSizes.length && 1 ) >
-			1
-		) {
+		// Using numeric slugs opts-in to sorting by slug.
+		if ( sizes.every( ( { slug } ) => /^[0-9]/.test( slug ) ) ) {
```
Comment (ajlende) [inline packages/block-editor/src/components/spacing-sizes-control/hooks/use-spacing-sizes.js:48]: I have this just checking that it _starts with_ a number, allowing slugs like `50-medium` to be sorted, but maybe it would make more sense to only sort slugs that are completely numeric.

Comment (scruffian) [reply packages/block-editor/src/components/spacing-sizes-control/hooks/use-spacing-sizes.js:48]: I think this is good

**Review by scruffian — APPROVED** [review]
Look good, and works as expected in my testing.

**Review by justintadlock — APPROVED** [review]
Changes look good to me. Sorting works, and I think it's OK to continue sorting when the slug begins with the number.

**Comment by ellatrix** [comment]
I just cherry-picked this PR to the wp/6.6-beta-3 branch to get it included in the next release: 8ffc66ffd7
