### PR TITLE
navigation block: fix empty site-log `li` element in the dom

### LINKED ISSUE #43470: Empty Site logo block in navigation block results in empty li item on front
### Description

When the site logo block is added to the navigation block, but no image is selected, there is a n empty `<li>` item in the navigation.

### Step-by-step reproduction instructions

1. Add a navigation block with two items.
2. Place a site logo block between the two items. The site logo block should not have an image assigned.
4. Save and view the front.
5. Confirm that there is a larger space between the two menu items.
6. View the page source to confirm that there is an empty `<li></li>` where the logo would have been placed if an image had been selected.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WordPress 6.0.1
Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by amustaque97**
## What?

Add a condition to verify that the site-logo is not null. 

## Why?

Don't create a `li` element in the dom when the site-logo is empty. If there is an empty `li` tag, it will add some extra space on the frontend.

## How?

An empty condition is added if `core/site-logo` is non-empty then add a `li` element in the dom or else it will continue the rest of the statements.

## Testing Instructions

- Add a navigation block with two items.
- Place a site logo block between the two items. The site logo block should not have an image assigned.
- Save and view the front.
- Confirm that there is no larger space between the two menu items.
- View the page source to confirm that there is no empty `<li></li>` 

Fixes: https://github.com/WordPress/gutenberg/issues/43470

### CODE REVIEW

**Review by carolinan — APPROVED** [review]
This is working well in my test, thank you.

File: packages/block-library/src/navigation/index.php [hunk 1]
```diff
@@ -556,7 +556,7 @@ function render_block_core_navigation( $attributes, $content, $block ) {
 			$is_list_open       = false;
 			$inner_blocks_html .= '</ul>';
 		}
-		if ( 'core/site-title' === $inner_block->name || 'core/site-logo' === $inner_block->name ) {
+		if ( 'core/site-title' === $inner_block->name || ( 'core/site-logo' === $inner_block->name && $inner_block->render() ) ) {
 			$inner_blocks_html .= '<li class="wp-block-navigation-item">' . $inner_block->render() . '</li>';
 		} else {
 			$inner_blocks_html .= $inner_block->render();
```
Comment (ockham) [inline packages/block-library/src/navigation/index.php]: One thing we could do is introduce a temporary var before this conditional to hold the result of `$inner_block->render()` so we don't call it twice (although the PHP interpreter will likely take care of that optimization for us, so it's probably not crucial):

```suggestion
		$inner_block_content = $inner_block->render();
		if ( 'core/site-title' === $inner_block->name || ( 'core/site-logo' === $inner_block->name && $inner_block_content ) ) {
			$inner_blocks_html .= '<li class="wp-block-navigation-item">' . $inner_block_content . '</li>';
		} else {
			$inner_blocks_html .= $inner_block_content;
```

**Review by ockham — APPROVED** [review]
Thanks @amustaque97! This LGTM.

I had a minor [suggestion](https://github.com/WordPress/gutenberg/pull/44049/files#r968517847), but it's not crucial. Feel free to apply or ignore 😊
