### PR TITLE
Fix link popover keyboard accessibility

### LINKED ISSUE #3350: Cannot edit existing link in URLInput
When inserting a link or a "@" username mention, clicking on a link or moving the caret on a link makes an inline "popup" appear. The popup contains controls to edit the link, remove the link, additional settings (e.g. open in a new window):

screen shot 2017-11-06 at 15 23 54

Although the popup is "inline" and it is possible to press Tab and move focus to it, there are a few missing features compared to the similar link inline toolbar in the Classic Editor:

- `Alt+F8` should move focus to the popup
- `Escape` should move focus back from the popup to the link, to the previous caret position or selection
- pressing Tab and arrow keys should loop through the popup controls
- tabbing should be constrained within the popup

Also, to match the current functionality in the Classic Editor, `Cmd/Ctrl + K` should switch the popup to edit mode. Currently, it is only possible to click the two edit buttons, with different results:

screen shot 2017-11-06 at 16 05 50

- clicking the Edit button within the modal, will switch to edit mode populating the input field with the current link URL
- clicking the Edit button in the top fixed toolbar, will switch to edit mode but the input field is empty

Also, when editing an username "mention", what should happen? Should the popup appear in edit mode and give users the ability to manually edit the link to the user page or present again the list of username suggestions?

Current behavior:

screen shot 2017-11-06 at 16 09 51

### LINKED ISSUE #8266: Can't edit an existing link using only the keyboard
In Gutenberg 2.9.0 it was possible to;
- select an existing link in the content

screen shot 2018-07-28 at 18 08 03

- press Tab and focus was moved on the link dialog: this way it was possible to edit a link using only the keyboard

screen shot 2018-07-28 at 18 10 12

This worked because the link toolbar was placed "inline" right after the block editable area. Pressing tab followed the normal tab order, moving focus to the following focusable element in the native tab sequence.

After the changes in #6911 this is no longer true. The link toolbar is now placed within a "popover" component and thus it's at the end of the markup, way far from the block content. The link toolbar is not the next following focusable element any longer.

Right now I can't find a way to edit an existing link using only the keyboard:
- pressing Tab takes me elsewhere
- pressing Cmd+K makes the link toolbar appear but it's in "insert mode" and doesn't allow me to modify the existing link

I'd like to remind everyone that so important changes should be marked with the Accessibility label and tested extensively _also with keyboard only_ to make sure there are no regression.

I'd suggest to consider to replicate the Classic editor behavior. Pressing Cmd+K on an existing link should make the link toolbar appear (and get focused) in edit mode.

I've checked only the paragraph block, this should be checked for all the blocks that use the link toolbar.

Aside:
there's one more bit missing comparing the behavior with the Classic editor:
- in Gutenberg there's the need to select the whole linked word(s)
- in the Classic editor, placing the cursor within the linked word(s) is enough to edit the whole link

### PR DESCRIPTION
**Pull request by talldan**
## Description
 Fixes #8266 by displaying the link popover whenever the caret is positioned within link formatting. As discussed in the issue, the agreed upon approach also involved displaying the toolbar whenever the caret is positioned within any formatting.

Also fixes #3350.

Changes:
- Add core/editor state handling for storing whether caret is positioned within formatting.
- Adjust toolbar rendering logic to show toolbar when caret is positioned within formatting.
- Add e2e tests to ensure regressions don't occur.

## How has this been tested?
- e2e tests
- manual testing

## Screenshots 
toolbar-formatting

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: packages/editor/src/components/rich-text/index.js [hunk 1]
```diff
@@ -426,7 +426,13 @@ export class RichText extends Component {
 			return;
 		}
 
-		const { start, end } = this.createRecord();
+		const { start, end, formats } = this.createRecord();
```
Comment (iseulde) [inline packages/editor/src/components/rich-text/index.js]: `createRecord` creates a new record form the DOM. `getRecord` gets the current record from props. Also I think this might be better to do in onChange right before or after you update the global state. You have direct access to the record there. Thanks!

File: packages/editor/src/components/block-list/block.js [hunk 2]
```diff
@@ -399,7 +400,7 @@ export class BlockListBlock extends Component {
 		// We render block movers and block settings to keep them tabbale even if hidden
 		const shouldRenderMovers = ! isFocusMode && ( isSelected || hoverArea === 'left' ) && ! showEmptyBlockSideInserter && ! isMultiSelecting && ! isPartOfMultiSelection && ! isTypingWithinBlock;
 		const shouldShowBreadcrumb = ! isFocusMode && isHovered && ! isEmptyDefaultBlock;
-		const shouldShowContextualToolbar = ! hasFixedToolbar && ! showSideInserter && ( ( isSelected && ! isTypingWithinBlock ) || isFirstMultiSelected );
+		const shouldShowContextualToolbar = ! hasFixedToolbar && ! showSideInserter && ( ( isSelected && ( ! isTypingWithinBlock || isCaretWithinFormattedText ) ) || isFirstMultiSelected );
```
Comment (talldan) [inline packages/editor/src/components/block-list/block.js]: These bools scare me - might be worth refactoring them into functions or something?

File: packages/editor/src/components/rich-text/index.js (hunk 1 above)
Comment (talldan) [reply packages/editor/src/components/rich-text/index.js]: looks like onChange only triggers when typing instead of when using cursor keys or changing selection with the mouse like I need.

The createRecord was there before, should it be getRecord instead?

Comment (iseulde) [reply packages/editor/src/components/rich-text/index.js]: Oh, never mind then, I only saw the green line. :) Then this looks good, sorry!

Comment (talldan) [reply packages/editor/src/components/rich-text/index.js]: No worries - thanks for taking a look. 😄

File: docs/data/data-core-editor.md [hunk 3]
```diff
@@ -1624,6 +1636,14 @@ Returns an action object used in signalling that the user has begun to type.
 
 Returns an action object used in signalling that the user has stopped typing.
 
+### enterFormattedText
+
+Returns an action object used in signalling that the caret has entered formatted text.
+
+### leaveFormattedText
```
Comment (tofumatt) [inline docs/data/data-core-editor.md]: Would this be better-named as `exitFormattedText`? It matches `enterFormattedText` more, and the docs confused me at first because I read "left" as in "left/right" not "left/leave".

File: test/e2e/specs/links.test.js [hunk 4]
```diff
@@ -388,4 +388,36 @@ describe( 'Links', () => {
 		await page.keyboard.press( 'Escape' );
 		expect( await page.$( '.editor-url-popover' ) ).toBeNull();
 	} );
+
+	it( 'can be modified using the keyboard once a link has been set', async () => {
```
Comment (tofumatt) [inline test/e2e/specs/links.test.js]: ❤️ for the test!

**Review by tofumatt — APPROVED** [review]
Thanks a million, this was the bug that was irking me the most in the merge milestone.

Just one comment about "leave" vs "exit", but after that: 🚢

**Comment by tofumatt** [comment]
Ah, hold off one second, getting some weird behaviour in Firefox, let me see...

**Comment by tofumatt** [comment]
Never mind, my build was buggy; fixed it.

Confirmed to be working for me with the keyboard. Awesome, thanks, ship it! 👍

**Comment by chrisvanpatten** [comment]
The only slightly weird thing is that it looks like the toolbar shows when your cursor is adjacent to the inline token but the token isn't itself highlighted. Not the end of the world, but it jumped out at me.

Either way this looks like an improvement!

**Comment by talldan** [comment]
@noisysocks - I might look at that on a separate PR today. I think it'll be related to this component:
https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/rich-text/format-toolbar/positioned-at-selection.js

It might have been one my past changes that caused it to regress as I put out a fix to make it recalculate position whenever the selection changes.

@chrisvanpatten - I see what you mean, and it works differently on the left and right side of the format. I think I can iron out the left/right inconsistency, but the highlighting of formatting is internal to tinymce (they're called inline boundaries), would have to hook into that somehow.

**Comment by talldan** [comment]
Looking some more the inconsistency with how the toolbar is displayed on the leading and trailing edge of formatted text is a bit of a deeper problem.

Currently if the caret is on the trailing edge of formatted text, the toolbar button to toggle the format doesn't work, but on the leading edge it does work. The logic in this PR for displaying the toolbar is consistent with that. 

I think it's worth filing a separate issue to look at fixing both things at once.

**Comment by afercia** [comment]
Thanks for working on this! Quickly tested, I've noticed the same thing @chrisvanpatten and @talldan mentioned about the highlighting and inline boundaries (not only an inconsistency between left and right behaviors but it's also different from Classic Editor). Regardless, makes perfectly sense to me to try to address that separately. This PR is a good improvement for keyboard users and I'm all for it. Thank you.

File: docs/data/data-core-editor.md (hunk 3 above)
Comment (talldan) [reply docs/data/data-core-editor.md]: 👍 changed this

File: packages/editor/src/components/block-list/block.js [hunk 5]
```diff
@@ -372,6 +372,7 @@ export class BlockListBlock extends Component {
 			isPartOfMultiSelection,
 			isFirstMultiSelected,
 			isTypingWithinBlock,
+			isCaretWithinFormattedText,
```
Comment (youknowriad) [inline packages/editor/src/components/block-list/block.js]: I don't like that the block's wrapper is aware of something very specific to the implementation of a given block (RichText). It doesn't seem like a generic enough solution for me. All blocks don't use RichText. As I see it the block wrapper should work similarily no matter what's the content of the `edit` function.

That said, I'm not familiar enough with the issue and the PR to propose an alternative. (which means I won't block this PR either)

Comment (tofumatt) [reply packages/editor/src/components/block-list/block.js]: That's a good point. I don't have a better solution either off the top of my head, aside from just documenting that it's `RichText` specific, which still isn't great/is the whole problem. 🤷‍♂️

**Comment by youknowriad** [comment]
Let's rebase and merge.

**Comment by tofumatt** [comment]
Rebased and pushed, just waiting on Travis and then I'll get this merged.

**Comment by tofumatt** [comment]
Urgh, something went wrong with the rebase, looking into it now...

**Comment by tofumatt** [comment]
Rebase fixed… will merge when ready 😄

**Comment by aduth** [comment]
Is this new action expected to be so noisy? This is just in writing a few words in a paragraph:

image

There's a decent amount of work performed on each action dispatched. We should try to limit this if we can.

File: packages/editor/src/components/rich-text/index.js [hunk 6]
```diff
@@ -424,7 +424,13 @@ export class RichText extends Component {
...
+
+		if ( formats[ start ] ) {
```
Comment (iseulde) [inline packages/editor/src/components/rich-text/index.js]: Could this be moved in `start !== this.state.start || end !== this.state.end` you think? Could we check right here which flag is set to avoid calling the prop?

**Comment by talldan** [comment]
Thanks for catching that - I've got a PR here to reduce the frequency of dispatches:
https://github.com/WordPress/gutenberg/pull/11235/files
