### PR TITLE
Fixes the FontSizePicker Custom option

### LINKED ISSUE #18716: Remove "Custom" from font size dropdown when custom fonts are disabled
**Describe the bug**
While using `add_theme_support( 'disable-custom-font-sizes' )`, "Custom" option still show up in the font sizes drop down.

**To reproduce**
1. Add `add_theme_support( 'disable-custom-font-sizes' );` as documented.
2. Go to block editor.
3. Create a paragraph block.
4. Try to change the font size from the sidebar controls.
5. "Custom" option still show up in the font sizes drop down.

**Expected behavior**
"Custom" option should be removed when using `add_theme_support( 'disable-custom-font-sizes' )`.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser Chrome
 - Version 78.0.3904.108

**Additional context**
- WP 5.3

### PR DESCRIPTION
**Pull request by JeanDavidDaviet**
Fixes #18716 
This commit prevent the "Custom" option still showing up in the font sizes drop down when  a WordPress theme uses the `add_theme_support( 'disable-custom-font-sizes' )` feature.

## Description
There was no check on the `disableCustomFontSizes`variable. The custom object `{ slug: 'custom', name: __( 'Custom' ) }` was then always added even when not wanted.

## How has this been tested?
Tested with Storybook and npm test

## Types of changes
Bug Fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.

### CODE REVIEW

File: packages/components/src/font-size-picker/index.js [hunk 1]
```diff
@@ -21,14 +21,19 @@ function getSelectValueFromFontSize( fontSizes, value ) {
...
 
-function getSelectOptions( optionsArray ) {
+function getSelectOptions( optionsArray, disableCustomFontSizes ) {
+	if ( ! disableCustomFontSizes ) {
+		optionsArray = [
+			...optionsArray,
+			{ slug: 'custom', name: __( 'Custom' ) },
+		];
+	}
 	return [
```
Comment (ZebulanStanphill) [inline packages/components/src/font-size-picker/index.js]: The return statement is over-complicated since you can just return `optionsArray.map(...)` directly. There's no need to spread the array into another array.

File: packages/components/src/font-size-picker/index.js [hunk 2]
```diff
@@ -21,14 +21,19 @@ function getSelectValueFromFontSize( fontSizes, value ) {
 	return 'normal';
 }
 
-function getSelectOptions( optionsArray ) {
+function getSelectOptions( optionsArray, disableCustomFontSizes ) {
+	if ( ! disableCustomFontSizes ) {
+		optionsArray = [
```
Comment (ZebulanStanphill) [inline packages/components/src/font-size-picker/index.js]: I think this is a bit confusing to read, since at first glance it looks like you are mutating the original array, when in fact you are only changing the function-scoped variable.

Also, I haven't tested the code yet, but wouldn't adding the custom value here cause problems with the `map` callback, which tries to get the `size` property of every `option`? In any case, it seems a bit confusing.

**Review by ZebulanStanphill — CHANGES_REQUESTED** [review]

File: packages/components/src/font-size-picker/index.js (hunk 2 above)
Comment (JeanDavidDaviet) [reply packages/components/src/font-size-picker/index.js]: I don't get what you mean about the mutating part ?
The map function goes over the custom option too, but as the custom size needs to be undefined in `getSelectValueFromFontSize` above, it works. I guess it's not optimal, I would like some suggestion on how to improve this piece of code but trying also to be DRY.

Comment (ZebulanStanphill) [reply packages/components/src/font-size-picker/index.js]: Well, you're not suppose to mutate props/state directly in React components, and setting `optionsArray` kind of looks like a mutation of the original value passed to `getSelectOptions`. It's **not** actually a mutation, since you're only replacing the local variable's reference value with a reference to an entirely new array; if you had used something like `optionsArray.push()` that _would_ have mutated the array. I just thought it looked a little confusing on first glance.

Good point about how `getSelectValueFromFontSize` works. On second examination, I guess rewriting `getSelectOptions` without introducing unnecessary repetition would be harder than I thought. Nevermind. :slightly_smiling_face:

**Review by JeanDavidDaviet — COMMENTED** [review]
I don't understand why this change makes Travis build fail. @ZebulanStanphill ?
They are necessary to update the custom select when the fontsize slider is used.

**Comment by ZebulanStanphill** [comment]
@JeanDavidDaviet The automated tests haven't been working quite right lately, so the failure may be unrelated. Try recommitting the change.

**Comment by JeanDavidDaviet** [comment]
@ZebulanStanphill Thanks, that was it !

**Review by ZebulanStanphill — APPROVED** [review]

**Comment by epiqueras** [comment]
It would be good to add tests for this.

**Comment by JeanDavidDaviet** [comment]
> It would be good to add tests for this.

@epiqueras I won't be home for december, but I sure would like to see the test suite for this feature implemented (or modified) as I'm not a good test writer.
