### PR TITLE
Post publish upload media dialog: handle more block types

### LINKED ISSUE #64899: Post publish upload media dialog: race condition in uploads results in incorrect image replacements
#### The issue

When publishing a post with external images, the upload media dialog in the post publish sidebar is shown. This dialog allows you to upload all the images in your post to the media library, and replace the image URLs in the post accordingly, the goal being to benefit from the various performance improvements that WordPress applies to media library images.

However, choosing to perform this upload can result in a race condition where some of the external images get replaced with the wrong local image (see screen recording).

The resulting attachments all have different IDs, but some of them end up pointing to the same file on disk.

#### The root cause

This took some effort to work out, but here's my understanding of the sequence of events:
- Gutenberg makes several simultaneous POST requests to the REST API (one for each image), all of them with the filename `image.png` (in the case of PNG uploads, such as in the video example).
- In affected configurations, each of these POST requests spawns a WordPress instance (PHP) as a separate OS-level process, with real concurrency.
- PHP handles the file upload into a unique temporary file, correctly, with no collisions.
- Each of the WordPress instances generates a unique attachment ID. This is done via the DB and thus adequately synchronised, resulting in correct, unique attachment IDs.
- Each of the WordPress instances tries to generate a unique filename. This is done by consulting the filesystem, and generating a name of the form `image-N.png` such that `N` is the lowest possible positive integer that isn't already taken.
- The generated filename runs through registered filters, potentially being changed.
- Once the final filename is obtained, the temporary file gets copied over to it.

The issue is that there is no locking mechanism used for the generated filenames, at any level. So if one process consults the filesystem in [the time between another process generating the filename and actually creating the file](https://github.com/WordPress/wordpress-develop/blob/e569967ee45e23186f6aa7f479fcb48a7511436b/src/wp-admin/includes/file.php#L984-L1020), they'll both end up generating the same filename, and we'll end up with them pointing to the same file on disk, overwriting each other.

#### Potential fixes

I'll start by saying that I think we should fix this at the media upload dialog level, since even if a fix eventually lands in Core (e.g. by somehow using the DB to synchronise the filenames), this will still affect every prior version of WordPress and will thus still be a concern for a long time to come.

As such, I can think of several strategies to handle this in the media upload dialog:
- Generating a unique name for each upload on the client side. If instead of uploading every image as `image.<extension>`, we use the block ID, a GUID, or some other sort of unique identifier, we'll bypass the problem by removing the need for the server to generate a unique filename. I believe this is possible in the current codebase, but it may take some changes to `mediaUpload` (haven't looked too closely).
- Uploading all of the files in a single POST request. This way, a single WordPress instance processes all of them, in sequence, avoiding the issue. This has the downside that it's a single large POST request, increasing the chances of it failing with flaky connections.
- Performing all of the uploads in sequence. This fixes the issue, but can be much slower if individual uploads are not enough to saturate the upload bandwidth.
- Using a hybrid solution, where uploads are batched, and batches are uploaded in sequence. It can provide a tradeoff between the previous two approaches, but it's impossible to get the balance right for every connection scenario.
- Adding a delay to the uploads. Instead of firing all requests at once, we could stagger them somewhat, to attempt to give the server enough time to copy the temporary file over to the final filename. This is not a guaranteed fix, and I'm only really suggesting it as a "best effort" approach to attempt to mitigate the issue if none of the other ideas are viable.

#### Folks who may be interested

@Mamaduka , who's been looking at the media upload dialog with me and patiently helping me with code reviews
@youknowriad , who's kindly been guiding me through the Gutenberg codebase
@ellatrix , who likely has the most experience with the media upload dialog, having graciously contributed this great performance feature in the first place

I'm happy to work on a fix myself, but I'd love your opinions on the best approach to solving the issue!

Thank you! 🙏

### Step-by-step reproduction instructions

As a race condition, this can be difficult to reproduce. Some environments, such as the WordPress Playground / `wp-now` seem immune to it; I don't know the technical details there, but I suspect they don't have real concurrency and thus end up with a form of accidental, environment-level synchronisation.

This is how I'm able to reproduce, but your mileage may vary:

- Use `wp-env` to set up a WordPress environment.
- Use any recent version of WordPress.
- Use Gutenberg trunk, just so we're on the same page, but any version with the post publish upload media dialog should do
- Create a new post and add several image blocks to it, each of them pointing to a different external image (added via "Insert from URL"). Be sure to use external images with no CORS restrictions, that can be fetched by the browser with non-opaque response bodies. One option is to use theme or plugin images in your WordPress install, which still count as external, being outside the media library.
- Hit Publish.
- Hit the upload button in the post publish upload media dialog.
- Ensure all of the images uploaded correctly, by ensuring the post publish upload media dialog goes away.
- Examine the post to see if any of the images incorrectly changed (see video).
- Examine the attachments in the media library to see whether they all point to different filenames (correct), or whether some of them point to the same filename (incorrect).

### Screenshots, screen recording, code snippet

Each of the numbers shown is a different external .png image.

https://github.com/user-attachments/assets/522c8118-4b61-4571-93f9-865833762be2

### Environment info

- MacOS Sonoma on an Apple Silicon MacBook Pro
- `wp-env` running WordPress nightly or WordPress 6.6.1 (have tried both)
- Chrome 128 (but it doesn't matter)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by sgomes**
## What?

This PR adds new block types to the post publish upload media dialog, so that external images in them are also considered for upload.

As part of this work, it also deduplicates URLs and generates unique filenames before upload.

This PR fixes #64899.

## Why?

The post publish upload media dialog suggests uploading external media to the media library, for both performance and reliability reasons. However, it currently only does so for Image blocks, which limits its usefulness.

## How?

Custom logic was added to handle `media-text` and `cover` blocks, as well as to generate adequate filenames before uploading.

## Testing Instructions

1. Clear your media library
2. Start a new post in the editor
3. Paste the below HTML into it

<details>
<summary>Post contents</summary>

```html
<!-- wp:image {"width":"127px","height":"auto","sizeSlug":"large"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://s.w.org/style/images/about/WordPress-logotype-standard.png" alt="WordPress Logotype" style="width:127px;height:auto"/></figure>
<!-- /wp:image -->

<!-- wp:cover {"url":"https://s.w.org/style/images/about/WordPress-logotype-standard.png","dimRatio":50,"style":{"color":{}}} -->
<div class="wp-block-cover"><span aria-hidden="true" class="wp-block-cover__background has-background-dim"></span><img class="wp-block-cover__image-background" alt="WordPress Logotype in a cover block" src="https://s.w.org/style/images/about/WordPress-logotype-standard.png" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","fontSize":"large"} -->
<p class="has-text-align-center has-large-font-size">Text</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->

<!-- wp:media-text {"mediaType":"image"} -->
<div class="wp-block-media-text is-stacked-on-mobile"><figure class="wp-block-media-text__media"><img src="https://s.w.org/style/images/about/WordPress-logotype-standard.png" alt="WordPress Logotype in a media-text block"/></figure><div class="wp-block-media-text__content"><!-- wp:paragraph {"placeholder":"Content…"} -->
<p>Text</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:media-text -->

<!-- wp:image {"width":"127px","height":"auto","sizeSlug":"large"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://s.w.org/style/images/about/WordPress-logotype-standard.png?forceDifferentUrl" alt="A separate copy of the WordPress Logotype, with a different URL" style="width:127px;height:auto"/></figure>
<!-- /wp:image -->
```

</details>

4. Hit Publish
5. Ensure that there are four images in the upload list, and that they all have the correct alt text (which will be different for each of them)
    image
6. Hit Upload
7. Ensure that the post visually looks the same
8. Switch to the code editor, and ensure that all the URLs now point to uploaded media (somewhere in `/wp-content/uploads/`)
9. Consult your media library
10. Ensure exactly two images were uploaded, and that they're named `WordPress-logotype-standard.png` and `WordPress-logotype-standard-<some UUID>.png`. The second file is expected because we used a different URL (via a query parameter) on the last block, and it's expected to have the UUID for deduplication of the filename.

### Testing Instructions for Keyboard
N/A, no UI changes.

### CODE REVIEW

File: packages/editor/src/components/post-publish-panel/media-util.js [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+		if ( mime.startsWith( 'video/' ) ) {
+			extension = 'mp4';
+		}
+	}
+
+	// If all else fails, try an empty extension.
+	// The server will probably reject the upload, but there isn't much
+	// else we can do.
+	return extension || '';
+}
```
Comment (swissspidy) [inline packages/editor/src/components/post-publish-panel/media-util.js]: IMHO this is overkill. We don't need to deal with non-images.

In `fetchMedia` we should already reject anything with a non-image file type.

Second, WordPress doesn't even support some of these file types, like `apng`. And even SVG is only possible with a plugin.

This should be enough:

```js
export function getExtensionFromMimeType( mime ) {
	return mimeType.split( '/' )[ 1 ] || '';
}
```

File: packages/editor/src/components/post-publish-panel/media-util.js [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+				.fetch( url.includes( '?' ) ? url : url + '?' )
+				.then( ( response ) => response.blob() )
+				.then( ( blob ) => {
+					// Not all remote filenames have an extension, but we need to
+					// provide one, or the server is likely to reject the upload.
+					if ( ! extension ) {
+						extension = getExtensionFromMimeType( blob.type );
+					}
+					blob.name = `${ basename }.${ extension }`;
+					return blob;
```
Comment (swissspidy) [inline packages/editor/src/components/post-publish-panel/media-util.js]: [`Blob`](https://developer.mozilla.org/en-US/docs/Web/API/Blob) doesn't have a `name` property. What you want is a [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File) object.

```suggestion
					return blob;
					return new File( [ blob ], `${ basename }.${ extension }`, { type: blob.type } )
```

File: packages/editor/src/components/post-publish-panel/media-util.js [hunk 3]
```diff
@@ -0,0 +1,120 @@
...
+ * External dependencies
+ */
+import { v4 as uuid } from 'uuid';
+
+/**
+ * WordPress dependencies
+ */
+import { getFilename } from '@wordpress/url';
+
+// Generate a list of unique filenames given a list of URLs.
```
Comment (swissspidy) [inline packages/editor/src/components/post-publish-panel/media-util.js]: Why no jsdoc? :-)

File: packages/editor/src/components/post-publish-panel/media-util.js [hunk 4]
```diff
@@ -0,0 +1,120 @@
...
+		}
+	}
+
+	// If all else fails, try an empty extension.
+	// The server will probably reject the upload, but there isn't much
+	// else we can do.
+	return extension || '';
+}
+
+// Returns an array of { url, blobPromise } objects, where the promise
```
Comment (swissspidy) [inline packages/editor/src/components/post-publish-panel/media-util.js]: Why no jsdoc? :-)

File: packages/editor/src/components/post-publish-panel/media-util.js [hunk 5]
```diff
@@ -0,0 +1,120 @@
...
+		( { url, basename, extension } ) => {
+			const blobPromise = window
+				.fetch( url.includes( '?' ) ? url : url + '?' )
+				.then( ( response ) => response.blob() )
+				.then( ( blob ) => {
+					// Not all remote filenames have an extension, but we need to
+					// provide one, or the server is likely to reject the upload.
+					if ( ! extension ) {
+						extension = getExtensionFromMimeType( blob.type );
+					}
```
Comment (swissspidy) [inline packages/editor/src/components/post-publish-panel/media-util.js]: We should not trust the `extension` as determined by the URL. Only the one we get ourselves based on the actual blob's mime type.

File: packages/editor/src/components/post-publish-panel/media-util.js [hunk 6]
```diff
@@ -0,0 +1,120 @@
...
+/**
+ * WordPress dependencies
+ */
+import { getFilename } from '@wordpress/url';
+
+// Generate a list of unique filenames given a list of URLs.
+// We want all basenames to be unique, since sometimes the extension
+// doesn't reflect the mime type, and may end up getting changed by
+// the server, on upload.
+export function generateUniqueFilenames( urls ) {
```
Comment (swissspidy) [inline packages/editor/src/components/post-publish-panel/media-util.js]: As per my other comment we should not assume any extension here in this function.

We could just return a simple url=>basename object (`Record< url, basename >`) here instead of an object for each URL. Seems like an odd data structure choice

**Review by swissspidy — COMMENTED** [review]
Some initial comments after a quick look, will do some in-depth testing later

File: packages/editor/src/components/post-publish-panel/media-util.js (hunk 1 above)
Comment (sgomes) [reply packages/editor/src/components/post-publish-panel/media-util.js]: This may well be overkill, and perhaps some simplification is in order 👍 I think your suggestion may be going a bit too far in the opposite direction, though.

Wouldn't it be best for us to code a bit defensively here? I'm not sure I like the scenario where the user adds a plugin to enable SVG support and ends up trying to upload filename `image.svg+xml` 😕

File: packages/editor/src/components/post-publish-panel/media-util.js (hunk 2 above)
Comment (sgomes) [reply packages/editor/src/components/post-publish-panel/media-util.js]: Yes, you're absolutely right 👍 It's best to do the right thing and instantiate an actual `File` object instead of using duck-typing here; who knows what the browser might do behind the scenes.

I took the opportunity to rename the property as well, for clarity.

Done in b93954dba144aa69aa941e134b0d3d89a5eec56c.

File: packages/editor/src/components/post-publish-panel/media-util.js (hunk 1 above)
Comment (swissspidy) [reply packages/editor/src/components/post-publish-panel/media-util.js]: I almost included that in my suggestion, but yes we could add a hardcoded return value for SVGs specifically. It's really an edge case though :-)


```js
export function getExtensionFromMimeType( mime ) {
	if ( 'image/svg+xml' === mimeType ) {
		return 'svg';
	}

	return mimeType.split( '/' )[ 1 ] || '';
}
```

In my media experiments work I also used [`mime/lite`](https://www.npmjs.com/package/mime) in the past, which is more accurate, but IMO that's also overkill here.

File: packages/editor/src/components/post-publish-panel/media-util.js (hunk 5 above)
Comment (swissspidy) [reply packages/editor/src/components/post-publish-panel/media-util.js]: Slight correction:

If the server doesn't send a proper `Content-Type`, then `blob.type` will be empty.

In that case, we can use the extension from the URL as a _fallback_, but not as the first source of truth. So the other way around.

Comment (sgomes) [reply packages/editor/src/components/post-publish-panel/media-util.js]: How do you feel about us simply using the `.png` or `.jpg` extension for all uploads? That would be the simplest option of all, and the server already rewrites the extension if it doesn't match the mime type, via [`wp_check_filetype_and_ext`](https://developer.wordpress.org/reference/functions/wp_check_filetype_and_ext/).

In fact, it's somewhat silly it'll flat-out reject your upload if you don't use an extension, given that it's already checking mime types and generating a proper filename, but that's where we are...

```php
// Check to see if wp_check_filetype_and_ext() determined the filename was incorrect.
if ( $proper_filename ) {
  $file['name'] = $proper_filename;
}

if ( ( ! $type || ! $ext ) && ! current_user_can( 'unfiltered_upload' ) ) {
  return call_user_func_array( $upload_error_handler, array( &$file, __( 'Sorry, you are not allowed to upload this file type.' ) ) );
}
```

Comment (swissspidy) [reply packages/editor/src/components/post-publish-panel/media-util.js]: Yeah that's a good point. Let's keep it simple and then see how that works 👍

File: packages/editor/src/components/post-publish-panel/media-util.js (hunk 3 above)
Comment (sgomes) [reply packages/editor/src/components/post-publish-panel/media-util.js]: Sorry, I'm still somewhat new to the codebase, and it didn't seem to be in widespread use 🙂

File: packages/editor/src/components/post-publish-panel/media-util.js (hunk 6 above)
Comment (sgomes) [reply packages/editor/src/components/post-publish-panel/media-util.js]: The data structure choice makes more sense when considering the extension was being returned as well, and an array of `{ url: string, basename: string, extension: string }` is less cumbersome than `Record< string, { basename: string, extension: string } >`, particularly when iterating through the results.

Since we're dropping the extension, though, I went ahead and made the change. The types and tests look cleaner now, but I'm not sure I prefer the code with all the `Object.entries()` / `Object.fromEntries()` back-and-forth 🤷

File: packages/editor/src/components/post-publish-panel/media-util.js (hunk 1 above)
Comment (sgomes) [reply packages/editor/src/components/post-publish-panel/media-util.js]: We went with a fixed extension instead, and are relying on the server to apply the correct one (see other thread).

File: packages/editor/src/components/post-publish-panel/media-util.js (hunk 4 above)
Comment (sgomes) [reply packages/editor/src/components/post-publish-panel/media-util.js]: Done.

**Comment by sgomes** [comment]
Thank you for the review, @swissspidy! 🙌 I believe I addressed all your comments, so please go ahead and take another look when you get a chance 👍

File: packages/editor/src/components/post-publish-panel/maybe-upload-media.js [hunk 7]
```diff
@@ -25,25 +30,71 @@ function flattenBlocks( blocks ) {
...
+ * Determine whether a block has external media.
+ *
+ * Different blocks use different attribute names (and potentially
+ * different logic as well) in determining whether the media is
+ * present, and whether it's external.
+ *
+ * @param {{name: string, attributes: Object}} block The block.
+ * @return {boolean?} Whether the block has external media
+ */
+function hasExternalMedia( block ) {
```
Comment (mtias) [inline packages/editor/src/components/post-publish-panel/maybe-upload-media.js:43]: just a mental todo, but I'm curious if we should include a new role=media for attributes to leverage stuff like this and the display of little thumbnails on list view. cc @youknowriad @ntsekouras

Comment (youknowriad) [reply packages/editor/src/components/post-publish-panel/maybe-upload-media.js:43]: I think it would be a good idea to declaratively know which attributes are media but there's a few things that we need to know:

 - The type of media (video, image, audio)
 - Whether it's saved or not by checking for the existence of `id` set on the block and it seems the attribute name is not consistent.

Comment (ntsekouras) [reply packages/editor/src/components/post-publish-panel/maybe-upload-media.js:43]: That's something worth exploring for sure, but in order to make some media blocks more semantic, we'd need more than one role. For start we'd need the `id` and the `url`, which could have different names in blocks, like the example below with Image and Media Text.

I'd probably expect to also require a `mediaType` because video and audio have different tag attributes and a preview for example would have to be generated differently. You can see an example of such [handling for media](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/inserter/media-tab/utils.js#L17) tab in inserter.

Finally, right now these attributes have the `content` role and that could simple mean that the new `media` roles are also considered `content`. This would require more testing though, to validate that this is the case for all blocks that use them.

**Comment by swissspidy** [comment]
> Ensure that there are four images in the upload list, and that they all have the correct alt text (which will be different for each of them)

I think I'd expect only two images in the list (`https://s.w.org/style/images/about/WordPress-logotype-standard.png?forceDifferentUrl` and `https://s.w.org/style/images/about/WordPress-logotype-standard.png`), not four. But that wouldn't work well with the block selection on click, as it could be a bit confusing. Maybe in the future blocks using the same image could be grouped together or so?

File: packages/editor/src/components/post-publish-panel/maybe-upload-media.js [hunk 8]
```diff
@@ -88,43 +138,86 @@ export default function PostFormatPanel() {
...
+							} )
+					);
+
+					return [ url, uploadPromise ];
+				}
+			)
+		);
+
+		// Wait for all blocks to be updated with library media.
 		Promise.all(
```
Comment (swissspidy) [inline packages/editor/src/components/post-publish-panel/maybe-upload-media.js]: Should this actually use [`Promise.allSettled()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled) instead? `Promise.all` rejects when the first promise rejects. But if one file rejects it would still be nice if the others continue to upload.

**Comment by sgomes** [comment]
> I think I'd expect only two images in the list

Yes, I agree that would be the most user-friendly approach, in general.

That said, I think changes to the UI go somewhat beyond the scope of this PR. Furthermore, I'm not sure if there would be any a11y concerns, since each image can have its own alt text (the demo HTML I provided does this, to verify everything is plumbed correctly), which means it could be important to display them separately.

File: packages/editor/src/components/post-publish-panel/maybe-upload-media.js (hunk 8 above)
Comment (sgomes) [reply packages/editor/src/components/post-publish-panel/maybe-upload-media.js]: I'm not sure what the original rationale was to use `Promise.all()` in this panel, but I agree it makes sense to let all uploads attempt to finish anyway. This is especially true when you consider that the upload would never be cancelled anyway, as far as I can tell (can't find any `AbortController`); we'd simply prevent the block attributes from being updated.

Done in 874c5f587c64163d88f90a5b336c7f6c153c7b6d.

File: packages/editor/src/components/post-publish-panel/maybe-upload-media.js (hunk 7 above)
Comment (mtias) [reply packages/editor/src/components/post-publish-panel/maybe-upload-media.js:43]: Let's open an issue so we can track that a bit, it will get lost otherwise. There's a lot of things for which media roles would be useful to know.

Comment (ntsekouras) [reply packages/editor/src/components/post-publish-panel/maybe-upload-media.js:43]: Opened an issue for this: https://github.com/WordPress/gutenberg/issues/65186

**Review by swissspidy — APPROVED** [review]

**Comment by sgomes** [comment]
Thank you for the review, @swissspidy! 🙌
