### PR TITLE
Theme JSON: Fix handling of default presets at block level

### LINKED ISSUE #72810: Theme.json: Can't define default presets at the block level
### Description

Found while investigating #72671

The theme.json file allows us to define presets for UIs like colors and font sizes. These presets can be defined at both the global and block levels.

Block-level presets work as expected, but under the following conditions, a preset cannot be used as a theme preset:

- The default preset is disabled.
- The slug matches the default preset.

To avoid this problem, developers are forced to take one of the following two measures.

- Define presets at a global level.
- Use a different slug than the default preset.

### Step-by-step reproduction instructions

The following theme.json files are examples of those that cause problems.

### Duotone

In the image block, only the "Dark grayscale" duotone preset should be available, but no presets are available at all.

```json
{
	"version": 3,
	"appearanceTools": true,
	"settings": {
		"blocks":{
			"core/image": {
				"color": {
					"defaultDuotone": false,
					"duotone": [
						{
							"name": "Dark grayscale",
							"colors": [ "#000000", "#7f7f7f" ],
							"slug": "dark-grayscale"
						}
					]
				}
			}
		}
	}
}
```

### Shadow

In the image block, only the "Natural" shadow preset should be available, but no presets are available at all.

```json
{
	"version": 3,
	"settings": {
		"appearanceTools": true,
		"blocks":{
			"core/image": {
				"shadow": {
					"defaultPresets": false,
					"presets": [
						{
							"name": "Natural",
							"slug": "natural",
							"shadow": "6px 6px 9px rgba(0, 0, 0, 0.2)"
						}
					]
				}
			}
		}
	}
}
```

### Font Size

In the Paragraph block, only the "Small" duotone preset should be available, but no presets are available at all.

```json
{
	"version": 3,
	"settings": {
		"appearanceTools": true,
		"blocks":{
			"core/paragraph": {
				"typography": {
					"defaultFontSizes": false,
					"fontSizes": [
						{
							"name": "Small",
							"slug": "small",
							"size": "13px"
						}
					]
				}
			}
		}
	}
}
```

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
## What?

Fixes: #72810

Prevents an issue where block level presets do not work correctly when:
- Default presets are disabled
- Slug matches the default preset

## Why?

Without this fix theme authors are forced to define presets only at the global level or fudge block-level preset definition slugs. This leads to a poorer end user experience.

## How?

The naming and shape of these preset configs can be a bit confusing but the fix itself is rather straightforward. When merging the block level config for default presets is preferred, only falling back to the global config value if it hasn't been set.

Ensuring the correct default preset config from the block level is used prevents incorrect filtering of theme presets.

## Testing Instructions

For each theme.json example config below:
1. Ensure default presets for the feature being testing is on at the global level
2. Add the block level preset config to your theme.json file
3. Confirm in the editor the expected presets are available generally and at the block level

### Duotone

In the image block, only the "Dark grayscale" duotone preset should be available

```json
{
	"version": 3,
	"appearanceTools": true,
	"settings": {
		"blocks":{
			"core/image": {
				"color": {
					"defaultDuotone": false,
					"duotone": [
						{
							"name": "Dark grayscale",
							"colors": [ "#000000", "#7f7f7f" ],
							"slug": "dark-grayscale"
						}
					]
				}
			}
		}
	}
}
```

### Shadow

In the image block, only the "Natural" shadow preset should be available

```json
{
	"version": 3,
	"settings": {
		"appearanceTools": true,
		"blocks":{
			"core/image": {
				"shadow": {
					"defaultPresets": false,
					"presets": [
						{
							"name": "Natural",
							"slug": "natural",
							"shadow": "6px 6px 9px rgba(0, 0, 0, 0.2)"
						}
					]
				}
			}
		}
	}
}
```

### Font Size

In the Paragraph block, only the "Small" duotone preset should be available

```json
{
	"version": 3,
	"settings": {
		"appearanceTools": true,
		"blocks":{
			"core/paragraph": {
				"typography": {
					"defaultFontSizes": false,
					"fontSizes": [
						{
							"name": "Small",
							"slug": "small",
							"size": "13px"
						}
					]
				}
			}
		}
	}
}
```

## Screenshots or screencast 

|Before|After|
|-|-|
| Screenshot 2025-11-03 at 7 23 34 pm | Screenshot 2025-11-03 at 7 20 28 pm |

### CODE REVIEW

**Comment by aaronrobertshaw** [comment]
I think this is testing ok for me now and ready for an initial review. I'll get the backport PR sorted tomorrow morning.

**Comment by bph** [comment]
@aaronrobertshaw  Thank you so much for jumping at it right away. I tested it with [my gallery aspect ratio preset](https://github.com/WordPress/gutenberg/issues/72671)s and it works as expected now! 🎉
Screenshot 2025-11-03 at 12 51 34

File: phpunit/class-wp-theme-json-test.php [hunk 1]
```diff
@@ -6100,4 +6100,288 @@ public function test_return_block_node_paths_with_variations() {
...
+			'default'
+		);
+		$theme    = new WP_Theme_JSON_Gutenberg(
+			array(
+				'version'  => WP_Theme_JSON_Gutenberg::LATEST_SCHEMA,
+				'settings' => array(
+					'blocks' => array(
+						'core/image' => array(
+							'color' => array(
+								'defaultDuotone' => false,
```
Comment (ramonjd) [inline phpunit/class-wp-theme-json-test.php:6135]: Is it worth adding tests to cover `defaultFontSizes` and `defaultPresets` (shadow) as well? Or is `prevent_override` already covered?

If not, would it be beneficial to verify the fix works across preset types?

**Review by ramonjd — APPROVED** [review]
### Shadow

Before the block support didn't show at all.

| Before  | After |
| ------------- | ------------- |
| Screenshot 2025-11-04 at 12 19 53 pm  | Screenshot 2025-11-04 at 12 15 15 pm  |

### Font sizes

| Before  | After |
| ------------- | ------------- |
| Screenshot 2025-11-04 at 12 02 55 pm  | Screenshot 2025-11-04 at 12 05 11 pm  |

### Duotone

| Before  | After |
| ------------- | ------------- |
| Screenshot 2025-11-04 at 12 02 37 pm  | Screenshot 2025-11-04 at 12 05 04 pm |

This is working as described for me. Thanks for the fix. 

LGTM

I think it'd be worth adding coverage for the other presets just in case.

**Comment by ramonjd** [comment]
Just needs a backport PR too. 👍🏻

File: phpunit/class-wp-theme-json-test.php (hunk 1 above)
Comment (aaronrobertshaw) [reply phpunit/class-wp-theme-json-test.php:6135]: Good question, I don't think it's worth it. 

All preset types use the same code path, just different config from `PRESETS_METADATA`. Additional tests would only catch config typos, not logic bugs.

**Review by t-hamano — APPROVED** [review]
Sorry for the late reply. This pull request appears to be working as expected.

As one edge case, I defined presets with the same slug at both the global and block levels:

```json
{
	"version": 3,
	"settings": {
		"appearanceTools": true,
		"typography": {
			"defaultFontSizes": false,
			"fontSizes": [
				{
					"name": "Small",
					"slug": "small",
					"size": "1em"
				}
			]
		},
		"blocks":{
			"core/paragraph": {
				"typography": {
					"defaultFontSizes": false,
					"fontSizes": [
						{
							"name": "Small",
							"slug": "small",
							"size": "2em"
						}
					]
				}
			}
		}
	}
}
```

The preset UI is displayed correctly at both the global and block levels, and the global styles are also output correctly.

```css
:root {
   --wp--preset--font-size--small: 1em;
}
p {
    --wp--preset--font-size--small: 2em;
}
```

**Comment by aaronrobertshaw** [comment]
Thanks for all the testing and reviews 🙇
