### PR TITLE
Fix issue with jest caching of block.json files

### LINKED ISSUE #16176: Jest aggressively caching block.json files
**Describe the bug**
I had a very frustrating time trying to regenerate fixtures for the full-content tests when working on #16154. It seemed, no matter what I did, the test continued using an old version of the block's attributes to generate the fixtures. This was for the table block, which doesn't have any deprecations. Even deleting the block.json and all related build files didn't have any effect on the test.

Finally, I deleted jest's cache (`npx jest --clearCache`), and that did the trick, the test suddenly worked as expected.

**To reproduce**
1. Run `npm run test-unit test/integration/full-content/full-content.spec.js`
2. Make changes to a block.json file (e.g. attributes)
3. Try regenerating fixtures using `GENERATE_MISSING_FIXTURES=y npm run test-unit test/integration/full-content/full-content.spec.js`
4. Observe that the changes to the block.json file had no effect, the test still had the same result as previous runs (not sure if this will be consistent on every environment, but it was on mine).

### PR DESCRIPTION
**Pull request by talldan**
Fixes #16176

Related https://github.com/WordPress/gutenberg/pull/16150

## Short description

This PR fixes the way jest caches block.json contents by ensuring the cache is invalidated when the block.json file changes.

## Long description
Block.json files are built by inlining the json as a JavaScript primitive into the index.js file they're imported into using `babel-plugin-inline-json-import`.

This seems to have caused an issue with jest's caching system. When jest builds a cache, it does so by generating a unique key for each file. Json files don't seem to be included in this cache. When a block.json is changed, jest seems to just look at the block's index.js source, and generates the same cache key because it hasn't changed. This means that often when adding new attributes to a block, the test results can be inaccurate because the built index.js still contains the old version of the block.json.

This PR fixes the issue by ensuring that jest generates a cache key for the block index.js that incorporates the contents of the block.json too.

## How has this been tested?
1. Run `npm run test-unit test/integration/full-content/full-content.spec.js`
2. Observe that the tests pass
3. Open up the paragraph block's block.json and delete all the attributes
4. Run `npm run test-unit test/integration/full-content/full-content.spec.js`

#### Expected Result (what happens on this branch)
The tests for the paragraph block should fail

#### Actual Result (what happens on master)
The tests still pass because the attributes from the block.json are still cached.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

File: packages/jest-preset-default/scripts/babel-transformer.js [hunk 1]
```diff
@@ -0,0 +1,27 @@
+const fs = require( 'fs' );
+const babelJest = require( 'babel-jest' );
+const babelJestTransformer = babelJest.createTransformer();
+
+module.exports = {
+	...babelJestTransformer,
+	getCacheKey( src, filename, ...args ) {
+		const isBlockIndex = /block-library[\/\\]src[\/\\].+[\/\\]index\.js/.test( filename );
```
Comment (gziolo) [inline packages/jest-preset-default/scripts/babel-transformer.js]: I don't think it's very useful as part of `@wordpress/jest-preset-default` in the current form. The issue is that this check is very specific to the structure of the Gutenberg repository and it will never match with any block definition which is maintained by other projects.

Moving forward, I see 2 ways of handling it. We either move this override to https://github.com/WordPress/gutenberg/blob/master/test/unit/jest.config.js which is local to Gutenberg or we find a way to approach it for all projects which load `block.json`. Given that we want to rework how `block.json` is loaded as proposed in #16088, it might be better to apply this transform to local unit tests config.

Comment (talldan) [reply packages/jest-preset-default/scripts/babel-transformer.js]: Thanks for the feedback. Yep, you're right, it shouldn't be in that package. I've moved it to the appropriate place. It still seems to work.

File: test/unit/scripts/babel-transformer.js [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+		if ( ! fs.existsSync( blockJSONFilename ) ) {
+			return babelJestTransformer.getCacheKey( src, filename, ...args );
+		}
+
+		// If the file is a block index file and there's a block json file, generate the
+		// jest cache key for this file by concatenating the block index and block json
+		// src together. This will result in the cache key changing and the cache being
+		// invalidated for the index when any changes to the json are made.
+		const blockJSONSrc = fs.readFileSync( blockJSONFilename );
+		return babelJestTransformer.getCacheKey( `${ src }\n${ blockJSONSrc }`, filename, ...args );
```
Comment (gziolo) [inline test/unit/scripts/babel-transformer.js]: Interesting, but it fully aligns with what Babel does as far as I can tell :)

**Review by gziolo — APPROVED** [review]
This is great, thanks for working on it @talldan 👍 

I haven't tested myself so your call whether you want me to do it :)

**Comment by talldan** [comment]
Thanks! I'll merge. After all, it'll only affect tests and if we see issues it can be reverted easily enough.
