### PR TITLE
Try: more accessible labels.

### LINKED ISSUE #21840: Default Social Icon labels are inaccessible when used more than once on a page
**Describe the bug**
The default social icon accessible name is usually the name of the icon, e.g. "Mail", "Facebook", etc.

For a screen reader user, this is likely not enough information to understand who/what the icon link is for. This goes from a usability problem to an accessibility error when more than one Social Icons block is used on a page. In that case, we now have duplicate link text going to different pages.

While it is possible for the user to fix this, that is not an ideal solution, especially for a page like "Staff" that might have 30 social icon blocks.

**Expected behavior**
Social Icon accessible name / anchor text should include more contextual information.

- The crudest way to do this would to include the linked URL in the label: Facebook http://facebook.com/example. This is better but only a little.
- If the block can switch to only asking for usernames/handles or this can be derived, then the text could be, "Facebook: Example".
- Better yet, what if the Social Icons block had a "Owner" field (label TBD) that could prefill this for all icons: "Owner on Facebook", "Email Owner". etc.

**Editor version (please complete the following information):**
WordPress 5.4

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

Fixes #21840.

This PR adds the URL as an additional aria label suffix to social links. 

Screenshot 2021-03-09 at 10 20 48
Screenshot 2021-03-09 at 10 20 17

This is a small improvement to the aria label for social links. Users can still add a more verbose label in the interface:

Screenshot 2021-03-09 at 10 21 24

Screenshot 2021-03-09 at 10 20 17

## How has this been tested?

- Insert social links.
- Add a few links.
- Inspect the rendered markup and observe more legible aria labels, such as "Mail: example@example.com" instead of "Mail", and "WordPress: https://wordpress.org/myprofile" instead of just "WordPress".

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/block-library/src/social-link/index.php [hunk 1]
```diff
@@ -19,7 +19,7 @@ function render_block_core_social_link( $attributes, $content, $block ) {
 
 	$service    = ( isset( $attributes['service'] ) ) ? $attributes['service'] : 'Icon';
 	$url        = ( isset( $attributes['url'] ) ) ? $attributes['url'] : false;
-	$label      = ( isset( $attributes['label'] ) ) ? $attributes['label'] : block_core_social_link_get_name( $service );
+	$label      = ( isset( $attributes['label'] ) ) ? $attributes['label'] : block_core_social_link_get_name( $service ) . ": " . $url;
```
Comment (gwwar) [inline packages/block-library/src/social-link/index.php:22]: @swissspidy did you have any thoughts on this one? It's really simple, but I'm not sure if this string building would be an issue.

Comment (aristath) [reply packages/block-library/src/social-link/index.php:22]: Will concatenating strings like that work OK for RTL languages? Maybe we should do something like this instead?
```suggestion
	$label      = ( isset( $attributes['label'] ) ) ? $attributes['label'] : sprintf(
		/* translators: %1$s: Social-network name. %2$s: URL. */
		__( '%1$s: %2$s', 'gutenberg' ),
		block_core_social_link_get_name( $service ),
		$url
	);
```

**Review by aristath — CHANGES_REQUESTED** [review]
I'm not sure about how this would be handled in RTL. Added a comment 👍

**Comment by jasmussen** [comment]
> I'm not sure about how this would be handled in RTL. Added a comment 👍

Nice, that works well for me. Thank you!

**Review by aristath — APPROVED** [review]
Than you for the tweaks!
LGTM 👍

File: packages/block-library/src/social-link/index.php [hunk 2]
```diff
@@ -19,7 +19,12 @@ function render_block_core_social_link( $attributes, $content, $block ) {
 
 	$service    = ( isset( $attributes['service'] ) ) ? $attributes['service'] : 'Icon';
 	$url        = ( isset( $attributes['url'] ) ) ? $attributes['url'] : false;
-	$label      = ( isset( $attributes['label'] ) ) ? $attributes['label'] : block_core_social_link_get_name( $service );
+	$label      = ( isset( $attributes['label'] ) ) ? $attributes['label'] : sprintf(
+		/* translators: %1$s: Social-network name. %2$s: URL. */
+		__( '%1$s: %2$s', 'gutenberg' ),
```
Comment (gziolo) [inline packages/block-library/src/social-link/index.php:24]: Does it really need to be applied in the translation? It looks like `sprintf` is enough.

Comment (aristath) [reply packages/block-library/src/social-link/index.php:24]: If it's not in the translation, then how would an RTL language reverse it, or how would French add a space _before_ the `:`? 🤔

Comment (gziolo) [reply packages/block-library/src/social-link/index.php:24]: I see now it's only used with `aria-label` so it's going to be read by the assistive technology which is yet another set of challenges.
