### PR TITLE
Fix RTL support for datepicker

### LINKED ISSUE #12718: DatePicker doesn't pass isRTL flag to DayPickerSingleDateController when RTL language is used
**Describe the bug**
As reported in [#45524 on Trac](https://core.trac.wordpress.org/ticket/), the arrows are incorrect when using a RTL language.

**To Reproduce**
1. Set language to a RTL language
2. Open editor and set post date

**Expected behavior**
The date picker looks good with a RTL language.

**Screenshots**
Current:
before
Expected:
after

**Additional context**
- https://github.com/airbnb/react-dates/issues/762
- https://github.com/airbnb/react-dates/pull/775

### PR DESCRIPTION
**Pull request by ocean90**
## Description

Instead of converting the styles the `isRTL` flag needs to passed to `DayPickerSingleDateController`.

Fixes #12718.

## How has this been tested?
* Set site language to a RTL language
* Check that the arrows are pointing to the right direction.

### CODE REVIEW

File: packages/components/src/date-time/date.js [hunk 1]
```diff
@@ -13,6 +13,7 @@ import { Component } from '@wordpress/element';
  * Module Constants
  */
 const TIMEZONELESS_FORMAT = 'YYYY-MM-DDTHH:mm:ss';
+const isRTL = () => document.documentElement.dir === 'rtl';
```
Comment (ocean90) [inline packages/components/src/date-time/date.js]: This was also used in https://github.com/WordPress/gutenberg/commit/f91e66ca2bcd9e1e7b97aa39c01f2888fc751712. I think it's fine to use it here too instead of `getEditorSettings().isRTL`.

cc @youknowriad

Comment (youknowriad) [reply packages/components/src/date-time/date.js]: Yes, so the components package shouldn't depend on the editor because these are generic components that can be used anywhere. 

So this approach is a workaround, It's ok.
A better alternative here for me is to have an `isRtl` prop for this component and pass the correct value  from the editor module using `getEditorSettings().isRTL`.  (In the Popover component it was harder to achieve because it's used in too many places).

That said I'm still ok with this.

File: packages/components/src/date-time/style.scss [hunk 2]
```diff
@@ -1,5 +1,7 @@
 // We can't reference this package with ~ because of how Lerna handles packages. 😩
+/*rtl:begin:ignore*/
```
Comment (talldan) [inline packages/components/src/date-time/style.scss]: It might be good to have an explanation in a comment here and a link to the issue.

**Review by talldan — APPROVED** [review]
Tested and confirmed the bug and that the fix works well—thanks for figuring out the issue and solving it 😄
