### PR TITLE
[Block Conversion - Embed]: Fix embed to paragraph transform when caption has rich text formats

### LINKED ISSUE #32265: Embed Blocks: When converting to a paragraph, any styling on caption turns into visible HTML tags in the text
### Steps to reproduce the behavior

1.  Go to the page/post editor
2.  Add any embed block (like YouTube, Vimeo, Twitter etc.)
3.  Add a caption, and add some styling to it (like bold, or color)
4.  Convert the whole block to a Paragraph block

#### What I expected to happen

The styling to either translate to the Paragraph block, or at least be stripped

#### What actually happened

All the html tags pull into the text node on the converted paragraph block

#### Browser / OS version

Chrome 90.0.4430.72  
Windows 10 Home 19042.928

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

Before:  
[embed_caption_before](https://user-images.githubusercontent.com/26772342/115973388-4036d480-a51a-11eb-9f00-2c7baf84d41a.png)

After:  
[embed_caption_after](https://user-images.githubusercontent.com/26772342/115973395-44fb8880-a51a-11eb-903f-fde35c1e3479.png)

Note:
Transferred here from https://github.com/Automattic/wp-calypso/issues/52267

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description

Fixes: https://github.com/WordPress/gutenberg/issues/32265

Currently when we have an `embed` block and we have added rich text formats to its caption (bold, link, color, etc..), if we transform to a `paragraph` all the html tags will be pulled into the text node. This PR solves that.

In addition I have added an `isMatch` for this transform, so it is shown only if we have a `url`. You can test the existing behavior by inserting a `Youtube` block without adding a `url` and observe that the convert to paragraph option is available.

## Testing instructions
1. Go to the page/post editor
2. Add any embed block (like YouTube, Vimeo, Twitter etc.)
3. Add a caption, and add some styling to it (like bold, color, etc.. )
4. Convert the whole block to a Paragraph block

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/block-library/src/embed/transforms.js [hunk 1]
```diff
@@ -33,10 +33,25 @@ const transforms = {
 		{
 			type: 'block',
 			blocks: [ 'core/paragraph' ],
+			isMatch: ( { url } ) => !! url,
 			transform: ( { url, caption } ) => {
-				const link = <a href={ url }>{ caption || url }</a>;
+				let linkText = url;
+				if ( caption?.trim() ) {
+					const captionEl = create( { html: caption } );
+					linkText = toHTMLString( {
```
Comment (ntsekouras) [inline packages/block-library/src/embed/transforms.js]: @ellatrix am I doing some kind of circles here with `create and toHTMLString`? 🤔

Comment (ellatrix) [reply packages/block-library/src/embed/transforms.js]: Why do we want add the URL at all? Why merge two things and potentially cause data loss? Maybe create two paragraphs, a link and the caption?

Comment (ntsekouras) [reply packages/block-library/src/embed/transforms.js]: You're right about the data loss. I've updated to create two paragraphs.

File: packages/block-library/src/embed/transforms.js [hunk 2]
```diff
@@ -33,11 +32,17 @@ const transforms = {
 		{
 			type: 'block',
 			blocks: [ 'core/paragraph' ],
+			isMatch: ( { url } ) => !! url,
 			transform: ( { url, caption } ) => {
-				const link = <a href={ url }>{ caption || url }</a>;
-				return createBlock( 'core/paragraph', {
-					content: renderToString( link ),
```
Comment (ellatrix) [inline packages/block-library/src/embed/transforms.js:39]: Good riddance.

**Review by ellatrix — APPROVED** [review]

File: packages/block-library/src/embed/transforms.js (hunk 1 above)
Comment (ellatrix) [reply packages/block-library/src/embed/transforms.js]: I'm not sure what would be a better setup, but it I think we should definitely avoid linking the caption.

Alternatives:

* A paragraph with the URL, a `<br>` element, and the caption. The nice thing is that it remains a single block.
* An version of the embed block that just displaces the URL text instead of the embed.

File: packages/block-library/src/embed/transforms.js [hunk 3]
```diff
@@ -33,11 +32,17 @@ const transforms = {
...
-				} );
+				const values = [ `<a href="${ url }">${ url }</a>` ];
+				if ( caption?.trim() ) {
+					values.push( caption );
+				}
+				return values.map( ( value ) =>
```
Comment (ellatrix) [inline packages/block-library/src/embed/transforms.js]: Alternatively we could join the values with a `<br>` element so it remains a single block.  See https://github.com/WordPress/gutenberg/pull/32355#discussion_r649176795. I'll let you decide. :)

Comment (ellatrix) [reply packages/block-library/src/embed/transforms.js]: Or even just a space. As long as the caption is not linked I guess. :)

Comment (ntsekouras) [reply packages/block-library/src/embed/transforms.js]: I updated to have a single block with a `<br>`.
