### PR TITLE
Blocks: Register block when invalid value provided for the icon

### LINKED ISSUE #18894: Block type unexpectedly not registered when icon is '' or null in WordPress 5.3
Before WordPress 5.3, it was possible to register a block type using an empty string or null value for `icon`. This would result in the block type using the default 'block' icon.

In WordPress 5.3, a block type registered with `icon: ''` or `icon: null` will trigger this warning:

image

The early return statement added in https://github.com/WordPress/gutenberg/commit/1a7255fb751f1bf519968330c8ca5fcda740c1e5#diff-bcd12caf7289c956a519c4cd8f3f363eR144-R150 causes the block type to not be registered.

My expectation is that a block type with `icon: ''` or `icon: null` would be registered with a default icon.

I took a look at the history of `normalizeIconObject` (https://github.com/WordPress/gutenberg/blame/a71241ca616642f6f590d6982fd82b46d96158ac/packages/blocks/src/api/utils.js#L85-L106). It seems like the last changes are a year old, so I'm not sure why we're only now experiencing this issue?

### PR DESCRIPTION
**Pull request by gziolo**
## Description

Fixes #18894.

> Before WordPress 5.3, it was possible to register a block type using an empty string or null value for `icon`. This would result in the block type using the default 'block' icon.
> 
> In WordPress 5.3, a block type registered with `icon: ''` or `icon: null` will trigger this warning:
> 
> image
> 
> The early return statement added in https://github.com/WordPress/gutenberg/commit/1a7255fb751f1bf519968330c8ca5fcda740c1e5#diff-bcd12caf7289c956a519c4cd8f3f363eR144-R150 causes the block type to not be registered.
> 
> My expectation is that a block type with `icon: ''` or `icon: null` would be registered with a default icon.

## How has this been tested?

I successfully registered and inserted a block with the icon field set to `icon: null` and `icon: ''`. I confirmed that the default block icon was used.

## Types of changes

Bug fix (non-breaking change which fixes an issue). Backward compatibility.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

File: packages/blocks/src/api/registration.js [hunk 1]
```diff
@@ -25,14 +25,13 @@ import {
 import { applyFilters } from '@wordpress/hooks';
 import { select, dispatch } from '@wordpress/data';
 import { _x } from '@wordpress/i18n';
-import { blockDefault } from '@wordpress/icons';
```
Comment (gziolo) [inline packages/blocks/src/api/registration.js:28]: @youknowriad, would it be fine to remove the dependency on `@wordpress/icons` here?

We map `block-default` to the same icon anyway:

https://github.com/WordPress/gutenberg/blob/f42fa3aaaaf8a0a6feca9cced6f9d0e6beb49cdd/packages/block-editor/src/components/block-icon/index.js#L13-L16

Comment (youknowriad) [reply packages/blocks/src/api/registration.js:28]: Sure, the goal was to illuminate string icons in Gutenberg and it seems we may not be there for a long time still.
