### PR TITLE
Inserter: Fix 'Browse All' in Quick Inserter

### LINKED ISSUE #24403: Inserter: Inner blocks not inserted at correct location
Blocks may not be inserted in the correct location when using the following steps:
- Use a layout type block that uses inner blocks and appenders, e.g. Columns block.
- The active or selected block should be in a different location.
- Access the quick inserter (click the **+** block appender in an inner block).
- Click "Browse all" button at the bottom of the quick inserter.
- The main inserter is opened, click a block to insert it.
- The block is inserted at the top level, not where the **+** appender was clicked.

#### Setup
<kbd>Screen Shot 2020-08-06 at 12 28 39</kbd>
#### Click appender to access quick inserter
<kbd>Screen Shot 2020-08-06 at 12 29 03</kbd>
#### Click "Browse all" to access the main inserter
<kbd>Screen Shot 2020-08-06 at 12 29 13</kbd>

#### Pick a block from the main inserter

<kbd>Screen Shot 2020-08-06 at 12 29 34<kbd>

#### The block is not inserted where the appender was clicked

</kbd>Screen Shot 2020-08-06 at 12 29 56

### Context

I believe this is the same issue as described in https://github.com/WordPress/gutenberg/issues/24262. https://github.com/WordPress/gutenberg/pull/24285 closed that issue, but it appears to have addressed an insertion bug in top level blocks, not in inner blocks.

---

**Editor version:**
- WordPress version: 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? **Gutenberg plugin**
- If the Gutenberg plugin is installed, which version is it? **8.7**

Related: https://github.com/WordPress/gutenberg/issues/24402

### PR DESCRIPTION
**Pull request by noisysocks**
Fixes https://github.com/WordPress/gutenberg/issues/24403.
Related to https://github.com/WordPress/gutenberg/pull/24285.

insertion-point

Maintain the insertion point in `@wordpress/block-editor` state when moving from the Quick Inserter to the Inserter.

This fixes a bug (https://github.com/WordPress/gutenberg/issues/24403) where the insertion point is wrong after clicking a block appender (e.g. in a Columns block) and selecting _Browse All_.

Care is taken to not regress a previous bug (https://github.com/WordPress/gutenberg/issues/24262) where the insertion point was wrong after clicking an inline insertion button and selecting _Browse All_.

I re-used the existing `insertionPoint` state tree so as to minimise the amount of new actions and selectors needed. This means we have three insertion point actions:

- `setInsertionPoint`: Sets where the inserter will default to inserting blocks.
- `showInsertionPoint`: Sets where the inserter will default to inserting blocks and display this to the user.
- `hideInsertionPoint`: Hides the insertion point from the user.

The insertion point is cleared when block selection changes. This is needed for the Site Editor where the Inserter is persistent.

### Testing

A regression E2E test has been added. This complements the one added in https://github.com/WordPress/gutenberg/pull/24396.

The manual flows that I checked are:

1. Create a new post.
1. Insert a Columns block with a paragraph in the first column.
1. Insert a block at the end of the post.
1. Click the block appender in the empty column.
1. Select _Browse All_.
1. Click on a block. It should be inserted into the empty column.
1. Click on the inline inserter that appears when you hover over the paragraph in the first column.
1. Select _Browse All_.
1. Click on a block. It should be inserted into the first column.

And:

1. Go to the experimental site editor.
1. Hover over a block and click on the inline inserter button that appears.
1. Select _Browse All_.
1. Click on a block. It should be inserted into the location you clicked on.
1. Hover over a block and click on the inline inserter button that appears.
1. Select _Browse All_.
1. Select a different block somewhere else in the page.
1. Click on a block. It should be inserted after the block you selected.

### CODE REVIEW

File: packages/block-editor/src/components/inserter/hooks/use-insertion-point.js [hunk 1]
```diff
@@ -27,77 +29,75 @@ import { speak } from '@wordpress/a11y';
...
+					);
+				} else {
+					// Insert at the end of the list.
+					_destinationIndex = getBlockOrder(
+						_destinationRootClientId
+					).length;
 				}
+			} else {
+				// Otherwise, we're in "auto mode" where the insertion point is
+				// decided by getBlockInsertionPoint().
```
Comment (youknowriad) [inline packages/block-editor/src/components/inserter/hooks/use-insertion-point.js:77]: Do you think we can simplify further and make this the default mode: Maybe by "setting the insertion point" when we open the inserter (all inserters)

File: packages/block-editor/src/components/inserter/hooks/use-insertion-point.js [hunk 2]
```diff
@@ -27,77 +29,75 @@ import { speak } from '@wordpress/a11y';
...
 			} = select( 'core/block-editor' );
 
-			let destRootClientId = rootClientId;
-			if ( ! destRootClientId && ! clientId && ! isAppender ) {
-				const end = _getBlockSelectionEnd();
-				if ( end ) {
-					destRootClientId = getBlockRootClientId( end );
+			let _destinationRootClientId, _destinationIndex;
+
+			if ( rootClientId || insertionIndex || clientId || isAppender ) {
```
Comment (talldan) [inline packages/block-editor/src/components/inserter/hooks/use-insertion-point.js:54]: There was a relevant comment here about these props - https://github.com/WordPress/gutenberg/pull/25763#discussion_r498059489.

So the idea would to refactor inserters to just use rootClientId and blockIndex. The insertion point state seems to fit well with that, which is nice.

**Review by talldan — COMMENTED** [review]
This is a really tough problem to solve.

Ideally the insertion point would be deterministic, derived from other state, but realistically there's probably no way to do that reliably with the way `Browse all` opens a completely unrelated component.

So this seems like a logical step, and especially so given there's already state used for showing the blue line.

File: packages/block-editor/src/components/inserter/quick-inserter.js [hunk 3]
```diff
@@ -154,26 +154,22 @@ export default function QuickInserter( {
...
-	);
-
-	const previousBlockClientId = useSelect(
-		( select ) =>
-			select( 'core/block-editor' ).getPreviousBlockClientId( clientId ),
-		[ clientId ]
-	);
+			blockIndex: getBlockIndex( clientId, rootClientId ),
+		};
+	}, [] );
```
Comment (ntsekouras) [inline packages/block-editor/src/components/inserter/quick-inserter.js:164]: Should this have `clientId, rootClientId` as dependencies?

File: packages/block-editor/src/components/inserter/hooks/use-insertion-point.js [hunk 4]
```diff
@@ -27,77 +29,75 @@ import { speak } from '@wordpress/a11y';
...
+					// Insert at the end of the list.
+					_destinationIndex = getBlockOrder(
+						_destinationRootClientId
+					).length;
 				}
+			} else {
+				// Otherwise, we're in "auto mode" where the insertion point is
+				// decided by getBlockInsertionPoint().
+
+				_destinationRootClientId = getBlockInsertionPoint()
```
Comment (ntsekouras) [inline packages/block-editor/src/components/inserter/hooks/use-insertion-point.js:79]: We can call `getBlockInsertionPoint` only once here and get its results then.

**Review by ntsekouras — COMMENTED** [review]
Tested and it seems to work well 👍

**Comment by ellatrix** [comment]
What's stopping us from rendering the sidebar inserter in the same react tree as the quick inserter, and creating a sidebar slot to render it there for the DOM? A similar thing is doen for the quick inserter. It as also rendered in a Popover slot, but part of the block react tree.

**Comment by noisysocks** [comment]
> What's stopping us from rendering the sidebar inserter in the same react tree as the quick inserter, and creating a sidebar slot to render it there for the DOM?

You're always [thinking with portals](https://knowyourmeme.com/memes/thinking-with-portals), @ellatrix! 🙂

It's an interesting idea. So in effect, `edit-post`, `edit-site` and `edit-widgets` would provide the `<Fill>` and then it's up to `InserterToggle` (new component) and `BlockAppender` to render the actual `Inserter`.

I'll play with it a little. I don't see why it couldn't work but if working on this bug has taught me anything it's that there are a lot more edge cases than you'd think.

File: packages/block-editor/src/components/inserter/hooks/use-insertion-point.js (hunk 2 above)
Comment (noisysocks) [reply packages/block-editor/src/components/inserter/hooks/use-insertion-point.js:54]: I like that idea. It's definitely a little crazy right now.

**Comment by noisysocks** [comment]
I tried a Slot/Fill approach and ran into a problem regarding closing the inserter sidebar.

Say that a user clicks on a block appender and then selects _Browse All_. `ButtonBlockAppender` renders a full `InserterLibrary` inside a `Fill` adjacent to the `QuickInserter`. This `InserterLibrary` appears in the left sidebar via a `Slot` that exists in `edit-post`'s `Layout`.

Now, say that the user closes the left sidebar by e.g. opening the right sidebar, clicking the ➕ icon, or clicking the X (only appears on mobile).

Or, alternatively, say that the user decides to not insert a block and instead move their cursor to the bottom of the post.

In both cases, we need to unmount the `<Fill><InserterLibrary /></Fill>` from `ButtonBlockAppender ` so that the sidebar closes and the inserter resets to its initial state. How can `ButtonBlockAppender` know to do this, though?

**Comment by ellatrix** [comment]
> In both cases, we need to unmount the <Fill><InserterLibrary /></Fill> from ButtonBlockAppender so that the sidebar closes and the inserter resets to its initial state. How can ButtonBlockAppender know to do this, though?

It would fill only if the appender is focussed right?

**Comment by noisysocks** [comment]
> It would fill only if the appender is focussed right?

No, because focus moves to the left sidebar's search field. If we unmount the `Fill` when the appender is unfocused then users won't be able to search in the full block library.

**Comment by ellatrix** [comment]
Could something like the click outside or focus outside HoC work? I guess the behaviour is much like a popover or modal, just positioned differently.

**Comment by PHuhn** [comment]
Hey:
It seems you have stopped this fix and moved it to Beta/RC.
I cannot speak for anybody but myself, but the latest release added drag-n-drop, and that gives me a work-around for the improper placement, so I can drag into a Group block.

**Comment by tellthemachines** [comment]
Hi, would any of the reviewers of this PR be interested in helping move it forward? It seems we got stuck between the current (working) solution and a (still hypothetical) completely different one. If no one is able to help, what are the thoughts on merging more or less as-is and refactoring later if needed?

**Comment by youknowriad** [comment]
I agree with @tellthemachines that we should favor solving the issue first before further refactorings of how the inserter is rendered.

**Comment by talldan** [comment]
I'm happy to have a go at addressing some of the feedback. 

Probably worth making the selectors/actions unstable if there's the potential for removing them, so I'll do that to.

File: packages/block-editor/src/store/actions.js [hunk 5]
```diff
@@ -523,8 +523,28 @@ export function* insertBlocks(
...
 /**
- * Returns an action object used in signalling that the insertion point should
- * be shown.
+ * Sets the insertion point without showing it to users.
+ *
+ * Components like <Inserter> will default to inserting blocks at this point.
+ *
+ * @param {?string} rootClientId Optional root client ID of block list on
+ *                               which to insert.
+ * @param {?number} index        Index at which block should be inserted.
```
Comment (talldan) [inline packages/block-editor/src/store/actions.js:532]: I'm thinking that these shouldn't be documented as optional, as they have the effect of unsetting the `rootClientId` and `index` in the store (and I'm not sure they should). There's the same issue with `showInsertionPoint`.

Passing a rootClientId without an index or index without rootClientId doesn't seem like good practice. If unsetting the values is required an additional unsetInsertionPoint action could be introduced.

Comment (talldan) [reply packages/block-editor/src/store/actions.js:532]: Passing no args is also not done anywhere in the codebase.

File: packages/block-editor/src/components/inserter/hooks/use-insertion-point.js (hunk 4 above)
Comment (talldan) [reply packages/block-editor/src/components/inserter/hooks/use-insertion-point.js]: Fixed in e707a30

File: packages/block-editor/src/components/inserter/quick-inserter.js (hunk 3 above)
Comment (talldan) [reply packages/block-editor/src/components/inserter/quick-inserter.js]: Fixed in 0ac181d

File: packages/block-editor/src/store/actions.js (hunk 5 above)
Comment (talldan) [reply packages/block-editor/src/store/actions.js]: Turns out `undefined` is used for the top-level block list. I thought this might be one of those places that uses an empty string.

I at least marked index as required.

File: packages/block-editor/src/store/reducer.js [hunk 6]
```diff
@@ -1379,11 +1379,27 @@ export function blocksMode( state = {}, action ) {
...
+				: { rootClientId, index };
+		}
+
+		case 'SHOW_INSERTION_POINT': {
+			const { rootClientId, index } = action;
+			return { rootClientId, index, isVisible: true };
+		}
 
 		case 'HIDE_INSERTION_POINT':
+			return state ? { ...state, isVisible: false } : state;
```
Comment (talldan) [inline packages/block-editor/src/store/reducer.js:1395]: I'm not sure there's any advantage to retaining the rootClientId and index using `...state`, since this is always overwritten by `SHOW_INSERTION_POINT` or `SET_INSERTION_POINT`.

Potentially this could just return `null`.

Comment (talldan) [reply packages/block-editor/src/store/reducer.js]: It simplifies things quite a bit to split it into two reducers:
- `insertionPoint` which has the shape `{ rootClientId, index }` and a default value of `{}`. This is set by `SHOW_INSERTION_POINT` and `SET_INSERTION_POINT` and reset by a bunch of other actions including `HIDE_INSERTION_POINT`.
- `insertionPointVisibility` which is a boolean. This is set to `true` by `SHOW_INSERTION_POINT` and `false` by `HIDE_INSERTION_POINT`.

File: packages/block-editor/src/store/selectors.js [hunk 7]
```diff
@@ -1138,12 +1138,18 @@ export function isCaretWithinFormattedText( state ) {
...
+ *    showInsertionPoint(); or
+ * 2) The point after the current block selection, if there is a selection; or
+ * 3) The point at the end of the block list.
+ *
+ * Components like <Inserter> will default to inserting blocks at this point.
+ *
+ * @param {Object} state Global application state.
  *
- * @return {Object} Insertion point object with `rootClientId`, `index`.
+ * @return {Object} Insertion point object with `rootClientId` and `index`.
```
Comment (talldan) [inline packages/block-editor/src/store/selectors.js:1152]: Previously in this PR `getBlockInsertionPoint` also returned `isVisible`, but I've removed that as it seems to be unused.

**Comment by talldan** [comment]
I need to look into the e2e test failures, seems like I broke something 😄

**Comment by tellthemachines** [comment]
I'm running into a weird bug while testing this branch: 

1. insert a columns block anywhere on the page 
2. click the inserter inside the first column and the click "Browse all"
3. hover over the block directory sidebar
4. all the blocks disappear, leaving the Column block as only option

Seems like the insertion point is being set inside the Columns block instead of the Column.

Other than that, testing in both post and site editors shows this working much better than on master.

**Comment by talldan** [comment]
@tellthemachines Yeah, I can reproduce, slightly different results, the available blocks was initially correct, but then changed to just column when my mouse left the block library.

**Comment by talldan** [comment]
Ah yep, the `HIDE_INSERTION_POINT` action is currently clearing the `insertionPoint` state, and it's called whenever hover leaves a block in the block library. It should just hide the insertion point, but not alter the `rootClientId` or `index`.

938c7a5b75 fixes.

**Review by tellthemachines — APPROVED** [review]
Looks good! Everything is working well now ✅

**Comment by talldan** [comment]
🕺

File: packages/block-editor/src/store/reducer.js (hunk 6 above)
Comment (talldan) [reply packages/block-editor/src/store/reducer.js]: Turns out HIDE_INSERTION_POINT should retain the state as per - https://github.com/WordPress/gutenberg/pull/26443#issuecomment-724435982. The component that calls `showInsertionPoint` must be reusing the existing rootClientId and index.

Splitting into two reducers is a bit friendlier anyway, so a worthwhile change.

**Comment by noisysocks** [comment]
Thanks for picking this up @talldan!
