### PR TITLE
Block Toolbar: Do not hide the block toolbar on mobile

### LINKED ISSUE #5346: Regression: Mobile block toolbar is gone
Steps to reproduce:

- Write a paragraph
- Select it to see block toolbar
- Scale down viewport to < 782px breakpoint

Notice how the block toolbar disappears.

This is `master`:

block-toolbar-disappears

This is 2.2:

### PR DESCRIPTION
**Pull request by youknowriad**
closes #5346 

When introducing the `viewport` module, the block toolbar has been hidden in mobile. I don't know the exact reasons for this but I think we still want it in mobile. So I'm bringing it back here.

**Testing instructions**

 - select a block in mobile
 - The block toolbar should appear
 - Try in both docker and undocker toolbar.

### CODE REVIEW

**Comment by jasmussen** [comment]
You are THE BEEEST! This fixes it for me. 👍👍👍👍

**Comment by aduth** [comment]
Related: #5206

**Comment by aduth** [comment]
So what was intended by `! isMobile( state )` in this condition (removed as part of #5206)?

https://github.com/WordPress/gutenberg/blob/9162e4c66e7ac2dedf2820801e64944c7b9e8b82/edit-post/store/selectors.js#L136-L145

**Comment by aduth** [comment]
So it appears after these changes, the fixed toolbar appears in mobile. But prior to #5206, even if the "Fixed toolbar" setting was somehow selected (it's hidden on smaller displays), it would still show the contextual toolbar.

**Comment by aduth** [comment]
9162e4c66e7ac2dedf2820801e64944c7b9e8b82|`fix/mobile-toolbar`
---|---
before|after

**Comment by aduth** [comment]
Also, the fixed toolbar section lingers when no block is selected:

image

File: edit-post/components/visual-editor/index.js [hunk 1]
```diff
@@ -29,7 +28,7 @@ function VisualEditor( { hasFixedToolbar, isLargeViewport } ) {
 			<WritingFlow>
 				<PostTitle />
 				<BlockList
-					showContextualToolbar={ isLargeViewport && ! hasFixedToolbar }
```
Comment (aduth) [inline edit-post/components/visual-editor/index.js]: I think the issue was a failure to preserve the original condition here.

Previously:

`! isMobile( state ) && isFeatureActive( state, 'fixedToolbar' )`

This should have translated to:

`! isLargeViewport || ! hasFixedToolbar`

https://www.wikiwand.com/en/De_Morgan%27s_laws

Comment (youknowriad) [reply edit-post/components/visual-editor/index.js]: I tried this condition and it's showing two toolbars on small viewports at the same time.

**Comment by youknowriad** [comment]
I need some clarification on the desired behavior here. For me, the current one in this PR is good but is this what we want?

File: edit-post/components/visual-editor/index.js (hunk 1 above)
Comment (aduth) [reply edit-post/components/visual-editor/index.js]: >I tried this condition and it's showing two toolbars on small viewports at the same time.

Only because of the other changes in `HeaderToolbar` on this branch.

Apply this diff to master, and it behaves as I'd expect:

```diff
diff --git a/edit-post/components/visual-editor/index.js b/edit-post/components/visual-editor/index.js
index 1d621863a..a439953e3 100644
--- a/edit-post/components/visual-editor/index.js
+++ b/edit-post/components/visual-editor/index.js
@@ -29,7 +29,7 @@ function VisualEditor( { hasFixedToolbar, isLargeViewport } ) {
 			<WritingFlow>
 				<PostTitle />
 				<BlockList
-					showContextualToolbar={ isLargeViewport && ! hasFixedToolbar }
+					showContextualToolbar={ ! isLargeViewport || ! hasFixedToolbar }
 					renderBlockMenu={ ( { children, onClose } ) => (
 						<Fragment>
 							<BlockInspectorButton onClick={ onClose } />
```

Comment (youknowriad) [reply edit-post/components/visual-editor/index.js]: Gotcha, thanks

**Comment by youknowriad** [comment]
Ok so I guess the idea is to avoid the fixed toolbar entirely on mobile. It should be good now.

**Review by aduth — APPROVED** [review]
👍
