### PR TITLE
Tweak styles of the document actions area

### LINKED ISSUE #26035: Switch to Text component in document actions area
**Describe the bug**
To verify that our text style matches the rest of the application, we should use the `Text` component for rendering text.

### PR DESCRIPTION
**Pull request by noahtallen**
## Description

closes #26035

Tweaking the styles of the document actions area in the site editor. Would love to get the CSS into a final state here (cc @shaunandrews @jameskoster). I also tried using the `Text` component to handle font-related styles, and it's pretty nice to defer that work elsewhere.

I'm mostly unsure about padding and margin for the document actions _dropdown_ area.

Since this uses `Text`, the text style is a bit different in the header:

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by noahtallen** [comment]
cc @shaunandrews @jameskoster @dubielzyk, my thought is that we can use this PR to finalize any "nitpicky" CSS issues for the document actions area. (like making sure it is consistent and all that stuff)

**Comment by noahtallen** [comment]
Also tried adding a basic section heading as in https://github.com/WordPress/gutenberg/pull/24020. Not sure what we're doing to handle colors for css-in-js though!

**Comment by dubielzyk** [comment]
I think the padding between the text and arrow should be reduced by 2-4px, but I think that might mess up the outline on the buttons?

**Comment by noahtallen** [comment]
cc @dubielzyk @shaunandrews we have some options for spacing here, assuming that the distance between the right side of the title and the left side of the chevron are equal in both options.

Option 1. We leave the margin and padding alone, letting the text overlap the button slightly while focused. (36x36px size)
Screen Shot 2020-10-14 at 7 31 21 PM

Option 2. We add 4px of margin, and then adjust the width of the button such that the distance doesn't change because of the extra margin. (28x36px)
Screen Shot 2020-10-14 at 7 31 40 PM

Option 3. Since the button is slightly squished in option2, make the height match the width (resulting in a smaller button. With 4px of margin on the edge, this is now (28x28px)
Screen Shot 2020-10-14 at 7 35 36 PM

We can make the margin a bit less as well, but 4px seems to be the minimum which looks good. Here's 2px of margin along with correct height/width adjustments. This button is 32x32px.
Screen Shot 2020-10-14 at 7 40 32 PM

so I don't forget, the formula for calculating this is `0.5*buttonWidth + leftMargin = 18px`. To adjust buttonWidth properly, you have to set min-width to 0 and then change the padding which defaults to 6px. Note that 18px is the default distance between the left element and the center of the chevron.

**Comment by noahtallen** [comment]
I also want to note that if we switch to the text component like @jameskoster mentioned, then we don't get a grayed-out text, it just defaults to the normal body style. It still contrasts will with the small subheading style though.

File: packages/components/src/text/styles/text-mixins.js [hunk 1]
```diff
@@ -74,8 +75,16 @@ const label = `
 	line-height: 16px;
 `;
 
+const sectionHeading = `
+	${ fontWeightMedium }
+	font-size: 11px;
+	line-height: 1.4;
+	text-transform: uppercase;
+	color: #757575; // $gray-700
```
Comment (david-szabo97) [inline packages/components/src/text/styles/text-mixins.js:83]: `${ G2.gray[ 700 ] }` could work here

**Comment by noahtallen** [comment]
current look:


Screen Shot 2020-10-15 at 3 59 24 PM

**Review by vindl — APPROVED** [review]
LGTM! 🚀
