### PR TITLE
 Fix the isBeingScheduled Selector. 

### LINKED ISSUE #11554: Post set to publish immediately shows a "Schedule" button instead of "Publish" button
<del>Possibly a regression caused by #11489? I'm not sure.</del>

This is a regression caused by a1b647dccabc.

If I create a new post on master that's set to publish immediately, the "schedule" text and not the "publish" text appears for me:

screenshot 2018-11-06 21 46 16

### PR DESCRIPTION
**Pull request by youknowriad**
closes #11554 

Dealing with timezones in JavaScript while the timezone is defined in the server is hard in WordPress. Hopefully, I added some tests to the date module to avoid breakage.

This fixes two issues:

 - Doing `new Date( wpDateString )` is wrong because it will read the date as if it was in the browser's timezone which is wrong. I added a `getDate` function to the date module to apply the WP timezone instead.

 - A small bug introduced in #11418 (where instead of removing a minute offset, we were adding a minute)

### CODE REVIEW

File: packages/date/src/index.js [hunk 1]
```diff
@@ -406,4 +406,20 @@ export function isInTheFuture( dateValue ) {
 	return momentObject.isAfter( now );
 }
 
+/**
+ * Given a string containing a date object formatted using the WP timezone
```
Comment (tofumatt) [inline packages/date/src/index.js]: This documentation is worded a bit oddly; I'll attempt a little rewrite 😄

File: packages/date/src/test/index.js [hunk 2]
```diff
@@ -0,0 +1,37 @@
+/**
+ * Internal dependencies
+ */
+import { isInTheFuture, getDate, setSettings, __experimentalGetSettings } from '../';
+
+describe( 'isInTheFuture', () => {
+	it( 'should return true if the date is in the future', () => {
+		const date = new Date( Number( getDate() ) + ( 1000 * 60 ) ); // 1 minute in the future
```
Comment (tofumatt) [inline packages/date/src/test/index.js]: These trailing comments to me are less clear, something like:

```suggestion
		// Create a Date object 1 minute in the future.
		const date = new Date( Number( getDate() ) + ( 1000 * 60 ) );
```

is a bit clearer. Also what's with the `1000` here? Shouldn't a minute be `60 * 60`? Or am I missing something?

Comment (tofumatt) [reply packages/date/src/test/index.js]: Ooohhhh I saw below it seems this is in milliseconds.

I think that's worth highlighting, because I too forgot that's how this worked. 😅

**Review by tofumatt — APPROVED** [review]
Looks good; I think it's worth tweaking the comments a bit as mentioned but it fixes the bug for me! 👍

File: packages/date/src/index.js [hunk 3]
```diff
@@ -395,7 +395,7 @@ export function dateI18n( dateFormat, dateValue = new Date(), gmt = false ) {
 /**
  * Check whether a date is considered in the future according to the WordPress settings.
  *
- * @param {(Date|string)} dateValue  Date object or string.
+ * @param {string} dateValue Date String or Date object in the Defined WP Timezone.
```
Comment (aduth) [inline packages/date/src/index.js]: So is it a string or an object? The current documentation here sends mixed messaging.
