### PR TITLE
Gallery block: fix bug with link destination default option not being set

### LINKED ISSUE #38302: "image_default_link_type" option doesn't work as of WP 5.9
As of WP 5.9 the `image_default_link_type` option doesn't work for the new galleries. Images do still work.

_Originally posted by @cxlxin in https://github.com/WordPress/gutenberg/issues/25582#issuecomment-1023612983_

### PR DESCRIPTION
**Pull request by glendaviesnz**
## Description
Fixes:  #38302

With the refactored Gallery block the `image_default_link_type` option is not being applied to new Images.

## Testing Instructions

- On test site go to `/wp-admin/options.php` and set `image_default_link_type` to `file`
- Add a new Gallery and add an image to it and make sure the Image is linked to `Media`
- On test site go to `/wp-admin/options.php` and set `image_default_link_type` to `post`
- Add a new Gallery and add an image to it and make sure the Image is linked to `Attachment`
- On test site go to `/wp-admin/options.php` and clear the `image_default_link_type` setting
- Add a new Gallery and add an image to it and make sure the Image does not have a link set

## Screenshots 
Before:
gallery-link-before

After:
gallery-link-after

### CODE REVIEW

File: packages/block-library/src/gallery/utils.js [hunk 1]
```diff
@@ -22,8 +22,17 @@ import {
  */
 export function getHrefAndDestination( image, destination ) {
 	// Need to determine the URL that the selected destination maps to.
-	// Gutenberg and WordPress use different constants so the new link
-	// destination also needs to be tweaked.
+	// Gutenberg and WordPress use different constants so if image_default_link_type
+	// option is set we need to map file -> media and post -> attachment
+	switch ( destination ) {
```
Comment (andrewserong) [inline packages/block-library/src/gallery/utils.js]: Do we need to add the additional `switch` statement?

Could we add these cases to the below switch statement instead, something like:

```
	switch ( destination ) {
		case LINK_DESTINATION_MEDIA:
		case 'file':
			return {
				href: image?.source_url || image?.url, // eslint-disable-line camelcase
				linkDestination: IMAGE_LINK_DESTINATION_MEDIA,
			};
		case LINK_DESTINATION_ATTACHMENT:
		case 'post':
			return {
				href: image?.link,
				linkDestination: IMAGE_LINK_DESTINATION_ATTACHMENT,
			};
```

I was also wondering if it's worth creating another couple of constants in `constants.js` so that these two new ones are centralised? (Though I'm not sure if we'll need to use them elsewhere 🤔)

**Review by andrewserong — APPROVED** [review]
This is testing great for me @glendaviesnz, so I'm giving it the ✅! Thanks for fixing it up. I've just left a couple of optional notes for where we might be able to tighten up the code a little, but it's really just more a code style thing than anything that would impact performance, so it otherwise LGTM.

File: packages/block-library/src/gallery/utils.js (hunk 1 above)
Comment (glendaviesnz) [reply packages/block-library/src/gallery/utils.js]: Yeh, that tidies it up nicely - have pushed that suggestion.

Comment (andrewserong) [reply packages/block-library/src/gallery/utils.js]: Perfect, that looks good to me!
