### PR TITLE
Avoid changing default wpautop priority

### LINKED ISSUE #11691: Embeds after breaks are broken
**Describe the bug**
Embeddable URLs after single line breaks stop working

**To Reproduce**
Create a post from classic editor/pre-gutenberg with content:

```
Some text above
https://www.youtube.com/watch?v=3V9QHBgrPNY

https://www.youtube.com/watch?v=f5KyMNDJE6o
```

View it

**Expected behavior**
Two embedded videos

**Screenshots**
(can get if needed)

**Actual behavior**
One plain URL and one video

**Cause**

https://github.com/WordPress/gutenberg/blob/master/lib/compat.php#L117 runs before https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-embed.php#L32

markup added by `wpautop` prevents regex from matching

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Firefox 
 - Version 63.0.1

**Smartphone (please complete the following information):**

**Additional context**
- Gutenberg version: master branch
- WP Version: 4.9.8

### PR DESCRIPTION
**Pull request by brandonpayton**
## Description
This is a change to avoid problems due to changing the default wpautop priority.

Fixes #11691.

## How has this been tested?

* Created a post in the classic editor and verified auto-embeds render correctly for the following raw content (mentioned in #11691):
```
Some text above
https://www.youtube.com/watch?v=3V9QHBgrPNY

https://www.youtube.com/watch?v=f5KyMNDJE6o
```

* Tested that block content opened in the classic editor retains its paragraphs.
* Tested that non-block content is autop'd.
* Unit tests.

## Types of changes
Take a similar approach to core by removing the `wpautop` filter when block content is detected and subsequently restore it for later applications of the `the_content` filter.

The core changeset used for reference:
https://core.trac.wordpress.org/changeset/43879

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: lib/compat.php [hunk 1]
```diff
@@ -100,22 +100,43 @@ function gutenberg_add_rest_nonce_to_heartbeat_response_headers( $response ) {
...
+ * Ensures `wpautop` is only applied to non-block content.
  *
  * @param  string $content Post content.
- * @return string          Paragraph-converted text if non-block content.
+ * @return string          The unmodified content.
  */
 function gutenberg_wpautop( $content ) {
-	if ( has_blocks( $content ) ) {
-		return $content;
+	// If there are blocks in this content, we shouldn't run wpautop() on it later.
```
[the remark this answers is not in the document]
Comment (brandonpayton) [reply lib/compat.php]: There's no good reason.

I may have made a mental mistake and avoided `do_blocks` because it is only defined conditionally by this plugin, but actually, we only need to worry about avoiding wpautop when we define `do_blocks`. Thanks for asking.

File: lib/blocks.php [hunk 2]
```diff
@@ -174,6 +174,13 @@ function gutenberg_render_block( $block ) {
 	 * @return string          Updated post content.
 	 */
 	function do_blocks( $content ) {
+		// If there are blocks in this content, we shouldn't run wpautop() on it later.
+		$priority = has_filter( 'the_content', 'wpautop' );
+		if ( false !== $priority && doing_filter( 'the_content' ) && has_blocks( $content ) ) {
+			remove_filter( 'the_content', 'wpautop', $priority );
+			add_filter( 'the_content', 'wpautop', $priority + 1 );
```
Comment (brandonpayton) [inline lib/blocks.php]: Immediately re-adding wpautop here. 🤦‍♂️   Good example of why one shouldn't work during time set aside for recharging.

File: lib/blocks.php [hunk 3]
```diff
@@ -187,6 +194,29 @@ function do_blocks( $content ) {
 	add_filter( 'the_content', 'do_blocks', 7 ); // BEFORE do_shortcode() and oembed.
 }
 
+if ( ! function_exists( '_restore_wpautop_hook' ) ) {
+	/**
+	 * If do_blocks() needs to remove wp_autop() from the `the_content` filter,
```
Comment (lkraav) [inline lib/blocks.php]: `wp_autop` ~> `wpautop`

Comment (brandonpayton) [reply lib/blocks.php]: Thanks for catching that. It's fixed now.

**Comment by catehstn** [comment]
This looks like it's ready for another pass, @brandonpayton?

**Comment by brandonpayton** [comment]
> This looks like it's ready for another pass, @brandonpayton?

Yep. It just needs a review.

**Review by noisysocks — APPROVED** [review]
Confirmed that this fixes https://github.com/WordPress/gutenberg/issues/11691 👍 

Could we include the unit test that's in https://core.trac.wordpress.org/changeset/43879?

Will be good to remove all of these workarounds once the Gutenberg plugin relies on having WordPress 5.0 installed.

**Comment by noisysocks** [comment]
This should go into the next _plugin release_. My understanding is that that will be 4.7, not 4.6.

**Comment by mtias** [comment]
@brandonpayton changed it to task because this is retrofitting the plugin with behaviour present in core, and since we are not doing another plugin release yet.

**Comment by brandonpayton** [comment]
ah, maybe I shouldn't be tagging PRs with "bug" at all. thanks for explaining @mtias

**Comment by mtias** [comment]
It's fine :) I just wanted to have a clear overview in the milestone to figure out what needs to be merged before release and what can be added after release but before 5.0.1, if that makes sense.
