### PR TITLE
wp-env: Fix upload directory conflict in phpunit service

### LINKED ISSUE #27922: ENV: Error when trying to map the uploads folder
**Describe the bug**
Error when trying to map the uploads folder in .wp-env.json...
Duplicate mount points: [X:\uploads:/var/www/html/wp-content/uploads:rw, phpunit-uploads:/var/www/html/wp-content/uploads:rw]

**To reproduce**
1. try to map the uploads folder with .wp-env.json
```
{
  "mappings": {
    "wp-content/uploads": "/somefolder/uploads"
   }
}
```
2. Try to start the environment with `wp-env start`

**Expected behavior**
The environment starts with the local uploads folder mapped.

**Editor version:**
- WordPress version:  default from wp-env

**Desktop:**
 - OS: Windows

Seems like wp-env hard codes the uploads folder for phpunit so when a mapping is created for the environment it is now a duplicate.  from the generated docker-compose.yml...
```
      - 'X:\uploads:/var/www/html/wp-content/uploads'
      - 'phpunit-uploads:/var/www/html/wp-content/uploads'
  ```

### PR DESCRIPTION
**Pull request by noahtallen**
Resolves #27922

If a user mounts their own `wp-content/uploads` directory, this conflicts with the upload directory in the phpunit service.

The fix is to mount the user-specified directory instead of the named docker volume if the user has indicated that they want their own upload directory used for the tests service.

If the user wishes to specify their own uploads directory for development, but just have the default internal one used for testing, they can use the environments feature of wp-env:

```json
{
  "env": {
    "development": {
      "mappings": {
        "local/upload/path": "wp-content/uploads"
      }
    }
  }
}
```

## How has this been tested?
Locally, in wp-env, and in unit tests.

## Types of changes
Bug fix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

File: packages/env/test/build-docker-compose-config.js [hunk 1]
```diff
@@ -73,4 +73,46 @@ describe( 'buildDockerComposeConfig', () => {
...
+		const expectedVolumes = [
+			'tests-wordpress:/var/www/html',
+			'/path/to/wp-uploads:/var/www/html/wp-content/uploads',
+		];
+		expect( dockerConfig.services.phpunit.volumes ).toEqual(
+			expectedVolumes
+		);
+	} );
+
+	it( 'should map the default phpunit uploads directory even if the user has specified their own directory only for the development instance', () => {
```
Comment (glendaviesnz) [inline packages/env/test/build-docker-compose-config.js:98]: Just a minor point, would this me clearer as `should map the default phpunit uploads directory even if the user has specified their own directory only for the phpunit service'

**Review by glendaviesnz — APPROVED** [review]
This worked as advertised for me - was able to map a local folder to the `wp-content/uploads` folder in the `wordpress` service and the `phpunit-uploads:` was still added to the  `phpunit` service
