### PR TITLE
Command Palette: fix incorrect path and snackbar message when template part is deleted

### LINKED ISSUE #52023: Command Palette: Nothing appears in the side menu after removing the template part
### Description

When Command Palette is launched in edit mode for a template part, the "Delete template part" action appears by default. When this action is executed, the template part is deleted and the page appears to move, but nothing appears in the side menu.

I expect a transition to the Library or All template parts menu once the template part is removed.

### Step-by-step reproduction instructions

- Create a template part in the site editor.
- Open the Command Palette.
- Click "Delete template part".
- Confirm that nothing appears in the sidebar.

**Note:** The snackbar shows `"undefined" deleted`, but this issue has already been reported on #51969.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/54422211/e02d52f9-f4ff-4bdd-9a99-e647f8c819a3

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes: #52023

## What?
This PR moves you to the Template Parts List page when you delete a template part via Command Palette.

## Why?
When you delete a template part from the Command Palette, the destination `path` is `wp_template_part`. However, with the introduction of Library page in the latest Gutenberg, the following page do not exist.

wp_template_part

## How?
I have changed the path so that when a template part is deleted, it goes to the Template Parts List page (`wp_template_part/all`).
Another idea might be the Library page.

## Testing Instructions

- Create a template part in Library menu.
- Open the Command Palette.
- Click "Delete template part".
- Confirm that you are taken to the Template Parts List page.

**Note:** The snackbar shows `"undefined" deleted`, but this issue has already been reported on #51969.

### trunk

https://github.com/WordPress/gutenberg/assets/54422211/a1687eef-cb07-465e-8dac-24e4f871cf01

### This PR

https://github.com/WordPress/gutenberg/assets/54422211/79a665ce-bf15-4147-88fe-9578ec9808d9

### CODE REVIEW

**Review by aaronrobertshaw — APPROVED** [review]
Thank you for catching this and the quick fix @t-hamano 👍 

This tests well and is definitely a step up over the blank sidebar!

I've left a [comment](https://github.com/WordPress/gutenberg/issues/51969#issuecomment-1612530445) over on the related issue regarding the `undefined` in the snackbar notice.

**Comment by t-hamano** [comment]
Thanks for the review, @aaronrobertshaw!

**Comment by aaronrobertshaw** [comment]
@t-hamano it might be easier (for testing) if we fix the snackbar notice in this PR as well. What do you think?

There are a couple of potential options:

1. Make the `removeTemplate` action handle a title differently based on if it is an object or string
2. Make that action accept an object with only the data required i.e. `{ title, type, id }`. The places we dispatch the action can be updated to pass through the appropriate data.


<details>
<summary>Option 1 - Example diff</summary>

```diff
diff --git a/packages/edit-site/src/store/actions.js b/packages/edit-site/src/store/actions.js
index 8da362ca01..e65eacfc73 100644
--- a/packages/edit-site/src/store/actions.js
+++ b/packages/edit-site/src/store/actions.js
@@ -141,11 +141,18 @@ export const removeTemplate =
 				throw lastError;
 			}
 
+			// Depending on how the entity was retrieved it's title might be
+			// an object or simple string.
+			const templateTitle =
+				typeof template.title === 'string'
+					? template.title
+					: template.title.rendered;
+
 			registry.dispatch( noticesStore ).createSuccessNotice(
 				sprintf(
 					/* translators: The template/part's name. */
 					__( '"%s" deleted.' ),
-					decodeEntities( template.title.rendered )
+					decodeEntities( templateTitle )
 				),
 				{ type: 'snackbar', id: 'site-editor-template-deleted-success' }
 			);

```

</details>


<details>
<summary>Option 2 - Example diff</summary>

```diff
diff --git a/packages/edit-site/src/components/template-actions/index.js b/packages/edit-site/src/components/template-actions/index.js
index 0b54d6ef3e..81e1cc970e 100644
--- a/packages/edit-site/src/components/template-actions/index.js
+++ b/packages/edit-site/src/components/template-actions/index.js
@@ -88,7 +88,11 @@ export default function TemplateActions( {
 								isDestructive
 								isTertiary
 								onClick={ () => {
-									removeTemplate( template );
+									removeTemplate( {
+										title: template.title.rendered,
+										id: template.id,
+										type: template.type,
+									} );
 									onRemove?.();
 									onClose();
 								} }
diff --git a/packages/edit-site/src/store/actions.js b/packages/edit-site/src/store/actions.js
index 8da362ca01..8b397cb265 100644
--- a/packages/edit-site/src/store/actions.js
+++ b/packages/edit-site/src/store/actions.js
@@ -120,12 +120,12 @@ export const addTemplate =
  * @param {Object} template The template object.
  */
 export const removeTemplate =
-	( template ) =>
+	( { title, type, id } ) =>
 	async ( { registry } ) => {
 		try {
 			await registry
 				.dispatch( coreStore )
-				.deleteEntityRecord( 'postType', template.type, template.id, {
+				.deleteEntityRecord( 'postType', type, id, {
 					force: true,
 				} );
 
@@ -133,8 +133,8 @@ export const removeTemplate =
 				.select( coreStore )
 				.getLastEntityDeleteError(
 					'postType',
-					template.type,
-					template.id
+					type,
+					id
 				);
 
 			if ( lastError ) {
@@ -145,7 +145,7 @@ export const removeTemplate =
 				sprintf(
 					/* translators: The template/part's name. */
 					__( '"%s" deleted.' ),
-					decodeEntities( template.title.rendered )
+					decodeEntities( title )
 				),
 				{ type: 'snackbar', id: 'site-editor-template-deleted-success' }
 			);

```

</details>

I don't have strong feelings towards either option, so am open to better ideas. If I had to pick, I'm leaning toward the simpler option 1 so as to not alter the signature for `removeTemplate`.

**Comment by t-hamano** [comment]
Thanks for the advice, @aaronrobertshaw!

> 1. Make the `removeTemplate` action handle a title differently based on if it is an object or string
> 2. Make that action accept an object with only the data required i.e. `{ title, type, id }`. The places we dispatch the action can be updated to pass through the appropriate data.

I also prefer the first option. I think the reason the title property type is different is because the template to be deleted is retrieved by either `useEntityRecords` or `useEditedEntityRecords`. This is because, in the future, when we want to dispatch `removeTemplate` elsewhere, we can simply pass the `template` object as-is as an argument.

I believe both delete from Llist and delete from Command Palette are working as expected.

https://github.com/WordPress/gutenberg/assets/54422211/22c3ca80-90c0-41e6-9fec-c2c78d5d6415

File: packages/edit-site/src/store/actions.js [hunk 1]
```diff
@@ -141,11 +141,18 @@ export const removeTemplate =
 				throw lastError;
 			}
 
+			// Depending on how the entity was retrieved it's title might be
+			// an object or simple string.
+			const templateTitle =
+				typeof template.title === 'string'
+					? template.title
+					: template.title?.rendered;
```
Comment (t-hamano) [inline packages/edit-site/src/store/actions.js:149]: I put `?` just in case. This implementation is also done in the following locations:

https://github.com/WordPress/gutenberg/blob/3fd16c019bee2e0bfa2769c1d68907aba0d482c1/packages/editor/src/store/selectors.js#L1611

**Review by aaronrobertshaw — APPROVED** [review]
Thank you for iterating on this @t-hamano 🙇 

✅ Deleting templates from Templates page works and correct snackbar notice displayed
✅ Deleting templates from command palette works as expected
✅ Deleting from Template Parts page works and correct snackbar notice displayed
✅ Deleting template parts from command palette works

**Comment by t-hamano** [comment]
Thanks for the review, @aaronrobertshaw! I would like to add what I have done additionally in this PR to the commit message and merge it in.

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the update/wp6-3-beta3 branch to get it included in the next release: d739511b77
