### PR TITLE
Site Title: Avoid 403 errors for users with low permissions

### LINKED ISSUE #33003: Inserting a Site Title block causes a 403 error (REST API)
## Description
Found while working on #32868. This is currently blocking #32868, as it causes e2e tests to fail 😕 

Repro'd on current GB `trunk`.

## Step-by-step reproduction instructions
1. Log into WP as a non-admin user (e.g. Editor role).
2. Create a new post.
3. Open your browser devtools bar (Network tab), and clear it.
4. Insert a 'Site Title' block

## Expected behaviour
No network request to fail with a 403.

## Actual behaviour
The network request to `GET http://localhost:8888/index.php?rest_route=%2Fwp%2Fv2%2Fsettings%2F&_locale=user` comes back with a 403 error, with the following response:

```json
{
	"code": "rest_forbidden",
	"message": "Sorry, you are not allowed to do that.",
	"data": { "status": 403 }
}
```

The error is also visible in the devtools console, including a stacktrace. While minimized, it seems to be caused by this line:

https://github.com/WordPress/gutenberg/blob/afee31ee020b8965e811f5d68a5ca8001780af9d/packages/block-library/src/site-title/edit/index.js#L31

## Bonus

If you enter 'Site' into the block picker to locate the Site Title block, there's another network request that fails with a 403:

`GET http://localhost:8888/index.php?rest_route=/wp/v2/users&context=edit&per_page=100&_locale=user` fails with

```json
{
	"code": "rest_forbidden_context",
	"message": "Sorry, you are not allowed to list users.",
	"data": { "status": 403 }
}
```

The stack trace points to the Query Loop block for this one: https://github.com/WordPress/gutenberg/blob/afee31ee020b8965e811f5d68a5ca8001780af9d/packages/block-library/src/query/edit/query-inspector-controls.js#L88-L90.

This latter 403 also causes an `Uncaught (in promise)` error to be logged in the browser console.

cc/ @ntsekouras

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Fixes #33003.

PR fixes `403` errors generated by the Site Title block for non-admin users.

## Why?
The editor should check permission before making requests when data isn't available for everyone.

## How?
I've updated the selector logic to conditionally use (and fetch) data from the settings endpoint or from the read-only index based on user permissions.

### Admin users

The Site Title block should work as before.

### Non-admin users (e.g. Editor or Author role).

1. Log into WP as a non-admin user
2. Create a new post.
3. Open your browser devtools bar (Network tab), and clear it.
4. Insert a 'Site Title' block
5. No network request to fail with a 403.

### E2E Tests
```
npm run test:e2e -- packages/e2e-tests/specs/editor/blocks/site-title.test.js
```

### CODE REVIEW

**Comment by Mamaduka** [comment]
Can anyone confirm if the newly enabled e2e test is passing locally for them?

File: packages/block-library/src/site-title/edit/index.js [hunk 1]
```diff
@@ -71,10 +81,11 @@ export default function SiteTitleEdit( {
 					href="#site-title-pseudo-link"
 					onClick={ ( event ) => event.preventDefault() }
 				>
-					{ readOnlyTitle || __( 'Site Title placeholder' ) }
+					{ decodeEntities( title ) ||
+						__( 'Site Title placeholder' ) }
 				</a>
 			) : (
-				<span>{ title || readOnlyTitle }</span>
+				<span>{ decodeEntities( title ) }</span>
```
Comment (ntsekouras) [inline packages/block-library/src/site-title/edit/index.js]: Not related to this PR, but I guess we should show `Site Title placeholder` as a fallback here too, no?

**Review by ntsekouras — COMMENTED** [review]
Thanks George! The test is passing locally for me..

I'm wondering if it has something to do with the changes when the actual title is fetched and the nodes. Have you tried something like waiting for the node with the site title inside and then check the prop?

And a small nit: in the new test the variable name shouldn't be `editableSiteTitleSelector`.

File: packages/block-library/src/site-title/edit/index.js (hunk 1 above)
Comment (Mamaduka) [reply packages/block-library/src/site-title/edit/index.js]: Good call; we have a similar fallback Site Tagline block. I'm fixing the same issue there as well.

**Comment by Mamaduka** [comment]
I adjusted the e2e tests a bit. Let's see if this works.

The CI test logs also show 400 requests; maybe the failure is related to user swapping.

**Comment by Mamaduka** [comment]
I think we also have a different cause of flakiness for the site title tests. So I'm going to revert the e2e tests state and only merge the 403 error bug fix.

**Review by ntsekouras — APPROVED** [review]
It'd be good to find the root issue for the failing test, but we can land the changes for now. Thanks!
