### PR TITLE
Heading: Add/correct typography examples

### LINKED ISSUE #69810: Typography example does not represent all letter cases
### Description

The example for the selected typography is wrong. The current string is:
AaBbCcDdEeFfGgHhiiJjKkLIMmNnOoPpQakRrssTtUuVVWwXxxYyZzOl23356789X{(…)},2!*&:/A@HELFO™

* no uppercase i s and lowercase v q
* 2x lowercase x
* the number 2 is doubled
* zero is letter O
* 1 . ? © is not represented
*  lowercase L is an uppercase i

### Step-by-step reproduction instructions

1. appearance
2. site editor
3. styles
4. selecting the eye icon

### Screenshots, screen recording, code snippet

It is a Greek one because it came up for a question a Greek user had
It's the same for the international one
Image

### Environment info

WordPress 6.7
Gutenberg dev and 20.6.0
playground

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [x] Classic
- [x] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by timse201**
## What?
fixes #69810

adds 0 (zero), uppercase i s and lowercase v
removes 2x lowercase x and the doubled number 2
1 . ? © and lowercase q is now represented

lowercase L was an I

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]
Good catch, @timse201!

**Comment by timse201** [comment]
I think we should add <, - and >, too.

File: packages/edit-site/src/components/style-book/examples.tsx [hunk 1]
```diff
@@ -115,6 +115,7 @@ function getOverviewBlockExamples(
 
 	if ( getBlockType( 'core/heading' ) ) {
 		const headingBlock = createBlock( 'core/heading', {
+			// translators: Typography example. Your local alphabet, numbers and some common special characters
```
Comment (Mamaduka) [inline packages/edit-site/src/components/style-book/examples.tsx]:
```suggestion
			// translators: Typography example. Your local alphabet, numbers and some common special characters.
```
