### PR TITLE
Disable selection when resizing

### LINKED ISSUE #17313: Multi-selection doesn't get disabled while resizing
**Describe the bug**
Multiselecting isn't disabled while resizing resulting in multiple blocks getting selected.

**To reproduce**
1. Add a new Post
2. Add some text into the default paragraph block.
3. Add an Image block, set an image. 
4. Resize the image for example from the right resizing handle so that the cursor moves on the upper block as well.
5. Observe the results.

**Expected behavior**
Multiselection should be disabled while resizing.

**Information from debugging**
Looks like that's the place where the multiselection happens and `this.props.isSelectionEnabled` is `true` even while resizing:
https://github.com/WordPress/gutenberg/blob/85eaee36845864ff97fd98f71589863533c59386/packages/block-editor/src/components/block-list/index.js#L150-L157

**Screenshots**
Screenshot 2019-09-03 at 15 51 45

In action:
resizing

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome

**Additional context**
- Using latest `master` as of today (6.4 is the last released version)

### PR DESCRIPTION
**Pull request by swissspidy**
## Description

Fixes #17313.

Disables text and block selection when resizing items in the editor.

Not part of the `ResizableBox` component itself as it should also work in different contexts.

## How has this been tested?

Tested by following the steps in #17313 and verifying that no accidental selection happens.

## Screenshots

Demo Video: https://cloudup.com/cNrI6jKgDpl

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by swissspidy** [comment]
It seems that the issue is a bit bigger because of `BLOCK_SELECTION_INITIAL_STATE` and how the `blockSelection` reducer uses it. For example, when I remove blocks via the `REMOVE_BLOCKS` action, state is set to `BLOCK_SELECTION_INITIAL_STATE`, which means selection will be enabled again - even if I didn't intend to.

**Comment by senadir** [comment]
this reintroduces bugs fixed by https://github.com/WordPress/gutenberg/pull/17175 & https://github.com/WordPress/gutenberg/pull/15884
can we possibly find a way to fix both of them? both here & on those PRs?

**Comment by swissspidy** [comment]
@senadir Thanks for pointing to these PRs! I think that should be doable by not using `BLOCK_SELECTION_INITIAL_STATE` in the way it currently is (see my previous comment). Will test it out in a bit.

File: packages/block-library/src/cover/edit.js [hunk 1]
```diff
@@ -212,6 +213,8 @@ class CoverEdit extends Component {
 			noticeUI,
 			overlayColor,
 			setOverlayColor,
+			onResizeStart,
```
Comment (senadir) [inline packages/block-library/src/cover/edit.js]: there is too many `onResizeStart` & `onResizeStop` functions in this file I'm surprised `eslint/no-shadow` didn't stop it, while this is not a problem, can we possibly name it to something else? just to avoid any confusion? and better explain the goal of it? would something like `deselectBlock` & `selectBlock`

**Review by senadir — APPROVED** [review]
I've tested this PR and it works great without breaking other things, I have one comment but it shouldn't block this PR, and I don't have strong opinions about it.

File: packages/block-library/src/cover/edit.js (hunk 1 above)
Comment (swissspidy) [reply packages/block-library/src/cover/edit.js]: Thanks, that's a good point. Will address in a bit.

Comment (swissspidy) [reply packages/block-library/src/cover/edit.js]: Fixed now in the most recent commit. As for the variable names, they were in different components and passed down from one to the other, so not really a shadowing issue.

However, it made me realize that the passed down `onResizeStart` prop wasn't actually used in `ResizableBox`. Renamed the variable names now to make it more clear too.
