### PR TITLE
Fix Navigation Links when post type is not Page or Post

### LINKED ISSUE #28712: Navigation link server renderer tries to `get_post` on links with types other than post/page causing links to not render
## Description

The `get_post` [here](https://github.com/WordPress/gutenberg/pull/27207/files#diff-96cfb99105116cdbf48eface8e7ac4dff062da11f291996bf5748d5a8b90f3e0R109) doesn't work with categories _(and possibly other link types different from post/page?)_, and (might) end up returning an empty string, resulting in the inner link block not rendering in the frontend.

It seems that this went unnoticed because, in a testing environment _(i.e when testing manually using a fresh WP org install)_, the IDs of post/pages and categories are small enough that they overlap, and that ends causing the link to be rendered, causing the false impression it's working as expected.

## Step-by-step reproduction instructions

1. Add a new post or page. We're also assuming there's a post with ID = 1 in your WP instance already; you'll also use the default "Uncategorized" cat (which also has 1 as the ID);
2. Add a horizontal or vertical Navigation block to the page. Add any number of links you'd like, but be sure to add at least one of type "Category" and select the "Uncategorized" cat;
3. View the published page. You'll see that the navigation link for "Uncategorized" is shown;
4. Now edit the post with ID = 1 and set it to private;
5. Go back to and view the test post/page you created earlier. You'll see that the nav link for "Uncategorized" is now gone!

## Expected behavior

I expect any navigation links with a type other than page or post to not be influenced by settings from posts / pages and to show as expected.

## Actual behavior

Navigation links with type other than page / post are not rendered if there's not a post/page with the same ID and or if there is and it's private.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/81248/106830994-c1d24100-6654-11eb-97a3-41cb5a9ed843.mp4

## WordPress information
- WordPress version: 
- Gutenberg version: `9.8.3` and `master` (`537412fd43`)
- Are all plugins except Gutenberg deactivated? Yes.
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes.

## Device information
- Device: Desktop.
- Operating system: Ubuntu Linux 18.04.
- Browser: Firefox 86.0b5 (64-bit).

### PR DESCRIPTION
**Pull request by gwwar**
This adds a check in the navigation link render callback to verify if a link is a post, before checking publish status.

It doesn't look like we have any other examples of this sort of dynamic block test, so I tried to scope the unit as low as possible. Let me know if folks had preferences.

### Before

https://user-images.githubusercontent.com/81248/106830994-c1d24100-6654-11eb-97a3-41cb5a9ed843.mp4

## After

Screen Shot 2021-02-09 at 5 22 52 PM

Screen Shot 2021-02-09 at 5 24 40 PM

Screen Shot 2021-02-09 at 5 25 19 PM

### Manual Testing Instructions

- Add a new post or page. We're also assuming there's a post with ID = 1 in your WP instance already; you'll also use the default "Uncategorized" cat (which also has 1 as the ID);
- Add a horizontal or vertical Navigation block to the page. Add any number of links you'd like, but be sure to add at least one of type "Category" and select the "Uncategorized" cat;
- View the published page. You'll see that the navigation link for "Uncategorized" is shown;
- Now edit the post with ID = 1 and set it to private;
- Verify that the Category link is still visible.

Verify that tests pass:
run `npm run test-unit-php`

Fixes #28712

### CODE REVIEW

File: packages/block-library/src/navigation-link/index.php [hunk 1]
```diff
@@ -105,7 +105,10 @@ function block_core_navigation_link_render_submenu_icon() {
  */
 function render_block_core_navigation_link( $attributes, $content, $block ) {
 	// Don't render the block's subtree if it is a draft.
-	if ( isset( $attributes['id'] ) && is_numeric( $attributes['id'] ) ) {
+	if (
+		isset( $attributes['id'] ) && is_numeric( $attributes['id'] ) &&
+		( 'post' === $attributes['type'] || 'page' === $attributes['type'] )
```
Comment (draganescu) [inline packages/block-library/src/navigation-link/index.php:110]: I wonder here if we should exclude what `get_post ` does not support (tags, categories) because CPT's (e.g. a `book`) should also follow this draft logic but we can't add them all to this condition.

**Review by draganescu — APPROVED** [review]
Apart from [this comment ](https://github.com/WordPress/gutenberg/pull/28892#discussion_r575233563)I think this is good to go.

File: packages/block-library/src/navigation-link/index.php (hunk 1 above)
Comment (draganescu) [reply packages/block-library/src/navigation-link/index.php:110]: As long as this remains on the radar, I am merging this 🚀

**Comment by tellthemachines** [comment]
I'm now getting an error on posts with Navigation blocks in them (both in editor and front end): `Notice: Undefined index: type in /var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/navigation-link.php on line 110`. The issue is that not all Navigation link blocks have the `type` attribute defined 😬

**Comment by talldan** [comment]
I noticed that too, fix here - https://github.com/WordPress/gutenberg/pull/28999.
